### ISSUE TITLE
[Flaky Test] [sig-storage] Subpath Container restart should verify that container can restart successfully after configmaps modified

### ISSUE THREAD

**Issue by thejoycekung** [kubernetes/kubernetes#100194]
#### Which jobs are flaking:
ci-kubernetes-e2e-ubuntu-gce

#### Which test(s) are flaking:
[sig-storage] Subpath Container restart should verify that container can restart successfully after configmaps modified

#### Testgrid link:
https://testgrid.k8s.io/sig-release-master-informing#gce-ubuntu-master-default

#### Reason for failure:
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/subpath.go:131
Mar 12 19:00:24.735: while waiting for container to stabilize
Unexpected error:
    <*errors.errorString | 0xc000246240>: {
        s: "timed out waiting for the condition",
    }
    timed out waiting for the condition
occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/testsuites/subpath.go:870
```

#### Anything else we need to know:
- links to go.k8s.io/triage appreciated
- links to specific failures in spyglass appreciated

Triage shows that this has been flaking quite frequently: https://storage.googleapis.com/k8s-gubernator/triage/index.html?test=Subpath%20Container%20restart%20should%20verify%20that%20container%20can%20restart%20successfully%20after%20configmaps%20modified#674c1b6ceaa54d8d0439

It has flaked in 5 of the last 10 runs:
- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-ubuntu-gce/1370446292399951872
- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-ubuntu-gce/1370415847964676096
- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-ubuntu-gce/1370385395895767040
- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-ubuntu-gce/1370324494312280064
- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-ubuntu-gce/1370233143465873408

/sig storage
/priority important-soon

**Comment by sladyn98** [comment]
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-ubuntu-gce/1377144613701160960
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-ubuntu-gce/1376718323915427840

Noticed some more flakes on this one

**Comment by sladyn98** [comment]
https://testgrid.k8s.io/sig-release-master-informing#gce-ubuntu-master-default&width=5&exclude-non-failed-tests=

**Comment by thejoycekung** [comment]
Yep, looks like this is still flaking quite frequently: https://storage.googleapis.com/k8s-gubernator/triage/index.html?test=Subpath%20Container%20restart%20should%20verify%20that%20container%20can%20restart%20successfully%20after%20configmaps%20modified

Going to re-ping SIG Storage.

**Comment by verult** [comment]
Test is flaking maybe half of the time. This test is failing in gce-ubuntu-master-default - not sure if it's failing in any other dashboards, nor whether this is run anywhere else.

This is a subpath test which
1. Creates a configmap
2. Creates a container that mounts the configmap
3. Fails a liveness probe and waits for the container to restart. 
4. Fixes liveness probe and waits for the container to stop restarting.

The test failed at the last step - the container never stopped restarting. Timeout is 2min.

The liveness probe continuously checks whether a "probeFile" exists, and if it doesn't exist, whether the configmap file contains the modified value. The probeFile essentially acts as a condition which guards the probe from checking the configmap file. The test fails the liveness probe by removing the probeFile without updating the configmap just yet. It then fixes the liveness probe by updating the configmap to the modified value.

So if the container keeps restarting, the configmap was never updated within 2min. This is probably a functional failure rather than a test failure.

**Comment by verult** [comment]
Reproduced this bug. The container failed with: 
```
OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:4 │
│ 49: container init caused \"rootfs_linux.go:58: mounting \\\"/var/lib/kubelet/pods/14f4462e-a3ac-4421-a9b0-2479c5a627d4/volu │
│ me-subpaths/test-volume/test-container-subpath-configmap-8tm5/0\\\" to rootfs \\\"/var/lib/docker/overlay2/43818ce0abbfb334e │
│ bf994083d43821b089826f63404cca9a0e532072f03fc76/merged\\\" at \\\"/var/lib/docker/overlay2/43818ce0abbfb334ebf994083d43821b0 │
│ 89826f63404cca9a0e532072f03fc76/merged/test-volume\\\" caused \\\"no such file or directory\\\"\"": unknown
```

Same as the original issue

**Comment by sladyn98** [comment]
Could we check if the configmap value was updated for sure to rule out that scenario ?

**Comment by verult** [comment]
Will do!

I ran the test in a GKE Ubuntu cluster running 1.19.6 and couldn't reproduce the failure. I'm now trying to run a cluster on GCE with Ubuntu nodes running k8s master, but haven't been successful after trying a number of techniques. If anyone happens to know how to do this let me know; I'll keep asking around otherwise.

**Comment by verult** [comment]
I got a repro on a GKE cluster backed by COS. After the test failed the container ends up in Running state eventually, and the configmap file outputs the expected modified value.

The fix is to increase the test timeout. PR coming up.
