### ISSUE TITLE
Cannnot go get legacy apimachinery packages

### ISSUE THREAD

**Issue by Ruminateer** [kubernetes/kubernetes#100242]
#### What happened:
I need to use legacy apimachinery packages like k8s.io/apimachinery/pkg/apimachinery/registered and k8s.io/apimachinery/pkg/apimachinery/announced. I found the version information on pkg.go.dev and tried to use go get to install the legacy packages but failed. Not sure if I am doing this the wrong way.

#### What you expected to happen:
Go get can install the package.

#### How to reproduce it (as minimally and precisely as possible):
```bash
$ export GOPROXY=https://mirrors.aliyun.com/goproxy/,https://goproxy.io,https://goproxy.cn,direct
$ go get k8s.io/apimachinery@v0.0.0-20190116203031-d49e237a2683
verifying github.com/gogo/protobuf@v0.0.0-20190410021324-65acae22fc9/go.mod: github.com/gogo/protobuf@v0.0.0-20190410021324-65acae22fc9/go.mod: reading https://mirrors.aliyun.com/goproxy/sumdb/sum.golang.org/lookup/github.com/gogo/protobuf@v0.0.0-20190410021324-65acae22fc9: 410 Gone
```

#### Environment:
```
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/zzy/.cache/go-build"
GOENV="/home/zzy/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/zzy/go"
GOPRIVATE=""
GOPROXY="https://mirrors.aliyun.com/goproxy/,https://goproxy.io,https://goproxy.cn,direct"
GOROOT="/usr/lib/go-1.13"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.13/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/zzy/go/src/github.com/Ruminateer/paddle-operator/hostport-allocator/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build763420470=/tmp/go-build -gno-record-gcc-switches"
```

**Comment by fedebongio** [comment]
/cc @sttts @liggitt 
@Ruminateer maybe Stefan or Jordan can help here, but these packages are already removed more than 2 years ago, we are not sure. 
/triage accepted

**Comment by liggitt** [comment]
That version of k8s.io/apimachinery predates go modules: https://github.com/kubernetes/apimachinery/tree/d49e237a2683

That means there is no information in the repo about the specific versions of dependencies desired, so go defaults to fetching the latest version of those dependencies. That is unlikely to work well.

To use go modules with a version that old, you will need to determine the specific version of each dependency desired and specifically `go get` that version. https://github.com/kubernetes/apimachinery/blob/d49e237a2683fa6dc43a86c7b1b766e0219fb6e7/Godeps/Godeps.json can be a starting point for finding that information.

My recommendation would be to use a version of the library new enough to have a go.mod file so that `go get` will understand the desired versions of dependencies and help you resolve them.

/close
