### ISSUE TITLE
volume.kubernetes.io/selected-node never cleared for non-existent nodes on PVC without PVs

### ISSUE THREAD

**Issue by nmiculinic** [kubernetes/kubernetes#100485]
#### What happened:

* PVC was created, & pod consuming this PVC. PVC is using the WaitForFirstConsumer policy. 
* controller with SA `persistent-volume-binder` in `kube-system` namespace edited the PVC, attached the following labels:

```
    volume.beta.kubernetes.io/storage-provisioner: ebs.csi.aws.com
    volume.kubernetes.io/selected-node: ip-10-0-92-212.ec2.internal
```
* PVC is pending phase, it wasn't bound to the PV. 
* The node in question was deleted, by cluster autoscaler 1.20 before the PV was provisioned and attached to the node. 
* The annotation remains
* The https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler v1.20 cannot scale up the node since there's the `volume.kubernetes.io/selected-node` annotation pointing to the deleted node. The cluster autoscaler sees this PVC bound to the Pod already bound to the node, but the node isn't there. 
* The pod stays forever in pending state
* Deleting this annotation allows cluster autoscaler to do its job, scaling up the cluster and the pod gets scheduled on a newly provisioned node. 
* The end. 

#### What you expected to happen:

* Upon node deletion, the `volume.kubernetes.io/selected-node` annotation should be cleared. 

#### How to reproduce it (as minimally and precisely as possible):

* You're playing with race conditions, but the previously mention story should be sometimes replicable. 

#### Environment:
- Kubernetes version (use `kubectl version`):
```
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.6-eks-49a6c0", GitCommit:"49a6c0bf091506e7bafcdb1b142351b69363355a", GitTreeState:"clean", BuildDate:"2020-12-23T22:10:21Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration:
- AWS EKS

**Comment by msau42** [comment]
/assign @verult @jsafrane 
to help look into this.

It looks like we only remove the selected-node annotation on provisioning failure if the [error returned is resource exhausted](https://github.com/kubernetes-csi/external-provisioner/blob/1b9d55dd8c7d8c076abeea1039d261723e2d6efa/pkg/controller/controller.go#L1717). Do you think it makes sense to return rescheduling for any other final error?

**Comment by msau42** [comment]
/triage accepted
@kubernetes/sig-storage-bugs

**Comment by nmiculinic** [comment]
> Do you think it makes sense to return rescheduling for any other final error?

It makes sense removing this annotation if node in question does not exist anymore. If the underlying PV can be attached to some other node, like many cloud PVs can, then it should be allowed to do so.

**Comment by schuerle** [comment]
We also facing this in other, similar situations:
- AWS Spot instances are removed
- Unexpected node terminations

Removing the annotation manually solves the corrupt state and the pods + pvc get placed

(eks 20, csi-driver v1.2.1)

**Comment by jsafrane** [comment]
Sorry, I somehow missed this issue.

> It looks like we only remove the selected-node annotation on provisioning failure if the error returned is resource exhausted. Do you think it makes sense to return rescheduling for any other final error?

I don't want a PVC + Pod to hop around Nodes on every little hiccup in the CSI driver. I think the provisioner should have at least configurable amount of retries (on cmdline). Then it could work for most CSI drivers.

For CSI drivers with the distributed provisioning mode, where each node runs its own external-provisioner, we need something else. If a node's VM is deleted (crashes, ...), there is no external-provisioner running for the node and therefore nothing removes the annotation. Since no in-tree controller (scheduler, PV controller) knows that there is distributed provisioning in action, they cannot remove `AnnSelectedNode`. Therefore it would need to be all other external-provisioners that would need to watch *other* CSINodes and clear the annotation from PVS that are scheduled to wrong nodes. I don't like it at all. @pohly, do you have any idea how to fix it?

In addition, when a CSINode is deleted / looses record of the CSI driver, can we be sure that the external-provisioner does not run on the node? If it was running, it can could be already provisioning a volume while say PV controller tries to remove the annotation, leading to weird races / possible volume leaks.

For the record, I think we could be fine in:
* Static provisioning (e.g. local volumes). I don't remember the binding sequence, do we set / clear `AnnSelectedNode` for non-dynamically provisioned PVCs? Scheduler / PV controller could be fine here.
* In-tree dynamically provisioned volumes. They're being moved to CSI soon.

**Comment by dex4er** [comment]
I believe I had this issue: the PVC with annotation for dead node.

My workaround:

```bash
#!/bin/bash

declare -A nodes
while read node; do
  nodes["${node#node/}"]=exists
done < <(kubectl get nodes -o name)

kubectl get pvc -A -o json |
jq '.items[].metadata | [.namespace, .name, .annotations["volume.kubernetes.io/selected-node"]] | @tsv' -r |
while read namespace name node; do
  if ! [[ ${nodes[$node]} == "exists" ]]; then
    kubectl annotate -n "${namespace}" "pvc/${name}" volume.kubernetes.io/selected-node-
  fi
done
```

**Comment by org-ci-cd** [comment]
Thanks for sharing @dex4er. We just got this issue randomly on 1.21 (it's the first time it happens to us and we've been scaling down instances at night for more than a year, in multiple environments. Surprising ! )

**Comment by sabinayakc** [comment]
Facing similar issue. Autoscaler deleted the node and the PVC had the `volume.kubernetes.io/selected-node` annotations. Then the EBS CSI driver kept on complaining that node didn't exist.

**Comment by jsafrane** [comment]
@verult, are you working on this? Please unassign yourself if not.

**Comment by DanniRiggin** [comment]
We are using Karpenter and have also seen this issue. The workaround of removing the `volume.kubernetes.io/selected-node` annotation works but this is still causing disruption.

**Comment by sunnylovestiramisu** [comment]
This issue is identical to https://github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/issues/121 by my understanding.

A fix has been submitted and the next step if cherry-pick the fix.

**Comment by sunnylovestiramisu** [comment]
The release has been published in external-provisioner:

https://github.com/kubernetes-csi/external-provisioner/releases/tag/v3.3.1
https://github.com/kubernetes-csi/external-provisioner/releases/tag/v3.2.2
https://github.com/kubernetes-csi/external-provisioner/releases/tag/v3.4.1

/close

**Comment by andyzhangx** [comment]
seems this issue still exist, if one node is deleted by auto-scaler, is it csi-attacher's responsibility to clear up the `
volume.kubernetes.io/selected-node` field in pvc, how is this issue fixed by csi-provisioner?

**Comment by andyzhangx** [comment]
I could confirm that when node is deleted, `volume.kubernetes.io/selected-node` still exists for non-existent node with csi-provisioner 3.5.0, I think this requires a fix with csi-attacher instead of csi-provisioner since csi-provisioner is only responsible for create/delete volume, and when node is deleted, there is volume detach call in csi-attacher.

**Comment by dingliu1** [comment]
So, anyone can tell me whether this is really resolved?  In our EKS, once the k8s node is replaced and pods rescheduled to new node, the same error occur.  selected-node tag is not deleted.....

**Comment by dataviruset** [comment]
> So, anyone can tell me whether this is really resolved? In our EKS, once the k8s node is replaced and pods rescheduled to new node, the same error occur. selected-node tag is not deleted.....

We had an outage recently and this was a red herring for us. The selected-node tag was set to a node that had crashed but not yet removed from the K8s control plane because it was unresponsive. I think the storage controller will set the correct selected-node tag once the volume has been mounted by another node.

**Comment by felpasl** [comment]
After update cluster from 1.30 to 1.31 the pods doesn't started with this problem, `volume.kubernetes.io/selected-node` are stucked in deleted nodes, pod's are in pending state forever, gp2 driver's doesn't change to new nodes.

**Comment by rljohnsn** [comment]
We are experiencing the same issue while using EKS K8s v1.30 and the following csi driver from AWS

```
602401143452.dkr.ecr.eu-central-1.amazonaws.com/eks/aws-ebs-csi-driver:v1.41.0
602401143452.dkr.ecr.eu-central-1.amazonaws.com/eks/csi-node-driver-registrar:v2.13.0-eks-1-32-7
```

**Comment by sunnylovestiramisu** [comment]
> We are experiencing the same issue while using EKS K8s v1.30 and the following csi driver from AWS
> 
> ```
> 602401143452.dkr.ecr.eu-central-1.amazonaws.com/eks/aws-ebs-csi-driver:v1.41.0
> 602401143452.dkr.ecr.eu-central-1.amazonaws.com/eks/csi-node-driver-registrar:v2.13.0-eks-1-32-7
> ```

What is the csi-provisioner version?

**Comment by mariastroe** [comment]
@sunnylovestiramisu We're encountering the same issue using EKS v1.31 and the following aws ebs csi driver
```
602401143452.dkr.ecr.eu-west-1.amazonaws.com/eks/aws-ebs-csi-driver:v1.36.0
602401143452.dkr.ecr.eu-west-1.amazonaws.com/eks/csi-attacher:v4.7.0-eks-1-31-5
602401143452.dkr.ecr.eu-west-1.amazonaws.com/eks/csi-node-driver-registrar:v2.12.0-eks-1-31-5
602401143452.dkr.ecr.eu-west-1.amazonaws.com/eks/csi-provisioner:v5.1.0-eks-1-31-5
602401143452.dkr.ecr.eu-west-1.amazonaws.com/eks/csi-resizer:v1.12.0-eks-1-31-5
602401143452.dkr.ecr.eu-west-1.amazonaws.com/eks/csi-snapshotter:v8.1.0-eks-1-31-5
