### ISSUE TITLE
Consider renaming 'Kubernetes Source Code' release artifacts

### ISSUE THREAD

**Issue by tallclair** [kubernetes/kubernetes#100460]
Github automatically adds a `Source code (tar.gz)` artifact to every release, which sounds very similar to the `Kubernetes Source Code` artifact that we generate as the release artifact. Assuming we don't have control over the naming or presence of the autogenerated source code artifact, I think we should consider renaming our published artifact to better disambiguate between the two.

**Comment by BenTheElder** [comment]
We distribute most of our artifacts outside of GitHub. We should probably stop uploading this one entirely.

**Comment by dims** [comment]
cc @kubernetes/release-managers @kubernetes/sig-release-leads

**Comment by justaugustus** [comment]
We've got a thread going on w/ Tim.
/assign

**Comment by dims** [comment]
@justaugustus can you please link so folks can follow the bread crumbs?

( cc @thockin )

**Comment by justaugustus** [comment]
> @justaugustus can you please link so folks can follow the bread crumbs?
> 
> ( cc @thockin )

@dims -- It's currently sensitive. Will share once there's an outcome.

**Comment by dims** [comment]
ACK. thanks for the heads up @justaugustus

**Comment by tallclair** [comment]
@justaugustus I think it's safe to discuss openly at this point.

We had a report that the sha512 hashes on our release artifacts were incorrect. We have confirmed that the mismatch was due to a bug in the release pipeline, and not malicious. This issue here was just a point of confusion that came out of that discussion.

**Comment by dims** [comment]
thanks @tallclair !

**Comment by saschagrunert** [comment]
Going one step back since I think the `kubernetes.tar.gz` exists for historical reasons:
https://github.com/kubernetes/kubernetes/blob/master/build/README.md#releasing

The client and server binaries we're part of this bundle, which is not the case any more:
https://github.com/kubernetes/kubernetes/blob/e8cf412e5ec70081477ad6f126c7f7ef7449109c/build/lib/release.sh#L548
https://github.com/kubernetes/kubernetes/blob/e8cf412e5ec70081477ad6f126c7f7ef7449109c/build/lib/release.sh#L559

So it seems that `kubernetes.tar.gz` is mostly a collection of licenses and scripts. Do we really need it or may we cleanup some code paths and remove it completely?

**Comment by dims** [comment]
+1 to put the word out and remove it completely if no one depends on it.

**Comment by BenTheElder** [comment]
> So it seems that kubernetes.tar.gz is mostly a collection of licenses and scripts. Do we really need it or may we cleanup some code paths and remove it completely?

I'm not confident that CI is not using these versioned scripts, in fact i'm fairly sure that it is. However it would not be pulling it from github.

**Comment by BenTheElder** [comment]
/remove-lifecycle stale
I think this remains as relevant as ever.

**Comment by DiptoChakrabarty** [comment]
Hi @justaugustus @puerco I am part of the bug triage team for v1.24. We noticed that this issue hasn't been updated for a while. Just wanted to check if there is any work planned that would go into this.

**Comment by dims** [comment]
this one keeps moving down the milestones. i don't see any activity since november. So kick the can down the road

/milestone v1.25

**Comment by tallclair** [comment]
That's a question for @justaugustus or @puerco

**Comment by helayoty** [comment]
@justaugustus @puerco 👋 the release 1.25 bug triage Lead. I'm reaching out to see the status of this issue and if we are still targeting the current release. Also, kindly if you can update the priority so we can track it in the future.

**Comment by dims** [comment]
this one keeps moving down the milestones yet again!. i don't see any activity since i moved this down the line. So kick the can down the road:

/milestone clear

(instead of v1.26 as this has been moving down the line for a few releases now)

**Comment by xmudrii** [comment]
@saschagrunert @puerco @BenTheElder What's the current status of this issue? Is there anything that we can do to move this forward?

**Comment by puerco** [comment]
We got new conversations going on during Kubecon on whether we should publish our release binaries on GitHub.

Given that [signing them is imminent](https://github.com/kubernetes/release/pull/2742) and [we now have bucket-to-github support in `publish-release`](https://github.com/kubernetes/release/pull/2707) I think we should rethink now what we publish on the release pages. I think we should start publishing all binaries for one. It is a common practice everywhere and I think users largely expect them to be there.

**Comment by saschagrunert** [comment]
@xmudrii @puerco let's scope the issue to the actual "Kubernetes Source Code" tarball. We can still remove it from what I can see from the discussion.

**Comment by xmudrii** [comment]
I agree with @saschagrunert. Removing the "Kubernetes Source Code" tarball should be as easy as removing this from krel: https://github.com/kubernetes/release/blob/f842735f5e2c72b614aaa21f757c0e4c901cae55/pkg/anago/release.go#L600-L609

However, there are a few questions:

* is it safe to do so?
  * I believe yes, because this "Kubernetes Source Code" tarball is pointing to the GCS bucket, and we'll still continue publishing that tarball to the bucket
  * The link is also available in the changelog, so it's easy to find
* do we need any deprecation period?
  * Considering the above two points, I don't think so.

If you folks agree with that, I can go ahead and create a PR to update krel.

**Comment by saschagrunert** [comment]
@xmudrii I agree on that, but let's drop a note on k-dev that others are aware of the change.

**Comment by xmudrii** [comment]
Update:

- An announcement to proceed with the removal of the "Kubernetes Source Code" artifact has been sent to k-dev: https://groups.google.com/a/kubernetes.io/g/dev/c/mLAxBdgawcM/m/vSew-lLdAgAJ
- PR to remove this artifact from being published: https://github.com/kubernetes/release/pull/2780

Removal will go into effect starting the January patch releases.
