### ISSUE TITLE
[Failing Test] k8s.io/kubernetes/test/integration/job.TestMain (ci-kubernetes-integration-master)

### ISSUE THREAD

**Issue by thejoycekung** [kubernetes/kubernetes#100551]
#### Which jobs are failing:
ci-kubernetes-integration-master

#### Which test(s) are failing:
k8s.io/kubernetes/test/integration/job.TestMain

#### Since when has it been failing:
https://github.com/kubernetes/kubernetes/compare/e71e284b7...d8193c950

#### Testgrid link:
https://testgrid.k8s.io/sig-release-master-blocking#integration-master

#### Reason for failure:
```
I0325 00:27:19.608278  130047 etcd.go:74] etcd already running at http://127.0.0.1:2379
FAIL	k8s.io/kubernetes/test/integration/job	64.998s
```

I can't seem to find a match for `test/integration/job` beyond that?

#### Anything else we need to know:
Most likely related to #100295 as it was merged during that set of commits

Example Spyglass link: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-integration-master/1374827993762893824

/cc @adtac 
/sig apps
/priority critical-urgent
/milestone v1.21

**Comment by adtac** [comment]
FYI: the `etcd already running at http://127.0.0.1:2379` error message is a red herring and isn't the real reason why this test is failing. When the integration tests are run with `make test-integration` instead of `go test`, the mutation detector is also started, which catches a bug in the job controller where we modify the shared cache. This root cause isn't present in the logs, but you can reproduce this bug with the following command:

```
make test-integration WHAT=./test/integration/job KUBE_TEST_VMODULE="''" KUBE_TEST_ARGS="-alsologtostderr=false -logtostderr=false -run=TestSuspendJob -v"
```

Then apply the job controller patch in https://github.com/kubernetes/kubernetes/pull/100553 and re-run the test, you'll see that the test passes.

You'll also notice that `TestSuspendJob` passes with/without the bug fix patch when run with `go test`.

cc @soltysh @alculquicondor @ahg-g

**Comment by puerco** [comment]
Test is back on green. Thanks @adtac !
