### ISSUE TITLE
kubelet liveness probe (to kube-apiserver) has its own account 

### ISSUE THREAD

**Issue by tkashem** [kubernetes/kubernetes#100844]
#### What happened:
kubelet liveness probe receives an HTTP `429 (Too Many Requests)` response because the kube-apiserver is under some load but still functioning:
```
Liveness probe failed: HTTP probe failed with statuscode: 429
```
The above liveness probe error may lead kubelet to restart a busy but "healthy" apiserver instance.

Restart of healthy apiserver instance(s) due to the above scenario is not desirable and to avoid this we wanted to `exempt` ( using API Priority and Fairness configuration) all liveness checks originating from kubelet so these probes never receive `429`. But it looks like, there is no way today to identify the liveness probes originating from kubelet.

This is what a `/healthz` probe looks like in the audit log:
```
{
  "kind": "Event",
  "apiVersion": "audit.k8s.io/v1",
  "level": "RequestResponse",
  "auditID": "af13ff6f-fcd7-444d-8224-0429d8a52b43",
  "stage": "RequestReceived",
  "requestURI": "/healthz",
  "verb": "get",
  "user": {
    "username": "system:anonymous",
    "groups": [
      "system:unauthenticated"
    ]
  },
  "sourceIPs": [
    "10.0.132.119"
  ],
  "userAgent": "kube-probe/1.20",
  "requestReceivedTimestamp": "2021-03-16T20:17:36.069405Z",
  "stageTimestamp": "2021-03-16T20:17:36.069405Z"
}
```

These probe requests appear as `system:anonymous` to kube-apiserver, there is no information in the `user` field to identify whether it's coming from kubelet.
If we exempt all liveness probes coming from `user=system:anonymous` or `group=system:unauthenticated` then we are leaving a window open for a bad actor (no authentication required) to flood the apiserver with these probes.

#### What you expected to happen:
kubelet liveness probes (to kube-apiserver) have their own user/group so we can exclusively `exempt` kubelet probes.

**Comment by tkashem** [comment]
cc @lavalamp @MikeSpreitzer @deads2k

**Comment by liggitt** [comment]
resolved by #100678

/sig node api-machinery
/remove-sig auth

**Comment by lavalamp** [comment]
I don't agree that this is resolved. That's an overly permissive bandaid to get around the lack of a specific user.

/sig auth
/remove-sig api-machinery

**Comment by liggitt** [comment]
not sure whether this is on node (generic identity to liveness probes) or cluster-lifecycle (config of self-hosted kube-apiserver manifests), but I don't think it's sig-auth... the self-hosting kubelet could provision a token and give itself an identity today if it wanted to embed it in the kube-apiserver manifest.

**Comment by lavalamp** [comment]
Hm, that makes sense, but I still feel like the problem overall, that
health checks in existing systems today are indistinguishable from the kind
of request that an unprivileged attacker could make, should be something
SIG Auth cares about and would drive to completion, even if the problem
isn't a missing SIG Auth feature?

**Comment by ehashman** [comment]
I don't understand how this is a Node bug. This seems like an issue with API Priority and Fairness, and the environment in question.

It's possible the API Server could apply different rate limiting rules to `/livez` or whatever is being queried for liveness. But, there is no requirement that an API Server needs to be run as a container under a kubelet, or that a liveness probe needs to be defined. The kubelet is doing its job: it's querying an endpoint, the endpoint fails to return a successful response, the failed responses hit the liveness failure threshold, and the pod is killed.

So, to me this seems like a combination of an issue with the deployment architecture for the API Servers, and potentially how the API Priority and Fairness rules are implemented. It looks like API Machinery [owns that KEP](https://github.com/kubernetes/enhancements/tree/master/keps/sig-api-machinery/1040-priority-and-fairness), so I think we need more input from that SIG.

/sig api-machinery

**Comment by lavalamp** [comment]
It is a node issue because there is no way, from apiserver's perspective, to tell the difference between an anonymous kubelet and an anonymous DDoS-er. The problem is that there is no way to put any identity information into the liveness probe section of a pod.

I doubt that apiserver is the only workload for which this would be handy.

Previously this was solved via the insecure port, which DDoSers would not be able to dial, but SIG Auth is making us get rid of that.

If SIG Node tells us kubelet is never going to do this, then we can close this issue and have to re-introduce something like the old insecure port. But the issue as requested here is not something SIG API Machinery can fix.

/remove-sig api-machinery

**Comment by deads2k** [comment]
In the vast majority of configurations, the kubelet has a client-certificate since it is required for the node authorizer to function.  Since mtls is not replayable, could the kubelet present its client certificate, allowing a pod which participates with in-cluster authentication to identify that it is a kubelet requesting healthz, livez, readyz?

That seems to be low risk, no configuration, no cost for non-participating pods, and allows for identification in normal flows.  For exceptional flows (restarting a cluster without any kubelet client certificates), some amount of grace needs to be provided by static pods (apiserver included), but in steady state an infinite number of healthz, readyz, livez requests can be allowed for the kubelet in particular

**Comment by MikeSpreitzer** [comment]
It's not just P&F, there is the authentication and authorization check too.
I think this is a fair question.  Perhaps the cure suggested here is worse than the disease.

**Comment by lavalamp** [comment]
> Is it cheaper to serve an OK response

It is not just about cheapness, it is also about information leakage -- oh hey look, this random IP address is responding as if it is a Kubernetes cluster!

(also health check isn't free right now -- I seem to recall a PR from you recently improving that :) )

**Comment by MikeSpreitzer** [comment]
Returning a rejection would also reveal a lot of information.

**Comment by lavalamp** [comment]
I agree an APF refection would reveal info. But ideally we'd be able to reject via RBAC -- I guess I actually don't know if authn or authz denials have a goal of no information leaking.

**Comment by SergeyKanzhelev** [comment]
/remove-kind bug
/kind feature

feels like a feature request. If it will be on Node, it needs a KEP.
