### ISSUE TITLE
irun cluster/kube-up.sh error

### ISSUE THREAD

**Issue by cclient** [kubernetes/kubernetes#10082]
root@debian02:~/kubernetes/cluster# KUBERNETES_PROVIDER=ubuntu ./kube-up.sh 

/root/kube/util.sh: line 25: /cluster/common.sh: No such file or directory
Connection to 172.16.231.173 closed.

i echo the  shell common.sh file path
it is "./../cluster/../cluster/common.sh"

**Comment by roberthbailey** [comment]
Some of the scripts may assume you are running them from the `kubernetes` directory. Did you try dropping one level and running `KUBERNETES_PROVIDER=ubuntu ./cluster/kube-up.sh`?

**Comment by cclient** [comment]
while
root@debian02:~/kubernetes# KUBERNETES_PROVIDER=ubuntu cluster/kube-up.sh 

Starting cluster using provider: ubuntu
... calling verify-prereqs
Identity added: /root/.ssh/id_rsa (rsa w/o comment)
... calling kube-up
warning: not enough binaries to build k8s, please run build.sh in cluster/ubuntu first

then i edit the 
root@debian02:~/kubernetes# vim cluster/ubuntu/util.sh
function kube-up {
  KUBE_ROOT=$(dirname "${BASH_SOURCE}")/../..
  source "${KUBE_ROOT}/cluster/ubuntu/${KUBE_CONFIG_FILE-"config-default.sh"}"
  # ensure the binaries are downloaded
  if [ ! -f "ubuntu/binaries/master/kube-apiserver" ]; then
    echo "warning: not enough binaries to build k8s, please run build.sh in cluster/ubuntu first"
    exit 1
  fi
  ....
}  
change ubuntu/binaries/master/kube-apiserver to cluster/ubuntu/binaries/master/kube-apiserver

error be 

ubuntu/config-default.sh: No such file or directory
ubuntu/util.sh: No such file or directory
ubuntu/master/*: No such file or directory
ubuntu/reconfDocker.sh: No such file or directory
ubuntu/minion/*: No such file or directory
ubuntu/binaries/master: No such file or directory
ubuntu/binaries/minion: No such file or directory

**Comment by goltermann** [comment]
We’re going through old support issues and asking everyone to direct your questions to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes). 

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases. 

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.
