### ISSUE TITLE
No answer on Kubernetes security email

### ISSUE THREAD

**Issue by g3rzi** [kubernetes/kubernetes#100924]
#### What happened:
I reported a security vulnerability to security@kubernetes.io as stated here:
https://kubernetes.io/docs/reference/issues-security/security/ 

#### What you expected to happen:
Someone to answer me 

#### How to reproduce it (as minimally and precisely as possible):
Send mail and wait two days.
It will wrote you that they will get back in 1 business day but there is no answer at all.

#### Anything else we need to know?:
I sent the mail couple of times, and still now answer.

#### Environment:
no need

**Comment by liggitt** [comment]
cc @kubernetes/product-security-committee

**Comment by joelsmith** [comment]
@g3rzi thank you for disclosing responsibly!

Regarding the specific email mentioned in the above report, the PSC responded yesterday. I apologize that we took so long.

I think this illustrates that we need a process change for handling direct emails to the PSC. We have been a little less responsive to those messages since now the vast majority of reports are triaged by HackerOne as part of the bug bounty program. (https://hackerone.com/kubernetes)

 I have added an agenda item to the PSC montly meeting to discuss potential process improvements to help us be more responsive.

Thanks for bringing visibility to this issue!
/close
