### ISSUE TITLE
kubelet should look for files in /etc/kuberenetes/pods

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#10091]
rather than (or in addition to) /etc/kubernetes/manifests

**Comment by thockin** [comment]
This is ancient, but a wart, and still deserves fixing, IMO.  Not hard at all, just needs someone to do it.

**Comment by nilsmagnus** [comment]
Is this as simple as search/replace /etc/kuberenetes/manifests for /etc/kuberenetes/pods ?

**Comment by thockin** [comment]
No, it probably needs to be able to pull from 2 places, so end-users don't
get broken..

**Comment by frankgreco** [comment]
@thockin I assume that this should only be the case if `--pod-manifest-path` is not set by the user. This would be consistent with the current behavior: https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet.go#L267-L270

**Comment by mtaufen** [comment]
I talked to Tim about this; the root issues is that "manifests" used to mean something else, and it's the wrong word for what this is now. I am going to try to at least expunge the word from the Kubelet's config API before 1.10, and also as many internal var names as possible.

**Comment by mtaufen** [comment]
#60314

**Comment by dpandhi-git** [comment]
@mtaufen Does this issue still need to work on , or is it taken care as part of #60314. I would like to help on the issue. Haven't done much commit to K8s but I can shadow you and like to help.

**Comment by mtaufen** [comment]
It wouldn't hurt for someone to go through and find instances of "manifest" that really mean "pod" or "static pod." If this is one of your first contributions and you're just trying to get the hang of committing to the project, that's an easy thing to do. 

But if you're interested in more serious contributions, I bet you can find something more important to help with. See if there are any open KEPs you'd like to work on: https://github.com/kubernetes/enhancements/issues.

**Comment by dpandhi-git** [comment]
Thanks @mtaufen will look around on issues list

**Comment by SergeyKanzhelev** [comment]
@mtaufen @thockin the issue is quite old. I think I understand context. Do you think the term manifest is still needs to be eliminated in the codebase? It looks like it is used as a reference to yaml file now in some cases. Like "Pod manifest": https://github.com/kubernetes/kubernetes/blob/3a47ddccdfb09e73758cebb2690ad2a014f67e23/hack/local-up-cluster.sh#L34 

Is there any "appropriate" uses of manifest from your perspective anywhere?

Is the scope of work:

- [ ] Deprecate `pod-manifest-path` in favor of kubelet configuration's `StaticPodPath` (we shouldn't introduce a new command line option `static-pod-path`).
- [ ] All mentions of "manifest" in kubeadm be changed to StaticPod: https://github.com/kubernetes/kubernetes/blob/f3371ced8593498a472452805b8ba212d67ea47d/cmd/kubeadm/app/phases/upgrade/staticpods.go `StaticPodManifest` is the thing now... I wonder if "manifest" in that case needs to be replaced with "yaml"? Definition? 
- [ ] cluster/gce folder has a few usages of the word "manifest". Likely can be replaced with staticpod quite easily.

**Comment by ehashman** [comment]
As far as I can tell, we have supported configuring this directory since at least 1.4: https://github.com/kubernetes/kubernetes/pull/29999

There's possibly some very non-urgent cleanup left to do re: the name manifest but I don't think it's very critical: https://cs.k8s.io/?q=manifest&i=fosho&files=cmd%2Fkubelet&excludeFiles=&repos=kubernetes/kubernetes

/remove lifecycle-frozen
/close
