### ISSUE TITLE
Change node.status.addresses to "atomic" (Dual-stack; log errors for multiple InternalIP items in Node objects)

### ISSUE THREAD

**Issue by uablrek** [kubernetes/kubernetes#101029]
#### What happened:

When upgrading from v1.20.x->v1.20.y or -> v1.21.0 with multiple `InternalIP` items for dual-stack as;
```
# kubectl get node vm-001 -o json | jq .status.addresses
[
  {
    "address": "192.168.1.1",
    "type": "InternalIP"
  },
  {
    "address": "1000::1:c0a8:101",
    "type": "InternalIP"
  },
  {
    "address": "vm-001",
    "type": "Hostname"
  }
]
```
these entries shows up in the `kube-apiserver` logs;
```
E0412 12:58:28.787842    3558 fieldmanager.go:186] [SHOULD NOT HAPPEN] failed to update managedFields for /, Kind=: failed to convert new object (/v1, Kind=Node) to smd typed: .status.addresses: duplicate entries for key [type="InternalIP"]
```

The upgrade seems to be succesful beside the error log items.

#### What you expected to happen:

There shall be no `SHOULD NOT HAPPEN` log entries.

#### How to reproduce it (as minimally and precisely as possible):

* Start kubelet with multiple node-ip's `--node-ip=192.168.1.1,1000::1:192.168.1.1`.
* Upgrade from v1.20.x (perhaps other versions. I have only tested from v1.20.x and v1.21.0->master)

#### Anything else we need to know?:

Unsure what sig but I set;
/sig/network

#### Environment:
- Kubernetes version (use `kubectl version`): v1.20.x
- Cloud provider or hardware configuration: No Cloud provider.
- OS (e.g: `cat /etc/os-release`): own setup
- Kernel (e.g. `uname -a`): linux-5.11.1
- Install tools: from scratch
- Network plugin and version (if this is a network-related bug): bridge
- Others:

**Comment by pacoxu** [comment]
/cc @aojea 

> advertiseAddress in InitConfiguration specifies the IP address that the API Server will advertise it is listening on. The value of advertiseAddress equals the --apiserver-advertise-address flag of kubeadm init
During writing the docs for kubeadm dual-stack, the examples here https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/dual-stack-support/ for apiserver advertise address should be specified in kubeadm as it doesn't support dual stack.

**Comment by aojea** [comment]
yeah, I hit this here too https://github.com/kubernetes-sigs/kind/pull/2173#issuecomment-811939569 
thanks for reporting it

@apelisse can you advise here?
should we treat `.status.addresses: duplicate entries for key [type="InternalIP"]`  as a known issue when upgrading in dual-stack?
if affirmative, can we improve the message?

**Comment by apelisse** [comment]
This error sounds worse than it is and typically doesn't have an impact on anything. It just prevents server-side apply from tracking who owns which fields, which may prevent people from server-side applying this object. Since node is rarely applied AFAIK, this should be fairly consequence-free.

https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/api/core/v1/types.go#L4795-L4804

This is due to the comment mentioned on that field:
> // Note: This field is declared as mergeable, but the merge key is not sufficiently
> // unique, which can cause data corruption when it is merged. Callers should instead
> // use a full-replacement patch. See http://pr.k8s.io/79391 for an example.

@thockin I'm not entirely convinced that we can't make that list "atomic", but I must be missing something?

**Comment by apelisse** [comment]
> > // Note: This field is declared as mergeable, but the merge key is not sufficiently

To be clear, we don't have any corruption here. The "not sufficiently unique" throws SSA off and prevents it from doing its job.

**Comment by thockin** [comment]
I don't know what the implications for making it atomic would be, but that seems like the "complete" answer.  Is that safe to change?

**Comment by thockin** [comment]
IOW: if I change that and I have existing clients, what happens?

**Comment by apelisse** [comment]
Multiple things to mention. 

This list is not atomic because of `patchStrategy=merge` which is interpreted by server-side apply as `listType=map`. What I'm actually suggesting would be to remove `patchStrategy=merge`, which is by default interpreted by SSA as `listType=atomic`.

We are in the process of [documenting](https://deploy-preview-27379--kubernetes-io-master-staging.netlify.app/docs/reference/using-api/server-side-apply/#compatibility-across-topology-changes) the impact of topology change on existing objects. In this case, we would transfer ownership of people who own an item of the list to the ownership of the whole list. I don't think it's super relevant though.

It looks like the doc already mentions that the list should be entirely replaced, so that wouldn't really change anything for existing patches.

**Comment by aojea** [comment]
/cc @danwinship 
he fixed the previous problem with the node statusa ddresses and was the author of the comment mentioned in https://github.com/kubernetes/kubernetes/issues/101029#issuecomment-819211711

**Comment by thockin** [comment]
I wonder if service ports (which also fail patch) could get the same
treatment?

**Comment by apelisse** [comment]
We've made [service ports use both port number and protocol as the key](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/api/core/v1/types.go#L4082-L4089)

**Comment by thockin** [comment]
That's just SSA, not legacy patch, right?

**Comment by apelisse** [comment]
Yeah, SSA would read `listType`, SMP uses `patchStrategy`

**Comment by thockin** [comment]
And there was no way to do compound keys in SMP, right?

**Comment by apelisse** [comment]
Updating SMP is always complicated and has been generally abandoned. In that specific case, I don't think we would benefit a lot to be honest. The list is mostly small, it can easily be replaced, no?

**Comment by thockin** [comment]
Yes - I am confused now on all the tags.  If I wanted to switch `Ports
[]ServicePort` from merge to atomic, is that a "safe" change?

**Comment by apelisse** [comment]
Clients that are aware of that change will always replace the list, which is what we want, that sounds safe.
Clients (if they exist) that still think they can send partial elements may fail, but since we have 0 documentation for SMP, the only way to know is to test.

**Comment by danwinship** [comment]
> This list is not atomic because of `patchStrategy=merge` which is interpreted by server-side apply as `listType=map`. What I'm actually suggesting would be to remove `patchStrategy=merge`, which is by default interpreted by SSA as `listType=atomic`.

This was discussed at the time that the comment was added, and it was pointed out that any change to `patchStrategy` is a breaking API change, because it would cause skewed clients and servers to disagree on the interpretation of patches (eg, an old `patchStrategy=merge` client trying to add a new value into the list would generate a patch containing only the new value, which a new `patchStrategy=replace` server would then interpret as meaning to replace the old value rather than merging the new value in).

It's true that at this point all still-supported versions of kubelet and cloud-provider always [forcibly override the patch strategy](https://github.com/kubernetes/kubernetes/pull/79391/files#diff-15a7ea42c856468667780447090b682f36ea0385dcdbe9105ff49900564a190bR234), and if anyone else tries to modify `node.status.addresses` then kubelet/cloud-provider will just overwrite their changes shortly after anyway, so it doesn't really matter much whether they patch it correctly or incorrectly. So... maybe we could get away with it?

**Comment by thockin** [comment]
I think your interp is correct @danwinship (for node addresses).

I don't think it's strictly safe for service ports and I am afraid of it. :(

**Comment by thockin** [comment]
@khenidak unless we've got a viable solution to this, I think we should  close it.

**Comment by khenidak** [comment]
ack -- looking.
/assign @khenidak
