### ISSUE TITLE
pull-kubernetes-integration: test-cmd: run_kubectl_diff_tests  

### ISSUE THREAD

**Issue by pacoxu** [kubernetes/kubernetes#101019]
#### Which jobs are failing:
pull-kubernetes-integration

#### Which test(s) are failing:
run_kubectl_diff_tests

#### Since when has it been failing:
https://prow.k8s.io/?job=pull-kubernetes-integration&state=failure It only shows failure cases in recent 2 days.
The last date is `Apr 10 16:04:18Apr 10 2021, 16:04:18 UTC+0800`

#### Testgrid link:
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/101013/pull-kubernetes-integration/1381512796969111552
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/101006/pull-kubernetes-integration/1381460511371038720

#### Reason for failure:

```
(B[mdiff -u -N /tmp/LIVE-706114995/v1.Pod.namespace-1618192119-8332.test-pod /tmp/MERGED-419169654/v1.Pod.namespace-1618192119-8332.test-pod
--- /tmp/LIVE-706114995/v1.Pod.namespace-1618192119-8332.test-pod	2021-04-12 01:48:42.133356843 +0000
+++ /tmp/MERGED-419169654/v1.Pod.namespace-1618192119-8332.test-pod	2021-04-12 01:48:42.137357267 +0000
@@ -19,7 +19,7 @@
             f:name: {}
     manager: kubectl
     operation: Apply
-    time: "2021-04-12T01:48:41Z"
+    time: "2021-04-12T01:48:42Z"
   name: test-pod
   namespace: namespace-1618192119-8332
   resourceVersion: "1026"
!!! [0412 01:48:42] Call tree:
!!! [0412 01:48:42]  1: /home/prow/go/src/k8s.io/kubernetes/test/cmd/../../third_party/forked/shell2junit/sh2ju.sh:47 run_kubectl_diff_tests(...)
!!! [0412 01:48:42]  2: /home/prow/go/src/k8s.io/kubernetes/test/cmd/../../third_party/forked/shell2junit/sh2ju.sh:112 eVal(...)
!!! [0412 01:48:42]  3: /home/prow/go/src/k8s.io/kubernetes/test/cmd/legacy-script.sh:132 juLog(...)
!!! [0412 01:48:42]  4: /home/prow/go/src/k8s.io/kubernetes/test/cmd/legacy-script.sh:533 record_command(...)
!!! [0412 01:48:42]  5: hack/make-rules/test-cmd.sh:191 runTests(...)
+++ exit code: 1
```

#### Anything else we need to know:

```
while true
do
   kubectl delete pod/test-pod && kubectl apply --server-side -f hack/testdata/pod.yaml; kubectl diff --server-side -f hack/testdata/pod.yaml; echo $?
   sleep 1
done
```
I tried to reproduce it locally, but can't

**Comment by kevindelgado** [comment]
I’ve only briefly taken a look at this, but my understanding is that server-side diff is flaking because the `managedFields` timestamp is different (by like a second) between the one already applied and the diff apply.

@apelisse, do you think this could be related to this recent change https://github.com/kubernetes/kubernetes/pull/100032? Could delaying when we update the timestamp cause it to sometimes get misaligned with what’s being diffed?

I’m not super familiar with diff, but it feels like it should ignore differences between timestamps that get updated on each call, right? Is there some sort of mechanism we have in `kubectl diff` that knows to ignore timestamps that just isn’t being done for `.metadata.managedFieds[*].time` fields?

**Comment by apelisse** [comment]
> I’m not super familiar with diff, but it feels like it should ignore differences between timestamps that get updated on each call, right? Is there some sort of mechanism we have in kubectl diff that knows to ignore timestamps that just isn’t being done for .metadata.managedFieds[*].time fields?

This error probably shows that we have a path that causes the object to be re-written to etcd when it shouldn't.

**Comment by apelisse** [comment]
As we can see, the diff only shows a difference in the timestamp but not in the fields that are managed. We are not supposed to update the timestamp if the managed fields haven't changed. That timestamp only gets updated if the two steps happen in different seconds (that's why it's flaky). That is definitely not a flake but an actual failure.

**Comment by pacoxu** [comment]
**Failed 80+ times today in https://prow.k8s.io/?job=pull-kubernetes-integration&state=failure**
/priority critical-urgent
I think, correct it if I am wrong.

**Comment by liggitt** [comment]
> **Failed 81/236 times today in https://prow.k8s.io/?job=pull-kubernetes-integration&state=failure**
> /priority critical-urgent
> I think, correct it if I am wrong.

correct. who should be assigned as the owner of this?

**Comment by kevindelgado** [comment]
I can take it, I'm looking into it now
