### ISSUE TITLE
PodTopologySpread: `criticalPaths[1]` is not used anywhere?

### ISSUE THREAD

**Issue by chendave** [kubernetes/kubernetes#101237]
#### What happened:
`PodTopologySpread` plugin has created  `[2]criticalPath` for each of the constraints, and it is get updated for each `TpPairToMatchNum` where `criticalPaths[0].MatchNum` always holds the minimum matching number and `criticalPaths[1].MatchNum` is always greater or equal to `criticalPaths[0].MatchNum` for each of the topology key.

The `criticalPaths[0].MatchNum` is used during filtering, but I cannot see where `criticalPaths[1].MatchNum` is used.
https://github.com/kubernetes/kubernetes/blob/5a92454f5e2d33b4c8b2419b220568704b764e28/pkg/scheduler/framework/plugins/podtopologyspread/filtering.go#L317-L322

Is that meaning `criticalPaths[1].MatchNum` doesn't necessary to be kept here? Cannot we just record the minimum matching number for each of the topology key?

#### Environment:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by chendave** [comment]
@alculquicondor , this should more like a question instead. I searched in the KEP and haven't found any clue about the design, why `criticalPaths` is designed as this in the first place? thanks for your eyes!

**Comment by alculquicondor** [comment]
@Huang-Wei implemented this. It was an implementation detail that is definitely not in the KEP. Wei, can you take a look?

**Comment by Huang-Wei** [comment]
@chendave it's built in PreFilter, and used in the preemption logic:

https://github.com/kubernetes/kubernetes/blob/fd8128d7d65cd650c0ecb60e6b1845f7d1844ff2/pkg/scheduler/framework/plugins/podtopologyspread/filtering.go#L92

Basically, we built a map keyed with topologyKey, and valued with [2]criticalPaths in PreFitler phase. This records top2 valid tpPairs with minimum matching number. E.g., {zone:zone1 -> 0}, {zone:zone2 -> 1}. Note that we don't care whether zone2 has ties or not (i.e., {zone:zone3 -> 1). The core idea is to ensure criticalPaths[0] always holds the pair with minimum matching number. So with this data structure, we can perform efficient preemption:

- suppose 2 pods are getting added to zone1, criticalPaths should be updated to {zone:zone2 -> 1}, {zone:zone1 -> 2}. Again, we don't flip {zone:zone3: 1} in no matter it exists or not, because we just need **one** miminum pair. (a bit like how miminum heap works, the top is the min/max value and that's enough)
- suppose 1 pod is getting added to zone2, criticalPaths is updated to {zone:zone1 -> 0}, {zone:zone2 -> 2}
- suppose pods are added to other zones, criticalPaths stay unchanged.

Also, there is a comment stating this implementation's limitation:

https://github.com/kubernetes/kubernetes/blob/fd8128d7d65cd650c0ecb60e6b1845f7d1844ff2/pkg/scheduler/framework/plugins/podtopologyspread/filtering.go#L74-L80

**Comment by chendave** [comment]
Thanks @Huang-Wei for the excellent explanation!

There is not need to maintain two critical paths for the normal scheduling process,  but I missed the case of preemption, and also the case where the node has some nominated pods associated already, both these cases have the possibility to update the initial `preFilterState` and then call the `Filter` extension points to check the feasibility of the node.
