### ISSUE TITLE
Reduce secret rbacs for csi mock e2e tests

### ISSUE THREAD

**Issue by msau42** [kubernetes/kubernetes#101334]
#### What happened:
Followup to https://github.com/kubernetes/kubernetes/pull/100637/files#r604424461

#### What you expected to happen:
Reduce the rbac to the e2e test namesapce

@kubernetes/sig-storage-bugs

**Comment by ZakMiller** [comment]
I see a couple of paths forward:
1. Update the code added as part of this commit: https://github.com/kubernetes/kubernetes/pull/100637/commits/c794b5c442b18b078b287bcbb25bb18b9eb439cd to add the role and role binding for that particular namespace, rather than granting access to secrets in the cluster role

Pros:
- only impacts test, if that's what we want

Cons:
- The resources aren't centralized in the example manifests anymore.

2. Update the yaml file in the external repo to add the secret permissions to the existing role that's bound to the default namespace (I think this works): https://github.com/kubernetes-csi/external-attacher/blob/master/deploy/kubernetes/rbac.yaml, then run the script in the kubernetes repo to pull it in after it's in. And remove the test-specific code

Pros:
- The yaml example is closer to what users should be doing

Cons:
-  Maybe we don't want to pollute this example with a secret if it isn't necessary in all cases?

I have a PR I'm working on for the second option.

**Comment by msau42** [comment]
I actually prefer the 1st option because not all csi drivers require secrets, and I think it's better to keep the rbac example as minimal as possible.
