### ISSUE TITLE
TCP Conntrack entries remain in stale 

### ISSUE THREAD

**Issue by kashifest** [kubernetes/kubernetes#101607]
We have a service with type as LoadBalancer. The service external-IP is allocated by a controller and the this IP is known in advance even before the service is deployed. The service external IP is configured on the client machines located outside the Kubernetes cluster and they are trying to reach the service all the time. The adjacent routers are configured to forward the traffic matching the service external-IP towards the worker node statically.

In the beginning the clients are trying to reach to the service external-IP and at this time the Kubernetes cluster do not have the service or the pods up and running. At this time the iptables do not have entry for the service external-IP and this means that the packets will not be handled by the iptables populated by kube-proxy. These TCP SYN packets creates a conntrack entry which will get removed in 120 seconds if no further packets are matching to the tuple

sudo conntrack -L  | grep 30.4.5.22
conntrack v1.4.4 (conntrack-tools): 48 flow entries have been shown.
tcp      6 48 SYN_SENT src=137.64.100.78 dst=30.4.5.22 sport=63302 dport=80 [UNREPLIED] src=30.4.5.22 dst=137.64.100.78 sport=80 dport=63302 mark=0 use=1

In this case the service external IP is 30.4.5.22

The client is having limited (may be 3) TCP source ports due to the way firewalling and clients are configured. This means that clients keep trying to establish TCP session with same source port and causes the conntrack entry to be alive and not cleaned up at all.

When the service and pods are deployed at a later stage, the iptables are correctly updated with the service externalIP (30.4.5.22) rules. Unfortunately due to existing conntrack entry matching the packets destined to 30.4.5.22, the packets do not hit the NAT table. This means that the clients can not talk to the real service and they do not recover. If the conntrack entries are dropped after NAT tables are updated then the TCP sessions are established correctly.

This issue can happen in some cases of node reboots since there are cases where the external traffic arrives to the node before the kube-proxy can setup the NAT entries for the service external IP.

When we checked the kube proxy code we see that there are logic to remove the conntrack entries matching the service IP in case of UDP and SCTP but not for TCP.

Does it make the system robust if we clear the conntrack entry matching the IP that is added to the NAT table so that we do not have undesired behaviour due to stale conntrack entries?

#### Environment:
Kubernetes version is v1.20.4
kube-proxy mode is iptables

**Comment by aojea** [comment]
> When we checked the kube proxy code we see that there are logic to remove the conntrack entries matching the service IP in case of UDP and SCTP but not for TCP.

Just for clarification, UDP and SCTP are stateless and there is no possibility from the client to understand if the server is still present or has left, so clients keeps sending traffic with same (src ip/src port) renewing the conntrack entry.
Kube-proxy "knows" if the UDP/SCTP server has gone or has been replaced with other IP (new endpoints created or changed), so it clears the "stale" conntrack entries in order that the new traffic is not blackholed forever in conntrack..

> These TCP SYN packets creates a conntrack entry which will get removed in 120 seconds if no further packets are matching to the tuple

TCP is stateful, so it can "know" if the server is alive, as you correctly point out, after some predefined time the client retries if is not able to connect, usually with a new source tcp port that means different "new" conntrack entry, so the old one is not renewed and cleared after the conntrack timeout.

> Does it make the system robust if we clear the conntrack entry matching the IP that is added to the NAT table so that we do not have undesired behaviour due to stale conntrack entries?

This seems a very specific scenario, with alternatives out of kube-proxy to fix it, so I don't know if this can be enough to implement a general solution, it will be interesting to hear others opinions.

It is important to mention that externalIPs is something that the project is restricting since the recent CVE-2020-8554 https://github.com/kubernetes/kubernetes/issues/97076

**Comment by kyrieSun-wow** [comment]
Hi guys,
So will kube-proxy clear the conntrack for the pod which is already removed from the corresponding service now ?

I have met the same issue when I using k8s v1.18.10, the STCP connection stay still when the corresponding pod is already removed,and all packets coming from client are forwarded to the pod that has been removed.

**Comment by aojea** [comment]
> I have met the same issue when I using k8s v1.18.10, the STCP connection stay still when the corresponding pod is already removed,and all packets coming from client are forwarded to the pod that has been removed.

for UDP and SCTP it does cleanup of the entries, this is about TCP

**Comment by kyrieSun-wow** [comment]
It's a good new! And from which version of k8s that the entries will be cleanup for SCTP?

**Comment by aojea** [comment]
> It's a good new! And from which version of k8s that the entries will be cleanup for SCTP?

1.19 https://github.com/kubernetes/kubernetes/pull/74073/commits/aa8521df666c0cc8f65da7150a1961cf3277fc44

**Comment by kyrieSun-wow** [comment]
> > It's a good new! And from which version of k8s that the entries will be cleanup for SCTP?
> 
> 1.19 [aa8521d](https://github.com/kubernetes/kubernetes/commit/aa8521df666c0cc8f65da7150a1961cf3277fc44)

Thank you so much!

**Comment by thockin** [comment]
If you configure the nf_conntrack_tcp_timeout_syn_recv and nf_conntrack_tcp_timeout_syn_sent timeouts down (say 6 and 12 seconds instead of 60 and 120) does that solve your problem?

Can you run a daemonset that does that?

**Comment by kashifest** [comment]
> If you configure the nf_conntrack_tcp_timeout_syn_recv and nf_conntrack_tcp_timeout_syn_sent timeouts down (say 6 and 12 seconds instead of 60 and 120) does that solve your problem?
> 
> Can you run a daemonset that does that?

This option has been tried and it helps when the client do not sent TCP SYN  in this time window. But what we have seen is that some of the clients were very aggressive and thus the configuration has to be even smaller numbers and eventually depends on the client behaviour. So we were looking at an option that will clear the entry when a matching service is added to iptables.

**Comment by uablrek** [comment]
Quite easily reproducible. Setup;
* Select a loadBalancerIP, `10.0.0.0` in this example
* Set a static route so traffic to that address comes to one node, `vm-002` in this example

From an external machine, constantly try to connect using the same source port;
```
while true; do date; nc -w 1 -p 40000 10.0.0.0 5001; done
```
On the receiving node (`vm-002`);
```
conntrack -L -d 10.0.0.0      # There should be an entry
# Now create a pod and service
cat <<EOF | kubectl apply -f -
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpine-deployment
spec:
  selector:
    matchLabels:
      app: alpine
  replicas: 2
  template:
    metadata:
      labels:
        app: alpine
    spec:
      containers:
      - name: alpine
        image: library/alpine:latest
        imagePullPolicy: IfNotPresent
        command: ["nc", "-lk", "-p", "5001", "-e", "hostname"]
---
apiVersion: v1
kind: Service
metadata:
  name: alpine-hostname
spec:
  selector:
    app: alpine
  ports:
  - port: 5001
    name: hostname
  type: LoadBalancer
EOF
# If needed, assign the loadBalancerIP
assign-lb-ip -svc alpine-hostname -ip 10.0.0.0
```
Now the service is setup and working but the external machine still can't connect because of the stale conntrack entry. Now we delete the conntrack entry on the receiving node and communication starts to work immediately;
```
conntrack -D -d 10.0.0.0
```
I use [assign-lb-ip](https://github.com/Nordix/assign-lb-ip) to set the loadBalancerIP, it may be set automatically in your env.

It can be observed that since the same conntrack is used the connection is "sticky". It is not load-balanced between PODs. If you remove the source port setting it will be load-balanced (or if another source address is used).

**Comment by uablrek** [comment]
While this is not a problem for web-applications where the clients are well behaiving and usually have no restricions on the source port, it _is_ a problem if the client is very primitive or is restricted by firewall rules. IMO K8s can, and should, support those clients.

/triage accepted

**Comment by uablrek** [comment]
The behavior is the same for kroxy-mode `iptables` and `ipvs`.

**Comment by thockin** [comment]
Thanks for the triage!  Any thoughts on best fix, while it is fresh?

**Comment by uablrek** [comment]
Same as for UDP/SCTP I guess. I havn't checked those though. A problem is that the conntrack crear and the config of iptables/ipvs should really be "atomic", but it can't. I think the best is to _first_ make the load-balancing setup and _then_ clear the conntrack entry. A connection may be lost, but at least subsequent attempts will work.

**Comment by aojea** [comment]
The problem I see with TCP is that we can race with the "normal" TCP shutdown and break it, I didn't think too much about this in this context honestly, but I saw and experienced myself issues because of cleaning "too fast", leaking fds, ...

**Comment by thockin** [comment]
That was also my first thought, too.

**Comment by uablrek** [comment]
This is not in shutdown, it is on "startup" so to speak, i.e. when the service is configured.

**Comment by uablrek** [comment]
Perhaps _that is_ different from UDP/SCTP.

**Comment by uablrek** [comment]
Before (stale);
```
vm-002 ~ # conntrack -L -d 10.0.0.0
tcp      6 119 SYN_SENT src=192.168.1.201 dst=10.0.0.0 sport=40000 dport=5001 [UNREPLIED] src=10.0.0.0 dst=192.168.1.201 sport=5001 dport=40000 mark=0 use=1
```
After (working);
```
vm-002 ~ # conntrack -L -d 10.0.0.0
tcp      6 3599 CLOSE_WAIT src=192.168.1.201 dst=10.0.0.0 sport=40000 dport=5001 src=11.0.1.2 dst=192.168.1.2 sport=5001 dport=48502 [ASSURED] mark=0 use=1
```
In this case it would be sufficient to remove any `[UNREPLIED]` entries with the loadBalancerIP as dest. To be extra sure we can check the NATed src, it should be a POD (or node) IP _not_ the loadBalancerIP. Such a conntrack entry is surely useless.

**Comment by thockin** [comment]
I wonder if it is finally time for a more complete conntrack-management
overhaul.  Any time the set of backends (endpoints) or frontends
(clusterIP, ports, nodeport, LB-IP) changes we may need to do something in
conntrack.  What that something is obviously depends on the protocol and
exactly what changed.  May be fun to work up that table :)

**Comment by aojea** [comment]
> I wonder if it is finally time for a more complete conntrack-management overhaul.

I wonder if we are reaching the limits of conntrack based loadbalancer

**Comment by uablrek** [comment]
What are the alternatives? eBPF and XDP? I think NTF will also rely on the conntracker.

And btw, the conntracker is *very hard* to get rid of. Believe me, I have tried :smile:  Please see; https://unix.stackexchange.com/questions/650790/unwanted-defragmentation-of-forwarded-ipv4-packets

**Comment by uablrek** [comment]
> I wonder if it is finally time for a more complete conntrack-management overhaul.

@thockin I think you are right. Yet another one https://github.com/kubernetes/kubernetes/issues/102618

**Comment by aojea** [comment]
> I wonder if it is finally time for a more complete conntrack-management
overhaul.  

Lars,Tim you've convinced me, _Better the devil you know than the devil you don't know_ ,  and think that is time to slay this conntrack dragon

Let me try to reproduce it with an e2e test, so we can be more confident on the solution
https://github.com/kubernetes/kubernetes/pull/102631

**Comment by aojea** [comment]
I can reproduce the behaviour, however,  trying to "expand" current logic for UDP to TCP I realised that we will break graceful shutdown, since kube-proxy will have the endpoint removed it will delete the conntrack entries breaking current TCP communications.

Andrew was a kep to handle it adding a new state to endpoint slices to handle loadbalancers https://github.com/kubernetes/enhancements/tree/master/keps/sig-network/1669-graceful-termination-local-external-traffic-policy but I don't think that we can extend this to ALL services, it seems like a big performance impact on the slice controller.

I have another idea, it is very simple, since we know exactly how the stale entries look like: an entry that is always renewed but never replied, for TCP:

```
tcp      6 119 SYN_SENT src=172.18.0.1 dst=10.10.10.10 sport=60000 dport=80 [UNREPLIED] src=10.244.2.3 dst=172.18.0.2 sport=80 dport=45815 mark=0 use=1

for UDP
```
udp      17 29 src=172.18.0.1 dst=10.10.10.10 sport=60000 dport=80 [UNREPLIED] src=10.10.10.10 dst=172.18.0.2 sport=80 dport=60000 mark=0 use=1
```
 
we can do a simple reconcile loop that looks for those entries and delete them, I think that we can also reduce the risk of false positives to near 0, we check entries in an interval T, if we have X matches of
- entry on SYN_SENT (tcp) and UNREPLIED
- entry life timer always renewed (we can check against the sysctl value to see the difference)

we delete it.
This also will decouple the logic of the different proxies and simplify it, current code is complex to read

**Comment by aojea** [comment]
/assign

I have to fix a similar issue for hostports too

**Comment by uablrek** [comment]
> we can do a simple reconcile loop that looks for those entries and delete them

:+1: on this one.

And for the problem in this issue it is all entries with dst=VIP in the first "half" of the conntrack entry and _also_ src=VIP in the second. I am no conntrack expert but have assumed that the "secon half" is the NAT entry. If I am right, a record as described would not NAT the VIP address, and as such always be wrong.

**Comment by aojea** [comment]
This is an interesting behaviour, I thought that it only happened because the TCP connection was NATed, but in this case it is not, you can see the packet is not modified
```
tcp 6 48 SYN_SENT src=137.64.100.78 dst=30.4.5.22 sport=63302 dport=80 [UNREPLIED] src=30.4.5.22 dst=137.64.100.78 sport=80 dport=63302 mark=0 use=1
```

actually I reproduced it and the host sends a ICMP_REDIRECT to tell the sender to stop, but "of course, who cares about ICMP messages these days" :) so we keep hammering creating the stale entries. Also, we send the packet back through the same interface it entered :shrug: 

For the whole conntrack history:
- I think that for UDP we are good, I revisited again current logic and I think that we clean all possible scenarios.
- I think that SCTP is missing some of the UDP cleanups, I have to check 
- IPVS and iptables proxies logic has diverged

Actions items:
- Consolidate the conntrack logic, so at least is consistent in both proxies
- For TCP I think we don't have to delete the conntrack entries for endpoints, since we have to let the pods to terminate gracefully, however, we should do something with the connections that are not finished in the host, we are also sending the packet back through the same interface that is really ugly. I'll be tracking TCP on https://bugzilla.redhat.com/show_bug.cgi?id=1930457

**Comment by aojea** [comment]
> * We have an internal bug to check with the kernel hackers if this is the correct behaviour https://bugzilla.redhat.com/show_bug.cgi?id=1930457#c30 , I will check if it can be make public later

I didn't manage to make the bugzilla public, some misconfiguration issue, not private on purpose, 
Anyway, patches are going to the kernel, copying comments from the kernel developer

> test case + patch to make entry time out after SYN_SENT seconds (1m default):
> http://patchwork.ozlabs.org/project/netfilter-devel/patch/20210624103642.29087-2-fw@strlen.de/
> http://patchwork.ozlabs.org/project/netfilter-devel/patch/20210624103642.29087-3-fw@strlen.de/

and soon patches to allow to dump only the unreplied conntrack entries

**Comment by js-timbirkett** [comment]
I've been debugging an issue that  _think_ might be related to conntrack keeping track of `ESTABLISHED` connections to none existent pods after they've been terminated for a few minutes causing timeouts and HTTP 502s.

First... 
## Info
Kubernetes version: `v1.20.4-eks-6b7464`
kube-proxy: `602401143452.dkr.ecr.eu-west-1.amazonaws.com/eks/kube-proxy:v1.20.4-eksbuild.2`

## Background and Observations
I have a `NodePort` service listening on port 30180, There is an ALB directing traffic to the `NodePort`. The `NodePort` service targets a Traefik ingress controller deployment.

On re-deploying Traefik we saw HTTP 502 errors returned by the ALB but there were no matching 502's in Traefik logs. The ALB logs indicated that the request hadn't been handled by the service. So, we started digging. We ensured that deployments were rolled out sensibly with new pods in a `Ready` state before the old pods were terminated. We ensured that this swap out of pods didn't all happen at once.

We saw no traffic to the new pods, but lots of 502s and timeouts with a `while true; curl --max-time 5 -I -X GET ...` loop. This led me to suspect that Traefik may not be configuring itself in a timely manner so we crafted up a tool `super-goggles` that would get instance IP addresses form the EC2 API and send requests concurrently to:
- The main web service address (going through the ALB)
- Each instance `NodePort` with an appropriate host header
This tool showed that connections to the instances directly were fine. 0 errors. Connections through the ALB were not fine had errors (502s, timeouts).

This led me to think that there might be an issue with slowness in `Endpoint` updates or `kube-proxy` updating IPtables. A few `--watch` and `iptables-save`s later and this appeared not to be the case.

### So what do I know so far?

1. I get errors when re-deploying a service on a `NodePort` (may not be restricted to `NodePort` services though).
2. I get errors after deleting a pod in the deployment targeted by the `NodePort`
3. Requests directly to the `NodePort` do not get any errors. 
4. Requests through the ALB in front of the `NodePort` **do** get errors.
5. ALBs maintain keepalive connections to backend instances and AFAIK, you can't disable this (and you probably wouldn't want to).
6. Disabling HTTP/2 has no effect on the timeouts.
---

This has led me further into the rabbit hole this morning. I naively watched the output of `watch -n 5 'conntrack -L | grep 30180'` whilst killing a pod (with IP: `100.64.15.20`) In the output I saw (amongst the other pod IP addresses:
```
tcp      6 86385 ESTABLISHED src=10.8.47.119 dst=100.64.42.80 sport=64874 dport=30180 src=100.64.15.20 dst=100.64.42.80 sport=8000 dport=60496 [ASSURED] mark=128 use=1
tcp      6 86262 ESTABLISHED src=10.8.47.13 dst=100.64.42.80 sport=21698 dport=30180 src=100.64.15.20 dst=100.64.42.80 sport=8000 dport=31871 [ASSURED] mark=128 use=1
tcp      6 86353 ESTABLISHED src=10.8.47.119 dst=100.64.42.80 sport=64700 dport=30180 src=100.64.15.20 dst=100.64.42.80 sport=8000 dport=25081 [ASSURED] mark=128 use=1
tcp      6 86304 ESTABLISHED src=10.8.47.13 dst=100.64.42.80 sport=8994 dport=30180 src=100.64.15.20 dst=100.64.42.80 sport=8000 dport=21725 [ASSURED] mark=128 use=1
```

The conntrack entries containing `src=100.64.15.20` hung around for a few minutes. They didn't enter any other state during this time (unless it got missed between watch command outputs) and when they dropped out of the conntrack table all requests were happy again.

I then found this very issue that feels like it is very much related. Any insight from more knowledgeable humans would be appreciated.

**Comment by js-timbirkett** [comment]
More relevant information:

ALB Idle timeout is set to 300 seconds. Reducing it to 60 seconds sees timeouts and 502's for a lesser amount of time but we have other workloads that fail in different ways when the ideal timeout is lower.

It also feels like lowering the ALB idle timeout is a bit like papering over cracks and that there's definitely something strange going on with the persistent connections being routed to the non-existent pod IPs because of the conntrack entries. That's assuming that NAT routing decisions are being made by looking information up in the conntrack entries 🤔

**Comment by hanamantagoudvk** [comment]
after discussing with antoni, I have written a small agent for cleaning conntrack entry which is in UNREPLIED state.
https://github.com/hanamantagoudvk/conntrack-cleaner

But i observed one thing,  without service created when i tried to send TCP packet with  non-existant ClusterIP , i see an entry in conntrack table with SYN_SENT packet. But if we create a service (with no endpoints) , and then when i tried to send TCP packet with service IP , i dont see entry in conntrack table. 

conntrack-cleaner agent logic is based on filtering UNREPLIED entries and cleaning.

**Comment by aojea** [comment]
upstream patch to implement kernel side filtering, so an userspace application can query only the SYN (not established) entries
http://patchwork.ozlabs.org/project/netfilter-devel/patch/20210730131422.16958-3-fw@strlen.de/

**Comment by uablrek** [comment]
I have re-tested as described in https://github.com/kubernetes/kubernetes/issues/101607#issuecomment-853906646 with;
```
  08:21:56 Server Version: v1.23.3
  08:21:56 Linux 5.16.1 #18 SMP PREEMPT Tue Feb 8 18:56:32 CET 2022
  08:21:56 CNI-plugin; bridge
  08:21:56 Proxy-mode: "ipvs"
  08:21:56 crio version 1.22.0
```
The invalid conntrack entry is not renewed and is cleared after 120s, and the connect start to work.

So the kernel update in linux-5.14 seem to work as expected.

With `linux-5.12.1` the conntrack entry is renewed for every connect attempt and the problem occurs.

**Comment by uablrek** [comment]
This issue is solved by a Linux kernel patch added in `linux-5.14`. Closing ...

/close
