### ISSUE TITLE
GPU limits being omitted

### ISSUE THREAD

**Issue by ajonathan** [kubernetes/kubernetes#101723]
#### What happened:
Crude example based on the NVIDIA cuda vectorAdd sample container.  

The yaml file contents below deploys a pod demonstrating that multiple containers in a single pod can access the same GPU on the K8s node concurrently. 

Screenshots of an on-premises execution and a quick diagram of the GPU node, Pod & Container layout follow the yaml file below. 

#### What you expected to happen:
Should it be possible to deploy multiple containers in a single pod and access the same GPU on the K8s node concurrently?
Is this by design and is it an expected behavior?

#### How to reproduce it (as minimally and precisely as possible):
apiVersion: v1
kind: Pod
metadata:
  name: cuda-vector-add
spec:
  restartPolicy: Never
  containers:
    - name: cuda-vector-add-c0
      image: "k8s.gcr.io/cuda-vector-add:v0.1"
      command: [ "/bin/bash", "-c", "--" ]
      args: [ "while true; do date; nvidia-smi -l 1; done;" ]
    - name: cuda-vector-add-c1
      image: "k8s.gcr.io/cuda-vector-add:v0.1"
      command: [ "/bin/bash", "-c", "--" ]
      args: [ "while true; do date; ./vectorAdd; done;" ]
    - name: cuda-vector-add-c2
      image: "k8s.gcr.io/cuda-vector-add:v0.1"
      command: [ "/bin/bash", "-c", "--" ]
      args: [ "while true; do date; ./vectorAdd; done;" ]
    - name: cuda-vector-add-c3
      image: "k8s.gcr.io/cuda-vector-add:v0.1"
      command: [ "/bin/bash", "-c", "--" ]
      args: [ "while true; do date; ./vectorAdd; done;" ]
    - name: cuda-vector-add-c4
      image: "k8s.gcr.io/cuda-vector-add:v0.1"
      command: [ "/bin/bash", "-c", "--" ]
      args: [ "while true; do date; ./vectorAdd; done;" ]
    - name: cuda-vector-add-c5
      image: "k8s.gcr.io/cuda-vector-add:v0.1"
      command: [ "/bin/bash", "-c", "--" ]
      args: [ "while true; do date; ./vectorAdd; done;" ]
  tolerations:
    - key: "nvidia.com/gpu"
      operator: "Exists"
      effect: "NoSchedule"
  nodeSelector:
    nvidia.com/gpu "true"

#### Anything else we need to know?:
![image](https://user-images.githubusercontent.com/15071719/116970623-9b09c200-acb8-11eb-9a1d-0f3e48a3282d.png)
![image](https://user-images.githubusercontent.com/15071719/116971364-bd500f80-acb9-11eb-878a-b461e00a642c.png)

**Comment by SergeyKanzhelev** [comment]
Docs are [saying](https://kubernetes.io/docs/tasks/manage-gpus/scheduling-gpus/#:~:text=containers%20(and%20pods)%20do%20not%20share%20gpus.%20there's%20no%20overcommitting%20of%20gpus.) it is impossible:

> Containers (and Pods) do not share GPUs. There's no overcommitting of GPUs.

I wonder if this is a security issue as well.

/priority important-soon
/triage accepted

**Comment by sgerace** [comment]
@sergeyevstifeev We are actually relying on the ability to access the same host GPU, from within multiple containers, within the same Pod, for some of our production workloads, so _removing_ our ability to do so would be a **major** issue for us (since we are unaware of any alternative ways to achieve the desired effect). Our situation is as follows: we have a workload that is supported by several GPU-based algorithms that are deployed within separate containers. We need to be able to respond to requests very quickly (i.e., 50-100ms), and unfortunately, the containers take upwards of 30-60 seconds to startup and become operational. In addition, our workload constantly varies between tasks to be performed by Algorithm A, then Algorithm B, then Algorithm C, in other words, it would be extremely cost inefficient if we had a set of GPUs dedicated exclusively to Algorithm A, a separate set dedicated exclusively to Algorithm B, and a separate set dedicated exclusively to Algorithm C (this is just a representative example, the number of algorithms actually deployed can be on the order of 20-50). Finally, each algorithm tends to completely utilize the entire GPU when running.

The solution we came up with was to deploy all of the algorithm containers (and an orchestrator container) into a single Pod as a DaemonSet. Since the host GPU is mapped into all the containers, all of the algorithms have access to the underlying resource. The trick, obviously, is that we can never have more than one algorithm running at one time. This is the responsibility of the orchestrator container. The actual requests to process jobs are issued to the orchestration container, which then instructs the associated algorithm container to perform the necessary work. This solution allows us to simultaneously:
- have no cold-start times because all of the algorithm containers are always running, 
- ensure that the GPUs are never "over-utilized" (via the orchestrator), and 
- keeps our costs as low as possible because we are able to utilize a single set of GPUs for ALL of our algorithms.

If there is a better approach to achieving ALL the above, we would certainly entertain it, but this has been the only approach thus far that has given us the best of all worlds, and it relies heavily on the behavior described by @ajonathan.
