### ISSUE TITLE
More debug logs to check scheduler spread algorithm

### ISSUE THREAD

**Issue by pacoxu** [kubernetes/kubernetes#101820]
/sig scheduling 

#### What would you like to be added:
A way to check the scoring of each node to figure out why a node has a high scheduling priority.

- proposal 1: add **some debug level logs** to Kube-scheduler, so we can know node score on each scoring step.
- proposal 2: a simple way to decrease the priority of one node(in my case a node with more than 200 pods is with the highest scheduling priority for an unknown reason) 
- proposal 3:?

All new pods are scheduled to one of five nodes in my cluster.
I have checked both CPU/memory requested usage and all five nodes are bare metal and running about 150 pods or 200 pods.
Pods on node request 80-93% of the memory. 

#### Why is this needed:

We have a similar issue as https://github.com/kubernetes/kubernetes/issues/73843.

Currently, I think `proposal 1` is the easiest way.

**Comment by ahg-g** [comment]
This is useful. how do you suggest we log this information? note that there are two dimensions for each pod: plugin and node score.

Also, we need to limit the log length, we can't simply log the score for each node in clusters with large number of nodes.

**Comment by pacoxu** [comment]
> Also, we need to limit the log length, we can't simply log the score for each node in clusters with large number of nodes.

@ahg-g I prefer to log only the top 5 or 10 node scores in the log. (I have not read the code yet.😄, will dig into it later.)

**Comment by damemi** [comment]
We actually merged something like this that I wrote in https://github.com/kubernetes/kubernetes/pull/99411, but had to revert it because of performance issue in large clusters. That could be a good starting point @pacoxu 

My general approach was to 1) invert the `scoresMap` already available to map `node->plugins` (rather than `plugin->nodeScores`, which it currently does) and then 2) log the top 3 highest scoring plugins for each node

However @Huang-Wei discovered performance issues after this in https://github.com/kubernetes/kubernetes/issues/99913 (we believe due to the many writes this process took) and it was reverted in https://github.com/kubernetes/kubernetes/pull/99914. I think we decided that *some* performance hit is reasonable, especially given log levels >=4, but this was ~50% drop.

**Comment by pacoxu** [comment]
@damemi thanks for the information.
```
	if klog.V(10).Enabled() {
		for plugin, nodeScoreList := range scoresMap {
			for _, nodeScore := range nodeScoreList {
				klog.InfoS("Plugin scored node for pod", "pod", klog.KObj(pod), "plugin", plugin, "node", nodeScore.Name, "score", nodeScore.Score)
			}
		}
	}
```

So with current kube-scheduler, I can set log level to 10 to get every node score for each plugin. It helps in some cases.

**Comment by damemi** [comment]
@pacoxu yes, that's the current case. Though `V(10)` creates a *lot* of other noise in the logs, so I think we agreed that it is okay for us to add this kind of summary at a lower level like `V(4)`

**Comment by Huang-Wei** [comment]
I think we can use this chance to standardize the logging logic to dump scores dynamically depending on log level:

- for logging level ranged in `[4, 6)`, dump the scores for topM nodes/plugins. And make it as performant as possible.
- for logging level ranged in `[6, 10)`, dump the scores for topN nodes, and probably show all plugins
- for logging level >= 10, dump the scores for all nodes/plugins.

**Comment by pacoxu** [comment]
/reopen

Some problems that were mentioned by  @Huang-Wei  are not fixed yet.
> After taking a glance, I can spot several issues:
> 
> 1. A consensus on the value `M` and `N`. This is not fully discussed yet.
> 2. Further dig into the performance result. The test runs on v=1 and v=4, but actually they're the same if it's running in the context of integration framework.
>    https://github.com/kubernetes/kubernetes/blob/90851a0fb5bbb6f02b3c22715f9f91609f8ee438/test/integration/framework/master_utils.go#L131-L136
>    
>    I'd expect to see the result comparing before/after on v=4 and v=6.
> 3. Further review on the code, like adding UTs and some logic nits.

/cc @kerthcet @muma378

**Comment by pacoxu** [comment]
Since #104849 is merged to revert the change, https://github.com/kubernetes/kubernetes/pull/103515#issuecomment-915548963
> feel free to open a new PR, taking the comments [#103515 (comment)](https://github.com/kubernetes/kubernetes/pull/103515#issuecomment-914922411) and [#103515 (comment)](https://github.com/kubernetes/kubernetes/pull/103515#issuecomment-915421527) into consideration.

**Comment by sanposhiho** [comment]
Just FYI: this may be related to https://github.com/kubernetes/kubernetes/issues/107556 in the future.

In #107556, we cannot add all scores to the event message (because the event msg has the limit on the length), so I am thinking we need to sort node-scores by total score and add the score of top N nodes. 
And, if we do so, we can easily achieve to log the top M Node's score by using this sorted node-scores.
