### ISSUE TITLE
Proxy endpoint container

### ISSUE THREAD

**Issue by pmorie** [kubernetes/kubernetes#10209]
It would be really handy to be able to run the proxy endpoint presented by the API server in a container in order to:
1.  Run it without loading the API server with traffic
2.  Run it behind a service, scaled horizontally via replication controller

@smarterclayton @derekwaynecarr cc @detiber

**Comment by mbforbes** [comment]
+cc @cjcullen @brendandburns

**Comment by cjcullen** [comment]
I like this idea. This would also allow it to be easily disabled when not needed.

It should be simple to move the resource lookup & proxying into a container. The touchier part is correctly doing auth outside of the apiserver.

Verifying the client:
In the bearer token (and basic auth) case, we could probably get by just passing along the header in the GET request for the resource. If that request is 403'ed, 403 the client. If we get a successful response, proxy to the resourceLocation.
In the client cert case, we'd need something else. If we made all client certs available on an endpoint on the master, the proxy container could sync with those and validate connections the same way as we do on the master (not sure how complicated that would be). Then the proxy container could use a service account to look up the requested resource.

Verifying the server (the proxy):
Right now, clients trust the /proxy endpoint because the apiserver has a cert signed by a CA that we tell clients to use. We would probably want a proxy container to have a new cert, signed by the same CA. It might even make sense to create a "k8s-util-server-cert" inside a secret for utilities like this one in the kubernetes namespace to use. Then clients would trust the proxy container, and it could terminate SSL and MITM bearer tokens or redo lookups for client-cert auth.

@roberthbailey @lavalamp @bgrant0607 @thockin

**Comment by smarterclayton** [comment]
This sounds pretty complex.  The broader we make this the harder the default config is.  We also have to expose two public endpoints for the masters now, not one.  If the proxies are broken, you can't get into their containers for logs and exec.  The containers have to be exposed to the edge, which means we have to use a public port.

On the other hand, at scale this would be a very common pattern.  However, clients have to discover the proxy endpoints, which means more client complexity.

**Comment by lavalamp** [comment]
We do want to separate proxy out eventually, yes. There's probably already issue(s) about it. When we do this, we should also think hard about the security story (#10351). The proxy currently is good for debugging stuff (and maybe admin UI components?), and shouldn't be used for production traffic.

Production traffic should go through a production load balancer (probably built with HA proxy or nginx or something), and it probably won't use the cluster's own auth, or at least that should be up to the service.

**Comment by smarterclayton** [comment]
You can assign this to me - our ops teams have requested this, so it's likely someone is going to take a stab at this soon.

**Comment by cjcullen** [comment]
Could client discovery be done with an HTTP/301 off of the /proxy endpoint to the location of this proxy service? (or do redirects pose some problem I'm not thinking about?)

**Comment by smarterclayton** [comment]
Maybe not.  We'd need to check the upgrade aware handler and verify it works cleanly.  Logs can definitely be a redirect, even in the browser.
