### ISSUE TITLE
deprecate alpha annotation used in CSINode for migration detection

### ISSUE THREAD

**Issue by gnufied** [kubernetes/kubernetes#102357]
I think we should try and replace alpha annotation with a GAed version because I think we will end up having that annotation until k8s makes V2 (which could be forever).

/sig storage

cc @kubernetes/sig-storage-api-reviews

**Comment by msau42** [comment]
/triage accepted
/assign @jiaweiwang
@kubernetes/sig-storage-bugs

**Comment by Jiawei0227** [comment]
annotation that is still not in GA:

1. On CSINode:
- `storage.alpha.kubernetes.io/migrated-plugins: xxx,xxx` This is still in alpha
2. On PVC:
- `volume.beta.kubernetes.io/storage-provisioner: pd.csi.storage.gke.io` This is still in Beta

These are the annos that I found need to be upgrade. I am wondering if there is anything else?

**Comment by jsafrane** [comment]
`storage.alpha.kubernetes.io/migrated-plugins`: will we need it GA? It marks nodes with list of migrated plugins. CSI migration will GA soon-ish and 2 releases after GA the annotation becomes useless and could be removed.  (2 releases because of potentially old kubelets).

`volume.beta.kubernetes.io/storage-provisioner`: that should probably get GA.

**Comment by Jiawei0227** [comment]
Sounds like from the discussion from https://github.com/kubernetes/kubernetes/pull/104597 is to keep it alpha until all plugins moves to GA and remove it completely. Will close this issue.

**Comment by Jiawei0227** [comment]
Create https://github.com/kubernetes/kubernetes/issues/104760 for tracking the beta annotation removal.
