### ISSUE TITLE
pull-kubernetes-node-crio-e2e failing due to lack of gcp permissions 

### ISSUE THREAD

**Issue by harche** [kubernetes/kubernetes#102616]
#### Which jobs are failing:
`pull-kubernetes-node-crio-e2e`

#### Which test(s) are failing:
failed to launch the job `pull-kubernetes-node-crio-e2e` itself, so no tests were executed. 

#### Since when has it been failing:
After https://github.com/kubernetes/test-infra/pull/22228 was merged to make ``pull-kubernetes-node-crio-e2e` blocking

#### Testgrid link:
https://prow.k8s.io/?job=*pull-kubernetes-node-crio-e2e*

#### Reason for failure:
After merging https://github.com/kubernetes/test-infra/pull/22228 which makes the job blocking, it seems the  gcp project that it was part of, `k8s-jkns-pr-node-e2e`, earlier isn't valid. The job fails to launch with following error, 

```
W0605 07:26:58.997] 2021/06/05 07:26:58 process.go:153: Running: gcloud compute --project=k8s-jkns-pr-node-e2e project-info describe
W0605 07:27:20.654] ERROR: (gcloud.compute.project-info.describe) Could not fetch resource:
W0605 07:27:20.654]  - Required 'compute.projects.get' permission for 'projects/k8s-jkns-pr-node-e2e'
W0605 07:27:20.655] 
```
The equivalent `containerd` blocking job does [not specify gcp project value at all](https://github.com/kubernetes/test-infra/blob/aa44f2be7bbc36030f094505582fe314eed7c22a/config/jobs/kubernetes/sig-node/sig-node-presubmit.yaml#L131). So may be the fix for it is to remove the argument which specifies the [--gcp-project](https://github.com/kubernetes/test-infra/blob/aa44f2be7bbc36030f094505582fe314eed7c22a/config/jobs/kubernetes/sig-node/sig-node-presubmit.yaml#L486) value explicitly.

**Comment by BenTheElder** [comment]
> k8s-jkns-pr-node-e2e

Depending on a specific GCP project is an old anti-pattern we try to discourage because when projects are leased instead we can cleanup any and all (potentially leaked) resources in-between leases (http://sigs.k8s.io/boskos).

But in this case the issue is moving from an old google.com prow cluster (still the default) to a wg-k8s-infra build/prow cluster means you can't use google.com GCP projects that predate the wg-k8s-infra effort / GCP credit donation to CNCF. We cannot grant access to these projects from new projects outside of the google.com org (wg-k8s-infra has projects in CNCF owned kubernetes.io org billed via the credits instead of directly).
