### ISSUE TITLE
Docs about how to bootstrap apiserver

### ISSUE THREAD

**Issue by vaspahomov** [kubernetes/kubernetes#102663]
#### What would you like to be added:

Docs about how to bootstrap stand alone apiserver.
 
#### Why is this needed:

I've not found any doc about right way to bootstrap apiserver with best practices. I want to know about:
* where to download prebuilt binaries of kubernetes parts
* how to bootstrap vanilla apiserver. Simple steps like:
  * run etcd
  * generate certs
  * cmdline of simple stand alone apiserver
* may be smth else about how to bootstrap other parts on kuernetes

**Comment by neolit123** [comment]
from the SIG Cluster Lifecycle (we maintain minikube, kubeadm, etc.) perspective we have been asked to host a guide about "k8s the hard way" at the k8s.io website and this is something we have voted against.

this is difficult to maintain due to possibility of drift between flags / setup.
if you have questions please comment on:
https://github.com/kubernetes/website/pull/27788

but also see my comment here:
https://github.com/kubernetes/website/pull/27788#issuecomment-839980423

/sig api-machinery
/close
