### ISSUE TITLE
Support for 1:N mapping between hostPort and containerPort in Deployment Spec

### ISSUE THREAD

**Issue by prnvkv** [kubernetes/kubernetes#103077]
Currently when we specify a deployment spec with hostNetwork is true and the application in a container listens to multiple ports, the hostPort should be assigned for each of those port. 

    
ports:
     - containerPort: 8090
        hostPort: 8090
     - containerPort: 8091
        hostPort : 8091

It would be nice to have range of containerPort for a given hostPort. Something like this below:
ports:
    - hostPort: 8090
       containerPort: 8090-8200

To add, we are not using the service resource here because these are security applications where it should need host network namespace and avoid SNAT/DNATing.  Currently `externalTrafficPolicy: Local` provides such functionality but when run in `hostNetwork: true` it does not matter as the application is directly accessible via pods.

**Comment by haircommander** [comment]
hey @prnvkv since we're adding a new field to the pod  API (we can't reuse hostPort as it's an int, and it would need to become a string), and extending CRI implementations, the kubelet and API, I believe an extension like this warrants a KEP. Do you have any interest in taking on this feature?

/priority backlog
