### ISSUE TITLE
Service with type=LoadBalancer should be able to attach to an extant LB or IP

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#10323]
Exact semantics TBD, but it's clear that people need to be able to connect to existing LBs.  Maybe we can provide a simple way to do this before the next major round of API changes.

**Comment by mbforbes** [comment]
@thockin feel free to pick a relevant priority when you open these. I'm just guessing.

**Comment by thockin** [comment]
@rojer said in #11177 

What subj says - use existing allocated static IP instead of auto-assigning one.
Sometimes renumbering and reconfiguring is a pain, it would be nice to be able to preserve IP when moving to container clusters.
Could be a viable workaround for #11175 too. The two of them make service reconfiguration (adding/removing ports) impractical.

**Comment by Bochenski** [comment]
This would be really useful for instance to allow a GCE network load balancer to route traffic to two separate clusters in different availability zones.  Also if you need to re-build a cluster for any reason it's useful to be able to 'reconnect' to an existing load balancer IP

**Comment by apackeer** [comment]
Any idea when this feature will be introduced? At the moment I am not deleting the services created as a workaround in GCE to hold onto the IPs allocated by type: LoadBalancer, but this is not ideal.

**Comment by thockin** [comment]
We consider it a high priority for v1.1, but have not specced the API
changes yet.

@a-robinson - let's chat

**Comment by pnovotnak** [comment]
+1

**Comment by kgrvamsi** [comment]
+1

I tried this with the Softlayer Portable ip's by assigning the cluster ip range and then making the service get the elastic ip which can load balance but its not working as expected.

**Comment by housebolt** [comment]
+1, if I can't assign my IP address explicitly, then I'm insecure in my knowledge that it will stay there and won't be changed automatically without my knowledge by my cloud provider. This happened to me on a few occasions during the beta phase.

**Comment by mlamina** [comment]
+1
Any idea on when this issue is going to be addressed?

**Comment by thockin** [comment]
@housebolt Interestingly, there is NO WAY to do what you're asking for on AWS, and they seem pretty reliable.

v1.1 will have a fix to prevent load-balancer IPs from getting changed when updating a Service on GCE, so that is part 1.

#13005 proposes support for adding an explicit IP for loadBalancers (at the cost of not working on some platforms)

**Comment by housebolt** [comment]
@thockin I ran into this issue w/GCE. I'm wondering if I'm just missing some concept that will allow me to set the IP explicitly in GCE without having to worry about instantiating a LoadBalancer. If the IP address stays put then I'm happy, but if a future update breaks this and an RC blows up then my business-critical software goes down with it.

I tried it once by explicitly setting up a network load balancer but it didn't work, but maybe I need to try again. Do you have knowledge of this or are you aware of any resources that might point me in the right direction?

**Comment by thockin** [comment]
@housebolt yeah, I bet you ran into a "bug" of sorts wherein an update to a Service would release the load-balancer IP (since GCE does not support updating a load balancer).  This is fixed in head-of-tree, but we're still considering #13005 which offers an even stronger guarantee.

**Comment by bgrant0607** [comment]
Related: #3683

**Comment by thockin** [comment]
#13005 is in - that should alleviate this for GCE.

**Comment by kgrvamsi** [comment]
This Functionality should be for every cloud provider but not restricted only to GCE.

**Comment by thockin** [comment]
It works for GCE and OpenStack.  AWS doesn't support it.

**Comment by housebolt** [comment]
For those who run across this thread and are trying to figure out how to specify an IP address for a LoadBalancer, it's now available and working in a fairly recent release. Add "loadBalancerIP": "{{ IP ADDRESS }}" to the "spec" section of your LoadBalancer service file. Confirmed working on GCE, but make sure your node cluster is updated and current.

**Comment by c1freitas** [comment]
Does this work with AWS?

**Comment by rasekar2000** [comment]
Hello @housebolt , 
   Thanks for the note, I am using gCloud - Kubernetes - Google Container Engine. and setting up the service 
   `  "spec": {
    "type": "LoadBalancer",
    "loadBalancerIP" : "Actual IPv4 Address",
    "selector": {
      "app": "myapp",
      "tier": "frontend"
    },
    "ports": [
      {
        "name":"httpport",
        "protocol": "TCP",
        "port": 80
      },
      {
        "name":"httpsport",        
        "protocol": "TCP",
        "port": 443
      }      
    ]
    }`

Still when the service is getting created, it is not using the allocated Static IP ...
 I have reserved this IP in the gCloud only .. 
![image](https://cloud.githubusercontent.com/assets/3443965/13588950/0eb5c7e2-e489-11e5-8430-1a68ac8c9fbb.png)

lb4b-myservice             10.219.242.xx                     80/TCP,443/TCP

My kubernetes in gCloud component version is 98.0.0

`Google Cloud SDK 98.0.0
beta 2016.01.12`

`RajRajen:scripts rajrajen$ kubectl version
Client Version: version.Info{Major:"1", Minor:"1", GitVersion:"v1.1.7", GitCommit:"e4e6878293a339e4087dae684647c9e53f1cf9f0", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"1", GitVersion:"v1.1.8", GitCommit:"a8af33dc07ee08defa2d503f81e7deea32dd1d3b", GitTreeState:"clean"}`

 Please let me know, if I am missing any steps?

Thanks and Regards,
Raj

**Comment by housebolt** [comment]
Raj, in your notes you have "Actual IPv4 Address" as the value for the
"loadBalancerIP" key in your spec file. You do have to specify the actual
IP address you want to use.

Just to be clear, are you using it like this?

"loadBalancerIP" : "107.178.253.100"

**Comment by rasekar2000** [comment]
@housebolt , Yes.. I was using that public IP only .. Now the problem is resolved , when I switched to another service name. Also in the gCloud ' External IP Addresses ' , I recreated with 'Regional' attachment with Forward Rules empty. Then when the actual service is getting created, it used the specified loadBalancerIP address.

**Comment by rasekar2000** [comment]
Another thread https://github.com/kubernetes/kubernetes/issues/22721#issuecomment-194719162

**Comment by satheessh** [comment]
does it supported in aws? Really good feature.

**Comment by ruippeixotog** [comment]
Can some maintainer reopen this issue, since this feature is not yet supported for AWS? Or is it better to open a new issue just for AWS? cc @thockin

I use Terraform to manage my cloud infrastructure and I don't want to leave the responsibility of managing LBs to Kubernetes, since many other services depend on me knowing the name/ID of the load balancer I create, from Cloudwatch alarms to additional Route 53 records with a custom configuration. Right now I had to resource to opening fixed node ports, which is less than ideal. Being able to dynamically configure the load balancer as services get configured would be awesome.

**Comment by soorena776** [comment]
@ruippeixotog one workaround for aws would be to create a service on kubernetes using [terraform's kubernetes provider](https://www.terraform.io/docs/providers/kubernetes/r/service.html)

**Comment by mprzygrodzki** [comment]
@soorena776 would like to provide some examples how to create such a service with TF and precreated LB - i'm really interested how to work with this workaround.

**Comment by heidemn** [comment]
@mprzygrodzki this could help: https://www.terraform.io/docs/providers/kubernetes/d/service.html
(Not shown there: You need to create a Kubernetes service first. Then you can proceed as follows.)
When you have a Kubernetes service, you can get the corresponding load balancer's hostname, and then create DNS entries for your own domains.

My general opinion about this issue:
Using existing LBs seems very useful to me because of DNS caching problems:
You have set up a k8s Service (e.g. Nginx ingress controller) with a Load Balancer. E.g. because of a configuration problem, or by accident, you (have to) delete and recreate the Service.
If the LB is also destroyed & recreated, then a large percentage of your users will make requests to the wrong IP addresses for minutes or even for hours, and there's nothing you can do except waiting. Even if you limit the DNS caching period: Clients or DNS caches may not be up to standards, and cache the DNS records longer than allowed. 
Result: Your web page / API does not work for the users.

**Comment by abdennour** [comment]
@heidemn  I am already using Terraform.. But I still needs this feature because my nginx-ingress controller is created thru Helmfile.
And helmfile provider is not mature.
So I designed to do the following on my terraform plan : 
1. Create AWS ELB
2. Call Helmfile : If this feature is implemented, I just need to pass the DNS of the created ELB as values to Helmfile.

Now, this is needs a critical decision: Should we throw out Helmfile, and use  either: 
- (Terraform+kubernetes provider ) 
- Or (Terraform + Helm provider)

If we do that, we need to rewrite everything.. Note, that helmfile is now used by developers to deploy helm releases on their local env ( docker-for-desktop cluster, or docker-desktop cluster)
