### ISSUE TITLE
Harden master API against web attacks

### ISSUE THREAD

**Issue by stephenR** [kubernetes/kubernetes#10351]
In #8871 we hardened the usage of "kubectl proxy" but the same issues apply if you use the master API directly from a Browser. Also currently the XSRF protection in the proxy works by blocking POST requests completely which prevents valid use cases so it would be good to have a better approach to XSRF protection.

The attack scenario would look like this:
- a cluster admin uses the master API in Chrome and is authenticated with http basic auth
- in the same browser, the admin surfs to evil.com
- evil.com can now execute arbitrary code in the cluster _if he knows the IP of the master API_ by doing cross-origin requests to the API to start a new container or use the kubelet's /exec endpoint.

I'd suggest:
- all POST requests should have a form of XSRF protection, maybe requiring a custom header might be easy to implement and sufficient for this use case. Though whatever protection is used, it should be disabled for anything under /proxy since those services should come with their own XSRF protection.
- /exec and /run of the kubelet API should require a POST method since they are state changing requests (and then XSRF protected)
- I'm still concerned about the /proxy endpoints. Any XSS in one of the proxied services could be used to read secrets from the API or to bypass any XSRF protection that is in place. The best mitigation would be if every proxied service would be served from a different origin. For example every proxied service could be served from a different port using the same basic auth credentials as the master API and the proxy endpoints could simply redirect to the right port.

**Comment by mbforbes** [comment]
+cc @roberthbailey @brendanburns @caesarxuchao

**Comment by roberthbailey** [comment]
@lavalamp

**Comment by roberthbailey** [comment]
@davidopp

**Comment by lavalamp** [comment]
The CORS headers are not sufficient to prevent this?

**Comment by lavalamp** [comment]
It's easy-ish to add a header requirement, but that's a pretty drastic change and would break all current clients. And what's to prevent evil.com from setting the header?

/proxy is not as bad as it seems at first, because it's only going to show stuff running in the cluster, and that stuff already has full access to the cluster anyway. Eventually we will move this feature out of apiserver completely and into its own component.

**Comment by lavalamp** [comment]
I filed #10366 about /run & /exec.

**Comment by lavalamp** [comment]
OK, so I read up on CSRFs.

POST/PUT etc are already quite inconvenient from a browser, so it's OK if we make them even more inconvenient. But they should continue to work from kubectl & e.g. curl, ideally without any changes, otherwise we'll be changing a LOT of clients. So here's what I propose we do. 

* apiserver starts setting a cookie ("XSRF=cryptographically strong random sequence")
* apiserver checks that a header matches that cookie for mutating requests, and rejects them if it doesn't.

Result of this:

* In kubectl, we ignore cookies, so the cookie value and the header value will always be blank.
* I believe curl also ignores cookies unless you pass a flag.
* But browsers will store the cookies. Attackers won't be able to read the cookie, and therefore won't be able to set the appropriate header. A human trying to do something from the browser will be able to look at the cookie and set the header. This might break the swagger ui? (but it should be easy to fix)

@stephenR does that course of action sound OK? Do we need to adjust any CORS headers for this to work?

I'm still thinking about how to deal with the proxy. That's not so simple.

**Comment by stephenR** [comment]
That solution can be bypassed by a man-in-the-middle if it relies on the fact that a certain cookie exists.
See 'Problems with "protected" cookie clobbering' in:
https://code.google.com/p/browsersec/wiki/Part2#Same-origin_policy_for_cookies
"httponly or secure cookies may get dropped and replaced with evil versions by simply overflowing the per-domain cookie jar."

So a mitm attacker could spoof an HTTP server on the same domain/IP, set a lot of cookies which results in the XSRF cookie getting dropped.

**Comment by smarterclayton** [comment]
Don't use basic auth in front of an API.  Ever. 

This is why we only support Token auth to the api.

**Comment by liggitt** [comment]
> Don't use basic auth or cookies in front of an API. Ever. 

+1000

**Comment by smarterclayton** [comment]
Along those lines we should update https://github.com/kubernetes/kubernetes/blob/master/docs/design/access.md#authentication to be explicit about that - we discussed it (which is why we don't list basic or cookie auth there) but apparently did not write "do not use basic auth"

**Comment by lavalamp** [comment]
I like @smarterclayton's approach. Adding an api exchange layer would take care of the reason why we haven't turned off basic auth yet.

**Comment by roberthbailey** [comment]
Yes please. The main reason we still have basic auth turned on is because bearer token / client certs is considered too high a barrier for users that want to use browsers. If we supported OAuth, that would be just as easy for users and much, much more secure.

**Comment by liggitt** [comment]
OAuth is just the mechanism for getting the token… it would still be used as a bearer token against the API

**Comment by mattjay** [comment]
Just reiterating that using a cookie for a CSRF token is not a viable protection mechanism. The randomized token should be part of the POST body and not header based at all. Preferably the tokens would be changed every request but at the bare minimum they should be tied to an authenticated session so after a logout/session expiration they are no longer valid.

Just a note in case it comes up as a potential solution: Referrer checking is also not good enough since that is a header that can be spoofed as well.

Good reference:
https://www.owasp.org/index.php/CSRF_Prevention_Cheat_Sheet

**Comment by smarterclayton** [comment]
The three laws of CSRF:

1. You can't win
2. You can't break even
3. You can't quit

The only winning move is not to play.

**Comment by liggitt** [comment]
Sending the token as an Authorization Bearer token is ok, it just can't be something the browser sends automatically along with any request to the domain (e.g. basic auth header, client cert, cookie, etc)

**Comment by smarterclayton** [comment]
We have no plans to encourage basic auth to the apiservers.  Closing due to age and lack of interest.

**Comment by falenn** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  curtis.l.bates@gmail.com
    Domain imwiz.com has exceeded the max emails per hour (167/150 (111%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o7.sgmail.github.com ([167.89.101.198]:13048)
	by box969.bluehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.87)
	(envelope-from <bounces+848413-5c7e-dev=imwiz.com@sgmail.github.com>)
	id 1dGU7z-000QI5-S4
	for dev@imwiz.com; Thu, 01 Jun 2017 11:43:20 -0600
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=uykBSmlmy22KuUoYF/VnQvYZ4Oo=; b=IHP9XXT0UrmI6rHh
	tT2FwtnD3V0J8187TkITA9aUsj6JAVqzMVn/37nnFkkbo4JgTTQfojhD05w9ywhn
	qqVQ7rn8IHjNm9kuJHHDMwvX4sPDpk5DI7sjdtLRLY6PSkVTmVCUzgHFAKp8xmPU
	uXkiBxqsWAeu4j/MNMH1Z8xEzzI=
Received: by filter0964p1mdw1.sendgrid.net with SMTP id filter0964p1mdw1-14722-59305218-42
        2017-06-01 17:42:48.647309974 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0003p1iad1.sendgrid.net (SG) with ESMTP id zXSyVj3UTUiXOAbqDTsXEQ
	for <dev@imwiz.com>; Thu, 01 Jun 2017 17:42:48.583 +0000 (UTC)
Date: Thu, 01 Jun 2017 10:42:48 -0700

**Comment by falenn** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  curtis.l.bates@gmail.com
    Domain imwiz.com has exceeded the max emails per hour (171/150 (113%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o4.sgmail.github.com ([192.254.112.99]:11576)
	by box969.bluehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.87)
	(envelope-from <bounces+848413-5c7e-dev=imwiz.com@sgmail.github.com>)
	id 1dGU8B-000QPm-J5
	for dev@imwiz.com; Thu, 01 Jun 2017 11:43:32 -0600
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=Hv5Hgyh41JMi/8JgwjVyWKSkzbA=; b=JGw4TAuyRAnBO53n
	IuNyJBP5ayR7OxUZj/aSpL+T3o18Kg368xxIJF6lb7xrOKd3BKH+TseCHukCLZpM
	L6Ouae60jVXzaMG3E8S/Ha0Zmi7P/DNEz0CMQ2OGG6b3M9AYu/G2a/onJYyumoLR
	QuPCDUyugqMXXpo8qoecYgu/xL4=
Received: by filter0994p1mdw1.sendgrid.net with SMTP id filter0994p1mdw1-14427-5930521F-18
        2017-06-01 17:42:55.391238116 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0005p1iad1.sendgrid.net (SG) with ESMTP id zbbyyFLvSDa-Yvs4FKHzCQ
	for <dev@imwiz.com>; Thu, 01 Jun 2017 17:42:55.344 +0000 (UTC)
Date: Thu, 01 Jun 2017 10:42:55 -0700

**Comment by accesskeeper** [comment]
Maybe i'm wrong but.. Why not just prohibit access to API port on network/firewall level?
