### ISSUE TITLE
Ingress.ingressClassName field is not readded if removed

### ISSUE THREAD

**Issue by elFarto** [kubernetes/kubernetes#103546]
#### What happened:
The default IngressClass was not applied to an Ingress when the ingressClassName field was deleted.

#### What you expected to happen:
The default IngressClass should be added to all new *or* updated Ingress' if they do not posses one.

#### How to reproduce it (as minimally and precisely as possible):
1. Create IngressClass, and add annotation to set as default IngressClass
2. Create Ingress without ingressClassName
3. Edit Ingress (using kubectl edit) and remove the ingressClassName field.
4. Get Ingress and note it's now missing an ingressClassName

#### Anything else we need to know?:
This was initially spotted due to using Lens to edit an Ingress which caused the ingressClassName to be added to the last-applied annotation, which a subsequent apply by the CI/CD system (the source file doesn't contain an ingressClassName) cause to get deleted.

As this is in AWS EKS we use the ALB Load Balancer component to manage an ALB based on the ingresses. The missing ingressClassName causes the ingress to be ignored by that component, and routing removed from the ALB.

Honestly I'm not sure enforcing ingressClassName rigorously is the best idea, but what does having an Ingress with no ingressClassName mean when there's a default IngressClass (esp. as the default is implemented by inserting that field in).

#### Environment:
- Kubernetes version (use `kubectl version`): v1.19.6-eks-49a6c0
- Cloud provider or hardware configuration: AWS EKS

**Comment by aojea** [comment]
is this with the v1beta1 or v1 api version?

**Comment by elFarto** [comment]
This is with Ingress v1

**Comment by aojea** [comment]
I think that the ingress class defaulting happen in the admission plugin

https://github.com/kubernetes/kubernetes/blob/388c2d901d185d34a340fcae566bd38b73bdb704/plugin/pkg/admission/network/defaultingressclass/admission.go#L82-L84

@robscott @rikatz you are more familiar than me with this, is it possible that the update is not being handled by the admission plugin?

**Comment by elFarto** [comment]
I did look at that file before, but didn't see anything. However looking at it again, it's obvious, it's only requesting create notification:

https://github.com/kubernetes/kubernetes/blob/388c2d901d185d34a340fcae566bd38b73bdb704/plugin/pkg/admission/network/defaultingressclass/admission.go#L62

**Comment by liggitt** [comment]
leaving existing Ingress objects alone on update is intentional to preserve backwards compatibility with Ingress objects created prior to the existence of ingressclass

**Comment by thockin** [comment]
Do we want to allow changing the ingress class after creation?

@bowei @robscott

**Comment by robscott** [comment]
Thanks for raising this issue! This does feel like an area where we need to provide a better experience. Usually for these kinds of decisions, I'd look to StorageClass for a reference, but there's not a great parallel since they enforce immutability here. 

We're also somewhat constrained by backwards compatibility here. We can't require this field to be present, but we do at least ensure that both the annotation and field can't be set as an Ingress is being created.

So then it comes down to what we can infer from a user's action. If we get an update to an Ingress resource that no longer includes an IngressClassName, it could mean any of the following:

1. The user wants to remove the IngressClassName and any association with an Ingress controller.
2. The user wants to remove the IngressClassName field and go back to using an annotation instead.
3. The user wants to remove the IngressClassName field and go back to the default value.
4. The user relied on the default IngressClass implementation on create and doesn't expect any changes to IngressClassName as part of this update.

If we were to update the existing webhook to apply to updates, 2 would not be an issue as [Ingresses with the class annotation would be ignored](https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/admission/network/defaultingressclass/admission.go#L106). That leaves 1 as the primary concern. There are other ways to accomplish this such as setting IngressClassName to "none" so that doesn't seem particularly bad. 

I am a bit concerned that adding this defaulting on Ingress update could bite existing users that did not have any concept of class configured on older Ingress resources. It does seem unlikely that users would both have a default ingress class set and have Ingress resources without a class specified though. It seems even more unlikely that they would want the lack of a specified class to be translated to anything other than their default class.

That's a lot of typing to say that I think we should probably add defaulting to updates. Although it is not completely risk free, it is likely our best option.

Does that make sense to everyone else? 

/cc @swetharepakula @cmluciano

**Comment by swetharepakula** [comment]
Would the default be added on all updates? or only on updates that explicitly remove the ingress class name?

If on all updates, at least with the GKE Ingress controller and possible other providers, the following is possible:
1) User creates ingress using v1beta1 with no annotation, or ingress class name set
2) User starts to use v1 and sets a default class
3) If the default class is not GKE ingress and the user updates the Ingress resource a default will get set and cause the Ingress class name to change but not necessarily due to user action.

I see this as a possible side affect for any of cloud-provider that claims Ingresses with no annotation or ingress class name in the v1beta1 case.

My suggestion is to only apply the default on Updates when `ingressClassName` was set and then changed to `nil`. If `ingressClassName` was `nil` previously, it should continue to be `nil`.

This would also work in the situation a user uses `kubectl apply` and depended on the webhook to supply the default on the `ingressClassName` on creation, and if the user uses `kubectl apply` with the same yaml, the webhook on Update would recognize that the class name was changed to `nil` and reapply the default.

**Comment by robscott** [comment]
>My suggestion is to only apply the default on Updates when ingressClassName was set and then changed to nil. If ingressClassName was nil previously, it should continue to be nil.

This is a good idea. I think if we move forward with this, we should limit it to this smaller scope. 

My biggest concern with this issue was the following scenario in a cluster with a default IngressClass:

1. User applies ingress yaml, class is set by defaulting because resource is being created.
2. User applies ingress yaml, class is not set (in manifest or defaulting) so class is effectively unset on the resource.

Fortunately that is not what's actually happening in my experience. If I try repeatedly applying this combination, and even changing fields in the Ingress resource, the IngressClassName field is not unset:

```yaml
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: test-class
  annotations:
    ingressclass.kubernetes.io/is-default-class: "true"
spec:
  controller: example.com/ingress-controller
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: test
            port:
              number: 80
```

The all important 3 way diffing with the `kubectl.kubernetes.io/last-applied-configuration` annotation as an input is saving us here when using kubectl. This may still be an issue for users interacting with the API directly, but in that case it seems more like a change they would be making intentionally than an accidental omission. 

So if an accidental omission is unlikely here, is this really a bug? If someone went out of their way to unset this field, should we let them?

**Comment by thockin** [comment]
Try using `replace` rather than `apply`.  This is the same problem as
clusterIP and NodePort (which I just fixed this week).

The questions I have:

Do we want to allow users to change class at all?  In theory you could have
2 classes with the same provisioner and different params, so update could
be less impactful than delete/recreate.  Is that actually likely?  It seems
more likely that different classes are different enough that it is
effectively a tear-down anyway, which leads to a new IP being assigned.
Hiding that behind a class update seems fraught.

Can we actually "fix" it now, even if we wanted to?  Probably not, if the
field is GA.  But we can learn from it (looking at you, Gateway!)

If we want to support `replace` properly we need to either require
read-modify-write cycles basically EVERYWHERE (which is distasteful to
some) or quietly convert PUT into PATCH.  The `defaultingressclass`
admission only handles create now.  If we want to handle Update cleanly, I
think it should be thru the same mechanism - don't make class special in
the REST stack.  And by "handle cleanly", I think I mean "copy the old
value if it is not set".

IOW:

OnCreate() {
  if s.class == nil {
    set s.class = current default
  }
}

OnUpdate() {
  if new.class == nil && old.class != nil {
    set new.class = old.class
  }
}

**Comment by robscott** [comment]
Although I agree that it seems likely that a change to IngressClassName will result in effectively tearing down and recreating infrastructure, I think there are legitimate use cases where that will not happen. One of the big selling points of an IngressClass (and GatewayClass) resource was that cluster admins could provide a consistent experience across envs. Consider the following scenario:

1. A cluster on vendor A has Ingresses with vendora-xlb class
2. A cluster on vendor B has Ingresses with vendorb-xlb class
3. Cluster admins create generic xlb classes on each cluster that are equivalent to vendored ones
4. Existing Ingresses are migrated to xlb gatewayclass as noop for ingress controllers

Admittedly I'm not sure how likely it is for the above to work seamlessly with every implementation of the API, but I think it's a fairly compelling story if it can. It also helps avoid a bunch of Ingresses with legacy/outdated class names because they were unnecessarily immutable.

>If we want to handle Update cleanly, I think it should be thru the same mechanism

To clarify, do you mean that we should add an update handler to `defaultingressclass` admission?

>by "handle cleanly", I think I mean "copy the old value if it is not set".

Since kubectl apply covers this with a 3 way diff, it seems like accidental omissions of this field are unlikely. I think this would be more likely to prevent intentional removals of this field through direct API calls or `kubectl edit`. Is that something we actually want?

**Comment by thockin** [comment]
>> If we want to handle Update cleanly, I think it should be thru the same mechanism
>
> To clarify, do you mean that we should add an update handler to defaultingressclass admission?

yes

> I think this would be more likely to prevent intentional removals of this field through direct API calls or kubectl edit

Yes, this would prevent un-classing yourself.  By definition, if you have the defaultingressclass enabled you are saying "don't allow ingress with no class", so this seems consistent to me?

**Comment by robscott** [comment]
> if you have the defaultingressclass enabled you are saying "don't allow ingress with no class"

That's a good point. I think one implementation detail is that we'd still want to allow users to unset the IngressClassName field if the annotation was set (similar to the existing defaultingressclass logic for create).

**Comment by thockin** [comment]
PIng @robscott seems like we should accept triage on this?  It also seems like a relatively simple change.  If someone writes it up well, there are lots of people who jump on "easy to approach" issues.

**Comment by mengjiao-liu** [comment]
I want to take it.
/assign

**Comment by thockin** [comment]
Is this still something we're looking at?

**Comment by mengjiao-liu** [comment]
#107018 work on this, but still waiting for a review.

**Comment by robscott** [comment]
@thockin even if we wanted to make IngressClassName immutable, wouldn't that be impossible to do without making a breaking change to a GA API? I double checked our validation and all I could find was this, which does not enforce immutability:

https://github.com/kubernetes/kubernetes/blob/15d12e713f82672ac8951ed14cb5e83ad3288d8b/pkg/apis/networking/validation/validation.go#L310-L314

In Gateway, GatewayClassName is also mutable. We provide the same guidance that implementations should likely treat this transition as a create/delete, but there are possibly some that could provide a more seamless transition.

> So I think the "safest" answer is to recognize that changing ingressClassName from any value to nil is almost certainly an error and just patch it up with the previous value

With this approach I think the biggest risk is that we would break an existing workflow. For example, someone might use a nil "IngressClassName" to indicate that the Ingress should not be implemented. Maybe their controller is broken and they're going through a process of elimination to find the specific Ingress resource that is causing the failure.

The currently proposed approach (#107018) of setting a default value when it is not specified also comes with a risk. If the cluster admin had changed the cluster wide default since the Ingress was originally created. That could result in a routine Ingress update changing the class.

Although each approach has flaws, I think they're both preferable to the current state where it's all too easy to unset IngressClassName.

**Comment by robscott** [comment]
I should also clarify that Gateway does not currently provide any defaulting for GatewayClassName so it's unlikely to run into this specific issue.

**Comment by thockin** [comment]
> even if we wanted to make IngressClassName immutable, wouldn't that be impossible to do without making a breaking change to a GA API? 

yeah, I don't think so.

We can document it as "do not change".

We can MAYBE make it so that setting it to nil patches the old value.
I do not think we should re-apply the default when setting it to nil.

If we think anyone actually relies on changing it, then we CAN'T silently
discard mutations (immutable in effect, but not an error).

> In Gateway, GatewayClassName is also mutable. We provide the same guidance that implementations should likely treat this transition as a create/delete, but there are possibly some that could provide a more seamless transition.

> The currently proposed approach (#107018) of setting a default value when it is not specified also comes with a risk. If the cluster admin had changed the cluster wide default since the Ingress was originally created. That could result in a routine Ingress update changing the class.

exactly

> I should also clarify that Gateway does not currently provide any defaulting for GatewayClassName so it's unlikely to run into this specific issue.

ACK.

**Comment by aojea** [comment]
> So I think the "safest" answer is to recognize that changing ingressClassName from any value to nil is almost certainly an error and just patch it up with the previous value. I do not think we should automatically change nil -> default at all. The open question is whether to allow changing nil -> value or value-A -> value-B after creation? It seems semantically correct but likely to be buggy.

I'm not as familiar with the use cases, but is not possible to hot loop if someone is trying to delete it? 

```
...loop {
  if ingress.ingressClassName != "" {
     delete(ingress.ingressClassName)
  }
```
