### ISSUE TITLE
I deployed 1.22-beta.0. I am having trouble starting kubelet

### ISSUE THREAD

**Issue by mapmiss** [kubernetes/kubernetes#103684]
When I started kubelet, it told me：--network-plugin has been deprecated, will be removed along with dockershim，
--cni-bin-dir has been deprecated, will be removed along with dockershim.
--cni-conf-dir has been deprecated, will be removed along with dockershim.
It does not recognize the previous parameters.

**Comment by yuswift** [comment]
Can you start the `kubelet`? If so, just ignore the message.

**Comment by ehashman** [comment]
Kubernetes does not use issues on this repo for support requests. If you have a question on how to use Kubernetes or to debug a specific issue, please visit our [forums](https://discuss.kubernetes.io/) rather than filing a bug.

Please see https://kubernetes.io/blog/2020/12/02/dockershim-faq/ for more information on the Dockershim deprecation, which has caused these flags to also be deprecated. They should still work and are not being removed until a later release.

/close
