### ISSUE TITLE
Kubelet panic in syncTerminatedPod

### ISSUE THREAD

**Issue by ehashman** [kubernetes/kubernetes#103625]
#### What happened:

When testing #102344 against OpenShift CI, I discovered a panic in the kubelet: https://github.com/openshift/kubernetes/pull/851#issuecomment-877469501

Further investigation revealed that it is possible for `syncTerminatedPod` to panic under certain circumstances: https://github.com/kubernetes/kubernetes/blob/a0d77e5763ac04ddc713bf2e284580d32fd4b079/pkg/kubelet/pod_workers.go#L685-L713

We hit this case when `update.Options.RunningPod != nil` (podStatus remains nil) and `update.WorkType == TerminatedPodWork` (nil will be passed along to `syncTerminatedPod`). I'm not sure why exactly that would happen but it seems possible.

#### What you expected to happen:

Don't panic!

#### How to reproduce it (as minimally and precisely as possible):

Unclear, I've been trying to trace the code/find evidence of this happening in k8s CI but haven't found a match yet. (https://github.com/kubernetes/test-infra/issues/22851 would be nice :smile:)

#### Anything else we need to know?:

/sig node
/cc @rphillips @smarterclayton 

/priority important-soon
/milestone v1.22

#### Environment:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by smarterclayton** [comment]
The bug is that running pods should terminate and then stop, not move to terminated. So something is getting into terminated but should never be in any other work type than terminating.  We'll need more debug to determine why but I suspect that an orphaned pod is still in podSyncStatus at the time it UpdatePod is called, which means it's not seen as being in Terminating.  isRuntimePod forces podSyncStatus to be a certain state, but perhaps it's not resetting a terminated bool.

Asked elana to add a v4 min level in the test jobs that reproduced this so we can see.

**Comment by ehashman** [comment]
@rphillips has bumped, here's a v=4 log with a panic: https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_kubernetes/851/pull-ci-openshift-kubernetes-master-e2e-aws-fips/1414584954561499136/artifacts/e2e-aws-fips/gather-extra/artifacts/nodes/ip-10-0-202-81.us-west-2.compute.internal/journal

**Comment by smarterclayton** [comment]
Elana got the version with more logs and it is indeed the case that the pod is terminating (in this case because a CSI volume hasn't been torn down).

So the bug is:

1. Pod worker for the pod is still running (terminating has completed, but is executing syncTerminatedPod)
2. Housekeeping runs, calls `runtimeCache.GetPods()`, gets a stale result for a pod (thinks the pod is still running, but that's just a stale cache result)
3. Housekeeping asks pod worker to terminate the pod with a runningPod
4. Pod worker sees that the pod is actually not terminating, but terminated, and so RunningPod is inconsistently handled (UpdatePod is not defensive enough)
5. Pod worker passes the kill pod request through to syncTerminatedPod which has a null pod status, causing the panic

In earlier versions of #102344 we explicitly refreshed the runtime cache in `syncTerminatingPod`, but when @Random-Liu and I went through review we removed it and I forgot this race was possible.  The race becomes more possible here because the particular workload Elana is testing involves CSI drivers that have a bad cleanup loop, so syncTerminatedPod is reaching timeout on volume unmount (>3m) before finally succeeding.  This means the race window is huge (invoke UpdatePod(runningPod) on an terminated but not yet cleaned up pod).

I think the real bug is that UpdatePod is not defensive enough - the difference between this race condition (seeing an older runtime container) and a human somehow starting the container up again before it is terminated is pretty similar.  The important difference is that the UpdatePod{... running pod } is intended to clean up orphaned pods - those the pod worker is not tracking.  But we only go into terminated when we are certain the workload is stopped, so if we simply ignore until the pod goes away it might be a while before we kill that container.  We absolutely need a background worker tracking that, which is best to be a pod worker, but it's a bit more work.

So easy fix (remove the possibility of the very common race) is to simply have syncTerminatingPod refresh the pod cache for that one pod.  A slightly less easy fix is to have UpdatePod simply ignore the runningPod request until the next housekeeping loop (which in some cases with bad csi drivers could be a few minutes or so).  The most correct fix is to ensure syncTerminated pod has an opportunity to maintain its invariants.

Pondering variations here of fixes.  The easy fixes will defiintely be "safe", but "slight regression in latency in a few rare cases".  Serializing the pod worker caused this, but it's in theory rare.

**Comment by Random-Liu** [comment]
> Pod worker sees that the pod is actually not terminating, but terminated, and so RunningPod is inconsistently handled (UpdatePod is not defensive enough)

My understanding is that we make pod worker the source of truth for pod state. In this kind of race condition, as long as the request is sent to the pod worker, and the pod UID matches, it should be able to reconcile the state.

> So easy fix (remove the possibility of the very common race) is to simply have syncTerminatingPod refresh the pod cache for that one pod. 

Even if we do this, it is not atomic, the race condition still exists in theory. We probably should make the pod worker be able to reconcile the state.

**Comment by smarterclayton** [comment]
Here's the most concerning scenario:

1. Pod is terminated and then deleted from apiserver
2. `syncTerminatingPod` kills the container
3. `syncTerminatedPod` is taking a very long time
4. shortly after 2, housekeeping fires and sees the stale cache, triggers a kill
5. (proposed change) ignore the kill request (since terminated pod is running)
6. user restarts container in the pod that references a volume mount
7. `syncTerminatedPod` can't make progress because volume detach can't make progress because the restarted container is holding a device lock / has a file open / w/e
8. the pod worker for that pod retries forever

https://github.com/openshift/kubernetes/pull/855/commits/21a37b5ef5f445a2f21c478fbb314a647f75d5a0 is the minimal fix that ignores (5) but I'm thinking through how to handle 8.  I don't think we should do the easy fix (and resync the cache, you're right, it's still a race).

I'm potentially considering having the pod worker invoke syncTerminatingPod in the event syncTerminatedPod exits with an error, or simply have syncTerminatedPod do it if it would return an error to address 8.

**Comment by Random-Liu** [comment]
> user restarts container in the pod that references a volume mount

But this basically means that after `syncPodTerminating`, there could still be running containers.

In that case, this wouldn't be the only problem, the whole assumption the refactor builds on becomes invalid?

**Comment by mrunalp** [comment]
> BTW, restarting container may happen to docker, but containerd doesn't support it (at least it can't be done easily), not sure about cri-o.

cri-o doesn't support restarting a container, either.

**Comment by smarterclayton** [comment]
The assumption in the kubelet is there are no more containers started by the kubelet, which is indeed safe.  That doesn’t prevent bugs in CRI implementations, user error, cosmic rays, basically computers.  It’s unlikely and not something we really designed for before, but the prerefactor code would survive it.

https://github.com/openshift/kubernetes/pull/855

Appears to have gotten past the issue as expected.

I’ll look at what it would take to mitigate the possibility of zombie containers such that the pod worker converges even if volume mount can’t be completed.

**Comment by smarterclayton** [comment]
In general a little defensiveness here to unreliable external components has only minor cost, and some mitigation seems reasonable.

**Comment by smarterclayton** [comment]
Opened the first part of the fix in https://github.com/kubernetes/kubernetes/pull/103668
