### ISSUE TITLE
[Failing test] [sig-node] InodeEviction [Slow] [Serial] [Disruptive][NodeFeature:Eviction] when we run containers that should cause DiskPressure should eventually evict all of the correct pods

### ISSUE THREAD

**Issue by ehashman** [kubernetes/kubernetes#103623]
##### Error text:
```
_output/local/go/src/k8s.io/kubernetes/test/e2e_node/eviction_test.go:475
pod memory-hog-pod failed; expected Status.Reason to be Evicted, but got 
Expected
    <string>: 
to equal
    <string>: Evicted
_output/local/go/src/k8s.io/kubernetes/test/e2e_node/eviction_test.go:632
```
#### Recent failures:
[7/9/2021, 3:24:55 AM ci-kubernetes-node-kubelet-eviction](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-eviction/1413444022743076864)
[7/8/2021, 10:54:57 PM ci-kubernetes-node-kubelet-eviction](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-eviction/1413376073223114752)
[7/8/2021, 6:24:54 PM ci-kubernetes-node-kubelet-eviction](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-eviction/1413308123812204544)

/kind failing-test

Appears to have started failing after ~6pm 07/08.

/sig node

**Comment by endocrimes** [comment]
This appears to be caused by an actual regression.

After digging into this and the other eviction failures, it appears that eviction itself happens in most cases (I haven't finished debugging storage tests). However, rather than pods transitioning to an `Evicted` state, they very briefly become `Evicted`, and then migrate to `Error`. This was not true in v1.21.1.

I'm running a bisect between 1.21.1 and now to figure out when exactly this broke, which should be done soon-ish.

**Comment by endocrimes** [comment]
Finished bisecting - Looks like the regression was introduced by 3eadd1a9ead7a009a9abfbd603a5efd0560473cc (cc @smarterclayton).

Going to investigate the changes and see if I can figure out a fix, not sure if this issue should be converted into a bug to block 1.22 or not though.

**Comment by endocrimes** [comment]
Digging further into the logs - It looks like they confirm that we do indeed correctly evict the pod, and then on the next SyncLoop reconcile, we patch the pod again with an `Error` state - so I'm gonna take a look into that now, guessing a lifecycle case got missed in the refactoring.

**Comment by endocrimes** [comment]
It seems like a race between PLEG and the Eviction termination - While the termination is completing, PLEG detects that the underlying containers have stopped, and writes the conflicting status.

[annotated.log](https://github.com/kubernetes/kubernetes/files/6831813/annotated.log)

**Comment by smarterclayton** [comment]
Thanks for the info, looking

/assign smarterclayton

**Comment by smarterclayton** [comment]
```

// CONTAINERS NOT READY, ERROR STATE WRITTEN TO POD STATUS

Jul 16 17:12:08 mir kubelet[2252318]: I0716 17:12:08.289741 2252318 status_manager.go:621] "Patch status for pod" pod="memory-allocatable-eviction-test-2441/memory-hog-pod" patch="{\"metadata\":{\"uid\":\"b42ff6b4-f887-4569-aef0-4fb4854694c3\"},\"status\":{\"$setElementOrder/conditions\":[{\"type\":\"Initialized\"},{\"type\":\"Ready\"},{\"type\":\"ContainersReady\"},{\"type\":\"PodScheduled\"}],\"conditions\":[{\"lastTransitionTime\":\"2021-07-16T15:12:08Z\",\"message\":\"containers with unready status: [memory-hog]\",\"reason\":\"ContainersNotReady\",\"status\":\"False\",\"type\":\"Ready\"},{\"lastTransitionTime\":\"2021-07-16T15:12:08Z\",\"message\":\"containers with unready status: [memory-hog]\",\"reason\":\"ContainersNotReady\",\"status\":\"False\",\"type\":\"ContainersReady\"}],\"containerStatuses\":[{\"containerID\":\"docker://3fd648ed52224cc6488690d420ae77522857dabd503e8b6c0d60bad1c9813218\",\"image\":\"k8s.gcr.io/stress:v1\",\"imageID\":\"docker-pullable://k8s.gcr.io/stress@sha256:f00aa1ddc963a3164aef741aab0fc05074ea96de6cd7e0d10077cf98dd72d594\",\"lastState\":{},\"name\":\"memory-hog\",\"ready\":false,\"restartCount\":0,\"started\":false,\"state\":{\"terminated\":{\"containerID\":\"docker://3fd648ed52224cc6488690d420ae77522857dabd503e8b6c0d60bad1c9813218\",\"exitCode\":2,\"finishedAt\":\"2021-07-16T15:12:07Z\",\"reason\":\"Error\",\"startedAt\":\"2021-07-16T15:08:13Z\"}}}],\"message\":null,\"reason\":null}}"
```

from your example implies someone wrote a new pod reason, which should only come from the pod worker loop.  I checked where readiness was setting status and thought it was not overriding this, but if so I missed something.  Looking to see what container readiness status is allowed to change (once a pod is out of terminated, no status update should overwrite that because by definition after terminating containers the status can't change)...

**Comment by smarterclayton** [comment]
The patch has 

```
\"message\":null,
\"reason\":null}}"
```

in it, which clears the values.  That is not expected, because container status should have no impact.  Looking at why that is with a unit test, that's definitely the bug:

> When SetContainerReadiness is invoked, the message and reason should not be changed.

**Comment by rphillips** [comment]
Looks like the API is modifying the pod and the RECONCILE event is calling into HandlePodReconcile. Perhaps HandlePodReconcile needs to detect the terminated pod?

**Comment by smarterclayton** [comment]
This is a race condition between different parts of the Kubelet, exposing a bug in how the kubelet writes status to the apiserver.

1. syncTerminatingPod creates the "final" status for the pod and sends it to status manager with reason/message set
2. status manager writes that update to the apiserver
3. a probe that was running while termination was happening fails and the probe manager invokes SetContainerReadiness (the probe manager is slow / was delayed)
4. the status manager calculates the diff of status, but reason/message from the internal status manager cache is apparently empty (it should be set from 1 above)
5. status manager reads the latest version of the pod status from 2 above, then calculates a patch that clears message/reason

I'm trying to determine right now why reason/message are empty in 4

**Comment by smarterclayton** [comment]
```
I0719 15:04:54.512047  624273 status_manager.go:483] "DEBUG: Container status" pod="priority-memory-eviction-ordering-test-5703/memory-hog-pod" podUID=462d4a5c-dd57-4023-9a83-457879fa3ba7 oldReason="Evicted" reason=""
```

This is showing that updateStatusInternal drops it during normalize

**Comment by smarterclayton** [comment]
Ok, so the root cause is:

1. The kubelet has no mechanism for preserving the reason/message of a pod status from previous status updates (convertStatusToAPIStatus always results in a new, empty reason/message)
2. Because we aren't refreshing the pod status cache in syncTerminatingPods, we invoke multiple SetPodStatus calls during termination (one at the beginning of syncTerminatedPod, one at the end in TerminatePod) in order to reduce latency of syncing container status on terminated containers (because volume unmount could take a while)
3. The combo of 1 and 2 causes Evict message and reason to be set during syncTerminatingPod, then reset at the beginning of syncTerminatedPod

Container status merging takes into account the old pod status from our cache (or the apiserver) and then the phase is calculated.  If the transition is illegal, we error (and do no update).  In theory both Reason/Message should be cleared when the kubelet calculates a different phase.

I am proposing a change to generateAPIPodStatus to preserve Reason/Message from the recent status and clear it on detected phase change.  I will attach that PR.  That also will ensure transitions from Running -> Pending that can occur don't lose the message until the phase transition happens (for instance if a pod fails soft admission).
