### ISSUE TITLE
[Failing Test] [sig-storage] subPath should unmount if pod is deleted while kubelet is down (ci-kubernetes-e2e-gci-gce-serial)

### ISSUE THREAD

**Issue by lambdanis** [kubernetes/kubernetes#103651]
#### Which jobs are failing:
ci-kubernetes-e2e-gci-gce-serial (gce-cos-master-serial)

#### Which test(s) are failing:
Four `Kubernetes e2e suite.[sig-storage] * Volumes [Driver: *] [Testpattern: *] subPath should unmount if pod is * deleted while kubelet is down [Disruptive][Slow][LinuxOnly]` tests:

* Kubernetes e2e suite.[sig-storage] CSI Volumes [Driver: csi-hostpath] [Testpattern: Dynamic PV (default fs)] subPath should unmount if pod is gracefully deleted while kubelet is down [Disruptive][Slow][LinuxOnly]
* Kubernetes e2e suite.[sig-storage] In-tree Volumes [Driver: hostPath] [Testpattern: Inline-volume (default fs)] subPath should unmount if pod is gracefully deleted while kubelet is down [Disruptive][Slow][LinuxOnly]
* Kubernetes e2e suite.[sig-storage] In-tree Volumes [Driver: hostPathSymlink] [Testpattern: Inline-volume (default fs)] subPath should unmount if pod is gracefully deleted while kubelet is down [Disruptive][Slow][LinuxOnly]
* Kubernetes e2e suite.[sig-storage] CSI Volumes [Driver: csi-hostpath] [Testpattern: Dynamic PV (default fs)] subPath should unmount if pod is force deleted while kubelet is down [Disruptive][Slow][LinuxOnly]

#### Since when has it been failing:
`Kubernetes e2e suite.[sig-storage] CSI Volumes [Driver: csi-hostpath] [Testpattern: Dynamic PV (default fs)] subPath should unmount if pod is force deleted while kubelet is down [Disruptive][Slow][LinuxOnly]` is failing since June 29th 2021 (but the first failure was different than more recent ones). Commit 1151dc1ee, infra commit a97a41ecc, [build](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-serial/1409809442718879744).

Other three tests are failing since July 9th 2021. Commit 617064d73, infra commit 27c63cf72, [build](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-serial/1413428671103897600).

#### Testgrid link:
Testgrid: https://k8s-testgrid.appspot.com/sig-release-master-informing#gce-cos-master-serial&width=20
Prow history: https://prow.k8s.io/job-history/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-serial

#### Reason for failure:
For CSI Volumes:
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/testsuites/subpath.go:348
Jul  9 10:01:28.012: while cleaning up resource
Unexpected error:
    <errors.aggregate | len:1, cap:1>: [
        [
            {
                msg: "persistent Volume pvc-8c22a1cc-d586-4f3b-a6ce-eba8c7425fa6 not deleted by dynamic provisioner: PersistentVolume pvc-8c22a1cc-d586-4f3b-a6ce-eba8c7425fa6 still exists within 5m0s",
                err: {
                    s: "PersistentVolume pvc-8c22a1cc-d586-4f3b-a6ce-eba8c7425fa6 still exists within 5m0s",
                },
            },
        ],
    ]
    persistent Volume pvc-8c22a1cc-d586-4f3b-a6ce-eba8c7425fa6 not deleted by dynamic provisioner: PersistentVolume pvc-8c22a1cc-d586-4f3b-a6ce-eba8c7425fa6 still exists within 5m0s
occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/testsuites/subpath.go:183
```

For In-tree Volumes:
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/testsuites/subpath.go:341
Jul  9 14:04:08.625: Expected grep stdout to be empty (i.e. no subpath mount found).
Expected
    <string>: 963 355 0:40 /provisioning-7593/provisioning-7593 /var/lib/kubelet/pods/1cab2854-f6e2-400c-9136-9986d769b168/volume-subpaths/test-volume/test-container-subpath-inlinevolume-ttr8/0 rw shared:27 - tmpfs tmpfs rw
    966 125 0:40 /provisioning-7593/provisioning-7593 /var/lib/kubelet/pods/1cab2854-f6e2-400c-9136-9986d769b168/volume-subpaths/test-volume/test-container-subpath-inlinevolume-ttr8/0 rw,nosuid,nodev,noexec shared:27 - tmpfs tmpfs rw
    965 383 0:40 /provisioning-7593/provisioning-7593 /home/kubernetes/containerized_mounter/rootfs/var/lib/kubelet/pods/1cab2854-f6e2-400c-9136-9986d769b168/volume-subpaths/test-volume/test-container-subpath-inlinevolume-ttr8/0 rw,nosuid,nodev,noexec shared:27 - tmpfs tmpfs rw
    964 381 0:40 /provisioning-7593/provisioning-7593 /home/kubernetes/containerized_mounter/rootfs/var/lib/kubelet/pods/1cab2854-f6e2-400c-9136-9986d769b168/volume-subpaths/test-volume/test-container-subpath-inlinevolume-ttr8/0 rw,nosuid,nodev,noexec shared:27 - tmpfs tmpfs rw
    
to be empty
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/utils/utils.go:202
```

#### Anything else we need to know:

There is another open issues for failing tests in this job: https://github.com/kubernetes/kubernetes/issues/102865 Failures reported there are about missing metrics, and were occuring before unmounting problems. So I opened a new issue, even though it's the same SIG. These tests don't look related to me, but I don't have enough context, maybe they somehow are.

/sig storage
/kind failing-test
/milestone 1.22

**Comment by lambdanis** [comment]
/cc @kubernetes/release-team-leads 

(my close/reopen yesterday was accidental, sorry)

**Comment by verult** [comment]
I can take a look

/assign

**Comment by verult** [comment]
The non-subpath counterpart of this test is passing:
* `Kubernetes e2e suite.[sig-storage] GenericPersistentVolume[Disruptive] When kubelet restarts Should test that a volume mounted to a pod that is deleted while the kubelet is down unmounts when the kubelet returns.`
* `Kubernetes e2e suite.[sig-storage] GenericPersistentVolume[Disruptive] When kubelet restarts Should test that a volume mounted to a pod that is force deleted while the kubelet is down unmounts when the kubelet returns.`

These tests seem to use the default storageclass, whereas failing tests use in-tree hostpath and csi-hostpath

**Comment by verult** [comment]
The CSI ones are failing because the hostpath driver never received a NodeUnstage (whereas it did in passing tests), causing the driver to error on volume deletion.

**Comment by verult** [comment]
In the failed run kubelet has this error: `E0720 18:20:42.733578   77006 operation_generator.go:881] UnmountVolume.MarkVolumeAsUnmounted failed for volume "" (UniqueName: "pvc-e6562d78-a615-4e89-afe8-290135af1ac0") pod "f59c76e3-e508-45c2-8509-4bd4c2ad70c6" (UID: "f59c76e3-e508-45c2-8509-4bd4c2ad70c6") : no volume with the name "pvc-e6562d78-a615-4e89-afe8-290135af1ac0" exists in the list of attached volumes`

which seems to have prevented kubelet from triggering a UnmountDevice. This error didn't exist in a successful run.

**Comment by msau42** [comment]
Hostpath driver can run with and without support for attach. Do you know which mode is enabled for this test?

**Comment by msau42** [comment]
Between the last passing time and when the test started failing, are there any PRs merged that look suspicious?

**Comment by verult** [comment]
According to csi-attacher logs, attach is disabled for both the good run and the failing run.

Haven't spotted any obvious PRs so far, but I did find this: in the successful run, the log message for the successful `TearDown` is this:

`I0709 03:42:55.321105   67520 operation_generator.go:859] UnmountVolume.TearDown succeeded for volume "kubernetes.io/csi/csi-hostpath-provisioning-787^86c283e3-e067-11eb-bae5-92a225334f0f" (OuterVolumeSpecName: "test-volume") pod "3f724a8e-d03f-463a-a814-ca06b7793692" (UID: "3f724a8e-d03f-463a-a814-ca06b7793692"). InnerVolumeSpecName "pvc-8f0adee7-d3e7-4bcd-8f83-50731dadeb8d". PluginName "kubernetes.io/csi", VolumeGidValue ""`

and the failed run:
`I0720 18:20:42.733427   77006 operation_generator.go:866] UnmountVolume.TearDown succeeded for volume "pvc-e6562d78-a615-4e89-afe8-290135af1ac0" (OuterVolumeSpecName: "") pod "f59c76e3-e508-45c2-8509-4bd4c2ad70c6 (UID: "f59c76e3-e508-45c2-8509-4bd4c2ad70c6"). InnerVolumeSpecName "pvc-e6562d78-a615-4e89-afe8-290135af1ac0". PluginName "kubernetes.io/csi", VolumeGidValue ""`

so the reconstructed volume names are somehow different. Checking reconstruction logic

**Comment by msau42** [comment]
This merged 12 days ago and was a pretty big change to pod lifecycle and could have trickling impact to volume manager. Does the timing of test failure match?

https://github.com/kubernetes/kubernetes/pull/102344

**Comment by msau42** [comment]
There is also this reconstruction fix that merged yesterday and seems related to outer vs inner spec name. I don't know if that will help fix this issue: https://github.com/kubernetes/kubernetes/pull/103181

**Comment by msau42** [comment]
cc @jingxu97

**Comment by verult** [comment]
Last successful run started at 7/8 17:49 PT, first failing run started at 7/9 2:23 PT. #102344 was merged at 7/8 16:48 PT, so it's possible (if there's a delay in picking up master)

Also this is in the failing kubelet logs but not in the successful one:

`I0720 18:20:42.719097   77006 reconciler.go:411] "Could not construct volume information, cleaning up mounts" podName=f59c76e3-e508-45c2-8509-4bd4c2ad70c6 volumeSpecName="pvc-e6562d78-a615-4e89-afe8-290135af1ac0" err="volume: \"kubernetes.io/csi/csi-hostpath-provisioning-153^00c6da00-e987-11eb-bf67-7a98fb96c8a5\" is not mounted"`

`I0720 18:20:42.719120   77006 reconciler.go:444] "Reconciler sync states: could not find volume information in desired state, clean up the mount points" podName=f59c76e3-e508-45c2-8509-4bd4c2ad70c6 volumeSpecName="pvc-e6562d78-a615-4e89-afe8-290135af1ac0"
`

**Comment by verult** [comment]
The newly introduced log message here exists in the failing kubelet logs but not the successful one:

https://github.com/kubernetes/kubernetes/pull/102344/files#diff-367a5b4b2c1d046a94b4eeb471202ef0c3b2a2af3b15fd4d061a17277dd364cfR446

**Comment by ehashman** [comment]
https://storage.googleapis.com/k8s-gubernator/triage/index.html?job=ci-kubernetes-e2e-gci-gce-serial

Failures starting 07/08:
- https://storage.googleapis.com/k8s-gubernator/triage/index.html?job=ci-kubernetes-e2e-gci-gce-serial#7b9f1bc633d8a3bff2bf
- https://storage.googleapis.com/k8s-gubernator/triage/index.html?job=ci-kubernetes-e2e-gci-gce-serial#e78b8769da8d0ef405c9
- https://storage.googleapis.com/k8s-gubernator/triage/index.html?job=ci-kubernetes-e2e-gci-gce-serial#7f132f1d027bd7669eb4
- https://storage.googleapis.com/k8s-gubernator/triage/index.html?job=ci-kubernetes-e2e-gci-gce-serial#2c2c512e1cf0bc381bd7

/sig node
for visibility

**Comment by jingxu97** [comment]
I think #102344 caused the failures. Before after kubelet restarts, pod will still be in desired state (even through it is in terminating state), so that clean up mounts can be done completely. 

I think now, terminating pods will not be added back to desired state, but reconstruction to actual state cannot completely clean up mounts. 
I am testing it about this.

**Comment by smarterclayton** [comment]
Is there a reason why reconstruction to actual state cannot clean up mounts?  Note that a pod can be force deleted at any time, so a terminating pod that is force deleted would still have to be capable of being cleaned up (it won't be in desired state)?

(note that the expectation of the changes in #102344 is that terminating and fully terminated and "never seen" are all completely equivalent from the perspective of other loops in the kubelet)

If I understand you correctly, is this an existing bug that we're now triggering consistently?

**Comment by msau42** [comment]
We have both "grace pod deletion" and "force pod deletion" test cases that are failing.

**Comment by smarterclayton** [comment]
There were a couple of key changes to volume loops:

```
@@ -203,8 +200,8 @@ func (dswp *desiredStateOfWorldPopulator) findAndAddNewPods() {
 
        processedVolumesForFSResize := sets.NewString()
        for _, pod := range dswp.podManager.GetPods() {
-               if dswp.isPodTerminated(pod) {
-                       // Do not (re)add volumes for terminated pods
+               if dswp.podStateProvider.ShouldPodContainersBeTerminating(pod.UID) {
+                       // Do not (re)add volumes for pods that can't also be starting containers
                        continue
                }
```

Roughly before was "it looks like it's got no running pods", and after my change is "we are going to be stopping all the containers from now on".  So this change meant that once a pod starts terminating, we are in "tearing down mode" and so my understanding of this method was that "any pod where containers are being torn down is not in the desired state of the world".  After a restart, we would definitely not add a pod back that was in terminating state into desired state of the world, but "restart + this change" should be roughly equivalent to "restart and force delete while restart is processing"

The other change was in 

```
@@ -245,36 +239,9 @@ func (dswp *desiredStateOfWorldPopulator) findAndRemoveDeletedPods() {
```

which changed a live CRI read (which was trying to enforce that the dsowp is synchronized with the pod worker) into a check against the pod worker directly (the pod worker can provide authoritative answers to "this pod has no running containers" now).  The latter change seems less likely to impact you.

**Comment by jingxu97** [comment]
Thank you @smarterclayton for the details!
I think your change is making the right change, but unfortunately some of volume management still have issues, and so the tests rely on some behaviors that is not very right (pod volume is added back to desired state even after it is in terminating)

The cleanup mount currently does not have the logic to clean up global mount point if the volume plugin sets it up. I am still testing more and will share more details.

**Comment by dims** [comment]
@jingxu97 @smarterclayton is this a release blocker?

**Comment by msau42** [comment]
Yes, this impacts volume cleanup if kubelet restarts for any reason.

**Comment by verult** [comment]
On a kube-up cluster running the latest master against the latest e2e binary, I was able to reproduce the in-tree failures but not the CSI ones for some reason.

Will focus on in-tree failures for the time being

**Comment by dims** [comment]
marking release-blocker per @ehashman note on slack: https://kubernetes.slack.com/archives/C2C40FMNF/p1627323614028800

**Comment by verult** [comment]
We were able to find the trigger for the CSI failures - on 6/29 there was a change in the hostpath driver test manifest, and the driver's `--check-volume-lifecycle` is enabled.

https://github.com/kubernetes/kubernetes/blob/ee5df7cbcfffaddece66944a528fccb07430d29a/test/e2e/storage/drivers/csi.go#L240

This makes the driver return an error instead of only logging a warning message on `DeleteVolume()` if the volume isn't unstaged properly. IIUC there's a long standing issue that reconstruction doesn't handle node unstage. @jingxu97 @msau42 could you confirm? If that's the case, then these CSI failures are *not release blocking*.

Furthermore, the CSI test with graceful delete started to fail on 7/9 because of #102344 since graceful and force deletes are now considered the same from the point of view of the volume manager.

**Comment by msau42** [comment]
> `--check-volume-lifecycle` is enabled.

When that check was enabled, I don't think we realized it would impact the reconstruction path; it was enabled to validate a different issue.

Are we running into the issue that reconstruction of staging directories isn't supported (https://github.com/kubernetes/kubernetes/issues/85476) OR is it that our reconstruction path requires drivers to have real mount points (https://github.com/kubernetes/kubernetes/issues/79980)?

Either way since both are known gaps with reconstruction, I think it makes sense to to disable the flag until we can address those issues.

**Comment by dobsonj** [comment]
@verult @msau42 I was looking at this today too, trying to understand the underlying cause. That `--check-volume-lifecycle` is why the failures are being reported now, but the part that I didn't understand is why NodeUnstageVolume is not being called for these volumes.
In this instance:
https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-serial/1418942168139042816/artifacts/_sig-storage_CSI_Volumes/_Driver_csi-hostpath_/_Testpattern_Dynamic_PV_default_fs_subPath/should_unmount_if_pod_is_gracefully_deleted_while_kubelet_is_down_Disruptive_Slow_LinuxOnly_/csi-hostpathplugin-0-hostpath.log
The DeleteVolume request fails because a staged path is still present:
```
E0724 17:28:16.113610       1 server.go:110] GRPC error: rpc error: code = Internal desc = Volume '4fa69976-eca4-11eb-8ee4-6acdf5008fc2' is still used (attached: false, staged: [/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-e4a92b67-2be1-4fd6-91c2-25e9d0d0898d/globalmount], published: []) by 'bootstrap-e2e-minion-group-wfgl' node
```
And in the kubelet log, NodeUnpublishVolume is called
https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-serial/1418942168139042816/artifacts/bootstrap-e2e-minion-group-wfgl/kubelet.log
```
I0724 17:27:41.022546   13572 csi_client.go:357] kubernetes.io/csi: calling NodeUnpublishVolume rpc: [volid=4fa69976-eca4-11eb-8ee4-6acdf5008fc2, target_path=/var/lib/kubelet/pods/8cd17601-db7d-40eb-b048-74aa13971930/volumes/kubernetes.io~csi/pvc-e4a92b67-2be1-4fd6-91c2-25e9d0d0898d/mount
```
Then we hit this error:
```
E0724 17:27:41.028389   13572 operation_generator.go:881] UnmountVolume.MarkVolumeAsUnmounted failed for volume "" (UniqueName: "pvc-e4a92b67-2be1-4fd6-91c2-25e9d0d0898d") pod "8cd17601-db7d-40eb-b048-74aa13971930" (UID: "8cd17601-db7d-40eb-b048-74aa13971930") : no volume with the name "pvc-e4a92b67-2be1-4fd6-91c2-25e9d0d0898d" exists in the list of attached volumes
```
And NodeUnstageVolume is never called for this volume (same for other failures I looked at) so DeleteVolume keeps failing.
So I think you're right that it's triggered by reconstruction, and it looks similar to https://github.com/kubernetes/kubernetes/issues/85476, except in this case the restart happened before NodeUnpublishVolume.

**Comment by verult** [comment]
And it's probably not https://github.com/kubernetes/kubernetes/issues/79980 since the test uses a PVC

**Comment by verult** [comment]
Will look deeper into why UnmountDevice wasn't issued as well, but some update on the in-tree tests: the force delete test is skipped for the in-tree hostpath CSI driver because of #61446

https://github.com/kubernetes/kubernetes/blob/ee5df7cbcfffaddece66944a528fccb07430d29a/test/e2e/storage/testsuites/subpath.go#L352-L355

Graceful tests are now failing as well because they behave like force tests due to #102344

**Comment by msau42** [comment]
> And it's probably not #79980 since the test uses a PVC

I don't think the issue is related to PVC or not. I think it's related to drivers that do not actually mount devices as a separate filesystem than the root.

**Comment by jingxu97** [comment]
There are three possible flows during kubelet restart

1. in pod gracefully delete case, the pod still exists (it is not considered as terminated in function isPodTerminated(); note that this logic has some changes after  #102344 https://github.com/kubernetes/kubernetes/issues/103651#issuecomment-884411621 ), so pod volume will be added back to desired state, and reconciler will try to set up volume and fill in actual state. When pod volume is finally deleted from desired state, reconciler will trigger teardown with information from actual state to unpublish and unstage volume.

2. if pod is forcefully deleted, pod volume will not be added in desired state. If volume reconstruction succeeds (be able to reconstruct volume spec), volume will be added back into actual state. Then  reconciler will trigger teardown with information from actual state to unpublish and unstage volume (this part is similar to case 1).

3. the last case is reconstruction failed (in this csi-host-path test, reconstruction will fail [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/volumemanager/reconciler/reconciler.go#L567) due to issue related to [isLikelyNotMountPoint](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/mount-utils/mount_linux.go#L301), it fail to check mount point for csi hostpath driver because it is using a bind mount of the same device ). In this case, reconciler will try to clean up mounts directly, but only published volume path, not the staged volume path (this logic is not implemented due to missing information).

As a workaround, we can now disable check-volume-lifecycle if it does not cause other issues. Then we will work on to make sure csi-host-path driver can pass volume mountpoint check during reconstruction.

**Comment by verult** [comment]
This issue is now mitigated with #103937 merged. There are two longer-term issues that are isolated to hostpath plugins (and maybe other plugins that are similar in behavior, perhaps emptydir and similar?):

1. #61446
1. Issue related to IsLikelyNotMountPoint as @jingxu97 mentioned.

Because these don't impact the core volume machinery and are not regressions, this issue doesn't need to be release blocking. We'll close this issue once (2) is tracked.

**Comment by msau42** [comment]
https://github.com/kubernetes/kubernetes/issues/79980 is the IsLikelyNotMountPoint issue

**Comment by jingxu97** [comment]
after  #103937  is merged, two csi-hostpath driver subpath test can pass, and two in-tree driver gracefully delete tests were skipped. 
https://k8s-testgrid.appspot.com/sig-release-master-informing#gce-cos-master-serial&width=20

**Comment by dims** [comment]
@jingxu97 can you please cherry-pick #103937 to release-1.22 branch?

**Comment by ehashman** [comment]
Opened cherry-pick, please review: https://github.com/kubernetes/kubernetes/pull/103983

**Comment by wojtek-t** [comment]
> and two in-tree driver gracefully delete tests were skipped.

@jingxu97 - what is the plan for reenabling them?

**Comment by savitharaghunathan** [comment]
cherry-pick https://github.com/kubernetes/kubernetes/pull/103983 merged!

**Comment by jingxu97** [comment]
> > and two in-tree driver gracefully delete tests were skipped.
> 
> @jingxu97 - what is the plan for reenabling them?

Cheng and I will work on solving IsLikelyNotMountPoint issue for hostpath drivers. That should allow test to pass and we can enable them.

**Comment by ehashman** [comment]
Can this be removed from the milestone now that the workarounds have been merged, while leaving this issue open to track further work?

**Comment by msau42** [comment]
We can use existing issue https://github.com/kubernetes/kubernetes/issues/79980 to track the real fix.

/close
