### ISSUE TITLE
[Flaking Test] [sig-scalability] restarting konnectivity-agent (ci-kubernetes-e2e-gci-gce-scalability)

### ISSUE THREAD

**Issue by lambdanis** [kubernetes/kubernetes#103742]
#### Which jobs are flaking:

* [ci-kubernetes-e2e-gci-gce-scalability](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/1415996980873662464) (master-blocking, gce-cos-master-scalability-100)
* [ci-kubernetes-e2e-gci-gce-scalability-node-killer](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability-node-killer/1415332695013068800) (gce-cos-master-scalability-100-nodekiller)

#### Which test(s) are flaking:

* `ClusterLoaderV2: load overall (testing/load/config.yaml)`
* `ClusterLoaderV2: load: [step: 31] gathering measurements`
* `e2e.go: ClusterLoaderV2`

#### Testgrid link:

[sig-release-master-blocking/gce-cos-master-scalability-100](https://k8s-testgrid.appspot.com/sig-release-master-blocking#gce-cos-master-scalability-100&width=20)
[sig-scalability-experiments/gce-cos-master-scalability-100-nodekiller](https://k8s-testgrid.appspot.com/sig-scalability-experiments#gce-cos-master-scalability-100-nodekiller&width=20)

#### Reason for failure:

`konnectivity-agent` is restarting:
```
:0
[measurement call TestMetrics - TestMetrics error: [action gather failed for SystemPodMetrics measurement: restart counts violation: RestartCount(konnectivity-agent-9rxpk, konnectivity-agent)=1, want <= 0]]
:0
```

#### Anything else we need to know:

Triage search: https://storage.googleapis.com/k8s-gubernator/triage/index.html?text=action%5C%20gather%5C%20failed%5C%20for%5C%20SystemPodMetrics%5C%20measurement%3A%5C%20restart%5C%20counts%5C%20violation%3A%5C%20RestartCount%5C(konnectivity%5C-agent&job=gce-scal
(Note: Triage is currently having problems (https://github.com/kubernetes/test-infra/issues/22906), but it works on Firefox for me, just not on Chrome.)

Same failures were reported in https://github.com/kubernetes/kubernetes/issues/102784 for `ci-kubernetes-e2e-gce-scale-performance` (`gce-master-scale-performance`). The last related failure for this job was a month ago (June 14th, [this build](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/1404484257878904832)). So maybe flags tuning in https://github.com/kubernetes/kubernetes/pull/102791 fixed it. Or maybe not, the PR was merged before last failure (June 11th), and the job was later failing with other errors, so they may have concealed the konnectivity restarts problem.

/sig scalability
/sig cloud-provider
/cc @kubernetes/ci-signal

**Comment by dims** [comment]
@cheftako can you please poke someone working on konnectivity? https://github.com/kubernetes/kubernetes/issues/103742

**Comment by cheftako** [comment]
Investigating. Sadly we do not seem to be capturing the either konnectivity-server or konnectivity-agent logs. containerd/kubelet logs show that we are seeing the konnectivity-agent failing a health check at about the time of some of the failures. Right now trying to get the logs captured so we are better set up to investigate.

**Comment by Tamas-Biro1** [comment]
/remove-lifecycle rotten

Checking the latest failure run today (at 2022-01-07 12:51:53 +0000 UTC, see:
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability-node-killer/1479435132900216832)

**The failure was:**
`W0107 13:29:56.507588 15192 simple_test_executor.go:175] Got errors during step execution: [measurement call TestMetrics - TestMetrics error: [action gather failed for SystemPodMetrics measurement: restart counts violation: RestartCount(konnectivity-agent-whjzn, konnectivity-agent)=1, want <= 0]]`

 Examining the logs for minion-group-0ft2 (see: https://storage.googleapis.com/sig-scalability-logs/ci-kubernetes-e2e-gci-gce-scalability-node-killer/1479435132900216832/e2e-big-minion-group-0ft2/)

`systemd.log` shows that there was a reboot at Jan 07 13:26:18:
```
Jan 07 13:26:18.119517 e2e-big-minion-group-0ft2 systemd-shutdown[1]: Sending SIGTERM to remaining processes...
Jan 07 13:26:18.119691 e2e-big-minion-group-0ft2 systemd-journald[118]: Journal stopped
-- Reboot --
Jan 07 13:27:57.430716 localhost kernel: Linux version 5.4.129+ (builder@5f2038e37965) (Chromium OS 11.0_pre391452_p20200527-r7 clang version 11.0.0 (/var/cache/chromeos-cache/distfiles/host/egit-src/llvm-project a8e5dcb072b1f794883ae8125fb08c06db678d56)) #1 SMP Thu Jul 8 19:57:33 PDT 2021
```

and the reason of reboot might be
```
Jan 07 13:16:07.714641 e2e-big-minion-group-0ft2 sshd[346]: Accepted publickey for prow from 35.235.240.80 port 38801 ssh2: RSA SHA256:7zn4DeeVmPP7aWkepXe2aiofjiUFdpJYQianL6yGHVI
Jan 07 13:26:09.696957 e2e-big-minion-group-0ft2 health-monitor.sh[1808]: curl: (7) Failed to connect to 127.0.0.1 port 10248: Connection refused
Jan 07 13:26:09.697337 e2e-big-minion-group-0ft2 health-monitor.sh[1808]: Kubelet is unhealthy!
Jan 07 13:26:09.701257 e2e-big-minion-group-0ft2 health-monitor.sh[1808]: Failed to kill unit kubelet.service: Unit kubelet.service not loaded.
```
since after the prow login, the shutdown process has been started (maybe who knows the test code better than me can confirm why, details: https://storage.googleapis.com/sig-scalability-logs/ci-kubernetes-e2e-gci-gce-scalability-node-killer/1479435132900216832/e2e-big-minion-group-0ft2/systemd.log)

and in `containerd.log` it can be seen that konnectivity-agent could successfully start at 2022-01-07T12:58 and could run until the restart
```
time="2022-01-07T12:58:11.858141960Z" level=info msg="CreateContainer within sandbox \"9745e7de755486f941c241086d063df881e714147a7b4fd0be80a3795bfedc75\" for &ContainerMetadata{Name:konnectivity-agent,Attempt:0,} returns container id \"0d486d48f1e355215ce3620f314a7eb9e849b86511556e9a5068841c512e64a8\""
```

and after the restart it could start again without error, at 2022-01-07T13:29:05 - with attempt number 1:
```
time="2022-01-07T13:29:05.850877923Z" level=info msg="CreateContainer within sandbox \"0e5d73799f0f4adf513aa928fbc4aca8164176d28427d384f250fe6a9a9160ea\" for &ContainerMetadata{Name:konnectivity-agent,Attempt:1,} returns container id \"af796797b1b83c17d2b3c4a57c753a8be2e12cce4a8ea217f68d75f4c1c9dda3\""
 (see: https://storage.googleapis.com/sig-scalability-logs/ci-kubernetes-e2e-gci-gce-scalability-node-killer/1479435132900216832/e2e-big-minion-group-0ft2/containerd.log)
```

I think Konnectivity does not have any effect on this flaking test failure, however - due to my limited knowledge of how the actual tests are working - do not know the real cause of this flapping. Maybe Konnectivity should be added to the restart count threshold overrides similar to the other ones: `map[coredns:1 fluentd-gcp:1 kube-proxy:1 metadata-proxy:1 prometheus-to-sd-exporter:1 volume-snapshot-controller:1]`
