### ISSUE TITLE
[Failing test] [sig-node]  Summary API and ResourceMetricsAPI tests are failing on cgroupv2 containerd job

### ISSUE THREAD

**Issue by adisky** [kubernetes/kubernetes#103759]
#### Which jobs are failing:
ci-cos-cgroupv2-containerd-node-e2e

#### Which test(s) are failing:
Summary API [NodeConformance]
ResourceMetricsAPI [NodeFeature:ResourceMetrics]

#### Since when has it been failing:
Failing since the job was created 
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-cos-cgroupv2-containerd-node-e2e/1406872829823029248

#### Testgrid link:
https://testgrid.k8s.io/sig-node-containerd#cos-cgroupv2-containerd-node-e2e

**Comment by bobbypage** [comment]
/assign @dragoncell

To take initial look into the failure on cgroupv2 containerd metric test.

**Comment by bobbypage** [comment]
Spent some time to investigate this. The problem here is related to https://github.com/google/cadvisor/pull/2801

The test was failing to obtain NodeStats. NodeStats are obtained from `rootStats` which obtains stats for root cgroup from cAdvisor.

https://github.com/kubernetes/kubernetes/blob/e5c4defa8e2ed6b1c5da26f68d586b9712e92df1/pkg/kubelet/server/stats/summary.go#L75

This ends up calling cAdvisor get container info with root container `/`
https://github.com/kubernetes/kubernetes/blob/e5c4def/pkg/kubelet/stats/provider.go#L112
https://github.com/kubernetes/kubernetes/blob/e5c4def/pkg/kubelet/stats/helper.go#L306-L311

The main stats collected by cAdvisor is done via calling into raw handler for libcontainer here
https://github.com/kubernetes/kubernetes/blob/e5c4def/vendor/github.com/google/cadvisor/container/libcontainer/handler.go#L83-L92

For CPU stats, libcontainer relies on reading  `cpu.stat` file. 

https://github.com/kubernetes/kubernetes/blob/e5c4defa8e2ed6b1c5da26f68d586b9712e92df1/vendor/github.com/opencontainers/runc/libcontainer/cgroups/fs2/cpu.go#L52

`cpu.stat` file did not previously exist on root cgroup for cgroupv2, it was not implemented in the kernel. As a result, no metrics were able to be obtained for `/` root by libcontainer, thus failing the test. 

Adding root `cpu.stat` file on cgroupv2 was only added on kernel 5.8.
https://kernelnewbies.org/Linux_5.8
`cgroup: add cpu.stat file to root cgroup commit`
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=936f2a70f2077f64fab1dcb3eca71879e82ecd3f

The test is currently running under `cos-89-lts` which has 5.4 kernel without this change. I tested with newer COS image under 5.10 kernel and the test passed successfully since the `cpu.stat` exists for root cgroup.

**Comment by adisky** [comment]
Thanks @bobbypage for fixing this and the detailed explanation
