### ISSUE TITLE
[sig-cli] Find out more global flags be shadowed in kubectl

### ISSUE THREAD

**Issue by jyz0309** [kubernetes/kubernetes#103835]
#### What would you like to be added:
As the #103769 comment said, `--user` flag has been shadowed by the root command flag and not show in the `kubectl create clusterrolebinding --help` command. We want to find out more flag which be shadowed and rename it. 
Just like: #103809 
#### Why is this needed:
For example, `kubectl create rolebinding --help` now not show the `--user` flag. But it's an optional flag for command. I think we need to show all flags that use in this command.

**Comment by mccricardo** [comment]
@kerthcet I was messing around the codebase and found an instance in **kubectl set subject** and submitted a PR.

**Comment by kerthcet** [comment]
> @kerthcet I was messing around the codebase and found an instance in **kubectl set subject** and submitted a PR.

sounds good. Or maybe you can help to find out more shadowed ones. it depends whatever.

**Comment by mccricardo** [comment]
@kerthcet I took a look and didn't find other instances. Assigning it to me then.

**Comment by karuppiah7890** [comment]
Can we use some sort of tasks in this issue's first comment to track the different commands / subcommands and their flags that get shadowed by the global flags? This way it's easier to track it, also, we could create sub issues in GitHub. Or else PRs will refer to this issue which seems to be an umbrella issue and this issue would get closed once PRs are merged. For example this issue will get closed if PR #103891 gets merged. What do you all think about tasks and separate sub issues for each of such instances?

**Comment by karuppiah7890** [comment]
cc @jyz0309 @mccricardo @GauravKakoti @kerthcet

**Comment by karuppiah7890** [comment]
Sub issues will also help us to assign contributors separately to each of those issues and it will be easy to track who is working on fixing which issue. Or else we would have to maintain that list too in this issue in the first comment or in the contributor's comments to mention - which issue they are working on and also assign themselves to this issue, and others who are trying to contribute will then have to search which issue is pending or left out so that they can pick it up. In the worst case scenario, it could also lead to duplication of effort in case people work on the same issue because they missed to see someone else is working on it. Sometimes we can't eliminate that, but I think we can lower the probability of that by tracking -
- The issues clearly - commands / subcommands and their respective flags that need fixing, all clearly
- Separate GitHub issue for each of the issues
- Who is working on which issue by assigning them to the separate GitHub issues

If necessary we can track the overall effort in this umbrella issue or else we can close this and just use separate standalone issues for each of these instances when we find this problem

**Comment by lauchokyip** [comment]
@karuppiah7890 , from what I have seen, we have not yet decided what solutions are acceptable yet. Until then, I think would remove the good-first-issues's tags first

**Comment by karuppiah7890** [comment]
Ah. Okay. Makes sense. I did notice two kinds of PRs - one breaking backwards compatibility of the CLI API, another not breaking backwards compatibility of the CLI API but planning to break it in a future release by having both shadowed and non-shadowed flag

But I'm wondering how it's a breaking change if it's shadowed - because if someone uses the flag, it would still be passing the value to the global flag regardless of sub command having the shadow flag. Anyways, something to discuss. I guess we can remove the good first issue tag if there's no clearly defined easy way to fix the issue yet. Once we have that, we can pen down the fix and then tag it with good first issue for folks to pick it up
