### ISSUE TITLE
Fix namespace deletion in e2e tests - it seems very broken

### ISSUE THREAD

**Issue by quinton-hoole** [kubernetes/kubernetes#10380]
#10225 refers

Copy of my notes from there:

This just all looks terribly wrong (not this particular PR, but the code around it).  Note to myself to understand it properly and fix it up soon.  Specifically:

1. The function deleteTestingNS() does nothing of the sort.  It just polls until all namespaces with some magic prefix are not in deleting state.  It would seem that that simply doesn't work if there are parallel test runs in flight.
2. If the comments in this PR are true, then we're deleting the contents of namespaces in a rather bizirre way.  I'd like to understand that.
3. Having namespace deletion take up to 60 minutes to complete is simply untenable in automated tests. Isn't this called for every test invocation?  Or perhaps it's once per test run.  Either way, it's way too long.

Q

**Comment by wojtek-t** [comment]
I'm copying my notes from #10225 (sorry I didn't see this issue before writing it there)

@quinton-hoole -  the rationale behind deleteTestingNS is as following:
- deleting namespace happens in the background
- deleting namespace after scalability tests can take more than half an hour
- deleteTestingNS is used only in scalability tests (and shouldn't be used anywhere else)
- thus we don't want to do it for both tests, because after running the second test we are shutting down the cluster anyway
- the reason why we are using it, because deleting namespace in the background is affecting metrics of the currently running test

 How this should be done in the future:
- once we the namespace can be deleted fast (within seconds) - #7372 should solve that problem, at the end of scalability tests we should just wait until that particular namespace is fully deleted

I agree the current approach is hacky - but we need to be able to delete the namespace fast to solve this problem properly.

**Comment by wojtek-t** [comment]
BTW - I'm happy to fix it (do it properly) once #7372 is merged.

**Comment by wojtek-t** [comment]
Also - I don't think it's necessary for 1.0

**Comment by wojtek-t** [comment]
Also:

>
The function deleteTestingNS() does nothing of the sort. It just polls until all namespaces with some magic prefix are not in deleting state. It would seem that that simply doesn't work if there are parallel test runs in flight.

Correct - but as I wrote before - deleteTestingNS is supposed to be used only for scalability tests and those tests also doesn't make sense if they are run in parallel.

>
Having namespace deletion take up to 60 minutes to complete is simply untenable in automated tests. Isn't this called for every test invocation? Or perhaps it's once per test run. Either way, it's way too long.

This depends on how many objects we have in the namespace  - for typical e2e tests there are just few of them.
In scalability tests we have tens of thousands of events. Thus having throttling at the level of controller-manager which is affecting ability of namespace-controller to remove them, means it needs to take half an hour.

Anyway - I still think it's not something we should do for 1.0.

**Comment by wojtek-t** [comment]
@quinton-hoole - are you fine with moving it to post 1.0?
If so then you can assign it to me - I will fix it as soon as #7372 is merged.

**Comment by quinton-hoole** [comment]
I'l like to review and comment further, but haven't had the time yet.  I don't fully agree with the logic of your notes above (Jun 26, 12:06 AM).  More later.

**Comment by wojtek-t** [comment]
I think this is already fixed.
