### ISSUE TITLE
Pod stuck on Running after node lost

### ISSUE THREAD

**Issue by Lanyujiex** [kubernetes/kubernetes#103929]
#### What happened:
I found that the Pod created by DaemonSet will not become Terminating or drift after the node NotReady. I describe that the status seen by these pods is Running, but the status.Conditions of the pod are not all true.

#### What you expected to happen:
After the node NotReady, the state of the Pod can become Terminating or error or drift.

#### Anything else we need to know?:
I realized the disconnection by closing the node
#### Environment:
- Kubernetes version (use `kubectl version`):1.20.1
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):CentOS 8
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by ehashman** [comment]
This is expected; DaemonSets explicitly tolerate nodes being NotReady by default: https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/#taints-and-tolerations

All pods proceed through a lifecycle of Pending -> Running -> Terminated. Even if a pod is crashing or unhealthy, if it is neither pending nor terminated, it is considered Running even if the containers are unhealthy.

Kubernetes does not use issues on this repo for support requests. If you have more questions on how to use Kubernetes or to debug a specific issue, please visit our [forums](https://discuss.kubernetes.io/).

/kind support
/close

**Comment by Lanyujiex** [comment]
I  got it

**Comment by amitkatyal** [comment]
I am also facing the same issue. I understand the daemonset pod to remain in the running state is expected but since we are exposing these daemonsets pods via a headless service, DNS resolution to the headless service is returning an IP address of the pod which is running on the unreachable node. Is there any workaround to address this behavior?

**Comment by kerthcet** [comment]
hi @amitkatyal , I was quite curious about the scenario why you want to access these daemonsets. In our practices, daemonsets works indepnedent around the node. And your advice is discussible I agreed.

**Comment by amitkatyal** [comment]
hi @kerthcet, We are running one of our data plane component as a daemonset as we are facing some issues with the HPA.
This daemonSet is exposed behind the headless service so that another data plane component can load balance the traffic across all the instances of the daemonSet. The problem we are facing is in the node down scenario. If one of the nodes is down, then daemonSet is not evicted and remains in the running state. And the DNS resolution to the headless service also returns the IP address of the POD which is not reachable. Since unreachable POD IP is returned to the client, 1/3 of the traffic is getting dropped in a 3 node cluster.
