### ISSUE TITLE
The CPU manager does not work correctly for the guaranteed pod with multiple containers

### ISSUE THREAD

**Issue by cynepco3hahue** [kubernetes/kubernetes#103952]
#### What happened:

The CPU manager removes the allocation for previous containers under the guaranteed pod once the next container allocation started.

The CPU manager test fails because of it
```
E2eNode Suite: [sig-node] CPU Manager [Serial] [Feature:CPUManager] With kubeconfig updated with static CPU Manager policy run the CPU Manager tests should assign CPUs as expected based on the Pod spec
```
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-serial-cpu-manager/1420014879246389248

#### What you expected to happen:

The CPU manager should keep previous containers allocations.

#### How to reproduce it (as minimally and precisely as possible):

- Start the guaranteed pod with two containers
- Verify the CPU pining for the first container

#### Anything else we need to know?:

I think the problem introduced by recent refactor under https://github.com/kubernetes/kubernetes/commit/3eadd1a9ead7a009a9abfbd603a5efd0560473cc

So what happens:
```
27 13:11:05.510153    4328 kubelet.go:2053] "SyncLoop ADD" source="api" pods=[cpu-manager-test-660/gu-pod]
27 13:11:05.510196    4328 topology_manager.go:200] "Topology Admit Handler"
27 13:11:05.510220    4328 manager.go:872] "Looking for needed resources" needed=1 resourceName="cpu"
27 13:11:05.510234    4328 manager.go:872] "Looking for needed resources" needed=104857600 resourceName="memory"
27 13:11:05.510274    4328 policy_static.go:251] "Static policy: Allocate" pod="cpu-manager-test-660/gu-pod" containerName="gu-test-container1"
27 13:11:05.510298    4328 policy_static.go:277] "Topology Affinity" pod="cpu-manager-test-660/gu-pod" containerName="gu-test-container1" affinity={NUMANodeA
27 13:11:05.510309    4328 policy_static.go:304] "AllocateCPUs" numCPUs=1 socket=<nil>
27 13:11:05.510368    4328 cpu_assignment.go:166] "takeRemainingCPUs: claiming CPU" cpu=2
27 13:11:05.510391    4328 state_mem.go:88] "Updated default CPUSet" cpuSet="0-1,3"
27 13:11:05.513807    4328 policy_static.go:339] "AllocateCPUs" result="2"
27 13:11:05.513844    4328 state_mem.go:80] "Updated desired CPUSet" podUID="0ea44149-552f-42ed-9d38-60e374249dca" containerName="gu-test-container1" cpuSet=
27 13:11:05.516331    4328 manager.go:872] "Looking for needed resources" needed=1 resourceName="cpu"
27 13:11:05.516373    4328 manager.go:872] "Looking for needed resources" needed=104857600 resourceName="memory"
27 13:11:05.516394    4328 cpu_manager.go:363] "RemoveStaleState: removing container" podUID="0ea44149-552f-42ed-9d38-60e374249dca" containerName="gu-test-co
27 13:11:05.516404    4328 policy_static.go:294] "Static policy: RemoveContainer" podUID="0ea44149-552f-42ed-9d38-60e374249dca" containerName="gu-test-contai
27 13:11:05.516416    4328 state_mem.go:107] "Deleted CPUSet assignment" podUID="0ea44149-552f-42ed-9d38-60e374249dca" containerName="gu-test-container1"
27 13:11:05.518811    4328 state_mem.go:88] "Updated default CPUSet" cpuSet="0-3"
27 13:11:05.521226    4328 state_mem.go:107] "Deleted CPUSet assignment" podUID="0ea44149-552f-42ed-9d38-60e374249dca" containerName="gu-test-container1"
27 13:11:05.521268    4328 policy_static.go:251] "Static policy: Allocate" pod="cpu-manager-test-660/gu-pod" containerName="gu-test-container2"
```
- the CPU manager allocates the CPU for the first container
- Part of the second container allocation the CPU manager calls to [removeStaleState](https://github.com/kubernetes/kubernetes/blob/d92b788faa2521a937acc5fdcb66bfdb960dbd48/pkg/kubelet/cm/cpumanager/cpu_manager.go#L240)
- The kubelet does not recognize our new pod as running one and as a result, `removeStaleState` removes the first container from the state file

The issues affect the memory manager as well.

#### Environment:
- Kubernetes version (use `kubectl version`): master
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): 
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by ehashman** [comment]
Issue is urgent but **not** release blocking this late: https://kubernetes.slack.com/archives/C0BP8PW9G/p1627409859207800?thread_ts=1627408015.203100&cid=C0BP8PW9G

Confirmed CPU manager e2e has been failing since 07/08 which is when Clayton's refactor initially landed: https://prow.k8s.io/job-history/gs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-serial-cpu-manager?buildId=1413362483304861696

**Comment by smarterclayton** [comment]
I commented on https://github.com/kubernetes/kubernetes/pull/103953#issuecomment-887856835 but I'm pretty sure the code here was wrong before my change - a pod in admission cannot be in `GetActivePods()` until it's actually delivered to the pod worker, so any background process you run that refreshes the pod worker has to track that.

I noticed that the cpu manager periodically reconciles - this is not synchronized with pod configuration management, so this call can race with the pod config loop (the pod shows up, is checked for admission, and then reconcileState() runs before the pod is added to the pod worker).

```
	// Periodically call m.reconcileState() to continue to keep the CPU sets of
	// all pods in sync with and guaranteed CPUs handed out among them.
	go wait.Until(func() { m.reconcileState() }, m.reconcilePeriod, wait.NeverStop)
```

A pod is not an active pod until it is passed to a pod worker.  Anyone relying on the behavior before (prior to my change) was accidentally including pods that are not active (because the bug #102344 fixed was that pods were incorrectly listed as active).

You either need to ensure reconcile is only called during pod housekeeping (which is synchronized with the config loop) or your cpu manager needs to track pods that are "in flight for admission but not yet active" (kube apiserver admission quota does this).

**Comment by cynepco3hahue** [comment]
Thanks for the info. Probably the second is the best option for us.

**Comment by fromanirh** [comment]
it seems the device manager (as well as the memory manager) can hit the same issue: https://github.com/kubernetes/kubernetes/blob/release-1.21/pkg/kubelet/cm/devicemanager/manager.go#L621

**Comment by fromanirh** [comment]
> Issue is urgent but **not** release blocking this late: https://kubernetes.slack.com/archives/C0BP8PW9G/p1627409859207800?thread_ts=1627408015.203100&cid=C0BP8PW9G
> 
> Confirmed CPU manager e2e has been failing since 07/08 which is when Clayton's refactor initially landed: https://prow.k8s.io/job-history/gs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-serial-cpu-manager?buildId=1413362483304861696

A bit more context: turns out all the resource managers (cpu, memory, device) use the same core logic, so in addition to the cpu manager we are tracking here, the memory manager is surely broken as well, and [the device manager](https://github.com/kubernetes/kubernetes/blob/release-1.21/pkg/kubelet/cm/devicemanager/manager.go#L621) is almost certainly (= same logic but no test to prove the breakage atm) broken as well

**Comment by smarterclayton** [comment]
Digging into this more, I see the problem and why it started breaking.  

> Admission plugins should not be using GetActivePods() to check the state of "all known pods" if they are tracking admitted requests, because GetActivePods() is post admission

To be broken, an admission handler must store data in internal maps AND have a background loop that checks GetActivePods (please verify who is impacted)

## Problem

There are two sets of pods in the Kubelet:

1. Those that are in config (in one or more of the config sources at the current time)
2. Those that are recognized by the Kubelet to do work (owned by the pod worker)

These are mostly overlapping groups:

```
|----------------------------------|            (config)      <- in the podManager.GetPods()
         |------------------------------------| (pod worker)  <- passed admission AND in the podWorker
         |------------------------------|       (active)      <- kubelet.GetActivePods() after my change
|--------|                                             (pod not yet admitted)
```

The bug that my change fixed was that some components were assuming that the first set and the second set are the same, especially cleanup loops.  My change however impacted GetActivePods to the majority definition, which is correct for admission (kubelet) but not for the cleanup loops inside admission handler components (which are assuming that admission cannot fail).

Any admission plugin that "allocates" internal resources needs to track the difference between a resource request (created in admission) and an actual reserved resource (for a pod that has passed admission and is known to the pod worker).  It appears if most of our admission plugins are assuming that all admission succeeds by simply allocating and then cleaning up later, which is incorrect if admission fails.  Admission that resyncs the state of the internal manager from a list of valid pods before it performs an Admit check can work around part of this (like cpu manager) by changing the list of pods it acts on.

## Other possible fixes

At least for the cpu manager, it needs to get the list of active pods AND then conditionally include the current pod.  The list of GetActivePods is already passed to the admission handler, and the admission hook can use that to check whether the pod is "already admitted" or not.  We should never invoke the admission handler twice (for each container), so that sounds like an admission handler bug if you are cleaning up your internal state in the middle of a single `Admit` call.

**Comment by klueska** [comment]
@smarterclayton thanks for the clear description of the issue. I believe that the proposal you have in "Other possible fixes" is the one that we should take for these components.

@fromanirh @cynepco3hahue please assign me to the PR you put together to fix this.

**Comment by hj-johannes-lee** [comment]
Hello, while trying to solve the issue #107074, I still see the similar problem like this.

> $ kubelet --version
Kubernetes v1.23.2-rc.0.56+3426f6ceaf92ad-dirty
#I compiled from release-1.23 branch (last commit 15 Jan 2022 06:32)

> $ sudo cat /etc/systemd/system/kubelet.service.d/10-kubeadm.conf 
# Note: This dropin only works with kubeadm and kubelet v1.11+
[Service]
Environment="KUBELET_KUBECONFIG_ARGS=--bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf"
Environment="KUBELET_CONFIG_ARGS=--config=/var/lib/kubelet/config.yaml --cpu-manager-policy=static --kube-reserved=cpu=1,memory=2Gi,ephemeral-storage=1Gi --system-reserved=cpu=1,memory=2Gi,ephemeral-storage=1Gi"
...

> $ cat testpod.yaml 
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
  - name: container1
    image: ubuntu:20.04
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 1
        memory: 200Mi
      requests:
        cpu: 1
        memory: 200Mi
  - name: container2
    image: ubuntu:20.04
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 1
        memory: 200Mi
      requests:
        cpu: 1
        memory: 200Mi
        
> $ tail -n 300 /var/log/syslog
...
Jan 20 10:36:22 hj-johannes-vm kubelet[1502979]: I0120 10:36:22.237283 1502979 topology_manager.go:200] "Topology Admit Handler"
Jan 20 10:36:22 hj-johannes-vm kubelet[1502979]: E0120 10:36:22.237355 1502979 cpu_manager.go:383] "RemoveStaleState: removing container" podUID="8c412f94-76e0-469a-b76b-6e53d77f2e29" containerName="container1"
Jan 20 10:36:22 hj-johannes-vm kubelet[1502979]: I0120 10:36:22.237367 1502979 policy_static.go:296] "Static policy: RemoveContainer" podUID="8c412f94-76e0-469a-b76b-6e53d77f2e29" containerName="container1"
Jan 20 10:36:22 hj-johannes-vm kubelet[1502979]: I0120 10:36:22.252081 1502979 state_mem.go:88] "Updated default CPUSet" cpuSet="0-2,4-7"
Jan 20 10:36:22 hj-johannes-vm kubelet[1502979]: E0120 10:36:22.255256 1502979 cpu_manager.go:383] "RemoveStaleState: removing container" podUID="8c412f94-76e0-469a-b76b-6e53d77f2e29" containerName="container2"
Jan 20 10:36:22 hj-johannes-vm kubelet[1502979]: I0120 10:36:22.255275 1502979 policy_static.go:296] "Static policy: RemoveContainer" podUID="8c412f94-76e0-469a-b76b-6e53d77f2e29" containerName="container2"
Jan 20 10:36:22 hj-johannes-vm kubelet[1502979]: I0120 10:36:22.260430 1502979 state_mem.go:88] "Updated default CPUSet" cpuSet="0-7"
Jan 20 10:36:22 hj-johannes-vm kubelet[1502979]: I0120 10:36:22.263840 1502979 policy_static.go:253] "Static policy: Allocate" pod="default/test-pod" containerName="container1"
Jan 20 10:36:22 hj-johannes-vm kubelet[1502979]: I0120 10:36:22.263864 1502979 policy_static.go:279] "Topology Affinity" pod="default/test-pod" containerName="container1" affinity={NUMANodeAffinity:<nil> Preferred:false}
Jan 20 10:36:22 hj-johannes-vm kubelet[1502979]: I0120 10:36:22.263870 1502979 policy_static.go:306] "AllocateCPUs" numCPUs=1 socket=<nil>
Jan 20 10:36:22 hj-johannes-vm kubelet[1502979]: I0120 10:36:22.263913 1502979 state_mem.go:88] "Updated default CPUSet" cpuSet="0-1,3-7"
Jan 20 10:36:22 hj-johannes-vm kubelet[1502979]: I0120 10:36:22.270563 1502979 policy_static.go:341] "AllocateCPUs" result="2"
Jan 20 10:36:22 hj-johannes-vm kubelet[1502979]: I0120 10:36:22.270580 1502979 state_mem.go:80] "Updated desired CPUSet" podUID="4ce49761-b22b-438d-ba7d-194949172184" containerName="container1" cpuSet="2"
Jan 20 10:36:22 hj-johannes-vm kubelet[1502979]: I0120 10:36:22.273735 1502979 policy_static.go:253] "Static policy: Allocate" pod="default/test-pod" containerName="container2"
Jan 20 10:36:22 hj-johannes-vm kubelet[1502979]: I0120 10:36:22.273753 1502979 policy_static.go:279] "Topology Affinity" pod="default/test-pod" containerName="container2" affinity={NUMANodeAffinity:<nil> Preferred:false}
Jan 20 10:36:22 hj-johannes-vm kubelet[1502979]: I0120 10:36:22.273758 1502979 policy_static.go:306] "AllocateCPUs" numCPUs=1 socket=<nil>
Jan 20 10:36:22 hj-johannes-vm kubelet[1502979]: I0120 10:36:22.273815 1502979 state_mem.go:88] "Updated default CPUSet" cpuSet="0-1,4-7"
Jan 20 10:36:22 hj-johannes-vm kubelet[1502979]: I0120 10:36:22.275291 1502979 policy_static.go:341] "AllocateCPUs" result="3"
Jan 20 10:36:22 hj-johannes-vm kubelet[1502979]: I0120 10:36:22.275305 1502979 state_mem.go:80] "Updated desired CPUSet" podUID="4ce49761-b22b-438d-ba7d-194949172184" containerName="container2" cpuSet="3"
Jan 20 10:36:22 hj-johannes-vm systemd[1]: Created slice libcontainer container kubepods-pod4ce49761_b22b_438d_ba7d_194949172184.slice.


What did I set wrong if this problem was already solved..?
