### ISSUE TITLE
Scheduling framework plugins missing Lock()

### ISSUE THREAD

**Issue by CermakM** [kubernetes/kubernetes#103975]
#### What happened:

Function `getPreFilterState(cycleState *framework.CycleState) (*preFilterState, error)` causes race condition with a custom `Filter` plugin if the plugin writes to the cycle state.

The function in the custom plugin is as simple as
```go
func WriteState(state *framework.CycleState, pod *v1.Pod, data model.StateData) error {
	state.Lock()
	defer state.Unlock()

	state.Write(podToStateKey(pod), data)
	return nil
}
```

and is called during the call to

```go
func (p *Plugin) Filter(ctx context.Context,
	state *framework.CycleState,
	pod *v1.Pod,
	nodeInfo *framework.NodeInfo,
) *framework.Status {
```

#### What you expected to happen:

No race condition is present.

#### How to reproduce it (as minimally and precisely as possible):

Have a filtering plugin which calls `state.Lock()` and writes into the cycle state, set `parallelism` to 16, and schedule a `Deployment` with a sufficient amount of replicas to cause this race condition.

#### Anything else we need to know?:

The function is copy-pasted into multiple existing plugins. The function `getPreFilterState` in those plugins should probably obtain a lock before reading the cycle state.

#### Environment:
- Kubernetes version (use `kubectl version`): 1.20.9

**Comment by Huang-Wei** [comment]
@CermakM the issue was also reported in #95887. And we did an enhancement in 1.22 (#101542).

The possible root cause is that you might be manipulating the top-level `CycleState` in your custom Filter plugin, which is not a good practice - even with #101542 in. A good pattern is to restrict the scope of your locking, i.e., you can place a custom `state` and inject into the top-level `CycleState` in PreFilter(), and then manipulate the custom `state` with your own locking in the filtering logic; rather than mutating the `CycleState` directly in Filter(). An example is how the volumebinding plugin manages its own state:

https://github.com/kubernetes/kubernetes/blob/dadecb2c8932fd28de9dfb94edbc7bdac7d0d28f/pkg/scheduler/framework/plugins/volumebinding/volume_binding.go#L247-L250

(Note that #101542 is a PR to avoid racing no matter how users manipulate `CycleState`. However, if performance is concerned, I do highly recommend plumbing your custom state and locking in your plugin, as mentioned above)

**Comment by CermakM** [comment]
@Huang-Wei that's an interesting point, thanks for the advice, I'll take a closer look at my code and see what can be fixed on my side. Also, thanks for the fix in the new release!

That being the case, I think we can close this issue. Cheers!
