### ISSUE TITLE
Should we remove go-spew from the dependency as it seems be abandoned

### ISSUE THREAD

**Issue by RainbowMango** [kubernetes/kubernetes#103942]
#### What would you like to be added:
Replace [github.com/davecgh/go-spew][1] with its alternatives, like:
- https://github.com/kr/pretty

#### Why is this needed:
Seems the `github.com/davecgh/go-spew` [has been abandoned][3], the last commit happened in the year 2018.
The effect, such as:
- The library still does not support `Go Module`
- Some [panic(issues)][2] not be handled for a long time.

[1]:https://github.com/davecgh/go-spew
[2]:https://github.com/davecgh/go-spew/issues
[3]:https://github.com/davecgh/go-spew/issues/128

**Comment by dims** [comment]
/area code-organization

sounds good @RainbowMango

**Comment by RainbowMango** [comment]
Thanks @dims.
I was wondering if I should ask you for help because I don't know which sig/wg this kind of issue belongs to. :) :):)

**Comment by neolit123** [comment]
go-spew is mostly used for debug printing in error messages and unit tests...but in a lot of places.
i can also see it in e2e tests.

i found at least one place where it's part of "main" code paths:
https://github.com/kubernetes/kubernetes/blob/ea0764452222146c47ec826977f49d7001b0ea8c/pkg/kubelet/cm/cpumanager/state/checkpoint.go#L114

i think the PRs should be broken in packages, but not too granularity:
/test/e2e
/test/e2e_node
/pkg/kubelet
/staging/src/k8s.io/client-go
/staging/src/k8s.io/apimachinery
...

**Comment by mcbenjemaa** [comment]
I take this Issue

/assign

**Comment by RainbowMango** [comment]
@mcbenjemaa are you still working on this? How is it going and do you need help?

**Comment by mcbenjemaa** [comment]
```
find . -name "*.go" |  grep -v vendor/ | { xargs grep 'github.com/davecgh/go-spew' -sl || true; } 

./staging/src/k8s.io/client-go/tools/watch/retrywatcher_test.go
./staging/src/k8s.io/client-go/tools/watch/informerwatcher_test.go
./staging/src/k8s.io/client-go/tools/watch/retrywatcher.go
./staging/src/k8s.io/client-go/restmapper/discovery_test.go
./staging/src/k8s.io/client-go/plugin/pkg/client/auth/exec/exec.go
./staging/src/k8s.io/client-go/kubernetes_test/timeout_test.go
./staging/src/k8s.io/kube-aggregator/pkg/controllers/status/available_controller_test.go
./staging/src/k8s.io/cli-runtime/pkg/resource/visitor_test.go
./staging/src/k8s.io/cli-runtime/pkg/resource/kustomizevisitor_test.go
./staging/src/k8s.io/cli-runtime/pkg/resource/builder_test.go
./staging/src/k8s.io/apiserver/pkg/server/dynamiccertificates/tlsconfig_test.go
./staging/src/k8s.io/apiserver/pkg/server/deleted_kinds_test.go
./staging/src/k8s.io/kubectl/pkg/cmd/wait/wait_test.go
./staging/src/k8s.io/apimachinery/pkg/util/jsonmergepatch/patch_test.go
./staging/src/k8s.io/apimachinery/pkg/util/diff/diff.go
./staging/src/k8s.io/apimachinery/pkg/util/mergepatch/util.go
./staging/src/k8s.io/apimachinery/pkg/util/strategicpatch/patch_test.go
./staging/src/k8s.io/apimachinery/pkg/api/apitesting/roundtrip/roundtrip.go
./test/e2e_node/image_id_test.go
./test/e2e_node/dynamic_kubelet_config_test.go
./test/e2e_node/apparmor_test.go
./test/integration/namespace/ns_conditions_test.go
./test/integration/client/exec_test.go
./test/utils/deployment.go
./test/e2e/storage/testsuites/volumeperf.go
./test/e2e/apps/deployment.go
./plugin/pkg/admission/storage/storageobjectinuseprotection/admission_test.go
./pkg/apis/apps/validation/validation_test.go
./pkg/proxy/service_test.go
./pkg/proxy/healthcheck/healthcheck_test.go
./pkg/proxy/endpoints_test.go
./pkg/proxy/winkernel/proxier.go
./pkg/util/hash/hash_test.go
./pkg/util/hash/hash.go
./pkg/security/podsecuritypolicy/apparmor/strategy_test.go
./pkg/controller/bootstrap/common_test.go
./pkg/controller/bootstrap/bootstrapsigner_test.go
./pkg/controller/bootstrap/tokencleaner_test.go
./pkg/controller/garbagecollector/dump_test.go
./pkg/controller/serviceaccount/tokens_controller_test.go
./pkg/controller/volume/pvcprotection/pvc_protection_controller_test.go
./pkg/controller/volume/pvprotection/pv_protection_controller_test.go
./pkg/controlplane/controller/clusterauthenticationtrust/cluster_authentication_trust_controller_test.go
./pkg/kubelet/kubeletconfig/checkpoint/download_test.go
./pkg/kubelet/kubeletconfig/checkpoint/configmap_test.go
./pkg/kubelet/kubeletconfig/checkpoint/store/store_test.go
./pkg/kubelet/kubeletconfig/checkpoint/store/fsstore_test.go
./pkg/kubelet/cm/cpumanager/state/checkpoint.go
./pkg/api/v1/endpoints/util_test.go
```

**Comment by RainbowMango** [comment]
/remove-lifecycle stale

kindly ping @mcbenjemaa. And just a reminder https://github.com/kubernetes-sigs/kustomize/issues/4218 has been closed due to lack of activity.

**Comment by mcbenjemaa** [comment]
I think, i can have some time for this.

**Comment by thockin** [comment]
I like spew enough that I have forked it and will spend some time hacking.  My goal is (currently) to stay api-compatible, but maybe I will minimize.

**Comment by dims** [comment]
we are way down in number of usages

```
❯ find . -name "*.go" |  grep -v vendor/ | { xargs grep 'github.com/davecgh/go-spew' -sl || true; }

./staging/src/k8s.io/code-generator/cmd/deepcopy-gen/output_tests/output_test.go
./staging/src/k8s.io/endpointslice/util/controller_utils.go
./staging/src/k8s.io/apimachinery/pkg/util/dump/dump.go
```

**Comment by thockin** [comment]
I'm disappointed it's more than just k8s.io/apimachinery/pkg/util/dump -- the goal of that was to consolidate ALL of our users into one API which we could them change the implementation of.

**Comment by RainbowMango** [comment]
@dims Thanks for the update. 

> I'm disappointed it's more than just k8s.io/apimachinery/pkg/util/dump -- the goal of that was to consolidate ALL of our users into one API which we could them change the implementation of.

Do we still have to remove the go-spew? We already have `k8s.io/apimachinery/pkg/util/dump`, which is maintained by the community and has plenty of test covers.

**Comment by dims** [comment]
@RainbowMango i think we are ok, but we do add something to limit folks from adding `"github.com/davecgh/go-spew/spew"` in any other files other than `dump.go`.

**Comment by RainbowMango** [comment]
That's great, thanks for your effort! 
How time flies, it's been 3 years since I filed this issue.

**Comment by dims** [comment]
`github.com/davecgh/go-spew` is still in `vendor/` and is load-bearing in production code — not just a test dependency. The chain is:

```
k/k (production) → k8s.io/utils/dump.ForHash() → github.com/davecgh/go-spew/spew
```

**Non-test call sites:**
- `pkg/util/hash/hash.go` — `DeepHashObject` (pod template hashes, controller revision hashes, endpoint slice hashes)
- `pkg/kubelet/cm/cpumanager/state/checkpoint.go` — `MarshalCheckpoint` / `VerifyChecksum` (checkpoint files on disk)
- `pkg/kubelet/cm/memorymanager/state/checkpoint.go` — same
- `pkg/controller/controller_utils.go`, `pkg/controller/history/controller_history.go`, `pkg/controller/job/job_scheduling_manager.go`, `pkg/kubelet/container/helpers.go`, `pkg/api/v1/endpoints/util.go`, and others

The comment in `vendor/k8s.io/utils/dump/dump.go` says it all:
> "The config MUST NOT be changed because that could change the result of a hash operation"

The concrete risk was demonstrated in #123552 — adding a field to a DRA checkpoint struct changed the spew-based hash, causing kubelet to fail to start on upgrade (`checkpoint is corrupted`).

- `stretchr/testify` `master` has removed `go-spew` as a direct dependency, but no release since v1.11.1 (August 2025).
- All other transitive upstream holders (prometheus/common, go-logr/zapr, etcd, otel packages, kustomize, cadvisor, etc.) still carry it at their latest releases with no active removal efforts.

Even if every transitive upstream dropped it, k/k would still need it through `k8s.io/utils/dump` — so this is a k/k-internal design problem, not just an upstream dependency problem.

1. Replace `k8s.io/utils/dump.ForHash` with an implementation that either (a) produces byte-for-byte identical output using a different library, or (b) deliberately breaks compatibility and ships a migration path for existing checkpoint files and labels on running nodes.
2. Coordinate with `k8s.io/utils` to remove the go-spew import there.
3. Then bump all the transitive upstream holders as they release new versions.

Option (a) is the safer path but still requires the replacement library to match spew's `%#v`-style output exactly. Option (b) requires versioned checkpoint structs and conversion code (the pattern that was needed anyway, per #123552).

Flagging here so the context isn't lost.

**Comment by pohly** [comment]
> The concrete risk was demonstrated in https://github.com/kubernetes/kubernetes/issues/123552 — adding a field to a DRA checkpoint struct changed the spew-based hash, causing kubelet to fail to start on upgrade (checkpoint is corrupted).

We stopped using this checkpointing for DRA already before graduation to beta, because of this. If you want a more recent example of the risk, look at https://github.com/kubernetes/kubernetes/pull/137751. Downgrading kubelet almost broke in 1.36.

**Comment by pohly** [comment]
Regarding kubelet checkpoint files: the only reason that I can imagine why it's done is to detect bit flips or incomplete files. Incomplete files are already covered by decoding errors in JSON when the object isn't closed. Checksums are better done as in https://github.com/kubernetes/kubernetes/blob/75d51c440770f96b9725efea4145ba50fc6aef4b/pkg/kubelet/cm/dra/state/checkpoint.go#L33-L39 with a separate checksum of the stored data, not of the in-memory representation as it's done via go-spew.

My preferred approach for them is to migrate to a checkpoint file format either without any checksum or with one that is computed for the stored data, as in DRA. The current approach causes too many problems. But that is a breaking change and I am not sure how to execute on it.

**Comment by pohly** [comment]
Here's an idea how kubelet could migrate away from go-spew based hashing:
- In 1.37, we change the content of the checkpoint file from `{<JSON dump of struct including checksum>}` to `{<JSON dump of struct including checksum>}{<JSON dump of new checksum over the preceding JSON object - format to be defined>}` (JSON stream) on writes.
- 1.36 *should* be able to read such a file without problems (to be verified!).
- When reading with 1.37, compare the new checksum if present and ignore the old checksum, otherwise do the same as before.
- In 1.38 (or later, if we want to support downgrading by more than one release), stop calculating the old go-spew based on writes. When reading, use only the new checksum and none if it's not available. This removes go-spew from kubelet.

**Comment by lukaszwojciechowski** [comment]
> * 1.36 _should_ be able to read such a file without problems (to be verified!).

That will return `json: syntax error (invalid character '{' after top-level value)` if structure is parsed by `json.Unmarshal` in 1.36
