### ISSUE TITLE
Sidecar container lifecycle feature

### ISSUE THREAD

**Issue by Lovnx** [kubernetes/kubernetes#103996]
From the post 'https://banzaicloud.com/blog/k8s-sidecars/' ,we know that k8s 1.18 supprot sidecar container for adding 'lifecycle.type=Sidecar' feature. But from previous [issue](https://github.com/kubernetes/kubernetes/issues/94453), @rata replied that It was planned to ship on 1.18, but it didn't and it didn't also on 1.19. I wanna konw, There is still no support for this feature yet?

**Comment by rata** [comment]
No there is no support for this yet. 

The KEP started a big discussion on some more fundamental issues. This email thread has a link to the KEP discussion, the use cases that were collected and the pre-proposals that were created since then (so far two, one exploring pod phases by Tim Hockin, another exploring using a DAG for dependencies by me).

@matthyx was trying to move this forward, I'm trying to join forces with him, but still no idea what will be done and when.

**Comment by Lovnx** [comment]
Hope that will be : )
