### ISSUE TITLE
Resource managers can remove allocated resources for terminating pods

### ISSUE THREAD

**Issue by cynepco3hahue** [kubernetes/kubernetes#104099]
#### What happened:
It is possible that resource managers
- CPU
- Memory
- Device
will remove the resource allocation for terminating pods. See the discussion https://github.com/kubernetes/kubernetes/pull/103979#discussion_r678587770.

#### What you expected to happen:
The resource managers should not remove pod allocated resources until it not ended the termination process.

#### Environment:
- Kubernetes version (use `kubectl version`): master
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

/area kubelet
/triage accepted
/importance long-term

**Comment by smarterclayton** [comment]
So to make this work we need to expose a core mechanism in the kubelet to summarize pods in config AND pods out of config (force deleted but still processing).  That requires some up front thinking because we are reconstructing pod state, so the prereq to execution is agreement there which I will drive.

/assign
