### ISSUE TITLE
[Failing test] [sig-node] NVIDIA GPU Device Plugin [Feature:GPUDevicePlugin][NodeFeature:GPUDevicePlugin][Serial] [Disruptive] DevicePlugin checks that when Kubelet restarts exclusive GPU assignation to pods is kept.

### ISSUE THREAD

**Issue by ehashman** [kubernetes/kubernetes#104175]
I can't find a single instance of this test passing in testgrid.

Run via https://testgrid.k8s.io/sig-node-kubelet#node-kubelet-serial and potentially other suites.

/sig node
/kind failing-test

**Comment by ruiwen-zhao** [comment]
The test fails because there is no GPUs reported by kubelet [1].

Looking at the node info right before the failure, the node does not have any gpu capacity [2]. And I cannot see any log related to device plugin in the kubelet log. 


[1] https://github.com/kubernetes/kubernetes/blob/master/test/e2e_node/gpu_device_plugin_test.go#L90

[2] 
```
"Status:NodeStatus{Capacity:ResourceList{cpu: {{2 0} {<nil>} 2 DecimalSI},ephemeral-storage: {{16684785664 0} {<nil>}  BinarySI},hugepages-2Mi: {{0 0} {<nil>} 0 DecimalSI},memory: {{7837757440 0} {<nil>} 7654060Ki BinarySI},pods: {{110 0} {<nil>} 110 DecimalSI},},Allocatable:ResourceList{cpu: {{2 0} {<nil>} 2 DecimalSI},ephemeral-storage: {{15016307073 0} {<nil>} 15016307073 DecimalSI},hugepages-2Mi: {{0 0} {<nil>} 0 DecimalSI},memory: {{7575613440 0} {<nil>} 7398060Ki BinarySI}
```

**Comment by endocrimes** [comment]
Since #104606 merged this test has been relatively stable. Going to close this issue now (kept it around while I was on PTO to take a look when I got back). Seems like there are some infrequent flakes that we should follow up on after we remove DKK.

/close
