### ISSUE TITLE
cluster/images/etcd uses old golang version and does not build

### ISSUE THREAD

**Issue by JacobX33** [kubernetes/kubernetes#104297]
Right now the golang version in the Makefile is set to GOLANG_VERSION?=1.12.17.

Build fails with "src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/client_conn_pool.go:305:6: undefined: errors.Is", presumably because errors.Is didn't exist in golang 1.12.

**Comment by serathius** [comment]
I can take a look.

**Comment by pacoxu** [comment]
According to https://github.com/etcd-io/etcd/blob/main/CHANGELOG-3.5.md#go, we should use 1.16.
/kind bug
/area release-eng

**Comment by serathius** [comment]
I send a fix. It would be good to make sure this doesn't break in the future. Question to @kubernetes/sig-testing: How we can include building cloud/image as part of presubmits?

**Comment by BenTheElder** [comment]
Somehow I thought maybe we'd switched to an ectd image built from the etcd project and needed to eventually drop this one? If not this is rather concerning.

We don't have a great presubmit to shove this in, I would suggest a run_if_changed presubmit to let reviewers of this image know if it builds w/o making it a required job on all PRs (since also changes should be scoped to a directory and infrequent).

**Comment by BenTheElder** [comment]
For example the conformance image works this way
