### ISSUE TITLE
update floatIP on openstack side, service can't perceive

### ISSUE THREAD

**Issue by liangjingtao11** [kubernetes/kubernetes#104385]
#### What happened:
Create a LoadBalancer type service through openstack LoadBalancer, This will help create LoadBalancer/floatip on the openstack side. And then you can see the created floatIp in the status field of the service like:

status:
  loadBalancer:
    ingress:
      - ip: 172.1.0.196

But if user update the floatIp or LoadBalancer on openstack side. The service cannot be sensed and updated.

#### What you expected to happen:
If user want to update the floatIP created by openstack LoadBalancer, the service can be synchronized here

#### How to reproduce it (as minimally and precisely as possible):
1 K8s use openstack cloud provider
2 Create  a LoadBalancer type service through openstack LoadBalancer
3 Update the floatIp on openstack side
4 Check whether the created service has updated the ip

#### Anything else we need to know?:
Kubernetes: v1.16.6
#### Environment:
- Kubernetes version (use `kubectl version`):v1.16.6
- Cloud provider or hardware configuration:OpenStack Newton LBaaSv2
- OS (e.g: `cat /etc/os-release`):irrelevant
- Kernel (e.g. `uname -a`):irrelevant
- Others:

**Comment by phiphi282** [comment]
This probably belong to [kubernetes/cloud-provider-openstack](https://github.com/kubernetes/cloud-provider-openstack)
I guess what you are looking for is this: kubernetes/cloud-provider-openstack#1597 :)

**Comment by liangjingtao11** [comment]
@phiphi282  Yes, it seems to be the same problem as your link.  Any other comments?

**Comment by phiphi282** [comment]
Since the occm can't do reconciling based on openstack resources after loadbalancer creation this would be more of a new feature instead of a bugfix.
If you are still using the internal cloud controller manager then there will most likely not be an update on this since these got deprecated in favor of the external cloud providers (see https://github.com/kubernetes/legacy-cloud-providers).

You can bring this issue to the external cloud controller manager for openstack (kubernetes/cloud-provider-openstack) where there are already talking about this as described in my previous comment :) 
However, since kubernetes 1.16 is already EOL there won't be an update for this there but earliest in the next minor version which is 1.22.

**Comment by andrewsykim** [comment]
Thanks @phiphi282 for the details. I'm gonna close this one since it seems like a feature request to the deprecated in-tree openstack cloud provider.

/close
