### ISSUE TITLE
Image pull policy to automate rolling updates upon image tag changes

### ISSUE THREAD

**Issue by mcandre** [kubernetes/kubernetes#104306]
#### What would you like to be added:

A new image pull policy option, which communicates to Kubernetes the desire to automatically perform a rolling restart of pods when the image tag receives an update. For example, the image pull policy could be called `FollowTagUpdates`.

This would work well for engineering teams that use `latest`, `stable`, `devel`, `<major-version>`, `<major>.<minor>`, or similar rolling update tag naming conventions.

#### Why is this needed:

Relieves DevOps of the need to explicitly perform rolling restarts.

**Comment by pacoxu** [comment]
In the testing environment, we set the image pull policy to be `Always` so that pod is running with the newer image once being recreated.

In my practice, we add a continuous delivery process for the registry. The CD process will update/restart the deployment(after update/restart, a new pod will trigger image pull as the imagePullPolicy is always) once the tag is changed/updated.

**Comment by caesarxuchao** [comment]
/sig node
/remove-sig api-machinery
cc @kubernetes/api-reviewers
