### ISSUE TITLE
Enabling ServiceAppProtocol feature gate doesn't seem to take effect

### ISSUE THREAD

**Issue by keymone** [kubernetes/kubernetes#104358]
#### What happened:

Followed the documented procedure of enabling a feature gate, but it doesn't seem to take effect.

#### What you expected to happen:

I expect to be able to create a service with appProtocol attribute in port options. Instead I get this error message:

    * spec.ports[0].appProtocol: Forbidden: This field can be enabled with the ServiceAppProtocol feature gate

#### How to reproduce it (as minimally and precisely as possible):

Given a cluster configured by kubeadm, I've modified kubeadm.yaml to include

```yaml
---
apiVersion: kubelet.config.k8s.io/v1beta1
...
featureGates:
  ...
  ServiceAppProtocol: true
```

- verified that kubeadm successfully finished the upgrade procedure
- verified that kubelet-config-1.18 contains new feature gate
- verified that `/var/lib/kubelet/config.yaml` contains new feature gate
- verified that kubelet on master node is passed `--config=/var/lib/kubelet/config.yaml`
- restarted kubelet processes, apiserver and controller-manager pods on each master node

Still can't create service with appProtocol attribute.

#### Environment:
- Kubernetes version (use `kubectl version`):
      Client Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-dirty"...}
      Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.9"...}```
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): 18.04.5 LTS (Bionic Beaver)
- Kernel (e.g. `uname -a`): 5.4.0-1030-aws

**Comment by keymone** [comment]
another detail - i do see this log message in kubelet log:

    Aug 11 07:48:40 foo kubelet[13791]: I0811 07:48:40.087026   13791 feature_gate.go:243] feature gates: &{map[... ServiceAppProtocol:true]}

so kubelet is initialized with that feature gate enabled

**Comment by keymone** [comment]
turns out, this feature gate should have been enabled on api server component separately. none of the documentation i found mentions this :(

**Comment by MadhavJivrajani** [comment]
@keymone thank you for creating this issue.
`ServiceAppProtocol` should be enabled by default since it went to GA in v1.20 and shouldn't require a feature gate anymore (this is also probably why you didn't see its mention in the `kube-apiserver` command line reference). The reason I think that you had to enable it explicitly is because of v18 being run (`ServiceAppProtocol` was still in alpha at the time, and hence disabled).

A complete list of feature gates and their status along with what versions they reached said status can be found here - https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/

I'm closing this issue for now, but if I've misunderstood anything please feel free to correct me and reopen this issue, you can do so my commenting `/reopen`
/close

Have a good day!

**Comment by keymone** [comment]
@MadhavJivrajani you're right that it's no longer an issue for this particular feature gate, but i don't understand how would i have been able to figure out what components that feature gate was relevant for at time of launch. i've browsed the codebase at version 1.18 and didn't find any documentation or even a comment that it should've been enabled for apiserver component. I still don't know if that's the only relevant component or should i enable it in some other components too.

how does discovering things like that work for features that are currently in alpha/beta?

**Comment by MadhavJivrajani** [comment]
@keymone, typically for older versions, you can time travel back in the documentation by prepending `v-version.docs.` to the current kubernetes.io URL. To know which feature flag to enable on which component, the best place to look at would be the command line reference for that component, so for `v1.18`, the place to look at would be: https://v1-18.docs.kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/ and then search for `ServiceAppProtocol`
