### ISSUE TITLE
make common sidecar for all pod in the cluster

### ISSUE THREAD

**Issue by artb1sh** [kubernetes/kubernetes#104480]
Hi, could you please make common sidecar for all pod in the cluster

#### What would you like to be added:
shared one sidecar for many any pods
#### Why is this needed:
utilization resource

**Comment by zxh326** [comment]
you can use `Admission Webhook` to inject sidecar for all pods

**Comment by mikebell90** [comment]
I think the point of the requester is that sidecars in their sum usage over many containers may be prone to “slack” and reusing the same one is “good”. Maybe I am wrong about this interpretation?

In general it seems better to just tune your sidecar so it doesn’t have much wasted memory snd cpu. That can be difficult with widely varying load and hence I am guessing that is what the poster points out. For example a mesh proxy can be very heavy with a busy pod and pretty light with an idle one but who would want to individually tune these ?

assuming I am correct and admitting I am a n00b it seems this would be better done at the cni level. Because what you really want is a poll of “sidecars” perhaps as a daemonset that is tapping into the pods traffic and “faking” being a true sidecar. If I’m not mistaken I sssume this is the approach cilium takes.  The alternative is the pod calls an external service as it’s “pseudo sidecar”

But I’m happy to be schooled as to my ignorance.

**Comment by thockin** [comment]
Thanks fir the interp @mikebell90.  If this is  what you describe, it's more like a "middle proxy" or "service chain". 
 It's not really a sidecar if it's not in the pod. :)

Aside from that, a sidecar is a VERY broad term it could be a log-saver (needs some shared FS) or a network proxy (needs some shared network) or a debugger (needs shared PID).

So we need moire details - this issue is very under-specified.  Without more details, we will have to close it.

**Comment by artb1sh** [comment]
@thockin @mikaelh . one filebeats, syslog, gatekeeper or any one sidecar for all pods

**Comment by mikebell90** [comment]
@artb1sh yes, but define "one". one sidecar total as in one single container shared by all pods? That doesn't really make sense. You'll need more than that to spread the load. CNI is probably the way to go for network level type sidecars. In that you have a DaemonSet (many, since you have load no matter what), and use the CNI to rewrite the tables. 

Or are you just trying to template (which saves no resources).

In the end you either have one sidecar per pod, or you have many pods connecting to a single pool (service deployment or daemonset). Which is it you are describing.

**Comment by thockin** [comment]
@artb1sh - can you please write a little (or a lot) more about a concrete example and how you think it SHOULD work?  There are all sorts of sidecars, and some of them would just not make any sense in the model you're suggesting.  So I suspect you have something more concrete in mind.  Please share?
