### ISSUE TITLE
Add non-serialized metrics tests for Windows

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/kubernetes#104418]
#### What happened:

- Lets put a metrics CI job in place that isnt `Serial`.
- Investigate our test coverage of metrics-server
- See why our CI jobs dont test metrics-server
- Confirm that we are doing enough in `kubelet_stats`

#### What you expected to happen:

https://github.com/kubernetes/kubernetes/blob/master/test/e2e/windows/kubelet_stats.go is a good test, lets make it part of all our containerd jobs by removing the Serial tags

**Comment by jayunit100** [comment]
while were at it
```
 				for i := 0; i < iterations; i++ {
```

make that iterations a non-magic number

**Comment by jayunit100** [comment]
while were at it make sure the metrics stats are non-zero , so that we catch regressions #102487

**Comment by san-coding** [comment]
Hey, is this issue still open? I would like to work on this, I am new to open source

**Comment by marosset** [comment]
@san-coding 
We cannot de-serialize the existing metrics job due to its nature.
We can however create new test cases that do not need to be run in parallel and do deeper validation of metrics like Jay suggested above.
I'm not sure if @FriedrichWilken is still working on the issue. If not feel free to work on this.

Thanks!

**Comment by marosset** [comment]
/retitle Add non-serialized metrics tests for Windows

**Comment by NikhilSharmaWe** [comment]
I would like to contribute to solve this issue. Can someone help me to get a clear picture what are trying to do and how can I proceed.
