### ISSUE TITLE
switch away from "go mod graph" for dependency stats

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubernetes#104461]
the kubernetes/kubernetes repository has a [dependency stats presubmit](https://github.com/kubernetes/test-infra/blob/6d524aecb66d5c1c7aac0009fe67c41522e5d0f1/config/jobs/kubernetes/sig-arch/kubernetes-depstat.yaml) e2e test job that is responsible for keeping track of statistics of dependencies when an update to a dependency happens in the repository.

currently, this e2e test job uses `go mod graph`. yet the go 1.17 release makes changes to how the command behaves and denormalizes all transitive dependencies into the root go.mod file. this affects our current usage of the command.

upstream Golang issue:
https://github.com/golang/go/issues/47648
according to the maintainer we should switch away from `go mod graph` and use `go mod why` (and `go mod why -m`) and `go list`.

alternatively we could try this third party tool that the maintainers recommended (it has a `graph` subcommand):
https://beta.pkg.go.dev/github.com/loov/goda

this can be done after we start building with golang 1.17

**Comment by neolit123** [comment]
cc @liggitt 

/area test code/organization
/sig architecture
/help

let us know if you have any questions.

**Comment by liggitt** [comment]
given that we want stats for the whole graph, not just a single dependency, I think either `go list` or some other tool built on top of `go list` will be needed

**Comment by liggitt** [comment]
one possibility is to transform the output of `go list -json -test ./...` to return a graph that matches the format of `go mod graph` and use that as input to tools that are currently processing `go mod graph` successfully

**Comment by palnabarun** [comment]
cc: @RinkiyaKeDad

**Comment by liggitt** [comment]
hoisting comments from @RinkiyaKeDad in slack:

Tried out this approach [here](https://github.com/RinkiyaKeDad/gomodgraph-sixteen/blob/master/cmd/root.go#L75-L140). Ran into some issues.

I was testing this on a small project where the main module was `github.com/go-modules-test` and the only two direct dependencies were `github.com/julienschmidt/httprouter` and `go.uber.org/zap`.

For the Deps of `github.com/go-modules-test` I saw `go.uber.org/atomic` in the list. So when we cycle through the Deps of the main module we will come across it and since it is not a standard package we’ll add an edge from `github.com/go-modules-test .Path -> go.uber.org/atomic .Path` which is `github.com/go-modules-test -> go.uber.org/atomic`

But we don’t want this edge :confused:

other than that too a lot things were missing from the output I got. For example the `go mod graph` output had the following edge:
```
go.uber.org/zap@v1.16.0 golang.org/x/lint@v0.0.0-20190930215403-16217165b5de
```

But when I search for `golang.org/x/lint` in the `go list -json -deps` output for my sample project, it isn’t even present so we don’t get this edge and many others like this one.

After spending some more time messing with this, I think we are missing some information in `go list -json -test -deps all`. 

For the sample project I was playing with the original `go mod graph` output had these lines:
```
go.uber.org/zap@v1.16.0 github.com/pkg/errors@v0.8.1
go.uber.org/zap@v1.16.0 github.com/stretchr/testify@v1.4.0
go.uber.org/zap@v1.16.0 go.uber.org/atomic@v1.6.0
go.uber.org/zap@v1.16.0 go.uber.org/multierr@v1.5.0
go.uber.org/zap@v1.16.0 golang.org/x/lint@v0.0.0-20190930215403-16217165b5de
go.uber.org/zap@v1.16.0 gopkg.in/yaml.v2@v2.2.2
go.uber.org/zap@v1.16.0 honnef.co/go/tools@v0.0.1-2019.2.3
```

But the output from `go list -json -test -deps all`  doesn’t have these two packages mentioned anywhere:
```
golang.org/x/lint
honnef.co/go/tools
```

**Comment by liggitt** [comment]
I think that's because those are only deps via the tools build tag

https://github.com/uber-go/zap/blob/v1.16.0/tools_test.go

it looks like `go list` doesn't give you a way to say "show me all deps via all build tags"

**Comment by RinkiyaKeDad** [comment]
Minor update I forgot to mention, this won't be a problem

```
For the Deps of github.com/go-modules-test I saw go.uber.org/atomic in the list. So when we cycle through the Deps of the main module we will come across it and since it is not a standard package we’ll add an edge from github.com/go-modules-test .Path -> go.uber.org/atomic .Path which is github.com/go-modules-test -> go.uber.org/atomic

But we don’t want this edge 😕

other than that too a lot things were missing from the output I got. For example the go mod graph output had the following edge:

go.uber.org/zap@v1.16.0 golang.org/x/lint@v0.0.0-20190930215403-16217165b5de
But when I search for golang.org/x/lint in the go list -json -deps output for my sample project, it isn’t even present so we don’t get this edge and many others like this one.
```

since we have access to the [Indirect](https://github.com/RinkiyaKeDad/gomodgraph-sixteen/blob/master/cmd/root.go#L41) field which lets us know that `go.uber.org/atomic` is an indirect dependency and hence we can skip adding the `github.com/go-modules-test -> go.uber.org/atomic` edge.

But the rest of what Jordan posted is still a blocker for us.

**Comment by RinkiyaKeDad** [comment]
We seem to be blocked by the Go team on this - https://github.com/golang/go/issues/47648#issuecomment-916092706

/remove-lifecycle stale

**Comment by RinkiyaKeDad** [comment]
We're still blocked on this, see Jordan's comment [here](https://github.com/golang/go/issues/42504#issuecomment-1098273774).

/remove-lifecycle rotten

**Comment by liggitt** [comment]
resolved this as best as we can with https://github.com/kubernetes-sigs/depstat/pull/65
