### ISSUE TITLE
pod disruption budget allowed disruptions not deleted along with pod

### ISSUE THREAD

**Issue by shivrajjadhav733** [kubernetes/kubernetes#104487]
#### What happened: I have an application which is deployed on kubernetes. There are 4 pods running:  PodA-123, PodB-456 and PodB-123, PodB-456
When I start application, I initialize 4 pods. I have matching labels configured in both deployment and pdb yaml configurations. Based on that when I run command kubectl get pdb, i see two pdb (one for podA and another for podB) 
"Min Available -> 1 and Allowed Disruption-> 1" .
Now when I delete lets say PodB both instances, i see no pods for PodB and kubectl get pdb shows "Min Available -> 0 and Allowed Disruption-> 0"
and status is seen as 
status:
  currentHealthy: 0
  desiredHealthy: 0
  disruptionsAllowed: 0
Events:
  Type    Reason  Age                      From               Message
  ----    ------  ----                     ----               -------
  Normal  NoPods  2m17s (x525 over 4h32m)  controllermanager  No matching pods found

#### What you expected to happen:
I would want to delete pdbB as well if no matching podB is found.
Is it possible to do? If yes, How can I achieve it? 
If no, why not and should it expected to restart another instance of PodB?

#### How to reproduce it (as minimally and precisely as possible):
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployA
  labels:
    appname: xyz
  annotations:
	appname: xyz
spec:
  replicas: 2
  selector:
    matchLabels:
      appname : xyz
  template:
    metadata:
	  name: podA
	  labels:
		appname: xyz
	  annotations:
		appname: xyz
	spec:
		containers:
		
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: pdbA
  labels:
    appname: xyz
  annotations:
	appname: xyz
spec:
  minAvailable: 1
  selector:
    matchLabels:
      appname : xyz

Same is configuration for PodB and pdbB

#### Environment:
- Kubernetes version (use `kubectl version`): 1.19
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by soltysh** [comment]
@atiratree fyi

**Comment by atiratree** [comment]
I could not reproduce this, but I need a bit more qualifying information:

> Kubernetes version (use kubectl version): 1.19

Is this client or server version? I have tested this on 1.19 and on master.

> Same is configuration for PodB and pdbB

do the label selectors differ between Deployment/PodDisruptionBudget A and B ? I presumed that they do

> Now when I delete lets say PodB both instances, i see no pods for PodB and kubectl get pdb shows "Min Available -> 0 and Allowed Disruption-> 0"

this could not be reproduced. The values updated correctly for me. Allowed disruption changed but the min available stayed the same.

status before:

```
    currentHealthy: 2
    desiredHealthy: 1
    disruptionsAllowed: 1
    expectedPods: 2
    observedGeneration: 1
```

status after:

```
    currentHealthy: 0
    desiredHealthy: 1
    disruptionsAllowed: 0
    expectedPods: 0
    observedGeneration: 1
```

> I would want to delete pdbB as well if no matching podB is found.
> Is it possible to do? If yes, How can I achieve it?

Self deletion is not a responsibility of a PDB. You could achieve this with a custom controller or by some other automation/delivery method

> If no, why not and should it expected to restart another instance of PodB?

Sorry, I am not following here. Pods are managed by the Deployment in your case.

@shivrajjadhav733 
Since it was not possible to reproduce, can you please post a working example ( full YAMLs + simple bash script) that reproduces this issue?

**Comment by shivrajjadhav733** [comment]
I found out the issue was due to HPA configuration getting kicked in due to cpu utilization hitting max capacity. With that issue has been identified and resolved.
