### ISSUE TITLE
Create service but feel something wrong about iptables?

### ISSUE THREAD

**Issue by hjianhao** [kubernetes/kubernetes#10441]
I compile and setup kubernetes cluster from master branch. When After I create service, I can not access the service , I see the iptables, that's the items:

On 0.19.0 , the KUBE-PORTALS-CONTAINER's target is REDIRECT, BUT now is the DNAT the same as the following KUBE-PORTALS-HOST, is there something wrong or need some configruations?

Chain KUBE-PORTALS-CONTAINER (1 references)
target     prot opt source               destination         
DNAT       tcp  --  0.0.0.0/0            10.100.0.1           /* default/kubernetes: */ tcp dpt:443 to:192.168.1.172:40996
DNAT       tcp  --  0.0.0.0/0            10.100.86.189        /* default/webfrontend: */ tcp dpt:9000 to:192.168.1.172:51323

Chain KUBE-PORTALS-HOST (1 references)
target     prot opt source               destination         
DNAT       tcp  --  0.0.0.0/0            10.100.0.1           /* default/kubernetes: */ tcp dpt:443 to:192.168.1.172:40996
DNAT       tcp  --  0.0.0.0/0            10.100.86.189        /* default/webfrontend: */ tcp dpt:9000 to:192.168.1.172:51323

**Comment by thockin** [comment]
Did you set --bind-address to a value other than 0.0.0.0 ?  That's what
this indicates.

**Comment by goltermann** [comment]
We’re going through old support issues and asking everyone to direct your questions to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes). 

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases. 

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.
