### ISSUE TITLE
ci-crio-cgroupv2-node-e2e-conformance is failing 

### ISSUE THREAD

**Issue by harche** [kubernetes/kubernetes#104567]
#### Which jobs are failing:
ci-crio-cgroupv2-node-e2e-conformance
pull-kubernetes-node-crio-cgrpv2-e2e

#### Which test(s) are failing:
`.[sig-node] Summary API [NodeConformance] when querying /stats/summary should report resource usage through the stats api`

#### Since when has it been failing:
20th Aug 2021

#### Testgrid link:
https://testgrid.k8s.io/sig-node-cri-o#ci-crio-cgroupv2-node-e2e-conformance

#### Reason for failure:
Not yet known. But the test consistently fail with systemd cgroups driver + cgroups v2.

**Comment by SergeyKanzhelev** [comment]
Started failing between:

https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-crio-cgroupv2-node-e2e-conformance/1428526241794756608 and https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-crio-cgroupv2-node-e2e-conformance/1428541341452734464

**Comment by SergeyKanzhelev** [comment]
Also failing here: https://github.com/kubernetes/kubernetes/issues/103759

**Comment by bobbypage** [comment]
Spent some time to investigate this. The problem here is related to https://github.com/google/cadvisor/pull/2801

The test was failing to obtain NodeStats. NodeStats are obtained from `rootStats` which obtains stats for root cgroup from cAdvisor.

https://github.com/kubernetes/kubernetes/blob/e5c4defa8e2ed6b1c5da26f68d586b9712e92df1/pkg/kubelet/server/stats/summary.go#L75

This ends up calling cAdvisor get container info with root container `/`/
https://github.com/kubernetes/kubernetes/blob/e5c4def/pkg/kubelet/stats/provider.go#L112
https://github.com/kubernetes/kubernetes/blob/e5c4def/pkg/kubelet/stats/helper.go#L306-L311

The main stats collected by cAdvisor is done via calling into raw handler for libcontainer here
https://github.com/kubernetes/kubernetes/blob/e5c4def/vendor/github.com/google/cadvisor/container/libcontainer/handler.go#L83-L92

For CPU stats, libcontainer relies on reading  `cpu.stat` file. 

https://github.com/kubernetes/kubernetes/blob/e5c4defa8e2ed6b1c5da26f68d586b9712e92df1/vendor/github.com/opencontainers/runc/libcontainer/cgroups/fs2/cpu.go#L52

`cpu.stat` file did not previously exist on root cgroup for cgroupv2, it was not implemented in the kernel. As a result, no metrics were able to be obtained for `/` root by libcontainer, thus failing the test. 

Adding root `cpu.stat` file on cgroupv2 was only added on kernel 5.8.
https://kernelnewbies.org/Linux_5.8
`cgroup: add cpu.stat file to root cgroup commit`
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=936f2a70f2077f64fab1dcb3eca71879e82ecd3f

The test is currently running under 5.4 kernel without this change. I tested with newer COS image under 5.10 kernel and the test passed successfully since the `cpu.stat` exists for root cgroup.

**Comment by harche** [comment]
Looking at https://testgrid.k8s.io/sig-node-cri-o#ci-crio-cgroupv2-node-e2e-conformance, it doesn't seem to consistently fail as it used to be. 

/close
