### ISSUE TITLE
Job pull-kubernetes-node-e2e-alpha constant failure

### ISSUE THREAD

**Issue by mmiranda96** [kubernetes/kubernetes#104556]
#### Which jobs are failing:
pull-kubernetes-node-e2e-alpha

#### Which test(s) are failing:
All tests run by the pipeline fail.

#### Since when has it been failing:
Since its first run.

#### Testgrid link:
https://k8s-testgrid.appspot.com/presubmits-kubernetes-nonblocking#pull-kubernetes-node-e2e-alpha

#### Reason for failure:
Local services are set to start, but this fails with the following message:
```
failed to start internal services: failed to run start command for server \"services\": exit status 255
```

#### Anything else we need to know:
This pipeline appears to not run as part of any presubmit. It has very few runs, and most of them have been manually triggered.

**Comment by SergeyKanzhelev** [comment]
@mmiranda96 do you know whether we run these same tests in different job? If so we can just remove this job.

**Comment by mmiranda96** [comment]
Job `ci-kubernetes-node-kubelet-alpha` has a very similar configuration (see [ci-kubernetes-node-kubelet-alpha](https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-node/node-kubelet.yaml#L43) vs. [pull-kubernetes-node-e2e-alpha](https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-node/sig-node-presubmit.yaml#L216)). They both run the same tests, and aside one being a PR job and the other one a periodic job, they don't look very different. This is [ci-kubernetes-node-kubelet-alpha TestGrid dashboard tab](https://k8s-testgrid.appspot.com/sig-node-kubelet#node-kubelet-alpha).

I think I could use a second opinion, but I believe we can safely delete job `pull-kubernetes-node-e2e-alpha` considering the following:
- Such job has seldom been run, all of these runs have been triggered manually.
- All these runs have failed.
- `ci-kubernetes-node-kubelet-alpha` runs the same tests in a periodic fashion and it passes constantly.

**Comment by ehashman** [comment]
Node has a general practice of trying to have a corresponding presubmit job for every periodic job. This ensures that we can invoke the periodic job on PRs as needed. Hence, I don't think we should remove the presubmit without removing the periodic.

There are a few possible paths forward:

1. The presubmit job might be broken, as it looks like the periodic is green. We could try to fix the presubmit.
2. The alpha periodic seems like it duplicates functionality in the blocking, required alpha features job: https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-alpha-features

From what I can see a bunch of the tests in the node-alpha job aren't actually alpha anymore...

I think it's reasonable for us to try to get rid of this separate job and fold any node alpha tests into the existing SIG Release blocking alpha job rather than maintaining our own general alpha features suite. For anything that needs special infra or configuration, we'll have to create a separate job anyways.

**Comment by mmiranda96** [comment]
I've created https://github.com/kubernetes/test-infra/issues/23642 to keep track of the jobs you mention. If we move forward with the merge plan, I think it would make sense to:
1. Clean the target jobs.
2. Update the target jobs to match these features.
3. Drop the current jobs.

Let me know your thoughts.

**Comment by SergeyKanzhelev** [comment]
/close

this was fixed by https://github.com/kubernetes/test-infra/pull/24405/files
