### ISSUE TITLE
Implement watch at apiserver level

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#10475]
Implementing should give us significant performance improvements, because:
- we avoid sending multiple watch requests to etcd that send as huge amount of unnecessary data
 (e.g. currently all Kubelets are watching for pods, but since filtering is done at the apiserver level, there are O(#nodes) watches to etcd open all the time , each of them sending all pods)
- on top of that we can build some Indexer - see  https://github.com/GoogleCloudPlatform/kubernetes/issues/4817#issuecomment-89437368 for more details

cc @lavalamp @davidopp @bprashanth @timothysc

**Comment by lavalamp** [comment]
I think this & indexer are exactly the same problem and should be solved with the same bit of code.

**Comment by wojtek-t** [comment]
I think Indexer is v2.0 of this one - I agree this should be the same code, but I think that the watch in apiserver is initial version that could then be extended to the Indexer.

**Comment by wojtek-t** [comment]
To be more clear - I agree that Indexer and this thinkg should be the same code - I just think that we can separate it into 2 steps which by first step I mean watch in apiserver.

**Comment by bprashanth** [comment]
We should separate it into more than 2 steps and share the work. This is going to be a source of enough bugs that everyone maintaining the apiserver should know (vaguely) how to debug. Tackling this as purely a performance optimization doesn't sound like a good idea.

**Comment by wojtek-t** [comment]
>
We should separate it into more than 2 steps and share the work. This is going to be a source of enough bugs that everyone maintaining the apiserver should know (vaguely) how to debug. 

I agree. I just think that those are two biggest steps, but we should divide them deeper.

>
Tackling this as purely a performance optimization doesn't sound like a good idea.

I don't understand what do you mean by that.

**Comment by wojtek-t** [comment]
I tried to put all my thoughts together and wrote a more detailed proposal in a more fine-grained way that could be divided among few people.

I'm not focusing on the Indexer here, although my design is supposed to be compatible with the proposal for the Indexer from https://github.com/GoogleCloudPlatform/kubernetes/issues/4817#issuecomment-89437368

### High-level proposal

The watch in apiserver will be plugged to the generic registry (pkg/registry/generic) - let's call it WatchProcessor. Internally it will have just a single watch open to etcd, listening to all objects of a given resource type. Whenever watch request reaches apiserver, it will be redirected to WatchProcessor which will register it (e.g. by storing it's filtering function - matcher) and will start a separate go-routine for it that will be iterating over that internal cache (built by the watch to etcd), filtering its elements and sending them back to the client. Processing errors and some corner cases is described in more details below.

### Detailed steps

0. The object responsible for processing all watch requests will be plugged into generic registry ("pkg/registry/generic"). Thus we should first migrate all the resources to use it. As for now, the ones to be migrated are: events, limit ranges and services.

1. Create an object responsible for processing all the watch requests (let's call it WatchProcessor) and use it in generic registry. In the initial representation it should just redirect all the requests to etcd (i.e. no logical change to what we have now). However, we should make using WatchProcessor optional for different resources (I think it won't be useful for many of them, at least for now).

2. WatchProcessor internally will have just a single watch open to the etcd reading all the changes to objects of a given resource. However, this watch can potentially expire and renewing it can return "error too old" - in that case, relisting is necessary. Thus, to avoid relists coming from all the clients, (as suggested in https://github.com/GoogleCloudPlatform/kubernetes/issues/4817#issuecomment-89437368) we will create an additional etcd event type: EtcdResync:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/tools/etcd_helper_watch.go#L36
Whenever relisting will be done in WatchProcessor, we will just send EtcdResync event to all the watchers which will contain the full list of all the objects the watcher is interested in as the parameter of the watch event.
This step is to add the EtcdResync event, extend watch.Interface and its implementations to support it (and handle those events appropriate in places like Reflector: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/client/cache/reflector.go )

3. Change the WatchProcessor to have a single watch call to etcd open (observing all the changes to all objects of a given resource) and and create a fifo-cache for them (a cache has a limited capacity and if we need to remove something, we remove an objects with the smallest resourceVersion = etcdIndex). This cache should also support returning the list of all objects from the "beginning time" (i.e. from the moment just before the oldest cached change read from etcd) and from "now" (right after the last cached change read from etcd).

4. Change the handling of watch request to just "register" them in WatchProcessor (registration means storing their filtering function (matcher) and their "current" resourceVersion). There will be a dedicated go routine per watcher, that will be iterating over the cache, filtering cache objects and sending them to the user.
Note that if a per-watcher go-routine will fall behind the oldest element of a cache, this would require sending EtcdResync event to the client and "resetting" it. Similarly, we can send an EtcdResync event if the watch request comes with resourceVersion older than the oldest cached one.

5. Add a support to WatchProcessor to appropriately handling "error too old" from etcd. What it should do is:
    - stop sending watch events to all registered watchers
    - clear the cache and relist all objects from etcd
    - send a EtcdResync event to all watchers (appropriately filter objects in all of them)
    - restart per-watcher go routines with the new value of resourceVersion

6. Enable WatchProcessor (for some resources - for pods the gains should be most visible).

I think that in the future we can extend it (without any design changes) to internally support indexing.


Any thoughts about it are very welcome: @lavalamp @bprashanth

**Comment by wojtek-t** [comment]
cc @smarterclayton

**Comment by smarterclayton** [comment]
@derekwaynecarr as well

**Comment by derekwaynecarr** [comment]
Can you write your doc as a design PR in ```docs/design```, so its easier to comment on specific sections and give feedback on selective items?

**Comment by derekwaynecarr** [comment]
@wojtek-t 

LimitRange is using etcdgeneric already.

Can you elaborate on the pros/cons of having a watch per resource type versus just having a single watch for all changes from root of the etcd repo?

**Comment by smarterclayton** [comment]
It seems like from the proposal above you're trying to avoid two things:

1. Having too many watches on etcd
2. avoiding deserializing objects twice in two different watch results

I would argue that those are separate problems.  Solving "deduping watches on etcd and offering longer history" is a smaller problem that is decoupled from "allow many clients to get a FIFO on the same store".  I think it would be superior to:

1. Provide a mechanism for deduping direct etcd watches, preserving longer history, and handling the "lost last index we saw an update for" problem
2. Wire that into etcd helper as a single object
3. On top of a registry, implement a store that can have multiple FIFOs (which may have similar characteristics)

That also preserves the separation between a store (API layer) and an etcdhelper/watch (db layer)

**Comment by wojtek-t** [comment]
@derekwaynecarr 

>
Can you write your doc as a design PR in docs/design, so its easier to comment on specific sections and give feedback on selective items?

Sure - will do. Let me just clarify something with @smarterclayton first (since it may change some things).


@smarterclayton 

>
It seems like from the proposal above you're trying to avoid two things:
1. Having too many watches on etcd
2. avoiding deserializing objects twice in two different watch results

I agree (although for 2 we already have a cache that is partially achieving it:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/tools/etcd_helper_watch.go#L275 - however, even deserializing jsons from http responses from etcd is expensive - so yes, those are basically things that we would like to achieve).
However, note that we would also like to build an Indexer on top of it in the near future too.

>
I would argue that those are separate problems. Solving "deduping watches on etcd and offering longer history" is a smaller problem that is decoupled from "allow many clients to get a FIFO on the same store". I think it would be superior to:
- Provide a mechanism for deduping direct etcd watches, preserving longer history, and handling the "lost last index we saw an update for" problem

This is exactly what I'm proposing - or do you disagree with that?

> 
- Wire that into etcd helper as a single object

I wanted to put it into registry/etcd, but I'm completely fine with putting it to etcd helper - this doesn't change anything in my proposal. 

> 
- On top of a registry, implement a store that can have multiple FIFOs (which may have similar characteristics)
That also preserves the separation between a store (API layer) and an etcdhelper/watch (db layer)

 I'm not sure if I understand what to you mean by "a store that can have multiple FIFOs". Can you please clarify?

**Comment by smarterclayton** [comment]
> However, note that we would also like to build an Indexer on top of it in
the near future too.

I may have missed / forgotten this from an earlier discussion, but how
would this Indexer differ from the existing Indexer we have on the store,
which provides incremental atomic maintenance and is used by several
components already?  Indexers are coupled to API objects and Stores - so my
assumption is that reducing open watches would not impact the store.

> I'm not sure if I understand what to you mean by "a store that can have
multiple FIFOs". Can you please clarify?

Today we are starting to accumulate controllers and admission controllers
that watch the same content.  Namespaces are the best example.  Rather than
having two etcd list watchers feeding two stores with two FIFOs, I would
prefer one list watcher, one store, and two FIFOs.  That would then
preserve our existing design patterns and require no net new concept.



On Jul 1, 2015, at 3:08 AM, Wojciech Tyczynski <notifications@github.com>
wrote:

@derekwaynecarr <https://github.com/derekwaynecarr>

Can you write your doc as a design PR in docs/design, so its easier to
comment on specific sections and give feedback on selective items?

Sure - will do. Let me just clarify something with @smarterclayton
<https://github.com/smarterclayton> first (since it may change some things).

@smarterclayton <https://github.com/smarterclayton>

It seems like from the proposal above you're trying to avoid two things:
1. Having too many watches on etcd
2. avoiding deserializing objects twice in two different watch results

I agree (although for 2 we already have a cache that is partially achieving
it:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/tools/etcd_helper_watch.go#L275
- however, even deserializing jsons from http responses from etcd is
expensive - so yes, those are basically things that we would like to
achieve).
However, note that we would also like to build an Indexer on top of it in
the near future too.

I would argue that those are separate problems. Solving "deduping watches
on etcd and offering longer history" is a smaller problem that is decoupled
from "allow many clients to get a FIFO on the same store". I think it would
be superior to:

   - Provide a mechanism for deduping direct etcd watches, preserving
   longer history, and handling the "lost last index we saw an update for"
   problem

 This is exactly what I'm proposing - or do you disagree with that?


   - Wire that into etcd helper as a single object

 I wanted to put it into registry/etcd, but I'm completely fine with
putting it to etcd helper - this doesn't change anything in my proposal.


   - On top of a registry, implement a store that can have multiple FIFOs
   (which may have similar characteristics) That also preserves the separation
   between a store (API layer) and an etcdhelper/watch (db layer)

 I'm not sure if I understand what to you mean by "a store that can have
multiple FIFOs". Can you please clarify?

—
Reply to this email directly or view it on GitHub
<https://github.com/GoogleCloudPlatform/kubernetes/issues/10475#issuecomment-117494601>
.

**Comment by wojtek-t** [comment]
>
Today we are starting to accumulate controllers and admission controllers
that watch the same content.  Namespaces are the best example.  Rather than
having two etcd list watchers feeding two stores with two FIFOs, I would
prefer one list watcher, one store, and two FIFOs.  That would then
preserve our existing design patterns and require no net new concept.

Sorry - my thought must have been unclear - but this is exactly what my proposal is about.
Also - this is supposed to be completely implementation detail - there should be no changes to the clients.

**Comment by wojtek-t** [comment]
In that case, I will try to write a doc with the proposal as @derekwaynecarr suggested (hopefully later this week or next week).

**Comment by smarterclayton** [comment]
Ok - I was confused by the watch processor discussion, since the
terminology I was expecting to hear was "multiple DeltaFIFOs on a store",
as well as "unifying underlying etcd watchers under etcd helper".  I think
we're on the same page - sorry :)

On Wed, Jul 1, 2015 at 10:04 AM, Wojciech Tyczynski <
notifications@github.com> wrote:

> In that case, I will try to write a doc with the proposal as
> @derekwaynecarr <https://github.com/derekwaynecarr> suggested (hopefully
> later this week or next week).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleCloudPlatform/kubernetes/issues/10475#issuecomment-117686303>
> .
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by wojtek-t** [comment]
@smarterclayton - thanks. I will try to be more clear when writing this doc.

**Comment by lavalamp** [comment]
I will try to find time to give feedback on this next week.

**Comment by wojtek-t** [comment]
@lavalamp - thanks - I will try to write my proposal in more clear way as a doc. Will let you know once it is ready.

**Comment by wojtek-t** [comment]
I've created #10679 with (hopefully) cleaner description of my proposal.

**Comment by wojtek-t** [comment]
#10679 is already LGTM-ed so it contains the design I will be implementing (starting today/tomorrow)

**Comment by wojtek-t** [comment]
I was running some tests over the weekend and there are two PRs opened fixing 2 correctness issues. Other than that, I wasn't able to catch any other problem with th Cacher.
So, when those two PRs are merged (#12721 #12782), I'm going to send a PR switching the cache for first resources.

**Comment by wojtek-t** [comment]
This has finally been reenabled today. So far, our e2e tests look ok I will be watching them, but I hope that this is finally done.

**Comment by wojtek-t** [comment]
This is enabled for all resources (except from events). So I'm closing this bug now.
