### ISSUE TITLE
Refactor `audit_test.go`

### ISSUE THREAD

**Issue by slaskawi** [kubernetes/kubernetes#104893]
#### What would you like to be added:

The `test/integration/controlplane/audit_test.go` contains a lot of duplicated code around checking if certain audit events are there. 

The `testAudit*` functions combine both actions for the tests and the assertions for the audit events. Decoupling those two things will enable us to move the "actions" code higher of the stack and unify the audit events evaluation code.

#### Why is this needed:

Unifying this test will make it shorter and will also make some of the functions more reusable. Less code = easier maintenance.

**Comment by neolit123** [comment]
please clarify in the description which audit_test.go this is about, since this repository has multiple.

i'm going to assume it's https://github.com/kubernetes/kubernetes/blob/08eaea4590821ab099551e334bfc0e0b2ebee348/staging/src/k8s.io/apiserver/pkg/endpoints/filters/audit_test.go

/sig api-machinery

**Comment by slaskawi** [comment]
@neolit123 It's `test/integration/controlplane/audit_test.go` but I believe the API Machinery SIG works there as well.
