### ISSUE TITLE
NotReady state. Any pointers

### ISSUE THREAD

**Issue by svennela** [kubernetes/kubernetes#10486]
Hi ,

finally after installing on 2 ubuntu machines. When i run kubectl get nodes i am getting below output. Any pointers? how to restart master or minion nodes?

10.10.103.162   kubernetes.io/hostname=10.10.103.162   NotReady

10.10.103.223   kubernetes.io/hostname=10.10.103.223   NotReady

**Comment by uruddarraju** [comment]
Can you please do `journalctl -u kubelet` on the minion to check for any issues with kubelet trying to update its status on the apiserver ?

**Comment by svennela** [comment]
Hi Uday,

I am not able to find journalctl on my minion. Do i need to install ?

**Comment by uruddarraju** [comment]
What is the cloud provider you are trying to use ?

**Comment by svennela** [comment]
I am using 2 nodes ubuntu.

**Comment by goltermann** [comment]
We’re going through old support issues and asking everyone to direct your questions to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes). 

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases. 

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.
