### ISSUE TITLE
flowschemas resource is currently skipped by TestApplyResetFields test.

### ISSUE THREAD

**Issue by tkashem** [kubernetes/kubernetes#104842]
#### What happened:
`flowschemas` resource is currently skipped by `TestApplyResetFields` test.

https://github.com/kubernetes/kubernetes/blob/master/test/integration/apiserver/apply/reset_fields_test.go#L70-L74
```
var resetFieldsSkippedResources = map[string]struct{}{
	// TODO: flowschemas is flaking,
	// possible bug in the flowschemas controller.
	"flowschemas": {},
}
```

When it flakes, it fails with the following error
```
 reset_fields_test.go:288: expected conflict, got error <nil>
```

this is the test result:
```
--- FAIL: TestApplyResetFields (5.94s)
    --- FAIL: TestApplyResetFields/flowcontrol.apiserver.k8s.io/v1beta2,_Resource=flowschemas (0.05s)
    --- PASS: TestApplyResetFields/flowcontrol.apiserver.k8s.io/v1beta2,_Resource=prioritylevelconfigurations (0.01s)
    --- FAIL: TestApplyResetFields/flowcontrol.apiserver.k8s.io/v1beta1,_Resource=flowschemas (0.01s)
    --- PASS: TestApplyResetFields/flowcontrol.apiserver.k8s.io/v1beta1,_Resource=prioritylevelconfigurations (0.01s)
    --- PASS: TestApplyResetFields/flowcontrol.apiserver.k8s.io/v1alpha1,_Resource=flowschemas (0.01s)
    --- PASS: TestApplyResetFields/flowcontrol.apiserver.k8s.io/v1alpha1,_Resource=prioritylevelconfigurations (0.01s)
```

#### What you expected to happen:

We need to identify the root case of why it flakes and fix it. "flowschemas" being skipped means that we may not catch any errors related to field resetting when we add a new version of the API.

#### How to reproduce it (as minimally and precisely as possible):
- remove "flowschemas" from `resetFieldsSkippedResources`
- go test -v -count=1 ./test/integration/apiserver/apply -run="TestApplyResetFields/flowcontrol.apiserver.k8s.io"

run multiple times to see the flake

#### Environment:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by tkashem** [comment]
/sig api-machinery

cc @wojtek-t @MikeSpreitzer

**Comment by fedebongio** [comment]
@tkashem is someone going to look at this one or you need help from the broader sig? (we saw this one during triage)

**Comment by tkashem** [comment]
@fedebongio I have limited knowledge on how the test `TestApplyResetFields` works. Yes, i would appreciate some help from the broader sig.

**Comment by lavalamp** [comment]
Judging from the comment it sounds like whoever wrote that believed that the APF controller was interfering with the test (probably by writing back a status). The fix might be to disable that controller for that test.

**Comment by MikeSpreitzer** [comment]
Bug #107535 might explain this.

**Comment by MikeSpreitzer** [comment]
Current understanding is as follows.  The annotations needed to guide strategic merge patch are missing from the Condition slice field in FlowSchemaStatus and in PriorityLevelConfigurationStatus.  The APF config-consuming controller was written, however, with the mistaken understanding that a strategic merge patch of Status with one Condition will only affect that member of the Condition slice.  The truth is that currently such a patch will replace the entire slice.  That is why FlowSchema fails TestApplyResetFields and is specifically excluded.

#107456 will change that controller to use server-side apply instead of strategic merge patch, so that indeed only the one intended member of the Condition slice is affected.

#107574 calls for adding the missing annotations in the API.  This is too disruptive to do to an existing version and so will have to be done as we create the next version of the API.

**Comment by tkashem** [comment]
/reopen

https://github.com/kubernetes/kubernetes/pull/107456 was reverted due to https://github.com/kubernetes/kubernetes/issues/107727.

**Comment by tkashem** [comment]
https://storage.googleapis.com/k8s-triage/index.html?date=2022-10-01&job=unit&test=TestApplyResetFields yields zero result
