### ISSUE TITLE
kubectl get pod appear NAME pod

### ISSUE THREAD

**Issue by ylmcr7** [kubernetes/kubernetes#104864]
i use kubectl to get pod list,then appear a pod name is NAME
![image](https://user-images.githubusercontent.com/63889450/132665080-b380ec13-472e-4179-b255-d1b703f84de5.png)

i want to deal with,but i dont know   
![image](https://user-images.githubusercontent.com/63889450/132665331-cfa67fc5-1ebc-480b-8b10-031da60fbf70.png)

**Comment by MadhavJivrajani** [comment]
/sig cli
/priority awaiting-more-evidence
@ylmcr7 it'd be helpful if you could provide more context and steps to help reproduce this.

**Comment by ylmcr7** [comment]
`$ kubectl get pod -n sys
NAME                                           READY   STATUS    RESTARTS   AGE
aaa-pages-667c7c8676-mvcdz                1/1     Running   0          175d
aaa-pages-667c7c8676-vczs6                1/1     Running   0          175d
NAME                                           READY   STATUS    RESTARTS   AGE
bbb-cargo-5d99ff89f4-wvgtz                     1/1     Running   0          190d
bbb-channel-gw-567b64769f-cpscx                1/1     Running   0          56d
`

**Comment by pacoxu** [comment]
Would you try `kubectl --v=6 get pod ` or even `kubectl --v=9 get pod` to get debug level logs of kubectl to know what happened?

A guess would be there are two types with same name `pod` in you cluster(which have different api-groups, you can check with `kubectl  api-resources  |grep pods`). Because this is similar with that kubectl get two different resources together like `kubectl get pod,secret`.

**Comment by brianpursley** [comment]
@ylmc7 more information please.  At a minimum can you provide the output of `kubectl version`

It is strange that you get two different tables.  Do you have kubectl aliased by chance?
