### ISSUE TITLE
The pod of another node cannot be accessed

### ISSUE THREAD

**Issue by slomo28** [kubernetes/kubernetes#104804]
#### What happened:
An Nginx service was created in the cluster. The pod was successfully scheduled to node1, but could not be accessed on the master node using curl+ virtual IP
#### Environment:
- Kubernetes version (use `kubectl version`):1.19.3
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):ubuntu21.4
- Kernel (e.g. `uname -a`):
- Install tools:kubeadm
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by EricWvi** [comment]
I have some suggestions:
- describe the service and check the endpoints carefully. Is the endpoints in place?
- get the service with output in yaml. Is the targetPort exactly the same as the pod's containerPort?

**Comment by slomo28** [comment]
> I have some suggestions:
> 
> * describe the service and check the endpoints carefully. Is the endpoints in place?
> * get the service with output in yaml. Is the targetPort exactly the same as the pod's containerPort?

Thank you very much for your advice!
I have checked the address and port and there is no problem, I suspect that the internal network of the cluster is disconnected. I am a three-node cluster built by virtual machine, and I found that the nginx on Node1 cannot be pinged on the master. I just learned K8S and don't know how to debug it.

**Comment by EricWvi** [comment]
The service can't be pinged, thus the name Virtual IP. There are rules configed in iptables by kube-proxy. The packet headers will be re-written so that the request is redirected to a particular Pod. The communication is based on TCP/UDP. Unfortunately, ping is based on ICMP.

The debugging concerned about network is kind of complex and time-consuming sometimes. There can be errors during every step through the chain. One thing I want to stress once more is that the targetPort of a service is the same as the port of the service by default. If you set a different service port from the container port of a pod, the targetPort will also be different from the container port, and the access will fail.

As for debugging, you can bring up a debugging pod, access the nginx service within the pod and play it by ear.
If all configs are right, checking the network interfaces and route tables may help, but may to a limited extent.
Since the lack of information, I run out of ideas :-)

**Comment by slomo28** [comment]
> The service can't be pinged, thus the name Virtual IP. There are rules configed in iptables by kube-proxy. The packet headers will be re-written so that the request is redirected to a particular Pod. The communication is based on TCP/UDP. Unfortunately, ping is based on ICMP.
> 
> The debugging concerned about network is kind of complex and time-consuming sometimes. There can be errors during every step through the chain. One thing I want to stress once more is that the targetPort of a service is the same as the port of the service by default. If you set a different service port from the container port of a pod, the targetPort will also be different from the container port, and the access will fail.
> 
> As for debugging, you can bring up a debugging pod, access the nginx service within the pod and play it by ear.
> If all configs are right, checking the network interfaces and route tables may help, but may to a limited extent.
> Since the lack of information, I run out of ideas :-)

Thank you for your patient reply. I will try to check again according to your idea.

**Comment by neolit123** [comment]
discussions like this are better suited for the support channels:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

i'm going to close this, but continue the discussion here if you like.

/close
