### ISSUE TITLE
anti-windup mechanism in queueset is too aggressive

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/kubernetes#104922]
#### What happened:
I looked into why TestDifferentWidth in `queueset_test.go` needs surprisingly wide tolerance for divergence from the ideal result.  One reason is the anti-windup mechanism at https://github.com/kubernetes/kubernetes/blob/b47f8263e18c7b13dba33fba23187e5e0477cdbd/staging/src/k8s.io/apiserver/pkg/util/flowcontrol/fairqueuing/queueset/queueset.go#L726-L742 is canceling the "credit" that the queues for the width=1 flow get from having requests wait in the queue.  For example, here is a bit of verbose logging from around the time the first round of requests finish and the second start (I am using a tweaked scenario, hoping a wider one will come closer to ideal --- it did not):
```
I0910 17:15:33.397998   39294 queueset.go:697] "Considering queue to dispatch" queueSet="TestDifferentWidths" queue=70 finishR=0.006000064296031746
I0910 17:15:33.398044   39294 queueset.go:697] "Considering queue to dispatch" queueSet="TestDifferentWidths" queue=1 finishR=1.003
I0910 17:15:33.398084   39294 queueset.go:697] "Considering queue to dispatch" queueSet="TestDifferentWidths" queue=2 finishR=2.006000002
I0910 17:15:33.398127   39294 queueset.go:697] "Considering queue to dispatch" queueSet="TestDifferentWidths" queue=5 finishR=0.0030000732960317462
I0910 17:15:33.398167   39294 queueset.go:697] "Considering queue to dispatch" queueSet="TestDifferentWidths" queue=10 finishR=0.0090000155
I0910 17:15:33.398209   39294 queueset.go:697] "Considering queue to dispatch" queueSet="TestDifferentWidths" queue=19 finishR=0.012000018166666668
I0910 17:15:33.398247   39294 queueset.go:697] "Considering queue to dispatch" queueSet="TestDifferentWidths" queue=29 finishR=0.006000050823809524
I0910 17:15:33.398284   39294 queueset.go:697] "Considering queue to dispatch" queueSet="TestDifferentWidths" queue=33 finishR=0.012000034466666667
I0910 17:15:33.398327   39294 queueset.go:697] "Considering queue to dispatch" queueSet="TestDifferentWidths" queue=35 finishR=0.003000083296031746
I0910 17:15:33.398368   39294 queueset.go:697] "Considering queue to dispatch" queueSet="TestDifferentWidths" queue=49 finishR=0.0060000479666666665
I0910 17:15:33.398410   39294 queueset.go:697] "Considering queue to dispatch" queueSet="TestDifferentWidths" queue=52 finishR=0.009000031666666667
I0910 17:15:33.398449   39294 queueset.go:697] "Considering queue to dispatch" queueSet="TestDifferentWidths" queue=61 finishR=0.8393333616293651
I0910 17:15:33.398499   39294 queueset.go:641] QS(TestDifferentWidths) at r=2021-09-10 17:15:34.357788002 v=0.833333363ss: dispatching request "TestDifferentWidths" []int{0, 5, 0} work {1 0s} from queue 5 with start R 0.833333363ss, queue will have 5 waiting & 1 requests occupying 1 seats, set will have 9 seats occupied
```

The "considering" line showed that queue 5 had quite a small value of `virtualStart`, but the "dispatching" line shows that it has jumped by about 0.83ss (which is most of the roughly 1ss credit it got from sitting out the first round).

#### Environment:
- Kubernetes version (use `kubectl version`): commit 59d319ec06bb33289a87036418b4a61ed3bb215f with TestDifferentWidths tweaked to have more concurrency
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by MikeSpreitzer** [comment]
@kubernetes/sig-api-machinery-bugs 
/cc @yue9944882 
/cc @tkashem 
/cc @wojtek-t 
@deads2k 
@lavalamp

**Comment by wojtek-t** [comment]
I started wondering what would happen if we would remove that completely:
- basically the virtual time of a particular queue can go arbitrarily into past, as long as there is always something in the queue (when at any point in time we empty the queue, the next incoming request will bring it back to "now")
- the queue may accumulate "credit" only if there is no request being currently processed from the queue (otherwise it's time is effectively advancing by at least its latency, potentially more for width>1)
- when choosing which queue to put a request to, we effectively don't use that time at all - we're only looking at the "number of waiting seats": https://github.com/kubernetes/kubernetes/blob/dd2d12f6dc0e654c15d5db57a5f9f6ba61192726/staging/src/k8s.io/apiserver/pkg/util/flowcontrol/fairqueuing/queueset/queueset.go#L473


Given the first two points we definitely need some anti-windup mechanism, but I'm wondering what if instead of what we have now, (maxing with set virtual time), we would do:
`queue_virtual_time = max(queue_virtual_time, request_income_time)`

That is theoretically incorrect (even units don't match), but if we would change "request_income_time" to "virtual_time at the moment of request income" that makes more sense.
And that introduces some anti-windup protection.

@MikeSpreitzer - thoughts?

**Comment by MikeSpreitzer** [comment]
@wojtek-t : yes, that sounds plausible.  I will give it a try.

**Comment by tkashem** [comment]
do we actually need an anti wind-up mechanism here? 

from dispatch - https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/util/flowcontrol/fairqueuing/queueset/queueset.go#L696
```
currentVirtualFinish := queue.virtualStart + qs.estimatedServiceSeconds*float64(oldestWaiting.Seats())
```

so if `virtualStart` goes back into past, that queue is more likely to be selected for dispatch, right?

**Comment by wojtek-t** [comment]
> so if virtualStart goes back into past, that queue is more likely to be selected for dispatch, right?

True, but if there are more requests than we're able to process, then each queue would be accumulating "credit" over time.

**Comment by wojtek-t** [comment]
IN other words - I think we need some windup protection, but I have a feeling (no hard proof) that what i proposed above should be enough.

**Comment by MikeSpreitzer** [comment]
Here is a visualization of the existing queueset TestWindup:

[windup.pdf](https://github.com/kubernetes/kubernetes/files/7193590/windup.pdf)
