### ISSUE TITLE
Remove DynamicKubeletConfig from node tests

### ISSUE THREAD

**Issue by ehashman** [kubernetes/kubernetes#105047]
/kind cleanup
/sig node
/area test

Deprecation issue: https://github.com/kubernetes/enhancements/issues/281

Currently, our e2e tests have a dependency on the deprecated DynamicKubeletConfiguration feature. At minimum, we use the feature to set the KubeletConfiguration, and we check metrics from it (e.g. https://github.com/kubernetes/kubernetes/issues/104041).

We've also seen that the use of this feature in our serial tests is unreliable. Sometimes the kubelet fails to restart, which causes the tests to crash/fail: https://github.com/kubernetes/kubernetes/issues/104038

The node e2e test suite was written before the component config APIs existed, and so right now the only way to configure a kubelet for tests is with extra command line flags, passed through our current test harness. The only way it's possible to set KubeletConfiguration values that don't have a corresponding command line flag is with a test code change using the DynamicKubeletConfiguration feature. It would be much better to refactor to just support a custom KubeletConfiguration provided at launch time.

Suggested path forward:

- [ ] Update our test runner such that we can provide a KubeletConfiguration file, rather than configuring jobs with command-line flags
- [ ] Determine some mechanism to either update the config and restart the kubelet during test runs, or guidelines for how to manage custom KubeletConfigs in test jobs that need to exercise features outside of the default set
- [ ] Remove all use of the DynamicKubeletConfiguration from e2e tests

/milestone v1.23
/priority important-soon

/assign @endocrimes 
/cc @SergeyKanzhelev

**Comment by ehashman** [comment]
/triage accepted
discussed in 2021-09-15 SIG Node CI meeting: https://docs.google.com/document/d/1fb-ugvgdSVIkkuJ388_nhp2pBTy_4HEVg5848Xy7n5U/edit#heading=h.o9f87erxdnxm

**Comment by yuzhiquan** [comment]
Can ci ignore `[Feature:DynamicKubeletConfig]` test failing for now, just make some pr which not relevant to these can merge first.

**Comment by kerthcet** [comment]
> Can ci ignore `[Feature:DynamicKubeletConfig]` test failing for now, just make some pr which not relevant to these can merge first.

if you want to skip the test, `/skip ***` may help.

**Comment by ehashman** [comment]
The tests aren't currently failing so they don't need to be ignored: https://testgrid.k8s.io/sig-node-kubelet#node-kubelet-serial

The issue is that if the kubelet is restarted and never comes back up, the test run doesn't complete and so we don't get results.

**Comment by swatisehgal** [comment]
This is affecting our PR: https://github.com/kubernetes/kubernetes/pull/97415

/cc @AlexeyPerevalov

**Comment by yuzhiquan** [comment]
> The tests aren't currently failing so they don't need to be ignored: https://testgrid.k8s.io/sig-node-kubelet#node-kubelet-serial
> 
> The issue is that if the kubelet is restarted and never comes back up, the test run doesn't complete and so we don't get results.

@ehashman https://github.com/kubernetes/kubernetes/pull/102162 is failing on pull-kubernetes-node-kubelet-serial, but in this pr does not relevant to these test case, would you like to help me on this?

**Comment by endocrimes** [comment]
I've been on PTO for the last couple of weeks but started looking at this again today and audited our current set of tests and how they exercise dkc to refresh my brain, and double check the extra modes that test_e2e can run in.

Unfortunately, without breaking tests into sub-suites and then merging test results, it doesn't seem that we can avoid replacing dkc in some way (rather than providing multiple static configurations). There are a fair number of tests that replace kubelet configuration multiple times during the duration of a single "test", especially within the performance tests, which would quickly become difficult to manage.

This means we're going to need to build a mechanism for replacing configuration at runtime (which... is amusing). I'm going to avoid diving deeper on that today however as I'm prioritising cleaning up the launcher and existing uses of dynamic config to simplify porting to a replacement mechanism rather than doing a single large diff.

---

Figuring out the right approach for managing these is initially a little bit tricky because there are a few different modes that `node_e2e` can run in, and in those modes, services interact in slightly different ways. For future readers of this thread, we don't seem to need to handle the non standard ways that node_e2e can run, at least initially.

#### Conformance tests

No tests tagged `NodeConformance` use `tempSetCurrentKubeletConfig` or `setKubeletConfiguration', which is the 'least known to me' mode we support.

```
$ rg -i '(temp)?set(current)?kubeletconfig' | grep .go | cut -f 1 -d ':' | uniq | sort > dkk-files
$ rg -i 'NodeConformance' | grep .go | cut -f 1 -d ':' | uniq | sort > node-conformance
$ cat ./dkk-files
container_log_rotation_test.go
cpu_manager_test.go
density_test.go
eviction_test.go
memory_manager_test.go
node_container_manager_test.go
node_perf_test.go
node_shutdown_linux_test.go
pids_test.go
podresources_test.go
quota_lsci_test.go
system_node_critical_test.go
topology_manager_test.go
util.go

$ cat ./node-conformance
e2e_node_suite_test.go
gcp/gke_environment_test.go
log_path_test.go
mirror_pod_grace_period_test.go
mirror_pod_test.go
pods_container_manager_test.go
runtime_conformance_test.go
services/services.go
summary_test.go
volume_manager_test.go
```

#### cadvisor tests

Doesn't seem to run any tests from k/k, instead is a harness to manage orchestrating running https://github.com/google/cadvisor/blob/master/build/integration.sh

**Comment by neolit123** [comment]
> This means we're going to need to build a mechanism for replacing
configuration at runtime (which... is amusing).

I find it surprising that so many tests are bound to this feature. The now
required kubelet restart might cause problems.

Porting to the new mechanism as a first attempt makes sense. At that point
if any tests are not happy about the restart, they should be rewritten to
not change config at runtime...and/or fix discovered bugs.

**Comment by endocrimes** [comment]
@neolit123 I was surprised by how many were using it too tbh - Fortunately we should have a bit more control in the harness doing it manually than we did with dynamic config (or at least more obvious debugging points).

I'm assuming that it's going to highlight a couple of currently flaky bugs that we'll need to take care of pretty quickly.

**Comment by endocrimes** [comment]
Dynamic Kubelet Config is no longer used in Node tests 🎉  (thanks @cynepco3hahue https://github.com/kubernetes/kubernetes/pull/104153). 

We probably need some contrib guidance on when to use the DKC replacement vs a new job with a new KubeletConfiguration, but I think that should be a new issue in k8s/community.

**Comment by varshaprasad96** [comment]
Hello (@ehashman @endocrimes @neolit123) :)
k8s 1.23 bug triage here 👋,
Just wanted to follow up and check if this issue is on track for 1.23. Would [kubernetes/test-infra#24284](https://github.com/kubernetes/test-infra/pull/24284) close this issue, or is there any other action needed since there is no particular PR linked for this issue?

**Comment by endocrimes** [comment]
@varshaprasad96 I think kubernetes/test-infra#24284 plus #106263 resolve this.

There's some follow up work around feature enablement and testing standards, but I think they're separate from the core of what we needed here.

**Comment by varshaprasad96** [comment]
Hi @endocrimes 
Thanks for the update! Looks like both the PRs (https://github.com/kubernetes/test-infra/pull/24284 and https://github.com/kubernetes/kubernetes/pull/106263) are merged. Can we close this issue?

**Comment by SergeyKanzhelev** [comment]
/close

the only mentions of DynamicKubeletConfig in test-infra are now "skip" lists
