### ISSUE TITLE
architecture-aware placement of pods

### ISSUE THREAD

**Issue by chendave** [kubernetes/kubernetes#105321]
#### What would you like to be added:
Actually, this was raised in the mailing list, and I did some investigation recently and found this is an area we might improve during scheduling.

#### Why is this needed:
The user case is that in a hybrid cluster, saying a cluster with some nodes are x86_64 while others are arm64. A pod with the image which only capable to run on the x86_64 nodes might be scheduled to arm64 nodes, obviously, the Pod will fail to start.

As node will be labeled with a `beta.kubernetes.io/arch` by default, we can define some node affinity rules to filter the matched nodes.
```
kubectl get node --show-labels
ip-10-253-11-33   Ready                      <none>                 82d   v1.21.2   beta.kubernetes.io/arch=arm64...kubernetes.io/os=linux,type=node33
```

But this requires us to understand which kind of architecture this images are built for and define the affinity rules accordingly for each of the pod, this doesn't seems like effective enough.

So, I think if we could do something more to alleviate the problem a little bit?  This doc show that [multi-architecture-images-with-image-indexes](https://kubernetes.io/docs/concepts/containers/images/#multi-architecture-images-with-image-indexes) images with a suffix -$(ARCH) is recommended, we could build a affinity rule based on the suffix on the fly and filter the only matched nodes, this is an enforced rule and no need to defined the affinity rule for each of the pod in advance.

Only my initial thoughts on this, hopefully, I could get some ideas from your guys, thanks!

@Huang-Wei @ahg-g @alculquicondor @damemi

**Comment by alculquicondor** [comment]
Is the practice of naming images like that widespread enough? We do it for the k8s official images, but I don't think there are many guarantees that we will find it in the wild.

I think we should leave the control to the user. Or to cluster administrators via webhooks.

**Comment by Huang-Wei** [comment]
AFAIK, the image index is _optional_ for image providers - from [OCI spec](https://github.com/opencontainers/image-spec/blob/main/image-index.md):

> The image index is a higher-level manifest which points to specific image manifests, ideal for one or more platforms. While the use of an image index is OPTIONAL for image providers, image consumers SHOULD be prepared to process them.

But, I'm fine with starting this as an alpha feature, to fit the users that already stick to standard OCI spec, and fall back to current logic otherwise.

I had an offline talk with one of the OCI maintainers @mikebrow. The technical obstacles upfront are:

1. given an image URL, how can I know which architectures it supports? and how to make it performant? (as it involves network overhead IMO)
2. are the architectures discovered from the image manifest aligned with the kubelet and container runtime configs?

Regarding 1, it seems you have to issue a HTTP call to verify it. But it seems not all image providers make this always accessible:

```shell
root@wei-dev:~# docker manifest inspect kindest/node:v1.22.1
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
   "manifests": [
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 743,
         "digest": "sha256:100b3558428386d1372591f8d62add85b900538d94db8e455b66ebaf05a3ca3a",
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 742,
         "digest": "sha256:7f539328bebb0483e4a91ae48fcd067619cd9fa28f4bf3b3d624858e30571a8e",
         "platform": {
            "architecture": "arm64",
            "os": "linux"
         }
      }
   ]
}

root@wei-dev:~# docker manifest inspect k8s.gcr.io/scheduler-plugins/kube-scheduler:v0.20.10
Get https://k8s.gcr.io/v2/scheduler-plugins/kube-scheduler/manifests/v0.20.10: unauthorized: You don't have the needed permissions to perform this operation, and you may have invalid credentials. To authenticate your request, follow the steps in: https://cloud.google.com/container-registry/docs/advanced-authentication
```

(BTW: Phil's tool [manifest-tool](https://github.com/estesp/manifest-tool) can help in a programmatic way)

Regarding 2, the only exposed info is the label `kubernetes.io/arch`. But I'm not sure it's canonical enough and if there is any inconsistency among node/kubelet/container runtime.

**Comment by mikebrow** [comment]
some hopefully useful notes:

* vm type runtimes may support additional guest platforms outside the node host environment
* container runtimes may be configured to modify a registry domain to point to a set of mirrors, including the ability to not use original registry domain
* kube image pull policies include never pull, pull if not present, and pull always - depending on the current cache of container images/platforms you may not be able to / allowed to pull the manifests/blobs needed 
* kubelet has an ensure image process that is executed for each pod to ensure the container images are present, it uses the aforementioned policies and requests to the container runtime image service 
* in the ensure/pull process authentication is often required, auth can be done via container runtime configuration and/or via kube image pull secrets
* the example shown by Wei reminds me that any tooling provided needs to work with both "application/vnd.docker.distribution.manifest.list.v2+json" and "application/vnd.oci.image.index.v1+json" https://github.com/opencontainers/image-spec/blob/main/image-index.md#example-image-index
* the runtime handler passed to the cri apis (right now just runtime services receives the handler, it is not passed in image services yet, can be presumed for pull image because we have the pod config and pod runtime handler, but for image status/list images etc. cri apis we don't know the context of the requests)... when passed this runtime handler will or should be used by the container runtime to pull/filter by selected platform see kep discussions here:  https://github.com/kubernetes/enhancements/pull/1302/files those discussions need a follow up to support "this" scheduler case and also to support confidential computing cases.*

**Comment by Huang-Wei** [comment]
Back to the issue, another angle is to leverage [RuntimeClass]. For example, if an image can only run on Arm, you can create a RuntimeClass called "arm", and associate the [scheduling primitives] to it. Next prepare a pod with "arm" as the `.spec.runtimeClassName`. Then the pod will be applied with additional nodeSelector / tolerations (on admission phase) so as to be scheduled to the proper node. I guess it can resolve the issue to some extent.

[RuntimeClass]: https://kubernetes.io/docs/concepts/containers/runtime-class/
[scheduling primitives]: https://kubernetes.io/docs/concepts/containers/runtime-class/#scheduling

**Comment by chendave** [comment]
> We do it for the k8s official images, but I don't think there are many guarantees that we will find it in the wild.

Agreed.

> I think we should leave the control to the user. Or to cluster administrators via webhooks.

Leave this to user is bad, as what's the original author said it require us to analysis the image beforehand and take actions such as webhook admission,  or attach affinity rules per pod level.

**Comment by chendave** [comment]
> another angle is to leverage RuntimeClass

`RuntimeClass` per my understanding is primarily a feature for gluing pod with the different runtimes, it doesn't sound like a good choice for this issue even it might work as node affinity.

The ideal solution is no pod level's modification, but kubernetes is clear enough to schedule to pod to the desired nodes. 
As we lack the proper API, or somewhere we can read directly on which `arch` the image is built for, let's pile it up, I will follow up on this issue if I could find something new.

Thanks for the inputs!

**Comment by alculquicondor** [comment]
How about starting with an out-of-tree webhook that uses the image index to add the node selector? Or perhaps it should only be limited to image name suffix?

**Comment by BenTheElder** [comment]
> This doc show that [multi-architecture-images-with-image-indexes](https://kubernetes.io/docs/concepts/containers/images/#multi-architecture-images-with-image-indexes) images with a suffix -$(ARCH) is recommended,

I don't think that's what it shows at all. It shows that we need this for backwards compatibility. I would argue this note is completely out of place in this doc as it really only pertains to our own images. Wherever possible tooling is using the multi-arch manifest names instead (e.g. kubeadm), IMHO this is by far the most robust solution to architecture placement (just let the node pull the relevant version from a manifest).

> Leave this to user is bad, as what's the original author said it require us to analysis the image beforehand and take actions such as webhook admission, or attach affinity rules per pod level.



If you have some more specialized workload that needs a specific architecture and does not support multi-architecture, the node selector seems reasonable. I don't think anything built in can assume anything about image names and there's no way at scheduling time to know the actual image metadata currently. I don't think it would be acceptable to put that in the hot path ...

**Comment by ahg-g** [comment]
> If you have some more specialized workload that needs a specific architecture and does not support multi-architecture, the node selector seems reasonable. I don't think anything built in can assume anything about image names and there's no way at scheduling time to know the actual image metadata currently. I don't think it would be acceptable to put that in the hot path ...

+1; I don't think the scheduler can make a decision, and it is not good enough to simply make a guess.

**Comment by Huang-Wei** [comment]
> I don't think it would be acceptable to put that in the hot path ...

Yes, we definitely don't want to put it on the hot path. That's the point of "make it performant" I mentioned earlier.

Also using the arch postfix `suffix -$(ARCH)` doesn't sound like a feasible option. It must be discovered from an authoritative OCI API call alike.

**Comment by BenTheElder** [comment]
Users today can expect to authenticate to the registry using credentials only present on the destination node (supply credentials to CRI or docker or kubelet directly), so I don't think the scheduler or a webhook even can depend on access to the registry, performant or otherwise without special user support (supplying these credentials, which may also be done by kubelet executing a credential helper so ...).

I don't think you can do this without completely changing the expectations around registry authentication.

**Comment by jonyhy96** [comment]
This [kep](https://github.com/kubernetes/enhancements/issues/2802) introduced `os` field to pod spec, but it doens't contains the `arch` info.Maybe we can change that `os` field to `platform` or add an `arch` filed, and add a plugin to framework to verify that field first  with [node status](https://github.com/kubernetes/kubernetes/pull/104613/files).

**Comment by chendave** [comment]
well, thanks for that information, will take a look! @jonyhy96

**Comment by alculquicondor** [comment]
It looks like they implemented what we concluded is not a good approach.
