### ISSUE TITLE
Volume manager re-conciler takes too long to reconcile under high pressure and large number of subpaths

### ISSUE THREAD

**Issue by manugupt1** [kubernetes/kubernetes#105642]
### What happened?

We have a situation where we are launching a lot of short-lived pods on a single node on EKS1.20 as a cronjob. Some volumes can take upto 2 hours to reconcile and unmount. Each pod has 3 volumes and 100 subPath

1. EFS volume
2. emptyDir 
3.  config map

Below logs show this
```
Oct 12 17:59:20 ip-192-168-58-97.ec2.internal kubelet[17955]: I1012 17:59:20.422730   17955 reconciler.go:193] Starting operationExecutor.UnmountVolume for volume "canikicka" [manu](UniqueName: "kubernetes.io/configmap/184df45d-548d-4012-8906-004779c9b22a-canikicka") pod "184df45d-548d-4012-8906-004779c9b22a" (UID: "184df45d-548d-4012-8906-004779c9b22a")
Oct 12 20:49:28 ip-192-168-58-97.ec2.internal kubelet[17955]: E1012 20:49:28.463764   17955 nestedpendingoperations.go:177] [manu] backOffErr: Failed to create operation with name "{volumeName:kubernetes.io/configmap/184df45d-548d-4012-8906-004779c9b22a-canikicka podName:184df45d-548d-4012-8906-004779c9b22a nodeName:}". An operation with that name failed at 2021-10-12 20:47:41.98837091 +0000 UTC m=+12608.434290319. No retries permitted until 2021-10-12 20:49:43.98837091 +0000 UTC m=+12730.434290319 (2m2s). Last error: "error cleaning subPath mounts for volume \"canikicka\" [manu](UniqueName: \"kubernetes.io/configmap/184df45d-548d-4012-8906-004779c9b22a-canikicka\") pod \"184df45d-548d-4012-8906-004779c9b22a\" (UID: \"184df45d-548d-4012-8906-004779c9b22a\") : error processing /var/lib/kubelet/pods/184df45d-548d-4012-8906-004779c9b22a/volume-subpaths/canikicka/init2: error cleaning subpath mount /var/lib/kubelet/pods/184df45d-548d-4012-8906-004779c9b22a/volume-subpaths/canikicka/init2/4: could not get consistent content of /proc/mounts after 3 attempts".
```

The above volume takes around 2 hours before it stops getting an unmount volume error.

### What did you expect to happen?

I was not expecting the reconciler to take 2 hours.

### How can we reproduce it (as minimally and precisely as possible)?

Same as https://github.com/kubernetes/kubernetes/issues/104976

### Anything else we need to know?

1. I tried the same with https://github.com/kubernetes/kubernetes/commit/82cfe9f14f8fb445d682ce2774ea44ce54885e81 ; however it is still not sufficient in some cases.

2. Since Unmount operations can happen concurrently on the code, they might change /proc/mounts very fast which which can throw back the errors to the volumemanager reconciler really fast while reading from /proc/mounts. is it possible to optimize subPath volumes during where a specif check for a given subpath; if a mount point is consistently present (2 consecutive reads) match for a mount point.
For eg
```
/proc/mounts has

Read 1
M1
M2
M3

Read 2
M2
M3 
M4
```

A consistentRead for M2, M3 will succeed while consistentRead for M1 or M4 will fail on the Unmount subPath volume path.

Thanks

cc @jsafrane @jingxu97 @thockin 

/sig storage

### Kubernetes version

<details>

1.20
</details>

### Cloud provider

<details>
AWS
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

[ec2-user@ip-192-168-58-97 ~]$ cat /etc/os-release
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
[ec2-user@ip-192-168-58-97 ~]$

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by wongma7** [comment]
@jsafrane it's not needed to read /proc/mounts before unmount at all because `umount` already does it for us (assuming my reading of their code is correct...) [1]. And we can even pass it -q [2] to suppress the "not mounted" error so we could basically treat `umount -q` as an idempotent operation to avoid reading mount table ourselves. And this works independent of the mount helper, i.e. whether we call umount on an NFS dir or XFS dir, this mtab check happens first. I'll submit a patch to illustrate this and link it here later.

[1] https://github.com/util-linux/util-linux/blob/57202f5713afa2af20ffbb6ab5331481d0396f8d/libmount/src/context_umount.c#L948
[2] https://github.com/util-linux/util-linux/blob/441f9b9303d015f1777aec7168807d58feacca31/sys-utils/umount.c#L106

/reopen
/remove-lifecycle rotten

**Comment by wongma7** [comment]
I repeated the test you guys did in #104976 in a 1.20 cluster recently and observed indeed there is improvement to be made in operation_generator as well. Right now we are incorrectly classifying EFS as device mountable and indexing EFS operations only by volName forcing them to happen serially. Patch https://github.com/kubernetes/kubernetes/pull/109011 treats EFS as NOT device mountable so that operation_generator indexes its operations by volName+podName and lets them happen in parallel.

Detailed findings: 1 Node, 100 cronjobs with 1minute period, each with 100 EFS subpaths , 1 EFS volume:

1. If I don't change kubelet, then mount table seems to grow eventually to like 50k after the CronJobs are left alone for a couple hours. Then the Node is slow to respond to commands and Pods seem not to become Running anymore so the Node is basically useless at this point. The Node had 16 vCPUs and 64 GB if that matters. This mount table growth kind of makes sense once you consider that mount will never fail with the consistent read error because it always no-ops here https://github.com/kubernetes/kubernetes/blob/1c526a536f83ca7a0dd77f455f85c336bca7e801/pkg/volume/util/subpath/subpath_linux.go#L103 since bindPathTarget never exists at that point yet, but umount frequently fails with the consistent read error, so rate of mounts > unmounts
2. If I change kubelet  to skip the consistent read during subpath cleanup to speed up Unmounts, the mount table seems bounded to about 1k even after left alone for ~an hour and some CronJobs' Pods still seem to get "stuck" ContainerCreating for minutes at a time. This indicates to me that even if Unmount is unbottlenecked now something else is bottlenecking, logically it could be Mount so I try patch #109011 next...
```
date && mount | grep efs.us | wc -l
Fri Mar 25 22:51:41 UTC 2022
871
date && mount | grep efs.us | wc -l
Fri Mar 25 22:53:11 UTC 2022
932
```
```
cron-3-kmfmt * * * * * False 1 3m13s 41m
cron-3-kqfsg * * * * * False 1 3m13s 42m
cron-3-l7p8z * * * * * False 1 9m13s 41m
```
3. If I change kubelet  to skip the  consistent read during subpath cleanup to speed up Unmounts AND patch it with https://github.com/kubernetes/kubernetes/pull/109011 to speed up Mounts, then, with 100 cronjobs each with 100 EFS subpaths, the mount table seems to be bounded by like 20k which kind of makes sense if you imagine that at any given time there is a max of 100\*100 pod mounts for the incoming jobs + 100\*100 pod mounts for the outgoing jobs with rate of mounts == unmounts.

HOWEVER, even with both patches the behavior is still not ideal because now, while Pods are not "stuck" ContainerCreating anymore, they get "stuck" Running. It seems to me that once we remove the bottleneck on Mount/Unmount calls, the sheer amount of them is hitting some OS/kernel limitations which I am not equipped to debug. But in any case IMO we should get both patches in (to repeat, one is WIP and other is #109011) because this behavior in step 3 seems closer to the "correct" behavior than without the patches in step 1.
```
kubectl get po --sort-by=.metadata.creationTimestamp
NAME                            READY   STATUS              RESTARTS   AGE
cron-3-7vqzc-1648501380-h6hv8   1/1     Running             0          13m
cron-3-97btz-1648501380-47m6k   0/1     Completed           0          13m
cron-3-9btnx-1648501380-8z74t   1/1     Running             0          13m
cron-3-94wc8-1648501440-rhj5k   1/1     Running             0          12m
cron-3-9vchv-1648501500-qqv86   1/1     Running             0          11m
... < SNIP BECAUSE THERE'S 100 PODS IN BETWEEN 13M OLD AND 13S OLD... > ...
cron-3-82djn-1648502160-kzqk4   1/1     Running             0          52s
cron-3-7m59b-1648502160-spsd7   0/1     ContainerCreating   0          34s
cron-3-8948j-1648502160-km589   0/1     ContainerCreating   0          33s
cron-3-6ljqz-1648502160-blg4q   0/1     ContainerCreating   0          15s
cron-3-872jq-1648502160-bg5h7   0/1     ContainerCreating   0          14s
cron-3-8fr5k-1648502160-q6hqv   0/1     ContainerCreating   0          13s
```

**Comment by wongma7** [comment]
Opened https://github.com/kubernetes/kubernetes/pull/109117 to use umount -q when cleaning up subpaths
