### ISSUE TITLE
CSI Volume staging path contains PV name

### ISSUE THREAD

**Issue by jsafrane** [kubernetes/kubernetes#105899]
### What happened?

When two CSI PVs point to the same volume in the storage backend, kubelet can't start pods that use these two PVs on the same node.

Both PVs have the same VolumeHandle and kubelet is smart enough to recognize that they're the same volume (because they have the same unique volume ID). It calls `NodeStage` only once, however, the staging path contains name of one of the PVs, say PV1:  `/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-f5fa91c3-bf91-42a9-a8a3-da516e0371f0/globalmount/`

https://github.com/kubernetes/kubernetes/blob/3e6d122ee1e34ca20f9cb2fae3d36810d8dbf937/pkg/volume/csi/csi_attacher.go#L661

One of the CSI volume `SetUpAt` calls then fails, because it uses PV2 to compute the staging path and that path does not exist.
```
MountVolume.SetUp failed for volume "pv2" : rpc error: code = InvalidArgument desc = volume "1fdb001d-3634-11ec-aa06-0242ac110003" was staged at [/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-f5fa91c3-bf91-42a9-a8a3-da516e0371f0/globalmount], not "/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pv2/globalmount"
```

### What did you expect to happen?

Both pods should just start.

### How can we reproduce it (as minimally and precisely as possible)?

Using CSI HostPath volume, PV1 (dynamically provisioned for simplicity):
```yaml
  apiVersion: v1
  kind: PersistentVolume
  metadata:
    annotations:
      pv.kubernetes.io/provisioned-by: hostpath.csi.k8s.io
    name: pvc-f5fa91c3-bf91-42a9-a8a3-da516e0371f0
  spec:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 500Mi
    claimRef:
      apiVersion: v1
      kind: PersistentVolumeClaim
      name: myclaim
      namespace: default
      resourceVersion: "524"
      uid: f5fa91c3-bf91-42a9-a8a3-da516e0371f0
    csi:
      driver: hostpath.csi.k8s.io
      volumeAttributes:
        storage.kubernetes.io/csiProvisionerIdentity: 1635235714073-8081-hostpath.csi.k8s.io
      volumeHandle: 1fdb001d-3634-11ec-aa06-0242ac110003
    nodeAffinity:
      required:
        nodeSelectorTerms:
        - matchExpressions:
          - key: topology.hostpath.csi/node
            operator: In
            values:
            - 127.0.0.1
    persistentVolumeReclaimPolicy: Delete
    storageClassName: csi-hostpath-sc
    volumeMode: Filesystem
  status:
    phase: Bound
```

PV2 (basically edited PV1):
```yaml
  apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: pv2
  spec:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 500Mi
    claimRef:
      apiVersion: v1
      kind: PersistentVolumeClaim
      name: myclaim2
      namespace: default
      resourceVersion: "664"
      uid: 89932338-c301-425b-9cef-dec861f4bdaf
    csi:
      driver: hostpath.csi.k8s.io
      volumeAttributes:
        storage.kubernetes.io/csiProvisionerIdentity: 1635235714073-8081-hostpath.csi.k8s.io
      volumeHandle: 1fdb001d-3634-11ec-aa06-0242ac110003
    persistentVolumeReclaimPolicy: Retain
    storageClassName: csi-hostpath-sc
    volumeMode: Filesystem
  status:
    phase: Bound
```

PVC1, PVC2, Pod1 and Pod2 are trivial, nothing special there. 

### Kubernetes version

<details>
Today's master, dba9975e3e3ba25e0712a209e67862603c172777
</details>

**Comment by jsafrane** [comment]
We require users to drain nodes before enabling migration or when updating to a Kubernetes version that have migration enabled by default. All volumes should be therefore unmounted.

**Comment by mattcary** [comment]
@jingxu97 probably yes this breaks backward compatibility, but since only migration for PD is being done maybe it's more rare? We saw a customer case for this situation with NFS shares using the csi filestore driver.

For PD I think it would only come up when trying to ROX a PD volume across namespaces, I'm not sure if that's common.

**Comment by saikat-royc** [comment]
Capturing some thoughts here in line to understand your [suggestions](https://github.com/kubernetes/kubernetes/issues/105899#issuecomment-951778471) @jsafrane 
1. If we use a staging path like `/var/lib/kubelet/plugins/kubernetes.io/csi/<driver name>/{some-transformed<volumeId>}`, the kubelet can locate the both the driver name and the volumeId, needed during UnmountDevice call.
e.g for pd csi driver `/var/lib/kubelet/plugins/kubernetes.io/csi/pd.csi.storage.gke.io/0a39950a8a2ec8f88fcb1be558d66b8ba7648dd4981af6a166dce39e97de6432` which is the sha256{projects/mattcary-saikatroyc-test/zones/us-central1-c/disks/pvc-4284ef52-f97d-43cd-a5f1-e0c4d43856b9}. This means the volume Id needs to persisted (say the the json), so that the volume Id can be retrieved for UnmountDevice call.

2.1. if we decide to make the change at a minor boundary, then a node drain mandate would unstage any volumes before the kubelet is upgraded. this ensures any staged path for csi volume is using the new format 

2.2 If we do not want to enforce a node drain, kubelet can first lookup json data, else try to fetch the driver and volume details from the new format of handle `/var/lib/kubelet/plugins/kubernetes.io/csi/<drivername>/<encoded volume Id>` and persisted volumeId information(from some file), else fallback to try the old format. `/var/lib/kubelet/plugins/kubernetes.io/csi/pv/{pvname}/globalmount`.

3. csidriver + sha(volumeId) is expected to be unique in the cluster, if I understand. (based on the assumption any storage resource provisioned by a given driver is expected to be unique)

**Comment by jsafrane** [comment]
@saikat-royc yes, your summary is correct. We persist a json, please make sure it contains anything that NodeUnstage may need.
It seems to me that people prefer option 2.2.

> csidriver + sha(volumeId) is expected to be unique in the cluster,

We already do `sha256(node name, driver name, volume ID)` to uniquely identify VolumeAttachment. So far nobody complained about any conflict.
