### ISSUE TITLE
Deploying kube-up cluster: Permission denied (public key)

### ISSUE THREAD

**Issue by adyanthaya17** [kubernetes/kubernetes#10599]
Hi, I'm building my kubernetes inside my openstack with the help of instances, while deploying the master and minion instance nodes I get the error 'Permission denied (public key). I have worked building on bare metal and I didn't face such issue then. 

I have added the ssh-agent identity successfully.

**Comment by adyanthaya17** [comment]
When I try the command with sudo this is what I get:

$ sudo KUBERNETES_PROVIDER=ubuntu ./kube-up.sh
Starting cluster using provider: ubuntu
... calling verify-prereqs
Could not find or add an SSH identity.
Please start ssh-agent, add your identity, and retry.

I've deleted and created the key freshly. And added the ssh-agent too.

**Comment by zmerlynn** [comment]
cc @WIZARD-CXY?

**Comment by WIZARD-CXY** [comment]
never met it before.Where do you issuse the `kube-up` command? openstack vm or what?
You can add `set -x` to enable debug in util.sh to see more info

**Comment by adyanthaya17** [comment]
I was wondering if it's because of the version I'm using. Previously I worked on the baremetal vm having ubuntu 14.04. The instances vm inside the openstack has ubuntu 12.04. Is that the reason it's not able to deploy and is giving permission issue related to ssh?

I googled few documents and went through it, I  have an inclination that it might be related to openssh-server. Currently I'm upgrading the image to 14.04 ubuntu.

**Comment by goltermann** [comment]
We’re going through old support issues and asking everyone to direct your questions to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes). 

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases. 

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.
