### ISSUE TITLE
/stats/summary kubelet endpoint usage

### ISSUE THREAD

**Issue by Nimmsy** [kubernetes/kubernetes#106080]
### What happened?

Hi,

Currently, we are monitoring the performance metrics ( cpu , memory utilized ) of pods and nodes via the kubelet endpoint /stats/summary.… Have been seeing news stating this API will be deprecated in the upcoming versions say 1.23 … one instance is – [[Move away from kubelet stats/summary](https://github.com/elastic/beats/issues/12792)]

Is this true … ? if this is true what is the alternative … what is the backward compatibility supported for this?

Apologize for posting this as a bug - not able to get a response in the Kubernetes discussion group. have raised a query there as well.. ( https://discuss.kubernetes.io/t/kubelet-stats-summary-endpoint/17922 )

Any help on this will be greatly appreciated.

### What did you expect to happen?

---

### How can we reproduce it (as minimally and precisely as possible)?

---

### Kubernetes version

<details>

```console
$ kubectl version
1.21
```

</details>

### Cloud provider

<details>
EKS, GKE , AKS
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by Nimmsy** [comment]
Guyz , Any update will be helpful

**Comment by serathius** [comment]
Please read this issue https://github.com/kubernetes/kubernetes/issues/68522#issuecomment-724928827

Kubelet Summary API, is currently only planned for deprecation, this hasn't yet happened as noone proposed a working alternative. When it will happen it will be clearly announced and it will take at least 3 releases before it is removed. Meaning you will have around a year to adapt. 

As for alternative that are currently two available:
* CPU and Memory metrics are also available via Kubelet /metrics/resource endpoint in Prometheus format. This was introduced to get Kubernetes internal autoscaling pipelines (Metrics Server, kubectl top, HPA) moved out of Summary API.
* Running cAdvisor yourself and using it's API. If you need something with longer support NOW, you might want to bind to cAdvisor API instead of Kubernetes one. This is will add some complexity for you, however you will not have a rug pulled from under you when Summary API is deprecated. This solution would make sense if you are want API available now that will not change in window of couple years.

/cc @dashpole

**Comment by Nimmsy** [comment]
Hi @serathius ,

Thanks for your suggestion... really helpful.

Could you also point me to the API for getting metrics of Pod such as data transmitted / received, errors transmitted/received?

**Comment by lizhuqi** [comment]
What is the current Windows support for /stats/summary endpoint? It seems that rootfs usedBytes is always return 0 for pods running in Windows nodes. However I do see some values are reported for availableBytes and capacityBytes. 

Is https://github.com/kubernetes/kubernetes/blob/33de444861d3de783a6618be9d10fa84da1c11b4/pkg/kubelet/cadvisor/cadvisor_windows.go#L82 the right code path for the support?

**Comment by ringerc** [comment]
If you want to query this directly use

```
kubectl get --raw "/api/v1/nodes/YOURNODENAME/proxy/stats/summary"
```

**Comment by devonhk** [comment]
> Kubelet Summary API, is currently only planned for deprecation

Are there still plans to deprecate this API? The [original proposal](https://github.com/kubernetes/kubernetes/issues/68522) is 7 years old and activity on the ticket seems to have died down.
