### ISSUE TITLE
Add go-runner to kube-proxy image

### ISSUE THREAD

**Issue by serathius** [kubernetes/kubernetes#106086]
All other control plane component images have go-runner available. With deprecation of klog flags [KEP-2845](https://github.com/kubernetes/enhancements/blob/master/keps/sig-instrumentation/2845-deprecate-klog-specific-flags-in-k8s-components/README.md) we should also add go-runner to kube-proxy image. 

This is required for https://github.com/kubernetes/kops/issues/12663

**Comment by serathius** [comment]
/sig release

Tried to read through image build code, I don't think I will be able to implement it without help.
Adding go-runner to kube-proxy is not as simple as it uses different base image than all other images.

**Comment by aojea** [comment]
what is "go-runner" ?

**Comment by serathius** [comment]
> what is "go-runner" ?

Small binary included in K8s container images used to write logs to file, it was developed by @dims as workaround for klog scalability problems. Instead of calling apiserver binary, we call it through go-runner.

**Comment by aojea** [comment]
do you have a link to a PR of another image migration?

**Comment by serathius** [comment]
> do you have a link to a PR of another image migration?

I don't have. This change is tricky as kube-proxy image is different than other. Maybe @BenTheElder can help and give a hint how to implement this.

**Comment by BenTheElder** [comment]
So these images now live in https://github.com/kubernetes/release/tree/master/images/build, currently the go-runner binary sources live as part of a go-runner image which is ~ distroless + go-runner.

With kube-proxy we need actually several binaries from a distro (`iptables-save` etc.) so we'd need to add the go-runner binary to that image. (["debian-iptables"](https://github.com/kubernetes/release/tree/master/images/build/debian-iptables)).

Since we already have the debian-iptables image depend on the debian-base image, we could also have it depend on the go-runner image and just copy over the binary, which would be a pretty minimal change. I can send a PR shortly.

I think the biggest question is just: should we also include this in debian-base for any other images that are for some reason using klog, with debian-base, but not debian-iptables.

/assign

**Comment by pohly** [comment]
This is done, thanks everyone.

 From current master:
```
$ docker run --rm k8s.gcr.io/kube-proxy-amd64:v1.23.0-alpha.4.255_3cfef611122484-dirty /go-runner -help
Usage of /go-runner:
  -also-stdout
    	useful with log-file, log to standard output as well as the log file
  -log-file string
    	If non-empty, save stdout to this file
  -redirect-stderr
    	treat stderr same as stdout (default true)
```
