### ISSUE TITLE
Expose the completions value to the indexed job containers

### ISSUE THREAD

**Issue by benjamin-bergia** [kubernetes/kubernetes#106009]
### What would you like to be added?

Following my comment [here](https://github.com/kubernetes/kubernetes/issues/14188#issuecomment-952935754), I think it would be very useful to expose the value of `spec.completions` to the containers. The same way that it is currently done for the completion index. 

### Why is this needed?

We have recently started to use the indexed jobs to process data on one of our clusters. When the pods are aware of both the completions and their own completion index, it is pretty trivial for the them to dispatch/slice the work without any central scheduler or queue.
Unfortunately, it is not trivial to pass to the containers environments since it is part of the Job spec and as such is not available through the downward API.

@alculquicondor @soltysh 

PS: If this is going to be implemented, you might as well expose both `spec.completions` and `spec.parallelism`. I can see situations where it might be useful for the pod to be aware of how many pods are running beside it.

**Comment by neolit123** [comment]
/sig apps
as per the original linked issue?

**Comment by rhuss** [comment]
I still think that it would be a great addition to have a `JOB_COMPLETION_TOTAL` (or `JOB_COMPLETION_NR`) to allow indexed jobs determine their partition to work on (like in the often cited example of video processing, without knowing how many Pods are working on a given file, the index alone is not good enough to find out which range of frames should be processed). Also, having it part of the Downward API would be great (as it could also be mounted as volumes so that changes could be detected).

The possible solutions all have their drawbacks:

* Hardcode the number of completions into the Job's application code. That is a bummer as it couples your code to the K8s resource descriptor (for sure the wrong direction) and potentially requires an image rebuild in case `.spec.completion` changes).
* User an own custom environment variable in the Job's template spec to specify that value. This is better but still duplicates the completion value, which would require two changes in the descriptor in case `.spec.completions` needs to be tuned. (and also provides the danger of getting out-of-sync).

**Comment by alculquicondor** [comment]
/reopen

I think this is the most important question that needs to be answered if we want to implement this:

> Now the only concern is that, after your proposed change, completions can never be mutable, which is something I was considering as a future possibility. Of course, we can always say that it's not guaranteed that the environment variable is accurate when you change the number of completions.

Are we giving up on mutable completions or are we comfortable with the environment variable being inaccurate if you change number of completions in a running job?

**Comment by rhuss** [comment]
> Are we giving up on mutable completions or are we comfortable with the environment variable being inaccurate if you change number of completions in a running job?

For the mutable case, would it be an option to refer to mounting that value via the Downward API, assuming that the number of completions is also exposed as an annotation, like the completion index via the annotation `batch.kubernetes.io/job-completion-index` ?

I mean, it's a restriction of every injected environment variable (not only for Jobs but also user-provided env vars) that it can't be changed once the process has started, so I don't expect that people will be surprised by this restriction.

Also, for the _Indexed Jobs_ I would even disallow changing the completion count once the Job has started since the work is partitioned at the startup of the job (like selecting the frame range in a video file for processing). I can't see a use case for how this could be changed in retrospect (e.g., when the job is running) without a complex burden for the application code. 

Which use cases do you have in mind for a mutable completion number, especially for jobs with `completionMode == Indexed` ?

**Comment by alculquicondor** [comment]
The mutable number of completions requirement comes from horovod, which supports the number of workers to change overtime. This would run on Indexed Jobs, if ever. I don't know if there are other similar use cases.

> For the mutable case, would it be an option to refer to mounting that value via the Downward API as a file

Certainly, but I fear that it's harder to use this way.

I'm inclined to leave this conversation to the time when we make a decision about mutable completions, which I'm thinking of tackling in a couple of releases.

**Comment by rhuss** [comment]
> The mutable number of completions requirement comes from horovod, which supports the number of workers to change overtime. This would run on Indexed Jobs, if ever. I don't know if there are other similar use cases.

Sorry for my ignorance, but I would like to understand the underlying use case _why_ changing the number of workers overtime for indexed jobs is important and how this change would be propagated to the existing workers as they have to adapt probably their work assignments ("change the sized of the partition to process", "process now only every m-th row, instead of every n-th row, ..."). But I could miss the use case where such a change would make sense without imposing such overhead.

**Comment by alculquicondor** [comment]
This is one reference https://horovod.readthedocs.io/en/stable/elastic_include.html

I'm actually not convinced that we should do this in the Job API. But it needs a proper analysis worthy of a KEP.

**Comment by rhuss** [comment]
fwiw, I still think this feature would be a super helpful addition to the API. Some background info might be ok: We are currently working on the second edition of "Kubernetes Patterns" (an O'Reilly book), and we are about to submit the following section for the final book:

![image](https://user-images.githubusercontent.com/99080/209857885-d82b5ae2-6d73-4cd5-abf8-4bf8b5401b9a.png)

There is only a little time left until the book's deadline (Jan 6th), but I hope the community is ok with this statement in the book. If not, please let us know asap. Thanks a lot for all your work btw!

**Comment by alculquicondor** [comment]
Even if we add the feature, it wouldn't be on time for the book.

TBH, I don't like the wording of the lack of the environment variable. As it's already discussed in the issue, the proposed solutions are perfectly valid and not a "workaround". Also, not all applications need to know the number of elements, so the wording could be confusing for these users.

I would phrase it along these lines:

If each worker of the application needs to know the total number of workers, you have two alternatives:
1. Copy `.spec.completions` into a environment variable (give YAML example)
2. Add a parameter to your application to accept the number of workers and pass it as part of the program arguments.

There has been some discussion in Kubernetes (link to github issue) about whether it's worth having Kubernetes provide the value as an environment variable by default. The main drawback is that environment variables can't be modified at runtime, complicating a future support for resizable jobs.

**Comment by rhuss** [comment]
Fair enough. Thanks for the feedback!

btw, I never called it a workaround but as 'two solutions with drawbacks'. I still think that updating two values in the spec when the number of completions changes (`.spec.completions` and the custom env variable/argument that hands it over to the application code) is not optimal because of a potential config drift and the risk of contradicting values set in both places. But I removed that `drawback` part.

I rephrased the final paragraph according to your suggestion:

> There has been https://github.com/kubernetes/kubernetes/issues/106009[some discussion] within the Kubernetes community about whether Kubernetes should provide the value of the `.spec.completions` field as an environment variable by default. The main concern with this approach is that environment variables cannot be modified at runtime, which could complicate support for resizable jobs in the future. As a result, it seems unlikely that a `JOB_COMPLETION_TOTAL` environment variable reflecting the initial `.spec.completions` field will be introduced in Kubernetes.

'hope this is ok. Thanks again for your help!

**Comment by alculquicondor** [comment]
> As a result, a `JOB_COMPLETION_TOTAL` environment variable is not provided by Kubernetes as of version 1.26.

**Comment by alculquicondor** [comment]
It looks like https://github.com/kubernetes/enhancements/pull/3724 is moving towards having mutable completions, which will render this request incompatible.

If this enhancement goes through, the recommendation for this request is that users add the environment variable themselves if they know completions won't change.

**Comment by alculquicondor** [comment]
The enhancement to make job completions mutable went through.

Users that want an environment variable for the number of completions should add them manually.

/close
