### ISSUE TITLE
Feature Request: CPU Core Grouping & Assignment (Performance vs Efficiency cores) 

### ISSUE THREAD

**Issue by sfxworks** [kubernetes/kubernetes#106157]
### What would you like to be added?

I would like the ability to group cores so that I may schedule deployments against faster or slower performing CPU cores within a motherboard.

### Why is this needed?

With the current state of ARM processors like the RockPro64 and the upcoming release of Intel 11th gen, a Kubernetes cluster should be able to schedule certain workloads on performance vs efficiency cores. 

End-user scenario: Being able to assign certain workloads (such as daemonsets or background tasks) on efficiency cores and main applications (such as a giant java application) on a performance core.

**Comment by MadhavJivrajani** [comment]
@sfxworks this seems worth brining up in a sig meeting.
More info here: https://github.com/kubernetes/community/tree/master/sig-node#meetings 
/cc @fromanirh

**Comment by SergeyKanzhelev** [comment]
cc: @kad 

Discussed during the SIG Node meeting. It would be great to start collect use cases and specific requirements on how this will look like from end user perspective. @mrunalp suggested we can start a document on this, or we can use this issue to keep the discussion going.

/triage needs-information

**Comment by mrunalp** [comment]
Do we have to care about integration with the Intel Thread Director on Alder Lake on Linux?

**Comment by kad** [comment]
@mrunalp checked with kernel team: thread director for Linux is still under development, and right now it is not easily forecastable on when it will be merged into mainline kernel. However, even if that is going to be implemented, it will not solve the overall issue that is brought in this issue: the ability to user to specify which kind of cores user would like to use for particular workload.

That is not only about CPU cores, but that is also applicable for memory: the current and future hardware going to have heterogenous "native compute resources" with different performance and feature characteristics, and potentially multiple classes of those.

The biggest problem that needs to be solved is ability to specify for user instead of generic "cpu" or "memory".
All existing/past ideas and approaches to use extended resources to represent different kinds of heterogenous resources leaded to double accounting with native cpu/memory tracking. Beside double accounting, there are also issues with ability to represent partial usage: for native "cpu" resource we can request "500m", but with extended resources we have only integer values...

As I mentioned in the meeting, our team (me + @klihub + @marquiz + @askervin ), had some ideas how to solve that. I don't have at the moment written proposal, but for people who are interested in the topic we can do ad-hoc meeting where I can present few ideas that we had in mind and have virtual "whiteboard" discussion session to see if that is really wild idea or something that we can evolve into potentially working solution.

Also, would like to remind, that many aspects of those hardware details will be really hardware vendor / architecture (or in worst case CPU model) specifics, so trying to fit every possible hardware combination inside kubelet is going to be very problematic and not scalable in my opinion.  We need better ways to discover, dynamically adjust node capacity/allocatable resources, etc... Designing this feature properly will require several places to be refactored, several assumptions removed... and if it will be implemented in simplistic "let's only close current gaps now" approach, it might create more problems in the future generations of the hardware.

**Comment by marquiz** [comment]
I agree with @kad here. We should aim at a future proof solution in the sense that try to avoid painting us in the corner in the face of new hardware generations. Also, trying to find a generic kubelet-only one-size-fits-all solution feels like a futile effort.

**Comment by morsik** [comment]
It's 2024, maybe time to reconsider opening this issue? Because it seems to useful in the long run.

**Comment by kad** [comment]
@morsik support for P and E cores available in Topology-Aware NRI policy: https://github.com/containers/nri-plugins/

**Comment by morsik** [comment]
@kad oh, I wasn't aware of that. Thanks, will take a look!
