### ISSUE TITLE
Reconsider how we implement watermarks in P&F

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#106302]
Spin off from https://github.com/kubernetes/kubernetes/pull/105873/files#r735360613

In my opinion, having additional concepts of TimedObservers rather than relying directly on metrics is unnecessarily complicating the (already pretty complicated) codebase.
My main questions are:
- do we really need them?
- do we really want to get into the business of watermarks, etc.? Can't we rely on monitoring solutions to just do that (compute the max?)

Mike`s argument was that scraping latency of metric is an issue, but my question is whether it is really an issue?

For example - if my PL was saturated for 1ms, and other than that stays 50% occupied only - is that really something I care as an operator? I can't imagine any action I could take as an operator based on that information.

I would really like to see that simplified, but also that's not something I want to block the above PR on - so opening this issue to discuss that further.

/kind cleanup
/sig api-machinery
/priority important-longterm

@tkashem @MikeSpreitzer

**Comment by MikeSpreitzer** [comment]
We have been in the business of watermarking since before I got involved.  The max-in-flight filter was already doing watermarking.

The simplest thing to do is to use a gauge.  Consider a scenario where scrapes happen once per minute (and yes, I know some real scenarios like that).  In that case the admin can only see situations that are very stable.

**Comment by wojtek-t** [comment]
Is the watermark really what gives us value?
I absolutely buy the need for some over-time aggregation (sorry - that wasn't clear from the initial issue report), but is watermark really what gives me any actionable information?

Let's say that we're aggregating over 5m even (yes - I'm aware of per-minute scraping usecases too).
And let's say that my watermark is saturated. Is that a useful information for an administrator? How can I really distinguish if it was saturated for 1ms or for majority of this 5m period?

My additional concern is that the code that currently does watermarking is pretty complicated:
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/util/flowcontrol/metrics/sample_and_watermark.go#L162
Comparing to the original water-marking in max-in-flight filters that was extremely simple:
https://github.com/kubernetes/kubernetes/blob/release-1.17/staging/src/k8s.io/apiserver/pkg/server/filters/maxinflight.go#L81


So what if instead we would be simply reporting the histrogram of "current saturation"?
Histograms are super simply to subtract from each other to get the value from a "period of time".
So by getting histogram from the e.g. last 1m, I can now quickly infer the good enough estimation for the watermark (we can have top bucket to be 99%-100% or sth and get good enough estimation).
I think it would be much easier codewise and much more useful for actual operators.

**Comment by MikeSpreitzer** [comment]
What do you mean by "current"?  When would `Observe` be called for such a histogram?  If that happens when the variable of primary interest changes then we are not getting time-weighted data.  Consider two scenarios.  In scenario A, the variable jumps up at time T0 and back down at time T0+1ms.  In scenario B, the variable jumps up at time T0 and back down at time T0+10s.  Those both produce the same metrics if we only Observe when the variable changes.

If we want a time-weighted sampling, well, that is the source of most of the complexity you cited.  Note that the cited code is producing both a histogram of samples and a histogram of watermarks.

The histogram of watermarks lets us know what the sampling missed.

**Comment by wojtek-t** [comment]
> What do you mean by "current"? When would Observe be called for such a histogram? If that happens when the variable of primary interest changes then we are not getting time-weighted data. Consider two scenarios. In scenario A, the variable jumps up at time T0 and back down at time T0+1ms. In scenario B, the variable jumps up at time T0 and back down at time T0+10s. Those both produce the same metrics if we only Observe when the variable changes.

Sure - the question is how big problem that is in practice. In practice we will be having some request finishing pretty frequently, so it shouldn't be that big deal.

That said - as discussed during our weekly sync - I think we have more urgent stuff to focus on now that simplifying this.
So let's close now - we can get back to it in the future.
