### ISSUE TITLE
Improve kubectl wait output message

### ISSUE THREAD

**Issue by collimarco** [kubernetes/kubernetes#106364]
### What would you like to be added?

Currently the output of `wait` is simply `condition met`... 

It would be much more useful to have something meaningful like `job completed`, `pod ready`, etc. You can simply use the name of the condition (`for` argument).

### Why is this needed?

Currently when you have a long CI/CD pipeline it's difficult to understand what is going on when there are multiple `wait` because the message is too generic and you can't distinguish the steps.

**Comment by NikhilSharmaWe** [comment]
@neolit123 I would like to add this enhancement. Could you please give me some direction about how can I proceed to solve this issue, like in which files the changes are needed and more.

**Comment by eddiezane** [comment]
This is a reasonable ask but would be a pain to implement because of the way the command and printers currently work. We can consider it if there is enough demand from the community.

> Currently when you have a long CI/CD pipeline it's difficult to understand what is going on when there are multiple wait because the message is too generic and you can't distinguish the steps.

@collimarco would something like `kubectl wait --for...... && echo "done deleting web pod"` help you for now?

/triage needs-information
