### ISSUE TITLE
CronJob loses track of Jobs after label update

### ISSUE THREAD

**Issue by RobinMcCorkell** [kubernetes/kubernetes#106496]
### What happened?

Changing the label on a job template in a CronJob causes any Jobs held by the successful/failed history parameters to stop being tracked, so they never get cleaned up.

### What did you expect to happen?

Jobs with labels that don't match the (upgraded) CronJob, but still have an owner reference, should be subject to the history limit.

### How can we reproduce it (as minimally and precisely as possible)?

1. Deploy a CronJob with a job template containing label `foo: one`, and non-zero history limit
2. Allow the CronJob to run and generate some Jobs (default 3 successful, 1 failed)
3. Update the CronJob with a job template containing label `foo: two`
4. Allow the CronJob to run and generate some more Jobs
5. Notice there are more than 3 successful Jobs/1 failed Job!

### Anything else we need to know?

I believe this is the relevant code: https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/cronjob/cronjob_controllerv2.go#L235-L239

The CronJob controller finds Jobs that it should care about by matching on the labels in the job template, this obviously breaks if the labels in the job template change.

### Kubernetes version

1.21

### Cloud provider

Self-hosted

**Comment by d-honeybadger** [comment]
Experiencing another side-effect of this bug.

If job template labels are updated while a cronjob has `active` status (a scheduled job is running), then that cronjob gets stuck in `active`. The cause seems to be the same as @RobinMcCorkell describes: once the job template labels are updated, cronjob controller V2 loses track of the jobs with the old labels, and therefore never updates the status of that active cronjob to indicate that the scheduled job has completed.
