### ISSUE TITLE
API deprecation metrics misleading with garbage collection controller

### ISSUE THREAD

**Issue by lorenz** [kubernetes/kubernetes#106668]
### What happened?

I was checking if everything in my cluster has upgraded to non-deprecated API versions prior to upgrading.
In https://github.com/kubernetes/kubernetes/pull/73032 the apiserver_requested_deprecated_apis metric was added
to help operators determine if there are any users of deprecated APIs left. But in a 1.21.7 cluster the extensions/v1beta1 ingresses gauge is always 1. Using audit logs I saw that the controller-manager was the sole user left. Since there is no explicit user in any controller, I'm pretty certain that the garbagecollector controller watches these resources because they are deletable.

### What did you expect to happen?

The gauge should go to zero once there aren't any users left. The garbage collector is a special case as it uses a form of reflection and is thus not a real "user" of that API. It will just stop using it as soon as it's gone.

### How can we reproduce it (as minimally and precisely as possible)?

If my theory is correct any stock 1.21 cluster with a full control plane should have that gauge as 1 wrongly.

### Anything else we need to know?

Architecturally this is a bit ugly to fix because the API server sensibly does not care if the client uses reflection to just use all APIs exposed or uses a specific one. But it essentially makes these metrics nearly useless other than to join them into apiserver_requests_total. Since these are alpha metrics it might also make sense to remove them because right now they are misleading.

### Kubernetes version

<details>

```console
$ kubectl version
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.7", GitCommit:"1f86634ff08f37e54e8bfcd86bc90b61c98f84d4", GitTreeState:"clean", BuildDate:"2021-11-17T14:35:38Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
Bare-Metal with custom integration
</details>

### OS version

<details>

```console
Custom OS based on Flatcar with a custom kernel based on Linux 5.10
```

</details>

### Install tools

<details>
Custom
</details>

**Comment by liggitt** [comment]
I agree that's a bit ugly. Fortunately, it won't be an issue for future APIs that graduate from a beta to a ga version in the same API group (extensions/v1beta1 ingress was the last remnant of the ill-fated extensions group whose APIs had to migrate to other groups before graduating)

the controller prefers more stable API versions when available, so in the future, as soon as a v1 is available, it will switch to use that instead of a beta version, and will stop triggering that metric. 

In this case, the audit log is the recommended approach for determining specifically which users are still relying on the deprecated API, and the garbage collection and resource quota controllers' reads of extensions/v1beta1 ingresses could be safely ignored.

**Comment by liggitt** [comment]
It's worth calling this edge out in the documentation, though.

**Comment by fedebongio** [comment]
@lorenz would you be up to add this case to our documentation? Let us know, thanks! 
/help
/triage accepted
