### ISSUE TITLE
vSphere getting started stuck on waiting kubernetes API

### ISSUE THREAD

**Issue by skuzye** [kubernetes/kubernetes#10675]
Hello, I'm trying to setup a kubernetes cluster using the development tree but cannot make it work. After running kube-up.sh it just hangs on waiting for the API to be ready. However, I can confirm that all machines have installed the saltstack correctly, i.e. finished the minion-start.sh and master-start.sh successfully.

Running salt-key --list-all shows that all keys have been accepted. None of the kubernetes services start. Am I missing something?

**Comment by roberthbailey** [comment]
@pietern seems to be the primary author of the vsphere getting started guide.

**Comment by erictune** [comment]
AFIAK, the vSphere guide was last tested with v0.9.  We are on v0.21.  If you are trying to use latest binaries with that guide, I'm certain it won't work.  If you are using v0.9 binaries, those are so old that most devs can't remember how to debug stuff that old.

**Comment by pietern** [comment]
I'll check it out.

**Comment by skuzye** [comment]
I tested with latest release version and with master. I'm trying to find where things go wrong but I have no experience with Saltstack.

If there's something you need from me to help debug this please let me know. Meanwhile I'll see what I can find out.

Thanks!

**Comment by pietern** [comment]
Thanks @skuzye, I tried running the original guide against the latest bits but there's some Salt files that don't compile. Instead of hacking that up to make it work again I'm now looking at taking the same approach the GCE scripts have and only use standalone Salt on every node rather than a master and several minions, removing the Salt interactions altogether.

**Comment by skuzye** [comment]
What about using docker-machine and run kubernetes from docker as that has been fixed in 1.0? Seems to me it would be a lot simpler.

**Comment by roberthbailey** [comment]
Please direct your questions to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes). 

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases. 

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to similar questions, and also familiarize yourself with:
  * [the user guide](http://kubernetes.io/v1.0/)
  * [the troubleshooting guide](http://kubernetes.io/v1.0/docs/troubleshooting.html)

Again, thanks for using Kubernetes.

The Kubernetes Team
