### ISSUE TITLE
Dry-run support for HPA

### ISSUE THREAD

**Issue by mfanjie** [kubernetes/kubernetes#106765]
### What would you like to be added?

Can we add dry-run function in HPA, similarly to VPA?
From code implementation perspective, this is low cost/risk change and  it would be super useful for many cases.
As I know, some organizations changed the HPA code and just for dry-run, it's better if it can be supported natively.

### Why is this needed?

HPA is is flexible enough to support built-in metrics as well as custom metrics or external metrics, and this flexibility gives us opportunities to build enhanced scaling solution, for example, we are building solution based on prediction algorithms.
That leads some challenges that how we can ensure the custom/external metrics is correct before it's taking into effects, if a dry-run mode can be supported in HPA, just like what VPA is doing now, it will be super helpful for building such solutions.

**Comment by minbaev** [comment]
Hello, I would like to start working on this issue

**Comment by minbaev** [comment]
@gjtempleton @mwielgus Hi do you think i can start looking into adding the dry-run?

**Comment by gjtempleton** [comment]
Hi, as much as I can see how this feature might be useful, before starting work on it it'd be best to get a clearer idea of exactly how you're wanting to implement this, what changes implementation would require to the HPA, and thus whether a full [KEP](https://github.com/kubernetes/enhancements/blob/master/keps/sig-architecture/0000-kep-process/README.md) is required for this. If you want to discuss it in more detail, you can always attend the [SIG's office hours](https://github.com/kubernetes/community/tree/master/sig-autoscaling).

A statement of `From code implementation perspective, this is low cost/risk change` doesn't really give us much to go on, and we'd obviously far rather discuss at least a general idea of implementation, rather than raise major issues at the point where you've written all the code.

**Comment by minbaev** [comment]
Thank you for you response. I can attend the sig office hours to discuss details
