### ISSUE TITLE
Kubelet --cluster-dns-service vs --clusterdns (maybe)

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#106771]
xref #101682

I have wondered if we should add a kubelet option like `--cluster-dns-service` (as an alternative to `--cluster-dns`) which takes a service ns/name (e.g. "kube-system/kube-dns") and looks up the IP(s).  That would avoid the need for a static DNS IP at all.

Kubelet could spawn a gorotine to poll it.  Any pod that starts before the DNS Service is up would not get a nameserver or maybe we just don't start pods which need that value until resolves.  E.g. hostNetwork pods could start.

This would obviate the need for a special static DNS IP (the .10 IP by convention).

@aojea

**Comment by aojea** [comment]
> Kubelet could spawn a gorotine to poll it. Any pod that starts before the DNS Service is up would not get a nameserver or maybe we just don't start pods which need that value until resolves. E.g. hostNetwork pods could start.

Some installers use host network pods for bootstrapping the cluster, installing the scheduler, controller-manager and apiserver ... I think that they will the main stakeholders, I'm curious about their feedback on this ...

/sig cluster-lifecycle

/cc @justinsb @neolit123

**Comment by neolit123** [comment]
AFAIK, `kube-system/kube-dns` is a hardcoded assumption in at least `kubectl cluster-info` e2e suite tests, kubeadm and kube-up. i don't see it in conformance tests, but we may have to double check if it is.

if that value is pinned as a default in a new kubelet option then kube-up and kubeadm will not have to opt-in into setting it.
ideally the value should be a KubeletConfiguration option instead of a flag, since IIRC sig-node no longer want new flags in the kubelet.

> Kubelet could spawn a gorotine to poll it. Any pod that starts before the DNS Service is up would not get a nameserver or maybe we just don't start pods which need that value until resolves. E.g. hostNetwork pods could start.

given we use static pods for deploying control plane components in a number of deployments such as kops, openshift, kubeadm, etc then we should not block these static pods in the loop at least, otherwise the apiserver will not start, the node will not register, etc.

> This would obviate the need for a special static DNS IP (the .10 IP by convention).

i don't think i understand the `.10` problem very well (likely gaps in the understanding of the networking model) but if this is something that is needed i can see it working for users who can override the kubelet option and deploy their own DNS server.

something to note though, is that the DNS server is pretty much the last thing that start running in a kubeadm deployment at least, as it starts after the CNI plugin is in place. but the DNS server (coredns deployment) and kube-proxy (ds) are also run as pods, so those should not be blocked as well somehow. kube-proxy in kubeadm is hostnetwork, but the coredns deployment is not.

/sig node
/area kubelet
given this needs changes in kubelet

**Comment by neolit123** [comment]
would love to hear what @justinsb thinks of the proposal as well.
