### ISSUE TITLE
endpointslice_controller_test.go is using time.Sleep

### ISSUE THREAD

**Issue by mborsz** [kubernetes/kubernetes#106989]
In https://github.com/kubernetes/kubernetes/pull/88745 I added a unit tests that are using time.Sleep. It's bad: it makes our tests slower than they need to be and involves some risk of races.

We should migrate this test to mocked clock.

This requires implementing a new workqueue.NewNamedRateLimitingQueueWitthCustomClock, similarly as workload.NewDelayingQueueWithCustomClock and migrating TestPodAddsBatching and TestPodUpdatesBatching to use that.

/kind cleanup

**Comment by mborsz** [comment]
/kind cleanup

Relevant code: https://github.com/mborsz/kubernetes/blob/55c92cf66aaecd4615f71d95ed96d4893e6fc685/pkg/controller/endpointslice/endpointslice_controller_test.go#L387

**Comment by NikhilSharmaWe** [comment]
@mborsz I would like to collaborate. Could you please tell me where is the code for `workload.NewDelayingQueueWithCustomClock` and where it is used, so that I can understand that how to work on making `workqueue.NewNamedRateLimitingQueueWitthCustomClock`. 

Could you please also elaborate what should I keep in mind or steps while making the changes.

**Comment by NikhilSharmaWe** [comment]
@mborsz I would like to collaborate. Could you please tell me where is the code for `workload.NewDelayingQueueWithCustomClock` and where it is used, so that I can understand that how to work on making `workqueue.NewNamedRateLimitingQueueWitthCustomClock`. 

Could you please also elaborate what should I keep in mind or steps while making the changes.

**Comment by yedamao** [comment]
@mborsz I noticed the `endpoints_controller_test.go` using time.Sleep, too. https://github.com/kubernetes/kubernetes/pull/107073 this PR migrate endpoints controller tests to mock clock. Please take a look.
