### ISSUE TITLE
Dockershim removal feedback & issues

### ISSUE THREAD

**Issue by mrbobbytables** [kubernetes/kubernetes#106917]
Please use this issue for feedback and issues regarding dockershim removal in the 1.24 release. 

/triage accepted
/milestone v1.24
/sig docs node
/area docker

**Comment by afbjorklund** [comment]
There is still no release available for cri-dockerd, even though being announced in April.

https://www.mirantis.com/blog/the-future-of-dockershim-is-cri-dockerd/

**Comment by neolit123** [comment]
A transition to cri-dockerd first might be smoother, indeed. There is especially a concern for business with a lot of clusters, with a lot of docker nodes. If they cannot move to alernative runtimes due to bugs these bugs will have to be reported and resolved. Requiring things like a host OS update with the CR update is not great.

cri-dockerd is currently a third party project with an undefined maintenance state. Because of that it is difficult to maintain a k8s.io guide for it.
The new guide for migrating to containerd seems like the best option for the time being.

At the same time we don't want users to be stuck with a 1.23 kubelet. Note: the k8s skew policy allows nodes to continue have a 1.23 kubelet against a 1.24  and 1.25 kube-apiserver, but that would only delay the required changes.

https://kubernetes.io/releases/version-skew-policy/#kubelet

**Comment by afbjorklund** [comment]
If I understand correctly, the plan is to remove all support (for docker) from the documentation and from the supporting tools like kubeadm and leave users to make their own adventure (or to pay for Docker or Mirantis)

For minikube it seems like continuing with docker runtime is doable, even if it means having to build our own CRI binaries and do our own CRI configuration. We do have containerd available as opt-in, since a long time back.

**Comment by neolit123** [comment]
> If I understand correctly, the plan is to remove all support (for docker) from the documentation and from the supporting tools like kubeadm and leave users to make their own adventure (or to pay for Docker or Mirantis)

if cri-dockerd becomes a maintained and documented project, i don't see a problem for k8s.io to link and mention it as part of CR setup. https://kubernetes.io/docs/setup/production-environment/container-runtimes/

> No documentation on kubernetes.io

cross-linking from k8s.io to cri-dockerd guides still make sense.

> No testing in kubernetes regression

testing is difficult if the CRI implementation is external and unmaintained. if cri-dockerd ramp up on the maintenance i can see kubeadm adding e2e tests for docker. we switched all test jobs to containerd for the time being.

> No binary packages available

cri-dockerd need to start making releases and have a support matrix against the kubelet especially WRT the CRI API version that is in use by both.

> No support in kubeadm init

`kubeadm init` allows you to pass *any* custom CRI socket via `Init|JoinConfiguration.nodeRegistration.criSocket`.
the CR will be treated as "remote" and configured (via a kubelet flags) similarly to how containerd | cri-o users, use kubeadm today. if `docker.sock` is present on the host and if cri-dockerd setups the legacy `dockershim.sock`, kubeadm would autodetect docker as the CR and start using it (we still have to make one minor change for kubeadm 1.24).

> For minikube it seems like continuing with docker runtime is doable, even if it means having to build our own CRI binaries and do our own CRI configuration. We do have containerd available as opt-in, since a long time back

i would not recommend for minikube and users of k8s to start using cri-dockerd until the project is actually maintained, has docs and releases. if Mirantis cannot staff the project, they'd have to grant community ownership.

**Comment by afbjorklund** [comment]
I think Mirantis had plenty of time for that, with the delay... Don't think moving to 1.25 would have helped ?

Was referring to the auto-detection and the recommendations, it does work to use `kubeadm` with params

Users of minikube are free to choose their kubernetes version and the container runtime, using parameters..

If they want to stick with k8s 1.23, or move to containerd, they are free to do so. Otherwise, it is inevitable.

**Comment by rphillips** [comment]
Linking my issue about local-up-cluster.sh not working nicely due to the dockershim removal: https://github.com/kubernetes/kubernetes/issues/106972

**Comment by afbjorklund** [comment]
Added https://github.com/Mirantis/cri-dockerd/commit/542e27dee12db61d6e96d2a83a20359474a5efa2, which identifies itself as `cri-dockerd 0.2.0 (HEAD)` (0.2.0-dev)

**Comment by afbjorklund** [comment]
There is a "real" 0.2.0 release of cri-dockerd now, needs some documentation changes for the new socket path.

https://github.com/Mirantis/cri-dockerd/releases

**Comment by afbjorklund** [comment]
It seems like dockershim is still in `crictl`:

> crictl by default connects on Unix to:
>
> - `unix:///var/run/dockershim.sock` or
> - `unix:///run/containerd/containerd.sock` or
> - `unix:///run/crio/crio.sock`

```go
var defaultRuntimeEndpoints = []string{"unix:///var/run/dockershim.sock", "unix:///run/containerd/containerd.sock", "unix:///run/crio/crio.sock"}
```

`WARN[0000] runtime connect using default endpoints: [unix:///var/run/dockershim.sock unix:///run/containerd/containerd.sock unix:///run/crio/crio.sock]. As the default settings are now deprecated, you should set the endpoint instead.`

Part of the new (for Docker users) cri-tools requirement...

**Comment by jyotimahapatra** [comment]
@mrbobbytables 👋 I'm in the release 1.24 bug triage team. Since this issue is marked as a release blocker , want to find out if this is a placeholder issue? Let me know how we could track the progress as we go deeper into the release timeline.

**Comment by afbjorklund** [comment]
Currently there are no (working) upstream instructions for how to install the CRI for containerd and for docker.

There are inline instructions for containerd (downloading from docker.com, **not** from containerd.io) and for CRI-O.
But for cri-dockerd, there are no inline instructions and the upstream instructions have a fatal typo (and no packages)

It's not blocking, but it's not ideal. You would want the Kubernetes page to either have good info or link to good info ?

----

https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#installing-runtime

https://kubernetes.io/docs/setup/production-environment/container-runtimes/

* https://github.com/containerd/containerd
  https://containerd.io/docs/getting-started/

* https://github.com/cri-o/cri-o
  https://cri-o.io/

* https://github.com/Mirantis/cri-dockerd
  https://docs.mirantis.com

**Comment by afbjorklund** [comment]
Adding a flag to `minikube`, to make it easier to test the new CRI with _any_ version of Kubernetes (since 1.20 or so):

```
minikube start --kubernetes-version=v1.24.0-alpha.2 --container-runtime=docker \
               --cri-socket=/var/run/cri-dockerd.sock --cri-service=cri-docker.service
```

Currently we are bundling the pre-release `cri-dockerd`, until there can be an official `v0.2.1` with the socket fixes.

cri-dockerd `v0.2.0-11-ga4d1895`
(https://github.com/Mirantis/cri-dockerd/commit/a4d1895a2659ea9974bd7528a706592ab8b74181)

**Comment by afbjorklund** [comment]
Some docs being added, for keeping "docker" runtime:

* https://github.com/kubernetes/website/issues/32129

**Comment by chrisnegus** [comment]
@mrbobbytables What is the endgame for closing this issue?

**Comment by afbjorklund** [comment]
Just realized that we are still using the "kubenet" CNI, and that it will be deleted along with the "dockershim" CRI...

* https://github.com/kubernetes/kubernetes/issues/100707

Need to add a similar change to minikube, to use CNI for _all_ container runtimes and remove Docker special case.

```go
        klog.Infof("CNI unnecessary in this configuration, recommending no CNI")
```

Maybe it should be mentioned in the migration docs (for docker) ?

I know that containerd and cri-o already adds /etc/cni/net.d files.

`/etc/cni/net.d/10-containerd-net.conflist`

`/etc/cni/net.d/cni/net.d/100-crio-bridge.conf`

**Comment by jyotimahapatra** [comment]
@afbjorklund can you help us with which documentation it could be suitable for. @nate-double-u this is a new ask around doc, wanted to make you familiar with the ask.

**Comment by afbjorklund** [comment]
@jyotimahapatra : I think for the migration docs it would be best to have it in PR https://github.com/kubernetes/website/issues/32131 (for https://github.com/kubernetes/website/issues/32129), for new installations I think that setting up CRI and CNI are a big part of those docs.

**Comment by reylejano** [comment]
Linking the Docs Dockershim Removal project board
https://github.com/orgs/kubernetes/projects/67

**Comment by afbjorklund** [comment]
Looks like "kubenet" is still available in cri-dockerd, maybe spoke too soon after reading those other issues...

Perhaps it wouldn't be a bad idea to start using CNI anyway, and use a "bridge" example like those other CR ?

**Comment by JamesLaverack** [comment]
Hey all.

As we approach the release for Kubernetes 1.24 (scheduled just under a month away on 19th April 2022), we're keeping track of this issue in the release team. Currently this is tracked as a release blocker, but after discussions with the SIG Docs team (cc @nate-double-u) we're under the impression that the docs are in a good enough ™️ state to no longer be blocking.

I'd like to get community feedback on removing the `release-blocker` label from this issue, in particular:

- Are [the docs](https://github.com/orgs/kubernetes/projects/67) in a state in which we'd be happy to release with, even if not everything was complete for the day?
- Is there anything else that we need to do for the Dockershim removal that would be a blocker for 1.24 if we didn't do it?

If people are happy, then I'll go ahead and remove the label.

**Comment by dims** [comment]
@justaugustus you had marked this release-blocker way back in December. Looks like we are in much better shape now. So we should remove the release-blocker tag. please revisit this when you get a chance (if you still think this is one).

@JamesLaverack +1 to remove `release-blocker`

**Comment by mrbobbytables** [comment]
I would also +1 removing `release-blocker`. The dockershim docs team has been doing a great job at shoring up the needed docs :)

**Comment by neolit123** [comment]
the decision seems up to release, but there are a number of open PRs (maybe some are not tracked in https://github.com/orgs/kubernetes/projects/67):

https://github.com/kubernetes/website/pull/30882
https://github.com/kubernetes/website/pull/32131

first one is rather important and has been in review since December.
without these merging prior to release there is potential of a flow of tickets logged in k/website and k/k.
as someone who does triage every week, i'd would like to avoid that...

**Comment by vsxen** [comment]
In addition, remove kubeadm check for `socat` & netfilter ?
```
	[ERROR FileContent--proc-sys-net-bridge-bridge-nf-call-iptables]: /proc/sys/net/bridge/bridge-nf-call-iptables does not exist
	[ERROR FileContent--proc-sys-net-ipv4-ip_forward]: /proc/sys/net/ipv4/ip_forward contents are not set to 1
```

**Comment by neolit123** [comment]
@vsxen are you sure these are dockershim only?
See the containerd docs https://kubernetes.io/docs/setup/production-environment/container-runtimes/#containerd

Also socat and iptables forwarding are different things, AFAIK. Happy to cleanup some if these checks but we need proof.

**Comment by vsxen** [comment]
I only find socat in there

https://github.com/kubernetes/kubernetes/blob/v1.23.0/pkg/kubelet/dockershim/docker_streaming_others.go#L44

for br_ netfilter it depends on which cni plugin you use, for example some cni plugin (cilium ovs) don't use bridge.

**Comment by dims** [comment]
removing `release-blocker`

**Comment by afbjorklund** [comment]
It seems the developer documentation for cri-dockerd gives just enough information to get started, but not to complete...

Missing some requirements like os version and go version, and missing the version linker flags that are provided by `make`

**Comment by ehashman** [comment]
/milestone clear
as this is not actionable for the 1.24 release

/lifecycle frozen
as we will want to continue collecting feedback for some time :)

**Comment by afbjorklund** [comment]
The docker runtime has now changed the default to "kubenet", which means that user needs to install CNI plugins.

`NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: could not locate kubenet required CNI plugins [bridge host-local loopback] at [\"/opt/cni/bin\" \"/opt/cni/bin\"]`

https://github.com/Mirantis/cri-dockerd/releases/tag/v0.2.4 (previously it would use the Docker network, by default)

**Comment by afbjorklund** [comment]
And now it is up to "cni" by default, and "no-op" by choice.

https://github.com/Mirantis/cri-dockerd/releases/tag/v0.2.5

**Comment by afbjorklund** [comment]
Now the docker removal is complete, since it was not supported in time for the (initial) 1.26 release.

It will probably be done retroactively in 1.27 timeframe, like how CNI was added retroactively with 1.25.
But the skeptics were right, and it would be better to move to the container runtime that is supported ?

Will look to nerdctl for picking up the ball, I would rather not resort to having to use the proprietary tools.

**Comment by dims** [comment]
It's been exactly a year. I am gonna close this now. please open fresh issues as needed in appropriate repositories.

/close
