### ISSUE TITLE
panic in TestCmdJoinConfig

### ISSUE THREAD

**Issue by songlh-psu** [kubernetes/kubernetes#107199]
### What happened?

Right now, `func TestCmdJoinConfig(t *testing.T)` cannot execute independently. If environment variable KUBEADM_PATH is not set, the unit test triggers a panic ([line 77](https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/test/cmd/util.go#L77)). 

Is it possible to build the kubeadm binary in the test and set KUBEADM_PATH accordingly? 

### What did you expect to happen?

`func TestCmdJoinConfig(t *testing.T)` executes independently. 

### How can we reproduce it (as minimally and precisely as possible)?

run TestCmdJoinConfig. 

### Kubernetes version

<details>

97d40890d00acf721ecabb8c9a6fec3b3234b74b and following versions

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by pacoxu** [comment]
It seems to be an intended panic for tests only. 
/area kubeadm

#89982 added this. 
```
Make getKubeadmPath() fetch the KUBEADM_PATH env. variable.
Panic if it's missing. Don't handle the "--kubeadm-path"
flag. Remove the same flag from the BUILD bazel test rule.

Don't handle "--kubeadm-cmd-skip" usage of this flag is missing
from the code base.

Remove usage of "kubeadmCmdSkip" as the flag "--kubeadm-cmd-skip"
is never passed.
```

https://github.com/kubernetes/kubernetes/blob/5b671d41c2fa89314eb9710dddd4f6a22c530952/hack/make-rules/test-cmd.sh#L169

**Comment by mk46** [comment]
Hi @songlh-psu, If still want to run the test from the local env.  
run `make WHAT=cmd/kubeadm` . It will generate kubeadm binary in `_output/bin` relative to k/k repo.
export KUBEADM_PATH and the test will run fine.

**Comment by songlh-psu** [comment]
@mk46 thanks a lot!

Linhai

**Comment by jlsong01** [comment]
/assign
I would like to take up this issue

**Comment by jlsong01** [comment]
@mk46 @pacoxu I am not sure if we need to fix this panic. Could you please give some guide?

In my opinion, unit test panic might not be friendly. We could fix it by check if KUBEADM_PATH is set or not. If not set, then just skip with some log indication.

**Comment by neolit123** [comment]
as mentioned above the panic is intended.

when running unit tests for /cmd/kubeadm/test (these are integration tests, not unit tests) the developer needs to pass the env variable because they might have multiple kubeadm binaries on disk. guessing what binary to test is not ideal...

eventually once kubeadm moves out of k/k it will have the test directory outside of the main app tree.
for the time being, we agreed to keep it under /cmd/kubeadm.

- you should run unit tests on /cmd/kubeadm/app
- run integration tests on /cmd/kubeadm/test and pass the variable with your kubeadm binary

i don't see what else we can do here.

**Comment by neolit123** [comment]
/close

closing for the time being.
