### ISSUE TITLE
kube-up lost connection while deploying

### ISSUE THREAD

**Issue by adyanthaya17** [kubernetes/kubernetes#10737]
Hi,
I'm unable to deploy the services and other functions on my node. I'm working on a single node, deploying master and minion on it.

kubernetes/cluster# KUBERNETES_PROVIDER=ubuntu ./kube-up.sh
Starting cluster using provider: ubuntu
... calling verify-prereqs
... calling kube-up
Deploying master and minion on machine 10.x.x.x

ubuntu@10.x.x.x's password:
ubuntu@10.x.x.x's password:
config-default.sh                  100% 2447     2.4KB/s   00:00                                    

Write failed: Broken pipe
lost connection

Could anyone point out what is going wrong, I have added the ssh-idenitity but still I'm unable to deploy.

**Comment by adyanthaya17** [comment]
The node I'm working on is on a openstack instance of image 12.04 ubuntu.

**Comment by goltermann** [comment]
We’re going through old support issues and asking everyone to direct your questions to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes). 

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases. 

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.
