### ISSUE TITLE
Non-trivial diff between staging and internal types.go

### ISSUE THREAD

**Issue by SergeyKanzhelev** [kubernetes/kubernetes#107442]
There is a non-trivial diff between [`staging/src/k8s.io/api/core/v1/types.go`](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/api/core/v1/types.go) and [`pkg/apis/core/types.go`](https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/core/types.go). 

1. Optional vs. non-optional int: `ServiceAccountTokenProjection.ExpirationSeconds`:
  `ExpirationSeconds int64` vs. `ExpirationSeconds *int64`
2. Optional vs. non-optional int: `ReplicationControllerSpec .Replicas`:
  `Replicas int32` vs. `Replicas *int32`
3. JSON vs Json in constant names:
    - `SecretTypeDockerConfigJson SecretType` vs. `SecretTypeDockerConfigJSON`
    - `DockerConfigJsonKey`  vs. `DockerConfigJSONKey`
4. `Secret. StringData` present in staging, but not present in internal file
5. `NodePIDPressure` as well as a few others are missing from internal (like `SecretVolumeSourceDefaultMode`, `ConfigMapVolumeSourceDefaultMode`, `ProjectedVolumeSourceDefaultMode`, etc.)

Some changes are expected. Like `DeprecatedServiceAccount` present in staging, but not present in internal. Same with `PodSpec.HostPID`, `PodSpec.HostIPC`, `PodSpec.HostNetwork`, `PodSpec.ShareProcessNamespace` and fields on `PodSecurityContext`. However presence of this mismatch raises the question how files consistency being validated. I couldn't find the test that was mentioned on the architecture code organization meeting last week (@dims, @liggitt).

/sig node
/sig architecture
/area code-organization
/kind cleanup

**Comment by dims** [comment]
cc @liggitt

**Comment by liggitt** [comment]
> Optional vs. non-optional int

This is intentional:
* allows versioned types to detect absence of a field and set a default value other than the zero value
* allows internal use to avoid needing to do nil checks on the field

Conversion code is generated between internal and external types, and is reviewed during API review. Non-convertible fields generated warning comments. Drift here would be caught by verify scripts showing unexpected diffs in generated conversion code.

> JSON vs Json in constant names

That's unintentional, but also unimportant (doesn't affect serialized data or conversion). It could be made consistent if we want.

> StringData present in staging, but not present in internal file

This is intentional. StringData is a weird feature that takes data in string format and converts it to []byte when converting to the internal type. Knowing what we know now, we wouldn't do this again. If another type tried to do this, it would be caught by verification scripts detecting a diff in the generated conversion files.

> NodePIDPressure as well as a few others are missing from internal (like SecretVolumeSourceDefaultMode, ConfigMapVolumeSourceDefaultMode, ProjectedVolumeSourceDefaultMode, etc.)

It doesn't look like these typedefs are actually used in API types.

**Comment by apelisse** [comment]
is there anything left to do here?

**Comment by dims** [comment]
let's close this out!

thanks,
dims
