### ISSUE TITLE
Outdated/confusing stuff in apiserver storage

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/kubernetes#107534]
While looking at `k/apiserver/pkg/storage` I noticed a few things.

1.  The parameter named `ptrToType` at https://github.com/kubernetes/apiserver/blob/56ff18e72e23862ac6fd0c6ddd57238be8324ba3/pkg/storage/interfaces.go#L237 has a misleading name.  The value of this parameter is not a pointer to a type; rather, it is an example instance of the type (if I understand correctly).
2. The example usage of GuaranteedUpdate in https://github.com/kubernetes/apiserver/blob/56ff18e72e23862ac6fd0c6ddd57238be8324ba3/pkg/storage/interfaces.go#L221-L235 is outdated --- it does not show the `cachedExistingObject runtime.Object` parameter.
3. The language at line 211, "or zero value in `ptrToType`", is confusingly ambiguous.  It could be that "zero value" is an imperative, meaning the given object will be side-effected to become the zero value.  Alternatively, "zero value" could be taken as a bit of additional information about what will be returned (in which case it would be clearer to write "the zero value").
4. The meaning of the phrase "If the object to update has the same value as previous" on line 212 is not clear to me.  What two values are being compared?
5. If "the object to update has the same value as previous" is trying to say that the update makes no change, then the consequence on line 213 ("will return the object in 'ptrToType' parameter") looks incorrect.
6. The implementation at https://github.com/kubernetes/apiserver/blob/56ff18e72e23862ac6fd0c6ddd57238be8324ba3/pkg/storage/etcd3/store.go#L312 uses the parameter name "out" instead of "ptrToType", but those two names do not look like things I would expect to have the same semantics.

**Comment by MikeSpreitzer** [comment]
@kubernetes/sig-api-machinery-misc

**Comment by MikeSpreitzer** [comment]
7. The func comment at https://github.com/kubernetes/apiserver/blob/56ff18e72e23862ac6fd0c6ddd57238be8324ba3/pkg/endpoints/handlers/patch.go#L516-L520 uses the wrong technique to quote parameter names.

**Comment by panzerox123** [comment]
Hey! So I looked through the code, and it seems that every implementation of the `GuaranteedUpdate` interface eventually passes the control to the `store` structure's implementation of the same, which converts the the `ptrToType` Object to a Pointer at https://github.com/kubernetes/apiserver/blob/56ff18e72e23862ac6fd0c6ddd57238be8324ba3/pkg/storage/etcd3/store.go#L317 . So I guess `ptrToType` variable name in the interface makes a little sense.

**Comment by aryan9600** [comment]
Terribly sorry for the inactivity on this. After trying to dig through the relevant code, here's what I understood. Still new to the codebase so please let me know if I'm mistaken anywhere.

* I agree with @panzerox123, that `ptrToType` does make sense. It's a pointer to a type as enforced [here](https://github.com/kubernetes/apiserver/blob/56ff18e72e23862ac6fd0c6ddd57238be8324ba3/pkg/storage/etcd3/store.go#L317).
* I think the explanation is clear regarding the usage of `cachedExistingObject`. To include the parameter in the example, it would need to be updated to show logic doing a read operation which it currently doesn't.
* Looking at the implementation of `GuaranteedUpdate` in `pkg/storage/etcd3/store.go`, it seems like we should change it to "the zero value" since we are calling `runtime.SetZeroValue` [here](https://github.com/kubernetes/apiserver/blob/56ff18e72e23862ac6fd0c6ddd57238be8324ba3/pkg/storage/etcd3/store.go#L846)
* I think what this means is that, if after calling `tryUpdate` on `ptrToType`, the `output` that's returned has the same value as the underlying object `ptrToType` is pointing to, then it will short circuit a write and just return the original object. 
* It looks correct to me. Please refer for this and the above point: https://github.com/kubernetes/apiserver/blob/56ff18e72e23862ac6fd0c6ddd57238be8324ba3/pkg/storage/etcd3/store.go#L397-L416
* The variable naming is definitely inconsistent and `out` should probably be renamed.

**Comment by MikeSpreitzer** [comment]
1. I agree, `ptrToType` holds a pointer --- but that's not the problem.  The question is, to what does the pointer point?  The name says that the pointer points to a type, but I suspect the truth is that the pointer points to an _instance_ of the _relevant type_.  In short, an "object" (in the jargon used elsewhere here) --- I mean, _of course_ it would be an object of the relevant type.  I think it would be more helpful if the name of this parameter says something about the role of this parameter in this function.  There is another parameter that is also typed as `runtime.Object`; it would be best if the name of the first such parameter contrasted helpfully with the name of the second such parameter.
2. I think we have agreement that the comment needs to be updated.
3. https://github.com/kubernetes/apiserver/blob/56ff18e72e23862ac6fd0c6ddd57238be8324ba3/pkg/storage/etcd3/store.go#L846 shows some object being side-effected to hold its zero value, so I suppose a clearer wording of line 211 might be something like "or the object in 'ptrToType' is set to its zero value otherwise".
4. So perhaps clearer wording for line 212 would be something like "If the eventual successful invocation of `tryUpdate` returns an `output` object with the same contents as `ptrToType`, it won't do any update"?  Or are we talking about a simple pointer comparison, so line 212 could say "If the eventual successful invocation of `tryUpdate` returns an `output` that is `== ptrToType`, it won't do any update"?  Actually, looking at the cited implementation at https://github.com/kubernetes/apiserver/blob/56ff18e72e23862ac6fd0c6ddd57238be8324ba3/pkg/storage/etcd3/store.go#L397-L416, I see a different comparison.  There I see a comparison of the serialized forms of the `input` and `output` in the successful invocation of `tryUpdate`.  So this would be mean that line 212 should say something like "If the eventual successful invocation of `tryUpdate` returns an `output` with the same serialized contents as `input`, it won't do any update".
5. So it looks like a clearer way to say line 213 would be something like "but will store those deserialized contents through the `ptrToType` parameter".
6. If the above is correct, then "out" says more about the first parameter's role than "ptrToType".  However, https://github.com/kubernetes/apiserver/blob/56ff18e72e23862ac6fd0c6ddd57238be8324ba3/pkg/storage/etcd3/store.go#L314 (and other lines like it) shows that the role of this parameter is _also_ to convey the name of the relevant type as input to the func.  I think a better way to explain this is to name the parameter "out" and add a comment that at call time it must already be initialized to refer to some object of the relevant type.
7. Nobody commented on this point, I think it still stands.

**Comment by lavalamp** [comment]
History: `ptrToType` smells like a variable name from before we had the runtime.Object type definition, the name was telling you what should be passed given the `interface{}` type. We have better enforcement now that things are passed as boxed pointers, so the name can probably be changed.
