### ISSUE TITLE
miss to return when listening channel closed

### ISSUE THREAD

**Issue by BugMakerPro** [kubernetes/kubernetes#107520]
https://github.com/kubernetes/kubernetes/blob/68e64ba52eb8518894ee62ef4240c9733f8c4346/cluster/images/etcd-version-monitor/etcd-version-monitor.go#L253

miss return ？

**Comment by neolit123** [comment]
https://github.com/kubernetes/kubernetes/blob/68e64ba52eb8518894ee62ef4240c9733f8c4346/cluster/images/etcd-version-monitor/OWNERS#L4

i don't know much about this tool. the owners file has api machinery.
/sig api-machinery

**Comment by jpbetz** [comment]
Looks like a bug to me. I would expected the stopCh case should return there.

**Comment by kerthcet** [comment]
/retitle miss to return when listening channel closed
/assign

**Comment by jpbetz** [comment]
> > Looks like a bug to me. I would expect the stopCh case to return.
> 
> nope, it was removed by this [pr](https://github.com/kubernetes/kubernetes/pull/87243)

That PR removes a break, which would be a noop (because a break terminates the execution of the innermost "for", "switch" or "select"). I agree the break should be removed because it doesn't do anything. But resuming the for loop when the goroutine has been signaled to stop seems like a bug. Return still seems right to me here.

**Comment by MadhavJivrajani** [comment]
/close
Fixed by https://github.com/kubernetes/kubernetes/pull/107542
