### ISSUE TITLE
4 of 5 zz_generated.openapi.go files are checked in - why?

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#107625]
Checked in:
staging/src/k8s.io/apiextensions-apiserver/pkg/generated/openapi/zz_generated.openapi.go
staging/src/k8s.io/code-generator/examples/apiserver/openapi/zz_generated.openapi.go
staging/src/k8s.io/kube-aggregator/pkg/generated/openapi/zz_generated.openapi.go
staging/src/k8s.io/sample-apiserver/pkg/generated/openapi/zz_generated.openapi.go

Not checked in:
pkg/generated/openapi/zz_generated.openapi.go

Can anyone explain why?

**Comment by liggitt** [comment]
ones outside k/k that are in libraries expected to be useful without running custom code generation steps are checked in

**Comment by liggitt** [comment]
example issue: https://github.com/kubernetes/kubernetes/issues/75338

there were similar issues with other instances

**Comment by thockin** [comment]
I guess I am asking why not check in pkg/generated/openapi/zz_generated.openapi.go

**Comment by liggitt** [comment]
oh, I'd be in favor of that :)

**Comment by dims** [comment]
downstream users very often end up realizing that we warn folks not to use k8s.io/kubernetes ( https://github.com/kubernetes/kubernetes#to-start-using-k8s ) because they go looking for why this file is not checked in. This paper cut makes people realize that they are doing something that we don't want them to do.

(not arguing for or against, just stating where this was effective before)

**Comment by liggitt** [comment]
I think the v0.0.0 local replace directives in go.mod accomplish similar things w.r.t. making people go digging about friction using k/k as a library
