### ISSUE TITLE
[Question] Autopilot creation results in two warnings

### ISSUE THREAD

**Issue by scheung38** [kubernetes/kubernetes#107889]
### What happened?

```
Cant' scale down a node because there's no place to move its Pods

Pod is blocking scale down because it’s a non-daemonset, non-mirrored, non-pdb-assigned kube-system pod

```

Why are we getting that?

Is this related to account quota exceeded the number of resources such as vCPU?

### What did you expect to happen?

2 gk3 nodes to be created 

gcloud container --project <PROJECT_ID> clusters create-auto <CLUSTERNAME> --region "europe-west2" --release-channel "rapid" --network "<PROJECT_ID>/global/networks/default" --subnetwork "<PROJECT_ID>/regions/europe-west2/subnetworks/default" --cluster-ipv4-cidr "/17" --services-ipv4-cidr "/22" --maintenance-window-start "2022-01-30T00:00:00Z" --maintenance-window-end "2022-01-31T00:00:00Z" --maintenance-window-recurrence "FREQ=WEEKLY;BYDAY=SA,SU"

### How can we reproduce it (as minimally and precisely as possible)?

From portal CLI command 

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>
GKE
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by nsspradeep** [comment]
@scheung38 These notifications in UI about failed scale down events about "Cant' scale down a node because there's no place to move its Pods" and "Pod is blocking scale down because it’s a non-daemonset, non-mirrored, non-pdb-assigned kube-system pod" are not relevant for autopilot clusters and are meant for standard GKE clusters. 

We are currently rolling out a fix that will avoid these notifications for autopilot clusters. For Autopilot clusters, once change is rolled out we will show only quota exceeded, ip space exhausted and service account deleted reasons for failed scaled up events as part of UI notifications.

We will update this issue once the fix is rolled out.

**Comment by liggitt** [comment]
Thanks for the info, @nsspradeep

Since this isn't tracking an issue with the Kubernetes components, I'll close this issue at this point
