### ISSUE TITLE
Kubeadm/kubeconfig: user should accept a in-cluster kubeadm config

### ISSUE THREAD

**Issue by ww3pl** [kubernetes/kubernetes#107844]
### What would you like to be added?

If possible, I'd love to see the option for `kubeadm kubeconfig user` to be able to use not only a kubeadm config file for the required `--config` flag, but also a ConfigMap directly from the cluster.

An alternative would be to specify in the Kubernetes docs how to easily find and/or generate such a kubeadm file to be passed into the command.

- [kubeadm config docs](https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-config/) mention only how to print configs for the `init` or `join` phase
- [kubeadm kubeconfig user docs](https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-kubeconfig/#cmd-kubeconfig-user) don't include any examples and/or information on how to obtain the kubeadm config file 

### Why is this needed?

Currently, to generate the kubeconfig for another user, a kubeadm config file has to be passed with the `--config` flag.

It seems that in default setups created with kubeadm, such config file doesn't exist on the filesystem (or at least the documentation does not include information about it). If that's the case, we have to output the kubeadm configuration from an in-cluster configmap into a file /just/ to be able to pass it to the `kubeadm kubeconfig user` command with the `--config` flag.

Considering [how important it is to not fallback to admin.conf if not needed, generating kubeconfigs for user instead](https://github.com/kubernetes/kubernetes/issues/98092#issuecomment-761848324), making it easier to create kubeconfigs would form a stronger deterrent from downloading the kubeconfig files just to get remote access to the cluster.

**Comment by neolit123** [comment]
hi,

> If possible, I'd love to see the option for kubeadm kubeconfig user to be able to use not only a kubeadm config file for the required --config flag, but also a ConfigMap directly from the cluster.

i don't think that is in scope of the command. the command's purpose is to generate a kubeconfig from state on disc, such as a CA and the kubeadm configuration file.

> kubeadm config docs mention only how to print configs for the init or join phase
> kubeadm kubeconfig user docs don't include any examples and/or information on how to obtain the kubeadm config file

the kubeadm configuration API documentation is linked from so many different locations...including the ones you've mentioned.

both the `init` and `join` pages have:
>> For more information on the fields and usage of the configuration you can navigate to our API reference page.

the kubeadm config page has:
>> For more information on using the kubeadm configuration API navigate to Customizing components with the kubeadm API.

i don't think those pages need changes.

having a minimal example for `kubeadm kubeconfig user` on this page about managing kubeadm certs would make more sense to me:
https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-certs/
the page seems like the best match because `kubeadm kubeconfig user` is about creating credentials.

if you think that makes sense, log an issue in kubernetes/website.
this repository is not for kubeadm tickets.

/close
/kind documentation

**Comment by neolit123** [comment]
xref https://github.com/kubernetes/website/issues/31575
