### ISSUE TITLE
EndpointSlice controller sync fails when Node is not found

### ISSUE THREAD

**Issue by robscott** [kubernetes/kubernetes#107927]
### What happened?

The following appears in EndpointSlice controller logs when a Node specified by `pod.spec.nodeName` is not present in the Node informer cache:

```
Error syncing endpoint slices for service "example/service", retrying: Error: node: "example-123" not found.
```

This is caused by  https://github.com/kubernetes/kubernetes/blob/baad1caee9dea68c6f9de9c14b23cfe6a96a80f8/pkg/controller/endpointslice/reconciler.go#L174-L177

Node is used to populate zone, without it, that field would be empty for a given endpoint:
https://github.com/kubernetes/kubernetes/blob/baad1caee9dea68c6f9de9c14b23cfe6a96a80f8/pkg/controller/endpointslice/utils.go#L73-L76

### What did you expect to happen?

I'm not sure. My biggest concern here is that the controller could potentially get stuck indefinitely for a single Service if one or more of the Pods was orphaned. I have not seen it get stuck indefinitely, but I have seen the controller get stuck on a Service for ~6 minutes for this reason.

None of the alternative options seem great here. Some options:

1. Drop endpoints that don't have a valid node in cache
2. Log but don't return error if node is not found, resulting in endpoints lacking a zone
3. Leave as is

With 1, we wouldn't retrigger the Service so may miss adding the node info back whenever it was available. We'd also risk dropping all endpoints if there was a bug in our Node informer cache. With 2, we would break topology hints (it bails out if one or more endpoints is missing zone) and any other implementation that relies on or expects zone to be present. With 3, we risk the controller getting stuck on a Service indefinitely if it keeps on including orphaned Pods.

So with that said, this may not be a bug, and there may not be anything better we can do here, I just wanted to open this up for broader discussion in case anyone else had run into something similar or had other approaches we could take.

### How can we reproduce it (as minimally and precisely as possible)?

Put a bogus value in `pod.spec.nodeName`.

### Kubernetes version

Applies to any running EndpointSlice controller, so likely 1.18+.

### Cloud provider

Any

### OS version

N/A

### Install tools

N/A

### Container runtime (CRI) and and version (if applicable)

N/A

### Related plugins (CNI, CSI, ...) and versions (if applicable)

N/A

**Comment by aojea** [comment]
heh, this is easy to repro with an unit test

> * Log but don't return error if node is not found, resulting in endpoints lacking a zone

Since the Node object is only required for topology, I think that is more resilient to log and keep going, in an edge case, a Service with one endpoint will not work at all ... Also, I see there is a handler for Node objects, so I think that when the Node event is received the controller will reconcile and set the topology information...

I thought in something like

```diff
diff --git a/pkg/controller/endpointslice/reconciler.go b/pkg/controller/endpointslice/reconciler.go
index 4756a0d3448..8aaab7b3a43 100644
--- a/pkg/controller/endpointslice/reconciler.go
+++ b/pkg/controller/endpointslice/reconciler.go
@@ -173,7 +173,7 @@ func (r *reconciler) reconcileByAddressType(service *corev1.Service, pods []*cor
 
                node, err := r.nodeLister.Get(pod.Spec.NodeName)
                if err != nil {
-                       return err
+                       klog.Warningf("Skipping topology information for pod %s: %v", pod.Namespace+"/"+pod.Name, err)
                }
                endpoint := podToEndpoint(pod, node, service, addressType)
                if len(endpoint.Addresses) > 0 {
diff --git a/pkg/controller/endpointslice/reconciler_test.go b/pkg/controller/endpointslice/reconciler_test.go
index 2e71419f352..b83ebedea63 100644
--- a/pkg/controller/endpointslice/reconciler_test.go
+++ b/pkg/controller/endpointslice/reconciler_test.go
@@ -460,6 +460,47 @@ func TestReconcile1Pod(t *testing.T) {
        }
 }
 
+// given an existing endpoint slice and 1 pods matching the service but no Node present on the informer cache
+// an slice should be created and log a message about the missing topology information
+func TestReconcileCreateEndpointSliceNodeMissing(t *testing.T) {
+       client := newClientset()
+       setupMetrics()
+       namespace := "test"
+       pods := []*corev1.Pod{newPod(1, namespace, true, 1, false)}
+       svc, _ := newServiceAndEndpointMeta("foo", namespace)
+
+       numActionsBefore := len(client.Actions())
+
+       r := newReconciler(client, []*corev1.Node{}, defaultMaxEndpointsPerSlice)
+       reconcileHelper(t, r, &svc, pods, []*discovery.EndpointSlice{}, time.Now())
+
+       assert.Len(t, client.Actions(), numActionsBefore+1, "Expected 1 additional clientset action")
+       actions := client.Actions()
+       assert.True(t, actions[numActionsBefore].Matches("create", "endpointslices"), "Action should be create endpoint slice")
+
+       slices := fetchEndpointSlices(t, client, namespace)
+
+       assert.Len(t, slices, 1, "Expected 1 endpoint slices")
+       assert.Regexp(t, "^"+svc.Name, slices[0].Name)
+       assert.Equal(t, svc.Name, slices[0].Labels[discovery.LabelServiceName])
+       protoTCP := corev1.ProtocolTCP
+       assert.EqualValues(t, []discovery.EndpointPort{{Name: utilpointer.StringPtr("foo"), Protocol: &protoTCP, Port: utilpointer.Int32Ptr(80)}}, slices[0].Ports)
+       expectedEndpoints := []discovery.Endpoint{{
+               Addresses:  []string{"1.2.3.5"},
+               Conditions: discovery.EndpointConditions{Ready: utilpointer.BoolPtr(true), Serving: utilpointer.BoolPtr(true), Terminating: utilpointer.BoolPtr(false)},
+               Zone:       nil,
+               NodeName:   utilpointer.StringPtr("node-1"),
+               TargetRef: &corev1.ObjectReference{
+                       Kind:      "Pod",
+                       Namespace: namespace,
+                       Name:      "pod1",
+               },
+       }}
+       assert.EqualValues(t, expectedEndpoints, slices[0].Endpoints)
+       expectTrackedGeneration(t, r.endpointSliceTracker, &slices[0], 1)
+       expectMetrics(t, expectedMetrics{desiredSlices: 1, actualSlices: 1, desiredEndpoints: 1, addedPerSync: 1, removedPerSync: 0, numCreated: 1, numUpdated: 0, numDeleted: 0, slicesChangedPerSync: 1})
+}
+
```


> The following appears in EndpointSlice controller logs when a Node specified by pod.spec.nodeName is not present in the Node informer cache:

that is a bit surprising, isn't it?  for the pod to be created there had to be a node :thinking: I wonder if we have something else here

**Comment by robscott** [comment]
>that is a bit surprising, isn't it? for the pod to be created there had to be a node 🤔 I wonder if we have something else here

Yes, very much so. It feels like a race condition, and I wouldn't have thought much of it until I saw a related incident. It seems like it can be triggered in a cluster with a sufficient combination of node and pod churn, which is very possible during a scale up or down. As one relatively concrete example, you can imagine that a Node deletion occurs before a Pod, but Pod GC controller has not cleaned up the Pod yet. It currently only takes _one_ of these Pods to fail the Service sync. If the Service is sufficiently large, and the scale up/down is long enough, the symptoms could repeat for a fairly long time.

The more I think about this, the more I think your suggested solution above is probably the best. My biggest concern is that we could potentially introduce incomplete data and then never resync once we had more complete data. For example, lets say we get a Pod before a Node and we leave the node info off the Slice, do we have a reliable way to ensure that we sync again if/when Node is added?

**Comment by aojea** [comment]
> The more I think about this, the more I think your suggested solution above is probably the best. My biggest concern is that we could potentially introduce incomplete data and then never resync once we had more complete data. For example, lets say we get a Pod before a Node and we leave the node info off the Slice, do we have a reliable way to ensure that we sync again if/when Node is added?

is not done by these handlers?

https://github.com/kubernetes/kubernetes/blob/7efc928dfa3ad88b5efa880eca5abe1be6550fd0/pkg/controller/endpointslice/endpointslice_controller.go#L516-L527

I honestly didn't go so deep, but is worth verifying and covering with an unit test that a node update/add fixes an endpoint with a pod that has no topology information

https://github.com/kubernetes/kubernetes/blob/084b28f6d58aaf82b9cc05d80232b31ce517c8c0/pkg/controller/endpointslice/topologycache/topologycache.go#L66-L68

**Comment by andrewsykim** [comment]
(re-posting here from the sig-network call today)

Is it an option to returned a specific error in `reconcileByAddressType` for this case and return a requeue error with a shorter duration for the workqueue?

**Comment by aojea** [comment]
more food for thought: 
- a pod can not be created  if a Node didn't exist before
- if we know that a Node has been deleted, we know that the pods referencing that node will eventually disappear and they are invalid

**Comment by robscott** [comment]
>Is it an option to returned a specific error in reconcileByAddressType for this case and return a requeue error with a shorter duration for the workqueue?

Although that might help, the specific incident I observed actually resulted in the controller exceeding the max retries after the exponential backoff and dropping from the queue.

>a pod can not be created if a Node didn't exist before

Maybe true to say that a Pod can not be scheduled if a node matching `spec.nodeName` hasn't existed before, but I think it could still exist.

>if we know that a Node has been deleted, we know that the pods referencing that node will eventually disappear and they are invalid

Although that would simplify a lot, I don't think it's safe to assume that a node missing from the informer cache has been deleted.

**Comment by andrewsykim** [comment]
> Although that might help, the specific incident I observed actually resulted in the controller exceeding the max retries after the exponential backoff and dropping from the queue.

Ah gotcha, but the retry is implemented inside endpointslice controller and not specific to the way workqueue is implemented generically:

https://github.com/kubernetes/kubernetes/blob/f24d917d3c69a4b08cee99148e74bbda74614601/pkg/controller/endpointslice/endpointslice_controller.go#L297-L314

So if we did have a specific error to check we can check it in `handleErr` and not count it towards the max retries. Although after talking through it out loud, I can see that being dangerous too because it seems possible that we could end up re-queuing some Services forever

**Comment by aojea** [comment]
> Although that would simplify a lot, I don't think it's safe to assume that a node missing from the informer cache has been deleted.

yeah, I´m not mean missing, I meant deleted :)

https://github.com/kubernetes/kubernetes/blob/f24d917d3c69a4b08cee99148e74bbda74614601/pkg/controller/endpointslice/endpointslice_controller.go#L529-L531

**Comment by robscott** [comment]
>yeah, I did not mean missing, I meant deleted :)

But how do we know that a deleted node name won't be reused? Anything we do here around Node state seems like it would involve making unsafe assumptions.

**Comment by robscott** [comment]
>So if we did have a specific error to check we can check it in handleErr and not count it towards the max retries. Although after talking through it out loud, I can see that being dangerous too because it seems possible that we could end up re-queuing some Services forever

I'd actually gone down a very similar path for other forms of error handling previously, but yeah, the possibility of an infinite backoff/sync loop due to invalid data is not ideal.

**Comment by aojea** [comment]
> But how do we know that a deleted node name won't be reused? Anything we do here around Node state seems like it would involve making unsafe assumptions.

yeah, that is right, I didn't think carefully about that

**Comment by khenidak** [comment]
prologue:

- There are legitimate situations where a pod may no have node assigned. An example: Before scheduling pods won't have this field set, this can go longer if the scheduler is down. Among other things I can think of that lead to this situation is node object delete (scale down) without deleting the pods assigned to it or in place node repave+replace.

- As discussed yesterday I purpose to separate the two discussions as the following: 
  - a _networking fubar_ situation where the watchers in controller manager just stopped working. I don't think controllers should be built to handle that instead we should shift focus to go-client/api-server relationship. The simplest workaround is to have api-server spitting a keep-alive style responses on when `time-since-last-event > interval`. think of a watch event that looks like `{}` that go client observes and does not bubble up to call back hooks.  Then maybe go-client later can surface `OnDeadWatch()` similar to `OnAdd(), OnUpdate(), OnDelete()` hooks allowing controllers to make informed decisions to either panic and bailout completely or restart the watch sequence. Whatever the approach we shouldn't do stuff like each controller relying on time since last updated or other means, it will get complicated, opinionated and rather redundant quickly.  
  -   A logical error such as the one described by @robscott above. e.g., a controller that has multi dependency (node, pods, endpoints) where one or more of the needed objects are not in cache, or not set by another controller.



Having the above in mind means that this situation should (or rather would happen) *if and only if* scheduler is down, or watcher are racy and we are yet to see the node in our lister cache (second entry above). It is entirely legitimate that two watchers originating from same client hit two different api-servers servers, one of which is over burdened by other clients.  fwiw if the node is not in controller manager shared cache then it also means that node related controllers don't see it as well, something to consider when thinking about that. Keep in mind that controller manager is all or none, meaning either all controllers run or none at all (because lead lease is held by another instance).

That leaves us with:
1. There is no node assigned yet to pod (`pod.Spec.NodeName == ""`) => does not matter because pod will not have IPs.
2. There is a node assigned but we can not find it in lister => 
 --> Pod GC will eventually collect these pod. if the entire CM is down then the entire cluster is influx state of partially broken. if GC does not kick in then these pods will blackhole all traffic going to them anyway (client side retrials helps here).
 --> Node will eventually show up => we should re-queue the pod for later reconciliation. and maybe log if failed to find node for x reconciliation attempts. But we will have always retry it until pod disappears or node appears.

**Comment by smarterclayton** [comment]
All controllers are out of date.  Kube is a distributed system, you are downstream of the truth, and you can never see the truth as it is now, only the truth as it was some time in the past (which for various reasons may be much much more than seconds).

> I'd actually gone down a very similar path for other forms of error handling previously, but yeah, the possibility of an infinite backoff/sync loop due to invalid data is not ideal.

In general, you ALWAYS need to retry everything when you are "downstream of the truth" situation forever.  Reconcile means "I'm not in charge, I just need to do my best to converge to the desired state as efficiently as possible".  A replication controller, attempting to create a pod in a namespace that has a full pod quota, must retry forever.  It does that efficiently by backing off, but retry forever is a valid strategy.  It's important never to "give up" unless your domain model allows "giving up" (scheduling can't give up, but the node can end a pod's life with a single patch command, but as a consequence EVERY client that reacts to pods has to deal with the fact that a pod could be killed at any time).  

> It feels like a race condition, and I wouldn't have thought much of it until I saw a related incident. It seems like it can be triggered in a cluster with a sufficient combination of node and pod churn, which is very possible during a scale up or down. 

It's worse.  There is no ordering you can assume between multiple clients, of any distributed system, ever, that isn't provided by the distributed system.  Also, because anything can be delayed forever (which includes watches, informers, processes, CPUs, etc) the best you can do is converge.  Kube's model tricks you into believing these things don't happen, but they do (we've discussed injecting arbitrary 10-15s delays in watches in production to help people realize this and unbreak their controllers.

> if we know that a Node has been deleted, we know that the pods referencing that node will eventually disappear and they are invalid

Unfortunately no client can ever really guarantee this.  You just have to work with the data you have, and if new data comes in, efficiently incorporate that data and react.  If your three caches say "this pod doesn't have an endpoint" at the current time you look at the caches, don't show the endpoint.  It's another components responsibility to handle the invariants of deleting the pod or deleting the node (sometimes it's a human, who can take O(months) to solve it).  You should just focus on treating the data you have as truth, minimizing the cost of reacting, and *occasionally* we put in affordances that make ourselves less choppy (i.e. we smooth out certain transient flips, or anticipate that if we see X we should see Y in a few seconds, so we retry looking for Y a bit more aggressively).

Your controller should as much as possible be designed to "take events from your different sources and trigger reconciliation if any of them have changed".  I.e., if you have Pods, Nodes, and Services as input, you want to make your reconciliation being a function like "given current state of this (pod,node,service), check what the correct output is", and have each event trigger that function.  Making that fast is a challenge, but it's much much easier to test in isolation.

**Comment by aojea** [comment]
>  It is entirely legitimate that two watchers originating from same client hit two different api-servers servers, one of which is over burdened by other clients. 

since https://github.com/kubernetes/kubernetes/pull/105490 all watchers from the same client use the same TCP connection, they can not hit different api servers if they are using http2 (that is the default)

**Comment by robscott** [comment]
Thanks for the great discussion here! I agree with @smarterclayton and @khenidak on all points, especially that this could be triggered for a wide variety of reasons, and that the EndpointSlice controller should likely retry indefinitely. It can use the same exponential backoff, just without a retry limit.

What I'm stuck on is how we handle the partially valid state in the meantime. Even if we retried indefinitely, invalid data would prevent the controller from updating slices for the associated Service with the current state. It seems plausible that by the time one `pod.spec.nodeName` was resolved, another Pod for the same Service could end up with the same problem. Or some other failure in the system, or intentional misconfiguration, could lead to unexpected/invalid references.

So when we get invalid data, or references that we can't resolve, we should always trigger a retry, but it seems like we should also do one of the following so we're not blocking updates forever:

1. Drop endpoints that have a missing node, as long as we're leaving a portion of endpoints in place. We would need to guard against invalid data causing us to drop all endpoints, this seems rather error prone though.
2. Drop node information from endpoints wherever we can't resolve it. I think this is the cleanest and simplest solution, as shown by @aojea in https://github.com/kubernetes/kubernetes/issues/107927#issuecomment-1028781396. 

With that said, both of the above options come with the potential to introduce new bugs, so open to alternatives here.

**Comment by khenidak** [comment]
@robscott the controller must get actual state of the system to the desired state of the system. We can make some sane assumptions e.g. if lost the entire desired state we can assume that something is up and wait a little (i think Tim described something similar in our discussion). But that does not apply on partial state because we simple don't know what happened and we can not tell for sure that last applied desired state is still valid. with this in mind: Pod that has no node is _invalid_ in endpoint list, so it must be dropped from endpoint list. 

IOW let us shift the discussion to "what is a valid pod for an endpoint, it must have an IP, ready (optional with override readiness settings in svc), have a node in our _local node list_, what else? Once we have that, we can make an assumptions such as pods that are invalid because they don't have IP/node assigned then it is likely that they will shortly hence retry them on short interval.

**Comment by khenidak** [comment]
> > It is entirely legitimate that two watchers originating from same client hit two different api-servers servers, one of which is over burdened by other clients.
> 
> since #105490 all watchers from the same client use the same TCP connection, they can not hit different api servers if they are using http2 (that is the default)

I understand the assertion you are making, but i disagree. Go's transport itself is a connection pooled transport, unless we use a custom transport? we *do* want pooled connections simply because a busy client with a single upstream connection can easily overrun socket buffers on both sides.

**Comment by aojea** [comment]
that is how golang http2 is implemented, there is a connection pool, if the host:port connection is in the pool, it is reused, you can not have 2 TCP connections to the same host:port using the standard library, you have to use a custom transport https://github.com/kubernetes/enhancements/pull/3034 ... but better to not hijack this issue ;)

**Comment by liggitt** [comment]
> that is how golang http2 is implemented, there is a connection pool, if the host:port connection is in the pool, it is reused, you can not have 2 TCP connections to the same host:port using the standard library

fwiw, that doesn't match the data structured used by the http2 client pool, which is a map of host:port to a *list* of connections: https://github.com/golang/net/blob/cd36cc0744dd695657988f15f08446dc81e16efc/http2/client_conn_pool.go#L48

**Comment by liggitt** [comment]
if a single http2 connection reaches max_concurrent_streams, new connections to the same host can be dialed:

https://github.com/golang/net/blob/cd36cc0744dd695657988f15f08446dc81e16efc/http2/transport.go#L868-L876

**Comment by aojea** [comment]
(bear in mind I'm not a golang developer and this may be wrong, but so far is what I found in this area)
I'm assuming we want multiple TCP connections with multiple streams each, to the same host port. You can have one TCP connection per request without multiplexing, but that sounds highly ineffective. See related issues

https://github.com/golang/go/issues/37373
https://github.com/golang/go/issues/23427

> if a single http2 connection reaches max_concurrent_streams, new connections to the same host can be dialed:

specially this one 
https://github.com/golang/go/issues/34511

> fwiw, that doesn't match the data structured used by the http2 client pool, which is a map of host:port to a list of connections: https://github.com/golang/net/blob/cd36cc0744dd695657988f15f08446dc81e16efc/http2/client_conn_pool.go#L48

The http implementation in golang is a bit complex, the development is done in net/http2 and the code is bundled into the standard library and have some flue part

The connection pool you use from the standard library is the `noDialClientConnPool`

https://github.com/golang/net/blob/cd36cc0744dd695657988f15f08446dc81e16efc/http2/client_conn_pool.go#L278-L281
https://github.com/golang/net/blob/cd36cc0744dd695657988f15f08446dc81e16efc/http2/transport.go#L195

and the logic to get the connection is this one, that reuses the connections from the pool 

https://github.com/golang/go/blob/1fe8f47cc39aec39fca3e6f367a7c1c7b254014f/src/net/http/transport.go#L577-L590

**Comment by aojea** [comment]
> max_concurrent_streams

bear in mind that is an option to announce to the peer

> > A peer can limit the number of concurrently active streams using the
>    SETTINGS_MAX_CONCURRENT_STREAMS parameter (see [Section 6.5.2](https://datatracker.ietf.org/doc/html/rfc7540#section-6.5.2)) within
>    a SETTINGS frame.  The maximum concurrent streams setting is specific
>    to each endpoint and applies only to the peer that receives the
>    setting.  That is, clients specify the maximum number of concurrent
>    streams the server can initiate, and servers specify the maximum
>    number of concurrent streams the client can initiate.
>

**Comment by aojea** [comment]
/assign

I think we can do better, before listing the nodes the function `ShouldPodBeInEndpointSlice` checks that the Pod has IPs, so we know that the Node already existed and simplifies the scenario we are  handling.

The PodGC will check if there are orphan nodes and delete them, but the node can go missing and come back, ... I'm testing these corner cases , will send a PR once I have them covered so you can review

**Comment by aojea** [comment]
@robscott do we close it?

**Comment by robscott** [comment]
@aojea I think we likely still need some work on this, though I don't think it's urgent. Will leave it open for now.

/assign

**Comment by aojea** [comment]
/unassign
Sounds good, all yours :)

**Comment by aojea** [comment]
> 1. Drop endpoints that have a missing node, as long as we're leaving a portion of endpoints in place. We would need to guard against invalid data causing us to drop all endpoints, this seems rather error prone though.

@robscott I think current behavior is correct, is other controllers business to reconcile the pod and node, the slice controller just  follows that infor and retries as Clayton and Khal says

should we close as "working as expected" ?

**Comment by robscott** [comment]
@aojea I think this is much less risky now that https://github.com/kubernetes/kubernetes/pull/110255 has merged. Combined with the Kubelet bug, a terminal Pod on a no longer existing preemptible VM EndpointSlice updates could have gotten stuck indefinitely. Of course that specific bug has been resolved, but I'm nervous about other edge cases where a Pod sticks around referencing an invalid/no longer existing node and causes all EndpointSlice reconcile loops that would reference that Pod to fail.

**Comment by robscott** [comment]
The more I think about this, the more I think this is the correct option:

> Drop endpoints that have a missing node, as long as we're leaving a portion of endpoints in place. We would need to guard against invalid data causing us to drop all endpoints.

**Comment by aojea** [comment]
> Pod sticks around referencing an invalid/no longer existing node and causes all EndpointSlice reconcile loops that would reference that Pod to fail.

that should be a bug in the pod garbage collector, no? we should assue that the other controllers do their job

**Comment by robscott** [comment]
> that should be a bug in the pod garbage collector, no? 

I think there are some exceptions where pod garbage collection does not happen immediately (cc @bobbypage).

> we should assume that the other controllers do their job

In an ideal world, every part of the system would have well defined and regularly tested contracts. Until that exists (and maybe even after) defense in depth seems like a good idea.

**Comment by aojea** [comment]
@robscott https://github.com/kubernetes/kubernetes/pull/110639
There were also 2 sublte bugs :upside_down_face:

**Comment by bobbypage** [comment]
> I think there are some exceptions where pod garbage collection does not happen immediately (cc @bobbypage).
> 
> >

pod garbage collection does not happen immediately - it will only run the when [threshold is reached](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/podgc/gc_controller.go#L189-L209) -  `terminatedPodThreshold`. This defaults to `12500` in kube-controller-manager today. Pod GC will also happen for bounds which are bound to a node object which no longer exists.
