### ISSUE TITLE
Cannot Allocate Memory causes RC to not continue to try to spin up nodes

### ISSUE THREAD

**Issue by aronchick** [kubernetes/kubernetes#10793]
What would cause this?

```
$ cluster/kubectl.sh describe po client-purple-g0t89
Name:				client-purple-g0t89
Image(s):			gcr.io/linear-pointer-95422/client_image:v2.0.0
Node:				ip-172-20-0-10.us-west-2.compute.internal/172.20.0.10
Labels:				name=client,version=v2.0.0
Status:				Pending
Reason:
Message:
IP:
Replication Controllers:	client-purple (2/2 replicas created)
Containers:
  client:
    Image:	gcr.io/linear-pointer-95422/client_image:v2.0.0
    Limits:
      cpu:		100m
    State:		Waiting
      Reason:		Image: gcr.io/linear-pointer-95422/client_image:v2.0.0 is ready, container is creating
    Ready:		False
    Restart Count:	0
Conditions:
  Type		Status
  Ready 	False
Events:
  FirstSeen				LastSeen			Count	From							SubobjectPath	Reason		Message
  Mon, 06 Jul 2015 16:58:01 -0700	Mon, 06 Jul 2015 16:58:01 -0700	1	{scheduler }								scheduled	Successfully assigned client-purple-g0t89 to ip-172-20-0-10.us-west-2.compute.internal
  Mon, 06 Jul 2015 16:57:56 -0700	Mon, 06 Jul 2015 16:59:06 -0700	8	{kubelet ip-172-20-0-10.us-west-2.compute.internal}			failedMount	Unable to mount volumes for pod "client-purple-g0t89_default": fork/exec /bin/mount: cannot allocate memory
  Mon, 06 Jul 2015 16:57:56 -0700	Mon, 06 Jul 2015 16:59:06 -0700	8	{kubelet ip-172-20-0-10.us-west-2.compute.internal}			failedSync	Error syncing pod, skipping: fork/exec /bin/mount: cannot allocate memory
```

This container is running properly on other nodes. As a result, my cluster is out of alignment (only one replica has been created, when 2 are required) but this is permanently stuck.

The exact same cluster works fine on GCE, it appears it's only on AWS.

**Comment by lavalamp** [comment]
What else is running on that node? Do you have resource values on the pod's containers?

**Comment by aronchick** [comment]
The odd part is that these nodes just finished running these very
containers. I'm using the default t2.micros, so I'm increasing it to
m3.mediums to see what happens.

**Comment by goltermann** [comment]
We’re going through old support issues and asking everyone to direct your questions to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes). 

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases. 

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.
