### ISSUE TITLE
Docker 1.7.0 auth login support broken

### ISSUE THREAD

**Issue by satnam6502** [kubernetes/kubernetes#10807]
As explained in #10801 we have an issue with docker auth login. We need to update:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/credentialprovider/config.go

Perhaps @mattmoor could kindly add more details?
Thank you.
@dchen1107  @davidopp

**Comment by mattmoor** [comment]
Yes, Docker 1.7.0 now reads credentials from the `auths` field of `~/.docker/config.json`.

For (partial) back-compat, they read the new file (if present), and otherwise read the old file (if present).

I believe the best implementation for the Kubelet is to provider another default `credentialprovider`, which provides the entries from `~/.docker/config.json` to the Keyring, as we do for `~/.dockercfg`


Here is the relevant file/line: https://github.com/docker/docker/blob/04c6f09fbdf60c7765cc4cb78883faaa9d971fa5/cliconfig/config.go#L64

**Comment by satnam6502** [comment]
@thockin @lavalamp @quinton-hoole  what do we think about this re: V1.0 ?
Is this a significant usability issue that we should address it?
The fix seems low-ish risk?

**Comment by mattmoor** [comment]
FWIW, if you don't fix it, then using "docker login" on Nodes to pull private images goes out the window when you upgrade to 1.7.0+, which presumably you will.

**Comment by dchen1107** [comment]
Here is my personal opinion: we should fix this asap, but it is not a 1.0 blocker. We are planning to release 1.0 with docker 1.6.2 by default, and later upgrade to docker 1.7.X.

**Comment by mattmoor** [comment]
@dchen1107 SGTM

**Comment by lavalamp** [comment]
We'd also need to make sure pull secrets work with docker 1.7.X before upgrading.

**Comment by quinton-hoole** [comment]
@dchen1107 I agree.

**Comment by yujuhong** [comment]
Obsolete.
