### ISSUE TITLE
shm size show inconsistently in the pod

### ISSUE THREAD

**Issue by YesterdayxD** [kubernetes/kubernetes#108291]
I set this in yaml file
```
Volumes:
  shm:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     Memory
    SizeLimit:  4Gi

```
but I got this in pod
```
shm                                                        32G     0   32G   0% /dev/shm
```
and my host memory size is 64G

**Comment by pacoxu** [comment]
/sig node

As you discovered, the sizeLimit parameter set for emptyDir volume could not be used for creating a volume with the size. Instead what it does it that eviction manager keeps monitoring the disk space used by pod emptyDir volume and it will evict pods when the usage exceeds the limit.

See https://github.com/kubernetes/kubernetes/issues/63126?spm=a2c65.11461447.0.0.37da3505iMDJ3A#issuecomment-387817170.

**Comment by YesterdayxD** [comment]
@pacoxu 
I read [https://github.com/kubernetes/kubernetes/issues/63126](url) and [https://github.com/kubernetes/kubernetes/pull/94444](url)
I test that pod will be evicted if pod usage exceeds the limit. And in the pods, type df -h command shows /dev/shm size is equal to half of host memory .Is it a right condition?

**Comment by pacoxu** [comment]
It is possible because the default behavior is that kubelet uses `du` to check emptyDir size and it is a `soft` limit because it will be evicted once kubelet checked the empty dir size is over the limitation. The default volume stats checking interval is 1m. If there are too many small files in the empty dir, it's possible the du will hang or cost a lot of time and the eviction will happen later. 

A solution for this would be to use https://github.com/kubernetes/enhancements/issues/1029 feature gate LocalStorageCapacityIsolationFSQuotaMonitoring which will use quota to calculate the volume disk usage by xfs_quota which is more quickly than `du`. Before enabling LocalStorageCapacityIsolationFSQuotaMonitoring, you may try a test case in https://github.com/kubernetes/enhancements/issues/1029#issuecomment-1000134682 which can simulate a 2GB-limit empty dir and create many files in it. Or just run `time du -clsh` in your testing pod to check how long will it take.
