### ISSUE TITLE
APIServer: Impose optional maximum limit on etcd range queries

### ISSUE THREAD

**Issue by chaochn47** [kubernetes/kubernetes#108258]
### What would you like to be added?

Modify [apiserver/blob/master/pkg/storage/etcd3/store.go list](https://github.com/kubernetes/apiserver/blob/master/pkg/storage/etcd3/store.go#L565-L576) to apply a maximum limit to every etcd range request and issue multiple range requests if necessary to satisfy the original list. Using the ResourceVersion that comes back from the first range request from etcd (or the one user provided) on later requests to ensure a consistent snapshot of resource collections. Here is the drafted [PR](https://github.com/chaochn47/kubernetes/pull/2) for the changes. 

The maximum limit will be a kube-apiserver cmd option. Default value is `0` which means unlimited (It's the current behavior). We will experiment internally with `500` limit in the design first phase like [client-go/tools/pager: const defaultPageSize = 500](https://github.com/kubernetes/client-go/blob/master/tools/pager/pager.go#L31)

The maximum limit will be applied to each resource type. 

### Why is this needed?

The main purpose is to protect etcd from out of memory and prevent its cascading APIServer failures like re-creating gRPC connections to etcd, rebuild all caches and resume internal reconciler which can be expensive. 

[APIListChunking](https://kubernetes.io/docs/reference/using-api/api-concepts/#retrieving-large-results-sets-in-chunks) should be in effect in most APIServer set up, `client-go/tools/pager` and `client-go/informers` are good libraries to use and they follows the pagination rule of thumb to reduce server load. However, there are still some native clients calling server without any limit to get a full list of resource. This created a lot of memory pressure on etcd. 

Carveat
- Setting the maximum limit too low will increase the total round-trip time between APIServer and etcd to breach the default 1 minute request time. This will probably cause APIServer cancelled the client requests prematurely. https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/ > `--request-timeout duration     Default: 1m0s`
  - We will explore fifo queue to process the list requests, one goroutine to split the request into multiple pages and get the response from etcd. Another goroutine to consume the etcd response and deserialize the response into k8s objects. 
  - Please drop any concerns and comments on this, thanks!

**Comment by chaochn47** [comment]
/sig api-machinery
/sig scalability

@kubernetes/sig-scalability @wojtek-t @smarterclayton @anguslees @shyamjvs @geetasg

**Comment by wojtek-t** [comment]
> Here is the drafted [PR](https://github.com/chaochn47/kubernetes/pull/1/files) for the changes.

We already support pagination. Instead of adding a second implementation for pagination, we should reuse the existing one (or at the very least refactor it to ensure that we end up with just one implementation):
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/storage/etcd3/store.go#L686


> The maximum limit will be applied to each resource type.

What might be useful to consider is to allow specifying a per-resource-type limit.
Or maybe I take it back, as it will be hard for most operators to configure. So a better option could be something like "initial limit", but based on the statistic apiserver would be able to adjust it (e.g. if the request was very fast, kube-apiserver can exponentially increase the limit or sth).

**Comment by enj** [comment]
Is there a KEP for this?  I would expect such a change to have an associated KEP to define any configuration, feature flags, lifecycle, design, etc.

**Comment by chaochn47** [comment]
@enj, thanks for the reminder. It is still in early stage. We will create a KEP for this by following https://github.com/kubernetes/enhancements/blob/master/keps/README.md

**Comment by anguslees** [comment]
@mborsz I think you're suggesting that we should consider increasing apiserver --request-timeout default?  Or at least, ensure --request-timeout default, this range limit, and an expected time to fetch a page from etcd all make sense together.  (Great point!)

I feel like whatever we do, there's always a legitimate-but-pathological query that a client can construct that will take a long time - your large inefficient (with the way apiserver/etcd works) fieldSelector query is a great example.  Afaics, we can either fail (not very useful), rebuild the cluster with bigger/faster hardware, or take longer.

Hrm.  _Theoretically_ there's no reason this proposal needs to take a lot longer.  We could issue multiple page requests and avoid sequential network round trips for example - indeed it could even be faster because the query would run across multiple etcd instances and deserialisation would happen in parallel.  Unfortunately, etcd doesn't _queue_ requests atm afaics and instead just executes them all in parallel, so a naive version of this risks overloading etcd again.

**Comment by chaochn47** [comment]
Any thoughts on this proposal? @ptabor from your comment on https://github.com/kubernetes/kubernetes/pull/94303#issuecomment-773174456

> With the unexpectedly huge gain from splitting big etcd transactions (leases) into smaller (1000 objects) in https://github.com/kubernetes/kubernetes/pull/98257, I think it's important to explore splitting the big range scans.

> From etcd perspective I expect:

>    1. lower RAM consumption / possibility of OOM.
>    2. lower tail latency.
>    3. (so) possibility to define stricter SLOs. E.g. reads>10000 entries might get excluded from SLO.
>    4. lower fragmentation of the DB (shorter bolt transactions)
