### ISSUE TITLE
test/e2e: use framework helpers to create namespaces

### ISSUE THREAD

**Issue by s-urbaniak** [kubernetes/kubernetes#108298]
### What would you like to be added?

Currently, some e2e tests do not use central framework helper methods to create namespaces. Examples:

https://github.com/kubernetes/kubernetes/blob/296bf4f01668374ade252a751d4c3567917b9890/test/e2e/apimachinery/webhook.go#L1532
https://github.com/kubernetes/kubernetes/blob/296bf4f01668374ade252a751d4c3567917b9890/test/e2e/apimachinery/webhook.go#L2370-L2375
https://github.com/kubernetes/kubernetes/blob/296bf4f01668374ade252a751d4c3567917b9890/test/e2e/network/netpol/kubemanager.go#L178

The fix is to use https://github.com/kubernetes/kubernetes/blob/296bf4f01668374ade252a751d4c3567917b9890/test/e2e/framework/framework.go#L519 instead.

### Why is this needed?

This makes maintanance of e2e tests hard as enforcement settings (like pod security admission) is not centralized

**Comment by kapiljain1989** [comment]
@s-urbaniak Are you working on it? 
I am new for k8s contribution, is it good issue to start with?

**Comment by s-urbaniak** [comment]
@kapiljain1989 sure thing, once https://github.com/kubernetes/kubernetes/pull/106454 is finally merged, you are welcome to contribute :-)

**Comment by antoninbas** [comment]
I'm running into an issue because of this. When running netpol e2e tests on GKE, the tests actually fail because the default ServiceAccount for the test namespaces take too long to be created, and unlike the framework helpers, the netpol-specific helpers for Namespace creation do NOT wait for ServiceAccount creation. After creating the Namespace, the netpol tests immediately try to create Pods in the Namespace, which fail as the ServiceAccount does not exist yet. We only observe this issue on GKE clusters, but this is not specific to GKE in itself.

See https://github.com/antrea-io/antrea/issues/3762

**Comment by astoycos** [comment]
We've run into this issue as well in OCP see https://github.com/openshift/origin/pull/26775

**Comment by antoninbas** [comment]
@astoycos I already have a PR for this: https://github.com/kubernetes/kubernetes/pull/111789. It's pretty comprehensive, as when I started working on this, I realized there were several things that needed fixing in the netpol tests.

**Comment by astoycos** [comment]
Ah sweet no worries thanks @antoninbas!!
