### ISSUE TITLE
kubectl run misdiagnoses extra arg

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#10838]
I mixed up `kubectl run` and `docker run` and got a bad error:

```
$ kubectl run busybox --image=busybox sleep 1000000
error: NAME is required for run
see 'kubectl run -h' for help.
```

Clearly I specified the name.

First, useless error.  Second, we should support syntax like this to run a specific command.

**Comment by bgrant0607** [comment]
cc @feihujiang

**Comment by feihujiang** [comment]
$ kubectl run busybox --image=busybox --command sleep 1000000 is accepted now, the result is: 
replicationcontroller "busybox " created

command flag is a bool type, default is false, "If true and extra arguments are present, use them as the 'command' field in the container, rather than the 'args' field which is the default."

@thockin  @bgrant0607 I think this could be closed.

**Comment by bgrant0607** [comment]
Thanks

**Comment by feihujiang** [comment]
@bgrant0607 Do we need to do something about this issue?

**Comment by bgrant0607** [comment]
Don't know why it was reopened.
