### ISSUE TITLE
Container logs not appearing in console, skydns crashes with exit code 2

### ISSUE THREAD

**Issue by marcospedreiro** [kubernetes/kubernetes#10852]
EDIT: 

Solution to the logging problem found: https://groups.google.com/forum/#!topic/google-containers/D6RdGOqxKP4

-----
I am running a kubernetes cluster on the GCE, cluster has a pod running a nodejs server. I can see the logs for the server with `kubectl logs podName`, however I cannot see the web server logs on the console. The web server creates logs with `console.log()`. The pod is managed by a replication controller, and I created the rc after I created the respective service.

Edit: Further testing: If I create a new cluster in a separate project and create a 'counter' pod as specified in the [getting started guide for logging](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/logging.md), then I am able to see the logs in the console under Monitoring>logs. However if I create the same pod in the project>cluster where the node js server is running, I cannot see the logs. It is also the case that if I run the webserver on the other project, I can see the logs in the console. 

Note: I am the owner of the project where I can see the logs. However I am not the owner of the project where I can not see the logs. The project where I can not see the logs has multiple instances running, each with multiple pods, and I need to be able to see the logs for everything. But in the console it does not give me the option to look at the logs for any of the instances. Instead the only type of log I can see is info, even though I select "any log level."

gcloud components are up to date, and running `kubectl version` gives:

```
Client Version: version.Info{Major:"0", Minor:"18", GitVersion:"v0.18.1", GitCommit:"befd1385e5af5f7516f75a27a2628272bb9e9f36", GitTreeState:"clean"}
Server Version: version.Info{Major:"0", Minor:"19", GitVersion:"v0.19.3", GitCommit:"3103c8ca0f24514bc39b6e2b7d909bbf46af8d11", GitTreeState:"clean"}
```

I created a new cluster, and fluentd said that it had exit code 0. 

Furthermore I am seeing that the `kube-dns` pod that runs skydns, kube2sky, and etcd shows the skydns container with an exit code 2. Running kubectl logs on that container I get the output:
Edit: I deleted my rc, and then killed the `kube-dns` pod and when it restarted I did not get the skydns error. However I am still curious as to why it crashed. I included this information incase it was related to me not being able to see the logs. My main concern is not being able to see the logs. 

```
2015/07/07 17:06:33 skydns: falling back to default configuration, could not read from etcd: 100: Key not found (/skydns) [2]
2015/07/07 17:06:33 skydns: ready for queries on cluster.local. for tcp://0.0.0.0:53 [rcache 0]
2015/07/07 17:06:33 skydns: ready for queries on cluster.local. for udp://0.0.0.0:53 [rcache 0]
2015/07/07 17:24:05 skydns: can not forward, name too short (less than 2 labels): 'namehere.'
```

The images for the three containers are: 
```
gcr.io/google_containers/skydns:2015-03-11-001
gcr.io/google_containers/kube2sky:1.9 
gcr.io/google_containers/etcd:2.0.9
```

**Comment by goltermann** [comment]
We’re going through old support issues and asking everyone to direct your questions to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes). 

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases. 

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.
