### ISSUE TITLE
Pod runs normally but still reports "FailedScheduling" event repeatedly

### ISSUE THREAD

**Issue by houjun41544** [kubernetes/kubernetes#108665]
### What happened?

The Pod has been running normally for more than two days, but the "FailedScheduling" event is still reported repeatedly.
![image](https://user-images.githubusercontent.com/25921749/157999468-f79c307f-5d87-4a71-b031-0377e3aa3282.png)

I can see in the kube-scheduler log that the pod was scheduled for the first time and failed due to a binding failure. The reason for the failure was "etcdserver: request timed out". After that, it was rescheduled repeatedly, but the scheduling failed due to port conflict.
![image](https://user-images.githubusercontent.com/25921749/158000182-45641af3-8772-4034-8837-4cd7a0af4076.png)
Looking at the kube-apiserver log, it took more than 11s to receive the response to the binding request.
![image](https://user-images.githubusercontent.com/25921749/158000527-6648af9c-87bf-48fb-a40d-94e7c27e1884.png)
So it could be that despite "etcdserver:request timed out", pod binding has been successfully updated to etcd. But kube-scheduler may not receive the “binding add” event, or the binding fails after receiving the event, so re-add the pod to the scheduler queue and reschedule.

This is the same reason as a previous issue #100140.

### What did you expect to happen?

Pod is running normally but no "FailedScheduling" event is reported.

### How can we reproduce it (as minimally and precisely as possible)?

Etcd processing takes a long time when Pod creates.

### Kubernetes version

<details>

```console
$ kubectl version
v1.19.4
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by denkensk** [comment]
copy form https://github.com/kubernetes/kubernetes/pull/108667#pullrequestreview-908006146

1. The root case is why etcd returns `etcdserver:request timed out` but update successfuly and also scheduler did't receive the binding event? It feels like there are errors in multiple component interactions. I think we need to dig into the reasons for that Instead of just patching, right? 

2. IIUC.  We have checked `cachedPod.Spec.NodeName` in `ErrorFunc` before re-enqueue. Right? Why the pod will retry again and again?
https://github.com/kubernetes/kubernetes/blob/45f2c63d6af7d25d2c17a3953a2451340218ef14/pkg/scheduler/factory.go#L234-L239

**Comment by houjun41544** [comment]
Close this issue as #96582 has fixed it.
