### ISSUE TITLE
ttlSecondsAfterFinished setting is ignored when Job is created by CronJob.  Always defaults to 30

### ISSUE THREAD

**Issue by scubakiz** [kubernetes/kubernetes#108677]
### What happened?

When I set ttlSecondsAfterFinished: 120 in a Job, it works fine.  However, when I use it in a jobTemplate in CronJob, it's ignored and the CronJob always creates a Job with this value set to 30.

### What did you expect to happen?

I expect ttlSecondsAfterFinished to be set correctly when the CronJob creates the Job.

### How can we reproduce it (as minimally and precisely as possible)?

apiVersion: batch/v1
kind: CronJob
metadata:
  name: sample-cron-job  
spec:
  schedule: "*/3 * * * *"
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 120     
      template:
      ...

Creates a Job with ttlSecondsAfterFinished: 30 regardless of the setting I specify.

### Anything else we need to know?

This worked correctly prior to 1.21 (in batch/v1beta1).  Now, it doesn't work in either version.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-17T15:48:33Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.9", GitCommit:"37f338aa38e0427e127162afe462e2f4150f0ba3", GitTreeState:"clean", BuildDate:"2022-02-07T20:49:26Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
Azure
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>
containerd://1.4.12+azure-2
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by mengjiao-liu** [comment]
/assign
I'll try to reproduce the issue first.

**Comment by mengjiao-liu** [comment]
This is the yaml I use:
```yaml
apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello-ttl
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 120
      template:
        spec:
          containers:
          - name: hello
            image: busybox
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: Never
```
 I used `kind` to run the k8s `1.21.10` version on the `MacOS` environment without reproducing this issue, `ttlSecondsAfterFinished` cleans up the job as expected (because `kind` does not have `kindest/nod:1.21.9` image, but k8s `1.21.9` to `1.21.10` does not have `ttlSecondsAfterFinished` this some code changes should not affect).
```
$ kind version
kind v0.11.1 go1.17.2 darwin/amd64

kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"5c99e2ac2ff9a3c549d9ca665e7bc05a3e18f07e", GitTreeState:"clean", BuildDate:"2021-12-16T08:38:33Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.10", GitCommit:"a7a32748b5c60445c4c7ee904caf01b91f2dbb71", GitTreeState:"clean", BuildDate:"2022-03-07T09:03:24Z", GoVersion:"go1.16.14", Compiler:"gc", Platform:"linux/amd64"}
```

I tested this problem in k8s 1.23.0 version in `Linux` environment , and it also did not reproduce this issue.
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.0", GitCommit:"ab69524f795c42094a6630298ff53f3c3ebab7f4", GitTreeState:"clean", BuildDate:"2021-12-07T18:16:20Z", GoVersion:"go1.17.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.0", GitCommit:"ab69524f795c42094a6630298ff53f3c3ebab7f4", GitTreeState:"clean", BuildDate:"2021-12-07T18:09:57Z", GoVersion:"go1.17.3", Compiler:"gc", Platform:"linux/amd64"}
```
----------
I also looked at the code and this part of the code processing logic is basically unchanged：
https://github.com/kubernetes/kubernetes/blob/02b1ec5b0b451d27d78507c237d6e2fcffe10feb/pkg/controller/ttlafterfinished/ttlafterfinished_controller.go#L251

The PR covering this part in version 1.21 is #98676 , but this PR is just for adding metrics.
- A new histogram metric to track the time it took to delete a job by the `TTLAfterFinished` controller ([#98676](https://github.com/kubernetes/kubernetes/pull/98676), [@ahg-g](https://github.com/ahg-g))


Maybe it's an issue with the configuration of your azure environment?

/cc @ soltysh
