### ISSUE TITLE
Misleading behaviour of pod deletion with --force --grace-period 0 flags

### ISSUE THREAD

**Issue by Excpt0r** [kubernetes/kubernetes#108741]
### What happened?

The situation is pretty good described in a comment [here](https://github.com/kubernetes/kubernetes/issues/86914#issuecomment-571931346).
The kubectl flag names "--force" and "--grace-period" and corresponding help indicate an IMMEDIAT deletion of the pod and kill of corresponding containers.

Actual behaviour:
- The kube api ressource is deleted immediatly
- The corresponding container(s) of the pod receive a SIGTERM signal, and SIGKILL is sent after "terminationGracePeriodSeconds" of the pod (30s in my case).

The unexpected behaviour is not obvious, because when you use the command with a container that reacts on SIGTERM quickly, you won't see the difference.

We used that command to test the behaviour of leader-election based StatefulSets.

### What did you expect to happen?

Expected behaviour:
- The kube api ressource is deleted immediatly
- The corresponding container(s) of the pod receive a SIGKILL signal immediatly, not after "terminationGracePeriodSeconds" of the pod (30s in my case).

### How can we reproduce it (as minimally and precisely as possible)?

terminal1:
- kubectl run test-pod --image docker-quay-io.prod.bk.dfs/strimzi/kafka:0.27.0-kafka-2.8.0 --command -- bash -c "trap 'echo SIGTERM received' SIGTERM; trap 'echo SIGINT received' SIGINT; while [ 1 ]; do date; echo sleeping; sleep 1; done"
- kubectl logs -f test-pod

terminal2:
- kubectl delete pod test-pod --force --grace-period 0

Observe ~30s between SIGTERM and container termination
```
Wed Mar 16 16:34:57 UTC 2022
sleeping
SIGTERM received
...
Wed Mar 16 16:35:28 UTC 2022
sleeping
```

### Anything else we need to know?

The best workaround is to use --grace-period 0 WITHOUT the --force flag.
That will send the SIGKILL directly after SIGTERM as it seems.

### Kubernetes version

<details>

```console
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.2", GitCommit:"9d142434e3af351a628bffee3939e64c681afa4d", GitTreeState:"clean", BuildDate:"2022-01-19T17:35:46Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3+e790d7f", GitCommit:"3a0f2c90b43e6cffd07f57b5b78dd9f083e47ee2", GitTreeState:"clean", BuildDate:"2021-12-14T02:10:38Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

N/A

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by brianpursley** [comment]
Unfortunately, as you discovered, grace period is confusing because `--grace-period 0` behaves differently depending on whether you are using the `--force` flag or not:

* Without `--force`, grace period 0 gets changed to 1.
* With `--force`, grace period 0 is not changed.  In fact, if it is < 0, it is converted to 0.  And there is a check elsewhere in the code that returns an error if you try to use a grace period > 0.

https://github.com/kubernetes/kubernetes/blob/d6c83281bc696474a76365a879f2255b8b568786/staging/src/k8s.io/kubectl/pkg/cmd/delete/delete.go#L181-L188

Grace period 0, sounds like it might mean immediate, but it gets interpreted by kubelet as "use the pod's defined grace period":

https://github.com/kubernetes/kubernetes/blob/69a3820214e0fb7bbdf6574ff2fbc86b14ca4d53/pkg/kubelet/pod_workers.go#L787-L791

Grace period 1 is really what is considered "immediate" and that is what the `--now` flag sets.

The help text for `--force` says it will "bypass graceful deletion", but this is wrong.

Here are a few ideas I can think of how to improve force deletion in kubectl:

* OPTION 1:  Always set grace period = 1 when force is used, no matter what.  This changes force behavior to be immediate, and in my opinion matches how it is described in the help text.  This is probably how it is intended to behave, but does not currently.

* OPTION 2:  Leave existing `--force` behavior as-is (pod's grace period is used), but allow the use of `--now` or `--grace-period 1` to allow immediate deletion.  Update help text to explain this.

* OPTION 3:  Allow any grace period to be specified, even when `--force` is used and don't do any special handling when force is used.  I'm not sure why it needs to prohibit the use of grace period in conjunction with force anyway.  Maybe someone with more history about force deletion can chime in why this is a bad idea.

**Comment by jayunit100** [comment]
so to really kill etcd, we need to do

```
--grade-period=0 --force
```

i believe, right?

**Comment by Excpt0r** [comment]
@jayunit100 
nope, `--grace-period=0` will use the grace-period defined in the pod, for example 30s.
And it's not possible to combine `--force` with grace-period different to 0.
The closest you can get to "kill pod immediately" is to use `--grace-period=1` or its alias `--now` (note the missing `--force`).

That is at least my understanding, based on the explanation from brian.

**Comment by jayunit100** [comment]
ah ok thanks !

**Comment by shopee-jin** [comment]
1 sec sounds reasonable and thus need better documentation

**Comment by zcahana** [comment]
/reopen

This issue is still valid, as people (myself included) continue to get confused about the semantics of force deletions and grace-periods.

> OPTION 1: Always set grace period = 1 when force is used, no matter what. This changes force behavior to be immediate, and in my opinion matches how it is described in the help text. This is probably how it is intended to behave, but does not currently.
>
> OPTION 2: Leave existing --force behavior as-is (pod's grace period is used), but allow the use of --now or --grace-period 1 to allow immediate deletion. Update help text to explain this.
> 
> OPTION 3: Allow any grace period to be specified, even when --force is used and don't do any special handling when force is used. I'm not sure why it needs to prohibit the use of grace period in conjunction with force anyway. Maybe someone with more history about force deletion can chime in why this is a bad idea.

Option (3) seems most plausible to me, and additionally it would be best if the semantics of `--grace-period 0` would
match its name (and, probably, user expectations) - that it to immediately terminate the pod containers in a non-graceful manner (i.e., immediate SIGKILL, no preStop hooks, no grace period). Combined with option (3), we would achieve a clear separation between `--force`, which will only affect if and how the pod object is removed from the k8s API, and `--grace-period`, which will only affects how containers are terminated.

The main issue remains backward compatibility for the change in semantics of `--grace-period 0`, but if we accept that the existing behavior (`--grace-period 0 ==> graceful termination) is a somewhat of a bug, than it would sweeten the pill.

**Comment by zcahana** [comment]
Apparently I can't `/reopen`, but if any project collaborator believes this issue is still valid and should be addressed, you're welcome to reopen.

cc @brianpursley
