### ISSUE TITLE
[Flakey Test] capz-windows-containerd-master ~ various tests ~ httpd timeouts

### ISSUE THREAD

**Issue by marosset** [kubernetes/kubernetes#108711]
### Which jobs are flaking?

We are seeing a various test flakes in https://testgrid.k8s.io/sig-windows-signal#capz-windows-containerd-master where Windows pods encountering errors making calls to httpd pods.

### Which tests are flaking?

We have seen these flakes in the following tests:
- [sig-node] Container Lifecycle Hook when create a pod with lifecycle hook should execute prestop exec hook properly [NodeConformance] [Conformance]
- [sig-apps] StatefulSet Basic StatefulSet functionality [StatefulSetBasic] should perform rolling updates and roll backs of template modifications [Conformance]
- [sig-network] Services should serve multiport endpoints from pods [Conformance]
- and more

Logs
- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-capz-master-containerd-windows/1503162834484203520

### Since when has it been flaking?

A few months?

### Testgrid link

https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-capz-master-containerd-windows/1503162834484203520

### Relevant SIG(s)

/sig windows

**Comment by marosset** [comment]
We saw another issue during our tirage meeting.
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-capz-master-containerd-windows/1508628790731870208

```
{ Failure test/e2e/windows/hybrid_network.go:86
Mar 29 03:02:04.806: Timed out after 11.484s.
Unexpected error:
    <exec.CodeExitError>: {
        Err: {
            s: "command terminated with exit code 28",
        },
        Code: 28,
    }
    command terminated with exit code 28
occurred
test/e2e/windows/hybrid_network.go:116}
```

@jayunit100 @daschott - would either of you be able to help look into these test flakes?

/cc @ravisantoshgudimetla

**Comment by daschott** [comment]
Could we take a collectLogs and packet capture?
aka.ms/collectlogs 
aka.ms/startpacketcapture

**Comment by marosset** [comment]
> Could we take a collectLogs and packet capture? aka.ms/collectlogs aka.ms/startpacketcapture

We have a lot of the logs that collectLogs captures at https://gcsweb.k8s.io/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-capz-master-containerd-windows/1508628790731870208/artifacts/clusters/capz-conf-ui6yhr/machines/

Unfortunately we don't have an easy way to do packet captures in our CI jobs.

**Comment by claudiubelu** [comment]
Regarding the ``[sig-node] Container Lifecycle Hook when create a pod with lifecycle hook should execute prestop exec hook properly [NodeConformance] [Conformance]`` test, it seems that this issue pretty much only occurs with capz, and only in the capz environments [1]. In capz, we do use calico, so that **might** be the issue. 

A small explanation on what's happening in the test: it spawns a webserver pod, and another pod exec pod, which has ``gracefulTerminationPod`` (meaning that it won't be killed immediately, and it is allowed to run a prestop hook) and which has a prestop hook, which execs a curl to the pod webserver, which sometimes ends up with an ``exit code 7 Bad Access``, and the request doesn't reach the webserver pod.

Now, I think there's a race condition happening between the prestop hook and the calico itself. For example, we can analyze one of the failures [2]. Here, we see that the exec pod started and then killed:

```
Apr 29 09:35:33.581: INFO: The status of Pod pod-with-prestop-exec-hook is Running (Ready = true)
ï¿½[1mSTEPï¿½[0m: delete the pod with lifecycle hook
Apr 29 09:35:33.789: INFO: Waiting for pod pod-with-prestop-exec-hook to disappear
```

So, the delete request is sent sometime between ``09:35:33.581`` and ``09:35:33.789``. During that time frame, we can see in the calico logs that it got some sort of updates: 

```
2022-04-29 09:35:33.738 [INFO][8088] felix/calc_graph.go 446: Local endpoint updated id=WorkloadEndpoint(node=capz-conf-zz6mx, orchestrator=k8s, workload=container-lifecycle-hook-385/pod-with-prestop-exec-hook, name=eth0)
2022-04-29 09:35:33.738 [INFO][8088] felix/win_dataplane.go 255: Received *proto.WorkloadEndpointUpdate update from calculation graph msg=id:<orchestrator_id:"k8s" workload_id:"container-lifecycle-hook-385/pod-with-prestop-exec-hook" endpoint_id:"eth0" > endpoint:<state:"active" name:"cali7ef6ebe3ea5" profile_ids:"kns.container-lifecycle-hook-385" profile_ids:"ksa.container-lifecycle-hook-385.default" ipv4_nets:"192.168.235.75/32" > 
2022-04-29 09:35:33.738 [INFO][8088] felix/endpoint_mgr.go 139: Processing WorkloadEndpointUpdate workloadEndpointId=orchestrator_id:"k8s" workload_id:"container-lifecycle-hook-385/pod-with-prestop-exec-hook" endpoint_id:"eth0" 
2022-04-29 09:35:33.739 [INFO][8088] felix/win_dataplane.go 306: Applying dataplane updates
2022-04-29 09:35:33.739 [INFO][8088] felix/endpoint_mgr.go 162: Refreshing the endpoint cache
2022-04-29 09:35:33.761 [INFO][8088] felix/endpoint_mgr.go 226: Cache refresh is complete. 3 endpoints were cached
2022-04-29 09:35:33.761 [INFO][8088] felix/endpoint_mgr.go 503: Resolved hns endpoint id id="D0773AE9-3B2D-44ED-8C6D-C846B9E9D653" ip="192.168.235.75/32"
2022-04-29 09:35:33.761 [INFO][8088] felix/endpoint_mgr.go 357: Processing endpoint add/update id=proto.WorkloadEndpointID{OrchestratorId:"k8s", WorkloadId:"container-lifecycle-hook-385/pod-with-prestop-exec-hook", EndpointId:"eth0"}
2022-04-29 09:35:33.761 [INFO][8088] felix/endpoint_mgr.go 447: Applying endpoint rules endpointId="D0773AE9-3B2D-44ED-8C6D-C846B9E9D653" id=proto.WorkloadEndpointID{OrchestratorId:"k8s", WorkloadId:"container-lifecycle-hook-385/pod-with-prestop-exec-hook", EndpointId:"eth0"} inboundPolicyIds=[]string{"profile-kns.container-lifecycle-hook-385", "profile-ksa.container-lifecycle-hook-385.default"} outboundPolicyIds=[]string{"profile-kns.container-lifecycle-hook-385", "profile-ksa.container-lifecycle-hook-385.default"}
```

And almost afterwards, we can see that the pod prestop hook also executes:

```
I0429 09:35:33.738288    3996 kubelet.go:2076] "SyncLoop DELETE" source="api" pods=[container-lifecycle-hook-385/pod-with-prestop-exec-hook]
E0429 09:35:33.813278    3996 handlers.go:67] "Exec lifecycle hook for Container in Pod failed" err=<
	command 'sh -c curl http://192.168.235.71:8080/echo?msg=prestop' exited with 7:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
	                                 Dload  Upload   Total   Spent    Left  Speed
	
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to 192.168.235.71 port 8080: Bad access
 > execCommand=[sh -c curl http://192.168.235.71:8080/echo?msg=prestop] containerName="pod-with-prestop-exec-hook" pod="container-lifecycle-hook-385/pod-with-prestop-exec-hook" message=<
	  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
	                                 Dload  Upload   Total   Spent    Left  Speed
	
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to 192.168.235.71 port 8080: Bad access
 >
E0429 09:35:33.813278    3996 kuberuntime_container.go:593] "PreStop hook failed" err=<
	command 'sh -c curl http://192.168.235.71:8080/echo?msg=prestop' exited with 7:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
	                                 Dload  Upload   Total   Spent    Left  Speed
	
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to 192.168.235.71 port 8080: Bad access
 > pod="container-lifecycle-hook-385/pod-with-prestop-exec-hook" podUID=bd777daf-31c7-4edf-92f8-c4871c3b3d74 containerName="pod-with-prestop-exec-hook" containerID="containerd://f5b215efd35ac0bd9ec60e76b9654834653120a8ff1f6246803641ad1c67bde1"
I0429 09:35:33.813278    3996 kuberuntime_container.go:722] "Killing container with a grace period" pod="container-lifecycle-hook-385/pod-with-prestop-exec-hook" podUID=bd777daf-31c7-4edf-92f8-c4871c3b3d74 containerName="pod-with-prestop-exec-hook" containerID="containerd://f5b215efd35ac0bd9ec60e76b9654834653120a8ff1f6246803641ad1c67bde1" gracePeriod=15
```

This seems to be the pattern for the failing tests, or at least for 3 jobs I've checked. Additionally, I've checked a few passing jobs, and it seems that in their case, the prestop hook executes slightly before the calico updates. More jobs should be investigated though to confirm this.

Additionally, I think it's worth noting that there are 2 different prestop lifecycle hook jobs: an exec prestop (flaky), and a http prestop (not flaky) [4]. In both scenarios, the webserver pod is contacted, but by different actors: In the exec prestop case, the exec pod is exec'd into and curl is used, while for the http prestop case, the node's kubelet is responsible for accessing the http pod (which means that it's not dependent on the client pod's networking).

[1] https://storage.googleapis.com/k8s-triage/index.html?text=failed%20to%20match%20regexp&test=should%20execute%20prestop%20exec%20hook%20properly
[2] https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-capz-master-containerd-windows/1519963975511445504
[3] https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-capz-master-containerd-windows/1519963975511445504/artifacts/clusters/capz-conf-hn7bmy/kube-system/calico-node-windows-s6pg4/calico-node-felix.log
[4] https://storage.googleapis.com/k8s-triage/index.html?text=failed%20to%20match&test=should%20execute%20prestop%20http%20hook%20properly

**Comment by pacoxu** [comment]
As the https://testgrid.k8s.io/sig-release-master-informing#capz-windows-master shows,

> * [sig-node] Container Lifecycle Hook when create a pod with lifecycle hook should execute prestop exec hook properly [NodeConformance] [Conformance]

This still flakes.
@claudiubelu I would suggest opening a new issue to track this flake only.

> * [sig-apps] StatefulSet Basic StatefulSet functionality [StatefulSetBasic] should perform rolling updates and roll backs of template modifications [Conformance]

Fixed and followed in https://github.com/kubernetes/kubernetes/issues/120700

> * [sig-network] Services should serve multiport endpoints from pods [Conformance]

Not flake in the testgrid.

> * ServiceAccountIssuerDiscovery should support OIDC discovery of service account issuer

Tracked in https://github.com/kubernetes/kubernetes/issues/107114.

**Comment by pacoxu** [comment]
> > * [sig-node] Container Lifecycle Hook when create a pod with lifecycle hook should execute prestop exec hook properly [NodeConformance] [Conformance]
> 
> This still flakes. @claudiubelu I would suggest opening a new issue to track this flake only.

Flake 5 times in https://testgrid.k8s.io/sig-release-master-informing#capz-windows-master. 

```
  "ci-kubernetes-e2e-capz-master-windows": {
    "consistency": 0.6,
    "flakes": 4,
    "test_flakes": {
      "Kubernetes e2e suite [It] [sig-node] Container Lifecycle Hook when create a pod with lifecycle hook should execute prestop exec hook properly [NodeConformance] [Conformance]": 3,
      "Kubernetes e2e suite [It] [sig-auth] ServiceAccounts ServiceAccountIssuerDiscovery should support OIDC discovery of service account issuer [Conformance]": 3
    }
  },
```
in https://storage.googleapis.com/k8s-metrics/flakes-latest.json
