### ISSUE TITLE
making it possible to grant specific PodSecurity permissions for specific services 

### ISSUE THREAD

**Issue by alonSadan** [kubernetes/kubernetes#108802]
(moved from https://github.com/kubernetes/pod-security-admission/issues/1)

As a user of this feature I would like to be able to allow specific capabilities for specific services in my project.

The current implementations offers only three general definitions of security levels which can be hard to suit services that require one or two special capabilities.

Also since the admission is applied in the namespace level (and because of the general security levels) it makes me either adopt the most permissive security level for the entire namespace (so that all services with their "special requirements"  will be allowed in the cluster), or divide my project into small namespaces increasing it's granularity. I see both options is bad options.

The ability to allow specific capabilities for specific services would help me keeping my project less granular, and secure as possible.

**Comment by liggitt** [comment]
Granting at the namespace level was an intentional design decision. PodSecurityAdmission controls the *highest* permission pod allowed into a namespace. It is certainly possible to deploy low-privileged things into a namespace that is more permissive.

Dividing into smaller more granular namespaces is the recommended approach, especially if you do not uniformly trust manifest authors.

Experience with the PodSecurityPolicy API and authorization model convinced us that namespace-level, coarse-grained permissions were the right level to build into Kubernetes, and to defer fine-grained policy or sub-namespace authorizations to external policy solutions via admission webhooks.

/close

**Comment by alonSadan** [comment]
Thanks @liggitt
