### ISSUE TITLE
When no resource found, `client-go` Lister.Get() return a `NotFound` err, but Lister.List() just return nil

### ISSUE THREAD

**Issue by astraw99** [kubernetes/kubernetes#108960]
### What would you like to be added?

When no resource found, `client-go` Lister.Get() and Lister.List() both return a `NotFound` err, to keep the error output consistent.

### Why is this needed?

When use the `client-go` Lister to Get or List resource(s), if the resource not found, the Lister.Get() return a `NotFound` err, but Lister.List() just return nil, this is confusing.

To keep the error output consistent, Lister.Get() and Lister.List() should both return a `NotFound` err.

**Comment by aojea** [comment]
I personally feel that this is right:
 Get(name) that doesn't exist -> error,
 List() return empty if there is nothing

**Comment by fedebongio** [comment]
Thank you @cyclinder and @aojea 
/cc @yliaog in case he has an opinion too
/triage accepted

**Comment by yliaog** [comment]
agree with @aojea, it is expected to return empty list, as it is not an error.

**Comment by cyclinder** [comment]
Lister.Get() return `nil` or `NotFound` err, I think both is ok.  Just look does it need to be consistent with Lister.List()?

**Comment by astraw99** [comment]
> Lister.Get() return `nil` or `NotFound` err, I think both is ok. Just look does it need to be consistent with Lister.List()?

I think it would be easier to handle err by client, if Lister.Get() and Lister.List() err is consistent.

**Comment by aojea** [comment]
> I think it would be easier to handle err by client, if Lister.Get() and Lister.List() err is consistent.

I have to disagree :) , is not about consistency, this example in the client-go project illustrate it well

https://github.com/kubernetes/kubernetes/blob/d58f42961cc397b820ea2372a42dee3bc33745eb/staging/src/k8s.io/client-go/examples/in-cluster-client-configuration/main.go#L51-L74

1. if you change the List() behavior to return an error, that is a non backwards compatible change, and you are going to break a lot of controllers
2. if I do a List() I expect a list of elements, if it is empty and my code iterate over the list, I don't need an additional check
```
pods, err := clientset.CoreV1().Pods("").List(context.TODO(), metav1.ListOptions{})
if err != nil {
	panic(err.Error())
}
for _, pod := range pods {
   // do things with the pods
}
```

this follows the common convention on REST APIs https://apihandyman.io/empty-lists-http-status-code-200-vs-204-vs-404/ , because at the end, client-go is just a wrapper of a rest client 

However, I don't think that at this point you are able to change any of these behaviors without keeping compatibility,
