### ISSUE TITLE
Delay in processing HNS LB policies on kube-proxy start on Windows nodes results in unreachable services

### ISSUE THREAD

**Issue by LP0101** [kubernetes/kubernetes#109162]
### What happened?

When starting windows nodes with a high number of HNS LB policies/rules on the cluster, there is a delay in processing them. This leaves services unreachable during the delay, which takes about half a minute per policy. This can be substatial given enough rules.

This occurs when restarting kube-proxy and rebooting the host. Once the system does reach a state where all the policylists are processed, incremental updates to the services are handled fine (ie. endpoint changes).

### What did you expect to happen?

HNS policies should not cause a large delay for Windows nodes.

### How can we reproduce it (as minimally and precisely as possible)?

With a large number of HNS policies in place, restart kube-proxy on a Windows node.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.7", GitCommit:"1f86634ff08f37e54e8bfcd86bc90b61c98f84d4", GitTreeState:"clean", BuildDate:"2021-11-17T14:41:19Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.7", GitCommit:"f74784f1eaf1e02b651778d6ee2df1ae5ee729ae", GitTreeState:"clean", BuildDate:"2022-03-10T07:58:41Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
Azure AKS
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by jsturtevant** [comment]
/triage accepted

There are more details on timing in the fix that @daschott opened https://github.com/kubernetes/kubernetes/pull/109124

When doing a sync of Services on a new node joining the cluster, the HNS is queried for state on every endpoint in a service which is expensive. When iterating over thousands of services, this can take hours (!) when there are lots of services.  

The fix proposed by @daschott gets the HNS state once instead of each time. This plus a fix in Windows OS the sync is reduced to mins in WS 2019 and ~1 min in WS 2022.

**Comment by zhiweiv** [comment]
@daschott @jsturtevant 
For the Windows OS fix mentioned, do you know when will it arrive at Windows Server 2019?
