### ISSUE TITLE
[Flaky test] gce-cos-master-default, node problem detector

### ISSUE THREAD

**Issue by leonardpahlke** [kubernetes/kubernetes#109281]
### Which jobs are flaking?

- sig-release-master-blocking gce-cos-master-default

### Which tests are flaking?

- Kubernetes e2e suite.[sig-node] NodeProblemDetector should run without error

### Since when has it been flaking?

not clear

### Testgrid link

https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-default

### Reason for failure (if possible)

[test/e2e/node/node_problem_detector.go:60](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/node/node_problem_detector.go#L60)
```bash
{ Failure test/e2e/node/node_problem_detector.go:60
Apr  4 04:16:24.757: Unexpected error:
    <*errors.errorString | 0xc00218be20>: {
        s: "error getting SSH client to prow@35.197.100.131:22: 'ssh: handshake failed: read tcp 10.32.192.70:41974->35.197.100.131:22: read: connection reset by peer'",
    }
    error getting SSH client to prow@35.197.100.131:22: 'ssh: handshake failed: read tcp 10.32.192.70:41974->35.197.100.131:22: read: connection reset by peer'
occurred
test/e2e/node/node_problem_detector.go:340}
```

### Relevant SIG(s)

/sig node
cc @kubernetes/ci-signal

**Comment by ehashman** [comment]
/triage accepted

### Failure cluster [60e158d84bb0d0abb118](https://go.k8s.io/triage#60e158d84bb0d0abb118)

##### Error text:
```
test/e2e/node/node_problem_detector.go:60
Mar 19 19:27:22.659: Timed out after 60.001s.
Expected success, but got an error:
    <*errors.errorString | 0xc003fc2020>: {
        s: "Event KubeletStart does not exist: [{{ } {bootstrap-e2e-minion-group-1b08.16dddec4a969249e  default  e5d0b7b5-f97d-48ec-aef7-f1ff3c81c89e 34695 0 2022-03-19 19:26:14 +0000 UTC <nil> <nil> map[] map[] [] []  [{node-problem-detector Update v1 2022-03-19 19:26:14 +0000 UTC FieldsV1 {\"f:count\":{},\"f:firstTimestamp\":{},\"f:involvedObject\":{},\"f:lastTimestamp\":{},\"f:message\":{},\"f:reason\":{},\"f:source\":{\"f:component\":{},\"f:host\":{}},\"f:type\":{}} }]} {Node  bootstrap-e2e-minion-group-1b08 bootstrap-e2e-minion-group-1b08   } TaskHung kernel: INFO: task docker:12345 blocked for more than 120 seconds. {kernel-monitor bootstrap-e2e-minion-group-1b08} 2022-03-19 19:26:14 +0000 UTC 2022-03-19 19:26:14 +0000 UTC 1 Warning 0001-01-01 00:00:00 +0000 UTC nil  nil  } {{ } {bootstrap-e2e-minion-group-1b08.16dddec4a9694947  default  0d62121c-1241-4dba-866b-85b856559988 34694 0 2022-03-19 19:26:14 +0000 UTC <nil> <nil> map[] map[] [] []  [{node-problem-detector Update v1 2022-03-19 19:26:14 +0000 UTC FieldsV1 {\"f:count\":{},\"f:firstTimestamp\":{},\"f:involvedObject\":{},\"f:lastTimestamp\":{},\"f:message\":{},\"f:reason\":{},\"f:source\":{\"f:component\":{},\"f:host\":{}},\"f:type\":{}} }]} {Node  bootstrap-e2e-minion-group-1b08 bootstrap-e2e-minion-group-1b08   } DockerHung Node condition KernelDea
```
#### Recent failures:
[4/1/2022, 3:22:39 AM ci-kubernetes-e2e-gce-stable1-latest-upgrade-cluster-new-parallel](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-stable1-latest-upgrade-cluster-new-parallel/1509838617164386304)
[3/31/2022, 5:09:35 PM ci-kubernetes-e2e-gce-stable1-latest-upgrade-cluster-new-parallel](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-stable1-latest-upgrade-cluster-new-parallel/1509684348503199744)
[3/31/2022, 6:33:23 AM ci-kubernetes-e2e-gce-stable1-latest-upgrade-cluster-new-parallel](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-stable1-latest-upgrade-cluster-new-parallel/1509524240888500224)
[3/28/2022, 12:12:01 PM ci-kubernetes-e2e-gce-stable1-latest-upgrade-cluster-new-parallel](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-stable1-latest-upgrade-cluster-new-parallel/1508522296195682304)
[3/27/2022, 4:02:13 PM ci-kubernetes-e2e-gce-stable1-latest-upgrade-cluster-new-parallel](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-stable1-latest-upgrade-cluster-new-parallel/1508217839666860032)

/milestone v1.24

**Comment by SergeyKanzhelev** [comment]
Issue with the timeout is likely some infra problem. Many tests are failing during the  run and the node has no kubelet log, just the serial log in artifacts. It is likely different problem than the original issues posted about SSH issue.

On this tab https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-default most flakes are caused by SSH issue.

SSH issue is quite strange, I see that many SSH calls before it to the same server succeed. I saw it before when connection pool was exhausted, perhaps the retry can solve the issue. Need to look deeper

**Comment by pacoxu** [comment]
Some simple research possibilities on it:
- https://github.com/golang/go/issues/20960#issuecomment-465998114 `sudo ulimit -n 6049 && sudo sysctl -w kern.ipc.somaxconn=1024` for https://stackoverflow.com/questions/67190125/error-ssh-handshake-failed-read-tcp-read-connection-reset-by-peer
- (I prefer this) https://stackoverflow.com/questions/47805723/golang-ssh-handshake-failed-eof The code is quite similar here. The issue was fixed by changing one server one connection and muliple NewSession fixed this problem.
- The last fix would be to change the timeout and retry time larger in the ssh retry logic below.

https://github.com/kubernetes/kubernetes/blob/c6478308f8aeb691b482a7b6d96606af6c477f9d/test/e2e/framework/ssh/ssh.go#L242-L254

**Comment by SergeyKanzhelev** [comment]
I feel like this line is incorrect:

https://github.com/kubernetes/kubernetes/blob/c6478308f8aeb691b482a7b6d96606af6c477f9d/test/e2e/framework/ssh/ssh.go#L247

Changing it to `return false, nil` should make the code retry.

**Comment by SergeyKanzhelev** [comment]
I'll spin off the bug for other test grids. The release blocking grid seems to be green now

/close
