### ISSUE TITLE
Kubernetes Cluster Provisioning through AWS takes a long time

### ISSUE THREAD

**Issue by kgrvamsi** [kubernetes/kubernetes#10929]
I'm trying to create a kubernetes cluster on aws but seems like it gets stuck at the Cluster initialization .Infact i waited 2 hrs on this but it keeps on adding the dots :(

    Output
    4 minions started; ready
    Waiting 3 minutes for cluster to settle
    ..................Re-running salt highstate
    Waiting for cluster initialization.

    This will continually check to see if the API for kubernetes is reachable.
    This might loop forever if there was some uncaught error during start
    up.     ...................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................

**Comment by roberthbailey** [comment]
I think @brendandburns may have a PR outstanding that fixes this.

**Comment by kgrvamsi** [comment]
To add some more information the docker daemon on the minions is not running

**Comment by justinsb** [comment]
Anything above 10 minutes is likely in the "This might loop forever if there was some uncaught error during start up" category.  We did indeed fix some issues around docker startup on AWS, and there's an open PR that will double-fix them on AWS: #9381

**Comment by kgrvamsi** [comment]
Ok will give a try today and see if i face any issues!!!

**Comment by goltermann** [comment]
We’re going through old support issues and asking everyone to direct your questions to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes). 

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases. 

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.
