### ISSUE TITLE
server-side field validation rejects metadata fields as unknown fields

### ISSUE THREAD

**Issue by uablrek** [kubernetes/kubernetes#109215]
### What happened?

When creating a CRD object this error is printed;
```
Error from server (BadRequest): error when creating "/etc/kubernetes/default-spiffeid.yaml": SpiffeID in version "v1beta1" cannot be handled as a SpiffeID: strict decoding error: unknown field "metadata.annotations", unknown field "metadata.name", unknown field "metadata.namespace"
```
When trying to add the metadata fields in the CRD spec, this error is received;
```
The CustomResourceDefinition "spiffeids.spiffeid.spiffe.io" is invalid: spec.validation.openAPIV3Schema.properties[metadata]: Forbidden: must not specify anything other than name and generateName, but metadata is implicitly specified
```

### What did you expect to happen?

CDRs that worked in v1.23.x should work in v1.24.x. If there will be an NBC it should be preceeded with a warning printout before applied.

### How can we reproduce it (as minimally and precisely as possible)?

* CRD definition [spiffeid.spiffe.io_spiffeids.yaml.txt](https://github.com/kubernetes/kubernetes/files/8395007/spiffeid.spiffe.io_spiffeids.yaml.txt)
* CRD object [default-spiffeid.yaml.txt](https://github.com/kubernetes/kubernetes/files/8395009/default-spiffeid.yaml.txt)

```
# kubectl apply -f spiffeid.spiffe.io_spiffeids.yaml
# # kubectl apply -f default-spiffeid.yaml
Error from server (BadRequest): error when creating "default-spiffeid.yaml": SpiffeID in version "v1beta1" cannot be handled as a SpiffeID: strict decoding error: unknown field "metadata.annotations", unknown field "metadata.name", unknown field "metadata.namespace"
```

### Kubernetes version

```console
$ kubectl version
Client Version: v1.24.0-beta.0
Kustomize Version: v4.5.4
Server Version: v1.24.0-beta.0
```

### Cloud provider

N/A

### OS version

Linux custom install.

### Install tools

None

### Container runtime (CRI) and version (if applicable)

```
  07:44:06 crio version 1.22.0
```

### Related plugins (CNI, CSI, ...) and versions (if applicable)

N/A

**Comment by dims** [comment]
cc @liggitt

**Comment by liggitt** [comment]
/assign @kevindelgado 
cc @apelisse 
/kind regression 
/milestone v1.24

**Comment by liggitt** [comment]
It looks like this is an issue with CRDs which declare a metadata stanza:

```yaml
    schema:
      openAPIV3Schema:
        properties:
          metadata:
            type: object
          spec:
...
```

CRDs are only allowed to declare (at most) `name` and `generateName` properties within `metadata`. Pruning is supposed to ignore content within `metadata` and lean instead on direct decoding into the ObjectMeta type. The pruning bit is actually unit tested to not return "unknown field" errors for unknown fields within metadata, and appears to be working correctly *if* told it is pruning an object at the root:

https://github.com/kubernetes/kubernetes/blob/c6153a93d0528a3dc6be9dedc2602f140081688d/staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/schema/pruning/algorithm_test.go#L380-L535

However, where the custom resource handler calls `PruneWithOptions`, it is passing `false` for `isResourceRoot`:

https://github.com/kubernetes/kubernetes/blob/c6153a93d0528a3dc6be9dedc2602f140081688d/staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/customresource_handler.go#L1329-L1341

I'm not sure why... that doesn't seem correct. Switching that to pass `true` (since we *are* pruning at the root of the incoming object) fixes this bug.

*However*, in digging into this, I also noticed that strict server-side field handling isn't noticing unknown fields within `metadata` properly. That is currently done here:

https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/schema/objectmeta/algorithm.go#L25-L28

That uses json.Unmarshal internally, which ignores unknown fields. I think we need to propagate similar information about whether unknown field info is desired and propagate that back up. Otherwise, previous versions of kubectl using client-side validation notice unknown fields in metadata, and current kubectl with server-side validation doesn't:

```shell
more ~/tmp/default-spiffeid.yaml.txt 
```

```yaml
apiVersion: spiffeid.spiffe.io/v1beta1
kind: SpiffeID
metadata:
  name: default-spiffeid
  namespace: default
  unknown: true
spec:
  parentId: "spiffe://example.org/spire/server"
  selector:
    namespace: default
    serviceAccount: default
  spiffeId: "spiffe://example.org/ns/default/sa/default"
```

```
$ kubectl-1.20 apply -f ~/tmp/default-spiffeid.yaml.txt 
error: error validating "/Users/liggitt/tmp/default-spiffeid.yaml.txt": error validating data: ValidationError(SpiffeID.metadata): unknown field "unknown" in io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta_v2; if you choose to ignore these errors, turn validation off with --validate=false

$ kubectl apply -f ~/tmp/default-spiffeid.yaml.txt 
spiffeid.spiffeid.spiffe.io/default-spiffeid configured
```

Implementing unknown field recognition in the `metadata` coercion should be pretty straightforward (similar to the pruning bit), but is too big of a change post code-freeze, so I'd suggest the following:
1. add a test covering and fixing the bug reported here - https://github.com/kubernetes/kubernetes/pull/109268
2. switch the feature gate back to alpha for 1.24
3. add test coverage for how client-side validation catches unknown metadata fields before 1.24 test freeze
4. implement server-side unknown metadata field validation in 1.25 and promote to beta then

**Comment by liggitt** [comment]
Also opened https://github.com/kubernetes/kubernetes/issues/109275 since the client-side validation error citing "ObjectMeta_v2" looked weird

**Comment by uablrek** [comment]
Is there something "Spire" should correct? That is, shall I write an issue to them?

**Comment by liggitt** [comment]
No, it's an issue on our side.

**Comment by dims** [comment]
Thanks a ton for filing this @uablrek ! we are landing https://github.com/kubernetes/kubernetes/pull/109271 now for upcoming 1.24 rc.0 please be sure to try that too to confirm that you are unblocked.

**Comment by uablrek** [comment]
> for upcoming 1.24 rc.0 please be sure to try that too to confirm that you are unblocked.

Works with
```
v1.24.0-beta.0.69+92a1d0f84c7107
```

**Comment by dims** [comment]
@uablrek thanks Lars!
