### ISSUE TITLE
Pod Topology Spread Constraint limits scheduling decisions to one pod at a time

### ISSUE THREAD

**Issue by shreyas-s-rao** [kubernetes/kubernetes#109364]
### What happened?

My setup consists of the following topology:
1. Zone A - 2 nodes
2. Zone B - 1 node
3. There are no taints on any of the nodes
4. Pods do not have any node affinity/anti-affinity or pod affinity/anti-affinity defined on them

My Topology Spread Constraints are defined as:
```
topologySpreadConstraints:
- maxSkew: 1
  topologyKey: topology.kubernetes.io/zone
  whenUnsatisfiable: DoNotSchedule
  labelSelector:
    matchLabels:
      app: test
- maxSkew: 1
  topologyKey: kubernetes.io/hostname
  whenUnsatisfiable: DoNotSchedule
  labelSelector:
    matchLabels:
      app: test
```

I started with 3 replicas of a statefulset:
Observed behavior: As expected, each node got one pod each.

I scaled from 3 to 7 replicas:
Observed behavior:
1. Upto 5 replicas, it was able to schedule correctly across nodes and zones according to the topology spread constraints
2. The 6th and 7th replica remain in pending state, with the scheduler saying `"Unable to schedule pod; no fit; waiting" pod="default/test-5" err="0/3 nodes are available: 3 node(s) didn't match pod topology spread constraints."`

### What did you expect to happen?

Replica 6 violates TSCs:
- Cannot be scheduled to node12 because of zone constraint violation
- Cannot be scheduled to node21 because of node constraint violation
- Cannot be scheduled to node11 because of both zone and node constraint violations

![TSC-bug-6-replicas](https://user-images.githubusercontent.com/42259948/162191456-92e6240b-a989-45a2-aee0-d91802671a52.png)

In the above image, it is evident that replica 6 violates both the constraints, hence cannot be scheduled. This is a valid behavior when we scale from <=5 replicas to 6 replicas.

However, if we now scale from <=5 replicas to 7 replicas, then there is a possible arrangement of replicas across nodes/zones as shown below.

![TSC-bugfix-7-replicas](https://user-images.githubusercontent.com/42259948/162191472-8db40285-c954-42b9-98e6-6dc23e91bb88.png)

There are two expected behaviors from the Topology Spread Constraint feature:
1. If we directly scale up from 5 replicas to 7 replicas, then it should take into consideration the total delta when taking scheduling decisions, and not behave as if the replicas are being scaled up one at a time. This would ensure that when replicas is set to 7, all 7 replicas will get scheduled correctly.
2. If we scale up from 5 replicas to 6 replicas, which throws the 6th replica into `Pending` state, and _then_ scale up from 6 to 7 replicas, then both 6th and 7th replicas should be scheduled properly as expected, as now the total number of pods can be spread across the available nodes/zones and still satisfy the constraints.

### How can we reproduce it (as minimally and precisely as possible)?

Pretty easy to reproduce:
1. Start a cluster with 3 worker nodes with following labels each:
  a. Node1: `kubernetes.io/hostname=Node1`,`topology.kubernetes.io/zone=ZoneA`
  b. Node2: `kubernetes.io/hostname=Node2`,`topology.kubernetes.io/zone=ZoneA`
  c. Node3: `kubernetes.io/hostname=Node3`,`topology.kubernetes.io/zone=ZoneB`
2. Create a statefulset with above topology spread constraint, and specify label `app=test` in the pod spec, with replicas set to `3`
3. Scale the statefulset replicas as per the above-mentioned cases

### Anything else we need to know?

/cc @unmarshall @timuthy @vlerenc @ashwani2k

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"c285e781331a3785a7f436042c65c5641ce8a9e9", GitTreeState:"clean", BuildDate:"2022-03-16T15:58:47Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.6", GitCommit:"f59f5c2fda36e4036b49ec027e556a15456108f0", GitTreeState:"clean", BuildDate:"2022-01-19T17:26:47Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
AWS
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Garden Linux 576.3"
NAME="Debian GNU/Linux"
ID=debian
HOME_URL="https://gardenlinux.io/"
SUPPORT_URL="https://github.com/gardenlinux/gardenlinux"
BUG_REPORT_URL="https://github.com/gardenlinux/gardenlinux/issues"
GARDENLINUX_FEATURES=aws,_nopkg,_prod,_readonly,_slim,base,cloud,gardener,server
GARDENLINUX_VERSION=576.3
GARDENLINUX_COMMIT_ID=c7bb2e0f81d8bd8bdbad6b1229ed21da586e027c
VERSION_CODENAME=bookworm
$ uname -a
Linux ip-10-250-2-247.eu-west-1.compute.internal 5.10.0-garden-cloud-amd64 #1 SMP Debian 5.10.93-0gardenlinux1 (2022-01-24) x86_64 GNU/Linux
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>
containerd
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by ahg-g** [comment]
/remove-kind bug
/kind feature

This is working as intended, so it is not a bug, but certainly worth documenting.

What you are asking is worth the discussion, but I am not sure if it can reliably be implemented given that the scheduler is designed to schedule one pod at a time.

**Comment by unmarshall** [comment]
So there are 2 variants:

1. In the above example when we are currently at 5 replicas and we attempt to add 6th replica due to scaling up then it would just not be possible to continue the scaling post 6 (lets say 7) which would then not violate any TSC.
2. Directly jump from let's say 5 to 7 replicas.

We initially assumed that constraints enforcement and the actual scheduling are clearly separated and therefore it would just feel natural to enforce the constraints by looking at the delta between desired replicas and the actual replicas and not tie itself to how the scheduler would operate (i.e one pod at a time). 

In case (1) - when 6th replicas is stuck in pending, scaling up to 7 should still be allowed provided there is sufficient capacity to provision the replica onto a node/zone which satisfies the TSC's. Scaling down is allowed and works.

In case (2) - May be the reason could be that it's not always possible to gauge in advance if the additional replica(s) can be started on node(s)/zone(s) given that the resource consumptions could vary by the time additional pods start. But i am just speculating as to the reason for the current behavior. May be the implementers/maintainers can throw some light on the reasons for taking the current approach.

**Comment by sathyanarays** [comment]
In the example given in this issue, if the number of pods is 8 or above, there is no way to schedule pods with the given constraints. We cannot validate the replica count since the validation time complexity increases exponentially as the number of pods grow. 

We can avoid such problems by restricting the choice that we provide. For example, we can restrict to have only one Topology Spread Constraint per pod or we can allow non overlapping constraints.

We can use `whenUnsatisfiable: ScheduleAnyway` as specified in the [documentation](https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/#example-conflicting-topologyspreadconstraints)
