### ISSUE TITLE
Propose LabelSelector to support `Regexp` operator

### ISSUE THREAD

**Issue by astraw99** [kubernetes/kubernetes#109400]
### What would you like to be added?

Currently, the `LabelSelector` and `selection` Operator supports:
```go
const (
	LabelSelectorOpIn           LabelSelectorOperator = "In"
	LabelSelectorOpNotIn        LabelSelectorOperator = "NotIn"
	LabelSelectorOpExists       LabelSelectorOperator = "Exists"
	LabelSelectorOpDoesNotExist LabelSelectorOperator = "DoesNotExist"
	LabelSelectorOpRegexp       LabelSelectorOperator = "Regexp" // new
)

const (
	DoesNotExist Operator = "!"
	Equals       Operator = "="
	DoubleEquals Operator = "=="
	In           Operator = "in"
	NotEquals    Operator = "!="
	NotIn        Operator = "notin"
	Exists       Operator = "exists"
	GreaterThan  Operator = "gt"
	LessThan     Operator = "lt"
	Regexp       Operator = "regexp" // new
)
```

We'd like to propose LabelSelector to support `Regexp` operator, to meet more label selection requirements.

### Why is this needed?

In some senarios, we have the request to get resource objects by regexp, e.g: `^foo.*`, support different types of query, like prefix or suffix.

Currently the operators could not meet the requirments, so we propose to support it.

**Comment by liggitt** [comment]
Thanks for the feature request, but this is unlikely to make progress as an issue. Things along these lines have been requested many times for selectors. Past related requests / discussions:
* https://github.com/kubernetes/kubernetes/issues/72196#issuecomment-971920747
* https://github.com/kubernetes/kubernetes/issues/72196#issuecomment-972002671 (link to discussion in api-machinery meeting)
* https://github.com/kubernetes/kubernetes/issues/107053
* https://github.com/kubernetes/kubernetes/issues/107285

The primary things that have prevented this from being pursued in the past are:
* it's unclear what use cases this is needed for that are 1) desired and 2) could not be satisfied by addition of a common label existing selectors would work with (e.g. add a label `foo` in addition to `foo-123`)
* performance implications and additional vectors for abuse (since selectors are evaluated server-side)
* backwards-compatibility implications for API clients using new selectors against old servers
* backwards-compatibility implications for API object specifications using new operators against old servers
* backwards-compatibility implications for clients consuming new selectors

A proposal that works through those issues along with the implications of such a change can be opened as a [KEP](https://github.com/kubernetes/enhancements/tree/master/keps#kubernetes-enhancement-proposals-keps).

I'll also note that there are already validation gaps with existing selector syntax (e.g. https://github.com/kubernetes/kubernetes/issues/99139). Expansion of selector syntax is unlikely to be considered until the existing problems are resolved.

/close

**Comment by astraw99** [comment]
Got it, thanks :)
