### ISSUE TITLE
capz-windows-containerd-master occasionally hangs during workload cluster creation

### ISSUE THREAD

**Issue by marosset** [kubernetes/kubernetes#109444]
### Which jobs are flaking?

[capz-windows-containerd-master](https://testgrid.k8s.io/sig-windows-signal#capz-windows-containerd-master)

### Which tests are flaking?

Cluster failures to provision 

### Since when has it been flaking?

It has been failing since at least 3/30.

We've seen similar failurs on
- 3/30/2022
- 4/2/2022
- 4/4/2022
- 4/5/2022
- 4/7/2022
- 4/12/2022

### Anything else we need to know?

```
INFO: Waiting for the cluster infrastructure to be provisioned
[1mSTEP[0m: Waiting for cluster to enter the provisioned phase
INFO: Waiting for control plane to be initialized
INFO: Waiting for the first control plane machine managed by capz-conf-cs4sxe/capz-conf-cs4sxe-control-plane to be provisioned
[1mSTEP[0m: Waiting for one control plane node to exist
INFO: Waiting for control plane to be ready
INFO: Waiting for control plane capz-conf-cs4sxe/capz-conf-cs4sxe-control-plane to be ready (implies underlying nodes to be ready as well)
[1mSTEP[0m: Waiting for the control plane to be ready
INFO: Waiting for the machine deployments to be provisioned
[1mSTEP[0m: Waiting for the workload nodes to exist
[1mSTEP[0m: Waiting for the workload nodes to exist
[AfterEach] Conformance Tests
  /home/prow/go/src/sigs.k8s.io/cluster-api-provider-azure/test/e2e/conformance_test.go:231
[1mSTEP[0m: Dumping logs from the "capz-conf-cs4sxe" workload cluster
[1mSTEP[0m: Dumping workload cluster capz-conf-cs4sxe/capz-conf-cs4sxe logs
Apr 12 12:28:18.917: INFO: INFO: Collecting logs for node capz-conf-cs4sxe-control-plane-fw5jf in cluster capz-conf-cs4sxe in namespace capz-conf-cs4sxe

Apr 12 12:28:30.913: INFO: INFO: Collecting boot logs for AzureMachine capz-conf-cs4sxe-control-plane-fw5jf

Apr 12 12:28:32.097: INFO: INFO: Unable to collect logs as node doesn't have addresses
Apr 12 12:28:32.097: INFO: INFO: Collecting logs for node capz-conf-cs4sxe-md-win-jn6rx in cluster capz-conf-cs4sxe in namespace capz-conf-cs4sxe

Apr 12 12:28:38.964: INFO: INFO: Collecting boot logs for AzureMachine capz-conf-cs4sxe-md-win-jn6rx

[1mSTEP[0m: Redacting sensitive information from logs

[91m[1m• Failure [1538.442 seconds][0m
Conformance Tests
[90m/home/prow/go/src/sigs.k8s.io/cluster-api-provider-azure/test/e2e/conformance_test.go:48[0m
  [91m[1mconformance-tests [Measurement][0m
  [90m/home/prow/go/src/sigs.k8s.io/cluster-api-provider-azure/test/e2e/conformance_test.go:103[0m

  [91mTimed out after 1200.001s.
  Expected
      <int>: 0
  to equal
      <int>: 2[0m

  /home/prow/go/pkg/mod/sigs.k8s.io/cluster-api/test@v1.1.2/framework/machinedeployment_helpers.go:121
```

### Relevant SIG(s)

/sig windows

**Comment by claudiubelu** [comment]
Hello,

Slightly unrelated, but I see this Warning in the cloudbase-init logs:

```
2022-04-28 15:14:06.975 4244 WARNING cloudbaseinit.utils.log [-] Serial port: COM1,115200,N,8 could not be opened: serial.serialutil.SerialException: could not open port 'COM1': FileNotFoundError(2, 'The system cannot find the file specified.', None, 2) 
```

Apprently, there is no ``COM1`` serial port present for the Azure Windows nodes, it seems. There is ``COM2`` however:

```
PS C:\Users\capi> &'C:\Program Files\Cloudbase Solutions\Cloudbase-Init\Python\python.exe' -m serial.tools.list_por
ts
COM2
1 ports found
```

So, the ``logging_serial_port_settings`` cloudbase-init config option could be updated to something like ``COM2,115200,N,8``. This will mean that at the very least the cloudbase-init logs could be collected through the VM's serial console, even though the VM itself has no network connectivity. This should help us figure out what happened during provisioning. Now, at this point, I'm not sure that ``cluster-api-provider-azure/test/e2e/conformance_test.go`` is able to collect the serial console logs, but if not, it would be a great addition. Although, from what I can see in the logs you've posted above, ``cluster-api-provider-azure/test/e2e/conformance_test.go`` won't even consider the nodes that failed to provision, which would make this problematic.

Now, as for why the provisioning failed: basically, cloudbase-init automatically detects which metadata service it has to use. In our case, it should be the Azure Metadata Service. However, it seems that it failed to detect it, which then meant it couldn't pull the metadata it needed to continue its job. Also, because there's no metadata service detected, it cannot update the VM status to the Provisioned Started / Failed / Completed state, hence the timeout after 30 minutes (whom to update, how to update?).

As to why it didn't detect it needs the Azure Metadata Service: basically, it tries to detect if it can contact the Azure Wire Server by making a DHCP request, but the socket timeout is 5 seconds, and I assume that timed out. I also notice that this is the only dependency for the cloudbase-init: ``DEPENDENCIES       : Winmgmt``, which is not Networking related. I think there's a possibility that cloudbase-init started before the networking started, resulting in this issue. A solution might be to add another networking dependency to ``cloudbase-init``, ensuring that it will start afterwards. Other than that, the 5 second timeout could be touched, IMO (maybe the Azure Security Group rules are not applied yet before the VM starts?).

**Comment by jsturtevant** [comment]
> So, the logging_serial_port_settings cloudbase-init config option could be updated to something like COM2,115200,N,8. This will mean that at the very least the cloudbase-init logs could be collected through the VM's serial console, even though the VM itself has no network connectivity. This should help us figure out what happened during provisioning. Now, at this point, I'm not sure that cluster-api-provider-azure/test/e2e/conformance_test.go is able to collect the serial console logs, but if not, it would be a great addition

Thanks for the tip, I can fix that port in image-builder. On a successful run we do collect the serial logs: https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-capz-master-containerd-windows/1520054825100775424/artifacts/clusters/capz-conf-uqwoqv/machines/capz-conf-uqwoqv-md-win-558d8b96b5-njttt/boot.log  I think it will show up there?  Might need to tweek the code that pulls that to work even on failed vms.

> As to why it didn't detect it needs the Azure Metadata Service: basically, it tries to detect if it can contact the Azure Wire Server by making a DHCP request, but the socket timeout is 5 seconds, and I assume that timed out. I also notice that this is the only dependency for the cloudbase-init: DEPENDENCIES : Winmgmt, which is not Networking related.

Had a similar [thought](https://github.com/cloudbase/cloudbase-init/issues/94#issuecomment-1113548934).  Where do you see the ` DEPENDENCIES : Winmgmt`?

**Comment by jsturtevant** [comment]
Found it: https://github.com/cloudbase/cloudbase-init-installer/blob/8ca6f0e24c700302fde8e3527a7778bdbb1b0e12/CloudbaseInitSetup/Product.wxs#L225

**Comment by luckerby** [comment]
Ran into this yesterday as well. As discussed with @jsturtevant I'm adding the link to the relevant logs [here](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/110075/pull-kubernetes-e2e-capz-windows-containerd/1527045280405393408).

**Comment by jsturtevant** [comment]
we are testing a fix here https://github.com/cloudbase/cloudbase-init/issues/94#issuecomment-1132286138. We are pretty close to getting a working fix.

**Comment by jsturtevant** [comment]
this is mitigated now, waiting on official release for Cloudbase-init but have a patch in place that has resolved the issue.

**Comment by marosset** [comment]
Issue has been resolved with a private drop of cloudbase-init.
We'll keep this open until those changes are releases officially.

**Comment by Namanl2001** [comment]
@marosset @jsturtevant - we're getting the same failure again.

testgrid link: https://testgrid.k8s.io/sig-release-master-informing#capz-windows-containerd-master

**Comment by jsturtevant** [comment]
resolved with a new relase of cloudbase-init
/close
