### ISSUE TITLE
E2E framework/pod WaitForPodCondition silently ignores condition errors.

### ISSUE THREAD

**Issue by tallclair** [kubernetes/kubernetes#109732]
`wait.Poll` treats any error returned by the condition as terminal, but `e2epod.WaitForPodCondition` silently ignores any errors that aren't returned along with `done=true`. We should change WaitForPodCondition to behave like `wait.Poll`.

/sig testing
/area e2e-test-framework

**Comment by pohly** [comment]
@tallclair Was there any reason why you added [a TODO](https://github.com/kubernetes/kubernetes/blob/661899f1a14680840e06c84bc3ff46f73d203012/test/e2e/framework/pod/wait.go#L271) instead of doing this right away?

I fully agree with this issue, we should abort early. I just found the TODO because I have a failing test that ran longer than expected after a final pod failure and that made me check out why it didn't abort quicker :grin:
