### ISSUE TITLE
Error while deploying on 3 nodes

### ISSUE THREAD

**Issue by adyanthaya17** [kubernetes/kubernetes#10973]
Hi,

I've been following the ubuntu.md document to build my kubernetes cluster. Previously I have deployed the master and minion (1 master and 2 minions) on two nodes successfully. I added another new node for the minion but the kube-up.sh command seems to be looping asking for the third nodes password.

I know the document states for deployment of 3 nodes and it has to work but in my case it isn't.

**Comment by mbforbes** [comment]
@adyanthaya17 I'm so sorry this issue fell between the cracks! Were you able to figure it out? Can you provide us with the looping you're talking about?

+cc @roberthbailey in case he has time to look at this tomorrow (I really can't tonight, unfortunately)

**Comment by goltermann** [comment]
We’re going through old support issues and asking everyone to direct your questions to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes). 

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases. 

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.
