### ISSUE TITLE
Better kubectl exec

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#10975]
Forked from #1513

@smarterclayton said:

Now that exec has landed and is looking pretty stable, some followups to look at:
### Variants on nsenter that are more aligned with the container

We've talked before about extending nsinit from docker to be a true "execute in running Docker container" process, like rockets' equivalent.
### Taking the proxies out of the loop (or at least, the kubelet proxy)

Instead of using nsenter to run the user process, use nsenter to start a process in the container with a predetermined port and secret that would listen for a subsequent connection.  The kubelet could then redirect the response back to the caller with the port and location, and the caller can connect directly to the process.  The stub process would then do the necessary exec to launch the child and clean up after itself.  Important part is that this would make the network I/O part of the container's cgroup, not the kubelets.
### Pattern for launching SSHD in a container via exec

Launch SSHD via exec, then terminate the exec connection and connect from the client directly to a port.  Might be a simple package you could install into your container.
### On demand port proxy

Be able to request using your credentials that a new, random port be exposed through the cluster so you can access a container from anywhere that can reach a master.  The port might only accept one connection or require a specific source IP

**Comment by MikaelCluseau** [comment]
For a personal project, I did a SFTP gateway+endpoint to access volumes with for instance `sftp namespace.volume@gateway` and a key auth, all in pure Go. May I specify that somewhere if it can address part of this need?
I think a pure-go thing could allow the endpoint (probably the kubelet in this case?) to fork and jump in the container's namespace, avoiding the SSHD-exec thing, removing the need to install sshd in the container (but a shell will still be required for interactive sessions).

**Comment by bprashanth** [comment]
@ncdc @kubernetes/kubectl maybe we can prioritize this?
* a lot of e2es rely on exec functionality and it's a big developer time sink to root cause. 
* docker exec has historically also been unstable: https://github.com/docker/docker/issues/14444, https://github.com/kubernetes/kubernetes/issues/34256, https://github.com/kubernetes/kubernetes/issues/25456, https://github.com/kubernetes/kubernetes/issues/10659
* execProbe as a feature is unstable if it relies on docker exec (this is why kubedns uses an exec over http probe instead), replacing it as part of this effort sounds like a net win

**Comment by ncdc** [comment]
@bprashanth sure, although the latest test flakes appear to be because of a bug in docker and the only item from the list at the top that would potentially address that is "Variants on nsenter that are more aligned with the container". I think @kubernetes/sig-node is probably a more appropriate team to weigh in on that aspect than @kubernetes/kubectl.

@mrunalp @runcom are we any closer to having an alternative to `docker exec` to exec a command in a container, maintaining the container's environment, cgroups, etc?

**Comment by bprashanth** [comment]
Yeah i think this will probably have to be a cross team effort to make it easier to debug/more stable. Agree  docker exec instability is probably biggest contributor, but that's not to say we don't gain anything by having fewer proxies. 

I think:

> Taking the proxies out of the loop (or at least, the kubelet proxy)

proposal is something like what we're already planning for cri.

**Comment by mrunalp** [comment]
@ncdc With docker 1.11+, one can use runc exec instead of docker for exec.

**Comment by vishh** [comment]
Does `runc exec` also setup the environment appropriately (caps, env, etc.)?

**Comment by mrunalp** [comment]
@vishh Yes, whatever docker exec supports is supported by runc exec because that's what is used under the hood starting with docker 1.11.

**Comment by AdoHe** [comment]
@mrunalp really good news.

**Comment by kargakis** [comment]
Can't find a @kubernetes/sig-node-misc team @kubernetes/sig-node-feature-requests

**Comment by brandonkal** [comment]
Was this supposed to be closed? @thockin
