### ISSUE TITLE
Why is there no clusterRoleBinding that binds the kubelet-bootstrap with the ClusterRole system:node-bootstrapper

### ISSUE THREAD

**Issue by lunhuijie** [kubernetes/kubernetes#109885]
group system:bootstrappers is existed and role system:node-bootstrapper is existed;
but no clusterRoleBinding 
why do this?

sometimes I need group system:bootstrappers have this permission only by creating it by myself after cluster is ready.

**Comment by liggitt** [comment]
it's not a given all cluster deployers want those permissions granted to that group in perpetuity

granting permissions to a group is easier, but less secure. granting permissions to a single bootstrapper user is more fiddly, but more secure. rather than bake that decision into roles set up by kube-apiserver, it is made part of deployment flows
