### ISSUE TITLE
[failing-test] SIG-Scalability as of May 9th

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#109915]
Context: Tests marked as failing in https://storage.cloud.google.com/k8s-metrics/failures-latest.json

CI Job | Days | URL
-- | -- | --
ci-kubernetes-e2e-gci-gce-scalability-node-killer | 298 | https://testgrid.k8s.io/sig-scalability-experiments#gce-cos-master-scalability-100-nodekiller
ci-kubernetes-kubemark-100-gce-scheduler-highqps | 504 | https://testgrid.k8s.io/sig-scalability-kubemark#kubemark-100-scheduler-highqps
ci-kubernetes-storage-scalability | 573 | https://testgrid.k8s.io/sig-scalability-experiments#storage

/sig scalability
/kind failing-test

cc @marseel @wojtek-t

**Comment by wojtek-t** [comment]
/triage accepted

/assign - I will take a look at storage tests.

/assign @mborsz 
@mborsz - will you be able to take a look (or delegate) the node-killer ones

And I'm wondering what the scheduler-high-qps test actually is... Do we need it? Can we get rid of it?

**Comment by wojtek-t** [comment]
Hmm - the storage failures are strange. Basically all of tests are failing because of things like this:
```
E0510 18:57:57.057996   14419 test_metrics.go:226] TestMetrics: [action start failed for SchedulingMetrics measurement: unknown (get pods https:kube-scheduler-e2e-a80624f4e4-86a3e-master:10259)]
```

Those failures are basically coming from here:
https://github.com/kubernetes/perf-tests/blob/master/clusterloader2/pkg/measurement/common/scheduler_latency.go#L303-L314

This is extremely strange, because the same code-path is used for gazilion of other tests and it works, e.g. for our main 100-node tests - I tried testing it with: Test PR: https://github.com/kubernetes/perf-tests/pull/2062/files
It should only matter on how the cluster is set up - and in all tests we're using gce kube-up...

**Comment by ameukam** [comment]
/remove-lifecycle stale

2/3 are still failing

**Comment by wojtek-t** [comment]
All fixed now. Closing.
