### ISSUE TITLE
[failing-test] SIG Cloud Provider AWS tests

### ISSUE THREAD

**Issue by nckturner** [kubernetes/kubernetes#109984]
Triage failing AWS tests in https://storage.cloud.google.com/k8s-metrics/failures-latest.json

ref: https://github.com/kubernetes/kubernetes/issues/109913

/assign @nckturner   

/area provider/aws
/sig cloud-provider
/kind failing-test

**Comment by nckturner** [comment]
Currently listed:

```
  },
  "e2e-kops-aws-misc-karpenter": {
    "failing_days": 136
  },
  "pr:pull-kops-e2e-aws-karpenter": {
    "failing_days": 130
  },
```

https://k8s-testgrid.appspot.com/google-aws#kops-aws-misc-karpenter
https://k8s-testgrid.appspot.com/kops-presubmits#pull-kops-e2e-aws-karpenter

@ellistarn or @rifelpet are you familiar with these tests?

**Comment by rifelpet** [comment]
We're working on getting those fixed, starting with https://github.com/kubernetes/kops/pull/13547 but the jobs are now failing because apparently AWS CCM merges to release branches overwrite the `latest` image tag and the version string panic (https://github.com/kubernetes/cloud-provider-aws/issues/339) has regressed:

https://storage.googleapis.com/kubernetes-jenkins/logs/e2e-kops-aws-misc-karpenter/1524547986720296960/artifacts/cluster-info/kube-system/aws-cloud-controller-manager-2mnp5/logs.txt

so we need the AWS CCM image stabilized first before we can continue troubleshooting
