### ISSUE TITLE
[failing-test] SIG-Cloud Provider as of May 9th

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#109913]
Context: Tests marked as failing in https://storage.cloud.google.com/k8s-metrics/failures-latest.json

CI Job | Days | URL
-- | -- | --
ci-kubernetes-e2e-gci-gce-flaky | 175 | https://testgrid.k8s.io/sig-api-machinery-gce-gke#gce-flaky
ci-kubernetes-soak-gce-gci | 52 | https://testgrid.k8s.io/google-soak#gce-gci
ci-kubernetes-soak-gci-gce-beta | 451 | https://testgrid.k8s.io/google-soak#gce-gci
ci-kubernetes-soak-gci-gce-stable1 | 519 | https://testgrid.k8s.io/google-gce#soak-gci-gce-1.14
ci-kubernetes-soak-gci-gce-stable3 | 116 | https://testgrid.k8s.io/google-gce#soak-gci-gce-1.15
cloud-provider-azure-multiple-zones | 217 | https://testgrid.k8s.io/provider-azure-cloud-provider-azure#cloud-provider-azure-multiple-zones
cloud-provider-azure-slow-capz | 75 | https://testgrid.k8s.io/provider-azure-cloud-provider-azure#cloud-provider-azure-slow-capz

/kind failing-test
/sig cloud-provider

**Comment by nckturner** [comment]
The link you provided (https://storage.cloud.google.com/k8s-metrics/failures-latest.json) shows more failing tests (at least today, 5/11) linked to cloud providers than you provided here.  Is there a reason you listed only the tests above or is everything listed in failures-latest.json worth attention?

**Comment by lzhecheng** [comment]
`cloud-provider-azure-slow-capz` job has been recovered. The case `LoadBalancers should be able to create an internal type load balancer` was failing because of a bug in k/k test code, which can be exposed by CAPZ clusters (now), but not aks-engine clusters (before).
Now the bug has been fixed: https://github.com/kubernetes/kubernetes/pull/109413
Due to the fact that the fix won't be in release branch soon. I skipped the case in `cloud-provider-azure-slow-capz` but added it to other cloud-provider-azure ccm jobs: https://github.com/kubernetes-sigs/cloud-provider-azure/pull/1706. So the testcase is continuously verified by CI.

**Comment by lzhecheng** [comment]
cloud-provider-azure-multiple-zones has been replaced by a new job cloud-provider-azure-conformance-multiple-zones-vmss-capz
https://testgrid.k8s.io/provider-azure-cloud-provider-azure#cloud-provider-azure-conformance-multiple-zones-vmss-capz
