### ISSUE TITLE
Fix reporting of Reason in Kubelet

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#11007]
First of all, Reason (everywhere in the API) is intended to be a concise, single-world, CamelCase categorization of the status. However, Kubelet is producing phrases, which more properly belong in a Message field. For example:
https://github.com/GoogleCloudPlatform/kubernetes/blob/7bb9cdf660a00e231d9dcd1a7c9c5985399fb977/pkg/kubelet/dockertools/manager.go#L458
```
				Reason: fmt.Sprintf("Image: %s is ready, container is creating", image),
```

Secondly, important cases are somehow being dropped. Here's an example of a single-container pod, where the container must be Waiting, probably during image pull:
```bash
$ kubectl get pods
NAME          READY     STATUS    RESTARTS   AGE
hello-world   0/1       Running   0          7s
```
kubectl get pods shouldn't say "Running" for pods whose images aren't pulled.

Not sure if the reason is being clobbered or something else is happening:
https://github.com/GoogleCloudPlatform/kubernetes/blob/7bb9cdf660a00e231d9dcd1a7c9c5985399fb977/pkg/kubelet/dockertools/manager.go#L469

I wouldn't 100% rule out kubectl, but the logic there is pretty straightforward.

cc @andronat

**Comment by yujuhong** [comment]
> First of all, Reason (everywhere in the API) is intended to be a concise, single-world, CamelCase categorization of the status. However, Kubelet is producing phrases, which more properly belong in a Message field

The [PodStatus.Reason](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/api/v1/types.go#L903) needs to be a single CamelCase word. However, all [ContainerState](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/api/v1/types.go#L748)s, and a couple of other "Reason" fields only requires the reason to be "(brief)". E.g., 
[PersistentVolumeStatus](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/api/v1/types.go#L287),  and [NodeCondition](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/api/v1/types.go#L1323)

kubectl uses PodStatus.Reason if it exists, and falls back to looking at the Reason in the container state. That's why sometimes kubectl returns long reasons.
We can fix this by making all "Reason" CamelCase, but many of them do not have a "Message" field. We'd either have to add more "Message" fields or compromise on the clarity. 

> Secondly, important cases are somehow being dropped. Here's an example of a single-container pod, where the container must be Waiting, probably during image pull:

If the image hasn't be pulled, kubelet should not report `Running`. This would be a bug. Do you have other information that indicate the pod may be waiting for the image to pull?

On the other hand, I don't see why this pod *must* be in the pending/waiting state.
- "Running" means that the all containers have been started for the pod.
- "Ready" means the container has passed the readiness check.

A pod can be in the "Running" state even though containers do not pass readiness checks (yet).

There are other cases where a ready container would appear not ready (while the pod is "Running"): 
 1. If the `InitialDelaySeconds` of the readiness check is set to non-zero, the container would stay not ready until the delay has passed.
 2. After kubelet starts the containers, it does not immediately perform the readiness check. Thus the containers would stay unready until the next sync. We can consider performing the extra probe to eliminate the at most 10 second delay.

**Comment by andronat** [comment]
I am +1 for adding a message field for verbose explanation

**Comment by bgrant0607** [comment]
Yes, we should add a Message field. I will add this to api-conventions.md.

**Comment by bgrant0607** [comment]
I'll see if I can reproduce the scenario and dump the json.

**Comment by bgrant0607** [comment]
There was no readiness probe defined for the container.

**Comment by yujuhong** [comment]
> I'll see if I can reproduce the scenario and dump the json.

That'd be helpful. Thanks!

> There was no readiness probe defined for the container.

It's likely to be the second case in my previous https://github.com/GoogleCloudPlatform/kubernetes/issues/11007#issuecomment-120127523
"After kubelet starts the containers, it does not immediately perform the readiness check. Thus the containers would stay unready until the next sync. We can consider performing the extra probe to eliminate the at most 10 second delay."
Even when there is *NO* readiness check defined, kubelet would still need to perform probing (which'd always be true) to set the readiness in its cache. This would be done in the next sync (~10 seconds later). I can see this being confusing, so we should probably fix it by forcing the extra probe after creating the containers.

**Comment by bgrant0607** [comment]
That indeed sounds like the problem.

**Comment by yujuhong** [comment]
Filed #11234 for fixing the readiness confusion; leaving this bug for the reason/message issue.

**Comment by bgrant0607** [comment]
@yaoguo: I'd appreciate a fix to this, also, if you're hunting for useful things to do.

**Comment by hurf** [comment]
@jiangyaoguo

**Comment by jiangyaoguo** [comment]
@bgrant0607 @hurf  I'll look into this and fix it.

**Comment by bgrant0607** [comment]
Thanks for the correction, @hurf.
