### ISSUE TITLE
Kubernetes Token Controller is not working at v1.24

### ISSUE THREAD

**Issue by cagatayatabay** [kubernetes/kubernetes#110113]
### What happened?

I installed kubernetes 1.24, cluster is up and healthy but when i try to install kubernetes-dashboard, i realized can not access dashboard token. Before 1.24 i just describe token and get.

Normally when sa created, secret should be created automaticaly, BUT NOW, I just tried create service account then secret not created automaticaly.

just create sa with: "kubectl create serviceaccount servicename" you should see secret as a servicename-token with kubectl get secrets. But not created..

### What did you expect to happen?

-----

### How can we reproduce it (as minimally and precisely as possible)?

-

### Kubernetes version

$ kubectl version
# "v1.24

### Cloud provider

onprem

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by Shubham82** [comment]
Hi @cagatayatabay 
This is due to the `LegacyServiceAccountTokenNoAutoGeneration` feature gate which is in beta(enabled by default) in k8sv1.24.

> The LegacyServiceAccountTokenNoAutoGeneration feature gate is beta and enabled by default. When enabled, Secret API objects containing service account tokens are no longer auto-generated for every ServiceAccount. Use the [TokenRequest](https://kubernetes.io/docs/reference/kubernetes-api/authentication-resources/token-request-v1/) API to acquire service account tokens, or if a non-expiring token is required, create a Secret API object for the token controller to populate with a service account token by following this [guide](https://kubernetes.io/docs/concepts/configuration/secret/#service-account-token-secrets).

See this [KEP:2799](https://github.com/kubernetes/enhancements/tree/master/keps/sig-auth/2799-reduction-of-secret-based-service-account-token) and PR: #108309

 From now you have to [manually create a service account API token](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#manually-create-a-service-account-api-token).  or you can also create a token for service account by using` kubectl create token <sa name>  --namespace <name>` to authenticate to the kube-apiserver as the service account  which is [implemented](https://github.com/kubernetes/kubernetes/pull/107880) in v1.24.

**Comment by cagatayatabay** [comment]
> Hi @cagatayatabay This is due to the `LegacyServiceAccountTokenNoAutoGeneration` feature gate which is in beta(enabled by default) in k8sv1.24.
> 
> > The LegacyServiceAccountTokenNoAutoGeneration feature gate is beta and enabled by default. When enabled, Secret API objects containing service account tokens are no longer auto-generated for every ServiceAccount. Use the [TokenRequest](https://kubernetes.io/docs/reference/kubernetes-api/authentication-resources/token-request-v1/) API to acquire service account tokens, or if a non-expiring token is required, create a Secret API object for the token controller to populate with a service account token by following this [guide](https://kubernetes.io/docs/concepts/configuration/secret/#service-account-token-secrets).
> 
> See this [KEP:2799](https://github.com/kubernetes/enhancements/tree/master/keps/sig-auth/2799-reduction-of-secret-based-service-account-token) and PR: #108309
> 
> From now you have to [manually create a service account API token](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#manually-create-a-service-account-api-token). or you can also create a token for service account by using` kubectl create token <sa name> --namespace <name>` to authenticate to the kube-apiserver as the service account which is [implemented](https://github.com/kubernetes/kubernetes/pull/107880) in v1.24.

Great, thanks!

**Comment by Shubham82** [comment]
Hi @icebear74

It is shown under `Tokens` when you describe the serviceaccount.

For example:
1) create serviceaccount with the following sa.yaml kubectl apply -f sa.yaml -n abc:

> apiVersion: v1
> kind: ServiceAccount
> metadata:
>   name: sa-abc
> 

2) Describe the pod using command `kubectl describe sa sa-abc` you will see output like this:
```
Name:                sa-abc
Namespace:           abc
Labels:              <none>
Annotations:         <none>
Image pull secrets:  <none>
Mountable secrets:   <none>
Tokens:              <none>
Events:              <none>
```
Nothing is present under token because we don't attach any token to serviceaccount till now.

3) Create secrets using the following sec.yaml `kubectl apply -f sec.yaml -n abc`:

> apiVersion: v1
> kind: Secret
> metadata:
>   name: sec-abc
>   annotations:
>     kubernetes.io/service-account.name: sa-abc
> type: kubernetes.io/service-account-token

4) Now describe serviceaccount again `kubectl describe sa sa-abc` :

```
Name:                sa-abc
Namespace:           abc
Labels:              <none>
Annotations:         <none>
Image pull secrets:  <none>
Mountable secrets:   <none>
Tokens:              sec-abc
Events:              <none>
```
Not the secret(having token) which we created above for sa is mentioned under the `Tokens` field.

**Comment by liggitt** [comment]
The `secrets` field of the service account is only for listing secrets that can be mounted into pods running as the service account. From https://kubernetes.io/docs/reference/kubernetes-api/authentication-resources/service-account-v1/#ServiceAccount:

> `Secrets` is a list of the secrets in the same namespace that pods running using this ServiceAccount are allowed to use. Pods are only limited to this list if this service account has a "kubernetes.io/enforce-mountable-secrets" annotation set to "true". This field should not be used to find auto-generated service account token secrets for use outside of pods. Instead, tokens can be requested directly using the TokenRequest API, or service account token secrets can be manually created. More info: https://kubernetes.io/docs/concepts/configuration/secret

Secrets have not been used for mounting into pods since 1.22, when injected tokens switched to using tokens obtained from the `TokenRequest` API and mounted using projected service account tokens.

Using `kubectl create token` get obtain a time-bound token is recommended instead of using secret-based tokens. The docs for obtaining a token for the dashboard have an update pending at https://github.com/kubernetes/dashboard/pull/6967 to use that.

If a non-expiring token is required, you can manually create a secret to request that following the instructions at https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#manually-create-a-service-account-api-token

/close
