### ISSUE TITLE
Add endpoint tag to apiserver_admission_webhook_admission_* metrics

### ISSUE THREAD

**Issue by SOF3** [kubernetes/kubernetes#110315]
### What would you like to be added?

When aggregator routing is enabled, kube-apiserver creates a direct connection to one of the webhook service endpoints for admission webhooks configured through services. The address and port of the selected endpoint can be added as a tag to the apiserver_admission_webhook_admission_\* metrics.

### Why is this needed?

apiserver may be suffering from latency issues with particular endpoints due to issues with network configuration. Classifying latency metrics based on endpoint helps identifying such issues.

/sig api-machinery

**Comment by aojea** [comment]
> apiserver may be suffering from latency issues with particular endpoints due to issues with network configuration. Classifying latency metrics based on endpoint helps identifying such issues.

can not this be a problem with metric cardinality explosion?

**Comment by dgrisonnet** [comment]
From a quick look, this sounds similar to https://github.com/kubernetes/kubernetes/pull/108468

**Comment by liggitt** [comment]
address / port as labels on the metric seem like they would cause excessive cardinality, right?

**Comment by SOF3** [comment]
> address / port as labels on the metric seem like they would cause excessive cardinality, right?

Yes if you have a huge amount of pods for the webhook server. Doesn't sound very excessive if there are only a small number (say 3) instances.

Could this be an opt-in feature where the tag is only provided if the webhook configuration has the annotation `admission.k8s.io/include-endpoint-tag: true`?

**Comment by dgrisonnet** [comment]
> Could this be an opt-in feature where the tag is only provided if the webhook configuration has the annotation admission.k8s.io/include-endpoint-tag: true? Alternatively, a feature gate in the apiserver?

The metric is stable so we shouldn't change it at any cost.

> apiserver may be suffering from latency issues with particular endpoints due to issues with network configuration.

I understand what you are trying to measure, but network monitoring should be done at the network level, not at the microservice level. Today, the existing webhook metrics should give you all the information you need about the latency of a particular webhook and if you need to know whether unexpected latency is caused by the network or not then you should look into metrics from network.

That said, we've recently invested into correlation between metrics, logs and traces. Once the work is done (most likely in a few releases), you will be able to go from metrics to audit logs to traces which would allow you to know exactly where time was spent for a particular request.

**Comment by logicalhan** [comment]
Yeah, this is a stable metric, we can't actually modify this metric anymore, not even considering the cardinality issues that this would cause.
