### ISSUE TITLE
Allow compression of json response body using Accept-Encoding header

### ISSUE THREAD

**Issue by ilackarms** [kubernetes/kubernetes#110349]
JSON payload returned by Kubernetes can be very large on GET requests when there are a lot of managed resources in the cluster.

Currently it is not possible to specify that large response bodies should be compressed; `Accept-Encoding` header is ignored by the apiserver.

Specifying the Accept-Encoding header on a GET request should cause the k8s apiserver to respond with response Body compressed with the given encoding sceme (e..g gzip, bzip2, etc.)

**Comment by sftim** [comment]
BTW, for extra credit: support [hop-by-hop compression](https://developer.mozilla.org/en-US/docs/Web/HTTP/Compression#hop-by-hop_compression) too.

Of course, `kubectl` doesn't yet support hop-by-hop compression, but some generic tools (eg `curl`) do.

Clients can combine what they negotiate, too: for example, preferring `application/vnd.kubernetes.protobuf` data and also advertising that they support either identity or `br` hop-by-hop transfer encoding.

You don't have to restrict compression to JSON response bodies (per the issue title)

&hellip;or even to responses. The API server can allow clients to hop-by-hop compress a request body, too (using the `Expect: 100-continue` mechanism).

Because clients that hop-by-hop compression typically implement it properly, and only for HTTP/1.1 requests, adding hop-by-hop compression support is low impact / low risk. We could implement that first to get feedback on the implementation and then later migrate to end-to-end compression (which clients and proxies often do get wrong).

PS. https://datatracker.ietf.org/doc/html/rfc7540 forbids HTTP/2 clients from requesting hop-by-hop response body compression, and it looks like HTTP/3 will forbid it too. I'm not suggesting that hop-by-hop compression for those protocols is likely; that's a different and bigger question.

**Comment by smarterclayton** [comment]
Interestingly the original issue should be fixed, accept encoding is what we key compression off of.  Possible to close?

**Comment by smarterclayton** [comment]
As per https://github.com/kubernetes/kubernetes/pull/77449 this has been in Kube for a while.  Please reopen if the original request was different.  Re: hop by hop that should be a separate issue.
