### ISSUE TITLE
"superfluous response.WriteHeader call" when using "kubectl logs -f"

### ISSUE THREAD

**Issue by champtar** [kubernetes/kubernetes#110409]
### What happened?

When running `kubectl logs -f`, I get the following log
```
http: superfluous response.WriteHeader call from k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*Response).WriteHeader (response.go:220)
```

### What did you expect to happen?

No error/warning

### How can we reproduce it (as minimally and precisely as possible)?

```
kubectl run --image=k8s.gcr.io/pause:3.6 test
timeout 2s kubectl logs -f test
```

### Anything else we need to know?

Same error message with or without logs to print

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.7", GitCommit:"42c05a547468804b2053ecf60a3bd15560362fc2", GitTreeState:"clean", BuildDate:"2022-05-24T12:30:55Z", GoVersion:"go1.17.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.7", GitCommit:"42c05a547468804b2053ecf60a3bd15560362fc2", GitTreeState:"clean", BuildDate:"2022-05-24T12:24:41Z", GoVersion:"go1.17.10", Compiler:"gc", Platform:"linux/amd64"}
```

(Also happens in 1.23.3)
</details>

### Cloud provider

<details>
Bare metal
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
Modified Alma 8.6
$ uname -a
# paste output here
Linux <REDACTED> 4.18.0-372.9.1.el8.x86_64 #1 SMP Tue May 10 08:57:35 EDT 2022 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Install tools

<details>
kubeadm
</details>

### Container runtime (CRI) and version (if applicable)

<details>
NA
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
NA
</details>

**Comment by pacoxu** [comment]
/sig node 
since the log is on the kubelet side. (I prefer to think this is expected behavior when canceling to get logs from kubelet.)

> 6月 08 15:42:20 daocloud kubelet[1755576]: I0608 15:42:20.465121 1755576 log.go:184] http: superfluous response.WriteHeader call from k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog.(*respLogger).WriteHeader (httplog.go:297)
> 6月 08 15:42:20 daocloud kubelet[1755576]: I0608 15:42:20.465229 1755576 httplog.go:129] "HTTP" verb="GET" URI="/containerLogs/default/test/test?follow=true" latency="1.923068429s" userAgent="Go-http-client/1.1" audit-ID="" srcIP="10.6.177.41:49672" resp=400

**Comment by tstapler** [comment]
The code for getting container logs can be found here: https://github.com/kubernetes/kubernetes/blob/7858fc93e5c61ad87e6e2fafa5df33806b38bf28/pkg/kubelet/server/server.go#L610

Based on the `resp=400` it seems like the path being hit is here
https://github.com/kubernetes/kubernetes/blob/7858fc93e5c61ad87e6e2fafa5df33806b38bf28/pkg/kubelet/server/server.go#L672
```
	fw := flushwriter.Wrap(response.ResponseWriter)
	response.Header().Set("Transfer-Encoding", "chunked")
	if err := s.host.GetKubeletContainerLogs(ctx, kubecontainer.GetPodFullName(pod), containerName, logOptions, fw, fw); err != nil {
		response.WriteError(http.StatusBadRequest, err)
		return
	}
```

In the `GetKubleletContainerLogs` function the logs are written by calling `fw.Write(...)`.
https://github.com/kubernetes/kubernetes/blob/HEAD/pkg/kubelet/kubelet_pods.go#L1320

Based the docs for WriteHeader have this comment
```
	// WriteHeader sends an HTTP response header with the provided
	// status code.
	//
	// If WriteHeader is not called explicitly, the first call to Write
	// will trigger an implicit WriteHeader(http.StatusOK).
	// Thus explicit calls to WriteHeader are mainly used to
	// send error codes.
```

It seems that we will see the `http: superfluous response.WriteHeader call` error after we call `fw.Write`/

@champtar, are there more kubelet logs surrounding the the two you shared?

It's unclear to me why `resp=400`. Is it because your `kubectl logs -f` command closed the connection to the api-server so the api server closed the connection to kubelet? Is it due to an error writing the response body in `GetKubeletContainerLogs` once the client connection from the api-server is closed?

I'd have to do more digging to trace the code path through the API server, and how restful handles connections which have been closed.

**Comment by SergeyKanzhelev** [comment]
it looks like this is by design, the only side effect seems to be a warning message in logs. Please re-open if this causes issues.

/close
