### ISSUE TITLE
Kubectl cp fails with "Error: archive/tar: invalid tar header" even with retries on 

### ISSUE THREAD

**Issue by nhumrich** [kubernetes/kubernetes#110613]
### What happened?

Running `kubectl cp` occasionally fails with the error:
`error: archive/tar: invalid tar header` with exit code 1. 

The docs say you can retry when an error occurs using --retry. The retry works, but it's not retrying the full amount of times. 

### What did you expect to happen?

I expected the cli to retry when it has connection issues.

### How can we reproduce it (as minimally and precisely as possible)?

try to copy a large directory from a remote k8s cluster. For me, it seems to start after 20MB, but gets really bad past 100MB.

Here is what I ran:
```
kubectl cp mypod:/app/content/cache /tmp/cache --retries 8
```

with the following output:
```
tar: Removing leading `/' from member names
Resuming copy at 43081728 bytes, retry 1/8
tar: Removing leading `/' from member names
error: archive/tar: invalid tar header
```

and when I try it again a couple times, it sometimes works, and sometimes fails. The `--retry` flag is required, however, as without it I always get a `Error: unexpected EOF`

### Kubernetes version

<details>

```console
$ kubectl version -o yaml
clientVersion:
  buildDate: "2022-05-04T15:25:22Z"
  compiler: gc
  gitCommit: 4ce5a8954017644c5420bae81d72b09b735c21f0
  gitTreeState: archive
  gitVersion: v1.24.0
  goVersion: go1.18.1
  major: "1"
  minor: "24"
  platform: linux/amd64
kustomizeVersion: v4.5.4
serverVersion:
  buildDate: "2022-05-12T18:44:04Z"
  compiler: gc
  gitCommit: 03450cdabfc4162d4e447e6d8c5037efe6d29742
  gitTreeState: clean
  gitVersion: v1.20.15-eks-a64ea69
  goVersion: go1.15.15
  major: "1"
  minor: 20+
  platform: linux/amd64
```

</details>

### Cloud provider

<details>
aws EKS
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Manjaro Linux"
ID=manjaro
ID_LIKE=arch
BUILD_ID=rolling
PRETTY_NAME="Manjaro Linux"
ANSI_COLOR="32;1;24;144;200"
HOME_URL="https://manjaro.org/"
DOCUMENTATION_URL="https://wiki.manjaro.org/"
SUPPORT_URL="https://manjaro.org/"
BUG_REPORT_URL="https://bugs.manjaro.org/"
LOGO=manjarolinux
$ uname -a
Linux humdingr-dell 5.15.41-1-MANJARO #1 SMP PREEMPT Wed May 18 09:20:01 UTC 2022 x86_64 GNU/Linux
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by nhumrich** [comment]
Update: This still happens even when running `kubectl cp` from another pod within the same cluster.

**Comment by nhumrich** [comment]
On further analysis, I think what is happening is the folder I am copying is being written to while the command runs. The reason why size matters for me is it just increases the likelihood the race-condition happens. 

So I think this is what is happening:
I run `kubectl cp` on folder `/app/content/cache`. Then _while that is running_ the pod writes to a file in `/app/content/cache` changing is contents, or even adding a file. This probably causes some issues to how the tar command is being ran.

**Comment by sftim** [comment]
/kind support

I think `kubectl cp` is working as specified.

**Comment by brianpursley** [comment]
The problem seems to be here:
https://github.com/kubernetes/kubernetes/blob/8fb423bfabe0d53934cc94c154c7da2dc3ce1332/staging/src/k8s.io/kubectl/pkg/cmd/cp/cp.go#L381

When it retries, it re-executes the tar command, but this time using `| tail` so that it doesn't need to re-send all the bytes that were already sent.

This is fine, if the file hasn't changed, but as @nhumrich discovered, if the file is changing, then the resulting tar file becomes "corrupted" because the first part that was sent was for one tar file, and the second part, after the retry, was for an entirely different tar file, but the cp command just puts all the bytes together and tries to untar them.

I don't know if there is some way to detect this error and show a message saying "file was changed after retry occurred" or something like that to make it more clear what the problem is.

One workaround I guess is for the user to make a copy of the file to a temp directory, so that it isn't changing while `kubectl cp` is running.

**Comment by colegatron** [comment]
Just to add my two cents;

Same issue happening since some days ago:
When I try to copy content with kubectl cp, even using --retry it fails to copy anything if the tar generated is big enough.
Not sure how much should be 'big' to stop working, but copying small files one by one does it work.
always worked until last k8s upgrade (1.18 to 1.19)

**single small file**
$ kubectl cp -n ci $NODE_CONTAINER:/usr/local/openresty/nginx/html/safety-worker.js /tmp/file.js
works

**total folder size=118M;  folder tar'ed zcvf 37M**
$ kubectl -n ci cp $NODE_CONTAINER:/usr/local/openresty/nginx/html /tmp/cached_files
tar: Removing leading `/' from member names
Dropping out copy after 0 retries
error: unexpected EOF

$ kubectl exec -ti -n ci $NODE_CONTAINER tar zcvf /tmp/cache.tgz /usr/local/openresty/nginx/html
**works, then cp**
$ kubectl cp -n ci $NODE_CONTAINER:/tmp/cache.tgz /tmp/cache.tgz
tar: Removing leading `/' from member names
Dropping out copy after 0 retries
error: unexpected EOF

**then with retries:**

$ kubectl cp --retries=-1  -n ci $NODE_CONTAINER:/tmp/cache.tgz /tmp/cache.tgz
tar: Removing leading `/' from member names
Resuming copy at 32366592 bytes, retry 0/-1
tar: Removing leading `/' from member names
error: archive/tar: invalid tar header

**Then again:**
$ kubectl cp --retries=-1  -n ci $NODE_CONTAINER:/tmp/cache.tgz /tmp/cache.tgz
tar: Removing leading `/' from member names
worked 1 time, tried a 2nd time and failed.

**Wondering if it is not k8s:**
I have multiple vpn clients running simultaneously, so I closed all connections
tried again but not working

Then I changed the wifi network to my cellphone hotspot:
The tgz copy worked bunch of times and tried to run the cp of the folder (letting kubectl cp run the tar itself) and it also worked (very slow, though)

**Conclusion:**
For me it seems related to the quality of the network, but since any other application and process works properly with my network connections, it might be some uncovered problem.

**Comment by FredMandry** [comment]
Hi @nhumrich , I'm facing same problem than you using Kubernetes, did you have a way to workaround it?
Best Regards :)
