### ISSUE TITLE
Computation of the StorageVersionHash is incorrect for overridden storage versions in unit test

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#110750]
Storage version defaults to the preferred version for a given group, but can be overridden when constructing API server storage.

This is done here: https://github.com/kubernetes/kubernetes/blob/035f22d7810a8970e42d60f276f71a519b174a44/pkg/kubeapiserver/default_storage_factory_builder.go#L60-L67

Reasons the preferred version might be overridden:
* A given resource/kind does not yet exist in the preferred version (like when introducing a new alpha type in an existing API group with more stable versions)
* A given resource/kind is continuing to store in etcd in an older version for compatibility with n-1 API servers

The etcd integration test verifies that we're actually storing the correct versions in etcd, but the computation of the StorageVersionHash is not honoring the overridden version.

on master, this code reports v1 CSIStorageCapacity:

https://github.com/kubernetes/kubernetes/blob/035f22d7810a8970e42d60f276f71a519b174a44/staging/src/k8s.io/apiserver/pkg/endpoints/installer.go#L398-L408

even though the etcd test verifies we're still persisting v1beta1

/kind bug
/priority important-soon
/sig api-machinery

cc @pohly

_Originally posted by @liggitt in https://github.com/kubernetes/kubernetes/issues/109394#issuecomment-1164608879_

**Comment by liggitt** [comment]
cc @deads2k

**Comment by harry1064** [comment]
hi @liggitt  @pohly 

I have found that on `Version` points to `v1beta1`
https://github.com/kubernetes/kubernetes/blob/035f22d7810a8970e42d60f276f71a519b174a44/staging/src/k8s.io/apiserver/pkg/endpoints/installer.go#L203

but here the `versioner` points to `v1`
https://github.com/kubernetes/kubernetes/blob/035f22d7810a8970e42d60f276f71a519b174a44/staging/src/k8s.io/apiserver/pkg/endpoints/installer.go#L402-L403

here is screenshot from debug console
![Screenshot 2022-06-27 at 12 22 49 AM](https://user-images.githubusercontent.com/6297435/175823898-4f62cc0b-e2a4-4644-a5c7-3fb16f2be907.png)

As I am still new to the codebase, I am trying to understand why it is happening so.
But we can say that because of this reason, test case below does not failed because the expected hash we put in data.go file matches correctly with the onc we create in `staging/src/k8s.io/apiserver/pkg/endpoints/installer.go` at line 404
https://github.com/kubernetes/kubernetes/blob/035f22d7810a8970e42d60f276f71a519b174a44/pkg/controlplane/instance_test.go#L389

I also believe that the value corresponding to key `storage.k8s.io/v1beta1/csistoragecapacities` has been wrongly put same as `storage.k8s.io/v1/csistoragecapacities`

Correct values are as follows. One caveat here is, hashes are calculated with appending resource `Kind` but the key for lookup is based on resource `Name`.
```
"storage.k8s.io/v1/CSIStorageCapacity" ->  "xeVl+2Ly1kE="
"storage.k8s.io/v1beta1/CSIStorageCapacity" -> "4as6MA/kOg0="
```

I hope this information will help in locating the issue. Meanwhile, I will also try to look why `storageVersionProvider` in `installer.go` is pointing to `v1` even though we override.

**Comment by 249043822** [comment]
The problem reported by this issue should not exist, on apiserver startup, we can get the right overrided version v1beta1 for the csistoragecapacities from ` storageVersionProvider.StorageVersion() `, since the code below overrided the storage version
https://github.com/kubernetes/kubernetes/blob/035f22d7810a8970e42d60f276f71a519b174a44/pkg/kubeapiserver/default_storage_factory_builder.go#L60-L67
![log](https://user-images.githubusercontent.com/18046309/176096136-16c57ea4-ab3e-463c-ba2e-2431cb5aee54.png)

But in the test `TestStorageVersionHashes`, it did not override the storage version, see the code below
https://github.com/kubernetes/kubernetes/blob/035f22d7810a8970e42d60f276f71a519b174a44/pkg/controlplane/instance_test.go#L94-L98

so this test case reports v1 CSIStorageCapacity is right.

@liggitt do you think that we should change the testcase to override the storage version again to keep consistent and dispel the confusion for StorageVersionHash ?

**Comment by liggitt** [comment]
ah, good catch... so this is a test-only issue, but still one we need to resolve, so the unit test reflects reality of storage versions when you actually start a kube-apiserver

**Comment by 249043822** [comment]
@liggitt As this pr https://github.com/kubernetes/kubernetes/pull/109394 would remove the storageversion override， so after this pr merged, the testcase would be just right, then we don't need another pr to fix the testcase again, right?

**Comment by liggitt** [comment]
> @liggitt As this pr #109394 would remove the storageversion override， so after this pr merged, the testcase would be just right, then we don't need another pr to fix the testcase again, right?

the test would still be exercising preferred version ordering without any overrides, which would still be incorrect, and would resurface problems as soon as another override is added
