### ISSUE TITLE
Node's EXTERNAL-IP is none

### ISSUE THREAD

**Issue by xiaofengzs** [kubernetes/kubernetes#110884]
Hi, all
I setup a single node k8s on the Ubuntu 20.04.4 LTS. It's on the Tencent cloud machine. I found the external ip of the only one node is node. When i test the NodePort service, the external ip will be used. But it's none. So i can not access NodePort service.
How to assign a external ip to the node?

> NAME              STATUS   ROLES                  AGE   VERSION    INTERNAL-IP   EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION      CONTAINER-RUNTIME
vm-24-11-ubuntu   Ready    control-plane,master   45h   v1.22.10   10.0.24.11    <none>        Ubuntu 20.04.4 LTS   5.4.0-109-generic   docker://20.10.17

> Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.10", GitCommit:"eae22ba6238096f5dec1ceb62766e97783f0ba2f", GitTreeState:"clean", BuildDate:"2022-05-24T12:56:35Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.10", GitCommit:"eae22ba6238096f5dec1ceb62766e97783f0ba2f", GitTreeState:"clean", BuildDate:"2022-05-24T12:50:52Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}

**Comment by harry1064** [comment]
Hi @xiaofengzs 
According to the documentation,https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types
you can access your service on <NodeIP>:<NodePort>
<NodeIP> would be your IP of tencent cloud machine, but in this case you need to open <NodePort> on you cloud machine or use your cloud provider load balancer to route traffic to your <NodePort>

Otherwise, you can follow the documentation here:
https://kubernetes.io/docs/concepts/services-networking/service/#external-ips

**Comment by xiaofengzs** [comment]
Hi @harry1064, thanks. i got it and expose the external ip.

**Comment by dennisvang** [comment]
related: 
- #92999
