### ISSUE TITLE
The logic of oom_score_adj doesn't work well for sidecar containers

### ISSUE THREAD

**Issue by jpinkul** [kubernetes/kubernetes#111356]
### What happened?

I was debugging a OOM failure recently and noticed some unexpected behavior for how the kubelet is setting `oom_score_adj`.

From the [Node-pressure Eviction documentation](https://kubernetes.io/docs/concepts/scheduling-eviction/node-pressure-eviction/) this is how setting `oom_score_adj` is described for burstable QoS pods:

> min(max(2, 1000 - (1000 * memoryRequestBytes) / machineMemoryCapacityBytes), 999)

The documentation also states the intention of this calculation is:

> This means that containers in low QoS pods that consume a large amount of memory relative to their scheduling requests are killed first.

However the calculation actually does the opposite. For processes that request a small amount of memory the `(1000 * memoryRequestBytes) / machineMemoryCapacityBytes` ratio approaches zero, meaning the calculation ends up being: `min(max(2, 1000 - 0), 999) = 999`

Similarly, when the requested memory increases and the ratio approaches the total size of the machine the calculation becomes: `min(max(2, 1000 - 1000), 999) = 2`

This means that containers that are using the smallest amount of the machine get the highest score adjustment which makes the smallest processes killed first. I observed this in practice while looking at the kernel's OOM logs. These are the set of processes the OOM killer was logging:

```
kernel: Tasks state (memory values in pages):
kernel: [  pid  ]   uid  tgid total_vm      rss pgtables_bytes swapents oom_score_adj name
kernel: [  10325]     0 10325      242        1    28672        0          -998 pause
kernel: [  11029]     0 11029   185553     4518   212992        0          -997 node-cache
kernel: [  10189]     0 10189      242        1    28672        0          -998 pause
kernel: [  11651]     0 11651     2890      117    65536        0          -997 bash
kernel: [  11692]     0 11692   191867    11673   303104        0          -997 aws-k8s-agent
kernel: [  11693]     0 11693     1060       16    57344        0          -997 tee
kernel: [   9998]     0  9998      242        1    28672        0          -998 pause
kernel: [  10857]     0 10857   188700     7795   249856        0          -998 kube-proxy
kernel: [  10115]     0 10115      242        1    24576        0          -998 pause
kernel: [  11256]  1000 11256   186562     2695   192512        0          -997 node-terminatio
kernel: [  14406]     0 14406      242        1    28672        0          -998 pause
kernel: [  16187]   100 16187   213158    20546   421888        0          -997 vault
kernel: [  14897]     0 14897      242        1    24576        0          -998 pause
kernel: [  14393]     0 14393      242        1    28672        0          -998 pause
kernel: [  15195]     0 15195  4690740  4301599 36208640        0          -997 logger
kernel: [  15717]     0 15717      242        1    28672        0          -998 pause
kernel: [  16487]     0 16487   187806     6452   217088        0          -997 herdmonitor
kernel: [   1474] 65534  1474      242        1    28672        0          -998 pause
kernel: [   5070] 65534  5070   180050     2762   135168        0           999 node_exporter
kernel: [  25878]     0 25878      242        1    28672        0          -998 pause
kernel: [  27296]     0 27296   184151     3800   192512        0           121 taskhost
kernel: [  27532]     0 27532   187011    11328   217088        0           121 run_sim_stack
kernel: [  27533]     0 27533   187011    11552   217088        0           121 run_sim_stack
kernel: [  27541]     0 27541   187139    11272   212992        0           121 run_sim_stack
kernel: [  27544]     0 27544   186819    11890   221184        0           121 run_sim_stack
kernel: [  27549]     0 27549   187011    11692   212992        0           121 run_sim_stack
kernel: [  27555]     0 27555   187011    11270   221184        0           121 run_sim_stack
kernel: [  27560]     0 27560   187011    11286   208896        0           121 run_sim_stack
kernel: [  27676]     0 27676   213898    10619   708608        0           121 stack_run
kernel: [  27681]     0 27681   283022    12289   815104        0           121 stack_run
kernel: [  27684]     0 27684   306570    11785  1413120        0           121 stack_run
kernel: [  27775]     0 27775   213898    10586   708608        0           121 stack_run
kernel: [  27838]     0 27838   217994    10748   704512        0           121 stack_run
kernel: [  27899]     0 27899   213898    10676   696320        0           121 stack_run
kernel: [  27963]     0 27963   207241    10588   696320        0           121 stack_run
kernel: [  28211]     0 28211  4636176  3709004 32600064        0           121 offline_main_pl
kernel: [  28212]     0 28212  4649424  3709621 32579584        0           121 offline_main_pl
kernel: [  28213]     0 28213  4635152  3701721 32612352        0           121 offline_main_pl
kernel: [  28214]     0 28214  4606542  3697740 32481280        0           121 offline_main_pl
kernel: [  28215]     0 28215  4638672  3713963 32645120        0           121 offline_main_pl
kernel: [  28216]     0 28216  4627408  3697821 32559104        0           121 offline_main_pl
kernel: [  28217]     0 28217  4632271  3716409 32641024        0           121 offline_main_pl
kernel: [  27390]     0 27390   183959     2534   176128        0           999 taskhost
kernel: [  27447]     0 27447   212069    20873   413696        0           999 vault
```

Due to the `999` value of `oom_score_adj` processes in the `vault` container were killed first, despite having the smallest resource request and the smallest memory footprint.

### What did you expect to happen?

I expected that containers that are using a larger portion of the machine to have `oom_score_adj` set to a higher value than containers that are using a small portion of the machine. This matches the intentions stated in the existing documentation. Changing the calculation to this should have that intended effect:

```
min(max(2, 1000 * memoryRequestBytes / machineMemoryCapacityBytes), 999)
```

With that change as the ratio of requested memory approaches the entire machine the value will approach 999, which will make the OOM killer most likely to target those processes.

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a burstable QoS pod that requests and uses a small amount of memory.
2. Create a burstable pod that requests a large amount of memory and has a memory leak that will eventually trigger the OOM killer.
3. Look at the OOM killer kernel logs and see that the small pod was targeted first.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.9", GitCommit:"b631974d68ac5045e076c86a5c66fba6f128dc72", GitTreeState:"clean", BuildDate:"2022-01-19T17:51:12Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.12-eks-a64ea69", GitCommit:"d4336843ba36120e9ed1491fddff5f2fec33eb77", GitTreeState:"clean", BuildDate:"2022-05-12T18:29:27Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
AWS
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
$ uname -a
Linux ip-10-35-95-93.swe.cloud.aurora.tech 5.4.190-107.353.amzn2.x86_64 #1 SMP Wed Apr 27 21:16:35 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>
kernel: 5.4.190-107.353.amzn2
dockerd: 20.10.13-2.amzn2
containerd: 1.4.13-2.amzn2.0.1
runc: 1.0.3-2.amzn2
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by kolyshkin** [comment]
@jpinkul I think you're misinterpreting this.

The calculations you cited are done by kubernetes, and they take into account two values:
 * `memoryRequestBytes` -- this is how much memory a container _requests_ (note this is NOT the current usage and NOT the memory limit, but rather a minimally required memory for a container -- although, if unset, this defaults to limit)
 * `machineMemoryCapacityBytes` -- this is basically how much memory the server has
 
Based on these two values, OOM score _adjustment_ is calculated and set.
 
Now, when OOM killer is invoked, it uses a _container_'s memory limit as well as a _process's_ (not container's) current memory usage to calculate OOM _score_ (not the _score adjustment_). Processes that are over the container's cgroup limit will have the score of 1000. Than the adjustment is applied.

Note that some containers may run a single process, while some others may run multiple small processes, and they are treated by the OOM killer separately (unless for cgroup v2, when `memory.oom.group == 1`, which apparently is never the case with k8s since by default `memory.oom.group = 0`, and also most people still use cgroup v1).

The code in question was written in 2015 and is reviewed in #12182. The idea behind the adjustment is described here:

https://github.com/kubernetes/kubernetes/blob/d6a3a68afce1525dc31a2a8e73a2bc5903120eb9/pkg/kubelet/qos/policy.go#L54-L61

As a result, this code gives the following OOM score _adjustments_:
 * 3 to processes inside a container which _requests_ 100% of memory
 * 500 to processes inside a container which _requests_ 50% of memory
 * 900 to processes inside a container which _requests_ 10% of memory
 
Again, the OOM score is determined on a per-process basis, using the process (not the container) memory usage and the container memory limit (not the requested memory!). For example, if we have three big processes each using 10% of memory running in different containers, the one in a container with smaller memory _limit_ will have higher OOM score (before the adjustment). The end result (after the adjustment) depends on the memory _requested_ (not limited).

Now I can't say if this algorithm is good or bad, because there are too much variables involved. What I can say is your initial analysis appears to be incorrect.

**Comment by kolyshkin** [comment]
@derekwaynecarr PTAL ^^^

**Comment by jpinkul** [comment]
Thanks for the additional context! I didn't realize how this score adjustment was intended to interact with the base OOM score.

To summarize the final OOM score consists of two components, the base OOM score which is from the actual usage of the process and the adjustment which is based off of the requested container resources. Containers that request a higher portion of a machine derive more of the final score from the usage of the process. Conversely containers that request a smaller portion of the machine derive more of the final score from the container requested memory.

This explains why I observed an OOM kill of a process that was using less memory than the container's memory request and was running in a container that had requested a small amount of memory. In this case since the ratio of the container's `memoryRequestBytes` to `machineMemoryCapacityBytes` was so small the OOM adjustment was set to the max of 999. This means that containers that request a very small portion of the machine will be targeted by the OOM killer regardless of the memory usage of their processes.

This behavior still seems undesirable since targeting these small containers causes failures without freeing a significant amount of memory. Is there a workaround to prevent these small `memoryRequestBytes` containers from being targeted? For single container pods we could use a `Guaranteed` QoS but that wouldn't work for pods that have small side cars, such as the vault injector.

**Comment by SergeyKanzhelev** [comment]
/remove-kind bug
/kind feature

I think oomkilling "small" bursteable pods is a good logic in general. Those are easier to reschedule and likely will cause less interruption. They are almost best effort in oom adjustment calculations.

As for the sidecars - it is a valid point that killing small sidecars of a large pod may be more disruptive and less efficient than smaller pod or smaller pod's sidecar. In other words, maybe formulae needs to account the entire pod request. Since there is no way to tell if the container is a sidecar container, maybe some heuristic may be applied. Perhaps, use the entire pod's OOM score adjustment for the containers when those containers are requesting a fraction of memory of the entire pod's request.

I was thinking of also using `restartPolicy` to determine the right calculation, but I don't think it will be easy to tell whether a containers inside the pod are more or less OK to be OOM killed based on this policy.

/retitle The logic of oom_score_adj doesn't work well for sidecar containers

@kolyshkin, @derekwaynecarr  wdyt?

**Comment by SergeyKanzhelev** [comment]
This was brought up at SIG Node meeting Sep 27, 2022. You can find notes here: https://docs.google.com/document/d/1Ne57gvidMEWXR70OxxnRkYquAoMpt56o75oZtg-OeBg/edit#heading=h.2lyv2y38jwkc

The suggestion was to postpone solving this problem to cgroupv2 and OOMd design.

I will close this feature request for now. Also the proposal of per container restart policy may help to mitigete the future if it will be adopted:  https://docs.google.com/document/d/1gX_SOZXCNMcIe9d8CkekiT0GU9htH_my8OB7HSm3fM8/edit 

/close

**Comment by sidewinder12s** [comment]
@SergeyKanzhelev Just wondering, is there a ticket or KEP you'd recommend to follow for how the Kubernetes community is looking at cgroupv2/oomd/pod v2 as referenced in the meeting notes?

**Comment by SergeyKanzhelev** [comment]
/reopen 
/triage accepted

Need to work on it as part of https://github.com/kubernetes/enhancements/issues/753

**Comment by bouaouda-achraf** [comment]
Anyone

**Comment by SergeyKanzhelev** [comment]
> Is anyone working on this ? I can ✋ ( before /.assign )

Go for it! This is a very scoped contribution.
