### ISSUE TITLE
proposal: introduce recovery mode for pod preemption

### ISSUE THREAD

**Issue by chendave** [kubernetes/kubernetes#111390]
### What would you like to be added?

Introduce recovery mode for pod preemption, with this mode enabled which maybe guarded by a feature gate, the pod deleted by the pod preemption will be re-created automatically when the workload is down for some reason, or the resource is expanded.

### Why is this needed?

For the pod which is not managed by a controller, such as `daemonset`, or `replicaset`, the pods which are marked as the victim pods and removed due to the pod preemption, won't be created unless this is done manually.

But in a cluster which has hundred or even thousand of pod, which Pods are removed are not easy to identified (this info could be found in the log, but I believe not all the end user has the knowledge to identify the victims).

Besides, this will cause the service provided by the pods down for a long time, potentially, this may cause some loses for our end-user.

The workload of a cluster is very dynamic, there is no need to wait for the admin to identify the victims and re-create them manually.

when the recovery mode is enabled, scheduler will push the pod into scheduler's Queue, and help to spawn up the Pod the first time when the cluster has the enough resource.

cc @Huang-Wei @alculquicondor @ahg-g @damemi  for thoughts.

/sig scheduling

**Comment by chendave** [comment]
/assign

I need to do more investigation on this, particularly, how to move the pods to the scheduler's Q.

**Comment by alculquicondor** [comment]
This is beyond sig-scheduling to decide.

You would need a KEP with sig-architecture as the owning-sig. But I doubt they would accept it. It's also a breaking change.

**Comment by chendave** [comment]
@alculquicondor I am not sure I understand it correctly. 

Both the logic of pod preemption and the scheduling Queue are maintained by scheduler, shouldn't this a scope of pod scheduling? 

Just one thing that is need to be ruled out is a path from the pod deletion to the  pod en-queue, maybe we can create a new API for that. 


>It's also a breaking change.

+1, agree that a KEP is needed.


I do think this is useful, especially, in a large cluster where pod preemption are expected.

**Comment by damemi** [comment]
The scheduler doesn't handle re-creation of pods, and preemption is the one
case where the scheduler even cares about existing pods (and that is only
because it's concerned with a new incoming pod). Re-queueing is not the
same as re-creation, so it's that pod creation step that stands out to me.

So I agree with Aldo that this probably isn't the scheduler's concern.
There are other controllers that are meant for maintaining pod
availability. And pods that are deleted without an owning controller aren't
meant to be automatically recreated.

From the scheduler's perspective, part of this issue could be to surface
more information about preemption when it does occur. Maybe the option to
persist preemption logs would be helpful? Or something like that

**Comment by alculquicondor** [comment]
> Both the logic of pod preemption and the scheduling Queue are maintained by scheduler, shouldn't this a scope of pod scheduling?

Yes, but this is an architectural change. Pods are immutable in kubernetes, regardless of which component is doing the operations.

I'm not even sure if the apiserver would allow you to reset the node name.

Why not put a controller in front of these pods that need to be restarted?

**Comment by ahg-g** [comment]
Mike and Aldo already discuss some issues with the proposal, but here is a quick take since you tagged me: 

The scheduler doesn't own the pods, and so it shouldn't create them. The common pattern is that pods are managed by a single workload controller to reduce the chances of race conditions and enforce separation of concern, especially pod creation and status updates. 

Also, it is not true that every preempted pod needs to be re-created, and so this proposal will spill into api changes to the pod (to decide when to recreate and when not) that I think are not needed if we simply stick with the pattern that pods are created only by the workload controller.

**Comment by chendave** [comment]
> Why not put a controller in front of these pods that need to be restarted?

I think it's a recommendation, but not all pod are required to be managed by a controller.


Let's put this to hold, inspired a lot from your feedback though, thanks!

**Comment by alculquicondor** [comment]
I suggest you bring this question to sig-architecture

**Comment by chendave** [comment]
> I suggest you bring this question to sig-architecture

When I have a concrete plan, I will.

**Comment by chendave** [comment]
/close

duplicate with https://github.com/kubernetes/kubernetes/issues/112273
