### ISSUE TITLE
pull-kubernetes-verify-govet-levee fails everything now

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/kubernetes#111452]
### Which jobs are failing?

pull-kubernetes-verify-govet-levee

### Which tests are failing?

verify: govet-levee

### Since when has it been failing?

Failing everything from 7:35 PM EDT July 26.
Failing almost everything from 5:29 PM EDT July 26.

### Testgrid link

https://k8s-testgrid.appspot.com/presubmits-kubernetes-blocking#pull-kubernetes-verify-govet-levee

### Relevant SIG(s)

/sig testing

**Comment by MikeSpreitzer** [comment]
There is a  Slack message in #sig-testing associating this with #111449.  Maybe from @heyste ?

**Comment by nikhita** [comment]
Looks like it's due to https://github.com/golang/go/issues/48525. `golang/x/tools` doesn’t seem to support type parameters yet.

**Comment by nikhita** [comment]
Why the tests didn't fail in https://github.com/kubernetes/kubernetes/pull/111254:

- The PR (https://github.com/kubernetes/test-infra/pull/26921) to bump the kubekins image for the test merged before #111254 did, but the config bumps didn't happen until after the tests for #111254 were triggered.
- Due to this, the prowjob for the govet-levee job on #111254 uses the old kubekins image - https://prow.k8s.io/prowjob?prowjob=a666dbdc-0d1f-11ed-9d9c-da706f6fcf9d and the test didn't fail.

**Comment by MadhavJivrajani** [comment]
For future - @palnabarun, can we document this, where we need to wait for the image bump to propagate to the CI so that changes such as https://github.com/kubernetes/kubernetes/pull/111254 can test on that?

xref: https://github.com/kubernetes/sig-release/issues/1972

**Comment by MadhavJivrajani** [comment]
Also, looks like adding support for type parameters in `golang/x/tools` is bumped to go1.20 release: https://github.com/golang/go/issues/48525#issuecomment-1190816141

**Comment by MadhavJivrajani** [comment]
Not sure what happened in go1.19 that is causing the panic, the go issue linked by @nikhita effects go1.18 as well

**Comment by nikhita** [comment]
go 1.19 is the first release to use generics in the standard library though - https://pkg.go.dev/sync/atomic@go1.19beta1#Pointer 🤔

**Comment by nikhita** [comment]
Let's open an issue in the go repo? If this is due to generics in the std lib, I'd expect the go team to prioritize fixing it.

**Comment by MadhavJivrajani** [comment]
I can create one, worst case we'll understand a little more about Go!

**Comment by MadhavJivrajani** [comment]
cc @dims @liggitt

**Comment by MadhavJivrajani** [comment]
Created: https://github.com/golang/go/issues/54086

**Comment by MadhavJivrajani** [comment]
Trying to think of how to unblock the CI for now:

So far:
- It does seem like the panics are occurring due to generics being present in the Go stdlib:
  - Generic code added as part of the 1.19 release: https://cs.opensource.google/go/go/+/master:src/crypto/elliptic/nistec.go;drc=faf4e97200df9415d55b04924ce77599f9e6fdfa;l=175
  - This isn't present in 1.18
- I don't see an immediate work around as per the discussion on the tracking issue to support generics in `x/tools/go/ssa`: https://github.com/golang/go/issues/48525

---

I can think of 2 ways to unblock the CI for now:
- disable the the `govet-levee` check 
OR
- revert the go1.19rc2 switch over.

re: disabling the `govet-levee` check: we can disable it for now and:
- Best case: things are resolved by 1.19 and we re-enable it.
- Worst case: we revert to 1.18.4 and re-enable the check. 

---

Also, as per https://github.com/golang/go/issues/48525, further work on this is moved to the go1.20 release, unless this is prioritised upstream and we are able to fix it in upstream Go as part of 1.19, waiting for 1.19 GA also wouldn't help I guess.

**Comment by nikhita** [comment]
> revert the go1.19rc2 switch over for the govet-levee job

This might be easier/better than disabling the govet-levee check completely.

**Comment by nikhita** [comment]
Created https://github.com/kubernetes/test-infra/pull/26931 and https://github.com/kubernetes/test-infra/pull/26932 to move the test back to go1.18 to unblock master for now (in case we want to go with option 2 above).

**Comment by nikhita** [comment]
Kicked off the job at https://github.com/kubernetes/kubernetes/pull/111449#issuecomment-1196547335 after https://github.com/kubernetes/test-infra/pull/26931 merged, the job is now green - https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/111449/pull-kubernetes-verify-govet-levee/1552238594398097408

**Comment by dims** [comment]
NOTE: this is in a tool we use `leevee`. `x/tools/go/ssa` is NOT used by k8s itself. So yes +1 to use older image for this for now. and keep going forward.

**Comment by BenTheElder** [comment]
using an older go version here means a skew in the go parser, it's probably fine in this instance, but as a general rule we probably want linters / analysis tools on the same go version.

How long do we expect to keep this out of sync? Do we have a path forward?

**Comment by dims** [comment]
@BenTheElder the forward path is folks responsible for `x/tools/go/ssa` to fix things on their end - https://github.com/golang/go/issues/48525

**Comment by BenTheElder** [comment]
I mean on our end it is only reasonable to “fix” by rolling back go for one job if we expect to be able to do so short term.

it looks like we can hope for a fix soon https://github.com/golang/go/issues/48525#issuecomment-1190816141

**Comment by timothy-king** [comment]
I left a description of a fix on https://github.com/golang/go/issues/54086#issuecomment-1204589970.

**Comment by MadhavJivrajani** [comment]
Thank you, @timothy-king! ♥️

**Comment by dims** [comment]
back on its feet now.
