### ISSUE TITLE
Reflector not able to log the correct type when using a dynamic informer

### ISSUE THREAD

**Issue by ncdc** [kubernetes/kubernetes#111604]
### What happened?

When using a dynamic informer, the underlying Reflector only logs about `*unstructured.Unstructured`. If you have multiple dynamic informers, for different `GroupVersionResource`s, it's not possible to determine which log message is for which resource.

### What did you expect to happen?

Reflector log messages should be able show the appropriate resource type for dynamic informers, instead of `*unstructured.Unstructured` for all of them

### How can we reproduce it (as minimally and precisely as possible)?

1. Create and start 1 or more dynamic informers
2. Look at the logs for `reflector.go` - they will mention `*unstructured.Unstructured` for all dynamic types

### Anything else we need to know?

The reflector does support logging the correct type if you fill in the `apiVersion` and `kind` in the example `&unstructured.Unstructured{}` object that is created.

Creation: https://github.com/kubernetes/kubernetes/blob/bddb4ec08ee76c98a04cc857d346fd80d44abd8f/staging/src/k8s.io/client-go/dynamic/dynamicinformer/informer.go#L138

Reflector support:

https://github.com/kubernetes/kubernetes/blob/bddb4ec08ee76c98a04cc857d346fd80d44abd8f/staging/src/k8s.io/client-go/tools/cache/reflector.go#L201-L210

Unfortunately, the dynamic informer does not set these fields, because it doesn't necessarily know them - it knows the group, version, and resource, but not kind.

One possible fix would be to set something like an annotation in the example `&unstructured.Unstructured{}` object created in `dynamicinformer/informer.go`, such as `gvr=widgets.example.io`. Then, in the reflector's code, it could at least set `r.expectedTypeName` to the annotation's value, e.g. `widgets.example.io`. This would allow the log messages to show the group-resource instead of `*unstructured.Unstructured`.

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by ncdc** [comment]
I'd be happy to create a PR that implements the annotation-based approach if that is acceptable to the SIG.

**Comment by fedebongio** [comment]
/cc @MikeSpreitzer @leilajal 

We discussed this one in the triage meeting, looks like people has opinions on the area. Maybe try to discuss here, and eventually bring it to the next SIG meeting?

**Comment by MikeSpreitzer** [comment]
Here is another log message that only mentions "unstructured":

```
I0811 06:33:18.222219       1 trace.go:205] Trace[1674010853]: "GuaranteedUpdate etcd3" type:*unstructured.Unstructured (11-Aug-2022 06:33:17.524) (total time: 698ms):
```

**Comment by MikeSpreitzer** [comment]
@ncdc: Let me see if I follow your suggestion for a fix.  The idea starts with modifying https://github.com/kubernetes/client-go/blob/a890e7bc14d5062a2a7eb96a5286239383d5cac8/dynamic/dynamicinformer/informer.go#L138 so that it
- Fills in the `apiVersion` from `gvr` and
- Supplies an annotation that carries `gvr.Resource`, using a new standard annotation name that gets established here.

The idea continues with making https://github.com/kubernetes/client-go/blob/a890e7bc14d5062a2a7eb96a5286239383d5cac8/tools/cache/reflector.go#L204 not give up on empty `gvk` but instead look for the `apiVersion` and that new annotation carrying the resource and, if found, use those to make the `r.expectedTypeName`.  But there is also the matter of `r.expectedGVK`.  I suppose the idea is to add `r.expectedGVR` as an alternative, allowing either of those to be supplied and generalizing https://github.com/kubernetes/client-go/blob/a890e7bc14d5062a2a7eb96a5286239383d5cac8/tools/cache/reflector.go#L511-L516 to check against whichever one was supplied.

Have I got that right?  It seems plausible to me.

**Comment by ncdc** [comment]
Yes, that's essentially it. It's working nicely for me locally

**Comment by MikeSpreitzer** [comment]
I think that would make a reasonable PR.
