### ISSUE TITLE
apiserver crashes with dual-stack service CIDRs if primary range does not match `kubernetes.default` Public IP family in k8s >= 1.24

### ISSUE THREAD

**Issue by tyler-lloyd** [kubernetes/kubernetes#111671]
### What happened?

apiserver crashes at startup if using dual-stack service CIDRs but the primary service CIDR family does not match the IP family of the advertised address.

#106721 introduced validation that checks the service CIDR is the same IP family as the advertised public address of apiserver. It assumes single-stack scenarios and does not check `ExtraConfig.SecondaryServiceIPRange`

### What did you expect to happen?

This should not block apiserver to come up. AKS has been testing clusters with the IPv6 service CIDR as primary with an IPv4 public IP with no issues until 1.24. Example of the kubernetes default service with IPv6 cluster IP but IPv4 endpoint.

```
Name:              kubernetes
Namespace:         default
Labels:            component=apiserver
                   provider=kubernetes
Annotations:       <none>
Selector:          <none>
Type:              ClusterIP
IP Family Policy:  SingleStack
IP Families:       IPv6
IP:                fdff:ffff:1234:6754::1
IPs:               fdff:ffff:1234:6754::1
Port:              https  443/TCP
TargetPort:        443/TCP
Endpoints:         52.188.128.76:443
Session Affinity:  None
Events:            <none>
```

### How can we reproduce it (as minimally and precisely as possible)?

Create a dual-stack cluster using k8s 1.24 with an IPv4 public IP and order the service-cluster-ip-range argument to apiserver such that IPv6 is first (e.g. `--service-cluster-ip-range="fdff:ffff:1234:6754::/108,100.64.0.0/16"`. Apiserver will fail to come up with a similar error message

```
I0803 14:48:27.991658       1 flags.go:64] FLAG: --advertise-address="20.21.22.23"
I0803 14:48:27.992806       1 flags.go:64] FLAG: --service-cluster-ip-range="fdff:ffff:1234:6754::/108,100.64.0.0/16"
E0803 14:48:30.149624       1 run.go:74] "command failed" err="error creating bootstrap controller: service IP family \"fdff:ffff:1234:6754::/108\" must match public address family \"20.21.22.23\""
```

### Anything else we need to know?

I think we should update `pkg/controlplane/controller.go` to also check the secondary service IP range during the reconciliation.

### Kubernetes version

>= 1.24

### Cloud provider

<details>
Azure
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by tyler-lloyd** [comment]
@aojea PTAL and let me know your thoughts on this issue. I think a simple fix would be to also check the secondary service range in `pkg/controlplane/controller.go`

**Comment by thockin** [comment]
The block you posted is suspicious:

```
Name:              kubernetes
Namespace:         default
Labels:            component=apiserver
                   provider=kubernetes
Annotations:       <none>
Selector:          <none>
Type:              ClusterIP
IP Family Policy:  SingleStack
IP Families:       IPv6
IP:                fdff:ffff:1234:6754::1
IPs:               fdff:ffff:1234:6754::1
Port:              https  443/TCP
TargetPort:        443/TCP
Endpoints:         52.188.128.76:443
Session Affinity:  None
Events:            <none>
```

You have a Service with a v6 "frontend" and a v4 "backend".  We specifically do not support that - we can't convert between families.

It sounds like the bug is that apiserver reconciled itself according to the default rules used for any service (single-stack, primary family == IPv6) without considering the `--advertise-address`.  It seems reasonable that we use the same family as the `--advertise-address` if that family is available.

Is that the correc reading of this bug?

**Comment by tyler-lloyd** [comment]
@thockin interesting, I did not realize this wasn't supported. TIL. The clusters we've done this on have only been test clusters where nothing reaches out to the apiserver from within the cluster so it was never noticed. We will make sure to set the IPv4 CIDR before the IPv6 in the args for clusters using an IPv4 advertise address. Do you think a bug needs to be filed for earlier k8s versions to prevent apiserver from reconciling itself like this? The PR from @aojea I linked in this issue should take care of it for 1.24 and greater.

**Comment by aojea** [comment]
Yeah, the problem is that using that configuration leaves the cluster unusable because of

> Service with a v6 "frontend" and a v4 "backend"

All InCluster communications use the "kubernetes.default" service. The clusters boots but controllers or apps that use the apiserver Service fail, creating a lot of confusion to users, since it is not easy to understand why the applications fail.

**Comment by aojea** [comment]
> Do you think a bug needs to be filed for earlier k8s versions to prevent apiserver from reconciling itself like this?

1.23 at max, that is when [ dual stack went GA](https://kubernetes.io/docs/concepts/services-networking/dual-stack/)

I can't remember why I didn't backport it, but it is probably I forget, feel free to do it

**Comment by thockin** [comment]
What we are doing now is clearly wrong.  apiserver should not set this up.

I think it's reasonable to consider whether to use the non-primary range when `--advertise-address` is within that, or else actually cause an error saying they do not match.

**Comment by aojea** [comment]
> What we are doing now is clearly wrong. apiserver should not set this up.

What is wrong? Who should configure the endpoint or current fix?

Let's take a look and how this works

1. The bootstrap of the apiserver creates a Service that is SingleStack with name "kubernetes.default" using the first IP of the Primary service ip range, this was decided during dual stack to keep backwards compatibility, creating the notion of Primary ServiceIPRange

https://github.com/kubernetes/kubernetes/blob/e6d6409cf873b0eac47216ff6061387d9c38b002/cmd/kube-apiserver/app/options/options.go#L74-L75

https://github.com/kubernetes/kubernetes/blob/bd9444c1cfd438690dc21c31404dd79ab60dc6cb/cmd/kube-apiserver/app/server.go#L539-L547

https://github.com/kubernetes/kubernetes/blob/d82f98c9b3dbbdf7daed2a17fb44ecc3ac7d23ad/pkg/master/master.go#L95-L96

2. If you use the endpoints reconciler (this case) it will use the configured `--advertise-address` as the endpoint IP for the "kubernetes.default" service.

https://github.com/kubernetes/kubernetes/blob/bd9444c1cfd438690dc21c31404dd79ab60dc6cb/pkg/controlplane/controller.go#L126

https://github.com/kubernetes/kubernetes/blob/bd9444c1cfd438690dc21c31404dd79ab60dc6cb/pkg/controlplane/controller.go#L155-L156

If the families doesn't match,  you have a broken cluster. 
We had a lot of bug reports because of this, reports are like: "I have some things that doesn't work within the cluster, pods restart with connection timeout trying to connect to service kubernetes.default ...."

Users and devs are not able to identify this problem easily, troubleshooting it requires knowing how apiserver bootstrap works and the Dual-stack Services/Endpoints relations , nobody is checking that the Service and the Endpoint IP family doesn't match, I mean, why on a connection timeout are you going to think that the problem is that :upside_down_face: 




```
$ kubectl get services
NAME         TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
kubernetes   ClusterIP   10.96.0.1    <none>        443/TCP   45h
$ kubectl get endpoints
NAME         ENDPOINTS         AGE
kubernetes   172.18.0.2:6443   45h

```

> I think it's reasonable to consider whether to use the non-primary range when `--advertise-address` is within that, or else actually cause an error saying they do not match.

Then you have to change the convention to assign the IP to the "kubernetes.default" Service, and that has a lot of implications, @danwinship covers this topic more in detail in his KEP https://github.com/kubernetes/enhancements/tree/master/keps/sig-network/2438-dual-stack-apiserver

If your concern is "how did we get there, we could have done better" I agree, but changing this right now seems complicated and is better to fail fast (the config is invalid) than leaving a cluster with an unusable "kubernetes.default" Service, with all the things it implies

**Comment by danwinship** [comment]
Yeah, the fix for now is probably "require that `--advertise-address` matches the primary service address family".

**Comment by thockin** [comment]
Agree

**Comment by aojea** [comment]
> Yeah, the fix for now is probably "require that `--advertise-address` matches the primary service address family".

is not as easy, we need to match the primary ServiceIPRange family, that comes from the flags, with the `advertise-address` that does not necessarily come from a flag, and usually is derived from the host IP (the IP obtained from the interface with the default route)

https://github.com/kubernetes/kubernetes/blob/ae62cd6ce2a61a6252c62a1de7a7061a2484a477/staging/src/k8s.io/apiserver/pkg/server/options/server_run_options.go#L104-L120

there is also the problem that --advertise-address` can use the unspecified address to favor one or the other family during the "discovery", but does not necessarily mean that the obtained IP will match it

**Comment by aojea** [comment]
... and, only if the flag `--endpoint-reconciler-type` is set, if is `none`, the endpoints are not generated by the apiserver, are generated externally

```
--endpoint-reconciler-type string     Default: "lease"
--
  | Use an endpoint reconciler (master-count, lease, none) master-count is deprecated, and will be removed in a future version.
```

**Comment by danwinship** [comment]
`--endpoint-reconciler` doesn't matter (in the sense that, if you try to manually set endpoint IPs of the wrong family, it won't actually work).

The "kubernetes" Service will _always_ have a clusterIP from the primary service CIDR, therefore the "kubernetes" Endpoints/EndpointSlice must also have IPs from the primary service CIDR's family or the apiserver service won't work, therefore anything else that redirects traffic to either the "kubernetes" clusterIP or its endpoint IPs must also be using the primary IP family.

**Comment by aojea** [comment]
> `--endpoint-reconciler` doesn't matter (in the sense that, if you try to manually set endpoint IPs of the wrong family, it won't actually work).

my point is that we only panic if we know that we are going to do something wrong

https://github.com/kubernetes/kubernetes/blob/bd9444c1cfd438690dc21c31404dd79ab60dc6cb/pkg/controlplane/controller.go#L98

if the endpoint reconciler is not set there is no check

**Comment by aojea** [comment]
/close

This is working as intended, it is the best solution we can provide with current state, most probably if we were able to redisign the kubernetes.default Service and endpoints we could something much betters, but avoid users to keep debugging why the cluster starts but nothing works during hours ( as Dan and I had to do some tieme ago ...)
