### ISSUE TITLE
Default `.spec.replicas` value for HorizontalPodAutoscaler

### ISSUE THREAD

**Issue by squakez** [kubernetes/kubernetes#111781]
When applying a HorizontalPodAutoscaler on a resource which has a missing `.spec.replicas` value (which may be the default state for any given custom resource), it fails with something like:
```
Internal error occurred: the spec replicas field ".spec.replicas" does not exist
```
The immediate workaround is to set `.spec.replicas` to 1 but I wonder if we could instead interpret the missing field with the default value of 1 or instead looking at `.status.replicas` which may hold the correct value.

Ref https://github.com/apache/camel-k/issues/3132

**Comment by oliviermichaelis** [comment]
Hi @squakez, I think this could be an expected behaviour. Based on the [documentation for the scale subresource](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#scale-subresource):

> If there is no value under the specReplicasPath in the custom resource, the /scale subresource will return an error on GET

I don't know how that should be handled in the CRD, though. Maybe the CRD could either define a sensible default value or require users to set the `.spec.replica`?

**Comment by squakez** [comment]
I see. I guess that thinking on the `specReplicasPath` as something optional, is not really something you're taking in consideration. The alternative, as you've suggested, would be on the API consumer to set either a default value or force the user to include any.
