### ISSUE TITLE
Pass event of pod termination to `preStop` hook

### ISSUE THREAD

**Issue by kylecarbs** [kubernetes/kubernetes#111719]
### What would you like to be added?

> This hook is called immediately before a container is terminated due to an API request or management event such as a liveness/startup probe failure, preemption, resource contention and others.

I'd like for the event to be passed to the `preStop` hook.

I'm not proposing an abstraction here due to my lack of familiarity with the Kubernetes codebase.

### Why is this needed?

At Coder, we provision development environments with Terraform. An agent runs inside a Kubernetes container that enables external connections. When a container dies, we'd like to display the reason in our UI so the user sees more than "Disconnected". I'd expect to display a message like "The node your container was on preempted!".

I'm very open to alternatives for solving this problem!

**Comment by arrowfeng** [comment]
You want to know why the container stopped If I understand correctly? I think you can query the current pod's events and then do something you want in custom.

**Comment by samsp-msft** [comment]
Having the reason the container is being terminated being passed to `preStop` would enable some very useful diagnostic tools. While logs can tell you about what is going on, you would likely need extensive logging, and to turn up the log level, which has an impact on performance, storage and analysis requirements for high load services. So if instead `preStop` can be used to initiate collection of a stack dump or GC dump of the process then you can collect high fidelity diagnostic data at the point of issue detection. Knowing the reason for killing the instance informs whether collection is needed, and what type of dump should be created.

It would be great if the reason could be passed as an environment variable for the exec action for `preStop` and appended as a query variable for the url.

It seems that the reason is known at https://github.com/kubernetes/kubernetes/blob/81bd2496bce080e5788cf18a807cdd42bd4ee8c1/pkg/kubelet/kuberuntime/kuberuntime_container.go#L666, but is not passed through at https://github.com/kubernetes/kubernetes/blob/81bd2496bce080e5788cf18a807cdd42bd4ee8c1/pkg/kubelet/kuberuntime/kuberuntime_container.go#L697
