### ISSUE TITLE
Fail pod with invalid image

### ISSUE THREAD

**Issue by ender-wieczorek** [kubernetes/kubernetes#111788]
When you specify an invalid image like `dummy`, Kubernetes keeps trying to start the pod forever. We should fail immediately and have the Job or Deployment retry policy handle retries.

**Comment by BenTheElder** [comment]
>  When you specify an invalid image like dummy, [...]

FWIW this isn't an invalid image name, it's normalized to `docker.io/library/dummy:latest` in the same way docker would.

Kubernetes has no way to know if an image isn't pull-able transiently or if the image name is "bad" somehow and would never be pullable, this image could exist.

> Kubernetes keeps trying to start the pod forever. We should fail immediately and have the Job or Deployment retry policy handle retries.

Because above, I don't think we can do that.

/sig node
