### ISSUE TITLE
kubectl edit seems to always use client-side apply, can it use server-side?

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#111924]
### What happened?

It seems impossible to request `kubectl edit` to send a server-side apply request

### What did you expect to happen?

To have a --server-side flag

### How can we reproduce it (as minimally and precisely as possible)?

`kubectl edit --help`

### Kubernetes version

Fairly recent HEAD

### Cloud provider

GCP

**Comment by apelisse** [comment]
I don't think we can, one is only supposed to server-side apply the fields they care about. We could build a patch with the difference that you're trying to apply, I don't know if it's practical. What problem are you trying to solve?

**Comment by KnVerey** [comment]
I'm a bit confused here, as I didn't think `kubectl edit` ever uses CSA, and the following simple experiment with kubectl v1.24 shows it already sends a patch with a field manager: `kubectl edit -v=6 deployment foo` on a CSA-created resource issues `PATCH https://127.0.0.1:52144/apis/apps/v1/namespaces/kverey-test/deployments/foo?fieldManager=kubectl-edit&fieldValidation=Strict`. The patch in my example was `{"spec":{"template":{"metadata":{"labels":{"version":"1.0.2"}}}}}`, i.e. no CSA data. Inspecting the object afterwards show the original CSA annotation unmodified (still has the old value for the field I edited), a new `kubectl-edit` field manager owning the field I edited, and the `kubectl` field manager no longer owning it.

I do see a different issue in terms of compatibility with SSA though: `kubectl edit --save-config` sends a patch that includes the CSA annotation, with problematic looking content. Specifically, it includes all the managed field data (as well as status). For one thing, managed fields can't have been edited, because they aren't shown in the editor, _even if the --show-managed-fields flag is used_. Perhaps CSA is ignoring these anyway? The more important question is what that flag should do with `kubectl edit` in a SSA world, if we even need it anymore. Currently, it effectively hands CSA management of all fields, including stuff that doesn't make sense and presumably gets ignored (status, UUID...). If that's useful, I'm not understanding why.
