### ISSUE TITLE
CSI volumes left overs are not cleaned up if CSI plugin is attachable

### ISSUE THREAD

**Issue by gnufied** [kubernetes/kubernetes#111933]
### What happened?

1. Create a Deployment or SS that uses a vsphere CSI volumes (for example).
2. Shutdown the node while pod was running.
3. Wait for node to go `NotReady` and pod to switch to `Terminating` state. 
4. Bring back the node up.
5. If the pod migrates to different node (or pod gets deleted), then files/directories inside `/var/lib/kubelet/pods/xxxx` should be cleaned up.

The reason those directories are not being cleaned up is because:

1. The volume types that are attachable, kubelet expects `node-publish-path` to be a mount point during reconstruction. So if node is rebooted then reconstruction fails because `/mount` path is not a mount point.
2. Kubelet tries to "Cleanup" the volume, but CSI driver may be unavailable at this point.
3. As a result volumes are never cleaned up.

### What did you expect to happen?

Expected cleanup to happen properly. 

### How can we reproduce it (as minimally and precisely as possible)?

See above

### Kubernetes version

master

### Cloud provider

Any

### OS version

Linux

**Comment by gnufied** [comment]
cc @dobsonj @jsafrane @jingxu97

**Comment by cvvz** [comment]
Hi @gnufied, thanks for finding this bug. I'm currently reading CSI and volume related code, and want to make contribution on k8s, may I have the opportunity to work on this bug? Really appreciate that 😀

**Comment by cvvz** [comment]
Hi, @gnufied I've created a PR to solve this issue. And could you PTAL?

In the case of this issue, orphan pod volume was not cleaned up successfully by volume manager since csi driver was not available at that time, however, it still can be cleaned by housekeeping handler. The reason why it not happened is because vol_data.json file blocked the process of removeall.RemoveDirsOneFilesystem in removeOrphanedPodVolumeDirs which can only remove dir but not file. So if we can clean it up here before calling out csi driver, orphan pod volume will be cleaned by housekeeping handler eventually.
