### ISSUE TITLE
Support active deadline in jobs since the time the pod started

### ISSUE THREAD

**Issue by asm582** [kubernetes/kubernetes#111948]
### What happened?

When a job is started with `activeDeadlineSeconds` param the duration currently is considered as soon as the job controller reports the job as running but it may not be the case that pods are running. In our case, All pods associated with the job are in the `Pending` phase. 

### What did you expect to happen?

We expect that the job controller should allow a pod min of 1 pod associated job to be in the `Running` phase before terminating all the pods associated with the job.

### How can we reproduce it (as minimally and precisely as possible)?

- Download minikube
- Taint node
- Submit job without tolerations to the only node in minikube cluster.
- Pods associated with the job remain pending and eventually, the pod(s) get deleted without even running.

### Kubernetes version

<details>

```console
$ kubectl version
$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.1", GitCommit:"3ddd0f45aa91e2f30c70734b175631bec5b5825a", GitTreeState:"clean", BuildDate:"2022-05-24T12:26:19Z", GoVersion:"go1.18.2", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:19:12Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}

$ minikube version
minikube version: v1.25.2
commit: 362d5fdc0a3dbee389b3d3f1034e8023e72bd3a7
```
</details>

### Cloud provider

<details>
NA
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
$ uname -a
$ uname -a
Linux mcad-dev.sl.cloud9.ibm.com 5.4.0-113-generic #127-Ubuntu SMP Wed May 18 14:30:56 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>
NA

### Container runtime (CRI) and version (if applicable)

<details>
Docker
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
NA
</details>

**Comment by bmoe24x** [comment]
+1 on this, would like the same functionality. When deploying to some multi tenant clusters we don't have direct operations over, we often see Pods (particularly from Jobs) get stuck in a pending state. I would like to set my job `activeDeadlineSeconds` to 30m but have a Pod that is pending to be controlled by an independent `activeDeadlineSeconds` value of say 10m

**Comment by kannon92** [comment]
This does seem like a useful feature.  I just wanted to say this effects more than the pending state.  If a container is being pulled down, this activeDeadlineSeconds will terminate the pod.   

I don't know if this is a bug though but maybe an enhancement request.  Sorta of a conditionally apply activeDeadlineSeconds if your job/pod is in the Running State.

**Comment by alculquicondor** [comment]
This is working as intended. Say for example you have a CronJob, and each instance of it (a Job) only makes sense to run in the next 30 minutes. Then, even if the Pods didn't have a chance to run, they should still be terminated.

We don't currently have an alternative to this behavior in the API, but it would have to be a new feature.

Instead of waiting for phase Running to start the timer, we probably should wait for a Pod (or a configurable number of Pods) to be [Ready](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-conditions).

I would welcome a KEP for this, but the enhancements freeze for 1.26 closes tomorrow, so it would have to be for 1.27 or later.

/remove-kind bug
/kind feature

**Comment by alculquicondor** [comment]
For sure. You can write `/assign` in a comment.
Here's the KEP template https://github.com/kubernetes/enhancements/tree/master/keps/NNNN-kep-template

Although it might be wise to discuss this in SIG meeting first.

**Comment by kannon92** [comment]
I was thinking some about this feature.  

The way ActiveDeadline currently works is it looks at `StartTime` and starts a deadline from that.  

If we wanted to add activeDeadline by Ready or Pending, I think we would need to add a new Status Field that starts a timer once a guarantee stage is past (x amount of Pods are Pending/Ready).

So this feature would require two things:

1) API for deadline by phase (Ready or Pending)
2) Status field when phase is passed.

From what @alculquicondor has suggested around Ready Condition, this reminds me of a requirement that the jobset brings up.  

> Add readiness status. Add a new condition to declare a job is ready. This should be configurable, for example the job is ready if 80% of the pods are ready.

Now the complication becomes if we want to include behavior for pending pods or ready pods we would want to include a Statusfield for each case so we could correctly handle a deadline?

**Comment by alculquicondor** [comment]
If we add the concept of job "readiness", we should probably have a new condition. Then the deadline can be based on the timestamp for that condition. However, something to think about is whether a Job can become unready. After that, what should happen to the timeout?

Alternatively, why is this a feature that needs to be backed off in the Job API? Can't the application itself handle this?

In the case of Jobs created by a CronJob, it makes sense to have a deadline based on the Job's start time, because it doesn't matter how long the pods take to schedule, the CronJob still needs some control over how long a Jobs is allowed to run, even if nothing really started.

Also, there's `activeDeadlineSeconds` in the Pod. Why is this not enough?

**Comment by kannon92** [comment]
> Also, there's activeDeadlineSeconds in the Pod, that starts counting from Pod startup. Why is this not enough?

So `activeDeadlineSeconds` in jobs sets a condition in the job controller and it effectively turns off the backOffLimit for a job if you hit the deadline.  I think this is good behavior. 

If you use `activeDeadlineSeconds` in a Pod, then the job controller assumes that your pod fails and retries based on the backoffLimit.  I don't think the job controller knows that the pod hit a deadline and I'm not sure it should.  

I think this behavior would be why I would want to use `activeDeadlineSeconds` in a Job and not rely on pods if I want to turn off retries if I go over a certain deadline.   

> If we add the concept of job "readiness", we should probably have a new condition. Then the deadline can be based on the timestamp for that condition. However, something to think about is whether a Job can become unready. After that, what should happen to the timeout?

I don't see an issue on this so I will go ahead and create that there.  I mostly brought up the readiness condition because I think we would need a condition if we want an active deadline based on it.  But I think maybe we want to just add the condition first.  I'm not pushing for this feature at the moment but I was thinking about it as I was looking in the job code.  

> In the case of Jobs created by a CronJob, it makes sense to have a deadline based on the Job's start time, because it doesn't matter how long the pods take to schedule, the CronJob still needs some control over how long a Jobs is allowed to run, even if nothing really started.

I think this is the concept of `startingDeadlineSeconds` but CronJob also supports `activeDeadlineSeconds` also.  
https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/#starting-deadline

> Alternatively, why is this a feature that needs to be backed off in the Job API? Can't the application itself handle this?

I would think that a goal of the Job Controller is have a standard for running batch jobs in K8 that doesn't require every organization to write a higher level controller to implement a one-off-feature.  I am new so maybe I misunderstand.

**Comment by alculquicondor** [comment]
> If you use activeDeadlineSeconds in a Pod, then the job controller assumes that your pod fails and retries based on the backoffLimit. I don't think the job controller knows that the pod hit a deadline and I'm not sure it should.

@mimowo was considering adding a Pod condition for reaching active deadline seconds, in the context of #115688
Then you could have a rule for `FailJob` that matches the condition.

Would that be enough?

> I would think that a goal of the Job Controller is have a standard for running batch jobs in K8 that doesn't require every organization to write a higher level controller to implement a one-off-feature. I am new so maybe I misunderstand.

Not at all, I'm just giving standard questions when a new feature is requested: do you really need this? can this be implemented in a different way?
It doesn't necessarily mean I'm opposed to the feature, just that we have to consider the alternatives.

**Comment by alculquicondor** [comment]
/retitle Support active deadline in jobs since the time the pod started
