### ISSUE TITLE
Need a container with installed gsutil (to access gcs)

### ISSUE THREAD

**Issue by marekbiskup** [kubernetes/kubernetes#11213]
Consider the following use case:
A hadoop batch job creates an input file for another service. The service then uses it as an input.
We need to exchange the data via some storage. But a PD cannot be mounted RW on on many nodes (we need RW access for hadoop, and RO for the service).

A way (on GCP) to exchange the data is to use GCS. A sidecar container would read the input file from GCS and put in on a local disk (non-persistent), for the service.
1. Create a public container that has gsutil installed.
   - (by the way, json API can be used to access GCS, so having gsutil is not so important)
2. This use-case can be added to our examples.

**Comment by marekbiskup** [comment]
cc @brendandburns @lavalamp

**Comment by lavalamp** [comment]
I'm pretty neutral on this. On one hand, it's relatively easy and we might as well demonstrate it. On the other hand, it's not portable between clouds, so __I consider it an anti-pattern__.

When we get a proper solution for batch, IMO it should be possible to have tasks that have volumes as their output and other tasks that take those volumes as their input, so that you can work around mounting restrictions. Uploading/downloading your data at every step is super inefficient, at least on GCE where your "local" disk is actually a PD mounted over the network.

A solution that explicitly manages volumes like this should also make it possible to have good properties when used with SSD volumes. (E.g., schedule step B on the machine that has the output from step A.)

**Comment by erictune** [comment]
How hard is it to make the program in the pod access the GCS api directly?

**Comment by marekbiskup** [comment]
> How hard is it to make the program in the pod access the GCS api directly?
Not hard. We managed to make it work within minutes.

**Comment by kargakis** [comment]
@ixdy is this still an issue?

**Comment by ixdy** [comment]
given https://github.com/kubernetes/kubernetes/issues/11213#issuecomment-121516336 I'm going to close.
