### ISSUE TITLE
why service of ClusterIP that has no endpoints is different from service of NodePort that has no endpoints

### ISSUE THREAD

**Issue by lojies** [kubernetes/kubernetes#112233]
### What happened?

when set internalTrafficPolicy: true, service of ClusterIP that has no endpoints, iptables rule "--reject-with icmp-port-unreachable" is added.
```
-A KUBE-SERVICES -d 123.123.22.76/32 -p tcp -m comment --comment "default/kubia-local has no endpoints" -m tcp --dport 80 -j REJECT --reject-with icmp-port-unreachable
```
when set externalTrafficPolicy: true,  service of NodePort that has no endpoints, iptables rule "-j KUBE-MARK-DROP" is added.
```
-A KUBE-XLB-4A2QNZEGYSIQGTWQ -m comment --comment "default/kubia-nodeport-local has no local endpoints" -j KUBE-MARK-DROP
-A KUBE-FIREWALL -m comment --comment "kubernetes firewall for dropping marked packets" -m mark --mark 0x8000/0x8000 -j DROP
```
why this is different?
if a udp service with no reply received, is it ok?

### What did you expect to happen?

why this can not be deal the same?

### How can we reproduce it (as minimally and precisely as possible)?

create a ClusterIP service with internalTrafficPolicy: true and a NodePort service with externalTrafficPolicy: true.
check iptables-save result.

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by danwinship** [comment]
> why this is different?
> if a udp service with no reply received, is it ok?

So I think you're suggesting that we should REJECT rather than DROP in both cases, in which case I have bad news for you; as of 1.24, we DROP in both cases.

For the externalTrafficPolicy case, DROP rather than REJECT is necessary to prevent connections being accidentally rejected due to race conditions when endpoints move between nodes.

For the internalTrafficPolicy case, the semantics are less clear, but it seemed to make sense to be consistent.

The change to DROP in the internal case was part of a much larger refactoring of the code, so it can't easily be backported to earlier releases.
