### ISSUE TITLE
ci-kubernetes-node-kubelet-serial-containerd failing device plugin test - Device Plugin [Feature:DevicePluginProbe][NodeFeature:DevicePluginProbe][Serial] DevicePlugin [Serial] [Disruptive] Can schedule a pod that requires a device

### ISSUE THREAD

**Issue by bobbypage** [kubernetes/kubernetes#112612]
### Which jobs are failing?

https://testgrid.k8s.io/sig-node-release-blocking#node-kubelet-serial-containerd

### Which tests are failing?

Device Plugin [Feature:DevicePluginProbe][NodeFeature:DevicePluginProbe][Serial] DevicePlugin [Serial] [Disruptive] Can schedule a pod that requires a device

### Since when has it been failing?

It appears a bit flaky on testgrid, but more recently been failing more often

### Reason for failure (if possible)

```
{Expected
    <int>: 3
to equal
    <int>: 2 failed test/e2e_node/device_plugin_test.go:184
k8s.io/kubernetes/test/e2e_node.testDevicePlugin.func1.3()
	test/e2e_node/device_plugin_test.go:184 +0x1c6}
```

example - https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-serial-containerd/1572297800845103104

### Relevant SIG(s)

/sig node

**Comment by swatisehgal** [comment]
I ran this test locally 15 times back to back and did not run into this failure. The test passed locally. I suspect this to be a case where pod cleanup is not happening properly. In this test, we are relying on the number of PodResources and based on the error it looks like we have an addtional pod running other than the two expected pods (device plugin pod and test pod requesting device) but can't be 100% sure because we don't have enough logs to support that claim. Going to add more logs to expose output obtained from the podresource API endpoint.
