### ISSUE TITLE
Ephemeral Containers link provided in CHANGELOG is broken

### ISSUE THREAD

**Issue by sathyanarays** [kubernetes/kubernetes#112908]
### What happened?

https://github.com/kubernetes/kubernetes/blob/master/docs/concepts/workloads/pods/ephemeral-containers

The above link provided in **v1.25.0 -> What's New (Major Themes) -> Ephemeral Containers Graduate to Stable ** is broken. GH responds with page not found

### What did you expect to happen?

To open the documentation related to ephemeral-containers

### How can we reproduce it (as minimally and precisely as possible)?

Trivial

### Kubernetes version

Not applicable

### Cloud provider

Not applicable

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by vaibhav2107** [comment]
The correct link for ephemeral containers would be:
https://kubernetes.io/docs/concepts/workloads/pods/ephemeral-containers/

**Comment by sftim** [comment]
I assume this was actually a report about a **link** that might have been intended as https://github.com/kubernetes/website/blob/main/content/en/docs/concepts/workloads/pods/ephemeral-containers.md (which renders as 
https://k8s.io/docs/concepts/workloads/pods/ephemeral-containers/)

We should fix that in the v1.25 changelog if we're able to.
/sig release

**Comment by ggold7046** [comment]
Hi @sftim, how should I start to work on this issue? Could you please guide me on this ?

**Comment by sftim** [comment]
@ggold7046 

It sounds like you're inviting me to make time to help you learn how to contribute here. Thank you for the offer, however I'm going to decline it.

Some context:
Although I can offer tips about whether this is a bug or not, I haven't investigated enough to be able to explain what work is needed to fix the issue. I could do that investigation but right now it's not a priority for me.

**Comment by vaibhav2107** [comment]
I have investigated a little, the issue is regarding the link present in [Ephemeral Containers Graduate to Stable](https://kubernetes.io/blog/2022/08/23/kubernetes-v1-25-release/#ephemeral-containers-graduate-to-stable)

I think it is working fine now and does not need any update. If someone can confirm this we can close this issue

**Comment by vaibhav2107** [comment]
@ggold7046 If you are new to community, you can take help from this contribute [doc](https://kubernetes.io/docs/contribute/) and could find some trivial bug to start with

**Comment by pacoxu** [comment]
This seems to be a general problem of Changelogs before v1.25.
- before v1.25, the major theme part was added back by release team https://github.com/kubernetes/sig-release/pull/1996 and re-generate the change log file.
- after v1.26, we did not add the major them in the CHANGELOG, and you can find the major theme in release blog only.

The text is copied from the blog whose links are pointed to `kubernetes.io/` not code base link. That's why the link is not correct. 

I wondered if someone can fix all the links or just keep it as is. Or just remove those major themes here as it is already in release blog(website repo). De-dup doc is as important as de-dup code IMO. Leave to release note team to decide on this. 

Contributions are welcome to make things better.

/remove-kind bug
/kind cleanup
