### ISSUE TITLE
Control permissions of non-emptyDir volumes

### ISSUE THREAD

**Issue by pmorie** [kubernetes/kubernetes#11319]
Forking from #2630 

This issue is to discuss how we can offer control of permissions on volumes that are not emptyDir or based on emptyDir (secrets, git repo, downward API) so that they can be used easily with packages that have requirements about perms.

@thockin @eparis @smarterclayton

**Comment by smarterclayton** [comment]
So existing proposal is there is a pod wide security context that applies
to volumes (explicit or inferred).  Volumes need to know the uid, gid,
SELinux label.  They also may need perm flags, but I assume that is per
volume?

On Jul 15, 2015, at 2:12 PM, Paul Morie <notifications@github.com> wrote:

Forking from #2630
<https://github.com/GoogleCloudPlatform/kubernetes/issues/2630>

This issue is to discuss how we can offer control of permissions on volumes
that are not emptyDir or based on emptyDir (secrets, git repo, downward
API) so that they can be used easily with packages that have requirements
about perms.

@thockin <https://github.com/thockin> @eparis <https://github.com/eparis>
@smarterclayton <https://github.com/smarterclayton>

—
Reply to this email directly or view it on GitHub
<https://github.com/GoogleCloudPlatform/kubernetes/issues/11319>.

**Comment by pmorie** [comment]
@smarterclayton I'm not sure whether I think it should be per-volume type -- it cuts across all volume types, doesn't it?

**Comment by smarterclayton** [comment]
Maybe - I wasn't sure whether one of the types might not be amenable to having a perm forced.

**Comment by pmorie** [comment]
@smarterclayton I am also not sure; I am talking to folks about this now.
