### ISSUE TITLE
Kubectl restmapping cache causes inconsistent behaviour in case of resource name conflict

### ISSUE THREAD

**Issue by hugoShaka** [kubernetes/kubernetes#113227]
### What happened?

I deployed a CRD (`teleportroles`) with the shortnames `role` and `roles`, conflicting with `roles.rbac.authorization.k8s.io/v1`.

Initially `kubectl get role` and `kubectl get roles` were both returnning `roles.rbac.authorization.k8s.io/v1` resources.

I ran `kubectl get teleportrole`.

Now, `kubectl get role` return my CRs instead of `roles.rbac.authorization.k8s.io/v1` resources.

However `kubectl get roles` continues to return `roles.rbac.authorization.k8s.io/v1` resources.

### What did you expect to happen?

I expect kubectl's behaviour to be consistent. The outcome of `kubectl get X` should not depend on the order the APIs were discovered and cached. I also expect exact names to be preferred over shortnames.

### How can we reproduce it (as minimally and precisely as possible)?

On a freshly kubectl context (not one you already used and might have cached RESTMappings):
- create a CRD with a shortname conflicting with another resource, `role` for example
- run `kubectl get role -n kube-sytem` (because there are roles by default there) and `kubectl get roles -n kube-system`
- observe the kube rbac resources are properly returned
- run `kubectl get yourcrd` once
- run `kubectl get role -n kube-sytem` (because there are roles by default there) and `kubectl get roles -n kube-system`
- observe the `kubectl get role` no longer returns the kubernetes roles, but `kubectl get roles` still does. 

### Anything else we need to know?

During initial resolution, [exact name matches are preferred](https://github.com/kubernetes/kubernetes/pull/58861). It seems this property is not true anymore when doing cache lookups. When cache was populated by `kubectl get teleportroles`, it overrode the mapping `role` -> `roles.rbac.authorization.k8s.io/v1`

I believe this is the same issue as https://github.com/kubernetes/kubernetes/issues/59812

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.0", GitCommit:"4ce5a8954017644c5420bae81d72b09b735c21f0", GitTreeState:"clean", BuildDate:"2022-05-03T13:46:05Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.4+k3s1", GitCommit:"c3f830e9b9ed8a4d9d0e2aa663b4591b923a296e", GitTreeState:"clean", BuildDate:"2022-08-25T03:45:26Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
I repro'd on AWS and locally using k3s.
</details>

**Comment by ardaguclu** [comment]
This looks like a duplicate of these https://github.com/kubernetes/kubernetes/issues/102378, https://github.com/kubernetes/kubernetes/issues/108573

**Comment by hugoShaka** [comment]
If I understand correctly those two issues are feature requests to warn users in case of conflict, I would not consider them duplicates of this one.

Here, the issue is not that there's a conflict the user don't know. The issue is that kubectl's behaviour is not consistent on how to choose a resource. The returned  resources depend on the last cached RESTmapping, which depends on the order the commands are run.

The following snippets currently have very different behaviours:
```bash
kubectl get role
kubectl get teleportrole
kubectl delete role my-role  # deletes a teleportrole
```

```bash
kubectl get teleportrole
kubectl get role
kubectl delete role my-role  # deletes a rbac role
```

This can be harmful in CI environments when each job has a fresh RESTMapping cache.

**Comment by ardaguclu** [comment]
I'm going to investigate this issue.

**Comment by ardaguclu** [comment]
I've sorted out the problem and this is a nice finding.

when user runs;
```sh
kubectl get role
```
The expectation is that shortcut expands singular form `role` to `roles` after matching `singularName` in [this line](https://github.com/kubernetes/kubernetes/blob/f7d1eb7726fa511b6439b7f8162138742ac639ab/staging/src/k8s.io/client-go/restmapper/shortcut.go#L142). However, this does not happen because for core types discovery endpoint does not return `singularName` field other than empty. As a result, this conditional is never true for core types.

`kubectl get role` returns `roles` up to now as expected because after shortcut could not expand this to any kind(also not in CRD shortcuts), it asks defaultRESTMapper in best effort. `role` is already expanded in this [unsafe function](https://github.com/kubernetes/kubernetes/blob/f229ef70764fcb4bda69c8a7af645bab67f4ecca/staging/src/k8s.io/apimachinery/pkg/api/meta/restmapper.go#L100)

But as in this case, if there is a CRD matching as shortcut, shortcut returns that and this creates nondeterministic behavior.

Workaround solution would be;

If `singularName` is not match, we can also search `role` in all apiresource list in singular form(by using `UnsafeGuessKindToResource`). But we may not want this due to statement in [here](https://github.com/kubernetes/kubernetes/blob/f229ef70764fcb4bda69c8a7af645bab67f4ecca/staging/src/k8s.io/apimachinery/pkg/api/meta/restmapper.go#L123-L125)

Permanent solution would be;

We can introduce `SingularNameProvider`(like being done for [shortNames](https://github.com/kubernetes/kubernetes/pull/40985)) and use it in [here](https://github.com/kubernetes/kubernetes/blob/57c95fbfa12bc04456330d8b0b29f333106cf156/staging/src/k8s.io/apiserver/pkg/endpoints/installer.go#L991) to let discovery can also return singular names of core types. 

@liggitt would you mind if I ask your opinions about the solutions?

/triage accepted
