### ISSUE TITLE
I ssh into the pod unable to get the variable of the pod custom property

### ISSUE THREAD

**Issue by ghost** [kubernetes/kubernetes#113380]
When I pass kubectl exec -it ${pod} -- bash
Then when env is executed, the custom attribute variables of k8s can be obtained, such as
![image](https://user-images.githubusercontent.com/20945014/198191760-7969c46b-4824-43b0-bb31-2053c23bf9cb.png)

But when I connect to the pod through ssh, I can't get these variable values
![image](https://user-images.githubusercontent.com/20945014/198191884-a4819b21-a53c-4cc5-a1cd-cfff037b60fd.png)

Is there any way to get the values of these variables?

https://github.com/kubernetes/kubernetes/issues/113380#tasklist-block-d284d7a3-4eaf-40e1-988c-484eed0a7246

**Comment by long318737396** [comment]
please help me

**Comment by donghui12** [comment]
how to ssh pod, pod port 22 opened?

**Comment by lixiaobing1** [comment]
variable in pod is not same as the host...

**Comment by long318737396** [comment]
my pod wraps ssh  
I can log into the pod's ssh

**Comment by cmagk** [comment]
How did you set those env variables in the first place?
Are you looking to pass variables from the host?

**Comment by n4j** [comment]
`kubectl exec` sets up env variables for you while SSH relies on system login shell and hence the difference.
This is an expected behaviour between `kubectl exec` and `ssh`
More information
1. https://stackoverflow.com/questions/67277994/different-environment-variables-with-ssh-or-kubectl-exec
2. https://goteleport.com/blog/ssh-vs-kubectl/
