### ISSUE TITLE
Tests to verify that existing pods/services continue to function across cluster resize and/or upgrade

### ISSUE THREAD

**Issue by a-robinson** [kubernetes/kubernetes#11340]
We have tests that verify that things work before and after resize, but AFAIK don't sufficiently ensure that everything in the cluster continues working properly in the steady state after an upgrade. #11327 is an instance of a bug where within the first 30-60 seconds after a resize or upgrade, external load balancers on GCE will continue working, but after target pool changes have had time to propagate, they'll stop working.

This issue could just encompass keeping a cluster up for a few more minutes after upgrade/resize to verify the steady state of everything that existed before the upgrade, or it could be something like @mbforbes keeps pushing for -- a soak cluster that doesn't just create and delete resources, but with a bunch of long lived resources.

**Comment by mbforbes** [comment]
So we do have exactly this test; it's called [`cluster_upgrade.go`](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/test/e2e/cluster_upgrade.go), and is discussed in #8081, https://github.com/GoogleCloudPlatform/kubernetes/issues/8081#issuecomment-112499324, #9987, ... . It creates resources, does an upgrade, then checks whether the resources are healthy. We've wanted to do more of this (see final TODO in https://github.com/GoogleCloudPlatform/kubernetes/issues/8081#issuecomment-112499324) but it wasn't a 1.0-blocker. See other related issues for more things to add, e.g. #6084, where everything "should work" but we don't have a test that verifies this persistence.

From where I sit, it seems like a Good Thing&trade; to:

0. Add more resources to the `cluster_upgrade` test
0. Re-use this verification in tests for other destructive cluster operations, such as `resize`
0. Extend this test to wait 1, 5, 10 minutes before verifying everything is healthy

Maybe adding some kind of variable "wait" and "repeat" flags to the verifier `cluster_upgrade` is the way to go, so that by default we don't wait at all to verify resource health, but we can wait arbitrarily long to verify resource health and keep doing so. 

This gets out of what an e2e test is, I think, but seems equally important.

**Comment by ihmccreery** [comment]
Closing in favor of #15131.  Re-open if you disagree, @a-robinson.

**Comment by a-robinson** [comment]
SGTM
