### ISSUE TITLE
Discuss: Decide the future of "service" spreading.

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#11369]
Various people risen similar concerns about current spreading semantics:
Currently we do spreading only on Services (and on resources, but that's orthogonal thing), i.e. if scheduling is trying to schedule a pod from some Service (which is defined as existence of a Service that has a selector matching given pod), we'll try to schedule it on a different machine from other pods of this Service (again - meaning pods that has label set matching Service selector). We don't handle the case of multiple services matching the same Pod very well (i.e. we deterministically pick effectively random one - first Service from the list). In principle this is a correct behavior which, I believe, all of us want to preserve. The problem is that it requires users to create services before creating underlying Pods/RCs, which turns out to be not natural (e.g. pretty much all examples create Pods before Services).

This situation was noticed as a problem by multiple people already:
#11144, #10667, #4971

Current logic was introduced by:
#1965 

"Short" summary:
#1965 was about spreading by Services as currently implemented instead of identical label sets as it was before. Argument (@bgrant0607) for doing it was: 
> This (i.e. full label-set spreading) works well with a single replication controller, but breaks down when one runs canaries, multiple release tracks, rolling updates, etc.

This may indeed be a problem, to : having canary Pods with additional `type: canary` label will make canaries completely independent from production Pods, thus allowing coscheduling of them on the same Node. Not everyone was convinced that this would be a bad thing.

 #4971 was a discussion about why spreading by RC might be more desired than spreading by Service:
@abhgupta
> I had raised the question of why we used services instead of replication controllers for identifying peer pods for spreading by the scheduler. The argument is that services might not be needed and could be avoided in some cases, whereas replication controller will most likely always be there.
> While I agree that there can be multiple replication controllers per service, I still believe that spreading of pods should still happen independently for the replication controllers. Also, we have customer use cases where the services are not created at all and routing/load balancing to a group of pods is being handled by custom middleware.

@bgrant0607 
> Falling back to spreading using the full set of labels on a pod (which would also likely be the labels specified by a replication controller's selector) is a reasonable thing to do in absence of a service.

@danmcp 
> I would certainly want a rolling deployment to schedule independent of any existing replication controllers. Because what matters to me there is that the deployment when it's done is scheduled to the best fit location. I don't care much about the deployment overlapping with the existing deployment for some period of time.
> All else being equal, spreading based on service is reasonable. But it seems like a tertiary concern with the order being:
1) spread by replication controller (and whatever other labels you choose to require spreading on)
2) provide a reasonably good fit
3) spread by service

@bgrant0607 
> Of course, in the case that there is just 1 replication controller, spreading by controller labels is reasonable. However, the controller/service decoupling enables multiple replication controllers to exist indefinitely, which is typical for applications with multiple release tracks (e.g., daily and weekly), which is common for "high-functioning" DevOps teams.

This ended up with creation of headless services, which allow user to create a "Service" that do not proxy anything, but act as a definition of Pod peering. This provides a workaround for the spreading problem, assuming that users will know/remember to create Service before RCs. There's also an important question what's the 'good' level of spreading, i.e. do we want to allow canaries to run on the same machines as production jobs, or do we want to try to schedule them somewhere else. I believe that most people think that the latter is a better option.

#10667 was originally written as a quick fix for 0-limit pod scheduling, which was problematic before @davidopp changed the resource usage computation slightly. What it does is effectively implement @bgrant0607 idea of spreading using 'full set of labels' in the absence of a Service (even though I didn't knew about it when I wrote it).

#11144 was opened by @marekbiskup after speaking with some users and was documentation/example driven. It made @bgrant0607 to update some docs, but examples are still left with wrong order.
@brendandburns suggested going back to the spreading from before #1965:
> We should really spread by label sets, and not just services. That will ensure that we do spreading for both cases and things won't be order dependent.

@davidopp noted:
>  Do you mean any time two Pods have the same value of the same label, we should try to put them in different machines? (...) This is an interesting idea. I think we need to revamp the whole spreading approach post-1.0 so we can take into account multiple levels of the hierarchy (spread across nodes, across various kinds of failure domains, etc.). So we'd have to think about how this could generalize.

I created this issue to have a discussion here, instead of splitting it between multiple other Issues/PRs.

cc @thockin

**Comment by bgrant0607** [comment]
We are just talking about spreading during initial deployment. Once a service is up and pods get replaced due to rolling updates, node updates, etc., this won't be a problem.

The service is the logical grouping that the user wants to have high availability. Users shouldn't lose spreading if they use multiple replication controllers (e.g., for a canary, for multiple release tracks, or for a Zookeeper-like application), do a rolling update (which creates a new RC during the update), or use their own controller instead. We should be spreading by services. @brendandburns also wrote that we should continue to spread by service: https://github.com/GoogleCloudPlatform/kubernetes/issues/11144#issuecomment-121732740. We should be discussing how to best make this work, not whether we should be doing it.

Note also that there are other reasons services should be started first. `kubecfg` (the predecessor to `kubectl`) used to start services first among multiple resources to ensure that service environment variables would be created for the services.

It would also make sense to create the RC without specifying replicas (defaulting to 1), then create the service, then scale up the RC, which may work better in an example using progressive disclosure, and may have benefits in real scenarios also, such as ensuring one replica works before creating lots of them. That's a workflow that matches Docker and many PaaSes, and would also likely happen in the case of auto-scaling.

That said, we need to support anti-affinity among multiple groups. There are currently scenarios where it makes sense to create multiple services, such as a service with a cluster IP for each RC, for durable names and IPs, and a headless service spanning multiple RCs, for peer discovery and spreading of the whole group. There will also be situations analogous to where we use "job conflicts" in Borg, which is what #9560 is intended to address, I believe. Pods produced by a Replication Controller are just one more example.

In addition to spreading by services, I don't think it matters much whether we spread by RC or by exact label-set match, or maybe both, though I slightly prefer by RC, since the RC's selector is more an expression of semantic intent than the full set of labels. Either would work in the common case currently. Both have edge cases. For instance, we expect to have more situations in the future that will set distinct labels on pods. We expect to have more kinds of controllers in the future, also. Once we have multiple controllers it will probably make sense to make the spreading request explicit and then just create the request by default in relevant controllers.

The simplest way to support anti-affinity among multiple groups would be to just union all the relevant sets, by either explicitly creating such a set in the scheduler or just checking matches against any of a list of selectors. If we wanted to get fancy we could weigh the matches differently (e.g., highest priority to explicit conflicts, then RC, then service). That admittedly might be easier to reason about if we switched to a partial-order prioritization (aka scoring) approach rather than the current total-order approach.

**Comment by gmarek** [comment]
@bgrant0607 I agree that the world would be a better (or at least simpler) place if users would start services before RCs, create single-instance-RC-and-scale-it-up-later, but I doubt that it's going to happen. We should somehow make it work in a reasonable way for people that won't follow the blessed way, especially that RC-first-then-Service is more natural at least for me and a few other people I talked to (generally defining grouping on an empty set is not really appealing).

I need to think more about how desired-in-the-fullness-of-time solution would look like, but I think in current situation spreading by Services if possible and by RC otherwise seems to me like a good course of action.

Let me try to repeat what problem I think you mentioned, so we'd be on the same page:
* Environment variables for Service discovery (I believe that this was a hack, not the desired solution though)
* Multiple services for the single Pod (we don't handle it now very well)
* Anti-affinity among groups, i.e. preventing Pods from different groups (for some definition of group) from running on a single Node (we don't have it now)
* When we have multiple controllers we might want to make spreading explicit, hence we don't want to tie it closely with current implementation of anything (e.g. labels)

**Comment by bgrant0607** [comment]
Why is it hard to spread using both services and RCs?

**Comment by gmarek** [comment]
It's not, I just didn't understood that you suggest to do it this way.

**Comment by gmarek** [comment]
Fixed by #10667
