### ISSUE TITLE
Documentation Links shows 404 Error

### ISSUE THREAD

**Issue by kgrvamsi** [kubernetes/kubernetes#11365]
Hello,

Every link which is cached in Google shows a Github 404 error.

Examples urls:

https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/replication-controller.md
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/examples/walkthrough/replication-controller.yaml
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/pods.md

**Comment by roberthbailey** [comment]
/cc @mikedanese 

This is almost certainly due to https://github.com/GoogleCloudPlatform/kubernetes/pull/11239. It looks like it may take the google crawler a little bit of time to figure out where the new home for the docs are. 

@brendandburns @bgrant0607 - should we have left placeholder docs that pointed users to the new location (a la https://github.com/GoogleCloudPlatform/kubernetes/blob/master/CONTRIB.md)?

**Comment by bgrant0607** [comment]
No, we're going to be directing people to kubernetes.io rather than github, anyway. We moved essentially all the docs. Leaving placeholders would create a mess. We should probably remove ancient placeholders at this point.

**Comment by kgrvamsi** [comment]
Can i have the link for that as i see no documents on the main page @http://kubernetes.io/gettingstarted/

**Comment by bgrant0607** [comment]
Coming today or tomorrow, hopefully.

**Comment by bgrant0607** [comment]
In the meantime, check out:
https://github.com/GoogleCloudPlatform/kubernetes/tree/master/docs/user-guide
https://github.com/GoogleCloudPlatform/kubernetes/tree/master/docs/admin
https://github.com/GoogleCloudPlatform/kubernetes/tree/master/docs/getting-started-guides

**Comment by bgrant0607** [comment]
cc @thockin

**Comment by mbforbes** [comment]
@bgrant0607 is this fixed?
