### ISSUE TITLE
Support topology aware routing (node and zone)

### ISSUE THREAD

**Issue by ialidzhikov** [kubernetes/kubernetes#113731]
**How to categorize this issue?**
/sig networking
/kind feature
/priority important-soon

**What would you like to be added**:
Currently there is no way to achieve topology aware routing (`kubernetes.io/hostname`, `topology.kubernetes.io/zone`, `topology.kubernetes.io/region`) and define _deterministic_ rules like the ones offered from the already deprecated and removed [`ServiceTopology`](https://kubernetes.io/docs/concepts/services-networking/service-topology/):
> - Prefer endpoints on the same node, fall back on any available endpoint if none are available for this node: `["kubernetes.io/hostname", "*"]`.
> - Prefer enpoints on the same zone, but fallback on any available endpoint if none are available within this zone: `["topology.kubernetes.io/zone", "*"]`.
> - Prefer endpoints on the same node, fall back to endpoints in the same zone, followed by the same region, and failing otherwise: `["kubernetes.io/hostname", "topology.kubernetes.io/zone", "topology.kubernetes.io/region"]`. This may be useful, for example, in cases where data locality is critical.

The `ServiceTopology` feature was deprecated (and removed in K8s 1.22) in favor of [`TopologyAwareHints`](https://kubernetes.io/docs/concepts/services-networking/topology-aware-hints/):
> Note: This feature, specifically the alpha topologyKeys API, is deprecated since Kubernetes v1.21. Topology Aware Hints, introduced in Kubernetes v1.21, provide similar functionality.

Although that the docs write that TopologyAwareHints "provide similar functionality", this is not reflecting the reality. TopologyAwareHints is a feature that is applicable only in particular use cases and is not a replacement for the feature offering of ServiceTopology.

Drawbacks of TopologyAwareHints:
- Sometimes the CPU-balance heuristic is wrong. For example, if we know that the whole zonal CPU pool does not model the set of clients which will access a service, then we may erroneously disable hints. (ref https://github.com/kubernetes/kubernetes/issues/110714#issuecomment-1178163573)
- Hints do not work at low-endpoint counts. (ref https://github.com/kubernetes/kubernetes/issues/110714#issuecomment-1178163573)
- Hints are not deterministic.
- ...

Scenarios from the topology aware routing story that TopologyAwareHints do not cover:
- Prefer endpoints on the same node, fall back on any available endpoint if none are available for this node: `["kubernetes.io/hostname", "*"]`.
- Prefer enpoints on the same zone, but fallback on any available endpoint if none are available within this zone: `["topology.kubernetes.io/zone", "*"]`.

**Why is this needed**:
To allow end users to configure topology aware rounting. For example cross-zone traffic is charged from most of the cloud providers.

**References**:
- https://github.com/kubernetes/kubernetes/issues/110714 - issue that discusses that not every scenario is covered by TopologyAwareHints.
- https://github.com/kubernetes/enhancements/pull/3642 - TopologyAwareHints KEP update PR that proposes support for `service.kubernetes.io/topology-aware-hints=always`
- https://github.com/kubernetes/enhancements/pull/3293 - KEP that proposes support for `["kubernetes.io/hostname", "*"]`
- https://github.com/kubernetes/enhancements/pull/3765 - TopologyAwareHints KEP update PR that proposes SameZone heuristic

**Comment by thockin** [comment]
Hi @ialidzhikov.

You're obviously correct that the hints mechanism is not as flexible as the older form - that's very much by design.  It turns out that a) almost everyone wants topology awareness; b) almost nobody wants to manually configure it; c)  total flexibility maskes it impossible to implement some of this on other control planes.  So we aimed for (and maybe did not quite hit) a model that can be on by default, that self-tunes, and that aligns with established industry conventions.

As you cited, it has corner cases which are hard to handle.  It's entirley likely that the heuristic we have so far is not sophisticated enough, and I have no doubt that, given care and feeding, it can get smarter.

That said, I've come around to the idea of allowing SOME explicit configuration, for those cases when the heuristic doesn't work and users NEED to break glass.  You called out KEP 3015 (https://github.com/kubernetes/enhancements/pull/3293) which is where this discussion is being had.

I'm going to close this and ask that the discussion go there, since we have effectively confirmed this feature request :)

**Comment by thockin** [comment]
Can you please say why you think this should be maintained as an open
issue, despite the KEP issue which already governs the work?

I'd rather not have multiple parallel discussions.

**Comment by ialidzhikov** [comment]
First, https://github.com/kubernetes/enhancements/pull/3293 is only about Node-level topology and the KEP currently does not have a goal to tackle the zone-level topology routing. Will https://github.com/kubernetes/enhancements/pull/3293 also tackle the zone-level topology routing?

Second, I don't see any consensus being made on https://github.com/kubernetes/enhancements/pull/3293 on which approach will be taken. The first approach proposes adding "service.kubernetes.io/topology-aware-hints=Node" but there was this reply from @robscott in https://github.com/kubernetes/enhancements/pull/3642#issuecomment-1301540746 that most likely "hints" are not the right home for such enhancements.

Third, the last activity on the KEP is 22days ago and the KEP is open since May 4.

Agree, I also don't want to have multiple parallel discussion. If https://github.com/kubernetes/enhancements/pull/3293 will really tackle Node and zone level topology, then I am fine to close this issue in favor of the KEP PR. But I rather see a KEP that is stuck on the discussion phase and we are not even sure whether the KEP will tackle zone level topology routing.

**Comment by thockin** [comment]
If we will tackle "prefer zone" at all, that KEP will be the place to discuss it, I think.

22 days ago covers the end of the code-freeze period, so everyone's attention was on code, rather than KEPs :)

Adding APIs is intentionally a slow, careful business.  This is not something that we have full understanding of, so we're trying to think it through

**Comment by LAMRobinson** [comment]
Should I close https://github.com/kubernetes/enhancements/pull/3642 in favour of https://github.com/kubernetes/enhancements/pull/3293 then and inflate the two? I asked in my PR earlier, happy to do so as long as folks are okay conflating the requests.

**Comment by nickvanwegen** [comment]
Maybe its already mentioned but I could not find it. 
It seems that the controller does not correct itself either I am hurt by the scenario of CPU imbalance. In my case I run a full spot instance cluster(AWS) so in some occasions I can have weird CPU balance in which the hints are removed from the endpointsslices. Tho after a while +-15min the CAS has corrected this balance again but the hints do not return. 

When I then manually recreate 1 pod(just delete) the hints are recreated again so it look like it only triggers on endpoint changes? not on the external factors

For me it would already be fine if the hints are restored after by CPU balance is restored(or any other factors)

**Comment by ialidzhikov** [comment]
@nickvanwegen please open a new issue to kubernetes/kubernetes. This issue is not umbrella issue for reporting any kind of problems with TopologyAwareHints.
I would appreciate if the maintainers can mark the corresponding comment as off-topic.

**Comment by thockin** [comment]
Did we get a new issue opened?

**Comment by nickvanwegen** [comment]
I opened  a new issue indeed 
https://github.com/kubernetes/kubernetes/issues/114215

As of the status now I am in contact with AWS support as it looks like its an issue just with my cluster but I am not sure. 
in short I cannot replicate it anymore on EKS or on kind

**Comment by thockin** [comment]
Thanks!

**Comment by ialidzhikov** [comment]
@thockin I don't understand why you keep closing this issue?

/reopen

**Comment by thockin** [comment]
Because we have a KEP, which is the vehicle for discussing the policy design, and we have a different issue to discuss the possible bug in heuristic.  Any further comments on this topic should go to one or the other of those.  If we discuss it here, it may not get seen by the people actually doing the work to fix it.

**Comment by ialidzhikov** [comment]
You forwarded me to the https://github.com/kubernetes/enhancements/pull/3293, I posted comments there but nothing happens. You forwarded me to `/dev/null` - someone else's KEP PR that should cover this. You all don't do anything to address the feedbacks/drawbacks, on top you come here and close my issue. I want this issue to be open as umbrella issue listing the drawbacks of TopologyAwareHints for certain scenarios.
If you close this issue one more time, I will report you.

**Comment by thockin** [comment]
@ialidzhikov please hear me.  I am not trying to shut you down or ignore your concerns.  I am actually trying to do the right thing to address your issue.

That KEP (https://github.com/kubernetes/enhancements/pull/3293) is the vehicle to discuss the details of this problem.  Just because it hasn't been updated in the timeframe you really want doesn't mean I've sent you to a /dev/null.  This is a VERY busy project.  Everyone involved is very busy and big changes, especially those that involve APIs, move slowly and deliberately.  We are all tracking or implementing multiple major areas - I myself and tracking 63 KEPs right now.

*IF* (that's a conditional, not a guarantee) we are going to address the concerns you raised it will almost certainly (but I have been wrong before) be either through a better heuristic or through an explicit policy API (the KEP).  Keeping this issue open *in addition to* the KEP makes it HARDER to collect signal - we all now have to monitor 2 distinct places to see comments on this topic.  I promise you it is worse overall for those of us who want to help solve your problem.

So I am going to close this again.  If you still do not understand why, you are free to "report me", whatever that means.  Or you can find me on slack.  Or you can jump on the sig-network channel on slack.  Or you can come to a sig-network meeting.  It's not like we're hiding from conversations :)

**Comment by ialidzhikov** [comment]
@thockin thank you for your reply.

> That KEP (https://github.com/kubernetes/enhancements/pull/3293) is the vehicle to discuss the details of this problem.

I dont' have objections against this. But we cannot expect users facing the same problems described in this issue to find that https://github.com/kubernetes/enhancements/pull/3293 is the right place to discuss this. The problems described in this issue are mostly about TopologyAwareHints (that only supports zone topology-aware routing) while the KEP itself is named "Node-level topology". This issue already contains references to similar issues and to the KEP itself.

> Keeping this issue open in addition to the KEP makes it HARDER to collect signal - we all now have to monitor 2 distinct places to see comments on this topic.

I can understand this. As I tried to describe above we cannot expect people to magically find the KEP and to raise their issues there. The proper place of raising similar issues should be by creating issue to https://issues.k8s.io or for searching for similar issue in https://issues.k8s.io. I believe this issue is useful for people as it mentions how things evolved in the past; what was supported in the past and what is not supported by the new feature.

If you want to close an issue, then please consider closing https://github.com/kubernetes/kubernetes/issues/110714 in favor of this issue. The title of https://github.com/kubernetes/kubernetes/issues/110714 and its initial description does not reflect the real problems that are afterwards discussed in https://github.com/kubernetes/kubernetes/issues/110714. This issue serves as good summary of the discussion in https://github.com/kubernetes/kubernetes/issues/110714.

Let's focus on solving the problems instead of spamming this issue with off-topic comments about where the problems should be raised/discussed. Let me know if I can contribute with something.

**Comment by thockin** [comment]
#110714 is a specific report of a case that is not handled well.  That's useful.

#114215 is a specific report of a bug (which may not be reproducible, but still..).  That's useful.

https://github.com/kubernetes/enhancements/pull/3642 should probably just fold into https://github.com/kubernetes/enhancements/pull/3293

https://github.com/kubernetes/enhancements/pull/3293 defines explicit policy for a node and opens the door to this same idea for a zone, though that expansion is not yet accepted, and may not be the same if if it is accepted.

If you want a discussion of the heuristic problems you cited ("if we know that the whole zonal CPU pool does not model the set of clients...", "Hints do not work at low-endpoint counts...") please open a NEW ISSUE which speaks to those specifically (or re-title #110714).

All discussion of explicit (deterministic) configuration of topology in the API is happening on https://github.com/kubernetes/enhancements/pull/3642.  

> we cannot expect people to magically find the KEP and to raise their issues there

It's not like this issue goes away - it's just not lying around collecting comments that the people working on the problem don't see.

> Let's focus on solving the problems instead of spamming this issue with off-topic comments about where the problems should be raised/discussed

That's rich.  I have a lot of patience, but this is getting pretty old.

**Comment by MikeZappa87** [comment]
@ialidzhikov rob commented on the KEP. I am trying to determine your concern with closing this issue. Do you think if this issue is closed that people won't be able to find the KEP? We are closing, not deleting this issue so users can still find the way. Are specific comments in that kep not being addressed?

**Comment by ialidzhikov** [comment]
> I am trying to determine your concern with closing this issue.

I am trying to determine your concerns why we need to close this issue.
Reasons to keep the issue open:
- It is not clear whether the KEP or the enhencement issue will tackle half of the feature request (zone aware traffic routing/"keep the traffic in the same zone").
- Theoretically, there are no guarantees that the KEP won't be abandonned or won't make it due to some reason.
- Let the usual GitHub workflow work. When there is a PR that implements the feature, let the PR merge close the issue.
- It is the wrong thing sematically. The feature is not implemented but you want to give the impression that there are no issues with the TopologyAwareHints feature. I don't know what to think about it. I start thinking that this issue is "uncomfortable" one to you because it reveals how a powerful feature (ServiceTopology) was dropped in favor of a feature (TopologyAwareHints) that does not offer the same feature set. I know that there were problems with ServiceTopology. I don't want to go into this discussion.
- I don't think there is a rule "If there is a KEP, all feature request issues have to be closed". If there is, feel free to link it.

I can close this issue when the corresponding KEP and enhencement issue are adapted to cover the feature request from this issue. So far, this didn't happen. I believe this consensus is reasonable and you will agree with me. I want to be sure that our feature request/feedback will be accepted and addressed.
I appreciate all of the effort that, you, maintainers put. I am looking forward to see the things moving. Let me if I can help with something.

PS. I will watch the recording from yesterday's SIG Network meeting to see what has been discussed.

**Comment by azelezni** [comment]
The current implementation of Topology Aware Hints is practically unusable, I only spend 1-2 hours on this and I can honestly say I'm not going near this feature ever again.
The docs don't explain much, same for logs, the CPU heuristic is only useful for some use cases, from my own experiments it just looks like this feature is totally random.

Honestly at this point I'd rather just manually configure topology hints but seems like this isn't possible either (or is it?)

**Comment by MikeZappa87** [comment]
> The current implementation of Topology Aware Hints is practically unusable, I only spend 1-2 hours on this and I can honestly say I'm not going near this feature ever again. The docs don't explain much, same for logs, the CPU heuristic is only useful for some use cases, from my own experiments it just looks like this feature is totally random.
> 
> Honestly at this point I'd rather just manually configure topology hints but seems like this isn't possible either (or is it?)

Are you able to help improve the documentation? The current implementation probably solved someone's specific problem and room for improvement always exists if people are willing to implement it. Kubernetes is a community driven project.

**Comment by azelezni** [comment]
> > The current implementation of Topology Aware Hints is practically unusable, I only spend 1-2 hours on this and I can honestly say I'm not going near this feature ever again. The docs don't explain much, same for logs, the CPU heuristic is only useful for some use cases, from my own experiments it just looks like this feature is totally random.
> > Honestly at this point I'd rather just manually configure topology hints but seems like this isn't possible either (or is it?)
> 
> Are you able to help improve the documentation? The current implementation probably solved someone's specific problem and room for improvement always exists if people are willing to implement it. Kubernetes is a community driven project.

Altough the docs can be improved, the main issue remains, the current implementation of Topology Aware Hints is only useful for 1 specific usecase, I go into more detail in #116300

**Comment by thockin** [comment]
https://github.com/kubernetes/enhancements/pull/3765

**Comment by ialidzhikov** [comment]
Hi @thockin @robscott 👋 

Sorry for getting back to you that late. I am now reading the KEP update PR - https://github.com/kubernetes/enhancements/pull/3765/files. In an earlier revision of this PR (https://github.com/robscott/k8s-enhancements/blob/89672c7/keps/sig-network/2433-topology-aware-hints/README.md#samezone-heuristic) it was proposing the `SameZone` heuristic:

> ### SameZone Heuristic
> The simplest of all heuristics, this will simply copy the zone of an endpoint to the hint of the same endpoint. If there are not endpoints available within a zone, that will mean no endpoints will have hints for that zone. As described above, when Kube-Proxy cannot find any endpoints with hints for its zone, it will route traffic ~evenly across all endpoints, regardless of hints.

The `SameZone` heuristic is exactly what we need currently.
I see that after comments from @thockin, this `SameZone` heuristic is removed. The KEP update PR (https://github.com/kubernetes/enhancements/pull/3765/files) rather mentions "A way to express the heuristic you'd like to use for Topology Aware Routing". It is not clear to me how a Kubernetes administrator/operator can easily configure such `SameZone` heuristic. Can you elaborate what I need to do if I want to enable such `SameZone` heuristic behaviour?

**Comment by aojea** [comment]
> Come on, I am (and this issue is) asking for the simplest strategy/heuristic named `SameZone` - if there are endpoints in the same zone, route to those Endpoints, if not - fallback to any available Endpoint. This can be implemented by setting the endpoint's zone as endpoint's hint.

I'm going to follow up on this next cycle, no need to get grumpy ;)

**Comment by ialidzhikov** [comment]
I am no grumpy. I am sorry if it sounds like this. As I shared, I was just trying to understand the KEP update PR (https://github.com/kubernetes/enhancements/pull/3765/files) and what K8s administrator/operator will need to do to enable a `SameZone`-like strategy. I'm raising my questions here, as I really failed to understand the answer for the question.
I would appreciate of someone can outline it with few sentences.

**Comment by aojea** [comment]
> I am no grumpy. I am sorry if it sounds like this. As I shared, I was just trying to understand the KEP update PR (https://github.com/kubernetes/enhancements/pull/3765/files) and what K8s administrator/operator will need to do to enable a `SameZone`-like strategy. I'm raising my questions here, as I really failed to understand the answer for the question.
> I would appreciate of someone can outline it with few sentences.

The thing in Kubernetes is that APIs are generic and kube-proxy is just an implementation detail, not all people use kube-proxy and once we add something to the API people expects to be implemented everywhere, so we can not force people to implement everything and we can not support all the possible ways of doing traffic topology ...

I have to update the KEP to come up with a SameZone strategy, since there is a wide agreement that is a common request , there are still different things that need to be addressed,  to explain how to avoid hotspots or problems overloading endpoints, and how to implement it, if adding using hints or as a kube-proxy specific feature, ...

**Comment by cbensimon** [comment]
> Currently there is no way to achieve topology aware routing (`kubernetes.io/hostname`, `topology.kubernetes.io/zone`, `topology.kubernetes.io/region`) and define deterministic rules like the ones offered from the already deprecated and removed [ServiceTopology](https://kubernetes.io/docs/concepts/services-networking/service-topology/)

Regarding `kubernetes.io/hostname`, isn't `Service.spec.internalTrafficPolicy: Local` doing the job ?

**Comment by pakwin9133** [comment]
Totally agree that some use-cases of ServiceTopology cannot be covered by TopologyAwareHints. That's why most of my K8S cluster are still in v1.20.

**Comment by jonathon2nd** [comment]
It has been a while since I have [checked up on this](https://github.com/kubernetes/enhancements/pull/3293#issuecomment-1284273537). Based off what I have seen [here](https://github.com/kubernetes/kubernetes/issues/116300), and [this was closed](https://github.com/kubernetes/enhancements/pull/3293) in favor for [this](https://github.com/kubernetes/enhancements/pull/3765) (which still does not seem to restore lost functionality), we still don't have a path forward to ensure [high-bandwidth traffic stays on the same host as much a possible](https://github.com/kubernetes/enhancements/issues/2433#issuecomment-1282707666).

Is that right, or have I missed a development on another thread that I have not watched?

**Comment by ialidzhikov** [comment]
Should be partially fixed by https://github.com/kubernetes/kubernetes/pull/121060.

**Comment by ialidzhikov** [comment]
https://github.com/kubernetes/kubernetes/pull/121060#issuecomment-1978144468:

Should be fixed by https://github.com/kubernetes/kubernetes/pull/123487.

**Comment by ialidzhikov** [comment]
/remove-lifecycle stale
as I want to play with the new trafficDistribution field

**Comment by aojea** [comment]
> /remove-lifecycle stale as I want to play with the new trafficDistribution field

please report feedback
cc: @robscott @gaurav1086

**Comment by thockin** [comment]
Rob, Gaurav, can we get an update here or maybe dedup with KEP issue, now that it is more comprehensive?
