### ISSUE TITLE
Can Grafana Dashbord json file be appended to the project?

### ISSUE THREAD

**Issue by xinsir88** [kubernetes/kubernetes#113911]
### What would you like to be added?

Can Grafana Dashbord json file be appended to the project?

### Why is this needed?

Can Grafana Dashbord json file be appended to the project?

**Comment by JingbenShi668** [comment]
There are many grafana panels json on https://grafana.com/grafana/dashboards/?pg=community&plcmt=topnav. If k8s integrates the grafana dashboard, it is not an elegant design. Because many developer has different requirements for the grafana. 
Besides, the  orientation of grafana is an operational  and visual dashboard, and it has loose coupling relation with k8s.

**Comment by neolit123** [comment]
agreed with the above. this repository is for mainly hosting core k8s code.
/close
