### ISSUE TITLE
Manually assigning pods to nodes could lead to cluster instability

### ISSUE THREAD

**Issue by yashp1402** [kubernetes/kubernetes#113907]
### What happened?

kube-controller-manager is **creating pods continuously** after the replication count reaches a certain number (91 in this case).
All the pods being generated is in **OutOfpods** state

NAME                   READY   STATUS        RESTARTS   AGE
test-d5d446578-22gjn   0/1     OutOfpods     0          21h
test-d5d446578-29s2f   0/1     OutOfpods     0          21h
test-d5d446578-2fpvm   0/1     OutOfpods     0          21h
test-d5d446578-2n9qk   0/1     OutOfpods     0          21h
test-d5d446578-2qwmc   0/1     OutOfpods     0          21h

The pod description shows the below message
Status:           Failed
Reason:           OutOfpods
Message:          Pod Node didn't have enough resource: pods, requested: 1, used: 110, capacity: 110

The pods will keep on generating till the limit of 12500(approx) is reached.
Now if the deployment is scaled down to n pod, then there will be n running pods and all the other pods which were generated will remain in the system.

### What did you expect to happen?

After scaling down the deployment to n there should have been n running pod and all the extra pods should have been terminated/deleted.

### How can we reproduce it (as minimally and precisely as possible)?

To reproduce the issue following steps can be taken: -

1) **Create a deployment file** test.yaml. **Initial replica count** is 1.
cat test.yaml 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  labels:
    app: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      \- args:
          \- /bin/bash
          \-c
          \- yes >> /dev/null
        name: test
        image: **Image name is irrelevant**. But for the record, nginx:1.18.0 was used
        imagePullPolicy: IfNotPresent
      nodeName: select any existing worker node

2. **Scale the number of pods** to 91. The number might be different for different setup
kubectl scale deployment test --replicas 91

3. Check the current number of pods
kubectl get pods -A | wc -l; sleep 10;  kubectl get pods -A | wc -l;
171
199

The issue is now reproduced, and the pods will keep on generating.
Now if we scale down to 1 pods then there will be 1 running pod and all the other pods which were in OutOfpods state remain in the system instead of terminating/deleting by itself.

### Kubernetes version

<details>

```console
$ kubectl version

GitVersion:"v1.25.3
GoVersion:"go1.19.2"
Compiler:"gc", Platform:"linux/amd64"

```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here


$ uname -a
# paste output here

```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by aojea** [comment]
this looks like a duplicate of https://github.com/kubernetes/kubernetes/issues/104560

**Comment by neolit123** [comment]
/sig node
for triage

**Comment by SergeyKanzhelev** [comment]
> this looks like a duplicate of #104560

The linked bug was a race between finishing pods and newly scheduled ones. In this case, pods with nginx (running continuously) are scheduled on a node ignoring the max pod setting. 

@yashp1402 what cloud provider (or installation) is being used? If you run kubectl describe node Foo, does it properly reflect the `110` as a max number of pods?

/triage needs-information

**Comment by yashp1402** [comment]
> > this looks like a duplicate of #104560
> 
> The linked bug was a race between finishing pods and newly scheduled ones. In this case, pods with nginx (running continuously) are scheduled on a node ignoring the max pod setting.
> 
> @yashp1402 what cloud provider (or installation) is being used? If you run kubectl describe node Foo, does it properly reflect the `110` as a max number of pods?
> 
> /triage needs-information

Yes the allocatable is 110.
Capacity:
  cpu:                4
  ephemeral-storage:  33514128Ki
  hugepages-1Gi:      0
  hugepages-2Mi:      0
  memory:             4010632Ki
  pods:               110
Allocatable:
  cpu:                3
  ephemeral-storage:  29812878490
  hugepages-1Gi:      0
  hugepages-2Mi:      0
  memory:             3396232Ki
  pods:               110

**Comment by aojea** [comment]
> Message: Pod Node didn't have enough resource: pods, requested: 1, used: 110, capacity: 110

you are running out of Pods, no?

this looks like the expected behavior

**Comment by yashp1402** [comment]
> > Message: Pod Node didn't have enough resource: pods, requested: 1, used: 110, capacity: 110
> 
> you are running out of Pods, no?
> 
> this looks like the expected behavior

The allocatable is set to 110 but this issue pops up when I scale to 91 which is lesser than the hard limit mentioned. This is not expected right?

**Comment by yashp1402** [comment]
> this looks like a duplicate of #104560

Also, according to [this](https://github.com/kubernetes/kubernetes/pull/104577/commits/a2ca66d280df83c5d32e058ef97a3d117a8309ed), the fix has been proposed in kubernetes v1.23.0, but this issue is seen in kubernetes v1.25.3.

**Comment by yashp1402** [comment]
Hi @aojea, I check the fix mentioned #[104577](https://github.com/kubernetes/kubernetes/pull/104577/commits/a2ca66d280df83c5d32e058ef97a3d117a8309ed) but I am unable to see the fixed code in either the master or 1.25 or 1.26. Was the fix reverted back?

**Comment by aojea** [comment]
yeah, I didn't notice that you are using `v1.25.3` , that was fixed in earlier versions, the code may not be there because there can be refactors.

There is only one node in this cluster?

**Comment by yashp1402** [comment]
> yeah, I didn't notice that you are using `v1.25.3` , that was fixed in earlier versions, the code may not be there because there can be refactors.
> 
> There is only one node in this cluster?

Actually there were 1 director, 3 master and 4 worker nodes.

**Comment by aojea** [comment]
and why all the pods get scheduled to the same node?

**Comment by yashp1402** [comment]
Let me check again if they get scheduled on the same node again or are scheduled in a balanced way.

> and why all the pods get scheduled to the same node?

**Comment by yashp1402** [comment]
> and why all the pods get scheduled to the same node?

I checked on this. Actually, I am mentioning **nodeName: worker name** as per our **testing purpose** for a particular worker node. That's why it is getting scheduled to a particular worker node.

**Comment by mac-chaffee** [comment]
I just replicated this bug using a fresh kind cluster, so I can confirm it exists. Replication steps:

```
$ kind --version
kind version 0.17.0

$ kind create cluster
Creating cluster "kind" ...
 ✓ Ensuring node image (kindest/node:v1.25.3)
...

$ kubectl apply -f scale-test.yaml

# In kind, there are less system pods than in yashp1402's cluster, so we have to scale to 102 to hit 111 pods (1 more than the limit)
$ kubectl scale deploy/test --replicas=101

# Observe no issues, wait for all pods to start up

$ kubectl scale deploy/test --replicas=102

# Observe pods are continuously created that immediately error out with "OutOfPods"
```

scale-test.yaml, re-formatted from the original post:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  labels:
    app: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - args:
        - /bin/bash
        - -c
        - yes >> /dev/null
        name: test
        image: nginx:1.18.0
      nodeName: kind-control-plane
```

**Comment by yashp1402** [comment]
Hi @SergeyKanzhelev and @aojea, as this issue is still an existing one, could you please suggest a workaround fix for the same? Thanks!

**Comment by yashp1402** [comment]
> Hi @SergeyKanzhelev and @aojea, as this issue is still an existing one, could you please suggest a workaround fix for the same? Thanks!
Hi,
    Please let me know in case of any updates. Thanks!

**Comment by yashp1402** [comment]
Just one clarification, I am more focused on deletion of those pods which continue to stay in the system once my deployment is scaled down and not on the creation of these pods.

**Comment by aojea** [comment]
> Just one clarification, I am more focused on deletion of those pods which continue to stay in the system once my deployment is scaled down.

but are those pods running or is just information of the API?

**Comment by yashp1402** [comment]
Neither of them, actually these are pods in failed state.

Annotations:      <none>
Status:           Failed
Reason:           OutOfpods
Message:          Pod Node didn't have enough resource: pods, requested: 1, used: 110, capacity: 110

**Comment by lentzi90** [comment]
Hello, I'm a colleague of @yashp1402 and I'll try to clarify this issue a bit.

First of all, what is happening?

When using `nodeName` to schedule pods, the scheduler is effectively bypassed completely, which means that the pods will not become `pending` if the node is out of resources. Instead they are "scheduled" to the node but then the kubelet will put them in OutOfPods state, as stated in the docs:

> If the named node does not have the resources to accommodate the Pod, the Pod will fail and its reason will indicate why, for example OutOfmemory or OutOfcpu.

Ref: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#nodename

Then, since the deployment does not have enough pods running, it will create more. So we get more and more pods that all fail in the same way. This "stops" when we hit the [pod garbage collection threshold](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-garbage-collection) (default 12500 failed pods), since the controller-manager will then start deleting failed pods (but new pods are also created all the time).

So far I think it is quite straight forward. When `nodeName` is used, this is expected to happen since the scheduler is bypassed. I.e. it would be up to the one setting the `nodeName` to determine if it is reasonable or not since the scheduler cannot help.

With that clarified, we are now more focused on the cleaning up of the failed pods.

When the deployment is scaled back down, all the failed pods stay. This was breaking expectations on our side. Is there a way to make the failed pods be cleaned up when scaling down the deployment?

The [documentation mentions](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-garbage-collection) that "For failed Pods, the API objects remain in the cluster's API until a human or controller process explicitly removes them." Is there a controller that can do what we are asking?

**Comment by furkatgofurov7** [comment]
> Is there a controller that can do what we are asking?

Is not it: Pod garbage collector (PodGC) controller which should take care of it based on the doc you linked above? 
```
The Pod garbage collector (PodGC), which is a controller in the control plane, cleans up terminated Pods (with a phase of Succeeded or Failed), when the number of Pods exceeds the configured threshold (determined by terminated-pod-gc-threshold in the kube-controller-manager). 
```

**Comment by lentzi90** [comment]
> Is not it: Pod garbage collector (PodGC) controller which should take care of it based on the doc you linked above?

It only deletes failed pods above the threshold. So when the deployment is scaled down it will still leave 12500 failed pods by default.

**Comment by aojea** [comment]
@alculquicondor do you have any suggestion?

**Comment by alculquicondor** [comment]
I don't have anything to add to what @lentzi90 said.

This is all WAI.

/close

**Comment by alculquicondor** [comment]
Since you seem to be in 1.25, you can just reduce the Pod GC threshold to a number that reflects your needs better.

For example, in the manifest of kube-controller-manager you can add:

```
--terminated-pod-gc-threshold=100
```

**Comment by mac-chaffee** [comment]
> This is all WAI.

Did you see this part (emphasis added)?

> This "stops" when we hit the [pod garbage collection threshold](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-garbage-collection) (default 12500 failed pods), since the controller-manager will then start deleting failed pods **(but new pods are also created all the time)**

This keeps kubelet, controller-manager, kube-apiserver pegged at 100% CPU.

I also noticed another issue: These infinitely-spawning pods also seem to mess with preemption. If you delete/restart any pod in kube-system like coredns, it will kill some of the running pods with the message "Preempted by kube-system/coredns-b886cf54-67vhr on node kind-control-plane". But because new pods are being created so quickly, the coredns pods never win the "race" to be scheduled and get stuck in "Pending" forever.

I don't think tricking Kubernetes into entering an infinite busy loop that causes cluster instability should be considered "working as intended" :)

**Comment by alculquicondor** [comment]
> This keeps kubelet, controller-manager, kube-apiserver pegged at 100% CPU.

Bypassing kube-scheduler is not something you should be doing. The cluster is just trying to reconcile under a user-induced problem.

**Comment by mac-chaffee** [comment]
Could the confusion be due to the fact that the PoC intentionally spawns more pods than can fit on a node? Because the issue could also be caused by just being the unlucky person who spawns the 111th pod on a node. 

If a node is already running 110 pods and a user decides to create a new Deployment with 1 replica and a `nodeName`, that user (who is not doing anything abnormal) would be unknowingly sending Kubernetes into a death spiral.

Using the `nodeName` field in Pods is not super rare (since [the docs don't [discourage]](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#nodename) its use): https://sourcegraph.com/search?q=context:global+file:deployment.yaml+nodeName:&patternType=standard&case=yes&sm=1&groupBy=repo

Another issue is that these infinitely-spawning pods bypass ResourceQuota restrictions, which poses a threat to [multi-tenant Kubernetes clusters](https://kubernetes.io/docs/concepts/security/multi-tenancy/#quotas). I actually run a multi-tenant cluster that frequently hits the max-pods-per-node limit during normal operation. I set ResourceQuotas to stop users from creating too many resources, but due to this bug, there is nothing I can do to prevent a user from using `nodeName` and causing cluster instability. I'd have to use some third-party tool like Gatekeeper to ban the use of `nodeName` all together.

**Comment by SergeyKanzhelev** [comment]
@mimowo any thoughts on this as it may relate to the KEP: https://github.com/kubernetes/enhancements/issues/3329 (not directly, but one of those scenarios)

**Comment by alculquicondor** [comment]
/reopen
/retitle Manually assigning pods to nodes could lead to cluster instability

The fact that setting `nodeName` is effectively not restricted predates my time in kubernetes. @thockin @liggitt, do you know of any rationale for this?

@sftim should we put a big warning in here? https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#nodename

Re https://github.com/kubernetes/enhancements/issues/3329
Admission errors are currently not annotated with a condition https://github.com/kubernetes/enhancements/tree/master/keps/sig-apps/3329-retriable-and-non-retriable-failures#admission-failures
I think the note still stands: Is this a user error? It could also be that the cluster administrator installed a buggy scheduler. Should we just add a condition along the lines of `AdmissionDenied` and let the user write a rule for it. But this deserves its own KEP, kind of similar to kubernetes/enhancements#3815 by @kannon92.

**Comment by sftim** [comment]
We don't have field level access control.

However, we could do some of:
- rate limit namespaces on how often they can create Pods
- rate limit namespaces on how often they can create Pods with a specified `nodeName`
- rate limit namespaces on how often they can create [arbitrary objects that the cluster admin has specified]
- teach controllers to back off making Pods on behalf of an object that contains a Pod template, when those are failing
- provide an out-of-tree admission webhook that restricts setting `nodeName` to specific control plane principals, possibly just the scheduler
- nudge ValidatingAdmissionPolicy towards making the same controls possible without a webhook
- somehow restrict setting `nodeName` on Pods other than by binding a previously unbound Pod
  - either with a ValidatingAdmissionPolicy that we then recommend cluster admins adopt
  - or with an admission webhook
  - or with an AdmissionRateLimit (that I just thought up) - obviously, this needs its own KEP
 - restrict setting `nodeName`, binding or otherwise, so that you can do it **iff** the scheduler agrees you can
    - in other words, still allow clients to create pre-bound Pods, but have an admission-time check on whether to
      allow that. Design the webhook (or whatever) to circuit-break and just reject Pods outright if the load from these
      checks is a problem, so as to avoid a DoS-the-kube scheduler risk.

The admission webhook is the easiest to deliver and lets us prototype things out-of-tree, which I'm a fan of doing. We should handle special cases for [mirror pods](https://kubernetes.io/docs/reference/glossary/?all=true#term-mirror-pod) and for non-default schedulers.

We should sketch what approach / approaches we like before we decide what to document. Potentially, these might mean we change https://kubernetes.io/docs/concepts/security/security-checklist/ too (if we think so, let's tag this with SIG Security).

**Comment by sftim** [comment]
KEP for fine-grained authz is https://github.com/kubernetes/enhancements/issues/3737

**Comment by tzneal** [comment]
@yashp1402 As a workaround for this sort of use case, instead of setting nodeName, why not set a nodeSelector and let kube-scheduler handle scheduling those pods?  You still get the ability to specify which pods land on which nodes, but if they don't fit for whatever reason, they would just remain pending instead of being bound and failing.

**Comment by liggitt** [comment]
> The fact that setting `nodeName` is effectively not restricted predates my time in kubernetes. @thockin @liggitt, do you know of any rationale for this?

Targeting a specific node and bypassing the scheduler is not exactly *wrong*, it just risks the node not being able to run the workload and getting immediately failed.

I agree that users in normal multi-node clusters that expect to have their workloads scheduled should not set nodeName directly. If you want to target a specific node *and* wait until the node has resources, a nodeSelector or node affinity that selects only the desired node is the way to accomplish that.

**Comment by thockin** [comment]
historical context:

Once upon a time we didn't have RBAC or authz in general.  We didn't exactly know what status was best at, and so we set up patterns based on best-intentions.  Some of those were imperfect.

It was important that one be able to write a "custom scheduler" and `nodeName` was how that would work. 

I am pretty sure we would design it (and other things) differently today, but we have some compat to keep. :(

**Comment by sftim** [comment]
Thinking about https://github.com/kubernetes/kubernetes/issues/113907#issuecomment-1428869640: could we already make that ValidatingAdmissionPolicy, one that denies creating bound Pods? We could then apply that policy to all namespaces except `kube-system` (ie: document how you would apply it).

**Comment by alculquicondor** [comment]
As long as it's opt-in, we could.

**Comment by smarterclayton** [comment]
OpenShift did this fairly early on (access to set that field requires create/update on the pod/binding subresource) and it was satisfactory for the vast majority of use cases (since openshift set an early distinction that kube admin was the only user who could do all things).  But as @alculquicondor notes, we could safely make this opt in and recommend it in hardening guides.  It's roughly the same as having the ability to write endpoint records and specify any IP address (which openshift limited via a policy check on another virtual resource), or setting status fields.

I would personally prefer the vpolicy admission check against pod/binding (since we already have a subresource for binding pods that is supposed to be granted to schedulers) if we were to provide an optional field.  I 100% intentionally made pod/bind a subresource in order to a) separate the ACL and b) be able to use it as a virtual admission check in dfc19185f5de9325bb2c3cbfc2ffc3ea8f9490f0 / #5054 but alas, i didn't write it down in the PR.
