### ISSUE TITLE
[Failing Test] Thumbprint related connection_tests in vclib vsphere provider fails with golang master

### ISSUE THREAD

**Issue by Rajalakshmi-Girish** [kubernetes/kubernetes#114089]
### Which jobs are failing?

https://prow.ppc64le-cloud.org/job-history/s3/ppc64le-prow-logs/logs/postsubmit-master-golang-kubernetes-unit-test-ppc64le

### Which tests are failing?

Below tests in vendor/k8s.io/legacy-cloud-providers/vsphere/vclib:
```
TestWithVerificationWithWrongThumbprint
TestWithVerificationWithoutCaCertOrThumbprint
TestWithValidThumbprint
```

### Since when has it been failing?

After the merge of change https://go-review.googlesource.com/c/go/+/449336
From Commit `f64c2a2ce5`

### Anything else we need to know?

```
=== FAIL: vendor/k8s.io/legacy-cloud-providers/vsphere/vclib TestWithVerificationWithWrongThumbprint (0.49s)
2022/11/18 19:48:51 http: TLS handshake error from 127.0.0.1:46286: remote error: tls: bad certificate
E1118 19:48:51.699156   80023 connection.go:197] Failed to create new client. err: Post "https://127.0.0.1:35525/sdk": tls: failed to verify certificate: x509: certificate signed by unknown authority
    connection_test.go:117: Expected wrong thumbprint error, got 'Post "https://127.0.0.1:35525/sdk": tls: failed to verify certificate: x509: certificate signed by unknown authority'

=== FAIL: vendor/k8s.io/legacy-cloud-providers/vsphere/vclib TestWithVerificationWithoutCaCertOrThumbprint (0.09s)
2022/11/18 19:48:51 http: TLS handshake error from 127.0.0.1:40864: remote error: tls: bad certificate
E1118 19:48:51.792358   80023 connection.go:197] Failed to create new client. err: Post "https://127.0.0.1:39707/sdk": tls: failed to verify certificate: x509: certificate signed by unknown authority
    connection_test.go:192: Expected to receive a wrapped x509.UnknownAuthorityError, got: 'Post "https://127.0.0.1:39707/sdk": tls: failed to verify certificate: x509: certificate signed by unknown authority' (&url.Error{Op:"Post", URL:"https://127.0.0.1:39707/sdk", Err:(*tls.CertificateVerificationError)(0xc0007760f0)})

=== FAIL: vendor/k8s.io/legacy-cloud-providers/vsphere/vclib TestWithValidThumbprint (0.12s)
2022/11/18 19:48:51 http: TLS handshake error from 127.0.0.1:44894: remote error: tls: bad certificate
E1118 19:48:51.908549   80023 connection.go:197] Failed to create new client. err: Post "https://127.0.0.1:44745/sdk": tls: failed to verify certificate: x509: certificate signed by unknown authority
    connection_test.go:208: Never saw a request, maybe TLS connection could not be established?
```

### Relevant SIG(s)

/sig testing

**Comment by Karthik-K-N** [comment]
After debugging I see that the [vim25..NewClient](https://github.com/Karthik-K-N/kubernetes/blob/1d4ba69ae40644c5109f55eaf280ac7c8fb63336/staging/src/k8s.io/legacy-cloud-providers/vsphere/vclib/connection.go#L195) creation being always failed in all cases with below error
```
E0109 14:58:06.785230    5787 connection.go:197] Failed to create new client. err: Post "https://127.0.0.1:52638/sdk": x509: “localhost” certificate is not standards compliant
2023/01/09 14:58:06 http: TLS handshake error from 127.0.0.1:52639: remote error: tls: bad certificate
    connection_test.go:213: Never saw a request, maybe TLS connection could not be established?
--- FAIL: TestWithValidThumbprint (0.02s)
```

@BenTheElder Any pointers on how to tackle this.

**Comment by Karthik-K-N** [comment]
> After debugging I see that the [vim25..NewClient](https://github.com/Karthik-K-N/kubernetes/blob/1d4ba69ae40644c5109f55eaf280ac7c8fb63336/staging/src/k8s.io/legacy-cloud-providers/vsphere/vclib/connection.go#L195) creation being always failed in all cases with below error
> 
> ```
> E0109 14:58:06.785230    5787 connection.go:197] Failed to create new client. err: Post "https://127.0.0.1:52638/sdk": x509: “localhost” certificate is not standards compliant
> 2023/01/09 14:58:06 http: TLS handshake error from 127.0.0.1:52639: remote error: tls: bad certificate
>     connection_test.go:213: Never saw a request, maybe TLS connection could not be established?
> --- FAIL: TestWithValidThumbprint (0.02s)
> ```
> 
> @BenTheElder Any pointers on how to tackle this.

I tried running test on MacOS so I might have hit the above error but CI has similar failures

**Comment by Karthik-K-N** [comment]
On further debugging I found that this [particular change](https://github.com/golang/go/blob/master/src/crypto/tls/handshake_client.go#L879) from the [PR](https://github.com/golang/go/commit/f64c2a2ce5dc859315047184e310879dcf747d53#diff-ab85793b9432fb5bea1142f2582e0c8bba9bec59a90913f95baf35560fdb9d7d) is causing the failures.

We always hit `x509: certificate signed by unknown authority` error [here](https://github.com/golang/go/blob/master/src/crypto/tls/handshake_client.go#L876) irrespective of the above PR.

[Client creation](https://github.com/Karthik-K-N/kubernetes/blob/1b5ef42681c8fa68b426bd77f865034cc5a3f859/staging/src/k8s.io/legacy-cloud-providers/vsphere/vclib/connection_test.go#L96) error in test.

1. Without above go PR

```
 _, err := connection.NewClient(context.Background())
 if err != nil {
       fmt.Println("error", err)
}

//Output
error EOF
```

2. After merging above go PR

```
 _, err := connection.NewClient(context.Background())
 if err != nil {
       fmt.Println("error", err)
}

//Output
error Post "https://127.0.0.1:45009/sdk": tls: failed to verify certificate: x509: certificate signed by unknown authority
```

On high level I think that there might be a change in error type handling that is causing the test failure. Because previously the error type used to be  `x509.UnknownAuthorityError` but now its `tls.CertificateVerificationError`.

I suspected on [this](https://github.com/vmware/govmomi/blob/939e78dc19bf32a5fef077079e9263e058ea5ee3/vim25/soap/client.go#L372-L390) (but not sure) but here also it would have handled [here](https://github.com/vmware/govmomi/blob/939e78dc19bf32a5fef077079e9263e058ea5ee3/vim25/soap/client.go#L385-L386).

**Comment by Karthik-K-N** [comment]
@MadhavJivrajani could you please take a look and help in reaching out to relevant member to help fix this issue. Thanks

**Comment by Rajalakshmi-Girish** [comment]
This failure isnt seen these days!
@Karthik-K-N ^^
