### ISSUE TITLE
Endpoints doesn't reconcile in some cases from instance that is shutting down

### ISSUE THREAD

**Issue by hakuna-matatah** [kubernetes/kubernetes#114049]
### What happened?

Hi,

At the time of shutdown process of an control-plane instance,   apiserver attemps to remove it's `master Lease-object` from etcd, and it may not find the lease-object in storage  if the leases already expire by the time APIServer attempts to delete it from storage [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/controlplane/reconcilers/lease.go#L123) , in such cases it will error out [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/controlplane/controller.go#L214) with following error depending on the k8s version it's on
```
controller.go:184] StorageError: key not found, Code: 1, Key: /registry/masterleases//172.18.100.37, 
```
because of this line [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/controlplane/reconcilers/lease.go#L316) errors out to delete from storage 

And endpoint won't be reconciled during the shutdown process from behind the Kubernetes service backend. Due to this some clients may still attempt connecting to old instance for some period of time as kube-proxy won't update the endpoints until new controller reconciler loop from another instances kicks off and removes the old endpoint.

Example of  `connection refused` errors that clients experience on client applications because of the above issue 
 ```
no more retries error: unable to recognize \""/tmp/manifest.yaml\"": Get \""https://10.100.0.1:443/api?timeout=32s\"": dial tcp 10.100.0.1:443: connect: connection refused"",""object"":{""apiVersion"":""v1"",""count"":1,""eventTime"":null,""firstTimestamp"":""2022-11-09T22:25:21Z"",""involvedObject"":
```

### What did you expect to happen?

Given there can be potential cases where our shutdown can take longer or don't end gracefully, our shutdown process can be more resilient and tolerate errors from storage and continue with reconciling anyway IIUC,
so I propose a fix  [here]( https://github.com/kubernetes/kubernetes/blob/release-1.20/pkg/controlplane/reconcilers/lease.go#L299) , basically swallow/log this error when you have issues deleting a lease-object from storage and continue with reconciling to update endpoint object.

^^^ what this gives us is, incases when there was no expiry of `master-leaseobject` from `etcd`,  it will be a no-op and continue to work the way it is i.e remove it from storage successfully and then reconcile. But in cases of `master-lease object` from etcd  expires, it will fail to find the key in etcd like in this case but because of this potential fix(swallowing the error and logging it), it will continue to reconcile the endpoints and this code [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/controlplane/reconcilers/lease.go#L204)  will have updated master endpoints from etcd anyway at the time of reconciliation and help keep endpoints behind K8s service up-to-date during the shutdown process and doesn't have to wait until next periodic reconciler/new instance controller reconciler loop kicks in.

If you like above proposed solution, I can submit a PR for this. Please let me know. Thank you.

### How can we reproduce it (as minimally and precisely as possible)?

1) Let clients continue to make new connections every sec to instance you are about to terminate
2)  Delay the shutdown process until `master-lease` object in etcd expires for a given instance
2) Let APIServer continue with shutdown down process so it fails with the error 
```
controller.go:184] StorageError: key not found, Code: 1, Key: /registry/masterleases//172.18.100.37, 
```
4) Check error in client logs saying ```connection refused``` because it was trying to connect to old instance (tcp dump may help here to help look at it clearly that it was making a  connection to IP/endpoint of old instance and failing because `connection refused` error at network layer.

### Kubernetes version

<details>
1.20 and 1.23 I have seen this issue happening
```console
$ kubectl version
```
Client Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.15-eks-6d3986b", GitCommit:"d4be14f563712c4e1964fe8a4171ca353b6e7e1a", GitTreeState:"clean", BuildDate:"2022-07-20T22:07:15Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
```
```
Client Version: version.Info{Major:"1", Minor:"23+", GitVersion:"v1.23.12-eks-1558457", GitCommit:"5e45ab4a299ac2f7c64cbc46f285b535ee32bdb8", GitTreeState:"clean", BuildDate:"2022-10-06T21:29:14Z", GoVersion:"go1.17.13", Compiler:"gc", Platform:"linux/amd64"}
```

But i think this may happen on any version as this part of the code hasn't been updated on master IIUC

</details>


### Cloud provider

<details>
AWS but can likely happen anywhere
</details>



### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by hakuna-matatah** [comment]
/assign @wojtek-t @lavalamp  

Thoughts ?

**Comment by aojea** [comment]
the apiserver shutdown process went through a lot of fixes in v1.25 and I remember some issues with the endpoints reconciler logic was fixed, we should check first if this issue is present in 1.25 or 1.26

**Comment by hakuna-matatah** [comment]
> he apiserver shutdown process went through a lot of fixes in v1.25 and I remember some issues with the endpoints reconciler logic was fixed, we should check first if this issue is present in 1.25 or 1.26

Thanks for your quick response.
The code links that I pointed out are from Master branch and the sections relating to issue i was specifically talking about haven't been touched since many versions. i have also checked  the commit history of the files controller.go and lease.go to see if there were any associated PR/Issues and and changelog for 1.25, seems like there hasn't been anything around this particular issue.

**Comment by aojea** [comment]
Yeah, let me explain myself better, the apiserver shutdown had some issues that may be related, not to the exact problem that you are pointing out but maybe to the root cause of why that happens, per example:

https://github.com/kubernetes/kubernetes/pull/108033
https://github.com/kubernetes/kubernetes/pull/110026/
https://github.com/kubernetes/kubernetes/commit/33dca56ba8226b287bc6aeb4a6f6e90675c00320

some of the pre-shutdown hooks were not executed or hanged or the apiserver listening socket was closed and the endpoint reconciler could not even remove the endpoint because it failed to connect to the apiserver or the stop() function was not executed.

The apiserver shutdown behavior is super complex as you can see in the following diagram, that means we should be supercarefull with any change we do to avoid any undesired consequence, we may fix something and break other thing without noticing during multiple releases, as you are describing in this very subtle bug.

https://github.com/kubernetes/kubernetes/blob/57eb5d631ccd615cd161b6da36afc759af004b93/staging/src/k8s.io/apiserver/pkg/server/genericapiserver_graceful_termination_test.go#L123-L172

Coming back to your issue, since is important to understand why the lease times out, let's try to understand the path it follows and see how can we improve this:

The lease is updated by `RunKubernetesService` that runs each `c.EndpointInterval` 

https://github.com/kubernetes/kubernetes/blob/57eb5d631ccd615cd161b6da36afc759af004b93/pkg/controlplane/controller.go#L241-L278

The endpoint updates start running by this async runner

https://github.com/kubernetes/kubernetes/blob/57eb5d631ccd615cd161b6da36afc759af004b93/pkg/controlplane/controller.go#L184

and is stopped by 

https://github.com/kubernetes/kubernetes/blob/57eb5d631ccd615cd161b6da36afc759af004b93/pkg/controlplane/controller.go#L203


The stop is triggered by one preshutdown hook (see diagram above for see when exactly happens during the shutdown)

https://github.com/kubernetes/kubernetes/blob/57eb5d631ccd615cd161b6da36afc759af004b93/pkg/controlplane/controller.go#L142

And the time that happens since the lease has been updated to we execute the RemoveEndpoints() method will depend on this code path if my read is correctly.

https://github.com/kubernetes/kubernetes/blob/57eb5d631ccd615cd161b6da36afc759af004b93/pkg/controlplane/controller.go#L203-L217

The other part of the equation is the lease ttl configured

https://github.com/kubernetes/kubernetes/blob/57eb5d631ccd615cd161b6da36afc759af004b93/pkg/controlplane/instance.go#L263-L268

The lease ttl is 15 seconds by default `pkg/controlplane/instance.go:   DefaultEndpointReconcilerTTL = 15 * time.Second`

The endpoint reconciler interval is 10 seconds ` DefaultEndpointReconcilerInterval = 10 * time.Second`

Just curiosity, are you using those values and hitting these issues? IIUIC in the worse case that the stop() starts just at the end of the reconcilerInterval there are still 5 seconds that the lease valid. 

If we modify the logic in `RemoveEndpoints()` we have also to modify the bootstrap code accordingly , we can't just swallow the error

https://github.com/kubernetes/kubernetes/blob/57eb5d631ccd615cd161b6da36afc759af004b93/pkg/controlplane/controller.go#L154

**Comment by hakuna-matatah** [comment]
Thank you for the detailed information.

>Just curiosity, are you using those values and hitting these issues? IIUIC in the worse case that the stop() starts just at the end of the reconcilerInterval there are still 5 seconds that the lease valid.

Yes,  we are using the defaults that  triggered this issue that I was talking about i.e; `pre-shutdown` hook triggered and failed to find the lease object in etcd. I understand logically based on the code that we will have 5seconds of lease lifetime in worst case like you are saying but somehow based on error logs  `StorageError: key not found, Code: 1, Key: /registry/masterleases//172.18.100.37` it says it couldn't find `master-leaseobject` in storage, so only plausible explanation that makes sense is that, `master lease-object` expiry unless I'm missing something less. 
Unfortunately we don't have logs at higher verbosity level around shutdown process and/or when each time our `master-lease object` gets renewed nor logs in etcd layer around CRUD operations around leases, that would have been made our debugging much easier to timeline the events.


Only important details I see in our logs in relation to this issue is as follows:

```
  | I1109 22:24:49.112366      12 controller.go:181] Shutting down kubernetes service endpoint reconciler
E1109 22:24:49.115425 12 controller.go:184] StorageError: key not found, Code: 1, Key: /registry/masterleases//172.18.100.37, ResourceVersion: 0,
............
............
.........
2022-11-09T22:24:54.000Z
I1109 22:24:54.275056 12 secure_serving.go:246] Stopped listening on [::]:443
```

The 5secs time diff from the first log line  (which is triggered as part of preHook() step ) `shutting down k8s service endpoint reconciler` and `stopped listening` (happens when listener is stopped which comes after `aftershtdowndelayduration` is completed)  - IIUC that is accounted for our `--shutdown-delay-duration` i.e; 5secs. I believe IIUC this `5secs` shouldn't account for the missing `5secs` in worst case as this runs in parallel to preShutdown() hook.


But regardless of this I see that there is a room for making it resilient is what I was trying to convey here i.e; from  logical standpoint I feel like we should not block APIServer instance from removing it's endpoint from k8s service on any issues relating to [storage failures](https://github.com/kubernetes/kubernetes/blob/master/pkg/controlplane/reconcilers/lease.go#L123) like not finding key, unable to connect to etcd due to some network glitch etc.  Do you agree on that ?

**Comment by aojea** [comment]
> I feel like we should not block APIServer instance from removing it's endpoint from k8s service on any issues relating to [storage failures](https://github.com/kubernetes/kubernetes/blob/master/pkg/controlplane/reconcilers/lease.go#L123) like not finding key, unable to connect to etcd due to some network glitch etc. Do you agree on that ?

🤔  the others apiserver will recycle the endpoints too, and 5 seconds to expire the lease meanwhile you clean the endpoints sounds too much... I don't know I don't like the idea of having an apiserver with network problems rewriting the endpoints... 

Maybe I'm very cautious with these things, I would not be in favor of doing changes like this without a test reproducing the problem or showing the improvements ...

I will defer to others, I expressed my opinion but it will be good to hear others

> /assign @wojtek-t @lavalamp
> 
> Thoughts ?

**Comment by hakuna-matatah** [comment]
> Thank you for the detailed information.
> 
> > Just curiosity, are you using those values and hitting these issues? IIUIC in the worse case that the stop() starts just at the end of the reconcilerInterval there are still 5 seconds that the lease valid.
> 
> Yes, we are using the defaults that triggered this issue that I was talking about i.e; `pre-shutdown` hook triggered and failed to find the lease object in etcd. I understand logically based on the code that we will have 5seconds of lease lifetime in worst case like you are saying but somehow based on error logs `StorageError: key not found, Code: 1, Key: /registry/masterleases//172.18.100.37` it says it couldn't find `master-leaseobject` in storage, so only plausible explanation that makes sense is that, `master lease-object` expiry unless I'm missing something less. Unfortunately we don't have logs at higher verbosity level around shutdown process and/or when each time our `master-lease object` gets renewed nor logs in etcd layer around CRUD operations around leases, that would have been made our debugging much easier to timeline the events.
> 
> Only important details I see in our logs in relation to this issue is as follows:
> 
> ```
>   | I1109 22:24:49.112366      12 controller.go:181] Shutting down kubernetes service endpoint reconciler
> E1109 22:24:49.115425 12 controller.go:184] StorageError: key not found, Code: 1, Key: /registry/masterleases//172.18.100.37, ResourceVersion: 0,
> ............
> ............
> .........
> 2022-11-09T22:24:54.000Z
> I1109 22:24:54.275056 12 secure_serving.go:246] Stopped listening on [::]:443
> ```
> 
> The 5secs time diff from the first log line (which is triggered as part of preHook() step ) `shutting down k8s service endpoint reconciler` and `stopped listening` (happens when listener is stopped which comes after `aftershtdowndelayduration` is completed) - IIUC that is accounted for our `--shutdown-delay-duration` i.e; 5secs. IOW this `5secs` shouldn't account for the missing `5secs` lifetime of `master lease object` in worst case as it runs in parallel to preShutdown() hook.
> 
> But regardless of this I see that there is a room for making it resilient is what I was trying to convey here i.e; from logical standpoint I feel like we should not block APIServer instance from removing it's endpoint from k8s service on any issues relating to [storage failures](https://github.com/kubernetes/kubernetes/blob/master/pkg/controlplane/reconcilers/lease.go#L123) like not finding key, unable to connect to etcd due to some network glitch etc. Do you agree on that ?


To add to my above comment,

Actually apiserver doesn't shutdown gracefully today i.e; endpoint doesn't remove  itself from the k8s service since this [PR](https://github.com/kubernetes/kubernetes/pull/113686/files) got merged (i.e; IIUC since 1.23)  until another instance reconciler resets the endpoint objects, so the impact of `connection refused` for clients that I mentioned in the overview would be there for around `15 seconds` + amount of time `kube-proxy` on each node takes to update it's iptables.

As this [code](https://github.com/kubernetes/kubernetes/blob/d1c0171aed848900daa07212370c991c19c318b1/pkg/controlplane/reconcilers/lease.go#L123) already appends another slash `/` before the `ip-address` at the time of attempting to delete the `lease-object` , `s.baseKey+"/"+ip` - basically leading to extra slash just before `ip address` and thus resulting in not able to find the `masterlease object` i.e; `/registry/masterleases//172.18.100.37` throwing an error like - `controller.go:189] Unable to remove endpoints from kubernetes service: StorageError: key not found, Code: 1, Key: /registry/masterleases//172.18.100.37`, 
even though actual lease-object doesn't expire and exist in etcd i.e; `/registry/masterleases/172.18.100.37`  and ends up failing the apiserver to remove it's endpoint from k8s service before terminating.



So one fix would be to remove this additional slash here in this [line](https://github.com/kubernetes/kubernetes/blob/master/pkg/controlplane/reconcilers/lease.go#L123) 

Another fix would be to make APIServer immune/resilient ( that i have been talking above in this issue) to these kind of issues that get introduced time to time unknowingly and continue removing endpoint irrespective of storage failures.


@aojea @lavalamp @wojtek-t ^^^

**Comment by aojea** [comment]
> As this [code](https://github.com/kubernetes/kubernetes/blob/d1c0171aed848900daa07212370c991c19c318b1/pkg/controlplane/reconcilers/lease.go#L123) already appends another slash / before the ip-address at the time of attempting to delete the lease-object , s.baseKey+"/"+ip - basically leading to extra slash just before ip address and thus resulting in not able to find the masterlease object i.e; /registry/masterleases//172.18.100.37 throwing an error like - controller.go:189] Unable to remove endpoints from kubernetes service: StorageError: key not found, Code: 1, Key: /registry/masterleases//172.18.100.37,
even though actual lease-object doesn't expire and exist in etcd i.e; /registry/masterleases/172.18.100.37 and ends up failing the apiserver to remove it's endpoint from k8s service before terminating.

This is a serious bug

> Another fix would be to make APIServer immune/resilient ( that i have been talking above in this issue) to these kind of issues that get introduced time to time unknowingly and continue removing endpoint independent of storage failures.

The fact that a serious bug like that can go unnoticed reinforces my position against ignoring errors

https://github.com/kubernetes/kubernetes/issues/114049#issuecomment-1325771034

**Comment by wojtek-t** [comment]
Thanks @aojea for effectively debugging this case. Yes - it's exactly this PR that broke that.
@tallclair @lavalamp @liggitt - FYI


To explain exactly what is happening:
- for creating/updating the masterlease we're using they key computed here:
 https://github.com/kubernetes/kubernetes/blob/master/pkg/controlplane/reconcilers/lease.go#L96
- but for deletion we're using https://github.com/kubernetes/kubernetes/blob/master/pkg/controlplane/reconcilers/lease.go#L123

Given that `baseKey` is initialized as '/masterleases/`, we're ending up (ip is example below) with:
- `/masterleases/127.1.1.1` in the first case
- `/masterleases//127.1.1.1` in the second case

It wasn't the problem previously, because before that change was doing:
```
key = path.Join(s.pathPrefix, key)
```

which was normalizing it to "<prefix>/masterleases/127.1.1.1"
After that change, the path.Join was removed (to address the CVE) and it effectively broke this flow.


The fix of this particular bug is fairly trivial - I opened https://github.com/kubernetes/kubernetes/pull/114109
[we should add some test for it to avoid future regressions, but I wanted to stop the bleeing asap]

But eventually we should also think how to avoid reimplementing the pieces of storage interface and unify this part with the rest of the codebase...

**Comment by wojtek-t** [comment]
/kind regression

@liggitt @lavalamp @tallclair - FYI ^^

**Comment by aojea** [comment]
> Thanks @aojea for effectively debugging this case. Yes - it's exactly this PR that broke that.

actually all the credit must go to @hakuna-matatah , great report and he was the one identifying the PR and the double slash problem

**Comment by lavalamp** [comment]
Thanks everyone! 🥂
