### ISSUE TITLE
Optimize volumebinding by moving PV list calls to PreFilter

### ISSUE THREAD

**Issue by ahg-g** [kubernetes/kubernetes#114075]
### What would you like to be added?

The call to list all PVs that belong to a storage class is expensive to do per node at scale. This can be moved to PreFilter and so done once for all nodes.

https://github.com/kubernetes/kubernetes/blob/57eb5d631ccd615cd161b6da36afc759af004b93/pkg/scheduler/framework/plugins/volumebinding/binder.go#L828

### Why is this needed?

Optimize performance.

@cofyc please take a look, would you be able to help apply this optimization?

**Comment by kidddddddddddddddddddddd** [comment]
I can try to help with this one. But feel free to reassign to someone else.
/assign

**Comment by kidddddddddddddddddddddd** [comment]
I'm currently thinking of the following implementation:

1. Add a map in stateData to save the result of ListPVs
```
type stateData struct {
    //key for storageClass name, value for corresponding pvs
	allPvs map[string][]*v1.PersistentVolume
}
```
2. In `PreFilter`, call to list all PVs and save the result
```
allPVs := Somefunction 
state.Write(stateKey, &stateData{allPvs: allPVs, boundClaims: boundClaims, claimsToBind: claimsToBind, podVolumesByNode: make(map[string]*PodVolumes)})
```
3. In `Filter`, pass the result to `pl.Binder.FindPodVolumes` 
```
podVolumes, reasons, err := pl.Binder.FindPodVolumes(pod, state.boundClaims, state.claimsToBind, state.allPvs ,node)
```

To pass the result of list all PVs from the binder to the plugin, We can

- Add a return parameter for `GetPodVolumes` since it is called in `PreFilter`
```
type SchedulerVolumeBinder interface {
	GetPodVolumes(pod *v1.Pod) (boundClaims, unboundClaimsDelayBinding, unboundClaimsImmediate []*v1.PersistentVolumeClaim, allPvs map[string][]*v1.PersistentVolume, err error)
}
```
- Or Create another method to just list all the pvs for the storage classes of a pod's pvcs
```
type SchedulerVolumeBinder interface {
    ListPodVolumes(pod *v1.Pod) (allPvs map[string][]*v1.PersistentVolume)
}
```

I don't know if this is a feasible implementation to you @ahg-g :). Do you have some suggestions?

**Comment by aimuz** [comment]
Can I use Informer?

**Comment by ahg-g** [comment]
> I don't know if this is a feasible implementation to you @ahg-g :). Do you have some suggestions?

It makes sense. Returning the map as part of GetPodVolumes sounds good to me.
