### ISSUE TITLE
staging repos v0.26.0-rc.0 tag content doesn't match k/k v1.26.0-rc.0

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#114192]
While opening https://github.com/kubernetes/autoscaler/pull/5336 to update to 1.26.0 rc.0 libraries, a compile error surfaced because published staging repo v0.26.0-rc.0 tag content doesn't match k/k v1.26.0-rc.0

these two files should be identical, but are not:
* https://github.com/kubernetes/apimachinery/blob/v0.26.0-rc.0/pkg/apis/meta/v1/validation/validation.go
* https://github.com/kubernetes/kubernetes/blob/v1.26.0-rc.0/staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/validation/validation.go

https://github.com/kubernetes/autoscaler/actions/runs/3577027159 is failing with `undefined: validation.LabelSelectorValidationOptions` because the published apimachinery tag isn't right

_Originally posted by @liggitt in https://github.com/kubernetes/autoscaler/issues/5336#issuecomment-1331188208_

**Comment by liggitt** [comment]
cc @dims @sttts

**Comment by liggitt** [comment]
cc @kubernetes/release-managers for visibility

**Comment by liggitt** [comment]
cc @nikhita

**Comment by xmudrii** [comment]
Should be fixed with #114193
/triage accepted
/assign

**Comment by nikhita** [comment]
Writing it here for the record: why only the commits in https://github.com/kubernetes/kubernetes/pull/113699 were dropped while other commits were correct in the `release-1.26` branch of the apimachinery repo when the directory was configured to code-generator:

For new branches, the bot assumes that the new branch `release-1.26` is branched off of master. The way it works for new branches:
1. Does a git filter-branch on the apimachinery repo and creates a new branch `filter-branch` with just the commits in the specified dir. In this case, it was code-generator.
2. Looks at HEAD of the `filter-branch` and gets the k/k [commit](https://github.com/kubernetes/publishing-bot/blob/0642432fea4ca05655bbe3edef46aed6280d511b/artifacts/scripts/util.sh#L222) that maps to it. In this case, it was https://github.com/kubernetes/kubernetes/commit/3f1511c8e9a64cf60821036aa1fc3ec9d58a2931.
3. Get the [commit](https://github.com/kubernetes/publishing-bot/blob/0642432fea4ca05655bbe3edef46aed6280d511b/artifacts/scripts/util.sh#L231) on apimachinery’s master branch that maps to the above k/k commit i.e. https://github.com/kubernetes/apimachinery/commit/b6b5c3fcffafc66aa74cd422dbe11dcd7330df84 and create the `release-1.26`. There are a few more things that happen before the release branch is created, but this is the gist.

Essentially:
HEAD of filter-branch => it’s k/k commit => corresponding master branch commit => create release-1.26 at this commit

The commit in step 2 (https://github.com/kubernetes/kubernetes/commit/3f1511c8e9a64cf60821036aa1fc3ec9d58a2931) included changes to both apimachinery and code-generator. If it didn't include apimachinery changes, step 3 would have given an error and we would have been able to catch the problem early.

Additionally, commits in https://github.com/kubernetes/kubernetes/pull/113699 were dropped because they didn't include code-generator changes and were merged _after_ https://github.com/kubernetes/kubernetes/commit/3f1511c8e9a64cf60821036aa1fc3ec9d58a2931. The dropped commits then led to the incorrect `v0.26.0-rc.0` tag.

**Comment by dims** [comment]
thanks a ton @nikhita !
