### ISSUE TITLE
kubectl message says "<object> deleted" before it actually deletes.

### ISSUE THREAD

**Issue by martinhitachi** [kubernetes/kubernetes#114348]
> What is actually going on under the covers? It appears that the command immediately prints "&lt;object&gt; deleted" and then hangs, but actually it is waiting. It seems like the messaging is incorrect. It should say "deleting" and if --wait is the default it should only print "deleted" when the object is actually deleted.
> 
> The way it works right now it seems like kubectl deletes things and then hangs for no reason, and it doesn't give any indication that a state change has actually happened when the command finally terminates. (However ctrl-c and inspecting with kubectl get shows what is going on.) It's also a little surprising that the whole operation is async and ctrl-c doesn't stop it.)

_Originally posted by @lukeschlather in https://github.com/kubernetes/kubernetes/issues/42594#issuecomment-955090666_

I've also had this issue where I `ctrl-c` before the `--wait` finished and even though `namespace mynamespace deleted` was printed, the namespace wasn't actually deleted, and was actually stuck in the `Terminating` state.

Either the message "&lt;object&gt; deleted" should be changed to "&lt;object&gt; deleting" or it should not print until the `--wait` is finished.

**Comment by rezasoumi** [comment]
Thanks! 
Could you help me with where to start?

**Comment by rezasoumi** [comment]
[@martinhitachi](https://github.com/martinhitachi) could you explain a scenario with cli which lead to the result you said?

**Comment by rezasoumi** [comment]
because I checked some points of code related to this topic such as [Deleting namespace ...](https://github.com/kubernetes/kubernetes/blob/70dde8d746a07392d945dde32dd7e3b12ca9a043/test/e2e/network/scale/localrun/ingress_scale.go#L152) which log this before deleting and I wonder how you get this result.
and actually somehow I am confused because in [namespace.go](https://github.com/kubernetes/kubernetes/blob/70dde8d746a07392d945dde32dd7e3b12ca9a043/staging/src/k8s.io/client-go/kubernetes/typed/core/v1/namespace.go#L47) Delete function of namespace exists without any async related (I traced code). and besides for delete function of node that is [onDelete](https://github.com/kubernetes/kubernetes/blob/70dde8d746a07392d945dde32dd7e3b12ca9a043/pkg/controller/nodeipam/ipam/controller_legacyprovider.go#L232) delete function of builtin.go has occurred which return and log nothing (I cannot see Deleting or deleted ... )
I would appreciate any help clearing up the confusion about this issue.

**Comment by lukeschlather** [comment]
Probably here?

https://github.com/kubernetes/kubectl/tree/master/pkg/cmd/delete

**Comment by martinhitachi** [comment]
My kubectl version might be old by now:
```
$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.0", GitCommit:"a866cbe2e5bbaa01cfd5e969aa3e033f3282a8a2", GitTreeState:"clean", BuildDate:"2022-08-23T17:44:59Z", GoVersion:"go1.19", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"23+", GitVersion:"v1.23.14-eks-ffeb93d", GitCommit:"96e7d52c98a32f2b296ca7f19dc9346cf79915ba", GitTreeState:"clean", BuildDate:"2022-11-29T18:43:31Z", GoVersion:"go1.17.13", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.25) and server (1.23) exceeds the supported minor version skew of +/-1
```

But when I just try an ordinary namespace deletion you can tell it is waiting for the request to finish even though "namespace <namespace name> deleted" has been printed.

```
$ kubectl delete namespace tenant-0
namespace "tenant-0" deleted
```

**Comment by martinhitachi** [comment]
Not sure where it is in the code, I'll try some greping

**Comment by martinhitachi** [comment]
Although
https://github.com/kubernetes/kubectl/blob/c230e1b22140e5767a57860f8d1ca3669859565d/pkg/cmd/delete/delete.go#L414-L441
Handles the actual printing, I don't think it has the bug, since the bug is with the order of the printing and the actual deletion.

**Comment by rezasoumi** [comment]
Thanks for references, I think this is good to print "Deleting ..." at first and then after process completion print "namespace mynamespace deleted". The first part is ok, but the second part is challenging because before [printObj](https://github.com/kubernetes/kubectl/blob/a08b3656dfd6d19710c71e420003a524ea5e8562/pkg/cmd/delete/delete.go#L406-L408) there is [delete process](https://github.com/kubernetes/kubectl/blob/a08b3656dfd6d19710c71e420003a524ea5e8562/pkg/cmd/delete/delete.go#L398-L401) and it has not any "go" keyword to delete the process async way. I mean maybe it is not a good way to change DeleteWithOption method !

**Comment by ardaguclu** [comment]
Thanks for opening this issue.

I understand the inconvenience in here but it works how it was designed. All the process is async and `<object> deleted` message is actually an optimistic attempt rather than assuring that deletion is completed.

I'm closing this because it is working as expected.

/close
