### ISSUE TITLE
Bind specific cpu number for pod

### ISSUE THREAD

**Issue by willzhang** [kubernetes/kubernetes#114380]
### What would you like to be added?

Bind specific cpu number for pod。

I have 2 cpu ,with 0~39 cores.
```
root@ubuntu:~# lscpu | grep NUMA
NUMA node(s):                    2
NUMA node0 CPU(s):               0-9,20-29
NUMA node1 CPU(s):               10-19,30-39
```

i want BIND some specific number  cpu to pods, eg:
```
pod-A cpu 3-4
pod-B cpu 5
```

### Why is this needed?

There have high performance workloads like NFV in my environments.Do not want any movement of the application process

**Comment by infinitydon** [comment]
Hi, another use-case for this is that in some systems, the NICs are ONLY located in a specific NUMA and there is need to allocate CPU cores from that NUMA for performance sensitive NFV applications.

I don't think the current CPU allocation implementation for Kubernetes supports this.

@willzhang - Were you able to find a way to do this?

**Comment by ffromani** [comment]
Hi, usign cpumanager static policy + device plugins (for NICs) + topology manager single NUMA node policy enables full alignment of compute resources, so a workload (e.g. a performance sensitive NFV./CNF application) can get CPUs from the same NUMA node on which the device is attached to. I'd be interested in learning if there are scenarios on which this is not enough.
In general, selecting specific CPUs is something the platform steered away from.

**Comment by infinitydon** [comment]
@ffromani - The use-case where `single-numa-node` will not be sufficient is when all the NICs are located in a specific NUMA e.g NUMA0, with this a situation can arise whereby the **_available_** CPU cores that will be allocated to a NFV CNF may not be in NUMA0 especially when all the NUMA0 CPU cores has been allocated to other PODs that doesn't need strict alignment.

**Comment by infinitydon** [comment]
Another way around this could be to find a way to reserve specific CPU cores that the kubelet _should not use at all_ (this would have worked simply by using something like **_isolcpus_** but from my checks the kubelet does not honor the **_isolcpus_** settings) and leave the actual CPU cores selection the NFV CNFs themselves i.e. no need to use the **_resources.request_** and **_resources.limit_** for the CPUs allocation

**Comment by ffromani** [comment]
> @ffromani - The use-case where `single-numa-node` will not be sufficient is when all the NICs are located in a specific NUMA e.g NUMA0, with this a situation can arise whereby the **_available_** CPU cores that will be allocated to a NFV CNF may not be in NUMA0 especially when all the NUMA0 CPU cores has been allocated to other PODs that doesn't need strict alignment.

Thanks for elaborating. This seems to me a form of (perhaps at node-level) scheduling/eviction issue, and that very well happen even if we allow to select specific cores, if the workloads are admitted with inverted priority: first the non-latency-sensitive workload, then the latency sensitive workload. The former should be evicted (and re-admitted) to make room for the latter in order to get the most optimal resource allocation.

IOW, this scenario seems to be identifiable with the tools the platform already provides - the latency-sensitive pod can already express its stricter requirements with the existing APIs.  I can't say atm if and how get this behavior from the platform, though.



> Another way around this could be to find a way to reserve specific CPU cores that the kubelet _should not use at all_ (this would have worked simply by using something like **_isolcpus_** but from my checks the kubelet does not honor the **_isolcpus_** settings) and leave the actual CPU cores selection the NFV CNFs themselves i.e. no need to use the **_resources.request_** and **_resources.limit_** for the CPUs allocation

AFAIR this is not doable indeed atm - it would require another form of resource partitioning which the platform is generally trying to steer away from, and it goes against the goal to maximize the pod density per node.
