### ISSUE TITLE
A huge amount of pending pods will cause the kube-scheduler memory to rise quickly

### ISSUE THREAD

**Issue by fjding** [kubernetes/kubernetes#114362]
### What happened?

A large number of pods cannot be scheduled due to insufficient resources, will cause the kube-scheduler memory to rise quickly.
pending pod count: 10W
node count: 10
memory overview：
![image](https://user-images.githubusercontent.com/21192363/206407233-e45473b6-e494-4c25-b994-3ecbb91dd79a.png)

gorouine overview：
![image](https://user-images.githubusercontent.com/21192363/206412121-12ce2612-5533-41e9-82bb-942ad5af6ef7.png)

schedule qps
![image](https://user-images.githubusercontent.com/21192363/206412700-61bcfbc9-91ae-4447-9381-9883bd6a0294.png)

goroutine pprof (top 2)
![image](https://user-images.githubusercontent.com/21192363/206411710-c7ecdf28-98f8-4395-814f-1c2b4381bc6e.png)
heap pprof（top3）
![image](https://user-images.githubusercontent.com/21192363/206411945-b64d2641-0be5-4d8e-9b76-166596f479a5.png)

So it looks like the memory rise quickly because of the increased number of goroutines,
the relative code as follow
![image](https://user-images.githubusercontent.com/21192363/206414398-bca7ce39-0aa9-4952-b6fb-c58ff2ec632f.png)

### What did you expect to happen?

Will the community fix it？

### How can we reproduce it (as minimally and precisely as possible)?

no

### Anything else we need to know?

no

### Kubernetes version

kubernetes version: v1.20.10

### Cloud provider

no

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>
no
</details>

### Container runtime (CRI) and version (if applicable)

<details>
no
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
no
</details>

**Comment by ShreyasKali01** [comment]
There are a few potential solutions to this problem:

Increase the amount of memory allocated to the kube-scheduler. By giving the kube-scheduler more memory, it will be able to maintain a record of more pending pods without running out of memory.

Reduce the number of pending pods. This can be done by increasing the number of available nodes in the cluster, or by decreasing the number of pods being submitted to the cluster.

Optimize the scheduling process. The kube-scheduler uses various algorithms and strategies to determine the best node for each pod, and these can be tuned to improve performance and reduce the number of pending pods.

Use a more efficient scheduling algorithm. The kube-scheduler currently uses the DefaultBinder algorithm to match pods to nodes, but there are other algorithms available that may be better suited to your specific workload and cluster configuration.

Use a horizontal pod autoscaler (HPA) to automatically scale the number of replicas for your workloads based on demand. This can help to ensure that there are always enough available nodes to schedule pending pods, reducing the need for the kube-scheduler to maintain a large number of pending pods in memory.

Overall, the best solution will depend on your specific situation and the requirements of your workloads. It may be necessary to try a combination of these solutions in order to effectively manage the kube-scheduler memory usage and reduce the number of pending pods.

**Comment by fjding** [comment]
Thanks for your suggestion.
In my case, no matter how much memory you give, it will be exhausted eventually. I think the unlimited creation of goroutines in the recordToSink function, it will cause the kube-scheduler unstable when there are a large number of pending pods.

**Comment by fjding** [comment]
Thanks for your suggestion.
In my case, no matter how much memory you give, it will be exhausted eventually. I think the unlimited creation of goroutines in the recordToSink function, it will cause the kube-scheduler unstable when there are a large number of pending pods.

**Comment by kerthcet** [comment]
Thanks @fjding for reporting this, just gave it a first glance, general comments here:
1) There maybe optimizations to reduce the memory usage when we have pods pending, I have to dig into the code. Your profiling files are really great!
2) No matter how we improve the performance, 10w pending pods are 10w pending pods, they will always consume the memory, so I think there's no approach to maintaining big plenty of pods with less memory usage, but yes as less as better.
3) Or we have something like fuse protection which will stop scheduling when we came across this scenario. But maybe it's not fair for high priority pods.

**Comment by kerthcet** [comment]
By the way, have you tried with v1.23, 1.20 is out of support now, we patched with several PRs to improve the performance of scheduler, have no idea whether it helps in this situation or not.

**Comment by fjding** [comment]
> By the way, have you tried with v1.23, 1.20 is out of support now, we patched with several PRs to improve the performance of scheduler, have no idea whether it helps in this situation or not.

ok, thanks
