### ISSUE TITLE
Job back-offs get reset on controller-manager restart

### ISSUE THREAD

**Issue by sathyanarays** [kubernetes/kubernetes#114650]
### What happened?

Exponential back-off kicks in when a pod fails. The back-off logic is offloaded to the in-memory `workqueue` data structure. On controller-manager restarts, the information in the `workqueue` is lost. So, the back-off information is lost and the back-off gets calculated as if the job is a new one.

### What did you expect to happen?

The pods to be created with correct back-offs even when the controller-manager restarts

### How can we reproduce it (as minimally and precisely as possible)?

1. Start a job that always fail
2. Let the job fail till we see a visible back-off
3. Stop the controller-manager container
4. New pod gets scheduled immediately after controller-manager restart irrespective of the previously computed back-off

### Kubernetes version

In master as of commit d2504c94a0116d4432a8a73fc17a0ec8d003d37b
Also present in latest release.

### Cloud provider

NA

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by sathyanarays** [comment]
related to #114391  and #114651

**Comment by alculquicondor** [comment]
There is a more immediate problem for me:
All job syncs are tied to the workqueue delays. We should just be delaying pod creation, but not job status updates. This is specially important when the job hits the `backoffLimit`. We would wait X seconds before declaring the Job as failed, even though it could be done immediately.

I think the solution is somewhat simple: keep track of the elapsed time within the sync, instead of the workqueue and restrict pod creation specifically. The time should be measured based on the Pod status, to be resilient to restarts. But even if we can't do that immediately, just tracking in memory shouldn't be too bad to start.

**Comment by alculquicondor** [comment]
cc @mimowo

**Comment by sathyanarays** [comment]
@alculquicondor , @mimowo , please provide early feedback on these changes if they are in the right direction!

#114684
