### ISSUE TITLE
Use site style sheet for docs/api-reference

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#11468]
#11357 should merge soon.  It will add these file:
  - docs/api-reference/definitions.html
  - docs/api-reference/operations.html
They have inline style which does not match the rest of kubernetes.io.

Soon, those files will be copied to gh-pages by whatever process @krousey comes up with.

Something ought to override the inline styles in those docs and use the site's style sheet.

@thockin @RichieEscarez

**Comment by thockin** [comment]
Is this done now?

**Comment by erictune** [comment]
no

**Comment by RichieEscarez** [comment]
I delivered 11771 yesterday to fix the broken link and also changed some of the colors to match. Fixing the CSS is a larger effort so i stopped at fixing the color to resolve the broken links.

These files get generated from the swagger output and end up as .html files (with the embedded CSS).  We need to either improve that process or provide CSS that overrides to match our site. 

To use the operations.html and definitions.html files as they are, we need to (1) delete the embedded CSS, header, and body tags (so we are left with just the enclosed html tagging from within <body>...</body> , (2) include or create new a CSS file to inject our site styling (and ensure the tables, etc render), (3) automate stripping the *.html files.

We might also be able to specify/add a class="" or id="" into the containing <body>..</body> tags of the *.html api files, and then use an includes or javascript to include only that content (rather than deleting all the unneeded tagging in those files? Just not sure yet if an include of only a div class is supported in github pages (otherwise use javascript).

**Comment by RichieEscarez** [comment]
@caesarxuchao

**Comment by caesarxuchao** [comment]
I can do (3) in gh-pages/_tool/ using golang, but I feel we should eventually use javascript or other web technologies to solve this problem. I'm not the right person to write the javascript though.

**Comment by bgrant0607** [comment]
We're going to totally change how API docs are presented. Closing.
