### ISSUE TITLE
move descheduler functions into kube-scheduler

### ISSUE THREAD

**Issue by snowplayfire** [kubernetes/kubernetes#114841]
### What would you like to be added?

Descheduler no longer acts as a separate component, but combines with kube-scheduler. That is,  move descheduler functions into kube-scheduler.

### Why is this needed?

Descheduler and kube-scheduler should have consistent perspective about cluster nodes to make consistent decisions.

**Comment by kerthcet** [comment]
Descheduler does not play a role of scheduling evicted pods, but still rely on default kube-scheduler. And it's not a fully necessary component comparing to kube scheduler, keep it out of kubernetes is reasonable I think, if not, there're so many components can be plugged into k/k, like NFD etc.. I'm not fairly familiar with descheduler, cc @damemi as maintainer for advices.

Kubernetes is so complex right now, I think keep it as simple as possible is something we're chasing but still very difficult...

**Comment by damemi** [comment]
+1 what @kerthcet said

While it is true that the descheduler could provide an easier UX and some more functionality that worked out of the box if it were more closely coupled with the default scheduler, it would also add constraints. The effort to do so would also be contrary to the direction the kube-scheduler has been growing, with more emphasis on the scheduling framework and modular customizability over a centralized monolithic component.

We do recognize the importance of the descheduler remaining in-sync with the scheduler, which is why we started projects like [cleaning up scheduler dependencies on k/k](https://github.com/kubernetes/kubernetes/issues/89930), which has since stalled out. The goal with this was to achieve a similar goal through an opposite approach: descheduler could depend on the same functionality as the scheduler if that functionality was externalized.

Still, the descheduler and scheduler sharing the same internal view of the cluster state could benefit the descheduler by allowing it to lean on what the scheduler already knows and make smarter, more efficient eviction decisions. However, the scheduler doesn't get any functional benefit from being tied to the descheduler. It only adds maintenance burden.

I think there is a lot of work that could be done to make the descheduler easier to use by default (and most of that is probably on the descheduler side rather than kube-scheduler), but I'm not sure building that into kube-scheduler is the right solution. I'm open to hear what others' opinions are.

**Comment by damemi** [comment]
cc @ingvagabund @knelasevero @seanmalloy @a7i
