### ISSUE TITLE
A potential issue in the node_affinity 

### ISSUE THREAD

**Issue by bingzheliu** [kubernetes/kubernetes#115047]
### What happened?

While I was reading the [`node_affinity.go` ](https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/framework/plugins/nodeaffinity/node_affinity.go)plugin source code in the scheduler, I found there may potentially exist a logic issue in the PreFilter(). 

As from the [document](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#node-affinity) (as well as from [line 125-129](https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/framework/plugins/nodeaffinity/node_affinity.go#L125) in node_affinity.go), the terms are ORed. However, I found that in [line 132-134](https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/framework/plugins/nodeaffinity/node_affinity.go#L132), if one term found no matching node, it will return and report `UnschedulableAndUnresolvable`, which makes the logic become ANDed.  Following is the code in line 132-134:
```
if len(termNodeNames) == 0 {
	return nil, framework.NewStatus(framework.UnschedulableAndUnresolvable, errReasonConflict)
}
```

Is this an actual logic issue or if I understand something wrong? 

### What did you expect to happen?

This logic of this code block (line 132-134) may be moved outside this for-loop, and test if the`len(nodeNames)` is 0 instead. 

### Kubernetes version

The master branch

**Comment by dariodsa** [comment]
You can have multiple affinity rules, and for each rule you calculate which nodes are following that rule (eq. ``termNodeNames``). You actually do intersection of all ``termNodeNames`` from each termNodeNames and for those you then calculate a score on which you will base your scheduling. So ``termNodeNames`` has  to be in a for loop. The reason for line from 132-134 is simple, because you are using intersection and if one of your set is empty, you can stop the calculation and said that result is empty set. 
But I have to agree that word union is misleading ( because of the ANDing). But again, maybe I am wrong also.

**Comment by lastland** [comment]
A quote from the document pasted by OP:
> If you specify multiple terms in `nodeSelectorTerm`s associated with `nodeAffinity` types, then the Pod can be scheduled onto a node if one of the specified terms can be satisfied (terms are ORed).

So it shouldn't be intersections.

And unions are the dual of intersections; a correct implementation of them should mean OR.
