### ISSUE TITLE
"swap tests are failing"

### ISSUE THREAD

**Issue by pacoxu** [kubernetes/kubernetes#115372]
### Which jobs are failing?

- https://testgrid.k8s.io/sig-node-presubmits#pr-kubelet-gce-e2e-swap-fedora-serial failed ❌
- https://testgrid.k8s.io/sig-node-presubmits#pr-kubelet-gce-e2e-swap-fedora Success Now. ✅
- https://testgrid.k8s.io/sig-node-presubmits#pr-kubelet-gce-e2e-swap-ubuntu-serial passed ❌

### Which tests are failing?

> W0127 11:55:39.475] I0127 11:55:39.474853    6928 ssh.go:120] Running the command ssh, with args: [-o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o CheckHostIP=no -o StrictHostKeyChecking=no -o ServerAliveInterval=30 -o LogLevel=ERROR -i /workspace/.ssh/google_compute_engine core@34.168.76.60 -- sudo sh -c 'systemctl list-units  --type=service  --state=running | grep -e containerd -e crio']
> W0127 11:55:55.060] E0127 11:55:55.060236    6928 ssh.go:123] failed to run SSH command: out: ssh: connect to host 34.168.76.60 port 22: Connection refused
> W0127 11:56:15.293] , err: exit status 255

### Since when has it been failing?

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-node-swap-fedora/1618940000303321088

### Testgrid link

 https://testgrid.k8s.io/sig-node-presubmits#pr-kubelet-gce-e2e-swap-fedora

### Relevant SIG(s)

/sig node 
/area test
/kind failing-test

**Comment by SergeyKanzhelev** [comment]
/cc @mmiranda96 

@mmiranda96 was planning to bring it on today's SIG Node meeting.

@pacoxu do you remember the reasoning for choosing fedora as one of OS-es for swap tests?

**Comment by haircommander** [comment]
(for the fedora side)

**Comment by mmiranda96** [comment]
Some of my previous attempts to fix this:
- https://github.com/kubernetes/test-infra/pull/26483
- https://github.com/kubernetes/test-infra/pull/27406

**Comment by haircommander** [comment]
I opened https://github.com/kubernetes/test-infra/pull/28611 to hopefully fix the cri-o pieces

**Comment by pacoxu** [comment]
> I opened [kubernetes/test-infra#28611](https://github.com/kubernetes/test-infra/pull/28611) to hopefully fix the cri-o pieces

This was merged just hours ago and I tried to retest on my PR.
- It still failed: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/105271/pull-kubernetes-node-swap-fedora/1620998325715079168/

I am not sure if the https://github.com/kubernetes/test-infra/pull/28611 took effect on my re-run.

**Comment by pacoxu** [comment]
https://testgrid.k8s.io/sig-node-kubelet#kubelet-gce-e2e-swap-fedora-serial
and
https://testgrid.k8s.io/sig-node-kubelet#kubelet-gce-e2e-swap-fedora

are failing as well when I check the sig-node testgrid today.

**Comment by pacoxu** [comment]
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/105271/pull-kubernetes-node-swap-fedora/1628961473218744320/

> I0224 03:48:26.143273    3250 manager.go:210] Machine: {Timestamp:2023-02-24 03:48:26.142945008 +0000 UTC m=+0.880338934 CPUVendorID:GenuineIntel NumCores:1 NumPhysicalCores:1 NumSockets:1 CpuFrequency:2200160 MemoryCapacity:7798296576 SwapCapacity:0 MemoryByType:map[] 


> E0224 04:15:28.374140   16001 kubelet.go:1463] "Failed to start ContainerManager" err="invalid Node Allocatable configuration. Resource \"swap\" has an allocatable of {{268435456 0} {<nil>}  BinarySI}, capacity of {{-268435456 0} {<nil>}  BinarySI}"


https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/105271/pull-kubernetes-node-swap-fedora-serial/1628961473306824704/artifacts/n1-standard-2-fedora-coreos-37-20230205-3-0-gcp-x86-64-6819286d/kubelet.log

> 
>       {
>         "contents": "[Unit]\nDescription=Enable swap on CoreOS.\nBefore=crio-install.service\nConditionFirstBoot=no\n\n[Service]\nType=oneshot\nExecStart=/bin/sh -c \"sudo dd if=/dev/zero of=/var/swapfile count=1024 bs=1MiB && sudo chmod 600 /var/swapfile && sudo mkswap /var/swapfile && sudo swapon /var/swapfile && free -h\"\n[Install]\n\nWantedBy=multi-user.target\n",
>         "enabled": true,
>         "name": "swap-enable.service"
>       },

swap-enable.service log cannot be found in kernel log. I suspect, the swap is not enabled as expected.

**Comment by SergeyKanzhelev** [comment]
/retitle "swap tests are failing"

https://testgrid.k8s.io/sig-node-presubmits#pr-kubelet-gce-e2e-swap-fedora-serial
https://testgrid.k8s.io/sig-node-presubmits#pr-kubelet-gce-e2e-swap-ubuntu-serial

**Comment by SergeyKanzhelev** [comment]
now just two tests are failing. Maybe test related, maybe swap affects it.

xref: https://github.com/kubernetes/enhancements/issues/2400

**Comment by pacoxu** [comment]
New enhancement issue in https://github.com/kubernetes/enhancements/issues/4128
- Not sure if we need to close 2400 then.

**Comment by haircommander** [comment]
it seems the serial tests for swap are failing the same way they are without swap, and that the swap e2e tests are passing. Thus, I don't think the failures are due to swap but due to instability in the serial tests (for cri-o). However, containerd serial swap are failing in a way containerd serial are not. We could leave this open or we could investigate separately.

**Comment by mmiranda96** [comment]
@pacoxu @iholder101 are you currently working on swap? Could you take a look at this failures? Thanks!

**Comment by iholder101** [comment]
> @pacoxu @iholder101 are you currently working on swap? Could you take a look at this failures? Thanks!

Hey @mmiranda96, thanks for the FYI!

Yes, indeed I'm still working on swap and aware of the problem. The cause is that the current way of checking whether a feature gate is enabled is flawed, and fixed here: https://github.com/kubernetes/kubernetes/pull/120139. Reviews are appreciated!

**Comment by kannon92** [comment]
Are these issues also related to this one?

https://testgrid.k8s.io/sig-node-kubelet#kubelet-gce-e2e-swap-fedora-serial

**Comment by kannon92** [comment]
I think we are looking really good on these tests.

We have three outstanding issues for swap AFAIK:

Issue 1: https://github.com/kubernetes/kubernetes/issues/121702
- OOMKiller seems to be less happy with swap and the jobs are not evicted.  

Issue 2: Summary stats for MajorPageFaults are way more flaky with swap enabled. Second try at PR to fix: https://github.com/kubernetes/kubernetes/pull/121700

Issue 3: https://github.com/kubernetes/kubernetes/issues/120646 @ndixita has mentioned that she is working on fixing this one.  This issue is unrelated to Swap actually so we can ignore it for swap.  Issue 1 and 2 should be fixed as part of swap.

**Comment by kannon92** [comment]
#12702 and #121700 are resolved.  Indirectly, we no longer see the failure for #120646.  This is because we skip OOM tests for the current configuration of Swap.  

I created a ticket to add tests for LimitedSwap and OOM.  The default is set to UnlimitedSwap which makes it difficult to test OOM at the moment.

- https://testgrid.k8s.io/sig-node-kubelet#kubelet-gce-e2e-swap-fedora
- https://testgrid.k8s.io/sig-node-kubelet#kubelet-gce-e2e-swap-fedora-serial
- https://testgrid.k8s.io/sig-node-kubelet#kubelet-gce-e2e-swap-ubuntu
- https://testgrid.k8s.io/sig-node-kubelet#kubelet-gce-e2e-swap-ubuntu-serial

They are flaking but the two serial jobs seem to obey the same failures and the other failures are documented elsewhere.  

I think we can close this issue.
