### ISSUE TITLE
Warn when new clusters are turned up using the `.local` DNS TLD

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#115300]
### What would you like to be added?

xref #82381

.local has meaning that doesn't really apply to Kubernetes.  We never should have used it.  We may not be able to change the default (maybe not now, maybe not ever), but we can make it more obvious to people.

1) Update docs to make it clear that `.cluster.local` is the default, but something like `.cluster.lan` is probably better.
2) Update examples to use a different name (2a: decide on a better name; 2b: use it)
3) Update tools which implement that default to issue warnings (non-fatal) 

### Why is this needed?

.local has meaning that doesn't really apply to Kubernetes.  We never should have used it.

**Comment by aojea** [comment]
> Update docs to make it clear that .cluster.local is the default,

is only default in kubeadm AFAIK

**Comment by thockin** [comment]
Maybe so, but we can fix all the examples and stuff, too.

**Comment by justinsb** [comment]
I think this is a can of worms.  Do we know that .lan won't become a valid TLD?  e.g. https://www.rfc-editor.org/errata/eid4529

Perhaps RFC 6762 is due for an update?  I think there's wiggle room in between `.local names are link-local` and the somewhat contradictory `Any DNS query for a name ending with ".local." MUST be sent to the mDNS IPv4 link-local multicast address`

Or let's stand up a globally delegated DNS tree, so that everyone can have a real domain name for whatever they want (though arguably, that already exists with the free dynamic-dns services).

My concern is that this particular warning would not be actionable (though I'm open to seeing what people come up with), and would just cause confusion until people learned to ignore it.

**Comment by thockin** [comment]
Want to write an RFC?

**Comment by thockin** [comment]
Or buy a TLD? :)

**Comment by justinsb** [comment]
Do we actually need a TLD?  We could just buy a normal domain and have free subdomains; everyone gets a `<ecdsa-pubkey>.ecdsa.cloud` for example.

So that's too easy.  Writing an RFC though, that could be fun...

**Comment by thockin** [comment]
We could buy .k8s and just let anyone anywhere use it.
