### ISSUE TITLE
Feature request: Upgrade buckets in statefulsets

### ISSUE THREAD

**Issue by hsiddulugari** [kubernetes/kubernetes#115436]
What is the ask?
If we were to assume all replicas of a Statefulset can be bucketed into a fixed number of 'upgrade buckets', can Statefulset controller support rolling update based on these 'upgrade buckets'

What is the benefit?
* Shorter upgrade times
* Constant time upgrade regardless of number of replicas

How does this work?
If we have hundreds or thousands of replicas in a sts, a simple rolling update can take a very long time.
If we were to bucket all replicas into a fixed number of buckets where the application deals with building redundancy across buckets vs replicas, we believe the upgrades can be shortened a lot and also can be made constant time.

**Comment by pwschuurman** [comment]
> If we were to bucket all replicas into a fixed number of buckets where the application deals with building redundancy across buckets vs replicas, we believe the upgrades can be shortened a lot and also can be made constant time.

It sounds like your use case involves mapping buckets to failure domains, where an entire bucket can be disrupted at once without impacting the health of the application. This enables StatefulSet updates to scale at O(# failure domains) rather than O(# replicas). I think that https://github.com/kubernetes/kubernetes/issues/114010 can solve this use case.
