### ISSUE TITLE
Publish tagged version of kubernetes/release used for making a kubernetes release

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#115486]
Request on behalf of downstream team(s) like EKS who would love to know 
- there are tags in kubernetes/release repository, Does the release team use the tag when making a release? (or they just use what's in `master`)
- If yes, Do we publish which version of k/release is used in a specific release of kubernetes (similar to how we generate the golang version etc and we make it easy to look up [dependencies](https://github.com/kubernetes/kubernetes/blob/master/build/dependencies.yaml)) 
- If no, is there a reliable way to self-service and determine which version we should be using for a specific k8s version?

Can you please consider making this easier please? (teams are guessing at the moment and are not really sure if their guess is right)

/sig release

**Comment by markapruett** [comment]
Thanks @dims! I'd add a third bullet, 
* If no, is there a reliable way to self-service and determine which version we should be using for a specific k8s version?

For example, our team is currently trying to determine which version to use for 1.26 as we prepare to roll that out.

**Comment by markapruett** [comment]
Can anyone shed some light on the questions above?

**Comment by dims** [comment]
@saschagrunert @cpanato @xmudrii @kubernetes/sig-release 

folks, any ideas?

**Comment by BenTheElder** [comment]
For some things like https://github.com/kubernetes/release/tree/master/images there are individual versions that are versioned into a release as image dependencies for building and you'll have to track back those version tags individually. The versions used are in https://github.com/kubernetes/kubernetes/blob/master/build/dependencies.yaml

Otherwise as a general rule you should be able to build a kubernetes release just from `make release` in this repo, which will generate binaries, tarballs, images etc the same as we'd build for an official release, the other automation etc in k/release is specific to our processes around publishing, our secure build hosts, etc and shouldn't actually be relevant for cutting a downstream release?

Debian/RPM packaging is also in k/release, but I don't think that's what we're talking about here.

**Comment by saschagrunert** [comment]
Ugh, I missed that issue, sorry about that!

> * there are tags in kubernetes/release repository, Does the release team use the tag when making a release? (or they just use what's in `master`)

For cutting release we always use `master`. The tags in k/release are more intended to be used by binaries and library consumers.

> * If yes, Do we publish which version of k/release is used in a specific release of kubernetes (similar to how we generate the golang version etc and we make it easy to look up [dependencies](https://github.com/kubernetes/kubernetes/blob/master/build/dependencies.yaml))
> * If no, is there a reliable way to self-service and determine which version we should be using for a specific k8s version?

As Ben said, the dependencies used within the release are part of dependencies.yaml on the release branch. But we also track the used k/release (krel) version in the corresponding tracking issue of the release, for example: https://github.com/kubernetes/sig-release/issues/2186
