### ISSUE TITLE
Do we need to support `linux/arm` build/release artifacts in kubernetes (32-bit arm for Raspberry PIs)

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#115738]
Do we have folks that use `linux/arm` on Raspberry Pi's that directly use Kubernetes release artifacts?

Asking as there are projects like k3s that have lightweight alternatives, so maybe we don't need to own this anymore?

/sig release
/sig testing

PS: we are not asking about 64 bit arm which goes by `linux/arm64`

**Comment by ehashman** [comment]
Chiming in given request for feedback from chairs and leads...

I don't know anything about the costs of supporting this architecture so I can't make an informed recommendation here. But I do have some experience supporting a variety of architectures, so let me quickly speak to the benefit of these binaries for users.

I assume this is referring to 32-bit ARM binaries that run in low-resource environments (given the reference to raspberry pis) rather than arm64. In my experience, these are some of the most difficult environments to build binaries on directly. Projects the size of Kubernetes need a lot more resources to build than what is available on this hardware configuration. Hence,  these users can't just build the software on the device they want to run it on; rather, they will need to cross-compile in an environment with more resources. Many of the people who first play around with Kubernetes on a raspberry pi or similar low-cost hardware won't necessarily have access to better hardware to cross-compile on, or the knowledge that they _should_ cross-compile and how to do it. I'm not sure what our documentation looks like for this use case.

From my own personal experience, when I run projects on my raspberry pi, everything needs to be precompiled because compilation takes days if it's even feasible 😄

**Comment by aojea** [comment]
I think that Kubelet does not run on those devices https://github.com/kubernetes/kubeadm/issues/253

**Comment by brandond** [comment]
@aojea armv6 and armv7 are both 32bit, but K3s also dropped v6 support a while back (ref: https://github.com/k3s-io/k3s/issues/2699#issuecomment-744087139)

We also see a lot of users still choosing to running 32bit distros on the newer Pi4 hardware, for whatever reason.

**Comment by dims** [comment]
Some feedback from @xmudrii and @afbjorklund 

xmudrii
  [< 1 minute ago](https://kubernetes.slack.com/archives/C2C40FMNF/p1676324338071179?thread_ts=1676320691.243899&cid=C2C40FMNF)
Some refs that I have if it's helpful:
https://kubernetes.slack.com/archives/C03U7N0VCGK/p1666616361998889?thread_ts=1666607483.882399&cid=C03U7N0VCGK
https://kubernetes.slack.com/archives/C03U7N0VCGK/p1675788698163439?thread_ts=1674553212.858809&cid=C03U7N0VCGK


afbjorklund
Probably time to deprecate anyway, since it doesn't actually work on RPi 2 anymore (only k3s)
[From a thread in release-packages-poc](https://kubernetes.slack.com/archives/C03U7N0VCGK/p1666616361998889?thread_ts=1666607483.882399&amp;cid=C03U7N0VCGK) | [Oct 24th, 2022](https://kubernetes.slack.com/archives/C03U7N0VCGK/p1666616361998889?thread_ts=1666607483.882399&amp;cid=C03U7N0VCGK) | [View reply](https://kubernetes.slack.com/archives/C03U7N0VCGK/p1666616361998889?thread_ts=1666607483.882399&amp;cid=C03U7N0VCGK)


Neal Gompa
the RPM world is largely dropping 32-bit ARM faster than the Debian world
[From a thread in release-packages-poc](https://kubernetes.slack.com/archives/C03U7N0VCGK/p1675788698163439?thread_ts=1674553212.858809&amp;cid=C03U7N0VCGK) | [Feb 7th](https://kubernetes.slack.com/archives/C03U7N0VCGK/p1675788698163439?thread_ts=1674553212.858809&amp;cid=C03U7N0VCGK) | [View reply](https://kubernetes.slack.com/archives/C03U7N0VCGK/p1675788698163439?thread_ts=1674553212.858809&amp;cid=C03U7N0VCGK)

**Comment by mrbobbytables** [comment]
> I think that Kubelet does not run on those devices [kubernetes/kubeadm#253](https://github.com/kubernetes/kubeadm/issues/253)
> 
> It was a long time, but you had to patch kubelet https://github.com/aojea/kubernetes-raspi-binaries/blob/main/cpuset.patch


tbh - I didn't realize we were still building them for 32bit, I thought that was dropped some time ago.

**Comment by dims** [comment]
xref: https://github.com/kubernetes/kubernetes/pull/115742

**Comment by liggitt** [comment]
As far as I know, we don't have *any* 32-bit arm test envs/jobs, so we don't really know if the artifacts we're building/releasing actually ... work. There's at least anecdotal mentions (https://github.com/kubernetes/kubernetes/issues/115738#issuecomment-1428715238 https://github.com/kubernetes/kubernetes/issues/115738#issuecomment-1428726853) that the 32-bit arm server/kubelet binaries we're currently releasing actually _don't_ work. If there are counter examples, and people are actually using them, that would be really helpful to know.

I commented in https://github.com/kubernetes/kubernetes/pull/115742, but continuing to build *clients* as widely as we can seems a lot more reasonable than building server/kubelet targets on platforms we can't test.

**Comment by brendandburns** [comment]
Agree with @liggitt that we should continue to build the `kubectl` client for a broad range of hardware.

The last I tried running a full k8s cluster on ARM32 an apiserver node barely fit into a Raspberry Pi 2 since it only has 1Gb of RAM. Given that, building apiserver, controller manger, etc. is probably pointless.

While it is still feasible to run an older Raspberry Pi as a worker node, they're getting pretty old. So consider that a 'meh' for `kubelet`

Starting with Raspberry Pi 3, it is possible to run them on ARM64 mode instead of 32-bit mode, so newer RPIs should be covered, by the ARM64 builds which will continue.

**Comment by xUnholy** [comment]
As one of the members of the Kubernertes@Home community, I can confirm many members are using Raspberry Pis armv7 architecture, although many are using or directed to use arm64 where 64bit userland is concerned.

Without knowing the implications of the cost it seems feasible to continue to support as many architectures as possible I would have thought - Most individuals are using the 4B model variant which is either 4GB/8GB RAM which is more than sufficient for hosting a cluster.

**Comment by dims** [comment]
@xUnholy Do they use the release artifacts from kubernetes? Or do they use something like k3s or other stripped down distros?

**Comment by xUnholy** [comment]
Depends, there are over 5k users in that community - many using some variant, k3s is definitely a popular one. I do know there are individuals using Ansible playbooks to wrap kubeadm either with or similar to kubespray.

Are there any metrics we can use to see which architecture in the multi-architecture image is being pulled? I think last time I checked there wasn't which was one disadvantage to knowing which architectures were heavily being used but it could have changed.

**Comment by afbjorklund** [comment]
There was some discussion about this in:
* https://github.com/kubernetes/kubeadm/issues/2000

> We also see a lot of users still choosing to running 32bit distros on the newer aarch64 Pi4 hardware, for whatever reason.

I think this was the main reason to support arm32 still, and I think the reason they ran it on their arm64 hardware was that the vendor wanted a single software for all devices - and then decided to continue with 32-bit "for a while".

But as far as I know, even Raspbian (Raspberry Pi OS) is available in a 64-bit version now - if you care to upgrade...
https://www.raspberrypi.com/news/raspberry-pi-os-64-bit/ - previously it was easier to use Ubuntu, for that.

**Comment by afbjorklund** [comment]
The 2 vCPU and 2 GiB RAM minimum seems a bit arbitrary too, people routinely disable all the preflights just so that they can (try to) run Kubernetes on less ? I think that k3s is fine with 1 vCPU and 1 GiB RAM still, though. Unrelated to 32-bit, perhaps. But I think memory was the constraint on Raspberry Pi 3, had to enable swap in order to run `kubeadm`. And it was hitting some arbitrary timeouts, but I _think_ (?) most of those have been lifted now.

**Comment by afbjorklund** [comment]
I did get k3s running on my Raspberry Pi Zero (same hardware as Rasperry Pi 1). But it required zram enabled and it didn't have room for any apps, it was busy running the control plane. Not that there were any `armv6` apps to run, anyway. We concluded that it could _only_ run Docker Swarm or Nomad, and that Kubernetes had outgrown that hardware at that time. I would not be surprised if it has outgrown also the Raspberry Pi 2 by now, maybe even the Raspberry Pi 3 (except k3s).

**Comment by saschagrunert** [comment]
There are a bunch of SIG Release related documents around which have to be updated when dropping/adding a new platform:
- https://github.com/kubernetes/sig-release/blob/master/release-engineering/artifacts.md
- https://github.com/kubernetes/sig-release/tree/master/release-engineering/platforms

I think we can outline a comms plan for a deprecation and removal of a supported platform there as well.

**Comment by dims** [comment]
Sounds good @saschagrunert !

**Comment by saschagrunert** [comment]
Working in https://github.com/kubernetes/sig-release/pull/2171 towards the docs.

**Comment by alexellis** [comment]
The issue isn't whether armv6 is supported (RPi 1 / RPi Zero 1). This doesn't work, and Kubernetes even with K3s uses a large amount of resources even on the RPi 4 at idle.

Ubuntu is available for Raspberry Pi 3/4 on aarch64 - which is the same userspace as an Ampere server or AWS Graviton. There's also the 64-bit OS from the Raspberry Pi Foundation.

The issues with dropping armhf would be:

* where RPi3/4 users need to remain on Raspberry Pi OS (32-bit) due to hardware or software compatibility issues with 64-bit OSes
* Or if the K3s builds for armhf rely on a container, image, patch or artifact like the ones mentioned above and in linked threads

The K3s maintainers also considered this path, and got telling feedback from the community - https://github.com/k3s-io/k3s/issues/3213

This is probably something that should happen and have a timeline, but I would advise some engagement with the K3s project and more notice for community users.

**Comment by brandond** [comment]
I think if there was a bit of runway on dropping it, we could probably coordinate it better across the distros. I agree that probably most folks at this point have aarch64-capable hardware, and anyone still using 32bit arm is probably doing so for reasons of inertia, but suddenly dropping support for low-end hardware will definitely make Kubernetes less approachable for an already fairly vulnerable class of users. Is this going to have any impact on Google, Amazon, or Microsoft? Absolutely not. Will it have an effect on homelab users who are trying to develop their skills on a budget? Absolutely yes.

**Comment by dims** [comment]
@brandond as the 1.20 bug crisis showed, k8s does not have any testing whatsoever, we don't know if things work or not, we don't have anyone who takes care of it either. it's not funded. 

I think we are at a point where we can drop all the BigCo names argument. We are all on our own scrounging to keep things running, please read the 2 annual reports so far if anyone wants to ... to show how strapped we are for people's time and resources.

If k3s wants to do it, it's upto k3s folks. We are not deleting the Dockerfiles or anything like that. If folks want to build it, they can build it.

What is on the table here is whether we ship as part of kubernetes release artifacts. We are making a case that we are not going to do that anymore. There are literally 5-6 low edge case projects (not just k3s). So since their consumers as them to keep it alive, they will have to do the work. (same like dockershim, community is throwing its hands up saying we can't do this anymore!)

**Comment by brandond** [comment]
@dims do you see this as occurring immediately, across all active branches, or as a change for 1.27?

**Comment by dims** [comment]
@brandond we will deprecate first for 1.27 (release notes etc). Please see Sascha's https://github.com/kubernetes/sig-release/pull/2171/files for how we will do this (policy wise)

**Comment by sxd** [comment]
@dims it's a damage to keep the 32 bit support? why dropping this? some people still working with 32bit machines (raspberry pi) and in some part of the world getting a 64 bit raspberry pi it's not possible or it's really expensive, this decision will damage people with less access to hardware and that can lead to people not being able to actually help

**Comment by liggitt** [comment]
> @dims it's a damage to keep the 32 bit support?

root causing build issues with linux/arm32 ate a ~week of engineering time over the past, which we don't really have to spare

**Comment by sxd** [comment]
@liggitt but the benefit of having more people with access to the software on 32-bit hardware, which it's not that old, will help, helping people to code that maybe will never have access to 64bit hardware because of the lack of resources (money, poor countries) may help, not just the project, but society. I'm from Chile, the access to technology here it's a problem and sometimes 64bits hardware for kids in a rural school it's expensive, I don't think it's a wise decision, even if take weeks, we work on opensource which it's more than just time, it's about sharing and do everything for everyone else

**Comment by brandond** [comment]
We have also burned multiple days of developer time on arm32 at various points, usually right in the middle of trying to cut a new release following this project's patch releases. Ref:
* https://github.com/k3s-io/k3s/issues/2535
* https://github.com/k3s-io/k3s/pull/6769

**Comment by liggitt** [comment]
I definitely sympathize, but there's *always* more work to do than time available, and time spent solving esoteric arm32 issues means neglecting other bugs and issues that impact *all* kubernetes users.

This isn't proposing to forbid building on arm32, just to drop prebuilt artifacts so issues with arm don't become critical-path and release-blocking.

**Comment by sxd** [comment]
@liggitt what if a team of people that will maintain the arm32 arch it's created? just to maintain, meaning fixing this kind of issues so no one on the upstream needs to be worried about it? what if there's people that may be there for that?

**Comment by brandond** [comment]
I think at the end of the day, everyone is struggling with the same problem - arm32 was never a proper datacenter architecture, and it's hard to reproducibly build and support an architecture that you can't get good hardware for. The few projects that do still support this architecture do so via emulation or weird franken-nodes running aarch64 hardware with a 32bit userspace.

**Comment by dims** [comment]
@sxd you are welcome to work with one of the downstream projects that people already use like k3s, k0s, Microk8s and do what you need there.

**Comment by sxd** [comment]
@dims thank you! =)

**Comment by afbjorklund** [comment]
Running k3s might be a better fit for that hardware anyway, due to the increased requirements of kubeadm and the demise of similar options like localkube

But I don't know if Rancher has made any public comment to keep `armv7` alive, if it is not actively maintained/tested upstream anymore ?

**Comment by dims** [comment]
`if it is not actively maintained/tested upstream` has been true for a long time...

**Comment by afbjorklund** [comment]
But at least it is regularly compiled :-)

**Comment by dims** [comment]
Folks, the arm support is not working currently, to take it out of the critical release path we've turned off the in-project arm build. 

Here's the issue: https://github.com/kubernetes/kubernetes/issues/116492#issue-1619876723 and the pull

**Comment by dims** [comment]
looks like the decision was made for us for good or bad :( 

/close

**Comment by afbjorklund** [comment]
I guess the Raspberry Pi 2 (armv7) will join the Raspberry Pi 1 (armv6) on the shelf...

Long live Raspberry Pi 3! That is, as long as we can side-step the 2 GiB "requirement"

`--ignore-preflight-errors Memory`

`--skip-phases=preflight`

**Comment by afbjorklund** [comment]
Does that mean that the arm32 support will be removed from the packages for **all** releases, not only 1.27 ?

**Comment by saschagrunert** [comment]
> Does that mean that the arm32 support will be removed from the packages for **all** releases, not only 1.27 ?

Yes, let's discuss in https://github.com/kubernetes/release/pull/2960

**Comment by grunlab** [comment]
Oh damn, that's really a shame. Is it still possible to challenge/review this decision?

Until now, building a fully operational k8s cluster on armhf was OK as most of the surrounding projects are still supporting armhf architecture :
- weave-net
- metrics-server
- kubernetes-dashboard
- kube-state-metrics
- metallb
- traefik
- ...

Please, reconsider this decision.

**Comment by BenTheElder** [comment]
It's still possible to build for armhf yourself locally, FWIW. Roughly: `make release KUBE_BUILD_PLATFORMS=linux/arm`

You may run into some of the same issues with the go linker breaking on large binaries on this architecture that we haven't really had time to continue fighting with.
