### ISSUE TITLE
Is it still necessary to maintain the limitation on exposing port 10250 externally?

### ISSUE THREAD

**Issue by RyanAoh** [kubernetes/kubernetes#115896]
An error as follow:
```
#  kubectl expose deployment -n kube-system virtual-kubelet --port=10250 --type=LoadBalancer
The Service "virtual-kubelet" is invalid: spec.ports[0]: Invalid value: 10250: may not expose port 10250 externally since it is used by kubelet
#
```
People who see it for the first time may feel confused. I wonder if it's still necessary to maintain the limitation on exposing port 10250 externally?

refer codes:
https://github.com/kubernetes/kubernetes/blob/1d02d014e8c1f0de84b0b58b2165548182815320/pkg/apis/core/validation/validation.go#L4752-L4758

refer PRs:  
https://github.com/kubernetes/kubernetes/pull/10974/files#diff-c1aafafbdff6b09e8a118d05bce7f6594bd9f20a5073354ca8cd991577eeecf0R1042-R1049

https://github.com/kubernetes/kubernetes/commit/43ed74748eefd9814311dfe7174a8a60b6d22d15#diff-c1aafafbdff6b09e8a118d05bce7f6594bd9f20a5073354ca8cd991577eeecf0R1278-R1283

cc @brendandburns @thockin

**Comment by sftim** [comment]
:thought_balloon: We might want to start allowing this for cases where `spec.allocateLoadBalancerNodePorts` is false, possibly still with a warning?

:thought_balloon: A related challenge - what addressess and ports does `kube-proxy` listen on? If you're using kube-proxy - or your network plugin copies the approach - then kube-proxy may set up packet filtering rules that intercept traffic to a NodePort even when it arrives via the loopback interface.

---

To do this safely, I think we need a KEP. Not because we're making an API change but because a KEP lets contributors point out the snags and try things out at an alpha stage before unleashing the fix on everyone else's cluster.

**Comment by thockin** [comment]
OK, so the impact of a mistake is high :)

**Comment by dcbw** [comment]
What's the real use-case here? Is it to ensure there's a single nodeport for all nodes that maps to the specific virtual-kubelet running on each machine, such that you can always get that node's virtual-kubelet with <node-ip>:<nodeport>?

It doesn't make any sense to have ClusterIP access (which kubectl expose would also provide by default, unless the service was modified after-the-fact) because then you don't know which kubelet you're talking to, unless you use local traffic policy or something.

**Comment by qabpea** [comment]
Port 10250 is still not assigned by iana to a service name, does it make sense to register the kubelet's use of the port number?
https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml?&page=119

**Comment by thockin** [comment]
Discussed at sig-net:

The original use-case cited here (an LB over VKs) seems dubious, but I buy that there could be real use cases, and we agree this hidden restriction is pretty horrible.

The fact that we have this ONE port special-cased an not kube-proxy or other things is ugly. 

I don't know how we can assert that it's safe without auditing ~all providers.  We could add a flag (puke) like `--allow-service-port-10250` so that providers can set it.  I don't love it.

**Comment by sftim** [comment]
We could force users to make a choice (no default), and document that with a
**No, really, you MUST read this before you upgrade**
mention.

Not sure I like that either. But it's safe in its own way.

**Comment by sftim** [comment]
>  When starting a kubelet from a config file, it defaults safe (no anonymous access, authz is checked with the kube-apiserver).

Anyone doing the documented thing wouldn't need to choose (configuring the kubelet just with command-line arguments is deprecated AIUI).

**Comment by shaneutt** [comment]
Hi @RyanAoh!

We appreciate your interest in this issue, but as it stands we don't seem to have anyone who is ready to move this forward, so it's closed state (e.g. not prioritized, nobody with capacity to work on it) appears to be correct:

/close

If you're interested in taking this one on personally, please let us know and feel free to re-open and assign yourself to this and we'll be happy to support you in trying to see if we can move it forward.

In fact for a next step if you have some time and are feeling strongly about this issue, maybe you could put this on our agenda for the next SIG Network and come chat with us about it? It would probably be good for us to catch up on this and get our bearings.

**Comment by thockin** [comment]
We don't have clear process for "this is really an issue, but low prio, and nobody has had time for it yet".  I would lean towards leaving it open, myself?

**Comment by tssurya** [comment]
I am happy to help out with this issue, did we decide in the end that its going to be documentation fix OR are we gonna fix this via a flag mechanism ?

**Comment by thockin** [comment]
I don't think we have decided the solution - it stemmed from kube-proxy not properly filtering for IPs, IIRC

**Comment by thockin** [comment]
Revisiting this, I think it is safe to remove this limitation.  The GCP load-balancers have long ago been fixed, and I think that was the last one that was broken.

Who wants to do the honors? :)

**Comment by RyanAoh** [comment]
@thockin  I can fix it.
/assign
