### ISSUE TITLE
Allow end-users to control the rate at which Deployment replicas are scaled up/down

### ISSUE THREAD

**Issue by intUnderflow** [kubernetes/kubernetes#116132]
We have tooling inside of Kubernetes to control the disruption to an application during an update, for example we have maxSurge and maxUnavailable

These strategy definitions are ignored in cases where an end-user changes the desired number of replicas for a Deployment, however there can be cases where an end-user wants this strategy to be respected even when changing the desired replicas up/down, for example an end-user may desire that Kubernetes scales up their application from 10 to 20 replicas 1 pod at a time

I think we should include an optional field in the Deployment spec to indicate that a user wants the strategy to be respected when the desired replicas is lower/higher than the actual replicas in the underlying ReplicaSet, we can then mutate the ReplicaSet within the constraints of this strategy

Happy to write this once we know what approach we have consensus on

/sig apps

**Comment by sftim** [comment]
I'm not sure if you're asking for anything like these:
- a signal to things (outside the core of Kubernetes) that manage the Deployment, that explains how the scale of the Deployment should change
- a mechanism to let someone drive the scale of the deployment abruptly but have that abrupt change only affect the underlying ReplicaSets more gradually
- a mechanism to constrain what changes to a Deployment are acceptable; for example, only allowing the scale to change from its current value by up to _n_ replicas. Bigger changes would be rejected.
- a mechanism to constrain what changes to a Deployment's ReplicaSet(s) are acceptable; for example, only allowing the scale of a ReplicaSet to change from its current value by up to _n_ replicas. Bigger changes would be rejected.

If several of those might help to achieve the story you'd like @intUnderflow, which ones would work for your use case(s)?

**Comment by intUnderflow** [comment]
Hey @sftim 

I think this mostly fits into allowing someone to drive the scale of the deployment abruptly but have that change only affect the underlying ReplicaSet more gradually. Folks could absolutely do this themselves right now but having this as a stable feature makes it a lot nicer. We already have this when cycling in/out updated pods via the deployment strategy after all :)

**Comment by pwschuurman** [comment]
@intUnderflow It sounds like this would be introducing a `PodManagementPolicy` concept to Deployment (similar to StatefulSet): https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#parallel-pod-management. The default today is something like parallel pod management (new replicas are added/removed right away to the replicaSet when scaling up/down). Potential options I see:

1) A pod management policy type could be introduce with its own configuration for maxSurge/maxUnavailable, the downside of this being configuration sprawl.
2) A pod management policy type could be introduced that respects the updateStrategy (eg: when the updateStrategy is RollingUpdate, the maxUnavailable/maxSurge semantics would be followed when scaling in new replicas). This puts the updateStrategy as a dependency of the podManagementPolicy, and limits the flexibility of the updateStrategy API, since the podManagementPolicy needs to be considered when adding new updateStrategy types.
3) An option could live on the RollingUpdate strategy, which would allow a RollingUpdate to extend its responsibility to scaling operations. The might introduce a bit of API overreach however, now it's somewhat unintuitive that scaling operations are configured in a field called `.spec.updateStrategy`.

**Comment by sftim** [comment]
> An option could live on the RollingUpdate strategy, which would allow a RollingUpdate to extend its responsibility to scaling operations. The might introduce a bit of API overreach however, now it's somewhat unintuitive that scaling operations are configured in a field called `.spec.updateStrategy`.

The KEP could propose a v2 Deployment API with new field names. If we really want to expand RollingUpdate then a new API version (and deprecating v1) could allow that and still allow for a more ergonomic field name.

**Comment by intUnderflow** [comment]
I think trying to push for an entire new version of the Deployment API may be a way bigger step than this feature and I'm not sure I have the context with Kubernetes to get that into a state where it actually makes it to the mainline, I think we should try and find a way to fit this into the v1 API before considering that sort of move, if we have no choice though we could of course do it but it will need a wide level of consensus across sig-apps

I think introducing a new strategy at `.spec.scalingStrategy` (or a similar name) effectively in the form of option 1 from @pwschuurman seems like the best option right now, it does introduce a bit of sprawl but has good separation of concerns with updateStrategy

**Comment by pwschuurman** [comment]
> The KEP could propose a v2 Deployment API with new field names. If we really want to expand RollingUpdate then a new API version (and deprecating v1) could allow that and still allow for a more ergonomic field name.

IMO, if we were to introduce a v2 of the Deployment, it should incorporate a redesign of the availability API surface (`pdb.spec.maxUnavailable`, `statefulset.spec.updateStrategy.rollingUpdate.maxUnavailable`,  `deployment.spec.strategy.rollingUpdate.maxUnavailable`, `statefulset.spec.podManagementPolicy`) to simplify user configuration across the following three scenarios:
1) Replica Scaling
2) Replica Update
3) Infrastructure Update (Pod Disruption)

Rebooting an effort like (https://github.com/kubernetes/community/pull/2045) would allow for an overhaul of pod management scenarios across other APIs as well. However, I think pursuing this feature as a v2 API is a considerable lift and not worth the effort, just for the added value of having configuration of the replica scaling scenario for a Deployment.

> I think introducing a new strategy at .spec.scalingStrategy (or a similar name) effectively in the form of option 1 from @pwschuurman seems like the best option right now, it does introduce a bit of sprawl but has good separation of concerns with updateStrategy

@intUnderflow Would your use case require a scenario where you'd want to specify your scaling strategy to be different than your upgrade strategy (eg: would both be 1 pod at a time)? Trying to think of use cases where a scalingStrategy and an updateStrategy should be configured orthogonally. Since Deployments use read-write-many storage, or ephemeral storage, there isn't a caching use case that distinguishes scaling from update, as replicas are fungible. So I would guess that users would want scaling to either follow the update strategy, or to be as fast as possible (the default today).

**Comment by intUnderflow** [comment]
@pwschuurman not particularly, but I'm trying not to second-guess end-users unless I have a really good reason to, if we think users won't have a use-case for differing strategies though I'm happy to have it based on .spec.strategy.rollingUpdate

**Comment by intUnderflow** [comment]
I've been talking with some folks and nobody I know can give me a good use-case for having two differing strategies that they need in their usage of k8s, given that I think we should lean towards either 2 or 3 from @pwschuurman

**Comment by sftim** [comment]
https://github.com/kubernetes/kubernetes/issues/116214 makes me think we might want even more control over Deployments and rollouts. If I change the memory spec for a container, do I want that to be an in-place resize or a Pod replacement? Do I want all the in-place resizes to happen in parallel, or _n_ at a time?

What if I change the horizontal scale (replica count) and vertical scale (resource assignments) in a single, atomic update?

--- 

Does that potential need have an impact on how we want to define the update strategy / pod management policy? (I think it might, but not sure).

**Comment by pwschuurman** [comment]
> How I'd do this: a new ScalingConstraint API, that declaratively defines how to to arrive at a desired state for something (Deployment, StatefulSet, etc). ... It's one more object to define which isn't ideal.

I think leveraging PodDisruptionBudget API would increase adoption. I don't know if scale constraints need to be considered independently of an application's disruption policy. A deficit in the number of pods (scaling down: loss of processing capacity), as well as a surplus (scaling up: overhead for quorum reconfiguration, or partition rebalancing), are both disruptive. An API that can captures the ability for an application be disrupted, and under what circumstances could be a superset of the ScalingConstraint API.

**Comment by konryd** [comment]
One more use-case for similar feature: installing DaemonSets in large clusters. Currently it results in all Pods starting up at once, which might strain their network peers if they aren't ready to accept this much traffic.
