### ISSUE TITLE
[Failing test] gce-cos-master-scalability-100

### ISSUE THREAD

**Issue by gracenng** [kubernetes/kubernetes#116229]
### Which jobs are failing?

master-blocking
[gce-cos-master-scalability-100](https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-scalability-100)

### Which tests are failing?

kubetest.Up

### Since when has it been failing?

03-02 8:41 PST
<img width="1308" alt="image" src="https://user-images.githubusercontent.com/42276283/222517765-c4b5db8f-2614-4099-a710-c3bb41057c72.png">

### Testgrid link

https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-scalability-100

### Reason for failure (if possible)

ERROR: (gcloud.compute.addresses.describe) Could not fetch resource:
 - The resource 'projects/k8s-infra-e2e-boskos-scale-22/regions/us-east1/addresses/e2e-big-master-ip' was not found
Could not detect Kubernetes master node.  Make sure you've launched a cluster with 'kube-up.sh'
Master not detected. Is the cluster up?

### Relevant SIG(s)

/sig scalability

**Comment by gracenng** [comment]
Related to this conversation: [discussion on this #release-ci-signal slack thread](https://kubernetes.slack.com/archives/CN0K3TE2C/p1677757427497919)

**Comment by lauralorenz** [comment]
job is back to green, root cause was identified as same as https://github.com/kubernetes/kubernetes/issues/116224 ([slack ref](https://kubernetes.slack.com/archives/CN0K3TE2C/p1677780425078369)) which was resolved out of band via https://github.com/kubernetes/k8s.io/issues/4691#issuecomment-1452388686 and the permanent fix for which was in https://github.com/kubernetes/kubernetes/pull/116222

/close
