### ISSUE TITLE
Change the name of metrics in scheduler perf-tests

### ISSUE THREAD

**Issue by kerthcet** [kubernetes/kubernetes#116204]
### What happened?

We have `defaultMetricsCollectorConfig` here with unit as `seconds`
https://github.com/kubernetes/kubernetes/blob/b4b2345f9a4faa08715a1bf3114e6312938f8736/test/integration/scheduler_perf/scheduler_perf_test.go#L86-L96

But actually the unit is `ms`, see here: https://github.com/kubernetes/kubernetes/blob/b4b2345f9a4faa08715a1bf3114e6312938f8736/test/integration/scheduler_perf/util.go#L275-L285

Proposed to change this like `scheduler_framework_extension_point_duration_seconds` -> `scheduler_framework_extension_point_duration` to avoid confusing, but have no idea this is intended or will break the dashboard. 
/cc @marseel 

/kind cleanup
/sig scheduling

### What did you expect to happen?

Better naming with no confusion.

### How can we reproduce it (as minimally and precisely as possible)?

N/A

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by nikzayn** [comment]
@kerthcet I would like to take this up.

/assign

**Comment by nikzayn** [comment]
@kerthcet If we are going to update the naming convention, should we also need to update in **documentation.md**.
Check more for the image attached:
![Screenshot 2023-03-07 195300](https://user-images.githubusercontent.com/25152186/223450079-93628856-e732-4c03-90c0-e664d282d85d.png)

**Comment by kerthcet** [comment]
This is still waiting for confirmation, cc @mars1024 Would you mind to give a direction, will this break the perf-test dashboard by changing the metric label values.

**Comment by ahg-g** [comment]
shouldn't the name match the one we have defined in the scheduler, which is `framework_extension_point_duration_seconds`, otherwise we will not be able to look it up.

**Comment by kerthcet** [comment]
Oh yes... got messed up. By the way, maybe we can make the name `scheduler_framework_extension_point_duration_seconds` a combined name, like `SchedulerSubsystem + schedulingLatencyName`, better to display where it came from and avoid wrong spellings.

**Comment by nikzayn** [comment]
@kerthcet Is this change, good to go, I think we should create one variable for ```metrics.SchedulerSubsystem + "_" + metrics.SchedulingAttemptDurationSeconds```. should store in one variable something like: `**schedulerSubsystemAttemptDurationSeconds**`

**Comment by pohly** [comment]
Displaying scheduler_perf data in perf-dash is currently broken and needs quite a bit more thought and experiments to fix it. This goes beyond renaming one metric, but perhaps we can use this issue for tracking the problem? I can also create a new issue, but then the solution for that would conflict with a PR for this one here.

Only `scheduler_framework_extension_point_duration_seconds` works. Even then, some workloads don't seem to have data for "Score", so only "Filter" actually renders anything.

For results where there is no plugin label, for example `SchedulingThroughput`, nothing is shown because no data has "Score" or "Filter" as label value.

The conclusion [from Slack](https://kubernetes.slack.com/archives/C09QZTRH7/p1684856425322669?thread_ts=1676392759.560789&cid=C09QZTRH7) was that "you should not mix labels in the same file", i.e. all data items in the same file must have the same labels. We also have to be careful to avoid label combinations with no data.

**Comment by pohly** [comment]
@nikzayn: do you intend to continue working on this, considering that it is not as simple as just renaming some strings?

**Comment by nikzayn** [comment]
@pohly I will do this!

**Comment by nikzayn** [comment]
Yes please someone else work on this.

/unassign

**Comment by kerthcet** [comment]
Close this as out of date.
/close
