### ISSUE TITLE
flaky tests: pull-kubernetes-e2e-autoscaling-hpa-cm and pull-kubernetes-e2e-autoscaling-hpa-cpu

### ISSUE THREAD

**Issue by sanposhiho** [kubernetes/kubernetes#116315]
### Which jobs are flaking?

- pull-kubernetes-e2e-autoscaling-hpa-cm
- pull-kubernetes-e2e-autoscaling-hpa-cpu

Both are HPA's e2e test.

### Which tests are flaking?

(Let's grow this list)

#### pull-kubernetes-e2e-autoscaling-hpa-cm

- Kubernetes e2e suite: [It] [sig-autoscaling] [HPA] [Feature:CustomMetricsAutoscaling] Horizontal pod autoscaling (scale resource: Custom Metrics from Stackdriver) with multiple metrics of different types should not scale down when one metric is missing (Pod and Object Metrics)

### Since when has it been flaking?

not sure.

### Testgrid link

- https://testgrid.k8s.io/sig-autoscaling-hpa#gci-gce-autoscaling-hpa-cpu-pul
- https://testgrid.k8s.io/sig-autoscaling-hpa#gci-gce-autoscaling-hpa-cm-pull

### Relevant SIG(s)

/sig autoscaling

**Comment by sanposhiho** [comment]
https://github.com/kubernetes/kubernetes/pull/116040 is one of the PRs which tries to solve the flaky

**Comment by pbetkier** [comment]
Status update: `-cpu` is much less flaky after #117669 and `-cm` is getting fixed in #118048.

**Comment by pbetkier** [comment]
I worked on deflaking the tests. After #117669, #118048 and #118603 they are much less flaky now.

Looking at the last 20 job runs (testgrid columns):
* `-cpu`: 20 green, 0 red.
* `-cm`: 17 green, 3 red.

The reason for the `-cm` flakes is known – it's getting 429 errors because of hitting a rate limit on creating metric descriptors in GCP. But I won't work on this right now.

IMO we can close the issue as good enough tests health. Please reopen if you feel otherwise.

/close
