### ISSUE TITLE
No ports on docker ps for containers

### ISSUE THREAD

**Issue by adyanthaya17** [kubernetes/kubernetes#11665]
Hi,

I had brought up the nautius application from the '/examples/update-demo' which seems to be missing out from the repository. My containers were running fine but I was unable to get the web interface for it.

When I ran the command 'docker ps' I'm able to view the container but the port coloumn shows empty. Is that the reason as to why I'm unable to get the web application? How do I make the ports visble and add to the containers.

Thanks!!

**Comment by thockin** [comment]
The way Docker handles shared network namespaces requires ports to be
declared on the POD container, not any app container.  I consider this a
bug, they disagree.  It's their code.

As for why the example doesn't work for you, you'll have to provide a bit
more information...

**Comment by goltermann** [comment]
We’re going through old support issues and asking everyone to direct your questions to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes). 

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases. 

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.
