### ISSUE TITLE
safe-sysctls check on windows failed

### ISSUE THREAD

**Issue by pacoxu** [kubernetes/kubernetes#116790]
### What happened?

E0320 18:35:17.623064    4656 safe_sysctls.go:43] "Failed to get kernel version." err="error reading osrelease file \"/proc/sys/kernel/osrelease\": open /proc/sys/kernel/osrelease: The system cannot find the path specified."

### What did you expect to happen?

handle windows node correctly.

### How can we reproduce it (as minimally and precisely as possible)?

Run kubelet v1.27 beta+ on windows.

### Anything else we need to know?

https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-windows-win2022-containerd-gce-master/1637882397410201600/artifacts/e2e-04289f2be9-268c3-windows-node-group-4rhw/kubelet.log

https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-windows-win2022-containerd-gce-master/1637882397410201600

This is an example

### Kubernetes version

v1.27.0-beta*

### Cloud provider

N/A

### OS version

windows

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by pacoxu** [comment]
/sig node windows
The issue came from https://github.com/kubernetes/kubernetes/pull/115374.

**Comment by cici37** [comment]
This Issue/PR has been marked as release blocker. Please have the fix merged by eod today otherwise the feature has to be reverted. For the Issue/PR owner: please have a revert/feature disable PR open today in case the fix failed to get in. Thank you! See the [announcement here](https://groups.google.com/a/kubernetes.io/g/dev/c/yzSvdfk8mo8)

-- Kubernetes 1.27 release manager
