### ISSUE TITLE
Flannel Service Inactive (v1.0.1) 

### ISSUE THREAD

**Issue by devilankur18** [kubernetes/kubernetes#11709]
Flannel service is not running on a multinode cluster running on digital-ocean. I have build the cluster following the documentation from  https://github.com/GoogleCloudPlatform/kubernetes/blob/release-1.0/docs/getting-started-guides/coreos/coreos_multinode_cluster.md

Every other service is active except the flannel service.

    $sudo systemctl status *
    ● flanneld.service.d.service
       Loaded: not-found (Reason: No such file or directory)
       Active: inactive (dead)

More details in the gist https://gist.github.com/devilankur18/e0a401e96d1413edcbc6

**Comment by vishh** [comment]
cc @kelseyhightower

**Comment by pires** [comment]
That's not an error. `flannel` should be running. Can you please run `ifconfig grep flannel`?

You should see something like:
```
$ ifconfig |grep flannel
flannel.1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1450
```

**Comment by roberthbailey** [comment]
Please direct your questions to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes). 

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases. 

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to similar questions, and also familiarize yourself with:
  * [the user guide](http://kubernetes.io/v1.0/)
  * [the troubleshooting guide](http://kubernetes.io/v1.0/docs/troubleshooting.html)

Again, thanks for using Kubernetes.

The Kubernetes Team
