### ISSUE TITLE
Signing certificates for cluster addons using apiserver CA

### ISSUE THREAD

**Issue by uluyol** [kubernetes/kubernetes#11725]
I've been looking into getting a cluster-local docker registry up as a cluster addon (#1319) and the problem comes down to creating the certificate for the registry and trusting it. The apiserver CA cert is already visible from every node and every pod, so signing the registry certificate with the apiserver CA would eliminate any CA cert distribution issues.

Right now, we create the CA and apiserver certificate and key in a number of places (we have provider-specific ways to create them or use one of two scripts in salt). We don't copy over the CA key which is needed to sign new certificates.

One approach to fixing this is copying the CA key (might as well copy all of the pki/ directory used by easyrsa), but I'm not sure that this is a good idea. Alternative, we could add creation to every instance where the CA cert is created, but this is tedious and error prone.

**Comment by roberthbailey** [comment]
I didn't bother copying over the private key because it wasn't needed on the server (right now there is no dynamic certificate signing / generation). As we move towards dynamic clustering, the apiserver will need to be able to sign CSRs, so we will either need to make the server cert have signing powers or give the CA private key to the apiserver.

**Comment by bgrant0607** [comment]
cc @kelseyhightower

**Comment by bgrant0607** [comment]
See also https://github.com/kelseyhightower/docker-kubernetes-tls-guide

**Comment by smarterclayton** [comment]
This was discussed in a few earlier issues.  It should be on request.
