### ISSUE TITLE
Harden kubernetes TLS certificates 

### ISSUE THREAD

**Issue by sdputurn** [kubernetes/kubernetes#117378]
### What would you like to be added?

provide ability to customise kubernetes certificate authority (CA). kubernetes creates it's own CA and it's configuration (like v3 extensions) are not configurable. we have some security findings with this CA certificate (like key being places on the server filesystem, too long TTL with low key length). we are using Rancher based deployment which usage hyperkube.

we would like to add:
1. allow users to use a pre-created custom CA and certificate.
2. **or** allow ways to configure below items in kubernetes managed CA
  2.1 set the TTL value or RSA key length for k8s root CA?
  2.2 allow some way to store k8s root CA private key in a secure place like HSM?

### Why is this needed?

this is need to configure the CA based on user's requirement.

**Comment by sftim** [comment]
We already [document](https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-certs/#external-ca-mode) how to use your own CA with Kubernetes, although perhaps not as fully as we could do.

If you're unhappy about how Rancher works specifically, you should report a feature request to Rancher.

/kind support

**Comment by sdputurn** [comment]
thank for the update. I have gone through the docs. I still have 2 queries:
1. This [document](https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-certs/#external-ca-mode) is very specific to kubeadm. is there something for hyperkube?
2. if we do not want to run in external CA mode. is there way to configure certificate TTL and key length?

thanks,
Sandeep

**Comment by BenTheElder** [comment]
> This [document](https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-certs/#external-ca-mode) is very specific to kubeadm. is there something for hyperkube?

Hyperkube is no longer part of the Kubernetes project since 1.19, however even if it was, kubeadm would be the relevant subcommand of that binary.

Documenting certificate management without using kubeadm would largely have to be specific to the substitute tool used. The CA is setup by kubeadm, or the other tool.

**Comment by BenTheElder** [comment]
This part:

https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-certs/#set-up-a-signer

Is just configuring api-server flags, which is general. Instead of using that config you convert:

```yaml
controllerManager:
  extraArgs:
    cluster-signing-cert-file: /etc/kubernetes/pki/ca.crt
    cluster-signing-key-file: /etc/kubernetes/pki/ca.key
```

To passing `--cluster-signing-cert-file=/etc/kubernetes/pki/ca.crt` and `--cluster-signing-key-file=/etc/kubernetes/pki/ca.key` to controller manager via whatever setup tool you're using.

If that tool is rancher, rancher will have to document this.

For the general controller manager flags: https://kubernetes.io/docs/reference/command-line-tools-reference/kube-controller-manager/

**Comment by sdputurn** [comment]
thanks @BenTheElder / @sftim for your help. i got your point. so for any substitute tool, the way to manage CA should be documented by the tool. however at the end the ca and it's key are passed to the controller manager via command line arguments. 

i am ok to close this issue. 

thanks,
Sandeep
