### ISSUE TITLE
pod_status_manager_state: checkpoint is corrupted

### ISSUE THREAD

**Issue by aheng-ch** [kubernetes/kubernetes#117589]
### What happened?

After enabling In-Place Pod Vertical Scaling, if deploy a pod without setting memory (or cpu) request, kubelet will be failed at its second restart

### What did you expect to happen?

kubelet restart successfully

### How can we reproduce it (as minimally and precisely as possible)?

1. start kubelet with In-Place Pod Vertical Scaling enabled
2. deploy a pod without setting memory request, e.g: 
```
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
  - image: nginx:1.24.0
    imagePullPolicy: IfNotPresent
    name: nginx
    resources:
      requests:
        cpu: 100m
```
3. restart kubelet for the first time
4. restart kubelet for the second time
5. kubelet will fail with error: `panic: could not restore state from checkpoint: checkpoint is corrupted, please drain this node and delete pod allocation checkpoint file "/var/lib/kubelet/pod_status_manager_state" before restarting Kubelet` 

### Anything else we need to know?

After deploying the pod, the following information is saved in the file `pod_status_manager_state`:

```
      "nginx": {
        "cpu": "100m"
      }
```
Then restart kubelet for the first time, the relevant content in the file becomes: 
```
      "nginx": {
        "cpu": "100m",
        "memory": "0"
      }
```
------
When deploying the pod, as there are no records in the checkpoint (`pod_status_manager_state`), kubelet will get resource config from `pod.Spec.Container.Resources`  directly and save it to the checkpoint (without memory request)
https://github.com/kubernetes/kubernetes/blob/3125009dd1ebdde499a810110ba1f6d3fb05698f/pkg/kubelet/kubelet.go#L2504-L2521
When restarting kubelet for the first time, it will restore the previously saved data from the checkpoint. Since the memory request was not previously set, it will be set to an empty value and resaved to the checkpoint
https://github.com/kubernetes/kubernetes/blob/3125009dd1ebdde499a810110ba1f6d3fb05698f/pkg/kubelet/kubelet.go#L2508-L2514
When restarting kubelet for the second time, it will process `memory: 0` as a value of 0 (not empty), which resulting in the inconsistency between the calculated checksum during data recovery and the previous one

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by gjkim42** [comment]
cc @vinaykul

**Comment by SergeyKanzhelev** [comment]
xlink: https://github.com/kubernetes/enhancements/issues/1287
/cc @vinaykul

**Comment by vinaykul** [comment]
@aheng-ch thanks for finding this issue and the fix. It looks good with @bart0sh suggestion.
For beta, I wonder if we can do away with local checkpoint and rely on PodStatus as persistent store and source of truth for allocated resources. It will simplify the implementation.

**Comment by LastNight1997** [comment]
> @aheng-ch thanks for finding this issue and the fix. It looks good with @bart0sh suggestion. For beta, I wonder if we can do away with local checkpoint and rely on PodStatus as persistent store and source of truth for allocated resources. It will simplify the implementation.

Using resource.Quantity in checkoutPoint is a bad usage. I found except the case in this issue,  whenever adding a static pod to the kubelet, then restart the kubelet, restore the resize status checkpoint will fail, casing kubelet panic.

The reason is , before restart kubelet, the checkpoint struct in kubelet will looks like:
`{AllocationEntries:map[613b641e-0afc-4945-a8a4-cb9dd36b04b5:map[kube-proxy:map[]] a97d1ae92249a663934cea325205d0d2:map[kube-scheduler:map[cpu:{i:{value:6 scale:-1} d:{Dec:<nil>} s: Format:DecimalSI} memory:{i:{value:4294967296 scale:0} d:{Dec:<nil>} s:4Gi Format:BinarySI}]]]}`

and the the pod_status_manager_state file is looks like:
`{"allocationEntries":{"613b641e-0afc-4945-a8a4-cb9dd36b04b5":{"kube-proxy":null},"a97d1ae92249a663934cea325205d0d2":{"kube-scheduler":{"cpu":"600m","memory":"4Gi"}}},"checksum":201217417}`

and after restart kubelet and recover the checkoutpoint state, the checkpoint struct in kubelet will looks like:
`{AllocationEntries:map[613b641e-0afc-4945-a8a4-cb9dd36b04b5:map[kube-proxy:map[]] a97d1ae92249a663934cea325205d0d2:map[kube-scheduler:map[cpu:{i:{value:600 scale:-3} d:{Dec:<nil>} s:600m Format:DecimalSI} memory:{i:{value:4294967296 scale:0} d:{Dec:<nil>} s:4Gi Format:BinarySI}]]]}`

the difference is between "kube-scheduler:map[cpu:{i:{value:6 scale:-1} d:{Dec:<nil>} s: Format:DecimalSI}" and "kube-scheduler:map[cpu:{i:{value:600 scale:-3} d:{Dec:<nil>} s:600m Format:DecimalSI} ".  It's caused by json Marshal and Unmarshal of resource.Quantity.

So, I think Using resource.Quantity in checkoutPoint is a bad case. We should consider using PodStatus in apiserver instead of checkoutPoint.

**Comment by wenzhaojie** [comment]
@vinaykul Is this problem solved now I can still reproduce this problem in the official version of 1.28. Thanks~

**Comment by wenzhaojie** [comment]
Could anyone please let me know what is the state of the art to solve this issue?

**Comment by patrickshan** [comment]
we have seen the similar problem after enabling InPlaceUpdate pod resources and could we reopen this ?

**Comment by divanodestiny** [comment]
> > @aheng-ch thanks for finding this issue and the fix. It looks good with @bart0sh suggestion. For beta, I wonder if we can do away with local checkpoint and rely on PodStatus as persistent store and source of truth for allocated resources. It will simplify the implementation.
> 
> Using resource.Quantity in checkoutPoint is a bad usage. I found except the case in this issue, whenever adding a static pod to the kubelet, then restart the kubelet, restore the resize status checkpoint will fail, casing kubelet panic.
> 
> The reason is , before restart kubelet, the checkpoint struct in kubelet will looks like: `{AllocationEntries:map[613b641e-0afc-4945-a8a4-cb9dd36b04b5:map[kube-proxy:map[]] a97d1ae92249a663934cea325205d0d2:map[kube-scheduler:map[cpu:{i:{value:6 scale:-1} d:{Dec:<nil>} s: Format:DecimalSI} memory:{i:{value:4294967296 scale:0} d:{Dec:<nil>} s:4Gi Format:BinarySI}]]]}`
> 
> and the the pod_status_manager_state file is looks like: `{"allocationEntries":{"613b641e-0afc-4945-a8a4-cb9dd36b04b5":{"kube-proxy":null},"a97d1ae92249a663934cea325205d0d2":{"kube-scheduler":{"cpu":"600m","memory":"4Gi"}}},"checksum":201217417}`
> 
> and after restart kubelet and recover the checkoutpoint state, the checkpoint struct in kubelet will looks like: `{AllocationEntries:map[613b641e-0afc-4945-a8a4-cb9dd36b04b5:map[kube-proxy:map[]] a97d1ae92249a663934cea325205d0d2:map[kube-scheduler:map[cpu:{i:{value:600 scale:-3} d:{Dec:<nil>} s:600m Format:DecimalSI} memory:{i:{value:4294967296 scale:0} d:{Dec:<nil>} s:4Gi Format:BinarySI}]]]}`
> 
> the difference is between "kube-scheduler:map[cpu:{i:{value:6 scale:-1} d:{Dec:} s: Format:DecimalSI}" and "kube-scheduler:map[cpu:{i:{value:600 scale:-3} d:{Dec:} s:600m Format:DecimalSI} ". It's caused by json Marshal and Unmarshal of resource.Quantity.
> 
> So, I think Using resource.Quantity in checkoutPoint is a bad case. We should consider using PodStatus in apiserver instead of checkoutPoint.

can we just do marshal&unmarshal before storing state checkpoint to avoid the issue of resource.Quantity?

**Comment by vinaykul** [comment]
I am +1 on doing away with the checkpointing code altogether and leveraging PodStatus. We discussed this in the Kubernetes Contributor Summit in Chicago. https://static.sched.com/hosted_files/kcsna2023/a4/KCS-LeanKubelet.pdf
I just have not been able to find the cycles to work on it :(
