### ISSUE TITLE
NoDiskConflict when mounting GDE disk in read-only mode

### ISSUE THREAD

**Issue by hernanliendo** [kubernetes/kubernetes#11752]
Maybe related to [Issue 8478](https://github.com/GoogleCloudPlatform/kubernetes/issues/8478)

# Characteristics:
- UniqueCluster/Pod**A** has successfully mounted gdeDisk1 as read-write
- UniqueCluster/Pod**B** fails to start when mounting gdeDisk1 as read-only

# Node description:
```
Name:			gke-zupcat-cluster-8fd35d81-node-1zr4
Labels:			kubernetes.io/hostname=gke-zupcat-cluster-8fd35d81-node-1zr4
CreationTimestamp:	Wed, 22 Jul 2015 14:47:56 -0300
Conditions:
  Type		Status	LastHeartbeatTime			LastTransitionTime			Reason					Message
  Ready 	True 	Thu, 23 Jul 2015 12:06:18 -0300 	Wed, 22 Jul 2015 22:53:34 -0300 	kubelet is posting ready status 	
Addresses:	10.240.17.72,146.148.79.174
Capacity:
 cpu:		2
 memory:	7679608Ki
 pods:		40
Version:
 Kernel Version:		3.16.0-0.bpo.4-amd64
 OS Image:			Debian GNU/Linux 7 (wheezy)
 Container Runtime Version:	docker://Unknown
 Kubelet Version:		v1.0.1
 Kube-Proxy Version:		v1.0.1
PodCIDR:			10.108.0.0/24
ExternalID:			11953122931827361742
Pods:				(5 in total)
  Namespace			Name
  default			fastrwdiskpod-yu517
  kube-system			fluentd-cloud-logging-gke-zupcat-cluster-8fd35d81-node-1zr4
  kube-system			kube-dns-v8-i3h20
  kube-system			kube-ui-v1-8zdrq
  kube-system			monitoring-heapster-v5-e1zmi
No events.
``` 

# Versions
```
Client Version: version.Info{Major:"1", Minor:"0", GitVersion:"v1.0.0", GitCommit:"cd821444dcf3e1e237b5f3579721440624c9c4fa", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"0", GitVersion:"v1.0.1", GitCommit:"6a5c06e3d1eb27a6310a09270e4a5fb1afa93e74", GitTreeState:"clean"}
```

docker version Docker version 1.7.1, build 786b29d

**Comment by vishh** [comment]
AFAIK PD can be either shared across Pods in read-only access mode or be mounted to a single Pod in read-write mode.

**Comment by hernanliendo** [comment]
Are you saying that a Pod with read-write mode invalidates any other Pod to have it mounted as read-only?

**Comment by goltermann** [comment]
We’re going through old support issues and asking everyone to direct your questions to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes). 

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases. 

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.
