### ISSUE TITLE
KeyUsage array content changed in 1.27 for a non-RSA key

### ISSUE THREAD

**Issue by nnmin-aws** [kubernetes/kubernetes#117506]
### What happened?

https://github.com/kubernetes/kubernetes/pull/111660

This PR changed the KeyUsage array from including 3 items to 2 in non RSA key case. KeyUsage is defined https://github.com/kubernetes/api/blob/master/certificates/v1/types.go#L124.

Hence starting 1.27 the [CertificateSigningRequest](https://github.com/kubernetes/api/blob/master/certificates/v1/types.go#L41) content actually changed but the version doesn't change accordingly.

This breaks a scenario in EKS with fargate where a non-RSA key is used. For example `kubectl exec` fails.

### What did you expect to happen?

Should not break existing applications when/where non-RSA key is used

### Kubernetes version

<details>

```console
$ kubectl version
1.27
```

</details>

### Cloud provider

<details>
aws
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by dims** [comment]
The PR commit where this happened was:
https://github.com/kubernetes/kubernetes/commit/160f015ef4affe903f98e74cf42b40fceef15cb9

The change is intentional (when using RSA key then there are 3 elements and a non RSA key has 2 elements):
https://github.com/kubernetes/kubernetes/commit/160f015ef4affe903f98e74cf42b40fceef15cb9#diff-b49646d3b5721aba05c9972b2dafe4b0fe182f5a87169bbc57696eca52e16cd6R52

Looking at the issue in k/k and the one in golang, the change is definitely the right thing to do:
- https://github.com/kubernetes/kubernetes/issues/109077
- https://github.com/golang/go/issues/36499

Unfortunately the release note says `Relax API validation for usage key encipherment and kubelet uses requested usages accordingly` (from https://github.com/kubernetes/kubernetes/pull/111660) which did not trigger enough alarm bells when someone is browsing the CHANGELOG. 

So folks who were relying on the number of elements (EKS components) have to go update their code to match the changes made in our code base. `tolerating CSR objects with/without that usage` is definitely called out in the issue logged by Jordan and folks probably did not notice the older PR https://github.com/kubernetes/kubernetes/pull/111061 in the previous kubernetes release.

**Comment by dims** [comment]
/sig auth

cc @pacoxu @liggitt

**Comment by nckturner** [comment]
Hmm yea its debatable but it would have been nice to have a callout in API changes for this, even though its not strictly an API change.

**Comment by liggitt** [comment]
Can you clarify what broke? The Kubernetes-provided approver / signer was updated a release before the kubelet adjusted the usages it requests

**Comment by dims** [comment]
nothing we can do now but march forward :)

/woof
