### ISSUE TITLE
Allow changing .spec.podManagementPolicy of an existing StatefulSet

### ISSUE THREAD

**Issue by geobeau** [kubernetes/kubernetes#117693]
### What would you like to be added?

At the moment, if you try to change the podManagementPolicy of an existing StatefulSet, you will be rejected:
```
spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden
```

The goal of this enhancement is to allow changing the policy dynamically.

### Why is this needed?

Changing the podManagementPolicy during the lifecycle of a statefulset would be useful for several reasons:
- You might not have chosen the correct policy in the first place
- The requirements of the workload running on the sts might have changed
- You might want to use different policies in different conditions

To give a more practical use case. When running a database, typically during the initial bootstrap or a scale up operation, you want to be in `OrderedReady`. In this mode each pod will start in order, waiting for the previous one being ready before starting.
But once the database is fully deployed and ready, you want to be in `Parallel`: during an incident, if multiple pods are forcefully evicted, you want all of them to come back as fast as possible. With ordered ready, you have to wait for all them to come up in order.
So what we would like is to be able to set `OrderedReady` during creation/scaling and be in `parallel` during normal operations/incident time.

The current alternative are not practical:
- Replace the statefulset: delete and recreating the sts with impacting pods is risky and typically unwanted. Often you are also using operators that might not let you create a new STS with a different name.
- Implement a controller to add the OrderedReady behavior to a Parallel STS: It doesn't work if you are not in Parallel to start with. It would also add more complexity for a behavior already provide by Kubernetes.

 ---------------------------------
 
 I first reported the issue on Slack #sig-apps where I was told to create this issue: https://kubernetes.slack.com/archives/C18NZM5K9/p1682342356800229
 
 The change appears simple, as it would just be about allowing the policy to be changed in the validation code:
 https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/apps/validation/validation.go#L171-L197

**Comment by ibilalkayy** [comment]
Hey there,

I have submitted a PR to address this issue. The proposed solution allows updating the .spec.podManagementPolicy field of an existing StatefulSet by modifying the ValidateStatefulSetUpdate function. You can find the PR here: https://github.com/kubernetes/kubernetes/pull/117698.

Please feel free to review the changes and provide any feedback or suggestions.

Thank you!

**Comment by zcahana** [comment]
> The change appears simple, as it would just be about allowing the policy to be changed in the validation code:
https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/apps/validation/validation.go#L171-L197

One additional issue to tackle is how to handle `.spec.podManagementPolicy` changes amidst an ongoing deployment/scaling operation.
- The `OrderedReady`--> `Parallel` direction is rather simple, and can be well-defined - upon policy change, all of remaining StatefulSet pods which haven't been started yet - are started in parallel (and similarly for termination).
- The `Parallel` --> `OrderedReady` is a little trickier. The simplest approach appears to be to retain any pod creation/deletion that was already conducted before the policy change. Is there any scenario in which only some of the pods managed to be created/deleted in parallel, while others didn't (e.g., due to partial failures)? If so, there needs to be a well-defined behavior of how to handle these other pods - e.g., continue with `Parallel` semantics (how to detect we "were" in parallel?), continue with `OrderedReady` semantics (are these well defined for such edge cases?).

What do you think?

**Comment by zcahana** [comment]
> For your use case, if you want to do a rolling update after initial deployment, would you also want it to be sequential or parallel is ok?

> I would do them sequentially:
>
> - either by changing the policies in Statefulset
> - switch to OnDelete and let a controller do it safely

Aren't rolling updates always applied with `OrderedReady` semantics, regardless of `.spec.podManagementPolicy `?
