### ISSUE TITLE
PodSpec defaulting sets hostPort on hostNetwork pods, but in the template rather than the pod

### ISSUE THREAD

**Issue by stavros-k** [kubernetes/kubernetes#117689]
### What happened?

After disabling hostNetwork on an already deployed Deployment, hostPorts are not cleared up.
Even if I explicitly set hostPort(s) to `null`, Ports that have the same number for TCP and UDP, only the TCP gets cleared up.

### What did you expect to happen?

hostPorts to get cleared on the new Pod

### How can we reproduce it (as minimally and precisely as possible)?

Deploy any container (in a deployment) with hostNetwork enabled and configure ports like this:

            - name: web
              containerPort: 8384
            - name: tcp
              containerPort: 22000
              protocol: TCP
            - name: udp
              containerPort: 22000
              protocol: UDP
            - name: somerando
              containerPort: 25000
              protocol: UDP

Then disable hostNetwork. Check new pod, still shows the above ports as hostPorts

Then go and change the above ports like this:

            - name: web
              containerPort: 8384
              hostPort: null
            - name: tcp
              containerPort: 22000
              protocol: TCP
              hostPort: null
            - name: udp
              containerPort: 22000
              protocol: UDP
              hostPort: null
            - name: somerando
              containerPort: 25000
              protocol: UDP
              hostPort: null

You will see all ports are now hostPort FREE, except the 22000/UDP. this still shows up in the hostPorts

### Anything else we need to know?

I've a longer version with more step by step reproduction here -> https://github.com/k3s-io/k3s/discussions/7382
(Posted in k3s repo first to make sure it's not a downstream issue)

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.27.1
Kustomize Version: v5.0.1
Server Version: v1.25.4+k3s1
```

</details>

### Cloud provider

<details>
Local Node (k3s)
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 23.04"
NAME="Ubuntu"
VERSION_ID="23.04"
VERSION="23.04 (Lunar Lobster)"
VERSION_CODENAME=lunar
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=lunar
LOGO=ubuntu-logo
$ uname -a
Linux IdeaPad-5-Pro-14ACN6 6.2.0-20-generic #20-Ubuntu SMP PREEMPT_DYNAMIC Thu Apr  6 07:48:48 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>
k3s
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by aojea** [comment]
I think this is one variation of this known issue https://github.com/kubernetes/kubernetes/issues/105610

@thockin one of your favorite :)

**Comment by thockin** [comment]
>Deploy any container (in a deployment) with hostNetwork enabled and configure ports like this:

I assume "with hostnNetwork" means Pod `.spec.hostNetwork: true` ?

The snippet you posted is not using `hostPort`s but we automatically convert declared ports on hostNetwork pods into hostPorts.  Unfortunately, we do so on the pod TEMPLATE, inside the Deployment / DaemonSet / whatever.

> Then disable hostNetwork

I assume this to mean setting Pod `.spec.hostNetwork: false` on the Deployment, which will cause all of the pods to be redeployed?

But, since the `hostPort` value was already set in the Deployment, it isn't automatically cleared.  The truth is that, at this point, we can't tell if you meant for them to be hostPorts or if we set them as defaults.

You can unset them manually, as you have done, but there's a related issue, which I can't find right now, where client-side apply uses a merge-key of port number without protocol, making the exclusion you see happen.  Unfortunately there hasn't been a good solution to that except to use server-side apply or use `kubectl replace` instead of patch or edit.

I know this is kind of sucky.  We might be able to fix the defaulting so it doesn't apply except to Pod (in this specific case - in general we have this defaulting problem) by attaching it to Pod rather than PodSpec.  I won't have time to try in the immediate future, but this does seem like a legit bug.  I'll update the title. 

I am going to leave it un-triaged until next sig-net meeting.

**Comment by stavros-k** [comment]
@thockin Yes, `hostNetwork: true/false` translates to `.spec.hostNetwork: true/false` (sorry working mostly with helm, should have been more clear).

The `null` to hostPort works like a charm for ports with single protocol. 
The issue is that AFAIK you can't tell helm to do server-side apply or replace. (As you already explained)

While me and maybe few others are capable of doing so manually, 
We provide helm charts (as catalog of "apps" both TrueCharts and iXSystems) via a "GUI" (TrueNAS SCALE) to make things easier for end users. Luckily only a handful of "apps" are affected since I applied the `hostPort: null` "fix". Which for now we can guide users to manually solve it.

Anyway. since it's a known issue, I'm sure it will get looked at and a solution will be found when the times come.

Thanks for looking into it and explaining the alternatives/workarounds for now.

Thanks.

**Comment by thockin** [comment]
It's worth noting that Pod ports definitions are REALLY only useful for 2 things:

1) declaring hostPorts (as you did) to avoid conflicts
2) name-based port remapping from a Service

If you are no longer using hostNetwork, you can just remove the `ports` block entirely.

**Comment by stavros-k** [comment]
> It's worth noting that Pod ports definitions are REALLY only useful for 2 things:
> 
> 1. declaring hostPorts (as you did) to avoid conflicts
> 2. name-based port remapping from a Service
> 
> If you are no longer using hostNetwork, you can just remove the `ports` block entirely.

Thanks for the reminder, yea it was mostly there for "documentation" purposes and debug/support.
I'll consider adjusting the helm charts to only include the section when hostPort is defined.

**Comment by thockin** [comment]
#117696 merged which should prevent this from being defaulted on the pod template in the future.  Unfortunately, the issue with client-side merge remains unsolved, but there are other issues open for that.  So I will resolve this one for now.
