### ISSUE TITLE
Add a condition to determine when a job is ready.

### ISSUE THREAD

**Issue by kannon92** [kubernetes/kubernetes#117758]
### What would you like to be added?

In the jobset proposal there was a request that Jobs should have some kind of Readiness condition.  Currently we have a status field that tells how many Jobs are ready. 

> Add readiness status. Add a new condition to declare a job is ready. This should be configurable, for example the job is ready if 80% of the pods are ready.

### Why is this needed?

When using JobSets, a user may want to start the replicatejobs if a percentage of jobs are ready.

**Comment by kannon92** [comment]
@ahg-g or @danielvegamyhre I could use a little help on the motivation for this from the jobset side.  

I was discussing this in the context of having a activeDeadlineSeconds based on ready and I realize that we would probably want some kind of condition to actually do this.  And I saw that there is a potential request to have this as part of the jobset.

**Comment by vsoch** [comment]
I have a related use case (but I'm not sure it's exactly the same). For any service / worker setup, you'd often want the lead service to start up first, and be ready to receive the workers. We'd want to be able to say "start the workers when the lead broker is ready." However, this would be between ReplicatedJobs within a JobSet, and I'm not sure that is relevant to the issue here, which seems to be about an entire Job being ready (for a user interaction or similar).

**Comment by kannon92** [comment]
> I have a related use case (but I'm not sure it's exactly the same). For any service / worker setup, you'd often want the lead service to start up first, and be ready to receive the workers. We'd want to be able to say "start the workers when the lead broker is ready." However, this would be between ReplicatedJobs within a JobSet, and I'm not sure that is relevant to the issue here, which seems to be about an entire Job being ready (for a user interaction or similar).

With the JobSet composing Jobs, I think this is very relevant.  

In your case you'd want all jobs in the broker set to be ready before you start the worker set.  

I think that in that case you'd want a condition in the Job status and replicatedJobs would just set the condition for the job.

**Comment by alculquicondor** [comment]
At a first glance, I'm not sure this is necessary. We have the `ready` field in status, counting the number of Pods with a Ready condition. Could higher level constructs such as jobset just use that?

**Comment by asm582** [comment]
pods are ephemeral and they can fail or die. is there a guarantee to maintain % of `Ready`?

**Comment by vsoch** [comment]
> pods are ephemeral and they can fail or die. is there a guarantee to maintain % of Ready?

I was thinking about this too today - and I think it's biased for using Kubernetes for services. Some something like a web server, it could be killed and you'd want it to restart. But for jobs / batch where it's less a service and more execution / finish of a script, you typically expect it to be ready, run, and complete, and if there is a case where a pod dies during the application run (again assuming it's not a sever or service) you wouldn't want it to just infinitely restart.

I think we are hitting the different use cases of K8s for stateless services vs. K8s for batch jobs that are the opposite. I don't have an answer but wanted to point this out, because this issue (in my head) feels more geared toward the latter.

**Comment by mimowo** [comment]
> Operating on conditions at the job level is much more convenient than looking at the status field for individual fields. One reason why we are bringing this up in the JobSet is that it would be nice to be able to operate on conditions for determining Ready or Succeeded if we wanted to build some kind of StartupPolicy. I think a similar reason that @mimowo utilizes conditions for PodFailurePolicy rather than looking at a status field is also.

The reason is similar, however, there is a difference. We introduced `DisruptionTarget` condition, because  the "reason" or "evicting component" information was not available in the Pod status. Ok, for some components there was pod-level `reason` set, but it wasn't consistent, would require string parsing, and would require setting the fields for components which didn't do it before.

Then, for exit codes, which were already part of the status, we support them inside `podFailurePolicy.rules.onExitCodes`, rather then surface (duplicate) then information as a pod condition.

So, IMO it is case-by-case. IMO, a new condition just to expose the value of `.status.ready` is overkill. 

Unless, `ReachedReady` is needed, it could indicate that the Job was ready at some point, but it is not necessarily ready currently, but not sure this is useful.

**Comment by vsoch** [comment]
Not to open the can of worms more, but this reflects on a larger issue that Kubernetes doesn't have the same level of granularity, both in things like timestamps or states (which are typically managed by a job manager). E.g., in Flux [rfc](https://flux-framework.readthedocs.io/projects/flux-rfc/en/latest/spec_21.html) we have an entire state diagram 
![image](https://github.com/kubernetes/kubernetes/assets/814322/5726bb4f-265a-43f8-b1f8-34bf4e38c2b7)

and ability to easily query and map actions to the states. Here is another (simpler) view:

![image](https://github.com/kubernetes/kubernetes/assets/814322/decfc93a-c7c5-49bf-9024-0fb4429f9732)

Note that is missing several other modules that handle logic, but you get the gist! This is an interesting thing to talk about because Kubernetes inherently was designed for services (not as in a Kubernetes service, but a persistent running application), so an entire space of additions for batch (a scoped piece of work that is typically not persistent and you'd be worried if it's restarting) is an extra we are adding (or almost forcing) onto that model. When the default is persistent applications, the idea of ending timestamps / timestamp granularity better than one second, the abstractions needed for running batch (such as knowing states as this issue is talking about) are kind of foreign, and polling one or more pods for conditions is not really the same thing as an entire job being able to have one holistic state that is accurate at any point in time.

Not sure if I'm contributing to the discussion, but this was on my mind this morning! I wanted to point out we are trying to merge two very different underlying models, or force one (scoped work) onto a different one (persistent application).

**Comment by kannon92** [comment]
We brought this up in the wg-batch meeting on August 3rd.  

Outcome of the meeting was that JobSet could utilize `ready` field in JobStatus.   

For [Active Deadline once Pods started](https://github.com/kubernetes/kubernetes/issues/111948), this issue could motivate some kind of condition or time when the pods are started.  Currently Active Deadline starts when `StartTime` is set (in case of starting or resuming a suspend job).  If we want Active Deadline to start when the job's pods are running, we would need some kind of timestamp when a job is "ready".  

We decided to leave this issue open in case of other use cases.

**Comment by kannon92** [comment]
actually I don't think we relaly need this.

/close
