### ISSUE TITLE
client: shared informer SetX functions are racy

### ISSUE THREAD

**Issue by howardjohn** [kubernetes/kubernetes#117869]
### What happened?

The functions SetWatchErrorHandler and SetTransform are racy with ShareInformer factory

Consider the following example:
```go
	informerFactory := informers.NewSharedInformerFactory(client, 0*time.Second)
	go func() {
		informerFactory.Start(stop)
	}()
	serviceInformer := informerFactory.Core().V1().Services().Informer()
	serviceInformer.SetWatchErrorHandler(func(r *cache.Reflector, err error) {
		// ...
	})
```

In the real world, the goroutine running Start is likely entirely decoupled from the rest; the code here is fairly obviously "wrong".

This has both a data race (I have a PR ready for this) and a logical race. There is no safe way to call these functions unless the entire application is sequenced in a manner such that all informers are created before Start is called. In our real world case, we have some informers that start after application start, which leads to races with other components calling Start().

### What did you expect to happen?

SetWatchErrorHandler and SetTransform can be called without races. That is, I can make an informer from a shared informer factory, set a watcher handler and transform, and ensure they are applied.

### How can we reproduce it (as minimally and precisely as possible)?

See incoming PR which has a test case

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by howardjohn** [comment]
/sig api-machinery

Note: I am working only on the data race aspect currently. How to fix the logical race is more challenging.

**Comment by alexzielenski** [comment]
I think in general these functions were meant only to be set immediately after construction. Since the informer factory abstracts that away from you that is a bit more challenging for users of the informer factory, it is a bit harder to solve in general. 

Given that they are not meant to be called more than once, or really that far from construction, I am not sure it makes sense to support synchronizing them.

IMO Use cases of `Set*` on an informer I've seen are:
1. Make a local informer that does something weird.
In this case you probably don't want to share it and you can safely call these functions after construction.

2. Globally apply some transformation/general handler onto informers for all objects. 
In this case I think a good solution would be to wrap SharedInformerFactory that wraps the provided `newFunc` in `InformerFor` to call whatever customizations you want. `SharedIndexInformer` could possibly have this added as an option fairly easily:

https://github.com/kubernetes/kubernetes/blob/f0417ac850a080e7ccf5081557c742c0b545d7a8/staging/src/k8s.io/client-go/informers/factory.go#L187-L208

Customizations could be applied after the `informer = newFunc(f.client, resyncPeriod)` line

**Comment by howardjohn** [comment]
Thanks for the suggestion - option (2) is great and led me down a rabbit hole of other improvements in our controller.

I had also tried a similar approach wrapping the new informer creation and Run calls in a shared mutex. At surface level seems like that would work as well, although I didn't test it much as we are going to go with (2) instead.

I do still think that https://github.com/kubernetes/kubernetes/pull/117870 is useful - we currently attempt to check for the informer already started, we just do that in an incorrect/racy way. But if anyone is triggering that, they _probably_ want to reconsider their calling patterns

**Comment by howardjohn** [comment]
Fixed via https://github.com/kubernetes/kubernetes/pull/117870 I think, as the rest is decided as WAI and can be worked around as done ^
