### ISSUE TITLE
CNI networking errors leave node marked ready but unusable

### ISSUE THREAD

**Issue by davidmatson** [kubernetes/kubernetes#118118]
### What happened?

When using an CNI (for example, Azure/azure-container-networking#3220), it may fail. Even if the plugin correctly reports errors back, the node is still marked ready, but it's unusable. If the node were not marked ready, the auto-scaler could heal.

### What did you expect to happen?

The node was not marked ready.

### How can we reproduce it (as minimally and precisely as possible)?

Have a node with a CNI that fails and reports an error.

### Kubernetes version

n/a

### Cloud provider

n/a

### Related plugins (CNI, CSI, ...) and versions (if applicable)

azure-container-networking, likely any version

**Comment by aojea** [comment]
> Have a node with a CNI that fails and reports an error.

This is a responsibility of the CNI, there is no much Kubernetes can do here.
From the top of my head, the CNI  can implement one of these two things:
- remove the cni config file, so the kubelet will automatically get tainted because it fails the readiness of the network (this comes via the container runtime)
- use a controller that detects that the CNI is down and taint the node


/close

**Comment by davidmatson** [comment]
@aojea  - thanks for the reply! To clarify, when you say "the CNI", do you mean the general integration between the CNI framework and Kubernetes? Or a specific CNI plugin, such as the azure one?

If it's the CNI framework itself that should have this behavior, do you know the right place to file an issue to track?

Thanks!

**Comment by aojea** [comment]
> If it's the CNI framework itself that should have this behavior, do you know the right place to file an issue to track?

The CNI plugin,

**Comment by shaneutt** [comment]
> If it's the CNI framework itself that should have this behavior, do you know the right place to file an issue to track?

If you mean which repository, I'm not 100% sure but I think the repository you referenced in your original post might be the place?

https://github.com/Azure/azure-container-networking

**Comment by davidmatson** [comment]
@aojea @shaneutt - having each CNI plugin communicate directly with K8S doesn't seem ideal - the response from the plugin folks is that they're sending the error back, and it's up to the CNI infrastructure to handle errors meaningfully. Can the CNI infrastructure handle this behavior, rather than each plugin having to do work here?

**Comment by aojea** [comment]
ok, this is a common problem with the terminology, the CNI spec is about adding or deleting the interfacees to the Pod, it just not handle node state.

But in kubernetes environments this is commonly used to name the "plugin" itself, like per example cilium or calico are commonly named CNI plugins.

So, these projects do something else than just adding interfaces and IPs to the Pods, like tainting the node per example.

Since the CNI plugin is not directly connected to kubernetes, is connected to the container runtime, is up to the implementations to decide how to handle this
