### ISSUE TITLE
startupProbe will runs again after kubelet restart

### ISSUE THREAD

**Issue by wenlxie** [kubernetes/kubernetes#118245]
### What happened?

I had a pod with containers that has startupProbe configured. 

Then I restart kubelet, 
Containers with startupProbe configured will be mark with containerStatuses.started=false
After startupProbe runs again and then set containerStatuses.started=true
Is this expected behavior? 

For the code,  https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/core/types.go#L2487-L2496

![image](https://github.com/kubernetes/kubernetes/assets/7530735/ea96082e-bcf2-45d0-8cd8-ce5428fc964d)

The started status is false by default, and then it will trigger the startupProbe runs again. 

But actually, the container had already running. 
It is unnecessary to do this. 

### What did you expect to happen?

When kubelet restart, it is no need to run startupProbe again. 

### How can we reproduce it (as minimally and precisely as possible)?

Create a pod with startupProbe, then restart kubelet

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by saschagrunert** [comment]
I assume this is expected behavior, because the kubelet will loose it's state on restart and has to re-evaluate the status again:

https://github.com/kubernetes/kubernetes/blob/2e306e9632b13a3c1530a7e7ddf52a50f4741523/pkg/apis/core/types.go#L2490-L2491

**Comment by BenTheElder** [comment]
If it's expected behavior, documenting it only on the container status object is not ideal.

I can't find anything relevant about this in:
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.27/#container-v1-core
https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#container-probes
https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/

I don't think this is expected behavior as a user, since there's pod state outside of kubelet reflected the startup probe success.

**Comment by adisky** [comment]
I do agree that this may not be expected behaviour as the user, but kubelet lost all its state and doesn't know what caused the restart, possibly a node reboot and for node reboot containers also get restarted so it has to probe the container again. 

I think this startup probe behaviour needs to be documented more clearly.

cc @SergeyKanzhelev (as from the other linked issue Sergey is documenting probe issues separately)

**Comment by BenTheElder** [comment]
> I do agree that this may not be expected behaviour as the user, but kubelet lost all its state and doesn't know what caused the restart, possibly a node reboot and for node reboot containers also get restarted so it has to probe the container again.

I don't think it's infeasible to avoid re-probing?

We have information about when the pod status changed in CRI right? And we have the last recorded startup probe state.

Container / Pod state is not only in kubelet memory. I don't think we should just consider this sort of thing WAI.

**Comment by adisky** [comment]
> We have information about when the pod status changed in CRI right?

yes

> And we have the last recorded startup probe state.

I didn't know this, if ` last recorded startup probe state` persist after kubelet restart then definitely we can avoid reprobing

**Comment by SergeyKanzhelev** [comment]
This may be improved as part of the https://github.com/kubernetes/kubernetes/issues/100277. But this is an expected behavior as implemented now.

/remove-kind bug
/kind feature

**Comment by BenTheElder** [comment]
> I didn't know this, if  last recorded startup probe state persist after kubelet restart then definitely we can avoid reprobing

It's on the pod object ..?

**Comment by BenTheElder** [comment]
To avoid retriggering we need to know:
- [x] Container was not restarted by CRI since we last looked 
- [x] Probe already succeeded 

We can determine both of those by pod container started status (with timestamp_ in k8s pod object persisted in API server vs CRI container status persisted in CRI (also with start timestamp).

If the container has started status at time X in the pod object and start time Y in CRI with  X ≥ Y then don't reprobe?

**Comment by BenTheElder** [comment]
[Note: this is just discussion about feasibility and desirability, actually proposing a fix like this would require more work]
