### ISSUE TITLE
IPVS flaky test gce

### ISSUE THREAD

**Issue by aroradaman** [kubernetes/kubernetes#118233]
### Which jobs are flaking?

pull-kubernetes-e2e-gci-gce-ipvs

### Which tests are flaking?

[It] [sig-network] LoadBalancers should be able to preserve UDP traffic when server pod cycles for a LoadBalancer service on the same nodes 

### Since when has it been flaking?

known flake, documenting it here.

### Testgrid link

https://testgrid.k8s.io/sig-network-gce#presubmit-network-ipvs,%20google-gce

### Relevant SIG(s)

/sig network
/area ipvs

**Comment by thockin** [comment]
Any updates on this?

**Comment by carlory** [comment]
sorry, I have no idea about it. 

/unassign

**Comment by uablrek** [comment]
### The test(s) and what goes wrong

This issue report "...the same nodes" but also the similar test "...on different nodes" fails in the same way. The tests goes like this:

1. A UDP service is created with "type:LoadBalancer"
2. Wait until a loadBalancerIP is assigned
3. Start sending UDP packets to the service in 1s interval **with a fixed source-port**
4. Create _one_ endpoint POD
5. Wait until a reply is received, which should contain the POD hostname. **This is where it fails!**
6. Start a second endpoint POD on the same or a different node (the two test cases)
7. Delete the first endpoint POD
8. Verify that the second now receives the traffic by checking the "hostname" in the reply packets

_It should be noted that it is UDP traffic to the first endpoint POD that fails_

### Status so far

The focus has been on invalid conntrack entries, which has been fixed in a several PRs on both proxiers and recently been unified in common code in https://github.com/kubernetes/kubernetes/pull/116171.

UDP traffic may be sent:
1. Before the loadBalancerIP is configured on the node by `kube-proxy`
2. When the loadBalancerIP is configured on the node by `kube-proxy` but before any endpoint exist

Or at any point during on-going reconfiguration. A scenario is described in https://github.com/kubernetes/kubernetes/pull/118844#issuecomment-1607964288, but this is fairly simple to [test manually](https://github.com/kubernetes/kubernetes/pull/118844#issuecomment-1608269856), and it seem to work.

@aroradaman has also found a possible correlation between failures and traffic entering on a node where the endpoint POD is **not** running. Test made with "externalTrafficPolicy:Local" which seem to fix the problem in https://github.com/kubernetes/kubernetes/pull/118938

**Comment by uablrek** [comment]
Inspired by https://github.com/kubernetes-sigs/cloud-provider-kind by @aojea I realized that the only thing needed to run these tests on any local cluster (not necessarily KinD) is to allocate loadBalancerIP's and have a working route to those addresses. This can be done with `metallb` or, as in my case, a simple loadBalancerIP allocator and a static route. I have 4 K8s nodes and a static route to one of them, so there should be a 1/4 probability that traffic enters a local node (in theory).

I can now run both tests in ~8s and can use `--repeat` to `ginkgo`. I have executed the 2 tests 100 times without any error. This does not mean that there is no fault in K8s, but that the problem only occurs on GCE. It can be a problem in the environment, or for instance that the timing in GCE clusters exposes a K8s bug.

**Comment by aroradaman** [comment]
@uablrek I too struggled to reproduce the bug using metallb/cloud-provider-kind locally. 
I strongly think it is related to IPVS proxier as same test passes every time in same environment for IPTables proxier. 
I'm trying to figure out a solution, will keep you posted.

**Comment by aroradaman** [comment]
> It should be noted that it is UDP traffic to the first endpoint POD that fails

@uablrek I have seen some cases where the test fails to connect to second pod.
(https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/119010/pull-kubernetes-e2e-gci-gce-ipvs/1676237227102834688#1:build-log.txt%3A2331)

**Comment by uablrek** [comment]
> @uablrek I have seen some cases where the test fails to connect to second pod.
(https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/119010/pull-kubernetes-e2e-gci-gce-ipvs/1676237227102834688#1:build-log.txt%3A2331)

The test points at this line:

https://github.com/kubernetes/kubernetes/blob/a9a7a3730e8c834a7ea2738c44aeb67549f5dc15/test/e2e/network/loadbalancer.go#L1158

which fails because there are no K8s nodes available. Which seems weird!

**Comment by aroradaman** [comment]
> The test points at this line:

@uablrek  I added some debugging steps in the test case, the test fails for my branch at this line:
https://github.com/kubernetes/kubernetes/blob/27d1ab0aaa62db817063a725493801e59f1c3117/test/e2e/network/loadbalancer.go#L1158

**Comment by pacoxu** [comment]
It still flakes in https://testgrid.k8s.io/sig-release-master-informing#gce-master-scale-correctness.

**Comment by aojea** [comment]
> It still flakes in https://testgrid.k8s.io/sig-release-master-informing#gce-master-scale-correctness.

let's track this in https://github.com/kubernetes/kubernetes/issues/122286

**Comment by pacoxu** [comment]
> > It still flakes in https://testgrid.k8s.io/sig-release-master-informing#gce-master-scale-correctness.
> 
> let's track this in #122286

This test is not flake since 02-17.

/close
