### ISSUE TITLE
scheduler: add nodeAnnotationsChanged event to trigger rescheduling

### ISSUE THREAD

**Issue by amewayne** [kubernetes/kubernetes#118369]
### What happened?

Due to limited character space, I've stored additional information in annotations on nodes. My custom scheduling plugins read these annotations to schedule Pods. However, when a Pod fails to be scheduled on a node, I want it to be removed from the Unschedulable queue. This can be achieved by modifying the annotations of the node, allowing the Pod to be rescheduled.

Unfortunately, the eventHandler of the scheduler only supports five types of node events, and it does not include the nodeAnnotationsChanged event. Consequently, I am currently unable to trigger rescheduling by changing the annotations of nodes.

/sig scheduling

### What did you expect to happen?

Unschedulable pods will be rescheduled after annotations of nodes changed.

### How can we reproduce it (as minimally and precisely as possible)?

None

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by sanposhiho** [comment]
It's more like a new feature, not bug because it doesn't lead to any bad behavior on the upstream.

/remove-kind bug
/kind feature

**Comment by kerthcet** [comment]
My concern is node annotation is arbitrary, changing a node annotation doesn't imply a pod is schedulable. But for other events, like node labels, node taints, they're the constraints we consider in scheduling. They're different, I'm afraid this will lead to invalid scheduling attempts.

Who is responsible for change the annotations in you scenario?

**Comment by sanposhiho** [comment]
> They're different, I'm afraid this will lead to invalid scheduling attempts.

This enhancement has no impact on the in-tree plugins, right? 
Only (custom) plugins, that want to reschedule the node annotation change, will register the event to EventsToRegister.

**Comment by amewayne** [comment]
> Who is responsible for change the annotations in you scenario?
I have a controller capable of modifying node annotations to indicate node's current availability. And my custom plugins need to be aware of these changes.

**Comment by kerthcet** [comment]
> This enhancement has no impact on the in-tree plugins / upstream scheduler, right?

I guess we can still be impacted when scheduling pod failed because of no fit node rather than failed by the plugin. see https://github.com/kubernetes/kubernetes/blob/34abd36e88e50d913af9413f9353515deb7f09d4/pkg/scheduler/internal/queue/scheduling_queue.go#L778-L780

> I have a controller capable of modifying node annotations to indicate node's current availability

Can we predict whether the pod is schedulable before running into scheduling cycle via the node annotations, then we can leverage the preEnqueue extension point since you already have a external controller. https://kubernetes.io/blog/2022/12/26/pod-scheduling-readiness-alpha/

**Comment by amewayne** [comment]
> This enhancement has no impact on the in-tree plugins / upstream scheduler, right?

The concerns raised by @kerthcet make sense to me.

In my understanding, most in-tree plugins will classify the event `nodeAnnotationsChanged` as an `Update` event.

https://github.com/kubernetes/kubernetes/blob/a8d40a2f2521dd473028f432cacdb10819754e4e/pkg/scheduler/framework/types.go#L61

**Comment by sanposhiho** [comment]
> I guess we can still be impacted when scheduling pod failed because of no fit node rather than failed by the plugin. 

No. When no fit Pod, UnschedulablePlugins will have the plugin rejected the Pod. (e.g., all nodes don't have enough capacity, UnschedulablePlugins has noderesourcefit. all nodes don't satisfy node affinity, UnschedulablePlugins has nodeaffinity)
`len(pInfo.UnschedulablePlugins) != 0` is a rare case like plugins other than PreFilter/Filter returns non-success. I don't think we should care about it.

**Comment by sanposhiho** [comment]
> most in-tree plugins will classify the event nodeAnnotationsChanged as an Update event.

But, this is a good point, I think we should refactor all plugins that register `Update` event with `Node` to have a specific Node update event.
For example, [node affinity](https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/framework/plugins/nodeaffinity/node_affinity.go#L86). It should have `UpdateNodeLabel` with `Node` instead of `Update`

**Comment by kerthcet** [comment]
> No. When no fit Pod, UnschedulablePlugins will have plugin(s) rejected the Pod

- 1) One possibility is Reserve Plugin, I added the capability here https://github.com/kubernetes/kubernetes/pull/118529
-  2) Another possibility is PreFilter, but not because failed by the plugin, but no fit node exists https://github.com/kubernetes/kubernetes/blob/8aeea9c1b818825d3f01afe1c1c5907e6d76c515/pkg/scheduler/framework/runtime/framework.go#L665-L671

Have no idea whether we have other places, I guess no. But yes, this only impacts unschedulable pods has no failed plugins.

**Comment by kerthcet** [comment]
> For example, [node affinity](https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/framework/plugins/nodeaffinity/node_affinity.go#L86). It should have UpdateNodeLabel with Node instead of Update.

I think this is for intended, like 
1. 1) we have a plugin failed by nodeAffinity
2. 2) we add a new node
3. 3) we receive the node add event, but because node not ready, we failed by nodeTaint plugin as `nodeNotReady`
4. 4) node become ready, we get the node update event, but dismatch with nodeAffinity registered event (if we registered with UpdateNodeLabel event)
5. 5) pod will not be moved to the active or backoff queue

**Comment by kerthcet** [comment]
weigh in @alculquicondor for advices as whether this is a good idea to take nodeAnnotations as a new event. As I know, some plugins will read the embedded prometheus metrics in node annotations for scoring. At least we should mitigate the impacts.

**Comment by kerthcet** [comment]
If we have no performance problems, I think it's ok to take nodeAnnotations into consideration.

**Comment by alculquicondor** [comment]
Wouldn't this be solved with @sanposhiho's proposal on ClusterEventWithHint? #117844

If so, I prefer we leave the existing code as-is.

**Comment by alculquicondor** [comment]
whatever we do here, we wouldn't back port, so I think #117844 is the right move forward.

**Comment by sanposhiho** [comment]
We put too many stuff here. Let me summarize each:

### 1. change node `Update` to a specific `UpdateXXXX` event

Born from https://github.com/kubernetes/kubernetes/issues/118369#issuecomment-1579851665

[The last comment](https://github.com/kubernetes/kubernetes/issues/118369#issuecomment-1581140381) from @kerthcet is right. But, that's the problem with preCheck. (Some preCheck depends on some in-tree plugins' logic and it affects badly to other plugins enqueueing https://github.com/kubernetes/kubernetes/issues/110175)
The preCheck is removed after https://github.com/kubernetes/kubernetes/pull/117844 is completed. After preCheck is removed, https://github.com/kubernetes/kubernetes/issues/118369#issuecomment-1581103551 will be the correct behavior. So, we can do the optimization that changes node `Update` to a specific `UpdateXXXX` event. 

### 2. plugin failed in `Reserve` isn't registered in unschedulable plugins.

will be fixed in: https://github.com/kubernetes/kubernetes/pull/118529

### 3. If PreFilter's PreFilterResult filter out all Nodes, no unschedulable plugin is registered

It's kind of rare case, but I feel we need to have some improvement like https://github.com/kubernetes/kubernetes/issues/118369#issuecomment-1581129204

---

I'd say (2) and (3) are kind of rare cases. So, the blocker here is (1). (And, (1) is blocked by the removal of preCheck, which is blocked by https://github.com/kubernetes/kubernetes/pull/117844.)
As my conclusion, it's safer to add `nodeAnnotationsChanged` after (1) is done so that we can make sure the performance won't be affected badly.
@kerthcet what do you think?

**Comment by alculquicondor** [comment]
Instead, can we just keep an event for "node updated", then individual plugins can decide whether a annotations change is worth requeuing or not?

**Comment by sanposhiho** [comment]
Yes, (1) can be replaced with that idea. But, I'd say changing to a specific `UpdateXXXX` is slightly better because the scheduling queue could filter out some Node update events without executing the hint functions.

**Comment by kerthcet** [comment]
If rescheduling can be triggered with precise events, that would be great. I haven't revisit https://github.com/kubernetes/kubernetes/pull/117844 since last time, I'll take a look again.

**Comment by alculquicondor** [comment]
Since we are missing an event for NodeUpdated, can we add it?

And in future releases we can get rid of some fine-grained events.

**Comment by kerthcet** [comment]
Since we will **add hintFuncs for all in-tree plugins**, so I think it's ok to add nodeAnnotationsChanged event now, we can filter out unrelated events in hitFuncs. Any other concerns? cc @alculquicondor  @sanposhiho 

> And in future releases we can get rid of some fine-grained events

Prefer to keep them as people can register fine-gained events instead a general `nodeUpdate` event.

**Comment by alculquicondor** [comment]
If by "now" you mean v1.30, then I'm ok with that.
