### ISSUE TITLE
The built-in "editor" role doesn't have access to execute operations of ephemeral containers

### ISSUE THREAD

**Issue by Shuanglu** [kubernetes/kubernetes#118565]
### What happened?

The built-in "editor" role doesn't have access to execute operations of ephemeral containers. Is this expected?
https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/auth/authorizer/rbac/bootstrappolicy/policy.go#L301

### What did you expect to happen?

"editor" role has access to execute operations of ephemeral containers

### How can we reproduce it (as minimally and precisely as possible)?

create a rolebinding under a namespace to associate a user/serviceaccount with the "edit" role. The user/serviceaccount doesn't have access to execute `kubectl debug xxx`

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.2", GitCommit:"5835544ca568b757a8ecae5c153f317e5736700e", GitTreeState:"clean", BuildDate:"2022-09-21T14:33:49Z", GoVersion:"go1.19.1", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.12-gke.500", GitCommit:"fa2714567d7451b5e32541c10119d1246730c197", GitTreeState:"clean", BuildDate:"2023-03-23T11:35:05Z", GoVersion:"go1.19.7 X:boringcrypto", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
GKE
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by liggitt** [comment]
/remove-kind bug
/kind documentation

This was intentional during the design of the feature, see https://github.com/kubernetes/enhancements/blob/master/keps/sig-node/277-ephemeral-containers/README.md#security-considerations

We cannot automatically assume cluster administrators have configured their admission policies to guard the ephemeral container subresource, so cannot automatically grant that to pod authors by including it in the edit role.

Documentation at https://kubernetes.io/docs/concepts/workloads/pods/ephemeral-containers/ could be improved to describe how to add the permission to editors in a particular cluster using an aggregated role (https://kubernetes.io/docs/reference/access-authn-authz/rbac/#aggregated-clusterroles)

cc @verb

**Comment by verb** [comment]
Assigning this to myself so I can make sure it gets done, but anyone with spare cycles should feel free to grab it.

/assign
