### ISSUE TITLE
Flaky: TestDQ_always_pop_earliest_deadline

### ISSUE THREAD

**Issue by davidopp** [kubernetes/kubernetes#11857]
Example failure at 
https://app.shippable.com/builds/55b327486572ba0c00576d31

```
--- FAIL: TestDQ_always_pop_earliest_deadline (23.77 seconds)
delay_test.go:256: Expected delay-prority of 1s got instead got 2s
FAIL
coverage: 64.9% of statements
FAIL	github.com/GoogleCloudPlatform/kubernetes/contrib/mesos/pkg/queue	92.958s
```

@karlkfi

**Comment by karlkfi** [comment]
Effectively the same reason as #11857 tho they're two different tests.
We tried to diagnose on Friday and were unable to duplicate or find an easy fix. The tests are time-based because the DelayQueue is time-based. The current implementation doesn't allow for deterministic tests. We're likely going to have to rewrite to improve testing.

**Comment by lavalamp** [comment]
Can we disable these tests until a fix is found? This is causing a lot of false negatives from shippable.

**Comment by mikedanese** [comment]
Dup of #11821

**Comment by mikedanese** [comment]
Oops different test never mind.

**Comment by wojtek-t** [comment]
@jdef @karlkfi - what's the status of it? Is it fixed? If not, is someone looking into it?

**Comment by wojtek-t** [comment]
@sttts - what about this one?

**Comment by sttts** [comment]
Closing, followed up by https://github.com/mesosphere/kubernetes-mesos/issues/432
