### ISSUE TITLE
Add a jitter when requeuing HPA objects

### ISSUE THREAD

**Issue by mengqiy** [kubernetes/kubernetes#118788]
### What would you like to be added?

A jitter should be added when requeuing HPA objects.

### Why is this needed?

Currently HPA controller list pods for each HPA object every 15s by default. These calls are always made at the same second. These calls always require quorum read from etcd.
As a consequence, APIServer and etcd are stressed a lot by these calls during a short period of time. e.g. Etcd needs to send all the pods to apiserver and it will stress the network bandwidth. APIServer and etcd memory usage will be high when processing multiple large list calls.
Ideally these call should be spread over the 15s window. Adding a jitter can help mitigate this problem.

**Comment by mengqiy** [comment]
It seems we can simply change [`enqueueHPA`](https://github.com/kubernetes/kubernetes/blob/9e0569f2ed3934060fabe51be4e15232bbea3877/pkg/controller/podautoscaler/horizontal.go#L227-L230) to add jitter behavior.

**Comment by killshotrevival** [comment]
Hey @mengqiy , If we add a random delay under `processNextWorkItem` from 1 to 10 seconds, then how it would be?? This will create a good amount of chance that all the processing will not work at the same time 🤔

**Comment by mengqiy** [comment]
[`HorizontalController.queue`](https://github.com/kubernetes/kubernetes/blob/9e0569f2ed3934060fabe51be4e15232bbea3877/pkg/controller/podautoscaler/horizontal.go#L107) supports a [`DelayingInterface`](https://github.com/kubernetes/kubernetes/blob/2802bbce14ca32cddbd0d0567cd33fb435f445e6/staging/src/k8s.io/client-go/util/workqueue/rate_limiting_queue.go#L23) interface. We can leverage its `AddAfter` method.
This is a common pattern used in controller. e.g. controller-runtime also uses it [here](https://github.com/kubernetes-sigs/controller-runtime/blob/a784ee78d04bdf216006adfbc313328a0aded88a/pkg/internal/controller/controller.go#L325C31-L332).

**Comment by Shubham82** [comment]
cc @pbetkier @mwielgus 
your thoughts on this?

**Comment by pbetkier** [comment]
> Currently HPA controller list pods for each HPA object every 15s by default. These calls are always made at the same second.

HPA controller **uses informers for Pods**. So there should be no direct calls from the reconciliation loop, only background watches for changes. The only direct calls from the reconciliation loop are to API server's scale subresource and to the metrics API.

If you observe direct GET calls instead of watch requests then that's a problem we need to debug. Please attach more debug data.

**About HPA processings**

HPAs are processed sequentially (or with a limited a parallelism after #108501). Processing of HPAs with resource metrics only takes usually 5-10ms. Processing time of HPAs with custom/external metrics depends on the latency to user-defined metrics backend, 500ms - 2s are not uncommon.

This is to say that processings happen at the same seconds only if the number of HPAs is rather low. Users of large k8s clusters often have 2000 HPAs or more, and with numerous custome/external metrics HPAs it takes 5 minutes or more to reconcile all HPAs. So if the cluster is large, the HPA processings spread by themselves.

**Spreading HPA processings**

Adding a delay (meaning a sleep?) to processing code is a bad idea. HPA controller already cannot keep up with processing all HPAs within 15s when the number of HPAs is large and they have customer/external metrics defined.

We could spread the work with `AddAfter` jitter I guess. But I think the best way would be to define a rate-limit for API server calls and let HPA controller slow down to the required rps limit.

**Comment by kwiesmueller** [comment]
Would https://kubernetes.io/docs/concepts/cluster-administration/flow-control/ help with limitting the load instead of adding something dedicated to HPA?
