### ISSUE TITLE
Come up with a clear story for attaching/detaching PD semantics

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#11879]
The current implementation of PD attach/detach operations can lead to races when using them - see #11873 for an example.

 In particular we should define the desired behavior in situations like "a pod with PD attached in RO mode is running and we schedule another pod with the same PD attached in RW mode"

@saad-ali for more details and his thoughts about it

**Comment by saad-ali** [comment]
To sum up this issue: While debugging #11873 I noticed that the current volume attach/detach code doesn't keep track of whether a PD was attached as read-only or read-write. Therefore we can run in to situations where a pod is created in one mode, deleted, but before the orphan volume loop picks up and tries to detach it, a new pod using the same PD with a different mode is created: now the PD will not be detached by the orphan volume loop (since it is still in use) but it is attached in the incorrect mode.

I spoke with @thockin offline. We agree that a potential fix would be storing additional metadata along with the global PD mount to identify the mode, and using that to ensure that RO and RW attaches are handled correctly.

**Comment by thockin** [comment]
Superceded by https://github.com/kubernetes/kubernetes/issues/20262 and https://github.com/kubernetes/kubernetes/issues/21931
