### ISSUE TITLE
TCP Conntrack entries remain in stale after rebooting worker node

### ISSUE THREAD

**Issue by adilGhaffarDev** [kubernetes/kubernetes#118814]
### What happened?

We have NBI traffic impact on worker node after node reboot. TCP Conntrack entries remain in stale after rebooting worker node hosting backend NBI POD.

### What did you expect to happen?

Initial analysis indicating there is some issue with kube-proxy/conntrack handling when endpoint IP changed. 
kube-proxy should delete the conntrack entry on endpoint change notification.

### How can we reproduce it (as minimally and precisely as possible)?

- Create cluster with 2 nodes, n1 and n2
- Enable ipvs mode:
```
      ipvs:
      excludeCIDRs: null
      minSyncPeriod: 0s
      scheduler: ""
      strictARP: true
      syncPeriod: 30s
      tcpFinTimeout: 2m0s
      tcpTimeout: 15m0s
      udpTimeout: 5m0s
    kind: KubeProxyConfiguration
    metricsBindAddress: '[::1]:10249'
    mode: ipvs
```
- Create 2 pods A and B running any TCP test service
- Create LoadBalancer service with externalTrafficPolicy Cluster
- Create TCP connections through the service ip: " "
- Active connections can be seen on both nodes:
```
#node1
sudo ipvsadm -ln -t 10.143.229.6:443
Prot LocalAddress:Port Scheduler Flags
  -> RemoteAddress:Port           Forward Weight ActiveConn InActConn
TCP  10.143.229.6:443 rr
  -> 192.168.62.230:8443          Masq    1      1          0         
  -> 192.168.171.42:8443          Masq    1      0          0

#10.143.229.6 is LB service ip and 192.168.62.230,192.168.171.42 tcp pod ips

sudo conntrack -L | grep 10.139.16.223
tcp      6 431999 ESTABLISHED src=10.139.16.223 dst=10.143.229.6 sport=51906 dport=443 src=192.168.62.230 dst=192.168.40.192 sport=8443 dport=35783 [ASSURED] mark=0 use=1

```
```
#node2
sudo ipvsadm -ln -t 10.143.229.6:443
Prot LocalAddress:Port Scheduler Flags
  -> RemoteAddress:Port           Forward Weight ActiveConn InActConn
TCP  10.143.229.6:443 rr
  -> 192.168.62.230:8443          Masq    1      1          0         
  -> 192.168.171.42:8443          Masq    1      0          0

#10.143.229.6 is LB service ip and 192.168.62.230,192.168.171.42 tcp pod ips

sudo conntrack -L | grep 10.139.16.223
tcp      6 431999 ESTABLISHED src=10.139.16.223 dst=10.143.229.6 sport=52098 dport=443 src=192.168.62.230 dst=192.168.150.128 sport=8443 dport=30313 [ASSURED] mark=0 use=1

```
- Reboot node 1, one of the pod ip is changed from192.168.62.230 to 192.168.62.204, and we have stale entry:
```
#node1
sudo ipvsadm -ln -t 10.143.229.6:443
Prot LocalAddress:Port Scheduler Flags
  -> RemoteAddress:Port           Forward Weight ActiveConn InActConn
TCP  10.143.229.6:443 rr
  -> 192.168.62.204:8443          Masq    1      0          0         
  -> 192.168.62.230:8443          Masq    0      1          0                              <=== stale entry
  -> 192.168.171.42:8443          Masq    1      0          0

sudo conntrack -L | grep 10.139.16.223
tcp      6 431634 ESTABLISHED src=10.139.16.223 dst=10.143.229.6 sport=52098 dport=443 src=192.168.62.230 dst=192.168.150.128 sport=8443 dport=30313 [ASSURED] mark=0 use=1
```
```
#node2
sudo ipvsadm -ln -t 10.143.229.6:443
Prot LocalAddress:Port Scheduler Flags
  -> RemoteAddress:Port           Forward Weight ActiveConn InActConn
TCP  10.143.229.6:443 rr
  -> 192.168.62.204:8443          Masq    1      0          0         
  -> 192.168.62.230:8443          Masq    0      1          0         
  -> 192.168.171.42:8443          Masq    1      0          0

sudo conntrack -L | grep 10.139.16.223
tcp      6 272 ESTABLISHED src=10.139.16.223 dst=10.143.229.6 sport=51906 dport=443 [UNREPLIED] src=192.168.62.230 dst=192.168.40.192 sport=8443 dport=13223 mark=0 use=1
```

### Kubernetes version

<details>

v1.27.1 
</details>

### Cloud provider

<details>
 kubeadm cluster 
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by aojea** [comment]
/area ipvs

> tcp      6 272 ESTABLISHED src=10.139.16.223 dst=10.143.229.6 sport=51906 dport=443 [UNREPLIED] src=192.168.62.230 dst=192.168.40.192 sport=8443 dport=13223 mark=0 use=1

what is the problem? is this affecting connectivity somehow? unless you send a packet with the same tuple you are not going to hit that entry and eventually it will timeout

**Comment by RajathNR** [comment]
@aojea  Hi,
on rebooting the worker node, the endpoint IP changed from 192.168.62.230 to 192.168.62.204. still, we have conntrack entry for the old endpoint (192.168.62.230) in the ESTABLISHED state impacting traffic for more than 10mins.

**Comment by uablrek** [comment]
@aroradaman You have synchronized conntrack handling for proxy-mode iptables and ipvs, right? If so, in which release is it included (if any)?

**Comment by aroradaman** [comment]
@uablrek yes, https://github.com/kubernetes/kubernetes/pull/116104 was merge on 19th April and was part of 1.28 release.

Conntrack cleaning is unified now, so it is not an ipvs-only problem.

**Comment by uablrek** [comment]
This can't be reproduced as described, there must be more details. I have created a cluster with 2 worker nodes, and server (replicas=2) and a (tcp) service. I do 2 tcp connects from a source outside the cluster.

Is the connect initiated from a source outside the cluster? I.e. is the address 10.139.16.223 external?

If so, I _assume_ ECMP is used?

This because if I route incoming traffic to _one node only_ (say node1), or if ECMP happens to select the same target for the 2 connects, that node have active 2 ipvs connections and 2 conntrack entries, but the other node _have none of these_ (which is the expected case). In your example the two nodes have on connection each, which indicates that incoming requests goes to both nodes, e.g. with ECMP.

I can configure ECMP and try-and-error until my 2 connects are routed to different nodes, then it looks similar to your example. But if I reboot a node with "reboot", the connection to the pod on that node is immediately closed at the external source. When the rebooted node comes back up, it is empty. No ipvs entries or conntrack entries.

**Comment by uablrek** [comment]
I think I can recreate something similar, but only that a connection is black-holed, not that new connects fails (they work fine).

#### Create a cluster

1. Start a cluster with 2 workers, and a daemonset or deployment/replicas=2 so one POD (endpoint) is started on each node
2. Create a service with type:LoadBalancer (and assign/get a loadbalancer-ip)
3. Setup ECMP routing from external sources to the loadbalancer-ip to the 2 worker nodes

#### Setup 2 tcp connection that enters one node and forwards to a POD _on the other node_

1. Connect from an external source to the loadbalancer-ip
2. Check with "ipvsadm -Ln" that the endpoint is on the other node. If not, disconnect and goto 1.
3. Repeat this until you have 2 tcp connection that enters each node and forwards to an endpoint on the other node

#### Reset one worker node

1. **Reset** (_not reboot_!) one worker node
2. Check "conntrack -L" on the remaining node. The ESTABLISHED entry to the endpoint on the rebooted (with reset) node is still there.

#### Result

When the node is reset _one_ (of the 2) connections is closed as soon as any data is sent on it (including tcp-keep-alive).

**The other connection however is black-holed**. Meaning that it does not get any response from it's peer, nor any RST or FIN. This state may remain for a long time. (for a go-program, I would expect ~1m since go set a tcp-keep-alive to 15s by default)

New connects are successful.

If the worker node is rebooted with "reboot", the kernel will clean up connections and the conntrack entry (on the other node) goes to FIN_WAIT, and both connection are closed on an attempt to send data.

**Comment by uablrek** [comment]
@adilGhaffarDev @RajathNR The way I recreated a problem similar to the described is _way more_ complex than your description in the issue, that basically indicates that this always happen. Is it the same problem?

If it is, then this is not a bug in K8s IMHO. It is inconvenient that connections are black-holed, but new connects works. But I must ask others about it

**Comment by uablrek** [comment]
The problem described in https://github.com/kubernetes/kubernetes/issues/118814#issuecomment-1604312224 (above) exist on the master branch, and is the same for proxy-mode=iptables

/remove area-ipvs

**Comment by uablrek** [comment]
/remove-area ipvs

:cursing_face:

**Comment by aojea** [comment]
> @aojea Hi, on rebooting the worker node, the endpoint IP changed from 192.168.62.230 to 192.168.62.204. still, we have conntrack entry for the old endpoint (192.168.62.230) in the ESTABLISHED state impacting traffic for more than 10mins.

@adilGhaffarDev  can you be more specific on how is impacting traffic and which type of traffic?

**Comment by aroradaman** [comment]
@adilGhaffarDev we don't clean conntrack entries for TCP protocol, being stateful the connection should be terminated itself either by timeout or keep-alive probes. 

As @uablrek mentioned default keep-alive for go program is 15 sec, and the connection should be terminated after that.  

More details on the connection details would help to narrow down the problem. Meanwhile can you try reducing the keep-alive timeout, or set a low value if it is disabled ?

**Comment by RajathNR** [comment]
> > @aojea Hi, on rebooting the worker node, the endpoint IP changed from 192.168.62.230 to 192.168.62.204. still, we have conntrack entry for the old endpoint (192.168.62.230) in the ESTABLISHED state impacting traffic for more than 10mins.
> 
> @adilGhaffarDev can you be more specific on how is impacting traffic and which type of traffic?

The traffic workflow:
DTG (Data traffic generate) —--- send POST http request ----> (LoadBalance) ---- forward http request --> backend application 

because of stale entry in conntrack, DTG still sends the request to the old connection which has not exist but it still marks an active connection on ipvs.

**Comment by aojea** [comment]
> because of stale entry in conntrack, DTG still sends the request to the old connection which has not exist but it still marks an active connection on ipvs.

I see, the problem here is that the connection is not completely terminated (FIN or RST packets) and the intermediate devices does not clean the entries because are not aware of that. kube-proxy does not clean up conntrack TCP entries for several reasons https://github.com/kubernetes/kubernetes/issues/104098 , but independently of that, this can happens to any TCP application that goes through different middle boxes that need to keep state.

Ssh solves this problem using keepalives, and http has the same ping mechanism to detect that the connection is alive or shutting down if is not.

The problem here is that we need to "break" the existing connection so it can retry and choose a new backend, or the client should be able to detect the connection is no longer available and retry

**Comment by uablrek** [comment]
> We are not seeing this behavior, conntrack entry remains in ESTABLISH state for a long time. connection at the client(NBI traffic generate) side is not getting reset.

Yes, it is there. There may be several conntrack entries that are "stale" in some way, but they are usually harmless and will eventually timeout. **But what is the problem?**

Is your established connection black-holed (as I have described)?

Or, does new connects fail? If so, are you reusing the exact same source-port for new connections?

**Comment by RajathNR** [comment]
> > We are not seeing this behavior, conntrack entry remains in ESTABLISH state for a long time. connection at the client(NBI traffic generate) side is not getting reset.
> 
> Yes, it is there. There may be several conntrack entries that are "stale" in some way, but they are usually harmless and will eventually timeout. **But what is the problem?**
> 
> Is your established connection black-holed (as I have described)?
>  Yes,
> Or, does new connects fail? If so, are you reusing the exact same source-port for new connections?

New connections are not failing. But, the client is not able to realize the backend connection is broken...
source-port,  I don't think the exact same source port is used, the kernel will allocate a different source port...

**Comment by aojea** [comment]
> ut, the client is not able to realize the backend connection is broken...
> source-port, I don't think the exact same source port is used, the kernel will allocate a different source port

your connection is stuck, it has to be using the same source port or it will not hit the same conntrack entry ... if your client connect directly to kube-proxy and the conntrack entry does not exist it will not work too , because it will send an existing open connection to a new backend ...  it is an application client side problem, you have to use timeouts to detect this stale connections

**Comment by uablrek** [comment]
The connection is black-holed. This will happen if a node (vm or metal) is reset or power-off. As Antonio pointed out:

> this can happens to any TCP application that goes through different middle boxes that need to keep state.

This is a case that network programs must handle, it's not a bug in K8s.

/close
