### ISSUE TITLE
AWS: CloudFormation / make a self-contained and complete cloudformation template

### ISSUE THREAD

**Issue by jboelter** [kubernetes/kubernetes#11889]
I've started to make progress on this, with the goal being to be able to deploy a kubernetes cluster from a cloudformation template that has no dependencies on manually created or pre-existing AWS resources.  A second goal is to deploy multiple clusters in the same account w/o overlap or collisions.
- Add IAM role for master
- Add IAM role for node
- Add VPC
- Add --cloud-provider=aws to cmdline params
  ?

What other implications does this have on the aws cloud provider implementation? e.g. provider needs to discover 'itself' from the meta-data for creating load balancers and security groups.

**Comment by mikedanese** [comment]
@justinsb

**Comment by mariomarin** [comment]
@jboelter I've just finished #12346. It enables ELB creation from a cluster created with cloudformation.

If merged it will cover:

- Add IAM role for master
- Add IAM role for node
- Add --cloud-provider=aws to cmdline params

However, there is still plenty to do in order to match kube-up.sh

- Add VPC
- Create raid with ephemeral storage
- Pick docker storage (btrfs vs aufs vs others)
- Logging
- Monitoring
- Authentication

@justinsb Do you want to track the previous items in this issue like [a task list](https://github.com/blog/1375%0A-task-lists-in-gfm-issues-pulls-comments)? an issue per item?

I guess we should create a separate cloudformation template with a basic VPC, it's really hard to please everyone's needs about networking. 

P.S.: #9801 is stopping us to use an existing VPC for a kubernetes cluster.
