### ISSUE TITLE
[KMSv2] update KEP with the crypto changes

### ISSUE THREAD

**Issue by aramase** [kubernetes/kubernetes#118837]
ref: https://github.com/kubernetes/kubernetes/issues/118831

/sig auth
/triage accepted
/assign @aramase @enj
/milestone v1.28

**Comment by zelenushechka** [comment]
Hey @enj & @aramase, I'm Anhelina from the Bug Triage Release team 1.28 👋. I wanted to reach out to discuss its progress and ensure it's on track for the v1.28 release, considering the Code Freeze is coming up on [01:00 UTC Wednesday 19th July 2023 / 18:00 PDT Tuesday 18th July 2023](https://everytimezone.com/s/72ee8496). Could you please provide an update on the current status of the issue? Is it still planned for the v1.28 release? We are currently in Week 7, and the Code Freeze will be in effect by Week 9. If there's anything I can do to assist in resolving this issue, please let me know:)

**Comment by zelenushechka** [comment]
Week 9 update: Code Freeze is approaching!

Hey! We are currently in Week 9, and Code Freeze is just over a week away. It will begin at 01:00 UTC on Wednesday, 19th July 2023 / 18:00 PDT on Tuesday, 18th July 2023. **Is this issue on track for the 1.28 release?** Let me know if you need any assistance. :)

**Comment by furkatgofurov7** [comment]
@aramase hey,  Bug Triage Lead here 👋🏼

Can we close this issue as completed, since reference [PR](https://github.com/kubernetes/kubernetes/issues/118831) is already merged or it requires more changes? If latter, please keep in mind that, as communicated by Bug Triage Team in earlier weeks, Code Freeze deadline passed and unfortunately I have to move this issue to the next milestone.

**Comment by furkatgofurov7** [comment]
Moving out of the milestone due to inactivity of the issue

/milestone clear
