### ISSUE TITLE
NCC-E003660-XE9: Multiple Concerns with Network Policies

### ISSUE THREAD

**Issue by reylejano** [kubernetes/kubernetes#118983]
### NCC-E003660-XE9: Multiple Concerns with Network Policies
This issue was reported in the [Kubernetes 1.24 Security Audit Report](https://github.com/kubernetes/sig-security/blob/main/sig-security-external-audit/security-audit-2021-2022/findings/Kubernetes%20v1.24%20Final%20Report.pdf)

**Description**
In Kubernetes, `NetworkPolicy` objects provide a flexible manner to configure networking
restrictions on and between pods to provide isolation. However, their design and behavior
result in several drawbacks that significantly limit their applicability. In general, the
`networking.k8s.io/v1` `NetworkPolicy` type attempts to present a lowest common
denominator specification for traffic filtering. It is not, however, required that a CNI
implement any kind of support for network policies, and those that do tend to provide more
useful isolation features than are supported by the standard `NetworkPolicy` type.
Additionally, while network policies may be partially or fully unsupported, there is no
mechanism to determine if an applied `NetworkPolicy` will be enforced. Instead, it is left to
administrators to validate the intended behavior. In general, the risk of this facet of network
policy behavior is low given that production CNIs tend to support network policies.

Standard network policies, similar to other Kubernetes components, use additive access
controls, whereby a range or “entity” that is allowed cannot be disallowed. While this does not go so far as to enable ingress rules to override egress restrictions, it nonetheless significantly limits the usability of network policies by enabling accidental fail-open configurations. Furthermore, network policies are, in the general use case, effectively opt-in, as rule application is performed via label matchers. Should any lax network policy exist in a namespace, even one that is otherwise locked down with RBAC rules to prevent the creation or manipulation of network policies, any cluster user that can create or modify a pod, either directly or indirectly in that namespace, can modify pod labels in an attempt to be granted the additional access of the
matching network policy rules, such as to sensitive pods and services that otherwise cannot be directly accessed from within a cluster. As a result, without additional admission
controller validations to “enforce” pod labels in a secure manner, network policies can only
be considered to be granular to the namespace level and not the pod level, and the only
way to enforce a network policy across all pods in a namespace is to give it a wildcard
`podSelector` of `{}` . Such policies are referred to as “default policies”3 and are often
recommended as a security best practice, though generally only as a means of denying
traffic by default, and often without discussing the weaknesses of network policies or their
opt-in nature.

**Recommendation**
In the long term, the built-in Kubernetes `NetworkPolicy` type should be refocused or
deprecated in favor of an alternate approach to ingress and egress filtering focused
entirely on in-cluster traffic. As part of this, consider enabling stronger binding
mechanisms for pod selection and explicit Deny rules that can be used to ensure that pods
may not be able to gain access via label configuration abuse. Lastly, CNIs should be
required to provide admission controller webhooks that fully validate network policies, and
deny any that use unsupported features, including all `NetworkPolicy` objects if the CNI
does not support network policies. Alternatively, if not using a `ValidatingAdmissionWebhoo
k` object directly, CNIs could be required to implement a validating admission webhook
endpoint that a new core Kubernetes admission controller would detect and then route
NetworkPolicy objects to, propagating the response accordingly.

**Anything else we need to know?**
See umbrella issue [#118980](https://github.com/kubernetes/kubernetes/issues/118980) for current status of all issues created from these findings.
The vendor gave this issue an ID of NCC-E003660-XE9 and it was finding 2 of the report under the Security Architecture Review section.
The vendor considers this issue Low Risk.
To view the original finding, begin on page 12 of the [Kubernetes 1.24 Security Audit Report](https://github.com/kubernetes/sig-security/blob/main/sig-security-external-audit/security-audit-2021-2022/findings/Kubernetes%20v1.24%20Final%20Report.pdf)

**Test Environment**
Kubernetes 1.24.3

**Comment by thockin** [comment]
I'll respond more fully later, but I sort of disagree with this report.  Most of the cited weaknesses (IIUC) are by design and have reasons.  I have plenty of problems with NetPol, but these are not them.

**Comment by thockin** [comment]
> It is not, however, required that a CNI implement any kind of support for network policies

While this has sadly become vernacular, it is strictly incorrect.  CNI defines the pod-connectivity problem and nothing more.  It is common for network implementations (e.g. Calico, Cilium) to provide BOTH a CNI plugin *and* a NetworkPolicy implementation, but they are two distinct concepts.  Just a nit :)

> there is no mechanism to determine if an applied NetworkPolicy will be enforced

Agree - we tried to push a status, but there was zero uptake from implementations because their customers are not asking for it.  So we abandoned the KEP.

> a range or “entity” that is allowed cannot be disallowed ... it nonetheless significantly limits the usability of network policies by enabling accidental fail-open configurations

Can you expand on this?  NetworkPolicy is intentionally the purvey of namespace users.  If they "accidentally" over-specify a range or selector, either a) they find out and can fix it by changing the allow rule; or b) they do not find out about it and do nothing.  Neither scenario would be made better by the API supporting deny rules.

If the point is about cluster operators putting "guard rails" on what namespace users can do, that's covered by an entirely different API (AdminNetworkPolicy), which *does* support deny rules.

> network policies are, in the general use case, effectively opt-in

This is true, BUT:
1) it's somewhat common for cluster admins to drop a default policy in, which flips from default-allow to default-deny, forcing namespace users to conside NetworkPolicy
2) AdminNetworkPolicy will provide this explicitly 
3) There is an explicit provision in NetworkPolicy spec, which allows a network to have a default disposition that is default-deny:  "Traffic is allowed to a pod if there are no NetworkPolicies selecting the pod (and cluster policy otherwise allows the traffic)".

> as rule application is performed via label matchers. Should any lax network policy exist in a namespace, even one that is otherwise locked down with RBAC rules to prevent the creation or manipulation of network policies, any cluster user that can create or modify a pod, either directly or indirectly in that namespace, can modify pod labels in an attempt to be granted the additional access of the matching network policy rules, such as to sensitive pods and services that otherwise cannot be directly accessed from within a cluster

Any user who can manipulate pod labels in a namespace effectively owns the namespace.  NetworkPolicy cannot change that.  There are myriad things I can do to a pod if I have enough power to modify its labels.  I think this point is trying to assert that this is insecure, but it's entirely within the namespace, which is is already assumed to be trusted.

> network policies can only be considered to be granular to the namespace level and not the pod level

This is wrong.  Between namespaces, this is true, but that doesn't mean NetworkPolicy has no value for intra-namespace use - only that trusted actors are trusted.  For example, if I express a policy that pods labelled "role=be" can receive from pods labelled "role=fe" on port 80 (and everything else is denied implicitly), then a compromised FE can not translate horizontally to other FEs, nor can it access BEs except on port 80.  That's WAY better than not having the policy at all.  In general, the pods are NOT trusted actors, and do not have a ServiceAccount which can manipulate pod labels. 

> In the long term, the built-in Kubernetes NetworkPolicy type should be refocused or deprecated in favor of an alternate approach ... enabling stronger binding mechanisms for pod selection and explicit Deny rules that can be used to ensure that pods may not be able to gain access via label configuration abuse

NetworkPolicy is a developer-focused API.  It describes the graph of expected traffic for an application.  You're asking for AdminNetworkPolicy, which is specifically for admins, and is somewhat more sophisticated than NetworkPolicy.  Neither one is a substitute for the other.

**Comment by liggitt** [comment]
I agree with Tim's comments. After discussing with sig-network more broadly, would it make sense to close this as wontfix?

**Comment by aojea** [comment]
This has to be revisited taking into account Tim's comments , is taking some false assumptions and mixing some concepts , please reopen once this has been addressed

/close
