### ISSUE TITLE
addons/dns/README.md 404 error

### ISSUE THREAD

**Issue by davidwalter0** [kubernetes/kubernetes#11894]
There appears to be a broken link or missing page to: http://kubernetes.io/v1.0/cluster/addons/dns/README.md
to http://kubernetes.io/v1.0/

Dead link origin page: http://kubernetes.io/v1.0/docs/getting-started-guides/mesos.html

**Comment by thockin** [comment]
Can you clarify?  Where did you find this dead link?

**Comment by davidwalter0** [comment]
Dead link referenced from page: http://kubernetes.io/v1.0/docs/getting-started-guides/mesos.html

**Comment by RichieEscarez** [comment]
@krousey Can you please help? This file looks like none of the inline links were processed (converted to *.html from *.md) before publishing so all the links are broken. There are also links to the "addons" directory which does not live on kubernetes.io. Do links to "addons" get processed to absolute URLs that point back to the Kubernetes repo on GitHub?

**Comment by krousey** [comment]
@RichieEscarez The link processor only changes from .md to .html when the file it is linking to is in the docs/ or examples/ directory. Since this is in a cluster/ directory that doesn't exist, it didn't touch it. I think the right fix for this is to update the getting started guide to HEAD link through the redirector.

**Comment by jdef** [comment]
is there a change that we need to make to the guide? not sure what ".. update ... to HEAD link .." means.

/cc @karlkfi
