### ISSUE TITLE
How to choose the MASQUERADEIP of kube-proxy

### ISSUE THREAD

**Issue by mzzgaopeng** [kubernetes/kubernetes#119060]
When there are multiple IPv6 addresses on the host node, and the cluster uses the kube-proxy mode as IPVS, but the IPVS mode uses MASQUERADE

When this host accesses the outside world, after going through the IPVS proxy, the source IP becomes the first IPv6 address. Can this address be adjusted to the second address?

**Comment by mzzgaopeng** [comment]
<img width="939" alt="Snipaste_2023-07-04_16-38-04" src="https://github.com/kubernetes/kubernetes/assets/22125180/de7fc01a-3327-483d-9314-278ff155ef35">
After active SNAT through MASQUERADE, the source address is 2408:8220:247:dae0::1f, but I hope it is 2408:8220:247:dae0::100

**Comment by mzzgaopeng** [comment]
<img width="1147" alt="Snipaste_2023-07-04_16-41-42" src="https://github.com/kubernetes/kubernetes/assets/22125180/f750f333-f561-47e0-a6c3-50b92cf2b866">
It is correct when I directly access the PODIP of coredns

**Comment by FOWind** [comment]
>Masquerading is equivalent to specifying a mapping to the IP address of the interface the packet is going out, but also has the effect that connections are forgotten when the interface goes down. 

may be you can modify the router table or default gateway of the system.

**Comment by uablrek** [comment]
This is an outgoing connect initiated from inside a POD, or a DNS query (the trace shows proto=DNS). K8s is not involved in that case. It is other SW, usually the CNI-plugin (Calico, Cilium, Flannel, etc...), that setup masquerading. As @FOWind mentioned setting the route is an option, e.g:

```
ip -6 route replace default via <your-gw> src 2408:8220:247:dae0::100
```
This is not something K8s does either, nor the CNI-plugin. This is your own (or a cloud-provider) node setup.

Kube-proxy (ipvs or iptables) is only involved in _incoming_ traffic to a K8s service. For completeness I tested to assign 2 ipv6-addresses to a K8s node and accessed the NodePort of a service to both node addresses from an outside source. Both worked as expected.


Since this is not a K8s issue I close this. Please re-open if you have a different opinion.

/sig network
/close
