### ISSUE TITLE
[ValidatingAdmissionPolicy] Param authorization checked only at compile time

### ISSUE THREAD

**Issue by alexzielenski** [kubernetes/kubernetes#119112]
### What happened?

There is a check to ensure that the param provided to `ValidatingAdmissionPolicyBinding` is capable of being read by the user who created the admission policy when it is first validated:

https://github.com/kubernetes/kubernetes/blob/a88defe09a13dac704ce27d1072292a99e152cee/pkg/registry/admissionregistration/validatingadmissionpolicybinding/authz.go#L88-L108

This check is never performed again. At runtime, the controller makes use of a the loopback Kubernetes client to fetch params, possibly giving access to protected resources to CEL expressions:

https://github.com/kubernetes/kubernetes/blob/a88defe09a13dac704ce27d1072292a99e152cee/staging/src/k8s.io/apiserver/pkg/admission/plugin/validatingadmissionpolicy/controller.go#L303-L307

### What did you expect to happen?

I have a open questions about the security of this:

1. Is it sufficient for the only creator of the `Binding` to have access to the params to make use of it in CEL expressions defined by the `Policy`?
2. Should this check be performed every time params are used, to guard against changing permissions

### How can we reproduce it (as minimally and precisely as possible)?

N/A

### Anything else we need to know?

/cc @cici37 @benluddy @jpb

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by deads2k** [comment]
I don't think this is a bug.

Checking secondary access at the time of mutation provides confidence that the client making the change is allowed to make the change at the time they are making it.  Because clients are ephemeral (people move companies for instance) and we do not track ownership, there is no controller-based rechecking and expiry.  We tie some capabilities to a namespace (PSA for instance), but cluster-scoped ones are coupled to the cluster lifespan.

We make similar checks when pods are created for instance. We check them when created, but we don't delete pods (which can exfiltrate data) when the creator loses rights to a namespace.

**Comment by liggitt** [comment]
I agree this is not a bug.

Authz check at time of create / update of the policy / binding is sufficient.

/close
