### ISSUE TITLE
googleapi: Error 403: Insufficient Permission, insufficientPermissions

### ISSUE THREAD

**Issue by Andre-Freitas** [kubernetes/kubernetes#11923]
I'm trying to enable loadbalancer in my k8s (0.21.4) services but when i try to define gce in cloud-provider argument in my apiserver, controller-manager and kubelet's i'm having InsufficientPermissions in my logs. Where in documentation can i find how to configue my coreos master and nodes to be able to comunicate with google api and be able to use --cloud-provider=gce?

**Comment by goltermann** [comment]
We’re going through old support issues and asking everyone to direct your questions to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes). 

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases. 

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.
