### ISSUE TITLE
after upgrade from 0.18 to 1.0.1 kube-proxy no longer forwards the requests

### ISSUE THREAD

**Issue by dlyub** [kubernetes/kubernetes#11926]
Hello,

we have upgraded kubernetes cluster from version 0.18 to 1.0.1 by overlaying the binaries and updating configuration files with the new API version. RCs and services appear to be fine, however it appears that kube-proxy is having issues with forwarding requests to PODs. When the service is restarted I see the following messages in the log:

Jul 28 07:41:01 HOST docker[13241]: time="2015-07-28T07:41:01-05:00" level=info msg="GET /containers/kube-proxy.service/json"
Jul 28 07:41:01 HOST docker[13241]: time="2015-07-28T07:41:01-05:00" level=info msg="+job container_inspect(kube-proxy.service)"
Jul 28 07:41:01 HOST docker[13241]: no such id: kube-proxy.service
Jul 28 07:41:01 HOST docker[13241]: time="2015-07-28T07:41:01-05:00" level=info msg="-job container_inspect(kube-proxy.service) = ERR (1)"
Jul 28 07:41:01 HOST docker[13241]: time="2015-07-28T07:41:01-05:00" level=error msg="Handler for GET /containers/{name:.*}/json returned error: no such id: kube-proxy.service"
Jul 28 07:41:01 HOST docker[13241]: time="2015-07-28T07:41:01-05:00" level=error msg="HTTP Error: statusCode=404 no such id: kube-proxy.service"

Can someone please provide clues on what might have gone wrong?

**Comment by mbforbes** [comment]
+cc @cjcullen

**Comment by thockin** [comment]
What OS?  It looks like kube-proxy is not running - is kube-proxy running?

**Comment by goltermann** [comment]
We’re going through old support issues and asking everyone to direct your questions to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes). 

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases. 

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.
