### ISSUE TITLE
If you set `FLANNEL_NET` using environment variable, starting a new ubuntu cluster does not respect that variable

### ISSUE THREAD

**Issue by mamikonyana** [kubernetes/kubernetes#11947]
To reproduce
```sh
export FLANNEL_NET='172.19.0.0/16'
KUBERNETES_PROVIDER=ubuntu ./kube-up.sh
....
```
And the flannel net configuration is still the default 172.16.0.0/16 from the `config-default.sh`

**Comment by hw-qiaolei** [comment]
Because your export will only take effect on your current shell, and reconfDocker.sh is remotely executed on all nodes in function provision-minion() in util.sh. So add your export FLANNEL_NET line in reconfDocker.sh which defines options(including the FLANNEL network) before start docker will take effect, or add your export line in those remotely executed commands (must before sudo -b ~/kube/reconfDocker.sh) in function provision-minion() in util.sh before your run kube-up.sh.

**Comment by resouer** [comment]
@mamikonyana can you close this issue now?

**Comment by mamikonyana** [comment]
Sure, I though admins close issues.
