### ISSUE TITLE
Multi-numa periodics are not working

### ISSUE THREAD

**Issue by SergeyKanzhelev** [kubernetes/kubernetes#119601]
### Which jobs are failing?

See https://github.com/kubernetes/test-infra/pull/29717#issuecomment-1584967574

### Which tests are failing?

- Topology manager: runs green, but with zero tests: https://testgrid.k8s.io/sig-node-kubelet#kubelet-serial-gce-e2e-topology-manager
- CPU manager fails on initialization: https://testgrid.k8s.io/sig-node-kubelet#kubelet-serial-gce-e2e-cpu-manager
- Memory manager fails on initialization as well: https://testgrid.k8s.io/sig-node-kubelet#kubelet-serial-gce-e2e-memory-manager

### Since when has it been failing?

Since creation. Those are new periodics, pull jobs are working fine. First attempt to resolve it didn't succeeded so I am creating a bug to track it explicitly

### Relevant SIG(s)

/sig node
/cc @swatisehgal

**Comment by swatisehgal** [comment]
Thanks @SergeyKanzhelev for creating an issue to track this. I will further look into this.

/assign
/triage accepted
/priority important-soon

**Comment by mmiranda96** [comment]
For CPU manager test, node is not ready. This is the NodeCondition object reported in the logs:
```
NodeCondition{
    Type:Ready,
    Status:False,
    LastHeartbeatTime:2023-07-26 18:10:51 +0000 UTC,
    LastTransitionTime:2023-07-26 18:10:41 +0000 UTC,
    Reason:KubeletNotReady,
    Message:"container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized",
},
```

**Comment by SergeyKanzhelev** [comment]
can it be unspecified cgroup driver?

I cannot find anything strange in logs from a quick look.

**Comment by swatisehgal** [comment]
> For CPU manager test, node is not ready. This is the NodeCondition object reported in the logs:
> 
> ```
> NodeCondition{
>     Type:Ready,
>     Status:False,
>     LastHeartbeatTime:2023-07-26 18:10:51 +0000 UTC,
>     LastTransitionTime:2023-07-26 18:10:41 +0000 UTC,
>     Reason:KubeletNotReady,
>     Message:"container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized",
> },
> ```
> 
> It also seems to be the case for memory manager.

Thanks Mike, yeah I noticed this and thought the issue was due to mis-configuration.

> can it be unspecified cgroup driver?
> 
> I cannot find anything strange in logs from a quick look.

I thought so too and added additional node args in https://github.com/kubernetes/test-infra/pull/30072 but that didn't seem to help. Note that the cgroup driver is specified now.

Also, I just found that we don't have results for presubmit jobs with the new multi-NUMA setting:
https://testgrid.k8s.io/sig-node-presubmits#pr-kubelet-serial-gce-e2e-cpu-manager
https://testgrid.k8s.io/sig-node-presubmits#pr-kubelet-serial-gce-e2e-memory-manager
https://testgrid.k8s.io/sig-node-presubmits#pr-kubelet-serial-gce-e2e-topology-manager

These jobs are disabled by default and perhaps no one executed them yet.

I can't help but notice that the common demonimnator between these failing jobs is the image-config-file: [image-config-serial-multi-numa.yaml](https://github.com/kubernetes/test-infra/blob/master/jobs/e2e_node/image-config-serial-multi-numa.yaml) and could be the root cause here.

Next steps:

1. Create a dummy PR to test the above presubmit jobs to determine if they are failing as well.
2. Update the image config file or replace it with the older one to narrow down the cause of the issue.

Let me know if this seems reasonable and if you have more ideas.

**Comment by swatisehgal** [comment]
- [X] 1. Create a dummy PR to test the above presubmit jobs to determine if they are failing as well.
[PR ](https://github.com/kubernetes/kubernetes/pull/119655) was created and shows that the multi-numa presubmit jobs for cpu manager and memory manager jobs are failing as well. Topology Manager job passes (probably because tests are skipped) and that is consistent with what we see in case of periodic jobs. I don't see build logs for these jobs and the also noticed that the test results are not stored in testgrid. On inspection of job history we get following:
```
failed to get job history: failed to locate build data: failed to read pr-logs/directory/pull-kubernetes-node-kubelet-serial-memory-manager/latest-build.txt: creating reader for object pr-logs/directory/pull-kubernetes-node-kubelet-serial-memory-manager/latest-build.txt: storage: object doesn't exist
```
This would need some investigation.
- [ ] 2. Update the image config file or replace it with the older one to narrow down the cause of the issue.
TODO

**Comment by SergeyKanzhelev** [comment]
I like the plan. Ping me with PRs when needed

**Comment by swatisehgal** [comment]
The above PR(s) didn't seem to help, this issue is still being investigated.

**Comment by ffromani** [comment]
This seems a very promising fix: https://github.com/kubernetes/test-infra/pull/30545
