### ISSUE TITLE
Custom root Cgroup for a pod

### ISSUE THREAD

**Issue by patrickbcullen** [kubernetes/kubernetes#11986]
I looked in the source code, but it does not seem to be possible to specify the Cgroup in the Pod spec. I see that Kubelet allows for a custom root Cgroup, but it is applied to all Pods. I would like to have certain Pods startup in a different Cgroup so I can manage the CPU set independently from other Pods.

**Comment by thockin** [comment]
I'm not sure if we want to expose this as a feature - we want to use parent
cgroups for QoS management.  I think we'd do better to expose intentions
for QoS, and maybe make the implementation of policies more pluggable.

**Comment by mikedanese** [comment]
related to #5671. I think that kubelet wants  to create/be in control of that cgroup though

**Comment by patrickbcullen** [comment]
The use case is that some pods need different CPU affinity from other pods to avoid negative interactions. CPUsets in Cgroups are one way to deal with that.

**Comment by thockin** [comment]
We're deeply deeply familiar with the problem.  Handing control to users is
a short-term fix, and maybe we need to do it, but it's a long-term disaster
to try to mix user-managed stuff with auto-managed stuff

**Comment by natchaphon-r** [comment]
Is this feature still under consideration at all? If not, what would be the best way to achieve this behavior in k8s?
My use case:
|-- parent cgroup (memory limit 10 GB)
|---- cgroup1 (memory limit 2 GB)
|---- cgroup2 (memory limit 2 GB)
 ...
|---- cgroup10 (memory limit 2 GB)
- If all 10 child cgroups use exactly 1 GB (total of 10 GB which is the limit enforced by parent cgroup), then none of the them will be able to exceed 1 GB; otherwise, they will be oom-killed.
- In my use case, it is rare that a child cgroup will consume 1GB memory. Usually, their memory usage is around 200-300 MB. My cgroup structure allows a cgroup that temporarily needs more than 1 GB to "borrow" from other cgroups within the parent cgroup, provided that the total memory usage in parent cgroup is below 10 GB.
- Note that memory consumption in my system is unpredictable

**Comment by thockin** [comment]
I still think pod-level resources are a fun and interesting feature, but I
don't know if anyone is working on it yet.

**Comment by liorokman** [comment]
See https://github.com/kubernetes/enhancements/pull/1592
