### ISSUE TITLE
set memory limits for etcd & kube-apiserver

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#12002]
Our standard salt-based startup scripts start etcd & kube-apiserver without any memory limit. Etcd is capable of using enough memory to make the VM start swapping, and in that case it becomes just about impossible to ssh in and figure out what is wrong. We should set a memory limit so that only etcd OOMs instead of making the entire system OOM.

kube-apiserver should get the same treatment.

**Comment by dchen1107** [comment]
Set memory limits with rational number for etcd is tough since it is scaled based on number of nodes, number of pods, etc. And there is no mechanism for dynamically updates resource limits based on number of objects managed by a giving kubernetes cluster. This is the same issue for kube-system pods I raised before: @brendandburns @roberthbailey @a-robinson @bgrant0607 

Also even we can have a mechianism ready for update, we need to do measurements first, which is not easy today even all master components running as a container. Here is the issue I filed: #10891. To solve this, we need to register master node with kube-apiserver first. Then Heapster can collect stats / metrics naturally. @roberthbailey is working on registry part now.

**Comment by a-robinson** [comment]
Whatever sets the limits will also have to take into account the master VM size, so we can't just statically set limits without later adjustment.

**Comment by lavalamp** [comment]
@dchen1107 I suggest (at least for now) just setting limits to use most of the master VM's memory, not via some complex formula based on the size of the cluster.

**Comment by dchen1107** [comment]
@lavalamp This is pretty much my intention here too. Like how we handle docker daemon one each node, we could allocate etcd server 60% of memory capacity of master VM. But this should be done by the script which generating master components' manifest files at master node.

**Comment by lavalamp** [comment]
Dawn and I talked about this and came up with an alternative approach, since it's very tricky to figure out appropriate values for these limits. Instead of putting a limit for apiserver & etcd, the plan is to (optionally) add a parent cgroup, to limit the total memory consumption of all kubelet-spawned containers.

**Comment by lavalamp** [comment]
Some updated status on this: Dawn convinced me that even that is really hard. I have no suggested solution at this point. I'm kicking it out of the milestone. @dchen1107 please put it back in if there was actually work in progress to make this happen.

**Comment by smarterclayton** [comment]
Including cluster lifecycle.

**Comment by roberthbailey** [comment]
It isn't difficult for the cluster lifecycle tooling to set limits on the apiserver and etcd pods if we know what those limits should be. Defining the limits should be done by the api-machinery team as they own those components.

**Comment by smarterclayton** [comment]
The limits are proportional to workload and sig scalability owns that determination (and has been publishing it).
