### ISSUE TITLE
Subject: Inaccurate Error Message for StatefulSet Updates in Kubernetes

### ISSUE THREAD

**Issue by riita10069** [kubernetes/kubernetes#120171]
### What happened?

Hello Team,

I hope this message finds you well. I wanted to bring to your attention an issue related to updating StatefulSets within the Kubernetes ecosystem.

Currently, when attempting to update a StatefulSet using the `kubectl apply` command, an error message is displayed that reads as follows:

```
The StatefulSet "rocketmongo" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'ordinals', 'template', 'updateStrategy', 'persistentVolumeClaimRetentionPolicy' and 'minReadySeconds' are forbidden.
```

The error message implies that this issue is caused by a syntax error in the provided YAML. However, this is misleading and not an accurate representation of the problem.

Upon further investigation, it is clear that updating a StatefulSet using the `kubectl apply` command is intentionally restricted. According to the official Kubernetes documentation at https://kubernetes.io/docs/tutorials/stateful-application/basic-stateful-set/#updating-statefulsets, StatefulSets cannot be updated in this manner. The error message should, therefore, communicate the restriction accurately.

I kindly suggest that the error message be revised to convey a more precise explanation, such as:

```
Updates to StatefulSets are not allowed. Refer to the official documentation for more information: https://kubernetes.io/docs/tutorials/stateful-application/basic-stateful-set/#updating-statefulsets.
```

This adjustment would help users better understand the limitation and direct them to the appropriate documentation for guidance.

Thank you for your attention to this matter and for your ongoing efforts to improve the Kubernetes ecosystem.

Best regards,

### What did you expect to happen?

The following error message is displayed

```
Updates to StatefulSets are not allowed. Refer to the official documentation for more information: https://kubernetes.io/docs/tutorials/stateful-application/basic-stateful-set/#updating-statefulsets.
```

### How can we reproduce it (as minimally and precisely as possible)?

Attempting to update a StatefullSet which has already been activated by `kubectl apply.

### Kubernetes version

<details>

```console
$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.2", GitCommit:"7f6f68fdabc4df88cfea2dcf9a19b2b830f1e647", GitTreeState:"clean", BuildDate:"2023-05-17T14:13:27Z", GoVersion:"go1.20.4", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"27+", GitVersion:"v1.27.4-eks-2d98532", GitCommit:"3d90c097c72493c2f1a9dd641e4a22d24d15be68", GitTreeState:"clean", BuildDate:"2023-07-28T16:51:44Z", GoVersion:"go1.20.6", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
Amazon EKS 1.27
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by Pravesh-Sudha** [comment]
Can I work on this?

**Comment by pwschuurman** [comment]
/kind documentation

> I kindly suggest that the error message be revised to convey a more precise explanation, such as:

The challenge here is that some Updates are allowed (eg: replicas). I would suggest the phrase to be:

`The update for StatefulSet "rocketmongo" is invalid: spec: Forbidden: update to statefulset spec was attempted for an immutable field: [<list of field names>]`

as this gives the user actionable feedback to make changes (eg: what should be changed, rather than what is allowed to be chnaged.

> Updates to StatefulSets are not allowed. Refer to the official documentation for more information: https://kubernetes.io/docs/tutorials/stateful-application/basic-stateful-set/#updating-statefulsets.

I hesitate to add a hyperlink to the documentation for two reasons:
1) We now introduce a dependency between Kubernetes binaries and the documentation site. This prevents refactoring and changes to the documentation website (and there is no way to programatically enforce this dependency).
2) Navigating from the command line to a web browser is an out-of-band context switch. For a developer using `kubectl` directly, actionable contextual feedback directly in the terminal is the most useful. Also, a user may be in an environment where the internet is not accessible. I also don't see a significant precedent of error messages printing out external website links in Kubernetes, so this method of navigating an error message may be less familiar to a user of the tool.

> Currently, when attempting to update a StatefulSet using the kubectl apply command, an error message is displayed that reads as follows:

The error message is processed generically for updates here (https://github.com/kubernetes/apimachinery/blob/master/pkg/api/errors/errors.go#L307). It's not simple to disambiguate the error message and remove the preamble. I think the best located for message update would be here: https://github.com/kubernetes/apiserver/blob/master/pkg/registry/rest/update.go#L156

@riita10069 I think you have stated that people may find the prefix to this error message misleading, is that a fair assessment of your statement? (specifically `The StatefulSet "rocketmongo" is invalid: spec: Forbidden:`).
