### ISSUE TITLE
kubectl create secret docker-registry --docker-password is insecure

### ISSUE THREAD

**Issue by jakub-bochenski** [kubernetes/kubernetes#120180]
### What happened?

Passing passwords via the command line is known to be insecure https://www.netmeister.org/blog/passing-passwords.html

### What did you expect to happen?

There is an option to pass the password via file like `docker login --password-stdin`

### How can we reproduce it (as minimally and precisely as possible)?

-

### Kubernetes version

Any

### Cloud provider

Any

**Comment by troy0820** [comment]
You can pass the password via the ~/.dockerconfig.json as annotated in the help:
```
  When using the Docker command line to push images, you can authenticate to a given registry by running:
  '$ docker login DOCKER_REGISTRY_SERVER --username=DOCKER_USER --password=DOCKER_PASSWORD --email=DOCKER_EMAIL'.

 That produces a ~/.dockercfg file that is used by subsequent 'docker push' and 'docker pull' commands to authenticate
to the registry. The email address is optional.
```
Changing the behavior of this explicit command will break compatibility between versions with how the command works.  Is the above not suitable?

**Comment by jakub-bochenski** [comment]
> Changing the behavior of this explicit command will break compatibility between versions with how the command works.

How about adding a new option  `--docker-password-stdin` and adding a warning to the former one, like `docker login` does?

**Comment by seantywork** [comment]
This one also I'm curious about but there could be reasons unspoken.

Regarding "--docker-password-stdin" kinda flag, some of the factors I could guess are,

1) by design: over the development course so far the project is deliberately trying to avoid kubectl waiting for user input from stdin    

2) been doing okay without it: it's hard to find any serious complaint so far regarding the absence of password from stdin especially when there is a pervasive use case of "--from-file" flag

Regarding warning message such as the one the Docker emanates,

1) user-facing? : there could be some use cases that are dependent on parsing output from it when creating secret?

However, those are only my futile guess.

To find out the real reason behind it, digging deeper into the official documentation or (better) making a PR about it might shed some light because one can here from the relevant parties why and why not directly.

Come to think of it, I might try PRing sooner.

**Comment by jakub-bochenski** [comment]
> user-facing? : there could be some use cases that are dependent on parsing output from it when creating secret?

Should be solved by using stdout instead of stderr

**Comment by seantywork** [comment]
you're right, I'll edit the PR and let's see how the thread goes
