### ISSUE TITLE
Util.sh 'get-password' doesn't work with Python 3.4.3

### ISSUE THREAD

**Issue by hugecannon** [kubernetes/kubernetes#12025]
python -c 'import string,random; print "".join(random.SystemRandom().choice(string.ascii_letters + string.digits) for _ in range(16))'
      File "<string>", line 1
        import string,random; print "".join(random.SystemRandom().choice(string.ascii_letters + string.digits) for _ in range(16))
                                     ^
    SyntaxError: invalid syntax

Using Python 2.7.10 fixed the issue.

**Comment by roberthbailey** [comment]
Where we you running the script that it broke? How difficult was it to use the older version?

**Comment by hugecannon** [comment]
> Where we you running the script that it broke?
If I remember correctly, it was when using `kube-up` on an aws/gce configured cluster.
So I was running the usual `cluster/kube-up.sh` from the kubernetes directory.

> How difficult was it to use the older version?

Im not sure what this is asking. Interpreting it as 'How difficult was it to switch to an older python version so you could continue to use the cluster tools?'

It was quite easy as I used pyenv.

**Comment by kramarz** [comment]
I have the same problem and using python 2.7.10 is not a solution for me. I want to have docker image with all my deployment scripts. It includes extracting kubernetes scripts. Installing older python there just because of  removing print statement in newer version is stupid. It make my docker image more complicated and larger in its size. Can we just update all calls to python -c so they use only print function(not statement)? It also works under python 2.7.  I don't see any other issues with python 3.

My workaround for now is overriding these functions in my dockerfile and replacing print "abc" with print("abc")

**Comment by roberthbailey** [comment]
We have the same code in [common.sh](https://github.com/kubernetes/kubernetes/blob/master/cluster/common.sh#L171) which is used for GCE/AWS and presumably has the same issue. We should refactor the centos script to use the common function and then fix the python snippet in the common function to work consistently in python 2.7 and python 3 (if possible). If that isn't possible, then maybe we should just replace it with a shell snippet like we use to [generate random tokens](https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/configure-vm.sh#L398).

**Comment by justinsb** [comment]
Closing; fixed by #19522
