### ISSUE TITLE
kubectl proxy doesnt support `proxy-url`

### ISSUE THREAD

**Issue by jwcesign** [kubernetes/kubernetes#120318]
### What happened?

The overall arch:
![image](https://github.com/kubernetes/kubernetes/assets/19745536/8c7c6eec-9985-4254-92e5-cfe88a54e840)

1. admin Kubeconfig
```
- cluster:
    certificate-authority-data: xxx
    proxy-url: http://172.18.0.3:8088
    server: https://10.96.0.1
```

2.svc in clusters
```
root@karmada [12:13:03 AM] [~/.kube]
-> # k get svc
NAME         TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
kubernetes   ClusterIP   10.96.0.1    <none>        443/TCP   30h

```

3.run proxy
```
root@karmada [12:13:41 AM] [~/.kube]
-> # k proxy --reject-paths --v=8
Starting to serve on 127.0.0.1:8001
```

4.users kubeconfig
````
- cluster:
    certificate-authority-data: xxx
    server: http://127.0.0.1:8001
````

5. Get pods ok but exec timeout
```
root@karmada [12:14:59 AM] [~/.kube]
-> # k get po -A
NAMESPACE            NAME                                            READY   STATUS    RESTARTS        AGE
karmada-system       karmada-agent-7cd65ffd5d-6jplw                  1/1     Running   2 (161m ago)    30h
karmada-system       karmada-agent-7cd65ffd5d-z28k9                  1/1     Running   2 (161m ago)    30h
karmada-system       proxy-agent-6cc4777c57-9rssg                    1/1     Running   1 (6h20m ago)   29h
kube-system          coredns-787d4945fb-27th5                        1/1     Running   1 (6h20m ago)   30h
kube-system          coredns-787d4945fb-wpm9p                        1/1     Running   1 (6h20m ago)   30h
kube-system          etcd-member3-control-plane                      1/1     Running   3 (162m ago)    30h
kube-system          kindnet-p4qjg                                   1/1     Running   6 (6h20m ago)   30h
kube-system          kube-apiserver-member3-control-plane            1/1     Running   1 (162m ago)    161m
kube-system          kube-controller-manager-member3-control-plane   1/1     Running   5 (162m ago)    30h
kube-system          kube-proxy-b2m5n                                1/1     Running   1 (6h20m ago)   30h
kube-system          kube-scheduler-member3-control-plane            1/1     Running   4 (162m ago)    30h
kube-system          metrics-server-5c84698c5d-5lswm                 1/1     Running   2 (161m ago)    30h
local-path-storage   local-path-provisioner-c8855d4bb-k6gsk          1/1     Running   1 (6h20m ago)   30h
root@karmada [12:15:02 AM] [~/.kube]
-> # k exec -nkarmada-system karmada-agent-7cd65ffd5d-z28k9 --v=8 -- ls
I0901 00:15:04.912922 4179389 loader.go:374] Config loaded from file:  /root/.kube/members-new.config
I0901 00:15:04.915848 4179389 round_trippers.go:463] GET http://127.0.0.1:8001/api/v1/namespaces/karmada-system/pods/karmada-agent-7cd65ffd5d-z28k9
I0901 00:15:04.915873 4179389 round_trippers.go:469] Request Headers:
I0901 00:15:04.915893 4179389 round_trippers.go:473]     Accept: application/json, */*
I0901 00:15:04.915904 4179389 round_trippers.go:473]     User-Agent: kubectl/v1.25.3 (linux/amd64) kubernetes/434bfd8
I0901 00:15:04.919172 4179389 round_trippers.go:574] Response Status: 200 OK in 3 milliseconds
I0901 00:15:04.919206 4179389 round_trippers.go:577] Response Headers:
I0901 00:15:04.919219 4179389 round_trippers.go:580]     Audit-Id: 8a1a8724-fbf4-4db7-9495-60fcf4ceb56a
I0901 00:15:04.919240 4179389 round_trippers.go:580]     Cache-Control: no-cache, private
I0901 00:15:04.919253 4179389 round_trippers.go:580]     Content-Type: application/json
I0901 00:15:04.919262 4179389 round_trippers.go:580]     Date: Thu, 31 Aug 2023 16:15:04 GMT
I0901 00:15:04.919269 4179389 round_trippers.go:580]     X-Kubernetes-Pf-Flowschema-Uid: 70f17fd1-cf46-4199-8652-a7536805fb85
I0901 00:15:04.919276 4179389 round_trippers.go:580]     X-Kubernetes-Pf-Prioritylevel-Uid: 6ee94f70-d0d3-4c03-880e-fa0f02bf9f65
I0901 00:15:04.919548 4179389 request.go:1154] Response Body: {"kind":"Pod","apiVersion":"v1","metadata":{"name":"karmada-agent-7cd65ffd5d-z28k9","generateName":"karmada-agent-7cd65ffd5d-","namespace":"karmada-system","uid":"bbf35b09-aa17-4db0-a8a3-360cd85667cd","resourceVersion":"112457","creationTimestamp":"2023-08-30T10:04:51Z","labels":{"app":"karmada-agent","pod-template-hash":"7cd65ffd5d"},"ownerReferences":[{"apiVersion":"apps/v1","kind":"ReplicaSet","name":"karmada-agent-7cd65ffd5d","uid":"fedce588-e0df-40d7-9c19-dd34a2abc7ec","controller":true,"blockOwnerDeletion":true}],"managedFields":[{"manager":"kube-controller-manager","operation":"Update","apiVersion":"v1","time":"2023-08-30T10:04:51Z","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:generateName":{},"f:labels":{".":{},"f:app":{},"f:pod-template-hash":{}},"f:ownerReferences":{".":{},"k:{\"uid\":\"fedce588-e0df-40d7-9c19-dd34a2abc7ec\"}":{}}},"f:spec":{"f:containers":{"k:{\"name\":\"karmada-agent\"}":{".":{},"f:command":{},"f:image":{},"f:imagePullPolicy":{},"f:livenessProbe":{".":{},"f:failureThreshol [truncated 4603 chars]
I0901 00:15:04.922648 4179389 podcmd.go:88] Defaulting container name to karmada-agent
I0901 00:15:04.922713 4179389 round_trippers.go:463] POST http://127.0.0.1:8001/api/v1/namespaces/karmada-system/pods/karmada-agent-7cd65ffd5d-z28k9/exec?command=ls&container=karmada-agent&stderr=true&stdout=true
I0901 00:15:04.922726 4179389 round_trippers.go:469] Request Headers:
I0901 00:15:04.922741 4179389 round_trippers.go:473]     X-Stream-Protocol-Version: v4.channel.k8s.io
I0901 00:15:04.922754 4179389 round_trippers.go:473]     X-Stream-Protocol-Version: v3.channel.k8s.io
I0901 00:15:04.922765 4179389 round_trippers.go:473]     X-Stream-Protocol-Version: v2.channel.k8s.io
I0901 00:15:04.922776 4179389 round_trippers.go:473]     X-Stream-Protocol-Version: channel.k8s.io
I0901 00:15:04.922787 4179389 round_trippers.go:473]     User-Agent: kubectl/v1.25.3 (linux/amd64) kubernetes/434bfd8
```

### What did you expect to happen?

exec success

### How can we reproduce it (as minimally and precisely as possible)?

As said before

### Anything else we need to know?

There is no proxy: https://github.com/kubernetes/kubectl/blob/71b74708cf06d941a812176f0893431a7043bdfe/pkg/proxy/proxy_server.go#L167

### Kubernetes version

<details>

```console
$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.3", GitCommit:"434bfd82814af038ad94d62ebe59b133fcb50506", GitTreeState:"clean", BuildDate:"2022-10-12T10:57:26Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.0", GitCommit:"b46a3f887ca979b1a5d14fd39cb1af43e7e5d12d", GitTreeState:"clean", BuildDate:"2022-12-20T03:35:13Z", GoVersion:"go1.19.4", Compiler:"gc", Platform:"linux/amd64"}```

</details>



### Cloud provider

<details>

</details>

kind

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by neolit123** [comment]
> There are no sig labels on this issue.

/sig cli

**Comment by Devesh-N** [comment]
Hi @jwcesign 

Thank you for providing such a detailed issue description. Your issue suggests that the kubectl get po command works as expected, but you're experiencing a timeout when trying to execute kubectl exec on a pod within the Karmada-managed cluster.

A couple of areas to explore:

Network Policy/Firewall: Are there any network policies or firewall rules that could be preventing the exec command from successfully completing?

Logs: Can you provide the logs of the specific pod you're trying to exec into? You can obtain them using kubectl logs <POD_NAME> -n karmada-system.

Kube API Server: Given that you're running the kubectl proxy command, you may want to examine the kube-apiserver logs for more detailed error messages that could help diagnose the issue.

Version Mismatch: I see that your client version is v1.25.3 and the server is v1.26.0. Although minor version differences usually aren't a problem, it's generally a good idea to keep them the same, especially if you're encountering issues.

Kubectl Debugging: Since you're running kubectl proxy with a verbosity level of 8 (--v=8), are there any other messages that appear in the output just before or after the timeout occurs?

Direct kubectl exec: If possible, try running kubectl exec directly against the cluster, bypassing the kubectl proxy, to see if the issue persists.

Karmada Specifics: Given that this is a Karmada-managed cluster, are there any Karmada-specific logs or settings that might provide more insight into this issue?

To move forward, could you please provide the above details? That will give us a more complete picture to help troubleshoot this issue effectively.

**Comment by jwcesign** [comment]
Hi, @Devesh-N Thanks for replying.


I think the root problem is here: https://github.com/kubernetes/kubectl/blob/71b74708cf06d941a812176f0893431a7043bdfe/pkg/proxy/proxy_server.go#L167
It should set a proxy for the `transport`.

Direct kubectl exec: It works fine.

Network Policy/Firewall: No policy denied this.

Kubectl Debugging: Just have timeout error.

Other information, I will copy it here later.

**Comment by Devesh-N** [comment]
Hi @jwcesign ,

Thank you for pointing to the specific line of code in the makeUpgradeTransport function. Your observation about the DialContext configuration is interesting and could be a pivotal clue to resolve the issue.

DialContext Line: The line you've highlighted sets the DialContext within the HTTP transport, affecting how the network requests are initiated. Have you considered what specific issue might be occurring at this step?

Local Testing: Given that you've narrowed it down to this specific line, have you tried modifying this part in your local environment to see if it resolves the issue? For example, you could try tweaking the Timeout and KeepAlive parameters.

Network Analysis: You mentioned that the direct kubectl exec works fine, which implies that basic networking is functioning as expected. Have you done any network traces (e.g., tcpdump) while reproducing the issue to examine what might be different when using the proxy?

Logs and Errors: You mentioned a timeout error. Are there any additional logs or error messages that might offer more clues? More verbose logging could be helpful.

Additional Information: Any other details you can provide would be valuable for further diagnosis.

Since you've been able to narrow down the issue so specifically, I'd suggest that this might warrant opening a dedicated GitHub issue (if not already done) mentioning this function and line of code, along with the symptoms you've observed. This will likely expedite the process of getting eyes on the problem and potentially receiving a fix from maintainers or contributors.

**Comment by ardaguclu** [comment]
@jwcesign thanks for opening this issue and with such a good explanation. I'm going to investigate this issue but first I'm closing the other referenced issues to just continue on this.

**Comment by ardaguclu** [comment]
* I initialized a Kind cluster on my local and start a proxy via `kubectl proxy--reject-paths`. 
* I created a sample nginx pod via `kubectl run nginx-pod --image=nginx --port=80`.
* Set my kubeconfig's server field to `server: http://127.0.0.1:8001`
* kubectl get pods returned nginx-pod
* `kubectl exec -it pod/nginx-pod -- date` prints the expected output

**Comment by panuhorsmalahti** [comment]
I can also reproduce the issue. The proxy seems to fail when the connection is upgraded to e.g. websocket.

@ardaguclu I think your test setup is missing `proxy-url`

@jwcesign I tried that (if I understood you right) but it doesn't seem to help.

**Comment by jwcesign** [comment]
Sorry for the delayed response, I will give a script to setup the testing environment, and I will put the script here.

**Comment by jwcesign** [comment]
I fixed it by changing from:
https://github.com/karmada-io/karmada/blob/4e7084c0f508c4c37d3c664f0ae9eed3db34de47/vendor/k8s.io/apimachinery/pkg/util/proxy/upgradeaware.go#L340


to(with our own backendConn creation function):
https://github.com/karmada-io/karmada/blob/4e7084c0f508c4c37d3c664f0ae9eed3db34de47/pkg/util/proxy/upgrader.go#L228

**Comment by panuhorsmalahti** [comment]
@jwcesign thanks for that, but this code is a bit hard to adopt for kubectl proxy (as it appears to contain various custom code not in this package/repo).
