### ISSUE TITLE
Flag to Disable the 6-minute Force Detach Window

### ISSUE THREAD

**Issue by rohitssingh** [kubernetes/kubernetes#120328]
### What happened?

Certain online upgrade workflows might need to restart kubernetes as a part of their upgrade procedure. This can lead to the following sequence:
* As a part of draining a kubernetes node, a pod might get deleted.
* The unmount of a pod could take more than 6 minutes.
* If the node is deemed unhealthy when the 6 minute timer fires for the pod being deleted (for example, because kubelet is still restarting), then the underlying PV will be force detached (via a `ControllerUnpublishVolume` RPC)

These workflows would likely benefit from disabling this feature in lieu of the Non-Graceful Node Shutdown feature that hit GA in kubernetes 1.28 (see [here](https://kubernetes.io/blog/2023/08/16/kubernetes-1-28-non-graceful-node-shutdown-ga/) for more details).

When these issues are encountered in our testbeds, we are left with Zombie iSCSI LUNs. If pods end up migrating to a node with such a Zombie LUN present, those pods might end up attaching themselves to the Zombie LUN leading to data corruption.

This data corruption has caused a number of our cluster-management applications to lose all access to their data, requiring them to be deployed from scratch (occasionally causing downtime for the entire cluster).

### What did you expect to happen?

The ControllerUnpublishVolume request to wait indefinitely until NodeUnstageVolume has succeeded.

### How can we reproduce it (as minimally and precisely as possible)?

See the “What happened?” section for more details.

### Kubernetes version

<details>

```console
root@bootstrapper:~# kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"c285e781331a3785a7f436042c65c5641ce8a9e9", GitTreeState:"clean", BuildDate:"2022-03-16T15:58:47Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.4-gke.500", GitCommit:"a955253697d6572565777f63dfe6df9fd74591a2", GitTreeState:"clean", BuildDate:"2023-07-26T09:27:11Z", GoVersion:"go1.20.6 X:boringcrypto", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.23) and server (1.27) exceeds the supported minor version skew of +/-1
```

</details>

### Cloud provider

<details>
Google
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by rohitssingh** [comment]
/sig Storage

Tagging @bswartz, @msau42, @saad-ali, @jingxu97

**Comment by Devesh-N** [comment]
Hi @rohitssingh 

Thank you for the detailed issue report. The issue you've described with zombie iSCSI LUNs during Kubernetes upgrades sounds concerning, especially with the data corruption implications for cluster-management applications.

Firstly, I noticed there's a version skew between your client (1.23) and server (1.27) that exceeds the supported minor version skew of +/-1. While this may not be directly related to the issue you're facing, it's generally a good idea to align the versions for more consistent behavior.

Regarding the ControllerUnpublishVolume behavior, the intent of the 6-minute timer was to provide a timeout for certain scenarios, but it seems that in your case, it leads to undesirable outcomes. Since Kubernetes 1.28 introduced the Non-Graceful Node Shutdown feature, you're correct that disabling the previous timer-based feature could be beneficial.

Possible Solutions and Next Steps:
Upgrade to Kubernetes 1.28 or later: If possible, consider upgrading your Kubernetes cluster to take advantage of the Non-Graceful Node Shutdown feature.

Further Investigation: We would like to reproduce this issue in a controlled environment to understand it better. Would you be willing to share additional logs that could be useful?

Temporary Workaround: As an immediate workaround, you may consider scripting a manual detach procedure that accounts for the time needed for NodeUnstageVolume to succeed.

We'll be looking into this issue more thoroughly. I'll keep you updated on our findings and potential fixes.

Thanks again for bringing this to our attention. Your detailed explanation is invaluable in understanding the severity and specifics of the problem.

**Comment by rohitssingh** [comment]
Thanks for the detailed feedback @Devesh-N.

I'm in the process of uploading an associated PR; it'll be coming out shortly.

> We would like to reproduce this issue in a controlled environment to understand it better. Would you be willing to share additional logs that could be useful?

I think we can reproduce this by stopping kubelet on a node, killing a pod with a PV on that node, and then also bringing down the CSI node driver pod.

We would like everything to just wait for kubelet & the CSI node driver pod to be restored. But the 6-minute timer ends up firing leaving with PVs in the forced detach state.

**Comment by Devesh-N** [comment]
Hi @rohitssingh ,

Thank you for your prompt response, and I'm glad to hear that you're already working on a PR for this issue.

Your steps for reproducing the problem by stopping kubelet and killing a pod with a PV on the affected node provide a clear path for investigating this further. We'll use this method to reproduce the issue on our end as well.

Regarding the 6-Minute Timer:
The 6-minute timer was designed to handle certain edge cases, but as you've pointed out, it can cause more problems than it solves in specific scenarios like yours. It makes sense to reassess this feature, especially in the context of how it interacts with kubelet and CSI node driver pod outages.

Next Steps:
Review Your PR: Once your PR is submitted, we will review it as promptly as possible.
Internal Reproduction: We will also try to reproduce the issue internally, using the steps you've provided, to better understand the root cause and any possible fixes or workarounds.
Discuss Possible Improvements: As part of our ongoing efforts, we will discuss whether we can make improvements to Kubernetes that would eliminate the need for a forced detach after the 6-minute timer elapses, especially when kubelet and the CSI node driver pod are expected to recover.
We appreciate your continued involvement and detailed input as we work towards resolving this issue. Your experiences and solutions are invaluable to the community.

**Comment by YuikoTakada** [comment]
Thank you for posting issue report.

```
If the node is deemed unhealthy when the 6 minute timer fires for the pod being deleted (for example, because kubelet is still restarting), then the underlying PV will be force detached (via a ControllerUnpublishVolume RPC)
```
To be exact, PV force detach occurs only when `out-of-service` taint is added to the unhealthy node. So, if you don't wish PV force-detach, you can avoid it by not adding the taint. PV force-detach doesn't occur automatically.
Thanks.

**Comment by xing-yang** [comment]
@YuikoTakada There are two reasons for force detach, one is due to the `out-of-service` taint, and the other one is due to the 6 minute timeout.  See this PR that added reason for the force detach:
https://github.com/kubernetes/kubernetes/pull/119185/files

**Comment by YuikoTakada** [comment]
@xing-yang Thank you for your comments, I misunderstood

**Comment by akalenyu** [comment]
@rohitssingh I am wondering if you ever actually hit the consequence described in the issue
> If pods end up migrating to a node with such a Zombie LUN present, those pods might end up attaching themselves to the Zombie LUN leading to data corruption.

We think we see it but we don't entirely understand how it's possible.
(Obviously the forced storage detach isn't very safe just trying to explain the phenomenon)

I can certainly produce the forced detach in https://github.com/kubernetes/kubernetes/issues/120328#issuecomment-1702394693, but it's the zombie swap I am interesting in reproducing and understanding

**Comment by rohitssingh** [comment]
> [@rohitssingh](https://github.com/rohitssingh) I am wondering if you ever actually hit the consequence described in the issue

Yes, we did encounter this issue in our environments.

> 
> > If pods end up migrating to a node with such a Zombie LUN present, those pods might end up attaching themselves to the Zombie LUN leading to data corruption.
> 
> We think we see it but we don't entirely understand how it's possible. (Obviously the forced storage detach isn't very safe just trying to explain the phenomenon)
> 
> I can certainly produce the forced detach in [#120328 (comment)](https://github.com/kubernetes/kubernetes/issues/120328#issuecomment-1702394693), but it's the zombie swap I am interesting in reproducing and understanding

Our issue was specific to the protocol we were using (iSCSI). Specifically, the problem was that the storage controller thought a LUN id was free for use (because of ControllerUnpublishVolume) when in fact it was still in use by a k8s node.

To reproduce this issue, I would suggest that you:
* Inject errors in the NodeUnstageVolume path for a particular LUN.
* Cordon the node that is running a pod that uses said LUN.
* Delete the pod that was using that LUN.
* The pod should try to come up on another node, leaving a "zombie" device behind.

If you then uncordon the node in question and cordon all other nodes and then start creating new pods that use new PVs, eventually the underlying storage controller will re-use the LUN id that was used by the "zombie" device; the LUN that comes up with this id will be in the state I mentioned above.

I hope that helps!

**Comment by akalenyu** [comment]
Thanks! just to make sure, the original LUN from the pod is the one getting corrupted? So the data of the original application?

Or in some weird way the other "new" LUNs get corrupted?

**Comment by bswartz** [comment]
> Thanks! just to make sure, the original LUN from the pod is the one getting corrupted? So the data of the original application?
> 
> Or in some weird way the other "new" LUNs get corrupted?

There are two cases to consider:
1) In the situation where the storage system can reuse the same LUN number for two different volumes, the main worry is that the new LUN gets confused with the old LUN, and the new LUN gets corrupted because it's mapped to a LUN number that the node things belongs to the old volume. In this case the old volume is safe, having been detached, and the risk comes from the confusion caused by reuse of numbers.
2) You can have a case when the volume gets detached after 6 minutes, and attached to another node, then later detached and reattached back to the original node. Since the node doesn't know that another node has mounted/unmounted the volume in the meantime, it may think it's had exclusive access all long and will flush dirty buffers to the disk once it regains access. This would corrupt the original volume.

Both problems stem from the lack of node-side cleanup when the 6-minute force detach triggers. For this reason the only safe thing to do is to disable the 6-minute timer, and handle dead nodes by actually rebooting them and tainting the node.

**Comment by akalenyu** [comment]
Thank you for the answer, I think I am more interested in 2

> 2\. it may think it's had exclusive access all long and will flush dirty buffers to the disk once it regains access

Is the existence of these dirty buffers realistic in a k8s environment? Where would dirty data come from? the first iteration of the workload (on this node?) Is that even possible?

Another question, I saw some drivers implementing guard rails (for what it looks like) against this problem:
https://github.com/NetApp/trident/commit/b33021d64da7588d65b7f38cda7cd01873850e14
(Second point)
I guess those guard rails make sense regardless of the force detach behavior, since any bug in the driver could lead to a "force detach". WDYT?

**Comment by rohitssingh** [comment]
The worst case I encountered was actually a combination of the two cases that Ben mentioned.

Let us say that we have two volumes in use by two different pods:
```
V in use by pod p
W in use by pod q
```

And two k8s hosts:
```
N
O
```

Along with three random LUN ids:
```
i
j
k
```

Let us assume that our LUN mappings are unique to each k8s host.

If initially `V` is mapped to `N` @ `i`, we will have the following LUN mappings:

```
On k8s Hosts			On the Storage Controllers
============			==========================
N:
i -> V					i -> V 

O:
N/A						N/A
```

This looks fine so far.

But things can get broken if we try to migrate pod `p`, which uses `V`, to `O`.

Node N has 6 minutes to tear down `V` so that it can be resurrected on `O`. However, if the timer fires before cleanup finishes, then KCM will prematurely issue a `ControllerUnpublishVolume` leading to a force detach.

This will leave us with:
```
On k8s Hosts			On the Storage Controllers
============			==========================
N:
i -> V					N/A

O:
N/A						N/A
```

Later, KCM will issue a `ControllerPublishVolume` for `V` on `O`, leaving:
```
On k8s Hosts			On the Storage Controllers
============			==========================
N:
i -> V					N/A

O:
j -> V					j -> V 
```

where `j` is some LUN id that was free for use in `O`'s mapping space.

The state on node `N` is not correct and can now result in serious problems after more pods get scheduled. Among other issues, this is dangerous because all of `V`'s buffers might not be flushed and committed at the time the mapping is broken. But as we will see, we have bigger problems too...

If pod `q` now gets scheduled on `N`, the storage controller is free to allocate any available LUN id; since it believes `i` is available, it is free to use it again.

If it does opt to allocate `i` here, we will then have the following mappings:
```
On k8s Hosts			On the Storage Controllers
============			==========================
N:
i -> V					N/A
i -> W					i -> W

O:
j -> V					j -> V 
```

Technically speaking, we do not yet have an problem; though we have a stale mapping for `V` on `N`, it is not actively in use.

But we will have a problem if `p` ever returns to `N`, when we will have:
```
On k8s Hosts			On the Storage Controllers
============			==========================
N:
i -> V					k -> V
i -> W					i -> W

O:
N/A						N/A
```

where `k` is some LUN id that was free for use in `N`'s mapping space.

Since the device is already established (and maybe even mounted in the appropriate namespace), the underlying machinery will then present the same LUN (i.e., `i` which is actually mapped to the LUN backing `W`) to both pods `p` & `q`. This will result in data corruption as both pods proceed to write data & flush their respective superblocks.

I will let Ben speak to the driver-side mitigations (in particular, the change you referenced seems to be his handiwork :) ).

**Comment by bswartz** [comment]
> Is the existence of these dirty buffers realistic in a k8s environment? Where would dirty data come from? the first iteration of the workload (on this node?) Is that even possible?

Rohit gave a very detailed explanation, but very shortly, the dirty data is any data written by an application or filesystem which never got acknowledged because write access was cut off by a controller unpublish. This can happen if you trigger the non-graceful-node-shutdown feature _without_ actually rebooting the node. Once the node regains write access to the volume it will continue writing without checking to see if anyone else wrote data in the mean time.

> Another question, I saw some drivers implementing guard rails (for what it looks like) against this problem: [NetApp/trident@b33021d](https://github.com/NetApp/trident/commit/b33021d64da7588d65b7f38cda7cd01873850e14) (Second point) I guess those guard rails make sense regardless of the force detach behavior, since any bug in the driver could lead to a "force detach". WDYT?

I have never successfully used the Trident force detach feature. I know that it's one of many such implementations in drivers to try to mitigate this problem. How easy or hard this is depends a lot of the underlying data protocol. iSCSI is one of the worst I've seen, thanks to how complex the Linux initiator implemenation is.

**Comment by akalenyu** [comment]
Thanks again for investing in replies here @rohitssingh @bswartz!
I have tried to follow the reproducer;

> If pod `q` now gets scheduled on `N`, the storage controller is free to allocate any available LUN id; since it believes `i` is available, it is free to use it again.
> 
> If it does opt to allocate `i` here, we will then have the following mappings:
> 
> ```
> On k8s Hosts			On the Storage Controllers
> ============			==========================
> N:
> i -> V					N/A
> i -> W					i -> W
> 
> O:
> j -> V					j -> V 
> ```
> 
> Technically speaking, we do not yet have an problem; though we have a stale mapping for `V` on `N`, it is not actively in use.

Thing is, at least with multipath, it will correct this state once a new volume/pod combo schedules on `N`.
So, I am seeing that it **does** opt to allocate LUN ID `i`, it just remediates the force detached state as far as `lsblk/multipath -ll` is concerned - the "bad" entry disappears from `multipath -ll` output.
So I don't think is the case for me
> ```
> On k8s Hosts			On the Storage Controllers
> ============			==========================
> N:
> i -> V					N/A
> ```
and instead it's
> ```
> On k8s Hosts			On the Storage Controllers
> ============			==========================
> N:
> i -> W					i -> W
> ```

And thus upon completing the reproducer's execution, I see no corruption.
I think these multipath logs are related to the remediation
```
multipathd[32318]: sdc: path wwid changed from 'FORCE_DETACHED_WWID' to 'NEW_WWID'
...
multipathd[32318]: 8:32: path removed from map FORCE_DETACHED_WWID
multipathd[32318]: FORCE_DETACHED_WWID: sdd - tur checker reports path is up
multipathd[32318]: FORCE_DETACHED_WWID: remaining active paths: 1
multipathd[32318]: sdd: path wwid changed from 'FORCE_DETACHED_WWID' to 'NEW_WWID'
multipathd[32318]: FORCE_DETACHED_WWID Last path deleted, disabling queueing
multipathd[32318]: FORCE_DETACHED_WWID: map flushed after removing all paths
```

Were you encountering the issues on an environment with multipath as well?

**Comment by rohitssingh** [comment]
That's very interesting @akalenyu!

I think we are using multipath too, but we never would end up down that codepath.

The last line where the map device is being flushed & removed is printed from `flush_map_nopaths` [here](https://github.com/opensvc/multipath-tools/blob/de16cf82c5263fc148118be56ebf44c8f0ee60b8/multipathd/main.c#L635C1-L637C14):

```
	condlog(2, "%s: map flushed after removing all paths", mpp->alias);
	remove_map_and_stop_waiter(mpp, vecs);
	return true;
```

In our case, we have `queue_if_no_path` enabled, so we wouldn't even get to this point.

**Comment by bmarzins** [comment]
@rohitssingh this log message:
```
multipathd[32318]: FORCE_DETACHED_WWID Last path deleted, disabling queueing
```
means `flush_on_last_del` is enabled and it disabled `queue_if_no_path` when the last path was deleted.

@akalenyu  looking at those logs, it looks like they are already consistent with a situation where corruption can occur. These two lines:
```
multipathd[32318]: FORCE_DETACHED_WWID: sdd - tur checker reports path is up
multipathd[32318]: FORCE_DETACHED_WWID: remaining active paths: 1
```
are printed by the path checker. Specifically `remaining active paths` is printed after the path is re-enabled. The line where the changed WWID is noticed:
```
multipathd[32318]: sdd: path wwid changed from 'FORCE_DETACHED_WWID' to 'NEW_WWID'
```
is printed when multipathd processes the uevent that presumably was issued when the LUN reappeared, and it appears after the path checker lines. The moment that the path is re-enabled in the kernel, it is able to flush any queued IO to it. This means that if there was queued IO to that device, these logs appear to show a window where the kernel could have sent it to the bad path before multipathd removed it. It is possible to close this window by setting the `recheck_wwid` configuration parameter. This will check for changed WWIDs whenever a path comes back online. That still can't remove the possibility of corruption completely. It is possible that a path changes WWIDs without multipathd ever noticing that it went down, and IO could go to it before multipathd processes the uevent for the change.
