### ISSUE TITLE
Detect nodes that are oscillating between ready and not ready

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#12041]
Probably by keeping a history of node status.

This should solve the case where, for example, the node flips in and out of outOfDisk because a pod has an image that is big enough to cause the node to go through both of its thresholds.

**Comment by davidopp** [comment]
> because a pod has an image that is big enough to cause the node to go through both of its thresholds.

What does "both of its thresholds" refer to?

It seems like a better solution to this problem is to do disk space scheduling and enforce disk limits, so the machine doesn't run out of disk. But I guess we want to fix this problem sooner than that?

**Comment by lavalamp** [comment]
Kubelet does hysteresis, so if disk usage goes over 90% (and kubelet reports NotReady), then kubelet won't report Ready again until disk usage goes below 70%.

The motivating use case was where a pod had a 2G image, and on a 10G disk that's just enough to make kubelet oscillate between ready and not ready.

But this bug is about generically detecting oscillating ready/not ready nodes. The specific case will be solved by disk space scheduling, as you say.

**Comment by davidopp** [comment]
@dchen1107 and @yujuhong both told me that OutOfDisk does not cause NodeReady==false; it only causes Pod to fail to start.

@lavalamp can you point me to the code that cause Kubelet to report NodeReady==false? Or maybe the original issue was due to something other than disk causing the NodeReady oscillation?

**Comment by lavalamp** [comment]
IRL conversation: 
* It seems I misremembered what kubelets do. The point is to prevent recidivism. Kubelet needs to start making an out of disk condition, which it doesn't currently.
* Once it starts making that condition, THEN we will have the problem that this issue is filed about, where it will be out of disk only until it garbage collects the image from the failed pod, and it will oscillate.

**Comment by davidopp** [comment]
@madhusudancs I almost forgot about this one. You can do it in a seprate PR after the one you are working on. I think the simplest thing to do is to add some trivial rule like Kubelet will only transition OOD in NodeStatus from true to false if kl.isOutOfDisk() has been returning false for, say, 5 minutes.

@lavalamp what do you think?

**Comment by lavalamp** [comment]
I think time-based check is not harmful but also won't fix the problem--
the cycles are triggered by something being scheduled on the node, so
adding a delay just makes the cycles longer, it doesn't prevent them.

On Tue, Oct 27, 2015 at 1:08 AM, David Oppenheimer <notifications@github.com

**Comment by davidopp** [comment]
@lavalamp Maybe I didn't understand your suggestion.

You suggested "detect nodes that are oscillating between ready and not ready" -- I interpreted this to mean the server should avoid scheduling onto nodes that are oscillating, until they have not oscillated for some period of time.

My suggestion was to do the same thing, but mask the oscillation in the Kubelet rather than have the master detect it. But aren't both of them instances of "avoid scheduling onto the node until it hasn't oscillated for X amount of time" and thus a time-based check?

Or are you suggesting that the server should track \<node, pod\> pairs, and forever forbid scheduling that pod onto that node? (This is tricky because pods don't have an identity that survives across failure, like OutOfDisk. The key in the map would have to be a ReplicationController UID or a hash of the PodTemplate or something like that. Also, I'm not sure this is a good policy, because it ignores the fact that other things might terminate on the machine in the mean time, thus making the pod now reasonable to put on that machine.)

**Comment by lavalamp** [comment]
So this issue is in the "solve the general class of problem" category, and
the point is to catch nodes for which kubelet's own status reporting is
faulty, so fixing it in kubelet is not my first choice.

I wasn't wanting to go so far as checking <node, pod> pairs, rather an
intermediate check for "every time I put something on this it goes
unhealthy" is what I was thinking.

I think this is actually a pretty hard request, I'm basically asking the
control plane to diagnose a node as sick-for-unknown-reason. "Solve the
general class of problem" in the postmortem checklist.

Putting an out-of-disk status in the node and making it accurate is good,
useful, and will 100% solve the object level problem, but not the class of
possible problems.

(Also a five minute delay is long enough for node controller to start
ejecting everything-- is that what we want?)





On Tue, Oct 27, 2015 at 2:23 PM, David Oppenheimer <notifications@github.com

**Comment by davidopp** [comment]
> Also a five minute delay is long enough for node controller to start ejecting everything-- is that what we want?

Sorry, I was just thinking of this in the context of OutOfDisk. We don't evict pods for OutOfDisk=true, only for NodeReady=false. If we also wanted to apply this to NodeReady=false, then you're right, waiting 5 minutes would evict everything (though if it has been flapping for a while, maybe that's actually what you'd want to do?).

Anyway, I'd really like to wait and see if people run into this problem in practice. This feature does not clearly align with any of our 1.2 goals.

**Comment by lavalamp** [comment]
As long as we fix the object-level problem, I'm OK with sitting on the meta
problem for a while.

On Tue, Oct 27, 2015 at 4:11 PM, David Oppenheimer <notifications@github.com

**Comment by davidopp** [comment]
What do you mean "the object-level problem" ?

**Comment by lavalamp** [comment]
"object-level problem" = nodes flapping due to out of disk

On Tue, Oct 27, 2015 at 5:51 PM, David Oppenheimer <notifications@github.com

**Comment by bprashanth** [comment]
https://github.com/kubernetes/kubernetes/issues/13492

**Comment by davidopp** [comment]
@lavalamp so you'd be OK with suppressing this on the Kubelet? (given that it won't cause pods to be evicted since OOD does not cause pod eviction)

**Comment by lavalamp** [comment]
@davidopp Yes. Specifically, fixes on the kubelet lower the priority of this issue, but do not close it.

**Comment by davidopp** [comment]
@madhusudancs Can you take this one? It looks pretty straightforward -- modify the code you added to setNodeStatus() in kubelet.go so that it only flips from reporting OOD True to reporting OOD False if it has been in OOD True state for some period of time -- say, 5 minutes. Probably want to make it possible to disable this behavior in e2e tests, so instead of hard-coded 5 minutes it should probably be a flag that defaults to 5 minutes, which you could override in e2e tests. (I believe I previously sent you a pointer to the code that allows you to override kubelet flags in e2e tests -- if not, @gmarek will remember where it is.)

**Comment by madhusudancs** [comment]
@davidopp Sure. I wanted to talk to you and/or Daniel about it this week if there was no resolution. Now that there is, I will work on it this week.

**Comment by kargakis** [comment]
@kubernetes/sig-node-bugs

**Comment by gmarek** [comment]
We probably should tackle it when we'll be moving conditions to Taints. It's not clear to me if we want to rate limit on a Node side or on a ControlPlane side (in the latter case we'd need to be stricter though).

I want to be able to create hotlists of github issues...
