### ISSUE TITLE
`poststarthook/apiservice-registration-controller` check blocks apiserver readiness for 1 minute if discovery cannot be completed

### ISSUE THREAD

**Issue by brandond** [kubernetes/kubernetes#120739]
### What happened?

I’m seeing some odd behavior with 1.28.2 that was not present in earlier releases, with regards to aggregated api services. It appears that the `poststarthook/apiservice-registration-controller` is now blocking the apiserver from becoming ready for 1 minute, if discovery for an aggregated apiservice is not available when the apiserver is started. Note that this only happens if the apiservice is marked available when the apiserver is started; if it is unavailable at startup (Available status: false), or the service has no endpoints, the health check does not block and readyz returns `ok` without delay.

I am seeing this behavior in 1.28.1 and 1.28.2, but not v1.27.6 or v1.27.5

### What did you expect to happen?

apiserver becomes ready without any additional delays

### How can we reproduce it (as minimally and precisely as possible)?

1. Deploy metrics-server to a Kubernetes cluster
2. Wait for api registration for `v1beta1.metrics.k8s.io` to complete (Available status is `true`).
3. Kill the kubelet and pods on the node hosting the metrics-server pod, such that the metrics-server service continues to show available endpoints, but the endpoint is not reachable.
4. Restart the apiserver before the `v1beta1.metrics.k8s.io` apiservice is marked unavailable
5. Note that the `poststarthook/apiservice-registration-controller` check blocks readiness for 1 minute. After 1 minute the Available status is updated to `false`, and the health check passes.

### Anything else we need to know?

Other notes:
* Does not appear to make any difference if `AggregatedDiscoveryEndpoint` feature-gate is set to false.
* If the metrics-server service has no endpoints available, the apiservice status reason is updated to `MisssingEndpoints` and the check passes quickly.
* If there is an available endpoint, but it is not reachable, the check seems to be stuck retrying the endpoint, with the following message repeated in the logs:
    `Sep 18 20:37:01 systemd-node-1 k3s[8000]: E0918 20:37:01.403911    8000 available_controller.go:460] v1beta1.metrics.k8s.io failed with: failing or missing response from https://10.42.0.2:10250/apis/metrics.k8s.io/v1beta1: Get "https://10.42.0.2:10250/apis/metrics.k8s.io/v1beta1": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)`

Odd error from GC that I don't remember seeing in the past:
`Sep 18 20:34:30 systemd-node-1 k3s[7903]: I0918 20:34:30.744555    7903 garbagecollector.go:816] "failed to discover some groups" groups="<internal error: json: unsupported type: map[schema.GroupVersion]error>"`

### Kubernetes version

<details>

```console
systemd-node-1:/ # kubectl version
Client Version: v1.28.2+k3s-416d7e87
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.2+k3s-416d7e87
```

</details>

### Cloud provider

<details>
k3s
</details>

### OS version

<details>

```console
systemd-node-1:/ # uname -a
Linux systemd-node-1 5.19.0-1019-aws #20-Ubuntu SMP Mon Jan 23 13:41:19 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

systemd-node-1:/ # cat /etc/os-release
NAME="openSUSE Leap"
VERSION="15.4"
ID="opensuse-leap"
ID_LIKE="suse opensuse"
VERSION_ID="15.4"
PRETTY_NAME="openSUSE Leap 15.4"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:leap:15.4"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"
DOCUMENTATION_URL="https://en.opensuse.org/Portal:Leap"
LOGO="distributor-logo-Leap"
```

</details>

### Install tools

<details>
k3s
</details>

### Container runtime (CRI) and version (if applicable)

<details>
containerd
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
flannel
</details>

**Comment by liggitt** [comment]
cc @tnqn @Jefftree @apelisse

**Comment by tnqn** [comment]
I investigated the cause of the delay and think it may be related to https://github.com/kubernetes/kubernetes/pull/118212 instead of https://github.com/kubernetes/kubernetes/pull/120108.

The following is where the 1 minute is delayed:
func (c *APIServiceRegistrationController) Run(stopCh <-chan struct{}, handlerSyncedCh chan<- struct{}) 
-> c.apiHandlerManager.AddAPIService(s)
--> s.openAPIAggregationController.AddAPIService(proxyHandler, apiService)
---> c.openAPIAggregationManager.AddUpdateAPIService(apiService, handler)
----> s.updateServiceLocked(apiService.Name)
-----> specInfo.downloader.Get()
------> d.downloader.Download(d.handler, d.etag)
-------> handler = http.TimeoutHandler(handler, specDownloadTimeout, "request timed out") // specDownloadTimeout is 1 * time.Minute
-------> handler.ServeHTTP(writer, req)
--------> if !handlingInfo.serviceAvailable {      // serviceAvailable is true according to the condition in APIService

Because the APIService is available in its status, it will try to get the v2 spec with a timeout of 1 minute. This also explains why there is no delay when the APIService is not available in its status.

The issue occurs only after v1.28 may be because https://github.com/kubernetes/kubernetes/pull/118212 changed `c.openAPIAggregationManager.AddUpdateAPIService` to download the latest spec synchronously?
