### ISSUE TITLE
Unable to access docker container address

### ISSUE THREAD

**Issue by adyanthaya17** [kubernetes/kubernetes#12071]
Hi,

I've deployed kubernetes environment and brought up containers but when I run 'docker ps -a' I'm unable to get any ports. It gives me an empty column. When I run ifconfig I"m able to see the docker and flannel working.

**Comment by dalanlan** [comment]
More details about your ENV & deployment process would help much.

**Comment by hw-qiaolei** [comment]
"brought up containers"...I think you just brought up nodes and pods other than containers

**Comment by adyanthaya17** [comment]
With the examples in the the kubernetes/example/ I have used to bring up mysql and wordpress containers. When I run the kubectl get services I'm able to view the Ip and port  number. 

I'm not sure of how to access it through my web page? 

$ kubectl get services

NAME         LABELS                                    SELECTOR         IP(S)           PORT(S)
kubernetes   component=apiserver,provider=kubernetes   <none>           192.168.3.1     443/TCP
mysql        name=mysql                                name=mysql       192.168.3.136   3306/TCP
wpfrontend   name=wpfrontend                           name=wordpress   192.168.3.37    80/TCP

**Comment by dalanlan** [comment]
No experience with GCE, but i guess [this](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/examples/mysql-wordpress-pd/README.md#start-the-wordpress-service) would help. 
It says `Then, find the external IP for your WordPress service by running:...`

**Comment by adyanthaya17** [comment]
I used the same document actaully and that's what I got.

**Comment by dalanlan** [comment]
So you run the exact cmd and could not get the expected result of external ip? 
I was wondering what you suffered.

**Comment by adyanthaya17** [comment]
Yes, that's right.

$ ifconfig
docker0   Link encap:Ethernet  HWaddr 56:84:7a:fe:97:99
          inet addr:172.16.57.1  Bcast:0.0.0.0  Mask:255.255.255.0

and the ip the container is receiving ip 192.168.3.37 as in cluster/ubuntu/config-default.sh

export SERVICE_CLUSTER_IP_RANGE=192.168.3.0/24
export FLANNEL_NET=172.16.0.0/16

**Comment by goltermann** [comment]
We’re going through old support issues and asking everyone to direct your questions to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes). 

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases. 

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.
