### ISSUE TITLE
I install the k8s failed with libvirt-coreos demo 

### ISSUE THREAD

**Issue by Icedroid** [kubernetes/kubernetes#12073]
[root@localhost kubernetes]# cat /etc/redhat-release 
CentOS release 6.6 (Final)
[root@localhost kubernetes]# export KUBERNETES_PROVIDER=libvirt-coreos
[root@localhost kubernetes]# cluster/kube-up.sh 
Starting cluster using provider: libvirt-coreos
... calling verify-prereqs
KSM is not enabled
Enabling it would reduce the memory footprint of large clusters
Do you want to enable KSM (requires root password) (y/n)? y
... calling kube-up
KUBE_MASTER_IP: 192.168.10.1
KUBE_MASTER: kubernetes-master
创建池 kubernetes

池 kubernetes 被刷新

从kubernetes_global创建网络cluster/../cluster/libvirt-coreos/network_kubernetes_global.xml 

从kubernetes_pods创建网络cluster/../cluster/libvirt-coreos/network_kubernetes_pods.xml 

cat: /root/.ssh/id_*.pub: 没有那个文件或目录
创建卷 kubernetes-minion-1.img 

池 kubernetes 被刷新

which: no qemu-system-x86_64 in (/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/ffmpeg/bin/:/root/bin)
错误：从 /tmp/tmp.SsFRfQdjfl 创建域失败
错误：internal error unknown input device type 'keyboard'

**Comment by hw-qiaolei** [comment]
Hi Icedroid,

I do not install k8s on CentOS 6.6, but from the error messages your posted here it seems that you missed some basic configuration and dependencies.

1, cat: /root/.ssh/id_*.pub: 没有那个文件或目录
Error is started here. Could you please generate a ssh key on master node and copy it to the remote nodes so they can be ssh logged in without a password by using key authentication? For example, 
ssh-keygen -t dsa -P '' -f ~/.ssh/id_dsa
ssh-copy-id -i ~/.ssh/id_dsa.pub <remote user>@<remote nodes' ip or hostname>

2, which: no qemu-system-x86_64 in ...
Try to install qemu-system-x86_64 on your system.

Good luck.

**Comment by Icedroid** [comment]
@hw-qiaolei Thanks for your reply. Which OS you installed the k8s.
I want to instlall the k8s with libvirt-coreos demo, the master is auto generate by the libvirt.

**Comment by goltermann** [comment]
We’re going through old support issues and asking everyone to direct your questions to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes). 

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases. 

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.
