### ISSUE TITLE
OpenStack implementation does not account arbitrary fixed/floating IP pool names

### ISSUE THREAD

**Issue by jpgxs** [kubernetes/kubernetes#12083]
A similar (closed) issue in https://github.com/rackspace/gophercloud/issues/111 outlines this.

The getAddressByName function in openstack.go does not account for pool names other than 'public' and 'private'

In private OpenStack implementations, the pool may have an arbitrary name containing either:
"OS-EXT-IP:type": "fixed"
or
"OS-EXT-IP:type": "floating"

Which, in such an implementation, would indicate whether this were a private or public IP (respectively)

**Comment by sc68cal** [comment]
Based on the code it seems to be 'public' or 'floating' - if I understand correctly.

https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/openstack/openstack.go#L286-L291

**Comment by emonty** [comment]
Things are actually much more complex than that, sadly. The code here:

https://github.com/openstack-infra/shade/blob/master/shade/meta.py#L325-L329

is the entry point for a pile of logic for figuring out the appropriate addresses. It's also worth noting that in shade we have stopped relying on the nova proxy info and replace it directly with neutron api calls ourselves, as the proxy data can get stuck in a stale state leading to VMs that seem broken but are actually functional

**Comment by sc68cal** [comment]
Yeah, when I started reading through the openstack k8s provider, I started to realize that it is basically having to solve the issues that Shade was written to solve. @emonty and I spoke quite a bit about the whole neutron/nova-network stuff and how handle all the little differences in Shade, so hopefully this new project @emonty is doing ([oaktree](http://lists.openstack.org/pipermail/openstack-dev/2016-November/107336.html)) can help

**Comment by dims** [comment]
@FengyunPan @anguslees anything we can do here to make things better?

**Comment by emonty** [comment]
We've been discussing various things with gophercloud as well, such as
making sure we get clouds.yaml support added there. I agree with Sean about
oaktree potentially being able to help - and at this past summit we got
interest from AT&T from starting to work on that (although I owe them a
kick-off mailing list thread)

If oaktree winds up not being the way this gets solved, I highly recommend
putting logic similar to what's in shade inside of gophercloud rather than
directly in the k8s provider, since the issues will exist for anyone using
openstack from golang, not just for kubernetes, and solving issues in
gophercloud will also help folks who might be using terraform or something
similar.

Would it be helpful to write up a document of the various things on top of
the API that shade/oaktree provide for the user so that we could implement
equivalent logic in gophercloud or the kubernetes provider?

**Comment by anguslees** [comment]
The original bug was fixed (a long time ago - #18829 in k8s v1.2) by adding the code pointed to above that checks for `OS-EXT-IPS:type=floating` afaics, and we should close this.

Since then we've had very few complaints/requests around the remaining logic.  I'm not sure what that says about the state of the world (or our approachability), but I'm reluctant to discuss adding more complexity here without having someone actually asking for it.

**Comment by sc68cal** [comment]
After a couple months in early 2017 strugging with all the ways to try and provision a k8s cluster on OpenStack (terraform, the openstack provider, heat templates, etc etc) I totally gave up on trying to get the openstack provider to work. We provision servers via the OpenStack API, then use kargo to set them up as a kubernetes cluster.

**Comment by sc68cal** [comment]
I don't think https://github.com/kubernetes/kubernetes/pull/18829 fixed it, because (it's been about a year now) the logic was extremely brittle and it did not work in the cloud I was using. Looking for `OS-EXT-IPS:type` to be floating or a network named "public" did not encompass all possible values.

Or something to that effect. I don't have my notes for what the Openstack Network objects that were available and their metadata - but I distinctly remember that we did not have a network named "public" or any floating ips
