### ISSUE TITLE
Removing pv keeps pvc as bound

### ISSUE THREAD

**Issue by farcaller** [kubernetes/kubernetes#12084]
running 1.0.1:

```
% kubectl create -f docker-registry-data.yml
persistentvolumes/docker-registry-data
% kubectl create -f docker-registry-data-claim.yml
persistentvolumeclaims/docker-registry-data
% kubectl get pv
NAME                   LABELS    CAPACITY      ACCESSMODES   STATUS    CLAIM                          REASON
docker-registry-data   <none>    10737418240   RWO           Bound     default/docker-registry-data
% kubectl get pvc
NAME                   LABELS    STATUS    VOLUME
docker-registry-data   map[]     Bound     docker-registry-data
```

all looks fine. Now to deletion:

```
% kubectl delete pv/docker-registry-data
persistentvolumes/docker-registry-data
% kubectl get pv
NAME      LABELS    CAPACITY   ACCESSMODES   STATUS    CLAIM     REASON
% kubectl get pvc
NAME                   LABELS    STATUS    VOLUME
docker-registry-data   map[]     Bound     docker-registry-data
```

claim is displayed as bound although the volume doesn't exist. Should be `Pending`.

**Comment by thockin** [comment]
@markturansky

We don't generally have a mechanism to block deletions, but here's a case
where we probably should fail a deletion with a message indicating the
claim that is pinning it.  Then repeat for claims that are in use by a pod.

Or we should cascade the delete as we do with RC.

On Fri, Jul 31, 2015 at 7:22 AM, Vladimir Pouzanov <notifications@github.com

**Comment by markturansky** [comment]
It's easy to fail validation if pv.Spec.ClaimRef isn't nil and phase=bound.  I will make a PR for that.

I think we'd need a special way to trigger a cascade delete purposefully.  An accidentally deleted PV would be a bad user experience.  Is there a way today to bypass the above validation with a force type flag/arg?

**Comment by markturansky** [comment]
How do I validate that a pod is referencing a claim before deleting the claim?  I would need to query for that data.  

This pattern plays out for any kind of dependency in the namespace, too, not just pvclaims.

**Comment by thockin** [comment]
I think v0 should be to prevent the deletion.  As we have more and more
objects referencing each other we have a real referential-integrity problem
to solve - we can't just back-link everything.

Another example: what happens if I delete a secret that is used by a pod?

@pmorie
@smarterclayton @bgrant0607 @lavalamp - we've dodged this for a while, but
we're making it worse for ourselves by dis-integrating objects and doing
cross-references.  I think this facet of API machinery is going to need
some love.

**Comment by bprashanth** [comment]
Sounds like we can plug BeforeDelete to invoke the strategy and validate deletes just like we do updates (https://github.com/GoogleCloudPlatform/kubernetes/blob/11f9fd1dcd9a0b45e2b1fdeced95b61aed153599/pkg/api/rest/update.go#L63, https://github.com/GoogleCloudPlatform/kubernetes/blob/5520386b180d3ddc4fa7b7dfe6f52642cc0c25f3/pkg/api/rest/delete.go#L39) and then give the pv resource a delete strategy from where they could query pods?

**Comment by smarterclayton** [comment]
This really should be a controller loop reacting to deleted pvs.

On Jul 31, 2015, at 2:58 PM, Prashanth B <notifications@github.com> wrote:

Sounds like we can plug BeforeDelete to invoke the strategy and validate
deletes just like we do updates (
https://github.com/GoogleCloudPlatform/kubernetes/blob/11f9fd1dcd9a0b45e2b1fdeced95b61aed153599/pkg/api/rest/update.go#L63,
https://github.com/GoogleCloudPlatform/kubernetes/blob/5520386b180d3ddc4fa7b7dfe6f52642cc0c25f3/pkg/api/rest/delete.go#L39)
and then give the pv resource a delete strategy from where they could query
pods?

—
Reply to this email directly or view it on GitHub
<https://github.com/GoogleCloudPlatform/kubernetes/issues/12084#issuecomment-126784684>
.

**Comment by markturansky** [comment]
I don't think we need a loop.  Deleting a claim is the only signal to know the user is done with the volume.   We want that object deleted first, so we need validation to prevent the volume from being deleted before the claim.

It's easy for a PV because it has ClaimRef on its Spec.  A ValidateDelete func would catch it easily.

But validating that a claim or Secret is not being used by a pod requires a query and iteration over all pods in the namespace.  I think something like that is the first of its kind.

**Comment by smarterclayton** [comment]
We're about to add it for pods that aren't on nodes, and it's how we handle
build pods and deployment pods in Openshift.  It's still a controller
rectification loop - just not an incremental one.

On Aug 3, 2015, at 7:38 PM, Mark Turansky <notifications@github.com> wrote:

I don't think we need a loop. Deleting a claim is the only signal to know
the user is done with the volume. We want that object deleted first, so we
need validation to prevent the volume from being deleted before the claim.

It's easy for a PV because it has ClaimRef on its Spec. A ValidateDelete
func would catch it easily.

But validating that a claim or Secret is not being used by a pod requires a
query and iteration over all pods in the namespace. I think something like
that is the first of its kind.

—
Reply to this email directly or view it on GitHub
<https://github.com/GoogleCloudPlatform/kubernetes/issues/12084#issuecomment-127433086>
.

**Comment by markturansky** [comment]
It could potentially surprise the hell out of a user who expects her claim to be there.  A deleted PV wouldn't go through recycling.  The data in the actual storage provider is presumably still there or at least backed up.  The PV is just a pointer to real storage.  

The deleted PV doesn't cause the pod to fail if the pod is currently running and the volume mounted.  All new pods that use that volume would fail to mount it.  I suppose it doesn't matter if the pod fails because the PV is gone or the PVC is also gone via recon loop.

The admin can restore a PV/C manually in case of error.  It's recoverable.

We leave all guarantees up to the admin anyway.  We're assuming a purposeful PV delete.

Does the pattern play out that another loop could possibly watch for missing claims to stop pods?

**Comment by smarterclayton** [comment]
On Aug 3, 2015, at 9:04 PM, Mark Turansky <notifications@github.com> wrote:

It could potentially surprise the hell out of a user who expects her claim
to be there. A deleted PV wouldn't go through recycling. The data in the
actual storage provider is presumably still there or at least backed up.
The PV is just a pointer to real storage.


Why would the PV be expected to go through recycling?  The admin might have
many reasons for deleting it - such as "take this volume out".  Even if
it's accidental, you can't override the admin by always recreating the PV -
that's even more unexpected (unless it's an option for the admin).

I don't disagree that deleting the PVC might not be the right thing to do.
See below.


The deleted PV doesn't cause the pod to fail if the pod is currently
running and the volume mounted. All new pods that use that volume would
fail to mount it. I suppose it doesn't matter if the pod fails because the
PV is gone or the PVC is also gone via recon loop.

The admin can restore a PV/C manually in case of error. It's recoverable.

We leave all guarantees up to the admin anyway. We're assuming a purposeful
PV delete.

Does the pattern play out that another loop could possibly watch for
missing claims to stop pods?


It's possible - it's also possible that we define a deleted PVC to continue
to be allowed to point to storage.  I merely wanted to identify that
generally this is a "controller loop" solution vs a "post delete actions on
the rest storage that might not ever get called".

It's also possible an admin might want to recreate the PV, or send an email
indicating something happened with extra info.

—
Reply to this email directly or view it on GitHub
<https://github.com/GoogleCloudPlatform/kubernetes/issues/12084#issuecomment-127444956>
.

**Comment by markturansky** [comment]
@thockin @smarterclayton where did this land?

Tim argued we should not allow a bound PV to be deleted.  Clayton said we should delete the PVC in a recon loop and I logically walked through what happens if we did.  Alternatively, we can unbind the PVC.

This issue is flagged P1 and is not difficult to fix, so long as we know what to do.

**Comment by smarterclayton** [comment]
So there are two issues to consider.  Why does the admin delete the PV, and
what processes may wish to delete PVs automatically without needing to know
about PVCs?  For the former, if the admin deletes it, does that mean she
expects the PVC to lose access to that disk.  For the latter, if the real
volume is deleted, does the controller loop that manages volume creation
need to indicate that the PV has been deleted to the end user?  I would
prefer that the *user* take action on the PVC in the latter case, and
possibly on the former.  In both cases, the intent is probably to deny
access to the PV (that's the natural assumption).  Does that actually block
access today?  If so, then the mechanism of communication to the user is
clear - "pod can't start because PV doesn't exist".  If it doesn't block
access today, cleaning up the PVC might make sense then (because the PVC is
the last record of the use) so they'll see their pod doesn't start because
the PVC doesn't exist.

PVC is "user requests disk, no longer needs disk".  PV is "admin wishes to
make disk available to platform, admin wishes to clean up the disk and
remove it from the platform".  I'm not sure the admin side needs to be a
hard cleanup or soft.


On Tue, Aug 25, 2015 at 11:01 AM, Mark Turansky <notifications@github.com>
wrote:

> @thockin <https://github.com/thockin> @smarterclayton
> <https://github.com/smarterclayton> where did this land?
>
> Tim argued we should not allow a bound PV to be deleted. Clayton said we
> should delete the PVC in a recon loop and I logically walked through what
> happens if we did. Alternatively, we can unbind the PVC.
>
> This issue is flagged P1 and is not difficult to fix, so long as we know
> what to do.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kubernetes/kubernetes/issues/12084#issuecomment-134595232>
> .
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by markturansky** [comment]
If a PV has been deleted and a PVC remains bound to it, any future pod using that PVC will fail.  Currently running pods would already have mounted the volume.

There are 3 errors the user will encounter when running a pod:

1.  Error finding claim (if we cascade delete the PVC after PV delete)
2.  Unbound error (if we unbind the PVC after PV delete)
3.  Missing PV (if we do nothing)

The first two above would happen in a recon loop.

All three errors above would be found in "describe pod".

**Comment by smarterclayton** [comment]
I don't think end users will have the authority to view a PV.  So the last
one won't be possible from describe in any system that is imposing real
security on the system.

Does the kubelet today assume that it has access to manipulate PVs (or at
least read them)?

On Tue, Aug 25, 2015 at 12:03 PM, Mark Turansky <notifications@github.com>
wrote:

> If a PV has been deleted and a PVC remains bound to it, any future pod
> using that PVC will fail. Currently running pods would already have mounted
> the volume.
>
> There are 3 errors the user will encounter when running a pod:
>
>    1. Error finding claim (if we cascade delete the PVC after PV delete)
>    2. Unbound error (if we unbind the PVC after PV delete)
>    3. Missing PV (if we do nothing)
>
> The first two above would happen in a recon loop.
>
> All three errors above would be found in "describe pod".
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kubernetes/kubernetes/issues/12084#issuecomment-134614506>
> .
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by markturansky** [comment]
the last error happens when a pod is trying to launch.   The persistent-claim volume plugin returns those 3 errors in order.

So, the user cannot see the PV, but they will get an error at runtime if the PV does not exist.

**Comment by lavalamp** [comment]
> As we have more and more objects referencing each other we have a real
referential-integrity problem to solve - we can't just back-link everything.

Late to the party. But traditionally, this problem is solved via having a
database enforce this. I know NoSQL thingies are all the rage, but if the
data actually references itself, it just may not be appropriate.

**Comment by bgrant0607** [comment]
Validation across objects can't be synchronous and is racy: #2457

Cascading deletes: I think we need a general GC controller for that, such as for existence dependencies: https://github.com/kubernetes/kubernetes/issues/1535#issuecomment-91413501

**Comment by bgrant0607** [comment]
If behavior is going to be different than node deletion, there had better be a compelling reason.

Node deletion causes pods on that node to be deleted. The equivalent here would be to delete the PVCs, which in turn would cause the pods attached to them to fail.

**Comment by markturansky** [comment]
The user has reasonable expectations that pods under an RC get recreated.  There is no analog that recreates deleted claims.

@bgrant0607 currently, the pods won't fail unless the volume is gone from the physical infrastructure.  Event then, I think it would only be write errors in the container logs.  Are you suggesting we delete the PVC and also purposefully fail all pods with those volumes currently in use?

I think that's the cleanest way to communicate to the user exactly what happened.  If we only unbind the claim, there are thorny questions of behavior (does it instantly rebind? your data is gone) and communication (condition/phase).  Instead we write it to the pod's events.  Whatever creates those pods can reason with the error.

**Comment by smarterclayton** [comment]
To be clear, I was not suggesting unbinding a claim. Claim binding is one
way, if you need the same data under a new claim an admin has to create
that for you after the old claim is deleted.

On Aug 26, 2015, at 10:09 AM, Mark Turansky <notifications@github.com>
wrote:

The user has reasonable expectations that pods under an RC get recreated.
There is no analog that recreates deleted claims.

@bgrant0607 <https://github.com/bgrant0607> currently, the pods won't fail
unless the volume is gone from the physical infrastructure. Event then, I
think it would only be write errors in the container logs. Are you
suggesting we delete the PVC and also purposefully fail all pods with those
volumes currently in use?

I think that's the cleanest way to communicate to the user exactly what
happened. If we only unbind the claim, there are thorny questions of
behavior (does it instantly rebind? your data is gone) and communication
(condition/phase). Instead we write it to the pod's events. Whatever
creates those pods can reason with the error.

—
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/12084#issuecomment-135007097>
.

**Comment by markturansky** [comment]
I was thinking through unbinding a claim as an alternative, but I see
deleting is cleaner.  You originally suggested we delete PVCs in a control
loop.

I think the only remaining question is whether or not to terminate all pods
currently using that claim?

**Comment by smarterclayton** [comment]
I don't think so - we don't try to provide guarantees like that for other
things.  It's assumed the admin removed the underlying resource if they
wanted that behavior.

On Aug 26, 2015, at 11:20 AM, Mark Turansky <notifications@github.com>
wrote:

I was thinking through unbinding a claim as an alternative, but I see
deleting is cleaner. You originally suggested we delete PVCs in a control
loop.

I think the only remaining question is whether or not to terminate all pods
currently using that claim?




On Wed, Aug 26, 2015 at 10:05 AM, Clayton Coleman <notifications@github.com>
wrote:

> To be clear, I was not suggesting unbinding a claim. Claim binding is one
> way, if you need the same data under a new claim an admin has to create
> that for you after the old claim is deleted.
>
> On Aug 26, 2015, at 10:09 AM, Mark Turansky <notifications@github.com>
> wrote:
>
> The user has reasonable expectations that pods under an RC get recreated.
> There is no analog that recreates deleted claims.
>
> @bgrant0607 <https://github.com/bgrant0607> currently, the pods won't fail
> unless the volume is gone from the physical infrastructure. Event then, I
> think it would only be write errors in the container logs. Are you
> suggesting we delete the PVC and also purposefully fail all pods with
those
> volumes currently in use?
>
> I think that's the cleanest way to communicate to the user exactly what
> happened. If we only unbind the claim, there are thorny questions of
> behavior (does it instantly rebind? your data is gone) and communication
> (condition/phase). Instead we write it to the pod's events. Whatever
> creates those pods can reason with the error.
>
> —
> Reply to this email directly or view it on GitHub
> <
>
https://github.com/kubernetes/kubernetes/issues/12084#issuecomment-135007097
> >
>
> .
>
> —
> Reply to this email directly or view it on GitHub
> <
https://github.com/kubernetes/kubernetes/issues/12084#issuecomment-135032360
>
> .
>

—
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/12084#issuecomment-135037597>
.

**Comment by markturansky** [comment]
Ok.

Assuming a recon loop deletes PVCs when their backing PV is deleted, the
expected system behavior, as I understand it:

1.  Future pods get a "Claim not found" error and fail.
2.  Running pods w/ active mount of PV/C will continue to run.
2a. If the volume is in the physical infrastructure, the pod functions
normally.
2b. If the volume is gone from the physical infrastructure, containers
experience read/write errors.  I don't know if this causes the container to
fail and then the pod or if the container logs get spammed with errors.

**Comment by markturansky** [comment]
@thockin @smarterclayton so where did we land with this issue?

I tend to think this is not a bug.  

Clayton argued that admins can delete PVs purposefully.  If so, the existing error handling (described by me in a previous comment) would handle the missing PV.

Cascade delete to a PVC would surprise me (as a user). 

Changing the PVC state to Pending means the PVC can be instantly rebound and my data would be gone.  That, too, would surprise me as a user.

I think it best to let the existing errors surface at runtime.

**Comment by markturansky** [comment]
I'm going to close this issue due to inactivity.  Existing error reporting tells the user when the PV has gone missing.  Admins can purposefully delete PVs.  With the ability to "pre-bind" a volume to a claim, admins can even create PVs deleted by accident that will match to an orphaned claim.
