### ISSUE TITLE
[Sig Node Presubmits] - node-kubelet-serial-containerd-alpha-features

### ISSUE THREAD

**Issue by kannon92** [kubernetes/kubernetes#120928]
https://testgrid.k8s.io/sig-node-presubmits#pr-node-kubelet-serial-containerd-alpha-features

DRA jobs are failing consistently in this presubmit.  

```
{ failed [FAILED] the server could not find the requested resource (post resourceclasses.resource.k8s.io)
In [It] at: test/e2e_node/dra_test.go:180 @ 09/27/23 12:46:23.798
}
```

/sig node
/sig testing

**Comment by kannon92** [comment]
@bart0sh any leads on this one?

**Comment by kannon92** [comment]
This gave me a lead on this one: https://github.com/kubernetes/kubernetes/issues/120927#issuecomment-1739421673

**Comment by bart0sh** [comment]
@kannon92 most probably it fails because service feature gate and runtime config are missing. You can see an example in other DRA jobs, e.g. [this one](https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-node/sig-node-presubmit.yaml#L2584). These options should be added to the `node-test-args` as far as I can see.
```
--service-feature-gates="DynamicResourceAllocation=true" --runtime-config=resource.k8s.io/v1alpha2=true
```

If above mentioned comment about `--feature-gates=AllAlpha=true` is correct, then DRA feature gate should be added as well:
```
--feature-gates="DynamicResourceAllocation=true"
```
However, I'd try to add service feature gate and a runtime config first.

**Comment by bart0sh** [comment]
@kannon92 I can take this issue if you don't mind.

**Comment by kannon92** [comment]
I have a PR https://github.com/kubernetes/test-infra/pull/30910 if you want to review

**Comment by bart0sh** [comment]
Let me test the change first.

**Comment by bart0sh** [comment]
It fails on ubuntu-gke instance as containerd 1.6 doesn't support CDI. You can either try to use containerd 1.7 and [enable CDI](https://github.com/kubernetes/test-infra/blob/master/jobs/e2e_node/dra/init-containerd-1.7.yaml#L45) or exclude DRA tests from the job.

**Comment by bart0sh** [comment]
Considering that DRA can be Beta in 1.29, I'd suggest to simply exclude tests from this job.

**Comment by kannon92** [comment]
If I exclude DRA tests, this test won't actually run any other tests.  https://testgrid.k8s.io/sig-node-presubmits#pr-node-kubelet-serial-containerd-alpha-features

Do you think we should just delete this one?

**Comment by bart0sh** [comment]
Yes, I think we should delete it. DRA is well covered by [its own jobs](https://testgrid.k8s.io/sig-node-dynamic-resource-allocation#Summary).
