### ISSUE TITLE
Long time for starting container when many pods are scheduled.

### ISSUE THREAD

**Issue by lleszczu** [kubernetes/kubernetes#12099]
I am trying to start about 50 pods on a minion, and it is taking about 2-3 minutes to start first pause container and over 15 minutes to start all containers for all pods. In docker logs I can see that kubelet is constantly listing running pods, but it doesn't start missing ones. Additionally in the same time I cannot list images, `docker images` is taking minutes to return anything ( after all pods are created, it starts working again ). I presume that kubelet is creating more requests to docker than daemon can handle.

I am using:
docker 1.7.1
kubernetes 0.19.3
kernel:  4.0.9-coreos

**Comment by fgrzadkowski** [comment]
@wojtek-t @dchen1107

**Comment by wojtek-t** [comment]
Currently Kubelet doesn't support running more that 30 pods per node. So this is not surprising that Kubelet cannot handle it now.
IIUC, Kubelet team is looking into using Docker event stream instead of relisting everything frequently. This should help a lot.
So we should be able to support more than 30 pods per node in the future (hopefully 1.1 release), but it's not the case now.

**Comment by dchen1107** [comment]
Using event stream is currently targeted for our 1.1 release, so that we could improve kubelet / docker performance and scalability to some degree.

**Comment by yujuhong** [comment]
We decided to *not* go with docker event stream for v1.2, and save that for v1.3 or beyond. That said, we've still made rather significant changes to kubelet, so that it won't hammer docker with numerous concurrent requests.

With HEAD (b3bc741d0d45422dbb0ac452cd42cafe3e13ceee) and docker v1.9.1, the time to start 50 pause pods (and wait until they are all running and ready) is ~1min. If you loosen the apiserver client QPS limit, the time becomes around 40 to 50s. 

I am going to close this issue. If you still see long startup time in batch creation, feel free to open another issue.
