### ISSUE TITLE
`kubectl create -f` and `kubectl delete -f` are not glob friendly

### ISSUE THREAD

**Issue by jbeda** [kubernetes/kubernetes#12123]
If I have a directory of YAML files, I'd love to be able to create and delete all of those easily.

For example: `kubectl create -f *.yaml`  However, this confuses the command line parsing.  If I separate things with commas, I'm good to go, but that is difficult to do with bash.  See http://stackoverflow.com/questions/3430569/globbing-pathname-expansion-with-colon-as-separator

I'd have to do something like:

``` bash
function join() {
  local IFS=$1
  shift
  echo "$*"
}
kubectl create -f $(join ',' *.yaml)
```

It would be great to have a smoother way to do this.

**Comment by bgrant0607** [comment]
I don't disagree, but FYI, you should be able to do the above with `kubectl create -f .` -- kubectl will find all .yaml files in the specified directory.

**Comment by bgrant0607** [comment]
FWIW, since I want to support putting multiple resources into the same files and directories, I imagine we'll want to be able to select a subset of the resources based on their metadata, preferably using a label selector and/or resource type -- in the client. For instance, that could be used to create all Services in the current directory with label tier=frontend.

**Comment by timothysc** [comment]
cc @jwforres

**Comment by bgrant0607** [comment]
cc @kubernetes/kubectl

**Comment by bgrant0607** [comment]
The following is not going to work:
```
kubectl <command> -f *.yaml
```
And I wouldn't expect something like that to work in any other command line, either. Flag parsing doesn't typically work that way. The flag consumes its immediately following argument, but the rest are assumed to be ordinary positional arguments, unrelated to the flags. We are not going to change that behavior. It would be extremely surprising, and unlikely to work in all commands that accept --filename (see callers of AddJsonFilenameFlag).

Cobra supports multiple instances of the same flag, so multiple `-f` flags can be passed. kubectl also generally supports the convention of comma-separated arguments. Also accepting spaces would be a non-backward-compatible change.

kubectl itself could expand globs. That would also be non-backward-compatible, but somewhat less likely to cause actual breakage.

Is it really that hard to use xargs, though?

Also, for selecting a subset of files, I'm leaning towards explicit specification, #24649, which would make it easy to pipe a list of files into kubectl.

**Comment by zhouhaibing089** [comment]
> It would be extremely surprising, and unlikely to work in all commands that accept --filename (see callers of AddJsonFilenameFlag).

Could you tell me more on the point why it is extremely surprising?

> Cobra supports multiple instances of the same flag, so multiple -f flags can be passed.

Using multiple `-f` could be accepted.

> Is it really that hard to use xargs, though?

We could use xargs to do this.

My opinion may be a little bit offending, but just for discussion: It looks like we do not support `kubectl create -f *.yaml` because we require the filenames to be a flag while an argument could only be consumed when it follows the flag immediately. 

From the perspective of engineer, I think it is fine, it keeps some consistency that we always use flags to do this sort of things. however from the perspective of user experience, it is a little bit tricky to using xargs or so, as most of cases, we are hoping it should just be there.

The the questions comes, do we really need filenames to be a flag, or being a plain arguments should be fine, too?

**Comment by bgrant0607** [comment]
Go's filepath library has support for expanding globs:
https://golang.org/pkg/path/filepath/#Glob

@zhouhaibing089 

kubectl obeys relatively standard flag conventions:
http://www.gnu.org/software/libc/manual/html_node/Argument-Syntax.html

kubectl already supports multiple `-f` flags.

Yes, we require filenames to be flags. Note that --filename/-f is supported by many commands, not just create. Most of those commands also take arguments that are not filenames (resource names), and these may be mixed on the command line.

**Comment by thockin** [comment]
We could maybe support a --ff flag meaning "consume all remaining args as
files" if this is important enough....

**Comment by smarterclayton** [comment]
we could support `--` for "everything after this is a file", at least for
create and a few other "filesystem xargs friendly".

**Comment by thockin** [comment]
`-f --` could mean everything else, so it is clear that the intent is `-f`

**Comment by smarterclayton** [comment]
I'm +1 to that, although I've never seen it used I can't think of a
reason it would fail.  The alternative is a more verbose flag
--files-as-args

**Comment by thockin** [comment]
That's what I said before, but I said -ff.  :)

> We could maybe support a --ff flag meaning "consume all remaining args as
files" if this is important enough....

**Comment by kargakis** [comment]
@kubernetes/sig-cli-misc

**Comment by thockin** [comment]
@pwittrock Keep or kill?

**Comment by bgrant0607** [comment]
/remove-lifecycle stale
/lifecycle frozen

See also #24649.

**Comment by smarterclayton** [comment]
I didn't even think about this until now, but I think we can fix this by using the args termination `--`:

```
$ find . -name *something* | kubectl create --
```

This would be roughly consistent with `git` and other commands that terminate flag processing at `--`.  This would not be backwards incompatible with our existing commands (`create`, `delete`, `get`, `describe`, `apply`, `replace`).

**Comment by mltsy** [comment]
Kinda seems like [you did think of it before](https://github.com/kubernetes/kubernetes/issues/12123#issuecomment-215124565) 😄  (Or maybe there's a distinction I'm missing!) In any case, I like it! Until there's a solution, here's an xargs example:

```bash
find ingresses/*.yaml -print0 | xargs -0 -L1 kubectl apply -f
```
(`-print0` and `-0` flags are only needed if your filenames have spaces or newlines in them, so that both programs use null characters as a separator instead of the default whitespace separator)

**Comment by apelisse** [comment]
For what it's worth, [git](https://github.com/git/git) does it's own globbing on top of shell expansion, e.g.
```sh
git diff -- '*.go' # single quotes prevents shell expansion
```

**Comment by eddiezane** [comment]
We would accept a PR with @apelisse's above solution.

/triage accepted
/help

**Comment by danielrodriguez** [comment]
I would like to take this @eddiezane
cc @seans3 @mengqiy

**Comment by eddiezane** [comment]
/assign @danielrodriguez 

Feel free to reach out on Slack if you need help.

**Comment by rothgar** [comment]
Personally, I like the option to use shell globbing and make `kubectl` more glob friendly. I read through the other issue with options and I'm in favor of supporting positional arguments (space separated) after `-f` and until another option is passed. There are plenty of 1 liners and pipes that _could_ make this work (`xargs`, `tr`) but the simplicity of space or new line separated file names is less surprising and more integrated into shell environments.

```
kubectl apply -f ./*deploy.yaml --namespace foo
```
is that more or less surprising than other tools?

```
ls ./*deploy*
mv *deploy.yaml folder/
cp .* hidden/
```
Requiring quotes makes subshell replacement work in a different way than if we accepted a list of files.
```
kubectl apply -f $(git grep -L deploy)
```
Accepting a space or newline separated list matches a lot of other shell functionality and IMO is less surprising. I'm not sure if there are any positional args in `kubectl` currently that this could cause problems with but file lists would be my preference.
