### ISSUE TITLE
DRA: How to use optional allocation ？

### ISSUE THREAD

**Issue by yingjun8** [kubernetes/kubernetes#121253]
### What would you like to be added?

I need the scheduler to support scheduling capabilities for hardware heterogeneous scenarios, similar to the optional allocation mentioned in the DRA document.

### Why is this needed?

In the same cluster, I have multiple types of heterogeneous hardware. However, these hardware resources are difficult to unify and report as the same type through device plugins. Here are my use cases:

1. I have purchased GPUs from two different manufacturers, and they are reported as resources using device plugins on two types of nodes. However, when creating a pod, I have to explicitly declare which type of GPU resource to request, and I cannot achieve optional scheduling.

2. When assigning networking to pods, some nodes are assigned virtual network cards (virtio-pci devices), while others are assigned physical network cards (physical device). I want to achieve the scheduling effect where pods uniformly request virtio-pci network cards, and if a node doesn't have it, the pod could be scheduled to a node with a physical device.

**Comment by kannon92** [comment]
cc @bart0sh

**Comment by pohly** [comment]
> I have purchased GPUs from two different manufacturers, and they are reported as resources using device plugins on two types of nodes. However, when creating a pod, I have to explicitly declare which type of GPU resource to request, and I cannot achieve optional scheduling.

Option 1:

Write a meta-DRA driver, one which replaces the controller part of the individual manufacturers. Towards apps, that driver presents an abstraction of the underlying GPU parameters. Apps must be able to use whatever programming API the GPUs provide. To do allocations, that meta driver needs to know about the CRDs used by the vendors for tracking and allocating resources.

Option 2:

Standardize a common set of parameters for GPUs, a ResourceClass name, and the corresponding programming API. Convince vendors to support this common API. The apps become portable between clusters with different hardware. This was excluded from the current KEP, but could be done separately on top of it without changes to Kubernetes. Note that with this approach, the admin would pick which vendor driver is used by the ResourceClass. Users don't need to care. 

However, only one driver is responsible for the class. For a cluster with mixed hardware it becomes a bit more tricky. I could imagine an approach where there's also a standardized driver name. When a driver sees a claim using a class with that name, then it needs to do things a bit differently:
- When checking nodes, ignore the ones where the driver has no resources, i.e. do not mark them as unsuitable. Otherwise driver A would mark nodes of driver B as unsuitable and vice versa. Nodes where neither A nor B have resources must be excluded through the ResourceClass node selector.
- When doing immediate allocation, be prepared for the other driver to finish allocation first. Only one driver can mark the claim as allocated, the other must undo the allocation.

What isn't solved yet is optional allocation. A third "fallback" driver would have to determine that a claim isn't getting allocated because both drivers are unable to do so, then mark the claim as allocated without any node-local resources associated with it. That driver then can also implement the policy that decides whether waiting for resources or proceeding without them is better.

> When assigning networking to pods, some nodes are assigned virtual network cards (virtio-pci devices), while others are assigned physical network cards (physical device). I want to achieve the scheduling effect where pods uniformly request virtio-pci network cards, and if a node doesn't have it, the pod could be scheduled to a node with a physical device.

This sounds like something that https://github.com/kubernetes/enhancements/pull/3045 might want to cover. They are standardizing an in-tree API for requesting special network interfaces with corresponding hardware.

**Comment by pranav-pandey0804** [comment]
hi @yingjun8 ,
Given the complexity of scheduling in heterogeneous hardware environments, 
have we considered leveraging Kubernetes CRDs to define specific hardware resources more granularly?

**Comment by pranav-pandey0804** [comment]
@yingjun8 
This approach could enable us to specify custom scheduling policies tailored to the unique requirements of diverse hardware types, such as GPUs from different vendors or the distinction between virtual and physical network interfaces. By defining these resources as CRDs, we might improve the scheduler's ability to make more informed decisions, aligning closely with the varied demands of workloads in these complex environments.

**Comment by pohly** [comment]
If there's a need for further discussion, then the new Device Management WG is a better place than this issue.

/close
