### ISSUE TITLE
memory-manager-policy & cpu-manager-policy value consistency (static vs Static)

### ISSUE THREAD

**Issue by sfxworks** [kubernetes/kubernetes#121423]
### What would you like to be added?

Currently, setting cpu-manager-policy to static requires lowercase
but setting memory-manager-policy to static requires uppercase S

### Why is this needed?

Minor inconvenience :)

**Comment by ffromani** [comment]
we can't rename the cpumanager options (as a sidenote, I personally prefer the lowercase version. Not really relevant though) because the feature is GA now.
We _can_ theoretically discuss the rename of the memory manager option because it's beta, even though this is quite unusual and likely to break existing user workflows.
If memory serves, the uppercase `Static` for memory manager was requested during the API review - so it seems intentional and not a oversight.

cc @Tal-or
