### ISSUE TITLE
Setting Initial Resources

### ISSUE THREAD

**Issue by jszczepkowski** [kubernetes/kubernetes#12149]
sub-issue of #10782

**Comment by smarterclayton** [comment]
@derekwaynecarr

**Comment by piosz** [comment]
*design proposal*

Since we want to make Kubernetes as simple as possible for its users we don’t want to require setting [Resources](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/api/v1/types.go#L696) for container by its owner. On the other hand having Resources filled is critical for scheduling decisions. Current solution to set up Resources to hardcoded value has obvious drawbacks. We need to implement a component which will set initial Resources to a reasonable value.

### Design
The component will be implemented as an [admission plugin](https://github.com/GoogleCloudPlatform/kubernetes/tree/master/plugin/pkg/admission) and invoked right before [LimitRanger](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cluster/gce/config-default.sh#L91). For every container without Resources specified it will try to predict amount of resources that should be sufficient for it. So that a pod without specified resources will be treated as Burstable (see more details #11713). The component will set only [Request](https://github.com/GoogleCloudPlatform/kubernetes/blob/3d2d99c6fd920386eea4ec050164839ec6db38f0/pkg/api/types.go#L691) field in the first version to avoid killing containers due to OOM (however the container still may be preempted if exceeds requested resources) . The container won’t be marked as managed by this component in any way, however appropriate event will be exported. The predicting algorithm should be simple to not increase significantly e2e pod startup latency #3954.

### Algorithm
In the first version estimation will be made based on historical data for the Docker image being run in the container (both the name and the tag matters). CPU/memory usage of each container is exported periodically (by default with 1 minute resolution) to the backend. The component will set Request for both cpu/mem as the 90th percentile of such samples (for exactly the same image - the same name and tag) from last 30 days and based on no more than 1000 youngest samples. If there is not enough data (at least 10 samples) it will take also samples with the same name and possible different tags. If there is still no data the default value will be used. All those values will be easily configurable with appropriate flags.

In the future other features will be added to the model like namespace. It may be also worth to consider handling special cases when the tag of the image is dev or canary and having some predefined values for well known containers like nginx or redis.

### Monitoring pipeline
In the first version there will be available 2 options for backend for predicting algorithm:
* [InfluxDB](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/user-guide/monitoring.md#influxdb-and-grafana) - aggregation will be made in SQL query
* [GCM](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/user-guide/monitoring.md#google-cloud-monitoring) - since GCM is not as powerful as InfluxDB some aggregation will be made on the client side 

Both will be hidden under an abstraction layer, so it would be easy to add another option.

cc @bgrant0607 @davidopp @erictune @vmarmol @vishh @smarterclayton @derekwaynecarr

**Comment by derekwaynecarr** [comment]
I think this will be a good help in OpenShift for getting good resource heuristics for our builder pods, so this is an interesting feature.

Questions:

1. Assuming no historical data, it will pick up what is specified in **LimitRanger**?
2. Does the heuristic take into account just the docker image name or any of its associated tags?  It would be very interesting to be able to build a model that could be informed based on the named image's immediate ancestor.
3. I think for our use, the **Namespace** is a key part of the heuristic.  There will be some apps on the cluster that use mysql that require very few resources versus others that require much more.  I am not sure a single 90th percentile is sufficient, but I need to reflect on that more.
3.  I think this will be interesting for OpenShift in getting good values for our pods that drive builds.  It would be interesting to be able to configure the admission plug-in to only apply its heuristics on pods with specific labels.

cc @ncdc

**Comment by piosz** [comment]
To address you questions:
1. Yes.
2. If there is enough data for the specific image (the same name and tag) then it will be used. Otherwise algorithm will try to estimate based on historical data of for the same name and possible different tags.
3. I wrote about it. I'd like to add namespace in the second iteration.
4. The heuristic will be applied only for containers without request specified. In the case you described the default value from LimitRanger will be set. If you think you need such feature I'm happy to add possibility to disable setting initial resources by adding label "setInitialResources=no".

**Comment by derekwaynecarr** [comment]
@piosz - Running this admission control makes pods in the BestEffort QoS tier not possible anywhere in the cluster.  Is this intended?  Should it be enabled on a per namespace basis?  For us, I could see us wanting this feature to only work on select pods within a namespace (i.e. our builds and deployments), but maybe not all of them.  This is why I wondered if we could provide a label to turn the feature on rather than turn it off.

**Comment by piosz** [comment]
@derekwaynecarr If the request is set to 0 the pod will be in BestEffort tier. If the request is not specified InitialResources plugin will take care of the pods. This is similar to the current solution when LimitRanger will take care of pods without limits (and possibly request in the future).

Are you ok with proposed solution to explicitly exclude pods from setting initial resources?

**Comment by smarterclayton** [comment]
Can you describe what you mean by abstraction layer to hide the calls?  We
are currently planning on running heapster + hawkular as a metrics backend
for this sort of data.  Would you expect heapster to be answering this
query behind the abstraction, and then heapster to call out to a GCM /
Influx backend?  If so, as long as we could add similar support in Hawkular
we'd be ok.

On Wed, Aug 5, 2015 at 3:45 PM, Piotr Szczesniak <notifications@github.com>
wrote:

> @derekwaynecarr <https://github.com/derekwaynecarr> If the request is set
> to 0 the pod will be in BestEffort tier. If the request is not specified
> InitialResources plugin will take care of the pods. This is similar to the
> current solution when LimitRanger will take care of pods without limits
> (and possibly request in the future).
>
> Are you ok with proposed solution to explicitly exclude pods from setting
> initial resources?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleCloudPlatform/kubernetes/issues/12149#issuecomment-128126716>
> .
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by piosz** [comment]
There will be data source interface with 2 implementations:
- InfluxDB, which will query InfluxDB
- GCM, which will query GCM and make some aggregation

The interface will be simple like get n-th percentile of the specified metric from specified window with given limit of samples.
 
I'm not familiar with Hawkular but you probably may add another implementation here.

**Comment by smarterclayton** [comment]
@mwringe can you weigh in here - ideally anything we do in the default Kube
setup we can back with heapster/hawkular

On Aug 6, 2015, at 1:04 AM, Piotr Szczesniak <notifications@github.com>
wrote:

There will be data source interface with 2 implementations:

   - InfluxDB, which will query InfluxDB
   - GCM, which will query GCM and make some aggregation

The interface will be simple like get n-th percentile of the specified
metric from specified window with given limit of samples.

I'm not familiar with Hawkular but you probably may add another
implementation here.

—
Reply to this email directly or view it on GitHub
<https://github.com/GoogleCloudPlatform/kubernetes/issues/12149#issuecomment-128242725>
.

**Comment by mwringe** [comment]
The problem with Heapster is that I am not sure if it will return the right values for the type of CPU usage you are wanting here. Currently Heapster only returns the total nanoseconds of CPU usage since the container was started (which doesn't really help). So someone might have to work with Heapster to expose more meaningful data.

If we have the right data going into Hawkular Metrics, we should be able to get back the results that you are looking for (eg n-th percentile within a given period). It doesn't look like the current implementation supports arbitrary percentile amounts (bucket data currently return 95th percentile by default) but it should be trivial to add in that kind of support.

So is this meant to directly connect with Hawkular Metrics then? Or is the plan to route things through heapster directly? Eg heapster becomes the metric handling endpoint which stores and fetches things from its sinks?

**Comment by piosz** [comment]
Heapster exports cumulative cpu usage per container. There are two possibilities: export also [cpu/usage_rate](https://github.com/GoogleCloudPlatform/heapster/blob/master/sinks/gcm/rate_metrics.go#L29) metric as it is done for GCM or assume the data source can convert cumulative -> gauge (not sure but I think InfluxDB can do it). Which of this is an option for Hawkular?

The component will directly query the data source (InfluxDB, GCM, Hawkular, any other provided). If there will be support in Heapster for fetching data from sinks it may be also considered data source but we don't want to block on this feature.

**Comment by smarterclayton** [comment]
On Aug 6, 2015, at 2:41 PM, mwringe <notifications@github.com> wrote:

The problem with Heapster is that I am not sure if it will return the right
values for the type of CPU usage you are wanting here. Currently Heapster
only returns the total nanoseconds of CPU usage since the container was
started (which doesn't really help). So someone might have to work with
Heapster to expose more meaningful data.

If we have the right data going into Hawkular Metrics, we should be able to
get back the results that you are looking for (eg n-th percentile within a
given period). It doesn't look like the current implementation supports
arbitrary percentile amounts (bucket data currently return 95th percentile
by default) but it shouldn't be trivial to add in that kind of support.

So is this meant to directly connect with Hawkular Metrics then? Or is the
plan to route things through heapster directly? Eg heapster becomes the
metric handling endpoint which stores and fetches things from its sinks?


I'd be ok with a pluggable backend direct to hawkular - since it sounds
like the expectation isn't that heapster services these queries.  Someone
using heapster to collect CPU for other purposes can then talk to influx or
hawkular directly for this path.


—
Reply to this email directly or view it on GitHub
<https://github.com/GoogleCloudPlatform/kubernetes/issues/12149#issuecomment-128467802>
.

**Comment by mwringe** [comment]
>Heapster exports cumulative cpu usage per container. There are two possibilities: export also cpu/usage_rate metric as it is done for GCM or assume the data source can convert cumulative -> gauge (not sure but I think InfluxDB can do it). Which of this is an option for Hawkular?

InfluxDB uses a derivative aggregation function to convert the cumulative value. 

For hawkular, since we don't have something like a derivative function, we will probably have to do the same thing that GCM does and expose the usage_rate

>I'd be ok with a pluggable backend direct to hawkular

Ok

**Comment by piosz** [comment]
Moved proposal to a doc. See #12472.
