### ISSUE TITLE
Use SSA for DisruptionTarget Pod conditions

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes/kubernetes#121678]
### What would you like to be added?

Use SSA instead of Patch.

Essentially, revert https://github.com/kubernetes/kubernetes/pull/121103
Although it might be desirable to leave Update for the disruption target garbage collector.

/sig apps

### Why is this needed?

With #113482 fixed, we can use SSA again.

**Comment by kaisoz** [comment]
/assign

I can work on this 😊 cc @mimowo

**Comment by mimowo** [comment]
> Essentially, revert #121103

Not exactly, reverting the PR would mean using SMP (Strategic-Merge Patch) for SSA in unit tests. This was discussed as not the right thing to do, see: https://github.com/kubernetes/kubernetes/issues/116851. 

The options I can see:
1. wait for https://github.com/kubernetes/kubernetes/pull/118211 to support unit tests
2. in the code of the unit tests install an observer which applies SMP, but don't do it at the global level
3. in the code of the unit tests install an observer which hardcodes the object modifications for matched patches

My preference is (1.), but provided the support is going to happen for 1.30, @apelisse do you have capacity working on this for 1.30?

If (1.) is not an option, I would go for (2.) for code simplicity, just add TODO(https://github.com/kubernetes/kubernetes/issues/116851), to replace SMP once https://github.com/kubernetes/kubernetes/pull/118211 is merged.

cc @alculquicondor @liggitt 

> Although it might be desirable to leave Update for the disruption target garbage collector.

I would use SSA for consistency. Here we use Update just so that it fails in case there was a concurrent update (based on ResoureVersion bump). This semantics can be expressed using SSA and passing the ResourceVersion as in the reverted PR.

**Comment by mimowo** [comment]
Ah, I just realized the revert would technically work, because we still have this line: https://github.com/kubernetes/kubernetes/blob/0c645922edcc06adff43c70c02fb56751364bbb5/staging/src/k8s.io/client-go/testing/fixture.go#L184. The line remains there, because there are other unit tests still relying on it: https://github.com/kubernetes/kubernetes/pull/116855#issuecomment-1787576774.

But it is highly questionable we want to go this path, so maybe until we have the proper testing framework we could do (2.). Still, asking @alculquicondor @liggitt @apelisse for the suggested way forward.

**Comment by kaisoz** [comment]
@mimowo does this still make sense?

cc @alculquicondor

**Comment by mimowo** [comment]
> @mimowo does this still make sense?

We don't have (as far as I'm aware) any issues with adding the DisruptionTarget conditions using SMP, that would be solved by SSA, so I consider it cleanup at this point.

Something might have changed, but a while ago we didn't have a good unit testing approach for SSA as mentioned in the [comment](https://github.com/kubernetes/kubernetes/issues/121678#issuecomment-1849814903). 

I would prefer to get input from API reviewers / approvers first.

**Comment by alculquicondor** [comment]
wasn't this completed already?
