### ISSUE TITLE
ReplicaSet naming is inconsistent

### ISSUE THREAD

**Issue by majanjua-amzn** [kubernetes/kubernetes#121687]
### What happened?

When kubernetes is creating a ReplicaSet automatically through a deployment, the suffix added to the deployment name has an inconsistent length. Although this is not necessarily a bug, this can lead to issues in trying to identify ReplicaSets that were created through deployments using, for instance, RegEx.

[This code](https://github.com/kubernetes/kubernetes/blob/9754e404390a8d4e969e17e339586376b6f6ad8f/pkg/controller/controller_utils.go#L1201) is responsible for creating a suffix string to add to the deployment name to create the ReplicaSet name. The number created by `podTemplateSpecHasher.Sum32()` is any number from 0 to 4,294,967,295. This means the suffix string after the number goes through `rand.SafeEncodeString` ([link](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/util/rand/rand.go#L121)) will have a length of 0 to 10.

### What did you expect to happen?

ReplicaSet names should always have a suffix of consistent length when created automatically via a deployment.

### How can we reproduce it (as minimally and precisely as possible)?

Create a number of deployments that will in turn create ReplicaSets. On average, 23% of these ReplicaSets will have suffixes of length 9 or shorter instead of the expected 10.

### Anything else we need to know?

An easy solution would be to simply change the code as follows:
```
return rand.SafeEncodeString(fmt.Sprintf("%0*d", 10, podTemplateSpecHasher.Sum32()))
```
There is no risk to a solution like this as it will only go into effect when new ReplicaSet revisions are created and will only make ReplicaSet names more consistent. Any names that would be generated out of a number like 1,234,567 will instead be generated by 0,001,234,567, i.e. there is the same number of possible suffixes as before.

### Kubernetes version

Doesn't really matter but:
```console
$ kubectl version
Client Version: v1.28.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Unable to connect to the server: dial tcp: lookup ...: no such host
```

### Cloud provider

Not sure what this means.

**Comment by sftim** [comment]
> this can lead to issues in trying to identify ReplicaSets that were created through deployments using, for instance, RegEx

I'm not sure that's a bug. A better way is to match via labels or via `ownerReferences`.

/priority awaiting-more-evidence

Also:
/remove-sig cluster-lifecycle

**Comment by majanjua-amzn** [comment]
I agree, but there's no reason not to add this small quality of life improvement to help identify resources. In large scale systems, looking through all pods and replicasets for their owners may put a unwanted load on the EKS control plane when using the name directly may be a more reasonable solution.

**Comment by majanjua-amzn** [comment]
Proof:
- Golang documentation for Hash shows it generates a uint32: [link](https://pkg.go.dev/hash)
- Code shows the following: [link](https://cs.opensource.google/go/go/+/refs/tags/go1.21.3:src/builtin/builtin.go;l=34)
```
// uint32 is the set of all unsigned 32-bit integers.
// Range: 0 through 4294967295.
type uint32 uint32
```

**Comment by toVersus** [comment]
It can be improved, but using regular expressions to identify ReplicaSets may not be the good approach. This is because the number of random characters is not guaranteed and could change in the future. For example, in the case of Pods, there was an attempt to increase the length of random characters from 5 to 10. In the end, there were several projects relying on parsing random strings, and the PR is currently on hold due to a lack of a good alternative (https://github.com/kubernetes/kubernetes/pull/116430, https://github.com/gocrane/crane/issues/716).

cc: @thockin

**Comment by thockin** [comment]
A few thoughts:

0) If, by chance, the hash ends up as 0 and we produce "" rather than "0", then that is a bug and should be fixed.

1) Regex parsing pod names to extract things like RS or deployment names IS NOT SUPPORTED.  We paused an effort to actively change this, because we don't want to break users, but it's already broken for very long names. If it works, it works by luck.  We should not endorse this pattern.

2) If doing this "right"  represents a real hardship for consumers, we should think up a better pattern that is more supportable. Please bring evidence. 

3) I am not against the idea of leading 0s, per se, but it has non-zero risk of breaking people who already parse this, and it sort of encourages this anti-best-practice of pattern matching. So I don't think it's worthwhile.

**Comment by thockin** [comment]
Hey sig-apps people,

I think we should close this, but maybe you think it's important to ensure that the RS suffix is always 10 chars?

@janetkuo @kow3ns @soltysh

**Comment by janetkuo** [comment]
I think we can close this one. As folks mentioned above we don't support or encourage parsing names, and I don't see evidence that RS suffix length could cause issues.
