### ISSUE TITLE
vSphere installation on clean ESXi failed

### ISSUE THREAD

**Issue by bsideup** [kubernetes/kubernetes#12191]
Hi!

I'm trying to install k8s on clean ESXi. But on `cluster/kube-up.sh` I'm getting following:

```bash
$ cluster/kube-up.sh
Starting cluster using provider: vsphere
... calling verify-prereqs
... calling kube-up
Starting master VM (this can take a minute)...
Error: datastore directory does not exist
```

Any idea why? 

Thanks

**Comment by goltermann** [comment]
We’re going through old support issues and asking everyone to direct your questions to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes). 

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases. 

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.
