### ISSUE TITLE
Minimize ensuring kube chains and jump rules

### ISSUE THREAD

**Issue by aroradaman** [kubernetes/kubernetes#121933]
### What happened?

IPVS proxier currently ensures kube-chains and jump rules on ever sync loop. These calls are expensive and consumes roughly 32% of CPU time of the sync loop. IPTables doesn't ensure the jump chains on every sync loop. https://github.com/kubernetes/kubernetes/pull/114181. 

https://github.com/kubernetes/kubernetes/blob/8509ab82b96caa2365552efa08c8ba8baf11c5ec/pkg/proxy/ipvs/proxier.go#L1744-L1765

<img width="1727" alt="Screenshot 2023-11-17 at 1 21 14 AM" src="https://github.com/kubernetes/kubernetes/assets/6954627/d44ccd7f-2832-44e2-97ec-7185efbf4609">

### What did you expect to happen?

Ensure chain/rules should not happen on every sync call. 

This only happens in IPTables if `proxier.needFullSync is true` which was introduced during `MinimizeIPTablesRestore` but as this feature got graduated there is no way to disable it. 

Maybe we can have the IPVS backend behave similarly ... or introduce a new feature to gate it ?

sig/network
area/ipvs

cc. @uablrek 

### How can we reproduce it (as minimally and precisely as possible)?

This happens on every sync loop.

### Kubernetes version

<details>

```console
$ kubectl version
Server Version: v1.29.0-alpha.3.65+194e4d537525a1
```

</details>

### Cloud provider

<details>
Kind
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by uablrek** [comment]
Good initiative! I must check how the iptables proxier does it. A full compare, a partial or none?. A "problem" (if you call it that) is _ipset_. It is likely as cheap to re-write them as to read/compare. Ipset also has an atomic operation "ipset swap" that should be used (it is already afaik). Ipvs config should be simple since we can assume that we are the only user.

I am a bit reluctant to polish the ipvs proxier since the [nft proxier](https://github.com/kubernetes/enhancements/tree/master/keps/sig-network/3866-nftables-proxy) is on it's way, which will [fix all things](https://github.com/kubernetes/enhancements/pull/3824#issuecomment-1417978134).

**Comment by aroradaman** [comment]
/close

> I am a bit reluctant to polish the ipvs proxier since the [nft proxier](https://github.com/kubernetes/enhancements/tree/master/keps/sig-network/3866-nftables-proxy) is on it's way, which will https://github.com/kubernetes/enhancements/pull/3824#issuecomment-1417978134.
