### ISSUE TITLE
Scheduler evaluates many nodes even if there are no scoring plugins defined

### ISSUE THREAD

**Issue by aleksandra-malinowska** [kubernetes/kubernetes#122057]
### What happened?

Even when no scoring plugins are defined, scheduler always attempts to find multiple nodes where the pod can run. This is unnecessary (and therefore inefficient) when we know ahead of time that there will be no difference between how those nodes are scored. 

### What did you expect to happen?

If we're going to pick a random node, we can just as well cut short the search after finding the first match.

### How can we reproduce it (as minimally and precisely as possible)?

Configure scheduler without any scoring plugins and see that mulitple nodes are evaluated anyway.

### Anything else we need to know?

/cc @ahg-g @alculquicondor 
/sig scheduling
/kind bug

### Kubernetes version

1.29 and older

### Cloud provider

N/A

**Comment by sanposhiho** [comment]
/reopen 

It's reverted because of the flaky test.
https://github.com/kubernetes/kubernetes/pull/122317

**Comment by alculquicondor** [comment]
/reopen
Reverted again, because it causes problems for Filter extenders.

However, the existing implementation could also run into the problem of declaring a Pod unschedulable prematurely:
The default numNodesToFind is 100. If it happens to be the case that the extenders reject these 100 nodes, but there is another node that would pass the extender, we still reach this situation, wouldn't we?
