### ISSUE TITLE
Kubernetes-Etcd vs Kubernetes-Redis

### ISSUE THREAD

**Issue by kgrvamsi** [kubernetes/kubernetes#12255]
Hello,

Lets take if i have a Machine which runs a Redis cluster to manage my Browser cookie sessions are for any Secrets then can i make my kubernetes cluster to use it for any key-value distribution instead using it up with etcd.

Incase not then how exactly it differs from a ETCD way of storing the key values with the Redis way of working.

Is there any integration planned for kube-Apiserver to be linked to the Redis cluster and Api server which serves inreturn to the minions as a place to store like how it does with etcd.

**Comment by erictune** [comment]
I think you are asking whether you can have kubernetes apiserver storing its state in Redis instead of etcd.  This is definitely not possible right now.  People have looked at substituting Consul for etcd (#1957).  

I think you are also saying that, if kubernetes apiserver could store its state in redis, you would want to use the same redis instance for both kubernetes state and browser cookie state.  I don't think this is a good idea.  The latency, size, and durability requirements for kubernetes apiserver state and for browser cookies (for a busy site) are going to be quite different.  For example, for kubernetes state, you are going to want redis to append ever change to a log and fsync after ever change, because you don't want to lose any apiserver state.  For browser cookies, you can get by with a less durable storage but probably can't afford the performance hit of syncing the log every time.   You want two different storage systems, I think.

**Comment by kgrvamsi** [comment]
@erictune  Thanks for your reply and yes may be i can create two different redis cluster which can manage the browser cookies and for some other app requirement another redis cluster and which i will be using the kubernetes cluster point to the second redis cluster.

And i see a point about the state changes of Api server but how different does it impact in case of performance or scalability when we compare it with etcd and redis.Yes i see Consul can be a good fit for kubernetes to act as a Key-Value storage and Consul have many more things which kubernetes needs it at this point.

**Comment by mbforbes** [comment]
@kgrvamsi based on your reply I'm going to assume that @erictune's response answered your question and close the issue. Please feel free to re-open if not! Cheers.

**Comment by abhi-jha** [comment]
Can redis be used to substitute etcd entirely just for apiserver state? Not storing anyting in it, except for k8s things. Redis does provide fsyncing to disk, though with a perf hit but that shoudln't really be a problem.
