### ISSUE TITLE
pv pvc is bound but deployment has error about can not find volume

### ISSUE THREAD

**Issue by 13567436138** [kubernetes/kubernetes#122599]
### What happened?

```
  Warning  FailedMount             2s (x4 over 7s)  kubelet                  MountVolume.MountDevice failed for volume "cephfs-pv" : rpc error: code = Internal desc = rpc error: code = Internal desc = volume not found
root@karmada-03-a:~# kubectl get pv
NAME        CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                      STORAGECLASS   REASON   AGE
cephfs-pv   1Gi        RWX            Delete           Bound    default/nginx-html-claim                           62s
root@karmada-03-a:~# kubectl get pvc
NAME               STATUS   VOLUME      CAPACITY   ACCESS MODES   STORAGECLASS   AGE
nginx-html-claim   Bound    cephfs-pv   1Gi        RWX                           87s
```

### What did you expect to happen?

deploy can run

### How can we reproduce it (as minimally and precisely as possible)?

install rook
create pv pvc manually，
deploy deployment vith pvc

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```
1.18.1
</details>

### Cloud provider

<details>

</details>
vmware

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by carlory** [comment]
The error message indicates that csi driver cannot find the volume from rook ceph cluster. It's not a bug of kubernetes or csi driver. 

It looks like a configuration issue of your manifest file. Please check the following items:

1. Please make sure the ceph cluster is running healthy and the corresponding volume exists in your ceph cluster. You can use ceph command or ceph dashboard to check it.
2. Please make sure pv's `volumeHandle` is correct.

It's not kubernetes bug. It's better to open an issue in the [csi driver's github repo](https://github.com/ceph/ceph-csi) because the csi driver's author is more familiar with the driver.

BTW, before you open an issue, please collect more information, such as the ceph cluster's volume status, the pv's yaml file, the csi driver's log, etc. otherwise, it's hard for others to find the root cause.

/triage needs-information
/remove-kind bug
/kind support
