### ISSUE TITLE
Metric process_start_time_seconds is not defined for /metrics/slis

### ISSUE THREAD

**Issue by courageJ** [kubernetes/kubernetes#122520]
### What would you like to be added?

/metrics/slis was added for several components (apiserver, kube-controller-manager, kube-scheduler, kubelet, cloud-controller-manager) in https://kep.k8s.io/3466

This is to propose adding metric `process_start_time_seconds` to these components  for /metrics/slis to support cumulative metric `kubernetes_healthchecks_total`

### Why is this needed?

Missing start time metric in metrics/slis will result in inaccurate cumulative metrics.

Even though the start time metric is available in /metrics, it requires the metrics collector to scrape two endpoints at once and sync them to prepare the cumulative metric data.

**Comment by courageJ** [comment]
@logicalhan

**Comment by dashpole** [comment]
/assign @logicalhan 
cc @Richabanker 
/triage accepted

**Comment by dgrisonnet** [comment]
@richabanker @logicalhan I just ran into an issue related to this change while adding scrapers to /metrics/slis in kube-prometheus https://github.com/prometheus-operator/kube-prometheus/issues/2500.

The components /metrics and /metrics/slis endpoints are supposed to be scraped together, but at different intervals and this is really possible anymore since we added the `process_start_time_seconds` metric to the /metric/slis endpoint since now both endpoints are exposing the same metric which causes a conflict when scraped by Prometheus.

Instead of exposing the `process_start_time_seconds` metric inside of the `/metrics/slis` endpoint, I think we should rather expect users to correlate the `kubernetes_healthchecks_total` metric with the process start time metric from the `/metrics` endpoint. Because otherwise, we have to explicitly drop the `process_start_time_seconds` metric at scrape time from the SLI endpoint in order to avoid conflicts.

**Comment by logicalhan** [comment]
> Instead of exposing the `process_start_time_seconds` metric inside of the `/metrics/slis` endpoint, I think we should rather expect users to correlate the `kubernetes_healthchecks_total` metric with the process start time metric from the `/metrics` endpoint. Because otherwise, we have to explicitly drop the `process_start_time_seconds` metric at scrape time from the SLI endpoint in order to avoid conflicts.

We can't not include it, what if people opt only to scrape `metrics/slis`?

**Comment by dgrisonnet** [comment]
That's a fair point, but do we really need `process_start_time_seconds` to make use of the cumulative metric? Computing an error rate from it shouldn't require a start time, and even in the event of a restart, it should be transparent to the computation of the rate.

**Comment by logicalhan** [comment]
> That's a fair point, but do we really need `process_start_time_seconds` to make use of the cumulative metric? Computing an error rate from it shouldn't require a start time, and even in the event of a restart, it should be transparent to the computation of the rate.

Yes, you need process-start-time in order to now when a process has restarted otherwise a cumulative metric could be (1) not cumulative going from 2 -> 1, (2) be cumulative but not measured as such if you measure 1 with process-start-time A, and then you measure 1 again with process-start-time B.

**Comment by logicalhan** [comment]
> > That's a fair point, but do we really need `process_start_time_seconds` to make use of the cumulative metric? Computing an error rate from it shouldn't require a start time, and even in the event of a restart, it should be transparent to the computation of the rate.
> 
> Yes, you need process-start-time in order to know when a process has restarted otherwise a cumulative metric could be (1) not cumulative going from 2 -> 1, (2) be cumulative but not measured as such if you measure 1 at process-start-time A, and then you measure 1 again at process-start-time B, but you ignore process-start-times.
