### ISSUE TITLE
Kublet stopped and resulted in a Not Ready state

### ISSUE THREAD

**Issue by kgrvamsi** [kubernetes/kubernetes#12269]
Output of Kubectl on the Master\

    Every 2.0s: kubectl get nodes                                                                                                                     Wed Aug  5 12:46:14 2015

    NAME                           LABELS                                                                    STATUS
    ip-10-20-30-191.ec2.internal   kubernetes.io/hostname=ip-10-20-30-191.ec2.internal,servicegrp=registry   Ready
    ip-10-20-30-192.ec2.internal   kubernetes.io/hostname=ip-10-20-30-192.ec2.internal                       NotReady
    ip-10-20-30-45.ec2.internal    name=Minion01                                                             NotReady

Output of Kubelet on the Minion

    Aug 04 10:36:29 ip-10-20-30-45.ec2.internal kubelet[24682]: I0804 10:36:29.308218   24682 fs.go:93] Filesystem partitions: map[/dev/xvda9:{mountpoint:/ major:202 minor:9} /dev/xvda3:{mountpoint:/usr major:202 minor:3} /dev/xvda6:{mountpoint:/usr/share/oem major:202 minor:6}]
    Aug 04 10:36:29 ip-10-20-30-45.ec2.internal kubelet[24682]: I0804 10:36:29.309408   24682 manager.go:156] Machine: {NumCores:1 CpuFrequency:2500064 MemoryCapacity:2101297152 MachineID:7ed89a15583e404bb7742dc2992124f7 SystemUUID:EC24072B-2BF5-A85C-BE28-AC83B4414A5E BootID:4f5966c9-2112-4352-a996-09f1861c69e9 Filesystems:[{Device:/dev/xvda6 Capacity:113229824} {Device:/dev/xvda9 Capacity:5843333120} {Device:/dev/xvda3 Capacity:1031946240}] DiskMap:map[202:0:{Name:xvda Major:202 Minor:0 Size:8589934592 Scheduler:cfq}] NetworkDevices:[{Name:eth0 MacAddress:0a:39:5e:17:62:15 Speed:0 Mtu:9001} {Name:flannel.1 MacAddress:16:1d:2d:13:e6:fa Speed:0 Mtu:8951}] Topology:[{Id:0 Memory:2101297152 Cores:[{Id:0 Threads:[0] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]}] Caches:[{Size:26214400 Type:Unified Level:3}]}]}

Output of Kube-Proxy on the Minion
  
    Aug 05 12:29:50 ip-10-20-30-45.ec2.internal kube-proxy[31746]: W0805 12:29:50.124005        31746 api.go:224] Got error status on WatchEndpoints channel: &{TypeMeta:{Kind: APIVersion:}   ListMeta:{SelfLink: ResourceVersion:} Status:Failure Message:EOF Reason: Details:<nil> Code:0}
    Aug 05 12:30:00 ip-10-20-30-45.ec2.internal kube-proxy[31746]: W0805 12:30:00.611559   31746 api.go:153] Got error status on WatchServices channel: &{TypeMeta:{Kind: APIVersion:} ListMeta:{SelfLink: ResourceVersion:} Status:Failure Message:EOF Reason: Details:<nil> Code:0}
    Aug 05 12:35:22 ip-10-20-30-45.ec2.internal kube-proxy[31746]: W0805 12:35:22.094281   31746 api.go:224] Got error status on WatchEndpoints channel: &{TypeMeta:{Kind: APIVersion:} ListMeta:{SelfLink: ResourceVersion:} Status:Failure Message:EOF Reason: Details:<nil> Code:0}
    Aug 05 12:35:31 ip-10-20-30-45.ec2.internal kube-proxy[31746]: W0805 12:35:31.972513   31746 api.go:153] Got error status on WatchServices channel: &{TypeMeta:{Kind: APIVersion:} ListMeta:{SelfLink: ResourceVersion:} Status:Failure Message:EOF Reason: Details:<nil> Code:0}

Some what when i restarted the Kublet and Kube-Proxy on the minion it shows Ready

**Comment by dchen1107** [comment]
is docker running properly on your minion?

**Comment by kgrvamsi** [comment]
Yes Docker is running Properly on the Minions and as i said when i restarted the kubelet and kube-proxy it changed to ready state.

**Comment by kgrvamsi** [comment]
@brendanburns  @dchen1107  this is happening today as well all of a sudden the minions go to Not Ready state

**Comment by dchen1107** [comment]
cc/ @vishh and @yujuhong

**Comment by vishh** [comment]
Can you post the output of `kubectl get events` ?

**Comment by yujuhong** [comment]
@kgrvamsi, could you also post kubelet.log and kube-proxy.log to somewhere we have access to (e.g. http://gist.github.com)? They should include the time frame where the node went to the NotReady state.

**Comment by kgrvamsi** [comment]
Sorry for the late reply and will get back to this issue as i have created another new cluster and i'm watching on its changes

**Comment by kgrvamsi** [comment]
@vishh  @yujuhong  here is the output log of the thing you asked for

http://pastebin.com/raw.php?i=sx3CAr7K

**Comment by vishh** [comment]
The events are old. I see a systemd service dependency check failure.
```shell
Aug 15 12:16:47 ip-10-20-30-45.ec2.internal systemd[1]: Dependency failed for Kubernetes Kubelet.
Aug 15 12:16:47 ip-10-20-30-45.ec2.internal systemd[1]: kube-kubelet.service: Job kube-kubelet.service/start failed with result 'dependency'.
```
What are the dependencies for kubelet service? Docker?

**Comment by goltermann** [comment]
We’re going through old support issues and asking everyone to direct your questions to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes). 

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases. 

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

**Comment by thinhduckhoi** [comment]
Seems like nonody care about stackoverflow anymore. I asked some questions on that and didn't even get any answers.

**Comment by bprashanth** [comment]
@thinhduckhoi what's your question?

**Comment by thinhduckhoi** [comment]
@bprashanth finally there was one guy who replied to my question. But seems like we didn't find a solution. Could you take a look at it and find out what happen? 
http://stackoverflow.com/questions/35076073/kubernetes-cluster-a-dependency-job-for-kubelet-service-failed/35089108?noredirect=1#comment57973789_35089108

**Comment by bprashanth** [comment]
I can try, but the reason no one answered for so long is probably because you're following a totally non-standard setup based on a blog post. I'd suggest picking one of the getting started guides (maybe the one for centos http://kubernetes.io/v1.1/docs/getting-started-guides/centos/centos_manual_config.html?) because the community is familiar debugging those problems, and we can git blame the doc in question.

**Comment by thinhduckhoi** [comment]
I didn't know that was not the standard setup :( But to be honest, i tried the kubernetes official tutorial first with no luck. Let me tell you something, that official tutorial is a little bit old because the "baseurl http://cbs.centos.org/repos/virt7-testing/x86_64/os/" didn't exists, i tried to find some alternative baseurl like "virt7-docker-common-release" but the configuration file is absolutely different and i don't know how to do. Could you please give it a test?

**Comment by bprashanth** [comment]
Maybe @coolsvap who contributed the manul centos configuration docs can shed some light?

**Comment by bprashanth** [comment]
Eitherway this is not the right place to discuss outdated docs, lets continue on https://github.com/kubernetes/kubernetes/issues/20460
