### ISSUE TITLE
When external source IP matters

### ISSUE THREAD

**Issue by moander** [kubernetes/kubernetes#12265]
I have not found any documentation describing scenarios where the external source ip of the routed pods  matter.

I want to kuberialize our SMTP servers using a service and a replication controller. Problem is that the world expect these servers to communicate from a specific external ip.

Is it a "right way" of doing this? I will contribute a .md for this scenario if I find the right solution :)

**Comment by kgrvamsi** [comment]
Lets assume you are running the SMTP ports on 25 or 2525 and when you run the service template then the controller-manager is giving you a ip from the subnet you initially declared so no is that what you are  expecting that the service template which you launch should have a variable ip to dedicate and route the traffic to that specific ip?

**Comment by kgrvamsi** [comment]
Some thing from the Documentation

    {
         "kind": "Endpoints",
        "apiVersion": "v1",
        "metadata": {
            "name": "my-service"
        },
    "subsets": [
        {
            "addresses": [
                { "IP": "1.2.3.4" }
            ],
            "ports": [
                { "port": 80 }
            ]
        }
    ]
    }

http://kubernetes.io/v1.0/docs/user-guide/services.html

**Comment by thockin** [comment]
What cloud environment?

If I understand - you want a pod to send traffic to the internet, with a
fixed source IP?

**Comment by jyrip** [comment]
I have use-case when partner accepts incoming traffic only from predetermined ip-s. 
For that I created smallest instance, enabled routing and routed all outgoing traffic to that partner through that gateway instance. Also when the gateway was in another google project, i used SOCKS5 proxy in that gateway.

**Comment by goltermann** [comment]
We’re going through old support issues and asking everyone to direct your questions to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes). 

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases. 

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.
