### ISSUE TITLE
Restrict addition of new e2e test images with a verify script

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/kubernetes#122748]
We should check the images configured in test/e2e to ensure we're not adding new images:
 
https://github.com/kubernetes/kubernetes/blob/83e6636096548f4b49a94ece6bc4a26fd67e4449/test/utils/image/manifest.go#L229

In almost all cases, [test/images/agnhost](https://github.com/kubernetes/kubernetes/tree/master/test/images/agnhost) should be extended to support any missing functionality and used as the sole image for new tests. This has been the policy in SIG Testing for at least a few years now.

To prevent regressing on this, we should check the list of images and permit tag updates but NOT adding any more names to the list.

We can do this with an allowlist against `e2e.test --list-images`

/sig testing
/kind test

Others are welcome to work on this, but I'll submit something soon if nobody beats me to it.
/assign

Follow up to https://github.com/kubernetes/kubernetes/pull/122747, we should aim to ship something this release (1.30).

**Comment by MaryamTavakkoli** [comment]
Hello! 
Release Signal shadow here.
This issue has not been updated for a long time, so I'd like to check what's the status. The code freeze is starting [02:00 UTC Wednesday 6th March 2024 / 18:00 PDT Tuesday 5th March 2024](https://everytimezone.com/s/5056bace) (less than a month from now), and while there is still plenty of time, we want to ensure that each PR has a chance to be merged on time.

As this issue is tagged for 1.30, is it still planned for this release?

**Comment by BenTheElder** [comment]
We still intend to do this and it's a test-only change so we're aiming for test freeze.

**Comment by MaryamTavakkoli** [comment]
Hello!
Release Signal shadow here.
I'd like to check what's the status. The code freeze is starting [02:00 UTC Wednesday 6th March 2024 / 18:00 PDT Tuesday 5th March 2024](https://everytimezone.com/s/5056bace) in a week, and we want to ensure that each PR has a chance to be merged on time.

Is it still planned for this release?

**Comment by pacoxu** [comment]
As https://github.com/kubernetes/kubernetes/pull/122751 has no update recently,
/milestone clear
we may make it in v1.31.

**Comment by BenTheElder** [comment]
Yeah I think we have to revisit this later.
