### ISSUE TITLE
Pods don't show up in the Mesos Master UI after another master is elected

### ISSUE THREAD

**Issue by hrishimantri** [kubernetes/kubernetes#12281]
You can reproduce the issue as follows:
1) Bring up a mesos-kubernetes cluster with 2 mesos-masters,1 mesos-slave,1 kubernetes master, zookeeper quorum
2) Launch a pod using kubectl 
3) Go ahead and kill the primary mesos master 
4) The secondary master becomes the new primary master - all the slaves and kubernetes master are now connected to this master
5) The pod launched in Step 2. is still running. You can check the same  by doing a : kubectl get pods
6) If you go to the UI of the new primary master the pod which we had launched doesn't show up though its running unperturbed

Any idea whats happening in this case ? All the k8s processes do get the new master via zookeeper. Though the Mesos UI is unable to pull this pod information.

xref https://github.com/mesosphere/kubernetes-mesos/issues/442

**Comment by dchen1107** [comment]
cc/ @karlkfi and @jdef

**Comment by sttts** [comment]
I can reproduce the problem with a multi-master docker-compose setup, compare https://github.com/mesosphere/kubernetes/blob/multi-master-mesos-docker-compose/cluster/mesos/docker/docker-compose.yml.

The following happens after I shutdown the original master (docker_mesosmaster2_1 in my case). The Mesos failover works fine (to docker_mesosmaster3_1 in my case), but the scheduler does not succeed to reregister. Because the scheduler represents the framework in Mesos terms, the corresponding tasks are marked as orphans. They actually appear in the master state.json, but the UI does not show them. Eventually they are killed by Mesos.

```
I0807 14:15:34.007790      66 client.go:274] syncConnected to zookper server
I0807 14:15:34.007825      66 client.go:358] Handling: zk.EventNodeChildrenChanged
I0807 14:15:34.007831      66 detect.go:108] fetching children at path '/mesos'
I0807 14:15:34.016949      66 detect.go:126] changing leader node from info_0000000001 -> info_0000000002
I0807 14:15:34.026311      66 detect.go:136] detected master info: &MasterInfo{Id:*20150807-141208-1042393280-5070-1,Ip:*1042393280,Port:*5070,Pid:*master@192.168.33.62:5070,Hostname:*mesosmaster3,XXX_unrecognized:[],}
I0807 14:15:34.026640      66 messenger.go:364] Receiving message mesos.internal.InternalMasterChangeDetected from scheduler(1)@192.168.33.61:40299
I0807 14:15:34.026690      66 scheduler.go:277] New master master@192.168.33.62:5070 detected
I0807 14:15:34.026704      66 scheduler.go:336] No credentials were provided. Attempting to register scheduler without authentication.
I0807 14:15:34.026719      66 scheduler.go:770] Reregistering with master: master@192.168.33.62:5070
I0807 14:15:34.026762      66 scheduler.go:362] Master disconnected!
I0807 14:15:34.026782      66 messenger.go:187] Sending message mesos.internal.ReregisterFrameworkMessage to master@192.168.33.62:5070
I0807 14:15:34.026836      66 scheduler.go:735] will retry registration in 455.990549ms if necessary
I0807 14:15:34.234134      66 client.go:337] rewatching children for path /mesos
I0807 14:15:34.483395      66 scheduler.go:770] Reregistering with master: master@192.168.33.62:5070
I0807 14:15:34.483735      66 messenger.go:187] Sending message mesos.internal.ReregisterFrameworkMessage to master@192.168.33.62:5070
```

**Comment by sttts** [comment]
@jdef can you test the master switch over with mesos-go? It might be broken.

**Comment by hrishimantri** [comment]
@sttts @jdef any ETA on when can we expect a fix for this ?

**Comment by sttts** [comment]
As we don't understand the actual problem it's hard to give estimates. I will take a deeper look tomorrow. Maybe we know more then.

**Comment by hrishimantri** [comment]
Thanks @sttts ... Will wait for your update.

**Comment by sttts** [comment]
I have debugged the problem: https://gist.github.com/sttts/fd66462513f6630aeeb7

The scheduler's http client is blocked by a message sent to the master after the master failed, but before the scheduler knew about that. You see those ReregisterFrameworkMessage which are never sent to the master because the previous message hasn't timed out.

Eventually the timeout happens. Unfortunately the scheduler terminates due to this. If you restart the scheduler it registers again with the master and the previously orphaned tasks show up again in the UI.

The best workaround for now might be to make the scheduler restart automatically after it terminates. Our docker-compose cluster setup does not do this, the DCOS package does.

**Comment by hrishimantri** [comment]
@sttts yeah we can go ahead and restart the scheduler. But I'm a little confused about your comment on the 'previous orphaned tasks showing up again in the UI'. These should not show in the UI unless the RC brings them up , right ?

**Comment by sttts** [comment]
The pods are still running. But the master does not see the framework. Also the executors should still be running.

**Comment by hrishimantri** [comment]
@sttts got it.. is there a timeout value we can configure for the scheduler talking to the mesos-master ?

**Comment by sttts** [comment]
I fear we don't have that (yet). Can you open a feature request for that?

**Comment by jdef** [comment]
xref https://github.com/mesosphere/kubernetes-mesos/issues/442

**Comment by karlkfi** [comment]
Just to set expectations here, we don't have any automated tests to validate multi-master k8s on mesos setups and it's not high on the priority list yet. Passing conformance test, validating dependence on etcd-mesos, and component registration all take precedence. Once those key pieces are in place we hope to focus more on HA modes.

We're definitely willing to take PRs to improve multi-master setups in the mean time, but we're unlikely to present a solution in the very near future.

**Comment by jdef** [comment]
This issue is quite old and a number of bugs have been fixed. Please confirm that this is still a problem.
