### ISSUE TITLE
Generate unique label for Replication Controller, Job

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#12298]
Currently, the user is responsible for ensuring that a replication controller has a selector which will be disjoint from all other replication controllers.  Job will have the same issue.

I expect some users will think carefully about their labels and not have a problem ensuring this uniqueness property for their rcs/services.  I expect other users will not be as careful, and may forget to do this.  If they forget it will be hard to debug.  

I expect this problem to be worse for Job because Jobs are run in a more ad-hoc manner, so with less thought, and don't last as long, perhaps making debugging of conflicts more difficult.  Also, while RCs often need to adopt existing pods, jobs need to be able to do this less often (but maybe in some cases?).

The solution seems to be to have a way to request that the Job or the ReplicationController will pick a unique label for the pods it creates.    Something like `kubernetes.io/job-uid=$UID_OF_JOB` or `kubernetes.io/rc-uid=$UID_OF_RC`.   This might be via a boolean flag like `generateSelector`.  When `generateSelector` is false, then the user is assumed to have provided a selector which provides the necessary uniqueness, either via the spec.selector, or via defaulting from the pod template.  If true, then the system adds another selector and adds another label to the pods which is unique per Job/RC.

We probably want as much as possible the same behavior for Job and ReplicationController.  
However for Job, it would be nice to have generateSelector default to true, so people can write succinct specs, and default to false for RC for backwards compat. 

@bgrant0607 said that it should always be possible for users to disable creation automatic creation of the system label.

**Comment by erictune** [comment]
Job proposal is #11746

**Comment by derekwaynecarr** [comment]
+1

**Comment by davidopp** [comment]
So this is basically the label equivalent of GenerateName?

**Comment by nikhiljindal** [comment]
This is relevant for Deployment as well: https://github.com/GoogleCloudPlatform/kubernetes/pull/12236

Why do we want users to care about system labels?

FWIW, rolling-update also adds some labels such as ```kubectl.kubernetes.io/next-controller-id```
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubectl/rolling_updater.go#L171

I see that openshift adds labels of the form ```openshift.io/deployment.name``` during deployment as well: https://github.com/openshift/origin/blob/master/pkg/deploy/api/types.go#L143 Not sure if they allow users to choose the label keys.
cc @ironcladlou @smarterclayton

**Comment by ironcladlou** [comment]
>I see that openshift adds labels of the form openshift.io/deployment.name during deployment as well: https://github.com/openshift/origin/blob/master/pkg/deploy/api/types.go#L143 Not sure if they allow users to choose the label keys.

Openshift uses `openshift.io/deployment.name` to solve the exact problem described in this issue. Users can still add their own selector entries, but we always add a unique one for the deployment to force disambiguation.

**Comment by smarterclayton** [comment]
We don't let the user choose the label key but that's only historical.  I suspect there are clever use cases out there that a customizable label key would allow.  Changing it would trigger a redeployment and lose the old deployments (which might be useful for orphan or cutover) or it should be prevented from changing (not as flexible)

**Comment by bgrant0607** [comment]
I need to add this to the API conventions -- #12322.

Labels are the domain of users. They are intended to facilitate organization and management of API resources using attributes that are meaningful to users, as opposed to meaningful to the system. Think of them as user-created mp3 or email inbox labels, as opposed to the directory structure used by a program to store its data. The former is enables the user to apply an arbitrary ontology, whereas the latter is implementation-centric and inflexible. Users will use labels to select resources to operate on, display label values in CLI/UI columns, etc. Users should always retain full power and flexibility over the label schemas they apply to labels in their namespaces. 

However, we should support conveniences for common cases by default. For example, what we now do in ReplicationController is automatically set the RC's selector and labels to the labels in the pod template by default, if they are not already set. That ensures that the selector will match the template, and that the RC can be managed using the same labels as the pods it creates. Note that once we generalize selectors (#341), it won't necessarily be possible to unambiguously do the reverse -- generate labels that match an arbitrary selector. 

If the user wants to apply additional labels to the pods that it doesn't select upon, such as to facilitate adoption of pods or in the expectation that some label values will change, they can set the selector to a subset of the pod labels. Similarly, the RC's labels could be initialized to a subset of the pod template's labels, or could include additional/different labels. 

For disciplined users managing resources within their own namespaces, it's not that hard to consistently apply schemas that ensure uniqueness. One just needs to ensure that at least one value of some label key in common differs compared to all other comparable resources. We could/should provide a verification tool to check that. However, development of conventions similar to the examples in labels.md make uniqueness straightforward. Furthermore, relatively narrow namespaces can be used to reduce the set of resources that could potentially cause overlap, by shrinking the scope of concern, as discussed in #1698. 

In cases where users could be running misc. examples with inconsistent schemas, or where tooling or components need to programmatically generate new objects to be selected, there needs to be a straightforward way to generate unique label sets. A simple way to ensure uniqueness of the set is to ensure uniqueness of a single label value, such as by using a uid, [resource hash](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubectl/rolling_updater.go#L143), as in [simple rolling update](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/design/simple-rolling-update.md), or generation number. 

Problems with uids and hashes, however, include that they have no semantic meaning to the user, are not memorable nor readily recognizable, and are not predictable. Lack of predictability obstructs use cases such as creation of a replication controller from a pod (#11490), such as people want to do when exploring the system, bootstrapping a self-hosted cluster, or deletion and re-creation of a new RC that adopts the pods of the previous one, such as to rename it. Generation numbers are more predictable and much clearer, assuming there is a logical sequence. Fortunately, for deployments that's the case. For jobs, use of creation timestamps is common internally. Users should always be able to turn off auto-generation, in order to permit some of the scenarios described above. Note that auto-generated labels will also become one more field that needs to be stripped out when cloning a resource, within a namespace, in a new namespace, in a new cluster, etc., and will need to be ignored around when updating a resource via patch or RMW sequence.

Inclusion of a system prefix in a label key is fairly hostile to UX. A prefix is only necessary in the case that the user cannot choose the label key, in order to avoid collisions with user-defined labels. However, I firmly believe that the user should always be allowed to select the label keys to use on their resources. This is why rolling update uses "deployment" by default, but enables the user to select their own key via a flag.

Therefore, we should have a `uniqueLabelKey *string`. That way, the user could specify the key if they wanted to, but if unspecified, it could be set by default, such as to the resource type, like job, deployment, or replicationController. The value would need to be at least spatially unique, and perhaps temporally unique in the case of job. I don't think we need to use the same value-generation method for every resource that needs this. If  uniqueLabelKey were set the empty string, that could disable auto-generation. Or we could add a bool for that. The label would be added to the pod template and to the selector, including in the case where the selector was set to the pod template's labels by default. I'm ok with "uniqueLabelKey" being immutable after creation.

Annotations have very different intended usage from labels. We expect them to be primarily generated and consumed by tooling and system extensions. I'm inclined to generalize annotations to permit them to directly store arbitrary json #12226. Rigid names and name prefixes make sense, since they are analogous to API fields. `next-controller-id` is an annotation, not a label.

**Comment by bgrant0607** [comment]
Well, it's probably safer to slap a prefix on the uniqueLabelKey by default (so `kubernetes.io/job`) and let the user override that with their own non-conflicting key.

**Comment by smarterclayton** [comment]
No disagreement on the above.

On Fri, Aug 7, 2015 at 4:17 AM, Brian Grant <notifications@github.com>
wrote:

> I need to add this to the API conventions -- #12322
> <https://github.com/GoogleCloudPlatform/kubernetes/issues/12322>.
>
> Labels are the domain of users. They are intended to facilitate
> organization and management of API resources using attributes that are
> meaningful to users, as opposed to meaningful to the system. Think of them
> as user-created mp3 or email inbox labels, as opposed to the directory
> structure used by a program to store its data. The former is enables the
> user to apply an arbitrary ontology, whereas the latter is
> implementation-centric and inflexible. Users will use labels to select
> resources to operate on, display label values in CLI/UI columns, etc. Users
> should always retain full power and flexibility over the label schemas they
> apply to labels in their namespaces.
>
> However, we should support conveniences for common cases by default. For
> example, what we now do in ReplicationController is automatically set the
> RC's selector and labels to the labels in the pod template by default, if
> they are not already set. That ensures that the selector will match the
> template, and that the RC can be managed using the same labels as the pods
> it creates. Note that once we generalize selectors (#341
> <https://github.com/GoogleCloudPlatform/kubernetes/issues/341>), it won't
> necessarily be possible to unambiguously do the reverse -- generate labels
> that match an arbitrary selector.
>
> If the user wants to apply additional labels to the pods that it doesn't
> select upon, such as to facilitate adoption of pods or in the expectation
> that some label values will change, they can set the selector to a subset
> of the pod labels. Similarly, the RC's labels could be initialized to a
> subset of the pod template's labels, or could include additional/different
> labels.
>
> For disciplined users managing resources within their own namespaces, it's
> not that hard to consistently apply schemas that ensure uniqueness. One
> just needs to ensure that at least one value of some label key in common
> differs compared to all other comparable resources. We could/should provide
> a verification tool to check that. However, development of conventions
> similar to the examples in labels.md make uniqueness straightforward.
> Furthermore, relatively narrow namespaces can be used to reduce the set of
> resources that could potentially cause overlap, by shrinking the scope of
> concern, as discussed in #1698
> <https://github.com/GoogleCloudPlatform/kubernetes/issues/1698>.
>
> In cases where users could be running misc. examples with inconsistent
> schemas, or where tooling or components need to programmatically generate
> new objects to be selected, there needs to be a straightforward way to
> generate unique label sets. A simple way to ensure uniqueness of the set is
> to ensure uniqueness of a single label value, such as by using a uid, resource
> hash
> <https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubectl/rolling_updater.go#L143>,
> as in simple rolling update
> <https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/design/simple-rolling-update.md>,
> or generation number.
>
> Problems with uids and hashes, however, include that they have no semantic
> meaning to the user, are not memorable nor readily recognizable, and are
> not predictable. Lack of predictability obstructs use cases such as
> creation of a replication controller from a pod (#11490
> <https://github.com/GoogleCloudPlatform/kubernetes/issues/11490>), such
> as people want to do when exploring the system, bootstrapping a self-hosted
> cluster, or deletion and re-creation of a new RC that adopts the pods of
> the previous one, such as to rename it. Generation numbers are more
> predictable and much clearer, assuming there is a logical sequence.
> Fortunately, for deployments that's the case. For jobs, use of creation
> timestamps is common internally. Users should always be able to turn off
> auto-generation, in order to permit some of the scenarios described above.
> Note that auto-generated labels will also bec! ome one m ore field that
> needs to be stripped out when cloning a resource, within a namespace, in a
> new namespace, in a new cluster, etc., and will need to be ignored around
> when updating a resource via patch or RMW sequence.
>
> Inclusion of a system prefix in a label key is fairly hostile to UX. A
> prefix is only necessary in the case that the user cannot choose the label
> key, in order to avoid collisions with user-defined labels. However, I
> firmly believe that the user should always be allowed to select the label
> keys to use on their resources. This is why rolling update uses
> "deployment" by default, but enables the user to select their own key via a
> flag.
>
> Therefore, we should have a uniqueLabelKey *string. That way, the user
> could specify the key if they wanted to, but if unspecified, it could be
> set by default, such as to the resource type, like job, deployment, or
> replicationController. The value would need to be at least spatially
> unique, and perhaps temporally unique in the case of job. I don't think we
> need to use the same value-generation method for every resource that needs
> this. If uniqueLabelKey were set the empty string, that could disable
> auto-generation. Or we could add a bool for that. The label would be added
> to the pod template and to the selector, including in the case where the
> selector was set to the pod template's labels by default. I'm ok with
> "uniqueLabelKey" being immutable after creation.
>
> Annotations have very different intended usage from labels. We expect them
> to be primarily generated and consumed by tooling and system extensions.
> I'm inclined to generalize annotations to permit them to directly store
> arbitrary json #12226
> <https://github.com/GoogleCloudPlatform/kubernetes/issues/12226>. Rigid
> names and name prefixes make sense, since they are analogous to API fields.
> next-controller-id is an annotation, not a label.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleCloudPlatform/kubernetes/issues/12298#issuecomment-128636518>
> .
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by davidopp** [comment]
> Note that auto-generated labels will also become one more field that needs to be stripped out when cloning a resource, within a namespace, in a new namespace, in a new cluster, etc.

Why "in a new namespace, in a new cluster"? I thought labels are scoped to namespace (and certainly to cluster).

> Therefore, we should have a uniqueLabelKey *string. That way, the user could specify the key if they wanted to, but if unspecified, it could be set by default, such as to the resource type, like job, deployment, or replicationController. [...] Well, it's probably safer to slap a prefix on the uniqueLabelKey by default (so `kubernetes.io/job`) and let the user override that with their own non-conflicting key.

How would you recommend to set the suffix for the case in this issue (job)? You mentioned timestamp earlier, since that's what we use internally for job, which seems reasonable.

**Comment by bgrant0607** [comment]
See also the `controllerRef` proposal: https://github.com/kubernetes/kubernetes/issues/2210#issuecomment-134878215

I view that proposal as being complementary to this one.

**Comment by bgrant0607** [comment]
@davidopp 

Re. "new namespace, new cluster": The scenario was that the user wanted to clone the resource. #13038

By "suffix", did you mean label value? Yes, timestamp would be reasonable for jobs. Or even resource name.

**Comment by smarterclayton** [comment]
I prefer resource name, unless we can come up with a case where a previous job leaves pods lying next around unintentially.

**Comment by erictune** [comment]
I am going to do this for 1.2.

**Comment by erictune** [comment]
Proposed Design 
=============
# Goals
Make it really hard to accidentally create a job which has an overlapping selector, while still making it possible to chose an arbitrary selector, and without adding complex constraint solving to the APIserver.

# Use Cases

1. user can leave all label and selector fields blank and system will fill in reasonable ones: non-overlappingness guaranteed.
2. user can put on the pod template some labels that are useful to the user, without reasoning about non-overlappingness.  System adds additional label to assure not overlapping.
3. If user wants to reparent pods to new job (very rare case) and knows what they are doing, they can completely disable this behavior and specify explicit selector.
4. If a controller that makes jobs, like scheduled job, wants to use different labels, such as the time and date of the run, it can do that.
5.  If User reads v1beta1 documentation or reuses v1beta1 Job definitions and just changes the API group, the user should not automatically be allowed to specify a selector, since this is very rarely what people want to do and is error prone. 
6. If User downloads an existing job definition, e.g. with `kubectl get jobs/old -o yaml` and tries to modify and post it, he should not create an overlapping job.
7. If User downloads an existing job definition, e.g. with `kubectl get jobs/old -o yaml` and tries to modify and post it, and he accidentally copies the uniquifying label from the old one, then he should not get an error from a label-key conflict, nor get erratic behavior.
8. If user reads swagger docs and sees the selector field, he should not be able to set it without realizing the risks.
8. (Deferred requirement:) If user wants to specify a preferred name for the non-overlappingness key, they can pick a name.

# Proposed changes

## API and defaulting

### New Unique Labels
`extensions/v1beta1 Job` remains the same. `batch/v1 Job` changes change as follows:

If user does not specify `job.spec.selector`, then, the defaulting logic sets `job.spec.selector` to `matchLabels["controller-uid"]="$UIDOFJOB", and appends 2 labels to the `.spec.template.metadata.labels.  The first label is controller-uid=$UIDOFJOB.  The second label is "job-name=$NAMEOFJOB".  This is a more familiar, self-explanatory, label.  
The defaulting logic also sets a selector that does `matchLabels` with `controller-uid=$UIDOFJOB` and `job-name=$JOBNAME`.    

#### Rationale

UID is better than Name in that:
- it allows cross-namespace control someday if we need it.
- it is unique across all kinds.  `controller-name=foo` does not ensure uniqueness across Kinds `job` vs `replicaSet`.  Even `job-name=foo` has a problem: you might have a `batch.Job` and a `snazzyjob.io/types.Job` -- the latter cannot use label `job-name=foo`, though there is a temptation to do so.
- it uniquely identifies the controller across time.   This prevents the case where, for example, someone deletes a job via the REST api or client (where cascade=false), leaving pods around.  We don't want those to be picked up unintentionally.  It also prevents the case where a user looks at an old job that finished but is not deleted, and tries to select its pods, and gets the wrong impression that it is still running.

Job name is more user friendly.  It is self documenting
Commands like  `kubectl get pods -l job-name=myjob` should do exactly what is wanted 99.9% of the time.  Automated control loops should still use the controller-uid=label.

Using both gets the benefits of both, at the cost of some label verbosity.

### Overriding Unique Labels
If user does specify `job.spec.selector` then the user must also specify `job.spec.noDefaultSelector`.
This ensures the user knows that what he is doing is not the normal thing to do.

To prevent users from copying the `job.spec.noDefaultSelector` flag from existing jobs, it will be
optional and default to false, which means when you ask GET and existing job back that didn't use this feature, you don't even see the  `job.spec.noDefaultSelector` flag, so you are not tempted to wonder if you should fiddle with it.  

## Job Controller

No changes

## Kubectl

No required changes.
Suggest moving SELECTOR to wide output of `kubectl get jobs` since users don't write the selector.

## Deployments, ReplicaSet, DaemonSet, etc

Follow this pattern for Deployments, ReplicaSet, DaemonSet when going to v1, if it works well for job.

Docs will be edited to show examples without a `job.spec.selector`. 

We probably want as much as possible the same behavior for Job and ReplicationController.

# Cross Version Compat

`v1beta1` will not have a `job.spec.noDefaultSelector` and will not provide a default selector.

Conversion from v1beta1 to v1 will use the user-provided selector and set `job.spec.noDefaultSelector=true`.

**Comment by soltysh** [comment]
@erictune the proposal LGTM, still can you create a separate doc for that? Based on this comment you can assume my approval of the proposal.

**Comment by bgrant0607** [comment]
cc @janetkuo

**Comment by smarterclayton** [comment]
I think this makes sense to me - noDefaultSelector being opt out makes
sense in this context, I agree that making the default case be foolproof is
an excellent goal.

**Comment by bgrant0607** [comment]
SGTM.

One clarification regarding: The defaulting logic also sets a selector that does `matchLabels` with `controller-uid=$UIDOFJOB` and `job-name=$JOBNAME`.  

I would expect the defaulting logic to create the selector to match the labels specified in the pod template. I assume this would only happen in the case that `noDefaultSelector:true` were specified, which makes this defaulting awkward. Maybe call that `noUniqueSelector` or `noAutoSelector` instead?

Deployment permits overriding the label key used to uniquify the underlying RCs, via `uniqueLabelKey`, which is somewhat different. This uniquifier is not optional, but I think we should rename that field to reduce confusion with this mechanism. I suggest `templateHashLabelKey`.

I include moving all selectors to `-o wide` as part of #19775.

**Comment by erictune** [comment]
Edited my long post to clarify the section you asked about @bgrant0607

**Comment by erictune** [comment]
User has to provide both labels and selector in the `noDefaultSelector:true` case.

**Comment by erictune** [comment]
Edited to rename to `noAutoSelector`

**Comment by bgrant0607** [comment]
LGTM

**Comment by erictune** [comment]
Converted to document in #20524

**Comment by erictune** [comment]
Found a problem while implementing this.  We don't generate a UID until after defaulting.  But it is during defaulting that we need to know the Job's UID for the current proposal.

For those curious, UID is generated in `api.FillObjectMetaSystemFields` which is called in `BeforeCreate` of `pkg/api/rest/create.go`.

I've thought of the following alternatives:

1. Set the UID for all objects with ObjectMeta as part of defaulting. 
  - big change this close to 1.2.
  - there may be some code that relies on the UID not being set yet to determine if an object has been created yet?  Search for `HasObjectMetaSystemFieldValues`.
  - @lavalamp do you see any other problems with this?
2. Generate a different UUID at Job defaulting time for use as a unique label for the job.
  - e.g. label/selector would be `job-unique-label=za7VbYcSQU2zRgGQXQAm/g`
  - easy to implement, and changes are confined to job.
  - safest choice at this close to 1.2
  - seems like a lost opportunity to not use UID
3. Controller sets selector after initial object creation
  - object is created with unspecified selector.
  - when Job controller sees a Job which needs selector generation, it updates the Job object with a unique selector.
  - Job can begin running after that initial update.
  - requires allowing updates to Job.Spec.Template and Job.Spec.Selector.  What rules would prevent further updates to these fields?

@bgrant0607 thoughts on above options?

**Comment by lavalamp** [comment]
One of @liggitt or @deads2k was already planning on moving UID generation earlier in the stack. Defaulting is probably not the best place because that gets run in some clients (this is a bug).

**Comment by deads2k** [comment]
> One of @liggitt or @deads2k was already planning on moving UID generation earlier in the stack. Defaulting is probably not the best place because that gets run in some clients (this is a bug).

@derekwaynecarr Pretty sure this was you so that you'd have a correlation value for quota.

**Comment by bgrant0607** [comment]
@erictune @lavalamp 

In particular, kubectl runs defaulting (#3955), so the label and selector would be run by kubectl.

I agree with the idea of moving UID generation earlier, but that does seem like a risky change to do now.

How about in the Job create handler?

**Comment by erictune** [comment]
@bgrant0607 I think you are suggesting that I move all the label selector generation logic into the job create handler?  I think that might work, at least as a quick fix for 1.2.  I'll look into that.

**Comment by smarterclayton** [comment]
Moving UID generation earlier is very risky, I would prefer not to change
anything in this stack right now for 1.2.

**Comment by erictune** [comment]
@smarterclayton any concern about doing defaulting-y stuff in the create handler, as a quick fix in 1.2?

**Comment by derekwaynecarr** [comment]
The solution we discussed at a recent sig meeting was to do the following:

* expose a `Context` on `admission.Attributes`
* allow you to read a UID or set a UID for an object on the context
* modify `FillObjectMetaSystemFields` to default to the UID on the context if present instead of creating new

This would be the least disruptive flow I think.

**Comment by derekwaynecarr** [comment]
@erictune - if the above works for your use case, I can look to get a PR open this afternoon/evening.

**Comment by erictune** [comment]
So, selector generation would be implemented as an admission controller rather than a defaulter?  That sounds good to me.

**Comment by erictune** [comment]
Hmm, the thing about an admission controller is that people have to manually add them to their apiserver flags.  I'd want this to always run.  I guess I could hardcode it on.

**Comment by erictune** [comment]
I'm adding unique-label/selector generation in the Job `strategy.Validate`, right before the api validation.

It is the quickest way forward.

**Comment by mml** [comment]
So this gets 90% of what we get from formalizing controllerRef

**Comment by mml** [comment]
So this gets 90% of what we get from formalizing controllerRef (#2210), but one other goal for controllerRef is to be able to quickly determine the controller for a pod.  Right now we can almost do that with the created-by annotation (it's incorrect if the pod has since been adopted by a different controller), and we don't need to know the type of the controller, or indeed all types of controllers, in advance.

As I'm looking to implement controllerRef and it seems so close to what this does, I wonder if there's a way to combine the two.

**Comment by davidopp** [comment]
Added v1.2 milestone -- this is a 1.2 blocker, right @erictune  ?

**Comment by erictune** [comment]
yes

On Thu, Feb 11, 2016 at 4:38 PM, David Oppenheimer <notifications@github.com

**Comment by bgrant0607** [comment]
@mml Unique label/selector generation and controllerRef are indeed related, which is why I'm going to summarize my thoughts on #14961.

**Comment by erictune** [comment]
Job is complete.  I'm removing this from v1.2.  For 1.3, we should add selector generation to other controllers before they go to GA.  I can advise people on how to do that.

**Comment by bgrant0607** [comment]
Some discussion of this here:
https://github.com/kubernetes/kubernetes/issues/36859#issuecomment-262022027

**Comment by soltysh** [comment]
@erictune I'm wondering, after reading @bgrant0607 comment from the linked issue I'm sure this issue could be closed. You fixed the label generation for job and for RC we won't be going this way, but instead we'll allow changing the lables. In that case the issues doesn't make sense anymore, imho.

**Comment by bgrant0607** [comment]
@soltysh Closing for now.
