### ISSUE TITLE
[Proposal]  Add most non-deprecated flags to the Kubelet configuration API

### ISSUE THREAD

**Issue by tallclair** [kubernetes/kubernetes#122916]
**Proposal:** Add most non-deprecated flags to the Kubelet configuration API. These will still be settable via flag (flag values override config values).

**Background:**
The decision of which Kubelet flags to expose in the Kubelet configuration was historically tied to the Dynamic Kubelet Configuration feature. Specifically, the configuration was designed to be shared across nodes. Dynamic Kubelet Configuration has since been deprecated and removed, and this concern is no longer relevant

**Motivation:**
Consolidating more of the configuration into the configuration API will let users manage their Kubelet configuration via a single API surface, rather than needing to split the configuration across flags and a configuration file.

**Add:**

- [ ] HostnameOverride 
- [ ] NodeIP
- [ ] config.ContainerRuntimeOptions (except deprecated PodSandboxImage)
- [ ] RuntimeCgroups
- [ ] ImageCredentialProviderConfigFile
- [ ] ImageCredentialProviderBinDir
- [ ] CertDirectory 
- [ ] RootDirectory 
- [ ] WindowsService 
- [ ] WindowsPriorityClass 
- [ ] CloudProvider - note: this may turn into a boolean option

**Open Question: "alpha" flags**
These flags claim to be alpha (`<Warning: Alpha feature>`), but appear to be ungated. These should probably be treated as default-GA, and added to the config.

- [ ] NodeLabels
- [ ] LockFilePath
- [ ] ExitOnLockContention

**The following options will remain flag only:**

- KubeConfig, BootstrapKubeConfig - We could consider adding these, but it seems odd to point one config file at the other.
- KubeletConfigFile, KubeletDropinConfigDirectory - Point to the Kubelet config (don't want a circular reference!)
- Deprecated flags:
    - MinimumGCAge
    - MaxPerPodContainerCount
    - MaxContainerCount
    - RegisterSchedulable
    - KeepTerminatedPodVolumes
    - ExperimentalMounterPath
    - ExperimentalNodeAllocatableIgnoreEvictionThreshold
    - CloudConfigFile
    - PodSandboxImage
    - `azure-container-registry-config`
- cAdvisor flags - Accidental flag leak
- version flag / help flag - Not config
- logging flags - Relevant fields are already included in the logging configuration

**Historical References:**
https://github.com/kubernetes/kubernetes/pull/40117 - Flags that can't be shared across nodes are moved out of shared config type (removed Hostname, NodeIP)
https://github.com/kubernetes/kubernetes/pull/44061 - Extract CROptions from KubeletConfig
https://github.com/kubernetes/kubernetes/pull/46254 - Removed CertDirectory, RootDirectory, CloudProvider

/sig node
/milestone v1.30
/kind cleanup api-change

**Comment by tallclair** [comment]
/cc @andrewsykim 

Can you comment on the cloudprovider flags? Are my assertions correct?

**Comment by tallclair** [comment]
Spoke with Andrew offline - The cloud provider flag will live on, as there will be an option to run without any cloud provider (including no external provider).

**Comment by carlory** [comment]
Can I pick up some tasks of  this issue?

**Comment by tallclair** [comment]
@carlory this issue needs more discussion before we implement the changes. I opened it as a proposal, I'm not sure if it needs a KEP.

**Comment by kannon92** [comment]
@tallclair We missed your item in sig-node this week due to planning. Maybe you can bring it up to sig-node next week?

**Comment by tallclair** [comment]
After digging into this more, and following up with some folks on specific options, this is looking more complicated than I originally realized. I don't think a straight port of all the flag options to the config API makes sense, and we should probably look at each option individually. As such, I'm not sure how much time I'll have for this in v1.30, so I'm going to remove it from the milestone for now.

/milestone clear

**Comment by mtaufen** [comment]
@tallclair is there a summary of your conversations?

If I had to go back and do it again, I think I'd make it an exclusive choice between using `--config` or configuring everything with flags, and require every option _except_ `--config` to be in both places until eventually deprecating the entire flag surface other than `--config`. I'd _maybe_ allow the value of `--config` to be a path OR a vanilla json object (no patching/overlays/or anything fancy), to continue supporting CLI use-cases. That wouldn't handle e.g. global flags from third-party libraries, but I think it would solve most of the complexity. The overlay machinery was just way over-complicated, more so with dynamic config on top of that, but even without dynamic, way too much going on there... 

We had this guide a while back on migrating flags to config, lists some special cases where we weren't migrating yet (Windows (why, I can't remember...), non-shared things as you mentioned (due to DKC), already-deprecated things): https://docs.google.com/document/d/10Kz__miCWEOekC6WnsUdxYWSLrf-t1AkHHpZN57ei5c/edit?tab=t.0#heading=h.mupqgfuyjwnm

We over-optimized for trying to solve all the edge cases, and that was a major reason this got stuck. To unstick it, I suspect we'll have to make someone unhappy.
