### ISSUE TITLE
Union authenticator may send credentials to all authentication providers

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#12316]
In `plugin/pkg/auth/authenticator/request/union/union.go` it tries each of the authentication methods in order.  This means that if you pass the admin token using basic auth, then it sends the basic auth information to all configured auth providers.  So, for example, if the admin is authorizing with the cluster's csv-file-based admin token, that password might also be sent to a configured OpenID identity provider (#10957), who didn't previously know my admin password, but could now learn it.  

In all the practical cases I can think of, I trusted the various authentication providers about the same amount.  But I think it is unexpected behavior and it makes me a little uneasy.

A minor improvement would be to document this behavior.  

A bigger improvement would be for the client (kubectl) to include a header saying which authentication provider the password or token were intended for.  

@liggitt what are your thoughts.

**Comment by liggitt** [comment]
For now, I'm ok with documentation. This is really only an issue when the supplied user credentials are passed to a remote system for authentication. None of the authenticators in k8s currently do that... even the proposed OpenID token verification is done locally using signature verification (though it's certainly possible future authenticators, like an LDAP authenticator could send a username/password to a backend server for verification).

I'm not sure if I prefer a side-channel header to select the authentication provider/realm, or something like a digest authorization header that has a way to indicate the realm (that assumes the backing identity providers actually support digest auth in a way the API could proxy).

I'd probably wait until we actually had a use case involving unioning multiple authenticators that made remote calls with user credentials before I worried too much about it.

**Comment by erictune** [comment]
I thought about this because #11798 appears to send a password to a backend.

**Comment by liggitt** [comment]
Yup, that one would send remotely.

**Comment by wangxinnong** [comment]
## Bug Analysis
* Basic auth information will only be sent to BasicAuth Authenticator (KeystoneAuthenticator and PasswordAuthenticator)
* The BasicAuth authenticators will be called in order (local first, then remote). If any authenticator successfully authenticate the request, other authenticators in the chain will not be called.

So the actual issue is that when we use kubectl or directly access api-server, we cannot specify which provider we want to use.

For example, even multiple authentication providers are setup in the k8s cluster, for some users, they will only use Keystore for authentication, but for others will only use oidc.

k8s will always try to authenticate the request by all the providers until one of them pass the authentication or all failed.

Another disadvantage of the current design is that the credential (Basic Authorization Header or Bearer Token) contained in the HTTP header will be parsed repeatedly for the same kind of provider.

For example, 2 basicauth.Authenticators will be created for Static Password File and Keystone Password

req.BasicAuth() will be called basicauth.Authenticator.AuthenticateRequest, get "Authorization" header and decode the base64 encoded string and split it to username and password.

Since the api-server is accessed very frequently, this will lead to a lower performance.

## Proposal
Support for explicitly specifying the provider for api-server authentication which can be set:
* in the kubeconfig file ( provider: ***)
* by the kubectl CLI (–provider=***)
* by the HTTP header using curl (-H "Authn-Provider: ***") or other REST client.

## kubectl
### kubeconfig file
Add an optional "provider" field to the section of users/use in the kubeconfig file like the following.
```
users:
- name: userpass
  user:
    provider: keystone
    password: uXFGweU9l35qcif
    username: user
- name: kubernetes-admin
  user:
    provider: cert
    client-certificate-data: ****
    client-key-data: ****
```
Authentication Type|Provider
------------ | -------------
basic auth|passwordfile,keystone
token|serviceacount,bootstrap,tokenfile,webhook	 
client certificate|cert	 
auth-provider|oidc

Auth-provider is supported by plugin. Currently there are 3 kinds: oidc, gcp, azure. All of them are authenticated by OIDCAuthenticator.

### kubectl-cmd
CLI of kubectl should support an optional "provider" option which can be passed to any command which communicates with api-server, e.g. kubectl get, kubectl create, kubectl delete, etc.

`kubectl -username=user --password=password --provider=passwordfile get all`

When accessing api-server by kubectl, a HTTP header of "Authn-Provider" will be added when authorization provider is set in the kubeconfig file or by CLI option.

Authorization provider can be saved to kubeconfig file by Sub-command of "config set-credentials":

`kubectl config set-credentials cluster-admin --provider=passwordfile --username=admin --password=uXFGweU9l35qcif`

### curl or other REST client
User can directly set Authn-Provider HTTP header when accessing api-server by curl or other REST client.

`curl -i -k  https://10.245.251.155:6443/api/v1/namespaces/deflt/p-iods -H "Authorization: Basic $userPass" -H "Authn-Provider:passwordfile"`

## api-server
When HTTP header of "Authn-Provider" is provided, api-server will only use the corresponding Authenticator Request to handle the authentication during the authentication handling of union.unionAuthRequestHandler.

If there is no corresonding AuthenticatorRequest was found for the provider, an error will be thrown.
### Authenticator Registration
When Authenticator Requests are registered, they will be put into a map, taken the provider name as the key.
They will still be put into the slice to keep the compatibility.

Provider|Authenticator|Type
------------ | ------------- | -------------
proxy|requestHeaderAuthenticator|x509.Verifier
passwordfile|AuthenticatorFromBasicAuthFile|basicauth.Authenticator
keystone|AuthenticatorFromKeystoneURL|basicauth.Authenticator
cert|AuthenticatorFromClientCAFile|x509.Authenticator
tokenfile|AuthenticatorFromTokenFile|bearertoken.Authenticator
serviceacount|ServiceAccountAuthenticator FromServiceAccountKeyFiles|bearertoken.Authenticator
bootstrap|BootstrapTokenAuthenticator|bearertoken.Authenticator
oidc|AuthenticatorFromOIDCIssuerURL|bearertoken.Authenticator 
webhook|WebhookTokenAuthenticator|bearertoken.Authenticator
loopback|loopbackTokenAuthenticator|bearertoken.Authenticator

### Authentication logic of union.unionAuthRequestHandler
The union.unionAuthRequestHandler's Authentication logic will be changed as the following:

If Authentication Provider Header is set, the corresponding Authenticator Request will be retrieved from HandlerMap and used for authentication.

If it is not found, then find out the group.AuthenticatedGroupAdder or union.unionAuthRequestHandler from the slice of Handlers and let it handle the authentication.

**Comment by liggitt** [comment]
there is currently a single remote authenticator for each auth type, and it is placed at the end of the union chain, so the remote authenticator only sees a credential after all the local methods have rejected it
