### ISSUE TITLE
Still having issues building Kubernetes on Mac OSX

### ISSUE THREAD

**Issue by satnam6502** [kubernetes/kubernetes#12330]
Although I can do `hack/build-go.sh` (does not build Docker images) I find that `build/release.sh` fails.
This was after changing my boot2docker VM settings as shown in #11852 to use 3GB
@cjcullen 

Satnam

``` console
satnam-macbookpro2:kubernetes satnam$ hack/build-go.sh
+++ [0805 22:51:01] Building go targets for darwin/amd64:
    cmd/kube-proxy
    cmd/kube-apiserver
    cmd/kube-controller-manager
    cmd/kubelet
    cmd/hyperkube
    cmd/kubernetes
    cmd/linkcheck
    plugin/cmd/kube-scheduler
    cmd/kubectl
    cmd/integration
    cmd/gendocs
    cmd/genman
    cmd/mungedocs
    cmd/genbashcomp
    cmd/genconversion
    cmd/gendeepcopy
    examples/k8petstore/web-server
    github.com/onsi/ginkgo/ginkgo
    test/e2e/e2e.test
+++ [0805 22:51:33] Placing binaries
satnam-macbookpro2:kubernetes satnam$ build/release.sh
+++ [0805 22:58:04] Verifying Prerequisites....
+++ [0805 22:58:04] Setting boot2docker clock
+++ [0805 22:58:05] Building Docker image kube-build:cross.
+++ [0805 22:58:11] Building Docker image kube-build:build-2e085a3636.
+++ [0805 22:58:17] Running build command....
+++ [0805 22:58:17] Creating data container
+++ [0806 05:58:18] Building go targets for linux/amd64:
    cmd/kube-proxy
    cmd/kube-apiserver
    cmd/kube-controller-manager
    cmd/kubelet
    cmd/hyperkube
    cmd/kubernetes
    cmd/linkcheck
    plugin/cmd/kube-scheduler
+++ [0806 06:04:10] Multiple platforms requested, but available 2G < threshold 11G, building platforms in serial
+++ [0806 06:04:10] Building go targets for linux/amd64:
    cmd/kubectl
    cmd/integration
    cmd/gendocs
    cmd/genman
    cmd/mungedocs
    cmd/genbashcomp
    cmd/genconversion
    cmd/gendeepcopy
    examples/k8petstore/web-server
    github.com/onsi/ginkgo/ginkgo
    test/e2e/e2e.test
+++ [0806 06:04:28] Building go targets for linux/386:
    cmd/kubectl
    cmd/integration
    cmd/gendocs
    cmd/genman
    cmd/mungedocs
    cmd/genbashcomp
    cmd/genconversion
    cmd/gendeepcopy
    examples/k8petstore/web-server
    github.com/onsi/ginkgo/ginkgo
    test/e2e/e2e.test
+++ [0806 06:06:07] Building go targets for linux/arm:
    cmd/kubectl
    cmd/integration
    cmd/gendocs
    cmd/genman
    cmd/mungedocs
    cmd/genbashcomp
    cmd/genconversion
    cmd/gendeepcopy
    examples/k8petstore/web-server
    github.com/onsi/ginkgo/ginkgo
    test/e2e/e2e.test
+++ [0806 06:08:02] Building go targets for darwin/amd64:
    cmd/kubectl
    cmd/integration
    cmd/gendocs
    cmd/genman
    cmd/mungedocs
    cmd/genbashcomp
    cmd/genconversion
    cmd/gendeepcopy
    examples/k8petstore/web-server
    github.com/onsi/ginkgo/ginkgo
    test/e2e/e2e.test
go build k8s.io/kubernetes/pkg/ui/data/swagger: /usr/src/go/pkg/tool/linux_amd64/6g: signal: killed
!!! Error in /go/src/k8s.io/kubernetes/hack/lib/golang.sh:388
  'go install "${goflags[@]:+${goflags[@]}}" -ldflags "${version_ldflags}" "${nonstatics[@]:+${nonstatics[@]}}"' exited with status 1
Call stack:
```

**Comment by BenTheElder** [comment]
I've since slightly increased my memory by another 256mb to 3328mb boot2docker base memory for building, and after building I kill the boot2docker vm with `boot2docker stop` before spinning up the vagrant cluster for e2e so I have some memory, alternately running one or the other. It's somewhat painful but it does work.

I also tend to interrupt release after the package tests and stick to `quick-release` most of the time as I don't deploy real releases, so I'm not sure if this will fix normal release builds, but slightly above 3gb has been working for me recently.

**Comment by satnam6502** [comment]
Thanks for the tip @BenTheElder and yes I can of course increase the memory limit. I am more worried about the experience our users have when they try to build for Mac OS X because our documentation has instructions which do not work (an issue saying use 3GB). We should update that limit... but probably not to 4G but to just what is required to build successfully.

**Comment by BenTheElder** [comment]
Yeah, that's why i worded it "at least 3gb" when i updated the mac docs last, it seems to have been going up with time.

I definitely would prefer to have less memory usage when building on mac. We could try to pin down exactly how much is needed and update the docs but it will probably just go up again unless we choose an excessive amount like 4GB, so we probably need to find a way to decrease the amount needed.

If anyone can point me to where to get started fixing the memory usage, I'd love to help as this has been a pain point while developing on my mac lately.

**Comment by satnam6502** [comment]
@cjcullen @zmerlynn who can we get to help point @BenTheElder in a promising direction for reducing memory consumption for Mac OS X builds (or builds in general)? Thanks.

**Comment by cjcullen** [comment]
#11852 just got bumped up to a P1, but doesn't have an owner yet.

**Comment by kargakis** [comment]
@kubernetes/sig-release-misc

**Comment by ixdy** [comment]
closing obsolete.
