### ISSUE TITLE
what should i do if i want to  change  container's hosts file before it start

### ISSUE THREAD

**Issue by fzu-huang** [kubernetes/kubernetes#12337]
etc. I want to start an Nginx pod. and i want to do edit the hosts file of the pod  when it  is created  ,but before Nginx is running.

**Comment by thockin** [comment]
What are you actually trying to achieve?  We don't currently expose that
feature

**Comment by erulabs** [comment]
You can roll your own Docker image, eg:

```
FROM nginx
ADD hosts /etc/
```

But most likely you're go about your actual goal in the wrong way. If you're trying to be able to do something like "ping mydatabase", you should look at Kubernetes Services: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/user-guide/services.md

**Comment by fzu-huang** [comment]
@thockin @erulabs    
well ,  i am not good at english..    : (
I am going to start a heapster, it will do some https requests to a hostname(my  kubenetes master's hostname, not IP) because my certification is build by hostname but not hostIP, so when heapster is running, I have to add a column to the container's  /etc/hosts, or it will find no route for the host.

**Comment by dalanlan** [comment]
IIUC, what @erulabs tells you is exactly the right thing to do.
You can build your own docker image and try it out.

**Comment by mbforbes** [comment]
@fzu-huang does https://github.com/kubernetes/kubernetes/issues/12337#issuecomment-128507473 answer your question? Have you gotten this to work? I'm going to close this for now, but please re-open if not!

**Comment by tonymeng** [comment]
I'm going to reopen this as editing `/etc/hosts` in a Dockerfile is essentially a no-op

```
Step 9 : RUN cat /etc/hosts
 ---> Running in f5fee576e51e
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
172.17.0.3	bcad5a346f31
 ---> 8ae569bc36eb
Removing intermediate container f5fee576e51e
Step 10 : ADD docker/hosts /etc/
 ---> 8084abbb776b
Removing intermediate container 1f4d9bb8f589
Step 11 : ADD docker/hosts /tmp/
 ---> 4c270b24385b
Removing intermediate container bf5a12b2b74c
Step 12 : RUN cat /etc/hosts
 ---> Running in d9149d6d4562
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
172.17.0.3	bcad5a346f31
 ---> a1b99bc9e8a1
Removing intermediate container d9149d6d4562
Step 13 : RUN cat /tmp/hosts
 ---> Running in 7c8b6339aef2
127.0.0.1 google.com
 ---> 867edf6691b6
```

**Comment by thockin** [comment]
/etc/hosts is a managed file - you can't just edit it Dockerfile.  I don't
really understand the issue, though.  The kube master should already be
available as a DNS name...

**Comment by tonymeng** [comment]
I'm trying to add an entry in `/etc/hosts` that will send all traffic to an internal ip on another box in the same network (application level purposes). the other service is not managed by kubernetes nor docker. I've tried adding it using dnsmasq (but can't edit `resolv.conf`) nor `/etc/hosts` as they are both "managed files"

**Comment by tonymeng** [comment]
I'm trying to add an entry in `/etc/hosts` that will send all traffic to an internal ip on another box in the same network (application level purposes). the other service is not managed by kubernetes nor docker. I've tried adding it using dnsmasq (but can't edit `resolv.conf`) nor `/etc/hosts` as they are both "managed files"

**Comment by tonymeng** [comment]
I'm trying to add an entry in `/etc/hosts` that will send all traffic to an internal ip on another box in the same network (application level purposes). the other service is not managed by kubernetes nor docker. I've tried adding it using dnsmasq (but can't edit `resolv.conf`) nor `/etc/hosts` as they are both "managed files"

**Comment by thockin** [comment]
And you don't have a real DNS server for it?  Can you add it as a Service
with `clusterIP: None` and and empty `selector` and a manually added
`Endpoints` object?  This is an "external service".

**Comment by tonymeng** [comment]
Are you referring to [this](https://github.com/kubernetes/kubernetes/issues/8631#issuecomment-104404768)? Is there a way to map that to a URL (e.g. google.com)? I do not have an internal dns server.

**Comment by hiroshi** [comment]
In my case, I have a mongo db replica set at GCE. The members of replica set are specified by local name like `db1.mongo.local`. Currently production app servers at GCE use /etc/hosts to resolve local IPs of those db replicas.

Mongo DB requires a client to be able to resolve all of members of replica set by name. We cannot access those members by IP.

It seems to be a Mongo DB specific problem, but I can imagine others may have same kind of issues...

I'm experimenting GKE to replace those app instances into kubernetes svc/pods/containers at least for staging/development.
I just want to resolve those local host names like `db1.mongo.local` from a container of GKE.

I know changinge those names to db1.mydomain.com and register it to public DNS can solve the issue, but the mongo db replica set is used by production apps, I don't want to do this for an experiment purpose.


I'm not sure I can add local DNS server like dnsmasq for this. Because /etc/resolv.conf in a container is also managed by kubernetes. Because I use GKE, changing /etc/resolv.conf of all cluster nodes doesn't seem to scale nor persistent through managed node updates.

I tried to mount /etc/hosts as a configmap entry on a pod, but I got `ContainerCannotRun`.

I could modify /etc/hosts manualy through `kubectl exec -ti my-pod /bin/sh`and it seems to work until the pod die. It seems to be possible that executing a script do the same thing at launch process of pods, but It never seems to be right solution.

FYI: I asked same problem at SO, but no response so far...
http://stackoverflow.com/questions/37166822/is-it-a-way-to-add-arbitrary-record-to-kube-dns

**Comment by thockin** [comment]
To be clear, you're trying to move mongodb into kubernetes?  Or just the
consumers of mongodb?

You can add a Service in kubernetes with clusterIP=None and an empty
selector, and then add an Endpoints object that has the IP you want.  This
will make a kube-dns record for you.  It's sort of a workaround, but it
should work for now.

**Comment by hiroshi** [comment]
> To be clear, you're trying to move mongodb into kubernetes?  Or just the
consumers of mongodb?

Just consume mongodb from kubernetes pods.

> You can add a Service in kubernetes with clusterIP=None and an empty
selector, and then add an Endpoints object that has the IP you want.  This
will make a kube-dns record for you.  It's sort of a workaround, but it
should work for now.

I'll try, but it seems that name will be `db1.default.svc.cluster.local`, but I want to use any name (e.g. `db1.mongo.local`.

**Comment by thockin** [comment]
Yeah, the name will be our style.  We don't have any way today for you to
inject your own hostname short of setting it in a DNS server.  I'll have to
think about what we could do here...  /etc/hosts is a poor way to manage
hostnames at scale...

**Comment by hiroshi** [comment]
> I'll have to think about what we could do here...  /etc/hosts is a poor way to manage hostnames at scale...

I agree that /etc/hosts doesn't scale, but it works for small numbers of hosts/containers. It doesn't seem to hart if users can use /etc/hosts in kubernetes.

Anyway I'm looking forward a solution...

For a while I'll try appending hosts to /etc/hosts after starting containers, or adding records to kube-dns etcd...

**Comment by hiroshi** [comment]
For those who want to append to `/etc/hosts`, following trick seems to work so far...

1) create configMap
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-hosts
data:
  hosts: |
    10.0.0.1  db1
    10.0.0.2  db2
```

2) write wrapper script `start.sh` and add to your image
```sh
#!/bin/sh

cat /mnt/hosts.append/hosts > /etc/hosts
exec your-app args...
```
Don't forget `chmod a+x start.sh`

2) use the configmap as volume and run start.sh
```yaml
apiVersion: extensions/v1beta1
kind: Deployment
...
spec:
  template:
    ...
    spec:
      volumes:
      - name: hosts-volume
        configMap:
          name: db-hosts
      ...
      containers:
        command:
        - ./start.sh
        ...
        volumeMounts:
        - name: hosts-volume
          mountPath: /mnt/hosts.append
        ...
```

**Comment by nmquyet** [comment]
@hiroshi My image does not run as root and get `operation not permitted` error. Is there any workaround for this problem?

**Comment by hiroshi** [comment]
@nmquyet It seems that permission issues are off-topic here, I'm afraid
Go on at stackoverflow maybe suitable.
http://stackoverflow.com/questions/37166822/is-it-a-way-to-add-arbitrary-record-to-kube-dns

**Comment by thockin** [comment]
As of right now there is not a workaround for this.  We will be adding
"external name" (CNAME) services in v1.4, which might help.  I would be
open to entertaining community proposals on how to expose something like
this.  The basic support exists in docker, but the API is all-important.

**Comment by rickypai** [comment]
CNAME support sounds great. Love to try it.

For posterity, those who tried to modify `/etc/hosts` need to be wary that since `/etc/hosts` is implemented as a volume mount during container startup, anytime you use a Pod that has a volume, when a rescheduled container needs to remount the volume, the modifications in `/etc/hosts` will be reverted.

**Comment by warden** [comment]
Linking to #13748 :-)

**Comment by klausenbusk** [comment]
I'm currently running a "web-app" pod with nginx and php-fpm (which expose foobar.com) (k8s test env), and my use-case is that I want request to foobar.com to get directly to this local webserver.

Currently we just use plain docker on CoreOS (scheduling with fleet), and I append to the hosts file at container start, but I can't do that with k8s due to:
> For posterity, those who tried to modify /etc/hosts need to be wary that since /etc/hosts is implemented as a volume mount during container startup, anytime you use a Pod that has a volume, when a rescheduled container needs to remount the volume, the modifications in /etc/hosts will be reverted.

I just read the man (http://man7.org/linux/man-pages/man3/gethostbyname.3.html), and it seems like I can use/abuse the HOSTALIASES env variable (wondering if php-fpm respect that), and solve it that way.

Should I open a new issue for this use-case?

**Comment by thockin** [comment]
I'm open to exposing this, but I have not thought it through very carefully.

**Comment by klausenbusk** [comment]
> I'm open to exposing this, but I have not thought it through very carefully.

I have opened a new issue: https://github.com/kubernetes/kubernetes/issues/43632

**Comment by mabounassif** [comment]
It may be too late to plead a case for the proponents of adding entries to `/etc/hosts`. I will however still voice my plight as a compassionate act for my brethren and sistren who found themselves in a similar situation (together we will be strong).

Here's what's up in my world right now: I'm trying to setup Jenkins on Kubernetes with a build that runs tests for an app that uses firebase as the persistent layer. As you may all know, Firebase is an online datastore and their client only supports urls that have firebaseio as the domain. To run our tests locally we run a stubbed version of Firebase (websocket server) and we modify or hosts file to point to our local ip. 

It would be amazing to be able to do that from the manifest level. I am now faced with the challenge of setting up my own nameserver and yadi yadi yada... :'(

**Comment by thockin** [comment]
Pod.spec.hostAliases was added for v1.7 - https://github.com/kubernetes/kubernetes/pull/45148

**Comment by ssubramanian123** [comment]
@hiroshi With above your solution, I am facing race condition where if replica set is 1 then it is works fine. if replica is 3 then randomly 2 pods has the valid host file, 1 pod hostfile is overwritten by k8s. From the log, i see host file script is executed and file is updated but after some time it get overwritten by k8s. If replica is 10 then randomly 5 to 6 works fine, remaining pods has host file copied but overwritten by k8s. Any way to modify in k8s to append host file and instead of replacing it?

Note : I added sleep 30; before host file copy step in the script. Looks this fixed the issue, but want to know the reason and how to fix it k8s way.

**Comment by hiroshi** [comment]
@ssubramanian123 

I found that it is needed to overwrite hosts files after k8s rewrites it.
See https://stackoverflow.com/a/37234130/338986, I used a while loop trick.

I have not used that trick since then, so I'm not sure under current implementation of k8s.
For now, k8s introduced `Pod.spec.hostAliases` as mentioned in https://github.com/kubernetes/kubernetes/issues/12337#issuecomment-306581240. I suggest you should use the feature if you can. I haven't used it yet though.

**Comment by klausenbusk** [comment]
@hiroshi @ssubramanian123 
Another solution is patching the library which read the `hosts` file, I have done that before like so:
```
sed -i "s:/etc/hosts:/tmp/hosts:g" "/lib/x86_64-linux-gnu/libnss_files.so.2"
```

**Comment by colindev** [comment]
i have the same question on kube 1.7
my deployment need send REST api to a peering conn network at 10.5.x.x 
but the API app need a host like [xxx.com]
so...
can i use a service
```
apiVersion: v1
kind: Service
metadata: 
  name: for-rest-api
spec:
  type: ExternalName
  externalName: xxx.com
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: v1
kind: Endpoints
metadata:
   name: for-rest-api
subsets:
  - addresses:
      - ip: 10.5.xx
    ports:
      - port: 80
```
i try this, but it's not work

**Comment by rickypai** [comment]
@colindev would this work for you? https://kubernetes.io/docs/concepts/services-networking/add-entries-to-pod-etc-hosts-with-host-aliases/

**Comment by colindev** [comment]
@rickypai i will try it, thx

**Comment by colindev** [comment]
i found the problem
ref: https://ben.straub.cc/2015/08/19/kubernetes-aws-vpc-peering/
i need set an iptable rule allow 10.5.0.0/16 go throw eth0
