### ISSUE TITLE
DRA: kubelet: checkpoint checksum changes when API gets extended

### ISSUE THREAD

**Issue by pohly** [kubernetes/kubernetes#123552]
### What happened?

When adding the `StructuredData` field to `resourcev1alpha2.ResourceHandle`, old checkpoint files became invalid because the checksum that gets calculated by hashing the `spew` output in `pkg/util/hash` no longer matches. This caused kubelet to fail to start with:
```
E0228 10:46:47.293483  363727 run.go:74] "command failed" err="failed to run Kubelet: failed to create claimInfo cache: error calling GetOrCreate() on checkpoint state: failed to get checkpoint dra_manager_state: checkpoint is corrupted"
```

Here's what the checksum in a unit test gets calculcated for:
```
"(*state.DRAManagerCheckpoint){Version:(string)v1 Entries:(state.ClaimInfoStateList)[{DriverName:(string)[test-driver.cdi.k8s.io](http://test-driver.cdi.k8s.io/) ClassName:(string)class-name ClaimUID:(types.UID)067798be-454e-4be4-9047-1aa06aea63f7 ClaimName:(string)example Namespace:(string)default PodUIDs:(sets.Set[string])map[139cdb46-f989-4f17-9561-ca10cfb509a6:{}] ResourceHandles:([]v1alpha2.ResourceHandle)[{DriverName:(string)[test-driver.cdi.k8s.io](http://test-driver.cdi.k8s.io/) Data:(string){\"a\": \"b\"} StructuredData:(*v1alpha2.StructuredResourceHandle)<nil>}] CDIDevices:(map[string][]string)map[[test-driver.cdi.k8s.io](http://test-driver.cdi.k8s.io/):[[example.com/example=cdi-example]]}]](http://example.com/example=cdi-example]]%7D]) Checksum:(checksum.Checksum)0}"
```

Note the new `StructuredData:(*v1alpha2.StructuredResourceHandle)<nil>`.

### What did you expect to happen?

Not sure what the right behavior is. Perhaps kubelet should have ignored the invalid checkpoint?

### How can we reproduce it (as minimally and precisely as possible)?

Revert the pkg/kubelet/cm/dra/state/state_checkpoint_test.go update in https://github.com/kubernetes/kubernetes/pull/123516.

### Anything else we need to know?

The state.DRAManagerCheckpoint contains a version field, which is set to v1.I think that's where things fall apart: that version must exactly match the type that gets serialized, which is not the case here. The type changes over time, but the version is fixed.

Let's reconsider what should get checkpointed and how we can make that stable. Also, is checkpointing really worth it? What bad things happen if we remove it?

### Kubernetes version

master

### Cloud provider

n/a

### Related plugins (CNI, CSI, ...) and versions (if applicable)

/sig node
/cc @bart0sh @klueska

**Comment by klueska** [comment]
We originally didn't have checkpointing and it was added by @moshe010 in https://github.com/kubernetes/kubernetes/pull/115912 to fix https://github.com/kubernetes/kubernetes/issues/115902

**Comment by moshe010** [comment]
The reasons for checkpoint were: 
1.  https://github.com/kubernetes/kubernetes/pull/115912 (what Kevin mentioned)
2. part of the pod resource API DAR extensions concerns raised on what happen if kubelet restart and we get GetPodResourcesRequest. The request should return the DRA claimed devices but if we didn't checkpoint the DRA cache is empty and we would return empty resources
3. pod force delete see [2]

My original PR didn't checkpoint the ResourceHandle is was added in PR [2]. Maybe  we should exclude ResourceHandle  from the checksum hash calculation 



[1] https://github.com/kubernetes/enhancements/pull/3738#discussion_r1099076427 
[2] -https://github.com/kubernetes/kubernetes/pull/119307

**Comment by pohly** [comment]
So the cache makes sense. What doesn't make sense to me is how the consistency of that on-disk file is checked and how it is versioned.

Shouldn't the checksum be calculated for the bytes on disk (version-independent) instead of the in-memory representation (version-dependent)? Or is the goal to protect against "I can't read this data anymore" instead of "bit has flipped on disk"?

The assumption is that the content can always be decoded from what was written in the past into the type which is used now. This works with JSON if the newer type is a true superset of the old one, but that's not necessarily guaranteed. The proper way of doing this is to define a scheme which includes conversion between different versions.

This cannot be done when embedding API types from resource.k8s.io because conversion between current v1alpha2 and a future v1beta1 can only be done in the apiserver, not client-side.

I don't see a quick solution here.

In the short-term, how do we deal with version upgrades? Require that users drain the node (thus clearing the cache) before upgrading or downgrading kubelet?

**Comment by moshe010** [comment]
I am still trying to understand the problem. 
1. It the problem that we checksum the version? 
2. Is the problem that we don't have conversion mechanism to move from version X -> version Y on upgrade? 
3. Is the issue related only for upgrade or there are other cases which checksum changes? 

In general we added the version to checkpoint file so that in the future when the DRA checkpoint struct changed we can have mechanism to convert old checkpoint version to new checkpoint version (in the initial PR we didn't implement conversion mechanism as I thought it will be added on DRA checkpoint struct change) . If you take a look on the CPU Manager checkpoint  [1] you will see that it detecting if the scheme matches to V1 first and if not it assume V2. We wanted that it will part of the checkpoint file so we won't need such detection and in the file we will know that correct version of the DRA checkpoint struct. 

Now if someone change the DRA checkpoint scheme and didn't implement migration flow (similar to CPU manager [2]) or change the version that indeed an issue, 

[1] - https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/cm/cpumanager/state/state_checkpoint.go#L98 
[2] - https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/cm/cpumanager/state/state_checkpoint.go#L108

**Comment by pohly** [comment]
The problem is that after an upgrade of kubelet from <1.30 to 1.30, it won't be able to read an existing, non-empty checkpoint file. Worse, it will refuse to start because of that.

The root cause is the lack of proper versioning and lack of conversion code.

> Is the issue related only for upgrade or there are other cases which checksum changes?

Any version change potentially has this problem (including downgrades). I'm not aware of other failure scenarios.

**Comment by liggitt** [comment]
This has to be solved before graduating from alpha

**Comment by pohly** [comment]
I intend to move all version-dependent code into drivers (https://github.com/kubernetes/kubernetes/issues/123699). This will simplify the checkpoint content a bit, but the overall questions around its design remain.

**Comment by bart0sh** [comment]
> The problem is that after an upgrade of kubelet from <1.30 to 1.30, it won't be able to read an existing, non-empty checkpoint file. Worse, it will refuse to start because of that.

Isn't it because checkpoint structure was changed without incrementing version and adding conversion code?

Anyway, I'd propose to remove version from the checkpoint structure and comment it to prevent changing it without changing its version. the implementation should be similar to the cpu maanager checkpointing. If it's been working for CPU (and device?) managers for some time, it should hopefully work for DRA as well.

Any other ideas?

**Comment by pohly** [comment]
> Isn't it because checkpoint structure was changed without incrementing version and adding conversion code?

Yes.

@bart0sh: I haven't looked into this again. Can you implement your proposal on top of https://github.com/kubernetes/kubernetes/pull/125488 and submit a PR for review, or do you want to discuss this first?

**Comment by bart0sh** [comment]
@pohly if you're ok with my proposal I'm ok to implement it. Otherwise it needs to be discussed further.

**Comment by pohly** [comment]
I don't fully understand the implications without looking into this further, so I can say neither yes nor no to it at this point.

@klueska: do you have an opinion?
