### ISSUE TITLE
AWS elb creation fails when there are multiple subnets in one AZ

### ISSUE THREAD

**Issue by mariomarin** [kubernetes/kubernetes#12381]
I am trying to launch an ELB with kubernetes from cloudformation. I created the VPC, named it *kubernetes-vpc*, then,  I created the subnets.

I need the RDS instance for a CI environment, so finally, I launched the RDS instance and the RDS wizard, with my consent, created a new subnet in an availability zone used by another subnet inside *kubernetes-vpc*.

This is the error message I get when the controller manager tries to attach the instances to the ELB.

```
kube-controller-manager[2132]: E0806 02:44:42.322509    2132 servicecontroller.go:173]
Failed to process service delta.
Retrying: failed to create external load balancer for service default/mycustomservice:
InvalidConfigurationRequest: ELB cannot be attached to multiple subnets in the same AZ.
```

The docs should warn about creating multiple subnets in the same availability zone inside kubernetes-vpc or group the AZs before giving their names to the controller manager.

**Comment by satnam6502** [comment]
@justinsb

**Comment by eramus** [comment]
Personally, I think we should just harden the AWS cloudprovider for creating (or selecting) a valid ELB regardless of subnet configuration. Since we can only select one subnet per AWS's requirements, I see a few different ways that we could do this:
* Attach a tag to the subnet in which we want to associate ELBs. This would create an easy method for selecting subnets.
* Parse the route tables to select a subnet that has an IGW attached -- we could assume a public subnet at that point.

Outside of the main issue, it would also be nice if we had a mechanism for attaching to an existing ELB. Again, modifications would be needed to update the set of listeners:
* Make use of labels to group services together in logical groups. This would work well with one of the proposed subnet rules above.
* A new option could be added to service definitions to directly identify an existing ELB. This may take more work since it would probably have an impact on APIs above the cloudprovider layer, but this would allow for a high level of flexibility.

**Comment by eramus** [comment]
@justinsb @satnam6502  Do you mind weighing in on what should be a proposed/acceptable solution for selecting an appropriate subnet and/or load balancer when creating a service? I have some free time to work on the fix, but I think a consensus on a method for and priority of selection should be made first.

**Comment by satnam6502** [comment]
We are trying to form working groups to discuss various aspects of Kubernetes and there will be a group which has external access as one of its main focus items. I would propose that folk on this thread consider joining that group and help discuss/drive a design going forward which has wider consensus. I think improving the situation is a non-trivial work item. @thockin

**Comment by justinsb** [comment]
Hi @eramus - thank you for figuring out the problem and being willing to work on a fix.

The approach I was taking was that we should match by tags, in particular the "KubernetesCluster" tag.  I have a WIP "under-the-hood" document here: https://github.com/GoogleCloudPlatform/kubernetes/pull/11938/files

So we should be tagging the subnets with a KubernetesCluster tag, and we should be filtering on that also.

The default kube-up script does tag the subnet with the KubernetesCluster tag, and it looks like the code will also filter subnets on the KubernetesCluster tag.

So I suspect that either (1) we have a bug or (2) this is another case where the non-kube-up scripts do things a little differently in ways that don't quite work.  The latter is my motivation for writing the "under the hood" document in #11938.

On your point about reusing an existing ELB, I think everyone agrees there.  I think the reason it didn't make V1 is that the security model around it isn't particularly clear; and that we probably would want to do something similar to PersistentVolume / PersistentVolumeClaim, but there simply wasn't time.

@satnam6502 I hope I get invited to the AWS working group :-)

**Comment by sachingharge** [comment]
Hi All,

I could see two errors when creating ELB for service with cloudformation kubernetes stack.

Error when service created first time:
creating loadbalancer failed	failed to create external load balancer for service default/service_name: error tagging security group: InvalidParameterValue: Value ( '' ) for parameter Tag key is invalid. Tag key cannot be null or empty. status code: 400, request id: []

When running describe service again (kubectl describe svc service_name):
failed to create external load balancer for service default/service_name: InvalidConfigurationRequest: ELB cannot be attached to multiple subnets in the same AZ.

Please let me know your inputs on this.

**Comment by mariomarin** [comment]
@justinsb I've followed these steps with my current k8s cluster:

- Attached *name: kubernetes-vpc* tag  to vpc.
- Attached *KubernetesCluster: foo* tag name to instances and security groups with cloudformation.
- Attached *KubernetesCluster: foo* tag name to subnets and vpc manually.
- Launch the service to create the ELB.

It didn't work, I got `InvalidConfigurationRequest: ELB cannot be attached to multiple subnets in the same AZ.` from the events log.

I finally deleted the extra subnet and now all my subnets are unique inside each AZ; this is a workaround but k8s is able to create ELBs. The extra subnet wasn't necessary in my case, it was just an accident after a lousy RDS instance creation; however, there must be use cases for multiple subnets in the same AZ.

**Comment by chrisleck-old-personal** [comment]
Tagging really isn't sufficient here, though is a place to start.  We really want the ability to create both "public" LoadBalancers (for Internet facing services) and "private" LoadBalancers for use only within the VPC by other non-Kubernetes instances.  I think that requires subtyping of the LoadBalancer so an appropriate subnet can be chosen - perhaps allow a subnet tag to be passed into the Service config for this case?

In addition, we also want services exposed as LoadBalancers to be able to provide friendly names through DNS CNAME records - but that's probably a separate request :)

**Comment by jtblin** [comment]
So the fix works in the sense only one subnet per AZ is picked but it doesn't really work because it picks the subnets randomly so in my case it picked up subnets that are private so the ELBs couldn't be reached. There doesn't seem to be a reliable way to determine if subnets are public or private (looking at the route table and check if traffic is sent to an internet gateway?) so it looks like we really need what @chrisleck-old-personal suggested i.e. the ability to pass which subnets should be used. It doesn't seem there is any ticket about this issue, although #16083 seems related. At the moment it's pretty much impossible to use ELBs in AWS with a standard vpc topology.

**Comment by hSATAC** [comment]
+1 to @jtblin

**Comment by manojlds** [comment]
+1 to @jtblin

**Comment by gopinatht** [comment]
+1 on this issue. Is the fix available in V1.1.7? I used this version today and I still get the error "InvalidConfigurationRequest: ELB cannot be attached to multiple subnets in the same AZ."

**Comment by jtblin** [comment]
I submitted a PR (#17912) for that but there is some discussion around whether it is actually needed.

Tagging the subnets properly fixed the issue for me in the meantime, see https://github.com/kubernetes/kubernetes/blob/master/docs/design/aws_under_the_hood.md.

**Comment by manojlds** [comment]
So what if I want some ELBs to be in private and some in public subnets? Is that something people think as being valuable? Currently, all my ELB management is via Terraform, and I only use NodePort in Kubernetes. More control on ELBs from k8s would be very helpful.

**Comment by gopinatht** [comment]
@manojlds Just curious, how do you use NodePorts? Do you just assign some static IP to a minion/node and use the port with it?

**Comment by manojlds** [comment]
@gopinatht - i point the ELB at the ASG of kubernetes nodes and configured to look at the NodePort for the corresponding service.

**Comment by gopinatht** [comment]
@manojlds thanks! did not know we could do that but that makes sense.

**Comment by jcderr** [comment]
Tagging the subnets doesn't work well in all circumstances - for instance, I'm not using kube-up, and some of my clusters go into VPCs that I cannot edit the tagging of. Passing a flag with allowed subnets is greatly preferred.

**Comment by justinsb** [comment]
@jcderr I don't think we require a tag on the VPC (if we do, we can probably relax that requirement).  But - at least for now - k8s realistically runs best in its own subnet that it "owns".  This issue is pretty meandering, so if tagging subnets is a problem, perhaps you can open a new one, and explain your particular use case!

And you should use kube-up :-)
