### ISSUE TITLE
GCE machine unresponsive

### ISSUE THREAD

**Issue by mbilko** [kubernetes/kubernetes#12389]
After deploying a pod without memory limit and running in this pod a program which allocates a lot of memory (more than machine has) a machine becomes completely unresponsive. It is impossible to ssh into it or check cAdvisor status.
Machine type: g1-small

**Comment by satnam6502** [comment]
Please can you provide a bit more information to allow a repo? Thank you kindly.

**Comment by dchen1107** [comment]
@mbilko based on what described above, this is expected behavior since you overcommit your node with memory, and trigger sys oom. With incoming 1.1 kubernetes release, we are going to do better work on resource management. The start point is the latest QoS proposal: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/proposals/resource-qos.md

**Comment by dchen1107** [comment]
In your current use case, can you specify memory limit for your application, so that it could be oom-killed by memory-exceeded? Or you have some special use case?
