### ISSUE TITLE
Consider "attach controller" to secure cloud provider credentials

### ISSUE THREAD

**Issue by markturansky** [kubernetes/kubernetes#12399]
Currently, each node in the cluster requires cloud provider credentials so that the node can attach a GCE/EBS volume.  A compromised node can lead to the exposure of those credentials.

An alternative approach would be to limit cloud provider credentials to Master and perform the attachment in a control loop that watches for newly scheduled pods.

@smarterclayton any additional thoughts or requirements?

**Comment by smarterclayton** [comment]
In the future, this might also impact fencing for other storage solutions
as well - where the "attach" controller is doing something like taking a
lock for volume source.

On Fri, Aug 7, 2015 at 10:14 AM, Mark Turansky <notifications@github.com>
wrote:

> Currently, each node in the cluster requires cloud provider credentials so
> that the node can attach a GCE/EBS volume. A compromised node can lead to
> the exposure of those credentials.
>
> An alternative approach would be to limit cloud provider credentials to
> Master and perform the attachment in a control loop that watches for newly
> scheduled pods.
>
> @smarterclayton <https://github.com/smarterclayton> any additional
> thoughts or requirements?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleCloudPlatform/kubernetes/issues/12399>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by childsb** [comment]
Request change to P1 issue.  This is a security hole and a blocker for OpenShift.

Currently if a single node is compromised this issue exposes the entire cluster.

**Comment by thockin** [comment]
This is not exactly a "new" issue

**Comment by smarterclayton** [comment]
Let's reframe that as - Mark and Brad are going to work on this because we feel the security risk is too high for normal operational use when there is O(several) parties on the cluster.  Structurally, what concerns / reservations are there to an implementation here that would only allow attach from a controller?

**Comment by thockin** [comment]
No concerns - we want to do it, and @saad-ali has a design doc, but it
has to fit into the larger volumes / storage plan, too.

**Comment by saad-ali** [comment]
@childsb This is definitely something that has been high pri for us. I have a preliminary detailed design doc to move attach/detach logic to a controller. I haven't shared it publicly yet because I want to make sure it's in alignment with whatever we decide for https://github.com/kubernetes/kubernetes/issues/18333. We're planning on closing on https://github.com/kubernetes/kubernetes/issues/18333 next week. Once that happens, I'm planning on publishing the design doc and starting coding soon after.

**Comment by thockin** [comment]
@childsb will you be in Raleigh next week?

**Comment by childsb** [comment]
@thockin i'l be at the Raleigh meetings, lets discuss then.

**Comment by thockin** [comment]
Superceded by https://github.com/kubernetes/kubernetes/issues/20262
