### ISSUE TITLE
Deprecate & remove Kubelet RunOnce mode

### ISSUE THREAD

**Issue by tallclair** [kubernetes/kubernetes#124030]
This was raised back in 2017 (https://github.com/kubernetes/kubernetes/issues/47184), but I think it's time to revisit it.

I'm not sure if anyone is using it, but runonce mode doesn't support many newer pod features (init containers), and the pod lifecycle for runonce mode is even less well defined than normal. The mode appears to be entirely untested in CI, except for a few unit tests.

Furthermore, I believe podman addresses the same use case in a more well-supported way: https://docs.podman.io/en/latest/markdown/podman-kube.1.html

I propose we mark runonce mode as deprecated in k8s v1.31, slated for removal in v1.33

/sig node
/milestone v1.31
/kind deprecation

**Comment by tallclair** [comment]
@haircommander do you think it makes sense to recommend users migrate to podman for this use case? Are there any notable differences?

**Comment by tallclair** [comment]
Do we need a KEP for this?

**Comment by haircommander** [comment]
I would caution that since `podman play kube` is essentially a reimplementation of the pod lifecycle that there probably are subtle differences between the two, but yes I think it could be a suitable replacement. to be honest, I'm surprised that RunOnce option exists in the kubelet at all, and would definitely support dropping support for it. I think it'd be worth bringing up to SIG-Node, but it seems like the type of thing we could avoid a KEP for (as it is kubelet internal flag and doesn't affect other components)

**Comment by dchen1107** [comment]
Discussed it at SIG Node KubeCon. Agreed to have a KEP to raise the awareness to the potential users.

**Comment by HirazawaUi** [comment]
Can I pick it and create a KEP for it?

**Comment by tallclair** [comment]
/assign @HirazawaUi 

Please go ahead

**Comment by tallclair** [comment]
Closing in favor of https://github.com/kubernetes/enhancements/issues/4580

**Comment by HirazawaUi** [comment]
After tracing back, the `runonce` mode seems to have completely stopped working in #90377, because the `cpuManager` is not initialized in `runonce`, when calling [activePods()](https://github.com/kubernetes/kubernetes/blob/44b2c363f2ff05554d223ce7a883388ec32576c3/pkg/kubelet/cm/cpumanager/cpu_manager.go#L364) will cause _nil pointer_ and kubelet panic. Since the milestone of #90377 is 1.19, I believe that no users are using it in the newer version.

Although it is no longer available, I think we can continue this KEP so that people who use it in the new version can know through warning logs and documents that we are no longer planning to maintain it. What do you think? @tallclair 

Sorry for reporting this so late, it should have been investigated when submitting the KEP...
