### ISSUE TITLE
SCTP Server on agnhost image crashes when a client connects from the same pod

### ISSUE THREAD

**Issue by aojea** [kubernetes/kubernetes#124209]
How to repro:
1. Run an agnhost pod listening on sctp
```
spec:
  containers:
  - command:
    - /agnhost
    - netexec
    - --sctp-port
    - "8080"
    image: registry.k8s.io/e2e-test-images/agnhost:2.39
```

2. Exec into the pod and use the connect command to probe against the same pod
```
/agnhost connect --timeout=2s --protocol=sctp localhost:8080
bash-5.0# FATA[0014] execing command in container: command terminated with exit code 137
```

The stack trace 

```
I0406 18:21:17.102027       1 log.go:195] Started HTTP server on port 8080
I0406 18:21:17.102399       1 log.go:195] Started UDP server on port  8081
I0406 18:21:17.102465       1 log.go:195] Started SCTP server
I0406 18:22:07.943777       1 log.go:195] SCTP server exited
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x15097bb]

goroutine 77 [running]:
k8s.io/kubernetes/test/images/agnhost/netexec.startSCTPServer(0x0?)
        /go/src/k8s.io/kubernetes/test/images/agnhost/netexec/netexec.go:696 +0x3fb
created by k8s.io/kubernetes/test/images/agnhost/netexec.main
        /go/src/k8s.io/kubernetes/test/images/agnhost/netexec/netexec.go:217 +0x22f
root@kind-worker:/#

```

that points to 

https://github.com/kubernetes/kubernetes/blob/f8930f980d2986f9e486b04c14c3e93e57bdbe12/test/images/agnhost/netexec/netexec.go#L696

and this is from the vendored library vendor/github.com/ishidawataru/sctp/sctp.go , 

/kind bug
/sig network 
/help

**Comment by aroradaman** [comment]
here we are immediately closing the connection after successful connect leading to EOF at server end (it is expecting data) causing the failure.
https://github.com/kubernetes/kubernetes/blob/22140b6a070e09589b5b2bcdf5c396114f25274f/test/images/agnhost/connect/connect.go#L116-L122

We can tweak this to connect send some data just like UDP and then exit?
https://github.com/kubernetes/kubernetes/blob/22140b6a070e09589b5b2bcdf5c396114f25274f/test/images/agnhost/connect/connect.go#L55

**Comment by aojea** [comment]
the panic seems a bug in that project, no?

**Comment by aroradaman** [comment]
[Accept(4)](https://linux.die.net/man/2/accept4) returns fd and socket address, for [TCP the returned socket address](https://github.com/golang/go/blob/master/src/internal/poll/sock_cloexec_accept.go#L22) is used to implement `RemoteAddr` (always read from struct field).

The SCTP implementation discards the returned socket address by `Accept` call.
https://github.com/ishidawataru/sctp/blob/7ff4192f6ff2b4b181ec7dce269bdf4076ff90a0/sctp_linux.go#L235, and `RemoteAddr` is always a new syscall ([SCTP_GET_PEER_ADDRS](https://man7.org/linux/man-pages/man7/sctp.7.html#:~:text=passed%20to%20users.-,SCTP_GET_PEER_ADDRS,-This%20option%20is)). 

In our case the client immediately closes the connection, there can be chances where SCTP_GET_PEER_ADDRS will fail and `RemoteAddr` will return nil in these cases.  I think this is reasonable for their project. 

We call `conn.RemoteAddr().String()` and panic is raised by calling `String()` on nil object. We can easily avoid this by not null check. Also, I strongly believe that the client handling should be done in a separate go-routine instead of the main loop to avoid errors like this crashing the pod.

**Comment by aojea** [comment]
>  I think this is reasonable for their project.

panicing does not seem very reasonable

It looks to me that the problem is that the SCTPConn struct needs to check if the connection is still valid before trying to access the file descriptor , see the std library implementation https://github.com/golang/go/blob/5c20d5faeb3d048a31896f3edfb54dbd960d07cc/src/net/net.go#L173

and then, all methods implement this check 

https://github.com/golang/go/blob/5c20d5faeb3d048a31896f3edfb54dbd960d07cc/src/net/net.go#L226-L230

to me it is a bug on the implementation

**Comment by aojea** [comment]
@aroradaman are you able to send a PR to add those improvements to the test image?
