### ISSUE TITLE
Scheduler still counts InitContainer resource requests after a pod finishes initialization

### ISSUE THREAD

**Issue by peter-emil** [kubernetes/kubernetes#124282]
### What happened?

I created a 1-node EKS cluster with that node having 4 CPU cores. I made sure at least 3.5 cores were allocatable after running all the daemonsets.

I created a deployment that has InitContainers, here is a summary of what that looked like (I replaced container names with dummy values and removed all the unnecessary container configuration).
```
initContainers:
    - image: 'test/initialization:v3.1.3'
      name: initialize
      resources:
        requests:
          cpu: 3
containers:
    - image: test/do-stuff
      resources:
        requests:
          cpu: 30m
```

I set the number of replicas to 1 and a pod successfully got scheduled, initialized and transitioned to the running phase.

I then bumped the number of replicas to 2, expecting the second pod to become scheduled since the first pod already finished initialization. However, it failed to schedule
```
Events:
  Type     Reason            Age                 From               Message
  ----     ------            ----                ----               -------
  Warning  FailedScheduling  57s (x2 over 6m3s)  default-scheduler  0/1 nodes are available: 1 Insufficient cpu. preemption: 0/1 nodes are available: 1 No preemption victims found for incoming pod.
```

### What did you expect to happen?

I expected the second pod to go through since the first pod had already finished initialization and the CPU it requests for running would definitely leave more than 3 cores allocatable for the next pod.

From the documentation, I know the scheduler computes the "effective resource requests" on pods with InitContainers by getting the maximum requests across InitContainers and containers. I understand how this is essential when deciding where to place a pod.

However, if a pod finishes initialization and transitions to the running phase, I'd expect the scheduler to discard the requests specified on InitContainers when it's computing how many resources are already scheduled on a particular node.

### How can we reproduce it (as minimally and precisely as possible)?

1. Start with a minimal cluster with one node and keep note of how many CPU is allocatable.
2. Run 1 pod on the cluster that has an InitContainer comprising 75% of the allocatable CPU and a container with negligible CPU requests
3. Wait till that pod finishes initialization and then run another one. The other one will not be schedulable.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.0", GitCommit:"b46a3f887ca979b1a5d14fd39cb1af43e7e5d12d", GitTreeState:"clean", BuildDate:"2022-12-08T19:58:30Z", GoVersion:"go1.19.4", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"29+", GitVersion:"v1.29.1-eks-b9c9ed7", GitCommit:"07600c74de018baffb16c82771a48adcb843a932", GitTreeState:"clean", BuildDate:"2024-03-02T03:46:35Z", GoVersion:"go1.21.6", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
EKS (Amazon AWS)
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
SUPPORT_END="2025-06-30"
$ uname -a
Linux <hostname trimmed> 5.10.205-195.807.amzn2.x86_64 #1 SMP Tue Jan 16 18:28:59 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

```

</details>

### Install tools

<details>

- EKS Cluster was installed using terraform
</details>

### Container runtime (CRI) and version (if applicable)

<details>
containerd 1.7.11 on EKS
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

- coredns from Amazon EKS version: `v1.11.1-eksbuild.6`
- VPC CNI from Amazon EKS version: `v1.16.2-eksbuild.1`
- Kube Proxy from Amazon EKS version: `v1.29.0-eksbuild.2`
- Amazon EBS CSI Driver from Amazon EKS version: `v1.27.0-eksbuild.1`
</details>

**Comment by chengjoey** [comment]
The allocatable resource is calculated and uploaded by kubelet, and the allocated resource is calculated by the scheduler component. It does not calculate whether the corresponding status of the container has exited.

https://github.com/kubernetes/kubernetes/blob/cae35dba5a3060711a2a3f958537003bc74a59c0/pkg/api/v1/resource/helpers.go#L96-L120

Then determine whether the pod can be scheduled to the node:
https://github.com/kubernetes/kubernetes/blob/cae35dba5a3060711a2a3f958537003bc74a59c0/pkg/scheduler/framework/plugins/noderesources/fit.go#L442-L450

in this example, you could change set nodeName in pod spec like this
```
spec:
  template:
    spec:
      nodeName:${you node name}
```

In this way, resource determination can be skipped and the pod can be directly scheduled to the corresponding node, and then the following situation will occur:
<img width="587" alt="image" src="https://github.com/kubernetes/kubernetes/assets/30427474/a058650e-5972-46a6-bccb-cc01cd6956ae">
<img width="690" alt="image" src="https://github.com/kubernetes/kubernetes/assets/30427474/cee195bb-9357-4126-9933-cad5e680706d">


I did a simple debug test and modified the logic of pod requests resources so that the exited container was not counted in the allocated resources.
<img width="955" alt="image" src="https://github.com/kubernetes/kubernetes/assets/30427474/b5ddf278-335e-4836-aeb7-1da1c0e54407">

Then rebuild the scheduler and kubelet and release them, and run the above example again, so that it can run smoothly
<img width="549" alt="image" src="https://github.com/kubernetes/kubernetes/assets/30427474/2977206b-a814-452a-967f-1893774ca769">

**Comment by chengjoey** [comment]
In addition, this should not be considered a bug, because the init container in the pod needs to be restarted and executed again after the pod exits, so sufficient resources need to be prepared.

[resource-sharing-within-contaienrs](https://kubernetes.io/docs/concepts/workloads/pods/init-containers/#resource-sharing-within-containers)

Under normal circumstances, the init container is unlikely to require more resources than the logical container. It is mostly used for initialization operations and resources should be allocated reasonably.

**Comment by peter-emil** [comment]
Thank you for your response @chengjoey , I learnt a lot just by reading it :)

> this should not be considered a bug, because the init container in the pod needs to be restarted and executed again if the pod container exited(oom, etc), so sufficient resources need to be prepared.

This makes sense to me if the container exited (oom, etc) before it finished the init phase (in other words, the init container itself was OOMKilled and needs to be restarted).
However, if the init phase was finished and the pod is already in the running phase (all main containers running) then why would the InitContainer ever need to re-run? If one or more of the main containers crash and restart, it's my understanding that they would do so without re-running the InitContainers hence the resource requests of the InitContainers are irrelevant.
On the other hand, if the pod is managed by a ReplicaSet and it gets deleted, then a potentially new one would just be rescheduled and can potentially be allocated to a different node for any reason, hence why does it make sense for the original node to keep holding on to resources required by the InitContainer(s) only 🤔 .

> Under normal circumstances, the init container is unlikely to require more resources than the logical container. It is mostly used for initialization operations and resources should be allocated reasonably.

I understand your point but would argue that in some scenarios initialization is more resource intensive than actually running a container and we have multiple use cases for this. For example: we use our InitContainer(s) to resolve secrets for our workers, which requires at least 200m of CPU. The worker logic itself needs 10m of CPU to run. Multiply this by 500 workers and we're wasting 95 CPUs 😅 

When I learnt that you could set different resource requests for InitContainers from main containers, I intuitively thought that this is intended to support use cases where initialization is a resource intensive process unlike the "Running" phase or what's the point of it if not so? 🤔 Maybe there's another use case beyond my personal knowledge but these were my thoughts on why this can potentially be a bug.

**Comment by chengjoey** [comment]
@peter-emil I think InitContainer Resource will still be counted as allocated resource even though exited because there are several [pod restart reasons](https://kubernetes.io/docs/concepts/workloads/pods/init-containers/#pod-restart-reasons) will re-execution of init containers, if there is a mechanism to ensure that the pod will not restart, then the InitContainer's resources should be released after initialization.

**Comment by peter-emil** [comment]
@chengjoey , ah it makes sense then if pods can be restarted. I never ran into a pod restart myself ever 😅 

> if there is a mechanism to ensure that the pod will not restart, then the InitContainer's resources should be released after initialization

I think this should be the default behavior and users can choose otherwise if they want to.

Otherwise, what's the point for having separate resource requests for the InitContainer; if the main container is higher then specifying for the InitContainer is redundant and if vice versa then I'd rather just give the higher requests to the main container since these resources will be allocated for the pod anyway and never released throughout the pod's lifetime.

Maybe having something under the pod spec like `releaseInitContainerResourcesAfterInitialization: true` would be helpful 🤔

**Comment by chengjoey** [comment]
> @chengjoey , ah it makes sense then if pods can be restarted. I never ran into a pod restart myself ever 😅
> 
> > if there is a mechanism to ensure that the pod will not restart, then the InitContainer's resources should be released after initialization
> 
> I think this should be the default behavior and users can choose otherwise if they want to.
> 
> Otherwise, what's the point for having separate resource requests for the InitContainer; if the main container is higher then specifying for the InitContainer is redundant and if vice versa then I'd rather just give the higher requests to the main container since these resources will be allocated for the pod anyway and never released throughout the pod's lifetime.
> 
> Maybe having something under the pod spec like `releaseInitContainerResourcesAfterInitialization: true` would be helpful 🤔

I think your idea is great, but in some cases, this allocates resources as much as possible. If the Pod infrastructure container is restarted, it may cause allocated resource > allocatable resource, i think your idea is great, it can be left to the user to decide

**Comment by fullykubed** [comment]
I was also looking for an answer to the problem of having very resource-heavy init processes that need > the sum of the requests from the app containers (e.g., database migrations, dynamic compile steps, etc.).

I agree this would be a useful opt-in feature. 

Right now this is called out as being a primary use case of the upcoming [in-place updates](https://kubernetes.io/blog/2023/05/12/in-place-pod-resize-alpha/) but this requires another controller (VPA) to perform the updates. Ideally, this could be solved by simply allowing the release of init resources.
