### ISSUE TITLE
Proposal: Allow anonymous inline claim in pod definition

### ISSUE THREAD

**Issue by ghost** [kubernetes/kubernetes#12450]
If you have a replicationcontroller with a pod that uses claims for persistent storage you currently have a hard time to scale them up. The name of the claim is part of the pod definition, so if you try to scale up every pod will try to use the same claim. If you have a scalable application where each pod needs its own storage this is not what you want.

If you can add an anonymous claim as part of the pod definition, a new pod would automatically be assigned with a new claim for his storage. If you scale down that claim get deleted and the claimed storage gets freed up.
Also, the claim must be reassigned to a new pod in case of a rolling update without getting cleared.

**Comment by a-robinson** [comment]
cc @markturansky

**Comment by markturansky** [comment]
Thanks for filing the issue.  Scaling storage is difficult today through an RC, for the reasons you mention.

This is a feature we (I) fully intend to revisit and implement.  Our go-to use case is "How do you scale MongoDB?"

**Comment by thockin** [comment]
Agree this is a facet we need to handle, I'll probably argue that we need
something like this MORE than we need auto-provisioning

@saad-ali

**Comment by markturansky** [comment]
@thockin I think they may be related.  Imagine if an RC could lay claim to a PersistentVolumeController (instead of a single volume) that can make N replicas of a volume from Min up to Max.    The entire pool (however large or small) managed by one PVCtrl can be used as a resource by an RC.

The part I don't grok yet is how we'll pin the same volume to the same or similar pod in the future.  In the even of cluster restart, how does the same PV get used in the same pod/replica created by an RC?  Further, what if all those pods are taken down, upgraded to a newer image, and a new RC deployed that wants to use all the same volumes?  I don't yet know how to pin those future pods to specific volumes.

Design suggestions?

**Comment by markturansky** [comment]
@smarterclayton design suggestions welcome :)

**Comment by smarterclayton** [comment]
This is overlapping with nominal services https://github.com/GoogleCloudPlatform/kubernetes/issues/260 

I don't think we want to have anonymous allocation because we want them to be reused, and there really has to be some object that maps that ownership.  There's discussion in #260 about the current design points.  The concern is making the RC own them.

**Comment by thockin** [comment]
I discussed a bit with @saad-ali today.  Inline claims would make it easy
to use PVs, but I can't think of any good reason to use this (actually one
reason, see below).  The point of PVs is the P - lifetime beyond that of a
pod (actually not true, see below).  I presume that these anonymous inline
claims would expire when the pod using them expires, binding the lifetime
of the volume to the lifetime of the pod.  At that point why not just use
emptyDir.

Now I actually Do see reasons, but it has nothing to do with Persistence
and everything to do with disaggregation.  Consider that I can provision
GCE PD-SSD (block devices that approach SSD speeds).  if I want one of
those, I might very well use a PV but release the claim when I kill the
Pod.  an anon claim might be perfect for this.

This is a complicated sort of API though, so we should tread carefully and
make sure we understand exactly what people hope to achieve.

**Comment by bgrant0607** [comment]
What an "anonymous inline claim" sounds like to me is a claim template. But, yes, let's discuss in #260.

**Comment by bgrant0607** [comment]
Re. PD-SSD: That sounds more like a local volume: #7562. If nodes had SSD and we had an SSD media type, then EmptyDir could be used.

**Comment by thockin** [comment]
My point with that example was that there exist network-hosted storage
technologies that I might want to use for the lifetime of my pod but no
longer.  This takes the P out of PV, but the mechanism is the same.

We can tell people to make a claim, use that claim in your pod, and then
release the claim.  But even GCE has delete-on-delete - it's a useful
construct.  An anonymous claim is basically that.  It's not clear that this
is really what OP wants, but I'm not so against this as a type of volume,
at this point.

**Comment by maklemenz** [comment]
PetSets #18016 will cover the use cases I had in mind.

**Comment by thockin** [comment]
I'm re-opening this.  Now that we have dynamic provisioning and storage classes, this becomes more interesting from a performance point of view.  This would allow me to request a "platinum" volume that is auto-deleted at the end of my pod's lifetime.

**Comment by thockin** [comment]
Implemented!
