### ISSUE TITLE
scheduler_perf: define thresholds per test case and set up alerts for results

### ISSUE THREAD

**Issue by sanposhiho** [kubernetes/kubernetes#124774]
/kind feature
/sig scheduling

Discussion with sig-scalability: https://kubernetes.slack.com/archives/C09QZTRH7/p1715262959575039

## What

We have scheduler-perf, and it'd be great if we could have an alert-ish stuff based on the result.

Based on the discussion with sig-scalability, the easiest way is to change scheduler_perf so that it can fail if the results show degradation, and monitor/alert the failures via testgrid.

"_if the results show degradation_" > for this, we probably have to define reasonable thresholds per test case.

## Why

The current pain point is that [perf-dash](https://perf-dash.k8s.io/#/?jobname=scheduler-perf-benchmark&metriccategoryname=Sched[…]20applicable&result=not%20applicable&plugin=not%20applicable) visualizes it, but no one actually doesn't care much, and consequently we've overlooked degradation several times actually.

**Comment by sanposhiho** [comment]
@kubernetes/sig-scheduling-misc any feedback for the direction proposed above?

**Comment by alculquicondor** [comment]
+1 from me.

Also, the dashboard doesn't load for me (unless the link is wrong?)

**Comment by alculquicondor** [comment]
Nvm, it loads :)

**Comment by sanposhiho** [comment]
/assign

I just assigned it to me so that it remains on my todo list, but it might take some time for me to come back here because of other prioritized tickets. So, if anyone wants, feel free to take over (I can help reviews either way).

**Comment by utam0k** [comment]
Can I take over it?

**Comment by sanposhiho** [comment]
Yes,
/assign @utam0k

**Comment by sanposhiho** [comment]
ref https://github.com/kubernetes/test-infra/pull/32707

**Comment by sanposhiho** [comment]
cc @gabesaba

**Comment by macsko** [comment]
@sanposhiho @utam0k Do you have any progress on it? If not, I would like to add the throughput threshold setting to scheduler_perf and define the values per test case.

**Comment by sanposhiho** [comment]
No, I don't. Actually, I thought I unassigned myself from here, it's not on my list.

/unassign @sanposhiho

**Comment by utam0k** [comment]
No, I'd like to use this feature, but I didn't find time to do it. Please take over it from me.

**Comment by macsko** [comment]
I think, before setting the thresholds we need to make the test cases more stable. For example `SchedulingBasic` seems to be noisy (see [perf-dash](https://perf-dash.k8s.io/#/?jobname=scheduler-perf-benchmark&metriccategoryname=Scheduler&metricname=BenchmarkPerfResults&Metric=SchedulingThroughput&Name=SchedulingBasic%2F5000Nodes%2Fnamespace-2&extension_point=not%20applicable&plugin=not%20applicable&result=not%20applicable)), because we only measure 1000 pods there. We could add new test cases for each benchmark with more measure pods, that will be running longer. Then we could setup thresholds for these new cases when we obtain some historical results.

**Comment by sanposhiho** [comment]
I think it's done.

/close

Feel free to reopen if any further things to do. @macsko
