### ISSUE TITLE
Test flake in TestBroadcasterDropIfChannelFull

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#12493]
Seen extremely rarely.

```
--- FAIL: TestBroadcasterDropIfChannelFull-2 (0.00s)
	mux_test.go:134: Sending event 1
	mux_test.go:136: Sending event 2
	mux_test.go:157: Got (ADDED, &watch.myType{ID:"foo", Value:"hello world 1"})
	mux_test.go:162: Watcher 0 received second event (ADDED, &watch.myType{ID:"bar", Value:"hello world 2"}) even though it shouldn't have.
	mux_test.go:157: Got (ADDED, &watch.myType{ID:"foo", Value:"hello world 1"})
FAIL
```

**Comment by ihmccreery** [comment]
@brendandburns Did you fix this with https://github.com/kubernetes/kubernetes/pull/14064?

**Comment by brendandburns** [comment]
@ihmccreery I don't think so...  Have we seen repros recently?

**Comment by ihmccreery** [comment]
Assigning to @a-robinson as author of that test.

**Comment by a-robinson** [comment]
Wow, I think I wrote that test in a different lifetime...

Are there any flake logs you can point me to?

**Comment by a-robinson** [comment]
I've run this test 2000 times each on two different machines today (one mac, one linux) and haven't had a single flake. Given that there haven't been any failures mentioned since August 10, I'm going to mark this as obsolete, but I'll continue doing some more local runs and am happy to look into it if any more failures are observed.
