### ISSUE TITLE
endpointslicemirroring controller not create endpointslice when the endpoints are recreate

### ISSUE THREAD

**Issue by yangjunmyfm192085** [kubernetes/kubernetes#125354]
### What happened?

* create a service without selector, and manual create endpoints for this service
* endpointslicemirroring controller will create an endpointslice for this service.
* after endpoint slice created, and kube-controller-manager restart.
* during the kube-controller-manager restart, the endpoint was deleted and recreated
* after kube-controller-manager restart,  garbagecollector controller delete this endpointslice and endpointslice not recreate until endpoint/service update event or kube-controller-manager restart

### What did you expect to happen?

endpointslice will be recreated

### How can we reproduce it (as minimally and precisely as possible)?

* create a service without selector, and manual create endpoints for this service
* endpointslicemirroring controller will create an endpointslice for this service.
* after endpoint slice created, and kube-controller-manager restart.
* during the kube-controller-manager restart, the endpoint was deleted and recreated

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
v 1.30.0
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
kind 1.30.0
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by robscott** [comment]
Trying to understand this, mostly just restating what you've said above to make sure I'm getting it:

>during the kube-controller-manager restart, the endpoint was deleted and recreated
>after kube-controller-manager restart, garbagecollector controller delete this endpointslice and endpointslice not recreate until endpoint/service update event or kube-controller-manager restart

So an Endpoints resource is being deleted while kube-controller-manager is not running. The EndpointSlice mirroring controller [uses owner references](https://github.com/kubernetes/kubernetes/blob/0a6ad55da9773b3988d63003d6ff3c08bf0ff045/pkg/controller/endpointslicemirroring/utils.go#L73) to point to the Endpoints they're mirroring. When kube-controller-manager is restarted, the garbage collector will delete the mirrored EndpointSlice because it's owned by an Endpoints resource that was previously deleted. 

That deletion by garbage collection would then be [observed by the EndpointSlice mirroring controller](https://github.com/kubernetes/kubernetes/blob/0a6ad55da9773b3988d63003d6ff3c08bf0ff045/pkg/controller/endpointslicemirroring/endpointslicemirroring_controller.go#L496), but if the EndpointSliceTracker doesn't think it should have that resource, it will ignore the deletion and not reconcile, resulting in the mirrored EndpointSlice not being recreated until something updates the Service or Endpoints resource.
