### ISSUE TITLE
[Flaking Test] gce-master-scale-correctness (Unexpected CSI call)

### ISSUE THREAD

**Issue by Vyom-Yadav** [kubernetes/kubernetes#125539]
### Which jobs are flaking?

master-informing:
- gce-master-scale-correctness

### Which tests are flaking?

`Kubernetes e2e suite.[It] [sig-storage] CSI Mock volume storage capacity storage capacity unlimited`

### Since when has it been flaking?

- [6/16/2024, 10:31:43 PM](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-correctness/1802386080972935168)
- [6/14/2024, 10:31:23 PM](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-correctness/1801661219988312064)
- [6/10/2024, 10:31:33 PM](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-correctness/1800211709860777984)
- [2024-04-18 17:01:54 +0000 UTC
](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-correctness/1781005242142298112)

### Testgrid link

https://testgrid.k8s.io/sig-release-master-informing#gce-master-scale-correctness

### Reason for failure (if possible)

```
  I0616 17:45:57.514844 10886 csi_storage_capacity.go:196] Unexpected error: while waiting for all CSI calls: 
      <*fmt.wrapError | 0xc00f749e40>: 
      error waiting for expected CSI calls: Unexpected CSI call 0: expected CreateVolume (0), got DeleteVolume (0)
      {
          msg: "error waiting for expected CSI calls: Unexpected CSI call 0: expected CreateVolume (0), got DeleteVolume (0)",
          err: <*errors.errorString | 0xc000fc31c0>{
              s: "Unexpected CSI call 0: expected CreateVolume (0), got DeleteVolume (0)",
          },
      }
```

### Relevant SIG(s)

/sig storage
/sig scalability
cc @kubernetes/release-team-release-signal

**Comment by jsafrane** [comment]
When the test was working few days ago ([job result](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-correctness/1799486923799007232), [external-provisioner log](https://gcsweb.k8s.io/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-correctness/1799486923799007232/artifacts/_sig-storage_CSI_Mock_volume_storage_capacity/unlimited/storage_capacity/unlimited/)), a single CreateVolume call in the test had ~ 9KB line in the provisioner log.

Now ([job result](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-correctness/1802386080972935168), [external-provisioner log](https://gcsweb.k8s.io/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-correctness/1802386080972935168/artifacts/_sig-storage_CSI_Mock_volume_storage_capacity/unlimited/storage_capacity/unlimited/)), such a CreateVolume call has ~17KB, because there seem to be more topologies reported by nodes. I am not sure where we have any limit, it could be 16KB per log line hardcoded _somewhere_.

And why are the messages larger? The old CI job listed 161 `preferred` and `requisite` segments in CreateVolume call, the new failing ones list 303 of them. I have no explanation so far for such increase.

**Comment by jsafrane** [comment]
I can see the mock CSI driver logs are cut in the middle, search for `CreateVolume` and  GRPC request JSON on the next log line is cut in the middle:

https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-correctness/1802386080972935168/artifacts/_sig-storage_CSI_Mock_volume_storage_capacity/unlimited/storage_capacity/unlimited/csi-mockplugin-0-mock.log

**Comment by jsafrane** [comment]
This line seems to cut long lines: https://github.com/kubernetes-csi/csi-driver-host-path/blob/586ed79ac6ae87be0186bd4a4fe9589054d73199/pkg/hostpath/server.go#L108

Maybe it's `glog` (sic!), maybe `protosanitizer`.

**Comment by jsafrane** [comment]
glog seems to have 1500 character limit on log lines: https://github.com/golang/glog/blob/861d094757551d2f65d1003f0ec93bc92b254a5a/internal/logsink/logsink.go#L33

So... I would not say it's a blocker, the test was rock stable for months.

Someone needs to rewrite the CSI driver from glog to klog and check klog has a better limit.

@carlory not sure if you have time

**Comment by jsafrane** [comment]
/help

We need to rewrite [csi-driver-hostpath](https://github.com/kubernetes-csi/csi-driver-host-path) from glog to klog and check klog has a better limit. The flaky test should then start working.

**Comment by jsafrane** [comment]
/reopen
we still need to tag a new release + maybe update the image version in couple of places

**Comment by carlory** [comment]
https://github.com/kubernetes/kubernetes/pull/124842 will update test-manfiests

**Comment by Vyom-Yadav** [comment]
@carlory Does https://github.com/kubernetes/kubernetes/pull/124842 resolve this issue?

**Comment by carlory** [comment]
> /help
> 
> We need to rewrite [csi-driver-hostpath](https://github.com/kubernetes-csi/csi-driver-host-path) from [glog](https://github.com/golang/glog) to [klog](https://github.com/kubernetes/klog) and check klog has a better limit. The flaky test should then start working.

@Vyom-Yadav https://github.com/kubernetes/kubernetes/pull/124842 updated the test-manfiests, so the flaky should be fixed.

**Comment by pacoxu** [comment]
Not fail after 06-18.
- https://github.com/kubernetes/kubernetes/pull/124842 was merged 06-20

/close
