### ISSUE TITLE
Unnecessary non-Nil Check in ipallocator.go

### ISSUE THREAD

**Issue by darren** [kubernetes/kubernetes#125512]
https://github.com/kubernetes/kubernetes/blob/6ac60160c5729ade462b041b170ec8ac0f1eb3bc/pkg/registry/core/service/ipallocator/ipallocator.go#L83-L107

The err is already checked on line 84, so it will always be nil On line 107, the check is redundant

**Comment by mauri870** [comment]
That is indeed redundant. It seems like someone forgot to remove after a refactor but It was added this way in https://github.com/kubernetes/kubernetes/commit/b022475448b3589bf881e9d6d255501b9752d143.

**Comment by mauri870** [comment]
@darren Feel free to send a pull request by following https://kubernetes.io/docs/contribute/. Thanks.

**Comment by mauri870** [comment]
> @mauri870
> 
> Thanks! I am wondering whether it is necessary to check ip address returned by calling `Next()` or `Prev()` is `IsValid()`
> 
> As in https://github.com/golang/go/blob/a85b8810c49515c469d265c399febfa48442a983/src/net/netip/netip.go#L741-L755
> 
> But I don't find the overflowed cases yet.

Hmmm, in theory yes, since .Next() and .Prev() can return an empty netip.Addr. In practice, they probably never overflow.

Adding a check for .IsValid() for both Prev and Next would not hurt. I don't expect the path of !ip.IsValid() to be ever taken in these cases, but if they do then that is a bug and it should propagate an error.
