### ISSUE TITLE
Tracking issue: evaluating dependencies with non-CNCF CLAs

### ISSUE THREAD

**Issue by skitt** [kubernetes/kubernetes#125595]
### What would you like to be added?

Some of Kubernetes’ dependencies require contributors to sign CLAs, and some of them may not be acceptable to some of `k/k`’s contributors (or their employers). In the same way that we only allow dependencies with approved licenses, perhaps we should have a policy on acceptable CLAs.

### Why is this needed?

CLAs can limit some contributors’ ability to propose changes in dependencies that would be useful to Kubernetes.

This is less of a concern with CLAs than it is with licenses, since a CLA-requiring project with an acceptable license can always be forked if the worst comes to the worst.

For context, the specific dependency which led to this is gomock, which is now maintained by Uber (thanks!) but requires signing a CLA. One approach to pursue is to politely ask Uber if this can be improved (either by dropping the CLA requirement, or by amending the CLA); but this isn’t specifically about that dependency. See the thread starting at https://groups.google.com/g/kubernetes-sig-testing/c/nqSzLPQBl8o for details.

**Comment by dims** [comment]
@skitt we have had this issue for a long time now... for example cadvisor one of our very important dependencies needs a non-CNCF CLA ( https://github.com/google/cadvisor/pull/3541#issuecomment-2174263577 for example )

**Comment by skitt** [comment]
Right, but we don’t have a policy around it — should we?

(The Google CLA is OK, at least for my employer — https://github.com/google/cadvisor/pull/3078. But I’m more interested in a general stance before we dive into specifics, which we can’t do anyway.)

**Comment by dims** [comment]
@skitt every employer may likely make different choices with respect to the same CLA, so probably no common ground that i can see to write a policy that revolves around explicit terms in CLA or which companies are willing to sign it or not.

This probably needs to be booted up the stack to CNCF level as our licensing posture comes from what's allowed and not allowed from the CNCF charter and Governing Body deliberations etc.

For now, we muddle around with what we have, asking folks who can contribute to fixing something in a repo to do so and when that becomes a burden figure out alternatives to remove them. This is what we have been doing in general for a bunch of dependencies already for one reason or another.

See https://github.com/kubernetes/kubernetes/blob/master/hack/unwanted-dependencies.json where we drop things into that we track longer term to cleanup/get-rid-off. To get something into that json files, needs the consensus of the dependency approvers. So that's the current "policy" if you will.

**Comment by skitt** [comment]
@dims I agree 100%, this can’t be decided at “our” level, and rather than a list of principles, we’d end up with (if anything) a list of approved CLAs (in the same way there’s a list of approved licenses, which may also be at odds with member companies’ own lists of approved licenses).

I suppose the question for the community is whether it’s OK to muddle along, or whether it’s worth pushing this up the stack.

**Comment by skitt** [comment]
> See https://github.com/kubernetes/kubernetes/blob/master/hack/unwanted-dependencies.json where we drop things into that we track longer term to cleanup/get-rid-off. To get something into that json files, needs the consensus of the dependency approvers. So that's the current "policy" if you will.

That reminds me that I wondered about adding gomock to this as part of this PR... What do you think?

**Comment by BenTheElder** [comment]
> I suppose the question for the community is whether it’s OK to muddle along, or whether it’s worth pushing this up the stack.

I think it's a good question for the TOC, but currently I'm not sure it's worth blocking on.

It's not _ideal_, but we do need maintained dependencies, however the maintainers want to work on it, and as long as it's under the license policy we have the ability to fork later if it comes to it.

Even if a dependency has no CLA, we can't predict if it will accept contributions from our contributor base for any other reasons.

Forking or replacing dependencies is always on the table if we can't get necessary changes implemented otherwise, but doing so preemptively for every dependency we think may be difficult for some of our contributors to patch is expensive and probably unnecessary.

**Comment by BenTheElder** [comment]
Also: If every open source project took the attitude that only their own CLA was acceptable, then any non-CNCF projects couldn't use our libraries ...

That doesn't seem like a desirable place to be, so I'd hesitate to endorse a blanket ban on dependencies having non-CNCF CLAs.

If we have _specific_ dependencies where we're unable to achieve essential fixes, then we should probably deal with those.
