### ISSUE TITLE
Enable OpenSSF Scorecard to enhance security practices across the project

### ISSUE THREAD

**Issue by harshitasao** [kubernetes/kubernetes#126233]
Hi, I'm Harshita. I’m working with [CNCF and the Google Open Source Security Team for the GSoC 2024 term](https://github.com/cncf/mentoring/issues/1196). We are collaborating to enhance security practices across various CNCF projects. The goal is to improve security for all CNCF projects by both using OpenSSF Scorecards and implementing its security improvements.

The [Open Source Security Foundation](https://openssf.org/) (OpenSSF) [Scorecard](https://github.com/ossf/scorecard) is a tool designed to evaluate the security posture of open-source projects. This has the [Scorecard GitHub Action](https://github.com/ossf/scorecard-action), which automates the process by running security checks on the GitHub repository. By integrating this Action into the repository's workflow, developers can continuously monitor the project’s security posture. The Scorecard checks cover various security best practices and provide scores for multiple categories. Some checks include Code Reviews, Branch Protection, Signed Releases, etc.

The workflow runs on every change in the main branch. It publishes the Scorecard checks' results to the project's security dashboard and includes suggestions on how to solve any issues. This Action has already been adopted by 1800+ projects, with prominent users like [Tensorflow](https://github.com/tensorflow/tensorflow), [Angular](https://github.com/angular/angular), [sos.dev](http://sos.dev/), [deps.dev](http://deps.dev/), and many CNCF projects.

Once the Scorecard GitHub Action is set up and running, the results can be displayed as a badge in the repository's README file. This badge serves as a quick indicator of the project's security posture, helping users and contributors evaluate the project's security practices quickly.

**Why is this needed:**

The OpenSSF Scorecard improves open-source project's security by providing automated, transparent assessments of their security practices. It will help you identify vulnerabilities, adhere to best practices, and continuously enhance your security posture, increasing user trust and reducing the risk of security exploits.

I'll be the one to create the PR to add the scorecard GitHub action, and I will also work with you to remediate the identified vulnerabilities. I'll go through each [scorecard check](https://github.com/ossf/scorecard/blob/main/docs/checks.md) to see where the score has dropped and how it can be improved.

Would you be interested in a PR which adds this Action?

/cc @joycebrum @diogoteles08 @pnacht @nate-double-u

**Comment by dims** [comment]
cc @BenTheElder

**Comment by dims** [comment]
@harshitasao looks like the scans are being run somewhere as i see data:

- https://img.shields.io/ossf-scorecard/github.com/kubernetes/kubernetes?label=openssf%20scorecard&style=flat
- https://scorecard.dev/viewer/?uri=github.com/kubernetes/kubernetes

Some notes:
- we do not use github actions in this repo, So you would need to do a prow job if you want something to run periodically
- kinda questionable scan results... just because we don't do things the way the scanner wants to

<img width="881" alt="image" src="https://github.com/user-attachments/assets/a84ac46c-a5ff-4351-b5ca-5320baa4b5ad">
<img width="881" alt="image" src="https://github.com/user-attachments/assets/e2086379-d615-423d-8d40-86de2d1c2cc0">

Will you be working with the folks who wrote the scanner to incorporate how we do things?

**Comment by BenTheElder** [comment]
I've previously said -1, because the results are misleading and Kubernetes does not make a habit of picking / promoting winners in ecosystems like this.

OpenSSF is welcome to scan the repo from their own infrastructure, to be a bit blunt: I see basically no upside for Kubernetes to doing this ourselves other than promoting questionable results that make the repo sound more insecure than it is.

We haven't added any new badges in a long time and we have removed badges.
The security of the Kubernetes project is quite a bit more complex than this scorecard captures and I find the results highly misleading.

**Comment by BenTheElder** [comment]
> The OpenSSF Scorecard improves open-source project's security by providing automated, transparent assessments of their security practices.

This seems to be the only claimed benefit to the project, but it's pretty useless for us because our infrastructure is custom and this tool doesn't know how to scan it...?

We don't use github actions (we run our own CI to meet our demands that predates actions), the pinned dependencies result is wrong (... we pin AND vendor), branch protection is wrong (We have protection automatically enforced on all branches, I assume this only reads .github or something, we don't rely on that), release signing assumes artifacts are hosted inline on github (we host them ourselves currently), Packaging is wrong ... the packaging specs are in another repo.

This tool seems best suited to smaller, recently created github projects that use largely off the shelf github tools for everything and do everything in a single repo.

It would be costly and unhelpful for us to migrate everything to github's tools instead of what we're already using, and I don't think teaching this tool about our tools is worth the time versus investing in securing them directly.

**Comment by mrbobbytables** [comment]
I tend to agree with @BenTheElder on this. It's come up several times and it just doesn't mesh with how k/k is structured and was essentially factually inaccurate. If we can configure it to ignore everything that is not applicable, then I can see it possibility,but it'd be removing a good chunk of the items on the scorecard.

**Comment by jeefy** [comment]
> This seems to be the only claimed benefit to the project, but it's pretty useless for us because our infrastructure is custom and this tool doesn't know how to scan it...?

This was a pain to find (which is a whole other issue) but you can create a `scorecard.yml` file and annotate the Scorecard results -- see https://github.com/ossf/scorecard/blob/main/config/README.md -- Setting that config allows you to say things like "we don't use GHA so it's not applicable" and it'll generate a more "Correct" scorecard.

---

In terms of the value/merit of OSSF Scorecards, is there a benefit to the Kubernetes project itself? Not necessarily directly, but in terms of a broader ecosystem there is. @justaugustus is on the Scorecard Steering Committee so he'd probably be a better person to discuss/evangelize it, not me. ;)

**Comment by dims** [comment]
@harshitasao so let's start there as @jeefy recommended, setting up a scorecard.yml to reflect how we view things here.

**Comment by BenTheElder** [comment]
> [...] then I can see it possibility,but it'd be removing a good chunk of the items on the scorecard.

In which case it's not telling _us_ anything? And we're just promoting this project then, which we don't make a habit of doing.

I disagree with the premise of communicating security as a score based almost purely on publicly readable github configs / github hosted artifacts, both in terms of false positives and in terms of failing to consider anything not in-scope for the automated scans.

I'd see clarification on how this system helps the Kubernetes project before adopting it.

The Kubernetes project absolutely cares about security and we currently engage in Security Audits and SIG K8s Infra (and testing, and release and ...) have spent a LOT of time securing infrastructure.

TBQH @jeefy the CNCF's own scorecored has also had fairly ridiculous results, such as dinging the project for not using github discussion (we have tons of forums already, we really don't need another to manage) or for not having more metadata in the CNCF's landscape tool (....).

**Comment by liggitt** [comment]
see https://github.com/kubernetes/kubernetes/issues/113144 for previous proposal and declining to add this

**Comment by pacoxu** [comment]
After a quick go-through on the report, we may check the Vulnerabilities list.
- [ ] Warn: Project is vulnerable to: https://github.com/advisories/GHSA-rcjv-mgp8-qvmr / GO-2023-2113
- [ ] Warn: Project is vulnerable to: https://github.com/advisories/GHSA-c5q2-7r4c-mv6g / GO-2024-2631:  WIP PR #126236
- [ ]Warn: Project is vulnerable to: https://github.com/advisories/GHSA-8r3f-844c-mc37 / GO-2024-2611: only `hack/tools`

https://github.com/kubernetes/kubernetes/blob/24b873c15e87deba4472b2a0c6f251d4f82a561b/hack/tools/go.mod#L201-L202

**Comment by harshitasao** [comment]
Thank you all for your feedback. Closing this issue as the majority of people have declined this addition.
