### ISSUE TITLE
Include crio node e2e conformance test on all PRs

### ISSUE THREAD

**Issue by kannon92** [kubernetes/kubernetes#126390]
CRIO jobs for node conformance are used in the sig-release informing dashboard to inform release team of issues in the release.  See https://testgrid.k8s.io/sig-node-release-blocking#ci-crio-cgroupv2-node-e2e-conformance.

This test runs around 30 minutes and doesn't seem to be flaky.

I want to propose that https://testgrid.k8s.io/sig-node-cri-o#pr-crio-cgrpv2-gce-e2e be a job that runs on every PR so we can catch bugs on PRs rather than having to dig into what caused the issue after the fact.

**Comment by kannon92** [comment]
cc @haircommander @saschagrunert

**Comment by dims** [comment]
WHOA! `nodes=8` 

Is there a really small footprint way to run CRIO? 

Also this is `NodeConformance` not general Conformance! looking at https://github.com/kubernetes/test-infra/blob/bb364be14add1c7412d955c748eccc2468cee3db/config/jobs/kubernetes/sig-node/sig-node-presubmit.yaml#L1179-L1187

**Comment by dims** [comment]
Can you please links for `dig into what caused the issue after the fact`? given you are saying `doesn't seem to be flaky.` as well :)

**Comment by kannon92** [comment]
Yes, https://github.com/kubernetes/kubernetes/issues/126314 is the example that comes recently. We had a feature bump from alpha to beta. And it exposed a bug the crio/cadvisor integration. It was a bit difficult to find the rootcause but the bug would've been pretty easily caught if we ran the node conformance test suite for crio.

I usually try to run presubmits from node when I review but I don't run the conformance tests that often.

**Comment by BenTheElder** [comment]
/sig testing
(Has historically maintained the state of presubmit)
/sig k8s-infra
(We work with on the resourcing angle)

So far I see a single bug / breakage referenced.

postsubmits / periodics are not useful signal if they never catch anything and fail. Always on presubmit is reserved for things that break so frequently we'll wind up underwater with concurrent uncaught bugs, along with cheap quality + nuisance checks (linters / spell check).

We don't add things to presubmit without evidence that we're unable to keep up with release blocking bugs without them, it's not sustainable to put the entire matrix in always on presubmit.

Note that these actually run on every push to every PR and tend to be quite expensive.

Also agree "node conformance" as I understand it is not something SIG arch ever endorsed and it seems unlikely that it should contain alpha features that not a single vendor supports.

Can we please provide more evidence regarding the necessity of adding to always run on every push?

**Comment by aojea** [comment]
I think the first step is making these jobs periodic and informing -> blocking -> (evaluate if presubmits are needed)

**Comment by BenTheElder** [comment]
If we do need this, we should probably be looking at what other coverage we can trade off, but first we should analyze the requirement. One alpha feature bug is not sufficient case for an always on presubmit.

As it currently stands we've been pushing back against the excessive creep of presubmit time and cost.

**Comment by kannon92** [comment]
My general issue is that sig-node tests are very under represented on presubmits. As a hopeful reviewer, I try to look at the code and decide what kind of test I should trigger in sig-node to help catch these bugs on PRs. As trying to bisect the PR can be quite diffiuclt. It is getting better because we have been trying to get the release signal boards green so we know if we see a breakage that it is serious.

But I was thinking since we have containerd node conformance tests (the only e2e_node related job) in as a blocking presubmit, I was thinking it would be beneficial to have a corresponding one for CRIO.

Maybe I will close this and I will keep it in the back of mind if we get more examples. I am not aware of many more where we had a bug in containerd/crio. I guess the best we can do is monitor these in the periodics and tag the author once we narrowed down who caused it.

**Comment by BenTheElder** [comment]
> My general issue is that sig-node tests are very under represented on presubmits. 

Most SIGs do not have their own presubmit jobs, instead we cover many sigs at once in:
- unit
- integration
- cluster e2es

SIG Node is actually currently the only SIG to have an always-on presubmit job dedicated entirely to testing that SIG's code only. All other sigs are depending on shared jobs*

(*We also always run some jobs both in IPv6 and IPv4 mode still which you might argue is indirectly sig-network having dedicated ipv6 presubmits because there have been so many bugs with this across sigs but primarily networking, but that's something we should be revisiting)

> As a hopeful reviewer, I try to look at the code and decide what kind of test I should trigger in sig-node to help catch these bugs on PRs. As trying to bisect the PR can be quite difficult. It is getting better because we have been trying to get the release signal boards green so we know if we see a breakage that it is serious.

https://testgrid.k8s.io/sig-node-release-blocking#ci-crio-cgroupv2-node-e2e-conformance

produces a diff of https://github.com/kubernetes/kubernetes/compare/fc03f3e74...77c3859ae which only has 10 commits aside from the merge robot?

You can manually run additional jobs as a reviewer on relevant PRs, but forcing them on _every_ push is a blunt approach we try to avoid.

The release signal boards have additional monitoring from release-ci-signal, but you should also enable testgrid alerts for when the jobs fail.

> But I was thinking since we have containerd node conformance tests (the only e2e_node related job) in as a blocking presubmit, I was thinking it would be beneficial to have a corresponding one for CRIO.

Yes, it's less "we don't want cri-o in presubmit"  .... I could not care less which pluggable solutions are in presubmit as long as they're a reliable enough reference implementation to test Kubernetes components, the goal is always to test the code in this repo ... It's more "we do not want a proliferation of presubmits without a strong requirement for them".

We're doing something wrong if we need to test all pluggable options on every push.

**Comment by BenTheElder** [comment]
> (*We also always run some jobs both in IPv6 and IPv4 mode still which you might argue is indirectly sig-network having dedicated ipv6 presubmits because there have been so many bugs with this across sigs but primarily networking, but that's something we should be revisiting)

thread: https://kubernetes.slack.com/archives/C09QZ4DQB/p1722010946813999

also xref: #126202

**Comment by kannon92** [comment]
From the slack thread, I see why we want to avoid adding these as presubmits. 

I opened up https://github.com/kubernetes/test-infra/pull/33117 to promote these jobs to release-blocking.
