### ISSUE TITLE
[Flaking Test] gci-gce-ingress (LB should handle updates to ExternalTrafficPolicy field)

### ISSUE THREAD

**Issue by Vyom-Yadav** [kubernetes/kubernetes#126400]
### Which jobs are flaking?

master-blocking:
- gci-gce-ingress

### Which tests are flaking?

`Kubernetes e2e suite.[It] [sig-network] LoadBalancers ExternalTrafficPolicy: Local [Feature:LoadBalancer] [Slow] should handle updates to ExternalTrafficPolicy field`

### Since when has it been flaking?

[7/26/2024, 5:30:31 PM ci-kubernetes-e2e-gce-cos-k8sbeta-slow](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-cos-k8sbeta-slow/1816805796189573120)
[7/25/2024, 8:03:30 PM ci-kubernetes-e2e-gci-gce-ingress](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-ingress/1816481909119651840)
[7/21/2024, 6:46:44 PM ci-kubernetes-soak-gci-gce-beta](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-soak-gci-gce-beta/1815013037229215744)
[7/21/2024, 5:59:44 PM ci-kubernetes-e2e-gce-cos-k8sbeta-slow](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-cos-k8sbeta-slow/1815001209203855360)
[7/20/2024, 4:47:40 AM ci-kubernetes-e2e-gce-cos-k8sstable1-slow](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-cos-k8sstable1-slow/1814439490991689728)

![Screenshot from 2024-07-27 01-59-56](https://github.com/user-attachments/assets/804faffc-7d01-402b-b802-5874e3c336cc)

### Testgrid link

https://testgrid.k8s.io/sig-release-master-blocking#gci-gce-ingress

### Reason for failure (if possible)

```
[FAILED] failed to update Service "external-local-update": Internal error occurred: failed to allocate requested HealthCheck NodePort 30202: provided port is already allocated
In [It] at: k8s.io/kubernetes/test/e2e/network/loadbalancer.go:1616 @ 07/21/24 12:41:29.957
```

There were additional failures detected after the initial failure. These are visible in the timeline

### Relevant SIG(s)

/sig network

**Comment by wendy-ha18** [comment]
cc @kubernetes/release-team-release-signal

**Comment by aojea** [comment]
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-ingress/1816481909119651840

> Kubernetes e2e suite: [It] [sig-network] LoadBalancers ExternalTrafficPolicy: Local [Feature:LoadBalancer] [Slow] should handle updates to ExternalTrafficPolicy field expand_less	1m36s
> { failed [FAILED] failed to update Service "external-local-update": Internal error occurred: failed to allocate requested HealthCheck NodePort 32394: provided port is already allocated
> In [It] at: k8s.io/kubernetes/test/e2e/network/loadbalancer.go:1360 @ 07/25/24 15:03:29.394

https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-soak-gci-gce-beta/1815013037229215744

> { failed [FAILED] failed to update Service "external-local-update": Internal error occurred: failed to allocate requested HealthCheck NodePort 31045: provided port is already allocated
> In [It] at: k8s.io/kubernetes/test/e2e/network/loadbalancer.go:1616 @ 07/21/24 14:43:16.1

This will be fixed by https://github.com/kubernetes/kubernetes/pull/125597

since the author is not responding and is impacting the CI I'm going to take over

**Comment by aojea** [comment]
ups, I think I jumped too fast on conclusions and @danwinship clarified it here https://github.com/kubernetes/kubernetes/pull/126403#issuecomment-2254144110

**Comment by shaneutt** [comment]
We talked about this on the call today, this is ready for work:

/triage accepted

And we would be happy to have anyone who wants to contribute jump in and help:

/help

Just let us know if you have questions or need support with it!

**Comment by aojea** [comment]
@Vyom-Yadav this is a known issue for a long time with low rate of failure and the fix is not straight forward, this has to wait for 1.32 ... not impacting the release at all since is a testing defect, the feature work as expected

**Comment by sshiv5768** [comment]
I would like to work collaborate for this issue, @Vyom-Yadav @shaneutt.

**Comment by Anurag252** [comment]
@aojea I see this issue referenced in [126403](https://github.com/kubernetes/kubernetes/pull/126403)  and also read your comment that the PR currently  just fixes 125466 and not this issue. If this issue is not being worked in that PR then I am happy to take a look at this.

I wanted to confirm before `/assign`  to avoid rework :)

**Comment by aojea** [comment]
@Anurag252 I don't have time now to work on this, so appreciate if someone can take on it.

See the discussion with @danwinship here https://github.com/kubernetes/kubernetes/pull/126403#issuecomment-2254144110 , his comments are very valuable.

I think first we need to do some due diligence and identify all the tests that are susceptible of racing because of nodePort conflicts (Dan already listed some of them but we may want to tag them or something_

Second, we should iterate on the idea of being able to have some conflict detection per Dan suggestion https://github.com/kubernetes/kubernetes/pull/126403#issuecomment-2254527489

**Comment by Anurag252** [comment]
> @Anurag252 I don't have time now to work on this, so appreciate if someone can take on it.
> 
> See the discussion with @danwinship here [#126403 (comment)](https://github.com/kubernetes/kubernetes/pull/126403#issuecomment-2254144110) , his comments are very valuable.
> 
> I think first we need to do some due diligence and identify all the tests that are susceptible of racing because of nodePort conflicts (Dan already listed some of them but we may want to tag them or something_
> 
> Second, we should iterate on the idea of being able to have some conflict detection per Dan suggestion [#126403 (comment)](https://github.com/kubernetes/kubernetes/pull/126403#issuecomment-2254527489)

Okay makes sense. I will start with identification of tests that fall in this category and will assign this issue to me.

**Comment by Anurag252** [comment]
I went through all the tests from both `loadbalancer.go` and `services.go` and found only these occurences where this case may arise. (both tests have already been pointed out by @danwinship.

## `loadbalancer.go`
- [setting ExternalTrafficPolicy back to Local](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/network/loadbalancer.go#L1358)
- [setting ExternalTrafficPolicy back to Local](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/network/loadbalancer.go#L1315) 

## service.go
- [should release NodePorts on delete](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/network/service.go#L1721) 
- [should release NodePorts on delete](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/network/service.go#L1727) 

I also liked the 2nd suggestion in the [comment](https://github.com/kubernetes/kubernetes/pull/126403#issuecomment-2254144110) about having a `e2eservice.ReserveNodePort()`. More specifically either
1. Have `ReserveNodePort` and `UnReserveNodePort` like so
```
e2eservice.ReserveNodePort(nodeport int, callback func)
e2eservice.UnReserveNodePort(nodeport int,callback func)
``` 
and create a new `Service` in `ReserveNodePort` with specified nodeport in order to block it from future allocations, like so:
```
func ReserveNodePort(nodeport int, callback func()) error {
	var err error
	
	// try to create the service with nodeport so that it is not allocated to any other service
	go func() {
		err = retry.OnError(retry.DefaultRetry, errAllocated, func() error {
			
			svc, err := jig.CreateTCPService(ctx, func(service *v1.Service) {
				service.Spec.Ports = []v1.ServicePort{
					{
						Nodeport = nodeport
					},
				}
			})
			return err
		})
		// de-allocate nodeport
		callback()

		// In case some other service raced and got the nodeport, then fail or retry whole test with new set of Nodeport
	}()
	return err
}
// In case some other service raced and got the nodeport, then fail or retry whole test with new set of Nodeport
}

.....
ReserveNodePort(oldport, func() {
	// deallocate nodeport
	svc, err := jig.UpdateService(ctx, func(svc *v1.Service) {
		svc.Spec.ExternalTrafficPolicy = v1.ServiceExternalTrafficPolicyCluster
	})
})
```
reference to dummy services will need to be maintained so that they can be deleted in `UnReserveNodePort()`.

2. Or we could just maintain a list of reserved nodes globally and on every call to 
`j.Client.CoreV1().Services(j.Namespace).Create() ` and `j.Client.CoreV1().Services(j.Namespace).Update()` we could delete the service if it was assigned a nodeport from the reserved nodeport and perform corresponding operation again.

Both approaches appear a bit hacky to me and in approach 1 there are still chances of test being flaky (when some other service gets the nodeport between retries). 

Please let me know your thoughts. 
cc @aojea

**Comment by aojea** [comment]
> Or we could just maintain a list of reserved nodes globally

we only have 4 tests that can conflict, it seems the global list of allocated nodeports seems the simplest ... with a big comment saying new tests should not use THAT functionality

This logic should be added to the `jig` structure and can only be used through those methods on that type

**Comment by Anurag252** [comment]
Thanks for your reply. Okay makes sense, then I will post a PR with functionality
-  to `Reserve` and `Unreserve` nodeports. and
-  In case any a service is created/updated and assigned a `reserved`  nodeport, it will be deleted and creation/updation will be retried n times  till it gets a nodeport that is not reserved.

>  with a big comment saying new tests should not use THAT functionality

Do we specifically want to avoid using `Reserve` and `Unreserve` nodeports functions in new tests ? My assumption was that these functions could be useful even in new tests, especially in scenarios where a nodeport is de-allocated and reachability is tested. In such cases, the expected failure of reachability can only be guaranteed if the nodeport isn't allocated to another service.

**Comment by aojea** [comment]
> I don't think you want to do it this way (calling into a method that creates the service). Particularly given that in one case you're reserving a NodePort an in another case a HealthCheckNodePort.

I was trying to avoid more consumption of these methods, your approach sounds simpler though

**Comment by Anurag252** [comment]
Thanks for pointing out the article. Considering only static ports for these two tests would greatly simplify the implementation. I am also considering 
- to combine `e2eservice.GetUnusedStaticNodePort()` and `e2eservice.ReserveStaticNodePort(port)` in order to avoid race between two calls
- moving looping part inside `GetUnusedStaticNodePort()` so that a call to this would return a free port

**Comment by aojea** [comment]
@danwinship I just spotted this today during the review

https://github.com/kubernetes/kubernetes/blob/a0ad420018d69601136223f91b818a73747a7ce3/test/e2e/framework/service/jig.go#L478-L497

did you know we have such method?
```
grep -r ChangeServiceNodePort test/
test/e2e/framework/service/jig.go:// ChangeServiceNodePort changes node ports of the given service.
test/e2e/framework/service/jig.go:func (j *TestJig) ChangeServiceNodePort(ctx context.Context, initial int) (*v1.Service, error) {
test/e2e/network/loadbalancer.go:               tcpService, err = tcpJig.ChangeServiceNodePort(ctx, tcpNodePort)
test/e2e/network/loadbalancer.go:               udpService, err = udpJig.ChangeServiceNodePort(ctx, udpNodePort)
```

**Comment by drewhagen** [comment]
@Anurag252 @aojea Thanks a ton for helping fix this!
The release cycle for 1.32 starts today. Since this is still open, I will carry it over to the latest milestone.

/milestone 1.32

**Comment by drewhagen** [comment]
@Anurag252 @aojea I see and appreciate that review is actively ongoing on the PR #127153.

The first release cut (1.32.0-alpha.1) is due in less than a week from today on Oct 1st 2024. While this issue is in progress, that would or should block and delay release cuts, particularly this first alpha version? Please advise - thank you!

**Comment by danwinship** [comment]
The problem is entirely with the e2e test, not with k8s itself, so there's no reason to block/delay the release

**Comment by knabben** [comment]
Hello @danwinship @aojea 
The code freeze is starting 02:00 UTC Friday November 8th 2024 (about 2 weeks from now), and while there is still time, we want to ensure that each PR has a chance to be merged on time.
As the issue is tagged for 1.32, is it still planned for this release?
Thank you!


Can this be closed, it seems the flake is not happening anymore.

**Comment by knabben** [comment]
After https://github.com/kubernetes/kubernetes/pull/125222 is merged the tests are not flaking anymore

/close

**Comment by Anurag252** [comment]
I believe this issue should be addressed in associated PR even though the flake does not appear. The reason being apparent possibility of race occurring in port allocation.
