### ISSUE TITLE
[Sidecar Containers] Ability to start sidecar and main containers in parallel

### ISSUE THREAD

**Issue by maxweisel** [kubernetes/kubernetes#126471]
### What would you like to be added?

I'm testing out the new sidecar beta and it's working really well! However, there's one small issue. The workloads we spin up are startup latency sensitive and it seems there's no way to tell kubernetes to not wait for the sidecar containers to start before starting the main containers.

### Why is this needed?

We have the following two containers:
1. Game server (main container)
2. Metrics collector (sidecar container)

Previously we ran both of these as regular containers, but the metrics collector will run forever, so we had to build some custom orchestration in order to have the pod terminate when the game server container completes. It works but it's not as clean as I'd like and it's harder for devops to discover pods where the game server has completed gracefully but the metrics collector has not.

I'm trying to switch the metrics collector to a sidecar so that way the pod lifecycle is only based on the game server container and this piece works great in my initial tests. When the game server container completes, the pod moves to a Completed state even though the metrics collector is still running and our system cleans the pod up.

The main issue is I'm running into is that kubernetes waits until the metrics collector image is pulled and started before it starts the game server container which results in significant additional startup latency for us before a player can connect. I'd love to be able to set a flag that allows both to start in parallel to work around this.

**Comment by toVersus** [comment]
> The workloads we spin up are startup latency sensitive and it seems there's no way to tell kubernetes to not wait for the sidecar containers to start before starting the main containers.

So, you want to rely solely on the guarantee of the shutdown order for Sidecar Containers. Since this would involve a significant change to the design of the Sidecar Containers, I'm not sure whether it can be supported. At least, it seems necessary to create a separate KEP from [KEP-753](https://kep.k8s.io/753) to discuss the API design and other aspects.

> The main issue is I'm running into is that kubernetes waits until the metrics collector image is pulled and started before it starts the game server container which results in significant additional startup latency for us before a player can connect.

Even if Sidecar containers and Regular containers are started in parallel, kubelet will, by default, download container images sequentially. So, it seems that the kubelet's parallel image pull is enabled on your setup. Comparing the sizes of the Game Server image and the metrics collector image, it looks like the Game Server image is much larger, right? Does downloading the metrics collector image really have such a big effect on the overall pod startup time?

If the container image size is large, downloading the container image will still occur even when containers are started in parallel. It might be worth considering options like preloading container images or lazy pulling.

**Comment by SergeyKanzhelev** [comment]
If we will want to implement this, it will be a whole new feature. We intentionally decided not to implement sidecars that starts AFTER the main container. Some things that mitigate this situation are can be image preloading or features like image streaming that eliminate the wait for the image pull.

I suggest the next steps here is to document this as the best practice: https://github.com/kubernetes/website/issues/47823

We can then close this issue with the suggestion to start one of the following new KEPs:

1. KEP to allow downloading images of all containers in a Pod in-parallel
2. KEP to allow new type of sidecar containers
3. Any other ideas with the different level of craziness that can come to mind to make this situation better

**Comment by sftim** [comment]
(I'm agreeing and clarifying).
We don't really have _any_ documentation on good practices for solution design. Would be great to have some, but: if we don't, that's not a bug in the Kubernetes code, or motivation by itself for new features.

**Comment by SergeyKanzhelev** [comment]
/close

we will handle this as a documentation issue

**Comment by sftim** [comment]
Just a detail
/reopen
