### ISSUE TITLE
Limit the Nodes to connect to the Cluster

### ISSUE THREAD

**Issue by kgrvamsi** [kubernetes/kubernetes#12653]
Hello,

I would like to know how can i limit the Minions to connect to the API server.Is this something at an etcd level i have to do inorder not to add more values on to the Minions key or i need to add some sort of arg when i start the API server.

On the other end would like to know about these args

Kube-Api Server

```
--max-requests-inflight=400: The maximum number of requests in flight at a given time.  When the server exceeds this, it rejects requests.  Zero for no limit.
```

For this is this something like you are regulating on the Requests which happen on the API server(Some sort of parameter for API server Performance?)

Kubelet 

```
--register-node=true: Register the node with the apiserver (defaults to true if --api-server is set)
```

For this if my assumption is not wrong then if i set this arg then when the kublet starts it wont register automatically which the user needs to register manually.

```
--max-pods=40:Number of Pods that can run on this Kubelet.
```

Can this Limitation can be done from the API server Level?

```
--global-housekeeping-interval=1m0s: Interval between global housekeepings
```

Do we have any documentation for the Housekeeping activities which happen on the Minions?

Thanks,
Vamsi

**Comment by apeeyush** [comment]
One usecase for this could be if I have set up a cluster on GCE/AWS and want to limit the max. number of instances even if the load is high.

Would love to work on this one if it has not been implemented yet! :)

**Comment by kgrvamsi** [comment]
@apeeyush  Limit to the Max is good to have when u predict the workload on to the cluster but handling the situation basedupon the load is something which comes at a dynamic cluster model.but still it can be useful to have

**Comment by brendandburns** [comment]
@apeeyush I don't think we currently have a limit in the apiserver.  Seems like a reasonable thing to add.

You can prevent nodes with invalid keys from joining, but you can't set a hard limit.

**Comment by kgrvamsi** [comment]
@brendandburns  can you please help me out with other information which i'm looking out for apart from the Max Limit?

**Comment by roberthbailey** [comment]
If we are going to start applying policies to allow / disallow nodes to join a cluster, I'd like us to move in the direction of supporting dynamic clustering (as described in [clustering.md](https://github.com/kubernetes/kubernetes/blob/master/docs/design/clustering.md#dynamic-clustering)). Even if we don't have the apiserver signing certificates yet, we could start implementing the "admin manually approving the kubelet [join] requests" part of the flow. Then when we add the signing capability to the apiserver the node admission control logic will already be in place.

**Comment by kgrvamsi** [comment]
@roberthbailey  I see the document for the Dynamic Clustering and is this bootstrap API part of the API server now or is it a proposal?If it is already there then there are not API functions mentioned about this here http://kubernetes.io/third_party/swagger-ui/ and If not then this bootstrap api will be a separate component to run on every API Server or it will be globally hosted somehwere.

**Comment by bgrant0607** [comment]
cc @derekwaynecarr

**Comment by roberthbailey** [comment]
The bootstrap API is currently just a proposal. The intent would be to host a global one (for easy getting started) but make it easy to set a different bootstrap endpoint for folks who want to run their own (GKE, on prem, etc).

**Comment by derekwaynecarr** [comment]
Right now, ```ResourceQuota``` lets you control Hard limits for the number of an api resource (pod, replication controller, etc.) per namespace.  

In the past, we discussed having a cluster wide quota document that would let you set Soft/Hard limits for number of API resources across all namespaces to help administrators manage the cluster.

The idea was that for many resource types, you would just want Soft limits to be able to get notifications for when the number of Pods, Replication Controllers, etc. so you can manage the cluster and plan.

In addition, you could set a Hard limit on resources like Node, or PersistentVolumes to control how many of these entities you are willing to grow your cluster since that may be tied to actual cost.

If someone wants to look at introducing a ```ClusterQuota``` to support this concept, it should all be do-able with our admission control hooks (to enforce hard limits on Nodes and PersistentVolumes) and a simple background controller that ran reports on current usage.

This is not a near-term priority for me, but I do think administrators will need this type of behavior as usage of Kubernetes grows.

**Comment by bgrant0607** [comment]
This is obsolete.
