### ISSUE TITLE
Cannot set kubelet config `resolvConf` with drop-in config files

### ISSUE THREAD

**Issue by ciffelia** [kubernetes/kubernetes#126630]
### What happened?

I created a kubernetes cluster with kubeadm and created a drop-in directory for kubelet configuration at `/etc/kubernetes/kubelet.conf.d`.

I created a config file within the directory to change the value of `resolvConf`. After restarting kubelet, the value of `resolvConf` stayed same.

### What did you expect to happen?

The value of `resolvConf` is updated.

### How can we reproduce it (as minimally and precisely as possible)?

```sh
# Create custom resolv.conf
echo 'nameserver 8.8.8.8' | sudo tee /etc/resolv.kubelet.conf

# Create drop-in config directory
sudo mkdir /etc/kubernetes/kubelet.conf.d
sudo chmod 700 /etc/kubernetes/kubelet.conf.d

# Create drop-in config file
cat <<EOF | sudo tee /etc/kubernetes/kubelet.conf.d/99-resolv-conf.conf
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
resolvConf: /etc/resolv.kubelet.conf
EOF
sudo chmod 600 /etc/kubernetes/kubelet.conf.d/99-resolv-conf.conf

# Add --config-dir flag
echo 'KUBELET_EXTRA_ARGS=--config-dir=/etc/kubernetes/kubelet.conf.d' | sudo tee /etc/default/kubelet

sudo systemctl daemon-reload
sudo systemctl restart kubelet

# Check if the value of resolvConf is changed.
kubectl get --raw "/api/v1/nodes/<node name>/proxy/configz" | jq
```

### Anything else we need to know?

I think this issue is particular to the drop-in config and `resolvConf` option because:

- I can configure `resolvConf` by editing `/var/lib/kubelet/config.yaml`
- I can update another option like `streamingConnectionIdleTimeout` with drop-in config.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.30.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.3
```

</details>

### Cloud provider

<details>
No cloud provider
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
$ uname -a
Linux vm-1aefb131-31 6.1.0-21-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.90-1 (2024-05-03) x86_64 GNU/Linux
```

</details>

### Install tools

<details>
kubeadm
</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by aojea** [comment]
Is not a duplicate of https://github.com/kubernetes/kubernetes/issues/79421

**Comment by kannon92** [comment]
> Is not a duplicate of #79421 ?

No. That issue is about the naming for resolvConf is different from the name of the field. https://github.com/kubernetes/kubernetes/issues/79421#issuecomment-2248608624

In this case, the user is finding that when they use resolvConf with drop-in configs, the values are not reflected.

**Comment by kannon92** [comment]
@ciffelia does this by chance work if you restart kubelet with the drop in config change?

**Comment by ciffelia** [comment]
> @ciffelia does this by chance work if you restart kubelet with the drop in config change?

No, I restarted kubelet several times but it doesn't work.

**Comment by HirazawaUi** [comment]
I can reproduce this issue on the master branch.

/triage accepted
/assign

**Comment by HirazawaUi** [comment]
> No. That issue is about the naming for resolvConf is different from the name of the field. [#79421 (comment)](https://github.com/kubernetes/kubernetes/issues/79421#issuecomment-2248608624)

I believe they are the same issue (because the subsequent discussion in #79421 deviated from its original topic). At least from https://github.com/kubernetes/kubernetes/issues/79421#issuecomment-2198462046 onwards , the issue aligns with what's being discussed here.

If we use the `resolverConfig` field in the drop-in config file, it will be correctly configured in the kubelet's configuration.

However, in the main kubelet config file, only the `resolvConf` field will be correctly configured into the kubelet's configuration.

**Comment by HirazawaUi** [comment]
I did some digging. Initially, due to compatibility issues, we set the corresponding command line for `ResolverConfig` to `--resolv-conf`.
ref:  https://github.com/kubernetes/kubernetes/pull/11955#discussion_r35731738

We set the json key for the `ResolverConfig` field in the `KubeletConfiguration` to `resolvConf`.

Should we fix it in v1 version of `KubeletConfiguration`?

@thockin @SergeyKanzhelev

**Comment by HirazawaUi** [comment]
Before fixing it, or if we don't plan to fix it, specifically handling the resolvConf field in https://github.com/kubernetes/kubernetes/blob/0f095cf0ba5156a972b446a5f65c963fe2a7919c/cmd/kubelet/app/server.go#L306-L312  seems like a reasonable option.

**Comment by kannon92** [comment]
Fixing there sounds good to me as an immediate step.

Maybe we should also add the correct label to the v1 api but keep the original one and deprecate it. We can’t drop resolvConf though so the best we could do is duplicate the field and eventually deprecate (but not remove) the older config name.

**Comment by kannon92** [comment]
But I’d like to hear what @SergeyKanzhelev and @thockin think of this

**Comment by HirazawaUi** [comment]
ping @thockin

**Comment by SergeyKanzhelev** [comment]
/cc @sohankunkerkar

@sohankunkerkar can you please take a look?

**Comment by liggitt** [comment]
> In this case, the user is finding that when they use resolvConf with drop-in configs, the values are not reflected.

The current discussion and report in https://github.com/kubernetes/kubernetes/issues/79421#issuecomment-2198462046 and following is the same as this issue, and is due to a bug in the [mergeKubeletConfigurations](https://github.com/kubernetes/kubernetes/blob/master/cmd/kubelet/app/server.go#L317) function which is specific to use of `--config-dir`

**Comment by liggitt** [comment]
> Did we really mean for the field and the json names not to match? That seems like it might have been an accident.

Maybe not, but I'm glad the mismatch exposed the merging bug.

**Comment by liggitt** [comment]
Opened https://github.com/kubernetes/kubernetes/pull/127421 with a fix

**Comment by HirazawaUi** [comment]
Thank you very much for guiding the solving approach in the right direction. However, after completing this fix, do we still need to address the mismatched fields in the KubeletConfiguration?

**Comment by liggitt** [comment]
> However, after completing this fix, do we still need to address the mismatched fields in the KubeletConfiguration?

No. That does not affect functionality at all.

**Comment by brandond** [comment]
@liggitt does that fix the fact that I cannot:
1. Generate a KubeletConfiguration struct in code
2. Serialize it to yaml and write it into the dropin directory
3. Have all the fields (specifically the resolv-conf field) honored by the kubelet

Unless that's fixed I would argue that this IS affecting functionality and needs to be fixed.

**Comment by liggitt** [comment]
The name of the struct field has no bearing on the json/yaml serialization when writing the v1beta1 config file. When you generate a struct in code and serialize it to yaml (using `sigs.k8s.io/yaml` which writes fields using the json tags), the field is written as `resolvConf` (correctly).

https://github.com/kubernetes/kubernetes/pull/127421 will fix handling of those config files so that they correctly override the value. See the unit test added in that PR.

**Comment by brandond** [comment]
Yeah, the whole problem was that the dropins were being unmarhalled as the internal type instead of the versioned type which broke round tripping. I see that your PR unmarshals as `v1beta1.KubeletConfiguration` and then converts to `config.KubeletConfiguration` which should fix the issue. Thanks!
