### ISSUE TITLE
Explicit version specification in go directive fouling corporate Snyk scans

### ISSUE THREAD

**Issue by dagraff-cisco** [kubernetes/kubernetes#126636]
The go directive specified here is fouling enterprise Snyk scans on dependent projects.

https://github.com/kubernetes/kubernetes/blob/60c4c2b2521fb454ce69dee737e3eb91a25e0535/staging/src/k8s.io/api/go.mod#L5

The issue https://github.com/kubernetes/api/issues/74 was opened against the 0.30.0 version of this library in April and I have noted two comments on this.

I had suggested executing `go mod edit -go=1.22 -toolchain=go1.22.0` to remedy.

Thank you in advance.

**Comment by dims** [comment]
@dagraff-cisco do you have an issue open on the `enterprise Snyk scans` tool vendor?

**Comment by dagraff-cisco** [comment]
I have a request number but am unclear on whether I can share that.

**Comment by dims** [comment]
@dagraff-cisco please see discussion here: https://github.com/thockin/kubernetes/commit/6a6bfcdcab985033c41efbd1b3429a0ebf463e76#r136416927

We are not likely to go back and revisit that. It's better to work with your tool vendor as they have to fix it anyway for other projects, newer golang etc.

**Comment by dagraff-cisco** [comment]
I did just find this statement:

> A module’s go line must declare a version greater than or equal to the go version declared by each of the modules listed in require statements. A workspace’s go line must declare a version greater than or equal to the go version declared by each of the modules listed in use statements.

Would that imply that the `go` directive be explicitly using a version of X.Y.Z greater than or equal to the versions of it's constituent libraries?

**Comment by BenTheElder** [comment]
Also FWIW to the tooling vendor: Even the `toolchain` statement may be overridden by `GOTOOLCHAIN` when actually building (which Kubernetes uses currently). IMHO scanning the version of the go **toolchain** in source code is just inaccurate (including inferring it from the go _language_ version IE the module go statement), it should only scan compiled binaries for the go runtime version `$(go version $binary)`.

`GOTOOLCHAIN` environment variable aside, non-root modules's toolchain statements will be ignored anyhow. `go` and `toolchain` statements in the module at best have a weak correlation to the go toolchain / stdlib actually used at build time and the only reliable way to detect that is scanning the compiled binaries.

This will probably false-flag on other projects as well.

**Comment by dagraff-cisco** [comment]
I believe this has uncovered an issue with the vendor scans which we will work with them on.

There seems to be some ... shall we say consternation ... with regard to the value of the go directive. I've heard a couple of opinions on this and the general theme I'm getting is that individual libraries should not necessarily specify X.Y.Z as that may artificially force a particular behavior.

What I have gotten from a colleague that brought this to my attention was that we're getting a myriad number of dependencies flagged that are not actually part of our dependency set.

The confusion has arisen, for my team at least, is that the version specifier in the `go` directive seemed a bit willy nilly and they were thrown off by the setting of `1.22.0` in the directive.

**Comment by BenTheElder** [comment]
> There seems to be some ... shall we say consternation ... with regard to the value of the go directive. I've heard a couple of opinions on this and the general theme I'm getting is that individual libraries should not necessarily specify X.Y.Z as that may artificially force a particular behavior.

My argument is that regardless of what should be set here for any other reasons, snyk has no(?) business reading the `go` directive.

The `go` directive controls the language version and language behavior and only indirectly hints at the compiler/toolchain/stdlib version. 

I doubt snyk is claiming the language spec has a vulnerability and you need to set the `go` statement to mitigate it?
Even if it did, you handle that by setting the `go` version in the root module of the project importing client-go, not by setting it in client-go.

Otherwise the `go` version is seemingly being read as a proxy for the go toolchain version that will be used to compile the project, which cannot be reliably scanned by parsing these values, regardless of what we set them to, and snyk should stop incorrectly attempting to determine the compiler/stdlib version from these values. 

It can reliably get the compiler version from compiled binaries though since go embeds that metadata.

---

Also worth noting:
```console
[bentheelder@bentheelder-macbookpro1:~/mod-test·2024-08-12T12:22:15-0700]
$ go mod init test
go: creating new go.mod: module test

[bentheelder@bentheelder-macbookpro1:~/mod-test·2024-08-12T12:22:21-0700]
$ cat ./go.mod
module test

go 1.22.5
```

A default `go mod init` will set a specific go version in the `go` statement, so snyk is going to see a lot of these.

**Comment by dagraff-cisco** [comment]
Understood - I will close this issue as it appears to have been settled some months prior and may not be relevant to the behavior noted.
