### ISSUE TITLE
CVE-2024-7646: Ingress-nginx Annotation Validation Bypass

### ISSUE THREAD

**Issue by cji** [kubernetes/kubernetes#126744]
CVSS Rating: [CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H](https://www.first.org/cvss/calculator/3.1#CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H)

A security issue was discovered in ingress-nginx where an actor with permission to create Ingress objects (in the `networking.k8s.io` or `extensions` API group) can bypass annotation validation to inject arbitrary commands and obtain the credentials of the ingress-nginx controller. In the default configuration, that credential has access to all secrets in the cluster.

This issue has been rated **High** (8.8) [CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H](https://www.first.org/cvss/calculator/3.1#CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H) and assigned **CVE-2024-7646**.

### Am I vulnerable?

This bug affects ingress-nginx. If you do not have ingress-nginx installed on your cluster, you are not affected. You can check this by running `kubectl get po -A` and looking for `ingress-nginx-controller`.

Multi-tenant environments where non-admin users have permissions to create Ingress objects are most affected by this issue.

### Affected Versions

ingress-nginx controller < v1.11.2

### How do I mitigate this vulnerability?

This issue can be mitigated by upgrading to the fixed version. 

### Fixed Versions

ingress-nginx controller v1.11.2 - fixed by https://github.com/kubernetes/ingress-nginx/pull/11719 and https://github.com/kubernetes/ingress-nginx/pull/11721

### Detection

Review your Kubernetes audit logs for Ingress objects created with annotations (e.g. `nginx.ingress.kubernetes.io/auth-tls-verify-client`) that contain carriage returns (`\r`).

If you find evidence that this vulnerability has been exploited, please contact [security@kubernetes.io](mailto:security@kubernetes.io)

### Additional Details

See the GitHub issue for more details: 
https://github.com/kubernetes/kubernetes/issues/126744 

#### Acknowledgements

This vulnerability was reported by André Storfjord Kristiansen @dev-bio. 

The issue was fixed and coordinated by the fix team:
André Storfjord Kristiansen @dev-bio
Jintao Zhang @tao12345666333
Marco Ebert @Gacko

/triage accepted
/lifecycle frozen
/area security
/kind bug
/committee security-response

**Comment by xrstf** [comment]
All communication regarding this issue mentions 1.11.2 as the _only_ version that fixes it.

But the original fix was also backported to 1.10.x and released in 1.10.4, so shouldn't 1.10.4 also be listed as a fixed version?

**Comment by cji** [comment]
@xrstf Thank you, I've confirmed with the maintainers that 1.10.4 has also been patched. I'll update the description.

**Comment by danielhoherd** [comment]
Version 1.9 was the last version to support PSP, but it is no longer supported, and expectedly I have not seen any discussion about it getting a new version to address this CVE in version 1.9. That means that anybody who is stuck on an older version by virtue of needing to work through PSPs migrations in their cluster is going to be vulnerable until they complete their PSP work. I understand that both nginx-ingress and k8s are end-of-support in that scenario, and in an ideal world nobody would be running end-of-support software, but the reality is that some people are stuck in that situation for reasons beyond their control.

Would it be possible to get a version of 1.9 that has the fix for this CVE so folks who are stuck on PSP work can mitigate the risk posed by this CVE?

**Comment by BenTheElder** [comment]
> [...] and in an ideal world nobody would be running end-of-support software, but the reality is that some people are stuck in that situation for reasons beyond their control.

PSP was deprecated in v1.21 and removed in v1.25[^1], it is not available in any supported Kubernetes release by  (1.28 is currently the oldest supported [^2], 1.25 is two years past end of support)

It's not realistic for maintainers to continue to support software for free indefinitely, and these are _long_ out of support, and the PSP deprecation was announced ~3.5 years ago.

There are some commercial vendors offering longer support for their Kubernetes distros (not here), but ingress-nginx runs pretty much entirely on overburdened volunteers.

In any case, the best place to ask would be https://github.com/kubernetes/ingress-nginx/issues, not here. This issue is pretty much only filed here for the purposes of the CVE feed.



[^1]: https://kubernetes.io/docs/concepts/security/pod-security-policy/
[^2]: https://kubernetes.io/releases/
