### ISSUE TITLE
High-Availability Examples Page Returns 404 Page Not Found

### ISSUE THREAD

**Issue by kgrvamsi** [kubernetes/kubernetes#12681]
Error to Reproduce

Got to http://kubernetes.io/v1.0/docs/admin/high-availability.html

Click on the here button in the Vagrant Section

Link: http://kubernetes.io/v1.0/examples/high-availability/

**Comment by brendandburns** [comment]
Correct link is here:

https://github.com/kubernetes/kubernetes/tree/master/examples/high-availability

Will get it fixed on kubernetes.io.

Thanks for the report.

**Comment by RichieEscarez** [comment]
Today the example under master is the same as what works for v1 (they match) but I think the fix for this is to redirect the broken link to the gh-pages.../v1.0 copy of the example during the pre-publishing file processing so that the doc and example remain at v1.0 (ie. whats under master can/will eventually change).

@krousey can you please help update the release processing scripts so that this link (and others like it - ones that point to a "HEAD" version of an example) instead points to the version specific copy in the gh-pages branch: https://github.com/kubernetes/kubernetes/tree/gh-pages/v1.0/examples/....

The url for this particular example is:
https://github.com/kubernetes/kubernetes/tree/gh-pages/v1.0/examples/high-availability

I think the long-term solution, would be to create/write up a formal "HA example" (to replace the "Vagrant Up" section) and discuss/walkthrough how to use each one of these files.

**Comment by krousey** [comment]
@RichieEscarez I have a PR out which links this back to the release branch, not the gh-pages branch. Is that ok? For this particular example, the link is https://releases.k8s.io/v1.0.1/examples/high-availability

There really shouldn't be any difference.

**Comment by RichieEscarez** [comment]
@krousey yes that works, i actually like this approach better because the version is more prominently displayed in the drop-down widget (versus in the file path location in gh-pages). Thanks!

I just tested and see that the PR went through so the link works and now goes to https://releases.k8s.io/v1.0.1/examples/high-availability .....closing.
