### ISSUE TITLE
Why Kubernetes Event's field InvolvedObject is called "regarding" in doc?

### ISSUE THREAD

**Issue by KeyOfSpectator** [kubernetes/kubernetes#126845]
### What happened?

I'm just curious, Why Kubernetes Event's field InvolvedObject is called "regarding" in doc?

Kubernetes Event's field "InvolvedObject" in code and structure. https://github.com/kubernetes/kubernetes/blob/6ca629d46b1267a1b8b03416edcaa8832ffc62a8/pkg/apis/core/types.go#L5687

In doc is called "regarding".
https://v1-27.docs.kubernetes.io/docs/reference/kubernetes-api/cluster-resources/event-v1/
and
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.31/#event-v1-events-k8s-io

### What did you expect to happen?

Is there a unique word in Event's InvokeObject field?

### How can we reproduce it (as minimally and precisely as possible)?

Just want to know the reason.

### Kubernetes version

maybe all version, I checked in <=1.30.

### Cloud provider

Alicloud Contaienr Service.

**Comment by BenTheElder** [comment]
> Why Kubernetes Event's field InvolvedObject is called "regarding" in doc?

I'm not sure if there's some additional request but ... it is called "regarding" because of the english meaning of the word "regarding"?

It means "with respect to" or "concerning". So the `regarding` field refers to the object the event is for.

From the docs:
> **regarding contains the object this Event is about**. In most cases it's an Object reporting controller implements, e.g. ReplicaSetController implements ReplicaSets and this event is emitted because it acts on some changes in a ReplicaSet object.

**Comment by KeyOfSpectator** [comment]
> > Why Kubernetes Event's field InvolvedObject is called "regarding" in doc?
> 
> I'm not sure if there's some additional request but ... it is called "regarding" because of the english meaning of the word "regarding"?
> 
> It means "with respect to" or "concerning". So the `regarding` field refers to the object the event is for.
> 
> From the docs:
> 
> > **regarding contains the object this Event is about**. In most cases it's an Object reporting controller implements, e.g. ReplicaSetController implements ReplicaSets and this event is emitted because it acts on some changes in a ReplicaSet object.

Ok, can I think this: 
1. These two fields (1. invokeObject in actual code field, 2. regarding in doc) refer to the same attribute field. 
2. This is just a matter of naming and translating in doc according to English semantics.

**Comment by logicalhan** [comment]
/triage accepted

I think it's probably poorly constructed phrasing.

**Comment by mengjiao-liu** [comment]
I took a look at the K8s source code, and I think the `regarding` field in the documentation corresponds to file https://github.com/kubernetes/kubernetes/blob/9edcffcde5595e8a5b1a35f88c421764e575afce/staging/src/k8s.io/api/events/v1/types.go#L69 , not the following file you listed in the description.
https://github.com/kubernetes/kubernetes/blob/6ca629d46b1267a1b8b03416edcaa8832ffc62a8/pkg/apis/core/types.go#L5687  

I think the event API is stored in two different places due to historical reasons, which leads to user confusion.
You can see more details for the [New Event API GA Graduation KEP](https://github.com/kubernetes/enhancements/blob/master/keps/sig-instrumentation/383-new-event-api-ga-graduation/README.md). @KeyOfSpectator

**Comment by KeyOfSpectator** [comment]
ok, thx, this is just a QA issue. 
I think i already get the answer. 
Very thx...
