### ISSUE TITLE
DRA: CEL cost limits

### ISSUE THREAD

**Issue by pohly** [kubernetes/kubernetes#126819]
### What would you like to be added?

The cost and (presumably) the size of CEL expressions in the API must have limits.

### Why is this needed?

Avoid intentional or accidental DOS of the kube-scheduler when it needs to evaluate CEL expressions.

/sig node
/priority important-longterm

This is a blocker for beta of structured parameters.

**Comment by pohly** [comment]
A first step would be to evaluate and log the cost of expressions. Then we need to pick some sufficiently complex expressions and try to come up with limits.

**Comment by cici37** [comment]
Regarding with the cost of cel, I saw DRA is building cel env through base env(https://github.com/kubernetes/kubernetes/blob/f6c88abb2a01d381cd161f7954ecc4b577021cb3/staging/src/k8s.io/dynamic-resource-allocation/cel/compile.go#L211) which will auto get the cost limit per expression working. FYI the cost limit we put: https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/apis/cel/config.go
I do suggest to turn on the strictCost for DRA(Pass `true` instead of `false` here: https://github.com/kubernetes/kubernetes/blob/f6c88abb2a01d381cd161f7954ecc4b577021cb3/staging/src/k8s.io/dynamic-resource-allocation/cel/compile.go#L211C2-L211C105

Also, we do have a overall budget put for the expression per resources as well: https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/apis/cel/config.go#L24-L26 
I would suggest DRA to adopt this as well to limit the overall cost run per resource

**Comment by pohly** [comment]
https://github.com/kubernetes/kubernetes/blob/beb696c2c9467dbc44cbaf35c5a4a3daf0321db3/staging/src/k8s.io/apiserver/pkg/apis/cel/config.go#L21 explains that the cost corresponds to a certain runtime duration. How was that measured?

**Comment by Nishant5454** [comment]
hmm

**Comment by pohly** [comment]
/assign

Implemented as part of a larger WIP PR for 1.32.

**Comment by pohly** [comment]
/close

Merged via https://github.com/kubernetes/kubernetes/pull/128101.
