### ISSUE TITLE
Kube-proxy conntrack logic does not consider Service traffic topology

### ISSUE THREAD

**Issue by aojea** [kubernetes/kubernetes#126934]
_Originally posted by @adrianmoisey in https://github.com/kubernetes/kubernetes/issues/126130#issuecomment-2301842312_
            

An UDP Service with internalTrafficPolicy set to Local leaves stale conntrack entries after the endpoint is deleted.

This happens because the Service is deployed as a daemonset with one endpoint per node.

When the endpoint is deleted, the endpoint conntrack entry is deleted but , when the new endpoint is added it should delete the Service ClusterIP entry because the Service effectively went from 0 endpoints in the node (InternalTrafficPolicy Local) to 1 endpoint.

However, the kube-proxy logic to detect stale entries does not have into consideration any of the traffic distribution features for Services, making wrong assumptions because of this and leaving stale entries

https://github.com/kubernetes/kubernetes/blob/619b0059cf8c224461cb411fda090c8ff25d9f71/pkg/proxy/endpointschangetracker.go#L290-L350

Kudos to @adrianmoisey for the thorough investigation and reproducer

/sig network
/kind bug
/assign @aojea

**Comment by adrianmoisey** [comment]
Thanks for the assist @aojea!

**Comment by aojea** [comment]
I can not repro with the e2e test in this release or previous https://github.com/kubernetes/kubernetes/pull/126935

however, I can do it with kind in 1.29 version locally .... checking more into this

cc: @danwinship

**Comment by aojea** [comment]
Talked with @danwinship offline, he explained that in recent versions a DROP rule was added, so that rule can cause that the conntrack entry is not created.

We need to merge the information from both the Services and EndpointSlices cache to be able to include the `CategorizeEndpoint()`  logic to figure out the actual Endpoints and Services that are programmed in the dataplane , so we can detect the entries that may be stale.

Since he is more familiar with the codebase of the endpointslice and service caches, I'm reassigning this to him

/assign @danwinship

**Comment by aojea** [comment]
@danwinship since @aroradaman is working on https://github.com/kubernetes/kubernetes/issues/126130 this cycle that will allow us to no longer depend on the cache logic for conntrack deletion, I wonder if we just can have a backportable change that fixes the issue in the supported minor versions and avoid any refactor

**Comment by danwinship** [comment]
OK, so the behavior that we _want_ here is

- When a service goes from 0 endpoints to non-0 endpoints on this node, delete all blackhole conntrack entries for the service's IPs.

The behavior we currently have is:

- When a service goes from 0 endpoints to non-0 endpoints **~on this node~**, delete all **~blackhole~** conntrack entries for the service's IPs.

Using netlink doesn't help with the endpoint-counting part, but if the netlink filter is able to distinguish blackhole entries from non-blackhole entries, then we could change the rule to be:

- Any time a service's endpoints change, delete all blackhole conntrack entries for the service's IPs.

or slightly more efficiently:

- When a service goes from 0 endpoints to non-0 endpoints, _or_ any time the service's endpoints change if the service has Local traffic policy or uses topology, then delete all blackhole conntrack entries for the service's IPs.

But long term, fixing the endpoint counting is probably still the right fix.

> I wonder if we just can have a backportable change that fixes the issue in the supported minor versions and avoid any refactor

Are you suggesting backporting the netlink conntrack code? That seems like a pretty big backport...

**Comment by aojea** [comment]
> Are you suggesting backporting the netlink conntrack code? That seems like a pretty big backport...

no, sorry, I;m saying that if we have the reconciler in  place in this release, the conntrack delete logic is different, we look at the existing services, we look at the existing conntrack entries and we delete the ones that does not match ... we no longer depend on the heuristics of if service had ... and now has ... and this happened ...

But we still depend on that for the old releases, I'm not in favor of backporting the reconciler not even the netlink thing, is very risky, what I was trying to understand is if we can get a patch that fixes the problem without having to refactor too mach so we can backport it

**Comment by danwinship** [comment]
Oh, you mean, if we get the reconciler in 1.32 but _don't_ have the topology fix in 1.32, can we later do the topology fix in a way that could be backported to 1.32?

If we are changing conntrack cleanup to be primarily based on reconciliation, then we have to totally change how the proxiers interact with the conntrack cleanup code anyway, so we should fix the topology bug at the same time. If we don't fix it then, then I don't think the eventual future fix is likely to be any more backport-able with the reconciler than it would be with the existing code. (The problem here is not with the "if service had ... and now has ... and this happened" part, it's that we're looking at the wrong data when we decide what to do. As soon as we fix it to pass the right data to the conntrack code, the problem fixes itself.)

**Comment by danwinship** [comment]
I think, at the point where we currently call

    endpointUpdateResult := proxier.endpointsMap.Update(proxier.endpointsChanges)

we need to change things so that the `CategorizeEndpoints` step happens then too, and is reflected in `endpointsMap` (or whatever `endpointsMap` becomes).

We need to do that _here_ because if we don't, then that implies we will essentially have to create a duplicate copy of `endpointsMap` with slightly different data later on for use by the conntrack reconciler, and we don't want to do that because the endpoint state is potentially enormous.

Two other things feeding into the refactoring:
- #112604 points out that we need to be able to roll back the effect of `proxier.endpointsMap.Update()` above if the sync fails. Right now `EndpointsTracker` keeps track of the currently-committed endpoint state, and any pending un-synced changes, but we need to make it keep track of 3 states (committed, currently-attempting-to-commit, and pending) instead. That also implies a more complicated `endpointsMap` representation, because we don't want to have to keep the old `endpointsMap` around to be able to roll back to it.
- #126013 effectively _did_ add a duplicate copy of `endpointsMap` to use for figuring out nftables partial syncs, because the existing tracker/map APIs don't expose diffs, only the final state. We need to add tracker/map APIs to be able to determine the diff between the "committed" and "currently-attempting-to-commit" states.

Anyway, I'm thinking about how to make this all work nicely...

**Comment by aroradaman** [comment]
Should we close this one, https://github.com/kubernetes/kubernetes/pull/127318 handles this as well.

**Comment by aojea** [comment]
> Should we close this one?, #127318 handles this as well.

Thanks for finding this
/Close

**Comment by danwinship** [comment]
Ah... I was thinking [before](https://github.com/kubernetes/kubernetes/issues/126934#issuecomment-2334233202) that the reconciler wouldn't fix this, because it _wouldn't_ fix it if we had kept the same logic as the old cleanup code. But using the netlink API lets us do a better job of cleaning things correctly than we did before, and Daman took advantage of that, so this bug is fixed too.

> When the endpoint is deleted, the endpoint conntrack entry is deleted but , when the new endpoint is added it should delete the Service ClusterIP entry because the Service effectively went from 0 endpoints in the node (InternalTrafficPolicy Local) to 1 endpoint.
> 
> However, the kube-proxy logic to detect stale entries does not have into consideration any of the traffic distribution features for Services, making wrong assumptions because of this and leaving stale entries

The new reconciler just correctly deletes all of the conntrack entries for the deleted endpoint at the point that the endpoint gets deleted, so it doesn't need an extra hack for "the number of endpoints went from 0 to 1", so it doesn't need to care about the distinction between globally-relevant and locally-relevant endpoints.
