### ISSUE TITLE
KubeUI not loading up

### ISSUE THREAD

**Issue by arun-gupta** [kubernetes/kubernetes#12692]
Started a Kubernetes 1.0.1 cluster using VirtualBox 4.3.30. Everything started correctly as:

```
Validate output:
NAME                 STATUS    MESSAGE              ERROR
controller-manager   Healthy   ok                   nil
scheduler            Healthy   ok                   nil
etcd-0               Healthy   {"health": "true"}   nil
Cluster validation succeeded
Done, listing cluster services:

Kubernetes master is running at https://10.245.1.2
KubeDNS is running at https://10.245.1.2/api/v1/proxy/namespaces/kube-system/services/kube-dns
KubeUI is running at https://10.245.1.2/api/v1/proxy/namespaces/kube-system/services/kube-ui
```

Accessing KubeUI at https://10.245.1.2/api/v1/proxy/namespaces/kube-system/services/kube-ui prompts for username/password and entered vagrant/vagrant. But the browser keeps waiting for a response and does not show any response.

**Comment by bgrant0607** [comment]
cc @kubernetes/kube-ui-maintainers

**Comment by jtblin** [comment]
Same issue, after a long long time, I can see errors in the Javascript console:

> GET https://10.245.1.2/api/v1/proxy/namespaces/kube-system/services/kube-ui/assets/js/app.js net::ERR_CONTENT_LENGTH_MISMATCH 10.245.1.2/:55
> GET https://10.245.1.2/api/v1/proxy/namespaces/kube-system/services/kube-ui/assets/js/base.js net::ERR_CONTENT_LENGTH_MISMATCH 10.245.1.2/:54
> GET https://10.245.1.2/api/v1/proxy/namespaces/kube-system/services/kube-ui/assets/css/app.css net::ERR_CONTENT_LENGTH_MISMATCH 10.245.1.2/:11

I also got some Angular module injection error but didn't copy, reloaded and not getting those anymore but the ones above.

**Comment by arun-gupta** [comment]
@kubernetes/kube-ui-maintainers any updates on this?

**Comment by bgrant0607** [comment]
FWIW, the Kube UI is now in a separate repo: https://github.com/kubernetes/kube-ui

Also, please re-post your question to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes). 

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases. 

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to similar questions, and also familiarize yourself with:
  * [the user guide](http://kubernetes.io/v1.0/)
  * [the troubleshooting guide](http://kubernetes.io/v1.0/docs/troubleshooting.html)

Again, thanks for using Kubernetes.

The Kubernetes Team
