### ISSUE TITLE
Kubelet hostname healtz fails

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#12726]
When looking at Kubelet healthz through proxy on master I'm getting:
```
[-]hostname failed: Kubelet hostname "e2e-test-gmarek-minion-93s0" does not match the hostname expected by the master "10.240.170.229"
```

cc @fgrzadkowski @dchen1107 @davidopp

**Comment by gmarek** [comment]
cc @yujuhong

**Comment by yujuhong** [comment]
kubelet expects `req.Host` to be the hostname, while master uses IP in the request instead. /cc people who knows more about proxy: @brendandburns @lavalamp

**Comment by lavalamp** [comment]
Master's expectation looks wrong.

**Comment by swagiaal** [comment]
The idea of that health check is to ensure that the master schedules work to the name expected by the kubelet. Otherwise sometimes you end up in a situation where the master is scheduling work for IP and the kubelet is looking for work for 'hostname -f'; the node status says 'Ready' but no pods get started on that node. User's must use --hostname_override to correct the situation.

It has been a while since I have looked at that code so things may have changed, but in this case is the master scheduling using the hostname "10.240.170.229" ? If so then pods will not start on that node. If not then the health check needs a better way of getting the hostname as the master knows it.

**Comment by lavalamp** [comment]
@gmarek I don't think this is related to the proxy, I think your master has an incorrect node configuration, as @swagiaal says.

**Comment by gmarek** [comment]
@lavalamp - I checked this on @fgrzadkowski and @jszczepkowski clusters as well, with the same result. All of us were running default GCE configuration.

**Comment by lavalamp** [comment]
That's very weird, I reproduce, too. But it has nothing to do with the proxy, rather it's the requested host (????!?):

```
$ curl -k https://10.240.219.172:10250/healthz
[+]ping ok
[+]docker ok
[-]hostname failed: Kubelet hostname "kubernetes-minion-tk18" does not match the hostname expected by the master "10.240.219.172"
[+]syncloop ok
healthz check failed
$ curl -k https://localhost:10250/healthz
ok
```

So kubelet gives different answers depending on whether you refer to it as "localhost" or by its IP address.

**Comment by lavalamp** [comment]
If kubelet is doing the healthz check about the host in the HTTP request, then that's wrong. To be useful, it should be making an assertion about the Node object that represents it in the system.

**Comment by yujuhong** [comment]
> If kubelet is doing the healthz check about the host in the HTTP request, then that's wrong. To be useful, it should be making an assertion about the Node object that represents it in the system.

To give more context, the change was introduced in #4497
I think @swagiaal was describing a situation where kubelet and master have discrepancy on what the node is. E.g., kubelet thinks it's node HOSTNAME, while master thinks the node is IP. In this case, kubelet wouldn't know which Node object to check.

@swagiaal, if I understand correctly, this should not happen now because
   - kubelet would not update the node status of the incorrect node, so the node would eventually become unavailable
   - kubelet can register itself now

**Comment by swagiaal** [comment]
> If kubelet is doing the healthz check about the host in the HTTP request, then that's wrong. To be useful, it should be making an assertion about the Node object that represents it in the system.

Yeah the original patch in #4497 sent the host name presumed by master along with the request but we though the hostname from the header sufficed as we could not come up with a scenario where the two differ.  That can be changed back if needed.

It looks like the localhost bypass was added later in #5120

@gmarek in your cluster if you disable the health check do pods actually start on the node ?

**Comment by swagiaal** [comment]
> @swagiaal, if I understand correctly, this should not happen now because
> 
>     kubelet would not update the node status of the incorrect node, so the node would eventually become unavailable

@yujuhong hmm... do you mean the master would not be able to reach the node if it has the incorrect name ? The hostname is correct it is just different from what the node uses. Say for example the host uses "example.com" and the node node knows itself as "93.184.216.34". The health check will pass because the node is reachable, but pods don't start because work no work is scheduled for "93.184.216.34"

> kubelet can register itself now

Yeah I think that is a safe path.

**Comment by yujuhong** [comment]
> @yujuhong hmm... do you mean the master would not be able to reach the node if it has the incorrect name ? The hostname is correct it is just different from what the node uses. Say for example the host uses "example.com" and the node node knows itself as "93.184.216.34". The health check will pass because the node is reachable, but pods don't start because work no work is scheduled for "93.184.216.34"

@swagiaal, kubelet updates node status now, and if the node status isn't updated for sometime, node controller would deem the node unhealthy.
E.g., if the node knows itself as "93.184.216.34", it'd try to update the status of node "93.184.216.34". The status of node "example.com" would not be updated by anyone, and would eventually become unhealthy.

**Comment by lavalamp** [comment]
It fails through the proxy because master's proxy code uses IP address (not hostname) to reach the node. Master is actually doing the right thing there.

Master doesn't directly health check kubelets any more (monit does) so that's why this isn't currently breaking anything. I'm guessing the localhost exception was added because that's how monit health checks; but that's evidence that the original assumption that one could use the HTTP request's host for this was faulty, and the check should be completely removed or done some other way.

**Comment by swagiaal** [comment]
@yujuhong got it!
@lavalamp I see. The check is no longer correct then and given what @yujuhong explained the check is unnecessary :)
I'll open a PR to remove it.

**Comment by yujuhong** [comment]
@swagiaal, thanks!
