### ISSUE TITLE
Page cannot load file for the API Object For Pod

### ISSUE THREAD

**Issue by kgrvamsi** [kubernetes/kubernetes#12728]
Url

    https://htmlpreview.github.io/?https://github.com/GoogleCloudPlatform/kubernetes/v1.0.1/docs/api-reference/definitions.html#_v1_pod

Documentation Page

    http://kubernetes.io/v1.0/docs/user-guide/pods.html

Section API Object

**Comment by RichieEscarez** [comment]
Hi @nikhiljindal, I found that you added the script to process these API links so that it opens the HTML preview - #11569, can you please help update the script so that it points to the kubernertes/kubernetes GitHub repo?

Note, for these API files, i see that they dont show in the target folder until tag v1.0.2 (they are not in v1.0.1 as the previous url indicates): 
https://github.com/kubernetes/kubernetes/tree/v1.0.2/docs/api-reference

**Comment by RichieEscarez** [comment]
Duplicate of #11772

**Comment by nikhiljindal** [comment]
This will be fixed by https://github.com/kubernetes/kubernetes/issues/13149.
Closing this as duplicate.
