### ISSUE TITLE
Add FieldSelector to MutatingWebhookConfiguration spec

### ISSUE THREAD

**Issue by lengrongfu** [kubernetes/kubernetes#127434]
### What would you like to be added?

Current, MutatingWebhookConfiguration can filter whether the current pod enters the webhook stage by configuring the LabelSelector resource, but it is hoped that FieldSelector can be added for filtering.

### Why is this needed?

There are many fields in the current pod. For example, we want to filter whether we need to enter the webhook by using the `.spec.schedulerName` field.

**Comment by googs1025** [comment]
Here is a more colloquial English translation of your message:

"Webhooks are applications (deployments) meant for users to implement. I believe that this kind of 'filtering logic' should be handled within the webhook application itself.

Moreover, this change involving API modifications requires careful consideration to determine if it's truly necessary. (The API change process is also quite complex.)

Furthermore, since webhooks can inherently have business logic (processes that users can implement themselves), this business logic is something that should and must be included within the webhook. Filtering out pods that are not relevant directly at admission or validating them quickly (fast return) in the business logic, while letting pods of interest proceed through the webhook process, is crucial.

Additionally, if there are concerns about webhooks affecting other pods, the failurePolicy: 'Ignore' option can be used. Business logic should not be 'configured' - configuration should be simplified while business logic can be complex. This is my understanding."

**Comment by lengrongfu** [comment]
Thanks for your explanation.

The core issue now is to filter out the Pods that the business cares about during admission. Currently, ObjectSelector or NamespaceSelector fields are provided to filter Pods, but filtering cannot be done by fields in Spec.

**Comment by googs1025** [comment]
As I was saying, I reckon this is the kind of business logic that should be handled within the webhook. Why spec? Why not status? Also, making it configurable like this, with different spec fields for different resource objects, will only complicate the setup. These kinds of operations are best left to be implemented internally within the webhook to handle the related business logic, rather than being part of the "configuration."

**Comment by BenTheElder** [comment]
cc @jpbetz to triage

**Comment by jpbetz** [comment]
A [`matchCondition`](https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#matching-requests-matchconditions) can be added to a webhook to configure the webhook to only be called if a CEL expression evaluates to true.  Would a `matchCondition` with CEL expression along the lines of `object.spec.schedulerName == "my-scheduler"` be sufficient here?

**Comment by lengrongfu** [comment]
Thank you very much, this is the function I need.
