### ISSUE TITLE
encrypt secrets when in etcd.

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#12742]
We should limit access to secrets when in etcd.

Initially discussed in #11937.

Although we discourage it, people seem to want to build their own clusters where etcd is used by both Apiserver and by other components, to store configuration.  Secrets want to have Kubernetes access controls on them, and not to be widely readable.  Other types of configuration wants to be widely readable. 

We could do this in a couple of ways:
1. use etcd ACLs to limit access to the etcd keys that hold secrets.
1. encrypt some or all of the secret data when stored.

@liggitt @pmorie 
thoughts?

**Comment by liggitt** [comment]
my first instinct would be to use etcd ACLs to subdivide the etcd instance, since indiscriminate write access to etcd would be just as much of a compromise (write yourself a privileged pod scheduled to every node that reads node credentials and asks the master API for all secrets... done)

**Comment by erictune** [comment]
related issue is using https://github.com/hashicorp/vault to store secrets https://github.com/kubernetes/kubernetes/issues/10439

At first glance, changing our storage seems easier than integrating with something that has a non-Kuberntes API.

**Comment by liggitt** [comment]
that said, I also like the idea of encrypting secrets at rest in etcd (actually, I'd like the ability to do that generically on any object, since we also store things like OAuth access tokens in etcd)

**Comment by erictune** [comment]
We might actually want to limit read and write on all apiserver storage, not just secrets.  That would discourage people from depending on our storage implementation.

**Comment by liggitt** [comment]
+1 for preventing end-runs around API conversion/validation. think of the support calls :)

**Comment by jefferai** [comment]
Probably whether it makes sense to use something like Vault vs. simply encrypting data at rest in any Kubernetes storage solution depends on whether the extra things Vault does are useful (fine-grained access control, tokens with TTLs and limits on the number of uses, generation of short-lived access to external resources etc.) It's really designed for a wide set of use-cases that may simply not be needed by Kubernetes.

There are other tickets for ZooKeeper/Consul support instead of etcd for backing K/V storage, so it probably makes sense for most secrets to simply encrypt what's being stored into the K/V store.

That said you then still have the problem of the master keys -- where they should be stored and who has access -- and that is both a hard problem and a place where Vault could be useful, especially using the transit backend (https://vaultproject.io/docs/secrets/transit/index.html). It's going to gain support for key generation (so that the private key is never exposed but kept locked in Vault) and key rotation/rollover pretty soon, which will make it work quite well as a KEK service. Those that don't want to use Vault or a similar solution could simply make do with ACLs on a master key stored in the K/V store, or some similar approach.

**Comment by davidopp** [comment]
This is marked P1 but hasn't been touched in months,. @erictune can you find an owner or bump it to P2?

**Comment by erictune** [comment]
I may have someone to work on this.  

I'm told @smarterclayton is working on code that (1) wraps all objects stored in etcd in a "wrapper" object, and (2) allows different "encodings" to be applied to the "inner" object stored in etcd, such as a protocol buffer binary wire format encoding, and (3) the outer or wrapper object can record what encoding(s) were applied to the inner object.

@smarterclayton  is the above correct, and can you point at an issue or PR and/or give an ETA for said feature?  1.3?

Assuming that feature is available, the idea would be to have encryption be one form of encoding that can be applied to "inner" objects, and to apply it to all secret objects.

I don't want to get into any specifics about keys and ciphers yet.  Just confirming that the encoding support is going to line up.

**Comment by erictune** [comment]
@lavalamp

**Comment by erictune** [comment]
@pmoire if you know about serializers status

**Comment by liggitt** [comment]
cc @pmorie

**Comment by lavalamp** [comment]
@wojtek-t wants the protobuf work to happen, too. 1.3 is a safe bet for this.

**Comment by wojtek-t** [comment]
@erictune - yes - you can assume that support for protobufs will be done for 1.3

**Comment by erictune** [comment]
One issue with the serializer approach.  It would not allow the secrets to be stored in an HSM, which some customers have asked for. That would require a different storage backend, rather than a different serializer.  I'm going to try to meet with some HSM users to understand the use case better.  Let me know if you have experience and are interested.

**Comment by erictune** [comment]
Here is an alternative that can be implemented by end-users now, rather than waiting for this feature to be implemented.

Assume you have a special secret that you never want to hit the disk, including via etcd.
You can do this:

1. have an init script on each node that makes a tmpfs, say at `/mnt/foo`.
2. Have some process by which, when a node boots, a secret is copied into `/mnt/foo`, say `/mnt/foo/special_secret.txt`.
3. Pods that need the special secret have a volume spec with `hostPath: /mnt/foo`.

This is a little bit clunky, but it does allow people with strict rules around secrets to start using Kubernetes.  Two use cases I am thinking of are when `special_secret.txt` is a credential used to talk to a HSM, to get other secrets, or a secret used to auth to Vault, to get secrets from Vault.

This pattern also might work in conjunction with https://github.com/UKHomeOffice/vault-sidekick

**Comment by rickypai** [comment]
@erictune: in the workaround, wouldn't this mean the nodes need to store on disk the superset of secrets needed by all pods that may be scheduled? also, preventing pods from mounting specific host paths, which may expose it secrets it's not supposed to have access to, would require additional logic.

**Comment by erictune** [comment]
@rickypai 

In this scenario, the node only stores one, or a few secrets.  Those secrets are used to  get additional secrets from vault.  Those secrets would not be stored on disk but on tmpfs.  On node reboot, and admin needs to ssh to each node and place a secret onto the tmpfs again.

Whether you need additional logic to prevent pods from mounting specific host paths depends on your threat model.  If you don't trust the users that create pods very much, then I agree you need the additional logic.  If you mostly trust your insiders, and just want to isolate containers from each other, and have audit requirements around your secrets, then I think what I said is useful.

**Comment by alfred-huangjian** [comment]
cc @kubernetes/huawei

**Comment by mkonda** [comment]
Good discussion.  Where did it end up?

Let's say we don't want the framework to assume we trust our insiders.  Let's also say we want the default behavior to be that secrets are encrypted and don't hit disk anywhere.  Finally, let's say that we want it to be easy to set up.

What would a good candidate PR look like?  Would it be to set a different default storage here: 
https://github.com/kubernetes/kubernetes/blob/f2ddd60eb9e7e9e29f7a105a9a8fa020042e8e52/pkg/registry/secret/registry.go or would it be here:  https://github.com/kubernetes/kubernetes/blob/f2ddd60eb9e7e9e29f7a105a9a8fa020042e8e52/pkg/registry/secret/etcd/etcd.go  (OR neither?  🎱 ?)

It is a hard problem to solve well - so not criticizing just wondering how we can make it better...

**Comment by brendandburns** [comment]
A place to start would be to create an 'encrypting storage' that wraps the storage interface and encrypts things, of course you're going to need to worry about where you get the secret that you use to encrypt the storage and how do you keep it around in the apiserver so that the encrypted data is actually safer.  An alternative would be to see if you can implement the storage layer in terms of calls to a Vault server.

One possibility would be to use some sort of client cert to get a key from some other server and only hold that key in memory in the apiserver and use that for encrypt/decrypt.  That way if your master gets owned you can revoke the client certificate on the other server someone can't decrypt the data (assuming that the apiserver process has died), perhaps we can leverage Vault here in some way.

Note that I really think you _do_ want the secrets to hit disk because otherwise they'll never get persisted anywhere which will lead to large-scale sadness when you upgrade clusters, or lose power, or...

This is different than the behavior of the secrets when they are assigned to a Pod, when they are assigned to a pod they are mounted on a ram disk and never hit the disk on the worker node, but persistence is an important part of usability on the master.  Though of course it should be encrypted.

Also we should probably decrypt the secret inside the apiserver and then re-encrypt with a node specific key so that if someone owns a node they can't access all secrets.

**Comment by smarterclayton** [comment]
Nodes should only have access to things scheduled to them.  This is
part of a larger issue that has been discussed with sig-auth
participants before.  We need an issue to track that.

**Comment by stevesloka** [comment]
I'm really interested in this as well, possibly adding another secret implementation which has a different backing . That adds complexity to the cluster, but allows users to define which pieces get encrypted and which don't since you could ask for a secret from the default backing or from the encrypted backing.

**Comment by stevesloka** [comment]
Could we add an interface to the secrets api. This would allows us to optionally implement an encryption backend to encrypt secrets before they are written to etcd. My thought would be much like the cloud provider implementation we could build one for Vault, or AWS KMS, etc. 

For example, using the Transit Backend in Vault (https://www.vaultproject.io/docs/secrets/transit/), we could grab the secret getting written to the api, first encrypt, then pass on to etcd. When the secret is needing read, the just do the same, but decypt on the way out. 

I could also see annotating a way to let users encrypt secrets or not (maintain current behavior), in this way we don't break anything existing. 

This is related to #10439 where the vault backend was wanting to get swapped in. 

If this makes sense, I'm happy to start a PR and work on seeing how this could be implemented.

**Comment by smarterclayton** [comment]
It should be possible to wrap the current storage interface to provide this
behavior (pkg/storage contains those interfaces).  There are a few
decorator patterns being used there.

**Comment by stevesloka** [comment]
Thanks @smarterclayton, I'm going to hack around a bit and see what I can come up with.

**Comment by stevesloka** [comment]
Being new to the core k8s codebase I'm feeling a little stuck as to where to start working on this implementation. Can anyone help me out with some pointers? 

I see there's a registry that gets created (https://github.com/kubernetes/kubernetes/blob/master/pkg/registry/secret/registry.go#L26) and is implemented, but I'm not 100% on where that is. 

I see the storage interface pieces (https://github.com/kubernetes/kubernetes/blob/master/pkg/storage/interfaces.go#L114) as @smarterclayton and @brendandburns noted, but again I'm not figuring out the implementation pieces of where I'd put by code. 

Thanks for any tips / help!

**Comment by smarterclayton** [comment]
Assigning myself to shepherd this through.

**Comment by pnovotnak** [comment]
What would the damage be if someone got into a **non-privileged** container in a 1.6 GKE cluster? Could they get into etcd or into the API right off the bat? Or would they need more, such as compromising a privileged container, etc.

**Comment by pawelprazak** [comment]
IFAIK, by default, it's game over, because you get access to
/var/run/secrets/kubernetes.io/serviceaccount and you can just create a
privileged container, take a look at this article:
https://medium.com/@CornflakeSavage/capturing-all-the-flags-in-bsidessf-ctf-by-pwning-our-infrastructure-3570b99b4dd0

also there is a problem of restricting access to AWS or GCE instance
metadata, and effectively to the IaaS API, we use kube2iam project with AWS

**Comment by smarterclayton** [comment]
The plan for GKE is to disable the ABAC mode for service accounts, but
that is a breaking change for existing users.  @cjcullen can point you
there if you need more info, not related to this issue.

**Comment by pnovotnak** [comment]
So, if RBAC is enabled, the situation is clearly better, unless someone
gets into a pod with too much access. So, the game is keeping an attacker
out of pods with what roles? Instance metadata is a good point... Can an
attacker get everything they need from that?

Any other ways into etcd?

**Comment by smarterclayton** [comment]
Would be better to move this discussion to the threat model PR in
kubernetes/community

**Comment by destijl** [comment]
Anyone here who has a use case for encryption of secrets at the database layer: please check the latest proposal:
https://github.com/kubernetes/community/pull/607

Particularly if you have hard requirements that aren't satisfied by option 1, we'd like to know now.

**Comment by stevesloka** [comment]
Hey @desttijl, my only requirement which is how I got started with this feature was to encrypt data at rest to better meet my HIPAA requirements of encryption at rest. 

I think option one is good for this to get rolling. My initial idea was to treat like a cloud provider where you could implement your own, but might be too difficult to implement safely. 

We use vault for some secret management so the vault transit API seemed interesting, but I'm cool with this right now. 

Need any help coding pieces? I'm happy to help out if appropriate!

**Comment by djschny** [comment]
Excuse my ignorance here, but for encryption at rest, why not setup `dm-crypt` on for the filesystem on the host supporting `etcd`?

**Comment by destijl** [comment]
@djschny you can, and having an encrypted disk is expected. The advantages of doing this on top are discussed in the first section of the proposal.

**Comment by kksriram** [comment]
We've been looking at [this](https://github.com/kubernetes/kubernetes/issues/12742#issuecomment-243235263) and have a proposal that builds on @smarterclayton implementations in 1.7. 

I'm new to this, so do I create a new issue to track managing the encryption key for a K8S cluster, via Vault?

**Comment by destijl** [comment]
@kksriram @sakshamsharma has a implementation for a KEK/DEK scheme that uses Google KMS to store the key. You should talk and align with that implementation:

https://github.com/kubernetes/kubernetes/pull/48574

**Comment by kksriram** [comment]
We've got a [proposal](https://docs.google.com/document/d/15-baW4i7qws1yxxIYjHXqKpk259ebauQbECQCpPD308/edit#heading=h.67bgmqyjswzf) to use envelope encryption and have Vault encrypt the DEKs. 

I will push this out to sig-auth as well. 

This builds on the work in [41939](https://github.com/kubernetes/kubernetes/pull/41939), [46460](https://github.com/kubernetes/kubernetes/pull/46460) and will likely end up being a new KMS provider based on [48574](https://github.com/kubernetes/kubernetes/pull/48574) that uses Vault.

**Comment by sakshamsharma** [comment]
Of note, https://github.com/Kubernetes/Kubernetes/pull/49350, which
implements this, is already up for review.

On 21 Jul 2017 10:23, "KK Sriramadhesikan" <notifications@github.com> wrote:

We've got a proposal
<https://docs.google.com/document/d/15-baW4i7qws1yxxIYjHXqKpk259ebauQbECQCpPD308/edit#heading=h.67bgmqyjswzf>
to use envelope encryption and have Vault encrypt the DEKs.

I will push this out to sig-auth as well.

This builds on the work in 41939
<https://github.com/kubernetes/kubernetes/pull/41939>, 46460
<https://github.com/kubernetes/kubernetes/pull/46460> and will likely end
up being a new KMS provider based on 48574
<https://github.com/kubernetes/kubernetes/pull/48574> that uses Vault.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/12742#issuecomment-317061185>,
or mute the thread

**Comment by kksriram** [comment]
@sakshamsharma, The Vault Provider would be another implementation of the same interfaces that you've got in that PR. The impl of the proposal I posted would go into Vendors  as a Vault Provider analogous to the one you're implementing for GCEKMS.

**Comment by liggitt** [comment]
closing in favor of kubernetes/features#92
