### ISSUE TITLE
`kubectl` handling of `node-role.kubernetes.io/control-plane` label encourages poor practice

### ISSUE THREAD

**Issue by sftim** [kubernetes/kubernetes#127507]
**This is a Feature Request**

The label `node-role.kubernetes.io/control-plane` indicates which nodes are control plane nodes.

However, `kubectl` will display the (unofficial, unregistered) label `node-role.kubernetes.io/fictional` label as a _node role_ for a node if set to `true`.

**What would you like to be added**

Either:
- revise `kubectl` / the API server to display unrecognized node roles a special way. For example, use the string `[unknown]` instead of `fictional` if a node is labelled `node-role.kubernetes.io/fictional`
  This approach fits if we think that the distinction Kubernetes cares about is the boolean control plane vs not distinction.
  - and include a changelog entry about this
- revise `node-role.kubernetes.io/control-plane` and ``node-role.kubernetes.io/master` and replace them with a new family of labels, `node-role.kubernetes.io/*`

We could also define a new label and recommend using that; for example, `node.kubernetes.io/grouping`. We could even switch the column in `kubectl` to use the new label rather than node role, or even automate that control plane nodes put themselves in a "control plane" grouping by default.

**Why is this needed**
People see that they can set an arbitrary _node label_ on a node, and that kubectl displays it, and they assume that the labels work differently from what we've documented.

**Comments**
/sig cli
/sig architecture

**Comment by liggitt** [comment]
I _think_ the current behavior is intended and correct, and the ability to define arbitrary node roles is intentional.

to my knowledge, there is not special treatment of control-plane and node roles in core kubernetes components, so end users *can* define arbitrary roles and use them as they please.

if sig-node confirms this, we should document that for`node-role.kubernetes.io/*`

**Comment by liggitt** [comment]
See https://github.com/kubernetes/kubernetes/pull/39112#issuecomment-275713102 and lots of surrounding comments … the prefix-only portion being well-defined and the suffix/role portion not was very specific and intentional. Particular tools used master and node (now control-plane and node), but those specific values don't drive special behavior within Kubernetes.

**Comment by sftim** [comment]
Relevant to https://github.com/aws/containers-roadmap/issues/1381

**Comment by sftim** [comment]
The SIG who defined these roles is, IIRC, cluster lifecycle.

**Comment by sftim** [comment]
We might want to document conventions about the wildcard within `node-role.kubernetes.io/*`; basically: is it “anything the API accepts is OK“ or do we think it should be narrower?

**Comment by sftim** [comment]
What's the right answer? Either the docs are wrong and we need an issue there, or kubectl _is_ misleading people, or it's an even more complex challenge to handle.

**Comment by liggitt** [comment]
The label was designed so arbitrary / custom roles would work properly. It is entirely up to the cluster administrator to set / use.

`kubeadm` as a tool for cluster administrators has opinions about the values to set here, but that's the only in-tree thing I know of that cares about the actual role set.

kube-apiserver keeps nodes from setting any arbitrary role, and kubectl will display any arbitrary role, but nothing in kubelet / apiserver / scheduler / kube-proxy / kubectl pays attention to the particular role a node has.

**Comment by sftim** [comment]
/triage unresolved

The docs are wrong.
/close not-planned
