### ISSUE TITLE
The getting started guide on CentOS should be updated

### ISSUE THREAD

**Issue by hw-qiaolei** [kubernetes/kubernetes#12767]
The `Getting started on CentOS`(https://github.com/kubernetes/kubernetes/blob/master/docs/getting-started-guides/centos/centos_manual_config.md) should be updated to track the latest changes.Current version is quite out of date. For example:

1, It does not clearly describe the prerequistes. It even does not say CentOS7.
2, It says very little about the OS setup.
3, The repo `virt7-testing` given by this guide is too old (kubernetes 0.18.0).
4, The configuration files varies a lot from the old version 0.18.0, it is the result of problem stated as above 3. For example:
    - `KUBE_API_ADDRESS` still uses the deprecated `--address` where it is recommended to use `-insecure-bind-address` instead. This also applies to `KUBE_API_PORT`
    - It does not say anything about how to setup service account (private) key file which is needed by the newer version of kubernetes
5, Users cannot specify the version of kubernetes(and its dependencies such as etcd) they want to install.

What do you think about it?

**Comment by mbforbes** [comment]
Thanks for the thorough feedback—we'd love a PR to improve this if you have time!

**Comment by hw-qiaolei** [comment]
I'd love to do that. My only concern is that this guide uses a yum repo to install kubernetes, and I need the SPEC files(`kubernetes-node`, `kubernetes`, `kubernetes-client`, `kubernetes-master`) to build kubernetes rpms. Could @mbforbes and @coolsvap (I noticed @coolsvap  is the maintainer of baremetal CentOS guide ) offer some help on this?
```
# rpm -qa | grep kubernetes
kubernetes-node-1.1.0-0.4.git2bfa9a1.el7.x86_64
kubernetes-1.1.0-0.4.git2bfa9a1.el7.x86_64
kubernetes-client-1.1.0-0.4.git2bfa9a1.el7.x86_64
kubernetes-master-1.1.0-0.4.git2bfa9a1.el7.x86_64
```

**Comment by mbforbes** [comment]
I can't, but @brendandburns can tell you who can.

**Comment by hw-qiaolei** [comment]
@brendandburns could you please provide me with these k8s SPECs or tell me who should I turn to get help?

**Comment by coolsvap** [comment]
I will update it in couple of days.

**Comment by hw-qiaolei** [comment]
Thanks @coolsvap , is it possible for me to get the SPEC files to build (`kubernetes-node`, `kubernetes`, `kubernetes-client`, `kubernetes-master`) ?

**Comment by kfox1111** [comment]
Ping?

**Comment by cognitiaclaeves** [comment]
Just got bit by this. I'd like to add the following concerns:

Getting start on CentOS for Kub 1.1 ( https://github.com/kubernetes/kubernetes/blob/release-1.1/docs/getting-started-guides/centos/centos_manual_config.md )

references the out-of-date repo ( virt7-testing kubernetes ), when, oddly, the prior version of the document:

Getting started on CentOS(https://github.com/kubernetes/kubernetes/blob/master/docs/getting-started-guides/centos/centos_manual_config.md):

reference a newer ( and usable ) repo.

Additionally, 

 - both reference using etcd-0.4.6-7, as a temporary update in documentation ( but one that carries through from the first page to its later version in the 1.1 tree ), but neither really identifies what the issue with the latest etcd was, so I can't determine if it would be okay to run the latest, which is probably later than what caused an issue.

- This becomes more important to know because the version of etcd recommended (0.4.6.7) causes immediate failures: it appears to arbitrarily bind to port 4001 instead of what is in the config file
- Further, that version of etcd does not include an etcdctl, which is included again in the latest package today.

I hope this documentation is updated soon.

**Comment by Trane9991** [comment]
Any updates? Currently, CentOS extras repo contain Kubernetes 1.2.0. But it would be nice to have latest stable packages(1.3.4)

**Comment by xiaoping378** [comment]
Maybe we should add an action in Makefile:  **make rpms**

**Comment by discostur** [comment]
Does anybody have a spec-file to self-compile a newer version than 1.2? Or is there any other repository?
