### ISSUE TITLE
ingress doesn't works well for namespaced scenario

### ISSUE THREAD

**Issue by yong-jie-gong** [kubernetes/kubernetes#127657]
### What happened?

with latest ingress/ingressClass design, there is no way to run application without requesting read permission on cluster level resource "IngressClass"
 
This is how issue happens
==As k8s administrator==
1) create the namespace for application "demoapp1" to be installed 
```shell
kubectl create ns demoapp1
```
2) create the role and rolebinding for application "demoapp1" 
```shell
kubectl create role demoapp1-admin --resource="*" --verb="*"
```

3) genenate the kubeconfig file "demoapp1-kubeconfig.yaml" from role "demoapp1-admin"

===As application administrator===
1) get the kubeconfig file of "demoapp1-admin"  from k8s administrator
2) install demoapp1 such as "helm install demoapp1 demoapp1.tgz --kube-config demoapp1-kubeconfig.yaml"
  in demoapp1, there is some ingresses as below
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-class-name-no-perm
  namespace: ingress-nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx

```
in demoapp1, there is one ingress-controller deployed which watch all of ingress whose ingressClassName is "nginx".   this ingress-controller should start and run without any error

as shown above, there is no cluster role binding for "application administrator" to install "demoapp1", it means any attempt to access k8s cluster resource will be denied

unfortunately,  k8s reference doesn't provide clear guidance  on how to valid the <ingress>.spec.ingressClassName, so most of ingress-controller implementation will try to read the IngressClass object from <ingress>.spec.ingressClassName.
obvisously, it will fail

in big shared k8s cluster, k8s administrator don't want to shared cluster level resource permission to applications running the namespace.  so typically, they just provide least privileged kubeconfig for application installation

### What did you expect to happen?

ingress-controller/ingress can works without read permission on cluster reosurce "IngressClass"

### How can we reproduce it (as minimally and precisely as possible)?

check details in "what happend" section

### Anything else we need to know?

it is ingress/ingressclass design issue, had a long discussion with @aojea 
https://kubernetes.slack.com/archives/C09QYUH5W/p1727081948800529

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

Client Version: v1.30.4
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.4

</details>

### Cloud provider

<details>
on-premise
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```
irrelevant
</details>

### Install tools

<details>
irrelevant
</details>

### Container runtime (CRI) and version (if applicable)

<details>
irrelevant
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
irrelevant
</details>

**Comment by yong-jie-gong** [comment]
@aojea @thockin

**Comment by thockin** [comment]
@robscott for more context

Ingress was designed as a cluster-concept.  Cluster admins would decide what modes of ingress are allowed (via IngressClass objects) and users would use them (via Ingress objects).  The assumption was that it was up to the implementations to be smart and safe.  If an implementation wanted to share a proxy and/or IP, it was that implementation's responsibility to make sure that (for example) one Ingress can't "steal" a hostname or URL from another Ingress.

It has become more common to see people who want to run THEIR OWN ingress implementation of Ingress in their own namespaces.  This should be fine EXCEPT:
1) you need to tell it to only watch this namespace - this could be done by a flag on the impl
2) you need to tell other controllers NOT to implement this namespace - this is generally IngressClass is for

I don't see the need for per-namespace classes - any particular config you would put in the class can be done via other,  more local mechanisms (e.g. flags, configmap).  I know some in-cluster implementations have a flag that says "watch this namespace, but ignore class".  Then your impl does not need permission to read IngressClasses, and certainly not write them. 
 That solves point 1 but not point 2.

The only way (I think) we have to communicate between ingress implementations is IngressClass - you need to specify SOMETHING in class that other implementations will know "not for me".  The actual API for specifying IngressClass is `IngressClassName` and is validated as an IngressClass name, meaning that there's no value you can put in this field which is not POTENTIALLY a valid IngressClass.  HOWEVER, it is possible to NOT specify a class.

So, as far as I can see, the only "safe" ways to define Ingress objects which intend to be implemented by a namespace-private controller are:
1) Don't specify `IngressClassName` and count on other implementations to ignore those
2) Use a bogus-sounding (but technically valid) name, e.g. "private-do-not-use-this-name-for-real"
3) Have the cluster admin define a real class which is reserved for this purpose, e.g. "namespace-private"

There are other ways we could approach this, if we consider "more work" to be OK.  

We could extend the validation to allow something which isn't a valid `IngressClass` name, e.g. `"_"` which could never match a real IngressClass.  I don't love this idea.

Instead of running private ingress controllers yourself, have cluster-admin run a multi-single-tenant controller which creates (perhaps based on class) a dedicated proxy and/or IP per tenant (e.g. namespace) and maps Ingress objects from a given tenant to that tenant's "private" proxy instance.  This doesn't SOLVE the problem, but dodges it.  It does assume that it's OK for cluster-admin to make that decision.

We could say "don't use Ingress".  Just configure nginx directly.

We could say "use Gateway" - does Gateway do this better?

What is the resolution desired here?

**Comment by fravoss** [comment]
@thockin , "just configure nginx" is not practical for large applications with many microservices that may or may not be installed, and each with their own ingress configuration.  Such applications would have to build their own ingress-controller-like functionality that compiles the overall nginx.conf based on the many configuration fragments that the microsevices deploy, i.e. they'd implement a duplication of an ingress controller's logic.

I wonder how critical problem #2 is, i.e. how problematic it would be if a cluster-wide ingress controller picked up the same ingress resources in addition to the namespaced ingress controller.  
Such an application would be reachable at two endpoints, (1) the namespaced ingress controller that the application brings, and (2) the cluster-wide ingress controller.  I am not sure how likely that would be in practice.  I'd expect that someone who installs such an application-private ingress to rather use an application-specific name and not "nginx" as in the example above, and in the theoretical situation of a collision of class names where the app-owner does not want his app to be reachable under the cluster controller, he'd simply reconfigure his namespaced application. 

I believe primary problem is "how can a namespaced ingress controller identfy the ingress resources it is responsible for (w/o read permission of IngressClasses)" to avoid the above proprietary duplication of controller logic to create nginx.conf.  
The IngressClass concept assumes an indirection where the controller looks up the ingress class names it shall look out for based on its controller identity, and that fails w/o if the controller cannot read IngressClass resources.  I believe the problem could be simply solved if a controller was allowed by the ingress specification to optionally defines directly the class names it should look out for.

**Comment by thockin** [comment]
> I believe the problem could be simply solved if a controller was allowed by the ingress specification to optionally defines directly the class names it should look out for.

It is already optional (not required) to specify a class, is that sufficient?

**Comment by fravoss** [comment]
Unfortunately not. On the one hand, I'd expect that to collide with a
cluster level Ingress controller that handles the default Ingress class.
The other problem: OpenShift flags Ingress resources without Ingress class
name as an issue in its admin console, which leads to customer complaints

Tim Hockin ***@***.***> schrieb am Fr., 27. Sept. 2024, 16:44:

**Comment by aojea** [comment]
> I'd expect that to collide with a cluster level Ingress controller that handles the default Ingress class.

is this a hypothesis or a fact?
should an ingress controller that knows about classes take on an ingress object without a class?

> OpenShift flags Ingress resources without Ingress class name as an issue in its admin console

is it only Openshift that is opinionated about this? do we have any place that documents the security issues this behavior present?

**Comment by fravoss** [comment]
That's the definition of the default Ingress class, afaik. If one of the
controller's Ingress classes is tagged as the default IC, then the
controller reads those ingresses that don't have the Ingress class name set

Antonio Ojea ***@***.***> schrieb am Fr., 27. Sept. 2024,
19:33:

**Comment by thockin** [comment]
Shoot, I forgot all about "ingressclass.kubernetes.io/is-default-class" (see plugin/pkg/admission/network/defaultingressclass/admission.go).  I edited my comment.

> I believe the problem could be simply solved if a controller was allowed by the ingress specification to optionally defines directly the class names it should look out for.

This is not part of the Ingress API, and nothing prevents ingress implementations from imposing their own restrictions or config.

The problem that remains is that *any* value you put into `IngressClassName` could, potentially, be a real class with an implementation looking for it.  That said, it's pretty unlikely that something like "namespace-private" or "namespace-$THISNS-private" would be used, and you can put anything there as long as you agree with yourself (the Ingress object and the implementation's flags).

**Comment by fravoss** [comment]
> This is not part of the Ingress API, and nothing prevents ingress implementations from imposing their own restrictions or config.

@thockin, that makes sense and was my assumptionas well. However, the nginx-ingress-controller folks sent us to sig/network as they interpret the Ingress API specification to disallow their controller implementation to have such controller-specific config to identify ingresses based on .spec.ingressClassName. 
Indeed, statements like "_the field is a reference to an IngressClass resource that contains additional Ingress configuration, including the name of the Ingress controller_" in [Ingress concepts](https://kubernetes.io/docs/concepts/services-networking/ingress/) could be read as"the .spec,ingressControllerName MUST point to a valid IngressClass resource", thus my above ask to crispen the wording of the Ingress API spec to remove the uncertainty about this controller-specific config.

**Comment by sftim** [comment]
> ingress-controller/ingress can works without read permission on cluster reosurce "IngressClass"

This sounds like a feature request. I think it's a big enough switch from the original design of Ingress that we should put forward a KEP.

**Comment by sftim** [comment]
We can come up with mechanisms that work namespaced, but we should aim for the formal review and buy-in that a KEP gets us.

**Comment by thockin** [comment]
>  they interpret the Ingress API specification to disallow their controller implementation to have such controller-specific config to identify ingresses based on .spec.ingressClassName.

Not an unreasonable interpretation, I guess.  That said, we don't usually enumerate all of the things that a non-conformant implementation is allowed to do. That's an open-ended list and would be noise for most readers of API docs.  

The way I interpret what we are talking about is "the controller can be configured to ignore the class".  That's it, right?  We are not talking about a conformance test, or saying that this is the right thing to do for cluster wide controller installations. This is about a very localized decision, perhaps a single namespace, to ignore some aspect of the spec.  There is some risk involved, as we discussed earlier, but it's plausible to make this "safe enough".

If there's a PR to be had here, it's just docs and needs to be somewhat insignificant. This is not the normal operating mode.  

If I misunderstood, and what you're really proposing is a deeper change to the specification to allow a namespaceed concept of class, then the other Tim is correct that it's a significant change and would require a kep.  That said, I don't think we're really entertaining significant changes to ingress API at this point. 

Also, if we make a docs change here, we should probably make a similar change to gateway API.

**Comment by sftim** [comment]
IMO: allowing a namespaced concept of class is only one of the potential fixes. We could define a label or annotation based mechanism for specifying something like an IngressClass, or we could look at an object reference mechanism, or&hellip; there are many options.

I think Kubernetes should clearly define that `ingressClassName` _is_ a reference to a name of a (cluster-scoped) IngressClass, which right now it is.

And we should also document that an ingress controller should be allowed to read IngressClasses, so that it can find the cluster default.

---

But if, for example, a particular ingress controller decides it's only interested in Ingresses that are labelled as:
- `foo.example/ingress-thingy: bananas`
- `foo.example/private-configuration-name: public-loadbalanced`

then that's basically fine. Nothing nonconformant has happened. Labels are there to let you do custom things (don't use official Kubernetes labels for this kind of detail).


We could define one well-known official label for Ingresses to indicate that they don't want the default IngressClass to apply to them even with `ingressClassName` unset. Setting that label won't stop another ingress controller trying, but we could do that, and I can see it being useful to try. Or we could extend the API, but I don't see the appetite for us to do that.


I also think we should ask in-project ingress controller authors to watch out for unhelpful precedents.

**Comment by sftim** [comment]
> the .spec,ingressControllerName MUST point to a valid IngressClass resource

This is really not a MUST. If you want to delete an IngressClass, we're not going to enforce that you delete all Ingresses that reference it. You might have some broken workloads, watch out for doing this in prod, test your changes etc. But it's _allowed_.

**Comment by thockin** [comment]
>> the .spec,ingressControllerName MUST point to a valid IngressClass resource
>
> This is really not a MUST. If you want to delete an IngressClass, we're not going to enforce...

Correct - in almost every place where one object refs another, we do not ENFORCE it, but instead seek to reconcile.

> I think Kubernetes should clearly define that ingressClassName is a reference to a name of a (cluster-scoped) IngressClass

It already says "ingressClassName is the name of an IngressClass cluster resource."

> And we should also document that an ingress controller should be allowed to read IngressClasses

I don't mind having documentation (an "Ingress controller implementors guide" seems useful) but it's not API comment-docs (e.g. in openapi).  

> so that it can find the cluster default.

The controllers don't do this, there's admission control which handles that.  But yes, a cluster-wide Ingress controller needs to be able to read IngressClass objects.  That seemed self-evident to me, but I guess that's not universally shared :)  

Because ingress is not implemented in-tree, we do not have a canned ClusterRole for it.  Should we?  That seems OK to me, but also could be seen as a security risk?

> We could define one well-known official label for Ingresses to indicate that they don't want the default IngressClass to apply to them even with ingressClassName unset

I guess, but ....is it really worhtwhile?  Just about everything with a "SomethingClass" follows a similar pattern - if you do not specify your class, you get `<this one>` as the default.  It feels a little cylcic to provide another way to say "I know you want to apply the default but I don't want the default", which will likely be met with another one expressing "I am the cluster admin, dammit, and you will get a default".  Remember, anything we change here we need to at least consider changing for Gateway and probably PVC and ...

IOW, electing a default class provides a sort of invariant for the cluster - do we want to violate that?  Is that better than recommending that people actually install a real IngressClass named "ns-private" or something?

**Comment by sftim** [comment]
> recommending that people actually install a real IngressClass named "ns-private" or something?

Actually, I like that idea. The trouble is: you need a friendly cluster admin, and if you had one of those you mightn't be asking for advice about how to get round them.

This could be a blog article. I think the official docs are basically already right, and blog articles are allowed to mark where the author's opinion isn't 100% aligned with Kubernetes as a project.

**Comment by fravoss** [comment]
> Actually, I like that idea. The trouble is: you need a friendly cluster admin, and if you had one of those you mightn't be asking for advice about how to get round them.

That exactly is the problem that triggered the issue - if an ingress controller is installed as part of a (large) application to handle that application´s ingresses, the permissions to read a cluster-wide resource like IngressClass are difficult to get from a cluster admin, let alone that it is inconvenient for the admin having to manage an ingressClass just for that app.

Using .spec,ingressClassName as the single hint for a controller to select ingress resources feels intuitive.  A parallel controller-defined selection mechanism (e.g. some label) and leaving the ingressClassName empty for these namespace-managed ingresses would introduce the need for that "I don´t want the default" hint for the default cluster-wide controller to ignore the ingress.

The gap is rather on the side of how the controller can determine the ingressClassNames it shall handle.  If the spec allowed a namespaced ingress controller to be configured directly which ingressClassName to avoid the need to read all ingressClass resources and find its matches would solve that.  I realize that this would require to relax the above statement, though:
> I think Kubernetes should clearly define that ingressClassName is a reference to a name of a (cluster-scoped) IngressClass

**Comment by thockin** [comment]
> The gap is rather on the side of how the controller can determine the ingressClassNames it shall handle.

`your-controller --this-namespace-only --class-pattern=^private-NS.*`

Controller looks up its own namespace and looks for Ingresses that match that pattern.  This is entirely under the controller's purvey.

>  If the spec allowed a namespaced ingress controller to ... avoid the need to read all ingressClass resources

The spec doesn't need to allow it.  You can do anything you want, as long as the name you pick is a) valid and b) not being used by a real class.

**Comment by sftim** [comment]
An analogy, maybe not ideal but it might help: there is a building code for emergency exits. The exit must open outwards and for high occupancy buildings there must be a bar you can push to open the door even when it is locked. If there is a glass panel it must be fireproof and cannot be frosted.

You want to use one of these doors for your bathroom. You ask the building control people if the regulations would allow using a frosted non-fireproof panel. The building regulations people say that this wouldn't pass code for a building exit door, but they also don't mind what kind of door you use for the bathroom in your own apartment.

Kubernetes probably won't change the API definition or field semantics here, but if you're running your own cluster: you don't need to worry too much about what Kubernetes, as a project, thinks about your cluster.

**Comment by fravoss** [comment]
The difference to your analogy is that not many people will want an emergency exit door for their bathroom, whereas there is demand for namespaced ingress controllers.  That worked earlier and got broken with the switch to ingressClasses.  

This thread was not about what I could do in my own private cluster, it was rather about how an ingress  controller team that wants to be well-behaving in the Kubernetes ecosystem can keep the namespaced controller scenario alive.

To conclude the long thread, the options are

(1) go along the lines of @thockin's "_Controller looks up its own namespace and looks for Ingresses that match that pattern. This is entirely under the controller's purvey_" in the nginx-ingress-controller, with the caveat that the spec does not specifically support this, it just does not disallow it
(2) don't set the .spec.ingressClassName in the Ingress, and hope that there's no undesired side-effect from the default ingress controller picking up these ingresses.
(3) accept that the namespace-only concept got broken and ask the cluster admin to create an extra ingressClass per each namespaced app

**Comment by thockin** [comment]
Option 4: build an argument for extending the validation on this field to include values that can't possibly be real, and document them as reserved for private implementations, or something. Opinion, to make this argument we would have to bring the gateway API in alignment. I can't see why doing it for one and not the other would make sense

**Comment by thockin** [comment]
Ingress and Gateway: YES
Storage: Maybe

**Comment by fravoss** [comment]
> Option 4: build an argument for extending the validation on this field to include values that can't possibly be real, and document them as reserved for private implementations, or something.

this would be, for example, to mandate that such controller-configured class names could contain an invalid character (e.g. must start with an underscore) to ensure there's no collisions with real storageClass resources.   That would work.

**Comment by fravoss** [comment]
> If we do it for IngressClass, does that set a precedent for StorageClass

There is currently no enforcement that PV and PVC references to StorageClasses are actually real StorageClass resources.  An admin can provision storage and create a PV for that storage with a .spec.storageClassName of the admin's choice, and a PVC will get bound if it requests a volume of that storageClassName.   I perceive that as intuitive; the admin acts like a storage provisioner and uses the regular storage class concept as an indication of the type of storage, and the PV-PVC binding works with the same matching rules.

**Comment by sftim** [comment]
> this would be, for example, to mandate that such controller-configured class names could contain an invalid character (e.g. must start with an underscore) to ensure there's no collisions with real storageClass resources. That would work.

That change needs a KEP, which means it needs contributor effort to make it happen. We can do it, but there are other priorities for the project that may come first.

**Comment by thockin** [comment]
I will also say that the bar for changes to Ingress is really high - it's essentially a frozen API.  Not impossible but the change needs to be VERY surgical and VERY thoroughly considered for side-effect.

**Comment by yong-jie-gong** [comment]
@thockin @sftim if that is the case, can we say option 01 is more practical. not sure if we should suggest ingress-controller vendor to resolve this issue with option-01?

**Comment by thockin** [comment]
I think vendors CAN implement this themselves.  https://github.com/kubernetes/kubernetes/issues/127657#issuecomment-2386255406 is a viable path, but to justify that I'd want to see why vendors can't do it themselves.

**Comment by yong-jie-gong** [comment]
is it possible add this options somewhere like kubernetes docs as recommendation?

**Comment by sftim** [comment]
@yong-jie-gong Kubernetes is open source; anyone is welcome to propose a docs improvement.

However, I don't think the Kubernetes project is going to _recommend_ doing this. The recommendation is more likely to be: use Gateway API; work with Gateway API to support deployment within a namespace; remember that Ingress is frozen.

If you want the project to not believe that Gateway is the right direction, this will be a big ask. If you want the docs to recommend slightly misusing a frozen API: I wouldn't support it. We should be aligning our recommendations with what we intend to deliver and support.

**Comment by thockin** [comment]
I'm going to close this, as it is not a "bug".
