### ISSUE TITLE
How to set max dead container and images number in kubernetes？

### ISSUE THREAD

**Issue by ttllyy** [kubernetes/kubernetes#12760]
@yujuhong 
#12713 I want to delete automatically dead docker container and images.
 if exceed  max dead container and images,  kubernetes  garbage collectors  self-delete automatically   exceeding limits dead container and images？
GC prior recovery oldest container and oldest images？
But in kubernetes, how to set max dead container？ how to set max dead container images？

Thanks!

**Comment by hw-qiaolei** [comment]
Hi ttllyy,
I do not have a test, but please refer to `kubelet` documentation at https://github.com/kubernetes/kubernetes/blob/8e05da1316bfdb15fd5193c9e70da0deea416010/docs/admin/kubelet.md, I think the following options helps:
`--maximum-dead-containers`
`-maximum-dead-containers-per-container`
`--minimum-container-ttl-duration`

**Comment by yujuhong** [comment]
@hw-qiaolei, thanks for answering the question! @ttllyy, you can set the flags to control the container garbage collection.

`minimum-container-ttl-duration` is set to avoid cleaning up the containers before kubelet gets to inspect the dead container. Also, because kubelet relies on examining the dead containers to construct the pod status, we want to keep a certain number of dead containers around (restart counts, etc). Hence, `-maximum-dead-containers-per-container` limits the maximum dead containers per container name in the pod.

**Comment by gmarek** [comment]
@ttllyy does this answer your question?

**Comment by yujuhong** [comment]
@ttllyy, I am closing this bug since it's inactive for over a week. Please follow #8416 for documenting GC policies. Thanks!
