### ISSUE TITLE
Kube-proxy scaling/perf

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#1277]
We should measure and (maybe) optimize kube-proxy at some point.  There are some fairly easy opportunities to make it more efficient.

**Comment by roberthbailey** [comment]
Also see #3760 for a performance optimization of the kube proxy.

**Comment by bgrant0607** [comment]
A benchmark would be useful. I had a chat with a user today about proxy performance problems.

@quinton-hoole

**Comment by wojtek-t** [comment]
This is extremely old issue and a lot has been done since then. Can we close it?

**Comment by josselin-c** [comment]
It's okay with me

-----Message d'origine-----
De : "Wojciech Tyczynski" <notifications@github.com>
Envoyé : ‎22/‎12/‎2015 16:36
À : "kubernetes/kubernetes" <kubernetes@noreply.github.com>
Cc : "josselin-c" <thecr3pe@gmail.com>
Objet : Re: [kubernetes] Kube-proxy scaling/perf (#1277)

This is extremely old issue and a lot has been done since then. Can we close it?
