### ISSUE TITLE
AWS: Document how to use private repositories

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#12794]
@andrewhampton suggested that the AWS docs incorporate how to use private repositories with AWS in #11938; I am splitting this off into a separate issue.

https://github.com/kubernetes/kubernetes/pull/11938#issuecomment-126395184

> Also, it would be nice to see how to add configuration to $HOME/.dockercfg for accessing private repositories as described here:
> https://github.com/GoogleCloudPlatform/kubernetes/blob/v1.0.1/docs/images.md#configuring-nodes-to-authenticate-to-a-private-repository

**Comment by andrewhampton** [comment]
I left this comment on #11938 as well, but this is probably a better place for it. I ended up using a secret instead of adding the .dockercfg to each minion. While it would be nice to have the option to deploy a .dockercfg to each server, I think the secret option is actually much cleaner since there's no need to make sure the file gets copied to new minions in the cluster.

Instructions on using secrets can be found here: https://github.com/kubernetes/kubernetes/blob/v1.0.1/docs/images.md#specifying-imagepullsecrets-on-a-pod
