### ISSUE TITLE
Need a 'reasonable' point at which monitor-resource should fail

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#12806]
Today failures (in the flaky suite) was caused by Docker Daemon CPU usage. Current limit is 0.1, which seems quite high for me, but it still fails. I saw values up to 0.4, which is ridiculous.

We need to decide what usage should trigger failures. The test is supposed to run on an 'empty' cluster (i.e. not in a parallel, and it's not starting anything). Currently it compares each node with the bound, which translates to test failing if maximum over the nodes is too high. This means that the test can be rather sensitive. To change that I can compare mean usage instead of max, which will mean that the test will fail only if something will be very wrong. Any opinions?

@dchen1107 @yujuhong @quinton-hoole @davidopp

**Comment by quinton-hoole** [comment]
To clarify, Docker Daemon is using 40% of a CPU core when no containers are running?  If so, that does indeed sound ridiculous, and warrants further investigation.

Having said that, a pragmatic immediate approach might be to set the limit for test failures to be slightly above whet we're seeing in practise right now (e.g. 0.5?), and work on reducing that limit as a separate issue.  That way at least we catch regressions now.

**Comment by gmarek** [comment]
Yup. Docker Daemon was using 40% of a CPU core when no containers were supposed to be running. It's in the Jenkins flaky suite run 3820. Scanning through other runs I saw Docker Daemon that were using more than 100% CPU (run 3815), and setting threshold this high seems... counterproductive.

**Comment by yujuhong** [comment]
Was there really no containers running at all? There are default addon pods in an e2e cluster (~14 containers). Depending on how the pods are split between the nodes, the cpu usage may vary too. Sometimes most pods would be scheduled on the node that registered first, causing the skew.

As for your test, I think the resource usage may fluctuate too much due to the sampling (5 sec * 5 times). Besides that, there is also the possibility that garbage collection may kick in at the time, skewing the results.

To provide a reference point, here are the results from [my test](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/kubelet.go#L163) in `test/e2e/kubelet.go` from three different builds. The cpu-usage of docker daemon seems to be more bounded. Note that I did not check all builds, but I looked at 5 more builds and they showed the similar pattern.

```

Aug 17 06:44:54.761: INFO: 
CPU usage of containers on node "e2e-gce-minion-5z38":
container        5th%  50th% 90th% 95th%
"/"              0.127 0.301 0.587 0.626
"/docker-daemon" 0.000 0.001 0.178 0.194
"/kubelet"       0.023 0.041 0.104 0.142
"/kube-proxy"    NaN   0.000 NaN   NaN
"/system"        0.000 0.000 0.024 0.032

Aug 17 06:44:54.761: INFO: 
CPU usage of containers on node "e2e-gce-minion-ngh4":
container        5th%  50th% 90th% 95th%
"/"              0.192 0.334 0.526 0.575
"/docker-daemon" 0.000 0.001 0.097 0.180
"/kubelet"       0.038 0.055 0.106 0.129
"/kube-proxy"    0.000 0.001 0.056 0.059
"/system"        0.000 0.000 0.027 0.031

Aug 17 06:44:54.761: INFO: 
CPU usage of containers on node "e2e-gce-minion-rgxu":
container        5th%  50th% 90th% 95th%
"/"              0.063 0.134 0.338 0.375
"/docker-daemon" 0.000 0.001 0.088 0.090
"/kubelet"       0.011 0.016 0.043 0.053
"/kube-proxy"    0.000 NaN   0.050 0.062
"/system"        0.000 0.000 0.026 0.027
```

```
Aug 17 05:46:05.288: INFO: 
CPU usage of containers on node "e2e-gce-minion-hm7r":
container        5th%  50th% 90th% 95th%
"/"              0.163 0.317 0.532 0.585
"/docker-daemon" 0.000 0.001 0.101 0.225
"/kubelet"       0.030 0.048 0.111 0.124
"/kube-proxy"    0.000 0.000 0.002 0.000
"/system"        0.000 0.000 0.028 0.031

Aug 17 05:46:05.288: INFO: 
CPU usage of containers on node "e2e-gce-minion-on2j":
container        5th%  50th% 90th% 95th%
"/"              0.060 0.136 0.314 0.347
"/docker-daemon" 0.000 0.000 0.073 0.077
"/kubelet"       0.008 0.014 0.035 0.041
"/kube-proxy"    0.000 0.000 0.028 0.029
"/system"        0.000 0.000 0.026 0.027

Aug 17 05:46:05.288: INFO: 
CPU usage of containers on node "e2e-gce-minion-tpp9":
container        5th%  50th% 90th% 95th%
"/"              0.170 0.293 0.566 0.613
"/docker-daemon" 0.000 0.001 0.056 0.059
"/kubelet"       0.028 0.040 0.072 0.075
"/kube-proxy"    0.000 0.002 NaN   0.028
"/system"        0.000 0.000 0.013 0.026
```

```

Aug 17 08:49:25.880: INFO: 
CPU usage of containers on node "e2e-gce-minion-6r7c":
container        5th%  50th% 90th% 95th%
"/"              0.169 0.317 0.519 0.578
"/docker-daemon" 0.000 0.001 0.100 0.183
"/kubelet"       0.031 0.042 0.104 0.115
"/kube-proxy"    0.000 0.000 0.070 0.080
"/system"        0.000 0.000 0.016 0.027

Aug 17 08:49:25.880: INFO: 
CPU usage of containers on node "e2e-gce-minion-631y":
container        5th%  50th% 90th% 95th%
"/"              0.104 0.223 0.406 0.519
"/docker-daemon" 0.000 0.000 0.096 0.151
"/kubelet"       0.019 0.028 0.078 0.106
"/kube-proxy"    0.000 0.002 NaN   0.029
"/system"        0.000 0.000 0.009 0.025

Aug 17 08:49:25.880: INFO: 
CPU usage of containers on node "e2e-gce-minion-68d0":
container        5th%  50th% 90th% 95th%
"/"              0.126 0.250 0.409 0.459
"/docker-daemon" 0.000 0.001 0.111 0.159
"/kubelet"       0.029 0.049 0.096 0.108
"/kube-proxy"    0.000 0.000 0.028 0.030
"/system"        0.000 0.000 0.017 0.026
```

**Comment by dchen1107** [comment]
Sigh! It is known issue when running some docker operations, like docker load, docker daemon uses tons of CPU. Also docker daemon has memory leakage issue badly (Even in docker 1.7.1.), but that is out of the scope here. 

Also please note that for all resource-only containers, like docker daemon, kubelet, and kube-proxy, currently we allocate them with default cpu shares, (1024), and without hard capping, which means if nothing else is scheduled by kernel at any giving time, each one of them could use up to one core cpu. 

But what you reported above like more than 100% CPU, I think it might be caused by too small set of sample data? Maybe we can collect more data at TearDown stage on Failure, like profiling docker?

**Comment by gmarek** [comment]
Thanks @yujuhong - IIUC you're using 1 minute intervals, which will indeed be much smoother, but I don't think 5 * 5 sec is too short. Especially if an average is over 100%. Of course by 'no pods' I meant 'no user pods' - system Pods were running as always.

Maybe you can fail kubelet test if Xth percentile is above Y (for some X and Y)?

**Comment by gmarek** [comment]
@dchen1107 - the goal of this test is to allow monitoring of how bad Docker Daemon is hurting us and to notice regression in other components - I'm thinking about adding a FluentD container to the list... I think that some level of flakyness is to be expected.

If we're allocating Docker, Kubelet and KubeProxy 1024 shares, then if all of they go haywire it leave only a  1/4 of a CPU left for user, which is bad (probably), but that's another issue.

**Comment by dchen1107** [comment]
@yujuhong Thanks! From what you reported, the usage of /docker-daemon, /kubelet, /kube-proxy and /system is much saner. But /root cgroup usage seems pretty high. I am wondering if there some processes are not moved in proper subcgroups. It is hard to believe kernel threads are using that much cpu. 

@gmarek I decided to leave all those resource-only containers with 1024 CPU shares by default for 1.0 because:

* That is a default value from kernel for a given cpu cgroup. We created those cgroups for monitoring first, so that we can understand their resource usage pattern better.
* We know docker daemon 1.6.2 is using a lot of CPU. Based on my monitoring data from soaking tests, docker 1.7.1 improves a lot.
* Kubelet depends on docker daemon tightly, and capping docker's cpu usage just simply make node NotReady. We plan to fix this in 1.1 by using event stream instead of heavy docker operations.
* There is no resource management, no QoS targeted for 1.0 release. All I have done on the node is trying to avoid really bad out-of-resource case. Pod / Container Resource limit / request is not mandatory, and there is no way to prevent overcommitted user containers from starving our daemons. In that case, I would rather to starve the users since that is their choice :-P
* There is no mechanism to provision daemons' resource requests. And scheduler doesn't take those reservation into account too.

**Comment by yujuhong** [comment]
> Thanks @yujuhong - IIUC you're using 1 minute intervals, which will indeed be much smoother, but I don't think 5 * 5 sec is too short. Especially if an average is over 100%. Of course by 'no pods' I meant 'no user pods' - system Pods were running as always.

No problem. Using a longer period definitely helps.
 
Another difference is that you collect some 5-second samples, which may be quite high if you're unlucky (what if you always sample when kubelet is syncing?). My test polls every 5 second and calculate the cpu usage by subtracting the cpu seconds in the past period, so it'd get a better picture the overall usage.

The problem with system pods is that, like I mentioned in the previous comment, that they can be mostly scheduled on one node. Having 10 pods running on one node vs 1 pod lead to very different cpu usage, even though there are not user pods.


> Maybe you can fail kubelet test if Xth percentile is above Y (for some X and Y)?

I agree. Using percentiles are probably safer in this case.

**Comment by quinton-hoole** [comment]
@gmarek it's not clear to me which e2e tests were failing here?  Are they still failing?  Or can we close this issue (from a test point of view)?

**Comment by gmarek** [comment]
ResourceUsage test. It's pretty quiet recently, but we may need to revisit it in the future.
