### ISSUE TITLE
e2e scalability test is flaky with "There should be no high-latency requests"

### ISSUE THREAD

**Issue by quinton-hoole** [kubernetes/kubernetes#12801]
e.g. kubernetes-e2e-gce-scalability/2160

[Performance suite] should allow starting 30 pods per node

/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/density.go:155
There should be no high-latency requests
Expected
    <int>: 1
not to be >
    <int>: 0

@fgrzadkowski Do you know whether anyone on your team looking into this?

**Comment by fgrzadkowski** [comment]
@wojtek-t Can you please take a look?

**Comment by wojtek-t** [comment]
Yes - I'm monitoring those tests.

The problem is that there is significant variation in the metrics (~2s). We can increase the limit, but I wanted to avoid it - I prefer to look into failures manually now than to allow regression that we won't notice.

I hope that switching on watch in apiserver should significantly help with that. Once this is in (I hope this will happen this week) we can tune the limits to avoid such a huge flakiness in those tests.

For now, I'm just leaving this open.

**Comment by wojtek-t** [comment]
This is no longer a problem
