### ISSUE TITLE
https://pkgs.k8s.io/core:/stable:/v1.27/deb/Release.key is expired

### ISSUE THREAD

**Issue by broken-ufa** [kubernetes/kubernetes#128567]
### What happened?

According to https://v1-27.docs.kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/
I'm trying to install kubeadm with repo https://pkgs.k8s.io/core:/stable:/v1.27/deb/

The following signatures were invalid: EXPKEYSIG 234654DA9A296436 isv:kubernetes OBS Project <isv:kubernetes@build.opensuse.org>, E:The repository 'https://pkgs.k8s.io/core:/stable:/v1.27/deb  InRelease' is not signed

### What did you expect to happen?

Repo should work

### How can we reproduce it (as minimally and precisely as possible)?

```
wget https://pkgs.k8s.io/core:/stable:/v1.27/deb/Release.key
# gpg --show-keys Release.key
pub   rsa2048 2022-08-25 [SC] [expired: 2024-11-02]
      DE15B14486CD377B9E876E1A234654DA9A296436
uid                      isv:kubernetes OBS Project <isv:kubernetes@build.opensuse.org>
```

### Kubernetes version

<details>
1.27
</details>

### Cloud provider

baremetal

### Related plugins (CNI, CSI, ...) and versions (if applicable)

deb repo

**Comment by dims** [comment]
1.27 is end of life-ed already https://endoflife.date/kubernetes

/close

**Comment by mpern** [comment]
in case anyone else stumbles across this:

update the signing key and apt repository as described here:

https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/#install-using-native-package-management

(overwrite all existing files)

**Comment by mddavisjha** [comment]
You don't have to download the 1.27 key.  You can download the 1.28 key instead and it works fine (it's the same signing key).
In the example below you can see that I'm going to be installing 1.27, but I'm downloading the 1.28 key which is properly signed.  Run the below, then do apt-get update and it should work fine getting 1.27 for you.
As for saying "1.27 is EOL" that is not a valid response, because in order to upgrade to the newest versions, we have to go through 1.27 to get to 1.28, which is how I ran into this error myself and finally figured out the solution below.

mkdir /etc/apt/keyrings
echo "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.27/deb/ /" | sudo tee /etc/apt/sources.list.d/kubernetes.list
curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
sudo chmod 755 /etc/apt/keyrings
sudo chmod 644 /etc/apt/keyrings/kubernetes-apt-keyring.gpg

**Comment by fario97** [comment]
> You don't have to download the 1.27 key. You can download the 1.28 key instead and it works fine (it's the same signing key). In the example below you can see that I'm going to be installing 1.27, but I'm downloading the 1.28 key which is properly signed. Run the below, then do apt-get update and it should work fine getting 1.27 for you. As for saying "1.27 is EOL" that is not a valid response, because in order to upgrade to the newest versions, we have to go through 1.27 to get to 1.28, which is how I ran into this error myself and finally figured out the solution below.
> 
> mkdir /etc/apt/keyrings echo "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.27/deb/ /" | sudo tee /etc/apt/sources.list.d/kubernetes.list curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg sudo chmod 755 /etc/apt/keyrings sudo chmod 644 /etc/apt/keyrings/kubernetes-apt-keyring.gpg

Still working nowadays, thank you!
