### ISSUE TITLE
[CVE-2024-45337] x/crypto/ssh: misuse of ServerConfig.PublicKeyCallback may cause authorization bypass

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#129164]
Note from golang team:
https://groups.google.com/g/golang-announce/c/-nPEi39gI4Q/m/cGVPJCqdAQAJ

Our use of the package:
```
❯ rg 'crypto/ssh"'
test/e2e/framework/ssh/ssh.go
31:     "golang.org/x/crypto/ssh"
```

the fix golang team applied:
https://github.com/golang/crypto/compare/v0.30.0...v0.31.0

Based on code inspection and the comments in the code itself:
https://github.com/golang/crypto/commit/b4f1988a35dee11ec3e05d6bf3e90b695fbd8909#diff-e951878a83c4f8e454f545a1a2880f387705de79b3272105eab50d18f0dc52b3R162-R165

Only the folks who are using `PublicKeyCallback` API are affected. We don't use that API in kubernetes/kubernetes and our only use of the entire package is in a test suite.

Based on the above, deliverables/binaries from kubernetes/kubernetes are NOT affected.

**Comment by dims** [comment]
Confirmed that the `vulndb` tags usage of `PublicKeyCallback` correctly:
https://go-review.googlesource.com/c/vulndb/+/635257/3/data/reports/GO-2024-3321.yaml#10

So when we ship 1.32.0 (or existing versions of k8s!), we should not see `govulncheck` failures!

**Comment by BenTheElder** [comment]
> We don't use that API in kubernetes/kubernetes and our only use of the entire package is in a test suite.

more specifically: we only use the ssh client in a test suite to access temporary test VMs, we don't have any attempts at implementing an ssh server at all, let alone that specific functionality.

**Comment by dims** [comment]
xref: https://github.com/golang/go/issues/70779#issuecomment-2540035412

**Comment by BenTheElder** [comment]
I think keeping this issue open is inviting the assumption that Kubernetes is impacted?

**Comment by BenTheElder** [comment]
Not specific to this issue, but we really need a process for ACK/NACK on this sort of thing. xref https://github.com/kubernetes/sig-security/issues/116

**Comment by dims** [comment]
@BenTheElder i want to land a PR to update x/crypto/ssh to latest in master and close this. Inevitably when folks come looking for a backport, this issue will serve as the answer why we wont.

**Comment by pbxqdown** [comment]
We run into similar issue in our stack. New vulns frequently reported by security scanner. Usually we either update the package to fix vuln or create an exception explaining the situation. 

May be good if community can create an exception list for false positive vuln? Since it is official from Kubernetes community, it would be easier for downstream projects to reference and create exception accordingly.

**Comment by BenTheElder** [comment]
> May be good if community can create an exception list for false positive vuln? Since it is official from Kubernetes community, it would be easier for downstream projects to reference and create exception accordingly.

https://github.com/kubernetes/kubernetes/issues/129164#issuecomment-2540203046 / https://github.com/kubernetes/sig-security/issues/116

Though also, if you run a symbol aware scanner like govulncheck it will accurately reflect that this CVE does not apply.

**Comment by dims** [comment]
cc https://github.com/kubernetes/kubernetes/issues/121454 for `Set up VEX to eliminate false-positives from vulnerability scanning tool results`

**Comment by ritazh** [comment]
cc @puerco @itaysk @knqyf263

**Comment by sarahhodne** [comment]
From the comments in this ticket, it sounds like govulncheck shouldn't flag this on the official Kubernetes binaries, but I'm seeing it flagged on the 1.32.2 kubelet binary (as well as several older binaries, we're actually using the EKS 1.30.9 binary at the moment, which also exhibits this, but I wanted to verify with the latest release as well):

```
$ govulncheck -mode=binary ./kubelet-linux-arm64-1.32.2
=== Symbol Results ===

[…snip…]

Vulnerability #2: GO-2024-3321
    Misuse of ServerConfig.PublicKeyCallback may cause authorization bypass in
    golang.org/x/crypto
  More info: https://pkg.go.dev/vuln/GO-2024-3321
  Module: golang.org/x/crypto
    Found in: golang.org/x/crypto@v0.28.0
    Fixed in: golang.org/x/crypto@v0.31.0
    Vulnerable symbols found:
      #1: ssh.ServerConfig.PublicKeyCallback

[…snip…]

$ sha256sum kubelet-linux-arm64-1.32.2
d74b659bbde5adf919529d079975900e51e10bc807f0fda9dc9f6bb07c4a3a7b  kubelet-linux-arm64-1.32.2
```

This is being flagged by our vulnerability management software, and while I am working on getting an exception for this since it sounds like a false positive, I just wanted to double check that I hadn't misunderstood something and `govulncheck` flagging this in the binary is actually expected?

**Comment by sftim** [comment]
AIUI: having `ssh.ServerConfig.PublicKeyCallback` in a binary doesn't mean that the call is being misused.

However, I wonder why the **kubelet** even handles SSH public keys. That seems odd.

**Comment by macedogm** [comment]
@sarahhodne after working quite a bit with govulncheck in order to "VEX at scale" in SUSE Rancher, my understanding is that when using govulncheck in binary mode, it will only correctly be able to identify and remove the false-positives if the binary has the debug symbols. If the binary had its debug symbols stripped, then govulncheck will flag all the possible CVEs.

Can you check yours `./kubelet-linux-arm64-1.32.2`?

```
> file kubelet 
kubelet: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, Go BuildID=jKr3kPDJMdWlwicuCmqs/4VhSCaGK4Ls5SEJhlktY/TaQ3jniMlj40OVhXmVCQ/8N9lYL2wSl9_gDw3_5s3, stripped
```

When the binary is stripped, you need to run govulncheck in the default source mode against the source code to be sure about the false-positives.

**Comment by macedogm** [comment]
I compiled `kubelet` locally and govulncheck removed the known false-positives:

```
/tmp/kubernetes/cmd/kubelet> ls -lh
total 109M
drwxr-xr-x 1 gmacedo gmacedo  430 Feb 12 18:19 app
-rwxr-xr-x 1 gmacedo gmacedo 109M Feb 19 08:22 kubelet
-rw-r--r-- 1 gmacedo gmacedo 1.5K Feb 12 18:19 kubelet.go
-rw-r--r-- 1 gmacedo gmacedo  377 Feb 12 18:19 OWNERS
/tmp/kubernetes/cmd/kubelet> file kubelet
kubelet: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, Go BuildID=JLEKxXDu5Sm2rJyRdC01/5DOTAfk-L4PjXhmalOwx/QhD2mMt4p_Q00yPnXB4k/zuej3KEc0x1YYEIOUkVc, with debug_info, not stripped
/tmp/tmo/kubernetes/cmd/kubelet> ~/code/github.com/macedogm/vuln/govulncheck -mode binary kubelet
=== Symbol Results ===

No vulnerabilities found.

Your code is affected by 0 vulnerabilities.
This scan also found 1 vulnerability in packages you import and 2
vulnerabilities in modules you require, but your code doesn't appear to call
these vulnerabilities.
Use '-show verbose' for more details.
```

**Comment by sarahhodne** [comment]
Ah yes, it is indeed a stripped binary:

```
$ file ./kubelet-linux-arm64-1.32.2
./kubelet-linux-arm64-1.32.2: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, Go BuildID=jKr3kPDJMdWlwicuCmqs/4VhSCaGK4Ls5SEJhlktY/TaQ3jniMlj40OVhXmVCQ/8N9lYL2wSl9_gDw3_5s3, stripped
```

Sounds like this is expected then and govulncheck probably can't correctly ignore this issue (in prod we're using the binaries provided by Amazon EKS, and trying to compile our own just to appease the vulnerability scanner seems overkill. We have an exception in place for this now so it's not a big issue, I just wanted to make sure I hadn't missed something.

Thanks for the explanation!

**Comment by macedogm** [comment]
> Sounds like this is expected then and govulncheck probably can't correctly ignore this issue

Yes, because the stripped binaries miss the symbols that are need for govulncheck to correctly find the used from the non-used symbols (which are the false-positives).


> trying to compile our own just to appease the vulnerability scanner seems overkill.

True. You can try inspecting the binaries provided by Amazon to check if they have `path` and `vcs.revision` data. If yes, a logic can be build to retrieve the upstream source code at the right revision point, then run govulncheck in binary mode.

```
/tmp> go version -m kubernetes/server/bin/kubelet | grep path
	path	k8s.io/kubernetes/cmd/kubelet
	dep	github.com/cyphar/filepath-securejoin	v0.3.4	
	build	-trimpath=true
/tmp> go version -m kubernetes/server/bin/kubelet | grep vcs.revision
	build	vcs.revision=67a30c0adcf52bd3f56ff0893ce19966be12991f
```

Yes, it's overkill too, but just sharing some ideas in case you need. That is essentially what we do to VEX@scal in https://github.com/rancher/vexhub/.

**Comment by nevetS** [comment]
> Yes, because the stripped binaries miss the symbols that are need for govulncheck to correctly find the used from the non-used symbols (which are the false-positives).

If this is only used for tests, the library shouldn't be included in the release binaries.

The CVE is CRITICAL, which means this is getting attention from everyone.  

Personally, I'd much prefer to "know it's fine because that library has been updated or isn't included in software I'm responsible for" instead of "I saw a github issue response where there was discussion and a couple of people decided it was really a non-issue so they aren't creating a fix".  I don't think compiling this locally and then deploying is a good solution either.

I think any CRITICAL level CVE should be addressed and backported to supported versions, even if it's something that looks to be innocuous on initial review.

**Comment by BenTheElder** [comment]
> If this is only used for tests, the library shouldn't be included in the release binaries.

It isn't included in any production binaries. If you build a non-stripped kubelet with debug symbols you can verify this, see above.

> The CVE is CRITICAL, which means this is getting attention from everyone.

If you check above, you can see that we've already responded to it.

> Personally, I'd much prefer to "know it's fine because that library has been updated or isn't included in software I'm responsible for" instead of "I saw a github issue response where there was discussion and a couple of people decided it was really a non-issue so they aren't creating a fix". I don't think compiling this locally and then deploying is a good solution either.
> 
> I think any CRITICAL level CVE should be addressed and backported to supported versions, even if it's something that looks to be innocuous on initial review.


The entire crypto/ssh library is only used for a tests-only package, which is not part of any of the runtime binaries, only a test-only binary (end to end tests).

Even within that binary, the relevant symbol is not used at all, we don't run an ssh server at all, only an SSH client in some tests.

Anything detecting our release binaries as being affected by this symbol is depending only on the version of kubernetes and falsely assuming it uses this symbol.

No part of this repo ever used the vulnerable symbol.

IMHO the databases should reflect this, you don't even need to load the symbols from a non-stripped binary, because this symbol was never used and that could've been verified from the sources, the same way the binaries are falsely being flagged as having this symbol because the version of those binaries matches some source that imports *the package* but not the symbol.

**Comment by BenTheElder** [comment]
See the OP:
https://github.com/kubernetes/kubernetes/issues/129164#issue-2733790498

We use `vendor`, so we can verify that even across dependencies, `crypto/ssh` is only imported under `test/e2e` where we build `test/e2e/e2e.test`, a binary that is used to test clusters.

`test/e2e` is not imported by the rest of the repo and we have restrictions in place to prevent this.

Even within `test/e2e/...` we are only using an ssh client for some tests. 

There are no ssh servers, so we can't have this vulnerable server callback.

We only bump dependencies on release branches when there is a real bug or vulnerability, because upgrading them risks regressions, and patch releases are supposed to be especially safe upgrades. 

There is no actual vulnerability in Kubernetes, so it's not eligible.

https://github.com/kubernetes/community/blob/master/contributors/devel/sig-release/cherry-picks.md#what-kind-of-prs-are-good-for-cherry-picks

**Comment by dims** [comment]
@nevetS please feel free to patch whichever versions of kubernetes you use. as we repeatedly point out since the beginning of this issue - `There is no actual vulnerability in Kubernetes, so it's not eligible.`
