### ISSUE TITLE
Backport policy: Backport misc client improvements?

### ISSUE THREAD

**Issue by zmerlynn** [kubernetes/kubernetes#12932]
See #12734

We need to codify the patch release policy. I think there's general tribal consensus on the server side to hold the line for `release-1.0` on random improvements, but what about the client?

cc @bgrant0607 @jlowdermilk @stefwalter

**Comment by bgrant0607** [comment]
cc @erictune

**Comment by bgrant0607** [comment]
Conceptually we could release the client more frequently, but I don't think we have the manpower to do it.

**Comment by stefwalter** [comment]
If contributors have to wait 12 to 16 weeks before a pull request makes it into a release (even an unstable one) ... not to then mention the time it takes for that release to be shipped in a package, dependent software to be updated, and then and possibly productized ... then the Kubernetes community is going to be hindered by this.

(Note I'm using #10608 as an example here, and the October schedule mentioned by @bgrant0607 for 1.1)

I know continuous delivery is hard ... but in today's world the "release overhead" in projects needs to be trending down ... so that it does not become a problem to release more frequently.

CC @eparis @smarterclayton @ncdc

**Comment by zmerlynn** [comment]
@stefwalter: The intention was to start pushing out `1.1.0-alpha.x` release builds on a biweekly basis. That hasn't happened yet, because we've all been kind of heads down on other things. `master` is tagged at `1.1.0-alpha.0`, and I was going write additional tooling to retag the additional `.x` bits and push the builds somewhere, but that hasn't been done. So we *will* have unstable builds published soon.

You can already grab arbitrary continuous integration builds from `master` already if you want to live more dangerously, and we have markers from "latest green" to make it easier. The stuff I mention about `1.1.0-alpha.0` builds is really about offering *slightly* more stable builds (we would at first choose an arbitrary green build to escalate, but we'd like to do additional validation at some point).

**Comment by brendandburns** [comment]
I'm going to close this for now.  We have the alpha releases, people can download kubectl from there if they really want to.  I think rev-ing client and server together is the state of the art.  If there are specific kubectl features people want, they can request a cherry-pick into the 1.0 branch.

We'd like to move to continuous delivery for all components in the limit, but for now this is the state of the art.
