### ISSUE TITLE
Is there python client library for kubernetes?

### ISSUE THREAD

**Issue by ttllyy** [kubernetes/kubernetes#12958]
kubernetes/docs/devel/client-libraries.md:

Libraries provided (go, java, node.js, ruby, perl ) client.
Is there readily available python client library or in future?

**Comment by brosner** [comment]
I am actively working on a Python client at https://github.com/eldarion-gondor/pykube

**Comment by bgrant0607** [comment]
Please direct your questions to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes). 

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases. 

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to similar questions, and also familiarize yourself with:
  * [the user guide](http://kubernetes.io/v1.0/)
  * [the troubleshooting guide](http://kubernetes.io/v1.0/docs/troubleshooting.html)

cc @madhuri-rai07 worked on one generated from swagger
