### ISSUE TITLE
Wordpress recreating every 6 minutes.

### ISSUE THREAD

**Issue by adyanthaya17** [kubernetes/kubernetes#12973]
Hi,

I downloaded wordpress docker image and have brought up the pod in the kubernetes cluster but it keeps recreating itself when I check the docker ps -a. Can anyone tell me as to how to stop the recreation?

It seems like the container is getting killed for every 6 minutes and a new container is taking it's place.

**Comment by saad-ali** [comment]
Please direct your questions to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes). 

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases. 

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to similar questions, and also familiarize yourself with:
  * [the user guide](http://kubernetes.io/v1.0/)
  * [the troubleshooting guide](http://kubernetes.io/v1.0/docs/troubleshooting.html)

Again, thanks for using Kubernetes.

The Kubernetes Team
