### ISSUE TITLE
Cannot create priviledged containers

### ISSUE THREAD

**Issue by sameersbn** [kubernetes/kubernetes#12983]
I am using instructions from https://github.com/kubernetes/kubernetes/blob/master/docs/getting-started-guides/docker-multinode.md to setup a multinode kubernetes cluster on vmware vcloud infrastructure.

I was able to get the cluster working but when I tried the [nfs example](https://github.com/kubernetes/kubernetes/tree/master/examples/nfs) I was not able to create the nfs container. So I recreated all the VMs and rebuilt kubernetes from source using:

```bash
git clone https://github.com/kubernetes/kubernetes.git
cd kubernetes
sed -i 's/allow_privileged: .*/allow_privileged: true/g' cluster/saltbase/pillar/privilege.sls
./build/run.sh hack/build-cross.sh
cp _output/dockerized/bin/linux/$(dpkg --print-architecture)/kubectl /usr/local/bin
chmod +x /usr/local/bin/kubectl
```
and continued to setup the kubernetes cluster and retried the NFS example and I get the following error:

```bash
kubectl create -f nfs-server-pod.yaml 
The Pod "nfs-server" is invalid.
spec.containers[0].securityContext.privileged: forbidden '<*>(0xc20931650c)true'
```

I tried with both the `master` and `1.0.3` release and had the same result.

Can you please tell me how to resolve this issue and Thanks for your support

**Comment by saad-ali** [comment]
Please direct your questions to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes). 

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases. 

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to similar questions, and also familiarize yourself with:
  * [the user guide](http://kubernetes.io/v1.0/)
  * [the troubleshooting guide](http://kubernetes.io/v1.0/docs/troubleshooting.html)

Again, thanks for using Kubernetes.

The Kubernetes Team

**Comment by sameersbn** [comment]
http://stackoverflow.com/questions/32131906/cannot-create-priviledged-containers. Thanks!
