### ISSUE TITLE
No enough space when build kubernetes in CoreOS

### ISSUE THREAD

**Issue by JackChen255** [kubernetes/kubernetes#12995]
Hi all,
I always meet insufficient space issue when building kubernetes in CoreOS as below. And actually there are much free space available in my virtual machine. It seems kubernetes building process tries to write files to /usr/..., and /usr is mounted to /dev/loop0 which is fully used. Any one can help on it?

git clone https://github.com/GoogleCloudPlatform/kubernetes.git
cd kubernetes/build/
./make-build-image.sh
write error: No space left on device
go tool dist: FAILED: /usr/src/go/pkg/tool/linux_amd64/6l -o /usr/src/go/pkg/tool/linux_amd64/go_bootstrap $WORK/_go_.a

localhost build # df -h
Filesystem      Size  Used Avail Use% Mounted on
devtmpfs        1.9G     0  1.9G   0% /dev
tmpfs           2.0G     0  2.0G   0% /dev/shm
tmpfs           2.0G   17M  2.0G   1% /run
tmpfs           2.0G     0  2.0G   0% /sys/fs/cgroup
tmpfs           2.0G  2.0G  1.4M 100% /
/dev/loop0      144M  144M     0 100% /usr
tmpfs           2.0G     0  2.0G   0% /media
tmpfs           2.0G     0  2.0G   0% /tmp

localhost build # lvextend /dev/loop0 -L 1G
  Path required for Logical Volume "loop0"
  Please provide a volume group name
  Run `lvextend --help' for more information.

**Comment by goltermann** [comment]
We’re going through old support issues and asking everyone to direct your questions to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes). 

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases. 

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

**Comment by erictune** [comment]
I ran into this today.
