### ISSUE TITLE
Kubernetes cluster set up script for azure loops for ever

### ISSUE THREAD

**Issue by biswars** [kubernetes/kubernetes#13027]
Kubernetes version used: 1.0.3
Cloud Provider: Azure

kube-up.sh for azure is run and everything seems to be successful. The nodes are created and can be seen in the azure portal. However, it then loops for ever stating "This might loop forever if there was some uncaught error during start" while trying to connect to the api server.

The problem for me is when I try to SSH to the master node (details as seen in the azure portal with ssh port), it says "permission denied (publickey)". There is no means to debug and see what had happened unless there is provision to log in to the master node.

Is there any configuration change to be made for the nodes to be SSHed either by key or credentials ?

**Comment by goltermann** [comment]
We’re going through support issues and asking everyone to direct your questions to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes). 

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases. 

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.
