### ISSUE TITLE
Kubernetes on AWS should be Multi-AZ by default

### ISSUE THREAD

**Issue by erulabs** [kubernetes/kubernetes#13056]
Hello!

  I thought I'd open an issue, as I am currently working on this and hope to have a commit ready by the end of the day.

  "kube-up" with AWS ought to build out a highly available and multi-AZ kubernetes cluster following AWS EC2 best practices. There are two large steps to this:

  1. Multi-AZ minions
  2. Highly available / Multi-AZ master

I am only focusing on goal #1 here. These changes center entirely in cluster/aws/util.sh. However, I will need to modify the actual provider code in Go because, while AWS ELBs are brought up with the proper subnets, it appears they do not have multi-availability zone routing enabled.

  I am leaving the security groups in place and creating a secondary subnet and secondary autoscaling group. NUM_MINIONS is now split into NUM_MINIONS_PRIMARY_ZONE and NUM_MINIONS_SECONDARY_ZONE. The default AWS_REGION of "us-east-1" is supplemented by AWS_ZONE_PRIMARY of "a" and AWS_ZONE_SECONDARY of "c" (us-east-1 has no "b"...)

  I wanted to pop this issue to collect thoughts from AWS users. If anyone is already doing multi-AZ kubernetes cluster, please let me know if you have run into any edge cases! I will issue a PR for this very shortly.

Thanks!

**Comment by justinsb** [comment]
So I think this is wonderful.  I think another important challenge will be to run etcd HA (i.e. multi-AZ).

To fill you in on some of the background here, I think there are two schools of thought when it comes to multi-AZ.  The first says that a k8s cluster should run out-of-the-box in multiple AZs.  The other says that you should actually run multiple k8s clusters, one per AZ, and somehow run services across multiple clusters ("ubernetes").

The advantages of a multi-AZ k8s are fairly clear: simplicity out of the box.  The advantages of cluster-per-AZ are that you can upgrade each cluster independently, that you can survive bugs in a cluster (e.g. if we had a bug that erased everything in an etcd), and that HA is often itself the source of problems.

I used to be in the ubernetes camp, but I think my view has softened: both scenarios are very important, and maybe at this stage the first scenario is more important.  The first scenario is much more practical for easy adoption at the moment, and over time the biggest deployments will likely move to the latter configuration, particularly as we build out the ubernetes support.

So I am very glad that you have started this work.  I don't think we should make it the default until we have tested and proved it out, but once we have I am in favor of doing so, or at least making it easy (I worry that a minimal multi-AZ cluster will be many more machines).

AFAIK, GCE does not run multi-AZ either.  We should also coordinate with any efforts there.  @brendandburns can you point us to any comparable multi-AZ GCE efforts?  (And also I think you will be interested in this for AWS)

**Comment by davidopp** [comment]
@quinton-hoole has been leading the design efforts for multi-AZ. His Ubernetes doc has a very nice discussion of the pros and cons of the two schools of thought you mentioned. We'd certainly be interested in getting feedback from folks on these two models, as there is a lively debate about how to prioritize the efforts.

https://github.com/kubernetes/kubernetes/blob/master/docs/proposals/federation.md

**Comment by justinsb** [comment]
@quinton-hoole is there a group that is planning on discussing these issues?  I think I have lots of thoughts on the importance on multi-AZ single-clusters, along with ideas for ubernetes (for example, I was thinking we could create a cluster object that represents 'foreign' clusters, and then enlightened containers could create services that span clusters)

**Comment by quinton-hoole** [comment]
@justinsb what perfect timing for your question :-)

I created the [Kubernetes Federation special interest group](https://groups.google.com/forum/#!forum/kubernetes-sig-federation) yesterday.

Are you a member of [kubernetes-dev](https://groups.google.com/forum/#!forum/kubernetes-dev) and/or [kubernetes-announce](https://groups.google.com/forum/#!forum/kubernetes-announce) ?  The SIG was announced there yesterday.

**Comment by davidopp** [comment]
See also
https://github.com/kubernetes/kubernetes/tree/master/examples/sharing-clusters

**Comment by benmccann** [comment]
I'll throw my 2 cents in here for now (though happy to move conversation to the mailing list or elsewhere).

I'd prefer both models being supported as well. [@justinsb summed up my thoughts on the matter almost perfectly](https://github.com/kubernetes/kubernetes/issues/13056#issuecomment-133625145). This is the main thing that's held me back from really jumping on to k8s and I'd potentially be willing to contribute in this area. I'd like to think through the ways we might be able to accomplish it a bit as there potentially could be very little we'd have to add.

One way to do this that might be nice would be to be able to specify in the replication controller spec not just a number of instances, but also which zone you want them to live in. E.g. you could have a line like:

    replicas: {us-west-2a:2, us-west-2b:2, us-west-2c:2}

(Right now `replicas` is purely an int. I'm not familiar with the Go YAML parser being used and whether it's possible to have a value than can be either an int or a map, but this gets the idea across even if we have to implement it some other way)

The benefit of this is that it would solve the question of how to handle the persistent disks that @erulabs mentioned (volumes in AWS at least need to remain in an AZ unless we want to deal with snapshotting them and moving them to another AZ). It would also make it such that the scheduler doesn't need to have any concepts like spreading instances such that they not only avoid living on the same machine, but also such that they don't live in the same AZ (or alternatively that they do live in the same AZ for slightly reduced latency - it's roughly 3ms within an AZ and 9ms across AZs in a region).

**Comment by erulabs** [comment]
I'd like to leave some documentation for any readers about my current thoughts on this. It seems to be, after much experimentation, that the benefits of a more complex Kubernetes (MultiAZ/HA cluster out of the box) are outweighed by the benefits of "confederated" Kubernetes clusters (aka "ubernetes").

Part of the benefit is that the Kubernetes API is extraordinarily wonderful to work with, as APIs go - and writing in-house tools for managing multiple clusters has so far been awesome. I have big plans for a tool for working with multiple Kubernetes clusters across multiple AWS data centers and availability zones.

I will try to find time clean up and publish some documentation regarding a single HA/MultiAZ Kubernetes on AWS (and if you really want to go down this path feel free to reach out to me), but the problem of persistent disks means making very complex changes to the scheduler - particularly if one wanted to scale the idea to multiple data centers, where you have much vaster problems than just EBS. The added complexity to Kubernetes isn't worth the effort and maintenance costs. At least for me, this turned out to be a huge rabbit hole.

On the other hand, "Ubernetes" is wonderful. It makes managing geographically distinct regions much more sensible. My current design involves a small service which runs on the Kubernetes masters and continually checks to ensure the sum total of pods in identical replication controllers across multiple clusters is OK. "Ensure I have 6 pods, at least 2 in at least 3 regions" etc. Should EAST-1 go down, EAST-2 and WEST-1 will both add +1 pod to their replication controllers.

While I'll be paying attention to this thread, and do plan on revisiting a single cluster in 2 AZs as soon as I can, I wanted to share my findings.

**Comment by quinton-hoole** [comment]
@erulabs Thanks for your hard-won feedback. Your experience very much mirrors mine in the sense that the conceptually simple "Multi-AZ Kubernetes" in practise generates a lot of complexity, both in the Kubernetes API, as well as in the underlying implementation.  I tried to capture most of that in the [Kubernetes Cluster Federation](https://github.com/kubernetes/kubernetes/blob/master/docs/proposals/federation.md) proposal.  Please do feel free to add additional thoughts/observations there.

Having said that, there does appear to be at least some demand for a "highly dumbed down" option to run Multi-AZ Kubernetes, even if it does come with severe caveats like "PD's simply don't schedule" and "inter-pod network connectivity is unpredictable" and other similar restrictions.  I plan to make time to work on a proof of concept of the latter soon, as pre-cursor to a more full-blown "Ubernetes" implementation, which will take longer to build.  Eventually I envision that users will have both options, i.e. a lighweight "Multi-AZ Kubernetes" which comes with a bunch of limitations, and a more comprehensive "Ubernetes" option for people who don't like those limitations.

**Comment by quinton-hoole** [comment]
Also related: https://github.com/kubernetes/contrib/tree/master/service-loadbalancer#cross-cluster-loadbalancing

**Comment by jvalencia** [comment]
From my perspective, I would rather run a single zone AWS cluster, but have multiple of them.  Data processing through network transactions on AWS is much, much faster if you stay in the same zone.  I would rather cut out a cluster from production traffic than deal with the increased architecture overhead.

Hence managing federated clusters is preferable.

**Comment by zytek** [comment]
Heavy AWS user here. The way our current environment works in us-east-1 is that we span on ALL AVAILABLE AZs (4). Example:
- load balancers, web workers and background ones split on 4 AZ on "paas grids"
- Redis sentinels in 3 AZ (quorum)
- ElasticSearch clusters also in 3 AZs 
- Redis/MySQL masters in one of the zones, with at least 2 slaves in other zones

This, connected via ELB plus some tooling (MySQL MHA etc) can help us mitigate any issues in single AZ (which **DO** happen) and **capacity issues** (which also do happen, single AZ can be out of capacity for some instance types!) and as far as I know follow the "AWS best practices".

IMO this **needs** to be replicated in Kubernetes setups in AWS environments to be considered *production ready*. Although I buy the "ubernetes" approach (ease of management and overal "safety" feeling in having >1 cluster) this doesn't seem feasible for anything more than workers connecting to AWS-hosted databases (RDS, ElastiCache etc). How can I, with ubeneters, setup Redis slaves from one cluster to another? What about other master-slave workloads that would benefit from AZ split?

Seems like the biggest issue for now are persistent disks. Snapshoting doesnt seem to be the option, as for big volumes with lots of small changes this can take hours (and can significantly degrade performance of snapshotted volume). It might be that some pods are 'pinned' to AZ, so that if host fails kubernetes could re-attach EBS disks to another node in the same AZ and restart pods there. Would be good enought. Additional tooling could be made to migrate pods between AZ. (via snapshot or data export/inport (rsync or custom solutions like mysqldump).

**Comment by justinsb** [comment]
@zytek Just so I can be clear - you're saying you have the multi-AZ setup without Kubernetes right? Because if you have this working with kubernetes that would be very welcome!

The answer to your big picture question is that for a cluster in Ubernetes, I imagine that each kubernetes cluster would be aware of the others are would coordinate discovery across them.  My only-exists-in-theory concept for how this would work would be that we would create objects that represent the other clusters, and then we would have some sort of multi-cluster replication-controller-like-thing that would work across clusters.  This does require pods that are deeper and more active consumers of the Kubernetes APIs, including cross-cluster consumption.  I may have something to show on this in a few weeks.

That doesn't mean that multi-AZ Kubernetes is not important; just that your scenario can work nicely even with Ubernetes.

Persistent disks are trickier, but I think they work in either multi-AZ Kubernetes (they are a scheduling constraint) or in Ubernetes.  In both cases you have a DB cluster running in 3 AZs, with one EBS volume in each, and you don't do cross-AZ recovery.  I agree that you should also have backups e.g. on S3, and this could enable more advanced strategies for long-term AZ failure.  We have yet to see an incident where I think this would have been the right course of action IMHO, but that is not to say it won't happen!

**Comment by pikeas** [comment]
+1 for either multi-AZ Kubernetes or Ubernetes. As an end-user in ops, my preference is for multi-AZ, because some AWS primitives (eg, elastic load balancer) are already multi-AZ aware, and this is a closer setup to existing production deployments.

Ubernetes may well be a better long-term, but it sounds like the work needed to bring that to look puts it off easily 6+ months. I'd rather see a good-enough multi-AZ solution sooner, if possible.

PS - "Ubernetes" is an absolutely hilarious name.

**Comment by pidah** [comment]
hi @justinsb – just following you up on our conversation at kubecon yesterday about multi-AZ  🙏

**Comment by justinsb** [comment]
Hi @pidah - I also opened #17059 as a tracking issue / TODO list

**Comment by pidah** [comment]
@justinsb :+1:

**Comment by davidopp** [comment]
I'm moving this out of v1.2 milestone because #17059 tracks the v1.2 work.

**Comment by danielwhatmuff** [comment]
+1 for multi-AZ Kubernetes

**Comment by quinton-hoole** [comment]
I think that we can close this as a duplicate of the various Kubernetes Lite and Kubernetes Proper issues, PR's and the working group (http://tinyurl.com/ubernetes-wg-notes). See also #17059, #19313.
