### ISSUE TITLE
Should it constitute an error if the network plugin status hook returns an error?

### ISSUE THREAD

**Issue by pmorie** [kubernetes/kubernetes#13055]
This just looks wrong, but I thought I would ask before changing the code:

https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockertools/manager.go#L311

@rajatchopra You're indicated by git blame -- is there a reason the error is swallowed and logged?

**Comment by rajatchopra** [comment]
It just follows what the default does two lines above - https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockertools/manager.go#L306
If the IP was collected properly, good, otherwise log and move on. The status call is a periodic collection, and its failure should not be considered fatal.

**Comment by pmorie** [comment]
@rajatchopra Ok, that makes sense.  I will add a comment (I'm changing some of that code now).
