### ISSUE TITLE
Incorrect Login For Master

### ISSUE THREAD

**Issue by ronaldpetty** [kubernetes/kubernetes#13060]
Hello,

For a brand new (first time) installation using the Vagrant install fails (different reason, suspect python lib issue).  I then switched to using the AWS tutorial, it succeeds after some undocumented fixes (will add new bug for that in docs).  After it starts, if you visit the AWS EC2 master, the authentication is requiring the login from the previous Vagrant install.  I suspect it didn't override with the new AWS settings.  I will keep investigating and try to see if this is a real bug or poor docs.

Regards.

Ron

**Comment by roberthbailey** [comment]
Sounds like a bug.

**Comment by jlowdermilk** [comment]
> After it starts, if you visit the AWS EC2 master, the authentication is requiring the login from the previous Vagrant install.

Do you mean that the master is using admin/password from the vagrant install? It's possible that it's picking up credentials from env vars that the vagrant install set.

**Comment by roberthbailey** [comment]
@jlowdermilk -- if a cluster (e.g. vagrant) currently exists that means that there is a current context for when [get-kubeconfig-basicauth](https://github.com/kubernetes/kubernetes/blob/master/cluster/common.sh#L130) is called -- so it may just re-use the existing credentials instead of generating new ones. I haven't had a chance to try and repro.

**Comment by brendandburns** [comment]
@jlowdermilk is this fixed by #13068?

**Comment by jlowdermilk** [comment]
Yes, #13068 contains fix. I don't think it got cherry picked tho.
