### ISSUE TITLE
Error creating external load balancer with gce and CoreOS cluster

### ISSUE THREAD

**Issue by smakam** [kubernetes/kubernetes#13073]
Hi
I have a CoreOS Kubernetes cluster that I created using steps in https://github.com/rimusz/coreos-multi-node-k8s-gce/blob/master/README.md.
I tried simple nginx application using steps in https://github.com/kubernetes/kubernetes/blob/master/docs/user-guide/quick-start.md.

When I try to create external loadbalancer, there is an error:

$ kubectl describe svc my-nginx
Name:			my-nginx
Namespace:		default
Labels:			run=my-nginx
Selector:		run=my-nginx
Type:			LoadBalancer
IP:			10.100.190.2
Port:			<unnamed>	80/TCP
NodePort:		<unnamed>	30049/TCP
Endpoints:		10.244.2.2:80,10.244.42.2:80
Session Affinity:	None
Events:
  FirstSeen				LastSeen			Count	From			SubobjectPath	Reason				Message
  Sun, 23 Aug 2015 21:15:23 +0530	Sun, 23 Aug 2015 21:19:17 +0530	6	{service-controller }			creating loadbalancer failed	failed to create external load balancer for service default/my-nginx: googleapi: Error 400: Invalid value for field 'resource.targetTags[0]': 'k8s-node-1.c.coreostest-1026.int'.  Must be a match of regex '(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?)', invalid
  Sun, 23 Aug 2015 21:15:50 +0530	Sun, 23 Aug 2015 21:19:58 +0530	6	{service-controller }			creating loadbalancer failed	googleapi: Error 404: The resource 'projects/coreostest-1026/global/firewalls/k8s-fw-ae684a7c349ad11e5b79842010af08d4' was not found, notFound

I see similar error in Controller manager log:
Aug 23 15:45:23 k8s-master.c.coreostest-1026.internal kube-controller-manager[1268]: E0823 15:45:23.462038    1268 servicecontroller.go:173] Failed to process service delta. Retrying: failed to create external load balancer for service default/my-nginx: googleapi: Error 400: Invalid value for field 'resource.targetTags[0]': 'k8s-node-1.c.coreostest-1026.int'.  Must be a match of regex '(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?)', invalid

I see that someone had posted a similar query in stackoverflow(http://stackoverflow.com/questions/31832713/kubernetes-1-0-1-external-load-balancer-on-gce-with-coreos) and it has not been answered. Is this an issue with latest Kubernetes version?

Thanks
Sreenivas

**Comment by ScOut3R** [comment]
Just bumped into this with version 1.0.3.

```
  Sun, 23 Aug 2015 20:28:32 +0200	Sun, 23 Aug 2015 20:28:32 +0200	1	{service-controller }			creating loadbalancer failed	googleapi: Error 404: The resource 'projects/kubetest-1046/global/firewalls/k8s-fw-a763ae23549c411e59b1242010af0e9a' was not found, notFound
  Sun, 23 Aug 2015 20:27:58 +0200	Sun, 23 Aug 2015 20:29:59 +0200	2	{service-controller }			creating loadbalancer failed	failed to create external load balancer for service default/web-service: googleapi: Error 400: Invalid value for field 'resource.targetTags[0]': 'kubenode01.c.kubetest-1046.int'.  Must be a match of regex '(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?)', invalid
```

**Comment by nikhiljindal** [comment]
cc @thockin

**Comment by thockin** [comment]
All signs point to `GCECloud.computeHostTag()`, whose comment starts with "This is kind of hacky, but"

@a-robinson do you have bandwidth for this?

**Comment by a-robinson** [comment]
Sure, I'll take a look

**Comment by a-robinson** [comment]
Hi @smakam. Thanks for linking to the tool you used to create your cluster, it's very helpful for getting to the bottom of issues like this!

I see at least three problems keeping this from working for you:

1. The bootstrap tool you used is registering nodes with the fully qualified hostname (k8s-node-1.c.coreostest-1026.internal), rather than just the GCE VM name (k8s-node-1).

2. The GCE cloud provider expects all node instances to be in a managed instance group (which all end with -xxxx, hence the minus 5 logic). That won't work with nodes that are names foo-1, foo-2, etc. This is both the fault of the cloud provider code for not being more general and cutting off the last hyphenated section, and of the bootstrap tool you used for not using a managed instance group.

3. The bootstrap tool you used isn't applying the correct tags to the nodes. Kubernetes expects the nodes to be tagged with the prefix of the node name (meaning nodes named k8s-node-1 would be tagged with k8s-node), but that tool uses a slightly different tag (k8s-nodes).

The bootstrap tool be fixed, but as a general rule, it's fairly difficult to keep cluster provisioning scripts up-to-date as the system changes, so it's unlikely that any given script or example outside of the supported repo is going to work perfectly. We already have a cluster provisioning script for using CoreOS on GCE. If you run the following two commands, I believe you should get a functioning multi-node CoreOS cluster on GCE.

```shell
export OS_DISTRIBUTION=coreos
cluster/kube-up.sh
```

**Comment by a-robinson** [comment]
However, after typing that I went to look for a more full guide on how to use it, and saw the bootstrap tool you used linked to in our docs 😩

@erictune, is there any reason not to replace the couple guides in [our mess of CoreOS getting started guides](https://github.com/kubernetes/kubernetes/blob/master/docs/getting-started-guides/coreos.md) that relate to GCE with using our normal cluster/kube-up.sh?

If so, I'll do so and not worry about doing anything else other than changing computeHostTag to cut off the final - rather than the final 5 characters.

If there is some reason to keep those guides around, I can fix these specific issues in that bootstrap tool, but I wouldn't be at all surprised if there are other bugs lurking in it.

**Comment by a-robinson** [comment]
Re issue 1: the cloudprovider code has actually been fixed in #12438 to strip out everything after the first dot, but that was never cherry-picked into release-1.0. I'll propose cherry-picking it and a generalization of the "removing 5 characters" into release-1.0.

**Comment by smakam** [comment]
hi @a-robinson 
Thanks for your detailed response. 

Is my understanding correct that there is an issue with bootstrap tool as well as with computeHostTag cloudprovider code? 

The fix that you pointed out in #12438 - are you proposing that the fix to be put in mainstream gce release? From the above link, I see that the fix is committed? Do I need to update gce?

On the procedure to start the cluster, you had mentioned using this (export OS_DISTRIBUTION=coreos
cluster/kube-up.sh). When I did this, I got the error "Cannot find kubernetes-server-linux-amd64.tar.gz". At which point, I realized that I need to build the binaries. I did "make quick-release" and this seems to binaries of all platforms and this seems to require more than 6GB of space and I ran out of space in my system. Is there an alternative to build only the Linux binary? I looked at this link(https://github.com/kubernetes/kubernetes/tree/master/build) and it suggested  doing "run.sh hack/build-go.sh; copy-output.sh" but that did not seem to work for me as it did not copy. If bootstrapping is not the right way, is there a official procedure/link to start kubernetes gce cluster on coreos or linux? Sorry, I could not find it.

Thanks
Sreenivas

**Comment by a-robinson** [comment]
Your understanding is mostly correct -- the cloudprovider code wasn't actually broken, but it wasn't as lenient as it could be in terms of accepting different node names. The bootstrap tool is applying incorrect tags to the nodes, which the cloudprovider code is unlikely to be lenient enough to handle anytime soon, since it would require much more knowledge of the infrastructure.

Both #12438 and #13121 have been cherry-picked into the 1.0 branch and will be part of 1.0.4 when it's cut. They'll make it so that fewer changes are needed to the bootstrap tool to make it functional, but its tags are still wrong.

You're best off deploying from a released version rather than from head. Go to the [releases page](https://github.com/kubernetes/kubernetes/releases), download the latest release's tar.gz file, untar it, and run the cluster/kube-up.sh from within it. This won't require building anything.

**Comment by a-robinson** [comment]
I've also opened a PR to fix the tag assigned by the bootstrap tool - https://github.com/rimusz/coreos-multi-node-k8s-gce/pull/9

**Comment by a-robinson** [comment]
@smakam, I'm going to mark this as closed since the changes that we know were needed to make the bootstrap tool work are now into the 1.0 branch and the bootstrap tool, respectively. Feel free to reopen if it doesn't in fact work once 1.0.4 is available.

If you have more trouble getting kube-up.sh to work with CoreOS, we request that you open a question on StackOverflow so that it's easier for others to benefit from the solutions posted. It's tough for people to find answers to questions in old Github issues. Thanks!

**Comment by kelbongoo** [comment]
I am getting this problem when I launch the cluster via gcloud container clusters create my-cluster.
Then following the tutorial here (https://github.com/GoogleCloudPlatform/kube-jenkins-imager/blob/master/cluster_up.sh) I get this error 

```
pc8:security richardfielding$ kubectl describe services nginx-ssl-proxy
Name:			nginx-ssl-proxy
Namespace:		default
Labels:			name=nginx,role=ssl-proxy
Selector:		name=nginx,role=ssl-proxy
Type:			LoadBalancer
IP:			10.15.242.142
Port:			https	443/TCP
NodePort:		https	30658/TCP
Endpoints:		<none>
Port:			http	80/TCP
NodePort:		http	32656/TCP
Endpoints:		<none>
Session Affinity:	None
Events:
  FirstSeen				LastSeen			Count	From			SubobjectPath	Reason				Message
  Sun, 20 Sep 2015 00:43:24 +0200	Sun, 20 Sep 2015 00:43:24 +0200	1	{service-controller }			creating loadbalancer failedgoogleapi: Error 404: The resource 'projects/legoutdufrais.com:api-project-728797969216/global/firewalls/k8s-fw-a6070536b5f1f11e5be9342010af0e5a' was not found, notFound
  Sun, 20 Sep 2015 00:42:20 +0200	Sun, 20 Sep 2015 00:45:09 +0200	2	{service-controller }			creating loadbalancer failedfailed to create external load balancer for service default/nginx-ssl-proxy: googleapi: Error 404: The resource 'legoutdufrais.com%3Aapi-project-728797969216' was not found, notFound
```
