### ISSUE TITLE
kube-proxy throwing i/o timeout

### ISSUE THREAD

**Issue by PhilibertDugas** [kubernetes/kubernetes#13111]
Hi,

I've been seeing this alot of these in the kube-proxy logs, not sure how to deal with them:

![selection_182](https://cloud.githubusercontent.com/assets/5460957/9452918/0f97a4c6-4a85-11e5-8f3c-9ccb2ac80459.png)

I'm running kubernetes 1.0.1 on a bare-metal Ubuntu 14.04 installation

I also have a HAProxy sitting in front of the kubernetes cluster doing health check via HTTP.

Noticed many health checks being very slow > 2S which causes a Layer 7 timeout, most likely related to the same issue

These timeout usually start to appear after stress/load testing our system and I can't seem to make them disapear (Even after kube-down / kube-up the whole system)

**Comment by goltermann** [comment]
We’re going through old support issues and asking everyone to direct your questions to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes). 

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases. 

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

**Comment by quinton-hoole** [comment]
@PhilibertDugas It looks like you might have run into #13345.  The fix for it will probably be in v1.0.5 in the next few days.
@thockin do you remember seeing the above specific error messages in the kube-proxy logs when you were investigating #13345?  Does this one look like the same thing?

**Comment by PhilibertDugas** [comment]
In the end I was able to figure out the issue,

For some reason Flannel and Docker were not under the same subnet anymore.

Flannel would register with a 172.16.28.0/24 subnet and the Docker interface was quite different. Because of this, the other Node would try to reach pods under 172.16.28.0/24 and would timeout because the Docker interface wasn't in that subnet

Not sure how this happened, I haven't been able to reproduce the issue yet but the solution for me was to run the ubuntu script: reconfDocker.sh
