### ISSUE TITLE
google-fluentd using a lot of memory which got killed by kernel every 2~3 secs

### ISSUE THREAD

**Issue by pencilcheck** [kubernetes/kubernetes#13129]
One of the compute engine instance created by the container clusters has a fluentd that keeps crashing and using over 100% CPU. 

Displaying the serial-port log of the node reveals that the process got killed by kernel cause it uses a lot of memory
https://gist.github.com/pencilcheck/4d0700869fdd435e4593

And the reason why it is using a lot of memory is unknown because there is no log when I try to inspect it via `kubectl`

`kubectl get pods --namespace=kube-system then kubect logs <fluentd pod> --namespace=kube-system`

There are only 2 pods that belongs to the application, the rest are set up by the container clusters. Those 2 pods are both using less than 1% of memory I believe, and very low CPU usage.

```
Name:                   gke-demo-7140bbcf-node-xzxu
Labels:                 kubernetes.io/hostname=gke-demo-7140bbcf-node-xzxu
CreationTimestamp:      Wed, 05 Aug 2015 14:20:20 -0700
Conditions:
  Type          Status  LastHeartbeatTime                       LastTransitionTime                      Reason            Message
  Ready         True    Mon, 24 Aug 2015 23:26:32 -0700         Wed, 05 Aug 2015 14:20:50 -0700         kubelet is posting ready status
Addresses:      10.240.239.104,162.222.179.164
Capacity:
 cpu:           1
 memory:        3800808Ki
 pods:          100
Version:
 Kernel Version:                3.16.0-0.bpo.4-amd64
 OS Image:                      Debian GNU/Linux 7 (wheezy)
 Container Runtime Version:     docker://Unknown
 Kubelet Version:               v0.21.4
 Kube-Proxy Version:            v0.21.4
PodCIDR:                        10.128.1.0/24
ExternalID:                     12523289726931493693
Pods:                           (4 in total)
  Namespace                     Name
  default                       mailer-5379238f9b83cc212373e927b364639f-dw8pm
  default                       nginx-466af8af4fb67dff39fed0240230dc30-vqe19
  kube-system                   fluentd-cloud-logging-gke-demo-7140bbcf-node-xzxu
  kube-system                   kube-dns-v8-1qg0o
No events.
```

The node is still online, I thought leaving it up would be helpful so one google engineer can ssh in and debug, but it would be nice if I don't have to leave it up, so maybe I should kill the node and restart a new one, but that would not be helpful as this might happen again.

**Comment by yujuhong** [comment]
cc @kubernetes/goog-gke

**Comment by a-robinson** [comment]
Hi @pencilcheck, thanks for reporting the issue!

The most likely issue is that your project doesn't have cloud logging enabled. Fluentd tries to write your logs to the Cloud Logging API for your project, but if the API isn't enabled its requests will fail. When its requests fail, it will build up a backlog of logs that it wants to send in memory. It's supposed to start dropping logs before it gets to this point, but we may have made a mistake in picking the limits on how much it's allowed to buffer. You can go to this page and pick your cloud project name to see if it has the logging API enabled: https://console.developers.google.com/project/_/apiui/apiview/logging/overview

If you do already have the logging API enabled, then I'd be very interested in SSH'ing to your node to figure out what the problem is. My email is arob at google.com if you'd like to get in touch privately.

**Comment by pencilcheck** [comment]
Yes, the logging API was already enabled. That's why I was confused.

**Comment by a-robinson** [comment]
I take it you've deleted the VM/cluster? If not, I'd definitely appreciate an email to arrange SSH access.

**Comment by a-robinson** [comment]
Thanks again for reporting this!

I looked into the cluster, and it's due to the nodes being on version 0.21.4. Fluentd is running out of memory because there are an incredibly large number of log file symlinks laying around, and PR #10830 for garbage collecting the symlinks from old containers didn't make it into a release until 1.0.0. Fluentd pays a bit of memory for each file it tails, and tens of thousands of symlinks were causing it to use more than 200MiB of memory.

Since this is on GKE, the best fix is to upgrade the cluster's nodes. Documentation about doing so is available in GKE's documentation: https://cloud.google.com/container-engine/docs/clusters/upgrade
