### ISSUE TITLE
Pods doesn't run on another node after its node down 

### ISSUE THREAD

**Issue by JackChen255** [kubernetes/kubernetes#13210]
I create a mysql pods which is running in Node3 172.24.18.125. But after I stop all kubernetes services in Node3, this pods disappears instead of running in Node1 or Node2. Why the kubernetes master doesn't reschedule the pods in another node?

[root@localhost pods]# kubectl get nodes
NAME            LABELS                                                STATUS
127.0.0.1       kubernetes.io/hostname=127.0.0.1                      Ready
172.24.18.123   database=mysql,kubernetes.io/hostname=172.24.18.123   Ready
172.24.18.124   kubernetes.io/hostname=172.24.18.124                  Ready
172.24.18.125   kubernetes.io/hostname=172.24.18.125                  Ready

YAML file to create mysql pod:
apiVersion: v1
kind: Pod
metadata:
  name: mysql2
  labels:
    name: mysql2
spec:
  containers:
    - resources:
        limits :
          cpu: 1
      image: mysql
      name: mysql
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: welcome
      ports:
        - containerPort: 3306
          name: mysql2
  nodeSelector:

**Comment by yujuhong** [comment]
You need to a replication controller to manage your pod. See https://github.com/kubernetes/kubernetes/blob/master/docs/user-guide/replication-controller.md

**Comment by yujuhong** [comment]
For future reference, please direct your questions to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes). 

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases. 

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to similar questions, and also familiarize yourself with:
  * [the user guide](http://kubernetes.io/v1.0/)
  * [the troubleshooting guide](http://kubernetes.io/v1.0/docs/troubleshooting.html)

Again, thanks for using Kubernetes.

The Kubernetes Team
