### ISSUE TITLE
kubeproxy performance and best practice for running a site

### ISSUE THREAD

**Issue by ddysher** [kubernetes/kubernetes#13234]
I'm running a website with multiple sub-domains on kubernetes (e.g. blog.mysite.com, get.mysite.com, etc).  However, I don't want to expose every subdomain as a external service (external loadbalancer), so the current setup is to only expose a nginx frontend service, and proxy to internal services, i.e. 

request-> kube-proxy (locate nginx pods) -> nginx pods (locate service) -> kube-proxy (locate pods) -> actual pods

This is a bit slower than not using kubernetes, particularly for establishing connection.  Is there any best practice for the use case?  It seems the bottlenet comes from kubeproxy.

**Comment by bprashanth** [comment]
This is actually 2 issues: kube-proxy performance and how to get around it. Performance of kube-proxy will get better in 1.1 (https://github.com/kubernetes/kubernetes/issues/3760). Recommend posting second part to stack overflow instead since that isn't really a bug. 

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases.
