### ISSUE TITLE
Preprocessing config files for kubectl

### ISSUE THREAD

**Issue by yugui** [kubernetes/kubernetes#13241]
I am wondering if it is possible to support [jsonnet](https://google.github.io/jsonnet/doc/) as a configuration file format for `kubectl`.  What do you think about supporting it?
# Background

I noticed that I have to manage similar but different configuration files for our dev, staging and production environments.  For example, some debug flags are enabled in dev environments; some monitoring stuff are enabled in staging and production environments; each environment has its own set of credentials.
On the other hand, other parts of the environments are very similar to each other and must be consistent. 

Jsonnet is a good way to consistently generate this kind of similar but different configuration files.  So it is very helpful for me if kubectl itself recognizes Jsonnet without generating JSON files from Jsonnet.

**Comment by bgrant0607** [comment]
Using "make" doesn't seem so bad.

Rather than support jsonnet specifically, I suggest that we add a general way for users to specify transformation passes. That's compatible with the "plugin" idea I suggested in #13606. 

Deployment manager #3685 will also provide another framework for invoking such transformations.

I do agree that we need to support parameterization #11492 and scoping #1698.

cc @kubernetes/kubectl

**Comment by bgrant0607** [comment]
cc @brendandburns @kubernetes/goog-ux

**Comment by chrisleck** [comment]
+1 for native jsonnet support.  I'd like to see kubectl support at least one config language that supports composition & factoring without forcing users to deal with writing, managing, and deploying plugins to every member of a development team.

**Comment by jackgr** [comment]
The new open source release of [Deployment Manager](https://github.com/kubernetes/deployment-manager) is another option.

**Comment by bgrant0607** [comment]
@ghodss was interested in jsonnet.

**Comment by danielqsj** [comment]
Hi all, has this feature been completed already? Or still in progress?

**Comment by bgrant0607** [comment]
@danielqsj @deads2k 

kubectl and its ecosystem have evolved since this issue was originally filed.

History:
#14993, #13606, #11492
https://github.com/kubernetes/kubernetes/blob/master/docs/proposals/templates.md
http://queue.acm.org/detail.cfm?id=2898444
https://github.com/kubernetes/helm

kubectl takes input from stdin and HTTP as well as from files. We only use file extensions to determine which files to process, not to infer content types. The content needs to be self-identifying. We should add that to kubectl conventions: https://github.com/kubernetes/kubernetes/blob/master/docs/devel/kubectl-conventions.md

Language-level imports won't work with those other input sources. That's really better suited for a package manager like Helm, which has a mechanism for bundling multiple files and/or specifying file dependencies.

Language-level parameterization and macro expansion doesn't meet the requirements laid out in #11492. For that, we have the template proposal:
https://github.com/kubernetes/kubernetes/blob/master/docs/proposals/templates.md
Work started (#23896, #25293, #25622), but hasn't been finished.

Additionally, most Kubectl commands accept multiple files, even recursive directory processing, in order to identify objects to operate on, including create, apply, replace, get, and delete. We'd probably have to require that templates had no unbound parameters, since we otherwise wouldn't have a good way to specify which parameters to provide to which files.

Client-side preprocessing would interfere with line numbers reported in error messages, which we added since this issue was originally filed. We'd want a mechanism similar to the C preprocessor for preserving the original line numbers.

I did previously think that invoking external programs might be a way to make kubectl more extensible, but it is problematic for a number of use cases, such as addon updates #23233. We'd also need to be very careful about which path was used to execute such a program, as mentioned here: https://github.com/kubernetes/kubernetes/pull/29175/files#r71322094.

We are also working towards making kubectl's commonly needed functionality thinner #12143.

We do want more create subcommands #25382, which could take parameters from files. For example, I could imagine `kubectl create container` reading a Container spec. Adding `--edit` #18064 would support programmatic postprocessing if we added a flag to specify the edit program. In general, I'm increasingly a fan of schema-aware, use-case-specific postprocessing (e.g., #17097) as an alternative to general-purpose parameterization.

We're going to need a bundle of client tools (https://github.com/kubernetes/release/issues/3): kubectl, helm/kpm, kompose, podex, minikube, kops, ... I think this is healthy, as it encourages the development of an ecosystem of tools. Some of those we might eventually pull into kubectl as subcommands, with distinct conventions for each of those command groups, but for now we should keep them separate. 

A Go implementation of jssonet could be added to such a bundle, or could be folded into one of the higher-level tools, such as Helm. I suggest asking them whether they are interested in jsonnet support.

cc @kubernetes/kubectl

**Comment by danielqsj** [comment]
@bgrant0607 
Sounds great. Wish to use templates and more tools ASAP.
If needs help, I am very interested in.

**Comment by bgrant0607** [comment]
Closing as out of scope for kubectl.

cc @kubernetes/sig-cli-feature-requests

**Comment by sparkprime** [comment]
In response to: "Client-side preprocessing would interfere with line numbers reported in error messages, which we added since this issue was originally filed. We'd want a mechanism similar to the C preprocessor for preserving the original line numbers."

My preferred approach is for error messages from lower level tools to report the context in terms of paths into the structure, i.e. "the 'foo' field of resource 'bar' inside namespace 'baz' should be a string, but we found a number" as opposed to using the line number from the YAML / JSON.

# line attributes don't work well in general, since there may not be a single appropriate line in the source file.  They don't even work very well for C:

```
#include <stdlib.h>
#include <stdio.h>

#define MY_MACRO(x) \
    do { \
        printf("%s", x[0]); \
    } while (0);
    

int main(void)
{
    MY_MACRO("seven");
    return EXIT_SUCCESS;
}
```

```
test.c: In function ‘main’:
test.c:12:5: warning: format ‘%s’ expects argument of type ‘char *’, but argument 2 has type ‘int’ [-Wformat=]
     MY_MACRO("seven");
     ^
```
