### ISSUE TITLE
N00b question - missing discovery token in yaml files

### ISSUE THREAD

**Issue by bartekborek** [kubernetes/kubernetes#13250]
Hi All,

Thanks for providing the code for us to work with, really appreciate that. I spun up some instances on AWS yesterday and noticed that there was no quorum formed between the instances, etcd2 wasn't happy and generally fleetctl failed? 

How is this supposed to be used? As a separate cluster of ONLY kubernetes to manage a separate cluster of actual worker nodes in a quorum or am I missing something. 

So essentially do we need two clusters? 
- Kubernetes
- CoreOS workers?

Or does the yaml need tweaking for our environment to form a quorum where etcd2 is happy.

Excuse the n00bness but this is still very new to most us and we are all very excited to learn new stuff.

Thanks

Bartek

**Comment by bprashanth** [comment]
Please re-post your question to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes). 

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases. 

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to similar questions, and also familiarize yourself with:
  * [the user guide](http://kubernetes.io/v1.0/)
  * [the troubleshooting guide](http://kubernetes.io/v1.0/docs/troubleshooting.html)

Again, thanks for using Kubernetes.

The Kubernetes Team
