### ISSUE TITLE
Calico: Network plugin "calico" failed init: exit status 255

### ISSUE THREAD

**Issue by Smana** [kubernetes/kubernetes#13269]
Hello,

I'm currently testing calico with kubernetes but i'm facing an issue.
I followed the documentation : https://github.com/kubernetes/kubernetes/blob/master/docs/getting-started-guides/ubuntu-calico.md

And calico seems to be happy : 
```
calicoctl status
calico-node container is running. Status: Up 36 minutes

IPv4 BGP status
+--------------+-------------------+-------+----------+-------------+
| Peer address |     Peer type     | State |  Since   |     Info    |
+--------------+-------------------+-------+----------+-------------+
| 10.115.77.88 | node-to-node mesh |   up  | 12:57:29 | Established |
| 10.115.77.89 | node-to-node mesh |   up  | 12:58:48 | Established |
| 10.115.77.87 | node-to-node mesh |   up  | 12:58:40 | Established |
+--------------+-------------------+-------+----------+-------------+

IPv6 BGP status
+--------------+-----------+-------+-------+------+
| Peer address | Peer type | State | Since | Info |
+--------------+-----------+-------+-------+------+
+--------------+-----------+-------+-------+------+
```
The containers can talk each others from node to node.

Unfortunately when i start kubelet on nodes i get the following message : 
```
/usr/local/bin/kubelet --logtostderr=true --v=0 --api_servers=https://10.115.77.86:443 --address=0.0.0.0 --hostname_override=10.115.77.87 --allow_privileged=true --kubeconfig=/etc/kubernetes/kubelet.kubeconfig --network_plugin=calico
I0827 13:37:12.027317     935 manager.go:127] cAdvisor running in container: "/"
I0827 13:37:12.028076     935 fs.go:93] Filesystem partitions: map[/dev/vda2:{mountpoint:/ major:254 minor:2}]
I0827 13:37:12.031702     935 manager.go:156] Machine: {NumCores:2 CpuFrequency:2260998 MemoryCapacity:3167059968 MachineID:c39561d3284963021ae3cb2b995631a5 SystemUUID:7869686E-14AA-25EA-A478-2454DC0FA17A BootID:af96ffa8-08d3-45cd-b799-c1e7f8441f18 Filesystems:[{Device:/dev/vda2 Capacity:31571550208}] DiskMap:map[254:0:{Name:vda Major:254 Minor:0 Size:32212254720 Scheduler:none}] NetworkDevices:[{Name:cbr0 MacAddress:4e:1f:03:44:18:a4 Speed:0 Mtu:1500} {Name:eth0 MacAddress:52:54:00:d7:32:b7 Speed:0 Mtu:1500} {Name:tunl0 MacAddress:00:00:00:00 Speed:0 Mtu:1480}] Topology:[{Id:0 Memory:3167059968 Cores:[{Id:0 Threads:[0] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:4194304 Type:Unified Level:2}]}] Caches:[]} {Id:1 Memory:0 Cores:[{Id:0 Threads:[1] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:4194304 Type:Unified Level:2}]}] Caches:[]}]}
I0827 13:37:12.033000     935 manager.go:163] Version: {KernelVersion:3.16.0-4-amd64 ContainerOsVersion:Debian GNU/Linux 8 (jessie) DockerVersion:1.6.2 CadvisorVersion:0.15.1}
I0827 13:37:12.033851     935 plugins.go:69] No cloud provider specified.
I0827 13:37:13.065601     935 docker.go:295] Connecting to docker on unix:///var/run/docker.sock
I0827 13:37:13.066002     935 server.go:673] Watching apiserver
failed to create kubelet: Network plugin "calico" failed init: exit status 255
```

Could you please help me to find out how to get it work ?

Some information : 
docker version : 1.6.2 (i know it is not the latest, tell me if that could be the cause)
calicoctl version : 0.5.1
kubernetes version : 1.0.3
OS : debian jessie

Thanks,
Smana

**Comment by thockin** [comment]
@symmetric @lxpollitt

**Comment by bprashanth** [comment]
Please re-post your question to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes). 

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases. 

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to similar questions, and also familiarize yourself with:
  * [the user guide](http://kubernetes.io/v1.0/)
  * [the troubleshooting guide](http://kubernetes.io/v1.0/docs/troubleshooting.html)

Again, thanks for using Kubernetes.

The Kubernetes Team

**Comment by lxpollitt** [comment]
@thockin, @bprashanth:  We are tracking and resolving this as a Calico related issue: https://github.com/projectcalico/calico-kubernetes/issues/27.

So I think this issue here can be closed.

**Comment by Smana** [comment]
ok closing it. thanks
