### ISSUE TITLE
More graceful fallback if 'docker pull' fails

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#1329]
If docker pull fails, we give up on a container and retry later, even if we actually have a local image of the same name & tag.  I'm not convinced this is better than simply using the one we have.  This also fails if someone tries to spec an image ID instead of an image name - which should be runnable, but is certainly not pullable.

**Comment by bgrant0607** [comment]
Is this still an issue @dchen1107 ?

**Comment by felipecrs** [comment]
Guys, I'm very sorry to reply on a ticket that was closed on 2016, but:

I have been observing that K8s seems to be doing precisely this: it falls back to a cached image if pull fails, even if `imagePullPolicy` is set to `Always`.

By any chance, do someone know if this is the expected behavior? I could not find it in the documentation.

This actually hurts my use-case, I need K8s to pull a newer image and never fallback to a cached one (and fail the deployment if necessary).

**Comment by thockin** [comment]
That sounds like a big to me, but it's outside my direct knowledge.
Sig-node should weigh in...

**Comment by felipecrs** [comment]
Ok, thank you, no problem. I'll verify it further and fill a bug if necessary.
