### ISSUE TITLE
kubelet should clean up more reliably

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#13311]
kubelet offloads most of the pod-specific work to the per-pod workers (goroutines). This includes creating pod directories and mounting volumes, and killing containers in some cases.
On the other hand, the main kubelet loop performs global cleanup/housekeeping such as unmounting and removing volume/pod directory, and killing containers in some cases.

This creates race conditions that lead to transient errors or often something worse. We should let the pod worker does all the cleanup and let kubelet only garbage collects unused resources. The first step is to teach pod worker to understand the notion of "deletion" and try to clean up their own pod if possible, and retries on errors.

@kubernetes/goog-node, @saad-ali, any thoughts?

**Comment by saad-ali** [comment]
> We should let the pod worker does all the cleanup and let kubelet only garbage collects unused resources.

I think that's a good idea.

We had to work around this in GCE PD attach detach logic: where the attach code, since it is kicked off by pod worker routine, didn't have to worry about blocking while attaching and mounting, but the detach code, since it is kicked off by the kubelet sync loop, had to be very careful about not blocking--and instead had to spin off threads to do clean up asynchronously (leading to some fun race conditions).

That said, I'm not sure it would fix all the issues. In particular as long as the garbage collection happens in the sync loop, there will be the worry of long running garbage collection tasks blocking the sync loop and, more importantly, a possibility of a race condition with the pod creation routines: consider a PD being garbage collected by the sync loop, while it is being "recreated" by a pod creation routine.

**Comment by yujuhong** [comment]
PD is definitely a more complicated case as it's shared by pods. We could either
 1. maintain a ref count somewhere, and let the pod worker detach the PD if ref count reaches 0.
 2. create a separate goroutine whose sole responsibility is managing shared resources like this. Individual pod worker can send requests to the goroutine, and this avoids unexpected race conditions.

(2) is theoretically cleaner since pod workers should not manage inter-pod resources.

**Comment by vishh** [comment]
Elaborating @yujuhong's option `2`, can PD be managed by a separate PD manager (or a Volume Manager) that understands the issues with PD? Creations and deletions of PD should go through that module.

**Comment by yujuhong** [comment]
At the least we should know whether the worker for a pod is still inflight, and only cleans up afterwards.
(I had an outdated PR to add this to pod workers: #20465)

Some more caveats: 
 - What if pod worker is stuck and unresponsive? This should be rare now that we have timeout for docker operations, but we need to be careful anyway.
 - Need to stop kubelet from creating a new worker for the pod during this window.
 - We will also need to ensure the worker cleans up everything before terminating itself, which I believe is not the case today.
