### ISSUE TITLE
log level from pod via fluentd 

### ISSUE THREAD

**Issue by navicore** [kubernetes/kubernetes#13355]
I got here from http://stackoverflow.com/questions/30955142/logseverity-on-aggregated-logs-in-google-container-engine

I'm running with kubernetes on gce with cloud logging enabled and looking at my pods logging output via the cloud logging console.  it is all there (great).

Is there a *best* log format that will facilitate log searches for WARN or ERROR in google cloud logging console?

```json
{severity: "WARN", time: "2015-08-29 10:34:39.200", service: "cred", logMessage: "password invalid"}
```

It would be great if these could get parsed for easy viewing and rendering just by us formatting them properly, ie: json with std fields like logLevel, time, etc...

**Comment by marktheunissen** [comment]
+1 this would be a great feature

**Comment by florenthobein** [comment]
I agree this would greatly increase log readability on the gcl console.

**Comment by torbjornvatn** [comment]
I'm also really interested in this feature because it would make it a lot easier to make *log based metrics* in Google Cloud Monitoring that can trigger an alert on e.g. "X number of ERRORs the last minute"

**Comment by alvinsay** [comment]
+1 It will be very helpful.

**Comment by a-robinson** [comment]
This has been supported since the 1.1. release in October 2015, so long as you log in JSON and include a field named "severity", as the OP did. You'll also probably want to populate the "message" field, which is assumed to contain the main body of the log message.

Sorry for not seeing this previously!

**Comment by gingerlime** [comment]
just curious, but why isn't this working if the json key name is `level` rather than `severity` ?

... especially since the UI refers to it as `level` as well, and (to my very limited knowledge) I think it's usually referred to this way.

![screenshot_2017-05-07_10-12-11](https://cloud.githubusercontent.com/assets/524274/25778981/b9428ef6-330d-11e7-93d8-69dc45cff918.png)
