### ISSUE TITLE
Nodetool status

### ISSUE THREAD

**Issue by adyanthaya17** [kubernetes/kubernetes#13374]
Instead of getting 100% I'm getting a '?' in the Owns section as below:

root@minion2:/home/ubuntu/cassandra# kubectl exec -ti cassandra-dtihg -- nodetool status
Datacenter: datacenter1
=======================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address     Load       Tokens       Owns    Host ID                               Rack
UN  172.17.0.7  96.89 KB   256          ?       33875135-c8d7-4fe5-8e4a-b6a9da8b3751  rack1

Note: Non-system keyspaces don't have the same replication settings, effective ownership information is meaningless

**Comment by lavalamp** [comment]
Please re-post your question to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes). 

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases. 

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to similar questions, and also familiarize yourself with:
  * [the user guide](http://kubernetes.io/v1.0/)
  * [the troubleshooting guide](http://kubernetes.io/v1.0/docs/troubleshooting.html)

Again, thanks for using Kubernetes.

The Kubernetes Team
