### ISSUE TITLE
Use gcloud self encrypted disk with Kubernetes

### ISSUE THREAD

**Issue by mbn18** [kubernetes/kubernetes#13391]
I need to encrypt the data on a block device and allow the Pod to access it as a volume.

I noticed its now possible on Google cloud to encrypt a new disk using [Customer-Supplied Encryption Keys][1]

Can I use self encrypted disk with Kubernetes and attach it to the Pod as volume?

If not, is there any other way to encrypt block device (for example LUKS) and use it with Pods?

  [1]: https://cloud.google.com/compute/docs/disks/customer-supplied-encryption

**Comment by lavalamp** [comment]
Please re-post your question to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes). 

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases. 

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to similar questions, and also familiarize yourself with:
  * [the user guide](http://kubernetes.io/v1.0/)
  * [the troubleshooting guide](http://kubernetes.io/v1.0/docs/troubleshooting.html)

Again, thanks for using Kubernetes.

The Kubernetes Team

**Comment by mbn18** [comment]
@lavalamp , thanks for the tip. My Q was first posted at [StackOverflow][1]

Though I am afraid that this feature is not supported yet. As no one answered the question.

[1]: http://stackoverflow.com/questions/32310849/use-gcloud-self-encrypted-disk-with-kubernetes

**Comment by lavalamp** [comment]
Sorry it didn't get an answer-- we're still working the kinks out. I will try to get someone to answer over there.

**Comment by erictune** [comment]
FTR, better response posed on SO and #13493
