### ISSUE TITLE
how to completely test guestbook example ?

### ISSUE THREAD

**Issue by jijun2** [kubernetes/kubernetes#13428]
I follow the guestbook guide , operate step by step, and everything seems to be OK,
guestbook web can be accessable, but web access very slowly and can't save any message I write, 
I use  nodeport type for service,kubectl get pod/node/ is ok, 

I think volume configure(no user) maybe the reason of error ?  or other reason?

**Comment by maklemenz** [comment]
Please ask support questions on stackoverflow. It is very hard to find the real bugs and proposals between all the support questions on github.
Also, please add the logs from `kubectl logs <podId> [<containerName>]`. It is very hard to support you without such informations.

**Comment by gmarek** [comment]
Please re-post your question to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes). 

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases. 

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to similar questions, and also familiarize yourself with:
  * [the user guide](http://kubernetes.io/v1.0/)
  * [the troubleshooting guide](http://kubernetes.io/v1.0/docs/troubleshooting.html)

Again, thanks for using Kubernetes.

The Kubernetes Team

**Comment by jijun2** [comment]
ok,thank you!
