### ISSUE TITLE
Re-evaluate rate-limiting parameters

### ISSUE THREAD

**Issue by davidopp** [kubernetes/kubernetes#13430]
The rate limiter parameters are DeletingPodsQps and DeletingPodsBurst in
cmd/kube-controller-manager/app/controllermanager.go. The defaults should allow 10 NotReady nodes to have their pods evicted right away, and 1 NotReady node every 10 seconds thereafter.

It's very possible these values are too aggressive. For one thing, they really should be expressed as a percentage of cluster size, not in absolute numbers--since our max supported cluster size is currently 100, we will remove all the Pods in the largest cluster in 900 seconds, and even sooner in smaller clusters. The rate should probably be something like 10% of the cluster every 5 minutes. And the number of nodes per time interval should possibly be exponential rather than constant, so that we can start off very slowly.

ref/ #13412 

@gmarek

**Comment by gmarek** [comment]
I agree with @davidopp, that current constants are too aggressive. The change wouldn't be only in tweaking the values themselves, as they should change in runtime, adapting to the cluster size changes (it gets more important with cluster autoscaling turned on). I'm not quite sure if current implementation of rate limiter allows any updates, but if it don't we'd need to add this feature.

**Comment by quinton-hoole** [comment]
It's not clear to me precisely what the aim of the rate limiting parameters are. 
Is it:
1. To provide a damper for intermittent intra-cluster partial network outages (e.g. a browned-out switch or router).  If so, the implicit goal is to prevent pods from being evicted en-masse for "short-lived, frequent brown-outs", but correctly evict relevant pods, given time, for "long-lived, infrequent, black-outs"  In this case the settings need to be based on real data data pertaining to such network outages.
2. To provide mitigation for control system software bugs which might cause nodes to be incorrectly reported as NotReady.  If so, the implicit goal here is to create enough delay as to allow humans to get paged and roll back the relevant software, or push some emergency button to prevent pods being evicted en-masse.  Same argument applies - lets figure out what signal pages them, and how much time they need to effect the necessary mitigation.
3. Something else?
4. Some combination of the above?

I think that we should answer the above questions, and those answers will inform how the limits should be expressed, and what the settings should be.  Initially it looks like the numbers should be expressed in such a way as to generate a noticable signal within some short period of time (to trigger alerts), but delay "catastrophic shutdown" for some longer period, based on how long it takes to get humans involved to intervene.

**Comment by quinton-hoole** [comment]
@davidopp @gmarek ^^

**Comment by davidopp** [comment]
@quinton-hoole I agree that initially the feature was intended for (1), and using it for (2) might require different timeout parameters and thus not work well. But I'm don't think we have relevant data to pick a value for case (1) or to know if the same value can be used for case (2) yet. Until then we probably just have to make something up and let the user tune it if they don't like it. Certainly the policy setting we have now doesn't make a lot of sense since the best case is we wipe out the cluster in 15 minutes; I suspect people are generally using Kubernetes at small cluster sizes (say, 40 nodes) in which case we will wipe out the cluster in 5 minutes. That can't be the right thing to do.

**Comment by gmarek** [comment]
Somehow I missed this thread...

I think that we believe that it's enough to require multiple "probe failures" (it's not a probe, nor failure, but semantically can be seen as such) to start evicting the Node, to distinguish short brownouts from long blackouts. This is for half of the (1). Original reason was to limit the damage if the master machine is the one with network problems.

Unlike @davidopp I think that actually we aim at (2) - namely doing it slowly enough to allow human to react (e.g. turn off the master on the problematic machine) . My gut feeling is that the alert will/is/should be triggered by the number of 'NotReady' Nodes as it precedes eviction by few minutes.

Having said that, I do think exactly as @davidopp does - current semantics of deleting X Pods per minute, despite the size of the cluster makes no sense, whatever the reason for this feature. It should specify in what time do we want to be able to empty the cluster fully, as this is the number that user can easily understand.

As for linear vs. exponential - I don't have any opinion. Currently it's linear because that's the only implemented rate limiter we have.

**Comment by quinton-hoole** [comment]
@davidopp @gmarek makes sense to me.  

* Alerting on percentage of nodes not ready in a cluster (e.g. something like 5% by default)  with an optional absolute lower bound of about 3 nodes, to squash noisy single-node and double-node failure alerts in small clusters makes lots of sense.
* Limiting the minimum cluster drain duration to something like 30-60 minutes (by default) should give humans time to respond in most cases, yet not unnecessarily slow down pod eviction rates.  The burst rates (perhaps 10% of nodes by default, with an absolute minimum of 3 nodes) should allow replication controllers do their magic quickly enough even on small clusters.

So I guess in summary I think that we need limits expressed as both a % of cluster to handle "normal" sized clusters, and an absolute lower bound to cater for "very small" clusters.

Q

**Comment by gmarek** [comment]
Agreed. IIUC we need another implementation of rate limiter...

**Comment by davidopp** [comment]
We could also re-evaluate the timeout periods (e.g. to move node to Unknown) at the same time.

**Comment by mml** [comment]
Has this caused an outage yet?  I agree that percentages are more general, but knowing that all clusters  are <= 100 nodes we can choose more sensible defaults.  At that scale, I would set `--deleting-pods-burst=1` and `--deleting-pods-qps=0.0033` (1/300) as defaults.  This limits you to 1 every 5 minutes.  Still a little fast for tiny clusters, but reasonable for the 40-100 scale.

For users who have a specific size failure domain they want to clear out quickly--say a switch--, I would recommend setting `--deleting-pods-burst` to that size, only, and leaving `qps` alone.

I wouldn't prioritize re-doing this as percentages until the distribution of cluster sizes is broader.

**Comment by quinton-hoole** [comment]
There is a fair bit of testing going on with 1,000 node clusters, and we'd like clusters around that size to work well.  But even so, I think that your model works quite well.

**Comment by davidopp** [comment]
> Has this caused an outage yet?

Yes, see the first couple of entries in #13412.

> knowing that all clusters are <= 100 nodes we can choose more sensible defaults

As @quinton-hoole alludes to, we are quickly moving to larger cluster sizes -- hundreds of nodes for the 1.1 release, >= 1000 for the 1.2 release -- so I do think we want to move to percentages soon.

**Comment by mml** [comment]
In reply to my last update, I was thinking in terms of machines when I wrote the suggestions for default values.

Taking a step back, as @quinton-hoole asked in a different way, why not just delete all pods the moment a machine becomes unreachable?

To prevent instantaneous cluster destruction when things aren't actually/completely broken:

1. The unreachability might actually be due to the master machine being broken.
2. Network partition (similar to 1).
3. Bug in the master.
4. kubelet may be hosed, but the pod is actually serving fine.

We discussed two ways to address this:

1. rate limit deletions and
2. stop deleting at a certain point (X% of machines down, or minimum Y machines left standing, both parameters)

(2) is really handy because:

1. it absolutely limits the damage in the case of certain bugs/situation
2. it gives an easy threshold on which to page
3. if you set up such a page, it offers an easy way to over-allocate so as to ride out most non-pageable machine loss events

There may be some users who find the rate limiter useful (those where a large fraction of machines may routinely get broken, probably bare metal customers), but I would wait for them to contact us.  My gut says that most users, especially users on VMs, will find the percentage easier to reason about.  In this case, I believe we can also drop the burst parameter.

So I argue for a new parameter, `--deleting-pods-max-machine-fraction` with a default of `0.1`.  We'd round up to the next whole machine, so in a 3-machine cluster, `0.1` means 1 machine.

@davidopp @gmarek

**Comment by gmarek** [comment]
I completely agree with everything except last paragraph. I'm not certain that rate of pod deletion is interesting, we want to rate limit node deletion (which you did in your example, so I guess that's what you actually has in mind). Second thing is that your flag misses the time interval, so it should be `--max-node-deletion-fraction-per-minute` (or something).

As for concrete value - if it's per minute then I guess 1% would be good (burstable to at least one machine), as this would mean that deleting everything would take over an hour and a half, leaving quite some time for human to intervene. 10% is probably a bit high for that.

**Comment by mml** [comment]
@gmarek you're right that this flag means percent of nodes.  The name I chose is sloppy.

But time isn't a factor here.  My proposal is that this is an absolute stopping point.  If nodes become unreachable, we will delete the pods on them only up until X% of the machines are unreachable at once.  Once the problem goes further than that, we'll stop.  This would prevent the kind of outage seen in #13412.

**Comment by quinton-hoole** [comment]
+1 @mml  I think picking a sane upper limit for auto-recovery from simultaneously unreachable nodes makes a lot of sense.  And yes, around 10% as a default seems like the right limit (rounded up to whole numbers, as you suggest).

**Comment by gmarek** [comment]
OK, so let me repeat what I understood. We want to say that we allow for up to X% machines to be removed 'at once', for some meaning of 'at once', and we want to do it in the node controller, in the loop healthchecking the Node, right? I guess we don't care about the case of crawling failure cause by slow rollout right (it happened internally - as you probably know). We also need to somehow make it work well with cluster autoscaling. 

Summing it up - I believe that there are a lot of corner cases for this approach, so simple rate limiting would be simpler. I'm not strongly against it, but it makes me feel uncomfortable.

**Comment by quinton-hoole** [comment]
@mml One more after-thought that might be useful. 

1. Ideally, in a world where the administrator doesn't actually get paged when the limit gets reached (or loses the page, or whatever), the system should self-recover, with the proviso that it never enters into a "catastrophic failure" state in the process (i.e. as long as the number of unreachable nodes is below the specified limit).  I assert that this is better than it being frozen in an essentially broken and unmanaged state for an arbitrary length of time (possibly forever) until an operator unfreezes it.
2. So this implies that as long as the number of unreachable nodes is less than the limit percentage, the system should continue to terminate pods on the unreachable nodes.  If the limit is reached, it stops. If enough nodes recover, it starts again, etc.  
3. Under certain circumstances (e.g. network brownouts, or master overload situations), this could lead to  a potentially undesirable outcome, namely all pods entering a never-ending cycle or restarts (node connects to master, replication controller restarts pods on it, master overloads, node is disconnected, pods are terminated,.... ad infinitum). 

So I think we still need to make an explicit choice between 1 and 3 above. Do we favor "auto-recovery" (1) at the risk of "possibly endless restarts" (3), or vice verse?  I think that the answer is probably to favor auto-recovery, but I could be convinced otherwise.

**Comment by mml** [comment]
(3) can also happen with a crash-looping or slow kubelet that we nonetheless get contact with periodically.

The most adversarial case is where nodes are almost always unreachable, but the moment they've been unreachable for whatever our timeout duration is, they come back for a split second.  So at any snapshot, less than 1% of nodes are marked bad.

I don't think we need to pick between (1) and (3).  We can solve both by just adding a rate limiter, but I favor not adding another parameter.

What if we combine the two parameters we already have: node timeout and max % nodes removed.  If the admin says nodes are "timed out" after 10 minutes and they'd like no more than 10% of nodes removed at once, I think we can also infer that within any 10 minute window, we don't want to do removals totalling more than 10% of the cluster, regardless of current conditions.

Thoughts?

**Comment by quinton-hoole** [comment]
@mml That's a perfectly reasonable solution, but it doesn't really solve what I tried to express in (3) above.  All it does (I think) is rate limit the endless restart cycle that I described.  Concretely, using your example parameters, every pod in the cluster will probabilistically restarted once every 100 minutes, potentially forever.   

To be clear, I think that's probably fine.  But I think it amounts to us "favoring auto-recovery (1) at the risk of possibly endless restarts (3), rather than solving both.

Make sense?

**Comment by gmarek** [comment]
Ref. #19124

**Comment by mml** [comment]
I'm not working on this right now.  Not sure anyone is.

**Comment by kargakis** [comment]
@kubernetes/sig-scalability-misc

**Comment by gmarek** [comment]
Actually I fix this a year ago.
