### ISSUE TITLE
Permission problem when reading metadata using "Volume Plugi-In"

### ISSUE THREAD

**Issue by roldancer** [kubernetes/kubernetes#13438]
Hi All,
    I have some "permission" problems reading metadata (labels, annotation),  my image is using the "java" user, but the metadata is mounted as root, I followed the Develper Guide "Chapter 21.4. Using the Volume Plug-in".
Any idea on how to resolve the problem ? is this feature only ready for root containser user ? 

[java@test2-1-526qi ]$ whoami                  
java
[java@test2-1-526qi ]$ cat /etc/metadata/labels
cat: /etc/metadata/labels: Permission denied

[java@test2-1-526qi ]$ ls -l /etc/metadata/labels
lrwxrwxrwx. 1 root root 15 Aug 31 04:59 /etc/metadata/labels -> .current/labels
[java@test2-1-526qi ]$ ls -ld /etc/metadata/.current/
drwx------. 2 root root 80 Aug 31 04:59 /etc/metadata/.current/

template:

          volumeMounts:
            - name: podinfo
              mountPath: /etc/metadata
              readOnly: false
        volumes:
          - name: podinfo
            metadata:
              items:
                - name: "labels"
                  fieldRef:
                    fieldPath: metadata.labels
                - name: "annotations"
                  fieldRef:
                    fieldPath: metadata.annotations

Many thanks.

**Comment by gmarek** [comment]
Please re-post your question to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes). 

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases. 

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to similar questions, and also familiarize yourself with:
  * [the user guide](http://kubernetes.io/v1.0/)
  * [the troubleshooting guide](http://kubernetes.io/v1.0/docs/troubleshooting.html)

Again, thanks for using Kubernetes.

The Kubernetes Team
