### ISSUE TITLE
Incorrect config filename yields confusing/unhelpful error message.

### ISSUE THREAD

**Issue by squee1945** [kubernetes/kubernetes#13450]
If I name my .yaml file as foo.yaml.2b , I get the following unhelpful error message:

  $ kubectl create -f example-pod.yaml.2b
  error: you must provide one or more resources by argument or filename

--v=9 offers no extra help

**Comment by quinton-hoole** [comment]
---------- Forwarded message ----------
From: Brendan Burns <bburns@google.com>
Date: Tue, Sep 1, 2015 at 9:56 AM

This has been noted previously.  I _think_ that the problem is that if we don't know what it is, we try to treat it as JSON and of course YAML won't parse as JSON.

We could use heuristics to try to guess (or try both, I suppose)

--brendan

**Comment by quinton-hoole** [comment]
Indicating in the error message (or log) that we're assuming the input to be YAML would help.
Or better still, requiring an explicit --format arg unless the file extension is from a small well-defined set (e.g. .yaml, .json etc) might be less confusing.

**Comment by jlowdermilk** [comment]
This failed because the resource builder expects/requires specific filename extensions:
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/resource/builder.go#L167
It does this to allow parsing only schema files in a directory that could contain arbitrary files.

I think the fix is to make the error message print the list of recognized extensions so it looks like
```
$ kubectl create -f example-pod.yaml.2b
error: you must provide one or more resources by argument or filename (*.json|.stdin|.yaml|.yml)
```

**Comment by jlowdermilk** [comment]
Hah. Turns out I already fixed kubectl to skip the file extension check in #10866. Should probably cherry pick it so the next 1.0.x gets the fix.

**Comment by quinton-hoole** [comment]
For what it's worth, I think that sensible error messages are more important than allowing arbitrary file names, trying to guess the format, and possibly generating confusing error messages.
