### ISSUE TITLE
Adding coarse-grained security policy at service and namespace levels

### ISSUE THREAD

**Issue by L-MA** [kubernetes/kubernetes#13459]
In follow up to the discussion in the [micro-segmentation thread in kubernetes-sig-network] (https://groups.google.com/forum/#!topic/kubernetes-sig-network/bQ0g4ppxu2Q), I would like to propose an API standard for coarse-grained security policy at the service and namespace levels.

I propose adding a `private` option to the `ServiceType` field, where `private` services are only accessible within their namespace. The `ClusterIP`, `NodePort`, `LoadBalancer` service types will be unaffected by the proposed additions. 

In addition, I propose adding a `networkPolicy` field to namespaces, with `private` or `public` options.  Pods within a `private` namespace are only accessible by pods within the same namespace.  Pods within a `public` namespace are accessible from anywhere in the cluster. 

A service should inherit its policy from the namespace it belongs to; therefore, if a namespace has a private networkPolicy, services within the namespace will have a private type, unless otherwise specified. Similarly, if a namespace has a public networkPolicy, services within the namespace will have a ClusterIP type, unless otherwise specified.

These proposed additions to the API will be implemented by the network plugin. If the network plugin does not support them, the default behavior will not break applications. The current default behavior in Kubernetes equates to namespaces with a public networkPolicy and services with a ClusterIP type. This will not change for the 1.X releases in order to maintain backward compatibility.  For 2.0, the default should change to a private namespace networkPolicy and a private service type. If a more open policy is desired, it must be specified in the spec. 

I’m keen to get more general feedback from the community on this as I begin to look into implementing it in the API.

**Comment by caseydavenport** [comment]
cc @thockin @symmetric

**Comment by rajatchopra** [comment]
Definitely useful.
Though 'namespace' is assumed here for a group of pods. 

An extension of 'group of pods' could be expressed using labels. Say, by using labels.Selector and fields.Selector we could specify who all are allowed to use the service. The advantage is that a service can then define arbitrary set of pods that it is available to, rather than just everyone only and within its namespace.
Same for networkPolicy, saying 'private' probably means namespace=<inherit>, labels=labels.Everything(), 'public' likely means namespace=NamespaceAll,labels=labels.Everything()

**Comment by caseydavenport** [comment]
I agree that label-selection semantics are a powerful and useful addition here, but I think of that as function that should be added to the API after this first baby-step.

As a tactical first step towards richer (label-based) policy, I'd suggest:
```
namespace:
  networkPolicy: [ Open | Closed ]
```
```
service:
  spec:
    type: [ clusterIP | Open | NodePort | LoadBalancer ] 
```
> I recognize that clusterIP in this case is a bit of a misnomer, and would advocate it being renamed to something like `NamespaceLocal` or something appropriate down the road, at which point `Open` might be renamed to `ClusterLocal` or something appropriate.

Pods within an `Open` namespace are accessible cluster-wide, and pods within a `Closed` namespace are only accessible within their own namespace.

Open namespaces should only be used if you _really_ want everyone to be able to access the pods within that namespace (or if you just don't care about security), so Services within an open namespace would always be globally accessible.  Essentially, open namespace == no security policy on pods within that namespace.

Services within a closed namespace would by default be accessible only by pods within the same closed namespace (on declared ports), but could poke holes through the namespace boundary if they are declared as `Open`, `NodePort`, or `LoadBalancer`.

This doesn't prevent adding more fine-grained security policy down the road, rather it gets the ball rolling in terms of getting network policy defined in the API.

**Comment by spikecurtis** [comment]
+1

**Comment by Symmetric** [comment]
I'd suggest a slight change from the above as suggested by @caseydavenport:

    service:
      spec:
        type: [ clusterIP | Closed | NodePort | LoadBalancer ] 

The current definition of "clusterIP" is:

>  "ClusterIP: use a cluster-internal IP only - this is the default and is discussed above. Choosing this value means that you want this service to be reachable only from inside of the cluster.

That maps onto "Open" as discussed above. Therefore the Service Type that we should add is "Closed", because we can't re-define clusterIP to mean "only accessible to the namespace" for the case where Namespace.networkPolicy=closed.

A separate question is what behaviour should be default. I think that Namespace.networkPolicy=closed and Service.type=closed are both the appropriate defaults (i.e. allowing access outside of a namespace should be a conscious decision on the part of the app developer). This change to the defaults will have to wait for API v2 of course.

One other point to explicitly note -- how do we deal with headless services? I think the current API here is OK, since headless vs. not-headless is orthogonal to open vs. closed. (i.e. we want to be able to configure all 4 combinations of the 2 variables).

**Comment by spikecurtis** [comment]
Can I suggest `Namespace` rather than `Closed`?  I think "closed" is an ok way to describe a namespace policy, but it's not very intuitive to say a service is "closed".

**Comment by quinton-hoole** [comment]
@kubernetes/goog-cluster

**Comment by Symmetric** [comment]
Or maybe "NamespaceIP" to mirror "ClusterIP".

**Comment by pmorie** [comment]
@deads2k

**Comment by smarterclayton** [comment]
I would want to create node port and load balancer services that can't be accessed from the normal pod network (without going through the balancer), because the balancer may impose security policy.  So I think the original proposal or a separate networkPolicy field is more flexible.  I didn't see a reason upthread not to introduce a separate field.  Also, if the network plugin is incapable of supporting isolation then having a service type have no effect is less impactful to generic clients.

**Comment by pedro-r-marques** [comment]
In my view, one needs to define the goal for security policy. This goal should be to be able to describe what are the list of allowed traffic flows between application tiers as well as limit the impact of a security vulnerability that compromises one or more pods of an app tier.

I'd like to propose the following api changes:
```
type PodSpec
    // Name of network access control group. Defaults to "namespace/default" when not specified.
    Network string
    // List of service network groups accessed by this pod.
    Services []string
```

```
type ServiceSpec
    // Service network name. Defaults to "namespace/services".
    Network string
    // Access list of client network names using regular expressions. Defaults to "namespace/ . *".
    ClientAccess []string 
```

A "namespace closed" policy as defined above in the thread is implemented by the default settings. An open policy for the service can be implemented by defining a client access regex of ".*/.*". Using tags allows any other combination and follows the k8s practice of using "selectors.

**Comment by caseydavenport** [comment]
@smarterclayton - What sort of security policy are you expecting the LoadBalancer to enforce in this case that shouldn't be done at the service level instead?

The problem I see with allowing a configuration where, for example, "NodePort" and "Closed" are not mutually exclusive on a Service is that NodePort is inherently opening that service outside of the namespace (since Nodes are not in a namespace).  So,
```
Service:
  spec:
    type: NodePort
    access: NamespaceOnly # (Closed)
```
Doesn't really make sense, since Nodes are not part of any namespace.  Do you allow traffic from the NodePort, even though it is outside of the namespace?

This case suffers the same problem:
```
Service
  spec:
    type: LoadBalancer
    access: NamespaceOnly
```

We could dis-allow these configurations, but then "NodePort" and "LoadBalancer" mandates the "Open" access level, so then "Open" is really just a type below NodePort and above clusterIP.

You could (eventually) limit traffic flows in the way you suggest with fine-grained policy.  For example it might look something like this (Please note I am not suggesting tackling fine-grained policy just this minute, this is just hypothetical):
```
Service:
  spec:
    type: LoadBalancer
    networkPolicy:
      - allow from loadBalancer
      - reject
```

Thoughts?

**Comment by smarterclayton** [comment]
Security policy on load balancer is things like running an Apache process with mod_sso that requires all http requests to services behind it to have a valid cookie from the central domain controller.  Or denying ingress to a set of services because the source packet has an IP from outside the cluster network.  That isn't really something the API expresses - that's an implementation detail of the load balancer configuration.

Note that I expect load balancers to cover multiple services in many cases - there are certainly times where there is only one, but ingress paths and Openshift routes are both designed to program L7 balancers in easy to use ways in bulk.

**Comment by smarterclayton** [comment]
Having simple network policies on services is good, but it should also be an easy option for an admin to make those choices on top of the cluster (out of the users purview) based on other criteria

**Comment by Symmetric** [comment]
@smarterclayton in the SIG-network we've been talking about attaching richer policy to Services (or creating a Policy object that selects pods as Services do), and I think that would be the way to implement the sort of LB policy you're talking about. I think that's the next iteration though, and I don't think this proposal closes the door on the sort of richer policy that you want.

In the next iteration we're going to need something more expressive than just "Type=NamespaceIP" (or however we decide to name that option); possibly a "Policy" field where we can specify more fine-grained access controls.

As Rajat says, selecting pods based on Namespace is just the simplest way of grouping pods. I'd like to be able to define this sort of policy on a Service:

```
Service:
  Policy:
    - allow from service A
    - drop
```

Where Service A could a headless service (just to select some pods), a normal service, or a custom EndpointSet (to manually select the IPs of all your provisioned load balancers, or other such non-kubernetes infrastructure).

I agree that we should be able to impose cluster-wide policy as well; this would be a good use-case for a generic Policy object that could select all pods (rather than having to use a Service to apply the policy).

I'm hesitant to pull the namespace isolation behaviour out into a separate field, because as @caseydavenport says, how do we enforce a NodePort service with Service.NetworkPolicy=Closed? I think it's better to scope this change in behaviour tightly (i.e. just add a single Service.Type for this behaviour), and not to try to cover LoadBalancer and NodePort services in this iteration.

**Comment by smarterclayton** [comment]
As long as we can come up with good justifications.  My concern is that policy growth leads to rules that are not quite NamespaceIP or ClusterIP - for instance, I doubt any user wants a service that is purely namespaced scope forever, or at creation time, is not sure.  A cluster scoped IP is required to do some forms of inter-cluster communication and has the benefit that it is future proof when a user wants to share a service across namespaces.  If we have both policy and type, and I have to change type sometimes and policy other times, then we've created an unclear API.  We could introduce a policy sub object today and simply say that you can't set policy on nodeports - it means the policy and type have subsets that are not allowed (like other existing fields on other objects).  

I would also note that I would expect to reserve NamespaceIP for a future where the IP was only unique to the namespace (since ClusterIP means you get a unique cluster ip).  However, having namespace unique IPs restricts the users future choices - I can't switch from NamespaceIP to clusterIP without possibly reallocating my IP, which defeats one of the goals of services.  Service ip mapping is an option, but that still requires a unique ip visible to other parts of the space that cannot overlap.  We make strong statements today about the Kube network and service space being flat, and some change is necessary to make that work, but for instance I would not want DNS to a service to resolve different in two different namespaces in the cluster unless we had a really compelling use case.

**Comment by Symmetric** [comment]
I see your point regarding API clarity. I'd note, though, that in the linked PR these fields are marked 'experimental', to attempt to get something in users' hands before trying to build the final policy API.

As an endgame, I tend to agree that it would be clearer to put all policy in a 'policy' attribute, rather than having both 'policy' and 'type=NamespaceIP', since 'Policy' can describe a superset of the function described here. But agreeing on the semantics and syntax for Policy is a big undertaking, which is why @thockin was keen to try to get something simple in first.

Also, doesn't Type=LoadBalancer also create a NodePort? The [docs](http://kubernetes.io/v1.0/docs/user-guide/services.html) seem to suggest so. If we can't support a particular policy on NodePort service, then how can we support it on a LoadBalancer Service?

Introducing overlapping IP ranges in Kubernetes seems like a very significant change to the k8s networking contracts; is that a use-case we need to plan for? I hope not, but I'll defer to those with more knowledge of the roadmap on that one; I don't know if it's a likely enough scenario to reserve the name for. That said, happy to switch to some other name (@thockin originally suggested Service.Type=Closed, I also suggested Private) if NamespaceIP is too loaded a term.

**Comment by smarterclayton** [comment]
I didn't have a concrete use case for a namespace scoped IP, but
naming-wise I think it could be construed ambiguously.

Regarding fields that only apply to certain types, technically we have
those already with loadBalancerIP.  I lean slightly towards introducing a
simple policy object with one field than adding a type because it's easier
for older clients to ignore a field they don't understand vs a value in an
enumeration.  It's much more likely to break simple clients and simple API
consumers.

**Comment by thockin** [comment]
The network SIG is working on a proposal, so I am closing the existing proposals.  Please reopen if you think I am wrong. :)
