### ISSUE TITLE
CoreOS: discovering node/minion etcd address within pod container

### ISSUE THREAD

**Issue by bkeroackdsc** [kubernetes/kubernetes#13465]
Similar to the issue described [here](http://blog.dixo.net/2015/02/discovering-etcd-from-inside-a-container-in-coreos/).

My application running within a pod needs to access etcd running within the host CoreOS, so that all pod replicas running on different Kubernetes nodes share the same keyspace (for sychronization purposes).

Is there an easier/less-hackish way to achieve this other than running ``route |grep default |awk '{print $2}'`` within the container?

**Comment by bkeroackdsc** [comment]
I suppose the other option is to run etcd within the pod, but I'm not clear on how I could get the etcd to form a single cluster among all the pod replicas.

**Comment by quinton-hoole** [comment]
Yes, you should not be trying to access services running on the host from within your pod.  Rather run etcd in pods.

Please re-post your question to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes). 

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases. 

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to similar questions, and also familiarize yourself with:
  * [the user guide](http://kubernetes.io/v1.0/)
  * [the troubleshooting guide](http://kubernetes.io/v1.0/docs/troubleshooting.html)

Again, thanks for using Kubernetes.

The Kubernetes Team
