### ISSUE TITLE
Enhance Rolling-Updates to support updating image with multi-container pods

### ISSUE THREAD

**Issue by mingfang** [kubernetes/kubernetes#13483]
As of 1.0.3, rolling-update with --image does not work when pod has multiple containers.
This is the error message
```error: Image update is not supported for multi-container pods```

**Comment by JanetKuo** [comment]
Ref #9868

**Comment by coleca** [comment]
Is this planned for 1.1?  It would be really helpful to use for pods using the sidecar patterns in a CI environment.

**Comment by JanetKuo** [comment]
@coleca It's not planned for 1.1.

**Comment by mingfang** [comment]
PR #9868 appears to not make any progress.
Being able to do rolling updates is key to our team's ability to use kubernetes.
Do we know what ballpark timeframe to expect this feature to be released?

**Comment by JanetKuo** [comment]
cc @bgrant0607

**Comment by bgrant0607** [comment]
The author of #9868 never addressed review feedback and never responded to requests to rebase. It's been inactive since July. I just closed it.

kubectl rolling-update can be used for multi-container pods. It's only the --image convenience feature that doesn't support it.

We're working on a server-side implementation of rolling update. It will be possible to enable the experimental API in 1.1:
https://github.com/kubernetes/kubernetes/blob/master/docs/proposals/deployment.md

cc @nikhiljindal @ironcladlou

**Comment by bgrant0607** [comment]
@brendandburns, would you be interested in taking this on?

**Comment by bgrant0607** [comment]
#17111 has merged.
