### ISSUE TITLE
Support encrypted disks in GCE (and other platforms)

### ISSUE THREAD

**Issue by brendandburns** [kubernetes/kubernetes#13493]
http://stackoverflow.com/questions/32310849/use-gcloud-self-encrypted-disk-with-kubernetes

The user wants to use encrypted disks with their pod.

**Comment by erictune** [comment]
My reading of the the Google docs (https://cloud.google.com/compute/docs/disks/customer-supplied-encryption) are that no key is required to mount the disk.  The keys are only provided at disk creation time.

So, the following should work without changes to kubernetes:

1. create encrypted disk "myencrypteddisk" per https://cloud.google.com/compute/docs/disks/customer-supplied-encryption
1. create a pod which mounts GCEPD called "myencrypteddisk".
1. kubelet will mount the disk on the VM.  It's compute scope should be enough to perform the mount, IIUC.

**Comment by erictune** [comment]
Posted same on Stack Overflow.

There might still be an issue with PersistentVolumes, but that wasn't requested.  

Closing this issue.

**Comment by pkyeck** [comment]
I tried the above but received an error message saying:

> Failed to attach volume "myencrypteddisk" on node "<mynode>" with: googleapi: Error 400: projects/<projectname>/zones/europe-west1-c/disks/myencrypteddisk is protected with a customer supplied encryption key, but none was provided.

Did anyone got this to work?

**Comment by artooro** [comment]
I'm surprised there has been no movement on this issue. @pkyeck I assume you never found a way to make this work.
I tried now but not getting any further with the "volume ... is protected with a customer supplied encryption key, but none was provided" error.

Using "customer managed" keys instead of "customer supplied" does work. But you could argue that it does not offer the same amount of security.

We do need a way to provide the decryption key to the storage provisioner so encrypted volumes can be mounted.

**Comment by pkyeck** [comment]
@artooro nope, but haven't tried in a while ...
