### ISSUE TITLE
Don't rely on gcloud for `e2e` tests

### ISSUE THREAD

**Issue by ihmccreery** [kubernetes/kubernetes#13535]
All of our e2e tests should rely on [google-api-go-client](https://github.com/google/google-api-go-client/) rather than `gcloud`.  There are several TODOs of this sort in `cluster_upgrade.go`.

**Comment by ihmccreery** [comment]
If we need motivation besides that `gcloud` is a terrible dependency to have, some tests have been brittle because `gcloud` is picky about placement of flags:

```
error running gcloud [compute instance-groups managed --project=k8s-jkns-gce-living-upgrades --zone=us-central1-f describe gce-upgrade-minion-group];
got error exit status 2, stdout \"\", stderr \"usage: gcloud compute instance-groups managed describe  NAME [optional flags]\\nERROR: (gcloud.compute.instance-groups.managed.describe) unrecognized arguments: --zone=us-central1-f\\n\""

`--zone` is a valid argument, it just can't come before `describe ...`.

**Comment by gmarek** [comment]
cc @brendandburns

**Comment by justinsb** [comment]
FYI, the AWS e2e tests avoid relying on the AWS CLI.  They check to see if the cloudprovider implements an interface and if so call into that interface.  I would love to promote those interfaces into cloudprovider, not least because I think they may prove generally useful as we add more functionality:

https://github.com/kubernetes/kubernetes/blob/95a60d60856987f36fc666252d1e74ca9c5d377e/test/e2e/pd.go#L259-L279

https://github.com/kubernetes/kubernetes/blob/bb3e20e361764cf0af8d23671b7fe00f0951b0f3/test/e2e/resize_nodes.go#L45-L64

Happy to rework the AWS ones as well if they are too AWS-y.

**Comment by saad-ali** [comment]
PR https://github.com/kubernetes/kubernetes/pull/17747 laid the ground work for this and switched the GCE PD create and delete calls in E2E from gcloud to the GCE library. It should be much easier now to switch over the remaining gcloud calls in E2E.

**Comment by kargakis** [comment]
@kubernetes/sig-testing-misc

**Comment by fejta** [comment]
/remove-area test-infra
/remove-sig testing

https://github.com/kubernetes/kubernetes/search?p=1&q=gcloud+path%3Atest%2Fe2e&type=&utf8=%E2%9C%93

/sig storage
/sig scalability
/sig scheduling
/sig network

**Comment by cmluciano** [comment]
Is this still relevant?

**Comment by spiffxp** [comment]
/remove-area test-infra
/area test
/sig gcp
Yeah, this is still relevant, there are plenty of usages of `gcloud` in `test/e2e`
