### ISSUE TITLE
Add support for Quotas on Running Pods

### ISSUE THREAD

**Issue by cameronbrunner** [kubernetes/kubernetes#13567]
This is a continuation of a discussion started in the #sig-scheduling kubernetes slack channel between @davidopp, @smarterclayton, and @quinton-hoole.

Fundamentally the quota system prevents the 'creation' of pods but has nothing (as far as I can tell) to do with the 'running' of pods.  There are lots of reasons why a pod can't get get to the 'Ready' state especially in a resource constrained cluster.  What a 'running' quota would do is not penalize a given user/namespace for having pods that can't be scheduled.

A simple example would be a namespace with a quota of 4 pods that current has 2 ready/scheduled pods and 2 pods that can't be scheduled and may not be able to for quite a while.  Given a the current quota system a new pod could not be created in this namespace.  With a running quota system of 4, however, 2 additional pods could get scheduled.

I believe that this is the time to address this functionality because the addition of the JobController, and support for batch workloads in general, will increase the potential of a given Kubernetes cluster to be resource constrained.

**Comment by smarterclayton** [comment]
@derekwaynecarr for limits and quota and @bparees @solytsh for builds and
jobs

On Sep 3, 2015, at 2:50 PM, Cameron Brunner <notifications@github.com>
wrote:

This is a continuation of a discussion started in the #sig-scheduling
kubernetes slack channel between @davidopp <https://github.com/davidopp>,
@smarterclayton <https://github.com/smarterclayton>, and @quinton-hoole
<https://github.com/quinton-hoole>.

Fundamentally the quota system prevents the 'creation' of pods but has
nothing (as far as I can tell) to do with the 'running' of pods. There are
lots of reasons why a pod can't get get to the 'Ready' state especially in
a resource constrained cluster. What a 'running' quota would do is not
penalize a given user/namespace for having pods that can't be scheduled.

A simple example would be a namespace with a quota of 4 pods that current
has 2 ready/scheduled pods and 2 pods that can't be scheduled and may not
be able to for quite a while. Given a the current quota system a new pod
could not be created in this namespace. With a running quota system of 4,
however, 2 additional pods could get scheduled.

I believe that this is the time to address this functionality because the
addition of the JobController, and support for batch workloads in general,
will increase the potential of a given Kubernetes cluster to be resource
constrained.

—
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/13567>.

**Comment by derekwaynecarr** [comment]
There were earlier discussions on where quota should be enforced.  I do not want to enforce quota in the scheduler, that is problematic if/when you run multiple schedulers, so if we change something we need to change how our admission controller operates.

A simple option of enforcing a running quota is to only charge against the quota pods whose podSpec.NodeName != nil in admission control.  The ramification there is that the scheduler would be told no to a pod creation request instead of what happens today, the replication controller is told no.

I need some time to think through that concept.  It has merits if/when we move to more lazy initializers that are not in our current admission controller sequence.

Right now, the more pressing issue for quota is to merge https://github.com/kubernetes/kubernetes/pull/12600

**Comment by derekwaynecarr** [comment]
Thinking a little more, I think we need to enable the ability to modify resource requirements on a container that is not yet scheduled before entertaining this idea further.  If we admit the pod and do not cost it against your quota until its nodeName is filled out, we need to ensure that if the pod had no resource requirements that it could be adjusted by another component.

I think the idea has a lot of merit when quota compute resources (memory, cpu) since you really should only be charged for usage of that compute resource when the pod is actually scheduled and running.

For object count quotas (#of pods, #of services, etc.), I am not sure if I agree with the desired change.  In those instances, you are also limiting to just restrict unbounded object growth in etcd.

Needs more thought to evaluate any edge cases.

**Comment by derekwaynecarr** [comment]
@cameronbrunner - are you really interested in quota-ing the number of pods, or are you more interested in quota of memory/cpu that those pods consume?  If its the latter, I think it makes a ton of sense to only charge the quota usage for compute resources when the api server receives that schedule request.  If we only charge for compute resources at schedule time, then a JobController can spawn as many pods as it wants, and the api server would prevent scheduling until quota was available unless in your case you are running pods that specify no resources and are best effort.  That also is problematic, so I am not sure I want to promote that and instead would assume most jobs are filled by burstable / guaranteed pods on memory at least (if not cpu).

Need to ensure that scheduler would respond well to being told no and backoff appropriately.  We had issues with the replication controller prior to 1.0.

**Comment by davidopp** [comment]
If we record the quota usages as etcd objects and have multi-object transactions then sharded scheduler should be fine (bind a pod in same transaction as you update quota usage).

**Comment by cameronbrunner** [comment]
@derekwaynecarr - The most important aspect to me is adding the concept of a running quota so if we want to start with actual host resources that is perfectly fine with me.

As for your concerns regarding the scheduler handling quotas; could you provide a couple of details or point me to the issue where this was discussed in the past?

**Comment by smarterclayton** [comment]
Actually, we don't even need that today, because we can do it during bind
which is a distinct API path and so we can apply the admission controller
for quota there.

On Sep 4, 2015, at 3:56 AM, David Oppenheimer <notifications@github.com>
wrote:

If we record the quota usages as etcd objects and have multi-object
transactions then sharded scheduler should be fine (bind a pod in same
transaction as you update quota usage).

—
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/13567#issuecomment-137672992>
.

**Comment by davidopp** [comment]
Actually, we already have a problem with multi-scheduler (to be clear -- if we were to run concurrent schedulers, not the HA scheduler failover mechanism we're using today), which is that two schedulers can bind two different pods to the same machine at the same time without any check before they are committed to etcd. (There will be no resource version conflict on the Pods, since they are different Pods.)

Doing a quota check at binding time has exactly the same problem as doing a predicate check at binding time. The solution to both of these is to make sure concurrent bindings conflict on some object. I was actually discussing this with Brendan recently. He mentioned that a long time ago we had boundPods to address the problem I mentioned in the previous paragraph, but we got rid of that. Analogously, if we do quota check at binding time, we'd need a version precondition on some object representing the in-use quota, that would cause the binding request to fail if it is mutated concurrently.

**Comment by smarterclayton** [comment]
For sure - just highlighting that we can approximate bound resource
tracking without multi-commit.

On Fri, Sep 4, 2015 at 3:15 PM, David Oppenheimer <notifications@github.com>
wrote:

> Actually, we already have a problem with multi-scheduler (to be clear --
> if we were to run concurrent schedulers, not the HA scheduler failover
> mechanism we're using today), which is that two schedulers can bind two
> different pods to the same machine at the same time without any check
> before they are committed to etcd. (There will be no resource version
> conflict on the Pods, since they are different Pods.)
>
> Doing a quota check at binding time has exactly the same problem as doing
> a predicate check at binding time. The solution to both of these is to make
> sure concurrent bindings conflict on some object. I was actually discussing
> this with Brendan recently. He mentioned that a long time ago we had
> boundPods to address the problem I mentioned in the previous paragraph, but
> we got rid of that. Analogously, if we do quota check at binding time, we'd
> need a version precondition on some object representing the in-use quota,
> that would cause the binding request to fail if it is mutated concurrently.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kubernetes/kubernetes/issues/13567#issuecomment-137829324>
> .
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by bgrant0607** [comment]
I don't see a compelling reason for this change, and it would break backward compatibility.

If anything, I'd think users would want even earlier admission-control decisions, such as at the RC or Job level rather than when pods are created. That's what creates the reservation that prevents even more work from entering the cluster. Enabling more pods to enter when some are already unable to schedule doesn't seem like the right direction.

Yes, resource fragmentation may be a problem. There are a number of (complementary) solutions to that:
* auto-scaling of the cluster
* oversubscription via lower levels of quality of service: https://github.com/kubernetes/kubernetes/blob/master/docs/proposals/resource-qos.md
* vertical auto-sizing, to only reserve what is needed: #10782
* rescheduler to rebalance: #12140

**Comment by bgrant0607** [comment]
With batch specifically, a lot of work has been done on queuing systems -- LSF, Maui, SLURM, ...  Defer execution if the cluster is too busy.

A horizontal auto-scaler could also be aware that some instances were unable to schedule and then downsize. ReplicationController already favors killing pods that are pending or unhealthy.

**Comment by cameronbrunner** [comment]
When I was first considering of this change I was thinking of the traditional queuing systems where quotas are enforced against submitted jobs as well as running jobs.  In traditional queueing systems submission limits are typically meant to bound the max resource usage of the scheduler when submission rates are consistently exceeding completion rates while runtime limits are typically used to enforce a piece of the overall sharing policy of the underlying resources.  Using batch terms to describe the current Kubernetes model it appears that quotas are only enforced at the submission level with controllers periodically attempting to 're-submit' until they reach their desired state.

Some more background of where I was coming from with this request - I was considering general pod prioritization together with this change to provide a base for more sophisticated resource sharing policies in Kubernetes.  I believe pod prioritization is a much bigger challenge but thought the runtime quota component was valuable on its own.

 The combined use case of these two features that I was considering was a single user with multiple JobControllers that should complete in a specific order and use as much resources as the user is authorized while still allowing user ReplicationControllers to be created and scaled up.  The user should be able to create the job controllers and walk away knowing that this workflow will complete as expected.  The current system can't handle this use case because the only quota system is on admission so all of the controllers are 'competing' to get the next pod into the system when doing their looping submit.  Having a runtime quota lets each of these controllers get some pods created which could then be scheduled on based on priority.

Also I definitely agree that horizontal scaling does address all of these problems.  Oversubscription may be doable as well given the nature of the work being run by the JobContoller (it would be bad to start more concurrent tasks if that actually increased  the overall controller runtime.

I know I am bringing up some other topics with this comment and will break any of this out into other issues if desired.

**Comment by davidopp** [comment]
@cameronbrunner Thanks for your additional explanation.

@bgrant0607 I think there are probably some workloads where you want admission control at the RC or Job level (i.e. the atomic unit of admission is the RC or Job), but I can imagine cases where you don't really care about the whole collection running simultaneously, you are fine with parts running as resources become available. Also, one problem with doing admission control at the RC or Job level is that these controllers are not integrated with the scheduler, so they have no way of knowing whether it will be productive to create a Pod (i.e. whether it will actually be able to run or will stay pending). So in our current quota scheme, there's really no guaranteed way for them to avoid wasting quota sometimes, which unnecessarily blocks other controllers from creating Pods that could be able to schedule. 

I wasn't clear on why you say this feature would break backward compatibility. I assume we would add it as an additional mechanism, not redefine the meaning of the current quota to be running instead of submitted.

**Comment by bgrant0607** [comment]
@cameronbrunner Yes, thanks for the further explanation. It's probably worth creating a batch SIG and discussing the use cases and landscape there before filing specific issues.

We're trying to develop the Job API incrementally. Many issues have been pushed to future iterations: time-deferred scheduling, gang scheduling, budget limits, deadlines, execution-order dependencies, etc. There's a lot we could envision doing in this space, but we're not ready. We don't even have the minimally useful construct yet (other than individual pods). Probably it would be better for people to prototype them and report back their findings.

In any case, the scheduler isn't the right place to build a submission queue. It does placement. Maybe it should be called "the placer", but the terminology was carried over from Borg.

@davidopp Right now, ReplicationController is fairly dumb. However, I envision it getting smarter, such as to deal with rejection by admission control, scheduling failures, crashloops, poison pods, etc. in a graceful fashion.

**Comment by bgrant0607** [comment]
Popping up a level: It's worth discussing what kinds of policies and outcomes users running / admins of batch workloads would want. Execution-ordering priorities (like a Disneyland FastPass -- go to the front of the queue)? Preemption? Background/scavenging? Fairness? Dedicated resource pools? Opportunistic scaling? Off-hours deferral? Deadline scheduling? Gang scheduling? Resource hoarding? Node-level oversubscription? Cluster-level oversubscription?

It's way too early to be designing a new quota mechanism.

**Comment by davidopp** [comment]
> In any case, the scheduler isn't the right place to build a submission queue.

I think the argument against this approach is that the scheduler has the advantage of knowing whether something will actually schedule. The alternative (for some use cases) requires linking the scheduling logic into each controller so they can know whether it will be productive to create a Pod.

To put it another way: I believe that the only way to use our existing admission control mechanism to implement  a cluster sharing policy that's based on what's actually running (rather than running+queued), is to give controllers the ability to bring the "queued" down to zero, which means giving them the ability to know whether a Pod they create will schedule. (Of course one can imagine hacky alternatives like having a controller create a Pod, see if it schedules, then delete it if not, but I think there are a lot of reasons why this is not a good idea.)

**Comment by davidopp** [comment]
I do agree we should have a more holistic discussion about the policies we want (such as the questions you listed) before implementing anything in this direction.

**Comment by bgrant0607** [comment]
cc @mml
