### ISSUE TITLE
Prefix/Suffix cluster name in loadbalancer name

### ISSUE THREAD

**Issue by ddysher** [kubernetes/kubernetes#13577]
Loadbalancer name is now based on service name, this works great but also poses challenges to delete them.  Resources like instances will be prefixed with cluster name, so when deleting, we can easily find them through cluster name (assuming it's unique).  We can of course record the loadbalancers created by user, but it adds states somewhere which I think we'd better to avoid.

The proposed change is simple, just pass `clusterName` to `GetLoadBalancerName`.  Also, it seems different cloudprovider has different rules for loadbalancer name, so we can also move `GetLoadBalancerName` to cloudprovider specific package.  Is there any reason we don't want to do this?

**Comment by quinton-hoole** [comment]
Sounds like a good solution to me.  I'll leave it to the team who work on this to prioritize.  I'm pretty sure that they would be open to a concrete code PR.

@kubernetes/goog-cluster

**Comment by thockin** [comment]
@a-robinson in paritcular

**Comment by a-robinson** [comment]
Your premise is a little flawed - each load balancer name is based on its service's UID, not name.

I wholeheartedly agree with everything else - cluster name should be used in conjunction with service name (and indeed it [used to be](https://github.com/kubernetes/kubernetes/blob/eb253a694e965ae8638d4b45433f812607019e91/pkg/cloudprovider/cloud.go#L45)) and the naming should be cloud-provider specific.

The only issue is how do you make the change to a new naming scheme without disturbing existing load balancers during upgrades? New service controllers have to continue working with old load balancers ad infinitum, so any change to the naming scheme will have to be coded very carefully to ensure support for the older names.

@quinton-hoole also had strong feelings in the past about not just using cluster name, namespace, and service name, at least partially due to how it caused resources to be reused by different e2e test runs. Those concerns might be lessened though by the fact that we now use unique namespaces for each e2e run.

**Comment by quinton-hoole** [comment]
@a-robinson the problem with using service names rather than service UID's is that names are reusable things in Kubernetes, so they're ambiguous over time. Concretely it's possible to create two completely different services with the same name, as long as you don't do it at the same time. But time itself is a difficult concept in a distributed system.  Imagine two asynchronous threads, one creating service UID=x, and the other deleting service UID=y.  If they both have the same name, and you identify the external load balancer using that name, it's ambiguous whether you're dealing with the load balancer for UID=x or the one for UID=y. It's possible to end up with one system (e.g. GCE) trying to asynchronously delete that load balancer, while another system (e.g. kubernetes) is trying to create it.  It's a solvable problem, for sure, but better just avoided all together.  So you avoid a bunch of potential race conditions like that by simply using UID's rather than names.

**Comment by a-robinson** [comment]
Agreed on the issue, and thanks for re-explaining. In GKE we deal with this by appending a short hash to the ends of user-understandable names, which seems like a good usability compromise.

**Comment by ddysher** [comment]
Thanks for commenting.  For loadbalancer name, appending a short hash sounds good to me: this also confirms to how we name other resources.  The problem is how we want to enforce this rule if we allow different cloudprovider to implement their own name?

The concern of backward compatibity is sound, since we did use service name before, is there any concret steps we can follow, or we just break things? @a-robinson

**Comment by quinton-hoole** [comment]
@a-robinson @ddysher one other problem with basing load balancer names on clusterName+namespace+serviceName is that the resulting name often breaks the naming restrictions of the underlying cloud provider (most notably name length restrictions, but there are other incompatibilities between allowable service names vs allowable load balancer names.  Appending a "hash" to the end of the name further exacerbates the name length problem.  If you do chose to use something other than the plain UID (which I'd advise strongly against), please make sure that your scheme works under these constraints.  For example, appending a hash to the clustername+namespace+serviceName does not work on GCE, as the name length restriction on GCE is narrower than that on Kubernetes.

**Comment by a-robinson** [comment]
@ddysher we definitely cannot just break things, and @quinton-hoole's warning about name length is important as well.

**Comment by ddysher** [comment]
@a-robinson Sorry, I meant 'broke things'.  I was trying to say that since we changed the name schema before, there should be some steps we can follow. But since it's pre-alpha at that time, I can understand that we just broke things and there is nothing to follow.

As to @quinton-hoole 's concern about name length.  I think that's part of the reason we want to make the lb name per cloudprovider, so each cloudprovider can enforce its own rules.

**Comment by thockin** [comment]
Is this still open?

**Comment by ddysher** [comment]
It seems we still use service ID as loadbalancer name.  I've hard-coded a little bit to make it work (find all loadbalancers in a cluster); it works, but not pretty.

@thockin WDYT?

**Comment by kargakis** [comment]
@kubernetes/sig-network-misc
