### ISSUE TITLE
links in kubernetes.io/v1.0/docs/api-reference/operations.html fail

### ISSUE THREAD

**Issue by caesarxuchao** [kubernetes/kubernetes#13599]
Start here: http://kubernetes.io/v1.0/docs/api-reference/operations.html, then click the "v1.Binding" link, the correct address http://kubernetes.io/v1.0/docs/api-reference/definitions.html#_v1_binding is shown in the address bar, but the browser doesn't take the user to the section.

cc @RichieEscarez

**Comment by bgrant0607** [comment]
cc @caesarxuchao

**Comment by RichieEscarez** [comment]
Ive looked at this and am pretty sure that the javascript is lacking the logic to recognize those urls with anchors and then scroll down to the right position. 

I think the fix is to:

Instead of 'always' scrolling the page up on load [see this code](https://github.com/kubernetes/kubernetes/blob/gh-pages/_layouts/docwithnav.html#L92), we should instead check for an anchor first (if anchor scroll there, else scroll to top of page).
