### ISSUE TITLE
Impossible to completely eliminate insecure access to apiserver

### ISSUE THREAD

**Issue by eparis** [kubernetes/kubernetes#13598]
The apiserver listens, by default, on 127.0.01:8080 in a completely insecure manor. Even if the scheduler, controller-manager, proxies, kubelets, etc are all configured to use the secure port the apiserver still talks to itself on the insecure port.

https://github.com/kubernetes/kubernetes/blob/master/cmd/kube-apiserver/app/server.go#L340

This is how things like the admission controllers (part of the apiserver) talk to other parts of the apiserver. The problem with having the apiserver talk to itself over the insecure port is that means we cannot block the insecure port from everything else on the host. Any user able to log into the machine running the api-server can connect to the insecure port and do anything they want. Blocking all access to 8080 with iptables means admission controllers and such stop working.

There may be many solutions, but the basic problem is I want to turn off all insecure access to the apiserver.

@liggitt suggested some form of privileged kubeconfig the apiserver would use to talk to itself

It might also be possible to create a unix domain socket pair which only the apiserver could use to talk to itself in an 'insecure' manor similar to how it is currently using the insecure socket, but which everyone else on the host couldn't use.

**Comment by gmarek** [comment]
The comment for --insecure-access flag says:
```
The port on which to serve unsecured, unauthenticated access. Default 8080. It is assumed that firewall rules are set up such that this port is not reachable from outside of the cluster and that port 443 on the cluster's public address is proxied to this port. This is performed by nginx in the default setup.
```

Do we want to do something with this? @thockin

**Comment by liggitt** [comment]
You can disable with `--insecure-access=0`, but it breaks admission controllers (at least). At minimum, need to plumb client config for the admission controllers to use (similar to the way you tell the controller manager what client config to use for the controllers)

**Comment by thockin** [comment]
It would be great to turn this off, but it's outside my area of expertise :)

**Comment by roberthbailey** [comment]
@gmarek We should update the comment that talks about nginx, since we removed it quite a while ago.

**Comment by lavalamp** [comment]
UGH.

Stuff inside the apiserver shouldn't do this. Making a client pointing at yourself is a little nuts. Have to think about how to fix this.

**Comment by gmarek** [comment]
cc @fgrzadkowski

**Comment by liggitt** [comment]
Would really like to see this fixed for 1.3

**Comment by roberthbailey** [comment]
Me too. Are you guys going to have any bandwidth to work on it?

**Comment by liggitt** [comment]
> Stuff inside the apiserver shouldn't do this. Making a client pointing at yourself is a little nuts

I like how you can make sure all the same paths apply (authnz, admission, etc). I like the ability to give different components different permissions. 

@smarterclayton was experimenting with a go library that let you do "loopback" calls via a channel so that you wouldn't pay network stack overhead, but could treat the rest of the handler chain consistently

**Comment by smarterclayton** [comment]
The network stack overhead isn't that bad on modern kernels.  Even the
loopback channels (emulated net.Conn) weren't substantially faster,
although tail latency was much better.

**Comment by discordianfish** [comment]
I'm surprised that this doesn't get address with higher priority.

For the sake of a safer world, can you please at least require token or basic auth on http endpoints?

Currently this behavior by default opens what is effectively a root shell to anyone who can reach 127.0.0.1. That could be containers if the apiserver runs on systems with regular workloads but also local, unprivileged users or remote attackers exploiting a https://httpoxy.org/ like vulnerability. Or use DNS-rebinding to trigger api calls etc.

**Comment by k3a** [comment]
Yes this really needs to be addressed

**Comment by wied03** [comment]
This may be already addressed above, but I also see no way to make ``kube-controller-manager``` work with the API Server in SSL only mode unless the API Server's cert is signed by a trusted CA. I don't know enough about Go off the top of my head to know if you can customize that like Java without changing code.

**Comment by wied03** [comment]
Unless the kubeconfig approach discussed [here](https://coreos.com/kubernetes/docs/latest/deploy-workers.html#set-up-kubeconfig) can work with the controller-manager, and it looks like it does

**Comment by k3a** [comment]
No, it doesn't seem to be fixed in v1.3.5 release. The problem are admission controllers inside kube-apiserver. They seem to communicate with api-server over insecure connection only.

1 . I have apiserver run with: --insecure-port=0
2. Every kubernetes process use --kubeconfig and --master with secure ports specified
3. Yet when I run the apiserver, it logs out:

reflector.go:216] k8s.io/kubernetes/plugin/pkg/admission/serviceaccount/admission.go:119: Failed to list *api.Secret: Get http://127.0.0.1:0/api/v1/secrets?fieldSelector=type%3Dkubernetes.io%2Fservice-account-token&resourceVersion=0: dial tcp 127.0.0.1:0: getsockopt: connection refused

Always tries insecure bind + insecure port. While it is mostly fine to use insecure port on machines dedicated for kubernetes only, it makes admission controllers unusable at the moment in environments where other processes are running next to the kubernetes processes.

**Comment by 245347881** [comment]
yes ,my k8s version is v1.3.3,in my log of  apiserver: k8s.io/kubernetes/plugin/pkg/admission/serviceaccount/admission.go:119: Failed to list *api.Secret: Get http://10.10.10.150:0/api/v1/secrets?fieldSelector=type%3Dkubernetes.io%2Fservice-account-token&resourceVersion=0: dial tcp 10.10.10.150:0: getsockopt: connection refused

**Comment by dims** [comment]
Am not sure if the approach i came up with in https://github.com/kubernetes/kubernetes/pull/31491 is acceptable or not. PTAL

**Comment by discordianfish** [comment]
@dims Awesome! Thanks for this!
