### ISSUE TITLE
Installation on Mac/Vagrant/Parallels

### ISSUE THREAD

**Issue by aleks-f** [kubernetes/kubernetes#13608]
Following [instructions](http://kubernetes.io/v1.0/docs/getting-started-guides/vagrant.html), using:

Mac OSX 10.10.5
Vagrant 1.7.4
Parallels Desktop 10.2.2

When I run 

<pre>export VAGRANT_DEFAULT_PROVIDER=parallels
export KUBERNETES_PROVIDER=vagrant
./cluster/kube-up.sh</pre>

master and minion-1 windows pop up, apparently fully functional (I can ssh into them and everything seems to work) but the command line shows following problems for both master and minion:

<pre>==> master: Checking for Parallels Tools installed on the VM...
==> master: Parallels Tools installed on this VM are outdated! In most cases
==> master: this is fine but in rare cases it can cause things such as shared
==> master: folders to not work properly. If you see shared folder errors,
==> master: please update Parallels Tools within the virtual machine and 
==> master: reload your VM.
</pre>

<pre>master: Running: /var/folders/ng/8c3_08cd5nb8y8414tffrb980000gn/T/vagrant-shell20150904-29622-1bot2j5.sh
==> master: Job for network.service failed. See 'systemctl status network.service' and 'journalctl -xn' for details.
==> master: An error occurred. The error will be shown after all tasks complete.</pre>

I have applied @wshearn fedora repo fix recommended [here](https://github.com/kubernetes/kubernetes/issues/8019) but it didn't help.

Any help appreciated.

**Comment by jlowdermilk** [comment]
cc @derekwaynecarr

**Comment by jlowdermilk** [comment]
Please re-post your question to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes). 

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases. 

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to similar questions, and also familiarize yourself with:
  * [the user guide](http://kubernetes.io/v1.0/)
  * [the troubleshooting guide](http://kubernetes.io/v1.0/docs/troubleshooting.html)

Again, thanks for using Kubernetes.

The Kubernetes Team

**Comment by aleks-f** [comment]
Thanks, re-posted on [stackoverflow](http://stackoverflow.com/questions/32429156/kubernetes-installation-on-mac-vagrant-parallels).
