### ISSUE TITLE
OVS:  ARP Reply missing

### ISSUE THREAD

**Issue by wulonghui** [kubernetes/kubernetes#13620]
I create ovs networking refer to [vagrant/provision-network.sh](https://github.com/kubernetes/kubernetes/blob/master/cluster/vagrant/provision-network.sh)

![image](https://cloud.githubusercontent.com/assets/5194128/9702937/f2bb1606-54a4-11e5-9809-2c90321f983d.png)

Host1:
```
[host1] # ovs-vsctl show
597e273e-e2a0-47ec-a668-e35aba3be5c6
    Bridge ovsbr
        Port "tun0"
            Interface "tun0"
                type: internal
        Port "gre0"
            Interface "gre0"
                type: gre
                options: {remote_ip="192.168.3.148"}
        Port ovsbr
            Interface ovsbr
                type: internal
    ovs_version: "2.3.1"

[host1] # brctl show
bridge name	bridge id		STP enabled	interfaces
docker0		8000.56847afe9799	no		tun0
							                       vethd3c5466
```

Host2:
```
[host2] # ovs-vsctl show
27c69d64-9d8d-4321-8290-7e5a5e743173
    Bridge ovsbr
        Port "tun0"
            Interface "tun0"
                type: internal
        Port "gre0"
            Interface "gre0"
                type: gre
                options: {remote_ip="192.168.3.149"}
        Port ovsbr
            Interface ovsbr
                type: internal
    ovs_version: "2.3.1"

[host2]  #brctl show
bridge name	bridge id		STP enabled	interfaces
docker0		8000.56847afe9799	no		tun0
							                       veth80f65b0
```

When I ping Container1's IP(10.1.58.3) on Host2, the ARP Reply is dropped on Host1,
`docker0` can capture the ARP Reply:
```
[host1] #tcpdump -i docker0 -n
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on docker0, link-type EN10MB (Ethernet), capture size 65535 bytes
14:47:08.800350 ARP, Request who-has 10.1.58.3 tell 10.1.14.1, length 28
14:47:08.800474 ARP, Reply 10.1.58.3 is-at 02:42:0a:01:3a:03, length 28
```

but on found on `tun0`
```
[host1] # tcpdump -i tun0 -n
tcpdump: WARNING: tun0: no IPv4 address assigned
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on tun0, link-type EN10MB (Ethernet), capture size 65535 bytes
14:49:02.808105 ARP, Request who-has 10.1.58.3 tell 10.1.14.1, length 28
14:49:03.808482 ARP, Request who-has 10.1.58.3 tell 10.1.14.1, length 28
14:49:03.808482 ARP, Request who-has 10.1.58.3 tell 10.1.14.1, length 28
```

Seems the ARP Reply is dropped between `docker0` and `tun0`
What can I do?

**Comment by jlowdermilk** [comment]
Please re-post your question to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes). 

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases. 

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to similar questions, and also familiarize yourself with:
  * [the user guide](http://kubernetes.io/v1.0/)
  * [the troubleshooting guide](http://kubernetes.io/v1.0/docs/troubleshooting.html)

Again, thanks for using Kubernetes.

The Kubernetes Team
