### ISSUE TITLE
kubernetes on mesos - apiserver received an error that is not an api.Status: tls: handshake did not verify certificate chain

### ISSUE THREAD

**Issue by siddharth20729** [kubernetes/kubernetes#13637]
I am running into this error when i run the kubectl exec command 

kubectl  exec busybox -- nslookup kubernetes
Error from server: tls: handshake did not verify certificate chain

can anyone guide me on the issue ?

kuberenetes release 1.0.5
go 1.5

**Comment by tsl0922** [comment]
Having the same problem with the HEAD version(6605b170b63d14f74d382acd65adf94a53e09ab4), this is the log from `/tmp/kube-apiserver.log` (cluster started with `hack/local-up-cluster.sh`):

```
E0907 21:50:11.477685    7973 errors.go:62] apiserver received an error that is not an api.Status: tls: handshake did not verify certificate chain
I0907 21:50:11.477840    7973 handlers.go:142] POST /api/v1/namespaces/default/pods/busybox/exec?command=nslookup&command=kubernetes&container=busybox&stderr=true&stdout=true: (16.814007ms) 500
goroutine 11999 [running]:
k8s.io/kubernetes/pkg/httplog.(*respLogger).WriteHeader(0xc821f18540, 0x1f4)
	/home/ubuntu/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/httplog/log.go:188 +0x9a
k8s.io/kubernetes/pkg/apiserver.writeJSON(0x1f4, 0x7f3f9b356240, 0xc820103d20, 0x7f3f9b3564b0, 0xc821d5bc80, 0x7f3f9b31cc60, 0xc821f18540, 0x1)
	/home/ubuntu/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/apiserver/apiserver.go:300 +0x292
k8s.io/kubernetes/pkg/apiserver.errorJSON(0x7f3f9b351028, 0xc821da0700, 0x7f3f9b356240, 0xc820103d20, 0x7f3f9b31cc60, 0xc821f18540, 0xc821e6caf0)
	/home/ubuntu/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/apiserver/apiserver.go:307 +0xa8
k8s.io/kubernetes/pkg/apiserver.ConnectResource.func1(0xc821e18810, 0xc821f18600)
	/home/ubuntu/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/apiserver/resthandler.go:184 +0x940
github.com/emicklei/go-restful.(*Container).dispatch.func6(0xc821e18810, 0xc821f18600)
	/home/ubuntu/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-restful/container.go:244 +0x34
github.com/emicklei/go-restful.(*FilterChain).ProcessFilter(0xc821e188a0, 0xc821e18810, 0xc821f18600)
	/home/ubuntu/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-restful/filter.go:21 +0x9f
k8s.io/kubernetes/pkg/apiserver.monitorFilter.func1(0xc821e18810, 0xc821f18600, 0xc821e188a0)
	/home/ubuntu/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/apiserver/apiserver.go:60 +0x88
github.com/emicklei/go-restful.(*FilterChain).ProcessFilter(0xc821e188a0, 0xc821e18810, 0xc821f18600)
	/home/ubuntu/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-restful/filter.go:19 +0x81
github.com/emicklei/go-restful.(*Container).dispatch(0xc820334cf0, 0x7f3f9b31cc60, 0xc821f18540, 0xc820a55500)
	/home/ubuntu/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-restful/container.go:246 +0xe67
github.com/emicklei/go-restful.(*Container).(github.com/emicklei/go-restful.dispatch)-fm(0x7f3f9b31cc60, 0xc821f18540, 0xc820a55500)
	/home/ubuntu/kubernetes/Godeps/_workspace/src [[kubectl/v1.1.0 (linux/amd64) kubernetes/6605b17] 127.0.0.1:59441]
```

**Comment by jlowdermilk** [comment]
Please re-post your question to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes). 

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases. 

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to similar questions, and also familiarize yourself with:
  * [the user guide](http://kubernetes.io/v1.0/)
  * [the troubleshooting guide](http://kubernetes.io/v1.0/docs/troubleshooting.html)

Again, thanks for using Kubernetes.

The Kubernetes Team
