### ISSUE TITLE
Quantity doesn't recognize format correctly.

### ISSUE THREAD

**Issue by hurf** [kubernetes/kubernetes#13631]
I set memory limit to 1.1Gi for a container, then used `describe` to view the details, it returned `memory: 1181116006400m`. But for 100Mi, 1Gi and **1.5Gi**, it will be 100Mi, 1Gi and **1536Mi**.
1. for 1.1Gi and 1.6Mi, it will be recognized as DecimalSI. 
2. for 1.5Gi, it will be recognized as BinarySI, but displayed with another suffix.

Should we fix this?

**Comment by thockin** [comment]
@lavalamp

**Comment by lavalamp** [comment]
Hm, we should definitely round to whole byte values, we obviously can't give you that extra .4 bytes you asked for. Binary suffixes only divide evenly by powers of two (so e.g. 1.125Gi and 1.0625 should both work). I suspect we just aren't doing enough validation; we should have rejected that or rounded it. 

> for 1.1Gi and 1.6Mi, it will be recognized as DecimalSI.

This is as expected, since .1 and .6 are not of the form 1/2^n and therefore leave a fractional part. We debated about not reinterpreting the value--displaying exactly what the user entered--but this has the disadvantage that the user can't see what the system is actually going to do with the number.

> for 1.5Gi, it will be recognized as BinarySI, but displayed with another suffix.

This is as expected/desired, it won't display fractional parts.

**Comment by hurf** [comment]
@lavalamp - Thanks for explaination. I'm now much more clear about the interpretion. 
About the display, I have a suggestion, can we just add a method to display the original input? Since we're using "human-readable" format to print information in kubectl, user's may not mind an accuracy loss of .4 bytes but prefer an output easy to read. In this case we can use the new method. For other cases may need more accuracy, we can still use the exsiting method. Does that sounds reasonable to you?

**Comment by lavalamp** [comment]
> About the display, I have a suggestion, can we just add a method to display the original input? 

Unfortunately the drawback of that is that we'd have to add an additional field to track the original entry. If it were just the addition of some code, that'd be one thing, but adding another field and plumbing it through everywhere begins to not seem worth it, at least to me.

But I think there is an **action item: fix validation, so that quantities of memory never end up with a fractional part.**

**Comment by thockin** [comment]
Are you saying that should be rejected or adapted?  We've held the line so
far that Quantity is never lossless, but in this case, a fraction of a byte
seems reasonable, especially given that memory is actually accounted in 4Ki
or larger chunks...

**Comment by lavalamp** [comment]
@thockin Did you mean "never lossy"?

I agree that it makes sense to round (or truncate?) memory so that it is an integer number of allocatable chunks, not just to the nearest byte. I suppose that number could in theory depend on the node, though, in which case we should perhaps not round and just report the number the node decides was meant?

**Comment by thockin** [comment]
I did mean "never lossy" or "always lossless" :)

I did not mean that we should round values in the request, just that the
resources granted might be different from the request.  If I request 100
bytes, the API should say 100 bytes for my limit, but it might also report
4096 bytes as the effective limit (do we report effective limits?  we might
want to).

Likewise if I ask for 0.01Mi (10485.76 bytes) the limit should say 10486
bytes, while effectve limit is 12288 (3 pages).

**Comment by lavalamp** [comment]
Yeah, I agree with all that. I don't think we report effective limit?
That'd have to show up in the status.

**Comment by lavalamp** [comment]
So I guess the action item would be to make kubelet report interpreted values in the status?

**Comment by thockin** [comment]
Two thoughts.  Can we craft an input quanitity string that can not be
losslessly represented in a Qunatity?  I am sure the answer is yes.  Does
that cause a problem in that what you read back is oh-so-slightly different
from what you wrote in?

If yes, we need to think.

If no, why not quantize know resources to their smallest units and store in
requests/limits ?

**Comment by smarterclayton** [comment]
Closing due to age, reopen if this is re-creatable.
