### ISSUE TITLE
kube-ui can't show anything

### ISSUE THREAD

**Issue by linzichang** [kubernetes/kubernetes#13641]
I use [libvirt-coreos] (https://github.com/kubernetes/kubernetes/blob/master/docs/getting-started-guides/libvirt-coreos.md) to start a k8s cluster. And the cluster work well.
Then
`kubectl create -f kube-ui-rc.yaml --namespace=kube-system`
`kubectl create -f kube-ui-svc.yaml --namespace=kube-system`
The service's `nodePort` is 30000

I have already run a pod.
```sh
core@kubernetes-master ~ $ /opt/kubernetes/bin/kubectl get pods
NAME                 READY     STATUS    RESTARTS   AGE
redis-master-wvkjo   1/1       Running   0          1h
```

It's ok to visit http://anyone of nodeip:30000. But It show nearly nothing. Is there anybody may help me to deal with it. 
![1](https://cloud.githubusercontent.com/assets/11015666/9715054/4edd6336-558f-11e5-907d-c3df6b28af25.PNG)
![2](https://cloud.githubusercontent.com/assets/11015666/9715058/5654e4a4-558f-11e5-8b0b-903ab921cca8.PNG)

**Comment by jlowdermilk** [comment]
Please re-post your question to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes). 

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases. 

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to similar questions, and also familiarize yourself with:
  * [the user guide](http://kubernetes.io/v1.0/)
  * [the troubleshooting guide](http://kubernetes.io/v1.0/docs/troubleshooting.html)

Again, thanks for using Kubernetes.

The Kubernetes Team
