### ISSUE TITLE
[Kubernetes on Mesos] : Failed to start service controller

### ISSUE THREAD

**Issue by ltagliamonte** [kubernetes/kubernetes#13654]
I'm trying to install Kubernetes on Mesos i followed this guide:
https://github.com/kubernetes/kubernetes/blob/release-1.0/docs/getting-started-guides/mesos.md
Mesos cluster logs are clean the only error the i can see in the logs is coming from the controller logs:
```
I0908 07:08:42.240715    1981 mesos.go:67] new mesos cloud, master='10.10.0.59:5050'
I0908 07:08:42.240788    1981 standalone.go:69] spinning up asyc master detector poller
I0908 07:08:42.240813    1981 standalone.go:78] spawning asyc master detector listener
I0908 07:08:42.240852    1981 nodecontroller.go:115] Sending events to api server.
E0908 07:08:42.241494    1981 controllermanager.go:132] Failed to start service controller: the cloud provider does not support external TCP load balancers.
I0908 07:08:42.241630    1981 plugins.go:217] Loaded volume plugin "kubernetes.io/host-path"
I0908 07:08:42.241652    1981 plugins.go:217] Loaded volume plugin "kubernetes.io/nfs"
I0908 07:08:42.242583    1981 standalone.go:140] polling for master leadership at '10.10.0.59:5050'
I0908 07:08:42.246898    1981 standalone.go:88] detected master change: &MasterInfo{Id:*master,Ip:*0,Port:*5050,Pid:*master@10.10.0.59:5050,Hostname:*10.10.0.59,XXX_unrecognized:[],}
I0908 07:08:42.246955    1981 client.go:147] cloud master changed to '10.10.0.59:5050' 
```
My configuration is: Mesos Master with Kubernetes + 1 slave node.
the output of cluster info  and get nodes is:
```
root@ip-10-10-0-59:~# ./kubectl --server=http://localhost:8888 cluster-info
Kubernetes master is running at http://localhost:8888
root@ip-10-10-0-59:~# ./kubectl --server=http://localhost:8888 get nodes
NAME      LABELS    STATUS
```
Thanks in advance for the help

**Comment by caesarxuchao** [comment]
Please re-post your question to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes). 

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases. 

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to similar questions, and also familiarize yourself with:
  * [the user guide](http://kubernetes.io/v1.0/)
  * [the troubleshooting guide](http://kubernetes.io/v1.0/docs/troubleshooting.html)

Again, thanks for using Kubernetes.

The Kubernetes Team
