### ISSUE TITLE
Start containers in privileged mode

### ISSUE THREAD

**Issue by udaraliyanage** [kubernetes/kubernetes#13653]
I am running a Kuberneties cluster with one master and one minion. I use coreos images in EC2 for both master and minions. Pods getting created and become running fine. I am using Kuberneties API in order to create/delete pods.

However I need to start the containers in privileged mode in order to solve the Transparent huge pages issue in NuoDB. I added --allow-priviledge=true in minions kubelet service file (/etc/systemd/system/kubelet.service). But the issue is still there.
There after I added the same property to Kuberneties master api server as suggested in the mail thread I opened https://groups.google.com/forum/#!topic/google-containers/w2zHfnV1pj8. In order to add the property to master I edited the configuration file  /etc/systemd/system/kube-apiserver.service.

**Comment by resouer** [comment]
Just as Brendan said in the post, have u restarted api-server and kubelet after you changed the config file?

**Comment by udaraliyanage** [comment]
Yes I restarted api service in master node and kublet service on minion. I have pasted commanda and content of the files in that thread.

**Comment by caesarxuchao** [comment]
Please re-post your question to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes). 

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases. 

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to similar questions, and also familiarize yourself with:
  * [the user guide](http://kubernetes.io/v1.0/)
  * [the troubleshooting guide](http://kubernetes.io/v1.0/docs/troubleshooting.html)

Again, thanks for using Kubernetes.

The Kubernetes Team
