### ISSUE TITLE
Kubernetes seems to fail when i try to run kube-up 

### ISSUE THREAD

**Issue by hansjmelby** [kubernetes/kubernetes#13657]
I try to run the command kube-up.sh in cygwin and I get the following response 
$ ./kube-up.sh
Starting cluster using provider: vagrant
... calling verify-prereqs
./../cluster/vagrant/util.sh: line 85: VAGRANT_DEFAULT_PROVIDER: unbound variable

I have tried to export the folliwing settings 
To remedy this, I have tried to to the following :
export VAGRANT_DEFAULT_PROVIDER=virtualbox

I still get an error,, but this time i get the following error :
Starting cluster using provider: vagrant
... calling verify-prereqs
Can't find the necessary components for the virtualbox vagrant provider, please fix and retry.

All required vagrant and virtualbox installations is done prior to this errors

Can you please guide me to solve this issue

**Comment by arun-gupta** [comment]
Windows experience of starting a Kubernetes cluster is not very optimal and needs to be cleaned up. The instructions to start the Kubernetes cluster by @hansjmelby are at:

https://htmlpreview.github.io/?https://github.com/javaee-samples/docker-java/blob/master/readme.html#_start_kubernetes_cluster

**Comment by caesarxuchao** [comment]
Please re-post your question to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes). 

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases. 

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to similar questions, and also familiarize yourself with:
  * [the user guide](http://kubernetes.io/v1.0/)
  * [the troubleshooting guide](http://kubernetes.io/v1.0/docs/troubleshooting.html)

Again, thanks for using Kubernetes.

The Kubernetes Team
