### ISSUE TITLE
Some 'command' and 'lifecycle.postStart.exec.command' values cause node to go offline

### ISSUE THREAD

**Issue by finn0013** [kubernetes/kubernetes#13685]
While working through how kubernetes works I'm struggling to get my commands to execute on the container using either the 'command' or 'lifecycle.postStart.exec.command' attributes. In trying to get this to work I've found that some commands cause the pod to not start correctly, as expected. However, some of these also cause the node to go offline and move to a 'NotReady' state within a minute or so of the pod not starting.

I've checked in an example rc that reproduces this. This will give ExitCode:143 for the pod start then after a minute or so will change the status of the node to 'NotReady'. In the attempt just now the pod attempted 11 restarts over 3 minutes before the node went down.  All other necessary files to reproduce are also in this repo. 

Files to reproduce - use 261390b of test/kubernetes/kubernetes/kube-capabilities-demo-rc.yaml:
https://github.com/finn0013/test

I'm running the following:
```
M-C02MG1T8FD59:~ jmcdonald$ kubectl version
Client Version: version.Info{Major:"1", Minor:"0", GitVersion:"v1.0.3", GitCommit:"61c6ac5f350253a4dc002aee97b7db7ff01ee4ca", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"0", GitVersion:"v1.0.3", GitCommit:"61c6ac5f350253a4dc002aee97b7db7ff01ee4ca", GitTreeState:"clean"}

M-C02MG1T8FD59:cluster jmcdonald$ vagrant version
Installed Version: 1.7.4
Latest Version: 1.7.4
```

I'm currently running 1 master and 1 minion.

---------

As a tangental question, if anyone can direct me to something that can help me figure out why my commands aren't executing I'd be extremely grateful. I've scoured the documentation and web searches but seem to be stumped. I cannot seem to get them to show up in logs and they are not executing so I'm kind of blind right now as to why my experiments aren't working as expected.

**Comment by gmarek** [comment]
Please re-post your question to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes). 

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases. 

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to similar questions, and also familiarize yourself with:
  * [the user guide](http://kubernetes.io/v1.0/)
  * [the troubleshooting guide](http://kubernetes.io/v1.0/docs/troubleshooting.html)

Again, thanks for using Kubernetes.

The Kubernetes Team

**Comment by finn0013** [comment]
Is this expected behavior? I'm filing an issue to track that the node goes down when I don't feel it should. 

I asked a tangental question that I'd be happy to move to StackOverflow.

**Comment by finn0013** [comment]
Moving my question to SO and removed from this ticket. 

What remains is an issue with the Node going down with invalid command arguments.
