### ISSUE TITLE
Concatenated CAcert in kubelet --tls-cert-file is not used for server validation

### ISSUE THREAD

**Issue by aaronlevy** [kubernetes/kubernetes#13696]
Per the --tls-cer-file flag description ( https://github.com/kubernetes/kubernetes/blob/v1.0.5/cmd/kubelet/app/server.go#L201 ) I assumed (maybe incorrectly) that the CA cert appended to the client cert would be used for server validation. However, it seems to be ignored.

Verified certs by using same concatenated file with curl --cacert and --cert flags.

Not sure if this is expected behavior, and the description is somewhat unclear, or that the CA cert should be used for server validation.

**Comment by roberthbailey** [comment]
Strange. We definitely check the CA cert from kubectl.

**Comment by liggitt** [comment]
`--tls-cert-file` provides the kubelet's serving cert, not a client cert... the concatenated cert chain after the initial server cert is served as well, and is only there so that clients talking to the kubelet can follow the chain to a CA as part of their verification of the server.

Were you expecting the kubelet to use the appended CA to verify client certs connecting to the kubelet?

**Comment by aaronlevy** [comment]
I was looking for a way to specify the CA that the kubelet would use to validate the apiserver cert. The answer to that was ultimately specifying a CA in a kubeconfig. When going through kubelet cli flags, the only mention of a CA was the --tls-cert-file, so I made the (incorrect) assumption that it was being used for validating outbound connections.

But your explanation makes sense as to its actual use, so gonna close this as it  was just my misunderstanding. Thanks!
