### ISSUE TITLE
update the description about label-selecors in the labels.md

### ISSUE THREAD

**Issue by caesarxuchao** [kubernetes/kubernetes#13699]
The [documentation](https://github.com/kubernetes/kubernetes/blob/master/docs/user-guide/labels.md#label-selectors) suggests we support both "equality-based" and "set-based" label selectors, but actually we only support "==" selector right now. This is confusing. People are asking questions on IRC. We should update the doc in both github and k8s.io/v1.0.

**Comment by gmarek** [comment]
@bgrant0607

**Comment by bgrant0607** [comment]
cc @sdminonne

**Comment by bgrant0607** [comment]
We support the set-based selectors for filtering GET/watch requests.

We support equality-based selectors, represented as maps, for API resources, such as ReplicationController, Service, and Pod nodeSelector.

**Comment by gmarek** [comment]
Even if it's technically correct people are getting confused, so we need to fix the documentation.

**Comment by bgrant0607** [comment]
Ref #341

**Comment by sdminonne** [comment]
@bgrant0607 sorry I see this only now.

@gmarek I'm ok to better explain the difference between set-based and equality based but I would need of some example of questions on IRC. May you have some of them?

Otherwise we may clearly write that kubectl <command> -l <selector> supports set-based and equality based selector while API resources supports only equality-based.

**Comment by gmarek** [comment]
I was thinking of making the difference between selectors in kubectl and in API clear.

**Comment by sdminonne** [comment]
@gmarek cool, I can work on this if you've not already started.

**Comment by gmarek** [comment]
By all means - please do:)

**Comment by sdminonne** [comment]
:)
