### ISSUE TITLE
local-cluster-up.sh should need to be executed from $KUBE_ROOT

### ISSUE THREAD

**Issue by zhengguoyong** [kubernetes/kubernetes#13735]
when i execute the script local-up-cluster.sh . it shows :  ./../hack/lib/init.sh no such file.
then i saw the script, i found when execute "source "${KUBE_ROOT}/hack/lib/init.sh"", the pwd is kubernetes, but the var KUBE_ROOT is "./..", so it cann't find the init.sh script,

please check it, and i will repair and merge as soon.

**Comment by caesarxuchao** [comment]
Please re-post your question to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes). 

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases. 

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to similar questions, and also familiarize yourself with:
  * [the user guide](http://kubernetes.io/v1.0/)
  * [the troubleshooting guide](http://kubernetes.io/v1.0/docs/troubleshooting.html)

Again, thanks for using Kubernetes.

The Kubernetes Team

**Comment by caesarxuchao** [comment]
From which directory did you run the local-cluster-up.sh script? I think you need to run it from $KUBE_ROOT.

**Comment by eulerzgy** [comment]
the script is in the $KUBE_ROOT/hack directory,  but we should run it on the $KUBE_ROOT directory, i don't think it is good for common users.
@caesarxuchao

Best regards!

**Comment by caesarxuchao** [comment]
@eulerzgy. I found it a little counter-intuitive when I first started on k8s as well. Then I found all k8s scripts need to be run from $KUBE_ROOT, so I think it's consistent.

**Comment by eulerzgy** [comment]
@caesarxuchao
i don't think all k8s scripts need to be run from $KUBE_ROOT, just for example:/kube-up.sh , it run in the $KUBE_ROOT\cluster  directory.

Best regards!
