### ISSUE TITLE
Vagrant setup - error: couldn't read version from server; connection reset by peer

### ISSUE THREAD

**Issue by JanetKuo** [kubernetes/kubernetes#13761]
@arun-gupta mentioned in https://github.com/kubernetes/kubernetes/issues/11262#issuecomment-137527756 that he got the following error from running `cluster/kube-up.sh` on `v1.0.5`. 
```
Wrote config for vagrant to /Users/arungupta/.kube/config
Each machine instance has been created/updated.
  Now waiting for the Salt provisioning process to complete on each machine.
  This can take some time based on your network, disk, and cpu speed.
  It is possible for an error to occur during Salt provision of cluster and this could loop forever.
Validating master
Validating minion-1
............................................
Waiting for each minion to be registered with cloud provider
error: couldn't read version from server: Get https://10.245.1.2/api: read tcp 10.245.1.2:443: connection reset by peer
```

**Comment by caesarxuchao** [comment]
Could you paste other logs like kube-apiserver?

**Comment by alexanderguzhva** [comment]
I see this message all the time in 1.1.0-alpha, but everything works as a charm

**Comment by arun-gupta** [comment]
@caesarxuchao where do I get the logs from kube-apiserver?

**Comment by apeeyush** [comment]
I am trying to setup the development environment (master branch) and having difficulties in setting up Vagrant!

The error is:

    Wrote config for vagrant to /home/peeyush/.kube/config
    Each machine instance has been created/updated.
      Now waiting for the Salt provisioning process to complete on each machine.
      This can take some time based on your network, disk, and cpu speed.
      It is possible for an error to occur during Salt provision of cluster and this could loop forever.
    Validating master
    Connection to 127.0.0.1 closed.
    Validating minion-1
    ......................................
    Waiting for each minion to be registered with cloud provider
    error: couldn't read version from server: Get https://10.245.1.2/api: dial tcp 10.245.1.2:443: connection refused

Commenting here instead of creating a new issue since they seem somewhat related. Does anyone know what might be going wrong?

Also, do developers use vagrant or something else for development?

**Comment by JanetKuo** [comment]
@arun-gupta the kube-apiserver log is in `/var/log/kube-apiserver.log` of your master, see:
https://github.com/kubernetes/kubernetes/blob/master/docs/admin/cluster-troubleshooting.md#master

**Comment by arun-gupta** [comment]
@JanetKuo I shutdown the server, deleted the directory, unzipped the archive again, started the server again, and now it seems to work fine.

This is very unpredictable.

**Comment by apeeyush** [comment]
@arun-gupta, could you please tell the version of Vagrant, Docker, Virtualbox and Kubernetes you are using. I am also facing issues in setting up the Vagrant dev environment and suspect that it might have to do with the versions I am using.

**Comment by arun-gupta** [comment]
@apeeyush Vagrant 1.7.2, Docker version 1.8.1, build d12ea79, Virtual Box 4.3.30, Kubernetes 1.0.5

**Comment by caesarxuchao** [comment]
Sorry, @arun-gupta, I missed your reply in my inbox. Thank you @JanetKuo for helping out. The log file JanetKuo pointed to is correct. @apeeyush could you take a look at this log file if you still have it? Thanks.

**Comment by apeeyush** [comment]
@caesarxuchao The log file `/var/log/kube-controller-manager.log` (on master) is empty. I get the following error:

    error: couldn't read version from server: Get https://10.245.1.2/api: dial tcp 10.245.1.2:443: connection refused

I am using kubernetes from master branch, Vagrant 1.7.4, Virtualbox 5.0.4r102546 and Docker version 1.8.1, build d12ea79 on my Ubuntu 14.04 machine.

**Comment by caesarxuchao** [comment]
@apeeyush, it seems the  server does not start up if the log is empty. I'm confused how it pass the "Validating master" step.

cc the authors of the util.sh to see if they can shed some light. @jbeda @derekwaynecarr. Thank you.

**Comment by derekwaynecarr** [comment]
This can happen if your host machine is not connected to the ethernet device created by Virtual Box.

See the comment here:
https://github.com/kubernetes/kubernetes/issues/12285#issuecomment-139348843

**Comment by apeeyush** [comment]
Thanks @derekwaynecarr for the reply. I will try it again this Sunday and report my findings here (trying a different Virtualbox and Vagrant version, going through past issues on github etc.).

I will greatly appreciate any feedback which might help me identify where the issue is and what tweaks I should do to make it work.

**Comment by apeeyush** [comment]
I downgraded virtualbox to 4.3.28r100309 and everything is working fine now! I guess Virtualbox 5.0.4 has some breaking changes. Should the issue be closed?

**Comment by dnascimento** [comment]
I was having some issues with Virtual Box: 5.0.4, Vagrant 1.7.4; Docker: 1.8.1.fc21
1. Docker is not starting on master.
2. **Ethtool** is required.

After installing Ethtool and restart docker and then Kube, it is working. Can someone confirm the need for **ethtool**?

**Comment by tPl0ch** [comment]
@dnascimento I can confirm the issue with 5.0.4, but upgrading to 5.0.5 fixes the issue, too :)

**Comment by bronger** [comment]
Installing ethtool did not help me.  Upgrading to VirtualBox 5.0.10 did help.  Well, at least I got one step further.

**Comment by bronger** [comment]
[I removed my previous message from Github as it turned out to be incorrect.]

I installed ethtool, but it didn't change anything for me.  An update of VirtualBox to 5.0.10 at least sometimes brings me one step further: Instead of "connection reset by peer" as decribed in the first post of this issue, I get "couldn't read version from server: Get https://10.245.1.2/api: dial tcp 10.245.1.2:443: connection refused".

And the third possibility is that the provision of the minion loops forever.

It is random to me which event happens.  It never works with the slow internet connection in our library.  ;-)  So, I suspect a race condition, and some people solved this for them by changing the race by installing this or updating that.

I use VirtualBox 5.0.10 on an Ubuntu 14.04 with Kubernetes v1.1.1.

**Comment by apeeyush** [comment]
@bronger  `couldn't read version from server: Get https://10.245.1.2/api: dial tcp 10.245.1.2:443: connection refused` might be caused because of insufficient memory in the master node. You could try increasing the memory allocated to the master node (and maybe minion as well) in the Vagrantfile.

**Comment by bronger** [comment]
Unfortunately, increasing memory to 2 or 3GB does not help.  (WIth 3GB, the minion provisioning abort with "Failed to run install_fedora_deps()!!!" --- never had this before.)
