### ISSUE TITLE
Implement static object count limits

### ISSUE THREAD

**Issue by roberthbailey** [kubernetes/kubernetes#13774]
/cc @erictune 

Having a limit on the total number of pods seems useful. This number should be quite a bit higher than `max-recommended-nodes * max-recommended-pods-per-node`, but low enough that we hit it before we completely run out of memory/disk on master. 

We would like to have a static limit that applies across all namespaces and isn't reconfigurable by someone with cluster API access. The easiest way to implement that seems like a flag to the apiserver (that way you can reconfigure it, but you need access to the apiserver binary rather than access to the api itself).

**Comment by bgrant0607** [comment]
cc @davidopp @mikedanese @derekwaynecarr

**Comment by davidopp** [comment]
This issue is related to pod GC, see #7660. This is not the same as a normal quota problem because in principle you can put "pressure" on the controllers that created pods to clean up dead ones, to free up space to create new ones. See for example this comment
https://github.com/kubernetes/kubernetes/pull/14325#issuecomment-142498925

Same is true for any object type we want to limit the number of, that is not deleted immediately but can stay around in a "dead" state for a while.

**Comment by derekwaynecarr** [comment]
I would like cluster level settings like this that controls object counts for all resource types, but I do not want it to necessarily attempt to enforce a hard quota.  As an operator, I want to be able to query a resource to get stats on object counts for each resource, so some type of cluster object counter that runs at some interval and records to etcd seems ideal.  In addition, as an operator I don't want to use it as a hard limit necessarily and instead would prefer to use it more for more knowing when I should scale or spin up a new cluster by having a soft limit.  A controller would just periodically run the count queries and dump the result in a cluster scoped resource.  Trying to enforce it as a cluster wide constraint enforces a need to do a global lock on all admissions into the cluster which is a bad idea.  Will comment more when not on mobile phone.

**Comment by bgrant0607** [comment]
I'd like to be able to use ResourceQuota for this, in addition to a global limit.

**Comment by davidopp** [comment]
@roberthbailey You marked this P1, but can we downgrade it to P2?

**Comment by roberthbailey** [comment]
It was P1 because it came from a postmortem but I'm ok with it being a P2.

**Comment by bprashanth** [comment]
Why enforce a static count insted of pushing stats every 10s to an independent DOS controller? Eg: we'd tell it that creates on /pods have spiked since last 10s, or have been spiking for 10m, and it would tell us  to start returning 500 on /pods. It could also return blacklisted ips, or limit based on per user qps.

Such a controller would be generally useful, even for DOS protection of Ingress. To start with, it could return a static limit that is configured by a flag to controller-manager.

**Comment by roberthbailey** [comment]
@bprashanth that would be a more elegant solution to the problem. The original proposal was a stop-gap because we wanted to prevent the master components from going into an OOM crash loop and seemed easy to implement. Is DoS protection something we would consider building in the 1.3 timeframe?

**Comment by bprashanth** [comment]
@roberthbailey there's a lot of scope for DOS prevention at scale and I think we'll inevitably need a dedicated DOS controller, so starting off with one makes sense to me. I think we should get the ball rolling on basic DOS prevention (https://github.com/kubernetes/kubernetes/issues/22679) in 1.3. 

It should at least protect us from: while true; do kubectl create -f pod.yaml; done, or more likely, a hot looping controller. It would be nice if it also protected against very large objects with bloated annotations.

If the apiserver starts to OOM we lose ssh, and this is hard to fix in non-hosted scenarios where one can't simply bump up the master size. The problem is made worse by the watch cache because the apiserver will try to load all objects into memory on first list (all the controllers will list pods on startup, and we don't have paginated lists yet).

**Comment by lavalamp** [comment]
Related idea: https://github.com/kubernetes/kubernetes/issues/33041
