### ISSUE TITLE
Default --validate=true fetches 500kb swagger spec on every create/replace invocation

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#13806]
https://github.com/kubernetes/kubernetes/pull/12837 changed the default of --validate to true.

This means that every create/replace invocation fetches the full API swagger spec, which is about half a megabyte of JSON. That's a pretty impactful change. I think we should undo defaulting to true until we have a better way to get/cache the spec used to validate.

**Comment by liggitt** [comment]
cc @bgrant0607 @jlowdermilk @deads2k for involvement in the original PR

**Comment by mikedanese** [comment]
@kubernetes/kubectl

**Comment by bgrant0607** [comment]
cc @nikhiljindal @brendandburns @JanetKuo 

Our top usability complaint is lack of adequate, actionable feedback about buggy resource specifications. Addressing that is P0, which is why we enabled validation by default. If someone doesn't want validation, they can turn it off.

We should cache the swagger, but we could also switch to a non-swagger-based validation mechanism. For example, how hard would it be to fork Go's decoder (http://golang.org/src/encoding/json/decode.go) to (optionally) not ignore unknown fields? It looks like it might be as easy as adding an `else` to one `if` statement.

**Comment by brendandburns** [comment]
I'll take this on.  Should be easy to add a "cache-forever" header and an caching HTTP client to kubectl.

wrt to forking the decoder, we're going to switch to code-gen'd JSON soon-ish, I'd rather add the explicit validation there...

--brendan

**Comment by liggitt** [comment]
Looks like it also broke List submission (since List doesn't validate), c.f. https://github.com/kubernetes/kubernetes/issues/13812

**Comment by liggitt** [comment]
careful with api spec caching assumptions if dynamic API group addition/removal is on the horizon
