### ISSUE TITLE
AWS load balancer not visible in "kubectl.sh get svc"

### ISSUE THREAD

**Issue by aronchick** [kubernetes/kubernetes#13827]
GCP uses IP addresses, which is shown on an extra line. AWS does not give an IP address. We should show it.

GCP:
```
$ cluster/kubectl.sh get svc
NAME                LABELS                                    SELECTOR         IP(S)             PORT(S)
client-service      name=client-service                       name=client      10.0.25.158       80/TCP
                                                                               104.187.114.208
dashboard-service   name=dashboard-service                    name=dashboard   10.0.233.55       80/TCP
                                                                               104.187.83.48
kubernetes          component=apiserver,provider=kubernetes   <none>           10.0.0.1          443/TC
```

AWS:
```
$ cluster/kubectl.sh get svc
NAME                LABELS                                    SELECTOR         IP(S)          PORT(S)
client-service      name=client-service                       name=client      10.0.1.134     80/TCP
dashboard-service   name=dashboard-service                    name=dashboard   10.0.139.186   80/TCP
kubernetes          component=apiserver,provider=kubernetes   <none>           10.0.0.1       443/TCP
```

I'd like to try to do this work.

**Comment by jlowdermilk** [comment]
cc @justinsb

**Comment by justinsb** [comment]
AWS uses hostnames for load balancers which is why they aren't showing up.  The hostname is also pretty long, and I know we've had problems with the width of the kubectl output before.

That said, I seem to recall a "--wide" option, and I think you can maybe choose which columns appear?

I think it is a useful suggestion, and I think your biggest battle will be to keep the number of columns such that it doesn't normally wrap.

Just so you know, I normally do `kubectl describe service X` to see the AWS ELB hostname.

**Comment by bprashanth** [comment]
Duping this into https://github.com/kubernetes/kubernetes/issues/18019, we also have an lgtm'd pr out
