### ISSUE TITLE
RFC: Handling logs in the future

### ISSUE THREAD

**Issue by vishh** [kubernetes/kubernetes#13846]
Having to handle logs at the node level complicates disk management considerably. 
- Currently logs are stored in the context of containers. The lifetime of logs is tied to the lifetime of container instances. 
- Disk usage accounting for logs is tricky since log files are handled by docker daemon, which provides no disk accounting.
- Containers store log files onto root filesystem at times, leading to uncontrolled disk usage.
- The existing implementation of logs APIs requires keeping old container instances around, which hinders efficient disk utilization.
- System level logs (kubelet, docker daemon, kube-proxy) have to be rotated quickly to avoid taking up too much disk space.

Since we have a cluster level logging infrastructure, we can redirect the `logs` endpoints to the logging infrastructure. This might require building a new component that can proxy logs requests to various logging backends like elasticsearch, Google Cloud Logging, etc. 

Another alternative is to not support `logs` in our APIs and require users to use their cluster logging infra to access all their logs.

@smarterclayton @bgrant0607 @dchen1107 @a-robinson

**Comment by smarterclayton** [comment]
On Sep 10, 2015, at 8:39 PM, Vish Kannan <notifications@github.com> wrote:

Having to handle logs at the node level complicates disk management
considerably.

   - Currently logs are stored in the context of containers. The lifetime
   of logs is tied to the lifetime of container instances.
   - Disk usage accounting for logs is tricky since log files are handled
   by docker daemon, which provides no disk accounting.
   - Containers store log files onto root filesystem at times, leading to
   uncontrolled disk usage.
   - The existing implementation of logs APIs requires keeping old
   container instances around, which hinders efficient disk utilization.


This should be fixed by allowing log Apis to go to the backing log store if
necessary, and being able to determine that from the apiserver.



   - System level logs (kubelet, docker daemon, kube-proxy) have to be
   rotated quickly to avoid taking up too much disk space.

Since we have a cluster level logging infrastructure, we can redirect the
logs endpoints to the logging infrastructure. This might require building a
new component that can proxy logs requests to various logging backends like
elasticsearch, Google Cloud Logging, etc.


Streaming logs has reliability and per trade offs.  Also, it forces
latency.  It's really important to keep log fetch latency between write and
read at O(seconds) otherwise the system becomes massively harder to debug. Some
people won't mind latency - let them stream.  Also, we have hit many use
cases where logs on node were critical to debug (logs in transit were lost).

One solution here is just a better log API than docker, like journald or
another store.  Batch or QoS log movement aggressively.  Rocket is already
better setup for this than Docker - we've done journald perf that makes us
pretty sure we can scale it as high as necessary.  Journald plugin to
docker has been discussed in passed.

Another is to move the log accounting to a volume accounted with the pod
(even if not mounted) and try to isolate it.  Doesn't resolve other
issues.  Can we take advantage of overlay or other mount trickery to set
hard limits?

Another alternative is to not support logs in our APIs and require users to
use their cluster logging infra to access all their logs.


Could be an option, but I think we will almost always want to run with logs
on, logs local but aggressively moved, etc.  don't think it's bad to allow
disable.


@smarterclayton <https://github.com/smarterclayton> @bgrant0607
<https://github.com/bgrant0607> @dchen1107 <https://github.com/dchen1107>
@a-robinson <https://github.com/a-robinson>

—
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/13846>.
