### ISSUE TITLE
vagrant libvirt network issue

### ISSUE THREAD

**Issue by mad0house** [kubernetes/kubernetes#13859]
Kubernetes 1.0.5

Did a Google could not find the answer when trying to use vagrant on rhel7.1 kube-up.sh errors out.

With the following message 

master: Job for network.service failed. See 'systemctl status network.service' and 'journalctl -xn' for details.

Looks like networking is failing somehow.

Configuration problem maybe

**Comment by davidopp** [comment]
Please direct your questions to stackoverflow.

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases.

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to similar questions, and also familiarize yourself with:

the user guide
the troubleshooting guide

**Comment by davidopp** [comment]
(URL is http://stackoverflow.com/questions/tagged/kubernetes)
