### ISSUE TITLE
enable filtering of responses from API

### ISSUE THREAD

**Issue by TomasTomecek** [kubernetes/kubernetes#13854]
# Use Case

I have a node with 1000 pods. I perform `GET /api/v1/pods`. Master sends megabytes of data. Unfortunately, I am interested only in several fields of the response.
# Solution

Provide a way to filter json in response to
- save bandwith
- improve performance

**Comment by smarterclayton** [comment]
We discussed this a long time ago with filtering responses.  The ideal case would be to avoid the load from etcd, but with increased in memory caches just returning the objects might be sufficient.  We now have jsonpath selectors - we could conceivably let users provide a subset of jsonpath on the list call to restrict the response.  We'd have to be careful since jsonpath is arbitrary, but building a simple template isn't that difficult:

    GET /api/v1/pods?only=metadata.name,metadata.uid,spec.containers.image

for example.

**Comment by smarterclayton** [comment]
@erictune was the last person to have an issue related to this IIRC

**Comment by davidopp** [comment]
@brendandburns @wojtek-t

**Comment by smarterclayton** [comment]
We have no plans to perform per field filtering, but now that we have alternate representations we could potentially do this.  Closing as it's not a short term thing, and pagination is more important.
