### ISSUE TITLE
Mergebot is not merging certain PRs, and I'm not sure why

### ISSUE THREAD

**Issue by davidopp** [kubernetes/kubernetes#13890]
If you search for open PRs with LGTM label and green tests, there are a few that have been in that state for a while but not merged and I'm not sure why (e.g. #13866, #13850, ...). Probably something I'm misunderstanding?

@brendandburns @lavalamp @ixdy

**Comment by lavalamp** [comment]
They appear to have been merged now. Did someone make a change to the submit queue? @brendandburns?

**Comment by brendandburns** [comment]
I hadn't made changes prior to you saying they got merged.  There is a degree of randomness due to what PR happens to be active when the e2e tests go back to green.  As discussed elsewhere, we should make it a priority queue.

Closing this issue (also, please file merge-bot issues in kubernetes/contrib, not kubernetes/kubernetes)
