### ISSUE TITLE
AWS: Allow to setup swap space for minions

### ISSUE THREAD

**Issue by mcbain** [kubernetes/kubernetes#13893]
Allow a setting to configure some swap space e.g. MINION_SWAP_SIZE=2. 
Even running on t2.medium (4G mem) the pods are restarting every 5min due OOM.

Examples:  monitoring-influx-grafana-v1, elasticsearch-logging-v1

**Comment by justinsb** [comment]
So I'm not sure whether this is specific to AWS, and I'm not even sure that swap space is the root cause.

I think we actually limit the memory usage of the containers e.g.:
https://github.com/kubernetes/kubernetes/blob/4b2d73dcb3df343b9f8a40ccb4f668fcc29eddd1/cluster/addons/cluster-monitoring/influxdb/influxdb-grafana-controller.yaml#L42

I suspect we're actually hitting that limit.  If you look at the syslog (/var/log/syslog I believe) you should see an out-of-memory report and I think that includes the actual memory usage at kill-time.

Are you running a particularly large cluster?

I was going to tag this as AWS, but I suspect it is actually an issue with the limits being too low.

**Comment by mcbain** [comment]
I will limit cpu and memory for my own pods too, maybe that helps.

**Comment by mcbain** [comment]
We are running currently only a mini cluster (v1.0.5) with 2 nginx private sites without any traffic.

```
NAME                                                                  READY     STATUS    RESTARTS   AGE
monitoring-influx-grafana-v1-rcseh                                    2/2       Running   247        2d
```
```
 [<ffffffff8117eac8>] pagefault_out_of_memory+0x18/0x90
Sep 15 06:29:26 ip-172-20-0-176 kernel: [497156.214079] memory: usage 204800kB, limit 204800kB, failcnt 1882989
Sep 15 06:29:26 ip-172-20-0-176 kernel: [497156.214080] memory+swap: usage 0kB, limit 9007199254740988kB, failcnt 0
Sep 15 06:29:26 ip-172-20-0-176 kernel: [497156.214158] Memory cgroup out of memory: Kill process 1376 (influxdb) score 58 or sacrifice child
```

The influxdb seems to be crashing in a loop

**Comment by thockin** [comment]
Note that once you turn swap on, basically all QoS guarantees you might
have made are gone.

**Comment by mcbain** [comment]
@thockin i reopend temp. only to add the logs about the restart due OOM.
