### ISSUE TITLE
apache-storm example is broken

### ISSUE THREAD

**Issue by danielschonfeld** [kubernetes/kubernetes#13944]
Since supervisors publish their hostname to nimbus, and the hostname in PODs are the Pod name which is unreachable with the current DNS system.  If a topology was deployed to nimbus, it would fail since there is no connectivity between supervisors.

To fix, the docker image needs to include a `storm.local.hostname` config variable populated with the pod IP address and there is no need at that point to use `hostPort` in the replication controller pod spec.

**Comment by bgrant0607** [comment]
cc @kubernetes/examples

**Comment by bgrant0607** [comment]
@ArtfulCoder : maybe a good example for #20688

**Comment by timothysc** [comment]
imho we should be moving "examples" out of the core.  They are better suited to live in helm or contrib.

**Comment by typhoonzero** [comment]
I have an repo make use of  ```storm.local.hostname``` for topologies to run, based on @mattf : https://github.com/typhoonzero/storm-docker, so where should I merge to?

**Comment by kargakis** [comment]
@ahmetb @kubernetes/sig-apps-misc

**Comment by ahmetb** [comment]
These examples are moved out of the main repo, to https://github.com/kubernetes/examples/tree/e00514bce95b38223f92c36b3a3fc526e5aaa94e/staging I see that this particular one hasn't been updated for a while. If you think it's still broken, please consider submitting a patch to kubernetes/examples repo.

**Comment by kargakis** [comment]
@ahmetb is there any plan to move example-specific issue in the examples repo?

**Comment by ahmetb** [comment]
cc: @sebgoa 

We're not planning to move issues here related to `examples/` over to the new `kubernetes/examples` repository.

The ultimate plan is to delete the `staging` directory until the community finds a better place for those examples (such as this Spark example) to live and continue to be maintained.

**Comment by sebgoa** [comment]
@ahmetb "we are not planning t" or "we are now planning to " ?

I think all example issues should be redirected to `kubernetes/examples`

**Comment by ahmetb** [comment]
@sebgoa We haven't talked about a plan to move the open examples-related issues over here (as the goal is to not to keep maintaining stuff in `staging/` any further). So I assumed we're not moving issues over. If you think we should, I'm open to it.

**Comment by sebgoa** [comment]
Since we are moving all the examples (maintained or not for now), we should redirect all issues to that issue.

Unless we code some issue importing mechanism, we could close all examples related issue here with a message to re-open an issue on kubernetes/examples.

Let's ping @spiffxp who I believe is doing a lot of triage.

Aaron, we are moving all examples to https://github.com/kubernetes/examples what is the best way to handle example related issues ?

**Comment by spiffxp** [comment]
Good question!  I've totally been making this up as a go along, erring on the side of leaving breadcrumbs that can be found later.

If nobody's opted to own this example, I'm not sure this issue is worth keeping open.  Is it tagged in a way that it could be easily found if someone decided to pick the example up later? eg: you could drop some well known text in a comment that could be searched for later, or maybe have a README in the broken example that has links to known issues with the example, etc.

**Comment by timothysc** [comment]
closing...

**Comment by timothysc** [comment]
Actually I made a PR to just remove this... and folks can work on the examples repo.

**Comment by foxish** [comment]
/close

Closing here. We should reopen against kubernetes/examples if it's still broken and unusable.
