### ISSUE TITLE
Missing type in v1.json

### ISSUE THREAD

**Issue by aleks-f** [kubernetes/kubernetes#13994]
I assume the missing type [here](https://github.com/kubernetes/kubernetes/blob/master/api/swagger-spec/v1.json#L5912) is an error?

**Comment by jlowdermilk** [comment]
Looks like an error. I wonder if it's because there are no annotations on any of the [PodExecOptions](https://github.com/kubernetes/kubernetes/blob/master/pkg/api/types.go#L1615) field. Incidentally [PodLogOptions](https://github.com/kubernetes/kubernetes/blob/master/pkg/api/types.go#L1580) and [PodProxyOptions](https://github.com/kubernetes/kubernetes/blob/master/pkg/api/types.go#L1638) are also missing annotations.

@lavalamp or @bgrant0607, does swagger generation rely on field annotations to correctly determine type for arrays, or is something else going on here?

**Comment by nikhiljindal** [comment]
Being fixed by https://github.com/kubernetes/kubernetes/pull/12507

**Comment by nikhiljindal** [comment]
Fixed by https://github.com/kubernetes/kubernetes/pull/12507
