### ISSUE TITLE
getaddrinfo failed: Name or service not known [tcp://redis-slave:6379]'

### ISSUE THREAD

**Issue by pbkwee** [kubernetes/kubernetes#14020]
When I load the guestbook page I get the following error.

<b>Fatal error</b>:  Uncaught exception 'Predis\Connection\ConnectionException' with message 'php_network_getaddresses: getaddrinfo failed: Name or service not known [tcp://redis-slave:6379]' in /vendor/predis/predis/lib/Predis/Connection/AbstractConnection.php:141
Stack trace:

What would the steps be to resolve this?

**Comment by pbkwee** [comment]
Figuring I need skydns or something for this to work (tried this struggling to get it working)?  Or is there some recipe that someone has to get this working out of the box?

**Comment by pbkwee** [comment]
got skydns working and that solved this problem.  seems like the guestbook howto should include the skydns steps if that dns is required to make the guestbook app functional.

**Comment by stiege** [comment]
+1
I get this issue also.

Tried problem solving by looking at some containers that were struggling to start:

frontend / php-redis
```
2017-01-01T19:13:55.422389759Z /usr/local/bin/apache2-foreground: line 7: exec: apache2: not found
```

I downgraded from `gcr.io/google-samples/gb-frontend:v4` to `gcr.io/google-samples/gb-frontend:v3`. This allowed php-redis to start properly but still kept what looks like the same dns problem.

Struggled to troubleshoot further as kubernetes rookie and couldn't get `apt-get update/upgrade` to work in order to debug with nslookup from dnsutils.

I was trying to run the guestbook example using the multi-machine vagrant setup at https://coreos.com/kubernetes/docs/latest/kubernetes-on-vagrant.html

A bit of looking also made me consider maybe the problem was related to https://github.com/kubernetes/kubernetes/issues/14533
