### ISSUE TITLE
kubectl replace-or-create would be helpful

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#14040]
I often find myself doing this:  `kubectl replace -f template || kubectl create -f template`, because I want to replace the existing RC, but I also want to create it if it was deleted.  This works, but it is messy (the error handling isn't quite right; error messages when kubectl replace fails etc).

It would be helpful to have `kubectl replace -or-create -f template` do the right thing:  check if the named object exists, then do a replace if so and a create if not.

(Deliberately bad straw-man argument naming :-) )

**Comment by bgrant0607** [comment]
Seems reasonable. In the api, PUT should have create-or-replace semantics #2114.

But `kubectl apply` #1702 is really a better solution and hopefully we'll have that soon.

**Comment by bgrant0607** [comment]
apply is the recommended way to do this.

**Comment by discordianfish** [comment]
I use `replace` instead of `apply` when updating large configmaps to get around the annotation size limitation, so in this case a replace-or-create would be still useful..

**Comment by bgrant0607** [comment]
A flag on create would be the simplest approach to this.

https://github.com/kubernetes/kubernetes/issues/30558#issuecomment-331342865

**Comment by bgrant0607** [comment]
cc @seans3 @monopole

**Comment by montanaflynn** [comment]
I'm creating or replacing a configmap from a file and use this pattern:

```
kubectl create configmap db-schema --from-file=file.sql -o yaml --dry-run | kubectl apply -f -`
configmap/db-schema configured
```

**Comment by Asday** [comment]
This seems useful to me as someone completely new to k8s.  I'm reading the docs and trying to futz my way through how I'd use it in a sensible manner, and it looks like I don't want to use `apply` at all, because that could mean that the cluster state drifts from my version-controlled configuration.  This means I'd always do `git pull && kubectl replace -R -f .` on push, except when something's new, in which case I'd have to add some intermediate step that somehow checks for new stuff and `create`s it instead.

**Comment by prein** [comment]
@montanaflynn this doesn't help for the issue described by @discordianfish in https://github.com/kubernetes/kubernetes/issues/14040#issuecomment-430605486

**Comment by alculquicondor** [comment]
@soltysh has this been considered?

**Comment by soltysh** [comment]
@alculquicondor with `kubectl apply` that'd be my current recommendation rather than implementing replace or create.

**Comment by seans3** [comment]
The canonical way to **create or update** is `kubectl apply`. If the reservation with using `kubectl apply` is the size of the resource (because it stores the entire applied config in the `last-applied-annotation`), then the user should use server-side apply: `kubectl apply --server-side ...`. Server-side apply went beta in version `1.16`. Closing.

/close

**Comment by llamasoft** [comment]
Just a heads up that `kubectl apply` isn't a perfect replacement for `kubectl create || kubectl replace`, specifically when it comes to _certain_ list types.  `kubectl apply` will attempt to _merge_ [some types of lists](https://kubernetes.io/docs/tasks/manage-kubernetes-objects/declarative-config/#how-different-types-of-fields-are-merged) whereas `kubectl replace` will always replace them.

This normally isn't a big deal but this subtle difference can cause production issues.  For example, if you rename a container or volumeMount between deployments, the merge result may end up with more containers or volumes than you wanted.

**Comment by mjamaah** [comment]
you can do this: `kubectl create -f template 2>/dev/null || kubectl replace -f template`, you will create the resource if it does not exist and suppress the error if it is, then replace it if exist.

**Comment by bhperry** [comment]
create || replace is pretty good, although it's worth noting that for yamls with multiple objects in them it would be really nice to have a kubectl command that handles the create/replace on a case-by-case basis
