### ISSUE TITLE
Swagger spec: Incorrect response model for /api/v1/namespaces/{namespace}/pods/{name}/log

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/kubernetes#14071]
Reported by @ae6rt: https://github.com/kubernetes/kubernetes/issues/14048#issuecomment-140858146

Spec says response model is v1.Pod. While the response is just string (logs in plain text form)

**Comment by lavalamp** [comment]
Probably a simple fix.

**Comment by nikhiljindal** [comment]
Problem is that we use storage.New object to figure out the rest mapping and use the same object to determine the returned object: https://github.com/kubernetes/kubernetes/blob/master/pkg/apiserver/api_installer.go#L124
We need to decouple them.

I could be completely wrong, but I can think of 2 ways to fix this:
* For subresources, we can get version, kind and mapping from the parent resource, and let storage.New determine the returned object (Is there a subresource whose version and kind differs from its parent resource?). Or
* We can introduce a new method storage.ReturnedObject that we use to determine the returned object. storage.New continues to be used to determine the version, kind and mapping.

cc @bgrant0607 @smarterclayton

**Comment by nikhiljindal** [comment]
fwiw, there is a TODO in LogRest.New, to return a resource that represents a log rather than returning api.Pod: https://github.com/kubernetes/kubernetes/blob/master/pkg/registry/pod/etcd/etcd.go#L226
I guess the expectation was that we will define a new API resource to represent logs?

**Comment by smarterclayton** [comment]
Log is interesting because it has no set schema (not quite an object) and
can have multiple serializations.  For instance:

Raw text over http
Json stream
Raw text over websocket
Json messages over websocket
Syslog??

We may want to have a method that returns a description of the possible
response values in a form suitable for swagger, like we've added for
Streamer and Connector.

We also have methods that could potentially return multiple objects or
lists of objects (a template processor endpoint).

On Oct 8, 2015, at 11:10 PM, Nikhil Jindal <notifications@github.com> wrote:

fwiw, there is a TODO in LogRest.New, to return a resource that represents
a log rather than returning api.Pod:
https://github.com/kubernetes/kubernetes/blob/master/pkg/registry/pod/etcd/etcd.go#L226
I guess the expectation was that we will define a new API resource to
represent logs?

—
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/14071#issuecomment-146743696>
.

**Comment by nikhiljindal** [comment]
From https://github.com/kubernetes/kubernetes/issues/24664:

In addition to the incorrect responseModel, `produces` is wrong as well. It says:
```
"produces": [
       "application/json",
       "application/yaml",
       "application/vnd.kubernetes.protobuf"
      ],
```
while it returns `text/plain`

cc @dims

**Comment by smarterclayton** [comment]
Well, if you get an error it can produce any of those.  So it's correct.

**Comment by nikhiljindal** [comment]
@smarterclayton We should add `text/plain` to the `produces` list?

**Comment by smarterclayton** [comment]
Log should implement `StorageMetadata` which has `ProducesMIMETypes(verb string) []string`, and we should combine the errors we know the rest endpoint can throw (all the normal serializations) + the values returned by that method.

**Comment by dims** [comment]
@smarterclayton Hmm, i don't see any code that implements the StorageMetadata interface. Guess we have to start with LogREST?

**Comment by dims** [comment]
Don't know why this PR did not get linked:
https://github.com/kubernetes/kubernetes/pull/25707
