### ISSUE TITLE
vagrant up for the HA example fails

### ISSUE THREAD

**Issue by v1k0d3n** [kubernetes/kubernetes#14116]
grabbed a fresh copy of the HA example directory and tried to vagrant up the example, but get the following:

````
==> kube1: % Received % Xferd  Average Speed   Time    Time     Time  Current
==> kube1:                                  Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
==> kube1: c
==> kube1: u
==> kube1: rl: (7) Failed to connect to kube0.ha port 2379: No route to host
==> kube1: + echo 'failed etcd!!!'
==> kube1: failed etcd!!!
==> kube1: + '[' -s /tmp/curl_output ']'
==> kube1: + echo 'etcd failure.  exit!'
==> kube1: etcd failure.  exit!
````

i'm probably missing something basic, but I thought I would open an issue in case others are experiencing the same problem with starting the vagrant HA example.

**Comment by alex-mohr** [comment]
I'm sorry you're having difficulty getting it to work.

Unfortunately, I'm not familiar with the Vagrant HA setup, but perhaps something in the troubleshooting guide might help?  https://github.com/kubernetes/kubernetes/blob/release-1.0/docs/troubleshooting.md

Also, we're trying to move support-style questions to Stack Overflow (e.g. http://stackoverflow.com/questions/tagged/kubernetes) and limit github issues to explicit bug reports and feature requests, so I'm going to close this issue here.
