### ISSUE TITLE
Create user-guide doc about experimental APIs

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#14132]
Should explain:
* What experimental APIs are
* How to enable the APIs
* User expectations re. API stability, or lack thereof, and what to do if there is a breaking change (delete all the changed resources before updating the cluster, probably)
* Pointers to docs for the experimental APIs we currently have

cc @caesarxuchao @lavalamp @RichieEscarez

**Comment by bgrant0607** [comment]
cc @jszczepkowski @nikhiljindal @mikedanese @erictune @bprashanth

**Comment by bgrant0607** [comment]
cc @brendandburns

**Comment by lavalamp** [comment]
https://github.com/kubernetes/kubernetes/blob/master/docs/devel/api_changes.md#making-a-new-api-group

Some preliminary stuff added there.

**Comment by bgrant0607** [comment]
cc @vishh

**Comment by bgrant0607** [comment]
@lavalamp We need user guide in addition to developer guide.

**Comment by lavalamp** [comment]
Yeah, I agree. Just wanted what little documentation we have pointed out here.

**Comment by lavalamp** [comment]
This issue is mostly obsolete now that we don't even have an experimental group. @erictune-- do you agree? Is this covered by your recent doc changes?

**Comment by RichieEscarez** [comment]
Can we define here how we want to expose and refer to the "v1beta1" documentation?

(1)
Is "v1beta1 extension" the correct way to refer to what was previously the "experimental API"? 
What variations are okay? Does "beta extension for v1.1" also work?

Example: "...this feature is a beta extension that is currently supported only by v1.1..."

(2)
Are there any specific statements that need to be made about the v1beta1 features? For example, (if this applies?) the expected duration of support or possibility of dropping support?

(3)
Also, how should we highlight this content in the docs?
For each section of v1beta1 extension content (that has be inserted into a document of fully supported v1.1 content), what indicator should we use?

Will a banner work? We can use an 'includes' so that a shared statement can be inserted at key points.

This would also apply to stand alone docs (ie Jobs); we would include the banner there as well.

@MikeJeffrey

**Comment by lavalamp** [comment]
@RichieEscarez Let's define this.

> Is "v1beta1 extension" the correct way to refer to what was previously the "experimental API"?

__No__. There is no experimental API. There are three new features that are in beta in 1.1. There's no reason to mention the word "extensions" unless you're explaining where to find them in the API.

Also please avoid mentioning "v1beta1" without context, because we already had a v1beta1 version. Only developers should care about this, and they will need to know that it is "extensions/v1beta1", not just v1beta1.

> Example: "...this feature is a beta extension that is currently supported only by v1.1..."

Better: "...this feature is in beta beginning with v1.1..."

> Also, how should we highlight this content in the docs?
> For each section of v1beta1 extension content (that has be inserted into a document of fully supported v1.1 content), what indicator should we use?

I think that's totally up to you.

**Comment by erictune** [comment]
I consider this issue closed by https://github.com/kubernetes/kubernetes/pull/15339

**Comment by erictune** [comment]
BTW, There is no relationship between the "v1" in "v1.0 or "v1.1", versus the "v1" in "v1beta1".
one is the version for a specific API, and one is a version for a software package.

**Comment by lavalamp** [comment]
If @erictune is happy, I am happy.
