### ISSUE TITLE
Cannot watch individual non-namespaced resources (node, namespace, etc) using query param

### ISSUE THREAD

**Issue by jimmidyson** [kubernetes/kubernetes#14289]
e.g.

```
curl -k "https://localhost:8443/api/v1/nodes/mynode?watch=true"
```

Returns a 200 with the node detail & completes.

You also cannot upgrade to websocket due to the 200 response.

**Comment by lavalamp** [comment]
Sounds like a api installer bug. The old way migh still work (curl -k "https://localhost:8443/api/v1/watch/nodes/mynode).

**Comment by nikhiljindal** [comment]
As per @smarterclayton's comment https://github.com/kubernetes/kubernetes/issues/8337#issuecomment-110163746, watch is not expected to work on individual objects.
As per swagger spec, watch query param does not exist on ```v1/nodes/{name}```. It does exist on ```v1/nodes``` (Verified that ```curl -k "http://localhost:8080/api/v1/nodes?watch=true"``` works)

@smarterclayton @bgrant0607 Was it because we did not finish the work to support watch query param or is there a reason not to support it?

**Comment by nikhiljindal** [comment]
As per discussion with @bgrant0607 this was not intentional.
We can support ```v1/nodes/myNode?watch=true``` in the same way as we support ```v1/watch/nodes/mynode```

**Comment by smarterclayton** [comment]
Well, I intentionally only implemented watch on list.  We *can* support it,
but I specifically targeted only watch on list as an API mechanism.  Watch
on item is supported via field selector.  The legacy path is implemented
via faking out the list call.

On Oct 8, 2015, at 7:22 PM, Nikhil Jindal <notifications@github.com> wrote:

As per discussion with @bgrant0607 <https://github.com/bgrant0607> this was
not intentional.
We can support v1/nodes/myNode?watch=true in the same way as we support
v1/watch/nodes/mynode

—
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/14289#issuecomment-146714377>
.

**Comment by bgrant0607** [comment]
It's true that it's a big weird because the query parameter would need to change the type of resource returned (List vs. specific resource type).

**Comment by jimmidyson** [comment]
OK using field selector is fine - thanks for reminding me of that. I'll close this now unless you actually want to support this directly via watch query param in named resource?

**Comment by nikhiljindal** [comment]
I think its fine to not support it, since field selector works. 
Closing the issue.

**Comment by lavalamp** [comment]
ah yes, sorry, I triaged this too quickly yesterday. You have to watch the group (w/ name selector), or at least list it first-- there's no place in the individual object to give a resourceVersion you can watch at.

**Comment by smarterclayton** [comment]
I believe the original reasoning I had was

* list returns a list of items
* watch returns a stream of changes about an item or items
* the fundamental type of a watch is a stream, and a stream is a list of
changes to a set of resources
* to a caller, there is no observable difference of type between watching a
list and watching a single item
* rather than try to have two ways to watch the same thing, have one way
and document it well
