### ISSUE TITLE
Experimental: Job status not being updated 

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#14308]
We need code in the job controller to update the status of the job.  That isn't happening right now.

@mikedanese @soltysh

**Comment by erictune** [comment]
Job is useable without this but kinda confusing.

**Comment by soltysh** [comment]
I kinda experienced that today, while working with e2e tests, but wasn't sure about the source of the problem, I'm quite positive it was implemented in such a way that the status was updated. Right now I'm getting lots of update failures because of job being updated in the mean time. Getting fresh version before doing the update didn't help. I'm working on it right now, this brakes my e2e tests right now, so without it I can't move forward. Assign this to me please.

**Comment by erictune** [comment]
@mikedanese can you invite @soltysh so I can assign stuff to him

**Comment by erictune** [comment]
I know this was assigned to you, but I was playing around and got curious.

**Comment by soltysh** [comment]
n/p I can pick this up and focus on e2e :smile:
