### ISSUE TITLE
Modify local-up-cluster to create a simple kubeconfig file for cluster authentication.

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/kubernetes#14355]
The e2e tests need a kubeconfig file to run, which can be empty. 

Should we just allow them to run optionally **without** a kubeconfig file?  

Seems like an unnecessary distraction to running them.

**Comment by erictune** [comment]
@jayunit100 how would the test learn what credentials to use and what URL to reach the master on?

**Comment by roberthbailey** [comment]
In #14112 it was mentioned that the kubeconfig file isn't needed when creating a local cluster, so presumably you might want to run e2e tests on a local cluster without a kubeconfig? Even so, it seems like part of creating a local cluster would be to create a kubeconfig file so that kubectl knows to hit the local apiserver. You could rely on the fact that the default url is localhost, but that seems unnecessarily brittle when all other e2e tests need a kubeconfig file anyway. I think it would make more sense for local cluster up to create a kubeconfig entry that explicitly points to the localhost url.

**Comment by jayunit100** [comment]
+1 makes sense I have a similar patch I can retool for this

**Comment by kargakis** [comment]
I think this one is done

**Comment by jayunit100** [comment]
If this is done and the default is same it should be referenced in e2e tests
