### ISSUE TITLE
AWS Cluster Creation Fails when checking if API is reachable (1.0.6)

### ISSUE THREAD

**Issue by mmarcant** [kubernetes/kubernetes#14380]
When trying to spin up a new cluster on AWS with these variables:
```
export KUBE_AWS_ZONE=us-east-1a
export NUM_MINIONS=3
export MINION_SIZE=m3.large
export MINION_ROOT_DISK_SIZE=16
```
and running this command:
```
export KUBERNETES_PROVIDER=aws; wget -q -O - https://get.k8s.io | bash
```
 I keep running into this error:
```
Waiting for cluster initialization.

  This will continually check to see if the API for kubernetes is reachable.
  This might loop forever if there was some uncaught error during start
  up.

Kubernetes cluster created.
panic: assignment to entry in nil map

goroutine 1 [running]:
k8s.io/kubernetes/pkg/kubectl/cmd/config.ModifyConfig(0x2208d69fd8, 0x208da4640, 0x0, 0x0, 0x0, 0x0, 0x0, 0x208e31020, 0x208e31050, 0x208e31080, ...)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/config/config.go:226 +0x1508
k8s.io/kubernetes/pkg/kubectl/cmd/config.createClusterOptions.run(0x2208d69fd8, 0x208da4640, 0x7fff5fbffb54, 0xe, 0x1, 0x7fff5fbffb6c, 0x16, 0x0, 0x0, 0x0, ...)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/config/create_cluster.go:100 +0x262
k8s.io/kubernetes/pkg/kubectl/cmd/config.func·003(0x208e40b60, 0x208d86d80, 0x1, 0x4)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/config/create_cluster.go:68 +0x88
github.com/spf13/cobra.(*Command).execute(0x208e40b60, 0x208d86d40, 0x4, 0x4, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/spf13/cobra/command.go:495 +0x65c
github.com/spf13/cobra.(*Command).Execute(0x208e821a0, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/spf13/cobra/command.go:560 +0x18d
main.main()
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubectl/kubectl.go:30 +0x104

goroutine 5 [chan receive]:
github.com/golang/glog.(*loggingT).flushDaemon(0xc37600)
	/go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/golang/glog/glog.go:879 +0x78
created by github.com/golang/glog.init·1
	/go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/golang/glog/glog.go:410 +0x2a7

goroutine 11 [syscall]:
os/signal.loop()
	/usr/src/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/usr/src/go/src/os/signal/signal_unix.go:27 +0x35
```

This was working for me quite well over the past week, but I starting running into this today.
Any suggestions?

**Comment by bgrant0607-nocc** [comment]
Please re-post your question to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes). 

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases. 

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to similar questions, and also familiarize yourself with:
  * [the user guide](http://kubernetes.io/v1.0/)
  * [the troubleshooting guide](http://kubernetes.io/v1.0/docs/troubleshooting.html)

Again, thanks for using Kubernetes.

The Kubernetes Team
