### ISSUE TITLE
Figure out what to do with lastProbeTime

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#14393]
We're disabling it due to sending too many status updates (#14390).

We need to figure out if it should be in the API at all, and if so, how we can put useful information in it without sending the # of status updates through the roof.

**Comment by bgrant0607** [comment]
Ideas to improve performance, most of which aren't specific to this field:
* We can rate limit uninteresting updates.
* Unlike desired state, status doesn't need to be 100% persistent. Like Events and Metrics, we should support high-throughput updates to status, such as by caching in memory with async. replication.
* Use PATCH rather than PUT to communicate deltas
* Binary encoding
* Bulk updates

cc @nikhiljindal @yujuhong

**Comment by lavalamp** [comment]
The problem is write load, so currently only rate-limiting helps.

**Comment by dchen1107** [comment]
Yeah, that is my understanding here too. One small improvement is that we don't need to update lastProbeTime if there is no ReadyProber specified.

**Comment by yujuhong** [comment]
I assume `LastProbeTime` in this context (pod ready condition) means the last time we probe/check the readiness and liveness. This could potentially be handled by the new prober with defined probing periods for each container (#12866).

@bgrant0607, do we expect to add any other pod conditions that may rely on kubelet to periodically send status update, even when there is no change? I was hoping kubelet can move towards a more event-driven model, and reduce overly-frequent periodic sync.

**Comment by bgrant0607** [comment]
@yujuhong Are you asking about polling of the containers or sending status to apiserver? Polling: yes, we'll probably want to poll some performance-related stats or condition. Sending status: Metrics are another example.
