### ISSUE TITLE
how does controller-manager select pods when we reduce replicas of a cluster?

### ISSUE THREAD

**Issue by fzu-huang** [kubernetes/kubernetes#14396]
I have a cluster with 5 pods, but two of them were created failed because of incapacity,the others were running normally.
so I reduce the replicas of cluster from 5 to 3 ,   I hope  that the controller-manager will delete the two failed pods, but it didn't.(sometimes it will delete 1 or 2 of the failed pods. Maybe it select pods randomly???)

another question.

I run a cluster with 3 replicas:
[root@vm-56-65 bin]# kubectl  get pods 
NAME                 READY     STATUS    RESTARTS   AGE
gomeimg-1j7eb        1/1       Running   0          11s
gomeimg-cv5z3        1/1       Running   1          1h
gomeimg-pq9j4        1/1       Running   1          1d

when I  do    `kubectl scale --replicas=2 rc gomeimg`  ,now the result is:
[root@vm-56-65 bin]# kubectl  get pods 
NAME                 READY     STATUS    RESTARTS   AGE
gomeimg-cv5z3        1/1       Running   1          1h
gomeimg-eid2s        0/1       Running   0          4s

kube-controller-manager close the pods gomeimg-1j7eb and gomeimg-pq9j4 (WHY CLOSE THIS ONE???) and start a pod name gomeimg-eid2s  .

I think it is dangerous . for example , when  I reduce the replicas of a cluster from 3 to 1, it might close all the pods and start a new one, too.

**Comment by bgrant0607** [comment]
Priority function is here:
https://github.com/kubernetes/kubernetes/blob/2da7e8d41fb32e00557f95c1bcd4419b96cd19b7/pkg/controller/controller_utils.go#L369

Unscheduled, pending, and not-ready pods are killed in preference to "running" pods, which includes pods with containers that have been or can be restarted. Failed pods are not counted against the replica count.

What do you mean by "failed because of incapacity"? 

Related to #4301.

**Comment by bgrant0607** [comment]
Using a similar health/availability notion as #11484 would make sense. Maybe prioritize by time since last restart and/or number of restarts.

Also related: #11234.

**Comment by bgrant0607** [comment]
Was addressed by #22065.
