### ISSUE TITLE
Node becomes unstable when overcommit on memory qos, does not always recover

### ISSUE THREAD

**Issue by derekwaynecarr** [kubernetes/kubernetes#14452]
I can reproduce a situation where the node can become unstable and never recover from a NotReady status using either the Vagrant or GCE based Kubernetes setups.

```
$ export KUBERNETES_PROVIDER=vagrant || gce
$ export NUM_MINIONS=1
$ export KUBE_ENABLE_CLUSTER_MONITORING=none
$ export KUBE_ENABLE_CLUSTER_DNS=false
$ export KUBE_ENABLE_CLUSTER_UI=false
$ cluster/kube-up.sh
```

Assuming you are using GCE, let's spin up the following:

```
$ cluster/kubectl.sh run mem-guaranteed --image=derekwaynecarr/memhog --replicas=2 --requests=cpu=10m --limits=memory=600Mi --command -- memhog -r100000 500m
$ cluster/kubectl.sh run mem-burstable --image=derekwaynecarr/memhog --replicas=2 --requests=cpu=10m,memory=600Mi --command -- memhog -r100000 100m
```

At this point, the Node is stable, and we have 2 guaranteed memory containers allocating 500MB of memory and writing to it repeatedly.  We also have 2 burstable memory containers allocating 100MB of container and writing to it repeatedly.  Both containers are using ```memhog``` utility.

The node is stable, and all is good.

If I do the following:

```
$ cluster/kubectl.sh run mem-besteffort --replicas=10 --image=derekwaynecarr/memhog --requests=cpu=10m --command -- memhog -r10000 500m
```

Where you may choose to scale the above based on replica size, the pods startup and each try to write 500MB of memory, and a ```SystemOOM``` event is triggered as expected.  

The Node may or may not remain stable at this point.  After some time, I found that even though we put the containers in a ```CrashLoopBackoff``` ultimately, the ```Kubelet``` ceased to report status back to the ```kube-apiserver``` for over 5 minutes and as a result, its status was reported as ```NotReady```.  I was unable to SSH into the GCE box to debug (it was locked out).

The only way I could get the node to fix itself was to kill the replications controllers in the cluster.  

After some time, it appeared the Node recovered and went back into a ```Ready``` state.  What I would prefer to have seen is that the Node remained ```Ready```, and only the ```BestEffort``` containers found themselves quarantined in a longer back-off period without affecting the other system processes from reporting status.

I looked at the logs for the 5 minutes that I encountered the NotReady status on the Kubelet and see messages like the following (using GCE):

```
/proc/2892/net/dev: open /proc/2892/net/dev: no such file or directory
I0923 21:41:28.895452    1361 helpers.go:96] Unable to get network stats from pid 2856: couldn't read network stats: failure opening /proc/2856/net/dev: open /proc/2856/net/dev: no such file or directory
...
failed to update stats for container "/0afe9347f4f12a9bfe3a6558f05cb48d0b3fd88540eb6e9950faa55c0ce41c1d": du command failed on /var/lib/docker/aufs/diff/0afe9347f4f12a9bfe3a6558f05cb48d0b3fd88540eb6e9950faa55c0ce41c1d with output  - fork/exec /usr/bin/du: cannot allocate memory, continuing to push stats
```

I recognize this is really difficult to debug over the last couple of days, but I am trying to determine if the ```Kubelet``` is getting wedged in a bad synch loop, and as a result, it no longer reports status back to the ```kube-apiserver```.

Will add more log details as I debug further.

@kubernetes/goog-node

**Comment by derekwaynecarr** [comment]
cc @kubernetes/rh-cluster-infra

**Comment by derekwaynecarr** [comment]
@timothysc - do you do any tests on clusters overcommited on memory in your work?

**Comment by vishh** [comment]
#13006 is very relevant here.

**Comment by vishh** [comment]
The kernel can get really slow in the event of a system OOM. In general, it
is better to reduce the likelihood of system OOMs.

**Comment by yujuhong** [comment]
> I recognize this is really difficult to debug over the last couple of days, but I am trying to determine if the Kubelet is getting wedged in a bad synch loop, and as a result, it no longer reports status back to the kube-apiserver.

Node status is updated by a separate goroutine (unrelated to sync loop of pods or CrashLoopBackOff), but overall slowness may have affected status reporting.

**Comment by derekwaynecarr** [comment]
@vishh - I get that it can get slow, but I thought by 5 minutes the CrashLoopBackoff for the offending containers would have kicked in, which is why I wondered what the reasonable expectation should be.  Thanks for the pointer to doc in progress.

**Comment by dchen1107** [comment]
@derekwaynecarr what you observed is expected. I mentioned in many occasions / meetings that we are not ready for overcommit on memory qos, and we should treat it as experimental feature only. One example is https://github.com/kubernetes/kubernetes/issues/12422#issuecomment-129545970

 Here are some of reasons: 

1. At node level, the only improvement was introduced is OOM score based on the resource class. This means we fully rely on Kernel sys OOM to react. This is dangerous, which could put the node to totally unstable mode. Based on my experience dealing with internal system, when sys OOM is triggered, before kernel kills some processes, process kswapd might use 100% CPU on a node to reclaim some pages, which could include disk io too, thus. All user processes are significantly slow down. **You can overcommit on request or limit, but Kernel sys OOM should be prevented**
1. This also means we should introduce a userspace memory manager to detect system overcommit on memory at run time. When memory pressure on the node is pretty high, and kubelet should proactively kill some lower priority containers / pods. We don't have this for today. 
1. Today all containers are at root level, instead of using cgroup_parent based on QoS. This means, the root cgroup is easily get oom-ed, instead, only some subcgroup. We plan to use cgroup_parent to improve QoS for 1.1 release, but don't have time to really get on it. 
1. Docker daemon uses tons of memory, even with 1.8.2 release. There is no good way to limit / reduce docker's resource footprint today. Currently it runs in a resource-only cgroup called /docker-daemon, and I limited it to 60% of node memory capacity. 
1. Other infrastructure daemons (kubelet, kube-proxy)' memory usage is scaled by workload. More work, more management overhead. We don't limit / budget them today. For 1.0 release, I put each one of them into a subgroup under root without limitation for monitoring / measurement only. We should have budget for them. 
1. We don't control all nodes. This means there are tons of processes / daemons running as native processes on a given node, including sshd. For measnurement / monitoring purpose, I put them in a resource-only cgroup called /system without any limit. We should have budget for them too. 
...

**Comment by dchen1107** [comment]
cc/ @bgrant0607 we talked about only advertise QoS feature as an experimental one for 1.0 with detail known issues.

**Comment by erictune** [comment]
Great summary of issues @dchen1107

**Comment by derekwaynecarr** [comment]
@dchen1107 - as always thanks for the summary.  I was trying to see just how bad things were, and if given enough time, would node stabilize in a bad actor scenario using normal crash loop back-off.  Sounds like 5 minutes was an insufficient time period to wait, but I had to disconnect.  I would like to assist in these issues moving forward so once again the summary very helpful.

As for 1.1, I think it would be reasonable to reserve some amount of system resources in the default Salt setups for the Docker and Kubernetes related daemons by placing something to reserve node resources in /etc/kubernetes/manifiests.  Right now, it looked like the code was limiting Docker cgroup to max(70pct node memory, 150Mi).  I know in the ```--system-container``` work, we are not yet subtracting those resources from node capacity, but I think the current user experience could be improved in interim if we gave a more accurate representation by having a file sourced pod that captured system daemons reserved memory usage even if with a request value that is very small value out of the box with a much higher limit.

Otherwise, user's seem to think Kubernetes does have control of the total node and may get confused when doing ```kubectl describe node```

**Comment by dchen1107** [comment]
>As for 1.1, I think it would be reasonable to reserve some amount of system resources in the default Salt setups for the Docker and Kubernetes related daemons by placing something to reserve node resources in a file based pod. Right now, it looked like the code was limiting Docker cgroup to max(70pct node memory, 150Mi). I know in the --system-container work, we are not yet subtracting those resources from node capacity, but I think the current user experience could be improved in interim if we gave a more accurate representation by having a file sourced pod that captured system daemons reserved memory usage even if with a request value that is very small value out of the box with a much higher limit.

You are combining 2 different issues together:

* system daemons like kubelet, docker, kube-proxy and other daemons not running as pod: We should reserve some resource upfront for them, and let Kubelet reports Allocable resource to upstream layers, and scheduler should schedule work based on allocable, not capacity. Otherwise, you just simply limit daemons' resource consumption without proper provisioning, thus not prevent any sys oom at all. Here is the issue I filed for this: https://github.com/kubernetes/kubernetes/issues/13984

* File based pod, such as fluentd. We can update them with some memory limits / request.

**Comment by yujuhong** [comment]
@dchen1107, I think @derekwaynecarr meant that we could create place-holders (i.e., do-nothing file-based pods) to reserve some system resources, so scheduler can subtract these reserved resources from the total node resources to prevent overcommitting. The notion of allocable resources introduced in #13984 would achieve the same effect though.

**Comment by derekwaynecarr** [comment]
@yujuhong - your understanding was correct.

**Comment by timothysc** [comment]
@derekwaynecarr I've not tested, but happy to share cluster is fairly idle atm working on other changes.

**Comment by derekwaynecarr** [comment]
I am closing this issue since eviction on node, and qos requirements capture known next steps.
