### ISSUE TITLE
Fuzz() method on IntOrString causes gofuzz linked into prod code

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#14460]
Sigh.  Not a huge deal but need a better answer.

**Comment by BenTheElder** [comment]
we would need gofuzz to use an interface instead of a concrete type in their own interface, I think

`fuzz.Interface` is:
```go
type Interface interface {
    Fuzz(c Continue)
}
```
where `fuzz.Continue` is a struct:
```go
type Continue struct {

    // For convenience, Continue implements rand.Rand via embedding.
    // Use this for generating any randomness if you want your fuzzing
    // to be repeatable for a given seed.
    *rand.Rand
    // contains filtered or unexported fields
}
```
with a collection of methods.

fuzz.Continue could be instead:
```go
type Continue interface {
    Fuzz(obj interface{})
    FuzzNoCustom(obj interface{})
    RandBool() bool
    RandString() string
    RandUint64() uint64
    Rand() *rand.Rand
}
```

and then we could use a local identical interface. https://play.golang.org/p/JOzEab2izmD

this would require API changes upstream due to callers accessing the embedded rand.Rand, or an alternative interface / fuzz method ...

**Comment by BenTheElder** [comment]
much more elegant: we can only implement this method in code at test time
I'll file a PR.
