### ISSUE TITLE
FR: Allow specifying the allowed source IPs for a service exposed as a Load Balancer

### ISSUE THREAD

**Issue by chrisleck** [kubernetes/kubernetes#14505]
By default, the AWS cloud provider enables all source IPs to access a service exposed through a cloud load balancer with the LoadBalancer type.  We should allow the source range(s) to be specified.

**Comment by bgrant0607-nocc** [comment]
cc @justinsb

**Comment by justinsb** [comment]
I agree this would be useful.  I don't think this is specific to AWS though - I believe it applies to all clouds (?).

One simple option would be to have this be a configuration parameter, where instead of opening to 0.0.0.0 we would open all services to the same CIDR.  This would be useful for a "private k8s", but not useful for a mixed-public/private k8s where some services are private and some are not.  And given this would be yet another flag, I don't think it's a great idea.

The "correct" option is probably to extend the API.  Probably with something that can apply to NodePort, LoadBalancer and future Layer7 load-balanced services.

Going to un-mark as AWS as I don't think we want to do something AWS specific.

@chrisleck having more details of your use-case would be helpful (e.g. do you want to restrict to your office IP block, or a different AWS group, or some potentially long whitelist of IPs etc)

**Comment by thockin** [comment]
#14545 is coming from the same place but is more generically worded.

As I said in the email on that one - I would support something like this but we need to be careful with cross-cloud compat (or go it ourselves with more iptables) or lump it into the budding network policy discussion

**Comment by chrisleck** [comment]
@justinsb - you are correct in that we'll want a mix of public & private services.

For example, I'll be exposing my service's frontends through a public LB.  However, I'll want to expose my internal services' debug endpoints via a LB only open to my corp's IPs or only open within a private subnet accessed via VPN to a remote site.

**Comment by Symmetric** [comment]
This sounds like a simple use-case for the sort of generic network policy language we have been discussing, so I reckon it's a good candidate to be included in the policy discussions.

To handle this you need a way to define the set of LB IPs; this can currently be implemented with a headless Service with a custom EndpointSet, or we could add a more simple/less overloaded "IP Set" entity. 

Then we need a way of specifying Policy which states semantics like "allow http from service=LoadBalancers, deny otherwise". This policy can be applied at the namespace boundary as proposed in https://github.com/kubernetes/kubernetes/issues/13459, or we could selectively apply the Policy to pods inside a namespace using using label selectors.

**Comment by thockin** [comment]
Close in favor of #14545
