### ISSUE TITLE
Access to private services from outside kubernetes cluster

### ISSUE THREAD

**Issue by rvrignaud** [kubernetes/kubernetes#14545]
Hello,
Following discussion started here : https://groups.google.com/forum/#!topic/google-containers/vpm1nmpHMNs.

We currently need a way to access, within the same private network but outside of Kubernetes cluster, to services defined in the cluster. Use case vary from private internal services accessed from VPN users to communication from "regular" instances to services running in cluster on the same network.

In my case, not every instances on my network have external IP address and I would like to avoid using external load balancer for that.

For now, I'm using a kube-proxy in my VPN gateway, but it won't work to reach multiple kubernetes cluster and doesn't solve the instance to k8s service access.

Any idea how to solve this problem ?

**Comment by thockin** [comment]
You need to "promote" an in-cluster Service to a higher order.  You can do this by running kube-proxy as you figured out, but that's a pretty clumsy answer overall, for reasons you have discovered and more.

You can elect a machine in your private network to act as an "external" load-balancer (https://github.com/kubernetes/contrib/tree/master/service-loadbalancer) or you can set Services as NodePort type and use "special" ports on your cluster nodes or you can claim specific ports on your nodes (https://github.com/kubernetes/contrib/tree/master/for-demos/proxy-to-service).

**Comment by ArKam** [comment]
Calico's way to do such a policy enforcement and isolation based on namespaces tags is such a sexy and lightning fast solution, you should take a look at their example over tectonic instance.

**Comment by thockin** [comment]
To circle back to this:  What we can do in GCE is set up static routes which send the service IP range for a given cluster to one or more kube nodes in that cluster.  The kube-proxy logic takes over and delivers traffic.

**Comment by JeanMertz** [comment]
FYI: this is currently all possible, we've got an external VPN, configured to allow us to access internal GKE pod and service IPs (and also use the internal GKE DNS over VPN).

There is one thing that isn't automated yet, and we had to write our own tool:

Routes on GCP only allow you to route to a specific IP or instance/node (or internet gateway or VPN tunnel), instead of to a group of instances with a network tag.

So, if your GKE (or GCE) Kubernetes nodes are removed/replaced (for example, when using preemptible nodes, or when upgrading node-pools), your routes no longer work, and you can't access service IPs.

We use a small tool running in our cluster that keeps the Kubernetes nodes and GCP routes in sync.

See: https://gist.github.com/JeanMertz/9fabe929cddfa7cf155ab9c72b61d140

As @thockin explained, we route the `servicesIpv4Cidr` (`gcloud container clusters describe cluster-name | grep servicesIpv4Cidr`) range to all our nodes using the above script.

Then, we set the `kube-dns` service IP as one of the nameservers in our VPN config, and route the above IP range and pod IP range `clusterIpv4Cidr`) over a VPN tunnel into GCP.
