### ISSUE TITLE
Restrict/prefer what pods schedule on particular nodes

### ISSUE THREAD

**Issue by erimatnor** [kubernetes/kubernetes#14573]
So, pods can have node selectors, which allows pods to be scheduled only on specific nodes. However, I can find no way to do the reverse; namely to say a node can only host pods that have certain labels.

The above would be useful in case one would like to limit which types of pods get scheduled on a node. For instance, there's an AWS machine with an instance disk and you'd like it to run an HDFS pod. However, you don't want other pods to be scheduled on the node, because they might steal resources and potentially make the HDFS pod unschedulable.

I know I can achieve this by labeling all my nodes and pods and equipping all pods with node selectors. But that is a lot more work and less elegant.

**Comment by lvlv** [comment]
Is it the same as add label to node and apply selectors in pods? If yes,
this is already supported.

**Comment by davidopp** [comment]
This is not currently supported. I agree it would be useful. It is related to anti-affinity but not exactly the same. As always, PRs are welcome. 

There are two paths to this:

(1) Continue to use node selectors. First we'd implement generalized node selectors (#341/#7053) so you can say "not \<label(s)\>". As you observed, this is hacky in that you'd have to put a node selector on every pod that you want to keep away from the node(s) in question. So the second step would be to automate putting that node selector onto Pods, perhaps using an admission controller like LimitRange but for selectors instead of limits.

(2) Add the concept of pod selectors, as you described. This would be a more efficient representation because it would scale with the number of nodes rather than the number of pods.

There's a lot of interest in generalized node selectors (and work begun on it already), so option (1) might be the first thing we deliver even though it's less elegant. But like I said, if you are interested in (2), PRs are always welcome (preceded by a design doc we can discuss, of course).

**Comment by bgrant0607** [comment]
Pod labels can't be expected to have consistent meaning across namespaces, so I don't think a pod selector on the node is a good approach.

We'll need something like @davidopp's suggestion about a LimitRange-like approach.

This is related to 2 general problems:
1. Resource stranding
2. Conferring attributes to the node from pods scheduled on it, which then affects scheduling of other pods. One such example is sole tenancy.

I don't have time to write up a full proposal now, but we should do so as part of #14816

**Comment by smarterclayton** [comment]
OpenShift today exposes a cluster default and namespace default node selector which is defaulted onto pods at admission time in order to limit placement per namespace (namespace setting trumps cluster setting).  That works well when admins manage the policy, but doesn't offer as much flexibility for users.  We recommend admins run with a default cluster policy which enforces a default for end users, while admins can reset their policy per namespace.

**Comment by bgrant0607** [comment]
See also #17190

**Comment by bgrant0607** [comment]
Also related: #17097, #17151

**Comment by bgrant0607** [comment]
This can be implemented using taints/tolerations
