### ISSUE TITLE
E2E soak test leaks static IPs sometimes

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#14597]
Perhaps when failing to create a forwarding rule or target pool, or when the test times out? Or maybe not test time out since kubernetes-soak-continuous-e2e-gke was timing out for 4 days without hitting this problem.

The symptom: E2e tests in the same project start to fail due to hitting quota limits on static ips. Sure enough, there are several unused static ips with names like a76b185ff63d711e5855b42010af01de.

@ixdy @quinton-hoole

**Comment by bgrant0607** [comment]
It's not just this test.

I reverted #14569 to see if that would help.

@a-robinson

**Comment by bgrant0607** [comment]
After reverting #14569, e2e tests have been passing.

**Comment by a-robinson** [comment]
Yeah, that PR will undoubtedly both
1. Use more static IP addresses, since every externally load balanced service now gets one
2. Cause static IPs to leak at the same rate or worse as target pools, because we delete them after we delete target pools.

We could somewhat alleviate the second point by deleting static IPs before target pools (but after forwarding rules), but we'll definitely need more quota in the projects anyway to handle the first point.

**Comment by a-robinson** [comment]
But as @thockin mentioned on #14569, this change is quite important for ensuring that service's externally load balanced IPs don't get changed out from under them.

**Comment by a-robinson** [comment]
Intended plan of action - increase the static IP quota in each project that runs e2e tests that create external load balancers (since the default of 7 is hardly even enough without creating load balancers), and make sure static IPs are included in the resource leak monitoring/gc tool that @fabioy has said he's going to write.

@bgrant0607 - do you recall which projects were running out of IPs?

Or @ixdy @jlowdermilk @zmerlynn - does anyone have context on which subset of projects the services e2e tests run in? Is it effectively all 22 of them?

**Comment by quinton-hoole** [comment]
@a-robinson Yes, it's effectively all of them.  And please document how much quota is required, both for future e2e test project setups, and for K8s users, who will presumably also need to increase their default quota.

**Comment by a-robinson** [comment]
Thanks -- where do we document our Jenkins projects?

**Comment by a-robinson** [comment]
And I'm only attempting to bump up to 20 per project since static IPs are considered more precious of a resource than target pools and forwarding rules :/

**Comment by a-robinson** [comment]
It also may avoid leaks if we parallelize the deletion of the target pool, static IP, and firewall rule, since GCE latency spikes won't affect us quite as much. I'll see if I can get to that later this afternoon

**Comment by a-robinson** [comment]
We now have at least 20 static IPs allocated in us-central1 in all of our jenkins projects.

**Comment by a-robinson** [comment]
Overnight, kubernetes-e2e-gce and kubernetes-e2e-gke-ci had no leaks, but there were a bunch of leaks (at least 26) in the kubernetes-jenkins project. Trying to figure out why that project was so disproportionately affected...

**Comment by thockin** [comment]
I had an e2e cluster that I was not being careful with but I also saw some
leaks.  I have cleaned up my project and am bringing up a new cluster from
head.  I only ran Services and KubeProxy.  Oh I did do a full run one
time.  Damn.  Will keep eyes open.

**Comment by a-robinson** [comment]
It's looking like this may be mostly fixed by #14964. In the three projects that I explicitly cleared out:
-kubernetes-e2e-gce: 0 leaks since Monday evening
-kubernetes-e2e-gke-ci: 1 leak since Monday evening
-kubernetes-jenkins: 1 leak since Tuesday morning

I've cleared out 3 more projects and will check back in on Monday, closing this if nothing looks any worse than than the first three projects.

**Comment by a-robinson** [comment]
Closing this for two reasons:
1. The leaks have been occuring very slowly.
2. #15286 will drastically reduce the possibility of leaking static IPs, since they're only held on to while updating a load balancer, not while it's in a steady state.
