### ISSUE TITLE
Kubelet resource usage tracking broken in GKE

### ISSUE THREAD

**Issue by brendandburns** [kubernetes/kubernetes#14620]
For example:
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gke-ci/8552/

I'm disabling the test in https://github.com/kubernetes/kubernetes/pull/14619

But we need to re-enable it, or roll-back the test.

@yujuhong @dchen1107 @kubernetes/goog-node

**Comment by brendandburns** [comment]
@roberthbailey fyi

**Comment by dchen1107** [comment]
Shouldn't this is part slow test, and the fix should be either:

1) Increase Kubernetes-e2-gke-ci timeout value if decide to include slow to that project or
2) disable all slow tests on that project? 

cc/ @roberthbailey Which one is required here?

**Comment by yujuhong** [comment]
The test runs 50 pods per node, which is over the default --max-pod limit of kubelet. The test relies on the flag --max-pods=100 being set in cluster/gce/config-test.sh. I will disable it for all GKE tests in jenkins/e2e.sh.

On the other hand, it's not clear to me where the timeout is set for a specific build. /cc @ixdy @quinton-hoole

**Comment by ixdy** [comment]
Timeouts for each Jenkins build are in the Jenkins project configurations themselves, which are not currently saved in version control anywhere. :\

**Comment by yujuhong** [comment]
Discussed with @dchen1107 about the test offline. There are several issues:

- Do we want to run any kind of kubelet resource monitoring test on GKE? Is it useful? @brendandburns @roberthbailey 
- We only override max-pods in GCE. Should the test itself figure out what platform it can run based on the #pods in the test (see #14698)
   * Per-test configuration allows greater flexibility (e.g., we may run 100 pods on GCE to test kubelet's scalability), but it'd make the tests more complicated as they need to be aware of the test environment (which many e2e tests already do); there is also the burden of updating the tests once the max-pod value changes.
- Does this test belong to SLOW tests or should it belong to a new category?
   * Not all slow tests have the same attributes. Arguably this test could be enabled only on selective builds. The downside would be more flags -- less readable/manageable e2e configs.
- Not all builds which run SLOW tests have the proper timeout value to run this test. We need to manually change them every time a slow test is added.

Re-assigning this back to @dchen1107 since she has more concerns about the PR.

**Comment by dchen1107** [comment]
Had offline discussion with @yujuhong. We are going to split current Kubelet resource usage tracking test into two, one is targeted for GCE, another one is for GKE. In this case, we won't mess up the test code itself by introducing if...else... knobs. Re-assign this back to @yujuhong
