### ISSUE TITLE
Unable to update/stop secrets volume

### ISSUE THREAD

**Issue by kelbongoo** [kubernetes/kubernetes#14638]
I have setup a secrets volume as per this guide (https://github.com/GoogleCloudPlatform/kube-jenkins-imager), and it is working fine and is accessible from the other services where it is referenced. And I can see it via "kubectl get secrets"
```
NAME                  TYPE                                  DATA
default-token-c7n16   kubernetes.io/service-account-token   2
my-secrets           Opaque                                7
```
However, on the man page, it says I should be able to update my-secrets via
```
kubectl rolling-update my-secrets -f new-my-secrets.yaml
```
but instead I get
```
Error from server: replicationControllers "my-secrets" not found
```
Similarly, the man page seems to say I should be able to run
```
kubectl stop pods my-secrets
```
but I get
```
Error from server: pods "my-secrets" not found
```
and I tried as well
```
kubectl stop secrets my-secrets
```
and got
```
error: no reaper has been implemented for "Secret"
```
Is my syntax correct ?

**Comment by kelbongoo** [comment]
OK found at least the correct syntax to remove
```
kubectl delete secrets my-secrets
```

**Comment by fabioy** [comment]
Please re-post your question to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes). 

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases. 

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to similar questions, and also familiarize yourself with:
  * [the user guide](http://kubernetes.io/v1.0/)
  * [the troubleshooting guide](http://kubernetes.io/v1.0/docs/troubleshooting.html)

Again, thanks for using Kubernetes.

The Kubernetes Team
