### ISSUE TITLE
Cloud load-balancers should have health checks for nodes

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#14661]
Given the state of cloud-LB today, most (GCE, AWS, Openstack) LB implementations target nodes indiscriminately.  We should ensure that the cloud-load-balancer is only targetting healthy nodes.

We should health-check to the nodes' kubelet or kube-proxy or add a new "do nothing but answer node health" daemon.

**Comment by bprashanth** [comment]
>We should health-check to the nodes' kubelet or kube-proxy or add a new "do nothing but answer node health" daemon.

Nodes will already flip to unhealthy after ~40s of kubelet silence, or immediately when something like docker death is observed by kubelet. You can probably fix it by swapping the nodelister: https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/service/servicecontroller.go#L77 with the conditional node lister https://github.com/kubernetes/kubernetes/blob/master/pkg/client/cache/listers.go#L119.

**Comment by bprashanth** [comment]
I mean, swap those *and* remove unhealthy nodes from the target instance group

**Comment by thockin** [comment]
That's a lot of propagation.  40s is an eternity

**Comment by bprashanth** [comment]
I mean your daemon could die too so you'll need a timeout. Avoiding the gce health checks suggestion because I'd rather do this in kube and have it work xplat.

**Comment by roberthbailey** [comment]
Healthchecking the kube-proxy seems like the best idea to me. Port 10249 is currently used for both healthz and pprof, and we might not want pprof data exposed to the internet. But it wouldn't be difficult to make healthz bind to 0.0.0.0 by default (even if we moved pprof to a different port) and then allow 10249 to be opened to healthcheckers as necessary. 

I don't think we should be doing our own healthchecking and manually modifying the target instance group. That code would be GCE-specific and seems like it's just re-implementing what is provided for free by the GCP cloud healthchecker as long as you can provide an http endpoint that is accessible to `130.211.0.0/22`.

**Comment by bgrant0607** [comment]
See #8673

**Comment by thockin** [comment]
I'm going close the dup (I dup'ed myself!).  This one has more info, so keeping it.

**Comment by bprashanth** [comment]
Why health check nodes instead of straight to network endpoint? If we do that, isn't the 40s eternity enough for node health checks?

**Comment by thockin** [comment]
Today we load-balance to nodes.  If a node dies, I want my cloud LB
targetting a different node ASAP.

**Comment by bprashanth** [comment]
Yes we can easily implement a short term solution where the service/ingress controller runs a goroutine that just polls health check daemons on the node. "Bouncy" makes that harder because kube-proxy will still continue to think the endpoint is ready. Even if we don't go to the extent of reporting utiliztion information per request, I think we should come up with somethig that re-uses an existing health check idiom (either nodecontroller health or liveness/readiness), in the long run. 

The risk of having some sort of instantaneous and binary feedback loop is osciallation or flapping. The "right" way to solve this, IMO, is to use backend weights.

**Comment by glerchundi** [comment]
@bprashanth @thockin which is the status of this issue? I would like to add GCE LB health checking, did you solved by making kubelet port available or how?

**Comment by thockin** [comment]
We're actually using cloud healthchecks for something different now, so we
should close this.

**Comment by glerchundi** [comment]
Ok @thockin can you point me to the documentation/issue/whatever to follow the new direction? I'll appreciate any hint that helps me finding out this concrete topic.

Thanks

**Comment by thockin** [comment]
https://github.com/kubernetes/kubernetes/pull/29409

**Comment by glerchundi** [comment]
thanks!

**Comment by bprashanth** [comment]
This is still an issue of course, meaning, if a node disappears due to partition we will take 40s to kill endpoints. If we had a health check endpoint, it would take O(5s). There are different ways to tackle it. 

One way is to make kube-proxy health checking much smarter (i.e use ipvs). We need to confirm that ipvs will autofail over if it noticed that eg a SYN got blackholed once. I wasn't able to confirm this with some preliminary tinkering: https://github.com/kubernetes/kubernetes/pull/30134#issuecomment-242941720

Another, is to make our health checking smarter. The problem right now is that the kubelet is responsible for reporting endpoint health and node status. We could come up with a system that reports endpoint health much more frequently, and doesn't actually run on the node: https://github.com/kubernetes/kubernetes/issues/28442

And yet another, is to actually do what this issue proposes, and add a secondary health check endpoint to nodes. Or find some clever way to leverage the same "healthcheck-nodeport" logic in a way that works for both "onlyLocal" and "Global" services.

**Comment by thockin** [comment]
On Fri, Oct 21, 2016 at 12:37 PM, Prashanth B <notifications@github.com> wrote:
>
> This is still an issue of course, meaning, if a node disappears due to partition we will take 40s to kill endpoints. If we had a health check endpoint, it would take O(5s). There are different ways to tackle it.
>
> One way is to make kube-proxy health checking much smarter (i.e use ipvs). We need to confirm that ipvs will autofail over if it noticed that eg a SYN got blackholed once. I wasn't able to confirm this with some preliminary tinkering: #30134 (comment)

I convinced myself that it DOES NOT do what we want.  it does exactly
what we do today.

**Comment by thockin** [comment]
Re-opening.  I do think we should have a node-level healthcheck for LBs that are not using the OnlyLocal annotation.

**Comment by cmluciano** [comment]
@MrHohn should this be assigned to you?

**Comment by MrHohn** [comment]
/assign

@cmluciano Sounds good. Though my open PR #45524 is only for GCE, we may also look for assignees for other cloud providers.

**Comment by MrHohn** [comment]
Unassigning as GCE part was done.
/unassign
/remove-area platform/gce
/area cloudprovider

**Comment by thockin** [comment]
Can you update what you think still needs to be done, and who should be
doing it?

**Comment by MrHohn** [comment]
@ngtuna for CloudStack

**Comment by jhorwit2** [comment]
@MrHohn This requires [at least v1.7.2](https://github.com/kubernetes/kubernetes/blob/50fa5637b6dc9538c908fbdd632ff1d3c59f65da/pkg/cloudprovider/providers/gce/gce_healthchecks.go#L34), correct?

**Comment by MrHohn** [comment]
> MrHohn This requires at least v1.7.2, correct?

@jhorwit2  Thanks for mentioning, that is correct. v1.7.2 is the earliest k8s version that kube-proxy properly serves healthz port. We should probably make it a global const somewhere.

**Comment by thockin** [comment]
Should we be doing this atthe Service controller level, or should this
simply be an implementation detail - if a cloud wants to do it, they should
do it, but it should not be part of Service Controller?

especially as we move towards Cloud Controller Manager ...

**Comment by colemickens** [comment]
I think they're sort of the same thing, the SC would just be calling into the cloudprovider and asking for this health check, or it would be part of the normal behavior of the SC calling the CP to create/update a load balancer.

It seems like it would be helpful if Kubernetes were prescriptive here, one way or the other, and that issues per-cloud-provider were opened to track them adding this health check.

Questions:
1. Are there backward compatibility concerns? Based on how I'd implement this in Azure on a first-pass, it would retroactively add health checks which seems potentially risky.

2. How is the cloudprovider supposed to know what port `kubelet` is listening on for `/healthz`? I don't think it's appropriate to hardcode the default port. This will lead to broken configurations for anyone that chooses to change the default port (maybe for security, not sure what all's exposed on /healthz...)

**Comment by MrHohn** [comment]
> I think they're sort of the same thing, the SC would just be calling into the cloudprovider and asking for this health check, or it would be part of the normal behavior of the SC calling the CP to create/update a load balancer.

I'd prefer the latter, make "ensure health check" another interface may place more constraints on cloud provider implementation --- given that even how health check is attached to a LB may happen very differently, and could be coupled with LB management.

> 1. Are there backward compatibility concerns? Based on how I'd implement this in Azure on a first-pass, it would retroactively add health checks which seems potentially risky.

Adding health check retroactively seems risky if adding health check itself is service disruptive. Another concern is various node versions --- some node reposes health check while others (in older version) don't.

> 2. How is the cloudprovider supposed to know what port kubelet is listening on for /healthz? I don't think it's appropriate to hardcode the default port. This will lead to broken configurations for anyone that chooses to change the default port (maybe for security, not sure what all's exposed on /healthz...)

To clarify, this "/healthz" is served by kube-proxy but not kubelet. The proxy healthz port is defined in the ports package:
https://github.com/kubernetes/kubernetes/blob/ca59d909cf1f1effad62830b1beeb3ea8a9d2125/pkg/master/ports/ports.go#L43
If someone choose to use a different healthz port in kube-proxy (via flag or config), they will need to do the same for service controller (or cloud controller manager).

**Comment by colemickens** [comment]
>Adding health check retroactively seems risky if adding health check itself is service disruptive. Another concern is various node versions --- some node reposes health check while others (in older version) don't.

I don't recall the stance on version skew, but if it has been there for at least a few revisions, then I'm not worried about the presence of `/healthz` presuming this feature wouldn't be backported. I hadn't considered that adding the health-check would be disruptive. Do we know if this is really the case in any of the supported clouds?

>To clarify, this "/healthz" is served by kube-proxy but not kubelet. The proxy healthz port is defined in the ports package:

Got it, thanks.

>If someone choose to use a different healthz port in kube-proxy (via flag or config), they will need to do the same for service controller (or cloud controller manager).

Hm, to my knowledge, most of the cloud-providers don't really even take configuration today (or if they do, it's inferred configuration discovered via their metadata servers).

I guess it wouldn't be the worst thing in the world if it defaulted to the default `kube-proxy` port and was overrideble inside the cloud provider, but there's still going to be the case where:

1. User is running with non-default healthz port.
2. User upgrades cluster, switches to CCM.
3. None of their (new) load-balancers work because they're now health checking a path on a wrong port.

The user doesn't really know why any of this is happening until they find this issue, find the corresponding PR for their cloud provider and find where the new flag/config field is.

**Comment by alok87** [comment]
@justinsb Do we have health check for AWS ELBs? We want to keep adding/removing nodes in the ELB based on health. What is the right way to do it.

We are not using k8s provisioned ELB, it is the ELB we have created. We want to keep healthy kubernetes nodes under it.

**Comment by jhorwit2** [comment]
@alok87 You'd want emulate what Kubernetes does in that scenario, which is either use the kube-proxy healthz endpoint, which is by default port 10256, or use the healthcheck port on the service if it's traffic policy is local.

**Comment by krmayankk** [comment]
Curious what is remaining here ? Also do all health checks (for both https, network, container native) go to kube-proxy 10256 port ? Why do they not go to kubelet ?

**Comment by thockin** [comment]
kube-proxy exposes "healthiness" as "was able to update the heartbeat recently.  We may want to go further with "readiness" vs "liveness" (I have an idea brewing) but it's unlikely that it will be totally user-defined.  Instead, I am focusing on things like node schedulability.  If the node is unschedulable, it should probably not be considered for new LB traffic.

That allow users to define arbitrary rules for what makes a node unschedulable, which is something we want anyway.

Closing this.  Thanks for the reminder :)
