### ISSUE TITLE
QoS tiers

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#147]
We have described QoS tiers in several presentations and the necessary underlying mechanisms are supported by lmctfy:
http://www.slideshare.net/dotCloud/eric-brewer-dockercon-keynote
http://www.slideshare.net/vmarmol/containers-google
http://www.linuxplumbersconf.org/2011/ocw/system/presentations/705/original/Control_Loops_In_Userspace.pdf
https://github.com/google/lmctfy

Borg: https://research.google.com/pubs/pub43438.html

We should expose QoS tiers through the Kubernetes pod API.

**Comment by bgrant0607** [comment]
Current thinking for basic tiers:
* Support specification of limit (max allowed) and request (min required for scheduling)
* If limit==request, then it's highest priority
* If limit > request, then middle priority (main reason to need this is for vertical auto-sizing)
* If no limit or request, then lowest priority
* Suggested defaulting is described in [resources.md](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/resources.md)
* High-priority pods/containers would get reserved resources.
* Lower-priority pods/containers would be put into cgroups with the resources reserved by the higher-priority ones subtracted, in addition to nested cgroups with their specified limits (using the proposed parent cgroup Docker feature)
* Containers specifying no cpu would get a tiny number of shares

We could also use core allocation, oom score adjustment, and other mechanisms to strengthen this basic protection.

**Comment by erictune** [comment]
@bgrant0607 @derekwaynecarr  would there be quota at each tier?

**Comment by bgrant0607** [comment]
@erictune Yes.

**Comment by erictune** [comment]
We will need to name the tiers/priorities so they can be referred to in the quota file.

**Comment by derekwaynecarr** [comment]
Is this post 1.0?  Want to know if I need to reserve time to handle quota related fallout?

**Comment by bgrant0607** [comment]
Yes, post-1.0.

**Comment by bgrant0607** [comment]
--cgroup_parent is in: https://github.com/docker/docker/pull/11428

**Comment by rjnagal** [comment]
Shall we go ahead with changes to differentiate between jobs with and without limits? Essentially introducing tier2 guarantees for jobs with unspecified limits?

**Comment by vishh** [comment]
+1 for having a limit for all jobs without limits. We need to reserve
resources for the system daemons as well.

**Comment by rjnagal** [comment]
Discussed offline. The minimal protection for sys daemons we have now is good enough for v1.0. We'll take up the rest post 1.0.

**Comment by erictune** [comment]
On Mar 3, I asked if there would be quota at priority (high, middle, low).  @bgrant0607 said yes.   

That would mean: 
  - quota file has separate quantites for each  resource type at each priority.  
  - ResourceQuotaSpec gets 3 ResourceLists: HardHi, HardMed, HardLow (names are just illustrative) 
  - ResourceQuotaStatus has HardHi, HardMed, HardLow, UsedHi, UseMed, UsedLo
  - as each pod is handled by quota system, exactly one of the Used* is incremented or decremented.

 
I thought of a second way to do this:
  - quota file separately accounts quota for "limit" (guaranteed resources) and "request" (allocated resources).
  - ResourceQuotaSpec gets 2 ResourceLists: HardGuaranteed, HardAllocated and   
  - ResourceQuotaStatus has HardGuaranteed, HardAllocated, UsedGuaranteed, UsedAllocated.
  - As each pod is handled by quota system:
    - the pod's limits are added or subtracted from the UsedGuaranteed.
    - the pod's requests are added or subtracted from the UsedAllocated.

**Comment by erictune** [comment]
@derekwaynecarr fyi

**Comment by erictune** [comment]
Evaluation:

Second option is easier to explain: it is simply summing existing fields of a pod.  Does not introduce priority concept.

Second option has fewer dimensions, and those dimensions map to real concepts (e.g. you might want the sum of HardGuaranteed quota to be less than or equal to the capacity of the cell (modulo bin packing  assumptions, etc).

**Comment by erictune** [comment]
For the second scheme, request < limit is treated as request := limit

**Comment by derekwaynecarr** [comment]
@erictune - my preference is option 2 as presented.

**Comment by AnanyaKumar** [comment]
I'm starting work on the Kubelet side of QOS tiers. Right now, my plan was to support 2 tiers - batch jobs and production jobs. Does this seem reasonable, or do you think keeping the code flexible to support an arbitrary number of tiers is essential?

**Comment by smarterclayton** [comment]
We *might* have a use case for a dev workload which is not batch, but
suitable for preemption.  However, it could probably be classified with
batch safely, so we don't have a concrete level beyond the two you mention.

On Jul 15, 2015, at 8:32 PM, Ananya Kumar <notifications@github.com> wrote:

I'm starting work on the Kubelet side of QOS tiers. Right now, my plan was
to support 2 tiers - batch jobs and production jobs. Does this seem
reasonable, or do you think keeping the code flexible to support an
arbitrary number of tiers is essential?

—
Reply to this email directly or view it on GitHub
<https://github.com/GoogleCloudPlatform/kubernetes/issues/147#issuecomment-121789319>
.

**Comment by bgrant0607** [comment]
What exactly do you plan on doing, @AnanyaKumar?

I don't think we need an arbitrary number of tiers.

Please see my proposal here: https://github.com/GoogleCloudPlatform/kubernetes/issues/147#issuecomment-76504724

I wouldn't characterize the tiers as "batch" and "production". 

The tier with no resource limits nor requests specified I consider "best effort". The degree to which we oversubscribe resources for best-effort workloads is TBD, and we'll probably want it to be parameterizable. In the absence of resource-usage information, that's a non-issue, however.

The top tier, with limits fully specified, could be called exactly that "top tier".

Until we implement "request", there's no middle tier.

I don't think we should get into per-resource QoS, as we do in lmctfy and Borg, for now.

I'm opposed to preemption by numerical priorities specified by users. I think we should punt on preemption in general, for now.

However, we could kill selected best-effort victims when a node runs out of resources in order to preserve QoS for other containers/pods.

**Comment by AnanyaKumar** [comment]
Thanks for the details! I'm drafting a proposal right now, and I'll work on it with @rjnagal and @vmarmol and then I'll send it out to you. I'll change the names according to what you suggest.

I plan to treat pods without limits as best effort jobs, and pods with limits as top tier jobs. Best effort pods will be invisible to top tier jobs, and should not affect top tier pods in either admission or resource usage. This means that I will kill best-effort pods to make room for top tier pods. Additionally, CPU limits of best-effort pods will not be guaranteed - top tier pods are allowed to starve best-effort pods of CPU time. So I'll be putting them best-effort pods into an cgroup with minimum CPU shares.

I've just started working on this, so if you have any suggestions, please let me know.

**Comment by nelcy** [comment]
+1 for implementing QOS tiers in Kubernetes. Would love to take part in adding support for it.

@bgrant0607 @erictune 

Thinking more, typing "best-effort" to limits, would not work for some scenarios.

Lets say user wants to define two apps
- A top-tier web app with requested resources and no limit
- A best-effort tier batch job with minimum requested resources and no limit

At run time, we want the top-tier web app to get idle resources as long as it needs it. Best-effort will only get to use idle resources if none of the top-tier apps are using it. 
If we opt to put a limit on web app, then we are actually capping the performance of web app even when the system is idle.

Let me know your thoughts..

**Comment by AnanyaKumar** [comment]
@nelcy I agree with you. There seems to be a very strong argument for "best-effort"/"top-tier" to be orthogonal to whether limits are specified. I'm thinking of implementing it like this:

Top-tier (mostly unchanged):
- CPU: Unspecified CPU limits -> minimum CPU priority
            CPU limits specified -> give the user the CPU resources she requested
- Memory: Best-effort pods will be "invisible" to top-tier pods. Best-effort pods will be evicted to make room for top-tier pods, and will be killed if top-tier pods request for more memory. So top-tier pods will be given an OOM score < 0.

Best-effort:
- CPU: Specified limits will be ignored, best-effort pods will be given minimum CPU priority. They can use CPU resources not consumed by other pods.
- Memory: Any specified limits will be enforced, but limits will not be guaranteed. In particular, if other top -tier pods need more memory, best-effort pods will be evicted. So best-effort pods will be given an OOM score > 0.

Within each tier, I'm thinking of distinguishing pods that specify memory limits vs. pods that do not specify memory limits. I'm worried about pods that don't specify limits taking up an excessive amount of memory and forcing out pods in the same tier. I think we should give pods that specify memory limits a lower OOM score than pods that don't (within the same tier), so pods that don't specify memory limits get evicted first. What do you think?

Also, for now, I intend to label pods without any specified limits to be best-effort. Eventually, I'm guessing we'll change the pod specification in the API so that users can specify whether pods are best-effort/top-tier, and then we can remove this default "best-effort" assignment. Does this seem reasonable?

Please let me know what you think, if there are issues with the design I'm proposing, or if you have other ideas! I'll work on it with @vmarmol @rjnagal and put up an updated plan later. Thanks!

**Comment by AnanyaKumar** [comment]
The proposal above is slightly different from what @bgrant0607 suggested, particularly in the way memory is handled. 

An alternative is that we could put all best-effort pods into a parent cgroup, and restrict the memory of the parent cgroup based on resource limits specified by the top-tier pods. This alternative would reduce the chance of a best-effort job being OOM killed, would reduce utilization. In my proposal, best-effort pods will be allowed to "eat" into top-tier pods' memory, but will be OOM killed if top-tier pods needs the memory they reserved. Also, I think dynamically changing the parent cgroup's memory limit (based on resource limits specified by top-tier pods) is messier. I think this is closer to what Brian proposed.

If anyone thinks the alternative sounds better, or if there's some other design that's better, please let me know!

**Comment by nelcy** [comment]
Thanks Ananya for giving more insight.

This is my understanding. Please feel free to correct me.

For Memory or any other incompressible resources
 1. Requested is always guaranteed for both top-tier & best-effort
 2. If a top-tier is under its limit and needs more resources it will kill the best-effort tier pod which is consuming more than requested
 3. Between pods of the same tier, pods with limits take more precedence, than the pods with out any limits.

For compressible resources,
In points 2 & 3, pod won't be killed but throttled.

One more question, in the current resource model there is no over-commitment. Will we be relaxing it with this proposal?

**Comment by AnanyaKumar** [comment]
To clarify, this is a very preliminary proposal that I'm drafting - I wanted to get some feedback. I'll update after syncing with more experienced people :)

From what I understand, we don't support requests right now, we only support limits (basically request == limits). Limits will be guaranteed for top-tier pods and won't be guaranteed for best-effort pods. There will be over-commitment in the new model, however over-commitment will be invisible to top-tier pods that specify limits.

Points 2 and 3 that you mention are in line with what I'm proposing, but I expect 3 might be controversial for incompressible resources. However, I don't see a better way to do this unless we preempt with numerical priorities (which Brian seems opposed to).

**Comment by nelcy** [comment]
Sounds good. Will wait for the proposal.

**Comment by bgrant0607** [comment]
Proposal is in #11713.

**Comment by bgrant0607** [comment]
Note that this issue is about performance/resource QoS, NOT availability/reliability/disruption QoS. They are related, but not necessarily coupled.

**Comment by erictune** [comment]
@nelcy @AnanyaKumar 
I agree it should be possible to handle the scenario that @nelcy describes.

However, I don't think it is necessary to introduce tiers/priority as a first-class to handle the @nelcy mentions.  You could also handle that scenario using vertical pod autoscaling.

With vertical pod autoscaling, you initially create a pod with some request and limit, and then a control loop periodically looks at each pod which is it supposed to manage, and decides whether to increase, decrease, or leave alone the request and limit of the pod.  A typical vertical autoscaling policy would be to look at historical usage, take, say, the 95%ile, and add some padding to that, and call that the new request and limit.  

The case @nelcy mentions could be implemented with the following autoscaling rule:
 - if pod has label `type=web` then try to increase limit and request by 10%
 - keep doing this until all pods with `type=web` have consumed all free resources on the nodes they occupy.  

I think it is better to keep the kubelet's and scheduler's view of resources as simple as possible, and to layer more complex policies as control systems on top of those.  This approach has several advantages:
- it keeps the complexity of scheduler and kubelet manageable.
- with less policy in kubelet, it is able to work well on a wider variety of kernels/platforms.
- If we hardcode tiers/priorities into a place in pod spec that everyone uses, it is going to be difficult to evolve, because any change will affect all kubernetes users when they try to upgrade kubelet and/or scheduler.  
- However, if priorities/tiers are expressed via labels or annotations, or custom fields in the pod spec, then those can evolve separately.  Different clusters can have different definitions of tiers.  I am certain different people will want different, incompatible, types of tiers.

**Comment by nelcy** [comment]
@AnanyaKumar
Thanks for the proposal. We included burstable pods and that should cover the use case I was concerned about. I will spend some more time and send you review comments if any. First look, the proposal is very good.

@erictune I like the idea of control loop on top, but it doesn't always give us a completely elastic behavior. in my previous experiences, with control loop it was always a debate about how frequently you run the control loop especially for compressible resources. But I agree it has several advantages and gives us greater flexibility. For now, I am happy with support for Burstable pods. Thanks.

**Comment by bgrant0607** [comment]
Superseded by more recent issues.

**Comment by rafis** [comment]
> Superseded by more recent issues.

Kubernetes v1.12.7. Problem still exists. Pods are randomly dying. I call it "Happy New Year Tree" effect in Kubernetes cluster. Which recent issue I shoud look?
