### ISSUE TITLE
Handle containerized hyperkube shutdown

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubernetes#14749]
I've followed your docker-multinode guide and it´s running fine now on a Raspberry Pi 2.

I´m using `systemd` to start up the master and worker main kubelet containers. 

When the master is up, and I run `systemctl stop k8s-master` which will stop the `kubelet` container, it stops as it should.

**But**, the other master processes keeps running...
How should one stop these easily?
This information should be present in the docker-multinode guide.

```
CONTAINER ID        IMAGE               COMMAND                CREATED             STATUS              PORTS               NAMES
bf4bbd6d507b        k8s/hyperkube       "/hyperkube apiserve   27 seconds ago      Up 26 seconds                           k8s_apiserver.41e0fcc1_k8s-master-192.168.1.59_default_a672ad2778b4243e3b9409b108a7d79c_d3948071
24e22e8b788e        k8s/hyperkube       "/hyperkube controll   28 seconds ago      Up 27 seconds                           k8s_controller-manager.8d83e451_k8s-master-192.168.1.59_default_a672ad2778b4243e3b9409b108a7d79c_8f666b27
81e80f2ca820        k8s/hyperkube       "/hyperkube schedule   29 seconds ago      Up 27 seconds                           k8s_scheduler.5d0ddd37_k8s-master-192.168.1.59_default_a672ad2778b4243e3b9409b108a7d79c_7543cfc3
50a835f33032        k8s/pause           "/pause"               38 seconds ago      Up 37 seconds                           k8s_POD.c7c0bdfa_k8s-master-192.168.1.59_default_a672ad2778b4243e3b9409b108a7d79c_1c2d92d6
```

**Comment by fabioy** [comment]
Please re-post your question to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes). 

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases. 

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to similar questions, and also familiarize yourself with:
  * [the user guide](http://kubernetes.io/v1.0/)
  * [the troubleshooting guide](http://kubernetes.io/v1.0/docs/troubleshooting.html)

Again, thanks for using Kubernetes.

The Kubernetes Team
