### ISSUE TITLE
kubernetes/server/bin/hyperkube: Wrote only 512 of 10240 bytes

### ISSUE THREAD

**Issue by aanm** [kubernetes/kubernetes#14743]
I'm getting an error while running the `cluster/kube-up.sh` with
```
export KUBERNETES_PROVIDER=vagrant
export VAGRANT_DEFAULT_PROVIDER=virtualbox
export NUM_MINIONS=1
```
error:
```
==> master: ‘/srv/salt-overlay/salt/kube-apiserver/basic_auth.csv’ -> ‘/srv/salt-new/salt/kube-apiserver/basic_auth.csv’
==> master: ‘/srv/salt-overlay/pillar/cluster-params.sls’ -> ‘/srv/salt-new/pillar/cluster-params.sls’
==> master: +++ Install binaries from tar: kubernetes-server-linux-amd64.tar.gz
==> master: tar: kubernetes/server/bin/hyperkube: Wrote only 512 of 10240 bytes
==> master: tar: Exiting with failure status due to previous errors
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```
am I missing something?

**Comment by fabioy** [comment]
Vagrant support is done by the community. Unfortunately, I can't test this combo since it doesn't seem to work with the latest VirtualBox (5.0). My apologies.

**Comment by snrism** [comment]
@aanm I faced similar issue, but resolved it by providing more memory to each VM (master & minions). In Vagrantfile line 107 and 108 you can notice that the default memory is 1024, if you dont set the KUBERNETES_MEMORY (or specific VM) env variable. When I updated the default value to 2048, the vagrant setup was successful.

**Comment by roberthbailey** [comment]
@aanm I'm going to close this as resolved since @snrism provided some guidance and there haven't been any recent updates. 

In the future, please post support questions to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes), as we are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases.
