### ISSUE TITLE
AWS EBS Timeout waiting for volume state 

### ISSUE THREAD

**Issue by delta440** [kubernetes/kubernetes#14759]
If I create this pod:

apiVersion: v1
kind: Pod
metadata:
  name: dsm-manager
spec:
  containers:
    - name: dsm-manager
      image: ******
      imagePullPolicy: Always
      command:
        -  /sbin/init
      volumeMounts:
        - mountPath: /srv/project/DSMManager/snapshots
          name: dsm-snapshot-storage
  volumes:
    - name: dsm-snapshot-storage
      awsElasticBlockStore:
        volumeID: aws://us-west-2b/vol-43e44482
        fsType: ext4
  imagePullSecrets:
          - name: dockerregistrykey

It always works, but if I delete it and re-create it it gets stuck with status 'CreatingContainer'. Looking in the events yields:
-Unable to mount volumes for pod "dsm-manager_default": Timeout waiting for volume state 
-Error syncing pod, skipping: Timeout waiting for volume state 

If I delete the pod and re-create it the same thing happens no matter what I do. However if I attach the volume to some instance and then detach it through the aws cli, then create the pod it works find. I'm wondering if the volume isn't being detached properly. For now I just have this odd work flow of attaching the volume to a random instance then detaching it while updating the container image

**Comment by fabioy** [comment]
Please re-post your question to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes). 

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases. 

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to similar questions, and also familiarize yourself with:
  * [the user guide](http://kubernetes.io/v1.0/)
  * [the troubleshooting guide](http://kubernetes.io/v1.0/docs/troubleshooting.html)

Again, thanks for using Kubernetes.

The Kubernetes Team

**Comment by delta440** [comment]
Okay, thanks. You should put that under the guidelines for contributing under Filing Issues (https://github.com/kubernetes/kubernetes/blob/master/CONTRIBUTING.md#filing-issues), if it were there I would have posted directly to StackOverflow.
