### ISSUE TITLE
Certain container labels only set when Lifecycle and PreStop are set

### ISSUE THREAD

**Issue by philk** [kubernetes/kubernetes#14768]
I noticed that some of our containers actually had docker labels for `io.kubernetes.container.name` and `io.kubernetes.pod.data` but most didn't. The `io.kubernetes.container.name` is actually a nice label since it gives us an easy way in our monitoring (which doesn't support k8s labels) to see all containers of a certain type (all AppX or AppY). I [looked up the code](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockertools/manager.go#L677) for it and those labels only get set if the pod has Lifecycle events.

For us at least it would be useful if we could use these labels. It also just seems more consistent for pods to get the same docker labels rather than just on pods with Lifecycle events and I can't readily think of a downside.

**Comment by yujuhong** [comment]
@philk, we are actually going to do a docker label overhaul in kubelet. See #15089 for the details. This would give every container proper name and namespace labels, along with other new labels (restart count, etc). I think that should meet your needs.

`io.kubernetes.pod.data` is kind of an odd label since I don't think we should dump the entire pod spec into the label. @brendandburns, you added this label and there is a [TODO comment for fixing this]( https://github.com/kubernetes/kubernetes/blob/1d352a16b8e766eabe7ab75ebddc43f07a6fcdd0/pkg/kubelet/dockertools/manager.go#L722). Do you plan to work on it and do you have any ideas in mind on how to fix this? @Random-Liu is working on #15089, he may take on this as well.

Also cc @dchen1107 since we discussed about this the other day.

**Comment by Random-Liu** [comment]
If possible, I'm very happy to take on this, :)

**Comment by yujuhong** [comment]
I believe we have consistent labels on all containers now, if that still matters :-)
