### ISSUE TITLE
Ability to specify NFS version?

### ISSUE THREAD

**Issue by esecules** [kubernetes/kubernetes#14779]
I'm trying to mount a volume using NFS to a server running NFS version 4, and after successfully mounting and attaching the volume to the container, I try to execute this command (as root): 
```
# chown -R redis /data
chown: changing ownership of `/data': Invalid argument
```
I've been able to reproduce this manually. 
I can fix it by adding the flags  ```-t nfs -o vers=3,nolock``` to my mount command
Is there a way to specify that I want to use NFS v3 instead of the latest available on the file server?

**Comment by fabioy** [comment]
Please re-post your question to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes). 

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases. 

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to similar questions, and also familiarize yourself with:
  * [the user guide](http://kubernetes.io/v1.0/)
  * [the troubleshooting guide](http://kubernetes.io/v1.0/docs/troubleshooting.html)

Again, thanks for using Kubernetes.

The Kubernetes Team
