### ISSUE TITLE
Enable experimental APIs by default

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#14799]
We've been discussing how to make experimental features available to users. The experimental APIs are currently disabled by default, but are enabled in increasingly many situations: e2e, vagrant (#14507), GKE, ...

RFC: Enable experimental by default. 

We'll need to figure out how to deal with potential future incompatible changes. If we need to make breaking changes to experimental APIs (which is part of the point of experimental), we'll need to delete affected experimental resources before upgrade. That mostly affects 1.2 rather than 1.1.

At minimum, there will be an API version treadmill of configs and storage version to get to stable APIs: experimental -> alpha -> beta -> v1. In order to advance in this progression, we need user feedback on the APIs, ideally more frequently than one step every 3 months.

cc @roberthbailey @alex-mohr @brendandburns @thockin @lavalamp @davidopp @mikedanese @nikhiljindal @erictune @bprashanth @jszczepkowski

**Comment by roberthbailey** [comment]
(I've been meaning to file an issue about this, but I supposed it can be part of this discussion)

I'm not as concerned with giving users access to the experimental APIs as making sure users are clearly aware that they are using a feature that is still considered experimental. For example, if we say that the daemon controller is part of the experimental API and thus may break in the future, many users will just run `kubectl create -f dc.yaml` and may not realize that they are using an experimental feature. Sure, the yaml file will say 'Experimental' in it, but users will just copy/paste an example yaml from a blog post or shared repository and not realize that they are building on an unstable foundation. 

I'd like to see a change to kubectl so that you need to pass a flag to force it to use an experimental api endpoint (e.g. `--enable-experimental-apis`). We should also clearly document (as part of the release notes and in the kubectl help text for this flag) that any objects created using the experimental API will not survive upgrades.

**Comment by derekwaynecarr** [comment]
Is it that experimental objects WILL NOT survive upgrades or MAY NOT
survive upgrades.  I actually think it's in our interest to support
experimental -> alpha -> beta -> v1 migrations if possible to attempt to be
as pro-user as possible.  I also think we need to think carefully here.  We
are telling users that the Job, DaemonSet, HorizontalPodAutoscalers they
create may not survive upgrades with no clear statement on what they should
or should not do about the then orphaned pods those objects spawn.

I don't think I want a flag in kubectl.  Right now experimental is an API
group with a special name.

I think experimental should be on by default otherwise it discourages
experimentation.  Operators that want to discourage experimentation should
choose to turn it off.

**Comment by davidopp** [comment]
I thought that if you used an alpha API version you might have to wipe your whole cluster. But maybe I am mis-remembering.

https://github.com/kubernetes/kubernetes/blob/master/docs/devel/api_changes.md
talks about backward compatibility but wasn't completely clear (to me, at least) on what happens from the end-user perspective when an incompatible change is made.

**Comment by jszczepkowski** [comment]
> I thought that if you used an alpha API version you might have to wipe your whole cluster. But maybe I am mis-remembering.

I agree with @davidopp, My assumption was that API for Horizontal Pod Autoscaler does not give any compatibility guarantees for now (as it is experimental).

**Comment by zmerlynn** [comment]
I personally think we need to elevate any of the APIs we want to advertise for 1.1 into stable group, or we're just not trying hard enough. If we don't, the 1.1 -> 1.2 experience is just going to be *horrible*.

**Comment by alex-mohr** [comment]
Are each of those 3 things ready for production use and we're just not sure if the API is perfect yet?

For those that are, it seems like it'd be a poor experience to require users to delete and re-create those objects when upgrading from 1.1 to 1.2, so we should explicitly support that as an upgrade step.

It also seems reasonable that clients using v1.1 servers should continue to work when those servers are upgraded to v1.2.  That would argue for promoting those objects to the v1 API group for the v1.1 release.

And if we've gotten the API so horrendously wrong that we need to change it in a non-backwards-compatible way, then we can do it as part of a new API version (APIv2 or APIv1.2).

The whole point of having versioned APIs is to ensure good user experiences, and having to increment our API version when the benefits justify it seems a better place than an unversioned-but-changeable API.

**Comment by alex-mohr** [comment]
Also, +1 to kubectl needing a flag to explicitly acknowledge that a command is targeting api.experimental w/o backwards compat.  Failing that, min bar is to log-spew warnings.  Neither of those is great for things we expect wide usage of, though, thus my suggestion to push such features into v1.

**Comment by derekwaynecarr** [comment]
@smarterclayton @kubernetes/rh-infra

**Comment by roberthbailey** [comment]
@bgrant0607 and I talked about this a bit more, and he mentioned that he knows of at least one case where we *do* know that we've gotten the apis wrong (how they implement label selectors) which needs to be fixed before they can be promoted to the v1 API. 

One possible solution we discussed would be to rename the experimental API group to something like `experimental1.1`. Then when you release 1.2 you could have an `experimental1.2` API group which could have objects of the name name but without backwards compatibility (if necessary). Some objects could be promoted to alpha/beta API groups or event into the v1 API. Some might disappear (failed experiment). We wouldn't want to remove the `experimental1.1` API group in 1.2 because we'd give users time to migrate their resources out of the group before it gets taken away. But in 1.3 we could remove the `experimental1.1` API group having given users ~3 months to migrate their deprecated objects.

**Comment by bgrant0607** [comment]
Another thing I like about the approach suggested by @roberthbailey is that it will force us to not leave stuff in experimental forever.

**Comment by bgrant0607** [comment]
None of the experimental APIs are ready to move out of experimental and we KNOW we need to make breaking changes to most of them.

**Comment by bgrant0607** [comment]
The kubectl firewall warnings were a nightmare, IMO. Let's not repeat that.

**Comment by derekwaynecarr** [comment]
Is there an issue that elaborates on what is wrong with label selectors in
experimental?

**Comment by bgrant0607** [comment]
Summary:
* Enable experimental APIs by default
* Rename experimental to experimental-1.1
* No printed warnings

**Comment by bgrant0607** [comment]
Label selector: https://github.com/kubernetes/kubernetes/issues/341#issuecomment-140809259

**Comment by smarterclayton** [comment]
I'll admit I'm somewhat concerned with the sheer amount of work involved in
the experimental groups and versions (and their proliferation into versions
and sub versions).  As a client consumer of the experimental API, I might
be appreciative, but do we have evidence that a substantial number of end
users benefit from the stability we are providing?  I can perhaps buy an
argument that we are doing work that will benefit us later, but I'm also
wondering how much people will wade through on our side (to enable the many
different conversions and versions) and on the consumer side (to leverage
something that isn't even very well baked).

My counter proposal would be
* Enable experiment by default
* have an experimental group version that is the "nursery", where things
change without warning (I would have just called this an experimental API
version prior to groups) - call it v1
* when we want to graduate versions, move them to v2 in experimental and up
- when they are ready, move them to another group.
* warn on server startup and that's it.

experimental-1.1/v1alpha1 seems a lot more complex and excessive than
experimental/v1, v2, etc


On Oct 1, 2015, at 3:27 AM, Brian Grant <notifications@github.com> wrote:

Summary:

   - Enable experimental APIs by default
   - Rename experimental to experimental-1.1
   - No printed warnings

—
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/14799#issuecomment-144589985>
.

**Comment by lavalamp** [comment]
We should use versions within a group for that, not new groups. so
experimental/v1.1, experimental/v1.2, etc.

**Comment by bgrant0607** [comment]
@lavalamp The reason to change groups is so that conversion would not be required/expected.

**Comment by bgrant0607** [comment]
Scenario we're concerned about: Someone starts using an experimental API. Their cluster is auto-upgraded to a new version with a non-backward-compatible API, not just naming-wise, which conversion handles fine, but semantically. Another alternative we discussed is changing resource name when semantic compatibility is not possible: Foo1, Foo2, Foo3.

**Comment by smarterclayton** [comment]
An experimental API that has long term support seems to violate the intent
of experimentation.  I'd be worried we're placing a huge burden on
ourselves and we'd be better off spending that time adding and evolving
features.  Semantic compatibility for core behavior hasn't been a huge
problem yet (except label selectors) and we can even design our way out of
that.

On Oct 1, 2015, at 8:11 PM, Brian Grant <notifications@github.com> wrote:

Scenario we're concerned about: Someone starts using an experimental API.
Their cluster is auto-upgraded to a new version with a
non-backward-compatible API, not just naming-wise, which conversion handles
fine, but semantically. Another alternative we discussed is changing
resource name when semantic compatibility is not possible: Foo1, Foo2, Foo3.

—
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/14799#issuecomment-144804215>
.

**Comment by bgrant0607** [comment]
Outcome of discussion:
* Stick with one experimental API group and enable it by default
* Require specification of experimental group in kubectl: e.g., experimental/deployment
* Print warning in kubectl (thank you very much for trying this out, but be aware that ...)
* Auto-delete experimental resources on upgrade

**Comment by bgrant0607** [comment]
So, yes, we agree that we need to retain the ability to break compatibility and iterate. We're just debating abiyt an approach that would be least surprising to users.

**Comment by derekwaynecarr** [comment]
>>Auto delete experimental resources on upgrade

Does that include any cascaded resources it created or managed?  e.g pods /
services / RC ?  If not, is that making it harder or easier for users?

**Comment by bgrant0607** [comment]
Cascading SGTM

**Comment by jszczepkowski** [comment]
> Cascading SGTM

So, I guess we will need a spacial code that will delete all the resources from etcd during upgrade. Any ideas what will trigger the deletion?

**Comment by mikedanese** [comment]
I don't think cascading would be right. If i have a daemonset running and my master upgrades (at a time I can't control) I would prefer if I had a chance to recreate the daemonset before the daemon pods get terminated.

**Comment by lavalamp** [comment]
Cascading pros:
* deletes resources that might otherwise be hard to track down and manually delete once orphaned.
Cons:
* No mechanism yet (someone has to do work)
* would delete things we'd prefer to just orphan

That one is a coin flip for me.

@JanetKuo take a look at @bgrant0607's comment above: https://github.com/kubernetes/kubernetes/issues/14799#issuecomment-144870203

**Comment by smarterclayton** [comment]
Deleting things because an API resource went away seems riskier than simply
explaining how someone can clean up.

On Oct 2, 2015, at 1:11 PM, Daniel Smith <notifications@github.com> wrote:

Cascading pros:

   - deletes resources that might otherwise be hard to track down and
   manually delete once orphaned. Cons:
   - No mechanism yet (someone has to do work)
   - would delete things we'd prefer to just orphan

That one is a coin flip for me.

@JanetKuo <https://github.com/JanetKuo> take a look at @bgrant0607
<https://github.com/bgrant0607>'s comment above: #14799 (comment)
<https://github.com/kubernetes/kubernetes/issues/14799#issuecomment-144870203>

—
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/14799#issuecomment-145088451>
.

**Comment by bgrant0607** [comment]
@smarterclayton How would someone clean up manually? Use etcdctl to cull orphaned keys?

**Comment by bprashanth** [comment]
> Deleting things because an API resource went away seems riskier than simply explaining how someone can clean up.

This is the same for loadbalancers. you don't want to tear them down because the Ingress resources has disappeared. The way I'm currently solving this is with a /quit endpoint on the loadbalancer controller pod. If the pod dies, the resources are left as is (eg: this could be other pods serving traffic or gce forwarding rules etc), the resources are only deleted if the Ingress is deleted. If the Ingress has gone away, users can cleanup by starting a new loadbalancer controller pod and hitting /quit.

**Comment by smarterclayton** [comment]
Yeah, recursive delete.  Won't help with off cluster resources (like
external loadbalancer), but it's fairly easy to add to release notes and
doc if we did drop a resource:

34. The experimental resource Elephant has been renamed to Horse, but no
migration is available.  You can remove unsupported resources of type
Elephant through the etcdctl command line:

    etcdctl delete -R /kubernetes.io/elephants

Note: you may wish to preserve a copy of elephants for reference via ...


On Oct 2, 2015, at 5:41 PM, Brian Grant <notifications@github.com> wrote:

@smarterclayton <https://github.com/smarterclayton> How would someone clean
up manually? Use etcdctl to cull orphaned keys?

—
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/14799#issuecomment-145161549>
.

**Comment by davidopp** [comment]
+1 to not doing cascading. I think in the long-term there could be arbitrary entanglement between objects (not as simple as just a controller and the Pods it created) and you could end up having to delete a lot of stuff if you did cascading.

**Comment by nikhiljindal** [comment]
> So, I guess we will need a spacial code that will delete all the resources from etcd during upgrade. Any ideas what will trigger the deletion?

We have https://github.com/kubernetes/kubernetes/blob/master/cluster/update-storage-objects.sh to update etcd objects while upgrading the cluster to a different API version (for ex: we used it while upgrading clusters from v1beta3 to v1). We can extend that.

**Comment by bgrant0607** [comment]
After a lot of discussion, we have decided not to enable experimental by default, due to impact on SLAs, support, upgrades, perception of quality level, etc. 

Once we have a general-purpose GC controller, deletion, cascading or otherwise, will be more straightforward.
