### ISSUE TITLE
Resource Requests Default Value

### ISSUE THREAD

**Issue by wangzhezhe** [kubernetes/kubernetes#14817]
It seems that the Resource Requests of the containers have  default value when a pod is created without Resources fields setting in json config file . But what's the default value and where do they set ? Thank you!

**Comment by derekwaynecarr** [comment]
This is being set by the default limit range in your namespace.

```
$ kubectl describe limits limits
```

For more information on Limit Range and default resource assignment see:
https://github.com/kubernetes/kubernetes/blob/master/docs/design/admission_control_limit_range.md

Since you did not specify a particular version of Kubernetes, pointed you to the design.

The documentation for this on latest code stream is being updated here:
https://github.com/kubernetes/kubernetes/pull/13724
