### ISSUE TITLE
skydns/kube2sky problem with multi api servers (failover via pacemaker)

### ISSUE THREAD

**Issue by rnagarajan12** [kubernetes/kubernetes#14818]
Hello,

I have  kubernetes cluster with 2 master both acting as master and slave.
2 servers are set up failover in mind and pacemaker doing the stuff with one virtual IP,
The cluster is fully operational except service discovery.

The service discovery  only works when skydns runs on server where virtual IP is attached (meaning current master)  and containers running on the same machine with skydns can resolve services without problem.
But containers running on other node(2nd server) cannot resolve any services even local cluster domain name.

I have verified etcd has all records, but some how getting/sending back the response to end machine is the problem

kubernetes version 1.0.6
kube2sky:1.11
skynetservices/skydns

Virtual IP is attached to node1

kubectl get po -o wide  --namespace=kube-system
NAME                                 READY     STATUS    RESTARTS   AGE       NODE
k8s-dns-v8-a1qmo                     4/4       Running   0          20h       node1
monitoring-heapster-v8-gf8gn         1/1       Running   1          22h  node1
monitoring-influx-grafana-v1-zclxv   2/2       Running   0          22h node1

kubectl get po -o wide 
NAME              READY     STATUS    RESTARTS   AGE       NODE
busybox           1/1       Running   1          21h       node2
nginx-web-o55db   1/1       Running   0          22h       node2
test-t4w90        1/1       Running   0          20h       node2

Skydns running on node1,

kubectl exec monitoring-heapster-v8-gf8gn --namespace=kube-system -- nslookup test-svc.default
Server:    10.0.0.10
Address 1: 10.0.0.10

Name:      test-svc.default
Address 1: 10.254.1.2

kubectl exec monitoring-heapster-v8-gf8gn --namespace=kube-system -- cat /etc/resolv.conf 
nameserver 10.0.0.10
nameserver host DNS
search kube-system.svc.cluster.local svc.cluster.local cluster.local
options ndots:5

kubectl exec monitoring-heapster-v8-gf8gn --namespace=kube-system -- nslookup nginx-svc
nslookup: can't resolve 'nginx-svc'
Server:    10.0.0.10
Address 1: 10.0.0.10

error: Error executing remote command: Error executing command in container: Error executing in Docker Container: 1

kubectl exec busybox -- nslookup cluster.local
nslookup: can't resolve 'cluster.local'
Server:    10.0.0.10
Address 1: 10.0.0.10

error: Error executing remote command: Error executing command in container: Error executing in Docker Container: 1
kubectl exec busybox -- cat /etc/resolv.conf 
nameserver 10.0.0.10
nameserver host DNS
search default.svc.cluster.local svc.cluster.local cluster.local
options ndots:5

**Comment by cjcullen** [comment]
Please re-post your question to stackoverflow.

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases.

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to similar questions, and also familiarize yourself with:

the user guide
the troubleshooting guide
Again, thanks for using Kubernetes.

The Kubernetes Team
