### ISSUE TITLE
kubectl unable Unable to upgrade connection

### ISSUE THREAD

**Issue by luedigernet** [kubernetes/kubernetes#14829]
I'm facing the problem that kubectl exec is not working properly

the following command does not work

./kubectl exec --server="http://my_fqdn:8080" busybox echo "Hello world"
error: Unable to upgrade connection: {
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "the server does not allow this method on the requested resource",
  "reason": "MethodNotAllowed",
  "details": {},
  "code": 405
}

while the   following one works well 

kubectl --server="http://my_fqdn:8080" get pods
NAME                                         READY     STATUS       RESTARTS   AGE
busybox                                      1/1       Running      1          35d
.......
.......

I've found the older issue  https://github.com/kubernetes/kubernetes/issues/6343 which points to some old nginx,  but we are not running a nginx.

best regards reinhard

**Comment by ncdc** [comment]
@luedigernet I'm wondering if your version of kubectl is trying to issue a GET request for exec. I believe we originally did it that way, but have since changed to only allowing POST. (Note, we will be returning to allow GET again in the future to support exec via websockets).

Could you please provide the output of `kubectl version` and also the output when you try your exec with `--v=9`?

**Comment by luedigernet** [comment]
@ncdc Thanks for your support. meanwhile I found the real root cause for my issue. But i had to wait until todays morning for confirmation by my clients before closing the issue here.
The root cause was that our internal repository (used for software installation) was completely messed up with some very old binaries in the wrong place. All kubernets server binaries where from release v0.19.3 by mistake.

Sorry for opening such issue it was just my mistake.
