### ISSUE TITLE
No external IP after starting guestbook-go from Kubernetes examples

### ISSUE THREAD

**Issue by nelsonad77** [kubernetes/kubernetes#14875]
After starting a Kubernetes cluster within Vagrant, either single or multi-node on a mac, or starting a full deployment on ubuntu 14.04, I try to deploy the examples/guestbook-go controllers and services. I can never see an external IP assigned and identified from 'kubectl get services'
<img width="632" alt="screen shot 2015-09-30 at 2 50 45 pm" src="https://cloud.githubusercontent.com/assets/6738518/10206328/8f7e1bdc-6783-11e5-99b4-2d30296d9356.png">
I followed all of the directions from here: http://kubernetes.io/v1.0/docs/getting-started-guides/locally.html
Any idea why I would not see a local IP under any conditions?

**Comment by cjcullen** [comment]
Please re-post your question to stackoverflow.

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases.

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to similar questions, and also familiarize yourself with:

the user guide
the troubleshooting guide
Again, thanks for using Kubernetes.

The Kubernetes Team
