### ISSUE TITLE
Extend Persistent Volume Claims to select on labels

### ISSUE THREAD

**Issue by tobad357** [kubernetes/kubernetes#14908]
We are currently evaluating using a large number of volumes with different characteristics for different apps. These volumes could as an example be ssd vs hd, different snapshot policies, different replication strategies etc. These volumes are then intended for different usage. Webserver vs Database

What I would like is to extend the claim to have a selector and then use that selector against the persistent volumes labels. This would be inline with how Services selects pods.

If this is an acceptable solution I would be happy to see if I can implement it.

**Comment by davidopp** [comment]
@thockin @kubernetes/rh-storage

**Comment by markturansky** [comment]
@tobad357 Thanks for the suggestion.

Users definitely need better ways to select PVs.  The approach we're currently implementing is additional "quality of service" annotations on a claim that are used by the various PV components (binder, provisioner, etc).

The goal is to allow easy customization of the components via config so that you have your snapshot policies, ssd v. hd volumes, etc.

**Comment by tobad357** [comment]
@markturansky 
So this is in the works already? and if it is, any issue number I can follow?
Sorry if off topic
And additionally in the new implementation is there any work for a claim to claim X number of PV's where X is the amount of replicas in a replication controller. This would be needed for non shared storage, such as iSCSI where each replica should have their own volume (clustered DB server, Cassandra, Zookeeper)

**Comment by markturansky** [comment]
See https://github.com/kubernetes/kubernetes/issues/260 for more discussion about each RC replica getting a distinct PV.  

I'm starting with QoS tiers for provisioning, but I realize now how I have to make all pieces pluggable so that admin can customize all of this behavior.  
https://github.com/kubernetes/kubernetes/pull/14537

**Comment by pmorie** [comment]
@kubernetes/rh-storage

**Comment by bgrant0607** [comment]
I could maybe imagine a volumeSelector as an escape hatch, similar to nodeSelector. If we do that, we should use the new-style selector we used for Job.

**Comment by thockin** [comment]
I think in the longer term we can do better than this, but I am not against
this.

**Comment by wkruse** [comment]
@tobad357 Seems like it is solved [Persistent Volume > Persistent Volume Claims > Selector](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#selector)

**Comment by tobad357** [comment]
Yes it is, will close it
