### ISSUE TITLE
Need an API documentation audit

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#14924]
Looking at the docs, many fields and structs are under-specified.  At some point (soon) we need to do an audit/scrub of API per-field and per-struct comments (which generate docs).
- What is this field?
- Is this field required?  (omitempty is sort of a bad way IMO)
- What happens if this field is not specified?
- What are valid values or bounds for this field?
- What happens if you specify an out-of-bounds value?
- Does this field have a literal default value (e.g. 42), a derived default value (e.g. same as another field), or no default value (the system will choose a value)?
- Is this field updateable?  What happens if you update it?

**Comment by bgrant0607** [comment]
We also need to standardize the form of the documentation: complete sentences vs. not, etc.

Since the type and field documentation is extracted, exported via swagger, and converted to user documentation, none of it should be in terms of Go field names nor types. As discussed in [another PR](https://github.com/kubernetes/kubernetes/pull/15350#discussion_r41797383), we should convert to json field names and plain english when describing types, or omit those names entirely, as we do for, say, the container image: https://github.com/kubernetes/kubernetes/blob/master/pkg/api/v1/types.go#L910

As for omitempty, that is exactly how our swagger exporter determines required vs. not, and we generate the documentation with a column that specifies that, so putting it in the description is redundant. 

We also should fork the types (perhaps by generating from a single source) in cases where required vs. optional, immutability, or some aspect of the documentation differs in different use cases, such as PodSpec in a Pod vs. in a PodTemplate.

**Comment by bgrant0607** [comment]
Dupe of #11933, but we need the content in that other issue as well.

**Comment by vllry** [comment]
@thockin @deads2k @lavalamp 

This issue is super old, what is still outstanding? Would be helpful to update the issue.

**Comment by nzoueidi** [comment]
Raising this issue again, I would like to help also if there is anything needed here.

**Comment by kbbgl** [comment]
Is this still relevant? Seems that it's a duplicate of https://github.com/kubernetes/kubernetes/issues/11933 which was closed also for age.

**Comment by thockin** [comment]
Yes this still needs to be done, but this issue is not helpful. Anyone who wants to is invited to jump in and make the comment-docs better, now and forever.  This is a process not a destination.
