### ISSUE TITLE
Adjust memory overcommit on node for QoS

### ISSUE THREAD

**Issue by vishh** [kubernetes/kubernetes#14935]
With the current QoS policy, kubernetes guarantees that memory allocations will not fail up until the memory `request` specified by the user. But the nodes are usually set up to fail memory allocations based on [kernel heuristics](https://www.kernel.org/doc/Documentation/vm/overcommit-accounting), if there isn't enough memory available to satisfy the request. A *Best-Effort* container can cause malloc to fail for a *Guaranteed* container. 
To avoid this, we can change the memory overcommit policy to never fail and let the OOM killer handle real memory allocations.
Kubelet on startup will have to run `echo 1 > /proc/sys/vm/overcommit_memory`.

**Comment by derekwaynecarr** [comment]
I had been experimenting with this last week when testing node at high
memory pressures.  Agree on change.

I had planned to recommend setting it permanently via sysctl as part of
setting up the node.

Good write up is here as well:

https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/6/html/Performance_Tuning_Guide/s-memory-captun.html

**Comment by derekwaynecarr** [comment]
@vishh - I will put together a PR for this today.

**Comment by vishh** [comment]
Thanks @derekwaynecarr

**Comment by xrow** [comment]
@derekwaynecarr

We were wondering. Should we use this setting in combination with vm.panic_on_oom=1 or vm.panic_on_oom=0? 

We had issues due to this setting. We are in a situation were we had deadlocks in the database and the apache threads were piling up and consuming alle memory. Then the OOM killer came and was killing all  of the threads except the apache threads. It was picking for example on solr because it had most memory. After a while the load on that server was 300 and not responding anymore.

Is there a recommendation?

Might it be maybe better to reboot the maschine with vm.panic_on_oom=1?

**Comment by vishh** [comment]
@xrow panic on oom should be disabled. vm.panic_on_oom=0

We have user space memory eviction in v1.3. Take a look at this feature - https://github.com/kubernetes/kubernetes.github.io/pull/718
