### ISSUE TITLE
Replace client QPS limits with apiserver backpressure

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#14955]
Forked from #14554

Brought up by @smarterclayton https://github.com/kubernetes/kubernetes/issues/14554#issuecomment-143976029

We don't have concrete numbers on what QPS apiserver can support, and we also don't dynamically adjust client QPS limits based on the cluster size. Today the limit is often unnecessarily low in a smaller cluster for components such as kubelet. Leveraging the apiserver backpressure may be better in the long term. This may also make it easier to surface the performance bottleneck, when there is one.

**Comment by pmorie** [comment]
@kubernetes/rh-cluster-infra

**Comment by smarterclayton** [comment]
Our current mechanisms

1. apiserver has a filter that returns HTTP 429 with a Retry-After header (number of seconds to wait) if the apiserver has too many concurrent requests
2. Golang client respects 429 and will re-execute a request up to 10 times, waiting Retry-After seconds after each

Some suggestions:

1. Bucket the API server incoming rate filter to separate LIST ALL NAMESPACES calls from LIST NAMESPACE
2. Make the API server incoming rate filter adjust more effectively to its available capacity (if the API server can handle more load, don't arbitrarily limit it)
3. Have the API server rate limit clients / api tokens instead of being a flat bucket

**Comment by timothysc** [comment]
@yujuhong this is one of our roadmap items, please label as performance.

/cc @kubernetes/sig-scalability

**Comment by lavalamp** [comment]
@smarterclayton those suggestions sound fine to me.

**Comment by wojtek-t** [comment]
+1 for all them (but especially second point)

**Comment by jayunit100** [comment]
By **can handle more  load** ... do we mean 
... **can handle more load without slowing down average response time ?**

**Comment by smarterclayton** [comment]
However we want to define it.

Another one

4. Controller resync should be aware of total size of the cluster and
adjust accordingly (if it retrieved 10k last LIST that's substantively
different than 100 last LIST)

**Comment by bgrant0607** [comment]
see also #12208

**Comment by lavalamp** [comment]
I think this is a dup of #12208--let's keep that one since it's older.
