### ISSUE TITLE
There should be docs and user guide for security context

### ISSUE THREAD

**Issue by pmorie** [kubernetes/kubernetes#15080]
Currently there are no user-facing docs (beyond the initial design document) for security context.

**Comment by jayunit100** [comment]
- I guess I don't know what security context is because there are no docs on it :)...  
- Can someone put a pointer in the code somewhere?  I'm happy to help with this as I did add some docs on the kubeconfig.
- have learned a few things  from @liggitt around the pathway for service auth and so on that i can try to help clarify......  those notes are currently residing in [kubecfonfigfile.md](https://github.com/kubernetes/kubernetes/blob/master/docs/user-guide/kubeconfig-file.md)

**Comment by pmorie** [comment]
@jayunit100 correct

**Comment by kargakis** [comment]
/sig docs
@php-coder

**Comment by php-coder** [comment]
I think this is fixed and the documentation is there: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/

@pmorie Please, close it if you agree.
