### ISSUE TITLE
Unify resyncing in informer/controller frameworks among different controllers

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#15095]
Currently evey controller is resyncing its resources with different frequence. We should fix that in a way that:
- in production we do it very rarely (like once per hour) or even never
- in e2e tests (to test that path) we do it e.g. every 5 minutes)

The motivation of making resyncing not that frequent is performance (LISTing is just expensive)

@kubernetes/goog-csi

**Comment by wojtek-t** [comment]
I will work on it.

**Comment by ncdc** [comment]
@bparees @ironcladlou @smarterclayton @pweil- do you think OpenShift should change its controllers to sync less frequently (most of them do it every 2 minutes IIRC)?

**Comment by ironcladlou** [comment]
We should definitely consider adopting the upstream controller framework and making more copius use of `cache.Store` in the process. This also brings with it the ability to do reliable resource delete handling. For deployments, if we're going to invest any refactoring effort, it would probably be scoped only to the trigger handlers since the rest of the architecture is trying to move upstream.

Regarding resync times, we'd need to look at them on a case by case basis. I think we need shorter resync periods while we await the aforementioned refactors because we can't do efficient delete-based reconcilation logic (based on store/watches).

**Comment by smarterclayton** [comment]
I don't like that the upstream controller framework doesn't have back off
and retry outside the sync interval (or, I haven't seen it in the code).
That's something we use extensively.

On Oct 8, 2015, at 11:35 AM, Dan Mace <notifications@github.com> wrote:

We should definitely consider adopting the upstream controller framework
and making more copius use of cache.Store in the process. This also brings
with it the ability to do reliable resource delete handling. For
deployments, if we're going to invest any refactoring effort, it would
probably be scoped only to the trigger handlers since the rest of the
architecture is trying to move upstream.

Regarding resync times, we'd need to look at them on a case by case basis.
I think we need shorter resync periods while we await the aforementioned
refactors because we can't do efficient delete-based reconcilation logic
(based on store/watches).

—
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/15095#issuecomment-146581064>
.

**Comment by wojtek-t** [comment]
@smarterclayton - what do you mean by "back off and retry outside the sync interval"?

**Comment by smarterclayton** [comment]
We requeue items that have non-terminal processing errors during loop
processing and retry them (rate limited).  That means transient failures
don't have to be handled in the core loop, and we don't have to wait for
resync to retry a conflict or network error.  I hadn't seen an equivalent
feature in controllers (but I may have missed it).

On Oct 9, 2015, at 3:50 AM, Wojciech Tyczynski <notifications@github.com>
wrote:

@smarterclayton <https://github.com/smarterclayton> - what do you mean by
"back off and retry outside the sync interval"?

—
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/15095#issuecomment-146785158>
.

**Comment by bprashanth** [comment]
> We requeue items that have non-terminal processing errors during loop processing and retry them (rate limited).

I think teaching the workqueue about backoff algorithmes should get us half way there. I've wanted to do so for a while.

**Comment by smarterclayton** [comment]
We added this
https://github.com/openshift/origin/blob/master/pkg/controller/controller.go#L86
right before @lavalamp implemented the controller framework upstream - we
don't care much about the implementation, but rate-limiting failures and
errors mattered a lot us because we have a number of loops that are
structured like the endpoints controller (observe X, write Y) and so
transient errors or conflicts on that are very painful for us.

**Comment by timothysc** [comment]
@bprashanth #14955

**Comment by kargakis** [comment]
> I think teaching the workqueue about backoff algorithmes should get us half way there. I've wanted to do so for a while.

https://github.com/kubernetes/kubernetes/pull/23444

**Comment by wojtek-t** [comment]
This has already happened in the meantime (with shared informers work etc.)
