### ISSUE TITLE
Image garbage collection failed: unable to find data for container /

### ISSUE THREAD

**Issue by cnaize** [kubernetes/kubernetes#15154]
Hello!
I have problem with `containers` `garbage collection`.
When I start `kubelet` I have an error:
```none
E1006 08:04:08.856100   25155 kubelet.go:682] Image garbage collection failed: unable to find data for container /
```
And `garbage collection` doesn't work.
How to fix it?

**Comment by yujuhong** [comment]
Please re-post your question to stackoverflow.

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases.

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to similar questions, and also familiarize yourself with:

the user guide
the troubleshooting guide
Again, thanks for using Kubernetes.

The Kubernetes Team
