### ISSUE TITLE
Daemon (was Feature: run-on-every-node scheduling/replication (aka per-node controller or daemon controller))

### ISSUE THREAD

**Issue by jbeda** [kubernetes/kubernetes#1518]
There are cases where we want to run a pod on every node.  This'll be useful for monitoring things (cAdvisor, DataDog) or replicated storage agents (HDFS node).

Right now you can approximate this by (a) using a hostPort and (b) setting replication count > nodes.  It would be better if we had an explicit way of doing this.

**Comment by bgrant0607** [comment]
Discussed further in #3058.

**Comment by bgrant0607** [comment]
Prototype: #2491.

This is definitely something we want.

**Comment by mingfang** [comment]
+1

**Comment by ravigadde** [comment]
This can be achieved using anti affinity scheduler #9560 and a replication controller attribute that would maintain the number of replicas as equal to the number of nodes.

For this replication controller, the Replicas field is not relevant. Can you comment on whether this definition is appropriate before I submit a patch or if I should combine them in to a embedded replication policy object?

// ReplicationControllerSpec is the specification of a replication controller.
// As the internal representation of a replication controller, it may have either
// a TemplateRef or a Template set.
type ReplicationControllerSpec struct {
	// Replicas is the number of desired replicas.
	Replicas int `json:"replicas,omitempty"`

	// Run a replica on every node. Mutually exclusive with Replicas.
	EveryNode bool `json: "everyNode,omitempty"`

        ...
}

**Comment by erictune** [comment]
I think it is a bit more complex than that.
 - it isn't sufficient to set the number of replicas equal to the number of nodes.  If one node leaves and another appears at about the same time, the controller needs to add a pod for the new node and delete the pod for the departed node.  The pod that was on the departed node won't be rescheduled elsewhere.
 - Doing a rolling update of per-machine pods is tricky because they need to be sure not to lose their place on the machine between the time the old version is stopped and the new version is started.  There needs to either be preemption or special coordination between the per-node controller and the scheduler.  Also not clear if we want to duplicate the "two replications controllers" pattern for per-node rollouts.  @bgrant0607

**Comment by davidopp** [comment]
That's a pretty interesting point.

I think there are (at least) two ways to handle this.

Approach 1: The "dumb scheduler" approach. RC orchestrates everything. That is, it creates pods with hostname label selector, and creates new pods when a new machine is added or comes back from being down. The problem with this approach is the issue you mentioned in your second bullet (though I think you intended that in a slightly different way): A machine comes online (cluster grew or machine failed and recovered), and by the time the RC notices it, creates a pod, and the pod gets scheduled, other pods may already be running on the machine and it can't run. A priority/preemption scheme can knock someone off to make room, but generating an unnecessary preemption every time a machine comes online seems undesirable.

Approach 2: The "offload some work to the scheduler" approach. RC creates some very large number of pods (larger than the size of the cluster) with an anti-affinity predicate and then doesn't do much else. Pods have priorities that control the order that the scheduler considers pods when scheduling. Thus the scheduler will always put exactly one of these pods on a machine when it comes up, without triggering any preemption. The downside of this approach is that you have a lot of pending pods sitting around for no good reason (though the RC can try to manage the pool so it's always a relatively small number of pods.)

I'm sure there are even more complicated approaches, but I'm less sure there are simpler ones.

**Comment by ravigadde** [comment]
@erictune 
Very valid points.
1) If a node goes away, node controller would evict the pod. The default pod eviction timeout was very large last time I looked at it (5 mins). Since RC only looks at total number of nodes and pods, it doesn't notice this condition until the timeout happens and the pod is deleted by node controller.
2) Yes upgrade is tricky but conflict labels #9560 help. If the same conflict label is used by the new RC, the new pods have no where to go but to the vacated nodes.

@davidopp 
I like your suggestion of carrying a few (X) extra pods to cover for the first issue. How much should X be?

**Comment by davidopp** [comment]
Until we have a priority-based scheduling scheme, the extra-pods approach doesn't work, for the reason @erictune originally mentioned and which I also mentioned: when a machine comes up, other pods may fill the machine and the one you want running on every node may not be able to fit. (Or as @erictune also mentioned, even a rolling upgrade gives a window of time when another pod could sneak in and the replacement pod can't schedule there.)

**Comment by timothysc** [comment]
The typical use case I see of per-node replication is some form of provisioning.  In those scenarios you can just startup the pod at boot time and consider your base boot-strapping images immutable.  

Eventually with preemption+priority, we can just boot out other pods and a naive controller would work.

**Comment by nelcy** [comment]
+1 for priority based scheduling scheme.

@davidopp @erictune 
Irrespective of the agents discussion, I think we will still need solve the problem of newer pods replacing older pods when a node goes down and comes back alive. As David mentioned, the problem can be solved to a certain degree using the priority based scheduling scheme, but not 100%. Users intuitively want their previously running jobs to be scheduled instead of picking new ones.

Thinking more, the current workaround we have "use Host Port" to force scheduler to distribute agent pods, is some what along the same lines of using anti-affinity predicate.

**Comment by erictune** [comment]
@davidopp 
Approach 3: the controller for per-node pods also acts as specialized scheduler.  Nodes self-register in a default "unschedulable" state.  The controller for per-node pods both creates pods *and* binds them to nodes while node is in unschedulable state.  Here "unscheduleable" means "unscheduleable by the general purpose scheduler".   After it finishes binding all the per-node pods, it marks the node as schedulable.  On an update, it can do a "lock-update-unlock" cycle.

Things I like about this approach:
  - doesn't have unnecessary preemptions
  - doesn't introduce a general priority mechanism: we have seen how these can be misued and how much more complex they can make the scheduler and reasoning about the system.
  - could support the case where some per-node pods need to be started before normal pods are started (e.g. kube-proxy could run in a per-node pod, etc...)

**Comment by davidopp** [comment]
Interesting idea. As your last bullet implies, what you're describing is really a "node setup/configuration" controller.

I think this makes it clear that we haven't defined the requirements of whatever this thing is very crisply. It seems there are two possible interpretations

(1) It's a best-effort thing. Anybody can use it. We don't worry about races or priorities because it's 
best-effort. There's no way to guarantee you'll run on every node (or any node). You can submit stuff to this controller any time you want. Approach 1 falls into this category.

(2) It's a guaranteed thing. Really only appropriate for pods owned by the admin. Implicitly, these pods have higher priority than any other pods in the system, at least in the sense that they are scheduled on a new node before anything else has a chance (so in this sense scheduling in Approach 3 is similar to Approach 2, but without all the extra pending pods). They don't all have to run on every node, but the guarantee is "if you ask to run on N% (or M) of the nodes, then you will run on N% (or M) of the nodes." (We assume the admin will only create a set of daemons that have some feasible scheduling that fits, otherwise the guarantee can't be achieved.)

I can't think of anything useful in between. (That said, I could imagine that you could build (1) first, and then iterate on it to get (2)).

The approach you're suggesting can be used to achieve (2). Obviously there can only be one these controller/schedulers in the system (without creating some complicated scheme for handing off responsibility from one controller to the next when initializing a node; but I think how to do that is an unsolved problem, similar to coordinating pod initializers/finalizers which we've discussed in the past). But that seems fine.

The one thing I'm not sure about in your proposal is what happens if a daemon pod dies (and is not restarted locally). I think there is no way to guarantee that the replacement pod will be scheduled back onto that machine (I don't see how to use the unschedulable idea to fix that, at least not when there may be multiple schedulers in the system). But that may be OK. Also, I think that without a preemption mechanism, the only way to add new daemon pods would be to drain a machine, remove it, and then re-add it.

[BTW I just realized Approach 2 doesn't work when there are multiple schedulers (unless they were all somehow aware of all the pending pods each other holds, and their priorities -- at which point you really have a single scheduler). It also can't schedule onto a fixed percentage or number of machines, it can only schedule onto all machines. So I think the approach you described is the only one proposed so far that actually works (assuming the requirements in (2)).]

**Comment by timothysc** [comment]
@erictune without priority and preemption you need some guarantee on fairness.

**Comment by bgrant0607** [comment]
See #10210

**Comment by bgrant0607** [comment]
I'll try to find time to respond to the above proposals at some point, but I'm strongly opposed to numerical priorities.

**Comment by bgrant0607** [comment]
One comment at a time.

@ravigadde re. https://github.com/GoogleCloudPlatform/kubernetes/issues/1518#issuecomment-111192910: See discussion in #3058. We already decided not to reuse ReplicationController for this case.

**Comment by bgrant0607** [comment]
Re. https://github.com/GoogleCloudPlatform/kubernetes/issues/1518#issuecomment-111301530: @erictune is correct that we do not plan to use the same approach for rolling update.

I think Daemon should be more similar to the proposed Deployment (#1743) than to ReplicationController, in that it should contain a declarative representation of the desired state of the pod on all nodes, and should orchestrate rolling updates.

**Comment by bgrant0607** [comment]
Re. https://github.com/GoogleCloudPlatform/kubernetes/issues/1518#issuecomment-111367104 @davidopp: we should use approach 1, insofar as the Daemon controller should set the nodeName field.

**Comment by bgrant0607** [comment]
General comment on eviction of Daemon pods from nodes:

Forgiveness (#1574) could prevent eviction of Daemon pods, if necessary, but we don't need that initially.

**Comment by bgrant0607** [comment]
Re. https://github.com/GoogleCloudPlatform/kubernetes/issues/1518#issuecomment-113716293 @erictune: I agree that such a startup protocol would be useful. Perhaps we could use initializers as discussed in #3585. I wouldn't want to overload the current unschedulable field. Perhaps we could also just have the node controller schedule daemon pods, since it's responsible for node lifecycle. The node controller is less than 500 LOC currently. That would have the additional benefit that we wouldn't need to add forgiveness to the API in order to not evict daemon pods.

**Comment by bgrant0607** [comment]
Let's not overcomplicate the problem right now. I agree we'll probably need to restrict who can create daemons and we might need preemption, but we don't need them initially in order for this to be useful.

**Comment by bgrant0607** [comment]
I think I'm caught up. Let's make further comments on the proposal in #10210

**Comment by bgrant0607** [comment]
cc @AnanyaKumar

**Comment by bgrant0607** [comment]
@ravigadde Please comment regarding whether #10210 satisfies your use case.

**Comment by davidopp** [comment]
I like the idea of having the node controller schedule daemon pods. Putting in one place all the logic that has to run before a node is considered ready to accept regular pods makes a lot of sense. 

But I'm not sure why you're mixing Deployment into this. It seems that just as we built ReplicationController as one component and plan to layer Deployment on top to allow declaratively describing state of the whole cluster and orchestrating rolling updates, we can build DaemonController as one component (that is mostly identical to ReplicationController except it uses % of nodes where ReplicationController uses # of replicas) and then layer Deployment on top to do those other things. The only tricky part is ensuring the % maps consistently, but IIRC you and @lavalamp had some ideas on how we could do that. Anyway, we can discuss that on the other issue.

**Comment by davidopp** [comment]
(To clarify my previous comment, when I refer to DaemonController I'm talking about logic, not necessarily a separate component; as you said, we could put the logic in the node controller).

**Comment by ravigadde** [comment]
@bgrant0607 Thanks for your comments. I will add my comments to #10210 

+1 for adding this logic to node controller

**Comment by mikedanese** [comment]
I think this is done and we can close this now. Thanks @AnanyaKumar! Still todo (and discuss) is:

* handle daemonset podtemplate update
* integrate into nodecontroller

**Comment by zhangxiaoyu-zidif** [comment]
I have a question:
when i create the ds, the memory did not meet the request memory, and then when momory is enough, does daemonset start its pod?
 If the pod was not created when memory is insuffient, when memory is suffient, could the pod of ds start?
