### ISSUE TITLE
Failing flocker unit tests

### ISSUE THREAD

**Issue by karlkfi** [kubernetes/kubernetes#15212]
Unit tests on our CI have apparently been failing for 2 weeks and no one noticed (oops!)...

The PR that seems to have caused the failures is #14328.

The failing test is `k8s.io/kubernetes/pkg/volume/flocker` - `TestSetUpAtInternal`.

```
[16:15:04][Step 4/5] --- FAIL: TestSetUpAtInternal (0.00s)
[16:15:04][Step 4/5] 	assertions.go:202: 
[16:15:04][Step 4/5]                         
[16:15:04][Step 4/5] 	Error Trace:	plugin_test.go:208
[16:15:04][Step 4/5] 		
[16:15:04][Step 4/5] 	Error:		Not equal: "expected-to-be-set-properly" (expected)
[16:15:04][Step 4/5] 			        != "" (actual)
[16:15:04][Step 4/5] 		
[16:15:04][Step 4/5] FAIL
[16:15:04][Step 4/5] FAIL	k8s.io/kubernetes/pkg/volume/flocker	0.014s
```

Full Test Log: https://teamcity.mesosphere.io/viewLog.html?buildId=54217&buildTypeId=Oss_KubernetesMesos_2UnitTests&tab=buildLog&guest=1#_focus=866

I'm not sure why this is failing on our CI and not on shippable. Has anyone else seen something similar? 

**That test only seems to fail on the second run through with `etcdPrefix: kubernetes.io/registry`.**

Our unit tests run in a container built specifically for testing k8s-mesos:

```
$ cluster/mesos/docker/test/build.sh
$ docker run --rm \
  -v "$(pwd):/go/src/github.com/GoogleCloudPlatform/kubernetes" \
  -v "/var/run/docker.sock:/var/run/docker.sock" \
  mesosphere/kubernetes-mesos-test \
  -cexu "\
    cd /go/src/github.com/GoogleCloudPlatform/kubernetes && \
    make clean && \
    export KUBERNETES_CONTRIB=mesos && \
    make test
  "
```

The Dockerfile for the env: https://github.com/kubernetes/kubernetes/blob/master/cluster/mesos/docker/test/Dockerfile

Is anyone else able to repro with the above env or their own?

**Comment by agonzalezro** [comment]
@karlkfi that test was added around a week ago, it's doesn't seem possible to me that it was failing since 2 weeks ago.

Anyway, we have few duplications of this issue:

- https://github.com/kubernetes/kubernetes/issues/15118
- https://github.com/mesosphere/kubernetes-mesos/issues/546
- https://github.com/mesosphere/kubernetes-mesos/issues/542
- this one

And the PR where @jdef is working on:

- https://github.com/kubernetes/kubernetes/pull/15158#issuecomment-146082683

It's a little bit difficult to me to follow all the conversations in all the differente places about the same bug, could it be possible to unificate some?

Since you provided the environment I will try and take a look to reproduce it locally.

Thanks!

**Comment by jdef** [comment]
I think I've got a working patch in #15158

**Comment by karlkfi** [comment]
Closing in favor of #15118 & #15158
