### ISSUE TITLE
KUBE UI and Cluster Monitoring availble from a secured public IP

### ISSUE THREAD

**Issue by lucmichalski** [kubernetes/kubernetes#15225]
Hey guys,

I tried to deploy Kubernetes/Coreos on AWS (https://github.com/coreos/coreos-kubernetes/blob/v0.1.0/Documentation/kubernetes-on-aws.md) but is there a way to get it more simple to expose to a public IP:
- Kube-UI
- InfluxDB/Grafana

Is it possible to makes things much more simple ^^ ? :-)

Cheers,
Luc Michalski

**Comment by roberthbailey** [comment]
I'm not terribly familiar with the CoreOS+AWS setup but these both look like system provided services, so to get them exposed you should consider filing an issue in the coreos-kubernetes repository. For services that you create yourself, running `kubectl expose` with the ``--create-external-loadbalancer` should be a simple way to get a public IP. 

If you want a _secured_ public IP, then you will need to run an http proxy in front of the (insecure) kube-ui and influx/grafana services to add authentication. Again, this would need to be a deployment change to kubernetes-on-aws since this is specific to their installation of k8s.
