### ISSUE TITLE
kubectl explain does not work with experimental resources

### ISSUE THREAD

**Issue by derekwaynecarr** [kubernetes/kubernetes#15235]
It would be nice if ```kubectl explain``` let me explain experimental resources to aid users ability to experiment.

**Comment by derekwaynecarr** [comment]
It's possible this works today, but it was non-obvious how to use.

Attempts: 
```kubectl explain hpa```
```kubectl explain experimental/hpa```

**Comment by bgrant0607** [comment]
cc @caesarxuchao

**Comment by bgrant0607** [comment]
cc @JanetKuo

**Comment by JanetKuo** [comment]
No, this isn't supported, since current implementation only use v1 Client but not experimental Client.

**Comment by caesarxuchao** [comment]
@bgrant0607, do we need to fix this for 1.1?

**Comment by bgrant0607** [comment]
@caesarxuchao How difficult do you think it would be to fix?

**Comment by caesarxuchao** [comment]
It has dependency on ServerAPIVersions(), for which we plan to make a clean-up PR. I guess it needs 3-4 days to get two PRs merged.

**Comment by caesarxuchao** [comment]
With #15659, this can be fixed now.

What's the expected behavior of `kubectl explain`? I assume in case of `kubectl explain hpa`, it should search hpa in both v1 and extensions/v1bata1, and determines hpa as a resource in the extensions group?

BTW, the use of "api-version" flag is problematic https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/explain.go#L71. It adds extra meaning to the generic "api-version" flag.
