### ISSUE TITLE
Make sure upgrading a master from 1.0 to 1.1 won't break existing external load balancers

### ISSUE THREAD

**Issue by a-robinson** [kubernetes/kubernetes#15272]
I haven't yet thought through whether there will be any issues, but the introduction of using static IPs may cause some subtly broken assumptions after the upgrade when it comes to handling old forwarding rules that don't have static IPs.

Opening this to ensure it gets considered soon, before 1.1 is finalized.

**Comment by cjcullen** [comment]
If we have to handle "upgrading" external services to static IPs, we might as well get around the quota issue too (https://github.com/kubernetes/kubernetes/pull/13335#discussion_r41586467). Instead of holding on to a static IP for the life of a service, we could just promote it to static before the forwardingRule update, and then release it after it's been reattached to a new forwardingRule. I think the static IP quota of 7 is going to be a unnecessary point of friction.

**Comment by a-robinson** [comment]
Yup, this'll be a no-op if we only use static IPs while updating load balancers. Will be fixed by #15286.
