### ISSUE TITLE
File server best practice for GKE

### ISSUE THREAD

**Issue by bosticka** [kubernetes/kubernetes#15379]
I work in a mixed GCE / GKE environment.

My applicatin requires read / write access to some form of network or distributed file system.  I feel this is a pretty basic functional requirement for most applications.

However, in the GKE managed world, we are completely unable to mount any type of filesystem, FUSE based or otherwise because our containers cannot be privileged (alllow_privileged=true in the salt pillar only works if you have access to master, i.e. you roll your own cluster).

The main reason I use GCE / GKE is to minimize my infrastructure management, but at the same time it would be really really nice to be able to run a simple mount command in a docker nginx container in GKE.

I saw some code exists with CAP_SYS_ADMIN in it, but when I created a pod with this security spec, I get no capability exists errors.  So my guess is this code is not ready.

So my question is how and when will mounted filesystems be allowed in containers in GKE?  Or is there a better approach I am missing?

**Comment by roberthbailey** [comment]
@bosticka -- We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases and we prefer that help/support questions get posted to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes).

However, in this case there's an easy answer and the question will soon be obsolete -- privileged mode will be enabled by default starting with kubernetes 1.1 and this includes GKE. Once the release is cut (later this month) so will be able to run privileged containers in your GKE cluster.
