### ISSUE TITLE
GKE cluster DNS available to GCE instances

### ISSUE THREAD

**Issue by bosticka** [kubernetes/kubernetes#15380]
I work in a mixed GCE / GKE environment as I am sure many GKE customers do.

Currently, the skyDNS service from the cluster is not exposed GCE hosts in the same project.  This ip address range used by the DNS service is different from the normal application service range which is routable from all of GCE (each cluster node gets a route for its own subnet).

I specifically have a headless service in GKE I want to be able to reliably access via DNS by my GCE hosts.  As a workaround, I added routing to the node hosting the DNS pod and it works.

However, I fully understand that a simple skyDNS pod restart can break my route.

My question is, can the cluster master add this route to GCE like it does for normal node services or, even better, pull the DNS address from the normal service subnets where routing already works?

Can this be done?

**Comment by roberthbailey** [comment]
Please re-post your question to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes). 

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases. 

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to similar questions, and also familiarize yourself with:
  * [the user guide](http://kubernetes.io/v1.0/)
  * [the troubleshooting guide](http://kubernetes.io/v1.0/docs/troubleshooting.html)

Again, thanks for using Kubernetes.

The Kubernetes Team

p.s. If the answer is that it requires features / changes to k8s, then we will open an issue to track feature improvements in github.
