### ISSUE TITLE
[mesos/docker] Flakey Smoke Test - provided IP is already allocated

### ISSUE THREAD

**Issue by karlkfi** [kubernetes/kubernetes#15413]
```
[16:52:41][Step 4/4] The Service "kube-dns" is invalid.
[16:52:41][Step 4/4] spec.clusterIP: invalid value '10.10.10.10', Details: provided IP is already allocated
```

https://teamcity.mesosphere.io/viewLog.html?buildId=56458&buildTypeId=Oss_KubernetesMesos_5SmokeTestsDockerMesos&tab=buildLog&guest=1#_focus=480

Looks like node reuse didn't deallocate the IP correctly.

This is the first occurrence. Documenting for searchability.

**Comment by jdef** [comment]
That's interesting. I wonder what other service claimed that service IP? perhaps kube-ui (since it's not assigned an IP by default, it's possible that it was created before kube-dns and the service IP allocator granted it 10.10.10.10). AFAICT in cluster/mesos/docker the kube-dns service should be spawned before kube-ui .. but maybe something else wonky is happening?

**Comment by sttts** [comment]
We though this is fixed with https://github.com/kubernetes/kubernetes/pull/17871, but @sur saw it locally and it looked like there were no previous containers.

**Comment by jdef** [comment]
next time this happens, can we capture a dump of all the registered services in the cluster? would be nice to know what is hijacking 10.10.10.10

**Comment by sttts** [comment]
Good idea. Never saw that locally. But maybe it takes 254 test runs to hit one.

**Comment by davidopp** [comment]
Removing kind/flake label since we want to use that label only for tests that are in the Google CB. Please feel free to create a kind/mesos-flake for tracking flakes in the Mesosphere CB if you wish.
