### ISSUE TITLE
Memory statisics

### ISSUE THREAD

**Issue by mzupan** [kubernetes/kubernetes#15444]
Sorry if this is the wrong place for this. Looking at kube-ui and heapster for memory data about the nodes and its pulling RAM usage from kubelet so I think its getting the data there.

kube-ui and heapster UI show memory-usage or memory-working as the memory of the node+filesystem buffers. This really gives an incorrect overview of the memory usage of a node. For example

<img width="371" alt="screen shot 2015-10-11 at 3 28 24 am" src="https://cloud.githubusercontent.com/assets/205373/10416337/2da98462-6fc8-11e5-93e1-11264963ce6e.png">

It should I have around 6.2gig of memory used. the command `free` gives a different view

```
[root@kube-node_2c34068c ~] [dev] # free -h
              total        used        free      shared  buff/cache   available
Mem:           7.4G        409M        1.1G        363M        5.9G        6.3G
Swap:            0B          0B          0B
```

I'd expect to see 6.3gig free and not 1.1 since the OS will release that on demand.

Sorry if this is the wrong spot for this and if it is close it

**Comment by fabioy** [comment]
Please re-post your question to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes). 

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases. 

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to similar questions, and also familiarize yourself with:
   * [the user guide](http://kubernetes.io/v1.0/)
   * [the troubleshooting guide](http://kubernetes.io/v1.0/docs/troubleshooting.html)

Again, thanks for using Kubernetes.

The Kubernetes Team

**Comment by Malet** [comment]
@fabioy - stackoverflow is completely the wrong place for this. This is definitely a valid issue, please re-open.

Using 'wired' memory as the data shown on the dashboard gives the impression that a node doesn't have enough memory - which is definitely not the case in your scenario (or my own).

**Comment by mzupan** [comment]
I agree with @Malet since linux will use all the memory for file system buffering it gives the impression that there is no more memory to use for pods.

**Comment by geoah** [comment]
+1 This feels like an issue; Reported memory usage is painting a very false picture of what is happening in my cluster. Even a newly created cluster will show minions with high memory usage.

**Comment by timstclair** [comment]
@vishh - do you know whether this is an issue at the heapster or kubelet level?

**Comment by Malet** [comment]
I have this issue with heapster disabled, so it must be in the kubelet.

**Comment by vishh** [comment]
AFAIK [heapster](https://github.com/kubernetes/heapster/blob/master/docs/model.md) exposes [working set](https://github.com/google/cadvisor/blob/master/container/libcontainer/helpers.go#L361), which does not take into account inactive anonymous and file backed pages. [Kubedash](https://github.com/kubernetes/kubedash) also uses `workingSet` which I'd expect to align with the output of `free`. 
I'm not sure about the Kube UI though. From the snapshot, it looks like it is using total memory usage, which includes cold pages as well, which the kernel can flush on demand.

**Comment by vishh** [comment]
This is an issue with kube-ui. I'd suggest filing this issue in the kube-ui
repo.

**Comment by mzupan** [comment]
I see the same issue outside of kube-ui with hitting the heapster API endpoint for a node

**Comment by vishh** [comment]
Did you query `memory-working` stat ?

The current API is unfortunately not user friendly. It might be better to
report `memory-working` and `memory-usage` and the current `memory-usage`
as `memory-total` or something similar.

**Comment by mzupan** [comment]
@vishh ok I see now.. thanks I see the expected results.. I'll open a ticket with the ui project
