### ISSUE TITLE
aws: after exposing a rc, how to obtain the publcip?

### ISSUE THREAD

**Issue by skwokmag** [kubernetes/kubernetes#15526]
Basically, I followed http://kubernetes.io/v1.0/docs/user-guide/quick-start.html and I am using AWS. 
I used 
```export KUBERNETES_PROVIDER=aws; curl -sS https://get.k8s.io | bash```
to create the cluster. After executing
```kubectl expose rc my-nginx --port=80 --type=LoadBalancer```
, I executed 
```kubectl get svc my-nginx -o json | grep \"ip\"```
to try to obtain the public ip; however, I realized that it is not in the json. Although I can find the ELB in my AWS console, I'd like to know if there is a way to find that using CLI. Thank you.

**Comment by saad-ali** [comment]
Please re-post your question to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes). 

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases. 

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to similar questions, and also familiarize yourself with:
   * [the user guide](http://kubernetes.io/v1.0/)
   * [the troubleshooting guide](http://kubernetes.io/v1.0/docs/troubleshooting.html)

Again, thanks for using Kubernetes.

The Kubernetes Team
