### ISSUE TITLE
Docker uses wrong IP range when using CoreOS with cloud configs from getting started guide

### ISSUE THREAD

**Issue by MartinPodval** [kubernetes/kubernetes#15545]
We currently use getting started's master and node cloud config yamls in our testing cluster. See https://github.com/kubernetes/kubernetes/tree/master/docs/getting-started-guides/coreos/cloud-configs

K8s cluster works fine. However, it sometimes happen that the docker assigns IPs from wrong range, typically 172.x.x.x but it should use 10.x.x.x

Our investigation shows that the issue is hidden in details :-) In short:
- flannel generates file called `/run/flannel_docker_opts.env`
- the docker start uses this file to set up it's environment

Unfortunately, there is no dependency between flannel and docker in cloud config. Thus, sometimes flannel and docker started simultaneously so the file was not generated and docker used own IP range.

According to (this topic)[https://github.com/coreos/flannel/issues/112#issuecomment-72708347]:

'Docker itself starts on demand (socket activated), therefore it will also start after flannel is up`

The solution is therefore very simple. Just remove docker's start command from both cloud configs.

**Comment by dhawal55** [comment]
I had a similar issue. To make it worse, flannel depends on etcd to start and can fail if etcd is not ready. Adding a dependency on flannel in docker unit file causes docker to fail due to 'dependency' . Restart on-failure does not work for dependency failures.

The solution we adopted is to wait for the flannel file before starting docker (or kubelet, which starts pods which needs docker) using the below ExecStartPre command

ExecStartPre=/bin/bash -c 'until [ -e /run/flannel/subnet.env ]; do echo "waiting for flannel to complete."; sleep 5; done'

**Comment by davidopp** [comment]
@robszumski

**Comment by ahmetb** [comment]
The docs have been moved to their own repo long time ago. I would consider opening the issue there if this is still relevant. Due to long time inactivity, I'll go ahead and close this.
/assign
