### ISSUE TITLE
"Cannot open session" when using "su"

### ISSUE THREAD

**Issue by brandon-adams** [kubernetes/kubernetes#15589]
Hi all. I'm attempting to launch a container that launches its process by running several commands as another user. The commands are executed using *su*. I first thought this was a problem in the storage backend, as the container was built on devicemapper but run on aufs, but the container starts correctly when I use *docker run*. I also thought that this was an issue with the container being privileged, but I've already taken the steps necessary to run privileged containers on my cluster, as well as added the *privileged: true* flag to my Replication Controller definition. Any help is appreciated.

Kube v1
Docker 1.7.0
Mesos 0.23.0

**Comment by gmarek** [comment]
Please re-post your question to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes). 

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases. 

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to similar questions, and also familiarize yourself with:
  * [the user guide](http://kubernetes.io/v1.0/)
  * [the troubleshooting guide](http://kubernetes.io/v1.0/docs/troubleshooting.html)

Again, thanks for using Kubernetes.

The Kubernetes Team
