### ISSUE TITLE
Is there anything easy we can do to cut down the baseline CPU usage of node components?

### ISSUE THREAD

**Issue by a-robinson** [kubernetes/kubernetes#15590]
I've seen a handful of complaints about the baseline level of CPU usage on the nodes in GKE ([example](http://serverfault.com/questions/728763/how-do-i-figure-out-what-is-causing-excessive-cpu-usage-in-google-container-engi)). On an f1-micro node of my own, docker, the kubelet, google-fluentd, and heapster all occasionally spike up to consume non-trivial amounts of CPU. For what it's worth, heapster tends to be the worst, regularly spiking up to 16% of CPU, while the other components ever seem to spike to a few percent.

Is there anything easy we can do here? A simple small improvement would be to turn down docker's log-level flag from info to something higher, or at least to disable collection of docker logs in fluentd, which we've previously discussed in #13033.

I of course am not the expert here, though, so what do the folks on @kubernetes/goog-node think about the repeated questions?

**Comment by yujuhong** [comment]
I have limited knowledge on heapster and/or fluentd... @vishh for suggestions.

As for kubelet and docker, we are working on improving the cpu usage (#12540) so that we can increase the density on the node (and also avoid huge cpu spikes). The gist is that we will replace constant docker polling with an event stream, which should significantly reduce the steady state cpu usage for both.

f1-micro might be too small though, given that our default e2e test config uses n1-standard-2. What's running on your node?

**Comment by a-robinson** [comment]
I agree that an f1-micro is a bad example, but there isn't anything running on the node and the node size isn't really the point - the point that I keep seeing brought up is that the baseline resource usage is high. For instance, in another cluster without anything running on it I have an n1-standard-1 node with a steady 15% CPU usage, according to the developer console.

Although if you're already on it, perhaps this issue isn't needed :)

**Comment by yujuhong** [comment]
> , in another cluster without anything running on it I have an n1-standard-1 node with a steady 15% CPU usage,

Was the 15% CPU usage solely from kubelet and/or docker or did it include fluentd and other add-on pods? kubelet/docker's usage should increase with #pods/containers running on the node. Even though the per-pod overhead is quite high now, If there are no pods running and the cpu usage is high, that'd be a bug. A cpu profile would be appreciated in that case:
Run `kubectl proxy` and then
`go tool pprof http://localhost:8001/api/v1/proxy/nodes/<node_name>/debug/pprof/profile`


> Although if you're already on it, perhaps this issue isn't needed :)

I am speaking solely for kubelet and docker :) 
For heapster, there are issues to reduce the overhead as well. #12483 (aimed for v1.1) will revamp kubelet stats API, so that heapster doesn't have to send a query per container.

**Comment by a-robinson** [comment]
That number is everything running on the node, according to GCE's automatic monitoring of instances.

You should easily be able to replicate this yourself if you'd like a cpu profile, since it's just a default container engine cluster. Run `gcloud container clusters create foo` and you'll have a cluster of n1-standard-1s to look at, that will likely all be using 10-20% CPU according to GCE.

**Comment by yujuhong** [comment]
> You should easily be able to replicate this yourself if you'd like a cpu profile, since it's just a default container engine cluster. Run gcloud container clusters create foo and you'll have a cluster of n1-standard-1s to look at, that will likely all be using 10-20% CPU according to GCE.

Thanks. The numbers are not so meaningful since we cannot tell which % is contributed by kubelet/docker and by monitoring or logging. I agree in general we should have lower overhead though.

**Comment by jimmidyson** [comment]
We turn down docker log level to `warn` - `info` is just too verbose & pretty useless anyway. That reduces docker resource usage too btw.

Switching to docker event stream should bring a reasonably big decrease in utilisation, both for kubelet & docker.

**Comment by vishh** [comment]
Docker logs have been a concern for GKE logging as well. So +1 for turning down docker log level!

**Comment by yujuhong** [comment]
@a-robinson, should we close this issue since docker logging level has been changed?

**Comment by a-robinson** [comment]
The baseline resource usage is still pretty noticeable, but I haven't seen or heard any complaints in quite a while. I'm fine with closing this if you'd like

**Comment by yujuhong** [comment]
A new issue might get more notice if anything comes up, so I'll go ahead and close this one. Thanks!
