### ISSUE TITLE
Broken selflink for a specific component status

### ISSUE THREAD

**Issue by dkorn** [kubernetes/kubernetes#15618]
The selflink provided in the api response for component statuses (/api/v1/componentstatuses) is broken.
For example: /api/v1/namespaces/componentstatuses/controller-manager (as specified in the response of /api/v1/componentstatuses), will return:
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "the server could not find the requested resource",
  "reason": "NotFound",
  "details": {},
  "code": 404
}
while:  /api/v1/namespaces/default/componentstatuses/controller-manager, will return the data.

In addition, and this is asked for better understanding, are the component statuses namespace scoped? as far as I understood etcd, the scheduler and the controller manager were shared across the kubernetes cluster.
If they aren't namespace scoped, what is the logic behind specifing a namespace in these api requests (as shown in http://kubernetes.io/third_party/swagger-ui/#/):
/api/v1/namespaces/{namespace}/componentstatuses
/api/v1/namespaces/{namespace}/componentstatuses/{name}

If they are in fact namespace scoped, would you be kind and share an explanation/link to a documentation page?

**Comment by lavalamp** [comment]
I agree that it doesn't make a lot of sense for this to be namespaced given what's in it at the moment. Given what I'd like it to contain, the namespace might make more sense in the future.

The self link is super broken right now, though, probably due to lack of actual namespace. @caesarxuchao there's probably a bug in the go-restful setup code for this. Can you take a look at some point?

Also it might be worth mentioning that this will probably change in the near future, @karlkfi is working on a replacement.

**Comment by karlkfi** [comment]
The whole /componentstatus API is just broken. It needs rewriting.
