### ISSUE TITLE
Reflector's call of WatchInterface.Stop() every resyncPeriod results in a new TCP connection to the apiserver each resync

### ISSUE THREAD

**Issue by ncdc** [kubernetes/kubernetes#15664]
The Reflector is currently calling WatchInterface.Stop() each resyncPeriod to stop the watch, retrieve the full list of resources again, and then restart the watch.

Unfortunately, as indicated by https://github.com/golang/go/commit/8476d4cf2937fc261bbcf2890ba39d815bce3ae5, you have to read the response's body to completion before calling body.Close() if you want to reuse the TCP connection.

Because the watch response is chunked and of infinite length, there is no way to read the body to completion before calling close.

The end result is that each resyncPeriod, the TCP connection from the Reflector to the apiserver is closed, and a new one is opened.

**Comment by ncdc** [comment]
@smarterclayton @liggitt @kubernetes/rh-cluster-infra @jeremyeder @timothysc @kubernetes/goog-control-plane @lavalamp

**Comment by liggitt** [comment]
Also, all the non-watch places we do resp.Body.Close() are destroying our keep-alive sessions

**Comment by gmarek** [comment]
cc @wojtek-t

**Comment by smarterclayton** [comment]
* without reading the full body, which we do in most cases.

On Oct 14, 2015, at 5:09 PM, Jordan Liggitt <notifications@github.com>
wrote:

Also, all the non-watch places we do resp.Body.Close() are destroying our
keep-alive sessions

—
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/15664#issuecomment-148201243>
.

**Comment by smarterclayton** [comment]
This manifests in CPU profiles on the apiserver that are biased towards tls
handshaking when using elliptic curves (because they're slow) and you have
reflectors with frequent resyncs.  Also clients that watch for a specific
event and then react (but close their watch) will also close their
connection (note there is no way to have the client terminate the watch, so
we're stuck on this being ugly until http2 unless the condition we're
trying to observe is easily expressable as a field connection).

We *could* stop the infinite stream behavior of watch but it would hurt
throughput, and would be a lot of ugly code.

The client can exert backpressure on watch, so on resync stopping reading
from watch would result in the apiserver stopping sending events.

We could also send a timeout with watch to trigger resync on the server
side.

On Oct 14, 2015, at 5:20 PM, Marek Grabowski <notifications@github.com>
wrote:

cc @wojtek-t <https://github.com/wojtek-t>

—
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/15664#issuecomment-148204970>
.

**Comment by smarterclayton** [comment]
I think we should reuse the existing ?timeout= behavior for watch, and have the apiserver close the watch on the server side for us, and we'll wait a bit longer than that in the watch loop before closing the connection directly.  We may actually want to enforce a shorter watch timeout anyway (15 minutes) and this would be a good angle.

**Comment by smarterclayton** [comment]
I also think that the resync interval should apply an inverse multiplier to list size instead of being a fixed duration.  `nextResyncDeadline` could be calculated from `cacheSize / desiredSize * baseInterval + minimumInterval` or similar.  An empty cluster would resync at minimumInterval, and a doubling of cluster size would double the extra interval.  A 1k pod cluster resync interval doesn't make sense at 100k pods.

**Comment by wojtek-t** [comment]
Thanks for reporting it - this explains https://github.com/kubernetes/kubernetes/issues/13671
cc @kubernetes/sig-scalability 

BWT - I recently increased resync periods in different controllers - see https://github.com/kubernetes/kubernetes/pull/15153

>
Also, all the non-watch places we do resp.Body.Close() are destroying our keep-alive sessions

Do we do that in case of non-watch requests?

>
I think we should reuse the existing ?timeout= behavior for watch, and have the apiserver close the watch on the server side for us, and we'll wait a bit longer than that in the watch loop before closing the connection directly. We may actually want to enforce a shorter watch timeout anyway (15 minutes) and this would be a good angle.

I think that we are already using ?timeout= in watch - however the timeout is a random number IIUC from 5 to 10 minutes. We should just adjust it with to the individual resyncPeriods.

**Comment by jeremyeder** [comment]
@wojtek-t can you add me to @kubernetes/sig-scalability ?

**Comment by wojtek-t** [comment]
@jeremyeder - you need to request membership yourself. And I think only @jbeda can accept it.

**Comment by jeremyeder** [comment]
@jbeda can you add me to @kubernetes/sig-scalability please ?

**Comment by wojtek-t** [comment]
@smarterclayton - I will try to hack something about it to measure the impact of.
I'm going to follow your suggestions (that I really like) about reusing ?=timeout option.

Assigning to myself - will post here when I have some results.

**Comment by timothysc** [comment]
This could also explain #13331
/cc @jayunit100

**Comment by jbeda** [comment]
@jeremyeder Go to https://github.com/orgs/kubernetes/teams/sig-scalability and request to join.  I *think* I can approve that. I can't add you directly though.

**Comment by jbeda** [comment]
Wrt the CPU cost of reestablishing the TLS connect, are we making sure that we are using fast resume?  It looks like we need to use a ClientSessionCache across multiple TLS connections.  We can also look at the `DidResume` bit in the connection state. That'd be a good thing to put a counter on.  In steady state the percentage of connections that are resumed should be very high.

**Comment by smarterclayton** [comment]
We would need to have the session tickets set and shared across master
instances - just more config work (and we'd need to handle rotation).  I'm
also a little scared about fast resume and the security implications being
something everyone needs to be very sure of before they enable.

**Comment by jbeda** [comment]
With a single master API server, this should be easier, right?  Obviously this gets more complicated with HA masters if users connect to all of them randomly but we can put that off for a bit, I'm thinking. (I am by no means an expert here!)

**Comment by smarterclayton** [comment]
Well.... OpenShift is now fully HA on the apiservers and controllers, so we
wouldn't want to add things that make it harder.  That shouldn't block Kube
doing this, just that we should make sure we know exactly what we want to
add.

**Comment by jbeda** [comment]
Looking at the golang crypto library, it looks like fast reconnect is turned on by default on the server.  So we are already there.  Looks like key rotation support is coming in 1.6 (https://github.com/golang/go/issues/9994).

**Comment by smarterclayton** [comment]
It's a shame the elliptic curve improvements are blocked on copyright
issues.  That's what the underlying roadblock was on this particular block.

**Comment by jbeda** [comment]
Those improvements did make it in but they won't show up until 1.6 either.  https://twitter.com/jbeda/status/642516821589946368

**Comment by smarterclayton** [comment]
That's GCM, not Elliptic curve (negotiation) which is amazingly slow.  I
think we can only do 50/sec on a reasonably fast core, or something
ridiculously low.
