### ISSUE TITLE
Watching a list of resource doesn't work

### ISSUE THREAD

**Issue by JanetKuo** [kubernetes/kubernetes#15665]
**Problem**:
`kubectl get -f <file> --watch` won't work if the file contains a list (api.List, api.ReplicationControllerList, etc). 

For example, if we want to watch a ReplicationControllerList with 2 rc:
```console
$ kubectl get -f hack/testdata/multi-resource-rclist.json -w
CONTROLLER   CONTAINER(S)     IMAGE(S)           SELECTOR    REPLICAS   AGE
mock         mock-container   kubernetes/pause   app=mock    1          <unknown>
mock2        mock-container   kubernetes/pause   app=mock2   1          <unknown>
error: resource name may not be empty
```
Note that watch will first print the object being watched and then start watching. The object printed here should be but is *not* retrieved from server, because the list doesn't have a "name" and therefore the code failed to refresh the object. 

**Solution**:
Since we don't support watching multiple resources, we should print an error message when we find the file contains a list. The above example should print:
```console
$ kubectl get -f hack/testdata/multi-resource-rclist.json -w
error: watch is only supported on a single resource, but a list of resources is found
```

cc @bgrant0607 @smarterclayton

**Comment by smarterclayton** [comment]
That solution sgtm

On Oct 14, 2015, at 5:26 PM, Janet Kuo <notifications@github.com> wrote:

*Problem*:
kubectl get -f <file> --watch won't work if the file contains a list
(api.List, api.ReplicationControllerList, etc).

For example, if we want to watch a ReplicationControllerList with 2 rc:

$ kubectl get -f hack/testdata/multi-resource-rclist.json -wCONTROLLER
  CONTAINER(S)     IMAGE(S)           SELECTOR    REPLICAS   AGEmock
      mock-container   kubernetes/pause   app=mock    1
<unknown>mock2        mock-container   kubernetes/pause   app=mock2
1          <unknown>error: resource name may not be empty

Note that watch will first print the object being watched and then start
watching. The object printed here should be but is *not* retrieved from
server, because the list doesn't have a "name" and therefore it failed to
refresh the object.

*Solution*:
Since we don't support watching multiple resources, we should print an
error message when we find the file contains a list. The above example
should print:

$ kubectl get -f hack/testdata/multi-resource-rclist.json -werror:
watch is only supported on a single resource, but a list of resources
is found

cc @bgrant0607 <https://github.com/bgrant0607> @smarterclayton
<https://github.com/smarterclayton>

—
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/15665>.

**Comment by bgrant0607** [comment]
A clearer error sounds fine to me, also, but we should support watching a resource collection, potentially filtered by a label selector, correct?

**Comment by JanetKuo** [comment]
@bgrant0607 Yes, commands like `kubectl get pods --watch` will continue working since it's filtered by a label selector (when you don't specify resource name, the system gives you labels.Everything() by default).

**Comment by shyamjvs** [comment]
Just FYI, there's ongoing design for watching list of resources - https://github.com/kubernetes/community/pull/443
