### ISSUE TITLE
kubelet cpu usage increases over time

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#15661]
I had a 4-day old cluster and the kubelet cpu was 20%+ in all three nodes with only add-on pods running.  **Restarting kubelet resolved the issue.**
We've had similar reports from users on slack before.

Edit:
```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"2+", GitVersion:"v1.2.0-alpha.1.1023+f981006eb58fa9-dirty", GitCommit:"f981006eb58fa9efca0e9be1e50f4edf007d4c38", GitTreeState:"dirty"}
Server Version: version.Info{Major:"1", Minor:"2+", GitVersion:"v1.2.0-alpha.1.760+ed382ec0a02c76-dirty", GitCommit:"ed382ec0a02c7633d560ab0ac81acaf64d05acf2", GitTreeState:"dirty"}
```

Here are some cpu profiles I took before restarting:

![kubelet1](https://cloud.githubusercontent.com/assets/10524058/10497163/58c7f634-7279-11e5-8eda-d5a8a3872962.png)
![kubelet2](https://cloud.githubusercontent.com/assets/10524058/10497191/7b08a5b8-7279-11e5-9e33-d9870b7d0e57.png)

**Comment by yujuhong** [comment]
@kubernetes/goog-node

**Comment by dchen1107** [comment]
@yujuhong What is the difference between this node and other two nodes? More pods? more containers? 

There are two major contributors from the graph you posted: 
1) cadvisor: we already know
2) go-dockerclient: Part of them comes from ListContainers, introspectContainer, which is known heavy operations. Once we switch to event based pod lifecycle management, those cost should go away.

But you are right on there must be some leakage either in go-dockerclient library itself, or caused by the way we are using it since restarting kubelet fixes such issue.

**Comment by yujuhong** [comment]
> @yujuhong What is the difference between this node and other two nodes? More pods? more containers?

There were three nodes in the cluster running only addon pods. **All three of them** exhibited the unusual high cpu usage.

**Comment by dchen1107** [comment]
@yujuhong any container has crashloop?

**Comment by yujuhong** [comment]
> @yujuhong any container has crashloop?

Nope, the containers were all running happily and had not be restarted for days.

**Comment by derekwaynecarr** [comment]
@kubernetes/rh-cluster-infra

@tstclair - have you seen this?

**Comment by dchen1107** [comment]
@bgrant0607 To answer your earlier question, we do actively pprofing kubelet, and several issues caused by cAdvisor were fixed. Here is the recent report from @yujuhong on kubelet cpuusage. Obviously there still some unknown leakage through using of go-dockerclient library. Beyond this, we can optimize the code and reduce more resource footprint in a long run. But some of those cost cannot be avoid, and have to be budget.

**Comment by ncdc** [comment]
cc @timothysc

**Comment by yujuhong** [comment]
Could be relevant: https://github.com/kubernetes/kubernetes/issues/15644#issuecomment-148659147

**Comment by dchen1107** [comment]
FYI, #15805 might be the real cause.

**Comment by yujuhong** [comment]
I found the culprit. It is caused by the go-dockerclient change and how cadvisor uses it. See the details in https://github.com/kubernetes/kubernetes/issues/15805#issuecomment-148963658. 

Closing this issue as dup.
