### ISSUE TITLE
Google Container Engine only recognizes Nodes created with Debian?

### ISSUE THREAD

**Issue by dmcqueen** [kubernetes/kubernetes#15660]
I'm trying to switch my gke cluster to use an ubuntu instance template for the clusters instance group and seems like kubectl will only recognize the nodes created with the Debian instance template.  Is this a restriction for GKE?

**Comment by dchen1107** [comment]
cc/ @kubernetes/goog-gke

**Comment by roberthbailey** [comment]
There isn't anything in GKE that is preventing your from using a different base image -- we may it really easy to use the default image, but it's possible (if you know what you are doing) to use a different OS. 

You won't be able to just change the image type in the instance template and expect the nodes to work. The instance template (and specifically the startup script) are specific to our Debian image, so you will need to create your own startup script to configure your nodes to join your cluster.

**Comment by fabioy** [comment]
If you need continued assistance, please re-post your question to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes). 

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases. 

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to similar questions, and also familiarize yourself with:
   * [the user guide](http://kubernetes.io/v1.0/)
   * [the troubleshooting guide](http://kubernetes.io/v1.0/docs/troubleshooting.html)

Again, thanks for using Kubernetes.

The Kubernetes Team
