### ISSUE TITLE
Dependency on unavailable source repos

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#15734]
Some Shippable builds failed with:
```
./hack/verify-godeps.sh ...
Starting to download all kubernetes godeps. This takes a while
package bitbucket.org/bertimus9/systemstat: https://api.bitbucket.org/1.0/repositories/bertimus9/systemstat: 503 Service Unavailable
godep: restore: exit status 1
package bitbucket.org/ww/goautoneg: https://api.bitbucket.org/1.0/repositories/ww/goautoneg: 503 Service Unavailable
godep: restore: exit status 1
```

Two problems are evident here:

1. every time we do a shippable build, we are running verify-godeps, which is pulling source from a remote repository.  That should not have to happen every single build, should it?  Seems wasteful.
1. today, http://www.bitbucket.org/ is down.  It was giving 500s when I visited their web site, and I see 503s in the log above.  So, our build system depends on the union of the reliabilities of the various packages we depend on.

**Comment by erictune** [comment]
http://status.bitbucket.org/ confirms "major outage".

**Comment by ihmccreery** [comment]
@jlowdermilk Does your work to containerize tests take care of this?

**Comment by jlowdermilk** [comment]
Nope. The fact that tests run containerized means they have to run `godep go install ./...` on each run. We can't cache dependencies across builds otherwise we'll get into inconsistent states when testing prs that add/bump dependencies. We could mirror dependencies but that defeats the entire purpose of using godeps. I think this is just something we live with.

**Comment by ihmccreery** [comment]
@erictune Do you agree?  Can we close this?

**Comment by ihmccreery** [comment]
Closing as obsolete.
