### ISSUE TITLE
e2e.go -push is borked

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#15738]
I suspect we're going through an if/else clause where KUBE_TAR_URL isn't defined, and not defaulting it, though the function header seems to indicate it should be set in the callee.
```
/usr/local/google/home/beeps/goproj/src/k8s.io/kubernetes/hack/e2e-internal/../../cluster/../cluster/../cluster/gce/../../cluster/common.sh: line 283: KUBE_TAR_URL: unbound variable
```
@ihmccreery

**Comment by ihmccreery** [comment]
Will take a look.

**Comment by ihmccreery** [comment]
@bprashanth Is this in Jenkins, or on a local run?

The Jenkins push job is borked as well, but it looks like it's for a different reason:

```
s: "error running /jenkins-master-data/jobs/kubernetes-push-gce-step1-deploy/workspace/kubernetes/hack/get-build.sh [-v ci/latest]; got error fork/exec /jenkins-master-data/jobs/kubernetes-push-gce-step1-deploy/workspace/kubernetes/hack/get-build.sh: no such file or directory, stdout \"\", stderr \"\"",
```

Which I'm taking care of in #15737.

**Comment by fabioy** [comment]
Jobs are generating incredibly large log files  (300 Megs?) with lots of repeated lines like this:

Failure trying to curl release .sha1
/jenkins-master-data/jobs/kubernetes-push-gce-step1-deploy/workspace/kubernetes/hack/e2e-internal/../../cluster/../cluster/../c
luster/gce/../../cluster/common.sh: line 283: KUBE_TAR_URL: unbound variable
Failure trying to curl release .sha1
/jenkins-master-data/jobs/kubernetes-push-gce-step1-deploy/workspace/kubernetes/hack/e2e-internal/../../cluster/../cluster/../c
luster/gce/../../cluster/common.sh: line 283: KUBE_TAR_URL: unbound variable
Failure trying to curl release .sha1

I think this needs to be resolved, since it already caused an out-of-disk in Jenkins.

**Comment by ihmccreery** [comment]
Okiedokie.  Yes, this was my fault.  `tars_from_version` silently expects `SERVER_BINARY_TAR_URL` and `SALT_TAR_URL` to be set in `find-release-tars`.  I added the extra expectation that `KUBE_TAR_URL` be set, but didn't think about how `find-release-tars` would then also have to set that.  Working on a fix.

**Comment by ihmccreery** [comment]
(For anyone who cares, culprit is #15519.)
