### ISSUE TITLE
Make capacity planning easier

### ISSUE THREAD

**Issue by quinton-hoole** [kubernetes/kubernetes#15743]
=== copy of email trail ===
If we can expose cluster fullness and pending pods metrics to customers, they will figure out from experience what a healthy fullness ratio is for their pod shape mix ("when we get to 90% RAM consumption, we typically see pending pods, so lets plan ahead and not get to 90% RAM consumption" etc).

Q

On Thu, Oct 15, 2015 at 2:22 PM, David Oppenheimer davidopp@google.com wrote:
A good measure for "cluster fullness" is tricky due to fragmentation. But it would be trivial to just give sum(request across all pods)/cluster capacity and sum(usage across all pods)/cluster capacity for each resource. Well, second one depends on getting usage surfaced to the API which isn't there yet.

On Thu, Oct 15, 2015 at 1:16 PM, Quinton Hoole quinton@google.com wrote:
In addition surfacing the number of pending pods(which will in many cases be ~0 until a cluster is almost out of capacity, and then shoot up, a bit too late to be useful), I was thinking of surfacing the "% fullness" of the cluster along some useful scheduling axes (presumably currently only CPU, RAM, but in future also disk space, disk IOPs, network bandwidth, network packets per second and perhaps others).

The key to all of these metrics is observing their trend over time, so while a "get pods" gives an instantaneous value, further tooling (e.g. graphing over time) would be needed to make this actually useful.  As you imply, some of this might already be available via one of our UI's/monitoring GUI's.  I don't know.

Q

On Thu, Oct 15, 2015 at 11:26 AM, David Oppenheimer davidopp@google.com wrote:
I guess you are suggesting that we somehow surface the # of pending pods more clearly?
It should be visible with "kubectl get pods"
Not sure how or if it shows up in the UI.

On Thu, Oct 15, 2015 at 10:59 AM, Quinton Hoole quinton@google.com wrote:
PS:  This does probably highlight a usability issue with K8s though.  
How does a user do capacity planning for their production cluster?
And how do they easily detect that they're out of capacity , and need to provision more nodes (other than by noticing that their pods don't schedule reliably - which is a pretty blurry signal)?
Horizontal node autoscaling might be one solution, but I would imagine that some users will want to do this sort of thing manually, at least at first.

Thoughts?

Q

**Comment by dchen1107** [comment]
Couple of comments without deep thinking:

* Shouldn't horizontal node scaling should take care of this? At least the same/similar set signals should be used by autoscaler? Of course, we need separate machine / node management system to get the signals, and add the new node(s) to the scheduling pool.
* Resource fragmentation has to be resolved through rescheduling. But to make node more compact, we need better resource isolation on node for sure. Again real QoS. :-)
* # of pending pods maybe not a good indicator based on today's pod lifecycle definition unless we can rule out all pending pods caused by long docker image pulling

**Comment by davidopp** [comment]
> Shouldn't horizontal node scaling should take care of this? At least the same/similar set signals should be used by autoscaler? Of course, we need separate machine / node management system to get the signals, and add the new node(s) to the scheduling pool.

Good point about using similar signals as cluster autoscaling; maybe the thing @quinton-hoole is talking about could be a service provided by the cluster autoscaler, on both cloud providers and bare metal (even though cluster autoscaling obviously doesn't work on bare metal). This will make sense once cluster autoscaler is a Kubernetes component; right now it is a GCP component and can't be customized.

@fgrzadkowski @jszczepkowski @mwielgus @piosz 

> # of pending pods maybe not a good indicator based on today's pod lifecycle definition unless we can rule out all pending pods caused by long docker image pulling

This is a good point. In Borg we try to use "pods that are pending because they are infeasible on all nodes" so we don't count things that were recently submitting and we just haven't gotten around to scheduling them yet, etc. I assume we'd want to use something like that here.

**Comment by ncdc** [comment]
@davidopp I had a chance to talk to @twiest from our Ops team to get some better ideas about what they need for cluster capacity planning. Before I get to that, I need to describe a custom admission controller on OpenShift that allows cluster admins to restrict which nodes are available to specific namespaces ("dedicated nodes" if you want to think of it that way). It works like this:

1. In the absence of the annotation `openshift.io/node-selector` on a namespace, a namespace's node selector is set to a default value specified by the cluster admin
1. During pod admission:
  1. Reject any pod whose node selector conflicts with the namespace's node selector
  2. Merge the namespace's node selector with the pod's node selector and admit the pod

This allows us to set a cluster-wide default of e.g. `type=compute` that is applied to most namespaces, but we can then have an `infra` namespace with a node selector of `type=infra`. @twiest can give more specifics on actual example selectors we have.

Having said all that, one of the things that would help our Ops team is being able to figure out when a given node selector is running low on available, schedulable capacity. They could imagine doing something like this:

1. Find all the namespace node selectors currently in use
1. For a given node selector
  1. Determine the resource requirements of the "biggest pod allowed" across all the namespaces using this selector. This basically means looking at the limit ranges in these namespaces and finding the max values of `limits.cpu` and `limits.memory`, for starters.
  1. Looking at the available resources on all the nodes matching this selector, determine how many pods could successfully schedule based on the limits gathered above (e.g. 1 data point for CPU, 1 for memory)

Ops has requested being able to get this information both in json/yaml (`-o FORMAT`) and pretty-printed.

cc @smarterclayton @eparis @derekwaynecarr @danmcp @aveshagarwal @kubernetes/rh-cluster-infra

**Comment by smarterclayton** [comment]
Note that we use the "type=infra" constraints specifically because
tolerations and taints had not been invented - we would prefer to have
tolerations be quota / policy controlled for end users and use taints to
steer user pods away from infra nodes.

**Comment by smarterclayton** [comment]
The things described here sound a lot like kubectl top and borgcfg --advise
as described in other issues, with the addition of "common requested node
selectors" and possibly "capacity available for those commonly requested
node selectors".  However since the set of selectors is potentially
infinite, it would probably be more reasonable to make it possible to ask
for answers on specific node selectors for "top".

**Comment by twiest** [comment]
@smarterclayton From what I've seen of `kubectl top` (which is admittedly not much), it shows you current usage.

We're more concerned about scheduled usage. We want to know ahead of time that we need to add capacity because the scheduler is close to running out of capacity in one way or another (cpu, mem, etc).

**Comment by derekwaynecarr** [comment]
I think this is a non-scheduling scheduler that runs as a pod on the cluster, watches all nodes, and all pods, and has a REST API to answer queries like: "approximately how many more pods could i schedule with this shape?".  Trying to do a N*N merge of scheduler state in a CLI command feels potentially non-responsive versus a dedicated controller that can do long running WATCH of pods and nodes.

**Comment by smarterclayton** [comment]
Otoh for small ad hoc clusters (what most people have) the tool is a
good first step to validate the idea, and a controller is just a fancy
CLI tool

**Comment by derekwaynecarr** [comment]
@ingvagabund fyi for historical reading...
