### ISSUE TITLE
Add example application for Apache Flink on Kubernetes

### ISSUE THREAD

**Issue by hsaputra** [kubernetes/kubernetes#15817]
With more people trying to run Apache Flink [1] as better distributed platform for streaming and batch, I think it will be great to add example to deploy Flink cluster on Kubernetes.

It is already support deployment on YARN [2], Google Cloud [3], and Apache Mesos pending PR [4]

[1] http://flink.apache.org/
[2] https://ci.apache.org/projects/flink/flink-docs-release-0.9/setup/yarn_setup.html
[3] https://ci.apache.org/projects/flink/flink-docs-release-0.9/setup/gce_setup.html
[4] https://github.com/apache/flink/pull/948

**Comment by HaiyangDING** [comment]
@hsaputra 

Hi, how is issue going? Are you working on this?

**Comment by hsaputra** [comment]
Hi @HaiyangDING , I will not start looking at this until sometimes next week.

If you would like to work on it, feel free to work on it.

**Comment by HaiyangDING** [comment]
@hsaputra 

Hi, I asked this because I am interested in Apache Flink, however I am not that familiar with it:) I am looking forward to seeing Flink running with Kubernetes.

I would give it a try but I think eventually it should be someone who knows Flink well to do this.

Thank you.

+1 for this issue.

**Comment by hsaputra** [comment]
That is awesome.Yeah, my interest is also actually with Flink. 
Will try to give it shot to make it deployable with Kubernestes

**Comment by davidopp** [comment]
@zmerlynn

**Comment by davidopp** [comment]
@kubernetes/sig-big-data

**Comment by jayunit100** [comment]
If someone is new to kube and working on this, i'd suggest a roadmap: 
- use hack/local-up-cluster.sh to get kube working locally
- then try to run the spark example,  its a good place to borrow from for glueing ports together and so o https://github.com/kubernetes/kubernetes/tree/master/examples/spark
- from there, modifying it to use flink containers shouldn't be too bad.

**Comment by timothysc** [comment]
@hsaputra could you elaborate the specific use case(s) that you are interested in?  

Other factors to consider: 
- Elastic?  Does Flink batch execution have enough knowledge to attempt to greedily widen it's execution, or should we start with stand-alone setup? 
- Communications?  Can flink handle being behind an L7 loadbalancer?  akka has known issues, and requires it be configured properly on startup which is often different then the defaults. 
- Logistics?  Where will we keep the Docker file and templated configs?  Do you have upstream acls to help push that file upstream, and possibly add test cases?  
...

**Comment by hsaputra** [comment]
Thinking this will be just bare basic example how kubernetes could be used to deploy Flink as standalone.
Need to add Docker image for Flink, I assume we could add it to main Docker repo?

**Comment by mattf** [comment]
cc @smarthi

**Comment by tillrohrmann** [comment]
Hi @timothysc, concerning some of your questions:

1. Flink starts with a fixed number of TaskManagers and JobManagers. If you want to increase those, then you have to restart the cluster at the moment. Is this what your question was?
2. Which component of Flink do you want to set behind a L7 loadbalancer? Do you intend to start multiple Flink clusters which can handle multiple incoming job submissions?

**Comment by zmerlynn** [comment]
@tillrohrmann: The issue with Akka is this (unless @timothysc is thinking of another one): In the Kubernetes world, the best practice is to start replication controllers for everything, including the master service. This ensures that that the master is protected from failures, so if the master pod crashes or if the node that it's running on dies, the RC will recreate it. But what this looks like is that you'll have a controller like `flink-master-controller` with a pod like `flink-master-controller-abc123`. 

We then put a Kubernetes service in front of it, say `flink-master`, so that the cluster DNS `flink-master` always resolves to the endpoint for `flink-master-contoller-abc123`. Now you can also envision a multi-master setup working with this, too (if flink supports multi-master), but let's not even go there, yet.

The problem I had in Spark at least comes about in the `flink-master-controller-abc123` pod, because Akka comes up, says "Oh, I'm `flink-master-controller-abc123`", but then the workers connect to it as `flink-master`. Akka on the master sees the worker messages to `flink-master`, but thinks its own identity is `flink-master-controller-abc123`, and in violation of the robustness principal (liberal acceptance, yadda yadda), rejects the alternate identity.

That's similar to Flink sitting behind a load balancer.

If you want to see how I worked around it in Spark, I hacked around it this way: https://github.com/zmerlynn/kubernetes/blob/777d3a6ec0acfbf6a517d5b3fb62ff64d8222e15/examples/spark/images/master/start.sh .. which was to give the master image a fixed `/etc/hosts` for `spark-master` (which wouldn't work in a multi-master, but don't care just yet), and fixed up some Spark specific variables that would override Akka specific variables. From what I've heard, other people get around this by doing something like calling `hostname spark-master`, which might also work. See https://github.com/kubernetes/kubernetes/issues/16517 for all the issues I ran into / and  https://github.com/kubernetes/kubernetes/issues/260#issuecomment-133318903 for the hostname thing in general.

**Comment by smarthi** [comment]
@jayunit100 I can take a shot at this

**Comment by jayunit100** [comment]
i thought @mattf also had an  elegant solution...  right matt? ... it involved one of the akka parameters  that you could plubm through spark?  maybe im forgetting something.

**Comment by zmerlynn** [comment]
@jayunit100: I springboarded off of some of @mattf's work (I assume, since the image design was his), but the original Spark example was service env based and and I switched it over to DNS, plus it was still using a naked pod for the master. But that all might've been @brendandburns's fault, too. :)

**Comment by mattf** [comment]
originally the naked pod was necessary, so the master would think of itself as "spark-master" and then https://github.com/mattf/docker-spark/blob/master/worker/start.sh#L4 so the workers would also think of the master as "spark-master"

https://github.com/mattf/docker-spark/blob/master/worker/start.sh#L7 was important to get the worker to avoid using its local name, which wouldn't resolve on the master

https://github.com/mattf/docker-spark/blob/master/master/start.sh#L4 is how i got around the tcp:// url issue

i haven't had a chance to try out the new spark example, which uses a controller for the master

i don't know how many of these issues a set of flink pods will run into

**Comment by jayunit100** [comment]
ah yes, `[SPARK-5078] Optionally read from SPARK_LOCAL_HOSTNAME`, is the key to it,.  if the flink stuff asks for resolution of the ip, then the local resolver   workaround will also be  needed in flink.

**Comment by tillrohrmann** [comment]
Thanks for the explanation @zmerlynn. I think you have to do something similar for Flink as well, since the RPC communication is done via Akka.

What happens on the `JobManager` side is that it is started with a hostname to bind to. The hostname is resolved to an IP which is used as the hostname for the `ActorSystem`. The same thing basically happens on the `TaskManager` side. When used without high availability, then the `TaskManager` read the `JobManager's` hostname from the configuration file and resolve it into an IP. This IP is then used to create the Akka URL to which the `TaskManager` then try to connect.

Consequently, the `TaskManagers` should be started with a hostname for the `JobManager` which they can resolve to the IP address of the machine on which the `JobManager` runs and to what the `JobManager's` `ActorSystem` is bound.

The fact that Flink always resolves the hostname to IPs probably entails that the `TaskManagers` also have to be restarted in case of a `JobManager` failure.

**Comment by shuowusc** [comment]
Any update on this?

**Comment by mattf** [comment]
if anyone is interested in this i encourage them to come discuss with the @kubernetes/sig-big-data (hangout 4pm et on mondays, #sig-big-data on slack.k8s.io)

currently flink isn't in the sig's plan, but there are members who would be willing to assist/guide.

**Comment by harold-sun** [comment]
I got this working. The trick is let workers connect to master through master's pod IP.

**Comment by irvingwa** [comment]
@harold-sun Do you have the templates you got this working with? Mind putting them up somewhere?

**Comment by CaliLuke** [comment]
I'm also interested in reading some kind of guide on how to get Flink to work on Kubernetes

**Comment by resouer** [comment]
@harold-sun @hsaputra Would you like to send a doc PR about `Apache Flink on k8s` in `https://github.com/kubernetes/kubernetes/tree/master/examples` as an official guide?

**Comment by yihuaf** [comment]
I got it working in a very rudimentary way. The basic idea is to create a service in your cluster for the jobmanager, give the k8s' dns path for the jobmanager's service to the taskmanager and then launch your taskmanager. The taskmanager should automatically add itself to the jobmanager. It's very much similar to running flink stand alone and have k8s launch more pod as taskmanager to scale the cluster up. I can try to write it up with sample deployment if no one is working on it already.

**Comment by immortalHuang** [comment]
in the flink website,i find https://ci.apache.org/projects/flink/flink-docs-release-1.2/setup/kubernetes.html#launching-the-cluster,and i deploy flink in my k8s cluster,but there is still some problem with akka,anyone known why?

**Comment by kargakis** [comment]
@ahmetb

**Comment by ahmetb** [comment]
We no longer accept contributions to examples unless they demonstrate use cases not covered by examples we already have [here](https://github.com/kubernetes/examples/blob/e00514bce95b38223f92c36b3a3fc526e5aaa94e/README.md). Consider creation a repository yourself and maintaining it outside Kubernetes.
