### ISSUE TITLE
Troubles in HDFS deployment on Kubernetes

### ISSUE THREAD

**Issue by JiaMingLin** [kubernetes/kubernetes#15827]
Hi 

I am trying to deploy Hadoop 2.7.1 on Kubernetes, Docker. But I got problem when the Namenode was starting.

I use the Flannel network, and enable the dns service, then make the service and replication-controller templates with some ports exposed such as 8020, 50070 and so on. And the pods were provisioned by the replication-controller.

I configured the Namenode host by using Service name, for example, service name is namenode-svc, then the Namenode host is namenode-svc and fs.default.name=hdfs://namenode-svc:8020
, and the other configurations were analogue to this way.

I also set the hostname to be the service name, what I have done were
1. Wrote the pair of service name and ip at the first line of /etc/host file.
2. hostname $SERVICE_NAME
3.echo $SERVICE_NAME > /etc/hostname
and make sure the output of command "hostname" is $SERVICE_NAME

But the it was failed when the Namenode was starting, and the log says the port 50070 is already used on 192.168.xx.xx

I am confused about why this error happened?

**Comment by jlowdermilk** [comment]
Please re-post your question to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes). 

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases. 

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to similar questions, and also familiarize yourself with:
   * [the user guide](http://kubernetes.io/v1.0/)
   * [the troubleshooting guide](http://kubernetes.io/v1.0/docs/troubleshooting.html)

Again, thanks for using Kubernetes.

The Kubernetes Team
