### ISSUE TITLE
Merge-bot seems to auto-merge PR's that break e2e

### ISSUE THREAD

**Issue by quinton-hoole** [kubernetes/kubernetes#15848]
#15787 got auto-merged, but broke e2e tests.  Probably because the test that it broke is not run pre-commit, due to it not running well in parallel?  Need to confirm and fix if possible.

**Comment by quinton-hoole** [comment]
cc @fabioy

**Comment by quinton-hoole** [comment]
I've confirmed that the test that #15787 broke was in fact run pre-commit, and passed.  So my theory above is incorrect:

job/kubernetes-pull-build-test-e2e-gce/13151/testReport/(root)/Kubernetes%20e2e%20suite/Kubectl_client_Simple_pod_should_support_exec_through_an_HTTP_proxy/

More investigation required to explain this.  Unless someone can explain this, we appear to have a fairly serious bug in our merge-bot.

**Comment by fabioy** [comment]
Agreed. Found this late Sat, so i reverted it (#15821). This PR seems to reference a shell script that's only available on a full build, so perhaps a difference in setup for the e2e test could account for the failure? I'm not as familiar with the e2e test setups.

**Comment by ashcrow** [comment]
@fabioy FWIW it does reference a script for full build but should only do so if the release tars do not contains a 386 ```kubectl```. It references it as it is needed to build a static ```kubectl```

**Comment by fabioy** [comment]
Interesting. The Jenkins script is basically "hack/jenkins/e2e.sh", which fetches the release tars from: 

        gsutil -m cp gs://kubernetes-release/${bucket}/${githash}/kubernetes.tar.gz gs://kubernetes-release/${bucket}/${githash}/kubernetes-test.tar.gz .

Still poking around.

**Comment by ashcrow** [comment]
@fabioy those are the two it requires. I wonder if the ```WORKSPACE``` environment variable is not set. If It isn't then this specific test will attempt to use the ```testContext.RepoRoot```. I'm not sure what the result would be if release tars are used with ```testContext.RepoRoot```...

**Comment by fabioy** [comment]
The exact tar ball it loaded was this:

gsutil -m cp gs://kubernetes-release/ci/v1.2.0-alpha.1.1270+0338e0ef538303/kubernetes.tar.gz gs://kubernetes-release/ci/v1.2.0-alpha.1.1270+0338e0ef538303/kubernetes-test.tar.gz .

Logs show the test failing with a "hack/build-go.sh" not found:

22:21:49 Kubectl client Simple pod 
22:21:49   should support exec through an HTTP proxy
22:21:49   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:378
22:21:49 [BeforeEach] Kubectl client
22:21:49   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:89
22:21:49 >>> testContext.KubeConfig: /var/lib/jenkins/jobs/kubernetes-e2e-gce/workspace/.kube/config
22:21:49 Oct 17 22:21:49.305: INFO: Waiting up to 2m0s for service account default to be provisioned in ns e2e-tests-kubectl-gir7q
22:21:49 Oct 17 22:21:49.307: INFO: Get service account default in ns e2e-tests-kubectl-gir7q failed, ignoring for 2s: serviceaccounts "default" not found
22:21:51 Oct 17 22:21:51.311: INFO: Service account default in ns e2e-tests-kubectl-gir7q with secrets found. (2.005703969s)
22:21:51 [BeforeEach] Simple pod
22:21:51   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:164
22:21:51 STEP: creating the pod
22:21:51 Oct 17 22:21:51.311: INFO: Running '/jenkins-master-data/jobs/kubernetes-e2e-gce/workspace/kubernetes/platforms/linux/amd64/kubectl --server=https://104.197.126.242 --kubeconfig=/var/lib/jenkins/jobs/kubernetes-e2e-gce/workspace/.kube/config create -f /jenkins-master-data/jobs/kubernetes-e2e-gce/workspace/kubernetes/docs/user-guide/pod.yaml --namespace=e2e-tests-kubectl-gir7q'
22:21:51 Oct 17 22:21:51.550: INFO: pod "nginx" created
22:21:51 
22:21:51 Oct 17 22:21:51.550: INFO: Waiting up to 5m0s for the following 1 pods to be running and ready: [nginx]
22:21:51 Oct 17 22:21:51.550: INFO: Waiting up to 5m0s for pod nginx status to be running and ready
22:21:51 Oct 17 22:21:51.555: INFO: Waiting for pod nginx in namespace 'e2e-tests-kubectl-gir7q' status to be 'running and ready'(found phase: "Pending", readiness: false) (4.609569ms elapsed)
22:21:53 Oct 17 22:21:53.558: INFO: Wanted all 1 pods to be running and ready. Result: true. Pods: [nginx]
22:21:53 [It] should support exec through an HTTP proxy
22:21:53   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:378
22:21:53 STEP: Finding a static kubectl for upload
22:21:53 Oct 17 22:21:53.558: INFO: No kubectl in /var/lib/jenkins/jobs/kubernetes-e2e-gce/workspace/platforms/linux/386/kubectl. Attempting a local build...
22:21:53 [AfterEach] Simple pod
22:21:53   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:167
22:21:53 STEP: using delete to clean up resources
22:21:53 Oct 17 22:21:53.559: INFO: Running '/jenkins-master-data/jobs/kubernetes-e2e-gce/workspace/kubernetes/platforms/linux/amd64/kubectl --server=https://104.197.126.242 --kubeconfig=/var/lib/jenkins/jobs/kubernetes-e2e-gce/workspace/.kube/config stop --grace-period=0 -f /jenkins-master-data/jobs/kubernetes-e2e-gce/workspace/kubernetes/docs/user-guide/pod.yaml --namespace=e2e-tests-kubectl-gir7q'
22:21:53 Oct 17 22:21:53.765: INFO: pod "nginx" deleted
22:21:53 
22:21:53 Oct 17 22:21:53.765: INFO: Running '/jenkins-master-data/jobs/kubernetes-e2e-gce/workspace/kubernetes/platforms/linux/amd64/kubectl --server=https://104.197.126.242 --kubeconfig=/var/lib/jenkins/jobs/kubernetes-e2e-gce/workspace/.kube/config get rc,svc -l name=nginx --no-headers --namespace=e2e-tests-kubectl-gir7q'
22:21:53 Oct 17 22:21:53.962: INFO: 
22:21:53 Oct 17 22:21:53.962: INFO: Running '/jenkins-master-data/jobs/kubernetes-e2e-gce/workspace/kubernetes/platforms/linux/amd64/kubectl --server=https://104.197.126.242 --kubeconfig=/var/lib/jenkins/jobs/kubernetes-e2e-gce/workspace/.kube/config get pods -l name=nginx --namespace=e2e-tests-kubectl-gir7q -o go-template={{ range .items }}{{ if not .metadata.deletionTimestamp }}{{ .metadata.name }}{{ "\n" }}{{ end }}{{ end }}'
22:21:54 Oct 17 22:21:54.166: INFO: 
22:21:54 [AfterEach] Kubectl client
22:21:54   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:96
22:21:54 STEP: Destroying namespace for this suite e2e-tests-kubectl-gir7q
22:21:59 
22:21:59 • Failure [9.881 seconds]
22:21:59 Kubectl client
22:21:59 /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:932
22:21:59   Simple pod
22:21:59   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:442
22:21:59     should support exec through an HTTP proxy [It]
22:21:59     /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:378
22:21:59 
22:21:59     Oct 17 22:21:53.558: Can't build static kubectl due to missing hack/build-go.sh. Error=stat /var/lib/jenkins/jobs/kubernetes-e2e-gce/workspace/hack/build-go.sh: no such file or directory
22:21:59 
22:21:59     /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:239

**Comment by jlowdermilk** [comment]
@ashcrow, sorry the path it's looking for is the problem. The e2e tests are run from a workspace directory that contains the kubernetes directory, not from the kubernetes dir itself.
```
22:21:53 STEP: Finding a static kubectl for upload
22:21:53 Oct 17 22:21:53.558: INFO: No kubectl in /var/lib/jenkins/jobs/kubernetes-e2e-gce/workspace/platforms/linux/386/kubectl. Attempting a local build...
```

So in the above it should be looking for `kubernetes/platforms/linux/386/kubectl`.

That being said, the kubectl version that most people use is the default, and if exec through an http proxy is a supported feature, it should work for the standard kubectl build. So really, we should just switch kubectl to a static build.

**Comment by ncdc** [comment]
@jlowdermilk a static kubectl build isn't required to do exec+proxy; it's required to run the e2e test for it, as we're running kubectl in a pod as part of the e2e test. I don't have any strong feelings one way or another to change the standard kubectl build from dynamic to static. If no one objects, however, changing the build to static will make the hoops we're going through to get an e2e test working go away.

**Comment by jlowdermilk** [comment]
If the static build is a test requirement only, then it's reasonable to use the static `linux/386/kubectl`
Fix should be to change the load path [here](https://github.com/kubernetes/kubernetes/pull/15787/files#diff-540d8a63e8b72b4e05dda54ae37f77d2R232) to
```
testStaticKubectlPath := path.Join(testContext.RepoRoot, "platforms/linux/386/kubectl")
```

**Comment by ncdc** [comment]
Ok, cool. Do we know yet why the "Jenkins GCE e2e" test passed but other GCE test environments failed?

**Comment by jlowdermilk** [comment]
@ncdc (and @fabioy, @quinton-hoole for fyi): the reason this passed on the pr builder (i.e. the presubmit check) and not other gce test environments is due to differences in the test environment:
- pr builder pulls and checks out the kubernetes repo and runs test from repo root (`kubernetes/`)
- other test environments pull a pre-built kubernetes release, then extract it and run test from a workspace directory that *contains* the `kubernetes/` repo root.

I think the lesson here is that e2e tests should only use `testContext.RepoRoot` when loading files that live under the `kubernetes/` directory.

**Comment by ashcrow** [comment]
@jlowdermilk I'm still trying to wrap my head around how this occured. Is this a third case from the two test envs tested in https://github.com/kubernetes/kubernetes/pull/15787?

**Comment by jlowdermilk** [comment]
@ashcrow, no it's not a third case, we were just missing a directory in the path to `platforms/linux/386/kubectl`. #15787 told the test to load `workspace/platforms/linux/386/kubectl`, but instead it should have been loading `workspace/kubernetes/platforms/linux/386/kubectl`. I suggested the one-line fix to make #15787 do the right thing [up above](https://github.com/kubernetes/kubernetes/issues/15848#issuecomment-149294712).

**Comment by ashcrow** [comment]
@jlowdermilk ok I think I follow now. Thanks!

**Comment by ihmccreery** [comment]
@fabioy Is there more to do here?  Do we need to put checks in place to prevent this from happening again?  And/or can we knock it down from `P0`?

**Comment by jlowdermilk** [comment]
I think we can close this. The reason #15787 got merged and broke e2e is that it added a test that made assumptions about the test environment that only hold when running from a kubernetes git repo (pr builder runs test from checked out repo, the continuous e2e tests download and extract release tars). We'll avoid doing that in the future.
