### ISSUE TITLE
GIT Not In Path (hyperkube:v1.0.1)

### ISSUE THREAD

**Issue by nVitius** [kubernetes/kubernetes#15855]
I'm running Kubernetes under Docker (following [this](https://github.com/kubernetes/kubernetes/blob/master/docs/getting-started-guides/docker-multinode/master.md) guide). I tried to set up an RC that would run a registry:2 container and attach a gitRepo volume with the SSL certs I want to use. When I run it though, I get this error: 
 `Error syncing pod, skipping: failed to exec 'git clone git@gitrepo': : exec: "git": executable file not found in $PATH`  
If k8s supports git repositories as volumes though, it feels like the executable should be included in the container.

**Comment by jlowdermilk** [comment]
k8s supports git repositories as volumes but it's an optional feature that not everyone wants, so it would not be appropriate to require/include the git executable. This is similar to how k8s supports nfs volumes, but we don't require you to run the kubelet on an os with nfs kernel support, because not everyone wants it.

**Comment by nVitius** [comment]
Hmm. Okay, that makes sense. Would it be feasible to create tags for those containers that have git?

**Comment by jlowdermilk** [comment]
@nVitius, I think I misunderstood the request. I think it's actually reasonable to add git to hyperkube, since afaict, it's only used for single node docker. The Dockerfile is [here](https://github.com/kubernetes/kubernetes/blob/b9cfab87e33ea649bdd13a1bd243c502d76e5d22/cluster/images/hyperkube/Dockerfile), feel free to send a pr.
