### ISSUE TITLE
Logs not showing up in Google Logs

### ISSUE THREAD

**Issue by ansgarstrother** [kubernetes/kubernetes#15949]
Following the instructions here:
http://kubernetes.io/v1.0/docs/getting-started-guides/logging.html

kubectl get pods --namespace=kube-system
NAME                                                READY     STATUS    RESTARTS   AGE
fluentd-cloud-logging-gke-lite-7b2390f5-node-74cc   1/1       Running   0          18h
fluentd-cloud-logging-gke-lite-7b2390f5-node-tp7d   1/1       Running   0          18h
fluentd-cloud-logging-gke-lite-7b2390f5-node-yylw   1/1       Running   0          18h
kube-dns-v8-cz2lo                                   4/4       Running   0          18h
kube-ui-v1-ys0ze                                    1/1       Running   0          18h
monitoring-heapster-v6-1w4iv                        1/1       Running   0          18h

kubectl create -f examples/blog-logging/counter-pod.yaml
pods/counter

kubectl logs counter
0: Tue Oct 20 13:39:18 UTC 2015
1: Tue Oct 20 13:39:19 UTC 2015
2: Tue Oct 20 13:39:20 UTC 2015
3: Tue Oct 20 13:39:21 UTC 2015
4: Tue Oct 20 13:39:22 UTC 2015
5: Tue Oct 20 13:39:23 UTC 2015

All good except when I go to my logging section in google cloud I don't get to select counter. The option is not avaiable nor do I see any logs from it. 

![screen shot 2015-10-20 at 9 41 11 am](https://cloud.githubusercontent.com/assets/2294085/10608841/d852118e-770e-11e5-96f8-4f7c40c263e2.png)

I double checked and cloud logging is enabled:
![screen shot 2015-10-20 at 9 45 23 am](https://cloud.githubusercontent.com/assets/2294085/10608950/63019002-770f-11e5-89e3-5f973ddefcdc.png)

Thanks for the help!

**Comment by jlowdermilk** [comment]
Please re-post your question to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes). 

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases. 

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to similar questions, and also familiarize yourself with:
   * [the user guide](http://kubernetes.io/v1.0/)
   * [the troubleshooting guide](http://kubernetes.io/v1.0/docs/troubleshooting.html)

Again, thanks for using Kubernetes.

The Kubernetes Team
