### ISSUE TITLE
kubectl should support ingresses

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#16070]
Forked from #15578

kubectl uses "ingress" for both singular and plural for the ingress resources, whereas it uses plural forms for everything except endpoints AFAIK.

kubectl should support both ingress (singular) and ingresses (plural). At least the following places need to be updated:

https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/kubectl.go#L111
https://github.com/kubernetes/kubernetes/blob/master/pkg/api/meta/restmapper.go#L145

cc @bprashanth @thockin

**Comment by bgrant0607** [comment]
I believe we should special-case endpoints here instead of status:
```
	if strings.HasSuffix(singular, "status") {
		plural = singular + "es"
```

cc @kubernetes/kubectl

**Comment by bgrant0607** [comment]
@derekwaynecarr Does OpenShift have any resource types ending with `s`?

**Comment by thockin** [comment]
Agree ingresses is as correct as ingress.

**Comment by JanetKuo** [comment]
If we're changing the plural of "ingress" to "ingresses" we need to change its resource name from "ingress" to "ingresses" too. 
https://github.com/kubernetes/kubernetes/blob/master/pkg/client/unversioned/ingress.go (and many other places)

It's because we use plural as resource name. See
https://github.com/kubernetes/kubernetes/blob/master/pkg/api/meta/restmapper.go#L130
https://github.com/kubernetes/kubernetes/blob/master/pkg/api/meta/restmapper.go#L227

The easiest way to support ingresses is adding `"ingresses": "ingress"` to `shortForms`. This way, we don't need to change the resource name. 
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/kubectl.go#L111

**Comment by smarterclayton** [comment]
We don't have any today.  RESTMapper exists to serve generic clients, however, that predates API discovery, at which point resources should be provided by the server and pluralization should be rule driven (and as Janet notes we can simply use heuristics on user input to locate resources based on rules - if "ingress" isn't found, "ingresses" could be).

**Comment by thockin** [comment]
From a consistency pov, you're right.  The URL path should be in
ingresses.  @bprashanth objections?

**Comment by bgrant0607** [comment]
@JanetKuo will fix the URL path and kubectl.
