### ISSUE TITLE
Overhaul kubectl help

### ISSUE THREAD

**Issue by RichieEscarez** [kubernetes/kubernetes#16089]
The new "[kubectl overview](https://github.com/kubernetes/kubernetes/blob/master/docs/user-guide/kubectl-overview.md)" document has been created and contains edits of all the kubectl descriptions (all technically reviewed/accurate).

We should push these updated/improved descriptions into the individual commands so that they also show up in the terminal and the topics generated for the commands.

(1)
In this file:
[md_docs.go](https://github.com/spf13/cobra/blob/master/md_docs.go) in [cobra](https://github.com/spf13/cobra)
We should update the section titles to replace:
- the references to "Options" and "Options inherited..." with the term "Flags" and "Flags inherited..." so its consistently referred to across the commands (ie. they all refer to "flags"):
- "SEE ALSO" with something more accurate like "Related commands"

(2+)
In the files in the https://github.com/kubernetes/kubernetes/tree/master/pkg/kubectl/cmd directory, the corresponding kubectl files should be updated to contain all the revised descriptions that we have put the new "[kubectl overview](https://github.com/kubernetes/kubernetes/blob/master/docs/user-guide/kubectl-overview.md)".

@JanetKuo @bgrant0607 @jlowdermilk

**Comment by bgrant0607** [comment]
We also should link from the overview to the generated reference docs.

**Comment by bgrant0607** [comment]
Using this issue as a broader umbrella issue.

In general, kubectl --help could use a lot of improvement. 

* Out of date: RC help still refers to a v1beta1 field, which was removed almost a year ago.
* Best practices: Most help shows json rather than yaml. 
* Consistency: The commands shown are inconsistent across commands.
* Relevant: Help doesn't necessarily reflect the most common scenarios. 
* Navigation: Help doesn't suggest alternative or more appropriate commands. Help doesn't direct users to the right resource types. No/few links to online documentation.
* Search: Synopses sometimes don't contain critical words that would help users find the right option. 
* Complete usage: Help doesn't indicate which resource types are valid for each command. Resource lists that do exist are hardcoded and not complete.
* Organization: Flags, commands, and resource types are presented in insufficiently organized flat lists.

See also #7496, #15741, #19736, #23402

Also see the brainstorming doc:
https://docs.google.com/document/d/1tPrTL5Fi8BjlIK_XwNz-W260ll2ZYflrdbtnwE1PQoE/edit#

cc @kubernetes/kubectl

**Comment by janetkuo** [comment]
#25290

**Comment by kargakis** [comment]
@kubernetes/sig-cli-misc

**Comment by eddiezane** [comment]
kubectl docs and help has been improved since this issue was opened.

We're more than happy to merge future improvements and don't need a lingering issue for this.

/close
