### ISSUE TITLE
Published local docker getting started guide is quite out of date

### ISSUE THREAD

**Issue by roberthbailey** [kubernetes/kubernetes#16087]
http://kubernetes.io/v1.0/docs/getting-started-guides/docker.html

References using kubernetes 0.21.2. The version at head (https://github.com/kubernetes/kubernetes/blob/master/docs/getting-started-guides/docker.md) shows 1.0.6. The published docs for 1.0 should show 1.0.6 because that is that latest supported release version on the 1.0 release branch. 

I think we can fix this by cherry picking the changes to that doc onto the release branch, but @RichieEscarez would know for sure. 

/cc @brendandburns

**Comment by bgrant0607** [comment]
Annoyingly, the 1.1 docs use 1.0.1. We need to munge these references, similar to links to version-specific docs.

**Comment by davidopp** [comment]
@fgrzadkowski can you take a look at this? I noticed it because it's marked for 1.2 milestone but didn't have an assignee. Obviously this can be done after the feature complete deadline.

**Comment by fgrzadkowski** [comment]
@davidopp Sure, I'll take a look. Recently @luxas made a lot of improvements (I reviewed some of them), so I think it's pretty up-to-date, but I'll double check.

**Comment by fgrzadkowski** [comment]
I've checked the docs and:
* Documentation linked by @roberthbailey is indeed outdated, but it's for `v1.1` and most of the changes/simplifications that we did require some code changes which were not cherry-picked
* Once we release `v1.2` they should be up-to-date

At the same time I think we should use there image versions like `:latest_alpha` or `:latest_stable` so that they are always up-to-date. I'll file a separate issue for this.
