### ISSUE TITLE
Don't log/event when killing the pause container

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#16091]
When a pod exits, the pause container is killed, which generates an event like
`Killing with docker id ba4f4f254103` which serves only to confuse when viewing event logs.

the killContainer function should be modified to not generate an event or other logs (except at high verbosity, maybe) when killing a pause container.  pause containers are a detail that users should not be exposed to.

**Comment by jiangyaoguo** [comment]
If we remove killing event of pause container, do we should remove creating event also?

**Comment by erictune** [comment]
yes

**Comment by dchen1107** [comment]
Removing event when killing the pause container is good because pause one is a hidden container, and shouldn't be user visible. But we should introduce a new event upon network configure is changed, and kubelet restart the entire pod by killing pause container here for introspection. Otherwise the user will confuse why kubelet restart pause container and trigger all user containers are restarted.

**Comment by zhengguoyong** [comment]
Dose anybody start working on this?

**Comment by jiangyaoguo** [comment]
@zhengguoyong I'm working on a event change pr refer to this.
