### ISSUE TITLE
Shared PID and UTS namespaces

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#1615]
Assuming https://github.com/docker/docker/pull/8211 goes in, we should decide whether we want containers within a pod to share IPC namespaces by default (which fits the "logical host" model for pods and keeps the API simple at the cost of slightly reduced isolation), or provide an option (in which case we could wait until users ask for it).

/cc @thockin

**Comment by mrunalp** [comment]
I would be interested in helping drive this forward by submitting PRs. Has the docker build been updated to include the --ipc feature?

**Comment by thockin** [comment]
I think nobody is working on this, so have at it.  At least GCE uses docker
1.4.1.

I think we have a bug in the docker names we build - if a user specifies a
container named "net" there will be something of a conflict.  Once we add
IPC it's not longer "net" any more but "pod".  Maybe we need a new field in
the docker name [yay :( longer] to disambiguate

**Comment by mrunalp** [comment]
@thockin Just starting to work on this. Any suggestions for docker name?

**Comment by vishh** [comment]
@mrunalp: Unassigned myself since you are working on this. Feel free to reach out if I can be of any help!

**Comment by thockin** [comment]
Let's not add a new field in the name.  Maybe change:

```
        networkContainerName  = "net"
        NetworkContainerImage = "kubernetes/pause:latest"
```

to 

```
       PodInfraContainerName  = "POD"  // caps are not allowed by users, but are OK for docker.
       PodInfraContainerImage = "kubernetes/pause:latest"
```

**Comment by mrunalp** [comment]
@thockin That sounds good to me. 
BTW, go-dockerclient doesn't have support for specifying IpcMode, so I will take a detour to go fix that first.

@vishh Thanks! I will ping you if I need any help.

**Comment by mrunalp** [comment]
https://github.com/fsouza/go-dockerclient/pull/205

**Comment by mrunalp** [comment]
I have started making the changes cherry picking the go-dockerclient change while we are waiting for that to get merged. Hopefully will have some basic testing done by end of day today.

**Comment by mrunalp** [comment]
Created a PR for updating go-dockerclient #3726. Next thing that's blocking me is Fedora 20 not having a recent enough docker package, so I can't test my changes on vagrant setup. I am working with Fedora packaging folks to get that fixed.

**Comment by mrunalp** [comment]
Created a PR #3817

**Comment by erictune** [comment]
@mrunalp @thockin Was this issue closed by #3817?  Seems like it was, but I see @bgrant0607 adding help-wanted to it.

**Comment by thockin** [comment]
I think it is fixed

**Comment by bgrant0607** [comment]
https://github.com/docker/docker/issues/10163 hasn't even been done on the Docker side yet.

**Comment by bgrant0607** [comment]
We still don't share UTS.

**Comment by bgrant0607** [comment]
cc @ArtfulCoder

**Comment by onorua** [comment]
BTW, shared PID namespace with the POD is really good idea for Java based applications with memory leak protection. As you might know, Linux kernel doesn't allow -9 signal to be send to PID 1 process, even if it's inside separate namespace. So, in case java app is doing OOM `kill -9`, it will be ignored. If we share PID namespace with POD container, we will have PID 1 as the "sleep" process, and the rest will have PID != 1, which perfectly solves the issue.

**Comment by erictune** [comment]
@onorua I can see how it would be a good idea to run a process other than java as PID 1 (e.g. `bash -c  'java'` instead of `java`).  

But I think this problem exists for systems without Pods too.  So I'm not sure it should influence the design of Pods.

related to @onorua issue: https://blog.phusion.nl/2015/01/20/docker-and-the-pid-1-zombie-reaping-problem/).

**Comment by vishh** [comment]
Linux treats Pid 1 specially. [Here](http://engineeringblog.yelp.com/2016/01/dumb-init-an-init-for-docker.html) is one way to solve it. As @erictune mentioned it is not an issue with the pod concept.

**Comment by onorua** [comment]
I merely telling that with sharing PID namespace we could have PID1 problem solved. I'm aware how to run command with PID2, but I do not like to reinvent the wheel if it can be easily done by default.
Not to mention that it opens new possibilities for sidecar monitoring containers.

**Comment by thockin** [comment]
Nobody is against shared PID, we just need to make time to implement it in
Docker, or get someone who has time.  Got any free time? :)

**Comment by dchen1107** [comment]
I punt this one to next release unless someone got some free time helping this issue within 1.2 release timeline.

**Comment by nickethier** [comment]
Really excited about this feature so I followed the chain of issues down the rabbit hole.

Shared PID namespaces depends on the following tree:
  * docker/docker#10163
    * docker/docker#13453
      * opencontainers/runc#105 or opencontainers/runc#454

The runc changes are tagged with milestone `0.1.0` which is scheduled for the end of March.

**Comment by estesp** [comment]
@nickethier runc 454 is merged, an after fixing up some userns problems, I have a PR open to vendor that update into Docker (docker/docker#20956).  Then work can continue on docker/docker#13453 to surface that to callers with options for PID namespace sharing.

**Comment by vishh** [comment]
If we share the PID namespace, we need a long running init, that is not tied to the lifetime of the containers themselves. We could possibly re-purpose the pause container as an init. But, that might break docker containers that depends on the entrypoint being init.

**Comment by thockin** [comment]
yeah, this is something that needs pretty careful thought.  Being able to
signal within a pod is pretty powerful, but the pid-1 problem is a real
pain.

**Comment by yifan-gu** [comment]
> If we share the PID namespace, we need a long running init, that is not tied to the lifetime of the containers themselves. We could possibly re-purpose the pause container as an init. But, that might break docker containers that depends on the entrypoint being init.

@vishh How is this going to work with `Pod.SecurityContext.HostPID = true`?

**Comment by vishh** [comment]
@yifan-gu All the containers would be part of the host pid namespace?

**Comment by onorua** [comment]
@vishh if POD "pause" will be doing "init" function, doesn't it mean that "pause" process will try to take over processes supposed to be taken by host init already due to host pid namespace, which may cause unpredictable behavior as a result?

**Comment by vishh** [comment]
I don't think we want pause to be an init and that was my point.

**Comment by thockin** [comment]
I'd be fine with pause being an init.  I am more concerned about what
happens to containers that have their own micro-init when they are not
actually pid1 any more.

**Comment by yujuhong** [comment]
> I'd be fine with pause being an init.  I am more concerned about what
> happens to containers that have their own micro-init when they are not
> actually pid1 any more.

What does the micro-init typically do? If "pause" handles signals and reaping the orphaned zombie processes, would that be enough?

**Comment by thockin** [comment]
signal propagation and wait()ing are the two that jump to mind, but there
are a bunch of docs on this

https://blog.phusion.nl/2015/01/20/docker-and-the-pid-1-zombie-reaping-problem/

**Comment by yujuhong** [comment]
@thockin, those are the two that I mentioned, and was most commonly seen among the micro inits. I was just wondering what other features that users want from these inits :)

**Comment by thockin** [comment]
I think most users don't want to think about it :)

**Comment by vishh** [comment]
Running our own `init` will open up many possibilities. I'm concerned about cross runtime compatibility though.

**Comment by vishh** [comment]
cc @kubernetes/sig-node

**Comment by bgrant0607** [comment]
Pid 1 was discussed some in #23085.

https://github.com/Yelp/dumb-init
https://github.com/miekg/dinit
http://blog.dscpl.com.au/2015/12/issues-with-running-as-pid-1-in-docker.html?m=1

We need to ensure:
* Kubelet can get exit information (exit code, signal, OOM, etc.) from terminated containers/processes
* Kubelet can count container restarts
* postStart hooks can execute after every restart
* Signals are correctly propagated to the application

http://kubernetes.io/docs/user-guide/pods/#alternatives-considered

**Comment by Random-Liu** [comment]
FYI, docker will support pid namespace sharing in 1.12 https://github.com/docker/docker/pull/22481

**Comment by thockin** [comment]
nice!  We should use this as soon as we can

**Comment by bprashanth** [comment]
Ah, i thought i saw support for that in runc and was puzzled why it didn't work through docker. 
Shared pid namespace would help petset too. 
@kubernetes/sig-node can we get docker 1.12 in 1.3? :)

**Comment by Random-Liu** [comment]
@bprashanth I don't think so we could make it for 1.3. :(
Docker 1.12 is not out yet, and we've decided to go with docker 1.11.

**Comment by thockin** [comment]
I didn't mean 1.3 :)

**Comment by bprashanth** [comment]
BUT I DID
/me types up a kubernetes-dev email to discuss this

**Comment by yujuhong** [comment]
@bprashanth, discuss shared PID namespace in general or discuss supporting this in v1.3? I see no practical, actionable plans to support this in v1.3 unless we push the release.

Why do you want this feature so bad?

**Comment by bprashanth** [comment]
In the context of https://github.com/kubernetes/kubernetes/issues/24957. So i can signal a database to reload on cluster membership change, from a sidecar. Wrapping the databse in a custom pid1 is gross, and there's no way to say: just exec this command in the namespace of another container today.

I don't need it for 1.3, docker 1.12 isn't even out right :)

**Comment by IanLewis** [comment]
Sharing of PID namespaces is also necessary to help drive a nail into the coffin for those crazy Docker startup scripts. A lot of Docker images on Docker hub use scripts or process managers like supervisord or foreman in each container when the same functionality should be handled by the environment (Kubernetes) and sidecar containers in pods w/ shared namespaces.

I don't think enough developers think about this and support in Kubernetes would go a long way to help educate developers on how to build cleaner, more robust deployments.

I can't wait for this to be in Kubernetes so I can start talking about it.

**Comment by sashokkum** [comment]
We are also early awaiting the release of this feature. We are trying to implement IPC between an app service container and a helper service container packaged into a single pod. Using Docker 1.10 and Kub 1.2.4 at present. 

Would this be part of Kub 1.4 ?

**Comment by jonboulle** [comment]
@sashokkum you could also try using [rktnetes](http://blog.kubernetes.io/2016/07/rktnetes-brings-rkt-container-engine-to-Kubernetes.html) which supports inter-app IPC today.

**Comment by sashokkum** [comment]
Thanks @jonboulle for the tip however, using CoreOS/rocket is not an option for us in prod. We are on Centos/Docker only

**Comment by verb** [comment]
Took me a while to track it down, so making a note here. Reparenting in shared PID namespace is broken in docker 1.12, @thockin opened docker/docker#25348 which led to opencontainers/runc#971

I expect a side effect of this bug is that zombies in the container are reaped by the host's init process, which would be wrong but convenient, but I haven't dug into it.

**Comment by verb** [comment]
FYI: after talking with @vishh it sounds like the first step towards a shared PID namespace is an Infra container that cleans up zombies. I'm going to start digging into this. Please wave me off if someone else is working on it.

I've noticed the 4 points above that @bgrant0607 wants to ensure. I'll reach out to SIG Node to discuss this and, in particular, compatibility of an infra container with current and future runtimes. In the particular case of docker, I'm also curious how docker chooses which processes to signal with stop/kill.

I think this is probably not complicated enough for a proposal, so if you have opinions on how an init infra container should look (e.g. whether to extend pause or create a second container option, should it be written in Go or C, etc) please let me know.

**Comment by vishh** [comment]
> I think this is probably not complicated enough for a proposal, so if you have opinions on how an init infra container should look (e.g. whether to extend pause or create a second container option, should it be written in Go or C, etc) please let me know.

Developing in `C` might be worth the maintenance overhead since the infra container is run for every single pod.

**Comment by IanLewis** [comment]
@verb @vishh Is there a reason why the pause container couldn't be PID 1 and clean up zombie processes? I thought that would be the most logical approach. Maybe the idea is that the pause container app itself could be written in C?

**Comment by verb** [comment]
@IanLewis After looking into it, that's what I did. Someone had already rewritten pause in C so I just added a handler for SIGCHLD. Now I just need to put together the PR.

**Comment by verb** [comment]
We talked about shared PID namespace in the sig-node meetup today. Long term, sig-node would like to design an init solution that works for all runtimes, but in the short term we're going to proceed with this docker-specific solution.

There was some concern about backwards compatibility, so I'm going to write a short doc proposing a rollout plan to change the default behavior.

**Comment by verb** [comment]
@vishh pointed out that we'll have to make sure that restarts to the infra container restart all of the other containers in the pod first so that it will regain PID 1. (mentioning here for tracking)

**Comment by verb** [comment]
We discussed this a little more in SIG Node today and general agreement was that we should make shared PID namespace a general requirement of the CRI. It's unlikely that docker >= 1.12 will see much use prior to a switchover to the CRI, so we're not going to implement it in the legacy dockertools runtime.

**Comment by verb** [comment]
I just noticed that if you kill the container that's the source of the pid namespace then all other containers sharing that namespace are also killed. So restarting the non-infra containers may be less of an issue, at least for docker.

Actually, I think this might be encapsulated in the sandbox design. Will have to dig into that later.

**Comment by vishh** [comment]
The "infra" container might have to become an entity that we want all
runtimes to support.

**Comment by verb** [comment]
#41583 added initial support for shared PID for docker

**Comment by verb** [comment]
Do we want to pursue sharing UTS?

**Comment by dims** [comment]
@verb don't know if things have changed, last time i went down the pid namespace stuff in https://github.com/kubernetes/kubernetes/pull/29677 ended up with this problem - https://github.com/opencontainers/runc/issues/971 and have been watching https://github.com/opencontainers/runc/pull/976 since then

**Comment by verb** [comment]
@dims yes, afaik it's still the case that the host's init is reaping zombies for the first process using a shared namespace.

**Comment by gjcarneiro** [comment]
Are you guys sure this is not implemented already?!  Because I am running 5 containers in a single pod, with kubernetes 1.7.2, and `ps ax` shows all the processes running, with process ID 1 being a pause container:
```
root@web-server-devbox-2395550446-30bhz:/code# ps ax
  PID TTY      STAT   TIME COMMAND
    1 ?        Ss     0:00 /pause
    7 ?        Ss     0:00 /bin/sh -c /usr/local/bin/statsrelay
   13 ?        S      0:00 /usr/local/bin/statsrelay
   14 ?        Ss     0:00 gunicorn: master [molly.web.wsgi]
   20 ?        Ss     0:00 nginx: master process nginx -g daemon off;
   26 ?        S      0:00 nginx: worker process
   29 ?        Sl     0:18 gunicorn: worker [molly.web.wsgi]
   40 ?        Ssl    0:00 env/bin/python3 /code/__main__.py --port 9081 --smtp-
   51 ?        Ss     0:00 nginx: master process nginx -c /code/nginx.conf
   57 ?        S      0:00 nginx: worker process
   58 pts/0    Ss     0:00 bash
  104 pts/0    R+     0:00 ps ax
root@web-server-devbox-2395550446-30bhz:/code# 
```
How to explain this unless shared PID namespaces are already implemented?  Or is it a side-effect of running with docker 17.06?

**Comment by verb** [comment]
@gjcarneiro it is implemented and enabled when running docker >= 1.13.1.
That version of docker has not been fully qualified for use with 1.7, but
there's nothing stopping you from using it. Let us know how it works!

**Comment by gjcarneiro** [comment]
Ah, thanks for the update!  Shouldn't this bug be closed then?...  Is it because docker 1.13.1 is also not fully qualified for use with 1.7 yet?
I'm using Docker 17.06 with Kubernetes 1.7.2, but it's only on my development desktop, not in production.  Still, working great so far...

**Comment by verb** [comment]
Yes, maybe it should be closed. The issue is also for sharing the UTS
namespace, but I don't think anyone is working on that.

**Comment by Fullmetal8ender** [comment]
Hi. Does docker.kubernetes.io/shared-pid annotation works?
I add
```
  annotations:
    docker.kubernetes.io/shared-pid: "True"
```
but this is not working. (minikube v0.21.0 with docker 1.12.6)

if not:
Is it possible to:
- enable shared pid namespace manually (to work with docker 1.12.6)?
- disable shared pid namespace manually with docker >= 1.13.1?

**Comment by verb** [comment]
No, this cannot be controlled by annotation. Docker 1.12.x doesn't support
shared pid and it cannot be enabled. For >= 1.13.1 the behavior can be
disabled with a kubelet flag, but not per pod.

**Comment by verb** [comment]
FYI, #51634 reverted this shared PID behavior for 1.8. Shared PID namespaces will be disabled unless enabled with a kubelet flag.

**Comment by smarterclayton** [comment]
From an API compatibility perspective, given that shared PID is a change that can break applications, it needs to be opt in at the Kube API level, not at the kubelet level.  We have balked at changing things like DNS (breaks apps silently) so I don't know why shared Pid would be any different.

**Comment by smarterclayton** [comment]
I don't see how the default can be changed without the app signaling its desire for shared PID.  And even then, given the security implications of shared PID, it seems more correct that someone has to opt in to sharing PID across all containers (which is another API change).

Concrete example: I have a script in my container that iterates through all PIDs and sends sigterm.  Today, that only kills the container.  Given pod shared PID namespace, that would terminate all pods.  That to me is a breaking change in the behavior of a pod and has to be opt-in, not opt-out.

**Comment by verb** [comment]
@smarterclayton are you interested in how we got here or where we're going now? (real question, it might be worth a retrospective.)

How we got here: the different thing about this change is sharing namespaces between containers in a pod is fundamental to the concept of a pod and I suspect the only reason the PID namespace wasn't shared previously is that docker didn't support it. Other runtimes do, and they share PIDs, aiui. Most importantly, there's **nothing inherent to sharing the PID namespace that would break containers**. The only reason it mattered is that systemd requires a specific combination of flags to run in system mode when its pid isn't 1, and no one predicted that behavior.

Re: your example, is that fabricated or has a real container image made that assumption? If we're going to hold changes to the standard of a fabricated counter-example, then we're never going to change anything because someone will always be able to fabricate an assumption that's broken by a change. Shared PID was enabled for a unqualified docker runtimes in 1.7 and during 1.8 alpha, and so far I've seen 1 report of a broken image, for a container to run _sshd_ & _ntpd_.

Here's why I'm asking (and segue to where are we going): I want to design a solution to enable this per-pod in 1.9 and I'm conflicted about whether this is something Kubernetes should support forever (as part of the API) or as a migration path (e.g. with annotations). I'm skeptical that hiding PIDs between containers within a pod is providing any practical security benefit. Thoughts?

**Comment by smarterclayton** [comment]
> How we got here: the different thing about this change is sharing namespaces between containers in a pod is fundamental to the concept of a pod

I don't think so.  It's implicit, but our goal is not "we must allow all sharing".  And even if that were the case, we have 8 releases under our belt where we have explicitly run workloads as unique PID, and so any philosophical justification is weighted much less than the compatibility of those workloads in real environments.

My example is real - I'm aware of at least 3 production workloads running at scale that various parts of the real world use to conduct business transactions that depend on PID 1 semantics and would be broken if we silently rolled this change out.

We do not break compatibility of running pods - that has always been our position.  Any change to their runtime behavior that has a measurable effect must be opt-in. There is no difference between strict API backwards compatibility and strict runtime compatibility.  There is a reasonable argument to make that broken things can be fixed (so the policy is not absolute), but there is absolutely a measurable difference for container workloads between shared PID and non-shared PID, and that needs to go through API and stability review, and the change needs to justify its "fixedness" vs its "brokenness".  The bar we have always set for ourselves is very high in terms of preserving compatibility, so it's pretty surprising to me that we would even consider changing this default.

The security angle could be discussed, but it's perfectly possible today to run two containers in a pod that are completely isolated that is at least as good as two pods on the same system.  SELinux, user UID, mount separation, and pid separation create a pretty darn good wall.

I'm open to coming with ways that make this easy to migrate to and consume (that preserve some future path) but that path needs much more attention paid to compatibility than apparently has to this point.

**Comment by gjcarneiro** [comment]
FWIW, I kind of agree with @smarterclayton wrt stability and backward compatibility.  But I disagree on security.  For isolating containers in different security contexts you should at least put them in separate pods. Expecting two containers in the same pod to have good security isolation is not a reasonable requirement IMHO.

For backward compatibility, it is safest to have this turned off by default, sure.  However, if we want shared PIDs to be always turned on in the future, and not even be an option (because why would this need to be an option, more options = more complexity), then the brave thing to do is to have this be turned on by default at some point in time, and have a per pod option to turn it.  This way developers can can start testing it progressively, as opposed to a cluster-wide option which no one will ever be brave enough to turn on for testing since it can break so many things.

**Comment by smarterclayton** [comment]
> Expecting two containers in the same pod to have good security isolation is not a reasonable requirement IMHO. 

We've designed for this at various points in Kube lifecycle.  We have never said that "sub pod container security is our highest priority" but there are many legitimate reasons to isolate two roles within the same pod.  I'd say right now we have very good isolation, so I'm loathe to simply regress to "ha no security" without some discussion.

>  is to have this be turned on by default at some point in time, and have a per pod option to turn it

I think we cannot enable this globally without breaking existing apps.  I think per pod option is the only reasonable course that preserves the API guarantees of the v1.Pod.  It would be totally reasonable for PSP and PodPresets to default this to on in some environments.  I would prefer to handle "enable for a wide range of apps" by having PodPreset or similar handle this, rather than doing it at the Kubelet level.

**Comment by verb** [comment]
> My example is real - I'm aware of at least 3 production workloads running at scale that various parts of the real world use to conduct business transactions that depend on PID 1 semantics and would be broken if we silently rolled this change out.

That's understandable. I was just surprised by a script that iterates and sends TERM to every pid (relevant xkcd: https://xkcd.com/1172/).

We discussed this in yesterday's sig-node meeting and agreed to implement first class support for configurable PID namespace in both v1.Pod and the CRI. I'm planning to propose a per-pod boolean setting (i.e. this pod either has a shared PID namespace or doesn't) rather than per-container configuration. If anyone has a requirement for per-container configuration please let me know, but I'd prefer to keep it simple if we can.

**Comment by ibotty** [comment]
I have an application that needs ephemeral host local storage (it uses emptyDir) with that need.

There are three containers in the pod that would like to communicate via signals to each other (but don't, because of that issue here) (running as random uid) and one container running openssh (as uid=0). openssh and the other containers only share a mount point, nothing else. It would be a security regression, if openssh shares the same pid namespace to the other pods.

I don't know, if that's enough of a usecase.

**Comment by verb** [comment]
@ibotty maybe it is, let's see what the others thing. Would it be sufficient for security to drop CAP_KILL in the openssh container so sshd could see the processes but not signal them?

The only prior art I see is host pid namespace, which is configurable per-pod rather than per-container.

**Comment by smarterclayton** [comment]
We're right in the middle on "per container vs per pod" and
historically leaned slightly towards per pod.

However, I think sophisticated pod users *have* leveraged the
distinctions we allow per container (and in my mind, correctly).  We
created pods to decomplicate single machine scheduling and to address
usecases that required close, but not tight coupling between them.
Anyone who needs tight coupling is free to do so by running in the
same container.   But saying "to get per container security isolation"
you suddenly have to use pod affinity for coscheduling strikes me as
wrong and antithetical to pod as a concept.

I agree share pid namespace is a pod level setting.  I however also
think we're missing the actual usability improvement, which is the
container --init equivalent, which makes Linux software behave
predictably.  If I had to guess, most of our users want *that* before
they need shared pid.  Saying the only way you can get --init is to
remove walls between containers may not be sufficient.

**Comment by ibotty** [comment]
@verb I guess so, but that still has to be per-container (because the others need it). I don't care for the information leak in _that_ case (`ps e` will contain any environment secrets!), but I can't claim I understand every attack vector that pid sharing allows.

**Comment by IanLewis** [comment]
To me it's not just providing --init but the ability to send signals to other containers in the same pod. Many applications communicate and provide maintenance functions this way (sending HUP signals to reload config, TERM signals to restart etc.). Not being able to send signals means that containers have to communicate over a shared volume or socket connection which really limits the composability of a pod. I'm imagining an app that watches anything like a Kubernetes object or git repo, and sends HUP signals to a main application.

**Comment by verb** [comment]
PID namespace sharing was included as an alpha feature in 1.10. It would be nice to coordinate its beta with removing the option to configure it in the kubelet (#41938), which we're planning to do in 1.12. This would leave 2 releases to gather feedback on the alpha.

Does anyone have any concerns they'd like to see addressed before promoting this feature to beta? In particular this is a question for @smarterclayton and @liggitt since it means committing to the API change.

**Comment by liggitt** [comment]
> Does anyone have any concerns they'd like to see addressed before promoting this feature to beta?

I don't have any issue with promotion... I primarily cared about maintaining compatible behavior, which the pod spec field did/does.

**Comment by yyb196** [comment]
@verb you said that "Docker 1.12.x doesn't support shared pid and it cannot be enabled" but i found that docker-1.12.0 has supported share pid name between containers. refer to https://github.com/moby/moby/pull/22481 . Is there a bug which stop we using it at veraion 1.12.x?
Any feedback will be appreciate.

**Comment by verb** [comment]
@yyb196 yes, have a look at https://github.com/kubernetes/community/pull/207#issuecomment-281870043

**Comment by verb** [comment]
Update: ShareProcessNamespace is graduating to beta in 1.12. I'll leave this issue open until GA.

/remove-lifecycle stale

**Comment by verb** [comment]
Shared PID namespaces was promoted to beta in the last release. afaik no one is working on configurable UTS namespaces. I guess these issues aren't intended to be long-lived, and I'm tired of fighting the bot, so I'll close this as fixed. Anyone wanting to track the feature further can follow kubernetes/enhancements#495.

/remove-lifecycle rotten
/close
