### ISSUE TITLE
self-contained Quantity type

### ISSUE THREAD

**Issue by crawshaw** [kubernetes/kubernetes#16172]
The api package uses a Quantity type to represent MB/GB/MiB/GiB/etc quantities. Right now it depends on an old version of a third-party infinite-precision decimal arithmetic package.

I believe it's possible to get the same effect with a type like:

```
type Quantity struct {
        base Format
        mant int64
        exp  int
}

type Format int

const (
        Base1000 Format = iota
        Base1024
)
```

...which would remove a lot of the sharp edges from inside its implementation. (And, one less dependency.) Would you accept a patch to do this?

@lavalamp, a random googler who seems to have touched this code recently

**Comment by thockin** [comment]
We're certainly open to simplifications...

**Comment by crawshaw** [comment]
Oh, I just realized I can't go get/test this package. And there are a lot of docs, but I can't find the ones that tell me how to run the tests. Can you point me at the instructions?

**Comment by lavalamp** [comment]
@crawshaw Why not just update the dec.Inf package dep?

Are you trying to use this package outside of Kubernetes?

You'll need to use the hack/test-go.sh script or `godep go test` to test the package.

IIRC, replacing inf.Dec with int64 is not OK for entire-cluster resource sizes, or we wouldn't have done it this way in the first place.

I am open to changes that improve it while not changing the semantics or interface, otherwise it will be a tough sell.
