### ISSUE TITLE
Failed Units: 2  (docker.service weave-create-bridge.service)

### ISSUE THREAD

**Issue by mreferre** [kubernetes/kubernetes#16355]
This issue is related to this provisioning workflow: https://github.com/kubernetes/kubernetes/tree/master/docs/getting-started-guides/coreos/azure 

The provisioning works fine but as soon as I login into the kube nodes (e.g. "ssh -F  ./output/kube_7d10e66148c601_ssh_conf kube-00") I constantly see this message:

CoreOS stable (647.2.0)
Update Strategy: No Reboots
Failed Units: 2
  docker.service
  weave-create-bridge.service

Subsequently there is no node being registered etc (obviously). 
If I login in into kube-01 and kube-02 there are more srvices that had failures: 

CoreOS stable (647.2.0)
Update Strategy: No Reboots
Failed Units: 4
  docker.service
  kubectl-create-minion.service
  weave-create-bridge.service
  docker.socket
 
If I login into the etcd nodes they don't show any error (Failed Units).
 
I have re-deployed the solution at least 10 times. The infrastructure provisioning always goes smooth but the issue above surfaces constantly inside the instances.

**Comment by lavalamp** [comment]
Please re-post your question to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes). 

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases. 

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to similar questions, and also familiarize yourself with:
   * [the user guide](http://kubernetes.io/v1.0/)
   * [the troubleshooting guide](http://kubernetes.io/v1.0/docs/troubleshooting.html)

Again, thanks for using Kubernetes.

The Kubernetes Team
