### ISSUE TITLE
Pods keeps in ContainerCreating status due to volume mount error

### ISSUE THREAD

**Issue by ddysher** [kubernetes/kubernetes#16367]
We've seen some API unavailability issues on our cloudprovider, which results in kubelet unable to post node status, as it tries to get node address from cloudprovider.  The outage went about 20min: enough for nodecontroller to mark node as not ready and evit all pods.

When kubelet sees pod deletion, it starts tearing down volume, the way I see how it works in current volume plugins is:
1. check if pod volume 'dir' is mount point or not, if not, delete the directory; otherwise go to 2;
2. unmount the volume;
3. detach the volume from cloudprovider;
4. make sure 'dir' is not mount point, and remove it.

There is an error in the logic. If detach volume fails (like in our case), kubelet will retry, but since we've already unmount the volume in 2, the second retry will just remove the dir without going deeper. The volume will remain on the host.

Another problem is that when cloudprovider comes back, scheduler re-schedules the pod to a node.  Kubelet tries to attach the volume but failed (because it was never detached!).  There is no Reason field, pod just keeps in `ContainerCreating` status forever.

**Comment by dchen1107** [comment]
cc/ @saad-ali

**Comment by saad-ali** [comment]
Volumes remaining attached to downed nodes, is a known issue. See https://github.com/kubernetes/kubernetes/issues/14642. We're working on a fix. See https://github.com/kubernetes/kubernetes/issues/15524. We've made some changes recently to make GCE PD attach/detach more robust. See https://github.com/kubernetes/kubernetes/pull/16053. But the best way to fix all the issues you mentioned will be to remove the attachment/detachment logic from kubelet.

I will close this issues for now since it sounds like it is captured by existing issues. However, if you feel the existing issues don't adequately address your concerns, please feel free to reopen.

**Comment by ddysher** [comment]
Existing issues focus on kubelet on downed node, but this issue is about the incorrect logic in kubelet. (The issue happens even if kubelet is running correctly).  I think it's possible to fix the logic in kubelet, but if there is a larger, clean solution, I would be great.

**Comment by saad-ali** [comment]
The decision to attach/detach a volume happens in two async loops in kubelet (pod creation and orphan volume cleanup), this leads to inherent race conditions that we've mitigated for GCE PDs by locking. The  downed node redesign, #15524, should fix this for all volume plugins, since it will remove the attach/detach logic from kubelet. If you think that there is a simple fixer in the meantime, feel free to send out a PR and I can take a look.

**Comment by Trane9991** [comment]
Still having the issue #29617

**Comment by saad-ali** [comment]
> Still having the issue #29617

That looks like a different issue. Replied to that issue.
