### ISSUE TITLE
Unable to mount flocker volume

### ISSUE THREAD

**Issue by Kaffa-MY** [kubernetes/kubernetes#16403]
I'm attempting to use flocker volume with ZFS. However, I find it cannot work well.
<pre>$ kubectl get po
NAME                 READY     STATUS              RESTARTS   AGE
frontend-5zpsj       1/1       Running             0          15h
frontend-ekk7a       1/1       Running             0          15h
frontend-mjv5q       1/1       Running             0          15h
kube-dns-vwh4p       3/3       Running             30         4d
redis-master-0qy2q   0/1       ContainerCreating   0          15h</pre>
Then, I look into the reason. It's reported that volume is not available, as follows.
<pre>$ kubectl describe po redis-master-0qy2q
Events:
  FirstSeen     LastSeen        Count   From                    SubobjectPath   Reason          Message
  ─────────     ────────        ─────   ────                    ─────────────   ──────          ───────
  15h           5s              5613    {kubelet 172.17.8.101}                  FailedMount     Unable to mount volumes for pod "redis-master-0qy2q_default": The volume 'redisdata' is not available in Flocker. You need to create this manually with Flocker CLI before using it.  
  15h           5s              5613    {kubelet 172.17.8.101}                  FailedSync      Error syncing pod, skipping: The volume 'redisdata' is not available in Flocker. You need to create this manually with Flocker CLI before using it.
</pre>
In fact, the volume has been created.
<pre>$ uft-flocker-volumes --user=user --control-service=172.17.8.100 list
DATASET                                SIZE     METADATA              STATUS         SERVER                  
e89425e1-11f7-427b-aa4f-217d8bd03eae   10.00G   name=my-flocker-vol   attached ✅   090ba570 (172.17.8.101) 
7750fee4-2936-4690-bbfb-36d6ed7432e4   10.00G   name=redisdata        attached ✅   090ba570 (172.17.8.101)</pre>
I tried many times, the volume was seldom mounted. How to solve the problem?

**Comment by lavalamp** [comment]
Please re-post your question to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes). 

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases. 

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to similar questions, and also familiarize yourself with:
   * [the user guide](http://kubernetes.io/v1.0/)
   * [the troubleshooting guide](http://kubernetes.io/v1.0/docs/troubleshooting.html)

Again, thanks for using Kubernetes.

The Kubernetes Team

**Comment by Kaffa-MY** [comment]
In fact, it's a bug in the flocker client which has out of date, it may fetch a deleted dataset and this dataset is not available.
