### ISSUE TITLE
Uneven kubelet memory usage in same cluster

### ISSUE THREAD

**Issue by rvrignaud** [kubernetes/kubernetes#16435]
I'm running a GKE cluster (master / nodes 1.0.6).
I'm seeing large memory usage variation between nodes from 60MiB to 340 MiB.
See following graph:

![screen shot 2015-10-28 at 15 27 39](https://cloud.githubusercontent.com/assets/525763/10793214/2664f7e2-7d90-11e5-9d85-c908964c5f38.png)

Here is the heap profiling of the kubelet using the more memory (gke-stg-b9e96ddd-node-9wfj):
![gke-stg-b9e96ddd-node-9wfj](https://cloud.githubusercontent.com/assets/525763/10793302/910b3b74-7d90-11e5-95d4-0e522f65ffd6.png)

I'm not sure if this is normal or known.
Please let me know if I can provide further informations for debug.

**Comment by thockin** [comment]
60 MiB is plausible, 340 seems out of line.

@vishh

**Comment by yujuhong** [comment]
The 340MB is the working set memory, which includes active anonymous and file-back pages. Because kubelet has a very high cgroup memory limit and kernel only moves pages from active to inactive under memory pressure, the working memory set can appear falsely high. See #12422 for more discussions. `/sys/fs/cgroup/memory/kubelet/memory.stat` would show you that most working set memory is from *active file-backed pages*, which are essentially kubelet.log files last time I checked. Kubelet doesn't need them, and they can be reclaimed by kernel when needed. This is easy to verify -- If you overwrite the memory limit in /sys/fs/cgroup/memory/kubelet to a smaller number, you can trigger a memory pressure and see the memory working set drop. Also note that the heap profiling only shows ~24MB of memory, which seems normal.

We are working on getting a more accurate memory measurement for kubelet and docker, so that we can set proper limits for them.

**Comment by vishh** [comment]
@yujuhong: IIUC, you are suggesting that the values in the graphs is the total usage, not `working set`, which will include cold pages which can be swapped out by the kernel when there is memory pressure.
`working set` on the other hand only includes pages that the kernel things is necessary to continue running a process.
AFAIK, the memory profile `inuse_space` corresponds to `working set` and current usage there is ~24MB, which is not a lot. The go runtime can choose to hang on to more memory that what is necessary based on its garbage collection policy.

@rvrignaud: Can you switch to using `working set` instead of `usage` for the purposes of monitoring? 
FYI: We have found a few issues wrt. resource usage that we are fixing in the upcoming v1.1 release.

**Comment by yujuhong** [comment]
@vishh, no, I meant the working set. The active file-backed pages are not transitioned to inactive pages under no memory pressure. You can easily verify that by looking at kubelet/docker working set memory from cadvisor or heapster. The working set is usually hundreds of megabytes, but could easily be lowered by setting a tighter memory limit.

**Comment by rvrignaud** [comment]
Thank you for the clarification. Closing this one.

**Comment by tianshapjq** [comment]
@yujuhong I have encountererd the similar scene in my setup. We had a containerized kubelet running with memory.limit_in_bytes=500M, but its memory seemed increase slowly when inspecting with _docker stats_. We noticed that the memory stats in _docker stats_ are extracted from cgroup/memory/memory.usage_in_bytes, which may be constructed with some of virtual memories? Finally the memory of containerized kubelet came up to 500M and killed by the cgroup, meanwhile the RES in _top_ command just stayed at about 200M. My question is: how is the memory.usage_in_bytes calculated? Is it proper to kill the container when memory.usage_in_bytes=memory.limit_in_bytes?
