### ISSUE TITLE
Faster use of images

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#16466]
It would be nice to go from scheduled to running in less than a second. 

Possible ideas:
- Prefetching
- Mount common storage containing images
- Peer-to-peer copying (not instantaneous, but could combine with prefetching)

cc @davidopp @brendandburns

**Comment by resouer** [comment]
Option 2 sounds interesting: in this case, do we have to run a separate "storage machine" and then mount its image storage to every node?

**Comment by davidopp** [comment]
Somewhat related: we should add a priority function that prefers to put a pod onto a machine where the largest number of images required by the new pod are already installed. (Borg has this, and Swarm has it and calls it "image affinity".)

**Comment by mitake** [comment]
Hi,

I'm interested in the idea of prefetching. It is because I'm trying to benchmark (just spawn pods on nodes) and understand performance of optimality of k8s (apiserver + etcd) and various schedulers. Let nodes prefetch images before doing the benchmark will be helpful for excluding the cost of image pulling.

Is anyone already working on this feature?

**Comment by ehashman** [comment]
/close

Old issue from 2015, this would need a KEP.
