### ISSUE TITLE
AWS: Use an Elastic IP by default: MASTER_RESERVE_IP=auto

### ISSUE THREAD

**Issue by evanphx** [kubernetes/kubernetes#16469]
By default, a cluster will use the ephemeral IP of the master as the IP of the cluster. This IP is embedded deeply in things like the CA certs, and thus it's impossible to even stop the master instance because it's IP will change and break all the certs.

Please consider using an Elastic IP by default. New users don't know to set MASTER_RESERVE_IP=auto to get this functionality and discovering they should have after running a cluster for months is quite frustrating.

If you feel that you don't want to assign an Elastic IP by default, please consider adding a section of the docs that covers optimal configuration for a production cluster and include this advise in there.

**Comment by davidopp** [comment]
@justinsb can you commento n this?

**Comment by justinsb** [comment]
I think this is a good idea; it is annoying to replace the master and have the cluster break.

(It is also surprisingly hard to replace the master on AWS, but that's a separate issue.  It's on my radar!)

My only concern is whether we should actually put the master behind an ELB.  When we have HA master (some day), we can either use an ELB or we can have an instance take over the master IP.  My gut feel is that we should probably switch to "auto" for now; we can do elastic IP remapping to a leader master, and if people want ELB that can be an option (and it would probably require regeneration of the cert because ELB works by host name).

@evanphx do you think kube-down should delete an "auto" elastic IP?  A slight complication is that we can't tag elastic IPs, so this would only work if the elastic IP was still attached to the master.Also, let me know if you would rather make the change - I'm thinking both in config-default and config-test, although I do worry about elastic ips leaking in config-test.

**Comment by evanphx** [comment]
@justinsb Yeah, I think you should assume the elastic IP is owned entirely by kubernetes. It would be associated with the VPC kube-up creates anyway, so it's easy to just state "all elastic IPs used in the kubernetes VPC are deleted when the VPC is destroyed."

**Comment by pikeas** [comment]
+1. Regarding whether to delete the EIP, could `kube-down` prompt the user for a Y/n?

Also, and this may be worth opening a separate issue, is there documentation somewhere on how to add an additional master? `kube-up` on AWS is single master. HA with an ELB would be nice to have, but multi-master should be supported out-of-the-box.

**Comment by justinsb** [comment]
@pikeas We don't have HA master in 1.2, though I hope we'll get it into 1.3.  sig-high-availability is probably the place to go for that; there's a HA-kubernetes document but it is really a starting point.

I'm not overly keen on prompting for a Y/N - for now the behaviour will be that kube-down reverses kube-up.  If it created an Elastic IP, it'll delete it.

This is now on master, so closing this issue.  (feel free to open other issues e.g. if you disagree on the Y/N behavior)
