### ISSUE TITLE
Guestbook-go example frontend not accessible in Vagrant

### ISSUE THREAD

**Issue by jacobstr** [kubernetes/kubernetes#16488]
I've bootstrapped Kubernetes locally using the guestbook-go example. 

```
➜  kubernetes  kubectl get services                                                                                                                               0
NAME           LABELS                                    SELECTOR            IP(S)            PORT(S)
guestbook      app=guestbook                             app=guestbook       10.247.25.102    3000/TCP
kubernetes     component=apiserver,provider=kubernetes   <none>              10.247.0.1       443/TCP
redis-master   name=redis-master                         name=redis-master   10.247.212.56    6379/TCP
redis-slave    name=redis-slave                          name=redis-slave    10.247.224.236   6379/TCP
```

I'm expecting to be able to visit `10.247.25.102:3000` to see the running application. No luck.

`https://10.245.1.2` Does yield some kind of HTTP response. This corresponds to the eth1 interface of the `master` vm.

```
➜  kubernetes  kubectl cluster-info                                                                                                                           
Kubernetes master is running at https://10.245.1.2
KubeDNS is running at https://10.245.1.2/api/v1/proxy/namespaces/kube-system/services/kube-dns
KubeUI is running at https://10.245.1.2/api/v1/proxy/namespaces/kube-system/services/kube-ui
```

```
vagrant ssh minion-1
ifconfig
...
eth1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.245.1.3  netmask 255.255.255.0  broadcast 10.245.1.255
        inet6 fe80::a00:27ff:fe9a:e16  prefixlen 64  scopeid 0x20<link>
        ether 08:00:27:9a:0e:16  txqueuelen 1000  (Ethernet)
        RX packets 8858  bytes 5128595 (4.8 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 10119  bytes 2535751 (2.4 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
...
```

Using Virtualbox 5.0.8, Vagrant 1.7.4,

**Comment by krousey** [comment]
Please re-post your question to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes). 

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases. 

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to similar questions, and also familiarize yourself with:
   * [the user guide](http://kubernetes.io/v1.0/)
   * [the troubleshooting guide](http://kubernetes.io/v1.0/docs/troubleshooting.html)

Again, thanks for using Kubernetes.

The Kubernetes Team
