### ISSUE TITLE
Rolling update should support scale-out first

### ISSUE THREAD

**Issue by jcderr** [kubernetes/kubernetes#16503]
I have a few processes where I use a replication controller to keep a single pod up and running, and which are completely intolerant of having multiple instances running simultaneously. For instance, JetBrains TeamCity fails if it detects another copy of itself accessing the database.

My current workflow is to:

* update the container
* update my rc.yaml
* kubectl scale rc/teamcity --replicas=0
* kubectl rolling-update teamcity -f rc.yaml

All I'm updating in my rc.yaml is the Docker image's tag to the new version (and the name of the RC per the rolling-update requirements). Using the `kubectl rolling-update [RC] --image=...` format would be perfectly sufficient, except that it requires there to be replicas>1, which I can't have for this process.

Something like `kubectl rolling-update [RC] --scale-out-first ...` would be nice.

**Comment by kargakis** [comment]
What you need is [deployments](https://github.com/kubernetes/kubernetes/blob/master/docs/user-guide/deployments.md) with the Recreate strategy which is currently added in the deployment controller (https://github.com/kubernetes/kubernetes/pull/16713).

Take, for example, https://github.com/kubernetes/kubernetes/blob/master/examples/extensions/deployment.yaml. You should specify Recreate in the deployment.spec.strategy.type field and create the deployment. The deployment controller would pick it up and run a replication controller for you. 

Then, you can do almost anything that you would normally do with a rc - scaling, reaping (https://github.com/kubernetes/kubernetes/pull/18077) and a more general command that would execute any strategy (`kubectl deploy` maybe) would be useful since rolling-update is specific.

Any subsequent changes to your deployment template will automatically recreate by scaling down the old rc and then scaling up a new one with the latest configuration.

Note that deployments are still alpha but they are functional and more enhancements are coming soon.

**Comment by kargakis** [comment]
So I guess this issue can be closed once https://github.com/kubernetes/kubernetes/pull/16713 is merged.

**Comment by kargakis** [comment]
cc: @bgrant0607 @nikhiljindal

**Comment by kargakis** [comment]
Btw the rolling update strategy in deployments supports scaling down first (.spec.strategy.rollingUpdate.maxUnavailable=1, .spec.strategy.rollingUpdate.maxSurge=0 in your case) but recreate is what you really need even if it's just one pod.

**Comment by bgrant0607** [comment]
For one pod, rolling update isn't really necessary. One could just update the RC (using patch, replace, apply, edit, whatever), then scale it down and back up again.

**Comment by bgrant0607** [comment]
Or update the RC and then delete the pod and let it get replaced.
