### ISSUE TITLE
HPA controller needs more flexibility from APIInstaller

### ISSUE THREAD

**Issue by deads2k** [kubernetes/kubernetes#16500]
Spawned from https://github.com/kubernetes/kubernetes/issues/16177

 Our `APIInstaller` infrastructure forces all requests for a particular version of a REST endpoint to use an exactly matching version (POSTs to api/v1/namespace/foo/resource must send a v1 object). This breaks the `HPAController` client because it cannot generically include every codec for every (group, kind) that it might want to scale.

// pulling a few comments from the original issue
1. HPA is a central component that should be able to reach out to generic endpoints
2. HPA can only know about a limited number of versions and conversions internally (anything compiled with kube)
3. We want HPA to be able to scale anything that results in pods generically, by virtue of invoking a generic Scale sub resource on endpoints
4. HPA will therefore have to be able to submit things it knows about to endpoints it does not know about.
5. Therefore an API server has to be able to accept the things HPA knows about (Scale, Kube group, v1) and convert it internally to its own recognized format (Scale, OpenShift/3rd party group, v2).
6. Therefore we need to relax the APIInstaller limitation and allow clients to convert.
   @bgrant0607 @lavalamp i think this walks back the previous decision we had to not accept multiple types of input - there is no way for HPA to scale things it doesn't know about unless it can send things to a remote server that it knows about. The remote server is responsibility for taking the Kube type submitted by HPA and converting it to its own internal format.

The contract between HPA controller client and remote API groups that implement Scale is "I will send you one of a set of API versions that I recognize".

@kubernetes/goog-csi @DirectXMan12 @ncdc @smarterclayton

**Comment by ncdc** [comment]
@kubernetes/rh-cluster-infra

**Comment by lavalamp** [comment]
I'm not sure we're on the same page here.

> HPA knows about (Scale, Kube group, v1) 

No: (extensions/v1beta1/scale)

Let's be very explicit. I'm saying the (resource, resource scale) path pairs must be the below, at least at the moment.

For: `https://my-kube-apiserver/api/v1/replicationcontrollers/myrc`
Scale is at: `https://my-kube-apiserver/apis/extensions/v1beta1/replicationcontrollers/myrc/scale`

For: `https://my-kube-apiserver/apis/extensions/v1beta1/jobs/mjob`
Scale is at: `https://my-kube-apiserver/apis/extensions/v1beta1/jobs/myjob/scale`

For: `https://my-openshift-apiserver/osapi/v1/scalableosthings/mything`
Scale is at: `https://my-openshift-apiserver/apis/extensions/v1beta1/scalableosthings/mything/scale`

For: `https://my-openshift-apiserver/apis/openshift.com/v1/scalableosthings/mything`
Scale is at: `https://my-openshift-apiserver/apis/extensions/v1beta1/scalableosthings/mything/scale`

An alternative (I believe this is what @deads2k is thinking) is to manufacture the scale path merely by appending `/scale` to the resource path. This doesn't work because the scale resource and the main resource are not in the same group/version. Do you really want to copy the scale type into a bunch of different groups? Scale is still beta, so that's really not a good idea. (Not copying is even worse; then the group/version/kind in the path are lies; that's actively deceptive and not acceptable IMO, even if we knew what the client wanted when they called GET, which we wouldn't.)

And if you do copy into a bunch of groups, you have to do client-side polymorphism, where HPA uses a client that speaks `runtime.Object`s instead of a typed client. I've proposed that client, but it does not exist yet.

As the code exists today, I think the only sensible thing to do short term is what I outlined above.

**Comment by deads2k** [comment]
> (Not copying is even worse; then the group/version/kind in the path are lies; that's actively deceptive and not acceptable IMO, even if we knew what the client wanted when they called GET, which we wouldn't.)

Not copying is what I was thinking. I see a distinction between the group,version of the resource and the group,version of the kind.  It seems reasonable to me that I'd have:

`group,version,resource,subresource = origin,v1,scalablething,scale`
that accepts and returns
`group,version,kind = extensions,v1beta1,Scale`

That structure makes it clear that you're scaling an (origin,v1) thing.  Given a discovery doc that can speak types, locating things you can scale is done by finding a group,version,resource,subresource tuple with subresource=scale than GET and PUT extensions,v1beta1,Scale kinds.

This structure also makes it easy for other providers to create resources that the HPA controller can scale.  Otherwise, we'll have to support having some resources for an API group hosted on server1 and some on server2, which seems strange.

**Comment by smarterclayton** [comment]
Yeah API groups I think are very much a single server problem.  And we definitely don't want to copy the scale type into groups... however, we need to support (in another API) a version of scale that is tied to one of the kube versions.

We can solve the client side polymorphism today (we just run the HPA ourselves, until the necessary upstream work is complete).  If that takes a few months I think that's ok (people on OpenShift will help make it a reality) as long as we agree.  We would hide the client details from the HPA controller behind an appropriate client interface.

Trying to slam our resources into your API group is more worrying - it means that different server groups will have different resources in their API group, which scares me very much.  I would like api groups to be predictable within themselves.

**Comment by DirectXMan12** [comment]
> (Not copying is even worse; then the group/version/kind in the path are lies; that's actively deceptive and not acceptable IMO, even if we knew what the client wanted when they called GET, which we wouldn't.)

Is there any reason we couldn't somehow extend the API to indicate what version we want for the subresource?  In my mind, `/scale` is somewhat unique, because it's acting like a contract between HPA and the scalable objects, and so the version really "belongs" to the HPA, and is just implemented by the objects.  Perhaps we could have something like "/api/v1/namespace/{ns}/replicationcontroller/ext/scale" ("ext" for "external interface"), and then have some header (or deepen the path) that specifies desired version?

**Comment by lavalamp** [comment]
> That structure makes it clear that you're scaling an (origin,v1) thing. Given a discovery doc that can speak types, locating things you can scale is done by finding a group,version,resource,subresource tuple with subresource=scale than GET and PUT extensions,v1beta1,Scale kinds.

This breaks as soon as we promote scale to v1. How does HPA know whether you take v1 or v1beta1 scale objects? You'd be forcing a client to deal with an arbitrary type. We lose the ability to make promises about what clients can deal with your objects.

> We can solve the client side polymorphism today (we just run the HPA ourselves, until the necessary upstream work is complete). If that takes a few months I think that's ok ...

It's in my client proposal, hopefully finished by v1.2.

> Perhaps we could have something like "/api/v1/namespace/{ns}/replicationcontroller/ext/scale" ("ext" for "external interface"), and then have some header (or deepen the path) that specifies desired version?

"/api/v1/namespace/{ns}/replicationcontroller/apis/extensions/v1beta1/scale" is gross, esp. if you do it consistently for all sub resources.

**Comment by DirectXMan12** [comment]
> "/api/v1/namespace/{ns}/replicationcontroller/apis/extensions/v1beta1/scale" is gross, esp. if you do it consistently for all sub resources. 

I certainly agree that that particular form is long (which is why I suggested perhaps a header with a default version).  I don't think it needs to scale out to all subresources -- only ones that act like Scale (which is why I suggested the subpath of `/ext` to differentiate).  AFAICT, the other subresources aren't directly used by a different controller and don't have the same "interface between controller and object" meaning.

**Comment by lavalamp** [comment]
Using headers to encode version info would be interesting, but we've never done it so far.

If we did it consistently, we could omit the version from the path. I think we'd want to keep the group? But that's a much bigger can of worms.

**Comment by smarterclayton** [comment]
Classically in rest when you want to change the version you get, you send
the http Accept header with a list of the types you accept, something like:
 Accept: application/json;apiversion=v2,kind=Bar.  The default is always
applied by the server.

You always want the version in the URL so you can change names and path
structures across versions.

On Oct 29, 2015, at 6:26 PM, Daniel Smith <notifications@github.com> wrote:

Using headers to encode version info would be interesting, but we've never
done it so far.

If we did it consistently, we could omit the version from the path. I think
we'd want to keep the group? But that's a much bigger can of worms.

—
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/16500#issuecomment-152345376>
.

**Comment by bgrant0607** [comment]
It would be great to have someone who really knows REST to take a look at our API and provide feedback #4187 (not that we'd implement all of it).

**Comment by smarterclayton** [comment]
We're all hostages now.

I have to say, I saw the GCE type encoding scheme today and I like it
better than apiVersion and kind :)

On Oct 30, 2015, at 5:34 PM, Brian Grant <notifications@github.com> wrote:

It would be great to have someone who really knows REST to take a look at
our API and provide feedback #4187
<https://github.com/kubernetes/kubernetes/issues/4187> (not that we'd
implement all of it).

—
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/16500#issuecomment-152656508>
.

**Comment by bgrant0607** [comment]
@smarterclayton What do you like about GCE's scheme? That group is part of kind?

**Comment by smarterclayton** [comment]
That group, version, and kind are together.  As a client, I only really
have to deal with kinds and groups when I'm fetching from APIs that can
return multiple things.  As a sophisticated client, I'm likely to have a
map between "kind" and a handler to do specific actions (like output), and
if I'm a sophisticated client, I probably need to have fairly sophisticated
handling around unrecognized types.  As a client that is in between naive
and sophisticated, it's a bit harder to do generic things (like use a
printer for anything that says its kind is "Pod"), but on the other hand
most of the time that's going to be wrong, and clients should be versioned
locked as much as possible.

A lot of our pain today is because our external serialization has multiple
fields that can interact.

**Comment by smarterclayton** [comment]
Yes I do want to copy Scale into all these groups.  OpenShift as a release
tool (an API on top of Kube) has to make very specific statements about
what it supports.  Putting our resource in a Kube API space is horribly
ugly - and ultimately, we have to make a statement that API group "foo" at
version "X" supports the following versions of the Scale interface:
["v1beta1", "v1", "v2"].

As soon as you have generic sub resources that are polymorphic objects, you
have to version the interface those objects expose.  I believe very
strongly that the type that a different group accepts is part of that
groups contract, not part of the core Kube API group.

**Comment by lavalamp** [comment]
>  the type that a different group accepts is part of that groups contract, not part of the core Kube API group.

How can a client discover that this thing conforms to a contract that the client understands?

**Comment by smarterclayton** [comment]
Via discovery?  A group that exposes the scale subresource on something has
to say "it supports these interfaces"

**Comment by smarterclayton** [comment]
> Yes I do want to copy Scale into all these groups

Oops, I meant "have a version of scale from another group exposed by this group, but locked at a specific interface version that is at the other group version".

**Comment by lavalamp** [comment]
Do we need an addition to object meta to communicate this?

e.g. `convertibleTo: {"v1", "scale"}`

Actually, perhaps somewhere in swagger, or in the info returned by the discovery APIs would be better.

**Comment by smarterclayton** [comment]
Discovery API or swagger is probably enough.

**Comment by lavalamp** [comment]
Last question: should we do these conversions server-side or client-side? I
think it has to be client side.

**Comment by deads2k** [comment]
> Last question: should we do these conversions server-side or client-side? I
> think it has to be client side.

I would argue for both.  I think that the server should be as flexible as possible when decoding input, so that anything it gets that is coercible to its expected format is handled.  I'd also expect that a client would look a the list of acceptable inputs and if its trying to send something that isn't one of them, it should try to coerce what it has into a type the server accepts.

**Comment by lavalamp** [comment]
After more thought, I think it's better to be very clear that the server only accepts a particular version, and it's the client's job to be polymorphic. I think this will reduce bugs, long-term. I'm just nervous about the server doing some possibly-never-tested conversion between a random object a client sends and missing some important field. Somehow it feels more tractable to me to have the client explicitly deal with "dynamic" objects.

**Comment by ncdc** [comment]
cc @piosz

**Comment by jszczepkowski** [comment]
CC @jszczepkowski

**Comment by smarterclayton** [comment]
Which version does it accept?  Imagine the following scenario:

1. Kube server is at v1, talking v1 scale objects (as a client)
2. OpenShift extension implements scale, talking at v1 (coincidentally)
3. Kube server (as a client) revs to v2, supporting v2 and v1 scale objects
4. OpenShift implementation doesn't rev to v2 scale, because we don't want
to introduce a new API version on our objects just because of Kube.  It
accepts v2 and v1 objects
5. Kube server (as a client) drops v1 support
6. OpenShift objects can't be scaled because we don't want to rev our API
version?

**Comment by erictune** [comment]
@lavalamp I'm trying to determine if fixing this bug might require a change to the API, and thus if this needs to be fixed (or at least a fix planned) before HPA goes to GA. What do you think.

**Comment by piosz** [comment]
@lavalamp could you please reply to @erictune's comment?

**Comment by lavalamp** [comment]
Sorry, I was OOO. I'm back for real now.

I think the thing in question in this issue is where to locate the /scale subresource; we had a meeting earlier today but did not fully decide. I think when we left @bgrant0607 is going to write up something.

I'm tentatively in favor of `https://apiserver/api/v1/replicationcontrollers/myrc/subapis/extensions/v1beta1/scale` (clients can find it with discovery); and I can live with hardcoding it to `https://my-kube-apiserver/api/v1/replicationcontrollers/myrc/scale` (clients have to have special knowledge to find it).

Either way it's a change from the current location (under `extensions/`). So yes, a change is needed.

**Comment by deads2k** [comment]
> I'm tentatively in favor of https://apiserver/api/v1/replicationcontrollers/myrc/subapis/extensions/v1beta1/scale (clients can find it with discovery); and I can live with hardcoding it to https://my-kube-apiserver/api/v1/replicationcontrollers/myrc/scale (clients have to have special knowledge to find it).

I prefer `https://my-kube-apiserver/api/v1/replicationcontrollers/myrc/scale` and updating the `APIResourceList` or `APIResource` to include subresources (which I think are needed in general) and include the group,version,kind that the subresource deals in.

**Comment by bgrant0607** [comment]
cc @madhusudancs

**Comment by lavalamp** [comment]
We made a decision on this at the last API machinery SIG, I wrote it up here: https://github.com/kubernetes/kubernetes/issues/18528#issuecomment-181564885

**Comment by lavalamp** [comment]
@madhusudancs is actually working on getting a new scale resource in.

**Comment by madhusudancs** [comment]
This issue shouldn't be closed yet. #22724 fixes this problem only partially and is a stopgap solution for v1.2. #22511 fixes this issue in a desirable way. So reopening the issue.

**Comment by piosz** [comment]
Is there anything to do for 1.2? If not let's change the milestone.

**Comment by smarterclayton** [comment]
Closing due to age, reopen if this is still needed.
