### ISSUE TITLE
Minions IP does not follow --hostname-override when set to a hostname

### ISSUE THREAD

**Issue by Fizzadar** [kubernetes/kubernetes#16512]
According to #9267, the Kubelet should register a node with the `--hostname-override` (cluster from scratch). This does not work if set to an actual hostname (even one that resolves correctly). Working with the IP:

``` sh
$ /opt/bin/kubelet --hostname-override=172.16.25.131 --address=172.16.25.131
...
$ kubectl describe node minion-2
Name:           minion-2
...
Addresses:  172.16.25.131
```

And when the override is set to a hostname (which resolves to the 172 IP):

```
$ /opt/bin/kubelet --hostname-override=my-server.com --address=172.16.25.131
...
$ kubectl describe node minion-2
Name:           minion-2
...
Addresses:  2a01:4f8:110:4085::2
```

**Comment by Fizzadar** [comment]
Update: the behaviour is exactly the same with IPv6 disabled, so isn't a problem with that.

**Comment by dchen1107** [comment]
Quota from issue #9267: "In the case of no cloudprovider, the --hostname-override flag in Kubelet sets LegacyHostIP."
Qutoa from the flag --hostname-override: "fs.StringVar(&s.HostnameOverride, "hostname-override", s.HostnameOverride, "If non-empty, will use this string as identification instead of the actual hostname.")"

Shouldn't this is the right behavior.

**Comment by spzala** [comment]
@Fizzadar Hello, just following up if it's still an issue since it was last discussed over a year ago? If it isn't or you agree with @dchen1107 that it's behaving as expected then can we close this issue? Thanks!!
