### ISSUE TITLE
Write a munger to replace the tabs with spaces in ```yaml of *md

### ISSUE THREAD

**Issue by janetkuo** [kubernetes/kubernetes#16541]
Follow up https://github.com/kubernetes/kubernetes/issues/16391#issuecomment-152316646

Tabs in ```yaml causes problem in gh-pages. Write a munger to replace `<tab>` with `<space>`.

**Comment by spzala** [comment]
@janetkuo Hi, I guess this work is not done yet? and we may want to keep this issue open but wondering of what you think about it, and that if this was discussed lately and there is any chance that issue can be closed? Since it's been over a year and seems like you have fixed tabs with space manually. Thanks!

**Comment by kargakis** [comment]
@kubernetes/sig-contributor-experience-feature-requests

**Comment by bgrant0607** [comment]
Doc munging in this repo is dead
