### ISSUE TITLE
swagger ui link doesn't work well in gh-pages

### ISSUE THREAD

**Issue by janetkuo** [kubernetes/kubernetes#16550]
In http://kubernetes.io/v1.1/docs/api.html, clicking on the link **statically generated UI** (http://kubernetes.io/third_party/swagger-ui/) returns you a blank page. 

cc @bgrant0607 @nikhiljindal @caesarxuchao

**Comment by bgrant0607** [comment]
We plan to delete the swagger UI. #15915

**Comment by nikhiljindal** [comment]
Nice catch.
gh-pages should treat that as an external link. Right now it does not : https://github.com/kubernetes/kubernetes/blob/gh-pages/_layouts/docwithnav.html#L151

**Comment by spzala** [comment]
@janetkuo @nikhiljindal Hi, since it's been over a year of this issue, 
and the docs has been changed a lot during this time and I don't see 'statically generated UI' link anywhere any more, thought good idea to touch base with you and request you to close this issue if it isn't an issue any more. Thanks!
