### ISSUE TITLE
Problem statement: interact with 3rd party API sources

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#16558]
For 1.2, we want to make API groups into a feature that enables people to build kubernetes APIs outside of our repository. The biggest missing piece of that is some mechanism by which kube-apiserver can find and report these resources for use by clients.

There's at least three mechanisms we can use to solve this:
* 3rd party storage (@brendandburns' system, partially implemented).
* Webhooks (I started to write something in #11823) - it seems we at least need them for admission, but that's probably a separate topic.
* 3rd party apiserver registration - something like this is probably necessary for this feature to be useful for OpenShift

Nikhil was interested in driving this for 1.2, so I'm making this tracking issue. The first step is to write a proposal or a roadmap for this.

**Comment by lavalamp** [comment]
Will link previous issues as I find them, starting with #3201

**Comment by nikhiljindal** [comment]
Based on my reading of those issues/PRs, it seems to me that the 3rd approach is the most desired.

At a very high level this will include:
* Ability for people to bring up their own APIservers. Automatically generated swagger spec will be used to define the operations supported by each of these servers.
* There will be a "master" APIServer that gets all user requests first. It can handle the request on its own or can send it to other registered APIServers if they support that operation.
* Master APIServer will expose an API which other APIServers can use to register themselves. This API will accept swagger spec.

Issues that this will need to handle:
* Allow APIServers to share storage rather than each one having their own.
* Extract api server machinery into an independent library.

Some questions:
* Is it fine to assume that a resource is completely handled by a single APIServer? Or do we want to support use cases where an APIServer A can register hooks on a resource implemented by another APIServer B?

cc @lavalamp @bgrant0607  @smarterclayton @derekwaynecarr

**Comment by lavalamp** [comment]
It is occurring to me that perhaps we first/in parallel want to make apiserver infrastructure easy-to-reuse, or there may not be anyone lining up to register 3rd party APIs.

**Comment by smarterclayton** [comment]
I'm still uncomfortable with "master" apiserver that gets requests first.
I think we need to argue this through - we've never reached closure on it.

We do want to register APIs with the master, but as a "here's where I am"
to start.

Resource handled by a single api server, but we need to sort out the
"subresource interface" problem like scale first (could someone else
implement the scale sub resource for you).  I don't think it's a blocker in
the short term to assume that.

Reusing the apiserver with minimal work would be good.  The question is
what else needs to be there - authorizer, easy wrappers, etc.

**Comment by lavalamp** [comment]
@smarterclayton Yeah, that's exactly the argument that I think we need to have. I don't have a clear picture of how auth/admission/etc can work in the world where apiserver doesn't proxy.

**Comment by nikhiljindal** [comment]
There are 2 sub-problems here:
1. Making it easy for people to build their own APIServers (separate out api server machinery from api code)
2. Once there are multiple servers, make them work together.

For the second problem:
a. It seems that we can start with the assumption that a resource (and its subresources) are completely handled by a single APIServer. This should simplify things.

b. Is it fine to proxy all requests through the master APIServer? The advantage is that we will get centralized auth and admission control. Other APIServers can exercise additional constraints when requests come to them. Disadvantage is that the master APIServer might end up spending most of its time just proxying requests.
Other alternative is to have a proxying layer at the top. All clients talk to this proxy which redirects the requests to individual APIServers. Disadvantage is that all APIServers will need to implement auth, admission control, etc.
While first alternative (proxying all requests via master APIServer) seems to make a few things easier to implement, the second one seems like a better design long term.

cc @erictune to see if he has comments on auth, admission control.

**Comment by smarterclayton** [comment]
The original design of auth was a proxy layer on top.  Also, I suspect that
we will have a few cases that will always be "i want my own auth" because
the service has a different auth domain.  I'm not terribly opposed to a
horizontal master apiserver proxy that does auth, buuuuut.... we still have
to authorize from the front proxy to the backend, and that means the
horizontal master layer has to have full delegation rights against the
backends.  I think that worries me more in the long term, because a loosely
federated model *can* still be proxied centrally, but you aren't forced to
have the same security failure domain.

I'll marshal some of the other discussion points we've had on this.
Examples like Kerberos to the front proxy tier won't make it to the
backend, which means we potentially wouldn't be able to support
organizations that had different services running that required Kerb
credentials.

**Comment by erictune** [comment]
If a request to a 3rd party apiserver just affects objects managed by that apiserver, then I think it can do its own authn.  It could also do its own authz.  Note that "doing authz" is independent of "storing objects that encode authz policy".  The latter might be on the 1st party apiserver.

If the 3rd party apiserver needs to read or write 1st party objects then it needs to authorize (perhaps with impersonation) to the 1st party apiserver.

Does that work?

**Comment by nikhiljindal** [comment]
Based on more discussions with @erictune and @lavalamp, it seems fine to let each apiserver do their own auth.
Each apiserver should have their own etcd. If they want to use core APIServer's etcd, they should do so using third party resources. This ensures that 3rd party APIServers cannot modify core APIServer's resources.

3rd party servers will register themselves with the core API Server, which will then include these registered 3rd party servers in its Discovery API. Clients will use the discovery API and contact 3rd party servers directly.

**Comment by nikhiljindal** [comment]
Wrote up a proposal in https://github.com/kubernetes/kubernetes/pull/17191

**Comment by bgrant0607** [comment]
I think there are at least 2 cases of 3rd-party apiservers: with and without separate storage.

**Comment by bgrant0607** [comment]
We still want to make ThirdPartyResource minimally usable for simple CRUD, such as for storing config templates or cloud storage breadcrumbs.

**Comment by lavalamp** [comment]
The proposal is written and merged.
