### ISSUE TITLE
Clarify Garbage Collection semantics in Kubelet

### ISSUE THREAD

**Issue by vishh** [kubernetes/kubernetes#16563]
Kubelet can manage only one storage partition as of today. 
Kubelet uses cadvisor to identify and track the overall usage of the partition where docker's storage directory is located. 
If the docker daemon's storage directory is different from that of the root filesystem, kubelet will not realize this.
Depending on how the node is setup, kubelet's garbage collection behavior will change.

Single partition scenario:
1. If the storage backend is either `Aufs` or `Btrfs`, kubelet will track the entire root partition usage and perform image & container GC whenever the usage cross a user configurable [high watermark](https://github.com/kubernetes/kubernetes/blob/b9cfab87e33ea649bdd13a1bd243c502d76e5d22/docs/admin/garbage-collection.md#L83). This includes logs, local disk based volumes, etc.
2. If the storage backend is `DeviceMapper`, kubelet is expected to track the usage of the `pool` device which includes the image layers and the container root filesystems. GC is expected to be triggered whenever the underlying storage availability for the pool device falls below the high watermark.
3. Support for Overlayfs does not exist. Kubelet will not perform any GC on nodes running OverlayFs. Relevant cAdvisor issue [here](https://github.com/google/cadvisor/issues/932).

Multiple partition scenario:
1.  If the storage backend is either `Aufs` or `Btrfs`, kubelet will use the partition where docker's storage directory is located and use it for GC purposes. If `--kubelet-root-dir` (default is `/var/lib/kubelet`) is on a different partition when compared to that of docker daemon, then GC will only happen when the usage on the docker partition crosses the high watermark. 
2. In the case of `DeviceMapper`, kubelet will use the storage device allocated for docker images and container root fs. Excessive logging usage by docker container's will not trigger GC, since log files are stored on a different partition.

From a user's perspective, the system should do everything possible to free up storage on local disk, possibly without any impact to running pods. If that assumption is valid, performing GC even on storage usage by local disk volumes is desirable. 
We want to support scheduling local disk as a schedulable resource in the near future. AFAIK supporting multiple partitions hasn't been considered as a requirement.
Once disk limits can be set on pod (for volumes) and containers (root filesystem and logs), GC might not matter as much as it does today.
The system might evict pods in the future to free up space on the local disk. This might not work as intended with multiple partitions unless kubelet is updated.

The existing GC behavior can be confusing to users. 

I'd like to get a consensus on the desired kubelet behavior when it comes to garbage collection. 

cc @kubernetes/goog-node @bgrant0607 @thockin @smarterclayton

**Comment by rhvgoyal** [comment]
Case of overlay I think should be very similar to aufs.

For device mapper, just looking at thin pool free space might not be sufficient in all the configurations. We have the capability to grow pool dynamically automatically if usage crosses user configured thresholds. Right now on fedora, by default when pool is 60% full, we grow it by 20% (If there is free space in volume group).

https://github.com/projectatomic/docker-storage-setup/blob/master/docker-storage-setup.conf#L65

As long as kube's threshold is above docker's threshold of growing pool, things will work. But otherwise you might start garbage collection while it is not required as pool will be grown.

So may be we can do determine if pool is setup for auto extension or not. If it is not setup for auto extension, the just consider pool's free space for GC. Otherwise consider pool's free space and underlying volume group's free space for total free space and apply GC threshold's accordingly.

**Comment by vishh** [comment]
> So may be we can do determine if pool is setup for auto extension or not. If it is not setup for auto extension, the just consider pool's free space for GC. Otherwise consider pool's free space and underlying volume group's free space for total free space and apply GC threshold's accordingly.

SGTM. Should we be concerned about a race between auto-resizing and the kubelet GC thresholds? 

IIUC, there are at-least two storage devices that kubernetes will have to manage from scheduling perspective.

**Comment by rhvgoyal** [comment]
One race could be that we checked thin pool's free space, and before we checked volume group's free space, pool got extended. That will give us wrong impression about available free space. May be we recheck in a loop to make sure pool did not grow in between reading two values and if it did, redo the operation.

**Comment by bgrant0607** [comment]
We should support scenarios where /var/lib/docker isn't on the root disk. That's always how I create VMs by hand so that (a) it's easier to resize and (b) when docker fills up the disk it doesn't brick the VM.

**Comment by victorgp** [comment]
@vishh what's the status of this as today that version 1.4 is released?

Is overlayfs already supported?
Is the kubelet able to clean data if /var/lib/docker is in a different partition?

**Comment by vishh** [comment]
@dashpole can you help out here?

**Comment by dashpole** [comment]
overlayfs is supported: https://github.com/google/cadvisor/pull/962.  I'm looking cleaning data if /var/lib/docker is in a different partition.

**Comment by dashpole** [comment]
To test this, I did the following:
Spun up a VM using the GCI image.
Used fallocate to create a 1 Gb file.
Used mkfs to make it an ext4 filesystem.
Replaced the directory: /var/lib/docker by mounting the new filesystem, and moving contents of the old folder into the filesystem.
Ran all node-e2e tests, except flaky tests.  All passed, except for known issues not related to this.
After a couple rounds of testing, resource usage all appears to be normal.
Digging through logs shows that the kubelet was able to successfully garbage collect both containers and images.
Overall, I did not find anything that would suggest that using /var/lib/docker in a different partition breaks anything.

Let me know if there is anything else I should look for.

**Comment by vishh** [comment]
@dashpole that's awesome. @victorgp does https://github.com/kubernetes/kubernetes/issues/16563#issuecomment-257413532 match your expectations and/or observations?

**Comment by victorgp** [comment]
I think so, i was asking that question because when kubelet starts i'm getting this log:

`Image garbage collection failed: unable to find data for container /`
`Failed to check if disk space is available for the runtime: failed to get fs info for "runtime": unable to find data for container /`
`Failed to check if disk space is available on the root partition: failed to get fs info for "root": unable to find data for container /`

I'm not sure if it is related to the fact of having /var/lib/docker in another partition. Do you have any idea what this might be?

**Comment by dashpole** [comment]
What os image are you on?  What version of k8s are you on?  Do you see lots of those in your logs, or does it only happen once?  It shouldn't have anything to do with /var/lib/docker being in a different partition, since those errors indicate that it wasn't able to collect for the "root" ("/") container.  I think it means that cadvisor isn't able to collect any information at all...

**Comment by victorgp** [comment]
We are running CoreOS 1068.10 and k8s 1.3.7 version. Those logs only happen once when the kubelet starts and not anymore. However, if i go to cadvisor dashboard i can see the metrics there and it is calculating the disk space properly, that is the weird part...

**Comment by dashpole** [comment]
That error is likely occurring because the kubelet is trying to query cadvisor before cadvisor has actually collected any information... I wouldnt worry too much about it

**Comment by victorgp** [comment]
That makes sense, and it is probably the issue. Thank you for your help!

**Comment by GaoRong** [comment]
@vishh 　How are we going with the issue?  Is there any PR to accomplish ?  it seems that there are still some related issue: #60662.

**Comment by shuaichang** [comment]
This seems to be an old issue, but it's a bit surprising to me that it seems Kubelet still does not support garbage collecting images with device mapper by reading through Kubelet GC code. Please see the following and feel free to correct if I'm wrong:

![image](https://user-images.githubusercontent.com/28563006/156674905-2946533f-8992-4fd7-a954-57e50a59d337.png)

Although Kubelet called cri.imagefsinfo to get the accurate device mapper thin pool storage usage data, it's never really used.
![image](https://user-images.githubusercontent.com/28563006/156674264-bffbe0b1-40fd-41e1-b6f0-5df1393685f1.png)

Instead, Kubelet only get FS info on `/var/lib/containerd/io.containerd.snapshotter.v1.devmapper` which is unchanged with adding/removing images and containers.

![image](https://user-images.githubusercontent.com/28563006/156675391-ec536656-9f56-4486-a702-3de7b0cf9597.png)

This seems to be a lack of support from Kubelet for any other snapshotter with CRI stats provider, is this the case or there are something else I'm missing. Also looked into cadvisor stats provider, but it seems for docker device mapper graph driver only and cannot work with K8s + containerd.

Please feel free to provide other insights, but seems to me device mapper is a fairly common snapshotter and storage option that Kubelet should have supported. Or at least provide extensibility with protocol between CRI to get the correct `available/capacity` stats instead of doing fsInfo only.
