### ISSUE TITLE
[feature request] adding a script that adds nodes to k8s cluster on the fly

### ISSUE THREAD

**Issue by caesarxuchao** [kubernetes/kubernetes#16648]
AFAIK, we don't have such a script yet. Such a script will make it convenient for users who want to experiment k8s with more worker.

(this is forwarded for a user request during my user-support rotation)

**Comment by babusatasiya** [comment]
Thank you @caesarxuchao  Sure, I was looking forward to add more worker nodes to test scaling up pods and it run-out of resources. It would be good to have the automation to add/remove additional worker nodes. 

These were failing due to resources, but was not clear from log messages.

Get gcloud eval account and try:
-----
curl -sS https://get.k8s.io | bash
kubectl run my-nginx --image=nginx --replicas=5 --port=80
time  kubectl  scale --current-replicas=5 --replicas=30 replicationcontrollers my-nginx

**Comment by babusatasiya** [comment]
After installing four nodes, if I want to scale, it fails due to It can not find tarball.

bash-3.2$ ./kube-up.sh
... Starting cluster using provider: gce
... calling verify-prereqs

All components are up to date.

All components are up to date.

All components are up to date.
... calling kube-up
Project: bb8-101
Zone: us-central1-b
!!! Cannot find kubernetes-server-linux-amd64.tar.gz

**Comment by piosz** [comment]
cc @mwielgus 

proposal is here #15304

**Comment by kargakis** [comment]
Is this now satisfied by `kubeadm join`?
@kubernetes/sig-cluster-lifecycle-misc

**Comment by roberthbailey** [comment]
Yes (either that or obsolete).
