### ISSUE TITLE
Figure out why in e2e tests we sometimes see non-capitalized verb 'proxy', even though it's not registered in the API server

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#16659]
cc @davidopp @lavalamp @wojtek-t 

see https://github.com/kubernetes/kubernetes/pull/16505/files#diff-1e89bcf0907383889eec45f6713cb049R113

**Comment by quinton-hoole** [comment]
This seems like a curiosity and cleanup rather than a breaking problem.  Technically HTTP verbs are supposed to be capitalized and case sensitive [1], but there are plenty of examples of these [RFC rules](http://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html) being broken in the wild, so we should probably just treat them as case-insitive, as you've done in your workaround (which should ideally be generalized).  Dropping to P3.

**Comment by kargakis** [comment]
@kubernetes/sig-testing-misc 
@kubernetes/sig-api-machinery-misc

**Comment by gmarek** [comment]
It's probably stale. Plus we don't currently have our own 'kube verbs':)
