### ISSUE TITLE
HPA Metrics Client should take a list of pod names instead of a selector

### ISSUE THREAD

**Issue by DirectXMan12** [kubernetes/kubernetes#16675]
The metrics client code should not be required to know how to collect a list of a pods for a given selector -- it should just need to know how to actually fetch the metrics for a set of pods.  This should make it easier to write different metrics clients, among other things.

**Comment by davidopp** [comment]
@jsz @piosz

**Comment by piosz** [comment]
cc @mwielgus

**Comment by mwielgus** [comment]
@DirectXMan12 Everything depends on how (under what key) the metrics are stored. It is easier to turn a selector into a set of pods (10 lines of code in heapster client, can make it a utility function if you wish) than set of pods into a selector. Also, the usage of selector is more in line with the scale subresource idea.

**Comment by DirectXMan12** [comment]
cc @deads2k

**Comment by deads2k** [comment]
Initializing the `HeapsterMetricsClient` with a single client that is used for both listing pods and getting metrics means that in order to effectively use this client, I must have a single set of credentials that grants me the ability to inspect pods and proxy services.  The latter is logically required, but the former is not.  The current structure exposes a tremendous amount of information (every env var, mount point, selinux setting, context constraints to target high value pods) that is not required for something that only needs to be able to inspect performance characteristics.

@liggitt anything to add?

**Comment by mwielgus** [comment]
Not sure if I understand your need correctly. You want to have 2 different clients used in HorizontalPodAutoscaler controller:
* One for querying api objects (HPAs, pods, etc)
* One for talking to Heapster
Am I right?

**Comment by deads2k** [comment]
> Not sure if I understand your needs correctly. You want to have 2 different clients used in HorizontalPodAutoscaler controller:

I think two clients, along with an API that allows passing a `[]ObjectReference` (or some other unambiguously identifying information for Pods), would be the minimum bar to have a reasonably securable API.

I would still like to see two layered APIs.  One for getting the performance data and one composed on top to provide helpers for reading pods.  The HelpingClient would have a separate `PodNamespacer`.

**Comment by davidopp** [comment]
@piosz @mwielgus We're trying to move all the v1.2-candidate issues to v1.2 or next-candidate. IIUC this isn't going to be worked on in the next few days. If that is the case, please move it to next-candidate.

**Comment by piosz** [comment]
We are passing labelSelector to [Metrics API](https://github.com/kubernetes/kubernetes/blob/master/docs/proposals/resource-metrics-api.md) to fetch resource usage, so it's required by metrics client.
