### ISSUE TITLE
NFS recycler does not work in containerized kube-controller-manager

### ISSUE THREAD

**Issue by jsafrane** [kubernetes/kubernetes#16727]
When controller manager looks for a recycler for a NFS volume, it calls `nfsPlugin.CanSupport()`, which checks for presence of `/sbin/mount.nfs` or `/sbin/mount.nfs4`. Since controller manager is containerized, it does not see any such executables and returns `false`.

This is related to issue #14244, volume plugins are used both by kubelet, where checking for `mount.nfs` makes sense, and by controller manager, which does not need `mount.nfs` at all.

**Comment by jsafrane** [comment]
cc @kubernetes/rh-storage

**Comment by markturansky** [comment]
@jsafrane good find.

**Comment by markturansky** [comment]
This would effect other volume plugins, too, that check for binaries in `CanSupport(spec)`.  Those other plugins don't have recycler implementations yet, but they will.

@thockin @pmorie the least intrusive way to tell CanSupport to skip any kind of binary check might be a bool on volume.Spec that the recycler controller can set before calling CanSupport.  Only the plugins requiring a binary check would need to be changed.  Thoughts?

**Comment by markturansky** [comment]
This is a blocker in OpenShift that has this change in the NFS plugin.

**Comment by rootfs** [comment]
the downside of not checking binaries is that once recycler pod lands on a host that doesn't have the necessary binaries, the recycler will fail.

**Comment by markturansky** [comment]
@rootfs I believe we can squash this bug while keeping the change you made.

**Comment by rootfs** [comment]
@markturansky can the recycler pod mounts nfs without using host's /sbin/mount.nfs? if so, then indeed we don't need to care about the binaries. 
yes, making `cansupport` return more than bool will be great.

**Comment by markturansky** [comment]
@rootfs we have an issue to make `CanSupport(spec) (bool,error)` for more detailed errors.  I like the idea of looking for binaries to determine support.  It can make error handling (and debugging) much easier.

I am suggesting a flag on volume.Spec.  maybe `spec.RequireLocalBinary` or something that tells the plugin to look or not.   That way, Kubelet can correctly look for the required binary while the controller-manager does not.  This would work because the recycler pod itself will fail when kubelet looks for the binary and cannot find it.

**Comment by rootfs** [comment]
or just add another parameter to `cansupport` like `CanSupport(spec *api.Spec, requireLocalBinary bool)`, then we don't need to change spec.

**Comment by markturansky** [comment]
@rootfs that requires touching every single plugin.  the flag approach only requires changing NFS.

My approach may not be the best (awaiting confirmation from others), but it is the fewest number of changes.

**Comment by markturansky** [comment]
@jsafrane what about containerized kubelet?

**Comment by pmorie** [comment]
The check should be fixed for this in order to have NFS work with containerized kubelet.  What needs to happen for that is that the commands being execed should be run in the host's mount namespace, since that is where the mount operations run when the kubelet is containerized.  To support this correctly we probably need to make an `exec` interface, similar to the `chown`, `mount`, and `chmod` interfaces, that runs the container 

I agree, strictly for the recycler at this moment you do not need this check, but there are larger implications for this bug than the recycler problem.  It seems like NFS would be busted in general in a containerized state.  Do you agree @markturansky @jsafrane ?

**Comment by markturansky** [comment]
Yes, I agreed, @pmorie.   Also, I think doing these binary checks in CanSupport is probably the wrong place.  I think now it should be in builder.SetUp.  That func already returns error and we can return exactly the error (any specific binary is missing).

**Comment by jsafrane** [comment]
IMO, there is no good time to check for /sbin/mount.nfs, as Kubelet may be containerized and we can't easily check filesystem on the host. IMO we should check for it only when Kubelet is not containerized and at SetUpAt() time, not in CanSupport().

**Comment by pmorie** [comment]
@jsafrane I was suggesting that the check be done in the host mount namespace when containerized, similar to how the mount operation is done when the kubelet is containerized.

**Comment by jsafrane** [comment]
@pmorie, yes, that could work.

**Comment by pmorie** [comment]
I don't think the checks should move -- `CanSupport()` is the right method of the interface to perform the checks in.  They should just be made to work correctly when containerized using the method we already use for mounts.

**Comment by rootfs** [comment]
I agree to revert check. Let's find a better place do check binaries.

**Comment by markturansky** [comment]
@pmorie I will investigate your approach and nag you with questions, I'm sure.  The worst case scenario is to revert the check in NFS.

**Comment by jsafrane** [comment]
@pmorie, the check should not be in CanSupport(), as it's called also by kube-controller-manager running on master, which does not need to have mount utilities. To be precise, recycler controller uses volume plugins and calls FindPluginBySpec(), which then calls CanSupport(). https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/plugins.go#L276

**Comment by thockin** [comment]
How do you plan to recycle an NFS volume if you can't mount it?

**Comment by thockin** [comment]
Don't we have an "exec in root mountns" exec interface already?  That seems
best for now.  At some point the check needs to become an interface of
sorts so that we can container-ize the mount tools.

I am travelling today and rather busy this week, but I will try to follow
along.

**Comment by markturansky** [comment]
I think we need both:

1.  use the existing exec interface in CanSupport so that Kubelet running pods can correctly check for required binaries.

2.  Add a flag to bypass the CanSupport check so that the recycler controller can find the correct plugin knowing it will fail a check for binaries.  

The controller running in master uses CanSupport to find the correct plugin.   Kubelet uses CanSupport to find the correct plugin *and* validate it will run.

Only Kubelet requires use of the exec interface.

2 PRs, one for each point above.   The 2nd one fixes two uses case but leaves containerized kubelet effected.  That will be fixed by the 1st point.

**Comment by pmorie** [comment]
We need the controller manager to use the same infrastructure so that CanSupport() can run there, IMO.

**Comment by pmorie** [comment]
@markturansky so, can we close out #12650 and #16743?

**Comment by markturansky** [comment]
I already closed #16743.

Changing CanSupport to (bool, error) still gives us the ability to tell the user exactly why it fails (specific missing binary) as opposed to ham-fisted true/false and debugging hell to find the missing dependency.

**Comment by thockin** [comment]
@pmorie @childsb @jsafrane @rootfs @saad-ali 

Hey all,  I am clearing out old PRs and issues and realized this is still open.  I propose one of 2 solutions.

1) We leave this as-is.  If you ask for NFS on a system that doesn't have NFS tools available, Mount() will fail, hopefully with a decent error message.  The volume plugin is correct, the system is wrong.

2) We add a "CanMount()" interface to the API and callers who want to SetUp() should call that first.  We could go further and make FindMountableVolumePlugin call CanMount, but then it would indicate that no plugin was found, when clearly one was.

So I think #1 is the right choice.  Plugins should just produce good errors.  Given that, I am closing this.  Argue with me...
