### ISSUE TITLE
Pod does not start despite restartPolicy=OnFailure

### ISSUE THREAD

**Issue by rroopreddy** [kubernetes/kubernetes#16816]
I have a pod below that started in kubernetes cluster. Runs fine  for a while and then the minion restarts all pods after some event (refer : http://stackoverflow.com/questions/33068639/kubernetes-pods-some-die-after-running-for-a-day).

All pods under replication controller are back up except the pods that are **not under replication controller** but the **restartPolicy=OnFailure** is set

This is still happening and raised as an issue (refer: https://github.com/kubernetes/kubernetes/issues/15731) but is closed with the recommendation that create replication controller for event single instance pods. Just wondering why **restartPolicy=OnFailure** does not work when minion restarts

          {
            "kind": "Pod",
            "apiVersion": "v1",
            "metadata": {
              "name": "spark-driver",
              "labels": {
                "name": "spark-driver"
              }
            },
            "spec": {
              "restartPolicy": "OnFailure",
              "imagePullSecrets": [
                {
                  "name": "dockerhubkey"
                }
              ],
              "containers": [
                {
                  "name": "spark-driver",
                  "image": "test/spark-driver",
                  "resources": {
                    "limits": {
                      "cpu": "0.3"
                    }
                  }
                }
              ]
            }
          }

**Comment by yujuhong** [comment]
@rroopreddy, as I replied on stackoverflow earlier: If for some reason, your node becomes unready for > 5 minutes, node controller will evict all the pods on the node. Note that "eviction" actually means "deletion" -- your pods are no longer visible anywhere. If the evicted/deleted pods were managed by a replication controller (RC), the RC will create new pods meet the replica requirement. This does not apply to pods you created manually. They are simply gone, forever. Even after your node recovers from the catastrophe, it will *NOT* be able to restart your containers because there are no visible pods.

The best way to prevent this is to have replication controller monitors your pods.

**Comment by rroopreddy** [comment]
@yujuhong, thanks for the clearing this. This means, there are certain scenarios that will not use restartPolicy. The only way is to define one instance pod under replication controller.

**Comment by yujuhong** [comment]
@rroopreddy, restart policy works under normal scenario, but if does not apply to special conditions. Having replication controller to manage your pods are better practices :)

Closing this issue since it's resolved, but feel free to ask more questions on stackoverflow and/or our slack channel (http://slack.k8s.io/).
