### ISSUE TITLE
Taking network bandwidth into account for scheduling?

### ISSUE THREAD

**Issue by mali11** [kubernetes/kubernetes#16837]
Currently k8s scheduler only takes memory and cpu into account but since network bandwidth oversubscription widely exists in current data center networks, and the host itself has even higher oversubscription ratio when more and more number of pods run on a host, bandwidth contention could be a big problem for bandwidth sensitive applications.

Some thoughts about this problem:
1.	By adding pod bandwidth into request/limits factors as well the proper algorithms, it could solve the problem introduced by the host level oversubscription
2.	If we want to guarantee those special applications won’t get blocked anywhere in a cluster, we’ll probably need a full picture of the whole cluster network topology and take which into account in the algorithms of scheduler (e.g. nonblocking and blocking aggregate switches lead to different placements)

I’m looking to get opinions and ideas from the community.
Thanks!

@davidopp

**Comment by davidopp** [comment]
We've started on (1) in #11988/#12513 but currently don't have the cycles on our team to turn this into a full-fledged resource with scheduling like memory and cpu. If you'd like to implement something like that, feel free to add a concrete design to #2856 and we can discuss there. Please read the discussion on #12187 first -- you'd probably want to reuse parts of that PR.

(2) is more complicated and not something we've considered yet, as we haven't really received any requests for it. We'd be happy to review a design from someone who is willing to implement it, but we don't have cycles on the core team to implement this soon either.

I'm going to close this issue since the followup for (1) belongs in #2856, and if you want to discuss (2) you should file a new issue that is specific just to that feature.

Thanks for your interest!

**Comment by maflaven** [comment]
@davidopp has there been any more discussion on this? I'm working on a cache service that's bandwidth-sensitive and could really use the ability to schedule as a full-fledged resource.
