### ISSUE TITLE
Schedule a group of pods all at once (aka gang scheduling)

### ISSUE THREAD

**Issue by mali11** [kubernetes/kubernetes#16845]
Like many other schedulers, k8s scheduler is a sequential scheduler handles pods one by one.
This makes the architecture and algorithm simpler, but in some cases a sequential scheduler could make worse decisions than a scheduler which takes a group of pods into account, The sequential scheduler is like a “greedy algorithm” framework for pods placement.

I would like to suggest adding “group scheduling” support for the scheduler, and an ”all-or-nothing” result is reasonable I think.
Please share your thoughts.
Thanks!

@davidopp

**Comment by davidopp** [comment]
This is a useful feature but usually requires transaction support. Even in the case where you don't have multiple schedulers or multiple API servers (which makes this even more complicated), it's currently not possible to atomically commit multiple bindings. So for example the scheduler might crash in the middle of sending the bindings to the API server, and when it comes back up you need to ensure that the first thing it does is to finish sending the rest of the bindings it was sending when it crashed.

I think we eventually want this feature, but it would definitely not be in the next release. etcd v3 will be available some time around the beginning of the year, and it supports multi-object transactions, so at that point we can consider implementing support for this feature.

**Comment by pmorie** [comment]
@timothysc

**Comment by timothysc** [comment]
This touches on a number of other issues as well.  1st and foremost, is multiple schedulers. 

/cc @kubernetes/sig-scalability  

imho , we should probably move to consolidate around a couple of main epics.

**Comment by mali11** [comment]
@timothysc
Agreed, thanks for noticing me of multiple schedulers, one of the consequences I could imagine of adopting group scheduling is that it could lower the efficiency of the shared state and optimistic concurrency control based schedulers like google’s omega, making decisions for more hosts lead to more conflicts after all.
We may need to take group scheduling into consideration when choose the multiple schedulers architecture, such like is it resource shared or partitioned

**Comment by bgrant0607** [comment]
Even once we have multi-object transactions, we should never use it for this. It's unnecessary and the transactions would never succeed in practice.

**Comment by bgrant0607** [comment]
At minimum, we want:

1. To be able to evaluate nodes in parallel
2. To reuse the evaluation of multiple nodes for multiple pods

For workloads that want to be spread, greedy works just fine. and rescheduling (#12140) can gradually improve placement over time.

Mainly it's workloads that want to be co-located/packed that require gang scheduling. 

However, gang scheduling alone can't solve the problem. Reservation, squatting, and/or preemption would be required to ensure the necessary resources were free. And, once those features are implemented, greedy doesn't actually work too badly.

**Comment by bgrant0607** [comment]
It's also likely that gang-scheduled workloads would want gang admission control and/or temporal scheduling (queuing).

**Comment by davidopp** [comment]
> Mainly it's workloads that want to be co-located/packed that require gang scheduling.

I agree; that's what I interpreted this issue to be about.

> To be able to evaluate nodes in parallel
> To reuse the evaluation of multiple nodes for multiple pods

Yes, I'm going to work on this or find someone to work on this, for 1.2. It is needed for our scalability goals. But I think it's orthogonal to gang scheduling.

> gang scheduling alone can't solve the problem. 
> Reservation, squatting, and/or preemption would be required to ensure the necessary resources were free.

This is a good point--once the cluster gets full and fragmented, you can't expect all the resources you need to be available simultaneously (without a preemption scheme). And I guess if the cluster is relatively empty, you don't need transactions in the first place.

> And, once those features are implemented, greedy doesn't actually work too badly.

I think the main benefit of transactions is that it reduces to zero the amount of time you need to reserve/squat on resources before your gang becomes fully scheduled. Of course the tradeoff is what you said earlier, that the transaction may take a very long time to succeed.

**Comment by mali11** [comment]
@bgrant0607  @davidopp 

The background I raised this issue is because we have requirements to ensure the traffic bandwidth between pods are guaranteed for specific applications, which means we need to guarantee the bandwidth for pods in each level(host, TOR, aggregate, spine) of the topology, we can't rely on a non-blocking datacenter and it should be topology-independent.

On the other hand, these pods could apply some anti-affinity rules because of the needs of HA, this makes the bandwidth issue can't easily be solved by the co-location policies.

So the idea is to leverage gang scheduling, between-pods network description, topology visibility, bandwidth quota and taking bandwidth into account for scheduling(#16837) all together to address the problem.

**Comment by mali11** [comment]
> Even once we have multi-object transactions, we should never use it for this. It's unnecessary and the transactions would never succeed in practice.

Sorry I don't understand why the transaction would never succeed in practice, could you please elaborate further?

**Comment by davidopp** [comment]
I think the argument is that reservations or squatting are just as powerful as transactions but more likely to succeed in getting all your pods eventually scheduled.

Simple example: A cluster with two machines. One machine is running a pod P that takes up half of a machine, the other machine is empty. You submit a gang of two pods P1 and P2 that each take up a full machine. In the transaction approach, the transaction will keep failing until it catches a moment when both machines are empty. This moment may never come because the same or a different scheduler will simultaneously be trying to use the unused resources (the half of the one machine that's empty, and the whole machine that's empty) to schedule other pods. In contrast, with a reservation/squatting approach, you wouldn't use a transaction, but first you'd reserve the empty machine and the half of the other machine that's empty. Then when P terminates, you hope you can jump in and reserve the rest of the machine, which then allows you to start P1 and P2. Even if you aren't quick enough, at least you only need to wait for that half of the machine to become empty, as opposed to having to wait for both machines to be completely empty as in the transactional approach.

Basically the squatting/reservation approach lets you reserve resources for parts of your gang incrementally rather than having to wait for resources to be available simultaneously for all gang members. In a very full or fragmented cluster, this is likely to work better than transactions.

Now, your particular use case is interesting because you have a topology dependency among the pods in the gang. So it may not be as useful to incrementally reserve resources, since you don't really know where one pod should go until you know where all pods should go. For example, if you have a requirement that all pods in the gang must schedule onto the same rack. You can still use the incremental reservation approach, but you would possibly be continually reserving, releasing and re-reserving as you (the scheduler) changed your mind about which rack you ultimately want the gang to schedule onto. But it might be the case that those are also the scenarios where it's likely the transaction would take a very long time to succeed (e.g. a busy/full/fragmented cluster).

**Comment by mali11** [comment]
Thank you for the detailed explanation! I think I've got the point :)

>Now, your particular use case is interesting because you have a topology dependency among the pods in the gang. So it may not be as useful to incrementally reserve resources, since you don't really know where one pod should go until you know where all pods should go.

Yes, exactly. and in our case, the algorithm spends much longer time than the usual algorithms, that could make the situation even worse since it gives other schedulers more time to place pods to cause races.

I'm considering if there's different methods to solve this problem more simply such like: is it possible to allow only the pods which can be preempted to be scheduled in parallel before the ongoing gang scheduling job succeed if there is such an ongoing job. Or to make the rule looser that measuring the busy/full/fragmented levels and limit the parallelization of scheduling based on the levels. Parallel scheduling doesn't help in a full cluster anyways.

The other aspect of the issue and is what I concern most currently is that I didn't find a better alternative solution instead of using gang scheduling for my particular use case.
I would like to collect more advice from the community before moving further.

**Comment by timothysc** [comment]
@mali11 .. Do you **really** need gang scheduling for your use case? The most common use case for 'gang scheduling' is MPI, where coordinated group start is important.  Resources can sometimes be hoarded/reserved in order to gather enough resources for the coordinated start.   Now-a-days this is more of an exception then the norm.

**Comment by mali11** [comment]
@timothysc I wish I don't have to ;P
>  The most common use case for 'gang scheduling' is MPI, where coordinated group start is important. Resources can sometimes be hoarded/reserved in order to gather enough resources for the coordinated start.

Yes, I agree, as @bgrant0607 also mentioned above, reservation, preemption are needed for this use case as well and after we get them implemented, greedy works not so bad.

But what I want is to make the scheduler more generic that allows different users could handle their edge use cases gracefully without making ugly workaround, An example is the [IBM PRS holistic scheduler plugin](http://www.slideshare.net/JarekMiszczyk/practical-advice-on-deployment-and-management-of-enterprise-workloads) to openstack which really is not something I want to do.

**Comment by davidopp** [comment]
> But what I want is to make the scheduler more generic that allows different users could handle their edge use cases gracefully, A counter-example is the IBM PRS holistic scheduler plugin to openstack which really is not something I want to do.

We support a number of mechanisms for users to customize the scheduling functionality:
* Write your own scheduler (either replace the default one completely, or run yours side-by-side with the default one): https://github.com/kubernetes/kubernetes/blob/master/docs/proposals/multiple-schedulers.md
* Write a scheduler extender: 
https://github.com/kubernetes/kubernetes/blob/master/docs/design/scheduler_extender.md
* Modify the default scheduler, adding your own predicate and priority functions, recompile the scheduler, and then select your new policies using the scheduler policy config file: https://github.com/kubernetes/kubernetes/blob/master/docs/devel/scheduler.md

We also allow users to modify the lifecycle behavior of Pods by writing a new controller or modifying an existing controller.

Can you give an example of a use case that is not easily handled by one of the above approaches?

**Comment by mali11** [comment]
@davidopp, Thank you for summarized the scheduler extension approaches, that helps!

I've read them but I think it's not easy to handle my use cases.
Let's say I have a gang includes 1 ReplicationController and 1 Pod, there's no API allows me to send them as a whole to the scheduler in the first place.

Somehow I could manage to schedule them as a whole by customizing the scheduler and make some trick on the pod to let the customized scheduler understand those pods from one gang should be cached then be scheduled as a whole.

Or I can query a 3rd party service from scheduler see if there's already a placement plan for the pods fetched from the queue.
Later I might need to find the other way to delete them as a whole...

This is neither easy to use nor robust, and I believe adding the abstraction of Gang to k8s is the better way.

Currently I'm working on an initial design on adding gang scheduling to k8s and would you mind if I raised an proposal then anyone who interested can take a look and give advice?
If it turned out benefits k8s I'd be happy to implement it.

**Comment by davidopp** [comment]
I read your PR and your comments above, but I'm still not understanding your use case.

Can you tell me specifically what application you're running that requires gang scheduling?

**Comment by mali11** [comment]
@davidopp Sure, please see the below.

Given a cluster with the available resources:
node1: 10 cpu cores
node2: 12 cpu cores

And I have 3 pods to create each requires:
pod1: 8 cpu cores
pod2: 6 cpu cores
pod3: 6 cpu cores

There's only one solution to successfully place them all:
host1: pod1
host2: pod2+pod3

But when sequentially schedule then, it needs different policies depends on the sequences of creating the pods:
A) Create pod1 first, need to apply a "packing" policy
B) Create pod2 or pod3 first, need to apply a "spreading" policy
so I think it's not easy for a sequential scheduler to handle this

**Comment by davidopp** [comment]
Sorry, I am not being clear.

By "application" I mean something like nginx, MySQL, or some application you wrote yourself (in which case please describe what it is doing -- financial transactions, data mining, graphics rendering, high-performance scientific computing, etc.) and why the processing model of the application requires gang scheduling.

**Comment by mali11** [comment]
oh, sorry, now I understand :)

It's for the telecom network functions. traditionally there're strong dependencies(network bandwidth, latency, ...etc.) among the hardware devices in an application, which leads to strict deployment requirements. As NFV was introduced, they were transforming to be software services but for some of them, however the dependencies remains, and still we want to make them work smoothly in a k8s managed cluster and the gang scheduling is one of the tool we want to leverage.

**Comment by HaiyangDING** [comment]
@mali11 

Just out of curiosity, do you work for Huawei? (Or other telecom providers?) I am also interested in your use cases.

**Comment by mali11** [comment]
@HaiyangDING You guessed it! sorry I forgot to complete my profile page

**Comment by jeremyeder** [comment]
NFV use-case is a specialization of the features written up in #10570

**Comment by mali11** [comment]
@jeremyeder  Thanks for the information, we're also interested in that feature.

**Comment by mitake** [comment]
Hi, I'm interested in this idea for deploying learning tasks of deep learning frameworks e.g. tensorflow.

If we execute distributed learning task of DL, the pods (PS tasks and worker tasks in the case of tensorflow) related to the learning task must be executed at once. Executing some of the pods and not executing others cannot start the learning task. The motivation is described in my lightning talk at this year's kubecon: https://schd.ws/hosted_files/kccncna17/95/kc_cnc_na17_mitake.pdf (from page 7 to 9).

Currently we are solving this problem with in-house custom scheduler. But if this gang scheduling can be implemented in the default scheduler, it is really helpful for us because of the reduced maintenance cost. Also, some people working on DL on k8s are interested in this idea so the requirement is not so small for the use case of DL. If it is acceptable, I'd like to port our custom scheduler to the default scheduler. How do you think?

**Comment by davidopp** [comment]
See https://github.com/tensorflow/k8s/issues/165

**Comment by mitake** [comment]
@davidopp thanks for the pointer, I'm looking at the issue.

**Comment by bgrant0607** [comment]
Replaced by #61012
