### ISSUE TITLE
Feature Request: Ability to WATCH more than one resource type

### ISSUE THREAD

**Issue by derekwaynecarr** [kubernetes/kubernetes#1685]
Our team is looking to build a web-based user interface for Kubernetes.

We are interested in the page dynamically updating as Kubernetes changes are made to the system, and we are interested in using web sockets to meet our need.  Our goal is to have a single web socket open per browsing session to the Kubernetes application.  This is due to best-practices, and browser limitations for the number of open connections to a particular host.  For some background on these limitations, see here:

http://stackoverflow.com/questions/12475462/html5-websockets-max-number-of-open-connections

Since our interface aggregrates changes to multiple resource types within a namespace (pods, replication controllers, services, etc) into a view, we are interested in enhancing the WATCH support in Kubernetes to accept more than one resource type so we can dynamically respond to changes.

This issue is intended as a discussion to see if upstream is agreeable to this concept, and if there should be some limitations on the number of resource types a single WATCH request can observe.

For example,

```
/api/v1beta1/watchAll?resourceType=pod&resourceType=service
```

could be supported by modifying our WatchServer as follows:

```
type WatchServer struct {
    watching []watch.Interface
    codec    runtime.Codec
}
```

and then modify the current for-loop to iterate over each watch.Interface in the slice.

It is possible we may have use-cases for internal Kubernetes daemon's finding this useful, but for our intended web application, the WATCH across resource types would always be scoped to a particular Kubernetes namespace.

**Comment by sym3tri** [comment]
+1. This is a crucial feature for us too and anyone building a live-updating UI.

**Comment by ncdc** [comment]
Any additional suggestions how to implement this given the current state of the REST API? I'm guessing that the /watchAll suggestion isn't what we want going forward? cc @smarterclayton @kubernetes/sig-api-machinery

**Comment by smarterclayton** [comment]
I discussed this briefly with various folks recently.  The ideal interface for a web client might be more along the line of a subscription API - clients connect, ask for a watch starting from X, and get resources until the watch expires / fails.  That's a more complex change, but reflects the actual use case of our web UI team (since one watch break does not imply other watch breaks, and as you navigate around you may wish to stop / start watching various resources).

Also, the disconnected nature of watches means you want to push this down to the API server where possible, but have to handle watches across potentially many backgrounds, which makes this more the domain of the API federator / summarizer (an authorizing proxy that hides the details of multiple backends).  That complicates the short term implementation, because we don't have a summarizer yet.

We've discussed generic bulk actions and bulk watch (at recent API sig meetings), but neither is particularly close.  It's not clear to me that if we wanted to push in the short term (to unbreak folks on IE who have >6 watches) what the clearest path would be given the lack of design.

**Comment by jwforres** [comment]
For browser clients this is becoming an issue because of the limitation to 6 same domain websocket connections in IE and Edge https://msdn.microsoft.com/en-us/library/ee330736(v=vs.85).aspx#websocket_maxconn

With all the new controller types we are having to revert to polling in some cases because we have passed the limit.

**Comment by lavalamp** [comment]
Browser clients scare me a lot right now because our API is *not* XSS safe!!

On Mon, Aug 22, 2016 at 2:11 PM, Jessica Forrester <notifications@github.com

**Comment by joeatwork** [comment]
This feature would be a *huge* win for us, and for UI clients generally (browser and otherwise)

**Comment by derekwaynecarr** [comment]
@lavalamp - lets discuss this in an upcoming sig api machinery meeting, I think we will want to push for this in 1.5 release.

**Comment by philips** [comment]
cc @hongchaodeng @xiang90

**Comment by mfburnett** [comment]
What is the latest on this? @derekwaynecarr @lavalamp

**Comment by smarterclayton** [comment]
Not on the near term roadmap.

On Tue, Feb 28, 2017 at 5:50 PM, Mackenzie Burnett <notifications@github.com

**Comment by smarterclayton** [comment]
Part of kubernetes/community#443

**Comment by gopinatht** [comment]
Hey Guys, I see this issue frozen but is there any news on being able to bulk watch multiple resources?

**Comment by wojtek-t** [comment]
https://github.com/kubernetes/kubernetes/pull/57792

**Comment by mitar** [comment]
@thockin Care to link to some more information about how has this been completed?

**Comment by smarterclayton** [comment]
Accidental?  We don’t have any of the infra for this that Im aware…

**Comment by liggitt** [comment]
it hasn't been completed... github started adding "completed" language any time anyone closes an issue by default

**Comment by mitar** [comment]
OK, then why was this closed?

**Comment by liggitt** [comment]
it's closed as unplanned

**Comment by jwforres** [comment]
So this means we've officially given up on ever doing multi watch?

With the overall change in support for the IE browser this issue is less painful than it was when it was opened.

**Comment by logicalhan** [comment]
> So this means we've officially given up on ever doing multi watch?
> 
> With the overall change in support for the IE browser this issue is less painful than it was when it was opened.

Out of curiosity, why do you want multi-watch?

**Comment by smarterclayton** [comment]
Prior to HTTP2 this was a pretty large issue for clients watching a substantial number of resources (as UIs tend to do), since you could have a thousand users watching a hundred resources.  Post HTTP2 it is less impactful overall, although I think in general every client / controller watches or cares about multiple resources at the same time, and there is amplified overhead on reconnect.

While our clients are more mature today, correctly caching sets of things is still hard.  Being able to move more of the construct to the api has advantages.

Agree it’s still missing a “must have use case” and someone to prioritize it.

**Comment by jwforres** [comment]
Yeah the critical issue that caused us to originally open this issue is just no longer a problem. Other browsers do not have the very small connection limit that IE had.

There are other API server improvements in the area of websockets that @spadgett and I would prioritize much higher now. I'm good with letting this one fall off the radar until a critical need comes up.

**Comment by lavalamp** [comment]
IMO HTTP2 solves this good enough and I don't plan to do anything visible to the API to support this unless someone can come up with a critical use case.

**Comment by wojtek-t** [comment]
I was looking into it in the past too with this "bulk watch" support design even merged in the past:
https://github.com/kubernetes/community/pull/443/files

But with http2 the scalability usecase is no longer valid and I agree with @lavalamp that I don't see a critical enough usecase for pretty complicated changes that would be needed to proceed with it.
