### ISSUE TITLE
Volume mounting a file is ambiguous (vs a directory)

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#16888]
I deleted /var/log/kube-scheduler.log, and restarted the kube-scheduler. (on a test cluster, of course!)

When the container restarts, someone does a mkdir on /var/log/kube-scheduler.log.  (that causes kube-scheduler to crash, because it tries logging to that directory as if it were a file).

I believe the problem is that the manifest syntax has no way to differentiate a file vs a directory when the source path does not exist.  I think we might need a "type: file" attribute in the hostPath spec to disambiguate.

The manifest from my cluster:

```
{
"apiVersion": "v1",
"kind": "Pod",
"metadata": {
  "name":"kube-scheduler",
  "namespace": "kube-system"
},
"spec":{
"hostNetwork": true,
"containers":[
    {
    "name": "kube-scheduler",
    "image": "gcr.io/google_containers/kube-scheduler:45c19e7118b9bd03d663736999cb42af",
    "resources": {
      "limits": {
        "cpu": "100m"
      }
    },
    "command": [ 
                 "/bin/sh",
                 "-c",
                 "/usr/local/bin/kube-scheduler --master=127.0.0.1:8080  --v=4 1>>/var/log/kube-scheduler.log 2>&1"
               ],
    "livenessProbe": {
      "httpGet": {
        "host": "127.0.0.1",
        "port": 10251,
        "path": "/healthz"
      },
      "initialDelaySeconds": 15,
      "timeoutSeconds": 15
    },
    "volumeMounts": [
        { 
          "name": "logfile",
          "mountPath": "/var/log/kube-scheduler.log",
          "readOnly": false
        }
      ]
    }
],
"volumes":[
  { "name": "logfile",
    "hostPath": {
        "path": "/var/log/kube-scheduler.log"}
  }
]
}}
```

**Comment by dchen1107** [comment]
I just realized that this should be a bug which might be caused by some races between the logging file is created initially and Kubelet tries to mount the existing volume since @justinsb mentioned above that he deleted /var/log/kube-scheduler.log. For HostPathVolumeSource type volume, we assume the HostPath is a pre-existing file or directory. But upon NotExist case, we must did some assumption in the code. 

cc/ @saad-ali

**Comment by thockin** [comment]
Is the right fix really to change the API?  It feels very special to me,
but I admit I don't have any better ideas, short of mounting the whole dir
into the pod.  And in fact, that might be the righter choice.

What happens when the log file gets big?  Do we do rotation?  The way bind
mounts work, any rotation done from outside would have to truncate the
file, rather than rename a new one into place - what is bind mounted is an
inode.  This is a really clunky way to do logs - why are we not logging to
stdout/stderr like we tell everyone else to do?
