### ISSUE TITLE
Add an opaque "container runtime params" object to api.Container

### ISSUE THREAD

**Issue by brendandburns** [kubernetes/kubernetes#17064]
We need to be able to parameterize the various container runtimes without having to add ever single configuration variable into our API.

To achieve this, we should add an opaque `params` object to `Container` this params field will be raw JSON, we can then use reflection to dynamically populate the API calls to the container runtimes.

@bgrant0607 @dchen1107

**Comment by bprashanth** [comment]
Can't we just give annotaitons to subobjects? I want this for Ingress configuration too (https://github.com/kubernetes/kubernetes/issues/16891), configuring sub-objects (in this case IngressBackends) through a single global annotation dict gets nasty.

**Comment by brendandburns** [comment]
Yes, one option here would be to use annotations, but I would like annotations to be `map[string]interface{}` rather than `map[string]string` which is a breaking API change, so we'd have to introduce a separaete `params map[string]interface{}` rather re-using annotations.

--brendan

**Comment by bprashanth** [comment]
Eitherway I would find this useful. There's high enough variance between loadbalancers that I'm not comfortable making these "runtime params" fields on the top level object. The top level yaml should be cross platform, users of the runtime params understand the consequences of lock-in.

**Comment by bgrant0607** [comment]
I agree this would be useful, but there are details to figure out. 

Presumably these params would map to the Docker client we use, rather than the remote API itself?
https://github.com/fsouza/go-dockerclient/blob/master/container.go#L187

And the params would be deserialized directly into that struct? We'd still be limited by the version of that client we were pinned to.

We'd need to document that in detail.

We'd also have to specify which fields can't be overridden, since Kubelet sets them, and we'd want to validate that.

**Comment by bgrant0607** [comment]
Re. a more general form of annotations: #12226

**Comment by thockin** [comment]
I have come around on this.  As long as it is patently obvious that
whatever you are doing in params might get subsumed by the API later, I can
live with it.  It seems very hard to implement cleanly, though

**Comment by ravilr** [comment]
@kubernetes/sig-node there are atleast 2 issues asking to support configuring container runtime options (MemorySwap, MemorySwappiness, shmSize per container ):
https://github.com/kubernetes/kubernetes/issues/28272
https://github.com/kubernetes/kubernetes/issues/7294#issuecomment-252374355

In addition to pod/container spec changes, i think new CRI interface should also support opaque container runtime config params.

**Comment by thockin** [comment]
It's still unclear to me how to pass params we don't understand through to
Docker without knowing how to map those to docker's JSON API.

**Comment by fxposter** [comment]
@thockin What about having the per-runtime map of `params` to runtime-specific options, but do not expose anything out of those on the kubernetes API side, IE: runtime can just extract the params that it knows and ignore all others?
Otherwise - are there any ways of achieving passing arbitrary docker params to some containers? I suspect that it may be possible to fork docker CRI shim and change it to company-specific needs (at least it's not maintaining a fork of full kubernetes), but from my perspective - it would be better if all those options live in official kubernetes contiainer runtime repos, even if they are opaque from the kubernetes API perspective. WDYT?

**Comment by thockin** [comment]
What does that map look like?  For example, the docker API has many nested
structs, some of which hold further maps and lists.  To be extensible, an
end user would need to be able to override basically arbitrary structures.
A JSON patch string?  If we want something here we need a spec that covers
how to do it and what is and is not possible.


On Jan 21, 2017 6:08 AM, "Pavel Forkert" <notifications@github.com> wrote:

@thockin <https://github.com/thockin> What about having the per-runtime map
of params to runtime-specific options, but do not expose anything out of
those on the kubernetes API side, IE: runtime can just extract the params
that it knows and ignore all others?
Otherwise - are there any ways of achieving passing arbitrary docker params
to some containers? I suspect that it may be possible to fork docker CRI
shim and change it to company-specific needs (at least it's not maintaining
a fork of full kubernetes), but from my perspective - it would be better if
all those options live in official kubernetes contiainer runtime repos,
even if they are opaque from the kubernetes API perspective. WDYT?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/17064#issuecomment-274263857>,
or mute the thread

**Comment by fxposter** [comment]
You would not be able to "extend" it, but this is usually not what is needed - you usually need to add additional params specific to runtime to containers on starting - and those can be specified by "runtume shims". IE - dockershim would expose all `docker run`-specific attributes and the end user may just use them by passing string options.
Yes - these would be runtime version specific (ie: until dockershim updates to specific docker api version - you would not be able to pass those).

**Comment by thockin** [comment]
I was hoping for something that didn't require us to explicitly support
features, even as annotations.

**Comment by vishh** [comment]
@thockin @ravilr I don't think the features mentioned in https://github.com/kubernetes/kubernetes/issues/17064#issuecomment-253005442 should be exposed as arbitrary knobs. There have discussions in other PRs for supporting (or not supporting) swap, shm, etc.
Do we have concrete use cases for needing opaque runtime params?

**Comment by thockin** [comment]
This has been an issue forver - user wants to do something we haven't added
yet or don't want to add, or just can't decide on what API to expose..

**Comment by vishh** [comment]
I still don't get the entire workflow. Are we expecting kubelet to support
arbitrary runtime features or is it just a matter of providing a
placeholder in the API and let users run a custom runtime that can
interpret such features? If its the latter, why doesn't pod annotations
work?

**Comment by thockin** [comment]
Annotations require kubelet to understand them.  That may be the best we
can do, but I was hoping for a way for an end-user to offer a "patch"
against Docker's API JSON, or something similar, so that kubelet doesn't
need to interpret it at all.

**Comment by feiskyer** [comment]
Maybe we could add some json-encoded dockertypes.Config or dockertypes.ContainerCreateConfig (which includes both Config and HostConfig) in annotations and merge it with dockertools generated one.

**Comment by fxposter** [comment]
@vishh @thockin I personally would like to have at least shm-size and log-driver options to be supported, but I don't think it should be the solution specific to kube API. it would be better to have arbitrarily container runtime options supported. So that it would be possible to set them and kubernetes should not need any specific behavior for those options, except properly passing them to runtimes.

And from my perspective - hardcoded list of those options per runtime is just fine - if there would be new docker options useful to people - it would just be a matter of pull request adding them. The current problem is passing those options to dockershim/dockertools packages.

**Comment by thockin** [comment]
The balance to strike is that if enough people need something we should
find a proper way to express it.  This should really be for seldom-used
things where kubernetes is just "in the way", but making actual code
changes for those cases is not cool.  That's why I am hoping for something
really transparent.

**Comment by sighingnow** [comment]
I'm wondering the status of this issue, or, is there any chance/possibility to pick it up and implement such features in official kubernetes repo? to support custom docker runtime arguments.
