### ISSUE TITLE
Add support in quota to allow run once pods to satisfy a maximum "rate"

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#17098]
Run once pods are not well accounted for by the current quota system, because run-always pods can absorb the quota and prevent jobs from running (builds, scheduled tasks).  We discussed today a "pods per unit time" measure with "max run once pods" that allow for users to run short jobs in parallel or over a longer time.

Since run always pods are typically "run up to N pods that run 24 hours a day", it's natural to want to state "run up to 3 pods at most 6 hours a day".  Whether that is 6 hours for one pod or 2 hours for each of 3, the end metric would be applied.  This may be continually refilling (useful).

**Comment by smarterclayton** [comment]
@derekwaynecarr

**Comment by derekwaynecarr** [comment]
**Some background:**
I am working on making the quota system more rapidly observe freed up compute resources in response to pod state changes.  This will greatly assist users that want to run many short-lived run-once pods by not having to wait for the quota system to recognize that compute resource is available.  Hope to have a PR this week.  We should then provide some measure of QoS on how rapidly we expect the quota system to observe freed-up compute.

**Back to this topic**
I think this scenario only really makes sense when running **BestEffort** pods.  We had previously discussed the quota system to allow a particular number of **BestEffort** pods even when cpu/memory hard limits are defined on the quota.  If possible I would prefer to tie quota changes more to quality of service tiers, and less to a particular controller requirement.

With that in mind, would it be sufficient to do the following:

1. Quota can set hard limits for cpu/mem for **Burstable/Guaranteed* tiers
2. Quota can set hard limits on total object count for pods (across all tiers)
3. Quota has flag to allow **BestEffort** pods even when compute resource limits are defined
4. Quota has flag to say how many **BestEffort** pods may be active
4. Quota is faster at observing changes to compute usage, pod counts in general

Job is updated to say:
1. run up to 3 pods at most 6 hours a day using concepts previously discussed (active deadlines).

And in this case the pods spawned by the Job were **BestEffort**, and it would be capped at 3 per the quota limiting to 3 best effort pods at a time.

If the job was not making **BestEffort** pods, in practice those pods will and should be counted against the cpu/memory compute resources it consumes like anything else.

**Comment by bgrant0607-nocc** [comment]
Related: #13567

cc @davidopp @erictune @mml

**Comment by bgrant0607** [comment]
@derekwaynecarr I agree on rates for terminating pods. For bounded-duration resources, we want to control rates. For indefinitely existing resources, we want to control footprint.

I was thinking that Jobs of BestEffort pods would just be run in a different namespace than indefinitely running pods.

If we added a cap on the number of BestEffort pods, I don't see why we'd also need a flag.

**Comment by derekwaynecarr** [comment]
@bgrant0607 - I know in OpenShift, I have use cases for running a BestEffort pod in the same namespace that has quota on compute resources.  For those use cases the operator may want to think of those pods as just cost of running infrastructure, but does not want run them in a separate namespace (need shared access to secrets).  Examples include our build and deploy pods.

Agree that flag/cap on number is the same and could be combined.

**Comment by derekwaynecarr** [comment]
PR to make resource quota respond to freed compute resources via watch notification is here:

https://github.com/kubernetes/kubernetes/pull/17133

**Comment by smarterclayton** [comment]
Are builds and deployments best effort?  Depending on who you ask, they
aren't.

**Comment by derekwaynecarr** [comment]
@smarterclayton - i agree its operator specific - but aside from the use case, i think its fair for an admin to say i give you X amount of burstable/guaranteed resource and Y best-effort tasks to run whatever (jobs of any kind) seems sane to me.

**Comment by bgrant0607** [comment]
One axis is QoS: BestEffort vs. Burstable/Guaranteed.

Another axis is terminating (restart Never/OnFailure) vs. not (restart Always).

We could potentially ignore the second axis by making it possible to express creation rates by QoS class. The indefinitely running pods will consume negligible creation rate quota except in pathological situations, which we should mitigate by making controllers smarter.

**Comment by davidopp** [comment]
> Quota has flag to allow BestEffort pods even when compute resource limits are defined
> Quota has flag to say how many BestEffort pods may be active

Isn't the first thing implied by the second thing (namely, whenever the second thing is > 0) ?

On the more general question... My understanding is that
(1) we want to control rate to prevent people from abusing the cluster manager
(2) we want to control footprint to fairly share the nodes
(3) we want to control total number of best-effort pods simultaneously active because they have zero footprint by definition, hence (2) cannot be used for them

Why isn't the following spec sufficient?
* max pod creation rate
* max total footprint of guaranteed and burstable pods
* max number of active best-effort pods

(If this is actually what is being proposed, and I just misunderstood, my apologies.)

**Comment by smarterclayton** [comment]
4) we want to prevent certain pathological starvation issues regarding
run-always pods when users operate under limits, but not have to over
allocate quota to stay safe.
5) allow very small limits to be sanely specified - I.e. run 1 run-always
and no more than 10 minutes of run once pods per hour.
6) we want to limit some users below "fair share of the cluster" by default

It's too easy under the schemes proposed to fill the guaranteed footprint
with run always pods when users are operating in the context of limited
resources.  That sets up a perverse incentive to never set limits on
run-once pods and jobs that *must* run.

I suspect most people setting quota for resources want to set aside some
quota for jobs so they can happen, just because it's easy to reason about
(best-effort seems much harder to explain).  The downside is the admin
can't easily set limits smaller than 1 pod for run-once pods, and users
have extra resources that aren't fungible (10 run-always and 2 run-once).

That's probably acceptable in a majority of scenarios, but really sucks
when your limit is 1 or 2 pods.  A combination of max active deadline and
creation rate can probably solve that in a way that prevents gaming, in
which case best-effort really is an orthogonal concern.

I suppose any scenario in which a cluster controller is running resources
in a namespace on behalf of the user requires that the cluster admin
carefully prepare quota.  We *could* potentially satisfy 4 and 5 with a
different set of quota patterns - applying a quota on those resources based
on the controller, not the owning namespace.


On Nov 15, 2015, at 4:16 AM, David Oppenheimer <notifications@github.com>
wrote:

Quota has flag to allow BestEffort pods even when compute resource limits
are defined
Quota has flag to say how many BestEffort pods may be active

Isn't the first thing implied by the second thing (namely, whenever the
second thing is > 0) ?

On the more general question... My understanding is that
(1) we want to control rate to prevent people from abusing the cluster
manager
(2) we want to control footprint to fairly share the nodes
(3) we want to control total number of best-effort pods simultaneously
active because they have zero footprint by definition, hence (2) cannot be
used for them

Why isn't the following spec sufficient?

   - max pod creation rate
   - max total footprint of guaranteed and burstable pods
   - max number of active best-effort pods

(If this is actually what is being proposed, and I just misunderstood, my
apologies.)

—
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/17098#issuecomment-156793211>
.

**Comment by davidopp** [comment]
>  That sets up a perverse incentive to never set limits on
run-once pods and jobs that *must* run.

I assume you mean request, not limit. Isn't the disincentive to not setting an accurate request that you might get starved?

I wonder if some of your scenarios for run-once are better solved by a billing system that charges for usage, rather than an admission control system.

**Comment by smarterclayton** [comment]
A lot of our use cases like this come up from overzealous admins - who
conserve under conditions of scarcity today, and want to continue to
conserve in the future.  They often want to set strict limits - but that
complicates any "pod machinery" use cases.  They don't want to allow
unbounded job execution for various reasons (which are sometimes wrong, but
are also human policy things, rather than ideal).

To summarize - best effort doesn't have any disagreement so far.  There may
be a use case in the future to limit run always vs run once via two
separate pools.  We can potentially solve this with alternative quota
systems.

On Nov 16, 2015, at 12:29 AM, David Oppenheimer <notifications@github.com>
wrote:

That sets up a perverse incentive to never set limits on
run-once pods and jobs that *must* run.

I assume you mean request, not limit. Isn't the disincentive to not setting
an accurate request that you might get starved?

I wonder if some of your scenarios for run-once are better solved by a
billing system that charges for usage, rather than an admission control
system.

—
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/17098#issuecomment-156919421>
.

**Comment by mml** [comment]
> provide some measure of SLA on how rapidly we expect the quota system to observe freed-up compute

This is a somewhat low-level detail.  I think internally we might want to have an engineering target, but users probably would prefer a general end-to-end measure that contains this, which is time from submission of a pod (or equivalently from freeing up enough resources to schedule a pending pod... this is the case that includes the speed of the quota system) until it's actually been handed to the kubelet.

**Comment by mml** [comment]
> Run once pods are not well accounted for by the current quota system, because run-always pods can absorb the quota and prevent jobs from running

@smarterclayton I'm not sure I understand the root issue here.  Are you saying "if we give out all the quota, and users use all the quota (for run-always pods), then there isn't any left (for run-once pods)"?

**Comment by smarterclayton** [comment]
Yes.  Users aren't the ones setting the quota, and they don't know all the
run-once pods that might run under their quota (on their behalf) by other
systems (builds, custom deployments, hooks, etc).  Preventing unintentional
starvation in a default setup is the scenario I'm focused on identifying a
solution to.  The "burst" or "best-effort" buckets are appropriate here.
Note this is generally a small quota problem, not a massive quota.

**Comment by mml** [comment]
One way to look at the problem here is that it derives from the fact that secrets and quota are partitioned along the same lines (namespaces).  There is no way to earmark quota except to say that it's usable by anything in namespace X, and the secrets are isolated in the same way.

How much of this could be solved by allocating the desired test/build resources into namespace X-test and simply duplicating the secrets into both X and X-test?  Now pods may run in X-test with access to the secrets and they have a token amount of resources for burstable work, and perhaps a very generous number of allowed pods.

**Comment by smarterclayton** [comment]
Could certainly work, although there are challenges.  It requires all the
parallel systems (authz policy, service accounts, pod security policy) to
understand that duplication, and correctly account for it.

Ultimately, that does sound like an admission that there are operational
reasons to distinguish the two.  Burst is valuable in lots of cases,
although it's much harder with run-always to enforce the correction.  At
least with jobs we can control rate, duration, and breadth.

On Nov 18, 2015, at 7:06 PM, Matt Liggett <notifications@github.com> wrote:

One way to look at the problem here is that it derives from the fact that
secrets and quota are partitioned along the same lines (namespaces). There
is no way to earmark quota except to say that it's usable by anything in
namespace X, and the secrets are isolated in the same way.

How much of this could be solved by allocating the desired test/build
resources into namespace X-test and simply duplicating the secrets into
both X and X-test? Now pods may run in X-test with access to the secrets
and they have a token amount of resources for burstable work, and perhaps a
very generous number of allowed pods.

—
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/17098#issuecomment-157904339>
.

**Comment by erictune** [comment]
Seems like there are two or three issues here.

The first problem is that there is no way to have quotas that treat pods in the same namespace differently.   You have this problem even between two run-always things (e.g. frontend and backed RCs, each autoscaled: if one spikes like crazy, it can stop the other from ever stopping, or even from doing a rolling update); and you can have it between two run-once things (e.g. two cron jobs that ususally run at different times, but sometimes collide, due to funky schedules).

The second is that, as a multi-tenant service provider, iI want to allow someone to consume an amount of resources which is small enough over the course of a day or week to deter abuse, but large enough over a minute or hour to be useful to the customer.  Currently, I have no way to express that.  This kind of burstability could be useful for both autoscaled long-running things, and for Jobs.

I think the solution to the first problem is to allow Quota to be accounted at finer granularity than a namespace.  I think that is pretty easy to do and I'll say how to do that in a follow-up comment.

The second problem is trickier.  For the current quota system, there is no automated way to reduce quota consumption.  For the rate-based quota, you definitely need a way to do that.   And users will want to control, when the start things, whether they are using the "forever quota" or the rate-based thing, which is sort of a short-term loan.

**Comment by erictune** [comment]
For the problem of fair-share within a namespace, I'd suggest the following:

1. add a field to the ResourceQuotaSpec called "Selector *LabelSelector".   
1. allow there to be many ResourceQuota objects in a namespace
1. If there is no `Selector`, then the namespace matches all objects in the namespace.
1. If there is a `Selector`, then only pods matching that selector are charged against this quota bucket.
1. All matching ResourceQuota objects are checked and incremented (an issue here with doing this atomically?)
1. users within a namespace can write their own ResourceQuota records to further divvy up resources.  add a new kind of quota that counts resources with label on it in a certain namespace as well.
1. Cluster admin continues to create a primary ResourceQuota that applies to the whole namespace, and is the overall limit on resource usage.  Since all matching ResourceQuotas are used, and normal users can change this object, there is no way for users to sneak more resources by creating their own ResourceQuotas.   
1. The object-count quota on ResourceQuota objects prevents users from overloading the apiserver with large numbers of ResourceQuota objects.

I can also see the value in either matching on QoS or matching on an annotation or label that is already applied that states the QoS of the Pod (xref  #18262)

**Comment by erictune** [comment]
For the problem of bursty quota, you are introducing the concept of Pods that can be terminated at any time if they exceed the rate calculation.  This is somewhat different from what we currently mean by QoS.

**Comment by smarterclayton** [comment]
Alternatively (not that I don't like the proposal), we could assess
quota per service account.  In which case we could reuse many of the
concepts but simply measure each service account if there is a
corresponding quota.  There could still be the overall quota.

I like the implied flexibility of the proposal you sketched out.  Is
this partitioning system natural for end users?  It allows very
selective targeting easily (limit the pods governed by an RC by
reusing the exact selector of the RC).  It also encourages composition
of quota over other sets (services)

**Comment by smarterclayton** [comment]
To a user, isn't it still equivalent to Best Effort?  When we evict,
we provide no guarantee to the timeliness of your reschedule.  I guess
implicitly we are saying these are best effort by that - if you need
guaranteed resources, you effectively can only do so to the limits of
your rate.

**Comment by erictune** [comment]
I think the intent of the current QoS specifications is a Node-level QoS.    

You could have low node-level QoS but pretty good cluster-level QoS, which means we may periodically boot you off a node, but we expect to be able to find you another home soon.

Quota (the current implementation or a rate-based one) can be used to implement cluster-level QoS (which we haven't said yet what we will call) and/or it can just be used to prevent excessive use of free resources by particular tenants.

**Comment by derekwaynecarr** [comment]
@erictune - this has become a near-term high priority request.  The axis we were looking to support sub-dividing quota on was associated with short vs. long-lived resource consumption, so largely around pod restart policy.  

The `Selector` proposal is actually really nice, but I may want to add that same facility to `LimitRange` as well.  I need to validate that that would meet our needs, but it seems promising without introducing a lot of complexity.

**Comment by derekwaynecarr** [comment]
To handle compute resources, I think I would need to also support a `FieldSelector` that was targeted to just `Pod` as well.  So for example, I could have a `LimitRange` with different constraints for pods whose `RestartPolicy=Always` versus pods whose `RestartPolicy=Never` to allow burstable job style pods that get a different resource footprint than what I want to offer to longer running pods in the cluster.
