### ISSUE TITLE
Concurrent runs of L7 E2Es can't share a project

### ISSUE THREAD

**Issue by jlowdermilk** [kubernetes/kubernetes#17119]
Test is now permanently failing (see [gce-disruptive-1.1](http://kubekins.dls.corp.google.com/view/CI%201.1/job/kubernetes-e2e-gce-disruptive-1.1/178/testReport/history/)). It's failing in the cleanup step waiting for the backends to be removed.

It looks like it the backends are eventually removed, since the project isn't filling up with old ones. Not sure if the timeout is too short or something else changed.

**Comment by bprashanth** [comment]
It's failing to start because it asserts the initial condition that no l7s exist. I would expect this to happen if 2 instances of the same test ran in parallel somehow, since the last run that passed checked that no l7s exist, and then it started failing. Will follow up.

**Comment by jlowdermilk** [comment]
It can't make the initial assumption that no l7s exist, otherwise you can't run more than one instance of the test per project (which is what we are currently doing on kubernetes-jenkins). It's unfortunate that backends aren't created with an identifying name, otherwise we could assert that the ones the test created get cleaned up.

**Comment by bprashanth** [comment]
Yes, the test should be resilient to parallel execution. Backends are ref counted because they're so limited in quota, so a backend existing is completely fine. Ref counting gets messy if you try to segment backends per test. WDYT about disabling the test on soak (which I think is the only other suites that does this) till I've done what I need to?

**Comment by jlowdermilk** [comment]
fwiw, I'm not sure that multiple jobs running this test on the same project is the root cause. It's also failing on [gke-1.1-features](http://kubekins.dls.corp.google.com/view/GKE/job/kubernetes-e2e-gke-1.1-features/), which runs in a dedicated project.

**Comment by bprashanth** [comment]
Aha, ok multiple issues all probably my problem in some way.

* Why was gke-1.1-features complaining?

Test uses `gcloud compute` to list backends, on jenkins master
```
$ gcloud compute backend-services list --verbosity debug
... request: (<googlecloudsdk.third_party.apis.compute.v1.compute_v1_client.BackendServicesService object at 0x3d8fbd0>, 'List', <ComputeBackendServicesListRequest
 maxResults: 500
 project: 'kubernetes-jenkins'>)
DEBUG: Making batch request...
```
So even though there were no backend services in gke-1.1-features the test thought there were.

* Where did these backend services come from? 

Gce-soak

* Why did they keep coming back?

This is a hard one. Everytime the l7-controller deleted them they'd pop back up. This is because the soak test runs a descructive kernel panic reboot test. One of the nodes got partitioned in a very tricky way. The containers on the node could see the Ingresses in the apiserver, but I couldn't ssh into the node and the kubelet reported it as unhealthy. As a result the orphan container kept recreating the backend, even when the pod on the Ready node would delete them. 

* what to do?

1. Test shouldn't use gcloud compute (or use it and specify project)
2. Test should be resilient to parallel runs in the same project (this might need a little thinking, because there are 2 masters but a single global pool of resources). Might be easier to focus on checking forwarding rules or some such in the short term. 
3. Reboot test should hard stop soak suite on NotReady node?
4. Don't share projects for parallel runs of the same test (I know this is a stretch)?

**Comment by bprashanth** [comment]
Fyi will probably not get a chance to work on this till EoW (maybe friday) because I'm on call, but tests look mostly green now.

**Comment by jlowdermilk** [comment]
@bprashanth have you had a chance to look at this? Test is still pretty bugged; would be good to fix before next patch cut to reduce noise.

**Comment by bprashanth** [comment]
https://github.com/kubernetes/kubernetes/pull/16979 just went in which has the right gcloud command (1. in the list above). Any failures now should only be because of https://github.com/kubernetes/kubernetes/issues/16985, which should be fixed in https://github.com/kubernetes/contrib/pull/219. As for making it tolerant to parallel runs of itself, I'm planning to do the following:
1. Tag all resources create by a controller with some uid
2. Don't deploy the controller by default in e2e clusters, instead create/delete the rc in the test
That way I can check just the resources tagged with the current uid. 

But this uid tagging change won't be in 0.5, which is the version of the image used in 1.1. So @jlowdermilk can we move just the 1.1 test to a kubernetes-1.1 cluster? or I can think of a way to backport the tagging to 0.5 in a non-disruptive way.

**Comment by jlowdermilk** [comment]
Sounds like the main test fix is in then. The main annoyance is that we have jobs that are running versioned tests at latest stable, which doesn't have the fix. As long as we cherrypick #16979 onto 1.1, that pain is temporary.

**Comment by bprashanth** [comment]
Fixed now
