### ISSUE TITLE
Support autoscale deployments

### ISSUE THREAD

**Issue by janetkuo** [kubernetes/kubernetes#17143]
Follow up #15739 
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/util/factory.go#L298

**Comment by kargakis** [comment]
We should also support manually scaling a deployment. `kubectl scale` would update the deployment with the desired replica count and the controller would actually do the scaling when reconciling the deployment. The reconciling should happen on the spot though, instead of the 30s time window that exists right now. 

@bgrant0607 @ironcladlou @nikhiljindal

**Comment by nikhiljindal** [comment]
+1

Regarding the 30s time window: @ironcladlou is going to send a PR to move DeploymentController to the informers pattern which will fix this (We will start watching resources instead of polling them)

**Comment by kargakis** [comment]
Yep, already familiar with his branch:)

Opened https://github.com/kubernetes/kubernetes/issues/17170 for manually scaling.
