### ISSUE TITLE
Log management roadmap

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#17183]
We need to decide where we're going with log management. 

We have kubectl logs and the fluentd and ELK setups. We're not currently using Docker logging plugins.

More specific open issues:
- rotation configuration, both for Docker logs and file-based logs, as in #13010
- kubectl logs #11046 vs. Fluentd and other agents to push off node
- how to capture kubernetes metadata: #8001

Forked from #16889

@vishh @dchen1107 @saad-ali @ncdc

**Comment by ncdc** [comment]
cc @jcantrill @mwringe @sosiouxme

**Comment by vishh** [comment]
Related issue: #13846

@bgrant0607: #8001 is almost resolved. The fluentd plugin does tag log lines with kubernetes metadata. Relevant [comment](https://github.com/kubernetes/kubernetes/issues/8001#issuecomment-139407239)

Following are some of the issues with logs today:

1. Logs are stored on disk. By default, the json logging driver is used with docker. They are not rotated by the kubelet directly. We rely on an external log-rotation.
2. Log lifetime is tied to container's lifetime. Kubelet ends up retaining old container instances, including its writable layer, which causes local storage pressure.
3. Alternate logging models are difficult to introduce because Kubernetes APIs demand access to logs from the nodes. For example, we cannot switch to using the fluentd logging driver, because the log files will not be stored locally.
4. The existing logging model does not handle log data that is not stored to stdout or stderr of a container. I'd argue that this is not of primary concern because docker supports stdout/stderr only and the image authors might be able to configure their images to log to stdout/stderr.
5. System daemon logs require fluentd + ELK stack to be run for it to be persisted forever. By default, they are rotated on the nodes.

Some thoughts on addressing these issues:

1. Add a logging plugin module in kubelet, which can handle logs request based on the the logging driver. By default, it will use `docker logs`. If docker is configured to use `journald` or `syslog` it will handle log requests appropriately. 

2. As discussed in #13846, we can use the fluentd plugin in docker. By default, this approach will result in logs being shipped off of the node without touching the local disk. This simplifies disk management on the nodes, but it makes cluster deployment harder since it requires a cluster level logging service like ELK to be setup prior to running containers. Since we provide the ELK stack as a simple add-on, this might not be big issue today. 
To begin with, we can [configure fluentd](http://docs.fluentd.org/articles/out_copy) to output log files to local disk in addition to remote storage like ELK. The logging module mentioned above, can then serve logs from these files. 
In the future, we can provide a logging add-on service that can translate log requests from the apiserver into appropriate ELK or other logging service queries. This approach will provide guaranteed access to current and historical logs. 

3. Once we stop using `json` logging driver in docker, kubelet can immediately delete old container instances, if the kubelet can tolerate that.

**Comment by sosiouxme** [comment]
On Fri, Nov 13, 2015 at 1:42 PM, Vish Kannan <notifications@github.com>
wrote:

> Related issue: #13846
> <https://github.com/kubernetes/kubernetes/issues/13846>
>
> @bgrant0607 <https://github.com/bgrant0607>: #8001
> <https://github.com/kubernetes/kubernetes/issues/8001> is almost
> resolved. The fluentd plugin does tag log lines with kubernetes metadata.
> Relevant comment
> <https://github.com/kubernetes/kubernetes/issues/8001#issuecomment-139407239>
>
> Following are some of the issues with logs today:
>
>    1. Logs are stored on disk. By default, the json logging driver is
>    used with docker. They are not rotated by the kubelet directly. We rely on
>    an external log-rotation.
>
> Note: With docker  1.8 you can configure docker to rotate these.

>
>    1. Log lifetime is tied to container's lifetime. Kubelet ends up
>    retaining old container instances, including its writable layer, which
>    causes local storage pressure.
>    2. Alternate logging models are difficult to introduce because
>    Kubernetes APIs demand access to logs from the nodes. For example, we
>    cannot switch to using the fluentd logging driver, because the log files
>    will not be stored locally.
>    3. The existing logging model does not handle log data that is not
>    stored to stdout or stderr of a container. I'd argue that this is not of
>    primary concern because docker supports stdout/stderr only and the image
>    authors might be able to configure their images to log to stdout/stderr.
>    4. System daemon logs require fluentd + ELK stack to be run for it to
>    be persisted forever. By default, they are rotated on the nodes.
>
> Definitely some important issues.

>
>
> Some thoughts on addressing these issues:
>
>    1.
>
>    Add a logging plugin module in kubelet, which can handle logs request
>    based on the the logging driver. By default, it will use docker logs.
>    If docker is configured to use journald or syslog it will handle log
>    requests appropriately.
>
>
Recently the journald logging driver was updated so that docker logs can
pull from it according to container metadata. The same doesn't exist for
syslog and probably won't as it's not really suitable for log metadata.


>
>    1.
>
>    2.
>
>    As discussed in #13846
>    <https://github.com/kubernetes/kubernetes/issues/13846>, we can use
>    the fluentd plugin in docker. By default, this approach will result in logs
>    being shipped off of the node without touching the local disk. This
>    simplifies disk management on the nodes, but it makes cluster deployment
>    harder since it requires a cluster level logging service like ELK to be
>    setup prior to running containers. Since we provide the ELK stack as a
>    simple add-on, this might not be big issue today.
>    To begin with, we can configure fluentd
>    <http://docs.fluentd.org/articles/out_copy> to output log files to
>    local disk in addition to remote storage like ELK. The logging module
>    mentioned above, can then serve logs from these files.
>    In the future, we can provide a logging add-on service that can
>    translate log requests from the apiserver into appropriate ELK or other
>    logging service queries. This approach will provide guaranteed access to
>    current and historical logs.
>
> Can we configure fluentd to split logfiles to journald as well as
ELK/other aggregator? Given the right metadata, journald entries would
allow docker logs to continue working (assuming it can handle the container
not actually being present). Minimal disruption.

Side note: One difficulty with ELK is that it doesn't have a concept of
multitenancy. That's fine if you trust all your users... but setting up
isolation when you don't want users seeing all the logs has proven to be
complicated for OpenShift. I don't feel great about relying on it as the
sole repository of logs - having the current mechanism as backup is
preferable.

**Comment by vishh** [comment]
> Recently the journald logging driver was updated so that docker logs can
pull from it according to container metadata. The same doesn't exist for
syslog and probably won't as it's not really suitable for log metadata.

Thanks for the info. This should make switching over to journald much simpler in the short term. 
Is it possible to configure per log stream disk usage constraints using journald? Explicit control over logging will help provide better disk usage isolation. I'd much rather use journald or other logging utilities that re-implement logging functionality in kubelet. 

> ELK/other aggregator? Given the right metadata, journald entries would
allow docker logs to continue working (assuming it can handle the container
not actually being present). Minimal disruption.

:+1: This property will then let us not depend on docker daemon for accessing container logs.

> Side note: One difficulty with ELK is that it doesn't have a concept of
multitenancy. That's fine if you trust all your users... but setting up
isolation when you don't want users seeing all the logs has proven to be
complicated for OpenShift. I don't feel great about relying on it as the
sole repository of logs - having the current mechanism as backup is
preferable.

If the design is generic enough, it should be relatively easy to use other logging stacks.

**Comment by jchauncey** [comment]
Isn't that the point of using something like fluentd as your collection point. It allows for people to plug and play any logging stack they want (splunk, elk, files, etc...)

**Comment by alfred-huangjian** [comment]
cc @liuhewei @huangyuqi

**Comment by vishh** [comment]
cc @a-robinson

**Comment by therc** [comment]
I opened a few logging-related issues, mostly related to fluentd: #23001 (partitioning log indices by namespace), #22222 (log the cluster name), #22366 (report errors forwarding logs), #21285 (AWS support). More in general, it would be nice to add knobs so that admins can tweak logging, without requiring them to build a whole new image. I might open another issue just for that.

**Comment by vishh** [comment]
cc @kzk @edsiper

**Comment by vishh** [comment]
Wants from the logging system:

* Ability to collect application specific logs. This includes collecting logs from custom directories.
* Retain recent history of logs on local disk, to workaround issues in logging agent and network outages.
* Isolation per pod - No single container / pod should take up all the disk and network bandwidth.
* Preserve log lines from containers without clobbering them with metadata.
* Support tagging logs with pod & container specific metadata - labels, pod name/UID, container name, namespace, cluster name, etc.

**Comment by a-robinson** [comment]
cc @piosz @fgrzadkowski

**Comment by devx** [comment]
After reading the entire thread and all the related links I would like to share my experience and how we have dealt with logging. We are still currently working on it!

We initially deployed a container that would use the k8’s API’s to get the logs, and metadata for all the containers in a replication controller. This worked however it has various drawbacks. As it increased the load of the API servers, not to mention that this would take away CPU resources from the applications that were supposed to run. In short it does not scale.

Our latest experiment is to log at a lower level, and that is at the Docker daemon.  This strategy for us has been working and is very efficient.  Currently we use the Docker log driver with the fluentd plugin that sends to a small Golang binary running on every kubelet; which transforms the message and sends it to Kafka with TLS for transport. (Granted Kafka can be replaced with AWS Kinesis, or Googles Cloud Pub/Sub or Google Log service, but we currently are just testing Kafka.) This gives us more flexibility over our data as we don’t have static data pipelines, and can test various ways to manipulate our data, etc.  

To be honest what I would like is for k8’s to inject the metadata to Docker’s labels, so this information could be passed in the Docker log’s information.

**Comment by vishh** [comment]
If you trap docker logs, `kubectl logs` will not work. And the logging
solution needs to work for other runtimes too.
Those are some of the reasons why this proposal is a bit more complex.
Makes sense?

**Comment by devx** [comment]
You are correct if you "trap" the logs you won't be able to see them via the `kubectl logs`. But that is ok for me as I rather have a different system to view/manipulate logs as I probably will be doing various thing with else with them.  (Not to mention that if you have regulatory compliance you will have to do other things with those logs.)

At the end of day it's another option, it might not be the right one for everyone but it is another option.

**Comment by bryk** [comment]
Is there a roadmap item to make `kubectl logs` return O(days) instead of O(minutes) of logs?

**Comment by piosz** [comment]
Let's sync f2f

**Comment by coffeepac** [comment]
is there any desire to have a f2f meeting around Kubecon (suggested as people may be travelling already)?  or possibly start off with a working group or a sig to get some community focus on this as well?  focus has seemed to be a bit start and stop over the past year+

**Comment by edsiper** [comment]
FYI: For log-collection/distribution stuff, Fluentd team will be at KubeCon in case you want to touch some specific topic.

**Comment by vishh** [comment]
A f2f meeting during kubecon sounds like a good idea.

**Comment by coffeepac** [comment]
I work for Samsung in Seattle conveniently located in the same town and maybe a 20 minute walk from Kubecon.  We have space for maybe 15 people.  Its a brand new office so its a bit rough but its nice and free.  We can also supply snacks.

@vishh you've been leading a lot of this discussion, what's a good venue for collecting interested parties and having a discussion?  I don't think continuing to hijack this PR is a good idea.

**Comment by vishh** [comment]
I'd suggest posting this as a topic in the [k8s developer summit](https://github.com/kubernetes/community/blob/master/community/Kubernetes_Dev_Summit.md) to begin with. I can do this today. 
If it doesn't get accepted for any reason, or if all the interested people don't make it through the dev summit lottery, we can then reach out to the community via `kubernetes-dev@googlegroups.com` to setup an alternate meeting. 
@piosz does that work for you?

**Comment by coffeepac** [comment]
@vishh I submitted a topic titled 'Logging in Kubernetes'.  If we need to have a non-dev summit meetup before/after, preferably after if doing both I think, I can host it in Samsung's Seattle office.

**Comment by piosz** [comment]
I didn't plan to attend Kubecon/k8s developer summit, though I'm very interested in the meeting. I need to figure out whether I will be able to attend.

I'm also going to write (similarly to the docs about monitoring): Logging current state and Logging architecture/roadmap proposal.

I think sig-instrumentation might be a good spot for discussions about logging. Depending on how many people would be interested and how much topic to discuss we have we may want to spawn a new sig-logging.

cc @fgrzadkowski
