### ISSUE TITLE
Out of resource killing

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#17186]
Forked from https://github.com/kubernetes/kubernetes/issues/14452#issuecomment-142758038, #15673, #16889, #13006, #14943, and other issues/PRs.

We need a model for out of resource killing on overcommitted nodes.

cc @dchen1107 @vishh @davidopp @derekwaynecarr

**Comment by derekwaynecarr** [comment]
@bgrant0607 - Just a heads-up this is a near term priority for me in next few days.  I am interested in your requirements.  I will try and write up more details on some of my own goals in more detail soon.

But a rough set of requirements:

1. The kubelet has the ability to monitor compute resource usage (memory / disk in near term)
2. An operator can set thresholds for % of memory and disk usage that would induce the out of resource killer.  It's possible this would be a field in the Node spec, or just a flag to start-up of the kubelet.
3. When thresholds are reached, we need to target based on QoS.  For disk, you would want to target those that are actually using it.  It's possible we may also want to invoke a local docker image garbage collection in low disk scenarios be
4. Kill a pod and spawn an event with the reason.

Basic acceptance criteria should be that its not possible to OOM kill a node inside of its monitoring interval (unless a system daemon is what induced it and no amount of user container killing could fix it).

**Comment by vishh** [comment]
@derekwaynecarr: The rough outline aligns with my thoughts as well. Step `3` is the core policy and this can get pretty complex. We can start with assuming that the default behavior will satisfy most users. 
I'm happy to collaborate since this is a priority for me as well :)

**Comment by derekwaynecarr** [comment]
@vishh - sounds good, maybe we can get a hangout this week to talk through topics and divide/conquer?

**Comment by derekwaynecarr** [comment]
fyi @ncdc for the upstream issue tracking out of resource killer

**Comment by vishh** [comment]
SGTM. Will sync up with you over IRC.

**Comment by dchen1107** [comment]
@derekwaynecarr What you listed at https://github.com/kubernetes/kubernetes/issues/17186#issuecomment-157185065 is aligned with our thoughts. For 2) the thresholds for % resource should align with https://github.com/kubernetes/kubernetes/issues/13984

**Comment by derekwaynecarr** [comment]
@dchen1107 - agree on #13984, that is also a near term priority for me.  I want to get rid of the resource-reserver pod and static resource reservation in general for incompressible resources in kubernetes 1.2, so having the kubelet dynamically report back its available compute resource goes hand-in-hand.  So we just need to synch up on how we can all best contribute to the effort.

**Comment by dchen1107** [comment]
@derekwaynecarr FYI: @timstclair has a proposal at https://github.com/kubernetes/kubernetes/pull/17201 based on our internal design discussion.

**Comment by bgrant0607** [comment]
The threshold probably has to be expressed similarly to alert triggers in other systems, such as including a duration as well as a threshold, in order to accommodate bursting.

We'll also want OOR killing for CPU, but since CPU is compressible, we'll need to take into account other factors (e.g., QoS) and signals (e.g., cpu load). That's sort of true even for memory, which is marginally compressible due to paging.

We'll also eventually want a principled way to provide back pressure to the scheduler. A crude approach would be for the scheduler to back off scheduling of at least BestEffort pods on nodes with recent/frequent OOR events. Eventually we'll want to take smoothed usage into account, though we need the metrics APIs to be finished first.

**Comment by derekwaynecarr** [comment]
@bgrant0607 - agreed.

At the node side, 
* operator can specify monitoring interval (N) for polling resource usage in user-space
* operator can specify a soft (S), hard (H) threshold and duration (D) for each compute resource C
* kubelet control loop at interval N monitors system-wide compute resource usage via cAdvisor
 * rank usage of C grouped by QoS tier (T) at pod scope
 * if usage of C exceeds S, but is less than H for period D, record Event, update NodeCondition
 * if usage of C exceeds H for period D, record Event, update NodeCondition, initiate eviction to reclaim C

It may be easier to model duration (D) as basically the number of consecutive monitoring intervals rather than an exact period of time.  For example, if N = 10s, then D=2 means if C exceeded its usage for 20s, then do something.

I think soft/hard thresholds would be appreciated by our operators.

We need to evict entire pods by QoS tier (T), and there would be a few different options here for how we find a candidate pod (P) to evict.  I think each compute resource C would have its own distinct priority function F for how it identifies pods to target.

* F=findCandidatePodMemory
 * T=BestEffort, find pod with largest consumer of C
 * T=Burstable, find pod with max(usage(c) - request(c)
 * T=Guaranteed, select most recently scheduled
 * in-case of tie, always choose most recently scheduled
* fail P
* check if C is blow T, else repeat

On the scheduler side we could then use the information to get smarter to do back-off.

My near-term interest is around the node, and low memory situations, which I think has a simpler priority function.

Will send a proposal we can evolve.

Thanks!

**Comment by derekwaynecarr** [comment]
Copying from #18438 to ensure its covered in the out of resource killing specification:

* Backpressure from the node if it is noticing system OOMs. We will need this for pods evictions on the node as well.
* Stronger feasibility checks on the node - reject best effort pods if the current availability is below certain threshold.
* Cap the total resources that best effort pods can consume on the node - This combined with NodeAllocable should improve node stability.

**Comment by derekwaynecarr** [comment]
I put a first-draft of a proposal for review here:
https://github.com/kubernetes/kubernetes/pull/18724

**Comment by davidopp** [comment]
It looks like we didn't link this issue to the out-of-resource eviction work, which now covers memory and disk: http://kubernetes.io/docs/admin/out-of-resource/

Anyway, we should add out-of-CPU killer, as discussed upthread.

**Comment by domleb** [comment]
> Anyway, we should add out-of-CPU killer, as discussed upthread.

We are looking at doing this ourselves as we regularly have high load average issues from bursting containers.  So it would be great if this was added to kublet.  Is there any plan to pick this up again?
