### ISSUE TITLE
Mirror pod status won't be updated after recreation

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#17253]
If a mirror pod gets deleted for some reason, the status won't ever be updated since the pod status appears the same.

We used to solve this issue by deleting the pod status. This is undesirable because many internal kubelet components relying on the pod status for various operations. I think we can add a function to forcibly increment the version of the status when creating a new mirror pod.

/cc @timstclair

**Comment by timstclair** [comment]
I think the issue is that when the mirror pod is recreated, it won't get the current pod status set. Once the status changes, that should still increment the version and push the update to the new mirror pod.

I think the best way to fix this is to update the status managers version tracking map (`manager.apiStatusVersions`) to tie the versions to the mirror pod UID (since that is the piece that needs the update) rather than to the static pod UID. This will add a small amount of complexity to `manager.syncBatch` since it now needs to map the pod UID in each loop.
