### ISSUE TITLE
Using TensorFlow with Kubernetes to optimize container/pods/nodes requirements/usage

### ISSUE THREAD

**Issue by dlsniper** [kubernetes/kubernetes#17296]
Hi,

After hearing the talks about "Kubernetes and Containers: Changing the way we build applications" by @tekgrrl and "Your Data and the World Beyond MapReduce" from @kazunori279 one question that I've had but couldn't really follow up with is: 

Could Kubernetes use TensorFlow to determine if either containers or pods resources can be optimized for different periods of times (during a day or for a series of days) for example?

The reason for this is that while autoscaling is useful inside a k8s cluster is a nice useful feature, being able to pre-warm the cluster to a certain size or even pre-warm the whole underlying "physical" cluster would further improve the benefits of autoscaling.

I could also imagine things such as networking requirements, or other metrics, possibly fed into this to create a smart, automatic, way to schedule the nodes not only horizontally but vertically as well. Say k8s observes that it's better to launch a couple more additional higher type "physical" instances to support the cluster needs rather that launching same instance types because they are not available (or they have better resources available and the response times are better even when the workload is larger on them).

This could also be used when performing load tests and allow for the cluster to learn from them with regards to the needs of new pods / containers before launching them in production thus removing the guesswork from allocating specific values for resources.

I'm not sure how clear the question is but I'm happy to dive more into this and try to make it more explicit if needed.

**Comment by dlsniper** [comment]
I could also see benefits to having a smart "learning" mechanism in place that could also understand from previous executions of similar containers / pods / etc. better scheduling being done in order to improve the resource usage across nodes / lower the number of nodes needed.  Or even to take price vs execution time vs other factors into account when scheduling tasks.

All of of these of course make (even more) sense when the concept of versioning for a certain task is in place (regardless task type) I think, no?

**Comment by davidopp** [comment]
Hi @dlsniper . While I'm not sure about the specific applicability of TensorFlow (I don't know much about it), using feedback control systems and machine learning for scheduling (both in time and space), for scaling, and for modeling the impact of load and system configuration on user-visible QoS  metrics, are definitely areas of active research -- not just in computer systems, but all kinds of domains.

Concretely, if you're interested in implementing any of the things you described, you are certainly welcome to give it a shot. 

Here are some references you might be interested in, to understand some of the previous work in this space:

http://www.amazon.com/Feedback-Control-Computing-Systems-Hellerstein/dp/047126637X (the whole book seems to be online; Chapter 15 talks about autoscaling)

http://www.amazon.com/Feedback-Control-Computing-Systems-Hellerstein/dp/047126637X

http://www.cse.ohio-state.edu/~cstewart/Papers/stewartnsdi05.ppt

http://cpslab.cs.mcgill.ca/feedbackcomputing15/
https://www.usenix.org/conference/feedbackcomputing14
https://www.usenix.org/conference/feedbackcomputing13
http://controlofsystems.org/FeedbackComputing2012/
(and so on and so forth)

If you're interested in implementing and evaluating any of the ideas you mentioned in Kubernetes, here are my thoughts:
* You could write your own scheduler to try out your ideas.
* You could write a rescheduler that computes an optimal (or close-to-optimal) bin-packing of the existing pods, and then formulates a sequence of pod moves from one node to another that get you from the current state to the optimal state, and then executes the moves. More details on rescheduler here
https://github.com/kubernetes/kubernetes/blob/master/docs/proposals/rescheduler.md
(note that we're going to start with a much simpler rescheduler -- but that doesn't mean you shouldn't try out more sohisticated approaches)
* You could write a cluster auto-scaler that uses the kinds of sophisticated algorithms you described.

All three of these can operate using the existing Kubernetes API both for observing cluster state and actuating changes (binding pods to nodes, evicting pods, etc.). The only exception is that actuating cluster auto-scaling requires calling out to the cloud provider and thus is cloud-provider specific (e.g. scaling the cluster up/down on GCE works differently than on AWS).

Note that in order to evaluate the effectiveness of any approach you develop, you're going to need a realistic workload and a workload generator. We haven't really done anything significant on that front; issue #3139 is the relevant issue, though it mostly just talks about generating a random workload, not one that is necessarily realistic. Google has released traces of cluster workloads, which many people have used to write papers, and are a reasonable starting point for understanding what a "realistic" workload looks like:
https://github.com/google/cluster-data
(the most well-known paper based on that data is
http://www.pdl.cmu.edu/PDL-FTP/CloudComputing/googletrace-socc2012.pdf )

Unfortunately the core Kubernetes team is too busy right now to explore applying machine learning to scheduling, but you and/or anyone else in the community is certainly welcome to try it out. Hopefully the information I've provided above is sufficient for you to get started if you're interested in pursuing it. 

Github is probably not the right place to discuss theoretical aspects of scheduling; if you wish to continue the discussion you started here, I'd suggest using the Kubernetes scheduling SIG mailing list:
https://groups.google.com/forum/#!forum/kubernetes-sig-scheduling
Therefore I'm going to close this issue. Please feel free to open a Github issue if/when you have a concrete proposal that you intend to implement, and wish to get feedback from the community.

Thanks for your interest in Kubernetes!
