### ISSUE TITLE
Kubernetes volume using OpenStack cinder doesn't work.

### ISSUE THREAD

**Issue by wangqunOne** [kubernetes/kubernetes#17360]
Hi, I use the official url http://kubernetes.io/v1.1/examples/mysql-cinder-pd/README.html to create a cinder volume.

Run the command "cluster/kubectl.sh create -f examples/mysql-cinder-pd/mysql.yaml"
The result of command is error validating "/home/minion/kubernetes/examples/mysql-cinder-pd/mysql-service.yaml": error validating data: field nodePort: is required; if you choose to ignore these errors, turn validation off with --validate=false.

2.Then run "cluster/kubectl.sh --validate=false create -f examples/mysql-cinder-pd/mysql.yaml"
The result of command is that the cinder volume doesn't be mounted.

Run "cinder list" volumeID:0a9c53b7-97f2-4369-8d62-43a2885c6be8 status: available.
4.Run "docker docker inspect 9159778bf436"
"Mounts": [
{
"Source": "/var/lib/kubelet/pods/6f73be8b-8cfa-11e5-9380-fa163ec0b6bd/volumes/kubernetes.io~empty-dir/mysql-persistent-storage",
"Destination": "/var/lib/mysql",
"Mode": "",
"RW": true
},
{
"Source": "/var/lib/kubelet/pods/6f73be8b-8cfa-11e5-9380-fa163ec0b6bd/containers/mysql/9159778bf436d255493716da0ab754b547b64e012780edbea9ae21628a6e7f61",
"Destination": "/dev/termination-log",
"Mode": "",
"RW": true
}
],

**Comment by gmarek** [comment]
cc @bgrant0607

**Comment by thockin** [comment]
@spothanis

**Comment by spothanis** [comment]
It is weird that you are getting a warning about a service when you are creating a pod.

When the kubelet boots up, do you see a log line about cinder volume plugin (you might have to increase the log verbosity to 4, I don't quite remember)?

Also when Kubelet starts up, do you see messages indicating that connection to nova was ok and that it was able to find the node from the cloud provider?
Another thing to check would be to list all the events on the pod with describe and see if there were any errors.

Using older version of kubectl might cause issues as well. Here is a reference https://github.com/kubernetes/kubernetes/issues/15966#issuecomment-149938049

**Comment by wangqunOne** [comment]
@spothanis， I check the kubernetes version. I  uses the kubernetes version 1.0.4. Does it cause the failure?

I want to ask you  which case is supported below ?  We want to make the kubernetes work with openstack cloud provider. 

First case: I have two VM instances to install kubernetes. Both of instances  were created by openstack. Then to install kubernete on the two instances. Finally, to config kubelet to start with cloud-provider=openstack
.
Second case: I use two separate instances,  which were not created by openstack. And I install the kubernetes on the two instances. My openstack was installed in other nodes.. ( I suspect kubernetes  not support this to work with openstack cloud provider)

Notes: The difference between above two cases, is that kubernetes nodes was created by Openstack or not, I think it is total different, not sure if k8s support all or just one case. Could you specify it ?
Thank you very much.

**Comment by swagiaal** [comment]
cc @jsafrane

**Comment by jsafrane** [comment]
@wangqunOne, Kubernetes 1.0.4 does not have Cinder volume plugin, AFAIK it has been added in 1.1.0.

In addition, you need to tell Kubernetes some OpenStack credentials to be able to attach volumes:
`kubelet --cloud-provider=openstack --cloud-config=/etc/cloud.conf`. You can see skeleton of `cloud.conf` here: https://github.com/kubernetes/kubernetes/blob/master/cluster/rackspace/cloud-config/master-cloud-config.yaml#L7 (starting with `[Global]`)

If it still does not work, please run kubelet with `--v=5` and post the logs somewhere.

**Comment by spothanis** [comment]
@wangqunOne apart from what @jsafrane mentioned, it will work only with case 1. In case 2, Openstack is not aware of your instances and wont be able to attach or detach volumes to it.

**Comment by bgrant0607** [comment]
The nodePort validation bug is fixed in 1.1 by PR #12831

**Comment by bgrant0607** [comment]
For further discussion, please post your questions to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes). 

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases. 

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to similar questions, and also familiarize yourself with:
  * [the user guide](http://kubernetes.io/v1.0/)
  * [the troubleshooting guide](http://kubernetes.io/v1.0/docs/troubleshooting.html)

Again, thanks for using Kubernetes.

The Kubernetes Team
