### ISSUE TITLE
Kubelet generates event spam

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#17475]
Why do we need events for failed sync, container creations and starts, etc.? It's too much detail. Creation of excessive numbers of events exacerbates performance and event filtering problems that we are not prepared to deal with. Status should cover ordinary status updates sufficiently.

Events should reflect normally infrequent occurrences relevant to and actionable by users or admins.

Internal implementation details should be logged and/or exported to prometheus metrics and should not spawn events.

We should document best practices here:
https://github.com/kubernetes/kubernetes/blob/master/docs/devel/api-conventions.md#events

cc @dchen1107 @vishh @erictune @saad-ali @derekwaynecarr @davidopp

**Comment by yujuhong** [comment]
Related issue: #14702 (audit kubelet events; using separate client for events to mitigate performance issues). 

From my experience, kubelet emits more and more events because users have always asked for more events for introspection.

Even though I agree that kubelet does generate excessive events, I find some events useful when debugging. `api.PodStatus` gives you more of a snapshot, while having a series of timestamped events allows you to compare them against a "normal" pod. Note that one may get all the relevant from the logs as well, but a normal user probably wouldn't want to look at kubelet.log to debug one pod. Besides that, we probably should fix api.PodStatus to include more meaningful data for debugging (e.g., failed post-start command couldn't be diagnosed without events).

By the way, does this mean we should stop recording events such ash "Scheduled" as well?

**Comment by erictune** [comment]
If you are looking at all the events at once, then it is too much detail.  I don't do that.

Events are used in `kubectl describe` to build a timeline for the user of their object.
I've found having the following timeline available to be quite useful for debugging:
- pod scheduled
- pod created by kubelet
- container image pulling
- container running
- container exited 

I don't think we should lose that.

Similarly, for an RC, having a timeline of when it created or deleted pods is useful too.

The level of detail depends on the object the user is interested in.

**Comment by erictune** [comment]
Also, event are GCed after a while, so they don't accumulate, and event compression (combining similar events) appears to be working well.

I don't think this is a problem.

**Comment by erictune** [comment]
Maybe the failed sync event should be removed. I don't understand that one. Or maybe it is a real bug we should fix.

**Comment by bgrant0607** [comment]
Related: #15999

**Comment by derekwaynecarr** [comment]
I agree with @erictune on the value of using an event to debug the life of an object in the system via kubectl describe <object>.  

Prior to adding event correlation, I had major issues with event spam when things go bad in our controllers, so we may want to scope the issue a bit broader than the Kubelet.

Are there specific cry-wolf scenarios right now we are vulnerable against in the Kubelet?

**Comment by dchen1107** [comment]
We introduced those events for introspection and debugging at the first place. Even PodStatus today contains a lot of information, but those timestamps associated with event itself add a lot of values to user when something is wrong with their application. At kubelet side, the developer(s) initially added both "-ing" and "-ed" pair event for each container operation. But now we did remove all "-ing" related events and only leave "-ed" ones except image pull one because pulling image might take a long time and has a lot of potential issues. 

On another hand, we do create event spam when a container is in crashloop because both started and created event of container have docker container id associated, which makes compression not work well on those events. Backoff of crashing container and pulling failure mitigates the issue a little bit, but not really fix this spamming issue. We could either omit docker container id from those events, or improve our compression logic on combining events. 

FailedSync should be removed, at least it shouldn't associate with a pod. From a user standpoint, this is useless information.

**Comment by saad-ali** [comment]
> On another hand, we do create event spam when a container is in crashloop because both started and created event of container have docker container id associated, which makes compression not work well on those events. Backoff of crashing container and pulling failure mitigates the issue a little bit, but not really fix this spamming issue. We could either omit docker container id from those events, or improve our compression logic on combining events.

This should be fixed by https://github.com/kubernetes/kubernetes/pull/16798 which collapses similar event seen in rapid succession.

CC @derekwaynecarr

**Comment by dchen1107** [comment]
Ahh I missed #16798. Yes, that will cover the spam generated from kubelet and replicationController on those rapid succession failures. @bgrant0607 any more concerns? 

This file defines all events fired by Kubelet: https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/container/event.go

**Comment by bgrant0607** [comment]
I'll hope that #15999 mitigates my annoyance with events I don't care about.
Thanks.

**Comment by derekwaynecarr** [comment]
@dchen1107 - if the event in container crash loop scenario only varies by message, we should be fine with #16798 and they will be collapsed.
