### ISSUE TITLE
Hung docker daemon yet kubelet remains in 'Ready' status

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/kubernetes#17525]
While running density tests against a kubernetes cluster, we will occasionally run into nodes where the docker daemon becomes unresponsive.  Symptoms include:
- `docker ps` hangs
- `kernel: unregister_netdevice: waiting for veth0123456 to become free. Usage count = 1` appears in journal output

Probably an upstream issue.  But I would expect kubelet to notice that its docker deamon is unhealthy and send a 'NotReady' status back up to the controller manager.  Instead, it stays at 'Ready' and the scheduler assigns pods to it, which will stay stuck in Pending.

This is not quite the same as #16601 but our mitigation is the same, we're forced to reboot the node.

**Comment by yujuhong** [comment]
`docker ps` is relatively expensive, so kubelet relies on `docker version` for health check (and reporting node status). Now that we have a single goroutine (generic pleg #13571) calling `docker ps` periodically, maybe we can check the relist timestamp as an indication of the docker healthiness?

@kubernetes/goog-node

**Comment by dchen1107** [comment]
@spiffxp Ok, Kubelet do detect docker daemon down issue and handled other API failure issues, but failed to detect docker hang issue.

 In normal case, since we have babysitter (supervisord on containerVM image) on all daemons including docker, that babysitter should detect the normal docker hang issue, and restart docker. But for this particular failure, even babysitter detects the issue, but restart docker will fail. Only way to recover is rebooting node. 

To fix the issue, Kubelet should have timeout on calling docker version to detect the docker's healthiness. If timeout, claim the container is hung, and set NodeNotReady.

**Comment by yujuhong** [comment]
> To fix the issue, Kubelet should have timeout on calling docker version to detect the docker's healthiness. If timeout, claim the container is hung, and set NodeNotReady.

I am a bit confused by the sentence @dchen1107. Do you imply that `docker version` would also hang when `docker ps` hangs? I don't think this is the case...

**Comment by dchen1107** [comment]
I believe docker version remote API call should hang. That is different from docker version CLI call since CLI has timeout in recent releases.  In old docker releases, docker version CLI hang when docker ps hang. The recent docker releases adding timeout to CLI. Here is an output of docker version:

```
# docker version
Client version: 1.7.0
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 0baf609
OS/Arch (client): linux/amd64
Server version: 1.7.0
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 0baf609
OS/Arch (server): linux/amd64
```

If daemon hung, you won't see the information of Server* information. @spiffxp Could you help us to verify this?

**Comment by dchen1107** [comment]
@spiffxp what is your os distro? Here is the issue reported against ubuntu: https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1403152

**Comment by spiffxp** [comment]
@dchen1107 I've been running the CoreOS alpha channel, currently at 845.0.0, which I believe comes with docker 1.8.3

**Comment by spiffxp** [comment]
Anecdotally, when the docker daemon gets in this state, `docker images` returns fine.  I'll see what version does next time I run into it.

**Comment by yujuhong** [comment]
> Anecdotally, when the docker daemon gets in this state, docker images returns fine. I'll see what version does next time I run into it.

Yes, `docker images` seems to work according to `https://github.com/docker/docker/issues/13885`

**Comment by spiffxp** [comment]
Showing symptoms
```
core@node-001 ~ $ dmesg | grep veth6861c6f
[ 1106.692600] eth0: renamed from veth6861c6f
[ 1246.946867] veth6861c6f: renamed from eth0
[ 1247.038795] IPv6: veth6861c6f: IPv6 duplicate address fe80::42:aff:fef4:1511 detected!
[ 1257.217074] unregister_netdevice: waiting for veth6861c6f to become free. Usage count = 1
```

The 'duplicate address' message looks suspicious.  There are many prior occurrences for other addresses, but this is the only (and final) one that references a `veth` device instead of `eth0`
```
core@node-001 ~ $ dmesg | grep 'duplicate' | tail -n3
[ 1219.551185] IPv6: eth0: IPv6 duplicate address fe80::42:aff:fef4:1536 detected!
[ 1219.797170] IPv6: eth0: IPv6 duplicate address fe80::42:aff:fef4:1538 detected!
[ 1247.038795] IPv6: veth6861c6f: IPv6 duplicate address fe80::42:aff:fef4:1511 detected!
```

Docker version shows the server's version
```
core@node-001 ~ $ docker version
Client:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.4.3
 Git commit:   cedd534-dirty
 Built:        Thu Nov 19 23:12:57 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.4.3
 Git commit:   cedd534-dirty
 Built:        Thu Nov 19 23:12:57 UTC 2015
 OS/Arch:      linux/amd64
```

Docker info output
```
core@node-001 ~ $ docker info
Containers: 121
Images: 110
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.2.2-coreos-r2
Operating System: CoreOS 870.2.0
CPUs: 4
Total Memory: 14.69 GiB
Name: node-001
ID: GY3L:2ADU:SZU2:AXS5:IGMB:GWNJ:VTF7:KLGE:FLPR:F6TC:VFXY:MX3H
```

**Comment by dchen1107** [comment]
@spiffxp Thanks for the updates. Looks like docker 1.8.3 also work around the issue. cc @vishh Using docker version cannot reliably detect docker hang issue now. We used to use "docker ps" to detect such issue, but since it is relatively heavy operation, and potentially causes more issues on a busy node, we switch to docker version. 

On another hand, I really don't want Kubelet becoming machine doctor / software doctor. It is impossible for Kubelet to make that comprehensive for all os distro and different hardwares, etc. I expect there are separate daemons running on the node to detect the kernel, filesystem, and hardware issues, and report to kubelet. 

For this particular issue, we could try to use docker ps less frequently to babysit docker daemon?

**Comment by bprashanth** [comment]
I saw this very recently (https://github.com/docker/docker/issues/5618, I think). Logging into the machine and running `docker run -it` just hangs. Maybe we can record the number of failed container start attempts? or perhaps use docker ps every 1m in the health check? The node actually goes into NotReady after a while because the kubelet gets really slow, but by then the e2e suite has finished.

**Comment by yujuhong** [comment]
> Maybe we can record the number of failed container start attempts?

This wouldn't work because I believe we don't have timeout for the calls yet.

> perhaps use docker ps every 1m in the health check

@dchen1107 also suggested the same approach in the comment above https://github.com/kubernetes/kubernetes/issues/17525#issuecomment-159012215.

I am ok with that since in general we should restart docker if it's not healthy. Just want to point out that in this specific case, where reboot is the only way to resolve the issue, docker/kubelet would get restarted frequently and kubelet may event report node ready once in a while (since kubelet checks `docker version`) to keep the node from being moved to NodeNotReady by node controller.

**Comment by bprashanth** [comment]
Recording number of failed container start attempts will be useful for other failure modes too, eg: https://github.com/kubernetes/kubernetes/issues/17518#issuecomment-158736628. Obviously we don't want to bounce the node in this case, just motivation.

**Comment by yujuhong** [comment]
> Recording number of failed container start attempts will be useful for other failure modes too, eg: #17518 (comment). Obviously we don't want to bounce the node in this case, just motivation.

This might be useful in other cases for introspection (but could also be discovered by restart count + error message), but I don't know how it'd help detect docker health issues.

**Comment by bprashanth** [comment]
In the particular case mentioned marking the pod as failed after a threshold of restart counts would've put it on another node, and I believe the test would've passed (so not desirable in a test because it papers over issues, but desirable in production). I view recording failed attempts as one half of the problem, which when implemented along with docker timeouts might solve this one as well.

**Comment by bprashanth** [comment]
More generally, timeout on calls + noticing abnormally high number of failed docker calls like the counter in /stats

**Comment by dchen1107** [comment]
Agreed with @yujuhong: https://github.com/kubernetes/kubernetes/issues/17518#issuecomment-158736628 doesn't help with docker issue at all. 
Yes, running docker ps can detect most of docker health issue and restarting docker daemon can mitigate most of issues causing by hung docker. 

@yujuhong since docker version cannot reliably detect docker health issue, we should use other mechanism (like docker ps). Both daemon babysitter and Node StatusManager should be consistent.

**Comment by yujuhong** [comment]
> More generally, timeout on calls + noticing abnormally high number of failed docker calls like the counter in /stats

Just to clarify, I agree with this approach in general. We'll need to add timeout and detect the 500 error code for every docker call.
I am not sure how much more docker issues would be caught by this compared with simply doing `docker ps`. From the reported docker issues, it seems `docker ps` might be good enough for most cases. If we discover that `docker ps` is not enough, we'd have more incentive to prioritize this. On the other hand, adding timeout is good for the health of kubelet, and there is an open issue for that.

**Comment by bprashanth** [comment]
A simple test would be to do somtething like chmod -R 0444 /var/lib/docker/ and see if pods start. I'd expect something like that to surface in a health check, be it docker or otherwise.

**Comment by jdef** [comment]
related: the kubelet/container/runtime_cache hangs when this happens because it executes a blocking op while holding a mutex:

v1.1.1:
https://github.com/mesosphere/kubernetes/blob/v0.7.0-v1.1.1/pkg/kubelet/container/runtime_cache.go#L114

**Comment by dchen1107** [comment]
I believe this one is addressed through:

1) our daemon watcher call docker ps instead of docker version now.
2) When docker is hung, kubelet did mark the node NotReady. 

Of course the root cause and how to mitigate this issue is still under discussion and tracked by #20096

@yujuhong Please feel free to open the issue if you disagree.

**Comment by guoshimin** [comment]
@dchen1107 Can you point me to the code where kubelet calls docker ps to check docker health? We are running 1.2.4 and we just had a case where kubelet didn't detect docker daemon was hung and all I could see in the docker daemon log was version and images calls.

/cc @thomaso-mirodin

**Comment by yujuhong** [comment]
@guoshimin kubelet doesn't call `docker ps` to detect whether the daemon hung. The daemon babysitter should be doing this. In the default GCE cluster setup with containervm images, supervisord is the one checking them.

**Comment by guoshimin** [comment]
@yujuhong OK so GCE has a way to address this problem but that shouldn't be grounds for closing this issue. Also in our case kubelet didn't mark the node NotReady when docker is hung. How exactly does kubelet notice docker is hung?

**Comment by daniilyar** [comment]
Running Kube 1.4.3 at Ubuntu 14.04.4 LTS and Docker 1.11.2 and AWS. After Docker daemon hanged (*docker version* worked, *docker ps* was hanging forever), Kubelet didn't mark the node NotReady, and no pods were marked as 'Unhealthy'. 

Kubelet logs:
```
E1101 06:35:53.196054    6953 pod_workers.go:184] Error syncing pod df28408f-9ea5-11e6-85f2-0e064dc89aa0, skipping: failed to "KillContainer" for "notification-service" with KillContainerError: "operation timeout: context deadline exceeded"
E1101 06:36:09.317531    6953 pod_workers.go:184] Error syncing pod f5d9ef31-9ba0-11e6-abbe-0e064dc89aa0, skipping: failed to SyncPod: operation timeout: context deadline exceeded
E1101 06:36:09.392964    6953 generic.go:193] GenericPLEG: Unable to retrieve pods: operation timeout: context deadline exceeded
E1101 06:36:10.015611    6953 kubelet.go:2019] Error listing containers: dockertools.operationTimeout{err:(*errors.errorString)(0xc8200110c0)}
E1101 06:36:10.021485    6953 kubelet.go:2372] Failed cleaning pods: operation timeout: context deadline exceeded
E1101 06:36:46.522352    6953 exec.go:78] error executing command in container: operation timeout: context deadline exceeded
W1101 06:37:11.748502    6953 image_gc_manager.go:139] [imageGCManager] Failed to monitor images: operation timeout: context deadline exceeded
E1101 06:38:10.021823    6953 kubelet.go:2019] Error listing containers: dockertools.operationTimeout{err:(*errors.errorString)(0xc8200110c0)}
E1101 06:38:10.021851    6953 kubelet.go:2372] Failed cleaning pods: operation timeout: context deadline exceeded
```

IMO, Kubelet should monitor docker via some more 'real-world' command - `docker ps` or `docker run rather than `docker version`.

**Comment by Raffo** [comment]
@daniilyar I had the same, any workaround or hint. I upgraded to 1.12.1, but had the same.

**Comment by daniilyar** [comment]
@Raffo, in our case docker daemon hangs on Ubuntu were caused by issues with _devicemapper_ storage driver. Upgrading or downgrading Docker didn't help, only switching docker to _AUFS_ fixed the problem for us on all Ubuntu 14 servers. See related https://github.com/docker/docker/issues/12606

**Comment by seanknox** [comment]
@Raffo posted this in https://github.com/docker/docker/issues/5618#issuecomment-264671313, hoping it might tip you in the right direction. We were seeing the same symptoms mentioned in this thread on Kubernetes v1.4.4; an unresponsive Docker daemon (tested via `docker ps`) leading to the Kubelet timing out with errors:
```

Dec 01 09:15:41 ip-10-250-12-130.ec2.internal kubelet-wrapper[1759]: E1201 09:15:41.620280    1759 generic.go:193] GenericPLEG: Unable to retrieve pods: operation timeout: context deadline exceeded
Dec 01 09:15:42 ip-10-250-12-130.ec2.internal kubelet-wrapper[1759]: E1201 09:15:42.514086    1759 kubelet.go:2035] Error listing containers: dockertools.operationTimeout{err:(*errors.errorString)(0xc8200303b0)}
Dec 01 09:15:42 ip-10-250-12-130.ec2.internal kubelet-wrapper[1759]: E1201 09:15:42.514800    1759 kubelet.go:2372] Failed cleaning pods: operation timeout: context deadline exceeded
```
...during all of this Kubernetes reported the node as healthy.

---
I was also able to reproduce this issue using https://github.com/crosbymichael/docker-stress on a Kubernetes worker node running CoreOS Stable 1185.3.0.

Running `docker_stress_linux_amd64 -k 3s -c 5  --containers 1000`: 5 concurrent workers creating/deleting containers, max lifetime of containers = 3s, create up to 1000 containers on an m4.large instance on AWS would leave the Docker daemon unresponsive after about three minutes.

Upgraded to CoreOS Beta 1235.1.0 and I haven't been able to reproduce (both the unresponsiveness or the `unregister_netdevice` message in the kernel logs). Whereas running 5 concurrent docker_stress workers would kill CoreOS Stable after a few minutes, I was able to run with 10 and 15 concurrent workers until test completion using CoreOS Beta. 

CoreOS releases in "channels" so it's not possible to upgrade the kernel in isolation. Here are the major differences between stable and beta:

## CoreOS Stable 1185.3.0
### kernel: 4.7.3
### docker: 1.11.2

## CoreOS Beta 1235.1.0
### kernel: 4.8.6
### docker: 1.12.3

**Comment by yujuhong** [comment]
#37865 may help a little bit. Kubelet will report node not ready if the periodic `docker ps` doesn't report back in time.

**Comment by duglin** [comment]
I believe this is still an issue since we're seeing cases where "docker version" returns ok but starting containers will generate an error.

What do people think about changing the check from `docker version` to some flavor of `docker run ...` ?

I can think of other types of checks, or even making it configurable in some way, but those could be follow-on PRs. For now, I think just doing a more realistic check (like docker run) might help a lot of people out.

Thoughts?

/cc @jmcmeek @treytabner @nkkashyap

**Comment by duglin** [comment]
ping @dchen1107

**Comment by hanikesn** [comment]
We definitely still have the problem that the docker daemon gets stuck, but the scheduler will still schedule pods to this node. They will never get started, but also not rescheduled.
