### ISSUE TITLE
kubectl logs with flag --since-time causes error

### ISSUE THREAD

**Issue by zreigz** [kubernetes/kubernetes#17561]
I noticed problem when I execute command:
kubectl logs redis-master-4h22s --since-time="2015-11-20T10:24:56+00:00"
Without flag  --since-time works perfect.
With flag I have error:
Error from server: Unable to convert <nil> to conversion.structAdaptor{typ:(*reflect.rtype)(0x16823e0), ptr:(unsafe.Pointer)(0xc820ef4e20), flag:0xd9}

**Comment by mikedanese** [comment]
cc @smarterclayton @ncdc

**Comment by smarterclayton** [comment]
This looks like our generic conversion is barfing on the type.

**Comment by smarterclayton** [comment]
@jwforres does the origin log console use sinceTime?

**Comment by jwforres** [comment]
Pretty sure we only use lines and maxBytes

**Comment by kargakis** [comment]
sinceTime is embedding time.Time. This is the same issue as https://github.com/openshift/origin/pull/5396#issuecomment-151142232

This has started happening since the last refactoring in kubectl logs due to changing the manual conversion of parameters to use [VersionedParams](https://github.com/kubernetes/kubernetes/blob/643cb7a1c7499df4e569f4f0fbd3b18c0c4e63ce/pkg/client/unversioned/pods.go#L126) which is trying to convert. I'll have a temporary fix baked shortly but the bigger problem (broken convertor) remains.

**Comment by kargakis** [comment]
> This has started happening since the last refactoring in kubectl logs due to changing the manual conversion of parameters to use VersionedParams which is trying to convert. I'll have a temporary fix baked shortly but the bigger problem (broken convertor) remains.

Actaully this is a problem since `--since-time` was added and there is no workaround to it other than fixing the conversion :(

**Comment by kargakis** [comment]
@smarterclayton is there an issue about broken conversion for inline structs?

**Comment by bgrant0607** [comment]
cc @lavalamp

**Comment by smarterclayton** [comment]
Uh, I wasn't aware of any.  Inline should be easy to fix, it's just truly nested that is ugly.

**Comment by lavalamp** [comment]
It should be easy to repro in a unit test if this is the case, right?
