### ISSUE TITLE
PTY allocation request failed

### ISSUE THREAD

**Issue by raffaelespazzoli** [kubernetes/kubernetes#17576]
I get this error when I try to connect to a node with kubernetes master running as a container: "PTY allocation request failed on channel 0"

Steps to reproduce:
1. I run a mac with OS X el Captain 10.11.1
2. download standard centos 7.1 from oxboxes
3. start in virtualbox 5.0.10. 1 natted interface. 1 port forward from host:2200->guest:22
4. install docker 1.9
5. ssh into the centos
6 run the following(as per kubernetes user manual):
6.a docker run --net=host -d gcr.io/google_containers/etcd:2.0.12 /usr/local/bin/etcd --addr=127.0.0.1:4001 --bind-addr=0.0.0.0:4001 --data-dir=/var/etcd/data
6.b docker run --volume=/:/rootfs:ro --volume=/sys:/sys:ro --volume=/dev:/dev --volume=/var/lib/docker/:/var/lib/docker:ro --volume=/var/lib/kubelet/:/var/lib/kubelet:rw --volume=/var/run:/var/run:rw --net=host --pid=host --privileged=true -d gcr.io/google_containers/hyperkube:v1.0.1 /hyperkube kubelet --containerized --hostname-override="127.0.0.1" --address="0.0.0.0" --api-servers=http://localhost:8080 --config=/etc/kubernetes/manifests
6.c docker run -d --net=host --privileged gcr.io/google_containers/hyperkube:v1.0.1 /hyperkube proxy --master=http://127.0.0.1:8080 --v=2
7. ssh into the centos again, you'll get the following error: "PTY allocation request failed on channel 0"

I'm opening this issue in kubernetes because otherwise the above configuration seems to be working fine. Only when I start kubernetes the issue shows up.

Thanks
Raffaele

**Comment by mikedanese** [comment]
Please re-post your question to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes). 

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases. 

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to similar questions, and also familiarize yourself with:
   * [the user guide](http://kubernetes.io/v1.0/)
   * [the troubleshooting guide](http://kubernetes.io/v1.0/docs/troubleshooting.html)

Again, thanks for using Kubernetes.

The Kubernetes Team

**Comment by bgrant0607** [comment]
@raffaelespazzoli Sorry for the delay. Did you ever resolve this problem? How did you authenticate to ssh before running Kubernetes? What security features do you have enabled?

**Comment by raffaelespazzoli** [comment]
I never solved this nor understood what the cause was. I'm not managing the
sever where this used to happen and I'm not able to reproduce it anymore.
I'm good with closing this issue.

I was using a one node cluster with no authentication on red hat and
centos. I was using username and password as a mean of authentication for
ssh.

Thanks
Raffaele


On Tuesday, March 1, 2016, Brian Grant <notifications@github.com> wrote:

> @raffaelespazzoli <https://github.com/raffaelespazzoli> Sorry for the
> delay. Did you ever resolve this problem? How did you authenticate to ssh
> before running Kubernetes? What security features do you have enabled?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kubernetes/kubernetes/issues/17576#issuecomment-190600989>
> .
>


-- 
ciao/bye
Raffaele

**Comment by disneyworldguy** [comment]
Running into this same issue myself.

> $ ssh hostname
> PTY allocation request failed on channel 0

Using a recommendation from http://bit.ly/1p2aFuH, logging in via following is somewhat functional, but still returns an error along the way:

> $ ssh user@hostname "/bin/bash -i"
> bash: cannot set terminal process group (-1): Inappropriate ioctl for device
> bash: no job control in this shell

Thanks in advance!
Kyle

**Comment by disneyworldguy** [comment]
Just a quick update. It turns out this isn't just an issue for Kubernetes, it is an issue for any container that bind mounts /dev.

Before starting the kubernetes container:

> $ ls -l /dev/ptmx
> crw-rw-rw- 1 root tty 5, 2 Mar  7 11:29 /dev/ptmx

After:

> $ ls -l /dev/ptmx
> lrwxrwxrwx 1 root root 8 Mar  7 11:29 /dev/ptmx -> pts/ptmx


Currently working on why the Docker daemon seems to symlink the ptmx interface instead of leaving it alone. Simply recreating the /dev/ptmx device node corrects the issue:

> sudo rm /dev/ptmx
> sudo mknod -m 666 /dev/ptmx c 5 2

Kyle

**Comment by mikedanese** [comment]
Thanks! https://github.com/opencontainers/runc/issues/80

**Comment by mikedanese** [comment]
Closing since this appears to be a docker issue.
