### ISSUE TITLE
PR checks didn't catch verify issues

### ISSUE THREAD

**Issue by krousey** [kubernetes/kubernetes#17679]
https://github.com/kubernetes/kubernetes/pull/15674 caused a verify issue in mainline as noted here: https://github.com/kubernetes/kubernetes/pull/15674#issuecomment-159026245. The verify issue seems to have passed in Travis. What happened?

cc @ixdy @ihmccreery

**Comment by ixdy** [comment]
The "e2e-not-required" label was put on the PR, which meant that the mergebot didn't re-run any tests. The last run of tests was from [11 days earlier](https://github.com/kubernetes/kubernetes/pull/15674#issuecomment-156313091). It's highly likely that something broke in the intervening time.

We should probably update mergebot so that "e2e-not-required" still makes mergebot re-run unit tests with "@k8s-bot unit test this". Or really it should just expire any test results after some period of time.(Maybe 3 days? 7 days at most?)

@brendandburns @eparis

**Comment by ixdy** [comment]
Oh, I already opened an issue on exactly this problem.

https://github.com/kubernetes/contrib/issues/197

I'm gonna close this one.
