### ISSUE TITLE
Kubectl couldn't read version from server

### ISSUE THREAD

**Issue by zhengguoyong** [kubernetes/kubernetes#17713]
i setup a k8s 2 nodes cluster on ubuntu, then i use kubectl to get nodes, it failed.
use k8s version:  v1.1.1
root@zgy:/home/zgy/code/master/src/kubernetes/cluster/ubuntu/binaries# ./kubectl -s http://127.0.0.1:8080 get nodes
error: couldn't read version from server: Get http://127.0.0.1:8080/api: dial tcp 127.0.0.1:8080: connection refused
root@zgy:/home/zgy/code/master/src/kubernetes/cluster/ubuntu/binaries# ./kubectl config view
apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: http://10.67.57.247:8080
  name: ubuntu
contexts:
- context:
    cluster: ubuntu
    user: ubuntu
  name: ubuntu
current-context: ubuntu
kind: Config
preferences: {}
users:
- name: ubuntu
  user:
    password: cjh3dg8AO9AbPYaJ
    username: admin

root@zgy:/home/zgy/code/master/src/kubernetes/cluster/ubuntu/binaries# ./kubectl version
Client Version: version.Info{Major:"1", Minor:"1", GitVersion:"v1.1.1", GitCommit:"92635e23dfafb2ddc828c8ac6c03c7a7205a84d8", GitTreeState:"clean"}
^Croot@zgy:/home/zgy/code/master/src/kubernetes/cluster/ubuntu/binaries# 

Ref:  #10539

**Comment by JeffChien** [comment]
have a look at https://github.com/kubernetes/kubernetes/issues/14474, it works for me

**Comment by zhengguoyong** [comment]
thanks very much.
i will try later. :)
@JeffChien

**Comment by lavalamp** [comment]
Sorry for delay--

Please re-post your question to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes). 

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases. 

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to similar questions, and also familiarize yourself with:
   * [the user guide](http://kubernetes.io/v1.0/)
   * [the troubleshooting guide](http://kubernetes.io/v1.0/docs/troubleshooting.html)

Again, thanks for using Kubernetes.

The Kubernetes Team
