### ISSUE TITLE
Is nodecontroller also responsible for create new node based on cloudprovider query?

### ISSUE THREAD

**Issue by xinxiaogang** [kubernetes/kubernetes#17726]
Hi, I didn't see any code from https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/node/nodecontroller.go that be responsible for creating new node in Kubenetes cluster based on cloudprovider.

Can anyone tell me where is the code? Or explain what is the main responsibility for nodecontroller?

**Comment by davidopp** [comment]
Kubelets register themselves by creating a Node object in the API server. So NodeController doesn't have to deal explicitly with that. It does *delete* nodes that have been removed from the cloud provider, however. All of the relevant logic is in monitorNodeStatus() in nodecontroller.go

In general, NodeController is responsible for updating the NodeReady condition of node status to ConditionUnknown when a node becomes unreachable (e.g. due to the node being down), and then later evicting all the pods from the node (using graceful termination) if the node continues to be unreachable. (The current timeouts for those are 40s and 5m, respectively.) It also allocates CIDR blocks to new nodes 

If you have any additional questions on this topic or other general questions about Kubernetes, please post them to our StackOverflow tag:
http://stackoverflow.com/questions/tagged/kubernetes

Thanks for your interest in Kubernetes!
