### ISSUE TITLE
Documentation on cli generators

### ISSUE THREAD

**Issue by kargakis** [kubernetes/kubernetes#17833]
Currently there is none. 

What is a generator? 
Which commands (should) use generators? 
What each generator does? 
What are the differences between versions of generators? 

We should have all these info in a doc and include it in the help message of our generators commands (currently expose, run, autoscale, more to be added).

@kubernetes/kubectl @bgrant0607 @deads2k @liggitt @derekwaynecarr

**Comment by deads2k** [comment]
As an example of some of the pain we're having around this today, see this downstream issue with how to handle `expose`: https://github.com/openshift/origin/issues/6094

**Comment by deads2k** [comment]
Highlights from the linked issue as we tried to work out how to extend the use of these generators:

@deads2k
To be a little more crisp. We have lots of flags that may be used in some contexts and not others. Given that we end up having to have separate paths to handle flag validation in these cases and then we're stuck dealing with conflicting flags or different meanings, I'm hard pressed to say that this makes it easier to users to do what they want.

Given that it makes it harder for users to predict what's going to happen, harder to write code that works, and harder to review/maintain that code, I don't see a lot to recommend the approach over tailored subcommands.

@liggitt
Once expose supports pods, rcs, dcs, deployments, ingress, services, endpoints, and routes, we will have so many conflicting mutually exclusive or ignored or differently-interpeted flags that the only sane flag help will be "See extended documentation for usage". That's a sad state of affairs.

At that point, we essentially have subcommands, but without useful flag help, or command-parsing/validation assistance

**Comment by kargakis** [comment]
Side notes:

> Given that we end up having to have separate paths to handle flag validation

https://github.com/kubernetes/kubernetes/pull/17516



> Once expose supports pods, rcs, dcs, deployments, ingress, services, endpoints, and routes

https://github.com/kubernetes/kubernetes/issues/17429

**Comment by ncdc** [comment]
cc @kubernetes/rh-cluster-infra

**Comment by deads2k** [comment]
@fabianofranz @jwforres the conclusion of this issue will have impacts in origin

**Comment by bgrant0607** [comment]
From https://github.com/kubernetes/kubernetes/pull/16028#issuecomment-158549497:

The point of generators is:

A) to enable users using kubectl in a scripted fashion to pin to a particular behavior, which we may change in the future. For example, we're in the process of changing kubectl run to create Deployments and Jobs instead of RCs and Pods, which could break scripts, but provides better behavior for interactive use.

B) to enable us to potentially expand the generated objects for scenarios other than just creation, similar to how we support -f for most general-purpose commands now.

Fundamentally, the problem is that kubectl commands are not versioned in general. API type versioning only helps the generic commands that accept the types as input, and/or which do something so simple or narrow that we never expect to change it in a non-backward-compatible way, like delete.

kubectl run, for which generators were created, is the perfect example. Previously it was generating Pods, now it is generating Jobs. We could have foreseen that we'd make that particular change and have added a --generate-pod flag to retain that specific behavior, but we won't always be able to foresee the kinds of changes we'll make. Generator versions facilitate pinning to a specific set of behaviors without regard to what incompatible change might be made in the future.

In the case of namespace creation, I could easily imagine generating a LimitRange by default with a new namespace in the future. We could add a --limit-range=false flag, but what if we introduced a new policy object that wanted to create by default? There's no way to retroactively add a new flag to existing scripts. 

Generator versions provide a way to pin to an existing behavior without needing to understand different ways in which it might evolve in a non-backward-compatible fashion.

**Comment by derekwaynecarr** [comment]
@brendandburns - your input would be here appreciated as it impacts a number of PRs, most notably mine here around kubectl create subcommands: https://github.com/kubernetes/kubernetes/pull/16028

**Comment by kargakis** [comment]
I have started documenting generators in https://github.com/kubernetes/kubernetes/pull/17366, would appreciate feedback there. Docs for each generator specifically should be added in follow-up PRs.

**Comment by kargakis** [comment]
Now fixed I believe: http://kubernetes.io/docs/user-guide/kubectl-conventions/#generators
