### ISSUE TITLE
Performance on AWS: Nodes take up lots of memory

### ISSUE THREAD

**Issue by sils1297** [kubernetes/kubernetes#17888]
Steps to reproduce:

```
cd kubernetes/cluster/
export KUBERNETES_PROVIDER=aws
export MINION_SIZE=t2.micro
export NUM_MINIONS=3
./kube-up.sh
```

Expected results:

A cluster with three minions spawns up, having most of it's performance available for my application.

Actual results:

All three nodes take up 77% of the memory, that's a bit over 800MB. From what I read or expect that's *far* too much. I wonder if I'm doing somthing wrong, in that case this may be a documentation bug, or this is an actual issue.

**Comment by zaa** [comment]
You may need to disable cluster logging, monitoring. See cluster/aws/config-default.sh (ENABLE_CLUSTER_MONITORING, ENABLE_NODE_LOGGING, ENABLE_CLUSTER_LOGGING, etc)

**Comment by sils1297** [comment]
Hm, it doesn't look much better. Before disabling logging:

![screenshot from 2015-11-27 20-59-26](https://cloud.githubusercontent.com/assets/5716520/11456566/33e3db20-968d-11e5-9b70-6270c3011412.png)

After disabling logging:

![screenshot from 2015-11-29 11-34-31](https://cloud.githubusercontent.com/assets/5716520/11456567/33e52174-968d-11e5-9533-bf5727bbe2c5.png)

Memory is still high up. I simply did

```
cd kubernetes/cluster/
export KUBERNETES_PROVIDER=aws
export MINION_SIZE=t2.micro
export NUM_MINIONS=2

export KUBE_ENABLE_NODE_LOGGING=false
export KUBE_ENABLE_CLUSTER_LOGGING=false
export KUBE_ENABLE_CLUSTER_MONITORING=none

./kube-up.sh
```

and the logging services indeed vanished:

```
lasse@localhost ~/prog/kube/kubernetes/cluster % ./kubectl.sh cluster-info
Kubernetes master is running at https://52.34.231.65
KubeDNS is running at https://52.34.231.65/api/v1/proxy/namespaces/kube-system/services/kube-dns
KubeUI is running at https://52.34.231.65/api/v1/proxy/namespaces/kube-system/services/kube-ui
```

So no real improvement here.

**Comment by dchen1107** [comment]
@sils1297 Thanks for reporting the issue and we are working on improving node performance. If your cluster is still running, could you please provide more information on who is using those memory on a node, like Kubelet, docker, kube-proxy, and other daemons on those nodes? Since you already disabled monitoring service, you can get those stats from monitoring service. But you still have those information from cAdvisor. Thanks. cc/ @yujuhong

**Comment by sils1297** [comment]
@dchen1107 sure, it's totally reproducable, I've redeployed the cluster multiple times since then with several machine sizes and it's actually the same every time. Interestingly the memory consumption even rose when I choose VMs with bigger memory.

How can I get the info you desire? I just began working with kubernetes a few days ago.

**Comment by yujuhong** [comment]
@sils1297, you can try deploying [kubedash](https://github.com/kubernetes/kubedash) to see memory consumption of pods/daemons on each node. You just need to clone the repository and run `kubectl create -f deploy/kube-config.yaml`. At the dashboard, you can click on individual nodes to see the stats.

By the way, how long was your cluster up before consuming this much memory? If it turns out that kubelet is the culprit here, could you disable kubelet logging level by either passing "--v=0" to kubelet directly or set KUBELET_TEST_ARGS="--v=0" (if you use a gce cluster) to see if it helps?

**Comment by sils1297** [comment]
@yujuhong the memory consumption was that high right from the initial construction of the cluster. Since then I've deployed only one application, that didn't change much, and a few days later it's still the same.

I'll deploy kubedash ASAP.

**Comment by sils1297** [comment]
@yujuhong ok, now there's something happening that's either completely wrong or I totally not understand. When I created the RC and SVC from the yaml, neither of them and no pods appeared, then this happened:

```
lasse@localhost ~/prog/gitmate (git)-[master] % k delete rc kubedash
Error from server: replicationControllers "kubedash" not found
lasse@localhost ~/prog/gitmate (git)-[master] % k create -f kubedash.yaml
Error from server: error when creating "kubedash.yaml": replicationControllers "kubedash" already exists
```

(k is my alias to kubectl.sh)

**Comment by yujuhong** [comment]
@sils1297, kubedash is running in the `kube-system` namespace by default. You should be able to see the pod & service by specifying "--namespace=kube-system" or simply "--all-namespaces".

**Comment by sils1297** [comment]
@yujuhong thanks, still not there though, it doesn't show any nodes: http://ab5068cfa9a6211e5aa1902d53657a61-39424795.us-west-2.elb.amazonaws.com/#!/nodes/

The few values I get (95% memory and cpu consumption for the cluster, no values for the nodes apparently) don't match with the ones on the Kube UI. (About 80% memory consumption, not a lot of CPU consumption.)

**Comment by yujuhong** [comment]
@sils1297, do you have heapster running in your cluster? kubedash relies on heapster for stats scraping.

/cc @vishh

**Comment by sils1297** [comment]
@yujuhong nope, I just did

```
cd kubernetes/cluster/
export KUBERNETES_PROVIDER=aws
export MINION_SIZE=t2.micro
export NUM_MINIONS=2

export KUBE_ENABLE_NODE_LOGGING=false
export KUBE_ENABLE_CLUSTER_LOGGING=false
export KUBE_ENABLE_CLUSTER_MONITORING=none

./kube-up.sh

kubectl.sh create -f kubedash.yaml
```

**Comment by yujuhong** [comment]
Could you *not* disable `KUBE_ENABLE_CLUSTER_MONITORING` and try again? Adding these pods would affect the resource usage but at least we could see the stats.

Alternatively, you could run `kubectl proxy` and access `http://localhost:8001/api/v1/proxy/nodes/<node_name>:4194/` to see directly see the stats exposed by cadvisor (which is part of kubelet).

**Comment by sils1297** [comment]
> Could you not disable KUBE_ENABLE_CLUSTER_MONITORING and try again? Adding these pods would affect the resource usage but at least we could see the stats.

Sorry, thats currently bad.

Though I did the second thing, the proxy is a nice feature by the way. I'll upload some data in a minute.

**Comment by sils1297** [comment]
Apparently this is actually the easiest way of sharing that data, this is the top processes for both nodes:

![screenshot from 2015-12-04 22-21-16](https://cloud.githubusercontent.com/assets/5716520/11601748/920da72a-9ad5-11e5-8c5b-c6fb266f86e6.png)

![screenshot from 2015-12-04 22-21-25](https://cloud.githubusercontent.com/assets/5716520/11601734/83a479f2-9ad5-11e5-8aff-d1fea87c9520.png)

**Comment by yujuhong** [comment]
@sils1297, you can click individual containers to see the reported memory working set graphs, which provides more information.

On the other hand, it seems kube-ui reports the total memory usage (including the cold pages). See https://github.com/kubernetes/kubernetes/issues/15444#issuecomment-149702603

Heapster/kubedash reports memory working set, which should be smaller than what kube-ui reports. On the other hand, kubelet and docker-daemon's memory working set may appear to be large at times. This is because we don't set memory limit for these two daemons yet, hence there is no memory pressure to trigger kernel to move pages from the active to the inactive list. We plan to set a reasonable memory limit for our daemons to mitigate this problem.

**Comment by sils1297** [comment]
@yujuhong not sure what to make of this and what information you want from me. Maybe it's even easier if you spawn your own AWS cluster and see if you can reproduce this, for me the memory usage is the same whenever I started the cluster so it's deterministic.

**Comment by yujuhong** [comment]
To sum up:
- Known issue: kube-ui doesn't provide an accurate view of memory usage; it provides total memory used instead of the working set. This should be reported to kube-ui.
- Known issue: heapster/cadvisor reports memory working set, but the number could be misleading for kubelet and docker-daemon, due to the fact that we don't set memory limit. We are working on fixing this.

@sils1297, from the cadvisor webpage, you should be able to click individual containers to see the reported memory working set. You could then see the memory working set graphs and identify the containers that appear to have a huge memory working set.

**Comment by sils1297** [comment]
Hi, I don't have the time to investigate this further. You seem to have some known issues so I guess it's best to close this, if you don't want to investigate this with an own AWS cluster (at least for me it was totally reproducable).

**Comment by yujuhong** [comment]
@sils1297 thanks for reporting this, and I appreciate your time. I don't have access to an AWS cluster now, so it's unlikely that I will pursue this further anytime soon. I am closing this but feel free to reopen the issue if you have more information. Thanks again.
