### ISSUE TITLE
Unused images not removed, minion ran out of disk

### ISSUE THREAD

**Issue by evanphx** [kubernetes/kubernetes#17994]
Some minions stop working today and I went to go figure out why. I found `/var/lib/docker` having 2.5G of data (/ is only 8G) and a number of dangling images: `docker images -f "dangling=true" | wc -l => 32`.

Does kubernetes GC the images? If so, when?

**Comment by evanphx** [comment]
I see that there are also a number of exitted but not removed containers: `docker ps -a | grep Exit | wc -l => 97`. I'm sure that is also contributing to the issue.

**Comment by evanphx** [comment]
I ran `docker rm $(docker ps -a -q); docker rmi $(docker images -f "dangling=true" -q)` and recovered about 1.8G of disk space.

**Comment by thockin** [comment]
@vishh @mikedanese I am sure this can be folded in with other issues.  We should really recommend larger disks by default.

**Comment by evanphx** [comment]
I should note this was setup using `kube-up` on AWS. The default instance type didn't work because of a bug in how `empty-dir` uses instance storage (and fills it up), so I picked another easy to use instance type and the defaults configured the 8G root partition.

**Comment by dchen1107** [comment]
For 1.1 release, we introduced a new node condition called OutOfDisk, but not taking any action from both kubelet and scheduler. For 1.2 release, we plan to make both kubelet and scheduler to handle OutOfDisk situation: https://github.com/kubernetes/kubernetes/issues/4135 cc/ @madhusudancs who is handling this currently.

But above situation, we assume kubelet can relative detect disk usage through cAdvisor. Assigning this to @vishh since he is driving disk managment ingeneral.

**Comment by vishh** [comment]
@evanphx What version of kube are you running? Kubelet is expected to recover disk space by deleting old containers and images. Such garbage collection doesn't happen unless usage on `/` exceeds 90% though.

**Comment by evanphx** [comment]
1.0, I don't recall which patch level off hand. I got this again today with
10 or so pods dieing with OutOfDisk and k8 never gc'd docker.

By the by, it's quite frustrating that there is no blessed upgrade process
for AWS, just a note about kube-push and that it's experimental.

**Comment by vishh** [comment]
@justinsb might be able to help you with upgrades. 

I'd recommend upgrading to a more recent version that has image GC built-in.

**Comment by druidsbane** [comment]
On AWS /mnt/ephemeral is out of disk space but the root is pretty empty.  I have 19 exited but not garbage collected containers and a couple of dangling images as well.  The PODs are dying on FailedSync not OutOfDisk.  I'm on 1.1.4 so I would expect that this would trigger GC but since we aren't hitting that state any ideas on how to deal with this?  Will GC happen on the 1.1.4 version or do I need to move to 1.2?

**Comment by vishh** [comment]
GC is expected to happen on 1.1.4. Kubelet will GC if the partition that
docker is using hits the high watermark.
What is `/mnt/ephemeral` used for in AWS?

**Comment by druidsbane** [comment]
I'm not 100% certain why we have /mnt/ephemeral and everything isn't just on the root image.  As it stands now the AWS script symlinks /var/lib/docker and /var/lib/kubernetes to that mount point and I guess that isn't being checked by the garbage collector thresholding process. Also I couldn't find a way to manually force a garbage collect to see if that would fix the issue so I ended up unable to load up any new images which were replacements for many test deployments that were done that caused us to run out of space.

**Comment by evanphx** [comment]
@druidsbane That's what the AWS setup scripts do if the AWS instance type has instance storage (which is governed the instance type).

If you rebuild the cluster with an instance type that does not have instance storage, you won't have this issue. That's how I got around this problem.

@justinsb mentioned this to be back when I opened the issue. I still think that the AWS install scripts should be modified to NOT use instance storage. They're too small and users constantly run into this issue.

**Comment by druidsbane** [comment]
Thanks @evanphx and @vishh, finding a different type helped.  The only thing is if we do intend to use that storage it should be added as part of the GC scripts otherwise we won't gain much benefit.  I couldn't find a way to set a larger ephemeral storage either but regardless it would eventually fill up.

**Comment by vishh** [comment]
Kubelet attempts to identify the filesystem that docker uses for images and
use that for GC. If kubelet is not running GC, then I'd suspect some issues
with that logic.

**Comment by openxxs** [comment]
Hi @vishh, I meet the same issue. for Kubernetes 1.1.7, docker 1.10.2 and CentOS 7, kubelet image GC only works fine in default /var filesystem. If I assign the docker parameter `--graph /opt/docker` to store images in /opt filesystem, GC never works.

**Comment by vishh** [comment]
Can you try running kubelet with `--docker_root=/opt/docker`? We are aware
of this issue and will fix it soon.

**Comment by openxxs** [comment]
Thanks @vishh , `--docker-root=/opt/docker` is really helpful. Kubernetes image GC works fine now.

**Comment by srkiNZ84** [comment]
This is really annoying. The cluster Nodes shouldn't be using ephemeral storage at all as it's just too small.

Additionally, it seems that if you add the "--docker-root" parameter and then reboot the instance, your change is lost (I'm assuming this is because of the EC2 instance bootstrap scripts) and you have to add it again and restart the "kubelet" service.

Please don't use ephemeral storage any more.

**Comment by srkiNZ84** [comment]
Ok, I added the "--docker-root=/opt/docker" option and it _still_ didn't use the main disk. Ended up running:
```
rm /var/lib/docker
rm /var/lib/kubelet
ln -s /opt/kubernetes/kubelet /var/lib/kubelet
ln -s /opt/docker /var/lib/docker
```
which finally got it to use the correct disk.

**Comment by matchstick** [comment]
Is this a dup of #27169?
