### ISSUE TITLE
Support kubectl run, expose, create --edit flag

### ISSUE THREAD

**Issue by feihujiang** [kubernetes/kubernetes#18064]
I think we should support --node-name flag for kubectl run command to run a particular image in a specified node.

**Comment by bgrant0607** [comment]
It is not my intent to support every pod spec knob in run. 

Please add kubectl run --edit instead, which would allow editing after generation but before creation.

I thought I had filed an issue for that, but couldn't find it.

**Comment by bgrant0607** [comment]
@ethernetdan This is another "kubectl run" feature that would be useful.

**Comment by kargakis** [comment]
I guess this would be useful for any kind of command that uses generators (or at least generates before creating).

**Comment by bgrant0607** [comment]
Even kubectl create --edit would be useful. That would allow us to do something like:
```
kubectl create -f http://github.com/kubernetes/templates/app.yaml --edit
```

**Comment by janetkuo** [comment]
> I guess this would be useful for any kind of command that uses generators (or at least generates before creating).

such as `kubectl expose` and `kubectl autoscale`

**Comment by ymqytw** [comment]
`kubectl run` and `kubectl expose` use generators before creating, but `kubectl create` doesn't.
A common way that should works for all these command would be:

Insert the following steps in beginning of each command

1. If the flag --edit is set, retrieve the file or url after flag -f.
2. Let the user edit it and save it as a temp file at local disk.
3. Validate the resource configuration.
4. If validation fails, go to step 2 or abort. Otherwise, create the resource.

Does this seem reasonable?

**Comment by kargakis** [comment]
@ymqytw validation happens during creation so all you really need is 1. and 2.

Also note that create is not using generators but all create subcommands do and that's where I think --edit would be more valuable.

**Comment by kargakis** [comment]
@kubernetes/sig-cli-feature-requests
