### ISSUE TITLE
Add support for Apache Hadoop HDFS as Volume

### ISSUE THREAD

**Issue by hsaputra** [kubernetes/kubernetes#18096]
Would like to have Hadoop HDFS as one of supported Volumes [1] in Kubernetes.

We have u se cases where we would like to allow process in container to access HDFS as supported Volume rather than manually mount (via FUSE).

Seemed like it is already have GlusterFS and other FS supported so I think it would be useful and 

[1] http://kubernetes.io/v1.1/docs/user-guide/volumes.html

**Comment by hsaputra** [comment]
Maybe we could extend from PR:
https://github.com/kubernetes/kubernetes/pull/13840
?

**Comment by rootfs** [comment]
Consider a couple of options
- Would HDFS NFS bridge work? If so, you may be able to use NFS volume
- Flexvolume could be a way to create HDFS FUSE

General question, what privilege does HDFS-NFS or HDFS-FUSE need? Any special uid/gid requirement?

@kubernetes/rh-storage

**Comment by wattsteve** [comment]
Kube volume plugins automate a host mount of a filesystem and then bind mount the host mount into a directory within the container. Essentially, to the container and its processes, the mounted filesystem is just another Linux directory. This means anything you mount in is expected to have full POSIX semantics. To the best of my knowledge, given that HDFS is not POSIX, I thought HDFS-NFS or HDFS-FUSE had limitations when people attempted to use them as Linux Filesystem. These limitations might cause some unexpected behaviour/errors when being used and it might be hard to communicate this sufficiently to the Pod Authors that might use such a volume plugin.

**Comment by hsaputra** [comment]
HDFS already have fuse-dfs component (via hadoop-hdfs-fuse so there are already some orgs out there using it. Since FUSE is a POSIX compliant I think it should be feasible via that abstraction.

I think people who use HDFS via mount would understand limitation that could happen since it is a "fake" file system ;)

**Comment by dchen1107** [comment]
cc/ @saad-ali

**Comment by dchen1107** [comment]
cc/ @zmerlynn

**Comment by wattsteve** [comment]
I think there's no reason not to have an HDFS FUSE or HDFS NFS volume plugin in Kube, but I'd prefer that the README.MD for any volume plugin we create points to the ASF docs for an overview on the functionality so that folks know that when they use it, things like random writes are not supported.

**Comment by drocsid** [comment]
If you just need some sort of HDFS client from inside your application: https://github.com/colinmarc/hdfs . But HDFS volume support would be nice. According to HDFS fuse docs reads and writes are slower with https://wiki.apache.org/hadoop/MountableHDFS . I'm not sure if this is also true for https://github.com/remis-thoughts/native-hdfs-fuse/blob/master/README.md . It would be nice to see HDFS volume support since I already have the HDFS filesystem deployed.

**Comment by davidstack** [comment]
@hsaputra  does this issue have any plan?

**Comment by erikbgithub** [comment]
This issue is google result number one for "kubernetes hdfs volume", so it would be cool if it would at least have an official suggestion, e.g. "don't mount it, use the ports" or something.

**Comment by rdefreitas** [comment]
I have several scenarios wherein this would be useful still
/reopen

**Comment by Tagar** [comment]
Our organization uses native HDFS client whenever possible over HDFS-fuse and HDFS-NFS options, because of following reasons.

HDFS-NFS doesn't have a good bandwidth; all HDFS data traffic goes through HDFS NFS servers, essentially making two roundtrips instead of one. 

HDFS-fuse has some stability issues (we had cases opened with Cloudera and RedHat, but they led to nowhere). 
On top of that HDFS-fuse mount doesn't support HDFS ACLs which limits our use cases a lot. 

So 3 years after this issue was opened, it still makes to have a native HDFS volume support for Kubernetes.

**Comment by wuminsure** [comment]
I think it is cool for HDFS volume support for Kubernetes.In our company, hdfs used for the base storage.The hdfs occupy all disk

**Comment by dalei2019** [comment]
really need this feature！
