### ISSUE TITLE
Worker node's status become "NOT READY"

### ISSUE THREAD

**Issue by Kwonho** [kubernetes/kubernetes#18190]
We made 9 kubernetes cluster(1 master + 8 workers).

But randomly, worker node's status become "NOT READY".

Here is the kubelet logs.(Docker process works fine at that time)

"I1204 06:26:09.828470   29219 kubelet.go:1735] Skipping pod synchronization, container runtime is not up."

**Comment by dchen1107** [comment]
Can you run command on the node: 1) docker version 2) docker ps, then copy&paste the output here?
Can you also run kubectl describe node $node-name and copy & paste the out here? Thanks!

**Comment by Kwonho** [comment]
1. docker version
docker version
Client:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   76d6bc9
 Built:        Tue Nov  3 17:43:42 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   76d6bc9
 Built:        Tue Nov  3 17:43:42 UTC 2015
 OS/Arch:      linux/amd64

2. docker ps
docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES

3. describe node( But i already restart kubelet, so the status is READY. Maybe 1 day later, the node will be changed "NOT READY". I will copy the result when the node is NOT READY.)

Name:                   10.231.2.28
Labels:                 kubernetes.io/hostname=10.231.2.28
CreationTimestamp:      Fri, 27 Nov 2015 11:39:56 +0900
Conditions:
  Type          Status  LastHeartbeatTime                       LastTransitionTime                      Reason                                  Message
  Ready         True    Fri, 04 Dec 2015 10:26:30 +0900         Fri, 04 Dec 2015 09:48:19 +0900         kubelet is posting ready status
Addresses:      10.231.2.28
Capacity:
 memory:        131866668Ki
 pods:          40
 cpu:           16
Version:
 Kernel Version:                3.13.0-24-generic
 OS Image:                      Ubuntu 14.04 LTS
 Container Runtime Version:     docker://1.9.0
 Kubelet Version:               v1.0.6
 Kube-Proxy Version:            v1.0.6
ExternalID:                     10.231.2.28
Pods:                           (0 in total)
  Namespace                     Name
Events:
  FirstSeen                             LastSeen                        Count   From                    SubobjectPath   Reason          Message
  Fri, 04 Dec 2015 09:48:19 +0900       Fri, 04 Dec 2015 09:48:19 +0900 1       {kubelet 10.231.2.28}                   starting        Starting kubelet.
  Fri, 04 Dec 2015 09:48:19 +0900       Fri, 04 Dec 2015 09:48:19 +0900 2       {kubelet 10.231.2.28}                   NodeReady       Node 10.231.2.28 status is now: NodeReady

Thanks

**Comment by sumitkgaur** [comment]
saw similiar issue on my setup. Can somebody comment on this.
Thank you

**Comment by rdgacarvalho** [comment]
please execute the follow commands and share.

sudo systemctl status etcd2 
sudo systemctl status flanneld (if you are using)
sudo systemctl status kubelet
etcdctl member list 
etcdctl cluster-health

worker nodes
sudo systemctl status calico-nodes
sudo systemctl status kubelet
sudo systemctl status etcd2
sudo systemctl status flanneld (if you are using)
etcdctl member list 
etcdctl cluster-health

Let us know more details about your environment.

Thanks

**Comment by castrojo** [comment]
Please re-post your question to [Stack Overflow](http://stackoverflow.com/questions/tagged/kubernetes).

Thanks for taking the time to report an issue to us. In the past this tracker has housed both bug reports and user support requests, we are now only using this tracker for software defects and feature tracking.   

We are trying to consolidate the channels to which questions for help/support
are posted so that we can improve our efficiency in responding to requests,
and to make it easier for you to find answers to frequently asked questions and
how to address common use cases.

The Kubernetes team scans Stack Overflow on a regular basis, and will try to
ensure your questions don't go unanswered.

If you're looking for more long-form discussion on best practices, we encourage you to check out the [Kubernetes user list](https://groups.google.com/forum/#!forum/kubernetes-users). 

You can also find more information here:

  * [User Documentation](http://kubernetes.io/docs/)
  * [Troubleshooting Guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/)

Again, thanks for using Kubernetes. If you feel this issue has been closed in error then please reopen it and we can have another look. 

The Kubernetes Team
