### ISSUE TITLE
RFC: add `pod/dockercmd` subresource

### ISSUE THREAD

**Issue by mqliang** [kubernetes/kubernetes#18205]
We propose to add a `pod/dockercmd` subresource, so that user can run some userful docker command on his container, such as commit the image of his container by running `docker commit`.

By now, k8s just support the `docker logs` and `docker attach`command by the `pod/log` and `pod/attach` subresource. Our idea is to add a general `pod/dockercmd` subresource to support more useful docker commands(and disable some dangerous commands such as `docker stop`), the existing `pod/log` and `pod/attache` subresource can be deprecated after the `pod/dockercmd` subresource is supported. 

Such a way is much more extensible: if we want support another docker command in the future, just add it to the "whitelist", instead of adding a new subresource and duplicating a lot of code.

Any comment is welcomed.

**Comment by smarterclayton** [comment]
Keeping attach and log distinct is important because then they can be secured by policy clearly.  Also, we support today multiple runtimes, so it's not clear how we abstract dockercmd to different runtime engines, and log and attach have to remain for that abstraction at a minimum.

I like the general idea of allowing imperative container commands that operate in the context of a pod container, mediated by some extension in the kubelet.  It's probably best to ask whether that abstraction *can* be runtime-agnostic - if not, the next question is whether we support runtime specific extensions invoked through the kubelet, or whether it would be better to use a DaemonSet to run a priviliged pod that proxies to docker and is accessible via the node proxy.

I do in general like the idea of having a way to commit a container in the context of a pod it is in - this is something we've been discussing recently in other issues in OpenShift - @derekwaynecarr can you xref those here?

**Comment by mqliang** [comment]
@smarterclayton 

Committing a container is such a helpful functionality. A while ago our team have started designing a plan for supporting it, but we want to make it more general and extensible: add a subresource to support all  container commands, instead of adding one subresource after another to support different commands.

>
whether it would be better to use a DaemonSet to run a priviliged pod that proxies to docker and is accessible via the node proxy.

The first question off the top of my mind is proxying a command to docker directly may add some unnecessary complexity about authorization to kubelet(I mean prohibiting a user to operate other users's container)

> 
Whether that abstraction can be runtime-agnostic - if not, the next question is whether we support runtime specific extensions invoked through the kubelet.

I think it's a implementation question, runtime-agnostic and runtime-gnostic are both not difficult to implement. But some discussion is needed. Personally, I'd like the abstraction be runtime-agnostic.

**Comment by thockin** [comment]
Given all of the things we need to sort out, this seems pretty low-priority
to me, even if it were a good idea (not saying it's not :)

**Comment by derekwaynecarr** [comment]
Do you need to commit+push for some containers on the cluster or any arbitrary container?  I originally proposed https://github.com/kubernetes/kubernetes/issues/14561 when trying to look into some OpenShift needs, but have since realized its insufficient at least for our short-term usage scenario.

An alternative to baking this into the API is to create a side-car container that you could embed in any pod that required the commit+push pattern.  The side-car container could get access to the docker daemon (meaning you have a lot of trust in this container), and it can receive traffic to tell it what peer container to commit+push in its pod?  

I think its best to explore this pattern first before taking in something more broadly powerful than run any docker command.  The first problem is the set of docker commands grow, and as @smarterclayton noted, they require different authorization to properly secure.  It's one thing to read logs, another to do an exec, etc.
