### ISSUE TITLE
unable to mount nfs volume

### ISSUE THREAD

**Issue by hitechmike** [kubernetes/kubernetes#18214]
Hello, 
I have some trouble mounting an nfs volume inside a docker container.
Can you help me ? 

Thanks and Regards

Mike

physical host (minion)
[root@LABCR3 ~]# uname -a
Linux LABCR3 3.18.17-13.el7.x86_64 #1 SMP Wed Jul 22 14:20:15 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

[root@LABCR3 ~]# cat /etc/redhat-release 
CentOS Linux release 7.1.1503 (Core) 

[root@LABCR3 ~]# rpm -qa | grep -i kube
kubernetes-client-1.0.3-0.2.gitb9a88a7.el7.x86_64
kubernetes-1.0.3-0.2.gitb9a88a7.el7.x86_64
kubernetes-master-1.0.3-0.2.gitb9a88a7.el7.x86_64
kubernetes-node-1.0.3-0.2.gitb9a88a7.el7.x86_64
[root@LABCR3 ~]# rpm -qa | grep -i docker
docker-1.8.2-7.el7.centos.x86_64
docker-selinux-1.8.2-7.el7.centos.x86_64
docker-registry-0.9.1-7.el7.x86_64
[root@LABCR3 ~]# 

Phisical host is able to mount the nfs volume.

[root@LABCR3 ~]# df -h /NFS
Filesystem                      Size  Used Avail Use% Mounted on
192.168.240.1:/mnt/VOL1/nfs-ds  500G     0  500G   0% /NFS

Here the priviliged mode enable on kubernetes on minion 
root@LABCR3 ~]# cat /etc/kubernetes/config  | grep PRIV
KUBE_ALLOW_PRIV="--allow_privileged=true"

describe on master

[root@labcr1 pods]# kubectl describe pod httpd-php 
Name:				httpd-php
Namespace:			default
Image(s):			centos7-httpd-php-alive-new
Node:				labcr3/10.99.1.203
Labels:				cont=httpd-php-mxs,name=httpd-php
Status:				Pending
Reason:				
Message:			
IP:				
Replication Controllers:	<none>
Containers:
  httpd-php-mxs:
    Image:		centos7-httpd-php-alive-new
    State:		Waiting
      Reason:		Image: centos7-httpd-php-alive-new is ready, container is creating
    Ready:		False
    Restart Count:	0
Conditions:
  Type		Status
  Ready 	False 
Events:
  FirstSeen				LastSeen			CountFrom			SubobjectPath	Reason		Message
  Fri, 04 Dec 2015 15:29:48 +0100	Fri, 04 Dec 2015 15:29:48 +0100	1	{scheduler }				scheduled	Successfully assigned httpd-php to labcr3
  Fri, 04 Dec 2015 15:31:53 +0100	Fri, 04 Dec 2015 15:38:09 +0100	4	{kubelet labcr3}			failedMount	Unable to mount volumes for pod "httpd-php_default": exit status 32
  Fri, 04 Dec 2015 15:31:53 +0100	Fri, 04 Dec 2015 15:38:09 +0100	4	{kubelet labcr3}			failedSync	Error syncing pod, skipping: exit status 32

Kubelet logs on minons 

-- Logs begin at ven 2015-12-04 14:25:39 CET, end at ven 2015-12-04 15:34:39 CET. --
dic 04 15:33:58 LABCR3 kubelet[1423]: E1204 15:33:58.986220    1423 pod_workers.go:111] Error syncing pod 7915461d-9a93-11e5-b8eb-d4bed9b48f94, skipping:
dic 04 15:33:58 LABCR3 kubelet[1423]: E1204 15:33:58.973581    1423 kubelet.go:1190] Unable to mount volumes for pod "httpd-php_default": exit status 32;
dic 04 15:33:58 LABCR3 kubelet[1423]: Output: mount.nfs: Connection timed out
dic 04 15:33:58 LABCR3 kubelet[1423]: Mounting arguments: labsn1:/mnt/VOL1/nfs-ds /var/lib/kubelet/pods/7915461d-9a93-11e5-b8eb-d4bed9b48f94/volumes/kube
dic 04 15:33:58 LABCR3 kubelet[1423]: E1204 15:33:58.973484    1423 mount_linux.go:103] Mount failed: exit status 32
dic 04 15:31:53 LABCR3 kubelet[1423]: E1204 15:31:53.939521    1423 pod_workers.go:111] Error syncing pod 7915461d-9a93-11e5-b8eb-d4bed9b48f94, skipping:
dic 04 15:31:53 LABCR3 kubelet[1423]: E1204 15:31:53.927865    1423 kubelet.go:1190] Unable to mount volumes for pod "httpd-php_default": exit status 32;
dic 04 15:31:53 LABCR3 kubelet[1423]: Output: mount.nfs: Connection timed out
dic 04 15:31:53 LABCR3 kubelet[1423]: Mounting arguments: labsn1:/mnt/VOL1/nfs-ds /var/lib/kubelet/pods/7915461d-9a93-11e5-b8eb-d4bed9b48f94/volumes/kube
dic 04 15:31:53 LABCR3 kubelet[1423]: E1204 15:31:53.927760    1423 mount_linux.go:103] Mount failed: exit status 32
dic 04 15:21:31 LABCR3 kubelet[1423]: E1204 15:21:31.119117    1423 reflector.go:183] watch of *api.Service ended with: 401: The event in requested in

**Comment by zmerlynn** [comment]
Please re-post your question to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes). 

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases. 

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to similar questions, and also familiarize yourself with:
   * [the user guide](http://kubernetes.io/v1.0/)
   * [the troubleshooting guide](http://kubernetes.io/v1.0/docs/troubleshooting.html)

Again, thanks for using Kubernetes.

The Kubernetes Team
