### ISSUE TITLE
How can I run docker in --net=host through kubectl?

### ISSUE THREAD

**Issue by yunfanzhang** [kubernetes/kubernetes#18269]
I want to run follow cmd:

    docker run -d --net=host

How can I pass the --net=host params to the docker through kubectl.

**Comment by thockin** [comment]
Any pod that has YAML can have it's `spec/hostNetwork` set to true.

**Comment by a-robinson** [comment]
Please re-post your question to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes). 

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases. 

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to similar questions, and also familiarize yourself with:
  * [the user guide](http://kubernetes.io/v1.0/)
  * [the troubleshooting guide](http://kubernetes.io/v1.0/docs/troubleshooting.html)

Again, thanks for using Kubernetes.

The Kubernetes Team

**Comment by sneak** [comment]
I found this from Google because I have the same question.  Do you happen to have a link to the answer there?

**Comment by thockin** [comment]
How about something like: kubectl run -n kube-system -i
--restart=Never --rm test-${RANDOM} --image=ubuntu
--overrides='{"kind":"Pod", "apiVersion":"v1", "spec": {"hostNetwork":
true}}'
