### ISSUE TITLE
`kubectl patch` does not work with admission controller LimitRanger and ResourceQuota

### ISSUE THREAD

**Issue by aclisp** [kubernetes/kubernetes#18272]
REPRODUCE 

latest release v1.1.2

1. Start apiserver with command line `--admission-control=NamespaceLifecycle,LimitRanger,SecurityContextDeny,ServiceAccount,ResourceQuota`
1. Create a pod with
```
kubectl --namespace=rds create -f -
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: rds
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
```
Then try to change Pod `nginx`'s image with
```
kubectl --namespace=rds patch pod nginx -p '{"spec":{"containers":[{"name":"nginx","image":"nginx:1.9.7"}]}}'
```
Output is
```
Error from server: Pod "Unknown" is forbidden: [Minimum cpu usage per Pod is 1.  No request is specified., Minimum memory usage per Pod is 2Gi.  No request is specified., Maximum cpu usage per Pod is 8.  No limit is specified., Maximum memory usage per Pod is 16Gi.  No limit is specified.]
```
After remove `LimitRanger` from apiserver's command line, repeat `kubectl patch`, the output is
```
Error from server: Pod "Unknown" is forbidden: resource name may not be empty
```
Again, remove `ResourceQuota` from apiserver's command line, repeat `kubectl patch`, the output is `"nginx" patched`

Related resourcequota and limits for this namespace is 
```
$ kubectl --namespace=rds describe limits
Name:           rds
Namespace:      rds
Type            Resource        Min     Max     Request Limit   Limit/Request
----            --------        ---     ---     ------- -----   -------------
Container       memory          2Gi     16Gi    2Gi     2Gi     -
Container       cpu             1       8       1       1       -
Pod             cpu             1       8       -       -       -
Pod             memory          2Gi     16Gi    -       -       -

$ kubectl --namespace=rds describe quota
Name:                   rds
Namespace:              rds
Resource                Used            Hard
--------                ----            ----
cpu                     2               2400
memory                  4294967296      4800Gi
persistentvolumeclaims  0               0
pods                    2               1k
replicationcontrollers  0               0
resourcequotas          1               1
secrets                 1               1
services                0               0
```

I take a look at 

In `pkg/apiserver/resthandler.go#PatchResource`, the admission control kicks in with an _empty_ object, before the `patchedObjJS` is decoded into this object. So `LimitRanger` and `ResourceQuota` admission controllers actually operate on this _empty_ object, which failed the validation.
```go
		obj := r.New()
		ctx := scope.ContextFunc(req)
		ctx = api.WithNamespace(ctx, namespace)

		// PATCH requires same permission as UPDATE
		if admit.Handles(admission.Update) {
			userInfo, _ := api.UserFrom(ctx)

			err = admit.Admit(admission.NewAttributesRecord(obj, scope.Kind, namespace, name, scope.Resource, scope.Subresource, admission.Update, userInfo))
			if err != nil {
				errorJSON(err, scope.Codec, w)
				return
			}
		}
```

Could this admission control in `PatchResource` be put after the patched object is constructed?

**Comment by lavalamp** [comment]
@erictune-- WDYT about this? It seems like multiple trips through the admitters/authorizers are needed for patch (maybe all updates). First a trip to authorize that the user can *read* the thing, then apply the patch to the thing, then validate/admit/authorize the patched thing, then write the patched thing.

**Comment by erictune** [comment]
@deads2k  in case he has seen this issue.

**Comment by erictune** [comment]
I was thinking that Authorization should be divided into two steps: authorization that does not depend on the actual values of the created request (which I call "object authorization) and authorization that depends on specific fields (which I call field authorization).  See #17549.

I also want to reclassify admission controllers.

- LimitRanger and most of ServiceAccount are classified as a "defaulters".  They can only modify an object.
- SecurityContextDeny and maybe a bit of ServiceAccount are classified as "field authorizers".  They can only say "yes" or "no" to letting the object proceed.  
- ResourceQuota is classified as an "accounter".  It runs after the decision has been made to create the object.
- not sure what NamespaceLifecycle is, need to look at it.

So, as I imagine it, then the sequence is this for an update will be:

1. authenticate user
1. authorize user to update objects of this kind (this is `authorize.Authorize(...)` )
1. build candidate object.
1. run all "defaulters" 
1. run all "field-authorizers" to check that the object is allowed , now that all modifications have happened.
1. run all "accounters", now that we are sure we want to create the object.

**Comment by erictune** [comment]
The scheme I described above should fix this bug, and does not require multiple trips.

I think we may eventually need multiple trips through "field authorizers" step, but for another reason that is not relevant right now.

**Comment by deads2k** [comment]
I think `LimitRanger` is more like "field authorizer" since it rejects pods that don't have acceptable limits set.  Field authorizers could be re-run after a PATCH operation.  We could also fix up the `LimitRanger` to properly handle PATCH.

@derekwaynecarr `LimitRanger` on PATCH should allow for unspecified limits.

**Comment by derekwaynecarr** [comment]
I am still catching up on the scenario, but I think we may be able to not run ```LimitRanger``` on ```UPDATE``` calls since we only allow changing the pod container image right now in updates.  If ```LimitRanger``` is just looking at the container resource requirements then we know they cannot be changed in an UPDATE (right now).

I will self-assign this and look to tackle.

**Comment by derekwaynecarr** [comment]
Just noting my agreement that `LimitRanger` is both a "field authorizer" and a "defaulter" in my view, and if anything I would like to reduce its role as a "defaulter" moving forward since it's dual role can make setting up the ability to edit a `LimitRanger` a little awkward in OpenShift.

see: https://github.com/kubernetes/kubernetes/issues/17097#issuecomment-162038232

As for classifying, `NamespaceLifecycle`, I think it's primarily a "field-authorizer" but I would more generally think we should relabel that as a "constraint-enforcer" since it basically enforces that on create, the namespace exists for the created object, and on delete of a namespace, that no new namespaced objects can be added.

Agree with @erictune that we have reached enough usage around admission control to understand more use-case specific patterns that it may help us to get a little more opinionated on where/when we invoke things.

That said, for this bug, I think we can just have `ResourceQuota` and `LimitRanger` ignore pod updates.  Hope to get a PR today.

**Comment by erictune** [comment]
I forgot LimitRanger rejected pods without the value set.
Agree it does both currently.
I think if I were refactoring admission control, I would split it into two separate modules with field auth and defaulting responsbilities.

How can ResourceQuota ignore updates to Pod resource requirements?

**Comment by derekwaynecarr** [comment]
@erictune - it cannot ignore them, but right now we don't support updating resource requirements on a pod.  see: https://github.com/kubernetes/kubernetes/blob/master/pkg/api/validation/validation.go#L1199

**Comment by erictune** [comment]
Okay, SGTM.

**Comment by derekwaynecarr** [comment]
This was indirectly fixed with the change made in https://github.com/kubernetes/kubernetes/pull/19481
