### ISSUE TITLE
Are there recommended or tried and tested options for syncing static content to Nginx within Kubernetes?

### ISSUE THREAD

**Issue by alexec** [kubernetes/kubernetes#18286]
I'm currently building a Kubernetes cluster. I plan on using Nginx containers to server static content, and to act as a web socket proxy. If you restart Nginx, you looks your web socket connection, so I do not want to restart the containers. But I will want to update the content within the container.

I would not expect Nginx to write to the static content. I would therefore expect to have a single writer, many readers.

The amount of static content will be tens of gigabytes (thought some may become unneeded after some time). I would expect to need to be able the updated multiple times a day. 

Therefore, I plan to mount a volume on the container. I see the following options:

1. RSync the static content to each and every node that might run Nginx. Only run Nginx on known nodes. 
2. Mount a read-only NFS share, and the use cachefilesd to reduce latency (this is not resilient, as it fails when the NFS share goes down).
3. As (2), but use GlusterFS for resilience. The Gluster servers could be the minions.
4. Deploy secondary Nginx containers containing static content. Add proxy passes to them with proxy cache. This run unnecessary containers, and feels like a work-around.

**Comment by mikedanese** [comment]
https://github.com/kubernetes/kubernetes/blob/22e527fe2577e2ee29d557681ee388b2d10b91a6/docs/user-guide/volumes.md#gitrepo

or you can use a sidecar container that shares a volume with nginx and syncs a git repo to that volume.

**Comment by mikedanese** [comment]
Please re-post your question to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes). 

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases. 

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to similar questions, and also familiarize yourself with:
   * [the user guide](http://kubernetes.io/v1.0/)
   * [the troubleshooting guide](http://kubernetes.io/v1.0/docs/troubleshooting.html)

Again, thanks for using Kubernetes.

The Kubernetes Team
