### ISSUE TITLE
"kubectl delete namespace --all" always exits with failure

### ISSUE THREAD

**Issue by xrow** [kubernetes/kubernetes#18282]
Hi,

I noticed a little oddity. When I run "kubectl delete namespace --all" the command always exists with error since it can`t delete default. I think it would be helpfull if the command would exit with 0 (success) in that case. Having a command always failing makes no sense to me.

```
[centos@admin01 ~]$ kubectl delete namespace --all
namespaces/dev
namespaces/intg
namespaces/kube-system
namespaces/local
namespaces/prod
namespaces/stage
namespaces/test
Error from server: Namespace "default" is forbidden: namespace can never be deleted
```

```
[centos@admin01 ~]$ kubectl version
Client Version: version.Info{Major:"1", Minor:"0.3", GitVersion:"v1.0.3.34+b9a88a7d0e357b", GitCommit:"b9a88a7d0e357be2174011dd2b127038c6ea8929", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"0.3", GitVersion:"v1.0.3.34+b9a88a7d0e357b", GitCommit:"b9a88a7d0e357be2174011dd2b127038c6ea8929", GitTreeState:"clean"}
```

**Comment by bgrant0607** [comment]
cc @derekwaynecarr

**Comment by bgrant0607** [comment]
I agree it shouldn't expect to delete "protected" namespaces. I don't think it should touch kube-system or openshift-infra, either, for example. We may need a way to mark such namespaces in the API.

**Comment by liggitt** [comment]
A "write protect" annotation as proposed in https://github.com/kubernetes/kubernetes/pull/17740 that was honored as a (user overrideable, client side) hint would be a lightweight way to prevent fat fingers

**Comment by xrow** [comment]
This sounds like an reasonable proposal.

**Comment by derekwaynecarr** [comment]
@liggitt - I like the approach of an annotation.

**Comment by AdoHe** [comment]
@liggit @derekwaynecarr any updates on this?

**Comment by bgrant0607** [comment]
Same issues also apply to `kubectl delete --all-namespaces=true`

**Comment by spzala** [comment]
Hi all, this issue is over a year old, wondering if we have any update on it, as trying to help close issues that are open for long time? I could recreate the issue, i.e. "kubectl delete namespace x" deletes x where as, "kubectl delete namespace --all" works fine by deleting namespaces except 'default' and 'kube-system' which supposed not to be removed,
Error from server (Forbidden): namespaces "default" is forbidden: this namespace may not be deleted.
Error from server (Forbidden): namespaces "kube-system" is forbidden: this namespace may not be deleted.

Should we close this issue as "working as designed"? I noticed that a related proposed PR #17740 is expired. Thanks!

**Comment by liggitt** [comment]
Yes, it is working as designed.

**Comment by spzala** [comment]
Thanks @liggitt

**Comment by xrow** [comment]
Sorry I didn`t come back to you in time. My desire was that it would exit with 0 (success), if it was designed to skip those. It doesn`t exit with 0. That is bad for ansible automation.
