### ISSUE TITLE
Update saltstack version?

### ISSUE THREAD

**Issue by pikeas** [kubernetes/kubernetes#18326]
Ref: https://github.com/kubernetes/kubernetes/blob/master/cluster/aws/templates/common.sh#L59

`kube-up` installs salt 2014.1.13, and does so from a Google-hosted .deb file.

Is there a reason salt hasn't been updated to a more recent version, e.g. 2015.8.3?
Is there a reason salt is installed manually instead of via the official repo at http://repo.saltstack.com/ ?

If there are reasons for one or both of these, this is a request for documentation.
If there's no reason, this a request to use the salt repo and latest version.

**Comment by roberthbailey** [comment]
> Is there a reason salt hasn't been updated to a more recent version, e.g. 2015.8.3?

On GCE, we are really just using salt as a jinja templating engine (AWS is still using the older master/slave configuration, but @mikedanese is hoping to migrate them to the stand-alone mode soon). We've worked around quite a few bugs in the 2014.1.13 version and there is a significant cost to migrating to newer versions.

> Is there a reason salt is installed manually instead of via the official repo at http://repo.saltstack.com/ ?

We found that installing from a .deb file was more reliable (on GCE). There isn't any reason we couldn't pull from saltstack.com on other platforms if folks wanted to.

**Comment by pikeas** [comment]
Hm...it's not clear in docs that the GCE stand-alone setup is the newer setup. In fact, my impression was the opposite - that the AWS master/slave config is preferred and standalone was a workaround for limitations in GCE.

Is there documentation on why only GCE was made standalone, and is there a tracking issue for updating AWS to a similar configuration?

For bonus points, is there a tracking issue for cluster differences between GCE and AWS? Between this and the docker version mismatch (1.8.3 GCE, 1.7.1 AWS), it's starting to feel like the AWS cluster turn-up story is lagging behind. Thoughts, @justinsb ?

**Comment by roberthbailey** [comment]
GCE originally used the master/slave configuration and it migrated to the standalone mode sometime last spring (thanks to @zmerlynn; see #5112) to help secure the master<->node communication (securing the salt connections is possible but much more difficult). 

Also see https://github.com/kubernetes/kubernetes/issues/14238 and https://github.com/kubernetes/kubernetes/issues/6413 for other AWS-specific salt issues that haven't affected GCE. 

Finally, @brendandburns opened https://github.com/kubernetes/kubernetes/issues/18201 recently which was caused by our very old version of salt.

**Comment by roberthbailey** [comment]
> is there a tracking issue for cluster differences between GCE and AWS?

Not that I know of. 

> Regarding salt 2014.1.13 vs 2015.8.3, are newer versions of salt known to be incompatible with the existing cluster turn-up scripts?

Last fall (when we weren't pinned to a specific salt release), cluster creation broke for a number of hours when our install started automatically using a newer salt release. @jbeda filed https://github.com/kubernetes/kubernetes/issues/3979 once we had pinned to this specific release and we haven't found the time to move since then, mainly because we keep thinking we are getting close to be able to remove salt altogether. And we are working on simplifying cluster deployment (see https://github.com/kubernetes/kubernetes/pull/18287) which should help us get closer to this goal.

**Comment by mikedanese** [comment]
I think it would be valuable to update AWS to masterless salt for parity with GCE and vagrant. I don't think we want to spend the effort to upgrade salt version right now and I don't think we would accept the change, as it would require significant effort to validate.

**Comment by zmerlynn** [comment]
FWIW, I think it would be valuable to update SaltStack at some point, but haven't been convinced (except for better `systemd` support, it seems) that it would be better). It's just a large task, as alluded to earlier, and getting smaller as we gradually trim Salt usage down to just a templating engine.
