### ISSUE TITLE
GCE cloud provider (and others) should use the "description" (or similar) fields

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#18396]
When we create GCE load-balancers we have to use an opaque name to fit.  We should populate the description field with enough information to help humans figure out what it is for and to be machine usable.

Maybe a JSON-formatted set of Key-Value pairs or something, including the k8s cluster name, namespace, and service name (at minimum)

@arob for any clues on why we don't do this

**Comment by thockin** [comment]
I think we did some but not all of this

@jingxu97

**Comment by a-robinson** [comment]
Sorry I never responded, I wish I had a way of getting notifications for @ mentions of arob.

There's no reason we shouldn't be doing this for all resources that support it.

**Comment by a-robinson** [comment]
It'd be great to get cluster name into these descriptions as well

**Comment by jingxu97** [comment]
Currently, the following objects already have description.
Firewall, ForwardingRule, TargetPool, Router, Disk
The objects that are missing description include UrlMaps, TargetHttpProxy, GlobalForwardingRule. Already add code to add description for clustername, zone and project name. But the testing requires godep update. Will work on this step because of the priority.

**Comment by spiffxp** [comment]
/sig cluster-lifecycle
/area platform/gce
since we lack a sig-gcp at the moment

**Comment by thockin** [comment]
@nicksardo @bowei as you think about CloudProvider stuff.

/lifecycle frozen
/remove-lifecycle stale
