### ISSUE TITLE
Can't delete pods in pending state?

### ISSUE THREAD

**Issue by aaskey** [kubernetes/kubernetes#18408]
I was following the [getting started guides](http://kubernetes.io/v1.1/docs/getting-started-guides/vagrant.html) to start a Kubernetes cluster with one master and one minion using Vagrant. 

The example is to start 3 pods, but they all stuck in pending state (This is a different issue I am still debugging),
````
$ ./cluster/kubectl.sh run my-nginx --image=nginx --replicas=3 --port=80
NAME             READY     STATUS    RESTARTS   AGE
my-nginx-5ibi5   0/1       Pending   0          1h
my-nginx-vdtnu   0/1       Pending   0          1h
my-nginx-yy17t   0/1       Pending   0          1h
````
I tried to delete one of the pods, kubectl returned with pod deleted:
````
$ ./cluster/kubectl.sh delete pod my-nginx-yy17t
pod "my-nginx-yy17t" deleted
````
However, a new pod was immediately scheduled and stayed in pending state:
````
$ ./cluster/kubectl.sh get pods
NAME             READY     STATUS        RESTARTS   AGE
my-nginx-5ibi5   0/1       Pending       0          1h
my-nginx-r8ze0   0/1       Pending       0          2s
my-nginx-vdtnu   0/1       Pending       0          1h
my-nginx-yy17t   0/1       Terminating   0          1h
````
Trying to delete all of the pods:
````
$ ./cluster/kubectl.sh delete pods --all
pod "my-nginx-5ibi5" deleted
pod "my-nginx-r8ze0" deleted
pod "my-nginx-vdtnu" deleted
pod "my-nginx-yy17t" deleted
````
Another 3 pods were scheduled, now there are 4 pods in pending and 3 pods in terminating state:
````
NAME             READY     STATUS        RESTARTS   AGE
my-nginx-5ibi5   0/1       Terminating   0          1h
my-nginx-fvoz8   0/1       Pending       0          20m
my-nginx-ikkot   0/1       Pending       0          20m
my-nginx-pi6a7   0/1       Pending       0          20m
my-nginx-r8ze0   0/1       Terminating   0          23m
my-nginx-vdtnu   0/1       Terminating   0          1h
my-nginx-yy17t   0/1       Terminating   0          1h
````

Is this expected? What would be the best to delete pods in pending state?

**Comment by dalanlan** [comment]
`$ ./cluster/kubectl.sh run my-nginx --image=nginx --replicas=3 --port=80`
With this command you are supposed to have 3 replicas all the time.

**Comment by mikedanese** [comment]
Run creates a replication controller that maintains 3 replicas. If you delete 3 pods it creates 3 more. Try `kubectl delete rc my-nginx` to delete the replication controller.

**Comment by saad-ali** [comment]
In the future, please post support questions to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes). 

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases. 

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to similar questions, and also familiarize yourself with:
   * [the user guide](http://kubernetes.io/v1.0/)
   * [the troubleshooting guide](http://kubernetes.io/v1.0/docs/troubleshooting.html)

Again, thanks for using Kubernetes.

The Kubernetes Team
