### ISSUE TITLE
scheduler: Relaxed randomization

### ISSUE THREAD

**Issue by xiang90** [kubernetes/kubernetes#18414]
From borg paper:

```
It is wasteful to calculate feasibility
and scores for all the machines in a large cell, so the
scheduler examines machines in a random order until it has
found “enough” feasible machines to score, and then selects
the best within that set. This reduces the amount of scoring
and cache invalidations needed when tasks enter and leave
the system, and speeds up assignment of tasks to machines.
```

This seems to be easy enough to implement for generic scheduler without a lot of complexity. But we need a way to define `enough`. Probably configurable percentage of all nodes for generic scheduler?

There is a small issue with current implementation for adding this too.

Scheduler have additional extenders that will try to filter out feasible nodes again. And it is done in a batch (The current extender is a HTTP implementation. Probably we want to reduce latency.) 

https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/scheduler/generic_scheduler.go#L145

So if we send the "enough" nodes to extenders in a batch, we might end up with no feasible nodes. But in reality, there are feasible nodes that outside the "enough" set. This might affect scheduling correctness. Do we want to ensure "correctness" at scheduler level? 

Any idea?

/cc @hongchaodeng @davidopp @HaiyangDING

**Comment by davidopp** [comment]
This is a good point. We anticipated this issue when we discussed the extender proposal with the folks who requested it, and our intention is that the scheduler optimizations that are incompatible with extender will be "turned off" when you use extender. The exact mechanism to do this is TBD, but part of the contract when you use the extender is you will not get all of the performance/scalability optimizations of the core scheduler. Relaxed randomization is a good example of one we wouldn't offer when you use extener. We communicated this clearly to the folks who wanted extender and they understand the limitation.

As for your other question, I don't remember what threshold we use in Borg. Probably we would want this to be admin-configurable anyway, since it represents a tradeoff between scheduling speed and scheduling quality.

**Comment by xiang90** [comment]
@davidopp Ack. I will try to get a initial implementation soon.

**Comment by HaiyangDING** [comment]
+1 to this optimization.

Maybe at some point we should update the current scheduler doc to state how to use the scheduler extender have and what the pay-off is. Or do we have this already?

**Comment by HaiyangDING** [comment]
Just found the doc regarding extender at https://github.com/kubernetes/kubernetes/blob/master/docs/design/scheduler_extender.md. Sorry.

Then when this is implemented, we should clarify the trade-off of using extender.

**Comment by timothysc** [comment]
@hongchaodeng can we close this one?

**Comment by hongchaodeng** [comment]
I can't close this.
@xiang90
