### ISSUE TITLE
REST api - why Node isn't required to have Status?

### ISSUE THREAD

**Issue by zakiva** [kubernetes/kubernetes#18428]
Node has Status as omitempty:
``Status NodeStatus `json:"status,omitempty"``
from: https://github.com/kubernetes/kubernetes/blob/master/pkg/api/v1/types.go#L1955

NodeStatus has important fields such as NodeInfo to uniquely identify the node. This information seems to be required and not optional. Is it possible for ``Status`` to be empty and thus trigger the omitempty option, and if yes in what case?

**Comment by nikhiljindal** [comment]
Generally speaking, all resources (not just Node) have status as omitempty.
For ex: while creating a resource, user only needs to specify the Spec and can leave status empty. https://github.com/kubernetes/kubernetes/blob/master/docs/devel/api-conventions.md#spec-and-status has some more details.

**Comment by moolitayer** [comment]
> Generally speaking, all resources (not just Node) have status as omitempty.
> For ex: while creating a resource, user only needs to specify the Spec and can leave status empty. https://github.com/kubernetes/kubernetes/blob/master/docs/devel/api-conventions.md#spec-and-status has some more details.

@nikhiljindal though it is not explicit in the documentation, it looks like we can assume that GET operation will always return with a non empty status. is that correct?

**Comment by bgrant0607** [comment]
I believe that an empty status section is added when the Node object is created. The other information is filled in asynchronously. In the case that Kubelet self-registers, much of the information may be there, but there are so many cluster configurations that I hesitate to claim that will always be the case.

Anyway, what Nikhil wrote is correct. Since we use the same schema for all operations, we currently have to indicate that status is optional.
