### ISSUE TITLE
GKE e2e test failure due to running out of disk space

### ISSUE THREAD

**Issue by roberthbailey** [kubernetes/kubernetes#18443]
Kubectl client Proxy server should support --unix-socket=/path [Conformance]

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:920 Dec 9 05:53:52.366: Failed to create temporary directory: mkdir /tmp/kubectl-proxy-unix440131382: no space left on device
```

/cc @dchen1107 @zmerlynn

**Comment by dchen1107** [comment]
cc/ @ixdy

**Comment by ixdy** [comment]
Disk looks OK again... long-term we should probably point tests on Jenkins to use a tmpdir other than `/tmp`, which is pretty space-limited.

**Comment by mml** [comment]
I think this happened again.

https://console.cloud.google.com/storage/browser/kubernetes-jenkins/logs/kubernetes-e2e-gce/14669
https://console.cloud.google.com/storage/browser/kubernetes-jenkins/logs/kubernetes-e2e-gce/14667

Since then there's been a string of failures to start.
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce/

**Comment by mml** [comment]
cc @ArtfulCoder (build cop)

**Comment by kargakis** [comment]
@kubernetes/sig-testing-misc

**Comment by roberthbailey** [comment]
If there have been no updates on this issue for over a year it should be closed as we focus on the current test failures & flakes.
