### ISSUE TITLE
Kubernetes Pods error: 'address already in use'

### ISSUE THREAD

**Issue by batazor** [kubernetes/kubernetes#18495]
What to do when kube-scheduler tries to use the port is already occupied?

`./kubectl logs --namespace=kube-system kube-scheduler-192.168.0.139`

`listen tcp 127.0.0.1:10251: bind: address already in use`

How can I fix it?

**Comment by davidopp** [comment]
Please re-post your question to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes). 

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases. 

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to similar questions, and also familiarize yourself with:
  * [the user guide](http://kubernetes.io/v1.0/)
  * [the troubleshooting guide](http://kubernetes.io/v1.0/docs/troubleshooting.html)

Again, thanks for using Kubernetes.

The Kubernetes Team

**Comment by VonC** [comment]
@davidopp This GitHub issue comes from the Stack Overflow question also posted 3 days ago: http://stackoverflow.com/q/34195766/6309
