### ISSUE TITLE
kube-addons.service failed on CoreOS-libvirt installation

### ISSUE THREAD

**Issue by idvoretskyi** [kubernetes/kubernetes#18517]
Hello everyone.

I have the following issue installing and provisioning my Kubernetes CoreOS-libvirt-based cluster.

When I'm logging on the *master* node, I see the following:

```
ssh core@192.168.10.1
Last login: Thu Dec 10 17:19:21 2015 from 192.168.10.254
CoreOS alpha (884.0.0)
Update Strategy: No Reboots
Failed Units: 1
  kube-addons.service
```

Trying to debug it, I run and receive the following:

```
core@kubernetes-master ~ $ systemctl status kube-addons.service
● kube-addons.service - Kubernetes addons
   Loaded: loaded (/etc/systemd/system/kube-addons.service; disabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Thu 2015-12-10 16:41:06 UTC; 41min ago
     Docs: https://github.com/GoogleCloudPlatform/kubernetes
  Process: 801 ExecStart=/opt/kubernetes/bin/kubectl create -f /opt/kubernetes/addons (code=exited, status=1/FAILURE)
  Process: 797 ExecStartPre=/bin/sleep 10 (code=exited, status=0/SUCCESS)
  Process: 748 ExecStartPre=/bin/bash -c while [[ "$(curl -s http://127.0.0.1:8080/healthz)" != "ok" ]]; do sleep 1; done (code=exited, status=0/SUCCESS)
 Main PID: 801 (code=exited, status=1/FAILURE)

Dec 10 16:40:53 kubernetes-master systemd[1]: Starting Kubernetes addons...
Dec 10 16:41:06 kubernetes-master kubectl[801]: replicationcontroller "skydns" created
Dec 10 16:41:06 kubernetes-master kubectl[801]: error validating "/opt/kubernetes/addons/skydns-svc.yaml": error validating data: found invalid field portalIP for v1.ServiceSpec; if you choose to ignore these errors, turn validation off with --validate=false
Dec 10 16:41:06 kubernetes-master systemd[1]: kube-addons.service: Main process exited, code=exited, status=1/FAILURE
Dec 10 16:41:06 kubernetes-master systemd[1]: Failed to start Kubernetes addons.
Dec 10 16:41:06 kubernetes-master systemd[1]: kube-addons.service: Unit entered failed state.
Dec 10 16:41:06 kubernetes-master systemd[1]: kube-addons.service: Failed with result 'exit-code'.
```

My `etcd` version is:
```
etcd --version
etcd version 0.4.9
```

But I have a `etcd2` also:
```
etcd2 --version
etcd Version: 2.2.2
Git SHA: b4bddf6 
Go Version: go1.4.3
Go OS/Arch: linux/amd64
```

And at the current moment the second one is being runned:
```
ps aux | grep etcd 
etcd       731  0.5  8.4 329788 42436 ?        Ssl  16:40   0:16 /usr/bin/etcd2
root       874  0.4  7.4  59876 37804 ?        Ssl  17:19   0:02 /opt/kubernetes/bin/kube-apiserver --address=0.0.0.0 --port=8080 --etcd-servers=http://127.0.0.1:2379 --kubelet-port=10250 --service-cluster-ip-range=10.11.0.0/16
core       953  0.0  0.1   6740   876 pts/0    S+   17:27   0:00 grep --colour=auto etcd
```

What causes the issue and how can I solve it?

Thank you.

**Comment by jlowdermilk** [comment]
Please re-post your question to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes). 

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases. 

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to similar questions, and also familiarize yourself with:
   * [the user guide](http://kubernetes.io/v1.0/)
   * [the troubleshooting guide](http://kubernetes.io/v1.0/docs/troubleshooting.html)

Again, thanks for using Kubernetes.

**Comment by idvoretskyi** [comment]
I will follow your recommendation.

Thank you.

**Comment by idvoretskyi** [comment]
I will follow your recommendation.

Thank you.
