### ISSUE TITLE
Cluster Autoscaling e2e tests are not compatible multiple MIGs

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#18566]
We're going to need multiple MIGs to create clusters bigger than 500 Nodes, so we need to figure out how to make cluster autoscaling to work. See #18545

cc @kubernetes/goog-control-plane @brendandburns @wojtek-t @fgrzadkowski @mwielgus

**Comment by piosz** [comment]
Is this fixed now?

**Comment by gmarek** [comment]
Not that I know of. Let's discuss it on Monday.

**Comment by davidopp** [comment]
This seems kinda bad but I'm not sure I'd block the release on it. Can we just document that a current limitation of cluster autoscaling is that it only works up to 500 nodes?

cc/ @roberthbailey @alex-mohr

**Comment by davidopp** [comment]
(That said, if we can fix it in the next few days, that would obviously be even better.)

**Comment by fgrzadkowski** [comment]
Autoscaling for multiple MIGs should work in a similar way as for a single MIG. Each will grow separately, but that's fine. The difference is that we will be rounding number of machines separately for each MIG, so it possible that will have slightly higher number of machines, e.g.:
* MIG_1 should have 50.3 nodes so we give 51 nodes
* MIG_2 should have 49.2 so we give it 50 nodes
Altogether we have 101 nodes, wheres with 1 MIG we'd have 100 nodes. Other than that cluster autoscaling will work OK.

I talked with @gmarek and when he was filing this issue he meant that cluster autoscaling e2e tests are failing for multiple MIGs, which is possible as they were written with the assumption that we have only one GCE autoscaler object.

@davidopp This is definitely not a blocker for anything and I believe we don't have to update documentation.

<changing the title to better explain what this issue is about>

**Comment by gmarek** [comment]
cc @mwielgus

**Comment by piosz** [comment]
This is obsolete.
