### ISSUE TITLE
PVClaimSpec Resources should not use teh same struct as Container Resources

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#18587]
Currently they both use `ResourceRequirements` which has `requests` and `limits` fields, but I think `limit` doesn't apply to PVClaim (or maybe it's vice-versa, but it's not a tiered request).  We should make different structs for those two cases.  Now we have an API compat issue.  Need to trawl docs to see if we were ever clear about which to use for PV.

We should change this before auto-privisioning goes too far, and people start using this more.

@markturansky @pmorie

**Comment by thockin** [comment]
@vishh

**Comment by vishh** [comment]
I feel `Limit` applies to PVClaim and `Request` does not. If we had a means to restrict usage on a PV, for example linux quota, we can enforce `Limits` on PVClaims at the node.

**Comment by markturansky** [comment]
I think we used `Request` at the time because `Limit` is the reverse of what a PVC needs.  PVC wants a `Minimum`, whereas other usages of `Limit` were maximums, I believe.

**Comment by vishh** [comment]
`Requests` imply Burstable behavior. Is such a semantic required for PVC?

**Comment by markturansky** [comment]
It didn't imply that at the time.  I was the one to add `Requests` (at behest of @bgrant0607, I think), because a PVC is a request for resources with specific minimums required.  I originally used `Limit` but in reverse (not a max, but a min), hence we got `Requests`.

I'm not married to it or arguing for/against.  Just trying to provide historical context.

**Comment by thockin** [comment]
I don't think either name is better than the other, we should use whatever
has been documented.  In fact, it may be too late to change it at all, and
we should maybe just fork the struct, deprecate one field and accept either.

**Comment by bgrant0607** [comment]
PVs aren't shared, so Guaranteed/Burstable/BestEffort doesn't make sense in this context.

However, as for pods, binding is based on Request, not Limit. Request is a better term, because it is an expression of how much is needed. 

Limit implies a max -- no more than. Limit happens to not be enforced AFAIK, and I'd be fine with removing it from PVC. We can add it back if we decide it's needed in the future.
