### ISSUE TITLE
How to execute command in a pod from API (websocket)?

### ISSUE THREAD

**Issue by spinus** [kubernetes/kubernetes#18632]
Hi, I'm trying to do exec on a pod. It looks like the docs are not very consistent about that yet, but with docs and few trials and errors I found that something like that almost work:

```
curl 'https://admin:xxx@IP/api/v1/namespaces/default/pods/hello-whue1/exec?stdout=1&stderr=1&command=ls' -H "Connection: upgrade" -k -X POST -H 'Upgrade: websocket'
```
repsponse for that is
```
unable to upgrade: missing upgrade headers in request: http.Header{"User-Agent":[]string{"curl/7.44.0"}, "Content-Length":[]string{"0"}, "Accept":[]string{"*/*"}, "Authorization":[]string{"Basic xxx=="}, "Connection":[]string{"upgrade"}, "Upgrade":[]string{"websocket"}}
```
Looks like that should be enough to upgrade post request and start using websocket streams, right? What I'm missing?

It is possible to do that only with websocket connection without upgrade? A lot of client libraries support websockets or http request but mixing is kind of limited.

**Comment by saad-ali** [comment]
Please re-post your question to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes). 

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases. 

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to similar questions, and also familiarize yourself with:
   * [the user guide](http://kubernetes.io/v1.0/)
   * [the troubleshooting guide](http://kubernetes.io/v1.0/docs/troubleshooting.html)

Again, thanks for using Kubernetes.

The Kubernetes Team

**Comment by spinus** [comment]
@saad-ali Hi, sure I'll repost the question.

 I think I followed the docs and couldn't make it working and I think:
1) I'm missing something (probably good reason to go to stackoverflow)
2) implementation is bad
3) documentation is bad
2 and 3 are reasons why I put the question here and not on stackoverflow in the first place. Maybe it's wrong that I used that "question" but I was not sure what's wrong.

**Comment by dotw** [comment]
I have the same question? any update till now?

**Comment by grubbywww** [comment]
I have the same question? any update till now?

**Comment by grubbywww** [comment]
web kubnetes terminal

**Comment by dbolkensteyn** [comment]
FYI here is the link to the StackOverflow question the OP created: https://stackoverflow.com/questions/34373472/how-to-execute-command-in-a-pod-kubernetes-using-api
