### ISSUE TITLE
Proposal to create a generic interface from kubelet to cadvisor

### ISSUE THREAD

**Issue by huang195** [kubernetes/kubernetes#18769]
# Proposal to create a generic interface from kubelet to cadvisor
## 1. Background

cadvisor was integrated with kubernetes in issue #4798, which made 
the deployment of kubernetes simpler and out-of-box UX smoother for new
users. However, at the same time, it created a tight coupling between
kubelet and cadvisor. We'd like create a generic interface so that other
container health checking tools can be used with kubernetes.
## 2. Motivation

It is great that there's a built-in cadvisor when a new user starts to 
play around with kubernetes. For most users, continuing to use this
cadvisor, and then configure heapster, influxdb, and grafana is the natural
way to go. However, for other users, they might prefer to use other open
source tools for collecting this information or create their own custom tools. 
As there is no way to disable cadvisor, one way is to run both cadvisor
and their custom tools at the same time, which is inefficient and wasteful.

Other use cases to further motivate this proposal are:
- a) Deploying kubernetes in a public cloud, and the cloud provider already provides
  similar health checking tools.
- b) Deploying kubernetes on top of mesos, where there could be multiple frameworks
  deployed on the same mesos node. If each framework is using its own health checking
  tool, they would perform duplicate works.
- c) The kubenetes-bundled cadvisor sometimes have performance issues where it is 
  consuming a much larger amount of resources than expected (see issues #10451, #16296). 
  In a production environment, one might want to run a stable version of cadvisor, 
  and have Kubernetes simply connecting to it instead of using the newer built-in one.
## 3. Planned work

We're planning to create a generic interface and a set of Kubernetes-based (instead of 
cadvisor-based) health checking data structs, so that it can interface with different 
health checking backends, including cadvisor. Integrating kubernetes with a new health
checking tool would involve writing a new driver that implements that generic interface.
### 3a. Phased approach

We'd like to phase this work to smaller steps. Initially, we are planning to create this
generic interface almost identical to what is defined in pkg/kubelet/cadvisor/types.go, and
the corresponding data structs directly from cadvisor. This allows us to put in the generic
health checking interface with minimal changes to the existing code.

In the 2nd phase, we would like to clean up the generic interface and the corresponding
data structs as not everything cadvisor collects are used by kubelet. Basically, we will make
the interface and data structs more generic so that new health check drivers can be more 
easily written.

In the 3rd phase, we will add one or two additional cmd flags to allow alternative health 
checking driver to be used when starting kubernetes. Of course, the default setting will be
to use the built-in cadvisor.

**Comment by huang195** [comment]
cc @vishh @yujuhong @dchen1107 @thockin

**Comment by yujuhong** [comment]
@huang195, first of all, I like a cleaner, more well-defined interface. That's always welcome.

I'd like to know what your use case is because we want to keep cadvisor for collecting the core metrics essential to kubernetes (e.g., scheduling). Users can use other monitoring tools/pipeline for the advanced/custom metrics. More details are in #18770. Given that, do you still want to swap out cadvisor for the basic monitoring or will your use case fall into the "other metrics" part?

**Comment by huang195** [comment]
@yujuhong I like the proposal in #18770, and I think it is orthogonal to this one. Perhaps the generic interface I'm proposing should be broken down to 2 parts: core and advanced, where each is pluggable. This gives a lot of flexibility, e.g., use cadvisor for core, and mock for advanced (e.g., this would make our debugging in #16296 much simpler without any code changes); or a custom tool for core, and cadvisor for advanced. Hope this answers your question.

**Comment by ncdc** [comment]
cc @kubernetes/rh-cluster-infra

**Comment by timstclair** [comment]
I'm assuming by "advanced" you mean the extra metrics which are non-essential to k8s functionality, and are just provided for monitoring & introspection (as described in https://github.com/kubernetes/kubernetes/issues/18770). If that's the case, you shouldn't need to mock the advanced part, since there shouldn't be any dependencies on it. We'd like to have it running in a separate pod which can simply be removed if the functionality is not desired. For the core case I agree with the desire to have a simple interface and the ability to mock it for testing purposes. The interface for the core case should be very minimal, as it will only provide a few stats. We are also likely to do extra optimization of the core functionality as it will have a more direct impact on kubelet performance.

**Comment by huang195** [comment]
@timstclair Thanks for the clarification. It's what I meant by "advanced". It seems a generic interface for the "basic" metrics collector is desired, so that we can plug different tools, including cadvisor, mock, and other collectors. Further optimizations can be done at individual driver level behind this generic interface.

Just to be more concrete, "basic" metrics include NumCores, MemoryCapacity, MachineID, SystemUUID, BootID, KernelVersion, ContainerOSVersion, etc. that are collected in pkg/kubelet/kubelet.go, cadvisor.DockerImageFSInfo() used by image manager, cadvisor.RootFSInfo() used by disk manager, and cadvisor.watchEvents() used by OOM watcher, which are relatively cheap to collect. And "advanced" metrics are what will be served out of pkg/kubelet/server.go:serveStats(). 

After #18770 is merged, we can expect kubelet to no longer need to support serveStats() as the information should be pulled from this dedicated pod that runs cadvisor or whatever other monitor tool of choice. If this is the correct understanding, I can just focus on the generic interface for the "basic" metrics collector, which makes my job a bit cleaner.

**Comment by yujuhong** [comment]
AFAIK, the basic per-container cpu&memory (or even disk) usage stats will still be considered as "core/basic" to kubelet, and the built-in cadvisor will continue serving them. I wouldn't mind if we split the cadvisor interface into machine information, container stats, etc. 

I agree that a cleaner interface would help code readability and mocking. On the other hand, since we are going to use only the minimal functionality of cadvisor, I think users would have less incentive to plug their own cadvisor tool for this purpose. I imagine that they'd care more about the "advanced" features. @huang195, do you have other specific use cases other than testing/debugging?

**Comment by huang195** [comment]
@yujuhong yes, we're planning to use our custom monitoring tool to collect both the basic and advanced metrics information in a kubernetes-on-mesos environment, where there could be multiple frameworks running at the same time. The custom monitoring tool would allow us to pay for monitoring cost once, not per framework.

**Comment by huang195** [comment]
One other point is that conceptually when we separate the basic vs. advanced metrics collection interfaces, we could potentially use 2 different tools to collect these information, e.g., use cadvisor to collect basic information and a custom tool for collecting the advanced stuff. But from deployment and operational point of view, it would be much easier to deploy/use 1 tool for collecting both type of information. And when there's a problem with metrics collection, we have only 1 tool to chase down instead of 2. If the basic information must be collected by cadvisor, for any user who wants to use other tools to collect advanced metrics information, they would be forced to run 2 separate tools with potential overlap of information they're collecting.

**Comment by dchen1107** [comment]
please see #18770

**Comment by dchen1107** [comment]
@huang195 From the high-level, we are convergent. We want to refactory cAdvisor so that Kubelet can only collect those core metrics used by our core control loops through cAdvisor library. The metrics (including custom metrics) are used for monitoring and other non-core control loops can be collected through a different pipeline, including a separate cAdvisor pod.

**Comment by huang195** [comment]
@dchen1107 I will take a look at the related issues you mentioned in #18770, and once I have more clarity on a generic interface of the core and non-core metrics, I will post it here to get more feedbacks before proceeding further. 

One clarification question: if we're going forward with collecting the non-core metrics using a separate cadvisor pod, how will the metrics information be exposed to collectors such as heapster? Will kubelet provide a directory service that helps heapster find where cadvisor pod can be accessed or will kubelet act as a middle-man (similar to the way the code works today) that gets metrics from cadvisor and servicing them out to heapster?

**Comment by vishh** [comment]
@huang195: Can we discuss the impact of #18870 in that issue itself?

**Comment by huang195** [comment]
Sure, @vishh. Let me post my question there
