### ISSUE TITLE
Shall we consider implement an "annotation selector" in Kuberentes?

### ISSUE THREAD

**Issue by HaiyangDING** [kubernetes/kubernetes#18801]
Currently, we have had a decent mechanism for label querying. However, querying annotations is not well supported yet. I noticed this when implementing the multi-scheduler feature in which I found the scheduler cannot "watch&list" pods in the api-server with specific annotations. Having an "annotation selector" would help scheduler watch the pods it actually cares (although we could also choose not to use annotation to implement the feature, but let's just focus on annotation selector for now). I can also imagine some other features/component may benefit from "annotation selector", e.g. #18261 and #18265 have considered to make further use of annotations, @jdef has also mentioned in https://github.com/kubernetes/kubernetes/pull/17865#issuecomment-164259527 that mesos scheduler may also benefit from this. 

If we want to do this, we can either:
1. extend the current fieldSelector to better support annotation selection
2. implement an annotation selector as a new selector like labelSelector or fieldSelector

What is your thought about this annotation selector, folks?

@feihujiang @davidopp @lavalamp

**Comment by feihujiang** [comment]
Yes, I'm working on this now, any feedback is welcome. :)

**Comment by lavalamp** [comment]
@bgrant0607 

I think the primary difference between labels and annotations is that the latter are not queryable.

For your use of selecting schedulers, since the annotation is basically a way to experiment before adding a "real" field, I would simply extend the field selector mechanism, making it pretend that you have a field.

**Comment by bgrant0607** [comment]
We've wanted general field selection on GET/WATCH for a long time: #1362

There are a few other GET/WATCH cases we want to support, also: #4817

I could imagine supporting annotation selectors similarly, if field selection is too cumbersome.

Which queries we index for efficiency is another matter.

I wouldn't allow selection of annotations in most API resources, such as controllers or services selecting pods.

We might want selection on annotations and/or fields for node selectors, though. See #18261.

cc @davidopp

**Comment by bgrant0607** [comment]
BTW, the current implementation of field selectors should be considered a total hack and not something we should try to copy/extend.

**Comment by davidopp** [comment]
@bgrant0607 Where were we proposing to use annotations in #18261? Are you referring to the side-discussion with @ravigadde here? https://github.com/kubernetes/kubernetes/pull/18261#issuecomment-164307219

**Comment by bgrant0607** [comment]
@davidopp No, sorry, I was referring to https://github.com/kubernetes/kubernetes/issues/341#issuecomment-154663349, and our discussion prior to that.

**Comment by spzala** [comment]
@HaiyangDING  @feihujiang hi, is this still a valid issue? If not, can you please close it? A gentle touch base as it's more than a year this issue was last discussed. Thanks!

**Comment by HaiyangDING** [comment]
@spzala Thanks for mentioning. I am closing this.

**Comment by spzala** [comment]
@HaiyangDING no problem at all and thank you for quickly verifying and closing!

**Comment by quinn** [comment]
Hi, how do you do this? This closed PR from 2 years ago is the closest thing i found to any documentation on this topic.

**Comment by liggitt** [comment]
only labelSelectors are supported, not annotations

**Comment by lavalamp** [comment]
You cannot query annotations in Kubernetes, and this will not change in the foreseeable future.

* cache locally and keep a local index (our controllers do this)
* put things in labels (not preferred, as lists are expensive for apiserver)

**Comment by peter-dolkens** [comment]
@lavalamp is there any reasoning behind this?

Our use case was we wanted to hook into the commonly seen `prometheus.io/scrape: 'true'` annotation and leverage that in some CRDs, but the CRDs only implement the standard `matchLabels` and `matchExpression` selectors.

Without explanation, it seems like an arbitrary restriction which impacts real-world use-cases.

Appreciate this is a long abandoned issue, but would be nice to understand the reasoning.

**Comment by lavalamp** [comment]
@peter-dolkens 

* Annotations don't have the value restrictions that labels do, meaning there's no reason to suppose that our "query language" would be a good fit.
* It's O(N) for apiserver to do this search. It's only barely more expensive for clients to do it themselves.
* A general query system is often requested. The real blocker for both is the performance characteristic. If we figured out a solution to that, I would want a general query system and I'd never do an annotation-specific query system. (Because APIs are forever.)
* The specific thing you mention appears as if it might have been a better fit for a label.
* Note that you can request objects in the form of PartialObjectMetadata if you just want to scan the annotations -- slightly easier on your network than the full objects.

**Comment by mgajda** [comment]
Since API server will not index the objects, the suggested workaround is to use `jq`.

For example:

```
$ kubectl get pvc --all-namespaces -o json| jq --raw-output '.items[]|select(.metadata.annotations."meta.helm.sh/release-name"=="<your-release>")|"\(.kind) \(.metadata.name)"

Service postgresuser
Deployment postgrest
Deployment postgresuser
ReplicaSet postgrest-68f7cd84d8
ReplicaSet postgresuser-54b9c4d477
```
