### ISSUE TITLE
Dynamically provisioned volumes are bound after 10 minutes

### ISSUE THREAD

**Issue by jsafrane** [kubernetes/kubernetes#18830]
I'm testing dynamic provisioning on AWS. When I create a claim with `volume.alpha.kubernetes.io/storage-class` annotation, Kubernetes creates a PV, marks it as Bound, while the claim is still `Pending`. The claim gets `Bound` only after 10 minutes, i.e. on the next provisioner controller refresh.

When the provisioning is complete, the claim should be marked as Bound immediately, probably somewhere at this place: https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/persistentvolume/persistentvolume_provisioner_controller.go#L294

**Comment by jsafrane** [comment]
cc @markturansky @pmorie @kubernetes/rh-storage

**Comment by markturansky** [comment]
This occurs because the claim will not be Bound until the volume is fully provisioned.  The provisioner updates the PV w/ "provisioning completed" annotation, but no update of the PVC occurs.  The next sync period of the binder correctly advances the claim to Bound, but it is a better user experience to not wait.  

I added an explicit update of the claim after the volume is updated.  See #18877.
