### ISSUE TITLE
trying to access apiserver web tools: unauthorized

### ISSUE THREAD

**Issue by streamnsight** [kubernetes/kubernetes#18935]
i posted a question/ issue here 
https://github.com/kubernetes/kubernetes/issues/18927

which brings me other troubles:

trying to access the apiserver Web components, I get a 
`unauthorized` 
answer in the browser (after clearing the HTTPS warning)

I tried in Chrome and Safari (Mac OS X Yosemite)
The CA used to sign the apiserver key / cert is in my keychain
It just seems like it's the api-server failing to authenticate with the client cert/key

**Comment by mikedanese** [comment]
You need to pass an authentication header.

**Comment by mikedanese** [comment]
Please re-post your question to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes). 

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases. 

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to similar questions, and also familiarize yourself with:
   * [the user guide](http://kubernetes.io/v1.0/)
   * [the troubleshooting guide](http://kubernetes.io/v1.0/docs/troubleshooting.html)

Again, thanks for using Kubernetes.

The Kubernetes Team
