### ISSUE TITLE
Error after vagrant halt ./cluster/kube-up.sh

### ISSUE THREAD

**Issue by Bretto** [kubernetes/kubernetes#18990]
I can start a fresh vagrant/kubernetes setup with no issue but if I 
```
vagrant halt
./cluster/kube-up.sh
```
I get this error:
```
==> master: kubernetes-master:
==> master:     True
==> master: kubernetes-minion-1:
==> master:     Minion did not return. [Not connected]
==> master: kubernetes-master:
==> master:     Data failed to compile:
==> master: ----------
==> master:     The function "state.highstate" is running as PID 2090 and was started at 2015, Dec 22 02:01:14.641866 with jid 20151222020114641866
==> master: kubernetes-minion-1:
==> master:     Minion did not return. [Not connected]
==> master: ERROR: Minions returned with non-zero exit code
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
``` 
so I have to do a vagrant destroy and start from scratch... how do I fix this ?

**Comment by mastoj** [comment]
I have the same problem and it is really annoying since whenever I get a faulty node I have to use `kube-down.sh` and then `kube-up.sh` which takes a long time to finish.

I did try to run `kube-up.sh` again after that error message and got a new one instead from the minion, since the master is already running:

```
Each machine instance has been created/updated.
  Now waiting for the Salt provisioning process to complete on each machine.
  This can take some time based on your network, disk, and cpu speed.
  It is possible for an error to occur during Salt provision of cluster and this could loop forever.
Validating master
/etc/profile.d/lang.sh: line 19: warning: setlocale: LC_CTYPE: cannot change locale (UTF-8): No such file or directory
Connection to 127.0.0.1 closed.
Validating minion-1

Waiting for each minion to be registered with cloud provider
error: couldn't read version from server: Get https://10.245.1.2/api: dial tcp 10.245.1.2:443: connection refused
```

**Comment by brandong954** [comment]
Yeup, just had to "kube-down.sh" and then "kube-up.sh" again, and everything worked!

**Comment by jlowdermilk** [comment]
cc @derekwaynecarr. I would assume vagrant halt not working with k8s is expected though.

**Comment by mastoj** [comment]
Might be so, but the docs says that is how you should restart the vagrant
cluster.

**Comment by jlowdermilk** [comment]
Ah, then either docs or setup needs fixing.

**Comment by derekwaynecarr** [comment]
I will look to debug some more to see what is happening.  It would be nice if this worked.

**Comment by zjmchn** [comment]
@derekwaynecarr I create PR #24324 for this
The 'vagrant halt; ./cluster/kube-up.sh' cannot work because:
1. etcd for flannel cannot start in boot after a 'vagrant halt' ( issue #23187 also mentioned it ). 
When systemd starts etcd, the required network interface may be not ready, and frequently restarts will fail the service. I add RestartSec=10 in the etcd service definition. The systemd will wait 10 seconds in schedule a restart. It will start etcd successfully.
2. the kube node cannot register successfully in master
It's because the kubeconfig is updated with the new token in node provisioning now, but the master will use the old key after a 'vagrant halt'. I changed the code to use old kubeconfig in kube node too.

**Comment by zjmchn** [comment]
@derekwaynecarr Any comments for my PR?

**Comment by derekwaynecarr** [comment]
Looking
