### ISSUE TITLE
rolling-update is forced to delete old pod?

### ISSUE THREAD

**Issue by ttllyy** [kubernetes/kubernetes#19008]
if rolling-update is forced to delete old pod, some responses about old pod will be interrupted.
Example:
Rc (myapp) define replicas 2 and contain 2 pods(myapp-mtlz8, myapp-an78c).
rolling-update rc (myapp).
When create a new pod(myapp-ed4988fb0b53ed961037a026068d1a3d-i8wvt) and start to delete a old pod(myapp-mtlz8). 
If old pod is being processed some requests, but the old pod is deleted. So some request don't complete about old pod.

Whether or not:
1. service don't proxy to old pod
2. Waiting to old pod completed all request
3. delete old pod

**Comment by jlowdermilk** [comment]
Is this a question or an issue? If a question please redirect to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes).

**Comment by bgrant0607-nocc** [comment]
Please re-post your question to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes). 

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases. 

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to similar questions, and also familiarize yourself with:
  * [the user guide](http://kubernetes.io/v1.1/)
  * [the troubleshooting guide](http://kubernetes.io/v1.1/docs/troubleshooting.html)

Again, thanks for using Kubernetes.

The Kubernetes Team
