### ISSUE TITLE
Kubelet should handle pod deletion better

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#19037]
kubelet is responsible for deleting pods when the `DeletionTimestamp` is set. Normally a pod worker (goroutine) will kill the containers in a pod and  generate a new status. Then the status manager will [delete the pod](https://github.com/kubernetes/kubernetes/blob/0b647564fce5e3450536388fa0067ca2e347310f/pkg/kubelet/status/manager.go#L376) after successfully updating the status. However, if the pod has terminated long before the deletion timestamp is set, there would not be a pod worker associated with it. To ensure we delete the pod, in the cleanup routine, kubelet calls [TerminatePods()](https://github.com/kubernetes/kubernetes/blob/0b647564fce5e3450536388fa0067ca2e347310f/pkg/kubelet/kubelet.go#L1895) to forcibly trigger a status update. There are a few problems with this approach:
- If there is a delay in watch or in processing the pod updates, kubelet would repeatedly increment the status version, causing huge number of updates piled up in the queue
- pod worker could compete with the cleanup routine to update the status, causing undesirable race (more updates)

This becomes much worse in many e2e tests because of the batch creation/deletion of pods, and the next test will be stuck with processing these updates. We can apply some bandaids such as reducing the frequency of calling `TerminatePods` or ensure we only trigger one termination notice per pod. In the long run, we might want to consider decoupling status updates & pod deletion so that we don't have to trigger a status update in order to delete a pod.

/cc @timstclair @Random-Liu

**Comment by Random-Liu** [comment]
A Humble Idea:
I found that pod worker has no state associated to specific pod, maybe for the no corresponding pod worker problem, we can always have a reaper pod worker which handles all the updates of all the other dead pod workers.

**Comment by Random-Liu** [comment]
Some other humble thoughts.

If we want to ensure there is always associated pod worker when pod update comes, we may want to consider the implementation below:

**Prerequisite:** the pod worker should avoid enqueue a resync when the the pod status becomes Failed after syncPod().

Then, there might be **3 optional implementation:**
* Treat pod workers as a worker pool, do not bound a worker to a specific pod, so that we can manage lifecycle of worker independently.
* Still bound worker to specific pod, but a worker can run many times. When no updates in a period of time, the worker should exit automatically. When new update comes, the worker should be created again.
* Still bound worker to specific pod, and the worker can only run one time (The implementation now). Add a reap worker, send the orphaned update to reaper worker.

**Comment by yujuhong** [comment]
@calebamiles this is NOT a release blocker and we don't plan to work on this by 1.6. Removing the milestone.

**Comment by bgrant0607** [comment]
@yujuhong Is this still relevant, or can it be closed?

**Comment by yujuhong** [comment]
Yes, we fixed this a while ago. Found the PR that includes my commit for this bug: https://github.com/kubernetes/kubernetes/pull/22155
