### ISSUE TITLE
Forward cluster/get-kube-local.sh to https://get.k8s.io/local and document it

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubernetes#19030]
@fgrzadkowski You mentioned in `cluster/get-kube-local.sh` that one may: `wget` or `curl` ` https://get.k8s.io/local` to get kubernetes-in-docker up and running fast.

However, it seems like you guys haven't made the forwarding rule yet.
After that I may send a PR that informs the user of this feature.

**Comment by fgrzadkowski** [comment]
I'm not sure what PR you want to send, but I think that for now we should just remove this comment from the script. I hoped to get it done faster, but this will have to wait until next year.

**Comment by luxas** [comment]
OK, I just thought about adding that info to `docker.md`. 
So the user don't have to type the long `docker run` command, but instead just type `curl`.
I'll wait for it :smile:
Maybe you could self-assign if you're gonna do it

**Comment by luxas** [comment]
@fgrzadkowski Could you keep this open until you fix it?
I think it would be a great feature

**Comment by fgrzadkowski** [comment]
The initial title of this issue was `404 error: https://get.k8s.io/local` and the problem was wrong comment in the script. This is fixed.

I agree that having this script served from `https://get.k8s.io/local` is a great feature, which is why I added this comment in the first place :) Now, that you've repurposed this issue we can re-open it.

Btw, the reason I'm not adding forwarding rules yet is that there is still some issues with running kubelet from docker (hopefully address in #19069).

**Comment by luxas** [comment]
Ping @fgrzadkowski 
I'm working on improvements for `cluster/get-kube-local.sh` which will make it more reliable.
When that PR is in, we should make the link, so this can be closed.
