### ISSUE TITLE
master.Config.StorageVersion is redundant with KUBE_API_VERSIONS

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/kubernetes#19032]
master.Config.StorageVersion enables users to change the storage version for each group supported by api server.
Same thing can be done using KUBE_API_VERSIONS env variable.

Documentation says to use KUBE_API_VERSIONS to switch the storage version https://github.com/kubernetes/kubernetes/blob/master/docs/admin/cluster-management.md#switching-your-clusters-storage-api-version.

Do we need to support master.Config.StorageVersion or Is it fine to delete it?

cc @smarterclayton @lavalamp @caesarxuchao @kubernetes/goog-csi

**Comment by nikhiljindal** [comment]
cc @kubernetes/sig-api-machinery

**Comment by caesarxuchao** [comment]
We still need master.Config.StorageVersion. Because in #18925, we *stops* requiring the versions in KUBE_API_VERSIONS to be in the order from most preferred to least, so users cannot use KUBE_API_VERSIONS to change the storageVersions anymore. They should use --storageVersions to change the storage version, by default the storage version will be the first version in the `availableVersions` in each group's install package. https://github.com/kubernetes/kubernetes/blob/master/pkg/api/install/install.go#L42
