### ISSUE TITLE
Server-side cascading deletion

### ISSUE THREAD

**Issue by kargakis** [kubernetes/kubernetes#19054]
I think it makes sense to maintain the ability to choose between cascading and non-cascading deletion once we move reaping server-side (https://github.com/kubernetes/kubernetes/issues/12143). This will most probably be a field in api.DeleteOptions. Opening this issue to track that change and capture any discussion regarding server-side reaping.

cc: @liggitt @bgrant0607 @soltysh @deads2k @smarterclayton

**Comment by smarterclayton** [comment]
In another issue we discussed whether cascade should default true or false.  After thinking it over a fair amount, I believe it would be more correct to default false.  Also captured for posterity - graceful period seconds and cascade have to be distinct options (graceful probably affects the children in this case), but we can't use graceful = 0 to indicate cascade false (since user may want to cascade true in that case).

**Comment by liggitt** [comment]
also, combining grace and cascade gets weird...

**Comment by bgrant0607** [comment]
There's some discussion of this in #1535.

**Comment by bgrant0607** [comment]
Programmatic clients building atop an API may well want cascade=false to do things like rename a resource, change other immutable fields, or replace one type of controller with another (e.g., ReplicationController with ReplicaSet).

Users using an API directly via kubectl or UI typically expect cascade=true, except when they intentionally orphan the resources.

One could achieve these different behaviors with the default set either way. 

Regardless, we'll want a robust way to override the default behavior.

In the case of a pod, the resource is still active during the grace period, which is not what we'd want when deleting replicas of a ReplicationController, since it would just replace them. OTOH, the grace periods of the RC's pods won't start until we try to delete them. So, it seems we need to decide what reasonable graceful termination behavior should be for each resource type. 

I could imagine that a RC with graceful deletion and cascading deletion could first delete pods using their default termination grace periods and then issue another round of deletes with grace period equal to zero at the end of its own grace period.

Note that for cascade=true, either some resource needs to continue to exist to represent the desire to clean up the child resources, or the desired behavior needs to be pushed down to the child resources, as in the proposed existence dependency, which I believe we want for other use cases. 

The main disadvantage of pushing the policy down to the child resources is that it becomes more difficult to change.

If we had multi-object transactions, it would be easy to index resources by both name and uid. We could then have deletion remove the name index entry and render the resource inert. The resource could continue to exist to drive cascading deletion. This is preferable to creating a secondary resource for this purpose, since the status of the resource could continue to be updated and made available during the process.

**Comment by caesarxuchao** [comment]
> The main disadvantage of pushing the policy down to the child resources is that it becomes more difficult to change.

@bgrant0607 may I ask what you mean by "change"? Do you mean the change of API scheme?

**Comment by bgrant0607** [comment]
@caesarxuchao If we record "delete me if this other object goes away" in each child (e.g., pod), then in order to choose not to delete the pods when deleting their parent (e.g., controller), one would have to update the pod template and every pod.

**Comment by bgrant0607** [comment]
@lavalamp @caesarxuchao Let's use this issue for server-side cascading deletion.

Forked from #12143

Supersedes #1535, which I'll close, finally.

Proposal: #23656
API changes: #23928

**Comment by bgrant0607** [comment]
cc @bmelville @vaikas-google

**Comment by caesarxuchao** [comment]
WIP garbage collector implementation phase I: https://github.com/kubernetes/kubernetes/pull/24509

**Comment by lavalamp** [comment]
Looks like we have a very alpha version in. Not ready for production yet.

We'll set a goal of beta in 1.4.

**Comment by bgrant0607** [comment]
@caesarxuchao What are we targeting for 1.4?

**Comment by caesarxuchao** [comment]
https://github.com/kubernetes/kubernetes/issues/26120 is the umbrella issue tracking the progress. I don't think we can make GC beta for 1.4. We are targeting early in the 1.5 cycle. For 1.4 we should finish the testing and benchmarking.

**Comment by lavalamp** [comment]
I think we can flip it on by default (beta) in 1.4 as long as we can add the "wait for completion" finalizer in the future and don't need it immediately.

**Comment by lavalamp** [comment]
On by default means the garbage collector runs on everything. However controllers need to be modified to actually use it. Chao has modified the replication controller, and I think @wojtek-t updated the replicaset controller. Objects from other controllers wouldn't be affected until they are updated.

**Comment by lavalamp** [comment]
Is there anything left to do here?

**Comment by caesarxuchao** [comment]
GC is on by default in 1.4. I'll close this issue. For known issues please refer to https://github.com/kubernetes/kubernetes/issues/26120.
