### ISSUE TITLE
Replication Controller with metadata.name length equal to 55 characters fails.

### ISSUE THREAD

**Issue by alexisvincent** [kubernetes/kubernetes#19075]
When creating a replication controller whose metadata.name has a length of exactly 55 characters, the template pods will fail to start with:

```
25s 2s  4   {kubelet gke-olympus-7c037362-node-whbj}    implicitly required container POD   Pulled  Container image "gcr.io/google_containers/pause:0.8.0" already present on machine
  2s    2s  1   {kubelet gke-olympus-7c037362-node-whbj}    implicitly required container POD   Created Created with docker id 6c1a57bf494b
  2s    2s  1   {kubelet gke-olympus-7c037362-node-whbj}    implicitly required container POD   Failed  Failed to start with docker id 6c1a57bf494b with error: API error (500): Cannot start container 6c1a57bf494b73d45971a0d702f2db1b4399e781cc0baec50ed8b346a3445109: [8] System error: read parent: connection reset by peer

  2s    2s  1   {kubelet gke-olympus-7c037362-node-whbj}        FailedSync  Error syncing pod, skipping: API error (500): Cannot start container 6c1a57bf494b73d45971a0d702f2db1b4399e781cc0baec50ed8b346a3445109: [8] System error: read parent: connection reset by peer
```

repeated many times.

Desired Action:
Pod is created successfully

Actual Action:
Pod fails with error above

Steps to reproduce:
Create a replication controller with a name exactly 55 characters long.

Here is a json config for reproducibility.

``` json
{
    "kind": "ReplicationController",
    "apiVersion": "v1",
    "metadata": {
        "name": "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
        "labels": {
            "app": "test"
        }
    },
    "spec": {
        "replicas": 1,
        "selector": {
            "app": "test"
        },
        "template": {
            "metadata": {
                "labels": {
                    "app": "test"
                }
            },
            "spec": {
                "containers": [
                    {
                        "name": "test",
                        "image": "tutum/hello-world",
                        "ports": [
                            {
                                "containerPort": 80,
                                "protocol": "TCP"
                            }
                        ]
                    }
                ]
            }
        }
    }
}
```

**Comment by alexisvincent** [comment]
Any feedback on this?

**Comment by fgrzadkowski** [comment]
@kubernetes/goog-node 

Can you please post the following information:
* cloud provider (GKE?)
* os
* kube version

**Comment by alexisvincent** [comment]
GKE
Master Version: 1.1.3
Node Version: 1.1.3
Not sure exactly what GKE uses as OS

**Comment by bprashanth** [comment]
Hmm,@lexisvincent can you consistently reproduce? might be related to https://github.com/docker/docker/issues/14203 (though a connection reset error is too broad to point fingers)

**Comment by bprashanth** [comment]
I meant @alexisvincent

**Comment by alexisvincent** [comment]
My thoughts too. I could when I had the issue. Haven't tested since. I will try again when I'm home

**Comment by alexisvincent** [comment]
I just tried on 2 clusters (one of the the same as before) and couldn't reproduce. Also I think the issue manifested on a previous version of kubernetes. 1.1.2 I've since upgraded the cluster to 1.1.3

**Comment by ins0mia** [comment]
I also have this problem, but in my case I have "metadata.name: cron". It behavior has appeared not after first deployment creation, but after some period of time. When I replace  “cron” with “scheduler-cron” - all works! Also, if I use “metadata.name: sche” - container is not created. I think that all words with 4 letters cause problem.

cloud provider: GCE
master and node os: Debian GNU/Linux 7 (wheezy)
kube version:
Client Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.0", GitCommit:"5cb86ee022267586db386f62781338b0483733b3", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.0", GitCommit:"5cb86ee022267586db386f62781338b0483733b3", GitTreeState:"clean"}

After creating deployment using “kubectl create -f cron_deployment.yml” with “metadata.name: cron”, “kubectl get pods” show that cron pod is in status “ContainerCreating”. Also, after creation lot of pause containers are created.

When I add some useless additional data to cron_deployment.yml:
          ports:
          - containerPort: 9000
            name: cron
Container start properly! But not always. 

maybe, it will be helpful:

kubectl get events
`Warning   FailedSync   {kubelet prod-minion-8cj1}   Error syncing pod, skipping: failed to "StartContainer" for "POD" with RunContainerError: "runContainer: API error (500): Cannot start container 00f37c1d30e63f0e3674b00e9221091408de780911357109a500397efa61584d: [8] System error: read parent: connection reset by peer\n"`

docker log
`signal: killed"
time="2016-04-15T12:34:41.953038632Z" level=warning msg="failed to cleanup ipc mounts:\nfailed to umount /var/lib/docker/containers/74359e75fc7ebc4003a94da2b6f0f03826648e0520a704366b114f36e8b3bb51/shm: invalid argument\nfailed to umount /var/lib/docker/containers/74359e75fc7ebc4003a94da2b6f0f03826648e0520a704366b114f36e8b3bb51/mqueue: invalid argument"
time="2016-04-15T12:34:41.953171123Z" level=error msg="Handler for POST /containers/74359e75fc7ebc4003a94da2b6f0f03826648e0520a704366b114f36e8b3bb51/start returned error: Cannot start container 74359e75fc7ebc4003a94da2b6f0f03826648e0520a704366b114f36e8b3bb51: [8] System error: read parent: connection reset by peer"
time="2016-04-15T12:34:41.953216466Z" level=error msg="HTTP Error" err="Cannot start container 74359e75fc7ebc4003a94da2b6f0f03826648e0520a704366b114f36e8b3bb51: [8] System error: read parent: connection reset by peer" statusCode=500
`

kubelet log:
`I0415 12:50:18.253859    2936 manager.go:1688] Need to restart pod infra container for "cron-1052350754-pwq4i_default(42a8a9df-0308-11e6-8eea-42010af10004)" because it is not found
E0415 12:50:19.282691    2936 manager.go:1858] Failed to create pod infra container: RunContainerError; Skipping pod "cron-1052350754-pwq4i_default(42a8a9df-0308-11e6-8eea-42010af10004)"
E0415 12:50:19.282800    2936 pod_workers.go:138] Error syncing pod 42a8a9df-0308-11e6-8eea-42010af10004, skipping: failed to "StartContainer" for "POD" with RunContainerError: "runContainer: API error (500): Cannot start container 60df85fba29e035310e1331f7bd48f0db593d0ace5a6ae471a21822effec3e59: [8] System error: read parent: connection reset by peer\n"
W0415 12:50:19.285435    2936 container.go:341] Failed to create summary reader for "/60df85fba29e035310e1331f7bd48f0db593d0ace5a6ae471a21822effec3e59": none of the resources are being tracked.
I0415 12:50:20.343613    2936 kubelet.go:2410] SyncLoop (PLEG): "cron-1052350754-pwq4i_default(42a8a9df-0308-11e6-8eea-42010af10004)", event: &pleg.PodLifecycleEvent{ID:"42a8a9df-0308-11e6-8eea-42010af10004", Type:"ContainerDied", Data:"6ab462bb1a5e16508aa422cb6e47f636a5cad6b2f9308e071f88ce6d6606fb57"}`
