### ISSUE TITLE
Update Elasticsearch and Kibana version for ES logging addon

### ISSUE THREAD

**Issue by freehan** [kubernetes/kubernetes#19149]
Elasticsearch addon is running ES version 1.5, while 2.1 is already out for some time. Addon Elasticsearch: https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/fluentd-elasticsearch/es-image

Plus, the ES addon cluster discovery only happens when pod starts. So if the es pods got recreated. The es cluster can easily get into bad state. 

Probably merging the elasticsearch setup from example would work
https://github.com/kubernetes/kubernetes/tree/master/examples/elasticsearch

**Comment by mingchuno** [comment]
+1

**Comment by Crassirostris** [comment]
@colemickens No, I just finished ES part, it took some time. Didn't work on kibana just yet

I will try to reproduce it shortly. Meanwhile, have you been able to isolate the problem? At what point kibana doesn't work?

By the way, I seems that we can't use ES image from dockerhub directly, because we need some k8s-specific files/configurations inside the container. Not sure about kibana, but probably the same -- easier to copy the offical Dockerfile and modify it, then to have another dependency and integrate with it.

**Comment by colemickens** [comment]
~~The problem was that the newer version of Kibana is a webapp that expects to be able to manipulate the URL in the browser in a way that is incompatible with the Service Proxy. It may be possible to workaround it with some configuration to Kibana, like setting the base URL to the same structure as the service proxy.~~

I just remembered that I was playing with 5.x which isn't stable yet, so I suppose disregard my comment.

**Comment by Crassirostris** [comment]
Oh, yes, I planned to use ES 2.4.1 and Kibana 4.6.1

Elastic products from 5.x will require even more attention, since they're not very backward-compatible in many aspects.

**Comment by Crassirostris** [comment]
@piosz Can be closed due to #34969
