### ISSUE TITLE
The problem of Master node switch in HA proposal design 

### ISSUE THREAD

**Issue by wangzhezhe** [kubernetes/kubernetes#19327]
It seems there still existing some problems in [HA proposal design](https://github.com/kubernetes/kubernetes/blob/master/docs/proposals/high-availability.md) especially the short window when the Master is switched to a new one. During that time , some requests from the controller manager and the scheduler may be committed to the apiserver at the same time probably. Could any one give me some practical cases of this conflicts? I want to know what influence this will cause on earth? Thank you !

**Comment by jlowdermilk** [comment]
This is a question you could probably ask on the original thread (#473), but cc @mikedanese.

**Comment by mikedanese** [comment]
I think the answer to that is "so what"? :)

Instead of spending time trying to disprove CAP theorem or the FLP result, we have agreed to design a control-plane that will keep working (albeit suboptimally) even when multiple masters are acting.

All components do approximately the same thing and we trust that they will at least "try" not to act when they aren't the leader. We implement optimistic concurrency using resource version which gives us a fair amount of saftey. If for some reason a scheduler is unable to read from the API but is able to write and thinks it's the master, all it's writes will fail because it will be writting with stale resource versions. If two schedulers race to write a node name as the leadership transistions, only one will succeed because the resource version will be incremented making the resource version in the second request stale. We have agreed not to implement fencing as we've decided that it would be too restricting (e.g. will not allow us to shard our datastore).

You can read about our concurrency control [here](https://github.com/kubernetes/kubernetes/blob/master/docs/devel/api-conventions.md#concurrency-control-and-consistency)

Here's where we disucssed the options https://github.com/kubernetes/kubernetes/pull/16830#issuecomment-158786529 

You can read about the knobs the leaderelection client has here https://godoc.org/k8s.io/kubernetes/pkg/client/leaderelection which allows you to sacrifice availability for correctness depending on your need.

We have a lot of experience with this approach and it has worked very well in practice.

**Comment by wangzhezhe** [comment]
Thanks for that information !
