### ISSUE TITLE
ImageGC garbage collect images even these images are used by containers not managed by kubernetes

### ISSUE THREAD

**Issue by AdoHe** [kubernetes/kubernetes#19328]
FYI. I just want to know this behavior is correct? or we should just garbage collect images used by containers which are managed by kubernetes?

**Comment by dchen1107** [comment]
It shouldn't, and it should be failed even it tries. @AdoHe Can you provide more information on why you think ImageGC tries to remove your images?

**Comment by mqliang** [comment]
AFAIK, if an image is in use, even used by containers which are ***NOT***managed by kubernetes, kubelet will avoid gc it. But if there is no container using it, the image will be GCed.

**Comment by AdoHe** [comment]
@mqliang IIRC, image manager will list all images on the node, but just use containers in the pod to check whether the image is in used, so if the image is actually used by an outside container, image manager still thinks it is not used, so it is easily to get garbage collected. I am not sure whether I misunderstand

**Comment by mqliang** [comment]
@AdoHe I looked through the code. You are right. Do you mind I send a PR to help fix this?

**Comment by AdoHe** [comment]
@dchen1107 what do you think of this issue?

**Comment by AdoHe** [comment]
@mqliang I want to make sure the default behavior is correct or not, if possible I will send a PR later.

**Comment by mqliang** [comment]
Ok, expect your PR!

**Comment by vishh** [comment]
I'm in the process of refactoring image gc logic to not talk to the runtime directly, but instead use kubelets's internal state. That change should fix this issue.

**Comment by dchen1107** [comment]
@AdoHe your understanding code above is right. Like @vishh mentioned above, he is rafactorying the code of GC which should fix the issue here.

But if an image is really used by a container, no matter the container is managed by kubelet or directly by docker daemon, removing such image will failed anyway.

**Comment by vishh** [comment]
In general, the recommendation is to not run docker containers outside of
kubelet since it complicates kubelet unnecessarily. Although my upcoming PR
will fix this, I'd suggest not following such a pattern.
For example, disk accounting will be wrecked if containers are run outside
of kubelet, and kubernetes cannot guarantee its semantics because of that.

**Comment by AdoHe** [comment]
@dchen1107 sure, the image in used can not be removed.

**Comment by AdoHe** [comment]
@vishh yes, we should better follow this pattern to not run containers outside of kubelet.

**Comment by dchen1107** [comment]
@AdoHe I am closing this issue as work-as-intended here. Today Kubelet only removes unused images when disk under pressure, no matter the image is pulled by docker directly or through kubelet. You definitely want to Kubelet, the node agent here to do this for node protection. Soon we want to add support to failed some running pods to clean up more disk space under OOD condition.

@vishh Not running docker containers outside of kubelet is the recommended way for general purpose. But please note that the user might pre-cached the image to reduce the startup latency in some cases. For example, GKE does precatched our infra container: pause.
