### ISSUE TITLE
Cluster can't see the nodes???

### ISSUE THREAD

**Issue by thinhduckhoi** [kubernetes/kubernetes#19526]
Hi guys.
I followed the tutorial but when i was trying to test if the cluster could see the nodes this error appeared.
[error: couldn't read version from server: Get http://localhost:8080/api: dial tcp [::1]:8080: getsockopt: connection refused]
I don't know what the reason was, can someone help me about this?
@ A little bit information: I'm running 2 instances with Centos7 installed on Amazon EC2.

**Comment by Pensu** [comment]
What command did you use to check?

**Comment by thinhduckhoi** [comment]
I run the this following command to check but it didn't work. 
kubectl get nodes

**Comment by Pensu** [comment]
What address are you binding your api server on? I used to get that error when my api-server wasn't listening on 0.0.0.0. Do you have any api-server and kubelet logs?

**Comment by lavalamp** [comment]
Please re-post your question to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes). 

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases. 

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to similar questions, and also familiarize yourself with:
   * [the user guide](http://kubernetes.io/v1.0/)
   * [the troubleshooting guide](http://kubernetes.io/v1.0/docs/troubleshooting.html)

Again, thanks for using Kubernetes.

The Kubernetes Team
