### ISSUE TITLE
Replicas is type int, but comment says it should be a pointer

### ISSUE THREAD

**Issue by mqliang** [kubernetes/kubernetes#19591]
see:
https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/extensions/types.go#L206-L208

Should we correct the comment, or make `Replicas` type as *int?

**Comment by thockin** [comment]
This is maybe touching on the difference between internal API and versioned
APIs.

For the versioned type (
https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/extensions/v1beta1/types.go#L195)
you can see we use a pointer.  This is important because it makes the
optional-ness clear, but it is REQUIRED here because the API-defined
default value is 1, which is NOT what Go will do if the field is
unspecified.  Using a pointer lets us distinguish "I want 0" from "I did
not specify, which means default, which means 1".

We apply defaults to versioned types.  Once we have applied the default
value, we don't NEED to distinguish anymore.  For a post-defaulting
internal type, 0 means 0, and 1 means 1.

So the question for API discussion is whether we should keep the internal
type as a pointer or not.

Reasons to keep it as a pointer:
+ consistency
+ obviousness to non-core-API developers (most of them)

Reasons to make it not a pointer:
+ internal code is easier to write (no nil checking, no dereferencing)
+ clarity - it's only optional to API users, not truly optional
