### ISSUE TITLE
K8s metrics not working with Graphana/influxdb/heapster/cadvisor on my cluster

### ISSUE THREAD

**Issue by ckleban** [kubernetes/kubernetes#19610]
Hello,

This could very well be a configuration error on my part but I'm trying to get metric collection working on my k8s cluster (on centurylink cloud) and I've run into issues that I believe have something to do with my kubelet and cadvisor configuration but I'm not sure. 

I have grafana up and running with some basic stats coming in but I seem to be missing metrics like cpu/network/etc about the pods/containers. 

What works:
*Going to the cadvisor ui on the minion. I see all stats. 

What doesn't seem to work:
- When I try to query the kubectl stats api at curl minion-IP:10250/stats/, I see the following errors in my  kubelet.log file:

```
I0113 19:56:34.674132   31859 logs.go:40] http: TLS handshake error from 127.0.0.1:46565: tls: first record does not look like a TLS handshake
I0113 19:57:22.667591   31859 logs.go:40] http: TLS handshake error from 127.0.0.1:46585: tls: first record does not look like a TLS handshake
```

My heapster log files look like this:

```
I0113 19:44:23.344056       1 heapster.go:55] /heapster --source=kubernetes:https://kubernetes?inClusterConfig=false&useServiceAccount=true&insecure=true&auth= --sink=influxdb:http://monitoring-influxdb:8086 --stats_resolution=30s --sink_frequency=1m
I0113 19:44:23.344258       1 heapster.go:56] Heapster version 0.18.2
I0113 19:44:23.344528       1 kube_factory.go:169] Using Kubernetes client with master "https://kubernetes" and version "v1"
I0113 19:44:23.344556       1 kube_factory.go:170] Using kubelet port 10255
I0113 19:44:23.356465       1 driver.go:376] created influxdb sink with options: {root root monitoring-influxdb:8086 k8s false}
I0113 19:44:23.366080       1 heapster.go:66] Starting heapster on port 8082
```

Perhaps kubelet is trying to communicate to cadvisor with a mismatch of http/https somehow? I'm not sure of the exact data flow of how things are moving.

Thanks for any help.
Chris

**Comment by timstclair** [comment]
What happens if you run `kubectl proxy`, and then curl the stats API through
```
http://localhost:8001/api/v1/proxy/nodes/NODE_NAME:10250/stats/
```

Kubelet doesn't need to communicate with cAdvisor, since it's compiled in as a library. Heapster does need to query the stats from the Kubelet though.

**Comment by ckleban** [comment]
Thanks for the response. It seems I'm getting 500 errors for any uri past
/api:

>>>>wget http://localhost:8001/api/

--2016-01-13 15:45:43--  http://localhost:8001/api/

Resolving localhost... 127.0.0.1, ::1

Connecting to localhost|127.0.0.1|:8001... connected.

HTTP request sent, awaiting response... 500 Internal Server Error

2016-01-13 15:45:43 ERROR 500: Internal Server Error.


>>>>wget http://localhost:8001/api/v1/proxy/nodes/10.136.191.14:10250/stats

--2016-01-13 15:47:48--
http://localhost:8001/api/v1/proxy/nodes/10.136.191.14:10250/stats

Resolving localhost... 127.0.0.1, ::1

Connecting to localhost|127.0.0.1|:8001... connected.

HTTP request sent, awaiting response... 500 Internal Server Error

2016-01-13 15:47:48 ERROR 500: Internal Server Error.

**Comment by ckleban** [comment]
Btw, the logs from the kubectl proxy command were as follows:

Starting to serve on 127.0.0.1:8001
2016/01/13 15:43:48 http: proxy error: unsupported protocol scheme ""
2016/01/13 15:44:04 http: proxy error: unsupported protocol scheme ""
2016/01/13 15:44:06 http: proxy error: unsupported protocol scheme ""
2016/01/13 15:44:36 http: proxy error: unsupported protocol scheme ""
2016/01/13 15:44:55 http: proxy error: unsupported protocol scheme ""

**Comment by castrojo** [comment]
Please re-post your question to [Stack Overflow](http://stackoverflow.com/questions/tagged/kubernetes).

Thanks for taking the time to report an issue to us. In the past this tracker has housed both bug reports and user support requests, we are now only using this tracker for software defects and feature tracking.   

We are trying to consolidate the channels to which questions for help/support
are posted so that we can improve our efficiency in responding to requests,
and to make it easier for you to find answers to frequently asked questions and
how to address common use cases.

The Kubernetes team scans Stack Overflow on a regular basis, and will try to
ensure your questions don't go unanswered.

If you're looking for more long-form discussion on best practices, we encourage you to check out the [Kubernetes user list](https://groups.google.com/forum/#!forum/kubernetes-users). 

You can also find more information here:

  * [User Documentation](http://kubernetes.io/docs/)
  * [Troubleshooting Guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/)

Again, thanks for using Kubernetes. If you feel this issue has been closed in error then please reopen it and we can have another look. 

The Kubernetes Team
