### ISSUE TITLE
DaemonSet doesn't create any pods: v1.1.2

### ISSUE THREAD

**Issue by c1freitas** [kubernetes/kubernetes#19700]
### Issue

Attempting to launch a DaemonSet on an existing cluster of 6 nodes with multiple containers already deployed. 

Deployment seems to succeed but no pods are created:
```
> ic describe ds
Name:		dd-agent
apiVersion: extensions/v1beta1
Image(s):	datadog/docker-dd-agent:kubernetes
Selector:	app=dd-agent,name=dd-agent,version=v1
Node-Selector:	<none>
Labels:		release=stable,tech=datadog,tier=backend
Desired Number of Nodes Scheduled: 0
Current Number of Nodes Scheduled: 0
Number of Nodes Misscheduled: 0
Pods Status:	0 Running / 0 Waiting / 0 Succeeded / 0 Failed
No events.
```

### Setup
Cloud: **AWS**
We are running the example cluster created with `kube-aws`
The existing cluster has 30 pods already running across 6 nodes.
* CoreOS alpha (891.0.0)
* Kubernetes server v1.1.2
* Updated the /etc/kubernetes/manifest/kube-apiserver.manifest to enable DaemonSets by adding `--runtime-config=extensions/v1beta1/daemonsets=true`
* On the _kube-aws-controller_ restarted services with:
  `sudo systemctl daemon-reload`
  `sudo systemctl restart kubelet`

This seems like the same issue as #18656, but I restarted with the above commands and no luck.

**Comment by mikedanese** [comment]
Restarting the kubelet restarts all the other daemons. Unlike the docker daemon we designed the kubelet so that it can be upgraded without affecting the nodes current workload (.i.e. conatiners won't get killed and restarted, they will get adopted by the new kubelet process)

**Comment by mikedanese** [comment]
Please re-post your question to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes). 

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases. 

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to similar questions, and also familiarize yourself with:
   * [the user guide](http://kubernetes.io/v1.0/)
   * [the troubleshooting guide](http://kubernetes.io/v1.0/docs/troubleshooting.html)

Again, thanks for using Kubernetes.

The Kubernetes Team
