### ISSUE TITLE
Add priority function for NodeNotReady count to probabalistically quarantine flapping nodes safely

### ISSUE THREAD

**Issue by quinton-hoole** [kubernetes/kubernetes#19722]
https://github.com/kubernetes/kubernetes/issues/19118#issuecomment-172102534 refers.

I think that we should potentially have a mechanism in place for quarantining nodes that fail often/repeatedly. We will of course need to be careful of "poisoned pods" which, when launched on a node, cause it to fail often and get quarantined. If the poison pod then gets rescheduled to another node in the cluster, eventually all nodes could become quarantined. That would be very bad. But repeated hardware or system problems on a node should ultimately cause pods not to scheduled there, somehow, safely.

A good approach might be to use a basic [priority function](kubernetes/docs/devel/scheduler.md). For example, keep a sliding window not ready count per node (how many times a node has gone not ready in a given time window), and add a priority function to put nodes with high not ready counts at the bottom of the list when selecting nodes. That works around the poisoned pod problem outlined above, as we wouldn't actually lose real capacity by hard quarantining nodes. Only probabalistically avoid scheduling onto more flaky nodes. I think that's both simple and effective. Unless @mml or @davidopp have better ideas, I think that we should add this feature to the backlog.

**Comment by quinton-hoole** [comment]
@kubernetes/goog-control-plane @mikedanese

**Comment by gmarek** [comment]
cc @gmarek

**Comment by mml** [comment]
You have to pick some tradeoff between risking capacity and reacting to problems.  We discussed a related tradeoff in #13430, but your idea to just steer the scheduler away from bad nodes would improve reliability.  The priority function you describe will tend to work pretty well in large clusters with a little extra capacity and won't do much in smaller, more tightly packed clusters.  It'll probably reduce flakiness as long as the e2e cluster isn't too tiny.

Based on experience watching the borg test gang manage system and integration tests, tracking down underlying flakiness elsewhere in the stack (hardware, kernel) is a fact of life.  It can be hard to tell generally if the test is failing because your code is bad or because the kernel is bad.

**Comment by spiffxp** [comment]
/sig scheduling
since this is referring to priority functions
