### ISSUE TITLE
Port-forwarding not working due to missing socat command

### ISSUE THREAD

**Issue by pwais** [kubernetes/kubernetes#19765]
I think #17157 might still be broken.  I'm using the spark example w/ ubuntu provider.  I'm forwarding 8081 below because I'm running the command on my k8s master, which is already using 8080.

```
$ which socat
/usr/bin/socat

$ kubectl port-forward zeppelin-controller-oea9w 8081:8080
I0116 11:51:55.986614   22704 portforward.go:213] Forwarding from 127.0.0.1:8081 -> 8080
I0116 11:51:55.986782   22704 portforward.go:213] Forwarding from [::1]:8081 -> 8080
I0116 11:52:03.982497   22704 portforward.go:247] Handling connection for 8081
E0116 11:52:04.116196   22704 portforward.go:318] an error occurred forwarding 8081 -> 8080: error forwarding port 8080 to pod zeppelin-controller-oea9w_default, uid : unable to do port forwarding: socat not found.

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"1", GitVersion:"v1.1.2", GitCommit:"3085895b8a70a3d985e9320a098e74f545546171", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"1", GitVersion:"v1.1.2", GitCommit:"3085895b8a70a3d985e9320a098e74f545546171", GitTreeState:"clean"}
```

Purportedly 1.1.2 should include the fix in #17157

**Comment by pwais** [comment]
I tried k8s 1.1.4 and the problem remains.   @alex-mohr where exactly is socat being called? how can I fix this?

**Comment by bgrant0607** [comment]
cc @ncdc

**Comment by bgrant0607** [comment]
@pwais socat needs to be installed on the nodes:

https://github.com/kubernetes/kubernetes/blob/9fef5f2938bb9db0667de893a5733cb899afd8ed/pkg/kubelet/dockertools/manager.go#L1182

**Comment by gramic** [comment]
I am using non containerized k8s via `./hack/local-cluster-up.sh` and after installing socat, the error changed to "uid : exit status 1"
```bash
$ kubectl port-forward jenkins-v14-hs1sf 8123:80
I0202 16:16:46.875324   18591 portforward.go:213] Forwarding from 127.0.0.1:8123 -> 80
I0202 16:16:46.875488   18591 portforward.go:213] Forwarding from [::1]:8123 -> 80
I0202 16:16:57.346917   18591 portforward.go:247] Handling connection for 8123
I0202 16:16:57.348187   18591 portforward.go:247] Handling connection for 8123
E0202 16:16:57.389108   18591 portforward.go:318] an error occurred forwarding 8123 -> 80: error forwarding port 80 to pod jenkins-v14-hs1sf_default, uid : exit status 1
E0202 16:16:57.397791   18591 portforward.go:318] an error occurred forwarding 8123 -> 80: error forwarding port 80 to pod jenkins-v14-hs1sf_default, uid : exit status 1
I0202 16:16:57.398114   18591 portforward.go:247] Handling connection for 8123
E0202 16:16:57.425331   18591 portforward.go:318] an error occurred forwarding 8123 -> 80: error forwarding port 80 to pod jenkins-v14-hs1sf_default, uid : exit status 1
```

**Comment by drocsid** [comment]
Hello, I'm running the spark example locally on the 1.22 release. After installing socat, I was able to connect to the zepplin-controller / dashboard.

kubectl port-forward zeppelin-controller-0go00 8081:8080
I0414 20:48:18.156878    2293 portforward.go:213] Forwarding from 127.0.0.1:8081 -> 8080
I0414 20:48:18.156952    2293 portforward.go:213] Forwarding from [::1]:8081 -> 8080
I0414 20:48:29.002317    2293 portforward.go:247] Handling connection for 8081
I0414 20:48:29.003358    2293 portforward.go:247] Handling connection for 8081
I0414 20:48:29.460353    2293 portforward.go:247] Handling connection for 8081
I0414 20:48:29.461996    2293 portforward.go:247] Handling connection for 8081
I0414 20:48:29.464332    2293 portforward.go:247] Handling connection for 8081
I0414 20:48:30.359611    2293 portforward.go:247] Handling connection for 8081


I'm trying to start a sig-local interest group. Since some of you are running kubernetes locally, would you consider joining the kubernetes-sig-local google group?

**Comment by munnerz** [comment]
I'm seeing this issue running kubectl 1.2.0 on a GKE cluster running 1.2.0. Port forwarding into a pod gives:

```
I0414 23:20:53.731580   71324 portforward.go:213] Forwarding from 127.0.0.1:53451 -> 80
I0414 23:20:53.731787   71324 portforward.go:213] Forwarding from [::1]:53451 -> 80
I0414 23:20:58.379950   71324 portforward.go:247] Handling connection for 53451
I0414 23:20:58.381856   71324 portforward.go:247] Handling connection for 53451
E0414 23:20:58.548161   71324 portforward.go:318] an error occurred forwarding 53451 -> 80: error forwarding port 80 to pod acme-3541642747-yuad5_default, uid : unable to do port forwarding: socat not found.
E0414 23:20:58.553493   71324 portforward.go:318] an error occurred forwarding 53451 -> 80: error forwarding port 80 to pod acme-3541642747-yuad5_default, uid : unable to do port forwarding: socat not found.
I0414 23:20:58.554010   71324 portforward.go:247] Handling connection for 53451
E0414 23:20:58.678159   71324 portforward.go:318] an error occurred forwarding 53451 -> 80: error forwarding port 80 to pod acme-3541642747-yuad5_default, uid : unable to do port forwarding: socat not found.
```

**Comment by cmpmohan** [comment]
I'm facing same issue.. where we need install socat..? in kubernetes nodes?

**Comment by ncdc** [comment]
@cmpmohan yes, socat is needed on the nodes for port forwarding to work.

**Comment by dims** [comment]
fyi, there's a list being compiled here ("New issue Identify, document and maybe remove kubelet dependencies"):
https://github.com/kubernetes/kubernetes/issues/26093

**Comment by cmpmohan** [comment]
@ncdc thanks for your response.. we have alternative way to access the zeppelin web portal .. i,e we are accessing them via kubernetes minion IP with port.. its working..

**Comment by jimmycuadra** [comment]
This is a problem on CoreOS where the nodes don't have socat. Is there a way to use socat packaged as a Docker image? In CoreOS, programs are generally not installed on the host itself.

**Comment by ncdc** [comment]
@smarterclayton @kubernetes/sig-node @kubernetes/rh-cluster-infra what do you all think about either switching to running socat from an image or at least making it an option?

**Comment by derekwaynecarr** [comment]
@ncdc - we need to determine if we want to charge usage of `socat` to the system or the pod if we run it from an image.  I think after we have pod-level cgroups, its worth visiting this option more.

**Comment by ncdc** [comment]
+1 to charging to the pod if we can make that happen

**Comment by smarterclayton** [comment]
Originally I had assumed a good place to put socat and other necessary
utilities would be in the pod infrastructure image.

**Comment by derekwaynecarr** [comment]
@smarterclayton - that is a really interesting idea ;-)

**Comment by pires** [comment]
@philips this used to work on CoreOS. what happened?

**Comment by euank** [comment]
If you run the kubelet via `kubelet-wrapper` on CoreOS, the dependencies (like socat) are included in the rkt fly container the kubelet is run in.

CoreOS issue: https://github.com/coreos/bugs/issues/1114

/cc @crawford @aaronlevy

**Comment by aaronlevy** [comment]
@jimmycuadra this should work on CoreOS when running the kubelet as a container via the kubelet-wrapper (as @euank mentioned).

See: https://coreos.com/kubernetes/docs/latest/kubelet-wrapper.html

Also agree that longer-term something along the lines of pod infrastructure image would help with required utilities (socat, nsenter), mount tools (nfs, ceph, git), network plugins (flannel, calico, weave).

**Comment by jimmycuadra** [comment]
The reason using the recommended kubelet-wrapper approach bothers me, and why I have opted not to use it thus far, is that it relies on a separate distribution of kubelet itself on CoreOS's quay.io account. On a few occasions I've tried it, the version of k8s I was trying to use had not yet been packaged and released, and I only found this out when I brought up a new cluster and everything failed because it couldn't download the kubelet. I don't think it's a reasonable compromise to add a custom distribution of kubelet to my dependency chain, even though it is of course my choice to use CoreOS in the first place. Sure, there could be improvements to CoreOS's release process to make sure new versions of the kubelet get there faster, but either way, it's another thing that can break that just doesn't need to be there.

One of the main points of containers (at least as they've been sold since the initial Docker hype) is that you no longer have to worry about system dependencies, because applications have everything they need packaged along with them. I think the best way forward is for the official kubelet image to either package system-level dependencies along with itself, or have a mechanism to download and run separate images containing the tools it needs via whatever container runtime the user selects. Any additional images needed by kubelet should also be maintained on gcr.io and be included as part of the k8s release process.

**Comment by pires** [comment]
Using something else than the pure `kubelet` also bothers me. I'm left wondering why stuff like `socat` is stripped from CoreOS.

**Comment by crawford** [comment]
CoreOS is meant to be a lightweight distribution with a smaller-than-average attack surface. We very intentionally do not ship a lot of tools in the OS (e.g. python, ruby, socat, file, bc, qemu), with the intent that applications bring specific versions of their dependencies. We expect the kubelet/hyperkube/whatever container image to bring along its dependencies, which is one of the reasons we maintain our own kubelet container image.

@pires Using something other than the "pure kubelet" really shouldn't bother you (as long as you can see what modifications have been made). Distributions historically ship patches on top of the software they package. CoreOS ships a modified GRUB and kernel. The `hostname` utility you use on Ubuntu is patched. Docker on RHEL carries roughly thirty patches. This is standard practice and is done to ensure that these tools work properly in these specific environments.

**Comment by jimmycuadra** [comment]
Fair points @crawford, and thanks for the additional context. As it applies to this issue, it still seems like the the official kubelet release needs a better story around packaging its dependencies with it in some way. There may be more tweaks that CoreOS has made to the distro-provided kubelet image, but the changes we're talking about would benefit any theoretical system with similar properties, and as stable as these networking tools are, it's probably a good idea to lock down specific versions of them that have been shown to work with the kubelet in e2e tests.

**Comment by ncdc** [comment]
One option for socat in particular (which would likely apply to most/all other external kubelet executable dependencies) is to add it to the pause container. I'm actually going to look at doing that as a part of #25113

**Comment by euank** [comment]
I'd like to provide a little more context to your comments about kubelet, dependencies, and the CoreOS kubelet-wrapper, @jimmycuadra.

> ... relies on a separate distribution of kubelet itself on CoreOS's quay.io account

First of all, the work of packaging dependencies with kubelet is being done with the [hyperkube image](https://github.com/kubernetes/kubernetes/blob/42a1deeff381518a97eae6293fbf0d89b3b630ee/cluster/images/hyperkube/).

It is true that we have our own package/distribution of this, but it's based on the same upstream work and we're working to unify them further so that we don't have to carry any patches on top of that hyperkube image. Right now I believe that if you make only small modifications to the kubelet wrapper, you can use your own build of that upstream image, or the copy Google hosts for the kubernetes project.

Being able to decouple our release has helped us by allowing us to validate it works with CoreOS (testing in that environment specifically) and carrying patches as needed to improve that experience, but the long-term goal here is not to carry our own fork but to make the upstream image work on CoreOS (and everywhere).

>  I think the best way forward is for the official kubelet image to either package system-level dependencies along with itself

That is what the above image is working towards and already mostly accomplishes! We'll continue to try and make it better.

There's additional complexities like the fact that there are N ways to run kubelet, which is why I agree shipping socat in the pause image can be worthwhile by solving the problem a layer up, but for CoreOS the way we think it should be solved is exactly that, an official kubelet image which encapsulates dependencies appropriately.

**Comment by jimmycuadra** [comment]
Sounds like we're all on the same page then. :} Thanks for the details, @euank!

**Comment by xynova** [comment]
@jimmycuadra This is what i did to get socat in coreOS. Wether it is good or not.. many shades of gray

```


# Make socat directories
mkdir -p /opt/bin/socat.d/bin /opt/bin/socat.d/lib

# Create socat wrapper
cat << EOF > /opt/bin/socat
#! /bin/bash
PATH=/usr/bin:/bin:/usr/sbin:/sbin:/opt/bin
LD_LIBRARY_PATH=/opt/bin/socat.d/lib:$LD_LIBRARY_PATH exec /opt/bin/socat.d/bin/socat "\$@"
EOF

chmod +x /opt/bin/socat

# Get socat and libraries from the CoreOS toolbox 
toolbox
dnf install -y socat
cp -f /usr/bin/socat /media/root/opt/bin/socat.d/bin/socat
cp -f /usr/lib64/libssl.so.1.0.2h /media/root/opt/bin/socat.d/lib/libssl.so.10
cp -f /usr/lib64/libcrypto.so.1.0.2h /media/root/opt/bin/socat.d/lib/libcrypto.so.10
```


# Then tell the kubelet to consider binaries in the /opt/bin directory .. maybe changing it to a socat specific isolated one is better

### /etc/systemd/system/kubelet.service

###	[Unit]
###	Description=Kubernetes Kubelet Master
###	Documentation=http://kubernetes.io/docs/admin/kubelet

###	[Service]
###	ExecStartPre=/usr/bin/mkdir -p /etc/kubernetes/manifests
###	ExecStartPre=/usr/bin/mkdir -p /etc/cni/net.d
###	ExecStartPre=/usr/bin/mkdir -p /opt/cni/bin
###	Environment="PATH=/opt/bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
###	...

**Comment by xynova** [comment]
@jimmycuadra This is what i did to get socat in coreOS. Wether it is good or not.. many shades of gray

```


# Make socat directories
mkdir -p /opt/bin/socat.d/bin /opt/bin/socat.d/lib

# Create socat wrapper
cat << EOF > /opt/bin/socat
#! /bin/bash
PATH=/usr/bin:/bin:/usr/sbin:/sbin:/opt/bin
LD_LIBRARY_PATH=/opt/bin/socat.d/lib:$LD_LIBRARY_PATH exec /opt/bin/socat.d/bin/socat "\$@"
EOF

chmod +x /opt/bin/socat

# Get socat and libraries from the CoreOS toolbox 
toolbox
dnf install -y socat
cp -f /usr/bin/socat /media/root/opt/bin/socat.d/bin/socat
cp -f /usr/lib64/libssl.so.1.0.2h /media/root/opt/bin/socat.d/lib/libssl.so.10
cp -f /usr/lib64/libcrypto.so.1.0.2h /media/root/opt/bin/socat.d/lib/libcrypto.so.10
```


# Then tell the kubelet to consider binaries in the /opt/bin directory .. maybe changing it to a socat specific isolated one is better

```
# Tell the kubelet to consider binaries in the /opt/bin directory .. or maybe a specific socat one
# /etc/systemd/system/kubelet.service

# [Unit]
# Description=Kubernetes Kubelet Master
# Documentation=http://kubernetes.io/docs/admin/kubelet

# [Service]
# ExecStartPre=/usr/bin/mkdir -p /etc/kubernetes/manifests
# ExecStartPre=/usr/bin/mkdir -p /etc/cni/net.d
# ExecStartPre=/usr/bin/mkdir -p /opt/cni/bin
# Environment="PATH=/opt/bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
# ...
```

**Comment by philips** [comment]
@xynova please please please use kubelet-wrapper https://coreos.com/kubernetes/docs/latest/kubelet-wrapper.html

**Comment by xynova** [comment]
I am totally in favour of the idea @philips but I have a couple of inconveniences with it at this present moment:

- I'm in Australia and unfortunately the connectivity to quay.io is a bit flaky with some internet providers (for some reason sometimes get timeouts or it is very slow)
- It would be nice if the wrapper could download only the kubelet instead of the hyperkube. Again.. internet speeds are pretty poor around here and a few MB less would help a lot.
- It would be nice also for those ACIs to be also in GCE which is pretty good in those download speeds.

**Comment by pires** [comment]
Quay.io should move to GCP.  However, I agree with having one (optional) image per component.
