### ISSUE TITLE
Add support for OpenStack LBaaS v2

### ISSUE THREAD

**Issue by jgriffiths1993** [kubernetes/kubernetes#19774]
LBaaS v2 for OpenStack adds some *very* necessary features such as multiple ports on one VIP and TLS termination.

We should add support for this in the OpenStack cloud driver.

The necessary interfaces are not yet in the gophercloud library. I'm working on putting them in and, once they're merged, we can add this driver in kubernetes.

**Comment by bprashanth** [comment]
From their homepage:

>  The long-term vision for the project, however, is to provide a single API that allows a user to seamlessly move between different load balancing technologies should the operator choose to do so. 

This is what Ingress was created for, so we should streamline if possible. Here is some documentation: https://github.com/kubernetes/kubernetes/blob/release-1.1/docs/user-guide/ingress.md, existing backends: https://github.com/kubernetes/contrib/tree/master/Ingress, tls discussion: https://github.com/kubernetes/kubernetes/issues/19497. 

This is an example of Ingress implemented as service annoations; I'm mentioning it because it might be easier to start doing something like this if LBaaS already works with services: https://github.com/kubernetes/contrib/tree/master/service-loadbalancer 

https://github.com/kubernetes/contrib/issues/346 is a sketch for AWS ingress that describes the gce backend. 

Feel free to rope me into issues/discussions/prs etc.

**Comment by bprashanth** [comment]
@thockin who was asking about ingress and openstack recently

**Comment by vipulsabhaya** [comment]
Can we add support for LBaaSv2 to the existing cloud driver? I agree the long term answer is likely Ingress, but until we have an actual deprecation plan for service-type=lb, we should not block progress here.

**Comment by sputnik13** [comment]
@bprashanth @thockin we're working to get LBaaSv2 support in ASAP, and upstream work for gophercloud is up for review at https://github.com/rackspace/gophercloud/pull/575, we would prefer to do service-type=lb for now given the existing code for LBaaSv1 in the Openstack CPI unless there's some reason such a change wouldn't be accepted by the kubernetes project.

**Comment by bprashanth** [comment]
Do what works best we can fiddle with the details later. The hard part is getting it to work :)

**Comment by dagnello** [comment]
@bprashanth k8 PR is out, but waiting for my Gophercloud PR to merge first :)
