### ISSUE TITLE
kubectl run --command not work

### ISSUE THREAD

**Issue by sharpevo** [kubernetes/kubernetes#19788]
Hi all, 

I know I should not ask this question here, but all the following codes failed to run the specific command:
- `kubectl run NAME --image=IMAGE --overrides='{...}' --command -- 'cmd -a1 -a2'`
- `kubectl run NAME --image=IMAGE --overrides='{...}' --command -- cmd -a1 -a2`
- `kubectl run NAME --image=IMAGE --overrides='{...}' --command 'cmd -a1 -a2'`
- `kubectl run NAME --image=IMAGE --overrides='{...}' -- 'cmd -a1 -a2'`
- `kubectl run NAME --image=IMAGE --overrides='{...}' -- cmd -a1 -a2`
- `kubectl run NAME --image=IMAGE --overrides='{... "commands":["cmd", "a1", "a2"], ...}'`

and I found that 'restartPolicy' is useless in overrides, so the `overrides` will be overwritten by the `kubectl --restart` argumets?

**Comment by alex-mohr** [comment]
Please re-post your question to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes). 

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases. 

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to similar questions, and also familiarize yourself with:
   * [the user guide](http://kubernetes.io/v1.0/)
   * [the troubleshooting guide](http://kubernetes.io/v1.0/docs/troubleshooting.html)

Again, thanks for using Kubernetes.

The Kubernetes Team
