### ISSUE TITLE
Kubernetes on Ubuntu hava a problem "NUM_NODES: unbound variable", how to slove it ?

### ISSUE THREAD

**Issue by minxinping0105** [kubernetes/kubernetes#19814]
root@ubuntu:/kubernetes# KUBERNETES_PROVIDER=root ../kube-up.sh
... Starting cluster using provider: root
... calling verify-prereqs
TODO: verify-prereqs
... calling kube-up
TODO: kube-up
... calling validate-cluster
../../cluster/../cluster/validate-cluster.sh: line 32: NUM_NODES: unbound variable

**Comment by AdoHe** [comment]
@minxinping0105 what kind of your kubernetes version?

**Comment by dalanlan** [comment]
@minxinping0105 Try `$ KUBERNETES_PROVIDER=ubuntu` instead. Also you might have problems when you have wrong CWD. Please stick to the doc.

**Comment by alex-mohr** [comment]
Please re-post your question to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes). 

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases. 

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to similar questions, and also familiarize yourself with:
   * [the user guide](http://kubernetes.io/v1.0/)
   * [the troubleshooting guide](http://kubernetes.io/v1.0/docs/troubleshooting.html)

Again, thanks for using Kubernetes.

The Kubernetes Team
