### ISSUE TITLE
Kubernetes pods hung at the status of Terminating

### ISSUE THREAD

**Issue by ztao1987** [kubernetes/kubernetes#19811]
I deployed zookeeper pods using replication controller. When I deleted the replication controller, the zookeeper pods hang at the status of Terminating. My kube version is v1.1.1. Even if I shutdown all the minion nodes, the status of zookeeper pods is still Terminating. Currently I have the environment available. Could you please kindly advice what kind of debug info I need to provide?

core@master ~ $ kubectl get pods
NAME                READY     STATUS        RESTARTS   AGE
zookeeper-1-s68t0   1/1       Terminating   0          22h
zookeeper-2-ygxqu   1/1       Terminating   0          22h
zookeeper-3-i7yj8   1/1       Terminating   0          22h
core@master ~ $ kubectl describe pods zookeeper-1-s68t0
Name:				zookeeper-1-s68t0
Namespace:			default
Image(s):			172.31.41.68:5000/zookeeper-cn:latest
Node:				ip-172-31-14-119.us-west-2.compute.internal/172.31.14.119
Start Time:			Fri, 15 Jan 2016 13:49:13 +0000
Labels:				app=zookeeper,server-id=1
Status:				Terminating (expires Fri, 15 Jan 2016 14:06:21 +0000)
Termination Grace Period:	30s
Reason:
Message:
IP:				10.20.95.4
Replication Controllers:	<none>
Containers:
  zkserver:
    Container ID:	docker://c787611ceb42327683ced41b05055048dfbc20d8c4ed667dcf3dac9147b31a04
    Image:		172.31.41.68:5000/zookeeper-cn:latest
    Image ID:		docker://49341992e848376d9f7aa7e569300eccc80b35d895335885750f8528f8a5240f
    State:		Running
      Started:		Fri, 15 Jan 2016 13:49:29 +0000
    Ready:		True
    Restart Count:	0
    Environment Variables:
      MYID:	1
      SERVERS:	10.100.225.50,10.100.12.152,10.100.12.8
Conditions:
  Type		Status
  Ready 	True
Volumes:
  data:
    Type:	EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
  wal:
    Type:	EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:	Memory
No events.

**Comment by AdoHe** [comment]
@ztao1987 Can you try to restart all your kubelet processes on minion nodes and see the pod status?

**Comment by ztao1987** [comment]
@AdoHe  unfortunately I have stopped the minion nodes, only master node exist now. Is there any other workaround?

**Comment by alex-mohr** [comment]
Please re-post your question to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes). 

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases. 

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to similar questions, and also familiarize yourself with:
   * [the user guide](http://kubernetes.io/v1.0/)
   * [the troubleshooting guide](http://kubernetes.io/v1.0/docs/troubleshooting.html)

Again, thanks for using Kubernetes.

The Kubernetes Team

**Comment by zongyimin** [comment]
@alex-mohr  @AdoHe  unfortunately, I have the same question. and  when I deleted the replication controller and the docker. the status of related pods is still Terminating.

**Comment by qianlifu12345** [comment]
Is there any solution?
