### ISSUE TITLE
Use ConfigMap for cluster-config

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#19831]
We have a lot of params that we use salt or other provisioning to plumb from top-level configs down to flags (kubelet, kube-proxy, controller-manager, etc).

Now that ConfigMap is pretty much in, we should start to spec out how we can use it to carry that same information instead of flags.

@mikedanese @justinsb

**Comment by mikedanese** [comment]
Once we finish moving components to [componentconfig API group](https://github.com/kubernetes/kubernetes/tree/master/pkg/apis/componentconfig) this should just be salt changes.

**Comment by thockin** [comment]
note, I am not just talking about per-component flags, but some flags are
truly cluster-wide, and we should model that.

**Comment by mikedanese** [comment]
Ahh okay.

**Comment by xinxiaogang** [comment]
Is `ConfigMap` a open source config management tool? Can you provide more information about `ConfigMap` ?

**Comment by thockin** [comment]
ConfigMap is a new structure in our API that can be watched or can be
projected into files via a volume.

**Comment by bgrant0607** [comment]
This is a dupe of #1627

**Comment by bgrant0607** [comment]
Unless the issue is really about factoring out common config from the individual components.

**Comment by thockin** [comment]
yes - extracting CLUSTER config that is no one component.

**Comment by philips** [comment]
A use case I have for a cluster ConfigMap:

A machine generated random number called "cluster-id" that can be used to uniquely identify a cluster instance permanently. The idea is that this number could be used in logs, backups, ubernetes, etc. It is a similar idea to the `/etc/machine-id` on Linux.

Today we have the name and DNS name of the servers but I think that this is insufficient because these things are easy for human beings to misconfigure and create duplicates or inconsistencies. Having this will make debugging Kubernetes easier in scenarios like: API servers behind a load balancer backed by different etcd storage, debugging issues where a user has local vs remote DNS inconsistency causing confusion, finding misconfigurations in ubernetes, etc.

The initial UX I would want would be something like:

```
$ kubectl cluster-info
Kubernetes cluster-id is aecha83d
Kubernetes master is running at https://172.17.4.99:443
```

The data points I have that this sort of machine unique metadata is useful is in both etcd and CoreOS Linux.

It might also be desirable to have `.kube/config` take a cluster-id and send that an `Kubernetes-Cluster-Id` header in requests. If there is a mismatch the call fails. It would be a nice safety measure, again, against misconfiguration of DNS/load-balancer.

**Comment by bgrant0607** [comment]
We should also think about what settings would make sense as part of a cluster API. Not every knob certainly, and not details that are needed to just wire components together. But semantically meaningful configuration of the cluster. The cluster name might be the first example, but I could imagine others. 

Of course, we'd need to decide which settings belong in the monolithic cluster-scope API vs having their own APIs. For instance, maybe the default node eviction timeout would belong in a NodePolicy API that would control default node settings for nodes matching a label selector, similar to #17097 but for nodes rather than pods.

**Comment by bgrant0607** [comment]
https://github.com/kubernetes/community/blob/master/contributors/design-proposals/runtimeconfig.md

**Comment by mtaufen** [comment]
@bgrant0607 Was that implemented as --feature-config in the proposed components? The --feature-gates mechanism on the Kubelet is eerily similar to that proposal, modulo use of a ConfigMap.

**Comment by neolit123** [comment]
(2020 refresh) cluster-lifecycle tools like kubeadm and CAPI do use config maps for storage of component config.
if other components need related extensions, we can assign the individual component-owning SIGSs.

/remove-sig cluster-lifecycle

**Comment by ehashman** [comment]
/remove-lifecycle frozen

I was going to put SIG Cluster Lifecycle on here but seems @neolit123 has removed it. Is there anything left to do? I think this can perhaps be closed.
