### ISSUE TITLE
salt minion authentication problem

### ISSUE THREAD

**Issue by danielschonfeld** [kubernetes/kubernetes#19845]
Sometimes when my noes come up on my autoscaling group, the master ends up with a public key for the minion which seems to not match what the minion has.  I assume the minion creates a key twice and only the first one gets put on the master on the initial contact but I can't be sure that's what's happening.

The fix is to remove the key from the `/etc/salt/pki/master/minions/` directory and start the `salt-minion` service on the minion again.

Can anyone point me in the right direction to debug this further? why would this happen?

OS: `Ubuntu 14.04 LTS (trusty)` Cloud: `AWS` Kubernetes: `v1.1.3`

**Comment by alex-mohr** [comment]
Please re-post your question to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes). 

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases. 

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to similar questions, and also familiarize yourself with:
   * [the user guide](http://kubernetes.io/v1.0/)
   * [the troubleshooting guide](http://kubernetes.io/v1.0/docs/troubleshooting.html)

Again, thanks for using Kubernetes.

The Kubernetes Team

**Comment by danielschonfeld** [comment]
I could be wrong but i don't think this is 'my' problem, I believe it's a bug in the images we use.

This doesn't happen all the time because of some poor configuration I've made, it happens infrequently and with mostly the stock configuration that comes out from the `kube-up` script.

cc @alex-mohr

**Comment by alex-mohr** [comment]
@danielschonfeld Ah, I see.  Thanks for the clarification and apologies for misreading it.  I think @roberthbailey has cert context, though he's out for the weekend.

It's quite possible that the salt config isn't sufficiently idempotent -- it should create only 1 key and use that forever rather than creating 2 keys.  Flagging team/control-plane as they nominally own.

**Comment by danielschonfeld** [comment]
@alex-mohr if i had to guess from my observations, i'd say salt-minion starts up once, sends something to the master which includes the initial public key and then somehow restarts with a clean /etc/salt and recreates a new key... only this time when it tries to contact master, the master already has a key for it so everything blows up.

I don't know enough about salt to debug this, but if you or @roberthbailey can point me in the right direction I can try to find some of history in our nodes that did that.

Thanks!

**Comment by alex-mohr** [comment]
Re: salt, sadly I don't either.

**Comment by roberthbailey** [comment]
@danielschonfeld I'll take a look on Monday when I'm back in the office.

**Comment by danielschonfeld** [comment]
thanks @roberthbailey

**Comment by roberthbailey** [comment]
@danielschonfeld -- I just read through your issue and this seems to be a problem specific to the AWS configuration. On other platforms (e.g. GCE / GKE) we use masterless salt (e.g. there is no salt master and no communication between nodes as part of the salt configuration). Instead, we generate certificates on the developer machine and push them out to all of the nodes. 

I'm going to assign to @justinsb since he's been working on the AWS salt configuration. 

/cc @brendandburns for good measure as well.
