### ISSUE TITLE
Don't allow updates of Node.PodCIDR except from "" to valid.

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#19854]
As we move closer to using a net plugin for the default network, this came up.  Is Node.PodCIDR actually mutable?  What do we expect to happen if it changes for a Node which has running containers?

Options: 
a) allow updates and kill running containers (heavy)
b) allow updates but ignore them as long as any containers are running (inconsistent)
c) allow updates but ignore them except at reboot (inconsistent)
d) only allow updates from "" to valid CIDR (presumably by node controller)
e) don't allow updates (breaks nodecontroller)
f) only allow updates by a sub-resource, and choose one of a-d

Of all of these, I think (d) is the only sane and halfway reasonable option right now.  Longer term, we need to reconsider the role of this field in a more pluggable world.

@dcbw @bprashanth @dchen1107 @bgrant0607

**Comment by mqliang** [comment]
I sent a PR about 2 weeks ago to add a CIDR allocator for NodeController(which can allow Node.PodCIDR not /24), see https://github.com/kubernetes/kubernetes/pull/19242.

**Comment by bprashanth** [comment]
If an admin has some reason to re-allocate all cidrs I think should respect that. As a totally made-up scenario, one can actually write a cidr controller that doesn't waste any ip range on node-label=backup and re-allocates as necessary.

**Comment by thockin** [comment]
But what should happen to running containers?

**Comment by bprashanth** [comment]
In the backup node case there will only be win, the old node is dead so nothing is using that range. Even otherwise isn't it safe to assume that if the admin asks for a new range, they are OK with the consequences?

**Comment by thockin** [comment]
We have to define what those consequences are before we can assume people
are OK with it.  Remember, too, that we have to implement and test this.

If the consequence is "kill all the containers" is it really any worse than
draining the node and destroying/recreating it?

**Comment by alex-mohr** [comment]
From the peanut gallery, seems like something we shouldn't spend much time on vs. e.g. ipvlan support.

**Comment by alex-mohr** [comment]
From the peanut gallery, seems like something we shouldn't spend much time on vs. e.g. ipvlan support.

**Comment by thockin** [comment]
I agree that this doesn't warrant deep engineering, which is why I like (d).

**Comment by alex-mohr** [comment]
+1 to (d).

**Comment by bgrant0607** [comment]
(d) SGTM

**Comment by feiskyer** [comment]
+1 to (d)

**Comment by dcbw** [comment]
I also vote for (d).

Currently, the only cases that are acceptable handled appear to be "" -> valid CIDR, and the existing cbr0 code will blow away the bridge entirely on PodCIDR change which will leave all the existing pods dangling.  So it doesn't work now either.

**Comment by thockin** [comment]
So say we all.  Now someone needs to implement that.  Updating this bug topic.

**Comment by thockin** [comment]
This is a good one for someone from community to jump in on.  Should be pretty simple.

**Comment by therc** [comment]
On a related note, what's the story with stand-alone mode? https://github.com/kubernetes/kubernetes/blob/master/docs/admin/high-availability.md and, in particular, https://github.com/kubernetes/kubernetes/blob/master/docs/admin/high-availability/default-kubelet tell people to use `--configure-cbr0=true`.
But that results in
`kubelet.go:2294] skipping pod synchronization - [ConfigureCBR0 requested, but PodCIDR not set. Will not configure CBR0 right now]`
What happens when the kubelet is started with --pod-cidr, before an API server is running, since we're using the kubelet to bootstrap it? Should that CIDR be treated in a special way, e.g. preventing future nodes to ever use if the bootstrap kubelet is temporarily unreachable?

**Comment by dcbw** [comment]
In standalone mode (eg, no apiserver is given) then you need to set --pod-cidr=x.x.x.x/y explicitly if you are also using --configure-cbr0.  Otherwise kubelet has no idea what address to configure on the bridge.

**Comment by dcbw** [comment]
StandaloneMode:                 (len(s.APIServerList) == 0),

**Comment by therc** [comment]
I guess the advice to use cbr0 for a bootstrapping kubelet that points to no apiserver doesn't make a lot of sense: if you start an apiserver that way, it should use host networking. But then you might still want to run DaemonSets for monitoring and log forwarding, in which case using a pod CIDR *and* talking to a bunch of API servers (since we're talking about HA) becomes desirable. It's not clear if that's a suggested or supported setup, though.

**Comment by therc** [comment]
(You can also set the node to schedulable=false, in which case regular pods can't run on the master nodes, but DaemonSets still can.)

**Comment by fiorix** [comment]
While playing with a 3 node cluster I misconfigured one my nodes CIDR using kubectl patch, and now I cannot change it back. What to do now?

**Comment by thockin** [comment]
You can delete the node and recreate it, I think.  This should force pods
on the node to be evicted (not sure if it does).
