### ISSUE TITLE
GCE L7 x nodeport services can black hole traffic

### ISSUE THREAD

**Issue by aronchick** [kubernetes/kubernetes#19927]
From a user:

The single worst experience we’ve had so far is from the loadbalancer:
The official loadbalancer abstraction (“ingress”) is not there yet (no reserved ip addresses). We therefore use a Service (with Nodeport) and configure a HTTPLoadbalancer with the nodeport as a backend.

When we take down a Node there are two error-sources:
a) The NodePort on the terminated Node goes down
b) A faulty pod (A Pods on the terminated Node)

The NodePort round-robins requests to all Pods. All Nodes will eventually get a faulty response. Therefore the Loadbalancer will mark the whole cluster as faulty.

**Comment by thockin** [comment]
@bprashanth for comment and triage

**Comment by bprashanth** [comment]
> The official loadbalancer abstraction (“ingress”) is not there yet (no reserved ip addresses). 

Can I get a more specific request? do they just want static ips, to re-use ips across cluster create/destroy, reserve just an IP and defer url configuration to a later stage, or something else?

> When we take down a Node there are two error-sources:
a) The NodePort on the terminated Node goes down
b) A faulty pod (A Pods on the terminated Node)
The NodePort round-robins requests to all Pods. All Nodes will eventually get a faulty response. Therefore the Loadbalancer will mark the whole cluster as faulty.

There are multiple failure scenarios we don't handle because of our reliance on node port services:

1. If the pod readiness probe doesn't match the L7 health check endpoint: Kubernetes will keep sending traffic to that endpoint, even if the L7 blacklists the node for failed healthcheck. This isn't too bad if we accept the Kubernetes probe as a source of truth. 

2. If a single node falls off the network: This is the classic netsplit case. The node controller should delete all endpoints on the node in 5 minutes, after which the nodePort service shouldn't be sending traffic to that node or its endpoints. If I've understood the situation correctly, they might face trouble in < 5m. We recently had a fix that would mark pods on unresponsive nodes as not ready (https://github.com/kubernetes/kubernetes/pull/17741). This will decrease the trouble window to 40s. 

3.  All nodes are cut-off from the master: Traffic might get blackholed. The system is designed to continue working in this case, but the L7 doesn't have any visibility into what endpoints are healthy, and the kubelets cannot communicate probe failures to each other.

4. 2 nodes are partitioned from each other, or the nodeport is hosed (I mean port :30001 or whatever is not accepting traffic because of, say, a firewall rule), or the L7 is unable to contact nodes: Traffic might get black holed. The problem is that as long as the kubelet can talk to the master, and pods on the node are responding to http health checks from localhost, we assume everythings fine. But nodeport services need cross host connectivity, and nodeport services used in L7 require cross host __and__ L7 connectivity (so from the 130.211/22 range). Kubernetes is unaware of partitions along those planes.

There are many known issues on the table which when solved will make this problem less hairy. The idea of "service health" has also crossed my mind.

**Comment by tback** [comment]
Thanks for the input. We’ll have to do some homework in “pod readiness domain” - point one on your list @bprashanth

>> The official loadbalancer abstraction (“ingress”) is not there yet (no reserved ip addresses).

> Can I get a more specific request? do they just want static ips, to re-use ips across cluster create/destroy, reserve just an IP and defer url configuration to a later stage, or something else?

To use GCE L7 through ingress we need a reserved IP address and HTTPS so we can point a DNS Record to said IP. 
It was my impression that could reserve an IP Address manually through the networking section in GCE.

(I am the user)

**Comment by bprashanth** [comment]
@tback great, good I found you :)

> It was my impression that I could reserve an IP Address manually through the networking section in GCE, so reservation an deferred configuration was not on our list of things we need.

In 1.2 we will have https support. This will create a http forwarding rule pointing to a target http proxy, promote the ephemeral IP to a static ip, and create another forwarding rule-> target httpS proxy. Is that enough? This way you can first create the Ingress with a tls section (https://github.com/kubernetes/kubernetes/pull/20142), wait for it to get a static ip and put that in DNS.

**Comment by wstrange** [comment]
Is that static IP going to change every time the ingress is deleted and recreated? 

I' d like to explicitly set the IP of the ingress myself- rather than have it done automatically

**Comment by bprashanth** [comment]
You can, soon, but it's not in 0.6.0. It will be through an annotation: https://github.com/kubernetes/contrib/blob/d9063241280cedfaac23a2283f6584e747aa2302/ingress/controllers/gce/controller/utils.go#L39


> Is that static IP going to change every time the ingress is deleted and recreated?
yes

**Comment by thockin** [comment]
I'm curious why you would delete and recreate an Ingress?

**Comment by wstrange** [comment]
I think it is more if you have reserved your own static IP, and set up DNS, etc. - you want the ingress to use that IP - not one it chooses.  For testing., etc. - you might not want to run an ingress 7x24.

It sounds like that will be possible via an annotation in a future release - so that should cover it.

**Comment by thockin** [comment]
That's a more realistic use case - I just wanted to understand.

**Comment by cmluciano** [comment]
/unassign @bprashanth 

@thockin I noted a PR removing bprashanth from OWNERS files. I think we need another owner here from the gce team

**Comment by cmluciano** [comment]
@kubernetes/sig-gcp-feature-requests is this still valid?
