### ISSUE TITLE
Can't connect to a service IP from the service's pod

### ISSUE THREAD

**Issue by virsox** [kubernetes/kubernetes#19930]
I'm trying to create 3 instances of Kafka and deploy it a local Kubernetes setup. Because each instance needs some specific configuration, I'm creating one RC and one service for each - eagerly waiting for #18016 ;)

However, I'm having problems because Kafka can't establish a network connection to itself when it uses the service IP (a Kafka broker tries to do this when it is exchanging replication messages with  other brokers). For example, let's say I have two worker hosts (`172.17.8.201` and `172.17.8.202`) and my pods are scheduled like this:

- Host 1 (`172.17.8.201`)
kafka1 pod (`10.2.16.1`)

- Host 2 (`172.17.8.202`)
kafka2 pod (`10.2.68.1`)
kafka3 pod (`10.2.68.2`)

In addition, let's say I have the following service IPs:

- kafka1 cluster IP: `11.1.2.96`
- kafka2 cluster IP: `11.1.2.120`
- kafka3 cluster IP: `11.1.2.123`

The problem happens when the kafka1 pod (container) tries to send a message (to itself) using the kafka1 cluster IP (`11.1.2.96`). For some reason, the connection cannot established and the message is not sent.

Some more information: If I manually connect to the kafka1 pod, I can correctly telnet to kafka2 and kafka3 pods using their respective cluster IPs (`11.1.2.120` / `11.1.2.123`). Also, if I'm in the kafka2 pod, I connect to both kafka1 and kafka3 pods using `11.1.2.96` and `11.1.2.123`. Finally, I can connect to all pods (from all pods) if I use the pod IPs.

It is important to emphasize that I shouldn't tell the kafka brokers to use the pod IPs instead of the cluster IPs for replication. As it is right now, Kafka uses for replication whatever IP you configure to be "advertised" - which is the IP that your client uses to connect to the brokers. Even if I could, I believe this problem may appear with other software as well.

This problem seems to be specific to my setup, because the exact same files work correctly in GCE.
Right now, I'm running:

- Kubernetes 1.1.2
- coreos 928.0.0
- network setup with flannel

I'm not sure if the problem is in the workers iptables rules, in kube-proxy, or in flannel. Let me know if I can provide with some more debugging information.

**Comment by alex-mohr** [comment]
Please re-post your question to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes). 

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases. 

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to similar questions, and also familiarize yourself with:
   * [the user guide](http://kubernetes.io/v1.0/)
   * [the troubleshooting guide](http://kubernetes.io/v1.0/docs/troubleshooting.html)

Again, thanks for using Kubernetes.

The Kubernetes Team

**Comment by thockin** [comment]
Please @ me if you open this on SO.  This is supposed to work.

**Comment by virsox** [comment]
@thockin thanks for your attention. I opened a thread on SO:

http://stackoverflow.com/questions/34937184/kubernetes-cant-connect-to-a-service-ip-from-the-services-pod

I believe it is some sort of bug. I'm willing to help to debug and with some guidance I can also work on a fix.

**Comment by harryge00** [comment]
@virsox

I have a similar problem when creating MongoDB cluster. For example:

* Host 1 (172.17.8.201)
Mongo1 pod (10.2.16.1)

* Host 2 (172.17.8.202)
Mongo2 pod (10.2.68.1)

* Host 3 (172.17.8.203)
Mongo3 pod (10.2.69.1)

Service IP:
* Mongo1 cluster IP: 11.1.2.96
* Mongo2 cluster IP: 11.1.2.120
* Mongo3 cluster IP: 11.1.2.123

My Mongo1 can connect to Mongo2, Mongo3 via cluster IP, but cannot access itself via cluster IP!
My Mongo2  can connect to Mongo3, Mongo1 via cluster IP, but cannot access itself via cluster IP!
But when using pod IP, all Mongo nodes can connect to each other. 

Has the bug been solved?

**Comment by thockin** [comment]
What instructions are you following for setup?  What cloud?  What
networking setup?  What flags to kubelet and kube-proxy?

**Comment by virsox** [comment]
@harryge00 for my case, I'm pretty sure the problem was caused by the bug #20391 - the bug refers exactly to my setup. For your case, you may need to answer @thockin questions first.
