### ISSUE TITLE
RESTMapper doesn't support the same 

### ISSUE THREAD

**Issue by piosz** [kubernetes/kubernetes#19941]
I created #19820 which adds to `metrics` api group types `Pod` and `Node` (which already exists in the default api group). Please correct me if I'm wrong but this case should be supported. Unfortunately when testing the mentioned change kubectl returns the following error:
```
error: unable to get RESTClient for resource 'nodes'
```
The problem is with [MultiRESTMapper](https://github.com/kubernetes/kubernetes/blob/master/pkg/api/meta/restmapper.go#L509) which iterates over mappers in arbitrary order.

Assigning @lavalamp for triage.

cc @kubernetes/goog-csi

**Comment by lavalamp** [comment]
Yes, I think this is a bug. We should use a deterministic search order and it should search "/v1" before other groups.

**Comment by lavalamp** [comment]
@caesarxuchao @krousey

**Comment by piosz** [comment]
It will be just a temporary fix, until someone wants to have 2 types with the same name within two different API groups which different than `/v1`. Does anyone from CSI team plan to work on it? I can do it.

**Comment by lavalamp** [comment]
We'd be happy for you to do it :)

**Comment by bgrant0607** [comment]
cc @madhusudancs

**Comment by bgrant0607** [comment]
horizontalpodautoscalers and jobs will have the same problem once they move to new API groups.

Was encountered as part of #20501

cc @janetkuo @erictune

**Comment by liggitt** [comment]
cc @deads2k

**Comment by deads2k** [comment]
I don't think that we want to pick winners and losers based on compiled in choices about order.  I would rather see something like ordering based on the discovery endpoint like @smarterclayton mentioned in https://github.com/kubernetes/kubernetes/issues/20293.

I've also found a few bugs in this area when we rebased Origin on it that may affect you.  The most pertinent are:
 1. https://github.com/kubernetes/kubernetes/pull/20829 - properly runs a check against all sub-RESTMappers to union all results
 2. https://github.com/kubernetes/kubernetes/pull/20846 - which provides most to least preferred ordering back from the groupversion registry so that you'll be properly order
 3. https://github.com/kubernetes/kubernetes/pull/20968 - which fixes the partial resource match for singular names

**Comment by lavalamp** [comment]
In our SIG meeting we discussed searching the discovery information *in the order apiserver delivers it*.

**Comment by piosz** [comment]
Sorry, I won't be able to fix this until the end of next week, so leaving unassigned.

**Comment by lavalamp** [comment]
@deads2k I think your PR will address this, right?

**Comment by deads2k** [comment]
> @deads2k I think your PR will address this, right?

Yes, with a hardcoded order for now built on types that could accept discovery based order post-1.2.

**Comment by piosz** [comment]
Reopened due to https://github.com/kubernetes/kubernetes/issues/22484#issuecomment-192261836

**Comment by liggitt** [comment]
Not a RestMapper issue according to https://github.com/kubernetes/kubernetes/issues/22484#issuecomment-192278990 ?

**Comment by piosz** [comment]
Closing as described in https://github.com/kubernetes/kubernetes/issues/22484#issuecomment-192287988
