### ISSUE TITLE
Nodecontroller reassigns CIDR of first node on restart

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#20048]
If the node controller ever restarts (like we do periodically in the daemon restart test, https://github.com/kubernetes/kubernetes/issues/19023) it will reassign the CIDR of the first node. This can cause all sorts of problems like docker and container restart, pod phase changing etc. 

This code seems to be at fault:
https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/node/nodecontroller.go#L545

I feel like I'm missing some context here, which is why I haven't uploaded a pr. 
We don't generate available cidrs before checking that the first node is in the set (https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/node/nodecontroller.go#L550). But then break out of the loop to generate cidrs a little later, saving the other nodes (https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/node/nodecontroller.go#L568). 

Do we only need to generate available cidrs once on startup? that sounds like the sensible thing unless there's a GKE subnet requirement I'm missing.
@kubernetes/goog-control-plane @cjcullen

**Comment by cjcullen** [comment]
This also confused me. #17754 added this (which I was looking at because it broke node CIDR allocation on GKE).

It looks like #17754 was trying to get rid of the old behavior where we recalculated all possible node CIDR ranges every time a new node showed up. I think the new code just made things unnecessarily complicated. We should be able to generate a list of CIDRs at startup (whether 1st startup or recovering from crash), remove already used ones, and then allocate from that set.

The old behavior (regenerate/recalculate for every allocation) was gross, but it was O(N) on max # of nodes. If you want to fix it the right way, that'd be best :smile:. But just a revert of #17754 would be okay too.

@gmarek knows more about this area than I do.

**Comment by davidopp** [comment]
@gmarek is out for a week. Let's just revert #17754.

**Comment by ArtfulCoder** [comment]
Even in the old code, is the CIDR allocation actually stable ?
When a node is added/deleted, existing nodes should not have their CIDR ranges changed.

**Comment by ArtfulCoder** [comment]
yeah, i read the code, and reverting should keep the cidr allocations stable..

**Comment by therc** [comment]
If you revert #17754, you also need to revert #19580. #19242 is a better change, as it also comes with tests.

**Comment by davidopp** [comment]
@ArtfulCoder @cjcullen Can you guys make a call on whether we should revert #17754/#19580, or merge #19242? (And verify that if we merge #19242, it will fix the problem in this issue?)

**Comment by cjcullen** [comment]
#19242 needs some work before it can be merged. As it is, I don't think it handles nodeController restarts at all. It will be a nice step forward once it is fixed up.

We should revert #17754/#19580 for now to get back to a known good state.
