### ISSUE TITLE
Explore ability to improve namespace deletion performance

### ISSUE THREAD

**Issue by derekwaynecarr** [kubernetes/kubernetes#20051]
The `Namespace` deletion process is complex and requires orchestration.
- `DELETE` `Namespace` marks it as `Terminating`
- controller observes `Terminating` `Namespace`
  - for each `Kind`
  - LIST `Kind`
  - DELETE `Kind` item by item

For `Event` objects we added support for `DELETE_COLLECTION`.  This operation does not reduce the number of operations to `etcd`, but it can reduce the number of requests to `kube-api-server`.

A few options to pursue:
- add `DELETE_COLLECTION` support for other `KIND`s (must do)
- explore keeping track of set of known `KIND` resources in a `Namespace`.  The list could grow during admission of new resources into the `Namespace`.  Orchestration of deletion could reference that information to know what `KIND`s are candidates to delete.
  - an annotation is not appropriate to hold this information since it is too easily editable and could cause the controller to leak data by never cleaning it up.
  - in practice, this is most likely an over-optimization that would only benefit our `e2e` setups, but noting it here.

**Comment by ncdc** [comment]
I have been looking into namespace deletion "timeouts" in e2e tests the past week. The typical flow for a namespace deletion, in isolation, looks like this:

1. Send DELETE request to apiserver
1. apiserver sets DeletionTimestamp
1. NamespaceController sees updated namespace with DeletionTimestamp set
1. NamespaceController adds namespace to its work queue with a 5-second delay (see https://github.com/kubernetes/kubernetes/pull/37431)
1. NamespaceController gets namespace from work queue, tries to delete all content in namespace
1. If content is remaining, NamespaceController will wait before retrying deletion, either:
    1. (maximum grace period of its resources / 2) + 1, _or_
    1. 5ms * 2^n, capped at 1000s, where n is the number of times the namespace has been retried (this only happens if items remain in the namespace unexpectedly; i.e., they've exceeded their grace period)

In isolation, it typically takes about 21-22 seconds to delete a small namespace (default items + 1 pod), where the time is 5 seconds (HA delay) + 16 seconds (30 second grace / 2 + 1). The 16 seconds frequently happens when a pod takes a little bit of time to be fully deleted - more than the time between when the NamespaceController issues the "delete pod" and when it lists all pods to see if any remain.

Now for the interesting part...

In our e2e tests, which run parallelized, we frequently have multiple namespaces active at the same time, due to multiple tests running simultaneously and each test using its own unique namespace. What I have seen is that the time between the `DELETE namespace` http call and the NamespaceController log message indicating it's popped the namespace off the work queue can be upwards of **3 minutes**. Once the NamespaceController starts the actual deletion of all the namespace's content, it can then take another **3 minutes** to delete it all, which is greater than the 5 minute default timeout used by the e2e tests.

By default, the NamespaceController uses only 2 worker goroutines to process namespaces in the work queue for deletion. I put together a though experiment PR (#46067) that increases the number of workers to 5 and replaces the (grace/2)+1 delay with a hard-coded value of 2 seconds. It seemed to help a little bit, but not as much as I would have expected. I probably need some more time to analyze the results to see if maybe I am missing something.

I was also talking with @smarterclayton about the (grace/2)+1 delay, and we agreed that for items that use the default grace period (30 seconds for pods), it would make sense to poll more aggressively (at least during the first 30 seconds). For items where the user has set a custom grace period, (grace/2)+1 still makes sense, since presumably the user has a decent estimate of how long it will take to terminate.

I wanted to record this information so it's not lost, and see if we can get some more eyes on it so we can do some combination of:

1. reduce how long it takes to delete a namespace during parallel deletions & an active cluster
1. reduce e2e flakes due to namespace deletion "timeouts" (maybe we need to increase the default timeout from 5 minutes to 10 or 20?)

Let's discuss 😄 

@kubernetes/sig-api-machinery-misc @kubernetes/sig-testing-bugs @kubernetes/sig-testing-misc @smarterclayton @derekwaynecarr @timothysc

**Comment by derekwaynecarr** [comment]
It would be good to know the depth of the work queue in our e2e runs to understand the 3 minute tail latency.  I assume the second 3 minute latency is caused by being put back into the same underlying work queue.  One thing we did for quota is maintain 2 queues (new quotas get evaluated faster than older quotas).  We could maintain two queues (the full queue, and the we know we tried to delete it once queue).

**Comment by deads2k** [comment]
We have promethus metrics on the queue depth for rate limited workers.  As I recall, it queues unconditionally, which can obviously be improved.

**Comment by ncdc** [comment]
I need to get those metrics for the CI jobs. I don't think they're enabled at the moment.

**Comment by timothysc** [comment]
I'd like to eliminate the recursive deleting entirely... 

What depends on this still?  v3 can delete O(1) now, and all watches should trigger...

**Comment by ncdc** [comment]
@timothysc you mean delete the dir in etcd instead of each item?

**Comment by timothysc** [comment]
Yes.

**Comment by ncdc** [comment]
I can put together a PR to try that.

**Comment by deads2k** [comment]
> I'd like to eliminate the recursive deleting entirely...
> 
> What depends on this still? v3 can delete O(1) now, and all watches should trigger...

Every resource is separate in  etcd since we do `prefix/resource/namespace/name`.  You could improve the deletecollection, sure, but you'll still need to find all the items.  In addition, direct etcd deletes would eliminate all graceperiods, which probably isn't the intent.

**Comment by derekwaynecarr** [comment]
we should also check what resource requirements are for controller-manager are in this case?  its running as a pod, and maybe it is getting cfs throttled?

**Comment by ncdc** [comment]
In a recent e2e flake, it took 2 minutes between the http delete and the queue pop. We don't have prometheus metrics gathering enabled for PR CI jobs (I plan to submit a PR for this to test-infra, along with one here to enable gathering namespace controller metrics), but I am inferring that we had a decently sized work queue, and the majority of the sync loops took 10-15 seconds in this 2 minute window, so it probably "just took that long" with just 2 workers.

**Comment by smarterclayton** [comment]
Unfortunately O(1) delete doesn't work for pods, because graceful deletion
isn't one step.  So pods will always be the long pole.

**Comment by ncdc** [comment]
FYI, the kube-controller-manager in GCE deployments looks to have requests.cpu=200m (https://github.com/kubernetes/kubernetes/blob/688c19ec710340986ba0a86730dd1add7acc5b3a/cluster/saltbase/salt/kube-controller-manager/kube-controller-manager.manifest#L110).

**Comment by wojtek-t** [comment]
> Yes. In v2 we were stuck so we created a weird recursive delete with workers.. we no longer need this imo.


We are still officially supporting etcd v2. So unless the implementation can be just put into etcd v3 code, we can't do it.
BTW - I think that we are doing graceful deletion for some objects, which etcd can't really do...

**Comment by wojtek-t** [comment]
@ncdc 

> FYI, the kube-controller-manager in GCE deployments looks to have requests.cpu=200m 

These only translates to shares - they sum up to ~1 core. If the machine is bigger than 1 core, then it will be allowed to use more. And note that this is request, so if there are free resources on the machine, we can use them.

**Comment by wojtek-t** [comment]
I briefly looked into the code, and I'm seeing this:
https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/namespace/deletion/namespaced_resources_deleter.go#L420
Which means that namespace controller is deleting objects one by one.

Can we instead try using: "DeleteCollection" api call in apserver:
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/registry/generic/registry/store.go#L911
@smarterclayton - WDYT?

BTW I have a hypothesis (though I didn't even try to verify it yet) that the client is throttled on the QPS limits for requests to apiserver. We were hitting this in many different places before.
@ncdc - since you were already looking into those logs, did you see these:
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/rest/request.go#L638
1. I hope this is used also by dynamic client
2. I also hope that we have high enough verbosity in our tests...

**Comment by ncdc** [comment]
@wojtek-t I have not seen evidence of throttling taking place _during the delete-to-pop latency interval_. I have looked repeatedly in logs from multiple jobs, and while there is throttling occurring, it never seems to be where I would expect it (i.e., it's not the smoking gun).

**Comment by derekwaynecarr** [comment]
@wojtek-t - we do delete collection if its supported.  as for resources, i was more concerned to see if it had a limit.  i am not sure how you got your sum to ~1 core statement, but if there is no contention, it can obviously use more than 204 shares of cpu time.

**Comment by liggitt** [comment]
it first tries to delete the collection:
https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/namespace/deletion/namespaced_resources_deleter.go#L450

**Comment by wojtek-t** [comment]
@liggitt - thanks for the link. and sorry for confusion

@derekwaynecarr 
>  i am not sure how you got your sum to ~1 core statement

summing up requests from both etcd instances, apiserver, scheduler, controller manager, glbc, ... => it sums up to 9xx millicores

**Comment by deads2k** [comment]
Opened https://github.com/kubernetes/kubernetes/pull/46373 to avoid extra queuing.  Not sure what, if anything would be updating namespaces, but it would keep the queue smaller if we're fighting for CPU.

**Comment by wojtek-t** [comment]
@ncdc - if you can share some runs where we hit this issue (I mean logs from them), I can also try looking into them.

**Comment by ncdc** [comment]
@wojtek-t the 2 failures from [here](https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/pr-logs/pull/46116/pull-kubernetes-e2e-gce-etcd3/). I've specifically been looking at 31862.

**Comment by wojtek-t** [comment]
@ncdc - I looked into this run and it seems that everything is working as expected. Looking only into logs from this line:
```
I0524 16:54:37.152108       5 namespace_controller.go:159] Finished syncing namespace "e2e-tests-horizontal-pod-autoscaling-qfxzb" (7.358179462s)
```
They are just dense in time. I mean keeping in mind that there are 2 workers, looking into time it took for each of the sync it's pretty clear that as soon as the previous one ends the next one starts.

I'm just surprised that you say that increasing the amount of workers doesn't help... Do you have any logs from a run with increased amount of workers? Is it the same?

**Comment by ncdc** [comment]
@wojtek-t see my PR https://github.com/kubernetes/kubernetes/pull/46067. I think I remember that it reduced the overall deletion time (as observed by the e2e framework; I have a script to download, parse, and get stats) only by 3 or 4 minutes for the entire test run. We can certainly run it several more times and see.

**Comment by ncdc** [comment]
@wojtek-t also, re something like `Finished syncing namespace "e2e-tests-horizontal-pod-autoscaling-qfxzb" (7.358179462s)`, I've found that when I run a single focused test, the times to finish syncing that one namespace tend to be quite small (whether it's one sync loop iteration or multiple). It only seems to take 7-15 seconds per iteration when there's multiple tests happening in parallel. I guess this could be attributed to the fact that writes to etcd are synchronized and not in parallel.

**Comment by wojtek-t** [comment]
> I think I remember that it reduced the overall deletion time (as observed by the e2e framework; I have a script to download, parse, and get stats) only by 3 or 4 minutes for the entire test run. We can certainly run it several more times and see.

@ncdc - sorry, I think I don't understand this. What exactly are you measuring? Time between DELETE namespace request and when it is deleted? Or something else?

**Comment by ncdc** [comment]
@wojtek-t yes, the time between DELETE namespace request and when an external client sees that it's been deleted (https://github.com/kubernetes/kubernetes/blob/7df01780768de82c635f0ae0c58c15f2be152bda/test/e2e/framework/util.go#L1015).

**Comment by wojtek-t** [comment]
@ncdc and this ```3-4 minutes for the entire test run``` is the sum over all tests? What percentage is it?

**Comment by justinsb** [comment]
> Every resource is separate in etcd since we do prefix/resource/namespace/name. You could improve the deletecollection, sure, but you'll still need to find all the items.

And they might not even be on the same etcd server, because of `--etcd-servers-overrides`!

**Comment by ncdc** [comment]
@wojtek-t now that I think about it, the 3-4 minutes was the time as reported in the build log as e.g. `Ginkgo ran 1 suite in 18m32.474254911s`.

In the current form for PR 46067, which increases the workers to 5 and hard-codes the requeue time to 2 seconds instead of looking at the estimate, it ended up decreasing the overall sum from an average of around 24000-25000 seconds down to 14000 seconds, or a savings of 40-45%. Note, however, I only have a sample size of 1 from the PR (the 14000 seconds).

**Comment by ncdc** [comment]
Here are some stats for a random PR I looked at (https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/46242/pull-kubernetes-e2e-gce-etcd3/31903/build-log.txt):

```
N	min	q1	median	q3	max	sum	mean	stddev	stderr
332	4.6	28.3	63.3	112.4	278.4	24403.2	73.5036	53.2419	2.92203
```

Here is my 1 sample:

```
N	min	q1	median	q3	max	sum	mean	stddev	stderr
329	7.4	23.4	39.2	54.9	112.2	13646.8	41.4796	22.3906	1.23443
```

**Comment by wojtek-t** [comment]
> In the current form for PR 46067, which increases the workers to 5 and hard-codes the requeue time to 2 seconds instead of looking at the estimate, it ended up decreasing the overall sum from an average of around 24000-25000 seconds down to 14000 seconds, or a savings of 40-45%. Note, however, I only have a sample size of 1 from the PR (the 14000 seconds).

That sounds like something we would like to push more.

**Comment by wojtek-t** [comment]
Anyway - given the flakiness ratio of these errors, I vote for at least sending a PR bumping amount of workers to 5 asap.

**Comment by ncdc** [comment]
I can do that but I won't be at my computer for another 2 hours.

**Comment by wojtek-t** [comment]
Sure - 2 hours doesn't really matter. I can also send out this PR if you want.

**Comment by ncdc** [comment]
PR to up workers to 5: #46437
