### ISSUE TITLE
kubectl get nodes : the server could not find the requested resource

### ISSUE THREAD

**Issue by madhavij** [kubernetes/kubernetes#20086]
Got the following error while running Kubernetes locally via Docker on the following step:
kubectl get nodes

**Comment by AdoHe** [comment]
no context, please provide more detailed information.

**Comment by madhavij** [comment]
While doing the complete process of installing kubernetes on MacOs using this github repo

and when we try  to run the kubectl binary to get the nodes of the cluster we get the error that says:

Could not read version from the server :get http://<ip>:8080/api dial tcp <ip>:8080 i/o timeout

If you could help out on this

**Comment by a-robinson** [comment]
Please re-post your question to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes). 

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases. 

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to similar questions, and also familiarize yourself with:
   * [the user guide](http://kubernetes.io/v1.0/)
   * [the troubleshooting guide](http://kubernetes.io/v1.0/docs/troubleshooting.html)

Again, thanks for using Kubernetes.

The Kubernetes Team

**Comment by rhetzler** [comment]
troubleshooting guide you linked to is a 404
