### ISSUE TITLE
ERROR: Failed to run install_fedora_deps()!!! with Vagrant Quick Start method

### ISSUE THREAD

**Issue by harobed** [kubernetes/kubernetes#20088]
Hi,

I try Kubernetes with [« Getting started with Vagrant »](http://kubernetes.io/v1.1/docs/getting-started-guides/vagrant.html) but I've this error after 

```
curl -sS https://get.k8s.io | bash
```

```
==> master:   libatasmart.x86_64 0:0.19-7.fc21
==> master:   libreport-filesystem.x86_64 0:2.3.0-10.fc21
==> master:   libssh.x86_64 0:0.7.1-1.fc21
==> master:   libstoraged.x86_64 0:2.1.2-1.fc21
==> master:   mdadm.x86_64 0:3.3.2-1.fc21
==> master:   ntfs-3g.x86_64 2:2015.3.14-2.fc21
==> master:   ntfsprogs.x86_64 2:2015.3.14-2.fc21
==> master:   storaged.x86_64 0:2.1.2-1.fc21
==> master:   storaged-lvm2.x86_64 0:2.1.2-1.fc21
==> master:   xfsprogs.x86_64 0:3.2.2-2.fc21
==> master:
==> master: Dependency Updated:
==> master:   cryptsetup-libs.x86_64 0:1.6.8-2.fc21     kpartx.x86_64 0:0.4.9-68.fc21.3
==> master: Complete!
==> master: /home/vagrant
==> master: Created symlink from /etc/systemd/system/sockets.target.wants/cockpit.socket to /usr/lib/systemd/system/cockpit.socket.
==> master:  *  INFO:  sh -- Version 2015.11.09
==> master:
==> master:  *  INFO: System Information:
==> master:  *  INFO:   CPU:          GenuineIntel
==> master:  *  INFO:   CPU Arch:     x86_64
==> master:  *  INFO:   OS Name:      Linux
==> master:  *  INFO:   OS Version:   3.17.4-301.fc21.x86_64
==> master:  *  INFO:   Distribution: Fedora 21
==> master:  *  INFO: Installing master
==> master:  *  INFO: Found function install_fedora_deps
==> master:  *  INFO: Found function install_fedora_stable
==> master:  *  INFO: Found function install_fedora_stable_post
==> master:  *  INFO: Found function install_fedora_restart_daemons
==> master:  *  INFO: Found function daemons_running
==> master:  *  INFO: Found function install_fedora_check_services
==> master:  *  INFO: Running install_fedora_deps()
==> master: which: no dnf in (/usr/local/sbin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin)
==> master:  *  INFO: Adding SaltStack's COPR repository
==> master:
==> master:
==> master: File contains no section headers.
==> master: file: file:///etc/yum.repos.d/saltstack-salt-fedora-21.repo, line: 1
==> master: '<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">\n'
==> master:  * ERROR: Failed to run install_fedora_deps()!!!
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

I've did a mistake ?

**Comment by fuggersbergerdavid** [comment]
i get the same error! Made a post on stackoverflow just a few min ago :) http://stackoverflow.com/questions/34993716/failed-to-run-install-fedora-deps-when-starting-up-local-kubernetes-cluster

**Comment by willmore** [comment]
We encountered same issue on `1.1.4`.

**Comment by pupapaik** [comment]
This is the issue https://github.com/saltstack/salt-bootstrap/issues/737

**Comment by willmore** [comment]
Have a temporary fix:

As pointed out in https://github.com/kubernetes/kubernetes/issues/20088#issuecomment-174930620, the root issue is a change in URL for an underlying dependency reference by `saltstack-bootstrap`.

This is fixed in https://github.com/saltstack/salt-bootstrap/pull/738, but the fix has not made it to `saltstack-bootstrap` stable. 

We can use the `develop` version:
```sh
cd cluster/vagrant
sed -i "s/https:\/\/bootstrap.saltstack.com/https:\/\/bootstrap.saltstack.com\/develop/" provision-minion.sh 
sed -i "s/https:\/\/bootstrap.saltstack.com/https:\/\/bootstrap.saltstack.com\/develop/" provision-master.sh 
```

Tested on `1.1.4`.

**Comment by sa-mao** [comment]
The fix doesn't work try to update the files 
cluster/vagrant/provision-minion.sh
cluster/vagrant/provision-master.sh
replace that
```
curl -sS -L --connect-timeout 20 --retry 6 --retry-delay 10 https://bootstrap.saltstack.com  | sh -s

```
with that 
```
curl -sS -L --connect-timeout 20 --retry 6 --retry-delay 10 https://bootstrap.saltstack.com | sed -e "s/fedoraproject/fedorainfracloud/" | sh -s

**Comment by arulrajnet** [comment]
@sa-mao Yes. There are ways to fix this. But Its not good idea modifying third party source code on the fly to make it work. That is not future proof also. 

Refer these lines in their source code [L203](https://github.com/saltstack/salt-bootstrap/blob/stable/bootstrap-salt.sh#L203) , [L583](https://github.com/saltstack/salt-bootstrap/blob/stable/bootstrap-salt.sh#L583) and [L2988](https://github.com/saltstack/salt-bootstrap/blob/stable/bootstrap-salt.sh#L2988) . In `__fetch_url() ` function curl command does not follow  redirects. Saltstack have the `BS_CURL_ARGS` env to override the curl arguments.

So that I have added BS_CURL_ARGS in both provision-minion.sh and provision-master.sh. I have tested its working also.

PS: In the develop branch [saltstack](https://github.com/saltstack/salt-bootstrap/blob/develop/bootstrap-salt.sh#L582) fixed the same. All reference based on [last commit](https://github.com/saltstack/salt-bootstrap/blob/e5e5f9f2742c4c8410a81808404aba598ebf3ab8/bootstrap-salt.sh) in stable branch.

**Comment by marun** [comment]
This should be fixed in master with the switch to Fedora 23, which no longer requires a 3rd party repo for salt packages.  I'm not sure when this will be reflected in the https://get.k8s.io bootstrap though.

**Comment by marun** [comment]
Ah, as per @arulrajnet, master being fixed already is no help.  The fix needs to land in the release branch to be reflected in the k8s bootstrap.

**Comment by sunshineo** [comment]
+1
So annoying!
