### ISSUE TITLE
Deployment graduation requirements to v1/GA

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#20130]
Forked from beta requirements #15313.

Placeholder for things that didn't make beta/1.2.

Known issues so far:
- [x] From #18901: Paused disables scaling behavior, but shouldn't, since it's hostile to horizontal pod auto-scaling (HPA).

cc @janetkuo @kargakis @ironcladlou

**Comment by kargakis** [comment]
I really don't know how I feel about this issue. In order to fix it we need to allow another entrypoint for scaling the deployment's latest state. Which means races.

Both autoscalers and [manual scaling](https://github.com/kubernetes/kubernetes/blob/3f40fb7d0af552b44dadc68dfb78e62bcb2819a6/pkg/kubectl/scale.go#L282-L283) hit the deployment /scale [endpoint](https://github.com/kubernetes/kubernetes/blob/3f40fb7d0af552b44dadc68dfb78e62bcb2819a6/pkg/registry/deployment/etcd/etcd.go#L155-L156) and the desired replicas in the spec of the deployment **will be updated**. It's then the job of the deployment controller to bring the actual state of the deployment in sync with its spec. If the deployment is paused ie we don't want it to be reconciled by the controller then it makes sense for scaling to not work.

**Comment by kargakis** [comment]
> From #18901: Paused disables scaling behavior, but shouldn't, since it's hostile to horizontal pod auto-scaling (HPA).

After thinking about this more, I believe it will be fairly easy to have a separate path in the controller just for paused deployments where we can allow scaling. Will submit a PR tomorrow.

**Comment by kargakis** [comment]
At this point, I think we are missing the following fixes/enhancements for GA:

* Resolve the hashing issue (A proposed change in https://github.com/kubernetes/community/pull/384)
* Automatic rollbacks (https://github.com/kubernetes/kubernetes/issues/23211)
* Extensible strategies (https://github.com/kubernetes/kubernetes/issues/14510)

Of the three, the hashing issue needs more thought. 
For automatic rollbacks, we need to decide whether we rollback the deployment template or simply scale up the last working replica set. I used to be in favor of the former solution but now I am on the fence.
For the extensible strategies, as the controller is designed atm, it would be easy to add an External strategy type (https://github.com/kubernetes/kubernetes/issues/39337) and simply not handle that case but we need a PoC.

cc: @mfojtik @tnozicka @smarterclayton

**Comment by bgrant0607** [comment]
@janetkuo @kow3ns Was pause behavior fixed?

**Comment by janetkuo** [comment]
> Was pause behavior fixed?

@bgrant0607 yes. Paused deployments can still be scaled, and their replicasets get scaled proportionally.
