### ISSUE TITLE
Kubelet reported capacity should take into account the size of pod CIDR

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/kubernetes#20177]
My kubernetes master in gce kube-up is using `10.123.45.1/30` which is enough ip addresses for 3 pods max yet the kubelet is reporting allocatable capacity for 40 pods.

cc @kubernetes/goog-node

**Comment by yujuhong** [comment]
I think we need more input for @kubernetes/sig-network-feature-requests  because it is unclear whether kubelet will always have this information in various networking environment.

**Comment by bboreham** [comment]
FWIW when using Weave Net the address space is dynamically shared out between nodes so this is not a problem. 

However it could be added as some kind of status request to CNI since most other pod networks do have a static allocation per node.

**Comment by caseydavenport** [comment]
Yeah, this might be hard to do in a generic way. 

Calico also doesn't have a strict limit to the number of addresses assigned to a node, since allocations are done dynamically. In the Calico case, even a call to CNI wouldn't necessarily return an accurate number, because Calico can assign more addresses to a node if they're needed.

**Comment by krmayankk** [comment]
/sig-scheduling we should reopen this and find a solution for this . There are cases where a node’s capacity can be dynamically extended and here are when it cannot be . We need solution for
Both ..
