### ISSUE TITLE
KUBE_COVER=y doesn't work on Mac

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#20223]
Haven't had time to debug, but just recording here.

```
$ KUBE_COVER=y hack/test-go.sh pkg/api/meta
Running tests for APIVersion: v1,extensions/v1beta1,metrics/v1alpha1 with etcdPrefix: registry
+++ [0127 13:50:24] Saving coverage output in '/tmp/k8s_coverage/v1,extensions/v1beta1,metrics/v1alpha1/20160127-135024'
bash: -c: line 0: unexpected EOF while looking for matching `"'
bash: -c: line 1: syntax error: unexpected end of file
+++ [0127 13:50:24] Combined coverage report: /tmp/k8s_coverage/v1,extensions/v1beta1,metrics/v1alpha1/20160127-135024/combined-coverage.html
!!! Error in hack/test-go.sh:333
  'return ${test_result}' exited with status 1
Call stack:
  1: hack/test-go.sh:333 main(...)
Exiting with status 1
```

**Comment by mfanjie** [comment]
Got the same issue here, the root cause is that in https://github.com/kubernetes/kubernetes/blob/master/hack/test-go.sh#L259
On BSD, the -I option has constraint of 255 bytes limit, so the arguments got truncated. This did not happen on Linux as GNU has no such limitation.
-I	replstr
	     Execute utility for each input line, replacing one	or more	occur-
	     rences of replstr in up to	replacements (or 5 if no -R flag is
	     specified)	arguments to utility with the entire line of input.
	     The resulting arguments, after replacement	is done, will not be
	     allowed to	grow beyond 255	bytes; this is implemented by concate-
	     nating as much of the argument containing replstr as possible, to
	     the constructed arguments to utility, up to 255 bytes. 

One solution is to extract the bash call command to a function, likely to be hack/lib/golang.sh, and change the code to something like
```
bash -c "source hack/lib/golang.sh; newfunc()"
```
all parameters need to be passed in to the function, still considering on how to optimize the call.

**Comment by mfanjie** [comment]
we have to put the newfunc somewhere rather than test-go.sh, golang.sh is a candidate, as the script need to be sourced before the function call is available. and test-go.sh can not be source.
Another option is to drop the xargs call, a function named runTestIterations is in test-go.sh, which is called when coverage is not enabled, evaluating the possibility of adapting this function.

**Comment by soltysh** [comment]
The other problem with this solutions is the hugely long path with tons of subdirs created by `group/version`. Eg. `/tmp/k8s_coverage/v1,autoscaling/v1,batch/v1,batch/v2alpha1,extensions/v1beta1,apps/v1alpha1,federation/v1alpha1,policy/v1alpha1,rbac.authorization.k8s.io/v1alpha1/20160624-145532/combined-coverage.html` which is very painful.
