### ISSUE TITLE
Kubernetes local setup using vagrant doesnt work

### ISSUE THREAD

**Issue by krmayankk** [kubernetes/kubernetes#20237]
I am using the 1.1.4 release. I built it locally.With Vagrant as the provider, i get the following 

cluster "vagrant" set.
user "vagrant" set.
context "vagrant" set.
switched to context "vagrant".
Wrote config for vagrant to /home/mayank.kumar/.kube/config
Each machine instance has been created/updated.
  Now waiting for the Salt provisioning process to complete on each machine.
  This can take some time based on your network, disk, and cpu speed.
  It is possible for an error to occur during Salt provision of cluster and this could loop forever.
Validating master
Connection to 127.0.0.1 closed.
Validating minion-1
..............
Waiting for each minion to be registered with cloud provider
error: couldn't read version from server: Get https://10.245.1.2/api: dial tcp 10.245.1.2:443: connection refused

When i login into the master, i see zero length file for kube-apiserver.log, kube-controller-manager.log, and kube-scheduler.log
 and only see kubelet running.

How can i debug this to find out why its not working.

**Comment by a-robinson** [comment]
Please re-post your question to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes). 

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases. 

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to similar questions, and also familiarize yourself with:
   * [the user guide](http://kubernetes.io/v1.0/)
   * [the troubleshooting guide](http://kubernetes.io/v1.0/docs/troubleshooting.html)

Again, thanks for using Kubernetes.

The Kubernetes Team
