### ISSUE TITLE
running hack/local-up-cluster.sh fails because api-server cannot come up

### ISSUE THREAD

**Issue by krmayankk** [kubernetes/kubernetes#20240]
it fails because of the following error:-
Waiting for apiserver to come up
!!! [0127 14:15:03] Timed out waiting for apiserver:  to answer at http://127.0.0.1:8080/api/v1/pods; tried 10 waiting 1 between each
Cleaning up...

When i look at the api-server log in /tmp/kube-apiserver.log, is see the following:-

mayank.kumar@mkumar-wsl:~/src/go/src/k8s.io/kubernetes$ cat /tmp/kube-apiserver.log 
usage: dzdo -K | -k | -V
usage: dzdo -v [-AknS] [-p prompt]
usage: dzdo -l[l] [-AknS] [-g groupname|#gid] [-p prompt] [-u user name|#uid]
            [-g groupname|#gid] [command]
usage: dzdo [-AbHknPS] [-C fd] [-g groupname|#gid] [-p prompt] [-u user
            name|#uid] [-g groupname|#gid] [VAR=value] [-i|-s] [<command>]
usage: dzdo -e [-AknS] [-C fd] [-g groupname|#gid] [-p prompt] [-u user
            name|#uid] file ...
usage: dzdo -h [user@]<host> [-W,ssh-option] <arguments>
usage: dzdo --help

i have a checkout from tag  1.1.4

**Comment by a-robinson** [comment]
Please re-post your question to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes). 

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases. 

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to similar questions, and also familiarize yourself with:
   * [the user guide](http://kubernetes.io/v1.0/)
   * [the troubleshooting guide](http://kubernetes.io/v1.0/docs/troubleshooting.html)

Again, thanks for using Kubernetes.

The Kubernetes Team
