### ISSUE TITLE
Kubectl get cluster 

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#20374]
I've observed a fair amount of confusion around the whole kubeconfig/multi cluster thing. Sometimes people ask about lost gke clusters, when really they ran kube-up on gce and wound up with a different context. 

Locally I've setup my aliases so `get`, `add`, and `use` cluster work, and I personally find this useful. Maybe we can teach Kubectl to do something like:

``` bash
# aka kubectl config view clusters | egrep "^[ \t]+name: " | sort | uniq | awk '{print $2}'
$ kubectl get clusters
dev
e2e-test-beeps
local

# gcloud container clusters get-credentials 
$ kubectl add cluster gke_dev_us-central1-b_cluster-1
Fetching cluster endpoint and auth data.
kubeconfig entry generated for cluster-1.

# kubectl config use-context
$ kubectl use cluster gke_dev_us-central1-b_cluster-1
switched to context "gke_dev_us-central1-b_cluster-1"
```

I realize the second one isn't really cross platform, so maybe go looking for `KUBERNETES_PROVIDER`?

**Comment by bgrant0607** [comment]
cc @kubernetes/kubectl

**Comment by smarterclayton** [comment]
Effectively this is what the Openshift "login" and "project" commands do but at a higher level (namespace focused, not cluster focused) with less of a direct link to the internal config.  So I agree this is a pretty relevant use case.  The reason we use login is because that's almost always the entry point to another cluster:

    $ oc login
    Server [https:/:localhost:8443]: _
    Username:
    Password:
    # generated a new user and cluster and created a context to bind them
    $ oc project
    You are in namespace "default" on cluster "https://foo.bar"
    $ oc project foo
    Switching to project "foo"
    
Practically speaking login required more sophistication than we're ready to bake into Kube at this time, but the flow you describe above does improve switching between contexts.  I think however that it's better for now to focus on making the switching easy / obvious.  Users change between namespaces and servers frequently, but change their user credentials per server rarely (except for admins).  Getting auth info across all the different providers is hard, but gathering it from a user is feasible.

**Comment by bgrant0607** [comment]
cc @quinton-hoole

**Comment by bgrant0607** [comment]
I agree our current commands are confusing.

See also #20605, and the issues it references.

**Comment by therc** [comment]
See also #20668 for confusing or missing shorthand notations (I die a little every time I type --namespace or forget to specify it) when juggling between kube-system and a custom namespace.
