### ISSUE TITLE
Allow configurable src range for type=loadbalancer firewall

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#20392]
Users can set an annotation denoting a trusted src range and we can apply that as the --source-ranges of the firewall.

**Comment by freehan** [comment]
I can take this up if no one else is working on it.

**Comment by bprashanth** [comment]
@a-robinson any objections/plans?

**Comment by a-robinson** [comment]
You should double double check the relevant AWS/OpenStack Neutron APIs to make avoid ruling out compatibility in them, but going for it SGTM.

**Comment by bprashanth** [comment]
Agree with checking. but if this ends up being a sneaky features that is not x-plat, we can just prefix the annotation with ".gce" and have everyone else ignore it. @kubernetes/goog-cluster fyi

**Comment by thockin** [comment]
This is a good thing to try as an annotation, but we should just poke folks
to see if it works.

@justinsb @anguslees - do your respective load-balancer implementations
support restricting to a particular client IP range?  If so, any
restrictions?

Whatever we do, this is particular to type=LoadBalancer, so it should say
so.

**Comment by anguslees** [comment]
These feature request bugs never explain what they're actually talking about :/   Assuming "apply that as the --source-ranges of the firewall" means only allowing certain remote source subnet(s) to access vip addresses on loadbalancers.  I haven't experimented with the range of vendor drivers out there, but I fear the answer for OpenStack is "unsupported".

**Comment by justinsb** [comment]
AWS uses security groups for ELB ingress, so yes, it does support CIDR ingress restrictions.  (It also supports restricting access to instances in specific security groups).

I don't think it's unreasonable to throw an error if you try to create a LB on OpenStack with a CIDR source restriction.  That's what we do e.g. if someone tries to create a UDP load balancer on AWS, and I haven't noticed many/any complaints about that.  If it turns out to be important (if users report hitting the error) we could then implement IP filtering in e.g. kube-proxy.

I suspect as long as we eventually support filtering for L7 ingress that we'll cover most use cases.

**Comment by thockin** [comment]
As an evolution, it might be interesting to have per-namespace policy that enforces that services in a namespace must have a specific source-ips (or something like that)

**Comment by thockin** [comment]
I'm assigning this to next milestone to decide whether and how to promote the annotation to a full feature.
