### ISSUE TITLE
Not able to run e2e tests locally

### ISSUE THREAD

**Issue by Pensu** [kubernetes/kubernetes#20399]
Hi all,

I have a local kueretes setup on Ubuntu. I am trying to execute e2e tests on this cluster. Here is the result I am getting:
```
root@kube-master:~/kube_latest/kubernetes# ./_output/local/go/bin/e2e.test --host="127.0.0.1:8080" --provider="local" --ginkgo.v=true --ginkgo.dryRun=true --kubecong="$HOME/.kubernetes_auth"
Feb  1 14:14:15.927: INFO: >>> testContext.KubeConfig: /root/.kubernetes_auth

Feb  1 14:14:15.928: INFO: >>> testContext.KubeConfig: /root/.kubernetes_auth

Feb  1 14:14:15.928: INFO: Waiting up to 10m0s for all pods (need at least 0) in namespace 'kube-system' to be running and ready
Feb  1 14:14:15.936: INFO: The status of Pod kube-dns-v8-m8drm is Pending, waiting for it to be either Running or Failed
Feb  1 14:14:15.936: INFO: 0 / 1 pods in namespace 'kube-system' are running and ready (0 seconds elapsed)
Feb  1 14:14:15.936: INFO: expected 1 pod replicas in namespace 'kube-system', 0 are Running and Ready.
Feb  1 14:14:15.936: INFO: POD                NODE             PHASE    GRACE  CONDITIONS
Feb  1 14:14:15.936: INFO: kube-dns-v8-m8drm  192.168.122.129  Pending         [{Ready False 0001-01-01 00:00:00 +0000 UTC 0001-01-01 00:00:00 +0000 UTC  }]
Feb  1 14:14:15.936: INFO: 
Feb  1 14:14:17.944: INFO: The status of Pod kube-dns-v8-m8drm is Pending, waiting for it to be either Running or Failed
Feb  1 14:14:17.944: INFO: 0 / 1 pods in namespace 'kube-system' are running and ready (2 seconds elapsed)
Feb  1 14:14:17.944: INFO: expected 1 pod replicas in namespace 'kube-system', 0 are Running and Ready.
Feb  1 14:14:17.944: INFO: POD                NODE             PHASE    GRACE  CONDITIONS
Feb  1 14:14:17.944: INFO: kube-dns-v8-m8drm  192.168.122.129  Pending         [{Ready False 0001-01-01 00:00:00 +0000 UTC 0001-01-01 00:00:00 +0000 UTC  }]
Feb  1 14:14:17.944: INFO: 
```

I am following this guide: http://kubernetes.io/v1.1/docs/devel/e2e-tests.html. I can't see the pod kube-dns-v8-m8drm in "kubectl get pods" either!
Can you please help me figure out what exactly is the issue here? TIA.

**Comment by gmarek** [comment]
Please re-post your question to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes). 

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases. 

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to similar questions, and also familiarize yourself with:
  * [the user guide](http://kubernetes.io/v1.1/)
  * [the troubleshooting guide](http://kubernetes.io/v1.1/docs/troubleshooting.html)

Again, thanks for using Kubernetes.

The Kubernetes Team
