### ISSUE TITLE
Kubelet: We should organize the status get functions better.

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes/kubernetes#20477]
`api.PodStatus` is used by many kubelet components and functions. Currently these components and functions retrieve `api.PodStatus` by different means:
- From status manager. Get status from status manager is very quick, but _the status may not have been populated and cached_ yet.
- From pod status cache and convert it to `api.PodStatus`. Get status from pod status cache is very quick, but status can't be got before until first `relist`.
- From runtime with `GetPodStatus()` function and convert it to `api.PodStatus`.Get status directly from runtime is slow, but it's more accurate.
- From `api.Pod` from apiserver. Get status from `api.Pod` can help us recover status after kubelet restarts. But it is usually not very accurate, we should avoid that unless we have no other choice.

These different means are used in different places in kubelet, which makes the code complex and confusing. We should orgnize them better, for example add a higher layer status get function.

**Comment by dashpole** [comment]
I am looking into this as part of my effort to clean up the status manager.  Let me know if these changes make sense:
change call from GetPodStatus(uid types.UID) to GetPodStatus(pod *api.Pod).  Currently, everyone who calls this passes in pod.UID, where pod is an *api.Pod.
If we have a cached status, return that.  
Otherwise, if my thinking is correct, we can tell if the pod is running using the containerRuntime
And we can tell if the pod is failed or succeeded using the pod.Status.

Ill test this out and let you know how it goes.

**Comment by dashpole** [comment]
Upon further inspection, I dont think it is a good idea to move any runtime calls inside the status manager.   There is only one place where we use containerRuntime as a backup for getting the status from the status manager.  That is in pkg/kubelet/kubelet_network.go , function cleanupBandwithLimits.  I think that using the containerRuntime within the status manager would be unwise, because callers will not be aware of the performance costs of the function.

So far, I have simply moved logic for using the status from the api server inside the status manager's GetPodStatus function.  This has cleaned up almost all logic related to this issue, and has left the functionality exactly the same, except for a few places, which should all still function appropriately.
