### ISSUE TITLE
e2e flake: "Services should be able to up and down services"

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#20554]
Failure [120.140 seconds]
    Services
      /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/service.go:896
    should be able to up and down services [It]
      /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/service.go:265

    Expected error:
        <*errors.errorString | 0xc8206d93f0>: {
            s: "service verification failed for: 10.0.9.21, expected [service2-2bzyi service2-2ohq2 service2-40ehj], got []",
        }
        service verification failed for: 10.0.9.21, expected [service2-2bzyi service2-2ohq2 service2-40ehj],   got []
    not to have occurred

    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/service.go:244

https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/19200/kubernetes-pull-build-test-e2e-gce/26500/?project=kubernetes-jenkins
http://kubekins.dls.corp.google.com:8081/job/kubernetes-pull-build-test-e2e-gce/26500/#

**Comment by wojtek-t** [comment]
@kubernetes/goog-cluster

**Comment by thockin** [comment]
@bprashanth maybe the same?

**Comment by bprashanth** [comment]
Perhaps, will triage. services up and down is new looking

**Comment by bprashanth** [comment]
This is a failure for the second service in the test (which spins up 3 services) to even come up. I.e we get on a hostexec pod on some node, curl the service2 endpoint 150 times, and expect to see 3 service2 endpoint hostnames show up. This does not happen, because 1 endpoint is MIA.

Good endpoints: 
service2-2bzyi(e2e-gce-master-1-minion-hlpz, nodeip: 104.154.18.118:22, podip: 10.245.3.22)
service2-2ohq2(e2e-gce-master-1-minion-uons, nodeip: 104.197.234.254:22, podip: 10.245.5.23)

Bad endpoints: 
service2-40ehj (e2e-gce-master-1-minion-novn, nodeip: 104.197.235.28:22, podip: 10.245.4.22)

On the node the *host exec* pod ran on, so that's 104.197.234.43  or e2e-gce-master-1-minion-5dnq, we see:
```
I0203 14:03:40.225846       6 proxier.go:379] Setting endpoints for "e2e-tests-services-ewh76/service2:" to [10.245.3.22:9376]
I0203 14:03:40.333855       6 proxier.go:379] Setting endpoints for "e2e-tests-services-ewh76/service2:" to [10.245.3.22:9376 10.245.5.23:9376]
I0203 14:05:22.188730       6 proxier.go:379] Setting endpoints for "e2e-tests-services-ewh76/service2:" to [10.245.3.22:9376 10.245.4.22:9376 10.245.5.23:9376]
```

So why the gap between lines 2, 3 above? (the test was polling in this time for 3 endpoints)

More kube-proxy logs:
```
I0203 14:03:45.232505       6 iptables.go:377] running iptables -N [KUBE-SERVICES -t nat]
I0203 14:03:45.276476       6 iptables.go:377] running iptables -C [PREROUTING -t nat -m comment --comment kubernetes service portals -j KUBE-SERVICES]
I0203 14:03:45.532449       6 iptables.go:377] running iptables -C [POSTROUTING -t nat -m comment --comment kubernetes service traffic requiring SNAT -m mark --mark 0x4d415351 -j MASQUERADE]
I0203 14:03:46.433195       6 proxier.go:762] Syncing rules: *nat
```
Note the 1s delay between the last 2 lines. If I'm not mistaken that's between the save operation and the next restore:
https://github.com/kubernetes/kubernetes/blob/master/pkg/proxy/iptables/proxier.go#L489
https://github.com/kubernetes/kubernetes/blob/master/pkg/proxy/iptables/proxier.go#L762

Anyway I don't think we can pinpoint just those ops, the timing I've added around syncProxyRules should help.

**Comment by bprashanth** [comment]
>@bprashanth maybe the same?

So yes, it's the same, i was initially confused because the nodes where the endpoints landed had fast kube-proxies, but the slow kube-proxy was on the node we ssh into to hit the service endpoints.

**Comment by bprashanth** [comment]
Duping into https://github.com/kubernetes/kubernetes/issues/20402

**Comment by thockin** [comment]
There's (I think) a variable shadowing bug in that test, too, which could produce the same result.
