### ISSUE TITLE
“--master-service-namespace” option of kube-apiserver does not work

### ISSUE THREAD

**Issue by lxb31** [kubernetes/kubernetes#20625]
Environment: centos7 + kubenetes1.1.7 + etcd2.0.12 + docker-engine-1.8.3

I want to move the kubernetes master service to another namespace named "kube-system" instead of the default namespace "default". so I change the "--master-service-namespace"  option of kube-apiserver to "kube-system", but it did not work at all. 

service info of the "default" namespace as below.
$kubectl get svc  
NAME         CLUSTER_IP   EXTERNAL_IP   PORT(S)   SELECTOR   AGE
kubernetes   172.16.0.1   <none>        443/TCP   <none>     9m

Is there something I forgot to setup? please help me.

**Comment by AdoHe** [comment]
@fuliangliu actually you can use `kubectl get svc --all-namespaces=true` to display namespace for services, besides I think this is a bug of apiserver, I am working on a quick fix to this.

**Comment by fuliangliu** [comment]
@AdoHe you mean kubernetes master service must be placed in the "default" namespace? No way to change?

**Comment by patrikbeno** [comment]
@AdoHe isn't `kube-apiserver` a system component? Shouldn't it be placed in `kube-system` by default?

**Comment by RickyCook** [comment]
it seems to me as though the pods are being put in the correct namespace, but the service isn't:
```
[root@localhost ~]# kubectl get svc --all-namespaces=true
NAMESPACE     NAME         CLUSTER-IP    EXTERNAL-IP   PORT(S)         AGE
default       kubernetes   172.16.0.1    <none>        443/TCP         5m
kube-system   kube-dns     172.16.0.10   <none>        53/UDP,53/TCP   4m
[root@localhost ~]# kubectl get po --all-namespaces=true
NAMESPACE     NAME                                    READY     STATUS    RESTARTS   AGE
kube-system   kube-controller-localhost.localdomain   5/5       Running   6          5m
kube-system   kube-dns-sa3pq                          2/2       Running   0          5m
```

**Comment by AdoHe** [comment]
I will recheck this.

**Comment by kiich** [comment]
I'm also seeing/curious of this issue.
I can see PODs are put in kube-system but the service always seems to get created in default name space and i can't seem to track how that is being done.

**Comment by AdoHe** [comment]
@fuliangliu @kiich @RickyCook @patrikbeno Actually the `master-service-namespace` is a deprecated flag, and apiserver will not respect this when create `kubernetes` service, the namespace of `kubernetes` service will always be `default`

**Comment by kiich** [comment]
@AdoHe Good to know - thanks for the clarification. Didn't/Couldn't tell it was deprecated.

**Comment by vdavidoff** [comment]
I am having the same issue. I just upgraded to 1.5.1 and I see that master-service-namespace is deprecated for kube-apiserver, but it's still a valid option for kubelet...though it doesn't seem to be working (and never has). If that's expected, then what is the point of master-service-namespace? Or is it slated to be deprecated as a kubelet option, too?

Side note: The reason I put my master services into the kube-system namespace in the first place is because while turning up my first clusters and learning k8s, plenty of "core services" provide example specs that put them in the kube-system namespace, so it only made sense to me to put the k8s master components there, too. This was before I realized master-service-namespace wouldn't do what it looks like it should, though, and before I really understood a lot of fundamental things about k8s. But ultimately, this is confusing - if k8s master services wouldn't go into kube-system, then why should anything else?

Thanks for any clarity anyone can provide.

**Comment by RyanHartje** [comment]
I believe I'm experiencing this when setting up k8s via the CoreOS Kubernetes walkthrough, while using etcd2.

```sh
# kubectl get all --all-namespaces
<truncated output>
NAMESPACE     NAME                       CLUSTER-IP   EXTERNAL-IP   PORT(S)         AGE
default       svc/kubernetes             10.3.0.1     <none>        443/TCP         4h
kube-system   svc/kube-dns               10.3.0.10    <none>        53/UDP,53/TCP   24m
kube-system   svc/kubernetes-dashboard   10.3.0.200   <none>        80/TCP          6m
```

Is there any troubleshooting information I could provide that would be helpful?

I'm using:
CoreOS stable (1235.9.0)
Kubernetes v1.6.1_coreos.0 (via hyperkube)
Etcd 2.3.7
Docker 1.12.6

**Comment by adohe** [comment]
@RyanHartje please take a look at my old comment.

**Comment by josdotso** [comment]
I would like to see the kubernetes service anchored by default in the `kube-system` namespace.  Users are encouraged to reach `https://kubernetes` in a normal namespace because it works in `default` namespace.  

However, one must use `https://kubernetes.default` (more something more qualified) if not originating from `default` namespace.  This seems like a user interface issue.
