### ISSUE TITLE
Allow Ingress to  accept from all IPs of Node

### ISSUE THREAD

**Issue by mateeyow** [kubernetes/kubernetes#20634]
Correct me if I'm wrong but I have noticed that ingress only services from one node ip. Is it possible to serve it to all ip address?

**Comment by codablock** [comment]
Which ingress controller are you using? The two example controllers found in the kubernetes/contrib source can be deployed to multiple nodes via replication controllers.

**Comment by mateeyow** [comment]
I'm using nginx-third-party controller.

*Sincerely,*

*Matthew Aldrin S. Torres*

**Comment by codablock** [comment]
You can scale the replication controller of nginx-third-party to be >= your node count.
Best solution would actually be to deploy the ingress controller as a DaemonSet, but the api is still experimental and the nginx-third-party does not support it yet (crashes because it expects a RC around itself)

**Comment by mateeyow** [comment]
@codablock Alright, thanks. Better close this issue.
