### ISSUE TITLE
Increase the logging level for a GKE test cluster

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#20661]
The logging level of a GCE e2e cluster is set at V4, while a GKE e2e cluster maintains the regular V2. This makes debugging GKE build failures more difficult than necessary. 

For GCE, the logging level is set in [configure-vm.sh](https://github.com/kubernetes/kubernetes/blob/d8be60ee57fc442ed19acc65060f615bf4accf48/cluster/gce/configure-vm.sh#L313). I am not sure what's the best way to do the equivalent for GKE.

**Comment by roberthbailey** [comment]
@kubernetes/goog-gke

**Comment by roberthbailey** [comment]
This seems like an infrastructure change rather than a flaky test issue. Is it marked as being flaky because it's blocking progress on flaky tests?

**Comment by yujuhong** [comment]
> This seems like an infrastructure change rather than a flaky test issue. Is it marked as being flaky because it's blocking progress on flaky tests?

Personally, it's one of the biggest obstacles for me to debug flaky tests that happen on GKE. I usually have to find similar failures in GCE, or try to reproduce this myself (which is often not very successful). That's why I marked it kind/flake. It is not blocking any flaky test for me personally as of now, but it'd be a great incentive for me to continue paying attention to flaky GKE tests.

**Comment by roberthbailey** [comment]
My concern is that changing the log level has other undesirable effects by making our test clusters different from production clusters. 

On GCE we now have a seen a slow divergence between config-default.sh and config-test.sh which I find to be troubling (since we don't have any infrastructure configured to run CI using config-default.sh) and I don't want the same thing to happen on GKE. One example is that https://github.com/kubernetes/kubernetes/pull/16986 removed the `SecurityContextDeny` admission controller from config-default.sh but not config-test.sh (oops). Another example is that we register the master kubelet in config-default.sh but not for e2e tests. 

We've also seen that high levels of logging has a significant performance impact on our binaries, so cranking up the log level in test means that we are no longer accurately testing the performance of our system. 

I guess I'm wondering why it requires log level 4 to debug test flakes. What happens when a k8s user is running a system and sees weird behavior? Do they have to restart their kubelet with a higher log level and hope it happens again? I'd rather see us have better default logging / event capturing in combination with better logging in our test code to help track down test flakes.

**Comment by yujuhong** [comment]
> Another example is that we register the master kubelet in config-default.sh but not for e2e tests.

Agreed.

> My concern is that changing the log level has other undesirable effects by making our test clusters different from production clusters.

I don't like this too, and I think it should be fixed.

> We've also seen that high levels of logging has a significant performance impact on our binaries, so cranking up the log level in test means that we are no longer accurately testing the performance of our system.

This is true, but since we're testing conservatively (assuming worse performance), I am ok with this.

> I guess I'm wondering why it requires log level 4 to debug test flakes. What happens when a k8s user is running a system and sees weird behavior? Do they have to restart their kubelet with a higher log level and hope it happens again? I'd rather see us have better default logging / event capturing in combination with better logging in our test code to help track down test flakes.

I agree in general we should do what you suggest, and there is definitely still room for improvement. However, I think one distinction is that we're testing buggy, unstable code at HEAD. I's difficult to know exactly what you're looking for and modify your tests for that. There are also too many internal operations in kubelet for it to expose the information anywhere else (e.g., events), and the tests may not have access to them (besides scanning the log). I brought up kubelet because I'm more familiar with it, but it should not be so different from debugging other components in kubernetes.

**Comment by roberthbailey** [comment]
I created https://github.com/kubernetes/kubernetes/issues/21052 to make sure that we are testing *something* against config-default.sh (I noticed some issues with it today when I ran it). 

I'll see what we can do about bumping up the log level for gke-ci.

**Comment by dchen1107** [comment]
@roberthbailey Please delegate to your team member. Thanks!

**Comment by roberthbailey** [comment]
Since this isn't a flaky test issue, I'm going to remove the flake label and we can use it to track making GKE more debuggable.

**Comment by spiffxp** [comment]
/sig cluster-lifecycle
/area platform/gce
since we lack a sig-gcp at the moment

**Comment by spiffxp** [comment]
/remove-area platform/gce
/area platform/gke
(too much copy-pasta for lunch)

**Comment by roberthbailey** [comment]
Based on a recent bug where all GKE clusters were being flagged as test clusters and had increased log level, I'm going to say that this is done. 

@dashpole

/close
