### ISSUE TITLE
Pod Autoscaler fails if pods are stuck in Terminating

### ISSUE THREAD

**Issue by bakins** [kubernetes/kubernetes#20673]
I had a node go down in AWS. Normally the controller-manager deletes all the pods, etc. For some reason, all the pods that were running on that node now are stuck in "Terminating."  The pod autoscaler still attempts to get metrics from heapster about them and therefore will not autoscale.  Should the controller-manager only consider pods in a certain state?

**Comment by davidopp** [comment]
@piosz @mwielgus could one of you take this?

**Comment by mwielgus** [comment]
It sounds like another problem with grace period/termination notice. 
@bakins  What Kubernetes version are you on?

cc: @gmarek

**Comment by bakins** [comment]
1.1.7

Regardless, should auto scalers consider terminating pods?

**Comment by piosz** [comment]
There are basically two problems here:
 1. Broken implementation of termination grace period, @gmarek and @mwielgus will take a look into this
 2. How HPA should care with pods in terminating state? What we think with @mwielgus is that RC should have a higher priority than HPA, so if RC is supposed to recreate pod which is in Terminating state HPA should not make any decisions. Otherwise if pod is in Terminating state is just a leftover from some previous operations HPA should disregard it and make its job.

**Comment by gmarek** [comment]
@bakins - can you paste all logs from kube-controller-manager that mention the Node that died? Also Events for this Node could be helpful.

**Comment by bakins** [comment]
This was almost 2 weeks ago on a production server, but I can probably find the logs. From memory, the logs about the server were the familiar "server not found in cloud provider, so deleting". The controller-manager also gave the unfortunantly familiar "unable to reconcile.. found metrics for 6/7 pods" for autoscaler.

FWIW, fro my perspective, the work around for removing the pods was fairly simple - I wrote a little script that delete pods with a grace-period of 0 seconds that are terminating and on a node that does not exist..  I'm more concerned about the autoscaler considering such pods as part of its scaling calculations - this could cause production issues for someone.

**Comment by davidopp** [comment]
cc/ @mikedanese 

Also, ref/ #7660

**Comment by davidopp** [comment]
And I guess cc/ @smarterclayton

**Comment by gmarek** [comment]
For the latter, @mwielgus should be able to help you.

For the former: can you ping me on slack if it happens again? I'd like to get some more data.

**Comment by def421** [comment]
I had problem with HPA and Pods in state Pending. 
Heapster try get CPU utilization from all pods, but failed, because can obtain metrics only for 9 pods from 12 (else 3 pods are in state Pending, because Pods ExedsFreeCPU).
Appear this error:
https://github.com/kubernetes/kubernetes/blob/a3972947cc140cc527d20c955a75a0b7af109a8d/pkg/controller/podautoscaler/metrics/metrics_client.go#L200
and hpa stay in previous state for a long time.

I found TODO about this problem
https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/podautoscaler/horizontal.go#L88
What can I do in this case?

Does it connect to this problem? or make new issue?

**Comment by piosz** [comment]
@def421 #21540 is related to your problem

**Comment by def421** [comment]
@piozs Thanks

**Comment by gmarek** [comment]
@piosz - why am I assigned to this issue? Is there something for me to do here?

**Comment by gmarek** [comment]
Inactive for few months.
