### ISSUE TITLE
GitRepo for Google Cloud Source Repositories

### ISSUE THREAD

**Issue by dinvlad** [kubernetes/kubernetes#20692]
Hi All,

Is it possible to point GitRepo for pods running on the GKE to a Cloud Source Repository available via Google console (within the same project), e.g.
```
gitRepo:
  repository: https://source.developers.google.com/p/<project_id>/r/default
  revision: HEAD
```
When I try to use it this way, `kubectl` displays pod status as `ImageNotReady`

I assume that means that the default credentials are not shared with GKE? Then per #17676, currently it's not possible to do that?

Any help would be appreciated.
Thanks

**Comment by thockin** [comment]
The git repo volume doesn't support credentials, so unless that is a public
repo it won't work.

**Comment by lavalamp** [comment]
Hopefully Tim answered your question, but if not:

Please re-post your question to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes). 

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases. 

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to similar questions, and also familiarize yourself with:
   * [the user guide](http://kubernetes.io/v1.0/)
   * [the troubleshooting guide](http://kubernetes.io/v1.0/docs/troubleshooting.html)

Again, thanks for using Kubernetes.

The Kubernetes Team
