### ISSUE TITLE
Does kube-scheduler support fault domain?

### ISSUE THREAD

**Issue by xinxiaogang** [kubernetes/kubernetes#20709]
Whether kube-scheduler consider about fault domain during Pod scheduling to try to schedule Pods to different fault domain in a RC?

**Comment by lavalamp** [comment]
I don't know the current answer, so tagging @davidopp. But in general, for this sort of question:

Please re-post your question to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes). 

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases. 

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to similar questions, and also familiarize yourself with:
   * [the user guide](http://kubernetes.io/v1.0/)
   * [the troubleshooting guide](http://kubernetes.io/v1.0/docs/troubleshooting.html)

Again, thanks for using Kubernetes.

The Kubernetes Team

**Comment by davidopp** [comment]
The "selector spread priority" policy spreads pods from the same service or RC across nodes and zones:
https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/scheduler/algorithm/priorities/selector_spreading.go#L76

The "service anti-affinity priority" priority function will let you spread based on an arbitrary fault domain that you choose by specifying the label name: https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/scheduler/algorithm/priorities/selector_spreading.go#L216

We'll have a much more expressive and flexible version of this type of affinity/anti-affinity in 1.3 (in a few months).
