### ISSUE TITLE
Should multiple partitions of a single GCE disk be able to be RW mounted to a Pod

### ISSUE THREAD

**Issue by saad-ali** [kubernetes/kubernetes#20835]
http://stackoverflow.com/questions/35256588/can-i-mount-multiple-partitions-of-a-single-gce-disk-to-a-pod

TODO:
* Determine intended/expected behavior.
  * Should multiple partitions of a single GCE disk be able to be RW mounted to:
    1. the same pod?
    2. different pods on the same node?
    3. different nodes?
* If intended behavior doesn't match actual behavior, we have a bug--fix it.
* Add tests verifying intended/expected behavior.

**Comment by wernight** [comment]
This is a real issue for smaller website or people have many website especially given the GKE 5 disks limit on shared machines, and 16 limit on standard machines.

Most website currently require 2 disks due to Kubernetes and ggg limitations:
 - Django websites require one for the DB and one for uploaded media files
 - [Dockerized GitLab](http://doc.gitlab.com/omnibus/docker/) requires 3

This means that on a tiny cluster I can host 2 websites about, and on a standard machine one I can host about 8 websites.

It's even more an issue that Kubernetes doesn't seem to try and run a website on another node if current node has too many mounted disks. This means that even a cluster of 10 tiny machines would still only allow about 2 website to run without issue (worst case scenario).

**Comment by saad-ali** [comment]
When a GCE PD is attached to a node, it must be attached either as `read-write` or `read-only`. And, GCE permits a GCE PD to be attached to no more than one node in `read-write` mode.

So if two different pods request two different partitions of the same GCE PD both in `read-write` mode, and the pods are scheduled to different nodes, even if k8s did not prevent this scenario, it would fail because GCE would not allow the same PD to be attached to two different nodes in `read-write` mode.

The only way to enable this scenario would be to modify the k8s scheduler such that if a new pod references the same GCE PD as an existing pod in `read-write` mode (but different partition), then the new pod must only be scheduled to the same node as the previous pod (regardless of availability on other nodes).

**Comment by wernight** [comment]
There is another solution which I think would prove a lot more flexible, which is to allow mounting sub-directories. The simplest way I'm thinking of is:

    $ mount /dev/sdX /mnt/sdX
    $ ln -s /mnt/sdX/something/something /my/mount/path

It could probably be done in a Dockerfile but that feels bad because it feels like the Dockerized image has to adapt to Kubernetes and hack around it.

**Comment by saad-ali** [comment]
> There is another solution which I think would prove a lot more flexible, which is to allow mounting sub-directories.

But the same problem mentioned above would still exist right? If pod A and pod B reference two different partitions on the same volume, if the pods are scheduled to different nodes, the same volume can't be attached to both nodes in RW mode.

**Comment by wernight** [comment]
Not for me. I partitioned to have DB and media (which should be in sync) on the same disk to have a single consistent snapshot also, and less disk usage.

**Comment by wernight** [comment]
Another tool which would also fix many more cases, but I'm not sure about latency, would be simple **nfs** support. Supporting nfs volume as simply as gfs disks or docker registry.

**Comment by thockin** [comment]
The only sane behavior for partitions of a single block device is that they may be used in the same pod (or not at all).

Allowing subdirectories is something we have looked at before and is much easier and more useful than multiple partitions.

We do have NFS support - just point a pod at your NFS server though an `nfs` volume.

**Comment by wernight** [comment]
I agree with what you say.

The point is "at your NFS server" which I don't have and I'd like to avoid setting up.

**Comment by thockin** [comment]
The more I stare at this the less confident I am.  If you have a PD with 2 partitions, that would be represented as two different PersistentVolumes.  We do not have any way to draw a dotted-line around those two and say that they can be used only together.  I think we should find other ways to handle the propositions listed here and MAYBE come back to this over time.

**Comment by wernight** [comment]
I agree the real issue is about basic scaling (for high availability to only scaling to 2 or 10 machines) writable data simply, without being a lot slower than a local disk.

**Comment by thockin** [comment]
I'm going to close this because it is about GCE, and we should not go out of our way to handle this.  That said, #26567 discusses this WRT hardware-centric issues, so the feature may yet come up.
