### ISSUE TITLE
docker-multinode master booting script doesn't work

### ISSUE THREAD

**Issue by fasthall** [kubernetes/kubernetes#20945]
Docker version: 1.7.1
K8S version: 1.2.0-alpha.7 (on master branch)
I follow [this guide](https://github.com/kubernetes/kubernetes/blob/master/docs/getting-started-guides/docker-multinode/master.md) and run master.sh.

$ **kubectl get pods** shows:
NAME                             READY     STATUS    RESTARTS   AGE
k8s-master-hostname   4/4       Running   1          10m
k8s-proxy-hostname    1/1       Running   0          9m

$ **kubectl cluster-info** shows:
Kubernetes master is running at http://localhost:8080

However, $ **kubectl get nodes** shows nothing.

If I try to deploy DNS , after deploying busybox to verify it, 
$kubectl get pods busybox always shows the pod is pending, it never get running.

**Comment by krousey** [comment]
Please re-post your question to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases.

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to similar questions, and also familiarize yourself with:
   * [the user guide](http://kubernetes.io/v1.0/)
   * [the troubleshooting guide](http://kubernetes.io/v1.0/docs/troubleshooting.html)

Again, thanks for using Kubernetes.

The Kubernetes Team
