### ISSUE TITLE
Status updates should blacklist label updates

### ISSUE THREAD

**Issue by kargakis** [kubernetes/kubernetes#20978]
https://github.com/kubernetes/kubernetes/pull/20906 makes deployment status updates rejecting label updates. The same change should be applicable to all objects with a status part.

cc: @bgrant0607

**Comment by bgrant0607** [comment]
We definitely shouldn't allow labels to be updated via status.

There are a few reasons why I think we should allow annotations to be updated:
1. To allow an extended controller to record extra information. For example, /binding is able to update annotations so that a custom scheduler can add external references.
2. To allow a controller to record information about what it did. For instance, /rollback updates an annotation that records the reason for the last change.
3. If we add fields to status of a new API version that are recorded as annotations in the storage version, then the controller may need to be able to write those annotations during a cluster upgrade.

**Comment by lavalamp** [comment]
Labels are very clearly not OK for change on a status update. I'm mostly persuaded by Brain's list that annotations ought to be mutable on a status update. It does allow controllers to do things that users may not expect. And buggy controllers would be able to cause more harm (but they can already do worse things, so this won't be an argument until we lock down controllers a lot more).

**Comment by kargakis** [comment]
cc: @smarterclayton @deads2k @liggitt

**Comment by smarterclayton** [comment]
Agreed

**Comment by kargakis** [comment]
Dropped annotations from the title and description of the issue. I am fine with labels.

**Comment by kargakis** [comment]
@kubernetes/sig-api-machinery-misc

**Comment by liggitt** [comment]
when we fix this there should probably be a test helper added to resttest#TestUpdate that tests status update behavior (ensures spec and labels are not allowed to mutate, etc)

**Comment by bgrant0607** [comment]
Something to consider for "v2" APIs. #8190

**Comment by liggitt** [comment]
as more and more fields get added to metadata (finalizers, ownerRefs, etc), they are all getting exposed to mutation by status subresources. It seems like we should default in the opposite direction and require opting in to letting /status modify specific things under metadata

**Comment by bgrant0607** [comment]
Opt-in for new fields is a good idea.

**Comment by nikhita** [comment]
See https://github.com/kubernetes/kubernetes/pull/59038 to enable this for new resources.

**Comment by liggitt** [comment]
broader issue in https://github.com/kubernetes/kubernetes/issues/45539, deduplicating
