### ISSUE TITLE
gce route creation for 1000 node clusters takes too long

### ISSUE THREAD

**Issue by alex-mohr** [kubernetes/kubernetes#20984]
I created a 5 node cluster on GCE, then cloned the MIGs to have more of them with faster-than-usual VM creation.

It took 7 minutes to create all the VMs, but it took an additional 19 minutes for the route controller to create all of the routes.  It should be a lot faster.

In particular, I think we're throttling calls to the GCE api due to rate limits?

Ideally, the controller would look something like:
- have a max number of outstanding operations on GCE at a time.
- if an API rate-limit token is available AND there's a queued create-operation request AND the number of outstanding operations is less than the max, create a new operation.
- otherwise, if an API rate-limit token is available, poll the most-long-ago-checked pending operation for doneness.
- otherwise, wait until an API rate-limit token is available.

@cjcullen

**Comment by alex-mohr** [comment]
(CJ was also looking at deletion, where we have an issue in which nodes are deleted from the master very slowly when scaling MIGs down.)

**Comment by cjcullen** [comment]
A couple problems:

1. In large clusters, the way we reconcileCIDRs fails a lot, and puts a lot of pressure on the apiserver:

    ```
    nodes := APIServer.Nodes.List
    for node := range nodes {
    	if node.CIDR == "" {
    		node.CIDR = allocateCIDR()
    		APIServer.Nodes.Update(node)
    	}
    }
    ```
    In a large cluster, that update call is competing with a lot of status updates coming from kubelets. Combined with the fact that it is all synchronous, we can only get through a few CIDR allocations each time through before all of the rest fail w/ "bad resource version" errors.

1. The RouteController does not handle nodes w/ empty CIDRs well. We don't skip nodes that haven't been allocated a CIDR yet, so we send some garbage POST to GCE, and get a ton of 400s back. Because our CIDR allocation is churning slowly, we continue to spam GCE until we hit our project's rate limit and start getting 403s.

This all eventually shakes out, but right now it takes about a half hour, and makes your GCE project unusable for that time.

#19242 would fix problem 1. If that PR is too risky for 1.2, we could probably get by just spawning goroutines for all of our Nodes.Update calls in reconcileCIDRs.

#19117 will make our scaling problems a little nicer, but all that's needed to solve problem 2 is a check that `node.PodCIDR != ""` before we go off and try to create a route. I'll send out a PR for that.

**Comment by gmarek** [comment]
@bgrant0607 - this is an example of issue why I'd like to separate Heartbeat from Node object. If we had a separate object, NodeController would be able to allocate most of CIDRs without collisions.

**Comment by bgrant0607** [comment]
@gmarek 

I assume we're talking about this loop:
https://github.com/kubernetes/kubernetes/blob/42e2ff94c15c01686473665d024a4bd1a5bf8916/pkg/controller/node/nodecontroller.go#L515

Yes, that's pretty lame.

No concurrency.

No retries.

No separation of CIDR allocation and node update.

For the update, an alternative could be to Patch with no resourceVersion precondition. 

Or fetch just metadata (#1459) and then RMW each element of the node list.

Yes, I'd like to eventually split spec and status (#8625), but "Heartbeat" is not the right API.

**Comment by gmarek** [comment]
This loop had it's problems forever, but concurrency or retries would only be a treatment not the cure.

Do you think that splitting spec from status will happen in v1.3?

**Comment by bprashanth** [comment]
@alex-mohr @cjcullen do we have an SLO for 1000 node turn up time or is this just a nice to have?
does this leave the 1.2 priority list once we have https://github.com/kubernetes/kubernetes/pull/19117? (asking for cluster team 1.2 triage)

IIUC we haven't fixed the mig problem mentioned in https://github.com/kubernetes/kubernetes/issues/20984#issue-132773837 (kube-up still creates giant migs last time I tried).

**Comment by cjcullen** [comment]
The 2 PRs to fix this in a targeted way are in. #19117 won't be going in to 1.2. Nothing more is required on this issue for 1.2 (and we can probably close the issue once @alex-mohr runs another test and confirms).

**Comment by alex-mohr** [comment]
Just tried creating 1000 nodes again and the route controller kept up this time -- GCE API reported node + route counts lagged each other by around a minute, which seems reasonable given time to create nodes and routes.

**Comment by alex-mohr** [comment]
Thanks CJ -- closing this one!
