### ISSUE TITLE
Failure domain labels should not be marked as "alpha"

### ISSUE THREAD

**Issue by roberthbailey** [kubernetes/kubernetes#21024]
I just created a cluster from head and I see labels with the name `failure-domain.alpha.kubernetes.io/region` on a cluster that doesn't have any alpha features enabled. If this is new default behavior for 1.2, the label shouldn't say `alpha`; it should either be `beta` or GA.

**Comment by davidopp** [comment]
Interesting question. This label is tied to Ubernetes Lite which is not a discrete API resource, hence no applicable  `--runtime-config` flag to enable/disable it.

@bgrant0607 any thoughts on this? It seems to me that some alpha labels/annotations will be directly tied to specific features that have API resources (e.g. a special label/annotation that is consumed by a new alpha-level controller) while others will not. But in both cases it seems not trivial to have `--runtime-config` control whether it is published.

**Comment by bgrant0607** [comment]
cc @aronchick regarding the status of Ubernetes Lite in GKE in 1.2

**Comment by davidopp** [comment]
@bgrant0607 Even if Ubernetes Lite is not truly alpha, hence we can make these labels not-alpha in 1.2, this issue is bound to come up in the future, since not all labels/annotations will be tied to API resources, so it would be good to have a policy on this (preferably one that can be implemented without a lot of new code). And even the ones that are tied to API resources, the mechanism to avoid publishing them when `--runtime-config` is not set to enable the corresponding API resource them may not be trivial, since IIUC Kubelet does not know about `--runtime-config` setting, and some labels are published by Kubelet.

**Comment by bgrant0607** [comment]
It's bad practice to introduce features initially as beta. Yes, we've done that often in the past, and it has incurred a significant cost pretty much every time. So that's why these were "alpha".

We have a number of "alpha" features that aren't disabled via flag. Typically, they are accessed via annotations. Users that don't invoke those features generally aren't aware they exist, since they don't show up in API output or in generated reference docs.

These labels are a bit different in that they are applied automatically, but they actually don't have any effect by default. They are just labels. It doesn't seem worth it to disable them, and we'd probably enable them in all our tests so that we don't increase the size of our test matrix. I'm not in favor of a general policy, because it's a risk vs cost tradeoff.

In this particular case, I don't mind changing them to `beta`, since we'd likely have to jump through the same hoops to advance them to GA regardless whether they were alpha or beta.

**Comment by roberthbailey** [comment]
> It's bad practice to introduce features initially as beta.

We are effectively doing that with ubernetes lite (as a whole), since it wasn't alpha in 1.1 and it will be enabled by default in 1.2 (hence I would call it beta). You don't have to use it (like any other new feature), but the scheduling changes and the node labeling are both turned on for all 1.2 clusters.

**Comment by bgrant0607** [comment]
@roberthbailey That was my guess. We also did that for HPA, Job, and Ingress in 1.1, and did it for the whole API back in June 2014. We treat "beta" more as a statement of commitment than the normal meanings.

Another alpha label: #20909

**Comment by davidopp** [comment]
I basically agree with all of @bgrant0607 's reasoning, though I also think it would be fine to leave these labels as alpha. I think the question is whether we think we might change them in the future. If we make them beta now, then we need to preserve compatibility for people who start using them in their own code.

@roberthbailey Whether it's proper or not, we've been making scheduling changes without any notion of alpha/beta/GA for quite some time. We have a versioned scheduling config file but that's not really the same thing (and isn't usable by GKE users anyway). We've been adding new priority functions (like spread RC/service across nodes) and predicate functions or the equivalent ("don't schedule on out-of-disk node" or "don't schedule too many PDs on a VM") all the time. We could debate whether this is the proper thing to do, but we already go through so many hoops for compatibility that I'm really reluctant to add more. So I'm not sure it's meaningful to ask whether Ubernetes Lite is itself alpha or beta.

cc/ @justinsb

**Comment by roberthbailey** [comment]
> If we make them beta now, then we need to preserve compatibility for people who start using them in their own code.

Once we launch them by default on a production release version of k8s, I think we need to commit to the beta level of support anyway, so I think our naming should be consistent with that. 

@davidopp - I think that the scheduling changes can be categorized as improvements to an already "GA" feature (e.g. that the cluster schedules pods to nodes).

**Comment by davidopp** [comment]
> Once we launch them by default on a production release version of k8s, I think we need to commit to the beta level of support anyway, so I think our naming should be consistent with that.

I guess I see your point. Though since we don't have a mechanism to disable publishing these kinds of labels, this means we cannot ever have alpha labels of this sort.

> @davidopp - I think that the scheduling changes can be categorized as improvements to an already "GA" feature (e.g. that the cluster schedules pods to nodes).

Good. :)

**Comment by roberthbailey** [comment]
> we don't have a mechanism to disable publishing these kinds of labels

It would be trivial to flag-guard the code that adds the annotation to the node.

**Comment by davidopp** [comment]
> It would be trivial to flag-guard the code that adds the annotation to the node.

But based on what, though? My understanding is that `--runtime-config` is tied to API versions and API resources. There isn't a direct correlation between those and node labels, especially in the case where they're not being consumed by an API resource (as in the Ubernetes Lite spreading case).

Would we introduce a new flag caled `--alpha-cluster` or something like that, which would control these labels and also force a particular setting of `--runtime-config`? I guess that could work...

**Comment by roberthbailey** [comment]
We've flag-guarded features on the kubelet before (privileged mode) and in that case you had to flip a flag on the kubelet *and* a flag on the master to enable it. If we wanted to make ubernetes lite an alpha-level feature, we could put the scheduling changes behind a flag in the scheduler and the node labeling behind a flag in the kubelet (either a generic flag like you suggest or something specific to this feature). Then if you want to build your own cluster you could flip them on. But the out-of-the-box and supported, backwards compatible beta quality features wouldn't include ubernetes lite. This would allow us to launch it as alpha, change it in backwards incompatible ways for 3 months, and then launch it as beta (take away the flags and enable it by default). I don't think we should do that in this case -- we should just change the names to beta.

**Comment by davidopp** [comment]
Yeah I agree we should just change the names to beta.

**Comment by davidopp** [comment]
#21235 fixed this.
