### ISSUE TITLE
cluster/ubuntu/util.sh's use of make-ca-cert.sh fails in restricted deployment environment

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/kubernetes#21037]
It is almost possible to run the cluster/ubuntu scripting on a non-cluster machine to deploy Kubernetes into a deployment environment that is restricted such that the cluster machines (master and workers (AKA "minions", "nodes")) can not open connections to arbitrary external locations.

However, there is at least one sticking point.  The one I discovered is that `provision-master` and `provision-masterandnode` use `ssh` to ask the master machine to run the `make-ca-cert.sh` script, and that script fetches https://storage.googleapis.com/kubernetes-release/easy-rsa/easy-rsa.tar.gz .

@dalanlan

**Comment by roberthbailey** [comment]
Does ubuntu have openssl installed by default? You can also generate the certs using openssl commands which could replace the easyrsa cert generation for ubuntu. Alternatively, if you drop certs onto the master machine in the right location, salt will skip running the `make-ca-cert.sh` script because the certs will already exist (so there is no need to create them). This is what we do on GCE.

**Comment by dalanlan** [comment]
I'm ok with self-assigned certs if you insist.

**Comment by MikeSpreitzer** [comment]
@roberthbailey: yes, Ubuntu 14.04 has openssl by default.

Is there a document describing the current (e.g., release 1.1.7) story about authorization?  I found access.md but it seems to be a hypothetical, not describing what I find in the current API.

**Comment by MikeSpreitzer** [comment]
@dalanlan: the current scripting produces self-signed certificates, right?

**Comment by MikeSpreitzer** [comment]
@roberthbailey: cluster/ubuntu/util.sh runs `make-ca-cert.sh` directly and unconditionally, not conditionally via Salt.
I looked at the GCE scripting, and it uses Brendan's hacked easyrsa too.  I think the better part of valor here is to continue using it.  It will be a small change to move the fetch of that earlier in the process, so that the machine doing the fetch is the machine running util.sh instead of the master.

**Comment by dalanlan** [comment]
nope. We use easyrsa for now. A self-assigned cert is generated by api-server itself, during which period no external resource would be touched.



Sent from myMail for iOS


Friday, February 12, 2016, 01:05 +0800 from notifications@github.com  <notifications@github.com>:

**Comment by MikeSpreitzer** [comment]
I was a bit imprecise.  What I see the easyrsa doing is creating:

- a  ca.cert in which issuer = subject (with a common name of the form <ip address>@<timestamp>);

- a server.cert in which issuer = ca.cert's issuer = ca.cert's subject and there are several X509v3 Subject Alternative Names; and

- a kubecfg.crt in which issuer = ca.cert's issuer = ca.cert's subject.

I don't really care about trying to make openssl do this right now, I have submitted a PR that just makes a small change in how easyrsa is fetched.

**Comment by roberthbailey** [comment]
> @roberthbailey: cluster/ubuntu/util.sh runs make-ca-cert.sh directly and unconditionally, not conditionally via Salt.

Sorry, I meant that on *GCE* we run it conditionally via salt. I didn't realize ubuntu did it unconditionally. 

> I looked at the GCE scripting, and it uses Brendan's hacked easyrsa too. I think the better part of valor here is to continue using it. It will be a small change to move the fetch of that earlier in the process, so that the machine doing the fetch is the machine running util.sh instead of the master.

This is true. I moved it out of the master and onto the machine running kube-up.sh so that we could push certificates to the nodes without requiring secure master <-> node connectivity prior to certificate distribution.

**Comment by MikeSpreitzer** [comment]
@roberthbailey: I assume your last remark was still about the GCE scripting.  The cluster/ubuntu scripting does not use Salt or Ansible, and is not sensitive to whether certificates are already in place.  I agree it would be good to make it so.  But that is not my immediate problem, so I am not trying to solve that right now.

**Comment by roberthbailey** [comment]
@MikeSpreitzer - Yes. The salt is configured to skip running the `make-ca-cert.sh` script if the certs are already in place on the master. That would be another direction we could take the ubuntu scripts -- rather than push the easyrsa tar file onto the master, fetch it onto the machine running kube-up, generate the certs, and the ssh over the certificates to the master. This would allow you to distribute certs to the master and nodes such that you could make the communications between them secure.

**Comment by MikeSpreitzer** [comment]
Now that you mention it, I see that the cluster/ubuntu scripting has the kubelet and kube-proxy contacting the unsecured port of the API server and provides no certificate to them.  This clearly can and should be improved.  But can we leave all that to a separate PR?  The one at hand solves my immediate problem of supporting some prototyping I need to do.

**Comment by roberthbailey** [comment]
We can certainly do it in a separate PR (smaller PRs are easier to review and faster to merge anyway).

**Comment by MikeSpreitzer** [comment]
FYI, I opened issue #21171 for the secure comm issue.
