### ISSUE TITLE
Collect master logs for GKE e2e's

### ISSUE THREAD

**Issue by ihmccreery** [kubernetes/kubernetes#21087]
(Somewhat related to #20661)

As of right now, we are only targeting green upgrade tests on GKE right now, but as far as I can tell, we have no way to look at master logs of GKE e2e runs, for diagnosing things like #20925.

We need to either:
1. get logs from GKE masters,
2. target upgrade tests on GCE instead of GKE, or
3. figure out a workaround so we can get tests green without logs.

As we move toward more test infrastructure targeting GKE, this is going to be a recurring issue.  We'll need visibility into what's going on on the GKE master.

cc @kubernetes/goog-testing

**Comment by ihmccreery** [comment]
Also cc @kubernetes/goog-gke

**Comment by a-robinson** [comment]
I assume you mean we don't have publicly findable logs, since Googlers have access to the logs from the master for the GKE e2e runs (modulo #20670...).

If you just want to be able to get a dump of the logs from the master, the /logs/ path on the API used to expose all the master log files, but now only seems to include the apiserver. I'm not when that changed or whether it was intentional.

**Comment by spiffxp** [comment]
/sig cluster-lifecycle
/area platform/gke
since we lack a sig-gcp at the moment
