### ISSUE TITLE
Guestbook example not working,unable to connect to master radis 

### ISSUE THREAD

**Issue by enlinxu** [kubernetes/kubernetes#21111]
Redis-slave can't resolve redis-master in guestbook example. My environment is VMWare ESX, CoreOS. Below is the error I am getting:
unable to connect to master radis 
no such file or directory CoreOS

I found this old issue seems quite relavant: https://github.com/kubernetes/kubernetes/issues/6158 , Kcao provided the solution to modify the /etc/hosts for each slaves, but that doesn't solve the issue at all.

Am I missing anything?

**Comment by bgrant0607** [comment]
Please re-post your question to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases.

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to similar questions, and also familiarize yourself with:
  * [the user guide](http://kubernetes.io/v1.1/)
  * [the troubleshooting guide](http://kubernetes.io/v1.1/docs/troubleshooting.html)

Again, thanks for using Kubernetes.

The Kubernetes Team

**Comment by Tushar120120** [comment]
Can we have a FAQ/trouble shooting section at the end of
https://kubernetes.io/docs/tutorials/stateless-application/guestbook/

There are so many ways to set up cluster and CNI, even if we can find it stackoverflow, many times we can not follow as it not applicable. If we do not use minicube, it is not clear how to get the URL.
