### ISSUE TITLE
Zone-spread HA master for Ubernetes Lite

### ISSUE THREAD

**Issue by davidopp** [kubernetes/kubernetes#21124]
The current incarnation of Ubernetes Lite makes the application tolerant to zone outages but does not make the Kubernetes control plane tolerant to zone outages since it doesn't use (zone-distributed) HA master. For a short or medium duration zone outage this is totally fine because the containers will continue running even if the master goes away, but if the zone where the master was running goes out for a long time, eventually there will be problems (since pods from failed nodes won't reschedule, users can't update the containers, etc.). 

It would be good to do a zone distributed HA master for Ubernetes Lite, with at least one etcd replica per zone, at least one API server per zone, and the master-elected components like scheduler and controller-manager distributed across the zones.

cc/ @quinton-hoole @justinsb 

ref/ #17059

**Comment by quinton-hoole** [comment]
@davidopp Yup, as you and I discussed a while back, we omitted automatic multi-zone HA master from v1.2 intentionally in the interests of time.  We already have instructions on how to manually set up HA master (which we will update to reflect multi-zone stuff).

**Comment by quinton-hoole** [comment]
We don't have anyone assigned to do this for v 1.3 (~07/2016), but would welcome community contributions.

**Comment by justinsb** [comment]
In my mind #19443 is the biggest blocker for this:  it isn't clear to me how we can set up a reliable HA etcd cluster.  If I can get guidance on that, I can at least start working towards HA master as part of the kube-up v2 work I'm doing (e.g. do we need IP address takeover, or does DNS suffice...)

**Comment by quinton-hoole** [comment]
Hi Justin. I don't think that you need any complicated stuff for etcd. Will
describe when I'm off my fone :-)
On May 10, 2016 7:11 AM, "Justin Santa Barbara" <notifications@github.com>
wrote:

In my mind #19443 <https://github.com/kubernetes/kubernetes/issues/19443>
is the biggest blocker for this: it isn't clear to me how we can set up a
reliable HA etcd cluster. If I can get guidance on that, I can at least
start working towards HA master as part of the kube-up v2 work I'm doing
(e.g. do we need IP address takeover, or does DNS suffice...)

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/21124#issuecomment-218169113>

**Comment by irfanurrehman** [comment]
This issue was labelled only for sig/multicluster and is thus moved over to kubernetes/federation#39.
If this does not seem to be right, please reopen this and notify us @kubernetes/sig-multicluster-misc.
/close
