### ISSUE TITLE
cluster/ubuntu scripting should expose --proxy-mode option of kube-proxy

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/kubernetes#21168]
There should be a way to select the iptables proxy-mode.
@dalanlan @zmerlynn

**Comment by resouer** [comment]
@dalanlan Are you interested in modifying ubuntu deploy scripts to use a user provided  configure file?

**Comment by dalanlan** [comment]
@resouer This is fixed by #21170 and it will be merged in soon.

**Comment by mfanjie** [comment]
This fix breaks cluster/kube-up.sh while kubernetes provider is rather than ubuntu, as the following variables are only defined in ubuntu folder
PROXY_SETTING=${PROXY_SETTING:-""}
DEBUG=${DEBUG:-"false"}
When I run KUBERNETES_PROVIDER=vagrant and run cluster/kube-up.sh

It will fail with error "==> master: [ERROR   ] {'pid': 5871, 'retcode': 1, 'stderr': '/tmppR9bNG.sh: line 21: DEBUG: unbound variable', 'stdout': ''}"

**Comment by MikeSpreitzer** [comment]
@mfanjie: I do not understand.  I have not tried KUBERNETES_PROVIDER=vagrant and run cluster/kube-up.sh, can you please clarify what is going wrong.  This PR (#21170) affected only files in cluster/ubuntu/; are you saying that some of them are used when KUBERNETES_PROVIDER=vagrant?  This PR did not introduce PROXY_SETTING or DEBUG.

**Comment by MikeSpreitzer** [comment]
@mfanjie I tried running kube-up.sh with the Vagrant provider, but ran into a different (and much prior) problem; see https://kubernetes.slack.com/archives/kubernetes-users/p1455920824002734 --- any help would be appreciated.

**Comment by MikeSpreitzer** [comment]
OK, I see you opened issue #21529 for this and PR #21531 fixed it.  Thanks.  I will respond to the larger question under #21529.
