### ISSUE TITLE
pkg/api/deep_copy_generated.go doesn't seem to be getting generated

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/kubernetes#21338]
This seems wrong:

```console
$ echo "package api" > pkg/api/deep_copy_generated.go && ./hack/update-generated-deep-copies.sh 
+++ [0216 13:18:05] Building go targets for linux/amd64:
    cmd/gendeepcopy
+++ [0216 13:18:12] Placing binaries
Generating for v1
Generating for authorization/__internal
Generating for authorization/v1beta1
Generating for extensions/__internal
Generating for extensions/v1beta1
Generating for componentconfig/__internal
Generating for componentconfig/v1alpha1
Generating for metrics/__internal
$ cat pkg/api/deep_copy_generated.go 
package api
```

cc @caesarxuchao @kubernetes/goog-csi @davidopp

**Comment by wojtek-t** [comment]
@mikedanese - this is WAI

Basically, we are moving towards new deep-copy generator, which is currently only generating pkg/api/deep_copy_generated.go file.

See:
https://github.com/kubernetes/kubernetes/blob/master/hack/after-build/run-codegen.sh#L37

I'm going to migrate the remaining ones after finished with 1.2 stuff I have on my plate, because there is still some generalization work that must be done there.

**Comment by mikedanese** [comment]
Ok thanks for the info
