### ISSUE TITLE
RFE 1.3 + : Network isolation for the kubernetes control plane

### ISSUE THREAD

**Issue by timothysc** [kubernetes/kubernetes#21331]
Currently we don't have hard separation of the control plane for node metrics, and status updates.  Ideally they would exist on their own plane to ensure timely responses and verifying health independent of the load on node.  

/cc @kubernetes/sig-node @jeremyeder @kubernetes/rh-networking @kubernetes/rh-cluster-infra

**Comment by jeremyeder** [comment]
This issue is to request supporting multi-homed network support in Kube, segregation of control-, data-plane and storage traffic.

Right now, flannel and openshift-sdn assume that there is only one network connection on the host, and that each container only needs access to the one network, and can rely on the kernel to route everything else.

That's fine for common traffic, but the special case of storage traffic needs to be separately designed and accounted for. We already pay an expensive price in both performance and per-packet CPU efficiency for using VXLAN.

If we put storage data over that same (already inefficient) network, we risk poor performance, and worse, storage traffic interfering with production (i.e. httpd) traffic.

For distributed storage like NFS, gluster or ceph, very specific interface tuning (for throughput) may be required, which is at odds with the latency-optimized tuning typically done for web-based transactional workloads. So, if both workloads share the same link, we will not be able to meaningfully optimize for either.

We have in fact been able to trigger node evictions just by running normal network traffic over the same network as Kubernetes infra communications.  Tweaking node-monitor-grace-period is our workaround.

I'd like to posit 2 possible solutions for this:

- Segregated networks (cluster infra, storage (as a Service, not GPD/EBS), backups)
- Do it on the same physical network, using QoS/tc or OpenFlow/QoS.

**Comment by timothysc** [comment]
In the case outlined above, the infra-pods or storage pods would need to pass meta-data to the networking layer to "do the right thing".

**Comment by eparis** [comment]
I feel like kubernetes might not be where we should be solving this (but I don't have an answer where it should be)...

How the node talks to storage is not a kubernetes problem.  It is a node config problem.

Kubernetes also doesn't really do container networking, that's the plugin's problem. It might not be easy to control/split where interpod traffic and node <-> master traffic goes, but it isn't a kube issue, it's a node and network plugin configuration issue.

Now QoS/rate limitting per pod is supposedly already possible in tc, but you have to turn it on....

**Comment by jeremyeder** [comment]
I think I agree, perhaps the feature belongs in openshift-sdn. I think Tim's point was that openshift-sdn might take direction/input from Kube in order to create those networks.  Not sure that's actually a technical requirement though.  We could just tell openshift-sdn to create N-networks and give them logical labels.  Then Kube would take those labels into account.

This is all just a brain-dump. This needs design work.

**Comment by timothysc** [comment]
Another question might be, do we want to formalize the notion of planes?  As a pod belongs in certain planes.  Right now I believe we've over-used namespaces to kind-of address this, but is that a good way of doing it, probably not.

**Comment by jeremyeder** [comment]
@knobunc

**Comment by timothysc** [comment]
As we start biggering and biggering, there we're going to need to address this soon.  

once we reach 250 or 500 pods/machine we're going to need to segregate traffic.  

/cc @kubernetes/sig-scalability

**Comment by diogo-reis** [comment]
I also have the same need in a bare-metal environment: put Pod traffic (containers) on one network and management traffic (API,...) on another network. Anyone have any idea how I can do this on 2 separate networks?

/remove-lifecycle stale
