### ISSUE TITLE
AWS: kubectl get service for a LoadBalancer service should include the hostname

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#21526]
It would be great to figure out a way to include the ELB hostname in the `kubectl get services` output.  The problem right now is that it is too wide, and this would cause the output to wrap and become unreadable.  The workaround is to do `kubectl describe service <serviceid>`.  But this is confusing to users e.g. comments at https://github.com/kubernetes/kubernetes/pull/21145#discussion_r53111858

**Comment by justinsb** [comment]
thockin suggested:

> As another idea, we could show the IP-or-hostname, but if len(hostname) > 16, show hostname[0:13] + "..." in normal output and show the whole thing in -o wide.

Also see discussion in #18019

**Comment by justinsb** [comment]
Marking as P1 for next-candidate as it is a very common question, and @aronchick wants it :-)

**Comment by therc** [comment]
I'm implementing this because it keeps annoying me, but we actually go above 16 characters already when there are multiple IPs (Ingresses), even without -o wide. I know because I added the ellipses as @thockin suggested, but now the last testcase in TestPrintHumanReadableService() fails. It has three ingresses. Do I fix the test and keep 16 as the limit? Do I bump that to something larger, so the current string matching test can work with, say, a couple of IP addresses, but neither with three of them nor with a full 70-character AWS ELB hostname?

**Comment by therc** [comment]
Forget it, I'm making more changes so it tests printing the service in both narrow and wide output. For narrow output, we only guarantee the first address to be printed in the 16 characters (yet more fun to be had with IPv6).

**Comment by justinsb** [comment]
As we have a fix for it that is LGTMed, I guess I didn't need to punt it the other day.
