### ISSUE TITLE
kubectl help prompt does not expose command for deploying multi-container pods

### ISSUE THREAD

**Issue by YnR** [kubernetes/kubernetes#21587]
When reading the list of commands for kubectl, it lists "run" for deploying a single container image to a pod, but not how to do the same thing for multi-image pods.

**Comment by AdoHe** [comment]
@YnR guess you are looking for such example:
```
{
  "kind": "Pod",
  "apiVersion": "v1",
  "metadata": {
    "name": "redis_django",
    "labels": {
      "app": "webapp"
    }
  },
  "spec": {
    "containers": [
      {
        "name": "key-value-store",
        "image": "redis",
        "ports": [
          {
            "containerPort": 6379,
          }
        ]
      },
      {
        "name": "frontend",
        "image": "django",
        "ports": [
          {
            "containerPort": 8000,
          }
        ]
      }
    ]
  }
}
```
for multiple-containers pod, you should better create through `yaml` file.

**Comment by bgrant0607** [comment]
Please re-post your question to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases.

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to similar questions, and also familiarize yourself with:
  * [the user guide](http://kubernetes.io/v1.1/)
  * [the troubleshooting guide](http://kubernetes.io/v1.1/docs/troubleshooting.html)

Again, thanks for using Kubernetes.

The Kubernetes Team
