### ISSUE TITLE
Question: kubectl fails to communicate with Kube-apiserver because of api versioning

### ISSUE THREAD

**Issue by gmelekh** [kubernetes/kubernetes#21747]
Hello kubernetes experts.
I try to create multi-master cluster on Centos 7 Atomic Host on a cloud.
The system include 3 master machines and 3 node machines.
I am focused on starting up the master machines.
I would like the kubelet to rump up all the services on startup.
Kubelet initialized with systemd ,watching manifests directory at /etc/kubernetes/manifests
kubelet starts kube-apisrver and podmaster according to manifests and podmaster elects master machines for kube-scheduler and kube-controller-manager.
I use following images:
 - kube-apiserver: gcr.io/google_containers/kube-apiserver:9680e782e08a1a1c94c656190011bd02
 - kube-scheduler: gcr.io/google_containers/kube-scheduler:34d0b8f8b31e27937327961528739bc9
 - kube-controller-manager: gcr.io/google_containers/kube-controller-manager:fda24638d51a48baa13c35337fcd4793

It looks like all necessary pods is up,but simple command   `kubectl version ` responds with 
```error: Failed to negotiate an api version. Server supports: map[v1beta1:{} v1beta2:{} v1beta3:{}]. Client supports: [v1].```

in kube-apiserver logs it looks like this:
```GET /api: (88.935µs) 200 [[kubectl/v1.0.3.34+b9a88a7d0e357b (linux/amd64) kubernetes/b9a88a7] 127.0.0.1:48772]```

Please advise.

**Comment by fabioy** [comment]
It looks like the api server is just really old (or a bad image), since it doesn't list the v1 endpoint. I'd suggest you pick up a newer image and try again.

Also, for these types of support issues, it may be faster/easier to have them in [StackOverflow].

Thanks.

**Comment by fabioy** [comment]
Please re-post your question to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases.

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to similar questions, and also familiarize yourself with:
   * [the user guide](http://kubernetes.io/v1.0/)
   * [the troubleshooting guide](http://kubernetes.io/v1.0/docs/troubleshooting.html)

Again, thanks for using Kubernetes.

The Kubernetes Team
