### ISSUE TITLE
Watch of 3rd party objects needs a test

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#21919]
A user report that it's broken in the slack channel: https://gist.github.com/cgilmour/4c8e721691f61e711fa0

```
E0224 21:54:28.145127   24219 errors.go:63] apiserver received an error that is not an unversioned.Status: no kind "ListOptions" is registered for version "romana.io/demo/v1"
```

**Comment by lavalamp** [comment]
@brendandburns

**Comment by lavalamp** [comment]
Also @smarterclayton and @caesarxuchao -- this probably broke with one of our recent refactors. The server should be accepting list options from any version, I thought?

**Comment by caesarxuchao** [comment]
FWIW, I think it's this line barf at the ListOptions:
https://github.com/kubernetes/kubernetes/blob/master/pkg/runtime/codec.go#L146

The parameter codec first decodes the query parameter to a versioned object and then convert it to the internal object. The code fails because it cannot create a "romana.io/demo/v1" ListOptions.

**Comment by smarterclayton** [comment]
The server should accept list options in the API version it is sent.  ListOptions should be in all third party groups.

**Comment by smarterclayton** [comment]
The thirdPartyResourceDataCreator should handle "ListOptions", which surprises me that it doesn't then respect the group.

**Comment by caesarxuchao** [comment]
I think we should add a wrapper around the api.ParameterCodec here: https://github.com/kubernetes/kubernetes/blob/master/pkg/master/master.go#L642

**Comment by caesarxuchao** [comment]
Putting together a PR now and will let you guys review.

**Comment by lavalamp** [comment]
I guess my point is, the list options are just there from the URL query parameters. The user didn't send a group. Why do we assume that value for the group rather than "/v1" or something?

**Comment by caesarxuchao** [comment]
My understanding is we want to allow options to evolve differently in different groups. We do have v1.ListOptions and v1beta1.ListOptions. And if a client sends requeset to extensions/v1beta1 endpoint, then it's expected to encode the ListOptions to v1beta1 and then convert it to query parameters.

**Comment by smarterclayton** [comment]
Mostly because the parameter codec is supposed to abstract that.  "virtual"
groups need to be implemented by the virtual "parameter codec".  The
statement on floating server objects (List, Delete etc) was that they have
a locked API schema, and we have a mechanism to do that via the scheme
which is registering them in a group.
