### ISSUE TITLE
Temporary pod

### ISSUE THREAD

**Issue by pjebs** [kubernetes/kubernetes#21925]
I have a use case and I can't find a solution from within the k8s way of doing things. Am I missing something or is it by design?

I want to have a single unified url for clients to connect through.
I want each new request to be routed to a brand new container that is kick started just for the request. The program on the container will exit straight after responding to request and hence docker will shut down the container. In fact the program will respond with an error if another client tried to connect while it is working on first request, hence another request must not be allowed to connect to it in the first place.

I'm assuming for the single unified url I need a service.
I'm not sure if a job is appropriate for managing my pod.
I also need everything to scale horizontally and create new nodes if no new pods can be made in node (hard to do well because the pods will shut down quickly after serving one request)
Not sure if a replication manager is needed or how to configure it since the number of pods will map 1 to 1 per request from user.

**Comment by navreetaft** [comment]
If you're on GCE, you can try the following pragmatic solution:

1.  Setup autoscaling on the kubernetes cluster through cloud console.  You can put a ballmark CPU utilization metric
1.  Create 1 job for each request, or setup one job to have `n` successful completions
1.  Code the job so that each task would be pulled from a queue or a database and run it to completion.

If your tasks take a few minutes, this will probably work.

I haven't tried this solution, so it might not work, but it might be worth a shot.

Some other things to think about:  If some tasks are bad and will always fail, you have to put some sort of logic for that scenario so that you can skip bad task(s) after a few retries and return a 'successful' completion, etc.

**Comment by pjebs** [comment]
The 'tasks' will only go for about 30 seconds.
I'll be using DigitalOcean and not GCE.
Are you saying that there is no easy solution with Kubernetes?

**Comment by navreetaft** [comment]
As far as I know, node autoscaling is not supported in k8s at this point in time.

Someone else might have a better solution for you.

**Comment by pjebs** [comment]
The node autoscaling is not really a deal-beaker for me.
The number one issue is really just kick starting 1 container per request and routing the request to the container.

**Comment by pjebs** [comment]
@fabioy Do you have any suggestions for a work-around?

**Comment by therc** [comment]
I think this sounds like #484. I also remember a similar discussion on another issue.

**Comment by therc** [comment]
No concrete solutions today, but also see https://github.com/kubernetes/kubernetes/issues/18623

**Comment by pjebs** [comment]
Is there any way I can use kubernetes to make a scalable iperf3 server? 
If not, then k8s has a serious limitation

**Comment by pjebs** [comment]
Would I be able to use kubernetes with AWS lambda to kick start a pod for a request and route request to iperf container?

**Comment by therc** [comment]
I'm not sure that this is limitation is "serious", since it's an unusual scenario. (And I speak as someone who's trying to overcommit GPUs...)
How many servers will you run concurrently at peak? how often are you spawning them? is anything else going to run on the cluster?
Perhaps Kubernetes is overkill for what you're trying to do. You could try being creative with readiness probes (http://kubernetes.io/v1.1/docs/user-guide/pod-states.html#container-probes) and autoscaling, but I'm not sure if you'll get pods to start quickly enough.

**Comment by pjebs** [comment]
Could someone at Kubernetes lobby Docker team to implement a timeout option for `docker run` which will destroy a container after some period of time. I have a solution but this feature would be very handy:

https://github.com/docker/docker/issues/1905

**Comment by therc** [comment]
I doubt Docker will bother, but you can set ActiveDeadlineSeconds on a Kubernetes pod.

**Comment by quinton-hoole** [comment]
This sounds like something that could be solved with a combination of Jobs and Cluster Autoscaling.  @erictune in case he wants to chime in.

**Comment by bgrant0607** [comment]
Kubernetes has HorizontalPodAutoscaler now.

Cluster autoscaling also exists on many platforms, such as GKE.

Event-driven FaaS platforms under development may facilitate this.

I can't imagine we'd implement features for this specific use case.
