### ISSUE TITLE
kube-apiserver: Failed to list *api.Endpoints: couldn't get version/kind

### ISSUE THREAD

**Issue by drngsl** [kubernetes/kubernetes#21941]
Hi!
I start my kube-apiserver server, in the log file, I see the same log:
`E0225 00:30:09.070061   10255 cacher.go:150] unexpected ListAndWatch error: pkg/storage/cacher.go:116: Failed to list *api.Endpoints: couldn't get version/kind; json parse error: json: cannot unmarshal number into Go value of type struct { APIVersion string "json:\"apiVersion,omitempty\""; Kind string "json:\"kind,omitempty\"" }`
And, this log is printed continuously and frequently.
I don't kown why kube-apiserver can not get api.Endpoints info.

kubernetes version:
`Client Version: version.Info{Major:"1", Minor:"1", GitVersion:"v1.1.7+e4e6878", GitCommit:"e4e6878293a339e4087dae684647c9e53f1cf9f0", GitTreeState:"not a git tree"}
Server Version: version.Info{Major:"1", Minor:"1", GitVersion:"v1.1.7+e4e6878", GitCommit:"e4e6878293a339e4087dae684647c9e53f1cf9f0", GitTreeState:"not a git tree"}`

**Comment by fabioy** [comment]
It seems like there's a bad build or configuration issue with your install.

But, to continue this, please re-post your question to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases.

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to similar questions, and also familiarize yourself with:
   * [the user guide](http://kubernetes.io/v1.0/)
   * [the troubleshooting guide](http://kubernetes.io/v1.0/docs/troubleshooting.html)

Again, thanks for using Kubernetes.

The Kubernetes Team

**Comment by thatsk** [comment]
I also got problem while using glcoud container
