### ISSUE TITLE
FailedMount/FailedSync error when multiple pods are scheduled on to same host

### ISSUE THREAD

**Issue by fangweili** [kubernetes/kubernetes#22008]
environment: Google Container Engine
master version: 1.1.7

RC config as:
...
      "spec": {
        "containers": [
          {
            ...
            "volumeMounts": [
              {
                "name": "my-storage",
                "mountPath": "/var/lib/mnt",
                "readOnly": true
              }
            ]
          }
        ],
        "volumes": [
          {
            "name": "my-storage",
            "gcePersistentDisk": {
              "pdName": "my-disk",
              "fsType": "ext4",
              "readOnly": true
            }
          }
        ],

when RC replica number is smaller than cluster size, everything works fine. when scale replica number to larger than cluster size, multiple pod will be schedule on same host, and will get error:

FailedMount	Unable to mount volumes for pod "xxx": Could not attach GCE PD "my-disk". Timeout waiting for mount paths to be created.
  2m		35s		2	{kubelet xxx}			FailedSync	Error syncing pod, skipping: Could not attach GCE PD "my-disk". Timeout waiting for mount paths to be created.

**Comment by fabioy** [comment]
Please re-post your question to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases.

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to similar questions, and also familiarize yourself with:
   * [the user guide](http://kubernetes.io/v1.0/)
   * [the troubleshooting guide](http://kubernetes.io/v1.0/docs/troubleshooting.html)

Again, thanks for using Kubernetes.

The Kubernetes Team
