### ISSUE TITLE
Upgrading to go 1.6

### ISSUE THREAD

**Issue by Pensu** [kubernetes/kubernetes#22039]
Folks at golang have released new golang version: https://groups.google.com/forum/#!topic/golang-announce/HQ7x813jurw

Do we have any plan to upgrade to go1.6? The reason I am asking is golang 1.6 is supported on couple of new architectures (case in point - ppc64le), where Kubernetes is not officially supported. It could be a good step in direction of getting those archs merged.

**Comment by luxas** [comment]
I'm working on multi-arch support #17981. See also all linked issues and especially #19769, where official ARM binaries are created. I'm also working on `ppc64le` and `arm64` support, and in the beginning I had those arches in the PR, but was forced to remove them when we reverted to `go1.4.2`. I have a #22149 for bumping go, but it seems we have a long way to go before we may do that.

But since #19769, it's super easy to cross-compile `ppc64le` and `arm64` locally anyway, just use `go1.5+`, add `ppc64el` and `aarch64` to `KUBE_DYNAMIC_CROSSPLATFORMS` and add `linux/arm64` and `linux/ppc64le` to `KUBE_CROSSPLATFORMS`, `KUBE_CLIENT_PLATFORMS` and `KUBE_SERVER_PLATFORMS`! I'm gonna file a PR for that as soon as #22149 is merged

**Comment by timothysc** [comment]
IMHO we should try to switch early and force resolution on the issues that arise.  It's entirely possible we'd need to mark a series of test as flakes for a period of time, but we seem to have pushed off a number of updates primarily due to GC issues on the api-server at scale. 

/cc @kubernetes/sig-scalability @rrati @kubernetes/rh-cluster-infra

**Comment by wojtek-t** [comment]
Yes - I agree that we should upgrade to higher versions of Go soon. We didn't do that for 1.2, because of scalability issues. But we can't stuck in Go 1.4.2 forever.
So, as soon as we are done with 1.2 release, we should really start looking into what was wrong with higher version of Go (we had problems even with Go 1.4.3) and: either workaround them in our code or push Go folks to fix them.

Note that we already have open issue: #20656 and Go folks are aware of it - we should just sit and do some progress on it.

BTW - I checked and we have 5 or 6 unit tests that are not passing with Go 1.6 - which we need to investigate (one of them is deep-hash test, which we can't afford disabling).

**Comment by eparis** [comment]
@DirectXMan12 for RH has been asked to try to put some time into @20656 along with our golang guy.

**Comment by wojtek-t** [comment]
@eparis - we also asked our Go fokls about; in fact I missed the fact that they were waiting for a response from us - just answered it and hopefully they will be able to help us.

**Comment by timothysc** [comment]
@wojtek-t as soon as it's ok(post 1.2), I'd like to start 1.6 migration.  Which history has taught us can be filled with behavioral changes.

**Comment by wojtek-t** [comment]
@timothysc - we are talking with Go folks right now - they are trying to debug our problems with Go 1.4.3 and Go 1.5. If/when they debug, I would like to first upgrade to Go 1.5, which should be just immediate at that point.

**Comment by luxas** [comment]
@wojtek-t So should I update #22149 to `go1.5.3`?

**Comment by spxtr** [comment]
It seems like a good idea to jump straight to 1.6 once the k8s 1.2 release is out. We might run into scalability issues again, but we should try to fix forward instead of rolling back to 1.4.2... again.

**Comment by wojtek-t** [comment]
@spxtr - we are already working with Golang folks. This is happening in the background.

**Comment by luxas** [comment]
I think this may be closed. 
Golang 1.6 is merged and the work of getting ppc64le in happens in #23931, #23697, #21617 and some other places as well

**Comment by spxtr** [comment]
We're still working on incorporating some of 1.6's new features, such as improved cross-compilation and vendoring, but I think this can be closed in favor of more specific issues.
