### ISSUE TITLE
PR Builder failed w/ unbound variable in E2E script

### ISSUE THREAD

**Issue by cjcullen** [kubernetes/kubernetes#22066]
```
./hack/jenkins/e2e-runner.sh: line 157: E2E_OPT: unbound variable
```
https://github.com/kubernetes/kubernetes/pull/21187#issuecomment-189386026
Another run passed immediately after.

**Comment by spxtr** [comment]
That's a confusing one. Turns out your PR needed a rebase, and rather than failing right away it used your old version of `e2e-runner.sh` which didn't have 83bfe2cfda0f90d1d1b9ed04684c8fe115f64fe2. That commit makes `E2E_OPT` optional.

We really should have Jenkins fail right away if it can't use Github's merge commit.
