### ISSUE TITLE
readinessProbe binary check KO while livenessProbe check OK

### ISSUE THREAD

**Issue by claudiu-stanciu** [kubernetes/kubernetes#22062]
Hello,

I have configured a readinessProbe on my pod with a binary which connects to my running server (in the same container) and retrieves some health information (like ready for traffic).

Configured as a readinessProbe, the binary fails to contact my server and get the required info. It connects on  a TCP socket.
But configured as a livenessProbe, it works as intended.

Configuration. Only changed readinessProbe to livenessProbe, to make it work.
```
"readinessProbe": {
              "exec": {
                "command": [
                  "/opt/bin/ready_probe",
                  "--check_ready_traffic",
                  "--service=myServer-service"
                ]
              },
              "initialDelaySeconds": 60,
              "timeoutSeconds": 5
            },
```

The service is for the server, to register it's host and port. This is OK.

Version used: kubernetes v1.1.0-origin-1107-g4c8e6f4

Thank you.

Kind regards,
Claudiu

**Comment by fabioy** [comment]
Please re-post your question to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases.

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to similar questions, and also familiarize yourself with:
   * [the user guide](http://kubernetes.io/v1.0/)
   * [the troubleshooting guide](http://kubernetes.io/v1.0/docs/troubleshooting.html)

Again, thanks for using Kubernetes.

The Kubernetes Team

**Comment by seveillac** [comment]
Now in http://stackoverflow.com/questions/35695058/kubernetes-readiness-probe-exec-ko-liveness-probe-same-exec-ok
