### ISSUE TITLE
Validate no replicationController overlap.

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#2210]
What happens when you make two replication controllers with the same selector, and different number of replicas?  Do they battle it out, killing and starting pods. 

Consider a validation that makes sure that selectors are disjoint.  

@bgrant0607 assures me that this is possible, and that the label/selector semantics are carefully crafted to make just this sort of check possible.

**Comment by bgrant0607** [comment]
cc @davidopp

**Comment by bprashanth** [comment]
Since I'm working on refactoring replication controller to use generic etcd, is this something we want for v1?

**Comment by bgrant0607** [comment]
At least a best-effort check would be nice, but if it's hard we should punt it to post-1.0. It can't be done in validation, unfortunately. See #2395 and #2457. @lavalamp had thoughts about how/where it should be done. I could live without the background checking for 1.0.

**Comment by jayunit100** [comment]
related #11990 to clarify the current state of things

**Comment by bgrant0607** [comment]
The relationship between a controller and the pods whose lifecycles it manages is exclusive: there can be only one controller.

In other cases of such exclusive relationships we have an established pattern. The binding of a pod to a node is an example: the pod refers to the node. PersistentVolumeClaim to PersistentVolume is similar. 

Controllers are a well established pattern in Kubernetes. We have several controllers in flight: Daemon, Job, etc.

We do want users to be able to write their own controllers, such as the DiurnalController #10881. We're adding plugin APIs to make those possible to configure in a first-class way #991.

I therefore propose that we add a field to Pod, `controllerRef`, to identify the controller responsible, which could also obsolete the created-by pod annotation. Controllers that didn't match the field would not try to take over the pod. Orphaning a pod would then require an explicit update to the pod, but we've discussed doing that, anyway, to make cascading deletion more robust and more automated #1535 #12143. Adoption would only occur in the case that the field were unset, as with other /binding cases. /binding on pods is currently used for scheduling, but a similar subresource could be created for controllers. We'd want to implement Generation and ObservedGeneration for pods, in order to make it possible to ensure RAW consistency.

Atomic validation of no overlap isn't possible without enforcing some convention, such as: at least one label key needs to be in common for all pods within a namespace, which must have a unique value for each disjoint selector (i.e., each controller). (And we'd need multi-object transactions #2904.)

However, generation of unique labels by default could reduce the likelihood of overlap #12298. In particular, see: https://github.com/kubernetes/kubernetes/issues/12298#issuecomment-128636518

We could provide a non-atomic best-effort validator, likely client-side.

**Comment by sdminonne** [comment]
@bgrant0607

Just a fact: in case `controllerRef` will be added to pod  I would say that the label selector should be removed by controllers (to avoid inconsistency), right?

If I had to choose between adding `controllerRef`, removing `label selector` and adding generation of unique labels by default I would vote for adding `controllerRef`. My point is that  labels should be kept as much as possible in user land.

If I'm not missing something labels on pods will be used exclusively for services and node selection keeping `controllerRef` to track controller ownership.  

The message for the user in this case would be: 
* design your labels to organize your services (and nodes)
* controllers will grant availability and running consistency

**Comment by davidopp** [comment]
I like this idea a lot.

If I understand the proposal, the idea is
* when a controller C1 creates a Pod, it stamps it with `controllerRef = C1`
* if controller C1 wants to give up control over a Pod, it clears `controllerRef`
* if controller C2 wants to take over control of a Pod with un-set `controllerRef`, it sets `controllerRef = C2`

On the issue @sdminonne mentioned, IIUC the only use for the label selector in the controller would be to specify which Pods it should adopt that have un-set `controllerRef` field. That is:
* if a Pod is created by controller C1, and then the user changes the labels on it so that they match the label selector of controller C2, but does not clear or change the `controllerRef` field, then the Pod continues to be controlled by controller C1
* analogously, if a Pod is created by controller C1, and then the user changes the `controllerRef` field to C2 but does not change the labels on the Pod, then the Pod will still be taken over by controller C2. 

Or to put it another way "you are welcome to confuse yourself by manually making a Pod's `controllerRef` not match its labels, but no properly-behaving component of the system will do this, and if it happens the `controllerRef` trumps the label selector in determining which Pods a controller controls."

Does that sound reasonable?

**Comment by derekwaynecarr** [comment]
I like the idea of a controllerRef

Assume you would want this field to be in ObjectMeta and not be pod-specific?

**Comment by bgrant0607** [comment]
I agree with @davidopp's last comment: A controller should not continue to manage a pod whose labels do not match its selector. RCs should unset `controllerRef` if the labels no longer match its selector. This is similar to how Daemon (#10210, #13181) kills its pods on nodes no longer matching its template's nodeSelector.

I also agree with:
* when a controller C1 creates a Pod, it stamps it with `controllerRef = C1`
* if controller C1 wants to give up control over a Pod, it clears `controllerRef`
* if controller C2 wants to take over control of a Pod with un-set `controllerRef`, it sets `controllerRef = C2`

@derekwaynecarr I'd put `controllerRef` in the `dependencies` block proposed in #3585. Deployment's control over RCs might be another use case.

**Comment by bgrant0607** [comment]
To be clear: I do not envision changing the role or behavior of the selector: The selector identifies the pods that should be managed by the controller.

**Comment by davidopp** [comment]
> To be clear: I do not envision changing the role or behavior of the selector: The selector identifies the pods that should be managed by the controller.

Unless/until we have an ACL scheme that prevents users from modifying `controllerRef`, the situation can definitely arise (not just as a race condition, but permanently) that the `controllerRef` points to controller C1 but the Pod's labels match the label selector for controller C2 (and not for C1). AFAICT we have only two choices in this situation:
(1) C1 is treated as the owner of the Pod
(2) C2 is treated as the owner of the Pod

I proposed (1). You appear to be proposing (2). What are the arguments for and against each of these choices? With (2), it's not clear to me what value `controllerRef` provides, since it doesn't actually indicate which controller is controlling the Pod.

**Comment by bgrant0607** [comment]
See comment https://github.com/kubernetes/kubernetes/issues/2210#issuecomment-135588169

If a pod's labels no longer match C1's selector, controllerRef should be unset, so that the pod may be adopted by a controller whose selector does match its labels.

**Comment by soltysh** [comment]
@sdminonne mentions `controlerRef` in #17787 which I found very useful. Is somebody working on a PR implementing that feature?

**Comment by mikedanese** [comment]
I think @bgrant0607 is planning on writing a design proposal for that, see #14961

**Comment by thockin** [comment]
Since this came up in a conversation, it's worth mentioning that "If a pod's labels no longer match C1's selector, controllerRef should be unset" means that (give stateless controllers) we have to explicitly select for "controllerRef=me" and the main selector, in order to identify the relative complement (pods that claim to be managed by me but don't match my selector)

**Comment by mqliang** [comment]
I thin `controllerRef` is not helpful to solve the overlapping problem, but we can use it to speed up FindControllerForPod and FindPodsForController.


###Speed up FindControllerForPod and FindPodsForController
----

K8s use lable and selector to couple Pod and ReplicaController/Job/Daemonset, it's flexible but not efficient, sicne when we want find 
the ReplicaController for a pod, we need traverse all the ReplicaController to see if their label/selector is matcing.

Adding a namespace index could help a lot when there are lots of namespaces in the cluster, so that filter first on namespace and then
search in that namespace for a match, see https://github.com/kubernetes/kubernetes/pull/17277  


#### Speed up FindControllerForPod
----
Add a "equivalent pod" cache: usually, a rc will have a replica number 3-5, which means there are 3-5 pods will have same 
labels(and thus same rcs), so there is no need to search the matching rc for every "equivalent" pods. We can search the matching
rc for the first pod, and cache the result. see https://github.com/kubernetes/kubernetes/issues/18972

#### Speed up FindPodsForController
----
Adding a "equivalent pod" cache could help a lot when FindControllerForPod, but if we want FindPodsForController, we still need
traverse all the pods and find the matching one. To speed up FindPodsForController, we could add a `controllerRef` field to pod:

#### Implement Detail

1) When RC1 create a pod, it stamps it with `controllerRef = RC1`

2) When ControllerManager want FindControllerForPod, if `pod.spec.controllerRef != ""`, it should check if the `controllerRef = RC1` 
is valid, if the `controllerRef` is invalidt(RC1 not exist or their label/selector doesn't match), or `pod.spec.controllerRef == ""`
traverse all the ReplicaController to find the matching one and update the `controllerRef` field

3) ControllerManager save all listed&watched pods in its cache using the `controllerRef` as index. For pods with `controllerRef == "", 
use a particular string as their index.

4) So when find pods for RC1, just use the index, we can get all pods with `controllerRef = RC1`, ***we should check again all the pods to see if their `controllerRef` is
 valid***, if the `controllerRef` is invalid(mean if the `controllerRef` and label/selector disagree), set the `controllerRef` 
 field as empty and update. We should also check all the pods with `controllerRef == ""`, to see if there are any matching one, if we 
 find some, update their `controllerRef` field.

**Comment by mml** [comment]
What's our disposition these days on where this goes?  Create the dependencies block mentioned in #3585?  I could argue about the name a bit as `relationships` seems a bit more general, but I do think we should have a distinct place to put this rather than using a special annotation key as we do now with creator ref.

**Comment by mqliang** [comment]
I am confused about the functionality of  `controllerRef`, since  `controllerRef` and selector may conflict:
* If we match pod based on `controllerRef` totally, I'd like hat the label/selector should be removed. 
* If we match pod based on label/selector, `controllerRef` is meaningless.

But if we add a `controllerRef` to track controller ownership(which could also obsolete the created-by pod annotation) and exposed to user, so that make ***debug easier***, I like the idea. For example, add a `relationshipRef` block to `ObjectMet`:
type ObjectMeta struct {
	/*
	*/
	*ReplicaSetRef 
	*DaemonSetRef
	*JobRef
}

**Comment by mml** [comment]
Having just been around this area while implementing drain and teaching NodeController to ignore node timeouts WRT DaemonSet pods, I'd like to grab this and unify our implementation of it.

I need to think about component compatibility and roll-forward/roll-backward semantics before barging in.

Also, @davidopp and @bgrant0607 can you speak to my previous question regarding where this should go?

**Comment by bgrant0607** [comment]
@mml I'll have to get back to this once 1.2 fires subside a bit.

@mqliang See #14961 for some discussion about scenarios where labels/selectors are needed.

**Comment by mml** [comment]
> If a pod's labels no longer match C1's selector, controllerRef should be unset, so that the pod may be adopted by a controller whose selector does match its labels.

"should be unset" means, AIUI, that it's C1's job to fix the controllerRef.

What if C1 is deleted without cascade, or if it's lost due to a bug, or the removal of the controllerRef fails due to a bug or timeout, or the component that manages C1 (imagine it's a third-party controller of some kind) is turned down.  In all these cases we have a pointer to nowhere.

Two questions:

1. Should a pointer to a nonexistent controller be treated the same as no controller?
2. If not, should some process periodically garbage collect dangling controllerRefs?

**Comment by bgrant0607** [comment]
We're now considering this for Deployment:
https://github.com/kubernetes/kubernetes/pull/21030#issuecomment-183380494

@mml Was there a specific controller you wanted controllerRef for (DaemonSet?), or does it need to be present in all of them to solve your problem?

cc @janetkuo @kargakis @madhusudancs @mqliang

**Comment by bgrant0607** [comment]
@mml The case of a third-party controller being turned down is interesting. I don't think we have worked out the model for how that would work. We need to ensure the controller resources are deleted, too. We also don't have a way to ensure a third-party controller uses or respects controllerRef, so I'd leave that out of scope for now.

I'll summarize the controllerRef on #14961.

**Comment by mml** [comment]
### Roll forward / roll back

Suppose version N is the last version where controllers don't set a controllerRef.  When upgrading to N+1 (and assuming all controllers get upgraded together, which they do with the current single controller manager component) the N+1 controllers will identify all of their pods as orphaned and adopt them (correct).

When we roll back to N, the controllerRefs will still be in the storage, but they won't be visible via the API and they won't get updated if the pods get adopted by a new controller.  When we roll forward again to N+1, controllers will see dangling controllerRefs.  If they treat this the same as "no controller", adoption will work fine.

### Version skew

There are multiple places we'd like to refer to this: `kubectl`, `NodeController`, and all the pod controllers.  `kubectl` has no way to know which version of the controllers is running.  How should it decide whether or not to trust controllerRef?  What is our defined level of supported version skew between `kubectl` and the controllers?

### Races

Even if the versions match, an admin could issue `kubectl drain` before the controllers have had a chance to complete adoption.  More generally, if controllerRef handoff isn't synchronous/atomic there will always be some window where managed pods appear to be unmanaged.  Those cases are fairly safe because they'll fail to drain a node rather than draining it incorrectly.

If `NodeController` handles a node timeout before the daemon set controller has adopted all its pods, we will delete daemon set pods when we shouldn't.

**Comment by erictune** [comment]
The `collection-uid` label that I'm adding to Job is similar to `controllerRef`.  (See [selector-generation.md](https://github.com/kubernetes/kubernetes/tree/docs/design/selector-generation.md) ).
The question is whether it is similar enough to use instead of controller-ref?  Or if we want both?

Options:
- *just controllerRef*:  disadvantage of this approach is that:
  - users have to understand labels and selectors before they can get started with kubernetes, and have to type selector and labels into all controller specs.
- *just selector-generation*: disadvantages of this approach are: 
  - no easily-followable link to controller (user has to list all controllers and find the one with the matching uid). 
  - if applied to replicaSet, contradicts what we have taught people about how to use replicationControllers in all our docs and examples.  if not applied to replica-set, then controllers are inconsistent.
- *both controllerRef and selector-generation*: disadvantage is:
  - there are now two ways to map between controllers and pods.  Seems confusing.  

I think I know which I prefer, but would like to hear from all interested parties, and in particular @mml @bgrant0607

**Comment by bgrant0607** [comment]
@erictune I was envisioning both in my proposal on #14961. 

controllerRef will work with manual selectors, which is another disadvantage of selector generation only. 

I view controllerRef as an implementation detail. Users won't set it themselves. I wouldn't mention it in our introductory user documentation.

Currently users do have to put labels into pod templates, but they don't have to write selectors for controllers, since we set those by default from the pod template labels. For ReplicaSet and Deployment that may be useful to retain even if we add the type of automatic label/selector generation that you're adding to Job.

While I do highly value consistency in the API, Job is a different use case than our controllers for continuously running applications. For instance, I expect Jobs to be a lot more expendable and short-lived. OTOH, ReplicaSets, Deployments, and DaemonSets will tend to be more durable and pet-like. Their pod labels are expected to be meaningful. Deployment and DaemonSet will support update propagation, and there are a number of scenarios where orphaning and adoption make sense, which would require use of manual selectors.

One of the original motivations for the current style of selector was to compel users to put useful distinguishing labels on their pods rather than just embed such identifying information into object names.

Anyway, over time I'd like to see more tooling developed for Kubernetes to create these resources for users, which could hide some of these details and also embody best practices.

**Comment by bgrant0607** [comment]
Also, if we encourage auto selectors for ReplicaSet, Deployment, etc. then I imagine it will become common to add a "service: myservicename" label to pods for matching their services' selectors. It's not my favorite pattern, would be sufficient for a number of use cases.

**Comment by gmarek** [comment]
@mml are you working on it, or can I take it over?

**Comment by davidopp** [comment]
@mml isn't working on this.

**Comment by mikedanese** [comment]
fyi https://github.com/kubernetes/kubernetes/pull/35298

**Comment by kargakis** [comment]
I think overlapping controllers is an obsolete topic with the introduction of owner references in 1.6.

**Comment by enisoc** [comment]
My understanding is that ControllerRef was about protecting the system if the user creates overlapping controllers, but we still don't want the user to do that. If that's the case, we may still want to consider some mechanism for discouraging it.

**Comment by ddysher** [comment]
@enisoc seems kubectl still only uses selector to find matching pods, result in confusing outputs

```sh
$ kubectl describe rs replicaset-2
Name:           replicaset-2      
Namespace:      default
Selector:       environment=prod
Labels:         environment=prod
Annotations:    <none>
Replicas:       2 current / 2 desired
Pods Status:    3 Running / 0 Waiting / 0 Succeeded / 0 Failed
Pod Template:
  Labels:       environment=prod
  Containers:
   created-from-replicaset:
    Image:              nginx
    Port:               
    Environment:        <none>
    Mounts:             <none>
  Volumes:              <none>
Events:
  FirstSeen     LastSeen        Count   From                    SubObjectPath   Type            Reason                  Message
  ---------     --------        -----   ----                    -------------   --------        ------                  -------
  5m            5m              1       replicaset-controller                   Normal          SuccessfulCreate        Created pod: replicaset-2-39szb
  5m            5m              1       replicaset-controller                   Normal          SuccessfulCreate        Created pod: replicaset-2-470jr
```

It reports three running pods (another one being managed via another controller with the same selector), should we add more option while listing?

```go
options := metav1.ListOptions{LabelSelector: selector.String()}
```

**Comment by bgrant0607** [comment]
ownerReferences is the solution to this.
