### ISSUE TITLE
Log reason for failure to launch pod

### ISSUE THREAD

**Issue by aknuds1** [kubernetes/kubernetes#22151]
Kubelet should not only log that it failed to launch a pod, but also the reason for this. Currently I have to dig in (inactive) container logs in order to get at this. Using version v1.1.2+3085895.

**Comment by bgrant0607** [comment]
cc @yujuhong

**Comment by yujuhong** [comment]
@aknuds1, did kubelet fail to create/start your container, or your container die quickly after starting. For the former, I believe we surface the error in both events and the pod status. If it wasn't the case in your cluster, could you provide more information on the failure so that we could fix it? For the latter, kubelet doesn't doesn't show logs of the container. There is an open issue to add some O(200 bytes) of container logs in the pod status #15826.

**Comment by aknuds1** [comment]
@yujuhong Looks as if the (apiserver) container died quickly after starting due to the inability to find a certificate.

**Comment by aknuds1** [comment]
I've commented in #15826.

**Comment by yujuhong** [comment]
> I've commented in #15826.

Let's move the discussion there. Closing this issue.
