### ISSUE TITLE
Annotate Upstream tests

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/kubernetes#22184]
*Background*

Ginkgo skip and focus are not good at filtering tests at a high level, rather, they are built to focus on the tests' hierarchichal data model (Describe/By/It) themselves.

*Our goal*

We want to run upstream tests from a binary which 
- has both downstream and 
- also has upstream tests in it.

*Implementation Details*

Wrap `It()` in the kube e2e framework as `KIt`, such that `KIt` automatically adds a Kubernetes specific annotation to every test.  We can even export the annotation as a public variable so downstream test runners can invoke upstream tests in a type safe way by adding the filter string programmatically in their wrappers to e2e.go.

**Comment by jayunit100** [comment]
Can we assign this to @timothysc ?  cc @kubernetes/sig-testing

**Comment by timothysc** [comment]
> KIt automatically adds a Kubernetes specific annotation to every test

The motivation here is to use leverage ginkgo.focus easily to execute upstream only tests for folks who extend downstream.

**Comment by ixdy** [comment]
Why do you need upstream and downstream tests in the same binary? It'd simplify things a lot to keep them separate.

**Comment by jayunit100** [comment]
Tests should be easy to run and filter.. This tagging makes them so.  The debate around simplicity is worth having, but I think the debate here is more around the fact that the tests, for intrinsic reasons, should have a unified namespace that is understood by the test framework we are using.

**Comment by timothysc** [comment]
> Why do you need upstream and downstream tests in the same binary?

B/c openshift is a strict super-set of kubernetes.  

> It'd simplify things a lot to keep them separate. 

Building multiple artifacts is also not tenable.  Extending via suites would be the ideal solution, but ginkgo is sadly crippled in this regard.  Adding a prefix for filtering is a low cost alternative, which will allow for "easi-er" consumption.

**Comment by ixdy** [comment]
I still don't understand why you're trying to put these all in the same namespace. Ginkgo works fine for this as long as you keep the suites in separate packages, as it recommends.

Adding this tag which changes based on the environment will make aggregating third-party test results more difficult, since the names will no longer match.

**Comment by timothysc** [comment]
> I still don't understand why you're trying to put these all in the same namespace.

Kubernetes is a godep for origin.  Building a potentially mutable set of binaries is less clean, then subsuming via library.   The multiple binaries approach works if it's in the same repository, and choose to launch via ginkgo mechanics.  However, when you span repos via Godeps, it's not clean at all.   Ideally I would like suite to correspond to library, but ginkgo does not have the capability yet.

**Comment by ixdy** [comment]
OK, thanks, that is a helpful explanation of the problem.

If we were to move e2e tests out of kubernetes/kubernetes (something we've vaguely been discussing), would this make things more, less, or the same level of painful?

**Comment by timothysc** [comment]
> If we were to move e2e tests out of kubernetes/kubernetes

I don't think you would want to do that, the deps are 1:1 with the code itself.  You would constantly need to godep kubernetes/kubernetes to keep them in sync just to run the tests.  If the tests were pushed to use only REST apis then that may be possible, but that is a lot of untangling.

**Comment by ixdy** [comment]
OK, since I haven't looked at your usage (since I'm not sure where to look), I'm just blindly speculating, but I'm guessing that you import kubernetes/test/e2e both to get the utility functions as well as the test cases. And because everything is in the same namespace, and because of the way Ginkgo sets up test specs, simply importing test/e2e pollutes everything into your Ginkgo test spec namespace. Is this correct?

Assuming so, I feel a slightly better way to achieve this would be something like the following:
 * move utility functions into their own package (test/e2e/util? cause we don't have enough pkgs named `util` yet.)
 * for openshift/origin, create a dummy e2e package which imports kubernetes/test/e2e to get the core k8s e2e tests. You should be able to easily build this artifact without any godep troubles.
 * additionally create a separate e2e package for the openshift/origin tests, but only import the test/e2e/util package.

By having two separate packages, you can easily select the tests you want to run. It keeps openshift/origin stuff out of kuberntes/test/e2e. And it cleans up the utility functions, which really should have been in a separate package anyway.

It's not as quick-and-easy a fix as #22206, but it feels a lot more maintainable in the long run.

**Comment by timothysc** [comment]
Your suppositions are mostly correct, and I'm not opposed to the approach over time.  But as of today, #22206 is a easy fix, and honestly I think it's slightly cleaner then what was there originally, which was little/no uniformity...  In general, I believe wrapping the dependencies in an envelope letter idiom helps isolate the monolithic dependency graph we have created in the code-base.  We have done with a number of other dependencies through creation of our own interfaces, and the change proposed is minor and a step in that direction.

**Comment by jayunit100** [comment]
from @kubernetes/sig-testing i dont think theres much opposition to extending the upstream package anymore, but i think jeff still has some concerns.  We can tackle the concerns in the PR moving forward .. if thats ok with  @ixdy....

**Comment by ixdy** [comment]
IMO having a custom `KDescribe`/`KIt` is not going to work. We'll likely end up with a mix of "regular" `Describe`/`It`, along with the custom version, and there's not really a good way to enforce it.

**Comment by timothysc** [comment]
The same could have been said for etcd, but we forced the kraken behind the storage interface, as well as several other dependency sprawls in the codebase.
