### ISSUE TITLE
launching flannel after stopping docker not working

### ISSUE THREAD

**Issue by geoHeil** [kubernetes/kubernetes#22256]
Hi,

following the instructions from: https://github.com/kubernetes/kubernetes/blob/release-1.1/docs/getting-started-guides/docker-multinode/master.md

Please note I run on `docker.sock` as `docker-bootstrap.sock` does not seem to exist.

```
sudo /etc/init.d/docker stop
[ ok ] Stopping docker (via systemctl): docker.service.
gheiler@testCluster:~/kubernetes/docs/getting-started-guides/docker-multinode$ sudo docker -H unix:///var/run/docker.sock run -d --net=host --privileged -v /dev/net:/dev/net quay.io/coreos/flannel:0.5.0
docker: Cannot connect to the Docker daemon. Is the docker daemon running on this host?.
See 'docker run --help'.
```

How can a docker-pull work if docker is shut down?

If I do not shut down docker I can pull the image:

```
sudo service docker start
gheiler@testCluster:~/kubernetes/docs/getting-started-guides/docker-multinode$ sudo docker -H unix:///var/run/docker.sock run -d --net=host --privileged -v /dev/net:/dev/net quay.io/coreos/flannel:0.5.0
55efe1587e97ba358b3ab7d63e42c72f78f70f06af123a1787ef1251381a5467
gheiler@testCluster:~/kubernetes/docs/getting-started-guides/docker-multinode$ sudo docker -H unix:///var/run/docker-bootstrap.sock exec 55efe1587e97ba358b3ab7d63e42c72f78f70f06af123a1787ef1251381a5467 cat /run/flannel/subnet.env
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
```

However it stil fails as the `/run/flannel/subnet.env` does not exist in the /kubernetes/docs/getting-started-guides/docker-multinode directory

**Comment by xiangpengzhao** [comment]
Please post such question or request for support to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes).

Before posting a new question, please search stackoverflow for answers to similar questions, and also familiarize yourself with:

  * [user documentation](http://kubernetes.io/docs/)
  * [troubleshooting guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/)

Since the guide in this issue is outdated, we are closing the issue. @thockin
