### ISSUE TITLE
Please provide some mechanism for giving specific pull secrets to pull infra image which is on an authenticated registry

### ISSUE THREAD

**Issue by wjiangjay** [kubernetes/kubernetes#22344]
checked with the code on https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockertools/manager.go#1612

```
func (dm *DockerManager) createPodInfraContainer(pod *api.Pod) (kubecontainer.DockerID, error, string) {
......
	container := &api.Container{
		Name:            PodInfraContainerName,
		Image:           dm.podInfraContainerImage,
		Ports:           ports,
		ImagePullPolicy: podInfraContainerImagePullPolicy,
		Env:             dm.podInfraContainerEnv,
	}

	// No pod secrets for the infra container.
	// The message isn't needed for the Infra container
	if err, msg := dm.imagePuller.PullImage(pod, container, nil); err != nil {
		return "", err, msg
	}
......
```

It pulll the infra image with the hardcode "nil" pullsecrets, so we can not pull an infra image on an authenticated registry.

Actually we can pre-pull the image on every node, but this is not a good idea.

**Comment by mdshuai** [comment]
@kubernetes/rh-cluster-infra

**Comment by jianlinliu** [comment]
Add some detail steps:
1. set up openshift v3 on an clean rhel os without pre-pulling infra images
2. Make sure point infra image to an authenticated registry.
imageConfig:
  format: <authenticated-registry>/openshift3/ose-${component}:${version}
  latest: false
3. Trigger the first deployment.
$ oc get po
NAME                       READY     STATUS              RESTARTS   AGE
docker-registry-1-deploy   0/1       ContainerCreating   0          1h
$ oc describe po docker-registry-1-deploy
<--snip-->
Events:
  FirstSeen	LastSeen	Count	From					SubobjectPath	Reason		Message
  ─────────	────────	─────	────					─────────────	──────		───────
  1h		1h		1	{default-scheduler }					Scheduled	Successfully assigned docker-registry-1-deploy to ip-172-18-13-193.ec2.internal
  1h		2m		19	{kubelet ip-172-18-13-193.ec2.internal}			FailedSync	Error syncing pod, skipping: failed to "StartContainer" for "POD" with ErrImagePull: "image pull failed for <authenticated-registry>/openshift3/ose-pod:v3.1.1.908, this may be because there are no credentials on this request.  details: (Error: image openshift3/ose-pod:v3.1.1.908 not found)"

  1h	5s	432	{kubelet ip-172-18-13-193.ec2.internal}		FailedSync	Error syncing pod, skipping: failed to "StartContainer" for "POD" with ImagePullBackOff: "Back-off pulling image \"<authenticated-registry>/openshift3/ose-pod:v3.1.1.908\""

**Comment by ncdc** [comment]
cc @kubernetes/rh-cluster-infra @kubernetes/sig-node do you all think we should add a flag to the kubelet to specify a pull secret to use to retrieve the pod infra container?

**Comment by vishh** [comment]
Why is the infra image in a different repo? Why not use the default infra image?

**Comment by eparis** [comment]
People use computers disconnected from the internet and/or may not trust the pause image created by google...

**Comment by mdshuai** [comment]
@vishh Now for kubelet it has parameter "--pod-infra-container-image=", if we use a private registry, there is no place to configure the secret for pull it.
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockertools/manager.go#L1605-L1607

**Comment by hurf** [comment]
> People use computers disconnected from the internet and/or may not trust the pause image created by google...

There's one thing called GFW. Private repo may be our best solution. Eagerly looking for this feature. @dchen1107 @Random-Liu

**Comment by vishh** [comment]
This feature +1! Is anyone working on a patch.

**Comment by Random-Liu** [comment]
I don't think we could use pull secret for all pods. Apiserver is also running as a pod. If we always pull pod infra container image with secrets, how could we start apiserver?

**Comment by Random-Liu** [comment]
@wjiangjay @mdshuai @hurf It is easy to add a flag to pull infra container image using the same secrets with other user containers in the same pod. But I'm not sure whether that will meet your requirement.

**Comment by vishh** [comment]
@Random-Liu: The goal is to fix [this line](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockertools/manager.go#L1633). We can inject docker config through flags. We can also consume a statically defined secret instead of docker config.

**Comment by Random-Liu** [comment]
@vishh Statically defined secret sgtm~ :)

**Comment by ncdc** [comment]
@vishh @Random-Liu what do you mean by a statically defined secret? Something like "if a secret called infra-pod (or whatever) exists, use it"?

**Comment by ncdc** [comment]
Or are you talking about a path to a json/yaml file containing an `api.Secret`?

**Comment by Random-Liu** [comment]
@ncdc I think it's something like the second one.

**Comment by ncdc** [comment]
Yeah, I realized that after reading the comments above about the apiserver. Working on this now.

**Comment by Random-Liu** [comment]
@ncdc Cool, thanks!

**Comment by aveshagarwal** [comment]
Sent a PR to address this: https://github.com/kubernetes/kubernetes/pull/23686

**Comment by ncdc** [comment]
This is possible today using http://kubernetes.io/docs/user-guide/images/#configuring-nodes-to-authenticate-to-a-private-repository. Can we close this issue?
