### ISSUE TITLE
Validate that a container does not try to mount two volumes to the same path

### ISSUE THREAD

**Issue by pmorie** [kubernetes/kubernetes#22369]
Currently there is no validation to prevent a container from doing this, but there should be.

@derekwaynecarr

**Comment by thockin** [comment]
It's really not even "the same path" but "any sub-path of another mount".
E.g. if I mount vol-a on /foo and volb-b on /foo/bar, any other container
using vol-a gets, at best, a `bar` directory that is empty.

On the other hand - is this really a bad thing to allow?  It seems a little
delicate but not invalid.  Mounting onto the exact same path is not likely
to be useful, I guess, whereas sub-mounting might be.  I guess I just
convinced myself that you are right.

**Comment by derekwaynecarr** [comment]
For context, I ran into this for the following scenario:

1.  I have some files that are secret in a `Secret`
2.  I have some files that are not secret in a `ConfigMap`
3.  My application expects the set of files to be in `/etc/myapp/config`
4.  I wanted to mount both to the same path, but then realized, we probably don't support this ;-)

I am not sure how uncommon this is where applications co-mingle secret and not secret files in a common configuration space, but something tells me its not that uncommon.

**Comment by thockin** [comment]
So I think we should validate that two volume Mounts don't use the same
path, because it is just impossible to imagine a case where that is useful
or correct.

As for mixing different sources in a single virtual mount dir, or even
projecting single files into extant dirs - we have issues open for those.
I think the latter is way more interesting in general.
