### ISSUE TITLE
Supported versioned client libraries in multiple languages

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#22405]
We need (in priority order):
- Go
- Python
- Javascript
- Java
- Ruby

See also #22389

cc @lavalamp

**Comment by AdoHe** [comment]
+1  I can help with Go&Javascript&Java

**Comment by ethernetdan** [comment]
+1 Happy to help with Go

**Comment by AdoHe** [comment]
@ethernetdan seems you are interested in this, guess we can start doing some prototype.

**Comment by bgrant0607** [comment]
See also #5660

**Comment by bgrant0607** [comment]
@AdoHe @ethernetdan 

There are a number of hand-written clients -- do a google search. We also have not-up-to-date links to some in our docs. They might be good starting points. For instance, the Fabric8 client is worth a look.

But I'm looking for a way to auto-generate the bulk of them, since they'll otherwise bit rot rapidly.

A few people of tried to generate them via swagger. We need to improve swagger support for that to be a good approach.

We're also looking into protobuf #8132. What do you think about that?

**Comment by bgrant0607** [comment]
See also #28559, #12290, #11606, #7584, #5660

**Comment by dims** [comment]
Over at OpenStack, we are maintaining a python client generated from swagger:
http://git.openstack.org/cgit/openstack/python-k8sclient/

**Comment by jimmidyson** [comment]
fabric8's [Java client](https://github.com/fabric8io/kubernetes-client) is pretty widely used now. Users seem to like the fluent DSL. We are looking to move to protobuf for version 2 if that is a recommended approach, but trying to retain a fluent DSL. We'd be happy to contribute to an official supported Java client moving forward.

**Comment by mbohlool** [comment]
A python client is created and in pretty good shape here: https://github.com/kubernetes-incubator/client-python

java and javascript is next. 

@jimmidyson lets sync up on java client.

**Comment by jimmidyson** [comment]
@mbohlool Hey! Any news on this? @iocanel and I were just discussing the possibility of contributing the fabric8 kubernetes-client to Kubernetes org if it's something the community are interested in? Honestly it has a reasonable amount of traction in the community and unfortunately we don't have the cycles to maintain it by ourselves right now.

**Comment by mbohlool** [comment]
@jimmidyson @iocanel, I looked at fabric8 and it looks pretty good. But one of the important features of a supported/blessed client is being up to date with latest API changes. I've achieved that for [client-python](https://github.com/kubernetes-incubator/client-python) by generating it from k8s OpenAPI spec and I would like to do the same for java.

I was written a proposal for a fluent interface (for both java and python) but I realized both generated client make it easy to create objects in a semi-fluent way. I am going to share a link to the document I've started but only look at the example part. I did not finish the document so the rest of it is pretty messy. I would also want to add a fabric8 example there to compare different approaches.

https://docs.google.com/document/d/17pZnh4k4R7ka8JS83eQ3smTxQTod9IKdCAUEuyX1YmY/edit#

At this step my (in progress) conclusion is we do not gain much by adding fluent support to OpenAPI and swagger-codegen. Generated clients are look good. But we may be able to add (more?) fluent interfaces on top of what it has. But I would really like to do it in a O(1) manner and keep O(n) files intact so we can update client after each release (my definition of O(1) generated files are like things like rest client, etc. and O(n) generated files are models and API files generated for each type and api call). Would love to discuss this in more detail and reach to a conclusion about a supported java client.

**Comment by iocanel** [comment]
In the [Fabric8 Kubernetes Client for Java](https://github.com/fabric8io/kubernetes-client) we are using the following code generation chain:

1. [From golang source to json schema](https://github.com/fabric8io/kubernetes-model/blob/master/cmd/generate/generate.go)
2. [From json schema to Java Pojos](https://github.com/fabric8io/kubernetes-model/blob/master/kubernetes-model/pom.xml#L101)
3. [From Java Pojo's to Fluent Interfaces and Builders](https://github.com/fabric8io/kubernetes-model/blob/master/kubernetes-model/pom.xml#L41)

The Fluent Builders that we generate look very much with what you describe in the Fluent section.

Then we use all of those Types, Fluent Interfaces and Builders in a hand crafted DSL which allows a descent amount of inlining _(e.g. from DSL -> Fluent Interfaces)_:

    ReplicationController rc = new ReplicationControllerBuilder()
                        .withNewMetadata().withName("nginx-controller").addToLabels("server", "nginx").endMetadata()
                        .withNewSpec().withReplicas(3)
                        .withNewTemplate()
                        .withNewMetadata().addToLabels("server", "nginx").endMetadata()
                        .withNewSpec()
                        .addNewContainer().withName("nginx").withImage("nginx")
                        .addNewPort().withContainerPort(80).endPort()
                        .endContainer()
                        .endSpec()
                        .endTemplate()
                        .endSpec().build();
                        
    ReplicationController created = client.replicationControllers().create(rc);


or using inlining: 

    ReplicationController created = client.replicationControllers().createNew().withNewMetadata().withName("nginx-controller").addToLabels("server", "nginx").endMetadata()
                        .withNewSpec().withReplicas(3)
                        .withNewTemplate()
                        .withNewMetadata().addToLabels("server", "nginx").endMetadata()
                        .withNewSpec()
                        .addNewContainer().withName("nginx").withImage("nginx")
                        .addNewPort().withContainerPort(80).endPort()
                        .endContainer()
                        .endSpec()
                        .endTemplate()
                        .endSpec().build()


IMHO, the Kubernetes types have so deep level of nesting and are so complex that using a Fluent Interfaces for creating types is an absolute must. 

For the client itself using code generation does guarantee the api coverage, but its really hard to get it being intuitive without some sort of supervision. I am not aware of any project generating a decent fluent dsl out of swagger _(but to be fair I haven't checked recently)_.

An alternative would be to generate a basic client (not necessarily intuitive) and then build (manually or semiautomatically) a DSL / Framework around it so that we have something mor epleasant to use.

**Comment by mbohlool** [comment]
My thoughts on those three steps:

on 1: It generates json schema directly from go code and not OpenAPI spec. The source changes a lot and this process cannot be repeated easily (I guess the json schema cannot be updated right now because most of those packages are moved/modified). Also some of the packages are internal. Generally we should use OpenAPI spec for this.
on 2: While we may have no issue with this step, if we used OpenAPI, we should use swagger-codegen for this step too. The swagger-codegen will do more than just generating models.
on 3: Would you explain this a little more. I am interested to see if it can be used with OpenAPI.

I agree that fluent interface is very useful, but if I want to put one P0 on a feature, I would say being able to update client and keep it in sync with k8s. The fluent interface of OpenAPI generated client is not as elegant as fabric8 client but it is good enough IMHO.

The problem on both approaches is on the operations: 

- Fabric8 approach to operations as far as I can tell is manually written. This mean changes in operation, their parameters or new/removed operations cannot be automatically reflected and need manual work.
- OpenAPI generated operation are not fluent. They are ugly long name such as listPodForAllNamespaces.

I would like to find a way to get a client that has both updatability and fluent interface. I vote for your alternative suggestion of having a generated client and then try to build a DSL on top of it. The main part of that is the operations as models are fluent enough (and we can contribute to swagger-codegen to make it more fluent). I want to find a way to automatically generate that framework.

**Comment by iocanel** [comment]
> Would you explain this a little more. I am interested to see if it can be used with OpenAPI.

In this step we use POJOs _(plain objects that contain just a couple of fields)_. For each of those objects we create two things:

- A Builder
- A Fluent Interface (An interface the define all the builder methods, but build itself)
- An Fluent Class (An implementation of the fluent interface)

The main reason that we separate the builder and then fluent, is that the fluent allows us to `inline` it _(see the example were we create a new Replication Controller without using directly a builder or an instance)_.

For generating this part, I used an experiment of mine, which turned out to be a perfect fit. The tool is called [Sundrio Builder Generator](https://github.com/sundrio/sundrio/blob/master/annotations/builder). And has some really nice features:

- Support hierarchical builders
- Support nested builders
- Supports unwrapping for buildable interfaces and abstract classes.
- Visitor pattern for modifying immutable types is baked inside the builder.
- Supports generating `inline` types.

An other relevant experiment is a DSL generator: [Sundrio DSL Generator](https://github.com/sundrio/sundrio/blob/master/annotations/dsl). The input is an annotated class (the describes the DSL), but in theory we could change the input to swagger or whatever it makes sense.

**Comment by mbohlool** [comment]
@jimmidyson @iocanel  We have an approved [new clients libraries process](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/csi-new-client-library-procedure.md) and also [structure for clients](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/csi-client-structure-proposal.md). I really like the idea of compatible clients and would like to go ahead with a swagger-generated java client. Of course I would love to have improvements of your client on top of it. Would you guys be interested in owning that (or know somebody that be interested)? I can start the repo, generate code and contribute to config loading part so we have an alpha client ready to go and then the owners can move it forward to implement better interfaces.

**Comment by iocanel** [comment]
Personally, I would like to avoid re-inventing the client from scratch, so from my pov its really important to check the our existing DSL is something that could be built on top of the swagger generated stuff.

Do you have a sample of how the code looks like?

**Comment by mbohlool** [comment]
It would be similar to [Python Client](https://github.com/kubernetes-incubator/client-python) (it won't be exactly the same, e.g. names would be camel case. But close enough).

**Comment by jimmidyson** [comment]
@mbohlool I would love to see what a generated Java client looks like from swagger-codegen, with a concern shared by some of our client consumers to keep dependencies minimal. Do you have a start on this somewhere or a pointer on best way to generate locally?

Our client is almost definitely the most widely used Java client out there and I echo @iocanel's feeling that we wouldn't want to reinvent our DSL client without good reason - just causes headaches and work for existing consumers.

Having said that, I would be happy to get rid of our inner plumbing and just maintain the DSL and the improvements that brings.

**Comment by jimmidyson** [comment]
@mbohlool @brendandburns What's the state of the generated Java client? Any closer to having something interested users like me can try out?

**Comment by brendandburns** [comment]
Yes, it works (mostly ;)

https://github.com/kubernetes-client/java

There are several examples (and more in PR s)

Will work on distribution of a Maven package.

Please file issues if you run into problems!

--brendan

________________________________

**Comment by mbohlool** [comment]
@jimmidyson It is in progress as @brendandburns said. With new GVK extensions in 1.7, I hope we would be able to generate a more fluent client (both for java and other languages). That part of the work however is not started yet. We want to get java client to beta/silver and release it first.

**Comment by bgrant0607** [comment]
Underway in the kubernetes-client org
