### ISSUE TITLE
Document multiple scheduler feature.

### ISSUE THREAD

**Issue by madhusudancs** [kubernetes/kubernetes#22471]
We need a doc that explains how to setup and run multiple schedulers in a cluster. In addition, the doc should also explain how the pods can be scheduled using these schedulers.

cc @davidopp @roberthbailey

**Comment by davidopp** [comment]
You're planning to write this, correct? If so, please assign to yourself.

**Comment by madhusudancs** [comment]
@davidopp Yeah. Assigned it to myself.

**Comment by mdshuai** [comment]
@madhusudancs Is there a example about scheduler extender ?

**Comment by davidopp** [comment]
Just to be clear, scheduler extender is unrelated to the multiple-schedulers feature that this issue is talking about.

Scheduler extender design doc is here
https://github.com/kubernetes/kubernetes/blob/master/docs/design/scheduler_extender.md

There's an example scheduler config file that uses it here
https://github.com/kubernetes/kubernetes/blob/master/examples/scheduler-policy-config-with-extender.json

We don't have any real user documentation about scheduler extender it because it is a very "alpha" feature. We make no guarantee that it will continue to work as we make changes to the scheduler. (Of course we would announce before we break it in an official release.)

If you are planning to use it, we'd love to hear about your use case. But please do so on the mailing list 
https://groups.google.com/forum/#!forum/google-containers
rather than in this issue, which is not related to scheduler extender.

**Comment by mdshuai** [comment]
@davidopp thanks for your comment

**Comment by madhusudancs** [comment]
This is now documented here - http://kubernetes.io/docs/admin/multiple-schedulers/
