### ISSUE TITLE
can not delete endpoint in special namespace

### ISSUE THREAD

**Issue by newjueqi** [kubernetes/kubernetes#22507]
i found one endpoint follow:

```
[root@kube-node-1 user_project]# kubectl    -o wide --all-namespaces=true get ep
NAMESPACE                          NAME                ENDPOINTS           AGE
d237352e841d58140c0695843159d78b   glusterfs-cluster   10.160.122.21:1     1d
default                            kubernetes          114.55.6.218:6443   18m
default                            private-registry    172.48.95.2:5000    18m
```

then I want to delete " glusterfs-cluster" use follow commond:
```
[root@kube-node-1 user_project]#  kubectl --namespace="d237352e841d58140c0695843159d78b"  delete ep glusterfs-cluster
Error from server: namespaces "d237352e841d58140c0695843159d78b" not found
```
or
```
[root@kube-node-1 user_project]#  kubectl  delete ep glusterfs-cluster
Error from server: endpoints "glusterfs-cluster" not found
```
or
```
[root@kube-node-1 user_project]#  kubectl --namespace=d237352e841d58140c0695843159d78b  delete ep glusterfs-cluster
Error from server: namespaces "d237352e841d58140c0695843159d78b" not found
```

is it something wrong with my commond?

**Comment by jlowdermilk** [comment]
Please re-post your question to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases.

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to similar questions, and also familiarize yourself with:
   * [the user guide](http://kubernetes.io/v1.0/)
   * [the troubleshooting guide](http://kubernetes.io/v1.0/docs/troubleshooting.html)

Again, thanks for using Kubernetes.

The Kubernetes Team
