### ISSUE TITLE
ReplicationController transfer docker run arguments 

### ISSUE THREAD

**Issue by bengong2015** [kubernetes/kubernetes#22514]
How to build replication controller in order to run docker container with arguments (e.g. docker run --add-host xxxxx:xxxxx --rm ...)?
I tried to add 'env' in container section but doesn't work.
Thanks.

**Comment by bgrant0607** [comment]
We don't support docker run arguments directly.

Env is supported. You should use services rather than --add-host.

Please see our documentation for details:
http://kubernetes.io/v1.1/app-admin-detailed.html

We also have numerous examples:
https://github.com/kubernetes/kubernetes/tree/master/examples

If you still have questions, please try [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases.

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

Again, thanks for trying Kubernetes.

The Kubernetes Team
