### ISSUE TITLE
Scheduler to continue if a predicate throws an error for a particular node

### ISSUE THREAD

**Issue by abhgupta** [kubernetes/kubernetes#22554]
Currently each node is passed through all the predicates to figure out whether the node is a match/fit to host the pod or not. The predicates are expected to return true/false without an error. However, if a predicate returns an error for a particular node, the scheduler throws an error and that pod that does not get scheduled.

Instead, I would suggest we continue on to other nodes to see if any of them can be a fit and clear the all predicates. This might make for a slightly sub-optimal scheduling decision (assuming that the node was expected to clear the predicate in the absence of the error), but at least the pod gets scheduled.

If this makes sense, I can quickly make this change and add test cases and submit a PR.

cc: @derekwaynecarr @kubernetes/sig-scheduling

**Comment by hongchaodeng** [comment]
Not sure why @kubernetes/sig-scheduling isn't notified for such a long time.
My opinion is that we still need to differentiate "schedulable" and "unschedulable" nodes in the knowledge of scheduler.

**Comment by resouer** [comment]
I'm afraid then we need to maintain extra node status in scheduler?

**Comment by HaiyangDING** [comment]
+1 to this change. 

Error on particular node should not block other node from being verified.

**Comment by timothysc** [comment]
@abhgupta ok to close?

**Comment by abhgupta** [comment]
@timothysc The actual error that got me to file this issue has been fixed by PR  https://github.com/kubernetes/kubernetes/pull/22568. However, this is still a valid issue and we need to answer whether a predicate error with a single node should block scheduling of the pod.

**Comment by jayunit100** [comment]
- assuming  **Error on a node == error in the predicate algorithm, or in the ability of the scheduler to calculate a predicate, or handle a particular node's information content.**
If thats the case, 
- then we should keep current behaviour, close the issue based on the "fail fast" mantra, rather then wallpapering over a broken predicate, or broken scheduler extension...

For example: 
- Lets say etcd is down - and so there is an error in the cache or something like that, which makes a predicate fail.   
- Or, lets say a predicate is causing a nil panic.  In either case, if an error occurs; it doesnt make sense to continue finding a match, because the error had nothing to do with the node, and in fact, doing so just consumes resources and covers an error.
So i suggest:
- we do fail fast and early on error, since error throwing predicates are a non-normal behaviour.
- we count on the scheduler itself to periodically retry scheduling.

**Comment by timothysc** [comment]
I'm going to close and if folks feel strongly enough we can reopen.
