### ISSUE TITLE
Nodes in Ubernetes Lite e2e clusters mysteriously started to come up network isolated

### ISSUE THREAD

**Issue by quinton-hoole** [kubernetes/kubernetes#22572]
Discussed offline. @spxtr thinks he might know what the problem is.

```
quinton: The ubernetes-lite e2e clusters stopped coming up 2 days ago, 
and I suspect your or zml's PR's around that time, but unfortunately I don't 
understand the scripts well enough any more to debug effectively.

spxtr: Might've been me.

quinton: In summary, most of the projects that e2e tests run in have a 
network configured in them, named similarly to the project they're in.  
Mine no longer has one, and as a result the VM's are all isolated 
from the network.  In the old days those networks were created by 
he e2e scripts, but these days they are perhaps manually created?  
It's possible that I deleted mine while cleaning up leaked resources, 
and perhaps it's no longer being automatically created?
https://pantheon.corp.google.com/compute/instances?project=k8s-jkns-e2e-gce-ubelite 
is a good place to start.  All of the instances are network-isolated 
as far as I can see (can't ssh to them, and they fail to come up 
because they fail to connect outbound either).  All of the "working" 
e2e projects seem to have 3 networks configured (e.g.
"default", ""jenkins-e2e", "jenkins-gke-e2e-serial", but 
mine (project=k8s-jkns-e2e-gce-ubelite) only has the first
 two for some reason.

**Comment by ixdy** [comment]
(taking this over because @spxtr is swamped with a few other issues)

`jenkins-e2e` is the network that basically every job uses now, unless it's sharing a project with another job. Names like `jenkins-gke-e2e-serial` aren't used anymore, and should probably be cleaned up.

The `k8s-jkns-e2e-gce-ubelite` project is missing the "default" network; I'm not sure if that's important to have or not. Still looking to see if there's something else amiss.

**Comment by ixdy** [comment]
Comparing routes against project `k8s-jkns-e2e-gce`, there are quite a few routes on the `jenkins-e2e` network that appear to be missing in `k8s-jkns-e2e-gce-ubelite`, which is likely what's causing the issue.

What was @zmerlynn's PR that you referenced?

**Comment by quinton-hoole** [comment]
The PR from zmerlynn that I referred to was #22234, but in retrospect I don't think it's to blame.  It merged around the time that the problems started, and it updated the binary download code (it's the downloads that are failing, but that's almost definitely due to the network isolation mentioned above).

**Comment by quinton-hoole** [comment]
@ixdy Whatever you did seems to have worked:

 http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gce-ubernetes-lite/802/console

**Comment by quinton-hoole** [comment]
Still all green.  Closing.

**Comment by ixdy** [comment]
Just to close the loop, my investigation/actions:

Build 691 failed with a resource leak:
```
ERROR: (gcloud.compute.instance-groups.managed.delete) Some requests did not succeed: - The service account '477660749787@cloudservices.gserviceaccount.com' is not associated with the project.
...
+ diff -sw -U0 '-F^\[.*\]$' /var/lib/jenkins/jobs/kubernetes-e2e-gce-ubernetes-lite/workspace/_artifacts/gcp-resources-before.txt /var/lib/jenkins/jobs/kubernetes-e2e-gce-ubernetes-lite/workspace/_artifacts/gcp-resources-after.txt
--- /var/lib/jenkins/jobs/kubernetes-e2e-gce-ubernetes-lite/workspace/_artifacts/gcp-resources-before.txt	2016-03-02 07:06:21.066171836 -0800
+++ /var/lib/jenkins/jobs/kubernetes-e2e-gce-ubernetes-lite/workspace/_artifacts/gcp-resources-after.txt	2016-03-02 07:37:25.463534390 -0800
@@ -10,0 +11 @@ [ instance-templates ]
+jenkins-e2e-minion-template n1-standard-2             2016-03-02T07:07:42.142-08:00
@@ -14,0 +16 @@ [ instance-groups ]
+jenkins-e2e-minion-group us-central1-f jenkins-e2e Yes     0
+ [[ true == \t\r\u\e ]]
+ echo '!!! FAIL: Google Cloud Platform resources leaked while running tests!'
```

Basically, since we failed to delete the instance group, we then couldn't delete the template, either.

This should have been harmless, as it should have been cleaned up in the next run, but there appears to be some bug in `kube-down` or `detect-node-names`, much like in #21564:
```
Shutting down test cluster in background.
ERROR: (gcloud.compute.firewall-rules.delete) Some requests did not succeed:
 - The resource 'projects/k8s-jkns-e2e-gce-ubelite/global/firewalls/jenkins-e2e-minion-jenkins-e2e-http-alt' was not found
 
ERROR: (gcloud.compute.firewall-rules.delete) Some requests did not succeed:
 - The resource 'projects/k8s-jkns-e2e-gce-ubelite/global/firewalls/jenkins-e2e-minion-jenkins-e2e-nodeports' was not found
 
Bringing down cluster using provider: gce

All components are up to date.

All components are up to date.

All components are up to date.
Project: k8s-jkns-e2e-gce-ubelite
Zone: us-central1-f
2016/03/02 07:38:20 e2e.go:278: Error running teardown: exit status 1
```

and since it didn't delete the instance group or its template, `kube-up` subsequently failed.

Quinton tried to fix this by purging everything in the project, but somehow things apparently got into a weird state. I noticed that there was no `default` network on the project, and the `jenkins-e2e` network only had one route instead of the usual 4.

I wiped out the project again (deleting all VMs, disks, routes, firewalls, etc) and also created a new `default` network so I could delete the `jenkins-e2e` network. The cluster infra then successfully recreated everything, and tests started passing.

I'm not sure there's anything actionable here, other than figuring out what's broken in `detect-node-names`.

**Comment by mfanjie** [comment]
just FYI.
An update for similar issue, I see the following error when I try to boot kubernetes e2e cluster on GCE, and the minion node can not be created.
```
ERROR: (gcloud.compute.instance-groups.managed.create) Some requests did not succeed:
 - The service account '57068524338@cloudservices.gserviceaccount.com' is not associated with the project.

ERROR: (gcloud.compute.instance-groups.managed.wait-until-stable) Some requests did not succeed:
 - The resource 'projects/jessefed-140605/zones/us-central1-b/instanceGroupManagers/e2e-test-root-minion-group' was not found
```
I retried different ways like delete the entry project on gce, rebuilt the whole kubernetes, etc, it did not help, reran gcloud init(with default zone=us-west1-a)

And finally it was resolved by gcloud init and set us-central1-b as default zone. I am quite sure about the linkage between the result and the init action. Not sure if there is a problem on gce zone us-west1-a.

**Comment by ptabor** [comment]
A.d. the error: 
```
ERROR: (gcloud.compute.instance-groups.managed.create) Some requests did not succeed:
 - The service account '57068524338@cloudservices.gserviceaccount.com' is not associated with the project.
```

You should run following commands: 
```
PROJECT_NAME=your-project-name

PROJECT_ID=`gcloud projects describe $PROJECT_NAME --format 'value(projectNumber)'`
echo projectId:${PROJECT_ID}
gcloud projects add-iam-policy-binding ${PROJECT_NAME}  --member=serviceAccount:${PROJECT_ID}@cloudservices.gserviceaccount.com --role=roles/editor

```
See:
https://stackoverflow.com/questions/39366326/gcp-autoscaler-instance-group-error-service-account-issue for more context.
