### ISSUE TITLE
Add Windows Containers Support

### ISSUE THREAD

**Issue by preillyme** [kubernetes/kubernetes#22623]
Add Windows Containers Support at least at the node level.

**Comment by preillyme** [comment]
I'd like to plan a kickoff meeting with @BenjaminArmstrong and @sschuller sometime in the next couple of weeks. I'd also like to ask @sarahnovotny to create the Windows SIG as well.

**Comment by asultan001** [comment]
And here we go!

**Comment by quinton-hoole** [comment]
Here are a few reasonable intro's, for those following along:

[The Register: Hands On](http://www.theregister.co.uk/2015/08/31/hands_on_with_windows_server_2016_containers/?page=2)
[Mark Russianovich, Microsoft CTO](https://azure.microsoft.com/en-us/blog/containers-docker-windows-and-trends/)
[Microsoft Docs](https://msdn.microsoft.com/en-us/virtualization/windowscontainers/about/about_overview)

**Comment by preillyme** [comment]
Thanks @quinton-hoole greatly appreciate the references. Exciting times @asultan001 @timothysc

**Comment by taylorb-microsoft** [comment]
This is great to see!  Just for a quick intro I am the lead program manager for all server container technologies in Windows, my team is responsible for Windows Server Containers and Hyper-V Containers.

**Comment by asultan001** [comment]
Thanks @taylorb-microsoft looking forward to connecting once we have something a bit more concrete.

**Comment by preillyme** [comment]
I've created a shared document available at: https://goo.gl/NE0ABx to track our planning discussions. Thanks for helping us @taylorb-microsoft.

**Comment by rakeshm** [comment]
A few of us at Apprenda,  @taylorb-microsoft  and @johngossman are going to do a quick sync up this week.

We'll add to the shard doc @preillyme

**Comment by quinton-hoole** [comment]
Could someone please grant me comment permission on the shared doc.  I'm
quinton@google.com

Thanks

Q

**Comment by davidopp** [comment]
cc/ @colemickens

**Comment by rakeshm** [comment]
I added a summary of the Apprenda/Microsoft meeting to the doc with some upcoming key action items.

**Comment by smarterclayton** [comment]
> How receptive will the project be to modifying allowable Kubelet options to include Windows specific flags and options?

We have an "ok" story for container runtime specific flags, but it needs to be upgraded to a "great" story.  We'd follow the `rkt` pattern for now probably.

> Is the PodSpec easy to modify in case any idiomatic Windows specs need to be added?

Great question, we should try to figure out what those would be and then have the discussion of a set of them together.  ContainerSpecs were designed to be more generic than the default Docker container spec originally was, but I suspect we'll simply have options that don't work on all runtimes, and a way to document that.  For instance, SELinux and AppArmor are already two items that don't work on all linux distros, but they're encapsulated within higher level security groupings.  Path specs are likely to be painful on volumes.  Dealing with persistent volumes across windows systems may not change that much, although certain options simply won't be available.  We've started the "how do we deal with images across multiple runtimes" discussion, but since Windows Docker would probably use the same format as Linux I don't expect that to be an issue.

**Comment by srounce** [comment]
@smarterclayton I know it isn't perfect, but would it be possible to take an approach similar to cygwin where we leverage a small util to transform paths to/from?

**Comment by dchen1107** [comment]
Can someone grant me, dawnchen@google.com the comment permission on that shared doc?

**Comment by preillyme** [comment]
Hey @dchen1107 I've added you as an editor to the shared document.

**Comment by luxas** [comment]
> Given the OS differences and eventual differences in Pods as a container grouping mechanism, how should we approach any asymmetry that will likely occur when handling Windows hosts when compared to non-Windows hosts? 

I've been thinking about if the kubelet should annotate or label itself with the platform it's running on. That might make arm, arm64, ppc64le, amd64 and windows handling easier, if there ever will be cross-clusters. WDYT?

**Comment by esotericengineer** [comment]
I think self-labeling based on host platform makes a ton of sense. It will help with idiomatic configuration per platform, but also lends itself to helping with cluster segregation. Is there anything else in k8s that currently self-labels?

**Comment by davidopp** [comment]
#9044 says cloud provider but can also cover platform stuff.

**Comment by esotericengineer** [comment]
OK, after reading it through #9044, it would seem we could capture 'Platform' as a standard label in 
`pkg/api/unversioned/well_known_labels.go`My guess is that in a multi-platform k8s, that would make the most sense since multiple platforms could become a pretty standard use case. That label could be used for OS & architecture combos or just OS

**Comment by luxas** [comment]
I guess samples value for `kubernetes.io/(generic/)platform` could be `linux/arm`, `linux/amd64`, `windows/amd64`. This would be very nice to have when we're heading for cross-platfrom (`amd64`, `arm`, `arm64` and `ppc64le`): #17981 

Talking code changes, what should be added more than this?
```go
# pkg/api/unversioned/well_known_labels.go:22
const LabelPlatform = "beta.kubernetes.io/platform"
```
```go
# pkg/kubelet/kubelet.go:1042
node.ObjectMeta.Labels[unversioned.LabelPlatform] = runtime.GOOS + "/" + runtime.GOARCH
```
I could send a PR for this if you like.

**Comment by csrwng** [comment]
Early prototype: https://github.com/csrwng/kubernetes/commit/e75550899522a51a27513a9196ee55b4232a3343
And corresponding demo:
https://goo.gl/2XxOtY

More than anything it helps to identify gaps in function (just look at the chunks of code that are stubbed or commented out). 

Main issue I ran into was that Windows containers don't lend themselves well to the Linux model where 1 container = (mostly) 1 process. Windows containers tend to include more of the OS, including the service manager and at least as of right now don't allow namespace sharing. Therefore it doesn't make sense to start a separate infra container to hold on to the ip as on the Linux side. More importantly, a pod cannot be represented as a set of containers that share certain things. In Windows, it may make more sense to have 1 pod = 1 windows container, and each container from the pod simply represent separate process on that container. If modeled that way, it means that containers in a windows pod cannot use a different image each, it also means that resource requirements, security constraints, etc. would apply to the entire pod, and not to each container.

**Comment by smarterclayton** [comment]
1 pod = 1 container is a dramatic shift, so it's worth diving in what
sharing is important.  Network and volumes are critical for sharing.
Everything else is just nice to have.  Can Windows handle 1 IP for multiple
containers?  Can it handle volume sharing?

On Apr 14, 2016, at 11:08 AM, Cesar Wong <notifications@github.com> wrote:

Early prototype: csrwng@e755508
<https://github.com/csrwng/kubernetes/commit/e75550899522a51a27513a9196ee55b4232a3343>
And corresponding demo:
https://goo.gl/2XxOtY

More than anything it helps to identify gaps in function (just look at the
chunks of code that are stubbed or commented out).

Main issue I ran into was that Windows containers don't lend themselves
well to the Linux model where 1 container = (mostly) 1 process. Windows
containers tend to include more of the OS, including the service manager
and at least as of right now don't allow namespace sharing. Therefore it
doesn't make sense to start a separate infra container to hold on to the ip
as on the Linux side. More importantly, a pod cannot be represented as a
set of containers that share certain things. In Windows, it may make more
sense to have 1 pod = 1 windows container, and each container from the pod
simply represent separate process on that container. If modeled that way,
it means that containers in a windows pod cannot use a different image
each, it also means that resource requirements, security constraints, etc.
would apply to the entire pod, and not to each container.

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/22623#issuecomment-209990789>

**Comment by csrwng** [comment]
> Can Windows handle 1 IP for multiple
> containers?

no (at least as of today). Actually the container IP is not yet surfaced through the Docker API, but I suspect that's just 

> Can it handle volume sharing?

yes

We're going to find out more next week as we talk to Microsoft and understand what will eventually be possible vs never possible.

**Comment by smarterclayton** [comment]
I would even say volume sharing is the key differentiator for multiple
containers.  I'd be extremely hesitant to consider a 1 pod = 1 container
approach for Windows unless we're saying containers on windows
fundamentally can never approach that.

**Comment by vishh** [comment]
Another thing to consider is the level of configurability we will get with windows containers. If we can emulate pods by dynamically configuring containers, that might work as well.

**Comment by rakeshm** [comment]
I guess we'll learn more next week on what MSFT would recommend but IMO, having a short term (if indeed it is short term) limitation on Windows that 1 pod = 1 container is better than having a host of materially important caveats on Windows when you have 1 pod = n containers if that's what it ends up coming down to. 

Clear statements of limitations - and we know there will be limitations in a variety of areas - are important b/c if you're constantly reading the fine print, it just creates lots of friction. 

I'm with you Clayton that we should be very hesitant to limit 1 pod = 1 container but if alternatives are going to be messy, we shouldn't force a model into place that isn't ready.

**Comment by smarterclayton** [comment]
I'm not against making progress, but limitations of a container
runtime don't invalidate the intent of the pod to be a scheduling
unit.  Colocated work in pods is the core Kube abstraction, and so we
wouldn't lightly propagate a restriction like that up the stack (to
the APIs, validations, or clients).

I'd want a much deeper discussion of the trade offs due to long term
technical gaps (as this work progresses) before we jump to a
limitation like that.  That's all info that should be part of the
proposal doc (even if we can't answer it yet) as you move forward.

**Comment by rakeshm** [comment]
Agreed. 

Just for clarification though - we'd be talking about deciding on the composition of a pod, not the fact that a pod is the unit of scheduling right? I'm certainly not suggesting we even consider the latter.

**Comment by smarterclayton** [comment]
If you want to achieve scheduling colocation onto a node for two
service endpoints you place them in a pod (even if you don't need
volume or network sharing).  Using other constructs to achieve that
would be discouraged / not supported / "a bad idea".  So in the worst
possible case (no way to technically implement network IP sharing) we
very well may want multiple containers per pod on Windows.

**Comment by rakeshm** [comment]
Got it. Looks like it will come down to what can actually be shared across containers within a pod and which life cycle operations can be mutually guaranteed before this becomes a tougher call.

**Comment by michmike** [comment]
hi everyone, members from Apprenda and Red Hat have created the first version of a technical investigations document on how to bring the kubelet to Windows.
Comments and feedback is welcome from everyone (everyone has the ability to add comments) - if you want edit/write access, let me know through the Slack messaging system.

https://docs.google.com/document/d/1qhbxqkKBF8ycbXQgXlwMJs7QBReiSxp_PdsNNNUPRHs/edit?usp=sharing

Our goal is to share some of these findings with Microsoft during our Wednesday meeting. The focal point of that meeting is to go over some of the questions for Microsoft that we started accumulating in this document. If you have additional questions to bring during that discussion, please add them to the document.

**Comment by michmike** [comment]
Today in the Kubernetes community meeting, we demo'ed the alpha version of the Windows Server Container support in Kubernetes, with kubernetes running on Microsoft Azure.

Feature: https://github.com/kubernetes/features/issues/116 will track bringing the work of SIG-Windows to beta with release 1.5 of Kubernetes. 

If you want to help, join SIG-Windows at https://kubernetes.slack.com/messages/sig-windows

cc: @sarahnovotny , @brendandburns

**Comment by luxas** [comment]
I think this issue can be closed in favor for https://github.com/kubernetes/features/issues/116; where the feature state is tracked. Also, this is implemented to a large extent already (beta); whohoo!

Thanks all for the great work :+1:
