### ISSUE TITLE
better PV error reporting for NFS volumes

### ISSUE THREAD

**Issue by jmccormick2001** [kubernetes/kubernetes#22647]
I'm finding that if you create a PV for NFS, that specifies a wrong IP address of the NFS server,
the error is not found until very late in the user's experience if at all.

The PV appears to create without an error, the PVC that binds to the PV appears to create
without an error.  NFS mount errors only appear when your pod tries to use the PVC and you often
don't get an understandable error in the pod log other than "Pending".

If a redesign of this is in the works, it would be great to use this as a use case to provide
better error messages back to the end-user earlier in the lifecycle (pv->pvc->pod).  Perhaps
some sort of NFS mount testing when the PV is first created?  I wouldn't think a PVC should
be allowed to create and bind to a broken PV for example.

**Comment by jingxu97** [comment]
@saad-ali @thockin Do we plan to add some early validation in the system? I can think of some other related examples such as create a pod with direct use of a pd which does not exist. The creation can be failed instead of scheduling the pod and stuck in the "ContainerCreating" phase and also controller keeps trying to attach the non exist pd forever.

**Comment by thockin** [comment]
API validation is syntactic, not semantic.  We ensure the value provided is
an IP address, not that it is an NFS server, or that you have access to it,
or even that it is reachable.  In general, the IP might be dead now, but
come online later..

I'm not sure there's much to do here, except better events.
