### ISSUE TITLE
Controller manager restart/fail-over causes massive spike in etcd traffic @ scale. 

### ISSUE THREAD

**Issue by timothysc** [kubernetes/kubernetes#22669]
We are currently running scale experiments and have uncovered a situation which causes a flood of traffic to etcd, to the point of saturating the link and causing a series of other knock-on issues.  

**Precondition:** A fully loaded system , e.g. 1000 nodes with multiple controllers actively running. 
**Event:** Controller manager failure or restart 
**Observation:** On restart the controller manager will aggressively try to refill it's state to the point it will watch-list everything it can.  This causes a saturation of the network link to etcd causing a series of secondary effects, grinds the system to become unresponsive. 
**Reproducability:** 100% 

/cc @kubernetes/sig-scalability @rrati @smarterclayton @ncdc @jeremyeder

**Comment by davidopp** [comment]
cc/ @bprashanth

**Comment by davidopp** [comment]
cc/ @lavalamp

**Comment by bprashanth** [comment]
@mqliang who recently made changes to re-population of the pod store on controller manager restart

**Comment by timothysc** [comment]
@bprashanth our testing was against a baseline before @mqliang changes, but I'm guessing it would still occur at this scale.  We basically need to throttle + jitter our restarting.

**Comment by bprashanth** [comment]
There was a condition where we weren't populating the store to being with (https://github.com/kubernetes/kubernetes/pull/19973) and this will cause weirdness in large clusters (like oscillation).

**Comment by mqliang** [comment]
IIRC, we have cache in API server. If we just restart Controller, without restarting API server, all list&watch requests will serve by the API server cache, instead of etcd, right?

I look through the code of cacher:
If client of Controller send a List request, and `resourceVersion != ""`, the List request will serve by cache, instead of forwarding to etcd:
https://github.com/kubernetes/kubernetes/blob/master/pkg/storage/cacher.go#L294

And fortunately, all List request sent by Reflector has a non-empty resourceVersion: https://github.com/kubernetes/kubernetes/blob/master/pkg/client/cache/reflector.go#L237

**Comment by timothysc** [comment]
> all list&watch requests will serve by the API server cache, instead of etcd, right?

Not necessarily in the load-balanced api-server use case, which is what we are doing.

**Comment by mqliang** [comment]
@timothysc 
Intuitively, we Controller will send about 15 LIST request to API server when restart, 15 List request per second is should not be a big problem for etcd actually, and we have rate limit in Controller.  

Does you Controller has https://github.com/kubernetes/kubernetes/pull/19973 or https://github.com/kubernetes/kubernetes/pull/20269 merged. If not, Controller will make incorrect decision: oscillate, but can recover after several ten minutes when pod numbers is not very large; if we have a large number of Pod, Controller will just can not control replica numbers and will continuously send pod creation requests.

**Comment by smarterclayton** [comment]
What's the size of the individual list calls in bytes?

**Comment by wojtek-t** [comment]
@timothysc 
Regarding cache in apiserver - if apiserver wasn't restarted and was available all the time, I agree with @mqliang that basically all LIST+Watch requests (coming from reflectors, informers etc.) should just hit apiserver and shouldn't be passed to etcd. The fact that you have load-balanced apiserver shouldn't change anything in my opinion.
@timothysc - can you check that all those LIST requests from controller-manager have "resourceVersion=0" set?

@smarterclayton @timothysc 
Regarind size of individual list - IIRC, we have between 5 and 10 reflectors listening to all pods in all controllers. If you have a full cluster - 30.000 pods, and we assume an average pod being 3kB (which I think is a lower bound), that given 100MB of data. Multiplying it by number of reflectors, that easily gives you 1GB of data, and it you are restarting controller-manager, all those data will be requested at the same time. So I'm completely not surprised that 100Mbits network is flooded.

Regarding solution, I think we have 2 action items:
- better throttling in this case
- and more medium-term solution, but I think what we really should do is #15095. Basically we should change our controllers so that they have injectable reflectors and all controllers running in a single binary should share a cache with other controllers. This requires a bunch of changes in controller too (to support registering handler function when reflector is already running), but that's definitely possible and would significantly reduce amount of data that needs to be read.

**Comment by mqliang** [comment]
@timothysc Seems you are an expert of API server cache. I carefully read the code of API server cache today, may I ask a question: should we use `NewDeltaFIFO` instead of `NewStore` here https://github.com/kubernetes/kubernetes/blob/master/pkg/storage/watch_cache.go#L107 ? Current code seems will miss come events when watch failed and relist. Hope I understand the code correctly.

**Comment by wojtek-t** [comment]
@mqliang I wrote this cache, but I'm not sure I understand your question.

>
Current code seems will miss come events when watch failed and relist. Hope I understand the code correctly.

What do you mean? If you mean "client to apiserver watch", then client explicitly sets what resource version is should start watching at.
If you mean "server to etcd watch", then if it fails and cannot be restore, all client watches will be closed. So there isn't any problem here.

**Comment by mqliang** [comment]
@wojtek-t I mean "server to etcd watch". 
> then if it fails and cannot be restore, all client watches will be closed. So there isn't any problem here.

This answered my question. Great thanks!

**Comment by timothysc** [comment]
OK, so many questions, I will try to hit them all: 

> Does your Controller has #19973 or #20269 

No, it's before those changes have landed. 

> can you check that all those LIST requests from controller-manager have "resourceVersion=0" set?

Yes, I will check and report back.  

> So I'm completely not surprised that 100Mbits network is flooded.

1 GBit is flooded, but this also includes openshift controller data as well.

> better throttling in this case 

+1 Better throttling and jitter is a very simple patch that would greatly easy the restart issue. 

> Basically we should change our controllers so that they have injectable reflectors and all controllers running in a single binary should share a cache with other controllers.

Could not agree more.

**Comment by smarterclayton** [comment]
xref unifying cache stores #14978

**Comment by wojtek-t** [comment]
Oop - thanks @smarterclayton - I linked a wrong issue above.

**Comment by xiang90** [comment]
> Intuitively, Controller will send about 15 LIST request to API server when restart, 15 List request per second should not be a big problem for etcd actually, 

This is not true for etcd. Recursive get can be huge (maybe MB). etcd2 does not limit the size of the request. Large requests uses a lot of CPU to encode, memory for buffering and network IO for transferring.

/cc @hongchaodeng Probably we need to keep this in mind when writing etcd3 integration. etcd3 supports consistent pagination so we can relist slowly. Or we can probably combine the cache or fill cache from another cache. So one cache miss will not result of multiple cache filling directly from etcd.

**Comment by timothysc** [comment]
@rrati is working on some controller startup throttling.

**Comment by lavalamp** [comment]
@wojtek-t maybe we could test this in the scalability test suite.

But yeah, I wouldn't expect this to cause it to fall over.

@timothysc What caused the failure of controller-manager? Maybe the cause of that is actually causing other problems, too.

**Comment by timothysc** [comment]
CPU saturation until it hits a lease expiration in openshift, forcing a fail-over.  It's on the controller-manager + scheduler restart on a fresh node that we see the hammering.  In our case they are 1 process.  

Our test hits the api-server probably harder then *e2es, we have concurrent submissions of deployments+other resource objects trying to hit every controller and resource object. 

So to answer your question @lavalamp, the use case is not normal, but the response on restart was harsher than expected.

**Comment by smarterclayton** [comment]
I would expect pod master to hit similar scenarios.  I would expect Mike's
leader library to expose more.  We're just running with 3 master 3
controllers today, so we hit it first.  The other thing we're seeing is
that CPU starvation can cause us to miss our lease renewal, which worries
me that there's something about fairness in the go scheduler or our client
libraries or the etcd client that prevents the very important lease renewal
from getting in in favor of repeated pod lists.

**Comment by lavalamp** [comment]
CPU starvation triggering this sounds like there's already a problem, and
the restart is triggering at the worst possible time.

**Comment by timothysc** [comment]
closed via #23819 & resync issue.
