### ISSUE TITLE
Gluster FS Server Runs outside of the Google Cloud and Mapping it with gcloud - GKE-  Container Client issue

### ISSUE THREAD

**Issue by rasekar2000** [kubernetes/kubernetes#22773]
Hello Team, 
I am having Gluster FS server outside google cloud. And when the same is getting connected ( via Gluster FS Client - mount) from Google VM .

But when I connect to GKE - Container Engine's Docker .. It is **not** working fine .. It worked very fine when the GlusterFS server was inside the Google VM.

5m          3m         2         my-glusterfs-cluster   Service                                                     CreatingLoadBalancerFailed   {service-controller }                           Error creating load balancer (will retry): Error getting LB for service default/my-glusterfs-cluster: Get https://www.googleapis.com/compute/v1/projects/my-my/regions/us-central1/forwardingRules/a822264aee68f11e59e8842010af0008?alt=json: Post https://container.googleapis.com/v1/masterProjects/1068698602830/zones/us-central1-c/tokens: **oauth2/google: can't get a token from the metadata service; not running on GCE**

Here is the service & endpoint, that worked when the GlusterFS is part of the gCloud network ..

----------
  kind: "Service"
  apiVersion: "v1"
  metadata: 
    name: "my-glusterfs-cluster"
  spec: 
    ports: 
      - 
        port: 1

----------
  kind: "Endpoints"
  apiVersion: "v1"
  metadata: 
    labels:
      app: "mystorage"
    name: my-glusterfs-cluster    
  subsets: 
    - 
      addresses: 
        - 
          ip: "104.131.100.100"
      ports: 
        - 
          #port: 1 
          port: 48152
    - 
      addresses: 
        - 
          ip: "104.131.100.101"
      ports: 
        - 
          #port: 1 
          port: 48152

----------

 I kept port as 1 and later tried with the proper port as used in the GlusterFS server. Still the same issue in my docker container's pod .. It just keep getting crashed ...  
 
 Thanks in advance for stepping up to resolve this issue.. 

Thanks and Regards,
Raj

**Comment by rasekar2000** [comment]
After shaking up docker file , 

After the ENV    PM2_HOME   setup, again did the sudo chown once again. 

RUN     sudo chown -R nonroot:nonroot /logfilelocation/logs/
ENV    PM2_HOME   /logfilelocation/logs/   
RUN     sudo chown -R nonroot:nonroot /logfilelocation/logs/

This time docker with application worked fine.. 

And after that to confirm glusterfs client folder mounting disrupting, commented out the second time 

RUN     sudo chown -R nonroot:nonroot /logfilelocation/logs/
ENV    PM2_HOME   /logfilelocation/logs/   
#RUN     sudo chown -R nonroot:nonroot /logfilelocation/logs/

This time also, it worked. So, keeping this ticket in watch status.. Will repeat similar one other dockers as well, if the issue is not reproducible , I will close this as well..

**Comment by lavalamp** [comment]
Please re-post your question to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases.

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to similar questions, and also familiarize yourself with:
   * [the user guide](http://kubernetes.io/v1.0/)
   * [the troubleshooting guide](http://kubernetes.io/v1.0/docs/troubleshooting.html)

Again, thanks for using Kubernetes.

The Kubernetes Team
