### ISSUE TITLE
Make custom metris count limit from cAdvisor available in kube_up.sh

### ISSUE THREAD

**Issue by mwielgus** [kubernetes/kubernetes#22800]
cc @fgrzadkowski @piosz

**Comment by dchen1107** [comment]
Why we need this one? We agreed with custom metrics count limit (:5) for this release because of the resource consumption and other concerns to Kubelet. Once you made this available in kube_up.sh, shouldn't we remove this restriction? Or you just suggest this for future release after we resolved the pending issues of monitoring pipeline? cc/ @vishh to refresh my memory on this. 

cc/ @timstclair who is looking at the standalone cadvisor issue.

**Comment by vishh** [comment]
AFAIK, this issue is referring to the limit in cAdvisor (100 by default)
and not in the kubelet.

**Comment by mwielgus** [comment]
Pivoted strategy around Custom Metrics in HPA. Kubelet and cAdvisor are not used anymore.
