### ISSUE TITLE
Keep seeing TLS handshake error "bad certificate"

### ISSUE THREAD

**Issue by rnataraja** [kubernetes/kubernetes#22822]
Hello,
Iam trying to setup a kubernets cluster with coreos and have hyperkube/v1.1.9.

 I keep seeing the following log on the apiserver

logs.go:40] http: TLS handshake error from xxxxx:60216: remote error: bad certificate
on the api server.  But I do not see any failure logs are seen on the worker kubelet. 

I tried issuing a curl with approproate certs from the worker node and the url acces seems to work fine : 
 curl --key xyz-11-254-worker-key.pem -k https://XXX:443/api/v1/nodes --cert xyz-11-254-worker.pem --cacert ./ca.pem

I also see that the worker node is populated into api/v1/nodes info. Should I be concerned about the error Iam seeing?

Thanks
Rajesh.

**Comment by ArtfulCoder** [comment]
@roberthbailey

**Comment by lavalamp** [comment]
Please re-post your question to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases.

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to similar questions, and also familiarize yourself with:
   * [the user guide](http://kubernetes.io/v1.0/)
   * [the troubleshooting guide](http://kubernetes.io/v1.0/docs/troubleshooting.html)

Again, thanks for using Kubernetes.

The Kubernetes Team

**Comment by lavalamp** [comment]
(personal note: check your kubelet command line.)

**Comment by roberthbailey** [comment]
also note that the error could be from a system component other than the kubelet that is trying to reach the apiserver.

**Comment by rnataraja** [comment]
Thanks

**Comment by rnataraja** [comment]
Thanks. Handshake error happens on the server. I think the error is in the API SERVER when it is trying to connect to kubelet worker. Would that be possible?

Thanks
Rajesh

**Comment by rnataraja** [comment]
I figured it was the worker kube-proxy that was causing the bad certificates on the Kube-apiserver. Still need to figure out how to fix it. Commands look fine to me.

**Comment by stephanlindauer** [comment]
@rnataraja any update on how you fixed it?

**Comment by rnataraja** [comment]
Hello Stephen 

I think it was due to a typo in the proxy yaml file .

I had a tab in the file, and kubelet / apiserver was throwing that error as the first line but would continue normally. Later resulting into handshake error. So see if you have an issue with yaml content and check the logs for error .

Thanks
Rajesh

**Comment by stephanlindauer** [comment]
thanks for the update. turned out my issues were also caused by a typo. :grimacing: :wink:

**Comment by vdoodala** [comment]
I see these errors in api-server logs... any insights ???



I0824 03:36:03.188348       1 log.go:172] http: TLS handshake error from <worker node ip>:38680: remote error: tls: bad certificate
I0824 03:36:18.188186       1 log.go:172] http: TLS handshake error from <worker node ip>:42806: remote error: tls: bad certificate
I0824 03:36:33.188260       1 log.go:172] http: TLS handshake error from <worker node ip>:56866: remote error: tls: bad certificate
I0824 03:36:48.297520       1 log.go:172] http: TLS handshake error from <worker node ip>:39009: remote error: tls: bad certificate

**Comment by azalenski** [comment]
I am also seeing this in my cluster. Can we please reopen this issue?
/reopen

**Comment by lavalamp** [comment]
The error means some client has a wrong / expired cert. This isn't actually an apiserver error, it's working as intended: clients with wrong certs get rejected.

Somewhere in your system there's a client that is probably logging about how it can't connect to apiserver. If the source IP addresses really don't show (I thought they did, maybe they do and an earlier commenter just censored them), you can still probably figure out who is on the other end of the connection attempts by digging around in /proc (e.g. [like this](https://unix.stackexchange.com/questions/233490/show-network-connections-of-a-process)), but it might be easier to just look and see what clients are unhealthy, depending on your setup.

It's intentional that apiserver can't give more detail about the client because it's important to reject connections from bad actors as early as possible, and clients with a bad cert could be such.

We can reopen this only if this is somehow a Kubernetes problem and not a misconfigured client problem.
