### ISSUE TITLE
Using master as a reserved node for kube-system apps

### ISSUE THREAD

**Issue by codefx9** [kubernetes/kubernetes#22820]
I would like a mode in kubelet that will allow running kube-system apps on master and visible via kubectl cli but no user apps can run on master. So far I have not found a way to do this. I have seen that Kubelet runs in 2 mode:
1. Master kubelet stays disconnected. In this mode, secret volumes does not seem to mount on static pods.
2. Master kubelet is connected. I can potentially use a node label to force kube -systems apps to run on master. But then user applications can also get scheduled on master. (am I right on this?)

So, Is this possible to use  master as a reserved node for kube-system apps? If not, can this feature be added?

My motivation for doing this is:
1. This will allow me to run kube-system for systems where PV is unavailable or broken (ex: AWS, rc does not work with replica=1)
2. This will also avoid needing special systems for monitoring master node.

I would like to keep the master node lean. That is why I don't want to avoid running user apps on master. Security is not the concern in this case.

**Comment by lavalamp** [comment]
This is probably a dup, I imagine we have a request for dedicated nodes already. @bgrant0607 might know.

**Comment by dchen1107** [comment]
You can achieve this with 1.2 release. 

1.2 release has daemon_set support as v1beta, Once you have done this, you can use this support to by passing scheduler and place your kube-system pods on master nodes. Of course daemon_set_controller will do feasibility check including resource admission. cc/ @mikedanese on daemon_set status for 1.2 release. 

Once you have done with above step, you definitely want to config your master node with auto-registering. So that you can query / introspect those kube-system pods through kubectl easily. By default on gce we register master node. If you are not no gce, you can config your master kubelet to register itself, but not schedulable. 

Hope this helpful and @bgrant0607 might have other ideas on this.

**Comment by bgrant0607** [comment]
https://github.com/kubernetes/kubernetes/blob/master/docs/design/taint-toleration-dedicated.md

**Comment by bgrant0607** [comment]
But, yes, DaemonSet can place the pods on unschedulable nodes, so that should work in the mean time.

**Comment by bgrant0607** [comment]
In 1.2

**Comment by therc** [comment]
I can definitely confirm that DaemonSet will place the pods on unschedulable nodes (kubelets). I use it for two separate pods on each of my three master nodes on AWS: monitoring and log forwarding. It works as of a few days ago, when the last few bugs I reported were squashed.

**Comment by codefx9** [comment]
@dchen1107, thanks a lot for the detailed answer. Can you please elaborate how do I config the master kubelet to register itself, but not schedulable ?Do I set --api-servers to 127.0.0.1 and --register-schedulable=false ?

A tangential question regarding master kubelet is that how does it handle the race condition on cbr0 interface. What I understood reading the source code is that systemd starts Kubelet, Kubelet creates cbr0 interface, Docker starts running using cbr0 interface, then Kube-apiserver, controller etc pods can run via Docker (static pod). The part I am confused is that to create cbr0 master kubelet will need a pod ip range assignment. For node kubelet, this is received from api server. How does master kubelet get's it's pod IP assignment when master kubelet is registered?
