### ISSUE TITLE
Review when auto-provisioned volumes be auto-deleted

### ISSUE THREAD

**Issue by saad-ali** [kubernetes/kubernetes#22975]
We need to think through the logic that triggers deletion of auto-provisioned volumes. When should it happen? As soon as a PVC is deleted? Should there be a grace period if the PVC is re-created? Are there race conditions in that logic?

@kubernetes/sig-storage @kubernetes/rh-storage

**Comment by saad-ali** [comment]
Will this logic currently delete the PV object if the actual disk is still attached?

**Comment by jsafrane** [comment]
PVs with `PersistentVolumeReclaimPolicy: Delete` will be deleted when appropriate claim is deleted.  When it fails e.g. because tho volume is still attached to a node, the controller tries to delete the volume again in the next update (10 minutes by default), up to 3 times by default (kube-controller-manager --pv-recycler-maximum-retry X).

Currently it's not possible to check if the PV is attached to a node, we may revisit this approach when we have attach controller.

**Comment by thockin** [comment]
Is this issue all covered by the new refactoring?  If so close this?

**Comment by jsafrane** [comment]
Refactored PV controller tries to delete volumes with `PersistentVolumeReclaimPolicy: Delete` in every `syncVolume` call and tries indefinitely, there is no nr. of maximum retries. So, if the disk is still attached, delete will fail and we will retry in 10 minutes in the worst case (see #24236 for reducing these 10 minutes).
