### ISSUE TITLE
Way to identify Master IP public address

### ISSUE THREAD

**Issue by pgmahesh** [kubernetes/kubernetes#22973]
Hi,

I am not sure if this needs to be raised as an issue; However , I do not find any provision to find the corresponding Master public IP address from the application that I run in POD?. ( say I create a kubernetes cluster A, with Master public IP address x.x.x.x; and I create a pod with my app (say a golang or J2ee) on a kubernetes minion belonging to that cluster A. from the App process that is running on cluster A minion, we like to know the public IP address of that Master (x.x.x.x) )
I do not find any Environmental variables for the same.

Kindly help.

BTW, Is there any portal to raise question and clarification?. My advanced apology for this question; as I am knew to this Kubernetes space.

Regards,
Maheshwaran.G

**Comment by zhouhaibing089** [comment]
Maybe what you actually want is the address of `kube-apiserver`?

**Comment by pgmahesh** [comment]
Yes. You are right.

**Comment by viglesiasce** [comment]
You can use the dns name: kubernetes.default

**Comment by pgmahesh** [comment]
Sorry I did not get you. Are you suggesting to use the DNS Name of the API Server in the App that I am deploying on to minion?.

If so that may not work, as the same app can undergo multi cluster deplyment.

**Comment by zhouhaibing089** [comment]
@pgmahesh the dns name inside the cluster, not actually the dns name of the node.

**Comment by Q-Lee** [comment]
Please re-post your question to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases.

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to similar questions, and also familiarize yourself with:
   * [the user guide](http://kubernetes.io/v1.0/)
   * [the troubleshooting guide](http://kubernetes.io/v1.0/docs/troubleshooting.html)

Again, thanks for using Kubernetes.

The Kubernetes Team
