### ISSUE TITLE
does kubernetes support random publish port in Pod? 

### ISSUE THREAD

**Issue by hehailong5** [kubernetes/kubernetes#22981]
like the option -P in docker, a random publish port will be allocated. is there a working way in the kubernetes to achieve the same? I see the "hostPort" in the Pod can be used to specify the publish port, but when doing scaling in the same node, this would run into port collision.

**Comment by pwittrock** [comment]
Each Pod has its own IP address so you shouldn't run into collision unless you have multiple containers in the same pod binding the same port

**Comment by hehailong5** [comment]
the case is that I have one container in the pod with hostPort specified, when scaling multiple instances in the same node, only one Pod would make success, others failed with host port collision.

**Comment by bgrant0607** [comment]
@hehailong5 Why do you need to use host ports? If you explain more about what you're trying to do, there's probably a better way.

**Comment by jiale921** [comment]
I have the same problem ,did you solve the problem?

**Comment by fieryvova** [comment]
In my case, I'd like to run a part of an [Akka cluster](http://akka.io/) in Kubernetes and to have a random host port for every pod. The other part is running somewhere else.
That would allow me to have a unique IP:Port pair for each component of the cluster, which is a requirement to connect them together.
Currently, I don't see any other way to have an external IP:Port combination for every pod in a deployment. If there is another way, please let me know.

**Comment by castrojo** [comment]
Please re-post your question to [Stack Overflow](http://stackoverflow.com/questions/tagged/kubernetes).

Thanks for taking the time to report an issue to us. In the past this tracker has housed both bug reports and user support requests, we are now only using this tracker for software defects and feature tracking.   

We are trying to consolidate the channels to which questions for help/support
are posted so that we can improve our efficiency in responding to requests,
and to make it easier for you to find answers to frequently asked questions and
how to address common use cases.

The Kubernetes team scans Stack Overflow on a regular basis, and will try to
ensure your questions don't go unanswered.

If you're looking for more long-form discussion on best practices, we encourage you to check out the [Kubernetes user list](https://groups.google.com/forum/#!forum/kubernetes-users). 

You can also find more information here:

  * [User Documentation](http://kubernetes.io/docs/)
  * [Troubleshooting Guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/)

Again, thanks for using Kubernetes. If you feel this issue has been closed in error then please reopen it and we can have another look. 

The Kubernetes Team
