### ISSUE TITLE
go template not rendered in user guide

### ISSUE THREAD

**Issue by guoshimin** [kubernetes/kubernetes#23026]
In the new github pages-based user doc, go templates are not rendered correctly. For example, in Kubernetes 101, the template is missing in the command:

```
$ curl http://$(kubectl get pod nginx -o go-template=)
```

**Comment by bgrant0607** [comment]
cc @kubernetes/docs

**Comment by mikebrow** [comment]
Quick look... seems jekyll is processing/consuming text that looks like  `{{ }}` Will google around and see if there is a simple solution.

**Comment by mikebrow** [comment]
Ok... looks like we may need to add raw tags where we don't want `{{ }}` to be parsed as a liquid variable.

example: 
```
{% raw %}
Hello, my name is {{name}}.
{% endear %}
```

**Comment by mikebrow** [comment]
Ayup that fixes it.   But it's a fairly big change would like to hear from the docs owners on this one before I generate a PR for all the cases in the docs where we are missing raw tags.  Esp. since man does not know what to do with these raw tags.. thus the md files will be uglier.  For example:

md: 
```
```shell
{% raw %} $ curl http://$(kubectl get pod nginx -o go-template={{.status.podIP}}) {% endear %}
```
```
converts to html:
```
<div class="highlighter-rouge"><pre class="highlight"><code> <span class="nv">$ </span>curl http://<span class="k">$(</span>kubectl get pod nginx -o go-template<span class="o">={{</span>.status.podIP<span class="o">}}</span><span class="k">)</span> 
</code></pre>
</div>
```
Which looks good on the browser...
`$ curl http://$(kubectl get pod nginx -o go-template={{.status.podIP}}) `
However in man you get:
`{% raw %} $ curl http://$(kubectl get pod nginx -o go-template={{.status.podIP}}) {% endear %}
`

**Comment by mikebrow** [comment]
Ok... looks like this is known.. a dup of: 
https://github.com/kubernetes/kubernetes.github.io/issues/81
