### ISSUE TITLE
Kubelet developer on-boarding / component conventions docs

### ISSUE THREAD

**Issue by pmorie** [kubernetes/kubernetes#23033]
There are a couple gaps that are closely related and entangled with one another:
1.  How do I make the right kind of changes at a higher level than Go coding guidelines?
2.  How do I approach some component of the system and learn the code effectively?

I originally brought this topic up in the sig-node meeting on Mar 15 and was encouraged to write up an issue with a wider scope by @dchen1107.  Hence, my examples are Kubelet-focused.

Let me present as a case study some analysis I did during a recent flake-busting run on the pod IP via env var flake.  The TLDR of that tale is that the existing code was just wrong in the sense that coding conventions in the kubelet were not followed.  In this specific case, the status field in a pod pointer, which should have been read-only, was used to hold the value of the pod IP and was sometimes not set.  The issue was fixed by making the code project-conventional, ie, using the existing internal status management subsystem of the kubelet to get this value where it was needed.

In hindsight, this example seems 20/20 to me as a case where concern (1) above is in play - how do I easily learn the 'way' without necessarily following every single issue and maintaining a mental model of what the current conventions for a component are?  This is not a problem unique to our project, of course, but we should try to have some basic first principles outlined for broad functional areas, at the coarsest possible level of detail to be meaningful without requiring constant update.

Rewinding this story a little to before the fix was determined, debugging the code was pretty instructive for me about learning the code.  I've spent a bit of time in the Kubelet, and yet tracing the Kubelet code and understanding the dependencies of that component was still quite a task.  As it happens, there are around 20 fields of the Kubelet named `*Manager`, `*Cache`, `*Queue`, `*Channel`, etc.  Here is where concern (2) is in play.

These direct dependencies of the Kubelet represent the actors, subsystems, and internal message buses that one has to know in order to reason correctly about the change.  So, in the case of the Kubelet, it might be helpful to have a map-like document of dependencies that describes their roles very concisely, and some behavioral diagrams that show interactions in main code paths like the sync loop.

In the sig node discussion that prompted this issue, we had a loose consensus that something should be done, but also that refactoring efforts shouldn't block on it.  Additionally, it was noted that this type of doc isn't a one-time thing to do, but something that takes maintenance and upkeep.  My personal opinion is that these two factors support that these docs should intentionally be not extensive, and contain as few details as possible while being concise.

@kubernetes/sig-node

**Comment by timstclair** [comment]
I absolutely agree that this is a problem worth addressing, but I think more emphasis should be on cleaning up the code than documenting the current state of affairs (though I do think a higher level kubelet architecture document could be useful).

Following your first example, rather than documenting the higher level convention of when pointers should be read only, I think it would be better to actual enforce this in the code. One option would for components to return deep copies of structures when they should not be modified, but this comes with an unnecessary overhead. An alternative approach would be to create a `ro` package with type aliases for our internal types, and enforce that `ro` types should not be written to. This would not be entirely enforced in code (limitations of go), but is at least self-documenting code.

It's not entirely the point of this issue, but a concrete change we could make to address your second issue would be to "shrink" packages so that each package only contains a single component. This would have the advantage of being able to use go's dependency analysis (and tools such as [godepgraph](https://github.com/kisielk/godepgraph)), and help combatting circular dependencies.

**Comment by pmorie** [comment]
@timstclair 

> I absolutely agree that this is a problem worth addressing, but I think more emphasis should be on cleaning up the code than documenting the current state of affairs (though I do think a higher level kubelet architecture document could be useful).

I agree with you there, and was trying to articulate that I was advocating for a least-effort solution that gets new people enough info to orient themselves while not taking a lot of time to generate.

> It's not entirely the point of this issue, but a concrete change we could make to address your second issue would be to "shrink" packages so that each package only contains a single component. This would have the advantage of being able to use go's dependency analysis (and tools such as godepgraph), and help combatting circular dependencies.

I agree with you in general about this, but I have had numerous experiences where splitting a package is opening a pandora's box of circular deps, so my personal opinion is that such refactors are almost never as easy as they seem on the surface.

Let me attach a price tag, so to speak, to this -- in the case of the kubelet, a couple people should be able to generate the basics in one day or 2 days per person at most.  Anything more than that is likely too much.

**Comment by yujuhong** [comment]
IMO, cleaning up the code is the priority, but it'd be good to have a general guideline so that we can all *work towards* the same goals. Documenting the current state as-it-is doesn't have much value because there are mixed (good and bad) coding patterns in kubelet, and we want to fix them (not just understand them). Eventually, the codebase should be more self-explanatory.

> Rewinding this story a little to before the fix was determined, debugging the code was pretty instructive for me about learning the code. I've spent a bit of time in the Kubelet, and yet tracing the Kubelet code and understanding the dependencies of that component was still quite a task. As it happens, there are around 20 fields of the Kubelet named *Manager, *Cache, *Queue, *Channel, etc. Here is where concern (2) is in play.

Agreed. We should have better interface to hide most of implementation details, as well as simplifying/consolidating a bunch of things. Given that we are going to revisit the container runtime interface (#
#22964), we can definitely put more time into this.

BTW, the cluster team is working on cleaning up the cni and the volume (#14217) code, which should help in general.

> Following your first example, rather than documenting the higher level convention of when pointers should be read only, I think it would be better to actual enforce this in the code. One option would for components to return deep copies of structures when they should not be modified, but this comes with an unnecessary overhead. An alternative approach would be to create a ro package with type aliases for our internal types, and enforce that ro types should not be written to. This would not be entirely enforced in code (limitations of go), but is at least self-documenting code.

In the absence of a special read-only type, I'd suggest assume all arguments are read-only unless you're certain that you *can* and *need* to modify the object. This'd save us from unnecessary copying.

**Comment by pmorie** [comment]
@yujuhong 

> In the absence of a special read-only type, I'd suggest assume all arguments are read-only unless you're certain that you can and need to modify the object. This'd save us from unnecessary copying.

To me the salient point is how you form the certainty.
