### ISSUE TITLE
Are dynamic volumes supposed to be deleted?

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#23032]
Are dynamic volumes supposed to be deleted when the PVC or PV is deleted?

A user brought this up on slack, and I think he opened an issue, but I can't find the issue, and it does appear to be the case that they are not deleted.

**Comment by bgrant0607** [comment]
cc @saad-ali @thockin

**Comment by paralin** [comment]
@justinsb Was that me? https://github.com/kubernetes/kubernetes/issues/22907

**Comment by justinsb** [comment]
@paralin there it is!  Thanks for prompting me - there's a lot going on :-)

Going to close the AWS specific issue, because I saw this on GCE also, and copy over your comment:

> This is definitely an issue. Two pvs are created via pvcs with the "magic annotation" for automatic PV allocation. I then delete the PVCs, wait a bit, and delete the PVs themselves. The volumes remain.

I poked around a very little bit, and there is code to delete a volume, so I think it is supposed to clean up dynamic PDs.  Maybe we're not supposed to delete the PV/PVC, or I may have shut down my cluster too quickly.

**Comment by paralin** [comment]
@justinsb I think deleting the PV object would semantically/logically imply deleting the underlying volume if it was dynamically created. Deleting the claim and making a new claim that bounds to the PV would re-use the dynamically allocated volume.

Is this how it is designed right now? I'd strongly vote for the above pattern :+1:

Thanks!

**Comment by eparis** [comment]
@kubernetes/rh-storage

**Comment by jsafrane** [comment]
A dynamically created volume is deleted when user deletes the **claim** that created it. See https://github.com/kubernetes/kubernetes/tree/master/examples/experimental/persistent-volume-provisioning

**Comment by paralin** [comment]
@jsafrane I would (as an end-user) prefer if it would delete it when the **pv** was deleted as this logically makes more sense - the PV provides the storage, the PVC consumes it. 

Also I've tested deleting the PVC and can confirm that at least on AWS it doesn't delete the volume.

**Comment by markturansky** [comment]
@paralin that's how it works.  Deleting the claim is the trigger to delete the PV.  The actual resource is removed from the infrastructure and then the PV is deleted from the cluster.

**Comment by paralin** [comment]
@markturansky okay, this makes some sense. I still think logically I would expect the PV to stay around in the unbound state until I deleted it via the PV api.

**Comment by jsafrane** [comment]
@paralin: I think that as an end user, you should not mess up with PVs much. You should create claim, let it bind to something (or dynamically provision it) and nag cluster admin if there is no free PV that would match your claim.

If the volume was dynamically provisioned, it should have 'PersistentVolumeReclaimPolicy: Delete' (please check). If it is not removed when you delete appropriate claim then please share your kube-controller-manager logs with loglevel 5.

**Comment by markturansky** [comment]
@paralin the PV can't stay around in an unbound state.  It is used and dirty with someone else's data.  To be "unbound" is to be available for another claim.  This is not that.  So, the PV is "released" and ready for reclamation.

We can't delete the PV *and then* the resource, because if removing the resource fails, it's now orphaned.  So we delete the resource and then the PV.

**Comment by paralin** [comment]
@markturansky @jsafrane this makes sense, thanks for the explanation. Just seems a bit counter-intuitive to have a object be deleted by its claim. But I understand the reasons and completely agree with those decisions.

**Comment by bgrant0607** [comment]
Doesn't sound like this is a 1.2 issue. Removing from milestone.

**Comment by justinsb** [comment]
Yes, thanks!  I was able to confirm that by deleting the PVC and not touching the PV, the PV & underlying disk were deleted (at least on AWS).  If we shut down the cluster without deleting the PVC, we leak the disk, but that is pretty much expected.

**Comment by saad-ali** [comment]
To be more specific, since I was a little confused about this logic, what happens to the PV is controlled by the `persistentvolume_recycler_controller` controller. When the controller sees that the `pv.Status.Phase` is set to `VolumeReleased`, and the [`PersistentVolumeReclaimPolicy`](https://github.com/kubernetes/kubernetes/blob/master/pkg/api/types.go#L295) is `PersistentVolumeReclaimDelete`, it triggers the volume deletion logic. All dynamically provisioned volumes [are created with](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/persistentvolume/persistentvolume_provisioner_controller.go#L370) the Policy set to `api.PersistentVolumeReclaimDelete`.

**Comment by neverfox** [comment]
> Just seems a bit counter-intuitive to have a object be deleted by its claim.

It's not deleted by the claim. It's deleted if it has a retention policy that says it should self-delete if it finds itself unclaimed. If that's not the desired behavior, the retention policy should be changed to Retain.
