### ISSUE TITLE
Our API code is hard to understand

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#2306]
I've been digging through our API code in order to automatically document the API, and it's hard to understand.

The division between master and apiserver isn't clean, and the API machinery is spread out between (at least) api, runtime, conversion, version, and registry, with a seemingly arbitrary decomposition into files and a bewildering proliferation of interfaces (storage, codec, scheme, ...). Additionally, it's not obvious which code is used by the server, by clients, or both. Also, ideally, the generic machinery would be cleanly separated from Kubernetes's specific API object implementations.

After we get some API plugins working, I suggest we look hard at how to simplify and reorganize this.

/cc @lavalamp @smarterclayton

**Comment by bgrant0607** [comment]
For example, why does api/conversion.go exist?

**Comment by yujuhong** [comment]
Isn't api/conversion.go there to add/register the conversion functions?

In general, I agree the API code is hard to understand. There are too many interfaces, and I am not sure they are all that necessary. A little background and/or higher-level overview on the API code would definitely help a newbie like me.

**Comment by bgrant0607** [comment]
@yujuhong Which conversion functions? vs. v1betaN/conversion.go files?

**Comment by smarterclayton** [comment]
Originally it was to facilitate containermanifest -> podspec, since kubelet continued to support legacy paths.

**Comment by yujuhong** [comment]
It seems like a temporary place to hold conversion functions. All of them can and should be moved to v1beta1/v1beta2/v1beta3, etc eventually.

**Comment by smarterclayton** [comment]
There will always be internal objects you want to convert across, although it should be a few (due to reuse of common structs.

**Comment by thockin** [comment]
It also hosts "copy constructors" that have been externalized from objects
because we have resisted making methods on objects.

If we were not allergic to methods we could make the same-type conversion
functions be methods, as well as the semantic-equal functions.  And then we
could talk about defaults and validation as methods.

**Comment by smarterclayton** [comment]
*aachoo*

----- Original Message -----

**Comment by bgrant0607** [comment]
@smarterclayton I'm increasingly concerned about the API code complexity. Could you please sketch what API layers/modules we have in the client and server, what they do, and why they exist? I very much want to preserve extensibility and testability, but would like to find a way to reduce the number of levels of indirection, or at least rationalize and streamline the organization.

**Comment by smarterclayton** [comment]
Yes agree.  

----- Original Message -----

**Comment by davidopp** [comment]
Some new people joining the team have also mentioned the API code complexity. When I joined the team a couple of months ago I also found it baffling (and largely still do, even though I wrote a fairly large CL that modified it). At the very least we need to document what we have (both in the code *and* in a separate design doc). It would also be nice if we could simplify it.

**Comment by bgrant0607** [comment]
What do I include in "API code"?
* pkg/master
* pkg/apiserver
* pkg/api -- except */types.go (though #1451, #1744, and #3914 are relevant)
* pkg/conversion
* pkg/registry
* pkg/runtime
* parts of pkg/util and pkg/types

Really, there are 3 overlapping sets of code:
1. API serving infrastructure: master, apiserver, registry, api
2. API decoding/encoding/conversion: api, conversion, runtime
3. Components implementing the API objects: controllers, schedulers, kubelet, etc.

**Comment by davidopp** [comment]
FWIW I think the badness situation is basically 2 is the worst, then 1, then 3.

**Comment by smarterclayton** [comment]
Can you define badness in terms of actionable cleanup for 2?

----- Original Message -----

**Comment by bgrant0607** [comment]
The actionable cleanup for (1) and (3) are most clear to me.

As discussed in #1451 (1) and #2726 (3), the apiserver should be entirely generic. Status should be pushed into etcd via calls to apiserver by controllers and not computed on the fly by apiserver. Validation and defaulting code should live with the registry objects. The individual registry objects shouldn't have any custom etcd code.

Mainly what I wanted to be the topic of this bug was (2), and I don't yet understand that code well enough to prescribe a solution.

**Comment by smarterclayton** [comment]
I think we have very clear paths for 1 that can be described today (based on iterative steps Dan and I had been taking).  3. Definitely can be simplified to fit more closely to helpers around gorestful, but that's been mostly small changes made at each point, and as you say it's in the best shape.

For 2, I can describe a fair amount of what is there now in the context of trying to tie external versions to go structs.  The Scheme is a bit of a catch all object that could be more cleanly factored into a smaller object.  Encoding and decoding are above the scheme, because they can use the go structs directly, except for some coupling to the object structure themselves which we can work around.  Some of the complexity in the code is an attempt to be moderately efficient (although encode/decode/conversion are anything but today), which has a lot of low hanging fruit.

I'll try to draft up something on that specifically soon (and #1, because from where we are today to where we want to be should be moderately mechanical refactoring).

**Comment by smarterclayton** [comment]
Next steps for simplifying RESTStorage, registry, generic registry, and etcd behavior:

* Create and Update are the two *complex* REST behaviors that need to follow strict rules based on our agreed schema
  * UID, creation timestamp need to be filled
  * Name is either provided or Generated
  * Validating a create is not the same as validating an update
  * Some fields are ignored on create (today)
  * Some fields should be ignored on update - silently merged (today)
  * The fields that are ignored or automatically merged are resource specific, and in the future we will allow automated systems to define those
* The general storage pattern for our existing resources is similar, with a few resources like pods that attempt to maintain two objects without a transaction (pod and the underlying bound pod, for constraint checking)
  * In the future, there will be limited transactional operations in etcd, and most other reasonable KV stores we would consider already have multi-put (consul, zookeeper, all SQL databases, cockroachdb, a few other), therefore transactional store guarantees *MUST* remain in the registry layer, but the etcd registry currently can leave things lying around that either need to be cleaned up or read repaired
  * In the time period between now and when etcd has multi-put, we may decide we need an "etcd transactional cleanup controller" that periodically cleans up mismatched references
* Some objects, during update, need to non-transactionally check the state of the store to validate other objects (to look for overlaps between RCs, for example)
  * This is also a responsibility of the registry, because transactional guarantees would make those checks more effective and the registry layer can hide those checks
* Having one etcd registry for all our resources (`pkg/registry/etcd/etcd.go`) is not necessary and potentially encourages people to couple resources of different types together
* We can potentially nuke the async channel in REST to simplify it (since we can do that async operation more easily at a higher level)

The current path implementation:

1. Implement a generic etcd registry object that takes generic API "resources", performs the necessary generic API transformations, has hooks for per-resource behavior, and in general actively discourages deviating from the "API pattern"  (mostly done)
2. Implement all per resource API logic like merging for updates in a way that is not tied to a particular backend (`pkg/api/rest`)
3. Each RESTStorage implementation is a thin wrapper that combines 1 and 2 to expose the supported methods for a resource.
4. The generic test suite on top of 2 can be reused for all resource types, with special cases per resource (see `pkg/api/rest/resttest`)

Example:

```
// Implements RESTStorage for pods on top of ETCD
type PodEtcd struct {
  registry GenericEtcd
}

func NewPodEtcd() RESTStorage {
  return &GenericEtcd{rest.Pods} // the "api logic" for pods is defined in a way that matches an interface
}

func (r *PodEtcd) Update(obj runtime.Object) (chan Result, error) {
  return registry.Update(obj)
}
```

It's assumed that writing stores to new backends is relatively uncommon, and that the test suite would be easily adapted to new storage types.  So we preserve the behavior that PodEtcd implements RESTStorage, and that the apiserver can check whether RESTStorage implements a method via a cast to an interface.

Remaining todos:

* Remove async channel on interfaces
* Figure out how metadata about the API can come from RESTStorage to go-restful to swagger
  * The more of this we do, the less apiserver is anything other than a set of utility functions for transforming rest storage into go-restful, which is what we want
* Need to determine how we model updating status for both end users (who are likely to not want to clobber status when they PUT) and for system users - probably via a flag / header / query param / new rest resource that imposes different behavior.

**Comment by bgrant0607** [comment]
Thanks for the writeup @smarterclayton. Will try to digest and reconcile with previous discussion in #1451.

I don't yet understand the division between pkg/conversion and pkg/runtime, which contain marshaling/unmarshaling, conversion, defaulting, some generic metadata accessors, some registry-like functionality (per-kind functionality, collections of kinds), support for extensions, and probably some other stuff.

**Comment by thockin** [comment]
I think I like 99% of what's written here.  The part I want clarity on is how widespread knowledge of etcd needs to be?  I was expecting to see something along the lines of #2594 wherein the kernel of the API server knows that etcd is how we implement the generic Storage interface.  All other REST object code simply uses the generic Storage.

More succinctly - the word "etcd" should not appear in the codebase except in the implementation of the storage interface and the code that constructs the concrete instance.

**Comment by davidopp** [comment]
FWIW I think this would be a great topic for the contributors meeting--describe the current partitioning of this functionality and the proposal.

**Comment by bgrant0607** [comment]
Ok, I think I understand this now. However, I second @thockin's question about etcd. 

There is currently business logic in pkg/registry/etcd/etcd.go that doesn't belong there, such as status field initialization upon create or update. It's horrible that the business logic is spread between individual registry objects (e.g., pkg/registry/pod/rest.go), etcd.go, pod_cache.go, and the responsible components (controller-manager, kubelet, etc.). And that doesn't even include the validation, conversion, defaulting, and fuzzing logic. 

A primary goal has to be to consolidate object-centric mutation logic. Making the apiserver framework totally generic and the etcd layer totally generic are also important goals.

Objects shouldn't care about details like what keys are used to store them in etcd -- that should be generically derived from Kind. 

We should solve field selection #1362 generically, also.

Preconditions should all be reducible to resourceVersion-based preconditions.

The BoundPods stuff will go away with BoundPods.

**Comment by smarterclayton** [comment]
> On Feb 9, 2015, at 3:12 AM, Brian Grant <notifications@github.com> wrote:
> 
> Ok, I think I understand this now. However, I second @thockin's question about etcd.
> 
> There is currently business logic in pkg/registry/etcd/etcd.go that doesn't belong there, such as status field initialization upon create or update. It's horrible that the business logic is spread between individual registry objects (e.g., pkg/registry/pod/rest.go), etcd.go, pod_cache.go, and the responsible components (controller-manager, kubelet, etc.). And that doesn't even include the validation, conversion, defaulting, and fuzzing logic.
> 
> A primary goal has to be to consolidate object-centric mutation logic. Making the apiserver framework totally generic and the etcd layer totally generic are also important goals.
> 
Yes - binding etcd storage to object mutation logic will be the only place someone should see etcd (in master.go where we instantiate it, and in the actual types that do the binding).  Those types should be small - a few lines per method at most.

**Comment by bgrant0607** [comment]
See also #1451

**Comment by smarterclayton** [comment]
@thockin given your previous complaints about boilerplate, here's the rough "add a new type using the new model" code - https://github.com/smarterclayton/kubernetes/commit/6e4ba792727861e69d5ec4b643b878ee6c5de9fa

**Comment by smarterclayton** [comment]
Started a proposal / summary here https://github.com/GoogleCloudPlatform/kubernetes/issues/7111

**Comment by lavalamp** [comment]
It's still getting worse, not better, along the understandable metric.

**Comment by bgrant0607** [comment]
cc @mml

**Comment by smarterclayton** [comment]
* I think the storage and storage initialization code has metastasized a bit, as well as API initialization
* We've got a proliferation of clients - I think we're up to 35 different clients total.
* api/unversioned is a mess.

**Comment by smarterclayton** [comment]
The majority of the refactors have been executed in 1.6, although more work in documentation is certainly helpful.  We actually have clean separation of core packages, layering, and stronger control on what goes where.
