### ISSUE TITLE
AWS: Wily goes unresponsive after some hours

### ISSUE THREAD

**Issue by paralin** [kubernetes/kubernetes#23117]
I set up an AWS cluster on Wily last night, and this morning I can't ssh into the master, and the API is not responding either.

It looks to me like a memory overflow. I have the master on t2.micro, which might be too small. 

Maybe we should install the "swapspace" package in the setup script? This way even if the server has a small amount of memory it won't run out.

**Comment by zmerlynn** [comment]
I'm not sure this is the right fix. We should be right-sizing masters so this doesn't happen in the first place rather than papering over the problem when we hit it.

**Comment by paralin** [comment]
@zmerlynn in the same note I would rather not have the master go unresponsive, wrong size or not.

**Comment by zmerlynn** [comment]
A longer response: This changes one {platform, cloud} combo to not-hardcap the master for memory, when in general the master should be running with memory restrictions for all of the individual pieces (`apiserver`, `controller-manager`, etc.), and we should be doing the right thing so that among {platform, cloud} combos, we actually just right-size the master and the individual pieces.

**Comment by paralin** [comment]
Master just went unresponsive for the same reason I think..

**Comment by paralin** [comment]
Hmm never mind I think in this case it was a routing issue in our AWS account

**Comment by zmerlynn** [comment]
cc @justinsb 

I've had this PR hanging out for a while, what say you?

**Comment by paralin** [comment]
I still think it should be merged, because the master isn't even enabled for scheduling right now, and is a mission critical component.
