### ISSUE TITLE
AWS: jessie deployment needs additional cgroup kernel features enabled

### ISSUE THREAD

**Issue by paralin** [kubernetes/kubernetes#23142]
The AWS jessie deployment needs `CONFIG_CFS_BANDWIDTH=y` in the kernel.

See: https://github.com/openshift/origin/issues/8074#issuecomment-198029115

This might not be the easiest thing to do. Re-compiling the kernel is pretty unrealistic, and installing a package to enable the option is not something I'm too sure is possible.

For now a temporary fix is to use `wily` instead.

**Comment by paralin** [comment]
cc @justinsb @bparees @smarterclayton

**Comment by markine** [comment]
Hello,

Seeking clarification: what's the recommended way for Kubernetes end users to get CPU limits working on AWS? Is using the wily image a well supported and stable config?

jessie is the default image for AWS installs for kubernetes v1.2.4. Out of the box the AWS installation silently fails to enforce CPU limits. The message "WARNING: CPU hardcapping unsupported" in Node status is an obscure/silent error (kube describe nodes | grep "CPU hardcapping").

Thank you,

Mikhail

**Comment by justinsb** [comment]
I am planning on creating a debian image with a custom kernel for 1.4, which will include CONFIG_CFS_BANDWIDTH=y.

Thanks for pointing this out!

**Comment by markine** [comment]
FYI, jessie image installed by kube-up.sh for 1.4.0 does not yet have CONFIG_CFS_BANDWIDTH set.

```
$ grep CONFIG_CFS_BANDWIDTH /boot/config-3.16.0-4-amd64 
# CONFIG_CFS_BANDWIDTH is not set
```

**Comment by justinsb** [comment]
The kops AMIs do now include a kernel with this enabled.

You can see the latest kernel name here: https://github.com/kubernetes/kops/blob/master/channels/stable#L3

It's probably too tricky to get into kube-up because 4.4 doesn't support aufs, so you have to use overlay and that feels like the sort of change we shouldn't be making now that kube-up is in maintenance mode.  Another good reason to use kops :-)  But if you don't want to, you can now use the AMI :-)

**Comment by markine** [comment]
Thank you @justinsb . It is my understanding that kops is not yet the canonical/standard/recommended way of bringing up clusters yet; kube-up.sh is still "it" for 1.4. Am I mistaken? Thank you!
