### ISSUE TITLE
Could not determine public IP from AWS metadata.

### ISSUE THREAD

**Issue by antoineco** [kubernetes/kubernetes#23155]
In Kubernetes 1.2.0, the message `aws.go:745] Could not determine public IP from AWS metadata.` appears every 10 sec in the kubelet logs.

I don't think it is necessary to try to determine a public IP which doesn't exist every 10 sec (the instance is on a private subnet) nor to notify about it every 10 sec.

**Comment by BradErz** [comment]
I'm currently working on a HA setup with nodes in multiple private subnets.

I'm also getting this error even when spawning kube-up with:
KUBE_ENABLE_NODE_PUBLIC_IP=false

**Comment by bboreham** [comment]
Would it be appropriate just to raise the glog v-level up a bit so it's not in the logs by default?

**Comment by matalo33** [comment]
I feel like this is an issue. Calling the API so frequently to determine if there is a public IP will adversely impact the API rate limit imposed by AWS on clusters with a large number of minions.

**Comment by ichristo** [comment]
I second this as an issue.  In our configuration, it is expected that there isn't a 'public-ipv4' value from the AWS metadata service since we're in private subnets as well.  

It should be suppressed when an appropriate flag is set and I would agree that it shouldn't be called frequently, it at all, when the configuration is in a valid state.

**Comment by derekwaynecarr** [comment]
see referenced PR to reduce log spam.
