### ISSUE TITLE
Bring PodSecurityPolicy to usable state

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#23217]
The PodSecurityPolicy object was merged by @pweil- in #7893.

That defined a new type, (https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/extensions/v1beta1/types.go#L919), a registry, kubectl support, and a client.  

We still need to:
- [x] expose the extension by default, and generate the docs for it.
- [x] write code that decides whether a Pod create/update is allowed by any maching PSP. (assume this exists downstream in openshift.)
- [x] decide on a way to determine which type applies to which requests; that is, something to bind request attributes, like user, groups, namespace, with the PSPs that apply to that pod.
- [x] write admission controller code that does the previous two things and says yes or no to Pod creates/updates.
- [ ] define behavior when multiple PodSecurityPolicy objects allow a pod - #52849
- [ ] define a way for policy authors to affect which PSP is selected when multiple PodSecurityPolicy objects allow a pod - #52849

**Comment by erictune** [comment]
@pweil- will you have time to do any work on PSP in the next few weeks?

**Comment by pweil-** [comment]
@erictune yes, many apologies for the delays.  I have still been wrapped up closing the current release.  Been a little crazy.

**Comment by quinton-hoole** [comment]
Assigning to @erictune to add priority label.

**Comment by sttts** [comment]
Any news about this work? I am referencing `PodSecurityPolicy` in my sysctl proposal #26057.

**Comment by pweil-** [comment]
> Any news about this work?

@sttts the PSP admission controller has been merged.  The next step is the authorization of individuals for specific PSPs.  Your proposal should be ok with what is there now.

**Comment by sttts** [comment]
@pweil- great @ admission controller. I guess some update of this issue (the check boxes above) is necessary? For the record: admission controller https://github.com/kubernetes/kubernetes/pull/24600

**Comment by Calpicow** [comment]
I'd like to see PSPs bindable as default and to namespaces. I think it would cover a common use-case where kube-system could run with elevated privileges while all other namespaces are homogeneous in their permissions.

**Comment by liggitt** [comment]
> I'd like to see PSPs bindable as default

that would be possible by binding to `system:authenticated` or `system:serviceaccounts` groups

> ...and to namespaces. I think it would cover a common use-case where kube-system could run with elevated privileges while all other namespaces are homogeneous in their permissions.

that would be possible by binding to service accounts in the kube-system namespace

**Comment by jheiss** [comment]
And perhaps related to my previous question, is there a plan for how to apply PSPs to pods created by replication controllers? More specifically, I would want to apply a PSP policy based on the user that created the replication controller. But it seems like currently the PSP admission controller sees those pod requests as coming from the Kubernetes machinery itself.

I don't know if the right course of action is to apply PSPs to each pod in a replication controller when the replication controller is created, or annotate the replication controller with info about the original user and then apply PSPs to the pods as they are created. It seems like the later is better from a security standpoint, otherwise you could update your PSPs but have replication controllers still able to create now invalid pods indefinitely.

**Comment by liggitt** [comment]
It was decided to accomplish the binding via a check against the authorizer. The admission plugin currently checks which PSP objects the current user has the "use" verb on. See the example RBAC role in the PSP example

**Comment by jheiss** [comment]
@liggitt: Thanks, I think that gets me pointed in the right direction.

**Comment by jheiss** [comment]
I wanted to mention a couple of issues/concerns we have with the current state of the PSP feature. Neither is a blocker for us but I thought I'd make a note of them.

- If I have a PSP with a runAsUser MustRunAs rule and submit a pod with no runAsUser specified it is accepted. The original PSP proposal seems to indicate that in this case it will be left to kubelet to enforce based on the user specified in the container image. I don't know if that is implemented, but in our case we'd rather have the pod rejected by the PSP admission controller. We're going to add our own admission controller that defaults any pod lacking a runAsUser to run as the user who submitted it.
- We would like to associate PSPs with namespaces. Since many of our PSPs will reference namespace-specific service accounts (per my last round of questions here), the PSP ends up being somewhat namespace-specific. But it seems like RBAC "use" rules associating a PSP to users currently must be ClusterRoles/ClusterRoleBindings. I tried using a RoleBinding and it didn't work.

**Comment by pweil-** [comment]
> If I have a PSP with a runAsUser MustRunAs rule and submit a pod with no runAsUser specified it is accepted. The original PSP proposal seems to indicate that in this case it will be left to kubelet to enforce based on the user specified in the container image. I don't know if that is implemented, but in our case we'd rather have the pod rejected by the PSP admission controller. We're going to add our own admission controller that defaults any pod lacking a runAsUser to run as the user who submitted it.

The PSP admission controller (if enabled) should be rejecting pods that do not meet the requirements or default the values if the user doesn't specify anything.  If you did enable the admission controller please check the security context on the pod after it was admitted and see if it defaulted to the correct UID.  

PSP relies on the kubelet to enforce the `MustRunAsNonRoot` rule but the `MustRunAs` rule should be rejected up front like you're hoping.  

One other thing I can think of is if the user has access to multiple PSPs and one of them allows any uid.  If your logging is up to at least level 4 you should see a message like `validating pod %s (generate: %s) against providers %s` that lists the providers available and then `pod %s (generate: %s) validated against provider %s` for which provider validated the pod.  The provider is also stored in `kubernetes.io/psp` annotation on the pod for reference.

> We would like to associate PSPs with namespaces. Since many of our PSPs will reference namespace-specific service accounts (per my last round of questions here), the PSP ends up being somewhat namespace-specific. But it seems like RBAC "use" rules associating a PSP to users currently must be ClusterRoles/ClusterRoleBindings. I tried using a RoleBinding and it didn't work.

I can envision the use case of wanting to grant usage of the PSP to all users/service accounts of a namespace but I'm not sure I understand the use case of a PSP belonging to a namespace.

**Comment by liggitt** [comment]
> I can envision the use case of wanting to grant usage of the PSP to all users/service accounts of a namespace but I'm not sure I understand the use case of a PSP belonging to a namespace.

it is allowing use of a PSP within a namespace - same thing I asked about in https://github.com/kubernetes/kubernetes/pull/33080#discussion_r84147987

**Comment by liggitt** [comment]
> One other thing I can think of is if the user has access to multiple PSPs

pay careful attention to which user is actually creating the pod. in the case of pods created via replicationcontrollers, etc, it is actually the controller user that creates the pod. to get PSP authz to take effect, that controller must be running against the secured port, and as a user that doesn't have access to the powerful PSPs

**Comment by jheiss** [comment]
@pweil-: Ah, indeed. You are correct that if I don't specify a runAsUser the pod gets defaulted to the first MustRunAs UID in the first PSP that matches. We probably want a different default in our case, but it is good to know that it is preventing the user from running things as an arbitrary UID.

**Comment by ericchiang** [comment]
@liggitt was wondering if there was anyone on the RedHat side of things working on this. We've also had customers interested in this feature.

Would it be reasonable to extend PSP to deployments, replication controllers, jobs, etc.? Naively, extending the admission controller to check anything with a pod template?

**Comment by Raffo** [comment]
@ericchiang We were thinking of doing what @liggitt suggested (restricting permissions for the controller manager and so on), but we're also interested in contributing a change to the relevant admission controller.

**Comment by hjacobs** [comment]
@ericchiang extending PSP to deployments, replication controllers, jobs, etc. (everything with pod template) sounds like the way to go to me.

**Comment by liggitt** [comment]
Not sure, for a few reasons.

1. PSP relies on being able to apply limiting defaults to pod specs. Applying those defaults to the parent objects (deployments/replicasets, etc) could lock specific user uids in place too early in the process, rather than at the point in time where the resulting pod was created.
2. PSP relies on the relevant aspects of the pod spec being immutable, which does not hold for deployments/replicasets, etc. Would need to figure out what it means for user A to create a deployment, and user B update an unrelated aspect.
3. Enforcing at the parent object level would mean giving complete PSP permissions to *all* controllers that create pods based on parent objects, which expands the chances of a confused deputy attack

**Comment by Raffo** [comment]
@liggitt I understand your point of view and it definitely includes some challenges, but the current implementation doesn't give a very good experience to the users as it is a bit confusing in terms of what is accepted and what is not and, from my experience, nobody really deploy a pure `Pod` in real production clusters. Additionally, it requires a configuration of the controller manager and relevant authorization that shouldn't be strictly necessary.

**Comment by liggitt** [comment]
I think limiting the inherent permissions of the thing actually creating pods (the replicaset controller, etc) is important to avoid confused deputy attacks.

**Comment by Raffo** [comment]
I get it, but this is very confusing for the user. The user has some permissions and wants to know if she can get something to run on the cluster. The user should not know, in my opinion, that there's a controller manager or any other component. Running the pod should be something done "on behalf of the user" and thus having the same type of constraint. I'm not sure how this would be translated at best in kubernetes terms though.

**Comment by liggitt** [comment]
> Running the pod should be something done "on behalf of the user" and thus having the same type of constraint

That is intentionally not the way the system is designed. If the pod was created on behalf of the user, if the user left the company and lost permissions, deployments they happened to be the one to create in a collaborative namespace would suddenly stop working.

**Comment by ericchiang** [comment]
@liggitt thanks for explaining.

Our issue is that our clusters run mixed workloads. Some need privileged access, some don't. The exact requirement is "having namespaces which don't allow privileged pods." I figured we'd apply policies to users that were only allowed to use those namespaces.

Maybe the controller master could use different credentials based on the namespace? That'd allow us to say "no privileged pods in this namespace."

That being said I think a mode which focused on end users and the objects they work with rather than individual controllers and pods would be useful. It'd certainly be something we'd be interested in exploring.

**Comment by Raffo** [comment]
@liggitt Maybe I wasn't clear, this is not what I meant: if we make the decision early (in the admission controller) we can have the "running the pod is something done on behalf of the user" kind of experience, without having to deal with the scenario that you mentioned in your previous comment.

**Comment by liggitt** [comment]
> Maybe the controller master could use different credentials (edit: when created pods) based on the namespace? That'd allow us to say "no privileged pods in this namespace."

That's what connecting the PSP permissions to the service account is accomplishing.

**Comment by kargakis** [comment]
@php-coder
