### ISSUE TITLE
Use case: How to create test pod with other label from  production pod for stateful container

### ISSUE THREAD

**Issue by tweakmy** [kubernetes/kubernetes#23235]
The obvious is that there is a running stateful pods(etc database) with volume mount. The volume mount is assume to faciltate for rolling update. However, i have got a use case where i would like to create a same set of database with it latest state but with s different image.One could do it by means of copying but that way is too clunky and it is anti kubernetes semantic. What is your advice?

**Comment by thockin** [comment]
I'm not sure I understand what you want to do, but as far as I can understand there is no built-in way.  We do not parameterize a pod by another pod ever.   You can do this client-side, maybe?

Or are you talking about sharing volumes?

I think this is more of a "support" style request and should probably be done in StackOverflow so other people can find it more readily.  Please file it there, with as much detail as you can provide. I'm going to close this now.  If it turns out that there is a feature request or bug behind this, feel free to reopen this.
