### ISSUE TITLE
move to a build tool that has dependency calculation

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/kubernetes#23236]
We need this for both the compilation phase and the release packaging phase. Building a release is incredibly inefficient right now and a huge development slowdown.

**Comment by thockin** [comment]
Are you mostly concerned about build time or things like only running tests
that have changed?  I have done significant experimentation here.  Here are
my current thoughts:

Easiest plan is to move to `glide` for dependency management and once we
get go-1.5 as a minimum requirement, the back-to-back build time (the
second being a no-op) was O(seconds).  It should be ~0, but it's not.  Go
still ends up relinking the final binaries.

More controversial plan is to move to `gb` as a builder and abandon plain
old `go build`.  The back-to-back build time is less than 1 second.  This
would require SIGNIFICANT repo reorg, or that we symlink into existence a
directory tree that gb likes.  This latter is not hard, but `...` builds
will never work (the core go libs that gb uses don't traverse symlinks.
Why?  Because Go).  Our own build can be made to work.

Beyond those points, we will need something that knows to regenerate
auto-gen code when source files change.  To me that says "Makefile".  We
could hide all the details behind scripts & Makefiles, such that `make all`
works and works fast.  This means `go get` is a secondary concern, which is
true anyway once we stop checking in auto-gen code.

**Comment by mikedanese** [comment]
I am concerned with both correctness and speed of build.

There are bugs in that pile of shell. For example @madhusudancs and I chased a bug a couple weeks ago on my work station where I was generating code that looked like it was from a codegentool from an old revision of the repository. My repo was synced to master. We spent a few hours writing print statements and analyzing huge debug outputs to finally find that I needed to run a `make clean`. Stuff like that should not happen.

As far as performance, gb and glide both sound great if if they support better comilation caching then whatever we are currently using. We should use something akin to a Makefile to calculate when we need to regenerate autogenerated code. We should also make a dependency graph of the release tars in the same manner. Ideally if I change a shell script in cluster/, it should take >10 seconds to rebuild the release artifiact. It should be a single retar operation.

**Comment by thockin** [comment]
I am 100% in favor.  I think we need to decide between glide and GB and
"other".  I have a repo converted to glide, it compiles, but godep is not
fully excised. I need to time it against go-1.6.

My hope was to build a new parallel Makefile with simpler build scripts
backing it.

**Comment by pires** [comment]
I like glide as well. gb is cool, and most my projects are still using it, but it's hard to manage transitive dependencies. It will fetch them but won't remove them if they're no longer needed.

**Comment by thockin** [comment]
I am 98.1 % on-board with Glide.

On Wed, Sep 7, 2016 at 12:56 AM, Ilya Dmitrichenko <notifications@github.com

**Comment by mikedanese** [comment]
fyi Bazle POC: #32774

**Comment by techtonik** [comment]
I would stuff SCons directly into repo https://godot.readthedocs.io/en/stable/development/compiling/introduction_to_the_buildsystem.html

**Comment by spiffxp** [comment]
/remove-sig testing
/remove-sig contribute-experience
pretty sure we're solidly on the path to bazel-all-the-things at this point via sig-release
