### ISSUE TITLE
kubelet failed to add host's DNS servers to pod container

### ISSUE THREAD

**Issue by fuliangliu** [kubernetes/kubernetes#23320]
kubernetes version: v1.2
docker version: 1.8.3
os: centos 7.1

see the help doc of kubelet option --cluster-dns below:
--cluster-dns="": IP address for a cluster DNS server.  If set, kubelet will configure all containers to use this for DNS resolution  **in addition to the host's DNS servers**

I set this option to my cluster dns, **but it failed to add host's DNS servers to pod container**. it added the cluser dns only. Thus, the program in the pod container could not access the domain name outside my cluster!
BTW, kubernetes v1.1.7 works well.

**Comment by AdoHe** [comment]
I will take a look asap.

**Comment by thockin** [comment]
The bug is the docs.  @artfulcoder changed it to be a single DNS
`nameserver` entry (long explanation).  We should update the docs to say
this value is used for the DNS server in case of Pods with
"dnsPolicy=ClusterFirst"

Can one of you make that change?

Thanks.

**Comment by AdoHe** [comment]
Ok, will update the doc.

**Comment by fuliangliu** [comment]
@thockin  But what should I do if I want the pod to contain both the cluster DNS 'nameserver' entry and the host  DNS 'nameserver' entry ? 
In my mind,  the "dnsPolicy=ClusterFirst" definition means that the cluster DNS 'nameserver' entry sits above the the host  DNS 'nameserver' entry in the file "/etc/resolve.conf", isn't it?

**Comment by thockin** [comment]
Please read https://github.com/kubernetes/kubernetes/pull/18089 for
rationale on why that doesn't work.  ClusterFirst is a little bit of a
misnomer now but it hard to change since it is part of the API.  We could
probably change it to a different string with the same meaning, maybe, but
I'd need to think through that.

The DNS server itself will forward requests to the "upstream" DNS.
