### ISSUE TITLE
Consume configMap resourceVersion in ENV or File

### ISSUE THREAD

**Issue by sadlil** [kubernetes/kubernetes#23326]
can a `configMap` `resourceVersion` be mounted in a volume or in Environment variable? like `downwardAPI`. 
If not could this Feature be added?

**Comment by zhouhaibing089** [comment]
ConfigMap could be mounted both as volume or env.

As env: https://github.com/eBay/Kubernetes/blob/master/docs/proposals/configmap.md#consuming-configmap-as-environment-variables-1

As volume: https://github.com/eBay/Kubernetes/blob/master/docs/proposals/configmap.md#consuming-configmap-as-volumes

I do not know what `resourceVersion` is though. :)

**Comment by sadlil** [comment]
@zhouhaibing089 yes. we can consume ConfigMap as both. But i was asking for the `resourceVersion` of `configMap`, one of the metadata to be consumed. [resourceVersion](https://github.com/kubernetes/kubernetes/blob/master/docs/design/configmap.md#consuming-configmap--updates) is sated here.  If this field could be consumed as like `downwardAPI` for pod wors would be better.

**Comment by pmorie** [comment]
@sadlil I don't think we should expose this through an env var, since they cannot be updated without restarting the process.  In our current implementation of the volume, I might be able to buy having a special file that contained the resource version, with emphasis on _might_.  I need to think about it.

Any thoughts, @thockin ?

**Comment by thockin** [comment]
If I parse correctly the request is to know what version of a configmap is
being presented?  If so, that really needs to be user-managed.
ResourceVersion is an ever-increasing value that changes when any change is
made to the resource.  ConfigMap doesn't currently have a 'status' block,
but it is not inconceivable. If that ever happened (or an atime field or
any other mutation) then Resource version would jump.

If you need to version your config, stick that in the config.

**Comment by sadlil** [comment]
one more extra metadata or an field `dataVersion` can be added to the resource. This can indicate the configMap data version, which is completely separate from the resource version. This can be updated in time the of updating the data. and can be mounted as a file.

**Comment by bgrant0607** [comment]
@sadlil What would you like to use resourceVersion for?

**Comment by sadlil** [comment]
@bgrant0607 in my case i am using configMap for loading configuration for some of my running applications inside pod. My applications needs to reboot if the configurations changes. So i need to watch over if the ConfigMap data is changed or not.

**Comment by thockin** [comment]
I still don't think that's what you want.  Can you just md5 the projected file and set an inotify on it so that any inotify update you can checksum it yourself?  That said, if the contents of the file don't change we don't even write the new file, so simply using inotify should be enough.

I don't think resourceVersion is what we want to do here,

**Comment by DanyC97** [comment]
@thockin sorry for a dummy request, by any chance do you have an example ?

**Comment by mengqiy** [comment]
@DanyC97 You may be interested in this example: https://github.com/kubernetes/kubernetes/tree/master/examples/https-nginx
