### ISSUE TITLE
Quota for DaemonSets and Deployments

### ISSUE THREAD

**Issue by vishh** [kubernetes/kubernetes#23360]
Do we need to quota for deployments and daemon sets? In general, would it make sense to expand the quota machinery to take into account other `Kind`s of objects in the API?

cc @derekwaynecarr

**Comment by derekwaynecarr** [comment]
In general, yes, but some things are more important than others.

I want to quota services by type so we can limit node ports and load
balancers separately.

See:

https://github.com/kubernetes/kubernetes/pull/22154

I want to quota how much storage we let pvc bind against in 1.3.

We should extend to the other types, but I am not sure how quick I want to
do that until we support post deletion hooks in admission control in API
server or we clear up what we can do to use etcd v3 multi object
operations.  The quota controller right now is responsible for observing
deletes across many kinds and I want to get a more efficiency there because
watching all kinds is not ideal.

As a result, I am stalling a little bit on reviewing this PR:

https://github.com/kubernetes/kubernetes/pull/22040

**Comment by kargakis** [comment]
/remove-lifecycle rotten

Still an issue afaik

**Comment by nikhita** [comment]
/remove-lifecycle-frozen

Ability to do object count quota was added in https://github.com/kubernetes/kubernetes/pull/54320. It works for both deployments and daemonsets.

Closing.
/close
