### ISSUE TITLE
How to only process the last notification from creating rc or deleting rc

### ISSUE THREAD

**Issue by hehailong5** [kubernetes/kubernetes#23369]
Hi,
I am using the list watch to watch the changes to kube pods, when I create a RC or delete a RC, the event handler would both receive a bunch of update notifications,  among them, there are many notifications indicating the intermediate status, how to avoid to handle all those intermediate notifations but process the last notifcation for each pod? I just want to handle the last update notification for creating RC and the last remove notification for deleting RC.
Thanks a lot!

here goes my watch function:
----------------------------------------------------------------------------------->
func watchForPods(kubeClient *kclient.Client, queue chan<- KubeWork) {
	var podController *kframework.Controller
	_, podController = kframework.NewInformer(
		createPodLW(kubeClient),
		&kapi.Pod{},
		resyncPeriod,
		kframework.ResourceEventHandlerFuncs{
			AddFunc: func(obj interface{}) {
				sendPodWork(KubeWorkAddPod, queue, obj)
			},
			DeleteFunc: func(obj interface{}) {
				sendPodWork(KubeWorkRemovePod, queue, obj)
			},
			UpdateFunc: func(oldObj, newObj interface{}) {
				if reflect.DeepEqual(newObj, oldObj) == false {			
					sendPodWork(KubeWorkUpdatePod, queue, newObj)
				}
			},
		},
	)
	stop := make(chan struct{})
	go podController.Run(stop)
}
<--------------------------------------------------------------------

**Comment by zhouhaibing089** [comment]
```go
func watchForPods(kubeClient *kclient.Client, queue chan<- KubeWork) {
    var podController *kframework.Controller
    _, podController = kframework.NewInformer(
        createPodLW(kubeClient),
        &kapi.Pod{},
        resyncPeriod,
        kframework.ResourceEventHandlerFuncs{
            AddFunc: func(obj interface{}) {
                sendPodWork(KubeWorkAddPod, queue, obj)
            },
            DeleteFunc: func(obj interface{}) {
                sendPodWork(KubeWorkRemovePod, queue, obj)
            },
            UpdateFunc: func(oldObj, newObj interface{}) {
                if reflect.DeepEqual(newObj, oldObj) == false {
                    sendPodWork(KubeWorkUpdatePod, queue, newObj)
                }
            },
        },
    )
    stop := make(chan struct{})
    go podController.Run(stop)
}
```
to make the code more readable. :)

**Comment by maisem** [comment]
Please re-post your question to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases.

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to similar questions, and also familiarize yourself with:
   * [the user guide](http://kubernetes.io/v1.0/)
   * [the troubleshooting guide](http://kubernetes.io/v1.0/docs/troubleshooting.html)

Again, thanks for using Kubernetes.

The Kubernetes Team
