### ISSUE TITLE
Split the "resync interval" on reflectors into "relist interval" and "resync interval"

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#23394]
Today the resync interval on a controller forces a LIST, and then as a consequence sends all objects down the reflector.  However, for most controllers LIST is necessary because 

1. Watch is reliable
2. They do not mutate the store themselves and thus might have data out of sync with etcd
3. They do not "drop" events when failures happen (instead they requeue)
4. Their source of data is relatively up to date, or isn't vulnerable to event reordering (B happens before A and is therefore ignored).

We should split "sync" into "sync" (send all events to listeners) and "list" (clear the cache and fetch from etcd).

All reflectors against etcd should have long "list" intervals (12-24h).  Controllers that don't mutate the store or drop events should have long relist intervals AND resync intervals.  For controllers that drop events or mutate the store in a potentially inconsistent way, we should relist infrequently and resync frequently.

The following reflectors are "fast" - every 30s

```
*api.Service from controller/endpoint/endpoints_controller.go:129
*extensions.Job from controller/job/controller.go:140
*api.ReplicationController from controller/replication/replication_controller.go:209
*extensions.DaemonSet from controller/daemon/controller.go:210
*extensions.HorizontalPodAutoscaler from controller/podautoscaler/horizontal.go:121
```

These reflectors should have a 24h relist.  We should separate resync, then tune each appropriately.

**Comment by smarterclayton** [comment]
@kubernetes/goog-control-plane @kubernetes/sig-cluster-ops

**Comment by smarterclayton** [comment]
Spawned from https://github.com/openshift/origin/issues/8229

**Comment by lavalamp** [comment]
I'd actually argue for not setting a relist period at all-- keep watching
until the network flakes out on you.

But since we do require that case to work, shortish relist periods in our
testing seem appropriate to me still.

**Comment by smarterclayton** [comment]
So you don't agree list and sync should be different intervals?

**Comment by hongchaodeng** [comment]
> we should relist infrequently and resync frequently.

May I ask what's difference between "relist" and "resync" here?

**Comment by smarterclayton** [comment]
Re-list is "make a LIST call to the API server".  Resync is "go through the
items in the cache and queue them up so that anyone on the other end sees
them all change again".  There are controllers that retry up to X times and
then continue (assuming the next resync will get a chance to try again),
and in a few cases the controllers mutate the cache (so it does need to be
refreshed from the server).

**Comment by wojtek-t** [comment]
@smarterclayton - 
+1000 for this idea
I definitely agree with all you wrote above. [In fact I also wanted to suggest something like that few months ago, but then forgot about it].

>
I'd actually argue for not setting a relist period at all-- keep watching
until the network flakes out on you.
But since we do require that case to work, shortish relist periods in our
testing seem appropriate to me still.

I think the idea behind relisting is mostly for tests. We still want to test the "relist" behavior, because it will be happening in reality due to e.g. connection issues. So we want to have it set for something relatively small (e.g. few minutes) in our tests.
On the other hand, I agree that setting it to infinity in production sounds like a good idea.

**Comment by smarterclayton** [comment]
Another reason to resync (without relisting) is to be able to handle delta
store comparisons against an external resource.  I.e. if you have X
external resources, and N internal resources, you want to verify X=N every
few minutes, but you don't need to LIST /services at the same rate you LIST
GCE loadbalancers (in the service load balancer controller)

**Comment by lavalamp** [comment]
I agree they should be different intervals. I'm arguing that the default
value for "relist" should be "never". :)

**Comment by smarterclayton** [comment]
Oh, then we're in agreements

**Comment by wojtek-t** [comment]
I can work on it, but I'm going to US for a week tomorrow, so not earlier than in ~2 weeks. If noone picks it up before then, I'm happy to do it.

**Comment by rrati** [comment]
I'm taking a look at this.  We have charts that seem to show the impact of the 30s fast reflectors:
![cpu_periodic](https://cloud.githubusercontent.com/assets/87555/14258548/d97701d8-fa70-11e5-84b3-1cd342d6d7f2.png)

As a first pass and possibly easy immediate change, I plan to try jittering the updating of those 30s reflectors.  That seems like it could be a quick and easy way to level out those spikes.  I'll log a separate issue for that.

**Comment by wojtek-t** [comment]
I'm not sure it makes much sense - we need a proper fix as described by @smarterclayton and it's not a very big change and we should do it anyway. So we should first do the main part and only then do some tweeking.

**Comment by timothysc** [comment]
Rob's intent is to make an independent change, and we now have tests for a baseline comparison in place.  IMHO we should do both.  I aimed him in this direction and the first thing we noticed was, we are way to periodic in the KCM.  So in trying not to step on toes, we'll do that first, compare.  

Hopefully this is a little less confusing.

**Comment by wojtek-t** [comment]
What I wanted to write is that I think that after proper fix (separating relist from resync) the cpu spikes are supposed to be significantly smaller (maybe small enough to even ignore them). That's why I think that we should start with that.

However, if you need to do fix it now (and can't wait until that is properly fixed - which I hope should happen in, say 2 weeks), then I'm fine with adding some jittering now.

**Comment by timothysc** [comment]
I may get to it before you ;-)

**Comment by wojtek-t** [comment]
@timothysc - that would be great; just let me know when you would be able to start working on it, so that we won't be duplicating work.

**Comment by hongchaodeng** [comment]
In etcd3, there is a relevant feature called [IsProgressNotify()](https://github.com/coreos/etcd/blob/b0cc0e443c163f36f29d078dd855ca9c7b68e612/clientv3/watch.go#L67-L69) from watch response.

@wojtek-t Would you like to share any implementation plan?

**Comment by wojtek-t** [comment]
@hongchaodeng - sorry, I didn't have time to deeply think about it

**Comment by bprashanth** [comment]
Just for the record.

> *api.ReplicationController from controller/replication/replication_controller.go:209

This is a 30s relist of RCs IIUC. That used to not even matter given the number of RCs one has on average in the system. Each rc will not force a relist of pods.

The reflectors also have a 5m timeout: https://github.com/kubernetes/kubernetes/blob/c6e995a824094a96f7d43a25e897283f83a12997/pkg/client/cache/reflector.go#L87
But I don't *think* it causes a relist. Didn't check apiserver side, does it return a relist forcing error on "timeout?" ?

And the apiserver will break watch on some random interval in the 1-2h range (or maybe it was 30m-1h): https://github.com/kubernetes/kubernetes/blob/dae5ac482861382e18b1e7b2943b1b7f333c6a2a/pkg/apiserver/watch.go#L142

**Comment by wojtek-t** [comment]
@bprashanth - breaking watch doesn't necessary cause relist (in fact in majority of cases it won't - it will simply cause initiating next watch without relisting).

**Comment by bprashanth** [comment]
Of course, I meant specifically if the apiserver returns an error on "timeout?" that causes listWatch to return https://github.com/kubernetes/kubernetes/blob/c6e995a824094a96f7d43a25e897283f83a12997/pkg/client/cache/reflector.go#L308, which I'm going to guess doesn't happen

**Comment by smarterclayton** [comment]
Should not, anymore (server should close <timeout)

**Comment by smarterclayton** [comment]
We're close to 5k RCs on a single cluster :)

**Comment by hongchaodeng** [comment]
I think [resync chan](https://github.com/kubernetes/kubernetes/blob/206308ea1453a34308a547c01819172af7b8b0e8/pkg/client/cache/reflector.go#L368) is duplicate to timeout.

After the timeout, it will check canForceResyncNow() and do resync/relist if needed. Am I right on this? If so, I can do some quick refactoring.

**Comment by lavalamp** [comment]
> I think resync chan is duplicate to timeout.

@hongchaodeng This code is tricky and has been wrong a number of times. Please don't make any changes that don't have a very pressing immediate need.

**Comment by timothysc** [comment]
@wojtek-t we're (mostly @rrati) are digging into this now, we have profiles on the spikes showing the list offenders.

**Comment by rrati** [comment]
Looking at the code and doing some experimentation has lead me to find that the culprit for those huge spikes in the replicationcontroller controller.  Looking at how that operates I found that

FullControllerResyncPeriod in pkg/controller/replication/replication_controller.go:564

Is set to the 30 second period I was seeing.  The comment implies this period is supposed to be used to resync against the local cache, however it is passed as the resyncPeriod to the Informer at:

pkg/controller/replication/replication_controller.go:564

Which looks to cause a full re-list every interval (in this case, 30s).  So I tried playing with that number. I set it to 1 hr for testing and from what I see in the logs the reflector is acting as expected.  I submitted a new rc and replicas were created.  The impact on the cpu utilization from that change is dramatic:

![all_cpu_1hlist](https://cloud.githubusercontent.com/assets/87555/14354483/71bfca7e-fcab-11e5-86e5-dcde8379b34b.png)

unit and integration tests pass as well.  Unless I'm missing something, a quick and impactful change could be to set that resync period, and other resync periods for the controllers, to something much larger.

**Comment by bprashanth** [comment]
>	// We'll attempt to recompute the required replicas of all replication controllers
	// that have fulfilled their expectations at least this often. This recomputation
	// happens based on contents in local pod storage.

That's accurate. The relist of RCs is from apiserver. The relist of pods is from pod storage. 

Also I think you've just inferred what the title of the bug says :)

**Comment by wojtek-t** [comment]
I think there was still some confusion about what this is about. I tried to clarify it in:
https://github.com/kubernetes/kubernetes/pull/24142#issuecomment-213285093
but also pasting here for completeness

>
@wojtek-t So I dove all through the code and I've come full circle on this. Splitting out a relist interval makes no sense to me, because for the reflector "a resync is a relist" (that's all it does, there is only one meaning...), all that needs to be done is set the existing s/resync/relist for most timers to 0, which is what rob has done in this patch, and is done in most places in the code.

Yes - for reflector, "resync" means "relist" - but we don't want to touch this. The problem is the Informer.
To clarify - most of controllers, actually need to periodically go through all objects to perform such actions - and this is called "resync period". Currently this is strictly coupled with "relist" period for the underlying reflector - you can't set different values for those 2 things.
However, assuming that e.g. namespace controller wants to go over all namespaces every 30s, there is completely no reason to force the relist of all namespaces every 30s.
And this effort is basically about it.

>
The forced re-list will still occur on watch breaks/errors, and that is what coreos/etcd#5148 is meant to address. I think breaking out yet another parameter only conflates things.

Correct. But I think it's not a big issue.

>
IMO I would vote for patching most timers to 0, and eventually removing s/resync/relist entirely.

We can't do it now, because some controllers really need to go through all objects periodically. And splitting these two things has a goal of setting "relist" period to 0 in the end of the day.

@smarterclayton @lavalamp - if any of you have anything to add to the above ^^

**Comment by smarterclayton** [comment]
I agree 100% with everything you described.

**Comment by timothysc** [comment]
After chatting with @wojtek-t it makes more sense.  I was missing a subtlety in how the delta_fifo.replace relabeled the contents as "Sync" to be handled in the Process function.

**Comment by timothysc** [comment]
closed via: https://github.com/kubernetes/kubernetes/pull/24142
