### ISSUE TITLE
Creating TLS ingress on GKE failes with k8s 1.2

### ISSUE THREAD

**Issue by jerryjj** [kubernetes/kubernetes#23401]
I've been trying to setup the HTTPS Load-Balancing using the ingress and secrets in test project.
However when I create the Ingress with kubectl it never goes in to error loop saying it does not have permissions to create the instance groups:
```
  2m		2m		1	{loadbalancer-controller }			ADD	production/production-ingress
  2m		2m		498	{loadbalancer-controller }			GCE	Post https://www.googleapis.com/compute/v1/projects/----/zones/europe-west1-c/instanceGroups?alt=json: oauth2/google: can't get a token from the metadata service; not running on GCE
```

I can create network load-balancers successfully so the scopes are correct and valid.

**Comment by mml** [comment]
Please re-post your question to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases.

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to similar questions, and also familiarize yourself with:
   * [the user guide](http://kubernetes.io/docs/user-guide/)
   * [the troubleshooting guide](http://kubernetes.io/docs/troubleshooting/)

Again, thanks for using Kubernetes.

The Kubernetes Team
