### ISSUE TITLE
kubectl run applies bad default CPU requirements

### ISSUE THREAD

**Issue by broady** [kubernetes/kubernetes#23403]
I was trying to run a docker image using `kubectl run`

I saw this kind of failure:

```
fit failure on node (gke-getuser-1cf9f3b1-node-z76p): Node didn't have enough resource: CPU, requested: 100, used: 920, capacity: 1000
```

run requested 100 CPU

```
    Requests:
      cpu:  100m
```

No pods were running on that node (a GCE g1-small node). I expected my container to be able to run.

**Comment by broady** [comment]
`n1-standard` also didn't have enough resource.

**Comment by broady** [comment]
Running a second node did help, though. Should the tutorials say that you can't just run a single node cluster?

**Comment by mml** [comment]
We should at least document this defaulting behavior.  There are flags to set requests and limits, but both just say that the default is "", which is obviously not correct.

```
      --limits="": The resource requirement limits for this container.  For example, 'cpu=200m,memory=512Mi'
      --requests="": The resource requirement requests for this container.  For example, 'cpu=100m,memory=256Mi'
```

**Comment by ScyDev** [comment]
I have exactly the same problem. It happened on `n1-standard-1` and it happens on `g1-small`.

First I'm deploying a Mongo container which really does noting at all on its own.
Then I deploy a Meteor container, and 2 out of 3 times the problem is: 
`Node didn't have enough resource: CPU, requested: 100, used: 920, capacity: 1000`

I really don't think an idle Mongo DB is using 920 CPU.

The problem then seems to stick, for a specific node.
Retrying on that node doesn't work in a usable time frame.
If I delete the two ReplicationControllers and delete the node and then create the ReplicationControllers again once a new node is ready, after a few iterations of this, both containers settle on the same node.
Then everything works fine until I have to re-create one of the containers and problems start again.

Adding more nodes to the cluster doesn't really seem to help. GKE tries to place both containers on one node (which is perfectly reasonable) and if that node happens to have that problem, it will continue the fail loop.

Also, adding resource limits didn't help either:
```
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 500m
            memory: 500Mi
```

**Comment by Tyguy7** [comment]
Same issue here.  +1

**Comment by mml** [comment]
> Node didn't have enough resource: CPU, requested: 100, used: 920, capacity: 1000

Pretty sure this means 920 *millicores*.  We should also improve that message.

**Comment by bgrant0607** [comment]
cc @janetkuo

**Comment by ScyDev** [comment]
Just tried it again with a `n1-standard-1` node. Isn't it strange that the exact same error appears as on a `g1-small` node?

`Node didn't have enough resource: CPU, requested: 100, used: 920, capacity: 1000`

Shouldn't the `n1-standard-1` have more capacity than the `g1-small`?

**Comment by Caravus** [comment]
That's work for me (n1-standard-1, 1 node, 1 pod):
>         resources:
          limits:
            cpu: 1000m
            memory: 1000Mi
          requests:
            cpu: 10m
            memory: 100Mi

**Comment by Tyguy7** [comment]
Caravus' solution is what worked for me as well.  The interesting thing is that I still got the same "requested 100, used 920" response when setting limits, until I reduced the limits to a passing level.  Almost as if that was a hard coded response if the limits failed.

**Comment by derekwaynecarr** [comment]
@mml - the cli help text is right...  the defauting semantic is being applied server side via the `LimitRange` in the namespace.  If you specify an explicit request, the `LimitRange` should not override.  If we update the help text in the CLI, we should just say that server side components may assign a cpu/memory request/limits depending on the server configuration (i.e. limit ranges, vertical auto sizers, initial resources, etc.)

**Comment by ScyDev** [comment]
How can I find out what is actually using 920 of 1000 CPU on my node?

**Comment by derekwaynecarr** [comment]
`kubectl describe node/yournode` has a detailed section on allocated resources and the pods that consume them.

**Comment by mml** [comment]
@derekwaynecarr fair enough, that'd be a start.  `kubectl run` (and `create`) could also print a warning to stderr whenever server side defaulting gets applied.

**Comment by derekwaynecarr** [comment]
@mml the defaulting will be applied when pod creation happens and not when deployment/replicaset/replicationcontroller happens so its not clear how we would warn appropriately.

**Comment by ScyDev** [comment]
@derekwaynecarr Thanks. Yes, I can see the requests and limits with `kubectl describe node mynode`, but how can I see what is actually, really used? In order to make the requests and limits better fits?

**Comment by cyberaleks** [comment]
Same issue on n1-standard-1. I'm wondering why kube-dns always allocates 31%. Is it expected behavior? Does it mean that i need more than 1 instance ( more than 3 micro instances), because 70% are reserved by kubernetes?

fluentd-cloud-logging:  80m (8%) CPU Requested
heapster-v1.0.2-2627135191-3rzmu: 150m (15%) CPU Requested
kube-dns-v11-v8vnl:  310m (31%) CPU Requested
kube-proxy: 20m (2%) CPU Requested
kubernetes-dashboard-v1.0.1-9q23s: 100m (10%) CPU Requested
l7-lb-controller-v0.6.0-6aqoc: 110m (11%) CPU Requested

Allocated resources:
  CPU Requests	CPU Limits	Memory Requests	Memory Limits
  ------------	----------	---------------	-------------
  970m (97%)	670m (67%)	794Mi (21%)	1594Mi (42%)

**Comment by broady** [comment]
Could someone else add the label? I don't know what team is appropriate.

**Comment by broady** [comment]
/remove-lifecycle rotten

No updates on this?

**Comment by chrissound** [comment]
Related: https://github.com/kubernetes/kubernetes/issues/33777

**Comment by janetkuo** [comment]
#24700 clarifies --limits and --requests flag already, so closing. 

> I can see the requests and limits with `kubectl describe node mynode`, but how can I see what is actually, really used? In order to make the requests and limits better fits?

@ScyDev You can use `kubectl top nodes`
