### ISSUE TITLE
[1.2] local cluster setup with hyperkube doesn't work

### ISSUE THREAD

**Issue by vishh** [kubernetes/kubernetes#23417]
I tried following the official docker based local cluster setup guide [here](http://kubernetes.io/docs/getting-started-guides/docker/#prerequisites) on OSX and it fails to work in the case of v1.2.

There are several issues. Enumerating a few of them.
- [x] API server is not accessible from outside of the docker VM host. 
- [ ] Image garbage collection fails
- [ ] Problem with nsinit - #19069 might solve this.
- [ ] Volumes cleanup - #22911
- [ ] Master node setup is racy - #23197

Some of the issues above are common to other linux based platforms too. This issue will serve as an umbrella issue for getting hyperkube functional soon.

**Comment by vishh** [comment]
xref: https://github.com/kubernetes/kubernetes.github.io/issues/159

**Comment by ericandrewlewis** [comment]
Thanks for posting this @vishh, I'm having the same problem. However, the docs are hosted in the separate repo, of which you linked to a similar issue.

Let's close this as a duplicate of that.

**Comment by vishh** [comment]
@ericandrewlewis: The issue against docs is specifically about the content in the docs. This issue is meant to resolve technical issues.

**Comment by vishh** [comment]
> API server is not accessible from outside of the docker VM host.

@pwittrock pointed out that the API server is bound to localhost only by default. I assume binding to all the interfaces is not an ideal default. We can make that configurable to work around this issue.

**Comment by luxas** [comment]
/cc @luxas

I think there are a reason why apiserver listens only to localhost on the docker guide, security. 
However, if we document it, I may update docs and hyperkube to listen on all interfaces (0.0.0.0). 
Can't find the issue with that discussion right now.

The image garbage collection would be good to have: #14403.

Other issues: #22927 #22911 #12856

How to run kubelet "natively" instructions here: #4869

**Comment by vishh** [comment]
@luxas @pwittrock: I assume hyperkube is meant for ease of use and not a production setup, given the fact that it is hardened yet. Why should we care about security as of now?

**Comment by luxas** [comment]
I'm OK with updating [127.0.0.1 in single node] to (https://github.com/kubernetes/kubernetes/blob/master/cluster/images/hyperkube/master.json#L34) to [0.0.0.0 in multi-node](https://github.com/kubernetes/kubernetes/blob/master/cluster/images/hyperkube/master-multi.json#L34)
I may send a PR with this quite trivial change now.
It should be documented too.

**Comment by luxas** [comment]
@vishh Do you think we should collect hyperkube-related issues to this issue? (umbrella issue)
If so, update title to reflect that.

**Comment by vishh** [comment]
xref: #23092

**Comment by vishh** [comment]
@luxas: #23092 suggests setting up a ssh tunnel to work around the port issue. I'm ok with that solution too.

**Comment by luxas** [comment]
Ok, let's leave as-is. But it should be documented, I may send a PR soon. 
IIUC, the command one have to run on Mac is
```
$ docker-machine ls
$ docker-machine ssh $MACHINE_NAME -N -L 8080:localhost:8080
```
and it'll work.
Probably other small things could be improved as well
cc @pwittrock

**Comment by pwittrock** [comment]
+1 on using an ssh tunnel instead of changing the insecure bind.

While you are in there, would you also update the kubectl and docker image version to 1.2.0 instead of the alpha version?

**Comment by huggsboson** [comment]
one thing to keep in mind with SSH tunnels is that it is somewhat harder for people to manage who are using docker machine (OS x).  It'd be nice if there was consistency between multi and non-multi.

**Comment by huggsboson** [comment]
If this turns into an umbrella issue, I believe #23197 is the thing causing various people issues with SkyDNS.

**Comment by luxas** [comment]
@vishh 
> Problem with nsinit - #19069 might solve this.

I think we won't fix this, it turns out `--containerized` works pretty well in `v1.2` for the most setups.
However, add that we should document how to run "natively" with docker 1.10+

> Master node setup is racy - #23197 

Fixed with #23550.

Another thing you should add is #20514. Since `make-ca-cert` is downloading Brendan's fork of `easyrsa`, internet connection is required. It also makes it impossible to use k8s with a proxy.
I may look into this, one easy fix would be to download the `.tar.gz` file on build-time, not run-time.
AFAIK, easyrsa has fixed the thing Brendans' fork fixed, so it might be an idea to refresh the `make-ca-cert.sh` script itself

**Comment by luxas** [comment]
One thing more, I think we're dependent on a quite new `findmnt` binary on host, so it doesn't work with RancherOS for example. Haven't tested with `v1.2.2` though, just `v1.2.0-alpha.6` or something

**Comment by jimmyjones2** [comment]
@luxas Just submitted a PR for including easyrsa in hyperkube image - #24218

**Comment by huggsboson** [comment]
@luxas I just noticed today that with a --containerized kubelet (/var/lib/kubelet mounted rw) that configMap's weren't functioning as volumes correctly.  It would create the volume's dir, but wouldn't put the configMap files into it.

**Comment by luxas** [comment]
@pmorie Doesn't ConfigMaps work with `--containerized`?
We should fix that before `v1.3`!
I don't think it's too hard to solve, we just need to use the `NsEnterMounter` I think

**Comment by tym-oao** [comment]
I hope this is the right place to note that the suggested port-forwarding workaround for OS X doesn't work with the new native Docker for Mac beta, there not being a `docker-machine` VM to ssh to. The `xhyve` hypervisor included with Docker for Mac does not include a ssh daemon AFAIK.

**Comment by pwittrock** [comment]
@tym-oao Thanks for letting us know.  Do you have a work around we can add to the documentation, or would you be interested in creating a PR to update it?

cc @dlorenc 

We are working on an alternative solution to replace the dockerized hyperkube (called 'minikube').

**Comment by vishh** [comment]
Docker for Mac is untested. We are working on `minikube` which will replace
the current docker based setup soon.

**Comment by the-destro** [comment]
I'll happily help with testing it out on the Docker for Mac stuff if you need testers.

**Comment by pwittrock** [comment]
@the-destro Cool.  You can checkout the pre-release from [minikube](https://github.com/kubernetes/minikube)

**Comment by the-destro** [comment]
@pwittrock looks like it is vbox only right now. I can poke around at some of the internals to see if I can coax a docker for mac setup out of it

**Comment by tym-oao** [comment]
@pwittrock @the-destro Yes I took a look at minikube first, but since it requires a VM anyway I figured I can just use hyperkube in docker-machine for now. 

As for workaround or fix in Docker for Mac, the one idea I've had is to get the `apiserver` container to expose port 8080, either by adding a `ports` element to the spec in `master.json` or setting up each of the kube-system pods with a docker-compose file, and include the 8080 binding for apiserver there.  Either one seems to me like it should work, but so far I haven't had any success. I suspect I'm just not doing it right, though, somehow. I'll be happy to share if I get something working satisfactorily. 

Since I didn't mention it earlier, I should add that hyperkube itself stands a cluster up in Docker for Mac just fine; the only issue is how to connect anything to it from the outside Mac host. If I run `kubectl` from another docker container on the Mac installation, I get access to everything that way. This may well Docker for Mac's issue to resolve in the end: there are already reported issues with routing from the Mac host to containers on the Docker bridge network.

**Comment by dlorenc** [comment]
We're looking at using the Docker for Mac setup in minikube, but don't have
anything to report yet. It's definitely in our roadmap. I haven't played
with it too much yet, but I've also had some trouble with connectivity.

**Comment by bgrant0607** [comment]
@vishh @luxas Could we please document what is and is not expected to work at this point? Users are following the instructions and running into problems (e.g., #22911).

**Comment by the-destro** [comment]
It would be nice if minikube and [Kube Solo](https://github.com/TheNewNormal/kube-solo-osx) could be merged or fleshed out. It does almost what I need but I also need outside users to be able to view the host.

**Comment by luxas** [comment]
However, I'm closing this as both the hyperkube singlenode and multinode guides have been deprecated and removed successfully
