### ISSUE TITLE
OpenStack, NodePort and floating IPs

### ISSUE THREAD

**Issue by andrejvanderzee** [kubernetes/kubernetes#23421]
Hi,

I have noticed that when I specify a service as NodePort on a VM running on OpenStack, the service is bound to the public floating IP. I would expect it to bind to its "private" IP and use externalIPs to bind to public floating IPs. Based on what logic does Kubernetes decide what IP to bind to?

Thanks,
Andrej

**Comment by jayunit100** [comment]
Maybe you should launch your kubelets using the `node-ip` option ?  otherwise probably it just grabs the default first ip address.

**Comment by jayunit100** [comment]
in any case, in kubelet.go, you can see the logic  for how the defaults are found... i guess in openstack the public IP is not the first non-loopback that is listed
```

				// check all ip addresses for this node.Name and try to find the first non-loopback IPv4 address.
				// If no match is found, it uses the IP of the interface with gateway on it.
				for _, ip := range addrs {
					if ip.IsLoopback() {
						continue
					}

```

**Comment by zhouhaibing089** [comment]
@jawnsy should not nodePort be `kube-proxy` things?

**Comment by zhouhaibing089** [comment]
@jayunit100 the node port should be handled by `kube-proxy`, right?

**Comment by ArtfulCoder** [comment]
@andrejvanderzee NodePort will bind to all addresses considered as local to the host.
The public service IP must be considered local to your machine, as a result, nodePort is binding to that address as well.

**Comment by ArtfulCoder** [comment]
My suspicion is that openstack is routing the public ip, to maybe a set of hosts without DNAT-ing the traffic.

**Comment by mml** [comment]
Please re-post your question to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases.

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to similar questions, and also familiarize yourself with:
   * [the user guide](http://kubernetes.io/docs/user-guide/)
   * [the troubleshooting guide](http://kubernetes.io/docs/troubleshooting/)

Again, thanks for using Kubernetes.

The Kubernetes Team
