### ISSUE TITLE
Create abbreviation for configMaps

### ISSUE THREAD

**Issue by luebken** [kubernetes/kubernetes#23438]
ConfigMaps is a resource which will be handled quite often in the CLI. An abbreviation would help in less typing. Also it would implicitly propose a standard for naming files: e.g. `myapp-cm.yml``

I would like to propose to use `cm` as an abbreviation for `configMaps`.

**Comment by pmorie** [comment]
@luebken Great minds think alike; in my implementation of kubectl integration w/ configmap, I had `cm` as an abbreviation.  @smarterclayton didn't like it -- still feel the same way, Clayton?

**Comment by smarterclayton** [comment]
We generally abbreviate long things.  We should never have abbreviated
"pods" or "nodes" or "events".  With bash autocomplete most names should be
easy to type.  I'm on the fence about 9 characters in general, I'm more on
the fence about the abbreviation here because secret is only six, and we
deliberately did not add an abbreviation for it.  Service got the nod
because it is a very commonly typed value - I'm not sure that config map
falls in the same bucket.

The other reason not to hand out abbreviations is because we don't know
when we might actually want to use "cm" for something longer.

**Comment by luebken** [comment]
@smarterclayton I was referring to configmaps not secrets.

+1 for not handing out abbreviations left and right. But I don't understand why we have `ing` for `ingress` and `ds` for `daemonsets` but not `cm` for configmaps. 

for me it's more than bash completion. it also gives some guidance for using these abbreviations elsewhere like naming the yaml files.

**Comment by smarterclayton** [comment]
Ingress probably shouldn't have been handed out either.  The point is
to come up with a process for resolving and reserving names since
short names are also an API.

Regarding file name, I would probably expect to use "foo-config.yml"
for it (especially if it was secrets and config)

@kubernetes/api-review needs to weigh in - I'm going to require
whatever rules we come up with here before merging this goes into
API-conventions.md so we can refer to it in the future.

**Comment by smarterclayton** [comment]
How about `config` as an abbreviation?  That parallels with `secrets`, and I don't think we would ever add a `config` object (since config map is our simpler object).

**Comment by pmorie** [comment]
I can get behind `config`

**Comment by smarterclayton** [comment]
From a rationalization perspective, *everyone* is going to call these config (no one is going to say the map at the end if they have to).  "I put it in a config."  "Which config is it?"  "Did you update the config?" etc.

From the CLI:

```
kubectl get config
kubectl describe config/master
kubectl delete config/foo
```

**Comment by smarterclayton** [comment]
Also, it disincentives others in the community from creating a generic `Config` kind.

**Comment by thockin** [comment]
Can we just make a shortest-prefix rule?

**Comment by smarterclayton** [comment]
What's that rule?

**Comment by thockin** [comment]
You only need to type as many letters as are needed to uniquely identify a
resource Kind.  Obviously, don't do this is scripts because of future
ambiguity.

The flattening on apiversion and kind here also seems to imply that we can
never have the same Kind used in2 different apigroups, right?

**Comment by smarterclayton** [comment]
Technically we can already do that with our bash completions - I would
argue that we don't even need to implement that.

Flattening of shortcuts is resource expansion, then it goes to the mapping
phase to find api groups, which then has the user resolve ambiguity.

**Comment by smarterclayton** [comment]
I think this was resolved.
