### ISSUE TITLE
AWS Feature: Configure idle timeouts on ELBs

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#23485]
We should support annotations to configure some of the more obscure settings on ELBs.

For example, apparently Akamai wants idle timeouts of >300s, and the default is 60s.

We might want to set the default timeout to 300s if that's generally a good thing, but then have an annotation to allow these settings to be tweaked.

If these annotations are generally applicable we should consider making them not-AWS specific, but some of them will be specific to ELB.

**Comment by felixbuenemann** [comment]
This feature is less obscure than you think. For example [DEIS Workflow](https://deis.com/workflow/) requires an idle timeout of 1200 seconds and it keeps resetting to 60 seconds whenever kubernetes updates the ELB, which happens every time a node is added or removed or the pods that are attached to the service change.

**Comment by davidw** [comment]
I know very little about kubernetes, but was digging in the source code, and saw this:

https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/aws/aws.go#L112

Is it relevant?  The name makes it seem like it, and I see it used further on:

https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/aws/aws.go#L2602

**Comment by davidw** [comment]
My colleague points out that https://github.com/kubernetes/kubernetes/pull/30695 may have solved this?

**Comment by felixbuenemann** [comment]
@davidw Thanks, I tested the `service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout` service annotation on k8s v1.4.6 and it worked fine.

**Comment by mirague** [comment]
@davidw Thanks for the find! Just applied this to our `deis-router` service and now we'll see how it goes:
```
kubectl annotate service deis-router -n deis service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout=1200
```

**Comment by felixbuenemann** [comment]
@mirague It's already documented for Deis in [Managing Workflow – Configuring Load Balancers](https://deis.com/docs/workflow/managing-workflow/configuring-load-balancers/)

**Comment by mirague** [comment]
@felixbuenemann Ah they updated the docs, fantastic!

**Comment by jimmycuadra** [comment]
I'm not sure if this is the right issue to bring this up, but I found it by searching for the "error: unexpected EOF" error in relation to running "kubectl logs -f" or "kubectl port-forward". If there is more than 60 seconds of inactivity while one of these long-running operations in inactive, the connection will get dropped because of idle timeout. (This is when connecting to the k8s API server through an ELB, of course.) This doesn't happen with "kubectl proxy", presumably because it is sending or receiving data of some sort even when the proxy is not actively being used by the operator. Increasing the idle timeout on the ELB would just kick the can down the road in the logs/port-forward cases. Would it make more sense to have those commands include some sort of keepalive mechanism?
