### ISSUE TITLE
kubectl apply  leaks secret data

### ISSUE THREAD

**Issue by spheromak** [kubernetes/kubernetes#23564]
when using `kubectl apply` for secrets the annotation will store the secret data, making it visible to `kubectl describe`

**Comment by AdoHe** [comment]
kubectl apply need special handling of secret data. @kubernetes/kubectl

**Comment by bgrant0607** [comment]
I wouldn't use apply with secrets.

**Comment by spheromak** [comment]
@bgrant0607 yes indeed, but it wasn't expected.

**Comment by kargakis** [comment]
> kubectl apply needs special handling of secret data. @kubernetes/kubectl

same thing applies for --record

**Comment by AdoHe** [comment]
so many issues about apply, I will open a new issue to track this and will focus on apply issues. @kubernetes/kubectl @bgrant0607 @kargakis

**Comment by bgrant0607** [comment]
Thanks @AdoHe.

For secret, we could either fail or maybe hash the secret contents in the annotation. We just need to be able to tell which fields changed.

**Comment by bgrant0607** [comment]
See also #20508

**Comment by bgrant0607** [comment]
There's an example and some discussion in #29923, which I closed in favor of this issue.

**Comment by ymqytw** [comment]
AFAIK the sensitive data in annotations(last-applied-configuration created by `apply` and change-cause created by `--record`) that is printed out using `kubectl describe` is considered as a leak.
Are there any other ways that may cause a leak like someone has access to the annotations but doesn't have access to the secret data?
If `describe` printing the annotations is the only leak, then this can be fixed by changing [func describeSecret()](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/describe.go#L1432) only.

**Comment by deads2k** [comment]
> that is printed out using kubectl describe is considered as a leak.
> Are there any other ways that may cause a leak like someone has access to the annotations but doesn't have access to the secret data?

`describe` isn't any more leaky than `get`. You already have access to all the data.  Once the API gives it back to you (remember its in the same object), the information is already exposed.

**Comment by ymqytw** [comment]
cc: @lavalamp

**Comment by AdoHe** [comment]
@ymqytw the things we need to is hash the secret content here, not store the original data.

**Comment by lavalamp** [comment]
I don't consider this an issue. We don't have a security level that's
"observe metadata but not contents". If we did have that level, then this
would be an issue not just for secrets.

**Comment by andronat** [comment]
We already have a special mechanism that translates `stringData` to base64 `data` in secrets. So I don't think is wrong to add some extra checks to ensure `lastAppliedConfig` is also properly formatted.

How about making `kubectl apply` putting `null` in every value of `data` in `lastAppliedConfig`? In this way we will patch all existing fields (even if there are no changes, which I think is fine) and delete the non-existing to keep consistency.

**Comment by smarterclayton** [comment]
Apply needs to be agnostic to the type of object in use.  If you are applying secrets, you are broken anyway.

**Comment by liggitt** [comment]
Agree, secret conversion shouldn't be messing with lastAppliedConfiguration

**Comment by andronat** [comment]
@smarterclayton why applying secrets is broken anyway? We have a use case that we use a custom controller to apply secrets based on a third party object.

**Comment by destijl** [comment]
We just got bitten by this in the GKE UI. We have a configuration section where we display configuration information about kubernetes objects. For secrets we hide the secret data, but not the annotations.

We can filter it out in the UI, but it's just treating the symptoms. Others will likely encounter the same problem at some point. It's very surprising to have your secret data sprinkled around the object in this way.

The stance of "don't use apply" isn't working. We could start by documenting that on the secrets page, but it seems natural to want to use apply if I hold a secret externally and want to push it into k8s in a way where I don't have to pay attention to whether it already exists. Why is this considered "broken"?

/sig auth

**Comment by liggitt** [comment]
> For secrets we hide the secret data, but not the annotations.

Anything given a Secret object and asked to display it, masking confidential data, already has a special-case... I'd recommend switching to a whitelist of "known safe" fields (namespace, name, type). It's making an already-special case slightly more special.

**Comment by liggitt** [comment]
at this point, it's clear we can't consider annotations/labels confidential

**Comment by mradmila** [comment]
Same here. How was this fixed and in what version of K8s?

**Comment by calind** [comment]
I think that this issue should be reopened. Having secret data stored as annotation by the means of `kubectl apply` defeats the purpose of having secrets encrypted at rest.

It is true that there is no distinction between data and metadata when it comes to regular RBAC access. But having data encrypted at rest should protect be from eventual etcd data exfiltration. `kubectl apply` storing that data in clear text in metadata defeats that so that my secrets become not so secret anymore.

cc: @liggitt

**Comment by liggitt** [comment]
The full object (including metadata) is encrypted at rest

**Comment by calind** [comment]
Thanks for clarifying.

**Comment by dims** [comment]
reopened https://github.com/kubernetes/kubernetes/issues/29923 just in case

**Comment by farvour** [comment]
So, the day that Kubernetes decides to actually make get object vs get object metadata a more granular security option, this issue is going to have to be revisited again. I guess I'm curious as to why all of the suggestions about hashing the value when storing it is a non-starter. If the purpose of this data is to detect change, then the original values getting hashed should produce the same checksum/output in theory and there would be no change detected.

I'm lost as to why nobody seems to care about this. It's a relative non-issue today. I'm not sure what k8s roadmap is for splitting up those permissions, but if that day happens.. we're going to be right back in the saddle with this issue.

Can someone enlighten me on why the raw value needs to be present in last-applied-configuration? Let's keep the fact that the secrets are just base64 encoded a separate issue here. I'm aware that it's 'security via obscurity' but in most instances, tools that probe the metadata of an object are more likely to **leak** this kind of information than tools that dump the entire object.. and that's exactly what most people (I think) are complaining about here...

**Comment by juanfresia** [comment]
I've just stumbled into a related issue to this. Turns out that the annotation can leak into metrics if `kube-state-metrics` have all annotations enabled as labels. They would have to be allow-listed [with this parameter](https://github.com/kubernetes/kube-state-metrics/blob/main/docs/developer/cli-arguments.md), but inadvertently using 'secrets=[*]` will cause the leaked secret in the annotations to also show in metrics ([kube_secrets_annotation](https://github.com/kubernetes/kube-state-metrics/blob/main/docs/metrics/storage/secret-metrics.md)).
