### ISSUE TITLE
Installation of Kubernetes-node fails with conflicting packages on CentOs 7

### ISSUE THREAD

**Issue by prashantabkari** [kubernetes/kubernetes#23572]
When i am trying to install kubernetes-node with the following command
# yum install docker kubernetes-node it gives me following error
[abkari@condor network-scripts]$ sudo yum install docker kubernetes-node
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: centos.skarta.net
 * epel: epel.besthosting.ua
 * extras: ftp.crc.dk
 * updates: centos.uib.no
Resolving Dependencies
--> Running transaction check
---> Package docker.x86_64 0:1.8.2-10.el7.centos will be installed
--> Processing Dependency: docker-selinux >= 1.8.2-10.el7.centos for package: docker-1.8.2-10.el7.centos.x86_64
---> Package kubernetes-node.x86_64 0:1.2.0-0.6.alpha1.git8632732.el7 will be installed
--> Processing Dependency: socat for package: kubernetes-node-1.2.0-0.6.alpha1.git8632732.el7.x86_64
--> Running transaction check
---> Package docker-selinux.x86_64 0:1.8.2-10.el7.centos will be installed
---> Package socat.x86_64 0:1.7.2.2-5.el7 will be installed
--> Processing Conflict: docker-engine-selinux-1.10.3-1.el7.centos.noarch conflicts docker-selinux
--> Finished Dependency Resolution
Error: docker-engine-selinux conflicts with docker-selinux-1.8.2-10.el7.centos.x86_64
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

I have uninstalled/removed the docker still the error exists !

**Comment by a-robinson** [comment]
Please re-post your question to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases.

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to similar questions, and also familiarize yourself with:
   * [the user guide](http://kubernetes.io/v1.0/)
   * [the troubleshooting guide](http://kubernetes.io/v1.0/docs/troubleshooting.html)

Again, thanks for using Kubernetes.

The Kubernetes Team

**Comment by prashantabkari** [comment]
Done . you can see the post in the following link
http://stackoverflow.com/questions/36351524/installation-of-kubernetes-node-fails-with-conflicting-packages-on-centos-7
