### ISSUE TITLE
AWS Feature: Integration with IAM

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#23580]
It would be great to be able to configure IAM permissions on a per-pod basis.   We would then have a "mock" metadata service on 169.254.169.254, which would inject the correct IAM roles into the pod (or no roles at all).

I believe this can be implemented using the AWS Security Token Service:
http://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp.html

**Comment by justinsb** [comment]
See also https://github.com/kubernetes/kubernetes/issues/14226

**Comment by guoshimin** [comment]
We here at Databricks is doing something similar to https://github.com/dump247/ec2metaproxy:
- We run a metadata proxy on each node, using DaemonSet
- The proxy uses host network namespace
- We DNAT calls to 169.254.169.254 in the PREROUTING chain to the proxy
- The proxy checks the source IP against the pod list to identify the pod
- Pods that need a role specify that in their annotations
- The proxy calls sts::AssumeRole to get the temporary crendentials for the role and forwards these to the requesting container.
- An authorization plugin enforces policies on what pods can use what roles

As @therc pointed out in [this](https://github.com/kubernetes/kubernetes/issues/14226#issuecomment-184328220) comment, it doesn't work for containers that use net=host, but those containers tend to perform admin functions and tend to be static, so they can use the role associated with the node itself.

**Comment by therc** [comment]
@guoshimin did you say it's written in Scala?

**Comment by guoshimin** [comment]
@therc It is indeed written in Scala.

**Comment by mgoodness** [comment]
Lyft recently released a similar project to ec2metaproxy, called metadataproxy. Announcement [here](https://eng.lyft.com/scoping-aws-iam-roles-to-docker-containers-c9c5f8f2f75#.zh72shmjl). Haven't tried it myself, but might be worth investigating here.

**Comment by quinton-hoole** [comment]
cc @erictune FYI.
Do we need an area/iam label?

**Comment by gtaylor** [comment]
@guoshimin Is your scala implementation specifically for Kubernetes? If so, I don't suppose that it's open source? Keen to see how other people are tackling this in production.

**Comment by thomaso-mirodin** [comment]
@gtaylor Shimin's co-worker here

Ours is specific for kubernetes as it relies on pod annotations to determine the appropriate role. Sadly it isn't open source, however @jtblin did write something very simliar and did open source it (https://github.com/jtblin/kube2iam) :D

Our internal one differs from kube2iam only in automatically running the needed iptables command if it isn't already set and requiring about 10-100x as much memory :P

**Comment by jtblin** [comment]
Author of https://github.com/jtblin/kube2iam, we're using it in our environment for quite some time without issue. We also use a slightly more restricted set of permissions than the example in the README, we only give `sts:AssumeRole` to a specific role instead of `root`. I shall update the README. 

The code is inspired from the original `kube2sky`, using similar APIs.

**Comment by rickypai** [comment]
Question regarding `sts:AssumeRole` and running proxies with DaemonSet:

It seems while we can use trust relationship to limit the number of roles the Kubnernetes workers are allowed to assume, it still means that Kubernetes workers, which runs all applications as Pods, can potentially expose all roles and is a single point of failure.

Instead, would it be possible that, instead of running the proxies with DaemonSet, run them as standalone instances, say `iam-proxy`, and route the Pods' `169.254.169.254` calls to them? This at least prevent containers with privileged access potentially gaining any roles.

**Comment by erictune** [comment]
But a proxy would be single point of failure too.  If it goes down, pods cannot refresh their creds via 169.254.169.254.

**Comment by erictune** [comment]
It depends on whether you want better uptime or better security.

**Comment by rickypai** [comment]
I was thinking running multiple-instances of proxies behind a load balancer to provide redundancy. But at least this way, the proxies' roles are isolated.

**Comment by yissachar** [comment]
Is this planned for 1.4? Trying to decide whether to wait for this to be implemented or just go ahead and use https://github.com/jtblin/kube2iam.

**Comment by erictune** [comment]
Not planned for 1.4.

**Comment by erictune** [comment]
Looks like there are several of these:

1) Lyft
https://github.com/lyft/metadataproxy
https://eng.lyft.com/scoping-aws-iam-roles-to-docker-containers-c9c5f8f2f75#.2svjixfff

2) jtblin (integrates with Kube)
https://github.com/jtblin/kube2iam

3) swipely
https://github.com/swipely/iam-docker

**Comment by rickypai** [comment]
the docker iam proxies all assume the docker networking model of one IP per container. since they use IP to look up the associated containers, they will not work. `kube2iam` by contrast looks through the kubernetes API, so does not have this shortcoming. also, it should support rkt out of the box since it does not have dependency on the docker networking model nor the docker socket.

**Comment by Vlaaaaaaad** [comment]
Any updates on this? What's the preferred way to grant permissions at a pod/container level on AWS?

**Comment by garrickpeterson-wf** [comment]
Also interested in this. When you want this it's one of those cases, to address earlier comments, where security trumps availability (though, couldn't availability be addressed via daemonsets or similar?).
