### ISSUE TITLE
Error from server: dial tcp: lookup xxx on 10.255.255.1:53: no such host

### ISSUE THREAD

**Issue by mysterytree** [kubernetes/kubernetes#23618]
The rc.yaml

![image](https://cloud.githubusercontent.com/assets/6166794/14130694/6a377b7a-f667-11e5-8f1d-eca5bfb17f26.png)

And the logs 

```
root@consul0:/data/k8s# kubectl exec -it chatroom-703e242e43275c569ae1525b244387aa-eekql bash
Error from server: dial tcp: lookup juliette on 10.255.255.1:53: no such host

```
```
root@consul0:/data/k8s# kubectl logs chatroom-703e242e43275c569ae1525b244387aa-eekql
Error from server: Get https://juliette:10250/containerLogs/default/chatroom-703e242e43275c569ae1525b244387aa-eekql/chatroom: dial tcp: lookup juliette on 10.255.255.1:53: no such host
```
apiserver.log

![image](https://cloud.githubusercontent.com/assets/6166794/14130756/d290dce8-f667-11e5-89fa-cac1d15ed53c.png)

The pods  and service run normally .
Only exec or logs pods occur the errors.

**Comment by a-robinson** [comment]
Please re-post your question to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases.

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to similar questions, and also familiarize yourself with:
   * [the user guide](http://kubernetes.io/v1.0/)
   * [the troubleshooting guide](http://kubernetes.io/v1.0/docs/troubleshooting.html)

Again, thanks for using Kubernetes.

The Kubernetes Team

**Comment by gajus** [comment]
For the record, I am getting the same issue on v1.4.0.

```log
[root@earth centos]# kubectl version
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.0", GitCommit:"a16c0a7f71a6f93c7e0f222d961f4675cd97a46b", GitTreeState:"clean", BuildDate:"2016-09-26T18:16:57Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.0", GitCommit:"a16c0a7f71a6f93c7e0f222d961f4675cd97a46b", GitTreeState:"clean", BuildDate:"2016-09-26T18:10:32Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
[root@earth centos]# kubectl get pods -o wide
NAME          READY     STATUS    RESTARTS   AGE       IP          NODE
hello-2h1et   2/2       Running   0          17h       10.40.0.3   moon.localdomain
hello-l1eur   2/2       Running   0          17h       10.40.0.7   moon.localdomain
hello-wm4zn   2/2       Running   0          17h       10.40.0.2   moon.localdomain
l5d-6z567     2/2       Running   0          17h       10.40.0.1   moon.localdomain
l5d-i83v0     2/2       Running   0          17h       10.32.0.3   earth.localdomain
world-alcaw   1/1       Running   0          17h       10.40.0.5   moon.localdomain
world-bwc3g   1/1       Running   0          17h       10.40.0.4   moon.localdomain
world-mctwy   1/1       Running   0          17h       10.40.0.6   moon.localdomain
[root@earth centos]# kubectl exec hello-2h1et date
Error from server: dial tcp: lookup moon.localdomain on 213.186.33.99:53: no such host
```

**Comment by mysterytree** [comment]
@gajus
Edit /etc/hosts 
like： 
```
juliette  xx.x.x.x
```

The problem  sloved

**Comment by bajishaik0073** [comment]
ubuntu@ip-172-31-85-158:~$ kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCom                                                                                                                mit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:                                                                                                                "2018-12-13T10:39:04Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd                                                                                                                64"}
Unable to connect to the server: dial tcp: lookup api.useast1.k8.techbodhi.us on                                                                                                                 172.31.0.2:53: no such host

**Comment by bajishaik0073** [comment]
getting this error

**Comment by ctrombet** [comment]
This error is still present
