### ISSUE TITLE
kube-down on AWS does not remove key-pairs

### ISSUE THREAD

**Issue by erez-rabih** [kubernetes/kubernetes#23622]
Hi,

While issuing a kube-down command all AWS resources are expected to be cleaned, but for some reason the key-pair created by kube-up to establish SSH communication to the nodes/master is not cleaned.

Do we leave it intentionally?

**Comment by justinsb** [comment]
Yes, we do leave this one around.  We use it because (1) there's no charge and (2) it's actually shared across projects (i.e. it is identified by hash, not by cluster).

Not saying this is correct, but that's the explanation :-)

What do you think we should do here?  Name them by cluster (even if then we have two keys named differently that are in fact the same key)?

**Comment by erez-rabih** [comment]
What does the hash function which generates the key-pair name depend on?
What I'm seeing is that every time I create new cluster in a region a new key-pair is generated for it.

Like every other resource kube-app allocates, I believe it should be cluster specific and erased when kube-down is issued so that the cluster leaves no traces in the AWS account.

Of course I might not be aware of all the considerations/implications of this but that's how I see things :)
