### ISSUE TITLE
Creating/Adding nodes on AWS always reports a failure

### ISSUE THREAD

**Issue by erez-rabih** [kubernetes/kubernetes#23623]
When creating a new cluster on AWS with the 1.2 version I always get a failure when checking docker on the nodes, but after the check loop ends everything seems to work fine and all nodes are marked as ready.
```
Sanity checking cluster...
Attempt 1 to check Docker on node @ 52.37.0.9 ...not working yet
Attempt 2 to check Docker on node @ 52.37.0.9 ...not working yet
Attempt 3 to check Docker on node @ 52.37.0.9 ...not working yet
Attempt 4 to check Docker on node @ 52.37.0.9 ...not working yet
Attempt 5 to check Docker on node @ 52.37.0.9 ...not working yet
Attempt 6 to check Docker on node @ 52.37.0.9 ...not working yet
Attempt 7 to check Docker on node @ 52.37.0.9 ...not working yet
Attempt 8 to check Docker on node @ 52.37.0.9 ...not working yet
Attempt 9 to check Docker on node @ 52.37.0.9 ...not working yet
Attempt 10 to check Docker on node @ 52.37.0.9 ...not working yet
Attempt 11 to check Docker on node @ 52.37.0.9 ...not working yet

Your cluster is unlikely to work correctly.
Please run ./cluster/kube-down.sh and re-create the
cluster. (sorry!)
```

The instance types for nodes is m4.large.

**Comment by justinsb** [comment]
That is very surprising.  Are you using any odd settings (to help me try to reproduce the problem)?

**Comment by erez-rabih** [comment]
These are the exports I make before running kube-up:
```
export KUBERNETES_PROVIDER=aws
export MULTIZONE=1
export AWS_REGION=us-west-2
export KUBE_AWS_ZONE=us-west-2a
export MASTER_SIZE=m4.large
export NODE_SIZE=m4.large
export NUM_NODES=6
export AWS_S3_BUCKET=XXXXXXXXXXXX
export NODE_ROOT_DISK_SIZE=100
export KUBE_NODE_IMAGE=XXXXXXXXXX
export KUBE_AWS_INSTANCE_PREFIX=XXXXXXXXX
```

**Comment by paralin** [comment]
The problem is the instances take a very long time to start up. I had to increase the timeout to 19.

**Comment by jlfields** [comment]
Hey @paralin how did you increase the timeout? Didn't see a setting in config-default.sh that I could override. Getting the same issue as the poster.

**Comment by paralin** [comment]
@jlfields 

https://github.com/paralin/kubernetes/commit/9a5571c45b860852a49f90793db7a6702b2ea199#diff-ca69b7d9d3c476654cc9fef6909b1ff0R107

**Comment by jlfields** [comment]
Thanks @paralin , that did the trick!

**Comment by scottstensland** [comment]
On kubernetes v1.4.5 I see same symptom 

 0 minions started; waiting
 0 minions started; waiting
 1 minions started; ready
Waiting for cluster initialization.

  This will continually check to see if the API for kubernetes is reachable.
  This might loop forever if there was some uncaught error during start
  up.

..............................................................................................................................................................................Kubernetes cluster created.
Sanity checking cluster...
Attempt 1 to check Docker on node @ 52.90.156.160 ...not working yet
Attempt 2 to check Docker on node @ 52.90.156.160 ...not working yet
Attempt 3 to check Docker on node @ 52.90.156.160 ...not working yet
Attempt 4 to check Docker on node @ 52.90.156.160 ...not working yet
Attempt 5 to check Docker on node @ 52.90.156.160 ...not working yet
Attempt 6 to check Docker on node @ 52.90.156.160 ...not working yet
Attempt 7 to check Docker on node @ 52.90.156.160 ...not working yet
Attempt 8 to check Docker on node @ 52.90.156.160 ...not working yet
Attempt 9 to check Docker on node @ 52.90.156.160 ...not working yet
Attempt 10 to check Docker on node @ 52.90.156.160 ...not working yet

... I killed it then found root cause was bad permissions on AWS cert files

~/.ssh/kube_aws_rsa
~/.ssh/kube_aws_rsa.pub

those had default umask due to getting manually created
 ... SOLUTION was to lock them down with

cd ~/.ssh/
chmod 600 kube_aws_rsa 
chmod 600 kube_aws_rsa.pub

Would be good to add a check and render fatal if permissions are not so locked down.
Currently it just fails silently with above symptoms
