### ISSUE TITLE
Kubectl expose service should change type on existing services

### ISSUE THREAD

**Issue by a-robinson** [kubernetes/kubernetes#23651]
I created a service of type ClusterIP. I later decide that I want to expose it externally. What's the correct way to do this in a 1.2 cluster, and where is it documented? I found nothing about it in our docs, and the approaches that came to mind first all don't work:

``` shell
# Creating the service without an external load balancer
$ kubectl create -f kubernetes/examples/guestbook/frontend-service.yaml
service "frontend" created
$ kubectl expose svc frontend
Error from server: services "frontend" already exists
# Modify the original config to set `type: LoadBalancer`
$ vim kubernetes/examples/guestbook/frontend-service.yaml
$ kubectl update -f kubernetes/examples/guestbook/frontend-service.yaml
W0330 15:51:21.625806    7556 cmd.go:187] update is DEPRECATED and will be removed in a future version. Use replace instead.
The Service "frontend" is invalid.
spec.clusterIP: Invalid value: "": field is immutable
kubectl replace -f kubernetes/examples/guestbook/frontend-service.yaml
The Service "frontend" is invalid.
spec.clusterIP: Invalid value: "": field is immutable
```

`kubectl expose` doesn't work because it only supports creating new services, not modifying existing services.

`kubectl update` and `kubectl replace` I'm not quite as sure about. The yaml file doesn't specify a `clusterIP` field, so kubectl is filling in the empty value for me. I seem to remember this working on older versions of kubernetes.

I assume you can craft a `kubectl patch` command that would do it, but there's a lot more friction in learning how to use `patch` than in running `update` or `replace`.

I feel silly even needing to ask about this, but it appears to be lacking from our docs.

cc @kubernetes/goog-cluster

**Comment by bprashanth** [comment]
Yeah I don't see why expose on a service shouldn't work. 
Simply updating the service to type=loadbalancer should work (i.e kubectl edit svcname, change type).

**Comment by bprashanth** [comment]
> Yeah I don't see why expose on a service shouldn't work. 

I meant, I know it's meant to expose an RC/deployment etc, but we can make `kubectl expose svc` also work the same way.

**Comment by a-robinson** [comment]
Edit is probably the best current option, assuming that it's expected that update and replace don't work. Maybe document it at http://kubernetes.io/docs/user-guide/services/operations/ ?

`kubectl expose svc` actually works, but you have to pass it a different name for the new service that it creates: http://kubernetes.io/docs/user-guide/kubectl/kubectl_expose/

**Comment by bprashanth** [comment]
> kubectl expose svc actually works, but you have to pass it a different name for the new service that it creates: http://kubernetes.io/docs/user-guide/kubectl/kubectl_expose/

That seems kind of clunky. Maybe there was a reason for it. I'd expect an in place update too.

**Comment by thockin** [comment]
To me, `expose svc` implies creating another service that is the same spec,
which is a little awkward (and useless, and semantically wrong because
clusterIP).  Overloading it to mean "edit in place" doesn't feel right.

The truth is that we can't have a porcelain command for every single thing
a user might want to do.  Porcelain commands should be "saved" for the
things that are common - I am not sure this is.

That said, `kubectl get svc foo | sed 's/ClusterIP/LoadBalancer/' | kubectl
replace -f -` or simply `kubectl edit svc foo` work.  We have a relatively
new `kubectl create` command tree that leaves room for `kubectl create
service` which could be similar in flags to `expose`.  I think of it as
semi-porcelain.  Given this, perhaps a parallel `kubectl change` or
`kubectl patch` or `kubectl apply` tree (or all of the above) makes sense?

kubectl create service foobar --selector="foo=bar" --port=80
kubectl apply service foobar --selector="foo=bar" --port=80 --type=NodePort
 # create-or-replace semantics
kubectl patch service foobar --type=NodePort  # patch semantics

If we want a really slick and consistent CLI, we would implement all three
for all major objects with sufficient flags to avoid ever touching yaml.
That's a lot of work...

**Comment by bprashanth** [comment]
> The truth is that we can't have a porcelain command for every single thing
a user might want to do.  Porcelain commands should be "saved" for the
things that are common - I am not sure this is.

But since we already have "expose svc", and it needs to do something, I'd rather it mean "expose *this* svc" instead of: create another that I now need to be careful to teardown. Is there actually a use case for the latter?

**Comment by bgrant0607** [comment]
Just delete the service and create a new one.

**Comment by a-robinson** [comment]
I don't think we're lacking a solution to exposing an existing service -- `kubectl edit` is a perfectly fine answer, among others.

My opinion (like @bprashanth) is that `kubectl expose svc` creating a new service instead of exposing the referred-to service is a strange choice, but I could easily be missing something that its creator knew. If we're happy with it the way it is, I'm fine closing this.

Is the defaulting of fields like `clusterIP` causing `kubectl replace` to fail tracked somewhere, or considered WAI?

**Comment by thockin** [comment]
I think `expose svc` would be inconsistent and special if it meant anything but what it does.

`replace` is a full replacement and always has been.  As weird as it feels, it doesn't work for Services.  I argued that we should handle it specially, Brian feels differently and I don't feel strongly enough to argue it further.

**Comment by montanaflynn** [comment]
I'm running into this issue where we have our deployment and services defined in a file and use `kubectl replace` as part of automated deployment, the services don't actually change but we would like to keep them in the same file if possible.

```
$ kubectl replace -f deploy.yaml
deployment "some-service" replaced
Error from server: error when replacing "deploy.yaml": Service "one-api" is invalid: spec.clusterIP: Invalid value: "": field is immutable
Error from server: error when replacing "deploy.yaml": Service "two-api" is invalid: spec.clusterIP: Invalid value: "": field is immutable
```

**Comment by thockin** [comment]
@montanaflynn: use `kubectl apply`, instead of `replace`

**Comment by thockin** [comment]
I am closing this old bug
