### ISSUE TITLE
horizontal pod autoscalling and rktnetes

### ISSUE THREAD

**Issue by sjpotter** [kubernetes/kubernetes#23765]
As part of getting rktnetes feature complete I've been focusin on cadivsor to get heapster working for hpa.

It seems to be working, and I can get metrics, but I see a few issues with hpa that I don't know how to solve (or if they are really problems)

1) metrics seem to take too long to show up, so get warnings about not having metrics for nodes - perhaps this is expected

i.e.

```
e2e-tests-horizontal-pod-autoscaling-ch153   2016-04-01 14:10:59 -0700 PDT   2016-04-01 14:12:04 -0700 PDT   8         test-deployment   HorizontalPodAutoscaler             Warning   FailedGetMetrics   {horizontal-pod-autoscaler }   failed to get CPU consumption and request: metrics obtained for 0/5 of pods
e2e-tests-horizontal-pod-autoscaling-ch153   2016-04-01 14:10:59 -0700 PDT   2016-04-01 14:12:04 -0700 PDT   8         test-deployment   HorizontalPodAutoscaler             Warning   FailedComputeReplicas   {horizontal-pod-autoscaler }   failed to get CPU utilization: failed to get CPU consumption and request: metrics obtained for 0/5 of pods
```

2) When things do work, many times (not all) it errors out updating the status

```
e2e-tests-horizontal-pod-autoscaling-ch153   2016-04-01 14:12:33 -0700 PDT   2016-04-01 14:12:33 -0700 PDT   1         test-deployment   HorizontalPodAutoscaler             Warning   FailedUpdateStatus   {horizontal-pod-autoscaler }   Operation cannot be fulfilled on horizontalpodautoscalers.extensions "test-deployment": the object has been modified; please apply your changes to the latest version and try again
```

3) it seems the metrics are off in rktenetes.  for example a test that goes from 1 to 3 to 5 pods might jump directly to 5 pods and test just waits till its 3 pods but never get there.

any help would be appreciated.

**Comment by sjpotter** [comment]
@kubernetes/autoscaling anyone?

**Comment by fgrzadkowski** [comment]
@piosz @mwielgus

**Comment by piosz** [comment]
@sjpotter which version of Heapster do you use? In version 0.18 there was significant latency in collecting metrics. The problem should be fixed in Heapster 1.0 which was bundled in Kubernetes 1.2 release.
Also the warning might happen right after you created RC and HPA since it takes some time to start collecting metrics for newly created pod (~1 minute).

Regarding 2. this looks like deployment feature. @nikhiljindal could you please take a look?

Regarding 3. this is interesting. To debug the problem I'd suggest:
- login into a node on which the pod from e2e test is running and verify how much resources it uses using `docker stats`
- check the values in Heapster:
```
curl "<master>/api/v1/proxy/namespaces/kube-system/services/heapster/api/v1/model/namespaces/<ns>/pods/<pod>/metrics/cpu/usage"
```

Please let me know if you have more problems.

**Comment by dchen1107** [comment]
@sjpotter Have you upgrade the heapster to the latest version for 1.3 release? Based on the information posted above, I think the issue should be either

* cAdvisor integration/compatibility issues with CoreOS / rkt, which are addressed separately already. Or
* heapster issue itself, but it should be generic, and shouldn't have rkt dependency here. 

@sjpotter I am assigning this issue back to you for more integration tests with heapster (new version) and rktnetes for now. Please update with the latest founds, so that we can decide if this is required to be addressed for 1.3 release. cc/ @philips

**Comment by euank** [comment]
I'll grab this issue, want to assign me @yifan-gu ?

**Comment by davidopp** [comment]
Is this a release blocker? If not, let's move it out of 1.3 milestone or downgrade to P2.

**Comment by piosz** [comment]
@davidopp I don't think so. It's not clear for me what the problem is.

**Comment by euank** [comment]
The HPA tests under rktnetes at this point are flaky and the "1 pod to 3 pods and from 3 to 5" is especially unreliable.

There's still a need for investigation and the possibility that something's broken.

I observe usage of 0% even while the test is making "ConsumeCPU" calls, but haven't investigated far enough to know why.

I'll investigate further so we can prioritize properly.

**Comment by yifan-gu** [comment]
So after some experiments, I am suspecting that the problem lives in the kubelet/cadvisor part. Something we could do is printing the metrics from the summary API periodically during the tests.

[Monitoring Architecture](https://docs.google.com/document/d/1HMvhhtV3Xow85iZdowJ7GMsryU6pvjOzruqcJYY9MMI/edit?ts=57b0eec1#heading=h.apg1zrud90oz)

**Comment by euank** [comment]
This is stale; how metrics and HPA will be handled in a CRI world is discussed in other topics, and rkt-specifc work should be tracked in [rktlet](https://github.com/kubernetes-incubator/rktlet/) instead.

/close
