### ISSUE TITLE
document resource usage limits of master components across releases

### ISSUE THREAD

**Issue by jlowdermilk** [kubernetes/kubernetes#23820]
On GKE we noticed with 1.2.0 the memory usage of master components was significantly increased. What is the best way for us to track request/limit resource usage of master components with each release? We need to know expected values to calibrate monitoring so we notice abnormal load spikes.
cc @gmarek

**Comment by wojtek-t** [comment]
@gmarek - since you were measuing it for large clusters, can you please do the same for small clusters?

**Comment by gmarek** [comment]
For GKE I don't really know. For GCE it's easy. We're running gce-scalability on 100 Nodes test with `--gather-resource-usage` flag flipped to true. Since we register master kubelet it gives us data about resource usage for master components. We do not test for regressions for master components, as they were not available when this code was written, and when they did noone updated that. That for continuous testing on GCE.

I don't have a reason to believe that GKE resource usage will be different than GCE one.

@jlowdermilk - is adding thresholds to tests for 100 nodes enough for you? Or do you need more data on different cluster sizes?

**Comment by jlowdermilk** [comment]
Getting the numbers for GCE is sufficient, they will be basically the same for GKE.

Having a test that verifies/reports cpu/mem usage of each master component for 100 nodes and 5 nodes would be ideal.

**Comment by gmarek** [comment]
We have data from Kubemark. To get data from real clusters #25527 is needed.

**Comment by gmarek** [comment]
We started monitoring the usage in test to look for regressions: https://github.com/kubernetes/kubernetes/blob/master/test/e2e/density.go#L53
