### ISSUE TITLE
Federation-testing.md 

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/kubernetes#23884]
We need a map for federation
- what a federated system is
- how to federate a system into the kube build (mesos seems to do this now, is that the current standard)
- where to upload results

cc @kubernetes/sig-testing @spiffxp @ingvagabund

**Comment by jayunit100** [comment]
maybe the work being done on the  munger #602 (which reads results) will be revelant to how federated testing aggregates things.  i believe aaron mentioned this earlier.

**Comment by spiffxp** [comment]
Not making a statement on what has/has-not been done, but these seem to be the high points from sig-testing's meeting notes:

- place existing e2e results into world-readable GCS buckets (per-job), provide convenient links (kubernetes/kubernetes#20161)
- make githubmunger use GCS as source of truth instead of privately-accessible jenkins (kubernetes/contrib#602)
- document the structure/format of the GCS buckets, document the required vs. optional set of artifacts
- provide ability to dry-run munger to audit that a given GCS bucket has the correct data
- provide federated test runner container
  - container as unit of execution instead of e2e.go
  - possible start: kubernetes/contrib#477
- provide way to specify list of gating vs. non-gating buckets
  - ...for PR's?
  - ...for releases? (at present release gating ~= "The Critical Builds" view in google's jenkins)
  - possible start: kubernetes/contrib#467
- ensure dashboards/tools that we pay attention to use GCS as source of truth
  - perf-dash
  - submit-queue
  - kuberentes-test-history
- mumble something about conformance/provider matrix
 - gce
 - gke
 - aws
 - azure

**Comment by travisnewhouse** [comment]
@gmarek Can you share any thoughts about "ability to dry-run munger to audit that a given GCS bucket has the correct data"?  Is this possible today?  Any tips on how to try it?

**Comment by gmarek** [comment]
I *think* I did that... Try
```
./mungegithub --min-pr-number=0 --max-pr-number=0 --once --pr-mungers=submit-queue
```
or ask @eparis

**Comment by eparis** [comment]
You probably don't want `--once`. I also think the queue might not serve a web page if you don't include a github oauth today with `--token-file=`

`./mungegithub --max-pr-number=0 --pr-mungers=submit-queue --token-file=$PATH`

should give you a web page and logs. You might need to up the `--v=` to get some more logs...

**Comment by spxtr** [comment]
You can also tack on `--fake-e2e` and it won't try to talk to Jenkins or GCS, it'll just say the jobs are passing.

**Comment by spiffxp** [comment]
/sig testing

/assign
https://github.com/kubernetes/test-infra#automated-testing and https://github.com/kubernetes/test-infra/blob/master/docs/federated_testing.md have this covered, closing
