### ISSUE TITLE
"kubectl drain" should optionally skip nodes with pods with local data volumes

### ISSUE THREAD

**Issue by davidopp** [kubernetes/kubernetes#23972]
I'm not sure whether the option should default to true or false...

I assume the volumes to match against are HostPath and EmptyDir.

Of course https://github.com/kubernetes/kubernetes/issues/14541#issuecomment-176427996 is relevant again here; these kinds of rules should go in a centralized place eventually.

**Comment by davidopp** [comment]
@mml I marked this for 1.3, so maybe you can interleave this with the why-pending and DisruptionBudget work. Unless I'm totally off base, this should require only a very small change.

**Comment by mml** [comment]
This was off my radar, but I'll pick it up now.  It's an ugly stopgap, but in that regard it will fit in well with its sibling ugly stopgaps, `--force` and `--ignore-daemonsets`.

The simplest thing is to make `--force` also toggle this behavior, but that would change behavior in a potentially surprising way on rollback, so I'll add a new flag `--delete-local-data`, which will default to false.

**Comment by mml** [comment]
A quick note on the defaulting behavior.  Defaulting to false is nice because users get maximum protection from mistakes by default, but if a user relies on the default value, their script will stop giving them that protection on rollback.

Users calling this from another tool who **need** this behavior should be explicit with `--delete-local-data=false`, which will blow up in the event we someday delete the flag or their kubectl binary gets rolled back.
