### ISSUE TITLE
kube-up gives incomplete error message about KUBE_AWS_ZONE

### ISSUE THREAD

**Issue by kgoedecke** [kubernetes/kubernetes#24020]
I was following the getting started with [K8s on AWS guide ](http://kubernetes.io/docs/getting-started-guides/aws/)an ran into a minor issue, which was nevertheless really frustrating.

I set the env variable `KUBE_AWS_ZONE` to `us-west-2`, which is obviously wrong (should be us-west-2a), but I didn't notice in the first place. 

The error message that showed up was the following: 

`Invalid endpoint: https://ec2.us-west-.amazonaws.com`

This didn't really point me in the right direction as the most important part of the endpoint wasn't even displayed (missing the "2"). I don't know if thats an error message bug related to k8s or the aws cli.

**Comment by bgrant0607** [comment]
cc @kubernetes/sig-aws

**Comment by bgrant0607** [comment]
Related: #24420

cc @kubernetes/kubectl

**Comment by justinsb** [comment]
@bgrant0607 do you mean #24420?  Not sure how it's related.

I agree it would be nice to fix this; suggestions on how to do are welcome!  We used to have a better error message because we hard-coded a list of regions -> AMIs, and when the region was not in the list the error was more obvious.  Though actually it was no more obvious than the invalid endpoint message above.

We could hard-code a list of regions, but that's not great.  We could query the list of regions using DescribeRegions.  We could do a regex to make sure the zone matches the current AWS format I guess.  But none of these strike me as great.  This might be one for kube-up v2, practically speaking.

**Comment by kgoedecke** [comment]
@justinsb "We could query the list of regions using DescribeRegions" whats wrong with this approach?

**Comment by justinsb** [comment]
@kgoedecke I guess that calling DescribeRegions and checking is a reasonable option (and `aws ec2 describe-regions` supports both `--region-names` and `--filter`.  So a PR to do that would be welcome!  We just need to remember _not_ to pass the region to it :-)

**Comment by kgoedecke** [comment]
@justinsb I'll see if I can find some time to implement this!
