### ISSUE TITLE
Ingress should check for service type upon creation

### ISSUE THREAD

**Issue by wombat** [kubernetes/kubernetes#24041]
I created an ingress with two backends in gke - the first service was of type `NodePort`, the second one was of type `ClusterIP`.
I spent some time debugging why my path rule didn´t work until I found out that my second service was of type `ClusterIP`. This could be handled more gracefully during creation or at least be visible somewhere.

**Comment by vishh** [comment]
cc @kubernetes/sig-network

**Comment by bprashanth** [comment]
Yeah it should show up in `kubectl describe ing`. 
It shows up in logs, if that's worth anything :)

The reason it's even allowed by the controller (i.e not a hard error thrown by the GCE backend) is so you can setup an Ingress before hand and flip each service to nodeport, and this will just work. 

The reason we don't validate against it is because Type=NodePort is only a stop gap till cloudprovider catch up on containers. It's not required for, eg the nginx ingress controller.

**Comment by w0mbat** [comment]
@bprashanth haha yeah thats true.
Yes, I understand the basic idea behind the way it is working and I like the basic way it is implemented because it gives the user the possibility to add an ingress later on and reuse the service.

I would like to see it checked/validated in the `kubectl describe ing` as you proposed

**Comment by cmluciano** [comment]
/unassign @bprashanth 

@kubernetes/sig-network-feature-requests  Any takers on an owner for this?

**Comment by cmluciano** [comment]
@kubernetes/sig-gcp-feature-requests
