### ISSUE TITLE
PV Acess policy API documentation states that PVs are node scoped

### ISSUE THREAD

**Issue by vishh** [kubernetes/kubernetes#24055]
PVs are Pod scoped right? Why do we talk about nodes in the API documentation.

https://github.com/kubernetes/kubernetes/blob/master/pkg/api/v1/types.go#L466

cc @kubernetes/sig-storage

**Comment by saad-ali** [comment]
> `...to exactly 1 host...to many hosts...` 

That's technically correct--the limitation is on how many nodes a volume can attach to (GCE PD for example can only attach to one node in RW mode).

However, I agree that the API doc should mention pods instead: if a PV is RWO, it should only be used by a single pod at a time, since there is no guarantee that multiple pods will land on the same node.

**Comment by saad-ali** [comment]
CC @kubernetes/sig-storage

**Comment by cjellick** [comment]
@saad-ali I want to make sure I understand correctly.
You are saying that RWO is implemented as limiting how many pods can use a volume, but the reason for it is effectively because the volume can only be mount to a single host (aka node) at a time, right?

And there is no way to say that a PV can be used by many pods as long as they are on the same host, right? 

(I asked this question in slack and @vissh answered and opened this issue, which is why I'm seeking clarification here)

**Comment by swagiaal** [comment]
@cjellick 

> You are saying that RWO is implemented as limiting how many pods can use a volume, but the reason for it is effectively because the volume can only be mount to a single host (aka node) at a time, right?

That is correct yes

> And there is no way to say that a PV can be used by many pods as long as they are on the same host, right?

That is also correct yes. That is it is not possible in RW mode but you can (at least for GCE PD) use a volume read-only in multiple pods. The pod access modes are implemented to reflect the underlying storage restrictions

**Comment by cjellick** [comment]
ok. thanks for clarifying @swagiaal

**Comment by saad-ali** [comment]
Yep, what Sami said.
