### ISSUE TITLE
Kubelet: Do we still need the `Logs` option on docker attach?

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes/kubernetes#24070]
During writing container attach node e2e test, I found this.

Docker attach has an option called `Logs` (see [Docker Remote API](https://docs.docker.com/engine/reference/api/docker_remote_api_v1.22/#attach-to-a-container)).
With this on, before each container attach docker will print the container log first (see [code](https://github.com/docker/docker/blob/5709f8e4227e0e1da333739c44003a3f47279bd5/daemon/attach.go#L77-L106))

The `Logs` option is supported in go-dockerclient (see [code](https://github.com/fsouza/go-dockerclient/blob/master/container.go#L1127)), while it is not supported in engine-api yet (see [code](https://github.com/docker/engine-api/blob/8924d6900370b4c7e7984be5adc61f50a80d7537/types/client.go#L14-L21)).

Before [switching to engine-api](#23506), the `Logs` option is **true** (see [old code](https://github.com/kubernetes/kubernetes/blob/release-1.2/pkg/kubelet/dockertools/manager.go#L1115)). While because engine-api doesn't support it, we don't set it now (see [code](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockertools/kube_docker_client.go#L324-L331))

What is the expected behavior here? If needed, we could send a PR to engine-api to support it.

@ncdc 

/cc @kubernetes/sig-node @kubernetes/rh-ux 

Ref #23563

**Comment by ncdc** [comment]
I don't think this is required. The only issue perhaps would be that maybe you wouldn't see what was already drawn on the screen, but as soon as we get around to implementing terminal resizing (which I'm working on), as soon as you attach, we'll force a screen refresh, so that shouldn't be an issue.

WDYT @smarterclayton

**Comment by Random-Liu** [comment]
@ncdc Good to know that! If that won't affect the user experience, I'll just ignore the `Logs` option for now. :)

**Comment by smarterclayton** [comment]
There appears to be a fairly predictable race condition in attach now (after switching to engine-api) where we sometimes fail to observe all the output from the container.  The engine buffers those streams for us, but it may be that we're not taking into account everything go-dockerclient was doing.  Trying to get a reproducible scenario.

**Comment by Random-Liu** [comment]
@smarterclayton I'll compare with the code of go-dockerclient.

**Comment by smarterclayton** [comment]
@stevekuznetsov was investigating from our end, he had reports of `kubectl run --attach` races prior to engine-api, so there are two races (kubectl run only) or two races (kubectl run + engine-api).

**Comment by ncdc** [comment]
@smarterclayton are you 100% sure that there's a race with engine-api and the attach output? I've seen it with go-dockerclient in OpenShift prior to the most recent rebase, but I haven't looked into engine-api yet.

**Comment by smarterclayton** [comment]
I am not sure.

**Comment by ncdc** [comment]
Picking this back up. We **do** need the logs option when attaching. Because there can be a delay before `kubectl run` sees the pod as `Running`, it is possible for the container to produce output prior to `kubectl run` being attached to the container. In this case, you miss whatever output was produced prior to attaching. We are flaking a ton because of this in OpenShift (openshift/origin#11240). I have opened a PR for docker to add support for sending logs=true when attaching: docker/docker#26718.

**Comment by ncdc** [comment]
Strictly speaking, the kubelet does create + start. The kubectl client does attach, but it has to wait to see the pod running first, which means the kubelet has to see the container running, then update the pod status with the apiserver.

**Comment by Random-Liu** [comment]
@ncdc @smarterclayton Do we still need to print all logs before attach?

It's a little bit tricky for cri-containerd, and I believe also for cri-o, because kubelet manages the log, you don't know how kubelet will rotate it.

/cc @mrunalp

**Comment by ncdc** [comment]
@Random-Liu I think there are a few different use cases at play here:

1) `kubectl run --attach`
  1a) With TTY
  1b) No TTY

2) `kubectl attach`
  2a) With TTY
  2b) No TTY

I would argue that the only place we absolutely must solve the race mentioned above is 1b - `kubectl run --attach --tty=false`. While the other cases would be nice, I don't think they're as critical.

The reason I think 1b is so critical is because you can potentially miss output due to the race described above. With something like `docker run busybox date` it can guarantee that you'll see the output, but we can't always say the same with `kubectl run --image=busybox --restart Never --attach bbox date`. _NOTE_, I just tried to reproduce the race against master, and so far haven't been able to.

For the 2 "with TTY" cases, I don't think need to worry about them, because when you attach to the container, we issue a resize command to get the screen to redraw, so that should cover that.

For the remaining case, attach without TTY, I'd be willing to let it pass. If you `docker attach` to a container without a TTY, it does not show you any prior output and instead only shows you output the occurs post-attach.

**Comment by Random-Liu** [comment]
@ncdc Thanks for your explanation.
So the most important thing is that, we want `kubectl run --attach` to behave similar with `docker run --attach`, but we could not guarantee that because of the known race.

If so, I feel like let attach print out recent logs is just a work around, the real problem is that you could not attach stream as soon as you start a container with current Kubernetes design.

Actually `kubectl log` should cover many use cases in 1b), user could even use `kubectl log` to read, and use `kubectl attach to feed input`. :)

**Comment by ncdc** [comment]
@Random-Liu if `kubectl run --attach` were implemented under the covers as `kubectl log` + `kubectl attach`, there's still a chance that you'd miss output in between when `log` ended and `attach` attached.

The only way I can think of to reliably support 1b with a docker backend is to somehow make the kubelet wait for the `attach` before it starts the container (i.e. create, attach, start), but it would only be allowed to do that in this particular use case (run + attach). I'm not sure if this would also work and be applicable to cri-containerd and cri-o.

**Comment by derekwaynecarr** [comment]
@mrunalp - can you weigh in here for what is possible w/ cri-o?

**Comment by ncdc** [comment]
@sjenning the only one that I think is critical is what I mentioned above - run a pod without a TTY and you want ALL its output. I have to defer to @mrunalp @yujuhong and everyone else in @kubernetes/sig-node-feature-requests @kubernetes/sig-node-bugs to figure out if there's a way to handle this.

My knowledge is still limited to how docker does it:

1. create container
2. attach
3. start container

The only way that I can think of to make that happen with Kubernetes is to add some new field that indicates there will be a client that wants to attach before the container is started by the kubelet. But that presumably throws a pretty big wrench in the entire pod lifecycle.
