### ISSUE TITLE
faild to startup etcd when run shell :service etcd start

### ISSUE THREAD

**Issue by qhj918** [kubernetes/kubernetes#24085]
I ran these command on Ubuntu Server 15.10：
KUBERNETES_PROVIDER=ubuntu ./kube-up.sh
when it ran at reconfDocker.sh  in line of this line : /opt/bin/etcdctl get /coreos.com/network/config,the std show errors like those:
[sudo] password to start master:
Error:  client: etcd cluster is unavailable or misconfigured
error #0: dial tcp 127.0.0.1:4001: getsockopt: connection refused
error #1: dial tcp 127.0.0.1:2379: getsockopt: connection refused

then i found that the etcd stoped:

root@qhjubu:~# service etcd status
● etcd.service - LSB: Start distrubted key/value pair service
   Loaded: loaded (/etc/init.d/etcd)
   Active: active (exited) since Sun 2016-04-10 21:36:55 CST; 13min ago
     Docs: man:systemd-sysv-generator(8)
  Process: 1457 ExecStop=/etc/init.d/etcd stop (code=exited, status=1/FAILURE)
  Process: 1465 ExecStart=/etc/init.d/etcd start (code=exited, status=0/SUCCESS)

Apr 10 21:36:55 qhjubu systemd[1]: Starting LSB: Start distrubted key/value.....
Apr 10 21:36:55 qhjubu etcd[1465]: * Starting Etcd: etcd
Apr 10 21:36:55 qhjubu etcd[1465]: ...done.
Apr 10 21:36:55 qhjubu systemd[1]: Started LSB: Start distrubted key/value ...e.
Apr 10 21:36:55 qhjubu etcd[1473]: error verifying flags, '>>' is not a val...'.
Apr 10 21:37:45 qhjubu systemd[1]: Started LSB: Start distrubted key/value ...e.
Hint: Some lines were ellipsized, use -l to show in full.

**Comment by lavalamp** [comment]
Please re-post your question to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases.

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to similar questions, and also familiarize yourself with:
   * [the user guide](http://kubernetes.io/v1.0/)
   * [the troubleshooting guide](http://kubernetes.io/v1.0/docs/troubleshooting.html)

Again, thanks for using Kubernetes.

The Kubernetes Team
