### ISSUE TITLE
Kubernetes Need A Private Container Registry

### ISSUE THREAD

**Issue by genedna** [kubernetes/kubernetes#24093]
Registry in Kubernetes is still addone’s and optional component at https://github.com/kubernetes/kubernetes/tree/dae5ac482861382e18b1e7b2943b1b7f333c6a2a/cluster/addons/registry, and only support Docker Registry Protocol.  It is certain that multi container runtimes should be fully supported like rkt(https://github.com/coreos/rkt) , Kurma(https://github.com/apcera/kurma), or even runc(https://github.com/opencontainers/runc) in Kubernetes. The addone’s component is already vastly outstripped by multi container runtime and multi image. When we deploy a Kubernetes cluster to run, pulling images from the registry  is the most important thing for developer and administrator. If Kubernetes default has a private container registry which deploy and run with master, everything will be easy.

The private container registry should have functions:
1.    Support multi container registry protocols like Docker Registry V1 & V2, Appc Container  Image Discovery.
2.    Customize the registry protocols between container registry and kubelet, peer to peer even.
3.    Support multi container image format like Docker Image, Appc ACI and converts between them.
4.    Customize container image extends from OCI image spec(https://github.com/opencontainers/image-spec) .
5.    Store container image in mainstream object storage service like Amazon S3, Google Cloud Storage.
6.    Support authentication and authorization for public and private in push action.
7.    Web UI integration with dashboard(https://github.com/kubernetes/dashboard).

Cc @dchen1107 @Random-Liu

**Comment by yujuhong** [comment]
related issues: #19033, #1319

**Comment by dchen1107** [comment]
@genedna Thanks for filing this. @genedna and I had several discussions related to this before. I gave my opinions on this very issue and I will summarize my response below. But I totally understood that my responses doesn't address their problem properly, and suggested him to file the issue so that we can have a wide discussion. 

> 1. Support multi container registry protocols like Docker Registry V1 & V2, Appc Container Image Discovery.
We don't support multi container registry protocols image  out-of-box today. But rktnetes (working in progress) does support both docker and appc images. But rkt will invoke a built-in converter tool to convert docker image to appc image before creating the container.

One proposal raised from the community is that having more than one runtime running a given node. My first reaction is big No here since it introduces the management complexity to node. Instead, I proposed to revisit container runtime interface (https://github.com/kubernetes/kubernetes/issues/22964) to 
* Decouple image_puller from container runtime interface.
* Finalize the image format on disk which should align with oci appc image format. This is a long term project. cc/ @philips

> 1. Customize the registry protocols between container registry and kubelet, peer to peer even.

Once we decoupled image_puller from runtime interface, it should be relatively easy to make image_puller pluggable. In this case, I think Huawei implement your own image_puller as plug-in which allow peer-to-peer pulling. 

> 1. Support multi container image format like Docker Image, Appc ACI and converts between them.

I mentioned above, rkt does convert docker image to aci image. In a long run, we want to standard the image format on disk, so runtime can run any image no matter what type it is, and no matter what kind of repository is. Again, it is long term project, and hope we can get more support from community on this. 

> 1. Customize container image extends from OCI image spec(https://github.com/opencontainers/image-spec) .

Can you clarify what kind of image extends you are asking for? Also I believe this should be proposed to OCI, and it is beyond Kubernetes scope. Of course, we should be looped into the discussion on how to support those extends if they are finalized.

> 1. Store container image in mainstream object storage service like Amazon S3, Google Cloud Storage.

This is simply not feasible from business sense, I guess. We cannot force the user to use mainstream object storage services. This is also one of blocker issues for #19033 to enhance today's private registry addon. But we do provide the instructions on how to use gcs storage backend: https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/registry/gcs/README.md

> 1. Support authentication and authorization for public and private in push action.

In #19033, @freehan listed the detail reason on technical difficulties to achieve this. Meanwhile, he also provide the detail instructions on how to do it in the user's environment:

* Enable TLS for kube-registry: https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/registry/tls/README.md
* Enable authentication: https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/registry/auth/README.md

> 1. Web UI integration with dashboard(https://github.com/kubernetes/dashboard).

No comment on this one. 

cc/ @thockin @bgrant0607 This is the issue I mentioned to you a while back.

**Comment by bgrant0607** [comment]
This seems to be more about supporting other image formats and transports than about running private registries. The former topic is covered by #8702.

**Comment by thockin** [comment]
I don't think Kubernetes is in the business of producing such a registry.
If such software exists, I would have no trouble enabling it as an add-on.
