### ISSUE TITLE
Diagram of Pod states

### ISSUE THREAD

**Issue by wernight** [kubernetes/kubernetes#24130]
I love the diagram on https://github.com/kubernetes/kubernetes/issues/3312 ![](https://camo.githubusercontent.com/5eafb51b611cf5ca6fd681dcfea51335914f1256/68747470733a2f2f7261776769746875622e636f6d2f6c687561726431412f7468726f74746c696e672d73747564792f6d61737465722f646570656e64656e63795f7468726f74746c696e675f66736d2e737667).

Can we have such a diagram on http://kubernetes.io/docs/user-guide/pod-states/ ?

**Comment by thockin** [comment]
This is not strictly correct though, because a pod can cease to be "ready" but not die.  We've intentionally NOT drawn this as a state-machine because conditions are really orthogonal concepts.  We report a singular status as part of kubectl, so maybe we should document THAT, but it's more complicated than this diagram captures.

@dchen1107 @yujuhong since the kubelet drives most of this.

**Comment by wernight** [comment]
Yes it'd be useful. Reason is especially until wait conditions are implemented, it's difficult to wait for example until a pod is "at least" started, or "at least" running (i.e. may be terminated already).

**Comment by bgrant0607** [comment]
There's a bounty on diagrams: https://github.com/kubernetes/kubernetes.github.io/issues/84
