### ISSUE TITLE
Allow user set mode for Secret/ConfigMap

### ISSUE THREAD

**Issue by mqliang** [kubernetes/kubernetes#24199]
I am recently working on adding a SSHVolume, the SSHVolume plugin will inject a ssh key to a specified dir("/home/username/.ssh/authorized_keys"), so that user could login into a container by ssh(if the container has a sshd running)

I am not sure such a SSHVolume is feasible in community. If community folks think such a volume is helpful, I'd like to contribute.

@saad-ali @thockin @pmorie Any thoughts?

**Comment by saad-ali** [comment]
Why is the existing Kubernetes Secret mechanism not be sufficent for this (see http://kubernetes.io/docs/user-guide/secrets/#using-secrets-as-files-from-a-pod)?

**Comment by mqliang** [comment]
Thanks for your pointer. Close this.

**Comment by mqliang** [comment]
@saad-ali 

Using Secrets mechanism to inject ssh key seems have several problems:

* The key of Secrets must be a valid DNS_SUBDOMAIN, which does not support '_', however, it's common that a ssh key file has a file name containing a '_', for example `~/.ssh/github_rsa`

* The mode of ssh key file should be 0600, however, the volume mount in pod using Secrets is 0644

**Comment by saad-ali** [comment]
I'm not a big fan of a proliferation of one-off volumes. Rather, I prefer having a set of volume primitives like secrets, emptydir, etc that can be customized for many uses. Instead of adding a new volume, the solution here might be to make secrets more customizable.

In this case, it may be useful to modify secrets to be able to set mode (https://groups.google.com/forum/#!topic/google-containers/EcaOPq4M758) rather than create a new volume with a minor difference.

For your first point, you can always symlink the mount point from inside your container to whatever path works for you (regardless of the external limitations)

CC @kubernetes/sig-storage

**Comment by thockin** [comment]
There's a PR in progress to add modes (@rata) and a separate PR to allow
more characters in keys.  No need for a custom volume.

**Comment by mqliang** [comment]
@saad-ali 

> In this case, it may be useful to modify secrets to be able to set mode (https://groups.google.com/forum/#!topic/google-containers/EcaOPq4M758) rather than create a new volume with a minor difference.

I agree! Is there anyone work for that? BTW, it seems that ConfigMap could not set mode either.

**Comment by mqliang** [comment]
@thockin fine. Feel free to close this when https://github.com/kubernetes/kubernetes/pull/28936 are merged.

cc/ @ddysher

**Comment by thockin** [comment]
https://github.com/kubernetes/kubernetes/pull/28733

https://github.com/kubernetes/kubernetes/issues/26663

**Comment by rata** [comment]
@mqliang If you have some time, please check the proposal (or implementation too! :)) and see if your use case is addressed. If you have any comment/sugguestion/something, please post in the appropriate issue/PR :)
