### ISSUE TITLE
Missing dev workflow documentation needs to be added/updated

### ISSUE THREAD

**Issue by david-mcmahon** [kubernetes/kubernetes#24228]
There are several bits pointed out in https://github.com/kubernetes/kubernetes/issues/24169#issuecomment-209577684 that are not covered in our development docs (docs/devel):

- [x] The `needs-ok-to-merge` label should be documented probably in [development.md](https://github.com/kubernetes/kubernetes/blob/master/docs/devel/development.md) or [owners.md](https://github.com/kubernetes/kubernetes/blob/master/docs/devel/owners.md)
- [x] Once documented update munger bot message to link back to it
- [x] k8s-bot retest process needs explanation, procedure and permissions documented (#27001)
- [x] A document explaining how contributors can earn privileges to get on the [ok-to-merge whitelist](https://github.com/kubernetes/contrib/blob/master/mungegithub/whitelist.txt).

cc @luxas @roberthbailey @eparis 
ref #24169

**Comment by roberthbailey** [comment]
@bgrant0607

**Comment by bgrant0607** [comment]
https://github.com/kubernetes/kubernetes/blob/master/docs/devel/pr_workflow.png

**Comment by eparis** [comment]
I question if 'ok-to-merge' has any value at all....

**Comment by luxas** [comment]
@eparis I wonder that too. Why did you implement it in the first place?
Not blaming, just wondering

@bgrant0607 Yes, I have seen that image, but it's a bit hidden, and everything isn't covered. (How to get into the list etc.) But it's a very good starting point, and we could make it more visible for new contributors.

As an aside note, I had contributed ~3-4 PRs before I even noticed there was a developer guide (docs/devel). I know it's hard to point it out clearly with Github, but maybe a small initial comment in the PR would make sense?

Also as discussed, the bots should always link to what they are doing and why.

BTW, does the official docs (kubernetes.github.io) at all have a link to the contributing docs? @johndmulhausen

**Comment by bgrant0607** [comment]
@luxas We would welcome help in better organizing developer-focused docs. Perhaps @jbeda, @erictune, and/or others would help also.

We have contributing guidelines:
https://github.com/kubernetes/kubernetes/blob/master/CONTRIBUTING.md

Do you have suggestions for how to improve them?

Or propose a PR template? #21437

**Comment by bgrant0607** [comment]
@goltermann @sarahnovotny

**Comment by eparis** [comment]
@luxas Its hard to say it pre-dates me, since I've been here since the beginning, but I don't know. ok-to-merge just has always been here. I think the idea is to get the reviewer to pay a little bit more attention to things from 'unknown' people. I'm not sure if it is worth it. I think it could probably die right now. But if we ever got OWNERS completed it would really be pointless....

**Comment by goltermann** [comment]
Isn't ok-to-merge our way to override the CLA bot (which occasionally tags stuff cla:no incorrectly)?

**Comment by eparis** [comment]
@goltermann that is `cla: human-approved`

**Comment by bgrant0607** [comment]
cc @david-mcmahon

**Comment by bgrant0607** [comment]
The purpose of ok-to-merge has changed over time. If the sets of people that can apply ok-to-merge and lgtm are the same, I agree it doesn't make much sense.

Another nuisance is that "ok to test" (and the bot request to type that) is a message in the PR, not a label.

We should reconcile the testing whitelist, ok-to-merge, and auto-application of lgtm via OWNERS.

**Comment by bgrant0607** [comment]
needs-ok-to-merge is applied to PRs that aren't from maintainers or collaborators -- it's basically a flag that the PR is from someone new-ish.

**Comment by luxas** [comment]
+1 for `ok-to-test` being a label, but the downside is that only people with write access then may add labels, so it ends up being a bad thing

I think the test check should be there for new committers as a safety check. 
It may be a good thing to have something like `ok-to-merge` to notify the assignee that the user is a non-maintainer, but it really doesn't make sense to have it as a label because of write access only.

Maybe the testing priv could live in `./TESTERS` or something like that? Or it could live in `OWNERS`, but only the top-level file.
Then the bot could query the `kubernetes` org and that file for allowed people. We also may experiment with a thing that an user is automatically allowed to test after submitting `15+` commits to k8s, to reduce PRs that just add people to the list.

When talking about the `lgtm` thing, would it be possible to let the bot add the `lgtm` label if an user in `OWNERS.writeaccess` comments `LGTM`. That would workaround the Github limitations. Could be extended to other labels as well

So I would propose to add a `k8s-labelling-bot` which adds labels based on comments from trusted users that are listed in the `OWNERS` file.
WDYT?

**Comment by bgrant0607** [comment]
cc @hongchaodeng

**Comment by bgrant0607** [comment]
cc @fejta

**Comment by hongchaodeng** [comment]
Re. 'ok to test', I think it's better to let contributor, not reviewer, trigger the test.
Often times, contributors push some code in commit A; Soon they realize something and push more code in commit B.
In current workflow, the jenkins job will run for both commits reply twice.
One solution is to let user trigger the jenkins job when they are ready.
This will also reduce the amount of jobs in Jenkins.

**Comment by davidopp** [comment]
+1 for getting rid of "ok-to-merge" 

Re "ok to test" I think the idea is that we don't want random people executing code on the project's Jenkins. So it's maybe fine to make it a larger group than just maintainers (in which case it shouldn't be a label), but it can't just be anyone.

**Comment by bgrant0607** [comment]
ok-to-merge is gone. What else do we need to do here? @david-mcmahon

**Comment by david-mcmahon** [comment]
Looks like the last item was covered in #27001.  Thank you, @eparis.  
Closing.
