### ISSUE TITLE
Consider reducing the PV/PVC binder provisioner retry time

### ISSUE THREAD

**Issue by saad-ali** [kubernetes/kubernetes#24236]
Consider reducing the PVClaimBinderSyncPeriod from 10 minutes down to something more reasonable, so that volumes don't sit around unbound for half an hour if it fails twice.

This would reduce the impact of issues like https://github.com/kubernetes/kubernetes/issues/21498 until the binder/recycler/provosioner consolidation/refactor is complete.

CC @kubernetes/sig-storage @kubernetes/rh-storage

**Comment by pmorie** [comment]
+100

**Comment by jsafrane** [comment]
@markturansky, do you remember what was the reason for 10 minutes?

**Comment by markturansky** [comment]
@jsafrane  https://github.com/kubernetes/kubernetes/pull/16728

**Comment by jsafrane** [comment]
I checked provisioner and recycler, lowering the sync period should not harm them. Still, it will impact deleter a bit. Now we try to delete a volume three times every sync-period (10 minutes), mostly because if user deletes a pod that uses a volume and deletes also the PVC bound to it, the volume is still attached to the node for some time and all deletion attempts fail. I've seen AWS detach taking around 5 minutes in some cases.

So, if we lower the timer, we should also increase the number of retries. Or have a different retry timer for deletion.
