### ISSUE TITLE
test's RestartAPIServer is docker specific for GCE

### ISSUE THREAD

**Issue by sjpotter** [kubernetes/kubernetes#24305]
```
func RestartApiserver() error {
        // TODO: Make it work for all providers.
        if !ProviderIs("gce", "gke", "aws") {
                return fmt.Errorf("unsupported provider: %s", TestContext.Provider)
        }
        var command string
        if ProviderIs("gce", "gke") {
                command = "sudo docker ps | grep /kube-apiserver | cut -d ' ' -f 1 | xargs sudo docker kill"
        } else {
                command = "sudo /etc/init.d/kube-apiserver restart"
        }
        result, err := SSH(command, GetMasterHost()+":22", TestContext.Provider)
        if err != nil || result.Code != 0 {
                LogSSHResult(result)
                return fmt.Errorf("couldn't restart apiserver: %v", err)
        }
        return nil
}
```

now that I have the master components running within rkt, this fails for rktnetes.

any reccomendations on how to abstract this for rkt?

@yifan-gu @euank

**Comment by yifan-gu** [comment]
@sjpotter We need to:
1. Grep the rkt uuid of the pod
2. systemctl stop/kill k8s_${rkt_uuid}.service

**Comment by sjpotter** [comment]
Yea, we can hack it in, but that wont be anything we can commit, need to figure out how to have the tests differentiate between rkt and docker

**Comment by euank** [comment]
Make a helper for IsContainerRuntime, use the `ContainerRuntimeVersion` from `describe node`, and check the scheme (e.g.g `rkt://` or `docker://` I think).

You can then vary the command appropriately for that node.

That's my guess for an okay way to do this anyways. However, the fact that we have a `ContainerRuntimeVersion` field in `NodeSystemInfo`, and not a `ContainerRuntime` makes me think that it would probably be more elegant to also just add a `ContainerRuntime` field that is simply `rkt` or `docker` (and was probably an oversight when `version` was added since there was only docker anyways), and split on that, though really it's not much of a difference.

**Comment by yifan-gu** [comment]
cc @kubernetes/sig-testing @kubernetes/sig-node for ideas about how to differentiate the runtime during tests.

**Comment by yujuhong** [comment]
> That's my guess for an okay way to do this anyways. However, the fact that we have a ContainerRuntimeVersion field in NodeSystemInfo, and not a ContainerRuntime makes me think that it would probably be more elegant to also just add a ContainerRuntime field that is simply rkt or docker (and was probably an oversight when version was added since there was only docker anyways), and split on that, though really it's not much of a difference.

I'd be ok with differentiating the commands based on the container runtime exposed in node status, at least for now.

**Comment by yifan-gu** [comment]
This test is not being run in the e2e PR suite, so moving to rktnetes 1.1

**Comment by yujuhong** [comment]
@yifan-gu is the requirement for rktnetes 1.1 passing the PR test suite only? Just want to understand the scope because there are quite a few non-PR test suites.

**Comment by euank** [comment]
The most important thing is that it works well for users. Tests are a good approximation of that, but what's more important for 1.0 is resolving real issues users might face. Running `docker kill {pod}` is clearly not a real issue, so I have no problem moving improving this specific testing problem out of scope of 1.0. If it were an issue that would impact users, regardless that it's not part of the e2e suite, we'd want to fix it.

We have focused on the most-run e2e suite (the pr one) because it's the most stable one and, based on it being trusted to gate new changes, I expect it to be the most valuable one. I do wish we had the time/resources to run all the test suites available and fix them to work with rktnetes where the problem lies with them or our code where the problem lies with us.

**Comment by yujuhong** [comment]
There are other ongoing efforts (tracked by newer issues) to ensure tests are portable across runtimes. Closing this.
