### ISSUE TITLE
Updated example to use non-default namespace

### ISSUE THREAD

**Issue by k82cn** [kubernetes/kubernetes#24314]
During the review of #23537, it's better to also update `openshift` and `k8s-pet-store` to use non-default namespace.

cc @eparis .

**Comment by bgrant0607** [comment]
cc @jayunit100

**Comment by k82** [comment]
@bgrant0607 / @jayunit100 , I can continue to work on this one :).

**Comment by k82cn** [comment]
@bgrant0607 / @jayunit100 , can you help to assign this issue to me? So I can trace the tasks in my hand :).

**Comment by bgrant0607** [comment]
@k82cn I'd be happy to assign you once you accept the invitation to the org.

Do you plan to work on this now? If you're not actively working on it, I'd prefer to leave it unassigned.

**Comment by k82cn** [comment]
@bgrant0607 , would you help to send the invitation ?
Yes, I'd like to work on this now, that's a good start for me to learn example & e2e test suite :).

**Comment by bgrant0607** [comment]
@k82cn Already sent. Visit https://github.com/kubernetes to accept.

See https://github.com/blog/1868-inviting-people-to-your-organization

**Comment by k82cn** [comment]
@bgrant0607 , I'm kuber now , thanks. I'm working on this now :).

Checked `openshift` and `k8s-pet-store`, openshift-origin is not using default namespace now; and we can update `k8petstore` 's script to update namespace.

But it seems `storm` and other example are still using default namespace, should we go through all example and update them accordingly?

**Comment by k82cn** [comment]
@bgrant0607 , should I update all ns in one commit or one commit per example?

**Comment by bgrant0607** [comment]
@k82cn In which examples do you plan to make this change?

cc @kubernetes/examples

**Comment by bgrant0607** [comment]
@k82cn Making this change in some examples would be useful, but only if we explain why we're doing it. Additionally, linking to existing docs and blogs about namespaces would be helpful:

http://blog.kubernetes.io/2015/08/using-kubernetes-namespaces-to-manage.html
http://blog.kubernetes.io/2016/08/kubernetes-namespaces-use-cases-insights.html

I don't want to do this in all of the examples, because it does add an extra step, and labels also provide a means of managing a group of related resources within a namespace. 

Perhaps @pwittrock could recommend examples where this would make sense.
