### ISSUE TITLE
provider vsphere dashboard not created

### ISSUE THREAD

**Issue by kgelinas** [kubernetes/kubernetes#24407]
configured with kupe-up.sh
# ~/kubernetes//cluster/vsphere/config-default.sh

...
# Optional: Install Kubernetes UI

ENABLE_CLUSTER_UI="${KUBE_ENABLE_CLUSTER_UI:-true}"
...

$ kubectl get po --namespace=kube-system
NAME                    READY     STATUS             RESTARTS   AGE
kube-dns-v11-9wm87      3/4       CrashLoopBackOff   1507       3d
kube-proxy-10.0.0.112   1/1       Running            0          3d
kube-proxy-10.0.0.113   1/1       Running            0          3d
kube-proxy-10.0.0.114   1/1       Running            0          3d
kube-proxy-10.0.0.115   1/1       Running            0          3d

If I try configuring it manually
$ kubectl create -f cluster/addons/dashboard/dashboard-controller.yaml --namespace=kube-system
replicationcontroller "kubernetes-dashboard-v1.0.1" created
$ kubectl create -f cluster/addons/dashboard/dashboard-service.yaml --namespace=kube-system
service "kubernetes-dashboard" created

 kubectl cluster-info
Kubernetes master is running at https://10.0.0.111
KubeDNS is running at https://10.0.0.111/api/v1/proxy/namespaces/kube-system/services/kube-dns
kubernetes-dashboard is running at https://10.0.0.111/api/v1/proxy/namespaces/kube-system/services/kubernetes-dashboard

curl -L -k -u admin:somepassword https://10.0.0.111/api/v1/proxy/namespaces/kube-system/services/kubernetes-dashboard
Error: 'dial tcp 172.17.0.2:9090: getsockopt: no route to host'

$ kubectl get events --namespace=kube-system

3d          <invalid>   1514      kube-dns-v11-9wm87                  Pod                     spec.containers{kube2sky}               Unhealthy          {kubelet 10.0.0.115}        Liveness probe failed: HTTP probe failed with statuscode: 503
3d          <invalid>   1501      kube-dns-v11-9wm87                  Pod                     spec.containers{kube2sky}               Killing            {kubelet 10.0.0.115}        (events with common reason combined)
<invalid>   <invalid>   1         kubernetes-dashboard-v1.0.1         ReplicationController                                           SuccessfulDelete   {replication-controller }   Deleted pod: kubernetes-dashboard-v1.0.1-2fsix
<invalid>   <invalid>   1         kubernetes-dashboard-v1.0.1-2fsix   Pod                     spec.containers{kubernetes-dashboard}   Killing            {kubelet 10.0.0.114}        Killing container with docker id 3e67166d0c48: Need to kill pod.

I've been trying a few time with all the latest release I've been unable to access the dashboard.

**Comment by hbokh** [comment]
Even with the commit from last night (commit c11229f) to `cluster/vsphere` by @roberthbailey , this error 
```
Error: 'dial tcp 172.17.0.2:9090: no route to host'
Trying to reach: 'http://172.17.0.2:9090/'
```
remains.
I tried today on a fresh install of VMware vSphere ESXi 6.0.0; installed k8s with the standard `KUBERNETES_PROVIDER=vsphere cluster/kube-up.sh` and the script finished with positive results, this time with "kubernetes-dashboard" enabled from the start:
```
Cluster validation succeeded
Done, listing cluster services:

Kubernetes master is running at https://192.168.178.36
KubeDNS is running at https://192.168.178.36/api/v1/proxy/namespaces/kube-system/services/kube-dns
kubernetes-dashboard is running at https://192.168.178.36/api/v1/proxy/namespaces/kube-system/services/kubernetes-dashboard
```
Still unable to connect to the dashboard from my Mac with the now infamous "no route to host"...

**Comment by AlainRoy** [comment]
Hi,

I'm the person who did the fix for the UI not working with the vSphere kube-up implementation. Where do you see the "no route to host" message, exactly? You should be able to connect to the UI by going to the master: https://MASTER-ADDRESS/ui (which redirects to the URL shown when you run kube-up). Do you see that message when you connect there? 

When you ran kube-up, what did you change in the config-default.sh or config-common.sh, if anything? 

When you say "lack of external IP", which external IP are you referring to, exactly? As long as you can connect from your Mac to the IP addresses of the master VM that was created, you should be fine. 

The UI runs in a pod that connects back to the master to make API calls. It looks like it's using the wrong address. It should be the cluster IP address that it's using, which was in the configuration.

**Comment by hbokh** [comment]
Hi Alain and thanks for answering!

When I connect with Firefox to `https://kubernetes-master.internal/ui/` it indeed redirects to `https://kubernetes-master.internal/api/v1/proxy/namespaces/kube-system/services/kubernetes-dashboard/`.
The "no route to host" is displayed in the browser-window on my Mac.
For example, `https://kubernetes-master.internal/healthz/ping` and the Swagger UI are displayed just fine at `https://kubernetes-master.internal/swagger-ui/` (but the last one is having script-issues in Firefox).

`kubernetes-master.internal` is an internal DNS name for IP 192.168.x.y. All 5 kube-systems are within an 192.168.x.y/24 local network. As is the vSphere server.

I have **not made any changes at all** to `config-default.sh` and / or `config-common.sh`. Should I?
I only changed `max_attempt=90` in `util.sh` due to network latency issues.

So an external IP (like using an external load balance / `type=LoadBalance`) is not needed. That is good to know.

Since 172.17.0.2 is an address in the Docker-network, I feel like the issue is somewhere in that part.
On the kubernetes-master I can not even ping 172.17.0.2 or curl the ui / dashboard:

```
root@kubernetes-master:~# curl -L -k -u admin:password https://kubernetes-master.internal/api/v1/proxy/namespaces/kube-system/services/kubernetes-dashboard/
Error: 'dial tcp 172.17.0.2:9090: no route to host'
Trying to reach: 'http://172.17.0.2:9090/'
```

IP-address 172.17.0.2 can only be pinged on the minion ("kubernetes-minion-1") where the dashboard is running as a Docker-container.

**Comment by AlainRoy** [comment]
Cc'ing @imkin the owner of the vSphere kubernetes implementation. I'll be traveling on business for a few days, so I'll be slow to respond until Thursday. I know that may be annoying, sorry. If you don't resolve it by then, I'll try to reproduce it on my return and see what I can do. 

A couple more questions:
* You downloaded the recommended VMDK to use as an image? 
* What version of Kubernetes are you using? I was testing with recent builds from the head of the master branch.

The IP it should be trying to reach should be a 10.x.x.x IP address. (I think it was 10.246.x.x ,not sure.) The fact that it's not is weird. You're right, it should not be a docker network address. 

If you log into the minion that's hosting the UI pod:
* Any error messages in the "docker logs" for the UI container?
* Does "iptables-save" show a bunch of rules for the Kubernetes network?

**Comment by hbokh** [comment]
Followed this guide: http://kubernetes.io/docs/getting-started-guides/vsphere/ with the VMDK from 2016-01-08.
The Kubernetes version is the one from last Friday, v1.2.4.
Take your time, I'll dive into the other stuff tomorrow.

**Comment by AlainRoy** [comment]
As far as I know, the fix above is only in the master branch, not in v1.2.4. I'm not 100% certain (I haven't followed the release process), but I don't see the fix in the release-1.2 branch, and I only contributed it o the master branch. If you're using the 1.2.4 release, I don't think you have the fix to make the UI work.

**Comment by hbokh** [comment]
Yes, you are completely right!
I forgot to mention I use the binary checkout tarball, with the 'cluster/vsphere'-scripts from the master copied over the ones from the tarball.

**Comment by AlainRoy** [comment]
In theory, that should work fine, but the most recent version on master hasn't been tested with Kubernetes 1.2. I don't think it's worth switching to the master branch--it should work.

**Comment by hbokh** [comment]
- _Any error messages in the "docker logs" for the UI container?_
Not on the minion the dashboard is running on as a container.

- _Does "iptables-save" show a bunch of rules for the Kubernetes network?_
Not on the kubernetes-master (only the basic Docker forwarding-chain).
It does on the minion the dashboard is running on as a container.
Will grep them:

```
kube@kubernetes-minion-1:~$ sudo iptables-save | grep dash
-A KUBE-SEP-5EZ7UN25Z3T5IPEC -s 172.17.0.2/32 -m comment --comment "kube-system/kubernetes-dashboard:" -j KUBE-MARK-MASQ
-A KUBE-SEP-5EZ7UN25Z3T5IPEC -p tcp -m comment --comment "kube-system/kubernetes-dashboard:" -m tcp -j DNAT --to-destination 172.17.0.2:9090
-A KUBE-SERVICES ! -s 10.244.0.0/16 -d 10.244.240.121/32 -p tcp -m comment --comment "kube-system/kubernetes-dashboard: cluster IP" -m tcp --dport 80 -j KUBE-MARK-MASQ
-A KUBE-SERVICES -d 10.244.240.121/32 -p tcp -m comment --comment "kube-system/kubernetes-dashboard: cluster IP" -m tcp --dport 80 -j KUBE-SVC-XGLOHA7QRQ3V22RZ
-A KUBE-SVC-XGLOHA7QRQ3V22RZ -m comment --comment "kube-system/kubernetes-dashboard:" -j KUBE-SEP-5EZ7UN25Z3T5IPEC
```

Either way, the `no route to host` is something that seems to happen quite often:
https://github.com/kubernetes/kubernetes/issues?utf8=%E2%9C%93&q=%22no+route+to+host%22
so maybe it's not just related to the dashboard on vSphere only, but something deeper elsewhere?

**Comment by kgelinas** [comment]
also something is wrong
I can't talk to my lan wich is on the 10.0.0.0/24 subnet from the pod.
minions and master everything is working.

will try rebuild everything.

**Comment by imkin** [comment]
@kgelinas What subnet is your pod on?

**Comment by kgelinas** [comment]
all default from config
