### ISSUE TITLE
Provide flags to use etcd3 backed storage

### ISSUE THREAD

**Issue by hongchaodeng** [kubernetes/kubernetes#24405]
ref: #22448

### Description

- We want to have a flag in apiserver to switch to different storage backends. The default should remain as "etcd2", and user can choose a different storage backend e.g. etcd3 by setting the flag.
  - ~~What should the flag look like?~~ We will add a flag "--storage-backend". By default it's "etcd2"; we can set "etcd3" to switch over.
- We need to pass configs specific to etcd3. On top of my head, I think we just need server list (incl. overrides), key prefix. We can reuse [existing flags](https://github.com/kubernetes/kubernetes/blob/a275a045d12b01f8349561190acb8793ec7489bc/cmd/kube-apiserver/app/options/options.go#L204-L205) "etcd-servers", "etcd-servers-overrides", and prefix. ~~One difference to note is that we will use "ip:port" instead of "http://ip:port".~~

### About Config Entry

How could we provide an abstraction to switch between storages?

Currently, user passes config into apiserver via [EtcdConfig](https://github.com/kubernetes/kubernetes/blob/2bf52175f914a600c5472f8cebff56bed6c9e178/pkg/storage/etcd/etcd_helper.go#L67-L76) and set those fields. I'm thinking about to reuse this struct as the entry point -- either add a new field "version" or have different sub-struct like "v2" and "v3". Of course, this is just a shortcut I'm pointing out. I want to collect everyone's thoughts and ideas about how to structure the configuration here better.

**Comment by wojtek-t** [comment]
>
We want to have a flag in apiserver to switch to different storage backends. The default should remain as "etcd2", and user can choose a different storage backend e.g. etcd3 by setting the flag.

In my opinion it should be something like "--storage-backend" with possible values "etcd2", "etcd3" (and potentially in the future other values if/when we support other storage backends).

>
We need to pass configs specific to etcd3. On top of my head, I think we just need server list (incl. overrides), key prefix. We can reuse existing flags "etcd-servers", "etcd-servers-overrides", and prefix. 

+1 for reusing

>
One difference to note is that we will use "ip:port" instead of "http://ip:port".

I think that we should support both format and potentially do some parsing in apiserver to adapt to the expected format.

**Comment by lavalamp** [comment]
Note that we already have the storage override mechanism. Whatever you do should be a natural extension of that. @deads2k is refactoring that code at the moment so you might want to wait for his PR to merge first.

**Comment by timothysc** [comment]
@lavalamp do you have a PR for reference? 

@hongchaodeng I would assume you would only need a single switch to kick a factory on key.  imo, we should mundge all other parameters to be equivalent, so consistency is maintainer.

**Comment by hongchaodeng** [comment]
@timothysc
Are you talking about server list. It wouldn't be hard to keep the same.

**Comment by xiang90** [comment]
@hongchaodeng We can drop the http:// scheme in the lib and hide it from the user.

**Comment by timothysc** [comment]
@hongchaodeng yes.

**Comment by hongchaodeng** [comment]
@lavalamp 
IMO #23208 is orthogonal.
We will parse the flag and other config parameters when calling etcdConfig.NewStorage(), which is transparently done.

**Comment by hongchaodeng** [comment]
Submitted a POC in #24455

**Comment by hongchaodeng** [comment]
closed via #24455
