### ISSUE TITLE
Question: Direction for kube-up on AWS

### ISSUE THREAD

**Issue by tbrox** [kubernetes/kubernetes#24401]
I've been trying to make the cluster deployment scripts work properly for existing VPC's, and I've created a patch that will solve the following issues:
- kube-up can't use existing security groups
- kube-up can't create master without public IP (This prevents the cluster from working on private subnets with a corporate VPN tunnel)

I was going to propose to merge these changes, but the more I think of it the more I'm uncertain whether the current kube-up is the right approach for this. The current deployment scripts are great for setting up new temporary clusters in its own VPC, but has several more issues when it comes to integrating with existing production environments:
- Deployment will in some cases fail when trying to create resources that already exist
- In cases where it is able to use existing resources, it will not check if these resources are actually usable (configured correctly, access rights, etc)
- If deployment fails, you're left with an awful mess to clean up manually.
- kube-down will either not work, or create a disaster for other services (haven't dared testing)
- The deployment scripts seems to provide few or no customization options for things like integrating nodes with a private docker registry. 

On the other hand, setting up a cluster manually seems to make it nearly impossible or at the very least very hard to utilize the AWS cloud-provider, which is required to make the Kubernetes LoadBalancer integrate with ELB. 

Is there a plan for how to go forward with this?

**Comment by paralin** [comment]
@tbrox please discuss this here: https://github.com/kubernetes/kubernetes/issues/23478

**Comment by bgrant0607** [comment]
cc @kubernetes/sig-aws

**Comment by justinsb** [comment]
kube-up is not perfect, but it actually works very well in practice, mostly because of the restriction of installing by default to a new VPC.  kube-down also works very well because it only deletes tagged resources.  Honestly kube-up's biggest problem is probably a PR problem, and I spend a lot more time helping people troubleshoot clusters installed with something other than kube-up than I do where kube-up was used.  We don't have indications on the sizes of the two populations though, so this may be a horrible abuse of statistics ;-)

That said, there are also definitely shortcomings as you have identified, particularly when it comes to trying to do things that don't fit the standard installation, such as integrating with an existing VPC.  paralin is spot-on - issue #23478 is a great place to discuss this as it pertains to these requirements on AWS.   I am not sure that your method of integration with an existing VPC is actually the right way - you will probably want to give k8s its own security groups for example.

But with regard to the future of kube-up, there's also a broader effort, led by @mikedanese to rework salt/kube-up in 1.3 (for GCE as well as AWS):

* the top-level issue for that effort: https://github.com/kubernetes/kubernetes/issues/23174 
* a github repo where we're working: https://github.com/kubernetes/kube-deploy
* also created an issue in that repo with a strawman plan of action: https://github.com/kubernetes/kube-deploy/issues/6
* I have some PRs coming this week (with luck) that will offer a strawman end-to-end replacement for kube-up.

This sort of discussion may be better suited to slack (where we have discussed this a few times in the past few weeks, though slack history is "limited").  If you want to use github issues, I suggest opening a number of highly focused issues is probably more effective.  For example, a lot of people use k8s with private docker registries, myself included.  My preferred method is to use a k8s secret to store the docker credentials, and reference those credentials from the pod.  This approach does not require any support from kube-up.  We can discuss your use-case for doing something different, but just this one example in your issue would fill up an issue all by itself!

**Comment by justinsb** [comment]
For housekeeping, I'm going to close this in favor of the pointers above.  If there are specific issues that slipped through the cracks please do open them!
