### ISSUE TITLE
Fighting controllers should not destabilize apiserver

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#24433]
For example, if you start a deployment for a workload and have a preexisting replicationController using the same selector in the system, the controllers fight and generate enough traffic to cause apiserver to OOM.

Action items:
- Why does apiserver OOM as its failure mode?
- Should we catch & prevent this in admission?
- Should we catch & stop this post-hoc?
- ControllerRef might fix this. @gmarek

**Comment by bgrant0607** [comment]
controllerRef should fix this.

**Comment by bgrant0607** [comment]
Ref #14961, #2210

**Comment by bgrant0607** [comment]
I assume the replica counts of the fighting controllers must have been different.

Re. OOM, my wild guess would be events.

**Comment by wojtek-t** [comment]
Regarding OOM - is it really apiserver OOMing or is it possible that etcd is OOMing?
If this is etcd, I agree those may be events, if this is apiserver, events shouldn't matter.

**Comment by a-robinson** [comment]
The kube-apiserver process was using 12GB of resident memory (according to
top) when I looked at it.

**Comment by wojtek-t** [comment]
This is strange - we are not caching events in apiserver, so it shouldn't be a result of events.

Also, we have QPS limits for controllers currently set to 20, which means that a controller cannot send more than 20 updates per second. That said, if we have two controllers fighting, there shouldn't be more than 40 updates (pod creation/update/deletes) per second, which we should be able to easily handle in apiserver (both in write and read path).

@lavalamp maybe because of some reason those pods are not being deleted properly (e.g. they are changing their state to terminated) and we are accumulating pods in the system? Although that sounds unrealistic.

**Comment by a-robinson** [comment]
Given how easy it should be to reproduce, I suggest we try that rather than
only guessing at the cause :)
On Apr 19, 2016 4:30 AM, "Wojciech Tyczynski" <notifications@github.com>
wrote:

This is strange - we are not caching events in apiserver, so it shouldn't
be a result of events.

Also, we have QPS limits for controllers currently set to 20, which means
that a controller cannot send more than 20 updates per second. That said,
if we have two controllers fighting, there shouldn't be more than 40
updates (pod creation/update/deletes) per second, which we should be able
to easily handle in apiserver (both in write and read path).

@lavalamp <https://github.com/lavalamp> maybe because of some reason those
pods are not being deleted properly (e.g. they are changing their state to
terminated) and we are accumulating pods in the system? Although that
sounds unrealistic.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/24433#issuecomment-211867752>

**Comment by lavalamp** [comment]
It was definitely *not* etcd OOMing. etcd was using 10% of RAM, apiserver was up to 80%+ before it got OOMkilled. Events etcd didn't even register.

**Comment by lavalamp** [comment]
Also, pods were *not* accumulating, there were like 80 pods in the relevant namespace.

**Comment by lavalamp** [comment]
Yes, we should also add an e2e or integration test for this situation.

**Comment by lavalamp** [comment]
> I assume the replica counts of the fighting controllers must have been different.

Not necessarily. I didn't check and it's gone now, but just being off temporally could cause this, too. (both create, both delete, rinse & repeat.)

**Comment by lavalamp** [comment]
In terms of mitigating this before 1.3, the only thing that comes to mind is to make kubectl do a client-side lookup and warn the user when multiple controllers will try to claim the output pods of the thing they're trying to create. I think this is way too much work to be worth it in the short term.

Whatever is causing apiserver to OOM may be worth looking into and fixing in the short term, though.

**Comment by smarterclayton** [comment]
Covered by owner refs.
