### ISSUE TITLE
Unused apiserver param: MasterServiceNamespace

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/kubernetes#24450]
Defined at https://github.com/kubernetes/kubernetes/blob/62fd60565a4bcc9afed79bc5384f1cd54125aa39/cmd/kube-apiserver/app/options/options.go#L70.

Doesnt seem to be used anywhere.

cc @deads2k @smarterclayton Does redhat use it?

Or can we delete it?
cc @kubernetes/sig-api-machinery

**Comment by smarterclayton** [comment]
We put it in to allow folks to to change which namespace we created
"kubernetes" in (and there was corresponding kubelet flag).  Some folks
hardcoded "kubernetes.default" and that's where we are today.

I think we want to move "kubernetes" to "kube-system" (or someplace
similar) as "api" over the long term, but that has migration / back compat
implications.

**Comment by smarterclayton** [comment]
We don't change it today in OpenShift, so the disposition probably rests as
a general "kube ecosystem migration" issues.

The use of "default" is a depressing reminder we should have been more
careful about names :)

**Comment by ncdc** [comment]
We're looking to add a similar flag to the controller manager: https://github.com/kubernetes/kubernetes/pull/20975/files#diff-7a68ae865340a73c760157dcc8f31bc0R152

**Comment by therc** [comment]
1) for backward compatibility, admins could use [ExternalName (CNAME) service](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/service-external-name.md) so that the API servers are reachable from both old and new KubeDNS names
2) speaking of which, an alternative to the whole controller's API health checks and reconciler machinery could be an external load balancer (e.g. a standalone ELB/ALB on AWS, HAProxy on baremetal, etc.), if the admin is so inclined, but then we'd need an option to tell the controller to make the API service an ExternalName one.

My use case: I have code to discover and keep updated a list of all the backends in a given gRPC service, which, in turn, is backed by a Kubernetes service.  To do that, I open a connection to the API server(s) and start a watch on the service's endpoints. I discover the cluster domain, so that
1. the same image can run on different clusters without forcing users to pass an annoying command line flag with the cluster name
1. I can construct the full hostname for the API server, for TLS purposes (in case there's no alternateName for the not-fully-qualified hostname, which many would consider a bad idea anyway)

I also need to be able to handle both the case where high availability is done by the controller manager's reconciler or through an external mechanism (the latter requiring an ExternalName service, of course, since the fullly qualified hostname is under KubeDNS' control).

So my question is: would there be interest in a PR that uses this flag, adds a MasterServiceName, supports the creation of a ExternalName service and helps with the migration to a better name?

**Comment by smarterclayton** [comment]
Eventually we'll need to move things out of the default namespace.  When we
do that, your proposal makes sense to me as the path to move.

1. Create new certs for master that have new name and old name
2. Restart the master with the new master service namespace
(kubernetes.kube-system) or something
3. Create a new external name in default for X period of time
4. Fully deprecate X.
