### ISSUE TITLE
Pod Creation shows Status as Container Creating 

### ISSUE THREAD

**Issue by arjunm183** [kubernetes/kubernetes#24513]
Hello Team,

I would humbly request you to help me with this in reference to the below link which i have already submitted.

https://github.com/kubernetes/kubernetes/issues/24241 

Hello Team,

I am unable to reach find anything in stackoverflow. As per your last update i am able to pull the image from gcr named pause and pushed to my local registry. and now i am getting a new error when creating pod
=======================================
**Command : ** kubectl describe pod <podname>

**Error**

34m 14s 159 {kubelet } Warning FailedSync Error syncing pod, skipping: failed to "StartContainer" for "POD" with RunContainerError: "runContainer: API error (500): No command specified\n"
=======================================
Kubelet logs says as below

Apr 20 04:22:27 <node name> kubelet[21992]: E0420 04:22:27.837469   21992 manager.go:1858] Failed to create pod infra container: RunContainerError; Skipping pod "walk2space_default(16f73d4c-0618-11e6-822d-005056b69c1a)"
Apr 20 04:22:27 <node name> kubelet[21992]: E0420 04:22:27.837514   21992 pod_workers.go:138] Error syncing pod 16f73d4c-0618-11e6-822d-005056b69c1a, skipping: failed to "StartContainer" for "POD" with RunContainerError: "runContainer: API error (500): No command specified\n"

What is this error. I have the image called walk2space in my node as well.but still pod creation status is showing "Container Creating"

zhouhaibing089 and boynux Helped me last time to overcome the issue.
Thanks for helping.

Please help me what should i do now.

**Comment by yujuhong** [comment]
Please post your question to stackoverflow, as suggested in https://github.com/kubernetes/kubernetes/issues/24241#issuecomment-210185736

**Comment by arjunm183** [comment]
Hello Team,

I have fixed the issue by setting the values in --pod-infra-container-image= <privateregistry:5000/imagename:tag in kubelet Args and then the pods started running.

However  Still if i have to move on further i cant keep on updating the arguments with the containers which i am going to run. I would request your help in this case.

Regards,
Arjun.M

**Comment by arjunm183** [comment]
The issue is fixed now. It was actually problem with importing the docker image, because i have to load the image from tar file i did it via docker import , that is the reason it was failing.

Thanks for your support team

**Comment by Mani1313** [comment]
Hello Team,

I am new to kubernetes. I am also facing the same kind of issue.Please help to fix the issue. I have kubernetes cluster with two ubuntu nodes  and tried to install the sample ngnix application using the command 
kubectl run my-nginx --image=nginx --replicas=2 --port=80
The contaniner status keep showing as "ContainerCreating" and the describsion shows as 


"  FirstSeen     LastSeen        Count   From                    SubobjectPath   Type            Reason          Message
  ---------     --------        -----   ----                    -------------   --------        ------          -------
  2m            2m              1       {default-scheduler }                    Normal          Scheduled       Successfully assigned my-nginx-249414  9703-fjfsx to 172.21.11.251
  1m            1m              1       {kubelet 172.21.11.251}                 Warning         FailedSync      Error syncing pod, skipping: failed t  o "StartContainer" for "POD" with ErrImagePull: "image pull failed for gcr.io/google_containers/pause-amd64:3.0, this may be because there are no cre  dentials on this request.  details: (Error response from daemon: {\"message\":\"Get https://gcr.io/v1/_ping: dial tcp 74.125.22.82:443: i/o timeout\"  })"
"
I have pulled the pause-amd64:3.0 and pushed the image and added to private registory and added to kubelet by using the command similar below 
--pod-infra-container-image="your-repo:5000/pause:2.0"

but still I am getting the above error. I tried some other application as well but got same error.
Please help to fix the issue and guide me to run my private docker images in kubernetes.

Expecting your immediate support.

Thanks!
Regards,
Mani

**Comment by arjunm183** [comment]
I am not sure about AWS how it works. Since i work on baremetal and i use NodePort for exposing the service.

**Comment by LiginGeorge** [comment]
Hi ,

Even i am facing similar kind of issue here i am giving some details which i am facing in my environment. Can anyone please help to resolve this issue.

Hi ,
I have installed kubernetes in my local server(single node), but when i am creating create a wordpress container by using below commad  i am getting pod status as below
# kubectl run wordpress --image=tutum/wordpress 

root@indmyskuberm01:~# kubectl get pods
NAME              READY     REASON                                                   RESTARTS   AGE
wordpress-y4zun   0/1       Image: tutum/wordpress is ready, container is creating   0          1h

Please find the error while running # kubectl describe pod wordpress-y4zun commad.


 Fri, 02 Sep 2016 22:10:35 +0530       Fri, 02 Sep 2016 22:10:35 +0530 1       {kubelet 127.0.0.1}     implicitly required container POD       created         Created with docker id 24fad231ce9f9476de723841818cf874889f2e71aea95a12a415517c994ccf16
  Fri, 02 Sep 2016 20:09:13 +0530       Fri, 02 Sep 2016 22:10:35 +0530 729     {kubelet 127.0.0.1}                                             failedSync      Error syncing pod, skipping: API error (400): {"message":"starting container with HostConfig was deprecated since v1.10 and removed in v1.12"}


Please find my docker information:

root@indmyskuberm01:~# docker info
Containers: 22
 Running: 0
 Paused: 0
 Stopped: 22
Images: 4
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 88
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 4.4.0-36-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 12
Total Memory: 7.755 GiB
Name: indmyskuberm01
ID: TDWH:UQSC:T3HZ:D5Q3:5253:IDT2:OINO:WU5E:CZ2K:JPNG:ESPC:AFA5
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8

Please let me know how to comeout from this issue

**Comment by yujuhong** [comment]
@LiginGeorge your question is more suited for the [stackoverflow](stackoverflow.com/tags/kubernetes) forum. Please post there instead. Thanks!
