### ISSUE TITLE
Improve quota replenishment

### ISSUE THREAD

**Issue by deads2k** [kubernetes/kubernetes#24527]
Quota replenishment can be slow and irksome in the case of rejected requests.  One common example: create with a conflicting name.  Quota charges you, but doesn't "uncharge" until it refreshes again.

If we don't need quota to be perfectly, this would be heuristically resolved by registering a time-based recheck on create against a cache of the resource to see if it exists in the store/index based on the reflector.  If you check for that particular resource existing in 500 millliseconds, you'll usually make the correct choice since you're basically talking about etcd latency at that point.  It possible that you'll be wrong, but a user can't force the system in their favor to gain advantage and the reconciliation of the controller will eventually get it right anyway.

In openshift, this would usually be zero cost, since we run core controllers in-process.  In kube, this is non-zero cost (you'd have another cache).  I'd like to see the quota admission plugin updated to at least have this as an option or some other solution that can uncharge on failed creates.  I see this or a RESTHandler post-hook that can never fail (someone will abuse this) as the best options.

@derekwaynecarr @kubernetes/rh-cluster-infra

**Comment by derekwaynecarr** [comment]
I am aware of the conflicting name problem we hit with deployments, we also just have this problem generally when you attempt to create invalid objects that fail validation.  Per our chat, I am in favor of a RESTHandler post-hook to support refunding quota in this case of a POST that failed validation.

The post-hook cannot depend on look-up of a resource by name since name generation happens after the fact, so in general, the hook would need to probably just know did the request fail or not, and know what to refund based on shared state, so we may want to expose `Context` on admission attributes.  I will hack something up.

Also related: https://github.com/kubernetes/kubernetes/pull/20113

**Comment by utkarsh2102** [comment]
Hey,

This hasn't been looked up in ~5 years and has a related PR, which has been closed, too. So I'd be inclined to closing this one. Should you feel differently, please let us know?

/kind feature
/close
