### ISSUE TITLE
When using host network, the pod IP is always empty in downward API

### ISSUE THREAD

**Issue by yifan-gu** [kubernetes/kubernetes#24576]
Turns our that when running a container in host network, its `podStatus *kubecontainer.PodStatus` that is passed to dockertools.SyncPod() will always contain empty IP, as a result, the `PodIP` environment becomes empty.

Maybe we want to use the `apiPodStatus` instead of `podStatus` in this case to [determine the pod IP](https://github.com/kubernetes/kubernetes/blob/v1.3.0-alpha.2/pkg/kubelet/dockertools/manager.go#L1805-L1808) ? Since the apiPodStatus has the valid PodIP, which is [populated by kubelet](https://github.com/kubernetes/kubernetes/blob/v1.3.0-alpha.2/pkg/kubelet/kubelet.go#L3271-L3278) when the container runs in host network.

Or just populate the podIP with hostIP in `dockertools.syncPod` when the container runs on host network.

Ref https://github.com/kubernetes/kubernetes/pull/22666

cc @aaronlevy @kubernetes/sig-node @pmorie

**Comment by Random-Liu** [comment]
Why not just set the apiPodStatus.IP to podStatus.IP before `SyncPod`?

**Comment by yujuhong** [comment]
> Why not just set the apiPodStatus.IP to podStatus.IP before SyncPod?

Do you mean "set the podStatus.IP to  apiPodStatus.IP before SyncPod?"

IMO, we should call [the block to determine the IP](https://github.com/kubernetes/kubernetes/blob/bf69b2a8629b0ba35b5d9986a808477eb069d2a4/pkg/kubelet/kubelet.go#L3290) only once. Why don't we populate set the `kubecontainer.PodStatus.IP` before calling `generateAPIPodStatus`?

**Comment by Random-Liu** [comment]
@yujuhong SGTM

**Comment by pmorie** [comment]
I must admit, I have been thinking about this in the background since @yifan-gu created this issue, and the discussion hasn't added up for me.  I finally sat down and spent some time getting my numerous fixes for podIP via downward API back into my brain, and now the problem seems very obvious to me.

So, after some thought, I believe that for the docker runtime, the problem is that `GetPodStatus`, which is responsible for generating the `kubecontainer.PodStatus` which is used to supply the pod IP, doesn't check to see whether the host network is being used and return the correct IP address if so.  However, `generateAPIPodStatus` _does_, which is why the obvious fix seems to be to use the value from this method.  I think the right thing to do instead is to change the following call stack to correctly determine the IP when the host network is being used.

```
DockerManager.GetPodStatus ->
  DockerManager.inspectContainer ->
    DockerManager.determineContainerIP
```

@Random-Liu @yifan-gu @yujuhong

**Comment by yifan-gu** [comment]
@pmorie Today `GetPodStatus` doesn't pass the pod spec, so it cannot know if the pod is running on host. This could be solved if we serialize the pod spec into docker labels.

BTW, I think we have a similar issue here for rkt.

**Comment by Random-Liu** [comment]
@pmorie As @yifan-gu said, GetPodStatus doesn't have full pod spec today. And I don't think docker manager has knowledge about the host ip now.

**Comment by pmorie** [comment]
@Random-Liu @yifan-gu I think we should think about adding the plbuming.  I have **not** had a good experience storingthis information in multiple places :)

**Comment by yujuhong** [comment]
The code was written so that it'd work in the absence of the pod specs (which we don't always have).

> @Random-Liu @yifan-gu I think we should think about adding the plbuming. I have not had a good experience storingthis information in multiple places :)

I agree with you, but adding the dependency today without some form of checkpointing (e.g., container annotations) of the pod specs may be problematic now. We can revisit this after we store pod specs in the annotations. What do you think? :)

**Comment by pmorie** [comment]
I'm cool with revisiting @yujuhong but if we do that we should drop this to p2

**Comment by yifan-gu** [comment]
Reopen the issue to capture https://github.com/kubernetes/kubernetes/pull/24633#issuecomment-219502831

**Comment by xiang90** [comment]
@yifan-gu Is this fixed?

**Comment by bassam** [comment]
hi, also interested in knowing if this is fixed.

**Comment by yifan-gu** [comment]
@bassam @xiang90 I don't think anyone is tacking on this one right now since people are mostly working on the new CRI implementation for different runtimes. cc @Random-Liu @yujuhong

**Comment by bassam** [comment]
@yifan-gu thanks. it also looks like there might be a specific issue with rkt here. Looking at https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/rkt/rkt.go#L804 and 
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/rkt/rkt.go#L1304, it looks like rkt does not handle the case of status.PodIP when using the host network.

**Comment by yifan-gu** [comment]
@bassam Thanks for the heads up. I will take a look to see if we can quickly work around this.
