### ISSUE TITLE
Unable to connect to the server: x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by joaoandremartins** [kubernetes/kubernetes#24586]
Trying to do anyting with kubectl (e.g., kubectl get po, kubectl create -f service.yaml, etc.) results in the same:

$ kubectl create -f service.yaml 
Unable to connect to the server: x509: certificate signed by unknown authority

This is from Google's internal network.

What certificate is it talking about? Where is it getting it from? I never installed any certificate or was asked for one.

gcloud components update is up to date.

**Comment by bgrant0607** [comment]
Please re-post your question to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases.

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to similar questions, and also take a look at documentation on http://kubernetes.io/.

Again, thanks for using Kubernetes.

The Kubernetes Team
