### ISSUE TITLE
Make it easy to run Kubernetes on top of the Kubelet (aka self-hosting)

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#246]
Pulling this out from #167

> I'd love to start using the kubelet in a more "static" mode to handle the master containers. That would consist of getting the kubelet running on the master (with out looking an etcd) and then have it run a pod for the master components by reading out of a manifest file on disk.

Something I'd be happy to work on

**Comment by saad-ali** [comment]
CC: @saad-ali

**Comment by vipulnayyar** [comment]
Hello everyone, 

I would like to work on this project during GSoC '15. I've gone through setting up the base dev environment and starting a local cluster. I'm going through the kubelet and apiserver code right now.

Which of the future points suggested by @bgrant0607 and others do you think are critical and should be pursued for this project? The bootstrapping part definitely seems interesting, but there are a lot of suggestions related to kubelet present in the whole issue queue. I'm assuming the bootstrapping process has a lot to do with other components apart from kubelet too.

And how should I proceed in order to contribute to the component dockerization work done until now by @jbeda? I mean, what parts have been covered and where should I focus now so as to further his work through this project?

**Comment by bgrant0607** [comment]
@vipulnayyar Thanks for your interest! Early next week I plan to flesh out more of the details of projects that GSoC candidates express interest in. I'll update this issue. 

My current thinking is that this project would focus on running the master components (apiserver, controller-manager, etc.) in pods. A necessary first step is to properly containerize them. We have made previous attempts at that, but didn't push them through to completion, for various reasons.

**Comment by vipulnayyar** [comment]
@bgrant0607 Related to this topic, based on my past experience as a GSoC student, you also need to figure out the application template that students need to follow while submitting their GSoC application for Kubernetes.

**Comment by bgrant0607** [comment]
I created a wiki re. participation: https://github.com/GoogleCloudPlatform/kubernetes/wiki/Google-Summer-of-Code-(GSoC)

GSoC project ideas are labeled kind/gsoc:
https://github.com/GoogleCloudPlatform/kubernetes/labels/kind%2Fgsoc

"Starter project" ideas are labeled help-wanted (note that not all are necessarily small/easy):
https://github.com/GoogleCloudPlatform/kubernetes/labels/status%2Fhelp-wanted

Bootstrapping-related issues are labeled in an obvious way:
https://github.com/GoogleCloudPlatform/kubernetes/labels/area%2Fbootstrapping

Work has started to run etcd in a container/pod (#4442). The apiserver, controller-manager, and scheduler also need to be handled. Pushing pod files via Salt is a reasonable starting point, but I'd love to be able to post the pods to Kubelet and then have the apiserver automatically pick them up (this latter bit is ongoing -- #4090).

Being able to run master components with high availability (#473) is related -- I think self-hosting them is essentially a prerequisite. 

Self-hosting Kubelet is almost an entirely separate project.

**Comment by bgrant0607** [comment]
See also #5011.

Sorry, @vipulnayyar. Someone has started working on this one, so I'm going to remove it from the GSoC list.

**Comment by bgrant0607** [comment]
More specifics, as background for #11908. 

I want to self-host the control-plane components on Kubernetes, at least in [HA configurations](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/proposals/high-availability.md), but I don't want to preclude running them outside the cluster or as static pods. The latter two would be non-bootstrapped configurations. It also needs to be possible to host Kubernetes control-plane components in another Kubernetes cluster.

Another benefit, in addition to those mentioned above, is that it would reduce the resource cost of the control plane.

When running on Kubernetes, each component and add-on will have a Service and a Deployment (#1743). The Service will generate Endpoints, whose controller will keep the list of addresses and ports up to date. Kubelet will perform liveness and readiness probes. Readiness probe failure currently removes pods from Endpoints. Deployment is needed in order to orchestrate updates and to obsolete the on-master add-on controller. 

To bootstrap, we'd start a minimal number of components on one host via Kubelet: apiserver, etcd, scheduler, controller manager, skydns/kube2sky. Since the components wouldn't be bound to specific VMs, they would not use host networking. The images would typically be official releases pulled from a public registry, such as gcr.io. Use of a private registry would be typical for development and/or customized clusters. That would just add the registry to the list of components that would need to be started. How to include a network storage system running in the cluster for use by these components should be possible, but I'm not going to describe that here.

So how would components [find each other](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/design/clustering.md)?

Most components, such as controller-manager and the scheduler, are simply clients of apiserver. They can find apiserver via its Service, either using DNS or, such as in the case of kube2sky, service environment variables. These components could then get their configurations via the configuration API (#1553). (If/when the DNS resolver moves to the nodes, then it can be treated similarly to kube-proxy.)

That reduces the problem to how kube-proxy and kubelet find apiserver, how apiserver finds etcd, and how the etcd instances find their peers. It would be simplest if we could always assume the existence of an external discovery/rendezvous mechanism (e.g., anycast, portable routable VIPs, private DNS, rendezvous service), which is how [etcd achieves dynamic discovery](https://github.com/coreos/etcd/blob/master/Documentation/clustering.md#discovery), but I'm concerned making that a hard requirement would further complicate porting Kubernetes to other platforms, especially ones lacking access to public discovery services and lacking suitable mechanisms of their own. Note that running a discovery service, such as etcd or consul, on fixed VMs doesn't solve the problem, since if the hosts permanently fail, the failed instances need to be moved and we'd need a mechanism to update all clients, unless we had a dynamic discovery mechanism, in which case we wouldn't need the additional service -- the turtles have to stop somewhere. Also, we could put etcd into the same pod as apiserver, but localhost couldn't be used to find etcd in the case of an HA configuration, which is the scenario we're discussing.

There's more to this obviously, but I wanted to post what I wrote so far.

TODO:
* How to set cluster, public IPs for apiserver
* Address what to do about the [magic kubernetes service](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/master/controller.go)
* [etcd membership update](https://github.com/coreos/etcd/blob/master/Documentation/runtime-configuration.md)
* Bootstrapping credentials
* Endpoints extensions
* Health-checking external components, including components running in another Kubernetes cluster
* Component updates

**Comment by smarterclayton** [comment]
We experimented and explored having kube-proxy function as a client of the
apiserver which could also look at a "bootstrap" server URL or a list of
URLs - it would start by trying the bootstrap URL, then cache the endpoints
for the "kubernetes" service and use those for direct access.  If the
endpoints failed it would fall back to the bootstrap.  The bootstrap is the
hard problem (it has to be some stable URL that can redirect to the master
or resolve to the master).  Other clients on the node would use the service
proxy and thus only one component has to be aware of the master.  It's only
truly useful if it works in all environments as you note, so it either has
to be a simple public service with registration (security concerns) or DNS
(setup / access concerns in the enterprise).  We could not find a one size
fits all solution.

The other path we explored was using a single "bootstrap master" that ran a
particular set of nodes - however, in practice you just introduce a SPOF
for the bootstrap master unless you build in additional resiliency (such as
letting the nodes talk to multiple masters).  Not a clear win because of
that concentration of failure domains, although interesting in some cases.

On Tue, Aug 4, 2015 at 2:16 AM, Brian Grant <notifications@github.com>
wrote:

> More specifics, as background for #11908
> <https://github.com/GoogleCloudPlatform/kubernetes/issues/11908>.
>
> I want to self-host the control-plane components on Kubernetes, at least
> in HA configurations
> <https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/proposals/high-availability.md>,
> but I don't want to preclude running them outside the cluster or as static
> pods. The latter two would be non-bootstrapped configurations. It also
> needs to be possible to host Kubernetes control-plane components in another
> Kubernetes cluster.
>
> Another benefit, in addition to those mentioned above, is that it would
> reduce the resource cost of the control plane.
>
> When running on Kubernetes, each component and add-on will have a Service
> and a Deployment (#1743
> <https://github.com/GoogleCloudPlatform/kubernetes/issues/1743>). The
> Service will generate Endpoints, whose controller will keep the list of
> addresses and ports up to date. Kubelet will perform liveness and readiness
> probes. Readiness probe failure currently removes pods from Endpoints.
> Deployment is needed in order to orchestrate updates and to obsolete the
> on-master add-on controller.
>
> To bootstrap, we'd start a minimal number of components on one host via
> Kubelet: apiserver, etcd, scheduler, controller manager, skydns/kube2sky.
> Since the components wouldn't be bound to specific VMs, they would not use
> host networking. The images would typically be official releases pulled
> from a public registry, such as gcr.io. Use of a private registry would
> be typical for development and/or customized clusters. That would just add
> the registry to the list of components that would need to be started. How
> to include a network storage system running in the cluster for use by these
> components should be possible, but I'm not going to describe that here.
>
> So how would components find each other
> <https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/design/clustering.md>
> ?
>
> Most components, such as controller-manager and the scheduler, are simply
> clients of apiserver. They can find apiserver via its Service, either using
> DNS or, such as in the case of kube2sky, service environment variables.
> These components could then get their configurations via the configuration
> API (#1553 <https://github.com/GoogleCloudPlatform/kubernetes/issues/1553>).
> (If/when the DNS resolver moves to the nodes, then it can be treated
> similarly to kube-proxy.)
>
> That reduces the problem to how kube-proxy and kubelet find apiserver, how
> apiserver finds etcd, and how the etcd instances find their peers. It would
> be simplest if we could always assume the existence of an external
> discovery/rendezvous mechanism (e.g., anycast, portable routable VIPs,
> private DNS, rendezvous service), which is how etcd achieves dynamic
> discovery
> <https://github.com/coreos/etcd/blob/master/Documentation/clustering.md#discovery>,
> but I'm concerned making that a hard requirement would further complicate
> porting Kubernetes to other platforms, especially ones lacking access to
> public discovery services and lacking suitable mechanisms of their own.
> Note that running a discovery service, such as etcd or consul, on fixed VMs
> doesn't solve the problem, since if the hosts permanently fail, the failed
> instances need to be moved and we'd need a mechanism to update all clients,
> unless we had a dynamic discovery mechanism, in which case we wouldn't need
> ! the addit ional service -- the turtles have to stop somewhere. Also, we
> could put etcd into the same pod as apiserver, but localhost couldn't be
> used to find etcd in the case of an HA configuration, which is the scenario
> we're discussing.
>
> There's more to this obviously, but I wanted to post what I wrote so far.
>
> TODO:
>
>    - How to set cluster, public IPs for apiserver
>    - Address what to do about the magic kubernetes service
>    <https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/master/controller.go>
>    - etcd membership update
>    <https://github.com/coreos/etcd/blob/master/Documentation/runtime-configuration.md>
>    - Bootstrapping credentials
>    - Endpoints extensions
>    - Health-checking external components, including components running in
>    another Kubernetes cluster
>    - Component updates
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleCloudPlatform/kubernetes/issues/246#issuecomment-127491326>
> .
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by bgrant0607** [comment]
An alternate to a bootstrap URL could be a local pre-initialized cache of bootstrap data, which would be overwritten once the kube-proxy was able to talk to the apiserver.

**Comment by smarterclayton** [comment]
Yeah, would be more composable.

On Wed, Aug 12, 2015 at 12:49 AM, Brian Grant <notifications@github.com>
wrote:

> An alternate to a bootstrap URL could be a local pre-initialized cache of
> bootstrap data, which would be overwritten once the kube-proxy was able to
> talk to the apiserver.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleCloudPlatform/kubernetes/issues/246#issuecomment-130159715>
> .
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by philips** [comment]
I feel like the primary task is largely done and then some. Here is the current status of self-hosted and bootkube thread: https://groups.google.com/d/msg/kubernetes-sig-cluster-lifecycle/p9QFxw-7NKE/jeYJF1hBAwAJ

**Comment by kargakis** [comment]
cc: @kubernetes/sig-cluster-lifecycle-misc

**Comment by luxas** [comment]
@timothysc has been working on the bootstrapping checkpointing feature for the node to make this work easily with upstream k8s. Also kubeadm has self-hosting support (alpha in v1.9 but expected to be beta in v1.10)
/assign @timothysc

**Comment by timothysc** [comment]
Given the plethora of incantations that exist today, I'm going to close this root issue b/c it no longer tracks the details.  We are working in sig-cluster-lifecycle to refine this on our road to GA and this issue no longer tracks state so closing.
