### ISSUE TITLE
Automate and/or create an interface for spinning up jenkins jobs for a new branch

### ISSUE THREAD

**Issue by david-mcmahon** [kubernetes/kubernetes#24639]
At the time a new branch is created, [new jenkins jobs need to be spun up](https://github.com/kubernetes/kubernetes/blob/master/docs/devel/releasing.md#manual-tasks-for-new-release-series).  See also #20946.

This is currently a labor-intensive process that requires much specialized knowledge of the current state of jenkins and jenkins in general.   Ideally this can be distilled to a simple interface (config/button/whatever) that can be updated at some point so that the release tooling can easily trigger it when a new branch is created.  Like adding the new branch to a config file.

@ihmccreery had a good idea in a meeting recently that the current master "set" is simply copied to create the new branch (in the same way the code is branched from master), rather than trying to set something up new. 

cc @spxtr @ixdy @fejta

**Comment by ihmccreery** [comment]
A couple of notes:

- Another option is to pin all jobs to a minor version, meaning that when a minor release is branched, all the CI jobs that were pointing at master move over to that branch.
  - This is nice because it means that master lags more than release branches, which is good for helping us get things out the door.  The downside is that having no testing on master ever seems like a bad idea, as a lot of our dev infra would fall over.  This also would take some (not much) engineering work to change.
  - We also run plenty of jobs on master that we wouldn't want on a given release branch (e.g. experimental features).
- "simply copying" the current jobs to the new branch is also not quite so easy.
  - Every job needs a new GCP project to be spun up, so it's not quite automatable yet (though I recently wrote a script to do exactly this).
  - This also suffers from the problem above that we don't actually want all master jobs running on release branches.

**Comment by ixdy** [comment]
@pwittrock want to add any comments given your recent experience?

**Comment by spiffxp** [comment]
/remove-area test
/remove-lifecycle stale
/remove-priority backlog
/priority important-soon
@krzyzacy @BenTheElder is there a better (k/test-infra?) issue to use for "make it easier to spin up release branch CI" ? I know this issue title has "jenkins" in the name, but the concept of just stamping out a new set up jobs still holds for prow I think

**Comment by BenTheElder** [comment]
I don't think so, we are planning to look at redesigning the prow config though so this might fall under that. 

Right now you probably *could* just automate copying all jobs over from the master branch, but I don't think that this alone is actually correct. We want to adjust things like the job names and the interval of periodic jobs and...

IMHO this is probably best solved by:
- making configuration of jobs clearer and simpler
- documentation

**Comment by krzyzacy** [comment]
We are trying to follow stable-x pattern, which means there's no need to delete/recreate jobs upon cutting a new branch, I'll close this
