### ISSUE TITLE
Docker multinode startup issue

### ISSUE THREAD

**Issue by mnowrot** [kubernetes/kubernetes#24654]
I'm trying to follow instructions given here http://kubernetes.io/docs/getting-started-guides/docker-multinode/master/ to start the master node on Debian 8 Jessie. However, after running a command that should start the master node:
```
docker run \
    --volume=/:/rootfs:ro \
    --volume=/sys:/sys:ro \
    --volume=/var/lib/docker/:/var/lib/docker:rw \
    --volume=/var/lib/kubelet/:/var/lib/kubelet:rw \
    --volume=/var/run:/var/run:rw \
    --net=host \
    --privileged=true \
    --pid=host \
    -d \
    gcr.io/google_containers/hyperkube-amd64:v1.2.2 \
    /hyperkube kubelet \
        --allow-privileged=true \
        --api-servers=http://localhost:8080 \
        --v=2 \
        --address=0.0.0.0 \
        --enable-server \
        --hostname-override=127.0.0.1 \
        --config=/etc/kubernetes/manifests-multi \
        --containerized
```
I'm receiving the following output:
```
89accdf805aa401d2a94e2f5e13d152f27756a3387ebba3251201175cc4b8418
docker: Error response from daemon: Container command '/hyperkube' not found or does not exist..
```
I'm using docker 1.11.0 Could anyone help me out here? I'm happy to provide further information if necessary.

**Comment by pwittrock** [comment]
#24114

**Comment by luxas** [comment]
I haven't come across this earlier, but haven't tried `docker-1.11` out either

**Comment by koubas** [comment]
Same experience with 1.11.0, downgrade to 1.10.3 fixed that

**Comment by astrolox** [comment]
Based on my own experience; I think this problem is caused by the two docker daemons running on the same host and using the same docker-containerd daemon which docker runs automatically now. The solution is to use the --exec-root option on the bootstrap docker daemon, so that it's containerd pipe can't be found by the main docker daemon.

**Comment by Mangirdaz** [comment]
@mnowrot any luck with this one?

**Comment by mnowrot** [comment]
Not really - I decided to run Kubernetes on Ubuntu and completely dropped this way of running Kubernetes.

**Comment by Mangirdaz** [comment]
I'm facing same issue on ARM on Raspberry PI. So not much way to back :D

**Comment by pwittrock** [comment]
@mikedanese Will the cluster setup work being done address this by providing a replacement?

**Comment by luxas** [comment]
The problem is not with kube-deploy itself, it's just that the "old" docker-multinode that was written a long time ago was copied over to kubernetes.github.io, while the current docker-multinode solution is developed in kube-deploy.

See: https://github.com/kubernetes/kubernetes.github.io/pull/876

(But hopefully, we'll soon get to a point where we have 3-5 core deployments, not ~20s of them like today)
