### ISSUE TITLE
Write an example using interemediate certs and Ingress

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#24669]
This causes more confusion than it should.
https://gist.github.com/bprashanth/176c76b8f713a1e88bfcff532fd1a5da

It's easy to mess up. The GCE L7 won't accept anything other than RSA-2048 and ECDSA P-256, and the cert will get rejected unless ordered as:

```
-----BEGIN MY CERTIFICATE-----
-----END MY CERTIFICATE-----
-----BEGIN INTERMEDIATE CERTIFICATE-----
-----END INTERMEDIATE CERTIFICATE-----
-----BEGIN INTERMEDIATE CERTIFICATE-----
-----END INTERMEDIATE CERTIFICATE-----
-----BEGIN ROOT CERTIFICATE-----
-----END ROOT CERTIFICATE-----
```

Additionally we should tell people how to check for the validity of the chain (https://github.com/kubernetes/kubernetes/issues/20176 should do that automatically), some loadbalancers will do that for you, cloud lbs won't.

**Comment by mpj** [comment]
A proper writeup of this would be grand. Setting up an ingress with an SSL certificate has been one of the most difficult things I've ever done, and it was JUST because of lack of a good example.

**Comment by bprashanth** [comment]
@mpj did you try: https://github.com/kubernetes/contrib/tree/master/ingress/controllers/gce#redirecting-http-to-https by any chance? please recommend how/where you landed and what tripped you

**Comment by nerdyglasses** [comment]
I have just done all this and it almost works for me. But it seems like the bundle isn't 100% working.
I know that android has problems with SSL when the chain isn't present. I am using a PostiveSSL which has one certificate, 2 intermediate and one root certificates like described above.

GCE now accepts my certificate but android is still causing issues.
I have searched almost every place for a solution. This github issue seems to be the most promising one.

Does anyone know why this still happens?

<img width="361" alt="dashboard" src="https://cloud.githubusercontent.com/assets/449438/24293220/f14255b0-1090-11e7-95fe-4c659978cd3c.png">

**Comment by bprashanth** [comment]
For good or bad desktop chrome will do it's darnest to try and thread some valid path through your cert chains from the provided leaf to a valid root. I think android chrome is a little more strict. Maybe https://www.ssllabs.com/ssltest/ will show you where the chain breaks?

**Comment by nerdyglasses** [comment]
@bprashanth thx for ssllabs.com!
I would never have figured it out without it.
I had the same intermediate cert twice in a row.

many many many thx. you have saved a long weekend!

**Comment by lumeche** [comment]
Amazing...... You saved my life!!!!!!!!!!!!!!!!!

That works perfect

**Comment by SARAN-thala** [comment]
If you add multiple certificates in `tls.cert` key. Please do this like this
```
-----BEGIN CERTIFICATE-----
<put your certificate value in a single line >
-----END CERTIFICATE-----
-----BEGIN INTERMEDIATE CERTIFICATE-----
<put your certificate value in a single line>
-----END INTERMEDIATE CERTIFICATE-----
```
Otherwise you'll get an error in ssl cert chain validation.
Always put main certificate first.

**Comment by kplimack** [comment]
@SARAN-thala definitely dont do this, those headers dont mean anything, which is why the upload is "working".  Nothing know hows to consume that chain with those headers.  Upload it as type generic using keys "tls.crt" and "tls.key".  The "tls" secret type wont know how to validate the chain and will bail, so just use generic.

**Comment by ashafer01** [comment]
For me I had to completely flip around the order that the cert bundle came from my CA.

My cert bundle shipped as "root...intermediates...server" and the ingress controller needed "server ... intermediates ... root". All of the certs in the bundle get the same `BEGIN CERTIFICATE` heading regardless of specific type (as the comment above says)

**Comment by ptrovatelli** [comment]
@SARAN-thala @kplimack sorry i'm confused: this issue is closed but still it doesn't seem obvious how to create a secret based on a full trust chain and it's still not documented either. I try when possible to include the full trust chain in servers so that client need only to trust the root CA. 
My trust chain is generated in PEM format, with my own server first and the root CA last (which is the standard way I believe). The certificate itself is already in base64, cut into many lines. 
So do I need to remove those \n? Do I need to remove the headers? I also have "subject=" / "issuer=" lines. do I need to remove them? Does it depend on the ingress controller type? 

It goes like: 

```
subject=...
issuer=...
-----BEGIN CERTIFICATE-----
.........
.........
.........
-----END CERTIFICATE-----

subject=...
issuer=...
-----BEGIN CERTIFICATE-----
.........
.........
.........
-----END CERTIFICATE-----

subject=...
issuer=...
-----BEGIN CERTIFICATE-----
.........
.........
.........
-----END CERTIFICATE-----

```

Thanks!

**Comment by ashafer01** [comment]
@ptrovatelli The subject and issuer lines are not valid.

**Comment by ptrovatelli** [comment]
> @ptrovatelli The subject and issuer lines are not valid.

OK thanks but the rest can be left as is? multi-lines base64 content + non base64 characters like "-----BEGIN CERTIFICATE--"?

**Comment by ashafer01** [comment]
@ptrovatelli that's correct. I suggest researching the PEM format if you have any further questions or issues. This issue covers any k8s-specific problems well.

**Comment by ptrovatelli** [comment]
@ashafer01 great thanks! I wasn't sure that pem format was fully supported as in most procedures it's asked to strip \n from the base64 string before using it in the secrets; and it's usually supposed to be base64 only.

**Comment by ptrovatelli** [comment]
@ashafer01 thanks a lot it works!
To sum up, in order to serve a a full trustchain during the handshake: 
- place the server certificate first and the root CA last
- strip off extra lines in the file to keep only `-----BEGIN CERTIFICATE-----`, `-----END CERTIFICATE-----`, and those multi-lines base64 certificate data (do not remove \n there)
  - for example if converted from p7b format, remove `subject=` and `issuer=` lines
- base64 encode what's left and put into data > tls.crt in the secret definition
```
base64 -w 0 certificate.cer
```
- add the key according to the doc. 

- Test: 
```
openssl s_client -connect myhost.com:443 -servername myhost.com -showcerts
```

(The `-servername` adds the SNI TLS extension that's required when the same gateway serves multiples certificates)

This should show the full chain and end up with `Verify return code: 0 (ok)` if the chain is trusted on the host:
```
CONNECTED(00000003)
depth=2 C = xx, O = xx, CN = myRootCA
verify return:1
depth=1 DC = xx, DC = xx, CN = xx
verify return:1
depth=0 C = xx, ST = xx, O = xx, OU = xx, CN = myhost.com
verify return:1
---
Certificate chain
 0 s:/C=FR/ST=xx/O=xx/OU=xx/CN=myhost.com
   i:/DC=xx/DC=msxxd/CN=xx
-----BEGIN CERTIFICATE-----
...
...
...
...
-----END CERTIFICATE-----
 1 s:/DC=xx/DC=xx/CN=xx
   i:/C=xx/O=xx/CN=xx
-----BEGIN CERTIFICATE-----
...
...
...
-----END CERTIFICATE-----
 2 s:/C=xx/O=xx/CN=myRootCA
   i:/C=xx/O=xx/CN=myRootCA
-----BEGIN CERTIFICATE-----
...
...
...
...
-----END CERTIFICATE-----

(...)

    Verify return code: 0 (ok)
---
```

**Comment by JonasAnastacio** [comment]
**I'm using GKE and none of these worked for me**

I think that's because gcloud doesn't acually use the certificate uploaded on the secret with kubectl. Instead it creates another one based on it, as it seems when I run:
`gcloud compute ssl-certificates list`

The output was an auto-generated certificate that didn't have the entire chain, as I figured with:
`gcloud compute ssl-certificates describe DISPLAYED-CERT-NAME`

So in order to make it work, I just removed all the secrets that I tried to put on the ingress yaml and created another directly on gcloud:
`gcloud compute ssl-certificates create NAME --certificate=LOCAL_FILE_PATH --private-key=LOCAL_FILE_PATH`

(You can describe it to verify that it includes the entire cert chain)

After that I went to:
https://console.cloud.google.com/net-services/loadbalancing

Selected the LoadBalancer related to my ingress resource and with the Edit button I just configured It to use my custom certificate.

After I while It worked! :-)

I'm pretty sure that there's a lot of other ways to do it, but I hope I can help anyone with my experience.

**Comment by craigafinch** [comment]
@JonasAnastacio The procedure described by @ptrovatelli worked for me on GKE. I created the certificate bundle per the procedure and used it to create a TLS secret. I then referenced this secret when creating the Ingress. I automated the process with Terraform.

**Comment by Makesh-Gmak** [comment]
Thanks @ptrovatelli for the detailed steps and @JonasAnastacio for the reference (https://medium.com/@superseb/get-your-certificate-chain-right-4b117a9c0fce)

I was facing chaining issue because I modified the start and end tag of the certs like mentioned in https://github.com/kubernetes/kubernetes/issues/24669#issuecomment-445858536 , ie. modified ```-----BEGIN CERTIFICATE-----``` of intermediate pem to ```-----BEGIN INTERMEDIATE CERTIFICATE-----``` for readability purpose.  

After retaining the tag to original ```-----BEGIN CERTIFICATE-----```, my chaining issue resolved.

**Comment by nofacer** [comment]
Test many answers, finally find this could work for me

For example, you have a server cert called `server.pem` with a key called `server.key`, a Intermediate cert called `server. Intermediate.pem` and a root cert called `server.root.pem`

Step1: Merge server cert and Intermediate cert together by `cat server.pem server. Intermediate.pem > merge.pem`.
Step2:  Create k8s secret by `kubectl create secret generic tls-secret --from-file=tls.crt=merge.pem --from-file=tls.key=server.key --from-file=ca.crt=server.root.pem`.  ca.crt here is important.
Step3: Reference this tls-secret in ingress resource.
