### ISSUE TITLE
Response filter from Kube apiserver

### ISSUE THREAD

**Issue by huang195** [kubernetes/kubernetes#24685]
On the request path to the apiserver, there are different control points, i.e., authn, authz, admission controls. On the return path, is there any mechanism to filter the response? The specific use case is we'd like to hide host name and host ip from users and just have them use service ips to get to their pods. Is there already mechanism in place for this type of work? This would be useful for service providers who use kubernetes under the cover but would like to keep the infrastructure information hidden.

**Comment by mml** [comment]
I don't believe we have hooks for this.  In general it seems dangerous because a user might make edits based on obfuscated information.

What you want sounds like something that should be implemented in a standalone proxy to me.

**Comment by mml** [comment]
@lavalamp @bgrant0607

**Comment by lavalamp** [comment]
There's no provision for this. As @mml mentioned, if you implemented it literally as described, users would be unable to update their pods, since the system would see such an update as an attempt to clear those fields. This could be fixed by using patch and/or also editing the update paths. But you'd be talking about a fork at that point, it's not clear that this is a general need.

I also think you need a proxy. If you don't trust users with the name of the node they're running on, you probably shouldn't trust them with access to the API at all, as there's other ways of figuring that out (scanning events, looking at logs...). Don't forget that we mount an api access token in the pod unless you disable the namespace service account!

I'm going to close this but feel free to argue with me if you don't think that's right :)

**Comment by huang195** [comment]
@mml @lavalamp thanks for your replies. We were also thinking about using an external proxy to do this work, but just wanted to check if there are anything in Kubernetes that already does this.
