### ISSUE TITLE
Missing unit-tests for HorizontalPodAutoscalerDescriber, IngressDescriber and JobDescriber

### ISSUE THREAD

**Issue by ingvagabund** [kubernetes/kubernetes#24731]
When running pkg/kubectl/describe_test.go, there are three objects that has no unit-tests at all:
- HorizontalPodAutoscalerDescriber
- IngressDescriber
- JobDescriber.

I could not found proper fake client for them. It looks like all three needs the same fake client.

Related to https://github.com/kubernetes/kubernetes/issues/24239 to finish testing of `kubectl describe --events=true|false`.

**Comment by bgrant0607** [comment]
@kubernetes/autoscaling @soltysh @bprashanth

**Comment by ingvagabund** [comment]
And ``PetSetDescriber`` too. @smarterclayton

**Comment by bprashanth** [comment]
actually i don't think unittests for "describe" on alpha/beta resources is that big of a deal. At lest in the case of petset, because there's hardly anything in there, and in the case of Ingress I'm actually serializing/deserializing json from annotations. In both cases I expect describe output to change significantly and I wanted to avoid the churn. 

That said, I suppose we should write some shell fake so we can test machinery for cases like this.

**Comment by soltysh** [comment]
Will work on a JobDescriber tests shortly.
