### ISSUE TITLE
Pod networking does not work in local Docker setup

### ISSUE THREAD

**Issue by zxcvbn97** [kubernetes/kubernetes#24757]
Hi there,

I setup kubernetes v1.2.3 according to the "[Running Kubernetes Locally via Docker](http://kubernetes.io/docs/getting-started-guides/docker/)" guide. I'm using Docker 1.9.1 using CoreOS stable (899.15.0) on a bare metal machine. 

I could run a Debian container for now.
`kubectl run -i --tty debian --image=debian --restart=Never`

*However, I could not ping other containers by IP address (e,g., ping 10.0.0.1) does not work.*
When I tried to expose a service, I don't see any external IP. 

Please help.

**Comment by mml** [comment]
Please re-post your question to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases.

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to similar questions, and also familiarize yourself with:
   * [the user guide](http://kubernetes.io/docs/user-guide/)
   * [the troubleshooting guide](http://kubernetes.io/docs/troubleshooting/)

Again, thanks for using Kubernetes.

The Kubernetes Team
