### ISSUE TITLE
Test Flakes: Expand the integration test framework

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#24760]
Many more tests than necessary are written as e2e tests right now. If the integration framework were easier to use, it could potentially give a lot of signal that we don't get right now until the e2es are run. Additionally, it'd be easier for people to run and debug locally.

Therefore:
- Make the integration tests use ginkgo. (Not that I love ginkgo, but we should be consistent.)
- Expand the integration test framework, to make it super easy to turn on any system component you need.
- It'd be super awesome if the framework were similar enough to the e2e framework that people could move tests between the two with relative ease.
- Remove cmd/integration. #24440

Part of: #24753

**Comment by spxtr** [comment]
> Make the integration tests use ginkgo. (Not that I love ginkgo, but we should be consistent.)

I'm not a fan of this. Go's testing framework is great, and we already use it for unit/integration tests. The only feature we're missing is JUnit XML output. Ginkgo can do very confusing things at times and has caused the test infra team quite a bit of pain. See #23350 for a recent example.

> Remove cmd/integration. #24440

We made #21420 a long time ago, but it turns out that the setup for these two integration suites is different enough that it won't be a simple thing to move the tests from one to the other. @jlowdermilk knows more.

**Comment by lavalamp** [comment]
@spxtr Yeah, that's a good point. I went on vacation once and we were using ginkgo when I came back. If only I'd made us stop right then! Alas, it'd now be a lot of work to switch away. But I agree that JUnit output is the more pressing concern.

Re: cmd/integration, we should just rewrite the tests. Don't bother moving them.

**Comment by spiffxp** [comment]
/close
I'm going to close this in favor of this proposal https://github.com/kubernetes/community/pull/1524 which is based on https://github.com/kubernetes/kubectl/tree/master/pkg/framework/test

Please /reopen if you think this isn't in the spirit of this issue
