### ISSUE TITLE
ELB creation doesn't support custom tagging (or naming)

### ISSUE THREAD

**Issue by victorcampos** [kubernetes/kubernetes#24791]
Currently, when creating an ELB in AWS, Kubernetes doesn't support adding custom tags or naming for the resources. In turn this requires a very broad set of permissions for the Instance Profile running the master, allowing full access to ANY ELB in the same account.

From my perspective this is unsuitable for larger corporations running in AWS under a single account as this increases risks of others teams' ELBs being manipulated by an instance they aren't aware of.

My suggestion would be to allow some basic configuration in the cluster to include custom tagging or at least prefixing the name of resources created by Kubernetes so allowing IAM-like permission schemes to filter based on the tags or naming. Not only for AWS but I don't have expertise with GCE or other public cloud providers to know if they support IAM-like authorization.

**Comment by therc** [comment]
The name prefix is the less preferable option, since we need to create unique names and already have a 32-character limit (and there's a PR under review to set a custom name or at least a prefix). Also, the Describe* APIs do not allow to restrict actions to specific resources, i.e. they can only be specified as "Resource": "*"

http://docs.aws.amazon.com/elasticloadbalancing/latest/userguide/load-balancer-authentication-access-control.html

For all other operations, ELB names all have an "a" prefix (because of a GCE limitation...), so perhaps the policy can tightened there.

We already set two tags, KubernetesCluster and kubernetes.io/service-name. Would that be enough? The problem with tag-based filtering is that the master needs to be able to set tags. Which means that, in case of bugs or remote code execution exploits, the master could work around the restrictions, e.g. by removing or changing the tags. Perhaps that, in turn, can be avoided by not granting the role RemoveTags/AddTags. I'm not sure if the tags passed when calling CreateLoadBalancer() require the AddTags permission, though.

It's not clear which of the several possible risk scenarios you are trying to avoid.

**Comment by dhoer** [comment]
Billing is our use case.  We have clusters that customers share and need a way to bill back their usage.  We use tags for billing on our current legacy AWS implementations and it works great.  Would like to use tags the same way on k8s.

**Comment by hridyeshpant** [comment]
@justinsb @therc in our case we are running some cleanup process and any aws resource dont have valid tag are getting deleted, so whenever i am creating service with Loadbalancer after some time that ELB is getting deleted by cleanup process.
I am kind of block now, is there way we can assign custom tag while creating ELB for service.
 i am abel to use "cloudLabels" for other resources, but seems ELB creation don't count cloudLabels.

**Comment by hridyeshpant** [comment]
do we have any solution for this?

**Comment by philips** [comment]
Put together a proposal to address AWS Custome Resource Labeling. PTAL: https://github.com/kubernetes/community/pull/404

cc @justinsb

**Comment by robszumski** [comment]
Tagging was added in this commit: https://github.com/arthur0/kubernetes/commit/e36b9a7f59b5745e0758ba7e425c4cc5ec4d844a

I had success with the following example:

```
kind: Service
apiVersion: v1
metadata:
  name: myservice
  namespace: service
  labels:
    app: ingress
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: 'createdBy=foo'
...
```

**Comment by howinator** [comment]
Can this be closed now?
