### ISSUE TITLE
Run Kubernetes cluster offline

### ISSUE THREAD

**Issue by MartinPyka** [kubernetes/kubernetes#24824]
I am following this tutorial to set up a test cluster with two CentOS VMs:
http://kubernetes.io/docs/getting-started-guides/centos/centos_manual_config/

I figured out that I am only able to start kube-apiserver (systemctl enable kube-apiserver) and kube-proxy when there is an internet connection. Otherwise I get the error:
"Job for kube-apiserver.service failed because the control process exited with error code. See "systemctl status kube-apiserver.service" and "journalctl -xe" for details.
The status command just mentions (code=exited, status=255).

When I connect the VM to the internet everything runs smoothly. After enabling the kube-apiserver I can switch back to offline mode and continue creating my cluster.

What is going on here? How can I set up the cluster entirely offline? Are kube-apiserver and kube-proxy not supposed to work offline?

Thanks,
Martin

**Comment by MartinPyka** [comment]
Sorry to bring this up again, but is there really no way to start the binaries offline? The hyperkube docker container seems to need internet and the kube-apiserver as well. Can anyone point me to the lines in the code where any remote calls happen?

**Comment by erictune** [comment]
Kubernetes should be able to start without a connection to the internet.  However, many of the core developers, including me, are not familiar with CentOS, so I don't know if it is doing something odd.

Suggested other places to go for help:
- The `systemctl enable` might need to do a `docker pull` from the internet.    You might have review what the systemd units are doing, in terms of starting docker containers, and pre-pull all needed images while connected to the internet, so that when docker runs, it uses the cached images.  I don't think there is any standard way for RPMs to distribute docker images.
- stackoverflow.com has lots of users, and some might have used CentOS.
- http://kubernetes.io/docs/getting-started-guides/coreos/bare_metal_offline/ talks about how to get Kubernetes working offline, with a different distro (not sure how up-to-date that doc is, let us know).

**Comment by erictune** [comment]
Please feel free to reopen if you find more information and think something in `kube-apiserver` itself (as opposed to docker or systemd units) is reaching out to the internet, and should not be.

**Comment by virtuald** [comment]
@MartinPyka did you get this figured out, seems related to https://github.com/kubernetes/kubernetes/issues/28189 .
