### ISSUE TITLE
kubectl patch --record doesn't show up at rollout history

### ISSUE THREAD

**Issue by hekike** [kubernetes/kubernetes#24858]
Hi,

Deployment patching with `--record` doesn't show up in the deployment rollout history:

first:
```
kubectl patch deployment mydep -p '{"spec":{"template":{"spec":{"containers":[{"name":"mycontainer","image":"gcr.io/project/my-container:TAG_NAME"}]}}}}' --record
```

after:
```
kubectl rollout history deployment/mydep
```
```
REVISION	CHANGE-CAUSE
1		<none>
10		<none>
2		<none>
3		<none>
4		<none>
```

Is it a bug? Should it show up?

Thanks,
Peter

**Comment by bgrant0607** [comment]
cc @janetkuo

**Comment by bgrant0607** [comment]
@hekike Which kubernetes and kubectl releases? Did the patch actually trigger a rollout?

**Comment by hekike** [comment]
@bgrant0607 

`kubectl version`
```
Client Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.2", GitCommit:"528f879e7d3790ea4287687ef0ab3f2a01cc2718", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.3", GitCommit:"882d296a99218da8f6b2a340eb0e81c69e66ecc7", GitTreeState:"clean"}
```

**Comment by hekike** [comment]
@bgrant0607 I also run the command from CI with the latest `kubectl`. So the problem affects the v1.2.3 kubectl as well

**Comment by kargakis** [comment]
We should also fix the way we sort revisions - 10 should be after 9, not 1.

**Comment by bharrisau** [comment]
Can confirm this. The issue is that the patch isn't updating `metadata.annotations.kubernetes.io/change-cause`, so the rollout history will just copy the value from the previous version. If you started with `<None>` you get that for the patches. In my case I have a different line repeated.

```
REVISION	CHANGE-CAUSE
1		kubectl create -f deployment.yml --record
2		kubectl --namespace test apply -f deployment.yml
3		kubectl --namespace test apply -f deployment.yml
4		kubectl --namespace test apply -f deployment.yml
5		kubectl --namespace test apply -f deployment.yml
6		kubectl --namespace test patch deployment foo --type=json -p=[{"op": "replace", "path": "/spec/template/spec/containers/0/image", "value":"repo/demo:build462"}]
7		kubectl --namespace test patch deployment foo --type=json -p=[{"op": "replace", "path": "/spec/template/spec/containers/0/image", "value":"repo/demo:build462"}]
8		kubectl --namespace test patch deployment foo --type=json -p=[{"op": "replace", "path": "/spec/template/spec/containers/0/image", "value":"repo/demo:build462"}]
```

Builds 7 and 8 were built with different `buildXXX`.

I'm not sure why the patch worked once.

Command I am calling is:
`kubectl $CMD_PREFIX patch deployment $deployment --record --type='json' -p="[{\"op\": \"replace\", \"path\": \"/spec/template/spec/containers/0/image\", \"value\":\"$image\"}]"`

**Comment by dshulyak** [comment]
If no one is working on patch - i can try to make one.

**Comment by tnachen** [comment]
@dshulyak I'll like to work on this issue if you haven't started yet

**Comment by tnachen** [comment]
Actually never mind I can look at something else :)

**Comment by dshulyak** [comment]
@deads2k Hi, i see that you are the author of the following comment. I think that currently every valid change cause is discarded because of version conflict. Maybe you have some information why it happens?

```
				// don't return an error on failure.  The patch itself succeeded, its only the hint for that change that failed
				// don't bother checking for failures of this replace, because a failure to indicate the hint doesn't fail the command
				// also, don't force the replacement.  If the replacement fails on a resourceVersion conflict, then it means this
				// record hint is likely to be invalid anyway, so avoid the bad hint
```

**Comment by bharrisau** [comment]
`apply` command instead generates a patch to update `kubernetes.io/change-cause` then applies that.

https://github.com/kubernetes/kubernetes/blob/c6e995a824094a96f7d43a25e897283f83a12997/pkg/kubectl/cmd/apply.go#L191

**Comment by dshulyak** [comment]
It was the same for patch, but for some reason was changed.

https://github.com/kubernetes/kubernetes/commit/11da9a7638e393f84eb34fcf54c1962b3cdc115c

**Comment by deads2k** [comment]
> Maybe you have some information why it happens?

The intent was two fold.  First, prevent the change-cause from ever failing patch the CLI command.  change-cause isn't authoritative and the patch took hold, so a non-zero return code is inappropriate.

Second, if the resource version change post-patch, before the update, the change-cause is unknown, something else touched it after the fact.  A command that issues a `patch` instead of an `update` could very easily *break* the history since patches will attempt to reapply themselves regardless of resource version in the face of conflicts.  The object returned from the patch operation is the one that we use to avoid hitting a resource conflict with ourselves.

Truth be told, I don't feel very strongly about getting the history right since it can be changed anyone with write access to the object, includes secrets that should be elided (--token for instance), ignores environment variables which affect outcome, ignores the actual path used to locate the binary you're running, and references paths that are only good from one location on one machine, so if you want to switch it back to a second patch, I don't mind as long as a failure to update the object doesn't cause a non-zero return from the command.

**Comment by bharrisau** [comment]
Could there be a race between the `replace` call and the deployment
updating itself to action the changes?
