### ISSUE TITLE
pod updates:how to change the  fields of spec.containers[].resources.limits.cpu(memory)?

### ISSUE THREAD

**Issue by liuyang430068** [kubernetes/kubernetes#24913]
I want to scale up live pod's spec.containers[].resources.limits.cpu(memory).
but:
kubectl patch pod valid-pod -p '{"spec":{"containers":[{"name": "kubernetes-serve-hostname","resources":{"limits":{"cpu":"2"}}}]}}'
stdout->
spec: Forbidden: pod updates may not change fields other than `containers[*].image` or `spec.activeDeadlineSeconds`

how to change the  fields of spec.containers[].resources.limits.cpu(memory)?

**Comment by bgrant0607** [comment]
@liuyang430068 Just as the message says, these fields cannot be updated on pods. You could delete and re-create the pod, though probably you should be creating a controller, such as a Deployment instead, which does allow these fields to be updated and can roll out the change for you. 
http://kubernetes.io/docs/user-guide/deployments/

**Comment by tobegit3hub** [comment]
Hi @bgrant0607 , is it any reason about why Kubernetes can't support this? Docker has the [APIs](https://docs.docker.com/engine/reference/commandline/update/) to update the memory or cpu for running containers and this is meaningful for serveless services.

**Comment by resouer** [comment]
See comment: https://github.com/kubernetes/kubernetes/issues/39060#issuecomment-268449812

**Comment by tsuna** [comment]
@bgrant0607 JFYI, using a deployment doesn't fix the problem here, at least with v1.9.6 editing the limit in the deployment doesn't cause any change to be rolled out by the controller.

**Comment by chestack** [comment]
v1.9.8

kubectl edit deploy ****, then update resources works on my env

**Comment by angeloudy** [comment]
It doesn't make sense to me that `kubectl edit` works while `kubectl apply` does not.
With `kubectl apply`, I can easiy update resource settings of hundreds of pods.
I can't go to every single pod and do `kubectl edit`.

**Comment by zatricky** [comment]
Perhaps some confusion here ; I came across this error due to trying to edit a pod directly. However, a pod shouldn't be edited. Pods should be managed by a controller (usually a deployment) which would replace the pod with a new one that has the new config. By design it makes sense you shouldn't ever need to edit a pod.

If you *really* want to "edit" a pod, one way is to edit an exported config, delete the existing pod, and then create/apply the new .yaml which creates a replacement pod with the same name as the old one.
