### ISSUE TITLE
how to choose the PersistentVolume types when binding PVCs to PVs

### ISSUE THREAD

**Issue by liuyang430068** [kubernetes/kubernetes#24914]
root@master:~/nfs/nfs-pv# kubectl get pv
NAME           CAPACITY   ACCESSMODES   STATUS      CLAIM             REASON    AGE
hostpathtest   50Mi            RWO                     Available                               4s
nfstest            50Mi            RWO                     Available 
the PersistentVolume type of hostpathtest is "hostpath";the PersistentVolume type of nfstest   is "NFS"

now I create a pvc ,I want the pvc to bind hostpathtest,how to how to choose the PersistentVolume types of the pv.

**Comment by jingxu97** [comment]
@saad-ali could we choose volume type in PVC?

**Comment by castrojo** [comment]
Please re-post your question to [Stack Overflow](http://stackoverflow.com/questions/tagged/kubernetes).

Thanks for taking the time to report an issue to us. In the past this tracker has housed both bug reports and user support requests, we are now only using this tracker for software defects and feature tracking.   

We are trying to consolidate the channels to which questions for help/support
are posted so that we can improve our efficiency in responding to requests,
and to make it easier for you to find answers to frequently asked questions and
how to address common use cases.

The Kubernetes team scans Stack Overflow on a regular basis, and will try to
ensure your questions don't go unanswered.

If you're looking for more long-form discussion on best practices, we encourage you to check out the [Kubernetes user list](https://groups.google.com/forum/#!forum/kubernetes-users). 

You can also find more information here:

  * [User Documentation](http://kubernetes.io/docs/)
  * [Troubleshooting Guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/)

Again, thanks for using Kubernetes. If you feel this issue has been closed in error then please reopen it and we can have another look. 

The Kubernetes Team
