### ISSUE TITLE
Flake: unit test federation/cmd/federated-apiserver/app.TestRun

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/kubernetes#24952]
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-test-go/11484/

Not much info on why or how it failed.

cc @quinton-hoole

**Comment by quinton-hoole** [comment]
Cc @nikhiljindal

**Comment by nikhiljindal** [comment]
cc @jianhuiz

**Comment by jianhuiz** [comment]
cant open the link, would you mind paste the content?

**Comment by mikedanese** [comment]
can you access http://ci-test.k8s.io/kubernetes-test-go/11484/ ?

**Comment by jianhuiz** [comment]
It failed due to bind address already in use. 
The same address were used in example/apiserver (which runs befor federated-apiserver) as well.
I wonder if the tests are run in parallel? If it is the case, I can change the port to other values (8082 for example)
Otherwise, it may indicate that the address:port was not proper released for some reason
http://stackoverflow.com/a/5106755/2259827


> 
=== RUN   TestRun
I0428 16:44:35.743406   11033 server.go:93] Will report 172.17.0.2 as public IP address.
I0428 16:44:35.743721   11033 plugins.go:71] No cloud provider specified.
I0428 16:44:35.744477   11033 genericapiserver.go:287] Node port range unspecified. Defaulting to 30000-32767.
[restful] 2016/04/28 16:44:35 log.go:30: [restful/swagger] listing is available at https://172.17.0.2:443/swaggerapi/
[restful] 2016/04/28 16:44:35 log.go:30: [restful/swagger] https://172.17.0.2:443/swaggerui/ is mapped to folder /swagger-ui/
I0428 16:44:35.771256   11033 genericapiserver.go:650] Serving securely on 0.0.0.0:6443
I0428 16:44:35.771586   11033 genericapiserver.go:713] using existing apiserver.crt and apiserver.key files
I0428 16:44:35.778684   11033 genericapiserver.go:694] Serving insecurely on 127.0.0.1:8081
**F0428 16:44:35.778897   11033 genericapiserver.go:695] listen tcp 127.0.0.1:8081: bind: address already in use**
FAIL	k8s.io/kubernetes/federation/cmd/federated-apiserver/app	0.228s

**Comment by quinton-hoole** [comment]
@jianhuiz Yes, tests run in parallel.   Can you perhaps use a random port number each time?  This will reduce the probability of collision to nearly zero (close enough to zero for practical purposes).

See https://github.com/kubernetes/kubernetes/blob/master/docs/devel/testing.md .

https://github.com/kubernetes/kubernetes/blob/master/docs/devel/writing-good-e2e-tests.md also provides other background reading, but is focussed on end-to-end tests.  Much of the discussion applies to unit tests also though.

**Comment by nikhiljindal** [comment]
I think changing the Insecure Port at https://github.com/kubernetes/kubernetes/blob/11298d02e07ce9fe2329f2cc9d27b450dce104ce/federation/cmd/federated-apiserver/app/server_test.go#L77 from 8081 to some other value (say, 8082) should be fine.

**Comment by jianhuiz** [comment]
Which should I use? 8082 or random?
Personally I wouldn't be so optimistic about using random port number since no matter how small the probability is, it will happen eventually, which would be a surprise to those who's not aware of this.

**Comment by nikhiljindal** [comment]
Yes I am fine with changing the port to 8082. Feel free to send me the PR for review.

**Comment by mikedanese** [comment]
> Personally I wouldn't be so optimistic about using random port number since no matter how small the probability is, it will happen eventually, which would be a surprise to those who's not aware of this.

If you specify port 0 when you bind, the kernel will hand you an available port so there won't be a conflict.

**Comment by nikhiljindal** [comment]
@mikedanese We also want to know the port to be able to curl it in the test.
