### ISSUE TITLE
Kubelet image GC for docker "Data Space Total" instead of disk space

### ISSUE THREAD

**Issue by openxxs** [kubernetes/kubernetes#24974]
Docker 1.10.2
Kubernetes 1.1.7

I start docker with parameter `--graph=/mydisk/mypath/`, and start Kubelet with parameters `--docker-root=/mydisk/mypath/ --image-gc-high-threshold=80 --images-gc-low-threshold=60`.
`docker info` shows me `Data Space Total: 107.4 GB`. And `mydisk` is 1.2T.
With a long time running, the total size of pulled docker images reaches 107.4GB. Then docker daemon crashes.
I do not want to set `--storage-opt dm.loopdatasize=1.2T` for docker. So what can I do to make Kubelet image GC for docker "Data Space Total" instead of disk space?

**Comment by mml** [comment]
Please re-post your question to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases.

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to similar questions, and also familiarize yourself with:
   * [the user guide](http://kubernetes.io/docs/user-guide/)
   * [the troubleshooting guide](http://kubernetes.io/docs/troubleshooting/)

Again, thanks for using Kubernetes.

The Kubernetes Team
