### ISSUE TITLE
Making kerberos credentials available inside a container

### ISSUE THREAD

**Issue by mogthesprog** [kubernetes/kubernetes#24997]
Note: I realise this is a very general question, but i specifically want to know if there's a feature of kubernetes or something that i can do to solve this in an easier way?

Hi Guys,

So i've been looking into how best to make a kerberos ticket-granting ticket available inside a container on behalf of a user. I'll give a bit of background below:

We have a self service portal, where users spawn services for themselves, things like jupyter notebooks/zeppelin and Rstudio, where they can develop their applications and models. We use a kerberised hadoop cluster for our warehousing/mart solution, and the interface between a k8s container and hadoop isn't currently working for us. Since all the user interaction with the service is done through a browser, there's no way for them to perform a kinit inside a container.

As a way around this, i'm thinking of generating UserPrincipal keytabs on behalf of users (using a web service and SAML auth), and using serviceAccounts and Secrets, orchestrating the keytabs into namespaced containers (where the namespace is the user, to prevent access from pods in other namespaces), and then using a bootstrap script in our image which will perform a kinit using the provided keytab, generating credentials for the user.

Multitenancy (as in, multiple krb5 domains) won't be an issue, since we use just one kerberos domain.

What are the drawbacks of this? I realise this isn't an ideal solution, but it seems like the only one that's currently available in k8s, unless i'm missing something?

Cheers

**Comment by maisem** [comment]
Please re-post your question to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases.

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to similar questions, and also familiarize yourself with:
   * [the user guide](http://kubernetes.io/v1.0/)
   * [the troubleshooting guide](http://kubernetes.io/v1.0/docs/troubleshooting.html)

Again, thanks for using Kubernetes.

The Kubernetes Team

**Comment by doprdele** [comment]
@mogthesprog were you able to find a solution for this? I'm in the same boat, need to kinit inside a container, currently authentication to a web service using university CAS connected to a central A.D. to launch JupyterHub, etc.
