### ISSUE TITLE
Web interface error. ssh: rejected: connect failed (Connection refused)

### ISSUE THREAD

**Issue by motomux** [kubernetes/kubernetes#25002]
When I accessed to web interface (MASTER_END_POINT/ui), I got redirected to `/api/v1/proxy/namespaces/kube-system/services/kubernetes-dashboard/` and got the following error page.

```
Error: 'ssh: rejected: connect failed (Connection refused)'
Trying to reach: 'http://10.0.1.6:9090/'
```

platform: GKE
Master version: 1.2.2
Node version: 1.2.0

**Comment by motomux** [comment]
After I tried several times, I got the other error page.

```
Error: 'EOF'
Trying to reach: 'http://10.0.1.6:9090/'
```

Then I finally could see web interface.

**Comment by mml** [comment]
Please re-post your question to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases.

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to similar questions, and also familiarize yourself with:
   * [the user guide](http://kubernetes.io/docs/user-guide/)
   * [the troubleshooting guide](http://kubernetes.io/docs/troubleshooting/)

Again, thanks for using Kubernetes.

The Kubernetes Team
