### ISSUE TITLE
Jenkins tasks can fail due to FS permissions problem

### ISSUE THREAD

**Issue by mml** [kubernetes/kubernetes#25086]
- http://ci-test.k8s.io/kubernetes-build/9650/
 - http://ci-test.k8s.io/kubernetes-build/9651/

@krousey will be adding some data from an ssh session.  I also note that once this build failed, it was not automatically retried.  Why was that?

**Comment by krousey** [comment]
I can't ssh to jenkins-builder-4 to diagnose/fix. I can ssh to the master just fine. Still working on it.

**Comment by spxtr** [comment]
```
09:55:16 +++ [0503 09:55:16] Cleaning out local _output directory
09:55:16 rm: cannot remove `/var/lib/jenkins/workspace/kubernetes-build/_output/dockerized/bin/linux/amd64/kubectl': Permission denied
```
```
$ ls -l _output/dockerized/bin/linux/amd64/
-rwxr-xr-x 1 root root 57384632 May  3 01:34 kubectl
```
This has happened to me before on my local machine, since those files in _output are made in a docker container and owned by root. I don't know why it's happening all of a sudden. I sudo rm'd the _output folders and kicked off a new build.

@ixdy should probably take things from here.

**Comment by spxtr** [comment]
#25052

**Comment by ixdy** [comment]
Yeah, it's dumb. Jenkins uses the build image from the previous run to clean up the artifacts from the previous run; since the files are written out by Docker, they're owned by root, so it can't delete them directly. And I changed the name of the build image, so it couldn't find the old one anymore.

It's fragile and breaks not infrequently. We should just use `sudo rm -rf` to clean up the workspace rather than relying on the build image to help us do it.

**Comment by ixdy** [comment]
Apologies for breaking the build, however. I should have known this would happen.

**Comment by ixdy** [comment]
https://github.com/kubernetes/test-infra/pull/14 should fix this once and for all, I hope.
