### ISSUE TITLE
Can not access service externally for nodePort type, help please.

### ISSUE THREAD

**Issue by xhe** [kubernetes/kubernetes#25093]
I am very interested in testing NodePort to see how the embedded is working, but then I am totally lost.
I am following this: http://kubernetes.io/docs/user-guide/connecting-applications/

Step 1:

`apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: my-nginx
spec:
  replicas: 2
  template:
    metadata:
      labels:
        run: my-nginx
    spec:
      containers:
      - name: my-nginx
        image: nginx
        ports:
        - containerPort: 80`
Step 2:

`
apiVersion: v1
kind: Service
metadata:
  name: my-nginx
  labels:
    run: my-nginx
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: my-nginx
`

After above step: I run 

`kubectl get services`

I got:

`my-nginx        10.0.0.99    nodes         80/TCP     9m`

I run: 

`kubectl describe service my-nginx`

I have:

`
Name:			my-nginx
Namespace:		default
Labels:			run=my-nginx
Selector:		run=my-nginx
Type:			NodePort
IP:			10.0.0.99
Port:			<unset>	80/TCP
NodePort:		<unset>	30526/TCP
Endpoints:		
Session Affinity:	None
No events.
` 
Now I am lost, how can I access the service externally?  I tried a lot, and it is always unavailable.

Thanks

**Comment by roberthbailey** [comment]
Please re-post your question to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases.

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to similar questions, and also familiarize yourself with:
   * [the user guide](http://kubernetes.io/v1.0/)
   * [the troubleshooting guide](http://kubernetes.io/v1.0/docs/troubleshooting.html)

Again, thanks for using Kubernetes.

The Kubernetes Team
