### ISSUE TITLE
RFC: Adding Persistent Volumes Test Cases

### ISSUE THREAD

**Issue by rootfs** [kubernetes/kubernetes#25120]
# RFC: Adding test cases to [e2e/persistent_volumes.go](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/persistent_volumes.go) and [integration/persistent_volumes_test.go](https://github.com/kubernetes/kubernetes/blob/master/test/integration/persistent_volumes_test.go)
### [e2e/persistent_volumes.go](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/persistent_volumes.go)

This file creates an NFS PV with recycle policy and an PVC to claim the PV. 
After the PVC is bound, it is deleted and PV is recycled.
### [integration/persistent_volumes_test.go](https://github.com/kubernetes/kubernetes/blob/master/test/integration/persistent_volumes_test.go)

This file creates a fake PV with Recycle policy, creates a PVC that binds to fake PV, deletes the PVC and triggers PV recycler, watches for the PV to be released then available.
In the second test, the PV is set Delete policy and binds to a PVC. After PVC is deleted, watches the PV to be deleted too.
In the third test, 100 PVCs are created, manually puts one of the PVC ref to a PV, watches PV is bound and verify PV is bound to the PVC.
## Existing Red Hat Tests proposed for transfer to Kubernetes E2E Test Environment

| Test Case | PR | Status |
| --- | --- | --- |
| 1 |  |  |
| 2 |  |  |
| 3 |  |  |
| 4 |  |  |
### 1. Create Pod that uses multiple PVCs. Verify all PVCs are successfully bound and mounted.
- Setup. 
  - In the NFS server pod, creates 3 exports  
  - Create 3 PVs, with sizes 1GB, 2GB, and 3GB, these PVs map to the 3 NFS exports
  - Create 3 PVCs, with claim sizes 1GB, 2GB, and 3GB. 
  - Create a client Pod that uses the 3 PVCs
- Expected Result. The client Pod should mount all NFS PVs, each PVCs are bound to the PVs with the matching size.
### 2. Create one PV and multiple PVCs. Verify exactly one PVC bound while other PVCs are pending.
- Setup
  - Create 1 PVs with sizes 1GB
  - Create 3 PVCs, with claim sizes 1GB, 2GB, and 3GB. 
- Expected Result. 1GB PVC should be bound to the PV, 2GB and 3GB PVCs are pending.
#### Create PV with Delete policy
- Setup
  - Create 1 PVs with sizes 1GB and Delete reclaim policy 
  - Create 1 PVCs with claim sizes 1GB
  - Delete the PVC
- Expected result. After PVC is deleted, PV is also deleted
#### 4. Create PV with Retain policy
- Setup
  - Create 1 PVs with sizes 1GB and Delete reclaim policy 
  - Create a file on the PV
  - Create 1 PVCs with claim sizes 1GB
  - Delete the PVC
- Expected result. After PVC is deleted, PV still exists and the file on the PV also exists

**Comment by jeffvance** [comment]
Additional test cases to consider (from https://gist.github.com/jeffvance/4d3f78d1e772e360ce33bef48e450df1):

### PREBIND: test that a pre-bound PVC binds to the target PV.
 - Setup:
     -  create pvc1 with _Spec.VolumeName_ = "pv1"
     -  create pv1 with no pre-binding (no ClaimRef)
     -  pvc1 and pv1 have same _accessModes_ and _capacity_ spec, so they would naturally match
 - Expected Result: pv1 and pvc1 are both in the _Bound_ phase and bound to each other.
     
### PREBIND: test that a pre-bound PVC binds to the target PV when not a "natural" match.
 - Setup:
     -  create pvc1 which defines _Spec.VolumeName_ = "pv1"
     -  create pv1 with no pre-binding (no claimRef)
     -  pvc1 and pv1 have **different** _accessModes_ and/or _capacity_ spec, so they will not naturally match
 - Expected Result: pv1 and pvc1 are both in the _Bound_ phase and bound to each other.

### PREBIND: test that a pre-bound PV and a pre-bound PVC (but _not_ pre-bound to each other) don't bind, even if they would otherwise match.
 - Setup:
     -  create pv1 which defines _Spec.ClaimRef.Name_ = "pvc1"
     -  create pvc1 which defines _Spec.VolumeName_ = "pv2" //_not_ "pv1"
     -  pvc1 and pv1 have same _accessModes_ and _capacity_ spec, so they would naturally match
 - Expected Result: pv1's status is _Released_, pvc1's status is _Pending_. They are not bound to each other.

### RECYCLE: test that a Retained (controller-bound) PV is re-claimable after being deleted.
 - Setup:
     -  pv1 defines `persistentVolumeReclaimPolicy` = "**Retain**" (pv1 does not define a `claimRef`)
     -  pvc1 is defined to match pv1 (pvc1 does not define `volumeName`)
     -  create pv1 and pvc1 and verify that they are both _Bound_
     -  delete PVC1 and verify that pv1's status is _Released_
     -  delete PV1 and re-create pv1
 - Expected Result: pv1's status is _Available_ and pvc1 can re-bind to pv1.

### RECYCLE: test that a Retained (pre-bound) PV is _not_ re-claimable after being deleted.
 - Setup:
     -  pv1 defines `persistentVolumeReclaimPolicy` = "**Retain**" and defines `ClaimRef.Name` = "pvc1"
     -  pvc1 does not define `volumeName`
     -  create pv1 and pvc1 and verify that they are both _Bound_
     -  delete PVC1 and verify that pv1's status is _Released_
     -  delete PV1 and re-create pv1
 - Expected Result: pv1's status remains _Released_ and pvc1 **cannot** re-bind to pv1.

**NOTE:** this is the current behavior but I believe that the expected result should be the same as for the controller-bound case above.

**Comment by rootfs** [comment]
@kubernetes/sig-testing @kubernetes/sig-storage

**Comment by jeffvance** [comment]
@jeffvance and @copejon will work on this issue and create a pr shortly.

**Comment by msau42** [comment]
@jeffvance can this be closed?

**Comment by jeffvance** [comment]
@msau42 In looking at this issue I think we have cases 2 & 3 covered. Cases 1 & 4 may be tested but this is not done explicitly/deliberately from what I am aware of. I have not seen new PV test cases in _integration/_. So it looks like this issue cannot be closed yet since it has not been fully satisfied. Or maybe it can be edited and a new issue can be created to contain only the cases we don't cover presently?

**Comment by msau42** [comment]
Yeah maybe it's worth opening up separate issues for the remaining test cases.  Can you evaluate which cases still need coverage?
