### ISSUE TITLE
Pods missing on Grafana/InfluxDB dashboards

### ISSUE THREAD

**Issue by erez-rabih** [kubernetes/kubernetes#25131]
Hi,

I'm having a lot of cases in which pods are missing on the Grafana dashboard so I can't view their metrics.

Using kubernetes 1.2.1 on AWS.

Any way to troubleshoot this?

**Comment by erez-rabih** [comment]
It looks like the same applies to nodes. I have 20 nodes on the cluster but I can see only 5 of them on the Grafana dropdown list.

**Comment by erez-rabih** [comment]
Looks like it is a heapster-kubelet error.
When I fetch the logs from the Heapster pod I get multiple errors of the following kind:
```
summary.go:114] error while getting metrics summary from Kubelet: request failed - "500 Internal Server Error", response: "Internal Error: unable to find data for container /system.slice/docker-add96a1e5ddb001f662fe92742052873f604bb1ac607ef4c52b30a46c7c55833.scope
```

**Comment by erez-rabih** [comment]
Might be related to #24713

**Comment by roberthbailey** [comment]
/cc @mwielgus @piosz @jimmidyson 

If this is a heapster problem, we should file an issue in https://github.com/kubernetes/heapster/

**Comment by piosz** [comment]
From https://github.com/kubernetes/kubernetes/issues/25131#issuecomment-217118801 it looks like a Kubelet problem.

cc @timstclair @dchen1107

**Comment by timstclair** [comment]
It looks like there are a couple of things going on here:

1. Kubelet uses it's internal state to individual request each container it is aware of, but that list may not be in sync with cAdvisor's list (due to latency from housekeeping interval), so a container may not be existing yet. Instead, "Recursive" calls to `GetContainerInfo` should rely on cAdvisor to get subcontainer info.
2. For robustness, when requesting info about all containers we should not fail the whole request if fetching 1 container fails. Rather, we should accumulate both errors and results and do a best-effort response. (We may be able to add more intelligence based on what / when / how containers failed).

I'm adding this to 1.3 since I think it's important for solidifying the summary API.

@erez-rabih With regards to fixing your specific issue, is that error response happening on every heapster request, or just some of them? I would expect the node to stabilize once cAdvisor has a current view of the containers, but if that's not the case it may indicate that the Kubelet thinks a container is still running and it's not.

**Comment by erez-rabih** [comment]
@timstclair The error happens all the time according to the heapster logs.
It might be related to anther weird thing I experience - I have some pods hung in a Terminating state for a few weeks now.
When I try to `kubectl delete pod <podname>` it doesn't change anything.
