### ISSUE TITLE
Kubectl rollout can't initiate a rollout

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#25142]
[kubectl rollout](http://kubernetes.io/docs/user-guide/kubectl/kubectl_rollout/) can pause or unpause or undo a rollout.  But it cannot initiate a rollout.  IIUC, you initiate one by patching a deployment.  Suggest that:
- the rollout docs say how to start one.
- maybe have `kubectl rollout start` be an alias to `kubectl patch` or something.

**Comment by bgrant0607** [comment]
@erictune 
Rollouts are started by any mutation to the pod template of the Deployment. We could make `kubectl rollout start` print suggested ways to start a rollout.

cc @janetkuo

**Comment by bgrant0607** [comment]
The main feature we're missing, IMO, is `kubectl set image`. #21648

**Comment by janetkuo** [comment]
We should add more examples in `kubectl rollout --help` too.

**Comment by janetkuo** [comment]
@kubernetes/kubectl

**Comment by dshulyak** [comment]
@janetkuo What do you think about editing deployment on `kubectl rollout start` ?

**Comment by kargakis** [comment]
`kubectl rollout image` could be an alias for `kubectl set image`.

**Comment by janetkuo** [comment]
@dshulyak did you mean making `kubectl rollout start deployment` an alias for `kubectl edit deployment`?

**Comment by pwittrock** [comment]
Instead of aliasing the commands, we could just print 'did you mean <correct command>'

**Comment by smarterclayton** [comment]
Aliasing would ensure the kubectl help didn't show the older pattern in the
command lists.  I believe we have already generalized into cobra the "is
this deprecated" warning.

On Aug 22, 2016, at 7:52 PM, Phillip Wittrock <notifications@github.com>
wrote:

Instead of aliasing the commands, we could just print 'did you mean '

—
You are receiving this because you are on a team that was mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/25142#issuecomment-241586312>,
or mute the thread

**Comment by AdoHe** [comment]
yes, we have already did this.
