### ISSUE TITLE
Error deploying nodejs pod while following tutorial

### ISSUE THREAD

**Issue by shikloshi** [kubernetes/kubernetes#25167]
I'm using the hello-world tutorial for nodejs in Kubernetes and when trying to upload the pod we just created in the console I'm getting this errors: 
```error: failed to negotiate an api version; server supports: map[], client supports: map[autoscaling/v1:{} authorization.k8s.io/v1beta1:{} v1:{} metrics/v1alpha1:{} extensions/v1beta1:{} componentconfig/v1alpha1:{} batch/v1:{}]```

I'm using:
**Docker** - version 1.11.1 build 5604cbe
**Docker-machine** - version 0.6.0, build e27fb87
**Kubernetes version** - 
```
Client Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.2", GitCommit:"528f879e7d3790ea4287687ef0ab3f2a01cc2718", GitTreeState:"clean"}
```

I'm followed exactly what[ this article](http://kubernetes.io/docs/hellonode/) suggested and got stuck at the pod deployment section.

What can go wrong?

**Comment by roberthbailey** [comment]
Please re-post your question to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases.

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to similar questions, and also familiarize yourself with:
   * [the user guide](http://kubernetes.io/docs/user-guide/)
   * [the troubleshooting guide](https://github.com/kubernetes/kubernetes/blob/master/docs/troubleshooting.md)

Again, thanks for using Kubernetes.

The Kubernetes Team
