### ISSUE TITLE
rkt: Handle cadvisor's detection for rkt better

### ISSUE THREAD

**Issue by yifan-gu** [kubernetes/kubernetes#25218]
When kubelet starts and tries to connect to rkt api service.
I saw the following error messages printed by rkt api service:

```
api-service: API service running on localhost:15441...
2016/05/05 12:11:24 grpc: Server.Serve failed to create ServerTransport:  connection error: desc = "transport: write tcp 127.0.0.1:15441->127.0.0.1:39655: write: broken pipe"
```

But it doesn't seem to affect the rktnetes's functionality.

cc @euank @sjpotter

**Comment by sjpotter** [comment]
Cadvisor.  It does the net test to see if the api service is running and
then kills the connection

**Comment by sjpotter** [comment]
in containers/rkt/client.go

the issue is a workaround of grpc not failing fast if no servicel, so test with a raw net connection that something is listening on the port, but grpc then complains

ugly way to fix is to have api service run a plain listening socket that doesn't do anything on another port and we hit that to test if api-service is alive

**Comment by sjpotter** [comment]
https://github.com/google/cadvisor/pull/1269

made the timeout 1ns and removed the tcp dial.  hopefully this basically means it will try once and not timeout before one it even tries once.

**Comment by sjpotter** [comment]
my fix didn't work, I've reverted it and have a bug files against grpc  https://github.com/grpc/grpc-go/issues/668
