### ISSUE TITLE
Recreated nodes don't get PodCIDR immediately

### ISSUE THREAD

**Issue by ihmccreery** [kubernetes/kubernetes#25220]
I'm still investigating, but it looks like when we recreate nodes with the same name as an old node, the new node can't start Docker properly because it doesn't have a PodCIDR, and must wait ~5 minutes to get one.  My guess is that the NodeController doesn't hand the new node a new PodCIDR until it's been reporting itself Unhealthy for at least 5 minutes.

This is causing unnecessary (I think) disruption during node upgrades.

**Comment by spzala** [comment]
@ihmccreery hi, since it's over a year this issue was reported, a gentle touch base on if the issue is still valid with latest k8s release or close it for now, and reopen if someone hit it in future?. Unfortunately I don't have env to recreate otherwise would have tried to verify it myself. Thanks!!
