### ISSUE TITLE
Add a verbosity flag in `kubectl` commands that explains all the things that it's doing

### ISSUE THREAD

**Issue by janetkuo** [kubernetes/kubernetes#25272]
It'd be especially useful for commands like `kubectl run`, `kubectl expose`. Make `kubectl` functionality more discoverable. 

An idea from @lavalamp.

cc @kubernetes/kubectl

**Comment by janetkuo** [comment]
The flag could be `--verbose`  (default = false). It'll be good for learning. Can be used in tutorial docs.

**Comment by lavalamp** [comment]
Isn't there already a -v?

**Comment by lavalamp** [comment]
Oh, right, this was talking about adding useful things, like describing e.g. "Making a deployment for you" so you can figure out what `run` does.

**Comment by janetkuo** [comment]
@lavalamp yes, this will be different from `--v`

**Comment by kargakis** [comment]
> @lavalamp yes, this will be different from --v

Would still be confusing:/

**Comment by smarterclayton** [comment]
I would prefer if we fix glog to not be "--v" because that's crazy.  In
OpenShift we rebound it as "--loglevel" and "--logmodule" - that would then
free up -v to be useful.

Although I would question whether --verbose should really be glog.V(3) with
better formatting.

If it's important to communicate to a user what is happening on run and
expose, I think we should just show more output and then support -q.

**Comment by pmorie** [comment]
How about `--explain`
