### ISSUE TITLE
Consider a kind of Service that ignores readiness

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#25283]
This is mostly motivated by petset. Currently we create a governing service that is responsible for the network identity of each pet. The requirements of this governing service differ from a normal service in the following ways:
1. Pets have internal protocols to notice peer health, and a list of different checks (eg: http://www.cloudera.com/documentation/enterprise/5-4-x/topics/cm_ht_zookeeper_server.html). In kube, peers use DNS to communicate. So we don't want a readiness check failure to remove the pet from DNS and abruptly cut it off from the set. 
2. The "governing service" is headless so kube-proxy doesn't need to NAT the service ip.
3. Clients will not be using this Service, so it doesn't matter that unready pets show up in DNS under the svcName sub domain.

In addition to these, there's one important reason some pets need to have DNS before readiness. To provide the guarantees required to safely bootstrap a pet, we need:    
1. Pet0 starts before pet1..
2. Don't start pet1 till pet0 is running/ready
3. When pet1 starts, it sees pet0 in DNS

The easiest way to guarantee 3 today is to do one of:    
- poll in the entrypoint of pet0, till it sees itself
- poll in the init container of pet0, till it sees itself 
- poll in the init containers of pet {1..N-1} till it sees all previous pets

Third option is not a great idea because we don't know who else is supposed to exist, and for the first 2 to work with a readiness probe, we need a DNS record before the Service is ready.

**Comment by bprashanth** [comment]
I have a wip that does this through an annotation: https://github.com/kubernetes/kubernetes/pull/25284

**Comment by ravilr** [comment]
+1. this is useful even in traditional n rc's and n+1 services setup for clustered systems like 
n nodes zookeeper/etcd. Currently, there isn't a easy way to specify a readiness check in such setups, because the check in these cases would look for whether the pod member has joined the cluster successfully as follower, which wouldn't work as they discover each other through them appearing in service endpoints.  this prevents one from being able to do a rolling upgrade of cluster members safely, because there is no readiness feedback after a member pod is upgraded.

**Comment by smarterclayton** [comment]
Suggestion to hold this for alpha in 1.5, and in 1.6 spend a bit of time talking about how services are best intermixed with stateful sets (there's a lot of correlation between them).  That avoids us breaking people in 1.5 and gets a bit more think time.

**Comment by erictune** [comment]
SGTM

**Comment by bgrant0607** [comment]
See also #14848

**Comment by bprashanth** [comment]
Can we claim that if a pod is requesting pet DNS (i.e DNS name via the hostname/subdomain annotation) it never wants kube-style readiness, because it has its own internal protocol for peer health? If that's true we can get rid of the annotation and teach kubedns to always serve records for pet DNS ignoring readiness. 

My intuition tells me the answer to that question is no (i.e there exist pets that use DNS for discovery, and don't have an internal protocol for readiness, so they must use kube readiness to remove themselves from the peer group), and so the ability to toggle it on/off is useful, but I also want others to consider it.

**Comment by thockin** [comment]
I'd love to nix an annotation but I have not the expertise to answer this one.

**Comment by smarterclayton** [comment]
I don't have a strong feel either way - I'd say readiness controls on a service feel orthogonal to independent names though.

Since we don't have per port readiness, we need to consider that at some point we might need more sophistication on services or pods to control membership (unless we make label flipping easier).  I would like to see us tease apart the "leader / follower" service member concept a bit more because that might inform how we handle readiness (seems like a separate bit, but we may want atomic changes).

**Comment by bprashanth** [comment]
They are somewhat orthogonal, but you presumably only want to discover healthy peers, unless you have a way to probe every peer you discover for health. Applying this policy based on endpoint info also feels a little weird, because it's harder to create overlapping Servics with different behavior. 

I think doing the common thing always and by default is fine, as long as we can annotate our way back to what we have today, but what form would the opposite of today's Service level annotation take? i.e something that says "even though my endpoints need pet names, apply the regular rediness behavior to their DNS records"

**Comment by thockin** [comment]
How bad would it be to start without an annotation, assume that pet-names
== tolerate-unready, and see if anyone screams?  Who should we consult?

**Comment by bprashanth** [comment]
SGTM, that's also what I was prposing in the previous comment

**Comment by smarterclayton** [comment]
I guess the question is why do we even want to do that?  Why make a change
that couples logic vs leaving as is with decoupled logic?  We have people
who want unready endpoints for deployments to form gossip pools - so I
guess that counts as a use case where pet names is not coupled to unready.

Is leaving the annotation on for another release really a problem?

**Comment by bprashanth** [comment]
> We have people who want unready endpoints for deployments to form gossip pools 

That's exactly the kind of use case I was looking for, something that doesn't require pet names. I get the feeling there will be other apps but I couldn't produce an example.

**Comment by smarterclayton** [comment]
JBoss EAP uses it to form initial quorum for jgroups, which isn't a strong
consensus system.  So they use deployments and a minimum set to form an
initial quorum and deal with split brain like jgroups normally does
(infinispan has multiple consistent modes, some of which might prefer loose
pools).  Arguably smaller sets and some infinispan quorums might prefer
statefulsets, but those use cases are also more tolerant of partitions in
general.

**Comment by ravilr** [comment]
we are using tolerate-unready-endpoints annotation in our zookeeper deployments (not using pet/stateful set). Without unready endpoints, it is impossible to define a meaningful pod readiness check for zk, and without a readiness check, it is hard to do rolling updates (one ensemble member at a time).

**Comment by thockin** [comment]
The question is whether there's a need to have StatefulSets *without*
tolerate-unready-endpoints.

It sounds like maybe yes, which makes me grumpy, but I'll acquiesce if
Clayton and Prashanth say so.

**Comment by bprashanth** [comment]
isn't it enough to establish a need to tolerate-unready without statefulsets?

**Comment by smarterclayton** [comment]
I have two services pointing to my etcd stateful set - one that is
endpoints (peers) and tolerates unready.  I have one that is for naive
clients that uses readiness.

On Dec 1, 2016, at 2:59 AM, Prashanth B <notifications@github.com> wrote:

isn't it enough to establish a need to tolerate-unready without
statefulsets?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/25283#issuecomment-264103541>,
or mute the thread

**Comment by thockin** [comment]
fine.

**Comment by xiang90** [comment]
> Can we claim that if a pod is requesting pet DNS (i.e DNS name via the hostname/subdomain annotation) it never wants kube-style readiness, because it has its own internal protocol for peer health? 

Right. This is exactly why etcd operator uses the alpha `tolerate-unready-endpoint` feature. Can we make it beta in 1.8 release?

**Comment by enisoc** [comment]
@erictune @janetkuo @kow3ns We had discussed promoting `tolerate-unready-endpoints` since we need it for StatefulSet and no one has come up with anything better. We should make a decision and include it in our GA roadmap for workload controllers.

**Comment by smarterclayton** [comment]
Be sure to include sig-network

On Jul 6, 2017, at 2:40 PM, Anthony Yeh <notifications@github.com> wrote:

@erictune <https://github.com/erictune> @janetkuo
<https://github.com/janetkuo> @kow3ns <https://github.com/kow3ns> We had
discussed promoting tolerate-unready-endpoints since we need it for
StatefulSet and no one has come up with anything better. We should make a
decision and include it in our GA roadmap for workload controllers.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/25283#issuecomment-313483378>,
or mute the thread

**Comment by bigkraig** [comment]
This is also useful for ingresses that need to retain the source IP using OnlyLocal node ports, which is important for firewalling with things like Calico. The problem that we see now is when a deployment occurs, the pod is removed from the node port before the PreStop completes, which doesn't give the upstream AWS load balancer time for the pod to fail out using normal health checks.

**Comment by kow3ns** [comment]
Headless Services are a thing now
