### ISSUE TITLE
Kubelet checking pod status before CNI execution.

### ISSUE THREAD

**Issue by caseydavenport** [kubernetes/kubernetes#25281]
Seen on Kubernetes v1.2.3.

Looks like the kubelet is trying to look up a pod's IP address before the CNI plugin has actually been executed, resulting in the following cryptic message:

```
May 06 20:53:29 k8s-node-01 kubelet[5948]: E0506 20:53:29.662825    5948 manager.go:309] NetworkPlugin cni failed on the status hook for pod 'bb-1567316873-gfwfh' - invalid CIDR address: Device "eth0" does not exist.
```

Here are logs isolating the issue, showing three notable events:
1) Intent to execute CNI - "About to run with conf.Network.Type=calico"
2) The above error log - kubelet trying to read eth0 before CNI has finished executing.
3) The CNI plugin returns - "Starting Calico CNI plugin execution"

```
May 06 20:53:29 k8s-node-01 kubelet[5948]: I0506 20:53:29.636126    5948 cni.go:164] About to run with conf.Network.Type=calico, c.Path=[/opt/cni/bin /opt/calico/bin]
May 06 20:53:29 k8s-node-01 kubelet[5948]: I0506 20:53:29.636101    5948 handler.go:320] Added event &{/system.slice/docker-f32c82eb5638960c2dbe6b80c0ce829342a216e51a75fed3da5d288c8b41d647.scope 2016-05-06 20:53:29.479414223 +0000 UTC containerCreation {<nil>}}
May 06 20:53:29 k8s-node-01 kubelet[5948]: I0506 20:53:29.640113    5948 container.go:386] Start housekeeping for container "/system.slice/docker-f32c82eb5638960c2dbe6b80c0ce829342a216e51a75fed3da5d288c8b41d647.scope"
May 06 20:53:29 k8s-node-01 kubelet[5948]: E0506 20:53:29.662825    5948 manager.go:309] NetworkPlugin cni failed on the status hook for pod 'bb-1567316873-gfwfh' - invalid CIDR address: Device "eth0" does not exist.
May 06 20:53:29 k8s-node-01 kubelet[5948]: I0506 20:53:29.662938    5948 generic.go:299] PLEG: Write status for bb-1567316873-gfwfh/default: &{ID:960a5c03-13cc-11e6-95bd-0800274b98c8 Name:bb-1567316873-gfwfh Namespace:default IP: ContainerStatuses:[0xc2082e40e0]} (err: <nil>)
May 06 20:53:29 k8s-node-01 kubelet[5948]: I0506 20:53:29.663103    5948 kubelet.go:2414] SyncLoop (PLEG): "bb-1567316873-gfwfh_default(960a5c03-13cc-11e6-95bd-0800274b98c8)", event: &pleg.PodLifecycleEvent{ID:"960a5c03-13cc-11e6-95bd-0800274b98c8", Type:"ContainerStarted", Data:"2e038a28dbd2d9f5cf1ae9a6b9add3a2a0ebae8a23a9e8a5b321139e51345957"}
May 06 20:53:29 k8s-node-01 kubelet[5948]: I0506 20:53:29.668145    5948 docker.go:363] Docker Container: /calico-node is not managed by kubelet.
May 06 20:53:29 k8s-node-01 kubelet[5948]: I0506 20:53:29.668372    5948 manager.go:324] Container inspect result: {ID:f32c82eb5638960c2dbe6b80c0ce829342a216e51a75fed3da5d288c8b41d647 Created:2016-05-06 20:53:29.479414223 +0000 UTC Path:/pause Args:[] Config:0xc208268700 State:{Running:true Paused:false Restarting:false OOMKilled:false Pid:6471 ExitCode:0 Error: StartedAt:2016-05-06 20:53:29.614458341 +0000 UTC FinishedAt:0001-01-01 00:00:00 +0000 UTC} Image:8950680a606cf7a0b7916dbf4a435b35d28d75c705999847eddb5ed38eb53204 Node:<nil> NetworkSettings:0xc2083de300 SysInitPath: ResolvConfPath:/var/lib/docker/containers/f32c82eb5638960c2dbe6b80c0ce829342a216e51a75fed3da5d288c8b41d647/resolv.conf HostnamePath:/var/lib/docker/containers/f32c82eb5638960c2dbe6b80c0ce829342a216e51a75fed3da5d288c8b41d647/hostname HostsPath:/var/lib/docker/containers/f32c82eb5638960c2dbe6b80c0ce829342a216e51a75fed3da5d288c8b41d647/hosts LogPath:/var/lib/docker/containers/f32c82eb5638960c2dbe6b80c0ce829342a216e51a75fed3da5d288c8b41d647/f32c82eb5638960c2dbe6b80c0ce829342a216e51a75fed3da5d288c8b41d647-json.log Name:/k8s_POD.6059dfa2_bb-1567316873-2bbtf_default_960af9dd-13cc-11e6-95bd-0800274b98c8_ea81b7af Driver:overlay Mounts:[] Volumes:map[] VolumesRW:map[] HostConfig:0xc208dde840 ExecIDs:[] RestartCount:0 AppArmorProfile:}
May 06 20:53:29 k8s-node-01 kubelet[5948]: E0506 20:53:29.717241    5948 manager.go:309] NetworkPlugin cni failed on the status hook for pod 'bb-1567316873-2bbtf' - invalid CIDR address: Device "eth0" does not exist.
May 06 20:53:29 k8s-node-01 kubelet[5948]: I0506 20:53:29.717374    5948 generic.go:299] PLEG: Write status for bb-1567316873-2bbtf/default: &{ID:960af9dd-13cc-11e6-95bd-0800274b98c8 Name:bb-1567316873-2bbtf Namespace:default IP: ContainerStatuses:[0xc2082e4540]} (err: <nil>)
May 06 20:53:29 k8s-node-01 kubelet[5948]: I0506 20:53:29.717449    5948 kubelet.go:2414] SyncLoop (PLEG): "bb-1567316873-2bbtf_default(960af9dd-13cc-11e6-95bd-0800274b98c8)", event: &pleg.PodLifecycleEvent{ID:"960af9dd-13cc-11e6-95bd-0800274b98c8", Type:"ContainerStarted", Data:"f32c82eb5638960c2dbe6b80c0ce829342a216e51a75fed3da5d288c8b41d647"}
May 06 20:53:29 k8s-node-01 kubelet[5948]: I0506 20:53:29.719339    5948 docker.go:363] Docker Container: /calico-node is not managed by kubelet.
May 06 20:53:29 k8s-node-01 kubelet[5948]: 2016-05-06 20:53:29,929 6507 [default/bb-1567316873-gfwfh] INFO Starting Calico CNI plugin execution
```

I haven't quite figured out which bit of the kubelet is actually jumping the gun here.  It seems benign (the pod still gets set up) yet quite confusing.

We should also fix the bit of CNI code that's trying to parse "Device eth0 does not exist" as an IP address.

**Comment by yujuhong** [comment]
Yes, there is a race condition because kubelet has a component that periodically polls docker to detect new containers (or any container state changes). In this case, you create the infra container first, and then call the cni plugin to setup the network. Between this two operations, kubelet detected this new container and tried to gather more information about the "pod" this container belongs to. I think it's safe to ignore it for now (albeit it's a bit confusing).

**Comment by yujuhong** [comment]
@caseydavenport do you want to fix the parsing issue?

**Comment by caseydavenport** [comment]
@yujuhong Yep, happy to do that. 

Agree that the race condition is safe to ignore.  I have encountered a number of users who thought there was something wrong with their cluster because of the message, so a fix for the log would definitely improve user experience.  I can take a look at that as well when I get a chance.

**Comment by yujuhong** [comment]
> Agree that the race condition is safe to ignore. I have encountered a number of users who thought there was something wrong with their cluster because of the message, so a fix for the log would definitely improve user experience. I can take a look at that as well when I get a chance.

+1 for better logging, e..g, we can just log that the network plugin is not ready yet.

**Comment by gaord** [comment]
It looks like what I encountered couple days on calico with kubernetes. I am bootstrapping my k8s cluster with static pods of etched, apiserver, scheduler etc with calico configure as cni. I  see similar error:
`8月 22 19:25:27 dscn1 kubelet[6022]: E0822 19:25:27.673132    6022 docker_manager.go:345] NetworkPlugin cni failed on the status hook for pod 'etcd-server-dscn1' - Unexpected command output Device "eth0" `
Any insights on this issues? Many thanks!

detailed logs as below:
`8月 22 19:25:29 dscn1 kubelet[6022]: I0822 19:25:29.080048    6022 helpers.go:101] Unable to get network stats from pid 6256: couldn't read network stats: failure opening /proc/6256/net/dev: open /proc/62
8月 22 19:25:29 dscn1 kubelet[6022]: I0822 19:25:29.002429    6022 docker_manager.go:2288] checking backoff for container "etcd-container" in pod "etcd-server-dscn1"
8月 22 19:25:28 dscn1 kubelet[6022]: I0822 19:25:28.701783    6022 kubelet.go:2884] Recording NodeHasSufficientMemory event message for node dscn1
8月 22 19:25:28 dscn1 kubelet[6022]: I0822 19:25:28.701757    6022 kubelet.go:2884] Recording NodeHasSufficientDisk event message for node dscn1
8月 22 19:25:28 dscn1 kubelet[6022]: I0822 19:25:28.698681    6022 kubelet.go:2561] SyncLoop (PLEG): "etcd-server-dscn1_default(db20a42d143f44bd830a5ba70cde0785)", event: &pleg.PodLifecycleEvent{ID:"db20a
8月 22 19:25:28 dscn1 kubelet[6022]: I0822 19:25:28.234506    6022 helpers.go:101] Unable to get network stats from pid 6211: couldn't read network stats: failure opening /proc/6211/net/dev: open /proc/62
8月 22 19:25:27 dscn1 kubelet[6022]: I0822 19:25:27.676741    6022 kubelet.go:2561] SyncLoop (PLEG): "etcd-server-dscn1_default(db20a42d143f44bd830a5ba70cde0785)", event: &pleg.PodLifecycleEvent{ID:"db20a
8月 22 19:25:27 dscn1 kubelet[6022]: I0822 19:25:27.676700    6022 kubelet.go:2561] SyncLoop (PLEG): "etcd-server-dscn1_default(db20a42d143f44bd830a5ba70cde0785)", event: &pleg.PodLifecycleEvent{ID:"db20a
8月 22 19:25:27 dscn1 kubelet[6022]: with error: exit status 1
8月 22 19:25:27 dscn1 kubelet[6022]: E0822 19:25:27.673132    6022 docker_manager.go:345] NetworkPlugin cni failed on the status hook for pod 'etcd-server-dscn1' - Unexpected command output Device "eth0" 
8月 22 19:25:27 dscn1 kubelet[6022]: I0822 19:25:27.277632    6022 kube_docker_client.go:295] Stop pulling image "192.168.1.45:5000/pause:2.0": "Status: Downloaded newer image for 192.168.1.45:5000/pause:
8月 22 19:25:27 dscn1 kubelet[6022]: I0822 19:25:27.221666    6022 docker.go:185] Pulling image 192.168.1.45:5000/pause:2.0 without credentials
8月 22 19:25:27 dscn1 kubelet[6022]: I0822 19:25:27.221516    6022 provider.go:119] Refreshing cache for provider: *credentialprovider.defaultDockerConfigProvider
8月 22 19:25:27 dscn1 kubelet[6022]: W0822 19:25:27.220566    6022 docker_manager.go:1380] No ref for pod '"cd6293a861a8d30cb9aa6070a2e42c6d7e9833d50359b7448d16ca3d5cd8d77c default/etcd-server-dscn1"'
8月 22 19:25:27 dscn1 kubelet[6022]: I0822 19:25:27.220508    6022 docker_manager.go:1374] Container "cd6293a861a8d30cb9aa6070a2e42c6d7e9833d50359b7448d16ca3d5cd8d77c default/etcd-server-dscn1" exited aft
8月 22 19:25:27 dscn1 kubelet[6022]: I0822 19:25:27.171942    6022 docker_manager.go:1335] Killing container "cd6293a861a8d30cb9aa6070a2e42c6d7e9833d50359b7448d16ca3d5cd8d77c default/etcd-server-dscn1" wi
8月 22 19:25:26 dscn1 kubelet[6022]: I0822 19:25:26.868412    6022 docker_manager.go:1746] Need to restart pod infra container for "etcd-server-dscn1_default(db20a42d143f44bd830a5ba70cde0785)" because it 
8月 22 19:25:26 dscn1 kubelet[6022]: I0822 19:25:26.768949    6022 operation_executor.go:720] MountVolume.SetUp succeeded for volume "kubernetes.io/host-path//etc/openssl" (spec.Name: "etcopenssl") pod "d
8月 22 19:25:26 dscn1 kubelet[6022]: I0822 19:25:26.768922    6022 operation_executor.go:720] MountVolume.SetUp succeeded for volume "kubernetes.io/host-path//usr/lib/ssl" (spec.Name: "usrlibssl") pod "db
8月 22 19:25:26 dscn1 kubelet[6022]: I0822 19:25:26.768934    6022 operation_executor.go:720] MountVolume.SetUp succeeded for volume "kubernetes.io/host-path//usr/ssl" (spec.Name: "usrssl") pod "db20a42d1
8月 22 19:25:26 dscn1 kubelet[6022]: I0822 19:25:26.768936    6022 operation_executor.go:720] MountVolume.SetUp succeeded for volume "kubernetes.io/host-path//etc/ssl" (spec.Name: "etcssl") pod "db20a42d1
8月 22 19:25:26 dscn1 kubelet[6022]: I0822 19:25:26.768916    6022 operation_executor.go:720] MountVolume.SetUp succeeded for volume "kubernetes.io/host-path//usr/share/ssl" (spec.Name: "usrsharessl") pod
8月 22 19:25:26 dscn1 kubelet[6022]: I0822 19:25:26.768907    6022 operation_executor.go:720] MountVolume.SetUp succeeded for volume "kubernetes.io/host-path//var/etcd/data" (spec.Name: "varetcd") pod "db
8月 22 19:25:26 dscn1 kubelet[6022]: I0822 19:25:26.768894    6022 operation_executor.go:720] MountVolume.SetUp succeeded for volume "kubernetes.io/host-path//etc/pki/tls" (spec.Name: "etcpkitls") pod "db
8月 22 19:25:26 dscn1 kubelet[6022]: I0822 19:25:26.768872    6022 operation_executor.go:720] MountVolume.SetUp succeeded for volume "kubernetes.io/host-path//usr/local/openssl" (spec.Name: "usrlocalopens
8月 22 19:25:26 dscn1 kubelet[6022]: I0822 19:25:26.768854    6022 operation_executor.go:720] MountVolume.SetUp succeeded for volume "kubernetes.io/host-path//var/ssl" (spec.Name: "varssl") pod "db20a42d1
8月 22 19:25:26 dscn1 kubelet[6022]: I0822 19:25:26.768863    6022 reconciler.go:253] MountVolume operation started for volume "kubernetes.io/host-path//etc/pki/tls" (spec.Name: "etcpkitls") to pod "db20a
8月 22 19:25:26 dscn1 kubelet[6022]: I0822 19:25:26.768842    6022 reconciler.go:253] MountVolume operation started for volume "kubernetes.io/host-path//etc/openssl" (spec.Name: "etcopenssl") to pod "db20
8月 22 19:25:26 dscn1 kubelet[6022]: I0822 19:25:26.768811    6022 reconciler.go:253] MountVolume operation started for volume "kubernetes.io/host-path//usr/ssl" (spec.Name: "usrssl") to pod "db20a42d143f
8月 22 19:25:26 dscn1 kubelet[6022]: I0822 19:25:26.768793    6022 reconciler.go:253] MountVolume operation started for volume "kubernetes.io/host-path//etc/ssl" (spec.Name: "etcssl") to pod "db20a42d143f
8月 22 19:25:26 dscn1 kubelet[6022]: I0822 19:25:26.768773    6022 reconciler.go:253] MountVolume operation started for volume "kubernetes.io/host-path//usr/local/openssl" (spec.Name: "usrlocalopenssl") t
8月 22 19:25:26 dscn1 kubelet[6022]: I0822 19:25:26.768736    6022 reconciler.go:253] MountVolume operation started for volume "kubernetes.io/host-path//usr/lib/ssl" (spec.Name: "usrlibssl") to pod "db20a
8月 22 19:25:26 dscn1 kubelet[6022]: I0822 19:25:26.768717    6022 reconciler.go:253] MountVolume operation started for volume "kubernetes.io/host-path//var/ssl" (spec.Name: "varssl") to pod "db20a42d143f
8月 22 19:25:26 dscn1 kubelet[6022]: I0822 19:25:26.768697    6022 reconciler.go:253] MountVolume operation started for volume "kubernetes.io/host-path//usr/share/ssl" (spec.Name: "usrsharessl") to pod "d
8月 22 19:25:26 dscn1 kubelet[6022]: I0822 19:25:26.768667    6022 reconciler.go:253] MountVolume operation started for volume "kubernetes.io/host-path//var/etcd/data" (spec.Name: "varetcd") to pod "db20a
8月 22 19:25:26 dscn1 kubelet[6022]: I0822 19:25:26.668462    6022 reconciler.go:179] VerifyControllerAttachedVolume operation started for volume "kubernetes.io/host-path//etc/pki/tls" (spec.Name: "etcpki
8月 22 19:25:26 dscn1 kubelet[6022]: I0822 19:25:26.668403    6022 reconciler.go:179] VerifyControllerAttachedVolume operation started for volume "kubernetes.io/host-path//etc/openssl" (spec.Name: "etcope
8月 22 19:25:26 dscn1 kubelet[6022]: I0822 19:25:26.668345    6022 reconciler.go:179] VerifyControllerAttachedVolume operation started for volume "kubernetes.io/host-path//usr/ssl" (spec.Name: "usrssl") p
8月 22 19:25:26 dscn1 kubelet[6022]: I0822 19:25:26.668310    6022 reconciler.go:179] VerifyControllerAttachedVolume operation started for volume "kubernetes.io/host-path//etc/ssl" (spec.Name: "etcssl") p
8月 22 19:25:26 dscn1 kubelet[6022]: I0822 19:25:26.668269    6022 reconciler.go:179] VerifyControllerAttachedVolume operation started for volume "kubernetes.io/host-path//usr/local/openssl" (spec.Name: "
8月 22 19:25:26 dscn1 kubelet[6022]: I0822 19:25:26.668237    6022 reconciler.go:179] VerifyControllerAttachedVolume operation started for volume "kubernetes.io/host-path//usr/lib/ssl" (spec.Name: "usrlib
8月 22 19:25:26 dscn1 kubelet[6022]: I0822 19:25:26.668220    6022 reconciler.go:179] VerifyControllerAttachedVolume operation started for volume "kubernetes.io/host-path//var/ssl" (spec.Name: "varssl") p
8月 22 19:25:26 dscn1 kubelet[6022]: I0822 19:25:26.668204    6022 reconciler.go:179] VerifyControllerAttachedVolume operation started for volume "kubernetes.io/host-path//usr/share/ssl" (spec.Name: "usrs
8月 22 19:25:26 dscn1 kubelet[6022]: I0822 19:25:26.668123    6022 reconciler.go:179] VerifyControllerAttachedVolume operation started for volume "kubernetes.io/host-path//var/etcd/data" (spec.Name: "vare
8月 22 19:25:26 dscn1 kubelet[6022]: I0822 19:25:26.567941    6022 kubelet.go:2884] Recording NodeHasSufficientMemory event message for node dscn1
8月 22 19:25:26 dscn1 kubelet[6022]: I0822 19:25:26.567919    6022 kubelet.go:2884] Recording NodeHasSufficientDisk event message for node dscn1
8月 22 19:25:26 dscn1 kubelet[6022]: I0822 19:25:26.564313    6022 kubelet.go:2561] SyncLoop (PLEG): "etcd-server-dscn1_default(db20a42d143f44bd830a5ba70cde0785)", event: &pleg.PodLifecycleEvent{ID:"db20a
8月 22 19:25:26 dscn1 kubelet[6022]: I0822 19:25:26.564295    6022 kubelet.go:2561] SyncLoop (PLEG): "etcd-server-dscn1_default(db20a42d143f44bd830a5ba70cde0785)", event: &pleg.PodLifecycleEvent{ID:"db20a
8月 22 19:25:26 dscn1 kubelet[6022]: I0822 19:25:26.564260    6022 kubelet.go:2561] SyncLoop (PLEG): "etcd-server-dscn1_default(db20a42d143f44bd830a5ba70cde0785)", event: &pleg.PodLifecycleEvent{ID:"db20a
8月 22 19:25:26 dscn1 kubelet[6022]: I0822 19:25:26.564205    6022 kubelet.go:2884] Recording NodeHasSufficientMemory event message for node dscn1
8月 22 19:25:26 dscn1 kubelet[6022]: I0822 19:25:26.564164    6022 kubelet.go:2884] Recording NodeHasSufficientDisk event message for node dscn1
8月 22 19:25:26 dscn1 kubelet[6022]: I0822 19:25:26.560168    6022 kubelet.go:2534] SyncLoop (ADD, "file"): "etcd-server-dscn1_default(db20a42d143f44bd830a5ba70cde0785)"
8月 22 19:25:21 dscn1 kubelet[6022]: I0822 19:25:21.580915    6022 manager.go:286] Recovery completed
8月 22 19:25:21 dscn1 kubelet[6022]: I0822 19:25:21.571934    6022 manager.go:281] Starting recovery of all containers
8月 22 19:25:21 dscn1 kubelet[6022]: I0822 19:25:21.569303    6022 oomparser.go:185] oomparser using systemd
8月 22 19:25:21 dscn1 kubelet[6022]: I0822 19:25:21.568176    6022 manager.go:1072] Started watching for new ooms in manager
8月 22 19:25:21 dscn1 kubelet[6022]: I0822 19:25:21.567516    6022 factory.go:86] Registering Raw factory
8月 22 19:25:21 dscn1 kubelet[6022]: I0822 19:25:21.566853    6022 factory.go:54] Registering systemd factory
8月 22 19:25:21 dscn1 kubelet[6022]: E0822 19:25:21.566843    6022 manager.go:240] Registration of the rkt container factory failed: unable to communicate with Rkt api service: rkt: cannot tcp Dial rkt ap
8月 22 19:25:21 dscn1 kubelet[6022]: I0822 19:25:21.566813    6022 factory.go:228] Registering Docker factory
8月 22 19:25:21 dscn1 kubelet[6022]: I0822 19:25:21.560120    6022 volume_manager.go:216] Starting Kubelet Volume Manager
8月 22 19:32:05 dscn1 kubelet[6942]: I0822 19:32:05.286816    6942 kubelet.go:384] Hairpin mode set to "hairpin-veth"
8月 22 19:32:05 dscn1 kubelet[6942]: W0822 19:32:05.286803    6942 kubelet.go:561] Hairpin mode set to "promiscuous-bridge" but configureCBR0 is false, falling back to "hairpin-veth"
8月 22 19:32:05 dscn1 kubelet[6942]: I0822 19:32:05.286747    6942 file.go:47] Watching path "/etc/kubernetes/manifests"
8月 22 19:32:05 dscn1 kubelet[6942]: I0822 19:32:05.286733    6942 server.go:758] Adding manifest file: /etc/kubernetes/manifests
8月 22 19:32:05 dscn1 kubelet[6942]: W0822 19:32:05.286706    6942 server.go:660] No api server defined - no events will be sent to API server.
8月 22 19:32:05 dscn1 kubelet[6942]: I0822 19:32:05.285255    6942 server.go:382] Using root directory: /var/lib/kubelet
8月 22 19:32:05 dscn1 kubelet[6942]: I0822 19:32:05.284376    6942 manager.go:198] Version: {KernelVersion:3.10.0-327.el7.x86_64 ContainerOsVersion:Red Hat Enterprise Linux Server 7.2 (Maipo) DockerVersio
8月 22 19:32:05 dscn1 kubelet[6942]: 5 Mtu:1500}] Topology:[{Id:0 Memory:137318232064 Cores:[{Id:0 Threads:[0 12] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 
8月 22 19:32:05 dscn1 kubelet[6942]: I0822 19:32:05.283726    6942 manager.go:192] Machine: {NumCores:24 CpuFrequency:3200000 MemoryCapacity:270191796224 MachineID:fafcaf3438f4415286d15cc284fb0627 SystemU
8月 22 19:32:05 dscn1 kubelet[6942]: I0822 19:32:05.279701    6942 fs.go:139] Filesystem partitions: map[/dev/mapper/rhel-root:{mountpoint:/ major:253 minor:0 fsType: blockSize:0} /dev/sda2:{mountpoint:/b
8月 22 19:32:05 dscn1 kubelet[6942]: W0822 19:32:05.275527    6942 manager.go:146] unable to connect to Rkt api service: rkt: cannot tcp Dial rkt api service: dial tcp [::1]:15441: getsockopt: connection 
8月 22 19:32:05 dscn1 kubelet[6942]: I0822 19:32:05.267384    6942 manager.go:138] cAdvisor running in container: "/"
8月 22 19:32:05 dscn1 kubelet[6942]: I0822 19:32:05.260276    6942 docker.go:327] Start docker client with request timeout=2m0s
8月 22 19:32:05 dscn1 systemd[1]: Starting Kubernetes Kubelet...
8月 22 19:32:05 dscn1 systemd[1]: Started Kubernetes Kubelet.
8月 22 19:32:05 dscn1 systemd[1]: Stopping Kubernetes Kubelet...
`
The yaml file is:
`apiVersion: v1
kind: Pod
metadata:
  name: k8s-etcd
  namespace: default-system
spec:
    containers:
    - name: etcd-container
      image: 192.168.1.45:5000/etcd:3.0.3
      command:
        - "/usr/local/bin/etcd"
        - "--name=calico-etcd"
        - "--data-dir=/var/etcd/calico-data"
        - "--advertise-client-urls=http://192.168.1.45:6666"
        - "--listen-client-urls=http://0.0.0.0:6666"
        - "--listen-peer-urls=http://0.0.0.0:6660"
      securityContext:
        privileged: true
      ports:
      - name: clientport
        containerPort: 6666
        hostPort: 6666
      volumeMounts:
        - mountPath: /var/etcd
          name: varetcd
    volumes:
      - name: "varetcd"
        hostPath:
          path: "/mnt/master-pd/var/etcd"`

**Comment by KIVagant** [comment]
We got similar issue today for Kubernetes 1.5.5:

```Nov 22 17:45:59 ip-10-132-85-103 kubelet[1208]: I1122 17:45:59.493424    1208 kubelet.go:1781] SyncLoop (ADD, "api"): "kube-dns-autoscaler-2813114833-hmszd_kube-system(fffe3c45-cfac-11e7-aa7f-0eaf22284046)"
Nov 22 17:46:00 ip-10-132-85-103 kubelet[1208]: I1122 17:46:00.094710    1208 docker_manager.go:1970] Need to restart pod infra container for "kube-dns-autoscaler-2813114833-hmszd_kube-system(fffe3c45-cfac-11e7-aa7f-0eaf22284046)" because it is not found
Nov 22 17:46:00 ip-10-132-85-103 kubelet[1208]: E1122 17:46:00.734414    1208 docker_manager.go:372] NetworkPlugin cni failed on the status hook for pod 'kube-dns-autoscaler-2813114833-hmszd' - Unexpected command output Device "eth0" does not exist.
Nov 22 17:46:00 ip-10-132-85-103 kubelet[1208]: I1122 17:46:00.735110    1208 kubelet.go:1816] SyncLoop (PLEG): "kube-dns-autoscaler-2813114833-hmszd_kube-system(fffe3c45-cfac-11e7-aa7f-0eaf22284046)", event: &pleg.PodLifecycleEvent{ID:"fffe3c45-cfac-11e7-aa7f-0eaf22284046", Type:"ContainerStarted", Data:"28f0aade1b1d8f5ccf432f67988b226d0f561cd0b1486a6fe1099b9a2542295d"}
```

Restarting docker and kubelet services didn't help us. But after we killed one of the `weave-net-*` pods all other pods were fixed.
