### ISSUE TITLE
Cluster Bootstrap Script with ETCD V3 Servers

### ISSUE THREAD

**Issue by hongchaodeng** [kubernetes/kubernetes#25286]
The current cluster bootstrap script (GCE specifically) pulls etcd v2 image from gcr.

As we are moving towards etcd v3 w.r.t. more comprehensive testing, we want to have the capability to bootstrap a cluster talking with etcd v3 servers. This includes two parts:
1. Configure kube-apiserver by specifying "--storage-backend" to "etcd3" and also other corresponding parameters if needed.
2. Start etcd3 servers as part of the master components or standalone instances.

Attack plan:
- For first step, we are planning to make it work on GCE and runs e2e tests against that.
- We are going to make sure all interested parties have it work on more use cases.

**Comment by hongchaodeng** [comment]
xref: #22448

**Comment by luxas** [comment]
cc @luxas

**Comment by wojtek-t** [comment]
Starting with GCE sgtm. I'm happy to help with reviews etc.

**Comment by hongchaodeng** [comment]
@roberthbailey 
Can cluster-ops team help on GCE side? We have passed e2e tests with [etcd-v3.0.0-beta.0](https://github.com/coreos/etcd/releases/tag/v3.0.0-beta.0).

The [salt command](https://github.com/kubernetes/kubernetes/blob/54933902b23cb9a5cc322c17f6c266a41470bb61/cluster/saltbase/salt/etcd/etcd.manifest#L19-L23) are the same.

What needs to change?
- Add a etcd3 salt file. It should be mostly the same as [etcd.manifest](https://github.com/kubernetes/kubernetes/blob/54933902b23cb9a5cc322c17f6c266a41470bb61/cluster/saltbase/salt/etcd/etcd.manifest) except ["image"](https://github.com/kubernetes/kubernetes/blob/54933902b23cb9a5cc322c17f6c266a41470bb61/cluster/saltbase/salt/etcd/etcd.manifest#L13) field. We can provide [quay repo](https://quay.io/repository/coreos/etcd?tag=v3.0.0-beta.0), make a GCR repo, or make this field configuration.
- Config option. We need an option to switch to etcd3 backed storage. Probably need to configure image name too.

Again, the rest of it should be the same.

**Comment by mikedanese** [comment]
Is etcd v3.0.0 backwards compatible for etcd v2? Why not just upgrade etcd? What is the motivation for adding this as a configuration option?

**Comment by xiang90** [comment]
@mikedanese v3.0.0 has a new set of APIs and a new storage engine. We can just upgrade etcd2 -> etcd3, however then k8s will still use the old API and the old engine. We need to explicitly tell k8s to use new API of etcd.

**Comment by mikedanese** [comment]
Ok IIUC then you don't need a new etcd3 salt file. Just upgrade the build tag in the old ones. That should be easy.

> We need to explicitly tell k8s to use new API of etcd.

Is this a flag on the apiserver? Can the apiserver check if the new API is enabled and use it preferentially?

**Comment by mikedanese** [comment]
I guess I don't understand why this should be a configuration option in kube-up and not just enabled.

**Comment by xiang90** [comment]
@mikedanese 

> Is this a flag on the apiserver? Can the apiserver check if the new API is enabled and use it preferentially?

Potentially yes. But the v3 also has a new engine. User needs to migrate data. So a user might have actual data still on the old storage engine. Then k8s cannot automatically switch to it. Also user might still want to use v2 at least for now, since v3 is less stable when both v2 and v3 engines are empty. Eventually, we can detect where the data is and help user with best choice.

**Comment by hongchaodeng** [comment]
> Is this a flag on the apiserver? 

It's "[--storage-backend=etcd3](https://github.com/kubernetes/kubernetes/blob/2ffa3b4586923fbeccfac18777cdb09398b20490/pkg/genericapiserver/server_run_options.go#L204)" for kube-apiserver.

**Comment by mikedanese** [comment]
Ok, I understand now. What is the process for migration? @wojtek-t have you thought about how to upgrade clusters in gce?

**Comment by roberthbailey** [comment]
@xiang90 -- given that we are 9 days away from feature complete for the 1.3 release, I'm a bit concerned with switching the storage implementation now if we don't have a flushed out plan for data migration. Do you think it'd be reasonable to switch to etcd3 right after we branch so that we have 3-4 months between 1.3 and 1.4 to soak test and automate the upgrade process?

**Comment by xiang90** [comment]
@roberthbailey 

I think it is reasonable to say we support etcd3 for testing at least. Or in another word, we want people to test etcd3 as a new backend for k8s. It is the path to go in the future and we have medium goals to optimize etcd3 backend part code + api server layer. 

I agree with you that we need to add soak testing inside k8s before we can say etcd3 is a stable backend and suggest people to use it by default.  And this is where we need help from testing infra experts.

For migration plan, hongchao and I are working on it, we already got something that should work. We will share it next week.

**Comment by wojtek-t** [comment]
>
Ok, I understand now. What is the process for migration? @wojtek-t have you thought about how to upgrade clusters in gce?

@mikedanese We were discussing it at some point and my plan about it was to:
- have a script that is converting data from old format to new format
- make this script idempotent (we need to be careful what that exactly means though)
- then change basically the image of apiserver to contain also this script and change the commandline for starting apiserver to do: "run this script && start apiserver"

That was my plan, but to be honest, I didn't have much time to think about it deeper. So if you have any suggestions how to improve it, just let me know.

>
@xiang90 -- given that we are 9 days away from feature complete for the 1.3 release, I'm a bit concerned with switching the storage implementation now if we don't have a flushed out plan for data migration. Do you think it'd be reasonable to switch to etcd3 right after we branch so that we have 3-4 months between 1.3 and 1.4 to soak test and automate the upgrade process?

@roberthbailey @xiang90 - we have basically 6-7 working days before freeze. IIUC, we don't even have the migration code under review, not even talking about having it really tested.

So my current thinking about is that we should definitely leave "etcd2" as a default backend storate in 1.3 release.
However, I think it's completely fine to have some flag in kube-up (or sth like that) that will enable users to start a cluster with "etcd3" as a backend storage if they want. But we need to be explicit that this is experimental feature in 1.3 and 1.3 we are not really supporting migration.

What do you think?

**Comment by roberthbailey** [comment]
I guess my question is whether the configuration complexity that we would introduce is worth it to add it as an experimental feature to 1.3. Or are we better off just enabling it as the default right after we cut 1.3 and telling people that if they want etcd3 they have to build from HEAD of master branch or grab a 1.4 alpha release (which would be available in <2 weeks after the PR gets merged). 

@mikedanese asked above, and I tend to agree, that if we want to switch to etcd3 we should just do it rather than adding the configuration complexity of being able to switch between different versions. Doing it right after a release branch is cut gives us the maximum amount of time to soak and perform upgrade testing from etcd2 -> etcd3 so that we are confident that we have a good upgrade story when 1.4 gets released.

**Comment by hongchaodeng** [comment]
I'm not sure about the release. But let me answer the "config complexity".

How is it complex? The simplest way is to just make "[image](https://github.com/kubernetes/kubernetes/blob/54933902b23cb9a5cc322c17f6c266a41470bb61/cluster/saltbase/salt/etcd/etcd.manifest#L13)" field configurable.

**Comment by xiang90** [comment]
@mikedanese @roberthbailey I think all we want is to give the users an easy way to spin up a k8s cluster with etcd3 as its backend as an option easily. We can explicitly this is not production ready, but at least then people can help us test it easily or put some non-production jobs on it.

**Comment by timothysc** [comment]
We will likely option enable as an experimental feature at this point.
There needs to be a heck of a lot of vetting involved still, now that kube is in the wild. 

/cc @detiber @eparis @smarterclayton @jeremyeder

**Comment by timothysc** [comment]
Closing this now that there is only 1 outstanding PR to enable by default.
