### ISSUE TITLE
Example of NFS volume doesn't working

### ISSUE THREAD

**Issue by DarkSkull91** [kubernetes/kubernetes#25304]
Hi guys! I've just run nfs example, but all I got is this error:
```
[root@kubernetes-master kubernetes]# kubectl create -f examples/nfs/nfs-server-rc.yaml
The ReplicationController "nfs-server" is invalid.
spec.template.spec.containers[0].securityContext.privileged: forbidden '<*>(0xc20952c6f8)true'
```

why?

**Comment by roberthbailey** [comment]
Please re-post your question to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases.

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to similar questions, and also familiarize yourself with:
   * [the user guide](http://kubernetes.io/docs/user-guide/)
   * [the troubleshooting guide](https://github.com/kubernetes/kubernetes/blob/master/docs/troubleshooting.md)

Again, thanks for using Kubernetes.

The Kubernetes Team
