### ISSUE TITLE
[Redis example] Cannot failover

### ISSUE THREAD

**Issue by fatduo** [kubernetes/kubernetes#25327]
Hi,
After trying redis example via k8s multiple times, it still cannot fail over.

Sentinel log:
> 15:X 09 May 02:17:57.893 # +sdown slave 172.16.29.0:6379 172.16.29.0 6379 @ mymaster 172.16.14.3 6379
15:X 09 May 02:17:57.894 # +sdown slave 172.16.77.0:6379 172.16.77.0 6379 @ mymaster 172.16.14.3 6379

Redis master replication info:

> role:master
connected_slaves:2
slave0:ip=172.16.77.0,port=6379,state=online,offset=193495,lag=0
slave1:ip=172.16.29.0,port=6379,state=online,offset=193495,lag=0

But the slave pods ip (using kubectl describe) are 172.16.77.3 and 172.16.29.6

The slaves service got the wrong ip address and send them to the master, so the sentinels cannot connect to them.

PLS help me that why the slaves service got the wrong ip address?

**Comment by fatduo** [comment]
When redis master accept a socket connection from slave, it use
> int conn = accept(server_sockfd, (struct sockaddr*)&client_addr, &length);
printf("IP: %s \n", inet_ntoa(client_addr.sin_addr));

to get the slave ip address.

Unfortunately, in k8s env, it get the flannel ip instead of the pod ip.

**Comment by fatduo** [comment]
cc @thockin @wernight @mikedanese

**Comment by fabioy** [comment]
My apologies, but support responses may be a bit slow.

Please consider re-posting your question to [stackoverflow]
(http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support
are posted so that we can improve our efficiency in responding to your requests,
and to make it easier for you to find answers to frequently asked questions and
how to address common use cases.

We regularly see messages posted in multiple forums, with the full response
thread only in one place or, worse, spread across multiple forums. Also, the
large volume of support issues on github is making it difficult for us to use
issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to
ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to
similar questions, and also familiarize yourself with:

  * [user guide](http://kubernetes.io/docs/user-guide/)
  * [troubleshooting guide](http://kubernetes.io/docs/admin/cluster-troubleshooting/)

Again, thanks for using Kubernetes.

The Kubernetes Team
