### ISSUE TITLE
Image: [......] is not ready on the node

### ISSUE THREAD

**Issue by DeeBrad** [kubernetes/kubernetes#25339]
When running `kubectl rolling-update platform-worker-beat --image=[image_name]` the pod status reads:

 ` 0/1       Image: [image_name] is not ready on the node   0          2m
`

I have tried deleting the pod, but when the replication controller spins it back up, the same status is shown. 

We're also getting an error in the event log:

`Error syncing pod, skipping: API error (500): Cannot start container a34f52b32b16a0eff707859a0e9430f7030112dc4c044c2eb795ae86be25039c: [8] System error: Activation of org.freedesktop.systemd1 timed out`

We're using version v1.0.1 of Kubernetes. I'm not sure what other information would help, but am more than happy to provide it if needed. I am very new to using Kubernetes, so any help or info would be greatly appreciated!

**Comment by fabioy** [comment]
Version 1.0.1 is rather old and that error may indicate a node setup issue. Please consider trying the latest version, 1.2.4, with the examples in the docs.

Also, please post future question(s) to [stackoverflow]
(http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support
are posted so that we can improve our efficiency in responding to your requests,
and to make it easier for you to find answers to frequently asked questions and
how to address common use cases.

We regularly see messages posted in multiple forums, with the full response
thread only in one place or, worse, spread across multiple forums. Also, the
large volume of support issues on github is making it difficult for us to use
issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to
ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to
similar questions, and also familiarize yourself with:

  * [user guide](http://kubernetes.io/docs/user-guide/)
  * [troubleshooting guide](http://kubernetes.io/docs/admin/cluster-troubleshooting/)

Again, thanks for using Kubernetes.

The Kubernetes Team
