### ISSUE TITLE
Surface better error when user directly specifies impossible mount in pod spec

### ISSUE THREAD

**Issue by therc** [kubernetes/kubernetes#25368]
and keeps it to itself. Witness:

```
W0509 20:06:57.396026     994 aws_util.go:177] Retrying attach for EBS Disk "vol-XXXXXXXX" (retry count=5).
E0509 20:06:57.512043     994 aws_util.go:182] Error attaching PD "vol-XXXXXXX": Error attaching EBS volume: InvalidVolume.ZoneMismatch: The volume 'vol-XXXXXXX' is not in the same availability zone as instance 'i-ZZZZZZZZ'
```

This is user error, but
1. there's no point in retrying, since the EBS is not going to jump zones
2. worst of all, it doesn't show anything in events (it gets reported as "Container creating"). You need to ssh to the node and look at kubelet logs

**Comment by therc** [comment]
I know that this is much more complicated than it seems at first and it's probably not easy to tell an error that can be retried from one that never should be, but we should at least propagate the real problem to the user (in my case, they couldn't get at the kubelet logs and I had to tell them). That, in itself, might be a limitation of the current APIs, in which case we should escalate upstream.

**Comment by thockin** [comment]
@jingxu97 if you get through the rest

**Comment by thenayr** [comment]
I just ran into this same issue on a multi-AZ deployment.   

Just another data point on how to debug this,  even though the pod shows as `ContainerCreating`,  if you run a `describe` on the pod ID,  you should see the volume issue show up in the events there..

**Comment by noose** [comment]
What about this one? If we can't use AWSElasticBlockStore in multi-az deployment then Kubernetes is not production ready :(

**Comment by justinsb** [comment]
@noose let's keep marketing statements out of the issue tracker ;-)  You can use EBS volumes with persistent volumes in multiple AZs today, and they will be scheduled correctly.  With PetSets in 1.3, PetSets automatically create EBS volumes span the available zones and everything is scheduled correctly.

This issue is about better surfacing the error for a particular case: when specifying an EBS volume directly in the pod spec.  The zone-aware scheduler doesn't handle that case; we want to encourage persistent volumes instead.

For multi-AZ clusters, we recommend using persistent volumes & persistent volume claims: http://kubernetes.io/docs/admin/multiple-zones/

**Comment by justinsb** [comment]
@noose that's great.  Be sure to check out the dynamic volume stuff as well if you haven't already seen it (it's on that same multizone page).  It saves you having to create the EBS volumes in the EC2 API, and just creates them for you.

**Comment by jingxu97** [comment]
Surface better error messages issue is requested by several users such as #31196. Will try to work on it soon.

**Comment by xing-yang** [comment]
CSI attacher does surface better error now so this issue is no longer valid.  Closing this.

/close
