### ISSUE TITLE
service cluster ip range problem

### ISSUE THREAD

**Issue by AdoHe** [kubernetes/kubernetes#25394]
FYI. I have a big subnet: `10.196.192.0/19`, for some reason I can't configure this as service cluster ip range directly, I have to reserve the beginning part of this big ip range. So I decide to use ip range which begins at `10.196.216.0` as the cluster ip range. I configured `10.196.216.0/19` as the `--service-cluster-ip-range`, and then I tried to create some services, and just found the service can still get cluster ip which is not behind `10.196.216.0`. Also from code level, this should be desired. It seems I have to configure `--service-cluster-ip-range` as `10.196.216.0/21`, which can satisfy my requirement. This seems ok, as in kubernetes, the cluster ip of service is not in `CIDR` notation(but why not in `CIDR` notation?), but I still think this is not a good way to work around my problem, as `10.196.216.0/21` and `10.196.216.0/19` has different meaning. @bgrant0607 @thockin @nikhiljindal ptal.

**Comment by thockin** [comment]
On Mon, May 9, 2016 at 9:18 PM, TonyAdo <notifications@github.com> wrote:
>
> FYI. I have a big subnet: 10.196.192.0/19, for some reason I can't configure this as service cluster ip range directly,

Why not?  What did you try and what error did you get?

> I have to reserve the beginning part of this big ip range.

Why? What error did you get?

> So I decide to use ip range which begins at 10.196.216.0 as the cluster ip range.

216 is not a sum of powers-of-two.  216 = 0xd8 = 0b1101_1000.
Netmasks must be a left-aligned contiguous block of binary ones.  In
this case the range you have selected is 10.196.192.0/19, 10.196.216.0
just happens to be inside that range.

https://play.golang.org/p/z3yYGRs-68

Perhaps controller-manager should log the CIDR that was actually
calculated or even blow up if the ipnet.String() != the input
(round-trip-clean).  Patches welcome.

> I configured 10.196.216.0/19 as the --service-cluster-ip-range, and then I tried to create some services, and just
> found the service can still get cluster ip which is not behind 10.196.216.0.

As above

> Also from code level, this should be desired.

I am not sure I get your meaning?

> It seems I have to configure --service-cluster-ip-range as 10.196.216.0/21, which can satisfy my requirement.

21 bits covers 10.196.216.0, so if you REALLY want that as your
prefix, you have to use a /21

> This seems ok, as in kubernetes, the cluster ip of service is not in CIDR notation(but why not in CIDR notation?),

A single cluster IP is a /32, but since it is an endpoint, not a
range, we would never write it in CIDR notation

**Comment by AdoHe** [comment]
```
Why not?  What did you try and what error did you get?
```
As the beginning part of this big subnet has other usage, and I can't use it.

```
In
this case the range you have selected is 10.196.192.0/19, 10.196.216.0
just happens to be inside that range.
```
Yes, actually I just want to use a part of this big range as service cluster ip.

```
A single cluster IP is a /32, but since it is an endpoint, not a
range, we would never write it in CIDR notation
```
I agree with this.

**Comment by thockin** [comment]
On Tue, May 10, 2016 at 8:01 PM, TonyAdo <notifications@github.com> wrote:
>
> Why not?  What did you try and what error did you get?
>
> As the beginning part of this big subnet has other usage, and I can't use it.

Ahh, well you understand the binary nature of CIDR ranges, I think, so
you can't just pick any number you want.  You could go to
10.196.224.0/20 - that's the upper-half of your /19

> In
> this case the range you have selected is 10.196.192.0/19, 10.196.216.0
> just happens to be inside that range.
>
> Yes, actually I just want to use a part of this big range as service cluster ip.

10.196.224.0/20 gives you 2^12 = 4096 Service IPs.

**Comment by thockin** [comment]
I'm closing this because I don't think there's a bug here, just an IP-allocation strategy to be decided :)

**Comment by AdoHe** [comment]
Yeap, I am clear about the binary nature of CIDR ranges, it's just an IP-allocation strategy problem, we can close this. Thanks @thockin
