### ISSUE TITLE
kubectl replaced configmap built from directory does not show new content in a container 

### ISSUE THREAD

**Issue by sbezverk** [kubernetes/kubernetes#25418]
Running kubernetes 1.2.4. I build configmap from directory, where I store files required by the application using this command:
kubectl --server=http://10.57.120.10:8080 create configmap keystone-config --from-file=config/

in some cases I need to add file to the set of config files. So get yaml version of configmap, change it manually and then use kubectl replace to update it.
kubectl --server=http://10.57.120.10:8080 get configmap keystone-config -o yaml > keystone-config.yaml
change  keystone-config.yaml following this file format
kubectl --server=http://10.57.120.10:8080 replace -f  keystone-config.yaml

When I check the container I do not see any changes at the point where this configmap is mounted, but if I restart container then I see a new file which I manually added.

Please let me know if it is a bug or this way of changing configmap is not supported.

Thank you

Serguei

**Comment by zhouhaibing089** [comment]
I do not think this is a bug as when the secrets/configmap has changes, it does not notify the pods to remount them, but I think there should be a good way to avoid restarting container just in order to get those changes applied.

/cc @pmorie as you developed secrets, WDYT? also @Random-Liu , is it possible to remount these volumes without restarting the running containers?

It will do give some value if the pod could get the updated secrets/configmaps automatically, say there may be a process to update the expired token in secrets, and pods will see them immediately.

**Comment by vefimova** [comment]
Hi, I'm working on this one

**Comment by vefimova** [comment]
Hi, @sbezverk I didn't manage to reproduce bug following the steps you described on 1.2.4. 

So what I did:

ConfigMap formed from dir:
### # ls -la ../config-dir/
```
total 16
drwxr-xr-x 2 root root 4096 Jul  8 13:28 .
drwxr-xr-x 4 root root 4096 Jul  8 14:45 ..
-rw-r--r-- 1 root root   13 Jul  8 13:28 file1
-rw-r--r-- 1 root root   13 Jul  8 13:28 file2
```
### # cat ../config-dir/file1
`Hi i'm file1`
### # cat ../config-dir/file2
`Hi i'm file2`
### # kubectl create configmap test-config --from-file=../config-dir/
`configmap "test-config" created`
### # kubectl get configmap/test-config -o yaml > ../test-config.yaml
### # cat test-config.yaml
```
apiVersion: v1
data:
  file1: |
    Hi i'm file1
  file2: |
    Hi i'm file2
kind: ConfigMap
metadata:
  creationTimestamp: 2016-07-08T14:42:20Z
  name: test-config
  namespace: default
  resourceVersion: "1954037"
  selfLink: /api/v1/namespaces/default/configmaps/test-config
  uid: 2ce38933-451a-11e6-8ed8-5254000d0846

```
### # cat podConfigmap.yaml
```
apiVersion: v1
kind: Pod
metadata:
  name: dapi-test-pod
spec:
  containers:
    - name: test-container
      image: gcr.io/google_containers/busybox
      command: [ "/bin/sh", -c, 'while :; do cat /etc/config/file1; sleep 1; done']
      volumeMounts:
      - name: config-volume
        mountPath: /etc/config
  volumes:
    - name: config-volume
      configMap:
        name: test-config
  restartPolicy: Never
```
### # kubectl create -f podConfigmap.yaml
`pod "dapi-test-pod" created`

### Ok, now let's change configMap and replace it:
### # cat test-config.yaml
```
apiVersion: v1
data:
  file3: |
    Hi i'm file3
    ;))))!!!!
  file1: |
    Hi i'm file1 !!!
  file2: |
    Hi i'm file2 !!!
kind: ConfigMap
metadata:
  creationTimestamp: 2016-07-08T14:42:20Z
  name: test-config
  namespace: default
  resourceVersion: "1954037"
  selfLink: /api/v1/namespaces/default/configmaps/test-config
  uid: 2ce38933-451a-11e6-8ed8-5254000d0846
```
### # kubectl replace -f test-config.yaml
`configmap "test-config" replaced`

### _After replacement it will take some time kubelet to update files in mount path (~1 min):_
### # kubectl exec dapi-test-pod -- ls -la /etc/config/
```
total 4
drwxrwxrwt    3 root     root           140 Jul  8 14:45 .
drwxr-xr-x    7 root     root          4096 Jul  8 14:43 ..
drwxr-xr-x    2 root     root           100 Jul  8 14:45 ..7987_08_07_09_45_56.099037854
lrwxrwxrwx    1 root     root            31 Jul  8 14:45 ..data -> ..7987_08_07_09_45_56.099037854
lrwxrwxrwx    1 root     root            12 Jul  8 14:43 file1 -> ..data/file1
lrwxrwxrwx    1 root     root            12 Jul  8 14:43 file2 -> ..data/file2
lrwxrwxrwx    1 root     root            12 Jul  8 14:45 file3 -> ..data/file3
```
### #kubectl exec dapi-test-pod -- cat /etc/config/file1
`Hi i'm file1 !!!`
### #kubectl exec dapi-test-pod -- cat /etc/config/file3
Hi i'm file3
`;))))!!!!`


So @sbezverk could you please provide more details for reproduction or confirm it was a confusion due to delayed update?

**Comment by sbezverk** [comment]
@vefimova I will redo this test and let you know the result, hopefully it was just a mistake on my side. Thank you.

**Comment by yadzhang** [comment]
Can K8S provide an option for updating or not updating the configuration in the container while it's running? If we update configmap, but do not want to spread the configuration to all conatainers. K8S can provide an option when create app.

**Comment by tobilarscheid** [comment]
Hi,

I can't reproduce the bug as well. I did however come here by googling the issue, simply for the reason that updating the file in the container takes a few seconds after the config map has been updated. So just leaving this here in case someone ends up here as well!
