### ISSUE TITLE
POD deleted, ignoring desired state.

### ISSUE THREAD

**Issue by snejati86** [kubernetes/kubernetes#25482]
Using the couchbase installation over kubernetes a pod with this definition is created to glue the cluster.
[https://github.com/couchbase/kubernetes/blob/master/pods/app-etcd.yaml](url) , as the database fills up the memory on the couchbase nodes ( potentially consuming the minions most memory and becoming a noisy neighbor ) couchbase controllers crash and come back up. However in one instance the app-etcd pod was deleted without any logs. The result was that the new couchbase controllers did not attach to the cluster. 

Is there a way to get more logs on this ?

**Comment by saad-ali** [comment]
Please re-post your question to [stackoverflow]
(http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases.

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to similar questions, and also familiarize yourself with:
  * [user guide](http://kubernetes.io/docs/user-guide/)
  * [troubleshooting guide](http://kubernetes.io/docs/admin/cluster-troubleshooting/)

Again, thanks for using Kubernetes.

The Kubernetes Team
