### ISSUE TITLE
Expose the service-cluster-ip-range CIDR through the API Server

### ISSUE THREAD

**Issue by 2opremio** [kubernetes/kubernetes#25533]
Having access to the service-cluster-ip-range CIDR would allow us to track connections more efficiently in [Weave Scope](https://www.weave.works/products/weave-scope/). See https://github.com/weaveworks/scope/pull/1490

AFAICT it's only stored in etcd and not exposed. See https://github.com/kubernetes/kubernetes/blob/ef885d05eb6769c741faed2157f0c3d2a27a5809/pkg/master/master.go#L430-L437

**Comment by AdoHe** [comment]
@thockin wdyt?

**Comment by thockin** [comment]
@mikedanese this is one of the things I want in the per-cluster configmap.  Mike is there any progress towards that sub-goal of the larger goal?

@2opremio other than that idea, which I believe WILL come, but maybe not by 1.3, what ideas for exposing it?

**Comment by 2opremio** [comment]
@thockin We are working it around by ... inferring a `/32` network per service IP (yeah, I know) which seems to work for now. We can live with that for now but  may change it results in reports of bad performance.

**Comment by johnbelamaric** [comment]
Any progress on this? I couldn't find anything in the 1.5 docs. Right now to get PTR support in CoreDNS we need to manually configure with the reverse zones. Would be nice to have the service and pod CIDRs available via an API so we could make it automatic.

**Comment by thockin** [comment]
I think the configmap work is focusing on kubelet first, so nothing to say
here yet.

**Comment by johnbelamaric** [comment]
Thanks Tim.

**Comment by 2opremio** [comment]
Any updates?

**Comment by deitch** [comment]
Just stumbled across this. Somehow I lost my `IPALLOC_RANGE` var for weave, which defaults to a conflicting address. Oh well. Then I checked if weave can get the range from the API, but realized it isn't exposed. Plans on it?

**Comment by errordeveloper** [comment]
/close

Closing in favour of #46508, simply because one has to be closed and this one is already marked as rotten.

**Comment by jayunit100** [comment]
hmmm so, i think this is incorrectly closed, the *other* issue is aboute ClusterCIDR, not ServiceCluster IP Range....

**Comment by errordeveloper** [comment]
Which other issue are you referring to?

**Comment by aauren** [comment]
@jayunit100 I agree, it says this was closed in favor of #46508 but that is for a different CIDR. That one is referring to the pod CIDRs and this one is referring to the service range CIDR.

I think that since k8s has this information it would be super helpful to have it supply it through the API rather than relying on side-effects (like this: https://stackoverflow.com/questions/44190607/how-do-you-find-the-cluster-service-cidr-of-a-kubernetes-cluster/61685899#61685899) or by having every network component expose a flag (like this: https://github.com/cloudnativelabs/kube-router/pull/914/files#diff-d76a88afa98afa848ebc5641cd1adf2fR85) to ingest this over and over again which makes things less DRY and can cause drift within the cluster between core components that share responsibilities.

Is there any chance that we can re-open this and k8s can support this functionality, even if it's in the future? @errordeveloper @thockin
