### ISSUE TITLE
Feature Request: Allow `change-cause` annotation to be overridden in resource file

### ISSUE THREAD

**Issue by osterman** [kubernetes/kubernetes#25554]
## what
- Let the user override the default `change-cause` generated by `kubectl` by specifying it in the `metadata` of the resource file

Example:
![image](https://cloud.githubusercontent.com/assets/52489/15233372/04024156-185d-11e6-8d1f-9f4131bd7829.png)
## why
- The automatic annotations are not very helpful if the same command is always executed
- The end-user can provide more meaningful annotations in the context of their application (i.e. git commit messages, git hash, release version, etc)
## note

Specifying `change-cause` sometimes works. Not sure if this is due to a race-condition.

![image](https://cloud.githubusercontent.com/assets/52489/15233410/59bfb98e-185d-11e6-9989-0822b4c1d1a7.png)

**Comment by janetkuo** [comment]
@kubernetes/kubectl @kubernetes/sig-config

**Comment by janetkuo** [comment]
or, we can create another annotation (for user specified change cause) to display in `rollout history`

**Comment by osterman** [comment]
Yea, a new annotation could work (e.g. `change-desc`).  

Alternatively, only populate `change-cause` with the current kubectl command when `--record=true`. This way if the `change-cause` is specified in the resource, it will not be replaced and still honored.

**Comment by osterman** [comment]
For the record, the current behavior is to replace `change-cause` with the current command in the resource definition even if `--record=false`.

**Comment by pwittrock** [comment]
I prefer using the second annotation so we always know where each came from.

**Comment by AdoHe** [comment]
I prefer adding a new annotation, so we can track this. Also we need to do some limitation.

**Comment by pwittrock** [comment]
Issue #25924 documents a hack to override the `change-cause` annotation which we probably want to prevent as part of this.

**Comment by ichekrygin** [comment]
I we add a "new" annotation, what would be the purpose for original annotation? If used w/ `--record=false` results in `CHANGE-CAUSE=<none>` IN rollout history.

**Comment by janetkuo** [comment]
The original annotation was for recording the commands automatically to make it easier to distinguish different rollout revisions. It wasn't turned on by default, because we don't want to spam all objects by change-cause annotations. The annotation will be updated if already present (no matter if `--record` is on). 

We can support a new annotation (manually updated, you can any information you like) to show in `rollout history`. But since the new annotation is applied _manually,_ it might be stale. It can't replace the original annotation IMO.

**Comment by punitag** [comment]
+1. new annotation is fine. we want to tag the rollout with the git commit so as to make it easier to rollback if we have to

**Comment by srcspider** [comment]
@janetkuo 
> We can support a new annotation (manually updated, you can any information you like) to show in rollout history. But since the new annotation is applied manually, it might be stale. It can't replace the original annotation IMO.

I don't think it's a good idea to mix "new revision" and "change" as if they mean the same thing. 

If I scale the deployment up and down then you replace the actual change that cause the revision. How is this helpful? You eventually end up with these inconsequential messages for the "revision cause" which technically speaking are NOT the cause.

Basically, you got it backwards. The command or custom annotation for any command that causes a new revision should be the priority. Any random-ness that causes "change" (eg. scaling, whatever-else) should appear as a separate (optional) list inside the revision itself (maybe have the last one show on the revision table as the "last change" or none if no random change happened since the start of the revision).

*As it is now even if I was interested in why something was scaled there's no information on when it was scaled anyway, nor how many times it was scaled before and to what. I can tell it's scaled just by doing `get` on the replication set (and that's the most likely goto anyway).*

**Comment by kargakis** [comment]
> We can support a new annotation (manually updated, you can any information you like) to show in rollout history. But since the new annotation is applied manually, it might be stale. It can't replace the original annotation IMO.

I think this is fine. If the annotation is not updated for a new revision, we can always default to something like "PodTemplate change".

**Comment by ericuldall** [comment]
Any idea if/when this will be implemented? It would be really nice to get a commit user name and commit id in that change-cause during ci. Right now the rollout history is essentially useless as i'm not 100% sure what state I may be rolling back to. If I pass the `--revision` flag to rollout history I can see some helpful information, like the image deployed, but our images are tagged with a branch name and timestamp, so I would have to then step through ci builds and match against that image to successfully track a commit. Granted this may be something we could optimize elsewhere, but the change-cause override would be much appreciated.

**Comment by jbeda** [comment]
Some observations based on experimentation (and not reading the code).

Note that if the Deployment does *not* have a `kubernetes.io/change-cause` annotation but the template *does* then the change cause is not clobbered and shows up in the revision history.  Note also that the annotation is included in the hash of the template so modifying it will trigger a new rollout and history entry.

Similarly, it appears that if it is set on the Deployment but `kubectl apply` is called with `--record=false` then the annotation is also not clobbered and is propagated down.

**Comment by dileepfrog** [comment]
@jbeda 
> Similarly, it appears that if it is set on the Deployment but kubectl apply is called with --record=false then the annotation is also not clobbered and is propagated down.

Thank you! Confirmed this is an entirely viable workaround for the time being.

**Comment by osterman** [comment]
@jbeda - I can also confirm these strategies both work now for us in k8s 1.4.6.  Not sure what's different, but could have sworn we tried some variation of both of these.

**Comment by kargakis** [comment]
> annotation but the template does then the change cause is not clobbered and shows up in the revision history. Note also that the annotation is included in the hash of the template so modifying it will trigger a new rollout and history entry.

How does the annotation end up in the pod template?

**Comment by julianvmodesto** [comment]
Seems that setting `kubernetes.io/change-cause` works. Could we close this issue?

**Comment by ithenov** [comment]
can we specify the `kubectl.io/change-cause` annotation in the patch configuration now?
