### ISSUE TITLE
resource quota calculate object count wrong

### ISSUE THREAD

**Issue by adohe** [kubernetes/kubernetes#25559]
FYI. I create a resource quota for a namespace, and set the replicationcontrollers number, just like this:

```
[root@localhost ~]# kubectl describe quota --namespace="staging"
Name:           quota
Namespace:      staging
Resource        Used    Hard
--------        ----    ----
cpu         6750m   20
memory          7936Mi  20Gi
replicationcontrollers  20  20
```

From this output, you can see we have used `20` replicationcontrollers, but if you run `kubectl get rc --namespace="staging"` and sum the number of rc, you will just get `9`, which means actually we just have `9` rc in this namespace. So it seems the resource quota controller can't always observe the rc DELETE.
Besides I am using kubernetes `1.1.4` and my apiserver configuration is:

```
--admission_control=ServiceAccount,NamespaceLifecycle,LimitRanger,ResourceQuota
```

@derekwaynecarr wdyt? I am not very clear whether 1.1.4 has some problems about resource quota.

**Comment by derekwaynecarr** [comment]
Prior to kube 1.2, we were slow to observe deletes.  Did it settle back to
9 as expected?  The controller manager has a flag that controls how often
quota is recalculated to observe replenishment.

**Comment by AdoHe** [comment]
@derekwaynecarr I take a deep look at the log of kube-controller-manager, and just found this:
```
Error synchronizing: the object has been modified; please apply your changes to the latest version and try again
```
I think the root cause is because the `resourceVersion` is stale, I set the `resourceVersion="0"` explicitly and it seems can fix this.

**Comment by AdoHe** [comment]
@derekwaynecarr Besides I am thinking whether it is good to use `utilruntime.HandleError` to handle the sync error. In this scenario, it is hard to tell which resource quota under which namespace has sync error.  Maybe we can add more specific error log here for better trouble shooting. In our case, since we are using kubernetes 1.1.4, and resource quota controller just log the resource quota name(exclude namespace), as you may have same quota name in different namespaces, it's hard to exactly tell which one is failed.
