### ISSUE TITLE
Node e2es leak vms

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#25639]
When the node e2e times out it sometimes leaks a vm. Such vms are usually running the kubelet in standalone mode, but not doing anything else. This exacerbates the IP exaustion: https://github.com/kubernetes/kubernetes/issues/25629 

@pwittrock

**Comment by ixdy** [comment]
gcloud one-liner to find VMs created over an hour ago, excluding Jenkins VMs:
```shell
gcloud compute instances list --project=kubernetes-jenkins-pull --filter="NOT tags.items:do-not-delete AND creationTimestamp<'$(date +%Y-%m-%dT%H:%M:%S%z --date='1 hour ago')' AND NOT name~'.*jenkins.*'" --format='value(name)'
```

**Comment by bprashanth** [comment]
@kubernetes/sig-node, short term fix? this seems to be the root cause for https://github.com/kubernetes/kubernetes/issues/25629. I don't know why we didn't always leak at this rate, probably the timeouts.

**Comment by ixdy** [comment]
Lots of node e2e runs on PR Jenkins are basically stuck after logging this:
```
Initializing e2e tests using image e2e-node-ubuntu-trusty-docker10-image.
Initializing e2e tests using image e2e-node-ubuntu-trusty-docker9-image.
Initializing e2e tests using image e2e-node-ubuntu-trusty-docker8-image.
Initializing e2e tests using image e2e-node-coreos-stable20160218-image.
Initializing e2e tests using image e2e-node-containervm-20160217-image.
```

They eventually time out after an hour, which causes us to then leak the VMs.

**Comment by ixdy** [comment]
Just to close the loop on this bug:
- we were leaking VMs all over the place because the node e2e jobs were timing out after 60 minutes on PR Jenkins
- the job has been running fine on post-commit Jenkins... but the timeout there is 90 minutes. Builds are usually taking ~60m there
- #24191, which merged two days ago, inadvertently added about 20m to the job runtime
- when Jenkins times out the node e2e job, it doesn't clean up after itself
- then the leaked VMs started causing the GCE e2e jobs to fail as well
- additionally, the submit queue doesn't currently look at the PR node e2e job, so though the job failed on the PR which increased the runtime, the SQ happily merged it anyway

We're addressing these issues at a number of places.

Short term:
- the PR node e2e job now has a timeout of 90m, matching post-commit
- I ran the cgo install nonsense on each of the PR Jenkins VMs, which seems to have sped up build times from ~20m to ~7m. (This alone has gotten the node e2e jobs under 60m again.)
- I've manually cleaned up all leaked VMs

Medium term:
- I created https://github.com/kubernetes/test-infra/pull/52 to automatically clean up leaked VMs periodically
- @pwittrock created #25685 to allow passing ginkgo flags through, so we can turn off some tests and speed up PR builds
- @Random-Liu / @pwittrock are working on fixing the slowdown introduced by #24191 (I think it was decided it wasn't intentional)
- I created #25708 to time out at the test stage so that cleanup can still occur, rather than having 
Jenkins abort the run. (This is similar to most of the other jobs in Jenkins.)
- also some minor improvements around logging

Longer term:
- We probably want 3 levels of testing:
  - post commit: run every test
  - PR created: run some subset of tests
  - right before merge: run a few quick smoke tests
- We need better monitoring of build times, alerting us when it gets drastically larger (20m is a huge red flag).
- The SQ should probably start paying attention to the PR node e2e job, too.

**Comment by ixdy** [comment]
No leaked node e2e VMs this morning! Woohoo!

**Comment by bprashanth** [comment]
Is that because of the GC or is this issue fixed?

**Comment by ixdy** [comment]
The GC PR hasn't merged yet. I think it's because the node e2e tests aren't timing out anymore.

**Comment by bprashanth** [comment]
Great! closing then

**Comment by spxtr** [comment]
We ran out of CPUs and IPs in the `kubernetes-jenkins-pull` project due to leaked VMs. https://github.com/kubernetes/test-infra/issues/190 needs to happen.
