### ISSUE TITLE
round-robin work queue proposal

### ISSUE THREAD

**Issue by mqliang** [kubernetes/kubernetes#25744]
#### Problem

[work queue](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/replication/replication_controller.go#L107) of controller-manager is FIFO, it can not ensure fairness across namespaces: user A create 1000 RCs, and soon user B create 1 RC, user B's RC can not been synced until all the 1000 RCs has been synced. User B get a really bad experience in such a case. 

#### Proposal
I'd like implement a work queue with round-robin strategy, which could solve the above starvation problem. 

@bprashanth @wojtek-t @gmarek @deads2k Any ideas? And we may need make the strategy(FIFO and RR) configurable?

**Comment by deads2k** [comment]
Is this a problem you're experiencing or a problem that just theoretically exists?  Straight round-robin of namespaces would be annoying since it would allow relative late-comers to "jump the queue".  Static scoring for a priority queue is annoying since ending up with a poor score is a "never do this" sentence.  I've never seen dynamic scoring that scaled in any reasonable way.

Is there a simple implementation that I'm not seeing?  I'm not opposed in principle, but none of the implementations that occur to me right away are both simple and satisfactory.
