### ISSUE TITLE
failed to set up cluster via docker

### ISSUE THREAD

**Issue by AaronTao1990** [kubernetes/kubernetes#25792]
I am following this tutorial [Installing a Kubernetes Master Node via Docker](http://kubernetes.io/docs/getting-started-guides/docker-multinode/master/) to set up a cluster via Dockar。

After setting up etcd and flannel. I tried to restart docker with --bip & --mtu option.

> You now need to edit the docker configuration to activate new flags. Again, this is system specific.
> This may be in /etc/default/docker or /etc/systemd/service/docker.service or it may be elsewhere.
> Regardless, you need to add the following to the docker command line:
> --bip=${FLANNEL_SUBNET} --mtu=${FLANNEL_MTU}

And after I ran

	ps aux | grep docker
	

I found my docker is already started with the right options:

	root     55351  0.1  0.0 994216 34940 ?        Ssl  14:25   0:07 /usr/bin/docker daemon -H fd:// --bip=10.1.65.1/24 --mtu=8972
	
	
	
But when I tried to run hello-world procedure with the following command
	
	sudo docker run hello-world
	
The error occurs
	
	docker: Error response from daemon: Container command '/hello' not found or does not exist..
	
	
BTW, I can run hello-world find with --bip & --mtu removed.

Any kind of help will be appreciated :)

**Comment by lavalamp** [comment]
Please re-post your question to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases.

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to similar questions, and also familiarize yourself with:
   * [the user guide](http://kubernetes.io/v1.0/)
   * [the troubleshooting guide](http://kubernetes.io/v1.0/docs/troubleshooting.html)

Again, thanks for using Kubernetes.

The Kubernetes Team
