### ISSUE TITLE
Check container exit status when inspecting immediately after create

### ISSUE THREAD

**Issue by timstclair** [kubernetes/kubernetes#25844]
Kubelet issues a docker inspect call after creating a container, but for very short lived containers there is a window in which they could exit before being inspected [1]. Specifically, I'm referring to [this line](https://github.com/kubernetes/kubernetes/blob/35c9ca853a084a4ea04debe027c6ea680fd9ddac/pkg/kubelet/dockertools/manager.go#L1493) in the docker manager.

If the container PID is 0, we should check the ExitCode and other relevant fields and handle them appropriately.

[1] This is the suspected cause of several flakes:
http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gke/7253/
http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gce-container-vm/25/
http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gce-container-vm/32/

/cc @kubernetes/sig-node @bprashanth @smarterclayton @zmerlynn

**Comment by bprashanth** [comment]
looking at the logs 2 weird things:
1. The race described 
2. The second container ran, which suggests inconsistent reporting of initialized status of init1 and choosing init2 as the next container (https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockertools/manager.go#L2144 vs https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet.go#L3399). I think 1 got it right and 2 got it wrong. 

From logs: 
```
May 18 15:58:33.380: INFO: pod-init-fa51f797-1d4b-11e6-80a4-0242ac110007 started at 2016-05-18T15:58:04-07:00 (2+1 container statuses recorded)
May 18 15:58:33.380: INFO:  Init container init1 ready: false, restart count 0
May 18 15:58:33.380: INFO:  Init container init2 ready: true, restart count 0
```

I'd expect the second one to not have run in this case?
Node logs: https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/logs/kubernetes-e2e-gke/7253/artifacts/gke-jenkins-e2e-default-pool-e3e961bc-f3ec/

**Comment by smarterclayton** [comment]
Init containers have an implicit assumption that container statuses include
results of previous SyncPod invocations. If that's not the case we may need
to fix that (or at least mitigate it).

On May 18, 2016, at 8:28 PM, Prashanth B <notifications@github.com> wrote:

looking at the logs 2 weird things:
1. The race described
2. The second container ran, which suggests inconsistent reporting of
initialized status of init1 and choosing init2 as the next container (
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockertools/manager.go#L2144
vs
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet.go#L3399).
I think 1 got it right and 2 got it wrong.

From logs:

May 18 15:58:33.380: INFO:
pod-init-fa51f797-1d4b-11e6-80a4-0242ac110007 started at
2016-05-18T15:58:04-07:00 (2+1 container statuses recorded)
May 18 15:58:33.380: INFO:  Init container init1 ready: false, restart count 0
May 18 15:58:33.380: INFO:  Init container init2 ready: true, restart count 0

I'd expect the second one to not have run in this case?
Node logs:
https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/logs/kubernetes-e2e-gke/7253/artifacts/gke-jenkins-e2e-default-pool-e3e961bc-f3ec/

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/25844#issuecomment-220196622>

**Comment by yujuhong** [comment]
> Init containers have an implicit assumption that container statuses include
> results of previous SyncPod invocations. If that's not the case we may need
> to fix that (or at least mitigate it).

This should be true. Is there any evidence that suggests the opposite? https://github.com/kubernetes/kubernetes/issues/25844#issuecomment-220196622 only shows conflicting view of whether init1 has run.

**Comment by yujuhong** [comment]
> Kubelet issues a docker inspect call after creating a container, but for very short lived containers there is a window in which they could exit before being inspected [1]. Specifically, I'm referring to this line in the docker manager.
> 
> If the container PID is 0, we should check the ExitCode and other relevant fields and handle them appropriately.

If the container exits already and it's not an infra container, kubelet should not error out. Although even if it does, I failed to see how this could affect the readiness of the init container without checking the code further.

**Comment by smarterclayton** [comment]
Each syncPod invocation, we inspect the list of init container in order
looking for lastTerminationState.  There could be a bug in that logic, or
if we didn't get the full status, we might make a bad decision.  When
determining which container to run *next*, we always look for the last init
container in the chain that has success, then run the next container
(unless the pod is RestartNever).

**Comment by smarterclayton** [comment]
Saw this flake again.  How do we verify that container status is not lost between syn pods?

**Comment by smarterclayton** [comment]
... between calls to syncPods

**Comment by yujuhong** [comment]
The second sync clearly saw the init1 container, and decided to launch init2. See "InitContainersToKeep" in the message below.
```
I0518 14:25:08.592331    3431 manager.go:1846] Got container changes for pod "pod-init-4dba4ed3-1d04-11e6-bc52-0242ac110019_e2e-tests-pods-372po(4dc307c5-1d04-11e6-ba0b-42010af00002)": {StartInfraContainer:false InfraChanged:false InfraContainerId:a9b366bda43b6d215c460ffc3caf0023dce8f3e7966f2e02c2b2efb8e777526e InitFailed:false InitContainersToKeep:map[cb280ac4bab4c23bf604dcbca8cd4162f7091b843eb4471a9e0c8ba74d69ac4f:0] ContainersToStart:map[0:Container {Name:run1 Image:gcr.io/google_containers/busybox:1.24 Command:[/bin/true] Args:[] WorkingDir: Ports:[] Env:[] Resources:{Limits:map[] Requests:map[]} VolumeMounts:[{Name:default-token-tsoey ReadOnly:true MountPath:/var/run/secrets/kubernetes.io/serviceaccount SubPath:}] LivenessProbe:<nil> ReadinessProbe:<nil> Lifecycle:<nil> TerminationMessagePath:/dev/termination-log ImagePullPolicy:IfNotPresent SecurityContext:<nil> Stdin:false StdinOnce:false TTY:false} is dead, but RestartPolicy says that we should restart it.] ContainersToKeep:map[a9b366bda43b6d215c460ffc3caf0023dce8f3e7966f2e02c2b2efb8e777526e:-1]}
```

**Comment by smarterclayton** [comment]
containers to keep can include failed containers.

**Comment by yujuhong** [comment]
Discussed on slack. In summary, the problem has to do with how we convert the kubecontainer.PodStatus to the api.PodStatus.

If a container is terminated, the function `convertToAPIContainerStatuses` makes the decisions:
 1. If the pod restart policy is "Always", and there is a "failure reason" recorded for the given container, this means the pod worker tried to (re)start the container but failed. Set the state to "Waiting" and populate the reason.
 2. Otherwise, the container state is simply "terminated".

Init containers don't obey the restart policy like regular containers, and the logic will need to be amended to work with them. @Random-Liu is working on a PR.
In addition to that, kubelet should not error out if a user container exited before it could apply the oom score (which is best effort in this case). #25896 fixes that.

**Comment by dchen1107** [comment]
Ahh, thanks for digging into the issue. 

This is the exact the concern I had when I reviewed the initial implementation of init container, which blocks pr for a while. I even asked @bprashanth to help me verify this case, unfortunately we didn't reproduce the issue back then. :-(

**Comment by smarterclayton** [comment]
I wish I'd seen the flakes in the runs prior to merge.

**Comment by timstclair** [comment]
> I wish I'd seen the flakes in the runs prior to merge.

We didn't notice this until we started running the tests against docker v1.11.1, which is much faster and hit the race condition differently.

**Comment by yujuhong** [comment]
> We didn't notice this until we started running the tests against docker v1.11.1, which is much faster and hit the race condition differently.

I suppose that's a good thing...

**Comment by dchen1107** [comment]
@smarterclayton It is hard to reproduce this. The extra check of last terminated container in your initial code makes me nervous, but we couldn't reproduce it due to that small race windows until we have a faster docker running on the node. :-)

**Comment by jsafrane** [comment]
I got "Pods should invoke init containers on a RestartAlways pod" flake (referenced from #25879):

```
[k8s.io] Pods
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:508
  should invoke init containers on a RestartAlways pod [It]
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/pods.go:794

  Expected
      <api.ConditionStatus>: False
  to equal
      <api.ConditionStatus>: True

```

Logs: https://console.cloud.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/25955/kubernetes-pull-build-test-e2e-gce/41020/

**Comment by yujuhong** [comment]
All the fixes went in. Please reopen this issue if you see any more flakes.
