### ISSUE TITLE
"Kubectl client [k8s.io] Simple pod [It] should support exec through an HTTP proxy" proxy log check is wrong

### ISSUE THREAD

**Issue by krousey** [kubernetes/kubernetes#25887]
At some point, kubectl starting doing multiple requests on calls to `kubectl exec`. One of these is not a SPDY connection, so at least one `CONNECT` will show up in the proxy logs even if proxy support is commented out in the SPDY round tripper. There should be a more robust method to verify that the SPDY round tripper is indeed proxying.

**Comment by ncdc** [comment]
I think unless we can have the proxy do MITM and decrypt the connection from kubectl, we may just need to check for 2 `CONNECT` lines in the log instead of 1.

Or you need to be able to find a way to allow packets to go only to the proxy and keep them from going to the apiserver itself.

I'm not sure what else we can really do.

**Comment by fejta** [comment]
Starting on Mar 7 roughly 20 tests/hr are failing the kubectl client simple pod tests with a super unhelpful false is not true type error:

https://k8s-testgrid.appspot.com/release-1.6-upgrade-skew#gke-1.6-master-cvm-kubectl-skew&width=20&sort-by-failures=

https://storage.googleapis.com/k8s-gubernator/triage/index.html#df761c6a379c7dc56dae

![kubectl](https://cloud.githubusercontent.com/assets/940341/23983631/6f3d415c-09d2-11e7-97d0-d8d5bb689edb.png)

Want to reuse this issue for this?

**Comment by ncdc** [comment]
@calebamiles @ethernetdan @fejta this issue is about how we ideally should change the logic in the "exec through an http proxy" test to validate the traffic actually uses the http proxy.

The failures that @fejta linked to are unrelated. In two that I examined, the pod was assigned to a node by the scheduler, and then quickly evicted by the taint manager, causing the test to fail because it couldn't find the pod.

I am removing the label `kind/flake` and the v1.6 milestone from this issue.

**Comment by ncdc** [comment]
I'd be happy to file a new issue if you'd like for the taint manager doing "weird things".

**Comment by ncdc** [comment]
Here's the actual issue causing most or all of the flakes reported in https://github.com/kubernetes/kubernetes/issues/25887#issuecomment-286965195: https://github.com/kubernetes/kubernetes/issues/43263.
