### ISSUE TITLE
Default plugin directory is /usr/libexec/kubernetes/kubelet-plugins/net/exec/ for CNI

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/kubernetes#25937]
If I understand correctly, when I tell the kubelet `--network-plugin=cni`, it will search `/usr/libexec/kubernetes/kubelet-plugins/net/exec/` by default to find the CNI plugin's config file.  That is contrary to the usual CNI place (`/etc/cni/net.d/`) and looks specific to the other kind of network plugin.  Have I got this right?  If so, it seems a less than ideal situation.

**Comment by MikeSpreitzer** [comment]
BTW, the Mesos framework for Kubernetes can pass `--network-plugin` to the kubelet but not `--network-plugin-dir`.

**Comment by luxas** [comment]
@bprashanth @thockin @freehan

**Comment by freehan** [comment]
If `--network-plugin-dir ` is not specified, it will serach in the CNI default directory. 

https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/network/cni/cni.go#L36

**Comment by bboreham** [comment]
As a purely historical point, this last comment seems wrong to me - `--network-plugin-dir` was defaulted at https://github.com/bboreham/kubernetes/blob/e070cb617ab99a204c8c4907b8db03286121ee8e/pkg/apis/componentconfig/v1alpha1/defaults.go#L213, so it would always be "specified" when it reached `cni.go`. 

I believe this issue was not fixed until #32151
