### ISSUE TITLE
`postStart` hook prevents registration of Pod in Service

### ISSUE THREAD

**Issue by streamnsight** [kubernetes/kubernetes#26035]
Hello,

I'm trying to use a `postStart` hook to run a config task in a pod.
In my hook script I look up the **Pods** referenced by a **Service**, to find all the **Pods** related to the one I'm starting.

The curl call to the `apiserver` works fine when inside the container, but when running within the `postStart` hook, it just returns nothing. Since I wait for it to return something to run the rest of the code, it just loops forever and the **Pod** is never `running`: it stays in `containerCreating` mode.

Is a **Pod** only registered with the **Service** after it is in `running` state? 
That would explain the behavior.

I would have though that `postStart` means after start, that is the Pod should actually be in 'running' state, but it doesn't seem to be the case.

Is this meant to be or is it a bug?

**Comment by streamnsight** [comment]
if this logic is meant to be, and it won't change, I guess I can alter my logic and assume the IP of the pod running the hook will NOT be in the list, and add it myself. 
It's dangerous if this behavior might change at some point.

**Comment by bprashanth** [comment]
The pod only joins the service when it's ready, which is after running. In 1.3 there will be an annotation you can use on a Service that allows endpoints for unready pods. Use it with caution, since readiness exists for a reason. Some situations where it's useful: https://github.com/kubernetes/kubernetes/issues/25283. The annotation is: https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/endpoint/endpoints_controller.go#L64

**Comment by livelace** [comment]
@bprashanth 

We have the same problem. We need a service which can send requests/traffic to a pod which not in a ready state (pod is executing poststart hook). I added specified annotations to my service, but it didn't help, the service doesn't respond and iptables rules are not present. Could you reveal more information ?

**Comment by thockin** [comment]
By definition a pod is not able to be part of the LBs until it is ready.  Can you describe what you're trying to do?

**Comment by livelace** [comment]
>Can you describe what you're trying to do?

It's not actual at the moment, because I found more flexible way, but imagine:

1. Service1 - starts first, pod is ready, all is good
2. Service2 - starts second, Serivce1 uses Service2, in pod with Service2 starts a task, which test Service2 through Service1. That task starts by PostStartHook, it's mean, that the pod is not in a ready state, consequently task always ends with error, because Service2 is not available over network.

**Comment by livelace** [comment]
It will be nice, if I could say "this Service should be routed always, because I know what I'm doing"

**Comment by streamnsight** [comment]
My particular issue was with a single service, to deploy a Mongo cluster: the first node starts as stand alone, then other nodes need to register with the first node as slaves, and configure the cluster.
I had to hack around quite a bit at the time, but I think there are now initContainers to do this kind of things.
Haven't reworked my config, but  I think @livelace should look into that:
https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-initialization/

**Comment by livelace** [comment]
@streamnsight Hello and thanks for your suggest, but I have known about init containers and it is not a convenient way. Anyway I use different approach now.
