### ISSUE TITLE
Pass zone through downard api

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#26030]
If I want to know what zone I'm running in currently I need to figure out what node I'm on, and then parse out `failure-domain.beta.kubernetes.io/zone=` label. This makes actions like figuring out the master of my zone more error prone. Also if I don't find that label I have to assume I'm in the default zone, which would lead to some bad failure modes if the reason I didn't find it was because the format changed. 

There's probably an issue somewhere for passing node through the downward api, but if there isn't, that would also be useful.

**Comment by dims** [comment]
@bprashanth - fyi, there's a PR for "Extend downward API volumes with node information":
https://github.com/kubernetes/kubernetes/pull/25957

**Comment by tpetracca** [comment]
#25957 was closed due to security/permissions concerns around exposing node information to a pod in an unchecked way.

For pods being ran in a statefulset, I would argue that it is super reasonable to at least be able to expose the zone a pod is running in via the downward API (even if the rest of the node information is not made available).

In my particular use case I'm trying to design a KubernetesSnitch for Cassandra that ideally doesn't rely on hitting either the k8s api or the metadata service exposed by my cloud provider, because I might not have access to these things (because they expose way more information than just my zone), and this would just be easier.

**Comment by spiffxp** [comment]
/sig api-machinery
because downward api

**Comment by frittentheke** [comment]
requested again in issue https://github.com/kubernetes/kubernetes/issues/40610
