### ISSUE TITLE
federation-apiserver: error in converting api.ServiceList to v1.ServiceList

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/kubernetes#26111]
I started the federation-apiserver and went to `/api/v1/services` and got the following output:

```
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "converting (api.ServiceList).[0].ObjectMeta.CreationTimestamp.Time.sec to (v1.ServiceList).[0].ObjectMeta.CreationTimestamp.Time.sec: Cannot set dest. (Tried to deep copy something with unexported fields?)",
  "code": 500
}
```

Expected: I should have got an empty v1.ServiceList

@kubernetes/sig-api-machinery @wojtek-t Any idea on what we are doing wrong?

@jianhuiz @mfanjie @kubernetes/sig-cluster-federation Have you guys seen this error?

**Comment by lavalamp** [comment]
I think your deep copiers or conversion functions are not getting
registered properly. If you look at my change in #25526, some places are
inappropriately registering with api.Scheme instead of the passed in
scheme. Maybe you have that problem or a similar one, since I think you
guys copied some code.

**Comment by smarterclayton** [comment]
Deep copy generation was slightly broken as well - you may want to double
check that they are registered.

On May 23, 2016, at 5:50 PM, Daniel Smith <notifications@github.com> wrote:

I think your deep copiers or conversion functions are not getting
registered properly. If you look at my change in #25526, some places are
inappropriately registering with api.Scheme instead of the passed in
scheme. Maybe you have that problem or a similar one, since I think you
guys copied some code.

On Mon, May 23, 2016 at 2:34 PM, Nikhil Jindal <notifications@github.com>
wrote:

> I started the federation-apiserver and went to /api/v1/services and got
> the following output:
>
> {
> "kind": "Status",
> "apiVersion": "v1",
> "metadata": {},
> "status": "Failure",
> "message": "converting
(api.ServiceList).[0].ObjectMeta.CreationTimestamp.Time.sec to
(v1.ServiceList).[0].ObjectMeta.CreationTimestamp.Time.sec: Cannot set
dest. (Tried to deep copy something with unexported fields?)",
> "code": 500
> }
>
> Expected: I should have got an empty v1.ServiceList
>
> @kubernetes/sig-api-machinery
> <https://github.com/orgs/kubernetes/teams/sig-api-machinery> @wojtek-t
> <https://github.com/wojtek-t> Any idea on what we are doing wrong?
>
> @jianhuiz <https://github.com/jianhuiz> @mfanjie
> <https://github.com/mfanjie> @kubernetes/sig-cluster-federation
> <https://github.com/orgs/kubernetes/teams/sig-cluster-federation> Have
> you guys seen this error?
>
> —
> You are receiving this because you are on a team that was mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/kubernetes/kubernetes/issues/26111>
>

—
You are receiving this because you are on a team that was mentioned.
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/26111#issuecomment-221106915>

**Comment by mfanjie** [comment]
@nikhiljindal I got the same error with latest branch, as I was swamping on service controller, so I use a previous version and worked around it.

**Comment by nikhiljindal** [comment]
deep copies were indeed missing, but adding them hasnt fixed the issue. Will debug more.
https://github.com/kubernetes/kubernetes/pull/26142 is my PR to add the deep copies

cc @mfanjie Please feel free to file issues for any such problem you face. We need to fix all these issues. Its good if we know about them early. Thanks!

**Comment by nikhiljindal** [comment]
https://github.com/kubernetes/kubernetes/pull/26142 fixes this
