### ISSUE TITLE
Need OWNERS for pkg/storage

### ISSUE THREAD

**Issue by fejta** [kubernetes/kubernetes#26118]
https://github.com/kubernetes/kubernetes/tree/master/pkg/storage

For https://github.com/kubernetes/kubernetes/issues/24679

@bgrant0607 @brendandburns @dchen1107 @lavalamp @smarterclayton @thockin

**Comment by bgrant0607** [comment]
Part of the problem is the lack of top-level OWNERS.

cc @mikedanese @eparis

**Comment by thockin** [comment]
Surprisingly pkg/storage has nothing to do with storage in kubernetes and
everything to do with the API implementation

**Comment by bgrant0607** [comment]
BTW, area/component owners are listed here:
https://github.com/kubernetes/kubernetes/wiki

Confusingly, pkg/storage is not about cluster storage, though.

@lavalamp @smarterclayton @wojtek-t Who would you like to be in the initial reviewers list?

**Comment by smarterclayton** [comment]
@liggitt, someone involved in the recent etcd3 work.

It should be a subset of the apimachinery owners under that sigs work.  We
should do a few clarifying refactors post 1.3 to make that clearer.

On May 23, 2016, at 7:36 PM, Brian Grant <notifications@github.com> wrote:

BTW, area/component owners are listed here:
https://github.com/kubernetes/kubernetes/wiki

Confusingly, pkg/storage is not about cluster storage, though.

@lavalamp <https://github.com/lavalamp> @smarterclayton
<https://github.com/smarterclayton> @wojtek-t <https://github.com/wojtek-t>
Who would you like to be in the initial reviewers list?

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/26118#issuecomment-221126732>

**Comment by dchen1107** [comment]
pkg/storage actually is the backend package for apiserver, not real storage related work.

**Comment by AdoHe** [comment]
I agree with @dchen1107 pkg/storage is not real etcd storage related work, we should assign different OWNERS.

**Comment by wojtek-t** [comment]
I'm happy to be one of the owners.

**Comment by AdoHe** [comment]
I'm happy to be one of the owners too if possible.

**Comment by lavalamp** [comment]
@fejta: Let's start with this list: @wojtek-t, @liggitt, @lavalamp, @timothysc, maybe @xiang90 if he wants.

@AdoHe: We're looking for people who've contributed a significant amount of code to this particular directory and understand the goals in the area deeply-- I appreciate your enthusiasm but this may not be the best place for you to help review quite yet. :)

**Comment by xiang90** [comment]
@lavalamp Sure. I would like to review/improve the storage related code.
