### ISSUE TITLE
Node e2e tests run against same releases and targets as e2e

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/kubernetes#26213]
Cluster e2e tests run against several different environments such as previous releases and GKE.  We need to run against the same targets.  May tie in to #26212

**Comment by dchen1107** [comment]
cc/ @vishh and @timstclair

**Comment by vishh** [comment]
@pwittrock Are the branches controlled via jenkins?

**Comment by pwittrock** [comment]
The different environments are separate jenkins jobs.

**Comment by vishh** [comment]
Node e2es were not part of the CI tests as of v1.2. So I don't think it makes sense to create node e2e jobs for v1.2 release.
Once v1.3 branch is cut, I can create a clone of the existing node e2e CI job and have it run against `release-1.3` branch.
I'm lowering the priority since there is nothing to do as of now.
