### ISSUE TITLE
livenessProbe and readinessProbe always fails

### ISSUE THREAD

**Issue by NiclasHedam** [kubernetes/kubernetes#26260]
No matter what I do, the probes always fails.

`kubelet gke-cluster-1-default-pool-441034bf-vddb}	spec.containers{web-http}	Warning		Unhealthy	Readiness probe failed: Get http://10.112.2.4:80/health_check: read tcp 10.112.2.4:80: use of closed network connection`

.. or from another pod ..

`{kubelet gke-cluster-1-default-pool-441034bf-vddb}	spec.containers{web-http}	Warning	Unhealthy	Readiness probe failed: Get http://10.112.2.5:80/health_check: dial tcp 10.112.2.5:80: connection refused`

But If I do 
`kubectl exec web-http-1321555595-6cpae -- curl -I http://10.112.2.5:80/health_check`, 
the results will be `HTTP/1.1 200 OK` as expected.

My probes are connecting to one of the two container ports defined in my Deployment configuration.

**Comment by a-robinson** [comment]
Please re-post your question to [stackoverflow]
(http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support
are posted so that we can improve our efficiency in responding to your requests,
and to make it easier for you to find answers to frequently asked questions and
how to address common use cases.

We regularly see messages posted in multiple forums, with the full response
thread only in one place or, worse, spread across multiple forums. Also, the
large volume of support issues on github is making it difficult for us to use
issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to
ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to
similar questions, and also familiarize yourself with:

  * [user guide](http://kubernetes.io/docs/user-guide/)
  * [troubleshooting guide](http://kubernetes.io/docs/admin/cluster-troubleshooting/)

Again, thanks for using Kubernetes.

The Kubernetes Team
