### ISSUE TITLE
Add test for running k8s clusters in non-us GCE zones

### ISSUE THREAD

**Issue by adityakali** [kubernetes/kubernetes#26361]
I am not sure if there is already a test for this, but we should catch issues like #26350 sooner.

@roberthbailey @dchen1107 @wonderfly @andyzheng0831

**Comment by roberthbailey** [comment]
The only non-US zones that I see in https://github.com/kubernetes/test-infra/blob/master/jenkins/job-configs/kubernetes-jenkins/kubernetes-e2e.yaml are for the GKE prod tests that are running in asia. There is no coverage for europe at all.

**Comment by ixdy** [comment]
Who's going to watch this new build? We have lots of noncritical builds which remain perpetually broken because they have no owner. I'm not sure adding to that list helps.

**Comment by roberthbailey** [comment]
We don't need a new build; we can move an existing build to a different zone. As a general principle, it seems as though we should spread our existing runs out across more than just a single region anyway.

**Comment by ixdy** [comment]
OK. Maybe we should wait until we're past the merge crunch to do this.

**Comment by roberthbailey** [comment]
The point of this issue was that *during* the merge crunch a change was made that was only caught by manual testing. We have no idea if other changes are merging that are breaking us in a similar way. Having e2es spread among zones/regions so that we at least know that basic cluster creation is working seems like it should be part of the test surge.

/cc @lavalamp

**Comment by ixdy** [comment]
We're testing one of the GCE builds in europe now. GKE will take more work on the internal side to support.
