### ISSUE TITLE
the docker-mutinode worker.sh output a 'no such file or directory' error

### ISSUE THREAD

**Issue by earthIsAPrisonIfYouNotAwareItCanNotOut** [kubernetes/kubernetes#26630]
# I have run the script in two place and get same result.

## vagrant virtualbox
- os : ubuntu 14.04
- docker version : 1.11.1

## aws ec2 
- os : aws linux t2.micro
- docker version : 1.9.1

the same output :

> sudo ~/kubernetes/docs/getting-started-guides/docker-multinode/worker.sh
> K8S_VERSION is set to: 1.2.4
> FLANNEL_VERSION is set to: 0.5.5
> FLANNEL_IFACE is set to: eth0
> FLANNEL_IPMASQ is set to: true
> MASTER_IP is set to: 192.168.1.104
> ARCH is set to: amd64
> ........
> Status: Downloaded newer image for quay.io/coreos/flannel:0.5.5
> Error response from daemon: lstat /var/lib/docker-bootstrap/devicemapper/mnt/fcd
> abf4f07474aa969c042641ab25a6a988bee18dda961c3455caba2d0d95d3f/rootfs/tmp/flannel
> /subnet.env: no such file or directory

new to kubernetes , so just have a try , do not make fun of me.

**Comment by a-robinson** [comment]
Please re-post your question to [stackoverflow]
(http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support
are posted so that we can improve our efficiency in responding to your requests,
and to make it easier for you to find answers to frequently asked questions and
how to address common use cases.

We regularly see messages posted in multiple forums, with the full response
thread only in one place or, worse, spread across multiple forums. Also, the
large volume of support issues on github is making it difficult for us to use
issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to
ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to
similar questions, and also familiarize yourself with:

  * [user guide](http://kubernetes.io/docs/user-guide/)
  * [troubleshooting guide](http://kubernetes.io/docs/admin/cluster-troubleshooting/)

Again, thanks for using Kubernetes.

The Kubernetes Team
