### ISSUE TITLE
Known issues for Kubernetes 1.3 release

### ISSUE THREAD

**Issue by dchen1107** [kubernetes/kubernetes#27076]
It is the time to collect all known issues for our coming release now. And runtimes' known issue are tracked separately: docker 1.10.X (#19720), docker 1.11.X (#23397), rkt (https://github.com/kubernetes/kubernetes/issues/26201)

cc/ @thockin @bgrant0607 @matchstick @davidopp @lavalamp @roberthbailey @fgrzadkowski 

cc/ @timothysc @kubernetes/goog-node @yifan-gu @philips

**Comment by timothysc** [comment]
So we can link to our errata once it's all said and done, we're lagging the 1.3 release, and it's still in progress.  /cc @runcom

**Comment by bgrant0607** [comment]
This needs to make its way into the release notes.
cc @david-mcmahon

**Comment by idvoretskyi** [comment]
Tracking to be added to Kubernetes-PM.

**Comment by timothysc** [comment]
Here is the current patch-set thus far ( https://github.com/docker/docker/compare/v1.10.3...runcom:docker-1.10.3-stable ) , we are still finding+fixing atm.

**Comment by david-mcmahon** [comment]
We don't currently have any mechanism to track and scrape "known issues".  That has been one of the hand curated items of release notes.  This issue is a good start at least to keep them all in one place for 1.3.  If we can agree on this, or some other format, going forward we can build functionality to extract them in an automated fashion.

Maybe for ease (and less moving parts), we simply keep a file in the tree called docs(or .)/known_issues.md (tracked history via PRs).  At branch/release time, we pull the file in-line into the release notes (CHANGELOG.md) and then delete the known_issues.md file.

**Comment by yifan-gu** [comment]
@dchen1107 FYI the rkt docs is merged into 1.3 release branch https://github.com/kubernetes/kubernetes.github.io/pull/699

**Comment by luxas** [comment]
Small question:
Which versions of docker are supported in the v1.3 release and which versions are targeted for v1.4?

(Couldn't find the info anywhere else)

**Comment by yujuhong** [comment]
@luxas release v1.3 should be compatible with docker v1.9, 1.10, and 1.11. The version that we did thorough testing in GCE+GCI is docker v1.11.

We don't have a target for v1.4 yet.

**Comment by goltermann** [comment]
This is an issue marked v1.3 and kind/documentation.  Can you get it fixed up this week?

**Comment by timothysc** [comment]
I'm not aware of known issues with docker 1.10.3 that we ship, we've actively patched the issues we uncovered (https://github.com/docker/docker/compare/v1.10.3...runcom:docker-1.10.3-stable).   However, we have not gone through a full re-based testing cycle yet, so we may uncover something in the next month.  If so, I'll be sure to update.  /cc @derekwaynecarr

**Comment by xiangpengzhao** [comment]
/sig release
We can close this stale issue now.
