### ISSUE TITLE
RFC: Re-evaluating `kubectl logs` --since flags

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#27154]
Log management on the node has been discussed in #24677. @vishh proposed that containers should log directly to files, and kubelet should access the log files directly without going through the runtime.
(More discussion and details in the original issue #24677)
A main part of the idea is for kubelet to create a designated log directory (e.g., `/var/log/pods`), and ask the container runtime to store the stdout/stderr logs in the per-pod subdirectory (e.g., `/var/log/pods/<POD_UID>`) with a given file name. This approach has the following benefits:
- [node] This detaches log's lifecycle from container's -- making disk space accounting/management on the node easier. 
- [cluster] kubelet can provide any log collector (e.g., fluentd) a log directory (e.g. `/var/log/pods`), where pod/container metadata such as name/namespace/uid can be extracted easily from the file paths. This means that log collector only has to integrate with kubernete once, and it can support all container runtimes (provided that the collector understands the log format used by the container/runtime). This reduces one more integration pain point for new runtimes.

This solution assumes that kubelet treats log files as blobs, i.e., it does not need to know the logging formats (for a good reason).
On the other hand, although a good cluster logging setup is essential to production workloads, `kubectl` provides access to container logs for convenience.  kubelet not knowing the log format means that even though it can serve the raw log for `kubectl logs`, it will not be able to support flags to filter logs by timestamps.

So, here are the questions: How important is it to support the filtering feature in `kubectl logs`? Is it worth imposing a log format for runtimes (IMO, no) to support this feature? 

p.s., There are other workarounds but none of them look too appealing. E.g., kubelet (or a separate process) can parse the logs based on a few common known formats, etc.

EDIT: `kubectl logs` does **not** always works. The current implementation relies on `docker logs`, which only works with json and journald logging drivers.

/cc @kubernetes/sig-node @vishh @mtaufen 

Ref: The current `kubectl logs` usage:

```
Flags:
  -c, --container="": Print the logs of this container
  -f, --follow[=false]: Specify if the logs should be streamed.
      --include-extended-apis[=true]: If true, include definitions of new APIs via calls to the API server. [default true]
      --limit-bytes=0: Maximum bytes of logs to return. Defaults to no limit.
  -p, --previous[=false]: If true, print the logs for the previous instance of the container in a pod if it exists.
      --since=0: Only return logs newer than a relative duration like 5s, 2m, or 3h. Defaults to all logs. Only one of since-time / since may be used.
      --since-time="": Only return logs after a specific date (RFC3339). Defaults to all logs. Only one of since-time / since may be used.
      --tail=-1: Lines of recent log file to display. Defaults to -1, showing all log lines.
      --timestamps[=false]: Include timestamps on each line in the log output
```

**Comment by vishh** [comment]
cc @kubectl 

Appreciate the detailed summary @yujuhong. 
One thing that I'd like to add is the lack of clarity around the *required* and *optional* features from a product UX standpoint. A user can switch to a different logging driver in docker today and `kubectl logs` will not work. So as it stands today, `kubectl logs` is an *optional* feature.

**Comment by yujuhong** [comment]
> One thing that I'd like to add is the lack of clarity around the required and optional features from a product UX standpoint. A user can switch to a different logging driver in docker today and kubectl logs will not work. So as it stands today, kubectl logs is an optional feature.

Thanks for pointing that out. I left it out by accident.

**Comment by yifan-gu** [comment]
cc @kubernetes/rktnetes-maintainers @philips @jonboulle

**Comment by yifan-gu** [comment]
So for the rkt, the journal log file lives in `$pod_uuid/stage1/rootfs/var/log/journal/$rkt_uuid/system.journal`.

We could probably mount the file so that journal appears in `/var/log/pods/<POD_UID>`.
For `kubectl logs` to work with the journal, we could still go through the rkt runtime.

**Comment by ncdc** [comment]
cc @kubernetes/rh-ux

**Comment by kargakis** [comment]
@kubernetes/kubectl

**Comment by smarterclayton** [comment]
Ultimately having a way to associate / retrieve meaningful logs is important when dealing with apps in bulk, but specialized apps often don't need that flexibility.  Trying to find an LCD between access to logs and efficiency and flexibility probably doesn't require indexing, and I do think there is value in moving logging up the stack in terms of abstraction is good (perhaps by providing a higher level log adapter).  

But ootb, it's very difficult to overstate how important O(1) logs access being able to do some minimal traversal of older logs is for initial platform users.  Maybe we can find a simple balance there.

**Comment by pskrzyns** [comment]
cc @jjlakis

**Comment by philips** [comment]
We discussed this at length yesterday with @vishh, @thockin, @yujuhong and others in f2f so I am reporting out.

The overall sentiment in the group was `--since` is important user experience to users who get paged and want to dig in and filter down to actionable data. I feel that `kubectl logs --since` is a mandatory feature and my personal data points are my own usage of k8s and the CoreOS SRE team at CoreOS. (cc @colhom @brianredbeard @bison @cgag)

The only way to implement this behavior is for the Kubelet or the container runtime to decorate each logline with a timestamp. This means we end up dictating a file format that the kubelet knows how to consume in the log directory.

The discussion explored other ideas:

- Parsing timestamps from applications or standardizing the timestamp. This is untenable as every app uses different logging formats and we will never fix every app to "log right".
- Let the log collection daemon decorate. However, if a log collection daemon crashes for a bit, hits a file descriptor limit, or has some other issue it will lose the timestamp metadata as well.

We also explored how log centralization/indexing systems might consume these logs:

1) kubectl logs is an option but might be lossy due to kubelet arbitrary truncation
2) Document the dictated log directory file format so "high efficiency" collectors can go down to the filesystem API

**Comment by timothysc** [comment]
> The only way to implement this behavior is for the Kubelet or the container runtime to decorate each logline with a timestamp. This means we end up dictating a file format that the kubelet knows how to consume in the log directory.

Is there a reason not to invoke separation of concerns here?  Operators will typically have their own federated logging system, and hook in their own log drivers.  Be it journal, syslog, whatever, and they are typically far more complete then any adaptation we would provide.

My concern is that we may venture to close to a yet another opinionated event horizon. 

Do we have an exact finite set of use cases that kube will handle, from there we offload to some 3rd party system?    b/c ```kubectl logs --since``` is not finite, and I'd rather provide plugin adapters to other systems.

**Comment by sosiouxme** [comment]
IMHO we want log lines decorated with consistent timestamps even if `kubectl logs` is not the mechanism for retrieving them - say, if fluentd reads in the logs and sends them off to ElasticSearch or Splunk; it would face the same problem of figuring out what time to associate each line with after the fact.

This conflicts with the idea of letting apps write arbitrary log formats in their logging volume, but perhaps a compromise is possible. What if we expected that stdout/stderr from the app went to a specified file format/name within the logging volume making that amenable to `kubectl logs --since` and automated rotation, but other files had no such format restriction and could only be retrieved in total or paged through like a regular file? It seems like it would satisfy the most use cases.

**Comment by portante** [comment]
@philips, are we saying here that Kubelet has to modify the payload of a log line to add a timestamp?  Why can't we always provide the log line as a JSON record, "{ message: 'asdf', timestamp: YYYY.MM.DDTHH:mm:ss.SSSZ }"?

Maybe this is a naive question, but it seems like we have the opportunity to provide a reasonable behavior this way to accommodate various needs of consumers.

**Comment by yujuhong** [comment]
@tmrts (thanks!) has volunteered to write up a proposal for logging based on the discussion of #27154 and #24677. Assigning the issue to him.
