### ISSUE TITLE
Limit the nodes on which NodePort is exposed

### ISSUE THREAD

**Issue by krmayankk** [kubernetes/kubernetes#27247]
For every Kubernetes service, the Nodeports are currently proxied into the service pods from every node. This is all good. 
In the scenario if you wanted to run two or three different overlays in a single kubernetes cluster, just to segregate the cluster for security requirements, this presents a problem. 

Suppose i have two overlays:-
1: overlay 1 on subnet 1
2: overlay 2 on subnet 2

A service created in overlay 1(targets pods on overlay 1), will create iptable rules on nodes that belong to overlay2. If a packet reaches node on overlay2, it will never be able to reach pods targeted by this service, since the pods are on overlay 1 subnet 1.

In this situation, it would be desirable  to have the service expose nodeports on only a subset of the nodes belonging only to overlay1.

**Comment by krmayankk** [comment]
@thockin  what do you think about this one ?

**Comment by thockin** [comment]
I don't think this is the right approach.  It's fairly complex to describe and overlaps with nascent NetworkPolicy.  Unless you're running out of NodePorts (in which case I am impressed), it's a false economy.  It doesn't offer real multi-tenancy, because pods in overlay1 can still access nodes in overlay 2 (or can't access nodes at all, in which case this matters not at all).  I'd rather think about multi-tenancy more holistically - it's a hard problem, and this is just a piece of it.

A further point is how one would configure this.  It's too important to leave to users, so it would have to be driven by some policy object, which again arrives at multi-tenancy.  I *might* be able to see something like this as part of a larger multi-tenant effort, which included dedicated machines, policy objects, Network objects, etc.

Are you actually solving a real problem or just theorizing?

**Comment by krmayankk** [comment]
@thockin thanks we are indeed solving this for our infrastructure. We want to run different customers on different network boundaries segregated by acls, since we dont yet trust the container as a security boundary. So for the same k8s cluster, we have two sets of minions for two different customers.  the nodes in one set can never talk to nodes in another set, which also means the pods in one set would never be able to talk to nodes in another set as well.  The external loadbalancers, will be programmed to talk to one set or the other based on the service they are trying to reach. So this basically makes the unwanted nodeports opened for one service(belonging to one set of nodes) on the other set of nodes useless. I agree , we are not really running out of nodeports, but it makes logical sense to limit the nodeports to a set of nodes. I agree this is not true multi tenancy but still makes a lot of sense imo. Any chance you think if  we wanted to submit a PR for this, would it make it ?

**Comment by krmayankk** [comment]
@thockin any thoughts on this.

**Comment by thockin** [comment]
I'm really not keen on this without understanding the rest of multi-tenancy.  Specifically, the whole notion of nodeports kind of violates multi-tenancy.  Before a PR we would need a really clear proposal with concrete use cases, an API design, and an evaluation of the alternative options, up to and including distinct clusters per user.

We have a semi-regular sig-network call - you may want to join...

@kubernetes/sig-network

**Comment by krmayankk** [comment]
@thockin sounds good. How can i join this call and how do start with a proposal. Any pointers ?

**Comment by thockin** [comment]
https://github.com/kubernetes/community/wiki/SIG-Network

**Comment by rocketspacer** [comment]
What was the outcome of this?

We have a special application deployed in a specific set of nodes using nodeSelector + taints/tolerations.

We observed performance side effects/bottlenecks as the traffic goes through some of our smaller nodes that we use for less important workload.
