### ISSUE TITLE
No GKE CPU usage for own containers on Stackdriver

### ISSUE THREAD

**Issue by admiralobvious** [kubernetes/kubernetes#27244]
Hello,

I have noticed the GKE Container CPU Usage in Stackdriver dashboards only reports CPU usage for containers that are created by default (kube2ky, glbc, etcd, heapster and so on) when creating a container cluster on GCP but not for containers I have created for my own applications. This used to work back in Kubernetes 1.1.x. The GKE Container Memory, Disk usage and Page Faults graphs correctly displays data for my own containers though.

My 5 clusters (4 on one account, 1 on my personal account) are all on Kubernetes 1.2.4 and all have Cloud Monitoring/Logging enabled.

Was this feature changed, disabled or removed in 1.2.x?

Thank you!

**Comment by chrislovecnm** [comment]
Do you have the stackdriver agent installed?  Also you may want to post this on heapster issues.

**Comment by piosz** [comment]
cc @a-robinson @mwielgus

**Comment by a-robinson** [comment]
To be precise, those default graphs show CPU *utilization*, not usage time. Utilization is only a meaningful metric for containers that have a CPU limit specified, since it's effectively `CPU usage time / reserved cores`. The system containers you list have a CPU limit attribute specified on them, while presumably your pods don't.

On 1.1.x, IIRC the system would use an arbitrary low number as the limit if there wasn't one. This mean that a utilization could always be calculated, but it was often misleading given that containers could go well over 100% utilization.

**Comment by admiralobvious** [comment]
@a-robinson Thanks!
