### ISSUE TITLE
gcr/google_containers/kubelet no longer exists and local-up-cluster.sh silently fails

### ISSUE THREAD

**Issue by rootfs** [kubernetes/kubernetes#27281]
refer to this line https://github.com/kubernetes/kubernetes/blob/master/hack/local-up-cluster.sh#L387

``` bash
# docker pull gcr.io/google_containers/kubelet
Using default tag: latest
Pulling repository gcr.io/google_containers/kubelet
Tag latest not found in repository gcr.io/google_containers/kubelet
```

@jayunit100

**Comment by lavalamp** [comment]
I think it's assuming that you've built locally first. It doesn't literally push that image to gcr.io.

**Comment by rootfs** [comment]
@lavalamp kubelet image is not built by default https://github.com/kubernetes/kubernetes/blob/master/build/common.sh#L94

**Comment by whitlockjc** [comment]
I've been running into this as well.

**Comment by whitlockjc** [comment]
I think I'm going to see if I can get `hack/local-up-cluster.sh` to build `gcr.io/google_containers/kubelet` locally when `DOCKERIZE_KUBELET` is set.

**Comment by whitlockjc** [comment]
It looks like this was removed here: https://github.com/kubernetes/kubernetes/commit/eb652814db401059de9f83074ce997240073e2c0  Seeing that `DOCKERIZE_KUBELET` requires this, is it work bringing back `cluster/images/kubelet`?

**Comment by whitlockjc** [comment]
I am able to get it working with this diff: https://gist.github.com/whitlockjc/915fc08984ff80089e8179f47a491106  Unfortunately, as documented in the Gist, it doesn't really make the Dockerized `kubelet` work because of its requirements for access to the host and Docker not providing it.  _(This could be a Docker for Mac issue.)_  If this looks reasonable, I don't mind turning this into a PR.

**Comment by kargakis** [comment]
Guess this is not an issue anymore, please reopen otherwise.
