### ISSUE TITLE
kubernetes-e2e-gce-ubernetes-lite should verify the cluster created is actually multi-zone

### ISSUE THREAD

**Issue by jlowdermilk** [kubernetes/kubernetes#27372]
Filing separate follow up from #27150. The issue should have been caught by http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gce-ubernetes-lite/ failing. The suite needs a specific feature test that e.g. looks at node labels to verify multiple zones are present.

cc @quinton-hoole

**Comment by quinton-hoole** [comment]
@jlowdermilk Yes, you make a good point.  The tests currently work the other way around.  If the tests detect a multi-zone cluster, they run, otherwise they skip.  This makes it safe to run against any cluster, and makes test configuration much simpler.  

To achieve what you suggest, we will need to add a test for multi-zone that is skipped by default (i.e. in all other test jobs), and only runs on that test job (kubernetes-e2e-gce-ubernetes-lite), failing if multiple zones are not detected.

**Comment by goltermann** [comment]
@quinton-hoole should we target this one for v1.4, or bump it to 1.5?

**Comment by goltermann** [comment]
Moving out of v1.4 as this is a P2.

**Comment by irfanurrehman** [comment]
This issue was labelled only for sig/multicluster and is thus moved over to kubernetes/federation#49.
If this does not seem to be right, please reopen this and notify us @kubernetes/sig-multicluster-misc.
/close
