### ISSUE TITLE
No more KubeDescribe verify.

### ISSUE THREAD

**Issue by spxtr** [kubernetes/kubernetes#27414]
It looks like 18e7a3eb243f4fa74ea3258dad946999c327da01 deleted the check for `KubeDescribe`, and since then `test/e2e/third-party.go` acquired a bare `Describe`. @jayunit100

**Comment by jayunit100** [comment]
Enforcing KubeDescribe was a stop gap while we were working with the ginkgo community to support hierarchichal namespaces.  

We can use `--ginkgo.scanRegexFilePath=true && --ginkgo.focus=k8s` to find all K8s.io tests now.  So we can survive without maintaining KubeDescribe.

I'm open to adding KubeDescribe if folks need it for another use case, but `scanRegexFilePath` has a functionally workaround, and am an advocate of it, if for no other reason, as a way to make the E2E setups a little more rigorous

Feeback from @sig-testing, @timothysc  ?  Im happy to add KubeDescribe back in if otherw want it as well.  OTherwise i would make priority on this quite low since we have a functional workaround for hierarchichally differentiating kuberentes tests from non kubernetes tests.
