### ISSUE TITLE
Unable to use commas in --from-literal when creating a configMap

### ISSUE THREAD

**Issue by mmontagna** [kubernetes/kubernetes#27454]
Creating a config map with a --from-literal argument fails when the literal value contains commas. 

Eg.
```
kubectl create configmap test \
	--from-literal=seeds=A,B
```

The error I get is:
```
error: invalid literal source B, expected key=value
```

**Comment by wu8685** [comment]
So, is it supposed to be valid to get value "A,B" for key "seeds" ?

**Comment by mmontagna** [comment]
Yes that is what I expect, or if there was some way to quote it such that "A,B" was the resulting value of seeds.

**Comment by wu8685** [comment]
@mmontagna
It happens because cmd flag parser expects the from-literal (or from-file) value is in the form key=value (where the value doesn't contain comma) or key1=value1,key2=value2...

@pwittrock 
I find the [k8s doc](http://kubernetes.io/docs/user-guide/configmap/) doesn't mention the second form. So how about we just disable the second form? I think it is a convenient solution.

**Comment by AdoHe** [comment]
@pwittrock @kubernetes/kubectl Actually what @wu8685 suggested sounds reasonable to me. Multiple from-literal should be used to support multiple key,value pairs, we should have no constraint on value format. I think @wu8685 has extra bandwidth to do this, but first we should make a decision.

**Comment by smarterclayton** [comment]
Supporting commas in arguments was an unintentional mistake - we did
it for the etcdservers argument but never corrected the pattern

We need to fix this, because we have blocked users from using certain
values.  There has to be some consideration for back compat.

We can make stringslice *not* split on comma when more than one flag
arg is provided (so --foo=a,b works the same).  That still blocks a
user who wants to specify a single flag value with comma.  So we need
to treat this as a bug and fix the core issue (most commands need to
be migrated to use a "correct" non splitting flag).

**Comment by AdoHe** [comment]
@smarterclayton As with consideration for back compat, the original behavior is that if we use this: `--from-literal=key=a,b`, `b` would be parsed as a key but not the value of `key` which  is not what user expect. So typically there are two formats we need to think about: `--from-literal=key=a,b` and `--from-literal=key1=a,b,key2=c`. IMO the second format is not a "correct" usage, we should avoid this. I think from code level, we could support both of these formats, the logical would be a little bit complicated. wdyt?

**Comment by pwittrock** [comment]
I agree that we do not want to support the second format since it adds more complexity and is harder to read than using multiple --from-literal args.  My only concern is changing the behavior for folks who depend on the second form.  We can put in a release note to notify users, but I wonder if there is anything else we can do.

**Comment by smarterclayton** [comment]
I think we just made a mistake here, we introduced a bug, and we are
really, really sorry that we didn't do it right.  Commas are not so
uncommon in both config maps and secrets that we aren't going to keep
hitting this.

I think we need to err on the side of ensuring that users can exactly
specify the values they need, over the convenience of the multi/value/key
setup.

On Mon, Jul 18, 2016 at 12:43 PM, Phillip Wittrock <notifications@github.com

**Comment by AdoHe** [comment]
```
I think we need to err on the side of ensuring that users can exactly
specify the values they need, over the convenience of the multi/value/key
setup.
```
Yes. @wu8685 could you please fix this?

**Comment by wu8685** [comment]
OK, I will fix it ASAP.

**Comment by wu8685** [comment]
hi @eparis ,
I think the `FlagSet.GetStringSlice()` method hasn't considered the case that some of the `stringSliceValue.value`s contain `,`.
```
// line 44 in github.com/spf13/pflag/string_slice.go

func (s *stringSliceValue) String() string { return "[" + strings.Join(*s.value, ",") + "]" }

func stringSliceConv(sval string) (interface{}, error) {
  	sval = strings.Trim(sval, "[]")
	  // An empty string would cause a slice with one (empty) string
	  if len(sval) == 0 {
		    return []string{}, nil
	  }
	  v := strings.Split(sval, ",")
  	return v, nil
}

// GetStringSlice return the []string value of a flag with the given name
func (f *FlagSet) GetStringSlice(name string) ([]string, error) {
	  val, err := f.getFlagType(name, "stringSlice", stringSliceConv)
	  if err != nil {
		    return []string{}, err
	  }
	  return val.([]string), nil
}
```

`stringSliceValue.String()` just joins slice values with `,`, as a result, it is unable to differ the comma in values.

**Comment by smarterclayton** [comment]
Yeah, we should clone StringSlice into two classes - one that handles
splits, and one that doesn't.  Starting with these types, we need to go
through all StringSlice use in the code and find whether they should
support splits or not.

**Comment by smarterclayton** [comment]
We can start with this one in particular and then do the rest in a
follow-up.

**Comment by wu8685** [comment]
I have send a [PR](https://github.com/spf13/pflag/pull/82) to fix the issue I mentioned before in pflag.
Then we can go on to fix this one.

**Comment by eparis** [comment]
the only bug i'm seeing is that in pflag `Set` is (correctly) using `csv` but `stringSliceConv` is incorrectly not using `csv` to parse the `,`'s...   That is the bug which should be fixed...

**Comment by wu8685** [comment]
I think `csv` has correctly parsed the `,` and store flag value in `stringSliceValue.value` in correct form. But the `value` is incorrectly joined and split by `,`.
@eparis I have sent a PR to fix this bug. After that we can support `,` by `--from-literal="A,B"`
could you please take a look at this [PR](https://github.com/spf13/pflag/pull/82) ?

**Comment by pwittrock** [comment]
@wu8685 Are you still working on this?  I see your PR is not to merge against the upstream repo.

**Comment by smarterclayton** [comment]
I commented on the upstream PR, but CSV escaping is not a solution.  Commands need to opt in to getting comma separating behavior, rather than tell users to escape their strings.  It is surprising for end users to treat `-a https://something:9000/b,c` as two values, or `-a /usr/lib/local,other/` as two values.  We need to fix this by introducing a new StringSlice that does not do comma separation.

**Comment by wu8685** [comment]
I agree to add a `StringSliceExact` type as you mentioned on that PR. If no any questions, I will open a new issue on that ?

**Comment by smarterclayton** [comment]
SGTM

**Comment by eparis** [comment]
clayton is wrong here. the upstream library has a bug. It has always (properly) handled CSV at Parse() but if one used the GetStringSlice() helper instead of the direct variable set at flag definition it would improperly screw up the results. Now that I see the bug, we'll get it fixed upstream (with proper CSV escaping)

**Comment by wu8685** [comment]
The [PR](https://github.com/spf13/pflag/pull/82) has been merged. It is now supporting `,` by `--from-literal="seeds=A,B"`
If it is ok, we can update dependency to fix the issue.

**Comment by smarterclayton** [comment]
Just to make sure this is closed off. If you accept a flag multiple times
(`--file INPUT1 --file INPUT2`) you should not be processing INPUT1 or
INPUT2 in order to accept more inputs (it should not be possible to split
INPUT1 to get INPUT3 or INPUT4).  Was GetStringSlice() doing that?  Or are
you saying that you believe that the common case for all string flags that
you can specify multiple times should be to support commas, and that to
bypass commas you have to provide quotes?

**Comment by eparis** [comment]
Before pflag was fixed you had 2 different behaviors. Given something like:
```
flagvar := string{}
pflag.Commandline.StringSliceVar(&flagvar, "flag", []string{}, "my string slice")
```
if you called a program with:
```
---flag="a,b" --flag="c,d" --flag=e,f
```
you would end up with:
```
flagvar = []string{"a,b", "c,d", "e", f"}
(len flagvar == 4)
```
But if you checked:
```
pflag.Commandline.GetStringSlice("flag")
```
you would end up with:
```
getstringslice = []string{"a", "b", "c", "d", "e", "f"}
(len == 6)
```

**Comment by eparis** [comment]
After the fix the behavior of both `flagvar` and `GetStringSlice()` is the same. Given:
```
--flag="a,b" --flag="c,d" --flag=e,f
```
You will get
```
[]string{"a,b", "c,d", "e", f"}
```

**Comment by fabianofranz** [comment]
We need to have a string slice flag type that is dumb about the value it gets and just put everything it gets from multiple ocurrences of `--flag` in a slice. No CSV parsing, no nothing. So that

```
cmd --value=this,is,a,value --value=another,value --value="another,one"
```
 
makes value to be

```
[]string{"this,is,a,value", "another,value", "another,one"}
```

if that's another flag type (not StringSlice) I'm ok with it, but we need to have this non-parseable-just-the-strings type. Also apart backwards compat I'd call the dumb one `StringSlice`, and this one something like `StringSliceCSV` (but yeah I know backwards compat).

This is a comment more for pflag than Kube or how to fix this issue, but I think we are making an unexpected assumption when we try to be smarter about something called just "string slice".

Now about this issue: what @smarterclayton is suggesting is that, to address this mistake we did in past, to have a string slice flag (probably with another name) that behaves like `StringSliceCSV` (after the fix, like [this](https://github.com/kubernetes/kubernetes/issues/27454#issuecomment-241860570)) if you provide `--value` just once, but behaves like my dumb `StringSlice` if it's provided more than once `--value=... --value=...`.

**Comment by smarterclayton** [comment]
Some examples of things that would be command line flags that can have
commas in them where splitting the flag on comma is surprising:

1. Filenames
2. Environment variables
3. User names (anything from LDAP)
4. Template parameters
5. Human readable messages

I agree there are places where you want the "quick split" values:

1. server hostnames
2. simple key names (where the name can't contain a comma)

But we have to have the generic solution that isn't surprising, and people
should have to make a choice to use "quick split".

**Comment by eparis** [comment]
This should move to pflag, since that's where we'll need a fix. StringSlice and IntSlice act exactly the same and that is a good thing. If there was a mistake it was adding the `--flag=... --flag=...` support to `*Slice` at all.

At first I liked the idea of making it be a CSV parser if there was a single `--flag=...` and a non-parser if `--flag=... --flag=...` but that seems too inconsistent and is magic. If I did `--user=dc=redhat,dc=com,cn=eparis --user=dc=redhat,dc=com,cn=fabiano` it would work, but when I removed `fabiano` it would fall apart in a weird impossible way to know. I'd rather both broken or both work rather than the inconsistency.

If people want a nonCSV version that's ok, I'll happily merge it. It doesn't make sense to have a nonCSV IntFlag, so we don't need to worry about that one...

**Comment by fabianofranz** [comment]
@eparis are you saying that we should not have added the form `--flag=v1 --flag=v2` specifically to `*Slice`, or we should not have added it at all? Because providing a list of options through multiple occurrences of the given `--flag` [is POSIX](http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap12.html#tag_12_01) so not supporting it in Cobra is not an option in my opinion.

**Comment by eparis** [comment]
should not  have added it to `*Slice`   I agree that a new non-CSV `StringSlice`like flag makes sense.

**Comment by wu8685** [comment]
I made a mistake to focus on quote-escaping before. Actually, we need this escape, when it is `--from-literal="key=hello world"`.
I think what we need now is a string array from pflag, maybe I can call it `StringArray`. This `StringArray` will handle all flags `from-literal` without spliting or any other processing. Right?

**Comment by eparis** [comment]
@wu8685 I'm not sure what a good name is, but yes, there seem to be plenty of places such a flag type would be useful.

**Comment by fabianofranz** [comment]
@wu8685 Right. So to close off:

1. `pflag` needs an additional `[]string` type that doesn't do splitting, takes values as-is as provided by multiple `--flag=wu1 --flag=wu2 ...`.
2. `--from-literal=` will use it, so no more string splitting. Closes this issue. Needs a release note.
3. Other flags might also use it. @smarterclayton's [comment](https://github.com/kubernetes/kubernetes/issues/27454#issuecomment-241899449) gives an idea where to look for.
3. Naming: if we were on ground zero I'd vote for `StringSlice` or `Strings` (no splitting) and `StringSplit` or `StringSplitSlice` or `StringSliceCSV` (with splitting).
4. But there's backward compatibility. So we either
  * Keep `StringSlice` as is (with splitting) and add a new name for the one with no splitting. Backwards compatible. Ideas `StringArray`, `Strings`, `StringRawSlice`.
  * Remove `StringSlice` and add both with different names (e.g. `Strings` and `StringSplit`). Not backwards compatible but better to break builds than change the behavior which may lead to unexpected results for people already using it.

**Comment by wu8685** [comment]
I prefer `StringArray` considering backward compatibility.
@all If there is no other questions, I am going to open a issue in pflag to add this type.

**Comment by AdoHe** [comment]
@wu8685 please help fix the upstream and then update here, you own this issue now.

**Comment by wu8685** [comment]
opened the [issue](https://github.com/spf13/pflag/issues/89) on pflag

**Comment by wu8685** [comment]
[PR](https://github.com/spf13/pflag/pull/90) on pflag

**Comment by eparis** [comment]
@wu8685 thank you!

**Comment by fabianofranz** [comment]
@wu8685 thanks!

**Comment by wu8685** [comment]
I add a PR #33263 to update godep

**Comment by pwittrock** [comment]
@wu8685 @fabianofranz Can we close this issue now?

**Comment by fabianofranz** [comment]
@pwittrock yes, this can be closed.
