### ISSUE TITLE
Deleting Pods with disconnected NFS volume makes kubelet unable to start new Pods

### ISSUE THREAD

**Issue by rootfs** [kubernetes/kubernetes#27463]
Steps to reproduce:
- create a Pod (call it Pod A) that uses an NFS volume
- watch Pod A run
- stop the NFS server that provides the NFS volume to Pod A
- delete Pod A.
- Now `kubectl get pod` shows the Pod A is terminating for ever.
- create another (different) Pod (call it Pod B), and the Pod B stays in Pending state for ever.

- restart the NFS server that provides the NFS volume for Pod A
- wait for a while
- Pod A is gone and Pod B is running

@kubernetes/sig-node

**Comment by yujuhong** [comment]
Sounds like kubelet was stuck at tearing down the volume. /cc @saad-ali

**Comment by rootfs** [comment]
It looks to me `HandlePodCleanups` hangs because it fails to read volume dir from dead NFS mount. As a result, syncLoop never returns.

**Comment by yujuhong** [comment]
Yes, that's what I meant :)

@saad-ali will have more idea whether this is being worked on.

**Comment by rootfs** [comment]
i tested letting HandlePodCleanups run in a goroutine and it seems to fix the problem.

**Comment by yujuhong** [comment]
Unfortunately, that doesn't actually address the root cause.. If the cleanup goroutine hangs, it'd still stop other resources from being cleaned up properly. It'd manifest in a different way.

In general, it's still good to run cleanup in a separate goroutine, but there are some caveats due to this pattern in `HandlePodCleanups`:
 1. Take a snapshot of all pods assigned to kubelet
 2. Get the current state of a resource (e.g., pod directory or volume)
 3. Compare the snapshot vs the state of the resource, and remove orphaned resources.
 4. Repeat (2)~(3) for a different resource.

If cleanup runs in a separate goroutine, we'll need to fix the pattern because "pods" may be modified by the syncloop, and the snapshot will be outdated.

**Comment by rootfs** [comment]
thanks for the clarity.

**Comment by yujuhong** [comment]
@rootfs np. I just found the comment I posted long ago with similar content
https://github.com/kubernetes/kubernetes/issues/13418#issuecomment-183146070

I think we still want a separate cleanup routine, but just need someone to put more thoughts into handling issues like this.

**Comment by saad-ali** [comment]
This code all got ripped out as of 12:16 PM PST today. See if you can get a repro with the new code. As long as Pod B is not referencing the NFS server it should not be blocked even if unmount for Pod A is blocked.

**Comment by wanghaoran1988** [comment]
After the pods hang there , "umount -l "  will resolve the pending issue ,not sure this will help or not.

**Comment by rootfs** [comment]
@saad-ali yes, latest code works!
