### ISSUE TITLE
kube-dns serializer doesn't exits

### ISSUE THREAD

**Issue by geoffhendrey** [kubernetes/kubernetes#27497]
This is my first time installing kubernetes. I am installing it on a mac using docker-machine. 

I followed the instructions here to install skydns on docker-machine kubernetes installation: http://kubernetes.io/docs/getting-started-guides/docker-multinode/deployDNS/

Here is the container log of my k8s_kubedns: https://gist.github.com/geoffhendrey/d1cde88087e8a71c3cd3f8850eac7613

As per the container log, the k8s_kubedns box shows:
I0615 23:35:16.993402       1 server.go:88] Using http://localhost:8080 for kubernetes master
I0615 23:35:16.993503       1 server.go:89] Using kubernetes API `<nil>`
I0615 23:35:16.993614       1 server.go:129] Starting SkyDNS server. Listening on port:10053
I0615 23:35:16.993652       1 server.go:136] skydns: metrics enabled on :/metrics
I0615 23:35:16.993664       1 dns.go:139] Waiting for service: default/kubernetes
I0615 23:35:16.994068       1 logs.go:41] skydns: ready for queries on cluster.local. for tcp://0.0.0.0:10053 [rcache 0]
I0615 23:35:16.994156       1 logs.go:41] skydns: ready for queries on cluster.local. for udp://0.0.0.0:10053 [rcache 0]
E0615 23:35:17.045007       1 reflector.go:216] pkg/dns/dns.go:128: Failed to list *api.Service: serializer for text/html; charset=utf-8 doesn't exist
E0615 23:35:17.045291       1 reflector.go:216] pkg/dns/dns.go:127: Failed to list *api.Endpoints: serializer for text/html; charset=utf-8

My guess is that for some reason the api.Service is somehow pointing in the wrong place, hence it is getting a text/html returned when in fact it is expecting a JSON. Hence "serializer for text/html...doesn't exist"

when I point to localhost:8080 on the docker-machine I get expected:
{
  "paths": [
    "/api",
    "/api/v1",
    "/apis",
    "/apis/apps",
    "/apis/apps/v1alpha1",
    "/apis/autoscaling",
    "/apis/autoscaling/v1",
    "/apis/batch",
    "/apis/batch/v1",
    "/apis/batch/v2alpha1",
    "/apis/extensions",
    "/apis/extensions/v1beta1",
    "/apis/policy",
    "/apis/policy/v1alpha1",
    "/apis/rbac.authorization.k8s.io",
    "/apis/rbac.authorization.k8s.io/v1alpha1",
    "/healthz",
    "/healthz/ping",
    "/logs/",
    "/metrics",
    "/swaggerapi/",
    "/ui/",
    "/version"
  ]
}

everything in kubernetes seems to be functioning properly. I can use the kubectl client, ran the nginx service, etc.

Any ideas why the kubedns does not seem to work (and keeps crashing and being restarted).

**Comment by lavalamp** [comment]
(personal note: I think you've diagnosed the problem. maybe something else is listening on localhost:8080 from skyDNS's perspective.)

Please re-post your question to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases.

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to similar questions, and also familiarize yourself with:
   * [the user guide](http://kubernetes.io/v1.0/)
   * [the troubleshooting guide](http://kubernetes.io/v1.0/docs/troubleshooting.html)

Again, thanks for using Kubernetes.

The Kubernetes Team

**Comment by geoffhendrey** [comment]
This was caused by using latest k8s instead of stable. I have already filled a ticket on docs asking them to expunge the "latest" build as an option since it does not work with the DNS instructions as described in the tutorial.

**Comment by xynova** [comment]
I was facing the exact same issue where kubedns container was looking for the api on localhost:8080 on a worker node. Using the following flags to tell the container where the api was solved my problem

--kube-master-url 
--kubecfg-file

https://github.com/kubernetes/kubernetes/blob/0881419e48c542c9c95237b937445008c0f6fe29/cmd/kube-dns/app/server.go#L82

**Comment by xynova** [comment]
I am guessing the previous flags are not present in the new dns config files because minions are talking to the masters through ssh tunnels?

**Comment by jeffchanjunwei** [comment]
@xynova , I add '--kube-master-url=master_node_ip' as the args section of skydns-rc.yaml.base file. but it doesn't work. Is there any wrong?

**Comment by xynova** [comment]
@jeffchanjunwei, I had to go for the kubecfg-file approach because I was using ssl. I also had to mount some volumes to allow the CA to be picked up by the kube-config file. 

https://github.com/xynova/kubernetes-on-coreos/blob/master/ansible/roles/kube-master-extras/templates/dns-rc.yml.j2#L60

https://github.com/xynova/kubernetes-on-coreos/blob/master/ansible/roles/pre-kube/templates/cluster-kubeconfig.j2#L14

**Comment by jeffchanjunwei** [comment]
@xynova,thx.
