### ISSUE TITLE
can't start kubelet when set openstack as cloud-provider

### ISSUE THREAD

**Issue by lanceyang1992** [kubernetes/kubernetes#27528]
Hi,I'm new to k8s

I'm trying this example:
https://github.com/kubernetes/kubernetes/tree/release-1.2/examples/mysql-cinder-pd

my env is single node devstack and k8s，but when I follow the readme and restart my kubelet, it failed...

the command is:
kubelet --address=0.0.0.0 --port=10250 --hostname_override=lance-2 --enable_server=true --v=0 --api-servers=http://x.x.x.x:8080 --cloud-provider="openstack" --cloud-config=/etc/cloud_config

and **content of cloud_config is:**
[Global]
auth-url=http://x.x.x.x:5000/v2.0
username=admin
password=123456
region=RegionOne
tenant-name=admin
tenant-id=40600130ded84d0d8978b7b459de9f5c

and **the output is:**
 Could not load kubeconfig file /var/lib/kubelet/kubeconfig: stat /var/lib/kubelet/kubeconfig: no such file or directory. Trying auth path instead.

W0616 04:18:24.785109   19751 server.go:440] Could not load kubernetes auth path /var/lib/kubelet/kubernetes_auth: stat /var/lib/kubelet/kubernetes_auth: no such file or directory. Continuing with defaults.

E0616 04:18:25.610176   19751 server.go:291] Failed running kubelet: could not init cloud provider "openstack": got unexpected status code when reading metadata from http://169.254.169.254/openstack/2012-08-10/meta_data.json: 404 Not Found

could not init cloud provider "openstack": got unexpected status code when reading metadata from http://169.254.169.254/openstack/2012-08-10/meta_data.json: 404 Not Found

so,why this situation will occur? anything I did is wrong? or my environment is wrong?

any ideas? thanks!

**Comment by dims** [comment]
@lanceyang1992 the 404 shows that kubelet is not able to access the Metadata service from Nova/Neutron that kubernetes openstack provider needs to figure out where it's running. I guess the current assumption in the provider is that the kubelet is running in a VM running on OpenStack and hence it has access to the metadata URL.

**Comment by lanceyang1992** [comment]
@dims thanks for your reply.
 my environment is the openstack and k8s running on a same host,and both are single node.

whether my seettings are wrong?

what should I do to solve this problem?

thanks!

**Comment by lavalamp** [comment]
Please re-post your question to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases.

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to similar questions, and also familiarize yourself with:
   * [the user guide](http://kubernetes.io/v1.0/)
   * [the troubleshooting guide](http://kubernetes.io/v1.0/docs/troubleshooting.html)

Again, thanks for using Kubernetes.

The Kubernetes Team

**Comment by donnydavis** [comment]
Just incase anyone runs across this, the fix is to add -v /etc/pki/ca-trust:/etc/pki/ca-trust to the systemd service file

**Comment by anxinyf** [comment]
The same issue as me(k8s v1.11.0), and i just configure kubelet conf file: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf, add "--cloud-provider=external --cloud-config=/etc/kubernetes/cloud.conf" to "KUBELET_KUBECONFIG_ARGS", then daemon-reload and restart kubelet. Not specify **--cloud-provider** for kube-controller-manager and kube-apiserver.
