### ISSUE TITLE
kube-master-configuration not salted on master

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#27551]
Nothing comes up. Kubelet logs on the master have:

```
master&resourceVersion=0: dial tcp 10.240.0.2:443: getsockopt: connection refused
E0616 11:42:55.865622    1309 reflector.go:205] pkg/kubelet/kubelet.go:279: Failed to list *api.Node: Get https://e2e-gce-agent-pr-13-0-master/api/v1/nodes?fieldSelector=metadata.name%3De2e-gce-agent-pr-13-0-master&resourceVersion=0: dial tcp 10.240.0.2:443: getsockopt: connection refused
E0616 11:42:55.865680    1309 reflector.go:205] pkg/kubelet/kubelet.go:260: Failed to list *api.Service: Get https://e2e-gce-agent-pr-13-0-master/api/v1/services?resourceVersion=0: dial tcp 10.240.0.2:443: getsockopt: connection refused
I0616 11:42:56.410823    1309 kubelet.go:2452] skipping pod synchronization - [Failed to start cAdvisor inotify_add_watch /sys/fs/cgroup/cpu,cpuacct/system.slice/kube-master-configuration.service: no such file or directory]
I0616 11:42:56.427565    1309 file.go:135] Reading config file "/etc/kubernetes/manifests/etcd-events.manifest"
```

https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/27468/kubernetes-pull-build-test-e2e-gce/44963/artifacts/e2e-gce-agent-pr-13-0-master/

Any ideas on how to debug why the file didn't show up? @andyzheng0831

**Comment by bprashanth** [comment]
> Any ideas on how to debug why the file didn't show up?

Without startup.log I mean, or is this blocked on collecting journald output through fluentd on the master? 
fyi @a-robinson

**Comment by andyzheng0831** [comment]
Let me take a look. 

Generally, the startup.log in ContainerVM is can be seen using the commands in https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/gci/configure.sh#l28-38. These commands shows the log of cluster instance initialization.

**Comment by bprashanth** [comment]
@kubernetes/goog-testing maybe we can collect the output of those commands as part of our e2e log dump? (the master is gone). Also on a running master I get 
```
computeMetadata/v1/instance/attributes/configure-sh (code=exited, status=0/SUCCESS)
  Process: 1015 ExecStartPre=/bin/mount -o remount,exec /home/kubernetes/bin (code=exited, status=0/SUCCESS)
  Process: 1011 ExecStartPre=/bin/mount --bind /home/kubernetes/bin /home/kubernetes/bin (code=exited, status=0/SUCCESS)
  Process: 1007 ExecStartPre=/bin/mkdir -p /home/kubernetes/bin (code=exited, status=0/SUCCESS)
 Main PID: 1026 (code=exited, status=0/SUCCESS)
   Memory: 0B
      CPU: 0
   CGroup: /system.slice/kube-master-installation.service

Warning: Journal has been rotated since unit was started. Log output is incomplete or unavailable.
```

So maybe we should just rsync rotated logs too?

**Comment by andyzheng0831** [comment]
The error log you saw should be because apiserver was not up. Any failure in https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/gci/configure-helper.sh#l884-l886 can cause this, but not limited in this block. Since the instance is gone, and we lack of more information, I am sorry to say I cannot infer what is wrong.

I agree that we should collect the output of these commands. If there is anything wrong, such as running a certain command, we can see it in the output.

I would like to share some  experience of debug on cluster on GCI:

(1) If an instance is still there and we can ssh into it, things are simple. Several things we may do:

- Just run these systemctl commands to check errors in instance initialization. 

- Check manifest files in /etc/kubernetes to see if any var is not evaluated (this can happen if someone adds/renames a var in the saltbase manifest but forgets to update gci config). Typically I 'grep -ri "pillar"' or 'grep -ri "{{"' in that dir.

- Check major components' command line. This can show some hints sometimes.

- Finally, check logs in /var/log. For kubelet and docker, use "journalctl -u kubelet" or "journactl -u docker"

99% failures can be seen using the above steps.

(2) If an instance is gone. So, collecting as much information listed above will be helpful.

**Comment by bprashanth** [comment]
We should be able to automate (1) through a sanity check script that runs anytime we hit the 300s cluster bringup timeout, eg https://github.com/kubernetes/kubernetes/issues/22655

**Comment by ixdy** [comment]
`cluster/log-dump.sh` is probably the script you want to update, though if things are very GCI-specific you may want to guard on that.

cc @kubernetes/test-infra-maintainers

**Comment by a-robinson** [comment]
IIUC, this could/should be solved on GCE by updating the log-dump.sh logic, as @ixdy suggests. It'll have to be solved on GKE by getting journald support in our fluentd image, which I hope to have ready soon.

**Comment by fejta** [comment]
Randomly assigned to @roberthbailey per https://github.com/kubernetes/kubernetes/blob/master/cluster/OWNERS and random.randint(1,4)

**Comment by andyzheng0831** [comment]
Unassign myself as I am leaving this project.

**Comment by bprashanth** [comment]
You mean you're checking out right? this is an open source project, you can never leave :)

**Comment by andyzheng0831** [comment]
My contribution to kubernetes codebase is mainly for supporting gci image. (Just like this issue has a area/os/gci label). I am leaving the gci project now, so I unassigned the issue. It will be better to contact @kubernetes/goog-image for these issues to have a prompt action.

**Comment by wonderfly** [comment]
Unfortunately this needs a new owner, and probably from Kubernetes team. @gmarek, Can you unassign me?

cc/ @kubernetes/goog-image

**Comment by matchstick** [comment]
@dchen1107 Can you find an owner for this?

**Comment by bprashanth** [comment]
I think the work here is to automate https://github.com/kubernetes/kubernetes/issues/27551#issuecomment-226570940 so it makes debugging this easier. There's nothing else one can do to figure out why we failed to place kube-master-configuration on the master.

**Comment by liggitt** [comment]
not referenced in 6 months. can this be closed?
