### ISSUE TITLE
servicecontroller needs to create namespaces in target clusters

### ISSUE THREAD

**Issue by mml** [kubernetes/kubernetes#27565]
See #27564 for the error message that lead me to find this.

If you create a service with a namespace that doesn't exist in any target cluster, (and set --v=5) the servicecontroller logs the below:

```
I0616 20:14:44.703341       1 servicecontroller.go:862] Successfully procceeded services mml-e2e-foo/e2e-foo
I0616 20:14:44.703387       1 servicecontroller.go:791] Finished syncing service "mml-e2e-foo/e2e-foo" (186.398µs)
I0616 20:14:44.703425       1 servicecontroller.go:296] Process service mml-e2e-foo/e2e-foo for cluster federation-e2e-gce-us-central1-f
I0616 20:14:44.707795       1 servicecontroller.go:417] Service 'mml-e2e-foo/e2e-foo' is not found in cluster federation-e2e-gce-us-central1-f, trying to create new
I0616 20:14:44.712567       1 servicecontroller.go:424] Failed to create namespaces "mml-e2e-foo" not found
I0616 20:14:49.716028       1 servicecontroller.go:417] Service 'mml-e2e-foo/e2e-foo' is not found in cluster federation-e2e-gce-us-central1-f, trying to create new
I0616 20:14:49.720070       1 servicecontroller.go:424] Failed to create namespaces "mml-e2e-foo" not found
I0616 20:14:59.723764       1 servicecontroller.go:417] Service 'mml-e2e-foo/e2e-foo' is not found in cluster federation-e2e-gce-us-central1-f, trying to create new
I0616 20:14:59.727617       1 servicecontroller.go:424] Failed to create namespaces "mml-e2e-foo" not found
I0616 20:15:19.732110       1 servicecontroller.go:417] Service 'mml-e2e-foo/e2e-foo' is not found in cluster federation-e2e-gce-us-central1-f, trying to create new
I0616 20:15:19.735066       1 servicecontroller.go:424] Failed to create namespaces "mml-e2e-foo" not found
```

This doesn't come up in the e2e test because the test framework automatically creates the namespace with a matching name in the target cluster.  It also often works fine in manual tests as long as you use the default namespace.

cc @quinton-hoole

**Comment by mml** [comment]
Possibly related to this, the federation-apiserver doesn't recognize the namespace type at all, meaning you can't delete namespaces to clean up after a test.

**Comment by nikhiljindal** [comment]
Yes this is not good, but we dont have namespaces in federation control plane yet. Users will have to ensure that namespaces exist in underlying clusters.
https://github.com/kubernetes/kubernetes/pull/26298 has some related discussion

Will fix this in 1.4

**Comment by quinton-hoole** [comment]
Even without namespaces in the federation control plane yet, we could in theory save users the trouble by creating the namespace in the underlying cluster if it does not exist yet, before trying to create services in that namespace.  But that would make it inconsistent with the Kubernetes API (which does not automatically create missing namespaces).  So what I suggest is:

1. Have the e2e tests automatically create the namespaces in the underlying clusters before running the tests (and delete them afterwards), so that they pass.  This is already happening.
2. Have users either use the default namespace (which should just work, because it exists everywhere, by default), or create the namespace in the underlying clusters manually, if they want to use a non-default namespace.  
3. We need to expose the error clearly when they don't do that (e.g. in the Events associated with the FederatedService).  I don't think that that is there yet, but should be easy to add to aid users debugging their setups.

**Comment by quinton-hoole** [comment]
I think that this is pretty much all done elsewhere (federated namespaces, and events).  Assigning to @nikhiljindal to close as appropriate.

**Comment by quinton-hoole** [comment]
Closing.
