### ISSUE TITLE
Test Flake Exit Criteria: Presubmit test requirements

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#27578]
From the [doc shared with kubernetes-dev mailing list](https://docs.google.com/document/d/1jnGRrZymgnXoVUNnZVER_TOKH_Z11VvsKxlLxU1gg0A/)

All presubmit test jobs:
- Must finish in less than 30 minutes.
- Because it's frustrating to have a hard timeout, to keep this rule,
  - Our actual time goal is 20 minutes.
  - Human(s) need to be alerted or paged if the test run goes above 30 minutes.
  - That should be treated as a P0 issue until the time is below 30 minutes again.

If we're over 30 minutes per retest, we can't possibly hope to keep up with demand.

**Comment by spxtr** [comment]
@kubernetes/sig-testing

**Comment by spiffxp** [comment]
Anecdotally we're now somewhere in the <60 minute range.  We're attempting to refine merge-blocking criteria in https://github.com/kubernetes/sig-release/issues/24 but I'll leave this open for now because it's still relevant

**Comment by BenTheElder** [comment]
I would *love* < 30 but it's definitely ~ <60. Alerting humans is problematic because it's difficult to get people to own / work on the tests even when they're broken (which [we have alerting for right now](https://github.com/kubernetes/test-infra/tree/master/testgrid/cmd/config#email-alerts), though many tests have nobody signed up for the alerts) but I'd like this as well..
