### ISSUE TITLE
Failed to remove orphaned pod because volumes weren't unmounted

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#27651]
I have a recently built cluster (0856e1dd43834f1b729756555365a8b672faa5bd) and after running some tests, kubelet.log is full of errors for not being able to remove orphaned pod directories.

E.g.,
```
I0618 00:17:04.062975    9199 kubelet.go:2004] Orphaned pod "87cfe5a1-34c7-11e6-85f1-42010af00002" found, removing
I0618 00:17:04.064022    9199 kubelet.go:2006] Failed to remove orphaned pod "87cfe5a1-34c7-11e6-85f1-42010af00002" dir; err: remove /var/lib/kubelet/pods/87cfe5a1-34c7-11e6-85f1-42010af00002/volumes/kubernetes.io~secret/default-token-qf0cp: device or resource busy
I0618 00:17:04.064134    9199 kubelet.go:2004] Orphaned pod "8809a228-34c7-11e6-85f1-42010af00002" found, removing
I0618 00:17:04.065055    9199 kubelet.go:2006] Failed to remove orphaned pod "8809a228-34c7-11e6-85f1-42010af00002" dir; err: remove /var/lib/kubelet/pods/8809a228-34c7-11e6-85f1-42010af00002/volumes/kubernetes.io~secret/default-token-qf0cp: device or resource busy
I0618 00:17:04.065153    9199 kubelet.go:2004] Orphaned pod "8832af8b-34c7-11e6-85f1-42010af00002" found, removing
I0618 00:17:04.066206    9199 kubelet.go:2006] Failed to remove orphaned pod "8832af8b-34c7-11e6-85f1-42010af00002" dir; err: remove /var/lib/kubelet/pods/8832af8b-34c7-11e6-85f1-42010af00002/volumes/kubernetes.io~secret/default-token-qf0cp: device or resource busy
```
I manually unmounted one of the directory and was able to delete the directory afterwards. I haven't tried reproducing it, but here is the sequence of the actions that led to this:
  1. Create an RC, and wait for all pods (~100 pods per node) to be running.
  2. Delete the RC
  3. Restart kubelet

(3) can happen before all pods were deleted properly.

I haven't try to reproduce this (even though all three of my nodes showed the same symtom) yet, so not marking this a bug yet. If I can't reproduce this later, I'll close the issue.
 
I assume the newly introduced volume manager will unmount all the volumes even when pod specs are unavailable, but /cc @saad-ali just in case.

**Comment by saad-ali** [comment]
> Restart kubelet

This is an expected side effect of the current design. When kubelet is restarted, volume manager's internal state is nuked. When it starts up again, it rebuilds the state based on the pods that still exist. In this case the pods are deleted so volume manager doesn't know about them or about the mounts that were not unmounted, so it tells orphanedPod cleanup loop to go ahead and delete them, but the deletes fail because the pod's volume is still mounted.

We intend to fix this in v.next, see https://github.com/kubernetes/kubernetes/issues/27653 which is tracking the fix.

CC @matchstick We were talking about this yesterday.

**Comment by yujuhong** [comment]
Thanks for the answer! I'll close this issue.
