### ISSUE TITLE
Safely GC the volumes of a petset

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#27658]
When a PetSet is deleted, the underlying pods / PVCs / PVs are not deleted.

Using the redis example:

```
> kubectl delete petset rd
petset "rd" deleted

> kubectl get pods
NAME      READY     STATUS    RESTARTS   AGE
rd-0      1/1       Running   0          5m
rd-1      1/1       Running   0          4m
rd-2      1/1       Running   0          1m

> kubectl get pvc
NAME           STATUS    VOLUME                                     CAPACITY   ACCESSMODES   AGE
datadir-rd-0   Bound     pvc-237b0114-350a-11e6-964c-42010a800002   0                        19m
datadir-rd-1   Bound     pvc-2382b0c2-350a-11e6-964c-42010a800002   0                        19m
datadir-rd-2   Bound     pvc-23862681-350a-11e6-964c-42010a800002   0                        19m

>kubectl get pv
NAME                                       CAPACITY   ACCESSMODES   STATUS    CLAIM                  REASON    AGE
pvc-237b0114-350a-11e6-964c-42010a800002   20Gi       RWO           Bound     default/datadir-rd-0             20m
pvc-2382b0c2-350a-11e6-964c-42010a800002   20Gi       RWO           Bound     default/datadir-rd-1             20m
pvc-23862681-350a-11e6-964c-42010a800002   20Gi       RWO           Bound     default/datadir-rd-2             20m
```

**Comment by goltermann** [comment]
@bprashanth Can you help triage?  Think this is a P1 (required for 1.3)?

**Comment by justinsb** [comment]
OK cool - if it isn't supposed to then I agree that it shouldn't block 1.3.  I think it will surprise users, so this is probably an important thing to document, and then if users hate it maybe we can revisit.

**Comment by bprashanth** [comment]
Yeah we intentionally left out pv deletion out of alpha:  https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/petset/pet_set.go#L352

**Comment by chrislovecnm** [comment]
@justinsb I would wonder since we are dealing with large apps like databases, that we want to GC volumes.  Just throwing that out there 😄

**Comment by smarterclayton** [comment]
With ownership GC we can potentially handle this if necessary - by letting someone opt in to the ownership reference.  Although arguably I'd want to make this an explicit choice.

**Comment by bprashanth** [comment]
We can probably also achieve it with cascading delete on a pet, provided that only cascaded after deletionTerminationGrace

**Comment by Raffo** [comment]
@justinsb Is it also expected that the pods are still running?

**Comment by smarterclayton** [comment]
?

**Comment by Raffo** [comment]
In the original post, the author mentioned that he removed a petset, leaving with the pods still running. I guess currently the default behavior is to have `cascade=true` in kubectl when doing this. 
I was originally commenting cause I was mixing version (1.4, 1.5) and due to the rename of PetSets into StatefulSets I was having similar behaviors to the one described in this issue.

**Comment by smarterclayton** [comment]
Yeah, cascade was not implemented in the original petset alpha release.

On Nov 23, 2016, at 2:04 PM, Raffaele Di Fazio <notifications@github.com>
wrote:

In the original post, the author mentioned that he removed a petset,
leaving with the pods still running. I guess currently the default behavior
is to have cascade=true in kubectl when doing this.
I was originally commenting cause I was mixing version (1.4, 1.5) and due
to the rename of PetSets into StatefulSets I was having similar behaviors
to the one described in this issue.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/27658#issuecomment-262617441>,
or mute the thread

**Comment by Raffo** [comment]
Then I guess this can actually be closed (one less!). Thanks!
