### ISSUE TITLE
Shouldn't kube processes use kubeconfig for API server discovery?

### ISSUE THREAD

**Issue by onorua** [kubernetes/kubernetes#27698]
I'm wondering, why do kubelet/kube-proxy need to have `--api_servers` defined explicitly as a command line argument and not use `server` in cluster config of the `kubeconfig` file. 
Generally kubelet will not be able to talk to API server due to missing certificates or credentials, so why don't use server from kubeconfig rather than from command line? 

I've tried to set it in kubeconfig removing command line argument, and I've got:

```
Jun 20 04:08:18 master kubelet[12090]: W0620 04:08:18.848294   12090 server.go:611] No api server defined - no events will be sent to API server.
```

instead of expected server defined in the cluster for current context.

**Comment by girishkalele** [comment]
Please re-post your question to [stackoverflow]
(http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support
are posted so that we can improve our efficiency in responding to your requests,
and to make it easier for you to find answers to frequently asked questions and
how to address common use cases.

We regularly see messages posted in multiple forums, with the full response
thread only in one place or, worse, spread across multiple forums. Also, the
large volume of support issues on github is making it difficult for us to use
issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to
ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to
similar questions, and also familiarize yourself with:

  * [user guide](http://kubernetes.io/docs/user-guide/)
  * [troubleshooting guide](http://kubernetes.io/docs/admin/cluster-troubleshooting/)

Again, thanks for using Kubernetes.

The Kubernetes Team

**Comment by onorua** [comment]
@girishkalele even though it looks like a question, it is rather proposal. You can't have proposal heard from stackoverflow :(

**Comment by girishkalele** [comment]
@onorua 

I didn't realize it was a proposal - I have reopened the issue and marked it as an enhancement for the node team.

**Comment by pires** [comment]
Related to https://github.com/kubernetes/kubernetes/pull/30707 and https://github.com/kubernetes/kubernetes/issues/30395.

**Comment by pires** [comment]
This issue can be closed since kubeconfig is now the way to point components to the API.

**Comment by justicezyx** [comment]
Could someone update the document about a clear pointer on how to switch from --api-servers or --api_servers flag to a config file?

I have no idea how that can be done.
