### ISSUE TITLE
Make it possible to build a cloudprovider outside the kubernetes repo and run on stock kubernetes

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#2770]
Kubernetes needs to be able to request resources on demand: external IPs, load balancers, storage devices, nodes, ...

**Comment by bgrant0607** [comment]
Worth looking at existing multi-cloud layers. For example: https://jclouds.apache.org/

Node image management, currently done with Salt, is largely a separable problem. For that, there are the usual suspects: bosh, puppet, chef, ansible, etc.

**Comment by bgrant0607** [comment]
#2003 is also relevant. I'll comment there.

/cc @eparis

**Comment by bgrant0607** [comment]
Here's another example: https://libcloud.apache.org/

**Comment by brendandburns** [comment]
We should probably fork the generic cloud provider library out into it's
own project (I know I resisted this elsewhere, but in this case, I think it
makes sense, and could be of general use to the go community)

--brendan

**Comment by timothysc** [comment]
+1 @brendanburns 

+tracking, and interest.

**Comment by bgrant0607** [comment]
More examples:
* https://github.com/rackspace/gophercloud (Go+OpenStack -- not sure this counts as multi-cloud)
* http://fog.io/ (Ruby)

**Comment by bgrant0607** [comment]
Openstack has a compatibility API, but only with EC2:
http://docs.openstack.org/admin-guide-cloud/content/instance-mgmt-ec2compat.html

**Comment by bgrant0607** [comment]
Another option to look at: https://hashicorp.com/blog/terraform.html

**Comment by bgrant0607** [comment]
cc @jackgr

**Comment by bgrant0607** [comment]
Another idea that's been discussed is pushing as much of the cloudprovider responsibilities as possible into a pluggable controller component, which could perhaps work for the cluster-level control plane. That would still leave the issue of how to access local cloudprovider-specific metadata, but perhaps that could be handled by some kind of pluggable on-node agent.

**Comment by pires** [comment]
Another one I've used for AWS and GCE, https://jclouds.apache.org/.

**Comment by pires** [comment]
+1 for Terraform.

**Comment by bgrant0607** [comment]
There is a proposal, if anyone is interested: #10503

**Comment by bgrant0607** [comment]
Another approach would be to externalize control so that we could eliminate the cloudprovider API entirely.

**Comment by erictune** [comment]
I don't see the value in forcing a single cloud provider library. 

Instead, let each component that needs to interact with the cloud decide what abstraction in wants to use to allow for per-cloud or per-environment implementations.

As an example, kubelet has a credentialprovider abstraction.  It happens to have implementations for ECR and GCR.  But there are no interfaces in pkg/cloudprovider about registry providers.

There is not a 1:1 mapping between our "cloud provider names" and registry integration: not all AWS users want to use ECR.  Some clouds may not have any registry.    "Cloud provider" is going to turn out not to be a single enum variable ("gce" or "aws" etc)  -- it is going to be a bunch of similar but not identical knobs.

Ingress is similar.  You might want GCE LB on GCE, but maybe not. 

A centralized library will also add significant friction to adding code.  If the PR that added ECR support had to add a new interfaces to pkg/cloudprovider, it would have taken quite a bit longer and might not have gotten done.

You could argue that having a centralized library makes it easier for someone to port to another cloud provider because they have all the code they need to implement in one place.  I don't think it does though: to implement a cloud-provider, I think you have to understand the context of how the functions are used.

You could argue that it will improve code reuse.  But then there are already fairly libraries for major cloud providers.

**Comment by aronchick** [comment]
I am a fan of moving this work up, significantly, potentially to 1.3 blocker. I'm open to discussion here - do we have a proposal? cc @jbeda @countspongebob

**Comment by smarterclayton** [comment]
Agree with a lot of eric's points - we see this in the on-premise side, there is an infinite variety of configuration, and there are lots of points where cloud provider implementations would be useful for very specific parts, but a monolithic cloud provider would be useless.  In the cloud, we have people who use ELB and EBS but would never use anything else.

**Comment by pires** [comment]
> Another approach would be to externalize control so that we could eliminate the cloudprovider API entirely.

+1

**Comment by erictune** [comment]
List of abstractions provided by current API, with comments:
- LoadBalancers
  - this is used by "services", but we already discovered with Ingress that `pkg/cloudprovider` abstraction doesn't fit, IIUC.
- Listing instances 
  - this may be obsoleted by kubelet self-registration?
- Instance metadata (addresses, IDs)
  - this is more of a kubelet-to-node API than a "cloud provider" API.
- Adding ssh keys to nodes:
  - I think this is only needed for e2e testing.  on-prem providers aren't going to run e2e realistically, and so don't need this.  They can just run conformance tests, which don't run the tests that need a cloud provider.
- Zones
    - this could be superceded by the other options we now have for setting node labels, including a zone label.
- ListClusters/Master
  - does this belong in a cloud provider API, or is this more of a general discovery feature?
- Routes
  - don't know much about this
- something called ScrubDNS 
   - don't know what it does.
```

**Comment by markturansky** [comment]
@erictune 

* Create/Delete/Attach/Detach volumes

**Comment by thockin** [comment]
Volume logic goes thru cloud provider, but the "abstraction" is pretty
nonexistent.

Load-balancers go through the cloud provider, but it's one of the few
interfaces simple enough to work as an abstraction.

I'd rather see (I think) the move towards evicting cloud provider into a
"bridge" controller or controllers that watch the appropriate API objects
and sync into cloud provider.  PV provisioning is already headed here.  L7
LB is there.  L3 LB would be easy enough (it's already async to all API
ops).

**Comment by erictune** [comment]
@thockin why centralize in one controller rather than put what is needed in each package that needs to talk to a cloud.  Distributed makes it easier for people not familiar with the whole code base (pretty much anyone) to make a locally-safe change.

**Comment by thockin** [comment]
I don't follow your comment, sorry.  I'm arguing (I think) that the
abstraction across cloud-providers is artificial to the point of not being
useful, and that we'd do better to get out of the way of cloud providers
and let them act as observer/controllers.  This has the side-effect of
making it possible for anyone to build a new cloud provider or extend an
existing one without sending pull requests to us and waiting 2 months for a
release.

Obviously, we'd have a few that we own and bundle and e2e test rigorously,
and we would need very clear docs on the various observation/reactions we
expect.

**Comment by smarterclayton** [comment]
I think Eric and I were arguing that there would be multiple
independent controllers per cloud provider that are more decoupled
than the single interface we have today.  A service load balancer
controller for GCE that is strongly decoupled from the disk attach
logic for GCE, so that it can be selectively enabled.

**Comment by thockin** [comment]
oh, yeah, I am fine with that too, but I don't think we really want to have
a generic L7 controller which uses plugins to get GCE, AWS, haproxy, NGINX,
etc support.

Curiously we ARE using single controller+plugins for storage mostly because
the API across plugins is simple enough that plugins are feasible and the
controller logic is complicated.  It's a tradeoff.

**Comment by smarterclayton** [comment]
Yes, I would much rather have a GCE L7 service load balancer controller
that is independently compilable and shares most of its code without
necessarily having to be the same binary.

**Comment by jackgr** [comment]
+1 to comments by @erictune and @smarterclayton.

**Comment by thockin** [comment]
Circling back on older issues, I think the jury is in - making cloud providers be controllers is the better design.  As we evolve cloud provider we should head in this direction.  It will come at some cost, but I think the benefits of it prevail.

**Comment by mfischer-zd** [comment]
I'm interested in this issue because I'd like to use my own Nginx Plus-based LoadBalancer implementation in my datacenters (and possibly in AWS). 

For many (maybe even most) users, the tight coupling between the CloudProvider and LoadBalancer is fine.  But for us, I find it limits our architectural options.  We can hack our way around it by using Consul service discovery controllers to publish NodePorts to our on-premise load balancers, but it would be nice to adhere as closely as possible to K8S idioms to be somewhat consistent with the outside world.

If we're going to make CloudProviders and/or LoadBalancers truly pluggable, I'd like us to consider child-process-based plugins like those enabled by https://github.com/hashicorp/go-plugin.  (This goes for anything K8S make pluggables, really.)  That way we can configure K8S controllers to use them, and we don't have to fork the codebase or wait for it to be accepted into upstream.  I'm happy to make this suggestion in a "grand unified plugin" issue if one exists.

**Comment by luxas** [comment]
There's work in progress for making this happen. 
Proposal: https://github.com/kubernetes/community/pull/128
Code: https://github.com/kubernetes/kubernetes/pull/34273

cc @wlan0

**Comment by bgrant0607** [comment]
Of historical interest:
https://github.com/kubernetes/kubernetes/pull/2003/files

**Comment by bgrant0607** [comment]
Merged:
https://github.com/kubernetes/community/blob/master/contributors/design-proposals/cloud-provider-refactoring.md

**Comment by thockin** [comment]
Closing this now that cloud-provider-refactoring.md is merged - this is happening.
