### ISSUE TITLE
Attach controller should not start detach until the node status has been updated

### ISSUE THREAD

**Issue by saad-ali** [kubernetes/kubernetes#27836]
https://github.com/kubernetes/kubernetes/pull/27567 introduced logic to make kubelet volume manager wait for attach detach controller to finish attach before it starts mount.

The controller should also not start a detach operation until the node status has been updated removing the volume from the list of attached volumes. Otherwise if a pod is rapidly created and deleted on the same node, it could result in a mount starting immediately before a detach starts.

Props to @bprashanth and his pet set tests for helping catch this.

**Comment by bprashanth** [comment]
Hmm, this just happened http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gce-petset/538/consoleFull, just a lot less frequently. Haven't debugged, but it looks like the failed pod did reland on the same node: pet-0, jenkins-e2e-minion-group-4mn2. Reopening, will try to confirm when i have time, and close if it's not the same thing.

**Comment by bprashanth** [comment]
Just following up with an update, Saad and i are tag teaming this. He's uploading a pr that I'm going to reivew. We're tracking a couple of issues:    

1. We need to update the "volumes in use" list before polling on the "volumes attached" list. Best option is to write a operation executor, so we don't hammer the apiserver. 
2. Reconciler needs to get up to date node object from apiserver to determine volumes in use. The update that removes volumes from the "attached list" shoud return a fresh node object, we can just iterate the volumes its using (this must happen after popping from attached, though). 
3. Potentially leaky volumes in the node object (this is not about the physical volumes but about the size of the json blob that's the node object growing). The proposed fix is to use the desired state of the world to update the list of volumes in use. 

There's a last point I need to follow up on. We might leave the node object in an inconsistent state with the proposed fix, but it *should* be ok since nothing is checking the inconsistent fields. This will happen if we pop a volume from the attached list, but then find its in use in the updated node object. 

@saad-ali ping me when you're ready to go, of if you need help
