### ISSUE TITLE
Too short timeout in AfterEach for image puller to finish in case of even a bit slower network

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#27940]
It happened in the serial suite: http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-serial/1553/consoleFull

This happened in the resize test, when we bring up a new Node, which needs to run image puller before it's fully functional. We need to extend the timeout.

Ref. #27320

cc @bprashanth @wojtek-t @davidopp

**Comment by bprashanth** [comment]
@gmarek that's why all other places in code make sure they don't fail when the prepuller doesn't complete. I think WaitForPodsRunningReady only recently started doing so (https://github.com/kubernetes/kubernetes/commit/9cf3724ed6e7c88e26104defa2187ad3c34b4c41). This might cause more failures actually. 

The passed in "ignore labes" arg should actually just translate to ignoring pods with those labels. The caller should call waitforPodsSuccess and fail if necessary. No one except the resource tracking test actually wants to fail today, and that test does fail after 8m (https://github.com/kubernetes/kubernetes/blob/master/test/e2e/kubelet_perf.go#L43). Suggest doing the same.

**Comment by gmarek** [comment]
Well - we have a new node after resize test, and either we agree that we don't need a prepuller, or we agree that it needs to finish. I chose the latter, even though I'm not a fan of this hack, that's there only to make tests passing, thus make the real problem less visible.

**Comment by bprashanth** [comment]
That doesn't make sense. We're obviously addressing the problem. No point in closing the SQ every 2 days while that happens. We know why and when it takes > 5m. Fixing it will take much longer. Why would we fail after knowing all this?

**Comment by wojtek-t** [comment]
@bprashanth - we definitely shouldn't fail. We should increase the timeout until this is fixed.
How long it can take?

**Comment by bprashanth** [comment]
On https://github.com/kubernetes/kubernetes/issues/26626#issuecomment-227591880 (b/29549398) we observed significant deviation between average and ~90%ile download bandwidth. I don't have a more accurate estimate for the timeout, that's why initially we just decided to forgive the long tail.
