### ISSUE TITLE
kube-dns more control over records "feature"

### ISSUE THREAD

**Issue by aabed** [kubernetes/kubernetes#28027]
kube-dns now supports the following DNS Schema 
https://github.com/kubernetes/kubernetes/tree/master/build/kube-dns#supported-dns-schema

What if we add more options to change this behaviour 
like 
--servicebubdomain=""
--namespace=yes/no
so that if the previous is passed you get a record 
**service_name.domain_name**
instead of 
**service_name-namespace.svc.domain_name**
### Why?

We had a case where we wanted some of the pods to talk to "API" pods using the internal DNS,however when we changed the code settings we faced a problem that the same settings are used in the front end so, internally api.default.svc.cluster.local will resolve, but not from the frontend 

So we can either add that record to the extern DNS "rackspace DNS" or we change the code, to get a domain name for the backend and front end separately,
However we chose to hack _kube2sky_ and remove the namespace and the service subdomain from the code

**Comment by aabed** [comment]
Ping

**Comment by girishkalele** [comment]
@aabed 

Note - we no longer use kube2sky but seeing your patch would help understand your issue better.

Eliminating namespace from the DNS entry makes this method not multi-tenant, since all services in all namespaces will collapse and conflict.
Removing the .svc. keyword in the middle of the entry will cause DNS entries for non-service entities to collide/conflict too.
Let me know if my understanding is correct.

**Comment by aabed** [comment]
@girishkalele 

I see your point but what I am saying is to give the user the flexibility, if he know what he is doing it will not make any conflicts 

and it was not a patch actually I just removed the constant for the "svc"
