### ISSUE TITLE
Restarting kubelet with new node labels doesn't update labels for node

### ISSUE THREAD

**Issue by guoshimin** [kubernetes/kubernetes#28051]
kubelet version: 1.2.4

Steps to reproduce:
- start kubelet with some labels using the `--node-labels` flag
- wait for the node to register itself with the master
- restart kubelet with a different set of labels

Expected result:
`kubectl get no --show-labels` shows the node with the updated labels

Actual result:
`kubectl get no --show-labels` shows the node with the original labels

**Comment by AdoHe** [comment]
@guoshimin this is an alpha feature, and may has problem. More specifically, when we register node in kubelet, we always use [Create](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet.go#L1164), maybe we should use UpdateOrCreate here. @kubernetes/sig-node

**Comment by vishh** [comment]
This is a known issue and that's why the feature is still `alpha`. There is no concept of label ownership as of now since labels can be added to the node object from multiple sources. 
We need to update kubelet to checkpoint the flags that it currently owns and use that knowledge while updating flags in the future. 

A possible workaround meanwhile will be that of having kubelet delete existing flags and adding the new flags specified via `--node-labels` flags everytime it restarts.

**Comment by ncdc** [comment]
Related #25811

**Comment by timothysc** [comment]
@vishh do you know if there is an assignee for for 1.4.  Our ops folks are not fond of having to manage node configs in maintain label sanity across restarts.  

/cc @twiest @scollier

**Comment by vishh** [comment]
@timothysc No one is working on completing node labels AFAIK.

**Comment by vishh** [comment]
cc @dchen1107

**Comment by AdoHe** [comment]
I would do this if we decide to persist node labels at last.

**Comment by dims** [comment]
switching this to 1.6 as it's too late for 1.5. ok? (please switch it right back if you disagree)

**Comment by AdoHe** [comment]
@dims I think we still don't make a final decision.

**Comment by dims** [comment]
Ack @AdoHe please adjust milestone when appropriate

**Comment by saad-ali** [comment]
@AdoHe Can you please triage this issue by EOD Friday. Is this a 1.5 issue or can it be punted to 1.6? If it is a 1.5 issue is it a blocker for the release (meaning release must wait for this to be fixed), or a non-blocker?

**Comment by euank** [comment]
I don't think this can be a release blocker since it's not a bug. This feature functions as documented. fixing this issue is an additional feature, not a bugfix.

This can't break customers since it's been as-is for multiple releases now.

I see no reason this additional feature (which requires additional kubelet persistence and has zero work thusfar) should go in post-feature freeze and shouldn't be targeted at 1.6.

**Comment by dims** [comment]
excellent @euank punting it to 1.6 :)

**Comment by resouer** [comment]
Relies on #29459

**Comment by pwittrock** [comment]
@resouer What is the status of this for 1.6?

**Comment by dchen1107** [comment]
This is not targeted for 1.6 at all, and no assignee. We need to first finish #29459 for kubelet config in general, then come back with the node labels.

**Comment by resouer** [comment]
I've confirmed this has been fixed #46254
