### ISSUE TITLE
parsing error when using the existing CIDR

### ISSUE THREAD

**Issue by kant111** [kubernetes/kubernetes#28089]
I am using kubernetes 1.2.4 release

<img width="1012" alt="screen shot 2016-06-26 at 3 13 42 pm" src="https://cloud.githubusercontent.com/assets/5432406/16365393/aabbbe86-3bb3-11e6-81bd-2615a166174a.png">

**Here are environment variables I used**

``````
export KUBERNETES_PROVIDER=aws
export NUM_NODES=5
export MASTER_SIZE=m4.xlarge
export NODE_SIZE=m4.xlarge
export AWS_DEFAULT_PROFILE=DevOPS
export KUBE_AWS_ZONE=us-west-2a
export AWS_S3_REGION=us-west-2
export AWS_S3_BUCKET=kant-kubernetes-bucket
export VPC_ID=vpc-86a33ae2
​
export KUBE_VPC_CIDR_BASE="10.100"
export KUBE_SUBNET_CIDR="10.100.3.0/24"
export NON_MASQUERADE_CIDR="100.64.0.0/10"
export SERVICE_CLUSTER_IP_RANGE="100.64.0.0/16"
export DNS_SERVER_IP="100.64.0.10"
export MASTER_IP_RANGE="100.65.0.0/24"
export CLUSTER_IP_RANGE="100.66.0.0/16"```


I get couple of errors when I run kube-up.sh with the above settings. Please look at the screen shots  above
1. error: error parsing jsonpath {.contexts[?(@.name == "Using subnet CIDR override: 10.100.3.0/24
aws_kubernetes")].context.user}, unterminated filter
2. Detected 6 ready nodes, found 6 nodes out of expected 5. Found more nodes than expected, your cluster may not behave correctly.
``````

**Comment by kant111** [comment]
@justinsb

**Comment by girishkalele** [comment]
@kant111 

Could you also mention the version - is this master/HEAD ? Is this release1.3 branch code ?

**Comment by captify-akraievoy** [comment]
I've seen that just now with my local install of fresh release of 1.4.0:
```
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.0", GitCommit:"a16c0a7f71a6f93c7e0f222d961f4675cd97a46b", GitTreeState:"clean", BuildDate:"2016-09-26T18:16:57Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/386"}
```
If you need extra details on my setup - please see https://github.com/kubernetes/kubernetes/issues/33559 for more.

I have confirmed that this is caused by diagnostic output in [cluster/aws/util.sh](https://github.com/kubernetes/kubernetes/blob/a6dfaff/cluster/aws/util.sh#L113), which is usually silent and activates only when you set KUBE_SUBNET_CIDR property.

I've commented that line, did kube-down.sh and kube-up.sh and now see that everything went fine - there's no similar warnings and parse errors anymore - as originally reported by @kant111.

So the above could be used as a workaround locally.
