### ISSUE TITLE
Implement a kubelet pod api

### ISSUE THREAD

**Issue by aaronlevy** [kubernetes/kubernetes#28138]
I couldn't find a specific issue for this, and I've heard various incantations of a similar feature:

It would be nice from the bootstrapping perspective to allow an api client to target the kubelet directly. Essentially being able to push pod manifests to the kubelet, which once an api-server is available would be persisted as if they had been created via calls directly to the apiserver.

Related discussions:

https://github.com/kubernetes/kubernetes/issues/2098
https://github.com/kubernetes/kubernetes/issues/1963
https://github.com/kubernetes/kubernetes/issues/246
https://github.com/kubernetes/kubernetes/issues/489

**Comment by mikedanese** [comment]
cc @bgrant0607 @dchen1107

**Comment by bgrant0607** [comment]
Also relevant: #16627

**Comment by luxas** [comment]
cc @luxas 

Is this issue for v1.4?

**Comment by vishh** [comment]
@luxas I don't think so. We need to start with a design first.

**Comment by luxas** [comment]
Argh, how bad. It would be a great feature to have for bare-metal bootstrapping.

Does anyone in @kubernetes/sig-cluster-lifecycle have bandwidth to take this on?
(As a proposal in the first place)

**Comment by pires** [comment]
I'd like to pick on this if @aaronlevy is up for a joint-effort.

**Comment by bgrant0607** [comment]
There was some discussion in #2098

**Comment by errordeveloper** [comment]
From kubeadm UX perspective, it'd be best to get confirmations when each pod is deployed and ready, may be even have status while images are being fetch, and _most of all we want to fail early_, without having to check in a polling fashion for multiple things.

**Comment by pires** [comment]
@luxas can please you assign this over to me and @aaronlevy?

**Comment by mikebryant** [comment]
Would this just be a pod api?
If the intent is to persist the pod definitions to the apiserver when it becomes available, and for the pods to be adopted by a higher level Deployment or Daemonset - Do we need a ConfigMap and Secret api as well?
i.e. make the pod spec we're pushing in match the one that might come from the Daemonset?


(I'm thinking in terms of the apiserver manifests generated by bootkube, which use secrets for the apiserver keys etc.)

**Comment by liggitt** [comment]
I'm really unsure about a partial API that operates disconnected from the "real" API, and attempts to move state to a real API once it is available. For example:
* references in a pod spec to other resources wouldn't be resolveable
* uids and resource versions would change when moving a pod from the "local" API to the "real" API
* names could conflict with existing real resources
* clients of the kubelet pod API would either need to know when to switch to the real API, or the kubelet API would have to proxy to the real API
* how would the kubelet pod API be protected?

maybe the proposal will address all of those things, but I have a hard time envisioning an approach that would work well

**Comment by pires** [comment]
I see it as an alternative or even replacement for static pod manifests. As @errordeveloper pointeed out:
> it'd be best to get confirmations when each pod is deployed and ready (...) without having to check in a polling fashion for multiple things.

I'm not sure about pushing said pods to an API server when one is available.

However, worry not! @aaronlevy and I will be putting out a design proposal before any implementation. We will reference said proposal as soon as we have something worth showing, which should happen next week.

**Comment by aaronlevy** [comment]
I can give some initial thoughts, but this is a bit speculative at this stage. This is assuming that pods created via the kubelet-pod-api are persisted once an api-server is available (similar in concept to persisting mirror pods, but without the "on-disk" static pod backing it).

A kubelet-pod-api bootstrap scenario I envision (assuming external etcd for now, but have some ideas there as well):

```
systemctl start kubelet
kubectl -s <kubelet-api> create -f api-server-pod
kubectl -s <kubelet-api> create -f controller-manager-pod
kubectl -s <kubelet-api> create -f scheduler-pod
```
A couple things to note:

- The "bootstrap" api-server relies on no external objects (secret, configmap).
- The "bootstrap" controller-manager does rely on a secret, so it has not started because it cannot be retrieved. A secret is used so all service accounts created at this stage are valid post-bootstrap.
- The "bootstrap" controller-manager uses host-networking so it can start without the pod-network being configured yet (Note: in the case of weave, this isn't necessary as it doesn't rely on the cm-assigned pod CIDR, so you could just start the weave networking pod at this stage).
- The "bootstrap" controller-manager contacts the api-server on localhost/insecure port

Create the controller-manager secret so the cm pod can start:

```
kubectl -s <api-server> create -f api-server-secret
```

We now have a fully functional "bootstrap" control-plane we can begin replacing/adopting with higher-level objects.

```
kubectl -s <api-server> create -f api-server-secret
kubectl -s <api-server> create -f api-server-daemonset
kubectl -s <api-server> create -f controller-manager-deployment
kubectl -s <api-server> create -f scheduler-deployment
kubectl -s <api-server> create -f pod-network-daemonset
kubectl -s <api-server> create -f kube-proxy-daemonset
```

We now have all components managed by higher-order objects. And a couple "bootstrap" components are different from these objects so they will not be adopted (api-server, controller-manager). The replacement api-server will consume secrets, and the replacement controller-manager will not use host-networking.

We should now be able to delete the bootstrap components which will not be adopted:

```
kubectl -s <api-server> delete -f apiserver-pod
kubectl -s <api-server> delete -f controller-manager
```

Now no orphaned pods, and all our core components are managed by higher-level objects. But I'm sure I'm missing some things...

**Comment by aaronlevy** [comment]
@liggitt:

> references in a pod spec to other resources wouldn't be resolveable

Per the above steps, I believe we can still bootstrap a control plane without needing external resources (will require some replacement / coordination points). And this is already true of static pods.

> uids and resource versions would change when moving a pod from the "local" API to the "real" API
> names could conflict with existing real resources

I'm not familiar enough with the mechanics right now to comment directly -- but very similar concerns were brought up with static pods. One such discussion: https://github.com/kubernetes/kubernetes/issues/4090

> clients of the kubelet pod API would either need to know when to switch to the real API, or the kubelet API would have to proxy to the real API

I feel like this would be the responsibility of the client to make this distinction. The use-cases I envision are that kubelet-api really is only used during bootstrap / disaster recovery. Once api-server is available, you would never use kubelet-api. Exactly how/when the pods were sync'd to the api-server is something that needs thought (and probably bugging sig-node)

> how would the kubelet pod API be protected?

TBD? Interested in your thoughts here. This would be fairly similar to dropping a static manifest on disk that the kubelet can pick up.

**Comment by bogdando** [comment]
This looks like a hack to make kubelet mimic apiserver, which is wrong from the design of microservices pov - components to do only their tasks and do it well, being kept designed in minimalist fashion. Therefore, I would vote against the proposal.

**Comment by ethernetdan** [comment]
This proposal has been worked on in a GDoc - https://docs.google.com/document/d/1tFTq37rSRNSacZeXVTIb4KGLGL8-tMw30fQ2Kkdm7JQ.

I'm working on a PR on this and will implement feedback from the doc.

**Comment by philips** [comment]
cc @thock

**Comment by philips** [comment]
cc @thockin

**Comment by armstrongli** [comment]
@aaronlevy
Why not let kubelet listening on one http server? It does support fetching pods list from http server.

kubelet watching 2 resources for static pods:
 - host path
 - http server

Then you can create pods directly to the http server instead of to the kubelet. kubelet should be one pure client watching resources, running/stopping pods.

The risk of implementing one rest api in kubelet is that : kubelet can't restart. Or it loses the context and flush the resources you have created.

**Comment by xinxiaogang** [comment]
I think @armstrongli's question is what if we use `static` pod for the bootstrap control plane and remove them after `normal` control plane pod ready?
- The `static` pods' lifecycle is only for bootstrap usage.

**Comment by metral** [comment]
@xinxiaogang The switch to static pods is an open issue (https://github.com/kubernetes-incubator/bootkube/issues/168) in bootkube. Currently, bootkube has the apiserver, controller-manager & scheduler baked into it to stand up the temp control plane.

**Comment by jamiehannaford** [comment]
What is the status of this?

**Comment by pires** [comment]
The proposal is on stand-by as per https://github.com/kubernetes/kubernetes/issues/28138#issuecomment-268861062.

**Comment by anguslees** [comment]
Fwiw I think the "API" part of this discussion is over-complicating the issue.  Afaics there are two desires here:
1. Allow certain pods (managed through regular k8s API) to be persisted to disk, and restored on reboots (before/until the controller tells us otherwise).
2. Have a way to manually inject entries into the database used for (1) for initial bootstrapping.

(.. and the plan then is to replace static pods with something that can be used for bootstrapping, but is also managed via regular API going forwards - which is awesome.  Big +1 to the overall goal here.)

I hope the above rephrasing as "have a checkpoint database of some sort", and "have a backdoor/manual way to insert entries into the database while offline" makes this feature easier to implement.  To me (2) sounds as easy as dropping files into some sort of /var/lib/kubelet directory in the right yaml format before starting the kubelet.  No special "API" is necessary.

**Comment by aaronlevy** [comment]
@anguslees https://github.com/kubernetes/kubernetes/pull/50984 is close to what you're describing.

**Comment by anguslees** [comment]
@aaronlevy, I knew it was in discussion but hadn't chased down the specific bug - thanks.

So that covers (1) - and assuming that we know the on-disk format and can do (2) - then I think we can bootstrap, and also recover from a cluster-wide reboot.  Is there a remaining use-case that requires a new kubelet pod api, or can we close this issue in favour of #50984?

**Comment by mihirnimbalkar** [comment]
Was there any update on this issue?

I believe we'd greatly benefit from this kubelet API. Our use case is:

We run a standalone kubelet and pass manifest file in /etc/kubernetes/manifests/ folder. We tightly tune --file-check-frequency and --sync-frequency intervals but we still notice a few hundred milliseconds of delay between writing the file and the container start. We could potentially avoid this latency by calling such API directly instead.

**Comment by ehashman** [comment]
/kind feature

I don't think there is any plan to support this. There are a couple ways I could see doing this:

- **add a kubelet API for a kubelet running as part of a cluster:** this breaks assumptions and guarantees around the API server as hub and sole source of truth of cluster state; we already have a number of bugs and race conditions around how kubelets handle static and mirror pods, and this will only make that issue worse
- **add a kubelet API for a kubelet running in standalone mode, as an addition or replacement to the static pod manifest directory:** the kubelet is not designed to run in standalone mode as a matter of course; this is mainly used for bootstrapping. I don't think SIG Node has any plans to add to functionality in this mode.

It's already not recommended to run a lot of static pods on the kubelet, with some limited exceptions.

Given that this has not seen any progress since 2017, I think we should close this, but we can reopen and revisit if there is a viable proposal.

/close
