### ISSUE TITLE
Rework kubeconfig reading/writing to be less complex/racy

### ISSUE THREAD

**Issue by cjcullen** [kubernetes/kubernetes#28260]
Following up on the discussion from #28197.

Parallel calls to ModifyConfig can do bad things to your kubeconfig file(s). We put together some quick fixes (#28034 & #28232), neither of which were all that satisfying because of the complexity of loading/storing kubeconfig from multiple locations.

@krousey @deads2k @jlowdermilk @ghodss

**Comment by smarterclayton** [comment]
Maybe the real question is - why are we concurrently writing / reading from kubeconfig?  When as a user will that result in a great outcome?

**Comment by deads2k** [comment]
> Maybe the real question is - why are we concurrently writing / reading from kubeconfig? When as a user will that result in a great outcome?

Our ops team hit it too.  For us, it's usually happening when running multiple parallel maintenance/test scripts using the same creds that all create new-projects.  For kube, I think its happening because they're refreshing a token every five multiple from multiple parallel scripts.

**Comment by smarterclayton** [comment]
As mentioned on the other thread, that's implicitly broken (I don't
consider calling writing to the same config to change context , even with
locks, valid).

On Jun 30, 2016, at 5:03 AM, David Eads <notifications@github.com> wrote:

Maybe the real question is - why are we concurrently writing / reading from
kubeconfig? When as a user will that result in a great outcome?

Our ops team hit it too. For us, it's usually happening when running
multiple parallel maintenance/test scripts using the same creds that all
create new-projects. For kube, I think its happening because they're
refreshing a token every five multiple from multiple parallel scripts.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/28260#issuecomment-229638715>,
or mute the thread
<https://github.com/notifications/unsubscribe/ABG_p3-H6oKf9RB5X7v85cHbHqovu3oWks5qQ7CYgaJpZM4JBuOt>
.

**Comment by smarterclayton** [comment]
Possibly one option would be split the token out into its own file if we're rapidly updating it, and reference it from the config file via path.

**Comment by cjcullen** [comment]
Yeah, that was the original plan. Then you are back in the "multiple files for config" world, but maybe that's okay for just the automatically-refreshed token case. For the general case (being able to persist config for a specific auth-provider), it's still nicer to have all config in one place.

**Comment by smarterclayton** [comment]
Absolutely.  Frequently refreshed tokens was not the original use case,
which was a well encapsulated and easily delivered config blob.  Multiple
config files suck - but unexpected write conflicts (and locking on config)
also sucks

Adding a tokenFile key to the config that is optionally set by login
providers that frequently change values which overrides a token value seems
much more strongly aligned with this use case.  I do think it needs to be
extremely predictable to scripters which commands are allowed to alter
config (impacting scripting).  If that's just a login or config command
we're in a better spot.

On Jul 1, 2016, at 1:52 PM, CJ Cullen <notifications@github.com> wrote:

Yeah, that was the original plan. Then you are back in the "multiple files
for config" world, but maybe that's okay for just the
automatically-refreshed token case. For the general case (being able to
persist config for a specific auth-provider), it's still nicer to have all
config in one place.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/28260#issuecomment-230008941>,
or mute the thread
<https://github.com/notifications/unsubscribe/ABG_p8B8fiZyLitvw6vrIMK6MTgf_MZOks5qRVPEgaJpZM4JBuOt>
.

**Comment by pwittrock** [comment]
@cjcullen Are you planning on working on this or does it need an owner?

**Comment by cjcullen** [comment]
I have no immediate plans to work on this.

**Comment by brendandburns** [comment]
I'm going to take this.  Initial PR expected soon-ish.

**Comment by brendandburns** [comment]
I'm closing this now that TokenFile is supported in the client config file.

Please re-open if you think there are still unaddressed issues.
