### ISSUE TITLE
Online resource oversubscription and external QoS control

### ISSUE THREAD

**Issue by balajismaniam** [kubernetes/kubernetes#28315]
Some jobs in the cluster are allocated resources (i.e., provisioned) to handle maximum loads and unexpected load spikes. As a result, a cluster might remain under-utilized. The cluster utilization can be improved if these temporarily unused resources from over-provisioned jobs can be used for running best-effort jobs. On the other hand, allowing many best-effort jobs jobs to run without any QoS control can easily lead to service-level objective (SLO) violation of the original job that was running on the node. 

**Proposal**
An external QoS controller can continuously monitor the resource usage and resource allocated to each pod in the Kubernetes cluster and calculate the usage slack (i.e., the difference between the resources allocated and the resources used). Based on the slack, the controller can perform actions to allow online resource oversubscription. 

For a more in-depth discussion of the requirements, mechanisms and proposed changes please refer to (and also comment/edit) this shared document [here](https://docs.google.com/document/d/1uulT2AjqXjc_pLtDu0Kw9WyvvXm-WAZZaSiUziKsr68/edit?usp=sharing).

After discussing and solidifying the ideas outlined in the document, we can add them to the docs/proposals and/or docs/design directories. Advice from maintainers on what belongs where is welcome.

**Upstream Work Items**
[#28316 External QoS Controller and Implement resizing a Pod/Container resource envelope via update in the API server.](https://github.com/kubernetes/kubernetes/issues/28316)

**Related Issues**
[#28310: Discovering, bookkeeping and isolating platform resources other than CPU time and main memory.](https://github.com/kubernetes/kubernetes/issues/28310)

cc @davidopp @ConnorDoyle

**Comment by davidopp** [comment]
@kubernetes/sig-scheduling @kubernetes/sig-node

**Comment by vishh** [comment]
This seems to be related to veritical pod auto-scaling - https://github.com/kubernetes/kubernetes/issues/10782

**Comment by timothysc** [comment]
Couldn't this be added as a functional feature to the rescheduler proposal?

**Comment by davidopp** [comment]
The plan was to run one of these controllers per-node. They don't need global information. But even if you ran one per cluster, there are all the standard arguments for separating different logic into different components (why do we have DaemonSet instead of just interpreting ReplicationController with `replicas == -1` as "run on every node", etc.).

My hope is that some day we can unify some of the implementations in Kubernetes where we could benefit from greater sharing, but I think it's too early to do that.

**Comment by timothysc** [comment]
Ohh wait, this sounds more like backfill.

**Comment by therc** [comment]
This sounds good. Is 1.4 a realistic target?

We have a very real use case. We train machine learning models, then make predictions from them. The former is a batch workload that can and probably always should use a GPU device exclusively, so it's not super interesting for oversubscription. The latter is demand-driven, depending on two main variables: model size and customers' access patterns. We can't give a full, expensive GPU to a model that is very small or has little traffic. Not only it'd be a waste of devices, but, being on EC2, it'd also require many more machines, thus forcing the procurement of a lot of CPU/RAM that aren't actually needed.

Thus, we manually oversubscribe the GPUs (NVIDIA's let you open the same device from multiple processes). We've been doing that in VMs and we've started to do that with Kubernetes, too. Since we have fairly stable GPU memory footprints for each model, we use that to decide how to "pack" things together. That's still "easy" while we only have one hardware vintage for serving. It would be nice to get GPU utilization, which a diagnostic tool like `nvidia-smi` can provide, as an additional signal in dynamic oversubscription. That and actual GPU memory allocated.<sup>[1](#myfootnote1)</sup>
 One feature we got for free with VMs was allowing only prod processes to share devices among themselves, but not with dev ones, etc. We will experiment with pod affinity for that.

Oversubscription would also help us with the other side of the coin. Right now there's a very real risk of GPU resources getting stranded, because other workloads might get scheduled on the GPU machines, requesting only CPU/RAM and leaving not enough for GPU pods to fit. Of course, developers often overestimate their application's needs, so those non-GPU pods are often sitting on idle resources, to add insult to injury...


<a name="myfootnote1">1</a>: We actually have three vintages of hardware: the smallest, AWS' g2 instances, for predictions; the intermediate, for training most models; the largest, for our broadest model that just can't be trained on the other two. It would be great, one day, to support all these use cases transparently.

**Comment by derekwaynecarr** [comment]
related:  https://github.com/kubernetes/kubernetes/pull/26751

Are the concerns around BE pods as large when `kubelet` is having a cgroup tier for it, and for each pod within it?  Are you looking to protect SLO guarantees around resources that are not cgroup restricted?

**Comment by ConnorDoyle** [comment]
@derekwaynecarr I think a great example of something that falls outside the Kubelet's current scope is manipulating RMIDs and associated cache allocations. There will be some affordance in the Linux kernel but it's my understanding the cgroups controller won't fly. So, think cgroups-like. I don't have enough historical context personally about the long-term intentions for what functionality the Kubelet will subsume regarding this kind of low-level resource management. This proposal (the "external" part) has some implicit assumption the Kubelet will draw a line in the sand at some point and delegate control for some of the more esoteric mechanisms that are only necessary for high-throughput or extreme low-latency/low-jitter requirements. But maybe that's not true and we can refocus on putting controls upstream. Landing some sort of external interface in K8s seemed attractive at first given the rising number of container runtime implementations; in cases where the only abstraction needed is the Linux process tree it would be nice to avoid having to enable support for those controllers in each runtime impl. Does that help? Also, thoughts / filling in the long-term vision for Kubelet might help us understand what direction makes sense.

**Comment by spiffxp** [comment]
/sig scheduling
/sig node
given the two sig teams mentioned above

**Comment by ConnorDoyle** [comment]
Vote to close this for now unless there is active work on it, or if that work is happening out of tree.

**Comment by balajismaniam** [comment]
+1. This issue is covered by https://github.com/kubernetes/kubernetes/issues/10782 and https://github.com/kubernetes/autoscaler/tree/master/vertical-pod-autoscaler.

**Comment by bgrant0607** [comment]
Closing in favor of VPA.
