### ISSUE TITLE
Disable running node e2e on release branch PRs

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#28357]
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/28354/node-pull-build-e2e-test/12888/

cc @fejta @dchen1107

**Comment by dchen1107** [comment]
Rantao, can you take a look at this one?

**Comment by Random-Liu** [comment]
@dchen1107 Sure. :)

**Comment by yujuhong** [comment]
The PR (#28354) is a cherry-pick to the v1.2 release branch. 
IIRC, the v1.2 node e2e didn't have junit file yet. 

Also, the error below was due to the fact that the old image was deleted during upgrade.
`projects/kubernetes-jenkins-pull/global/images/e2e-node-coreos-stable20160218-image'. The referenced image resource cannot be found., invalid`

Overall, I think the node e2e test for the 1.2 branch may not be very meaningful at all. We can cherrypick and fix a few things (e.g., the image), but I'm not sure about inspecting the failures.
