### ISSUE TITLE
Better way to communicate deployment's RS garbage collection

### ISSUE THREAD

**Issue by janetkuo** [kubernetes/kubernetes#28373]
I've seen many users find it confusing. It seems that just documenting ideas about `.spec.revisionHistoryLimit` isn't enough. The help text of `--show-all` may be confusing too (`When printing, show all resources (default hide terminated pods.)`). 

An example of user confusion: https://github.com/kubernetes/kubernetes/issues/13621#issuecomment-229171096

How may we make this more intuitive in terms of:
1. Why are there 0 replica ReplicaSets sitting in my system?
2. Why aren't `--show-all` reflecting this?
3. The relationship between old ReplicaSet and rollback (revision history)?

The first step could be improving related `kubectl` commands, for example, PR https://github.com/kubernetes/kubernetes/pull/27510 is hiding 0 replica RSes by default. More thoughts are welcome. 

@kubernetes/kubectl @kubernetes/deployment

**Comment by osterman** [comment]
I think by default the `get` command should hide resources that are inactive and then the `--show-all` command generalized to work across resource types. If that's unreasonable, then the `--show-all` flag should be renamed to `--show-all-pods`.

**Comment by smarterclayton** [comment]
Hiding zero scale RS by default seems strange, since users may never know
that the RS exists otherwise.  Possibly we could sort the list more
effectively?

On Jul 1, 2016, at 2:28 PM, Janet Kuo <notifications@github.com> wrote:

I've seen many users find it confusing. It seems that just documenting
ideas about .spec.revisionHistoryLimit isn't enough. The help text of
--show-all may be too confusing too (When printing, show all resources
(default hide terminated pods.)).

An example of user confusion: #13621 (comment)
<https://github.com/kubernetes/kubernetes/issues/13621#issuecomment-229171096>

How may we make this more intuitive in terms of:

   1. Why are there 0 replica ReplicaSets sitting in my system?
   2. Why aren't --show-all no reflecting this?
   3. The relationship between old ReplicaSet and rollback (revision
   history)?

The first step could be improving related kubectl commands, for example, PR
#27510 <https://github.com/kubernetes/kubernetes/pull/27510> is hiding 0
replica RSes by default. More thoughts are welcome.

@kubernetes/kubectl <https://github.com/orgs/kubernetes/teams/kubectl>
@kubernetes/deployment <https://github.com/orgs/kubernetes/teams/deployment>

—
You are receiving this because you are on a team that was mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/28373>, or mute the thread
<https://github.com/notifications/unsubscribe/ABG_p8TXx1EixVrO8F6yAQ3RcOVxJeHPks5qRVxXgaJpZM4JDYPY>
.

**Comment by therc** [comment]
As just one data point: a few weeks ago I had 2680 replicasets in one of my clusters. I think they originated from somewhere between 7 and 10 deployments. I noticed that while trying to debug why kube-dashboard's `/workload` was so slow. `kubectl get rs` was useless, also because, with so many entries, it's hard for a human to quickly tell columns with single-digit, non-zero entries (1-9) from the inactive ones that have zero. I have since enabled history limits, so we have less than a hundred replicasets, but without effective sorting/hiding, it still feels like a game of `spot the difference`, hence #27510.

**Comment by smarterclayton** [comment]
As noted as long as a new user knows there are others (and how to see them)
it's less of an issue to hide them.

On Jul 1, 2016, at 7:02 PM, Rudi C <notifications@github.com> wrote:

As just one data point: a few weeks ago I had 2680 replicasets in one of my
clusters. I think they originated from somewhere between 7 and 10
deployments. I noticed that while trying to debug why kube-dashboard's
/workload was so slow. kubectl get rs was useless, also because, with so
many entries, it's hard for a human to quickly tell columns with
single-digit, non-zero entries (1-9) from the inactive ones that have zero.
I have since enabled history limits, so we have less than a hundred
replicasets, but without effective sorting/hiding, it still feels like a
game of spot the difference, hence #27510
<https://github.com/kubernetes/kubernetes/pull/27510>.

—
You are receiving this because you are on a team that was mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/28373#issuecomment-230064934>,
or mute the thread
<https://github.com/notifications/unsubscribe/ABG_p7ZEtfmPd8FQp3h4jTr4IB5PP4cBks5qRZx6gaJpZM4JDYPY>
.

**Comment by kargakis** [comment]
@janetkuo the user comment you are linking to doesn't seem specific to the RS garbage collection but is fundamentally wrong in assuming that 0 replicas == terminated. There is no such thing as a terminated RS. Maybe it's fine to filter out these RSs in the dashboard but I would not do it for plain kubectl.
