### ISSUE TITLE
Improve SEO for kubernetes.io

### ISSUE THREAD

**Issue by proppy** [kubernetes/kubernetes#2838]
make sure default query for kubernetes led to an actual landing page (kubernetes.io) and not github repo

Part of #2633

**Comment by bgrant0607** [comment]
And doc queries generally should:
a) Find relevant docs
b) Hit kubernetes.io

**Comment by RichieEscarez** [comment]
I found some guidance here that ill try to digest and take action on: https://support.google.com/webmasters/answer/35291?hl=en

**Comment by RichieEscarez** [comment]
**In progress**
(1) 
Keywords gathered from current site analytics have been sent to our SEO rep. We are now awaiting feedback/recommendations.

**Possible actions**
(2)
Ive also reviewed of the [Google SEO help topic](https://support.google.com/webmasters/answer/35291?hl=en) that I posted previously and the only viable recommendation is to revisit and revise titles so that they more accurately describe the content.

(3)
One other possible change that might help improve SEO would be to add canonical links into all the source files in the GitHub repo (master branch). If we add canonical links at the bottom of each help topic then web crawls are made aware that our recommended versions of our help lives on kubernetes.io:
https://support.google.com/webmasters/answer/139066?vid=1-635800074863437517-1115139372&vid=1-635800074863437517-1115139372#4

**Status:**
At this point, we are going to wait for advice from our SEO rep. and determine how to take action then. (given that its not clear what actions will provide real benefits and that the options Ive found so far are time consuming). 

Initial feedback from peers indicate that SEO can be a long and tedious effort -> this might be more efficiently accomplished as a team. Will post necessary actions here after receiving SEO recommendations from rep.

@MikeJeffrey

**Comment by bgrant0607** [comment]
cc @mansoorj

**Comment by bgrant0607** [comment]
https://github.com/blog/2162-better-discoverability-for-github-pages-sites
https://github.com/benbalter/jekyll-seo-tag
https://help.github.com/articles/sitemaps-for-github-pages/

cc @kubernetes/docs

**Comment by bgrant0607** [comment]
SEO analysis and recommendations:
https://docs.google.com/document/d/1AjMme3SGvvvRLyqpiGHNre5eDmvSQ1qw_4TulwqVFF8/edit?ts=57d83df9

**Comment by bgrant0607** [comment]
Subsumed by doc overhaul, and docs have been moved to kubernetes.github.io, so closing here
