### ISSUE TITLE
Job controller should not rely on calculating pod for its status

### ISSUE THREAD

**Issue by soltysh** [kubernetes/kubernetes#28486]
Currently [our job controller](https://github.com/kubernetes/kubernetes/blob/35a345269eac879b0d9f25110d598845dcf8a62f/pkg/controller/job/controller.go#L452-L456) relies on completed and failed pods to stay around to be properly calculated. This might become cumbersome when a job will be big (iow. high completions number). It would be nice to re-implement this part so that those status numbers are updated on each run rather than re-calculated each time.

@erictune you've mentioned this some time ago, it would be nice to fix it some time, that's why I'll create this issue so we don't forget.

**Comment by soltysh** [comment]
This will be related to #28484.

**Comment by clamoriniere1A** [comment]
Hi @soltysh

Working on #48075. As you referenced in it, I need first to fix this issue in order to simplify the implementation of the "Backoff policy and failed pod limit" (https://github.com/kubernetes/community/pull/583).

I would like to clarify/rephrase what you said in this issue by 

> It would be nice to re-implement this part so that those status numbers are updated on each run rather than re-calculated each time

my understanding is: 
* by "each run" you are referencing the Pods lifecycle (add, update events)
* by "each time" you are referencing the execution of the ```syncJob(...)```method?
Did I understand correctly? 

For improving the current Job Controller implementation, my idea is to modify the ```updatePod(...)```method in order to increment/decrement the JobStatus counters (active, succeeded, failed) of the associated Job. Then remove the "re-calculation" of those counters in the ```syncJob``` method.

Are you agree with the idea? Else could you give me more advice on how to fix it?

**Comment by soltysh** [comment]
> Are you agree with the idea? Else could you give me more advice on how to fix it?

@clamoriniere1A basically I agree with all you've said. But the biggest problem is how to know which pods you've already calculated and which not. We need to make sure we hold some information about state of the job, so that we don't include one pod multiple times. It looks simple but is not. We can think discuss this more during next release, I'm hoping to push this forward in 1.9 (maybe).

**Comment by foxish** [comment]
The `FailedPodsLimit` functionality is not going to be enabled on in 1.8? We should edit the relnote in https://github.com/kubernetes/kubernetes/pull/48075 to indicate that. 
@soltysh, what would be the implications of having the backoff but not the limit parameter?

**Comment by bgrant0607** [comment]
A straightforward solution would be to use finalizers on the pods to prevent deletion until the job was deleted, though that would obviously inhibit GC, which could be problematic for large jobs.

A refinement to that would be to create the pods with the finalizer and then remove the finalizer once the pod's completion has been accounted for. That would require a short dance:
1. Add the pod to a list on the Job when modifying the completion count
2. Remove the finalizer from the pod
3. Remove the pod from the list on the Job once the pod is confirmed to be gone

The completions are recorded in status. That still meets my requirement of "must be able to recompute from observation or acceptable to lose", as this would just reduce the likelihood of rerunning instances, not eliminate it.

cc @kow3ns @janetkuo @erictune @kubernetes/sig-apps-bugs

**Comment by soltysh** [comment]
I was also thinking about some kind of observed generation, similarly to how deployments handle. But in the case of a job it might be working slightly different.

**Comment by seh** [comment]
How does this interact with the controller manager's `terminated-pod-gc-threshold` parameter? According to [the documentation](https://kubernetes.io/docs/reference/command-line-tools-reference/kube-controller-manager/), by default, once 12,500 completed pods exist, the controller can start deleting them.
> Number of terminated pods that can exist before the terminated pod garbage collector starts deleting terminated pods. If <= 0, the terminated pod garbage collector is disabled.

If the job controller relies on these pods existing for accurate accounting, it sounds like that automatic collection would interfere. Or does the garbage collector hold off on collecting pods with an owner reference set?

**Comment by bgrant0607** [comment]
@seh Currently, pod GC does interfere.

**Comment by seh** [comment]
Thank you for confirming. I appreciate your strong comment [here](https://github.com/kubernetes/kubernetes/pull/74987#issuecomment-483485977).

**Comment by alculquicondor** [comment]
Was there ever a better proposal than Brian's? https://github.com/kubernetes/kubernetes/issues/28486#issuecomment-394558752

**Comment by alculquicondor** [comment]
@bgrant0607 

> 1. Add the pod to a list on the Job when modifying the completion count

Is the proposal to keep this list in the Job Status? This might be a big overhead if completions is a big number.

And at this point we also increment the counter (failed or succeeded)?

> 2. Remove the finalizer from the pod
> 3. Remove the pod from the list on the Job once the pod is confirmed to be gone

I don't think we want to remove Pods from the controller. That's up to GC and the new TTL controller. So, in general, Pod names or IDs would remain in the list.

**Comment by alculquicondor** [comment]
*Thanks to @lavalamp for brainstorming this with me offline*

I have a 2nd proposal that addresses the issue of unbounded number of IDs added to `.status`.
Instead of keeping track of the counted Pods, we keep track of the uncounted Pods in a `.status.uncountedPods` field. The flow goes like this:

1. Controller creates Pods with finalizer
1. Pod finishes
1. Controller adds a Pod to the .status.uncountedPods list, if Pod is finished and has a finalizer.
1. Controller removes finalizer from Pod, if it’s in the uncountedPods list.
1. Controller removes the Pod from uncountedPods list and increments the failures or completions counters, in a single API call

Normally, 3-5 happen in a single Job sync cycle, but the controller can go down in-between. The extra API call in step 3 guarantees that information is not lost.

Pro:
Size of .uncountedPods list is somewhat bounded by .spec.parallelism (unless the controller is down for a long time). In general, this list only contains Pods that finished in-between 2 Job syncs. We can also limit the number of Pods that get added to the list in a single sync cycle, if it's a big concern.

Con:
One extra API call: Job status gets updated twice, before and after removing the finalizer.

**Comment by lavalamp** [comment]
I think the extra API call is not an issue, we can halve the update frequency if need be. Multiple pod changes can be batched together in step 3 and again in step 5.

**Comment by erictune** [comment]
That proposal sounds good.
Just to clarify: although the finalizer is added to the pod, in normal operation, the controller removes the finalizer to it long before it actually would block pod deletion.  Right?

**Comment by alculquicondor** [comment]
Assuming users normally delete Job Pods after they have completed, yes. Same for the TTL controller.

Now, if a user wants to delete a Job (or one of the Pods) before they complete, they get a deletion timestamp. Eventually the kubelet marks them as Failed and then the Job controller can pick it up and remove the finalizer. But... this is a good corner case to add to the tests.

**Comment by lavalamp** [comment]
I think that's an improvement over today.

The risk is a bug in the Job controller causes the finalizers to not be removed, which keeps the pods around and eventually overwhelms the system.

**Comment by alculquicondor** [comment]
I got it working kubernetes/kubernetes#98238

I'll send a KEP PR soon, now that I've figured all the details.

**Comment by alculquicondor** [comment]
I have one implementation detail left (hopefully last).

Today, we declare a Job completed as soon as .status.succeeded >= .spec.completions, even though there might be active pods still running (which are left there running). This could happen in 2 scenarios: the job controller restarts and didn't see all the pods yet (so initially miscalculates active pods) or if the job is adopting running pods.
We also stop syncing jobs once they have been declared completed (succeeded or failed).

If I do the same in the new tracking, then I would be left with running pods with finalizers that can't be cleared.

Options:

1. Do not declare completed until active=0
2. Delete active pods one job is declared completed. This is equivalent to calling taking into consideration succeeded pods in `manageJob` also for deletions.
3. Declare job completed, but keep a finalizer on it. Keep syncing the job even if completed. Remove the finalizer once there are no pods left with one. I already decided that I need a job finalizer regardless. Will add to the KEP once my prototype passes all unit tests :)

1 could be confusing. 2 is a breaking change. So probably 3? We just might do more syncs. But in the regular scenario this shouldn't happen.

@soltysh thoughts?

**Comment by ahg-g** [comment]
why is option 2 a breaking change? is this part of the job completion semantics? I would expect that all running pods to be deleted once a job is declared completed.

**Comment by alculquicondor** [comment]
It's breaking just because it's not what happens today. Those pods are left to finish, even if they are not tracked.

**Comment by ahg-g** [comment]
A breaking change is one that violates declared semantics, those pods being left to finish was perhaps an implementation detail, not something the api promised.

**Comment by ahg-g** [comment]
To me this is similar to the case were parallelism was reduced, we don't wait for the extra pod to complete, they just get deleted.

**Comment by alculquicondor** [comment]
Yeah, that should be the way to solve it, if implicit implementation details don't matter. We would do the same for both legacy and finalizers tracking.

**Comment by lavalamp** [comment]
> A breaking change is one that violates declared semantics

At some point we care about the perceived or expected semantics more than the explicitly declared ones, especially if we've been less than perfectly clear or let the situation drag on for a long time.

**Comment by ahg-g** [comment]
> At some point we care about the perceived or expected semantics more than the explicitly declared ones, especially if we've been less than perfectly clear or let the situation drag on for a long time.

I agree, it is also not correct that a change is a breaking one if it is not what we do today.

I don't believe we care about it in this instance because the exact number of active pods is not guaranteed at any point during the job execution, we may go above or below the requested parallelism, and when it is above we delete excess active pods to reach the desired parallelism level. We don't guarantee that all pods the controller creates will actually complete.

**Comment by lavalamp** [comment]
Yeah if people already have to handle this condition then there's definitely no compatibility problem :)

**Comment by alculquicondor** [comment]
So 2 votes for 2

@soltysh anything to add?
