### ISSUE TITLE
Node Controller doesn't recheck that a node has the correct AWS tags on retry

### ISSUE THREAD

**Issue by thomaso-mirodin** [kubernetes/kubernetes#28519]
Context: I'm currently working on getting minions working with AWS Spot Fleet. Instead of using the workaround discussed in #24472 I decided to setup a service that would regularly poll the AWS API, list the instances and tag them as required (see: https://github.com/thomaso-mirodin/spot-fleet-tagger for my basic impl).

It seems that if a newly registered kubelet fails the first cloud provider health check, the node controller will never actually rerun the cloud provider health check fully unless the minion's kubelet process is restarted (via init or reboot). It seems that the retry loop the kubelet is in will at least attempt some partial rejoin, but because the node controller never seems to rerun the cloud provider healthcheck it will fail indefinitely.

Relevant logs from the controller manager:

```
I0705 23:29:40.016523       1 nodecontroller.go:415] NodeController observed a new Node: api.Node{TypeMeta:unversioned.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:api.ObjectMeta{Name:"ip-10-20-11-49.us-west-2.compute.internal", GenerateName:"", Namespace:"", SelfLink:"/api/v1/nodes/ip-10-20-11-49.us-west-2.compute.internal", UID:"579ae109-4308-11e6-8089-023c36c152d3", ResourceVersion:"42783938", Generation:0, CreationTimestamp:unversioned.Time{Time:time.Time{sec:63603358178, nsec:0, loc:(*time.Location)(0x3b1c5c0)}}, DeletionTimestamp:(*unversioned.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string{<REMOVED>}, Images:[]api.ContainerImage(nil)}}
I0705 23:29:40.016715       1 nodecontroller.go:603] Recording Registered Node ip-10-20-11-49.us-west-2.compute.internal in NodeController event message for node ip-10-20-11-49.us-west-2.compute.internal
W0705 23:29:40.016787       1 nodecontroller.go:670] Missing timestamp for Node ip-10-20-11-49.us-west-2.compute.internal. Assuming now as a timestamp.
I0705 23:29:40.016803       1 event.go:211] Event(api.ObjectReference{Kind:"Node", Namespace:"", Name:"ip-10-20-11-49.us-west-2.compute.internal", UID:"ip-10-20-11-49.us-west-2.compute.internal", APIVersion:"", ResourceVersion:"", FieldPath:""}): type: 'Normal' reason: 'RegisteredNode' Node ip-10-20-11-49.us-west-2.compute.internal event: Registered Node ip-10-20-11-49.us-west-2.compute.internal in NodeController
I0705 23:29:40.480742       1 nodecontroller.go:504] Deleting node (no longer present in cloud provider): ip-10-20-11-49.us-west-2.compute.internal
I0705 23:29:40.480766       1 nodecontroller.go:603] Recording Deleting Node ip-10-20-11-49.us-west-2.compute.internal because it's not present according to cloud provider event message for node ip-10-20-11-49.us-west-2.compute.internal
I0705 23:29:40.480812       1 event.go:211] Event(api.ObjectReference{Kind:"Node", Namespace:"", Name:"ip-10-20-11-49.us-west-2.compute.internal", UID:"ip-10-20-11-49.us-west-2.compute.internal", APIVersion:"", ResourceVersion:"", FieldPath:""}): type: 'Normal' reason: 'DeletingNode' Node ip-10-20-11-49.us-west-2.compute.internal event: Deleting Node ip-10-20-11-49.us-west-2.compute.internal because it's not present according to cloud provider
I0705 23:29:45.518965       1 nodecontroller.go:430] NodeController observed a Node deletion: ip-10-20-11-49.us-west-2.compute.internal
I0705 23:29:45.518997       1 nodecontroller.go:603] Recording Removing Node ip-10-20-11-49.us-west-2.compute.internal from NodeController event message for node ip-10-20-11-49.us-west-2.compute.internal
I0705 23:29:45.519197       1 event.go:211] Event(api.ObjectReference{Kind:"Node", Namespace:"", Name:"ip-10-20-11-49.us-west-2.compute.internal", UID:"ip-10-20-11-49.us-west-2.compute.internal", APIVersion:"", ResourceVersion:"", FieldPath:""}): type: 'Normal' reason: 'RemovingNode' Node ip-10-20-11-49.us-west-2.compute.internal event: Removing Node ip-10-20-11-49.us-west-2.compute.internal from NodeController
I0705 23:29:45.597424       1 nodecontroller.go:603] Recording Deleting all Pods from Node ip-10-20-11-49.us-west-2.compute.internal. event message for node ip-10-20-11-49.us-west-2.compute.internal
I0705 23:29:45.597512       1 nodecontroller.go:839] Starting deletion of pod kube-proxy-ip-10-20-11-49.us-west-2.compute.internal
I0705 23:29:45.597795       1 event.go:211] Event(api.ObjectReference{Kind:"Node", Namespace:"", Name:"ip-10-20-11-49.us-west-2.compute.internal", UID:"ip-10-20-11-49.us-west-2.compute.internal", APIVersion:"", ResourceVersion:"", FieldPath:""}): type: 'Normal' reason: 'DeletingAllPods' Node ip-10-20-11-49.us-west-2.compute.internal event: Deleting all Pods from Node ip-10-20-11-49.us-west-2.compute.internal.
I0705 23:29:45.598241       1 event.go:211] Event(api.ObjectReference{Kind:"Pod", Namespace:"kube-system", Name:"kube-proxy-ip-10-20-11-49.us-west-2.compute.internal", UID:"5a78bb56-4308-11e6-8089-023c36c152d3", APIVersion:"v1", ResourceVersion:"42783969", FieldPath:""}): type: 'Normal' reason: 'NodeControllerEviction' Marking for deletion Pod kube-proxy-ip-10-20-11-49.us-west-2.compute.internal from Node ip-10-20-11-49.us-west-2.compute.internal
I0705 23:29:45.618804       1 nodecontroller.go:400] forceful deletion of kube-proxy-ip-10-20-11-49.us-west-2.compute.internal succeeded
E0705 23:29:45.620287       1 nodecontroller.go:352] pods "kube-proxy-ip-10-20-11-49.us-west-2.compute.internal" not found
I0705 23:29:45.692231       1 nodecontroller.go:275] All pods terminated on ip-10-20-11-49.us-west-2.compute.internal
I0705 23:29:45.692256       1 nodecontroller.go:603] Recording Terminated all Pods on Node ip-10-20-11-49.us-west-2.compute.internal. event message for node ip-10-20-11-49.us-west-2.compute.internal
I0705 23:29:45.692316       1 event.go:211] Event(api.ObjectReference{Kind:"Node", Namespace:"", Name:"ip-10-20-11-49.us-west-2.compute.internal", UID:"ip-10-20-11-49.us-west-2.compute.internal", APIVersion:"", ResourceVersion:"", FieldPath:""}): type: 'Normal' reason: 'TerminatedAllPods' Node ip-10-20-11-49.us-west-2.compute.internal event: Terminated all Pods on Node ip-10-20-11-49.us-west-2.compute.internal.
E0705 23:30:33.847780       1 nodecontroller.go:352] pods "kube-proxy-ip-10-20-11-49.us-west-2.compute.internal" not found
I0705 23:30:33.851718       1 nodecontroller.go:400] forceful deletion of kube-proxy-ip-10-20-11-49.us-west-2.compute.internal succeeded
I0705 23:30:34.785403       1 nodecontroller.go:400] forceful deletion of kube-proxy-ip-10-20-11-49.us-west-2.compute.internal succeeded
E0705 23:30:34.787754       1 nodecontroller.go:352] pods "kube-proxy-ip-10-20-11-49.us-west-2.compute.internal" not found
I0705 23:31:03.859249       1 nodecontroller.go:400] forceful deletion of kube-proxy-ip-10-20-11-49.us-west-2.compute.internal succeeded
E0705 23:31:03.861216       1 nodecontroller.go:352] pods "kube-proxy-ip-10-20-11-49.us-west-2.compute.internal" not found
# instance now has the required tags
E0705 23:31:33.869395       1 nodecontroller.go:352] pods "kube-proxy-ip-10-20-11-49.us-west-2.compute.internal" not found
I0705 23:31:33.869942       1 nodecontroller.go:400] forceful deletion of kube-proxy-ip-10-20-11-49.us-west-2.compute.internal succeeded
E0705 23:31:33.894830       1 nodecontroller.go:352] pods "kube-proxy-ip-10-20-11-49.us-west-2.compute.internal" not found
I0705 23:32:03.878586       1 nodecontroller.go:400] forceful deletion of kube-proxy-ip-10-20-11-49.us-west-2.compute.internal succeeded
I0705 23:32:03.891587       1 nodecontroller.go:400] forceful deletion of kube-proxy-ip-10-20-11-49.us-west-2.compute.internal succeeded
E0705 23:32:03.892869       1 nodecontroller.go:352] pods "kube-proxy-ip-10-20-11-49.us-west-2.compute.internal" not found
E0705 23:32:33.888816       1 nodecontroller.go:352] pods "kube-proxy-ip-10-20-11-49.us-west-2.compute.internal" not found
# repeats forever
```

Sorry if this is expected behavior or if I'm misunderstanding the steps involved when a kubelet joins the minion pool but I looked at the docs and the node controller code and neither gives me the impression that retries would not actually attempt to rejoin the cluster.
- https://github.com/kubernetes/kubernetes/blob/master/docs/design/aws_under_the_hood.md#tagging
- https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/node/nodecontroller.go#L634

There are a few workarounds available to me (reboot via API, cron job to check nodes labels and restart the kubelet, etc) but they are all less than ideal :D

---

Versions:

```
# Worker Kubelet
core@ip-10-20-0-10 ~ $ /opt/bin/kubelet --version
Kubernetes v1.2.4
```

```
# Controller Manager's Hyberkube
root@ip-10-20-0-10:/# /hyperkube --version
Kubernetes v1.2.4
```

Both were compiled from `3eed1e3be6848b877ff80a93da3785d9034d0a4f`

**Comment by philk** [comment]
Interestingly enough this also happens when requesting spot instances from an autoscale group. About 1 in 50 instances end up stuck in this non-state:

1. node boots
1. kubelet starts and registers itself
1. controller-manager deletes the node `Recording Deleting Node blah because it's not present according to cloud provider`
1. kubelet sits around doing nothing responding happily the `/healthz` with ok which we _were_ using to determine the node was healthy

I'm not sure what the right answer here is since I realize the kubelet being registered to the API server may not be part of "healthy" depending on how you want to define it (or what you're using the kubelet for, such as in kubelet self-bootstrapping). My ideal would be that the kubelet exit's non-zero if it can't find its node but we're also not using manifests so for us if the kubelet isn't connected to a master it's useless.

**Comment by thomaso-mirodin** [comment]
@kubernetes/sig-aws-misc should this be categorized as an AWS issue or a sig-cluster-* issue?

**Comment by sdlarsen** [comment]
I experience this as well, but a lot more frequent than 1 in 50 nodes. More like 1:5.

In the manager logs i see:
`I1227 14:55:34.106018       7 node_controller.go:721] Deleting node (no longer present in cloud provider):
 ip-172-20-36-55.ec2.internal
I1227 14:55:34.106040       7 controller_utils.go:237] Recording Deleting Node ip-172-20-36-55.ec2.interna
l because it's not present according to cloud provider event message for node ip-172-20-36-55.ec2.internal
W1227 14:55:34.106090       7 node_controller.go:916] Missing timestamp for Node ip-172-20-55-146.ec2.inte
rnal. Assuming now as a timestamp.
I1227 14:55:34.106202       7 event.go:218] Event(v1.ObjectReference{Kind:"Node", Namespace:"", Name:"ip-1
72-20-36-55.ec2.internal", UID:"fb396d12-eb15-11e7-b3b9-0ac90041afde", APIVersion:"", ResourceVersion:"",
FieldPath:""}): type: 'Normal' reason: 'DeletingNode' Node ip-172-20-36-55.ec2.internal event: Deleting No
de ip-172-20-36-55.ec2.internal because it's not present according to cloud provider
I1227 14:55:34.147174       7 node_controller.go:721] Deleting node (no longer present in cloud provider):
 ip-172-20-55-146.ec2.internal
I1227 14:55:34.147196       7 controller_utils.go:237] Recording Deleting Node ip-172-20-55-146.ec2.intern
al because it's not present according to cloud provider event message for node ip-172-20-55-146.ec2.intern
al
`

This on a fresh kubernetes 1.8.6 cluster with cluster-autoscaler 1.0.3 - created with cups 1.8.0 (I've tried latest CoreOS stable in addition to the stock debian image to no avail)
