### ISSUE TITLE
kubelet container runtime API machinery

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#28642]
The umbrella issue for container runtime interface/API: #28396

PR #17048 introduces the client/server architecture to improve container runtime integration. The PR uses protobuf+grpc, with API defined manually in the proto files and the corresponding go code generated automatically. This process is straightforward and let us focus on the iterating the API itself.

In the long run, we may want to reconsider these choices to ensure we have a good upgrade (roll forward/back) story for kubelet and the container runtime, while keeping the manual maintenance overhead manageable. One option is to follow the standard kubernetes API and reuse all the framework/machinery (see the [api changes doc](https://github.com/kubernetes/kubernetes/blob/5617360d39aba337f1617775ad97850ad27361f8/docs/devel/api_changes.md) for an overview).
This includes (but not limited to):
- Versioned API+internal structs
- Versioned defaulting
- Automatically generated conversion code (from versioned to internal structs)
- Validation

/cc @kubernetes/sig-node

**Comment by feiskyer** [comment]
Add more open questions:

* Do we need authn for runtime API? @thockin 
* Does it really have to add new flags to kubelet (e.g. `--container-runtime-endpoint` and `--image-service-endpoint`)? What about dropping a UNIX socket or a metadata file into a known place? @thockin

**Comment by feiskyer** [comment]
Here is a comparison between API machinery and proposed method in #17048:

## API machinery (follows the standard kubernetes API)

Kubelet always use a versioned client to work with runtimes (same with k8s apiserver and versioned client today).

**How to achieve this**:

* define versioned and unversioned api, e.g. `api/runtime/` and `api/runtime/v1`
* modify `deepcopy-gen` to include `api/runtime/` and `api/runtime/v1`
* run `deepcopy-gen` to generate convertion functions ( a sample is [here](https://gist.github.com/feiskyer/c7d06ef02a7037a58ddbca9025c6c44c))
* kubelet gets remote runtime's API version by calling `Version()` first and then creates a versioned client for interacting with the runtime.

A limitation of `deepcopy-gen` is it doesn't process interfaces. If a new interface is added or removed, it should be added or removed in all versioned packages manually.

**Pros**:

* Same upgrade story with existing kubernetes API
* Reuse framework/machinery

**Cons**:

* need to maintain several versioned clients
* need converting types from different versions
* need process interface adding/removing manually

## Proposed method in #17048 (Requires a minimum version of runtime API)

Kubelet (aka the client) only requires a minimum version of runtime API and supports all versions above it.

**How to achieve this**:

* Follow [protobuf rule](https://developers.google.com/protocol-buffers/docs/proto#updating) on updating runtime API
* Mark the unwanted field in protobuf message as `deprecated` for sevaral versions, e.g. above minimum version (and of course continue to setting values for those field) instead of removing it
* Report error if runtime's API version is smaller than minimum API version

Supposing kubelet runtime API (client) is newer than runtime's (server) one (which is common scenario on kubelet upgrading), let's have a detailed look what will happen on following scenarios:

* Adding new interfaces: the call to the runtime will report an error. This is expected.
* Removing a interface: kubelet will no longer call the removed interface, so this is no problem.
* Updating a message by adding a field: kubelet could continue make request with old versioned runtimes, but runtimes don't see newly added field, which is still expected.
* Updating a message by deprecating a field: by following the rules above, although it is deprecated, we will continue support it for several versions, so old runtimes won't realize any difference.
* Removing a message: this should be included on above cases (interface's request/response message couldn't be removed unless the interface is also removed togather, all other messages are field of request/response message).

**Pros**:

* Simple, just follow protobuf 
* Don't need type conversions

**Cons**:

* still need to maintain some depracated message for old versions
* any updates of runtime API should follow protobuf rules (not sure whether this enforcement could be done automatically)
