### ISSUE TITLE
[Feature] Integrate closely with flannel and/or Calico, via network plugins.

### ISSUE THREAD

**Issue by girishkalele** [kubernetes/kubernetes#28653]
Integrate closely with flannel and/or Calico, via network plugins.

**Comment by luxas** [comment]
cc @luxas

**Comment by cizixs** [comment]
Is there a plan or roadmap for this issue?

**Comment by caseydavenport** [comment]
@cizixs good question.

I'd like to help make this happen, but it would be good to get a better idea of what the issue means by a closer integration.  I suspect this is likely related to the self-hosting work that @mikedanese has been working on.

**Comment by mikedanese** [comment]
This aligns with https://github.com/coreos/flannel/pull/483

What are the exit criteria for closing this feature issue @girishkalele ?

**Comment by caseydavenport** [comment]
@girishkalele could you share what "done" means for this issue?

**Comment by bprashanth** [comment]
@bowei or @freehan might be interested in taking this on

**Comment by caseydavenport** [comment]
@bprashanth I'm still not entirely sure what "this" means.  You can install both Calico + flannel via CNI plugins today - what else does this issue cover?

**Comment by bprashanth** [comment]
I haven't spent enough time penning down requirements, but I'd say at a high level the plugin should:     

1. work with cri (conform to CNI, handle things like host ports and podCIDR -- calico doesn't use podCIDR today right? or somehow figure out how to express that it doesn't handle features like bandwidth shaping)
2. work on all major clouds (gce,aws,DO) and their default choice of base OS (eg: gci). Flannel udp mode won't work on gce for example. 
3. not require any cloudprovider features (like gke clusters need gce advanced routes today)
4. pass full suite of e2es (well, we should probably setup a continuous builder and triage failures)
5. figure out deployment/upgrades for dependencies (like if flannel or calico require a secondary etcd, it would need to become a conditionally deployed cluster addon)

I think there's value in a tried and tested, well documented, cross platform network plugin that just works (and we know it just works because there would be autofiled bugs otherwise).

**Comment by bprashanth** [comment]
bigger picture, basically it should be possible to setup a cluster on [CP of choice] that costs as much as the compute vms, but supports the full feature-set of kube. Today, the big gaps are routing (this bug), ingress and storage. Now obviously this can be *made to work*, as you pointed out there's a CNI plugin, we have an nginx ingress controller, and storage can use emptyDir or hostPath, but SO tells us that people don't have much luck heading down this road. I think a "bare metal" e2e builder running on some vms would be quite a big step.

**Comment by caseydavenport** [comment]
I think this issue should be closed.  Any objections?  @thockin?

**Comment by luxas** [comment]
I also think it should be closed now that we have CNI and CRI that work well, and Calico can be used very easily in all sorts of clusters due to that that interface is satisfied.
