### ISSUE TITLE
Request: A Kubernetes "Hello World" deployment

### ISSUE THREAD

**Issue by aronchick** [kubernetes/kubernetes#28694]
Similar to what Docker does (https://github.com/docker-library/docs/tree/master/hello-world) we should have a 'hello world' deployment, where, in one line, you can create a deployment (or replica set) that outputs something friendly and exits.

**Comment by pwittrock** [comment]
@aronchick nit: This should be a Job if it is going to exit (Deployments are meant to be long lived).

**Comment by pwittrock** [comment]
@ymqytw Creating a docker image that does this and corresponding `kubectl run` command seems like a good getting started task.

**Comment by MHBauer** [comment]
I wouldn't mind working at this, but I'll need some help.

While #28695 exists, we need a pause at the start. 

A minimal example requiring 1.4 based features is:
```
kubectl run hi --quiet --rm --attach --restart=Never --image=alpine  -- sh -c 'sleep 3; echo "Hello from Kubernetes!"'
```

Not quite `docker run hello-world`, but I can explain why we need all the flags.

 - `hi` is needed because run needs a `NAME`
 - `--quiet` to avoid echoing all the garp that I don't want to see as a new user (unless we want to explain said garp, but I would prefer to avoid it at the `hello-world` level)
 - `--rm` is needed because we're not auto generating a name, so we have to clean up to avoid a conflict with `hi` in the future. We should be able to run a `hello-world` example over and over without having any cleanup.
 - `--attach` is needed because `--rm` needs an attached container.
 - `--restart=Never` is to create a regular pod and not a Job or Deployment. Not a deployment, because that's a long running thing. Not a job, because this runs so quickly that it is seen as failed.
 - `--image=alpine  -- sh -c 'sleep 3; echo "Hello from Kubernetes!"'` will be replaced by our custom image which sleeps to get around #28695.

Put it all together and it will look something like 
```
λ kubectl run hi --quiet --rm --attach --restart=Never --image=hello-kube
Hello from Kubernetes!
```

Yes, it really is that painful.

I understand that k8s is more for running infrastructure than individual containers, but it would be really great to get this down to something like `kubectl run --one-shot hello-kube`.

I can write up a dockerfile and hello-world program, but where do we want to put that stuff and the image?

**Comment by ymqytw** [comment]
@MHBauer Thanks for your input. I have create a job as discussed above. example/hello-world directory seems to be a place for this example.

**Comment by soltysh** [comment]
Isn't this example from `kubectl run` sufficient?
```
kubectl run pi --image=perl --restart=OnFailure -- perl -Mbignum=bpi -wle 'print bpi(2000)'
```
This runs a perl image calculating pi number to 2000 places and prints it. There's more detailed info in the [docs](http://kubernetes.io/docs/user-guide/jobs/#running-an-example-job) if needed.

**Comment by ymqytw** [comment]
>kubectl run pi --image=perl --restart=OnFailure -- perl -Mbignum=bpi -wle 'print bpi(2000)'

This example need flag `-i` to print out. And I think `--rm` is needed to clean up for new user. 
We may also need flag `--quiet`, since we want to suppress unnecessary messages to avoid confusing new users.

I can simplify the hello world example to:
`kubectl run hello-world --quiet --rm -i --image=busybox --restart=OnFailure -- echo "Hello from Kubernetes!"`

**Comment by soltysh** [comment]
> I can simplify the hello world example to

There are multiple options how this can be modified. I'm just saying we don't need any dedicated example to show this off. That's why I'm proposing to close this issue, because `kubectl run` has examples how to simply run a job or a deployment. @aronchick agreed?

**Comment by ymqytw** [comment]
I'm OK to get this issue closed if we don't need it any more.

**Comment by soltysh** [comment]
This is already addressed with `kubectl run`.
