### ISSUE TITLE
Some pod update operations are not handling conflict errors correctly

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#28749]
This looks like PATCH pod status is not properly converting the storage error `ErrCodeResourceVersionConflicts` into an API response, possibly due to a code path missing a call to  `InterpretUpdateError`.

```
   1  Failed to update status for pod "_()": Operation cannot be fulfilled on pods "docker-registry-1-deploy": StorageError: resource version conflicts, Code:
   1  Failed to update status for pod "_()": Operation cannot be fulfilled on pods "ipfailover-1-deploy": StorageError: resource version conflicts, Code: 3, K
```

This may result in improper handling of client calls.

**Comment by AdoHe** [comment]
According to code [https://github.com/kubernetes/kubernetes/blob/master/pkg/api/errors/storage/storage.go#L66](https://github.com/kubernetes/kubernetes/blob/master/pkg/api/errors/storage/storage.go#L66), it seems no case in switch satisfy, I think the problem is [IsTestFailed](https://github.com/kubernetes/kubernetes/blob/master/pkg/storage/errors.go#L109) maybe.

**Comment by obeattie** [comment]
I've just encountered the same error when trying to delete a deployment:
```Aug 01 13:19:12 ip-10-101-26-115 docker[896]: E0801 13:19:12.595921       1 deployment_controller.go:400] Error syncing deployment io-gmon/s-3ds: Operation cannot be fulfilled on deployments.extensions "s-3ds": StorageError: resource version conflicts, Code: 3, Key: /registry/deployments/io-gmon/s-3ds, ResourceVersion: 0, AdditionalErrorMsg:```
