### ISSUE TITLE
errors helpers should always set causes

### ISSUE THREAD

**Issue by bparees** [kubernetes/kubernetes#28753]
a number of the pkg/api/errors/errors.go helper methods (eg NewBadRequest) do not set the Details field with a Cause.

@smarterclayton

**Comment by smarterclayton** [comment]
We should probably make it possible to easily add "causes" to several classes of error, because today they are not distinguishable (we basically use an unstructured BadRequest for lots of different conditions that clients might want to differentiate on).  That could potentially be a builder method on StatusError that lets you do something like:

```
NewBadRequest(...).WithCause(StatusCause{}, ...)
``

**Comment by AdoHe** [comment]
SGTM, I would like to do this.
