### ISSUE TITLE
Align scheduler node scoring with cluster autoscaler

### ISSUE THREAD

**Issue by mwielgus** [kubernetes/kubernetes#28842]
Right now it seems that scheduler tries to place pods on nodes that have the most free space. However, from the cluster autoscaler perspective it would be best to place them on the more busy nodes so that the unused nodes are easier to remove.

cc: @fgrzadkowski @davidopp @piosz @jszczepkowski

**Comment by davidopp** [comment]
Changing the default scheduling algorithm from worst-fit to best-fit is a large change (not in terms of code, but in terms of what users will observe). I think you could argue that best-fit is a "power user" feature and should require user action to enable. We could automatically enable it if the user is using cluster autoscaling.

**Comment by mwielgus** [comment]
@davidopp  Yep, we are thinking about switching to best-fit automatically if (and only if) cluster autoscaler is enabled.

**Comment by wojtek-t** [comment]
This is not fixed - we only have this function, but it's not enabled.

**Comment by timothysc** [comment]
Can we close this?  It sounds like an opt-in, not default on.

**Comment by davidopp** [comment]
I don't think we should close this. We have the priority function, but we should try to figure out how to automatically enable it when cluster autoscaler is enabled. I'm not sure it's high priority, since people can enable it manually, but the user experience would be a lot better if it's automatic.

**Comment by bgrant0607** [comment]
Changing scheduling policy seems like a confusing and potentially dangerous hack.

Do we have any idea how much users are implicitly relying upon spreading in order to make oversubscription work?

Also, hopefully "best fit" isn't purely best fit, such that many pods from the same application would fill up one node before spilling over to another? 

Have we considered policies that would be good all the time, such as hybrid spreading/packing?

What would happen to best-effort pods?

**Comment by bgrant0607** [comment]
Also, forcing users to specify node anti-affinity always would be a big step backwards in usability.

**Comment by bgrant0607** [comment]
Additionally, do we have evidence that this would make a significant difference in realistic growth-contraction scenarios? Is the objective to reduce the work the rescheduler would have to do to drain nodes for potential removal?

**Comment by davidopp** [comment]
Let's set best-effort workloads aside for the moment. They might need a different scheduling policy from the others. For now let's just focus on burstable and guaranteed. 

> Do we have any idea how much users are implicitly relying upon spreading in order to make oversubscription work?

I assume by "make oversubscription work" you mean "given a particular number of nodes and a particular set of pods, minimize the amount by which nodes are oversubscribed, thereby relying less on the node-level resource isolation working well"? The thing is that this goal contradicts the goal of maximum utilization. Now, I guess your point is that that enabling cluster autoscaler doesn't necessarily mean the person wants maximum utilization, just that they never want pending pods. So maybe we really need some kind of "top-level" knob that the user adjusts, that in turn affects how aggressive the cluster autoscaler and pod binpacking is. (It could also affect how aggressive the rescheduler and vertical pod autoscaling is.)

> Also, hopefully "best fit" isn't purely best fit, such that many pods from the same application would fill up one node before spilling over to another?

The best-fit algorithm itself is pure best-fit. However, the total priority for a node also takes into account spreading based on service and controller. We can tune the weights to get the balance we want. This is not exactly the same as using a hybrid best-fit/worst-fit binpacking strategy, but it probably has a somewhat similar effect.

> Also, forcing users to specify node anti-affinity always would be a big step backwards in usability.

I assume you're referring to #40358. The problem that's solving is related but not exactly the same. There problem there is: say you have an empty ten-node cluster and create a twelve-node set, and cluster autoscaling is enabled. Regardless of what binpacking algorithm you use, you're going to end up with some nodes hosting more than one pod from the same set. How do you trigger the cluster autoscaler to scale up? The only way to do it *today* is something like #40358. I guess it's possible that the "top-level" knob I hypothesized earlier could be used by the cluster autoscaler to infer what it should do in this scenario, instead of #40358 (having users specify policies explicitly in set description). But it seems that this behavior needs to be configurable somehow, as some users will want the cluster autoscaled in that scenario and some won't.

>  Is the objective to reduce the work the rescheduler would have to do to drain nodes for potential removal?

This issue was based on the assumption that people who use cluster autoscaler also want high utilization. The cluster autoscaler is implicitly making *some* assumption along these lines, otherwise it would only scale up and never scale down. The idea was that it doesn't make sense for the cluster autoscaler to remove nodes to try to pack the workload onto a smaller number of nodes, if the scheduling algorithm is trying to spread the workload onto the maximum number of nodes possible. In a sense they are fighting.

From a practical standpoint, today the cluster autoscaler will not remove a node unless the cpu and memory requests of all pods on the node is < 50% of the node capacity. So using spreading can prevent the cluster autoscaler from working at all.

I think the knob I suggested earlier is needed to address this combination of issues.

As for best-effort, simple usage-based spreading across all available nodes is probably fine, but there is still the question of whether to ever trigger scale-up (today we only trigger scale-up when there are pending pods, and best-effort pods effectively never go pending), and how to handle them during scale-down (since they can always be squeezed onto fewer nodes). It's possible that we need one top-level knob per QoS level or something like that.

**Comment by bgrant0607** [comment]
Another issue to consider is what model we want for shared control over component configuration.

This has also come up for addons: #40108, https://github.com/kubernetes/kubernetes/issues/37048#issuecomment-272510835

**Comment by bgrant0607** [comment]
@davidopp 

I'm not a fan of changing the scheduling prioritization policy based on whether or not cluster (i.e., horizontal node) autoscaling is in use or not. Was this proposed because you believe that users need to opt in to a new policy, and opting in to cluster autoscaling provides an opportunity to change the behavior?

I'd be more in favor of changing to a new default policy that would always be used, regardless whether horizontal node autoscaling were in use or not. Using a policy that is only enabled in some scenarios will decrease testing of and user/admin experience with the policy. It's likely to incur failure modes not exposed by scalability tests, soak tests, upgrade tests, etc. Unless you're suggesting adding another dimension to our test matrix.

Also, while I understand that best fit wouldn't be the only criterion, some amount of spreading of serving workloads by default for availability is critical to usability, as is worst-fit scheduling of best-effort workloads. We need to leave some slack on multiple nodes for spreading new workloads, which is why I think hybrid spreading/packing makes a lot of sense. 

As you know, I do agree that we need to reason about resource management holistically, and that the scheduling, rescheduling, and autoscaling policies need to be aligned. If you'd like to change the threshold for switching the scheduler from packing to spreading to align with a utilization threshold specified for cluster/node autoscaling, that would make sense. As such a threshold could affect multiple components (scheduler, rescheduler, vertical pod autoscaler, horizontal node autoscaler, cluster monitoring/alerting infrastructure), I would get behind a cluster-wide "desired node utilization" threshold or somesuch, either in cluster config (#19831) or even a cluster policy API, since the value could represent semantic intent of a cluster administrator. (Side note: the default amount of time to wait before killing pods on an unresponsive node is another candidate for cluster config/policy.)
