### ISSUE TITLE
ELK Stack Example is missing

### ISSUE THREAD

**Issue by andrewwatson** [kubernetes/kubernetes#28899]
http://kubernetes.io/docs/samples/ still links to https://github.com/kubernetes/kubernetes/tree/release-1.3/examples/logging-demo/ which no longer exists.

**Comment by dims** [comment]
@andrewwatson : looks like when all the docs/examples moved over the docs did not get updated. Can you please throw in a issue in https://github.com/kubernetes/kubernetes.github.io/issues instead of here? Note that the logging-demo is in that repo as well https://github.com/kubernetes/kubernetes.github.io/tree/master/docs/user-guide/logging-demo

thanks!

**Comment by chrislovecnm** [comment]
@saad-ali here is another bug on the examples moved to storage ... 😄

**Comment by saad-ali** [comment]
@chrislovecnm This appears unrelated to https://github.com/kubernetes/kubernetes/pull/27977 That PR did not touch `logging-demo` and is not in the 1.3 release branch

**Comment by xiangpengzhao** [comment]
I think this issue is no longer valid. Please file an issue in https://github.com/kubernetes/kubernetes.github.io/issues if there is still any broken link in http://kubernetes.io/docs/. Thanks!

cc @thockin
