### ISSUE TITLE
Lots of "does not conform to prefix" in controller-manager logs

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#29074]
Looking at node names and prefixes.  Scary message.

**Comment by bprashanth** [comment]
this is from the "gce rejects long filters" fix we put in. the node instance prefix is in /etc/gce.conf, if the service controller finds a node that doesn't match this prefix, it should fallback to listing all nodes.
@zmerlynn

**Comment by zmerlynn** [comment]
@thockin: What was your cluster name? Why was the prefix wrong?

**Comment by thockin** [comment]
This was a customer GKE cluster.  Investigating other issues, saw that.

**Comment by zmerlynn** [comment]
Well, let's just say I'm glad I made the filter advisory. :)

**Comment by zmerlynn** [comment]
The problem here is that GKE isn't filling in a valid `NODE_INSTANCE_PREFIX` - it's still the metadata we use for the node tags, so I'm going to have to tease those apart, but we have a different naming scheme for nodes. This works fine on OSS, though - unless you modify `config-default.sh` and change the `NODE_TAG` naming scheme to e.g. `"${INSTANCE_PREFIX}-node"` (which will make it different than the `NODE_INSTANCE_PREFIX`), at which point you actually end up with a worse issue, which is that the firewall tags are just wrong.

**Comment by spiffxp** [comment]
/sig cluster-lifecycle
/area platform/gke
since we lack a sig-gcp at the moment

**Comment by spiffxp** [comment]
/close
If there is evidence that this is still happening, please reopen with said evidence. 
 The GKE tests that we run don't currently collect logs from the master components, so it's difficult to say whether this is still an issue, eg: http://gcsweb.k8s.io/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gke/20291/artifacts/
