### ISSUE TITLE
will the users get two versions of the pod during the rolling update ?

### ISSUE THREAD

**Issue by gudeyang1** [kubernetes/kubernetes#29174]
if an application have 100 pods ,and i want to update the image from v1 to v2 ,so during the rolling update ,kubernetes will scale the v2 image from 0 to 100 ,and sacle v1 image for 100 to 0 , just during the rolling update period ,some users access the pods ,will the users get two versions ?

**Comment by apelisse** [comment]
Please re-post your question to [stackoverflow]
(http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support
are posted so that we can improve our efficiency in responding to your requests,
and to make it easier for you to find answers to frequently asked questions and
how to address common use cases.

We regularly see messages posted in multiple forums, with the full response
thread only in one place or, worse, spread across multiple forums. Also, the
large volume of support issues on github is making it difficult for us to use
issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to
ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to
similar questions, and also familiarize yourself with:

  * [user guide](http://kubernetes.io/docs/user-guide/)
  * [troubleshooting guide](http://kubernetes.io/docs/admin/cluster-troubleshooting/)

Again, thanks for using Kubernetes.

The Kubernetes Team
