### ISSUE TITLE
Directly connecting a container to an external IP for UDP connections

### ISSUE THREAD

**Issue by hach-que** [kubernetes/kubernetes#29192]
I have a service which receives UDP packets from clients.  It's essential to the operation of this service that it's able to read the IPv4 address and port that the packet is coming from (essentially this service exists for NAT punchthrough in games).

The `LoadBalancer` option in Kubernetes doesn't work because the Google Cloud Load Balancer rewrites the source address, and apparently `NodePort` rewrites it too?  I expected the latter option to directly connect the container to the external port on each node and thus it would be able to receive the UDP traffic with the source address intact.

If it's not intended that `NodePort` maintains the external source IP address and port of the connecting user, is there anyway to do this under Kubernetes, or do I have to look into running a separate (non-container) machine to do what I want?

**Comment by apelisse** [comment]
Please re-post your question to [stackoverflow]
(http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support
are posted so that we can improve our efficiency in responding to your requests,
and to make it easier for you to find answers to frequently asked questions and
how to address common use cases.

We regularly see messages posted in multiple forums, with the full response
thread only in one place or, worse, spread across multiple forums. Also, the
large volume of support issues on github is making it difficult for us to use
issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to
ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to
similar questions, and also familiarize yourself with:

  * [user guide](http://kubernetes.io/docs/user-guide/)
  * [troubleshooting guide](http://kubernetes.io/docs/admin/cluster-troubleshooting/)

Again, thanks for using Kubernetes.

The Kubernetes Team
