### ISSUE TITLE
PreStop NOT WORKING

### ISSUE THREAD

**Issue by antbreton** [kubernetes/kubernetes#29203]
I am trying the "preStop hook on container" feature and it doesn't work. It would be very useful for me. I see on an old issue (#7091) that in 2015 it wasn't implemented. Is it still the case ?

If you want to see the context you can check this link :
http://stackoverflow.com/questions/38310976/openshift-v3-issue-with-prestop-container-hook-with-a-basical-example

**Comment by apelisse** [comment]
Thank you for posting your question to [stackoverflow]
(http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support
are posted so that we can improve our efficiency in responding to your requests,
and to make it easier for you to find answers to frequently asked questions and
how to address common use cases.

We regularly see messages posted in multiple forums, with the full response
thread only in one place or, worse, spread across multiple forums. Also, the
large volume of support issues on github is making it difficult for us to use
issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to
ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to
similar questions, and also familiarize yourself with:

  * [user guide](http://kubernetes.io/docs/user-guide/)
  * [troubleshooting guide](http://kubernetes.io/docs/admin/cluster-troubleshooting/)

Again, thanks for using Kubernetes.

The Kubernetes Team
