### ISSUE TITLE
Node labels disappear after upgrade to 1.3.2 - breaks deployments using nodeSelector

### ISSUE THREAD

**Issue by Salakar** [kubernetes/kubernetes#29218]
---

**Provider:** GCP
**Previous Version:** 1.2.4
**Current Version:** 1.3.2
**Region:** europe-*

---

After upgrading the default node pool via the GCP cloud console UI all the nodes in the pool lost their custom labels I had added previously, this subsequently broke all my deployments after the upgrade, bringing everything down 😭  

Had to go through all my nodes and re-label them and re-deploy all deployments to get everything back up. All the deployments use the `nodeSelector` option, hence why they died without the node labels.

**Comment by pwittrock** [comment]
cc @roberthbailey

**Comment by roberthbailey** [comment]
@Salakar -- I'm sorry that the upgrade broke your deployments. https://cloud.google.com/container-engine/docs/clusters/upgrade (which can be found by following the "Learn More" link in the cloud console) describes how node upgrades are implemented:

> An upgrade/downgrade works by deleting all node instances, one at a time, and replacing them with new instances running the desired Kubernetes version.

Deleting the instances removes them from the Kubernetes cluster, which removes any customizations that you've added to the nodes (including labels), even though the new instance "will be assigned the same instance name" as it is represented by a new Node object in the cluster. 

I've filed a bug to add some clarifications to our documentation to hopefully make this less surprising behavior, and we are also looking at less disruptive options for node upgrades.

The section "More fun with node pools" in https://cloudplatform.googleblog.com/2016/05/introducing-Google-Container-Engine-GKE-node-pools.html describes an alternate mechanism for upgrade the node version in your cluster, which is the way that I currently recommend doing upgrades, since it gives you the most control:

1. Update your deployments to be pinned to your current node pool. 
1. Create a new node pool that is the same size as your current node pool at the desired node version. 
1. Apply any customizations (e.g. node labels) to nodes in the new node pool.
1. Update your deployments to migrate to the new node pool. You can do a gradual migration (e.g. 1%, 10%, 50%, 100%) to canary your application on the new node version, or if you have a small cluster doing a knife switch cutover is ok as well (since you can roll back quickly).
1. Once all deployments have been migrated to the new node pool, you can delete the old node pool.

If you don't want to make the new node pool the same size as your current node pool (due to cost / quota constraints or because you want to do a small canary of the new version), you can create a smaller node pool at the new node version and migrate a subset of your deployments over. As you gain confidence, you can increase the size of the new node pool and decrease the size of the old node pool (as you no longer need the space).

**Comment by grodrigues3** [comment]
@fabioy can we close this
