### ISSUE TITLE
Integrate Docker with new runtime interface

### ISSUE THREAD

**Issue by feiskyer** [kubernetes/kubernetes#29252]
This issue tracks the considerations of integrating Docker with new runtime interface. This is also one TODO of Milestone 3 in #28789.

- Docker will remain in the kubelet codebase.
- The `image.Image` may not have tag, so for docker we've to apply default tag ":latest" here, or else docker will pull all tags of the image.
- Potential issue for docker #16580.
- Docker version requirement, e.g. minimumDockerAPIVersion
- docker apiserver is not semver.

CC @Random-Liu @yujuhong @kubernetes/sig-node

**Comment by Random-Liu** [comment]
@feiskyer Thanks a lot! This would help us avoid losing some old fixes during refactoring.

**Comment by yujuhong** [comment]
Just a note: there is experimental nvidia GPU support in pkg/dockertools. We'll need to handle that.

**Comment by Hui-Zhi** [comment]
So far only Docker support Nvidia GPU, add the GPU interface maybe not a good idea.

**Comment by feiskyer** [comment]
@Hui-Zhi I think it's ok for adding new features to new runtime interfaces, as runtimes could choose whether support to support those features or not.

**Comment by yujuhong** [comment]
> @Hui-Zhi I think it's ok for adding new features to new runtime interfaces, as runtimes could choose whether support those features or not.

I am less sure about that, unless we have a good way for the runtime to express whether it supports or not. 

For example, we may want to make sure the runtime *can* support certain security features (e.g., #29765)

**Comment by yujuhong** [comment]
> So far only Docker support Nvidia GPU, add the GPU interface maybe not a good idea.

This issue keeps track of the items that we need to deal with later, but it doesn't mean that we *have* to add it to CRI :)

**Comment by Random-Liu** [comment]
Found a small thing we need to pay attention for docker implementation. Offline discussed with @yujuhong.

Currently, all labels and annotations we write to the container at the runtime interface level are compatible with what we have today.
However, currently in docker shim there is no good way to distinguish annotations and labels unless we add some special prefix or suffix. No matter what we add, it will break backward compatibility.
At that time, we still have to handle backward compatibility. Maybe for old containers, get a hacky set of labels from runtime interface and check whether current label is in the label set or not.

Track the issue here just make sure we don't forget it. :)

**Comment by feiskyer** [comment]
@Random-Liu How about still storing annotations into labels, but with another label identifying what keys should be in annotations for new runtime API?

**Comment by Random-Liu** [comment]
@feiskyer Good idea! But even though, for old containers which don't have the identifying label, we still don't know which is label, which is annotation. :)

**Comment by yujuhong** [comment]
Closing this in favor of the new issue: #31459
