### ISSUE TITLE
Forgot to set KUBE_ENABLE_INSECURE_REGISTRY before running kube-up.sh, is it too late?

### ISSUE THREAD

**Issue by olalonde** [kubernetes/kubernetes#29257]
I forgot to set `export KUBE_ENABLE_INSECURE_REGISTRY=true` when running `kube-up.sh` (AWS provider). I was wondering if there was anyway to do whatever that does manually (3 node cluster) or if the only option is to tear down the cluster and start from scratch.

**Comment by apelisse** [comment]
Please re-post your question to [stackoverflow]
(http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support
are posted so that we can improve our efficiency in responding to your requests,
and to make it easier for you to find answers to frequently asked questions and
how to address common use cases.

We regularly see messages posted in multiple forums, with the full response
thread only in one place or, worse, spread across multiple forums. Also, the
large volume of support issues on github is making it difficult for us to use
issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to
ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to
similar questions, and also familiarize yourself with:

  * [user guide](http://kubernetes.io/docs/user-guide/)
  * [troubleshooting guide](http://kubernetes.io/docs/admin/cluster-troubleshooting/)

Again, thanks for using Kubernetes.

The Kubernetes Team

**Comment by olalonde** [comment]
Oops, sorry. http://stackoverflow.com/questions/38487736/how-to-set-i-forgot-to-set-kube-enable-insecure-registry-true-on-a-running-kuber

**Comment by apelisse** [comment]
Thank you!
