### ISSUE TITLE
image pull from private registry is broken

### ISSUE THREAD

**Issue by fvigotti** [kubernetes/kubernetes#29303]
with kubernetes 1.3.0

Docker version 1.10.3, build 20f81dd
ubuntu 16.04 lts
registry v2 ( with auth and tls, not certified ) on a public domain accessed though a public ip
I've spent two days trying to pull image from my private registry , the only solution that worked is this : [https://github.com/coreos/coreos-kubernetes/issues/498](https://github.com/coreos/coreos-kubernetes/issues/498) ( which is now closed, but in my opinion is a bug that should be opened to be fixed by someone more expert than me.. :) )

docs says that kubelet would use the $HOME/.dockercfg or $HOME/.docker/config.json and specify how to use the secrets specific type "kubernetes.io/dockerconfigjson" also to use : " kubectl create secret docker-registry"
I've tried every format I've seen around ( with/without prepending "https" to the url , using a json format as
```json
{
"auths":
{
"quay.io": {
"auth": "xXxXxXxXxXx=",
"email": "username@example.com"
},
}
```
or
```json 
{
"quay.io": {
"auth": "xXxXxXxXxXx=",
"email": "username@example.com"
}
```
 removing newlines , 
) I've tried all possible permutations of those params, placing it in various secrets format or node , nothing worked, errors also was misleading ( image not found, "no basic auth credentials" ) and the "no basic auth credentials" error appear when 
THERE IS an imagePullSecrets in place, in the correct namespace, and also there is a /root/.docker/config.json and the kubelet run under root user, and even the node itself can pull image without problems ( restarted everything multiple times , nothing changed )

I've also tried with 
cp /root/.docker/config.json /var/lib/kubelet/.dockercfg ( and restart of the kubelet )

the only thing that worked is : 
echo '{ "https://$PRIVATEREGPUBLICDNS:5000": {"auth": "$AUTH","email": "$EMAIL"} }' > /var/lib/kubelet/.dockercfg
with kubelet restart

with or without "imagePullSecrets:" which never worked anyway , at least for me

shouldn't be such a pain doing a so much important thing ( I need a private registry ! ),
the strange thing is also that authentication from registry that are not private/custom seems to work ( I've also created an account in quay.io to test this and it worked )

**Comment by mikekap** [comment]
One thing I noticed when recently setting up a kube cluster on Ubuntu is that systemd strips environment variables when starting kubelet. To get /root/.docker to work I had to launch kubelet with $HOME set to /root.

**Comment by fvigotti** [comment]
cat >/etc/systemd/system/hello.service <<EOF
[Unit]
Description=MyApp

[Service]
TimeoutStartSec=5
Environment=HOME=/root
ExecStart=/bin/bash -c "/usr/bin/env > /tmp/env"

I've checked , @mikekap  You are right, 
in systemd under the 
`[Service]` for the kubelet service descriptor,
adding a line : `Environment=HOME=/root` (and obviously having the correct /root/.docker/config.json ) seems to fix the issue,

anyway  the bug for me still have to remain opened at least until those 2 points gets fixed : 
- documentation have correct information for the setup ( no software is production ready with such hidden pains hidden around )
- ImagePullSecrets really works , to me still doesn't in all my tests, now I have a "working solution" but is not the ideal, and is not the documented one,
    ( and ALL documented solutions do not works , at least in my environment setup , which I suppose is also quite popular ..)

I would like to hear from someone which has been successful running a private registry ( v2 )  with tls and auth using ImagePullSecrets with docker > 1.7   , ( now google is full of attempts to solve the ImagePullSecrets issue  with  different "solutions" ( various json file format, with/without https, with/without newlines, changing secrets type, .....   not official and not working :) )

**Comment by apelisse** [comment]
Please re-post your question to [stackoverflow]
(http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support
are posted so that we can improve our efficiency in responding to your requests,
and to make it easier for you to find answers to frequently asked questions and
how to address common use cases.

We regularly see messages posted in multiple forums, with the full response
thread only in one place or, worse, spread across multiple forums. Also, the
large volume of support issues on github is making it difficult for us to use
issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to
ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to
similar questions, and also familiarize yourself with:

  * [user guide](http://kubernetes.io/docs/user-guide/)
  * [troubleshooting guide](http://kubernetes.io/docs/admin/cluster-troubleshooting/)

Again, thanks for using Kubernetes.

The Kubernetes Team
