### ISSUE TITLE
Expose metrics for desired replica counts

### ISSUE THREAD

**Issue by therc** [kubernetes/kubernetes#29323]
There's currently no way for Prometheus to learn the expected number of replicas for a replication controller, a replica set or a deployment. It has some Kubernetes logic to discover pods, nodes, etc., but apparently, if it doesn't return a target to monitor, it doesn't belong in their current service discovery code.

This would be equivalent to BNS' Shardinfo data.

Maybe covered by these issues, maybe not:

https://github.com/kubernetes/kubernetes/issues/1625
https://github.com/kubernetes/kubernetes/issues/28156

**Comment by onbjerg** [comment]
Can't this be pulled from the k8s API under ``.spec.replicas``?

**Comment by therc** [comment]
@onbjerg who's going to pull the data? Prometheus folks said that this is not going to implemented in the service discovery code on their side. So, if the API server won't export those variables, either, then you'd need to run some kind of agent that is neither in Prometheus, nor in the Kubernetes control plane and bridges the two.That's an additional component to deploy/manage and yet another point of failure to keep in mind.

**Comment by onbjerg** [comment]
I'm not sure I understand. The desired replica count is exposed in the API.

**Comment by therc** [comment]
Prometheus doesn't use the Kubernetes API to collect metrics, it only uses it to discover target groups (HOST:PORT lists) for services, machines, pods, endpoints and API servers, so that later you can write rules to scrape data FROM those.

Information (metrics) like the expected number of replicas in a Deployment is NOT imported. And Prometheus only scrapes data in two different formats:

https://prometheus.io/docs/instrumenting/exposition_formats/

So Prometheus as it is can't and won't get the desired replica count. The other two options are for the API server to return metrics about deployments or to write something that gets information from the API and exposes it in one of the two Prometheus formats.

**Comment by onbjerg** [comment]
Oh. I understand now. Thank you for elaborating!

**Comment by fabxc** [comment]
Yes, these things should be instrumented directly with the chosen exposition format 👍 

Everything meaningful to monitor should be exposed on the `/metrics` endpoint. Requiring every monitoring system to manually integrate with every custom API of every application is not a scalable approach.
Ultimately, not all application metrics worth monitoring are exposed via the application's API. Hence the `/metrics` endpoint should be the source of truth for all information worth monitoring.

We would like to build out the metrics described here and more directly in the respective Kubernetes.
It would be valuable to get some feedback on whether anybody would be against this and why before getting started.

@vishh @mwielgus I know you are to some degree involved with metrics/monitoring

**Comment by therc** [comment]
The main argument against this is that it might get expensive. The more stuff gets exposed, the higher the chances that the average scraping client doesn't care about a large chunk of it. So perhaps additional endpoints (e.g. /orchestration for replica counts, etc., plus /all to include REALLY everything) might be an option.

A second argument might be the potential security or leakage issues.

Last, and probably, least, the Prometheus format is kinda arbitrary, but given that it's already exposed elsewhere in Kubernetes and they're both CNCF projects, it makes some sense. And, since we're at it, I'll just add that it's unfortunate that Prometheus and expvar are not compatible. :-(

**Comment by fabxc** [comment]
Thanks for the input. To be clear, I'm a Prometheus maintainer and hence biased. But I really care about having the best possible solution here regardless of which monitoring system is being used.

We also thought about providing different metric endpoints. I don't believe it's best practice in general but could see people wanting/needing that.
Security concerns should probably be addressed along these endpoints. We don't want to do authz on every single metric.
Actually, prometheus/client_golang#214 will finally allow for multiple registries, so the timing is good :)

 One should never have to sacrifice insight for performance concerns. That's why the metric library was designed to be very efficient and optimized even to get rid of single allocations.
Even with high concurrency and intense contention on modifying a metric, we are performing fairly well. @beorn7, author of the library, did a talk on it: https://github.com/gophercon/2015-talks/blob/master/Bj%C3%B6rn%20Rabenstein%20-%20Prometheus/slides.pdf
Lastly, one can always just retrieve values at collection time (think ever 30s or longer), which is then merely a much cheaper version of querying the API for that information.

Could you elaborate on the arbitrariness? It's a very simple yet expressive format that models the use case very well and was picked for exactly that reason. It is also widely used across other projects and understood by a wide range of monitoring systems.
The alternative would be to establish a custom Kubernetes format, I suppose?

**Comment by therc** [comment]
@fabxc I was just picturing possible objections from others. At my previous job, my team had the largest monitoring system in the company and, in the name of insight, it used more resources on its own than most companies out there use to run entire businesses. :-)

I meant arbitrary in the sense that Kubernetes would be dictating a specific format, but, as you say, it works pretty well, being a refinement of the venerable varz (minus the filtering), and is also understood by others.

**Comment by brian-brazil** [comment]
This seems like something that https://github.com/kubernetes/kube-state-metrics should cover.

**Comment by kargakis** [comment]
@kubernetes/sig-apps-feature-requests
