### ISSUE TITLE
Federation: Write e2e tests for Federated Namespaces

### ISSUE THREAD

**Issue by quinton-hoole** [kubernetes/kubernetes#29336]

**Comment by quinton-hoole** [comment]
We still need to extend the existing e2e tests to check that the namespaces are correctly CRUD in the underlying clusters.

**Comment by nikhiljindal** [comment]
@mwielgus did that.

I think he is planning to add another test to verify that all resources in the namespace are deleted when the namespace is deleted.
Assigning to him to close this appropriately

**Comment by pwittrock** [comment]
@quinton-hoole @nikhiljindal @mwielgus 

I am moving this out of the blocking issues we are tracking for the 1.4 release because the unfinished pieces are non-blockers for the release and do not need to be tracked in the burndown meetings.  If there are components besides docs & tests that need to be completed, please move it back to the 1.4 milestone and provide daily status updates.

**Comment by mwielgus** [comment]
The tests are there.
