### ISSUE TITLE
Federation: Write e2e tests for Federated ReplicaSets

### ISSUE THREAD

**Issue by quinton-hoole** [kubernetes/kubernetes#29339]

**Comment by quinton-hoole** [comment]
@mwielgus Where do we stand on this one?  As far as I can see we have e2e tests for API-level CRUD of FederatedReplicasets, but the tests do not confirm that the underlying replicasets get created correctly, or that the number of replicas in each cluster makes sense.  We should also run the non-federated e2e tests against the federation (as far as is possible) to help to ensure API compatibility.

**Comment by pwittrock** [comment]
@quinton-hoole @mwielgus 

I am moving this out of the blocking issues we are tracking for the 1.4 release because the unfinished pieces are non-blockers for the release and do not need to be tracked in the burndown meetings.  If there are components besides docs & tests that need to be completed, please move it back to the 1.4 milestone and provide daily status updates.

**Comment by quinton-hoole** [comment]
This is fixed. Will cross-reference the PR tomorrow.
