### ISSUE TITLE
Federation: write e2e tests for Federated Secrets

### ISSUE THREAD

**Issue by quinton-hoole** [kubernetes/kubernetes#29337]

**Comment by quinton-hoole** [comment]
Same comment as https://github.com/kubernetes/kubernetes/issues/29339#issuecomment-243165769 applies.  Need e2e test to confirm that underlying secrets are always created correctly in underlying clusters.

**Comment by nikhiljindal** [comment]
@kshafiee can you update us on the progress of this task as per our discussion in the last meeting?

**Comment by pwittrock** [comment]
@quinton-hoole @nikhiljindal 

I am moving this out of the blocking issues we are tracking for the 1.4 release because the unfinished pieces are non-blockers for the release and do not need to be tracked in the burndown meetings.  If there are components besides docs & tests that need to be completed, please move it back to the 1.4 milestone and provide daily status updates.

**Comment by nikhiljindal** [comment]
Fixed by https://github.com/kubernetes/kubernetes/pull/31655
