### ISSUE TITLE
Setup Kubernetes cluster on Mesos on Docker failed

### ISSUE THREAD

**Issue by jianzhangbjz** [kubernetes/kubernetes#29360]
Hi guys,

I try to setup a **k8s cluster on Mesos on Docker** on Ubuntu according to the reference [Kubernetes on Mesos on Docker](http://kubernetes.io/docs/getting-started-guides/mesos-docker/#build-locally), but when I exec `./cluster/kube-up.sh` command with sudo privileges, it pop error, details as below:
```
Scaling mesos/docker cluster to 2 slaves
Starting docker_mesosslave_1 ... done
Starting docker_mesosslave_2 ... done
docker: Error response from daemon: Cannot link to a non running container: /docker_apiserver_1 AS /cocky_noyce/apiserver.
                                                                                                                          Dumping logs to '/root/tmp/kubernetes/log'
```
the docker_mesosslave_2.log as below:
```
+ DOCKER_NETWORK_OFFSET=0.0.2.0
+ exec wrapdocker mesos-slave --work_dir=/var/tmp/mesos/2 '--attributes=rack:2;gen:2012' --hostname=172.17.0.8 '--resources=cpus:4;mem:1280;disk:25600;ports:[8000-21099];cpus(public):2;mem(public):640;ports(public):[7000-7999]'
ln: failed to create symbolic link '/sys/fs/cgroup/systemd/name=systemd': Operation not permitted
No supported filesystem found (aufs, overlay)
```
the docker_apiserver_1.log as below:
```
F0721 06:10:11.658470      49 server.go:144] error in initializing storage factory: group version experimental/v1alpha1 that has not been registered
```
Have someone encounter this error?

**Comment by apelisse** [comment]
Please re-post your question to [stackoverflow]
(http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support
are posted so that we can improve our efficiency in responding to your requests,
and to make it easier for you to find answers to frequently asked questions and
how to address common use cases.

We regularly see messages posted in multiple forums, with the full response
thread only in one place or, worse, spread across multiple forums. Also, the
large volume of support issues on github is making it difficult for us to use
issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to
ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to
similar questions, and also familiarize yourself with:

  * [user guide](http://kubernetes.io/docs/user-guide/)
  * [troubleshooting guide](http://kubernetes.io/docs/admin/cluster-troubleshooting/)

Again, thanks for using Kubernetes.

The Kubernetes Team

**Comment by jianzhangbjz** [comment]
@apelisse Thanks your kindly reply.
