### ISSUE TITLE
kubectl create limit: need for specification of usage

### ISSUE THREAD

**Issue by hodovska** [kubernetes/kubernetes#29433]
How should the usage of new subcommand `kubectl create limit` look like?

kubectl create sub-command will be created to provide simpler way of how to create LimitRanges for pods and containers. For now it is possible by object definiton in file and passing to kubectl create.

One named limitRange object consists of multiple values which are specified by:
    - type - pod or container, 
    - resource - memory or cpu,
    - limit specification - max, min, default, defaultRequest, maxLimitRequestRatio

For more information read: http://kubernetes.io/docs/admin/limitrange/

One limit value in LimitRange object must be specified with all of the three keys. In new sub-command we should retain the possibility to have more limits specified in one LimitRange object and ability to have limitRange object created with any non-empty set of combination of keys menioned above (e.g. max number of cpus for pods =2 and minimum memory for container = 3Mi in one LimitRange object).

**Comment by hodovska** [comment]
Suggestion of how the sub-command could be used:

```
kubectl create limit example --set=pod.cpu.max=3, pod.cpu.default=2, container.memory.min=200M
```

**Comment by derekwaynecarr** [comment]
Due to history of `LimitRange` existing before requests/limits were clearly defined, I would like the command to reflect where we want `LimitRange` to go so it will continue to function even when we have a v2 concept for that resource.  That could mean using slightly different flag names than the API fields (which muddle default and defaultRequest).

**Comment by ncdc** [comment]
cc @kubernetes/kubectl @kubernetes/rh-ux

**Comment by pwittrock** [comment]
subscribe @pwittrock

**Comment by derekwaynecarr** [comment]
I am putting together a doc describing some updates I would like to do to `LimitRange` to simplify the API.

In practice, I would prefer we settle on a pattern like the following:

```
kubectl create limitrange mylimit --type=Pod \
 --min=requests.cpu=10m,limits.cpu=100m \
 --max=requests.cpu=100m,limits.cpu=1 \
 --default=requests.cpu=50m,limits.cpu=500m
```

I think I would like to deprecate the current `default` and `defaultRequests` split and move closer to the model of supporting requests.* and limits.* fields separately like we now do in quota.  In addition. for the limitToRequestRatio support, I would prefer we just have a resource name for that concept rather than a dedicated field.

I think the CLI experience is simpler once we settle the API as described above.
