### ISSUE TITLE
kubelet only choose the first api-server given， caused all services unavailable.

### ISSUE THREAD

**Issue by anzhsoft** [kubernetes/kubernetes#29434]
one of The kubelet's start parameter is 
-api-servers=[]: List of Kubernetes API servers for publishing events, and reading pods and services. (ip:port), comma separated.

It appears that it's designed for api-server's HA, only if one of the api server is alive, that everything will work well.

But I found that the kubelet would only choose the first api server, even if I gave it 3 api -servers. If the first api-server was stopped, all the services were unavailable.

The version I used is:
Kubernetes v1.2.1

So are there any ways to avoid this issue, Hopefully I just use it in a wrong way. Or I may fix it in the kubelet..

Any comments are appreciated.

**Comment by apelisse** [comment]
Please re-post your question to [stackoverflow]
(http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support
are posted so that we can improve our efficiency in responding to your requests,
and to make it easier for you to find answers to frequently asked questions and
how to address common use cases.

We regularly see messages posted in multiple forums, with the full response
thread only in one place or, worse, spread across multiple forums. Also, the
large volume of support issues on github is making it difficult for us to use
issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to
ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to
similar questions, and also familiarize yourself with:

  * [user guide](http://kubernetes.io/docs/user-guide/)
  * [troubleshooting guide](http://kubernetes.io/docs/admin/cluster-troubleshooting/)

Again, thanks for using Kubernetes.

The Kubernetes Team

**Comment by roffe** [comment]
This needs to be repopened as it's still a issue in 1.7.2 and the stackoverflow is unanswered
