### ISSUE TITLE
how kube-apiserver worked on binding 443 port using non-root?

### ISSUE THREAD

**Issue by DavadDi** [kubernetes/kubernetes#29450]
I noticed that installed kube-apiserver prog can start  on port 443 (<1024) using non-root user 'kube'. 

But I can't find any clue how kube-apiserver prog works. Any help? I have the problem of binding port 443 when upgrade kube-apiserver by cp.

Also I know linux capabilities (CAP_NET_BIND_SERVICE Bind a socket to Internet domain privileged ports (port numbers less than 1024).) such as: 
> setcap 'cap_net_bind_service=+ep' /path/to/program.

But I find nothing searching keyword  "setcap" from  the whole project.

**Comment by apelisse** [comment]
Please re-post your question to [stackoverflow]
(http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support
are posted so that we can improve our efficiency in responding to your requests,
and to make it easier for you to find answers to frequently asked questions and
how to address common use cases.

We regularly see messages posted in multiple forums, with the full response
thread only in one place or, worse, spread across multiple forums. Also, the
large volume of support issues on github is making it difficult for us to use
issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to
ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to
similar questions, and also familiarize yourself with:

  * [user guide](http://kubernetes.io/docs/user-guide/)
  * [troubleshooting guide](http://kubernetes.io/docs/admin/cluster-troubleshooting/)

Again, thanks for using Kubernetes.

The Kubernetes Team

**Comment by bronger** [comment]
It's here: http://stackoverflow.com/questions/38536900/how-kube-apiserver-worked-on-binding-443-port-using-non-root
