### ISSUE TITLE
code in spec/containers never updated (e.g. guestbook/index.html)

### ISSUE THREAD

**Issue by yahavb** [kubernetes/kubernetes#29496]
I am trying to modify the application code shared in guestbook example. 
For example I changed the index.html (minor text change) and tried to recreate the frontend controller as the code declares in the fronted-controller.yaml under containers(php-redis).
Bit no matter what Im doing, the original guestbook index.html always used. 
I guess its comes with the image: gcr.io/google_samples/gb-frontend:v4.

1. is it?
2. if its, when is the value of the name under containers
spec:
      containers:
      - name: green-cdn
        image: gcr.io/google_samples/gb-frontend:v4
     ...

What am I missing?

Thanks!

**Comment by yahavb** [comment]
Alos, I logged in to three frontend instance and saw that the index.html deployed under /var/www/html is the original one and NOT the one the controller spec specified.

**Comment by apelisse** [comment]
Please re-post your question to [stackoverflow]
(http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support
are posted so that we can improve our efficiency in responding to your requests,
and to make it easier for you to find answers to frequently asked questions and
how to address common use cases.

We regularly see messages posted in multiple forums, with the full response
thread only in one place or, worse, spread across multiple forums. Also, the
large volume of support issues on github is making it difficult for us to use
issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to
ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to
similar questions, and also familiarize yourself with:

  * [user guide](http://kubernetes.io/docs/user-guide/)
  * [troubleshooting guide](http://kubernetes.io/docs/admin/cluster-troubleshooting/)

Again, thanks for using Kubernetes.

The Kubernetes Team

**Comment by yahavb** [comment]
NP sorry about it. I realized the image needs to be recreated for every change before executing the yaml.
On Jul 25, 2016, at 8:49 AM, Antoine Pelisse <notifications@github.com<mailto:notifications@github.com>> wrote:


Please re-post your question to stackoverflow<http://stackoverflow.com/questions/tagged/kubernetes>.

We are trying to consolidate the channels to which questions for help/support
are posted so that we can improve our efficiency in responding to your requests,
and to make it easier for you to find answers to frequently asked questions and
how to address common use cases.

We regularly see messages posted in multiple forums, with the full response
thread only in one place or, worse, spread across multiple forums. Also, the
large volume of support issues on github is making it difficult for us to use
issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to
ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to
similar questions, and also familiarize yourself with:

  *   user guide<http://kubernetes.io/docs/user-guide/>
  *   troubleshooting guide<http://kubernetes.io/docs/admin/cluster-troubleshooting/>

Again, thanks for using Kubernetes.

The Kubernetes Team
