### ISSUE TITLE
restart cassandra pod will not come up

### ISSUE THREAD

**Issue by zhjchen** [kubernetes/kubernetes#29501]
Using the example Cassandra yaml to start Cassandra ( Cassandra 2.2.7) cluster.
In my test, each Cassandra runs as kubernetes deployment. Two Cassandra pods are running. Each pod has only one container. 

To simulate Cassandra restart, I kill the Cassandra java process in container, pod will start one new container. However the new container will not come up since Cassandra will the following exception:

> INFO  [GossipStage:1] 2016-07-23 18:16:01,656 TokenMetadata.java:414 - Updating topology for /10.168.254.239
> INFO  [GossipStage:1] 2016-07-23 18:16:01,657 TokenMetadata.java:414 - Updating topology for /10.168.254.239
> DEBUG [GossipStage:1] 2016-07-23 18:16:01,658 MigrationManager.java:96 - Not pulling schema because versions match or shouldPullSchemaFrom returned false
> DEBUG [PendingRangeCalculator:1] 2016-07-23 18:16:01,661 PendingRangeCalculatorService.java:64 - finished calculation for 0 keyspaces in 0ms
> DEBUG [MigrationStage:1] 2016-07-23 18:16:01,668 MigrationManager.java:493 - Gossiping my schema version b145475a-02dc-370c-8af7-a9aba2d61362
> ERROR [main] 2016-07-23 18:16:01,672 CassandraDaemon.java:644 - Exception encountered during startup
> java.lang.NullPointerException: null
>         at org.apache.cassandra.service.StorageService.maybeAddOrUpdateKeyspace(StorageService.java:992) ~[apache-cassandra-2.2.7.jar:2.2.7]
>         at org.apache.cassandra.service.StorageService.joinTokenRing(StorageService.java:878) ~[apache-cassandra-2.2.7.jar:2.2.7]
>         at org.apache.cassandra.service.StorageService.initServer(StorageService.java:629) ~[apache-cassandra-2.2.7.jar:2.2.7]
>         at org.apache.cassandra.service.StorageService.initServer(StorageService.java:500) ~[apache-cassandra-2.2.7.jar:2.2.7]
>         at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:306) [apache-cassandra-2.2.7.jar:2.2.7]
>         at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:522) [apache-cassandra-2.2.7.jar:2.2.7]
>         at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:631) [apache-cassandra-2.2.7.jar:2.2.7]
> INFO  [StorageServiceShutdownHook] 2016-07-23 18:16:01,674 Gossiper.java:1448 - Announcing shutdown

If delete the deployment, then create it again, the new pod will not come up either since Cassandra will gives the same exception as above.

**Comment by apelisse** [comment]
Please re-post your question to [stackoverflow]
(http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support
are posted so that we can improve our efficiency in responding to your requests,
and to make it easier for you to find answers to frequently asked questions and
how to address common use cases.

We regularly see messages posted in multiple forums, with the full response
thread only in one place or, worse, spread across multiple forums. Also, the
large volume of support issues on github is making it difficult for us to use
issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to
ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to
similar questions, and also familiarize yourself with:

  * [user guide](http://kubernetes.io/docs/user-guide/)
  * [troubleshooting guide](http://kubernetes.io/docs/admin/cluster-troubleshooting/)

Again, thanks for using Kubernetes.

The Kubernetes Team
