### ISSUE TITLE
Kube-up and kube-down with exsisting VPC

### ISSUE THREAD

**Issue by olalonde** [kubernetes/kubernetes#29587]
I couldn't find information on this in the docs. Is it possible to use `./cluster/kube-up.sh` and `./cluster/kube-down.sh` with an existing AWS VPC (e.g. the default VPC)?

**Comment by gellis01** [comment]
It is possible, but unless your VPC is set up the right way, the deployment might fail. You can set the `VPC_ID` parameter, [see here for more info](https://github.com/kubernetes/kubernetes/blob/release-1.3/docs/design/aws_under_the_hood.md). 

There is also an [open pull request](https://github.com/kubernetes/kubernetes/pull/28499) to further parameterise this.  

However, I would **NOT** yet recommend using `kube-down` to delete the cluster if you do this. Currently `kube-down` attempts to delete the VPC the cluster is running in, as well as some of the other resources within it. Most of these are created by `kube-up` but I've realised that it will also delete an internet gateway if you have one attached to the VPC, so be very careful with this.

**Comment by justinsb** [comment]
You can run kube-up into an existing VPC, per @gellis01 's comment above.  If you do that, kube-down will not delete anything, because the VPC is not tagged, and in 1.3 it will warn you that it is not doing anything.

However, in general for these advanced use cases I'm starting to steer people on AWS towards kops - it's still early, but if you're pushing the limits of kube-up like this I think you will be happier with [kops](https://github.com/kubernetes/kops)

Closing for now, as I think this is opened.  Please reopen if needed.
