### ISSUE TITLE
Increase TTL of DNS resource records of pod lookups

### ISSUE THREAD

**Issue by grobie** [kubernetes/kubernetes#29642]
The new kube-dns implementation does not longer do any kind of validation for pod resource lookups  (e.g. `8-8-8-8.whatever.pod.local.`). Neither the existence of the IP nor namespace is validated and the record will simply contain the parsed IP address.

Given the returned result will never change, the usage of the default TTL of 30s causes an unnecessary amount of DNS queries in our network. Using a much higher TTL will utilize our caches much better.

Are there any objections to increase the TTL of resource records for pod name queries? I'm happy to contribute a PR.

@madhusudancs @ArtfulCoder

**Comment by vincentheet** [comment]
We have actually seen performance issues due to the fact that the TTL is low and some of the app's in our pods where waiting for DNS responses. To resolve this problem we scaled up kube-dns and the problem went away but 30 seconds is to low in my opinion. We heavily call internal service based on their dns names but a service ip will not change that often. Is there a way we can increase the TTL by default of have an option to configure it? I also see some reports of similar performance issues in https://github.com/kubernetes/kubernetes/issues/26707

**Comment by krmayankk** [comment]
is the ttl for kubedns records configurable  or is it a compile time change ?

**Comment by saurfangg** [comment]
Any chance of an answer on this? We're also running into this issue and would like to experiment with increasing the TTL from 30 seconds to a couple minutes.
