### ISSUE TITLE
How I can upgrade Kubernete's version on AWS?

### ISSUE THREAD

**Issue by yograterol** [kubernetes/kubernetes#29643]
Hi,

I looked for a way to upgrade Kubernete on AWS but I didn't find one.

**Comment by dchen1107** [comment]
cc/ @justinsb @zmerlynn

**Comment by justinsb** [comment]
If you used kube-up, kops is a tool that is still young but which a lot of people are using with good results, including to upgrade a cluster from 1.2 -> 1.3:  https://github.com/kubernetes/kops/blob/master/docs/upgrade_from_k8s_12.md

The best alternative is otherwise to bring up a second cluster and move your manifests across.  If you do that in the same zone you can bring your EBS volumes across.

**Comment by rcshubhadeep** [comment]
@justinsb I am trying the same exact thing and this is the error I am getting

```
Cluster Name must be a fully-qualified DNS name (e.g. --name=mycluster.myzone.com)

**Comment by RichardBronosky** [comment]
I have the same error as @rcshubhadeep. It seems like a documentation flaw.

**Comment by hernandanielg** [comment]
@justinsb so your recommendation is to spin up a second cluster and move manifests to the new one. Can you please tell what do you think are the risks, possible lost and/or downtime?

**Comment by castrojo** [comment]
I think this sort of discussion is best had on the list as things have a changed a bunch since this issue was opened. There's a SIG for AWS here where you can find other people on AWS that will be able to give you best-practice information: https://github.com/kubernetes/community/tree/master/sig-aws

Also check this out: https://github.com/kubernetes/kops/blob/master/docs/cluster_upgrades_and_migrations.md

Since this isn't a bug report I'm going to go ahead and close this, thanks!
