### ISSUE TITLE
Use dateTime type in swagger

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#2968]
Swagger supports a `date-time` type:
https://github.com/swagger-api/swagger-spec/blob/master/versions/1.2.md

Our time fields are currently represented as strings.

It looks like go-restful does recognize time.Time as `date-time` (https://github.com/emicklei/go-restful/blob/master/swagger/model_builder.go), but we're using a wrapper.

Haven't investigated the best way to fix this yet.

**Comment by nikhiljindal** [comment]
Fixing typeToJSON at https://github.com/kubernetes/kubernetes/blob/3111985564f4bfc769111c5708a01d9d711edf70/pkg/apiserver/api_installer.go#L945 should fix this.
Instead of converting unversioned.Time to string, we should convert it to time.Time and then go-restful will correctly handle time.Time.

**Comment by whitlockjc** [comment]
Would it make sense to leverage the `format` feature of Swagger/JSON Schema?  A real date time in Swagger should be `{"type": "string", "format": "date-time"}` and most JSON Schema validators and Swagger tools will use this.  I'm not sure a `type: string` paints the full picture.

**Comment by mbohlool** [comment]
I've looked into this. Problem is go-restful does not understand a custom marshaled unversioned.Time and set the type to string and does not set format property for it. 

https://github.com/emicklei/go-restful/blob/master/swagger/model_builder.go#L141

The type should be still string but the format should be "date-time". I can think of these fixes:

1. Add a Marshaling format tag to go-restful (e.g., an interface with getMarshalingFormat method). If a type (like unversioned.Time) is using its own marshaling, we can get the format tag and set it in json. Needs a change in go-restful.
2. Dynamically Create a new struct with time.Time instead of unversioned.Time as the example object for go-restful. This is not supported in go 1.6 and we need to wait for go 1.7.

3. add a "format" tag to all unversioned.time usage and support the tag in go-restful (here https://github.com/emicklei/go-restful/blob/master/swagger/model_property_ext.go). I would prefer 1 to this option, but supporting format tag in model_property_ext is not a bad idea anyway.

**Comment by nikhiljindal** [comment]
@whitlockjc Yes thats what we want to do here.

As @mbohlool said, we pass go-restful a custom `unversioned.Time` object right now and go-restful sets the type to string for that. If we pass `time.Time`, then go-restful will handle it correctly and set `{"type": "string", "format": "date-time"}`

**Comment by whitlockjc** [comment]
@nikhiljindal That makes sense, thanks for clarifying.
