### ISSUE TITLE
Document custom JSON types in swagger

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#2971]
Our API uses a number of custom types, such as `util.IntOrString`. We should check whether the fields using such types are documented accurately in the swagger output. `IntOrString` is simply documented as `string`, for example.

**Comment by brendandburns** [comment]
In general looks like it custom types are not supported.  We likely need some sort of tool to massage the output of go-restful (or upstream go-restful changes, but that seems harder)

**Comment by bgrant0607** [comment]
Seems worth trying to fix go-restful. Looks like maybe a case that fell through the cracks here:
https://github.com/emicklei/go-restful/blob/master/swagger/model_builder.go#L74

**Comment by bgrant0607** [comment]
Now all string types are represented as strings, I believe, and others are represented as "any"?

**Comment by brendandburns** [comment]
Kicking this into 1.0 bubble.

**Comment by nikhiljindal** [comment]
We are now representing all our custom types as `"type": "object"` in the spec.

**Comment by aljim** [comment]
intOrString should be represented as anyOf

**Comment by cjcullen** [comment]
Yeah, it looks like `intstr.IntOrString` is still broken
```
TargetPort intstr.IntOrString `json:"targetPort,omitempty" protobuf:"bytes,4,opt,name=targetPort"
```
produces

```
"targetPort": {
 "type": "string",
 "description": "Number or name of the port to access on the pods targeted by the service. Number must be in the range 1 to 65535. Name must be an IANA_SVC_NAME. If this is a string, it will be looked up as a named port in the target Pod's container ports. If this is not specified, the value of the 'port' field is used (an identity map). This field is ignored for services with clusterIP=None, and should be omitted or set equal to the 'port' field. More info: http://releases.k8s.io/HEAD/docs/user-guide/services.md#defining-a-service"
},
```

**Comment by cjcullen** [comment]
Not a regression. It has been this way for a long time.

**Comment by mbohlool** [comment]
is "anyOf" a swagger type? where is it documented?

**Comment by aljim** [comment]
Right it seems that anyOf is not supported on swagger,  OAI/OpenAPI-Specification#707
Another type of generation needs to be set in place, since accepting integers with schema string, is impossible in some generated libraries, and also for automated systems that validate requests.

one possibility is to create the schema

numberOrString:
  properties:
     numberValue:
       type: number
     stringValue:
       type: string

targetPort:
  type: object
  properties:
     $ref: definitions/numberOrString

**Comment by mbohlool** [comment]
But that would change the API itself, right? I mean now the target port need to be provided as an object instead of string or integer (instead of targetPort: 12, we would have targetPort: {numberValue: 12}). Type 'object' does not make sense by itself too (without any schema) as no validation can be done and also generated clients does not know what to do with an object with no schema. I suggest we keep it as string. This way we won't have validation for now (and we maybe be able to do something about that later by using swagger 2.0 custom tags) and generated clients (if any in future) just pass string that won't break anything.

**Comment by aljim** [comment]
Yes, is an API change that could allow this behavior, swagger 1.2 does not allow oneOf, neither swagger 2.0.

This are the options I see.

1. You could use a discriminator on the parent objects of things that contain IntOrString, but you need to define an extra property that defines this value.

targetPort: {
   numberValue:
   stringValue:
}

2. Change the API to have IntOrString represented as part of the schema.

3. Add another field called, targetPortNumber.

4. Leave the schema wrong, but here are the side effects.

Generated clients cannot set the integer value even if they wanted to, since clients libraries generally are either strongly typed, or check the schema of the input on the fly.
Also since the API is taking invalid strings that represent a number is impossible to set number values.
Automated systems that make requests to Kubernetes API also will fail to validate this value if integer since schema is wrong.

**Comment by mbohlool** [comment]
I would say the side effects are acceptable for now (changing APIs just to make this work does not make sense, specially if we need to do it in many places these fields defined). The best solution in my opinion is to define a format "int-or-string" (swagger 2.0 allows it) and mark these fields as type "string" and format "int-or-string". We can change client generators we know to understand "int-or-string" and for other clients, they fall back to accept only String.

**Comment by lavalamp** [comment]
I added this to the umbrella issue.

**Comment by lavalamp** [comment]
Changing the API to split out int and string values separately would be a bit of a big deal--it breaks every client ever--we should do it only as a last resort, and we could only do it on a version boundary. v1 objects can't ever make that change. :(

**Comment by bgrant0607** [comment]
We should engage with OpenAPI to get extensions we need.

**Comment by mbohlool** [comment]
IntOrString fields is now documented as 

```
"io.k8s.apimachinery.pkg.util.intstr.IntOrString": {
    "type": "string",
    "format": "int-or-string"
   },
```

While this is not ideal (and we maybe able to represent it better in OpenAPI 3.0), it serves the purpose of this issue.

p.s. We may (should?) add support for int-or-string in our generated clients. Right now python let you pass an actual value instead of an IntOrString type and that can be int or string. But we can certainly do better.
