### ISSUE TITLE
HPA - handle situation when current replica count doesn't match to the desired number

### ISSUE THREAD

**Issue by mwielgus** [kubernetes/kubernetes#29739]
Currently this is silently accepted.

cc: @jszczepkowski @piosz

**Comment by goltermann** [comment]
@mwielgus @jszczepkowski @piosz is this needed for 1.4?

**Comment by pwittrock** [comment]
@mwielgus @jszczepkowski @piosz

I am moving this out of the blocking issues we are tracking for the 1.4 release because the unfinished pieces are non-blockers for the release and do not need to be tracked in the burndown meetings.  If there are components besides docs & tests that need to be completed, please move it back to the 1.4 milestone and provide daily status updates.

**Comment by ccwillia** [comment]
Is there a work around for this issue?  I have 3 deployments now where the desired say 1 but the hpa has a minimum of 2.  I have tried removing only the deployments and recreating but that results in the same behavior

**Comment by piosz** [comment]
@MaciekPytel to triage
