### ISSUE TITLE
Kubelet use RunC instead of docker daemon

### ISSUE THREAD

**Issue by sparkthu** [kubernetes/kubernetes#29731]
Mesos 1.0.0 has already support use docker images without docker daemon. I think it is an attractive feature for kubelet.

**Comment by luxas** [comment]
cc @kubernetes/sig-node

**Comment by euank** [comment]
I believe this is a duplicate of https://github.com/kubernetes/kubernetes/pull/26788

This is also related to the features https://github.com/kubernetes/features/issues/54 (which will make it possible to swap in such a runtime) and https://github.com/kubernetes/features/issues/58 (a feature to run Kubernetes with rkt rather than Docker), as well as other bits of related discussion.

**Comment by yujuhong** [comment]
Yes, integrating with other container runtimes (runc being one example) is WIP already. Let's close this issue.

**Comment by shenshouer** [comment]
How to ?

**Comment by dims** [comment]
@shenshouer see https://github.com/kubernetes-incubator/cri-o
