### ISSUE TITLE
container logs should not live on root partition

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#29762]
Currently we store container logs in /var/lib/docker..., we should document and enforce where possible, that this doesn't live on the root partition. when root fills up all bets are off. 

In fact we can go even deeper and come up with a nice partitioning scheme that protect critical system files from corruption. I think @girishkalele had some ideas at one point.

**Comment by girishkalele** [comment]
Our current partitioning scheme for GCE worker nodes is a giant X GB Debian bootable disk, where root as well as all data directories exist in one single partition/volume.

In general, the partitioning scheme is outside the scope of the node/kubelet feature because for a lot of downstream integrations of Kubernetes, we don't control the process of creation of the worker nodes and/or their disks.

We can probably recommend best practices for Kubernetes worker node disk partitioning for these cases.
For GCE/AWS/GKE, the recipes to build the worker nodes need some changes - @zmerlynn and others had ideas to attach multiple cloud provider disks to the workers, one per purpose - for e.g. /var/lib/docker on one disk, /var/log on another and so on. This approach would also leverage the ability of GCE to resize disks on the fly if necessary, depending on which particular disk is getting full.

**Comment by bprashanth** [comment]
Hmm, why is this out of scope for the node? it's essentially just a permanent volume for the kubelet. nodes need boot disk, and they're going to store logs somewhere. we already format and mount volumes requested by users today, maybe we can just do something similar on bootup for /var/lib/docker/logs ?

**Comment by girishkalele** [comment]
I meant it would be hard for kubelet to dictate the partitioning scheme.

In some cases, like for GCE/AWS, we could mount cloud disks onto these directories. Maybe we change the MIG template to create multiple disks and the minion bootup provisioning script formats and mount them.

**Comment by vishh** [comment]
Disk resources are managed differently across distros. Have a look at https://github.com/kubernetes/kubernetes/issues/24677 and kubelet evictions. Evictions will prevent the root partition from being full in the first place. #24677 will help with restricting the log usage of individual containers.
