### ISSUE TITLE
AWS: Friendly ELB Names

### ISSUE THREAD

**Issue by ProTip** [kubernetes/kubernetes#29789]
`a44e18e4c552b11e683bb02fff13e176` is not a very friendly ELB name. The AWS console does not allow for searching/sorting by tags for every resource. We use something like this:

```
[environment]-[app]
staging-my-app
```

It would be nice if we could pick a template to use for naming. A combination of cluster name and pod name might work well.

**Comment by rata** [comment]
The whole env name might be too long, as the whole name should be <= 20 characters. By default, I use `[app]-[env-short-name]` and env-short-name is a terraform map that is "stag" for staging and prod for "production".

In any case, doing just that doesn't seem enough as we need to guarantee the ELB name is unique. So some randomness or something might be needed

**Comment by chrislovecnm** [comment]
What about prefixing it with something.  Pod, petset, etc.  GCE volumes are prefixed and are super easy to find because of the prefixing.

**Comment by rata** [comment]
On Fri, Jul 29, 2016 at 01:42:50PM -0700, Chris Love wrote:
> What about prefixing it with something.  Pod, petset, etc.  GCE volumes are prefixed and are super easy to find because of the prefixing.

Remember the max is 20 characters for an ELB name

**Comment by ProTip** [comment]
ELB names can be up to 32 characters long:

* [Docs](http://docs.aws.amazon.com/ElasticLoadBalancing/latest/APIReference/API_CreateLoadBalancer.html)
* The 32 char name I posted that was generate by kubernetes

**Comment by hjacobs** [comment]
:+1: we are also interested in this feature :smile: We are currently implementing our own adapter with custom annotation to automatically assign Route 53 DNS records (Alias) for the ELB.

**Comment by justinsb** [comment]
We have yet to come up with a strategy that doesn't have a high chance of collisions, given ELB naming limitations and also the potential for hostile tenants.  We do tag the ELB though with the name of the service though, in the tag kubernetes.io/service-name.

**Comment by lpabon** [comment]
@ProTip @justinsb Would something like this be possible using the following template:

```
k8s-{namespace:8}-{name:8}-{uuid} 
```

Here is an example of an ELB:

```
k8s-default-myservic-307abb8b71a
```

**Comment by akhmadfld** [comment]
Is this issue fixed?

I tried in kubernetes 1.8.4 with these additional annotation from existing ELB:
- service.beta.kubernetes.io/aws-load-balancer-name: "some-name"
- kubernetes.io/aws-load-balancer-name: "some-name"
- kubernetes.io/loadbalancer-name: "some-name"

and nothing changed

**Comment by Constantin07** [comment]
+1 Prefixing ELB name with some meaningful name, aka env, app stack, etc. would be much helpful!

**Comment by darrenhaken** [comment]
Still no fix for this? The names are a mess right now

**Comment by KIVagant** [comment]
Why just don't add something like `service.beta.kubernetes.io/aws-load-balancer-name` [to annotations](https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/aws/aws.go#L99) and allow users to manage this?

**Comment by greg-jaunt** [comment]
Thumbs up to that, although is there any scenario in which Kubernetes needs to recreate the ELB in order to apply a change to a service?  If so, this would then force a delete-before-create scenario whereas before the replacement ELB could be brought up independent of deleting the existing to-be-replaced ELB.

**Comment by BobbyJohansen** [comment]
I think this is a must have when it comes to managing the cluster. It is quite annoying to have to dig through random string ELBs when attempting to find the one you are looking for. Especially if you have multiple coming from kubernetes.

**Comment by corby** [comment]
For large corporations where there is a Tier 1 devops support team, they need to be able to look at an ELB, EC2 instance, AutoScaling group, etc. and, at a glance, be able to tell what the component belongs to.
Currently kubernetes assumes that all human interaction will be done through some kube interface, but if the DevOps/Ops team doesn't have access to this, they are hard pressed to figure out what some UUID named components belong to and who to call.
Please keep in mind that the components kubernetes created (including ec2 key pairs) need to be cataloged by a human and tracked just like any old data center.

**Comment by nneul** [comment]
To be fair, the information IS present in the tags, it's just incredibly tedious to find stuff since AWS doesn't expose the ability to see tag columns on the ELB listing like they do for ec2 instances. (Why?!?)

**Comment by justinsb** [comment]
We've had some attempts at solving this before, but the problems are around:

* Collisions if users can specify names (though this can be fixed)
* What happens when e.g. an annotation is changed, or what happens to existing ELBs if we change the prefix

As @nneul pointed out, we do add tags so the information is visible, though the AWS console doesn't surface them as nicely as it could.

I'd welcome any attempt at fixing this, but it is non-trivial.

**Comment by gtaylor** [comment]
Though, as mentioned, the presentation on AWS's part leaves something to be desired (by default), I think the tags satisfy our needs for cataloging what ELB comes from which cluster. The names _could_ be somewhat more friendly, but is it fair to consider this mostly cosmetic (due to the tags)? Or is there something else we could add to the tags to satisfy the other concerns here?

**Comment by BobbyJohansen** [comment]
Would something like k8s-{servicename}-{uuid} not suffice within the given elb character limit?

**Comment by greg-jaunt** [comment]
@nneul :  Pro Tip for finding your service's ELB in AWS.

In the search box on the Load Balancers page in the EC2 console type "tag:k", then select "kubernetes.io/service-name" from the dropdown, then select your service name from the list.

**Comment by nneul** [comment]
@BobbyJohansen I believe the ELB name is limited to 32 characters... While certainly you could chop off the uuid, that raises issues about either potential collisions and needing to handle those additional failure modes. Does seem like it would be useful as an option though if set on an annotation for the loadbalancer.

**Comment by nneul** [comment]
There was a suggestion from @lpabon above that suggested something similar.

**Comment by nneul** [comment]
ELBs don't use the 'Name' tag since the name can only be set once during provisioning and can't be changed. That is unlike EC2 instances and other resources where the 'Name' is just an abitrary label.

**Comment by andrewsykim** [comment]
Same problem with other cloud providers 

/area cloudprovider
/sig cloud-provider

**Comment by andrewsykim** [comment]
Update on this issue (applies to all cloud provider LBs, not just ELB): we've merged in https://github.com/kubernetes/kubernetes/pull/66589 which gives us a mechanism to customize the LB names per provider, previously this was done by 1 global method. In upcoming releases, we want to start pushing changes to actually give LBs more meaningful names (based on what works best for that provider). The biggest challenge so far is how to handle existing LBs (should they be dynamically renamed? not touched at all? replaced?).

**Comment by yves-vogl** [comment]
I'm currently doing some workarounds ```kubectl get svc/chartmuseum -ojson | jq '.status.loadBalancer.ingress[0].hostname'``` and would like to have a better solution.

**Comment by yves-vogl** [comment]
Maybe this could be useful for you guys. Currently this is for single resources only.

```yaml

data "kubernetes_service" "chartmuseum" {
  metadata {
    name = "chartmuseum"
  }
}

# Load Balancer name cannot be specified from Kubernetes and AWS API does not allow
# filtering Load Balancer resources by tags
# https://github.com/kubernetes/kubernetes/issues/29789
#
# kubectl get svc/chartmuseum-chartmuseum -ojson | jq -r '.status.loadBalancer.ingress[0].hostname' | awk -F "-" '{ print $1}'
#

data "aws_lb" "chartmuseum" {
  name = "${element(split(data.kubernetes_service.chartmuseum.load_balancer_ingress.*.hostname[0], "-"), 0)}"
}

```

**Comment by chris-brace** [comment]
There needs to be a way to specify ELB/ALB/NLB names because AWS (of course) violates its standard here and doesn't respect the `Name` tag. So, right now, in order to manage a stack in Terraform where you installed nginx-ingress, then automatically create a route 53 record, you have to do the following:

```hcl
data "kubernetes_service" "nginx_ingress" {
  metadata {
    name      = "nginx-ingress-singleton-controller"
    namespace = "nginx-ingress"
  }
}

data "aws_elb" "nginx-ingress" {
  // This seems fragile as hell 
  name = "${element(split("-", element(split(".", data.kubernetes_service.nginx_ingress.load_balancer_ingress.0.hostname), 0)), 0)}"
}
```

All someone needs to do is expose this as an annotation: 30 x [a-z, A-Z, 0-9,-] and set it as the name to avoid having to have access to kubernetes in order to manage aws resources.

**Comment by joaquinclearmetal** [comment]
Is it possible represent ELB `dns_name` through AWS annotations?

**Comment by stephen-dahl** [comment]
I am looking for an annotation to set the loadbalancers name. something like `service.beta.kubernetes.io/aws-load-balancer-name=my-loadbalancer`
In aws's ui you can give it a name and aws will prefix the loadbalancer address with it

**Comment by costimuraru** [comment]
We're trying to auto scale our pods running in Kubernetes, based on an external (ELB) metric coming from Cloudwatch via HorizontalPodAutoscaling [1].

For that, we need to create an `ExternalMetric` resource and provide the ELB name. However, because the ELB is created automatically through Kubernetes, we have no way of determining the ELB name (see below). Having a way to provide the ELB name through an annotation on the Service 
 resource, would solve this issue (eg. `service.beta.kubernetes.io/aws-load-balancer-name=my-loadbalancer`).

```yaml
kind: ExternalMetric
metadata:
  name: konductor-elb-requests
  namespace: konductor-perf-kond
spec:
  name: konductor-elb-requests
  resource:
    resource: "deployment"
  queries:
    - id: konductor_elb_requests
      metricStat:
        metric:
          namespace: "AWS/ELB"
          metricName: "RequestCount"
          dimensions:
            - name: LoadBalancerName
              value: "a1344c95641ec11ea8eba0a7eb9f2c4c"       <------ THIS is manually added
        period: 300
        stat: Sum
        unit: Count
      returnData: true
```

[1] https://aws.amazon.com/blogs/compute/scaling-kubernetes-deployments-with-amazon-cloudwatch-metrics/

**Comment by andrewsykim** [comment]
The name of the ELB should still be predictable, it's "a" + "Service UID". See https://github.com/kubernetes/cloud-provider/blob/master/cloud.go#L77-L91 for how the name is generated.

**Comment by costimuraru** [comment]
Thanks, @andrewsykim. This is useful information, thanks for sharing!
It does not solve the whole issue though, because the UID is randomly generated so we still need to wait for the LoadBalancer resource to be created first.
This means we can't create the `LoadBalancer` resource alongside the `ExternalMetric`, in one step. We still have to first create the LoadBalancer, retrieve the Service UID somehow (manually or by a custom script) and create the second resource (ExternalMetric in our case).
That's why I was suggesting the ability to create a pretty name for the ELB, in which case the name would be known beforehand and the two resources could be created together (eg. via a helm chart).
Am I missing something?

**Comment by ImIOImI** [comment]
I'd also like to see this so I can automate assigning a load balancer to a new deploy with terraform

**Comment by JonathanParrilla** [comment]
How is this issue still open? I appreciate that I can look up the UI of the service and realize that the ELB naming convention is "a<service UUID>", but that is not ops friendly, or programmer friendly.

We should be able to determine the name of the ELB upon creation within the yaml file. No different than we establish tags, ports, SSL certs, and everything else...except the name.

**Comment by glenjamin** [comment]
Is this something that's blocked on a philosophical point, or does it just require someone to go write the code to make it work?

**Comment by chaimk-als** [comment]
Seems to be related to this case:
https://github.com/kubernetes-sigs/aws-alb-ingress-controller/issues/1331
And this code:
https://github.com/kubernetes-sigs/aws-alb-ingress-controller/blob/master/internal/alb/generator/name.go#L23

**Comment by andrewsykim** [comment]
I'm going to close this issue because the in-tree cloud provider is deprecated and we are actively trying to remove it. We are looking into improving the naming of ELBs in the out-of-tree cloud provider implementation https://github.com/kubernetes/cloud-provider-aws. 

/close

**Comment by andrewsykim** [comment]
For people watching this issue, we are also looking into allowing node names that are not the private DNS of the ec2 instance.

**Comment by voor** [comment]
Please move your :+1: and requests to https://github.com/kubernetes/cloud-provider-aws/issues/124 to help prioritize

**Comment by dineshkumar181094** [comment]
> 👍 we are also interested in this feature 😄 We are currently implementing our own adapter with custom annotation to automatically assign Route 53 DNS records (Alias) for the ELB.

is this custom adapter is open-sourced?
