### ISSUE TITLE
Can't finish Kubernetes deployment on VMware vSphere

### ISSUE THREAD

**Issue by evaldasou** [kubernetes/kubernetes#29783]
Hi Guys!

I have followed this guide in order to deploy Kubernetes on VMware : http://kubernetes.io/docs/getting-started-guides/vsphere/

However, I reach the same wall every time I try to re-deploy it. Maybe anyone has any ideas what to do next, or what to change in order to finish deployment succesfully?

> root@kube:/home/kube/kubernetes/kubernetes# KUBERNETES_PROVIDER=vsphere cluster/kube-up.sh
> ... Starting cluster using provider: vsphere
> ... calling verify-prereqs
> ... calling kube-up
> Identity added: /root/.ssh/id_rsa (/root/.ssh/id_rsa)
> Starting master VM (this can take a minute)...
> kubernetes-server-linux-amd64.tar.gz                                                                                                                                                                              100%  351MB 873.0KB/s   06:52  
> kubernetes-salt.tar.gz                                                                                                                                                                                            100%   44KB  44.2KB/s   00:00  
> uploaded /tmp/kubernetes.fgu5oh/master-start.sh to /tmp/master-start.sh
> Using master: kubernetes-master (external IP: 10.0.30.150)
> 
> Starting node VMs (this can take a minute)...
> uploaded /tmp/kubernetes.fgu5oh/node-start-1.sh to /tmp/node-start-1.sh
> uploaded /tmp/kubernetes.fgu5oh/node-start-0.sh to /tmp/node-start-0.sh
> uploaded /tmp/kubernetes.fgu5oh/node-start-3.sh to /tmp/node-start-3.sh
> uploaded /tmp/kubernetes.fgu5oh/node-start-2.sh to /tmp/node-start-2.sh
> Found kubernetes-minion-1 at 10.0.30.151
> Found kubernetes-minion-2 at 10.0.30.154
> Found kubernetes-minion-3 at 10.0.30.155
> Found kubernetes-minion-4 at 10.0.30.152
> Waiting for salt-master to be up on kubernetes-master ...
> This may take several minutes. Bound to 60 attempts....
> [salt-master running]
> 
> Waiting for all packages to be installed on kubernetes-master ...
> 
> This may take several minutes. Bound to 60 attempts............................................................
> (Failed) rc: 1 Output: 
> 
> sudo salt "kubernetes-master" state.highstate -t 30 | grep -E "Failed:[[:space:]]+0" failed to start on 10.0.30.150. Your cluster is unlikely
> to work correctly. You may have to debug it by logging in.

**Comment by kylegordon** [comment]
Hi @evaldasou 

I had exactly the same problem with the released versions of Kubernetes. I solved it by git cloning from master, and doing 'make quick-release'.

Make sure you have the following stuff exported...

GOVC_URL
GOVC_INSECURE
GOVC_DATACENTER
GOVC_DATASTORE
GOVC_RESOURCE_POOL
GOVC_NETWORK
GOVC_GUEST_LOGIN=kube:kube

After that, it should be a case of doing cluster/kube-up.sh.

Let me know how it goes please.

Kyle

**Comment by chrislovecnm** [comment]
Should be able to update here https://github.com/kubernetes/kubernetes.github.io

On my phone so I could not check

**Comment by kylegordon** [comment]
Excellent, thank you. Docs updated in https://github.com/kubernetes/kubernetes.github.io/pull/1007

**Comment by kerneltime** [comment]
The latest code in master in release-1.4 does not have this issue. This issue should be closed.

**Comment by evaldasou** [comment]
thanks everyone!

**Comment by avirat28** [comment]
I have similar issue even after adding GOVC_GUEST_LOGIN.

root@photon-863c115f50dd [ ~/kubernetes ]# KUBERNETES_PROVIDER=vsphere cluster/kube-up.sh
... Starting cluster using provider: vsphere
... calling verify-prereqs
... calling kube-up
Identity added: /root/.ssh/id_rsa (/root/.ssh/id_rsa)
Starting master VM (this can take a minute)...
Powering on VirtualMachine:vm-148... OK
kubernetes-server-linux-amd64.tar.gz                                                                                                                                                                        100%  336MB   4.7MB/s   01:11
kubernetes-salt.tar.gz                                                                                                                                                                                      100%   53KB   8.8KB/s   00:05
uploaded /tmp/kubernetes.bCMP0S/master-start.sh to /tmp/master-start.sh
Using master: kubernetes-master (external IP: 100.115.254.40)

Starting node VMs (this can take a minute)...
Powering on VirtualMachine:vm-151... Powering on VirtualMachine:vm-152... Powering on VirtualMachine:vm-150... Powering on VirtualMachine:vm-149... OK
OK
OK
OK
kubernetes-minion-3-ip                                                                                                                                                                                      100%   72   236.3KB/s   00:00
kubernetes-minion-1-ip                                                                                                                                                                                      100%   72   243.6KB/s   00:00
kubernetes-minion-2-ip                                                                                                                                                                                      100%   72   152.5KB/s   00:00
kubernetes-minion-4-ip                                                                                                                                                                                      100%   72   206.4KB/s   00:00
uploaded /tmp/kubernetes.bCMP0S/node-start-3.sh to /tmp/node-start-3.sh
uploaded /tmp/kubernetes.bCMP0S/node-start-2.sh to /tmp/node-start-2.sh
uploaded /tmp/kubernetes.bCMP0S/node-start-1.sh to /tmp/node-start-1.sh
uploaded /tmp/kubernetes.bCMP0S/node-start-0.sh to /tmp/node-start-0.sh
Found kubernetes-minion-1 at 100.115.254.17
Found kubernetes-minion-2 at 100.115.254.16
Found kubernetes-minion-3 at 100.115.254.15
Found kubernetes-minion-4 at 100.115.254.14
hosts                                                                                                                                                                                                       100%  140   580.5KB/s   00:00
hosts                                                                                                                                                                                                       100%  140   435.3KB/s   00:00
hosts                                                                                                                                                                                                       100%  140   648.3KB/s   00:00
hosts                                                                                                                                                                                                       100%  140   396.3KB/s   00:00
Waiting for salt-master to be up on kubernetes-master ...
This may take several minutes. Bound to 60 attempts.....
.......................................................
(Failed) rc: 1, output:

salt-master failed to start on 100.115.254.40 after checking for 60 attempts. Your cluster is unlikely
to work correctly. You may have to debug it by logging in.

Any suggestions ?

To me it looks like salt-master is not configured at all on the master due to non-root user login.
