### ISSUE TITLE
Scheduler and Kubelet don't agree on resources

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#29846]
SchedulerPredicates tests (MaxPods and resource usage) started failing from time to time with an error I haven't seen before - Kubelet and Scheduler don't agree on amount of free resources. Namely scheduler successfully schedules Pod to a Node:

```
Jul 30 05:35:58.751: INFO: At 2016-07-30 05:25:58 -0700 PDT - event for overcommit-6: {default-scheduler } Scheduled: Successfully assigned overcommit-6 to jenkins-e2e-minion-group-s9i0
```

but Kubelet rejects it:

```
Jul 30 05:35:58.751: INFO: At 2016-07-30 05:25:58 -0700 PDT - event for overcommit-6: {kubelet jenkins-e2e-minion-group-s9i0} OutOfCPU: Node didn't have enough resource: CPU, requested: 500, used: 1508, capacity: 2000
```

If I understand correctly our assumptions that shouldn't happen in a healthy system with a single scheduler (probably it shouldn't happen at all, but that's beside the point). Full logs available in 
https://storage.googleapis.com/kubernetes-jenkins/logs/kubernetes-e2e-gce-serial/1825/build-log.txt
in test `validates resource limits of pods that are allowed to run`.

It _may_ be related to #29845.

@wojtek-t - can this be caused by some of the changes you recently did?

cc @davidopp @kubernetes/goog-node

**Comment by wojtek-t** [comment]
All of them were supposed to be no-op changes from the "logic" point of view.

@gmarek - are we sure that there is no race with pods scheduled differently (either with preassigned node or e.g. DaemonSets)?

**Comment by gmarek** [comment]
Yeah, we're pretty sure. It's in serial suite and the cluster looks stable (but see #29845).

**Comment by wojtek-t** [comment]
The only logical changes in the code should be coming from bug fixes:
https://github.com/kubernetes/kubernetes/issues/28883
https://github.com/kubernetes/kubernetes/issues/29098

**Comment by wojtek-t** [comment]
OK - so my feeling is that we should first debug #29845 and see if that helps here too (if something is not in apiserver, then scheduler also won't be aware of it).

**Comment by wojtek-t** [comment]
>
If I understand correctly our assumptions that shouldn't happen in a healthy system with a single scheduler 

We have DeamonSets currently, that means that logically we already have two schedulers.

This failure is coming from serial suite, where we have different disruptive tests - can this be related to e.g. adding a node or sth like that?

**Comment by hpejustin** [comment]
This may happens when the resource usage of the target node increased after the pod has been scheduled to it but before final predict before run by kubelet. Kubelet do final predict to determine if the pod should be run via canAdmitPod functions, which consist of some predict functions. Among all the predicts functions, one is about resource which name is PodFitsResources. This function is also the function which was used by the scheduler to determine if the pod resource request can be accept. So,this reason maybe the only one can explain why this happen. For more detail, please see https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet.go#L2053

**Comment by gmarek** [comment]
This is clear. The question is what would cause this increase. The only thing I can think of is starting a mirror pod.

**Comment by yujuhong** [comment]
From #29845, the image-puller pod on the node (`jenkins-e2e-minion-group-s9i0`) has terminated, so kubelet didn't try to create the mirror pod again (which was evicted/deleted in an earlier test).
The difference then becomes:
 * kubelet thinks there is a image-puller pod in a terminated state.
 * scheduler is not aware of the image-puller pod at all.

The discrepancy should not matter for scheduling because kubelet doesn't take into account "terminated pods" during admission. 

One thing that anyone could do is to total the used resources by pods on the node, and see if it matches what the kubelet claimed:
`I0730 12:25:58.720645   24978 kubelet.go:2058] Predicate failed on Pod: overcommit-6_e2e-tests-sched-pred-xfkrx(c52d62c1-5650-11e6-ac13-42010af00002), for reason: Node didn't have enough resource: CPU, requested: 500, used: 1508, capacity: 2000`

From `kubectl get pods`:
```
overcommit-1 jenkins-e2e-minion-group-s9i0 Running
overcommit-6 jenkins-e2e-minion-group-s9i0 Failed
elasticsearch-logging-v1-01e37 jenkins-e2e-minion-group-s9i0 Running
fluentd-elasticsearch-jenkins-e2e-minion-group-s9i0 jenkins-e2e-minion-group-s9i0 Running
heapster-v1.1.0-527143062-i41q6 jenkins-e2e-minion-group-s9i0 Running
kube-proxy-jenkins-e2e-minion-group-s9i0 jenkins-e2e-minion-group-s9i0 Running
monitoring-influxdb-grafana-v3-0 jenkins-e2e-minion-group-s9i0 Running
node-problem-detector-v0.1-77c91 jenkins-e2e-minion-group-s9i0 Running
```

**Comment by gmarek** [comment]
@yujuhong - I don't understand what you wrote. IIUC the only pods that scheduler shouldn't be aware of according to the mirror-pod theory are the terminated ones, which should be accounted by kubelet as well. This means that all scheduler decisions should still be correct and Kubelet shouldn't be rejecting any one of them. What am I missing?

**Comment by yujuhong** [comment]
@gmarek you didn't miss anything. I think *theoretically* this discrepancy should not cause any mistake in scheduling, but I didn't have time to check how kubelet's calculation of cpu resource matches the pods printed from `kubectl get pods`. If someone can do the calculation, maybe he/she can shed some light on the issue.

**Comment by gmarek** [comment]
Assigning to @dchen1107 to triage. cc @davidopp

**Comment by gmarek** [comment]
I believe #37293 should have fixed this.
