### ISSUE TITLE
Do not enumerate volume plugins in SecurityPolicy

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#29896]
pkg/apis/extensions/v1beta1/types.go has an FSType type that has a set of string variables naming each volume plugin.  Firstly, it names plugins in a way that is inconsistent with the way plugins name themselves (no prefix!).  Secondly, we should NOT be enumerating plugin names.  This will never be maintainable over time.

It should be strings, full stop, or make it a type but let it hold any value.

@pweil- @saad-ali

**Comment by pweil-** [comment]
This is actually referring to the volume sources and I'm attempting to keep `FSType` and `VolumeSource` fields in sync.  I created tests to ensure that we could be flag the drift that occurs and not have to be constantly chasing new volume sources: https://github.com/kubernetes/kubernetes/blob/master/pkg/security/podsecuritypolicy/util/util_test.go#L31.

I'm not sure I see much difference in a string or a typed string since I'd still want to make sure it covers all volume sources.  I'd still want the test to make sure we're not chasing policy updates because we missed a new volume source.  If I removed the `FSType` and just made it a string but kept the sync tests would that suffice?

cc @pmorie

**Comment by thockin** [comment]
I am asserting that any place outside of the plugin itself that spells out
a plugin's name is wrong.  Eventually we will have more and more
out-of-process plugins that you can't enumerate this way.  I *hate* that it
is spelled out in the API, and if/when we move to more use of
out-of-process, it must be solved differently.

No urgent fire, but I'd much rather not keep a list of this, especially so
far away from the actual code.

**Comment by saad-ali** [comment]
CC @pmorie

**Comment by thockin** [comment]
/lifecycle frozen

This is a real issue, especially once CSI kicks in. @saad-ali
