### ISSUE TITLE
CI and test-cmd

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/kubernetes#29938]
*problem*

test-cmd isnt validated in all cases by the CI.  

to reproduce, we can corrupt test-cmd.sh and run the ci driver, to detect how it gets overlooked.

*solution*

make sure that the CI validates that test-cmd runs with exit code 0.  

*background*

Looks like https://github.com/kubernetes/kubernetes/pull/29918 fixed a bug i introduced in one of my go-bindata rebases, wherein test-cmd had a huge merge conflict @ the top.

The rebase has been fixed (thanks @deads2k) , but the question remains... Any idea how test-cmd could be so broken yet passes CI ? PS thanks to everyone who helped fix this.  

cc @deads2k @lavalamp @timothysc @kubernetes/sig-testing

**Comment by ixdy** [comment]
CI runs `make test-cmd`, which calls `hack/make-rules/test-cmd.sh`. `hack/test-cmd.sh` was left as a pass-through until folks update their workflow.

There was a bad rebase in #25584 which broke `hack/test-cmd.sh`, but CI didn't notice since it doesn't use it anymore. Since this script is deprecated, there's really nothing to fix.
