### ISSUE TITLE
Investigate logs2kafka + kafka as a ES + fluentd replacement

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#30006]
docker -> logs2kafka -> kafka -> Various data sinks like ES, S3, write to disk etc

The win here is getting json into kafka, this allows us to fanout to various different backends each with their own strengths (eg: kibana for log analysis). Kafka itself gives us a flexible, scalable middle tier that would enalbe things like a sql interface (https://www.pipelinedb.com/blog/sql-on-kafka).

Forking from: https://groups.google.com/forum/#!topic/google-containers/iLDsG85exRQ

@piosz fyi

**Comment by edsiper** [comment]
Note that Fluentd already supports Kafka, so if the goal is to replace ES at some point a Fluentd configuration should be enough.

**Comment by bprashanth** [comment]
The goal I think is to improve the stability of our logging pipeline, while supporting a more flexible core. On cloudproviders, we offload straight to some cloud service so scale isn't an issue. I don't think we've actually tested clusters that need more than 2 ES shards.

**Comment by matthiasr** [comment]
I started that thread, so I'll add some of our thinking …

# Where [we](https://soundcloud.com) came from

Before Kubernetes, we have been using a homegrown deployment platform supporting [12 factor](http://12factor.net) applications. All applications log to stdout/stderr. The logs are shipped off nodes asynchronously and (after some delay) show up in HDFS.

We want to replace both the platform (with Kubernetes) and the logging system. We do not want to make significant changes to our application model.

Independently, some teams have been running ELK stacks for their own systems, with system-specific mechanisms to get messages there.

# How we got here

In preproduction, we started out by just dropping the fluentd/elasticsearch logging example from Kubernetes into our clusters. This worked for a short period of time but was very unstable; at some point deleting all elasticsearch pods to start over did not recover it and we gave up on it for a while.

We try to keep shared/multi-tenant infrastructure to a minimum, preferring reusable components that are instantiated per system that requires them.

We realized that running a sizable Elasticsearch cluster is hard – so much so that it was neither practical to expect every team to run their own (which implies that the reusable component must be mostly maintenance-free) or a company-wide one (which would be huge).

In a very insightful conversation @lennartkoopmann (of Graylog) dropped the wisdom that 99% of all operational log lines are never analyzed, and that every analysis starts with a time frame ("right now" or "yesterday between 2 and 4").

Another team had started exploring Kafka as a replacement for our aging log shipping system before we took over this area. Kafka _is_ a distributed log, so it offers just the right primitives for what we need but with much better operational characteristics and usability than what we had before.

We started out by modifying the fluentd-es configuration to write to Kafka, which works quite well. However, some of our systems log at high volumes (~10kB/s/pod) and our nodes are big, so  fluentd could not keep up even pegging 2 cores.

We realized we do need to maintain the HDFS "interface" as a compatibility, but only for a small subset of applications – accessing logs directly from Kafka and maintaining them there for some period of time (~2 weeks) is enough to cover operational/debugging use cases for developers. HDFS is only needed for a few map-reduce jobs (and these should not rely on operational logs).

# Current design

Applications keep logging to stdout / stderr. The Docker daemon writes and maintains local log files, it makes sure to rotate them so the local disk usage is bounded.

A custom, dedicated log-shipper tails the current one of these (with snapshotting so it should not lose messages while restarting). It is deployed as a daemonset like fluentd was. It uses the Kubernetes API client with caching to annotate the log lines with metadata. Colleagues are currently working on this, I'll lobby to open source it.

The log messages are logged into Kafka, annotated with pod labels and a timestamp as part of a JSON message. There is one Kafka topic per namespace. The partition key is the container ID so that ordering is preserved within the logstream of a single container, but not across containers.

An independent reusable component can be deployed into a namespace to ship logs from that namespace's log topic into HDFS, if the owners of the system wish to do so.

# Future ideas

We have a half-done tool to pull data for a certain time frame out of Kafka and feed it into a temporary [Graylog](https://www.graylog.org/) instance which uses local storage to keep the index. The end goal here is to have "on-demand log analysis" as yet another reusable component, to be employed either in tailing mode or retroactively (limited by the Kafka retention) whenever it is needed.

Doing this after the fact and not as the main storage for the log data makes our lives much easier. For log lines that are never analyzed, the work to index them and keep these indexes up to date is saved. We do not need to keep a moving elasticsearch cluster alive and healthy – even if one of these temporary analysis components fails we destroy it and start over from the raw data in Kafka.

This will be almost-realtime and certainly more usable than writing mapreduce jobs over logs all the time.

**Comment by spiffxp** [comment]
/sig instrumentation
because logging

**Comment by garo** [comment]
We have improved logs2kafka now to support Graylog format, which works better with Docker as it can send more metadata from Docker to the logging tier.
