### ISSUE TITLE
Kubelet flag cluster-domain doesn't work if resolve-conf is configured

### ISSUE THREAD

**Issue by nearbyfly** [kubernetes/kubernetes#30073]
Hi,

When starting Kubelet both cluster-domain and resolve-conf are passed, but only resolve-conf took effect. The cluster-domain still inherited from host /etc/resolv.conf search domains.

Based on pkg/kubelet/dockertools/manager.go, looks like resolve-conf can overwrite cluster-domain. Is that the intention to introduce resolve-conf to replace cluster-domain and cluster-dns?

But there is no description about interaction about these related flags.

Regards,
Neil

**Comment by yujuhong** [comment]
The documentation around these flags and dns policy is lacking (#31813). @kubernetes/sig-network-misc will have a better idea of what's the expected behavior.
FWIW, I think PR #29666 changed the logic around the passed --cluster-domain and resolve-conf. Not sure if that was intended.

**Comment by thockin** [comment]
ouch.  We should fix this.

cluster-domain is sort of important.

**Comment by tacy** [comment]
@thockin - What is the expected behavior if both cluster-domain and resolv-conf are passed.

I start kubelet with flags: '--cluster-domain=cluster.local --resolv-conf=/root/resolv.conf',  the result is following:

```
[root@primeton-tacy-k8s-node2 ~]# cat /root/resolv.conf
# Generated by NetworkManager
nameserver 192.168.11.181
search example.com

[root@primeton-tacy-k8s-master ~]# kubectl exec -it busyboxmusl-273741147-qjg3x cat /etc/resolv.conf
nameserver 10.96.0.10
search default.svc.cluster.local svc.cluster.local cluster.local example.com
options ndots:5
```

**Comment by thockin** [comment]
--resolv-conf should *only* change where we get the initial resolve info.
Beyond that, the semantic should be exactly the same as the default path -
e.g. merge `search` lines

**Comment by tacy** [comment]
> --resolv-conf should *only* change where we get the initial resolve info.
Beyond that, the semantic should be exactly the same as the default path -
e.g. merge `search` lines

See: https://github.com/kubernetes/kubernetes/tree/master/pkg/kubelet#L1215

GetClusterDNS  would read resolv.conf and merge cluster.domain to `search` line , I think that it is same with your comment,  Or have I missed something?

**Comment by thockin** [comment]
Yeah, that looks right.  Looking at the code, it's as straight-forward as I remember.

@nearbyfly can you provie more details?

What does /etc/resolv.conf look like?

What does the alternate resolv.conf look like?

What does a pod's resolv.conf look like?

**Comment by thockin** [comment]
Maybe this is a non-bug :)

**Comment by thockin** [comment]
Any update on this?

**Comment by bowei** [comment]
Update or punting to next milestone...

**Comment by bowei** [comment]
@dchen1107  punt from milestone

**Comment by dchen1107** [comment]
Removed to next milestone since we didn't fix this.

**Comment by someword** [comment]
I am running into this issue as well and I see that the questions posted by @thockin never got answered so I'll do that now.  The reason why i'm interested in this issue is that we are looking to move to pointing the pods to dnsmasq which is bound to the docker0 bridge on each node.   This requires the use of the kubelet --resolv-conf flag.

 > What does /etc/resolv.conf look like?

```
nameserver 10.20.0.2
search ec2.internal
```
> What does the alternate resolv.conf look like?

```
nameserver 172.20.150.1
nameserver 172.16.0.10
search ec2.internal
```

> What does a pod's resolv.conf look like?
The issue here is the search list is not getting created it's just being copied from the alternate resolv.conf as is.

```
search ec2.internal
nameserver 172.20.89.1
nameserver 172.16.0.10
options ndots:5
```

When I do a describe on a pod that launched on a node where kubelet is configured to use an alternate resolv-conf I see this warning

>   kubelet does not have ClusterDNS IP configured and cannot create Pod using "ClusterFirst" policy. Falling back to DNSDefault policy.
  1m            1m              1       {kubelet ip-10-20-8-134.ec2.internal}   spec.containers{scarf}                  Normal          Started 

The default dns policy is just to copy /etc/resolv.conf from the node to the pod.  It looks like to me the combination of the default dns policy and the kubelet --resolv-conf flag gives us a scenario where the search and nameserver entries from the alternate resolv.conf are preserved but the ndots:5 is still added.   What I would expect is that only the namserver lines from the alternate resolv-conf are used from the alternate resolv-conf and the search line is built by the kubelet and injected into the pods resolv.conf so you would end up with the typical kubernetes search path of something like this.

> <namespace>.svc.cluster.local svc.cluster.local cluster.local ec2.internal

Let me know if any further info is needed.
Thanks.

**Comment by someword** [comment]
@bowei @thockin 
If you guys can add the labels required to keep this in the v1.8 milestone I will try to work up a pull request for the issue.

**Comment by someword** [comment]
Some more details about what is going on here.   When running the kubelet with the flags
`--cluster-domain=cluster.local --resolv-conf=/etc/kube-resolv.conf`
And the contents of /etc/kube-resolv.conf are

> nameserver 172.20.76.1
> search ec2.internal
> 

The beginning of the process to manufacture a pods resolv.conf begins [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet.go#L1347).

The alternate resolv conf is parsed [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet.go#L1357).
At this point the variables `hostDNS` and `hostSearch` are 

> hostDNS = 172.20.76.1
> hostSearch = ec2.internal

The variable `useClusterFirstPolicy` get's set to false [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet.go#L1362-L1371) because the kubelet is not running with the `--cluster_dns` flag.

Because `useClusterFirstPolicy` is false we enter this [block](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet.go#L1374) which passes `hostSearch` [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet.go#L1386) which passes `hostSearch` along to [this](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet_network.go#L139) which in turn passes it to [this](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet_network.go#L104) which is just verifying that the search domains meet the length/limit requirements of the linux resolver.  

At the end of the above adventure the pods manufactured /etc/resolv.conf is
> nameserver 172.20.76.1
> search ec2.internal

Which is missing the desired search domains of 
`kube-system.svc.cluster.local svc.cluster.local cluster.local`

When running the kubelet with the flags
`--cluster_dns=172.16.0.10 --cluster-domain=cluster.local --resolv-conf=/etc/kube-resolv.conf `

The resulting /etc/resolv.conf in the pod is
> nameserver 172.16.0.10
> search kube-system.svc.cluster.local svc.cluster.local cluster.local ec2.internal
> options ndots:5

So to me this seems like a bug.  It's possible the bug is with my interpretation of what the intended outcome *should* be.

**Comment by charandas** [comment]
Assuming you have modified kubelet to use a custom `resolv.conf` using `--resolv-conf=/path/to/resolv.conf`: you have to remember to use `hostNetwork` in my experience for it to actually work:

```
      hostNetwork: true
      containers:
      - name: my-service
```

Using an empty `--resolv-conf=` with kubelet did not inherit my node's resolv.conf, I saw this instead in the test container:

```
cat /etc/resolv.conf

nameserver 127.0.0.1
seach ''
```

**Comment by paravz** [comment]
My understanding from DNS docs is that pods with "dnsPolicy: ClusterFirst", should have "--cluster-dns" in pod's /etc/resolv.conf.

This is still an issue in v1.8.3 (and likely in 1.9): pods with "dnsPolicy: ClusterFirst" only use host node's /etc/resolv.conf, ignoring --cluster-dns in the following configuration produced by kubespray:



```
kubelet --cluster-dns=10.233.0.3 --cluster-domain=cluster.local --resolv-conf=/etc/resolv.conf

[kube-node]$ cat /etc/resolv.conf
search default.svc.cluster.local svc.cluster.local
nameserver 169.254.169.253

```

```
[pod]$ $ cat /etc/resolv.conf
nameserver 169.254.169.253
search default.svc.cluster.local svc.cluster.local
```
