### ISSUE TITLE
DoS protection for ingress

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#30088]
We should AT LEAST document how to handle it, but ideally give users an easy way to prevent agains some of the most common attacks both at l7 and l4. 

Most obvious options is to accumulate logs from a bank of nginx ingress controllers via fluentd into ES/Cloud logging and setup a reconciliation loop that feeds into a DoS engine, which then sends accept/reject policy back down to nginx, through the Ingress. We'd need to add a DoS section to Ingress for this. 

We could also do pof at iptables layer (http://www.ioremap.net/projects/osf/), or some iptables firewalling as discussed https://github.com/kubernetes/kubernetes/issues/22679 and https://github.com/kubernetes/kubernetes/issues/13774. Would be nice if the apiserver could use the DoS engine to protect itself, when/if we move it behind an Ingress.

**Comment by therc** [comment]
I had a wishlist for traefik last time I evaluated it: https://github.com/containous/traefik/issues/431

**Comment by bprashanth** [comment]
@therc nice list. maybe you have time to collaborate over adding something basic to the nginx ingress controller? we'd start out by piping things through annotations, iterate, then boil it up to the Ingress api.

**Comment by therc** [comment]
Not for another month. :-( By the end of next week, I have three features to complete and a conference in SF to attend, then ContainerCon, then two weeks off. And a launch needs to happen through all of this. :-)
I found traefik more interesting than nginx, because it can be repurposed into a controller.

**Comment by anguslees** [comment]
Other commonly seen DoS attacks are non-HTTP things like SYN floods and DNS amplification attacks.  I mention these because these are unlikely to work via nginx/ingress, and the source IPs are likely spoofed.  I think a slow feedback loop based on mining logs will likely block the wrong target and/or be prohibitively expensive to be effective for these lower levels.

**Comment by bprashanth** [comment]
Typically volumetric attacks are dropped by the cloudprovider/CDN etc. You have a harder problem if you *are* the CDN, you'd probably have to resort to some smart iptables black listing policy that ends up being more reactive and strategic than proactive.

**Comment by aledbf** [comment]
Today nginx released a new version of [nginx-plus](https://www.nginx.com/blog/nginx-plus-r10-released/) that includes Modsecurity3 as web application firewall (WAF) module (supported by nginx Inc).

The repository [owasp-modsecurity-crs](https://github.com/SpiderLabs/owasp-modsecurity-crs/tree/v3.0.0-rc2) contains the rules that works OOTB. This set includes 2 rules that can help with this issue:
- [block countries](https://github.com/SpiderLabs/owasp-modsecurity-crs/blob/v3.0.0-rc2/crs-setup.conf.example#L525)
- [DOS protection ](https://github.com/SpiderLabs/owasp-modsecurity-crs/blob/v3.0.0-rc2/crs-setup.conf.example#L554)

(this also works in the open source version of nginx using the [ModSecurity-nginx](https://github.com/SpiderLabs/ModSecurity-nginx) repo)
