### ISSUE TITLE
kubelet should fail if version of docker is not supported

### ISSUE THREAD

**Issue by streamnsight** [kubernetes/kubernetes#30117]
this is just my opinion, but I think kubelet should fail if it doesn't have a supported version of docker.

i went on and upgraded kubelet to 1.3.4 on a CoreOS 899.17 and kubelet happily reported it was running, so I thought all was fine, and upgraded other machines, only to realize my pods died after a few minutes...
looking at the logs i see kubelet could not find docker 1.10+ and just wasn't running properly.

That's a pretty important dependency to be missing, so I am not sure why kubelet should be running if it doesn't have it; IMHO it should terminate fatally so it's clear right away that it won't work on the given machine.

**Comment by dchen1107** [comment]
@streamnsight today Kubelet detects 
1) if the runtime is running. If not, it reports the node is not ready due to runtime is down
2) if the runtime is running, but the version is below the minimal support version, it reports node is not ready too. 

For 1.3 release, sig-node team validate both docker 1.11.x and docker 1.10.X, but both have some issues which are documented as known issue of the runtime in the release notes. But I have to admit that we didn't validate docker 1.10.X specifically on CoreOS. 

From what you reported above, I am not sure the root cause is. Also when you said kubelet should fail, have you run kubectl describe node <node id> yet? If Kubelet properly detect the issue and report runtime is down?

**Comment by streamnsight** [comment]
my point was that one is supposed to be able to update kubelet on a live node. if kubelet is upgraded and is running, even though it can't do its job because the runtime is below required version, it 'looks' like kubelet upgraded successfully... but the node is reported as not ready and pods fail.

if kubelet would fail on mismatched version, it's clear that something is wrong, and there is time to rollback to previous version, and figure what is wrong. 
without clear failure, it's difficult to realize the node will eventually go to not ready and dump the pods.

**Comment by dchen1107** [comment]
@streamnsight If I understood your above comment correctly, you want Kubelet reason about why the node not ready. If that is true, I think we already provide that information. Have you tried to try kubectl describe node <node id>?  The output of that command should include a list of node conditions including Ready. If it is false, the message column should tell the root cause of the NotReady condition.

**Comment by streamnsight** [comment]
@dchen1107 I was mostly pointing out that if kubelet doesn't have the correct version of Docker to work with, it will fail no matter what, so while it's good to have tools to get the information, a pure and simple failure of the service is way more obvious right away: upgrade kubelet, run it, if it doesn't run, logs will tell Docker needs an update and it's crystal clear this kubelet upgrade won't run without further work.

Time if of the essence when upgrading a live node: once the scheduler figured the node is not Ready the Pods are gone. If kubelet fails and it's obvious right in the first few seconds, there is time to roll back previous kubelet and then look for solutions.

If kubelet happily says it's running, I would patiently wait to see the node turn 'ready' only to see Pods being terminated. 

It is simply my opinion that hard, obvious failure when there is no way kubelet will work, just make life easier.
