### ISSUE TITLE
Lock ObjectMeta as tag 1 for all objects when serialized to protobuf

### ISSUE THREAD

**Issue by caesarxuchao** [kubernetes/kubernetes#30110]
This rule is useful in several scenarios: 1. this will make it easy to decode only the ObjectMeta part, which is useful for the garbage collector. See #28480. 2. this will make it easy to push indexing down into the storage layer.

@smarterclayton suggested we also need to handle the objects that don't have ObjectMeta. (like `SubjectAccessReview` in #20573?)

Initial discussion is here: https://github.com/kubernetes/kubernetes/pull/28480/files/41d92b1b3fe4883311ae3037fb816f858d565fbd#r73240203

**Comment by smarterclayton** [comment]
So let's play this out.  What happens if we split ObjectMeta in a future API revision?  Objects without ObjectMeta, or which have a stripped down ObjectMeta (things may have names that don't have labels, for instance)?

We would need to have a way to identify the schema of ObjectMeta from an external source (swagger) to safely decode.  We already need that for a few other things (Status, ListOptions, Scale).  Not every resource is versioned at the same rate.  Maybe we should have just kept Status/ListOptions/Scale in their own API groups and returned them from API endpoints - it makes generic clients lives much easier ("you gave me a Scale object... but *which* Scale object?").

**Comment by caesarxuchao** [comment]
> What happens if we split ObjectMeta in a future API revision? Objects without ObjectMeta, or which have a stripped down ObjectMeta (things may have names that don't have labels, for instance)?

Those different flavors of ObjectMeta will be versioned, right? And we know the mapping between a Kind to its version of ObjectMeta, so I think we can decode it. What did I miss?

**Comment by smarterclayton** [comment]
If we have to know the mapping in the future, why hardcode a
potentially incorrect assumption now?  Why not implement the minimal
path that correctly identifies how to get ObjectMeta in schema X from
kind Y?

I ask because we already have some overlap here with ListOptions and
status - naive client needs to fetch things cross version group, and
so some mapping between group -> sub schema is necessary.

Strawman 1:

Clients can request a Kind and Version representation of a resource
"v1.ObjectMeta" from the API server on list / get / watch.  Future
implementations can provide alternate representations (get RC "as"
RS).

Strawman 2:

Clients read metadata we encode in swagger  to locate the correct
subset of object via JSON and protobuf.

The former is potentially more performant and makes clients simpler.

**Comment by caesarxuchao** [comment]
Yeah, both seem reasonable. I'll create an issue for strawman 1 to track.
