### ISSUE TITLE
Create ReplicaSet

### ISSUE THREAD

**Issue by jstrachan** [kubernetes/kubernetes#3024]
When using the CLI or REST API or just talking about Kubernetes to people the phrase "replication controller" is a little bit of a mouthful. Pod & service are 1 and 2 syllables. "replication controller" is as many syllables as service, pod and kubernetes combined ;)

How about using the phrase "replicator" instead? Shorter, less to type on the CLI and less to say out loud? Then the core pieces of Kubernetes would be pods, services and replicators?

**Comment by jasonkuhrt** [comment]
@bgrant0607 What's the status on this now? Is there an expected winner yet?

**Comment by bgrant0607** [comment]
@jasonkuhrt Was out for the holidays. Will pick this up again later this week -- a few things are ahead of it in my queue. Also, first we need to resolve #3058 -- subobjects vs.separate objects for main different controller types.

**Comment by bgrant0607** [comment]
Some more fuel for the fire:
* The existing name and proposals convey that the object is active: controller, overseer, replicator, etc. This is in distinct contrast to our other objects, pods and services, which are no less active. Services also monitor label selectors, for instance, and pods monitor and restart containers using liveness probes. This inconsistency suggests that we should at least entertain inactive-sounding names, as well.
* If we go with the separate-object/plugin approach, there will be multiple controllers that replicate and/or oversee pods, so neither of those will be distinguishing properties. Other planned controllers include per-something controllers (generalization of per-node #1518), batch/workflow job controllers (#1624), cron controllers (#2156), and, depending on your definition of "controller", auto-scalers (#2863) and nominal services (#260).
* For the separate-object approach, we'll want first-class metadata about Kinds of objects in order to be able to reliably determine which object Kinds represent controllers and the Kinds of objects they control, so "Controller" need not be part of the Kind name.

**Comment by jasonkuhrt** [comment]
> The existing name and proposals convey that the object is active: controller, overseer, replicator, etc. This is in distinct contrast to our other objects, pods and services, which are no less active. Services also monitor label selectors, for instance, and pods monitor and restart containers using liveness probes. This inconsistency suggests that we should at least entertain inactive-sounding names, as well.

To play devil's advocate; `service` should be renamed to be active and `pod` is only active on entities which it wraps but ***not*** on any peer objects. So the POV I'm imaging right now is that there is a single noun in kubernetes `pod` that has a powerful "library" of verbs which do "things" to it. But I'm pretty sure this line of thinking falls apart because e.g. an `autoScaler` may act upon `replicationController` meaning this one-nouns many-verbs idea is fiction...

**Comment by thockin** [comment]
One could argue that service is just another controller - watching pods and
manipulating endpoints...

**Comment by jasonkuhrt** [comment]
> One could argue that service is just another controller - watching pods and
manipulating endpoints...

Exactly

**Comment by jasonkuhrt** [comment]
I rescind `podlicator` in favour of `replicator`.

**Comment by jasonkuhrt** [comment]
I wonder if `replicator` could not just replicate `pod`s but act as a primitive `loop`-like construct for any infrastructure objects?

**Comment by davidopp** [comment]
Clayton used "rcs" to abbrevation "replication controllers" in another issue just now, which gave me an idea. Do we really need a name? Why not just an abbreviation with no attempted explanation of what it stands for? I'm quite serious. We can just call the thing the RC. Note for example that there is a restaurant chain called KFC; some people know why, but anyone born in the 1990s or later has no idea that it used to stand for something, and doesn't care. Same deal with lots of other abbreviation names.

**Comment by satnam6502** [comment]
maintainer since it tries to maintain the specified invariant.

**Comment by bgrant0607** [comment]
@davidopp Interesting idea. `rc` is already used as an abbreviation in kubectl, and RC has the vague implication of "remote control", which isn't too far off. But I'm concerned it may be too obscure.

I'm thinking about how we want to name all of the controllers using a consistent approach. Maybe Server* (for replication controller), Daemon* (for per-foo controller), Task* (for job controller; or maybe Batch*), and Cron*, where * could be either Set, Group, Job, Controller, Manager, Overseer, Master, Lord, Keeper, etc. Job has the benefit of being the shortest, and also may be familiar to users who've used queuing systems (LSF, etc.). ServerJob is less than half the length of ReplicationController. I kind of like Master, though it's a little longer: ServerMaster, DaemonMaster, TaskMaster, CronMaster.

**Comment by thockin** [comment]
In my mind "server" has always meant a machine.  I have never reconciled to
Google's use of the word.  And Server and Daemon and Task are just not
clear enough.

**Comment by bgrant0607** [comment]
Client/Server?

No short terms are going to be 100% precise.

**Comment by bgrant0607** [comment]
Also: http://searchsqlserver.techtarget.com/definition/application-server

**Comment by thockin** [comment]
appserver is a much clearer term because of the additional qualification.
I'm the worst sort of person - I am not very good at names (lmctfy) but I
have an opinion on everyone else's choice :)

I don't hate replication controller or replicator

**Comment by bgrant0607** [comment]
Definitely not lmrtfy. :-)

**Comment by derekwaynecarr** [comment]
From our perspective on OpenShift, we want to not hide underlying Kubernetes concepts and terminology.  RC lacks any meaning and I worry we would have real trouble with that as a piece of terminology.  Whatever is settled upon on this thread, an acronym should not be the final outcome.

**Comment by jasonkuhrt** [comment]
What @derekwaynecarr said, except from a direct Kubernetes user POV not even OpenShift.

**Comment by bgrant0607** [comment]
I'm leaning towards the FooMaster pattern, which is a very common pattern internally (e.g., MapReduceMaster, BigtableMaster) and conveys a similar degree of activeness as "controller". If we have an all-in-one controller, then PodMaster. Otherwise, ServerMaster (or possibly ReplicaMaster -- as in fungible service replicas), DaemonMaster, TaskMaster (almost makes up for not choosing DaemonLord :-)), CronMaster. `/servermasters` is 13 characters, and `/replicamasters` is 14 characters, which admittedly has the benefit of similarity to the existing name. `/replicationcontrollers` is 22 characters.

**Comment by bgrant0607** [comment]
I propose 1/14 as the deadline for bikeshedding on this topic. The reigning proposal is ReplicaMaster.

**Comment by jasonkuhrt** [comment]
What is the main argument against `replicator` again? I think it would be a shame if something short can't be achieved; most of all something that avoids multiple words. Its a legitimate pain to know where things are camelCase or not, and when its not, how it transforms `"-"`,`"_"`,`""`, etc. ugh

**Comment by thockin** [comment]
Jason: But we expect to see multiple kinds of controllers, so having it be
<specific>Thing is useful.

**Comment by jasonkuhrt** [comment]
@thockin Ok clear.

**Comment by bgrant0607** [comment]
Going once, going twice, ...

**Comment by thockin** [comment]
I'm "meh" on "master", and I don't hate controller (it's really the right word) but I abdicate.

**Comment by bgrant0607** [comment]
@thockin "Controller", unqualified? That's not compatible with separate, narrow-purpose controllers. I'm open to alternatives to FooMaster, but have exhausted the thesaurus -- see my proposed alternatives above. I could live with ReplicaSet, which has the benefit of being even shorter. That wouldn't work for Cron, but would work for the other proposed controllers (DaemonSet, TaskSet). Alternatively, ServerJob, DaemonJob, BatchJob/TaskJob, CronJob.

The other main alternative would be to abandon the pattern and go for more idiosyncratic names for each type of thing, though I haven't thought of a specific proposal along these lines, other than just "Job" for a set of terminating tasks (restart on failure pods).

**Comment by abonas** [comment]
I still don't understand what's wrong with replicator. This is what it does. If there will be something else doing something different, there will be another entity and it will be named accordingly.
It is difficult enough with the rest of the names too, for example "pod" doesn't explain anything about what it is. Why isn't it called "containers group" or something similar?

**Comment by jasonkuhrt** [comment]
@abonas The argument against `replicator` is most recently summarized here https://github.com/GoogleCloudPlatform/kubernetes/issues/3024#issuecomment-69440602. As for `pod`, I'll defend that. All names are rooted in essential arbitrariness, at best maybe so-named for some human experiential effect, the sounds therein, etc. Creating a new term for the atom of Kubernetes is totally fine, especially one that reduces the word to three characters whilst having a decent visual and behavioural meaning correlating to use in practice. Nothing in the word `pod` precludes the notion of `containers group`. The arbitrary part in Kubernetes that must be wrote memorized is that `pod`s house `containers`. That is a small task indeed for a lot of gain.

**Comment by bgrant0607** [comment]
More thoughts after an IRL discussion:
* We should only change the name if there is significant benefit, since changing it will not only be work for us but will cause user disruption.
* Unfortunately, ReplicationController is not only long (which is mitigated somewhat by kubectl abbreviations), but doesn't sufficiently distinguish it from other controllers (daemon/per-node and job/task, in particular), now that we've decided to go with the separate-controller model.
* If we do change the name, there is some benefit from similarity to the current name.
* Active-sounding appellations, such as Controller or Master, (a) are different in style from our other objects for no justifiable reason (since all objects have active control loops) and (b) cause confusion when discussing the implementation of those objects (cf. controller-manager). In particular, Master causes confusion vs. the apiserver and/or "master node".
* We will have controllers, at least as plugins, that don't adhere to any particular pattern we establish, such as FooController or FooMaster. AutoScaler is one example. Again, since being able to reflect on the relationships between objects has already been determined to be necessary (see #3058), having "controller" or somesuch be part of the name is neither necessary nor sufficient.
* Names that describe control over a process (e.g., "replication") are (a) unlikely to accurately reflect the full responsibilities of the object and (b) longer than ones that describe control over nouns. Note previous discussion about Replicator vs. Overseer. IMO, replication isn't even the primary responsibility of ReplicationController. It's a side effect of an entity responsible for self-healing. Additionally, the distinction between "replication"  and "scaling" (i.e., auto-scaling) is hard to explain.

Taking all of this (and prior discussion) into account, I do advocate that we change the name, and I propose ReplicaSet, where "Replica" refers to a fungible (app)server replica. We can argue about the names of the other controllers when those PRs are picked up again.

**Comment by jasonkuhrt** [comment]
I am ok with `ReplicaSet`. Could there be any interest in `PodSet`? I'm assuming there's something preferable about `ReplicaSet` but not quite sure what it is.

**Comment by jbeda** [comment]
*Please* let's not do `ReplicaSet`.  This implies a level of ownership vs. arms length management.  The active component is important here.

**Comment by jasonkuhrt** [comment]
Haha I'm going to shut up.

**Comment by jbeda** [comment]
Also, the relationship between Pods and Containers is very different than the relationship between ReplicaControllers and Pods.  Pods *own* Containers in a very hierarchical way.  There is no way to either (a) recreate what a pod does or (b) replace the pod without also replacing the containers.  With ReplicaControllers I can both (a) reimplement it from the outside and (b) delete the ReplicaController and replace it with SuperDuperReplicaController without recreating the pods. 

Similarly, Services are aren't active objects like ReplicaControllers either.  They don't automatically create/delete objects on behalf of users.  If, for example, a Service was in charge of scheduling pods to act as proxies, we probably would have called it a "ProxyController" instead.  But it doesn't so we didn't.

**Comment by bgrant0607** [comment]
@jasonkuhrt PodAnything is not sufficiently distinguishing in a world of multiple similar-but-different pod controllers.

**Comment by thockin** [comment]
Brian,

Thanks for the deep analysis.  I can buy your arguments, though I do see
Joe's point: ReplicaSet has a static connotation. Replicator is the same
length (win) and active (win).  If we strive for active things having
active names, Replicator wounds good to me.

Tim

**Comment by bgrant0607** [comment]
@jbeda I agree that arms-length vs. owning is an important distinction to convey. To me, "Set" implies relatively loose coupling. 

I disagree that the level of "activeness" is significantly different. The endpoint-controller part of set does actively monitor and change the set of reported endpoints, as well as affecting what traffic goes to which pods. 

I also agree that ReplicationController (and Autoscalers, Cron, etc.) could be built by third parties -- only pods and services control the underlying infrastructure.

ReplicaController is not sufficiently better than ReplicationController to be worthwhile. @thockin Replicator doesn't solve any of the problems other than length.

Naming is hard. Enough energy and time has been put into this, and today was the deadline. Let's just not rename it, then.

**Comment by thockin** [comment]
I don't see what ReplicaSet has that Replicator doesn't?  I already
abdicated my vote, anyway.

**Comment by bgrant0607** [comment]
@thockin That was covered by the last bullet here: https://github.com/GoogleCloudPlatform/kubernetes/issues/3024#issuecomment-69989200

**Comment by bgrant0607** [comment]
I'm writing a User Guide. ReplicaSet is self-explanatory in a way that ReplicationController and Replicator are not. I'm changing ReplicationController to ReplicaSet in the v2 API #8190. We're going to end up hiding it with higher-level APIs (Deployment -- #1743) and/or tooling, anyway.

**Comment by jbeda** [comment]
I still very strongly disagree on `ReplicaSet`.  I think it implies a level of ownership that doesn't actually exist.  And if higher level tooling is going to mask it anyway why not leave it alone and thereby (a) not introduce confusion with a name change and (b) pick the most accurate name for what the thing does?

**Comment by bgrant0607** [comment]
Objection noted.

kubectl delete rc already recursively deletes pods by default. I plan on making this the default for ReplicaSet, also.

ReplicationController is confusing for users and for developers, and makes the system sound more alien than it is. 

Other reasons for the change are described above: https://github.com/GoogleCloudPlatform/kubernetes/issues/3024#issuecomment-69989200

**Comment by jbeda** [comment]
I disagree and I think you are creating more confusion by renaming it.

I would structure `kubectl delete rc` differently.  If pods still exist and no flag is specified it would error out.  Other than that, users would have to pass an `--orphan-pods` flag or `--recursive` flag.

I'm obviously not going to convince you of this though.

**Comment by ghodss** [comment]
I agree with the rename to ReplicaSet for pretty much every reason Brian listed in https://github.com/kubernetes/kubernetes/issues/3024#issuecomment-69989200. My top personal reasons:

* Everything else in the API is an inert thing (e.g. Pod), not something that actively does something (e.g. ReplicationController). This is further solidified with the choice of Deployment as the object that otherwise should have been called Deployment Controller.
* It's shorter. :)
* The controller terminology is overloaded by controllers (which run in a control loop and affect state of the system, e.g. node controller) and a replication controller (which is an inert object that sits in etcd). The new name of the current replication controller daemon should be replica set controller, which is much cleaner.

Aesthetically, I like Replicator more than ReplicaSet, but I think it's more important that the object is not an actor, so ReplicaSet is better.

**Comment by lavalamp** [comment]
I would also like to see a name change, to help disambiguate the object in the system (currently replicationController) from the thing that makes the changes to the system (no official term; "replication controller manager" is probably clearest).

**Comment by bgrant0607** [comment]
New strategy proposed on #341: Create a new ReplicaSet API (with several incompatible changes), leave ReplicationController alone, and EOL ReplicationController when we EOL the v1 API.

**Comment by smarterclayton** [comment]
ReplicaSet is an incredibly superior name to ReplicationController

**Comment by smarterclayton** [comment]
@jbeda to your point about ownership, practically RCs have a stronger ownership of the pods under their set selector than I think our documentation and initial design proposals makes them out to be.  The fact that they cannot overlap, need to be annotated to track the creator to protect against overlap races, and that having a stray pod in an RC is so much work for a client to set up has led me down the road of treating them as the unit of abstraction *over* the pods rather than unit of abstraction *next to* the pods.

**Comment by davidopp** [comment]
ReplicaSet is much better than ReplicationController. I'm definitely in favor of this change.

I'd like to see us also standardize on the naming scheme for the other thing @lavalamp brought up: "the thing that makes the changes to the system." (Note that this thing is not an API object.) I think "controller" is fine here. Renaming ReplicaController to ReplicaSet will let us start using "controller" to unambiguously describe the logic (e.g. replica sets controller, daemon sets controller, etc.); we already did this for daemon set (https://github.com/kubernetes/kubernetes/blob/fa86f0749d604fd93c0287b820fb4a83207e33fa/pkg/controller/daemon/controller.go#L51)

**Comment by jbeda** [comment]
*sigh*  I yield :)

**Comment by smarterclayton** [comment]
I thought we settled on "controller" being that name a long time ago :)  So
I completely agree that things that act on the system in response to state
change (via the API or in external systems) are controllers.

**Comment by alex-mohr** [comment]
My bikeshed contribution: as the number of other types have proliferated (job, task, deployment, etc) -- and my reading of the tea lives says we'll only see more going forward -- perhaps with a rename it's time to make the Pod part of the replica set explicit?

That is, call it a PodSet.

I'm sure to all of us it's amazingly clear that of course it's pods that are replicas, but for someone coming to k8s for the first time, it's more self-evident what a PodSet is than a ReplicaSet.

**Comment by davidopp** [comment]
I think the problem with PodSet is lots of controllers manage sets of pods (daemon, job, RC, etc.). ReplicaSet is no better on this front, but PodSet doesn't seem any better and thus not easy to justify renaming.

**Comment by derekwaynecarr** [comment]
I am fine with ReplicaSet, but another option is to just drop Set altogether.

Process - N pods that run forever

Daemon - N pods spread by node that run forever in background

Job - N pods that run to completion

I do worry Set is redundant and may also get annoying if it becomes a common suffix.

**Comment by bgrant0607** [comment]
(Catching up on filtered notifications.)

@derekwaynecarr Process is very ambiguous. We started with Daemon but decided to add "Set" due to ambiguity between the controller resource and individual instances, in docs, comments, code, etc. We are using Job (as opposed to, say, TaskSet).

FYI for everyone not filtering this: Since we're going to be pushing Deployment as the main resource to use for continuously running apps, I proposed to use ReplicaSet for that and use Replicator for the new RC: https://github.com/kubernetes/kubernetes/issues/1743#issuecomment-144881062

**Comment by karlkfi** [comment]
Heh, seen this naming problem everywhere I've been. 

Process is just too generic. A process is anything that executes for any duration of time.

CloudFoundry Diego calls short things Tasks and long things LongRunningProcesses (LRPs). 

CF BOSH calls everything a Job (please dont do this). 

I personally prefer `Daemon` for something that runs until stopped. Task or Job is ok for something short-lived.

Tho in this context it makes more sense to talk about a Pod of Daemons and a Pod of Tasks, or DaemonPods & TaskPods when grouped.

**Comment by karlkfi** [comment]
+1 for Replicator

PodReplicator is a close 2nd, but I prefer single word resources at the top level API, at least until we actually need to replicate other resources with a common API.

**Comment by abonas** [comment]
> +1 for Replicator
> 
> PodReplicator is a close 2nd, but I prefer single word resources at the top level API, at least until we actually need to replicate other resources with a common API.

+1 for Replicator. 
BTW ManageIQ's Kubernetes provider already calls them replicators.

**Comment by davidopp** [comment]
Let me reiterate my opinion: I think that resources representing collections should either have names that sound like a collection of objects, or names that sound like a thing that manages collections of objects. We should be consistent and not use a mixture of the two across different collections.

So it should either be Job/DaemonSet/ReplicaSet or JobController/DaemonController/Replicator.

**Comment by karlkfi** [comment]
I would agree, David, but I don't think this IS a set of pods. It's a single pod factory with a template for producing more of one kind of pod. It's also it's own daemon that watches those pods and makes new ones when necessary. It's NOT a group of pods, which makes it distinct from the way borg works. 

-Karl

**Comment by karlkfi** [comment]
There's already a"pod set" too. It's called PodList. 

-Karl

**Comment by karlkfi** [comment]
The other distinction between JobController and ReplicationController is that RC's are created by users. I think the fact that it makes a controller is an implementation detail that the end user shouldn't have to know about. It could continue to be implemented as ReplicationController, as long as it's exposed to the user with a friendlier name. The dev and operator are the only personas that should have to know its implemented by a controller.

That said, this isn't java. We don't need all our objects to say what kind of interface they satisfy in their name.

Also, a good interface is similar but not identical to the implementation. The API needs to be flexible enough to change when it improves usability without being tightly coupled to the architecture or impl details.

**Comment by davidopp** [comment]
> It's a single pod factory with a template for producing more of one kind of pod. It's also it's own daemon that watches those pods and makes new ones when necessary.

How is this different from DaemonSet or Job? They're all pod factories that also manage the lifecycle of the pods they create.

**Comment by karlkfi** [comment]
I'm not an expert in either.

The only clear difference between DaemonSet and RC seems to be the constraints that can be placed on the creation of pods. Both are constrained by node constraints but a ReplicationController can also have a desired number of pods independent of nodes and DaemonSets have an implicit maximum per node. I may be ignorant, but I don't see why they're not just the same thing with multiple optional constraint types. 

As for Job, I think it's well named and exemplifies my point. A Job is a singular abstraction that creates Pods with a logical policy and a set of constraints.

**Comment by karlkfi** [comment]
In fact, now that I think about it, if I were really going to clean house (in a reverse incompatible way) I'd combine DaemonSet and ReplicationController into one API resource and call it a Daemon, singular. That way it simplifies the abstractions down to just Daemons and Jobs. Daemons run till you stop them. Jobs run till they complete successfully.

**Comment by davidopp** [comment]
@karlkfi I would agree with you about combining DaemonSet and ReplicationController, but we are planning to move DaemonSet into the NodeController, so I think it makes sense to keep them separate.

Anyway, my point is that all three (D, R, and J) are "pod factory with a template for producing more of one kind of pod [and] it's own daemon that watches those pods and makes new ones when necessary" so they should be named in a parallel fashion.

**Comment by karlkfi** [comment]
> we are planning to move DaemonSet into the NodeController

Why?

> they should be named in a parallel fashion

Agreed. 

Is it possible to move to a world of just Daemons and Jobs or is that going to be impossible with reverse compatibility concerns and "daemon" already being used for a narrower concept?

**Comment by davidopp** [comment]
> Why?

To make it easier for it to put the daemons on newly-added machines before any scheduler can jump in and schedule something there, possibly blocking the daemon from scheduling. (Even if we had preemption, doing this in node controller allows us to avoid the preemption.)

> Is it possible to move to a world of just Daemons and Jobs or is that going to be impossible with reverse compatibility concerns and "daemon" already being used for a narrower concept?

My main concern is the latter; when you read the code, documentation, comments, etc. it is really confusing to see "daemon" sometimes used to mean the traditional thing (the process that runs) and sometimes used to mean the API object/resource representing a collection of (traditional) daemons.

**Comment by karlkfi** [comment]
> it is really confusing to see "daemon" sometimes used to mean the traditional thing (the process that runs) and sometimes used to mean the API object/resource representing a collection of (traditional) daemons.

Um, yes... Repurposing a term to mean something new is always going to cause intermediate confusion. It's only worth doing if the end state is sufficiently less confusing.

If the controllers are implementation details, however, the user can still conceptually create a Daemon and let k8s decide how to make that happen. 

The difference to the user then is just "one per node + as many as possible total + high priority" vs "any number per node + exactly N total + low priority". High priority Daemons would be scheduled first, by the NodeController or Kubelet or however you want to implement it. "Priority" may or may not be the term you want to use; it could be a flag or something.

**Comment by bgrant0607** [comment]
@karlkfi More history about the separation of DaemonSet and ReplicationController is in #3058, if you're interested.

**Comment by bgrant0607** [comment]
We need to create a new controller in order to adopt the new label selector:
https://github.com/kubernetes/kubernetes/issues/341#issuecomment-140809259

Back to original plan:
ReplicationController replacement should be called ReplicaSet
Deployment will not be renamed.

**Comment by mqliang** [comment]
Is there anybody working on this now? If not, I'd like to volunteer myself to do this work.

**Comment by madhusudancs** [comment]
@mqliang I am working on it. You can follow the progress here - https://github.com/madhusudancs/kubernetes/commits/deployment-pod-selector I haven't pushed my latest changes yet. I will do so soon. I am fixing up e2e tests for Deployments.

**Comment by bgrant0607** [comment]
@mqliang If you'd like to help, kubectl get/describe haven't been implemented yet for ReplicaSet.

**Comment by mqliang** [comment]
@bgrant0607 I send a PR https://github.com/kubernetes/kubernetes/pull/20886 to implement kubectl get/describe. I am not very familiar with kubectl, hoping I have not miss anything.

**Comment by bgrant0607** [comment]
Remaining tasks should be covered by more specific issues.
