### ISSUE TITLE
Creating ext4 filesystem on empty network volumes takes long time

### ISSUE THREAD

**Issue by rootfs** [kubernetes/kubernetes#30240]
According to [RHEL doc](https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/6/html/Performance_Tuning_Guide/s-storage-fs.html):

``` text
For very large file systems, the mkfs.ext4 process can take a very long time to initialize all inode tables in the file system. This process can be deferred with the -E lazy_itable_init=1 option.
```

While the [default](https://github.com/kubernetes/kubernetes/blob/master/pkg/util/mount/mount_linux.go#L335) is exactly the opposite. 

This significantly slows down large ext4 volume creation.

**Comment by rootfs** [comment]
@kubernetes/sig-storage

**Comment by matchstick** [comment]
@kubernetes/sig-storage  
This might be worth bringing up at the storage f2f coming up.I am going to add to the agenda.
This is an interesting approach to what I think may be a few larger issues. 

Questions and thoughts:

- What is a good SLO for mkfs?
- If the SLO is going to be violated due to size should k8s do something or should the user pre-format?
- There are tradeoffs for initting the filesystem lazy or not. Supporting all the options for a user may require an API change. Is this a persistent volume only thing?

**Comment by jsafrane** [comment]
I may miss something, but `mkfs.ext4 -E lazy_itable_init=0,lazy_journal_init=0 -F /dev/sdc` on a random GCE node with 500GiB magnetic(!) disk and Fedora 24 takes around 2 seconds.

ext3 is a different story, it takes 74 seconds.

**Comment by matchstick** [comment]
@jsafrane @rootfs I cannot imagine any reason why anyone would be installing ext2/ext3 on a 500GB drive. If they do they should be expecting things to be slow. 

In any case knowing what the SLO is is still not a crazy idea.

**Comment by colemickens** [comment]
@rootfs I manually ran `mkfs.ext4

**Comment by rootfs** [comment]
@jsafrane This is probably not a big problem with GCE, since GCE PD's IOPS is per GB. This is mostly a problem for EBS/Cinder/Azure, since the IOPS per volume is fixed.

**Comment by thockin** [comment]
If we're going to do this at all, we should really think hard about this problem top-to-bottom.  Ext3 vs ext4 vs other FS?  Myriad filesystem options, etc.

**Comment by jsafrane** [comment]
I got bitten by this when implementing e2e tests for all supported storage class options on AWS. "Cold HDD" volume type has max. 250 IOPS and the smallest one is 500 GB. It takes 3-4 minutes just to format the volume, which slows down the test quite considerably.

Was there any conclusion on f2f meeting?

`lazy_itable_init=0,lazy_journal_init=0` was added in commit ab0258f2598d05c61a67cb5694373de14b32d7c8, which claims to be https://github.com/GoogleCloudPlatform/compute-image-packages/blob/master/google-startup-scripts/usr/share/google/safe_format_and_mount rewritten to Go. Original script not exist any more on the link above. Was there some smart idea in original `safe_format_and_mount`?

**Comment by rootfs** [comment]
see some inconclusive investigation at https://github.com/kubernetes/kubernetes/issues/30752

**Comment by codablock** [comment]
Please take a look at https://github.com/kubernetes/kubernetes/issues/30752#issuecomment-261303142 

I encountered not only performance issue due to lazy_itable_init=0, but also oom situations and thus killed processes. To to the amount of data written to the disk, all free memory gets filled with dirty buffer cache.
