### ISSUE TITLE
Kubernetes creates PVs in wrong AWS zone

### ISSUE THREAD

**Issue by jsafrane** [kubernetes/kubernetes#30265]
When dynamically creating a PV on AWS, Kubernetes sometimes create the PV in a zone that has no running nodes.

Looking at `getAllZones()` in https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/aws/aws.go#L951, it lists all AWS instances in a project to get list of allowed zones. But this code does not check that Kubernetes is running on any of these instances! There may be other services running there or even separate Kubernetes cluster [and yes, we're hitting this case as we share one AWS account among many developers for their tests].

IMO, it should list Kubernetes nodes that are `Ready`.

In addition, choosing a zone randomly severely hurts performance as scheduler has no clue about this and may choose to run a pod with this PVC on a node in distant zone. Can we limit this dice roll only to petsets before a smarter scheduler is implemented?

@justinsb

**Comment by justinsb** [comment]
OK so a few things here:

* On AWS you must tag your resources with the KubernetesCluster tag.  You can run multiple clusters in the same VPC, mix workloads etc, as long as you tag.

* Deeper scheduler integration would indeed be nice.  In the meantime, not forcing everything into the master zone is the first order problem, and I don't think we should lose that.  I'm not sure what you mean by a "distant zone" though - all zones in a region are relatively close to each other in AWS.

* Checking for ready or not is an open question.  We don't want to overload a zone, and I expect the set of zones to be relatively static for most configurations, so I came down on the side of not checking.  Also, the default for PetSets is likely to be different for a one-off.  It's not a trivial call, and I'm happy to review it.

**Comment by justinsb** [comment]
Removing P1 - with tagging, this is not a blocker for 1.4 release.

**Comment by eparis** [comment]
I'm not sure what 'PetSet' has to do with it.

@justinsb how about instead of calling the AWS API at all we look at all Kube nodes and look for the 'zone' label on the node. Thus we will know that whatever zone is picked is actually running a kubelet.

If I run a single VM in east that has nothing to do with kube and I run a kube cluster entirely in west if we get the 'zones to randomly pick from' from the node labels instead of from the AWS API we won't get this wrong...

**Comment by justinsb** [comment]
@eparis that is a good idea, but we don't have access to the API in the cloudprovider (last I looked!).  I would love it if we did though - it would save us a bunch of API calls!

But the scenario you suggested isn't right.  All AWS APIs are region-local, so you'll never cross east <-> west.  As long as you tag, if you have a cluster in us-east-1b, even if you have other clusters running in other zones, volumes will only be in us-east-1b.  You can run non kubernetes workloads in other zones also and we still won't pick them up, because they also won't be tagged.

Ideally we would make failure to tag on AWS a hard failure (i.e. refuse to start kubelet), but it does serve as a useful canary: if your AWS cluster isn't tagged likely then likely it is broken in more subtle ways also :-)

**Comment by jsafrane** [comment]
@justinsb, tagging helped a lot, thanks

**Comment by justinsb** [comment]
@jsafrane are you OK if I close this issue?

**Comment by jsafrane** [comment]
sorry, I should have closed it a long time ago
