### ISSUE TITLE
kube-proxy for Windows

### ISSUE THREAD

**Issue by jbhurat** [kubernetes/kubernetes#30278]
As work progresses on the POC to support Kubernetes on Windows, we should start looking at supporting kube-proxy on Windows as well. 
- Investigate the feasibility of implementing kube-proxy on Windows
- If feasible implement kube-proxy for Windows
- if not suggest alternatives

**Comment by jbhurat** [comment]
Did some initial investigation on the different modules present in Windows to support kube-proxy like functionality and below are the finding,

- kube-proxy extensively uses **nat** and **filter** tables along with Chains to provide the functionality, there is no equivalent on Windows
- Investigated netsh, Network Security powershell commands and Windows Filtering Platform (WFP)
-  netsh is deprecated and it is advised to use powershell commands instead
- Network Security powershell commands allows to create basic firewall rules and their associated lifecycle
- Windows Filtering Platform (WFP) is a set of APIs and system services that provide a platform for creating networking filtering applications.
- We can use either WFP APIs or Network Security powershell commands to create a basic iptables equivalent and I am currently working towards evaluating these to see if they can fit the kube-proxy requirements.

@brendandburns, can you please advise if this is the right direction to move forward

**Comment by brendandburns** [comment]
So the initial MVP of the `kube-proxy`  did end-to-end TCP/UDP proxying, meaning the mapping was from kube-dns IP -> `localhost:<random-port` and the kube-proxy did all of the forwarding inside of the kube-proxy application.

The code is still in there:
https://github.com/kubernetes/kubernetes/tree/master/pkg/proxy/userspace

There are lots of drawbacks to this approach (higher tail latency, lots of CPU usage from the user space proxy) but it is way simpler to build.

I recommend that we start there, and use the simple PowerShell commandlets to map `<service-ip>:<service-port>` to `localhost:<random-port>` which then forwards on to the appropriate Pod.  That's going to easier to get going than to port the entire existing IPTables proxy.

Once we get that going, we can then investigate other solutions for improving it's performance.  That's the approach we took with Linux as well.

It's also worth taking a look and seeing if we can use Azure internal load balancing for this, since ultimately the kube-proxy is just a way to implement internal load balancing.  If a cloud vendor (like Azure) provides internal load balancing, we should see if we can just program that.

**Comment by jbhurat** [comment]
Thanks for the insights @brendandburns, I will take a look at these

**Comment by jbhurat** [comment]
Hi @brendandburns,
I started with trying out the above approach manually first to see the options available to make it work, and I have been able to make it work using the below approach. Please let me know your thoughts,

- Add Service IP to an existing network adapter

`netsh interface ipv4 add address <IF Index> <service-ip> <service-ip-mask>`
- Redirect `<service-ip>:<service-port>` to `<localhost>:<random-port>`, kube-proxy (LB) listens for connections on that local `<random-port>` and decides to forward the request to an appropriate POD based on session affinity or other criteria. 

`netsh interface portproxy listenaddress=<service-ip> listenport=<service-port> connectaddress=<127.0.0.1> connectport=<random-port>`

`netsh interface portproxy listenaddress=<127.0.0.1> listenport=<random-port> connectaddress=<pod-ip> connectport=<pod-port>`

**Comment by brendandburns** [comment]
Yeah, that seems like it should work, especially for an MVP.

I'm trying to connect w/ the Windows networking folks on this side to see what the replacement for netsh would be, but for now, let's just go with that.

Thanks!
--brendan

**Comment by jbhurat** [comment]
Sounds good. Thanks

**Comment by jbhurat** [comment]
Hi @brendandburns, I had a question regarding firewall and would like to know your thoughts,
Firewall rules need to be added for the following
-  For each POD endpoint, a rule has to be to accept incoming request
- A firewall rule has to be added to accept connections on the NodePort
- A firewall rule has to be added to accept incoming requests for the kubelet port

We can either have Kubelet/Kube-proxy implementation define these rules or have them part of the cluster setup (We can define rules to accept connections for the cluster CIDR). Can you please share your thoughts. I have also created a post on #sig-network google group page for their advice https://groups.google.com/forum/#!topic/kubernetes-sig-network/-npgm1GIFz0
