### ISSUE TITLE
Avoid putting new controllers into kube-controller-manager

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#30329]
We should not put new controllers into kube-controller-manager, unless a compelling reasons exists why it can not or should not be a separate controller.

We've had this as an implicit consequence of a lot of things we are working on: splitting up the code into separate repos, making kubernetes easier to install, and splitting out controllers or cloudproviders.  Many new features have been written following this approach (ingress, network policies etc).  But @mikedanese pointed out that we don't have an issue that explicitly states it.

By doing this we will:
- Keep "core" kubernetes leaner and cleaner, more reliable, and easier to understand.
- Make it easier for us to split code into separate repos if we decide to do that down the road
- Make these controllers easier to replace, and make it easier to write a replacement controller by modifying the "reference" controller.
- Make kubernetes itself easier to install.  This may be counter-intuitive, but a big part of the reason why k8s is difficult to install is when we don't use our own API to manage things, users can't use our own API to replace things.  For example, if you're replacing a networking controller, we must also turn off the controllers in KCM, which then requires flag management.  If we could just replace a daemonset this would be much easier.  The less functionality that must be configured to get to the kubernetes API "boot-prompt", the easier installation will be.

We obviously have not followed this principle in the past, but I do not know of a single controller in KCM that I haven't seen someone propose that we split out or have a flag to turn off :-)

Ideally we would split out the existing controllers, but starting with new controllers where there is no compelling reason to put them into KCM seems like a good first step.

**Comment by mikedanese** [comment]
cc @davidopp @bgrant0607 @thockin @smarterclayton @kubernetes/goog-control-plane

**Comment by thockin** [comment]
I sort of disagree.  For places where the controller needs to be pluggable, such as ingress, it makes sense to be out-of-core.  For cases where the controller will never really be replaced (e.g. service, volumes, etc) the only effect of putting it outside is more moving parts for people to comprehend.

**Comment by bgrant0607** [comment]
Before we do this, we need to ensure there is a generic way to get all clusters to run some addons by default. If not, we'll break all clusters every time we add a new required component.

**Comment by bgrant0607** [comment]
cc @kubernetes/sig-cluster-lifecycle

**Comment by timothysc** [comment]
> the only effect of putting it outside is more moving parts for people to comprehend. 

Debugging an issue of a single controller from the assortment of cross-cutting behaviors has become obtuse at best now-a-days.  It's compounded by the fact that we are sharing data, notifications, and locks now.

**Comment by smarterclayton** [comment]
I think the rule of thumb here is somewhere in the middle ground of "all split" or "all shared".  It should probably be grouped by:

* Common data set (multiple controllers dealing with pod lifecycle exclusively)
* Common objectives (things that deal with volumes)
* Things that are bulk "replaced" should be split out (scheduler)
* Split because they depend on external tools that change at different rates or are not coupled to the core system.

This exactly parallels a similar debate on API groups - what resources should be in a similar API group, and which ones should be in their own API groups.

I agree with @thockin that every moving part needs to justify itself.  If someone needs to disable a specific controller occasionally, we shouldn't split it out just because of that.    Every split out config means a config migration.  Every new controller process means a new config file with lots of common flags.

OpenShift today runs all Kube controllers, all OpenShift controllers, and the scheduler in one process.  We'd like to split out Kube controllers and scheduler, but all of the cut lines seem like they are on "group" boundaries rather than "individual controller" boundaries.  

How about we define a set of criteria for controllers that should be split off, and ask that on new controllers and existing controllers, and make sure the first one we do has the right standard code so that it's also not reinventing the wheel (we still haven't succeeded at that for API servers).

**Comment by bgrant0607** [comment]
Layers doc (join kubernetes-dev to access):
https://docs.google.com/document/d/1XkjVm4bOeiVkj-Xt1LgoGiqWsBfNozJ51dyI-ljzt1o/edit#

**Comment by bgrant0607** [comment]
We shouldn't need resource-specific support in the add-on manager, and we need to get away from round-tripping the resources in kubectl.

We're planning to put apply support in apiserver: #17333, #12143 

And we need to add strategic merge info to the OpenAPI schema: #25716

**Comment by jszczepkowski** [comment]
FYI @kgrygiel

**Comment by vllry** [comment]
Would be good to follow up with the cloud-provider out-of-tree split and see if there's lessons to be learned.

**Comment by thockin** [comment]
Closing old issues that are unlikely to be useful any further.
