### ISSUE TITLE
Publish Chocolatey package for kubectl

### ISSUE THREAD

**Issue by mcandre** [kubernetes/kubernetes#30403]
Please publish kubectl to [Chocolatey](https://chocolatey.org/) to make it easier for Windows users to install.

**Comment by kpgriffith** [comment]
Looks like this is already done.  https://chocolatey.org/packages/kubernetes-cli

**Comment by xiangpengzhao** [comment]
Thanks @kpgriffith for the information! That's awesome!

/close

/cc @thockin

**Comment by markrj** [comment]
Noticed this while browsing for "help wanted" issues. It seems like this issue can be cleaned up / closed; earlier comments confirmed that this was already done.

See https://chocolatey.org/packages/kubernetes-cli

Also see https://kubernetes.io/docs/tasks/tools/install-kubectl/#install-with-chocolatey-on-windows

@mcandre - could you comment with the close command?

Alternatively, @xiangpengzhao, since you're a member of the Kubernetes org, could you assign this to yourself and then issue the close command? Your earlier attempt was unsuccessful because it wasn't assigned to you.

Thanks!

**Comment by xiangpengzhao** [comment]
@markrj thanks for notifying!
/close
