### ISSUE TITLE
Further improvements for 'kubectl top' command

### ISSUE THREAD

**Issue by mksalawa** [kubernetes/kubernetes#30507]
Follow-up for #11382.

Proposed features for the 'top' command, after heapster is adapted to an apiserver:
- [ ] sorting by column
- [ ] different output methods (yuml/json/gotemplate)
- [ ] watch
- [ ] pasteable output for `kubectl describe`
- [ ] support for additional rollup resource types: services, replicasets/rcs, deployments, jobs, daemonsets, ingress

**Comment by mksalawa** [comment]
cc @piosz

**Comment by piosz** [comment]
@mksalawa is no longer working on this. Help wanted.

**Comment by ajanthan** [comment]
@piosz  I would like to take this.

**Comment by piosz** [comment]
Sure, your contribution is welcome.

**Comment by davidquarles** [comment]
Taking @smarterclayton's #11382 comments a step further, I'd personally love the option to output the resource requests / limits alongside the actual utilization data.  This would yield a quick snapshot of usage, capacity and overcommit in one location.  I'm happy to contribute the changes if that's sane.

**Comment by piosz** [comment]
@kubernetes/kubectl @kubernetes/sig-cli WDYT about https://github.com/kubernetes/kubernetes/issues/30507#issuecomment-263876829?

**Comment by AdoHe** [comment]
```
This would yield a quick snapshot of usage, capacity and overcommit in one location.
```
SGTM.

**Comment by RemingtonReackhof** [comment]
I'm new to this project and would like to take a look at this issue. I've started working on the sorting by column feature

**Comment by piosz** [comment]
@RemingtonReackhof cool, thanks for letting us know.

cc @kubernetes/sig-cli-misc

**Comment by piosz** [comment]
@kubernetes/kubectl-maintainers

**Comment by RemingtonReackhof** [comment]
Due to the differences in accepted object types between the `ResourcePrinter` and the `metrics_printer`, particularly that `RuntimeSort` uses a slice of runtime objects and `metrics_printer` uses `ResourceList`, I think it would be best to define a separate sort for the metrics objects that get passed to `metrics_printer`.

On top of this, I find that the format for values `--sort-by` uses, i.e., the JSON paths, are not applicable to the metrics objects since the cpu and memory values are retrieved by functions on a quantity object. I think a simpler implementation would just specify either `name`, `cpu`, or `memory` to sort by:
```console
$ kubectl top nodes --sort-by=name
```
My proposed solution would have three added types implementing the sort interface, one for nodes, one for pods, and one for containers. Right now they are living in `metrics_printer.go`, but I was thinking of moving them to their own file within `/metricsutil`. Any feedback would be appreciated!
