### ISSUE TITLE
node controller does not evict pods properly

### ISSUE THREAD

**Issue by derekwaynecarr** [kubernetes/kubernetes#30536]
Any of the following scenarios can block `Namespace` deletion:

1. If a node has a single terminating pod, it is never evicted.
 * see deletePod, remaining will always be false if all pods are already terminating, see: https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/node/controller_utils.go#L105
1. If all nodes in a cluster report `NotReady`, no pod is ever evicted, and namespace is never deleted.

The first issue was encountered when the container runtime was corrupted on a 300 node cluster, and an operator manually attempted to delete the pod (without forceful deletion), but was confused why the node controller never fully deleted the pod after the fact.

The second issue introduced here (https://github.com/kubernetes/kubernetes/issues/24597#issuecomment-213106775) while understandable is an edge case that confuses users that are trying to validate the system.  I wonder if its an optimization that leads to more confusion than benefit.  Users expected to see existing pod killed, and a new pod created that just could not schedule.

@kubernetes/rh-cluster-infra @lavalamp @smarterclayton

**Comment by derekwaynecarr** [comment]
To be clear, if anything other than node controller sets `TerminationGracePeriodSeconds` on a pod, the node controller will not evict that pod if its the only pod on the node.

**Comment by derekwaynecarr** [comment]
Related https://bugzilla.redhat.com/show_bug.cgi?id=1364243

**Comment by derekwaynecarr** [comment]
I would like to get a fix in node controller for kube 1.4 that fixes the pod never being deleted iff its only pod on that node and its already terminating.

**Comment by smarterclayton** [comment]
The line of code you copied should be mirrored by "terminatePods" which
does not already ignore pods.  There are two loops - one to ensure pods are
deleted, and one to monitor when they exceed their limit.

**Comment by smarterclayton** [comment]
Nm, I see that you meant "remaining" should be set to true by this loop in
this condition, which it should.

**Comment by lavalamp** [comment]
@gmarek @davidopp 

Number 2 is very much on purpose and if it's problematic for the namespace controller then the namespace controller should provide a fix. It fixes the issue where a network segmentation causes a correlated cluster-wide pod restart, which is a disaster for many people.

**Comment by lavalamp** [comment]
Why can't the namespace controller force-delete pods that are already terminating after the namespace has been in the deleting state for more than (say) 30 seconds?

**Comment by smarterclayton** [comment]
Because that violates the safety guarantees provided to app authors
via grace period.  Just because the node controller can't observe the
node doesn't mean that it can deliver force kills - if the node came
back suddenly grace period would be violated.

**Comment by lavalamp** [comment]
...which is why I added "has been in the deleting state for more than (say)
30 seconds" :)

**Comment by gmarek** [comment]
I guess because there's no upper bound on GracePeriod. CriticalPodRescheduler (whatever the name it currently has) has exactly the same problem with respecting arbitrary GracePeriods.

**Comment by smarterclayton** [comment]
Also NamespaceController.

**Comment by smarterclayton** [comment]
We have customers running tens of minute grace periods.  :)

**Comment by gmarek** [comment]
FYI @piosz

**Comment by davidopp** [comment]
I don't understand the scenario that's being described here (let's just focus on the second one).

What is the connection between deletion and eviction? The feature we added should block pod evictions from NotReady nodes when node controller thinks there is a network partition. But I don't understand why it would affect pod deletions (even with grace period).

My (possibly wrong) understanding of deletion with grace period is that the pod can't ever be deleted if the node is unreachable (since Kubelet does the deletion, and will never find out that the deletion was request), but that behavior has always been there.

Definitely something I'm missing here.

**Comment by gmarek** [comment]
@derekwaynecarr similarly to @davidopp - I don't really understand what problem are you describing and what users are expecting. If all Nodes are NotReady then even if something would get evicted it won't be scheduled anywhere - why users expect us do delete everything if we know there's no place where we could put evicted Pods? As @lavalamp mentioned current logic was introduced on purpose as we already had a number of people complaining about the behavior you want to have (if I understand it correctly). E.g. https://github.com/kubernetes/kubernetes/issues/13412#issue-104149586

I think that what @lavalamp suggested is a good solution for dangling Namespace deletion, i.e. Namespace controller should handle force deletion of unresponsive Pods - it can even try to respect GracePeriod.

The thing we guarantee for GracePeriod is that there's at least GracePeriod between an attempt to send SIGTERM and an attempt to send SIGKILL, not that there's a GracePeriod between actual SIGTERM and SIGKILL - hence the sudden Node's come back is not a problem, as this guarantee is not violated and we can make NamespaceController to respect it as well.

IIUC the real issue is the interaction between GracePeriod and Node being unreachable. That is: what should we do when deleting a Namespace (or any kind of collection deletion) and Node is unreachable so we can't get a deletion confirmation from Kubelet hence the deletion of a top-level object is dangling (e.g. for tens of minutes as NC respects GracePeriod when evicting pods)? My take is that it should be a responsibility for the collection-deletion driver to make sure it actually can finish it's job in reasonable amount of time @caesarxuchao. I don't know how the current implementation of "collection" (RC/RS/Deployment/Job/etc.) deletion in kubectl works...

**Comment by smarterclayton** [comment]
The overall design of this is that everyone who wants to invoke delete = 0 has to follow the same rules, although in some cases we allow specific uses to cap the amount of time that they wait before delete = 0.  The namespace controller already handles force deletion of unresponsive pods.

Delete collection (if you're referring to the bulk delete) is just invoking the same delete operation on multiple resources - it has to follow the same rules to get the same consistent behavior in the system.

The node controller owns node timeout.  A well functioning system expects the node controller to handle when the node is unresponsive, and the namespace controller should allow the node controller to resolve correctly.  Namespace controller should never delete before node controller does.

**Comment by eparis** [comment]
Not a useful comment but this makes me very very yucky/dirty: `The thing we guarantee for GracePeriod is that there's at least GracePeriod between an attempt to send SIGTERM and an attempt to send SIGKILL, not that there's a GracePeriod between actual SIGTERM and SIGKILL`

**Comment by smarterclayton** [comment]
Actually, I'm pretty sure we guarantee that today for Docker, but not for
Rkt.  Would have to double check.  If docker fails in the API call, we will
always preserve that interval.

**Comment by derekwaynecarr** [comment]
@gmarek @lavalamp @davidopp - scenario 1 is fixed in #30624 which should fix any interaction with the namespace controller marking a pod for termination on nodes that were not healthy, and the node controller should now properly evict those pods (assuming there is at least one other healthy node on the cluster).

I understand the rationale behind scenario 2, but it was a surprise for me when debugging scenario 1.  My experience showed that users/testers that ran with a N node cluster, and who unfortunately found themselves with N nodes now unhealthy (in this case caused by storage driver corruption due to kernel bug now addressed) reacted with confusion when they expected to see pods evicted independent of other nodes being healthy in the cluster.  Their expectation was that the pods should have failed, and new pods should have been created by backing controller that are pending schedule.  

When this operator tried to debug the platform, they deleted the namespace that had their pods.  

1. The namespace controller sent the deletion request as expected.  
2. The kubelet (since it was unhealthy) never sent the second delete request to delete the pod.  
3. The node controller never evicted the pods because all nodes were unhealthy.  
4. The namespace controller kept asking for all pods to be deleted.

We could argue that the namespace controller should send a force delete if 2 or 3 never succeed, but the node controller is responsible for observing evictions when nodes are unhealthy, not the namespace controller.  The namespace controller assumes a healthy graceful deletion setup (meaning kubelet performs final delete), and imho the node controller is responsible for handling cases where that is not possible.

At best, we should document that we will not evict pods if all nodes report unhealthy.  The current behavior was only discoverable after a lot of sleuthing a bug ;-)

At worse, the current behavior seems odd 

* if you have a 500 node cluster, all nodes unhealthy, pods stay put.  
* 1/500 nodes are healthy, pods are evicted from all other 499 nodes and never reschedule.

**Comment by derekwaynecarr** [comment]
Reading through the original bug report, this seems to have been induced by poor integration from kubelet with cloud provider that was undergoing an upgrade without HA.  Should we just fix the kubelet instead of changing node controller in ways that dont make a material difference as cluster size grows?  I think 500/500 reporting unhealthy but 499/500 reporting unhealthy causing a difference in behavior is a difference without merit?

**Comment by gmarek** [comment]
This was only an original report. We've seen cases when master machine got separated from nodes and all hell broke loose. We certainly need to document the change and we will do it when we know what to document (there's still a bit of discussion in #30138) - the documentation will certainly be there for the release (I admit that it should have been there for 1.3, but there was absolutely no time to write it and the original PR that was in 1.3 was a quick stopgap).

There's actually huge difference between 499 and 500/500 - in first case we know that *something* can connect to the master, so there's no complete network failure. This make Node problem more probable (e.g. bad config rollout that might have been stopped) than in the 500/500 case, when we just can't hear anything.

To make things a bit more continuous we're drastically slowing down NC evictions when more than 55% Nodes are unreachable.

**Comment by derekwaynecarr** [comment]
@gmarek - I was unaware of the percentage based approach.  That seems like a nice middle-ground.

**Comment by gmarek** [comment]
@derekwaynecarr - as 1) is fixed can we close this issue?

**Comment by ncdc** [comment]
@gmarek #30624 hasn't merged yet (it's in the queue)

**Comment by gmarek** [comment]
Oh sorry - I was sure it got merged in last couple of days... Oh freeze dates...

I checked that it will actually close this issue, so we're golden.
