### ISSUE TITLE
Decide the domain name infix for the Ingress entries in KubeDNS

### ISSUE THREAD

**Issue by madhusudancs** [kubernetes/kubernetes#30544]
Discovery DNS records for services take the form `mysvc.myns.svc.cluster.local.` with `svc` as the constant infix for services. We also want to make ingresses discoverable by publishing their DNS records. PR #29768 already does that. It uses the infix constant `ing` to indicate that a record belongs to an ingress resource. We need to decide if `ing` is the appropriate constant for ingresses.

cc @kubernetes/sig-cluster-federation @matchstick

**Comment by quinton-hoole** [comment]
Thanks @madhusudancs for opening this tracking issue to make sure that it doesn't get lost.  @thockin @matchstick In particular (copy of my review comment in #29768):

@thockin @bprashanth Any objections to this? It's the equivalent to '.svc' for services. _What process do we need to follow to take this out of Alpha? Is it a big enough decision to drag through the networking/API SIG's? I suspect not._

**Comment by quinton-hoole** [comment]
@nikhiljindal and I discussed this with @thockin yesterday, and agreed on using "ing".  A few caveats to be aware of:

1. "short DNS name expansion" will not work for ingresses, due to the fact that we've exhausted the maximum DNS search path length of 6 already.  So e.g. "myingress" will not auto-expand to "myingress.mynamespace.ing.<domain>  This makes ingress somewhat of a second class citizen compared to services (for which the above auto-expansion does work), but we already have this problem for pods (which get DNS names "mypod.mynamespace.pod.cluster.local" but for which auto-expansion does not work).  We have the option, in future, of doing auto-expansion/DNS search path expansion in kube-dns rather than relying on the resolver and search-path in resolv.conf, to get around the length limit of 6 imposed by search-path in resolv.conf.
2.  Currently none of the ingress controllers expose ingresses on a service-ip, so ingresses currently only ever get an external IP.   In such cases, we should not publish a ".ing.cluster.local" DNS name.  Only CNAMES for ".ing.myfederation" style DNS names, as we do for external federated services.

**Comment by quinton-hoole** [comment]
@madhusudancs FYI.

**Comment by thockin** [comment]
as per quinton, "ing" seems fine.  @smarterclayton because DNS

**Comment by smarterclayton** [comment]
Is "ing" really the best we can do?  My argument as a human being is that "ingress" I could maybe understand, but I will never guess "ing" and it looks like a dangling participle.  :)

**Comment by smarterclayton** [comment]
I don't *hate* ing, but it does make me think of things like `myingress.walk.ing.cluster.local` and that makes me think it falls into "cute" rather than "obvious".

**Comment by thockin** [comment]
pod, svc, ing, ept are all pretty obvious.  I think the *real* answer will
be to chain an "external" service onto an ingress IP so that short names
work, so that direct use of ing names will be few and far between.

If we did that nowish, do we still need ing?

**Comment by quinton-hoole** [comment]
@thockin I'm not sure that I fully understand what the API semantics of "ingresses auto-fronted by external services" would be.  I guess it could be made to work, but seems to require more thought than we have time for in 1.4.  The presence of some DNS name for the Ingress is a pre-requisite Federated Ingress, which is in turn planned for 1.4.   

So as far as I can tell, we have a few concrete options:

1. Go with "ing" (or "ingress") as described [above](https://github.com/kubernetes/kubernetes/issues/30544#issuecomment-240773497)
2. Block 1.4 on figuring out how  "ingresses auto-fronted by external services" would  work, and implement the outcome.
3. Kick Federated Ingress out of v1.4, pending resolution of the above.

I think I'm most inclined towards option 1, but the other are also theoretically on the table.

**Comment by thockin** [comment]
I am OK with (1), I don't think it is particularly detrimental to long-term
goals.

(2) won't happen so (3) is the other  choice.  The implication is that when
you create an ingress and you want to give it a DNS name you ALSO create a
Service with `clusterIP: None` and no `selector`, and then create a
same-name Endpoints with a single IP in it.

**Comment by smarterclayton** [comment]
I am not opposed to 1 either.  My concern is that the other side of this is app auto discovery of external names, which (to me) is a really big problem (how does a pod get *its* public name easily).  I don't think this blocks that (in some cases it makes it easier).

**Comment by madhusudancs** [comment]
@thockin @quinton-hoole a couple of questions for clarification:

> 2. Currently none of the ingress controllers expose ingresses on a service-ip, so ingresses currently only ever get an external IP. In such cases, we should not publish a ".ing.cluster.local" DNS name. Only CNAMES for ".ing.myfederation" style DNS names, as we do for external federated services.

1. So this means, no Ingress object gets an A record today?

2. If the ingresses were exposed on a service-ip (or what it really means is a cluster-local IP I guess?) how are we going to disambiguate between a local address and an external address. In a Service it is very clear. `.spec.clusterIP` is internal and whatever is in `.status.loadBalancer.ingress` are external. Should we make the same assumption about `.status.loadBalancer.ingress` in Ingress?

**Comment by thockin** [comment]
On Thu, Aug 18, 2016 at 12:43 PM, Madhusudan.C.S
<notifications@github.com> wrote:
>
> @thockin @quinton-hoole a couple of questions for clarification:
>
> Currently none of the ingress controllers expose ingresses on a service-ip, so ingresses currently only ever get an external IP. In such cases, we should not publish a ".ing.cluster.local" DNS name. Only CNAMES for ".ing.myfederation" style DNS names, as we do for external federated services.
>
> So this means, no Ingress object gets an A record today?

correct

> If the ingresses were exposed on a service-ip (or what it really means is a cluster-local IP I guess?) how are we going to disambiguate between a local address and an external address. In a Service it is very clear. .spec.clusterIP is internal and whatever is in .status.loadBalancer.ingress are external. Should we make the same assumption about .status.loadBalancer.ingress in Ingress?

up to now, ingress is presumed to be a cluster-edge ingress, and as
such it would have a non-cluster-local IP

**Comment by madhusudancs** [comment]
@thockin Ok, thanks.

**Comment by bprashanth** [comment]
> I think the *real* answer will
be to chain an "external" service onto an ingress IP so that short names
work, so that direct use of ing names will be few and far between.

Another interesting problem is chaining an internal ingress that we're running as a Service to the external counterpart. 

If I'm running the nginx controller as a Service intra cluster clients would reach it via:
 `ingress-controller.svc.cluster.local`. 

This would run through the ingress rules eg:
```yaml
annotations:
  kubernetes.io/ingress.class: nginx
rules:
  - host: foo.bar.com
    paths:
    - path: /bar
      backend:
        serviceName: fooSvc
        servicePort: 80
```

The nginx in the pod would find no endpoints and redirect somehwere. 
I would prefer going to `ingress-controller.ing.myfederation` at this point, which is a weird translation.
I could also go to `fooSvc.svc.myfederation` per Service.

But this is not a now problem.

**Comment by dims** [comment]
@madhusudancs @quinton-hoole : punt to v1.6? can you please move the milestone if so.

**Comment by madhusudancs** [comment]
@dims ack. Changed.

**Comment by ethernetdan** [comment]
@madhusudancs @dims could this be closed or moved to the `v1.7` milestone if we're not fixing in 1.6

**Comment by madhusudancs** [comment]
This is not happening any time soon. (Doesn't mean it is not going to happen at all). So I am just removing the milestone.

**Comment by irfanurrehman** [comment]
This issue was labelled only for sig/multicluster and is thus moved over to kubernetes/federation#201.
If this does not seem to be right, please reopen this and notify us @kubernetes/sig-multicluster-misc.
/close
