### ISSUE TITLE
Setup federation e2e on AWS and GKE

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/kubernetes#30543]
Forked from https://github.com/kubernetes/kubernetes/issues/23653.

@colhom  is working on this. Assigning it to him.

cc @kubernetes/sig-cluster-federation

**Comment by nikhiljindal** [comment]
Actually cant assign it to him. But he is working on it

**Comment by colhom** [comment]
@nikhiljindal yep!

**Comment by pwittrock** [comment]
@quinton-hoole @nikhiljindal @colhom 

I am moving this out of the blocking issues we are tracking for the 1.4 release because the unfinished pieces are non-blockers for the release and do not need to be tracked in the burndown meetings.  If there are components besides docs & tests that need to be completed, please move it back to the 1.4 milestone and provide daily status updates.

**Comment by quinton-hoole** [comment]
Yup, that's fine. The AWS stuff got mostly sorted out today, and we know
that GKE works due to manual testing.

**Comment by felipejfc** [comment]
Are there any tutorials on how to setup a aws/gke kubernetes cluster federation? Is this possible yet?

**Comment by nikhiljindal** [comment]
Yes you can setup cluster federation on GCE, GKE or AWS. You can follow the instructions at http://kubernetes.io/docs/admin/federation/

**Comment by irfanurrehman** [comment]
This issue was labelled only for sig/multicluster and is thus moved over to kubernetes/federation#65.
If this does not seem to be right, please reopen this and notify us @kubernetes/sig-multicluster-misc.
/close
