### ISSUE TITLE
Deprecate experimental-flannel-overlay in v1.5 and remove old networking code

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubernetes#30589]
@thockin partially asked for this.

and flannel integrations will now take place in https://github.com/coreos/flannel/pull/483

@kubernetes/sig-network

**Comment by mikedanese** [comment]
We actually need to generalize it. There's a flag on controller-manager:
```
      --configure-cloud-routes[=true]: Should CIDRs allocated by allocate-node-cidrs be configured on the cloud provider.
```
Which needs to be mirrored in kubelet. Currently with --configure-cloud-routes=true set on controller-manager and --cloud-provider=gce set on kubelet, kubelet will never become ready because it's waiting for a route to be configured.

**Comment by thockin** [comment]
I think we need to streamline and de-hackify it.  I don't know if that means keep it or abandon it or something else.

@justinsb since he was playing with something that sounded cleaner...
