### ISSUE TITLE
DaemonSet controller should use a rate limiting queue to prevent hotloops

### ISSUE THREAD

**Issue by derekwaynecarr** [kubernetes/kubernetes#30628]
A `DaemonSet` controller should avoid getting into a hotloop when it gets denied a pod creation.

The controller should use a rate limiting queue similar to what was done for RC here:
https://github.com/kubernetes/kubernetes/pull/30626

/cc @kubernetes/rh-cluster-infra @deads2k

**Comment by kargakis** [comment]
Why was this issue closed?

**Comment by foxish** [comment]
cc @kubernetes/sig-apps-bugs

**Comment by lukaszo** [comment]
DaemonSet controller is already using rate limiting queue https://github.com/kubernetes/kubernetes/pull/32210 so it seems to be a different bug.

**Comment by kargakis** [comment]
This is similar to https://github.com/kubernetes/kubernetes/issues/43846 - a ratelimiting queue is not enough in this case because the DS will always create a new Pod successfully, the Pod runs OutOfcpu so it's terminated, and the DS will spin up the next one, and so on. We need a way to ratelimit such controllers and I suspect it's going to be easier with history objects, because then we can track CREATE requests for specific templates and start ratelimiting those templates with CREATE requests that have started exceeding a threshold proportionate to the desired number of replicas. Not sure what's the solution for ReplicaSets in that case because they are not going to support history (at least in the short term).
