### ISSUE TITLE
Devel doc: api_changes.md out of date

### ISSUE THREAD

**Issue by foxish** [kubernetes/kubernetes#30692]
https://github.com/kubernetes/kubernetes/blob/master/docs/devel/api_changes.md

The document makes several mentions of paths which no longer exist in the source tree.
For example:

> The struct definitions for each API are in `pkg/api/<version>/types.go`. Edit those files to reflect the change you want to make. Note that all types and non-inline fields in versioned APIs     must be preceded by descriptive comments - these are used to generate documentation. Comments for types should not contain the type name; API documentation is generated from these comments and end-users should not be exposed to golang type names.

Also, 

> `pkg/api/<version>/conversion.go` containing manually written conversion functions
> `pkg/api/<version>/conversion_generated.go` containing auto-generated conversion functions
> `pkg/apis/extensions/<version>/conversion.go` containing manually written conversion functions
> `pkg/apis/extensions/<version>/conversion_generated.go` containing auto-generated conversion functions

These have since moved to apis/.... The doc needs to be updated to reflect this.

**Comment by vbmade2000** [comment]
@foxish I see all mentioned paths exist but I noticed two links don't exist. Following are those links:

1. ...or an example, see [v1 conversion tips](https://github.com/kubernetes/community/blob/master/contributors/api.md#v1-conversion-tips)
2. [The client library](https://github.com/kubernetes/community/blob/master/pkg/client/restclient/request.go) has custom conversion... 

Can you tell me what should they point to so that I can correct them ?
