### ISSUE TITLE
Validated kernel version / filesystem plugin for 1.3?

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#30706]
We're seeing some kernel panics with the default AWS images, which use Debian Jessie & aufs, with k8s 1.3 & Docker 1.11.2.

What is the validated kernel version and filesystem with k8s 1.3?

cc @dchen1107

**Comment by chrislovecnm** [comment]
Do you have any information on the panic?

**Comment by rata** [comment]
@justinsb can you post the panic? (it's available via the AWS console, in general). Are you doing heavy I/O on the docker root volume? Is aufs in the call trace?

I've seen a panic with 1.2 and newer docker daemon running on a container: https://github.com/kubernetes/kubernetes/issues/27885. If that is what you see, my workaround was to use a different backing volume and not write to the container root (but not tried k8s 1.3).

I don't know which version it is validated, but following links from the bug above it seems this issue is the one to track it and was not closed yet: https://github.com/kubernetes/kubernetes/issues/25893. Don't know if you already found it, it took me a while because I was looking at closed issues :)

**Comment by rata** [comment]
@justinsb cool. Just curious, what kernel in debian jessie (like `apt-cache policy` output for the kernel pkd)?

**Comment by justinsb** [comment]
@rata `3.16.7-ckt25-2+deb8u3`  and also `3.16.7-ckt25-2`

**Comment by dchen1107** [comment]
@justinsb We need to investigate on this. We didn't change minimal kernel version and docker version for both 1.3 and 1.4 release. 

I did observe the same kernel panics before 1.3 release and we even introduces a node-problem-detector daemonset to make the issue visible. But with kubernetes 1.3 + docker 1.11.2 together on containervm e2e tests, I haven't seen such kernel panics. 

One possibility is the different configurations on the node? For example, on GCE, we switched to use kubernet, not using docker's network component at all. How about aws?

**Comment by justinsb** [comment]
Thanks @dchen1107  AWS is not using kubenet (though it should).  I can probably upgrade the cluster most affected to use kubenet and see if it makes a diference.

Also, for unknown reasons, we aren't logging the kernel panic into the journald logs.  Would the NPD pick up on it if it is not in the logs, but only visible e.g. in uptime?  We currently get the hint from the uptime, and then confirm by looking at the AWS console output.

**Comment by chrislovecnm** [comment]
cc @fandingo

**Comment by dchen1107** [comment]
@justinsb today NPD can only pick up the issue from the logs. But which logs, and what format with regex can be configured easily. 

In kernel panic case, Is there anyway to get console screenshot during reboot, something like startup script?

**Comment by justinsb** [comment]
Just switched to kubenet and had another panic within a few hours (in the scheduler again).

```
[10905.003885] BUG: unable to handle kernel NULL pointer dereference at 0000000000000078
[10905.007856] IP: [<ffffffff8109f9f0>] check_preempt_wakeup+0xd0/0x1d0
[10905.007856] PGD 16664b067 PUD 103790067 PMD 0 
[10905.007856] Oops: 0000 [#1] SMP 
[10905.007856] Modules linked in: nf_conntrack_netlink nfnetlink xt_statistic xt_nat xt_recent xt_mark ipt_REJECT xt_tcpudp sch_htb veth xt_comment ipt_MASQUERADE iptable_nat nf_conntrack_ipv4 nf_defrag_ipv4 nf_nat_ipv4 xt_addrtype iptable_filter ip_tables xt_conntrack x_tables nf_nat nf_conntrack bridge stp llc aufs(C) nfsd auth_rpcgss oid_registry nfs_acl nfs lockd fscache sunrpc evdev ppdev parport_pc parport intel_rapl ttm i2c_piix4 drm_kms_helper crc32_pclmul drm processor thermal_sys i2c_core aesni_intel aes_x86_64 lrw gf128mul glue_helper button ablk_helper serio_raw cryptd autofs4 ext4 crc16 mbcache jbd2 btrfs xor raid6_pq dm_mod ata_generic xen_blkfront crct10dif_pclmul crct10dif_common ata_piix crc32c_intel libata psmouse scsi_mod ixgbevf(O)
[10905.007856] CPU: 3 PID: 19256 Comm: exe Tainted: G         C O  3.16.0-4-amd64 #1 Debian 3.16.7-ckt25-2
[10905.007856] Hardware name: Xen HVM domU, BIOS 4.2.amazon 05/12/2016
[10905.007856] task: ffff880245d80210 ti: ffff88015bc0c000 task.ti: ffff88015bc0c000
[10905.007856] RIP: 0010:[<ffffffff8109f9f0>]  [<ffffffff8109f9f0>] check_preempt_wakeup+0xd0/0x1d0
[10905.007856] RSP: 0018:ffff88015bc0fe60  EFLAGS: 00010006
[10905.007856] RAX: 0000000000000000 RBX: ffff88027c906280 RCX: 0000000000000008
[10905.007856] RDX: 0000000000000000 RSI: ffff880077ca81d0 RDI: ffff88040fc72f78
[10905.007856] RBP: 0000000000000000 R08: ffffffff81610960 R09: 0000000000000001
[10905.007856] R10: 0000000000000000 R11: 0000000000000000 R12: ffff880245d80210
[10905.007856] R13: ffff88040fc72f00 R14: 0000000000000000 R15: 0000000000000000
[10905.007856] FS:  00007f38d545d740(0000) GS:ffff88040fc60000(0000) knlGS:0000000000000000
[10905.007856] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[10905.007856] CR2: 0000000000000078 CR3: 0000000245d9f000 CR4: 00000000001406e0
[10905.007856] Stack:
[10905.007856]  ffffffff81099e58 ffff88040fc72f00 ffff880077ca81d0 ffff88040fc72f00
[10905.007856]  ffff880077ca8854 0000000000000246 ffff88017194b7c0 ffffffff81094605
[10905.007856]  0000000000012f00 ffffffff81096a8a 00007fffffffeffd ffff880077ca81d0
[10905.007856] Call Trace:
[10905.007856]  [<ffffffff81099e58>] ? sched_clock_cpu+0x88/0xb0
[10905.007856]  [<ffffffff81094605>] ? check_preempt_curr+0x85/0xa0
[10905.007856]  [<ffffffff81096a8a>] ? wake_up_new_task+0xda/0x160
[10905.007856]  [<ffffffff81066a0c>] ? do_fork+0x13c/0x390
[10905.007856]  [<ffffffff81514d79>] ? stub_clone+0x69/0x90
[10905.007856]  [<ffffffff81514a0d>] ? system_call_fast_compare_end+0x10/0x15
```

**Comment by justinsb** [comment]
@dchen1107 I'm going to look at whether we can be sure to panic output into the journald log.  I would much rather do that then scrape the console output, but worst case it is a good suggestion!

**Comment by justinsb** [comment]
We've tried a lot of things, and the only thing that seems to work is to run a 4.4 kernel (we are running a 4.4.19 kernel I built).  This also entails running overlayfs.

I'm going to work on building an image that offers this as an option, and maybe we can consider making it the default on 1.4 on AWS.

**Comment by dchen1107** [comment]
@justinsb Google GCI team is currently working together with node team to qualify GCI image for GKE/GCE replacing today's debian-based container-vm image. Since you are considering to rebase your image to newer kernel, why not sync with what GCI has so that we can provide better support for our aws users? Currently GCI image is on 4.4.14. cc/ @yinghan @kubernetes/goog-image 

@justinsb could you please provide the detail information on what are not working on your current image? I understood there are kernel panic, unfortunately we saw such panic at very rare rate in house. But looks like in your case, it occurs very frequently. We need to understand the discrepancy and try to minimize them so that we can consolidate our effort to provide the better service in general to the users. Meanwhile, since Kubernetes is an open-source project, we can only harden minimal kernel version (3.10?) and many other configurations, instead of forcing a homogeneous environment, especially for the users running Kubernetes on the private clouds.

**Comment by justinsb** [comment]
@dchen1107 Yes, for the AWS image I will try to sync with GCI as closely as I can, if we go to 4.4 as the default on AWS.  Although if you're maintaining 4.4.14 + patches, I do wonder if official upstream (4.4.19) would be better than 4.4.14 without patches.  I don't know how different these will be in practice though.  My feeling is that testing effort will inevitably focus on 4.4 kernels & overlayfs, if GCI, CoreOS & Ubuntu 16.04 are all on 4.4 kernels, and remaining on an earlier kernel is just going to cause more and more problems.

The panics are as I reported previously in the thread.  The stack traces do not seem to change significantly: always in the scheduler, always segfaults slightly offset from 0x0.  I have not been able to track down any root cause other than the m4 instance types, which are slightly newer chips, and typically with more cores.  I originally thought it was a particular version of the ixgbevf driver, but the evidence does not appear to support that (unless all the versions I tried are bad, and the version in the 4.4 kernel fixes it, which is not impossible - the driver is pretty active).

I totally understand that we can't mandate 4.4, but we should not shy away from saying "here is the configuration k8s tests, and we run a lot of tests".  The node team does a lot of under-appreciated work to find a working configuration, and I want to remain reasonably close to that with the default AWS configuration.

I tried getting the segfault to appear reliably in the journal and have given up.  Capturing the aws console output and dumping it to a file seems more fruitful.  Haven't yet had time to do that though...

**Comment by matchstick** [comment]
@dchen1107 Assigning to you for triage right now. AS it is a 1.4 P0. If you are the wrong person I apologize. Also @thockin and @vishh should have this on their radar.

**Comment by dchen1107** [comment]
@matchstick No need to apologize, this is on my radar all the time. And I know @justinsb is working on this actively and diligently. The only reason I didn't assign to either me or @justinsb is that this is not in 1.4 milestone, and I cannot do much on aws's image besides offering the suggestions. @justinsb Do you think this should block 1.4 release? 

@justinsb yes, you and I are on the same page to align AWS node configuration with GCE ones so that we can get rid of one more discrepancy between AWS and GKE, and provide better support to our users on AWS. Thanks for all your support & effort on getting AWS configuration as close as possible to ours. GCI team is working on open source GCI. If that process is finalized, we can help to build an AWS kubernetes image based on GCI. Unfortunately we are not there yet. cc/ @yinghan @aronchick @mansoorj 

On another hand, node team maintains node e2e test infrastructure and performance the tests on a list of images. You can access the test result at https://k8s-testgrid.appspot.com/google-node. We didn't attempt to exclude any images from that project. If you build your image based 4.4.19, you can add your image to our image project, we can include that in our test metrics too. The only caveat is that we shouldn't make the breakage on those image block our submit-queue.

**Comment by pwittrock** [comment]
@justinsb @dchen1107 

I am leaving this in the 1.4 release as a blocking issue.  Please continue to provide daily status updates to this issue or move it out of the release and into v1.4-nonblocking where it will no longer be tracked as a release blocking issue in the burndown meetings.

**Comment by justinsb** [comment]
I can probably take this as assigned to me.  I don't think it should block the whole k8s release, but it is a pretty serious issue for AWS and I want to get it resolved for 1.4.

I'm planning on taking a look at the kernel you are running in GCI and trying to figure out how many patches you are carrying (any links greatly appreciated).  My concern is that if we ship an image with our own kernel, we then have to build the kernel/AMI going forward whenever there is e.g. a security issue.  It is pretty attractive to me to just build from the official 4.4 Linux LTS kernel and rely on their work, rather than trying to maintain a set of patches and get involved in kernel cherry-picks.  And I believe this problem may go away around the end of the year with debian, because the next version of debian should include the next Linux LTS kernel.

And big thanks @dchen1107 for helping me figure out which kernel we should be running here!  I'll update as I continue looking around (probably with more questions, I'm afraid).  If you'd rather assign to me please do so!

**Comment by vishh** [comment]
Question:
Why is it not OK to use Ubuntu trusty or debian jessie for AWS? We can have our node e2e suite validate compatibility with those distros. We test trusty already. 
I'm concerned that manually keeping the aws image in sync with GCI will be a non-trivial task.

**Comment by justinsb** [comment]
@vishh Debian Jessie has an older kernel which kernel panics on m4 instance types.  I suspect we just haven't been seeing it because (1) it is rare and (2) it only happen on certain instance types and (3) it is non-trivial to capture a kernel panic on a systemd system, so it might be happening and we might just not be noticing.  I don't know if the NPD would detect kernel panics on non-journald systems?

Ubuntu Trusty is really old, and it seems very likely to fall victim to the same problems (although Ubuntu does a good job of backporting kernels).  However, if we're going to run Trusty with a backported kernel, at that point we might as well use Ubuntu Xenial (which is 4.4, LTS, and systemd).  I think that is another option, but I also want an option for Debian because we had to go with debian for 1.2 because there was no sufficiently supported version of Ubuntu at that time, and we want some continuity.

**Comment by dchen1107** [comment]
@justinsb I leave this with 1.4 milestone and P0, but marked it as non-blocker. I assigned this one to you since you are the one doing the real work. I still leave myself as another assignee to help you figure out the short-term workaround and work on the long-term strategy on qualifying the image running on AWS. Building from the official 4.4 Linux LTS kernel sounds good to me for me. Again, let's add your image to node e2e test image project and run test suite against that daily. 

@vishh Please read the initial description @justinsb wrote. They are using debian jessie (3.16.0-4-amd64 #1 Debian 3.16.7-ckt25-2+deb8u3) for AWS already, and observing the kernel crashes with high frequency. The initial suggestion is making those kernel crash visible for the end user / cluster admin first. We added the support to NodeProblemDector, but @justinsb ran into some issues of logging the kernel panic into the journald logs on AWS nodes.

**Comment by dchen1107** [comment]
@justinsb You can find the kernel sources for GCI from their release notes at: 
https://cloud.google.com/compute/docs/containers/vm-image/release-notes

**Comment by chrislovecnm** [comment]
Just to throw my two cents in, we have to have a Debian tested version. Custom kernel is fine, but we need the .config on a stable configuration. Multiple parties are using Debian, and we need to make this happen.

Let me know if you need any support with this. We have already scheduled an upgrade in the next couple of weeks.

@justinsb we are in your debt for finding this one!

**Comment by chrislovecnm** [comment]
@dchen1107 so here are some thoughts

1. don't want to run GCI quite yet, till it is burned in more on EC2
2. don't want to really maintain custom patches, unless someone can say, you have to have this.  No choice.
3. kinda leaning toward using vanilla LTS kernel

Opinion?

**Comment by dchen1107** [comment]
@chrislovecnm Agreed with you above. We, GCE / GKE side are moving toward the direction listed above: 2) and 3). Also I'm not suggesting to running GCI unless it is completely open sourced.

**Comment by chrislovecnm** [comment]
@justinsb what is the status on your patched Kernel?  You have that into production?

**Comment by dims** [comment]
Is this still a p0 (open since Aug!)?

**Comment by chrislovecnm** [comment]
@dims this is listed as non-blocking but yah....

**Comment by chrislovecnm** [comment]
@dims I am not sure what priority to list, but we do not have a decent answer, and I am guessing that this is not documented well.
