### ISSUE TITLE
Service with type=NodePort and clusterIP=None is allowed

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#30908]
The combination of NodePort and headless is not valid today.  The apiserver allows it but kube-proxy does not implement it.

We should either say that nodeport should treat the set of backends just like the service VIP or we should make apiserver reject it.  I lean towards the latter.  It should be a very simple change, great for someone who doesn't know this logic so well to learn it.

**Comment by AdoHe** [comment]
It should be just some validation logical change.

**Comment by surajssd** [comment]
@thockin I would like to work on this, I am new to k8s so might be a good starting point!

**Comment by thockin** [comment]
Derek started it with https://github.com/kubernetes/kubernetes/pull/30932
but I am sure he'd be happy to hand off the remaining work, and you can use
it to get a little familiar.

**Comment by surajssd** [comment]
@thockin its okay I will take something else :) because handing off process will introduce unnecessary time to get it done, Thank you

**Comment by thockin** [comment]
In this case, what Derek already did is very very minimal, and he hasn't
responded to feedback (I know for a fact he has 50 different efforts in
flight).  Please feel free to take this...please?

**Comment by surajssd** [comment]
@thockin sure

**Comment by YouriT** [comment]
Just to be sure @thockin if I got it properly, in your initial post, you basically said that it's not valid and you proposed either to implement it, either to reject it when applying this config, right?

Hence, the question is: what choice has been made there with the resolution of the issue?

On 1.5.6, it isn't rejected and it doesn't work. So in order to know whether I should open a new issue or not, I need to be sure what has been achieved here.
