### ISSUE TITLE
Idea: make headless services first-class

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#30918]
Given #30908 and #30909, it feels like maybe we would do well to make "Headless" an actual value for cluster.spec.type.  Specifically, we don't intend to support node-ports or load-balancers for headless services, but it is possible to specify that intersection.

It would be cleaner, I think, to say:

headless-params:
- selector (optional)
- ports[*].port, protocol,  and name

clusterip-params:
- all of headless-params
- clusterip (optional else assigned)
- ports[*].targetPort
- sessionAffinity

nodeport-params:
- all of clusterip-params
- ports[*].nodePort

loadbalancer-params:
- all of nodeport-params
- loadBalancerIP
- loadBalancerSourceRanges

With #30599 we add:

externalname-params:
- externalName

I argued against this before, but I am not sure why.  Looking at history, I don't find my own arguments that compelling, but maybe I am missing some.

**Comment by xiangpengzhao** [comment]
This is a dup of #9307, but since this has more details , I prefer to close that one and let's track this.

If we all agree with a new service type for headless service, I'd like to work on this.
/assign
/remove-componet kubectl
/remove-team cluster

Making headless services to be a service type will be a break change. What's the policy to make this change? What I can think is, adding the new service type and at the same time still supporting config `clusterIP: None` but marking it as deprecated. After two release, we can then remove the `clusterIP: None` way completely.

/cc @thockin @smarterclayton WDYT?

**Comment by smarterclayton** [comment]
I think we (at the time) hadn't used it extensively.  It's hard to argue from your list that headless services aren't the bedrock of the hierarchy.

**Comment by weiwei04** [comment]
I am not sure headless service should have port:targetPort as normal service(with cluster ip), since headless service is just a DNS record and resolves to the backend Pod ip, so the port must equal targetPort, since a http://headless-servicename is indeed http://podip:port, so the port must equal targetPort?
