### ISSUE TITLE
Node-e2e density test failure due to the host port conflicts

### ISSUE THREAD

**Issue by ronnielai** [kubernetes/kubernetes#30938]
I've seen consistent failures from density test in node-e2e suite. 

**Steps to reproduce:**
Run "make test-e2e-node REMOTE=true FOCUS="Density"

**Observed result**
https://gist.github.com/ronnielai/03fe48c95dd1f376a11536c95cbc3282

**Comment by Random-Liu** [comment]
@ronnielai Thanks a lot! :)

**Comment by dchen1107** [comment]
This cause of this density failure is different from other flaky ones. This one is caused by port conflicts, which might be a special case in @ronnielai's environment:

Aug 18 22:17:22.729: INFO: At 2016-08-18 22:17:22 +0000 UTC - event for cadvisor: {kubelet test-gci-dev-54-8711-0-0} PodFitsHostPorts: Predicate PodFitsHostPorts failed

I am going to leave this one open for a while to see if the issue re-occur.

**Comment by yujuhong** [comment]
Since this only happens in the specific test environment, let's close this issue.
