### ISSUE TITLE
Ensure that federated replica set controller logic is compatible with cluster autoscaler.

### ISSUE THREAD

**Issue by mwielgus** [kubernetes/kubernetes#30999]
According to current design federeated rs controller may move replicas to other cluster once they fail to schedule. At the same time cluster autoscaler may try to grow the cluster to place the pending pod somewhere. Some mechanism needs to be added so that these two don't compete with each other. 

cc: @quinton-hoole @piosz @fgrzadkowski @jszczepkowski @kubernetes/sig-cluster-federation

**Comment by dims** [comment]
@mwielgus : no assignee or update since this was filed. Do we move this to v1.6?

**Comment by fgrzadkowski** [comment]
@mwielgus I'm moving this issue to 1.7. Please revert this change if you believe this should block 1.6.

**Comment by marun** [comment]
Not a release blocker for 1.7.

**Comment by munnerz** [comment]
In my particular use case, we have an on-prem cluster and a GKE cluster federated together.

The on-prem cluster is of a fixed size, and the GKE cluster has the autoscaler enabled. I've then set the weight for the on-prem cluster to '50', and the weight for the GKE cluster to '1' (in an attempt to create a 'burst mode' style setup, where cloud resources are utilised only when required).

Aside from the scale events sometimes taking a few minutes whilst the federation Deployment controller works out a correct 'estimated capacity', I'm not actually seeing any negative interactions between the two.

What I observe:

* Federation CM attempts to schedule as many as possible onto on-prem cluster
* When some of these are unschedulable, after about 1 minute the remaining replicas are scheduled onto the GKE cluster, which at this point is also unable to service this number of replicas.
* The cluster-autoscaler then kicks in and scales up the GKE cluster, thus allowing those pods to be scheduled.
* The replica count on the on-prem cluster is actually set far above what it *can* schedule - this is beneficial in my case, as it means that if a pod *does* eventually schedule, the Deployment controller will actually scale down the Deployment on the GKE cluster.

It seems the 'move' isn't so much of a 'move', but more 'let's allocate some more here and hope replicas appear on one of the clusters sometime soon, otherwise I'll add some more replicas to yet another cluster'.

Could someone try and outline what issues may occur here? Or is this a tracking issue to reference issues that may occur with future developments? I wouldn't want to be missing something obvious!

**Comment by piosz** [comment]
@mwielgus isn't this obsolete?

**Comment by piosz** [comment]
closing as obsolete, please reopen if I'm wrong
