### ISSUE TITLE
The pods i am working with are being managed by kubernetes. When I use the docker restart command to restart a pod, sometimes the pod gets a new id and sometimes the old one. When the pod gets a new id, its state first goes friom running ->error->crashloopbackoff. Can anyone please tell me why is this happening

### ISSUE THREAD

**Issue by abhism** [kubernetes/kubernetes#31092]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Kubernetes version** (use `kubectl version`):

**Environment**:
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else do we need to know**:

**Comment by Random-Liu** [comment]
This is expected behavior.

When restarting a container, kubelet will kill the old one and start a new one instead of using docker restart. Kubelet doesn't use docker restart because of several reasons (docker restart won't preserve previous container exit status etc.).

When you use docker restart and the container id is changed, kubelet can't find current running container by id, thus thinks that the container is gone, reports crashloop, and tries to start a new one.

**Comment by abhism** [comment]
@Random-Liu But what about when the pod restarts with the same ID?

**Comment by yujuhong** [comment]
@abhism there is already a stackoverflow question for this. Please move the discussion there as this is not a bug in kubernetes: http://stackoverflow.com/questions/39071922/kubernetes-pods-are-restarting-with-new-id
