### ISSUE TITLE
Build etcd/storage into the api-server, simplify the deployment.

### ISSUE THREAD

**Issue by timothysc** [kubernetes/kubernetes#31132]
A long time ago we proposed the notion of building etcd directly into the api-server, but for some time the main detractors have been "flexibility of deployment", or the notion that as some point in time we may want to horizontally auto-scale the api-server.  

This idea[HPA-api-server], which has never panned out I might add, has come at a **huge cost**.  Today we hold several layers of caching in the api-server and we've debug'd a countless number of bugs that have been rooted in the notion that we want to keep etcd separate.  

I'd gladly force a deployment of 3 api-servers, embed etcd with a native client (https://github.com/coreos/etcd/issues/4435) for the reduced layering, simplify deployments, and eliminate more communications channels.  

/cc @kubernetes/sig-scalability @kubernetes/sig-cluster-lifecycle @smarterclayton @hongchaodeng @xiang90 @ncdc

**Comment by justinsb** [comment]
Also we can embed management of the Raft cluster membership.  I think this makes it _easier_ too support more flexible API/etcd configurations, not harder.

**Comment by timothysc** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;Carz92Bn&#x2F;182-5-sprint-119-community-work"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> (5) Sprint 119 Community Work</a>

**Comment by mikedanese** [comment]
@kubernetes/sig-api-machinery

**Comment by lavalamp** [comment]
If we did this:
* we wouldn't be able to turn off any of the caching that apiserver does.
* we wouldn't be able to serialize less data (everything still gets written to disk). 
* something like an etcd2-etcd3 migration would be *harder* than it is today. 
* We'd lose the flexibility of having differing numbers of etcd and apiserver instances.

Literally the only advantage I can think of is that we save network traffic between etcd and apiserver, and we'd have 1 copy in memory of the serialized data instead of 2.

**Comment by lavalamp** [comment]
And in fact without doing surgery somewhere we'd probably still have two caches of the serialized data, it's just that they'd both be in the apiserver process now.

I can't actually think of anything that this would make simpler, other than maybe turn-up.

**Comment by smarterclayton** [comment]
I do think today we benefit from updating etcd at slightly different rates than the apiservers - post etcd 3 that seems more likely that we would pick up occasional fixes without having to rev Kube.

**Comment by wojtek-t** [comment]
I generally agree with @lavalamp - in my opinion it would complicate few things, without having clear benefits of that.

**Comment by timothysc** [comment]
Thx for the feedback, I'll lump the comments into PROs and CONs, and DEBATABLE and try to provide the logic behind each.  

**PRO:**
- Simplified deployment, less components, less certs etc. 
- Removal/optimization of watch caches, etcd3 maintains it's own.  Slowly eliminate the redundancy.
-- Tests we have today show the api-server caching can be a multiple of the data that is actually stored.
- Removal of comm channel apiserver<>etcd3

**CONS:** 
-   We'd lose the flexibility of having differing numbers of etcd and apiserver instances. 

**DEBATABLE** (point/counter point)
- **P1:** we wouldn't be able to turn off any of the caching that apiserver does.
- **CP1:** I'd argue this can/should be broken up over time.  For example, as of today the apiserver does **a lot** of object validation, which is debatable if that is necessary and or useful.  A concrete example can be found from list gets.  Every sub-element is decoded <> cached <> re-encoded over the wire, then re-decoded on the other end.  The question that should be raised in an etcd3 world is why do a decode + cache if we are serving out of memory?  Object validation/upgrade should really be a one time operation, so why not serve out of the in memory data structure that etcd3 maintains.  This simplifies the api-server to become a dumb pass through for most operations.  
- **P2:** we wouldn't be able to serialize less data (everything still gets written to disk). 
- **CP2:** I don't understand the point you are trying to make here, could you please elaborate on how this proposal would be a con in what we do today? 
- **P3:** something like an etcd2-etcd3 migration would be harder than it is today.
- **CP3:** I'd say this requires a concrete example of how it is "harder" 
- **P4:** I do think today we benefit from updating etcd at slightly different rates than the apiservers - post etcd 3 that seems more likely that we would pick up occasional fixes without having to rev Kube.
- **CP4:** I agree with this statement.  I would hope over time that etcd3 would become more solid and provide systematic versioning such that updates are well defined and well versioned.  I could also wish for a unicorn too.

**Comment by lavalamp** [comment]
Not a pro: "Removal/optimization of watch caches, etcd3 maintains it's own.
Slowly eliminate the redundancy. -- Tests we have today show the api-server
caching can be a multiple of the data that is actually stored."

This isn't true because we do a bunch of filtering that etcd doesn't and
isn't going to do.

On Tue, Aug 23, 2016 at 8:20 AM, Timothy St. Clair <notifications@github.com

**Comment by lavalamp** [comment]
I really don't think the things you list as debatable are debatable, but I'll respond in kind. I don't understand CP4.

**DEBATABLE** (point/counter point)
- **P1:** we wouldn't be able to turn off any of the caching that apiserver does.
- **CP1:** I'd argue this can/should be broken up over time.  For example, as of today the apiserver does **a lot** of object validation, which is debatable if that is necessary and or useful.  A concrete example can be found from list gets.  Every sub-element is decoded <> cached <> re-encoded over the wire, then re-decoded on the other end.  The question that should be raised in an etcd3 world is why do a decode + cache if we are serving out of memory?  Object validation/upgrade should really be a one time operation, so why not serve out of the in memory data structure that etcd3 maintains.  This simplifies the api-server to become a dumb pass through for most operations.  
_ **CCP1:** No, we implement features in our watch stack that etcd doesn't implement and isn't going to implement. Additionally, various efforts are underway to do things like run k8s on consul instead of etcd, so even if etcd implemented all of our watching/filtering needs, we still couldn't delete this code.
- **P2:** we wouldn't be able to serialize less data (everything still gets written to disk). 
- **CP2:** I don't understand the point you are trying to make here, could you please elaborate on how this proposal would be a con? 
- **CCP2:** Total number of kubernetes object serialization calls and bytes is the same (yes, we drop the etcd API wrapper but that's proto and insignificant).
- **P3:** something like an etcd2-etcd3 migration would be harder than it is today.
- **CP3:** I'd say this requires a concrete example of how it is "harder" 
- **CCP3:** It's an offline migration. How do you keep apiserver from messing with the data when the database is built in to apiserver? We'd actually have to write code in apiserver to support this migration. Right now we can do it with shellscripts and sealing wax.

**Comment by timothysc** [comment]
> I really don't think the things you list as debatable are debatable, but I'll respond in kind.

Then we shall agree to disagree ;-) 

> Additionally, various efforts are underway to do things like run k8s on consul instead of etcd, so even if etcd implemented all of our watching/filtering needs, we still couldn't delete this code. 

ok, I'll concede that one.   

> CCP2: Total number of kubernetes object serialization calls and bytes is the same (yes, we drop the etcd API wrapper but that's proto and insignificant).

The socket hop + sec + grpc unmarshing is always a cost.  Also my point in CP1 was that we are doing far to much object validation and hence don't need to deserialize in many cases.  

> CCP3: It's an offline migration. How do you keep apiserver from messing with the data when the database is built in to apiserver? We'd actually have to write code in apiserver to support this migration. Right now we can do it with shellscripts and sealing wax.

There is always a way here, we could simply have a command line option, but I'll concede it's not pretty.  

OK, I'm cool with closing this issue, but at least it's captured now for posterity and to revisit at another point.

**Comment by lavalamp** [comment]
Thanks, I agree it's good to have this documented.

Re: excess deserialization, Clayton and I have discussed adding a
"fastpath" to allow us to not deserialize on reads.

**Comment by xiang90** [comment]
@lavalamp 

>Re: excess deserialization, Clayton and I have discussed adding a "fastpath" to allow us to not deserialize on reads.

We have some idea to store raw data in cache to reduce memory overhead. We should have a discussion on this some day...
