### ISSUE TITLE
Support executing command within `kubectl proxy`

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/kubernetes#31178]
In the docs we often tell users to `kubectl proxy` then do some other command e.g. `curl`.  It would be nice if we had something similar to what `find --exec 'ls {}'` provides where we have kubectl setup the proxy and run the command sustituting in the url then tear down the proxy.  `kubectl proxy --exec "curl {}/api/v1/..."`

**Comment by nhlfr** [comment]
This will be tricky in case of unix sockets. There is no universal pattern for dealing with them in all the application. Of course in curl we can do `curl --unix-socket somesocket.sock http:/api/v1/...`, but what about the other commands?

However, it'd be great to have something like that for HTTP sockets.

**Comment by bgrant0607** [comment]
See also #5164

**Comment by nhlfr** [comment]
Due to discussion with @fabianofranz in #31240, we decided to change the approach a little bit. The idea is to provide `--curl` option to the `kubectl proxy` command, which will work like `--raw` in `kubectl get`. Why? Because no one provided any other usecase than curl, so in our opinion, there is no need to implement `--exec`.

**Comment by pwittrock** [comment]
@nhlfr Does this support wget as well?  What are they advantages of just supporting curl?

**Comment by nhlfr** [comment]
@pwittrock 

#31240 - supports every command you want
#33077 #33659 - brings a `--curl` option, which is using k8s RESTClient, like in `kubectl get --raw`

I think we should support both behaviours - mostly because it's better to use a native REST client from Kubernetes than to force user to use external binaries like curl or wget.

**Comment by pwittrock** [comment]
SGTM
