### ISSUE TITLE
Move cluster setup guides out of kubernetes docs repo

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/kubernetes#31204]
The cluster setup guides are a maintenance nightmare.  They should be moved out of the kubernetes repo and into someplace where they can be updated out of band

**Comment by pwittrock** [comment]
Need to figure out the story of which guides are tightly coupled to code in the repo (don't move these) and which guides have no coupling at all to code in the repo (move these first)

**Comment by errordeveloper** [comment]
Great idea. I've raised this before in https://github.com/kubernetes/kubernetes/issues/12907, but closed because docs are in separate repo now. If the guides you are talking about are using `kube-up.sh` and/or some kind ad-hoc tools, we are naturally planing to deprecate them as part of @kubernetes/sig-cluster-lifecycle efforts.

**Comment by colemickens** [comment]
I'm confused, probably missing something. Does this mean to move the Getting Started guides out of the `kubernetes/kubernetes` repo or moving them out of the `kubernetes/kubernetes.github.io` repo? They've already been moved from the former to the latter.

**Comment by castrojo** [comment]
/close

The getting started sections have been out of kubernetes/kubernetes for a while now and sig-docs has been maintaining these sections and has plans for improving the navigation and structure. There's also a plan from sig-onprem to make the bare-metal guides better, so I'm closing this.
