### ISSUE TITLE
Monitoring Kubernetes using Prometheus

### ISSUE THREAD

**Issue by aktarali** [kubernetes/kubernetes#31249]
Hi;

I have tried to add the following lines to prometheus.yaml file:
# Kubernetes
- job_name: "K8s Cadvisor"
  scrape_interval: "15s"
  metrics_path: "/metrics"
  target_groups:
  - targets: ["http://node6.crmld.com:4001"] #Cadvisor
- job_name: "K8s APIserver"
  scrape_interval: "15s"
  metrics_path: "/metrics"
  target_groups:
  - targets: ["http://node6.crmld.com:8888"] #APIserver
- job_name: "K8s Kublet"
  kubernetes_sd_configs:
  - api_servers: 'http://node6.crmld.com:8888'
    relabel_configs:
  - source_labels: ["__meta_kubernetes_role"]
    action: "keep"
    regex: "node"

I keep getting the following errors:

Aug 19 17:14:27 node1 prometheus: time="2016-08-19T17:14:27+01:00" level=error msg="Couldn't load configuration (-config.file=/opt/prometheus/prometheus.yml): \"http://node6.crmld.com:4001\" is not a valid hostname" file=main.go line=177
Aug 19 17:14:27 node1 prometheus: time="2016-08-19T17:14:27+01:00" level=error msg="Note: The configuration format has changed with version 0.14. Please see the documentation (http://prometheus.io/docs/operating/configuration/) and the provided configuration migration tool (https://github.com/prometheus/migrate)." file=main.go line=178

Can someone please help. Maybe I am doing something or everything wrong?

ALi.

**Comment by castrojo** [comment]
Please re-post your question to [Stack Overflow](http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support
are posted so that we can improve our efficiency in responding to your requests,
and to make it easier for you to find answers to frequently asked questions and
how to address common use cases.

We regularly see messages posted in multiple forums, with the full response
thread only in one place or, worse, spread across multiple forums. Also, the
large volume of support issues on github is making it difficult for us to use
issues to identify real bugs.

The Kubernetes team scans Stack Overflow on a regular basis, and will try to
ensure your questions don't go unanswered.

Before posting a new question, please search Stack Overflow for answers to
similar questions, and also familiarize yourself with:

  * [user documentation](http://kubernetes.io/docs/)
  * [troubleshooting guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/)

Again, thanks for using Kubernetes.

The Kubernetes Team
