### ISSUE TITLE
OIDC authentication plugin: username claim is prefixed by issuer URL which isn't document

### ISSUE THREAD

**Issue by ericchiang** [kubernetes/kubernetes#31380]
This was brought up when investigating #31365

Currently if you use a claim other than "email" the value is prefixed by the issue URL when determining username. This means if I have a (non-standard) JWT with the following claims:

```
{
    "iss": "https://example.auth.com",
    "profile-name": "janedoe"
}
```

And "profile-name" is used to indicate username claims through the API server flag

```
--oidc-username-claim=profile-name
```

The username for this user will be:

```
https://example.auth.com#janedoe
```

Email is special cased and not prefixed by this value.[0]

This needs to be documented, but it's also annoying that we can't turn this off, which was achnologed by @liggitt when this code was added[1]

> the option to have fully-qualified issuer+sub usernames is good to have (and fully-qualified is probably good as a default), but in practice, most installations will not need such specificity, and having to express ACL rules like "https://accounts.google.com:1234567890" is almost impossible to use (especially once end-users are able to add ACL grants). As long as a cluster admin can choose between something like "issuer:sub" format and "email", I think our bases are covered.

The actual username being produced in by @mlbiam's setup using KeyCloak is:

```
https://kcdev.tremolosecurity.com:8443/auth/realms/kubernetes#mmosley.ent2k12.domain.com
```

Which I think fits the bill of "almost impossible to use".

So I guess my question to @kubernetes/sig-auth is, would we still consider fully-qualifying the username claim useful? Or is it reasonable to drop this?

EDIT: Also note that `--oidc-username-claim` is still marked as experimental[2]

[0] https://github.com/kubernetes/kubernetes/blob/1952986a345b2106fc165530592eb9c689decc10/plugin/pkg/auth/authenticator/token/oidc/oidc.go#L238-L246
[1] https://github.com/kubernetes/kubernetes/pull/10957#issuecomment-130010294
[2] http://kubernetes.io/docs/admin/authentication/#openid-connect-tokens

**Comment by mlbiam** [comment]
@ericchiang @kubernetes/sig-auth @whitlockjc 

I think its important for security reasons to keep this in place.  If someone:
1.  knew the subject of the cert used for privileged access
2. was able to compromise a single account in the IdP to set whatever claim is being read from

a user could elevate themselves to being a cluster-administrator, which could then be used in turn to do whatever they want.  So long as k8s will support multiple authentication sources then the recognition of the super user should be a combination of a value that the IdP is supplying and a value that the idp is not supplying so it can't be over ridden by a malicious user.

in fact, I would call that this is inconsistent with email address a bug since now if a user can change their own email address at an application, idp or data layer then its an easier vector for attack with a large attack surface.

I don't think its feasible to only allow a single auth source (service accounts would become much harder to manage) and even if you can disable the super user there is precidence for using that account as a "Break glass in case of emergency" account.  This is common with public cloud infrastructures where the "main" account is given a giant random password, a multi factor token and locked in a safe.

I don't know it has to be a URL, since thats unwieldy.  Anything will really do since the value thats checked is a combination of a static value NOT supplied by a user compromised source and a value that could potentially be compromised even a single extra character would protect from an elevation attack.

**Comment by deads2k** [comment]
Without separate concepts of identities (provided by idp) and the ability to map them to a different user, I think that qualification is the only reasonable way to support multiple idps.  Offering an option for setting that qualification to something cluster-admin defined is probably a good idea, though doing that via command line flags is likely to be unwieldy.

We kept a similar concept of qualification in openshift for handling identities, but then provided a distinct concept for users: https://docs.openshift.org/latest/install_config/configuring_authentication.html#mapping-identities-to-users .  We've intentionally stayed away from doing this in kube because it is very opinionated about what users are and how they map to things like groups.

**Comment by liggitt** [comment]
> in fact, I would call that this is inconsistent with email address a bug since now if a user can change their own email address at an application, idp or data layer then its an easier vector for attack with a large attack surface.

agree, the email claim not being prefixed is inconsistent. my comment was not intended to special-case email as a non-prefixed value, but to give the admin control over the claim and over prefixing.

**Comment by whitlockjc** [comment]
I agree that the inconsistency and lack of documentation on this is the real issue.  But as @liggitt suggested, requiring the fully-qualified URI for the subject name in the rules _"is almost impossible to use "_.  I understand the purpose of it but is there a better way to support what we need?

What if we made `--oidc-username-claim` _(or something similar)_, capable of being a composed value, a pattern, instead of a single claim?  This pattern could include any claim in the JWT token, and also `$issuer_url` since the `iss` claim is optional.  _(I can't tell if it's presence in a JWT is optional or if using it for verification is optional: https://tools.ietf.org/html/rfc7519#section-4.1.1)_  With something like this in place, we would not need to do any automatic prepending or special casing of anything.

For example, if you wanted to have the fully-qualified username we see now when not using `email` as the claim, you would use `--oidc-username-claim=$issuer_url#$email`.  But if you wanted **only** email as your username, you would have `--oidc-username-claim=$email`.  I like this, or something like it, a lot better because since I _(as the cluster admin)_ own this pattern, I am not surprised when creating authz rules.  Thoughts?

**Comment by ericchiang** [comment]
> Without separate concepts of identities (provided by idp) and the ability to map them to a different user, I think that qualification is the only reasonable way to support multiple idps. Offering an option for setting that qualification to something cluster-admin defined is probably a good idea, though doing that via command line flags is likely to be unwieldy.

I would be interested in how we plan to extend this to other auth providers. We're going to want to qualify any field potentially controlled by users. Fields returned by keystone, attributes in LDAP, etc. Is there a general solution where we qualify all identity providers in a reasonable way?

**Comment by whitlockjc** [comment]
The pattern approach mentioned above _could_ be used for all assuming that each provider has an object with properties that could be exposed for the composition key.  So while OIDC would use JWT claims, the other providers might use user detail properties, token fields, etc.  So instead of doing stuff behind the code, give the cluster admin control with some reasonable defaults _(documented)_.

**Comment by whitlockjc** [comment]
By the way, I'm not suggesting my proposal is awesome and needs to be the implementation to this.  I am advocating for a user-owned approach more than anything, for all cases.

**Comment by deads2k** [comment]
> By the way, I'm not suggesting my proposal is awesome and needs to be the implementation to this. I am advocating for a user-owned approach more than anything, for all cases.

I think a cluster-admin defined prefix on a per-idp basis makes the most sense.  It puts ownership in the right spot and all idps can be equivalent.

**Comment by whitlockjc** [comment]
I like that approach as well.  I do wonder how that would look but I guess that would be more along the lines of how Kubernetes supports multiple authn providers of the same type and less about your suggested approach.

Six in one hand, half a dozen in the other.

**Comment by mlbiam** [comment]
Yeah, I think an idp specific prefix is a good idea.  gives you best of both worlds.  k8s can handle multiple idps without becoming an idp, or the complications that come with it.  but it gives idps the flexibility to provide management.  From a practical perspective the important data points are the user's "id" and the groups so adding a prefix probably wouldn't be too much of a burden.  Since its impossible for an idp to spoof the prefix, the prefix its self doesn't matter.  For instance if the prefix is just "a" and the idp sends the groups as "aadmin" then the result would be "aadmin".  A simple name or label would suffice.

**Comment by whitlockjc** [comment]
I agree that an idp specific prefix makes the most sense too.  My proposal was more based on the existing `kube-apiserver` CLI flags and less general.  I'm on the @deads2k bandwagon now.

**Comment by ericchiang** [comment]
fyi this is now documented https://github.com/kubernetes/kubernetes.github.io/pull/2894 which was what this original issue was about.

/close

**Comment by grillz** [comment]
Just hit this issue and its odd. Thank you for adding the docs, but this should definitely be configurable. Its strange that its applied to users and not groups, and if my users are unique the prefix is cumbersome. Is this a done deal or can we reopen this?

**Comment by ericchiang** [comment]
@grillz there are a ton of possible configuration options that the oidc provider could support, e.g. https://github.com/kubernetes/kubernetes/issues/46806. It's unclear how much of this should go upstream and how much should go into an external webhook authenticator. Feel free to open the an issue, but there's been push back in the past for making this the default at least.

**Comment by liggitt** [comment]
Control over the prefix (including not prefixing) seems reasonable to me to give the cluster admin as an option, and would make the in-tree oidc useful in broader applications.

**Comment by ericchiang** [comment]
Opened https://github.com/kubernetes/kubernetes/issues/50408. Will send a change.
