### ISSUE TITLE
Design a mechanism to record a real workload and replay it deterministically

### ISSUE THREAD

**Issue by roberthbailey** [kubernetes/kubernetes#3138]

**Comment by timothysc** [comment]
You would need a job/history-server of some sort.

**Comment by davidopp** [comment]
We have a system like this for our internal cluster management system at Google. You can make this arbitrarily complicated. My suggestion would be to do this in phases.

First phase
(1) log every API request coming into the API server, including requests to create/update/delete pods, minions, and services
(2) write a client that can replay the request stream
At the end of the first phase, you have the ability to replay a workload that starts from an empty cluster (no minions) against a cluster that starts out empty (no minions)

Second phase: add the capability to replay starting in the middle of a cluster lifetime (i.e. don't require that cluster starts out empty); requires adding etcd state to the logged state, so now a replay looks like (1) re-create cluster configuration (including pods, minions, services) from some time in the past using the etcd state, (2) start replaying the logged API operations against the master

Third phase: remove the need to provision a physical machine or VM for each minion, by writing a fake minion such that you do the whole replay on a single physical or virtual machine.

A separate axis you can play with is artificial modifications to the workload and/or cluster. For example, replaying the workload faster than realtime, or doubling the number of pod creations compared to what was in the workload, or doubling the size of the cluster. This turns out to be complicated once you have complicated scheduling policies; for example if the minions are labeled with the id of some kind of failure domain that you want to spread across, blindly duplicating all the nodes doubles the size of the failure domains when in fact you might want to keep the size of the failure domain constant and double the number of them. 

In any event, you don't really need a separate server for any of this as long as you have a way to store the logs persistently (API server logs and etcd state) and retrieve them later. You do need some code or agent running on the master to take care of this saving. We probably want that anyway, since these logs are very useful for post-hoc debugging.

**Comment by davidopp** [comment]
One other comment: the design depends a bit on how much of the system you want to test.

If you just want to test the API server, then you can log (and later reply) all  the API operations that it receives, and then later instantiate an API server and replay that log. But if you want to test both the API server and scheduler, then you want to instantiate a real scheduler instance (along with the API server), and *not* replay the scheduler's calls into the API server from the original trace (since the scheduler instance you use during the replay will be making those calls). Same thing for replication controller and kubelet (for example if you want to replay with real or fake kubelets, then you don't want to replay the kubelet API calls the API server received in the trace, since the real or fake kubelets will make those calls).

**Comment by davidopp** [comment]
Random notes from a discussion with @xiang90 and @hongchaodeng 

* Can we get workload traces from OpenShift?
* Google cluster workload traces might or might not be relevant: https://github.com/google/cluster-data

**Comment by xiang90** [comment]
> Google cluster workload traces might or might not be relevant: https://github.com/google/cluster-data

I will look into this more carefully and report back soon.

**Comment by davidopp** [comment]
One approach to this issue is to make Kubemark be able to take a real workload trace rather than just use a synthetic workload.

I think being able to load historical cluster state for debugging/exploration purposes is related but a different use case.

random notes:
* collect snapshot of cluster state in real clusters, maybe trace of pod creation and termination/eviction along with where scheduled and node capacities

cc/ @smarterclayton @ncdc @derekwaynecarr

**Comment by gmarek** [comment]
I don't think it's related to Kubemark per se. We just need something that can read series of API calls sent to the API server. When we have something like this it can be used with any cluster, emulated or not.

**Comment by kargakis** [comment]
Related: https://github.com/kubernetes/perf-tests/tree/master/clusterloader

**Comment by davidopp** [comment]
Nice blog post on it
https://blog.openshift.com/managing-the-lifecycle-of-openshift-clusters-vetting-openshift-installations/

**Comment by k82cn** [comment]
> One other comment: the design depends a bit on how much of the system you want to test.

Total agree with that, we do not need to simulate all components. In our products, we only replay error handling in agent for the case that: error handling of error handling of error handling of error handling  .........

As davidopp's linked, I'd like to have a scheduler simulator.
