### ISSUE TITLE
Design a mechanism to generate a synthetic workload and play it

### ISSUE THREAD

**Issue by roberthbailey** [kubernetes/kubernetes#3139]

**Comment by timothysc** [comment]
It would be cool to also have an accompanying 'chaos monkey' tool. http://techblog.netflix.com/2012/07/chaos-monkey-released-into-wild.html

**Comment by davidopp** [comment]
Let's keep this issue limited to workload generators, and split off chaos monkey into a different issues.

Workload generator is particularly important for these two v1.0 goals:
* Scheduling throughput: 99% of scheduling decisions made in less than 1s on 100 node, 3000 pod cluster; linear time to number of nodes and pods (#3954)"
* "API performance: 99% of API calls return in less than 1s; constant time to number of nodes and pods (#4521)"

**Comment by davidopp** [comment]
Saad is going to do a first cut of this as part of #4432.

**Comment by saad-ali** [comment]
@lavalamp  took advantage of #4862 for load generation

**Comment by lavalamp** [comment]
It seems like everyone independently realized that load generation is important... I will not do anything for workload generation for the next week or so (will be out). I will look back here before doing anything about workload generation to see what's going on when I get back.

**Comment by timothysc** [comment]
FYI - Incorporating generator in examples here: https://github.com/GoogleCloudPlatform/kubernetes/pull/5447

**Comment by fgrzadkowski** [comment]
@saad-ali - Are you working on this? If not, I'm happy to do it.

**Comment by saad-ali** [comment]
@fgrzadkowski I am not. Removed my self as assignee. Feel free to grab it.

To avoid duplicating work, please sync with @jayunit100 and @satnam6502, I understand that they were working on a load generator (see #5447 and #5260).

**Comment by jayunit100** [comment]
I'm currently using k8petstore generators from asf bigtop to do this, you can read about them here ( https://github.com/apache/bigtop/tree/master/bigtop-bigpetstore/bigpetstore-transaction-queue  ).  I think they can be recomposed in many different ways.  To generate the load, I'm using the k8petstore app in `examples` and currently working to make the e2e tests able to run arbitrary examples/ applications.  So maybe we should sync up , possibly a call, @fgrzadkowski  ?

**Comment by fgrzadkowski** [comment]
@jayunit100 I only started looking at this, so let me first understand we already have :) Sync would be great!

**Comment by jayunit100** [comment]
okay, lets sync up !   
my email is jay@apache.rog or jayunit100.apache@gmail.com for a google hangout

**Comment by smarterclayton** [comment]
Chaos monkey is covered in #6729

**Comment by timothysc** [comment]
@jayunit100  We still need to hook soak-tests through e2e and report out similar to your graph in petstore.

**Comment by jayunit100** [comment]
- good idea. @satnam6502 has a scale test also but its not ginkgo-fied yet.  shall we start with that?
- https://github.com/GoogleCloudPlatform/kubernetes/issues/6183 this is the generic issue for adding examples (including workload generator) to e2es.

**Comment by satnam6502** [comment]
I vote for your k8petstore generator. I want to resist the Ginkgo-ization of the soak test (and another one too called cauldron that I hope to unleash soon) because I really want them to run as regular binaries and not as part of a test framework. This is because these programs are not directly testing our *code* (as the unit, integration and e2e tests) -- instead they test properties of a *running system* -- which of course is determined by code to some extent -- but also by many other factors. So in my mind that makes soak tests a very different kind of test.

**Comment by quinton-hoole** [comment]
As discussed with satnam6502 in person, wrapping Ginkgo around the soak test and cauldron binaries is probably worthwhile to make it easier to run them in a standard CI environment. Provided that the binaries output some sort of analysis of the results, the Ginkgo wrapper could decide what constitutes a "pass" or "failure".   The benefit of running these automatically in a CI, is that the test bits don't rot over time, due to nobody running them manually and scrutinizing graphs :-)

**Comment by jayunit100** [comment]
okay so goals are 
- implement satnam's soak as an e2e, just to prevent bitrot.
- implement loadgenerator k8petstore test as an e2e.

**Comment by piosz** [comment]
@jayunit100, goals you defined are good, but I think we should focus on generator which will help us reach our 1.0 goals as described by @davidopp in https://github.com/GoogleCloudPlatform/kubernetes/issues/3139#issuecomment-75474831.

I propose to implement the first version of load generator which will just create a few instance of guestbook application of different sizes, and simultaneously will resize existing ones.

Creating separate issues for goals defined by @jayunit100: #7507, #7508

**Comment by jayunit100** [comment]
hmm... guestbook for load generation ? iirc, guestbook doesnt load test - it accumulates transactions in the web browser and overwrites a string value in redis (rather than accumulating all the guests as independent records).

**Comment by piosz** [comment]
The application/docker image used for test doesn't matter. The goal for v1 is e2e pod startup time <5s on 99p (see #3954), so we want to have a tool which starts a lot of pods and measure theirs startup times.

The goal is **not** to measure (as for now, we probably want to do it post v1) how efficient applications running on kubernetes can be ie. by running a heavyweight application and spam it by many request.

AFAIU the load in this issue doesn't mean load on application running in kubernetes but load on kubernetes itself.

**Comment by jayunit100** [comment]
So this is like the density test...  if the app is not really going to do anything; why bother muddling things with a "real" app like guestbook ?  maybe for this type of workload, you can just use pause containers.  

guestbook implies that the application needs to have some workload behaviour associated with it.

**Comment by piosz** [comment]
So the question is do we really need something more sophisticated to verify our v1.0 goals than density test (maybe with improvements). The argument was to have something more similar to what users run. What do you think @fgrzadkowski, @wojtek-t?

**Comment by timothysc** [comment]
@piosz - if we mock @jayunit100's test to spread based on cluster size it would be much more realistic workload scenario.

**Comment by davidopp** [comment]
We can re-title the issue to "Design a mechanism to generate a synthetic *cluster management* workload and play it" to make it clear we're talking about a cluster management workload, not an application-level workload.

Density test is good but I think we can do something more thorough. I think we can use serve_hostname pod instead of pause because serve_hostname has an HTTP endpoint you can hit to verify it is working (IIRC pause does not have any kind of server?). I agree guestbook is not necessary.

Here is an example random workload of the type I was thinking:
* Create N replication controllers, verify that the pods come up
* Kill a pod, verify the RC creates a replacement pod [and/or have a pod that terminates on its own]
* Kill a VM, verify the RC creates a replacement pod (there is some overlap here with #7051)
* Randomly resize some of the RCs, verify pods were killed or created (depending on direction of resize)
* Stop an RC, verify the pods disappear and then the RC disappears
* Update PodSpec template in RC, grow the RC, and verify the new pods match the new spec
* Create a Pod with a label matching an existing RC's selector, verify the RC "adopts" the pod
* Remove a label from a pod that is being managed by an RC (so that the pod no longer matches the RC's selector), verify the RC creates a replacement pod and does not kill the pod you removed the label from
* Create a service, verify that connecting to it from a pod eventually reaches all the live pods of a service (round-robin load balancing)
* Having created a service, do things like change labels on pods to cause them to join/leave the service, delete pods (e.g. by scaling down RC), add pods (directly or by scaling up RC), and always verify that the expected thing happens
* Delete a service
* Update label selector on a service, verify expected thing happens

I'm sure you have additional ideas, but I think a complete workload generator would generate all of these kinds of events in random orders and scales.

**Comment by quinton-hoole** [comment]
I feel fairly strongly that testing the cluster management infrastructure only, in the absence of any realistic CPU, memory and disk load on nodes introduced by pods is necessary but definitely not sufficient, as real-world clusters are not full of idle pods, and part of our infrastructure share machines with these pods.

Do we have a separate issue tracking the testing of cluster management performance and stability in the presence of significant Pod-induced load yet?  I know Satnam and I have discussed it a few times, but I can't find an explicit issue for it.

I'm thinking along the lines of scheduling as many instances of a simple cpu-bound pod ("keep-calculating-pi-to-many-decimal-places"?) as a cluster will accommodate, and then running cluster management performance and stability tests against that cluster.

**Comment by davidopp** [comment]
@quinton-hoole I think ideally we should do all of this in one test. So what would you think of the following:
1) First, we build the test the way I described, using serve_hostname
2) Then, we replace serve_hostname with pods that generate a more realistic "application-level" workload

One benefit of structuring the test this way is that if we hit a failure, we can in theory re-run the test with non-load-inducing test pods (revert from 2 to 1) and see if the pods are contributing to the problem.

**Comment by quinton-hoole** [comment]
Yes, that's exactly what I had in mind.  

In a really ideal world :-)  we'd have a few different app-level workload pods, which saturate each resource (CPU, Mem, Disk I/O, Network) individually, and collectively.  But just starting with CPU would be a big improvement over what we have today.

**Comment by davidopp** [comment]
One more thought: We could do a first version of this that just generates the cluster operation workload and doesn't do any of the "verify" steps. We can add verification as a later step. That way we'll have a good performance benchmark more quickly than if we have to implement verification at the same time as workload generation. (These steps are orthogonal to whether we use serve_hostname or a more realistic application-level workload like @quinton-hoole described.)

**Comment by piosz** [comment]
Let's make a decision what to do for 1.0.

I implemented the first version of load generator as load.go e2e test which creates a number of RC of various sizes and play with them by resizing, removing and recreating. The test hasn't been enabled on Jenkins yet but we are about to it (see #8873).

As for 1.0 I propose to add a service on top of each RC, query it with http requests and expect a reply from each pod.

The more sophisticated load generator can be done as post-1.0 work. It may be a good project for intern/GSOC participant.

Any objections? @davidopp @roberthbailey @quinton-hoole

**Comment by davidopp** [comment]
SGTM.

**Comment by wojtek-t** [comment]
SGTM

**Comment by piosz** [comment]
I spent some time trying to stabilize the test and make it green on Jenkins, but it still tends to fail. The priority should be to reach that goal. Also I talked with @fgrzadkowski and implementing services seems to not add too much value for performance related issues and it will probably make stabilization harder.

However if anyone wants to implement it feel free to do it. I won't work on it until the end of next week.

**Comment by davidopp** [comment]
I've reopened #7561 to track the problems with the load test. I'm going to move this issue out of the 1.0 milestone because nobody is going to have time to add the service thing before the code deadline and, as you say, it's not super-valuable anyway.

**Comment by kargakis** [comment]
Related: https://github.com/kubernetes/perf-tests/tree/master/clusterloader
