### ISSUE TITLE
curl will hang, if service's endpoint is not ready type as nodeport 

### ISSUE THREAD

**Issue by zhulinhong** [kubernetes/kubernetes#31435]
**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):
## I search the keywords "kube-proxy curl hang"

*_This a BUG REPORT *_ (choose one):

**Kubernetes version** (use `kubectl version`):  1.3

**Environment**:
- **Others**:

**What happened**:
I think it is independence the environment, so I did not describe them.

If I create a type of nodePort  service , kube-proxy will use net.Listen to openLocalPort in every node.
If the service have no endpoint (means pod have not started, or start failed.), the client like  curl http://xxxx:xxx will hang. It will not timeout.

I had tried it just use net.Listen to create a TCP Listener, it can be reproduce.

**What you expected to happen**:
I expected  it will timeout, if the endpoints is not ready.

I think it will infect the third-part to  access the service that the endpoint have not ready. 
The third-part client will hang.

**How to reproduce it** (as minimally and precisely as possible):
1. Create an nodePort  service without any endpoint.
2. curl http://node-ip:nodeport. The curl will always hang. 

**Anything else do we need to know**:

**Comment by AdoHe** [comment]
@thockin ptal.

**Comment by bprashanth** [comment]
We should jump to REJECT for the given destination port if there're no endpoints. Sounds like that isn't happening.

**Comment by thockin** [comment]
This is because we set a REJECT rule for the service IP but we do not set a REJECT for the nodePort or for the LB VIP.  What we really should do is detect all cases and reject.  Conveniently we have logic that does this - it is the DNAT rules.  Unfortunately, that is in the nat table and REJECT has to happen in the filter table.

@freehan just added a common way to mark packets for DROP.  Maybe we should have the equivalent for REJECT ?  Or is that getting to be too much?

**Comment by freehan** [comment]
What if we just drop it??

**Comment by bprashanth** [comment]
Reject gives away less information than drop to a port scanner because it looks like any other unoccupied port. If we drop random ports people might figure out something should/will soon be there. Haven't spent enough time thinking about corner case exploit vectors where this might matter.

**Comment by freehan** [comment]
based on http://www.chiark.greenend.org.uk/~peterb/network/drop-vs-reject
It looks like DROP send no response. And REJECT send back ICMP destination-unreachable.

**Comment by thockin** [comment]
Yeah, we talked about making your MARK-DROP do a reject but you advocated
for black ole rather than reject.  DROP emulates a dead machine.  REJECT
emulates a live machine but dead port.  That is what we want for services.

Would it be bad if your firewall rules rejected?  I don't know.

Would it be bad to consume a 3rd bit for REJECT (alongside DROP and MASQ)?

**Comment by zhulinhong** [comment]
Is there certain way to fix this issue ? I hope I can to try it firstly.

**Comment by bprashanth** [comment]
insert a jump to the REJECT target in the filter table INPUT chain for the given destination port and retry curling

**Comment by freehan** [comment]
@zhulinhong Feel free to put together a PR.

Just have to add iptables util chains for REJECT. It should be similar to this [commit](https://github.com/kubernetes/kubernetes/pull/30486/commits/85fdeb47426ec6615a3af642a4b9247eb7dc4ef4)

Then just change the current REJECT [logic](https://github.com/kubernetes/kubernetes/blob/master/pkg/proxy/iptables/proxier.go#L1069) to use KUBE-MARK-REJECT on KUBE-SVC chain if there is no endpoints.

**Comment by zhulinhong** [comment]
@freehan @bprashanth  thx a lot. I will try it.

**Comment by thockin** [comment]
Great!

**Comment by m1093782566** [comment]
@freehan I am trying to fix this issue and have some questions to ask you.

> First need to add iptables util chains for REJECT. It should be similar to this commit

I find this [PR](https://github.com/kubernetes/kubernetes/pull/30486/commits/3bf8679232fd0db511cbbeea5e68c707754f92bc) is a very useful reference for me. Besides, this PR mainly fixes two issues: 

1. syncNetworkUtil in kubelet 

2. fix loadbalancerSourceRange on GCE

My first question is should I create a util in kube-proxy just like what you did in kubelet(syncNetworkUtil)? Or something like [this code block](https://github.com/kubernetes/kubernetes/blob/master/pkg/proxy/iptables/proxier.go#L1080-L1090) is just works?

**Comment by freehan** [comment]
@m1093782566 Sorry for the late response. Notification got buried.

We are moving network utils from kube-proxy to kubelet. So it would be better to manage all new iptables util rules in `syncNetworkUtil`. You can add another iptables util chain for Reject. Similar to the existing ones (DROP and MASQ).


Since REJECT has to happen in filter table, we mark it for REJECT in nat table and let the util chain to actually reject it in filter table. So the question is where to mark it for reject. Since all endpoints are not ready, why not just mark REJECT in the beginning. Somewhere in KUBE-SERVICES or KUBE-SVC. Thoughts?

**Comment by thockin** [comment]
Fixed in 1.7
