### ISSUE TITLE
multi-zone clusters apparently not spreading deployments evenly across zones in some cases

### ISSUE THREAD

**Issue by quinton-hoole** [kubernetes/kubernetes#31447]
https://kubernetes.slack.com/archives/sig-federation/p1472135037001188

andrejvanderzee [7:23 AM]  
We have started using Federation Light for spreading pods over availability zones by labeling the nodes:
```NAME            STATUS    AGE       LABELS
192.168.64.69   Ready     30d       failure-domain.beta.kubernetes.io/region=isp,failure-domain.beta.kubernetes.io/zone=dc-01, ...
192.168.64.71   Ready     30d       failure-domain.beta.kubernetes.io/region=isp,failure-domain.beta.kubernetes.io/zone=dc-01, ...
192.168.64.72   Ready     29d       failure-domain.beta.kubernetes.io/region=isp,failure-domain.beta.kubernetes.io/zone=dc-02, ...
192.168.64.73   Ready     29d       failure-domain.beta.kubernetes.io/region=isp,failure-domain.beta.kubernetes.io/zone=dc-02, ...
```
(edited)

[7:24]  
We have many deployments with two replicas, but they are not always spread over dc-01 and dc-02.

[7:25]  
Are there any other factors that I should take into consideration?

**Comment by justinsb** [comment]
Zone spreading is a weighting, not a guarantee (just like node-spreading).  Do the nodes in the zones have roughly equal free capacity etc?  Otherwise the scheduler might consider it more important not to overload a particular node, vs spreading the load.  Consider the case that you have one node in an AZ, and 10 in another: you don't really want to overload that one node.  Nor do you want to _not_ run pods simply because they don't fit on that one node, when there is plenty of capacity in another zone.

Note though that if you use volumes (on AWS or GCE), they will force the zone allocation.  If you use PetSets also, dynamic volumes will be spread across zones, and thus a PetSet is (informally) always going to spread across your zones.

**Comment by andrejvanderzee** [comment]
@justinsb Let me clarify. Both AZ have equal number of nodes and each node is identical in terms of resources. We see this in two clusters each with two AZs (one has 2 nodes and the other 3 nodes in each AZ). We are not using PetSets nor PVs, just plain Deployments. 

At the time of actual deployment, it might be that some nodes have more free space than others, which is difficult to track. But, there were definitely enough resources to run the PODs in both AZs. 

Finally, none of the Deployments have specified any explicit resource limits for its containers, nor did we specify a default resource limit for any namespace yet.

**Comment by quinton-hoole** [comment]
Closing for now.  Does not seem like a bug.  Feel free to re-open once you've studied the scheduling code as discussed on slack @andrejvanderzee

**Comment by justinsb** [comment]
Or if you can capture some logs from the scheduler, that would also help diagnose.  This is a heuristic unless you're using volumes or some other constraint, so if you have a log that shows poor placement we could tweak the heuristics!

**Comment by andrejvanderzee** [comment]
The scheduling algorithm spreads over nodes and mixes in zones when it has the fail-over labels. Unfortunately, it hard-coded a magic number for combining node and zone scheduling:

> // When zone information is present, give 2/3 of the weighting to zone spreading, 1/3 to node spreading
> // TODO: Any way to justify this weighting?
> const zoneWeighting = 2.0 / 3.0

Note the TODO.
