### ISSUE TITLE
[k8s.io] Monitoring should verify monitoring pods and all cluster nodes are available on influxdb using heapster test failing

### ISSUE THREAD

**Issue by vishh** [kubernetes/kubernetes#31626]
This test is failing in the "kubernetes-soak-continuous-e2e-gke-gci" test suite often - 
https://k8s-testgrid.appspot.com/google-soak#soak-continuous-e2e-gce-gci

**Comment by vishh** [comment]
cc @dchen1107

**Comment by pwittrock** [comment]
@dchen1107 This one as well please

**Comment by pwittrock** [comment]
[link](https://k8s-testgrid.appspot.com/google-1.3-1.4-upgrade#gce-cvm-1.3-cvm-1.4-upgrade-cluster)

@piosz can you take a look at this.  It is an urgent P0 blocker for launch.

**Comment by dchen1107** [comment]
@piosz, please ignore the initial description, and I believe that is fixed already. @pwittrock added this as the release blocker due to the failure occurred during the upgrade tests.

I took a quick look at the failing test, and noticed that

* The test only failed with https://k8s-testgrid.appspot.com/google-1.3-1.4-upgrade#gce-cvm-1.3-cvm-1.4-upgrade-cluster, and always passed with https://k8s-testgrid.appspot.com/google-1.3-1.4-upgrade#gce-cvm-1.3-cvm-1.4-upgrade-cluster-new. This means when upgrading to 1.4 from 1.3, 1.3 tests failed, but 1.4 test passed. 
* Also https://k8s-testgrid.appspot.com/google-1.3-1.4-upgrade#gce-cvm-1.3-cvm-1.4-upgrade-master failed too. This indicates the same root cause as the above.
* The test failed with the following error message:
```
[It] should verify monitoring pods and all cluster nodes are available on influxdb using heapster.
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/monitoring.go:43
Sep 19 14:12:36.665: INFO: Expected one column for query "show tag values from \"cpu/usage\" with key = pod_id". Found [key value]
```
* I checked the changes at related to test code path, and I noticed that we upgraded influxdb in 1.4, and changed the related monitoring e2e tests at: https://github.com/kubernetes/kubernetes/commit/2c19b189c7ff2eab13491da2d4072bd482adf072

I think that is the cause here.

**Comment by piosz** [comment]
Thanks @dchen1107 for investigating. The test has changes between 1.3 and 1.4 and the version from 1.3 branch won't work with 1.4.

Also there is a known issue with OOMing inlfuxdb which is not a blocker for the release (see https://github.com/kubernetes/kubernetes/issues/27630#issuecomment-244360020).
