### ISSUE TITLE
kube-proxy should batch updates

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#31631]
I created 1000 Services with no endpoints (same selector).  Then I created a single pod that matched them all.  Kube-proxy took upwards of 30 seconds to update all the chains because it was doing a full save/process/restore cycle for each service.  It could instead batch up changes and sync after 2 seconds of accumulation, or something.

**Comment by thockin** [comment]
@kubernetes/sig-network

**Comment by leopoldxx** [comment]
will k8s consider that  different services should be  separated on different  nodes(kube-proxy)? 
so kube-proxy only need to monitor the services that assigned onto it.  this maybe speed up the iptables update process and also save ports on nodes.

**Comment by thockin** [comment]
No.  All nodes must support all service VIPs.  It may be that EVENTUALLY we
have multi-tenancy clusters and then we can reduce, but that only buys time.

**Comment by MrHohn** [comment]
What about add one more layer between getting service/endpoint update from apiserver and calling `OnServiceUpdate()`/`OnEndpointsUpdate()`?

We could inject batching mechanism in this layer. Do things like setting lower bound interval and upper bound timeout:
- lower bound interval will be used for batching operations. If two operations show up within this interval, batch them
- upper bound timeout will be used for forcing update. If it's been a certain amount of time since last  OnUpdate() we called, force it to update current batch.

**Comment by bprashanth** [comment]
we already do some level of batching, checkout pkg/proxy/config/config.go, essentially if a notification somes in and takes 5s to apply, the notifications that come over that 5s are batched because we apply a snapshotted update (so if 10 updates come in that 5s, we don't apply each update individually taking 50s, we just apply all 10 new endpoint/svc in one shot taking 5s). 

That's probably where we would add some smarts, you can try writing a go benchmark to measure any gains locally (I don't always find this useful, sometimes it is, eg: https://github.com/kubernetes/kubernetes/blob/master/test/integration/master/master_benchmark_test.go).

**Comment by rbtcollins** [comment]
This might be root cause for #34064 and #33887 - came here after we had a bug lead to 4000 services in a namespace and other namespaces started seeing extraordinarily long endpoint bringups.

**Comment by bowei** [comment]
/assign @freehan

Did the batching changes for kube-proxy go in? Is this still relevant?

**Comment by freehan** [comment]
ref: https://github.com/kubernetes/kubernetes/pull/45343
