### ISSUE TITLE
dashboard https Unauthorized

### ISSUE THREAD

**Issue by chowyu08** [kubernetes/kubernetes#31665]
Dashboard version: 1.1
Kubernetes version: 1.3.6
Operating system: ubuntu14.04
Go version:1.6.2
Ideploy kubernetes and dashboard as http://kubernetes.io/docs/getting-started-guides/ubuntu/

I can access the dashboard http://master-ip:8080/
bur when I access https://master-ip:6443/ ,return "Unauthorized"
why?

**Comment by workhardcc** [comment]
I have the same issue. And I think author maybe haven't consider it yet.
https://github.com/kubernetes/dashboard/issues/1116

**Comment by floreks** [comment]
I'm guessing that your clusters are using certificates for secure communication over HTTPS. There are 2 issues here.

1. Browser doesn't recognize root CA so it can't trust that connection is safe. We can bypass that and still use it.
![zrzut ekranu z 2016-09-15 15-50-35](https://cloud.githubusercontent.com/assets/2285385/18552318/2ca919ba-7b5c-11e6-9f2f-5892502433d8.png)
2. API Server needs client certificate/token/user and pass (depends on configuration) to authorize client otherwise it will return `Unauthorized`.

It's easy to authorize with curl because you can easily provide required data.
`curl https://<MASTER_IP>/version --cacert ca.crt --cert admin.crt --key admin.key`
`curl https://<MASTER_IP>/version --header "Authorization: Bearer $TOKEN"` <certs>`

With browser it's more complicated than that. There are several ways to access dashboard:

1. You can expose it through service using NodePort and access it with `<MASTER_IP>:<NODE_PORT>`. (Not Safe)
1. Import certificates into your browser.
1. Use `kubectl proxy` and go to `http://127.0.0.1:8001/` (bind address can be changed). It will handle SSL tunneling if your `kubeconfig` file is configured to use secure connection.


Regarding second option. I can provide some information how to do that using firefox.

1. Import generated CA certificate into the browser.
![zrzut ekranu z 2016-09-15 16-05-47](https://cloud.githubusercontent.com/assets/2285385/18552795/4c108a3e-7b5e-11e6-8f5b-0601d53418f4.png)
1. Import user certificate to `Your Certificates`. If you have 2 separate certificates `crt` and `key` it's best to merge them into `PFX/PKCS#12` certificate because it's easy to import it directly into the browser certificate store.
![zrzut ekranu z 2016-09-15 16-09-44](https://cloud.githubusercontent.com/assets/2285385/18552916/d84f3996-7b5e-11e6-9b84-6b5945d805b6.png)

If certificates are generated correctly then popup will be displayed on next attempt to access api server over HTTPS.
![zrzut ekranu z 2016-09-15 16-12-04](https://cloud.githubusercontent.com/assets/2285385/18553059/5bd1421e-7b5f-11e6-90cf-720de5f3883d.png)

You should see the dashboard now. :)
![zrzut ekranu z 2016-09-15 16-14-16](https://cloud.githubusercontent.com/assets/2285385/18553110/8d2cb956-7b5f-11e6-8ed2-c411e70b8461.png)

I don't know how to use bearer token in browser. Possibly it requires some manual work to add data to HTTP header before sending request to api server.

There are of course other options to authorize user. Kubernetes supports ABAC, RBAC and much more. Still, all of this is related more to kubernetes core and cluster configuration than to the dashboard itself.

**Comment by liggitt** [comment]
The browser is required to authenticate when accessing the secured API server port. As https://github.com/kubernetes/kubernetes/issues/31665#issuecomment-247342834 demonstrates, that can be done with certificate-based authentication.

For token-based authentication, browsers do not give you a way to send bearer tokens automatically with your requests.

The dashboard describes how you can use `kubectl proxy` which adds in your authentication credentials, and lets you access the dashboard locally through the proxy - https://github.com/kubernetes/dashboard#usage
