### ISSUE TITLE
e2e flake: Failed to list images in project "google-containers" and zone %!q(*string=0xc8200e4750)

### ISSUE THREAD

**Issue by jsafrane** [kubernetes/kubernetes#31694]
Logs: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/30825/node-pull-build-e2e-test/21451/

```
F0825 19:13:54.910873    2524 run_remote.go:168] Could not retrieve list of images based on image prefix "gci-dev-.*": Failed to list images in project "google-containers" and zone %!q(*string=0xc8200e4750)
exit status 255
Build step 'Execute shell' marked build as failure
[xUnit] [INFO] - Starting to record.
[xUnit] [INFO] - Processing JUnit
[xUnit] [INFO] - [JUnit] - No test report file(s) were found with the pattern '_artifacts/**.xml' relative to '/var/lib/jenkins/workspace/node-pull-build-e2e-test' for the testing framework 'JUnit'.  Did you enter a pattern relative to the correct directory?  Did you generate the result report(s) for 'JUnit'?
```

**Comment by dims** [comment]
cc @vishh @Random-Liu (possibly triggered by https://github.com/kubernetes/kubernetes/commit/5c332e0d0245d9735839b4810e45fe6e54c09adb)

**Comment by Random-Liu** [comment]
@dims, that PR only changed script for local development, the Jenkins job won't be affected at all. :)

**Comment by dims** [comment]
@Random-Liu next time i will add an emoji for a wild guess :)

**Comment by fejta** [comment]
I suspect this was an error calling gcloud? Would be nice if we had some additional logs

**Comment by ixdy** [comment]
Two and a half issues with the error message:
* `zone` is a pointer, so it should be dereferenced
  * I don't think `zone` applies to the `List` command anyway, so we can probably remove it from the error
* the `err` returned by the compute library is being thrown away

I just created https://github.com/kubernetes/kubernetes/pull/32169 to address these issues (though not the root cause).
