### ISSUE TITLE
allow storageClass.provisioner to be empty

### ISSUE THREAD

**Issue by childsb** [kubernetes/kubernetes#31723]
For manually created volumes that belong to a storageClass there is no provisioner type.  The field should be permitted empty in storageClass object.

**Comment by eparis** [comment]
@saad-ali @thockin @kubernetes/rh-storage @kubernetes/sig-storage

**Comment by saad-ali** [comment]
This may lead to some potentially confusing user experiences: If a storage class is allowed to be defined with no provisioner, imagine a storage class with no provisioner marked as default. A user creates a PV and PVC both without storage class, admission controller automatically adds the default storage class to the PVC, but since there are no PVs matching the default storage class and no provisioner specified, the PVC will remain unbound indefinitely.

**Comment by saad-ali** [comment]
I might be misunderstanding something. So please correct me if I'm wrong: my understanding is that this scenario can occur in the cloud world as well: if a storage class is able to be created without a provisioner (and be marked as default), and PVCs have default storage classes added to them, and PVs do not, then a user could easily end up in a scenario where their lack of awareness of storage classes leads them to create a PVC that can't be fulfilled. If storage classes are required to have provisioners then this problem doesn't exist. What is the driver for allowing storage classes without provisioners?

**Comment by eparis** [comment]
I'm thinking of a situation in which I have 2 different types of storage inside my enterprise, neither with a dynamic provisioner. Maybe one is an array backed by ssds and one by spinning platters. I want users to be able to create PVC w/SC=gold and get the ssd and PVC w/SC=silver and get the spinning platters.

The fact that these are manually or dynamically provisioned is not at all relevant to the representation of storage as classes.

I'm not sure what this really has to do with defaults though. I agree that a storage admin can mess up the default class. One could create a default storage class in GCE with an AWS EBS provisioner which would (obviously) always fail. I'm not sure how the potential to get a default storage class unable to satisfy a claim is a justification. In fact I may choose to manually provision 1000 PVs and actually use a non-provisioning StorageClass as the default. It's on me, outside of kubernetes, to realize that all 1000 have been used and I need to make more...

Today I can manually create a PV with a StorageClass. I can create a PVC with that StorageClass. But I can't create a StorageClass object to represent those (non dynamically provisioned) PVs. I want to represent things to my user.

**Comment by saad-ali** [comment]
I can buy that. If you don't have provisioners and still want to use storage classes, you should be able to. 

> One could create a default storage class in GCE with an AWS EBS provisioner which would (obviously) always fail

Good point, my scenario requires cluster administrator to mark a Storage Class without a provisioner as default, which doesn't make sense. As you pointed out, blocking this behavior is not sufficient to prevent cluster admins from shooting themselves in the foot by, for example, creating bad storage class with invalid provisioner params. 

@thockin thoughts?

**Comment by thockin** [comment]
All SCs are provisionable, they just have variable latency, up to and
including waiting for storage admin to notice a pending claim, ordering a
disk from Amazon and racking it into a machine.

So the provisioner should be "manual" or "example.com/file-a-ticket".

On Aug 30, 2016 5:43 PM, "Saad Ali" <notifications@github.com> wrote:

I can buy that. If you don't have provisioners and still want to use
storage classes, you should be able to.

One could create a default storage class in GCE with an AWS EBS provisioner
which would (obviously) always fail

Good point, my scenario requires cluster administrator to mark a Storage
Class without a provisioner as default, which doesn't make sense. As you
pointed out, blocking this behavior is not sufficient to prevent cluster
admins from shooting themselves in the foot by, for example, creating bad
storage class with invalid provisioner params.

@thockin <https://github.com/thockin> thoughts?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/31723#issuecomment-243625587>,
or mute the thread

**Comment by jsafrane** [comment]
So, summing up the discussion so far:

- `StorageClass.Provisioner` **must** be filled (and it's checked in validators)
- It should be possible to set it to some value that does not represent a volume plugin.
  - the volume controller now complains that it cannot find a volume plugin named "example.com/file-a-ticket"

This is very close to external provisioners as I proposed a while ago in #30285. 
The controller should silently ignore unknown `provisoner` values and expects that someone creates a PV, be it external provisioner or storage admin.

The only problem is a typo in a `StorageClass.Provisioner` value - PVCs requesting this class would be pending forever, without any error sent to the user.

**Comment by eparis** [comment]
@thockin ok, so I'd like to see us jam a 'manual' provisioner into 1.4.  Sound good?

**Comment by thockin** [comment]
What is a "manual" provisioner?  You mean the string constant?  Undecored
named ("manual" as opposed to "kubernetes.io/manual" are explicitly
reserved for end users, so Joe admin can jam whatever he likes in there..

**Comment by eparis** [comment]
Any 'well known name' which won't cause error messages and will print one event/log if a PVC is unsatisfied which states that a PV needs to be manually provisioned. @rootfs said it could be done with a a non-existent provisioner (say nfs) but it leaves both scary error messages and not a good result for the end user...

**Comment by thockin** [comment]
"manual" or "call-eric-at-123-867-5309" are equally valid.  Why do we need
to codify what string to put there.  Just put something

**Comment by eparis** [comment]
as long as it doesn't leave any scary messages in the logs and leaves the user some sane message why things didn't work...

**Comment by thockin** [comment]
Agree - the logs should be considered.  I'm looking at Jan for details
there.  Maybe log iff provisioner matches "kubernetes.io/*" and we can't
find that driver.  Ignore other prefixes, including no-prefix.

**Comment by jsafrane** [comment]
I am not that good with English, proposing a normal event sent to the claim with: `cannot find provisioner %q, expecting that a volume for the claim is provisioned either manually or via external software`.
