### ISSUE TITLE
Couldn't delete ns was not deleted within limit: timed out waiting for the condition, pods remaining: []

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/kubernetes#31740]
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:127
Aug 16 08:11:16.645: Couldn't delete ns "e2e-tests-v1job-gmj3l": namespace e2e-tests-v1job-gmj3l was not deleted within limit: timed out waiting for the condition, pods remaining: []
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:265

**Comment by derekwaynecarr** [comment]
Now that https://github.com/kubernetes/kubernetes/pull/31636 has merged, we should see a reduction of these flakes, or if they do occur we will have clearer information on what remained and why and be able to better classify.

The error message reported will differ.

For messages of the form:

__"namespace %v was not deleted with limit: %v, pods remaining: %v, pods missing deletion timestamp: %v"__

I plan to submit a PR tomorrow that updates the namespace controller to delete pods *last*.  The idea is that this will ensure the things that spawn pods will be deleted first and are more likely to have their corresponding controllers see those deletes and stop sending additional requests to create new pods that then need to be deleted by the namespace controller.  This may also reduce the incidence of when we see unexpected pods in our verification stop inducing a rate limited back-off.

__"namespace %v was not deleted with limit: %v, pods remaining: %v"__

this most likely means the `kubelet` did not delete pods in time.  i would want to automatically forward issues of that type for sig-node to debug.

__"namespace %v was not deleted with limit: %v, namespaced content other than pods remain"__

this would let us look at the log to see what content is actually remaining that we spit out.  if some content in a test is deleted but not others will help us better diagnose what is special there...

__"namespace %v was not deleted with limit: %v, namespace is empty but is not yet removed"__

this is the most interesting case, but it is hard to know if its distinguished from this issue since the code prior to the referenced pr did not distinguish pods being gone from other resources not being deleted in time as for why the namespace was not deleted.

This is a long winded way of requesting that we close the existing issues and open new issues to make it easier to triage as flakes appear post https://github.com/kubernetes/kubernetes/pull/31636 with a crisper error message.

@ncdc @pwittrock - thoughts objections?  there are a number of duplicate issues.

**Comment by ncdc** [comment]
Sgtm

**Comment by pwittrock** [comment]
SGTM.
