### ISSUE TITLE
PetSet fencing

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#31762]
Jotting down some thoughts so we can start fleshing it out in time for 1.5.
## Problem

Currently petset uses ns/name as an implicit lock. So there are situation where we might: 
- deleted a pod from the apiserver
- but the pod is still alive on the node
- and the petset controller has created another pod with the same name on another node
- and kube-dns has re-programmed dns to point pet-0 at this new ip 
- but some clients are pointing at pet-0(2) and some at pet-0(1) because they haven't resolved dns. 

To prevent such situations, we need to ensure that exactly one instances of an application occupies a given petset index. Since this is not a new problem in distributed systems, one option is to completely defer to the application layer to implement a consistency protocol. In reality this places a pretty big burden on the app.
## Proposal

So I'm proposing the following fencing guards: 
- Don't delete pets from node controller (or make this conditional)
- Use a RWO volume for fencing
- Take a lease via apiserver annotations

The first eliminates ONLY the most common cause of duplicity. 
The second only works if you trust the storage layer, or actually need pet storage.
The third needs to be our last line of defense, and happen at 2 points of the pet lifecycle: 
1. Prevent PetSet controller from creating pet-0(2) based on the lock annotation
2. Prevent pet-0(2) from ever starting by blockig in an init container

None of these require changes to the petset resources IMO, unless we decide to add the locks to the petset.
## Example scenario

To break down some cases, say we do the following:   
1. Pipe the petset name as an env var into all pets
2. Each pet writes an annotation of the form {$POD_NAME: $POD_UUID} in the petset
3. The pet deletes the annotation in terminationGrace/postStop

Assuming we have a node controller or kubelet bug that leads to node controller actually deleting pet-0, or user deletes pet-0 but kubelet fails to kill container, the petset controller will not create pet-0(2) because of the annotation.

Assuming we also have a petset controller bug, so petset-0(2) gets created: 
- pet-0(2) comes up and reads {pet-0:different-uuid}, crashloops
- kubelet deletes pet-0 (either because partition recovers, or it recovers from its own bug)
- pet-0 erases annotation within terminationGrace
- pet-0(2) starts up and writes its annotation

The impact is a loss of availability during partition, and if there's a second bug that prevents terminationGrace on pet-0, pet-0(2) will remain in crashloop till human erases annotation.
## Food for thought
1. Do we need a third layer of defense in the form of a sidecar that commits suicide if the annotation is set to something else?
2. We should probably allow nodecontroller deletion gate to be opt in
3. This adds a coupling between pets and apiserver that I dislike

@kubernetes/sig-apps @smarterclayton @erictune

**Comment by ibotty** [comment]
You don't mension partial netsplits. How are these going to be handled? Is the local petset container supposed to kill itself whenever it can't update the annotation? Who is going to do that (a local agent, like the kubelet)?

**Comment by xiang90** [comment]
@bprashanth 

One stupid question. You mentioned `but some clients are pointing at pet-0(2) and some at pet-0(1) because they haven't resolved dns.` in the issue. Can you explain why this is a problem in practice? We do not control DNS caching anyway, do we? If the any client connected to the old pod, what might happen? Do we have an example bad case in mind?

**Comment by ibotty** [comment]
It can lead to split brain. One client weites something to pet-0(1), another client writes something conflicting to pet-0(2).

**Comment by xiang90** [comment]
> It can lead to split brain. One client weites something to pet-0(1), another client writes something conflicting to pet-0(2).

Shouldnt the application itself handle this? What would be an example application that would be affected by this?

**Comment by smarterclayton** [comment]
Proposal 1 should be forgiveness (forgiveness is an indication that you
tolerate disruption on the node).  Node controller should respect it.  If
we can verify that the implementation matches the expectation we're covered
there.

For proposal 2, I want to make the general statement that "All volumes are
responsible for owning their 'locks' for RWO, that the attach-detach
controller is the component that enforces locks if necessary, and new
volume types should take that into account when writing".  That allows us
to say you can use RWO for fencing except in these specific cases.  The
"these specific cases" we need to explore - @thockin and I were discussing
this for people using/abusing two pods on the same node, and so we need to
figure out whether that could surprise a petset owner who doesn't set
exclusions (or alternatively, benefit them).

**Comment by doron-fediuck** [comment]
What will be the consequence of network issues while using NFS?
So one node sees this in D-state. What happens next?

**Comment by smarterclayton** [comment]
NFS in RWM (read write many) should provide no guarantees.

I think it's reasonable to say that in the future it should be possible for
an NFS RWO PV (expected to be read by one user) to be "locked" by the
attach-detach controller in the same way that we expect local volumes to be
"locked" - bound to one node, and attach / detach has to unbind it.  That
allows node decisions (deletion) to control lock breaking, and technically
kicking a node out is also a signal for fencing the node.

**Comment by bprashanth** [comment]
@xiang90 you can have a petset that has no concept of conflict resolution, maybe it isn't even a database. This is not a new problem in distributed systems, the problem is not all apps are distributed. The petset guarantee is that we never create 2 pet-0s, but as described, we're using the ns/name in apiserver as a lock, and ns/name can get deleted without the actual process dying. 

So if you have 2 slaves with a config that says: 
```
master: pet-0
```
regardless of when the slaves resolve DNS, they should not hit 2 live database masters. 
Fencing will help with this problem.
Sticky ips will also help, but the races are greatly reduced just with fencing.

**Comment by smarterclayton** [comment]
To extend the analogy further, the node controller is a lock breaker today (thus introducing split brain) as is anyone who does delete grace-period=0.  So we need to figure out how to make lock breaks clearer as well.

**Comment by bprashanth** [comment]
So do we trust the storage layer enough to just use a volume lock and leave the petset+init container+POD_UID idea as an exercise for the reader (documented of course)? meaning the petset controller won't respect the annotation, it's up to the petset author to build this into init and teardown if they don't want to use volumes.

**Comment by xiang90** [comment]
@bprashanth We do not want the database to use distributed lock service to elect a master? We want them to fully rely on petset instead?

**Comment by bprashanth** [comment]
hmm, this is not about leader election per se. The guarantee is that there is a set of indices {1..N} and there should only be one process behind any of these indices. We can frame this as N leader election problems.

The goal here is that a mysql admin should be able to safely deploy mysql without understanding lease/lock api. That might take the form of the system doing all the heavy lifting, or us providing standard init/sidecar containers, but I think requiring the admins to write a custom entrypoint means they have to restructure their app to run safely on kube.

**Comment by smarterclayton** [comment]
I've wondered whether the node could do its own lease.  Follow rules and shoot pods in the head if it looses connection with master for X seconds.  That makes it easier for the pods to work.

**Comment by xiang90** [comment]
>  We can frame this as N leader election problems.

Then it can be further reduced to 1 leader election or lease problem I guess. I am not opposite to the idea, just want to make sure I understand what we want to achieve. Thanks for your explanation.

**Comment by bprashanth** [comment]
yeah here the leader is the petset controller

**Comment by bprashanth** [comment]
> I've wondered whether the node could do its own lease. Follow rules and shoot pods in the head if it looses connection with master for X seconds. That makes it easier for the pods to work.

A limitation of the current proposal is that pet-0(1) holds the lock for the duration of the netsplit. If we evolved it to some variantion of STONITH, we could create a replacement sooner.

**Comment by smarterclayton** [comment]
True, but most STONITH relies on both sides doing their best to shutdown.
A node problem detector (at the cluster level) could fence by calling out
to cloud provider / IPMI / switches.

**Comment by Cloven** [comment]
I've been thinking about this issue for a while, and motivated by some of thockin's thoughts and a really interesting discussion with @smarterclayton on the main petset thread, I went through the exercise of trying to formalize the conflicts between the 'traditional model' of applications running in data centers, and the 'kubernetes model'.

From that list of conflicts I distilled down a short, and in my opinion, clean set of solutions (not all of which are trivial to implement) that I think address the issues at hand in a composable way.

I'd love to get feedback and thoughts from @smarterclayton and @bprashanth and indeed anyone else interested in this topic.

Rough first draft here:

https://docs.google.com/document/d/1hw_0edCtZ8D4FYhc6oNRTAXm8z0rApuxC6mPTnMEYFU/edit?usp=sharing

**Comment by bprashanth** [comment]
took a really quick look, you seem to have described the need for petset by enumerating the conflict points (right?). will leave comments later.

**Comment by doron-fediuck** [comment]
Looking at distributed locking and fencing, there's a project called SanLock[1] which handles distributed
locking. We could leverage it (we need some time to do a proper design) and use its built-in fencing or indeed an external fencing agent using IPMI or similar.

[1] https://fedorahosted.org/sanlock/

**Comment by smarterclayton** [comment]
I don't know that we need distributed locking as much (keep me honest)
because we already have a strongly consistent core storage and a lease
library for clients.  But we definitely need to be able to have easy
integrations into existing fencers.

**Comment by bprashanth** [comment]
Yeah I think we already have a 90% solution if you're willing to trust the storage layer to enforce RWO, because each pet in the set gets 1-N unique volumes. We're just looking for further lines of defense. Each line of defense can be something simple, like an init container writing an annotation, and the kubelet timing out and killing local containers. 

Using a third party fencing solution seems like an application layer decision, though I think we should surface this as a real option, and prototype some examples around it.

**Comment by Cloven** [comment]
@bprashanth kind of!  I felt like the failure cases hadn't been explicated, so I tried to do that.

Once I did that, collapsing the model conflicts into the smallest set led to the realization that it's possible to solve the problems in a simpler way than Pet Sets is doing it now, while at the same time being a little more composable (the state of needing-a-constraint is a logical property of a pod), extensible (pods may have other needs for special handling in the future than the currently known pet set case), and Kubernetic (again -- my opinion).

Since Pet Sets is in alpha I thought this would be good to bring up now while things are still in flux.

**Comment by bprashanth** [comment]
A better place for that discussion would be on the petset proposal then (https://github.com/kubernetes/kubernetes/pull/18016) where we discussed extending pods, extending rcs, arbitrary templatization and various other solutions

**Comment by Cloven** [comment]
alright, I'll post something over there.  Thanks!

**Comment by smarterclayton** [comment]
Prashanth and I chatted about fencing in the context of pet sets.  Allow me to relate an integrated theory of kubernetes storage fencing that we straw manned.  @kubernetes/sig-storage because you care about fencing almost as much as we do.

A persistent volume is a strongly consistent entity in Kubernetes (being backed by etcd) and represents a "lock" as far as a hypothetical consensus decider is concerned.

Persistent volumes can be bound to run only on particular nodes via label selectors (the AWS / GCE cloud binding is a special case of this, local persistent storage is a general case of this, and nothing prevents us extending it).

A persistent volume that can only run on particular nodes is safe from split brain if a) the administrator doesn't change what nodes it can run on or b) the administrator doesn't bring up a new node with the same name.

If a volume attach / detach controller (using the existing one as a stand in, could be any consistent process) applies a selector label on a PV prior to mounting it on a node (hypothesized for local persistent volumes) and removes that label if and only if the pod is cleanly shut down and acknowledged as unbound by the node (by being a finalizer on the pod), then ANY volume of ANY storage type can be safely bound to single nodes on the cluster (fibrechannel, iscsi, NFS, etc).

When a node dies, the node controller can safely delete the pod without causing split brain, as long as the attach detach controller can observe the difference between "clean" shutdown and "unclean" shutdown.  An unclean shutdown should leave the label on the PV (aka "locked to a volume").

On top of these semantics, arbitrarily complex fencing mechanisms can be othogonally implemented without the core needing to be aware of it by using the PV label selector as a lock.  A fencer could, for instance, accumulate information from many sources and make a decision to fence a node, then enforce that fencing decision by any means.  Once it has decided the node is fenced (or the storage is fenced) it can drop the PV label.  In the absence of a fencer, the admin could manually unlock the storage PV by clearing the PV selector (the PV selector is a lease with infinite duration).

This would in theory allow us to safely turn RWM volume types (which in practice are very common, i.e. NFS is defacto) into safe RWO volumes with no extra complexity.

**Comment by smarterclayton** [comment]
Also, PetSet controller can use a finalizer on the Pet pods to guarantee it receives the chance to make a decision about the pod deletion prior to actual removal safely.  A pod can be deleted by an admin with the appropriate warnings about inducing split brain by overriding that finalizer.

**Comment by saad-ali** [comment]
Drive by comment: Why does the fencing need to be applied to the PV. A PV can only be consumed via a bound PVC object, a 1:1 relation. And the PVC object can specify exactly the access mode it needs, in this case just make sure the PVCs request RWO (RWO claims can be satisfied by RWX PVs so the "turn RWX volume types into safe RWO volumes with no extra complexity" issue is non-existent). The only thing that would need to change is that we would need to enforce that if a PV is bound to a PVC that has an access mode RWO, some mechanism ensure that no other pod can reference it (e.g. https://github.com/kubernetes/kubernetes/issues/30085).

**Comment by smarterclayton** [comment]
> (RWO claims can be satisfied by RWX PVs so the "turn RWX volume types into safe RWO volumes with no extra complexity" issue is non-existent).

Not sure what you mean.  If you bind a PVC to an NFS PV and the node
is separated from the master, you *will* have two pods accessing that
NFS five minutes later when the node controller evicted the pod,.

> PVC vs PV

Yes as long as the PV can't be rebound either object can serve as a
lock.  We talked from the PV perspective for two reasons - PVs already
have zone limits and for local storage the PV needs to record which
node has the data.

**Comment by Cloven** [comment]
I feel like this is a set of architectural epicycles caused by the desire to permit split-brain in the presence of persistence (of identity, of storage, ...).  As a dev and as an op, the idea that my semi-stateful pod could suddenly get multiple doppelgangers is the problem in the first place, and no concentric collection of workarounds and failure detectors is going to clear all the edge cases.

**Comment by bprashanth** [comment]
To clarify, you can do this with a hard forgivness policy. The volume lock is a *node* level guarantee. Meaning, there are 2 pods, one which the entire system can see, and only that only the kubelet on the node can see. If you end up in this situation, there is nothing but the kubelet on the node that can protect you really (ignore how you end up in such a situation, just assume you can, it will happen :)

**Comment by smarterclayton** [comment]
And the default policy we have in place is a best-effort reclaim for
replicas, not hard forgiveness.  The node controller "breaks the lock"
after five minutes + graceful deletion.

Petsets by default will probably want hard forgiveness or another
guarantee (that's what the discussion of the PetSet Pod finalizer
would be - the PetSet controller owning the lock).  Having safe
defaults and matching user expectations is exactly what petsets are
about.  Examples and doc have to be geared to help understand this
concept, but the defaults have to be there.

You can't really use NFS in a replicaset without either explicitly
understanding this is going to happen - we may tune the experience to
warn / behave differently for those settings.

**Comment by erictune** [comment]
PV solution is not comprehensive because not all things that need PetSet uniqueness guarantee will use a volume.

**Comment by erictune** [comment]
I think PetSet should offer a "very conservative" option, where it does not start a replacement until it is sure that there is not another instance with the same name running.   Prashanth called this favoring CP over CA.  

Forgiveness doesn't give this.  STONITH could give you this depending on the implementation, but I worry about privilege escalation issues with STONITH and dependency on cloud provider to make STONITH really work.


What I do think works is for the node controller to not delete Pods (so the name remains a lock) until either (1) an app admin verifies that it is safe to proceed (using some sideband info that we can't reasonably automate and teach petset about) and force deletes the pod, or (2) the kubelet rejoins the cluster and verifies that the pod is no longer running.   This would require changing existing controllers, or putting a mode bit on Pods.  

I don't think Forgiveness is quite the thing.  Forgiveness is about sticking to a node.  It doesn't cover asserting that the Pod is not running anymore.    So, I think we need a new Pod state, and users need to be aware when Pods are in an indeterminate state.

**Comment by smarterclayton** [comment]
The finalizer I think would be the right solution.  The PetSet controller
makes the CP choice to release the finalizer (which it doesn't by default)
and an admin / fencer / cloud provider can release it.

All of the cases I can think of that would result in this state are because
the kubelet is non responsive, so maybe we would argue that the node
controller should be setting a condition when it attempts to delete pods on
dead nodes - the finalizer would prevent deletion, the node controller
would set the condition, and the admin or the fencing controller could
decide whether to break consistency or move forward.

Do we want that behavior for all pods?  If we do, then we just add the
kubelet finalizer and the node controller sets the condition.

**Comment by kfox1111** [comment]
I can see a desire to have a way to disconnect a kubelet and let the disconnected kubelet continue to function. We have some systems where they would be great to manage with kubernetes, but their network connection might be transient. but the services on the nodes would be used locally to that machine so disconnected control plane operation would be fine for them.

**Comment by bprashanth** [comment]
> Prashanth called this favoring CP over CA.

CA is not a thing, unless you mean Chartered Accountancy :)

Forgiveness kind-of gives this if you set (events=*, duration=infinity), that moves the dial all the way to C, and moving it all the way to A would be setting duration=1s and using an RC.  Like Clayton described a finalizer would also work.

The absolute easiest way to avoid removing the pod is to just delete some code from the nodecontroller. Today the nodecontroller first sets deletionTimestamp (https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/node/controller_utils.go#L58) then computes remaining grace and goes ahead to remove the pod from apiserver (https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/node/controller_utils.go#L309). If it just didn't do the second thing unless the entire node was deleted:     
* We'd end up with pods in Terminating beyond their deletingGrace, till kubelet deleted them
* RC/RS would still create replacements because they observe deletionTimestamp
* Nodecontroller already marks these pods as !Ready, so they leave a Service

What bad thing happens? 
I guess those pods still occupy some user quota.

**Comment by smarterclayton** [comment]
Pods occupy quota, pods that have specific names are blocked from being
recreated without user action, replication controllers might go a bit crazy
and generate hundreds of dead pods (if anything scheduled the pod to the
node afterwards) are the biggest ones.

Nodes can also be deleted by admins - we have pod GC for this, and we could
argue the node controller could ask for finalization on a node being
deleted in order to guarantee all pods are cleaned up.

The admin signal is either deleting a pod or deleting a node (and bypassing
finalizers) to exit CP behavior.

**Comment by bprashanth** [comment]
Aarg. 
* I want the kubelet to still honor terminationGrace. I *don't* want the nodecontroller to set the timestamp, finalizer blocks deletion, then a day later the kubelet wakes up and sigkills the db. 
* I'd also prefer something that's not-irreversibe, so I can segment a node from nodecontroller (master upgrade) and connect them back with 0 pet downtime. 

So if the node controller sets the "desired deletion" condition based on forgiveness (whenever we get it), I think we solve the second issue. The "desired deletion" condition itself solves the first issue as long as the kubelet observes it and respects terminationGrace.

**Comment by bprashanth** [comment]
Oh wait, my frustration was premature, we don't check deletionTimestamp. The kubelet always respects terminationGrace (overridden by deletionGrace): https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockertools/docker_manager.go#L1529 and uses deletionTimestamp != nil as a bool trigger (https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet.go#L1345). 

So then as long as nodecontroller respects forgivness in setting the timestamp, and never hard deletes, we have the CP version right? 

But we don't actually need to change the nodecontroller, we can let it keep trying and failing on a finalizer auto added by the petset controller. 

But we don't actually need to change the petset controller, we can document the use of finalizers in preserving petset guarantees... how far do we want to take this?

**Comment by smarterclayton** [comment]
Node controller doesn't have to set grace period to anything other than
default.  Kubelet starts clock from when it observes signal, not global
clock.  We should be good there.

Node controller + forgiveness are enough for the master separation thing I
think

Fencer would observe node separation and use disruption budget,
forgiveness, and other hand wavy metrics to perform cloud provider / metal
provider specific fencing.  It would fence by manipulating node state and
invoking external controls.  We'd need some more discussion but I suspect
the separation of the described concerns is enough to have our cake and eat
it to.

At this point, I think have enough to draw up phase two of graceful
deletion proposal and take into account the CP and fencing semantics we've
discussed as a concrete proposal, taking into account the node teams
request.  Look for that soon.

On Sep 29, 2016, at 6:21 PM, Prashanth B <notifications@github.com> wrote:

Aarg.

   - I want the kubelet to still honor terminationGrace. I *don't* want the
   nodecontroller to set the timestamp, finalizer blocks deletion, then a day
   later the kubelet wakes up and sigkills the db.
   - I'd also prefer something that's not-irreversibe, so I can segment a
   node from nodecontroller (master upgrade) and connect them back with 0 pet
   downtime.

So if the node controller sets the "desired deletion" condition based on
forgiveness (whenever we get it), I think we solve the second issue. The
"desired deletion" condition itself solves the first issue as long as the
kubelet observes it and respects terminationGrace.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/31762#issuecomment-250608571>,
or mute the thread

**Comment by bprashanth** [comment]
So to sum it up we could say: 
* If you don't want anything deleting pets (including kubectl and system components like the nodecontroller), set a finalizer. As the admin, you are responsible for lifting this finalizer on each pet.
* If you want `kubectl delete petset` and `kubectl scale petset` to work, but don't want your pets deleted when there's a network partition, set `taint.alpha.kubernetes.io/nodedown=NoExecute`

Unresolved:
* Should something else lift the finalizer? (kubelet, petset controller)
* Can we give petset authors a way to communicate with the fencer through forgiveness events? The current proposal is pretty simple (https://github.com/kubernetes/kubernetes/pull/30191)

Does this sound ok?

**Comment by smarterclayton** [comment]
I think so.  Re the unresolved:

1. Assuming that we want Kubelets that recover from partition sufficiently
to acknowledge termination (by observing and resolving deletion), and
assuming that the node controller deletes but cannot finalize, then I think
petsets should automatically set a finalizer or at least make it obvious
how to do so (probably by default?).

I think that petsets controller could probably always set the finalizer and
remove it if all the node conditions are satisfied.  If the fencer can
fence the node, I think that should propagate to the pod (perhaps fencer
explicitly completes the kubelet's termination sequence, because fencing is
logically equivalent to kubelet deletion).  Then the petsets controller
sees "dead pod" can can safely finalize.

2. Should forgiveness period on a pod be mutable?  Grace period is (via
delete action), and only the node controller / fencer has to observe.
Petsets author could increase forgiveness in some scenarios (in trying to
actually think of one, not doubting they exist).

On Sep 30, 2016, at 6:17 PM, Prashanth B <notifications@github.com> wrote:

So to sum it up we could say:

   - If you don't want anything deleting pets (including kubectl and system
   components like the nodecontroller), set a finalizer. As the admin, you are
   responsible for lifting this finalizer on each pet.
   - If you want kubectl delete petset and kubectl scale petset to work,
   but don't want your pets deleted when there's a network partition, set
   taint.alpha.kubernetes.io/nodedown=NoExecute

Unresolved:

   - Should something else lift the finalizer? (kubelet, petset controller)
   - Can we give petset authors a way to communicate with the fencer
   through forgiveness events? The current proposal is pretty simple (#30191
   <https://github.com/kubernetes/kubernetes/pull/30191>)

Does this sound ok?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/31762#issuecomment-250865215>,
or mute the thread

**Comment by davidopp** [comment]
Sorry I didn't have time to read this whole thread but I saw "forgiveness" mentioned and just wanted to explain the semantics so you can check to make sure you're using it correctly (and BTW this feature is being implemented right now; it's not in 1.4)
* different kinds of problems result in NodeController or kubelet adding a taint to the node. The scenario you're probably interested in here is "node unreachable" taint with effects "stop scheduling" and "evict" (the exact syntax is different, but this is the idea)
* a pod that wants to stay bound to a node that becomes unreachable from the NodeController can add an annotation saying that it tolerates the "node unreachable" taint with "evict" effect for X amount of time (possibly forever) which means it will not be evicted by NodeController until the taint has been there for X amount of time
* forgiveness period should in theory be mutable, but I don't know if the implementation in 1.5 will be

**Comment by smarterclayton** [comment]
Thanks - I think your second point accurately captures the need.  We
probably don't need mutability immediately, but we should explore the
design space around communication between a babysitter and the forgiveness
policy more.

**Comment by smarterclayton** [comment]
Now covered by proposal https://github.com/kubernetes/kubernetes/pull/34160

**Comment by dims** [comment]
This needs to be triaged as a release-blocker or not for 1.5 @bprashanth @smarterclayton

**Comment by smarterclayton** [comment]
Not.

**Comment by ethernetdan** [comment]
Moving to 1.7 as late to happen in 1.6. Feel free to switch back if this is incorrect.

**Comment by foxish** [comment]
The original fencing fix was implemented in 1.5. 
We can probably close this issue. There is the pod safety proposal for tracking the "fencer" component. WDYT @smarterclayton

**Comment by smarterclayton** [comment]
Agreed, an actual fencer example should be a separate proposal and we can
do a design (if the authors here are ready)

On Mar 13, 2017, at 6:36 PM, Anirudh Ramanathan <notifications@github.com>
wrote:

The original fencing fix was implemented in 1.5.
We can probably close this issue. There is the pod safety proposal for
tracking the "fencer" component. WDYT @smarterclayton
<https://github.com/smarterclayton>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/31762#issuecomment-286265314>,
or mute the thread
