### ISSUE TITLE
kube-apiserver should only try to authorize real paths

### ISSUE THREAD

**Issue by derekwaynecarr** [kubernetes/kubernetes#31798]
See discussion from here: 
https://github.com/kubernetes/kubernetes/pull/31636#issuecomment-243617070

Clients that use discovery services with dynamic client will make this call.

The namespace controller for example makes this call.

/cc @cjcullen @yujuhong

**Comment by cjcullen** [comment]
@derekwaynecarr thanks for opening this up.

The root cause on GKE is that the GKE authorizer does not know how to handle "get bindings" because we don't have a "bindings.list" [permission defined](https://cloud.google.com/container-engine/docs/iam-integration#iam_permissions) because it is not a valid path.

Right now, our authorizer is returning a 500. We should change that to a 400: It is an invalid request to authorize a "get bindings" call.

I would argue that we should be doing some minimal validation of the request path before asking an authorizer to authorize it. But I can see the counterargument that we shouldn't leak *any* information about available paths to an unauthorized user.

**Comment by cjcullen** [comment]
We could also hack around this by adding fake permissions for any non-existent methods on real objects (is bindings the only one?), but that feels gross.

**Comment by cjcullen** [comment]
cc @maisem who was also looking into this.

I'd also like to get @erictune & @lavalamp's takes on this.

**Comment by lavalamp** [comment]
Kubernetes should check paths/verbs for existing before it authorizes them.

Unless we have paths which you should not even be able to know the existence of before being authorized.

This is tricky to fix generally. I actually think there might be both kinds of paths: collection names are not secret and don't need to be. But individual object names might be more sensitive? e.g. I shouldn't be able to use DELETEing namespaces/yours/pods/your-secret-pod returning 401 vs 404 as a way to detect if that pod existed (e.g., searching for vulns in your cluster to do a privilege escalation attack).

I think the fastest route to fix this is to make the change CJ suggested.

**Comment by cjcullen** [comment]
I agree. We should validate the things that could never exist, but should pass through to the authorizer things that potentially could be real in a cluster.

E.g. if I try to `DELETE /api/v1/bindings/super-secret` or `GET /api/v1/proxy/namespaces` (another one I saw), we can bail before authorization w/ a 405.

But if I try to `GET /api/secret-group/secretstuff/foo` that should be passed through.

**Comment by goltermann** [comment]
@cjcullen is this needed for 1.4?  or can be bumped to v1.5?

**Comment by derekwaynecarr** [comment]
The merge queue is no longer blocked on this, so I am fine to defer, but its really GKE specific.

**Comment by goltermann** [comment]
@cjcullen agreed offline, moving to v1.5

**Comment by cjcullen** [comment]
Old title is no longer accurate (because of the workaround we added specifically for bindings). I'd like this issue to track kube-apiserver being smarter about the authorization questions that it asks.

**Comment by lavalamp** [comment]
@cjcullen what does "being smarter" mean? Can you make a list of desired changes?

**Comment by cjcullen** [comment]
The apiserver should not attempt to authorize a path that could never exist. It should just return a 404, or a 405 (if the resource is real, but the method isn't). It shouldn't be the authorization system's responsibility to determine whether a path is valid.

E.g., if a user tries to "proxy" a "persistentVolume" the apiserver should respond w/ a 405 without first asking the authorization subsystem whether that user is allowed to proxy persistentVolumes.

This bites us in GKE, because GCP IAM permissions are specific to each actual API method, so there is no persistentVolumes.proxy or persistentVolumes.* permission. The only two responses the authorizer can give at this point are "error" or "not authorized" which translate into 500 and 403 respectively.

This tripped us up in #31636 because the namespace deletion code was trying to "delete bindings" and was getting back either a 403 or a 500. A 403 suggests that there may still be some bindings to delete, but we just weren't allowed to delete them, so we better fail the namespace delete. A 500 suggests that something went wrong, and maybe we should retry our delete a little bit later, but we shouldn't skip the important "delete bindings" step.


I would like to see the apiserver return a 404 for a request on a resource type that doesn't exist, and a 405 for a verb that doesn't exist on a given resource, without querying authorization.

**Comment by lavalamp** [comment]
OK, that was clear, thank you. Is this blocking anything?

**Comment by cjcullen** [comment]
It is not blocking anything critical. It makes our monitoring noisy, and we have some workarounds in place that would be nice to remove.

**Comment by lavalamp** [comment]
OK, I don't think my team has bandwidth for this at the moment.

**Comment by dims** [comment]
This needs to be triaged as a release-blocker or not for 1.5 @cjcullen @lavalamp

**Comment by cjcullen** [comment]
This does not need to block 1.5.

**Comment by dims** [comment]
Ack @cjcullen switching milestone

**Comment by cjcullen** [comment]
My thinking on this has evolved:
I now think it is reasonable to hit the authorizer before we determine if the path is valid.

From a security perspective, we lower the risk that we leak information to unauthorized callers (e.g. if I get a 403 trying to list `SecretObjects` but a 404 trying to list `Widgets`, I just learned something about this cluster I shouldn't have been able to).

From an authorizer's perspective, you should just return `allowed: false` for any resources you don't know about. Well-written clients should expect that they may get a 403 from a non-existent resource if they don't explicitly have permissions on that resource.

@lavalamp @liggitt If I don't hear any objections, I'm going to close this issue.
