### ISSUE TITLE
Port forwarding tests won't work with rkt-kvm (propably with all hypervisor based runtimes)

### ISSUE THREAD

**Issue by pskrzyns** [kubernetes/kubernetes#32128]
Inside portforwardtester container in portforwardtester.go line 52

``` go
       listener, err := net.Listen("tcp", fmt.Sprintf("localhost:%s", bindPort))
```

It causes app to only listen on the local interface, its not the problem with namespace based runtimes cause we can use nsenter.
With hypervisor based runtimes we need app to be available on external address, so line mentioned above should look like:

``` go
       listener, err := net.Listen("tcp", fmt.Sprintf("0.0.0.0:%s", bindPort))
```

@ncdc PTAL cause i don't know who is owner of this container
@feiskyer could you check if this is a problem for hyper too ?

**Comment by ncdc** [comment]
@pskrzyns you can submit a PR to adjust the portforwardtester code, and then someone from Google will need to push the updated image, and then you can update the e2e tests to point at the updated image.

**Comment by euank** [comment]
Based on the discussion in #29579, I think the CRI implementation of this would actually solve this problem and allow listening on localhost.

Basically, my understanding is a "shim" process would be created inside the "sandbox" (inside the vm) that would then be able to talk to localhost, what have you, and redirect it to a port on eth0. That process would take the place of socat, and nsenter would be replaced with creating a new container via the usual "create / start" means.

So long as my understanding is correct, that means we could actually just add an additional argument to port-forward, turn it into two tests ("should be able to port-forward an application listening on 0.0.0.0; should be able to port-forward an application listening on localhost"), and then skip the latter test for the rkt runtime, or in your testing environment with specific flags.

So long as the fact that you can port-forward to localhost is intentional (pretty sure it is), I think it makes sense to add a new test rather than lose a slight bit of coverage on the existing one.

**Comment by pskrzyns** [comment]
@euank for me its a bug in application running inside container, whats the point of running application listening only on localhost, where you can't talk to it from outside of container ?
My understanding is that if i have pod IP i should be able to talk with application running in it when I'm in environment where this IP is routable.

**Comment by ncdc** [comment]
I wouldn't say it's necessarily a bug in the app. If you have something that truly should be protected and not visible outside the container, then port forwarding to localhost is the perfect mechanism for connecting to it.

**Comment by feiskyer** [comment]
> @feiskyer could you check if this is a problem for hyper too ?

Agree with @euank, we could solve this problem for hypervisor-runtimes  by #29579. It just needs time to get an agreement of how to achieve this.

> @euank for me its a bug in application running inside container, whats the point of running application listening only on localhost, where you can't talk to it from outside of container ?

Containers belonging to a pod may interact with each other by local networking.

**Comment by pskrzyns** [comment]
Ok, so as @euank suggested we should rename existing tests and add additional tests cases

TODO:
- [ ] add to portforwardertester.go ```os.Getenv("BIND_ADDRESS")``` if not set, it should be localhost for backward compability with existing tests
- [ ] Rename existing tests to "With a server listening on localhost that expects a client request It ..."
- [ ] For existing tests pass explicity BIND_ADDRESS='localhost'
- [ ] Add new test cases "With a server listening on 0.0.0.0 that expects a client request It ..."

Will it be ok ? @ncdc @kubernetes/sig-testing

**Comment by ncdc** [comment]
No objections here

**Comment by pskrzyns** [comment]
@ncdc there is name duplication in those tests, ```"should support a client that connects, sends no data, and disconnects [Conformance]"``` is used twice. Do we really need 2 tests cases for this (cause it looks  more like portforwarder image testing, than testing k8s functionality), if so do you have any idea how to rename one of them ?

**Comment by ncdc** [comment]
@pskrzyns yes we need both test cases. The first is for `With a server that expects a client request`, and the second is for `With a server that expects no client request`. These are two different valid scenarios that ensure that the port forwarding connection and streams are terminated properly in both cases. It is not just portforwarder image testing.

**Comment by pskrzyns** [comment]
@ncdc thx, missed ```With a server that expects no client request``` part ;)
