### ISSUE TITLE
Kubelet is infinitely asking apiserver for terminated pod

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#32191]
In large GCE test clusters (2000-nodes) we are observing that ~30% of all requests to apiserver are: "GET" requests about image-pullers that are returning 404.
This is generating super large load that basically shouldn't be there, however, this seems like a bug anyway.

Details:
- we are starting image-pullers from manifest files on all nodes
- at some point they are finishing
- if there are enough of them, some of them will be garbage collected by "pod-garbage-collector"
- kubelet receives DELETE/REMOVE event about this pod, e.g.
```
I0907 09:30:41.545069    3657 kubelet.go:2312] SyncLoop (DELETE, "api"): "e2e-image-puller-e2e-test-wojtekt-minion-group-ekar_kube-system(328a7913-74dd-11e6-8d6e-42010af00002)"
I0907 09:30:41.579395    3657 config.go:281] Setting pods for source api
I0907 09:30:41.579886    3657 kubelet.go:2306] SyncLoop (REMOVE, "api"): "e2e-image-puller-e2e-test-wojtekt-minion-group-ekar_kube-system(328a7913-74dd-11e6-8d6e-42010af00002)"
```
- once the pod is removed, kubelet starts sending "GET" requests for this pod every 10s and getting 404 errors
- this happens infinitely 

This clearly looks like a bug - Kubelet should simply forget about this pod and stop sending those requests.
[Note that kubelets whose image-pullers weren't removed by GC, are not sending those requests.]

How to reproduce:
- set "TERMINATED_POD_GC_THRESHOLD=1"
- change NODE_OS_DISTRIBUTION to debian (image-puller doesn't work on GCI, but that's a separate issue)
- start test cluster (from cluster/gce/config-test.sh)
- wait until image-pullers are finished (and all but 1 are removed by pod-garbage-collector)
- log into some node whole image-puller was removed - this kubelet is generating GET request every 10s and producing such log:
```
I0907 09:56:21.589336    3657 status_manager.go:405] Pod "e2e-image-puller-e2e-test-wojtekt-minion-group-ekar" (188ff65a5a5e521be0b4686b5923a96e) does not exist on the server
```

@dchen1107 @yujuhong @kubernetes/goog-node @gmarek

**Comment by Random-Liu** [comment]
I guess this is similar with #29845. What happened is that:
1. e2e-image-puller run to completion. (PodStatus = Success)
2. pod-garbage-collector removed the corresponding mirror pod of e2e-image-puller.
3. Kubelet receive the pod deletion and remove mirror pod from pod manager. https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet.go#L2473
4. kubelet didn't `SyncPod` for e2e-image-puller because it was terminated, thus didn't recreate the mirror pod. https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet.go#L2386
5. Status manager run [`syncBatch`](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/status/status_manager.go#L356) every 10 seconds, and will run [`syncPod`](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/status/status_manager.go#L396) for e2e-image-puller every time. Because in [this line](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/status/status_manager.go#L373-L377), it should be using mirror pod uid, but was using static pod uid because the mirror pod is removed from pod manager.

**Comment by Random-Liu** [comment]
I think status manager makes the assumption that:
* If there is the pod in pod manager
* => status manager should keep the expected status
* => apiserver should have a corresponding pod object
* => status manager should keep pod object status matching the expected status.

Normally, this is always true even for mirror pod (because kubelet will always make sure there is a corresponding mirror pod object). However, in this special case, because kubelet didn't recreate the mirror pod because the pod was terminated, which broke the assumption of status manager.

Possible fixes:
* Option 1: Make sure kubelet always recreates the mirror pod. This could have been addressed by https://github.com/kubernetes/kubernetes/pull/18638, but I really didn't have time to finish it. :P
* Option 2: Avoid mirror pod being deleted by anyone else. This has been discussed in https://github.com/kubernetes/kubernetes/issues/16627.

Anyhow, I'll try to find a quick fix for Option 1.

**Comment by wojtek-t** [comment]
@Random-Liu - thanks for taking a look into it - what you wrote definitely makes sense (at least first 3 dots are exactly what happened).

I have a question regarding "option 1". If you recreate the mirror pod, this would mean that again we have a pod for already finished pod. Wouldn't pod-garbage-collector try to remove it again?

And the general question - do we want to keep a mirror pod for terminated pods from manifests forever? I agree that for 1.4 we don't want to change it, but is it also a long term plan? This doesn't seem to be a perfect option for me.

**Comment by Random-Liu** [comment]
> If you recreate the mirror pod, this would mean that again we have a pod for already finished pod. Wouldn't pod-garbage-collector try to remove it again?

@wojtek-t Yeah, that will happen again.
On a second thought, we can also patch status manager to make it behave properly for this special case. I'll think about it.
