### ISSUE TITLE
Regression in OOM score configuration starting from v1.3+

### ISSUE THREAD

**Issue by vishh** [kubernetes/kubernetes#32238]
Kubelet and docker daemon were expected to run with an `oom-score-adj` of `-999` as mentioned [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/qos/policy.go#L25) and [here](https://github.com/kubernetes/kubernetes/blob/master/docs/design/resource-qos.md#oom-score-configuration-at-the-nodes).

This behavior has been broken since v1.3+. I consider this a serious regression because system OOMs will result in kubelet and/or docker daemon getting evicted instead of pod. QoS will essentially be broken at the node level. 

I'm working on a patch to fix this in v1.4 for now. I will then attempt to cherry-pick the patch into v1.3 release branch. 

I will also be adding a test for these settings.

cc @kubernetes/sig-node

**Comment by dchen1107** [comment]
Prior 1.0 release, Kubernetes provided some oom protection to important daemons: docker and kubelet etc. @vishh reported this regression issue when he works on GCI for 1.4. We traced back to previous version to figure out when the regression was introduced, and found it was broken since 1.3. 

Here is the result on my old 1.2 nodes:

```
dawnchen@kubernetes-minion-5ldv:~$ kubelet --version
Kubernetes v1.2.0-alpha.4.1571+37b5726716231c-dirty
dawnchen@kubernetes-minion-5ldv:~$ cat /proc/$(pidof docker)/oom_score_adj
-900
dawnchen@kubernetes-minion-5ldv:~$ cat /proc/$(pidof kubelet)/oom_score_adj
-999
```
But on another node running HEAD:
```
dawnchen@e2e-test-dawnchen-minion-group-ll9t:~$ kubelet --version
Kubernetes v1.4.0-alpha.1.769+7e108814dc19d6-dirty
dawnchen@e2e-test-dawnchen-minion-group-ll9t:~$ cat /proc/$(pidof docker)/oom_score_adj
0
dawnchen@e2e-test-dawnchen-minion-group-ll9t:~$ cat /proc/$(pidof kubelet)/oom_score_adj
0
```

@vishh also confirmed that this is broken on his 1.3 nodes. We need to fix this for 1.4 for sure, but not sure if we should patch 1.3.

**Comment by dchen1107** [comment]
cc/ @fabioy since you are the release czar for 1.3. Should we patch 1.3 for this?

**Comment by dchen1107** [comment]
cc/ @derekwaynecarr I am not sure if this is also broken on your nodes?

**Comment by vishh** [comment]
My PR was failing builds on windows and darwin. I have no clue why node e2e is being cross compiled. It is linux only. Re-opening this issue.

**Comment by Random-Liu** [comment]
I'll send a PR to make node e2e only built on arm64, arm and amd64.
