### ISSUE TITLE
Container IPv6 address is marked as duplicate (dadfailed)

### ISSUE THREAD

**Issue by yehiyam** [kubernetes/kubernetes#32291]
BUG REPORT

**Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.6", GitCommit:"ae4550cc9c89a593bcda6678df201db1b208133b", GitTreeState:"clean", BuildDate:"2016-08-26T18:13:23Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.6", GitCommit:"ae4550cc9c89a593bcda6678df201db1b208133b", GitTreeState:"clean", BuildDate:"2016-08-26T18:06:06Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**:
  bare metal ubuntu 
- **OS** (e.g. from /etc/os-release):
  14.04.5 LTS
- **Kernel** (e.g. `uname -a`):
  Linux yehiyam-adsl 3.19.0-68-generic #76~14.04.1-Ubuntu SMP Fri Aug 12 11:46:25 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
- **Install tools**:
- **Others**:

**What happened**:
In kubernetes 1.3.6 every container that is created has an ipv6 address that is marked as duplicate address. 
i.e. 
`
10: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 
   inet6 fe80::42:acff:fe10:2e02/64 scope link tentative dadfailed 
      valid_lft forever preferred_lft forever
`
this prevents one of our services (kurento-media-server) from working correctly.
This never happened with an older version of k8s (1.1.7)
**What you expected to happen**:
The IPv6 address should not be marked as duplicate

**How to reproduce it** (as minimally and precisely as possible):
Create a container (e.g. busybox, nginx)
execute the **ip** command in the container
`
kubectl exec pod_name ip add show
`

**Anything else do we need to know**:

**Comment by leblancd** [comment]
This problem is caused by a race condition, which is in turn caused by kubelet enabling "hairpin mode" on the veth interface on the host bridge for all pods. The problem with hairpin mode is that it reflects ALL packets back to the pod, including IPv6 neighbor solicitations (which are used for IPv6 DAD). When the pod sees an echo of a neighbor solicitation that it had just sent out, it treats the packet as coming from someone else, and marks the address as a duplicate. After several such failures, IPv6 on the container is dead in the water. This failure doesn't happen every time: Sometimes, DAD on the container can complete before kubelet turns on hairpin mode on the bridge's veth.

To determine if this indeed the failure mode on your setup, create some pods, and then on the minions where these pods are instantiated, check if the hairpin mode on the bridge's veths are set to "1", e.g.:
    cd /sys/devices/virtual/net/cbr0/brif
    for i in `ls`; do echo -n "$i: "; cat $i/hairpin_mode; done

The enabling of hairpin mode for bridge veth interfaces was added so that a container can access a service that is hosted in its own pod when the cluster is using bridges in the container network. I believe that hairpin mode for bridges was first introduced with PR #13628.

One workaround for this issue is to disable hairpin mode by modifying the kubelet config and restarting the kubelet service on each minion. (Of course, this would mean that the benefit introduced with PR #13628 would be eliminated, i.e. containers may not be able to reach services in their own pods.) To do this:
- On each minion, edit the kubeadm config file:
        sudo vi /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
   and add the following argument to the list of args for KUBELET_NETWORK_ARGS:
        --hairpin-mode=none
- Restart kubelet (on each minion):
        sudo systemctl daemon-reload
        sudo systemctl restart kubelet
- Check that kubelet is running with '--hairpin-mode=none':
        ps -ef | grep kubelet | grep hairpin
- Create some pods, and confirm that the hairpin mode for the veth interfaces on the host for each pod is set to '0':
        cd /sys/devices/virtual/net/cbr0/brif
        for i in `ls`; do echo -n "$i: "; cat $i/hairpin_mode; done

In order to fix this issue, while still allowing hairpin mode so that a container can access services hosted in its own pod, we'll probably have to figure out a way to configure IP tables so that when any IPv6 neighbor solicitation is received on a given bridge veth interface, any reflected (hairpinned) copies of that packet are dropped at that bridge veth interface before being transmitted back (if that's possible). Otherwise, IPv6 DAD may need to be disabled, but this would be a very undesirable solution.
