### ISSUE TITLE
How to limit resources used by multiple namespaces?

### ISSUE THREAD

**Issue by blindpirate** [kubernetes/kubernetes#32488]
Hello guys,
I'm using deis to manage k8s cluster, which will create a namespace for each application, even though they are created by a single user. I want to limit resouces used by user, but k8s's limitation is namespace-scoped. Is there any possibility that I can limit sum of resources used by multiple namespaces? 

Can I implement my hook or interceptor to manage resource request event or something?

Thank you very much.

**Comment by castrojo** [comment]
Please re-post your question to [Stack Overflow](http://stackoverflow.com/questions/tagged/kubernetes).

Thanks for taking the time to report an issue to us. In the past this tracker has housed both bug reports and user support requests, we are now only using this tracker for software defects and feature tracking.   

We are trying to consolidate the channels to which questions for help/support
are posted so that we can improve our efficiency in responding to requests,
and to make it easier for you to find answers to frequently asked questions and
how to address common use cases.

The Kubernetes team scans Stack Overflow on a regular basis, and will try to
ensure your questions don't go unanswered.

If you're looking for more long-form discussion on best practices, we encourage you to check out the [Kubernetes user list](https://groups.google.com/forum/#!forum/kubernetes-users). 

You can also find more information here:

  * [User Documentation](http://kubernetes.io/docs/)
  * [Troubleshooting Guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/)

Again, thanks for using Kubernetes. If you feel this issue has been closed in error then please reopen it and we can have another look. 

The Kubernetes Team
