### ISSUE TITLE
Kubectl client Simple pod should support exec through an HTTP proxy

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/kubernetes#32701]
https://k8s-testgrid.appspot.com/release-1.4-blocking#gke-1.2-1.4-upgrade-cluster

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-e2e-gke-1.2-1.4-upgrade-cluster/6162

**Comment by maisem** [comment]
#32688 should fix this.

**Comment by maisem** [comment]
Well - it will skip the test as the test is overly complicated and the test fix is large enough that it's infeasible to cherry-pick back to 1.2.

**Comment by maisem** [comment]
Please reopen if you still see a failure in test runs that started after 14:02 PST.

**Comment by ixdy** [comment]
ISTR this test was always a little problematic. 

https://github.com/kubernetes/kubernetes/blob/release-1.2/test/e2e/kubectl.go#L251-L255

We should be finding a built version of `kubectl`, but either the `linux/386` requirement or the skew environment is messing things up. (I'm not sure if we want to investigate further, or just skip the test as we've done.) We removed this mess entirely in #25776 for 1.3+, which is why this hasn't been as much of an issue.

The fallback to local build has never worked on Jenkins - we intentionally don't have the source available to e2e runs.

**Comment by pwittrock** [comment]
FYI @krousey Manually executed this test and it worked.
