### ISSUE TITLE
GKE: [k8s.io] Pods should invoke init containers on a RestartAlways pod

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/kubernetes#32711]
[k8s.io] Pods should invoke init containers on a RestartAlways pod

https://k8s-testgrid.appspot.com/release-1.4-blocking#gke-1.3-1.4-upgrade-cluster

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-e2e-gke-1.3-1.4-upgrade-cluster/559

**Comment by dchen1107** [comment]
I believe all init containers related failures have the same root cause. The below are the facts I know and the conclusion / hypothesis I drawn so far (haven't double check master component's logs to confirm this yet):

* https://k8s-testgrid.appspot.com/release-1.4-blocking#gke-1.3-1.4-upgrade-cluster running 1.3 tests against the upgraded cluster, and all init container related tests failed
* https://k8s-testgrid.appspot.com/release-1.4-blocking#gke-1.3-1.4-upgrade-cluster-new running 1.4 tests against the upgraded cluster, and all init container related tests succeeded.
* init container feature is promoted from alpha feature to beta feature from 1.3 release to 1.4 release. 
* In GKE 1.3, there is no feature gate, init container tests with alpha annotation are allowed to run
* 1.4 release, we introduced the feature gate which is defined at: https://github.com/kubernetes/kubernetes/blob/master/pkg/util/config/feature_gate.go#40, but it missed feature key for initContainer. In this case, all alpha features except with the key defined there will be rejected.

**Comment by dchen1107** [comment]
I can send a fix shortly if no one is doing it.

**Comment by bprashanth** [comment]
do the feature gates kick out annotation features as well? how do we even know what annotations are being used for alpha features? or is init containers just a victim because we convert an annotation to a field on the pod, and other alpha annotations (eg dynamic volume provisioning) will continue to work?

**Comment by pwittrock** [comment]
@dchen1107 What needs to be done to cross this off my list of things I am hunting down?  Does the referenced PR need to be cherrypicked?

**Comment by davidopp** [comment]
failing in
https://k8s-testgrid.appspot.com/google-1.3-1.4-upgrade#gke-gci-1.3-gci-1.4-upgrade-cluster
https://k8s-testgrid.appspot.com/google-1.3-1.4-upgrade#gke-gci-1.3-cvm-1.4-upgrade-cluster
https://k8s-testgrid.appspot.com/google-1.3-1.4-upgrade#gke-cvm-1.3-gci-1.4-upgrade-cluster
https://k8s-testgrid.appspot.com/google-1.3-1.4-upgrade#gke-cvm-1.3-cvm-1.4-upgrade-cluster
https://k8s-testgrid.appspot.com/google-1.3-1.4-upgrade#gce-cvm-1.3-cvm-1.4-upgrade-cluster

**Comment by dchen1107** [comment]
A quick updates:

The issue is in 1.3 release branch's test infrastructure. All init containers in tests are running as expected on nodes, no issue in kubectl, master and kubelet at all. I even manually upgrade 1.3 cluster to 1.4 cluster and run the related tests this morning. Everything is fine except at the end, the test checks pod's status, and pod is removed.
