### ISSUE TITLE
Networking dependencies

### ISSUE THREAD

**Issue by vishh** [kubernetes/kubernetes#32735]
Networking in k8s seems to have quite a few base image dependencies be it kernel configuration or user space tools. To ensure cross distro/base image compatibility for k8s, 
1. These dependencies needs to be documented 
2. A node conformance tests needs to be added that ensures that these dependencies are satisfied
3. Functional tests _must_ exist that exercise these dependencies

We should complete at-least `1` sooni(ish).

cc @kubernetes/sig-network @freehan @thockin @luxas

**Comment by thockin** [comment]
@luxas has started this list but that doesn't include some of the kernel
deps and tools that other vendor plugins want.  @freehan, can you throw
this on your TODO pile for medium-term?

**Comment by luxas** [comment]
Feel free to comment on my issue with more details about the kernel modules and so forth...
Who's gonna document this and where?

**Comment by dcbw** [comment]
From a quick review of pkg/kubelet's use of Command(), we have at least:

- brctl (could be replaced by /sbin/ip)
- /sbin/ip (a whole lot of places) - some uses could be replaced by Go libraries for netns manipulation (eg, CNI's 'netns' module) and many could be replaced by vishvananda/netlink
- systemctl (--configure-cbr0) - for restarting docker after telling docker to use cbr0
- service (same reason, restarting docker if systemd isn't installed)
- nsenter (a whole lot of places) - could be replaced with 'ip netns exec'
- modprobe (kubenet and noop) - used for br-netfilter to ensure we can twiddle bridge-nf-call-iptables, which is only required for plugins that use a Linux bridge and use iptables, eg kubenet and internal --configure-cbr0
- ls (kubenet)- could be replaced by Go directory listing functions

If we're interested in reducing external dependencies, I think we can pretty easily get down to /sbin/ip and modprobe only, by

1. finally killing --configure-cbr0 in favor of kubenet
2. converting brctl and nsenter usage over to /sbin/ip.  'ip netns' does require a specific iproute2 version though, due to some previous issues with netns manipulation.  We could replace this with cni/netns but this has some pitfalls.

**Comment by thockin** [comment]
@freehan and @dcbw - can we make 1.5 goal to excise the old pre-kubenet
code, or is it too soon?

**Comment by luxas** [comment]
@dcbw Hah, that's exactly what I've been proposing in https://github.com/kubernetes/kubernetes/issues/26093 :)

I'm gonna revisit my PRs that reduces the deps as soon as v1.4 is out the door.

@thockin We marked it deprecated in v1.4, so if we're aggressive (which I think we should be in this case), `--configure-cbr0` could be removed _now_ when HEAD is targeting v1.5

We should delete the experimental-flannel-overlay right away at least

**Comment by luxas** [comment]
That was what I was thinking, the earlier we remove it, the higher is the chance that someone tries to use configure-cbr0 with v1.5-alpha and notices the removal early.
(Not everyone is reading the relnotes)

**Comment by dcbw** [comment]
My wish-list/plan is to (a) remove configure-cbr0 in favor of kubenet after making sure that kubenet does everything configure-cbr0 does, and then (b) get kubenet into a plain CNI plugin instead of its own plugin.

**Comment by luxas** [comment]
@bowei any status update on this?

**Comment by bowei** [comment]
No progress -- but this is a good starter bug for anyone in sig-network

/label help-wanted
