### ISSUE TITLE
Document role of cloudprovider healthchecks in L4 lb

### ISSUE THREAD

**Issue by aaskey** [kubernetes/kubernetes#32827]
A load balancer type of service/deployment is created on GKE using the command below:
```
kubectl run my-nginx --image=nginx --port=80
kubectl expose deployment my-nginx --port=80 --type=LoadBalancer
```
A load balancer was created automatically. This is nice. However, from Google Cloud Platform/Networking/Load balancing, it complains:
```
This load balancer has no health check, so traffic will be sent to all instances regardless of their status.
```
Should the load balancer to be created with health check by default? I don't see an option to enable load balancer health check in service manifest. Would such an option be necessary in case we don't want to enable health check all the time?

**Comment by bprashanth** [comment]
kubelet does container level health checks so traffic doesn't go to unhealthy pods. If no pods are healthy, you (should) get an connection reset (RST).

If you use the source ip preservation feature (https://github.com/kubernetes/features/issues/27, alpha in 1.4) the service controller will program health checks for you so a node without endpoints doesn't get traffic. 

We should probably surface this through docs.

**Comment by aaskey** [comment]
Retaining source ip info is very important for our applications. We are happy to see this source ip preservation feature. 

Does GCE L4 LB replace original source IP with its own IP address?

**Comment by renaudguerin** [comment]
I've created L4 LBs in GCP using a "type: Loadbalancer" service definition, which doesn't create health checks for the nodes at the LB level (or didn't as of 1.4)

Am I correct in thinking that Kubelet's container level health checks don't help at all when a node is completely down (e.g. during a cluster version upgrade), and the L4 LB keeps sending traffic to it because it has no health checks to know it's down, and the node upgrade process hasn't temporarily removed the down node manually from the LB's backends either ? 

This is obviously causing service disruptions and IIUC, the current solution to this is to use the source IP preservation feature, even when you don't care about the source IP, just because it has the side effect of creating proper health checks on L4 LBs ? 

Correct ?

**Comment by thockin** [comment]
I reopened https://github.com/kubernetes/kubernetes/issues/14661

What you're doing is a viable workaround, but it is a workaround.

@mdelio

**Comment by renaudguerin** [comment]
@thockin That's what I thought yes, but there isn't currently a better solution apart from that SIPP side effect, correct ?

**Comment by thockin** [comment]
Correct
