### ISSUE TITLE
CRI: unify stdout and stderr streams for exec/attach

### ISSUE THREAD

**Issue by lucab** [kubernetes/kubernetes#32869]
In the [current CRI specification](https://github.com/kubernetes/kubernetes/blob/e8fbcb166928f57f29aaab7f51e64f2079be1020/pkg/kubelet/api/v1alpha1/runtime/api.proto#L597-L602), app execution (and perhaps attaching too, as per #29579) is supposed to return two separate streams for out and err:

```
message ExecResponse {
    // Streaming stdout
    optional bytes stdout = 1;
    // Streaming stderr
    optional bytes stderr = 2;
}
```

While this fine for the specific Docker case where a daemon running under the same kernel keeps two separate file descriptors and drains them, it is not a workable design for more general cases. I first encountered this when implementing a generic attach method for rkt, but after a quick search I found out multiple other issues related to this. 

These are (some of) the issues with having separate streams:
- it doesn't work cross-VM, as one can't just pass fd around and needs to resort to multiplexing I/O across kernel boundaries instead (eg. via network). I guess this is also why [Hyper interface](https://github.com/kubernetes/frakti/blob/master/pkg/hyper/types/types.proto#L544-L546) only has a single stream, but I'm having the same problem with rkt-kvm.
- it doesn't work with tty, as writing to pty is multiplexed by the guest and the host doesn't know about streams. This is a known issue which also affects logging (https://github.com/docker/docker/issues/25542, https://github.com/kubernetes/kubernetes/issues/30159) and which is intrinsics in how a tty works.

I would suggest evolving the spec for CRI exec/attach in order to have just a single input and a single output stream, as it is a more general approach which works even remotely or across VMs.

/cc @kubernetes/sig-node for ownership
/cc @feiskyer for the streaming design
/cc @timstclair for the streaming implementation

**Comment by feiskyer** [comment]
@lucab CRI streaming APIs (attach/exec/port-forward) are addressed at https://github.com/kubernetes/kubernetes/issues/29579.

**Comment by lucab** [comment]
Indeed, I linked it at the top. However this a partly different issue, which doesn't touch the topic of **how** to perform (generic) streaming operations but it is instead focused on **which** stream semantic should be exposed by container runtimes.

**Comment by feiskyer** [comment]
@lucab Check https://github.com/kubernetes/kubernetes/issues/29579#issuecomment-238665038, Option (3) will be based on http2, which supports multiplexed multi-channel stream with non-blocking.

**Comment by smarterclayton** [comment]
I am -1 - many, many people rely on proper POSIX semantics for shell inputs.  Removing separation between stderr and stdout means a whole class of application stop working inside of Kubernetes.

**Comment by smarterclayton** [comment]
Also, we have semantics for TTY today - if those aren't captured in CRI that's a gap.

**Comment by smarterclayton** [comment]
So if you remove the separation, expectation would be that you always use a TTY single stream and that the CRI implementation would be expected to set up proper TTY?  Would that mean that for any client to receive multi-streams they would have to implement TTY on their end?  Or something else?

Of note too we don't have 2 streams - we also have the resize stream and the error stream.  I'm not sure whether those are covered in the CRI design but they need to be. @sttts if you can help identify what the action / challenges might be there (since you were the last person in exec).

**Comment by jonboulle** [comment]
This seems a bit dramatic - is there really a whole class of applications and many, many people using attach regularly? We went through this discussion to try gain some more example use cases in https://github.com/kubernetes/kubernetes/issues/23335 and the only concrete thing that popped out was the OpenShift build system.

**Comment by lucab** [comment]
Thanks for your input @smarterclayton, I'm answering inline here below.

> many people rely on proper POSIX semantics for shell inputs. Removing separation between stderr and stdout means a whole class of application stop working inside of Kubernetes.

This doesn't touch POSIX semantics for shell inputs. Also this doesn't remove stderr/stdout separation for *applications running in a pod*. This merely concerns how the pod runtime carries this information to the kubelet.

> So if you remove the separation, expectation would be that you always use a TTY single stream and that the CRI implementation would be expected to set up proper TTY? Would that mean that for any client to receive multi-streams they would have to implement TTY on their end? Or something else?

Yes, for applications that need to be exec'd/attached the CRI-runtime will setup a proper tty. Output streams will be muxed when reaching the tty and a single stream will be exposed to kubelet/k8s (similarly to a ssh/telnet interactive session). In a multi-streams scenario, I'm not sure how client will want to implement tty, nor how the local tty will interact with the streams (eg. for resizing), nor if there is a case for execing/attaching without a tty.

**Comment by smarterclayton** [comment]
I'm not sure what you're asking?  Whether "kubectl exec ... find" should put errors on stdout?  Common uses of exec include:

* streaming a backup out of a container via rsync or tar - requires two streams
* running find / cat operations in containers - two streams
* running bash - tty in most cases, although someone pointed out recently that ttys don't work in all containers
* external checks run inside the container for zabbix - two streams

We have a few folks using attach as interactive debugging shells which terminate when they exist.  I'm aware of a few sets of users doing streaming jobs like Openshift, but not as sophisticated.

Let me flip this around a bit - we're building a cluster level abstraction for Unix-like processes, and we'd like to enable the process models that have worked for 30 years to enable the broadest possible applicability.  VMs and Windows are interesting, but they are not the primary concern of the product in terms of watering down to a lowest common denominator.

We should absolutely work to ensure TTY and single stream use cases work - because we already do today (stderr is an optional flag).  The API design must support existing use cases - otherwise we can't move to CRI for docker.

We should work to have an API that supports our use cases and maintains our existing compatibility.  We have a well established deprecation and feature retirement approach and practically it carries over many more releases than CRI will take to land.

If we need to get folks more familiar with the exec code base to help with this effort I'm happy to try and move people around to help CRI succeed.  But it's best to design CRI around the features we have and move forward - otherwise CRI is going to take 2 releases to land.

**Comment by smarterclayton** [comment]
The kubelet needs to preserve the distinction between stderr and stdout if it's a proxy for exec (otherwise who is providing that abstraction?).  This discussion seems only to make sense in terms of a proxy... which is not what I thought we agreed to in the other thread?

If CRI isn't providing the abstraction that answers the exec stream, this is an easier problem.  Which is why I suggested we start by not trying to pass exec / attach through the kubelet.

**Comment by smarterclayton** [comment]
Maybe we should try to sort this out in a hangout - want to make sure I understand what is truly being proposed.

**Comment by mrunalp** [comment]
I think https://github.com/docker/docker/issues/25542 could be fixed by having a separate tty attached to stderr.

**Comment by yujuhong** [comment]
> Of note too we don't have 2 streams - we also have the resize stream and the error stream. I'm not sure whether those are covered in the CRI design but they need to be

That's (resizing) what started the whole discussion in #29579, so we haven't addressed that yet in the current implementation.

**Comment by sttts** [comment]
Next to stdout, stderr and resizing, don't forget the error channel sending back a command return code. Something around the lines of:

```
message ExecTermination {
    int64 rc = 1
}
```

**Comment by lucab** [comment]
After a direct chat with @smarterclayton, I see there are different usecases for keeping the streams separated and as such rkt will try to provide them separately to the kubelet.

I'm however still not completely sure about the relationship between streaming stdin/stdout/stderr and the TTY. I'm currently inclined to have different attach modes depending on whether the app is running with a TTY (in/out streams + control back-channel) or without (stdin/stdout/stderr streams), but I'd like to know if I'm missing some details here.

**Comment by TerraTech** [comment]
Just to make sure that I don't have a misconfiguration with my _rktnetes_ cluster, is this issue the reason why the following doesn't work?
```sh
$ kubectl run busybox --rm -it --image=busybox --command -- /bin/sh
Waiting for pod default/busybox-3689126863-9ow73 to be running, status is Pending, pod ready: false
Waiting for pod default/busybox-3689126863-9ow73 to be running, status is Pending, pod ready: false
If you don't see a command prompt, try pressing enter.
                                                      Error attaching, falling back to logs: Internal error occurred: error attaching to container: unimplemented

E1002 16:57:25.537154   20551 v2.go:105] EOF
deployment "busybox" deleted
```
Is there something I'm misunderstanding or doing incorrectly with ```kubectl run -it```?

_I'm posting this here so that others search for a reason why a documented feature isn't working correctly.  I'll delete my post if this issue isn't related._

Right now, I'm having to launch it by using a 'sleep', then later ```kubectl exec -it``` into it.
```sh
$ kubectl run busybox --image=busybox --restart=Never --command -- /bin/sleep 3000
pod "busybox" created
$ kubectl exec -it busybox /bin/sh
**gained CLI access, debug/test whatever is needed
$ kubectl delete pod/busybox
pod "busybox" deleted
```
Is there a better way than the above obtuse workaround?

**Comment by euank** [comment]
@TerraTech Under the hood, `kubectl run -it` uses attach, which we're aware doesn't work under rkt (see [here](http://kubernetes.io/docs/getting-started-guides/rkt/notes/#kubectl-attach), as well as the second issue you mention). That document could make it more clear that attach not working includes the `kubectl run -it` use of it, certainly.

Your workaround of running a sleep or pause or such is the best workaround I know of.

This issue's related to hashing out fixing this as part of the CRI refactor, so at least a bit related.

**Comment by TerraTech** [comment]
@euank thank you for the clarification, most helpful.
