### ISSUE TITLE
Fix federation ingress e2e tests

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/kubernetes#33135]
They are failing right now due to a panic which is being fixed by https://github.com/kubernetes/kubernetes/pull/33120.

They still fail after that fix.
I see the following in the controller manager logs:
Logs: https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/33120/kubernetes-pull-build-test-federation-e2e-gce/30/build-log.txt
```
ingress_controller.go:748] Failed to execute updates for e2e-tests-federated-ingress-jo8tc/federated-ingress: Operation cannot be fulfilled on ingresses.extensions "federated-ingress": StorageError: invalid object, Code: 4, Key: /registry/ingress/e2e-tests-federated-ingress-jo8tc/federated-ingress, ResourceVersion: 0, AdditionalErrorMsg: Precondition failed: UID in precondition: 0xc82529be60, UID in object meta: b465807f-7f78-11e6-b65f-42010af00002
```

Update fails because of UID mismatch

**Comment by nikhiljindal** [comment]
cc @kubernetes/sig-cluster-federation @quin

**Comment by quinton-hoole** [comment]
OK, the bug here is pretty obvious, as is the reason why it was not caught by unit tests.

For updates of cluster Ingresses, the UID of the federated ingress, rather than the cluster ingress is  being used.  This is not correct.  Our fake test framework is not as strict as the real Kubernetes API about checking UID's on updates, so it didn't pick this up.

https://github.com/kubernetes/kubernetes/blob/master/federation/pkg/federation-controller/ingress/ingress_controller.go#L631

I'll send a PR to fix shortly.

@matchstick @nikhiljindal FYI.
