### ISSUE TITLE
Add pod level selinux options, and pod level volume mount labels.

### ISSUE THREAD

**Issue by yifan-gu** [kubernetes/kubernetes#33139]
### Problems:

Today, the selinux options and volume mount labels are at the app level:

Selinux option is defined in `CreateContainerRequest.ContainerConfig.LinuxContainerConfig.SELinuxOption`

Mount label is defined in
`CreateContainerRequest.ContainerConfig.Mount.selinux_relabel`

However, currently for rkt, it's very hard to do app level selinux context and mount relabeling. But we **do** support pod level selinux context and mount relabeling, which are defined in v1 api's [PodSecurityContext](https://github.com/kubernetes/kubernetes/blob/master/pkg/api/v1/types.go#L1833-L1835)

On the other hand, during oob discussion in sig-node channel, @smarterclayton mentioned a scenario that uses per app selinux to isolate untrusted apps within the pod:

> claytonc [2:20 PM]  
> there are definitely advanced use cases for container labelling, but in practice most peolpe can live without them for now
> if you ever want to have privileged and unprivileged containers in a pod
> where the untrusted code is in one container and teh privileged code is in athore
> (another)
> then having only pod level selinux can actually be dangerous - you can make the pod unconfined (so for instance a build daemon can call the docker socket), but that means if you’re running Git in an init container and an exploit happens Git is now running with selinux unconfined
> basically at that point without container level selinux you’d have to have two pods, then ensure that the two pods get scheduled together on the same node
> user agent sidecars that have access to host resources are another example

Based on this use case, we might not drop the app level selinux options.
### Possible solutions:

So instead of having only app level selinux options. How about adding another selinux option in `PodSandboxConfig.LinuxPodSandboxConfig`, e.g.

``` protobuf
// LinuxPodSandboxConfig holds platform-specific configuraions for Linux
// host platforms and Linux-based containers.
message LinuxPodSandboxConfig {
    ...
    // Optional SELinux context to be applied.
    optional SELinuxOption selinux_options = 3;
}
```

Here are examples how this will work with `docker` and `rkt`
#### For docker:
- When receiving `RunPodSandboxRequest`:
  - Ignore the selinux option in the request, go ahead creating the pod infra container.
- When receiving CreateContainerRequest:
  - Apply the selinux options in the request to the container through docker API.
  - For each mount, relabeling the mount according to the mounting labels if necessary.
#### For rkt:
- When receiving RunPodSandboxRequest:
  - Apply the selinux option on the request to the sandbox. It will be done by setting the `SELinuxContext=` option of systemd unit that runs the sandbox process.
- When receiving CreateContainerRequest:
  - Ignore the selinux options in the request.
  - For each mount, relabeling the mount according to the mounting labels if necessary.
    However, **the mount label must match the pod level selinux options**.

I can see the drawback is we could end up with slightly different ux, e.g. 
- If a user provides rkt only app level selinux options, it might not work correctly, unless we can know before hand how to translate the app level selinux options to pod level selinux options before launching the sandbox.
- If a user provides docker only pod level selinux options, **it might work**. We could potentially write down the pod level selinux options in the pod's annotation, and later read from it when creating the containers.

@lucab Could you explain in more detail why we can't do per app selinux context/mount relabeling? 
AFAIU, our mounting process is different. Unlike docker, that mount volumes to individual containers, we are essentially mounting the volumes into the sandbox first before bind mounting them to the apps in the sandbox. And our apps are in the **same** mount namespace.

cc @kubernetes/sig-node @kubernetes/sig-rktnetes  @s-urbaniak @alban @iaguis @mrunalp

**Comment by yifan-gu** [comment]
cc @squeed

**Comment by lucab** [comment]
From my (little) understanding of SELinux, the current spec is quite hard to implement for rkt (and perhaps other generic runtimes) because of several reasons:
 * it is not specified in which context the pod as a whole (ie. supervising helpers) should be run. We can either run it unconfined or apply a dynamic sVirt context/label to it, without guarantees about app-interaction. Both of those have drawbacks in security and UX respectively.
 * when using VM isolation, we can't ask the host to move single apps (in the guest) to a different context. Also see above point regarding the context in which the VM will actually run.
 * it breaks contracts related to pod as a unit of execution. From @pmorie feedback, it also goes in the opposite direction of a wishlist long-term plan (only pod-level SELinux context for v2 api).

**Comment by pmorie** [comment]
I think it would add to this conversation if we defined what 'app' is.

> it breaks contracts related to pod as a unit of execution. From @pmorie feedback, it also goes in the opposite direction of a wishlist long-term plan (only pod-level SELinux context for v2 api).

I don't think this is an official wishlist.  @smarterclayton's use case about a single container in a pod running unconfined is definitely a valid one.

**Comment by smarterclayton** [comment]
Yeah I'll clarify:

1. We originally supported container only - so we have backwards
compatibility responsibilities
2. We then added pod level, which would be intended to support shared
volumes correctly
3. Since then, we have identified that we need certain containers to be
unconfined.

If we deprecate 1, we'll have to do it over multiple releases.

2 is not optional going forward.

3 running unconfined sidecar containers that have access to hostPath is
probably a requirement for any monitoring sidecar that needs to write to
the disk, while you may want the web container to run confined.  If someone
can make an argument that we don't need that, we can remove it.  But it
would have to be a strong argument, since pods are *supposed* to be able to
colocate different workloads harmoniously, and if we can't define some
level of restrictive security here we're not making pods a real solution
for that (we would need to schedule two pods on the same node to accomplish
the use case, which requires different changes).

**Comment by yifan-gu** [comment]
> I think it would add to this conversation if we defined what 'app' is.

@pmorie Here is what an `app` is in today's rkt:

```
stage1
   |_____ systemd
            |_____ app1.service
            |_____ app2.service

```

Where `stage1` can be `systemd-nspawn` or `kvm`, which encapsulate the `apps` and an init process.
The `stage1` corresponds to pod sandbox in CRI.

So we can see, the `apps` are all sharing the same namespaces today, but can be applied with individual cgroups.

**Comment by mjg59** [comment]
A couple of things here:

1) app-level contexts make no sense in a VM-based environment. If someone is running multiple apps in a single kvm-based pod, there's (a) no tooling inside to allow us to set up SELinux, and (b) no mapping between internal contexts and host ones. So what you probably want when you're using kvm is for the kvm instance to be in a unique confined context (so any hypervisor breakout vulnerabilities are still mitigated by the selinux confinement) and to ignore any app-level contexts

2) app-level contexts in a namespace-based environment leave the question of what context the parent should be in. If systemd-nspawn is itself confined, it needs to be confined in such a way that it can still launch children that are able to transition into their final per-app selinux contexts. That means writing new policy, and would *reduce* the extent to which (eg) nspawn is confined.

The two cases have fundamentally incompatible semantics. In (1) you want per-pod confinement that's as strict as possible. In (2), the pod-level confinement needs to be relaxed in order to allow the independent strict confinement of the apps below. How do we reconcile this without introducing confusion?

**Comment by pmorie** [comment]
@yifan-gu thanks, that jogged my memory -- too many overloaded terms :)

**Comment by jonboulle** [comment]
I'm pretty strongly in favour of deprecating individual app-level contexts for the reasons that mjg and Luca outlined.

> 3 running unconfined sidecar containers that have access to hostPath is
> probably a requirement for any monitoring sidecar that needs to write to
> the disk, while you may want the web container to run confined.  

Isn't this handled by just not exposing (mounting) that particular hostPath into the web container? Unless you're suggesting something like (for example) mounting `/var/` from the host into both containers in the pod, and then relying on security contexts within that to further isolate behaviour... which does not seem like a great pattern to encourage.

> pods are *supposed* to be able to
> colocate different workloads harmoniously, 

Pods are also supposed to be a co-operative unit right?

**Comment by jonboulle** [comment]
(somewhat related: #20899)

**Comment by smarterclayton** [comment]
> Isn't this handled by just not exposing (mounting) that particular
hostPath into the web container?

No, the container wouldn't have the right selinux context or app armor
settings to access the host.

Pods are cooperative and co-scheduling, but we have never said they must
co-operate.

**Comment by yifan-gu** [comment]
> hostPath into the web container?

@smarterclayton I think what @jonboulle was saying is that in the case when both web container and sidecar container have the same selinux, you only mount to the sidecar container with the hostPath it needs, so it doesn't affect the web container? Is that what you are saying, @jonboulle ? Correct me if wrong.

**Comment by jonboulle** [comment]
Yes, that's what I was saying; my confusion remains.

**Comment by smarterclayton** [comment]
I was saying that the selinux context matters to the sidecar with the host path - it needs to write files to the host in the host's selinux context.  The web containers selinux context, on the other hand, should be restrictive to minimize breakouts.  The web container and side car might connect over a shared filesystem or over local networking on a unix domain socket.

**Comment by jonboulle** [comment]
@smarterclayton OK, why does it need to be unconfined? Can't it run in a confined context with that particular access to that particular directory on the host? Also, do you have any response to mjg's points above?

**Comment by rhatdan** [comment]
I have just been working on SELinux support for OCID, and was pointed to this discussion. 
https://github.com/kubernetes-incubator/cri-o/pull/100

I think in general the SELinux labels should be the same for all containers within the POD. Too easily to get breakage. The problem I saw was that the SELinux label specified in CRI was at the Container Level but not available for the initial sandbox creation. IE I don't have the label at the time I am creating the Pause container.  

I can see a use for specifying a separate SELinux type for each container being potentially useful.   But changing other parts of the label like MCS level, makes little sense.

**Comment by yifan-gu** [comment]
> IE I don't have the label at the time I am creating the Pause container.

Exactly, without a pod level selinux context, the pause container has no selinux context to run with.
Besides, when all docker containers are sharing the IPC namespace, they are running with [the same selinux context](https://github.com/kubernetes/kubernetes/blob/master/docs/proposals/selinux-enhancements.md#sharing-ipc-namespaces). So the app level selinux context is only useful when they are running in host IPC namespace ??

**Comment by rhatdan** [comment]
Well theoretically you could have processes inside of the same pod with different SELinux labels. For example you could have container_apache_t which is only able to listen on port 80. and a monitoring container type container_t which is allowed all ports and to control container_apache_t.

But this would be by far the exception.

**Comment by feiskyer** [comment]
I'm in favor of support security context on both sandbox and container. we could make them aligning with [PodSecurityContext](https://github.com/kubernetes/kubernetes/blob/master/pkg/api/types.go#L1582) and [Container SecurityContext](https://github.com/kubernetes/kubernetes/blob/master/pkg/api/types.go#L3037).

I think changing the behavior of container security context is out of CRI scope. It may break some current use cases and should be discussed for a wide scope.

@yifan-gu @yujuhong @smarterclayton  What do you think?

**Comment by smarterclayton** [comment]
In general, any non backwards compatible API change is out of scope unless
we have pretty broad consensus at the top level and the feature isn't
accidental or a security hole.

Restricting it for new runtimes in alpha is less of a problem.  But when
those run turns graduate we'd have to make a decision one way or another.

I don't think we have consensus for change here yet, and we would need
multiple releases if we did intend to stop supporting it, so for now it's
better to implement both and move this discussion to a larger forum as a
candidate to drop functionality.

On Oct 14, 2016, at 2:44 AM, Pengfei Ni <notifications@github.com> wrote:

I'm in favor of support security context on both sandbox and container. we
could make them aligning with PodSecurityContext
<https://github.com/kubernetes/kubernetes/blob/master/pkg/api/types.go#L1582>
and Container SecurityContext
<https://github.com/kubernetes/kubernetes/blob/master/pkg/api/types.go#L3037>
.

I think changing the behavior of container security context is out of CRI
scope. It may break some current use cases and should be discussed for a
wide scope.

@yifan-gu <https://github.com/yifan-gu> @yujuhong
<https://github.com/yujuhong> @smarterclayton
<https://github.com/smarterclayton> What do you think?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/33139#issuecomment-253722272>,
or mute the thread
