### ISSUE TITLE
Kube-dns should not be setting CPU limits 

### ISSUE THREAD

**Issue by vishh** [kubernetes/kubernetes#33222]
CPU limits are enforced on most distros excepting Google's debian based containerVM. The current CPU limits for kube-dns are not based on empirical data ( quoting @bprashanth ). 
The kube-dns pod is already in the `Burstable` class. I propose removing CPU limits altogether until we profile kube-dns in more detail.
This issue will impact users.

**Comment by bprashanth** [comment]
It's based on some empirical data, just not very good data because we keep running into issues. I think removing the limits should be fine, but this isn't a fire right now, so it probably won't make it into 1.4.0 as a cherrypick unless @kubernetes/sig-network really wants to relax it.

**Comment by vishh** [comment]
This issue will not be detected by our existing tests. What defines a `fire`?

**Comment by bprashanth** [comment]
hmm, something that is causing problems for existing customers with todays deployment/os etc?

**Comment by bprashanth** [comment]
or will, if they get on the 1.4 release

**Comment by vishh** [comment]
There have been GKE customer issues in the past around kube dns being slow
on GCI based ContainerVM which has CPU limits enabled.

**Comment by bprashanth** [comment]
sure we haven't prioritized it till now for 1.4, i don't see a sudden reason to do so

**Comment by bprashanth** [comment]
when i say 1.4 i meant 1.4.0

**Comment by bprashanth** [comment]
also i think the slowness was more because of cpu requests being low (even on gce), per https://github.com/kubernetes/kubernetes/issues/33027. Though as described, it really can't *hurt* to alleviate the limits, especially if we were never honoring them. Do you have a bug for that I can look over to understand the risk/impact?

**Comment by vishh** [comment]
I can share the internal bug offline.

**Comment by bprashanth** [comment]
oh, so it's still honored on other platforms, then it's still a risk right?

**Comment by vishh** [comment]
Yes. CPU limits are honored on all other distros other than debian based
container VM.

**Comment by bprashanth** [comment]
Alright, lets assess the real risk/benefit here, there are currently 3 dns containers:     
   * kubedns: guaranteed cpu, burstable ram
   * healthz: guaranteed cpu/ram
   * dnsmasq; guaranteed cpu/ram

you're proposing that we lift cpu limits on all of them. The impact is:    

1. Debian based: suffer from stringent enforcement of cpu limits. On these platforms DNS lookups can simply fail because the limits are throttling the container.
2. Non debian: moves all containers out of guaranteed cpu.

I'm trying to quantify the tradeoff here. 
* Do all debian based platforms suffer? 
* By how much is the stringent enforcement (or, please describe this problem so I can understand it better)? 
* What happens to !Debian platforms that are running other cpu hogs on the same node, because now the DNS containers are no longer guaranteed? 

The case I'm really trying to understand is:    

1. If a user has a bunch of cpu hogs all in burstable, in the !Debian case, does this mean DNS will suffer? 
2. If kubedns goes wild on cpu because of a skydns bug, does that mean all !guaranteed pods on all platforms will suffer? 

I understand they'll all get at least what they requested in terms of cpu, but I'm asking about the impact to apps that might be running on allocated cpu that's say 2 x requested. All this analysis only because we're so close to the releases and we've had enough surprises in the past.

**Comment by bprashanth** [comment]
Spoke irl, the impact is to all *non* debian systems. They could potentially get throttled on cpu, only debian won't because it ignores cpu limits. 

Simply setting any container cpu or memory requests > limits puts the pod in burstable QoS, so kube-dns is already only burstable and the change doesn't degrade its QoS.

**Comment by thockin** [comment]
I think we DO set the CPU limit, so more modern distros will throttle CPU.
We should disable that.

**Comment by bprashanth** [comment]
the only reason we set it in the first place was for qos, but apparently there was a misunderstanding because the pod is already burstable on memory. the only reason it isn't infinite is because I thought qos degraded by the *amount* limits are > requests, but apparently that is also not true. 

There really is very little motivation to set cpu limits on anything important, apparently.

**Comment by thockin** [comment]
The primary reason to set CPU limits is determinism, e.g. benchmarks.  The
Borg default is not to limit CPU.  Request is guaranteed.

**Comment by Pendoragon** [comment]
Don't know if this is the right place to ask but I was going through the QoS docs and had this (wrong?) impression that anything important should fall into the `Guaranteed` bucket. But then as @bprashanth said, if something is really important, there is little motivation to set cpu limit since the requested cpu is always guaranteed. Now I'm wondering what kind of applications should be classified as `Guaranteed` ? And why it is called `Guaranteed`?

**Comment by vishh** [comment]
If an app is sensitive to resource availability & performance, and doesn't
want to ever be starved of any compute resources, it should be in the
`Guaranteed` class.
If an app falls out of the `Guaranteed` class, then it can get evicted at
any time once it exceeds its requested amount of compute resources.

**Comment by thockin** [comment]
Vish,

It's important in these discussions to distinguish the behavior wrt
compressible and incompressible resources.  If you go over your memory
request, your OOM-probability and eviction-probability goes up in the face
of contention.  If you go over your CPU request and there is contention,
you should just get throttled back to request.  Right?

**Comment by vishh** [comment]
@thockin Yeah. I assume you are describing the behavior of `Burstable` pods. As for `Guaranteed`, they are (mostly) shielded from evictions and have to worry about CPU throttling only if the `limit` is lower than what is required for the containers.

**Comment by vishh** [comment]
As for this specific issue, we'd like to keep kubedns in the `Guaranteed` class ideally. To do that though, we either need vertical scaling of compute resources or detailed profiling of resource requirements for kubedns across different cluster sizes and performance requirements (QPS)

**Comment by thockin** [comment]
Vish,  I think there's a disconnect, or maybe I am misunderstanding.

Guaranteed class means that you will never use more than your CPU limit.
While this SOUNDS good, it's actually pretty useless outside of benchmarks.

We absolutely want memory request == limit.  I do not think we want the
same for CPU.

**Comment by vishh** [comment]
> Guaranteed class means that you will never use more than your CPU limit.

I assume you say this because we choose to hard limit CPU for guaranteed now. 

1. It is an internal implementation detail and we can choose to change it in the future. 
1. Ideally, if hard capping doesn't negatively impact apps, for example by having a short quota period, CPU limits wouldn't matter to most end users.

> While this SOUNDS good, it's actually pretty useless outside of benchmarks.

CPU isolation is one facet of QoS classes. `Guaranteed` class happens to include CPU quota as of now. I don't see how that would make `Guaranteed` a candidate just for benchmarks. Can you clarify further?

**Comment by thockin** [comment]
For a benchmark or load-test, you want to know how your system performs at
the limits.  Request is guaranteed, so "the limit" is when you can't go
above your request.

In real operation, there's almost always free cycles to use.  Why would you
NOT use them?  CPU is a compressible resource.  There's very little cost to
using more CPU than you requested, as long as that CPU is available.  This
is different from memory or disk, which have a real cost to reclaim.

This is extra painful with highly-concurrent languages and low-request
jobs.  If I request 1 core of a 32 core machine, I can theoretically
exhaust my quota in 34 milliseconds.  Even with 250 ms quota, I am sitting
idle for 216 ms.  That is going to look SUPER CRAPPY on a service that
really needs to be < 2 ms latency, and happens to be at the center of
everything (e.g. DNS).

So remind me why we are advising users to hurt themselves?  Or am I
misunderstanding?

**Comment by vishh** [comment]
> So remind me why we are advising users to hurt themselves?  Or am I
misunderstanding?

IIUC, you are primarily focussed on CPU quota, and not on QoS classes in general.

The real question I guess is why is CPU quota imposed on `Guaranteed` pods?
This was suggested by @erictune I think because `Guaranteed` pods should not consume more than what they asked for.
If we want to optimize for latency instead of burst capacity, then we can set the quota period to `20ms` for example. 
`Guaranteed` pods are expected to be fine tuned for consistent performance across homogenous nodes. Allowing Bursting of CPU can result in inconsistent performance across nodes.

That said, admins can choose to allow `Guaranteed` pods to burst too with a simple flag flip. 
I'd like to wait for user feedback on QoS before moving further ahead.

**Comment by thockin** [comment]
Well, either way DNS should NOT be using quota.  It's killing our tail
latency.

**Comment by bprashanth** [comment]
It currently still uses requests, not limits. And if we're only guaranteeing requests, it's probably still deieing. when the wrong pods land on the node (it might've been worse on debian where we didn't enforce the other addon limits).

**Comment by vishh** [comment]
I suspect we can run kubedns in the `Guaranteed` class by running [pod
nanny](https://github.com/kubernetes/contrib/tree/master/addon-resizer)
alongside it. Pod nanny can resize the kubedns pod as and when required.
Given that it will be a guaranteed pod, it will most-likely never get
evicted.

**Comment by thockin** [comment]
I really do not think eviction should be tied to compressible-resource
overages, or at least that is the VERY LOWEST factor

**Comment by bprashanth** [comment]
Increasing requests for kube-dns has the awful downside of evicting user pods (the last time this happened we had an epic disaster: https://github.com/kubernetes/kubernetes/issues/23556). My first reaction coming from a "process management" world is: I just want cpulimits+nice.

**Comment by thockin** [comment]
We should dynamically increase request to what we think is a realistic
value - this is not a free ride.  But I don't think we need quota.

**Comment by bprashanth** [comment]
yeah but what's to prevent everyone else from doing the same? at which point someone gets kicked out. do we have a priority level setting that says never kick dns out?

**Comment by thockin** [comment]
DNS is marked as critical, but no, nobody should be kicked out for using
spare cycles.  We schedule on requests, and we don't overcommit.  If
everyone runs full tilt and eats as much CPU as they can, everyone gets
their request.  99.999% of the time this is not the case and there are
spare cycles.

Ideally, tooling would automatically adjust DNS to have more CPU request
when it needs more on a consistent basis.  We don't have that tooling yet.

**Comment by bprashanth** [comment]
It is easy to write a feedback loop that scrapes heapster data (I think the nanny Vish mentioned does some form of this). My previous question was in this context. If everyone kept bumping up requests when they observed their pod hitting request, what happens? Do we try to reschedule dns, leave it running with too little cpu, or kick something else out and scale dns? I want to kick things out based on priority.

**Comment by thockin** [comment]
DNS is critical, so it will kill other things.  In theory.  I have not
tested this myself :)

**Comment by Pendoragon** [comment]
So in terms of incompressible resource, what is the point of setting limit? I ask this because pod eviction is WIP and in case of memory or disk contention, someone will get kicked out and the node will remain stable. Is it because we can prioritize pods and eviction can be done in order(BE ones first, then Bu...)? Or scheduling can probably be done based on limit in the future?

**Comment by thockin** [comment]
Setting limit allows you to opportunistically use more memory than you have
a guaranteed right to use.  This of it this way - if you have limit ==
request, and you get a sudden spike, you will OOM.  If you have limit >
request, you *might* OOM, but you might survive.  It's not so black and
white, though, because having a limit means the kernel tries to keep you
below the limit, so raising the limit means you're less likely to stay
below request (pressure is applied wrt limit, I am pretty sure).

There's a LOT of work we can do here, but a lot of it is very subtle, and
upstream kernels have indicated reluctance to adopt some of the more
nuanced semantics.

**Comment by ddysher** [comment]
+1 But everywhere eviction is mentioned, we see QoS.  And although QoS is said be orthogonal to request & limit, we uses request & limit to determine QoS exclusively.  Further, there doesn't seem to be a plan to decouple them?  I remembered reading some docs in k8s.io saying that we deliberately rejected using numbered priority.
> I really do not think eviction should be tied to compressible-resource overages, or at least that is the VERY LOWEST factor

One of the assumptions for CPU is that there is always free cycles; but we run cpu intensive apps on kubernetes (tensorflow).  Haven't tried yet, but curious about what happens if we run them with normal apps.

**Comment by thockin** [comment]
My main point is that for compressible resources there is almost NO IMPACT
on the system if I temporarily exceed my request.  If everyone is using
their request, I might not be able to get extra, and that might cause my
app pain, but that's on me to figure out.

**Comment by Pendoragon** [comment]
Does this mean that If an application is critical, I should place it in `Burstable` class in terms of memory? e.g. In stead of setting request & limit memory as 2G/2G, I can raise the memory limit to 4G if the application is critical so that it can survive some memory spikes. Or can I make the statement that critical applications should be classified as `Burstable` rather than `Guaranteed` because it can survive memory spikes while a guaranteed application will be killed once it tries to use more memory than its request.
> This of it this way - if you have limit ==request, and you get a sudden spike, you will OOM.  If you have limit > request, you *might* OOM, but you might survive.

**Comment by vishh** [comment]
If a pod exceeds its requests, it becomes a highly likely candidate for OOM
kills or evictions. Using more than `request` is opportunistic and can lead
to container deaths.

If a pod is critical and cannot tolerate disruptions, I'd recommend setting
request ( and limits) to all its containers to the amount of memory and cpu
the respective containers will require at expected peak usage. Maybe give
them 20% more just to be safe.

**Comment by thockin** [comment]
Vish and I are just going to disagree on CPU, but we agree on memory.

**Comment by Pendoragon** [comment]
So to put it another way, QoS class has little, if any, relevance to the importance of the application. What matters is how much guaranteed resource(request) it can safely use and how much resource it can opportunistically use(limit). Because it's not the QoS class that decides whether a pod should be evicted or killed, rather it's whether a pod exceeds its requested resource. From a user's PoV, I should only care about guaranteed and opportunistic resource I give to an application respectively and not be concerned about the QoS class it is in.

**Comment by ddysher** [comment]
This only hold true for burstable QoS ?
> Because it's not the QoS class that decides whether a pod should be evicted or killed, rather it's whether a pod exceeds its requested resource.

We have users running quite a few apps on kubernetes and they are terrible at guesting request/limit; so they usually request large number of resource for important app which result in VERY bad utilization.  We are investigating a couple of solutions, like initial resource, autopilot kind of tooling. This really bites us.

**Comment by vishh** [comment]
QoS classes are tied to `requests` and `limits` today and so QoS classes do
determine which pods get evicted under resource pressure on the nodes.

In the future, we hope to deliver pressure signals to k8s native apps that
can opportunistically use more resources and dial down their usage when
there is resource pressure (primarily for memory)

**Comment by Pendoragon** [comment]
@vishh Sorry, maybe I didn't convey it clearly. What I meant by "Because it's not the QoS class that decides whether a pod should be evicted or killed" is that request is guaranteed resource, being in `Guaranteed` class does not buy you extra level of guarantee on the requested resource than `Burstable`. e.g. For a `Guaranteed` pod A with 2G/2G (request/limit) and a `Burstable` pod B with 2G/4G are running on the same node with some other pods, A and B will have the same level of guarantee on their requested 2G memory. If their actual memory usage is below request, theoretically neither of them will be evicted in any circumstances (I am not counting the kube reserve and system reserve). Because the scheduling is based on request so if everyone on the node is below request, there will not be any memory contention. And if some other pods goes above their request, those who exceed their requests will be killed/evicted first. If I am correct on the scenario above, then will it be any different if we only have request and limit defined but no QoS class at all?

**Comment by chrissound** [comment]
What is the conclusion to this?

https://github.com/kubernetes/kubernetes/issues/33777

This question has 4000 views on stackoverflow (in 6 months, that 20 views per day): https://stackoverflow.com/questions/45573825/pod-will-not-start-due-to-no-nodes-are-available-that-match-all-of-the-followin
