### ISSUE TITLE
Investigate alternative JSON parsers

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#3338]
e.g., I saw this on reddit: http://ugorji.net/blog/go-codecgen

The primary reason why this would be worth our time at the moment is to get better error messages when people do things like pass a string to an array, or misspell a field name. Performance will eventually become important as we scale up, but serialization performance is a very tiny issue compared with e.g. the serial health checking when you list minions.

**Comment by erictune** [comment]
Agree that better error messages is primary reason.  Not sure parsing performance will be an issue, since we have to shard for availability, and that creates adequate parallelism.

**Comment by erictune** [comment]
Wondering if the code generation approach has any aspects that could be borrowed for the client code generation we talked about.

**Comment by bgrant0607** [comment]
IMO, code generation should be a last resort -- it incurs a significant cost in debugging complexity and binary size. Also, it's not going to work for API plugins.

There are other ways to do validation.

**Comment by bgrant0607** [comment]
Copied from #4872: https://github.com/rainingclouds/autobindings

**Comment by sdminonne** [comment]
@smarterclayton @lavalamp landing here from https://github.com/openshift/origin/issues/1243
Our issue is with kubectl: basically reported errors are not human readable. Not sure if we need to replace the whole json marshalling... We may just need to validate json and schema before unmarshalling eventually only for CLI.  Eventually returning line number in case of missing comma or similar.

**Comment by bgrant0607** [comment]
@sdminonne Have you tried the swagger validation in kubectl (--validate)? Does it suffer from this problem?

cc @nikhiljindal

**Comment by sdminonne** [comment]
@bgrant0607  I was not aware of. I'll do a test tomorrow. Thanks

**Comment by vmarmol** [comment]
+1 to this, I just spent more time than I'd like to admit debugging #5326 and the root cause was a typo in one of the fields "readyOnly" instead of "readOnly". No error message was generated, the field was simply silently dropped.

**Comment by gmarek** [comment]
+1. I believe it's at least P2 if not P1, as it impacts performance and usability.

**Comment by sdminonne** [comment]
@bgrant0607 I managed to have a look at this

`--validate=true` helps only for basic JSON syntax troubles.
Removing a comma in a JSON produces:  `Client error processing command: unable to get type info from ... : couldn't get version/kind: error converting YAML to JSON: yaml: line 15: did not find expected ',' or '}'` which is not so explicit but fair enough.

**Comment by smarterclayton** [comment]
https://github.com/dustin/go-jsonpointer is an interesting implementation for locating arbitrary json - we could easily convert some of the proposed syntaxes into this form.  

We really want more control over both phases: tokenization (for better error reporting and debugging of local json files in the cli) and structural comparison.  The author of that library also forked the go json scanner to expose scanning more directly. We could potentially extend further and hook ignored keys (not recognized) and maltyped keys.

I'm a bit worried about flagging typo keys because that breaks forwards compat.  That sort of behavior should be client specific (kubectl logs to stderr unrecognized fields).

**Comment by smarterclayton** [comment]
I've followed ffjson for a while now, and I'm starting to think it has some unique advantages for us given our current choices.  We may need additional things (like being able to generate code for checking type matching on fields), but it in theory could leverage our existing structs, be extended to handle defaulting and conversions, and gets us much closer to the ideal goal of versioned JSON -> internal object.

**Comment by smarterclayton** [comment]
https://github.com/ugorji/go Is probably better than ffjson.  It also gets me thinking of how conversion really should be generated (nothing in convertor.go is truly dynamic) - if I had more time I'd give a try of using the existing conversion framework to generate go code to do conversions.  Then we could depend on a json -> go library for decoding encode, and focus more on internal object behavior (smart objects).

**Comment by wojtek-t** [comment]
This is becoming more important now not only for validating errors, but since json (un)marshaling is currently a significant factor in our performance.

cc @fgrzadkowski

**Comment by bgrant0607** [comment]
Re. validation, see https://github.com/GoogleCloudPlatform/kubernetes/issues/7598#issuecomment-99496662

**Comment by bgrant0607** [comment]
@wojtek-t If you have data re. amount of time spent in (un)marshaling, separate from other parts of decoding/encoding (conversion, etc.), please post it here.

**Comment by smarterclayton** [comment]
We probably want to be careful about immediately diving in and using ugorji for validation - we probably want to identify all the possible errors, not just the first, and we need to tolerate fields that are unrecognized (otherwise new clients can't talk to old servers).  It's really fields that are type mismatched that we need to flag, or when a validation error occurs on a field, look for similarly named fields on the incoming object (which is hard because validation happens much later).

----- Original Message -----

**Comment by wojtek-t** [comment]
>
@wojtek-t If you have data re. amount of time spent in (un)marshaling, separate from other parts of decoding/encoding (conversion, etc.), please post it here.

This is more than 25% of cpu usage now, but I will do detailed profiling and post the profile tomorrow.

**Comment by thockin** [comment]
On Wed, May 6, 2015 at 7:49 AM, Clayton Coleman
<notifications@github.com> wrote:
>
> We probably want to be careful about immediately diving in and using ugorji for validation - we probably want to identify all the possible errors, not just the first, and we need to tolerate fields that are unrecognized (otherwise new clients can't talk to old servers).

We do this inside Google with proto because we do not generally have
versioned APIs.  With versioned APIs, I think that rejecting unknown
fields is much more tenable.  Specifically, you asked for something
and we don't know how to handle it.  Ignoring it MIGHT be OK, but it
might also cause the result to be semantically different than what I
asked for.

This is a hard problem, but I think that our experience so far says
that it would be better to flat out reject.

>It's really fields that are type mismatched that we need to flag, or when a validation error occurs on a field, look for similarly named fields on the incoming object (which is hard because validation happens much later).

Unless we want to leave "forwarding instructions" on all new APIs for
fields from old APIs, I disagree.  We have had a LOT of bug reports
from people fat-fingering field names or using field names from
v1beta1 in a v1beta3 object. etc.

Having the API accept all at the same time sounds great, but quickly
becomes glacial.  We have versioned APIs so that we don't have to deal
with that.

**Comment by smarterclayton** [comment]
----- Original Message -----
> On Wed, May 6, 2015 at 7:49 AM, Clayton Coleman
> <notifications@github.com> wrote:
> >
> > We probably want to be careful about immediately diving in and using ugorji
> > for validation - we probably want to identify all the possible errors, not
> > just the first, and we need to tolerate fields that are unrecognized
> > (otherwise new clients can't talk to old servers).
> 
> We do this inside Google with proto because we do not generally have
> versioned APIs.  With versioned APIs, I think that rejecting unknown
> fields is much more tenable.  Specifically, you asked for something
> and we don't know how to handle it.  Ignoring it MIGHT be OK, but it
> might also cause the result to be semantically different than what I
> asked for.

That means we can no longer add new fields to v1beta1.  Instead every new field requires a new api version....

**Comment by smarterclayton** [comment]
----- Original Message -----
> 
> 
> ----- Original Message -----
> > On Wed, May 6, 2015 at 7:49 AM, Clayton Coleman
> > <notifications@github.com> wrote:
> > >
> > > We probably want to be careful about immediately diving in and using
> > > ugorji
> > > for validation - we probably want to identify all the possible errors,
> > > not
> > > just the first, and we need to tolerate fields that are unrecognized
> > > (otherwise new clients can't talk to old servers).
> > 
> > We do this inside Google with proto because we do not generally have
> > versioned APIs.  With versioned APIs, I think that rejecting unknown
> > fields is much more tenable.  Specifically, you asked for something
> > and we don't know how to handle it.  Ignoring it MIGHT be OK, but it
> > might also cause the result to be semantically different than what I
> > asked for.
> 
> That means we can no longer add new fields to v1beta1.  Instead every new
> field requires a new api version....
> 
> > 
> > This is a hard problem, but I think that our experience so far says
> > that it would be better to flat out reject.
> > 
> > >It's really fields that are type mismatched that we need to flag, or when
> > >a
> > >validation error occurs on a field, look for similarly named fields on the
> > >incoming object (which is hard because validation happens much later).
> > 
> > Unless we want to leave "forwarding instructions" on all new APIs for
> > fields from old APIs, I disagree.  We have had a LOT of bug reports
> > from people fat-fingering field names or using field names from
> > v1beta1 in a v1beta3 object. etc.
> > 
> > Having the API accept all at the same time sounds great, but quickly
> > becomes glacial.  We have versioned APIs so that we don't have to deal
> > with that.

The vast majority of versioned REST APIs I'm aware of have a "ignore what you don't expect, allow new fields to be added" policy, except those that micro version (every property change causes an api version change).

**Comment by thockin** [comment]
On Wed, May 6, 2015 at 10:46 AM, Clayton Coleman
<notifications@github.com> wrote:
>
>
>
> ----- Original Message -----
> > On Wed, May 6, 2015 at 7:49 AM, Clayton Coleman
> > <notifications@github.com> wrote:
> > >
> > > We probably want to be careful about immediately diving in and using ugorji
> > > for validation - we probably want to identify all the possible errors, not
> > > just the first, and we need to tolerate fields that are unrecognized
> > > (otherwise new clients can't talk to old servers).
> >
> > We do this inside Google with proto because we do not generally have
> > versioned APIs. With versioned APIs, I think that rejecting unknown
> > fields is much more tenable. Specifically, you asked for something
> > and we don't know how to handle it. Ignoring it MIGHT be OK, but it
> > might also cause the result to be semantically different than what I
> > asked for.
>
> That means we can no longer add new fields to v1beta1. Instead every new field requires a new api version....

No, it means you have to not try to use fields before your master
supports them.  That's very different.  Now, this may be a problem as
long as kubectl is doing version conversions and defaulting.

> The vast majority of versioned REST APIs I'm aware of have a "ignore what you don't expect, allow new fields to be added" policy, except those that micro version (every property change causes an api version change).

Yeah, it's a tradeoff of "do you help people get what they really
wanted" vs freedom to mix-and-match components.  I used to be a
mix-and-match guy, but I've seen a lot of people file bugs on fields
that are wrongly named or typed and don't produce errors.

Maybe we can find middle ground - could we leave "traps" in new APIs
that receive field names from old APIs and cause errors?  E.g. if a
user said "hostDir", we would give back an error "I think you meant
hostPath", but if they said "fooBar" we would ignore it since we never
knew it in the past.

But this still doesn't answer the issue of "I need the new frobnicator
feature, but I forgot to upgrade my master", why did my job run at
all?

**Comment by smarterclayton** [comment]
----- Original Message -----
> On Wed, May 6, 2015 at 10:46 AM, Clayton Coleman
> <notifications@github.com> wrote:
> >
> >
> >
> > ----- Original Message -----
> > > On Wed, May 6, 2015 at 7:49 AM, Clayton Coleman
> > > <notifications@github.com> wrote:
> > > >
> > > > We probably want to be careful about immediately diving in and using
> > > > ugorji
> > > > for validation - we probably want to identify all the possible errors,
> > > > not
> > > > just the first, and we need to tolerate fields that are unrecognized
> > > > (otherwise new clients can't talk to old servers).
> > >
> > > We do this inside Google with proto because we do not generally have
> > > versioned APIs. With versioned APIs, I think that rejecting unknown
> > > fields is much more tenable. Specifically, you asked for something
> > > and we don't know how to handle it. Ignoring it MIGHT be OK, but it
> > > might also cause the result to be semantically different than what I
> > > asked for.
> >
> > That means we can no longer add new fields to v1beta1. Instead every new
> > field requires a new api version....
> 
> No, it means you have to not try to use fields before your master
> supports them.  That's very different.  Now, this may be a problem as
> long as kubectl is doing version conversions and defaulting.

This is a big problem for people who have existing stable deployments and new clients that need to talk to multiple servers.  It effectively means that the client you use to talk to X servers has to be min(version){X}, which is practically impossible to manage.

> 
> > The vast majority of versioned REST APIs I'm aware of have a "ignore what
> > you don't expect, allow new fields to be added" policy, except those that
> > micro version (every property change causes an api version change).
> 
> Yeah, it's a tradeoff of "do you help people get what they really
> wanted" vs freedom to mix-and-match components.  I used to be a
> mix-and-match guy, but I've seen a lot of people file bugs on fields
> that are wrongly named or typed and don't produce errors.
> 
> Maybe we can find middle ground - could we leave "traps" in new APIs
> that receive field names from old APIs and cause errors?  E.g. if a
> user said "hostDir", we would give back an error "I think you meant
> hostPath", but if they said "fooBar" we would ignore it since we never
> knew it in the past.

I'm ok with that - it was the converse that has me concerned.  Just because I have kubectl 1.1 and I need to talk to a 1.1 Kube and a 1.0 Kube, I can't be rejected from contacting a 1.0 Kube.

> 
> But this still doesn't answer the issue of "I need the new frobnicator
> feature, but I forgot to upgrade my master", why did my job run at
> all?

I think you're using to thinking about a few centrally maintained masters, and I'm used to thinking about enterprises that will have 3 or 4 versions of a major piece of software all running simultaneously, plus a cloud hosted version.  In the former case you're right, the better behavior is "your client doesn't match your master".  In the latter case, angry mobs of developers hunt you down and burn your keyboard.

**Comment by bgrant0607** [comment]
Can we please not have the versioning/validation discussion on this issue? Please comment on #4855 instead.

**Comment by wojtek-t** [comment]
>
@wojtek-t If you have data re. amount of time spent in (un)marshaling, separate from other parts of decoding/encoding (conversion, etc.), please post it here.

The example profile where json unmarshaling plays significant role is pasted below.
In this particular profile unmarshaling is ~26% of CPU usage (cpu was saturated at that time). Usually I'm observing json-marshaling consuming 15-30% of CPU.

![profile](https://cloud.githubusercontent.com/assets/10743879/7564710/c24f5de6-f7e9-11e4-92c4-8b349dadf604.png)

**Comment by thockin** [comment]
Am I reading this wrong, or is this indicating that 23 of that 26% is in
etcd's Unmarshalling?

**Comment by smarterclayton** [comment]
Deep copy is also 20.  Can we fix deep copy before we bring in the JSON parser?

**Comment by timothysc** [comment]
@wojtek-t post 1.0, can't we defer the unmarshaling to a protobuf shift?

**Comment by wojtek-t** [comment]
>
Am I reading this wrong, or is this indicating that 23 of that 26% is in
etcd's Unmarshalling?

It seems to be.

>
Deep copy is also 20. Can we fix deep copy before we bring in the JSON parser?

Sure - I already started looking into - I hope to have something working later this week.

>
@wojtek-t post 1.0, can't we defer the unmarshaling to a protobuf shift?

I'm fine with that. As I wrote above, I will be working on DeepCopy now.

**Comment by bgrant0607** [comment]
@timothysc If you're interested in protobuf, please file a separate issue for that.

**Comment by bgrant0607** [comment]
The apiserver should be a dumb CRUDy server, so it should be spending all its time on unmarshaling/marshaling, defaulting, validation, conversion, reading/writing from/to etcd, and memory allocation/GC.

**Comment by wojtek-t** [comment]
>
The apiserver should be a dumb CRUDy server, so it should be spending all its time on unmarshaling/marshaling, defaulting, validation, conversion, reading/writing from/to etcd, and memory allocation/GC.

I think noone disagrees with that, but currently there are either too many of these operations or they are to slow. That's why we're trying to speed up some of them.

**Comment by fgrzadkowski** [comment]
For the last two days I've been investigating ugorji codec. Unfortunately I've already found 3 bugs:
https://github.com/ugorji/go/issues/68
https://github.com/ugorji/go/issues/70
https://github.com/ugorji/go/issues/71

Fortunately we have pretty good test coverage for most json-related things, but this is troubling :/

**Comment by bgrant0607** [comment]
See #9348, which uses ffjson

**Comment by erictune** [comment]
Raising priority because error handling of current impl is atrocious.

### Unrecognized keys are silently dropped
so if you nest a key one level too high or too low, it just gets ignored and the object is created.
so in this example:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: frontend3
spec:
   resources:
     limits:
       memory: "100M"
       cpu: "500m"
  containers:
  - name: db
    image: mysql
    mistake:
```
4 lines of otherwise correct spec are dropped because they are mistakenly placed under the wrong parent.  Combine silent dropping of fields with automatic setting of fields (e.g. resources.limits.cpu automatically set by limitRanger) and you have a recipe for seriously confused users.

### Unrecognized keys are silently dropped
Error messages are still opaque.
If a user creates this pod:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: frontend3
spec:
  resources:
    limits:
      memory: "100M"
      cpu: "500m"
  containers:
  - name: db
    image: mysql
  nodeSelector: somehostname
```
They get this error:
```
error: unable to load file "a.yaml": unable to load "a.yaml": json: cannot unmarshal string into Go value of type map[string]string
error: no objects passed to create
```
1. why do I need to see "unable to load file" twice?
1. at which line was it expecting find a map[string]string

**Comment by erictune** [comment]
I'd like to see this split into two issues, one for usability, and one for performance.
The former is much more urgent.

**Comment by bgrant0607** [comment]
Usability is #5889

**Comment by bgrant0607** [comment]
Note that the lame error message has been known for a long time: https://github.com/golang/go/issues/6716

**Comment by a-robinson** [comment]
Another annoyance from the parser we're using: you can't pass numbers to fields that are expected to be strings without wrapping them in quotation marks.

```yaml
    env:
    - name: FOO
      value: 100
```

The yaml above fails to parse, saying `json: cannot unmarshal number into Go value of type string`. The yaml below with quotation marks added works.

```yaml
    env:
    - name: FOO
      value: "100"
```

**Comment by wojtek-t** [comment]
I started looking into it from the performance point of view. I looked into:
- ugorji/codec - in the current form it just doesn't work for our structures (so far I filed https://github.com/ugorji/go/issues/94 and https://github.com/ugorji/go/issues/95 - but I'm afraid it's not the end)
- ffjson - it mostly works, but the gain here is not very significant (it's more like 20% and definitely not 2-3x how they announce it)

**Comment by timothysc** [comment]
@wojtek-t At what point do we re-evaluate the cost/benefits of putting etcd behind the api-server?  

The api-server is clearly the bottleneck, and carries the burden of encoding&decoding etcd.

**Comment by wojtek-t** [comment]
@timothysc - sorry I didn't understand the question. I agree that api-server is obviously the bottleneck. What do you mean by:
"At what point do we re-evaluate the cost/benefits of putting etcd behind the api-server?"
Did you mean measuring performance without etcd (i.e. backed by e.g. in-memory storage or some other database)? That would obviously be useful, but that seems like a lot of work.

**Comment by fgrzadkowski** [comment]
@wojtek-t @timothysc AFAIU Timothy is considering an architecture where clients talk directly to etcd. Is my understanding correct? It would definitely increase performance, but would also mean that etcd API is part of our official API, which doesn't sound like a good idea to me.

**Comment by timothysc** [comment]
> but would also mean that etcd API is part of our official API
I'm not advocating that...

**Comment by wojtek-t** [comment]
I did another step in evaluating parsers. As wrote above, ffjson given a very small gains.

ugorji seems to be much better, but there are still some issues with it (the previously files bugs are already fixed, but I just filed another one: https://github.com/ugorji/go/issues/97)

However, it's in the shape that I was able to do some benchmarking, and in the current code marshaling/unmarshaling pods seems to be ~2x faster (than using encoding/json). So I will be working with authors of ugorji code to fix the remaining issues.

**Comment by fgrzadkowski** [comment]
@wojtek-t When I was working on using ugorji in etcd client library this happened to me as well. I filed number of issues, after which it started to work again. Apparently it's broken again. I think the problem is that it lacks tests (any sort of tests honestly). Some of the problem I've seen were so obvious that even a very basic test would caught it.
Maybe we should push the owner to write some. WDYT?

**Comment by wojtek-t** [comment]
Yes - I think this would be valuable. Currently I'm working with him to fix the existing issues. He already fixed few of them and it seems we're quite close now...

**Comment by wojtek-t** [comment]
BTW - we are pretty close after a bunch of fixes made to the library (there is only one unit test failing now).

**Comment by smarterclayton** [comment]
I love me some free* performance improvements

* some assembly required

On Sep 15, 2015, at 10:49 AM, Wojciech Tyczynski <notifications@github.com>
wrote:

BTW - we are pretty close after a bunch of fixes made to the library (there
is only one unit test failing now).

—
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/3338#issuecomment-140417877>
.

**Comment by lavalamp** [comment]
We are using ugorji now.

Wow, this is an old issue.

**Comment by krmayankk** [comment]
@lavalamp was this only about json or also yaml parser. Would using ugorji improve error handling for kubernetes manifests as well or is this in different context ?

**Comment by lavalamp** [comment]
@krmayankk Not really sure what you're asking. I think there are other issues for this topic. ugorji is only json.

**Comment by krmayankk** [comment]
@lavalamp  basically if there are errors in the yaml that kubectl consumes, i dont see lot of very easily diagnosable error information in it. Wanted to know if ugorji solves that or not ?

**Comment by lavalamp** [comment]
No, it doesn't. There's another issue about that floating around somewhere.
