### ISSUE TITLE
loadBalancerSourceRanges should apply to nodePort

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#33586]
Since `Type=NodePort` is also a "loadbalancer", @freehan fyi

**Comment by freehan** [comment]
We thought about it. But I do not think all LB proxy like ELB preserves source IP.

**Comment by bprashanth** [comment]
NodePort is the poor man's loadbalancer. If you do `kubectl expose` on GCE you get a loadbalancer, if you do the same thing on-prem, you just get a NodePort service. Maybe we can never apply the source ip filters on AWS, but the first node traffic hits for a nodePort can apply the firewall filter right?

**Comment by freehan** [comment]
On AWS, the source ip filter is done thru security group configured on ELB. 

If hitting the node directly, then we can do source ip filtering.

**Comment by bprashanth** [comment]
Exactly, meaning I can plug all the nodes I have :nodePort into DNS for my site and disallow all but 1 CIDR block from ever hitting my endpoints quite easily, if this worked. I can also whitelist country blocks.

**Comment by freehan** [comment]
Okay. How do we decide whether we should filter or not? By Cloud Provider? What should be the default then?

**Comment by bprashanth** [comment]
Don't we unconditionally apply it for type=lb today?

**Comment by bprashanth** [comment]
hmm, maybe we escape because IIRC we only do it if ingress.IP != "" and on AWS you only have a hostname. So I guess you're saying if we detected the nodePort and applied the filter, the ELB will stop working. It sounds like we're already broken if AWS allocates IPs suddenly, but that's a good point, we need to figure out how we handle the nodePorts allocated to incompatible cloud lbs. 

This is however different from applying it for type=nodeport (though we should probably apply the same policy to nodeport everywhere).

**Comment by freehan** [comment]
Then should we consider to extend it to `sourceRanges` instead of `loadBalancerSourceRanges`?
For cluster ip and nodeport, just do whatever user specifies. 
For loadbalancer, special case for AWS and other cloud providers where traffic got proxied to node port without source ip preservation. Or for loadbalancer, we do not filter for node port?

More corner cases?

**Comment by bprashanth** [comment]
I think we should leave it as loadbalancersource. I'm sure there's something equivalent in network policy to enforce intra cluster segmentation (though that will probably end up being iptables, we won't be the policy engine).

**Comment by freehan** [comment]
Make sense.
So for type=nodeport, we filter it.
For type=lb, we filter based on cloud provider?

**Comment by bprashanth** [comment]
I don't know how we'd do it based on cloud provider though, since kubeproxy knowns nothing about that. Sounds like we just get lucky today.

**Comment by tonglil** [comment]
I would like to present a use case for this here.

We are running in GKE, and the way to have K8s manage firewall rules is to use `loadBalancerSourceRanges`, which is only available with `type: LoadBalancer`.

However, because we want to use an Ingress resource as well, this means 2 "load balancers" (in GCP, they are just rules and targets) get created in GCP, and traffic only actually "uses" the one created by Ingress.

The one created by the Service basically only tags the instances and adds the firewall rules to the target tags, sitting there not "load balancing" traffic, and maybe costing $?

Ideally we would use `type: NodePort` and `loadBalancerSourceRanges` to establish the firewall rules, and let Ingress' load balancer point traffic at the NodePort ports. It is weird to have 2 LBs in order to get this behavior.

Does that make sense?

**Comment by bprashanth** [comment]
Hmm, Ingress doesn't actually have the right source ip. The l7 lb will terminate the connection and reopen another, so the source ip on the packet hitting the node port is the ip of the gce L7, not your client.

**Comment by tonglil** [comment]
Let me do some testing and get back to you. Maybe I've got this wrong. Thanks.

**Comment by tonglil** [comment]
Hi @bprashanth, you are correct in that the connection to the application is from the L7 LB itself.

1) How does one configure FW rules for the LB from Kubernetes? Is this feature something on the roadmap for Ingress? Or does this need to be a manual step outside of K8s?

2) Since the L7 LB sends traffic to the node ports directly, is the `backend` in Ingress only used as a selector for traffic?

**Comment by bprashanth** [comment]
The ingress controller creates a firewall rule for google's anycase ip range, and adds each node port from the service in the ingress to it. The backend in GCE ingress is used to figure out which node port to send to currently, this is an implementation detail and likely to change. Nginx ingress for examples uses the backend to lookup endpoints and go directly to them.

**Comment by tonglil** [comment]
Thanks, I meant that if I want to limit the traffic to my application from a certain IP, do I need to add those additional FW rules in GCP's firewall myself (no K8s way to do it)?

**Comment by bprashanth** [comment]
You will need to run something like nginx behind the gce ingress and reject
based on X-FORWARDED-FOR header that the GCE L7 inserts (contains the true
client ip). There is no way to program the GCE L7 to reject based on source
on k8s or gce.

**Comment by tonglil** [comment]
Interesting, ok thanks. Is that on the roadmap at all?

**Comment by bprashanth** [comment]
https://github.com/kubernetes/contrib/tree/master/ingress/controllers/nginx/examples/whitelist
helps maybe? if not, please figure out the nginx options that filter
looking at XFF and file a bug at https://github.com/kubernetes/ingress

**Comment by brunobowden** [comment]
Issue was created by @nickform for Source IP whitelist support for the Ingress Controller on GKE:

https://github.com/kubernetes/ingress/issues/566

**Comment by cmluciano** [comment]
@kubernetes/sig-network-bugs think this is still relevant?
