### ISSUE TITLE
Fix "WARNING: CPU hardcapping unsupported"

### ISSUE THREAD

**Issue by dmitrig01** [kubernetes/kubernetes#33594]
**Kubernetes version** (use `kubectl version`): 1.3.5

**Environment**:
- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release): Debian Jesse
- **Kernel** (e.g. `uname -a`): `Linux ip-172-20-46-179 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2 (2016-04-08) x86_64 GNU/Linux`
- **Install tools**: kops

**What happened**:
Kubelet reports "WARNING: CPU hardcapping unsupported" as part of the Ready status

**What you expected to happen**:
no error message :-)

**Anything else do we need to know**:
@justinsb suggested it could be "fixed in the 1.4 default image"

Thanks!!

**Comment by justinsb** [comment]
I had a look, and I think this is actually #23142, and that gives the magic config option that is needed.  And it is already in the config for the kernel I am working on: https://github.com/kopeio/kubernetes-kernel

**Comment by justinsb** [comment]
This should now be fixed with the latest images.  If you update kops, you can do `kops upgrade cluster`, and it should prompt you to update the cluster.  Then a 4.4 kernel is just a `kops update cluster` and `kops  rolling-update-cluster` away.

If you're feeling less adventurous, you can also create a second instance group (`kops create ig`) with the new image, as found here: https://github.com/kubernetes/kops/blob/master/channels/stable#L3, and create that (and then you can `kops delete ig` on the old instance group or scale it down gradually)
