### ISSUE TITLE
Self-links are not cleaned up when exporting resources

### ISSUE THREAD

**Issue by kargakis** [kubernetes/kubernetes#33767]
I have noticed it a couple of times that when I am trying to export a resource, selflinks stay around and the namespace is not part of the link anymore.

```
[mkargaki@dhcp129-211 kubernetes.github.io]$ kc get quota -o yaml
apiVersion: v1
items:
- apiVersion: v1
  kind: ResourceQuota
  metadata:
    creationTimestamp: 2016-09-29T16:53:38Z
    name: object-counts
    namespace: default
    resourceVersion: "63"
    selfLink: /api/v1/namespaces/default/resourcequotas/object-counts
    uid: 4494594b-8665-11e6-9fad-68f72840e7df
  spec:
    hard:
      pods: "2"
  status:
    hard:
      pods: "2"
    used:
      pods: "0"
kind: List
metadata: {}
$ kc get quota object-counts --export -o yaml
apiVersion: v1
kind: ResourceQuota
metadata:
  creationTimestamp: null
  name: object-counts
  selfLink: /api/v1/namespaces//resourcequotas/object-counts
spec:
  hard:
    pods: "2"
status: {}
```

We could maybe have this issue as a duplicate of https://github.com/kubernetes/kubernetes/issues/24855 but I thought we already cleaned up object meta.

@kubernetes/sig-apps

**Comment by davidopp** [comment]
This seems more like @kubernetes/sig-api-machinery

**Comment by smarterclayton** [comment]
Yikes - when did that break?

**Comment by kargakis** [comment]
@kubernetes/sig-api-machinery-misc @kubernetes/sig-cli-bugs

**Comment by adohe** [comment]
@smarterclayton do we need to fix this now? I notice that you commented in #41880, this will be fixed as server side get.

**Comment by smarterclayton** [comment]
Self links aren't a significant problem (they don't block anything) so we
can wait quite a while to fix this.  Really just cosmetic


On Apr 3, 2017, at 3:12 PM, TonyAdo <notifications@github.com> wrote:

@smarterclayton <https://github.com/smarterclayton> do we need to fix this
now? I notice that you commented in #41880
<https://github.com/kubernetes/kubernetes/issues/41880>, this will be fixed
as server side get.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/33767#issuecomment-291138195>,
or mute the thread

**Comment by adohe** [comment]
Roger that.

**Comment by nikhita** [comment]
/remove-lifecycle stale
Fixed by https://github.com/kubernetes/kubernetes/pull/57937.

**Comment by liggitt** [comment]
Server side export is deprecated

/close
