### ISSUE TITLE
install gcloud in gci toolbox

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#33871]
Container vm had gcloud and it was really useful for debugging, can we pre-install it in the toolbox? 
@kubernetes/goog-image

**Comment by adityakali** [comment]
Please assign this to me. We are working on this.

**Comment by wonderfly** [comment]
Happened to see this. @adityakali I think we can close this now?

**Comment by adityakali** [comment]
yes, please do. gcloud is now pre-installed in the toolbox container used by gci.

**Comment by bprashanth** [comment]
Thanks! so this is as of 1.4.5 (the next minor release)? or is it already out? 
Also, is toolbox running as a docker container behind the scenes, or some other non-docker sandbox? im asking because I want to know if something I do in a toolbox that ends up logging 1000s of lines to stdout can potentially make docker unresponsive.

**Comment by adityakali** [comment]
This is available since `gci-dev-55-8872-18-0` and onwards. So k8s v1.4.4 already uses toolbox with gcloud preinstalled.
Docker is used only on first use of toolbox to pull the image and create a container from it. After that, any commands you run inside toolbox are run under `systemd-nspawn` and doesn't involve docker. 
`gcloud` is installed under `/google-cloud-sdk/bin/`. At the moment, that path is not in default `$PATH` environment inside toolbox. So you may have to add it explicitly before using `gcloud` directly:

```
# inside toolbox:
$ export PATH="/google-cloud-sdk/bin:$PATH"
$ which gcloud
/google-cloud-sdk/bin/gcloud
```

**Comment by tonglil** [comment]
This still seems the case and not made very explicit. Any updates?

**Comment by adityakali** [comment]
This has been fixed in the image sometime back. I believe the next Kubernetes image update (https://github.com/kubernetes/kubernetes/pull/41027) will pick up the new image with fixes.

**Comment by tonglil** [comment]
Thank you
