### ISSUE TITLE
kubectl produces a very cryptic message on DNS failure

### ISSUE THREAD

**Issue by errordeveloper** [kubernetes/kubernetes#33877]
I am seeing this and it's very cryptic. I'm using GKE and it makes feel like GKE is `accounts.google.com` flaky and then I catch the `write udp` part, and I am very confused thinking about why there is anything to do with UDP?

```
Unable to connect to the server: Post https://accounts.google.com/o/oauth2/token: dial tcp: lookup accounts.google.com on 192.168.0.1:53: write udp 192.168.0.2:64479->192.168.0.1:53: i/o timeout
```

I think a much more useful message, would be:

```
Unable to lookup accounts.google.com
```

Additionally, I think it may be good idea to retry lookup a couple of times, particularly in the case of UDP write timeout.

**Comment by jeremywadsack** [comment]
DNS uses UDP over port 53 for lookups.

Incidentally we have had this quite often as well. I think the DNS is the issue though, not `accounts.google.com` because it's a look up failure. I've seen the same for `accounts.google.com`, but probably because we send tons of requests to that host. Usually this happens for us when a node is about to become out-of-memory and `kube-dns` fails. 

Upgrading Kubernetes to 1.4 reduced the incidents of this failure.

**Comment by errordeveloper** [comment]
/close

I haven't seen this behaviour in a while...
