### ISSUE TITLE
Master is added to NodePort / AWS ELBs

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#33884]
I noticed that the master node is now added to NodePort and to AWS ELBs, now that the master is registered as a Node.

I think we probably don't want to do this, as we don't want to be bouncing traffic through the master, for performance reasons.  Also the master doesn't always run kube-proxy.

**Comment by justinsb** [comment]
cc @girishkalele @thockin

**Comment by justinsb** [comment]
Another reason this is a bad idea: this also means we're likely to open up a port on the master

**Comment by thockin** [comment]
@kubernetes/sig-network

**Comment by bprashanth** [comment]
Can you clarify "get added to nodeport"? If the master is running kube-proxy, it will open up the nodeport on the master and proxy requests to endpoints. If you're not, the master nodePort is left closed. If you're listing all nodes and adding external-ip:nodePort to an lb, you should instead list only schedulable nodes. If the master is not marked unschedulable, that's a bug.

**Comment by justinsb** [comment]
Ah, I think this is the problem:
>  If the master is not marked unschedulable, that's a bug.

The master is not marked unschedulable.  But that is correct, because we are supposed to use taints and tolerations instead.  We mark it schedulable with a taint so that we can use deployments for our system components.

kops does today where we're (likely) going now that we include the master: it runs kube-proxy, it gets a PodCIDR, it has a taint but is not marked Unschedulable, the master will allow `kubectl logs`.

I think we both need:

1) a way to make sure kube-proxy doesn't open NodePort on the master when the master is tainted
2) a way to exclude the master from the servicecontroller that doesn't rely on Unschedulable, as that is going way

If we agree I can split into two separate issues.

**Comment by bprashanth** [comment]
I guess the point of making the master just another node that you can now run master components on just any other node. If we need to treat it specially, we need some stigma, right? saying every unschedulable node (be it through taint or explicity field) doesn't get nodePort seems wrong.

**Comment by justinsb** [comment]
As I understand the reasoning behind moving from Unschedulable to taints: taints expose greater control.  So we can say "these instances can run etcd", and "these instances can run apiserver".  And we allow "userspace" to have the same control.

It also means we can run our system components as e.g. deployments; today they are required to bypass the scheduler (i.e. be in /etc/kubernetes/manifests).

(I actually think we should continue to remove a node that has been `kubectl cordon node` from load balancers, as it is likely undergoing maintenance.  I added a note in the code.)

cc @mikedanese  and @davidopp as this is more taints stuff (LMK if I should not be cc-ing you on these!)

Sent PR #35902, which will stop us adding new-master nodes to LoadBalancers, but does not address the concern that we shouldn't even be opening the NodePort on a master.

**Comment by caseydavenport** [comment]
I'm not sure I'm convinced yet that we never want to open NodePorts on master nodes (i.e that triggering off of master / non-master is correct).

Seems like there should be a way to say "don't open node-ports on this node", but using the "master" as the switch doesn't feel right.  If the old way was to check the unschedulable mark, can we maintain that behavior by looking at the "unchedulable" taint instead?

**Comment by justinsb** [comment]
@caseydavenport we will continue to honor unschedulable - that'll be important for when a node is cordon-ed e.g. for maintenance.  #35902 will say that if a node is marked as a dedicated node in the specific key "master" we will avoid it.  Similarly we recognize two labels that are applied by installation tools like kops & kubeadm today.  I did it this way for consistency with https://github.com/kubernetes/kubernetes/pull/35901

I don't mind if we don't key off the name of the taint and simply treat any NoSchedule taint as the equivalent of unschedulable, and/or if we ignore the labels. Is that what you're suggesting instead?  If not, can you explain what you are suggesting?

**Comment by davidopp** [comment]
Yes, when #29178 is implemented then Unschedulable will be represented as a taint that you can use to decide whether a pod should schedule on the node. (We can also do a special taint just for the master, if that helps.) But this won' t be in 1.5.

**Comment by davidopp** [comment]
Hmm, it looks like #31647 has the intention of having the master node register with a taint, and that PR is already merged. It wasn't clear to me if we are actually using it to have master node register with a taint yet, though. @mikedanese can you clarify?

**Comment by justinsb** [comment]
@davidopp kops already has tainted masters that are otherwise schedulable - the genie is out of the bottle.  It's why I'm pushing to fix all these taint issues :-)

**Comment by dims** [comment]
This needs to be triaged as a release-blocker or not for 1.5 @justinsb @davidopp

**Comment by dims** [comment]
This needs to be triaged as a release-blocker or not for 1.5

**Comment by dims** [comment]
@justinsb all issues must be labeled either release blocker or non release blocking by end of day 18 November 2016 PST. (or please move it to 1.6) cc @kubernetes/sig-aws

**Comment by justinsb** [comment]
A lot of discomfort around this; marking as a release-blocker for now.

**Comment by chrislovecnm** [comment]
Do we have a PR in to address this?

**Comment by dims** [comment]
@justinsb : @chrislovecnm : How do we unblock the release? What needs to be done here?

**Comment by grodrigues3** [comment]
@justinsb ping

**Comment by justinsb** [comment]
Out of time I think :-(

@thockin can you make a call on the label/annotation to use?

**Comment by grodrigues3** [comment]
does the milestone just get changed?

**Comment by thockin** [comment]
It's not clear to me what the final design is here.  At a glance, unschedulable node probably should NOT be included in load-balancers - they may be going down or undergoing arbitrary maintenance.  Do taints fully obviate `unschedulable`?  What what `cordon` will use to denote a drained node?

**Comment by mikedanese** [comment]
> Do taints fully obviate unschedulable?

They will but they haven't yet. That's https://github.com/kubernetes/kubernetes/issues/29178.

**Comment by thockin** [comment]
So what signal do we use to remove a node from load-balancers gracefully?

**Comment by bprashanth** [comment]
> At a glance, unschedulable node probably should NOT be included in load-balancers

Unschedulable is Ok to include in the lb, people cordon nodes for various reasons but if it's healthy, we can assume the pods on it are serving traffic. 

The node will get removed from the target pool if it is not ready, or it fails enough health checks (i.e onlylocal + no endpoints). We lack a command to do what I think you want (https://github.com/kubernetes/kubernetes/issues/30272).

**Comment by thockin** [comment]
I think we should have a way to say this node is completely out of service"
so we can GRACEFULLY take it out of LBs.  failing HC's is a last resort
because it means we are failing traffic, too!

**Comment by bprashanth** [comment]
Today to truly drain a node the lb actually needs to continue including unschedulable in the target pool. Then when `kubectl drain` marks the node unschedulable, traffic still reaches it, but the deletion timestamp is also set simultaneously on all pods, so they're removed from the endpoints set. Such a node is just proxying requests off node while waiting for endpoints on it to clean up open connections and die. When all endpoints are gone, someone needs to delete the node to truly remove it from the target pool.

**Comment by thockin** [comment]
Deleting the node while it is alive means kubelet might recreate it (race).
Turning off the node before it is deleted means some LB traffic will arrive
at a dead-end.

Both are bad.  We need graceful deletion of nodes.

**Comment by bprashanth** [comment]
Rigth we need to stop services before deleting the node, just like we do with scale down. I imagine a graceful deletion of nodes to look like what i described, without some sort of "LameDuck" mode supported by all cloudproviders.

**Comment by thockin** [comment]
I am confused - you said

> Such a node is just proxying requests off node while waiting for endpoints
> on it to clean up open connections and die. When all endpoints are gone,
> someone needs to delete the node to truly remove it from the target pool.

As long as the node is running, kubelet will try to (race) to recreate the
Node object, I think.

**Comment by bprashanth** [comment]
I'm saying this boils down the "how to delete a node", because we've already solved the draining problem as described. I believe kubelet will only create the node once, but it doens't snapshot so if you delete the node and restart the kubelet, it'll recreate the node. I also *think* there's logic in the nodecontroller to delete the node from cloudprovider when it observes it is gone from Kube (or maybe it's only the other way around). 

We surely need a way to delete a node, and we would trigger that when kubectl drain returns (which will happen after all pods terminated gracefully evacuating the node).

**Comment by bprashanth** [comment]
Or if you don't want to delete the node at the end there, put it in "maintenance mode" via the kubectl command from https://github.com/kubernetes/kubernetes/issues/30272

**Comment by thockin** [comment]
This has gone a little off-target, so I apologize.  Maybe @mml can say more about this path?

**Comment by davidopp** [comment]
Is the question here how do you take a node out of commission?

You're supposed to
1. Run "kubectl drain" -- this marks the node unschedulable (using the field in the Node spec -- we don't use taints for this yet, as various folks already mentioned), then deletes all the pods (see caveat in next sentence) giving them their graceful termination. When "kubectl drain" returns the only pods left on the node are DaemonSets, podes not managed by a controller, pods that use local storage, and mirror pods (you can force-delete these to override).
2. Then delete the VM through your cloud provider. NodeController will see that the VM has disappeared and delete the corresponding Node object. On-prem you should instead kill the kubelet (or just power down the node) and then delete the node object manually.

I don't know the details of what kops does.

My understanding was that deleting the pods with graceful termination removes them from the service endpoints, so that shouldn't be a problem.

I think the only problem is the original one @justinsb mentioned, which has nothing really to do with the above, and is about how to prevent proxying of traffic through the node running the master. But I guess the answer is, just don't run kube-proxy on it?

Tying "unschedulable" (whether the Node Spec implementation or the taint implementation) to removing the node from NodePort proxying or removing its pods from service endpoints doesn't seem like a good idea to me.

Is there anything we need for 1.5 here?

**Comment by bprashanth** [comment]
The first part about how to drain is basically what I described, with one change. You don't always want to delete the node. We need some way to pull the node out of the target pool of the lb without necessarily taking it down (https://github.com/kubernetes/kubernetes/issues/30272). 

> Tying "unschedulable" (whether the Node Spec implementation or the taint implementation) to removing the node from NodePort proxying or removing its pods from service endpoints doesn't seem like a good idea to me.

That was also my feeling, but abusing such another taint/annotation to mean "don't add this node to the cloudprovider target pool" doesn't feel too bad. That's the "dedicated master" annotation done in https://github.com/kubernetes/kubernetes/pull/35902. To remove from nodeport, one still needs to not provision kube-proxy on the node, but at least the node won't start proxying traffic for random cluster services.

**Comment by davidopp** [comment]
> We need some way to pull the node out of the target pool of the lb without necessarily taking it down

I assume by "target pool of the lb" you mean the cloud load balancer?

I think the right approach depends on whether you want something general or specific to the master. If you want something general, you should use a node label or a node annotation. If you want it specific to the master, I think @justinsb was using a label "role=master" and you could specially interpret that to do whatever you want with the cloud load balancer. Ifyou want to also block scheduling pods onto the master and not have it be a back-end for the cloud load balancer, you could use a "role=master" taint instead, I guess.

**Comment by bprashanth** [comment]
Yeah the idead is to come up with a general purpose way to remove the lb from the target pool that we can apply to: 
1. the master, so it doesn't proxy lb traffic
2. any node, so a user can do `kubectl drain node; kubectl remove-node-from-tp` and it no longer gets lb traffic

Obviously that second kubectl command can't be `delete node` if we want to apply it to 1, and the name of whatever we pick for 1 needs to be general enough that we can apply it to 2 (so not role=master I guess).

**Comment by dims** [comment]
@justinsb Is it appropriate to move this to the next milestone or clear the 1.5 milestone? (and remove the non-release-blocker tag as well)

**Comment by ajohnstone** [comment]
Any update on this issue?

**Comment by greg-jaunt** [comment]
I'm hitting the problem described in the original post (master nodes are being used by AWS ELBs for routing service traffic, but they should not be).  The discussion here has diverged from the original problem.

In AWS, master nodes will typically be run on instance types with fewer vCPUs than the worker node instance types to save cost.  In AWS, nodes with fewer vCPUs typically also have lower available virtual network bandwidth.  Routing ELB traffic through both master and worker instances using equal weight round robin will therefore result in performance problems on the master or potentially starve the cluster from being able to access the master when the load is high.

A mechanism for excluding master nodes from ELBs has not been established in this thread.  Taints seem like a very complicated way to do this as you would have to look for some very explicit set of taint parameters that would indicate that no external traffic should ever be routed to the node.  Tagging could be a more-flexible alternative, however since all worker nodes join the ELB all of the provisioned bandwidth of the worker nodes will already be available to any one ELB.  I can't think of a scenario where just always excluding master nodes from ELBs would be problematic.

I can envision problems in a cluster with multiple instance groups, each with nodes of different size.  Blindly ELB round-robining across all instances both instance groups could result in saturating the network on the nodes in the instance group with smaller instances.

IMO:
* This issue could be considered a production blocker for anyone on AWS with high traffic.
* Master nodes should be schedulable so that extra administrative containers can be run on them.  Marking master nodes unschedulable is not a good solution.
* Simply excluding master nodes from ELBs is a simple solution that should not have any undesirable side-effects and should be implemented as a first step.
* A better solution would enable even more control over assignment of nodes to ELBs to ensure all nodes in an ELB are of equal size.

**Comment by dlsniper** [comment]
Based on the comment from @greg-jaunt maybe another solution could be to tag the node if it should be excluded from the load balancer for a certain service? That way you could potentially take a node out of the LB for a certain service but keep it for another service if so desired.

**Comment by greg-jaunt** [comment]
Tags would be the most flexible.  The other alternative that comes to mind is to be able to specify an instance group name in the Service config, since I think nodes in an instance group would always all be the same instance type.  That's less flexible, but foolproof.

An even better solution, IMO, would be to determine what nodes the service is actually running on and only add those nodes to the ELB.

**Comment by quentez** [comment]
The solution of allowing services to have `node-selector` labels (or something similar) to decide what nodes to add to the ELB would be a great solution to this. We're using different instance groups for different workloads, and this results in not all nodes being equal to proxy web traffic.

**Comment by rushtehrani** [comment]
Having something similar to `nodeSelector` on services makes sense, especially if they are `LoadBalancer` services.  For example, we have an instance group for GlusterFS nodes and those nodes should not be added to ELB.

**Comment by justinsb** [comment]
I have checked, and the servicecontroller documents that masters are excluded, and that the only way it can be recognized is via the unschedulable field.

As such I have submitted a PR to fix this, which is a regression for when we are using the new 1.6 taints and the new 1.6 labels for our master.  The servicecontroller now recognizes 1.6 master nodes and will exclude them, returning the documented behaviour :-)

**Comment by renewooller** [comment]
Are we sure this is closed? I've noticed the master node being added to LoadBalancers eg
![ec2_management_console](https://user-images.githubusercontent.com/3643599/27016053-918dee9c-4f5e-11e7-812c-6e1b319f0d14.png)

**Comment by renewooller** [comment]
and https://github.com/kubernetes/kops/issues/853

**Comment by justinsb** [comment]
#44745 added 82d600bb5c34b2c7352643d4d811941e063a8215 which is on the release-1.7 branch (as of v1.7.0-alpha.3), and the backport #44926 added f542fe12837560d991218289e8297dac7362c7ba which is on the 1.6 branch (as of 1.6.3).

But this could also be https://github.com/kubernetes/kubernetes/pull/45773 .

In this case though @renewooller , the fix is not in server 1.6.2.

**Comment by renewooller** [comment]
Thanks for the prompt clarification @justinsb

**Comment by cricci82** [comment]
It seems as though the fix only applies to when nodes are added or removed from the cluster, in which case the nodes in the LB pool are recalculated and only the workers are added.  When creating a new LoadBalancer service masters nodes are still being added.

**Comment by justinsb** [comment]
@cricci82 which k8s version?  https://github.com/kubernetes/kubernetes/pull/45773 should have harmonized the two cases

**Comment by cricci82** [comment]
I'm running 1.6.7

**Comment by justinsb** [comment]
It wasn't backported to 1.6, it looks like: https://github.com/kubernetes/kubernetes/commit/976e046f7a8d220dfd1df2e2f61d4630bcfbaf4c

**Comment by cricci82** [comment]
That explains it, thank you!

**Comment by ljani** [comment]
I'm running a single node cluster on AWS EC2, ie. scheduling work on the master as well. Now that I tried to add an ELB for my service, the EC2 instance is not associated with the ELB. The reason seems to be [this](https://github.com/kubernetes/kubernetes/commit/82d600bb5c34b2c7352643d4d811941e063a8215#diff-56c9c66bf151b9d7268939da6ebf3613R609). Is my scenario a supported one? @greg-jaunt what would be the second step you were implying? :-)

As a workaround, I wonder what would happend if I removed the `node-role.kubernetes.io/master` label.

The error message is:

```
I0628 17:54:48.853175       1 event.go:221] Event(v1.ObjectReference{Kind:"Service", Namespace:"default", Name:"nginx", UID:"59980933-7afc-11e8-9a8c-0621b993d602", APIVersion:"v1", ResourceVersion:"2052", FieldPath:""}): type: 'Warning' reason: 'UnAvailableLoadBalancer' There are no available nodes for LoadBalancer service default/nginx
```

**Comment by smarterclayton** [comment]
I'm not sure this is correct as we run more things on the master.  If I have a service that I want to expose like an API proxy, an aggregated API server that wants its own LB, or a not quite control plane but not quite end user workload.  We shouldn't *bias* towards the master (I.e. a lot of node port services for regular workloads should bypass the master), but this PR as it stands prevents using service load balancers with services that run on masters, which limits options like self hosting and use.

Now that node load balancing is more nuanced (with health checking endpoints), do we even need this?  Masters should not be marked as healthy when pods aren't run on them, which means no traffic would go to masters?
