### ISSUE TITLE
discuss kubeadm reset and/or kubeadm init --reset

### ISSUE THREAD

**Issue by errordeveloper** [kubernetes/kubernetes#33931]
We quite likely need to provide a reset command that cleans up files, and perhaps stops kubelet and containers it started, remove etcd's data other pieces of state.

**Comment by guybrush** [comment]
In this context i think it is important to also think about how *resetting* works for every installed cluster-addon, e.g. storage and especially cni-addons (clean up the ip-routes).

**Comment by luxas** [comment]
I think we should go for `kubeadm reset` as it isn't specific to `init`; it cleans up from join as well.

Opened #34044 for that along with a bash script that describes what to be done.
Sorry, but closing this in favor for #34044 which is more specific in order to minimize dupes, hope you don't mind :)
