### ISSUE TITLE
Re-enable "Feature" e2e tests to avoid regressions like Gluster not working on GCI

### ISSUE THREAD

**Issue by quinton-hoole** [kubernetes/kubernetes#33960]
Gluster volumes don't work on GCI (issue?), which is an unintended regression in v1.4.

We _do_ have a [working e2e test for gluster](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/volumes.go#L402) that should have picked up that regression, but it has been (i.m.o. incorrectly) [disabled](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/volumes.go#L349) as a ["Feature"](https://github.com/kubernetes/test-infra/blob/d6258a0d9b0f85d4a1cd01886ad485f116baeeb8/jenkins/job-configs/kubernetes-jenkins/kubernetes-e2e-gce.yaml#L73) in all of our CI tests (as far as I can tell).

In general I think that all e2e tests that can be run reliably and automatically should be run regularly to detect these sorts of regressions.

@kubernetes/sig-testing @kubernetes/sig-storage @saad-ali @thockin @matchstick fyi

**Comment by jsafrane** [comment]
I am in favor of enabling the tests, however they were disabled exactly because GCE test platforms did not have necessary binaries. In this case, GCI needs `/usr/sbin/mount.gluster`. On Fedora, it's `glusterfs-fuse` package.

And all the other volume tests need similar utilities - `/usr/bin/rbd`,  `mount.ceph`, `iscsiadm` and such.

**Comment by spiffxp** [comment]
/close
I don't foresee this getting done anytime soon.  @kubernetes/sig-storage-bugs please /reopen if you disagree and are interested in taking this on
