### ISSUE TITLE
CRI: Ensure that container runtime runs in a known cgroup

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#33980]
Currently, it's kubelet's responsibility to [move the docker daemon (and associated processes)](https://github.com/kubernetes/kubernetes/blob/v1.4.0/pkg/kubelet/cm/container_manager_linux.go#L328) to a cgroup. With CRI, such actions would require knowledge about the runtime that's beyond what the API currently provides. One option is to ask runtime to return a list of PIDs which kubelet can manage (i.e., move to a cgroup and apply oom scores). Another option is to exclude this from CRI, and instead, define it in the NodeSpec. We can then leverage the NodeSpec validation test to make sure a node is qualified to run kubelet. I am leaning towards the second option because it frees kubelet from the details of how this is achieved, and one can either configure the node properly, or modify the shim to take on the responsibility.

/cc @kubernetes/sig-node

**Comment by dchen1107** [comment]
In one of our sig-node meetings, @derekwaynecarr and I touched this very topic a little bit when we discussed NodeSpec and Node conformance tests. The top level cgroup / resource provisioning should be defined at NodeSpec, and system_config_validation_test in Node Conformance Test should check this, and throw the error / warning if the config doesn't meet the specification. 

Then the issue is how we achieve this for different runtimes. @yujuhong and I briefly discussed this earlier and I am leaning towards her opinion too.

**Comment by yifan-gu** [comment]
cc @kubernetes/sig-rktnetes

**Comment by yujuhong** [comment]
@derekwaynecarr @vishh @yifan-gu @euank @feiskyer thoughts? 

I'd like to move the relevant code down to the docker packages if we decide to go with the second option.

**Comment by derekwaynecarr** [comment]
I am in agreement to move it into the docker packages, but would prefer we
don't grow an opinion on the cgroup location that changes precedent when on
systemd in 1.5.

**Comment by yujuhong** [comment]
> I am in agreement to move it into the docker packages, but would prefer we
> don't grow an opinion on the cgroup location that changes precedent when on
> systemd in 1.5.

Sure. I think the cgroup location should be discussed carefully along with the rest of the NodeSpec.

**Comment by yifan-gu** [comment]
+1 On the second option, and moving the current code to docker package.

**Comment by feiskyer** [comment]
Is it possible for container runtime to get top level cgroup from NodeSpec?

**Comment by yujuhong** [comment]
#34490 is merged. Closing.
