### ISSUE TITLE
add some pre-flight checks to kubeadm init and join

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubernetes#34046]
from the top of my head:
 - check for free ports: 8080, (6)443, 2379, 10250, 10251, 10252, ...
 - check if docker is running (yes, this is one of the most common failures)
 - check if systemctl is present and if kubelet is crashlooping
 - check that `/etc/kubernetes`, `/var/lib/etcd`, `/var/lib/kubelet` is empty
 - check for root and warn that it might fail
 - check for kubelet dependencies in PATH
 - allow the user to opt-out of the checks via a flag

@kubernetes/sig-cluster-lifecycle

**Comment by Random-Liu** [comment]
This looks a little similar with https://github.com/kubernetes/kubernetes/issues/28408.

**Comment by lukemarsden** [comment]
This sounds great. Any volunteers to get started? :)

**Comment by dgoodwin** [comment]
I can get the ball rolling with the kubelet and docker systemctl service check.

**Comment by mikedanese** [comment]
Which of these aren't covered by kubelet verify? kubeadm verify should not fail after kubeadm init is run. Some of these checks look like that would be the case.

**Comment by mikedanese** [comment]
Oops got this mixed up with https://github.com/kubernetes/kubernetes/issues/33962. Why is this different?

**Comment by pires** [comment]
@mikedanese i believe this is mostly prior to have `kubelet` running, e.g. checking if a port is available for API server or that we're running as root.

**Comment by dgoodwin** [comment]
In my mind the difference was pre-flight kubeadm vs post-install e2e and conformance. However looking through what's there, it does appear to be pretty similar and intended to run *before* e2e tests, and doesn't seem to currently do anything we wouldn't want. Tricky as our needs are going to deviate but there might be enough overlap to find something that will work here. I will see if I can meld them together.

**Comment by Random-Liu** [comment]
IIUC, there are several levels of validation:

1. kubeadm pre-flight check (this issue): Some basic check to make sure `kubeadm` itself can work properly, e.g. whether all dependencies are installed.
2. system validation (kubeadm/kubelet verify, #28408, #32427): Check whether the system meets the minimum requirement of a Kube-node, e.g. kernel configuration, runtime configuration, cgroup hierarchy etc. (Related to NodeSpec @dchen1107)
3. node conformance test (a separate tool, currently packaged as a container #30122): Run a subset of node e2e test to validate the basic functionality of the node.

I'm not sure whether these 3 should all be run before `kubeadm init/join` or not. But at least a new bare-metal node or cloud node image should run and pass all these three checks at some time.

**Comment by dgoodwin** [comment]
As it stands now with the kubelet verify PR #28408 there's not a whole lot of overlap, I don't think that suite would want many of the checks we do, however I don't see any reason we wouldn't run the checks they have there.

We could try to use their framework, it's not quite what I would want but I can leave a review if folks think we should go this path. I'd like a little more nuance and the ability to return both errors and warnings, we *might* want to actually take action in our checks as well. (i.e. enable the systemd service if it's not rather than just warn). We definitely have opinionated checks that don't fit with the node e2e tests so we would have to be able to pick and choose suites of checks to run, but this would be possible with the current code in that PR.

However the amount of plumbing is light in both cases, there's very little risk of causing trouble by changing this later, I'd be tempted to just carry on separately and we can re-examine merging the two sometime in future. 

What do others think?

**Comment by dchen1107** [comment]
In one of our internal meeting a while back, I proposed several things: 

1. 
Instead of assuming all kubernetes node pre-installed docker daemon, then download kubelet (as docker image or tar file, etc.), why not putting Kubelet or another kube controlled binary into linux package manager, like APT. The responsibility of that binary is resolving all the dependencies (Kubelet, runtime, iptable, cni plugin, etc.) to get the node prepare to run as KNode (I call all kubernetes node as KNode). Sig-node team validates each docker releases, and in the future, each runtime vendor will validate their runtime release, and publish the conformance test result. Eventually together with other validation / test results, the Kubernetes release engineer can easily figure out the dependencies between required daemons (not master components, not daemon set daemons) on the node for each release, and packaging them through linux standard package manager. **This is how / where kubeadm started originally**, currently as part of kubeadm pre-flight (didn't check the latest kubeadm's status).
1. 
Kubelet CLI can provide **init** option to initialize the node by starting the required daemons, like docker, kubelet, etc. 
  - Part of work is running system_validate_tests to check. The validation can be extended to run the entire node conformance tests and publish the result. This is #28408. And this piece of work (--verify) has huge dependency on @Random-Liu's NodeConformanceTest work. I didn't realize that Kubeadm decides to take over this too. This is better since it won't put Kubelet itself monolithic. And kubeadm can easily reuse NodeConformanceTest work to accomplish the work here. 
1. 
If the node is the master node, kubeadm should resolve the rest dependencies for running as Kubernetes master, then hand over to Kubelet to start the master component pods.
1. 
Today Kubelet can auto-join the cluster already once the admin points it through flags to the right apiserver with the right credential, keys, etc. I suggested to provide a **join** option to make this step explicit. I think it makes sense to let kubeadm take over this by pulling proper daemons configs from whatever configure store, and reconfigure Kubelet to join a cluster. But Kubelet still needs to get PodCIDR information from the master to really join the cluster. cc/ @freehan on runtime interface

cc/ @aronchick @matchstick @kubernetes/sig-node

**Comment by pires** [comment]
Overall, it's an interesting proposal, @dchen1107!

> Instead of assuming all kubernetes node pre-installed docker daemon, then download kubelet (as docker image or tar file, etc.), why not putting Kubelet or another kube controlled binary (...)

Did you mean _why not putting kubeadm_?

**Comment by dchen1107** [comment]
> Did you mean why not putting kubeadm?
Yes, that is what I mean. But when I proposed this at the internal meeting, there is no kubeadm yet. Kubeadm project is created right after that. :-)

**Comment by dgoodwin** [comment]
Spoke with @luxas on slack, I think we're going to proceed with kubeadm pre-flight checks separately from kubelet verify and the e2e/conformance pre-test. Our desired checks are not useful there (much too opinionated), we need speed, the frameworks have slightly different needs and yet both are quite small.

**Comment by luxas** [comment]
This is now fixed with #34341

**Comment by RupakRath** [comment]
kubeadm join 10.0.0.46:6443 --token v86r90.a9wqmkf2f1goq76m --discovery-token-ca-cert-hash sha256:7ecc7acf44910f118cf5abc1529537badc2a03863063a2b0a9b82fa059120e77
[preflight] Running pre-flight checks
        [WARNING IsDockerSystemdCheck]: detected "cgroupfs" as the Docker cgroup driver. The recommended driver is "systemd". Please follow the guide at https://kubernetes.io/docs/setup/cri/

stucked here please help me   what to do   how to do  and where to do means on which machine   master or worker i have change????
