### ISSUE TITLE
cluster/addons/fluentd-elasticsearch/kibana-image is stale

### ISSUE THREAD

**Issue by colemickens** [kubernetes/kubernetes#34079]
This: https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/fluentd-elasticsearch/kibana-image installs version 4.0.2 of Kibana. Something like 4.6 (current stable) might be more appropriate.

**Comment by colemickens** [comment]
In fact, I'm not sure why it needs to be a custom container instead of using the default library image with a custom command to do the things in `run.sh`.

**Comment by Crassirostris** [comment]
I'm going to update ES version soon, as well as kibana's, because they're quite tied together. Related issue: #19149

And while solving the related issue, I will figure out if it's possible to use official es/kibana images instead of custom.

Feel free to close this issue, if related one covers what you mentioned.

**Comment by colemickens** [comment]
Thanks!
