### ISSUE TITLE
Set up testing environments for kubeadm

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubernetes#34136]
First we should make small integration tests that are spinning up a two-node cluster (maybe in containers) and verifying that the cluster comes up and basic functionality works

Then full-featured e2e testing that runs the e2e conformance suite on a kubeadm-created cluster should follow as a presubmit check so we can be sure that we're not breaking things when submitting PRs

Hopefully we're doing this in containers, @errordeveloper and @marun were experimenting with that.

Anything else we need for testing kubeadm?

cc @kubernetes/sig-cluster-lifecycle @kubernetes/sig-testing

**Comment by errordeveloper** [comment]
I've started doing some work on integration tests, using Docker-in-Docker and systemd (of course). It's sort of very experimental and exploratory, e.g. I used Drone and not Jenkins, and I am still to look at test-infra repo and see how well it suites our needs, I have some doubts if there much that can be reused for deb/rpm+systemd integration test in particular.

See these repos (sorry, no docs yet):
- https://github.com/errordeveloper/kubeadm-ci-dind
- https://github.com/errordeveloper/kubeadm-ci-packager
- https://github.com/errordeveloper/kubeadm-ci-tester

I'll continue playing with this, unless someone thinks it's a really bad idea... Let's discuss in more details on Slack, I just thought I can start something unless anyone else commits to it. It's not ready to show and it's a 65% functional PoC, but I just want to make sure folks know that I'm working on something in this are, and I also would really appreciate any help!

**Comment by ivan4th** [comment]
See also https://groups.google.com/d/msg/kubernetes-sig-cluster-lifecycle/nb-To3C8eZ8/_5o2hs6SFAAJ
I've made a version of [kubernetes-dind-cluster](https://github.com/ivan4th/kubernetes-dind-cluster/tree/kubeadm) ([original version](https://github.com/sttts/kubernetes-dind-cluster) by @sttts) that is capable of starting kubeadm cluster based on locally-built binaries for kubeadm, kubelet, kubectl & hyperkube. I'll add support for this to my [k8s-devbox](https://github.com/Mirantis/k8s-devbox) project soon. The devbox has some tests already and I'll add some tests that bring up cluster with kubeadm and run conformance tests against it (runnable on GCE).
Proper DIND support requires this PR: #34522 

This being said, I think @errordeveloper's `kubeadm-ci-*` is necessary, too, because my implementation doesn't do any packaging.

Also, thanks to @marun for his [dkr-systemd-dind](https://github.com/marun/dkr-systemd-dind) project.

**Comment by roberthbailey** [comment]
It would be great if we could get e2es running in our existing test-infra using kubeadm.

**Comment by mikedanese** [comment]
I'd like to do this by adapting kubernetes-anywhere to use kubeadm instead of iginition and write bindings for kubernetes-anywhere using  @zmerlynn 's new hack/e2e.go features.

**Comment by dims** [comment]
This needs to be triaged as a release-blocker or not for 1.5 @luxas @pires @mikedanese

**Comment by mikedanese** [comment]
@dims This is very close to done. This won't be a release blocker. I'm ok with moving this out of the milestone even though it will likely be done by the release. Last release didn't we have a v1.4-nonblocking milestone?

**Comment by luxas** [comment]
@mikedanese Have you set up a jenkins ci?

**Comment by dims** [comment]
@mikedanese : nice! let's ask Saad. @saad-ali : we need a v1.5-nonblocking milestone this time?

**Comment by mikedanese** [comment]
Ok, @saad-ali Informed me that I should leave in v1.5 but add non-release blocker.

@luxas, very soon we will. One more PR left.

**Comment by dims** [comment]
@mikedanese sounds good to me.

**Comment by dims** [comment]
@luxas @pipejakob Is it appropriate to move this to the next milestone or clear the 1.5 milestone? (and remove the non-release-blocker tag as well)

**Comment by luxas** [comment]
@mikedanese Actually we can move this issue to kubernetes/kubeadm

**Comment by luxas** [comment]
@pipejakob @mikedanese I think this issue can be closed now given that we have the kubeadm e2e Prow job running?

Also @ivan4th has the kubeadm DIND project that can be used for this purpose easily by devs.
