### ISSUE TITLE
Adopt Kubelet Dynamic Settings in order to be able to change values like --cluster-dns, --cloud-provider based on arguments given to kubeadm

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubernetes#34132]
We should use Kubelet Dynamic Settings by pushing values given to `kubeadm init` to the apiserver when started, and that will make all kubelets in the cluster reload and pick up those configuration values.

That's much better than having to modify every `10-kubeadm.conf` systemd dropin file in the whole cluster.

**Comment by luxas** [comment]
cc @kubernetes/sig-cluster-lifecycle

**Comment by errordeveloper** [comment]
Is this feature already usable?

**Comment by luxas** [comment]
I don't know actually, but I think an alpha version of it exists

cc @mtaufen @vishh @mikedanese @dchen1107 @yujuhong

**Comment by axsuul** [comment]
Is this related to customizing arguments for the kubernetes API server? I'm trying to customize the secure port it listens on (`--secure-port=8081`) but I'm not sure how to do it when setting up the cluster with `kubeadm`.

**Comment by errordeveloper** [comment]
James, no this is not related. To your question, please try editing
/etc/kubernetes/manifests/kube-apiserver.json, but please create another
issue if you have more questions.

**Comment by axsuul** [comment]
@errordeveloper Thanks, I've opened up issue #34307 with more questions

**Comment by mtaufen** [comment]
There is an alpha version of the dynamic settings feature, but it still needs a lot of work. I'm going to be mostly focused on GCI-related things for v1.5, but am planning be giving it high-priority focus for v1.6. I wouldn't recommend building on top of dynamic settings just yet, as it will undergo some significant changes (e.g. we will move to telling a node which configmap to use via annotations rather than creating configmaps with a per-node naming convention). 

As it stands you would have to create a configmap for every node in the cluster anyway, and based on @luxas's first comment in this issue, it looks like you are trying to avoid per-node work, so that might be another reason to wait. Granted, this per-node work is still probably less effort than modifying systemd conf across a cluster...

**Comment by mikedanese** [comment]
This issue was moved to kubernetes/kubeadm#28
