### ISSUE TITLE
Why are heapster and grafana at different versions in the monitoring addon?

### ISSUE THREAD

**Issue by colemickens** [kubernetes/kubernetes#34216]
Reference 1: The current influxdb-grafana-controller: https://github.com/kubernetes/kubernetes/blob/42e5f95a6b41877a56f909e06aef912f63948eaa/cluster/addons/cluster-monitoring/influxdb/influxdb-grafana-controller.yaml

Reference 2: The Makefile for heapster, which looks like it builds the containers referenced in the influxdb-grafana-controller: https://github.com/kubernetes/heapster/blob/6b5b26f0d9d81960608319ab712db9c6bb225293/Makefile

They seem to both use `$(TAG)` to label the built image, so I'm confused as to why the `influxdb-grafana-controller` has:
* gcr.io/google_containers/heapster_influxdb:v0.7
* gcr.io/google_containers/heapster_grafana:v2.6.0-2

Are these up to date or old like the logging addon containers?

**Comment by colemickens** [comment]
Even more confusing, the TAG in `heapster` Makefile is currently `1.2.0` which is confusing since heapster_grafana is at a higher tag version...

This is kind of confusing. All I wanted to do was figure out what version of influxdb is running to check API compatibility with Kapacitor.

**Comment by brendandburns** [comment]
@vishh can you comment on heapster/influx/grafana versioning?

**Comment by piosz** [comment]
Sorry for the confusion.

The current InfluxDB version is 0.12.

We build Grafana using this Makefile https://github.com/kubernetes/heapster/blob/master/grafana/Makefile
And the version should match the Grafana version itself.

[Here](https://github.com/kubernetes/heapster/blob/master/influxdb/RELEASES.md) you have InfluxDB release. The versioning started from 0.1 and is increasing any time the release is made. The plan is to have the same approach as for Grafana - the version should match the version of InfluxDB included.

Heapster was released in version 1.0 in Kubernetes 1.2 and since then we've been bump minor release for every Kubernetes release.
