### ISSUE TITLE
kubelet is not populating the "MemoryReservation" field in Docker container

### ISSUE THREAD

**Issue by huang195** [kubernetes/kubernetes#34244]
I would expect: `--request='memory=xxx'` would map to Docker container's `MemoryReservation` field, as currently `--limits='memory=xxx'` maps to Docker container's `Memory` field.

In a project I'm working on, we're making these in sync. I'm wondering if there's any interest (or problem) for us to upstream this small change.

(Looking at rkt driver code, it seems to be using both memory request and limit information already.)

**Comment by huang195** [comment]
cc @vishh @yujuhong

**Comment by euank** [comment]
@huang195 I believe requests/limits for memory are just used to set the maximum limit and to handle QoS (e.g. set oom_score_adj). It's possible that that's because docker didn't have that feature when this was originally implemented, but 

If `request` were to have more meaning, I would think that it should be applied at the pod cgroup level rather than by the runtime (via the `memory.soft_limit_in_bytes` tunable).

I'm not sure if there's a particular reason `soft_limit_in_bytes` isn't used, cc @vishh.

cc @kubernetes/sig-node

**Comment by euank** [comment]
Potentially related: #12422

**Comment by vishh** [comment]
Memory Soft limits are practically useless for Kubernetes purposes.

**Comment by huang195** [comment]
@euank thank for that information. I'm wondering now that Docker has this feature, whether or not it's worth the time to keep this info synced between the 2 systems.

@vishh yep, understood it's currently not used, but I'm wondering if there's some merit to keeping information sync'ed between K8s and its container runtimes.
