### ISSUE TITLE
Mark pods as failed if there are no ips available

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#34283]
If the network plugin reports no available ips, we should at least send an event, and preferably mark pods as Failed so the RC can recreate them elsewhere. We can't mark the nodes as NotReady because pods are running, but we can cordon it to ensure new pods land elsewhere.

**Comment by nhlfr** [comment]
I'm working on this.

**Comment by xiangpengzhao** [comment]
@nhlfr Michal's PR was closed due to inactive in 90 days. And that PR was a fix for DockerManager which had been removed.

In the current dockershim code, if there is an error from [getIPFromPlugin](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockershim/docker_sandbox.go#L284-L285), the error is only logged instead of being returned. I wonder if network plugins can report such a "no available ips" error and we can identify it specially.

@Random-Liu @yujuhong @thockin

**Comment by cmluciano** [comment]
Can this PR be resubmitted to conform to the dockershim layout? It looks like the PR was against the removed dockertool path.
