### ISSUE TITLE
[FEATURE REQUEST] Default resource request documentation 

### ISSUE THREAD

**Issue by andrewmclagan** [kubernetes/kubernetes#34401]
We are having trouble understanding Kubernetes resource requests.

We run a cluster of 3x 1CPU / 3.75Gb

Our issue is this: We are allocating really small CPU requests to each container in our pods so the pod will be scheduled onto a node. Our containers are basically all web containers running NodeJS or PHP so their CPU is pretty low and occasionally bursts.

I personally just don't see the point in having to declaratively allocate stupidly low CPU requests to each container in our deployments when we know in advanced they will use much more CPU then this request but never exhaust the node as a whole. Its just not a concern although Kubernetes seems to force us into this thinking.

In the beginning we were not allocating any requests at all, although we ran into problems as Kubernetes allocated defaults. These defaults were exceeded when updating our deployments and a rolling update tried to allocate pods to a node with insufficient resources...

**Why does Kubernetes not have default resource allocation of 0 so users can simply ignore these scheduling rules?**

**Comment by mikekap** [comment]
By default I don't believe kubernetes automatically sets resources/limits if you don't provide them. (Or the first line of http://kubernetes.io/docs/admin/limitrange/ is wrong). This can happen in a non-default configuration if you enable the [InitialResources admission controller](http://kubernetes.io/docs/admin/admission-controllers/#initialresources-experimental). Do you have that enabled on your cluster? Also could you let us know how you set up the cluster? (i.e. was it kube-up, kops, or something else entirely?)

**Comment by andrewmclagan** [comment]
okay, you are correct I really don't know how we missed this..!

**Comment by andrewmclagan** [comment]
Re-opening this as it seems Kubernetes really does have undocumented default resource allocations:

Our `deployment.yml` has absolutely no resource requests or limits and when describing the nodes in our cluster its clear that Kubernetes is allocating `100m` per container within each pod.

This then causes scheduling errors when we do a rolling update of our deployment:

`kuebctl apply -f deployment.yml`

**These default resource requests are undocumented, is there anyway to set them to 0?**

**Comment by mikekap** [comment]
I think there's a slight gotcha with apply if you didn't create the deployment with apply in the first place. It sounds very similar to something like #25390 .

Try using kubectl replace or removing the resources with kubectl edit, or just deleting the deployment and recreating it. You should see the CPU requests disappear from the config.

**Comment by andrewmclagan** [comment]
Is there anyway to get around resource limits when undergoing an update? It just seems very counter intuitive that resource limits apply to new pods being scheduled and removed. Having to take this into account we are assigning unrealistic resource requests to pods just to get around this "surge" issue

**Comment by mikekap** [comment]
You can disable the surge behavior in deployments where it will instead take down an instance from the old set before bringing a new one up. That just involves setting maxsurge to 0. Is that what you're looking for? Otherwise if you remove cpu requests/limits kubernetes schedules pods with an assumption that they use 0 cpu.

Separately I would suggest moving this question to stackoverflow or the kubernetes slack. I don't think there's an actual bug here. You're more likely to get prompt (and more correct than my rambling) support there.

**Comment by andrewmclagan** [comment]
haha, thank you for your support its very much appreciated. Stackoverflow and Kubernetes questions are usually quiet. I actually already posted this question there, someone told me it wont get answered and to post it on the issues board.

I have finally worked out the issue, new Kubernetes clusters on GKE create a default resource `limits` type of `100m` for every container in a pod. There are no docs describing the fact this default is created:

````
ethicaljobs.com.au in ~/development/ethical-jobs/ethical-jobs-api on staging*
>> kubectl get limits
NAME      AGE
limits    23h
ethicaljobs.com.au in ~/development/ethical-jobs/ethical-jobs-api on staging*
>> kubectl describe limits
Name:		limits
Namespace:	default
Type		Resource	Min	Max	Default Request	Default Limit	Max Limit/Request Ratio
----		--------	---	---	---------------	-------------	-----------------------
Container	cpu		-	-	100m		-		-
ethicaljobs.com.au in ~/development/ethical-jobs/ethical-jobs-api on staging*
>>
````

**Comment by javiercr** [comment]
I had the same problem. [Kubernetes docs](http://kubernetes.io/docs/admin/limitrange/) say: 
> By default, pods run with unbounded CPU and memory limits

Which seems to not be true at least in GKE clusters with v1.4.0

**Comment by bgrant0607** [comment]
http://kubernetes.io/docs/admin/limitrange/

**Comment by andrewmclagan** [comment]
"By default, pods run with unbounded CPU and memory limits."

In GKE that is incorrect.

@bgrant0607

**Comment by miracle2k** [comment]
I had changed the default limitrange on GKE, but it seems that after a cluster upgrade, it was reset to the default.

**Comment by bgrant0607** [comment]
cc @fabioy @devin-donnelly

**Comment by hut8** [comment]
I just encountered the same problem as @miracle2k .

There's a huge difference here between the "request" and the "limit", which are both confusingly returned by this command:

```
% kubectl describe limits                                                                                                                                      [2017-06-17 14:48:37]
Name:           limits
Namespace:      default
Type            Resource        Min     Max     Default Request Default Limit   Max Limit/Request Ratio
----            --------        ---     ---     --------------- -------------   -----------------------
Container       cpu             -       -       100m             -               -
```

@javiercr  @andrewmclagan, you state that `"By default, pods run with unbounded CPU and memory limits."`, which I think is in fact true (I'm on GKE). According to the above command, there are no *limits* here for CPU or memory resources. In other words, if I'm able to schedule a pod on a node, then it can use any amount of memory and CPU. However, there is a default *request*. This is why I was so confused initially about this; there *is* a default request of 100m CPU per container. That means that I can only have ten containers running per node, which is a disaster, because if I'm using, e.g., `cloud_sql_proxy` on GKE plus my app in one pod, that's 200m CPU per pod. Plus there are resource requests from the kube-system namespace and my ingress controller, so once I have one deployment up with two replicas, my 1-CPU node is full, even though the processor is practically idle.

I really wish that *actual limits* and *resource requests* were not both lumped under the word "limits."

**Comment by jingxu97** [comment]
cc @fabioy 
It seems like we still don't have document for this default setting?

**Comment by andrewmclagan** [comment]
Is this GCE specific?

**Comment by jingxu97** [comment]
@kubernetes/sig-docs-maintainers I think we still need to fix this issue.

**Comment by steveperry-53** [comment]
Adding @ryanmcginnis who works on the GKE docs.

Unless I'm missing something, this is all about default requests and limits set by GKE. Correct me if I'm wrong, but I don't think Kubernetes itself has default request and limits. So any doc that explains this belongs in the [GKE docs](https://cloud.google.com/kubernetes-engine/docs/), not the [Kubernetes docs](https://kubernetes.io/).

**Comment by ahmetb** [comment]
Sounds about right. I saw different limits on different platforms, or even the different versions of GKE. it would be good to confirm first however.

**Comment by njam** [comment]
Is it possible to *change* this GKE default persistently?

I can do `kubectl delete LimitRange limits`, but when I create new GKE nodes or upgrade existing ones the limit comes back.

**Comment by ahmetb** [comment]
@njam I doubt that. I'll ask around internally.

**Comment by pcj** [comment]
Any update on this being documented?  I arrived here after several hours of researching this issue.

```
$ kubectl describe ns default 
Name:         default
Labels:       <none>
Annotations:  <none>
Status:       Active

No resource quota.

Resource Limits
 Type       Resource  Min  Max  Default Request  Default Limit  Max Limit/Request Ratio
 ----       --------  ---  ---  ---------------  -------------  -----------------------
 Container  cpu       -    -    100m             -              -
```

**Comment by ahmetb** [comment]
@pcj This default LimitRange is not documented and is a pretty historical artifact (was added around 2015). It also doesn't exist on namespaces other than `default` namespace.

**Comment by kierenj** [comment]
Just stumbled across this, it still feels important to me.. ?

**Comment by JCMais** [comment]
It's still important and not documented anywhere else. Changing the default one does not work, because gke seems to reset it after some time.

What I recommend is to explicitly set the limit on the pod/deployment spec to `0` or to another, more correct, value (recommended).

`100m` was too big for one of our dev clusters, so I've updated our CI to set it to `40m` for every dev pod.
