### ISSUE TITLE
there should be a way to leave cluster in kubeadm

### ISSUE THREAD

**Issue by bruceauyeung** [kubernetes/kubernetes#34404]
currently `kubeadm` command provides a command `join` to join a cluster. but there isn't a command to leave that cluster. maybe `kubeadm leave` is suitable for this circumstance

kubeadm version

> version.Info{Major:"1", Minor:"5+", GitVersion:"v1.5.0-alpha.0.1534+cf7301f16c0363-dirty", GitCommit:"cf7301f16c036363c4fdcb5d4d0c867720214598", GitTreeState:"dirty", BuildDate:"2016-09-27T18:10:39Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}

**Comment by errordeveloper** [comment]
This makes sense to add. Are you envisioning re-joining another cluster or simplify clean-up and recycle nodes? Right now you can just throw away a node and run `kubectl delete node <name>`.

**Comment by pires** [comment]
@luxas please assign this to me.

**Comment by pires** [comment]
I'll add this behavior after #34807 lands, such that both
`kubeadm reset` and `kubeadm leave` result in the node been marked as unschedulable to the cluster.

Thoughts @luxas @errordeveloper?

**Comment by pires** [comment]
This is a list of potential execution steps:
* Mark current node as **unshedulable** _aka_ cordon the node
* [Drain the node](http://kubernetes.io/docs/user-guide/kubectl/kubectl_drain/)
* Restart the `kubelet` with empty or default values, e.g. crash-loop until an API server is provided

1 - Existing `kubectl` code living in `pkg/kubectl/cmd/drain.go` should be either re-used or adapted.
2 - `kubeadm reset` should execute similarly, differing only in the last step where instead of restarting, it should stop the `kubelet`.

Thoughts?

**Comment by mikedanese** [comment]
This issue was moved to kubernetes/kubeadm#42
