### ISSUE TITLE
move service ClusterIP/NodePort allocation logic to a controller?

### ISSUE THREAD

**Issue by mqliang** [kubernetes/kubernetes#34417]
Is there any particular reason for putting service ClusterIP and NodePort allocation logic into API server, instead of controller? 

AFAIK, allocating in API server is racy when we have multiple API server, unless we write allocation status into etcd. Currently, we have a repair controller in API server which periodically examines all service ClusterIP/NodePort allocations and handle duplicate ClusterIP/NodePort assignments, which is not elegant. 

So I propose to put ClusterIP/NodePort allocation logic into controller-manager component(maybe in service-controller). Adding several dedicated allocation-controllers also sounds interesting:

* add a controller to allocate ClusterIP/NodePort for Service
* add a controller to allocate PodCIDR for Node(which is putting in node-controller currently)

Considering that we have shareInformer now, seems reasonable to split all unrelated logic?

@smarterclayton @davidopp @gmarek @derekwaynecarr

**Comment by davidopp** [comment]
@fgrzadkowski since replicated API server is related to HA

**Comment by AdoHe** [comment]
```
unless we write allocation status into etcd
```
we definitely write status into etcd, use bitmap to store it.

**Comment by smarterclayton** [comment]
When we last discussed this we could not come up with a way to make a
change to move allocation to a controller while preserving backwards
compatibility and not being a very complex change.

The initializers concept is as close as we've come and the changes required
there are also very expensive a

On Oct 9, 2016, at 6:18 PM, TonyAdo <notifications@github.com> wrote:

unless we write allocation status into etcd

we definitely write status into etcd, use bitmap to store it.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/34417#issuecomment-252522987>,
or mute the thread

**Comment by smarterclayton** [comment]
Allocation is HA - we've tested it extensively replicated API servers since
Kube 1.1 (openshift HA is multi API server) and I'm not aware of any fixes
post 1.1.  We did handle add retry loops for when startup conflicts piled
up (the repair core controller can race against the other API server to
update the allocation bitmap, which can lead to lots of write conflicts).

On Oct 9, 2016, at 6:18 PM, TonyAdo <notifications@github.com> wrote:

unless we write allocation status into etcd

we definitely write status into etcd, use bitmap to store it.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/34417#issuecomment-252522987>,
or mute the thread

**Comment by gmarek** [comment]
PodCIDR allocation is currently kind-of separate from NodeController. They do sit in a single "Controller", which would make it harder to re-implement only one of them, but that's the only problem there is now (codebase is separate and the intersect only on listening to Node changes - it'll be trivial to separate them completely, but I didn't have any reason to do so).

If you want to do the split, I'm completely OK with it.
