### ISSUE TITLE
Deployment controller only works because of 30 second resync

### ISSUE THREAD

**Issue by deads2k** [kubernetes/kubernetes#34458]
There's a deployment test called `"overlapping deployment should not fight with each other"` with a part called `"Waiting for the second deployment to clear overlapping annotation"` that only passes because of a tight resync period.  The test indicates that the secondary deployment would not become active when the first one was deleted until the resync happens, so the controller doesn't work well without a tight resync.

@kargakis can you find the right home for this?

**Comment by kargakis** [comment]
Thanks for digging this out. This issue is easily fixed by reconciling all overlapping deployments every time we have an event for one. 

Unfortunately, we have a bigger issue that needs a tight sync interval and that is [ProgressDeadlineSeconds](https://github.com/kubernetes/kubernetes/pull/19343). Imagine a deployment with a deadline of 10m and the last time it syncs due to an event is during the first 1m. Then it gets stuck forever without producing any new event and we will need to resync it around the tenth minute (only way is to rely on relist?) in order to report lack of progress. Do you have any ideas on this? 

cc: @bgrant0607 @smarterclayton @kubernetes/deployment

**Comment by deads2k** [comment]
> Then it gets stuck forever without producing any new event and we will need to resync it around the tenth minute (only way is to rely on relist?

You know this is going to happen, just set it up to queue later.  `workqueue.AddAfter(key, 10*time.Minutes)` and that one item will re-enter your queue.

**Comment by kargakis** [comment]
> You know this is going to happen, just set it up to queue later. workqueue.AddAfter(key, 10*time.Minutes) and that one item will re-enter your queue.

Awesome

**Comment by bgrant0607** [comment]
cc @kubernetes/deployment

**Comment by kargakis** [comment]
https://github.com/kubernetes/kubernetes/pull/36648 fixes Deployments that use ProgressDeadlineSeconds
https://github.com/kubernetes/kubernetes/pull/38080 fixes overlapping Deployments
