### ISSUE TITLE
Deployment  create/delete issue with same selector

### ISSUE THREAD

**Issue by jingxu97** [kubernetes/kubernetes#34466]
When I tested with deployment, found some issue. The steps to reproduce is 

1.  Create a deployment with the example online http://kubernetes.io/docs/user-guide/deployments/#what-is-a-deployment
1. Edit the deployment yaml file, just change the name of the deployment, and create a second one.

After creating, check the deployment status. The first one is running correctly. The second one returned the error
SelectorOverlap	found deployment default/nginx-deployment2 has overlapping selector with an older deployment default/nginx-deployment, skip syncing it
Deployment status
NAME                DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
nginx-deployment    3         3         3            3           3m
nginx-deployment2   3         0         0            0           2m

Although I didn't specify a selector in the yaml file, looks like it assigned a selector using the label name (both deployments use the same label name)

1. Delete the deployments, both returns with error
error: error when stopping "deployment.yaml": timed out waiting for the condition
Check the status

NAME                DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
nginx-deployment    0         3         3            3           48m
nginx-deployment2   0         0         0            0           47m

Note the objects still exist. For the first deployment, the desired is changed to 0, but current is still 3?! (I also checked the pods, no pod is running for deployment).

**Comment by jingxu97** [comment]
@janetkuo , do you have some time to help take a look?

**Comment by AdoHe** [comment]
@jingxu97 

1. if you have not specify any selector, then the default selector will bd derived from `spec.Template.Labels`
2. If two deployments have the same selector, we will not sync the latter one, IIRC @janetkuo add this, https://github.com/kubernetes/kubernetes/pull/30730, ptal
3. For the deletion failure, seems like a bug

**Comment by pwittrock** [comment]
1 & 2 working as intended.  There is also an annotation applied that lists what the overlapping issue is.

**Comment by jingxu97** [comment]
The issue is when deleting the deployment, it returns with error  timed out waiting for the condition. And when checking the status, the api object is still in apiserver. The it shows the desired replica number is 0, but actual replica number is 3, which is wrong. Tried to delete multiple times, it returns the same thing.

**Comment by kargakis** [comment]
Can you post the yamls with both deployments?

**Comment by kargakis** [comment]
It can be related to us not updating observedGeneration for deployments with overlapping selectors (the deployment reaper gets stuck until it observes that the deployment is observed by the controller)

**Comment by jingxu97** [comment]
I used the exact deployment file as the online doc  (http://kubernetes.io/docs/user-guide/deployments/#what-is-a-deployment), just change the name

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80


***

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-deployment2
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80

**Comment by jingxu97** [comment]
BTW: I think I created 3 or more of those deployment and then try to delete them

**Comment by kargakis** [comment]
@jingxu97 I am more interested in the current state of the Deployments. Can you post the output of 
```
kubectl get deploy/nginx-deployment deploy/nginx-deployment2 -o yaml
```

**Comment by kargakis** [comment]
I could see the second deployment added being stuck for the reason I mentioned above. I could delete the first deployment without a problem. Sending a patch soon for fixing the deletion for the deployments we don't sync.

**Comment by kargakis** [comment]
The reaper should also take into account overlapping deployments and do not cascade deletion for them.

**Comment by AdoHe** [comment]
@kargakis I will send a PR to check overlapping selector when  user create deployment through kubectl.

**Comment by kargakis** [comment]
@AdoHe thanks but kubectl changes are not enough. There are a couple of options here: 
1.
i. fix the deployment controller to update observedGeneration for overlapping deployments
ii. fix the deployment controller to not add the overlapping annotation for the older deployment
iii. fix kubectl to do non-cascading deletion of deployments with the overlapping annotation

2.
i. fix the deployment controller to not add the overlapping annotation for the older deployment
ii. fix kubectl to do non-cascading deletion for deployments that are not synced (d.generation > d.status.observedGeneration) and have the overlapping annotation

3.
I. fix the deployment controller to update observedGeneration for overlapping deployments
ii. fix kubectl to do non-cascading deletion for deployments with the overlapping annotation and zero replicas in their status

4.
Implement owner references and get rid of all the ugliness we do with overlapping annotations

While 1. and 2. are more correct than 3,, they don't actually work for cluster upgrades because in 1.5 all overlapping deployments will be deleted without cascading including the only one that is working. We should never have the overlapping annotation set on the deployment that is working in the first place. Since that ship has sailed short-term I would go with 3.. Ideally 4 is the best option but it's more work than the rest, @krmayankk have you started on the owner reference issue (https://github.com/kubernetes/kubernetes/issues/33845)? If not, I can take it over. I would like to have it for 1.5 if possible.

**Comment by kargakis** [comment]
Even 3. has a problem: if the working deployment is set to zero replicas and we try to delete it, we will actually orpahn any replica sets that it has, albeit with no pods.

**Comment by kargakis** [comment]
Actually we can remove the annotation from the working deployment so I think 1 and 2 are viable options. What I really don't want is to embed any of that logic (overlapping selector annotation) into kubectl. That's why I think 4 is what we really want.

**Comment by kargakis** [comment]
One last thought before I go offline: I think we will need to continue supporting kubectl 1.5 to work with older servers which means that we are stuck with the current implementation of the reaper as a fallback from server-side deletion. Iow. we should probably do one of 1. or 2. anyway since 4. is not backwards-compatible.

**Comment by AdoHe** [comment]
```
 I think we will need to continue supporting kubectl 1.5 to work with older servers
```
yes, this is the kubectl convention, kubectl 1.5 should still work with 1.3 server.

**Comment by AdoHe** [comment]
As for 4, owner reference should be a good solution for lots of problems, the backward compatibility is the biggest block.

**Comment by kargakis** [comment]
Opened https://github.com/kubernetes/kubernetes/pull/34952
