### ISSUE TITLE
If multiple default StorageClasses exist, pvc request fails

### ISSUE THREAD

**Issue by screeley44** [kubernetes/kubernetes#34549]
Do we want to stop the creation of a StorageClass with the "is-default" annotation, if one already exists on the cluster?  

If I create multiple "default" storage classes 

```
[root@screeley-sc1 gce]# kubectl get storageclass
NAME            TYPE                   ISDEFAULT
another-class   kubernetes.io/gce-pd   NO        
generic1-slow   kubernetes.io/gce-pd   YES       
generic2-fast   kubernetes.io/gce-pd   YES       
```

and then try to submit a PVC, I get this error

```
[root@screeley-sc1 gce]# kubectl create -f gce-pvc-multidefault.yaml 
Error from server (Forbidden): error when creating "gce-pvc-multidefault.yaml": persistentvolumeclaims "pvc-default" is forbidden: Internal error occurred: 2 default StorageClasses were found
```

@kubernetes/sig-storage

**Comment by screeley44** [comment]
@saad-ali - any thoughts on this? Do we want to not allow this to happen?

**Comment by jsafrane** [comment]
@kubernetes/sig-storage-misc, shall we update our admission controller to prevent two classes to be marked as default at the same time?

**Comment by msau42** [comment]
Sounds reasonable to me

**Comment by thockin** [comment]
This is something of scope creep on the admission controller - now it
handles PVCs and StorageClasses. If we do this, make sure to handle Update
properly.  This seems to be a backdoor way to get around the "no cross
object validation" pseudo-rule.

@lavalamp any other precedents around "only one" situations?

**Comment by lavalamp** [comment]
@smarterclayton is working on a proposal to move admission controllers out of process, which we talked about a lot during today's API Machinery SIG.

If you really want to provide a guarantee like this, you need some sort of locking mechanism around the check. The naive implementation where the admission controller lists all storageclasses and checks for uniqueness is actually quite broken (I'll leave this as an exercise for the reader), possibly worse than not doing the check at all because other components won't realize they have to handle the case where two get in.

I would consider making the controller implementing this thing responsible for demoting one class if it finds two defaults. This is the model that we use for Kubelet to reject a pod if it actually doesn't fit. I'm personally more of a fan of this approach because it means the cluster state is eventually correct. If the only defense against invalid state is an admission control check, then a bug there is potentially disastrous since the system can't self-heal. Of course if there's no bugs then it's probably not a problem...

**Comment by msau42** [comment]
My only concern about making it out of process is that it's not as easy to notify the user that they made a mistake.  By automatically demoting classes, then the user may not realize that their volume is not using their intended default class since the provisioning will succeed with a different default class.

**Comment by thockin** [comment]
yeah, I'd rather continue to error, I think

**Comment by agilgur5** [comment]
So in the current state, this issue delays an error until a PVC request is made instead of erroring out early during admission.

I found out I had two default `StorageClass`es (a new default was [added in `kops` 1.17](https://github.com/kubernetes/kops/pull/8582)) not when the second default was added, but when I added an application with a PVC. This was much further down the line in my cluster set-up (after multiple applications were deployed and running) than when the StorageClasses were created (immediately after `kops create cluster`).

It was also very confusing as the first thought when you see this is "wait why are there two defaults?" (I don't know when the second got added as it didn't error) and then "why was it _allowed_ to create two defaults when the error says it is _not_ allowed?"

**Comment by farvour** [comment]
This is an interesting scenario I also ran into with EKS 1.17 (I don't think it's specific to version). I have to agree with @agilgur5 that this type of situation should not really occur and the storage class shouldn't even be created if there is already another with the default annotation. It causes a lot of confusion downstream when one goes to actually start using PVCs and realizes "oh crap, I have 2 defaults defined... now I have to go figure out what might still be using the other one non-explicitly before I delete it".

Obviously the counter argument is one could be explicit about the "new" one, but that still seems wrong, to even allow a second default annotated storageclass of the same kind, at a minimum.

**Comment by gdraganic** [comment]
Same here:

```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: gp2-encrypted
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/aws-ebs
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: gp2
  fsType: ext4
  encrypted: "true"
```

When a new storage class is created, both are marked as default :

```
NAME                      PROVISIONER             RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
gp2 (default)             kubernetes.io/aws-ebs   Delete          WaitForFirstConsumer   false                  3d
gp2-encrypted (default)   kubernetes.io/aws-ebs   Delete          WaitForFirstConsumer   true                   128m
```

Creating a PVC yields the following error: `forbidden: Internal error occurred: 2 default StorageClasses were found`

**Comment by gnufied** [comment]
FWIW the bug still exists, so lets keep it open. It is kinda hard to fix though.

/reopen

**Comment by altitude1326** [comment]
The bug still exists need to re-open it.

/reopen

**Comment by altitude1326** [comment]
@msau42 can you do somthing for reopen and treat this bug please ?

**Comment by QJoly** [comment]
the problem is still here

**Comment by jsafrane** [comment]
This should be fixed by https://github.com/kubernetes/kubernetes/pull/110559

**Comment by khteh** [comment]
Still happen!

**Comment by aojea** [comment]
> Still happen!

in 1.26?

**Comment by khteh** [comment]
Due to them being annotated as `default`. There can only be ONE default `sc`.
