### ISSUE TITLE
kubeadm output should be clear and beautiful

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/kubernetes#34559]
Example of current output:

``` console
root@2f0adb170448:/# kubeadm init --cloud-provider=aws
<cmd/init> cloud provider "aws" initialized for the control plane. Remember to set the same cloud provider flag on the kubelet.
<master/tokens> generated token: "3a83a1.cd513749f90a4514"
<master/pki> generated Certificate Authority key and certificate:
Issuer: CN=kubernetes | Subject: CN=kubernetes | CA: true
Not before: 2016-10-11 18:20:57 +0000 UTC Not After: 2026-10-09 18:20:57 +0000 UTC
Public: /etc/kubernetes/pki/ca-pub.pem
Private: /etc/kubernetes/pki/ca-key.pem
Cert: /etc/kubernetes/pki/ca.pem
<master/pki> generated API Server key and certificate:
Issuer: CN=kubernetes | Subject: CN=kube-apiserver | CA: false
Not before: 2016-10-11 18:20:57 +0000 UTC Not After: 2017-10-11 18:20:57 +0000 UTC
Alternate Names: [192.168.9.3 10.0.0.1 kubernetes kubernetes.default kubernetes.default.svc kubernetes.default.svc.cluster.local]
Public: /etc/kubernetes/pki/apiserver-pub.pem
Private: /etc/kubernetes/pki/apiserver-key.pem
Cert: /etc/kubernetes/pki/apiserver.pem
<master/pki> generated Service Account Signing keys:
Public: /etc/kubernetes/pki/sa-pub.pem
Private: /etc/kubernetes/pki/sa-key.pem
<master/pki> created keys and certificates in "/etc/kubernetes/pki"
<util/kubeconfig> created "/etc/kubernetes/kubelet.conf"
<util/kubeconfig> created "/etc/kubernetes/admin.conf"
<master/apiclient> created API client configuration
<master/apiclient> created API client, waiting for the control plane to become ready
```

I don't know what is important. There's no indentation. There's no color. Let's add some structure and convention to this output.

cc @kubernetes/sig-cluster-lifecycle

**Comment by maciaszczykm** [comment]
It could be good improvement. Me and @floreks would like to discuss what direction we can go and possibly work on implementation.

Please share your feedback and post your own ideas.

## Indentation

Indents should be used for all second+ tier messages:

```
<master/pki> generated Service Account Signing keys:
  Public: /etc/kubernetes/pki/sa-pub.pem
  Private: /etc/kubernetes/pki/sa-key.pem
<master/pki> created keys and certificates in "/etc/kubernetes/pki"
<util/kubeconfig> created "/etc/kubernetes/kubelet.conf"
<util/kubeconfig> created "/etc/kubernetes/admin.conf"
<master/apiclient> created API client configuration
<master/apiclient> created API client, waiting for the control plane to become ready
```

`\t` indent should be used per every tier of message like in `kubectl`.

## Structure

### Timestamp

Taking into consideration, that `kubeadm` is not long-lasting process it should be kept rather short. We should display it in `hh:mm:ss` format. Otherwise, date could be added to make it `yyyy/mm/dd hh:mm:ss`.

### Source

Using `[]` braces instead of `<>` seems to be better choice, because it's easier to read.

## Colors

Should we use them? It could make logs much easier to read, but it's not common pattern in other Kubernetes' tools like `kubectl`, `hyperkube` etc.

If we'd like to, we should establish color pattern for every message. What colors should we use?

## Visualisation

![image](https://cloud.githubusercontent.com/assets/2823399/19387235/2e036df0-9219-11e6-9c2d-88e228973704.png)

![image](https://cloud.githubusercontent.com/assets/2823399/19387285/907eace2-9219-11e6-887a-ca33241b96be.png)

**Comment by pires** [comment]
I like this a lot, however I'd leave it until the code stabilizes. Right now, there's too much still going on and there's already some rebase he'll happening.

**Comment by dgoodwin** [comment]
I like the color, indentation, and timestamps. 

I'd love to see warnings/errors printed in red/yellow from the new pre-flight checks. (Example here: #34341)

**Comment by errordeveloper** [comment]
@maciaszczykm great work, I love it! If you make a PR, please make sure colours can be disable when output is not a TTY, or doesn't suppor colours. I am not sure we have to hold on with this, if it's something you have already implement and can open a PR soon, as long as it doesn't change lines other than ones that print output message.

**Comment by errordeveloper** [comment]
We can discuss more colours later, e.g. some extra verbose messages can be grey, but I'd love to get something in for the start!

**Comment by pires** [comment]
@errordeveloper there are quite a few PRs already open and some in the works related to the many issues that were opened for `kubeadm`.I'm looking to avoid the frustration of handling rebase hell for everyone involved, particularly because CLI is under active development.

**Comment by mikedanese** [comment]
Awesome stuff!

We won't know the impact on other PRs until we know what the code looks like. I'd recommend opening a PR once this is ready. We can always merge other PRs before this if we think conflicts will be painful.

**Comment by floreks** [comment]
It's great to hear that you liked our proposal. 

We've investigated couple of possible solutions to add support for coloring. As we can see `kubeadm` module uses mostly `fmt` package for printing. There is `initLogs` called which initializes `glog` but is it actually used somewhere? There are no references in `kubeadm` module.

First option (if log/glog is not used) is to use default `log` package with custom writer. We could chain them to set timestamp/colors. In this case indents would have to be set by the user within log messages.

Second option is to add own logging interface with custom API (foo.Info, foo.Error, etc.). Possibly we could support indents for 2+ tier messages here but we think that this kind of logic is not destined for loggers and should be handled by the users (`\t` usage, we can refactor existing messages as a kick off).

Third option is to implement new `Writer` that can be passed to `fmt.FprintX` and used to add suffix `hh:mm:ss [package/file]` before actual message. Indents would have to be handled by the user and it would require from devs to always use `fmt.FprintX` that accepts `Writer` as a parameter. `Writer` also would have to be passed to all functions directly or within some structure in order to follow the logging pattern.

We will start with some common implementation that will be used by all options, i.e. colors, isTTY.

What do you think?

**Comment by floreks** [comment]
Any reply would be great. We would like to move forward with it.

**Comment by errordeveloper** [comment]
@floreks we are pressing for a snapshot release to get some of the user issues fixed, if you would like to chat about more details, please join us on Slack.

**Comment by errordeveloper** [comment]
> We've investigated couple of possible solutions to add support for coloring. As we can see kubeadm module uses mostly fmt package for printing. There is initLogs called which initializes glog but is it actually used somewhere? There are no references in kubeadm module.

Yes, we are not using `glog`, as it produces rather noisy output by default, and we haven't had time to investigate custom formating, please feel free to do so.

> First option (if log/glog is not used) is to use default log package with custom writer. We could chain them to set timestamp/colors. In this case indents would have to be set by the user within log messages.

Please take a look, I think a PR that add custom writer definition would be a good start.

> Second option is to add own logging interface with custom API (foo.Info, foo.Error, etc.). Possibly we could support indents for 2+ tier messages here but we think that this kind of logic is not destined for loggers and should be handled by the users (\t usage, we can refactor existing messages as a kick off).

May be. I think there are a few interesting things we could try. 

> Third option is to implement new Writer that can be passed to fmt.FprintX and used to add suffix...

No need, we don't have to stick to `fmt` package, as I said above.

**Comment by floreks** [comment]
First option is quite simple but as I've started to work on that I've noticed that `log` lacks option to write to stderr. It only offers simple `Print` with custom writer. 

I guess this leaves us with second option. I don't want to create whole framework but rather simple solution that will meet our requirements and offers at least 3 levels of logging (Info, Warning, Error).

**Comment by floreks** [comment]
Small update:

![zrzut ekranu z 2016-10-25 16-24-28](https://cloud.githubusercontent.com/assets/2285385/19723517/e12b4c3e-9b7b-11e6-8bfb-76f04f5185aa.png)

Do we want to color warning messages also? If yes, I think that we should consider changing the color of timestamp so it's not the same as warning color.

I've almost finished initial version. I should be able to create PR soon and if we agree on the solution then I will refactor current messages to use this logger.

**Comment by mikedanese** [comment]
This issue was moved to kubernetes/kubeadm#41
