### ISSUE TITLE
PersistentVolume on EBS can be created in availability zones with no nodes

### ISSUE THREAD

**Issue by buildmaster** [kubernetes/kubernetes#34583]
**Kubernetes version** (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.1", GitCommit:"33cf7b9acbb2cb7c9c72a10d6636321fb180b159", GitTreeState:"clean", BuildDate:"2016-10-10T18:19:49Z", GoVersion:"go1.7.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.0", GitCommit:"a16c0a7f71a6f93c7e0f222d961f4675cd97a46b", GitTreeState:"clean", BuildDate:"2016-09-26T18:10:32Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: `aws`
- **Install tools**: `kops` default install

**What happened**: 
AWS EBS backed PersitantVolumeClaim created a volume in an AZ where there was a master but no nodes. Making it unusable.

**What you expected to happen**:
Zones with master and no nodes shouldn't be used to create the EBS Volume

**How to reproduce it** (as minimally and precisely as possible):
- AWS setup across 3 AZs in one region
- Master in three AZs
- Nodes in 2 AZs (so one AZ has a Master but no Nodes)
- Create a Storage class to use EBS without specifying AZ 

```
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: ebs
provisioner: kubernetes.io/aws-ebs
```
- Create PVC against StorageClass 

```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data
  annotations:
    volume.beta.kubernetes.io/storage-class: "ebs"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
```
- PVC can create a volume in an availability zone with no nodes

**Anything else do we need to know**:
Mentioned on Slack channel #sig-aws with @justinsb who asked me to raise this

**Comment by ymqytw** [comment]
@kubernetes/sig-storage

**Comment by thockin** [comment]
@jsafrane

**Comment by jsafrane** [comment]
Running Kubernetes master in a zone that has no running nodes is quite strange and I don't think this is a typical case we should support.

AWS cloud provider lists all machines in the cluster and chooses a random zone that has at least one running instance. It seems it does not distinguish master/node machines.  IMO, GCE has the same problem, it lists all zones in a region where the master runs and it does not distinguish masters and nodes either.


We can either introduce a new AWS instance tag with master/node role that is running on the instance or we can move the zone decision into volume plugin itself, where we have a kubeclient and we can filter nodes relatively easily, however we will depend on an admission controller that must add a zone label to nodes.

@justinsb,  thoughts?

As a third option, we could rely on kubernetes admin to fill all zones into StorageClass in this weird case. Right now we support only one zone in "zone" parameter, we could allow a list:

```
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: ebs
provisioner: kubernetes.io/aws-ebs
parameters:
  zone: "us-east-1a,us-east-1b,us-east-1c"
```

**Comment by buildmaster** [comment]
just to add to this, the reason why it's a deal is I actually don't have full control over where the nodes run, as they're in an autoscale group across all AZs. So you could have master in AZ a and nodes in b and c just because that's what the auto scale group picked.

**Comment by stevesloka** [comment]
I just ran into this, however, I only have nodes / masters in 3 zones, but the PV was created in a 4th zone. So right now I can't even spin up a node in the last AZ since in my infrastructure, I'm not supporting it.

```
~/dev ❯❯❯ kubectl get no --show-labels
NAME                          STATUS    AGE       LABELS
ip-10-0-70-253.ec2.internal   Ready     2d        beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=t2.large,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=us-east-1,failure-domain.beta.kubernetes.io/zone=us-east-1c,kubernetes.io/hostname=ip-10-0-70-253.ec2.internal
ip-10-0-71-238.ec2.internal   Ready     2d        beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=t2.large,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=us-east-1,failure-domain.beta.kubernetes.io/zone=us-east-1d,kubernetes.io/hostname=ip-10-0-71-238.ec2.internal
ip-10-0-72-59.ec2.internal    Ready     2d        beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=t2.large,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=us-east-1,failure-domain.beta.kubernetes.io/zone=us-east-1e,kubernetes.io/hostname=ip-10-0-72-59.ec2.internal

~/dev ❯❯❯ kubectl describe pv pvc-288e7b9c-d9d8-11e6-9d58-0a8828a2b648
Name:		pvc-288e7b9c-d9d8-11e6-9d58-0a8828a2b648
Labels:		failure-domain.beta.kubernetes.io/region=us-east-1
		failure-domain.beta.kubernetes.io/zone=us-east-1b
StorageClass:	default
Status:		Bound
Claim:		default/es-data-es-data-0
Reclaim Policy:	Delete
Access Modes:	RWO
Capacity:	100Gi
Message:	
Source:
    Type:	AWSElasticBlockStore (a Persistent Disk resource in AWS)
    VolumeID:	aws://us-east-1b/vol-0f2110cfa5904e4ba
    FSType:	ext4
    Partition:	0
    ReadOnly:	false
No events.

~/dev ❯❯❯ kubectl describe po es-data-0
...
  FirstSeen	LastSeen	Count	From			SubObjectPath	Type		Reason			Message
  ---------	--------	-----	----			-------------	--------	------			-------
  1d		1m		6055	{default-scheduler }			Warning		FailedScheduling	pod (es-data-0) failed to fit in any node
fit failure summary on nodes : NoVolumeZoneConflict (3)
```

**Comment by mastercactapus** [comment]
@jsafrane I think it may be more than just where there are or not nodes vs masters in an AZ.

As an additional use case, consider pods that must run on a "dedicated" tenancy node in AWS, (which have a baseline cost per-zone) for compliance. Since masters are supposed to be an odd number (i.e. 3 zones) it would make sense to have 3 instead of 2. But for a pod that has to be scheduled on a "dedicated" tenancy node, there may be only 2 zones with nodes that are "dedicated" due to said cost. Even if there are nodes in all zones, a pod may need to be scheduled on a specific node or subset thereof. 

More information about node selection:
https://kubernetes.io/docs/user-guide/node-selection/

More information about why this specific case would be necessary here:
https://d0.awsstatic.com/whitepapers/compliance/AWS_HIPAA_Compliance_Whitepaper.pdf

If PVs are used by pods, and pods must be able to access them from whatever nodes they are constrained/scheduled to, I think whatever solution is implemented needs to account for that.

**Comment by jsafrane** [comment]
@stevesloka, do you have any other non-Kubernetes instances in us-east-1b in your AWS account?

Did you try to tag your AWS instances that run Kubernetes with tag `KubernetesCluster=steve` - all AWS instances in one Kubernetes cluster must share the same tag value, so you can run multiple Kubernetes clusters in one AWS account. This tag is not documented, see #39178.

**Comment by stevesloka** [comment]
@jsafrane There is another non-k8s instance running in us-east-1b, but it's not related (created via breanstalk). 

I added labels to all my nodes / controller as you sugessted and still it created the PV in `us-east-1b`. 

I may bail on Statefulset for now and manage my pv's by hand since I'm building out an operator and it wont be that painful, but would like to see if this could be addressed. 

I'm also willing to help out if you can help point into the right places this logic lives. I'll try and dig in and see if I can find it myself.

**Comment by naphthalene** [comment]
It would be ideal to have the StorageClass accept an expression or wildcard zone under the aws provisioner. Ideally I shouldn't have to care where my pods are running and where the EBS are created.

**Comment by jsafrane** [comment]
We've a PR https://github.com/kubernetes/kubernetes/pull/38505 that adds "zones:" with list of zones instead of single "zone:". No wildcards though.

**Comment by dforste** [comment]
I just hit this as well. I think moving the "zone" decision closer to the provisioning decision would be best. Perhaps wait until a PVC is consumed by a pod before you create it in a zone. That way corner cases like this are not a problem.

**Comment by zfy0701** [comment]
We also hit this problem because different use case.

We have master running in all us-west-2a us-west-2b us-west-2c
We use nodeSelector to create pod under a specific zone, say us-west-2b

we use a storage class with default zone (which is us-west-2 I assume)
and then it seems the volume is created at us-west-2a instead of us-west-2b

it seems when volume is created, it doesn't consider the node select the pod have

**Comment by jingxu97** [comment]
Just want to check whether PR  #38505 is good enough to solve the issue raised here?

**Comment by redbaron** [comment]
@dforste , is right. Another use case is that if pod consumes >1 PVC, associated PVs might be created in different zones, therefore pod becomes unschedulable, as there is no node which belongs >1 AZ. Zone decision when provisioning PV must be made as late as possible, while currently it seems to be a very first thing to do.

**Comment by redbaron** [comment]
I don't think it can be closed yet, reasons are:
 1. those magical tags are not documented anywhere, how people or going to know to use them?
 2. can't it continue to create volume in  a zone where pod with a given PVC can never be scheduled (lets say it has node affinity configured to a node in a particular AZ)?

**Comment by mccormd** [comment]
Would it make sense to say that the dynamic creation of a volume should happen only once a PVC has been attached to a pod which has been successfully scheduled to a node?  Then the av_zone of the volume should match that of the selected node?

**Comment by dforste** [comment]
Yes I would agree with that statement. The PVC should be created when we know the node and AZ it is a apart of.

**Comment by colinmorelli** [comment]
Just to add another use case to this - I just spun up a new cluster in AWS. Masters spanning `us-east-1a`, `us-east-1b`, and `us-east-1d`. After creating the ASG for nodes, I learned that AWS is out of instance capacity in `us-east-1d` for that particular instance type. Now I currently don't have nodes in `us-east-1d` (until capacity is restored and I can move an instance over).

The reason this is different is because, in this case, I don't want to tell k8s to only use a subset of AZs. I _want_ it to deploy across all AZs that are available. It just so happens that at this moment in time not all AZs are available.

@mccormd suggestion above would work, I believe. Schedule the node first, then provision a volume. That might have other implications, though.

**Comment by ashb** [comment]
I just ran into this today - PVC created in eu-west-1c, but the only node with memory to to run the pod was in eu-west-1b.

```
Events:
  Type     Reason            Age              From               Message
  ----     ------            ----             ----               -------
  Warning  FailedScheduling  2s (x9 over 2m)  default-scheduler  0/3 nodes are available: 1 Insufficient memory, 1 node(s) had no available volume zone, 1 node(s) had taints that the pod didn't tolerate.
```

This was a new pod and a new volume claim. Can we have this re-opened at least please?

**Comment by ValeryNo** [comment]
We had to ultimately get rid of all persistence volume claims on AWS because of this.
For really large clusters with lots of reserved capacity in all availability zones that woulnd't be such a big deal, but I'd image most companies are trying to optimize their cost and don't have than many node pre-provisioned just for the sake of it.
Still looking for a solution which is easy to configure and AZ-failure friendly

**Comment by ashb** [comment]
Would `volumeBindingMode: WaitForFirstConsumer` in a StorageClass go some way to fixing the issue? (At least for new claims anyway)?

From https://kubernetes.io/blog/2018/04/13/local-persistent-volumes-beta/

**Comment by stevesloka** [comment]
I solved this in the Elastic Operator by creating StorageClasses per zone and spreading work across that way. You need to make sure your app is zone tolerant. For example, the Elastic operator sets up sharding and replication across zones, given one AZ goes down, the other two still have enough of the data to continue functioning.

**Comment by deitch** [comment]
@stevesloka doesn't each pod then need access to storage from a different class (appropriate for the zone it is in)? How does that work?

**Comment by willtrking** [comment]
Just ran into this as well, running work load specific zones in 2 regions for development to save cost over 3, had an EBS volume provisioned in the zone with no instance.

**Comment by ddebroy** [comment]
https://github.com/kubernetes/kubernetes/pull/65730 should address the above scenarios when you use set `volumeBindingMode: WaitForFirstConsumer` in the storageclass.

**Comment by nicroto** [comment]
I have a similar issue:
 - 3 masters + 3 nodes in 3 regions. I have a PV (created on regionA) for data backups created by a CronJob. When the cron's job gets scheduled on a node on a different region (regionA's CPU has been allocated almost fully and the master chooses another node in a different region) - it can't start because the PV is not accessible.

Is there a way to avoid this issue?

**Comment by lachlancooper** [comment]
As mentioned above, this feature is now in beta in 1.12: https://kubernetes.io/docs/concepts/storage/storage-classes/#volume-binding-mode

**Comment by frankgu968** [comment]
Are there any workaround for Amazon EKS to address the above issue? 

I am trying to make a multi-az JupyterHub deployment and changing zones causes the "no available volume zone" error...

**Comment by markyjackson-taulia** [comment]
Is this still in progress? I just ran in to issue as well

**Comment by chandresh-pancholi** [comment]
we moved it to GCP with 1.10 version and didn't face the issue

**Comment by KristianWindsor** [comment]
I'm also having this issue...
```
  Type     Reason            Age                   From               Message
  ----     ------            ----                  ----               -------
  Warning  FailedScheduling  14s (x15 over 3m20s)  default-scheduler  0/2 nodes are available: 2 node(s) had no available volume zone.
```
So there's no solution to this?

**Comment by AdeOpe** [comment]
im also having this issue on AWS EKS

Events:
  Type     Reason            Age                From               Message
  ----     ------            ----               ----               -------
  Warning  FailedScheduling  2m (x841 over 1h)  default-scheduler  0/2 nodes are available: 1 Insufficient pods, 1 node(s) had no available volume zone.

losing hope over here :(

**Comment by khteh** [comment]
Warning  FailedScheduling   3m2s (x660 over 58m)   default-scheduler   0/2 nodes are available: 1 Insufficient pods, 1 node(s) had no available volume zone.

**Comment by zakkg3** [comment]
Another similar case here, like @khteh: 0/2 nodes are available: 1 Insufficient pods, 1 node(s) had no available volume zone.
The EBS was created in the AZ where the node is full (1c).. you can guess the rest..

**Comment by srinivasrk** [comment]
Any update on this ? Since Node affinity is a beta feature causing this issue?

**Comment by rohith-vallabhaneni** [comment]
I'm using EKS to deploy my services integrating it with rancher, I ran into the same issue as mentioned above. My setup is something like this:
1. I have added few labels for the worked nodes to seperate the nodes per namespace/team  as each team requires different types of instances.
2. I created the nodes for the pods in that node needs persistant volumes in a single availability zone as aws EBS attachment is per availability zone.
3. When I deployed my applications, the persistant volume got created but in different availability zone as I used the default storage class which creates EBS in random zones.


The issue is fixed by creating another **storage class** with only single availbility zone.

`kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: ebs
provisioner: kubernetes.io/aws-ebs
parameters:
  zone: "us-east-1a"`

**Comment by abdennour** [comment]
I am using EKS , and I designed not only my pods to be Cattle, but also my nodes are Cattle as well : 

- I have Pod created statefulset. 
- This statefulset defines a PVC. 
- The PVC triggers the creation of new EBS in the same AZ of the Node (i don't have pb here)
- Because Nodes are Cattle, it happen that there is no Node exist in   the AZ of EBS (PVC)
=> Pod of statefulset remains in "Pending" state
=> Pod events shows this error: " 1 node(s) had no available volume zone"

- Once a New node joins the cluster in the wanted AZ, the Pod of statefulset runs like a charm because the EBS can be attached at that node (same AZ).

Thinking to use EFS ([like this man did](https://medium.com/faun/aws-eks-volumes-architecture-in-a-statefull-app-in-multiple-azs-6ca1b05f80eb) )but looking to better solutions.

**Comment by thangbn** [comment]
> I am using EKS , and I designed not only my pods to be Cattle, but also my nodes are Cattle as well :
> 
> * I have a Pod created by statefulset.
> * This statefulset defines a PVC.
> * The PVC triggers the creation of new EBS in the same AZ of the Node (i don't have pb here)
> * Because Nodes are Cattle (destoryable any time), it happen that there is no Node exist in   the AZ of EBS (PVC)
>   => Pod of statefulset remains in "Pending" state
>   => Pod events shows this error: " 1 node(s) had no available volume zone"
> * Once a New node joins the cluster in the wanted AZ, the Pod of statefulset runs like a charm because the EBS can be attached at that node (same AZ).
> 
> Thinking to use EFS ([like this man did](https://medium.com/faun/aws-eks-volumes-architecture-in-a-statefull-app-in-multiple-azs-6ca1b05f80eb) )but looking for better solutions.

from my experience, EFS performance is not that great. better avoid it.

**Comment by tdmalone** [comment]
> from my experience, EFS performance is not that great. better avoid it.

It depends how you use it. It's not great for lots of little files (don't check out a git repo on it, for instance 😅). It's been working great for us in production for almost a year so far, mainly on larger PDF files etc. But, like anything, definitely test it for your use case.

**Comment by ksummersill2** [comment]
> I'm using EKS to deploy my services integrating it with rancher, I ran into the same issue as mentioned above. My setup is something like this:
> 
> 1. I have added few labels for the worked nodes to seperate the nodes per namespace/team  as each team requires different types of instances.
> 2. I created the nodes for the pods in that node needs persistant volumes in a single availability zone as aws EBS attachment is per availability zone.
> 3. When I deployed my applications, the persistant volume got created but in different availability zone as I used the default storage class which creates EBS in random zones.
> 
> The issue is fixed by creating another **storage class** with only single availbility zone.
> 
> > `kind: StorageClass apiVersion: storage.k8s.io/v1beta1 metadata: name: ebs provisioner: kubernetes.io/aws-ebs parameters: zone: "us-east-1a"`

So I do have a question. If I just put the PVC into the specific availability. zone. Does that allow the other pods on different nodes to use it?

**Comment by rohith-vallabhaneni** [comment]
> > I'm using EKS to deploy my services integrating it with rancher, I ran into the same issue as mentioned above. My setup is something like this:
> > 
> > 1. I have added few labels for the worked nodes to seperate the nodes per namespace/team  as each team requires different types of instances.
> > 2. I created the nodes for the pods in that node needs persistant volumes in a single availability zone as aws EBS attachment is per availability zone.
> > 3. When I deployed my applications, the persistant volume got created but in different availability zone as I used the default storage class which creates EBS in random zones.
> > 
> > The issue is fixed by creating another **storage class** with only single availbility zone.
> > > `kind: StorageClass apiVersion: storage.k8s.io/v1beta1 metadata: name: ebs provisioner: kubernetes.io/aws-ebs parameters: zone: "us-east-1a"`
> 
> So I do have a question. If I just put the PVC into the specific availability. zone. Does that allow the other pods on different nodes to use it?

The nodes running on other availability zones couldn't access this PV until if you use EFS rather than EBS

**Comment by jobevers** [comment]
I ran into a similar issue today investigating a `0/2 nodes are available: 2 node(s) had volume node affinity conflict.` error

I have a PVC:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 250Gi
```
and originally it bound fine, with a PV in us-east-1d
```
➜  kubectl describe pv pvc-... | grep VolumeID
    VolumeID:   aws://us-east-1d/vol-02...a
```

Then, I ran an upgrade and none of the new nodes were created in us-east-1d
```
➜  kubectl describe nodes | grep ProviderID
ProviderID:                   aws:///us-east-1b/i-002...7
ProviderID:                   aws:///us-east-1c/i-06d...d
```
And, now I have a disk in a zone without any nodes.

**Comment by ksummersill2** [comment]
I found the issue. The issue is that when you are using AWS then the PVC is set to the Node. That means that if you try to put that pod or deployment on another node then it will not connect with the PVCs and being a pending state. It's an AWS thing. I resolve this by specifying taints and toleration to the nodes within that specific region.

**Comment by abdennour** [comment]
@ksummersill2  thank you! can you post an example for more elaboration
