### ISSUE TITLE
PodDisruptionBudget maxUnavailable

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#34776]
PodDisruptionBudget allows you to specify minAvailable.

I would like to have, say, a cassandra cluster, and be able to scale it up and down according to some custom metric.  

Say my data is replicated 3 ways.  So, I don't ever want more than 2 instances down or I can't read my data during the disruption.

With the current `minAvailable`, I have to adjust both the Deployment (or PetSet) scale, and the PodDisruptionBudget at the same time, which prohibits use of generic scaling, e.g. via HPA with custom metrics.

Presumably the validation would only allow one of these options to be specified at a time.

@kubernetes/api-review-team 

@kow3ns @foxish we talked about this today.

@davidopp @mwielgus you work on PodDisruptionBudget I think.

**Comment by davidopp** [comment]
We allow minAvailable to be expressed as a percentage of desired number of replicas rather than an absolute number. Does that address your requirement?

**Comment by erictune** [comment]
I don't think so.  What percentage should I use for a collection that must allow for 1 unavailable, and up to 2 unavailable, but not more than 2, and which can be scaled from 3 to 300 Pods?

**Comment by davidopp** [comment]
Let me see if I understand. You have a storage system. It consists of an arbitrary number of pods whose quantity can change over time. Within the storage system, regardless of the number of pods that constitute the storage system, each data item is replicated 3 times, with each replica on a separate node. Therefore you want to ensure that no more than 2 nodes are ever down at the same time. Is that correct?

We can certainly add maxUnavaiable, but I'm wondering if we're sliding into territory where it would be better to just have an API to ask the application whether it's OK to disrupt a particular pod. The approach you're describing seems like it will have to be very conservative. For example, say your 300-pod storage system is internally organized into three groups of 100, and each group stores exactly the same data as the other two. In that case you can safely disrupt 200 of the 300 pods simultaneously as long as you pick the right 200 pods. But if you pick random pods, you can only safely disrupt 2 at the same time.

As with your (unrelated) question about distinguishing data-deleting vs. non-data-deleting drains, at some point the requirements become complex enough that an actual maintenance API is probably the right approach. Of course the two scenarios are slightly different; maxUnavailable is about getting application-level information out of the application, while the drain one is about getting information into the application.

**Comment by erictune** [comment]
@mml @davidopp @ko3ns talked about this just now.  Summary:

- Eric would be fine with replacing maxUnavailable with minAvailable, or with having both.
- If you chose to not change or add, consider at least making maxUnavailable optional for 1.5, so it is easier to change later.
- The API would be useful, but tricky to implement, so we don't want very many apps to have to serve such an API.
-  We couldn't think of any reasons that minAvailable is more useful than maxUnavailable, and we tried.
- Matt pointed out that Available might not be precisely defined, and that maybe we should use "ready" since Readiness has a precise definition, we think.

**Comment by erictune** [comment]
@mwielgus leave it up to you what to do.

**Comment by kargakis** [comment]
> Eric would be fine with replacing maxUnavailable with minAvailable, or with having both.

Let's keep this as simple as possible. I would prefer to replace.

> Matt pointed out that Available might not be precisely defined, and that maybe we should use "ready" since Readiness has a precise definition, we think.

We already use Available in Deployments and RC/RS which is Ready+MinReadySeconds. Once we push MinReadySeconds down to Pods and add an Available condition it will be clearer what "available" means cc: @bgrant0607

**Comment by mml** [comment]
> We already use Available in Deployments and RC/RS which is Ready+MinReadySeconds. Once we push MinReadySeconds down to Pods and add an Available condition it will be clearer what "available" means

Originally we were going to add MinReadySeconds to the PDB, but it seemed crazy complicated to specify so many thresholds and to specify MinReadySeconds in Yet Another Place.

Thus in the PDB type we have written Available but the code implements Ready.

To make matters even muddier, even "Available" isn't quite going to be the actual definition we use, as we'll probably be counting pods *approved* for eviction against the budget (see https://github.com/kubernetes/kubernetes/pull/34546#issuecomment-253135695 and https://github.com/kubernetes/kubernetes/pull/34546#issuecomment-253368793) as well, even when they're Available.  Whether this distinction needs to be reflected in the field name in the PDB, I'm not sure.  But since we're on the cusp of changing names and semantics, I figured I should raise the issue.

**Comment by kargakis** [comment]
> Thus in the PDB type we have written Available but the code implements Ready.

This is unfortunate because it means PDB cannot work with controllers that use MinReadySeconds. Note that Available is a superset of Ready so if something works with Available it can also work with Ready, not the other way around. I see two solutions to this: 1) add Available condition to pods or 2) add MinReadySeconds to PDB. I also don't like 2 and 1 doesn't seem to be something we will have in 1.5. That being said I think it's perfectly fine but eventually we want PDB to work with controllers that use MinReadySeconds which means PDB eventually should work with Available pods.

**Comment by timothysc** [comment]
FWIW you would **never-ever-ever-ever** scale cassandra based on HPA, even with some custom metric, unless you somehow bound internal params outside the system, even then you would need to account for data lifecycle management.  If anything you would have some custom logic to determine if/when to scale vs. compact vs. remove vs ...

**Comment by bgrant0607** [comment]
@erictune @davidopp @mml Are we discussing changes to PodDisruptionBudget, Deployment + RS + RC, or both?

**Comment by davidopp** [comment]
@bgrant0607 AFAIK we're just talking about a change to PodDisruptionBudget.

As for what to do here -- my suggestion would be to continue to call it minAvailable, and when pods start exporting an Available condition, change the implementation of PDB to use that. Until then, we can document what minAvailable means in this context (i.e. really means ready).

The more proper thing to do, of course is to
* rename what we have now to minReady
* when pods start exporting an Available condition, continue supporting minReady using the current definition, and add a minAvailable, which uses the Available condition from pods

The downside of the first approach is that people may be surprised when the definition changes, but I am not super-worried because that surprise is making the system more conservative (we wait longer for the thing to be "available").

**Comment by davidopp** [comment]
But I'm fine with either approach, so whichever people prefer, I say go with that.

**Comment by bgrant0607** [comment]
@davidopp Changing from minAvailable to maxUnavailable isn't an option?

Anyway, calling it available but using ready for now is fine by me.

**Comment by davidopp** [comment]
Sorry, yes, I did not mean to imply I am opposed to maxUnavaliable. So just replace in what I wrote
minAvailable -> maxUnavailable
minReady -> maxNotReady

I agree that changing it from min to max makes sense.

**Comment by kargakis** [comment]
+1 for maxUnavailable and for continuing with *Available but changing the docs to reflect ready

**Comment by kargakis** [comment]
Are we going to do this for 1.5?

**Comment by erictune** [comment]
Talking to @mwielgus, this is too hard to do for 1.5, and it is more important for PDB to go to Beta than to have this, so I'm closing this request. 

For 1.5, StatefulSet users should create PDBs alongside their StatefulSets.  For StatefulSets, we'll recommend that users need to adjust PDB when scaling the set (uncommon operation for quorum-based) or when using a template, helm chart, etc, that they update the parameters of the template/chart and the scale parameter will flow to both the StatefulSet and the PDB.

**Comment by erictune** [comment]
Talking to @mwielgus, this is too hard to do for 1.5, and it is more important for PDB to go to Beta than to have this, so I'm closing this request. 

For 1.5, StatefulSet users should create PDBs alongside their StatefulSets.  For StatefulSets, we'll recommend that users need to adjust PDB when scaling the set (uncommon operation for quorum-based) or when using a template, helm chart, etc, that they update the parameters of the template/chart and the scale parameter will flow to both the StatefulSet and the PDB.

**Comment by erictune** [comment]
Talking to @mwielgus, this is too hard to do for 1.5, and it is more important for PDB to go to Beta than to have this, so I'm closing this request. 

For 1.5, StatefulSet users should create PDBs alongside their StatefulSets.  For StatefulSets, we'll recommend that users need to adjust PDB when scaling the set (uncommon operation for quorum-based) or when using a template, helm chart, etc, that they update the parameters of the template/chart and the scale parameter will flow to both the StatefulSet and the PDB.  

If feedback after 1.5 is that this is too hard to keep in sync, we can consider teaching StatefulSet to optionally managed PDB for the user.  This can be done backwards compatibly.

**Comment by mwielgus** [comment]
Just to clarify - it is not hard to replace minAvailable with maxUnavailable but just maxUnavailable combined with pod selector doesn't have much sense when the selector doesn't match to any replication controller/dep/rs/etc - in general, something that contains information what should be the total number of replicas. 

We could have both minAvailable and maxUnavailable, it would be probably possible to squeeze it to 1.5 but we can also probably do it later. Adding optional maxUnavailable to minAvailable won't be a breaking change.

**Comment by kargakis** [comment]
> maxUnavailable alone combined with pod selector doesn't have much sense when the selector doesn't match to any replication controller/dep/rs/etc

Most if not all of the workloads are going to run under a controller, right? MinAvailable isn't very useful for a controller for the exact reason @erictune mentioned in the starting post.

**Comment by mwielgus** [comment]
It is useful if you want to have PDB with the same selector as your service.

**Comment by mwielgus** [comment]
Otherwise we should rather replace selector with object reference.

**Comment by kargakis** [comment]
So you have a service that load balances pods that are not controlled by a
controller?
I am interested into knowing cases where you wouldn't want to use a
controller.

**Comment by kargakis** [comment]
> which can span over multiple rs/rc/dep

You still have the same problem because the service can be scaled up/down but MinAvailable stays the same...

**Comment by mwielgus** [comment]
Thats exactly what is needed, minAvailable should always be there. MaxUnavailable needs an expected number of replicas to be present somewhere. You cannot get expected number of replicas from a service. It doesn't have such information.

Some other example. Imagine that your deployment is controlled by HPA. HPA can scale from 1 to 10. You want to make sure that there is always at least one replica present. With maxUnavailable = 1 you cannot fulfill this because if your deployment size = 1 then someone can kill your last replica. If you set maxUnavailable to 0 then HPA will not work. 

So minAvailable is needed and cannot be fully substituted by maxUnavailable.

**Comment by kargakis** [comment]
> With maxUnavailable = 1 you cannot fulfill this because if your deployment size = 1 then someone can kill your last replica. If you set maxUnavailable to 0 then HPA will not work.

This is a problem with absolute numbers but not with percentages. I see that maxUnavailable cannot fully substitute minAvailable but the same holds for minAvailable. I guess the latter is more safe than the former so I am fine with proceeding with MinAvailable. Would it overcomplicate PDB to have both?

**Comment by mwielgus** [comment]
No, I voted for having both. But unfortunately the code freeze is on Monday so maxUnavilable got deprioritized over other stuff that is needed for PDB to work reliably at all.

**Comment by kargakis** [comment]
We can have it in 1.6 and keep this issue open then?

**Comment by mwielgus** [comment]
Sure.

**Comment by davidopp** [comment]
I am in favor of adding maxUnavailable in 1.6 for the reasons @mwielgus mentioned (I've changed the milestone to 1.6).

We have also talked about possibly adding an application-specific API endpoint that would be queried instead of a hardcoded min/max, but that is more speculative. The point is just that we are likely to add moe fields to PDBSpec in the future.

**Comment by davidopp** [comment]
PDB was envisioned to constrain disruptions caused by cluster-level agents like node upgrade, rescheduler, cluster auto-scale-down, etc. Disruptions from other causes are reflected in its computation of how many pods are up/down, but disruptions from other causes are not themselves limited by PDB.

We should consider how/whether to integrate Deployment's rolling update maxUnavailable with PDB maxUnavailable. Today if your Deployment maxUnavailable is more generous than your PDB, you can violate the PDB during a rolling update, which seems bad (Deployment rolling update doesn't use /eviction subresource). We could just have Deployment rolling update use /eviction subresource, but that might be a confusing user experience since maxUnavailable (or the equivalent) would be specified in two places, one less obvious than the other.

**Comment by foxish** [comment]
> We should consider how/whether to integrate Deployment's rolling update maxUnavailable with PDB maxUnavailable. Today if your Deployment maxUnavailable is more generous than your PDB, you can violate the PDB during a rolling update, which seems bad (Deployment rolling update doesn't use /eviction subresource). We could just have Deployment rolling update use /eviction subresource, but that might be a confusing user experience since maxUnavailable (or the equivalent) would be specified in two places, one less obvious than the other.

Someone who created the deployment should have better knowledge of the disruption that they can tolerate for it, so, it does sound like that should supersede a PDB specified. If `.spec.strategy.rollingUpdate.maxUnavailable` is not specified, having rolling update respect the PDB makes sense. So perhaps we should have the PDB be used when any controller for pods is unable to specify how eviction should be carried out? I can imagine for example, even with third party controllers, we may want an associated TPR to specify a more specific bound.

**Comment by davidopp** [comment]
The conservative approach would be to use whichever of the two settings is more restrictive. I guess we would get that today for free if we just have Deployment use /eviction subresource. My concern is just that the user experience could be confusing in the case where PDB is more restrictive -- they explicitly set maxUnavailable but then some other value is what is being enforced.

(There is one other issue to think about: Deployment has a minReadySeconds whereas PDB does not.)

**Comment by kargakis** [comment]
> (There is one other issue to think about: Deployment has a minReadySeconds whereas PDB does not.)

Exactly, we can't use PDB with Deployments unless we move minReadySeconds in pods (I hope to get at this soon-ish).

**Comment by kargakis** [comment]
> Exactly, we can't use PDB with Deployments unless we move minReadySeconds in pods (I hope to get at this soon-ish).

I've got https://github.com/kubernetes/community/issues/194 up for review (proposal for adding minReadySeconds to pods) and I have a preliminary buggy working implementation of it locally but the concerns raised by @thockin regarding the ready condition being ambiguous already got me thinking of following the simplest solution possible. The PDB controller already fetches all Deployments/RS/RC, it can easily check if they use MinReadySeconds and set pods deemed as available. It will need to use a virtual clock in order to avoid clock skew (https://github.com/kubernetes/kubernetes/issues/29229).

**Comment by ethernetdan** [comment]
Moving to 1.7 as late to happen in 1.6. Feel free to switch back if this is incorrect.

**Comment by spiffxp** [comment]
@kubernetes/sig-apps-misc do you want this in v1.7? is this the right sig to own this issue?

**Comment by foxish** [comment]
@stiffxp, this is already merged as of now and tracked in https://github.com/kubernetes/features/issues/285.

**Comment by spiffxp** [comment]
@foxish so should this particular issue be closed?

**Comment by foxish** [comment]
Yes, was waiting on documentation to merge in https://github.com/kubernetes/kubernetes.github.io/pull/3885. Can close if that makes tracking easier.

**Comment by spiffxp** [comment]
ok, thanks... docs are typically linked to feature issues, rather than k/k issues, I'll go ahead and close this out
/assign

**Comment by kargakis** [comment]
> @kubernetes/sig-apps-misc do you want this in v1.7? is this the right sig to own this issue?

FYI, we recently moved ownership of PDB under sig-apps
