### ISSUE TITLE
Add DigitalOcean support to Cloud Providers 

### ISSUE THREAD

**Issue by jmarhee** [kubernetes/kubernetes#34783]
I was unable to locate an efforts/attempts at this in any existing issues (looked for instances of "digitalocean" and "digital ocean" which didn't yield anything seemingly relevant), so I'd like to work to add support for DigitalOcean as a Kubernetes_provider when deploying with kube-up.sh (and kube-down.sh). 

I did work to this effect in the following fork to try to make this happen, based on the Rackspace provider workflow, updated to reflect the DO CoreOS stable image and provider networking:

https://github.com/jmarhee/kubernetes/tree/digitalocean_provider/cluster/digitalocean

As it stands, it just takes in DO_REGION, MASTER_SIZE, NODE_SIZE, DO_CERTS (whether or not to generate self-signed certs for the apiserver; if false, just requires user-provided certs), SSH_KEY_NAME specific to this provider when creating the cluster from the user before running the kube-up script with this provider. As it exists, and after some testing, it creates the cluster, passes validation, generates a working kubeconfig as expected.

**Comment by wardviaene** [comment]
Hi,

I was looking for Digital Ocean support for Kubernetes and bumped into this issue. Are there plans for Kubernetes to merge this into the main distribution? I think more people are going to look into running Kubernetes on DigitalOcean now that they they support Volumes. DigitalOcean Volume support within Kubernetes would also be very useful.

**Comment by wardviaene** [comment]
Hi @jmarhee 

Great work on the kube-up script, I need something similar, so I tried out your script from your fork. I had a few issues with the script:

- You use a lot of $(dirname $0), but this doesn't seem to give me the correct path in my environment, better assign a variable and do a better path lookup at the start of the script. I ended up getting a path like ../digitalocean/digitalocean/... 
- I had the same issue as above with the openssl commands
- The script fails when $SSH_KEY_NAME is not in ~/.ssh. The AWS script creates a new key if no key is present, maybe that's a better approach rather than expecting that the user does all the setup
- Took me some time to figure out NODE_SIZE, and MASTER_SIZE need not just '1' , but '1gb' as argument (or other increments), maybe those should be defaults / should be documented
- This script depends on mc? I don't really want to install mc, and it seems that the mc commands are commented out

I fixed those issues I had in the script, but still there seems to be something wrong with the cloud-init scripts

**Comment by klausenbusk** [comment]
I assume we can close this? DigitalOcean now provide a cloud-controller https://github.com/digitalocean/digitalocean-cloud-controller-manager + there is a digitalocean block storage provisioner (including a flexplugin): https://github.com/kubernetes-incubator/external-storage/tree/master/digitalocean
