### ISSUE TITLE
Dynamic provisioning with Secrets can leak any secret on the system

### ISSUE THREAD

**Issue by jsafrane** [kubernetes/kubernetes#34822]
When a dynamic provisioner (and deleter) needs some credentials to a remote storage appliance (gluster server, Ceph, ...), we use a reference to a Secret instance in `StorageClass.Parameters`.

We also agreed that the StorageClass does not need to exists at the point when a provisioned volume is being deleted, therefore we must pass all information (incl. reference to the Secrets) in annotations of the provisioned PV. So, the PV typically has URL of the remote appliance + pointer to secrets.

Now, anyone who can write PV annotations can steal any secret on the system by forging a PV with URL to a fake storage appliance and pointer to a super secret Secret. When a volume plugin tries to delete the PV, it will read the referenced secret and pass it to the fake storage appliance -> attacker has the secret.

While it's true that the same people who can edit a StorageClass are likely the same people who can annotate a PV, it is MUCH less obvious that annotating a PV is such a security risk to the system. No cluster admin is going to accidentally give a user permission to manage StorageClasses but a cluster admin could certainly give a user the ability to annotate a PV without realizing how dangerous it is.

**Proposal**: for the time being, assume that StorageClass instance **is** available at all times when a deleter might need it.
- We do not need to pass any references via annotations
- If admin deletes a StorageClass, all PVs that should be deleted but can't will enter Failed state with some reasonable message ("Can't find StorageClass xyz"). I.e. admin can find these easily and do something with them (probably manually).

**Long-term**, we should move all these provisioners and deleters to pods in specific namespace(s), where we can give them necessary credentials via usual Secret in the same namespace.

@kubernetes/sig-storage @liggitt @eparis @derekwaynecarr 

I will start filling PRs for affected volume plugins next week.

[for security-sensitive people, this bug/feature is not present in any released Kubernetes, we just need to fix it before 1.5 GA].

**Comment by thockin** [comment]
This is another case of referential integrity (or lack thereof) causing problems. @lavalamp 

To be clear on the problem statement, you talk about annotations because that's how the feature is currently implemented.  Once the annotation for class becomes a real field, is this a problem?  It seems like the root of the problem is allowing users to write to PVs in the first place.  I know upstream ACLing is still not fully baked, but that seems like the "real" solution, no?  @erictune 

As an alternative design, we have finalizers now.  You could set a finalizer on the class for each PV you provision (or each PV with cleanup policy of Delete).  This would prevent the class from being deleted until the PVs were gone.  I don't know that this will scale the say we want, and I am pretty sure we do not want an RMW refcount in there.  @caesarxuchao

**Comment by eparis** [comment]
What happens now is that on provision we copy the secret namespace/name as an annotation onto the `PV`. The reason we do that is so that on de-provision we don't need the `StorageClass` to actually do the de-provision (we still need the secret).

This is suggest we stop copying that information onto the `PV`. If the `StorageClass` or the `Secret` gets deleted you cannot de-provision the `PV`. (Before you only failed if the `Secret` was deleted).

**Comment by saad-ali** [comment]
> This is suggest we stop copying that information onto the PV. If the StorageClass or the Secret gets deleted you cannot de-provision the PV. (Before you only failed if the Secret was deleted).

Although removing the reference to the secret from the PV annotation doesn't fix the main vulnerability: instead of "anyone who can write PV annotations" it is "anyone who can write a StorageClass object and a PVC object"... "can steal any secret on the system...". Since, the existing solution is really bad, and this slightly improves the situation, FWIW, I'm ok with this change. @thockin's idea of having a finalizer on the StorageClass that prevents deletion until the provisioned PV would be a good way to prevent the drawback of not having the secret info in the PV object.

That said, I'll defer final decision to @thockin.

**Comment by thockin** [comment]
I'm wary of abusing finalizers just yet.  It's not clear that this is
really going to be what we want.  I think I am OK to trigger an error in
case of StorageClass going away.

OTOH, writing to a PV's annotations is a pretty high level of privilege.

@erictune @matchstick for any ideas

**Comment by eparis** [comment]
I restate my position that: `No cluster admin is going to accidentally give a user permission to manage StorageClasses but a cluster admin could certainly give a user the ability to annotate a PV without realizing how dangerous it is.`

I'm fine with the system being unable to de-provision a PV if the admin deleted the storage class. We can work in the future to try to keep the storage class from getting deleted. But we also have to work to keep the secret from getting deleted before any of that actually matters...

**Comment by liggitt** [comment]
To further scope down the targeting ability, https://github.com/kubernetes/kubernetes/pull/35675 makes the 3 provisioners that look up secrets (rbd, gluster, quobyte) require a secret type matching the volume plugin name (when looking up across namespaces for a PV provision). That at least requires the creator of the secret to have intended the secret to be used with that volume type.
