### ISSUE TITLE
API uses body in DELETE requests

### ISSUE THREAD

**Issue by bdbauer** [kubernetes/kubernetes#34856]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

When deleting a pod using DeleteOptions, we use a DELETE http request, but require a body. This is generally a bad idea. It seems like DeleteOptions should become a query parameter, rather than a body parameter.

cc: @maisem @lavalamp @krousey @kubernetes/sig-api-machinery

**Comment by maisem** [comment]
cc @davidopp

**Comment by krousey** [comment]
Just adding info.. quoting https://tools.ietf.org/html/rfc2616#section-4.3

>A message-body MUST NOT be included in
   a request if the specification of the request method (section 5.1.1)
   does not allow sending an entity-body in requests. A server SHOULD
   read and forward a message-body on any request; if the request method
   does not include defined semantics for an entity-body, then the
   message-body SHOULD be ignored when handling the request.

and https://tools.ietf.org/html/rfc2616#section-9.7 does not define any semantics for an entity-body on DELETE.

**Comment by smarterclayton** [comment]
Are you reporting this because you're broken somewhere or have seen it
broken?  I'm not aware of any HTTP client, proxy, or server that has an
issue with this.  DELETE is not required to not take a body as krousey
notes.

**Comment by krousey** [comment]
@smarterclayton It is an actual problem we're hitting with an internal proxy.

**Comment by smarterclayton** [comment]
Wow, I've dealt with every crazy proxy in enterprise software I can imagine
and none of them have thrown up yet.  Google having the problem surprises
me :)

I don't see any reason not to also accept query parameters if a body is not
present (we have to take the body if provided for backwards
compatibility).  Are you proposing to patch older versions of Kube if we do
change to support this as well?  How far back would you go?

**Comment by roberthbailey** [comment]
We'd like to see 1.4 patched.

**Comment by maisem** [comment]
@roberthbailey beat me to the reply. Yeah we only care about fixing this in v1.4+.

**Comment by smarterclayton** [comment]
The problem being that clients would have to send both to work with all
servers, but that that would break your internal proxy, so you'd need to
switch to sending query params, which means graceful deletion would be
broken from a kubectl 1.4 against 1.3?

**Comment by roberthbailey** [comment]
Clients don't have to work with all servers, just +/- 1 version. So a 1.4 client should work with 1.3, 1.4, and 1.5. 

Since you said that the server would accept both, why do we need to change the client at all?

**Comment by roberthbailey** [comment]
(or rather, we could change the client at head, and then remove the body handling in the server once we get to k8s 1.7 or so)

**Comment by smarterclayton** [comment]
A 1.4 client that sends query params wouldn't be able to talk to a 1.3
server, unless I miss your point.

**Comment by maisem** [comment]
If we only change the 1.4 and 1.5 servers to accept both.
We change the 1.5 client to use query parameters.
We change 1.6 to only accept query parameters (not accept body).

**Comment by roberthbailey** [comment]
What @maisem said -- I don't think we should back-port the client changes. But we should back-port the server changes to accept either query parameters or a body.

**Comment by smarterclayton** [comment]
I'm fine with that.  The relevant check is pkg/apiserver/resthandler.go
DeleteResource to add an else for "if len(body) > 0" - use the equivalent
logic from GetResource with:

opts := api.DeleteOptions{}
if err := scope.ParameterCodec.DecodeParameters(req.Request.URL.Query(),
scope.Kind.GroupVersion(), &opts); err != nil {
scope.err(err, res.ResponseWriter, req.Request)
return
}

and that should be everything you need.

**Comment by davidopp** [comment]
cc/ @mml

**Comment by roberthbailey** [comment]
@bdbauer - can you take a crack at fixing this given's @smarterclayton's suggestions above?

**Comment by krousey** [comment]
Re-opening as this is not fully fixed. Clients still send bodies. We need to make client changes so that they use query parameters.

**Comment by mml** [comment]
@krousey which clients?

**Comment by krousey** [comment]
Sorry. Our generated client. Here: https://github.com/kubernetes/kubernetes/blob/master/pkg/client/clientset_generated/clientset/typed/core/v1/pod.go#L109

**Comment by caesarxuchao** [comment]
It's not working for DeleteOptions.PropagationPolicy.

```
I0316 16:49:12.003939   30640 round_trippers.go:417] DELETE http://localhost:8080/api/v1/namespaces/default/replicationcontrollers/redis?propagationPolicy=Orphan 500 Internal Server Error in 2 milliseconds
I0316 16:49:12.004002   30640 round_trippers.go:423] Response Headers:
I0316 16:49:12.004028   30640 round_trippers.go:426]     Content-Type: application/json
I0316 16:49:12.004050   30640 round_trippers.go:426]     Date: Thu, 16 Mar 2017 23:49:12 GMT
I0316 16:49:12.004071   30640 round_trippers.go:426]     Content-Length: 284
I0316 16:49:12.004176   30640 request.go:991] Response Body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"converting (url.Values).[]string.[]string to (v1.DeleteOptions).*v1.DeletionPropagation.v1.DeletionPropagation: couldn't copy '[]string' into 'v1.DeletionPropagation'; didn't understand types","code":500}
I0316 16:49:12.004855   30640 helpers.go:206] server response object: [{
  "metadata": {},
  "status": "Failure",
  "message": "converting (url.Values).[]string.[]string to (v1.DeleteOptions).*v1.DeletionPropagation.v1.DeletionPropagation: couldn't copy '[]string' into 'v1.DeletionPropagation'; didn't understand types",
  "code": 500
}]
```

Looks like a bug with the parameter codec.

**Comment by smarterclayton** [comment]
Beyond that, we can't change the client because it would be incompatible
with old servers that don't support query parameters?

On Mar 16, 2017, at 7:54 PM, Chao Xu <notifications@github.com> wrote:

It's not working for DeleteOptions.PropagationPolicy.

I0316 16:49:12.003939   30640 round_trippers.go:417] DELETE
http://localhost:8080/api/v1/namespaces/default/replicationcontrollers/redis?propagationPolicy=Orphan
500 Internal Server Error in 2 milliseconds
I0316 16:49:12.004002   30640 round_trippers.go:423] Response Headers:
I0316 16:49:12.004028   30640 round_trippers.go:426]     Content-Type:
application/json
I0316 16:49:12.004050   30640 round_trippers.go:426]     Date: Thu, 16
Mar 2017 23:49:12 GMT
I0316 16:49:12.004071   30640 round_trippers.go:426]     Content-Length: 284
I0316 16:49:12.004176   30640 request.go:991] Response Body:
{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"converting
(url.Values).[]string.[]string to
(v1.DeleteOptions).*v1.DeletionPropagation.v1.DeletionPropagation:
couldn't copy '[]string' into 'v1.DeletionPropagation'; didn't
understand types","code":500}
I0316 16:49:12.004855   30640 helpers.go:206] server response object: [{
  "metadata": {},
  "status": "Failure",
  "message": "converting (url.Values).[]string.[]string to
(v1.DeleteOptions).*v1.DeletionPropagation.v1.DeletionPropagation:
couldn't copy '[]string' into 'v1.DeletionPropagation'; didn't
understand types",
  "code": 500
}]

Looks like a bug with the parameter codec.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/34856#issuecomment-287227594>,
or mute the thread

**Comment by caesarxuchao** [comment]
We can change the client in 1.7, since 1.7 client only have to be compatible with 1.6-1.8 server.

**Comment by smarterclayton** [comment]
I'm pretty hesitant to apply that to clients (not kubectl) that may be
used generically.  "This client only works on servers released in the
last half year" is a pretty terrible experience.

We could consider having the client retry specifically for that error
code and retry with query params - but that's very very specific to
Kube and I don't necessarily feel comfortable about that.

When we introduce delete preconditions I'm pretty sure that we would
have preconditions that exceed url length too.

I don't see a ton of other options, but "have a better http proxy" is
one of them.

**Comment by krousey** [comment]
The server side change made it in 1.5 (and I actually think it was cherry-picked into a 1.4 patch release). We only guarantee client compatibility one minor revision in either direction. This could be in 1.6 (probably too late now).

**Comment by smarterclayton** [comment]
We have never really made a statement about client library.  And I'm not
sure I agree with it in this case.  Our policy is the minimum, not the
maximum.

On Mar 17, 2017, at 2:59 AM, krousey <notifications@github.com> wrote:

The server side change made it in 1.5 (and I actually think it was
cherry-picked into a 1.4 patch release). We only guarantee client
compatibility one minor revision in either direction. This could be in 1.6
(probably too late now).

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/34856#issuecomment-287281630>,
or mute the thread

**Comment by krousey** [comment]
We actually did make a [statement](https://github.com/kubernetes/community/blob/854e9518703851ec79e26a47d46a0c70d829fe37/contributors/design-proposals/versioning.md#supported-releases-and-component-skew) about clients:

> Different components are expected to be compatible across different amounts of skew, all relative to the master version. Nodes may lag masters components by up to two minor versions but should be at a version no newer than the master; a client should be skewed no more than one minor version from the master, but may lead the master by up to one minor version. For example, a v1.3 master should work with v1.1, v1.2, and v1.3 nodes, and should work with v1.2, v1.3, and v1.4 clients.

We added that particular wording in [1.3](https://github.com/kubernetes/kubernetes/blob/release-1.3/docs/design/versioning.md#supported-releases-and-component-skew)

And yes it is a minimum. I would like to move towards a spec compliant client. What version do you think it would be ok to make this switch? 1.8? 1.9?

**Comment by caesarxuchao** [comment]
@bdbauer could you help debug https://github.com/kubernetes/kubernetes/issues/34856#issuecomment-287227594?

**Comment by smarterclayton** [comment]
That's "internal clients" (we wrote that thinking about kubectl or
kubelet), I don't see that as sufficient doc to imply "the client go
library is now broken".

We have a real problem anyway - the body is where we push large chunks of
data.  If we need more preconditions on delete, or choose to include other
structured data, we run a real chance of running out of http header space.
I'm not willing to say body shouldn't be used at all without a better plan
for the future of delete.


On Mar 17, 2017, at 11:05 AM, krousey <notifications@github.com> wrote:

We actually did make a statement
<https://github.com/kubernetes/community/blob/854e9518703851ec79e26a47d46a0c70d829fe37/contributors/design-proposals/versioning.md#supported-releases-and-component-skew>
about clients:

Different components are expected to be compatible across different amounts
of skew, all relative to the master version. Nodes may lag masters
components by up to two minor versions but should be at a version no newer
than the master; a client should be skewed no more than one minor version
from the master, but may lead the master by up to one minor version. For
example, a v1.3 master should work with v1.1, v1.2, and v1.3 nodes, and
should work with v1.2, v1.3, and v1.4 clients.

We added that particular wording in 1.3
<https://github.com/kubernetes/kubernetes/blob/release-1.3/docs/design/versioning.md#supported-releases-and-component-skew>

And yes it is a minimum. I would like to move towards a spec compliant
client. What version do you think it would be ok to make this switch? 1.8?
1.9?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/34856#issuecomment-287379319>,
or mute the thread

**Comment by optimality** [comment]
This is an issue for me.  I'm working on a C++ Kube client.  None of the HTTP libraries I've considered using so far support bodies on DELETE ([restclient-cpp](http://code.mrtazz.com/restclient-cpp/) and [cpp-netlib](http://cpp-netlib.org/), the latter of which I think is a pretty popular standard library, for example).  I suspect it's because they all use libcurl under the hood, and libcurl doesn't allow it.  You *can* do it with bare libcurl, but you have to set the request type to "custom" - the standard delete request doesn't allow it.

I think Kubernetes is definitely going against the grain here.  I understand that you're concerned about HTTP header space, and I don't have a great solution to that.  One idea would be to do a POST to a special `/delete` URI if you need a bulky DELETE.  It's also an abuse of the REST metaphor, but it seems like less of one than sending undefined bodies.

**Comment by lavalamp** [comment]
@k8s-ci-robot oh yeah?

**Comment by seeb0h** [comment]
Same as @caesarxuchao. 
`propagationPolicy`  is not working with this query: `https://my-ip/apis/batch/v1/namespaces/default/jobs/downloading-inputs-5694510977777664?propagationPolicy=Background`

```


{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "converting (url.Values).[]string.[]string to (v1.DeleteOptions).*v1.DeletionPropagation.v1.DeletionPropagation: couldn't copy '[]string' into 'v1.DeletionPropagation'; didn't understand types",
  "reason": "BadRequest",
  "code": 400
}
```

version 1.10.5-gke.0 (Google Cloud)
