### ISSUE TITLE
kube-scheduler and kube-controllermanager not coming up in 1.4.1 with --kubeconfig option

### ISSUE THREAD

**Issue by praoreo** [kubernetes/kubernetes#34897]
Hi,

I am trying to upgrade my lab from kubernetes 1.3.6 to 1.4.1. After copying the latest kube-scheduler and kube-controllermanager binary I am not able to start the process as it says "unable to build config from flags: invalid configuration: no configuration has been provided"

```
root# /opt/bin/kube-scheduler --logtostderr=true --leader-elect=true --kubeconfig=/var/lib/kube-scheduler/kubeconfig/config
E1013 12:47:37.395646   39876 server.go:79] unable to build config from flags: invalid configuration: no configuration has been provided
root#
```

```
root# /opt/bin/kube-controller-manager --logtostderr=true --leader-elect=true --kubeconfig=/var/lib/kube-controller-manager/config --node-monitor-period=1s --node-monitor-grace-period=5s --pod-eviction-timeout=50ms
invalid configuration: no configuration has been provided
```

I have a valid kubeconfig file at "/var/lib/kube-scheduler/kubeconfig/config" and "/var/lib/kube-controller-manager/config". Also, the same was working fine using 1.3.6 binaries.

Following commands were used to generate the kubeconfig

```
./kubectl config set-cluster mykubecluster --server=https://<IP>:8081 --insecure-skip-tls-verify=true
 ./kubectl config unset clusters
 ./kubectl config set-cluster mykubecluster --certificate-authority=<Path>/ca.crt --embed-certs=true --server=https:// <IP>:8081
```

Is this a known issue in latest release? Is their any work around for the same?

**Comment by praoreo** [comment]
@lavalamp - Have you seen this issue in 1.4.1 release? Any pointers on how to resolve the issue?

**Comment by lavalamp** [comment]
This is probably an issue with your particular setup. You may want to ask this question in a better forum (and post your kubeconfig file when you do).

---

Please re-post your question to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases.

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to similar questions, and also familiarize yourself with:
   * [the user guide](http://kubernetes.io/v1.0/)
   * [the troubleshooting guide](http://kubernetes.io/v1.0/docs/troubleshooting.html)

Again, thanks for using Kubernetes.

The Kubernetes Team
