### ISSUE TITLE
kubeadm doesn't work on GCE

### ISSUE THREAD

**Issue by craigbox** [kubernetes/kubernetes#34949]
The [getting started guide for kubeadm](http://kubernetes.io/docs/getting-started-guides/kubeadm/) assumes you will use a CNI plugin, and kube-dns will crash-loop until you have one installed.

If you are on GCE, you shouldn't need a CNI plugin; you should be able to use kubenet, but kubeadm today only supports add-on networks.

**Comment by errordeveloper** [comment]
It is possible to enable kubenet.

If you take a look at `/etc/systemd/system/kubelet.service.d/10-kubeadm.conf`, you will see:
```
Environment="KUBELET_NETWORK_ARGS=--network-plugin=cni --cni-conf-dir=/etc/cni/net.d --cni-bin-dir=/opt/cni/bin"
```
So this means that you can do the following:
```
printf '[Service]\nEnvironment="KUBELET_NETWORK_ARGS=--network-plugin=kubenet"\n' > /etc/systemd/system/kubelet.service.d/20-kubenet.conf
```
I haven't tested this, but it should work in theory.

**Comment by mikedanese** [comment]
Let us know if that does work @craigbox

**Comment by dstiliadis** [comment]
Just tested this and it seems work. On the nodes make sure you create cbr0 first according to the instructions http://kubernetes.io/docs/getting-started-guides/scratch/

**Comment by dstiliadis** [comment]
Just tested this and it seems work. On the nodes make sure you create cbr0 first according to the instructions http://kubernetes.io/docs/getting-started-guides/scratch/

**Comment by mikedanese** [comment]
I don't think that's actually necessary anymore. Kubelet will do that for you.

**Comment by dstiliadis** [comment]
To be more accurate the way I got it working (and kube-dns to actually come up) is by using this in the master: 

printf '[Service]\nEnvironment="KUBELET_NETWORK_ARGS=--network-plugin=kubenet --reconcile-cidr --pod-cidr=10.20.0.0/24"\n' > /etc/systemd/system/kubelet.service.d/20-kubenet.conf

I believe this is because of #32900  

Note: this is a bare metal setup, where subnet/host is handled in the network.
