### ISSUE TITLE
Add dump command to kubectl 

### ISSUE THREAD

**Issue by dchen1107** [kubernetes/kubernetes#3500]
When a user report an issue on Kubernetes, we normally ask them to provide some outputs by running kubectl commands, such as kubectl get <resource>, kubectl describe <resource> etc. We ask for daemons' log from various nodes often. Sometimes the user has to reproduce the issue for us because the config is changed. Meanwhile the developer might spend a lot of time on debugging the issues on a deprecated version or mismatched client with server. 

I propose to add a dump command to kubectl, which collects related outputs, logs, from various components or related nodes, then generate a tarball and attach that to the issue.

**Comment by dchen1107** [comment]
cc @lavalamp @brendandburns @thockin

**Comment by davidopp** [comment]
This seems very useful. It could be the starting point for a more comprehensive diagnose-me that the user runs when they see a problem.

**Comment by satnam6502** [comment]
For a while now the kubelet logs have been collected by node level logging. For Elasticsearch the user needs to enable cluster level logging (on by default for Elasticsearch node level logging). For gcp node level logging the kubelet logs will have been ingested into the cloud logging console for the GCE project used to host the cluster.

**Comment by dchen1107** [comment]
cc/ @jszczepkowski   @piosz

They are going to help with this issue. Thanks!

**Comment by jszczepkowski** [comment]
I guess this issue is not closed yet (it was incorrectly closed by keyword in PR message).

**Comment by jszczepkowski** [comment]
Together with @piosz, we propose to dump the following information: 

1. Kubernetes level: description of all kubernetes resources: nodes, replication controllers, services, pods: 
    kubectl get nodes,podes,rc,services,events -o json,
2. Docker level: docker processes and images on each master/minion node:
    docker ps -a,
    docker images.
3. Etcd level: version of etcd and boundpods stored in it:
    etcd --version,
    etcdctl get boundpods.
4. (may consume a lot of space): the whole state (dump) of etcd.
5. (may consume a lot of space): logs of the following components: kubelet, docker, etcd, kube-apiserver and kube-addons.

The information will be dump by hack/kube-dump.sh script. The current version of the script (PR #4346) implements point 1, 2 and 3.

We suggest extending the kube-dump.sh by adding of the following flags:
  --all: dump etcd state and logs: in addition to points 1, 2 and 3, also dump information proposed in pointes 4 and 5 (this may consume a lot of space);
  --issue=XXX: instead of writing output to stdout, make a tarball and attach it to #XXX issue on kubernetes github.

**Comment by bgrant0607** [comment]
Proposed command is `kubectl cluster-info dump` (turning cluster-info into a command group).

**Comment by dims** [comment]
@brendandburns @bgrant0607 - Is there anything else needed to be done in this PR? (can it be closed?)

**Comment by bgrant0607** [comment]
@dims The original proposal wasn't fully implemented, but a new more specific issue can be filed to record additional data.

**Comment by dchen1107** [comment]
cc/ @coufon
