### ISSUE TITLE
[Request] Labeling spot instances / preemptible instances as such.

### ISSUE THREAD

**Issue by jason-riddle** [kubernetes/kubernetes#35166]
I don't believe this exists, but it would be nice if AWS spot instances / GCE preemptible instances are labeled (or annotated) with 'preemptible'. I ask because if you want to schedule a job, you probably don't want to schedule on a node that can die at any minute. I know I could manually create the label, but it would be nice if kubernetes were smart enough to figure it out using the metadata api.

**Comment by justinsb** [comment]
If you're using kops, you can apply k8s labels at the instance group level.

But I agree there should probably be a standard annotation / label / taint.  Any thoughts @davidopp @bgrant0607

**Comment by bgrant0607** [comment]
@justinsb A taint makes sense, but we'll need to create a way to automatically add tolerations. (#17097)

**Comment by davidopp** [comment]
As @bgrant0607 alludes to, the downside of using a taint instead is that then users would have to  add tolerations to use these nodes (either manually or using some kind of defaulter/admission controller that they create or add rules to). It would be bad to default to adding taints for spot/preemptible nodes because then a user who isn't aware of this behavior might spin up a cluster and find none of their pods schedule and not understand why.

Automatically adding labels is fine; in fact we [already do that in GKE](https://cloud.google.com/container-engine/docs/preemptible-vm).

I think the only reasonable way to add taints for spot/preemptible is to make it an explicit option of the cluster deployment tool (defaulting to not doing it). If the user specifically requests it, then it's safe to assume they know what they are getting into and will create the necessary tolerations one way or another.

**Comment by bgrant0607** [comment]
Ref #17151, #17190, #21566, #30302

**Comment by timothysc** [comment]
I'm not really a fan of the taints idea, although possible.  

Most often use cases for spot instances that I've come across are typically opportunistic batch jobs. But I'm certain each group of folks, might have their own reasons.  

This is where customization might come into play, to extend your scheduler with your own logic.
