### ISSUE TITLE
Pod or Job lifecycle lacks of a mechanism to define cleanup actions once you delete a pod

### ISSUE THREAD

**Issue by hectorj2f** [kubernetes/kubernetes#35183]
Our user story for a FEATURE REQUEST is the following: we have been developing distributed applications using systemd during long time. To coordinate them, we used fleet as distributed system to manage them all in our infra. However, we decided to move all our systems to Kubernetes since several months.

Regardless of all the amazing features you can find in Kubernetes when defining applications. We are missing a good one, we had when creating systemd units. 
-  A mechanism to trigger deletion actions (cleanup tasks) once we delete a pod. e.g ExecStop, ExecStopPost instructions used to trigger actions when destroying or stopping a systemd unit.

We research among all the features and we couldn't find any available mechanism to trigger delete-or-cleanup actions. As an example, I have a pod that does some stuff (like adding a key to etcd, setting some iptable rules) when I delete the pod k8s doesn't provide a way to trigger an action (like removing the key from etcd, cleaning up all the iptable rules). So, we have to create some additional pods that do the jobs which is ugly from an app lifecycle definition.

Therefore, I'd like to know or learn if there would be any possibility to get this functionality inside kubernetes. Also, if you know of any third party project trying to achieve the same goal, it'd be really helpful for us.

**Comment by pires** [comment]
@hectorj2f did you look at [Termination of Pods](http://kubernetes.io/docs/user-guide/pods/#termination-of-pods), particularly [step 5](http://kubernetes.io/docs/user-guide/container-environment/#hook-details)?

**Comment by bgrant0607** [comment]
cc @smarterclayton

**Comment by smarterclayton** [comment]
We've hit this when looking at how to do image builds using a container.  Ideally, we'd run a container in the pod to set the image state, then commit and push that image in a follow on.  But it requires a more complex lifecycle than our current flow.  We had concerns about adding post-containers or post stop hooks when we discussed init containers.

**Comment by hectorj2f** [comment]
@smarterclayton Which are those concerns ? 

With the current lifecycle either, you increase the container functionality to cleanup itself when calling the `PreStop` operation of the pod lifecycle (this is quite ugly when those operations aren't related to the container logic :/ ); OR you have to hack some pods to be scheduled once you run a delete operation to do the cleanup. Both alternative are a bit ugly in my opinion. 

What is it the blocker of this new feature for the pod lifecycle ? 

@smarterclayton I'd like to help if it is necessary to push this issue.

**Comment by kargakis** [comment]
Lifecycle hooks for different objects (eg. Deployments) discussed elsewhere:
https://github.com/kubernetes/kubernetes/issues/140
https://github.com/kubernetes/kubernetes/issues/3585
https://github.com/kubernetes/kubernetes/issues/14512

Also custom strategies are related to this -  having the ability to customize the lifecycle of X means you can add your own hooks anywhere you want in the process. See https://github.com/kubernetes/kubernetes/pull/33545#issuecomment-252139205 for more information.

cc: @mfojtik @soltysh

**Comment by kargakis** [comment]
@kubernetes/sig-apps

**Comment by kow3ns** [comment]
It sounds like what you are looking for is analogous to an [init cotainer](http://kubernetes.io/docs/user-guide/pods/init-container/) except that it runs after the pod is shutdown. Would a feature like this, lets call it a de-init container, be suitable to your requirements?

**Comment by hectorj2f** [comment]
I think that having something similar to init-containers to be launched when the pod is terminated. It could make sense.

**Comment by smarterclayton** [comment]
We had hesitations around adding finalizing containers when designing init
containers.  Allowing long strings of finalizers adds an additional state
machine component to the pod that is new (and hard to make backwards
compatible).  There is also a serious desire to avoid anything close to a
graph of tasks.

Use case wise, I've heard:

1. Release resources acquired during init (global locks, API registration)
2. Upload contents from shared volumes (job logs, build artifacts)
3. Commit one of the app containers and push it (image build)
4. Signal job finalization to arbitrary entities.

So "outputs" and "signal", primarily.  What others are relevant?  There's
also the case that the caller might want more info from the pods.  What
guarantees are required for these use cases?


Slightly deeper thought:

Could we translate this into a container that receives a hook execution /
signal when all other containers terminate?

Pod
  Spec
    Containers
    - OnShutdown:
        Exec /bin/cleanup.sh
        (LifecycleHook)

Adding a new post container could be unnecessary if a lifecycle hook was
sufficient, although this does seem to fall afoul of the "no graph concepts
of tasks" rules



On Dec 15, 2016, at 5:24 PM, Hector Fernandez <notifications@github.com>
wrote:

I think that having something similar to init-containers to be launched
when the pod is terminated. It could make sense.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/35183#issuecomment-267462313>,
or mute the thread

**Comment by hectorj2f** [comment]
I understand that adding `destroy-containers` for a deployment, might imply to add a new state in the workflow. If it is necessary I won't see the problem but I understand your concerns about it.

```
Pod
  Spec
    Containers
    - OnShutdown:
        Exec /bin/cleanup.sh
        (LifecycleHook)
```

On the other hand, if we add a hook when deleting a deployment, my main concern is to able to use containers that are different than the containers that run in the Pod of the deployment as an example. If so, I'd be happy with your approach but I believe with your solution. We aren't able to run any logic which is outside of the own container like it happens with the current Termination hooks. 

Doing so, it'd require to: 
- Add additional logic to the containers that run in the pods to be able to clean themselves and whatever their `init-container` did. 
- Add a new hook `postStop` cause `preStop` might limit the cleanup operations to be triggered in multiple case scenarios.

**Comment by pigmej** [comment]
I can imagine some complications around that area. 

How are we going to solve this problem:
- user defines cleanup action (whatever we will call it)
- node with a pod is down, therefore pod will be not able to call cleanup action
- user want to delete pod from k8s system
It's obvious that then pod hooks weren't be executed, but then we will have 2 different behavior of the same.

Second problem:
- user defines cleanup action
- it crashes
  - should we proceed with pod delete
  - or maybe instead retry cleanup action? (how many times?)
- what if cleanup can't succeed because of some conditions (`delete -f` ?)

**Comment by dhilipkumars** [comment]
https://github.com/kubernetes/community/pull/483

**Comment by bboreham** [comment]
I have basically the same requirement, but for DaemonSet: I work on [Weave Net](https://www.weave.works/documentation/net-latest-kube-addon/) which installs itself on every node via a DaemonSet.  The install creates some side-effects on each node - network virtual devices, etc. - that a user would like to clear down if they decide to uninstall.

Users variously expect this to happen via `kubectl delete` or `kubeadm reset`, but currently there is no hook to run some uninstall code on each node.

@pigmej makes some good points, but it seems to me that users would understand that the code made some efforts to clean up, rather than no effort at all at present.

**Comment by cheburakshu** [comment]
@bboreham `kubeadm reset` can be run individually on nodes. It is a common cleanup command for both as per [this](https://github.com/kubernetes/kubeadm/issues/42), but this does not delete the network interfaces as one would expect. One thing I observed is even after doing the `kubeadm reset` on the node, the master listed it as running. I don't know if it was because of the un-deleted network.

**Comment by bboreham** [comment]
> master listed it as running. I don't know if it was because of the un-deleted network.

No.  It is because the code to remove a node was removed in #42713, @cheburakshu

**Comment by cheburakshu** [comment]
@bboreham Will the master still schedule the node since it sees it? In my experience it did and the pod was in a pending state. Is it a correct behaviour?

**Comment by bboreham** [comment]
@cheburakshu I dare say it will; however that is off-topic for this issue. Per #42713 the system administrator has to remove the node. Suggest you open an issue against kubeadm if this doesn't suit.

**Comment by tgraf** [comment]
> I have basically the same requirement, but for DaemonSet: I work on Weave Net which installs itself on every node via a DaemonSet. The install creates some side-effects on each node - network virtual devices, etc. - that a user would like to clear down if they decide to uninstall.

I have the same requirement. CNI plugins typically install files (binaries & a config file in `/etc/cni/net.d/`) in the host filesystem when the managing pod is first started as a `DaemonSet`.

 I'm doing the installing part using a `PostStart` hook. Ideally I could clean up (remove both binaries and config files) as the pod is removed from the node. I looked into using a `PreStop` hook for the cleanup but the hook is run *after* the volumes are being unmounted in the namespace which means I can no longer remove binaries and configfiles in the host filesystem directories which are mapped into the namespace using volumes.

A naive thought is to consider a `PreUnmount` hook which would run before volume unmounting takes places.

**Comment by tgraf** [comment]
> In case this is not guaranteed, a naive thought is to consider a PreUnmount hook which would run before volume unmounting takes places.

Confirmed that this is not guaranteed. I sleep in the `PreStop` hook for 60 seconds and then attempt delete files on mounted volumes they will not be deleted as the volume has already been unmounted.

**Comment by dhilipkumars** [comment]
Hi @bboreham, @tgraf , @cheburakshu, could you please take a look at this proposal and provide more feedback it appears to me that we could achieve these using  [deferContainers](https://github.com/kubernetes/community/pull/483), this will not only allow us to isolate termination scripts from the main image but also provide more guarantee and control than preStop hooks.

**Comment by bboreham** [comment]
@dhillipkumars I couldn't see how that would allow me to know that the entire DaemonSet is being deleted.  Conversely I don't seem to need additional isolation.

**Comment by dhilipkumars** [comment]
@bboreham hmmm... you may probably need [this one](https://github.com/kubernetes/community/pull/541) too to precisely know why the pod is being brought down.

**Comment by bboreham** [comment]
How about using a finalizer?

In the case of a Pod, it would need permission to write to its own object, which is unorthodox.

In the case of a DaemonSet the pods could all add themselves as finalizers to the DaemonSet, but that gets out of hand at scale. Add another pod to coordinate shutdown (an operator, if you like), it feels like it could work.

**Comment by juan-chan** [comment]
Any update? I have the similar requirement now. I want a hook to do something when a job is deleted (or a pod is terminated). I tried to use the `preStop` hook, but it didn't work when I try to delete my jobs in a cron-job.

**Comment by krmayankk** [comment]
this proposal https://github.com/kubernetes/enhancements/pull/1995 seems to handling this use case, please review it and see if that is in the right direction as per this issue

**Comment by bboreham** [comment]
@krmayankk can you point more precisely to how https://github.com/kubernetes/enhancements/pull/1995 would notify when a pod, deployment, daemonset, etc., is being deleted?

I think it could be extended to cover the case described here, by defining system-triggered notifications, but all I can see in the proposal as it stands is user-triggered.

**Comment by thockin** [comment]
I don't think we're going to implement  new "do this when a pod is deleted" hooks in the core system any time soon.  https://github.com/kubernetes/enhancements/pull/1995 is not what you want here, it's what bboreham described - user-triggered.  If someone wants to think up a general event-integration, it should at least start as an out-of core implementation.
