### ISSUE TITLE
When OutOfDisk daemonset pods are deleted from node

### ISSUE THREAD

**Issue by germansosa** [kubernetes/kubernetes#35228]
When a node reach OutOfDisk state, running pods from all daemonsets are deleted from node, this is a big problem when we have critial pods running in daemonsets, like network agents, ingress controllers or log collectors.

State of daemonset before OutOfDisk in node:

```
$ kubectl describe no v1107udesa.int.cmd.com.ar | grep OutOfDisk
  OutOfDisk             False   Thu, 20 Oct 2016 16:23:42 -0300         Thu, 20 Oct 2016 13:43:53 -0300         KubeletHasSufficientDisk        kubelet has sufficient disk space available
$ kubectl describe ds fluentd --namespace=kube-system
Name:           fluentd
Image(s):       gcr.io/google_containers/fluentd-elasticsearch:1.19
Selector:       name=fluentd
Node-Selector:  <none>
Labels:         kubernetes.io/cluster-service=true
Desired Number of Nodes Scheduled: 3
Current Number of Nodes Scheduled: 3
Number of Nodes Misscheduled: 0
Pods Status:    3 Running / 0 Waiting / 0 Succeeded / 0 Failed
```

After OutOfDisk:

```
$ kubectl describe no v1107udesa.int.cmd.com.ar | grep OutOfDisk
  OutOfDisk             True    Thu, 20 Oct 2016 16:26:03 -0300         Thu, 20 Oct 2016 16:24:53 -0300         KubeletOutOfDisk                out of disk space
  1d            2m              145     {kubelet v1107udesa.int.cmd.com.ar}                     Normal          NodeOutOfDisk           Node v1107udesa.int.cmd.com.ar status is now: NodeOutOfDisk
$ kubectl describe ds fluentd --namespace=kube-system
Name:           fluentd
Image(s):       gcr.io/google_containers/fluentd-elasticsearch:1.19
Selector:       name=fluentd
Node-Selector:  <none>
Labels:         kubernetes.io/cluster-service=true
Desired Number of Nodes Scheduled: 2
Current Number of Nodes Scheduled: 2
Number of Nodes Misscheduled: 0
Pods Status:    2 Running / 0 Waiting / 0 Succeeded / 0 Failed
Events:
  FirstSeen     LastSeen        Count   From            SubobjectPath   Type            Reason                  Message
  ---------     --------        -----   ----            -------------   --------        ------                  -------
  1m            1m              1       {daemon-set }                   Normal          SuccessfulDelete        Deleted pod: fluentd-u4vxx
```

**Kubernetes version**:

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.0", GitCommit:"a16c0a7f71a6f93c7e0f222d961f4675cd97a46b", GitTreeState:"clean", BuildDate:"2016-09-26T18:16:57Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.0", GitCommit:"a16c0a7f71a6f93c7e0f222d961f4675cd97a46b", GitTreeState:"clean", BuildDate:"2016-09-26T18:10:32Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: Bare metal
- **OS**:

```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```
- **Kernel** (e.g. `uname -a`):
  Linux v1108udesa.int.cmd.com.ar 3.10.0-327.28.3.el7.x86_64 #1 SMP Thu Aug 18 19:05:49 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
- **Install tools**: Custom
- **Others**:

**What happened**:
When node reach out of disk daemonset pods are deleted from node.

**What you expected to happen**:
Existing pods stay in node, but no new pods will be sheduled.

**How to reproduce it** (as minimally and precisely as possible):
Fill disk in node, reach out of disk condition and daemonsets pods automatically will be deleted from node.

**Comment by lukaszo** [comment]
This is expected behavior (https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/daemon/daemoncontroller.go#L656) but I understand your point.
@davidopp @bgrant0607 are there any plans to make Conditions taints? User would be able to set tolerations for his daemon then.

**Comment by bgrant0607** [comment]
@lukaszo We have discussed representing all sources of disruption/unschedulability, including conditions, as taints. I don't know that anyone is working on this, however.

**Comment by davidopp** [comment]
That's interesting, I hadn't even realized DaemonSet would evict daemons. But the code @lukaszo pointed to seems to do that -- IIUC the path is that the node condition changes to NodeOutOfDisk, which triggers the watch on nodes (dsc.updateNode) which iterates over all the pods and does
`shouldEnqueue := (dsc.nodeShouldRunDaemonPod(oldNode, ds) != dsc.nodeShouldRunDaemonPod(curNode, ds))` so it queues the daemon. Then eventually syncDaemonSet() runs for the daemon which calls manage() for the daemon which ultimately deletes the daemon.

Anyway, as @bgrant0607 alluded to, we will eventually represent node problems like NodeOutOfDisk using taints, and then do the evictions based on the taints. This means daemon pods that want to stay bound to the node can "tolerate" the taint and won't get evicted. We will have alpha support for this just for "node not ready" and "node unreachable" in 1.5, so the earliest we'll have this for the scenario we're talking about here is 1.6.

Before then, I guess we could change the behavior so that if behaves the way you requested, i.e. new daemons won't schedule, but already-running ones will keep running.

@mikedanese WDYT?
