### ISSUE TITLE
kubectl logs --tail=0 is not working properly

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes/kubernetes#35335]
How `docker logs` works:
- `docker logs --tail=-1 CONTAINER_ID`: prints all lines.
- `docker logs --tail=1 CONTAINER_ID`: prints the last line.
- `docker logs --tail=0 CONTAINER_ID`: prints no lines. (Usually used with `-f` to follow new logs)

How `kubectl logs` works:
- `kubectl logs --tail=-1 POD_NAME`: prints all lines.
- `kubectl logs --tail=1 POD_NAME`: prints the last line.
- `kubectl logs --tail=0 POD_NAME`: prints all lines. <-------------- Diffierent.

The reason is that the `tail=0` is ignored when converting the parameters https://github.com/kubernetes/kubernetes/blob/master/pkg/conversion/queryparams/convert.go#L111.

Confirmed with @caesarxuchao.

What is the expected behavior? @smarterclayton 
/cc @kubernetes/sig-api-machinery

**Comment by adambom** [comment]
I've also noticed that even if `--tail=1` or some arbitrarily low number is specified, it tries to read the whole logfile into memory. If it's a big file it can crash the worker node.

**Comment by Random-Liu** [comment]
@adambom I noticed that, so in our own implementation, I've avoided that.
https://github.com/kubernetes/kubernetes/pull/35348

**Comment by smarterclayton** [comment]
Tail should be *int in the API, is it not?

On Oct 21, 2016, at 6:01 PM, Lantao Liu <notifications@github.com> wrote:

How docker logs works:

   - docker logs --tail=-1 CONTAINER_ID: prints all lines.
   - docker logs --tail=1 CONTAINER_ID: prints the last line.
   - docker logs --tail=0 CONTAINER_ID: prints no lines. (Usually used with
   -f to follow new logs)

How kubectl logs works:

   - kubectl logs --tail=-1 POD_NAME: prints all lines.
   - kubectl logs --tail=1 POD_NAME: prints the last line.
   - kubectl logs --tail=0 POD_NAME: prints all lines. <--------------
   Diffierent.

The reason is that the tail=0 is ignored when converting the parameters
https://github.com/kubernetes/kubernetes/blob/master/pkg/conversion/queryparams/convert.go#L111
.

Confirmed with @caesarxuchao <https://github.com/caesarxuchao>.

@smarterclayton <https://github.com/smarterclayton>
/cc @kubernetes/sig-api-machinery
<https://github.com/orgs/kubernetes/teams/sig-api-machinery>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/35335>, or mute the thread

**Comment by smarterclayton** [comment]
Agree tail=0 no logs is intended behavior

On Oct 21, 2016, at 6:01 PM, Lantao Liu <notifications@github.com> wrote:

How docker logs works:

   - docker logs --tail=-1 CONTAINER_ID: prints all lines.
   - docker logs --tail=1 CONTAINER_ID: prints the last line.
   - docker logs --tail=0 CONTAINER_ID: prints no lines. (Usually used with
   -f to follow new logs)

How kubectl logs works:

   - kubectl logs --tail=-1 POD_NAME: prints all lines.
   - kubectl logs --tail=1 POD_NAME: prints the last line.
   - kubectl logs --tail=0 POD_NAME: prints all lines. <--------------
   Diffierent.

The reason is that the tail=0 is ignored when converting the parameters
https://github.com/kubernetes/kubernetes/blob/master/pkg/conversion/queryparams/convert.go#L111
.

Confirmed with @caesarxuchao <https://github.com/caesarxuchao>.

@smarterclayton <https://github.com/smarterclayton>
/cc @kubernetes/sig-api-machinery
<https://github.com/orgs/kubernetes/teams/sig-api-machinery>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/35335>, or mute the thread

**Comment by Random-Liu** [comment]
> Tail should be *int in the API, is it not?

Yeah, tail is `*int`. But if `tail=0`, kubelet will see `TailLines=nil`.

**Comment by caesarxuchao** [comment]
I think the [line](https://github.com/kubernetes/kubernetes/blob/master/pkg/conversion/queryparams/convert.go#L111) @Random-Liu linked to is the problem.
```go
func addParam(values url.Values, tag string, omitempty bool, value reflect.Value) {
	if omitempty && zeroValue(value) { // value is already deferenced for pointer type in the caller
		return
	}
```

**Comment by HaraldNordgren** [comment]
The obvious workaround is to instead use:

    kubectl logs --tail=1

**Comment by smarterclayton** [comment]
The line pasted by chao implies omitempty should not be false for tail.

**Comment by Qix-** [comment]
I hate to bump, but 'bump'. Still an issue here. Can confirm `--tail=1` works but `--tail=0` does not.

**Comment by Qix-** [comment]
/remove-lifecycle stale

This is still relevant.

**Comment by wrfly** [comment]
Any good news?
