### ISSUE TITLE
vSphere kube-up.sh: Add support for flannel

### ISSUE THREAD

**Issue by kerneltime** [kubernetes/kubernetes#35340]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):
NA

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):
## NA

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Feature Request

**Kubernetes version** (use `kubectl version`):
1.3.x 1.4.x master

**Environment**:
- **Cloud provider or hardware configuration**: vSphere
- **OS** (e.g. from /etc/os-release): Linux
- **Kernel** (e.g. `uname -a`): NA
- **Install tools**: kube-up.sh
- **Others**:

**What happened**:
Currently the networking setup when deploying using kube-up is manual and not fleshed out. The routes get setup manually for the CIDR on each node. This has prone to be buggy based on past experience.

**What you expected to happen**:
Use and configure a networking plugin such as flannel or weaveworx

**How to reproduce it** (as minimally and precisely as possible):
use kube-up.sh to deploy on vSphere.

**Anything else do we need to know**:

**Comment by kcrawley** [comment]
I'm working on integrating flanneld into the default vsphere setup for our own organization needs. I intend on opening a PR when I'm done.

**Comment by kerneltime** [comment]
@kcrawley can you share some more details on the changes planned?

**Comment by kcrawley** [comment]
@kerneltime i've been looking at some of the other cluster providers for patterns and I'm not seeing anything that I'm overly fond of. I'd like to use saltstack; but that looks like an excessive amount of work. (as in, my employer would be unhappy with me spending anything more than a day or three on this).

that being said, since we are using debian, i'll likely pull the systemd scripts for etcd/flannel/docker from ubuntu. all of those are fairly straightforward and provide the startup ordering and constraints we need. the provisioning of these would occur at the appropriate time during `master-start.sh` and `node-start-x.sh`. I'd likely put the scripts and configuration templates in the `templates` directory.

it's also worth noting that i found a rather nasty bug in `setup-pod-routes` that i'm about to create an issue and open a PR.

**Comment by kcrawley** [comment]
Given the `deprecation` notice, is it worth taking the time to go ahead and move this project in accordance to the maintainers wishes? I don't mind taking on that project in my spare time - the fix I've mentioned above has solved a major problem I was having (and the entire reason I started researching flanneld)

**Comment by kcrawley** [comment]
Well, it appears the issue was addressed and is awaiting the 1.4 release.

https://github.com/kubernetes/kubernetes/pull/35308/files

**Comment by kerneltime** [comment]
@kcrawley Looks like in master the management of cbr0 is quite a bit different.. what is the most important for you here.. getting 1.4 using flannel or the master?

**Comment by kcrawley** [comment]
I don't want to derail this issue; I believe flannel is the right call here. I'm not on a critical time or anything.

_however_ since the cbr0 bug has been identified, it makes sense for the fix to be merged. i'm a bit confused as to why #35308 is tagged in 1.4, but hasn't been released. is it waiting for the next point release?

**Comment by kerneltime** [comment]
@kcrawley yes, I am hoping that it makes it into 1.4.5 which should be tagged this Friday.
There is another pull request I hope makes it as well https://github.com/kubernetes/kubernetes/pull/35474

**Comment by kcrawley** [comment]
@kerneltime i spent an unnatural amount of time making an attempt at pulling flanneld into the vsphere cluster configuration. i'm not ready to completely give up on it, but in order to make it work we'd need to completely forego our reliance on the saltstack for bootstrapping (or make a lot of changes to the salt stack that the core team would likely be uncomfortable with).

it seems to me that energies would be better spent contributing vsphere to https://github.com/kubernetes/kube-deploy

**Comment by kerneltime** [comment]
We are planning to move to kubernetes-anywhere.
