### ISSUE TITLE
Need validate namespace node-selector when create namespace

### ISSUE THREAD

**Issue by mdshuai** [kubernetes/kubernetes#35505]
**Kubernetes version** (use `kubectl version`):
v1.5.0-alpha.1.857+c81816751387a2-dirty

**What happened**:
Create a namespace with invalid node-selector, it can create successfully

**How to reproduce it** (as minimally and precisely as possible):

```
1. Create a namespace with invalid 
{
    "kind": "Namespace",
    "apiVersion": "v1",
    "metadata": {
        "name": "projectlable",
        "creationTimestamp": null,
        "annotations": {
            "scheduler.alpha.kubernetes.io/node-selector": "region#=xyz%|=|country=china||"
        }
    },
    "spec": {},
    "status": {}
}
# kc create -f ns.yaml
namespace "projectlable" created

2. Create a pod in this namespace
# kc create -f https://raw.githubusercontent.com/mdshuai/testfile-openshift/master/k8s/pod/hello-pod.yaml --namespace=projectlable
Error from server: error when creating "https://raw.githubusercontent.com/mdshuai/testfile-openshift/master/k8s/pod/hello-pod.yaml": invalid selector: [region# xyz%| |country china||]
```

**Expected results**
1. When create namespace with invalid value"scheduler.alpha.kubernetes.io/node-selector" should failed.

**Anything else do we need to know**:

**Comment by mdshuai** [comment]
@aveshagarwal @derekwaynecarr

**Comment by mdshuai** [comment]
also can update "scheduler.alpha.kubernetes.io/node-selector" after create namespace
```
[root@ip-172-18-6-200 podnodeselector]# kubectl patch ns ns1 -p '{"metadata":{"annotations":{"scheduler.alpha.kubernetes.io/node-selector":"env=#=xyz%|=|"}}}'
"ns1" patched
[root@ip-172-18-6-200 podnodeselector]# kc get ns ns1 -o json
{
    "kind": "Namespace",
    "apiVersion": "v1",
    "metadata": {
        "name": "ns1",
        "selfLink": "/api/v1/namespaces/ns1",
        "uid": "bf7b7aa4-9a95-11e6-aac5-0ebd788c9e1f",
        "resourceVersion": "3523",
        "creationTimestamp": "2016-10-25T09:31:03Z",
        "annotations": {
            "scheduler.alpha.kubernetes.io/node-selector": "env=#=xyz%|=|"
        }
    },
    "spec": {
        "finalizers": [
            "kubernetes"
        ]
    },
    "status": {
        "phase": "Active"
    }
}
```

**Comment by aveshagarwal** [comment]
@derekwaynecarr I do not have enough permissions, could you assign this issue to me?

**Comment by liggitt** [comment]
We have to deal with invalid data in annotations, because those annotations could have values from previous releases, before validation was added. I don't think we should validate the annotation structure in the API.

**Comment by aveshagarwal** [comment]
@liggitt  The annotation scheduler.alpha.kubernetes.io/node-selector is going to be in 1.5 for the first time. And I see that pkg/api/validation/validation.go has several validations for annotations like ValidatePodSpecificAnnotations, ValidateEndpointsSpecificAnnotations,  ValidateAffinityInPodAnnotations and some others too.

**Comment by liggitt** [comment]
> The annotation scheduler.alpha.kubernetes.io/node-selector is going to be in 1.5 for the first time

it can be set in annotations in previous releases, so you need to be able to handle invalid values, despite validation.

**Comment by aveshagarwal** [comment]
I wonder why would someone want to set the annotation scheduler.alpha.kubernetes.io/node-selector in a previous release? It'd be of no use as only the podnodeselector admission plugin uses it and the plugin is going to be in 1.5 only.  Also node selector is an API field in pod, but not in namespace, and I am not sure if there is a plan to do that.

Also there is going to be some annotations based features (like taints/tolerations and there are others too, some in alpha and some in beta), and since given the possibility that customers of downstream distributions might use these features, I think adding validation makes sense to me.

On another note (but not directly related to this), regarding converting annotations to API fields, yes there is an effort to move existing annotations to api fields (https://github.com/kubernetes/kubernetes/issues/34508, https://github.com/kubernetes/kubernetes/issues/30819) before moving them from alpha to beta and I know that for some scheduler related annotations based features, we are already working for that:  https://github.com/kubernetes/kubernetes/issues/25320#issuecomment-256069850 ,  https://github.com/kubernetes/kubernetes/issues/35518

**Comment by derekwaynecarr** [comment]
If we don't verify annotations, we really make life hard for users to use alpha stuff.  I wish we could move off annotations, but until that time, I agree with @aveshagarwal

**Comment by yurrriq** [comment]
I also got burned by this with PodNodeSelector, and the documentation is misleading. I'd love to see proper validation as well as improved documentation. Maybe I can help.
