### ISSUE TITLE
Feature proposal: Add username/password auth for etcd

### ISSUE THREAD

**Issue by lchi** [kubernetes/kubernetes#35565]
Kubernetes does not currently support authentication w/ etcd using users and roles (see: https://coreos.com/etcd/docs/latest/authentication.html). I'd like to add support for this but I'm not sure of the best way to accomplish this, but looking at the command line flags I was thinking something along the lines of:

```
--etcd-authorization-config-file string                File with the etcd user name and password in kubeconfig format
```

Any thoughts on this? This would be my first contribution so I'm not sure what the appropriate format of the config file would be.

**Comment by liggitt** [comment]
I'm not sure we'd want to encourage colocating kubernetes in a partitioned etcd. Can you describe what else you would want to put in the etcd instance kubernetes uses?

**Comment by lchi** [comment]
@liggitt makes sense, closing this.

**Comment by geekofalltrades** [comment]
@liggitt, I've been thinking about sharing Kubernetes' etcd cluster with a Canal overlay network, which needs its own etcd cluster. It makes sense to me to host both in one etcd cluster, as they're both core components of my Kubernetes cluster.

However, in order to do this, I would need to open up access to the etcd cluster from every node in the Kubernetes cluster, whereas otherwise only the Kubernetes master nodes need access. I would be more comfortable doing this if I could have Kubernetes' apiserver and Canal authenticate to etcd as different users, and then each user would have access to separate paths dictated by etcd roles.
