### ISSUE TITLE
Should kubeadm automatically deploy the kubernetes dashboard?

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubernetes#35642]
I'm leaning towards yes, because the dashboard is an integrated part of k8s and our focus is on good UX and an UI is great for that purpose.

cc @kubernetes/sig-cluster-lifecycle

**Comment by pires** [comment]
It's an add-on so I'd suggest adding `--enable-ui` to enable it (disabled by default).

**Comment by roberthbailey** [comment]
> leaning against yes

Did you mean leaning *towards* yes?

**Comment by roberthbailey** [comment]
How are we handling other add-ons in kubeadm? Are we deploying a canonical set of add-ons by default?

**Comment by pires** [comment]
@roberthbailey kube-proxy and kube-dns are automatically provisioned, but that's it.

**Comment by luxas** [comment]
> Did you mean leaning towards yes?

@roberthbailey Oops, yeah of course I did that. What a typo :sweat_smile: 

We're only deploying kube-dns right now, manually in Go code, since it's such an integral part of k8s.
So I thought we might want to do the same for the dashboard...

**Comment by roberthbailey** [comment]
We have a long list of possible add-ons:

- Dashboard
- Ingress Controller
- Monitoring (heapster, influxdb, grafana)
- Logging (fluentd, elasticsearch)
- Node Problem Detector
- Docker Registry
- Horizontal Pod Autoscaling
- Cluster Autoscaling


Are we going to add a flag for each? I think that's going to be a cumbersome user experience.

**Comment by justinsb** [comment]
@mikedanese and I (well mainly me) were/are going to look at a better addons manager, to effectively remove these from the installer.  We have one in kops that could serve as a starting point called "channels".  channels uses the addons manager even for the "system" addons (dns), so that these can be updated also.

Then you can type `channels add channel kubernetes-dashboard` to install the dashboard.  And it saves a bit of metadata (as an annotation on the kube-system namespace) so that it knows what you installed and can prompt for updates when a new version comes out.  And further it knows if you've deleted an addon, so e.g. if you make the mistake of installing influxdb, and then delete all the resources (but leave the tracking annotation), the addon manager won't put it back 5 minutes later.

**Comment by colemickens** [comment]
Or maybe there's a more appropriate meta Issue about addon deployments where I should ask such questions...

**Comment by errordeveloper** [comment]
It is very simple, see
https://github.com/kubernetes/kops/blob/master/channels/cmd/channels/apply_channel.go
.

I had a look at using Helm, I think it's an okay fit...

For meta issues, please look at features#18 and links from there.

**Comment by justinsb** [comment]
channels is very simple and - I believe - minimal.  In particular there's no server component (like tiller).  channels is not much more than a wrapper around `kubectl apply`, similar to `kube-addons` but with some of the rough edges removed, and runnable both server-side and by end-users after installation.  Primary rough edge removed is that you can delete or update a `channels` installed component, and "kube-addons" won't undo your work 5 minutes later. 

My view was that it wasn't acceptable to bake a dependency on helm into core installation, even for an opinionated installer like kops.  Your tastes may differ!  But we should encourage people to use helm, e.g. with a `channels add channel helm`.

channels adds sufficiently little that I think it is reasonable to even think about having it be part of kubectl - it is the next logical step for `kubectl apply --prune`.  But I'm "incubating" the feature outside of kubectl.

**Comment by luxas** [comment]
@justinsb From where do channels "come from"? Which url/location?
For example, if you do `channels add channel helm`, where is the manifest stored?

**Comment by mikedanese** [comment]
This issue was moved to kubernetes/kubeadm#20
