### ISSUE TITLE
Pods that are terminating due to node loss should be surfaced in kubectl output

### ISSUE THREAD

**Issue by foxish** [kubernetes/kubernetes#35725]
Due to https://github.com/kubernetes/kubernetes/pull/34160, we may see pods which have their `DeletionTimeStamp` set and surface in kubectl as Terminating whose status is simply unknown because the node/kubelet was unresponsive for sometime. We should do a better job of surfacing this to the user. 

For example:

```
$ kubectl get pods
NAME       READY     STATUS    RESTARTS   AGE
alpine-0   1/1       Running   0          29m
alpine-1   1/1       Lost      1          17h
```

`kubectl describe` on the lost pod should ideally have a longer message that the node it was running on has not responded in a certain amount of time.

cc @erictune @kow3ns @kubernetes/sig-apps

**Comment by smarterclayton** [comment]
Agree.  When the node controller deletes a pod due to a partition, perhaps
we should be sending a condition on delete options that indicates
partition.  That would give us an unambiguous signal.

Not totally in love with Lost - is there another word that conveys the fact
that the pod should be gone, but is not?  Stuck?  Unresponsive?
NotResponding?  Partitioned?

**Comment by bparees** [comment]
Zombie would seem to align reasonably well w/ how unix handles pids that lost their parents, though Zombie processes are always terminated (but not cleaned up yet)

**Comment by smarterclayton** [comment]
Zombies are cool.  But also overdone.  But still cool.  We could also have `kubectl delete --shoot-zombie` but that might violate the code of conduct for the differently-alive.

**Comment by foxish** [comment]
I think either Unresponsive/Unknown might be the most generic way to represent this state for now. Later on, we may want to have more intermediate states to denote:

- Lost communication with node, but still within forgiveness time period.
- Lost communication with node, hit forgiveness timeout, trying to terminate pod.

**Comment by smarterclayton** [comment]
Ideally a fencer would be able to record a final condition when it deletes
the pod (we record terminal deletion).  Wouldn't show up in the UI but it
would show up in a watch.

On Oct 27, 2016, at 7:14 PM, Anirudh Ramanathan <notifications@github.com>
wrote:

I think either Unresponsive/Unknown might be the most generic way to
represent this state for now. Later on, we may want to have more
intermediate states to denote:

   - Lost communication with node, but still within forgiveness time period.
   - Lost communication with node, hit forgiveness timeout, trying to
   terminate pod.

—
You are receiving this because you are on a team that was mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/35725#issuecomment-256796132>,
or mute the thread

**Comment by foxish** [comment]
I see. That's post-1.5 if IIUC. I feel like if we call the **pod** "unresponsive", one may think that it is safe to force delete it. Any objections to "Unknown"? It's general enough and the user can always drill down and see a longer reason when they do a `kubectl describe`.

**Comment by davidopp** [comment]
@gmarek

**Comment by smarterclayton** [comment]
Unknown is pretty good.  Describe should show more detail about all states

On Oct 27, 2016, at 7:50 PM, David Oppenheimer <notifications@github.com>
wrote:

@gmarek <https://github.com/gmarek>

—
You are receiving this because you are on a team that was mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/35725#issuecomment-256801621>,
or mute the thread

**Comment by AdoHe** [comment]
```
 Describe should show more detail about all states
```
SGTM.

**Comment by gmarek** [comment]
SGTM
