### ISSUE TITLE
CRI: multi character log file delimiter support

### ISSUE THREAD

**Issue by coffeepac** [kubernetes/kubernetes#35734]
As part of the discussion in https://github.com/kubernetes/kubernetes/pull/35348 it was noticed that we are currently hardcoding all log file delimiters to be a single character:

pkg/kubelet/kuberuntime/kuberuntime_logs.go +139

In the medium term this limits us to a subset of logging formats that do not contain the eol character, eg for a default of '\n' that character can't exist in the log message because we are unable to determine if the character is escaped.  We are also unable to have multicharacter message terminations, which can lessen the need for character escaping.

@yujuhong 
/cc @kubernetes/sig-node

**Comment by feiskyer** [comment]
cc/ @kubernetes/sig-node

**Comment by euank** [comment]
I dislike the proposed solution.

mult-byte characters does not fix this, rather escaping does.

However, I'm not convinced this is a problem in the first place.

As you know, these logs are intended *only* for stdout/stderr, and nothing else. As far as I know, you cannot distinguish a multi-line stdout message vs multiple single line messages without additional information.

Because of that, the application will have needed to escape newlines or otherwise indicate message parts in order to output multi-line stuff anyways.

Am I wrong or misunderstanding something, @coffeepac ?

**Comment by coffeepac** [comment]
@euank a. windows new line is CR+LF so for Windows logs going to this we're going to have special characters laying around.
b. I'm not sure escaping would fix this.  encoding would fix this, ie: converting '\n' into the separate characters '\' and 'n' to be assembled by something later.  but escaping would create the characters '\' and '\n'.  So unless we have a method for communicating the escaping character from the application to the log parser I don't think application layer escaping does much.

encouraging message encoding seems fairly sane but doesn't get us around a.  Also, if the application has chosen a multi-byte character to avoid the overhead of encoding do we simply not support that? 

I guess I'm focusing on this because there is an effort made to not transport partial lines.  I believe this request increases our ability to not transport partial lines.

**Comment by euank** [comment]
> I don't think application layer escaping does much

>  Also, if the application has chosen a multi-byte character to avoid the overhead of encoding do we simply not support that? 

I think we might be talking past each other. I am not talking about anything application side. This is for arbitrary stdout/stderr, we can't make any assumptions about the application. We aren't communicating anything to it.

All we need is a lossless-enough way to store and replay completely arbitrary application output.

CR+LF will leave CR's lying around, but it doesn't matter because this isn't really meant to be human readable anyways.

We don't need escaping or encoding though as this layer. if an application wants to print a "\n" without printing a literally newline, it must do its own encoding / whatever, and tihs logging mechanism doesn't need to care about it in any way, so it's orthogonal to this design.

**Comment by coffeepac** [comment]
Right, I was never advocating for escaping or encoding to occur at this level.  I was discussing how I think this layer would handle escaping or encoding.  I was also suggesting that we may not want to assume the event terminator is a newline which suggests that newline may not exist in the logs at all.  Its ugly output but its still legal.

Your points about this not being intended for humans is fair and does clear up my original intent.  The logs not having newlines at all didn't occur to me until nowish.  Is that something we want to support?  It would require the eol char be configurable by the application.

**Comment by euank** [comment]
> this layer would handle escaping or encoding

And I'm saying it wouldn't because there's no need for it.

> suggests that newline may not exist in the logs at all. Its ugly output but its still legal.

I'm still confused. I'm claiming that newlines cannot exist in logs except for as multiple loglines indicating their existence.

Basically, your application can outline multiple logs in the two ways which the application might think are semantically different:

You have an application of `echo -e "foo\nbar"`. This application prints a single multi-line string.
You have an application of `echo foo; echo bar`. This application prints two strings.

I'm claiming that stdout in both of those cases is identical and there is literally no way to identify that the first application intended a multi-line string, so it's not a concern the proposal needs to care about at all. We can losslessly reconstruct the stdout stream there. We can't figure out the semantic intent of the application but we don't want to.

> The logs not having newlines at all didn't occur to me until nowish. Is that something we want to support? It would require the eol char be configurable by the application.

That is a place where our timestamps break down because we assume we can stream line-by-line, but presumably no EOL would mean the application's stdout logfile just contains a giant single line once the application exits.
I don't think we care.

> It would require the eol char be configurable by the application

I still don't get the mention of the application at all.

If you wanna hop on slack to explain more clearly what you're talking about ([sig-node](https://kubernetes.slack.com/messages/sig-node/)) maybe that can help me because I still feel like we're talking about different things. Maybe I'm just totally on the wrong page here.

**Comment by coffeepac** [comment]
Talked with @euank in sig-node.  This doesn't buy us anything.  Closing.
