### ISSUE TITLE
Document cloud-config.json

### ISSUE THREAD

**Issue by runningman84** [kubernetes/kubernetes#35788]
@kubernetes/sig-cluster-lifecycle

Please document how to create these files:
/etc/kubernetes/cloud-config.js
/etc/systemd/system/kubelet.service.d/10-kubeadm.conf
These files are needed for a cloud provider integration using kubeadm according to this document:
http://kubernetes.io/docs/admin/kubeadm/

**Comment by luxas** [comment]
/etc/systemd/system/kubelet.service.d/10-kubeadm.conf is created by the deb/rpm package by default

/etc/kubernetes/cloud-config.json is often a `gcfg` file that is cloud-provider-specific, see https://godoc.org/gopkg.in/gcfg.v1 and the per-provider documentation

**Comment by runningman84** [comment]
can you provide a an aws sample cloud-config.js? The gcfg docs are not very specific here...

**Comment by luxas** [comment]
@justinsb should chime in here with an example of what a AWS example cloud config looks like

**Comment by justinsb** [comment]
It's optional, and should not be needed.  I don't think I have ever used one myself.

**Comment by runningman84** [comment]
This means I can use load balancing and other AWS services out of the box?

**Comment by RaphaelHerd** [comment]
Hi,

I'm interested in the same thing. I try to install a k8s 1.4 cluster with kubeadm in aws but the whole installation process is very poor documented if you haven't done that before.

However, I need that aws integration especially for EC2 load balancers. So my current cluster is not able to create an AWS load balancer. I think it's because a missing cloud provider as well as their credentials. No external loadbalancers means no external connectivity and that's bad in case of a web application :).

So how I have to do that?

Thanks for helping me

**Comment by mikedanese** [comment]
I think that provisioning is out of scope for main repo and kubeadm. We would happily accept a link to an external github repo that implements this in our docs.

**Comment by RaphaelHerd** [comment]
Dear all,

why you closed that issue mikedanese? My question is not about provisioning (see text above). My question relates to the fact that kubernetes should run in a AWS for example and therefore you need some kind of cloud provider integration. That integration is still there in Kubernetes, but very very poor documented. This integration is working with kube-up.sh but it's not with kubeadm. So my question is, what do I have to do to get this integration?

So please reopen the issue that we can disuss that.

Thanks
