### ISSUE TITLE
No remote command equivalent in new go-client

### ISSUE THREAD

**Issue by tnine** [kubernetes/kubernetes#35917]
I'm building some management containers for our PG clusters.  Testing health requires the ability 
to execute commands remotely on the single container in the pod.  I'm using using this command from kubectl as a template.  

https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/exec.go

However, when making the request via client.CoreClient.GetRESTClient().Post() there is currently no mechanism for upgrading the request.  As a result, I always receive the response "Upgrade request required".  Are there any plans to port this wrapper to the new client?

https://github.com/kubernetes/kubernetes/blob/master/pkg/client/unversioned/remotecommand/remotecommand.go

**Comment by nickschuch** [comment]
I managed to get exec running with the following code:

https://github.com/previousnext/m8s/blob/master/server/k8s/utils/pod_exec.go#L15

I found that I had to set the `Param()` calls myself because the underlying checks don't like the  `PodExecOptions` object (see this change for more details https://github.com/previousnext/m8s/commit/5df0a67fe2807618511ebfe66fcf21ff1d59e9c1#diff-a4a5f5ad91d758fe4aa53145a23315f4)
