### ISSUE TITLE
Latest release tag may be wrong

### ISSUE THREAD

**Issue by ronaldpetty** [kubernetes/kubernetes#35946]
It appears that 1.3.10 is marked as "Latest release" here https://github.com/kubernetes/kubernetes/releases/
However 1.4.5 is out.  Unclear what should be latest.

**Comment by liggitt** [comment]
github sorts by tag date... I don't think there's much we can do about that

**Comment by xiangpengzhao** [comment]
Then which one is the newest version? AFAIK there are some users being confused by this.

Right now I see the order of release list is `v1.5.8-beta.0` --> `v1.5.7` --> `v1.4.12`(!) --> `v1.7.0-alpha.2`. Since we already have the stable (if) v1.6, why do we release/tag some v1.5.x or even v1.4.x? Any policy?

@enisoc @jessfraz (since you release v1.4.12) :)

**Comment by enisoc** [comment]
The [release support policy](https://github.com/kubernetes/community/blob/4605abfa0755e7741907db0bc7f131edd0406242/contributors/design-proposals/versioning.md#supported-releases-and-component-skew) is that we support 3 minor releases at a time with patches. Since 1.6 is the latest, that means we need to continue patching 1.6, 1.5, and 1.4 for any bugs deemed impactful enough.

Unfortunately as @liggitt said, we can't change how GitHub applies that marker, and we can't hide it. For now, the most accurate way to determine the latest stable release is to check the following URL, which our automated release tooling keeps up-to-date:

https://storage.googleapis.com/kubernetes-release/release/stable.txt

If you want to stay on 1.5.x for some reason, you can also find the latest stable 1.5.x:

https://storage.googleapis.com/kubernetes-release/release/stable-1.5.txt

**Comment by xiangpengzhao** [comment]
Thanks @enisoc for explanation!
