### ISSUE TITLE
bump docker engine-api

### ISSUE THREAD

**Issue by PI-Victor** [kubernetes/kubernetes#36011]
in the latest version of source-to-image we had to bump the docker engine-api to resolve a bug,
see this: https://github.com/openshift/source-to-image/pull/612#discussion_r83702785
wanted to kick the conversation about bumping it here so we can bump it in origin. i already looked into it and it seems that the docker team also broke API compatibility by removing some fields from the types.go so now, cadvsior needs to be bumped to solve that (and who knows what else). not to mention that they also deprecated the docker engine-api altogether. 

@mfojtik @kargakis what do you guys think? 
cc: @bparees @smarterclayton

**Comment by kargakis** [comment]
@kubernetes/sig-node @kubernetes/sig-api-machinery

**Comment by smarterclayton** [comment]
Does anyone understand the total scope of work?

**Comment by PI-Victor** [comment]
@smarterclayton long story short, we can no longer bump s2i in origin due to the engine-api dependency. which is also holding my PR blocked. 
if there is some other workaround i would gladly take that to be able to move fw.
sorry if i was unclear.

**Comment by PI-Victor** [comment]
i misunderstood, you meant the total scope. yeah i could only trace it to cadvisor dependency so far.

**Comment by yujuhong** [comment]
duplicate: #34308

**Comment by bparees** [comment]
@yujuhong @timstclair though it wasn't super clear, this issue is proposing bumping the docker-engine godep one more time, not moving off it.  (as a short term thing).

**Comment by timstclair** [comment]
Got it. Sorry for misinterpretting it, I'll reopen & revert title.

**Comment by smarterclayton** [comment]
We're so close to freeze that this needs to happen now if it's going to
happen.

On Nov 2, 2016, at 11:18 AM, Ionut Palade <notifications@github.com> wrote:

i misunderstood, you meant the total scope. yeah i could only trace it to
cadvisor dependency so far.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/36011#issuecomment-257896386>,
or mute the thread

**Comment by dchen1107** [comment]
The feature freeze date is next Monday. Agreed with @smarterclayton please share with us the scope first, we can decide what is the next.

**Comment by PI-Victor** [comment]
@smarterclayton me and @bparees were talking about raising this topic tomorrow in planning and see what the best solution is. we both agreed that this bump making it in time all the way from here down to origin is unrealistic because of the amount of work that needs to be done here.
oh and now code freeze. 
totally newb question, any estimate on the code freeze duration?

**Comment by smarterclayton** [comment]
Until early December.

On Nov 2, 2016, at 6:45 PM, Ionut Palade <notifications@github.com> wrote:

@smarterclayton <https://github.com/smarterclayton> me and @bparees
<https://github.com/bparees> were talking about raising this topic tomorrow
in planning and see what the best solution is. we both agreed that this
bump making it in time all the way from here down to origin is unrealistic
because of the amount of work that needs to be done here.
oh and now code freeze.
totally newb question, any estimate on the code freeze duration?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/36011#issuecomment-258022393>,
or mute the thread

**Comment by PI-Victor** [comment]
ok, we fixed our issue with s2i by bumping the engine-api dep back. 
this is no longer a blocker, the question is should this issue still be open and be handled after code freeze, or is moving away from docker engine-api going to be implemented as a priority ? that would make the bump pointless.

**Comment by dims** [comment]
@PI-Victor Looks like the latest docker release does not have all the things needed. looking for example in https://github.com/docker/docker/tree/v1.12.3/api/types So guessing this will have to wait until they mint a release So can pick up a non-random commit from them.
