### ISSUE TITLE
AWS ELB might be created in wrong subnet

### ISSUE THREAD

**Issue by anioool** [kubernetes/kubernetes#36156]
Hi guys,

I need to enable HA for controller currently. I decided to use kops app and kubernetes version 1.4.3. 
Currently I have 3 controllers (each in different AZ), however I need to have rest of stuff located only in one AZ, ie. zone C.

In this situation leader election marked master from zone B as a leader and all requested ELB's somehow need to be created in the same zone as elected master. In this situation, even I have free IP addresses in that subnet (zone B) it is not useful as all stuff is in different zone. 

Is there a possibility to determine which subnet should be taken into consideration for ELB creation?
Maybe ELB should be created in the same zone as svc and pods connected to that service requested?
Is there any possibility to change manually leader ?

Thanks,
Adam

**Comment by anioool** [comment]
@justinsb May you help to assign this issue?

**Comment by justinsb** [comment]
So I think the issue here is that we are including masters in the list of zones for an ELB.  In your case you have masters in zones A,B,C; but you only have nodes in zone C.  So you would like your ELB only to be created in zone C.  Is that right @anioool ?

If so, I think this a case of #33884  We should only create ELBs in zones where there are nodes (and ignore master nodes).

If not, can you please explain further?

If you agree it is part of #33884 I will close as a duplicate and we can continue the discussion there.

**Comment by anioool** [comment]
@justinsb, True, you can close this and mark as duplicate. Thanks for help.
