### ISSUE TITLE
[StatefulSet] Fail to scale pod when there is a blocking pod

### ISSUE THREAD

**Issue by m1093782566** [kubernetes/kubernetes#36333]
**What:**

StatefulSet fails to scale down pod when there is an unhealthy pod.

**How:**

* Create a satefulset

```
# kubectl create -f statefulset.yml
statefulset "mysql" created
```

* First pod is unhealthy

```
# kubectl get pod
NAME                            READY     STATUS    RESTARTS   AGE
mysql-0                         0/1       Pending   0          6s
```

* Try to scale down statefulset

```
# kubectl patch statefulset mysql -p '{"spec":{"replicas":0}}'
"mysql" patched
```

* Unhealthy pod is not deleted.

```
# kubectl get pod
NAME                            READY     STATUS    RESTARTS   AGE
mysql-0                         0/1       Pending   0          20s
```

**Why:**

I assume the root cause is that statefulset controller will ignore delete operations if there is a blocking pod, [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/petset/pet.go#L151-L154). Scaling down can perform as expected if all pods are healthy.

It means users are unable to delete failed pods via `kubectl patch statefulset`, they can only `kubectl delete pod` by force. Some users are confused about this, they want to scale down pods just like what they did in deployment(deployment can easily scale down even if there are some failed pods).

@bprashanth @smarterclayton  @foxish 

Is there any special considerations?

Thanks much!

**Comment by foxish** [comment]
With a StatefulSet of size > 1; if there is an unhealthy pod, there is no way for k8s to know (yet) if it is due to a permanent fault or a transient one (upgrade/maintenance/node reboot). If it were a permanent fault, scaling without paying heed to it may lead to a state where the StatefulSet membership drops below a certain minimum number of "replicas" that are needed to function correctly, leading to unavailability (or worse).

If it were a transient one and the pod were coming back up shortly, we do not want that to interleave with our scale-up/scale-down operation. Some distributed databases have issues when nodes join and leave at the same time. I think it is better that we reason about scaling operations at the application level in these cases, and perform scaling using kubectl patch/scale only when we're sure that our stateful application cluster is completely healthy. I would agree that this should be better documented.

**Comment by m1093782566** [comment]
@foxish 

Thanks a lot for the patient explanation.
