### ISSUE TITLE
kubedns  skydns: failure to forward request / libvirt coreos 

### ISSUE THREAD

**Issue by timactive** [kubernetes/kubernetes#36349]
I recently deployed a kubernetes cluster(http://kubernetes.io/docs/getting-started-guides/libvirt-coreos/)

All working fine but i have issue for my container inside the cluster. In fact i cannot resolve request outside the container.

I create a issue in stackoverflow to explain more.

http://stackoverflow.com/questions/40462338/skydns-failure-to-forward-request

**Kubernetes version** (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.4", GitCommit:"3b417cc4ccd1b8f38ff9ec96bb50a81ca0ea9d56", GitTreeState:"clean", BuildDate:"2016-10-21T02:48:38Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5+", GitVersion:"v1.5.0-alpha.2.266+cc84673ebee685", GitCommit:"cc84673ebee6857265c0378517617bfa76e793f4", GitTreeState:"clean", BuildDate:"2016-11-01T09:54:37Z", GoVersion:"go1.7.1", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release): 
NAME=CoreOS
ID=coreos
VERSION=1221.0.0
VERSION_ID=1221.0.0
BUILD_ID=2016-11-03-0452
PRETTY_NAME="CoreOS 1221.0.0 (MoreOS)"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"

- **Kernel** (e.g. `uname -a`): Linux kubernetes-node-3 4.8.6-coreos #1 SMP Thu Nov 3 04:43:35 UTC 2016 x86_64 QEMU Virtual CPU version 2.5+ GenuineIntel GNU/Linux
- **Install tools**:libvirt coreos

**Comment by cmluciano** [comment]
/close

Please re-post your question to [Stack Overflow](http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support
are posted so that we can improve our efficiency in responding to your requests,
and to make it easier for you to find answers to frequently asked questions and
how to address common use cases.

We regularly see messages posted in multiple forums, with the full response
thread only in one place or, worse, spread across multiple forums. Also, the
large volume of support issues on github is making it difficult for us to use
issues to identify real bugs.

The Kubernetes team scans Stack Overflow on a regular basis, and will try to
ensure your questions don't go unanswered.

Before posting a new question, please search Stack Overflow for answers to
similar questions, and also familiarize yourself with:

  * [user documentation](http://kubernetes.io/docs/)
  * [troubleshooting guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/)

Again, thanks for using Kubernetes.

The Kubernetes Team
