### ISSUE TITLE
Deployment e2e shouldn't test event messages

### ISSUE THREAD

**Issue by krousey** [kubernetes/kubernetes#36453]
These messages are meant for human consumption, not programmatic testing. This is causing issues in the 1.5 release upgrade tests and should be fixed. The fix will have to be cherry picked into 1.4 and 1.3 as well.

See

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-e2e-gce-1.4-1.5-upgrade-cluster/3
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-e2e-gke-gci-1.3-container_vm-1.5-upgrade-cluster/13

cc @kargakis @janetkuo

**Comment by kargakis** [comment]
Agreed about stop using events in the tests.

**Comment by kargakis** [comment]
It's hard to know programmatically that you don't run two versions of pods at the same time and it's even harder because of the Recreate deployment not working 100% correct (https://github.com/kubernetes/kubernetes/issues/32567). For now, I will restore the events back to their original state and in 1.6 I am going to remove events from the tests.

**Comment by janetkuo** [comment]
> Agreed about stop using events in the tests.

+1
