### ISSUE TITLE
kubernetes service can only request pod in local node

### ISSUE THREAD

**Issue by mootezbessifi** [kubernetes/kubernetes#36493]
Since 3 days i faced a very strange behavior in kubernetes cluster when requesting mounted services.
first of all i am newbie with kubernetes. i tried to install a kubernetes cluster (one master 10.104.25.85 and 2 nodes 10.104.25.86 , 10.104.25.87) using ansible on CentOS 7. i inspired my playbooks from official kubernetes github repository (https://github.com/kubernetes/contrib/tree/master/ansible).

after that, i tried to run different steps in this document http://kubernetes.io/docs/user-guide/connecting-applications/ into my cluster, but when i come up with requesting the service by curl from master as follow:
#curl <Cluster_IP>:<PORT>. 
The prompts hangs for few seconds and finishes by showing the next message:

Connection timed out
* Failed connect to <Cluster_IP>:<PORT>; Connection timed out
* Closing connection 0
curl: (7) Failed connect to <Cluster_IP>:<PORT>; Connection timed out

i tried to follow the next article http://kubernetes.io/docs/user-guide/debugging-services/ but nothing seems strange.

i can even ping the pod IP (12.16.23.2 affected from Flannel) from master host.
in each host of the cluster, i can make "curl ip_pod:port" after adding the next rule to filrewalld (already exists on my ansible roles):
#firewall-cmd --permanent --direct --add-rule ipv4 filter FORWARD 1 -o docker0 -j ACCEPT -m comment --comment "docker subnet"

Only From the node where the pod was deployed, curl <Cluster_IP>:<PORT> works perfectly.

the next is the added rules from kube-proxy to iptables after creating the service.
-A KUBE-SEP-PKKU2GKBNWF37J43 -s 12.16.23.2/32 -m comment --comment "default/my-nginx:" -j KUBE-MARK-MASQ
-A KUBE-SEP-PKKU2GKBNWF37J43 -p tcp -m comment --comment "default/my-nginx:" -m tcp -j DNAT --to-destination 12.16.23.2:80
-A KUBE-SERVICES -d 10.254.11.93/32 -p tcp -m comment --comment "default/my-nginx: cluster IP" -m tcp --dport 80 -j KUBE-SVC-BEPXDJBUHFCSYIC3
-A KUBE-SVC-BEPXDJBUHFCSYIC3 -m comment --comment "default/my-nginx:" -j KUBE-SEP-PKKU2GKBNWF37J43

**PS:**
- my-nginx: service name
- 80: port
- 10.254.11.93: service ip.

So what i am doing wrong ??

- kubernetes-master (kubectl, apiserver, scheduler,controller): 1.2.0
- kubernetes-nodes (kubelet, kube-proxy): 1.2.4

**Environment**:
- **Kubernetes cluster (1 master and 2 minions CentOS based)**
- **CentOS 7.1**
- **Ansible 2.1.1.0**:

**Comment by mootezbessifi** [comment]
@k8s-merge-robot

**Comment by mootezbessifi** [comment]
@thaJeztha

**Comment by mootezbessifi** [comment]
@thockin

**Comment by mootezbessifi** [comment]
@eparis @aledbf @bprashanth @lavalamp

**Comment by lavalamp** [comment]
Please re-post your question to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases.

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to similar questions, and also familiarize yourself with:
   * [the user guide](http://kubernetes.io/v1.0/)
   * [the troubleshooting guide](http://kubernetes.io/v1.0/docs/troubleshooting.html)

Again, thanks for using Kubernetes.

The Kubernetes Team
