### ISSUE TITLE
[Federation][Bug] Some problems with kubefed init

### ISSUE THREAD

**Issue by irfanurrehman** [kubernetes/kubernetes#36587]
**Is this a request for help ?**: No (I will raise a PR for the fix very soon)
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug Report

**Kubernetes version** (use `kubectl version`): v1.5.0-alpha

**Environment**:
- **Cloud provider or hardware configuration**: gce
- **OS** (e.g. from /etc/os-release): ubuntu 16.04
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:
listing multiple issues in one
Some flakes/problems which am not sure, when really introduced:

1 - kubefed init code hardcodes the service name of apiserver for controller manager run as federation-apiserver whereas the apiserver service is created using the name provided at command line
    for example if the user does 
    kubefed init <options> federation-us1
    the service name created to expose API server will be federation-us1-apiserver whereas the name for apiserver service name is hard coded as federation-apiserver
    
2 - image name if not specified, the pods created by kubefed init dont work properly.. 
    tag should be one of the existing release images at default path (gcr.io/google_containers/hyperkube-amd64) (it can may be be hard coded to latest official release)
    version.Get() builds the tag based on local info and in most cases does not seem to get one of the tag values available at this repo (for example v1.5.0-beta.0)

**What you expected to happen**:
as listed above

**How to reproduce it** (as minimally and precisely as possible):
as listed above

**Anything else do we need to know**:
No

**Comment by madhusudancs** [comment]
@irfanurrehman thanks for the bug report!

> 1 - kubefed init code hardcodes the service name of apiserver for controller manager run as federation-apiserver whereas the apiserver service is created using the name provided at command line
for example if the user does
kubefed init <options> federation-us1
the service name created to expose API server will be federation-us1-apiserver whereas the name for apiserver service name is hard coded as federation-apiserver

The fix for this is in https://github.com/kubernetes/kubernetes/pull/36294. I will work on getting that merged soon.

> 2 - image name if not specified, the pods created by kubefed init dont work properly..
tag should be one of the existing release images at default path (gcr.io/google_containers/hyperkube-amd64) (it can may be be hard coded to latest official release)
version.Get() builds the tag based on local info and in most cases does not seem to get one of the tag values available at this repo (for example v1.5.0-beta.0)

I am not entirely sure I understand this. Did you try pushing your image before running the command?

**Comment by madhusudancs** [comment]
cc @kubernetes/sig-cluster-federation

**Comment by irfanurrehman** [comment]
@madhusudancs 
about the second issue, relating tag
On any given day, I clone the latest k8s repo
do make WHAT=federation/cmd/kubefed
use the newly built kubefed bin to run 
kubefed init --host-cluster-context=<context> <fed-name>

the tag value picked by version.get() will be something like v1.6.0-alpha.0.433+dbb4def47046da (today)
I think version.get builds the version string using the last applied release label + latest commit hash.

So as a developer (or anybody who might want to build the kubefed bin), either I should clone and build from the release tag, or ensure I build the hyperkube image and push the image also to some repo and use that image.

**Comment by madhusudancs** [comment]
@irfanurrehman isn't that a better default behavior than other options that we have? Hard coding that string is painful because we need to keep chasing the moving target. Every release, we need to ensure we update it to the latest version. If there is an alternative way to automatically update it, I am all ears. Think about it from a user's perspective. User convenience trumps developer convenience, IMHO. What we have now is the default behavior for the user. Developers are not left out though. They can always use the --image flag.

**Comment by irfanurrehman** [comment]
@madhusudancs for issue 2,  I could not find a better way of automatically put a tag value. I think what you say is sort of right.
for issue 1, as you mentioned the fix is raised as part of https://github.com/kubernetes/kubernetes/pull/36294
will close this issue once that PR is merged.

**Comment by dims** [comment]
This needs to be triaged as a release-blocker or not for 1.5 @madhusudancs @irfanurrehman

**Comment by madhusudancs** [comment]
@dims see @irfanurrehman's comment above. This is already fixed, he was waiting for the bug fix PRs to merge.
