### ISSUE TITLE
[CRI] Add authentication to streaming server

### ISSUE THREAD

**Issue by timstclair** [kubernetes/kubernetes#36666]
Address TODO [here](https://github.com/kubernetes/kubernetes/blob/2822e4fd78ca2f448317f97acb551f8e23b5cd58/pkg/kubelet/server/streaming/server.go#L95)

Proposal [here](https://docs.google.com/document/d/1OE_QoInPlVCK9rMAx9aybRmgFiVjHpJCHI9LrfdNM_s/edit#heading=h.nj7347k9gf4q)

/cc @kubernetes/sig-node @liggitt

**Comment by liggitt** [comment]
cc @kubernetes/sig-auth

**Comment by liggitt** [comment]
@timstclair can you target the milestone for this appropriately?

**Comment by timstclair** [comment]
## Proposal

The current request flow for an exec request looks like this:

1. apiserver --> kubelet: exec request
2. kubelet --> CRI shim: get exec request
3. CRI shim --> kubelet: get exec response (URL of shim server)
4. kubelet --> apiserver: 302 redirect to URL of shim server
5. apiserver --> CRI shim: exec
6. pod <---> CRI shim (proxy) <---> apiserver

I propose as a medium-term auth solution for CRI exec we move the intermediate proxy server from the shim into the Kubelet. I.e. the request flow now looks like:

1. apiserver --> kubelet: exec request
2. kubelet --> CRI shim: get exec request
3. CRI shim --> kubelet: get exec response with (e.g.) local named pipe unix socket
4. kubelet proxies local socket to the apiserver connection:
    pod <---> kubelet (proxy) <---> apiserver

I don't think there is a big downside to this compared with running the proxy server in the shim process, and it means that the connection gets to use the Kubelet authentication. Eventually we still want to be able to serve from a separate process, but I don't think this blocks that (and that might be easier once we have a better pod identity story).

As for API changes, we could add a field to the GetExec response, e.g. `ProxyLocal bool`. Alternatively, the kubelet could just use use protocol of the response URI to decide whether to do a redirect or proxy directly (e.g. if the protocol is `file://` or `unix://` proxy directly, otherwise redirect).

WDYT?

/cc @yujuhong @mrunalp

**Comment by sjpotter** [comment]
I'm wondering what this would mean for VM oriented pod containers.  Currently able to run the server within the VM and give that as a URL, makes exec simple.

**Comment by sjpotter** [comment]
I'm wondering what this would mean for VM oriented pod containers.  Currently able to run the server within the VM and give that as a URL, makes exec simple.  which seems to be against the initial premise of the proposal

**Comment by timstclair** [comment]
A problem with my proposal above is it assumes the Kubelet understands the protocol used between the CRI shim & the pod. If that's not the case, the kubelet would still need to talk to the CRI shim for the streams, which adds an extra proxy hop. This might be an acceptible temporary solution, but we should still look into what it would take to get the CRI streaming server a proper signed serving cert (can it use the Kubelets cert, and deal with rotation? If not, can it use a CSR? Does it need rotation then?)

**Comment by yujuhong** [comment]
Moving this to 1.9.

**Comment by Random-Liu** [comment]
To summarize the discussion:
* The overhead in kubelet and resource charge back is important, but less important compared with security. The bottleneck is in apiserver today anyway.
* Option 3 is still our long term plan, but option 2 is a better solution for now, because we don't have a good auth/authz solution for option 3 today.
* We decide to do Option 2 for short term, but make it possible to easily switch to option 3 once we have a better auth/authz solution.

We will:
* Keep today's logic in apiserver and kubelet, and CRI unchanged, so that we can switch to option 3 easily in the future.
* Add direct stream support in kubelet, and add feature gate for it.
* Serve container streaming on unix domain socket in container runtime.

To switch to option 3 in the future, we should firstly:
* Have a good solution for auth/authz;
* Remove the bottleneck in apiserver.

**Comment by feiskyer** [comment]
+1 to option 2

> Add direct streaming support in kubelet, and feature gate it.

If a feature gate is added to kubelet, should all runtimes also add such a feature gate? e.g. runtimes may need deciding to serve streaming APIs on tcp port (as today) or unix domain socket.

**Comment by mikebrow** [comment]
Agreed let's switch to a socket for streaming.

**Comment by Random-Liu** [comment]
@mikebrow Volunteered to help on this. Thanks a lot! :D

**Comment by Random-Liu** [comment]
Discussion for long term solution: https://github.com/kubernetes/kubernetes/issues/62747

**Comment by liggitt** [comment]
@tallclair is this still needed with the current plans for the streaming server?

**Comment by dims** [comment]
@tallclair @mikebrow Any updates? Following up on @liggitt 's query, what is the "current plan" for the streaming server?

**Comment by tallclair** [comment]
I should probably write this up as a KEP, but here are the bullet points for now. The solution I would like to see:

- introduce streaming gRPC calls to the CRI API
- streaming requests are proxied through the API server & Kubelet
  - client calls apiserver, which does an upgrade request to the kubelet (as today), kubelet calls streaming CRI functions, and proxies the output to the apiserver
- remove the streaming redirect handling from the apiserver & kubelet
- rate limit streaming requests everywhere
  - _optional: parametrize rate limiting (with max), allowing admission controllers to implement streaming quota or more strict rate limiting_
- for more advanced cases, recommend a containerized daemon approach, possibly with a reference implementation.

This isn't currently staffed, and we don't have a roadmap.

Given these plans, we don't need authorization since we would remove this code path.

**Comment by dims** [comment]
long-term-issue (note to self)

**Comment by tallclair** [comment]
CRI streaming will only happen locally, so I don't think it's worth adding this anymore. See:
- https://github.com/kubernetes/enhancements/tree/master/keps/sig-node/1558-streaming-proxy-redirects
- https://github.com/kubernetes/enhancements/issues/1558
