### ISSUE TITLE
REST api v3 in the "status"  no info about ports, memory, cpu, etc. even when container is running.

### ISSUE THREAD

**Issue by abonas** [kubernetes/kubernetes#3669]
forked from #3622 

![podports](https://cloud.githubusercontent.com/assets/6277245/5834539/755ae1d2-a167-11e4-8801-23406a60096f.png)

**Comment by bgrant0607** [comment]
Copied from the other issue:

@abonas What info would you like to see about ports?

We plan to introduce a separate API for resource information. See the section about usage here:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/resources.md

/cc @rjnagal @dchen1107

**Comment by abonas** [comment]
copied from the other issue:

@bgrant0607 when I query for pod information and its containers, it's important to see what's going on with them in runtime. so if spec was ports XYZ, cpu A and memory B, I would like to see if indeed it matches the spec or is different. were the ports allocated? same ports? different ports?

otherwise, having only the spec information, there's nothing user can do to monitor/manage the runtime.

also, having an additional api means it's requiring more requests to server, more merging work and resolving relationships on client side. not very convenient for clients.

**Comment by bgrant0607** [comment]
We should put links (in a style similar to selfLinks) to the resource API in the pod and node status. Those links should be stable. /cc @vishh 

@abonas I sympathize, but resource usage in the core objects is infeasible to both keep up to date and scale. Our experience is that a custom data path is necessary in order to provide reasonably fresh data. That ensures that only genuinely interested clients request/watch the information, custom change-significance filters can be more easily applied, custom aggregations can be applied, rapidly changing ephemeral data won't be unnecessarily persisted and won't unnecessarily invalidate cached status information, etc.

**Comment by abonas** [comment]
so @bgrant0607 if my pod has 5 containers, and I would like to understand their status, I will need 6 requests? (one for pod and 5 more for containers?)  
BTW when the resource api will be available?

**Comment by abonas** [comment]
I also don't understand from resources.md:
1. does that mean that it replaces the "spec" part of pod? so user needs to define through that api what should be each container resources?
2. how a current utilization of ports, cpu, memory should be queried per container or per pod?

**Comment by itamarh** [comment]
@bgrant0607 - Can you please provide an example of how one would get the usage statistics of a pod / its container's using this resource approach? say, cpu/ram usage polled every few minutes? thanks.

**Comment by bgrant0607** [comment]
@abonas Exact API is being worked out now. There is also a prototype, not plugged into apiserver yet. We're working on it, but no specific ETA at this point.

The new resource spec will replace the cpu and memory fields of the container specification.

@itamarh One would get the pod, and then get the resource object(s) referred to in the pod's status. For periodic changes, we may make a way to watch for periodic updates.

**Comment by itamarh** [comment]
@bgrant0607 I thought the resource objects are more definition/policy like, say, like flavours/instance types for VMs. but if they are used for dyanmic stats, its really like a separate table for statistics you would be pointing at a specific, different, resource for each container? since this means the resources are just specific instances for each container, would they keep their identifier throughout the container lifetime? or contain the back reference to the container id?
(why? since if i want to poll for stats, i don't want to poll all containers all the time, just to get their pointers to their stats, to poll them again directly)

**Comment by abonas** [comment]
@bgrant0607, any news on resources api? design? ETA? thanks

**Comment by vishh** [comment]
@abonas: API has been [extended](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/api/v1beta3/types.go#L364) to include diverse set of resources. By API I assume you are referring to the Spec part and not the usage.
When it comes to usage, are you looking for instantaneous data or distributions? I find the latter to be more useful as a user. If you can provide a few use cases for needing periodic usage data, other than monitoring, that would be useful.
We have [heapster](https://github.com/GoogleCloudPlatform/heapster) that exports compute resource usage. It is tied closely to InfluxDB, but we are working on making it generic and we are considering exposing usage metrics via heapster.

**Comment by bgrant0607** [comment]
Metrics proposal: #11951

**Comment by bgrant0607** [comment]
I propose we close this in favor of #4057 and/or the current proposal.

**Comment by kargakis** [comment]
@abonas @kubernetes/sig-node-feature-requests  is this an issue anymore?
