### ISSUE TITLE
More general scheduling constraints

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#367]
There have been a few folks who have asked about machine constraints for scheduling.  Let's use this issue as a place to gather ideas and requirements.

@timothysc

**Comment by pires** [comment]
+1 for @jbeda suggestion
> Have a "avoid co-schedule" labels on each pod. That way the pod would say "don't schedule me on any node that has pods that match this label selector".

Also the SQL-alike syntax for defining this would be a _awesome-to-have_, but not a priority, I reckon.

**Comment by abhgupta** [comment]
@pires @jbeda @brendanburns @bgrant0607 Am a bit late to this discussion, but in case this issue is still relevant, here is my take. The "avoid co-schedule" functionality is now easier to implement in a more generic manner, while also being closer to what the user actually intended. 

The user could either want to avoid co-scheduling on a per-minion basis, or for a rack/zone/etc. https://github.com/GoogleCloudPlatform/kubernetes/pull/2906 implemented the priority functions for the scheduler that spreads pods across, for lack of a better word, "node groups" that are defined based on node labels. We could easily add a configuration parameter to this priority function that specified the maximum number of pods that can be placed on a single "node group". If co-scheduling is to be avoided on a per-minion basis, then there is a service spreading priority function that can be modified to accept the max-pods-per-minion parameter. 

If a proper fit is not available, the pod would fail to be scheduled and this is an area where we don't currently have visibility (error being surfaced to the user properly). I would suggest going for these simple enhancements once we have the mechanism to bubble up scheduling constraint violations to the user/admin.

https://github.com/GoogleCloudPlatform/kubernetes/pull/4674 deals with accepting the scheduler configuration via a JSON file.

**Comment by bgrant0607** [comment]
See also anti-affinity discussion here: https://github.com/GoogleCloudPlatform/kubernetes/issues/4301#issuecomment-74355529

**Comment by timothysc** [comment]
I've been looking to eval: https://github.com/hashicorp/hcl and ttps://www.terraform.io/docs/configuration/syntax.html as an extensible config language for constraints, but it also has other applications: #7739

**Comment by benmccann** [comment]
@timothysc have you seen [HOCON](https://github.com/typesafehub/config/blob/master/HOCON.md)? It looks extremely similar to hcl/terraform.

**Comment by bgrant0607** [comment]
Thanks for the pointer, but this is getting off-topic. You could use #1743 or file a new issue to discuss higher-level configuration mechanisms, such as parameterization and object cross references. You could also browse issues relating to the broader topic of configuration:
https://github.com/GoogleCloudPlatform/kubernetes/labels/area%2Fapp-config-deployment

**Comment by erictune** [comment]
[Docker Swarm](https://docs.docker.com/swarm/) supports:
  - [Filters] which limit the set of nodes that a container can be scheduled on. 
  - [Scheduling Strategies](https://docs.docker.com/swarm/scheduler/strategy/) which affect how various eligible nodes are ranked. 

Filters include:
  - Constraint, where container label has to match node label.
  - Affinity, where a container label needs to be near another container.
  - Port, which is largely not relevant in K8s due to IP per pod.
  - Dependency, which is when two containers need to be near the same volume.  Pods captures this case for kubernetes.
  - Health: keeps containers off unhealthy nodes.

Scheduling Strategies include one which does spreading.

**Comment by bgrant0607** [comment]
We have constraints via nodeSelector.

Affinity, Port, and Dependency are covered by pods.

Health should be automatic.

Strategies are currently baked into the scheduler, which is configurable, thus preserving what/how separation. We've discussed making it possible to disable default scheduling, which would enable users to run their own schedulers.

**Comment by davidopp** [comment]
> We have constraints via nodeSelector.

Swarm has regular and "soft" constraints. We don't have the latter yet, but I filed #8008 for us to implement it.

**Comment by timothysc** [comment]
After giving this a fair amount of thought... for service orchestration you could likely boil down most options into two categories (affinity, and anti-affinity).  We could get far more fancy, but at some point I wonder "Everything Should Be Made as Simple as Possible..."  

Here are my distilled thoughts: 

function (label or annotation)  
SPREADBY  - typical use case - SLA uptime 
GROUPBY  - typical use case - SLA performance

operators:
& | 

Constraint: SPREADBY (rack) & GROUPBY (datacenter) 

/cc @eparis @rrati @jayunit100

**Comment by eparis** [comment]
I'd think a ! operator would be in order

**Comment by davidopp** [comment]
There are "soft constraints" (scheduling goals) and "hard constraints." I think you're talking about the first?

What is the use case and semantics of the | operator? (For connecting SPREADBY and GROUPBY clauses, I assume)

Same question for !

**Comment by timothysc** [comment]
@davidopp soft 

Constraint evals to simlpe true or false expressions, so it should really be &&, || this way you can connect them including simple predicate matching. 

GROUPBY (cluster) ||  rack==funkytown 

The more I think about it, the less I want to tread into config language space given the cattle idiom on services.  Weather they are soft or hard could either be denoted kia keyword or some other semantics.

**Comment by davidopp** [comment]
So IIUC the way the thing you're proposing would work would like this?

GROUPBY expr1 || expr2 => put a virtual label X on all the machines that match expr1 or expr2, and then try to co-locate all the pods of the service on machines with label X
GROUPBY expr1 && expr2 => put a virtual label X on all the machines that match expr1 and expr2, and then try to co-locate all the pods of the service on machines with label X
SPREADBY expr1 || expr2 => put a virtual label X on all the machines that match expr1 or expr2, and then try to spread all the pods of the service across machines with label X
SPREADBY expr1 && expr2 => put a virtual label X on all the machines that match expr1 and expr2, and then try to spread all the pods of the service across machines with label X

It would be good to flesh out some use cases...

**Comment by bgrant0607** [comment]
I agree that flavors of affinity and anti-affinity are the basic 2 features that would satisfy most use cases.

With respect to As Simple As Possible, specifying just whether to group or spread seams like the simplest possible API. That needs to be associated with some set of pods, via label selector (in which object TBD). Node groups to concentrate in or spread across could be configured in the scheduler in most cases.

**Comment by jcderr** [comment]
+1

**Comment by dchen1107** [comment]
cc/ @pwittrock

**Comment by dchen1107** [comment]
https://github.com/kubernetes/kubernetes/pull/13524

**Comment by davidopp** [comment]
This is part of #18261

**Comment by timothysc** [comment]
@davidopp I think it reasonable to close this issue, in lieu of the assorted proposal.

**Comment by davidopp** [comment]
@timothysc Let's wait until we merge the proposal.

**Comment by bgrant0607** [comment]
Affinity/anti-affinity proposals merged and implementations are underway.
