### ISSUE TITLE
Split generator files into its own subpackage

### ISSUE THREAD

**Issue by soltysh** [kubernetes/kubernetes#36805]
`pkg/kubectl` is getting messier and messier with the number of generators being created. I'm propose creating new subpackage `generators` and split each generator into its own file.

@fabianofranz @kubernetes/kubectl opinions?

**Comment by deads2k** [comment]
Have generators fulfilled their mission yet?  There are a lot of them, but I'm still struggling to find the value they add to our CLI.

@derekwaynecarr

**Comment by smarterclayton** [comment]
The concept of version locked strategy is valid.  The lower level details
are still pretty ugly.

On Nov 15, 2016, at 8:17 AM, David Eads <notifications@github.com> wrote:

Have generators fulfilled their mission yet? There are a lot of them, but
I'm still struggling to find the value they add to our CLI.

@derekwaynecarr <https://github.com/derekwaynecarr>

—
You are receiving this because you are on a team that was mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/36805#issuecomment-260638210>,
or mute the thread

**Comment by bgrant0607** [comment]
Our other alternative is to insist that we never change behavior of any generation commands. The `kubectl run` changes caught most people by surprise because most users weren't aware of the generator versioning mechanism.
