### ISSUE TITLE
Enhanced kube-proxy:iptables testing with iptables-restore --test

### ISSUE THREAD

**Issue by mandarjog** [kubernetes/kubernetes#36850]
## FEATURE REQUEST:
At present the rules generated by kube-proxy (pkg/proxy/iptable/proxier) cannot be / are not validated  for syntactic correctness. 

### Options 1
```
iptables-restore --test
```
Given a rules set, it validates if the rules are correct.
This test does more than just syntactic validation.

1. It expects the kernel modules for tables to be loaded (or available for modprobe)
2. You need root privileges to run --test. 
Given this we can run the validation tests as part of e2e tests inside   docker container.

### Option 2
It is still desirable to have this as part of the unit test. 
Update iptables-restore.c to separate out the parser and then use it for proper unit test validation.

**Comment by mandarjog** [comment]
@bprashanth Added the iptables-restore issue.

**Comment by bprashanth** [comment]
we should write an e2e that ssh's into the node and shells out. This would've caught https://github.com/kubernetes/kubernetes/issues/36652

This is an example of an e2e that ssh's into a node https://github.com/kubernetes/kubernetes/blob/master/test/e2e/daemon_restart.go#L61

**Comment by yuval-k** [comment]
Anybody working on this? I'm trying to setup end2end testing environment, so I may be able to give this one a try.

**Comment by thockin** [comment]
Nobody is working on this,

**Comment by yuval-k** [comment]
Hello, 

I have tried to implement the test, please see my branch:
https://github.com/yuval-k/kubernetes/tree/feature-e2e-proxier

and specifically, the test it self:

https://github.com/yuval-k/kubernetes/blob/feature-e2e-proxier/test/e2e/proxier.go

The test has successfully SSH'ed to a kubernetes node and used "iptables-restore --test" to verify the rules generated by the proxier.

It is not 100% complete yet - I wanted to get some feedback, to make sure i am heading in the right direction. 

Some questions:
- Can't create a fake proxier as it is in the test package - is it ok to move it to its own package (like iptablestest.NewFake)?
    - some other private methods were copied from the proxier unit test - should i refactor them to a package as well, or leave it as it is?
- I create one service so that the proxier would generate iptables rules for it. Does that seem like the right approach? If so, I'll go ahead and create more services of different types.


any other feedback is appreciated,
Thanks!

CC: @thockin, @mandarjog

**Comment by cmluciano** [comment]
@yuval-k Can you open a PR with your patchset?

**Comment by yuval-k** [comment]
@cmluciano  - https://github.com/kubernetes/kubernetes/pull/47662
