### ISSUE TITLE
Compatibility with GCP deployment manager

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#3685]
We could also build a simplified open-source version.

https://cloud.google.com/deployment-manager/fundamentals

One useful functionality it would add is parameterization, using jinja templates and sandboxed python.

Known issues: 
* Need the ability to wait for readiness of dependencies #1899

**Comment by bgrant0607** [comment]
cc @jackgr @iantw89

**Comment by DamodarSojka** [comment]
Hi 
I am a student at University of Edinburgh currently involved in undergraduate research project concerned with configuring large systems. I am faced with prototype of new configuration language, and my task is to understand common problems that exist in area of configuring large systems. I want to track down problems that existing solutions are not solving and hopefully make useful proposals to prototype language. For example now I am looking at google's App Engine approach to configuration in order to figure out what are the useful features and how they can be implemented in more declarative approach, but in order to pick such features I would need to receive either feedback or data, like existing code for configurations. Is this possible? If I have asked in a wrong place please let me know where I can go.

**Comment by bgrant0607** [comment]
cc @vaikas

**Comment by errordeveloper** [comment]
@DamodarSojka please post on StackOverflow or the Kubernetes mailing list, this is a good question indeed and Kubernetes may be the right kind of system to study.

**Comment by jackgr** [comment]
We've just pushed the initial bits for [open source Deployment Manager](https://github.com/kubernetes/deployment-manager). See the new repository here. @DamodarSojka, we would welcome your involvement and review.

**Comment by jackgr** [comment]
Note that we don't yet sandbox the python or wait for readiness of dependencies #1899, although both features are in the backlog.

Can this issue be closed, now?

cc @bgrant0607

**Comment by DamodarSojka** [comment]
Yes. Thanks!
