### ISSUE TITLE
Incorrect documentation of rollingUpdate.maxUnavailable rounding

### ISSUE THREAD

**Issue by luksa** [kubernetes/kubernetes#37083]
API documentation says deployment.spec.strategy.rollingUpdate.maxUnavailable is rounded up, but it is actually rounded down:

```
$ kubectl explain deployment.spec.strategy.rollingUpdate.maxUnavailable
FIELD: maxUnavailable <string>

DESCRIPTION:
     ...Absolute number is calculated from percentage by >>>>> rounding up.  <<<<<
```

The code shows it is rounded down, not up:

https://github.com/kubernetes/kubernetes/blob/fbe29f43eaf2f561d2f1f61542381ae53894efd4/pkg/controller/deployment/util/deployment_util.go#L925

and

https://github.com/kubernetes/kubernetes/blob/fbe29f43eaf2f561d2f1f61542381ae53894efd4/pkg/util/intstr/intstr.go#L143

**Comment by kargakis** [comment]
Yes, the documentation is obsolete. We changed maxUnavailable to round down so that we wouldn't accidentally infer 100% unavailability for non-100 percentages. For example, maxSurge=25% and maxUanavailable=25% with a Deployment of 1 replica meant that we could scale down 1 before thus leading in 100% maxUnavailable (implicit).
