### ISSUE TITLE
kube-proxy logs are not collected by fluentd

### ISSUE THREAD

**Issue by piosz** [kubernetes/kubernetes#37107]
cc @thockin @bprashanth

**Comment by Crassirostris** [comment]
Currently logs from kube-proxy are written to the kube-proxy.log file in the /var/log directory on the node [(link)](https://github.com/kubernetes/kubernetes/blob/master/cluster/saltbase/salt/kube-proxy/kube-proxy.manifest#L55)

At the same fluentd configuration (for example, [this one](https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/fluentd-gcp/fluentd-gcp-image/google-fluentd-journal.conf), for GCI) doesn't have a separate rule for this file.

It makes sense to remove forwarding logs to the `/var/log/kube-proxy.log` so that fluentd can automatically pick up kube-proxy logs from the container's `stdout` and `stderr`.

**Comment by Crassirostris** [comment]
Unfortunately, it not possible to use default container logging mechanism, because `kube-proxy.log` has multiline log entries (mainly with iptables rules).

Currently docker json driver wraps every line into the separate entry, which is later picked up by fluentd as separate entries. I will create a PR with config change for `kube-proxy.log`.

**Comment by dims** [comment]
@piosz @Crassirostris : can you please add a release-blocker or non-release-blocker tag as appropriate?

**Comment by thockin** [comment]
What is the proposed config change?  The assumption that every output line
is a distinct log record is broken, but I an SURE that affects many pieces
of many systems...

**Comment by Crassirostris** [comment]
The proposed change is to add `kube-proxy.log` with the possibility of having multiple line records, in the exactly same way kubelet and api-server's logs are working.

**Comment by Crassirostris** [comment]
@piosz Forgot to fix in pr, please close

**Comment by piosz** [comment]
We also need to bump the version.

**Comment by Crassirostris** [comment]
Oh, yeah, thanks
