### ISSUE TITLE
v1.5.0 known issues / FAQ accumulator

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/kubernetes#37134]
Please link to this issue or comment on this issue with known errata for the 1.5.0 release.  This follows what we have done for prior releases (see #32332, https://github.com/kubernetes/kubernetes/issues/10760#issue-93324758)

We will be populating the "Known Issues" section of 1.5.0 release notes based on this issue

/cc @saad-ali

**Comment by davidopp** [comment]
For #37862 we should write something like

**NOTE** If you used the PodDisruptionBudget feature in 1.4 (i.e. created `PodDisruptionBudget` objects) then **BEFORE**  upgrading from 1.4 to 1.5, you must delete all `PodDisruptionBudget` objects (`policy/v1alpha1/PodDisruptionBudget`) that you have created. It is not possible to delete these objects after you upgrade, and their presence will prevent you from using the beta PodDisruptionBudget feature in 1.5 (which uses `policy/v1beta1/PodDisruptionBudget`). If you have already upgraded, you will need to downgrade the master to 1.4 to delete the `policy/v1alpha1/PodDisruptionBudget` objects.

**Comment by dims** [comment]
@spiffxp Is it appropriate to move this to the next milestone or clear the 1.5 milestone? (and remove the non-release-blocker tag as well)

**Comment by davidopp** [comment]
No, this issue is about v1.5 known issues, so it is for the 1.5 release.

**Comment by dims** [comment]
Ack @davidopp :)

**Comment by saad-ali** [comment]
Release notes have been checked in to https://github.com/kubernetes/features/blob/master/release-1.5/release-notes-draft.md

@smarterclayton @yujuhong @euank @timstclair @childsb @BaluDontu @pwittrock @davidopp you all have issues linked to this indicating that you identified a "Known Issue" with the 1.5 release.

The 1.5 release notes are now checked into https://github.com/kubernetes/features/blob/master/release-1.5/release-notes-draft.md. Please take a look at that ASAP, verify that your issue is captured correctly, if not please open a PR and assign it to @spiffxp to get it fixed ASAP.

We plan to release 1.5 on Monday, Dec 12--when the release is cut, it will automatically pick up this file, so if you have any changes to the release notes please make sure you get them merged before that.

**Comment by pwittrock** [comment]
@smarterclayton We probably want to improve the line for `kubectl --force deletion is breaking upgrade tests #37117`.  I have a PR out I can add it to if you know what the wording should be.

**Comment by smarterclayton** [comment]
https://github.com/kubernetes/kubernetes/pull/37263 has a longer release note - but if you want it to be even longer I can make it so.

**Comment by pwittrock** [comment]
No, that is good

**Comment by spiffxp** [comment]
v1.5.0 has been released, closing this issue
