### ISSUE TITLE
e2e test for kubectl drain involving Stateful Sets with a defined PDB

### ISSUE THREAD

**Issue by foxish** [kubernetes/kubernetes#37132]
We should have an e2e test which uses PDBs and Stateful Sets together to ensure that node drains occur as expected.
We expect drains to not affect the functioning of a Stateful Set, and should capture this.

cc @erictune @smarterclayton @janetkuo @enisoc

**Comment by foxish** [comment]
Do we also need one for anti-affinity and ensure that the pods do get spread? It's not a Stateful Set property but is certainly going to be important to users.

**Comment by dims** [comment]
@foxish : can you please throw a non-release-blocker or release-blocker label as appropriate?

**Comment by calebamiles** [comment]
@erictune, @smarterclayton, @janetkuo, @enisoc @kow3ns we need an update as to whether this issue is a 1.5 release blocker. This seems like a non release blocker but I'd like someone to comment before I add the label. Please respond by end of day 21 November 2016 PST, thanks!

**cc: @saad-ali, @dims**

**Comment by foxish** [comment]
Not a release blocker.

**Comment by ethernetdan** [comment]
Moving to 1.7 as late to happen in 1.6. Feel free to switch back if this is incorrect.

**Comment by enisoc** [comment]
Removing milestone as I don't see any evidence of this being worked on for v1.7.
