### ISSUE TITLE
Loadbalancer setup needed for metal deployments

### ISSUE THREAD

**Issue by sandys** [kubernetes/kubernetes#37146]
https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/cloud.go#L28

https://github.com/kubernetes/kubernetes/tree/master/pkg/cloudprovider/providers

There are already load balancer setups built for all major cloud providers... however there is no built in option for metal deployments. 
I have already looked at https://github.com/kubernetes/contrib/tree/master/service-loadbalancer ... some people are setting up keepalived to do this as well. But there is no seamless built-in option.

A lot of us are on providers like rackspace and softlayer and we would love to have a out-of-the-box setup. In fact, I would argue that k8s is much more relevant for us than for the cloud guys!

**Comment by sajal** [comment]
I just evaluated [service-loadbalancer](https://github.com/kubernetes/contrib/tree/master/service-loadbalancer), whats missing is that the loadbalancer itself cant see the actual client ip, it only sees a NAT IP. IP based affinity is useless in this case it sees all traffic coming from a single IP and directs everything to a single pod.

I am trying to figure out load balancing within kubernetes that can reliably pass along the real client ip, and do IP based affinity to pods. If you don't care about these 2 points then service-loadbalancer should work well.

**Comment by kad** [comment]
isn't it related to #37396 if all traffic SNAT'ed ?

**Comment by sandys** [comment]
@sajal +1.
real client-ip is super critical for us. IP based affinity is not that critical to us, since our services can look up session ids anywhere.

But would love to know what you come up with. 

Incidentally, are you doing kube-dns based service discovery or are you using nodeport and registering them in load balancer?

**Comment by sajal** [comment]
@sandys Just did a PoC today where I was able to get real client ip and afinity. But I have no idea if im doing a hacky fragile work-around or proper way. The trick is to use `hostNetwork` - which bypasses SNAT/kube-proxy/whatever .

What I did.

Setup a cluster using the [tutorial by CoreOS](https://coreos.com/kubernetes/docs/latest/getting-started.html) version `v1.4.4_coreos.0`. Not using Calico. 

Exception: [Configure flannel Network](https://coreos.com/kubernetes/docs/latest/deploy-master.html#configure-flannel-network) says to use `$POD_NETWORK` which is `10.2.0.0/16`, but instead I used `10.2.0.0/15` . I did this to include the service IP range (i.e. `10.3.0.0/24` ) in flannel (this is needed for later on).

Now deploy [nginx-controler](https://github.com/nginxinc/kubernetes-ingress/blob/master/examples/complete-example/nginx-ingress-rc.yaml). One difference: add `hostNetwork: true` in pod spec around line 16. Now because service ip range is routed by flannel, this pod can talk to apiserver. Run your app, configure your service and ingress, you will see X-Forwarded-For being populated correctly.

For IP based affinity you need to add `ip_hash;` to upstream block in [ingress.tmpl](https://github.com/nginxinc/kubernetes-ingress/blob/master/nginx-controller/nginx/ingress.tmpl#L3) and build your own image. I did not do that.. I instead tested it by hand editing the template on the running pod for the PoC.

the nginx pod does not get configured to use kube-dns, because of `hostNetwork`, but its not needed since it only needs access to apiserver to discover endpoints.

Once setup, use ingress rules just like those fancy cloud guys... but you do need to manage some load balancing strategy(perhaps DNS or VIP) to point users to an available box.

Try it out (I might kill the cluster before then) :-

    $ curl -vv  http://138.68.50.48/

Its a simple app dumping the request headers as json... and the last line is the pod name that served the response(to test affinity)

**Comment by sandys** [comment]
@sajal This was awesome! I just tried it.

what about trying this without using ingress. you can run kube-dns and create Cluster-IP for each Service and route the load balancer (I dont know what load balancer you are using) to the Cluster IP directly ?

have you tried this ? IMHO unless you have new Services popping up (not pod creation/scaling... but completely new Services being defined and popping up), ingress is not really needed

**Comment by sajal** [comment]
I only tried 2 methods. service-loadbalancer which just tries to map all services, i guess it was created before Ingress was a thing, and the nginx ingress example. Both these methods use the kubernetes API to figure out which pods belong to a service and then direct traffic directly to the pods (i.e. use service for pod discovery but not use it for sending traffic eliminating one redundant hop). The `Ingress` method does what I want and makes me feel in control of what I am exposing to the world.

I think if you send traffic thru a service, you loose the external client ip affinity because service does not have access to it.

**Comment by sandys** [comment]
@sajal not entirely true. you can work with SessionAffinity (http://kubernetes.io/docs/user-guide/services/). I have an inkling the kube-dns and SessionAffinity will be better performing.

**Comment by sajal** [comment]
@sandys yeah but the client IP visible to the service is the internal NAT's ip belonging to the load balancer and not the real external client IP. Doing SessionAffinity based on loadbalancer's IP is pointless IMHO. This affinity is targeted towards internal consumers.

The services work at L4 and can't peak into `X-Forwarded-For` header.

**Comment by sandys** [comment]
@sajal that is a super-useful comment ! You should really file a bug that allows session-affinity to be set based on clientip or a particular header. Makes total sense. You would not need to do the hostnetwork hack then. 

you have my +1 for it.

**Comment by sandys** [comment]
@sajal alternatively you can use nginx real-ip module or proxy protocol (https://github.com/kubernetes/contrib/tree/master/ingress/controllers/nginx#proxy-protocol) to enable this.

Probably that will be much simpler

**Comment by sajal** [comment]
@sandys Doing it at service level is a bad idea IMHO. I believe currently kube-proxy just sets iptables rules and lets kernel do the NAT ... to look at headers and then route it you would need to do it within pods, not within kube-proxy...

I did consider using proxy protocol, one pod with hostNetwork uses proxy protocol to send traffic inside and then i apply affinity based on real-ip, but why not cut that layer and just do it on the outer pod....

What is it that you are trying to optimize? The nginx example I mentioned uses the kubernetes api directly and it cuts down on so many layers (like dns)... you can build whatever logic you want into it.

**Comment by sandys** [comment]
@sajal - so you're conflating two things that I said. Let me elaborate.

Proxy Protocol - you can feed in the proxy protocol to your ingress. I
think the latest master of ingress supports proxy/L4 routing and SSL
passthrough. You will not have to resort to the hostnetwork and CIDR stuff
that you are doing.

Service proxy vs ingress - I agree a lot with what you are saying. I had a
conversation with the linkerd.io guys and they talked about how linkerd
allows you to route directly to the pods using the endpoint api. However,
I'm not sure IN YOUR PARTICULAR CASE whether ingress would be faster or the
NAT. Both would work. That is what I was curious to find out.


On Dec 2, 2016 10:29 PM, "Sajal Kayan" <notifications@github.com> wrote:

@sandys <https://github.com/sandys> Doing it at service level is a bad idea
IMHO. I believe currently kube-proxy just sets iptables rules and lets
kernel do the NAT ... to look at headers and then route it you would need
to do it within pods, not within kube-proxy...

I did consider using proxy protocol, one pod with hostNetwork uses proxy
protocol to send traffic inside and then i apply affinity based on real-ip,
but why not cut that layer and just do it on the outer pod....

What is it that you are trying to optimize? The nginx example I mentioned
uses the kubernetes api directly and it cuts down on so many layers (like
dns)... you can build whatever logic you want into it.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/37146#issuecomment-264504205>,
or mute the thread

**Comment by kargakis** [comment]
@kubernetes/sig-network-feature-requests
