### ISSUE TITLE
namespace in terminating status when there is thirdpartyresources created

### ISSUE THREAD

**Issue by zhouhaibing089** [kubernetes/kubernetes#37278]
When there are ThirdpartyResources created, a namespace will not be able to be deleted successfully.

logs from kube-controller-manager:

```
I1122 09:19:12.155710    3825 namespace_controller.go:194] Finished syncing namespace "abc" (246ns)
E1122 09:19:12.155732    3825 namespace_controller.go:164] no kind "DeleteOptions" is registered for version "stable.example.com/v1"
```

logs from kube-apiserver:

```
E1122 09:20:13.662432    3803 errors.go:63] apiserver received an error that is not an unversioned.Status: no kind "DeleteOptions" is registered for version "stable.example.com/v1"
I1122 09:20:13.662657    3803 panics.go:76] DELETE /apis/stable.example.com/v1/namespaces/abc/crontabs: (292.971µs) 500
```

**steps to reproduce**:

```console
$ cat a.yaml
apiVersion: extensions/v1beta1
kind: ThirdPartyResource
metadata:
  name: cron-tab.stable.example.com
description: "A specification of a Pod to run on a cron style schedule"
versions:
- name: v1
$ kubectl create -f a.yaml
thirdpartyresource "cron-tab.stable.example.com" created
$ curl -k https://10.148.250.190:6443/apis/stable.example.com/v1 -u ${username}:${password}
{
  "kind": "APIResourceList",
  "apiVersion": "v1",
  "groupVersion": "stable.example.com/v1",
  "resources": [
    {
      "name": "crontabs",
      "namespaced": true,
      "kind": "CronTab"
    }
  ]
}
$ kubectl create ns abc
namespace "abc" created
$ kubectl delete ns abc
namespace "abc" deleted
$ kubectl get ns
NAME          STATUS        AGE
default       Active        10m
kube-system   Active        10m
abc          Terminating   1m
```

**kubernetes version**: master branch HEAD.

```console
$ kubectl version
Client Version: version.Info{Major:"", Minor:"", GitVersion:"v0.0.0-master+$Format:%h$", GitCommit:"cc0406ca26e2df2be77d989c5b97de906d2de01c", GitTreeState:"dirty", BuildDate:"2016-11-22T08:35:36Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"", Minor:"", GitVersion:"v0.0.0-master+$Format:%h$", GitCommit:"cc0406ca26e2df2be77d989c5b97de906d2de01c", GitTreeState:"dirty", BuildDate:"2016-11-22T08:44:11Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by zhouhaibing089** [comment]
ref: https://github.com/kubernetes/kubernetes/pull/35947

**Comment by pidah** [comment]
we are experiencing this issue on 1.4.6 atm

**Comment by smarterclayton** [comment]
I think we should fix this in tpr by registering delete options and then backport the fix.  Controllers are allowed to couple to apiservers, and this is a client side only problem.

**Comment by caesarxuchao** [comment]
It's a server-side problem. When decoding the DeleteOptions, the server calls the TPR decoder, which then [delegates](https://github.com/kubernetes/kubernetes/blob/master/pkg/registry/extensions/thirdpartyresourcedata/codec.go#L372) to the api.Codec, with gvk set to the thirdparty one. Shall we just hard-code the gvk to v1 in this branch? I think currently the switch case won't be hit except for decoding DeleteOptions.

**Comment by smarterclayton** [comment]
Ah.  Might as well, we implicitly version everything in v1 that is
unversioned.

On Nov 22, 2016, at 4:22 PM, Chao Xu <notifications@github.com> wrote:

It's a server-side problem. When decoding the DeleteOptions, the server
calls the TPR decoder, which then delegates
<https://github.com/kubernetes/kubernetes/blob/master/pkg/registry/extensions/thirdpartyresourcedata/codec.go#L372>
to the api.Codec, with gvk set to the thirdparty one. Shall we just
hard-code the gvk to v1 in this branch? I think currently the switch case
won't be hit except for decoding DeleteOptions.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/37278#issuecomment-262383542>,
or mute the thread

**Comment by zhouhaibing089** [comment]
@caesarxuchao your patch works for me. thanks!

**Comment by deads2k** [comment]
> It's a server-side problem. When decoding the DeleteOptions, the server calls the TPR decoder, which then delegates to the api.Codec, with gvk set to the thirdparty one. Shall we just hard-code the gvk to v1 in this branch? I think currently the switch case won't be hit except for decoding DeleteOptions. @deads2k @brendandburns

Shall we make an issue to remove that codec entirely?  I think that its only trying to write the raw TPR json out.  `runtime.Unstructured` was build for the sole purpose of funneling data like that and will serialize properly when encoded.

**Comment by smarterclayton** [comment]
I think you might even be able to register runtime.Unstructured for the
specific kind into a scheme and just get the right behavior.

On Nov 23, 2016, at 7:10 AM, David Eads <notifications@github.com> wrote:

It's a server-side problem. When decoding the DeleteOptions, the server
calls the TPR decoder, which then delegates to the api.Codec, with gvk set
to the thirdparty one. Shall we just hard-code the gvk to v1 in this
branch? I think currently the switch case won't be hit except for decoding
DeleteOptions. @deads2k <https://github.com/deads2k> @brendandburns
<https://github.com/brendandburns>

Shall we make an issue to remove that codec entirely? I think that its only
trying to write the raw TPR json out. runtime.Unstructured was build for
the sole purpose of funneling data like that and will serialize properly
when encoded.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/37278#issuecomment-262508649>,
or mute the thread

**Comment by deads2k** [comment]
> I think you might even be able to register runtime.Unstructured for the
> specific kind into a scheme and just get the right behavior.

Tried it.  Its not a drop-in.  You have to adjust creators and typers and then the list objects become an issue because `ListMeta` API retrievals don't work down in storage.  It's close, but its not all the way there.

**Comment by smarterclayton** [comment]
Ok.  At some point I'd like to come back to it.

**Comment by hectorj2f** [comment]
I can confirm that this issue remains when using v1.5.1.

```
hector@0c07434fb78a94a3 ~ $ ./kubectl version
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"clean", BuildDate:"2016-12-14T00:57:05Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1+coreos.0", GitCommit:"cc65f5321f9230bf9a3fa171155c1213d6e3480e", GitTreeState:"clean", BuildDate:"2016-12-14T04:08:28Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```
```
hector@0c07434fb78a94a3 ~ $ kubectl get ns
NAME            STATUS        AGE
bots            Active        34d
giantswarm      Active        43d
monitoring      Active        10d
tt              Terminating   1d
```

**Comment by zhouhaibing089** [comment]
I suggest that we cherry pick it into 1.4 and 1.5.

**Comment by yvespp** [comment]
Is there a workaround for this?

**Comment by george-angel** [comment]
@yvespp Delete the `thirdpartyresource`

**Comment by hectorj2f** [comment]
@george-angel This solution isn't a workaround. I am not gonna delete the `thirpartyresource` every time I want to delete a namespace.

**Comment by zhouhaibing089** [comment]
There is no true workaround, unless changing the code, compile, and
deploy...

**Comment by george-angel** [comment]
@hectorj2f Its not a silver bullet by it definitely fixed the problem I was having. Use at your own discretion of course.

**Comment by hectorj2f** [comment]
I am using `v1.5.2` and the problem seems to be fixed by #39457. I am able to delete namespaces.

**Comment by huggsboson** [comment]
Hey Folks,

We had piled up a bunch of broken namespaces so I created a script to get rid of them until we can get onto 1.5.x.  It's an ugly bit of bash.  It tries to clean up resources before back-dooring kube.  Feedback welcome.
```
#!/bin/sh

# space separated list of tpr names e.g. a b c
tprs=( tpr1 tpr2 tpr3 )

etcd_servers="https://youretcdserver1:2379,https://youretcdserver2:2379,..."
etcdctl_args="--ca-file=/path/to/your.pem --cert-file=/path/to/your.crt --key-file=/path/to/your.key"
etcdctl_cmd="sudo etcdctl -C $etcd_servers $etcdctl_args"

if ! command -v kubectl >/dev/null; then
   echo "kubectl not found."
   exit 1
fi

if ! command -v etcdctl >/dev/null; then
   echo "etcdctl not found."
   exit 1
fi

if [[ -z "$1" ]]; then
    echo "Usage: murder-namespace <namespace-name>" 2>&1
    exit 1
fi

echo "About to delete these resources from $1 {"
kubectl get cm,ds,deploy,jobs,pods,rs,secrets,sa,svc --namespace=$1
for tpr in "${tprs[@]}"; do
    kubectl get $tpr --namespace=$1
done
printf "}\n\n"

echo "Deleting {"
kubectl delete cm,ds,deploy,jobs,pods,rs,secrets,sa,svc --namespace=$1 --all
for tpr in "${tprs[@]}"; do
    kubectl get $tpr --namespace $1 -ojsonpath='{range .items[*]}{.metadata.name}{"\n"}{end}' | xargs --no-run-if-empty -n1 kubectl delete $tpr --namespace=$1
done
printf "}\n\n"

echo "Here's what's left {"
kubectl get cm,ds,deploy,jobs,pods,rs,secrets,sa,svc --namespace=$1
for tpr in "${tprs[@]}"; do
    kubectl get $tpr --namespace=$1
done
printf "}\n\n"

echo "Removing namespace in etcd {"
$etcdctl_cmd rm /registry/namespaces/$1
printf "}\n\n"
```

**Comment by nikinath** [comment]
This issue seems to be fixed in 1.5.2.

Logs:

```
$ kubectl create namespace mynamespace
namespace "mynamespace" created

$ cat resource.yaml
apiVersion: extensions/v1beta1
kind: ThirdPartyResource
metadata:
  name: cron-tab.stable.example.com
description: "A specification of a Pod to run on a cron style schedule"
versions:
- name: v1

$ kubectl create -f resource.yaml
thirdpartyresource "cron-tab.stable.example.com" created

$ kubectl delete namespace mynamespace
namespace "mynamespace" deleted

$ kubectl get namespace
NAME          STATUS    AGE
default       Active    10h
kube-public   Active    10h
kube-system   Active    10h
```

It is fixed by https://github.com/kubernetes/kubernetes/blob/master/pkg/registry/extensions/thirdpartyresourcedata/codec.go#L367. (PR https://github.com/kubernetes/kubernetes/pull/37328)

When a namespace is deleted, the namespace controller deletes all the deletable resources under that namespace. In case it is a TPR resource, the delete options failed to be decoded by a TPR GVK.

Before, the GVK sent to the delegated codec was a thirdparty one which was not recognized by the delegated codec. So we needed to check the defaulting GVK and send it onwards if it doesn't point to our thirdparty group.

Now, if it points to the TPR group, the GVK is set to nil and then sent to the codec, which it recognizes and hence everything works fine!

**Comment by zhouhaibing089** [comment]
@nikinath FYI, #37328 also needs to pair with: https://github.com/kubernetes/kubernetes/blob/master/pkg/master/thirdparty/thirdparty.go#L290.

**Comment by nikinath** [comment]
@zhouhaibing089 Oh yes, I think the check for GVK is done by calling `registered.IsThirdPartyAPIGroupVersion` and for that we need to register the TPRs. Thanks!
