### ISSUE TITLE
Need consistent printing for Name, Namespace, etc

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#3731]
From #3729 

We should land on one syntax for printing namespace and name (for all sorts of objects) "namespace/name" vs "name.namespace" vs other.

namepsace/name has an advantage when both name and namespace are DNS subdomains: "foo.bar/quux.zorb" is clear, while "quux.zorb.foo.bar" is ambiguous.

If we all agree, we should start enforcing it in code reviews and fixing it up when we find it.

**Comment by dchen1107** [comment]
Vote for namespace/name. Once we enforce this, the logging could be a little bit less verbose.

**Comment by bgrant0607** [comment]
In what context? User-visible messages?

What about partial URLs?

**Comment by thockin** [comment]
Context is primarily logs and maybe error messages

**Comment by derekwaynecarr** [comment]
Namespace/name works for me for logs and error messages.

Even better if we have a utility that returns that for me so we can just enforce its usage.

**Comment by smarterclayton** [comment]
In the other issue I commented this should be in api/meta.  For object refs we want to go a step further and print additional ref info (uid resource version) which in some log contexts is also useful

**Comment by quinton-hoole** [comment]
PR #5192 provides a possible canonical implementation of "namespace/name" format in pkg/types/valid/namespacedname.go.
Do we want to standardize on using that?

**Comment by bgrant0607** [comment]
Most people seem to be in favor of namespace/name. I will point out, however, that that's not sufficient to identify an object. One also needs at least the kind or resource path. Since names and namespaces exclude `/`, we could support both 2- and 3-part short names: namespace/name and namespace/resourcepath/name.

**Comment by smarterclayton** [comment]
namespace/resourcepath/name seems a bit confusing (because I would assume resource path dominates namespace), but our API does take that pattern.

**Comment by bgrant0607** [comment]
Yes, I'm trying to avoid introduction of yet another naming schema for fully qualified names. While it's less concise, I'd be happy with URL suffixes (omitting apiserver address, path root, and api version). Actually, it's even debatable whether we can omit api version, since not all objects exist in all versions, at least not at the same paths.

**Comment by smarterclayton** [comment]
We at least (today) use the provided api version to convert resource types from the cli to the internal type.  So clients can control that via --api-version.

**Comment by smarterclayton** [comment]
I'm ok with namespace/resource/name, until we need to introduce namespace/*/* selectors :)

**Comment by bgrant0607** [comment]
Using #8225 for format in logs. Using this for format in kubectl output.

**Comment by bgrant0607** [comment]
See also #10626

**Comment by bgrant0607** [comment]
And #10591

**Comment by bgrant0607** [comment]
Also relevant: #10009 and #7111
