### ISSUE TITLE
It's not necessary for Kube Proxy to SNAT UDP Packets

### ISSUE THREAD

**Issue by boynux** [kubernetes/kubernetes#37396]
**What happened**:
Source address in UDP packets are the only way to reliably identifies the originator and many UDP based systems (like Radius servers) rely on this fact. Kube Proxy in iptables mode masks the originator IP by obfuscating the originator address when forwards the request to the POD.

**What you expected to happen**:
Option in Server config or Kube Proxy settings to override this behavior and leave UDP packets originators untouched. Since UDP packets are state less it can be routed back to the originator from the POD directly.

**How to reproduce it** (as minimally and precisely as possible):
Launch a POD and listen for UDP packets on any port, the create a service and expose a NodePort. Any request comes to POD through NodePort is from Node IP address.

**Comment by kargakis** [comment]
@kubernetes/sig-network-misc

**Comment by thockin** [comment]
This is not true in all environments.  DNS, for example, will complain or
reject replies from any IP except the one it targetted.

This should be covered by the OnlyLocal work which we hope to progress in
1.6 or at worst 1.7

@mrhohn

**Comment by boynux** [comment]
Yes, that's true in case of dns which does not really care about the source
of the request however it's also not the case for all types of services,
when service wants to know the originator address, which will be changed
now, however ipvs (lvs) directly routing would be a solution as well (
which currently docker Swarm uses)

**Comment by thockin** [comment]
LVS direct return is only viable with a very different model of Services
than Kube offers, including no port remapping.

**Comment by boynux** [comment]
That's also true, I'm just exploring the possibilities.
There might be 1 in 100 of the applications that need this feature
including mine (radius)  which I deployed it outside of the cluster for
now. But it's not a big chunk of applications anyway.

Tproxy might be another option which I'm currently exploring too. But this
is going to be way more complex than lvs which I'm willing to sacrifice
port mapping in favor of that.

Thanks for the comment

**Comment by thockin** [comment]
Did you look at the OnlyLocal logic?  This is designed specifically to
avoid SNAT

**Comment by boynux** [comment]
No, i'll look. Thanks for the hint.

**Comment by kad** [comment]
But if we forget about chances where it is really required, do we have reasons why at all for both TCP and UDP we have SNAT which hides real client ip ? Is it covered by some design document ?

**Comment by thockin** [comment]
The SNAT is required for external traffic because of the way most
load-balancers work.  They can only target a VM, so kube-proxy
"re-balances" which means it might reroute to a different node.  When that
happens, the final node tries to reply directly to the client, which
doesn't work.

OnlyLocal accepts the limitation of (im)balancing to nodes, in exchange for
not losing the client IP.

**Comment by boynux** [comment]
That's correct and OnlyLocal has its own limitations, on the other hand this requirement is only due to limitations of kube-proxy in first place.

Using IPvS or probably some sort of TProxy hack will make it possible to use multi nodes pods and preserve the client IP. But for I'm just looking for a "quick fix" even if that means sacrificing some features and flexibility.

OnlyLocal seems to be that "quick fix" and there is a PR for IPvS already open.
Thanks

**Comment by thockin** [comment]
IPVS is not a panacea.  It has a masquerade mode, which I am 99% sure
suffers the same problems, or a direct return mode which can not do things
like port remapping, and which requires other routing tricks.

I don't think there is a good fix without loss of function, yet.

On Mar 18, 2017 1:27 AM, "Mohammad Arab" <notifications@github.com> wrote:

That's correct and OnlyLocal has its own limitations, on the other hand
this requirement is only due to limitations of kube-proxy in first place.

Using IPvS or probably some sort of TProxy hack will make it possible to
use multi nodes pods and preserve the client IP. But for I'm just looking
for a "quick fix" even if that means sacrificing some features and
flexibility.

OnlyLocal seems to be that "quick fix" and there is a PR for IPvS already
open.
Thanks

—
You are receiving this because you are on a team that was mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/37396#issuecomment-287525477>,
or mute the thread

**Comment by boynux** [comment]
@thockin You are right "IPvS is not a panacea" neither current iptables hack.
IPvS is good because it gives you options, you can use NAT mode or Direct Routing depending on the situation. It's more reliable, flexible and performant than iptables because it is, well, a load balancer. I don't think it's necessary to throw away the current implementation rather adding another option for users with different requirements who need more performant and reliable solution.

IPvS besides different types of load balancing has options for different routing policies like round-robin, weight-routing, least-connections and ... It is also takes care of origin health and if origin does not respond it will choose another origin.

For my case I forced to take two services out of my K8S cluster just because load-balancing issues I wished I could sacrifice port mapping to avoid this. And I'm sure there are other people out there with similar problems. For me Ingress is not an options either due to it's state and also very similar limitations.

Current proxy in K8S is definitely a bottleneck and should be replaced with a more robust solution IMO.

 TProxy might fix some limitations of current iptables implementations but it's also just another hack to fix the current situation. But could be much easier to integrate for a quick win (I really don't have time to test this idea though).

**Comment by thockin** [comment]
On Mar 18, 2017 1:13 PM, "Mohammad Arab" <notifications@github.com> wrote:

@thockin <https://github.com/thockin> You are right "IPvS is not a panacea"
neither current iptables hack.
IPvS is good because it gives you options, you can use NAT mode or Direct
Routing depending


With big caveats

 on the situation. It's more reliable, flexible and performant than
iptables because it is, well, a load balancer. I don't think it's necessary
to throw away the current implementation rather adding another option for
users with different requirements who need more performant and reliable
solution.

IPvS besides different types of load balancing has options for different
routing policies like round-robin, weight-routing, least-connections and
... It is also takes care of origin health and if origin does not respond
it will choose another origin.


It does not retry failed connections, by my testing.  Please show me where
that is documented, because I couldn't make it work.

Don't get me wrong - I think IPVS even in NAT my desk would be better than
our current iptables, if only for obviousness.

For my case I forced to take two services out of my K8S cluster just
because load-balancing issues I wished I could sacrifice port mapping to
avoid this. And I'm sure there are other people out there with similar
problems. For me Ingress is not an options either due to it's state and
also very similar limitations.


Can you detail the issues?

Current proxy in K8S is definitely a bottleneck and should be replaced with
a more robust solution IMO.


A bottleneck?  Even with only-local?  There's almost no per-packet
processing being done.  It is entirely in-kernel.

TProxy might fix some limitations of current iptables implementations but
it's also just another hack to fix the current situation. But could be much
easier to integrate for a quick win (I really don't have time to test this
idea though).

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/37396#issuecomment-287571609>,
or mute the thread

**Comment by boynux** [comment]
Sorry for the confusion, I didn't mean LVS can retry the failed connection, specially in DR mode, it doesn't even know that the origin has failed, because it doesn't not intercept the packets. For NAT mode however it will mark origins as inactive. Anyhow a supervisor is required like the one currently handling iptables rules to remove or add new origins. What I meant is the behaviour in NAT mode.

The issue is that OnlyLocal does not give me the option to distribute the load easily over the cluster and I need a second layer of load-balancer on top of it. 

I'm running a cluster of Radius servers using FreeRadius (plus a handful of services and cassandra, kafka and ... all in the k8s cluster) and in order to find the originator NAS I need to reliably get the AAA packet originator IP address. as a workaround I'm currently running another radius server which proxies the requests to the original radius inside the cluster. Meaning that I'm running a second instance of service just to proxy the request and including realm into proxied packets to find the originator from the cluster's Radius server. This approach works with some serious limitations, first, I need another proxy which needs failover and monitor which is obviously can not be handled by K8S and second another load-balancer (I'm using iptables on another machine without SNAT) to distribute the load over all the cluster nodes. As you see it's very difficult to maintain and monitor.

This setup currently works but I don't have confidence to roll it out to the production.

**Comment by thockin** [comment]
On Sat, Mar 18, 2017 at 3:20 PM, Mohammad Arab <notifications@github.com> wrote:
>
> Sorry for the confusion, I didn't mean LVS can retry the failed connection, specially in DR mode, it doesn't even know that the origin has failed, because it doesn't not intercept the packets. For NAT mode however it will mark origins as inactive. Anyhow a supervisor is required like the one currently handling iptables rules to remove or add new origins. What I meant is the behaviour in NAT mode.

We have such a supervisor - it is the general kube liveness/readiness
probe system.  When a pod isn't alive or isn't ready, we remove it
from all sets of rules.

> The issue is that OnlyLocal does not give me the option to distribute the load easily over the cluster and I need a second layer of load-balancer on top of it.

Well, this is exactly the tradeoff.  If your LB doesn't understand
containers, just machines, then you have to pick your evil - SNAT and
double hop with good balance or OnlyLocal and risk imbalance.  The
only other option I see is for your LB to balance directly to
containers.  If you can do that you absolutely should.

Or, if your LB can do weights you could program it with the
proportions of pods-per-each-VM, which will dramatically reduce the
imbalance.

**Comment by quinton-hoole** [comment]
We have a tested implementation of IPVS kubeproxy in https://github.com/kubernetes/kubernetes/issues/44063
Busy tying the various related issues and PR's together now.

**Comment by caseydavenport** [comment]
> This should be covered by the OnlyLocal work which we hope to progress in
1.6 or at worst 1.7

So IIUC the concerns in this issue are probably covered by either OnlyLocal + IPVS kubeproxy (#44063), right?  If so, can we close this issue?

@thockin is there an issue for extending OnlyLocal support to other cloud providers besides GCE?  I wasn't able to find it (there's https://github.com/kubernetes/features/issues/27 for GCP).

**Comment by thockin** [comment]
OnlyLocal should not be specific to GCE.  @MrHohn can reply with an issue for non-GCE issues

**Comment by MrHohn** [comment]
@caseydavenport  FYI some folks are working on adding OnlyLocal support to AWS - #43585.
