### ISSUE TITLE
No system/misc stats in Summary API on master

### ISSUE THREAD

**Issue by piosz** [kubernetes/kubernetes#37453]
**Kubernetes version** (use `kubectl version`):
1.4.6

**Environment**:
GCE

**What happened**:
I created a cluster for Heapster testing purposes to debug failing test in https://github.com/kubernetes/heapster/pull/1394. It turned out that Summary API does not export system/misc stats in SystemContainers section (though there are kubelet and docker stats). Everything works as expected on nodes.

See also https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/heapster/1394/pull-heapster-e2e/31/

**Comment by timstclair** [comment]
What node OS were you using? We don't create the system (misc) container on systemd, so it's expected that GCI nodes don't report those stats.

**Comment by piosz** [comment]
The default configuration for 1.4, which is:
master: GCI
nodes: Container VM

**Comment by timstclair** [comment]
Are the nodes running 1.4.6 too? There was a bug with this in 1.4.5, but it should have been fixed in 1.4.6.

**Comment by piosz** [comment]
Yes, both are running in 1.4.6. If you want to reproduce from Heapster current head run `make test-integration`. It will take some time and as a side effect you should have a cluster with the mentioned problem. This was catch by integration tests and I temporary disabled the check here https://github.com/kubernetes/heapster/pull/1394/files#diff-af263c749dde31773664d8eb738eec4e

**Comment by timstclair** [comment]
@dashpole  if you have spare cycles, can you look into this?

**Comment by piosz** [comment]
friendly ping

**Comment by dashpole** [comment]
Looking at it now

**Comment by dashpole** [comment]
I have found a couple things so far.
On the containerVM nodes, cadvisor is exporting a container with "name": "/system"
On the GCI Master, cadvisor is exporting a container with "name": "/system.slice"
The [default salt config for kubelet](https://github.com/kubernetes/kubernetes/blob/master/cluster/saltbase/salt/kubelet/default) has this: "{% set system_container = "--system-cgroups=/system" -%}" (/system is the default misc container name)

So the real question is: Should cadvisor export "/system" instead of "system.slice" on GCI?  Or should we be configuring GCI to use "--system-cgroups=/system.slice"?

**Comment by dchen1107** [comment]
I thought we fix this very issue for 1.4 branch by @timstclair a while back.  @piosz Are you running into the same issue with 1.5?

**Comment by timstclair** [comment]
@dashpole I think I told you the wrong thing earlier. We don't support the misc (/system) cgroup on systemd systems (I can't remember why, but it was an explicit decision - @vishh or @derekwaynecarr might know). The `/system.slice` is something different, I believe a base systemd cgroup (slice).

As for the misc container on ContainerVM nodes, we've been testing for the misc container in 1.5+ in the summary api test (https://k8s-testgrid.appspot.com/google-node#kubelet) for a while, and I haven't seen this issue. So if this is still reproducible, it's limited to 1.4.

@dchen1107 See this [comment above](https://github.com/kubernetes/kubernetes/issues/37453#issuecomment-263679213) the bug was created for the post-fix.

**Comment by timstclair** [comment]
Found the explanation here: https://github.com/kubernetes/community/blob/795d951bba8bad8bcb67feacc18d741eac8c3597/contributors/design-proposals/kubelet-systemd.md#system-reserved

> The current meaning of `system-container` is inadequate on `systemd` environments.
The `kubelet` should use the flag to know the location that has the processes that
are associated with `system-reserved`, but it should not modify the cgroups of
existing processes on the system during bootstrapping of the node.  This is
because `systemd` is the `cgroup manager` on the host and it has not delegated
authority to the `kubelet` to change how it manages `units`.

**Comment by dashpole** [comment]
@piosz IIUC this is intended behavior on systemd nodes.  Based on the explanation @timstclair provided, the kubelet doesnt have the authority to control "misc" processes on systemd.

**Comment by vishh** [comment]
+1. "misc" is just a bandaid for cvm.

**Comment by piosz** [comment]
Ok, so I'm closing this issue.
