### ISSUE TITLE
Kubelet on AWS should use Instance Metadata instead of IAM roles

### ISSUE THREAD

**Issue by hanikesn** [kubernetes/kubernetes#37492]
As of the recent changes the masters attach/detach EBS volumes on AWS nodes. That means it shouldn't be necessary to assign IAM roles to the instances anymore.

When testing that out with we found that the kublet version 1.4.6 didn't start:
```
error: failed to run Kubelet: could not init cloud provider "aws": error finding instance i-xxxx: error listing AWS instances: NoCredentialProviders: no valid providers in chain
```
Even without an IAM role it's still possible to query the [EC2 Metadata API](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-metadata.html) to fetch the required information and that method of information retrieval should be used when no IAM roles are assigned.

Assigning IAM roles to the nodes is also a security risk as Pods can easily query the EC2 Metadata API to fetch the IAM roles. This can also be prevented by blocking access to `169.254.169.254` which is the endpoint of the EC2 Metadata API.

**Comment by justinsb** [comment]
Two reasons we need access right now I believe:

1) https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/aws/aws.go#L1401-L1408
2) To find our tags, in particular KubernetesCluster

For the first, we should now (finally) be able to name instances with non-resolvable names, so we can probably move to `i-12345678` for example.

But the second remains a problem I think - any suggestion @hanikesn ?

(I'm also not sure, but we might use DescribeInstances to check if a volume is attached also, though I think that this has now moved to the master).

I agree that IAM lockdown is an issue, which is why we're looking at solutions like kube2iam.

**Comment by hanikesn** [comment]
> For the first, we should now (finally) be able to name instances with non-resolvable names, so we can probably move to i-12345678 for example.

There's also `curl http://169.254.169.254/latest/meta-data/local-hostname` which gives me the same hostname as `ec2:Describe*`.

> But the second remains a problem I think - any suggestion @hanikesn ?

Honestly, I'm pretty suprised to find out that you can't query the tags of your instance with the metdata API. Unfortunately I don't have any contacts to influence that.

But I would be fine with only giving it `ec2:DescribeTags` for now. Seems better than the current default.

**Comment by justinsb** [comment]
`local-hostname` is different when you're using a custom DHCP domain, for reasons I don't fully understand.  Moving to use the instance id as identifier, or passing in the Node objects into the cloudprovider is probably an easier way forwards here.

But I think this is a good idea - I think we can certainly lock down IAM to DescribeTags and DescribeInstances.

**Comment by hjacobs** [comment]
@justinsb @hanikesn I would love to have a more configurable approach regarding "AWS environment detection". The `KubernetesCluster` tag leads currently to issues like #35052 and I think something like cluster name / ID could also be (optionally) passed via a config flag instead of calling `ec2:DescribeTags`.
