### ISSUE TITLE
Compare openapi compiler output with our proto files

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#37573]
https://github.com/googleapis/openapi-compiler

I think it would be interesting to see what the difference is, and see if there's anything we should change in our openapi spec, our proto files, or this complier to make them more similar.

I guess maybe this is medium priority to take a look, just in case it turns up something we want to change?

**Comment by lavalamp** [comment]
@mbohlool @smarterclayton

**Comment by mbohlool** [comment]
Interesting, I remember seeing this (or a similar) project that compiled swagger/OpenAPI spec to an intermediate language and then generated client from that but it wasn't clear at the time that the intermediate state is ProtoBuff (or maybe it wasn't and they changed it). I talked with the person working on that to see if we can use the compiler to generate better clients and it wasn't possible at the time. I will give this another try and report here.

**Comment by mbohlool** [comment]
OK, this wasn't what I (and I guess you) thought. It does not generate a .proto file from an OpenAPI spec, it merely change the format of OpenAPI spec from json to a protobuf message (in binary or text format) to be consumed using a protobuff reader rather than a json reader. I should say I am disappointed. Please let me know if I am wrong (and I enthusiastically hope that I am wrong).

**Comment by lavalamp** [comment]
Oh. That's not very interesting.
