### ISSUE TITLE
kube-apiserver: startup code should tolerate starting before etcd

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#37704]
See: https://github.com/kubernetes/kubernetes/blob/v1.6.0-alpha.0/pkg/master/controller.go#L126

This code should make several attempts before `Fatalf`ing. Alternatively, we could consider not listening for connections until this code has succeeded.

**Comment by davidmckayv** [comment]
#dibs

**Comment by psaintlaurent** [comment]
Feel free to correct me if I'm wrong on any of this since I've never looked at kubernetes code base before.

The code for the [node port repair controller](https://github.com/kubernetes/kubernetes/blob/v1.6.0-alpha.0/pkg/registry/core/service/portallocator/controller/repair.go#L76 ) and the[ ip cluster repair controller](https://github.com/kubernetes/kubernetes/blob/v1.6.0-alpha.0/pkg/registry/core/service/ipallocator/controller/repair.go#L92) both appear to make multiple attempts before returning an error which leads to a Fatal.

Would this be handled better elsewhere in the codebase?

**Comment by k82cn** [comment]
@lavalamp , I think we had waited for 10s for etcd to start at https://github.com/kubernetes/kubernetes/blob/v1.6.0-alpha.0/pkg/registry/core/service/ipallocator/controller/repair.go#L94 . Do we need to wait more or make it configurable?

**Comment by stu-gott** [comment]
I would like to work on this if nobody else is.

**Comment by lavalamp** [comment]
No need to ask for permission! Just say here that you're working on it, that should be sufficient to prevent duplicate work. :)

**Comment by karsinkk** [comment]
@stu-gott @lavalamp  Can I have a go at this?

**Comment by stu-gott** [comment]
I have a nearly completed solution for this already. Just working on testing/test cases. WIll hopefully sumbit a PR shortly.

**Comment by karsinkk** [comment]
@stu-gott  Ok.

**Comment by mml** [comment]
I wondered why we care about this.  After all, kubelet restarts failing pods.  For posterity, after talking with @lavalamp, the reason is that the apiserver may fail so fast that the kubelet begins to back off on restarts of a failing pod.  That backoff may be too aggressive.  (Maybe it causes spurious alerts, or maybe it allows too much downtime.)  So, let's fix the apiserver.

That's fine, but clearly we're not the only user that might encounter this.  You may be running a server you don't want to (or can't) modify, and you might wish you could tweak the kubelet's backoff heuristics *for your pod*.

Alternately, maybe the kubelet could choose not to enter the backoff if apiserver exited with a different code.  @kubernetes/sig-node-feature-requests anything like this already in place?

**Comment by psaintlaurent** [comment]
@mml That's a wonderful explanation that hadn't occurred to me. If there isn't a feature request for this already I'll work on something and reference this issue.

**Comment by yujuhong** [comment]
> That's fine, but clearly we're not the only user that might encounter this. You may be running a server you don't want to (or can't) modify, and you might wish you could tweak the kubelet's backoff heuristics for your pod.
> 
> Alternately, maybe the kubelet could choose not to enter the backoff if apiserver exited with a different code. @kubernetes/sig-node-feature-requests anything like this already in place?

AFAIK, the backoff mechanism is there to protect kubelet from being overwhelmed by failed user containers. Trusting the containers with returning a specific exit code sounds like a big "no" to me. Making this configurable per pod *might* be ok, but it's still not good in general to allow aggressive restarts.

**Comment by nikhiljindal** [comment]
The referred PR (https://github.com/kubernetes/kubernetes/pull/39821) only fixes the issue for kube-apiserver. We still need a generic fix in genericapiserver (Ref https://github.com/kubernetes/kubernetes/pull/39821#discussion_r103298724).
