### ISSUE TITLE
seLinuxOptions in pod level and container level has different result

### ISSUE THREAD

**Issue by mdshuai** [kubernetes/kubernetes#37809]
**Kubernetes version** (use `kubectl version`):
v1.6.0-alpha.0.1063+39e64fde8ca42e-dirty

**Environment**:
```
[root@ip-172-18-6-200 selinux]# docker version
Client:
 Version:         1.12.3
 API version:     1.24
 Package version: docker-common-1.12.3-8.el7.x86_64
 Go version:      go1.6.2
 Git commit:      8b91553-redhat
 Built:           Wed Nov 16 11:35:08 2016
 OS/Arch:         linux/amd64

Server:
 Version:         1.12.3
 API version:     1.24
 Package version: docker-common-1.12.3-8.el7.x86_64
 Go version:      go1.6.2
 Git commit:      8b91553-redhat
 Built:           Wed Nov 16 11:35:08 2016
 OS/Arch:         linux/amd64

```

**What happened**:
Create pod with same seLinuxOptions in pod level and container level, then check selinux context label in container, it has different result, I don't know it's a bug or it's correct.

**How to reproduce it** (as minimally and precisely as possible):
```
1. Run a pod with seLinuxOptions in pod level
[root@ip-172-18-6-200 selinux]# kc create namespace dma
namespace "dma" created
[root@ip-172-18-6-200 selinux]# kc create -f https://raw.githubusercontent.com/mdshuai/testfile-openshift/master/k8s/securityContext/pod-selinux.yaml --namespace dma
pod "hello-pod" created
[root@ip-172-18-6-200 selinux]# kc get po --namespace dma
NAME        READY     STATUS    RESTARTS   AGE
hello-pod   1/1       Running   0          12s
[root@ip-172-18-6-200 selinux]# kc exec -it hello-pod --namespace dma -- /bin/sh
sh-4.2# ls -lZ
-rw-r--r--. root root unconfined_u:object_r:svirt_sandbox_file_t:s0:c25,c968 anaconda-post.log
lrwxrwxrwx. root root unconfined_u:object_r:svirt_sandbox_file_t:s0:c25,c968 bin -> usr/bin
drwxr-xr-x. root root unconfined_u:object_r:svirt_sandbox_file_t:s0:c25,c968 dev
drwxr-xr-x. root root unconfined_u:object_r:svirt_sandbox_file_t:s0:c25,c968 etc
-rwxr-xr-x. root root unconfined_u:object_r:svirt_sandbox_file_t:s0:c25,c968 hello-pod
drwxr-xr-x. root root unconfined_u:object_r:svirt_sandbox_file_t:s0:c25,c968 home
lrwxrwxrwx. root root unconfined_u:object_r:svirt_sandbox_file_t:s0:c25,c968 lib -> usr/lib
lrwxrwxrwx. root root unconfined_u:object_r:svirt_sandbox_file_t:s0:c25,c968 lib64 -> usr/lib64
drwx------. root root unconfined_u:object_r:svirt_sandbox_file_t:s0:c25,c968 lost+found
drwxr-xr-x. root root unconfined_u:object_r:svirt_sandbox_file_t:s0:c25,c968 media
drwxrwxrwx. root root unconfined_u:object_r:svirt_sandbox_file_t:s0:c25,c968 mnt
drwxr-xr-x. root root unconfined_u:object_r:svirt_sandbox_file_t:s0:c25,c968 opt
dr-xr-xr-x. root root system_u:object_r:proc_t:s0      proc
dr-xr-x---. root root unconfined_u:object_r:svirt_sandbox_file_t:s0:c25,c968 root
drwxr-xr-x. root root unconfined_u:object_r:svirt_sandbox_file_t:s0:c25,c968 run
lrwxrwxrwx. root root unconfined_u:object_r:svirt_sandbox_file_t:s0:c25,c968 sbin -> usr/sbin
drwxr-xr-x. root root unconfined_u:object_r:svirt_sandbox_file_t:s0:c25,c968 srv
dr-xr-xr-x. root root system_u:object_r:sysfs_t:s0     sys
drwxrwxrwt. root root unconfined_u:object_r:svirt_sandbox_file_t:s0:c25,c968 tmp
drwxr-xr-x. root root unconfined_u:object_r:svirt_sandbox_file_t:s0:c25,c968 usr
drwxr-xr-x. root root unconfined_u:object_r:svirt_sandbox_file_t:s0:c25,c968 var
sh-4.2# runcon 
unconfined_u:unconfined_r:svirt_lxc_net_t:s0:c25,c968

2. Run a pod with seLinuxOptions in container level
[root@ip-172-18-6-200 selinux]# kc create namespace dma1
namespace "dma1" created
[root@ip-172-18-6-200 selinux]# kc create -f https://raw.githubusercontent.com/mdshuai/testfile-openshift/master/k8s/securityContext/container-selinux.yaml --namespace dma1
pod "hello-pod" created
[root@ip-172-18-6-200 selinux]# kc get po --namespace dma1
NAME        READY     STATUS    RESTARTS   AGE
hello-pod   1/1       Running   0          11s
[root@ip-172-18-6-200 selinux]# kc exec -it hello-pod --namespace dma1 -- /bin/sh
sh-4.2# ls -lZ
-rw-r--r--. root root system_u:object_r:svirt_sandbox_file_t:s0:c3,c298 anaconda-post.log
lrwxrwxrwx. root root system_u:object_r:svirt_sandbox_file_t:s0:c3,c298 bin -> usr/bin
drwxr-xr-x. root root system_u:object_r:svirt_sandbox_file_t:s0:c3,c298 dev
drwxr-xr-x. root root system_u:object_r:svirt_sandbox_file_t:s0:c3,c298 etc
-rwxr-xr-x. root root system_u:object_r:svirt_sandbox_file_t:s0:c3,c298 hello-pod
drwxr-xr-x. root root system_u:object_r:svirt_sandbox_file_t:s0:c3,c298 home
lrwxrwxrwx. root root system_u:object_r:svirt_sandbox_file_t:s0:c3,c298 lib -> usr/lib
lrwxrwxrwx. root root system_u:object_r:svirt_sandbox_file_t:s0:c3,c298 lib64 -> usr/lib64
drwx------. root root system_u:object_r:svirt_sandbox_file_t:s0:c3,c298 lost+found
drwxr-xr-x. root root system_u:object_r:svirt_sandbox_file_t:s0:c3,c298 media
drwxrwxrwx. root root system_u:object_r:svirt_sandbox_file_t:s0:c3,c298 mnt
drwxr-xr-x. root root system_u:object_r:svirt_sandbox_file_t:s0:c3,c298 opt
dr-xr-xr-x. root root system_u:object_r:proc_t:s0      proc
dr-xr-x---. root root system_u:object_r:svirt_sandbox_file_t:s0:c3,c298 root
drwxr-xr-x. root root system_u:object_r:svirt_sandbox_file_t:s0:c3,c298 run
lrwxrwxrwx. root root system_u:object_r:svirt_sandbox_file_t:s0:c3,c298 sbin -> usr/sbin
drwxr-xr-x. root root system_u:object_r:svirt_sandbox_file_t:s0:c3,c298 srv
dr-xr-xr-x. root root system_u:object_r:sysfs_t:s0     sys
drwxrwxrwt. root root system_u:object_r:svirt_sandbox_file_t:s0:c3,c298 tmp
drwxr-xr-x. root root system_u:object_r:svirt_sandbox_file_t:s0:c3,c298 usr
drwxr-xr-x. root root system_u:object_r:svirt_sandbox_file_t:s0:c3,c298 var
sh-4.2# runcon 
system_u:system_r:svirt_lxc_net_t:s0:c3,c298


```

**Anything else do we need to know**:

**Comment by mdshuai** [comment]
@pmorie @derekwaynecarr Help check, thanks.

**Comment by mdshuai** [comment]
@eparis @rhatdan Could you help look at this selinux too?

**Comment by mdshuai** [comment]
This should fixed by https://github.com/docker/docker/pull/30652

**Comment by rhatdan** [comment]
This also needs to be fixed on Kubernetes, Kubernetes should be specifying a label for the pause container as well as any containers it joins to the pod.

**Comment by coeki** [comment]
@rhatdan I thought the pause container could run in the default label as specified by the system, and the containers joining could have their own label. As discussed in https://github.com/kubernetes/kubeadm/issues/107

However consensus was agreed on, to set pod security instead of container security, so the pause and other containers joining it, would have the same labels. At least this was the fix for kubeadm. 

Thoughts?

**Comment by rhatdan** [comment]
Sure that will work, and with the fix, when it gets merged into docker would allow you to run multiple different labels on different containers within the same pod.  But I believe if the caller specified he wants the pod to run as spc_t, then the pod processes should run as spc_t.

**Comment by eparis** [comment]
I'm not sure I understand the problem. If we specify something at the pod level everything without some other specification should get that label. If we specify something at the container level that container should get that specification.

What needs to change with kube? What are we improperly requestion?

**Comment by rhatdan** [comment]
I thought there was an issue with not being able to specify a security label at the pod level, only at the container level, which triggered this bug.  If the pod label had been set to spc_t then this would not have been a problem.

The problem was that k8s was not specifying the label at the pod level, so the pause container was running with something like container_t:s0:c1,c2, and then you attempted to set the first container as spc_t, docker was and still is currently ignoring the second label if the container is joining a currently running container (pause).  My patch will fix this, if/when docker gets around to merging it.  We are shipping the fix in the projectatomic/docker versions.

**Comment by eparis** [comment]
kube allows both. One can set a label at the pod level or at the container level. When set at the pod level I thought ( @mdshuai can correct me if I'm wrong) things work fine. When set only at the container level we hit the problem which you are hopefully going to get fixed in upstream docker.

So I think we are good (once you get the docker pr merged upstream that is, thank you for getting it into atomic

**Comment by coeki** [comment]
@mdshuai was showing that pod level security was not working, because your fix (@rhatdan)  was not there. That was the problem. If you look at his 2 pod specs you see that, one was on pod level, not working, should work with your patch, and the second spec showing at container level it was as expected behavior, as Eric pointed out. So with the fix everything is good ;)

**Comment by mdshuai** [comment]
@eparis you are right, pod level and container should work both and have same selinux result if only set one of them.

**Comment by rhatdan** [comment]
I would refrase this to say that they should have one label if the POD Label is set but the container label is not set.  
If you set the container label it could be different then the pod label, since the pod label will get the default label and the container label will get the specified label.
