### ISSUE TITLE
Is it safe to share the OAuth/OIDC client-secret?

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#37822]
Kubernetes advertises support for OAuth / OIDC, but it requires putting the client-secret into the kubecfg file.  i.e. it shares the OAuth client-secret with end users.  This seems (on the surface) to be unsafe - I have not yet found any indication that the client secret is in fact _not_ a secret.

Some providers (e.g. tremolo) will generate a per-auth client-secret, so that the client-secret is no more a secret than the auth-token & refresh-token.

Is there any documentation to support the notion that client-secret is in fact not a secret, and it is safe to share the secret in this way?

(Thanks to @mlbiam for talking this over with me in sig-auth, and for explaining that this is a bad idea anyway in terms of policy and likely wouldn't pass an audit; his suggestion was that k8s should implement a traditional OAuth flow).

cc @kubernetes/sig-auth

**Comment by mlbiam** [comment]
More specifically instead of using the id_token, the kubernetes config file should use the access_token and then check it against the OP (OpenID Connect Identity Provider) to make sure its valid.  

The problem with this approach is that there's no standard way to do this (I'm pretty sure in discussions with @ericchiang this was one of the main reasons that the current approach is taken).  Neither the OpenID Connect core specification (http://openid.net/specs/openid-connect-core-1_0.html#ImplicitTokenValidation) or the OAuth 2.0 Bearer token specification (https://tools.ietf.org/html/rfc6750).  In order for this to work openidconnect will need to have some "opinions" on how this should work OR this should be left to a webhook by individual vendors/projects that create identity information.

**Comment by mlbiam** [comment]
And for those that weren't in the @kubernetes/sig-auth channel the argument for why a shared client secret is insecure are based on that most enterprises have policies around both service accounts and privileges access accounts that include:

1.  The credential needs to be rotated periodically
2.  If a member of the team leaves the project/team/company the credential needs to change

These policies exist because the most likely attack against any password is one of the many social attack vectors out there (people are much easier to hack then computers).  

If these are deal breakers or not for a deployment will depend on the risk tolerance of the deploying company.

**Comment by liggitt** [comment]
This was discussed extensively when the OIDC feature was added to kubectl. Some highlights:

* Because the token is granted by some third party, using the access_token against kubernetes is not appropriate (there's no telling what that access_token allows access to, and kubernetes can't verify it... access tokens are opaque, even in OIDC)
* There are two valid modes of operation:
  * the client_id is for a public client, no client_secret is needed (or not considered a secret)
  * the client_id is unique to the local user, so the client_secret belongs to them

**Comment by ericchiang** [comment]
@mlbiam and I actually had this exact conversation on the keycloak mailing list. Going to post my thoughts directly from there:

> Today the Kubernetes API server trusts ID Tokens issued to a single client. Refreshing a token requires a client_secret, hence the flags Marc provided in his example. Though we don't have official recommendations about what the properties of the client passed in those flags should be there's two obvious ways of going about this.
>
> 1) Have each kubectl share a client secret. Some authorization servers provide mechanisms for declaring "public clients" to imposes restrictions on its capabilities. For example Google, when it assumes client_secrets aren't secret, restricts the redirect URLs for embedded apps to only localhost and a magic OOB, doesn't let it do incremental authorization, etc. Though as Marc noted this may have unintended consequences with providers who assume this doesn't happen.
>
> 2) Another option is for kubectl to utilize the "azp" claim in the ID Token[0], which allows clients to request ID Tokens on behalf of other clients. This means each kubectl gets its own client_id and client_secret, with each one requesting ID Tokens minted for a common client_id. However that capability isn't generally supported by OIDC providers, though Google does[1]. This is probably a more secure option, but the actual implementations differ so widely that it becomes hard to make a general statement.
>
> We'd be interested in knowing if either of these methods raise red flags when combined with keycloak.
>
> Eric
>
> [0] https://openid.net/specs/openid-connect-core-1_0.html#IDToken
> [1] https://developers.google.com/identity/protocols/CrossClientAuth

(The keycloak guy replied that he'd advocate for using a keycloak "public client")

Different providers have different capabilities to avoid a public secret or restrictions on public secrets. Those differences and how you setup your Kubernetes API server determine when it's appropriate (or at least less inappropriate) to store a secret in your kubeconfig.

ref https://github.com/kubernetes/kubernetes.github.io/issues/1831

**Comment by ericchiang** [comment]
So I it depends. I think part of the maturing of the OIDC plugins will be documenting these caveats and trying to proposed recommended setups.

**Comment by mlbiam** [comment]
@ericchiang @liggitt why couldn't k8s accept the access_token and call the user_token endpoint of the idp?  user_token is part of the oidc core standard and the endpoint would be documented in the oidc metadata url.  From a performance standpoint its no different then a webhook and its the same concepts.  I wouldn't replace the existing oidc, just add it as an option.

**Comment by ericchiang** [comment]
> user_token is part of the oidc core standard and the endpoint would be documented in the oidc metadata url.

```
$ curl -s https://openid.net/specs/openid-connect-core-1_0.html | grep "user_token"
(no results)
```

Do you mean user_info (which is recommended btw)? I'm confused what that busy us. You still need an access_token which expires and needs refreshing. You just added another call that the k8s cluster needs to make instead of parsing a signed id_token.

**Comment by mlbiam** [comment]
@ericchiang argh you're right user_info.  It would let you use the access_token which can be longer lived then the id_token since it can be revoked and authorizations changed on the backend but you wouldn't need kubectl to do the refresh.  If the token is still active would be up to the IdP.  It would give you a similar user experience as what we did with OpenUnison (having a per session shared secret) without having to use a specific vendor's IdP.

**Comment by liggitt** [comment]
I don't think using a third-party access_token as a bearer token to kubernetes is appropriate. There is no telling what power that access_token holds in the third-party system that the user is not intending to give to the kubernetes API server.

**Comment by mlbiam** [comment]
@liggitt shouldn't that be up to the deployer and the idp?  Hows that any different then using a webhook for authentication?  Its still an opaque token to k8s that tells k8s who the user is and what groups the user has.  This is no different except its using documented standards.

**Comment by liggitt** [comment]
> @liggitt shouldn't that be up to the deployer and the idp?

Not if claiming to use the OIDC standard

> How's that any different then using a webhook for authentication? Its still an opaque token to k8s that tells k8s who the user is and what groups the user has. This is no different except its using documented standards.

You could implement this as a webhook if you wanted, but that doesn't claim to be standards-based. The proposed use of a third-party-issued access_token and user_info endpoint confuses the actors in the OIDC standard.

The actor using the access_token to get additional information from the user_info endpoint is supposed to be the actor that obtained the access_token/id_token in the first place, and the one that holds the client_id/client_secret.

The access_token is *not* meant to be passed to another system as proof of identity which the other system checks by looking up the user_info. That is what the id_token is for. That's made clear from the requirement to validate the information returned from the user_info endpoint against the subject in the id_token.

**Comment by jsloyer** [comment]
So if you try to use an empty `client_secret` now `kubectl` rejects it and says its a required field.  Thoughts on accepting a PR that would make it optional?

**Comment by ericchiang** [comment]
@jsloyer sure, but wouldn't that just be equivalent to setting a bearer token?

**Comment by liggitt** [comment]
it would enable the "shared public client with no client_secret" use case

**Comment by ericchiang** [comment]
@liggitt yeah just realized that.

The "old" go-oidc client is extremely opinionated about refreshing. I rewrote it recently to just use golang.org/x/oauth2 so writing tests and updating to use the new client is probably a requirement here.

@jsloyer can you open a separate issue and ask for someone to assign me?

**Comment by jsloyer** [comment]
Opened #37874. @liggitt can you assign to @ericchiang?

**Comment by mlbiam** [comment]
@liggitt <https://github.com/liggitt> shouldn't that be up to the deployer
and the idp?

Not if claiming to use the OIDC standard

My first thought was for ouath2 not oidc but I looked back at the core doc
and while the authorization flow shouldn't expose the access token to the
user agent the hybrid flow, which is what I'd argue is what k8s is using,
makes no such requirement. The table in the authentication section says the
implicit and hybrid flows can expose the access_token to the user agent.


How's that any different then using a webhook for authentication? Its still
an opaque token to k8s that tells k8s who the user is and what groups the
user has. This is no different except its using documented standards.

You could implement this as a webhook if you wanted, but that doesn't claim
to be standards-based. The proposed use of a third-party-issued
access_token and user_info endpoint confuses the actors in the OIDC
standard.

My point was that k8s already supports opaque tokens via Web hooks, so that
on its own shouldn't be a reason to not support this flow.


The actor using the access_token to get additional information from the
user_info endpoint is supposed to be the actor that obtained the
access_token/id_token in the first place, and the one that holds the
client_id/client_secret.

The access_token is *not* meant to be passed to another system as proof of
identity which the other system checks by looking up the user_info. That is
what the id_token is for. That's made clear from the requirement to
validate the information returned from the user_info endpoint against the
subject in the id_token.

OK, I concede the point here.  5.3.2 and 5.3.4 int he openidconnect spec
don't match up (verifying the sub is in 5.3.2 but NOT in 5.3.4).

If k8s is going to support refresh without the client_secret then this
probably makes it a mute point.  It's an optional part of the spec and from
a security standpoint the only issue I really see with that is that and id
token can be valid for at least a minute and a lot of damage can be done in
a minute but that's a minor risk.

-- 
Marc Boorshtein
CTO Tremolo Security
marc.boorshtein@tremolosecurity.com
(703) 828-4902
Twitter - @mlbiam / @tremolosecurity

**Comment by liggitt** [comment]
client_secret is now optional for the k8s oidc config, which means we can support public clients (with or without client_secret) and confidential clients (with client_secret, per kubectl user)

**Comment by mecampbellsoup** [comment]
> it would enable the "shared public client with no client_secret" use case

@liggitt @jsloyer @ericchiang 

Sorry, maybe/probably a dumb question but, how is that ... better than just giving out a shared secret?

`authlib` also discusses using JWTs for authorization grants, I'm looking into this but I expect the big picture to be the same - you have to share some secret value among different `kubectl` users.

(Our use case is administering a multi-tenant, and eventually multi-cluster, `k8s` cloud platform. So we have different companies/users accessing our production k8s API.)

**Comment by mlbiam** [comment]
@mecampbellsoup using a client secret with k8s would provide no security value, since it would need to be handed out to everyone using kubectl.  It would also impact compliance issues in most enterprises because the shared secret would be considered a "password" and need to be rotated periodically like any other service account password.

requiring a client secret for kubectl is like embedding a password in an HTML login form that allows the page to post the user's credentials for verification.

**Comment by mecampbellsoup** [comment]
> @mecampbellsoup using a client secret with k8s would provide no security value, since it would need to be handed out to everyone using kubectl. It would also impact compliance issues in most enterprises because the shared secret would be considered a "password" and need to be rotated periodically like any other service account password.
> 
> requiring a client secret for kubectl is like embedding a password in an HTML login form that allows the page to post the user's credentials for verification.

Yea, I get that but, how is registering my k8s client as _public_ any different in effect? I realize it's less hassle since I won't have to deal w/ rotating the secret over time, for example, but otherwise they both seem to have 0 security (at least regarding client auth)...

**Comment by mlbiam** [comment]
> Yea, I get that but, how is registering my k8s client as public any different in effect? I realize it's less hassle since I won't have to deal w/ rotating the secret over time, for example, but otherwise they both seem to have 0 security (at least regarding client auth)...

yes, they both provide zero security so why go through that additional hassle for zero additional security?  The security of OIDC comes from (in no particular order):

1. Short token length
2. one time refresh tokens
3. security of the idp because k8s is trusting it

the client secret is designed for web applications where there's a server side and client side component to the transaction.  It's not designed for use with kubectl, which isn't really an oidc client.  It just knows how to use the id_token and refresh it (but not obtain it)

**Comment by mecampbellsoup** [comment]
> > Yea, I get that but, how is registering my k8s client as public any different in effect? I realize it's less hassle since I won't have to deal w/ rotating the secret over time, for example, but otherwise they both seem to have 0 security (at least regarding client auth)...
> 
> yes, they both provide zero security so why go through that additional hassle for zero additional security? The security of OIDC comes from (in no particular order):
> 
> 1. Short token length
> 2. one time refresh tokens
> 3. security of the idp because k8s is trusting it
> 
> the client secret is designed for web applications where there's a server side and client side component to the transaction. It's not designed for use with kubectl, which isn't really an oidc client. It just knows how to use the id_token and refresh it (but not obtain it)

As an update, I think we are actually just going to create/register a new OAuth client for each of our cloud customers so that they have distinct secrets alongside their refresh tokens. This way the client secret is not shared, and we don't have a single public k8s client which feels like really poor security.
