### ISSUE TITLE
Kubectl -o jsonpath throws an error if field is not present in json

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/kubernetes#37991]
Moving the discussion to an issue

cc @smarterclayton @bgrant0607

In 1.5, the kubectl -o jsonpath command was changed to throw an error if the field referred to by the path is not found.  Pre 1.4 the field might have been defaulted to a value and returned this value instead.

I am not sure if we consider this a api compatibility breaking change. The json path doc does NOT explicitly state what the behavior is when the field is not present in the JSON.

1.4 behavior:
If the field is present (non-pointer) in the struct, but missing from the JSON, return empty string
If the field is missing from the struct, exit 1 with an error

1.5 behavior:
If the field is missing from the JSON, exit 1 with an error

I have not been able to find a record of the original intention when the field is missing from the JSON. It would probably be best to support either behavior by exposing a flag to control the knobs introduced in #31714. I am not sure it is worth the risk introduced to get that into 1.5 though.

Causing skew test failures: #35741

**Comment by pwittrock** [comment]
Release 1.5 known issues link: #37134

**Comment by pwittrock** [comment]
I think I figured out the issue.

**Correction: In 1.4 the default field value was returned, not just an empty string.**

My current best theory is that in 1.4 the responses were round-tripped through the unversioned golang structs objects and back to JSON.  At least some unversioned objects do not contain the omitempty tag that is present on the versioned objects (e.g. NodePort).  This would result in the default fields being set on the struct and then written in the output json.   This would explain why jsonpath was able to find these fields.

RE: The best 1.5 behavior
AFAIK we don't have a good way to emulate the 1.4 behavior of providing the defaults in jsonpath when they are missing from the json response.  It is not clear to me that this is even the correct thing to do.  It is relatively simple to change kubectl to return an empty string instead, but this doesn't seem to be a clear win either.

**Comment by smarterclayton** [comment]
According to JSONPath the spec an empty field is supposed to return empty
value.  It may be that we just implemented the spec in a way that resulted
in this hidden error and did not notice.

I think we should be more spec compliant rather than less, where possible.

On Dec 2, 2016, at 6:59 PM, Phillip Wittrock <notifications@github.com>
wrote:

I think I figured out the issue.

*Correction: In 1.4 the default field value was returned, not just an empty
string.*

My current best theory is that in 1.4 the responses were round-tripped
through the unversioned golang structs objects and back to JSON. At least
some unversioned objects do not contain the omitempty tag that is present
on the versioned objects (e.g. NodePort). This would result in the default
fields being set on the struct and then written in the output json. This
would explain why jsonpath was able to find these fields.

RE: The best 1.5 behavior
AFAIK we don't have a good way to emulate the 1.4 behavior of providing the
defaults in jsonpath when they are missing from the json response. It is
not clear to me that this is even the correct thing to do. It is relatively
simple to change kubectl to return an empty string instead, but this
doesn't seem to be a clear win either.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/37991#issuecomment-264594843>,
or mute the thread

**Comment by smarterclayton** [comment]
- An alternative for jsonPath to return false in case of *no match* may
   be to return an empty array in future.

**Comment by smarterclayton** [comment]
Returning the default value seems wrong.

Trying to find a clear answer among the maze of implementations.  It does
not seem to be correct to error in any of these implementations.  Client
code may differ from server side schema, and clients may not even know the
schema (tpr, extension apis).

On Dec 2, 2016, at 6:59 PM, Phillip Wittrock <notifications@github.com>
wrote:

I think I figured out the issue.

*Correction: In 1.4 the default field value was returned, not just an empty
string.*

My current best theory is that in 1.4 the responses were round-tripped
through the unversioned golang structs objects and back to JSON. At least
some unversioned objects do not contain the omitempty tag that is present
on the versioned objects (e.g. NodePort). This would result in the default
fields being set on the struct and then written in the output json. This
would explain why jsonpath was able to find these fields.

RE: The best 1.5 behavior
AFAIK we don't have a good way to emulate the 1.4 behavior of providing the
defaults in jsonpath when they are missing from the json response. It is
not clear to me that this is even the correct thing to do. It is relatively
simple to change kubectl to return an empty string instead, but this
doesn't seem to be a clear win either.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/37991#issuecomment-264594843>,
or mute the thread

**Comment by dims** [comment]
@pwittrock Is it appropriate to move this to the next milestone or clear the 1.5 milestone? (and remove the non-release-blocker tag as well)

**Comment by pwittrock** [comment]
@smarterclayton

**Comment by liggitt** [comment]
I just ran into this... it depends if we're working off a go struct or the unstructured json

when we're dealing with unstructured json, missing fields return an error

when we're dealing with a go struct, missing fields return the default value

**Comment by pwittrock** [comment]
kubectl jsonpath was switch from gostruct to unstructured in 1.5 right?

**Comment by liggitt** [comment]
It's inconsistent… it depends what is passed in, and whether you are working with a list or not :(

https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/resource_printer.go#L2680

**Comment by smarterclayton** [comment]
I think this was a breaking change.  It bit openshift very badly, and we depend on the behavior of JSONPath for a lot of scripts.

**Comment by smarterclayton** [comment]
@ncdc can you describe how prevalent this was?

**Comment by ncdc** [comment]
1. We have a test that evaluates a field in our DeploymentConfig.Status to ensure that its value is 0. Because the field is set to `omitempty`, and go's json encoder doesn't emit a field if its value is the default value (i.e. 0) or nil, we had to remove the `omitempty` tags so we didn't have to change the test
1. We have a test that is supposed to check for a pod's `{.status.podIP}` frequently, waiting up to 1 minute for it to be set. But because `podIP` is `omitempty`, you get this error instead: `error executing jsonpath "{.status.podIP}": podIP is not found`.

I'll add more as I find/remember them

**Comment by smarterclayton** [comment]
So basically anyone using jsonpath in scripting this way is potentially broken?  All things considered, we have stopped releases for much less than this.

**Comment by smarterclayton** [comment]
Bumping priority so we can assess whether this constitutes an API regression

Copying in @kubernetes/api-reviewers @kubernetes/sig-cli-misc

**Comment by ncdc** [comment]
It looks like the implementation from http://goessner.net/articles/JsonPath/ returns "false" if the input doesn't match against the jsonpath expression. How about if we just always allow missing keys, instead of making it optional and off by default?

**Comment by ncdc** [comment]
I'm going to do a PR that:

1. Makes jsonpath relaxed by default; i.e., allow missing keys
1. Adds a `--strict` flag that, if set, would disallow missing keys

**Comment by nikhiljindal** [comment]
Another example where this change broke a script: https://github.com/kubernetes/kubernetes/issues/36287 (we have since fixed the script so its not a problem any more).
