### ISSUE TITLE
Remove --auth-path from kubectl

### ISSUE THREAD

**Issue by deads2k** [kubernetes/kubernetes#3800]
Since the .kubeconfig file was introduced, there is a new way to describe the information contained inside of the existing .kubernetes_auth format.  .kubernetes_auth combined information that described how to recognize the api-server with information about how to authenticate the user to the api-server.  .kubeconfig separates those two concepts into discretely re-useable chunks, but --auth-path was kept for backwards compatibility.

If .kubernetes_auth is eliminated, there will be one way to express that information and that will simplify the explanation of how the information is built.  Right now, allowing references to .kuberentes_auth and defaulting to looking at the ~/.kubernetes_auth makes it harder to describe exactly where authentication information is coming from.

This would be a breaking change that has ripples affecting e2e tests, so I'd like to be sure there is agreement to the concept before starting a change.

/cc @jlowdermilk @smarterclayton @liggitt

**Comment by smarterclayton** [comment]
@deads2k the only concern I would have is whether it's substantially harder for someone to "generate" a .kubeconfig than a kubernetes_auth (so that tooling can generate .kubeconfig for a running app).  If it's equally easy, I don't see an issue removing it.

@brendandburns we would I assume handle this by publicly communicating the change (and recording the non-backwards compat), but I assume we're agreed on the goal to centralize down on the standard config file.

**Comment by deads2k** [comment]
> so that tooling can generate .kubeconfig for a running app

Is there an example of code doing this for .kubernetes_auth today?  That would make it easier for me to speak to.

**Comment by smarterclayton** [comment]
It's only proposed as part of secrets (the master has to be able to inject auth to talk back to master, and Eric floated doing it as a kubernetes_auth file, which means the CLI would work inside that container to talk back to the master).  As long as the generation is not insane, it's not an issue.

----- Original Message -----

**Comment by deads2k** [comment]
@smarterclayton Yes, it is sane.  We do it in OpenShift for component authentication.

**Comment by jlowdermilk** [comment]
+1 to deprecating the .kubernetes_auth format. We need to update the e2e tests to use kubeconfig first, but we want to do that anyway (#3745).

**Comment by jlowdermilk** [comment]
Turns out if we want to get rid of kubernetes_auth, we first need to either make token-based authentication work for kubectl -> apiserver, or else add User and Password as AuthInfo entries.

/cc @erictune

**Comment by smarterclayton** [comment]
What's left on token auth?  Generating the token and turning it on in all the environments?

----- Original Message -----

**Comment by jlowdermilk** [comment]
I think so; it looks like apiserver and kubectl can use a token if given one from file.

**Comment by smarterclayton** [comment]
I think we talked about making the change, and then never did.  We have the token file support - I honestly can't even remember what the latest was on this (beyond pure focused on other stuff).  We definitely wanted to nuke user/password support.  There was talk about cert auth - Jordan did the first steps of that, but I think that was really only needed for the kubelet (or rather, the kubelet talking to the master over TLS was the first step).

----- Original Message -----

**Comment by jlowdermilk** [comment]
Remaining work on token auth: #4007

**Comment by jlowdermilk** [comment]
kubeconfig now supports username/password user entries, so we are partially unblocked on pulling `auth-path` out of kubectl. Basic auth will be in use for some time, and the current kubeconfig loading rules are hopelessly complex until we remove auth-path loading. So here is what needs to be done to deprecate `auth-path` from kubectl:
1. Make `kube-up.sh` generate a standalone kubeconfig that includes username and password.
2. Make the ginkgo e2e test driver load its auth info from a kubeconfig file (the same one created by `kube-up.sh`) instead of a `kubernetes_auth` file.
3. Make sure downstream clients don't depend on `--auth-path` support (gcloud currently does, I can update).
4. Remove clientauth loading rules from clientcmd.
1. and 2. have to be done in the same PR to avoid breaking all e2e tests.
I actually already started on 1, so I'll take this.

**Comment by jlowdermilk** [comment]
Update: as of #6691 there are no active users of `--auth-path`. Should be safe to rip it out of clientcmd now.

**Comment by deads2k** [comment]
Because `AuthPath` references an external file and because it affects both the user stanza and an unknown(!) cluster stanza, we can't build a reasonable conversion.  On the openshift side, I think we'd be ok with the break (we've never generated or used that file).  How do you feel about that?

Either way, I'll start by pulling the flags from the commands.

**Comment by jlowdermilk** [comment]
I as I know, nothing should be using it now that master and kubelet use kubeconfig for auth, but removing flags sounds like good start.

**Comment by deads2k** [comment]
It lives! https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cmd/kubelet/app/server.go#L195

**Comment by roberthbailey** [comment]
auth-path was marked as deprecated quite a while back but hasn't yet been removed from the kubelet.
