### ISSUE TITLE
kubectl: Bad creds get cached in ~/.kube/config, causing user confusion until expiry (or manual file edit)

### ISSUE THREAD

**Issue by jdanbrown** [kubernetes/kubernetes#38075]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):
- No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):
- kubectl "does not allow access" 

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
- Bug report

**Kubernetes version** (use `kubectl version`):
 ```
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.6", GitCommit:"e569a27d02001e343cb68086bc06d47804f62af6", GitTreeState:"clean", BuildDate:"2016-11-12T05:22:15Z", GoVersion:"go1.7.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.5", GitCommit:"5a0a696437ad35c133c0c8493f7e9d22b0f9b81b", GitTreeState:"clean", BuildDate:"2016-10-29T01:32:42Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**:
  - GCP GKE 1.4.5
- **OS** (e.g. from /etc/os-release):
  - Not sure, using gci
- **Kernel** (e.g. `uname -a`):
  - Not sure, using gci
- **Install tools**:
  - GKE web UI
- **Others**:
  - N/A

**What happened**:
- In juggling multiple gcloud accounts with GKE clusters I accidentally used `kubectl` with the wrong application default credentials and it cached bad creds in `~/.kube/config`
- After pointing gcloud at the right application default credentials and re-running `kubectl`, it continued trying and failing to use the bad creds cached in `~/.kube/config`; at this point I was stuck and confused for a few hours
- To repair, I had to manually edit `~/.kube/config` to remove `users[].user.auth-provider.config`, and then `kubectl` started working again (or else wait ~1h for the access token to expire and refresh itself)

**What you expected to happen**:
- After pointing gcloud at the right application default credentials `kubectl` should just work, or at least provide an error msg to the user that can help them figure out that they need to revoke the bad access token and how to do it

**How to reproduce it** (as minimally and precisely as possible):

Good scenario: just works
```sh
# Avoid calling kubectl with wrong application default credentials
gcloud auth application-default login # -> Auth with user A
kubectl --context cluster-A version   # Ok + caches good creds
gcloud auth application-default login # -> Auth with user B
kubectl --context cluster-B version   # Ok + caches good creds

# Both now work
kubectl --context cluster-A version   # Ok, using cached good creds
kubectl --context cluster-B version   # Ok, using cached good creds
```

Bad scenario: user makes one mistake and gets stuck
```sh
# Use kubectl with wrong ADC
gcloud auth application-default login # -> Auth with user A
kubectl --context cluster-A version   # Ok + caches good creds
kubectl --context cluster-B version   # Oops + caches bad creds
gcloud auth application-default login # -> Auth with user B
kubectl --context cluster-B version   # Fails, stuck on bad creds cached in ~/.kube/config
kubectl --context cluster-A version   # Still works, using cached good creds

# User is now stuck and confused with no clear approach to resolve...

# Tada!
vim ~/.kube/config                    # Manually remove users[].user.auth-provider.config for cluster-B
kubectl --context cluster-B version   # Ok + caches good creds

# Both now work
kubectl --context cluster-A version   # Ok, using cached good creds
kubectl --context cluster-B version   # Ok, using cached good creds
```

**Comment by ppawiggers** [comment]
+1

Removing `users[].user.auth-provider.config` helped, thanks.

**Comment by kargakis** [comment]
@kubernetes/sig-cli-bugs

**Comment by matt-tyler** [comment]
I can look into fixing this if no-one else has already made a start on it?

**Comment by fabianofranz** [comment]
@matt-tyler feel free to take it, thanks!

**Comment by matt-tyler** [comment]
Ok, I think I have an understanding of what is happening

1. The call to `gcloud auth application default login` is storing credentials in a json file in a known location.

2. On a subsequent credential-requiring kubectl command, the GCP plugin is being loaded, and the application default credentials are being exchanged for a token. That token is then cached in the .kube/config file.

So where do things go wrong?

As far as I can tell, if I switch to a cluster-2 without refreshing the application default credentials from it's separate account, those existing credentials will still be exchanged successfully for an oauth2 token and cached against cluster-2. Those tokens will then fail against a call to cluster-2 - because they were intended for cluster-1.

The only sure-fire fix I can think of would be to ensure the application default credentials client ID is stored in users[].user.authprovider. Doing this would at least enable the ability to verify that the default credentials were valid for that particular cluster, and if not, prompt the user with a message to correctly aquire the application default credentials for it. Lets call this option 1.

Of course, there is a problem here with determining what the Client ID is in the first place. I think this would require that a call to `gcloud container clusters get-credentials <cluster-name>` would store the client ID in the generated config. This would require exposing the client id from oauth2/google.

Otherwise, perhaps storing the client ID the first time around would be enough - assuming the user at least manages to authenticate successfully against the cluster in the first instance. Then only oauth2/google would require a change, and not the gcloud command.

The other option (option 2) would be, upon failure, check if `CLOUDSDK_CONTAINER_USE_APPLICATION_DEFAULT_CREDENTIALS` is true and if-so, prompt the user that their application default credentials may be invalid for the target cluster, and to either prompt or clear the currently cached credentials in .kube/config. This would probably mean extending the auth provider interface such that a function may be provided that can be called upon failure that enables the auth provider plugin to do some checking of the state and to provide a reasonable message as to what might be wrong with the credentials that have been provided.

I feel like option 2 is probably the better option in the long term. Different auth plugins are likely to have different failure modes. Providing a way to communicate back to the user about possible edge cases seems a little more flexible.

Any thoughts?

**Comment by mcfedr** [comment]
Just come across this, its particularly strange to have to edit the config file, when there is a folder `cache` in the `.kube` folder.

**Comment by r0bj** [comment]
Is it really fixed?
I still can reproduce it with description @jdanbrown provided in initial comment.

**Comment by grant-zietsman** [comment]
I also reproduced this, unfortunately. Tried to use kubectl to access a cluster from an unauthorised account. Then, switched to the authorised account but the invalid authentication was cached. To resolve it, I set the `users[*].user.auth-provider.config.expiry` to an expired date.

**Comment by alexhwoods** [comment]
Believe I'm hitting this issue as well

**Comment by rocketraman** [comment]
I just ran into this as well, gcloud 311.0.0, kubectl 1.18.6.

**Comment by akashagarwal7** [comment]
I've got the same issue. I need to change the expiry time to 1 year back as @grant-zietsman pointed out.

**Comment by Paxa** [comment]
Solution that usually works for me
```
- name: user-name-alias
  user:
    auth-provider:
      config:
        access-token: xxx
        cmd-args: config config-helper --format=json --account=my-service-account@project-name.iam.gserviceaccount.com
        cmd-path: /path/to/google-cloud-sdk/bin/gcloud
        expiry: "2020-11-06T19:45:22Z"
        expiry-key: '{.credential.token_expiry}'
        token-key: '{.credential.access_token}'
      name: gcp
```
So it will use different credentials when switching contexts

**Comment by alexhwoods** [comment]
## Here's how to expire all of your users automatically
```bash
yq eval -i '.users[].user.auth-provider.config.expiry = "2020-01-01T12:00"' ~/.kube/config
```

You'll need [`yq`](https://mikefarah.gitbook.io/yq/#homebrew) installed (`brew install yq`).
