### ISSUE TITLE
Move to UnixUserID and UnixGroupID in API fields

### ISSUE THREAD

**Issue by pmorie** [kubernetes/kubernetes#38120]
Currently in the API there are a number of fields that correspond to a unix user id or group id which are typed as `*int64`.  We also have, in `pkg/types/unix_user_id.go`, typedefs for `UnixUserID` and `UnixGroupID`, but these are unused.  I don't see any compatibility issues with migrating the API to use these types, and so we should.  If we do not plan to use the types, we should delete them.

**Comment by pmorie** [comment]
@kubernetes/api-review-team

**Comment by thockin** [comment]
I think we'd do well to use string types more.  @mbohlool - any
implications for swagger?

**Comment by mbohlool** [comment]
@thockin I did not understand your comment. Are you suggesting we use string type instead of int64?

As far as I can tell from @pmorie's first comment, we want to change *int64 members to be UnixUserID and UnixGroupID that are both int64. That does not have any implications on OpenAPI spec (*int64 and int64 or any alias to any of them should all be treated the same in OpenAPI spec generation).

**Comment by smarterclayton** [comment]
Widening int types would be backwards incompatible.

**Comment by thockin** [comment]
I don't think we're widening them, just changing `*int64` to `*UnixUserID`
which is a type-alias to `int64`

**Comment by pmorie** [comment]
Correct, we would not be widening, just adopting a strong typedef equivalent to the current API type.

**Comment by mengqiy** [comment]
This is not fully backward compatible, it breaks 1.6 kubectl. see: #47448 and #47560

**Comment by dchen1107** [comment]
We decided to revert #44714 due to the backward compatible problem.
