### ISSUE TITLE
kube-proxy should have retry logic for iptables op failure

### ISSUE THREAD

**Issue by MrHohn** [kubernetes/kubernetes#38140]
From #7370.

Recently learned there are cases iptables command may fail(#38057). Especially when using old iptables version that does not support `-w` flag (wait for xtables lock). Without the `-w` flag, iptables command from kube-proxy may fail if kubelet is holding the xtables lock.

Checked the codes but did not find any direct retry logic in kube-proxy. What we do is simply log the error([ref](https://github.com/kubernetes/kubernetes/blob/master/pkg/proxy/iptables/proxier.go#L829)). Though we do have periodical sync loop(per 30 seconds by default) to handle this failure. Plus kube-proxy currently would receive lots of "non-op" updates from Apiserver(#26637), which would also trigger `syncProxyRules()`. 

The "non-op" updates somehow alleviate this situation. But once that is fixed, this kind of iptables failures may need to wait 30 seconds for the next sync loop, which sounds less effective. May be we could consider to retry on iptables failure.

@kubernetes/sig-network

**Comment by thockin** [comment]
I'm not super concerned about this.

1) 30 seconds is not that long
2) this primarily affects REALLY old versions

I'm not shutting it down, because I am always open to improvements, and
this is a fun place for someone to contribute a little bit.  I imagine the
fix would be:

a) add some jitter to the timer so it is not exactly 30 seconds (maybe 30
seconds +/- 1.5s).
b) in case of failure add a timer to retry in 1.5s +/- 0.5s, up to 3 tries
total

That said, this is the definition of a pony bug.

**Comment by dcbw** [comment]
Also, note that 'iptables-restore' doesn't actually take the iptables lock and doesn't currently support '-w'.  So iptables-restore, as run by the proxy, can certainly clash with any other parallel iptables calls including other iptables-restores.

There are patches upstream on the netfilter lists to fix this and introduce a '-w' option to iptables-restore. See http://marc.info/?l=netfilter-devel&m=148965094309925&w=2 and http://marc.info/?l=netfilter-devel&m=148976928314436&w=2

**Comment by dcbw** [comment]
I'd imagine that if we could depend on the -w option to iptables-restore, then we can probably close this bug and not introduce a retry or jitter, since we could depend on the lock to serialize calls.

**Comment by thockin** [comment]
-w equivalebt support was added.
