### ISSUE TITLE
Support log collection for  end to end tests

### ISSUE THREAD

**Issue by satnam6502** [kubernetes/kubernetes#3820]
Right now although we enable node level logging for end to end tests we don't support cluster level logging (to Elasticsearch) although logging to Cloud Logging does work when the node level logging option is `gcp`. To help debug tests we should allow the collection and retention of logs for end to end tests.

For an end to end test, a user should be able to specify:
* Node level logging configuration: none, Elasticsearch or Cloud Logging.
* Cluster level logging (e.g. Elasticsearch + Kibana)
* An option to leave the cluster level services and pods up after the test so they can be inspected.

**Comment by satnam6502** [comment]
@roberthbailey @zmerlynn

**Comment by dchen1107** [comment]
I filed #3500 which could be benefit from this one by the log collection too.

**Comment by roberthbailey** [comment]
I can see this being quite useful for developers running individual e2e tests. 

For CI though, we need a solution that exports the logs out of the running cluster so that it can be torn down at the end of the test: we can't leave every cluster running (even only the ones that fail) to collect logs because we will quickly run into resource limits.
