### ISSUE TITLE
[Upgrade test] "Addon update should propagate add-on file changes" failing in ci-kubernetes-e2e-gce-1.4-1.5-upgrade-cluster

### ISSUE THREAD

**Issue by saad-ali** [kubernetes/kubernetes#38229]
Test has been failing [100% of the time](https://k8s-testgrid.appspot.com/google-1.4-1.5-upgrade#gce-cvm-1.4-cvm-1.5-upgrade-cluster&width=20&sort-by-failures=&include-filter-by-regex=Addon%20update%20should%20propagate%20add-on%20file%20changes) in [ci-kubernetes-e2e-gce-1.4-1.5-upgrade-cluster](https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-1.4-1.5-upgrade-cluster/). Sample failure: [link](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-1.4-1.5-upgrade-cluster/4).

Based on [spreadsheet](https://docs.google.com/spreadsheets/d/1sAZqyWE--0fvN1PIuKTw9JwmcXNz6tQIm1MrjdILtm4/edit#gid=1403603610&vpid=A1) tracking 1.5 upgrade test failures created by @krousey.

**Comment by MrHohn** [comment]
Paste my same comment from #35600:

This test always failed in 1.5 upgrade builds. An example as this :https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-1.4-1.5-upgrade-cluster/12/.

Checked logs and found we were actually running the old version Addon update e2e test(probably depends on the original version?) after upgrade. But because Addon Manager is upgraded to a newer version in 1.5 and does not take care of resources in non `kube-system` namespace anymore, this test must failed without the necessary test code changes in #36008.

May triage it as a non blocker

**Comment by dims** [comment]
@saad-ali Is it appropriate to move this to the next milestone or clear the 1.5 milestone? (and remove the non-release-blocker tag as well)
