### ISSUE TITLE
[Upgrade test] "Rescheduler [Serial] should ensure that critical pod is scheduled in case there is no resources available" in ci-kubernetes-e2e-gce-1.4-1.5-upgrade-cluster

### ISSUE THREAD

**Issue by saad-ali** [kubernetes/kubernetes#38235]
Test has been [failing 100%](https://k8s-testgrid.appspot.com/google-1.4-1.5-upgrade#gce-cvm-1.4-cvm-1.5-upgrade-cluster&width=20&sort-by-failures=&include-filter-by-regex=should%20ensure%20that%20critical%20pod%20is%20scheduled%20in%20case%20there%20is%20no%20resources%20available) of the time in [ci-kubernetes-e2e-gce-1.4-1.5-upgrade-cluster](https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-1.4-1.5-upgrade-cluster/). Sample failure: [link](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-1.4-1.5-upgrade-cluster/4)

Based on [spreadsheet](https://docs.google.com/spreadsheets/d/1sAZqyWE--0fvN1PIuKTw9JwmcXNz6tQIm1MrjdILtm4/edit#gid=1403603610&vpid=A1) tracking 1.5 upgrade test failures created by @krousey.

**Comment by MrHohn** [comment]
This test always failed in 1.5 upgrade builds for the similar reason as #38229. In previous version it will try to retrieve the ReplicationController of kube-dns during the test([ref](https://github.com/kubernetes/kubernetes/blob/366366022e0347/test/e2e/rescheduler.go#L59)). But since #36008 kube-dns started to use Deployment but not RC and leads to this failure in upgrade builds.

**Comment by dims** [comment]
@saad-ali Is it appropriate to move this to the next milestone or clear the 1.5 milestone? (and remove the non-release-blocker tag as well)

**Comment by xiangpengzhao** [comment]
/close
This issue is no longer valid.
