### ISSUE TITLE
[Upgrade test] "Kibana Logging Instances Is Alive should check that the Kibana logging instance is alive" failing in ci-kubernetes-e2e-gce-1.4-1.5-upgrade-cluster

### ISSUE THREAD

**Issue by saad-ali** [kubernetes/kubernetes#38230]
Test has been failing [100% of the time](https://k8s-testgrid.appspot.com/google-1.4-1.5-upgrade#gce-cvm-1.4-cvm-1.5-upgrade-cluster&width=20&sort-by-failures=&include-filter-by-regex=Kibana%20Logging%20Instances%20Is%20Alive%20should%20check%20that%20the%20Kibana%20logging%20instance%20is%20alive) in [ci-kubernetes-e2e-gce-1.4-1.5-upgrade-cluster/](https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-1.4-1.5-upgrade-cluster/). Sample failure: [link](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-1.4-1.5-upgrade-cluster/4).

Based on [spreadsheet](https://docs.google.com/spreadsheets/d/1sAZqyWE--0fvN1PIuKTw9JwmcXNz6tQIm1MrjdILtm4/edit#gid=1403603610&vpid=A1) tracking 1.5 upgrade test failures created by @krousey.

**Comment by saad-ali** [comment]
Same comment as https://github.com/kubernetes/kubernetes/issues/38238:

@Crassirostris You marked this test as a non-blocker in the spreadsheet, could you please provide justification here. As soon as you do, we can remove the release blocker label.

**Comment by Crassirostris** [comment]
The problem is that in the 1.5 I upgraded kibana, but now it requires some procedures to rebuild its caches in order to work behind a proxy (https://github.com/kubernetes/kubernetes/pull/36103)

This rebuild takes up to 10 minutes (even 10 minutes timeout creates flakiness, https://github.com/kubernetes/kubernetes/issues/36809, which resulted in PR https://github.com/kubernetes/kubernetes/pull/38284), this was increased from 2 minutes in 1.4 e2e test (https://github.com/kubernetes/kubernetes/pull/36192), but in test I see only 2 minutes of retrying

Anyway, that's expected from kibana to spend a lot of time to start, there's no way to avoid that.

**Comment by saad-ali** [comment]
Based on @Crassirostris's explanation, this is an expected failure, marking issue as non-release-blocking.

**Comment by dims** [comment]
@saad-ali Is it appropriate to move this to the next milestone or clear the 1.5 milestone? (and remove the non-release-blocker tag as well)
