### ISSUE TITLE
[Upgrade test] "Pods should invoke init containers on a RestartAlways pod" failing in gke-container_vm-1.3-container_vm-1.5-upgrade-master

### ISSUE THREAD

**Issue by rkouj** [kubernetes/kubernetes#38248]
Test has been failing [100% of the time](http://k8s-testgrid.appspot.com/google-1.3-1.5-upgrade#gke-container_vm-1.3-container_vm-1.5-upgrade-master&include-filter-by-regex=Pods%20should%20invoke%20init%20containers%20on%20a%20RestartAlways%20pod) in [ci-kubernetes-e2e-gke-container_vm-1.3-container_vm-1.5-upgrade-master](http://k8s-testgrid.appspot.com/google-1.3-1.5-upgrade#gke-container_vm-1.3-container_vm-1.5-upgrade-master). Sample failure: [link](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-container_vm-1.3-container_vm-1.5-upgrade-master/15).

Based on [spreadsheet](https://docs.google.com/spreadsheets/d/1sAZqyWE--0fvN1PIuKTw9JwmcXNz6tQIm1MrjdILtm4/edit#gid=1325239137&vpid=A1) tracking 1.5 upgrade test failures created by @krousey.

**Comment by rkouj** [comment]
This also fails on

gke-container_vm-1.3-gci-1.5-upgrade-master
gke-gci-1.3-container_vm-1.5-upgrade-master
gke-gci-1.3-gci-1.5-upgrade-master

**Comment by enisoc** [comment]
The logs for the sample failure link in the original comment strangely don't contain any mention of pods named `pod-init-*`. I found another [sample failure](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-container_vm-1.3-container_vm-1.5-upgrade-master/10#k8sio-pods-should-invoke-init-containers-on-a-restartalways-pod) that does have such mentions in its [logs](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-container_vm-1.3-container_vm-1.5-upgrade-master/10/nodelog?junit=junit_01.xml&wrap=on).

The pod name created by this test is `pod-init-92a50e7f-bae2-11e6-b593-0242ac110002`.

According to the build log, the failure is on [this line](https://github.com/kubernetes/kubernetes/blob/f894cbb340da27/test/e2e/pods.go#L794) meaning the init containers have `Ready: false` after the Pod enters Running and PodInitialized has become True. This does seem to be corroborated elsewhere in the build log:

```
I1205 04:01:40.700] Dec  5 04:01:40.699: INFO: pod-init-92a50e7f-bae2-11e6-b593-0242ac110002 started at 2016-12-05T04:01:36-08:00 (2+1 container statuses recorded)
I1205 04:01:40.700] Dec  5 04:01:40.699: INFO: 	Init container init1 ready: false, restart count 0
I1205 04:01:40.700] Dec  5 04:01:40.699: INFO: 	Init container init2 ready: false, restart count 0
I1205 04:01:40.700] Dec  5 04:01:40.699: INFO: 	Container run1 ready: true, restart count 0
```

**Comment by enisoc** [comment]
Just a guess: This and related failures (#38249, #38250, #38251) could be related to old test code running against new behavior. In the version of these tests on master, extra steps have been added to copy InitContainers and InitContainerStatuses in and out of annotations before checking them:

https://github.com/kubernetes/kubernetes/commit/a55c71db4dbcb20d36ffabf86b17db3490ca911e#diff-dec94e1a17aa696de112e8e7378797b9R91

**Comment by saad-ali** [comment]
> related to old test code running against new behavior

Thanks for the update @enisoc! Can you verify if this is expected or unexpected, i.e. can you please help triage these issues as blocker or non-blocker for the 1.5 release ASAP.

**Comment by Random-Liu** [comment]
> In the version of these tests on master, extra steps have been added to copy InitContainers and InitContainerStatuses in and out of annotations before checking them

The change in the master is not included in 1.5

**Comment by Random-Liu** [comment]
@saad-ali @enisoc This is a non issue, we can mark this as non-release-blocker. I'll update detailed reason soon.

/cc @dchen1107 @erictune

**Comment by Random-Liu** [comment]
The test failed in the following combination:
`test client (v1.3) + apiserver (v1.5/v1.4) + kubelet client (v1.3)`.

The full story is that:
* Test client side: `api.Pod` -> `v1.Pod`, alpha annotation is set. (v1.3)
* Apiserver side: (v1.5)
  * `v1.Pod -> api.Pod`: alpha annotation is used.
  * `api.Pod -> v1.Pod`: alpha & beta annotation is set.
* Kubelet client side: (v1.3)
  *  `v1.Pod` -> `api.Pod`, alpha annotation is used (**beta annotation is treated as a normal annotation**)
  *  `api.Pod` -> `v1.Pod`, alpha annotation is set (**beta annotation still exists**)
* Apiserver side: (v1.5)
  * `v1.Pod` -> `api.Pod`: beta annotation is used. (**[Apiserver prefer beta annotation](https://github.com/kubernetes/kubernetes/blob/master/pkg/api/v1/conversion.go#L608-L610), and real init container status information is lost**).
* ...

That's why we can't see right init container status in the test. The biggest problem is that apiserver should not prefer `beta annotation`, however there is no easy fix now as is discussed with @caesarxuchao 

This is not a release blocker because:
* This is a known backward compatible issue and I think is already in 1.4.
* Init container is still a alpha feature in 1.3 and beta feature from 1.4.
* This will only happen when test and kubelet clients are 1.3 and master is 1.4+.

**Comment by caesarxuchao** [comment]
@Random-Liu, thanks for the nice summary.

I think this a known issue for @kubernetes/sig-api-machinery. https://github.com/kubernetes/kubernetes/issues/34508 is a proposal on how to solve it.

**Comment by dims** [comment]
@rkouj Is it appropriate to move this to the next milestone or clear the 1.5 milestone? (and remove the non-release-blocker tag as well)

**Comment by Random-Liu** [comment]
@dims I think so. We won't fix this for this release.

**Comment by xiangpengzhao** [comment]
/close
This issue is no longer valid.
