### ISSUE TITLE
[Upgrade test] "[k8s.io] Restart [Disruptive] should restart all nodes and ensure all nodes and pods recover" in ci-kubernetes-e2e-gke-container_vm-1.4-gci-1.5-upgrade-master

### ISSUE THREAD

**Issue by dashpole** [kubernetes/kubernetes#38331]
Test has been failing <20% of the time in [ci-kubernetes-e2e-gke-container_vm-1.4-gci-1.5-upgrade-master](https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-container_vm-1.4-gci-1.5-upgrade-master/). Sample failure: [link](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-container_vm-1.4-gci-1.5-upgrade-master/11)

Based on spreadsheet tracking 1.5 upgrade test failures created by @krousey.

cc: @Random-Liu, can you add the appropriate labels and assign me? Can you also add me to the spreadsheet for this test?

**Comment by Random-Liu** [comment]
I checked the sample failure, the failure message is:
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/restart.go:123
Expected error:
    <*errors.errorString | 0xc82099c760>: {
        s: "couldn't find 15 pods within 5m0s; last error: expected to find 15 pods but found only 11",
    }
    couldn't find 15 pods within 5m0s; last error: expected to find 15 pods but found only 11
not to have occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/restart.go:118
```
These are all pods running before node restart:
```
fluentd-cloud-logging-gke-bootstrap-e2e-default-pool-3ccd3c51-fsjk
fluentd-cloud-logging-gke-bootstrap-e2e-default-pool-3ccd3c51-ldry
fluentd-cloud-logging-gke-bootstrap-e2e-default-pool-3ccd3c51-ovai
kube-proxy-gke-bootstrap-e2e-default-pool-3ccd3c51-ovai
kube-proxy-gke-bootstrap-e2e-default-pool-3ccd3c51-fsjk
kube-proxy-gke-bootstrap-e2e-default-pool-3ccd3c51-ldry
kubernetes-dashboard-v1.4.0-hgpze <-- During rolling upgrade
kubernetes-dashboard-3543765157-n4g49
l7-default-backend-v1.0-exq1c <-- Duraing rolling upgrade
l7-default-backend-2234341178-wm9ls
kube-dns-v20-g7ciq <-- During rolling upgrade
kube-dns-v20-tqfho <-- During rolling upgrade
kube-dns-4101612645-hzmkj
kube-dns-autoscaler-2715466192-q5t0n
heapster-v1.2.0-2168613315-vhn6t
```

In v1.5 we change addon pods to use deployment.
After master is upgraded, there is an interval that all addon pods are doing rolling upgrade. The restart test is just running at that time. So before restart, the test saw some old pods, and after restart those old pods were gone.

This is an issue in the upgrade test itself. We should fix our upgrade test to wait for a period of test after master upgrade. @krousey 

Mark this as non-blocker, because:
* Addon pods rolling update is expected behaviour.
* The issue is in the upgrade test itself.
* The test will only fail when it is the first few test running.

@dashpole 
/cc @saad-ali

**Comment by MrHohn** [comment]
@dashpole @Random-Liu Thanks for the investigation.

Yeah we introduce [a lag for deleting the old addon resources](https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/addon-manager/kube-addons.sh#L207-L209) to support zero downtime addon update. This is explicitly needed for 1.5 because we migrated a big part of addons from RCs to Deployments(#36008).

Sorry about the confusing situation.
