### ISSUE TITLE
kubefed join should modify the kube-dns configmap

### ISSUE THREAD

**Issue by madhusudancs** [kubernetes/kubernetes#38400]
`kubefed join` joins a cluster to a federation. However, users are expected to make the modification to the `kube-dns` config by hand to make the intra-cluster service discovery to work. This config used to be passed as a flag to `kube-dns` and required `kube-dns` restart. In v1.5, `kube-dns` learned the ability to read this config from a configmap and needs no restarts. It watches for the configmap and automatically updates its internal config whenever the configmap changes. This makes `kube-dns` config change amenable to automation. So we should make this change when the cluster is joined to a federation and revert it when the cluster is unjoined.

cc @kubernetes/sig-federation @irfanurrehman

**Comment by MazizEsa** [comment]
Any steps/document on how to do this?

**Comment by irfanurrehman** [comment]
Hi Maziz, there is still an open PR for this. Please wait for that to get merged.
https://github.com/kubernetes/kubernetes/pull/39338

**Comment by MazizEsa** [comment]
@irfanurrehman so without this the federation will not be able to route request to the federation? Is there any workaround?

**Comment by irfanurrehman** [comment]
@MazizEsa yes there is a workaround.
Please follow the steps listed here to do it by hand.
https://kubernetes.io/docs/admin/federation/#updating-kubedns

**Comment by MazizEsa** [comment]
@irfanurrehman Notice that one. But not very clear. 
Are you suppose to create the config map within the "federation plane" context of the host cluster context?

Even i've done still dns record is incomplete. Missing the "A" entries, but only CNAME, indicating the services are un-healthy when in fact I have replicaset already. Appreciate if you have any pointer.

**Comment by irfanurrehman** [comment]
@MazizEsa no!
You need to create the configMap in each of the clusters that you register with federation.
This configMap needs to be created in namespace kube-system, because it needs to be consumed by kubedns which runs in the namespace kube-system.
The yaml for the same as listed on the link I sent u is as below:
apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-dns
  namespace: kube-system
data:
  federations: <federation-name>=<dns-domain-name>

<federation-name> is the name you used to deploy your federation control plane with. (for example maziz-federation)
<dns-domain-name> is the domain name you would have specified while deploying this control plane. (for example maziz.global)

you can use kubectl as below:
kubectl create -f <configmap-yaml.yaml>
against each of the clusters you have registered with federation

**Comment by MazizEsa** [comment]
@irfanurrehman I see!. Got it.

**Comment by irfanurrehman** [comment]
@MazizEsa if you let me know ur gmail id, I could ping you on hangouts.. !

**Comment by ethernetdan** [comment]
Moving to 1.7 as late to happen in 1.6. Feel free to switch back if this is incorrect.

**Comment by irfanurrehman** [comment]
@madhusudancs  the PR was merged, I think you can close this, if nothing additionally is needed.

**Comment by madhusudancs** [comment]
@irfanurrehman yeah, sure. I don't think there is anything more that we need here.
