### ISSUE TITLE
[resource quota admission controller] Sleep between retrying update resource quota status

### ISSUE THREAD

**Issue by m1093782566** [kubernetes/kubernetes#38447]
Recently, I occur some 409 resource version conflict errors when batch create pods(create a rc/rs with 100+ pods). That's because I set a pod number limitation in resource quota and when many goroutines update resource quota status concurrently, then resource version conflicted.

I find resource quota admission controller already has a retry mechanism in updating resource quota status, see [here](https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/admission/resourcequota/controller.go#L196), but without sleeping between every retries.

After adding sleep time, my problem fixed. So, I would like to introduce it to the upstream.

What do you think about it?

@derekwaynecarr @smarterclayton

**Comment by smarterclayton** [comment]
In this case the 409 is probably because we're exhausting our retry count - there should be a finite number of conflicts, so retrying more times or telling the client to retry would probably be better than sleeping.

**Comment by m1093782566** [comment]
> In this case the 409 is probably because we're exhausting our retry count

Yes. But I think sleep some time when conflicts happen is more reasonable, it can reduce the possibility of conflict again in very short time.

**Comment by smarterclayton** [comment]
The conflicts are limited in number - sleep won't actually make them less
common and objects unavoidable latency into the system.

On Dec 9, 2016, at 8:39 PM, DuJun <notifications@github.com> wrote:

In this case the 409 is probably because we're exhausting our retry count

Yes. But I think sleep some time when conflicts happen is more reasonable,
it can reduce the possibility of conflict again in very short time.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/38447#issuecomment-266169082>,
or mute the thread
