### ISSUE TITLE
Feature Gates for Federation APIs

### ISSUE THREAD

**Issue by madhusudancs** [kubernetes/kubernetes#38593]
Federation control plane components don't support feature gates for non-GA APIs/features and must be implemented. See here for examples - https://github.com/kubernetes/kubernetes/blob/master/pkg/util/config/feature_gate.go.

cc @kubernetes/sig-federation @nikhiljindal

**Comment by spiffxp** [comment]
known issue for v1.5.0 #37134

**Comment by nikhiljindal** [comment]
I am going to take this up.
All alpha APIs should be disabled by default.

I will need to enable them explicitly in tests that test those APIs.
Filed https://github.com/kubernetes/kubernetes/issues/40398 for kubefed to allow modifying runtime-config flag while bringing up `federation-apiserver`

**Comment by nikhiljindal** [comment]
Sent https://github.com/kubernetes/kubernetes/pull/42225 to fix runtime-config support for federation-apiserver. We can now use the `--runtime-config` flag to enable/disable api groups, versions or specific resources.

I am disabling batch and autoscaling groups in that PR since the controllers for those API resources havent merged yet. Am keeping all other APIs enabled by default.

Am on the fence for deployments (since it has known issues in rollback) and ingress (only works on GCP). Would love to know what others think.

This is related to the which resources are alpha vs beta discussion which we havent settled yet.

cc @quinton-hoole @marun @csbell @madhusudancs

**Comment by ethernetdan** [comment]
Moving to 1.7 as late to happen in 1.6. Feel free to switch back if this is incorrect.

**Comment by nikhiljindal** [comment]
Now that https://github.com/kubernetes/kubernetes/pull/42225 and https://github.com/kubernetes/kubernetes/pull/42375 are merged, we have command line flgas that users can use to disable specific APIs.

**Comment by nikhiljindal** [comment]
I realized this bug had 2 parts to it:
* support feature flags (have flags that users can use to enable/disable specific APIs).
* alpha APIs should be disabled by default.

First part is done. Tracking second in https://github.com/kubernetes/kubernetes/issues/44291

**Comment by irfanurrehman** [comment]
The APIs considered alpha are disabled by https://github.com/kubernetes/kubernetes/issues/42587, thus closing this issue. @nikhiljindal please correct me if this is not the case.
/close
