### ISSUE TITLE
Kubernete 1.5.0 DOA

### ISSUE THREAD

**Issue by arun-gupta** [kubernetes/kubernetes#38722]
Downloaded Kubernetes 1.5.0 and tried starting the server:

```
kubernetes > export KUBERNETES_PROVIDER=aws
kubernetes > ./cluster/kube-up.sh 
... Starting cluster in us-west-2a using provider aws
... calling verify-prereqs
... calling kube-up
Starting cluster using os distro: jessie
!!! Cannot find kubernetes-server-linux-amd64.tar.gz
```

The download is 4.57 MB only.

**Comment by saad-ali** [comment]
@arun-gupta This is by design. The release was getting ridiculously large with all possible binaries bundled in. So the main download link now only contains cluster scripts, examples, docs, and scripts to download the binary tarballs you need. Links to the binaries are in the changelog: https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG.md#v150

**Comment by arun-gupta** [comment]
@saad-ali so I need to download two separate bundles in order to get started with Kubernetes? Can I setup an environment variable that will download the right binaries for me?

**Comment by calebamiles** [comment]
@arun-gupta, @saad-ali do you think this discussion might be better had over at Stack Overflow (for persistence) or Slack (for expediency) following the [suggestions here](http://kubernetes.io/docs/troubleshooting/). If so perhaps we could close this issue.

**Comment by saad-ali** [comment]
If you know what binary you want you should be able to downloading just that. It contains source code as well.

CC @kubernetes/release-maintainers @ixdy @jbeda

**Comment by arun-gupta** [comment]
@saad-ali discussing at #kubernetes-users http://kubernetes.slackarchive.io/kubernetes-users/-/1481647268.005605/1481664288.005836/. You may close the bug!
