### ISSUE TITLE
Anonymous auth default enabled for kubelet

### ISSUE THREAD

**Issue by TamalSaha** [kubernetes/kubernetes#38784]
Hi,
Anonymous auth default enabled for kubelet . 
https://github.com/kubernetes/kubernetes/blob/release-1.5/pkg/apis/componentconfig/v1alpha1/defaults.go#L174

Should this be also set to default false?

cc: @erictune

**Comment by TamalSaha** [comment]
cc: @saad-ali

**Comment by sharms** [comment]
This had already been noted in the release notes, and set to false by default in the current release: 
https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG.md#changelog-since-v150

**Comment by TamalSaha** [comment]
@sharms It is not the same. 1.5.1 release disabled default anon for Kube api server. But kubelet's default anon is still enabled.

https://github.com/kubernetes/kubernetes/commit/c7c2c7355062cbc416822b8e2c7acffdf95ccbdb

**Comment by liggitt** [comment]
Kubelet has allowed anonymous auth since 1.0. In 1.5, we added the ability to also authenticate using client certificates and/or API bearer tokens, but for compatibility with previous releases, the default behavior of the kubelet has not been changed.

When combined with kubelet authorization (also added in 1.5), this allows anonymous requests to be authorized before being allowed.

To secure a kubelet, you should either disable anonymous auth or enable authorization. See https://kubernetes.io/docs/admin/kubelet-authentication-authorization/#kubelet-authorization for more details. In future releases, the defaults will likely change to enable authorization.

**Comment by TamalSaha** [comment]
@liggitt thanks a lot for explaining this. I am still confused about one thing.

Say I am running a Kube cluster is DigitalOcean, where all there is no private network. I am using default kubelet anonymous auth. Does that mean that anyone can call kubelet api and mess with the cluster?

**Comment by liggitt** [comment]
> I am using default kubelet anonymous auth. Does that mean that anyone can call kubelet api and mess with the cluster?

Yes. Your options are to disable anonymous auth and/or enable kubelet authorization. Before disabling anonymous auth, you must give your apiserver a credential to use to speak to the kubelet as documented in https://kubernetes.io/docs/admin/kubelet-authentication-authorization/#kubelet-authentication
