### ISSUE TITLE
apiserver should reject HPA object if no requests are set on a corresponding object

### ISSUE THREAD

**Issue by fgrzadkowski** [kubernetes/kubernetes#38812]
We should verify whether a corresponding object in HPA (e.g. Deployment) has set request and reject HPA object if it doesn't as utilization doesn't make any sense in that situation.

**Comment by DirectXMan12** [comment]
While I agree with the general sentiment (making it more obvious to the user that something is wrong), this has some implications for creation ordering, etc (what if I create my HPA first, and the the deployment, what if I create the HPA and then change the deployment, etc).

I think probably the better solution is to make it clearer in the HPA status (@derekwaynecarr had suggested we have a conditions field, which I like).

**Comment by fgrzadkowski** [comment]
Do we create event if there is no request now? I wonder, because if we already do it, then HPA status will not help as user didn't check there.

**Comment by DirectXMan12** [comment]
We do, but one of the pieces of feedback that we got from customers is that people are more likely to check the objects themselves, as opposed to events, which are sometimes confusing to look at, get lost, etc (e.g. it's hard to tell if a given event represents the current state -- you have to know to check events, you have to check the "last seen at", because it's probably been rolled up, and then you have to see if there are any newer events, guess, etc).

**Comment by DirectXMan12** [comment]
while the events on `describe` are useful, they're not always easy to interpret, due to event collapsing, etc.  I think a status indicating the *current* state would be very useful here.

**Comment by marun** [comment]
Assuming this shouldn't block 1.7, moving to 1.8.

**Comment by derekwaynecarr** [comment]
i actually think we should close this in favor of just HPA status, agreed?

**Comment by DirectXMan12** [comment]
yep
