### ISSUE TITLE
where does the yaml file used in ' kubectl create'  to fetch the variable value ? 

### ISSUE THREAD

**Issue by BruceZu** [kubernetes/kubernetes#38858]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Not sure
 
**Environment**:
K8s cluster based on metal machines and OS is CentOS 7

**What happened**:
I run kubectl create -f <yaml file> to create deployment and pod.
The special part here is I want the namespace and image value be variable
but apparently yaml file know it is variable but it can not resolve it.

I posted it to Ansible community https://github.com/ansible/ansible/issues/19419
As the yaml file is kubernetes template file, I come here and want to know 
Where does the yaml file find the variable. If I know the places I may try to prepare it there.

**What you expected to happen**:
I hope the template yaml file can resolve the variable by any ways as 
-- kubectl create provide some variable optional 
-- env
other ways are welcome

**How to reproduce it** (as minimally and precisely as possible):
detail is in https://github.com/ansible/ansible/issues/19419
The command is 
`kubectl create -f deploy-gitlab.yaml`

```
$ cat yaml/deploy-gitlab.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "{{ namespace }}-gitlab"
  namespace: "{{ namespace }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      run: "{{ namespace }}-gitlab"
  template:
    metadata:
      labels:
        run: "{{ namespace }}-gitlab"
    spec:
      containers:
      - image: gitlab/gitlab-ce:8.13.6-ce.0
        imagePullPolicy: Always
        name: "{{ namespace }}-gitlab"
        ports:
        - containerPort: 443
          protocol: TCP
        - containerPort: 22
          protocol: TCP
        - containerPort: 80
          protocol: TCP
```

Got error: 
`"stderr": "Error from server: error when creating "/root/temp-bruce/deploy-on-k8s/yaml/deploy-gitlab.yaml": namespaces "{{ namespace }}" not found",`
**Anything else do we need to know**:

**Comment by everett-toews** [comment]
@BruceZu Can this be closed as https://github.com/ansible/ansible/issues/19419 is now closed?

**Comment by spzala** [comment]
@BruceZu hi, one of the way of passing variables as you mentioned is via using Helm charts. You can find some example here https://github.com/kubernetes/helm/blob/master/docs/examples/nginx/templates/deployment.yaml  Also, the better way of getting answer for question like you have in this issue is to ask it on https://stackoverflow.com/questions/tagged/kubernetes For example there is a similar question https://stackoverflow.com/questions/46318262/how-to-refer-to-variables-in-a-kubernetes-deployment-file Since your issue is not really an issue but a question, it would be great if we can close it. Hope makes sense :) Thanks!
