### ISSUE TITLE
MacOS bash completion `have` dependency missing

### ISSUE THREAD

**Issue by tylerFowler** [kubernetes/kubernetes#38877]
After installing the kubectl bash completion (as well as `bash-completion` via homebrew and the appropriate changes to my bash profile) I've been getting this error every time my bash profile is sourced:

`-bash: have: command not found`

Unfortunately this 'have' command is extremely difficult to Google, although the kubectl completion seems to work even without it.

**kubectl version:**
```go
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1+82450d0", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"not a git tree", BuildDate:"2016-12-14T04:09:31Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"darwin/amd64"}
```

**Comment by spzala** [comment]
@tylerFowler hi, kubectl bash completion  works fine for me on mac. Since it's been a long time the issue was last discussed, can you please verify if it's still a problem. Also, it's not really a kubernetes issue as mentioned here - https://kubernetes.io/docs/tasks/tools/install-kubectl/#on-macos-using-bash  ("The Homebrew project is independent from Kubernetes, so the bash-completion packages are not guaranteed to work." ). If you are okay, can you please close the issue? Thanks!

**Comment by tylerFowler** [comment]
Yup! Haven't seen this in quite a while, forgot about this issue

**Comment by spzala** [comment]
@tylerFowler  :-) Thanks!
