### ISSUE TITLE
[BUG REPORT] use ./build/run.sh  compile kubelet fail

### ISSUE THREAD

**Issue by fanhaozzu** [kubernetes/kubernetes#38933]
**Kubernetes version** :
kubernetes v1.14.1.beta and other version

**Environment**:
- **OS** :
Red Hat Enterprise Linux Server release 7.2 (Maipo)
- **Kernel** :
3.10.0-327.el7.x86_64

**What happened**:

+++ [1218 18:58:11] Verifying Prerequisites....
mkdir: cannot create directory ‘/opt/data/kubernetes-1.4.1-beta.2/_output/images/kube-build:build-769ef22c22’: Invalid argument
!!! Error in ./build/../build/common.sh:496
  'mkdir -p "${LOCAL_OUTPUT_BUILD_CONTEXT}"' exited with status 1

**How to reproduce it** (as minimally and precisely as possible):

 ./build/run.sh ./hack/build-go.sh ./cmd/kubelet

**Anything else do we need to know**:

the path should not include image name, the ":" cause the problem

**Comment by xiangpengzhao** [comment]
`:` is allowed in directory name in linux. I didn't run the full build script on my server which has the same OS & Kernel with yours, but I manually ran `mkdir -p /opt/data/kubernetes-1.4.1-beta.2/_output/images/kube-build:build-769ef22c22` as the script does and the directory could be created successfully.

I'm afraid there might be filesystem corruption on your env. Try `fsck` and then `reboot` please. Since this issue is several months old, you should have fixed it already. :)
