### ISSUE TITLE
Documentation copy example popup unable to close for large examples

### ISSUE THREAD

**Issue by jwforres** [kubernetes/kubernetes#38970]
The copy button in the documentation examples can sometimes cause a success popup that can not be closed, this occurs when the example is large. The PetSet example is the easiest to reproduce this on http://kubernetes.io/docs/user-guide/petset/

Hit the copy button on the example and the dialog pops up saying what was copied.  The dialog extends off the top and bottom of the screen, causing the Close button to be unclickable.  Clicking outside the dialog area does not close the dialog either.

Putting the entire contents of what was copied into the popup seems unnecessary.

Screenshot below is not cropped, this is what my browser screen looked like after clicking copy:

![kube-docs-copy](https://cloud.githubusercontent.com/assets/1467629/21316911/ea13db48-c5d0-11e6-8549-1a461293f037.png)

**Comment by jwforres** [comment]
Adding that the only workaround when this happens is to refresh the browser page.

**Comment by deads2k** [comment]
@devin-donnelly This is in the docs code somewhere, right?

**Comment by spzala** [comment]
@jwforres hi, I couldn't recreate the issue as such. I am sure it must be a problem in the past but petsets is now statefulsets (v1.5 and above). I understand the issue is about truncated content when clicking copy button ( vs petsets to statefulsets) but I don't see it now (e.g. https://kubernetes.io/docs/concepts/workloads/controllers/deployment/). In some example with large content I don't see copy button is provided at all. Can you please take a quick look and see if you can recreate the issue?, if not, it would be good to close it. Thanks!

**Comment by jwforres** [comment]
Yeah the copy dialog doesn't contain the copied content anymore so this no longer seems to be an issue

**Comment by spzala** [comment]
Thanks @jwforres
