### ISSUE TITLE
kubectl exec execution output should separate stdout and stderr

### ISSUE THREAD

**Issue by freehan** [kubernetes/kubernetes#38998]
`kubectl exec` merges command stderr into stdout. Please consider returning them separately. This has been a problem when I tried to pipe command execution result from pod to other tools, which unfortunately made assumptions on this. 

Repro:
```
$ kubectl exec -it debugpod -- sh -c "(>&2 echo error) 1>out 2>err"
$ kubectl exec -it debugpod -- cat out
$ kubectl exec -it debugpod -- cat err
error
$ kubectl exec -it debugpod -- sh -c "(>&2 echo error) " 1>out 2>err
$ cat out
error
$ cat err
$ 
```

**Comment by janetkuo** [comment]
@kubernetes/kubectl

**Comment by ymqytw** [comment]
@ncdc

**Comment by ncdc** [comment]
`kubectl exec` separates the container's stdout and stderr and delivers each to the appropriate stream, unless something has changed recently.

**Comment by ncdc** [comment]
This is happening because you're passing `-t`. If you specify `-t` that means that we set up a TTY and *all* output from the container is sent back to the client, and it's up to the client to decide what to do with it. This means, for example, that if you want to redirect the container's stderr somewhere else, you have to instruct the *container* to redirect it, because otherwise it is delivered back to the client over the TTY.

If you want to separate stdout and stderr and you don't need an interactive TTY, I would recommend you avoid specifying `-t`.

This behavior is identical to `docker exec -t`.

**Comment by freehan** [comment]
@ncdc Ah Thanks! Closing this issue.
