### ISSUE TITLE
Unable to add Windows Server 2016 nodes to a Kubernetes cluster on AWS

### ISSUE THREAD

**Issue by khannag** [kubernetes/kubernetes#38999]
**Is this a request for help? Yes**

**What keywords did you search in Kubernetes issues before filing this one? Windows server 2016 containers, AWS, kubernetes.**

I am running into issues adding a Windows server 2016 node to a kubernetes cluster on AWS. Here are the steps that I have followed.

I performed the following steps to setup a kubernetes cluster on AWS.

git clone https://github.com/kubernetes/kubernetes.git
make quick-release
export PATH=$PATH:/home/ubuntu/kubernetes/_output/dockerized/bin/linux/amd64
export KUBERNETES_PROVIDER=aws
export NUM_NODES=2
kube-up.sh 

With these commands, I was able to get a working cluster up and running.

root@ip-172-31-5-156:/home/ubuntu# kubectl cluster-info
Kubernetes master is running at https://35.165.132.44
Elasticsearch is running at https://35.165.132.44/api/v1/proxy/namespaces/kube-system/services/elasticsearch-logging
Heapster is running at https://35.165.132.44/api/v1/proxy/namespaces/kube-system/services/heapster
Kibana is running at https://35.165.132.44/api/v1/proxy/namespaces/kube-system/services/kibana-logging
KubeDNS is running at https://35.165.132.44/api/v1/proxy/namespaces/kube-system/services/kube-dns
kubernetes-dashboard is running at https://35.165.132.44/api/v1/proxy/namespaces/kube-system/services/kubernetes-dashboard
Grafana is running at https://35.165.132.44/api/v1/proxy/namespaces/kube-system/services/monitoring-grafana
InfluxDB is running at https://35.165.132.44/api/v1/proxy/namespaces/kube-system/services/monitoring-influxdb

Additionally, I followed the instructions @ https://github.com/kubernetes/kubernetes.github.io/blob/9eaaa1433661f80d5af25d7405b4683a947fc0f3/docs/getting-started-guides/windows/README.md to setup a kubernetes cluster with Windows Server 2016. 

I built the kubelet and kube-proxy for windows. As a starting point, I was trying to add a Windows Server 2016 node to this cluster. So, I launched a Windows 2016 instance on AWS and ran the following commands inside it. 

1) Added a second network adapter Ethernet2 to the instance.
2) Created a docker transparent network using the below command.
    a) docker network create -d transparent --gateway 172.1.0.1 --subnet 172.1.0.0/24 -o com.docker.network.windowsshim.interface="Ethernet 2" TransparentNet
3) $env:CONTAINER_NETWORK="TransparentNet"
4) .\kubelet.exe --hostname-override=172.20.1.20 --pod-infra-container-image="apprenda/pause" --resolv-conf="" --api_servers=172.20.0.9

Here 172.20.0.9 is the private IP of the kubernetes master node and 172.20.1.20 is the private IP of the Windows instance under consideration. Please note that I had launched the Windows instance in the same VPC which kube-up.sh creates as part of the cluster setup process. I am running into the following errors on Windows.

I1220 00:29:59.498583    4840 kubelet_node_status.go:77] Attempting to register node 172.20.1.20
E1220 00:30:00.384560    4840 reflector.go:188] pkg/kubelet/kubelet.go:379: Failed to list *v1.Service: Get http://172.20.0.9/api/v1/services?resourceVersion=0: dial tcp 172.20.0.9:80: connectex: No connection could be made because the target machine actively refused it.
E1220 00:30:00.384560    4840 reflector.go:188] pkg/kubelet/config/apiserver.go:45: Failed to list *v1.Pod: Get http://172.20.0.9/api/v1/pods?fieldSelector=spec.nodeName%3D172.20.1.20&resourceVersion=0: dial tcp 172.20.0.9:80: connectex: No connection could be made because the target machine actively refused it.

I had updated the security groups for the master node to be able to accept all traffic from the security group corresponding to where the Windows instance is running.

Would appreciate the help to see what I could be missing here ? 

-Thanks
Gaurav

**Comment by asktomsk** [comment]
Any progress on this? I tasked to do the same operation.

**Comment by khannag** [comment]
I had opened another ticket on this -which captures the progress I was able to make on this. Please see https://github.com/kubernetes/kubernetes.github.io/issues/2033.

**Comment by rvbsalgado** [comment]
The workaround that a found for your problem was do convert the ca.pem to ca.crt, and install this cer on the windows node.

But after that when i run:
 
kubelet.exe --hostname-override=10.61.1.8 --pod-infra-container-image="apprenda/pause" --resolv-conf="" --kubeconfig=C:\var\lib\Kubelet\kubeconfig\kubeconfig.yaml --require-kubeconfig

the output is:

I0412 13:15:44.608472    6100 feature_gate.go:144] feature gates: map[]
I0412 13:15:44.679457    6100 docker.go:384] Start docker client with request timeout=2m0s
W0412 13:15:44.681470    6100 cni.go:157] Unable to update cni config: No networks found in /etc/cni/net.d
I0412 13:15:44.684458    6100 server.go:513] --cgroups-per-qos enabled, but --cgroup-root was not specified.  defaulting to /
E0412 13:15:44.684458    6100 server.go:568] Kubelet needs to run as uid `0`. It is being run as -1
W0412 13:15:44.685465    6100 server.go:578] setting OOM scores is unsupported in this build
I0412 13:15:44.686458    6100 kubelet.go:265] Watching apiserver
W0412 13:15:44.689458    6100 iptables.go:142] Error checking iptables version, assuming version at least 1.4.11: executable file not found in %PATH%
W0412 13:15:44.689458    6100 kubelet_network.go:70] Hairpin mode set to "promiscuous-bridge" but kubenet is not enabled, falling back to "hairpin-veth"
I0412 13:15:44.690459    6100 kubelet.go:494] Hairpin mode set to "hairpin-veth"
W0412 13:15:44.693459    6100 plugins.go:221] can't set sysctl net/bridge/bridge-nf-call-iptables: open /proc/sys/net/bridge/bridge-nf-call-iptables: The system cannot find the path specified.
W0412 13:15:44.699458    6100 cni.go:157] Unable to update cni config: No networks found in /etc/cni/net.d
W0412 13:15:44.702458    6100 plugins.go:221] can't set sysctl net/bridge/bridge-nf-call-iptables: open /proc/sys/net/bridge/bridge-nf-call-iptables: The system cannot find the path specified.
I0412 13:15:44.702458    6100 docker_service.go:198] Docker cri networking managed by kubernetes.io/no-op
W0412 13:15:44.712459    6100 docker_service.go:207] No cgroup driver is set in Docker
W0412 13:15:44.713460    6100 docker_service.go:208] Falling back to use the default driver: "cgroupfs"
I0412 13:15:44.714461    6100 docker_service.go:215] Setting cgroupDriver to cgroupfs
error: failed to run Kubelet: failed to create kubelet: Container Manager is unsupported in this build


Any clue?

**Comment by michmike** [comment]
please use the slack channel for additional support. cleaning up this ticket right now.
https://github.com/kubernetes/community/tree/master/sig-windows has all the details to get started or to find the slack channel for support

/close
