### ISSUE TITLE
PATCH is the most expensive operation in apiserver

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#39017]
While running large cluster tests, I'm observing PATCH to be the biggest part of profiles. This involves both CPU as well as memory allocations.

On the unrelated node, memory allocations are relatively crucial for us now - after my PR https://github.com/kubernetes/kubernetes/pull/38961 that only reduce amount of memory allocations in cacher, the latency metrics in apiserver in 5000-node kubemark dropped by 5-30% depending on the metric.

That said, we are pretty much using strategicpatch now. How this is implemented on the server side now is:
```
Input: current runtime.Object, patch string
1. serialize current to json
2. deserialize it to map[string]interface{}
3. deserialize patch to map[string]interface{}
4. merge maps
5. serialize the result to json
6. deserialize it to runtime.Object (already patched).
```

This is pretty expensive because it requires double json serialization & deserialization (and most memory allocations came from that).

It would be good to optimize this somehow (though I don't have any good idea yet).

@kubernetes/sig-api-machinery-misc @smarterclayton @kubernetes/sig-scalability-misc

**Comment by smarterclayton** [comment]
I'm glad I was right :)

Do you have a measurement of how many conflicts the average PATCH encountered?  There's some higher level refactorings that might be more beneficial if conflicts > 1.5.

**Comment by wojtek-t** [comment]
The conflicts ration that I'm seeing is pretty small (below 1%).

**Comment by wojtek-t** [comment]
@caesarxuchao @lavalamp

**Comment by wojtek-t** [comment]
@smarterclayton - assuming the the conflict rate is pretty low, do you have any ideas how to optimize PATCH operation? In particular maybe avoid some of those json serialization/deserialization that happen twice here?

**Comment by liggitt** [comment]
That seems like the minimal set of operations to ensure we have the required form for evaluation, unless we allow encoding/decoding JSON directly to/from map[string]interface{}

**Comment by mbohlool** [comment]
Thinking out loud here, maybe generating (like deepcopy) patch methods for all runtime objects?

**Comment by uluyol** [comment]
It's unclear to me why you couldn't just use reflection to walk over the fields of the object instead of converting to map[string]interface{}. That would eliminate 1, 2, 5, and 6, though there would be some cost due to the reflection. Codegen could eliminate that at the cost of code bloat.

**Comment by liggitt** [comment]
> It's unclear to me why you couldn't just use reflection to walk over the fields of the object instead of converting to map[string]interface{}

because the patch applies to the serialized version, not the internal version (which is what the API server is working with).

**Comment by uluyol** [comment]
> because the patch applies to the serialized JSON version, not the internal go object (which is what the API server is working with).

I don't understand this comment. Are you referring to fields that have custom marshallers/unmarshallers? You could see if those methods exist and call them appropriately. Likewise for field renaming.

**Comment by liggitt** [comment]
> The smart object proposal could probably make it work though.

As storage moves to protobuf, wouldn't that degrade to re-encoding to JSON most of the time anyway?

**Comment by caesarxuchao** [comment]
I recommended people ( @Random-Liu ) to use PATCH instead of UPDATE because old clients will drop new fields when using UPDATE. If we properly fix our clients so that they don't drop unknown fields, we can avoid using PATCH in many cases.

Alos, because UPDATE has a greater chance of retries, we need to profile whether PATCH or UPDATE is cheaper if a resource is modified frequently.

**Comment by mbohlool** [comment]
If we generate a `patch` method, then we can just deserialize `patch` to a `runtime.Object` and pass it to the patch method of `current`.

**Comment by smarterclayton** [comment]
Also, if we can map[string]interface{} to a versioned object in a way that reuses existing arrays or maps we can avoid a fair number of struct allocations - if we got a v1 pod from etcd, then get the resulting map[string]interface{}, if we can set that map[string]interface{} onto the v1 pod we loaded we avoid having to reallocate slices for containers, for conditions, and the resource maps (all of which are not cheap).

**Comment by wojtek-t** [comment]
>PATCH is correct to use, we just need to make it less expensive.

+100, I don't think we should now get back to update, we should just think how to improve patch.

>We have to deal with the possibility of conversion from the versioned form in etcd to an intermediate representation matching the patch.

I think we shouldn't worry about this, and just assume we have a runtime.Object as the entry point to which we are supposed to apply patch. Then what we are storing in etcd doesn't really matter. At least, we shouldn't start with this.

>Avoiding serializing the merged map to JSON is probably the first big win, so map[string]interface{} -> versioned object is probably where I would think we should start.

Yeah - that sounds very reasonable to me.
Do you think it should be auto-generated code or something different?

>Also, if we can map[string]interface{} to a versioned object in a way that reuses existing arrays or maps we can avoid a fair number of struct allocations - if we got a v1 pod from etcd, then get the resulting map[string]interface{}, if we can set that map[string]interface{} onto the v1 pod we loaded we avoid having to reallocate slices for containers, for conditions, and the resource maps (all of which are not cheap).

I think I don't understand this. If we say have a slice of conditions, then in map[string]interface{} it won't be slice of conditions. So how you would like to reuse this?

**Comment by wojtek-t** [comment]
>>Also, if we can map[string]interface{} to a versioned object in a way that reuses existing arrays or maps we can avoid a fair number of struct allocations - if we got a v1 pod from etcd, then get the resulting map[string]interface{}, if we can set that map[string]interface{} onto the v1 pod we loaded we avoid having to reallocate slices for containers, for conditions, and the resource maps (all of which are not cheap).

>I think I don't understand this. If we say have a slice of conditions, then in map[string]interface{} it won't be slice of conditions. So how you would like to reuse this?

@smarterclayton - can you please clarify?

**Comment by smarterclayton** [comment]
If we have a versioned object from the store, and we can merge back to the versioned object (as opposed to internal) we save quite a few operations.  So just arguing we need to consider that we need a way on the server to ask for the raw object from the store and if the versions match, do a direct merge.  That also aligns with another optimization we want to do - serving values back to clients without conversion.  So we should ensure whatever we add here is not explicitly ruling that out.  "Smart objects" is the generic way of describing that - instead of using runtime.Object, return a wrapper that includes the bytes from store and can defer / optimize certain types of operations.

**Comment by wojtek-t** [comment]
So you suggest applying patch at the string/bytes level? It sounds dfferent that what you described in https://github.com/kubernetes/kubernetes/issues/39017#issuecomment-268680624
(though it sounds more promissing).

**Comment by smarterclayton** [comment]
That would only work if the two types were the same version.  I just want
to ensure we leave room for the optimization.  Pretty sure versioned go
struct -> map[string]interface{} is still our best option for the general
case.

On Dec 27, 2016, at 3:56 PM, Wojciech Tyczynski <notifications@github.com>
wrote:

So you suggest applying patch at the string/bytes level? It sounds dfferent
that what you described in #39017 (comment)
<https://github.com/kubernetes/kubernetes/issues/39017#issuecomment-268680624>
(though it sounds more promissing).

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/39017#issuecomment-269381577>,
or mute the thread

**Comment by wojtek-t** [comment]
So going back to "versioned go object -> map[string]interface{}". You wrote that:

>if we can map[string]interface{} to a versioned object in a way that reuses existing arrays or maps we can avoid a fair number of struct allocations

How can we reuse memory in those conversions? Unless I'm completely missing something, e.g. if we have []Container, than we need to translate this each Container to map[string]interface{} anyway (to make it generic). So I don't think we can reuse that much. Or am I completely missing something?

**Comment by wojtek-t** [comment]
Anyway - I will try to created some generator for it in the upcoming days at least as a starting point for optimizing it.

**Comment by smarterclayton** [comment]
Why would we need a generator?  Reflection probably is probably close to same speed since we don't need to actually allocate anything in the reflect pass.

**Comment by smarterclayton** [comment]
i think allocations are going to dominate runtime (creating new interface arrays and maps) and so the efficiency of scan time is less important.  I'd probably recommend just doing the reflect traversal first.

**Comment by smarterclayton** [comment]
I was referring to reusing the final array (versioned []Container) when we map the merged object back.  So we'd allocate for the interface array, but potentially reuse the original map and only have to do small edits.

**Comment by wojtek-t** [comment]
I already started working on some generator, but I'm fine with implementing reflection-based approach first to see if that would be enough.
That said, I have 2 questions to what you wrote above:
>since we don't need to actually allocate anything in the reflect pass.

I don't understand this. Let's assume we have a simple struct with 10 string fields. Then we are allocating a map[string]interface{} first, but then in a reflection phase, we are allocating copies of those ten strings to put them into the map. So we are allocating something (though it's probably the same amount of allocations as in the generated code - is that what you meant?

>I was referring to reusing the final array (versioned []Container) when we map the merged object back. So we'd allocate for the interface array, but potentially reuse the original map and only have to do small edits.

Sorry, I'm still lost. When we are converting the merged map[string]interface{} back to real runtime.Object, we have to copy all fields from that, as none of these are actually the expected types. Or am I completely missing something?

**Comment by wojtek-t** [comment]
Regarding the problem with large int64, you can see here the result from my test:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/39305/pull-kubernetes-unit/11160/

After doing json.Marshal + json.Unmarshal to map[string]interface{}, I'm getting this:
```
"sizeBytes":7.842972465191279e+18
```
which seems to cause problem due to precision...

**Comment by liggitt** [comment]
JSON implementations in general do not support int precision >= 53 bits (c.f. https://github.com/kubernetes/kubernetes/issues/17095)

That said, it would help for the patch operation should be using `pkg/util/json` instead of `encoding/json` in order to keep ints ints.

Isn't the nil vs empty list issue is the ugorji bug that will be fixed by https://github.com/kubernetes/kubernetes/pull/37557?

**Comment by wojtek-t** [comment]
@liggitt - thanks for pointers.

Regarding the latter, unless I'm completely missing something, I'm not using ugorji in my test:
https://github.com/kubernetes/kubernetes/pull/39305/files#diff-b906e5654b8131c5cf8d88210322a2e1R33

**Comment by wojtek-t** [comment]
I just switched from encoding/json to pkg/util/json, and it magically solved all the problems that I had. I still have some problems on my side, but these are due to not yet finished few things, so I'm sure I will fix those.

Anyway - @liggitt thanks a lot for help with that.

**Comment by lavalamp** [comment]
Just want to agree that we should encourage usage of PATCH, even if it
increases apiserver footprint, it decreases client CPU and network usage so
it's probably already a net win even if we don't optimize it.

but in regards to optimizing it, I know I have seen go libraries for
turning map[string]interface{} directly into structs--if it's not too late,
it would be good to look for something to use rather than writing this from
scratch.

**Comment by wojtek-t** [comment]
Patch is no longer a problem after all those changes. Closing.
