### ISSUE TITLE
Dose kubernetes support docker update command when pod is running?

### ISSUE THREAD

**Issue by liubnu** [kubernetes/kubernetes#39060]
This is a FEATURE REQUEST.
I use kubernetes v1.4.7 on centos 7.2.

Docker has command named update to change allocated resources on the fly.
I'd like to know if I can use kubectl to change allocated resources of a running pod.
I look this in kubectl patch command, but could not find solution.

**Comment by resouer** [comment]
In a cluster, it is not easy to update container resource on the fly. Just imagine what happens if you changed your memory request to +1GB while your node only have 512MB available?

And, for example, `docker update` command only changes values in the container's cgroup, but resources like memory is actually incompressible, container can not free out more memory unless the process is killed.

For more details, please check: https://github.com/kubernetes/kubernetes/issues/9043. People have been talking about in-place pod update for long time, but as you can see there, it is definitely not as easy as replace values in cgroups.

For now using [deployment](http://kubernetes.io/docs/user-guide/deployments/) to manage your container workload and trigger rolling update is a good idea, unless you have other strong reason that your workload can not be stopped. In that case, I assume it's mostly because your container has `state`,  [Stateful Apps](http://kubernetes.io/docs/tutorials/stateful-application/basic-stateful-set/) may also help.

If it's not all the case above, #9043 is a good place to continue discussing your problem, @davidopp is the one of the authors of Borg paper and owner of scheduling there.

**Comment by kargakis** [comment]
cc: @derekwaynecarr

**Comment by bgrant0607** [comment]
Pod resource update is #5774
