### ISSUE TITLE
Remaining genericapiserver dependencies

### ISSUE THREAD

**Issue by deads2k** [kubernetes/kubernetes#39086]
Primed the list with `go list -f {{.Deps}} k8s.io/kubernetes/pkg/genericapiserver | tr ' ' '\n' | grep k8s.io | grep -v vendor | grep -v third_party | grep -v "pkg/genericapiserver/" | sort`, removed core libraries and godeps, removed items from client-go (`find pkg -type d`), now I'll start checking them off with resolutions

dependencies not in client-go assuming open pulls merge
 - [ ] k8s.io/kubernetes/pkg/admission
 - [ ] k8s.io/kubernetes/pkg/api/rest
 - [ ] k8s.io/kubernetes/pkg/apis/meta/v1/validation
 - [ ] k8s.io/kubernetes/pkg/api/validation/genericvalidation
 - [x] k8s.io/kubernetes/pkg/auth/authenticator
 - [ ] k8s.io/kubernetes/pkg/auth/authenticator/bearertoken
 - [x] k8s.io/kubernetes/pkg/auth/authorizer
 - [ ] k8s.io/kubernetes/pkg/auth/authorizer/union
 - [ ] k8s.io/kubernetes/pkg/auth/group
 - [ ] k8s.io/kubernetes/pkg/auth/handlers
 - [ ] k8s.io/kubernetes/pkg/client/cache
 - [ ] k8s.io/kubernetes/pkg/client/clientset_generated/clientset/typed/authentication/v1beta1
 - [ ] k8s.io/kubernetes/pkg/client/clientset_generated/clientset/typed/authorization/v1beta1
 - [ ] k8s.io/kubernetes/pkg/client/metrics
 - [ ] k8s.io/kubernetes/pkg/client/restclient
 - [ ] k8s.io/kubernetes/pkg/client/transport
 - [ ] k8s.io/kubernetes/pkg/client/unversioned/auth
 - [ ] k8s.io/kubernetes/pkg/client/unversioned/clientcmd
 - [ ] k8s.io/kubernetes/pkg/client/unversioned/clientcmd/api
 - [ ] k8s.io/kubernetes/pkg/client/unversioned/clientcmd/api/latest
 - [ ] k8s.io/kubernetes/pkg/client/unversioned/clientcmd/api/v1
 - [ ] k8s.io/kubernetes/pkg/cloudprovider
 - [ ] k8s.io/kubernetes/pkg/httplog
 - [ ] k8s.io/kubernetes/pkg/serviceaccount
 - [ ] k8s.io/kubernetes/pkg/ssh
 - [ ] k8s.io/kubernetes/pkg/storage
 - [ ] k8s.io/kubernetes/pkg/storage/etcd/metrics
 - [ ] k8s.io/kubernetes/pkg/storage/storagebackend
 - [ ] k8s.io/kubernetes/pkg/util/cache
 - [ ] k8s.io/kubernetes/pkg/util/proxy
 - [ ] k8s.io/kubernetes/pkg/util/wsstream
 - [ ] k8s.io/kubernetes/plugin/pkg/auth/authenticator/request/anonymous
 - [ ] k8s.io/kubernetes/plugin/pkg/auth/authenticator/request/headerrequest
 - [ ] k8s.io/kubernetes/plugin/pkg/auth/authenticator/request/union
 - [ ] k8s.io/kubernetes/plugin/pkg/auth/authenticator/request/x509
 - [ ] k8s.io/kubernetes/plugin/pkg/auth/authenticator/token/tokenfile
 - [ ] k8s.io/kubernetes/plugin/pkg/auth/authenticator/token/webhook
 - [ ] k8s.io/kubernetes/plugin/pkg/auth/authorizer/webhook
 - [ ] k8s.io/kubernetes/plugin/pkg/webhook

dependencies in client-go we need to switch to
 - [ ] k8s.io/kubernetes/pkg/api
 - [ ] k8s.io/kubernetes/pkg/api/errors
 - [ ] k8s.io/kubernetes/pkg/apimachinery
 - [ ] k8s.io/kubernetes/pkg/apimachinery/announced
 - [ ] k8s.io/kubernetes/pkg/apimachinery/registered
 - [ ] k8s.io/kubernetes/pkg/api/meta
 - [ ] k8s.io/kubernetes/pkg/api/resource
 - [ ] k8s.io/kubernetes/pkg/apis/apps
 - [ ] k8s.io/kubernetes/pkg/apis/apps/v1beta1
 - [ ] k8s.io/kubernetes/pkg/apis/authentication
 - [ ] k8s.io/kubernetes/pkg/apis/authentication/install
 - [ ] k8s.io/kubernetes/pkg/apis/authentication/v1beta1
 - [ ] k8s.io/kubernetes/pkg/apis/authorization
 - [ ] k8s.io/kubernetes/pkg/apis/authorization/install
 - [ ] k8s.io/kubernetes/pkg/apis/authorization/v1beta1
 - [ ] k8s.io/kubernetes/pkg/apis/autoscaling
 - [ ] k8s.io/kubernetes/pkg/apis/certificates
 - [ ] k8s.io/kubernetes/pkg/apis/certificates/v1alpha1
 - [ ] k8s.io/kubernetes/pkg/apis/extensions
 - [ ] k8s.io/kubernetes/pkg/apis/extensions/v1beta1
 - [ ] k8s.io/kubernetes/pkg/apis/meta/v1
 - [ ] k8s.io/kubernetes/pkg/apis/meta/v1/unstructured
 - [ ] k8s.io/kubernetes/pkg/apis/policy
 - [ ] k8s.io/kubernetes/pkg/apis/policy/v1beta1
 - [ ] k8s.io/kubernetes/pkg/apis/rbac
 - [ ] k8s.io/kubernetes/pkg/apis/storage
 - [ ] k8s.io/kubernetes/pkg/apis/storage/v1beta1
 - [ ] k8s.io/kubernetes/pkg/api/v1
 - [ ] k8s.io/kubernetes/pkg/api/validation/path
 - [ ] k8s.io/kubernetes/pkg/conversion
 - [ ] k8s.io/kubernetes/pkg/conversion/queryparams
 - [ ] k8s.io/kubernetes/pkg/fields
 - [ ] k8s.io/kubernetes/pkg/genericapiserver/openapi
 - [ ] k8s.io/kubernetes/pkg/genericapiserver/openapi/common
 - [ ] k8s.io/kubernetes/pkg/labels
 - [ ] k8s.io/kubernetes/pkg/runtime
 - [ ] k8s.io/kubernetes/pkg/runtime/schema
 - [ ] k8s.io/kubernetes/pkg/runtime/serializer
 - [ ] k8s.io/kubernetes/pkg/runtime/serializer/json
 - [ ] k8s.io/kubernetes/pkg/runtime/serializer/protobuf
 - [ ] k8s.io/kubernetes/pkg/runtime/serializer/recognizer
 - [ ] k8s.io/kubernetes/pkg/runtime/serializer/streaming
 - [ ] k8s.io/kubernetes/pkg/runtime/serializer/versioning
 - [ ] k8s.io/kubernetes/pkg/selection
 - [ ] k8s.io/kubernetes/pkg/types
 - [ ] k8s.io/kubernetes/pkg/util
 - [ ] k8s.io/kubernetes/pkg/util/cert
 - [ ] k8s.io/kubernetes/pkg/util/clock
 - [ ] k8s.io/kubernetes/pkg/util/config
 - [ ] k8s.io/kubernetes/pkg/util/diff
 - [ ] k8s.io/kubernetes/pkg/util/errors
 - [ ] k8s.io/kubernetes/pkg/util/flowcontrol
 - [ ] k8s.io/kubernetes/pkg/util/framer
 - [ ] k8s.io/kubernetes/pkg/util/homedir
 - [ ] k8s.io/kubernetes/pkg/util/httpstream
 - [ ] k8s.io/kubernetes/pkg/util/integer
 - [ ] k8s.io/kubernetes/pkg/util/intstr
 - [ ] k8s.io/kubernetes/pkg/util/json
 - [ ] k8s.io/kubernetes/pkg/util/labels
 - [ ] k8s.io/kubernetes/pkg/util/net
 - [ ] k8s.io/kubernetes/pkg/util/parsers
 - [ ] k8s.io/kubernetes/pkg/util/rand
 - [ ] k8s.io/kubernetes/pkg/util/runtime
 - [ ] k8s.io/kubernetes/pkg/util/sets
 - [ ] k8s.io/kubernetes/pkg/util/strategicpatch
 - [ ] k8s.io/kubernetes/pkg/util/uuid
 - [ ] k8s.io/kubernetes/pkg/util/validation
 - [ ] k8s.io/kubernetes/pkg/util/validation/field
 - [ ] k8s.io/kubernetes/pkg/util/wait
 - [ ] k8s.io/kubernetes/pkg/util/yaml
 - [ ] k8s.io/kubernetes/pkg/version
 - [ ] k8s.io/kubernetes/pkg/watch
 - [ ] k8s.io/kubernetes/pkg/watch/versioned

@kubernetes/sig-api-machinery-misc @sttts @liggitt @ncdc

**Comment by deads2k** [comment]
@mehdy @mbohlool Are you the same person?  I think you mentioned this.

**Comment by deads2k** [comment]
@caesarxuchao can I change a dependency like `k8s.io/kubernetes/pkg/client/typed/discovery` to `k8s.io/client-go/discovery` without any ill effect in kubernetes or will that turn out badly for me?

**Comment by mbohlool** [comment]
@deads2k no mehdy is not my ID, I wish :)

**Comment by deads2k** [comment]
> @deads2k no, 'mehdy' is not my github ID, I wish :)

You tried to buy it from him? :)

**Comment by mbohlool** [comment]
I didn't. Maybe I should :)

**Comment by caesarxuchao** [comment]
I don't think you can. We haven't extracted types.go to a separate repo yet (it's next in my todo list), so currently the types used by client-go and kubernetes are different.

**Comment by deads2k** [comment]
@sttts good progress here.  Admission is big money.

**Comment by mehdy** [comment]
:)) 
@mbohlool sorry but I don't want to sell it :)

**Comment by mbohlool** [comment]
@mehdy you sure? I can pay a good price. What about a kubernetes badge? :D Kidding of course. I am not even sure if such a thing exists If it does, I may give my user id for it :)

**Comment by sttts** [comment]
Maybe helpful (using goviz with https://github.com/hirokidaichi/goviz/pull/8 applied):

```
$ goviz -i k8s.io/kubernetes/pkg/genericapiserver/api -d 2 | dot -Tpdf -o deps.pdf
```

![hoge](https://cloud.githubusercontent.com/assets/730123/21604155/d8b04648-d1a1-11e6-8c63-a0c0ee6ca8ca.png)

**Comment by deads2k** [comment]
First level of no-k8s/kubernetes deps are these:

1. k8s.io/kubernetes/pkg/api/pod - need to figure out why this is here
2. k8s.io/kubernetes/pkg/api/util - need to figure out why this is here
3. k8s.io/kubernetes/pkg/capabilities - need to snip this dependency
4. k8s.io/kubernetes/pkg/client/metrics - need to figure out why this is here
5. k8s.io/kubernetes/pkg/genericapiserver/routes/data/swagger - move
6. k8s.io/kubernetes/pkg/healthz - move
7. k8s.io/kubernetes/pkg/util/flushwriter - move
8. k8s.io/kubernetes/pkg/util/net/sets - move
9. k8s.io/kubernetes/pkg/util/strings - move

**Comment by deads2k** [comment]
Running this: https://gist.github.com/deads2k/989d7cb9a6c714fe81c0efb43e0322f2

**Comment by deads2k** [comment]
updated the list in the description to show current state after open pulls merge.

**Comment by deads2k** [comment]
@sttts We're going to have trouble in admission.  The API for admission provides `kubernetes/pkg/runtime.Object`s, but obviously the gotypes being decoded won't match the ones we have in tree.

@lavalamp @caesarxuchao @kubernetes/sig-api-machinery-misc I think we have to bite the bullet and move all types from `kubernetes/pkg/api`, `kubernetes/pkg/apis` to `staging/src/k8s.io/api`.  Similar to how we're we're doing genericapiserver.  The copy in staging is authoritative and everyone in tree switches to use the vendored copy.  This would also move `kubernetes/pkg/runtime/*` as a side effect.

**Comment by smarterclayton** [comment]
Declare a new interface with the same methods.  Identical interfaces can be
substituted.

On Jan 4, 2017, at 5:15 PM, David Eads <notifications@github.com> wrote:

@sttts <https://github.com/sttts> We're going to have trouble in admission.
The API for admission provides kubernetes/pkg/runtime.Objects, but
obviously the gotypes being decoded won't match the ones we have in tree.

@lavalamp <https://github.com/lavalamp> @caesarxuchao
<https://github.com/caesarxuchao> @kubernetes/sig-api-machinery-misc
<https://github.com/orgs/kubernetes/teams/sig-api-machinery-misc> I think
we have to bite the bullet and move all types from kubernetes/pkg/api,
kubernetes/pkg/apis to staging/src/k8s.io/api. Similar to how we're we're
doing genericapiserver. The copy in staging is authoritative and everyone
in tree switches to use the vendored copy. This would also move
kubernetes/pkg/runtime/* as a side effect.

—
You are receiving this because you are on a team that was mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/39086#issuecomment-270502809>,
or mute the thread

**Comment by deads2k** [comment]
> Declare a new interface with the same methods.  Identical interfaces can be
> substituted.

@smarterclayton 

I can't because they aren't identical. 

```go
type Object interface{
    GetObjectKind() runtime/schema.GroupVersionKind
}
```
and 
```go
type Object interface{
    GetObjectKind() client-go/runtime/schema.GroupVersionKind
}
```

are mutually exclusive . Nothing can satisfy both and I need to stop either stop depending on `k8s.io/kubernetes/pkg/runtime` or move it to `k8s.io/different-repo/pkg/runtime` to be able to finish splitting out the generic API server.

**Comment by smarterclayton** [comment]
Depend on client-go runtime/schema

On Jan 5, 2017, at 10:10 AM, David Eads <notifications@github.com> wrote:

Declare a new interface with the same methods. Identical interfaces can be
substituted.

@smarterclayton <https://github.com/smarterclayton>

I can't because they aren't identical.

type Object interface{
    GetObjectKind() runtime/schema.GroupVersionKind
}

and

type Object interface{
    GetObjectKind() client-go/runtime/schema.GroupVersionKind
}

are mutually exclusive . Nothing can satisfy both and I need to stop either
stop depending on k8s.io/kubernetes/pkg/runtime or move it to
k8s.io/different-repo/pkg/runtime to be able to finish splitting out the
generic API server.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/39086#issuecomment-270666380>,
or mute the thread

**Comment by smarterclayton** [comment]
I'm also ok with not requiring admission to have runtime.Object

On Jan 5, 2017, at 10:10 AM, David Eads <notifications@github.com> wrote:

Declare a new interface with the same methods. Identical interfaces can be
substituted.

@smarterclayton <https://github.com/smarterclayton>

I can't because they aren't identical.

type Object interface{
    GetObjectKind() runtime/schema.GroupVersionKind
}

and

type Object interface{
    GetObjectKind() client-go/runtime/schema.GroupVersionKind
}

are mutually exclusive . Nothing can satisfy both and I need to stop either
stop depending on k8s.io/kubernetes/pkg/runtime or move it to
k8s.io/different-repo/pkg/runtime to be able to finish splitting out the
generic API server.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/39086#issuecomment-270666380>,
or mute the thread

**Comment by deads2k** [comment]
> Depend on client-go runtime/schema

@smarterclayton if I do that, then we'll have k8s.io/kubernetes packages with two incompatible views of the API types.  What if I started smaller and made a k8s.io/apimachinery which included pkg/apimachinery/registered, pkg/runtime, and pkg/runtime/serializer plus their fanout (it's not too big and I think I can snip the weird links).  I make that in staging.  Force the staging copy to be authoritative and then switch k8s.io/client-go, k8s.io/apiserver, k8s.io/heapster, and k8s.io/kubernetes to use the the k8s.io/apimachinery version of pkg/runtime, etc?

**Comment by smarterclayton** [comment]
Sgtm

On Jan 5, 2017, at 10:59 AM, David Eads <notifications@github.com> wrote:

Depend on client-go runtime/schema

@smarterclayton <https://github.com/smarterclayton> if I do that, then
we'll have k8s.io/kubernetes packages with two incompatible views of the
API types. What if I started smaller and made a k8s.io/apimachinery which
included pkg/apimachinery/registered, pkg/runtime, and
pkg/runtime/serializer plus their fanout (it's not too big and I think I
can snip the weird links). I make that in staging. Force the staging copy
to be authoritative and then switch k8s.io/client-go, k8s.io/apiserver,
k8s.io/heapster, and k8s.io/kubernetes to use the the k8s.io/apimachinery
version of pkg/runtime, etc?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/39086#issuecomment-270679351>,
or mute the thread

**Comment by deads2k** [comment]
> Sgtm
> 
> On Jan 5, 2017, at 10:59 AM, David Eads <notifications@github.com> wrote:
> 
> Depend on client-go runtime/schema
> 
> @smarterclayton <https://github.com/smarterclayton> if I do that, then
> we'll have k8s.io/kubernetes packages with two incompatible views of the
> API types. What if I started smaller and made a k8s.io/apimachinery which
> included pkg/apimachinery/registered, pkg/runtime, and
> pkg/runtime/serializer plus their fanout (it's not too big and I think I
> can snip the weird links). I make that in staging. Force the staging copy
> to be authoritative and then switch k8s.io/client-go, k8s.io/apiserver,
> k8s.io/heapster, and k8s.io/kubernetes to use the the k8s.io/apimachinery
> version of pkg/runtime, etc?

@lavalamp I plan to pursue this path.  What's involved in getting an actual k8s.io/apimachinery repo set up so that we can cleanly godep for client-go and heapster?

**Comment by lavalamp** [comment]
good question-- can you file an issue so we can track that? It's easy to
create the repo but I'll have to look up how to configure the bot to do the
copies.

**Comment by deads2k** [comment]
@smarterclayton @sttts Just writing this down so I don't lose my spot.  Short version: `ListOptions` must move.

Long version, `pkg/storage` looks very genericapiserver-ish (various helpers, caches, and the like for dealing with etcd).  It depends on `pkg/client/cache` for reflectors and listerwatcher interfaces.  listerwatcher interfaces rely on `ListOptions`.  I can snip most of the other dependencies, but we'll get stuck on ListOptions.

**Comment by liggitt** [comment]
is this resolved?

**Comment by sttts** [comment]
Yes.
