### ISSUE TITLE
HPA should have scale down/up limits

### ISSUE THREAD

**Issue by andrewsykim** [kubernetes/kubernetes#39090]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):
No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):
HPA 
HPA limits 
scaling limits 
max scale up
max scale down 

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Feature Request

HPA should have some specifications on limiting the number of pods that can be scaled up/down in a given scaling period. This is mainly useful for replica sets that receive bursts of traffic. Currently HPA will aggressively scale down based on CPU metrics which can be undesirable. At the moment this isn't a problem for scaling up because of a hard coded limit [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/podautoscaler/horizontal.go#L361-L365). Having a configurable specification can give cluster admins the ability to control this. If this is a desired feature I'd love to get my hands dirty and open a preliminary PR to get started. 

/cc @DirectXMan12

**Comment by mattjmcnaughton** [comment]
@andrewsykim - I believe this behavior was added in https://github.com/kubernetes/kubernetes/pull/34955, and was included in the 1.4 release.

Can this be closed?

**Comment by andrewsykim** [comment]
@mattjmcnaughton the limits were introduced with `--horizontal-pod-autoscaler-downscale-delay` and `--horizontal-pod-autoscaler-upscale-delay` in the `kube-controller-manager` but I was hoping the delay can be specified on a per HPA basis instead of a catch-all in the kube-controller-manager. 

I personally think the delay should be on a per HPA basis, if others agree I think we should leave this issue open, otherwise feel free to close :).

**Comment by mattjmcnaughton** [comment]
Ah, I understand - thanks for clarifying @andrewsykim! There's been some discussion about this in [this issue](https://github.com/kubernetes/kubernetes/issues/56335) as well. 

From @DirectXMan12 

> Yeah, we've discussed this quite a bit in the past, and the conclusion has always been that the forbidden window is an implementation detail that we really shouldn't need at all, so we shouldn't expose it as a knob. There's an argument to be made about a pragmatic approach, but even then, it probably shouldn't be an API field (at most an annotation).

So definitely something people are thinking about, but I think there's some hesitation towards the per HPA method.

**Comment by WilliamDenniss** [comment]
I don't think that only having a global setting is what users want, that assumes that every team and every workload has the same desired HPA behavior.

The [stated goal](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#support-for-cooldown-delay) of the upscale and downscale delay is to reduce thrashing:

> When managing the scale of a group of replicas using the Horizontal Pod Autoscaler, it is possible that the number of replicas keeps fluctuating frequently due to the dynamic nature of the metrics evaluated. This is sometimes referred to as _thrashing_.

Different workloads may have different thresholds before thrashing is a concern. For example you could have a highly responsive node.js application serving a very spiky workload. With its small container size and fast bootup time, a low cooldown can work just fine. In the same cluster, another team has a large app with a slow bootup time. Due to the overhead of stopping and starting this container, a longer cooldown is desired.

+1 to re-open, and implement this request.

**Comment by andrewsykim** [comment]
I'm happy to implement this using an alpha annotations for the initial iteration. @DirectXMan12 are you able to review?

**Comment by maneeshmurali** [comment]
In my scenario, I have used custom metrics auto scaling the pods but the issue am facing is when the pod is re scaling the connections are lost and I think k8s  doesn't consider the live connections in a pod while re-scaling the pods.
Example :  Currently am having 2 pods and I have set the threshold to 100 socket connection. If I push 300 socket connections to the pods the pods will auto scale to 4 and consider each pod having more that 50 connections but the issue is when re-scaling, the pods will re-scale to 2 after the cool down but the connection will be terminated in the extra two pods which spin up. Is there any solution for the same. Requesting for help.

**Comment by andrewsykim** [comment]
> the pods will re-scale to 2 after the cool down but the connection will be terminated in the extra two pods which spin up 

This likely belongs in another issue, but your application should handle closing connections gracefully during the termination grace period (seconds after SIGTERM is received).

**Comment by Rajat-0** [comment]
@andrewsykim any update on this?
If you are not working on this then I would like to work on this.

**Comment by gabrielfsousa** [comment]
i would luv to have this feature

**Comment by andrewsykim** [comment]
@Rajat-0 I was mostly waiting for one of the HPA owners to respond :). I had spoken with @DirectXMan12 last month and he said we should wait for https://github.com/kubernetes/kubernetes/pull/68122 to be merged first as it will change some of the scale down logic. Seems like that PR is merged and we should see if we're good to start this work now. @DirectXMan12 any comments?

**Comment by DirectXMan12** [comment]
yeah, I think we can start poking around/prototyping this now

**Comment by andrewsykim** [comment]
Cool, @Rajat-0 I have some bandwidth this week to try to tackle this, but happy to let you take it if you'd like.

**Comment by MorrisLaw** [comment]
I will take this issue

**Comment by Rajat-0** [comment]
@MorrisLaw I'll be happy to help on this, let me know If you need any.

**Comment by MorrisLaw** [comment]
Thank you @Rajat-0 I'll let you know if I need help. Keep an eye out for the PR too so you can review my changes. Thank you!

**Comment by cablespaghetti** [comment]
Just to add my use case; we're running on Amazon EKS and so have no control over the kube-controller-manager flags. This means that I effectively have no control over how aggressively my Pods scale down if I continue to use the HPA.

This is particular problem for us because we're running websites using some quite hefty Java apps, so the load is quite spiky and it can take 1-2 minutes for a new instance to become ready (after hammering the CPU to start up). We tend to want to scale up reasonably aggressively but not scale down unless an instance hasn't been needed for somewhere along the lines of 10-30 minutes.

To go off on a slight tangent, it might also be good for our use case to allow the target CPU value to have separate scale-up and scale-down values (much like AWS Autoscaling works) so I can say, scale up if the average is 80% CPU but only scale down if the average goes as low as 40%.

Is there currently any workaround for people like me, other than to implement some kind of rudimentary autoscaling script myself?

Thanks

**Comment by gliush** [comment]
Hey there, I'm working on the RFC to add some configuration parameters into the HPA
https://docs.google.com/document/d/1Su2tzHEtjc7_orTVbKZEhSFGWiHk16JqA4Z7zJU2oNs/edit
I'll appreciate your feedback.

**Comment by max-rocket-internet** [comment]
> Just to add my use case; we're running on Amazon EKS

Us too

> This is a particular problem for us because we're running websites using some quite hefty Java apps

Us too.

Our problem is that Java uses maximum CPU during startup. The startup process can take anywhere between 1-5 mins depending on the. And this process is enough to trigger the HPA to scale up. In extreme cases the HPA will scale to `maxReplicas`. With really no options to customise the HPA we are left with no options.

Even some simple options for the `HorizontalPodAutoscaler` resource would help a lot. For example:

- Scale up and down delays, AKA "cool down period"
- Evaluation period for `targetCPUUtilizationPercentage`. e.g set this to 10 minutes to smooth out spikes from application startup

**Comment by juanpmarin** [comment]
@max-rocket-internet I'm currently experimenting that same issue with the jvm, the HPA can't stabilize the deployments because of the cpu utilization at startup, so it's scaling up and down all the time, 
do you found any workaround for that ?

**Comment by max-rocket-internet** [comment]
Well according to this https://github.com/kubernetes/kubernetes/pull/68068 the CPU consumption is not used for calculation until the pod is `Ready` so you can easily work around the problem by having a pod not become ready until it's done all its init. i.e. with a `livenessProbe` or `readinessProbe`. We had these probes all along so I guess our issue was something else.

**Comment by juanpmarin** [comment]
We already have both liveness and readiness probe, I can't figure out what is the reason of our problem because when I do `kubectl get hpa` it shows the targets lower than 50% but it scales up anyway, is it the same for you ?

**Comment by max-rocket-internet** [comment]
Yes but these are different issues:
https://github.com/kubernetes/kubernetes/issues/78761
https://github.com/kubernetes/kubernetes/issues/78712

**Comment by steven-sheehy** [comment]
> do you found any workaround for that

What we do is define a custom metric like transactions per second or request latency to scale off of instead of CPU. This is more accurate anyway since it's a business metric that you are completely in control of. We use the [Prometheus Adapter chart](https://github.com/helm/charts/tree/master/stable/prometheus-adapter) to scrape those custom metrics and make them available to the HPA. Full disclosure: I'm an owner of that chart.

**Comment by juanpmarin** [comment]
@steven-sheehy nice! I'll take a look at it, I think that metrics could be provided with Istio too 🤔 
So the workaround is get rid of CPU

**Comment by MorrisLaw** [comment]
I believe the following PR addresses this ticket, so I'll link it here for reference. 
[Configurable HorizontalPodAutoscaler, PR #74525](https://github.com/kubernetes/kubernetes/pull/74525)
