### ISSUE TITLE
Changing service port and reapplying doesn't work.

### ISSUE THREAD

**Issue by mikkeloscar** [kubernetes/kubernetes#39144]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): **BUG REPORT**

**Kubernetes version** (use `kubectl version`):
```
$ ./kubectl version                                                                                 [0]
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"clean", BuildDate:"2016-12-14T00:57:05Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"clean", BuildDate:"1970-01-01T00:00:00Z", GoVersion:"go1.7", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: minikube (also reproducable in other envs)
- **OS** (e.g. from /etc/os-release): 
- **Kernel** (e.g. `uname -a`):
- **Install tools**: `minikube start --kubernetes-version v1.5.1`
- **Others**:

**What happened**:

Assume you have a service:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: "test-service"
spec:
  selector:
    application: "test-service"
    stage: production
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
```

and you create it with: `kubectl create -f svc.yaml`.

Then if you want to change the port by modifying the manifest and applying:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: "test-service"
spec:
  selector:
    application: "test-service"
    stage: production
  ports:
    - port: 443
      targetPort: 8080
      protocol: TCP
```

You get this error:

```
$ ./kubectl apply -f svc-new-port.yaml
The Service "test-service" is invalid: 
* spec.ports[0].name: Required value
* spec.ports[1].name: Required value
```

**What you expected to happen**:

I expect to be able to apply the changes without a conflict.

Interesting enough if I apply the initial service at any point before applying the port change then it works.

E.g.:

```
$ ./kubectl create -f svc.yaml
service "test-service" created
$ ./kubectl apply -f svc.yaml
service "test-service" configured
$ ./kubectl apply -f svc-new-port.yaml
service "test-service" configured
```

Works fine.

I would expect `create` and `apply` for the very first time would behave the same.

**How to reproduce it** (as minimally and precisely as possible):

Create the two manifests from above and run:

```
$ kubectl create -f svc.yaml
service "test-service" created
$ kubectl apply -f svc-new-port.yaml
The Service "test-service" is invalid: 
* spec.ports[0].name: Required value
* spec.ports[1].name: Required value
```

I also found this issue which sounds very related: https://github.com/kubernetes/kubernetes/issues/28225

**Comment by MrHohn** [comment]
This is the expected behavior. You should always use `kubectl apply` (or `kubectl create --save-config` etc.) to create the object if you want to perform kubectl apply on this object in the future.

The commands you entered did not do what you want. It tried to configure the `test-service` into below setup:
```
apiVersion: v1
kind: Service
metadata:
  name: "test-service"
spec:
  selector:
    application: "test-service"
    stage: production
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
    - port: 443
      targetPort: 8080
      protocol: TCP
```
As this requested service has more than one port, each port must have port name for identity. Hence it is invalid for real([ref1](https://github.com/kubernetes/kubernetes/blob/v1.5.2-beta.0/pkg/api/validation/validation.go#L2454-L2457) and [ref2](https://github.com/kubernetes/kubernetes/blob/v1.5.2-beta.0/pkg/api/validation/validation.go#L2561-L2565)).

To explain why the `kubectl apply` command added one more port instead of replacing the original one. Take [`CreateThreeWayMergePatch()`](https://github.com/kubernetes/kubernetes/blob/v1.5.2-beta.0/pkg/util/strategicpatch/patch.go#L1165-L1247) as reference. As the service was created by `kubectl create`, it does not have its original configuration saved, which is needed by `kubectl apply` for figuring out what is deleted by the modified configuration. In your case, as a result, `kubectl apply` could only figure out a new port was added without noticing the old port should be deleted. Hence it patched an invalid service object.

cc @kubernetes/sig-cli-misc

**Comment by ymqytw** [comment]
@MrHohn is correct.
If you want to make `kubectl apply` works correctly, you should use `kubectl apply` or `kubectl create --save-config`. Otherwise, it doesn't know if it is safe to delete something.
`kubectl apply` relies on the `last-applied-configuration` annotation to work. You can see this annotation if you create an object by `kubectl apply` or `kubectl create --save-config`.

**Comment by rijuchatterjee** [comment]
My service is running on port 32xxx. I need to change the port number and make the service run at port 30000. How can I do this?

**Comment by bgrant0607** [comment]
cc @apelisse

**Comment by apelisse** [comment]
@rijuchatterjee Some thoughts:
- You should **apply** your files next time rather than create: `kubectl apply -f service.yaml`
- You can recreate a new service and replace, etc ... (not recommended)
- You can `kubectl edit service test-service` and update the port, that should work (I just tested)

Possible improvements: 
- why don't we have `--save-config` by default on `kubectl create` in the first place? @kubernetes/sig-cli-maintainers 
- We might want to convert `kubectl create` to always use server-side apply eventually @lavalamp 

Unfortunately, for now this is expected behavior.

**Comment by lavalamp** [comment]
I think we likely will change POST to store the user's intent rather than
change kubectl create.

**Comment by apelisse** [comment]
Yes, right.

**Comment by bgrant0607** [comment]
@lavalamp @apelisse The reasons that --save-config isn't on by default are:
1. It could cause confusing behavior if a user isn't expecting it
2. It had a noticeable impact on the scalability tests

**Comment by lavalamp** [comment]
I don't believe it's possible for the scalability tests to be affected much
by what kubectl does--most objects are made by controllers, not kubectl,
assuming kubectl is used at all for anything during the tests. We will have
to watch out for this for server side resources, though.

I'm much more worried about confusing users, if you have an example.

**Comment by apelisse** [comment]
The fact that `kubectl create` and `kubectl apply` do two different things is much more confusing to me (and based on this issue, I'm tempted to say I'm not alone).

**Comment by rijuchatterjee** [comment]
Thanks @apelisse that actually works. can you also help me in starting a postgres container? I am trying to deploy a postgres image from my registry to my cloud environment with kubernetes by using a yaml file. I need to know the command to start the postgres which needs to be mentioned in the yaml file.

**Comment by apelisse** [comment]
@rijuchatterjee You should ask your question on #kubernetes-users on slack, or on the kubernetes-users@googlegroups.com mailing list. I'm sure there is also plenty of resources online.
