### ISSUE TITLE
NodeProblemDetector in Kubemark doesn't work

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#39245]
Event though the NPD in kubemark is running it seems it is not able to connect to apiserver. All I'm seeing in its logs is:
```
I1227 12:43:53.517143       1 kernel_monitor.go:83] Finish parsing log file: {WatcherConfig:{KernelLogPath:/log/faillog StartPattern:Initializing cgroup subsys cpuset Lookback:10m} BufferSize:10 Source:kernel-monitor DefaultConditions:[] Rules:[]}
I1227 12:43:53.519158       1 kernel_monitor.go:97] Start kernel monitor
I1227 12:43:53.519177       1 kernel_log_watcher.go:95] kernel log "/log/faillog" is not found, kernel monitor doesn't support the os distro
I1227 12:43:53.519190       1 problem_detector.go:60] Problem detector started
I1227 12:43:53.519215       1 kernel_monitor.go:190] Initalize condition generated: []
E1227 12:48:57.619751       1 manager.go:130] failed to update node conditions: dial tcp 10.0.0.1:443: i/o timeout
E1227 12:50:24.248961       1 manager.go:130] failed to update node conditions: dial tcp 10.0.0.1:443: i/o timeout
E1227 12:51:08.451716       1 manager.go:130] failed to update node conditions: dial tcp 10.0.0.1:443: i/o timeout
E1227 12:51:41.410016       1 manager.go:130] failed to update node conditions: dial tcp 10.0.0.1:443: i/o timeout
E1227 12:52:11.410385       1 manager.go:130] failed to update node conditions: dial tcp 10.0.0.1:443: i/o timeout
E1227 12:52:46.438235       1 manager.go:130] failed to update node conditions: dial tcp 10.0.0.1:443: i/o timeout
E1227 12:53:30.589205       1 manager.go:130] failed to update node conditions: dial tcp 10.0.0.1:443: i/o timeout
```

I think this is simply misconfigured as the master address is not 10.0.0.1

@gmarek @kubernetes/sig-scalability-misc @shyamjvs

**Comment by wojtek-t** [comment]
I think this is the problem:
https://github.com/kubernetes/node-problem-detector/blob/master/pkg/problemclient/problem_client.go#L55

The problem is that we shouldn't use InClusterConfig in case of Kubemark, as we should connect to kubemark master. So we should allow for overwriting master address.

Some time ago, we did exactly the same for heapster, so that should be relatively simple to duplicate the logic.

**Comment by wojtek-t** [comment]
This is the flag in heapster:
https://github.com/kubernetes/heapster/blob/e19c9fb0d78695ce02e34afc821be5525f70f1d7/metrics/options/options.go#L54

**Comment by shyamjvs** [comment]
@wojtek-t Can you tell which ci-test you noticed this problem in?

**Comment by wojtek-t** [comment]
This was from kubemark-scale. But in general, as I wrote above, this cannot work. so it doesn't matter which suite we are talking about. The errors can be different, but it will never talk to the kubemark master.

**Comment by shyamjvs** [comment]
Here are some of my thoughts regarding this issue:
- Firstly, there is an error in the earlier step `kernel log "/log/faillog" is not found, kernel monitor doesn't support the os distro` as it seems like /log/faillog doesn't exist on GCI distros (unlike the CVM image (the one used in cluster/gce/config-default.sh) on which this was tested using kube-up.sh).
- Changing "logPath" in kernel-monitor.json to "/log/lastlog" (this file path should in fact become a part of kubemark/config-default.sh) might resolve the above issue. But it still doesn't mean that the NPD is talking to the kubemark apiserver.
- To make the NPD talk to the apiserver, we have the following 2 solutions:
  1. Define a new flag for specifying (optionally) an alternate master address and change this line https://github.com/kubernetes/node-problem-detector/blob/master/pkg/problemclient/problem_client.go#L53 to use this     
      alternate address (if defined) to create the config instead of using InClusterConfig. We would have to rebuild and upload a newer version of the NPD image if we do this.
  2. Just set the environment variable KUBERNETES_SERVICE_HOST in the NPD container to MASTER_IP (using the NPD config-map) so that InClusterConfig creates the right config. (see 
      https://github.com/kubernetes/kubernetes/blob/master/pkg/client/restclient/config.go#L275 )
The 2nd solution seems better as it doesn't require us to touch the existing npd code or image.

**Comment by wojtek-t** [comment]
I'm not sure we can do the latter (maybe we can, I just don't know). Those KUBERNETES_SERVICE_HOST and _PORT variables are just automatically created and set as part of downward api, and that's why I'm not sure we can overwrite them.

**Comment by shyamjvs** [comment]
Looks like the solution works as I now see an error at a later stage:
`I1229 10:32:36.799249       1 kernel_monitor.go:83] Finish parsing log file: {WatcherConfig:{KernelLogPath:/log/faillog StartPattern:Initializing cgroup subsys cpuset Lookback:10m} BufferSize:10 Source:kernel-monitor DefaultConditions:[] Rules:[]}
I1229 10:32:36.800474       1 kernel_monitor.go:97] Start kernel monitor
I1229 10:32:36.800566       1 kernel_log_watcher.go:110] Start watching kernel log
I1229 10:32:36.800609       1 problem_detector.go:60] Problem detector started
I1229 10:32:36.800801       1 kernel_monitor.go:190] Initalize condition generated: []
E1229 10:32:37.807537       1 manager.go:130] failed to update node conditions: x509: certificate signed by unknown authority
E1229 10:32:38.811143       1 manager.go:130] failed to update node conditions: x509: certificate signed by unknown authority
E1229 10:32:39.807208       1 manager.go:130] failed to update node conditions: x509: certificate signed by unknown authority`

This seems to be an issue with this line https://github.com/kubernetes/kubernetes/blob/master/pkg/client/restclient/config.go#L285 as I think we are using the wrong ca.crt file. We should be using the kubemark ca.crt instead of the default one present at the location `/var/run/secrets/kubernetes.io/serviceaccount/ca.crt`. The same issue might arise with `/var/run/secrets/kubernetes.io/serviceaccount/token`. I'm thinking of solving this issue by creating a npd-tls-volume mounting the above path at `/` and making sure that the correct ca.crt file is copied to `/` using `cluster/images/kubemark/Dockerfile`.
Do you suggest any better solution @wojtek-t ?

**Comment by wojtek-t** [comment]
Solving this with a volume (assuming that NPD is taking certs from that location) sounds like a good idea.

**Comment by shyamjvs** [comment]
I tried solving the problem using a volume for the ca.crt/token and it didn't work. Here is what I learnt from this effort:
- The file path `/var/run/secrets/kubernetes.io/serviceaccount/ca.crt` is actually a symbolic link to `/var/run/secrets/kubernetes.io/serviceaccount/..data/ca.crt`,
  and the path `/var/run/secrets/kubernetes.io/serviceaccount/..data` is itself again a symbolic link to the dir `/var/run/secrets/kubernetes.io/serviceaccount/..<a randomly generated string>`.
- Further, all the above paths are on a read-only filesystem, thus not allowing us to rewrite the real ca.crt and token files.
- Also, mounting a volume inside the npd container that maps the path `/var/run/secrets/kubernetes.io/serviceaccount` to any other location (where we could place the files) doesn't  seem
  to work as the link also is part of a read-only filesystem and hence the mounting process is ineffective.

After trying out some options, here are the solutions I feel are most promising:
- Even though the path `/var/run/secrets/kubernetes.io/serviceaccount` exists on a read-only filesystem, `/var/run/secrets` is the longest prefix that is writable. So instead of creating a volume
  mount in the npd container to the full path, just create it till this prefix. And ensure that the suffix of the path left out is where we place these files at the target location, so that together we can
  create the effect of replacing these files at the full path.  However, this requires changing the Dockerfile for the npd to create a symlink to the prefix and also changing the Dockerfile for the
  kubemark container to copy the files to the suffix path. We wouldn't have to change the npd code in this approach, as all we do is just build a new image using the npd code (with modified
  Dockerfile) and upload it to gcr once and for all (unless we want to change the npd version later).
- Change the npd code to allow passing the following optional flags (either all of them have to be passed or none):
   1. --kubernetes-service-host : The IP address of the master (we assume port is 443)
   2. --ca-cert-file : The path to the ca cert file
   3. --token-file : The path to the token file
  If these flags are all non-empty, we use them to construct the client config instead of using restclient.InClusterConfig. If only some of them are non-empty, we throw an error.
- Change the restclient.InClusterConfig function (https://github.com/kubernetes/kubernetes/blob/master/pkg/client/restclient/config.go#L274) to try reading and using the environment variables
  CA_CERT_FILE and TOKEN_FILE before falling back to their default paths.

I'm less experienced with making these decisions, but here is what I feel:
- The first solution might be the easiest way (requiring least code change) to get around the problem, but is quite hacky.
- The 3rd solution seems better than the 2nd one, because we should prefer adding features to an upstream package over a downstream one so that it is available widely.

Suggestions? @Random-Liu @wojtek-t

**Comment by gmarek** [comment]
We probably should see how it's done in e.g. heapster and/or other things that use `InClusterConfig` by default.

**Comment by gmarek** [comment]
@shyamjvs - you can probably add logic similar to https://github.com/kubernetes/heapster/blob/e603915446120a1fd3175539d041de6f5822425e/common/kubernetes/configs.go#L86 to the NPD.

**Comment by Random-Liu** [comment]
@shyamjvs @gmarek @wojtek-t 

Sorry for the delay. I was on vocation and just come back today.

There is an on-going effort by @andyxning to directly reuse the heapster code in NPD. #49

After this is merged, we should be able to use the same flag with heapster to config the master.

**Comment by shyamjvs** [comment]
Thanks @Random-Liu ! This PR is super helpful. I was suggesting a solution similar to this in my last comment, as modifying the client library would make it available to all the downstream libraries (npd, heapster, etc).
There is a small caveat that still remains:
- We want to use npd with authentication (so the option of `insecure=false` is ruled out). But we also cannot use service account for npd, as the path to the `defaultServiceAccountFile` is read-only in the hollow-node image we use (viz. `debian:jessie`) and overriding the ServiceAccountFile is not possible (even in this PR). I've mentioned this as a comment under [PR#49](https://github.com/kubernetes/node-problem-detector/pull/49).
- But IIUC we can get over this problem by making the npd use the same config as that of the hollow-kubelet (which hollow-proxy also uses) like this:
`node-problem-detector -apiserver-override=http://${APISERVER_IP}:${APISERVER_PORT}?inClusterConfig=false&auth=${PATH_TO_KUBELET_KUBECONFIG_FILE}` (`insecure` and `useServiceAccount` are defaulted to false)

**Comment by shyamjvs** [comment]
I'm sorry about the confusion. Looks like this won't be needed as the npd runs in a separate container on which the path to the service account file is (of course) writable. I guess I was confusing this with the option of also morphing the npd binary into the kubemark binary (which currently morphs into the hollow-kubelet or the hollow-proxy binary, based on the command line argument passed to it).

**Comment by wojtek-t** [comment]
@Random-Liu - thanks a lot for pointing to the PR (i was on vacation over last week, sorry for delay).

@shyamjvs - what's the status of this? Can we make use of it in kubemark?

**Comment by shyamjvs** [comment]
Yes. We have a current work-around to solve the issue (which is to erase the service account token file on the npd using a volume, so that the npd doesn't fallback talking to the real cluster apiserver). There's a PR on the way for this. On the other hand, we need to change heapster and npd to not fallback to in-cluster config in the case of stand-alone mode (I sent out a [PR](https://github.com/kubernetes/heapster/pull/1468) for this to heapster and will follow this change in npd and then to kubemark as well in a later PR).

**Comment by wojtek-t** [comment]
I will reopen it for a moment to verify if it really works now.

**Comment by shyamjvs** [comment]
I just checked the logs from the apiserver on one of our kubemark-500 CI test run that includes this commit (https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-kubemark-500-gce/1773). Both npd and heapster seem to be working fine now (except that there are some 404s for GET node/status in the starting which is fine):

```
I0119 14:18:37.449515       7 panics.go:75] PATCH /api/v1/nodes/hollow-node-lkrgp/status: (1.16587ms) 200 [[node-problem-detector/v1.4.0 (linux/amd64) kubernetes/$Format] 35.184.72.9:47300]
I0119 14:18:37.454777       7 panics.go:75] PATCH /api/v1/nodes/hollow-node-g0pph/status: (1.516645ms) 200 [[node-problem-detector/v1.4.0 (linux/amd64) kubernetes/$Format] 104.154.223.34:35316]
I0119 14:18:37.462739       7 panics.go:75] PATCH /api/v1/nodes/hollow-node-xq2qf/status: (1.214089ms) 200 [[node-problem-detector/v1.4.0 (linux/amd64) kubernetes/$Format] 104.154.223.34:48130]
I0119 14:18:37.470148       7 panics.go:75] PATCH /api/v1/nodes/hollow-node-tbb9q/status: (1.602222ms) 200 [[node-problem-detector/v1.4.0 (linux/amd64) kubernetes/$Format] 104.154.188.199:55898]
```

```
I0119 14:02:03.242362       7 panics.go:75] GET /api/v1/nodes: (1.271145ms) 200 [[heapster/v0.0.0 (linux/amd64) kubernetes/$Format] 104.154.223.34:37092]
I0119 14:02:03.244583       7 panics.go:75] GET /api/v1/nodes?resourceVersion=0: (272.388µs) 200 [[heapster/v0.0.0 (linux/amd64) kubernetes/$Format] 104.154.223.34:37092]
I0119 14:02:03.246876       7 panics.go:75] GET /api/v1/pods?resourceVersion=0: (244.227µs) 200 [[heapster/v0.0.0 (linux/amd64) kubernetes/$Format] 104.154.223.34:37092]
I0119 14:02:03.246975       7 panics.go:75] GET /api/v1/nodes?resourceVersion=0: (223.482µs) 200 [[heapster/v0.0.0 (linux/amd64) kubernetes/$Format] 104.154.223.34:37092]
I0119 14:02:03.248044       7 panics.go:75] GET /api/v1/namespaces?resourceVersion=0: (384.291µs) 200 [[heapster/v0.0.0 (linux/amd64) kubernetes/$Format] 104.154.223.34:37092]
I0119 14:02:03.248597       7 panics.go:75] GET /api/v1/nodes?resourceVersion=0: (250.723µs) 200 [[heapster/v0.0.0 (linux/amd64) kubernetes/$Format] 104.154.223.34:37092]
```

I guess we can close this issue now.

**Comment by shyamjvs** [comment]
@wojtek-t Seems like npd is stable now. Shall we close this issue?

**Comment by wojtek-t** [comment]
We probably can close this one, but please open another bug that kubemark-scale is now failing.

**Comment by wojtek-t** [comment]
[I mean it started failing again after your change (which was kind of expected). Though the might be two different issues there now].

**Comment by wojtek-t** [comment]
@shyamjvs - btw, I understand the failures with "high latency metrics":
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-kubemark-gce-scale/222
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-kubemark-gce-scale/223

but the next 4 ones is something different. If you could take a look, it would be great - it seems pretty critical now.

**Comment by shyamjvs** [comment]
@wojtek-t Sorry for delay in response. Seems like these issues have been resolved with the revert of refactor commit.

**Comment by shyamjvs** [comment]
Closing this issue as we don't have issues with NPD in kubemark anymore.
