### ISSUE TITLE
How do I get list of pod IPs that match a service?

### ISSUE THREAD

**Issue by ivanjaros** [kubernetes/kubernetes#39296]
Hi,
I have a Symfony based PHP application and it has a trusted proxy setting:
http://symfony.com/doc/current/components/http_foundation/trusting_proxies.html

which then works with x-forwarded- headers.

Since service is an umbrella for one or more pods matching set configured labels the IP address of the incoming request will be always different and so I cannot hard-code exact value.

So I an wondering if there is a way to get the list of IP addresses matching the pods but in a way that does not slow down the connection/request? Looking at the environment variables only the service is there but not matching pods and doing some sort of DNS lookup or Kubernetes API call would be very slow.

Currently I am just trusting that the incoming request came from my proxy(since there is no way of connecting from outside directly, only via proxy(service)) so I am setting this value directly from REMOTE_ADDR but it is basically bypassing the security measure altogether.

**Comment by cmluciano** [comment]
/closing

Please re-post your question to [Stack Overflow]
(http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support
are posted so that we can improve our efficiency in responding to your requests,
and to make it easier for you to find answers to frequently asked questions and
how to address common use cases.

We regularly see messages posted in multiple forums, with the full response
thread only in one place or, worse, spread across multiple forums. Also, the
large volume of support issues on github is making it difficult for us to use
issues to identify real bugs.

The Kubernetes team scans Stack Overflow on a regular basis, and will try to
ensure your questions don't go unanswered.

Before posting a new question, please search Stack Overflow for answers to
similar questions, and also familiarize yourself with:

  * [user documentation](http://kubernetes.io/docs/)
  * [troubleshooting guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/)

Again, thanks for using Kubernetes.

The Kubernetes Team
