### ISSUE TITLE
Init containers should (optionally) not block Pod startup

### ISSUE THREAD

**Issue by brendandburns** [kubernetes/kubernetes#39343]
(apologies if this is already possible but I didn't see it in the docs)

You should be able to optionally have an init container that doesn't block the startup of the rest of the
containers in the Pod.

The situation is this: With MongoDB you have to run some [imperative commands to set up replication](https://docs.mongodb.com/manual/tutorial/deploy-replica-set/)

To do this, I need a running mongo instance to issue those commands against.

Ideally, the container that ran these commands would be an init container, since it should really only run once then exit.

However, given the fact that I depend on another container (which is the main process) I now have
two containers, the main container and the would-be init container which just sleeps.

Not the end of the world, but not awesome either.

@smarterclayton

**Comment by smarterclayton** [comment]
Isn't that a use case for post start hook?  Downside is you have to reserve
more memory if needed.

There's definitely been a lot of desire to have a way to do this.

On Jan 2, 2017, at 1:18 AM, Brendan Burns <notifications@github.com> wrote:

(apologies if this is already possible but I didn't see it in the docs)

You should be able to optionally have an init container that doesn't block
the startup of the rest of the
containers in the Pod.

The situation is this: With MongoDB you have to run some imperative
commands to set up replication
<https://docs.mongodb.com/manual/tutorial/deploy-replica-set/>

To do this, I need a running mongo instance to issue those commands against.

Ideally, the container that ran these commands would be an init container,
since it should really only run once then exit.

However, given the fact that I depend on another container (which is the
main process) I now have
two containers, the main container and the would-be init container which
just sleeps.

Not the end of the world, but not awesome either.

@smarterclayton <https://github.com/smarterclayton>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/39343>, or mute the thread

**Comment by smarterclayton** [comment]
Note that init containers must be reentrant and idempotent, they can
be rerun on a node restart or other catastrophic shut down cases.
