### ISSUE TITLE
update-generated-docs.sh updates all links to kubernetes/community

### ISSUE THREAD

**Issue by k82cn** [kubernetes/kubernetes#39505]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
feature request

**Kubernetes version** (use `kubectl version`):
master

**What happened**:
all md files in docs are updated.

**What you expected to happen**:
create a PR for the update or skip `mungedocs`

**How to reproduce it** (as minimally and precisely as possible):
run `./hack/update-generated-docs.sh`

**Comment by k82cn** [comment]
cc @eparis , @spxtr, @ixdy

**Comment by spzala** [comment]
@k82cn Hi Klaus, wondering if this is still a valid request/issue since docs dir has changed a lot in last few months as part of moving doc files. I also run ./hack/update-generated-docs.sh and I see nothing was changed per git status. I hope I didn't misunderstand the request but wanted to bring the finding to your attention :). Thanks!
