### ISSUE TITLE
Is there a pv and pvc sample for cephfs?

### ISSUE THREAD

**Issue by keith4743** [kubernetes/kubernetes#39521]
https://github.com/kubernetes/kubernetes/blob/master/examples/volumes/cephfs/cephfs-with-secret.yaml

I found a pod sample here, is there a pv and pvc sample for cephfs?

And i have run this sample successfully on my k8s cluster.

**Comment by keith4743** [comment]
@resouer

**Comment by calebamiles** [comment]
Hello @keith4743 you might want to ask your question on StackOverflow so that it might be preserved for others in the future per the [official suggestions](http://kubernetes.io/docs/troubleshooting/). Alternatively someone from [SIG Storage](https://github.com/kubernetes/community/blob/master/sig-storage/README.md) should be able to help you out. If you are looking for examples of using CephFS as a [dynamic provisioner](http://blog.kubernetes.io/2016/10/dynamic-provisioning-and-storage-in-kubernetes.html) you would be disappointed to find that there doesn't seem to be a CephFS example located [with other similar examples](https://github.com/kubernetes/kubernetes/tree/master/examples/persistent-volume-provisioning) although it should be possible to adapt the [RBD example](https://github.com/kubernetes/kubernetes/tree/master/examples/persistent-volume-provisioning/rbd) and I'm sure a PR would be welcome. If someone from @kubernetes/sig-storage-misc could double check my info that would be awesome. If you have enough information to go on @keith4743 would you mind closing this issue when you get a chance. Thanks!

**cc: @saad-ali**

**Comment by rootfs** [comment]
There is no cephfs PV example yet. You can find a similar PV example using NFS at https://github.com/kubernetes/kubernetes/blob/master/examples/volumes/nfs/nfs-pv.yaml

**Comment by resouer** [comment]
+1 to Huamin's link, @keith4743 you can have a try and submit example if it works.

**Comment by keith4743** [comment]
@resouer ok, i will have a try.

BTW, another question, RBD do not support **ReadWriteMany** access mode, why k8s can use it for backend storage?

##### refer to 
http://kubernetes.io/docs/user-guide/persistent-volumes/

**Comment by resouer** [comment]
Kubernetes volume plugin is responsible for detach/attach devices to right node.

**Comment by keith4743** [comment]
get it, thanx.
