### ISSUE TITLE
Eliminate round-trip conversion of API objects in `kubectl convert`

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#3955]
kubectl decodes a json file and encodes it again before sending out the request to the API server, i.e.,
`versioned json-> versioned api object -> internal api object -> versioned api object -> versioned json`
The API server then decodes the versioned json and converts it to the internal API object. 

It is debatable whether kubectl needs to perform the round-trip conversion, since the API server would perform the similar process immediately after receiving the request. Can we simplify this?

@bgrant0607 @smarterclayton

**Comment by smarterclayton** [comment]
Right now, the mutation we are doing on create/update is to set the namespace of the object, and during update we set the resource version.  Ideally, we'd be able to do this opaquely, and with less conversions (perhaps by having a runtime.Object that supported deferred decoding by working a bit like runtime.Unknown).  Right now we don't assume that it's safe to mutate the JSON directly because we'd have to write code for each object type that says what sort of mutation we need for metadata (we *can* read it from the scheme via the name conversion rules, but it's a bit tricky because we don't define what fields are metadata).  The assumption that an apiversion can have rules defined on it is invalid (because eventually core resources will split and migrate at different times, so they may have different rules).

Once we nuke v1beta1/2, it would be a good time to go through the code and simplify a bit to say that there is a fast path for certain known object types (core resources) which can bypass direct conversion and do mutation directly on the JSON, and the rest can use the slower pass for mutation.

----- Original Message -----

**Comment by bgrant0607** [comment]
Some observations:
* So long as defaults are set by kubectl, we'll need to capture user intent first in order to facilitate merging an updated configuration with the live desired state.
* Obvious but worth stating: apiserver can't rely on kubectl to apply defaults. 
  1. The API has other clients.
  2. We need to retain the ability to add new fields without changing the api version.

**Comment by thockin** [comment]
Yeah, its dubious that clients should even be able to see internal structs
and conversion.  The obvious exception is validation, with the caveat that
it could drift.

If validation is applied to versioned structs, then clients can stay
versioned.  To get validation we will need per-version defaulting.
Luckily....

**Comment by bgrant0607** [comment]
We should use (potentially cached) swagger for basic (optional) client-side validation. That approach will work with newer releases, new versions, and new objects (plugins, etc.). 

Detailed validation that can't be expressed via swagger can be performed by the server.

**Comment by derekwaynecarr** [comment]
Some of the work I did with RESTMapper last week could be used in the future where we introspect swagger and build a RESTMapper from it on the client.

**Comment by yujuhong** [comment]
Agreed that clients should not have to perform the conversion. What's the main purpose of client-side validation?

**Comment by thockin** [comment]
Client-side validation can be lower-latency.

**Comment by smarterclayton** [comment]
Clients can be about validation, which increases user frustration (go to web UI, set something, go to client, can't set it, hate product forever).  I would argue client validation is always optional and as much as possible comes from source of truth (schema exposed a la swagger, which is a reasonable compromise).

----- Original Message -----

**Comment by smarterclayton** [comment]
"can be very wrong"

----- Original Message -----

**Comment by bgrant0607** [comment]
Agreed that we want the source of truth to come from the server.

**Comment by bgrant0607** [comment]
Found that the test for template-based printing in kubectl (resource_printer_test.go) failed when I removed the json tags on api/types.go for #3933.

**Comment by bgrant0607** [comment]
cc @vishh

**Comment by bgrant0607** [comment]
Another wrinkle -- version negotiation: #9762

**Comment by krousey** [comment]
My plan to attack this is to decode things to `runtime.Unstructured` and use the dynamic client for most operations. Here's a quick guess at commands that can be switched to decoding to `runtime.Unstructured`

 - annotate
 - apply
 - create
 - delete
 - edit
 - get
 - label
 - replace

I plan on adding a method to `cmdutil.Factory` to get dynamic clients, and the command by command, switching the decoder and changing use of `Helper` to dynamic client.

**Comment by krousey** [comment]
cc @kubernetes/sig-api-machinery @kubernetes/rh-ux

**Comment by smarterclayton** [comment]
Sounds reasonable to me.  I'm currently concerned that there is use of the
third party decoder in certain methods - we need to put that under the
decoder returned by the factory in some code paths, and you may hit that.

**Comment by krousey** [comment]
@smarterclayton Just took a quick peek at the third party codec. From what it looks like, the dynamic client would exhibit the exact same file->wire behavior just with different internal representation. I'll be sure to cc on PRs and maybe you can point out what you mean.

**Comment by smarterclayton** [comment]
All I meant was that no code outside of cmdutil.Factory() needs to be aware
of ThirdPartyCodec.  Right now, it's littered through the codebase next to
the codec we pass through - the original intent of the RESTMapper and Codec
and ObjectTyper interfaces is that they're supposed to hide those details
from consumers in the code.

**Comment by lavalamp** [comment]
This didn't make the date. :'(

**Comment by krousey** [comment]
With my most recent change, kubectl replace and create no longer do round trip conversions on the client side. I believe that covers most of the bugs we had with client-side conversion/defaulting.

**Comment by smarterclayton** [comment]
Phenomenal

**Comment by thockin** [comment]
w00t!  that's huge.

**Comment by lavalamp** [comment]
@krousey is there more to do or can we close this issue?

**Comment by krousey** [comment]
@lavalamp Because of the way we do patching (relies on data being of the same version and also needs versioned struct tags for merge strategies), anything that computes a strategic merge patch still does client side conversion. I may have missed a few, but that's `apply`, `edit`, `label`, and `annotate`. I think `label` and `annotate` don't have any danger of introducing fields that have defaulting. `apply` and `edit` could potentially introduce new fields to an object that has some defaulted internals. It is *possible*, but I think most fields are defaulted before clients that `apply` or `edit` see the object.

We'd have to fix how we compute patches client-side (and/or handle them server-side) to change that. I don't know if we want to attempt that, and if we do, whether this is the place to track that effort.

**Comment by smarterclayton** [comment]
For operations not on the server we can either implement one patch
calculation for each API version kubectl supports, or split defaulting
into its own pass and allow conversion without defaulting (we are
going to have to do that anyway for other reasons).  The latter could
still introduce patch artifacts.

The "set" commands are going to end up having a lot of internal code
that needs patch.  I would regret the cut and paste, but one function
per version isn't the end of the world.

**Comment by lavalamp** [comment]
Kicking this out of the milestone since we're not planning on doing more at the moment.

**Comment by smarterclayton** [comment]
This was mostly completed in 1.6.  Some specific commands still use internal version.

**Comment by krousey** [comment]
reassigning to @lavalamp as I haven't actually worked on this in a while.

**Comment by liggitt** [comment]
/unassign @lavalamp
/assign @seans3 

I think `kubectl convert` is the last place this is being done

**Comment by thockin** [comment]
Is this still a real issue?

**Comment by liggitt** [comment]
This functionality got split out to kubectl-convert so kubectl no longer has a dependency on internal types. I think that's the final destination and this can be closed
