### ISSUE TITLE
kube-proxy container image without debian underneath?

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#39696]
We currently build from a base image that has debian and iptables installed.  I wonder if we can find or buidl something smaller and less exposed?  Maybe a static iptables build?

**Comment by thockin** [comment]
@kubernetes/sig-network-misc

**Comment by bowei** [comment]
Does alpine work? Or we need a customized iptables version:

```
/ # apk add iptables
/ # iptables --version
iptables v1.6.0
```

**Comment by thockin** [comment]
How responsive is Alpine to things like CVEs?  I am looking for a long-term
solution that requires less work from us :)

**Comment by bowei** [comment]
Yeah -- not too sure about that. If we compile completely from source, we would take over the security patching though? I have had some weird behavior trying to use CFLAGS=-static building on a Debian system, but running with a Alpine musl libc due to some libc functions that require dynamic loading.

**Comment by thockin** [comment]
Maybe we can just build a container that has iptables and nothing else?

**Comment by eparis** [comment]
Can I ask "why".  What does "smaller" really get us? At least with debian we have a distro with some real trust and respect behind it. What is the size of the base doing that we should jump through any hoops at all? Even the tiniest hoop....

**Comment by thockin** [comment]
CVEs - scanning tools are starting to become de rigeur and debian and
ubuntu images all have open CVEs.

**Comment by timstclair** [comment]
This is a broader issue than just kubeproxy - I filed https://github.com/kubernetes/kubernetes/issues/40248 to make a Kubernetes wide policy. Let's keep this issue to track the specific problems around kubeproxy though.

**Comment by cemo** [comment]
Our operations have same concerns as @thockin stated. We are using `hyperkube` and scanners are complaining about CVEs. My last scan result in more than 30 critical issue. So what is the best practice to update these containers? I am afraid of screwing up the things and having more issues. I would be glad that anyone shed light on this topic as well.

**Comment by timstclair** [comment]
@cemo - The short-term solution is to rebuild the image, which should automatically pull in upstream fixes. Longer term (1.6 timeframe), @ixdy and I are working on a multi-pronged approach to fixing these issues in the future.

In response to some of the issues stated above, I do not think we should build our own static iptables (and other external dependencies). If we did, we would need to manually track CVEs in those dependencies since package based scanners would not work, and we would be responsible for patching. In contrast, if we use a distribution like alpine CVE scanning is more easily automated, and we can rely on the package maintainers to handle patching. More discussion on #40248

**Comment by cblecker** [comment]
/remove-lifecycle rotten
I believe this is still relevant.

**Comment by ixdy** [comment]
x-ref continued discussion in https://github.com/kubernetes/kubernetes/issues/70249.

**Comment by BenTheElder** [comment]
extra current: https://github.com/kubernetes/kubernetes/issues/109406
