### ISSUE TITLE
A pod with a toleration gets scheduled on a node with no taints

### ISSUE THREAD

**Issue by aveshagarwal** [kubernetes/kubernetes#39818]
As per the doc: https://github.com/kubernetes/kubernetes/blob/master/docs/design/taint-toleration-dedicated.md, It says: "..Or to give all pods that require GPUs access to GPU nodes, an admission controller would add the toleration for GPU taints to pods that request the GPU resource...." .

As per my understanding if a pod has a toleration for GPU resource, but there is no node in the cluster that is tainted for GPU resource, then the pod should not scheduled at all.

However, I did a test on a simple cluster with one node, where the node did not have any taint, but I created a pod with a tolerations: key1=value1:Noschedule and I found that the pod gets scheduled on the node.  Is this working as expected? As per my understanding, the pod should not have been scheduled on the node, so is my understanding incorrect?

@kubernetes/sig-scheduling-misc

**Comment by aveshagarwal** [comment]
Otherwise, it would require to add something like node selector labels to pods to restrict them to only those nodes. Because there is no point in scheduling a pod on a node with no GPU resource.

**Comment by davidopp** [comment]
This is working as expected (though maybe we should clarify the documentation).

A node with no taints allows any kind of pod to schedule, regardless of whether the pod has tolerations.

A node with taint X allows only pods that tolerate X to schedule. (The pod may tolerate other things as well; what's relevant is whether it tolerates X.)

The way to think of taints is that it only prevents pods from scheduling on node(s). If you want pods to schedule on specific nodes, then you need to add node affinity, *unless* the nodes you want to schedule on are exactly the complement of the tainted nodes.

Does that make sense?

**Comment by aveshagarwal** [comment]
@davidopp thanks. wanted to double check. Though wondering what is the disadvantage of restricting pods with tolerations to not get scheduled on nodes with no taints?

**Comment by jeremyeder** [comment]
The presence of a toleration on a pod represents a specific "pod-routing intent" by the author. Isn't it the case that landing pods on nodes without that taint is a violation of the user's intent?

Without the behavior described by Avesh, we have to couple tolerations with label-based node-selectors.  It's really awkward.  I wonder if there should be a toleration-effect to smooth out this oddity.

**Comment by derekwaynecarr** [comment]
basically, this means for many classes of workloads, you would have to have a `PodAffinity` that matched each toleration.  I could see this being a pain-point.  Maybe we need something akin to ServiceInjectionPolicy for Tolerations/PodAffinity/PodAntiAffinity that can cover a label selected group of pods and apply defaults so users do not need to muck with each pod spec.

**Comment by aveshagarwal** [comment]
@jeremyeder One work around (or whatever you may call it), that is possible is that to taint all non-special/general nodes with a default taint and all non-special/general pods get similar toleration. That would kind of partition nodes into special and general nodes. This would ensure that general pods get to schedule only on general nodes and special pods get to schedule on special nodes.

**Comment by davidopp** [comment]
> The presence of a toleration on a pod represents a specific "pod-routing intent" by the author. Isn't it the case that landing pods on nodes without that taint is a violation of the user's intent? Without the behavior described by Avesh, we have to couple tolerations with label-based node-selectors. It's really awkward. I wonder if there should be a toleration-effect to smooth out this oddity.

Taints and tolerations aren't really expected to be used by end-users. For example, one of the main use cases is for dedicated node. You could imagine a tool that takes some kind of high-level specification as input, and places taints on the appropriates nodes and configures an admission controller to apply the appropriate tolerations (and labels and node affinity, when needed) on pods based on namespaces or users or whatever property/properties you use to decide who should be able to use each of the groups of dedicated nodes. 

But to answer your question more directly, the reason a toleration does not also imply a node affinity is that it would prevent us from describing policies where the node affnity part is not desired. It's better to split the "I can schedule on a certain group of nodes that normally nobody can schedule on" behavior from the "I must schedule on a certain group of nodes" behavior. If you combine these concepts, then it wouldn't be possible to say a pod can schedule on nodes that are un-tainted or have particular taint(s).
Moreover the implied "I must schedule on..." behavior would have to be somewhat complicated to account for pods that tolerate multiple different taints (e.g. a cluster with three dedicated node groups, and a pod that can schedule onto two of the three -- the implied node affinity would be an OR of the two groups where it is allowed to schedule). Lastly the implied node affinity couldn't be implemented using the current node affinity code, because node affinity applies to labels, which are a different object from taints -- there's no notion of affinity to nodes with particular taints.

So if you want to give a pod permission to schedule on a particular group of nodes that nobody else is allowed to use, *and* the pod should *only* schedule on those nodes (e.g. not also un-tainted nodes), then you should pair the toleration with a node affinity. I realize this is a bit verbose but I think decomposing these concepts and making them explicit is better than trying to make node affinity be an implicit behavior of tolerations.

**Comment by timothysc** [comment]
> I realize this is a bit verbose but I think decomposing these concepts and making them explicit is better than trying to make node affinity be an implicit behavior of tolerations.

+1, I'm going to close the issue as... expected.  I've always viewed affinity + taints&tolerations as admin policy not user preference.

**Comment by jayunit100** [comment]
@aveshagarwal can you update the issue text at the top to clarify why this was closed?  that way newcomers to t&t don't have to scroll to the bottom to realize this is just a doc. ambiguity/improvement rather then a real bug

**Comment by aveshagarwal** [comment]
@jayunit100 I wish there was a label something "working as expected" that I could set.

**Comment by aveshagarwal** [comment]
@jayunit100 I have updated the issue text if thats what you want.

**Comment by jayunit100** [comment]
thanks avesh
