### ISSUE TITLE
Review custom conversions and document why each one is needed

### ISSUE THREAD

**Issue by kargakis** [kubernetes/kubernetes#39865]
Custom conversions can end up rotting and bite us hard. Especially as our apis evolve, some may become obsolete and there is no clear way to maintain them apart from having deep knowledge of the code.

For example, it's not clear to me even though I have been developing part of the Deployment and ReplicaSet apis why do we need the conversions in https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/extensions/v1beta1/conversion.go at this point. Is it because our generator has limitations and still can't handle specific types? We don't seem to try to maintain backwards compatibility.. We should strive to get rid of custom conversions IMO.

@kubernetes/sig-api-machinery-misc

**Comment by deads2k** [comment]
> We should strive to get rid of custom conversions IMO.

I agree that custom conversions (especially unnecessary ones) can make the code more complicated, but I don't think we can resolve the problem by trying to factor them out.  If you are going to have a hubbed conversion strategy, then only one of the external versions can match the hub.  All the others will have custom conversion logic to wire them together.

So I think that rather than trying to eliminate them, we should try to find ways to avoid them rotting and make them more reliable.  That was the intent behind the fuzzing tests and changes that Tim made to allow "generate as much as you can, call the generated conversion, then fix up".

**Comment by lavalamp** [comment]
Custom conversions should be documented and unit-tested (for the thing that
they're customizing). It looks like the deployment ones aren't sufficiently
clear.

**Comment by soltysh** [comment]
Eventually, if doable we should replace them with auto-generated ones. The last example (#39683) was failing for me due to not having a conversion between `intstr.IntOrString` and `*intstr.IntOrString` which could be generalized, I hope.

**Comment by soltysh** [comment]
On the other hand, I'm not sure how the auto-generated code handles the cases like in #39683, since that has external version in `apps/v1beta1`, but internal in `extensions`, so I'm not quite sure.

**Comment by smarterclayton** [comment]
You can create conversions between *intstr and intstr.  It's just something we don't generate today.

**Comment by kargakis** [comment]
> You can create conversions between *intstr and intstr. It's just something we don't generate today.

Opened https://github.com/kubernetes/kubernetes/issues/42332
