### ISSUE TITLE
Write e2e tests for wrong volume being mounted

### ISSUE THREAD

**Issue by gnufied** [kubernetes/kubernetes#39910]
if we can reproduce bug mentioned in https://github.com/kubernetes/kubernetes/issues/29324 via an e2e test, that would help us in tracking it down.

@jingxu97 if you know the steps that can reproduce that bug with latest version let me know. I read the whole thread and the bug appears pretty old. The original reason why this bug surfaced seems to have been fixed long back but it is still happening so we would need steps to reproduce. 

cc @chrislovecnm @kubernetes/sig-storage-misc

**Comment by chrislovecnm** [comment]
cc @kubernetes/sig-aws-misc

**Comment by chrislovecnm** [comment]
Can we get this tagged properly?

**Comment by jingxu97** [comment]
I think the following step should be able to reproduce the error

1. Disable attach/detach reconciler sync by setting DisableAttachDetachReconcilerSync to true when starting the cluster with only one node.
2. Create two AWS volumes v1 and v2, create two pods p1 and p2 which attach v1 and v2 respectively. 
3. Reboot the node, create two volumes v3 and v4, pods p3 and p4 which attach v3 and v4 respectively. 
4. Check p1 and p2 and see what volumes are attached.

**Comment by kris-nova** [comment]
Thanks @jingxu97,

Who did we say was going to try to replicate?

**Comment by gnufied** [comment]
I am going to replicate and get some tests going. @jingxu97 can you assign this to me please

**Comment by jingxu97** [comment]
@gnufied 
I just checked a PR related to this #38818. I think after this PR, the wrong volume is mounted behavior will be changed since the device path will not be reused immediately. 
To reproduce the issue, we have to do the steps as follows
1. Create two AWS volumes v1, create pods p1 and p2 which attach v1, check the attach device path 
2. Reboot the node, create volume v2 and manually attach v2 using the the same device path ( I am not sure this is possible or not)
3. delete p1 and recreate p1 on the node immediately.

**Comment by jeffvance** [comment]
Can this by reproduced on GCE or GKE following @jingxu97 steps above?

**Comment by jingxu97** [comment]
@jeffvance  this issue is specific to AWS. 
@gnufied is this still an issue?
