### ISSUE TITLE
Building a release should update the staging directory

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#40043]
Now that we have moved some code such that it's built out of the staging directory, we should probably update binary and/or release building steps to update the staging directory, or folks' changes won't propagate like they expect. (@cheftako just hit this while changing the labels package.)

@deads2k

**Comment by deads2k** [comment]
@lavalamp only client-go has the unusual, "I need to copy and mutate stuff" problem.  The staging directory for everything else is authoritative.  Because of what client-go does around re-vendoring, it needs to be done *after* changes to apimachinery have propogated through the owning repo.

Being able to call https://github.com/kubernetes/apimachinery/blob/master/hack/sync-from-kubernetes.sh on the master branch and push automatically would be nice though.  I'm no worse than once a day (on workdays), but its a thing that's pretty annoying to do.

I'd say that time trying to carve apart client-go into what's authoritative, what isn't, and having it with a similar `sync-from-kubernetes.sh` script would make like easier though.  Then we could vendor it more normally.
