### ISSUE TITLE
kube-dns should be replicated more than two times

### ISSUE THREAD

**Issue by airstand** [kubernetes/kubernetes#40063]
Hello,
During my conversation with @justinsb , we agreed that kube-dns pod should be replicated on more than one node.

Till now, kube-dns is running just on a single node and if that node comes down the whole cluster is unable to make any DNS queries.

There was some test cases on my side that all of the other nodes inside the cluster are overloaded and kube-dns is not able to fit any of these nodes, if that pod dies on the node that is deployed during cluster creation.

Regards,
Spas

**Comment by AlexLast** [comment]
Thanks for reporting @airstand I've also seen this issue.

**Comment by JeanMertz** [comment]
We've seen the same issues happening. This also makes running preemptible clusters on GKE impossible, because you'll experience cluster-wide DNS outage when a node is swapped for a new one.

In the mean time, we've updated the `kube-dns-autoscaler` ConfigMap to scale the dns deployment to a minimum of two pods, instead of one.

**Comment by airstand** [comment]
We are not able to change ConfigMap in case we are using kops to deploy the whole cluster.

**Comment by MrHohn** [comment]
@airstand How did you fail to change the `kube-dns-autoscaler` ConfigMap? I don't think kops caused this.

**Comment by MrHohn** [comment]
cc @kubernetes/dns-maintainers

**Comment by JeanMertz** [comment]
I'm wondering; is there any downside to just scaling `kube-dns` to as many nodes as possible, to have the highest possible availability, besides from a minor increase in required resources?

We've set it to two, but I'm still not sure if this is enough, as I now see one of the pods not starting because DNSMasq doesn't have any inodes available (an issue we've been seeing for some time now, but are unable to find its cause), and the second kube-dns pod was just deleted because its preemptible node was terminated, again causing a cluster-wide DNS outage.

Ideally (at least for now), we'd scale the kube-dns pods to the amount of machines.

I'm unsure however if having two dns pods on the same machine can cause problems, since there is no guarantee (since these aren't DaemonSets, and pod anti-affinity isn't available yet) that the pods won't end up on the same machine.

**Comment by bowei** [comment]
@JeanMertz -- Can you post the log for DNSmasq inode problem?

Apart from resource utilization, there should be no problem with running more copies of the DNS service.

I would not recommend use of pre-emptable nodes for running important services such as DNS however.

**Comment by airstand** [comment]
@JeanMertz I also want to see what the inode problem is?

Btw.. is a great idea to have kube-dns deployed on each node.

**Comment by JeanMertz** [comment]
@bowei @airstand I also replied here about the inode error: https://github.com/kubernetes/kubernetes/issues/32526#issuecomment-273696911

> I would not recommend use of pre-emptable nodes for running important services such as DNS however.

Fair point. Until now, we really haven't modified any "default" Kubernetes resources in the `kube-system` namespace, but since we started doing this anyway, by updating the `kube-dns-autoscaler` ConfigMap, we might as well update the `kube-dns` deployment to add an affinity to the non-preemptible machines we still have running.

**Comment by MrHohn** [comment]
Looks like [inter-pod anti-affinity](https://kubernetes.io/docs/user-guide/node-selection/#inter-pod-affinity-and-anti-affinity-alpha-feature) is going to beta in 1.6 (#25319)?

BTW, you won't be able to update the `kube-dns` deployment if it's managed by Addon-manager (#36411).

**Comment by JeanMertz** [comment]
@MrHohn thanks for those links.

I'm guessing if this issue is converted to a PR, it would be nice if anti-affinity is added to the kube-dns deployment as well (given both features land in 1.6).

Also, regarding your link about the Addon-manager, does this immutability also apply to the configmap used by the deployment to configure itself? It obviously isn't right now (since we scaled our kube-dns to more than one pod), but I hope that won't change in the future without this issue being fixed.

**Comment by kargakis** [comment]
> I'm guessing if this issue is converted to a PR, it would be nice if anti-affinity is added to the kube-dns deployment as well (given both features land in 1.6).

Note that pod-antiaffinity is alpha in 1.5 and can be specified as an annotation (`scheduler.alpha.kubernetes.io/affinity`) in the pod template. 
https://kubernetes.io/docs/user-guide/node-selection/

**Comment by JeanMertz** [comment]
@kargakis Thanks, but we're running on GKE, so that's not a solution to us unfortunately 😢

**Comment by MrHohn** [comment]
@JeanMertz Yeah, make sense to me to put anti-affinity into the kube-dns deployment.

The tricky point about `kube-dns-autoscaler` ConfigMap is that it is managed by kube-dns-autoscaler instead of Addon-manager. So it is allowed to be modified, and will be re-created with the template value if it is deleted. I believe this pattern will not change for kube-dns-autoscaler.

**Comment by bowei** [comment]
@JeanMertz, @airstand  -- adding anti-affinity to the kube-dns pod spec would be great target for community contribution :-)

**Comment by thockin** [comment]
I thought the only way we end up with one DNS replica is if we have 1 node
- am I mistaken?  I thought we immediately go to 2 replicas in case of 2
nodes, and then go CPU-proportional after that.  Something like that is
what should be happening, anyway...

**Comment by JeanMertz** [comment]
@thockin that's not what we are seeing on GKE.

This is what is currently configured on our cluster:

```
$ k get no --no-headers | wc -l
       5

$ k get --namespace=kube-system -ojson cm kube-dns-autoscaler | jq -r .data.linear
{"coresPerReplica":256,"min":2,"nodesPerReplica":16}
```

but this is **after** we manually set the `min` value to `2`, it was set to `1` ever since we booted this (and one other) cluster on GKE.

**Comment by thockin** [comment]
Indeed, @mrhohn, it looks like we lost that property in some optimization
pass.  Can we bring it back?

https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/dns-horizontal-autoscaler/dns-horizontal-autoscaler.yaml#L48

**Comment by MrHohn** [comment]
@thockin Sure, I will change it back.

**Comment by soudy** [comment]
I would like to see some way of giving `kube-dns` pods affinity, because as @bowei said, having `kube-dns` on a preemptible node is not a good idea. In our current setup we have 3 preemptible nodes and 2 regular nodes, and `kube-dns` often lands on a preemptible node.

**Comment by rvrignaud** [comment]
Hello,

What is the status of this one ? On my 2 GKE clusters running 1.7.6 I still have a kube-dns deployment configured with only 1 replica.
My `kube-dns-autoscaler` configmap is still:
```
{"coresPerReplica":256,"min":1,"nodesPerReplica":16}
```

**Comment by MrHohn** [comment]
@rvrignaud We've updated the default parameters to ensure at least 2 replicas when cluster has >= 2 nodes by https://github.com/kubernetes/kubernetes/pull/42065. Your clusters are using the old default parameters likely due to https://github.com/kubernetes/kubernetes/issues/45851 --- we don't update those params if cluster is upgraded from an older version.

For getting the latest default params for the confimap, you could:
- Delete `kube-dns-autoscaler` configmap in `kube-system` namespace and dns-horizontal-autoscaler pod will recreate a new configmap with default params. OR
-  Manually edit that confimap. Please take https://github.com/kubernetes/kubernetes/blob/v1.7.6/cluster/addons/dns-horizontal-autoscaler/dns-horizontal-autoscaler.yaml#L47 as reference.
