### ISSUE TITLE
Docker Vulnerability CVE-2016-9962

### ISSUE THREAD

**Issue by geojaz** [kubernetes/kubernetes#40061]
**Is this a request for help?** No

**What keywords did you search in Kubernetes issues before filing this one?** Docker/CVE
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug/Potential Problem Report

Please see Docker CVE-2016-9962 related to insecure opening of file-descriptor allows privilege escalation.

Which version of docker are we working with? Do we have a plan to upgrade to a non-compromised version?

Originally referenced in [kops issue #1520](https://github.com/kubernetes/kops/issues/1520)

**Comment by justinsb** [comment]
cc @dchen1107

**Comment by resouer** [comment]
More info: CVE-2016-9962 has been fixed in docker [v1.12.6](https://github.com/docker/docker/releases/tag/v1.12.6).

Docker v1.12 has been validated in #28698, latest validated version is v1.12.3, see: [External Dependency](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG.md#external-dependency-version-information)

Maybe just need validation for v1.12.6.

**Comment by druidsbane** [comment]
My experience with 1.12.6 going from 1.11.2 is that it ended up breaking networking in my cluster.  I upgraded a pre-existing cluster that was already running on 1.11.2 on Ubuntu 16.04.  I don't know 100% if I upgraded Docker incorrectly as in downgrading I had to delete the /var/lib/docker/network directory for it to start up properly.

The issue with 1.12.6 was that after a few days from the upgrade that was working fine, suddenly the networking broke with no ability to communicate outside the cluster, only within it.  It is using Kubernetes 1.5.2 and Weave as the CNI.

**Comment by yujuhong** [comment]
@justinsb, you weren't there in today's sig-node meeting, so this issue was skipped (actually @dchen1107 and @timstclair were also unable to attend).

I discussed with @timstclair last week, and here are our thoughts. First, the CVE is not good, but in kubernetes, most pods have access to the apiserver and can do more damage if they are malicious. Normal users who don't enforce extra security measures should not worry too much about this CVE. For users who do care about this specific CVE:
 - The kubernetes master branch (1.6) tests docker 1.2.6 on ubuntu in the node e2e test suites. Users can probably switch to 1.12.6.
 - For 1.5, we tested 1.12.3. I believe 1.12.6 should also be compatible. We can consider bumping the docker version to 1.12.6 in the 1.5 node e2e branch. (/cc @dchen1107). For the users who care about this CVE, they can switch to 1.12.6.
 - For 1.4, we simply don't support 1.12+, and it'd be too much work to make it compatible. Users are recommended to upgrade to kubernetes 1.5 instead.

These are just general guidelines. Users should first check with their k8s/cloud/os vendors and see if the docker they use have been patched, and which version of docker is recommended. For GCI (COS) and the debian-based CVM images, the GCI/GKE team are working on patching them.

Thoughts?

**Comment by alex88** [comment]
This not only would help security but also reliability as the current version (1.12.3) has deadlock issues (fixed in 1.12.4) and in our case we have to restart the docker services docker on nodes at least 2-3 times a week making all containers restart
