### ISSUE TITLE
[Kubemark] Make master startup and hollow-node creation asynchronous

### ISSUE THREAD

**Issue by shyamjvs** [kubernetes/kubernetes#40151]
Currently, the hollow-nodes creation phase is reached only after all the startup in the master has finished and the apiserver is checked to be reachable.
However, I think that performing the master setup in the background while the hollow nodes are simultaneously getting ready should save us some time.
This saving could be considerable in the case of our large CI tests for kubemark.

@wojtek-t @gmarek Do you think this is worthwhile to do and/or any issues in doing this?

cc @kubernetes/sig-scalability-misc

**Comment by shyamjvs** [comment]
In principle, the only steps that are common to and should precede master and hollow-node startup is creation of the MASTER_IP and pki. After that we can fork our script.

**Comment by wojtek-t** [comment]
To be honest, I'm not convinced this would significantly help. The issue is that the hollow-nodes will not be able to connect to apiserver (as it will still be down) and thus will be failing. But maybe even with restarts it will be faster.

Anyway - I think that we don't have problems with the time of setting up kubemark now, so I wouldn't spend time on it, at least now.

**Comment by shyamjvs** [comment]
> Anyway - I think that we don't have problems with the time of setting up kubemark now, so I wouldn't spend time on it, at least now.

Ok, so let me close this issue for now. We can look into this again if/when needed in future.
