### ISSUE TITLE
Make kubectl rollout work with federated deployments

### ISSUE THREAD

**Issue by mwielgus** [kubernetes/kubernetes#40323]
Currently no history information is stored in federated deployment so no rollout rollback is possible.

cc: @nikhiljindal

**Comment by nikhiljindal** [comment]
To clarify, kubectl rollout should work fine unless a new cluster is registered which wont have the rollout history, right?

If all clusters have been there since the start then rollout should work fine.
cc @csbell since this came up recently in a discussion with him.

cc @kubernetes/sig-federation-bugs

**Comment by nikhiljindal** [comment]
Also link to the design proposal to fix this: https://github.com/kubernetes/community/pull/325

**Comment by quinton-hoole** [comment]
Required for GA of federation.  I'm pretty sure that @mwielgus is not currently working on this, so unassigning.  Feel free to re-assign as necessary.

**Comment by irfanurrehman** [comment]
This issue was labelled only for sig/multicluster and is thus moved over to kubernetes/federation#100.
If this does not seem to be right, please reopen this and notify us @kubernetes/sig-multicluster-misc.
/close
