### ISSUE TITLE
Design and document translations

### ISSUE THREAD

**Issue by brendandburns** [kubernetes/kubernetes#40643]
So far we have a simple translation directory:

https://github.com/kubernetes/kubernetes/tree/master/translations

With a single translation file per language, e.g.

https://github.com/kubernetes/kubernetes/tree/master/translations/kubectl/en_US/LC_MESSAGES

There is some discussion that perhaps this should be multiple files.  The purpose of this issue is to discuss this.

**Comment by zen** [comment]
There are different ways of structuring this, but it's not a main concern, we can leave with one folder per component, although different layout should be supported by underlying library.
Biggest concern is that using current library (http://github.com/chai2010/gettext-go/gettext) we cannot extract translatable strings from the code. 
Usual workflow is as follows:
- identify strings for translation
- wrap them in i18n function
- run extraction using xgettext (or other tool) based on keywords (POT file is generated)
- run init on POT file to generate PO files
- translate PO files
- generate MO files

After updating string, workflow is similar, but POT file gets updated and gettext library is identifying "fuzzy" strings that require review. 
AFAICS with current implementation it will not be possible, because underlying library does not support:
- string extraction
- POT updates

Unfortunately I don't see an easy way to fix that. I would suggest to use another, better designed library. One candidate is https://github.com/gosexy/gettext It supports all normal l10n / i18n workflows.

We can take a look how much effort is needed to reimplement i18n. 

CC @pigmej

**Comment by brendandburns** [comment]
@zen thanks for the detailed comments, I'll look at converting to a more gettext/xgettext based workflow.

The trouble with https://github.com/gosexy/gettext is that it is based on calling into the gettext C library rather a 100% golang implementation. This makes portability and building kubernetes harder, so I would very much prefer not to do that.

I think that we can take the extraction tool and modify it so that it will work to extract the i18n strings from kubectl as well.  That will handle both string extraction and POT updates.

**Comment by kargakis** [comment]
@kubernetes/sig-cli-misc

**Comment by zhangxiaoyu-zidif** [comment]
Only kubectl has translations?
I think any component,e.g. kube-controller-manager, kube-scheduler, should have its own translations when execute --help. That would look great :)
