### ISSUE TITLE
Kube-api could assign nodeport to already used one

### ISSUE THREAD

**Issue by Oloremo** [kubernetes/kubernetes#40920]
**Kubernetes version** (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1+coreos.0", GitCommit:"cc65f5321f9230bf9a3fa171155c1213d6e3480e", GitTreeState:"clean", BuildDate:"2016-12-14T04:08:28Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1+coreos.0", GitCommit:"cc65f5321f9230bf9a3fa171155c1213d6e3480e", GitTreeState:"clean", BuildDate:"2016-12-14T04:08:28Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**:

Bare metal nodes
- **OS** (e.g. from /etc/os-release):

Ubuntu 16.04 x64
- **Kernel** (e.g. `uname -a`):

`Linux node1 4.4.0-38-generic #57-Ubuntu SMP`

**What happened**:
k8s tried to create a node port and hit a situation when this node port was already used.
So it reported this error:
```
E0203 14:08:15.591906       1 proxier.go:1108] can't open "nodePort for ccp/memcached:11211" (:34104/tcp), skipping this nodePort: listen tcp :34104: bind: address already in use
```

and that service iptables rules were incomplete, which leads to non-working service from this node.

**How to reproduce it** (as minimally and precisely as possible):
Make a node-ports range really small, like 1 ip, bind something to this port and after try to create a service with node port.

**What you expected to happen**:
Not sure, probably a retry, or probe first. And some kind of visible error, like service creation failer.

Other possible solution is to set `net.ipv4.ip_local_reserved_ports` to the node ports range. Or at least add this to the documentation, like OS pre-requirements.

**Comment by thockin** [comment]
Should be fixed in 1.6

**Comment by linhbombk** [comment]
It is still in 1.6.9

**Comment by thockin** [comment]
Can you provide more repro details?

@mixia @dcbw

**Comment by linhbombk** [comment]
The last time it happened same as mentioned symptom this issue.
I will try to reprodure as @Oloremo's way and update here.

**Comment by mitio** [comment]
We just hit the same issue with Kubernetes 1.9.0. The fix proposed by @Oloremo to use `net.ipv4.ip_local_reserved_ports` and [implemented in this PR](https://github.com/kubernetes-incubator/kubespray/pull/969) seems like the sensible thing to do, but it depends on how you install your Kubernetes cluster.

Since we're currently using kops, then it'll be kops' responsibility to properly configure `ip_local_reserved_ports`. From what I can tell, this doesn't happen yet in kops, so we'll open an issue there.

In the meantime, you could consult your installation method of choice, check this `sysctl` setting and possibly look for a way to manually configure it.
