### ISSUE TITLE
Basic StatefulSet functionality Scaling down before scale up is finished should wait until current pod will be running and ready before it will be removed

### ISSUE THREAD

**Issue by cheftako** [kubernetes/kubernetes#40953]
[https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/39901/pull-kubernetes-e2e-kops-aws/10745/](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/39901/pull-kubernetes-e2e-kops-aws/10745/)

```
go run hack/e2e.go -v -test --test_args='--ginkgo.focus=StatefulSet\s\[k8s\.io\]\sBasic\sStatefulSet\sfunctionality\sScaling\sdown\sbefore\sscale\sup\sis\sfinished\sshould\swait\suntil\scurrent\spod\swill\sbe\srunning\sand\sready\sbefore\sit\swill\sbe\sremoved$'
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/statefulset.go:274
Test Panicked
/usr/local/go/src/runtime/panic.go:458
from junit_19.xml
```

**Comment by luomiao** [comment]
Got the same error for e2e test:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/40843/pull-kubernetes-e2e-gce/16475/

**Comment by calebamiles** [comment]
Could someone from @kubernetes/sig-apps-bugs help with properly routing this issue? Thanks!

**Comment by fejta** [comment]
This seems to be more a problem with statefulset than aws? 

It is also a top source of flakiness in GKE and GCE environments:
http://storage.googleapis.com/kubernetes-test-history/static/suite-ci-kubernetes-e2e-gci-gce.html
http://storage.googleapis.com/kubernetes-test-history/static/suite-ci-kubernetes-e2e-gce-etcd3.html
http://storage.googleapis.com/kubernetes-test-history/static/suite-ci-kubernetes-e2e-gci-gke.html

Assigning some people to help this get attention

**Comment by ncdc** [comment]
This is panicking because a watch on pods is getting back a `*v1.Status`, and not a `*v1.Pod`, as expected here: https://github.com/kubernetes/kubernetes/blob/7c7ca34246651243f5422897ab4eab56499b7403/test/e2e/statefulset.go#L259. I have this running in an infinite loop locally with some added code to print out the details of the status object, but have yet to get it to flake.

**Comment by bprashanth** [comment]
I checked https://github.com/kubernetes/kubernetes/issues/40953#issuecomment-277766908, it's a panic because this is not a pod: 
https://github.com/kubernetes/kubernetes/blob/master/test/e2e/statefulset.go#L259
It's probably a tombstone, like: https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/replicaset/replica_set.go#L376

**Comment by bprashanth** [comment]
Oh, didn't realize @ncdc mentioned the exact same symptom. Also the tombstone theory is invalid because it's a raw watch.Until, not a watch through the informer like other controllers.

**Comment by dshulyak** [comment]
Sorry, it was my mistake. Will submit a fix in a moment

**Comment by kow3ns** [comment]
@foxish Can we close this? This is no longer flakey.

**Comment by foxish** [comment]
Closing.
