### ISSUE TITLE
Kubelet Garbage Collection should account inode usage as well.

### ISSUE THREAD

**Issue by MrHohn** [kubernetes/kubernetes#41033]
Related issue: #32526

[Kubelet Garbage Collection](https://kubernetes.io/docs/admin/garbage-collection/) is taking disk space usage as the factor for triggering image collection. From the [codes on current HEAD](https://github.com/kubernetes/kubernetes/blob/a461eab321f8262a48d71eda94129c6db524bf6f/pkg/kubelet/images/image_gc_manager.go#L246-L284), it seems like the inode pressure is not accounted.

However it is not rare that with some large Docker images, we could consumes more than 90% inodes with lower than 50% disk space occupied on nodes. In this case the image garbage collection won't help. For now, the only chance kubelet will delete unused images for reclaiming inodes is during eviction manager eviction under inode pressure, which may instead lead to issue #41032.

We should consider accounting the inode usage as well when do garbage collection.

@dashpole @kubernetes/sig-node-bugs

**Comment by dashpole** [comment]
This is something we should do, although the periodic garbage collection (from the link), doesnt look like it has any effect, even for disk.  The default threshold is 90%, which is the same threshold as the eviction manager (nodefs.available<10%).  In addition to changing periodic garbage collection to take inodes into account, we should consider lowering the threshold so that it kicks in before the eviction manager, rather than at the same time.

That being said, I think the more fundamental issue is described by [this comment in #41032.](https://github.com/kubernetes/kubernetes/issues/41032#issuecomment-277794667)

**Comment by dashpole** [comment]
@MrHohn can you assign me to this?

**Comment by MrHohn** [comment]
@dashpole Thanks for the info. Though I don't have permission to assign neither...

**Comment by yujuhong** [comment]
@dashpole as you wish

**Comment by dashpole** [comment]
I just realized that Kubelet Garbage Collection is actually meant to be replaced by eviction according to [the eviction documentation](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/kubelet-eviction.md#deprecation-of-existing-features).  That would explain why the thresholds are the same.  
@derekwaynecarr are we still planning to depreciate periodic Garbage Collection (based on image-gc-high-threshold) in favor of letting the eviction manager handle image garbage collection?

**Comment by s-pk** [comment]
Any progress on this? / Anything I could do to help? Running into full inodes quite often

**Comment by dashpole** [comment]
Running out of Inodes already triggers image garbage collection before evicting pods.
You can verify this in the kubelet logs by looking for `eviction manager: able to reduce nodefsInodes pressure without evicting pods.` or `eviction manager: able to reduce imagefsInodes pressure without evicting pods.`
This issue refers to adding the same functionality to an older component.

**Comment by alexey-medvedchikov** [comment]
:+1:

**Comment by derekwaynecarr** [comment]
@dashpole - the intent was to deprecate the old behavior in favor of the eviction manager itself.  i would like to understand if the eviction support around nodefsInodes or imageFsInodes is insufficient and understand how to further improve eviction manager if need be than add capability to a deprecated component.

@MrHohn -- is there a inode usage target you are looking to achieve?

**Comment by MrHohn** [comment]
@derekwaynecarr Thanks for the response, I think a threshold like 90% inode usage looks reasonable?

Also, given the plan is deprecating the old feature in favor of eviction manager, I should close this issue.

**Comment by moshe0076** [comment]
Hi,

I just hit this problem with Kubernetes 1.5.4. I have a CI/CD cluster with many images pulled each day.
I have run out of Inodes.
In which version of Kubernetes was the this fix implemented?

Thanks!

**Comment by dashpole** [comment]
@moshe0076 Support for inode-based evictions and image garbage collection was added to the eviction manager in 1.4.  If you have set the `--eviction-hard` to include `imagefs.inodesFree`, or `nodefs.inodesFree` on a single-partition system, then you have image garbage collection  based on inode pressure.

Feel free to open a bug and cc me if that is not the case for you.  One thing to note is that if you run pods and do not delete them, then they will continue to consume disk space and inodes until you delete them, and can cause your node to run out of inodes.  This behavior is fixed in 1.7.

**Comment by moshe0076** [comment]
Hi,

Thank you for the prompt response!

I'm using Rancher to deploy the cluster and it looks like the --eviction-hard parameter is not set.
Please correct me if I am wrong, from what I can see, the only default set on this flag is --eviction-hard=memory.available<100Mi. So if the other options are not set, one can just run out of Inodes or disk space eventually?

Thanks for the help.

Moshe

**Comment by dashpole** [comment]
Yes, the 1.6 default for eviction was `--eviction-hard=memory.available<100Mi`.  The default in 1.7 is `--eviction-hard=memory.available<100Mi,nodefs.available<10%,nodefs.inodesFree<5%`.  Yes, if nodefs.inodesFree is not set, then the kubelet will not respond when it runs low on inodes.

**Comment by moshe0076** [comment]
The change in 1.7 is very welcome.

For now I have implemented your suggestion and it does the job.

Thank you so much for your help!

Moshe.
