### ISSUE TITLE
Deleting a pod will logout an iscsi session even if that session is in use by other pods

### ISSUE THREAD

**Issue by adkerr** [kubernetes/kubernetes#41041]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): iscsi session logout

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Kubernetes version** (use `kubectl version`): 
> Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T04:57:25Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}

> Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T04:52:34Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**: Libvirt qemu VM, 4 CPU, 8Gig RAM
- **OS** (e.g. from /etc/os-release): Ubuntu 16.04.1 LTS (Xenial Xerus)
- **Kernel** (e.g. `uname -a`): Linux localhost 4.4.0-62-generic #83-Ubuntu SMP Wed Jan 18 14:10:15 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- **Install tools**: kubeadm
- **Others**:

**What happened**:

If you have multiple pods on the same node using PVCs that are backed by iSCSI LUNs on the same external system over a single iSCSI session (same IQN but different LUN numbers), then deleting one of the pods causes the iSCSI session to terminate for all pods on that node that are using it.

For example, here `pod1` and `pod2` are nginx pods each connected to a different PVC, which are backed by LUNs residing on the same NetApp storage system.  These share a single iSCSI session, differing only by LUN number.  Once pod2 is deleted, all the connected LUNs are no longer available.

`user@localhost:~$ kubectl get pod`
> NAME                       READY     STATUS             RESTARTS   AGE
> kube-flannel-ds-glct5      2/2       Running            0          59m
> pod1                       1/1       Running            0          2m
> pod2                       1/1       Running            0          1m

`user@localhost:~$ lsscsi`
> [6:0:0:0]    disk    NETAPP   LUN C-Mode       8300  /dev/sdb
>[6:0:0:1]    disk    NETAPP   LUN C-Mode       8300  /dev/sdc

`user@localhost:~$ kubectl delete pod pod2`
> pod "pod2" deleted

`user@localhost:~$ kubectl get pod`
> NAME                       READY     STATUS             RESTARTS   AGE
> kube-flannel-ds-glct5      2/2       Running            0          1h
> pod1                       1/1       Running            0          2m

`user@localhost:~$ lsscsi`
`user@localhost:~$`

**What you expected to happen**:

I expect that in-use iSCSI sessions are not terminated

**How to reproduce it** (as minimally and precisely as possible):

1. Create 2 PVs and PVCs that are backed by a single storage system that aggrates iSCSI connections into a single session.
2. Create 2 pods that consume those PVCs
3. Delete one of the pods

**Anything else we need to know**:

**Comment by calebamiles** [comment]
Could someone from @kubernetes/sig-storage-bugs please take a look? Thanks!

**Comment by rootfs** [comment]
looking...

**Comment by adkerr** [comment]
Minor clarification: the last lsscsi command from the example was executed on the same system as the other commands (my hostname obfuscation failed me here)

**Comment by cdragga** [comment]
It looks like the problem is in line 86 of `pkg/volume/iscsi/iscsi_util.go`, in the `getDevicePrefixRefCount` function.  The check evaluates whether a given mount path starts with the prefix (protocol + target portal + target IQN) for the LUN; this will always evaluate to false in most set-ups, since each path will look something like  `/var/lib/kubelet/plugins/kubernetes.io/iscsi/<prefix>`.  Changing `strings.HasPrefix` to `strings.Contains` appears to result in the correct behavior.

**Comment by rootfs** [comment]
@cdragga 
The problem is that the mount device shown in /proc/mounts are canonicalized, and thus when searching device prefix, iscsi volume failed to find a match.

If we can use `-c` mount option, this the device will show up in /proc/mounts. But this is not a reliable fix since there are probable mpio paths too.

**Comment by cdragga** [comment]
@rootfs 
If I'm reading the code correctly, the function doesn't look at the actual device that's backing the mount point; it looks at the mount path (i.e., the second token in /proc/mounts, rather than the first).  Thus, the change I proposed (HasPrefix -> Contains) appears to work with some very basic testing.  That said, I've not done anything with multipathing, so there may be something I'm missing; in addition, I suppose there's a chance that Contains may trigger false positives.

**Comment by rootfs** [comment]
@cdragga I see your point, yes that sounds right to me.

**Comment by rootfs** [comment]
@cdragga I think in this case, mpio device should work too (since the mount path constructed in the same way). I see you have yet another iscsi issue open, I am good with rescan.

Can you create a pr to fix them?

**Comment by cdragga** [comment]
@rootfs I should be able create a PR for this issue; the LUN rescan PR will probably get handled by someone else on my team.  Is the fix itself sufficient, or does it require tests?

**Comment by rootfs** [comment]
@cdragga thanks, the rescan fix doesn't have to unit test. The mount path fix needs also a unit test fix here
https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/iscsi/iscsi_util_test.go#L46
