### ISSUE TITLE
Kubelet needs an Object-Oriented Internal Pod Abstraction

### ISSUE THREAD

**Issue by dashpole** [kubernetes/kubernetes#41055]
cc @kubernetes/sig-node-feature-requests 

Structs are great to pass around when they are immutable, or remain constant.  However, if they dont remain constant, passing around structs can lead to a few problems:
- If copies of the struct are made, then these copies may become inconsistent.  It becomes difficult, if not impossible to reason about these various copies, and requires extensive knowledge of the system and each thread that uses a component.  This can lead to bugs where components with different copies of the struct act on outdated information, which can cause benign performance problems in the best case, and can cause safety bugs in the worst case.
- If no copies of the struct are made, but the object is shared by many threads, then you have classic concurrency problems.

There are a few different components in the kubelet that keep their own copy of pods:
- [Pod Manager](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/pod/pod_manager.go)
- [Status Manager](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/status/status_manager.go)
- [Volume Manager](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/volumemanager/cache/desired_state_of_world.go)
- [Runtime Cache](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/container/cache.go)

There are many examples where we pass around v1.Pod objects between threads.  The best example may be that [pod workers asynchronously perform updates on v1.Pod objects passed to them](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/pod_workers.go#L212).

It is important to note that what we currently have works.  However, it means that in order to make any changes to the kubelet, the author needs to be aware of all the complexities of all components that manage pod objects.  For example, if we want to check to see if a *v1.Pod is terminated, we need to first get it status from the status manager, rather than simply use pod.Status.  Only then can we correctly check to see if the pod is terminated.

I propose that we replace the use of *v1.Pod structs in the kubelet with an internal object.  Ideally, instead of exposing fields, like pod.Status, it will expose methods like pod.GetStatus(), and pod.SetStatus().  Instead of exposing pod.UID (and making consumers convert between static and mirror pods), expose pod.GetInternalUID() and pod.GetExternalUID().  This object should be thread safe, so that we can pass it around without fear of concurrency issues.

I also propose that we unify the various caches of pods that we keep in different components.  Ideally, we should have a single representation of each pod that can be viewed and modified concurrently by various internal components.

Initially, this could simply take the form of a unified API over the existing Managers and Caches, but it could ideally be refactored to eliminate the need to manage multiple copies of a pod.

**Comment by smarterclayton** [comment]
@caesarxuchao and @lavalamp re: internal versions of objects in the kubelet

**Comment by yujuhong** [comment]
I think having an internal pod object might be good in the long run, but perhaps not for the reasons stated in the post.

To give some background, most components in kubelet looks at the desired spec (i.e., the v1.Pod object) and the current state, and try to reconcile both.

The desired spec, the v1.Pod objects, are passed around everywhere but they should be read-only, so the concurrency is not much of an issue. Unfortunately, golang doesn't support passing read-only structs, so occasionally mutations do sneak in if PRs are not reviewed carefully. But I wouldn't say this is the biggest problem.

The components also check the status manager for the most up-to-date status, in addition to what it reconstructs from the disk itself. They usually don't care about the status in the current v1.Pod object that we get from the apiserver since it'd be stale.

I think what's really missing in the current architecture is the ability to express kubelet's *internal* desired spec and status (that do not already exist in the v1.Pod object) that can be shared among the components. E.g.,
  - The intent to evict a pod. This cannot be easily passed to components that only look at the v1.Pod spec.
  - The status of of volumes, whether they are mounted or not. This is necessary to decide whether kubelet should send the pod deletion request to the apiserver.

Another use of this internal pod object may be to claim ownership and prevent other components from performing the same operation, e.g., deleting a pod.

Of course, as long kubelet doesn't persist this new object, we'd need to ensure that it's ok to lose the information over restart or that the information can be recovered.

I'd like to see a more detailed proposal addressing the issues above with more analysis on pros and cons, if possible.

----------
Below are some minor points that you may have already known. Ignore them if that's the case :-)

> There are a few different components in the kubelet that keep their own copy of pods:
> 
> Pod Manager

Pod manager is just the de facto place for getting pod specs in kubelet. It's a pod cache for every one.
> Status Manager

Status manager doesn't actually cache pods...It's caching the "status" only so that it can talk to the apiserver to update the status.
> Volume Manager
> Runtime Cache

This is a historical artifact that we can probably get rid of.

> There are many examples where we pass around v1.Pod objects between threads. The best example may be that pod workers asynchronously perform updates on v1.Pod objects passed to them.

This is probably not the best example. Each worker is assigned a unique pod and on top of that, they don't mutate the pod object.

> Instead of exposing pod.UID (and making consumers convert between static and mirror pods), expose pod.GetInternalUID() and pod.GetExternalUID(). This object should be thread safe, so that we can pass it around without fear of concurrency issues.

This is good, but in my opinion, a very minor reason for doing this overhaul.

> I also propose that we unify the various caches of pods that we keep in different components. Ideally, we should have a single representation of each pod that can be viewed and modified concurrently by various internal components.

This is a bit unclear to me. What do the components cache, the spec or the actual state? Do they mutate it? Does it matter to keep a read-only copy of the spec?

**Comment by dashpole** [comment]
I completely agree with @yujuhong.  I think what I was attempting to point out is that we have a lot of assumptions about how we use different portions of a pod, and where the "correct" one is in the kubelet.  Pods in the pod manager are from the API server, but statuses from the kubelet are in the status manager, for example.  While I was initially coming from a safety perspective, I realize that our current architecture is safe, as long as contributors follow our assumptions and preserve our invariants.

An internal object will allow us to attach specific dependencies to a pod object, that currently require a reference to another component.  For example, the internal object could have a HasCgroups() method, which returns true if cgroups exist for a pod.  Underneath, this would call a method in the cgroup manager, but it would allow other components to examine the basic state of a pod without requiring a reference to the underlying component that actually tracks that information.

My long-term vision for this is that it could help reduce dependencies and allow us to compartmentalize the kubelet a bit more.  For example, if the status manager is simply an implementation detail of the Pod object, and no other components directly access it, then testing other components becomes simpler.  In addition, people trying to add code to the kubelet do not have to reason about components, like the status manager that are abstracted away.  Ideally, the folders: cm, container, dockershim (?), dockertools(?), gpu, kuberuntime, network, rkt, rktshim, status, and volumemanager would all eventually be hidden behind this pod API.  Then the kubelet only needs to reason about pods, making code and testing (with a mock pod) simpler.  Of course, this pushes testing to the pod level, but that is simpler than at the kubelet level.

**Comment by cmluciano** [comment]
@dashpole @vishh Should we close this in favor of something else?

**Comment by dashpole** [comment]
a lot has changed since this was open, and I think we are content with the current design for the time being.
