### ISSUE TITLE
kube-dns with preemptible nodes cause downtime

### ISSUE THREAD

**Issue by soudy** [kubernetes/kubernetes#41125]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): kube-dns preemptible

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug report

**Kubernetes version** (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"clean", BuildDate:"2016-12-14T00:57:05Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T04:52:34Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: GKE
- **OS** (e.g. from /etc/os-release): Google Container-VM Image
- **Kernel** (e.g. `uname -a`): Linux gke 4.4.21+ #1 SMP Thu Nov 10 02:50:15 PST 2016 x86_64 Intel(R) Xeon(R) CPU @ 2.30GHz GenuineIntel GNU/Linux
- **Install tools**: N.A
- **Others**: N.A

**What happened**:
We have our cluster setup with three preemptible nodes and two regular nodes. This means there's a big chance that `kube-dns` pods land on preemptible nodes. We have two `kube-dns` pods running. Yesterday, all three preemptible nodes fell away at the same time (because we did an upgrade recently they all had the same age), causing downtime because the `kube-dns` pods were on those nodes.

**What you expected to happen**:
I expect `kube-dns` and other important `kube-system` pods to always be on regular nodes and never on a preemptible. Right now our "fix" is to manually get them on a regular node, but that isn't very permanent.

**How to reproduce it** (as minimally and precisely as possible):
Set up a cluster with preemptible nodes and normal nodes, and watch as `kube-dns` get scheduled on preemptible nodes.

**Anything else we need to know**:
https://github.com/kubernetes/kubernetes/issues/40063 is somewhat related, however not exactly, since it doesn't take preemptible nodes in account.

**Comment by larsha** [comment]
Sounds like a job for Taints/Tolerations? Or am I missing something? `kube-system` deployments seems to have toleration key: `CriticalAddonsOnly` (at least on GKE). You can add a taint on nodes with that key and use NoSchedule or PreferNoSchedule to avoid scheduling on preemptible nodes.

**Comment by JeanMertz** [comment]
@larsha did you ever find a solution to this? I'm a colleague of @soudy and was just messing around with this again.

What we managed to do:

- add a `requiredDuringSchedulingIgnoredDuringExecution` node affinity block to the `kube-dns` deployment
- add another `toleration` to the existing `CriticalAddonsOnly` toleration, because our regular nodes have taints on them to only allow specific pods to be scheduled on them

The problem is that the node affinity addition is kept as is, but the added toleration is actually _removed_ from the deployment by Kubernetes itself if we edit it. This means we can't add the right toleration for the pods to be scheduled on our regular nodes which have taints on them.

Is this a known issue? I'm still going through past reported issues, but haven't found any mention of this yet.

**Comment by larsha** [comment]
Hi @JeanMertz, unfortunately I didn't find a solution to it. I just stopped using preemptibles for now. But I will follow the issue you referenced here.

**Comment by faun** [comment]
We were able to eliminate DNS downtime by tainting our preemptible nodes and adding a toleration for any preemtible workloads as described on [Stack Overflow](https://stackoverflow.com/a/51274434/807693).
