### ISSUE TITLE
Node does not reconnect to master after upgrading master

### ISSUE THREAD

**Issue by TamalSaha** [kubernetes/kubernetes#41126]
I am upgrading master of a cluster from 1.5.1 -> 15.2 using the upgrade.sh script.  After upgrade, it seems that nodes does not auto reconnect with master. If I restart the kubelet on nodes, they reconnect to master. I have not change anythign regarding --register-node (so it should be default true). My question is how do I get nodes to reconnect to new master without having to restart kubelet on every node?

**Comment by Random-Liu** [comment]
@TamalSaha kubelet does not register itself again unless you restart it.

IIUC, during master upgrade, we should:
* Preserve the etcd storage on master, so after master upgrade the previously registered nodes are still be in apiserver;
* Preserve the master ip, so that kubelet can still connect to the apiserver.

In that case, you don't necessarily need to restart your kubelet.
