### ISSUE TITLE
Anti-Affinity should be a default property of Statefulset

### ISSUE THREAD

**Issue by dhilipkumars** [kubernetes/kubernetes#41130]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):
---
Statefulset / petset
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Feature Request

**Kubernetes version** (use `kubectl version`): 
```
k version
Client Version: version.Info{Major:"1", Minor:"6+", GitVersion:"v1.6.0-alpha.0.4111+e7950e6f496159-dirty", GitCommit:"e7950e6f4961595e6c9df878bbc6dd520c792d03", GitTreeState:"dirty", BuildDate:"2017-01-28T06:09:31Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6+", GitVersion:"v1.6.0-alpha.0.4111+e7950e6f496159-dirty", GitCommit:"e7950e6f4961595e6c9df878bbc6dd520c792d03", GitTreeState:"dirty", BuildDate:"2017-02-08T05:49:00Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: dind-kubernetes
- **OS** (e.g. from /etc/os-release): Ubuntu 16.04.1 LTS
- **Kernel** (e.g. `uname -a`): 4.4.0-59-generic
- **Install tools**:dind
- **Others**:

**What happened**:
It makes sense to have default Anti-affinity property along with Statefulset,  The workloads deployed via SS are either going to be Master-Slave or DB/Cache Shards or quorum of self-cooperating members.  None of these workloads would want to be co-located in the same node/host.

If above is true then it appears that Anti-Affinity seems a necessity, unless we have some compelling usecases not to use Anti-affinity.  

**What you expected to happen**:  There is a reasonable spread by selector-spreading (priority), but that is not anti-affinity.  Like selector-spread is automatic for any object with a label selector, SS could also have anit-affinity and it will be one less thing to worry for the enduser when creating SS object. 

The only problem i see is when SS objects are created in dev env like minikube with strong affinity constrains. 

**How to reproduce it** (as minimally and precisely as possible):  Create a statefulset with more replicas than available nodes in the cluster. 

**Anything else we need to know**:  For starters i have  a working code that creates soft anti-affinity object for every pod that is created via SS controller.  I would love to raise a PR for review if this feature request sounds reasonable to the community.   The best thing to do would be to create soft affinity for dev-envs and hard affinity for larger cluster automatically. 

When an [SS object](https://github.com/kubernetes/kubernetes/files/760513/d1.txt) (without explicitly mentioning anti-affinity constrains) is created,  the controller adds a default (soft) antiaffinity term.   The SS attempts to create 8 replica on a 4 node K8s cluster. 

```
I0208 06:07:32.401800       1 interpod_affinity.go:237] DhilipLogs: CalculateInterPodAffinityPriority (pod.Name=d1-0, pod.kind=) result=[{172.17.0.4 0} {172.17.0.9 0} {172.17.0.7 0} {172.17.0.8 0}]
I0208 06:08:01.409961       1 interpod_affinity.go:237] DhilipLogs: CalculateInterPodAffinityPriority (pod.Name=d1-1, pod.kind=) result=[{172.17.0.4 10} {172.17.0.9 10} {172.17.0.7 10} {172.17.0.8 0}]
I0208 06:08:18.501457       1 interpod_affinity.go:237] DhilipLogs: CalculateInterPodAffinityPriority (pod.Name=d1-2, pod.kind=) result=[{172.17.0.9 0} {172.17.0.7 10} {172.17.0.8 0} {172.17.0.4 10}]
I0208 06:09:05.046998       1 interpod_affinity.go:237] DhilipLogs: CalculateInterPodAffinityPriority (pod.Name=d1-3, pod.kind=) result=[{172.17.0.8 0} {172.17.0.4 0} {172.17.0.9 0} {172.17.0.7 10}]
I0208 06:09:16.840119       1 interpod_affinity.go:237] DhilipLogs: CalculateInterPodAffinityPriority (pod.Name=d1-4, pod.kind=) result=[{172.17.0.7 0} {172.17.0.8 0} {172.17.0.4 0} {172.17.0.9 0}]
I0208 06:09:29.006456       1 interpod_affinity.go:237] DhilipLogs: CalculateInterPodAffinityPriority (pod.Name=d1-5, pod.kind=) result=[{172.17.0.4 5} {172.17.0.9 5} {172.17.0.7 5} {172.17.0.8 0}]
I0208 06:09:50.093591       1 interpod_affinity.go:237] DhilipLogs: CalculateInterPodAffinityPriority (pod.Name=d1-6, pod.kind=) result=[{172.17.0.4 5} {172.17.0.9 5} {172.17.0.7 0} {172.17.0.8 0}]
I0208 06:10:02.720656       1 interpod_affinity.go:237] DhilipLogs: CalculateInterPodAffinityPriority (pod.Name=d1-7, pod.kind=) result=[{172.17.0.7 0} {172.17.0.8 0} {172.17.0.4 0} {172.17.0.9 5}]
I0208 06:27:22.798799       1 interpod_affinity.go:237] DhilipLogs: CalculateInterPodAffinityPriority (pod.Name=d1-7, pod.kind=) result=[{172.17.0.9 5} {172.17.0.7 0} {172.17.0.8 0} {172.17.0.4 0}]
```
Thanks in Advance,
Dhilip
@erictune @kow3ns @smarterclayton @kargakis @bprashanth @enisoc @kubernetes/sig-apps-feature-requests

**Comment by resouer** [comment]
Just raise one thought, I think:

1. adding anti-affinity to StatefulApps is very simple
2. we can not assume  `None of these workloads would want to be co-located in the same node/host` unless user requires that

**Comment by kow3ns** [comment]
@dhilipkumars 
1. You can use parameterized helm charts to allow users to specify hard, soft, or no anti-affinity and to materialize the correct rule for them see [zk](https://github.com/kubernetes/charts/blob/master/incubator/zookeeper/templates/ss.yaml#L21-L53)
2. Are you claiming that we need to materialize affinity rules for users because it is too difficult or cumbersome? If not, what is problem addressed by this feature?
3. I don't think "The best thing to do would be to create soft affinity for dev-envs and hard affinity for larger cluster automatically." is a safe assumption to make, and there are definitely exceptions to "None of these workloads would want to be co-located in the same node/host". Also, how are you deciding what a "dev-env" versus a "larger cluster" is in your code?
4. For "When an SS object (without explicitly mentioning anti-affinity constrains) is created, the controller adds a default (soft) antiaffinity term.", how does a user specify they don't want anti-affinity?

**Comment by dhilipkumars** [comment]
@kow3ns @resouer Thanks for taking a look at the issue.
Imagine every time we open the refrigerator door we have to manually switch on the light inside it? Switching on the light is neither too difficult nor putting a switch there is cumbersome.  My argument is if something is too obvious the its worth making it automatic, if its going to save 30secs while writing a stateful yaml or a chart that contains SS then it could get really convenient.

What i would love to learn from the community is about those special applications/workloads that are 'stateful' in nature and prefer to be co-located in a node rather than be spread across the cluster.

Also there are valid but rare usecases where i dont want my refrigerator's light to glow when i open it,  but still the automatic light makes my life a lot easier. :-)

```
Also, how are you deciding what a "dev-env" versus a "larger cluster" is in your code?
```
currently it does not do that, i was thinking we could get a `node` count and compare it with the `replica` count in the SS object?

**Comment by smarterclayton** [comment]
We give users the pod template as the lowest level primitive.  We don't
impose complex defaulting rules on the pod template because it imposes
higher level constraints - other tools that might want to use that
assumption now have to behave differently.  Anything that exposes a pod
template needs to behave consistently, and for that reason alone we're
unlikely to implement this as defaults on the stateful set.

Saving 30s when writing a SS yaml directly is not a design goal we optimize
for - mostly because it's impossible to predict what people are doing in
their sets, and we have counterexamples to stateful set affinity.  We do
however believe that many people would want higher level tools to help them
specify it, and having higher level tools apply this as a default while
generating a SS is reasonable.

**Comment by kow3ns** [comment]
@dhilipkumars 
1. The number of nodes is not static. Heuristically determining behavior based on cluster size as a default is over-complicated and error prone. 
2. Defaulting to nothing seems safer and less surprising than materializing node anti-affinity unless the user specifies something else (e.g. rack, power-domain).
3. I don't see a clean way to specify that you don't want anti-affinity (i.e. now users would have to explicitly specify none).
4. imo the current behavior is easier for users to reason about than defaulting to an anti-affinity they didn't request.

**Comment by smarterclayton** [comment]
@dhilipkumars the easiest is when I'm running stateful processors that are worker queues for another stage in a pipeline.  Imagine a web service behind a load balancer that receives incoming log events and then sorts and indexes those locally before sending them on to a database.  That could easily be a stateful set if the worker needed persistent storage (needed to process large chunks of logs at once).  Nothing about that service requires anti-affinity, since it's stateful.  If it takes 2cpu and 4GB memory but with only 1M/s ingress, and my worker nodes are 16cpu 48GB machines with 10gbit ingress, there's no reason that I can't run 4-8 instances on a node.  Spreading is useful, but it's not required, and it's very easy for someone to ask for spreading.

@kow3ns's point 3 above is the best argument for adding this - if a user has to do something different for stateful sets to *not* get affinity, that is unique only to SS which means someone has to know that ahead of time.

**Comment by dhilipkumars** [comment]
@smarterclayton  Thanks for the usecase, as you have mentioned even for that workload the spread wouldn't hurt.   when i asked for _Could you site some examples...._ I was looking for a scenario where the user would want to purposely `disable` anti-affinity for that statefulset workload _(if it was offered by default)_.  

I completely agree with @kow3ns its not well thought idea to automatically choose between soft or hard anti-affinity based on the number of nodes available at the moment.  How about introducing an optional field in SS's spec for those extremely rare usecases which 'SHOULD not' have anit-affinity property by default?

```yaml
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: cache
spec:
  serviceName: "cache"
  defaultAntiAffinity: false
  replicas: 5
  template:
```

by default it provides a hard interpod topological anti-affinity but for development environment and other smaller cluster they could disable _(and override)_ it?

or even further something like below....
```
  defaultAntiAffinity: ["none" or "hostname" or "Availablity Zone" or "Cluster"(for federated SS)]?
```
but i believe _SelectorSpreadPriority_ already does a soft spread, 

IMHO i see 99/100 statefulset will have anti-affinity and largely benefit from this default property.  

If this is still not convincing im okay to close this issue.

**Comment by smarterclayton** [comment]
The alternative is just that we educate people how to require anti-affinity
and tell them that it works across all controller types in docs and in
tooling.

**Comment by dhilipkumars** [comment]
Closing the issue in favour for improved documentation.

**Comment by BeHiz** [comment]
Would love help on how to implement AntiAffinity on StatefulSet (no two nodes should run same statefulset service).
I could not find an example of where to put the AntiAffinity entries as part of StatefulSet tags

**Comment by gyliu513** [comment]
@BeHiz as we want to update the document, so you may want to update the document here https://github.com/kubernetes/kubernetes.github.io/blob/master/docs/concepts/workloads/controllers/statefulset.md

For an example of `Affinity`, please refer to https://github.com/kubernetes/kubernetes.github.io/blob/master/docs/concepts/configuration/assign-pod-node.md#inter-pod-affinity-and-anti-affinity-beta-feature
