### ISSUE TITLE
[Federation][kubefed] Should bind flags directly to a configuration type

### ISSUE THREAD

**Issue by marun** [kubernetes/kubernetes#41209]
``kubefed`` currently defines flags and then assigns the values from the flags to individual variables.  This makes maintenance and testing more difficult than necessary.

cc: @kubernetes/sig-federation-misc

**Comment by marun** [comment]
I'm working on this, and will be taking advantage of the change to refactor the tests to ease future maintenance.

**Comment by madhusudancs** [comment]
I think @irfanurrehman is also working on this. Please coordinate.

**Comment by madhusudancs** [comment]
cc @kubernetes/sig-federation-bugs

**Comment by marun** [comment]
Why is he working on something without filing an issue first?  I'm responding to your suggestion to implement better testing and flag binding was the obvious place to start.

**Comment by madhusudancs** [comment]
This is an unreasonable expectation. People can't be expected to file issues for 10 line code refactors/code health changes. Whether this particular change is exactly 10 lines is a topic for bike shedding, but the argument still holds. Expecting people to file issues for such things demotivates most people from doing any code health improvements and thus results in bad code overall. We get a good number of code health improvements, comment fixes from new contributors and asking them to go file an issue before sending those improvements just discourages them from making those contributions.

In addition, I haven't seen this requirement in any project I have worked on, open source or otherwise. Do we have this in other SIGs? I am not saying we should perpetuate the mistake that others make, just because others are doing it anyway. But IMO, there is a strong reason why that's not done. It is a huge penalty on productivity.

Many of us are already trying to grapple with the huge influx of emails/notifications, untriaged issues and sometimes forgotten ones. Requiring this would be an unnecessary burden on top of that.

There is no council of elders yet. So I am escalating this to some senior people on the project for their opinions: @bgrant0607 @thockin @smarterclayton @jbeda @brendandburns 

Happy to be convinced otherwise.

**Comment by marun** [comment]
@madhusudancs Your response suggests that you're taking my comment to have far more gravity than I intended.  I didn't realize that advocating for publicizing intent would be controversial.  I agree that it shouldn't be required, and I'm sorry if I gave you that impression.

In development communities that I've been a part of, I have found that publicizing intent before starting implementation of anything non-trivial aids in coordinating effort and reduces the potential for duplication of effort.  Enabling input from stakeholders as early as possible can help to ensure good outcomes.  That's all I was trying to convey.

**Comment by madhusudancs** [comment]
@marun and I have taken this conversation offline. We will post an update.

**Comment by irfanurrehman** [comment]
@marun I have seen ur PR, it looks ok to me.. and its not that big to cause any reasonable code conflict, so lets go ahead with the process of getting it in, meanwhile lets be in sync for future PRs.. :)

**Comment by perotinus** [comment]
@marun Was this issue fixed by your PR? Is there follow up work that needs to be done?

**Comment by madhusudancs** [comment]
@perotinus yes, this is done now.
