### ISSUE TITLE
Add Binder to HTTPExtender of scheduler

### ISSUE THREAD

**Issue by k82cn** [kubernetes/kubernetes#41235]
Currently, the extender allows an external process to filter and prioritize nodes when scheduling a pod.  But the process may also need to do preparation before binding Pod to host; for example, in kube-mesos, the k8sm-scheduler will ask Mesos to start kubelet before binding the Pod to host.

/cc @kubernetes/sig-scheduling-misc

**Comment by k82cn** [comment]
cc @davidopp , @timothysc

**Comment by davidopp** [comment]
At some point (in terms of increased functionality) the scheduler extender becomes the wrong approach and writing a custom scheduler is better. I wonder if this request crosses that point...

**Comment by k82cn** [comment]
The purpose of scheduler extender is to re-use k8s-scheduler's policy, e.g. PodAffinity. If writing a custom scheduler, it'll import scheduler related codes which introduces code level dependency.

**Comment by davidopp** [comment]
I think the question is whether we want to expand the scheduler API beyond just asking the API server to bind pods to nodes.

**Comment by davidopp** [comment]
(What kube-mesos is doing sounds a little odd...)

**Comment by k82cn** [comment]
> I think the question is whether we want to expand the scheduler API beyond just asking the API server to bind pods to nodes.

The original idea was from kube-mesos; the kubelet is started on-demand. So before binding Pod to host, k8sm-scheduler need to make sure kubelet is started, and then, bind Pod to the host (by calling API); otherwise, no kubelet retrieves the Pod.

Honestly, did not make up other scenario right now; but `Filter`/`Prioritize`/`Bind` are the major actions of scheduler and http extender is configurable (no impact to others). And there's an interface `Binder` in `scheduler.go`, so I think we can implement a http extender for Binder.

**Comment by ravigadde** [comment]
@k82cn are you thinking of an interface similar to the one in #11470?

**Comment by k82cn** [comment]
@ravigadde , yes, similar requirements on `Bind` :).

**Comment by davidopp** [comment]
Can you explain at a high level what problem you're trying to solve? I haven't looked at the Kubernetes-on-Mesos code in a very long time, and don't remember how it works. Is the problem you're trying to solve how to get Kubernetes-on-Mesos scheduler to work with scheduler extender approach?

**Comment by k82cn** [comment]
This relates to the project in kube-mesos (https://github.com/kubernetes-incubator/kube-mesos-framework/projects/1 ).

Currently, kube-mesos modified Kubernetes's code to make it running on Mesos, e.g. k8sm-controller-manager & kubelet; and it also write a custom scheduler. It has two issues
1. The custom scheduler missed scheduling policy, e.g. affinity
1. Modified codes introduce dependency, e.g. https://github.com/kubernetes-incubator/kube-mesos-framework/issues?q=is%3Aissue+is%3Aopen+label%3Apriority%2Fp2

So I'm going to refactor kube-mesos: make Mesos as resource provider only and using Kubernetes external APIs as much as possible, e.g. client-go, scheduler http extender, cloudprovider extention (later version). It'll make integration simpler and more stable.

Back to this issue, I'd like to re-use scheduler's policy: one option is to use HTTP extender (need Bind interface to start kubelet on-demand), and another option is to import related code.

**Comment by davidopp** [comment]
Since the extender(s) [run(s)](https://github.com/kubernetes/kubernetes/blob/3dbbd0bdf44cb07fdde85aa392adf99ea7e95939/plugin/pkg/scheduler/generic_scheduler.go#L201) after the default scheduler's predicate functions, can you get the same effect as a Bind operation by having scheduler extender filter the list of nodes down to just one node (i.e. return just one node in the list)?

**Comment by ravigadde** [comment]
This is the recipe as of now :) The drawback is that it requires the extender to import the priority functions from k8s scheduler (selector, replica spreading etc). A separate Bind call or a modified Prioritize interface that can just return one node should solve the issue.

**Comment by davidopp** [comment]
> The drawback is that it requires the extender to import the priority functions from k8s scheduler (service, replica spreading etc).

I'm confused.

IIUC, the Bind operation that is being requested, would tell the API server "bind the pod to node X."

How is that different from extender returning a single-node filtered list (and some random number for the priority)?

It seems that how the extender decides which node X to pick is orthogonal to whether there is a Bind operation or it just returns a single-node list -- either way it will need to import scheduler code if it wants to use the same policies as the scheduler.

Maybe I am misunderstanding some part of this.

**Comment by ravigadde** [comment]
Lets take an example, perhaps that will help clear up things.

1) k8s scheduler picks 5 nodes - n1, n2, n3, n4, n5

**Option 1 (current)**
2) Filter call to extender
3a) extender runs its predicates and picks n2, n3, n4
3b) extender runs its priority functions and k8s priority functions (that are imported) and scores 100, 50, 40
3c) extender picks n2 (creates an alloc against n2) and returns that in the filter response
4) there is only n2 that goes through k8s scheduler priority functions, so it gets picked. k8s scheduler binds pod to n2.

**Drawback**
Extender needs to import k8s priority functions

**Option 2**
2) Filter call to extender
3) extender runs its predicates and returns n2, n3, n4
4) k8s scheduler scores n2, n3, n4
5) Prioritize call to extender with n2, n3, n4
6) extender scores n2, n3, n4 and returns scores
7) k8s scheduler accumulates the scores and picks n2
8) Bind call to extender with n2
9) extender reserves resources (alloc) against n2
10) k8s scheduler binds pod to n2 with apiserver

**Option 3**
2-4) Same as Option 2
5) Prioritize call to extender with n2, n3, n4 and their scores computed by k8s scheduler
6) extender scores n2, n3, n4 and adds up scores
7) extender returns n2 (and creates alloc against n2) to k8s scheduler
8) k8s scheduler binds pod to n2 

**Drawback**
Doesn't work with multiple extenders. I dont know if multiple extenders is a real use case though.

**Comment by davidopp** [comment]
Oh sorry, I mis-read #11470. I thought the Bind you wanted was from extender to API server, but you want the other way around. So the Bind you have in mind is a message from API server to extender saying "node X has been chosen for pod P"? And the API server promises not to actually bind the pod to the node (i.e. fill in NodeName) until the scheduler extender says it is OK to do so? What does step 9 in Option 2 actually do in terms of existing Kubernetes types?

@k82cn is this the meaning of the "Bind" operation you had in mind? I just want to be sure we're all talking about the same thing...

If what you're trying to do is to insert an arbitrary operation between node being chosen and pod being started on the node, I wonder if initializers (kubernetes/community#132) would solve the problem. I think we had been envisioning scheduler as always being the last initializer in the chain, but maybe somehow initializers could also run after the scheduler if we change the way API server handles "bind" subresource so it doesn't immediately write NodeName, but instead some really-truly-the-last-initializer-to-run writes NodeName, thereby allowing some other logic to run between the binding being decided and the kubelet starting the pod.

**Comment by k82cn** [comment]
@davidopp , thanks very much; I think initializers will solve the problem: in kube-mesos-initializer, it'll ask Mesos to launch task (including the kubelet for the first time); and then, the kubelet can start the Pod accordingly.
As you said, if it's not the latest initializer and the following initializers failed, it need a notification to let Mesos kill the task. I think we can discuss those race cases at https://github.com/kubernetes/community/pull/132 if it's not covered.

@ravigadde , if no more comments, I'm going to close this one :).

**Comment by ravigadde** [comment]
@davidopp the Bind call can originate from the scheduler too, before it binds a pod with the apiserver. If the bind call  to apiserver fails subsequently, pod is rescheduled and extender can release the stale alloc.

If the Bind originates from apiserver initializer, there is a window where extender is scheduling with stale resource usage information.

**Comment by k82cn** [comment]
> @davidopp the Bind call can originate from the scheduler too, before it binds a pod with the apiserver. If the bind call to apiserver fails subsequently, pod is rescheduled and extender can release the stale alloc.

Similar issue to kube-mesos; but I think we can discuss in kubernetes/community#132 for this case, e.g. add a notification to extender on finial result (maybe already covered).

**Comment by davidopp** [comment]
We discussed this issue a bit in the sig-scheduling meeting today. IIUC the argument was that although initializer approach should be able to handle the "run code between scheduler choosing node and kubelet starting pod" (e.g. the Mesos use case), it doesn't handle (or would not easily handle) the (separate) feature request for the scheduler extender to find out which node was chosen before the binding happens. Unless I misunderstood, the motivation for this second use case is so the extender can bind the pod to the correct node in its own local state before the binding happens in th API server (otherwise there is a race condition if it waits to find out through watch).

This second use case necessitates adding a third stage to the communication between scheduler (S) and extender (E), i.e.
1. S->E: nodes meeting scheduler's predicate functions
2. E->S: nodes from (1) that also meet extender's predicate functions
3. S->E: nodes from (2) together with their scores based on scheduler's priority functions
4. E->S: nodes from (2) together with their scores based on extender's priority functions
5. S->E: name of node that was chosen
6. E->S: ACK

(5 and 6 are the new third stage)

Between 5 and 6 the scheduler extender can bind the pod to the node in its local state (what @ravigadde was calling "creating an alloc").

And it turns out that this can also solve the Mesos problem, because between 5 and 6 the extender could launch the task. In that case you wouldn't need the initializer.

Someone from Ravi's company is going to prototype this idea (add the new third phase) so we can see how complicated it is. But it might not be too bad and would solve both problems.

We discussed whether we want to continue to support multiple extenders attached to the same scheduler, and I think that since we currently do, we should continue to do so. (Ceasing to do so would arguably be a breaking change to the existing functionality, and anyway I don't think there is anything about this idea that limits it to one extender, you can just call them in series as today.)

**Comment by k82cn** [comment]
>  it doesn't handle (or would not easily handle) the (separate) feature request for the scheduler extender to find out which node was chosen before the binding happens. 

So scheduler will also send a node candidates list to extender? and extender will bind it based on it local state?

**Comment by davidopp** [comment]
Both use cases are addressed by the 6-step process in my previous comment. For Mesos use case, scheduler starts task between step 5 and 6. For "local state" use case the extender records the binding in its local state between step 5 and 6. Does that make sense?

**Comment by k82cn** [comment]
That's great :). It also make kube-mesos simpler: less code on race condition handling.

**Comment by timothysc** [comment]
I just want to state on this issue, as I've mentioned on the SIG calls.  I'm firmly in the camp where I believe that it should be easy to fork and rebase your own scheduler and that maintaining the extender in the long term is actually a liability.  

By compartmentalizing the scheduler and cleaning up the dependancies we can pretty easily make it where folks could write their own custom logic, and rebasing from the master should be a straight forward process.  In the long haul, I wanted to slowly push the scheduler into a set of libraries whose algorithm is a pipeline of connected concepts.  This is often done in signals analysis, graphics, etc. and I think can directly apply. 

We probably won't get there anytime soon, but I will absolutely continue to push towards this goal.  Otherwise I fear will end up with brittleness, and intractability.

**Comment by ravigadde** [comment]
PR submitted using #41447

**Comment by ravigadde** [comment]
@k82cn Would really appreciate if you can give this a spin.

**Comment by cmluciano** [comment]
Is this still an issue?

**Comment by ravigadde** [comment]
Yes, #44883 is in final stages of approval. I can close this issue one #44883 is merged.
