### ISSUE TITLE
Arbitrary topology through the system

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#41442]
This topic has come up many times lately, so I am writing down my thoughts.

Assertion: topology is arbitrary.  Today we sort of capture "region" and "zone" as special things, which we decorate as labels on a few resource kinds.  That works for AWS and GCE and other clouds, but a) falls down in case of on-premise environments and b) isn't used pervasively (e.g. https://github.com/kubernetes/kubernetes/issues/41394).  You can easily imagine an on-prem installation that wants to track things per-rack or per-generator or who knows what.

In fact, if you squint, we have a third level of topology - "hostname" - which is used by things like DaemonSet.

What is starting to form is an idea of a "per-topological-value" aspect to many APIs.  What if I could say "I want 3 replicas per zone" or "I want 1 replica per rack" or "find zone-local backends for service X"?

Obviously questions remain.  What sort of slush is there at the edges?  Do things like rolling updates apply per-topo or across all topos? are updates per-topo or cross-sectional?  Are within-topo Services hard requests or soft-requests?  If this extends to Services (https://github.com/kubernetes/kubernetes/pull/28637#discussion_r94002246), does it mean "try local, then go wider" or is it a hard constraint?  Naively these seem exact, not a min or max or suggestion.  It's a somewhat simplistic model, but it seems to be a reasonable starting place.  Perhaps eventually it grows into weights or scalars per topo, but not yet.

This is very familiar to the federation design, and to the taints/tolerations design, too.  I am tired of seeing this pattern pop up and I think it might be worth thinking about how to solve it more holistically.  I do not have a more concrete proposal at this time.

@davidopp @justinsb @kubernetes/sig-federation-misc

**Comment by smarterclayton** [comment]
Topology is arbitrary, based on what I see in existing production deployments and what we have enabled and encouraged via liberal use of labels.  Rack / bar / switch are already out there.

I will say that without topo-awareness on scale down or due to replacement complex topology is academic (the desired constraints are violated too easily).  Some form of convergence is more important to the people I talk to than adding more tools (now)

**Comment by thockin** [comment]
Obviously if we had a concept of topology, then ~ everything would be
impacted - scale up, scale down, rolling updates, services, etc.

I did not file this issue lightly.

**Comment by davidopp** [comment]
There are two types of topological requests that are relevant
* **Type 1:** The user selects a level of the topology hierarchy and one of the topology graph nodes in that level of the hierarchy. The user's request is of the form "put this instance onto a machine that is in topology graph node X." This is exemplified by our current "node affinity/anti-affinity" feature (e.g. "schedule this pod onto a machine that is in zone Y"). 
* **Type 2:** The user selects a level of the topology hierarchy and the *system* selects the topology graph node(s) in that level of the hierarchy. The user's request is of the form "put these instances onto machines that are in the same (or different) topology graph nodes of topology hierarchy level Z." This is exemplified by our current "pod affinity/anti-affinity" feature (e.g. schedule these pods into the same zone, or spread these pods across machines).

Being able to specify "how hard to try" (predicate vs. priority function, and weighting for priority function) can also be useful, but doesn't really change anything. Also, the topology doesn't have to be hierarchical, but it's easier to talk about that way.

On the "advertisement" side, in both Types, labels suffice for specifying what topology node(s) a machine is in. On the query/rule/request side, for Type 1 you want something akin to labelSelector (we have a NodeSelector type for that in node affinity/anti-affinity, which is a generalization of labelSelector), and for Type 2 you just need to specify a key that defines the level of the topology hierarchy (machines with the same value of the topology key as one another are considered to be in the same node of that level of the topology hierarchy, and nodes with different values are considered to be in different nodes of that level of the topology hierarchy; an example topology key would be `failure-domain.beta.kubernetes.io/zone`). 

Using labels in this way is very flexible. The system doesn't know any semantics about these labels, or how different topologies might be related (e.g. that different zones always implies different nodes), but I would argue this is a feature, not a bug, because we can't foresee what everyone's topology will look like (and who's to say some weird setup might not actually have a node live in more than one zone, based on that provider's definition of zone--the topology graph might not be a tree).

Although I love grand unifications, the best starting point for thinking about this general problem might be to start with the specific use cases/deficiencies people see, and seeing if we can address them without too much work. I think it's also helpful to think about whether each one is in Type 1 or Type 2.

Here's the list I'm aware of right now, based primarily on your message:
* **How do we extend topology requests to specifying update patterns, not just pod placement**? #41394 requests "update by failure domain" (take down all instances in a whole failure domain at a time) - this is arguably Type 2 (though a different use of the concept, since it's not about placing pods). Your questions "Do things like rolling updates apply per-topo or across all topos?" and "are updates per-topo or cross-sectional?" I believe can be considered part of this issue (what rules do we want people to be able to specify for updating by failure domain).
* **How do we unify node affinity/anti-affinity at the federation level and per-cluster level** kubernetes/community#344 proposes a "ClusterSelector" annotation for (at least some of the) objects in the federation control plane, that controls which underlying cluster(s) the corresponding "real" objects get created in. They propose to reuse the main underlying type (NodeSelector) that we use in node affinity/anti-affinity (because this is Type 1). They are going to use this for placing all kinds of objects, not just pods. I think the only way they could avoid using annotations is if we had every kind (for which it made sense) have a NodeAffinity (or NodeSelector) field; today only PodSpec does (well, it will in 1.6, since we're moving it into a field of PodSpec).
* **What kind of "N" values do we want in rules**: We don't currently have any concept of N for either Type 1 or Type 2. #40358 proposes to add an N with the semantics of "max of N per" but you have pointed out that people might also want other things like min, exactly, and approximately ("slush at the edges" as you put it). I think if we made the N associated with anti-affinity be interpreted as "max per" (as in that issue), and the N associated with affinity be interpreted as "min per," and we allow both hard and "preference" versions of the rules (with corresponding weights), then we might be able to cover all the use cases you alluded to. (I think you could specify a range by using an affinity w/ min-per and anti-affinity w/ max-per in combination?)
* **Weighting** ("weights or scalars per topo" in your message): The approach we took in node and pod affinity/anti-affinity is that each rule can be "hard" or "soft" and the latter have weights attached to them. So although it's not literally a "weight per topo" it is a weight per (soft) rule, and you can specify one rule for each topo you are interested in and specify multiple rules, hence it is effectively the same thing as what you want.
* **How do we extend topology requests to Services (select a subset of endpoints based on topology)?** Your https://github.com/kubernetes/kubernetes/pull/28637#discussion_r94002246 "locality" field looks at first like Type 2 since you just specify a topology key, but it is actually Type 1 because you specify a topology key *and* a pod, hence you are specifying both the key and the value (the value is simply the value of that key for the node where that pod is running). The "try local, then go wider" concept could perhaps be achieved most simply by specifying multiple rules, with weights that decrease as the topology domain gets larger. (The total "score" for a node is the sum of the weights of the rules that are satisfied.)

Are there others?

I guess I could have put this in a doc, but it's not a design of anything; at best it's a taxonomy of sorts.

[BTW #41394 also requests a more direct way to specify packing/spreading rules in Deployment ("Making pods spread across failure domains on a best effort basis or as a hard requirement should be as simple as flipping a switch in Deployment. We shouldnt have to write a pod anti affinity rule to achieve this.") I'm not sure this will be as necessary once affinity becomes part of the PodSpec (which it will in 1.6); today it is an annotation on the pod, which I agree is awkward. But in any event this isn't asking for a fundamentally new feature, just syntactic sugar.]

**Comment by smarterclayton** [comment]
I'm not disagreeing, I was trying to describe the things I'm hearing
that matter the most to people running real workloads today:

1. What do you mean, scaling down means my app is no longer properly
spread across failure zones?!
2. What do you mean, updates cause my app to be concentrated in one
failure domain?!
3. Why is my app still not properly balanced 3 days after I deployed?!
4. What do you mean, my stateful set doesn't spread by default across
the failure zones I defined?!

Without those, better ways of describing topology are academic because
topology is just an aspiration.  I'm not critiquing the desire, just
trying to focus on a timeframe for making our existing strategy whole.

**Comment by davidopp** [comment]
> What do you mean, scaling down means my app is no longer properly spread across failure zones?!

This is related to #4301. We don't need a new notion of topology or new topology rules, but we do need the scale-down to take into account the existing rules.

> What do you mean, updates cause my app to be concentrated in one failure domain?!

This shouldn't happen. If an update causes a pod to reschedule, the replacement pod goes through the scheduler which should take the spreading requirements into account when placing the new pod.

> Why is my app still not properly balanced 3 days after I deployed?!

The rescheduler should address this -- if the app cannot spread well on initial creation because of load imbalance across failure domains, but later some of that load terminates, the rescheduler can give the app a better spreading.

> What do you mean, my stateful set doesn't spread by default across the failure zones I defined?!

In theory the scheduler should be spreading stateful apps across failure zones on a best-effort basis, but we've talked about having the StatefulSet controller add an explicit pod anti-affinity rule to the pods it creates in order to force the spreading more explicitly.

> Without those, better ways of describing topology are academic because topology is just an aspiration. 

My argument is that we don't need better ways of describing topology; what we have is good enough. We just need to add it to more types (e.g. services and federated control plane objects, maybe also PVs), add it to more operations (e.g. scale-down and update, not just initial pod placement), and make it a little more flexible (e.g. max-N and min-N).

**Comment by smarterclayton** [comment]
On Wed, Feb 15, 2017 at 3:21 PM, David Oppenheimer <notifications@github.com
> wrote:

> What do you mean, scaling down means my app is no longer properly spread
> across failure zones?!
>
> This is related to #4301
> <https://github.com/kubernetes/kubernetes/issues/4301>. We don't need a
> new notion of topology or new topology rules, but we do need the scale-down
> to take into account the existing rules.
>
For every controller, first-party or not.  Every third party controller /
operator / babysitter for stateful sets needs some variant of this.
Stateful sets in practice need to rebalance before a member is evicted or
very shortly after, where even with disruption budget and scheduler
constraints there still needs to be additional restraints that may only be
known to the running software.


> What do you mean, updates cause my app to be concentrated in one failure
> domain?!
>
> This shouldn't happen. If an update causes a pod to reschedule, the
> replacement pod goes through the scheduler which should take the spreading
> requirements into account when placing the new pod.
>

If the above is true, yes.


> Why is my app still not properly balanced 3 days after I deployed?!
>
> The rescheduler should address this -- if the app cannot spread well on
> initial creation because of load imbalance across failure domains, but
> later some of that load terminates, the rescheduler can give the app a
> better spreading.
>

Yes.


> What do you mean, my stateful set doesn't spread by default across the
> failure zones I defined?!
>
> In theory the scheduler should be spreading stateful apps across failure
> zones on a best-effort basis, but we've talked about having the StatefulSet
> controller add an explicit pod anti-affinity rule to the pods it creates in
> order to force the spreading more explicitly.
>

I was actually referring more to the volume spreading issue that was just
recently identified, caused by having lots of hard coded code for
controllers in places that doesn't take that into account.


> Without those, better ways of describing topology are academic because
> topology is just an aspiration.
>
> My argument is that we don't need better ways of describing topology; what
> we have is good enough. We just need to add it to more types (e.g. services
> and federated control plane objects, maybe also PVs), add it to more
> operations (e.g. scale-down and update, not just initial pod placement),
> and make it a little more flexible (e.g. max-N and min-N).
>
Requirements I've heard apply to access control and quota on tolerations
and subdivision by region / zone / other topology.  That's something today
that we can only approximate by combining per namespace quota/limitrange
and per namespace label selectors.  I do think we're getting closer to
wanting a TopologyPolicy.

**Comment by davidopp** [comment]
> I was actually referring more to the volume spreading issue that was just recently identified, caused by having lots of hard coded code for controllers in places that doesn't take that into account.

Yeah, I have seen bits and pieces of that; it would be good if someone could link all the relevant discussions to this issue. I know there has been some discussion of integrating PVClaim scheduling with pod scheduling, at least for the local PV case.

> Requirements I've heard apply to access control and quota on tolerations

and we'll need it for priority too once we have it....

> and subdivision by region / zone / other topology. 

Can you expand on this? Do you mean people wan access control and quota not just on namespace granularity but also on topology granularity? What specifically does that look like -- something like "X amount of RAM quota in zone A, Y amount in zone B, ..."? One vaguely related thing is that you can use taints and tolerations to implement "dedicated nodes" where you limit who can access particular subsets of nodes.

**Comment by quinton-hoole** [comment]
cc @kubernetes/sig-federation-misc 
@thockin thanks for calling this out - I agree that it's really worthwhile figuring out.
I largely agree with most of what @davidopp says.
Would it perhaps be better to move this to a Google Doc to better facilitate feedback and addressing thereof?  I can see this issue turning into a monster megathread pretty soon :-)

**Comment by davidopp** [comment]
I can put it into a Google Doc by Monday.

**Comment by kow3ns** [comment]
I think #41598 summarizes the magic we currently do to spread StatefulSet across zones by round robin provisioning storage.

**Comment by MikeSpreitzer** [comment]
I have a slightly different take on this than @davidopp , who I would characterize as focusing on operations rather than data.  I favor first focusing on the model that the user presents.  The use cases are not single pods but larger things (e.g., replica set, stateful set) that can be annotated with the desired topological constraints.  I would focus first on characterizing those constraints, with the expectation that all operations on those larger things respect the topological constraints.

Following is a taxonomy that makes sense to me, for constraints put on a larger thing X.

Type A: collocation or anti-collocation with a node in the topology graph.

Type B: mutual collocation or anti-collocation at topology hierarchy level L among the pods of X.  Possible more specific versions of those two are: concentrate placement on some child of node N, or spread as evenly as possible among at least K children of node N (there is a bit of tension between "as evenly as possible" and "at least", and what I mean here is that the numbers on individual nodes are no higher than would exist if exactly K children are used).

Both types can come in hard and soft flavors.  The type B anti-collocation can be weighted.

Note that I use the term "collocation" rather than "affinity" because I think "affinity" is a broader concept --- e.g., it can include network affinity as well as location affinity.

Note that the "spread evenly" constraint is different from a "max-number" constraint, in that when the size of X changes a spread-evenly constraint does not have to be updated to maintain what the user really means, while the number in a max-number constrain has to be updated.  Note also that spread-evenly prevents a (0,2,2) distribution of four pods among three nodes, while a max-number constraint can not.

**Comment by davidopp** [comment]
> The use cases are not single pods but larger things (e.g., replica set, stateful set) that can be annotated with the desired topological constraints.

I think these are isomorphic. Giving a topological constraint to a ReplicaSet is equivalent to giving topological constraints to each of the corresponding pods of that ReplicaSet relative to one another. (For example, "place all of the pods of ReplicaSet X in the same zone" is equivalent to giving the ReplicaSet's pod template a label Z and a constraint "the pod can only run in a zone with another pod with label Z." The first approach is surely more "natural" to express, but in a system like Kubernetes where collections are defined implicitly, bottom-up, based on labels and label selectors, rather than top-down, we felt that the second approach would work better.

BTW I believe both you Type A and Type B can be represented using our existing affinity rules (except for the notion of a K, which we don't have yet) and correspond roughly to my Type 1 and Type 2. Your point about using the term "collocation" vs. "affinity" seems like a good observation and might reduce confusion.

We do have "spread evenly" today, with "soft" pod anti-affinity. The original idea for adding "max-number" (which we didn't do yet) would be that it would only apply to "hard" pod anti-affinity though I guess there isn't any reason we can't also do it for "soft."

**Comment by davidopp** [comment]
> in a system like Kubernetes where collections are defined implicitly, bottom-up, based on labels and label selectors, rather than top-down, we felt that the second approach would work better.

Actually it's that PLUS the fact that our current scheduler schedules one pod at a time. If we had gang scheduling, then putting topology constraints on the collection might be a better approach (though effectively we do already put topology constraints on the collection since the controller has a "pod template" and that's where we put the topology constraints).

**Comment by davidopp** [comment]
I'm not sure a doc is necessarily better than an issue, but I've created a doc [here](https://docs.google.com/a/google.com/document/d/1nZ6Vnjpn9WtwReqGImEOKQ4oF1WoRWeBGiIZ5q-WgsI/edit?usp=sharing) and shared it with kubernetes-dev. The doc is an extraction of the ideas in this thread into a background/problem statement section and a use cases/proposal section.

**Comment by bgrant0607** [comment]
See also #4301

**Comment by thockin** [comment]
I totally lost track of this topic.  It has come up again in the form of local volumes (@msau42) and has been cited repeatedly as a pain point for multi-zone clusters (cross-zone network traffic being charged, while in-zone is not).

We’ve seen a number of requests for “per-node services” - when I ask for a Service IP, I always get the service on my local node.  This could be implemented by yet another Service “type” which allocates a node-private IP (e.g. link local).  That would solve this particular problem, but isn't generic.  At least the semantic is easy - you ALWAYS want your local instance.

Storage is using the NodeAffinity structure to say that a volume has a selector of which nodes it is available from.  This is not enough for services, or rather is too much.  What services really want is a way to say "select a backend with the same value for topology level X", for example "select a backend with the same value for hostname".  The scheduler/rescheduler stack isn't quite ready to make guarantees about availability, but DaemonSet seems workable for node-level guarantees.  For Services maybe we could simply say:

```
spec:
  topologyMatch: [ "kubernetes.io/hostname" ] # while this is a list, only one record is supported, and only hostname is known to work.
```

Kube-proxy would need to know the value of that label for each Endpoint.  We know the NodeName for endpoints (optionally but we populate it), so we could watch Nodes and cache topology-related labels (or all labels, since we can't really know which).  We would then only use Endpoints that match.  It turns out this is exactly what I proposed exactly 1 year ago yesterday.  Sigh.  I guess it's a good thing that a year later, the idea still holds?  https://github.com/kubernetes/kubernetes/pull/28637#discussion_r94002246

This seems like it would be a fun project, anyway.

If this worked out, we could expand the list to multiple, arbitrary keys and the resulting rules would be more complex.  I can see how to do it for iptables kube-proxy, but the simple behavior would still be "hard" - if there is any endpoint in my own zone, use it, even if there are 100 available in other zones.  THEN we could start to explore weights and probabilities maybe, which really wants a table of zone-to-zone cost per topology level (or maybe not, if it is good enough).  If we want to consider load or latency, then this becomes more istio-like, and is a much larger conversation.  Maybe at the Services level it can stay simple.

@bowei for a fun starter project for someone :)

**Comment by davidopp** [comment]
The simple version of what you described (one-element list) is essentially the same semantics as `topologyKey` that we use in pod affinity/anti-affinity, though it's a string rather than a one-element list. The [comment](https://github.com/kubernetes/api/blob/master/core/v1/types.go#L2609) puts it this way: "[...] co-located is defined as running on a node whose value of the label with key `topologyKey` matches that of any node on which a pod of the set of pods is running"

We should probably try to make the API service topology match the API for pod scheduling topology, especially if we plan to expand either of them later to the more complex form you described.

> DaemonSet seems workable for node-level guarantees

Especially with priority/preemption.

**Comment by m1093782566** [comment]
@thockin 

I like the idea of #28637 (comment) and are happy to implement it.

Actually, I am writing a proposal about "topology aware routing of services" and will publish it soon.

**Comment by m1093782566** [comment]
There is the proposal "topology aware routing of services", which is intended to fix the "only-local" service, please see https://github.com/kubernetes/community/pull/1551

**Comment by m1093782566** [comment]
IIUC, the array `topologyMatch` described above is used to guarantee ability? For example, 

`topologyMatch: [ "kubernetes.io/hostname", "failure-domain.beta.kubernetes.io/zone" ]`

if hostname mismatch, then it will try to find the endpoints in the same zone?

BTW, From the review of scalability, we should avoid letting **kube-proxy** watching ALL nodes otherwise it will increase O(N nodes) long polling connections to API Server.

**Comment by thockin** [comment]
I will read your proposal now.  I was thinking of topologyMatch as a priority-ordered list of affinity zones, yes.  That said, David is right that consistency is important.  Pod affinity seems to run with "preferred" and "required" (aka soft and hard), rather than a list.  If that API is working well for users (is it?), perhaps that is the pattern to follow.  Either "Prefer this topo key, but fall back on any endpoint" or "Match this topo key, and fail otherwise".

It still only allows hard preference, so we should think about whether we would want to offer something like weighted probability or even more dynamic feedback-based (e.g. near-realtime cost), and what that might do to the API.

**Comment by davidopp** [comment]
It might be good enough (in terms of staying consistent) to just use the `topologyKey` concept and terminology in both places. If the service resolution use case is better handled by a list of expanding topologies than by a required/preferred split as in pod scheduling, then I wouldn't say you should feel obligated to use the latter.

**Comment by bgrant0607** [comment]
cc @saad-ali

**Comment by msau42** [comment]
FYI volume topology design for 1.10 is [here](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/storage/volume-topology-scheduling.md)
And dynamic provisioning design proposal is here: kubernetes/community#1857

**Comment by bgrant0607** [comment]
Another topology-related issue -- service routing:
https://github.com/kubernetes/community/pull/1551
https://github.com/kubernetes/kubernetes/issues/58744
https://github.com/kubernetes/kubernetes/pull/58732

**Comment by janetkuo** [comment]
I drafted a KEP for topology-aware workload controllers:
https://github.com/kubernetes/community/pull/2045

**Comment by chino** [comment]
...Sorry if this isn't the right place to ask questions...

What about the use case where I *ONLY* want to resolve to a pod on my local node and NEVER want to route to another node. Assuming that something (a daemonSet or an Operator) ensures that the pod should exists and/or will eventually exist...

I have use cases where we improve performance in production systems (per node) by centralizing certain types of work into a single pod.  This service has intention to leverage things like unix sockets, ipc, mmap, shared volumes, and network connections across various pods on the system.

I could obviously query the k8s to discover the pod's ip but it would be really clean and simple to have a service with a non changing cluster-ip resolve to a simple convention like, `<service>.local`?

**Comment by bgrant0607** [comment]
@chino See https://github.com/kubernetes/kubernetes/issues/28610

**Comment by Dm3Ch** [comment]
..Sorry if this isn't the right place to ask questions...

Would this useful thing be created?

**Comment by thockin** [comment]
cosing this in favor of the various individual features being developed
