### ISSUE TITLE
Our kubernetes is installed via the rpm package.But how to setting up HA masters in version 1.5.The official in 1.5 can only use kube-up/kube-down to create, whether there are other ways

### ISSUE THREAD

**Issue by strugglingyouth** [kubernetes/kubernetes#41467]
Our company installed kubernetes through the already made rpm package, the version is 1.5, but through the new function how to create HA, in addition to using kube-up.sh/kube-down.sh  this method.
Hope to give suggestions,thanks.

**Comment by castrojo** [comment]
Please re-post your question to [Stack Overflow](http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support
are posted so that we can improve our efficiency in responding to your requests,
and to make it easier for you to find answers to frequently asked questions and
how to address common use cases.

We regularly see messages posted in multiple forums, with the full response
thread only in one place or, worse, spread across multiple forums. Also, the
large volume of support issues on github is making it difficult for us to use
issues to identify real bugs.

The Kubernetes team scans Stack Overflow on a regular basis, and will try to
ensure your questions don't go unanswered.

Before posting a new question, please search Stack Overflow for answers to
similar questions, and also familiarize yourself with:

  * [user documentation](http://kubernetes.io/docs/)
  * [troubleshooting guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/)

Again, thanks for using Kubernetes.

The Kubernetes Team
