### ISSUE TITLE
parameterCodec::DecodeParameters seems to be doing strange things

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#41472]
I was looking into memory allocations in large clusters and discovered that ~5% of allocations are coming from "parameterCodec::DecodeParameters".

I started looking closer into it and it seems that something strange is happening there.

So I added some logs to the code and have the code like this:
```
156 // DecodeParameters converts the provided url.Values into an object of type From with the kind of into, and then
157 // converts that object to into (if necessary). Returns an error if the operation cannot be completed.
158 func (c *parameterCodec) DecodeParameters(parameters url.Values, from schema.GroupVersion, into Object) error {
159   if len(parameters) == 0 {
160     return nil
161   }
162   glog.Errorf("AAA: %#v", from)
163   targetGVKs, _, err := c.typer.ObjectKinds(into)
164   if err != nil {
165     return err
166   }
167   targetGVK := targetGVKs[0]
168   glog.Errorf("AAA: %#v (%#v)", into, targetGVK)
169   if targetGVK.GroupVersion() == from {
170     glog.Errorf("AAA: direct conversion")
171     return c.convertor.Convert(&parameters, into, nil)
172   }
173   glog.Errorf("AAA: bad conversion")
174   input, err := c.creator.New(from.WithKind(targetGVK.Kind))
175   if err != nil {
176     return err
177   }
178   glog.Errorf("AAA: %#v", input)
179   if err := c.convertor.Convert(&parameters, input, nil); err != nil {
180     return err
181   }
182   return c.convertor.Convert(input, into, nil)
183 }
```

And when I'm looking into apiserver logs now, I'm seeing a lot of lines like this:
```
E0215 12:09:51.658746       5 codec.go:162] AAA: schema.GroupVersion{Group:"meta.k8s.io", Version:"v1"}
E0215 12:09:51.658763       5 codec.go:168] AAA: &v1.GetOptions{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ResourceVersion:""} (schema.GroupVersionKind{Group:"meta.k8s.io", Version:"__internal", Kind:"GetOptions"})
E0215 12:09:51.658777       5 codec.go:173] AAA: bad conversion
E0215 12:09:51.658785       5 codec.go:178] AAA: &v1.GetOptions{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ResourceVersion:""}
```

For me it clearly seems like:
- from is "meta.k8s.io/v1"
- into is "v1.GetOptions"
But: targetGVK is set to "meta.k8s.io/__internal"

And what we are doing then is:
- we create yet another "v1.GetOptions" object
- we decode into that object
- and then we convert this input into "into" (which is of the same type)

It seems that targetGVK is not what we want. (and it seems we can avoid a lot of allocations if we fix that).

@smarterclayton @kubernetes/sig-api-machinery-misc @kubernetes/sig-scalability-bugs

**Comment by wojtek-t** [comment]
So I looked into the code, and the reason for that behavior is that we have:
```
v1.GetOptions
v1.ListOptions
v1.DeleteOptions
v1.GetOptions
```

registered in both "meta.k8s.io/__internal" and "meta.k8s.io/v1" groups.

So if registering those in both internal and external group is by-design, then we need to fix the "typer" that is determining group-version of an object.

**Comment by sttts** [comment]
Here is the root cause: https://github.com/kubernetes/kubernetes/blob/a591242061742bfb651cb25f2dc7b3da160f9a0c/staging/src/k8s.io/apimachinery/pkg/apis/meta/internalversion/register.go#L68

We register the meta types multiple times.

Moreover, the order in `targetGVK` is unlucky, leading us to the described conversion path in the parameter codec.

To solve this, we can
1. fix the order of targetGVK by enforcing the order of registration of metainternal and metav1
2. or make the parameter codec aware of possibly multiple matching GVKs.

In downstream OpenShift we will register types in two groups in order to migrate to api groups. I guess we will have exactly the same problem as now with meta. Hence, I vote for (2).

@smarterclayton @deads2k any side effect to expect with (2)?

**Comment by wojtek-t** [comment]
I'm not fan of 1 - initialization order is pretty subtle thing and it would be easy to break it in the future.

I think (2) is much better. Though the question is: can we do better than iterating over all returned "GVKs" and if any of those is equal to from then just avoid 2-step conversion?
I mean - can we avoid this "iteration over all returned GVKs"?

**Comment by wojtek-t** [comment]
Anyway - that change is super trivial, so I will send out a PR with it in few minutes.

**Comment by sttts** [comment]
The iteration will always be tiny: 1, 2 or 3 iterations. So this is not super performance critical I guess. Can you double check that this really is the case? Maybe even write a small unit test that no Kind is listed more than n times?

If this becomes a problem, we can easily switch to a map I guess.

**Comment by wojtek-t** [comment]
Yeah - it seems it's never more than 2.

**Comment by smarterclayton** [comment]
Yeah, decodeparameters is a copy of converttoversion and has drifted over
time.

I'm fine with 2 - converttoversion is the model

On Feb 15, 2017, at 8:05 AM, Wojciech Tyczynski <notifications@github.com>
wrote:

Yeah - it seems it's never more than 2.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/41472#issuecomment-280005311>,
or mute the thread
