### ISSUE TITLE
[Proposal] Describe ports of a service with tls

### ISSUE THREAD

**Issue by nicksardo** [kubernetes/kubernetes#41678]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Small Feature Request

**What you expected to happen**:
A frequent user request is the ability to encrypt the backend communication for L7 load balancing. We cannot provide this currently because a service port is only described by its protocol, and any given ingress controller cannot make an accurate determination of using HTTPS. 

**Feature**
Although it won't change how they're are implemented, it seems appropriate that the service resource dictate whether the backend is expecting encryption or not. Multiple ingress resources could then point to the same service and respect its behavior. 

Start with annotating the service with a list of ports/portnames.  eg:
```
    service.beta.kubernetes.io/tls-ports: "[\"443\",\"abc\"]"
```

If this indicator is deemed useful as an annotation during alpha, it could be later moved to the port struct as a boolean flag.
```
  ports:
  - port: 443
    protocol: TCP
    tls: true
    name: http
```

In regards to the associated `Endpoints` resource, it does not seem immediately useful to propagate this flag over, but could be done later if necessary.

cc @thockin

**Comment by thockin** [comment]
NIck,

A few thoughts.

1) We could alternatively implement this in Ingress, since TLS is sort of an L7 thing.  But not REALLY.  I was going to argue hard that it should be in Ingress.  I even started to write it up, but the more I think on it, the more I think this could be better.  It's just "decoration" but it is informative.

2) While I would demand alpha for a lot of changes, if this is just informational and is just a bool, I could maybe argue going straight to beta.

3) Is this just a bool?  Very often these things start as a bool, and end up a struct.  Are there any other values we can anticipate wanting wrt TLS here?  Hostname?  I don't know TLS well enough to project forward.  @bprashanth or @smarterclayton ?

4) There was some discussion about not doing annotations for pre-GA fields anymore.  I don't know if we've actually started doing that (since we have not done more granular versions yet).  @smarterclayton or @bgrant0607 or @lavalamp ?

I think this is a workable idea - we can regognize it in the various Ingress controllers and enable back-side TLS.

@kubernetes/sig-network-api-reviews

**Comment by davidopp** [comment]
Regarding (4) I am not sure we ever resolved #34508. If we did, someone really should write it up as a design doc.

**Comment by smarterclayton** [comment]
If we're going to add a little bit more metadata on ports, I'd prefer to go into https://github.com/kubernetes/kubernetes/issues/6908 which covers some of the other things that are useful to know.

**Comment by thockin** [comment]
I'm OK to consider other decorations, but I'm trying to walk the line for
pretty low-level stuff in Service.  TLS is not particular to HTTP, for
example.

**Comment by thockin** [comment]
Clarification, the value should be the name of the port.  The only case where a port is allowed to have no name is when there is a single port, in which case its name may be "" (or may be defined).

So I think this annotation should only be node names, i.e. not "443".

**Comment by nicksardo** [comment]
@thockin Should I go with `tls-port-names` to prevent user confusion? 

To make sure I understand you correctly, in the case a service has a single unnamed port, it would be acceptable to have the annotation value = `"[ \"\" ]"`

**Comment by thockin** [comment]
I think tls-ports is ok, and yes

**Comment by bowei** [comment]
@nicksardo -- I think this is fixed?
