### ISSUE TITLE
[Federation] Member cluster config should be stored in federation control plane

### ISSUE THREAD

**Issue by marun** [kubernetes/kubernetes#41673]
Configuration for member clusters that require secure access is currently stored in secrets in the cluster hosting the federation control plane.  According to the following comment, this was originally necessary because the federation control plane didn't support secrets:

https://github.com/kubernetes/kubernetes/blob/master/federation/apis/federation/v1beta1/types.go#L43

Now that secrets are supported, cluster configuration should be stored in the federation control plane.

cc: @kubernetes/sig-federation-misc

**Comment by madhusudancs** [comment]
One of the reasons why we are still not in a position to do this is because creating a secret in a federation control plane copies those secrets to all the underlying clusters. This is unnecessary and also potentially dangerous. We should be able to do this when we get cluster selection support or some form of support to not propagate secrets to the underlying clusters.

**Comment by marun** [comment]
@madhusudancs How about using an annotation on a namespace to prevent propagation of it and any contained resources?  I was looking into what it would take to support Helm, and being able to prevent a namespace from being federated would support Helm's use of release-tracking ConfigMaps.

**Comment by madhusudancs** [comment]
@marun storing credentials in a namespace object's annotation is even more dangerous than propagating secrets. It is unexpected and it is quite likely to surprise users. Federation admins then also have to ensure that they have right RBAC's applied to the namespace objects and can't let anyone who can't read the credentials to read the namespace object.

I am not sure I understand the proposal about ConfigMaps. Could you please elaborate a bit?

**Comment by marun** [comment]
@madhusudancs I didn't say anything about storing credentials in annotations.  I asked whether marking a namespace via an annotation would be a good way of indicating that it and resources it contained (e.g. secrets or ConfigMaps) shouldn't be propagated to member clusters.

The Helm tiller pod uses ConfigMaps to track releases of charts.  The tiller currently expects to be able to store ConfigMaps via the same API that it deploys charts to, which suggests that the Federation API support creating ConfigMaps that won't be propagated to member clusters.

Another option could be that Helm gain the ability to target one API for deployment of charts and another API for tracking deployment history. If a general purpose mechanism to prevent resource propagation is desirable anyway, though, I'm not sure that would be the best option.

**Comment by madhusudancs** [comment]
> @madhusudancs I didn't say anything about storing credentials in annotations. I asked whether marking a namespace via an annotation would be a good way of indicating that it and resources it contained (e.g. secrets or ConfigMaps) shouldn't be propagated to member clusters.

I see. That wasn't very clear since the original discussion was about cluster config/credentials secret and its propagation. Makes sense now. That approach might work. But is there a reason why it is superior than applying these rules to individual objects? If we were to have this, what happens when someone submits resources such as ReplicaSets/Deployments to these federation-only namespaces?

**Comment by marun** [comment]
Applying rules to individual objects would require that tools like Helm have explicit support for federation annotations.  If exclusion was supported via a namespace, a user could configure a namespace with the annotation and configure Helm to use it by setting ``--tiller-namespace``.  Helm wouldn't have to know it was targeting a federation API to work.  The user would set the annotations for the objects they intended to federate in the templates of a given Helm chart.

I share your concern regarding accidental creation of federated resources in federation-only namespaces.  What do you think of refusing to create or update resources in federation-only namespaces if they specified federation annotations?  Maybe via an admission controller?

cc: @technosophos

**Comment by smarterclayton** [comment]
What is a "federation-only namespace"?

**Comment by marun** [comment]
@smarterclayton A 'federation-only namespace' as proposed is a namespace with an annotation that indicates it and its contents should not be propagated to member clusters.

**Comment by marun** [comment]
cc: @derekwaynecarr

**Comment by marun** [comment]
@liggitt @deads2k This is a blocker on enabling integration testing of secured federation member clusters.

**Comment by nikhiljindal** [comment]
1. Yes we do want to move from creating secrets in host cluster to creating them in federation control plane.
2. To be able to do this, we need the ability to tell federation control plane to not distribute the secret to underlying clusters (which is what it does by default).
3. https://github.com/kubernetes/community/pull/344 is the proposal which we want to use to be able to do this. We can set a cluster selector that only matches the federation control plane and none of the underlying clusters.

So hopefully, we will be able to do this in 1.7

Caveats: I didnt really follow the helm discussion.
And @marun Can you please add more detail on why does this block integration testing?

**Comment by nikhiljindal** [comment]
ok I read the helm discussion again and I think I understand it now.

1. Whats the drawback of propagating the helm configmaps to underlying clusters? 
2. Who uses these configmaps? Does it make sense to keep them in underlying clusters as well so that users can run helm commands directly in underlying clusters if required?

**Comment by nikhiljindal** [comment]
Re: federation only namespace. https://github.com/kubernetes/community/pull/344 wont support it out of the box. Users are expected to ensure that they create federation only resources in federation only namespace. Else their creation will fail in underlying clusters since the namespace wont be there.

But once we have the basic support as outlined in that proposal, we should be able to extend it to support that use case.

**Comment by marun** [comment]
@nikhiljindal Integration testing involves running the api server standalone so there isn't a host cluster to store secrets in.  Since accessing secured member clusters requires being able to store secrets in the host cluster, it's not possible to target secured member clusters.  

It's not blocking testing of unsecured clusters, but I didn't realize that http vs https is more than just transport.  @liggitt and @deads2k made it clear authn/authz is entirely disabled when running over http, which means we really need to be testing with secured member clusters.

**Comment by marun** [comment]
Regarding helm's use of configmaps, they are to track releases for helm and I don't see the point of propagating them.  I'm not sure why helm would be running in more than the federation control plane, seems like a coordination nightmare.  But maybe @technosophos could chime in?

**Comment by irfanurrehman** [comment]
This issue was labelled only for sig/multicluster and is thus moved over to kubernetes/federation#103.
If this does not seem to be right, please reopen this and notify us @kubernetes/sig-multicluster-misc.
/close
