### ISSUE TITLE
Master components are not started after kubemark-master reboot

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#41735]
We currently have only anecdotal evidence, so it needs to be verified.

cc @wojtek-t @shyamjvs

**Comment by shyamjvs** [comment]
The problem seems to be that the files written by the start-kubemark-master.sh script (like systemd kubelet.service file, /etc/kubernetes/manifests, etc) disappear from the disk once the machine is rebooted. They need to persist across reboots. So from offline discussion, the best thing to do for now seems to be creating a new PD for placing these files.

**Comment by shyamjvs** [comment]
After failing on multiple attempts trying to move config files to a new disk, here is why I think it's a bad idea to do it:
- Each time on reboot, we would need to remount this new PD as disks don't stay mounted across boots. We can get over this by adding an entry for the mount in /etc/fstab so it happens automatically on boot, but it doesn't seem to be a stable solution across distros ([ref](http://www.linuxquestions.org/questions/linux-server-73/nfs-entries-in-etc-fstab-not-mounting-on-boot-546512/))
- We use symbolic links for standard locations like /etc/default/docker, /etc/default/kubelet, /etc/srv/kubernetes, etc (no pun intended :p) as an indirection to the files on the PD, as the master components seem to be unable to access files from non-standard locations (like the mounted PD). However, those symlinks don't persist across boots, so we would have to create them on each boot (and that too only after mounting the PD).
- Overall, it would make our setup unnecessarily complicated and different from that of real clusters.

Here's a much better solution:
- Modify `start-kubemark-master.sh` script to recreate the same state as before, when run after a reboot. This involves a few caveats, like preserving the master env file across boots, not running non-idempotent operations (like creating and writing controller-manager, scheduler tokens to apiserver tokens file) which should happen only on the first time.
- Then just make this script get called on boot by adding it to some place like init.d, crontab, etc.
- This setup would also make it quite similar to real clusters.

Luckily, due to the way we structured kubemark startup scripts, it is not very difficult to achieve the above. We already have the master env available as a file which stays across boots. So we just need to make couple of other things (like certs/sshkeys/tokens, etc) that are passed from `start-kubemark.sh` to persist. I already have a working solution coded and would send out a PR for this soon.
