### ISSUE TITLE
kube-apiserver does not have sufficient permissions to proxy all kubelet API calls

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#42045]
Current results look like this:
```
I0210 18:33:16.839] Feb 10 18:33:16.839: INFO: ResourceUsageSummary JSON
I0210 18:33:16.840] {}
```

This is probably caused by:
```
I0210 18:09:44.941] Feb 10 18:09:44.941: INFO: Error while reading data from e2e-scalability-minion-group-rjn8: Forbidden (user=kube-apiserver, verb=create, resource=nodes, subresource=stats) (post nodes e2e-scalability-minion-group-rjn8:10250)
```

Which means that one of RBAC changes broke https://github.com/kubernetes/kubernetes/blob/master/test/e2e/framework/resource_usage_gatherer.go

Monitoring resource usage is VERY important (even though we don't promise anything in that space), so we need to fix that during the code freeze. @timothysc @jeremyeder 

Quick-ish fix would be to make default service account admin of the scalability test clusters @kubernetes/test-infra-maintainers @shyamjvs @wojtek-t 

The tool is very old, and thus very brutal, so we may want to replace it with something better, but I can't take too long.

**Comment by spiffxp** [comment]
@kubernetes/sig-scalability-bugs @gmarek @wojtek-t are we still aiming to complete this for 1.6?

**Comment by wojtek-t** [comment]
I think we do, but that's not a release-blocker.

**Comment by liggitt** [comment]
That looks like the user I'd expect for the `master<->kubelet` communication (added in https://github.com/kubernetes/kubernetes/pull/42675 and https://github.com/kubernetes/kubernetes/pull/41207)

That PR set up [authorization rules](https://github.com/kubernetes/kubernetes/pull/41207/files#diff-6e3b476b9225d1213dc6ad13e453fc16R1109) for that user, but it looks like the `/stats` call takes POST requests as well, so that role needs to include create.

Fixed in https://github.com/kubernetes/kubernetes/pull/43265

**Comment by liggitt** [comment]
moving to blocker, impact is to the node/proxy API, not just the resource monitor

**Comment by gmarek** [comment]
Thanks @liggitt. This made `Error while reading data from` go away, which indicates that RBAC issue is solved. ResourceMonitor still returns an empty result, but I'll create a separate issue for it #43908.
