### ISSUE TITLE
No way to configure addresses for a node with kubelet

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#42125]
Kubelet currently will update the node addresses in the status, meaning it cannot be edited manually / with a controller.

However, there is also no way to tell kubelet to register anything other than a single `--node-ip` address flag, which gets registered as `NodeLegacyHostIP` and `NodeInternalIP`.

We should allow arbitrary addresses to be specified on the kubelet command line, if kubelet is going to prevent them being updated externally.

**Comment by smarterclayton** [comment]
Yeah, this is *extremely* annoying.

**Comment by dchen1107** [comment]
@justinsb @smarterclayton Can you share more detail with your use case? cc/ @mtaufen who is cleaning up kubelet command line and kubeletConfig etc.

**Comment by justinsb** [comment]
For my use case, this is on bare-metal, and I want to expose services that are NodePort or pods that are HostPort, using a dns-controller ( e.g. https://github.com/kubernetes-incubator/external-dns ) that watches the Nodes and extracts the node addresses.

Another option would be to have an option for kubelet not to set node addresses at all, so we could move it to a script / admission-controller / initializer / controller.  I don't know if this ties in to the work to split off cloud-providers cc @wlan0 ?

**Comment by wlan0** [comment]
@justinsb My work adds a `--private-id` (name is still being decided) flag to kubelet. It is a unique IP ID per host. 

> Kubelet currently will update the node addresses in the status, meaning it cannot be edited manually / with a controller.

I am pretty sure node addresses can be updated in a controller. It just gets overridden quickly by kubelet (which gets the correct addresses from the cloud) if you edit it and `--cloud-provider` is not null.

**Comment by claytononeill** [comment]
This is worse now that NodeLegacyHostIP has been removed.  There doesn't seem to be any way to set ExternalIP now for a node, and some code like keepalive-vip assumes it is set.

**Comment by munnerz** [comment]
FWIW @claytononeill, I've submitted a PR to kube-keepalived-vip to also check for the InternalIP field too https://github.com/kubernetes/contrib/pull/2708

**Comment by claytononeill** [comment]
I submitted a PR to fix this also. :)  kubernetes/contrib#2705

**Comment by bzub** [comment]
Some e2e tests require NodeExternalIP. I take it there's still no way to set this for bare-metal cluster nodes?

https://github.com/kubernetes/kubernetes/blob/2dcf54ed6478f896cd98ef64520f9618fecd7edc/test/e2e/framework/util.go#L3699

**Comment by mtaufen** [comment]
Please do not add any parameters that must be unique to an individual node to the KubeletConfiguration object (including the node's IP address). It must be possible to share a single ConfigMap containing this object between multiple nodes.

**Comment by mtaufen** [comment]
I'm also not sure if the Kubelet is the proper agent to configure this, as there is a lot of work towards moving networking code *out* of the Kubelet. 
/cc @kubernetes/sig-network-api-reviews 
/cc @thockin @dnardo

**Comment by danehans** [comment]
> I am pretty sure node addresses can be updated in a controller. It just gets overridden quickly by kubelet (which gets the correct addresses from the cloud) if you edit it and --cloud-provider is not null.

@wlan0 you are correct. @leblancd and I verified this behavior by creating a node spec containing InteralIP and ExternalIP values. The spec updates the node resource properly until a node status update occurs, when the ExternalIP is removed. This is because the Kubelet is not configured for a cloud provider and therefore has no way of managing the ExternalIP field of the node resource.

To meet @justinsb and other bare metal use cases, I suggest the following 2 options:

**Option 1:**

- Update the NodeIP type from `string` to `map[string]string`, containing `address-type: address` k/v pairs. If updating the NodeIP field is too impactful, create a new field containing the address/type map and deprecate NodeIP over time.
-  If NodeIP is configured, validate each IP and use it in the node status update.
-  If NodeIP is not configured, have Kubelet create the type/address map. If the host has a single address, use it for InternalIP and ExternalIP address types. If the host has multiple addresses, use the IP associated to a default route for ExternalIP and the first valid IP address without a default route for InternalIP.

**Option 2:**
- Use NodeLabels to manage the ExternalIP/InternalIP addresses in a node status update.
-  If NodeIP is configured, it takes precedence over ExternalIP/InternalIP address NodeLabels (backwards compatibility).
-  Deprecate NodeIP over time.

I am willing to submit a PR to implement either option.

**Comment by gogene** [comment]
@danehans I would like to have the possibility to add the ExternalIP via labels and without configured cloud-providers. Are you still working on that?

**Comment by danehans** [comment]
@gogene I am not working on this. I never received feedback on the 2 options that I proposed. It sounds like you're interested in option 2. Maybe someone in sig-network can take it on or feel free to take a crack at it.

cc: @leblancd @pmichali @rpothier

**Comment by lloeki** [comment]
I like *Option 1* for its simplicity and reusal of `--node-ip` which is already a known workaround for bare metal (Digital Ocean precisely), which currently only sets `InternalIP` on nodes, leaving `ExternalIP` as `<none>`. It's especially simple and useful when provisioning nodes using `kubeadm` and `KUBELET_EXTRA_ARGS` in `/etc/systemd/system/kubelet.service.d/10-kubeadm.conf`.

> I am pretty sure node addresses can be updated in a controller. It just gets overridden quickly by kubelet (which gets the correct addresses from the cloud) if you edit it and --cloud-provider is not null.

In the meantime I was looking for a stopgap measure to set `ExternalIP` too. Some way to perform the above would be great, as it sounds like it'd stick since we're not setting `--cloud-provider`. Even a hack as below would be fine for now (but this doesn't work):

```
$ kubectl patch node my-node-03 -p '{"status": {"addresses": [{ "address": "11.22.33.44", "type": "ExternalIP" }, { "address": "44.33.22.11", "type": "InternalIP" }, { "address": "my-node-03", "type": "Hostname" }] } }'
node "my-node-03" not patched       # :-(
```

So is there any way to come up with anything like that, or is the whole `{Ex,In}ternalIP` thing entirely internally managed currently?

**Comment by ernoaapa** [comment]
If someone is still looking for a way to define ExternalIP (no `--cloud-provider` defined), you can update it with a PATCH request, the same way how the cloud-provider does it.

```shell
# (Add token or certificates, depending on how you authenticate to Kube)

curl -k -v -XPATCH \
  -H "Accept: application/json" \
  -H "Content-Type: application/json-patch+json" \
  https://<YOUR KUBE ADDRESS>/api/v1/nodes/<YOUR NODE NAME>/status \
  --data '[{"op":"add","path":"/status/addresses/-", "value": {"type": "ExternalIP", "address": "<ADDRESS HERE>"} }]'  
```

**Comment by cskarby** [comment]
> \# (Add token or certificates, depending on how you authenticate to Kube)

What kind of privileges are needed? As an user with the cluster role cluster-admin privilege I run 
```shell
kubectl patch node "${NodeName}" --type='json' -p="[{\"op\":\"add\",\"path\":\"/status/addresses/-\",\"value\":{\"type\":\"ExternalIP\",\"address\":\"${ExternalIP}\"}}]"
```
, but it seems to have no effect, even after reinstalling the worker node initiating a fresh kubelet (v1.14.3) with `--cloud-provider=external`. Also `kubectl edit node ${NodeName}` seems happy, but there is no change (the address is missing when starting kubectl edit node ${NodeName} again.

**Comment by micahhausler** [comment]
@cskarby cluster admins are able to overwrite node addresses, but the Kubelet does a periodic  update (I think 30s?) of it's own addresses and is overwriting your patch.

**Comment by furkanmustafa** [comment]
I don't think that this issue is closed in any way.

**Comment by aojea** [comment]
/remove-lifecycle rotten
/reopen

I think that this should be reconsidered for dual-stack, a node will have an IPv4 and an IPv6 internal address on dual-stack environments 

/cc @khenidak @thockin

**Comment by jpetazzo** [comment]
@cskarby (and others who might stumble upon this): the PATCH request must be issued on `/api/v1/nodes/${Node}/status`. It took me a while to understand the difference between the example given by @ernoaapa above, and what I was doing :sweat_smile: 

When we use `kubectl patch`, the request is issued on `/api/v1/nodes/${Node}` (without the final `/status`) and the API server drops it silently.

When troubleshooting this, I saw two kinds of problems:

1) My update is dropped silently (`kubectl patch` says `(no change)`
→ This happens when doing the request on the wrong URI. The request should be done "manually" (with e.g. `curl`) instead of `kubectl patch`.

2) My update gets reverted almost instantly (the ExternalIP shows up briefly in e.g. `kubectl get nodes -o wide` but disappears less than a minute later
→ This happens when kubelet overwrites the addresses. We need to tell kubelet that the addresses will be managed by the cloud controller manager, by starting kubelet with `--cloud-provider=external`. This means that we need to add all the addresses ourselves, and then remove the taint placed by the kubelet.

I hope this helps. It would indeed be super nice if it were possible for kubelet to just add the ExternalIP :thinking:

**Comment by furkanmustafa** [comment]
come on @fejta-bot  we're all still here.

/remove-lifecycle stale

**Comment by furkanmustafa** [comment]
While "cloud provider"s do provide external IP, originally a node having an External IP does not necessarily have to do anything with a "cloud provider". I should be able to configure my node's external IP on the node, just with a parameter. Just as I could set `node-ip`.

adding an `--external-ip`, or even better; `--external-ips` field to `kubelet` should be very trivial.

**Comment by fromanirh** [comment]
it seems there still is interest in this issue
/area kubelet
/priority backlog
/triage accepted

**Comment by furkanmustafa** [comment]
Dear `area/kubelet`,

Would it be accepted if we work on a spec by discussing here, and create a Pull Request for this? Based on the suggestion below,

> adding an `--external-ip`, or even better; `--external-ips` field to `kubelet` should be very trivial.

For covering use cases where poeple do not have a "Cloud Provider".

**Comment by aojea** [comment]
Why do you need to define the external IP in the kubelet?
Is not valid to set the node internal IP only?

**Comment by furkanmustafa** [comment]
> Why do you need to define the external IP in the kubelet?
> Is not valid to set the node internal IP only?

Usual use-cases that External IP is there for, like for routing, auto-configuring DNS, etc.
Most of the time, we don't use public IPs as "Internal IP". Most of our nodes do not have a public IP (but have an Internal IP that is accessible from all other nodes), but some nodes do have an External(/Public) IP as well, on top of having an Internal IP.

**Comment by aojea** [comment]
> Would it be accepted if we work on a spec by discussing here, and create a Pull Request for this? Based on the suggestion below,
> 
> > adding an `--external-ip`, or even better; `--external-ips` field to `kubelet` should be very trivial.

Although at first sight looks simple, the node addresses topic has a lot of caveats,  I remember to discuss them extensively during the dual-stack feature, https://github.com/kubernetes/enhancements/pull/1665#issuecomment-706146957and https://github.com/kubernetes/kubernetes/pull/95768 

@danwinship you went through all the node addresses code, what do you think?

**Comment by danwinship** [comment]
:man_shrugging: 

See also #73760

**Comment by thockin** [comment]
@danwinship This seems relevant to current discussion - opportunity to de-dup issues?

**Comment by danwinship** [comment]
/retitle No way to configure ExternalIP addresses for a node with kubelet

It's not quite a dup of the other discussion because that's about dual-stack InternalIPs, whereas this is about (single-stack or theoretically dual-stack) InternalIP+ExternalIP.

There was some discussion of this in https://github.com/kubernetes/enhancements/pull/1665 but never any consensus that we actually wanted to support this (as opposed to, say, killing off ExternalIPs and/or node.status.addresses)

**Comment by shaneutt** [comment]
As discussed in our community meeting today:

/assign @danwinship

**Comment by qdii** [comment]
Is there an update on this?

Another problem is that passing `--cluster=external` to kubelet makes it impossible to configure dual-stack internal IP addresses. Quoting https://kubernetes.io/docs/concepts/services-networking/dual-stack/:

> when there is no --cloud-provider the administrator can pass a comma-separated pair of IP addresses via --node-ip to manually configure dual-stack .status.addresses for that Node

So the workaround proposed by ernoaapa@ comes with abandoning IPv6.

**Comment by danwinship** [comment]
That's addressed by [KEP-3705](https://github.com/kubernetes/enhancements/tree/master/keps/sig-network/3705-cloud-node-ips) which is currently alpha. (It should be beta in 1.29.)

**Comment by dvaldivia** [comment]
@danwinship did that KEP ever got moved forward?

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/enhancements/issues/3705 Went GA in 1.30 (the KEP issue is more up to date than https://github.com/kubernetes/enhancements/tree/master/keps/sig-network/3705-cloud-node-ips#implementation-history which is pretty common)

**Comment by danwinship** [comment]
The original issue was about adding ExternalIPs when not using a cloud provider. There has been no progress on that, including agreement on whether or not that is actually a good idea.

(The discussion over the last year was a side discussion about external cloud providers not related to the original bug report.)

**Comment by danwinship** [comment]
/triage accept

Previous comment still applies.

ExternalIPs have no globally-well-defined semantics, but they have consistent semantics on each individual cloud platform, so some people use them for some things in isolated contexts. In theory we could define a semantics for ExternalIPs on bare metal, and people would do things with that, but it would be better to redesign node addresses entirely...

**Comment by kvaps** [comment]
Hey, just for your information: I ran into the same issue and created local-ccm, which automatically detects the external address via netlink and sets it on the Node object.

More details specified here:
https://github.com/cozystack/local-ccm?tab=readme-ov-file#how-it-works
