### ISSUE TITLE
Moving towards file-based interface for container stdout/stderr logs

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#42188]
When designing CRI, we've had many discussions on how to best approach container logs. There were pros and cons for each approach, but we settled on letting container runtimes write to files directly, and kubelet be the consumer/manager of the log files ([proposal](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/kubelet-cri-logging.md)). This aligned (and I believe still align today) with the long-term roadmaps for log management on the node and the cluster logging pipeline.

This file-based API does not work well with non-json log drivers in docker because most of them involve sending log streams directly to a separate logging daemon. Specifically, rhel/openshift sets the log driver to journald by default. To help users transition to the json log driver, we need to figure out what's missing in the current log management scheme, and decide whether we can support them or not.

 - log rotation
   - By default, kubernetes requires an external log rotator on the node; docker also supports size-based log rotation for the json driver)
   - There has been discussions on letting kubelet perform the log rotation
 - rate limiting

What else?

/cc  @derekwaynecarr @ncdc @sjenning @dchen1107 @vishh @Random-Liu @thockin

**Comment by ncdc** [comment]
cc @richm @jcantrill @portante @sosiouxme

**Comment by ncdc** [comment]
@smarterclayton @mrunalp @rhatdan @jwhonce

**Comment by richm** [comment]
From the standpoint of OpenShift aggregated logging, the most important thing is having a way to get all available log metadata for each log message from a container/pod.  Right now we get the pod name, namespace name, and container name/id, and we use this data to look up the pod uuid, namespace uuid, pod labels and annotations from the API.  We must have a way to get all of this data, and we get the log data via standard log collectors such as fluentd and rsyslog.

**Comment by yujuhong** [comment]
@richm fluentd+json log driver today should also give you enough metadata, so you don't need the journald driver for that.

Also, there have been discussions on properly defining the logging integration interface, and add more metadata if necessary. 
/cc @Crassirostris @piosz

**Comment by richm** [comment]
@yujuhong yes, and we support both.  We prefer journald because we get a lot more metadata and avoid some file I/O.

**Comment by yujuhong** [comment]
> @yujuhong yes, and we support both. We prefer journald because we get a lot more metadata and avoid some file I/O.

What kind of additional metadata you get from journald?

**Comment by richm** [comment]
```
$ journalctl -n 1 -o export 'CONTAINER_NAME=k8s_curator.c70f0cc0_logging-curator-1-x4tgb_logging_e67198ec-fabd-11e6-847e-fa163e6a3ed1_fc0b6b7f'
__CURSOR=s=46fae4ed08ad45bb9a47c05c52eb0796;i=62d23;b=f3dd6d2fc60144d7959bfdde8d
__REALTIME_TIMESTAMP=1488153601858681
__MONOTONIC_TIMESTAMP=194196202207
_BOOT_ID=f3dd6d2fc60144d7959bfdde8d80238c
_UID=0
_GID=0
_CAP_EFFECTIVE=1fffffffff
_SYSTEMD_SLICE=system.slice
_MACHINE_ID=6d48b4ed994e4baa915236703275389b
_HOSTNAME=my.fqdn
CONTAINER_TAG=
_TRANSPORT=journal
_PID=5040
_COMM=dockerd-current
_EXE=/usr/bin/dockerd-current
_CMDLINE=/usr/bin/dockerd-current --add-runtime docker-runc=/usr/libexec/docker/
_SYSTEMD_CGROUP=/system.slice/docker.service
_SYSTEMD_UNIT=docker.service
_SELINUX_CONTEXT=system_u:system_r:container_runtime_t:s0
PRIORITY=3
CONTAINER_ID=8224c6085ee1
CONTAINER_ID_FULL=8224c6085ee1bb207a84e4b4cff43568589153a1364b1c757d84445b1f1dd8
CONTAINER_NAME=k8s_curator.c70f0cc0_logging-curator-1-x4tgb_logging_e67198ec-fab
MESSAGE=curator run finish
_SOURCE_REALTIME_TIMESTAMP=1488153601857759
```
So, not necessarily Kubernetes/docker metadata, but a lot of other metadata we can use for correlation.

**Comment by portante** [comment]
@yujuhong, we really want to have the ability to add that rich metadata, as @richm displays, to correlate with other subsystems and services on the hosts.  It would be a loss to drop all that without a way to replace it.

**Comment by vishh** [comment]
Managing Disk IO will soon become a necessity for kubernetes. To provide
QoS for IO, it is better for the system to manage storage of logs directly
than via other agents like journald.

**Comment by vishh** [comment]
Metadata will be provided by dumping pod spec into pod level logging
directories. It will be upto logging agents to surface the metadata in a
user friendly manner.

**Comment by portante** [comment]
@vishh, will that pod spec have the same or equivalent metadata that journal offers now?

**Comment by richm** [comment]
> Metadata will be provided by dumping pod spec into pod level logging directories.

@vishh Will that data be updated dynamically, when pod/namespace metadata changes?  For example, a pod is created, and metadata is dumped.  What happens when the pod labels/annotations are changed while the pod is running?  Will new metadata be dumped?  Same goes for namespace metadata, if applicable.

**Comment by Crassirostris** [comment]
@richm But do you need to have this metadata in each entry? Almost all these fields can be extracted independently and then joined with the log entries, if necessary.

As for k8s metadata, the current plan is to retrieve it from API server. In the future, maybe that will change to retrieving metadata from kubelet directly (via API or files, that's yet to be discussed).

**Comment by Crassirostris** [comment]
@richm As for the problem with mutable metadata, does journald allow to solve it?

**Comment by Crassirostris** [comment]
@portante What Vish is talking about is kubernetes metadata, journald doesn't have that

Metadata that is currently inside journald log entry can be acquired in a different way and then joined with logs. For example, when consuming logs by fluentd, you can add hostname as one of the labels, or join hostname with the node name (that is inside kubernetes metadata) on backend later.

**Comment by richm** [comment]
> But do you need to have this metadata in each entry?

No.  I just need a method I can use in the local log collector agent (e.g. fluentd, rsyslog, filebeat, fluentbit, whatever) to associate the pod/namespace metadata with each log entry.

> As for k8s metadata, the current plan is to retrieve it from API server. In the future, maybe this will change to retrieving metadata from kubelet directly (via API or files, that's yet to be discussed).

Our current logging solution gets the k8s metadata from the API server, via the fluentd https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter.  The problem is that if you have 1000 nodes, you have 1000 persistent connections to the API server.  We have found this to be a problem in production.  That's why we would prefer a solution that does not hammer the API server quite so much (e.g. get from the local kubelet, etc.).

> As for the problem with mutable metadata, does journald allow to solve it?

No, it does not make a difference w.r.t. k8s metadata if you use docker with `--log-driver=json-file` or `--log-driver=journald`.  The only advantage of journald is fewer hops (e.g. read directly from journal rather than file I/O), and more system metadata (not k8s metadata) for each log entry.

> What Vish is talking about is kubernetes metadata, journald doesn't have that

Correct.

**Comment by crassirostris** [comment]
> No. I just need a method I can use in the local log collector agent (e.g. fluentd, rsyslog, filebeat, fluentbit, whatever) to associate the pod/namespace metadata with each log entry.

Do you find podUID + container name sufficient for this purpose?

> Our current logging solution gets the k8s metadata from the API server, via the fluentd https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter. The problem is that if you have 1000 nodes, you have 1000 persistent connections to the API server. We have found this to be a problem in production. That's why we would prefer a solution that does not hammer the API server quite so much (e.g. get from the local kubelet, etc.).

That is indeed a great note. I created an issue https://github.com/kubernetes/kubernetes/issues/42718 about integration with logging pipeline on the node, maybe discuss the question of moving away from querying API server directly there?

> The only advantage of journald is fewer hops (e.g. read directly from journal rather than file I/O)

Could you please elaborate on that? By 'fewer hops' you mean less work for log collector, which doesn't have to look for separate files and only read from one source or less performance overhead?

For the less fuss with log sources, I think that is a necessity, because in the future we want to isolate and account disk usage to pod resource consumption for better sharing. With journald you would still need to separate logs for different container/pods in the long term. Do you agree?

As for the performance overhead, I'm not sure journald is better in this sense than raw file IO. It performs additional steps to process logs, compared to just appending to a file, isn't it? 

> more system metadata (not k8s metadata) for each log entry

Do you want this metadata for the remote logging or for the debugging while on the machine? What pieces of metadata you find valuable? Maybe Kubernetes can provide them even without journald in a container-runtime- and system-independent way?

**Comment by sosiouxme** [comment]
The problem with relying on looking up metadata from the k8s API is that pods/namespaces/etc can be deleted or modified. If you are aggregating log data to a log analysis solution or for any reason want to keep track of logs after pods have been deleted, you won't be able to look that up in k8s after the fact. You have to either look it up as the logs are coming through and store the metadata with each log entry, or you have to separately store the metadata and join it in your logging solution (and I don't think ElasticSearch at least will let you search for/aggregate logs by a field in "joined" data so it's dubious whether that's even a valid option).

**Comment by yujuhong** [comment]
There are two types of metadata discussed in this thread: k8s metadata (name, namespace, etc) and journald-provided metadata.
As @crassirostris pointed out, the former is part of the cluster logging integration and this is not affected by the introduction of file-based containers logs in CRI. Let's move that discussion to #42718.
For the latter, which is the journald provided, non-k8s, metadata, I don't think kubelet can support the full list in https://github.com/kubernetes/kubernetes/issues/42188#issuecomment-282855422. @richm are they are required? Can you get them through other means?

**Comment by crassirostris** [comment]
@sosiouxme I answered you in https://github.com/kubernetes/kubernetes/issues/42718#issuecomment-285206473 , let's continue the discussion there

**Comment by piosz** [comment]
>The problem is that if you have 1000 nodes, you have 1000 persistent connections to the API server. We have found this to be a problem in production. That's why we would prefer a solution that does not hammer the API server quite so much (e.g. get from the local kubelet, etc.).

@wojtek-t is this a problem from performance point of view? Do you plan to solve it? Or maybe the recommendation is to not have watch per node in big clusters?

**Comment by wojtek-t** [comment]
> @wojtek-t is this a problem from performance point of view? Do you plan to solve it? Or maybe the recommendation is to not have watch per node in big clusters?

It seems like a matter of setup, configuration etc. Even now, e.g. kubelet has IIRC at least 2 open connections to API server all the time. And it works for us in 5000-node clusters too. Also http2 helps with that (I can't remember when we enabled it by default - I think it was 1.5).

**Comment by richm** [comment]
@crassirostris 
> Do you find podUID + container name sufficient for this purpose?

No.  We need namespace_uuid, pod labels, pod annotations

> By 'fewer hops' you mean less work for log collector, which doesn't have to look for separate files and only read from one source or less performance overhead?

Yes, that plus potentially avoiding file I/O if the journal is in memory (although with file system caching, that's probably a non-issue).  So that isn't a compelling factor to favor journald over file logs.

> With journald you would still need to separate logs for different container/pods in the long term. Do you agree?

Yes, that's one of the limitations of the journald support - we don't have a way to throttle reading logs per pod/namespace with journal - we still have to read everything, and drop logs from pods/namespaces we don't care about (but that can still overwhelm the log collector with their sheer volume).

Another benefit of journald is that we get historical pod/namespace logs - if you delete a pod/namespace, with the file based approach, those log files are currently deleted - with the journald, they stay in the journal until the journal is rotated.

> As for the performance overhead, I'm not sure journald is better in this sense than raw file IO. It performs additional steps to process logs, compared to just appending to a file, doesn't it?

Yes, so the performance between journald and the file based approach is probably a wash.

> Do you want this metadata for the remote logging or for the debugging while on the machine?

Both, but primarily remote logging.

> What pieces of metadata you find valuable?

It depends on what you are debugging/troubleshooting . . . it is pretty nice to have all of this data available, for analysis and correlation.  I've attached an excerpt from a journald container log below [1]

> Maybe Kubernetes can provide them even without journald in a container-runtime- and system-independent way?

Sure, that would be fine.

[1] 
```
__REALTIME_TIMESTAMP=1490806753231892
__MONOTONIC_TIMESTAMP=284820061
_BOOT_ID=f1b1367ad6f2405a8cc0ab85b9a0bb53
PRIORITY=6
_UID=0
_GID=0
_SYSTEMD_SLICE=system.slice
_MACHINE_ID=464814b61cfcf330e1cdd3ed2d316b8b
_TRANSPORT=journal
_CAP_EFFECTIVE=1fffffffff
_COMM=dockerd-current
_EXE=/usr/bin/dockerd-current
_SYSTEMD_CGROUP=/system.slice/docker.service
_SYSTEMD_UNIT=docker.service
_HOSTNAME=host-192-168-78-2.openstacklocal
_PID=2344
_CMDLINE=/usr/bin/dockerd-current --add-runtime docker-runc=/usr/libexec/docker/
docker-runc-current --default-runtime=docker-runc --exec-opt native.cgroupdriver=systemd --userland-proxy-path=/usr/libexec/docker/docker-proxy-current --selinux-enabled --log-driver=journald --signature-verification=false --log-driver=journald --insecure-registry 172.30.0.0/16
_SELINUX_CONTEXT=system_u:system_r:container_runtime_t:s0
CONTAINER_TAG=
CONTAINER_ID=c862c75d134e
CONTAINER_ID_FULL=c862c75d134ea615858aab3a34a0dd7433b389b7b0e42e6db3d88ebdda141249
CONTAINER_NAME=k8s_registry.1e990719_docker-registry-1-g2rz9_default_d7c6fde1-14a0-11e7-9505-fa163e831ba8_6c166b06
MESSAGE=192.168.78.2 - - [29/Mar/2017:16:59:08 +0000] "PATCH /v2/logging/logging-auth-proxy/blobs/uploads/275156ca-1e17-48bb-8fc7-515ef9ffe8fc?_state=bgOFmfhumYELOp3h8b8GmBn3geZn8wTTR1zd4-fvokl7Ik5hbWUiOiJsb2dnaW5nL2xvZ2dpbmctYXV0aC1wcm94eSIsIlVVSUQiOiIyNzUxNTZjYS0xZTE3LTQ4YmItOGZjNy01MTVlZjlmZmU4ZmMiLCJPZmZzZXQiOjAsIlN0YXJ0ZWRBdCI6IjIwMTctMDMtMjlUMTY6NTk6MDguNTg4ODAxNjE4WiJ9 HTTP/1.1" 202 0 "" "docker/1.12.6 go/go1.7.4 kernel/3.10.0-514.10.2.el7.x86_64 os/linux arch/amd64 UpstreamClient(go-dockerclient)"
_SOURCE_REALTIME_TIMESTAMP=1490806753226843
```

**Comment by jberkus** [comment]
@yujuhong Are there still changes planned for 1.10 for this issue?  If so, it needs kind/ and priority/ labels, and probably needs to be tracked as a feature.

**Comment by yujuhong** [comment]
The issues (e.g., log rotation and metadata) are tracked separately. Rate limit is something we are not considering in the near term. Closing this issue.
