### ISSUE TITLE
kubeadm failed to start

### ISSUE THREAD

**Issue by xilabao** [kubernetes/kubernetes#42228]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

kubeadm version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.0-alpha.0.445+36a5c0091bcaff", GitCommit:"36a5c0091bcafffd0fb2025b9501e6223a46f169", GitTreeState:"clean", BuildDate:"2017-02-28T04:58:02Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}

**What happened**:
 `kubeadm init` failed to start kube-apiserver

**Anything else we need to know**:

https://github.com/kubernetes/kubernetes/pull/41815 `enable DefaultTolerationSeconds admission controller by default` is maybe the reason. @kevin-wangzefeng 

The kube-apiserver is created from pod by kubelet.  Does DefaultTolerationSeconds effect it?

@luxas I mention you because you are the maintainer of kubeadm

**Comment by pires** [comment]
This issue should be moved to kubernetes/kubadm repo.

**Comment by luxas** [comment]
This is due to that `DefaultTolerationSeconds` was implemented recently and requires a very new version of k8s.

This can be closed in some hours, but please file new issues in kubernetes/kubeadm as @pires pointed out.
This will be fixed in a day or two when `v1.6.0-beta.1` is cut (may be today)
Then we're gonna pin the k8s version to that `v1.6.0-beta.1` (and increment when new betas arrive), and things will work.

**Comment by luxas** [comment]
Issue moved to kubeadm: https://github.com/kubernetes/kubeadm/issues/187
