### ISSUE TITLE
Scaling Down to Zero and Back Up

### ISSUE THREAD

**Issue by jezell** [kubernetes/kubernetes#42255]
How can ResourceSets be auto scaled down to zero and back up based on network activity, similar to what an application server like IIS does with HTTP / TCP activation? The "Serverless" implementations that are targeting docker / kube seem to mainly be trying to solve this problem, which seems like something that would be nice to have in the box.

Does this type of behavior belong in an Ingress Controller, or would it be more suitable somewhere else?

**Comment by DirectXMan12** [comment]
We do have some functionality like that written in Origin that we intend to eventually upstream.  Basically, the way it currently works is that when an application is marked as idled, the kube-proxy switches into a special version of the userspace proxy which signals a controller, which scales the application back up to its previous state.  The ingress controllers then basically have to watch for an application which is idled, and make sure to send traffic to the kube-proxy.

We don't yet have the "automatically scaling to zero" part yet, though.  That's tricky, because in many cases that is based on somewhat complex policy.  Now that the custom metrics API is in place, we'll probably revisit that, though.
