### ISSUE TITLE
Improvements for hack/test_owners.csv

### ISSUE THREAD

**Issue by derekwaynecarr** [kubernetes/kubernetes#42312]
**What happened**:
hack/test_owners.csv was discussed in sig-node and problems were discussed with the process.

Problems:
1. there is no automation that auto assigns test owners when a pr is merged
1. approvers/reviewers are missing that updates are needed to that file before lgtm of pr
1. having all test owners in a single file promotes rebase problems (https://github.com/kubernetes/kubernetes/issues/35850)

Potential improvements:
1. i assume sig-node would just like all tests under test/e2e_node assigned to sig-node by default
1. i assume sig-federation would like just all test under test/e2e_federation to follow a similar practice in future...

I am opening this issue to ensure that the discussion from sig-node is not lost.

@kubernetes/sig-contributor-experience-misc @kubernetes/sig-node-proposals

**Comment by yujuhong** [comment]
Piggybacking on this issue. The tests now have individual owners and sig owners. Many of the individual owners were assigned automatically. Could we regenerate the list based on which sig the test belongs to? A sig-node member should not be assigned tests owned by sig-federation. Or, if the individual owners are so unreliable, could we just have sig owners and remove individuals?

**Comment by rmmh** [comment]
We used to require test owners to be updates with PRs were merged, but quickly turned it off because of the number of merge conflicts. Github doesn't support overriding its default merge strategy to fix the merge conflicts.

We could make test ownership comment annotations in the files themselves. Each test file is probably owned by a single sig or person, so this would make sense.
