### ISSUE TITLE
Pod can not access service IP when no nsenter in $PATH

### ISSUE THREAD

**Issue by typhoonzero** [kubernetes/kubernetes#42314]
I've created a influx-grafana pod and service point to it. But can not access influxdb api in the pod using `curl http://monitoring-influxdb:8086/`, `curl` command ends with a timeout.

According to https://kubernetes.io/docs/user-guide/debugging-services/#a-pod-cannot-reach-itself-via-service-ip , kubelet is using `hairpin-veth` mode. and the kubelet log says:

```
W0301 14:02:32.078029   13272 kubelet_network.go:69] Hairpin mode set to "promiscuous-bridge" but kubenet is not enabled, falling back to "hairpin-veth"
I0301 14:02:32.078064   13272 kubelet.go:478] Hairpin mode set to "hairpin-veth"
....
W0301 14:07:59.923866   13272 docker_manager.go:2199] Hairpin setup failed for pod "influxdb-grafana-gbjl1_kube-system(ccfb3824-fe44-11e6-861f-6c92bf04de02)": exec: "nsenter": executable file not found in $PATH
```

Seems the `nsenter` command is required under `hairpin-veth` mode, should this be checked when kubelet is starting, so this won't happen again.

------------

**Environment**:
- **Cloud provider or hardware configuration**: Bare Metal with GPU cards
- **OS** CentOS 6.3 
- **Kernel** 3.10.0_2-0-0-0 #1 SMP Tue Sep 20 17:18:54 CST 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by cmluciano** [comment]
The error seems to be returned https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/network/hairpin/hairpin.go#L66-L70 . I recall an earlier PR that removed nsenter from somewhere in the codebase; will try to track this down.

**Comment by cmluciano** [comment]
Found this https://github.com/holser/kargo/commit/82a7779abb8af929324510639e53945d9ceb7178 which seems to suggest that b/c of the recent nsenter removal in Docker 1.12, nsenter was dropped in the kubelet. 

I also remember that nsenter was specifically added to hairpin b/c of a potential bug in iproute2 with certain runtimes https://github.com/kubernetes/kubernetes/pull/25062#r61829095.

I wonder if we should consider working around nsenter so we can remove it in more places. Any thoughts @dchen1107 @vishh ?

**Comment by edevil** [comment]
I've also come across a related message when testing a new 1.6 cluster:
```
Mar 30 17:26:34 node-0-vm kubelet-wrapper[32730]: W0330 17:26:34.480249   32730 docker_sandbox.go:263] NetworkPlugin kubenet failed on the status hook for pod Unexpected command output nsenter: cannot open : No such file or directory
```

The pod in question is in the Terminating state since several hours ago.

**Comment by cmluciano** [comment]
@kubernetes/sig-network-bugs

**Comment by cmluciano** [comment]
possibly related https://github.com/containernetworking/cni/issues/476 . @caseydavenport not sure if we are transplanting all of these issues to CNI or if this issue stands on its own.

**Comment by caseydavenport** [comment]
@cmluciano this is partially related, but I think it stands on its own since this is about a missing Kubernetes user space dependency.  

> I wonder if we should consider working around nsenter so we can remove it in more places

Yeah, first step would be understanding all of the places that kubelet uses nsenter and then deciding if maybe we can get rid of our dependency on it somehow. 

That said, the immediate fix for this issue is probably to use a CNI plugin which performs hairpin and then disabling hairpin on the kubelet.

Additionally, we should update [this document](https://kubernetes.io/docs/user-guide/debugging-services/#a-pod-cannot-reach-itself-via-service-ip) to stop recommending to enable hairpin on the kubelet and instead instruct users to make sure they're using a compliant CNI plugin.  @cmluciano does that sound right to you?

**Comment by cmluciano** [comment]
SGTM
