### ISSUE TITLE
ci-kubernetes-e2e-gce-serial-release-1.6: broken test run

### ISSUE THREAD

**Issue by marun** [kubernetes/kubernetes#42345]
http://gcsweb.k8s.io/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-serial-release-1.6/3

Multiple broken tests: 

Failed: [k8s.io] Daemon set [Serial] Should not update pod when spec was updated and update strategy is on delete
```
error waiting for daemon pod to start
Expected error:
    <*errors.errorString | 0xc4203a2600>: {
        s: "timed out waiting for the condition",
    }
    timed out waiting for the condition
not to have occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/daemon_set.go:246
```

Issues about this test specifically: #42342

Failed: [k8s.io] Daemon set [Serial] Should update pod when spec was updated and update strategy is RollingUpdate 5m26s
```
error waiting for daemon pod to start
Expected error:
    <*errors.errorString | 0xc4203a2600>: {
        s: "timed out waiting for the condition",
    }
    timed out waiting for the condition
not to have occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/daemon_set.go:274
```

Issues about this test specifically: #42343 

Failed: [k8s.io] Daemon set [Serial] should run and stop simple daemon
```
error waiting for daemon pod to start
Expected error:
    <*errors.errorString | 0xc4203a2600>: {
        s: "timed out waiting for the condition",
    }
    timed out waiting for the condition
not to have occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/daemon_set.go:118
```

Issues about this test specifically: #42344

**Comment by marun** [comment]
cc: @yifan-gu @mtaufen @kubernetes/sig-apps-bugs

**Comment by kargakis** [comment]
@lukaszo @janetkuo

**Comment by marun** [comment]
@janetkuo Could #40330 be related?

**Comment by janetkuo** [comment]
> @janetkuo Could #40330 be related?

No. I checked the logs and they all failed at the first step -- `Check that daemon pods launch on every node of the cluster`

```
INFO: nodesToPodCount: map[string]int{"bootstrap-e2e-minion-group-765q":1, "bootstrap-e2e-minion-group-mzrf":1, "bootstrap-e2e-minion-group-5n4d":1}
```

There are 6 nodes in total, and only 3 of them were scheduled with DaemonSet pods. I think the other 3 nodes are full, which caused the test failure (because no more DaemonSet pods can be scheduled on them). This doesn't seem to be related to DaemonSet controller, but more like test-infra problem. @kubernetes/test-infra-maintainers

**Comment by janetkuo** [comment]
Looking at the logs more deeply, after the test failed, node info will be dumped. There are actually only 3 nodes involved in this test (not all nodes listed in artifact). 

As the log showed, we created all DaemonSet pods successfully on all those 3 nodes. However, we can't schedule pods on the master node anymore, because it has the "ismaster" taint. That's why the test failed. 

I wonder why we didn't see this in PRs. Is this e2e test not blocking submit queue?

**Comment by marun** [comment]
@janetkuo This failure is only seen on the serial job, which isn't blocking.  Apparently it takes too long to execute.

**Comment by ethernetdan** [comment]
> I wonder why we didn't see this in PRs. Is this e2e test not blocking submit queue?
@janetkuo unfortunately not 😢

**Comment by janetkuo** [comment]
Fix is underway. Eventually we'll reduce the number e2e tests and improve unit/integration test coverage.

**Comment by janetkuo** [comment]
> @janetkuo This failure is only seen on the serial job, which isn't blocking. Apparently it takes too long to execute.

It's running in "serial" not because it takes too long, but because it won't work in parallel.

**Comment by marun** [comment]
@janetkuo Sorry if I I wasn't clear, I meant that the serial job takes too long to run pre-merge.
