### ISSUE TITLE
Oracle Coherence in kubernetes

### ISSUE THREAD

**Issue by rajeshchowdary143** [kubernetes/kubernetes#42389]
Hi  
For JAVA application, i was trying to save profile information in coherence while i was using 1JVM. After moving to docker & kubernetes, came to know that WKA helps in sharing cache between 2 java JVM'S. I was  searching on how to setup Oracle coherence cluster in k8s, so that play containers can communicate to with Coherence cluster containers to retrieve profile information by using coherence*Extended. Here i was planning to deploy coherence cache-servers as separate pods. I found some examples on how to build Oracle Coherence image, any clue if we can onboard coherence images to kubernetes.

**Comment by castrojo** [comment]
Please re-post your question to [Stack Overflow](http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support
are posted so that we can improve our efficiency in responding to your requests,
and to make it easier for you to find answers to frequently asked questions and
how to address common use cases.

We regularly see messages posted in multiple forums, with the full response
thread only in one place or, worse, spread across multiple forums. Also, the
large volume of support issues on github is making it difficult for us to use
issues to identify real bugs.

The Kubernetes team scans Stack Overflow on a regular basis, and will try to
ensure your questions don't go unanswered.

Before posting a new question, please search Stack Overflow for answers to
similar questions, and also familiarize yourself with:

  * [user documentation](http://kubernetes.io/docs/)
  * [troubleshooting guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/)

Again, thanks for using Kubernetes.

The Kubernetes Team
