### ISSUE TITLE
Can PVC show used/available size?

### ISSUE THREAD

**Issue by harryge00** [kubernetes/kubernetes#42465]
This is a FEATURE REQUEST.

Now persistent volume/persistent volume claims can display capacity. However, I am wondering if PVC can display how much of the capacity is used, and how much is left.

**Comment by kargakis** [comment]
@kubernetes/sig-storage-feature-requests

**Comment by jingxu97** [comment]
I plan to work on this feature, assign to myself.

**Comment by killy001** [comment]
does the capacity work well ? when the volume size more than the capacity, there is nothing happened, why?

**Comment by jsafrane** [comment]
@killy001, `PVC.spec.capacity` is user's request for storage, "I want 10 GiB volume". `PV.spec.capacity` is actual size of the PV. PVC can bind to a bigger PV when there is no smaller available PV, so the user can get actually more than he wants.

Similarly, dynamic provisioning works typically in bigger chunks. So if user asks for 0.5GiB in a PVC, he will get 1 GiB PV because that's the smallest one that AWS can provision.

There is nothing wrong about it.

**Comment by nesl247** [comment]
This would be really useful.

**Comment by killy001** [comment]
@jsafrane I know what you said, but i am wondering when user actually used more than the binded pv capacity,what will happened?

**Comment by jsafrane** [comment]
It's up to storage driver to decide. In case of a block volume, `write()` will probably fail. Kubernetes does not do any checking here.

**Comment by halradaideh** [comment]
this feature is needed .. !!!!
@jingxu97

**Comment by ntsh999** [comment]
this is a much required feature!

**Comment by bappr** [comment]
Is there a way to get that information programmatically using the metrics api?

**Comment by halradaideh** [comment]
well it depend on the provisioner
for example Ceph have a long workaround to get the size of the image (PV) 
i made an integration with Ceph/k8s/Prometheus here https://github.com/halradaideh/size_exporter

I think a DaemonSet replicaset, can have access to the mounted paths on each node, and simple check the size using a Linux utility like DH, then map them to the PVs..
