### ISSUE TITLE
kubectl 1.6.0-beta.1 is twice the size of kubectl-1.5.3

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#42573]
Comparing sizes indicates the size has gone from 49MB => 114MB.  Did we change the compilation options? Do the betas ship with more debug options enabled?

```
>  wget https://storage.googleapis.com/kubernetes-release/release/v1.5.3/bin/linux/amd64/kubectl -O kubectl-1.5.3
> wget https://storage.googleapis.com/kubernetes-release/release/v1.6.0-beta.1/bin/linux/amd64/kubectl -O kubectl-1.6.0-beta.1

> ls -lh
-rw-r--r-- 1 justinsb justinsb  49M Feb 15 03:51 kubectl-1.5.3
-rw-r--r-- 1 justinsb justinsb 114M Mar  2 18:57 kubectl-1.6.0-beta.1
```

**Comment by ixdy** [comment]
Looks like the `1.6.0-beta.0` kubectl was only 66M, which is a more justifiable increase (though still a lot).

Between 1.6.0-beta.0 and 1.6.0-beta.1 we went from go1.7.4 to go1.7.5.

**Comment by ixdy** [comment]
OK, it is not due to the golang version bump:
```console
$ _output/bin/kubectl version --client
Client Version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.0-alpha.0.936+d6ae61c3c9b102", GitCommit:"d6ae61c3c9b10265f29ea9963e76b90768e4739d", GitTreeState:"clean", BuildDate:"2017-03-08T00:08:30Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
$ du -h _output/bin/kubectl
114M    _output/bin/kubectl
```

**Comment by ixdy** [comment]
Happened between https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-build-1.6/3?log#log and https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-build-1.6/4?log#log:

```
I0228 23:24:12.490]   66.1 MiB  2017-03-01T07:23:31Z  gs://kubernetes-release-dev/ci/v1.6.0-beta.0.525+b877536df3c6f2/bin/linux/amd64/kubectl
```
```
I0301 14:56:35.981] 112.94 MiB  2017-03-01T22:55:54Z  gs://kubernetes-release-dev/ci/v1.6.0-beta.0.640+30dd66013dd0d3/bin/linux/amd64/kubectl
```

So something in https://github.com/kubernetes/kubernetes/compare/b877536...30dd660.
I'm digging at the CI build artifacts for master (`gs://kubernetes-release-dev/ci/v1.7.0-alpha.0.*`) to find a more specific commit.

**Comment by ixdy** [comment]
Search complete.
```
  70400990  2017-03-01T18:57:17Z  gs://kubernetes-release-dev/ci/v1.7.0-alpha.0.629+c713ef434d05a5/bin/linux/amd64/kubectl
 118424917  2017-03-01T19:55:15Z  gs://kubernetes-release-dev/ci/v1.7.0-alpha.0.635+cdf0cae9e4d604/bin/linux/amd64/kubectl
```

New smaller range: https://github.com/kubernetes/kubernetes/compare/c713ef434d05a5...cdf0cae9e4d604

**Comment by liggitt** [comment]
https://github.com/kubernetes/kubernetes/compare/c713ef434d05a5...cdf0cae9e4d604#diff-095754adfdcb15cae5584c79c20510e0 massively increases the import tree of the apiserver

**Comment by ixdy** [comment]
@kubernetes/release-team fyi

**Comment by smarterclayton** [comment]
Yikes, that is a serious problem.  pkg/api/validation should *not* import
every volume plugin implementation.

We need to either find a way to snip the dependencies or revert mount
options.

This is a pretty serious regression in size, not only a layering violation.

On Mar 7, 2017, at 8:05 PM, Jeff Grafton <notifications@github.com> wrote:

@kubernetes/release-team
<https://github.com/orgs/kubernetes/teams/release-team> fyi

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/42573#issuecomment-284912772>,
or mute the thread

**Comment by gnufied** [comment]
I am looking at options what we can do. The reason volume plugins are getting imported in api server is because - we wanted to do a creation time validation of PVs and whether underlying volume plugin supports mount options (there are many that don't).

**Comment by smarterclayton** [comment]
If you need to do that, create a sub package with just that code, no
external dependencies.

We really can't have "dynamic" plugins in the API code, it's a locked API.

On Mar 7, 2017, at 10:02 PM, Hemant Kumar <notifications@github.com> wrote:

I am looking at options what we can do. The reason volume plugins are
getting imported in api server is because - we wanted to do a creation time
validation of PVs and whether underlying volume plugin supports mount
options (there are many that don't).

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/42573#issuecomment-284932591>,
or mute the thread

**Comment by gnufied** [comment]
There are couple of options I am thinking:

1. Define new subpackage that contains PV validation code and plugin imports and directly call that function via https://github.com/kubernetes/kubernetes/blob/master/pkg/registry/core/persistentvolume/strategy.go#L56 hooks. These are the entry points from where `validation.ValidateXXX` methods are called anyways. 

2. We can drop creation time validation of mount options for PVs altogether. 

I am thinking I will go with option#1 and open a follow up PR.

**Comment by gnufied** [comment]
@smarterclayton I still don't quite get what you mean by we can't have "dynamic" plugins in the API. These volume plugins aren't dynamic and they don't change API interface in anyway. The mount option is merely an annotation .The only thing they can "potentially" change is - whether a PV type will accept mount options or not. 

Having said that,  I didn't expect kubectl to import `api/validation`. :( 
I looked at decoupling validations required in CLI and validation required in server side. They seem to be tangled and any such refactoring will require larger work.

**Comment by smarterclayton** [comment]
Splitting your validation into separate packages is what I would recommend.

Validation happens on the server, not on the client.  The client validation
is a swagger schema validation, which is based on the server side document
generated by swagger.  We will eventually break client validations away,
but it's tied into other changes.

I consider this a release-blocker at this point since this is a significant
regression for all client libraries picking up pkg/api.

**Comment by saad-ali** [comment]
@gnufied Let's drop creation time validation of mount options for PVs for this (1.6) release, that'll get rid of the dependencies in API server, and open an issue to reimplement them without importing the full dependency tree in v1.7 (as @smarterclayton suggested, maybe multiple packages, we'll need to think about it).

**Comment by gnufied** [comment]
Okay I have removed creation time validation of mount options for now - https://github.com/kubernetes/kubernetes/pull/42706

Follow up issue is here for 1.7  - https://github.com/kubernetes/kubernetes/issues/42707 . @saad-ali please assign the issue to me.

**Comment by calebamiles** [comment]
Added your PR to the 1.6 milestone @gnufied.

**cc: @ethernetdan, @kubernetes/release-team, @kubernetes/kubernetes-release-managers**

**Comment by gnufied** [comment]
@calebamiles thank you. 

Just to make it clearer, I have opened two PRs to fix this problem.

1. https://github.com/kubernetes/kubernetes/pull/42706 -- which simply drops creation time validation of mount options to avoid referring volume plugins in `pkg/api/validation`. 
2. https://github.com/kubernetes/kubernetes/pull/42750 -- which splits the packaging such that, mount option validation is removed from `pkg/api/validation`. We are still doing the validation of mount options when user tries to create PV but we do this via new package. 

Spoke with @saad-ali about this.  My preference would be to merge https://github.com/kubernetes/kubernetes/pull/42750 since this way we still get to keep the validation. Waiting for approval from @smarterclayton  @justinsb @liggitt

**Comment by gnufied** [comment]
We ended up not merging both of above PRs, but we merged third PR I made for fixing same problem - https://github.com/kubernetes/kubernetes/pull/42811
