### ISSUE TITLE
kubelet failed to record some events.

### ISSUE THREAD

**Issue by k82cn** [kubernetes/kubernetes#42701]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
bug

**Kubernetes version** (use `kubectl version`):
master

**What happened**:
```
E0306 07:26:10.013767    3385 event.go:259] Could not construct reference to: '&v1.Node{...}' due to: 'selfLink was empty, can't make reference'. Will not report event: 'Normal' 'NodeAllocatableEnforced' '       Updated Node Allocatable limit across pods'
```

**Comment by calebamiles** [comment]
could someone from @kubernetes/sig-api-machinery-misc or @kubernetes/sig-node-bugs please help with triage? Thanks!

**Comment by dchen1107** [comment]
@vishh the event is related to the NodeAllocatable, please take a look.

**Comment by pwittrock** [comment]
@k82cn Please run `kubectl version` and paste in the result.  "master" is not a Kubernetes version.

**Comment by k82cn** [comment]
@pwittrock , I found this log when investigating #42686 ; so I using branch name 'master' :). I think it should be 1.6+.

**Comment by k82cn** [comment]
Append node infos, it seems UID is also empty:


E0306 07:26:10.013767    3385 event.go:259] Could not construct reference to: '&v1.Node{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""},     ObjectMeta:v1.ObjectMeta{Name:"bootstrap-e2e-minion-group-sh51", GenerateName:"", Namespace:"", SelfLink:"", UID:"", ResourceVersion    :"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(    nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string{"beta.kubernetes.io/instance-type":"n1-standard-2", "failure    -domain.beta.kubernetes.io/zone":"us-central1-f", "failure-domain.beta.kubernetes.io/region":"us-central1", "beta.kubernetes.io/os":"    linux", "beta.kubernetes.io/arch":"amd64", "alpha.kubernetes.io/fluentd-ds-ready":"true", "kubernetes.io/hostname":"bootstrap-e2e-min    ion-group-sh51", "agent-light-10":""}, Annotations:map[string]string{"volumes.kubernetes.io/controller-managed-attach-detach":"true"}    , OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:""}, Spec:v1.NodeSpec{PodCIDR:"", ExternalID:"51070    54328687931504", ProviderID:"gce://kubernetes-jkns-e2e-gce-serial/us-central1-f/bootstrap-e2e-minion-group-sh51", Unschedulable:false    , Taints:[]v1.Taint(nil)}, Status:v1.NodeStatus{Capacity:v1.ResourceList{"cpu":resource.Quantity{i:resource.int64Amount{value:2000, s    cale:-3}, d:resource.infDecAmount{Dec:(*inf.Dec)(nil)}, s:"", Format:"DecimalSI"}, "memory":resource.Quantity{i:resource.int64Amount{    value:7864107008, scale:0}, d:resource.infDecAmount{Dec:(*inf.Dec)(nil)}, s:"", Format:"BinarySI"}, "pods":resource.Quantity{i:resour    ce.int64Amount{value:110, scale:0}, d:resource.infDecAmount{Dec:(*inf.Dec)(nil)}, s:"", Format:"DecimalSI"}}, Allocatable:v1.Resource    List{"cpu":resource.Quantity{i:resource.int64Amount{value:2000, scale:-3}, d:resource.infDecAmount{Dec:(*inf.Dec)(nil)}, s:"", Format    :"DecimalSI"}, "memory":resource.Quantity{i:resource.int64Amount{value:7601963008, scale:0}, d:resource.infDecAmount{Dec:(*inf.Dec)(n    il)}, s:"", Format:"BinarySI"}, "pods":resource.Quantity{i:resource.int64Amount{value:110, scale:0}, d:resource.infDecAmount{Dec:(*in    f.Dec)(nil)}, s:"", Format:"DecimalSI"}}, Phase:"", Conditions:[]v1.NodeCondition{v1.NodeCondition{Type:"NetworkUnavailable", Status:    "True", LastHeartbeatTime:v1.Time{Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}}, LastTransitionTime:v1.Time{Time:time.Tim    e{sec:63624381969, nsec:996530228, loc:(*time.Location)(0x4e91740)}}, Reason:"NoRouteCreated", Message:"Node created without a route"    }, v1.NodeCondition{Type:"OutOfDisk", Status:"False", LastHeartbeatTime:v1.Time{Time:time.Time{sec:63624381970, nsec:5781404, loc:(*t    ime.Location)(0x4e91740)}}, LastTransitionTime:v1.Time{Time:time.Time{sec:63624381970, nsec:5781404, loc:(*time.Location)(0x4e91740)}    }, Reason:"KubeletHasSufficientDisk", Message:"kubelet has sufficient disk space available"}, v1.NodeCondition{Type:"MemoryPressure",     Status:"False", LastHeartbeatTime:v1.Time{Time:time.Time{sec:63624381970, nsec:5843328, loc:(*time.Location)(0x4e91740)}}, LastTrans    itionTime:v1.Time{Time:time.Time{sec:63624381970, nsec:5843328, loc:(*time.Location)(0x4e91740)}}, Reason:"KubeletHasSufficientMemory    ", Message:"kubelet has sufficient memory available"}, v1.NodeCondition{Type:"DiskPressure", Status:"False", LastHeartbeatTime:v1.Tim    e{Time:time.Time{sec:63624381970, nsec:5858974, loc:(*time.Location)(0x4e91740)}}, LastTransitionTime:v1.Time{Time:time.Time{sec:6362    4381970, nsec:5858974, loc:(*time.Location)(0x4e91740)}}, Reason:"KubeletHasNoDiskPressure", Message:"kubelet has no disk pressure"},     v1.NodeCondition{Type:"Ready", Status:"False", LastHeartbeatTime:v1.Time{Time:time.Time{sec:63624381970, nsec:5874905, loc:(*time.Lo    cation)(0x4e91740)}}, LastTransitionTime:v1.Time{Time:time.Time{sec:63624381970, nsec:5874905, loc:(*time.Location)(0x4e91740)}}, Rea    son:"KubeletNotReady", Message:"container runtime is down,PLEG is not healthy: pleg was last seen active 2562047h47m16.854775807s ago    ; threshold is 3m0s,network state unknown"}}, Addresses:[]v1.NodeAddress{v1.NodeAddress{Type:"InternalIP", Address:"10.240.0.5"}, v1.    NodeAddress{Type:"ExternalIP", Address:"146.148.66.23"}, v1.NodeAddress{Type:"Hostname", Address:"bootstrap-e2e-minion-group-sh51"}},     DaemonEndpoints:v1.NodeDaemonEndpoints{KubeletEndpoint:v1.DaemonEndpoint{Port:10250}}, NodeInfo:v1.NodeSystemInfo{MachineID:"", Syst    emUUID:"0C3E9175-B5A0-F5AB-D1C8-D26CFE2E8639", BootID:"39fc8721-1f50-4b42-a044-c693e3f0ecea", KernelVersion:"3.16.0-4-amd64", OSImage    :"Debian GNU/Linux 7 (wheezy)", ContainerRuntimeVersion:"docker://1.11.2", KubeletVersion:"v1.7.0-alpha.0.849+df70b30e59b5da", KubePr    oxyVersion:"v1.7.0-alpha.0.849+df70b30e59b5da", OperatingSystem:"linux", Architecture:"amd64"}, Images:[]v1.ContainerImage{v1.Contain    erImage{Names:[]string{"gcr.io/google_containers/kube-proxy:ccb1e93b18593cec918935ec091a0cd7"}, SizeBytes:109638053}, v1.ContainerIma    ge{Names:[]string{"gcr.io/google_containers/pause-amd64:3.0"}, SizeBytes:746888}}, VolumesInUse:[]v1.UniqueVolumeName(nil), VolumesAt    tached:[]v1.AttachedVolume(nil)}}' due to: 'selfLink was empty, can't make reference'. Will not report event: 'Normal' 'NodeAllocatab    leEnforced' 'Updated Node Allocatable limit across pods'

**Comment by k82cn** [comment]
Here's the root cause: this event was triggered in `kl.initializeModules`, but the nodeInfo(`v1.Node`) was update in `kl.syncNodeStatus` after `kl.syncNodeStatus` in other go routine. So the SelfLink maybe not set. Created a PR for this, @vishh , any suggestion on the solution? I'm going to do more check on the impact.

**Comment by ethernetdan** [comment]
@k82cn @dchen1107 @vishh Is this a release blocker for 1.6? Please decide by EOD

**Comment by vishh** [comment]
@k82cn your approach to fix this is sound. Adding comments on your PR.

**Comment by k82cn** [comment]
@ethernetdan , this's NOT a release blocker to me, as the impact is low: the events maybe not updated because of race condition. @vishh , please help to double confirm.

**Comment by tristanls** [comment]
Hello, I am observing the same error when I start `kubelet`. I noticed that this was marked as not a release blocker, but I am curious if the following sequence of events is causal and valid? 

0. `$ kubelet ... --network-plugin=kubenet ...` and `$ kube-controller-manager ... --allocate-node-cidrs=true ... --cluster-cidr=$CLUSTER_CIDR ... `
1. `kubelet` fails to record the events listed in the error message (as reported in this issue).
2. `kubelet` is not allocated a PodCIDR from `kube-controller-manager`.
3. `kubelet` cannot configure networking (i.e. cluster does not work).

**Comment by tristanls** [comment]
I just ran an experiment where (it seems to me) I confirmed this issue is preventing a cluster configured in my scenario above from ever working.

In my experiment I created a patched build of `kubelet` using the changes from #42939 committed on top of source code checked out at tag `v1.6.1`.

After deploying a node that uses the patched `kubelet`, it successfully records the event (registers the Node), it is then assigned a PodCIDR, which then allows it to configure networking.

I hope this info is useful.

**Comment by k82cn** [comment]
@tristanls , thanks very much for your verification. That maybe my miss on the usage of that event to make it `non-release-blocker`. Anyway, I'll ping approver to get that PR merged; and dig why it impacts cluster configuration.

**Comment by luckyruruguo** [comment]
This bug isn't fixed now, right?

**Comment by anilreddyv** [comment]
We are having same issue with version v1.6.2, do we know to which version the fix is merged? 

May 26 23:54:03 ar-master-k8-02 kubelet: E0526 23:54:03.462871   14883 event.go:259] Could not construct reference to: '&v1.Node{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"ar-master-k8-02", GenerateName:"", Namespace:"", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string{"beta.kubernetes.io/os":"linux", "beta.kubernetes.io/arch":"amd64", "kubernetes.io/hostname":"ar-master-k8-02", "node-role.kubernetes.io/master":"true"}, Annotations:map[string]string{"volumes.kubernetes.io/controller-managed-attach-detach":"true"}, OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:""}, Spec:v1.NodeSpec{PodCIDR:"", ExternalID:"ar-master-k8-02", ProviderID:"", Unschedulable:true, Taints:[]v1.Taint(nil)}, Status:v1.NodeStatus{Capacity:v1.ResourceList{"cpu":resource.Quantity{i:resource.int64Amount{value:1000, scale:-3}, d:resource.infDecAmount{Dec:(*inf.Dec)(nil)}, s:"", Format:"DecimalSI"}, "memory":resource.Quantity{i:resource.int64Amount{value:3975622656, scale:0}, d:resource.infDecAmount{Dec:(*inf.Dec)(nil)}, s:"", Format:"BinarySI"}, "pods":resource.Quantity{i:resource.int64Amount{value:110, scale:0}, d:resource.infDecAmount{Dec:(*inf.Dec)(nil)}, s:"", Format:"DecimalSI"}}, Allocatable:v1.ResourceList{"memory":resource.Quantity{i:resource.int64Amount{value:3358765056, scale:0}, d:resource.infDecAmount{Dec:(*inf.Dec)(nil)}, s:"", Format:"BinarySI"}, "pods":resource.Quantity{i:resource.int64Amount{value:110, scale:0}, d:resource.infDecAmount{Dec:(*inf.Dec)(nil)}, s:"", Format:"DecimalSI"}, "cpu":resource.Quantity{i:resource.int64Amount{value:900, scale:-3}, d:resource.infDecAmount{Dec:(*inf.Dec)(nil)}, s:"", Format:"DecimalSI"}}, Phase:"", Conditions:[]v1.NodeCondition{v1.NodeCondition{Type:"OutOfDisk", Status:"False", LastHeartbeatTime:v1.Time{Time:time.Time{sec:63631404962, nsec:506613277, loc:(*time.Location)(0x6f094
May 26 23:54:03 ar-master-k8-02 kubelet: 00)}}, LastTransitionTime:v1.Time{Time:time.Time{sec:63631404962, nsec:506613277, loc:(*time.Location)(0x6f09400)}}, Reason:"KubeletHasSufficientDisk", Message:"kubelet has sufficient disk space available"}, v1.NodeCondition{Type:"MemoryPressure", Status:"False", LastHeartbeatTime:v1.Time{Time:time.Time{sec:63631404962, nsec:506710600, loc:(*time.Location)(0x6f09400)}}, LastTransitionTime:v1.Time{Time:time.Time{sec:63631404962, nsec:506710600, loc:(*time.Location)(0x6f09400)}}, Reason:"KubeletHasSufficientMemory", Message:"kubelet has sufficient memory available"}, v1.NodeCondition{Type:"DiskPressure", Status:"False", LastHeartbeatTime:v1.Time{Time:time.Time{sec:63631404962, nsec:506731608, loc:(*time.Location)(0x6f09400)}}, LastTransitionTime:v1.Time{Time:time.Time{sec:63631404962, nsec:506731608, loc:(*time.Location)(0x6f09400)}}, Reason:"KubeletHasNoDiskPressure", Message:"kubelet has no disk pressure"}, v1.NodeCondition{Type:"Ready", Status:"False", LastHeartbeatTime:v1.Time{Time:time.Time{sec:63631404962, nsec:506740987, loc:(*time.Location)(0x6f09400)}}, LastTransitionTime:v1.Time{Time:time.Time{sec:63631404962, nsec:506740987, loc:(*time.Location)(0x6f09400)}}, Reason:"KubeletNotReady", Message:"container runtime is down,PLEG is not healthy: pleg was last seen active 2562047h47m16.854775807s ago; threshold is 3m0s,network state unknown"}}, Addresses:[]v1.NodeAddress{v1.NodeAddress{Type:"LegacyHostIP", Address:"10.169.237.29"}, v1.NodeAddress{Type:"InternalIP", Address:"10.169.237.29"}, v1.NodeAddress{Type:"Hostname", Address:"ar-master-k8-02"}}, DaemonEndpoints:v1.NodeDaemonEndpoints{KubeletEndpoint:v1.DaemonEndpoint{Port:10250}}, NodeInfo:v1.NodeSystemInfo{MachineID:"8e025a21a4254e11b028584d9d8b12c4", SystemUUID:"420A7EB4-83C7-CAC2-B439-C16B08AA8892", BootID:"a566e7fa-c5c9-4b32-a5d3-6b571e03f5f4", KernelVersion:"3.10.0-514.10.2.el7.x86_64", OSImage:"CentOS Linux 7 (Core)", ContainerRuntimeVersion:"docker://1.13.1", KubeletVersion:"v1.6.2+coreos.0", KubeProxyVersion:"v1.6.2+coreos.0", OperatingSystem:"linu
May 26 23:54:03 ar-master-k8-02 kubelet: x", Architecture:"amd64"}, Images:[]v1.ContainerImage(nil), VolumesInUse:[]v1.UniqueVolumeName(nil), VolumesAttached:[]v1.AttachedVolume(nil)}}' due to: 'selfLink was empty, can't make reference'. Will not report event: 'Warning' 'FailedNodeAllocatableEnforcement' 'Failed to update Node Allocatable Limits "": failed to set supported cgroup subsystems for cgroup : Failed to set config for supported subsystems : failed to write 3975622656 to memory.limit_in_bytes: write /var/lib/docker/devicemapper/mnt/3a87989b91ec0b34b965eb851af0e47036bb2037b71fc6a61132d17948283141/rootfs/sys/fs/cgroup/memory/memory.limit_in_bytes: invalid argument'

**Comment by ZhangYou0122** [comment]
same issue here for v1.6.6, is there any fix around?

E0626 19:20:38.463655   19598 event.go:259] Could not construct reference to: '&v1.Node{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"hz01-matrix-docker-0009.hz01.baidu.com", GenerateName:"", Namespace:"", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string{"beta.kubernetes.io/arch":"amd64", "kubernetes.io/hostname":"hz01-matrix-docker-0009.hz01.baidu.com", "beta.kubernetes.io/os":"linux"}, Annotations:map[string]string{"volumes.kubernetes.io/controller-managed-attach-detach":"true"}, OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:""}, Spec:v1.NodeSpec{PodCIDR:"", ExternalID:"hz01-matrix-docker-0009.hz01.baidu.com", ProviderID:"", Unschedulable:false, Taints:[]v1.Taint(nil)}, Status:v1.NodeStatus{Capacity:v1.ResourceList{"cpu":resource.Quantity{i:resource.int64Amount{value:24000, scale:-3}, d:resource.infDecAmount{Dec:(*inf.Dec)(nil)}, s:"", Format:"DecimalSI"}, "memory":resource.Quantity{i:resource.int64Amount{value:67363291136, scale:0}, d:resource.infDecAmount{Dec:(*inf.Dec)(nil)}, s:"", Format:"BinarySI"}, "pods":resource.Quantity{i:resource.int64Amount{value:110, scale:0}, d:resource.infDecAmount{Dec:(*inf.Dec)(nil)}, s:"", Format:"DecimalSI"}}, Allocatable:v1.ResourceList{"cpu":resource.Quantity{i:resource.int64Amount{value:24000, scale:-3}, d:resource.infDecAmount{Dec:(*inf.Dec)(nil)}, s:"", Format:"DecimalSI"}, "memory":resource.Quantity{i:resource.int64Amount{value:67258433536, scale:0}, d:resource.infDecAmount{Dec:(*inf.Dec)(nil)}, s:"", Format:"BinarySI"}, "pods":resource.Quantity{i:resource.int64Amount{value:110, scale:0}, d:resource.infDecAmount{Dec:(*inf.Dec)(nil)}, s:"", Format:"DecimalSI"}}, Phase:"", Conditions:[]v1.NodeCondition{v1.NodeCondition{Type:"OutOfDisk", Status:"False", LastHeartbeatTime:v1.Time{Time:time.Time{sec:63634072838, nsec:461946983, loc:(*time.Location)(0x6f2a4e0)}}, LastTransitionTime:v1.Time{Time:time.Time{sec:63634072838, nsec:461946983, loc:(*time.Location)(0x6f2a4e0)}}, Reason:"KubeletHasSufficientDisk", Message:"kubelet has sufficient disk space available"}, v1.NodeCondition{Type:"MemoryPressure", Status:"False", LastHeartbeatTime:v1.Time{Time:time.Time{sec:63634072838, nsec:462026523, loc:(*time.Location)(0x6f2a4e0)}}, LastTransitionTime:v1.Time{Time:time.Time{sec:63634072838, nsec:462026523, loc:(*time.Location)(0x6f2a4e0)}}, Reason:"KubeletHasSufficientMemory", Message:"kubelet has sufficient memory available"}, v1.NodeCondition{Type:"DiskPressure", Status:"False", LastHeartbeatTime:v1.Time{Time:time.Time{sec:63634072838, nsec:462045034, loc:(*time.Location)(0x6f2a4e0)}}, LastTransitionTime:v1.Time{Time:time.Time{sec:63634072838, nsec:462045034, loc:(*time.Location)(0x6f2a4e0)}}, Reason:"KubeletHasNoDiskPressure", Message:"kubelet has no disk pressure"}, v1.NodeCondition{Type:"Ready", Status:"False", LastHeartbeatTime:v1.Time{Time:time.Time{sec:63634072838, nsec:462055531, loc:(*time.Location)(0x6f2a4e0)}}, LastTransitionTime:v1.Time{Time:time.Time{sec:63634072838, nsec:462055531, loc:(*time.Location)(0x6f2a4e0)}}, Reason:"KubeletNotReady", Message:"container runtime is down,PLEG is not healthy: pleg was last seen active 2562047h47m16.854775807s ago; threshold is 3m0s,network state unknown"}}, Addresses:[]v1.NodeAddress{v1.NodeAddress{Type:"LegacyHostIP", Address:"10.211.177.38"}, v1.NodeAddress{Type:"InternalIP", Address:"10.211.177.38"}, v1.NodeAddress{Type:"Hostname", Address:"hz01-matrix-docker-0009.hz01.baidu.com"}}, DaemonEndpoints:v1.NodeDaemonEndpoints{KubeletEndpoint:v1.DaemonEndpoint{Port:10250}}, NodeInfo:v1.NodeSystemInfo{MachineID:"72706494018d410627f082fa00000019", SystemUUID:"00BFB3FA-259C-E211-8B2B-40F2E91B7FE0", BootID:"c26c94bf-dfeb-43fc-9046-46509bae01e7", KernelVersion:"3.10.0_3-0-0-1", OSImage:"Unknown", ContainerRuntimeVersion:"docker://1.10.2", KubeletVersion:"v1.6.6", KubeProxyVersion:"v1.6.6", OperatingSystem:"linux", Architecture:"amd64"}, Images:[]v1.ContainerImage{v1.ContainerImage{Names:[]string{"dockerimage.baidu.com/aducaros/debug:debug_integration-zhuxian-1.4.0.16-computing-release"}, SizeBytes:10930740201}, v1.ContainerImage{Names:[]string{"dockerhub.baidu.com/caros:latest"}, SizeBytes:7298503157}, v1.ContainerImage{Names:[]string{"dockerhub.baidu.com/centos:odp3"}, SizeBytes:1292289299}, v1.ContainerImage{Names:[]string{"dockerimage.baidu.com/google_containers/hyperkube:v1.6.6"}, SizeBytes:582561841}, v1.ContainerImage{Names:[]string{"dockerhub.baidu.com/xudifsd-py-hello-world:latest"}, SizeBytes:190607964}, v1.ContainerImage{Names:[]string{"dockerhub.baidu.com/with-entry:latest"}, SizeBytes:190607964}, v1.ContainerImage{Names:[]string{"dockerimage.baidu.com/google_containers/kube-apiserver:v1.6.6", "gcr.io/google_containers/kube-apiserver:06d8b21afeca619348410825b683e83b"}, SizeBytes:150650954}, v1.ContainerImage{Names:[]string{"dockerimage.baidu.com/public/ubuntu:12.04"}, SizeBytes:83561317}, v1.ContainerImage{Names:[]string{"dockerimage.baidu.com/google_containers/kube-aggregator:latest", "dockerimage.baidu.com/google_containers/kube-aggregator:v1.6.6", "gcr.io/google_containers/kube-aggregator:79d47c67f308fdde4b21f02ec6e4acb7"}, SizeBytes:56364187}, v1.ContainerImage{Names:[]string{"dockerimage.baidu.com/fission/fission-bundle:latest"}, SizeBytes:51032708}, v1.ContainerImage{Names:[]string{"dockerimage.baidu.com/fission/fission-bundle:alpha20170328"}, SizeBytes:45104772}, v1.ContainerImage{Names:[]string{"dockerhub.baidu.com/google_containers/kubernetes-dashboard-amd64:latest"}, SizeBytes:44090031}, v1.ContainerImage{Names:[]string{"dockerimage.baidu.com/public/busybox:latest"}, SizeBytes:1106304}, v1.ContainerImage{Names:[]string{"gcr.io/google_containers/pause-amd64:3.0"}, SizeBytes:746888}, v1.ContainerImage{Names:[]string{"dockerhub.baidu.com/kubernetes/pause:latest"}, SizeBytes:239840}}, VolumesInUse:[]v1.UniqueVolumeName(nil), VolumesAttached:[]v1.AttachedVolume(nil)}}' due to: 'selfLink was empty, can't make reference'. Will not report event: 'Warning' 'FailedNodeAllocatableEnforcement' 'Failed to update Node Allocatable Limits "": failed to set supported cgroup subsystems for cgroup : Failed to set config for supported subsystems : failed to write 67363291136 to memory.limit_in_bytes: write /sys/fs/cgroup/memory/memory.limit_in_bytes: invalid argument'

**Comment by k82cn** [comment]
@anilreddyv , @ZhangYou0122 the fix was not included in 1.6; if necessary, we can backmerge it.

**Comment by jbunce** [comment]
+1 for this. @k82cn will this be backmerged?

**Comment by k82cn** [comment]
ok, let me creat a backmerge pr for 1.6

**Comment by chenww** [comment]
Same issue with kubectl 1.7.2:

Capacity:
 cpu:           4
 memory:        16004820Ki
 pods:          110
Allocatable:
 cpu:           3900m
 memory:        15402420Ki
 pods:          110
System Info:
 Machine ID:                    833e0926ee21aed71ec075d726cbcfe0
 System UUID:                   EC2F249D-24B6-9EFC-DF6E-AFCF471F3D32
 Boot ID:                       4dcd9027-39e3-4f5d-a75a-6a9b909b0108
 Kernel Version:                3.10.0-514.16.1.el7.x86_64
 OS Image:                      CentOS Linux 7 (Core)
 Operating System:              linux
 Architecture:                  amd64
 Container Runtime Version:     docker://1.13.1
 Kubelet Version:               v1.7.2+coreos.0
 Kube-Proxy Version:            v1.7.2+coreos.0
ExternalID:                     weiwenmaster0
Non-terminated Pods:            (7 in total)
  Namespace                     Name                                            CPU Requests    CPU Limits      Memory Requests Memory Limits
  ---------                     ----                                            ------------    ----------      --------------- -------------
  kube-system                   fluentd-es-v1.22-9gs41                          100m (2%)       0 (0%)          200Mi (1%)      200Mi (1%)
  kube-system                   kube-apiserver-weiwenmaster0                    100m (2%)       800m (20%)      256M (1%)       2G (12%)
  kube-system                   kube-controller-manager-weiwenmaster0           100m (2%)       250m (6%)       100M (0%)       512M (3%)
  kube-system                   kube-proxy-weiwenmaster0                        150m (3%)       500m (12%)      64M (0%)        2G (12%)
  kube-system                   kube-scheduler-weiwenmaster0                    80m (2%)        250m (6%)       170M (1%)       512M (3%)
  kube-system                   nginx-ingress-controller-d6gst                  0 (0%)          0 (0%)          0 (0%)          0 (0%)
  kube-system                   weave-net-z5hwp                                 20m (0%)        60m (1%)        128M (0%)       800M (5%)
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  CPU Requests  CPU Limits      Memory Requests Memory Limits
  ------------  ----------      --------------- -------------
  550m (14%)    1860m (47%)     927715200 (5%)  5892300Ki (38%)
Events:
  FirstSeen     LastSeen        Count   From                    SubObjectPath   Type            Reason                                Message
  ---------     --------        -----   ----                    -------------   --------        ------                                -------
  10h           8s              654     kubelet, weiwenmaster0                  Warning         FailedNodeAllocatableEnforcement      Failed to update Node Allocatable Limits "": failed to set supported cgroup subsystems for cgroup : Failed to set config for supported subsystems : failed to write 16388935680 to memory.limit_in_bytes: write /var/lib/docker/overlay/778e064112d15bf671d298639c61cf1a3f2d4c4bd52ad7ae756cef7114d61d41/merged/sys/fs/cgroup/memory/memory.limit_in_bytes: invalid argument

**Comment by sokoow** [comment]
Hi All,

We're also experiencing this with 1.8.2 with docker 1.13 :
```
Failed to update Node Allocatable Limits "": failed to set supported cgroup subsystems for cgroup : Failed to set config for supported subsystems : failed to write 8201408512 to memory.limit_in_bytes: write /var/lib/docker/devicemapper/mnt/69641d63999364ce6bed9ff9a37e18922d1738df76d84db691a854f0e931e435/rootfs/sys/fs/cgroup/memory/memory.limit_in_bytes: invalid argument  
```
any updates on why this is happening on 1.8 ?

**Comment by joshuatalb** [comment]
To bump this, we're also experiencing this exact issue above ^ on a 3-node AKS cluster running k8s 1.8.7. Here's the output from `kubectl describe node <hostname>`:


```Events:
  Type     Reason                            Age               From                               Message
  ----     ------                            ----              ----                               -------
  Warning  FailedNodeAllocatableEnforcement  1m (x96 over 1h)  kubelet, aks-agentpool-10045148-3  Failed to update Node Allocatable Limits "": failed to set supported cgroup subsystems for cgroup : Failed to set config for supported subsystems : failed to write 4114153472 to memory.limit_in_bytes: write /var/lib/docker/overlay2/df563466adada9e2d5109d2d6084fa59fdf3b106cc6424b276834d7f80fa2f1e/merged/sys/fs/cgroup/memory/memory.limit_in_bytes: invalid argument
```

Is there any fixes for this?
