### ISSUE TITLE
kubeadm init discovery: Invalid value

### ISSUE THREAD

**Issue by myonlyzzy** [kubernetes/kubernetes#42703]
when I use kubeadm init  

kubeadm init 
[kubeadm] WARNING: kubeadm is in alpha, please do not use it for production clusters.
[preflight] Running pre-flight checks
[init] Using Kubernetes version: v1.5.4
discovery: Invalid value: null: exactly one discovery strategy can be provided

if I use  --discovery  what  discovery method  I can use

**Comment by calebamiles** [comment]
Could someone from @kubernetes/sig-cluster-lifecycle-bugs please help with triage? Thanks!

**Comment by jamiehannaford** [comment]
@myonlyzzy I think you specify discovery like this ([reference](https://github.com/kubernetes/kubernetes/pull/36462)):

```
$ kubeadm init --discovery token://
$ kubeadm join --discovery token://c05de9:ab224260fb3cd718@192.168.0.1:6555,191.168.0.2:6443
$ kubeadm join --discovery file:///etc/kubernetes/cluster.json
$ kubeadm join --discovery https://storage.google.apis.com/kube-discovery/98ea6e4/kubeconfig.json
```

Although I've only ever seen token discovery used for the `init` stage, since it's the default. I didn't realise you could override with other types.

@mikedanese Are any other discovery methods accepted for `init` except `token://`?

**Comment by mikedanese** [comment]
@calebamiles this appears to be a support question, not a bug.

**Comment by mikedanese** [comment]
@jamiehannaford is right but those flags will change (and become stable) in the 1.6 release.

**Comment by myonlyzzy** [comment]
Thank you guys ! I hava solved the problem by myself 。The reason of this problem is i forget disable SElinux。
