### ISSUE TITLE
Where's the log files of cluster setup by kubeadm?

### ISSUE THREAD

**Issue by wuzesheng** [kubernetes/kubernetes#42727]
Hi there,

I setup my Kubernetes cluster on CentOS 7 by kubeadm, I can view the logs via 'kubectl logs $pod -f', but I can't find the logs files either in the /var/log/containers directory or the /var/lib/docker/containers directory.  And even I searched the whole system by the system find command, there's no log file related to kubernetes pod. This is really weird.

Any suggestions?

**Comment by xilabao** [comment]
It is on the way. ref to https://github.com/kubernetes/kubernetes/pull/42470

**Comment by calebamiles** [comment]
Hello @wuzesheng thanks for asking your question! We [have been trying](https://kubernetes.io/docs/troubleshooting/) to route help/support requests to stack overflow or slack due to our large number of opened issues against the kubernetes repository. As mentioned bt @xilabao, there is an open pull request which may address your issue; please join the conversation there. Additionally [SIG Cluster Lifecycle](https://github.com/kubernetes/community/tree/master/sig-cluster-lifecycle) should be able to help you with future kubeadm issues or questions. Have a great day and closing this issue.

**Comment by wuzesheng** [comment]
@xilabao @calebamiles Got it, thanks guys:)

**Comment by nelson-cf** [comment]
Did anyone ever figure out how kubeadm is handling container logs and the approach to ship them?  It appears to do something different than every other cluster management solution.

**Comment by nelsonfassis** [comment]
I have the same problem @nelson-cf . Documentation from filebeat doesn't seem to be compatible with however logs works on kubeadm and I can't find a work around. Did you?

**Comment by nelsonfassis** [comment]
@nelson-cf You can edit you /etc/docker/daemon.json to set its default log to json files and set a max size and max files to take care of the log rotation. After that, logs wont be written to journald and you will be able to send your log files to ES. 

{
"log-driver": "json-file",
"log-opts": {
"max-size": "9m",  # Max size of the log files.
"max-file": "5"    # The maximum number of log files that can be present.
 }
}

Hope it helps.

**Comment by nelsonfassis** [comment]
@nelson-cf You can edit you /etc/docker/daemon.json to set its default log to json files and set a max size and max files to take care of the log rotation. After that, logs wont be written to journald and you will be able to send your log files to ES. 

{
"log-driver": "json-file",
"log-opts": {
"max-size": "9m",  # Max size of the log files.
"max-file": "5"    # The maximum number of log files that can be present.
 }
}

Hope it helps.
