### ISSUE TITLE
Deployment upgrade test failed to create new replica set

### ISSUE THREAD

**Issue by krousey** [kubernetes/kubernetes#42738]
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-latest-upgrade-cluster/564

```
[k8s.io] Upgrade [Feature:Upgrade] [k8s.io] cluster upgrade should maintain a functioning cluster [Feature:ClusterUpgrade] 39m59s
go run hack/e2e.go -v -test --test_args='--ginkgo.focus=Upgrade\s\[Feature\:Upgrade\]\s\[k8s\.io\]\scluster\supgrade\sshould\smaintain\sa\sfunctioning\scluster\s\[Feature\:ClusterUpgrade\]$'
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/cluster_upgrade.go:112
Expected error:
    <*errors.errorString | 0xc4204bdd10>: {
        s: "deployment \"deployment-hash-test\" failed to create new replica set",
    }
    deployment "deployment-hash-test" failed to create new replica set
not to have occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/upgrades/deployments.go:60from junit_01.xml
```

I expect https://github.com/kubernetes/kubernetes/pull/42175 might have caused this as it was merged in the time window that this started failing.

**Comment by kargakis** [comment]
@enisoc can you please have a look? Otherwise, I'll get to it tomorrow

**Comment by enisoc** [comment]
The error occurs during the [Setup phase](https://github.com/kubernetes/kubernetes/blob/a2eac21/test/e2e/upgrades/deployments.go#L60) before the cluster is upgraded. I think this happens because the upgrade test binary is built with 1.6 code, but is running against a 1.5 cluster.

In particular, [this call](https://github.com/kubernetes/kubernetes/blob/62766c697cd1d94c4f3c5731172745f97d701a40/test/e2e/framework/util.go#L3344) filters by ControllerRef in 1.6, but the 1.5 Deployment does not set ControllerRef:

```go
newRS, err = deploymentutil.GetNewReplicaSet(deployment, c)
```

If calls like that from `deploymentutil` are used by clients like kubectl, then this could cause a problem for a user running kubectl 1.6 against a 1.5 cluster. I will look into the possible effects of that.

**Comment by kargakis** [comment]
@enisoc we can simply emulate the behavior of the helper for 1.5 by including a copy of it (w/o the owner ref check). kubectl uses those helpers as well but I think the direction is to ask users to update to the same version with the server (see the discussion in https://github.com/kubernetes/kubernetes/pull/42362 and https://github.com/kubernetes/kubernetes/issues/42392). I would expect that we document somewhere all the problems kubectl 1.5 user will face in a 1.6 cluster.

**Comment by enisoc** [comment]
@kargakis If we give up on supporting kubectl/master version skew, then this issue is only a matter of fixing the upgrade test to not expect new behavior from old clusters. Is a decision going to be made on that before 1.6 release?

If we do want to support skew, our options are:

1. Have kubectl 1.6 maintain the 1.5 behavior (don't check ControllerRef). It will do the wrong thing in the presence of overlapping selectors, both in 1.5 and 1.6 clusters.
2. Have kubectl 1.6 check ControllerRef. It will do the right thing in the presence of overlapping selectors in 1.6 clusters. It will do the wrong thing in 1.5 clusters even with no overlaps present.
3. Have kubectl 1.6 behave differently based on the cluster version it's talking to. Is there any precedent for this?

Unless option 3 is an established pattern in kubectl, I would lean towards option 1 since it only does the wrong thing in the presence of user error (overlapping selectors).

In any case, using kubectl 1.5 will do the wrong thing in the presence of overlapping selectors, even if the cluster is 1.6+.

**Comment by skriss** [comment]
@enisoc @kargakis can we at a minimum get a fix for the test in by the RC? I need a clear signal out of this test.

**Comment by enisoc** [comment]
@skriss I expect to have a PR out for this today. I'm going to try option 1 from above because I found that option 3 is not... an option.

**Comment by kargakis** [comment]
@enisoc if we won't support version skew there is no reason to do 1. Can somebody from @kubernetes/sig-cli-misc confirm that we are not going to support version skew for 1.6?

**Comment by enisoc** [comment]
@kargakis In #42392 it looks like they're only proposing at most a "strongly worded warning" against skew. If there's no programmatic guard against it, many users are still going to do it, so we should think about what's the worst damage they could do in that case.

So far, the worst I can think of is that the user tries to delete a Deployment in a 1.5 cluster with kubectl 1.6, and all the ReplicaSets are left behind because the reaper doesn't see them (because they don't have ControllerRefs). That means all the Pods are left behind too, so in essence the cascading delete failed but the client reported success.

In any case, since there is uncertainty here, I will instead focus today on just fixing the upgrade test and not changing anything in kubectl yet.

**Comment by skriss** [comment]
@enisoc will a PR for this make it into the next beta?

**Comment by enisoc** [comment]
@skriss I'm working on this now. I'm not sure when the next beta will be though since we pushed the scheduled RC. I will check with Dan.

**Comment by ethernetdan** [comment]
@enisoc @skriss let's do another beta once this merges to give it some soak time
