### ISSUE TITLE
Add a built-in addon-manager

### ISSUE THREAD

**Issue by timstclair** [kubernetes/kubernetes#42756]
Reasons to do so:
- consistency with Kubernetes production code (easier for devs to manage)
- robustness (bash isn't exactly known for being a robust production language)
- reduced base image (less CVE management overhead)
- can be built with release branch code (avoid out of date kubectl problems: https://github.com/kubernetes/kubernetes/issues/34943, https://github.com/kubernetes/kubernetes/issues/41817)

This should be a pretty straightforward implementation with the [client-go](https://github.com/kubernetes/client-go) library.

/cc @ixdy @kubernetes/sig-cluster-lifecycle-feature-requests

**Comment by frankgreco** [comment]
@timstclair could you provide a link to the current bash code?

**Comment by bgrant0607** [comment]
Before doing this, please look at:
https://docs.google.com/document/d/1XkjVm4bOeiVkj-Xt1LgoGiqWsBfNozJ51dyI-ljzt1o/edit#

cc @MrHohn @thockin

**Comment by bgrant0607** [comment]
Ref #7459

**Comment by bgrant0607** [comment]
https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/addon-manager

**Comment by frankgreco** [comment]
@bgrant0607 I just requested access to view the document

**Comment by frankgreco** [comment]
I'll start work on this

**Comment by MrHohn** [comment]
Previous discussions on https://github.com/kubernetes/kubernetes/issues/23233#issuecomment-232461242 and other comments in that thread are also worth reading :)

Relevant feature issue: kubernetes/features#18

**Comment by bgrant0607** [comment]
Relevant text from the layers doc:

We need a built-in add-on manager (not unlike static pod manifests, but at the cluster level) so that we can automatically add self-hosted components and dynamic configuration to the cluster, and so we can factor out functionality from existing components in running clusters. 

At its core would be a pull-based declarative reconciler, as provided by the current add-on manager and as described in the whitebox app management doc (also join kubernetes-dev to access):
https://docs.google.com/document/d/1S3l2F40LCwFKg6WG0srR6056IiZJBwDmDvzHWRffTWk/edit#

See the picture at the end.

I'd like the mechanism to be able to pull from at least HTTP, HTTPS (e.g., S3 or GCS), and git. 

As for how to configure where it should pull from -- that would be a namespaced API.

Where do the turtles for addons and self-hosted components end? My first instinct is component configuration, but it needs more thought, since I could easily imagine wanting to use this to pull component configuration ConfigMaps.

Where should this live? I'd say controller-manager, at least for now. 

cc @mtaufen @pwittrock @smarterclayton @philips

**Comment by bgrant0607** [comment]
See also #23233

**Comment by bgrant0607** [comment]
I'm going to close this in favor of #23233.
