### ISSUE TITLE
DNS horizontal autoscaling test error in upgrade test

### ISSUE THREAD

**Issue by skriss** [kubernetes/kubernetes#42766]
@MrHohn 

There is a test failure in the upgrade test jobs around DNS horizontal autoscaling. Can you take a look and let me know if this is an issue for the 1.6 release?

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-gci-1.5-gci-1.6-upgrade-cluster-new/18#k8sio-dns-horizontal-autoscaling-kube-dns-autoscaler-should-scale-kube-dns-pods-in-both-nonfaulty-and-faulty-scenarios

For context, this test job is creating a 1.5 cluster, upgrading it to 1.6, and then running the 1.6 E2E tests to ensure it works the same as a fresh cluster.

**Comment by MrHohn** [comment]
@skriss I took a look at the failure. Turned out the root cause is in the dns autoscaling test itself.

There is a testcase that we delete the kube-dns-autoscaler ConfigMap and see if it is re-created with the default data. But we updated the default parameters for dns-autoscaler in v1.6, so the configMap is re-created with different data, so the [assertion here](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/dns_autoscaling.go#L168) failed.

I will soon send a PR to fix the test.

**Comment by marun** [comment]
@MrHohn What's the status on this?  Should it be blocking the 1.6 release?

**Comment by MrHohn** [comment]
This is not blocking 1.6 as it is a flaw in test itself. And I sent #42773 to fix.

**Comment by marun** [comment]
@ethernetdan Please remove from 1.6
