### ISSUE TITLE
[Federation][kubefed] Not possible to disable a controller via --controllermanager-arg-overrides

### ISSUE THREAD

**Issue by marun** [kubernetes/kubernetes#42761]
#42375 promised to support disabling any of the federation controllers.  However, due to the way ``kubefed init`` marshalls overrides (splits on commas), multi-valued overrides (separated by commas) are not supported.  This means that only a single controller can be disabled. 

Support for multi-valued arg overrides was [discussed](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/40917#-Kc5FeEWRiVgtRN8Vv9t) on #40917.

cc: @kubernetes/sig-federation-bugs

**Comment by irfanurrehman** [comment]
As a bug fix, I think we can replace currently used ',' with another special character (;, :, or something else) for 1.6, but I think we might need to think more beyond 1.6.. 
Or does a dedicated argument for disabling controllers makes more sense.. ? (because the overrides argument details might end up with 2 notes, in 1.6 release notes, if we do above)

**Comment by marun** [comment]
Actually, not even a single controller can be disabled via override.   The marshalling code disallows the form that would be required (``--controllers=services=false``):

https://github.com/kubernetes/kubernetes/blob/master/federation/pkg/kubefed/init/init.go#L915

**Comment by marun** [comment]
I've updated the title to reflect the increased severity of the problem.  The following documentation provides an example that currently breaks ``kubefed init`` as per my previous comment:

https://kubernetes.io/docs/tutorials/federation/set-up-cluster-federation-kubefed/#passing-command-line-arguments-to-federation-components

**Comment by irfanurrehman** [comment]
How about using a ":" as the key:value separator.
for example:
```
--apiserver-arg-overrides="--anonymous-auth:false,--v:4" \
--controllermanager-arg-overrides="--controllers:services=false"
```
Any of you have come across, any arguments (or possibility of them in future) which might have a ":" in use.
If this sounds ok, I will raise a PR ASAP, and update the documentation too.

**Comment by perotinus** [comment]
@marun @irfanurrehman Couldn't we also fix the issue with the marshaling code? Instead of splitting on every `=`, it would scan for a comma, then split on the first `=` after that comma. The state machine is a bit more complicated, but from a user's point of view it should work as expected, whereas using colons makes for a bit of an odd experience.

For that matter, isn't there a Go library that could deal with this sort of marshaling?

**Comment by marun** [comment]
I agree with @perotinus that it would be preferable to split on the first ``=`` rather than confusing things with an additional separator character.

No code is always better, but in this case a simple parsing change should solve the problem. Unless there's already a vendored library that handles this I'm not sure it'd be worth the dependency.

**Comment by irfanurrehman** [comment]
@marun @perotinus, actually there are two issues here that need to be solved. Apologies for confusing this one with the other (multiple controllers cannot be disabled using kubefed init). I agree with perotinus, for the current issue, update the marshaling and the problem of ```=``` can be solved (if only one controller is specified).
To solve the multiple controllers problem (and still using the ```--controllermanager-arg-overrides```) needs changing the separator to another character then ```,```. To me this sounds like a viable solution because, its quite unlikely that the other separator for example ```:``` will also be used by some other argument (but very likely that ```,``` will be used by somebody else again).
One other solution, given that this is the only argument which uses both ```=``` and ```,``` in value; is a dedicated ```kubefed init``` argument for disabling controllers, but will fall flat if some other argument presents the same problem in future.

My suggestion would thus be to solve the ```=``` problem with updated marshalling and ```,``` problem replacing it to another separator (say ```:```).

**Comment by madhusudancs** [comment]
Copying my comments with context from PR #44209.

>> How is that less complex?

> More complex in terms of UX, not implementation. I think it would be simpler for the user to provide a first-class argument to kubefed vs having to remember kubefed-specific formatting for multivalued arguments.

There are pros and cons. There are the advantages that you mention here. But on the other hand

1. Every user, even the ones who don't care about these flags, has to sift through the ton of documentation that is generated for these flags.
2. Each such flag has to be dealt on a case-by-case basis. If we miss a flag in a release, there will be a window where users will have to wait for that flag to be available in `kubefed`.
3. Adds to the confusion. There are now multiple ways of providing override args. 
4. Name collision. You might have a flag with a same name for different components that mean different things. Now you need to namespace them or qualify them with the component name. In either case those names are not exactly the same as the one taken by the components and users need to learn this.

**Comment by marun** [comment]
@madhusudancs I think those justifications are largely hypothetical, and that following the principle of YAGNI would be a more likely path to usable software.

**Comment by perotinus** [comment]
@madhusudancs @nikhiljindal I'm not sure that a generic mechanism for passing parameters and having top-level arguments to kubefed are mutually exclusive. There's benefit to making common things easier to do, and still providing an escape hatch for other things.

That said, I still think the overrides passed as a flag mechanism is not a good one, and we should replace it ASAP.

**Comment by madhusudancs** [comment]
> I'm not sure that a generic mechanism for passing parameters and having top-level arguments to kubefed are mutually exclusive.

They are not mutually exclusive. But we need to be deliberate. I don't think "a flag that takes comma-separated values" qualifies to be top-level flag in kubefed.

> There's benefit to making common things easier to do, and still providing an escape hatch for other things.

But what makes this common? The argument here is not about common vs uncommon flags, but it is about flags that take comma separated values. They are two different things.

> That said, I still think the overrides passed as a flag mechanism is not a good one, and we should replace it ASAP.

This was always supposed to be a medium-term solution. The long-term solution is to use some form of structured config.

**Comment by irfanurrehman** [comment]
I think its time we explore using the config similar to what kubeadm does -> https://kubernetes.io/docs/admin/kubeadm/

As far as I understood, kubeadm allows overriding args only through config.
Earlier, we did choose to use command line args for simplicity, and if we suspect breaking users cases, by removing command line override args (given kubefed declared beta in 1.6); we can have both. Suggestions?

**Comment by perotinus** [comment]
Hmm. I'm not quite sure what the right path forward is here. If we want to get something done right now, then I think the proposed solution of using colons is the way to do that. I'm concerned that adding this will tie us to supporting it going forward, or that something in the future will require a colon and we'll have tied our hands: it's dangerous to choose an arbitrary sentinel character, because you never know when you'll need it elsewhere.

How pressing is it to fix this issue? If we can wait until we have a more integrated solution to kubefed configuration, then we will have less to maintain.

**Comment by marun** [comment]
>How pressing is it to fix this issue? If we can wait until we have a more integrated solution to kubefed configuration, then we will have less to maintain.

The docs say this is supported or 1.6, so a fix to either docs or the code is suggested.

@nikhiljindal Is this required for your work in disabling alpha features by default, so that users will have a way of enabling controllers that would otherwise be disabled?

**Comment by nikhiljindal** [comment]
> @nikhiljindal Is this required for your work in disabling alpha features by default, so that users will have a way of enabling controllers that would otherwise be disabled?

Controllers can be explicitly disabled or be disabled automatically if the corresponding API resource is disabled. My plan is to use the later. I will disable apha APIs which will automatically disable the corresponding controllers. Enabling the APIs using `--runtime-config` flag on federation-apiserver will enable the controllers.
Now I assume the same problem exists with runtime-config flag for apiserver. So they can enable one alpha API or all (runtime-config supports api/alpha=true to enable all alpha APIs at once) but not 2.

There is always the workaround to run `kubectl edit deployments federation-apiserver-deployment --namespace=federaion-system` directly and pass runtime-config flag.

**Comment by quinton-hoole** [comment]
cc @madhusudancs @perotinus as they probably need to fix this for the cluster registry reference implementation.  I'm pretty sure @irfanurrehman is not currently working on this, so unassigning.

**Comment by irfanurrehman** [comment]
This issue was labelled only for sig/multicluster and is thus moved over to kubernetes/federation#117.
If this does not seem to be right, please reopen this and notify us @kubernetes/sig-multicluster-misc.
/close
