### ISSUE TITLE
1.6 upgrade testing - [k8s.io] Kubectl client [k8s.io] Kubectl describe should check if kubectl describe prints relevant information for rc and pods [Conformance]

### ISSUE THREAD

**Issue by skriss** [kubernetes/kubernetes#42831]
@pwittrock 

The following test has been failing consistently in 1.6 upgrade testing. For context, this test job is creating a 1.5 cluster, upgrading the master to 1.6, and then running 1.5 tests against it to ensure compatibility.

/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:733
Mar  8 13:35:01.304: Failed to find BestEffort in QoS Class:	
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:1503

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-1.5-1.6-upgrade-master/4#k8sio-kubectl-client-k8sio-kubectl-describe-should-check-if-kubectl-describe-prints-relevant-information-for-rc-and-pods-conformance

Please look and determine if this is an issue for the 1.6 release. Thanks!

**Comment by skriss** [comment]
@pwittrock ping on this

**Comment by skriss** [comment]
@fabianofranz can you help route this to the appropriate person? thanks.

**Comment by ymqytw** [comment]
```
$ kubectl describe pod redis-master-00xd8 
Name:		redis-master-00xd8
Namespace:	default
Node:		kubernetes-minion-group-nt08/10.128.0.5
Start Time:	Mon, 13 Mar 2017 15:15:02 -0700
Labels:		app=redis
		role=master
Status:		Running
IP:		10.244.3.8
Controllers:	ReplicationController/redis-master
Containers:
  redis-master:
    Container ID:	docker://beb1379862dd821b92043f7995f1d816e7f232ac836a261ba9b462fcc5c2a852
    Image:		redis:2.8.23
    Image ID:		docker://sha256:481995377a044d40ca3358e4203fe95eca1d58b98a1d4c2d9cec51c0c4569613
    Port:		6379/TCP
    Requests:
      cpu:		100m
    State:		Running
      Started:		Mon, 13 Mar 2017 15:15:03 -0700
    Ready:		True
    Restart Count:	0
    Volume Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-cvlgq (ro)
    Environment Variables from:	<none>
    Environment Variables:	<none>
Conditions:
  Type		Status
  Initialized 	True 
  Ready 	True 
  PodScheduled 	True 
Volumes:
  default-token-cvlgq:
    Type:	Secret (a volume populated by a Secret)
    SecretName:	default-token-cvlgq
    Optional:	false
QoS Class:	Burstable   <--------------------- This line is expected to be BestEffort
Node-Selectors:	<none>
Tolerations:	<none>
```
@enisoc @kubernetes/sig-apps-misc Anyone know what change cause the `QoS Class` changes from `BestEffort` to `Burstable`?

**Comment by vishh** [comment]
@sjenning can you take a look at this?

**Comment by kargakis** [comment]
@ymqytw not sure if sig/apps has anything to do with resource management.

**Comment by pwittrock** [comment]
@vishh This needs to be marked as a release-blocker or moved out of the milestone.

**Comment by jessfraz** [comment]
I don't think this is a blocker it just seems like the phrasing changed? So should we patch the 1.5 tests to not run this if the server is a 1.6 version?

**Comment by jessfraz** [comment]
I dont this this should be a blocker unless that phrasing was not an intentional change

**Comment by pwittrock** [comment]
I think I know why this is failing.  In 1.6 the server started populating the status and the client was changed to read the qos from status instead of calculating it.  The test is failing in a way that makes it look like the kubectl is 1.6 and expects to read the qos from the status, and the server is 1.5 and is not populating the status.

`
Running '/workspace/kubernetes_skew/cluster/kubectl.sh --server=https://130.211.238.9 --kubeconfig=/workspace/.kube/config describe pod redis-master-bzqpj --namespace=e2e-tests-kubectl-b5zq7'
I0308 13:35:01.305] Mar  8 13:35:01.304: INFO: stderr: ""
I0308 13:35:01.305] Mar  8 13:35:01.304: INFO: stdout: "Name:\t\tredis-master-bzqpj\nNamespace:\te2e-tests-kubectl-b5zq7\nNode:\t\tbootstrap-e2e-minion-group-2mv8/10.240.0.5\nStart Time:\tWed, 08 Mar 2017 13:34:58 -0800\nLabels:\t\tapp=redis\n\t\trole=master\nAnnotations:\tkubernetes.io/created-by={\"kind\":\"SerializedReference\",\"apiVersion\":\"v1\",\"reference\":{\"kind\":\"ReplicationController\",\"namespace\":\"e2e-tests-kubectl-b5zq7\",\"name\":\"redis-master\",\"uid\":\"144f192c-0447-11...\nStatus:\t\tRunning\nIP:\t\t10.180.2.30\nControllers:\tReplicationController/redis-master\nContainers:\n  redis-master:\n    Container ID:\tdocker://2eeeccf6ff985063435a3dd5735f42da1df1cdcd6cea4cd607be2b1fc59735e7\n    Image:\t\tgcr.io/google_containers/redis:e2e\n    Image ID:\t\tdocker://sha256:e5e67996c442f903cda78dd983ea6e94bb4e542950fd2eba666b44cbd303df42\n    Port:\t\t6379/TCP\n    State:\t\tRunning\n      Started:\t\tWed, 08 Mar 2017 13:34:59 -0800\n    Ready:\t\tTrue\n    Restart Count:\t0\n    Environment:\t<none>\n    Mounts:\n      /var/run/secrets/kubernetes.io/serviceaccount from default-token-hxt78 (ro)\nConditions:\n  Type\t\tStatus\n  Initialized \tTrue \n  Ready \tTrue \n  PodScheduled \tTrue \nVolumes:\n  default-token-hxt78:\n    Type:\tSecret (a volume populated by a Secret)\n    SecretName:\tdefault-token-hxt78\n    Optional:\tfalse\nQoS Class:\t\nNode-Selectors:\t<none>\nTolerations:\t<none>\nEvents:\n  FirstSeen\tLastSeen\tCount\tFrom\t\t\t\t\t\tSubObjectPath\t\t\tType\t\tReason\t\tMessage\n  ---------\t--------\t-----\t----\t\t\t\t\t\t-------------\t\t\t--------\t------\t\t-------\n  3s\t\t3s\t\t1\tdefault-scheduler\t\t\t\t\t\t\t\tNormal\t\tScheduled\tSuccessfully assigned redis-master-bzqpj to bootstrap-e2e-minion-group-2mv8\n  2s\t\t2s\t\t1\tkubelet, bootstrap-e2e-minion-group-2mv8\tspec.containers{redis-master}\tNormal\t\tPulled\t\tContainer image \"gcr.io/google_containers/redis:e2e\" already present on machine\n  2s\t\t2s\t\t1\tkubelet, bootstrap-e2e-minion-group-2mv8\tspec.containers{redis-master}\tNormal\t\tCreated\t\tCreated container with docker id 2eeeccf6ff98; Security:[seccomp=unconfined]\n  2s\t\t2s\t\t1\tkubelet, bootstrap-e2e-minion-group-2mv8\tspec.containers{redis-master}\tNormal\t\tStarted\t\tStarted container with docker id 2eeeccf6ff98\n"
I0308 13:35:01.306] Mar  8 13:35:01.304: INFO: Failed to find BestEffort in QoS Class:	
`

**Comment by pwittrock** [comment]
Figured this out.  This is caused by the Nodes being at 1.5 - not populating the qos status - and the client at 1.6 and trying to read the qos from status.

**Comment by ymqytw** [comment]
@vishh @sjenning Will 1.6 master with 1.5 nodes function correctly in this case?

**Comment by sjenning** [comment]
@vishh @derekwaynecarr @ymqytw https://github.com/kubernetes/kubernetes/pull/38989 is the PR that switched kubectl to read QoSClass from the pod field rather than computing it.  Didn't consider a 1.6 kubectl talking to a 1.5 server at the time.  Do I need to add code to check for the 1.5 server not setting the field and fall back to computing it?

**Comment by derekwaynecarr** [comment]
@sjenning -- i think we should fall back to locally computing it if the field is not present otherwise its a regression that the field is missing.

**Comment by vishh** [comment]
Why is it a regression? Why can't the field be empty if the node cannot
populate it? The behavior would be the same for any node level features
(new fields in pod status for example)

**Comment by derekwaynecarr** [comment]
@vishh -- its a regression because we used to show the field before the change.

**Comment by skriss** [comment]
This test is still failing -- looks like now due to a minor change from "Image(s)" to "Image" (see PR 42283) -- https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-1.5-1.6-upgrade-master/28#k8sio-kubectl-client-k8sio-kubectl-describe-should-check-if-kubectl-describe-prints-relevant-information-for-rc-and-pods-conformance

cc @smarterclayton
