### ISSUE TITLE
Validating docker 1.13.x and 17.03

### ISSUE THREAD

**Issue by dchen1107** [kubernetes/kubernetes#42926]
.

**Comment by dchen1107** [comment]
xref: https://github.com/kubernetes/kubernetes/issues/40182

**Comment by ethernetdan** [comment]
@dchen1107 is this a blocker for 1.6?

**Comment by dgageot** [comment]
Hi @dchen1107, I'd like to help validate docker 1.13.x and 17.03.x. Can you help me understand what kind of validation currently runs?

**Comment by tmjd** [comment]
Is this expected to be done for k8s 1.7? With an RC cut I'm guessing probably not.

**Comment by alexbrand** [comment]
EOL for docker 1.12 is 2017-11-14 according to their [maintenance lifecycle page](https://success.docker.com/Policies/Maintenance_Lifecycle). Is this issue still active, or is there another one that is tracking the validation of newer versions of docker engine?

**Comment by yguo0905** [comment]
Yes, it's active and being tracked in this issue (if you see the attached PRs).

- The node/cluster e2e tests are running fine against the cos image with docker 1.13.
- The test for shared PID namespace has been added.
- The test for live-restore is in review and is expected to be merged today. https://github.com/kubernetes/kubernetes/pull/50277.
- The test for overlay2 is under development.
- We added benchmarks for docker 1.13 on http://node-perf-dash.k8s.io, and I will run the docker micro-benchmark tool, and provide the data.

I will have a full summary no latter than next Monday.

**Comment by alexbrand** [comment]
Thanks @yguo0905!

**Comment by tessiof** [comment]
@yguo0905 docker 17.03 ce is basically docker 1.13 with bug fixes, so I guess this version could be validated to.

**Comment by cmluciano** [comment]
@yguo0905 What was done to work around the issue of iptables rule drops as mentioned in https://github.com/kubernetes/kubernetes/issues/40182

**Comment by yguo0905** [comment]
> @yguo0905 docker 17.03 ce is basically docker 1.13 with bug fixes, so I guess this version could be validated to.

Yes, I think this version will be supported by 1.8.

> @yguo0905 What was done to work around the issue of iptables rule drops as mentioned in #40182

No new workaround is there. We use cos-m60 image on GCE for docker 1.13 validation. The cos images are already configured to drop those packages by default, so we have additional [iptables rules](https://github.com/kubernetes/kubernetes/blob/5c03d3759d7a9065b0b67b1cfb4bc8ee095cd639/cluster/gce/gci/configure-helper.sh#L84-L99) to work around the issue. So the validation is not affected by this docker change.

**Comment by tianon** [comment]
> EOL for docker 1.12 is 2017-11-14 according to their [maintenance lifecycle page](https://success.docker.com/Policies/Maintenance_Lifecycle).

I feel like it's probably important to clarify here that the EOL dates on that page are for the _commercially supported_ editions of the engine, not the open source editions.  In the open source world, 1.12 is long-past EOL, as is 1.13, and even 17.03 now that 17.06 is out.

**Comment by yguo0905** [comment]
## Docker 1.13.1 micro-benchmark result

### Benchmark Tool

https://github.com/kubernetes/contrib/tree/master/docker-micro-benchmark

### Benchmark Environment

- Cloud Provider: GCE
- VM Instance: n1-standard-2 (2 vCPUs, 7.5 GB memory)
- OS: Debian GNU/Linux 8.9 (jessie)
- Docker version:
```
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.8.1
 Git commit:   092cba3
 Built:        Thu Aug 17 02:04:05 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.8.1
 Git commit:   092cba3
 Built:        Thu Aug 17 02:04:05 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

### 1. Benchmark list/inspect with varying number of containers

`benchmark.sh -c`

- **Latency**
    - Docker 1.12.1
    ![](https://cloud.githubusercontent.com/assets/5821883/18221099/0e52f22a-712e-11e6-8635-19f4e489e351.png)
    - Docker 1.13.1
    ![latency-varies_container](https://user-images.githubusercontent.com/26879063/29542466-c873aed4-868f-11e7-9041-a92a1646d03c.png)

- **CPU Usage**
    - Docker 1.12.1
    ![](https://cloud.githubusercontent.com/assets/5821883/18221125/3980a46a-712e-11e6-96c8-20b6d6183a16.png)
    - Docker 1.13.1
    ![cpu](https://user-images.githubusercontent.com/26879063/29542524-f62eb72e-868f-11e7-921e-41ef8e04df76.png)

### 2. Benchmark list/inspect with varying operation intervals

`benchmark.sh -i`

- **`ps` [all=true] Latency**
    - Docker 1.12.1
    ![](https://cloud.githubusercontent.com/assets/5821883/18221148/76581a3a-712e-11e6-9b94-9b024990d961.png)
    - Docker 1.13.1
    ![latency-list_all](https://user-images.githubusercontent.com/26879063/29542573-32d65006-8690-11e7-8d5a-caddd2fba033.png)

- **`ps` [all=false] Latency**
    - Docker 1.12.1
    ![](https://cloud.githubusercontent.com/assets/5821883/18221155/852cbd9a-712e-11e6-8cb5-39a2c54f689c.png)
    - Docker 1.13.1
    ![latency-list_alive](https://user-images.githubusercontent.com/26879063/29542640-5587681a-8690-11e7-87e4-c6b7da997780.png)

- **`inspect` Latency**
    - Docker 1.12.1
    ![](https://cloud.githubusercontent.com/assets/5821883/18221159/8c1e51f4-712e-11e6-8a6f-c4e792887bd9.png)
    - Docker 1.13.1
    ![latency-inspect](https://user-images.githubusercontent.com/26879063/29542667-7c83055a-8690-11e7-8013-932a081139e9.png)

- **CPU Usage**
    - Docker 1.12.1
    ![](https://cloud.githubusercontent.com/assets/5821883/18221189/ca775414-712e-11e6-8778-30dfa70360b8.png)
    - Docker 1.13.1
    ![cpu](https://user-images.githubusercontent.com/26879063/29542684-9e5cd52a-8690-11e7-9ffa-6b34382fb7d5.png)

### 3. Benchmark list/inspect with varying number of goroutines

`benchmark.sh -r`

- **`ps` [all=true] Latency**
    - Docker 1.12.1
    ![](https://cloud.githubusercontent.com/assets/5821883/18221197/d936f932-712e-11e6-9592-16610275f353.png)
    - Docker 1.13.1
    ![latency-list_all](https://user-images.githubusercontent.com/26879063/29542702-c65185da-8690-11e7-88c7-13a654b3f770.png)

- **`inspect` Latency**
    - Docker 1.12.1
    ![](https://cloud.githubusercontent.com/assets/5821883/18221202/e2214a16-712e-11e6-8124-56c21c6463ca.png)
    - Docker 1.13.1
    ![latency-inspect](https://user-images.githubusercontent.com/26879063/29542729-e11917b6-8690-11e7-9d2b-b8b3b275e5bb.png)

- **CPU Usage**
    - Docker 1.12.1
    ![](https://cloud.githubusercontent.com/assets/5821883/18221205/ec88af76-712e-11e6-970e-c2b42a645d94.png)
    - Docker 1.13.1
    ![cpu](https://user-images.githubusercontent.com/26879063/29542763-0d3decd6-8691-11e7-87d7-4a48ba3f7de6.png)

### Conclusion

Docker 1.13.1 performs better than 1.12.1 in terms of both CPU usage and latency for all the operations performed by the micro-benchmark tool.


_Docker 1.12.1 results are copied from [here](https://github.com/kubernetes/kubernetes/issues/28698#issuecomment-244514829)._

**Comment by yguo0905** [comment]
### Summary

We use cos-m60 OS image for Docker 1.13.1 validation.

### Functionality

The following tests are running fine.

- Node e2e tests: [default](https://k8s-testgrid.appspot.com/cos-image-validation#e2enode-cosstable1-k8sdev-default) and [serial](https://k8s-testgrid.appspot.com/cos-image-validation#e2enode-cosstable1-k8sdev-serial).
_The "[k8s.io] Dockershim [Serial] [Disruptive] [Feature:Docker] When checkpoint file is corrupted should complete pod sandbox clean up" test failure should have nothing to do with the new docker since this test is failing [everywhere](https://k8s-testgrid.appspot.com/sig-node#kubelet-serial-gce-e2e)._

- Cluster e2e tests: [default](https://k8s-testgrid.appspot.com/cos-image-validation#e2e-gce-cosstable1-k8sdev-default), [serial](https://k8s-testgrid.appspot.com/cos-image-validation#e2e-gce-cosstable1-k8sdev-serial) and [slow](https://k8s-testgrid.appspot.com/cos-image-validation#e2e-gce-cosstable1-k8sdev-slow).

### Performance

- **Micro-benchmarks**
See the results in the [previous post](https://github.com/kubernetes/kubernetes/issues/42926#issuecomment-323882758).

- **CPU and memory usages**
We compare cos-m59 (with docker 1.11.1) and cos-m60 (with docker 1.13.1). The data is available on http://node-perf-dash.k8s.io. The runtime (docker containers) uses 12.5% more CPU in 1.13 than that in 1.11.1, and the kubelet uses slightly more memory in 1.13.
![node-perf-dash-docker](https://user-images.githubusercontent.com/26879063/29543376-8b0fd22e-8695-11e7-8acf-658d346da585.png)


### New features

- Shared PID namespace node e2e test (https://github.com/kubernetes/kubernetes/pull/49914)
- Live-restore node e2e test (https://github.com/kubernetes/kubernetes/pull/50277)
- overlay2 (TBD)

The new tests are currently running in the above node e2e test suites.

**Comment by luxas** [comment]
@yguo0905 Thank you! Is docker v1.13.x gonna be supported in v1.8?
What about overlay2, did you have time to check a status on that https://github.com/kubernetes/kubernetes/issues/32536?
It a very commonly asked-for supported feature...

Are we also aware of the https://github.com/kubernetes/kubernetes/issues/40182 issue?
cc @kubernetes/sig-node-bugs ?

**Comment by luxas** [comment]
This is a release blocker right, as 1.12 is EOL'd in November, so if this doesn't make it; v1.8 users will use a EOL docker versions before v1.9 is released?

**Comment by yguo0905** [comment]
Yes, both 1.13.x and 17.03.x will be supported in k8s 1.8.

Will take a look at https://github.com/kubernetes/kubernetes/issues/32536. But at the meantime, https://github.com/kubernetes/kubernetes/pull/51158 will enable overlay2 for node e2e tests.

**Comment by dims** [comment]
@yguo0905 - do we need to do something about https://github.com/kubernetes/kubernetes/issues/43224 for validating 1.13?

**Comment by yguo0905** [comment]
> @yguo0905 - do we need to do something about #43224 for validating 1.13?

I don't think we need to do anything here. Before they upgrade Docker to 1.13, the users should ensure that no images still use the v1 format.

**Comment by yguo0905** [comment]
> What about overlay2, did you have time to check a status on that #32536?

I've updated https://github.com/kubernetes/kubernetes/issues/42926#issuecomment-323887167 with the node e2e tests that have overlay2 enabled, andthere I don't see any issues.

**Comment by yujuhong** [comment]
> I don't think we need to do anything here. Before they upgrade Docker to 1.13, the users should ensure that no images still use the v1 format.

This should be included in the release note.

Another question: are we dropping support for docker 1.10?

**Comment by yguo0905** [comment]
> This should be included in the release note.

OK, and also https://github.com/kubernetes/kubernetes/issues/40182.

> Another question: are we dropping support for docker 1.10?

I think so, given that one k8s supports three Docker versions. So k8s 1.8 will support Docker 1.11, 1.12, 1.13 (17.03).

**Comment by dawidmalina** [comment]
Was there any changes in k8s codebase to support new docker engines or same versions should be suitable for k8s 1.6 / 1.7

**Comment by yguo0905** [comment]
> Was there any changes in k8s codebase to support new docker engines or same versions should be suitable for k8s 1.6 / 1.7

I'm personally unaware of any changes in 1.8 that are required to make Docker 1.13 (the parts that are compatible with the previous Docker versions) work, so you may run Docker 1.13 with K8s 1.6 and 1.7. However, this is not supported by the community - the fixes/workarounds for the Docker 1.13 issues may not be merged into K8s 1.6 and 1.7 branches.

**Comment by markine** [comment]
Request for background info: does the process of validating a particular Docker version + storage driver for Kubernetes include a continuous deployment use case? Does Kubernetes make any promises about the typo of work loads it supports out of the box (e.g. kube-up or kops)?

I'm asking because my recent tests of kops 1.7 +  Kubernetes 1.7.2 on AWS under CICD load (frequent container churn) showed that overlay and overlay2 drivers would fill up the root disk in just a few days. Using aufs with an Ubuntu AMI did not exhibit the issue.

**Comment by imkin** [comment]
When 17.06 is already released, why are we only limiting 1.8 to 17.03?

**Comment by luxas** [comment]
@imkin as that version is not load/scale/e2e tested, the k8s team can't promise that that version works in all cases. It _should_ and will _probably_ work, but no guarantees.

If you want to see that being supported in v1.9, feel free to help the node team perform that validation ;)

**Comment by imkin** [comment]
@luxas Thanks for responding :-) .
what do you mean by "version is not load/scale/e2e tested"? How did 17.03 become a load/scale/e2e tested? I am just trying to learn.
Thanks.

**Comment by luxas** [comment]
@imkin by that @yguo0905 ran several tests that can be found above in https://github.com/kubernetes/kubernetes/issues/42926#issuecomment-323882758 and made the e2e environment use that docker version so we can catch possible regressions related to it

**Comment by dchen1107** [comment]
We finished the qualification for both docker 1.13.x and 17.03 for k8s 1.8. The related docker dependency information in 1.8 release notes were updated. Close the issue.

**Comment by euank** [comment]
Unfortunately, at the time of the 1.8 release, `docker 17.03-ce` will not be a supported version.

Docker CE releases are only supported for a 4 month period, so 17.03 was EOL'd by August.

That means that Kubernetes still warns on every single version of docker-ce that is supported by upstream.

It seems irresponsible to recommend users use software which will not be receiving security updates.
I have no objection with e.g. GKE's container-vm or RHEL or tectonic choosing a version not updated by docker inc because they'll apply updates themselves.

However, for the open source project to recommend unsupported (aka insecure) software seems wrong to me.

I can open a new issue for 17.06/17.09 specifically, but this doesn't seem like a scaleable approach.

**Comment by luxas** [comment]
Is 1.11-1.13 receiving security updates anymore?

**Comment by tianon** [comment]
Only if you pay for the commercially supported edition.

**Comment by tianon** [comment]
Additionally, as of last night, 17.06 is no longer officially supported in the open source editions of Docker (only 17.07 and now 17.09).

**Comment by tessiof** [comment]
You can also move away from docker to cri-o or cri-containerd..

**Comment by luxas** [comment]
Which basically means it's pretty hard to keep up with that pace from k8s' PoV? All validated versions (except 1.13) seem EOL'd at this point... (1.11, 1.12, 17.03)

**Comment by euank** [comment]
@luxas all validated versions have been EOLd. 1.13 CSE ("Commercially Supported Edition") might still be supported, but that's a closed source fork of docker, not docker 1.13.

Kubernetes probably needs to just explicitly not be recommending specific versions of the engine, but rather support a version of the dockerd API.. and then test against upstream to ensure things aren't breaking.

As far as I can tell, other components (like the Linux kernel, or iptables, or cgroups) we don't declare compatibility with exact numbers, but rather with an ABI or a minimum version.

@tessiof 

> You can also move away from docker to cri-o or cri-containerd..

My complaint is about what Kubernetes marks as validated/supported.
If Kubernetes quits recommending docker entirely in favor of containerd/cri-o then I'll happily not complain about them recommending unsupported software.

**Comment by yujuhong** [comment]
Publishing the Docker API version sounds reasonable. 

On the other hand, most of the value of the Docker validation lies within discovering/fixing/working around Docker engine-version-specific bugs. I am not sure I'd compare docker to cgroups or iptables, and I think it's still valuable to publish this information in some form. 

Another thing is that we could provide an option (in dockershim) to use a specific docker API version. That way, users can continue upgrade their docker engine while staying on the same API version. Of course, they will have to deal with bugs themselves.

> If Kubernetes quits recommending docker entirely in favor of containerd/cri-o then I'll happily not complain about them recommending unsupported software.

I don't think Kubernetes recommends docker. It just *happens* to be the only feature complete, production-ready integration we have now.
Other CRI implementations are built on more stable grounds, so hopefully this gets better in the future.

**Comment by yujuhong** [comment]
FYI, I filed a new issue for using the docker API version: #53221

**Comment by roffe** [comment]
Seeing this thread and the discussion just raises the question, Why Docker at all? Should we maybe move towards another container engine that maybe follows the Kubernetes release cycle closer?

**Comment by jimmycuadra** [comment]
@roffe That’s what projects like cri-o, cri-containerd, and rktlet are working towards. They’re just not as mature as Docker at this point. (You’ll find all three projects under the kubernetes-incubator GitHub org.)

**Comment by imkin** [comment]
How long does kubernetes support its releases?

**Comment by wkornewald** [comment]
What speaks against following Docker via shorter patch release cycles?

**Comment by roffe** [comment]
@jimmycuadra I am partially already running RKT for my core components. but there has been some problems running it for the containers.

Regarding CRI-O i would love to test it on CoreOS but it requires me to build the OS myself from scratch to make modifications needed to include deps for CRI-O and that is over my head.

@wkornewald i would say Docker itself, it's not rare with regressions and them making breaking changes between versions.

**Comment by cpuguy83** [comment]
@roffe 

> @wkornewald i would say Docker itself, it's not rare with regressions and them making breaking changes between versions.

Speaking as a project maintainer on moby/moby, if you find a breaking change it's a bug. Please report as quickly as possible so we can get it fixed in a patch release.

**Comment by wkornewald** [comment]
@cpuguy83 
> Speaking as a project maintainer on moby/moby, if you find a breaking change it's a bug. Please report as quickly as possible so we can get it fixed in a patch release.

Would it be possible to run the (Docker-specific parts of the) Kubernetes test suite before each Docker release in order to ensure there are no breaking changes or regressions? After all, Kubernetes is an important use-case for Docker. Also, other projects building on top of Docker would surely benefit from the additional compatibility guarantees brought by the extra test suite, too.

**Comment by euank** [comment]
@wkornewald docker provides release candidates, which allows other projects (like Kubernetes) to run such tests against releases before they start breaking users.

It's rare for a project to take on the burden of running other project's tests for numerous reasons. In this case, it would be an especially large burden since running the Kubernetes test suite is so involved.

An RC period during which projects that care test and report issues is a more normal and, in my opinion, healthy way to handle that issue. The Linux Kernel is probably the most notable user of that model, and it works fairly well for them.

I would much rather argue that the Kubernetes project, or possibly community, should consume docker-ce RCs and alert them if/when regressions are found.

**Comment by boonyasukd** [comment]
Now that Docker Enterprise announced Kubernetes as [an officially supported orchestration platform](https://blog.docker.com/2017/10/docker-enterprise-edition-kubernetes/) besides Swarm, wouldn't it mean it's in the best interest of Docker Inc. to work on test suites & regression tests to ensure smooth integration as well? I presume Docker Inc. and/or their Enterprise customers will probably want to run Kubernetes with latest Docker version instead of being stuck with the past/patched Docker versions indefinitely.

**Comment by yujuhong** [comment]
> I would much rather argue that the Kubernetes project, or possibly community, should consume docker-ce RCs and alert them if/when regressions are found.

I'd love to see the community pick up the work validating Docker RCs and report issues. I think that's orthogonal to validating Docker (in kubernetes) against a fixed API version (#53221).

> Now that Docker Enterprise announced Kubernetes as an officially supported orchestration platform besides Swarm, wouldn't it mean it's in the best interest of Docker Inc. to work on test suites & regression tests to ensure smooth integration as well? I presume Docker Inc. and/or their Enterprise customers will probably want to run Kubernetes with latest Docker version instead of being stuck with the past/patched Docker versions indefinitely.

I have no clue how Docker plans to validate Kubernetes releases. Perhaps @cpuguy83 can provide some insight?

**Comment by cpuguy83** [comment]
I couldn't comment on immediate plans (beta hasn't started yet), but definitely expect to see kubernetes running on top of containerd directly as part of the (Docker) platform instead of sitting on top of it.

containerd, once out of beta, will be a much more stable base (much smaller scope) and have much longer support cycle (https://github.com/containerd/containerd/blob/master/RELEASES.md#support-horizon)
See https://github.com/kubernetes-incubator/cri-containerd/ for this integration work.

containerd is already being tested with kube node e2e tests: https://k8s-testgrid.appspot.com/sig-node-containerd, more work to be done for cluster e2e tests (so I'm told).

**Comment by bamb00** [comment]
Hi, I'm trying to locate documentation from kubernetes that recommends running kubernetes 1.8.x or 1.9.x with certain docker version on CentOS 7.4 or Ubuntu 16.04.

**Comment by marcellodesales** [comment]
@bamb00 looking for the same...

**Comment by dawidmalina** [comment]
Check https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.9.md section: External Dependencies.

But to be honest we are using docker ce 17.06.x and it's working ok for us.

**Comment by bamb00** [comment]
What is the preferred storage driver used with Kubernetes 1.9.x in a production environment for CentOS and RHEL? Docker listed the preferrable storage driver is overlay2 but I would like to hear from the user what is being use and why.

Thanks in Advance.
