### ISSUE TITLE
Standardize/cleanup timeouts in Go e2e tests

### ISSUE THREAD

**Issue by roberthbailey** [kubernetes/kubernetes#4292]
From @zmerlynn in #4269 

We now have three timeout mechanisms that I know of in the system

- There's this one, which is actually nice because it's "true". 
- There's this one: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/test/e2e/util.go#L43 (which uses the "sleep and add up the sleeps" method). 
- And then when I was porting Brendan's endpoints test, I gutted his goroutine based individual timeouts and actually forced the test into a full test timeout: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/test/e2e/service.go#L248 (which is the combination of that timeout and the "done Done" on the function signature).

I can't decide if we want fine-grained timeouts for individual actions or to just go through and profile whole tests, honestly. We probably want some combination of both.

**Comment by zmerlynn** [comment]
I did some testing last week with the last form of timeout (the ginkgo native timeout). As is probably obvious, the biggest issue we're going to have is that any test that is using the `defer SomeCleanupFunc(someResource)` pattern to do a leaf cleanup at the end of the test is going to have issues, because Ginkgo, as it should, shoots the whole goroutine in the head and the defers never run.

Given that, I think the right approach is actually the following:
* Each API action, or state loop should have an associated fine-grained timeout
* Each test should have a full test timeout
* Each test should be tolerant of its own resources being still around when it starts (i.e. before it tries to create `foo`, it should test for `foo` and delete it)
* Jenkins should keep its full e2e run timeout (for "someone violated these rules")

This bug should be an umbrella to getting us there. I propose that the existing shell tests be ignored for this bug.

**Comment by satnam6502** [comment]
Personally, I think you should never create a resource called "foo" in e2e tests -- you should make a unique name for it by suffixing it with a string from the UUID library. That makes the test even more resilient to failed cleanup and allows multiple instances of the test to run in parallel.

**Comment by zmerlynn** [comment]
Agreed. Changing my comment to match.

**Comment by zmerlynn** [comment]
cc @quinton-hoole
