### ISSUE TITLE
Add service annotation for AWS ELB zones so tagging subnets is not required.

### ISSUE THREAD

**Issue by michaelajr** [kubernetes/kubernetes#42957]
**Is this a request for help?**:
No

**What keywords did you search in Kubernetes issues before filing this one?**:
aws, elb, subnets

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Feature request

Currently AWS subnets need to be tagged with `KubernetesCluster` to have ELBs correctly include all the zones in a multi-zone cluster. This is problematic when bringing your own VPC/subnets as it is not desirable to have them tagged as part of the resources owned by K8S. I know there is work going on to create a new tagging scheme which will allow multiple clusters to be in a VPC and share resources, but I wonder why tagging is needed at all in this case since an annotation could be used:

```service.beta.kubernetes.io/aws-load-balancer-subnets: "subnet-xxxxxxxx,subnet-xxxxxxxx,subnet-xxxxxxxx"```

This would allow people to stand up their cluster in an existing VPC without needing to tag their subnets, which might be dangerous when tools like kops go to delete the cluster.

**Comment by kenden** [comment]
It's better than having to modify existing subnets. 
But this make life more complicated for users/developers. Now they need to know which subnets they want to use, instead of just adding this annotation on the service config:
`service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0`
That annotation works on all clusters.

Couldn't we just check on which subnets the workers are and use those?

**Comment by michaelajr** [comment]
Interesting. Yeah. I suppose the logic there is that unlike a typical AWS Ec2 deployment where the application is launching into subnets via an *app-specific* ASG, the application is just launching onto K8s, and the knowledge of what subnets the nodes are in is held by the K8s cluster itself (and maybe the cluster creation tool, like `kops`). Therefore forcing the application deployment yaml to know about this adds a burden. Makes sense.

**Comment by kenden** [comment]
Right. maybe if a service it created in kube-system it should use the controllers' subnets. 
Else, the workers.

**Comment by kenden** [comment]
I just created a new cluster with Kops 1.6.1 without any tags on the existing subnets and my ELB registered to all subnets. The ELB has the tags:
`KubernetesCluster: k8s.prod.eu-central-1.redacted.net`
`kubernetes.io/cluster/k8s.prod.eu-central-1.redacted.net: owned`
This new tag `kubernetes.io/cluster/...`, from [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/aws/tags.go#L30) seems to have helped.

**Comment by michaelajr** [comment]
Which ELB? The API ELB, or a Service ELB?

**Comment by kenden** [comment]
@michaelajr a service ELB

**Comment by izakp** [comment]
What would be the expected behavior if the cluster in a hybrid network topology, i.e. nodes exist in both private and public subnets?  It would follow that when creating an internet-facing service ELB, you would want to attach the ELB to only those nodes in public subnets, and when creating an internal service ELB you would want to attach the ELB to nodes only in private subnets, no?  I am currently able to create "internal" ELBs that get registered to public subnets, and this is not quite correct. See: https://github.com/kubernetes/kops/issues/1142#issuecomment-314359041
