### ISSUE TITLE
GCE 1.5->1.6 upgrade testing: CronJob - the server could not find the expected resource

### ISSUE THREAD

**Issue by skriss** [kubernetes/kubernetes#43023]
@soltysh, please take a look ASAP and let me know if this is a 1.6 blocker or not.

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-1.5-1.6-upgrade-cluster/19#k8sio-cronjob-should-not-emit-unexpected-warnings

On GCE, in the 1.5->1.6 upgrade-cluster job (which creates a 1.5 cluster, upgrades to 1.6, then runs 1.5 E2E tests), the CronJob tests are failing with 

```
Expected error:
    <*errors.StatusError | 0xc422657180>: {
        ErrStatus: {
            TypeMeta: {Kind: "", APIVersion: ""},
            ListMeta: {SelfLink: "", ResourceVersion: ""},
            Status: "Failure",
            Message: "the server could not find the requested resource",
            Reason: "NotFound",
            Details: {Name: "", Group: "", Kind: "", Causes: nil, RetryAfterSeconds: 0},
            Code: 404,
        },
    }
    the server could not find the requested resource
not to have occurred
```

**Comment by soltysh** [comment]
@skriss as part of https://github.com/kubernetes/kubernetes/pull/41890 I removed everything from `batch/v2alpha1` which was not new, including Jobs. The test in 1.5 were configured in such a way (due to problems with discovery mechanisms at the time) to always use `batch/v2alpha1.Job` endpoint, which does not exists in 1.6. So this is an expected error when running 1.5 e2e against 1.6 cluster. [This particular change](https://github.com/kubernetes/kubernetes/pull/41890/commits/6c0cd2486556f71bb9d0acdfae576600c7c633db#diff-699bca1718c4c9b5d1acf7bbe7549860R52) fixed this problem in 1.6. This is not a release blocker.

**Comment by ethernetdan** [comment]
We should find a way to quiet this false positive but agreed not a release blocker.

**Comment by soltysh** [comment]
This was rather fixing a tech-debt, but https://github.com/kubernetes/kubernetes/issues/42451 was explicitly called out, in both cases like @deads2k mentioned the filtering has to be done manually, I'm afraid.

**Comment by ethernetdan** [comment]
@idvoretskyi could you make sure we have action requireds for these compatibility breakages?

**Comment by idvoretskyi** [comment]
@ethernetdan yes, thank you for notifying.

**Comment by soltysh** [comment]
@idvoretskyi see my comment https://github.com/kubernetes/kubernetes/issues/42451#issuecomment-287037902, on a side note, we should merge these two issues since they're covering the same problem.

**Comment by enisoc** [comment]
This appears to be obsolete.
