### ISSUE TITLE
Best practice of kubernetes cluster setup to support large number of nodes/pods

### ISSUE THREAD

**Issue by gyliu513** [kubernetes/kubernetes#43043]
Hi
We're planning to use k8s as the framework as our cloud service and need to support a large number of services(pods). I'm not sure if we have any guide or best practices to setup such kind of environment, from architectural view, some related questions below:

1) Ho we can achieve best performance when deploy large amount of pods in the cluster? Say 300 nodes, each node have 30 pods, total 300*30 = 9000 pods
2) The pods creating will become slow and slow when I deploying large amount pods in one deployment, why?
3) Any performance tuning parameters we can use to have best performance for this?

Any other suggestions will be appreciated, thanks.

**Comment by tomzhang** [comment]
my suggestion is "divide  and conquer", 
1, running different services in different namespace and make a deployment step by step rather than one time deployment(for example , you can deploy the services by 10 times and one time for 100pods).

2, because all of the metadata is stored in etcd, each time you make an action for deployment which will take a  request/response action between k8s api, scheduler and controller service with etcd that we just may need to make a batch-request/batch-response tuning for this field to decrease the request/response communication.

**Comment by rata** [comment]
The users mailing list is better for these things, I think. And you will probably have way more answers.

In any case, nothing special needs to be done. Kubernetes has strict SLOs (pod creation bellow 1 second or something like that, etc.) When it says it supports an X node cluster. In 1.6 X would be 5000 nodes, so there should be no problem to handle that (with 1.5 either) as that is tested whenever it says it works with that number of nodes.

**Comment by gyliu513** [comment]
Thanks @rata and @tomzhang , will dig more for this by using different parameters, this also seems related to https://github.com/kubernetes/kubernetes/issues/9673 , close this for now.
