### ISSUE TITLE
Deployment creating became more and more slow in repeated tests

### ISSUE THREAD

**Issue by yanyanhu** [kubernetes/kubernetes#43049]
Hi, guys,

We found an issue when performing large scale deployment test repeatedly. We have a k8s cluster with about 70 worker nodes. And our test procedure is as following:

1. Creating about 2,000 deployment/pod in sequence using "kubectl run ..." command;
2. Waiting until all deployment/pod enter "running" status;
3. Cleaning all deployment/pod by running "kubectl delete deployment ..." command;
4. After all deployment/pod are eliminated, repeat step1, 2 and 3;

The image we used is "busybox", and the command to run inside docker is "httpd";

We found the first time deployment of 2,000 deployment/pod are always the fastest. It costs about 12mins in our system. However, when we perform this deployment test repeatedly, the deployment progress become more and more slow. For example, in 3rd test, the time consumption for deploying 2,000 deployment/pod could be over 20mins. 

Looks like the system was not cleaned completely before we start new test round. However, we have ensured that no pod/deployment is left in the system by checking pod list using "kubectl get pod/deployment" . We also checked the docker instance list in all worker nodes by running "docker ps -a" to ensure all docker instances have been completely removed. So we are confused about this result...

Did anyone meet the similar issue? Very appreciative for any help or hint. Thanks a lot!

Environment Configuration:
------------------------------------
- **Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.0", GitCommit:"58b7c16a52c03e4a849874602be42ee71afdcab1", GitTreeState:"clean", BuildDate:"2016-12-13T13:30:32Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.0", GitCommit:"58b7c16a52c03e4a849874602be42ee71afdcab1", GitTreeState:"clean", BuildDate:"2016-12-13T13:30:32Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}

- **Cloud provider or hardware configuration**: 4Core 8GB memory
- **OS** : SUSE Linux Enterprise Server 12 SP2
- **Kernel**: Linux n10k01 4.4.21-69-default
- **Docker info**:
Containers: 10
 Running: 10
 Paused: 0
 Stopped: 0
Images: 24
Server Version: 1.10.3
Storage Driver: btrfs
 Build Version: Btrfs v4.1.2+20151002
 Library Version: 101
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.4.21-69-default
Operating System: SUSE Linux Enterprise Server 12 SP2
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.796 GiB
Name: n10k01
ID: A64I:EV5A:YX52:GA2X:BYYO:NXE5:KEFI:JLZA:US67:OHOI:TJDD:N2XZ
WARNING: No swap limit support

**Comment by kargakis** [comment]
@kubernetes/sig-scalability-misc

**Comment by kargakis** [comment]
@kubernetes/sig-apps-misc

**Comment by kargakis** [comment]
@yanyanhu can you provide a cpu profile and --v=5 logs from the controller manager?

**Comment by timothysc** [comment]
So depending on the number of services / endpoints there are known issues there.  What I'm curious to know @ what latencies are across different areas.  

@gmarek @kensimon , this is the root of tracing + events issue(s).

**Comment by gmarek** [comment]
I'm not sure if service problems are related, as @yanyanhu didn't mention them at all. This is interesting issue, that we certainly need to investigate at some point.

@kargakis - honestly I don't think the problem is in controller manager, but we should check it either way. My guess would be some leftover cleanup work on kubelet, or something finishing work on the apiserver/etcd side. The problem is that there's currently no easy way to figure out where the problem is.

Sadly, the best way to do it would be introducing few changes to `e2e/perf/density.go`, so that it'd track times of pod startup during saturation phase (starting all pods in parallel).

Otherwise you can build your own system for tracing time spent in various phases of pod startup using events that we currently emit. It'll be far from perfect, but that's the best we can currently do...
