### ISSUE TITLE
k8s volumes nfs example not bound

### ISSUE THREAD

**Issue by minminmsn** [kubernetes/kubernetes#43120]
Hello，ALL
Step by step according to the sample：
https://github.com/kubernetes/kubernetes/blob/master/examples/volumes/nfs/README.md , but 
"SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "nfs-pv-provisioning-demo", which is unexpected".
who can tell me why ,tks!
k8s 1.5.3
centos7.3.1611

**Comment by castrojo** [comment]
Please re-post your question to [Stack Overflow]
(http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support
are posted so that we can improve our efficiency in responding to your requests,
and to make it easier for you to find answers to frequently asked questions and
how to address common use cases.

We regularly see messages posted in multiple forums, with the full response
thread only in one place or, worse, spread across multiple forums. Also, the
large volume of support issues on github is making it difficult for us to use
issues to identify real bugs.

The Kubernetes team scans Stack Overflow on a regular basis, and will try to
ensure your questions don't go unanswered.

Before posting a new question, please search Stack Overflow for answers to
similar questions, and also familiarize yourself with:

  * [user documentation](http://kubernetes.io/docs/)
  * [troubleshooting guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/)

Again, thanks for using Kubernetes.

The Kubernetes Team
