### ISSUE TITLE
[k8s.io] Dynamic provisioning [k8s.io] DynamicProvisioner Default should be disabled by * the default annotation[Slow] [Serial] [Disruptive] [Volume] {Kubernetes e2e suite}

### ISSUE THREAD

**Issue by marun** [kubernetes/kubernetes#43150]
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-serial/795/

Failed: [k8s.io] Dynamic provisioning [k8s.io] DynamicProvisioner Default should be disabled by removing the default annotation[Slow] [Serial] [Disruptive] [Volume] {Kubernetes e2e suite}

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/volume_provisioning.go:349
Expected
    <bool>: true
to equal
    <bool>: false
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/volume_provisioning.go:356
```

Failed: [k8s.io] Dynamic provisioning [k8s.io] DynamicProvisioner Default should be disabled by changing the default annotation[Slow] [Serial] [Disruptive] [Volume] {Kubernetes e2e suite}

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/volume_provisioning.go:325
Expected
    <bool>: true
to equal
    <bool>: false
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/volume_provisioning.go
```

**Comment by marun** [comment]
These test have failed in the last few serial jobs (#43092) and may represent a regression.  The tests were added in #42357 by @msau42.  Assigning her to take a look.

/assign @msau42 

cc: @kubernetes/release-team

**Comment by saad-ali** [comment]
CC @kubernetes/sig-storage-bugs @jsafrane

**Comment by msau42** [comment]
The e2e test is using IsDefaultStorageClassAnnotation, which used to equal the beta annotation, but then got changed to use the non-beta annotation.  However, the default storage classes that are installed are using the beta annotation.  So when the test tries to disable the default storage class by modifying or deleting the annotation, it is trying to use the non-beta annotation which does not exist, so it has no affect, since the the beta annotation is unchanged.

So for now, the simple fix should be to make the test modify the beta annotation.  I am working on it now and should have a PR out soon.  Longer term, the test should be able to detect which annotation is being used and modify the appropriate one.

**Comment by ethernetdan** [comment]
Looks like this is failing again with a different error:
```
Expected error:
    <*errors.StatusError | 0xc42152e880>: {
        ErrStatus: {
            TypeMeta: {Kind: "", APIVersion: ""},
            ListMeta: {SelfLink: "", ResourceVersion: ""},
            Status: "Failure",
            Message: "storageclasses.storage.k8s.io \"default\" not found",
            Reason: "NotFound",
            Details: {
                Name: "default",
                Group: "storage.k8s.io",
                Kind: "storageclasses",
                Causes: nil,
                RetryAfterSeconds: 0,
            },
            Code: 404,
        },
    }
    storageclasses.storage.k8s.io "default" not found
not to have occurred
```

**Comment by msau42** [comment]
This should be fixed by #43285

**Comment by ethernetdan** [comment]
Good to know, I'll leave open until we confirm in e2e

**Comment by liggitt** [comment]
this test went green in the last two e2e's
