### ISSUE TITLE
fluentd stuck in a bad state 

### ISSUE THREAD

**Issue by paulharter** [kubernetes/kubernetes#43288]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):no

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): fluentd logging crash

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):BUG REPORT

**Kubernetes version** (use `kubectl version`): 1.5.3

**Environment**:
- **Cloud provider or hardware configuration**: GCE
- **OS** (e.g. from /etc/os-release):Container-Optimized OS from Google
- **Kernel** (e.g. `uname -a`):4.4.21+
- **Install tools**:
- **Others**:Container Runtime Version:	docker://1.11.2

**What happened**: By mistake I flooded my logging fluentd with too many events. Understandably it didn't like this and stopped delivering them, but it is now stuck in a bad state and is unable to recover. The fluentd-cloud-logging pod seems to be out of memory and fluentd is being repeatedly restarted. The logs show it dying and restarting roughly every 12 seconds:

```
==== START logs for kube-system/fluentd-cloud-logging-gke-spate-eu-service-pool-d193a256-nz9c ====
2017-03-17 00:00:11 +0000 [error]: fluentd main process died unexpectedly. restarting.
2017-03-17 00:00:12 +0000 [warn]: 'block' action stops input process until the buffer full is resolved. Check your pipeline this action is fit or not
2017-03-17 00:00:12 +0000 [warn]: 'block' action stops input process until the buffer full is resolved. Check your pipeline this action is fit or not
```

and the node shows it has reached its memory limits:

```
 kube-system			fluentd-cloud-logging-gke-spate-eu-service-pool-d193a256-nz9c		100m (1%)	0 (0%)		200Mi (2%)	200Mi (2%)
```

I have tried deleting the pod. It was recreated ok but with the same problem.

**What you expected to happen**: I would expect fluentd to recover from receiving too many log entries, and probably drop some.

**How to reproduce it** (as minimally and precisely as possible): I haven't tried to do this.

**Anything else we need to know**:

**Comment by paulharter** [comment]
Hi @crassirostris,

I see that you came across this same bug in https://github.com/kubernetes/kubernetes/issues/32762

The problem on my servers lasted several days, which wasn't a total disaster as I'm only deploying a beta, but it was inconvenient and would be really bad in production. I'm not sure what fixed it, I guess  maybe a system upgrade in the background.  I tried 

* Deleting the pod. - It recreated but with the same issue.
* Downgrading and upgrading the k83 version on the node. Again still the same.
* Looking in the host /var/log/fluentd-buffers to see if the on file buffers were massive, they weren't.
* Found that the recommended way of flushing the fluentd buffers is by sending a SIGUSR1 signal to the process and then couldn't find a way to do this with k8s/docker

If this happens again what should I do? It there a way to recover?

I know people use logs in different ways, I feel a logging system should certainly prioritise remaining active and tailing current server output over guarantees of delivery, especially if the latter risks loss of all logging.  It should drop lines and keep going rather than buffer and crash. This is logging not a message queuing system, and there are better solutions for distributing business critical data. At the very least this prioritisation should be configurable in the GKE/stackdriver managed service. 

Are you looking at alternatives to fluentd for GKE? Unreliable logging is annoying.

Thanks

P

**Comment by crassirostris** [comment]
@paulharter There's a fix for fluentd being stuck in a bad state without any progress: https://github.com/kubernetes/kubernetes/pull/42299 . It basically removed buffers (hard way, not via signals :) ) and restarts fluentd if it hasn't made any progress for a several minutes. It will be a part of 1.5.5 I believe.

Generally, this is a known problem and a paint point. Fluentd (and ruby in general) doesn't play well with the memory constraints and we cannot lift them in a general case. The problem is worsened by the fact that in Kubernetes 1.5 fluentd is a static pod, so you cannot do anything with it, apart from manually ssh'ing to every node and chaning manifest to, for example, increase memory limit.

In 1.6 we moved fluentd to a DaemonSet, which allows to change the configuration on the fly. Also the new documentation is on the way, that will allow you to easily change fluentd parameters. You can wait for the release or try deploying fluentd as a DaemonSet into your cluster right now by following the [half-finished guide](https://github.com/crassirostris/kubernetes.github.io/blob/deploying-stackdriver-logging/docs/tasks/debug-application-cluster/logging-stackdriver.md) I'm writing, and then increase the memory limit to avoid OOMs. Note, that if you decide to try this out, you will have to recreate your cluster without cluster logging (it will only be possible to enable/disable it on the fly in 1.6), so that there is only one logging agent on the node.

> Are you looking at alternatives to fluentd for GKE? Unreliable logging is annoying.

In the near future Stackdriver will be responsible for the logging agent, with clear integration, documentation and troubleshooting guides. They have plans for replacing fluentd with fluentd-bit, which may address resource usage problem once and for all, but that's most probably not the next quarter.

If you have any questions left, feel free to ask.

/cc @piosz @igorpeshansky

**Comment by paulharter** [comment]
@crassirostris thank you for the prompt and comprehensive answer. It sounds like you have this in hand.

I'll move to 1.5.5 when its ready and wait for 1.6 to tweak the config. In the meantime I'll try not to write any more dysfunctional back off code.

Thanks

**Comment by crassirostris** [comment]
@paulharter OK. Sorry for the inconvenience with this part! Hope they will be resolved soon

**Comment by piosz** [comment]
It seems the mentioned patch missed 1.5.5, see #42299
