### ISSUE TITLE
`kubectl rollout` for overlapping deployments

### ISSUE THREAD

**Issue by janetkuo** [kubernetes/kubernetes#43321]
Forked from #43239

`kubectl rollout` commands (such as `undo` or `history`) should take deployment overlapping annotation into consideration; for example, when listing replica sets. It won't interfere with the other overlapped deployment, but may cause user confusions. 

@kargakis @kubernetes/sig-apps-bugs

**Comment by kargakis** [comment]
I don't think this is necessary especially since we are moving away from the annotation from 1.6

**Comment by adohe** [comment]
@kubernetes/sig-cli-bugs

**Comment by enisoc** [comment]
I believe this is now obsolete.

As of 1.6, the overlapping annotation is no longer used. However, in 1.6 client code we still had to support talking to 1.5 servers, and in that context it was suggested that perhaps we should take the annotation into account.

In 1.7+, we no longer need to support talking to a pre-1.6 server, and the client code already uses the full ControllerRef logic rather than 1.5-compatible logic (#43942) so it will not be confused by overlap.
