### ISSUE TITLE
gce.go is hard to test

### ISSUE THREAD

**Issue by gnufied** [kubernetes/kubernetes#43410]
So this is my somewhat naive observation that - `gce.go` is pretty hard to unit test because it is coupled with concrete implementation of `compute.Service` and `container.Service` -- which makes initializing GCECloud problematic.

I propose that - we replace those two with wrapped interfaces which can be replaced in tests. It does make code somewhat more complex  but I am open to other ideas.

cc @k8s-mirror-storage-bugs

**Comment by justinsb** [comment]
Background info:

In kops I started on a mock (AWS) cloud provider: https://github.com/kubernetes/kops/tree/master/cloudmock/aws.

And in cloudprovider/aws we also declare an interface with the subset of methods we actually use, so that we can mock them out.

I find the mock AWS cloud provider more effective, though neither is great.
