### ISSUE TITLE
cannt choose a exists load balancer(ELB) of aws

### ISSUE THREAD

**Issue by Finsico** [kubernetes/kubernetes#43438]
i want choose a exists load balancer for service(type="LoadBalancer") or config the load balancer name(default is from service.UID)

**Comment by Finsico** [comment]
support a new annotation(like `service.beta.kubernetes.io/aws-load-balancer-name`)

**Comment by justinsb** [comment]
There is a long-standing issue here: https://github.com/kubernetes/kubernetes/issues/23483

I'm going to close this in favor of that one, so that we can try to focus the conversation there.

The challenges seem to be around security (what if I specify someone else's ELB maliciously) and collisions (what happens if two services map to the same ELB accidentally)
