### ISSUE TITLE
Tag e2e tests for alpha features as such and exclude them as appropriate from upgrade testing

### ISSUE THREAD

**Issue by skriss** [kubernetes/kubernetes#43523]
Currently, there is no explicit tagging of e2e tests that exercise alpha features. Because we provide no guarantees for compatibility across k8s versions for these features, these tests frequently fail in our upgrade jobs when running some form of version-skewed testing (i.e. create a 1.5 cluster, upgrade the master to 1.6, run 1.5 E2E tests against the cluster).

We should tag any e2e tests for alpha features as such, and explicitly exclude these from the relevant upgrade test jobs to eliminate noise in the release cycles.  This will require ongoing maintenance to adjust the tags on the tests as a feature moves from alpha to beta to GA.

cc @timothysc @ethernetdan @marun

**Comment by timothysc** [comment]
Some of the root causes around failures in some of the upgrade tests were breaking compat behavior from Alpha-Beta.  Perhaps it would be easier to just skip [Alpha] tests as part of upgrade, b/c we make no guarantees across releases.?.? 

/cc @kubernetes/sig-scheduling-bugs @derekwaynecarr

**Comment by bsalamat** [comment]
+1
There are alpha features known to be incompatible. If we see failures caused by such incompatibilities, we should skip the upgrade tests. The question is that "can we find a solution, such as versioning, etc., to automatically or semi-automatically detect these incompatibilities?" By semi-automatically I mean something along the lines of tagging all the tests with the features that they test. This needs to be done once. Then we can have a master config which lists all the features. We can mark which features we expect to break in the latest upgrade. We may want to have multiple of these master configs, each for upgrading from a specific version to another. The benefit of this is that we won't need to tag tests again and again for every upgrade.
Of course, all of these are just raw ideas that came to my mind as I was typing this message. If you think there is value, we can explore this more.

**Comment by timothysc** [comment]
> The question is that "can we find a solution, such as versioning, etc., to automatically or semi-automatically detect these incompatibilities?" 

yes, just add [Alpha] to tests the exercise alpha features and add it to the ginkgo skip list.

**Comment by bsalamat** [comment]
> yes, just add [Alpha] to tests the exercise alpha features and add it to the ginkgo skip list.

Sure, but as skriss said, that would require ongoing maintenance to adjust the tags in the future.

**Comment by ConnorDoyle** [comment]
As long as it makes it into the general alpha => beta checklist, it seems pretty manageable.

**Comment by davidopp** [comment]
I think manually tagging is fine.

But I am not sure alpha always implies we break compatibility. It just means we MIGHT break compatibility.
For example, 1.5 affinity test would work against 1.6 cluster, except for the fact that we flag-gated the 1.5 behavior in 1.6 and disabled it by default, which for some other features in the future (especially ones that are not using annotations in alpha) we might not do.

So I would suggest the tag say something more specific than just "alpha" -- it should imply alpha and not expected to work in next version.

**Comment by timothysc** [comment]
> But I am not sure alpha always implies we break compatibility. It just means we MIGHT break compatibility.

It means we guarantee nothing so the tests should not be trusted outside of a release.  I think minimizing false positives on upgrade tests is our primary goal.

**Comment by ConnorDoyle** [comment]
+1

**Comment by timothysc** [comment]
I don't think anyone has started this, punting out.
