### ISSUE TITLE
Bugs in EmptyDir Teardown path

### ISSUE THREAD

**Issue by dchen1107** [kubernetes/kubernetes#43534]
While debugging a node-e2e failure on Ubuntu image, I noticed that the kublet log is full of the following error messages from: https://github.com/kubernetes/kubernetes/blob/a2c7eb275443a5afea4052094a07daf627e4a724/pkg/volume/empty_dir/empty_dir.go#L332

```
Mar 22 17:30:28 test-ubuntu-gke-1604-xenial-v20170303 kubelet[4138]: E0322 17:30:28.782993    4138 nestedpendingoperations.go:262] Operation for "\"kubernetes.io/empty-dir/49e7a02c-0f1f-11e7-888f-42010a8a0004-test-volume.deleting~35
5603580.deleting~682169602.deleting~871638708.deleting~593222404.deleting~633708239\" (\"49e7a02c-0f1f-11e7-888f-42010a8a0004\")" failed. No retries permitted until 2017-03-22 17:30:29.282751427 +0000 UTC (durationBeforeRetry 500ms)
. Error: UnmountVolume.TearDown failed for volume "kubernetes.io/empty-dir/49e7a02c-0f1f-11e7-888f-42010a8a0004-test-volume.deleting~355603580.deleting~682169602.deleting~871638708.deleting~593222404.deleting~633708239" (volume.spec
.Name: "test-volume.deleting~355603580.deleting~682169602.deleting~871638708.deleting~593222404.deleting~633708239") pod "49e7a02c-0f1f-11e7-888f-42010a8a0004" (UID: "49e7a02c-0f1f-11e7-888f-42010a8a0004") with: rename /var/lib/kube
let/pods/49e7a02c-0f1f-11e7-888f-42010a8a0004/volumes/kubernetes.io~empty-dir/test-volume.deleting~355603580.deleting~682169602.deleting~871638708.deleting~593222404.deleting~633708239 /var/lib/kubelet/pods/49e7a02c-0f1f-11e7-888f-4
2010a8a0004/volumes/kubernetes.io~empty-dir/test-volume.deleting~355603580.deleting~682169602.deleting~871638708.deleting~593222404.deleting~633708239.deleting~655544917: file exists
```

The above failure results in tons of EmptyDir volumes (including both secret and confgmap) are not properly deleted, thus test failures. cc/ @saad-ali

**Comment by saad-ali** [comment]
CC @kubernetes/sig-storage-bugs

**Comment by saad-ali** [comment]
@dchen1107 could you share the complete kubelet logs please

**Comment by dchen1107** [comment]
@saad-ali you can access the kubelet log from previous run at: https://pantheon.corp.google.com/storage/browser/canonical-kubernetes-tests/logs-gke/kubernetes-gce-e2e-node/170317055001/artifacts/

They have the same issue.

**Comment by vorlonofportland** [comment]
for the most recent test run see also https://pantheon.corp.google.com/storage/browser/canonical-kubernetes-tests/logs-gke/kubernetes-gce-e2e-node/170322163928/artifacts/

**Comment by gnufied** [comment]
Is there a link not behind a login?

**Comment by msau42** [comment]
Here is one of the errors:
Mar 17 06:20:32 vorlon-vorlon-test-e2f kubelet[3808]: E0317 06:20:32.047086    3808 nestedpendingoperations.go:262] Operation for "\"kubernetes.io/empty-dir/f6970dd1-0ad5-11e7-ae49-42010a8a0005-test-volume.deleting~627643705.deleting~484157271.deleting~226651937.deleting~672981309.deleting~979447588\" (\"f6970dd1-0ad5-11e7-ae49-42010a8a0005\")" failed. No retries permitted until 2017-03-17 06:20:32.547007598 +0000 UTC (durationBeforeRetry 500ms). Error: UnmountVolume.TearDown failed for volume "kubernetes.io/empty-dir/f6970dd1-0ad5-11e7-ae49-42010a8a0005-test-volume.deleting~627643705.deleting~484157271.deleting~226651937.deleting~672981309.deleting~979447588" (volume.spec.Name: "test-volume.deleting~627643705.deleting~484157271.deleting~226651937.deleting~672981309.deleting~979447588") pod "f6970dd1-0ad5-11e7-ae49-42010a8a0005" (UID: "f6970dd1-0ad5-11e7-ae49-42010a8a0005") with: rename /var/lib/kubelet/pods/f6970dd1-0ad5-11e7-ae49-42010a8a0005/volumes/kubernetes.io~empty-dir/test-volume.deleting~627643705.deleting~484157271.deleting~226651937.deleting~672981309.deleting~979447588 /var/lib/kubelet/pods/f6970dd1-0ad5-11e7-ae49-42010a8a0005/volumes/kubernetes.io~empty-dir/test-volume.deleting~627643705.deleting~484157271.deleting~226651937.deleting~672981309.deleting~979447588.deleting~452399049: file exists

Saad and I debugged. Our hypothesis is that:

The Rename() method for EmptyDir is first creating a directory with a new name and then tries to rename the old directory to the new name.  That os.Rename() is failing on Ubuntu because the directory already exists, which succeeds on other images.  To verify the Ubuntu issue, we can write a small test program using os.Rename() directly on the Ubuntu image.

Then the volume reconstruction logic is picking up the new directory as a new emptydir volume for the pod, which triggers another deletion round.

**Comment by saad-ali** [comment]
Some things we should improve regardless of the root cause of this:
1. The volume reconstruction logic should ignore any `.deleting~` folders (to break the explosion of directories/volumes in cases like this).
2. Improve the the default `TearDown(...)` method for `EmptyDir`:
    * Understand why it does a create directory before rename. Eliminate the create directory if possible. Otherwise make sure that the created directory is deleted if subsequent rename fails.
    * Understand why a rename is required at all before delete. Eliminate it if possible. Otherwise make sure that if delete fails, that the rename is undone.

**Comment by msau42** [comment]
BTW, in Go 1.8, it looks like they've changed the behavior of os.Rename:

https://golang.org/doc/go1.8#os

> On Unix systems, os.Rename will now return an error when used to rename a directory to an existing empty directory. Previously it would fail when renaming to a non-empty directory but succeed when renaming to an empty directory. This makes the behavior on Unix correspond to that of other systems.

So I think we should move towards eliminating the create directory.

**Comment by vorlonofportland** [comment]
On Thu, Mar 23, 2017 at 11:37:40AM -0700, Michelle Au wrote:
> BTW, in Go 1.8, it looks like they've changed the behavior of os.Rename:

> https://golang.org/doc/go1.8#os

> > On Unix systems, os.Rename will now return an error when used to rename a directory to an existing empty directory. Previously it would fail when renaming to a non-empty directory but succeed when renaming to an empty directory. This makes the behavior on Unix correspond to that of other systems.

> So I think we should move towards eliminating the create directory.

Does this mean the problem could be caused by a difference in the use of
golang 1.7 vs. golang 1.8 for k8s binary builds?

**Comment by msau42** [comment]
Yes that's possible.  From the development guide, go1.8 has not been verified for building k8s.  https://github.com/kubernetes/community/blob/master/contributors/devel/development.md

**Comment by gnufied** [comment]
related https://github.com/kubernetes/kubernetes/pull/38345

**Comment by dchen1107** [comment]
@vorlonofportland Is the test binary which generates the failures reported here is built with golang 1.8? I couldn't find those information through the existing logs.

**Comment by msau42** [comment]
From what I understand, the purpose of the rename is so that the system knows quickly that the volume has been deleted.  This is important for volumes with large content that can take a long time to delete.  So I think the right set of changes that are needed are:

1.  The volume reconstruction logic should ignore directories with ".deleting~".  I can make this change.
2.  The rename needs to be changed to not create a directory first.  It looks like #38345 is handling this.

**Comment by vorlonofportland** [comment]
On Thu, Mar 23, 2017 at 01:27:30PM -0700, Dawn Chen wrote:

> @vorlonofportland Is the test binary which generates the failures reported
> here is built with golang 1.8?  I couldn't find those information through
> the existing logs.

Yes, it is.  Should we build with golang-1.7 instead?

**Comment by vorlonofportland** [comment]
Confirmed that when building with go1.7 instead of go1.8, the node tests succeed.

**Comment by dchen1107** [comment]
Great! Thanks for the updates. We can continue carrying on our integration work. 

I am leaving this open to fix the error-prone logic in EmptyDir's teardown logic, and resolving the golang 1.8 compatibility issue.

**Comment by dims** [comment]
@dchen1107 looks like a possible dup of https://github.com/kubernetes/kubernetes/issues/36983

**Comment by louyihua** [comment]
I've encountered this issue about a month ago and now I can confirm that this issue is caused by compiling with Go 1.8, which forbids renaming a directory into an existing directory even if the destinition is empty. So the current logic that uses `TempDir()` call does not work properly under Go 1.8.
