### ISSUE TITLE
add a `kubectl shell` or `kubectl repl` command to provide an interactive REPL shell to reduce typing

### ISSUE THREAD

**Issue by jstrachan** [kubernetes/kubernetes#43617]
its common to work on the same kinds of resources quite a bit; viewing/editing/removing the same kinds of resources so you can find yourself typing quite a lot. An interactive REPL could help reduce typing.

e.g. something like:

```
foo> $ kubectl shell
mynamespace> cd ../barnamespace
barnamespace> ls
pods deploys services ...
barnamespace> cd pods
barnamespace/pods> ls foo*
foo-1234 foo-4567
barnamespace/pods> cat foo-1234
----
apiVersion: v1
kind: Pod
metadata:
  name: foo-1234
...
barnamespace/pods> rm foo-1234
pod foo-1234 deleted
barnamespace/pods> exit
foo> $
```

**Comment by jayunit100** [comment]
probably should be a proposal?

**Comment by errordeveloper** [comment]
I've experimented with some ideas around this, please checkout [`kubeplay`](https://github.com/errordeveloper/kubeplay).

**Comment by errordeveloper** [comment]
/close

As an author of `kubeplay`, I wouldn't see a good reason for this to exist in core – there are far too ways to go about implementing a REPL (e.g. syntax is probably the biggest one, there are many languages to consider).  Let's see how we can encourage the ecosystem instead of trying to look for a silver bullet!
