### ISSUE TITLE
kubectl create ingress / kubectl expose 

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#43667]
I think it would be very useful to be able to expose services via an ingress with a single command.  In particular, because ingress seems to always need a hostname, and that will always be specific to the installation.

There are two ways that immediately spring to mind to do this, and I'd appreciate some input on which is preferable before I start coding ( cc @kubernetes/sig-cli-feature-requests ) :

1. `kubectl expose service myapp  --ingress myapp.example.com --tls-acme`
1. `kubectl create ingress myapp --host myapp.example.com --tls-acme`

The second would rely on a service existing with the same name and would rely on the service port being port 80, whereas the first performs more error checking and is less magical.  But I can also appreciate how the second continues to nudge people towards a well-established pattern.

cc @aledbf for ingress

**Comment by smarterclayton** [comment]
I would say we probably want "create ingress" first, because it's easier to
say how it should work.  I don't think expose is unreasonable (openshift
uses expose for routes today) but arguments require a lot more thought.




On Mar 25, 2017, at 10:06 PM, Justin Santa Barbara <notifications@github.com>
wrote:

I think it would be very useful to be able to expose services via an
ingress with a single command. In particular, because ingress seems to
always need a hostname, and that will always be specific to the
installation.

There are two ways that immediately spring to mind to do this, and I'd
appreciate some input on which is preferable before I start coding ( cc
@kubernetes/sig-cli-feature-requests
<https://github.com/orgs/kubernetes/teams/sig-cli-feature-requests> ) :

   1. kubectl expose service myapp --ingress myapp.example.com --tls-acme
   2. kubectl create ingress myapp --host myapp.example.com --tls-acme

The second would rely on a service existing with the same name and would
rely on the service port being port 80, whereas the first performs more
error checking and is less magical. But I can also appreciate how the
second continues to nudge people towards a well-established pattern.

cc @aledbf <https://github.com/aledbf> for ingress

—
You are receiving this because you are on a team that was mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/43667>, or mute the thread

**Comment by adohe** [comment]
```
to be able to expose services via an ingress with a single command
```
I would like we add `create ingress` (another create subcommand) at first just as what @smarterclayton suggested.

**Comment by kargakis** [comment]
ref: https://github.com/kubernetes/kubernetes/issues/17429
