### ISSUE TITLE
GCE-Scalability test is flakey

### ISSUE THREAD

**Issue by anhowe** [kubernetes/kubernetes#43728]
Potentially blocking issue, #43721, was because the scalability test waits for 100 pods to come up in 600s.  The investigation shows that 100 pods takes anywhere from 200s to >600s.  Once >600, it causes the tests to failure.  Even after fix 0cb4a33, test 69 still took a full 600s to bring up 100 pods.

The ask here is to make the time to bring up 100 pods less variable, or make the time limit double what the expected max time to bring up 100 pods.

**Comment by wojtek-t** [comment]
Let's be clear here - the 0cb4a337c commit has nothing to do with this suite and it didn't cause the improvement. It was just accident.

But I took a look into recent failures and there are basically two groups of failures (all of them seem to be known):

1. image-puller is not finishing successfully (i.e. it doesn't manage to download all images it is supposed to download within the timeout). These are for example:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scalability-release-1.6/67

2. Kubelet is not starting any containers at all due to:
```
runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: could not locate kubenet required CNI plugins [bridge host-local loopback] at "/opt/cni/bin" or ""
```
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scalability-release-1.6/65

**Comment by wojtek-t** [comment]
The second one seems to be some setup issue. Though probably someone from Kubelet team can provide more info @kubernetes/sig-node-bugs @yujuhong @dchen1107

**Comment by wojtek-t** [comment]
@kubernetes/sig-scalability-test-failures @gmarek

**Comment by wojtek-t** [comment]
It seems we were doing some unexpected things regarding image-puller pods.
#43741 is fixing the (1) of what I described above.

**Comment by wojtek-t** [comment]
BTW - we are facing exactly the same issues in 1.5 release - @mwielgus FYI

**Comment by yujuhong** [comment]
> The second one seems to be some setup issue. Though probably someone from Kubelet team can provide more info @kubernetes/sig-node-bugs @yujuhong @dchen1107

The same issue that happened before: https://github.com/kubernetes/kubernetes/issues/32478

**Comment by wojtek-t** [comment]
We have switched off image prepulling completely in scalability tests this is doing the final cleanup: https://github.com/kubernetes/test-infra/pull/2872

Regarding the other issue, it seems we are in much better shape now, so closing this issue.
