### ISSUE TITLE
Release v1.6 Blocking - GCE Scalability 1.6 test grid failures

### ISSUE THREAD

**Issue by anhowe** [kubernetes/kubernetes#43721]
The GCE scalability 1.6 tests have been failing since March 25th:

https://k8s-testgrid.appspot.com/release-1.6-blocking#gce-scalability-1.6

This issue to track:
* what is the issue?
* is this blocking for v1.6?

**Comment by liggitt** [comment]
got a green run on 0cb4a337c

**Comment by anhowe** [comment]
thanks @liggitt.  It now looks like we are green on 68 and 69, so the SSD GCE fix worked.

I looked into the error logs of 65, 66, and 67 and saw the same errors of pods not coming up in enough time:
**test 65 failure:**
```
67388 I0325 16:59:02.223] Mar 25 16:59:02.222: INFO: Error waiting for all pods to be running and ready: 2 / 423 pods in namespace "kube-system" are NOT in RUNNING and READY state in 10m0s
```
**test 66 failure:**
```
I0326 05:02:57.744] Mar 26 05:02:57.744: INFO: Error waiting for all pods to be running and ready: 9 / 100 pods in namespace "kube-system" are NOT in SUCCESS state in 10m0s
```
**test 67 failure:**
```
38205 I0327 05:01:13.019] Mar 27 05:01:13.019: INFO: Error waiting for all pods to be running and ready: 5 / 100 pods in namespace "kube-system" are NOT in SUCCESS state in 10m0s
```

This does look like a flakey test since here are the results of 68 that took 210s to get all 100 pods up:
```
Mar 27 12:52:42.768: INFO: 99 / 100 pods in namespace "kube-system" are in Success state (180 seconds elapsed)
Mar 27 12:53:12.763: INFO: 100 / 100 pods in namespace "kube-system" are in Success state (210 seconds elapsed)
```

However, test 69 just barely made it and used all 600 seconds to bring up 100 pods:
```
Mar 27 16:28:56.920: INFO: 99 / 100 pods in namespace "kube-system" are in Success state (570 seconds elapsed)
Mar 27 16:29:26.919: INFO: 100 / 100 pods in namespace "kube-system" are in Success state (600 seconds elapsed)
```

From what I see here, we can close this issue, but I'll open another to make this test less flakey.

**Comment by anhowe** [comment]
filed issue https://github.com/kubernetes/kubernetes/issues/43728

**Comment by wojtek-t** [comment]
Let's be clear here - the 0cb4a337c commit has nothing to do with this suite and it didn't cause the improvement. It was just accident.

But I took a look into recent failures and there are basically two groups of failures (all of them seem to be known):

1. image-puller is not finishing successfully (i.e. it doesn't manage to download all images it is supposed to download within the timeout). These are for example:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scalability-release-1.6/67

2. Kubelet is not starting any containers at all due to:
```
runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: could not locate kubenet required CNI plugins [bridge host-local loopback] at "/opt/cni/bin" or ""
```
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scalability-release-1.6/65
