### ISSUE TITLE
svc error

### ISSUE THREAD

**Issue by timchenxiaoyu** [kubernetes/kubernetes#43799]
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"c55cf2b7d8bfeb947f77453415d775d7f71c89c2", GitTreeState:"clean", BuildDate:"2017-03-07T00:03:00Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"c55cf2b7d8bfeb947f77453415d775d7f71c89c2", GitTreeState:"clean", BuildDate:"2017-03-07T00:03:00Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}

CentOS Linux release 7.2.1511 (Core) 

two mini node,I call svc through svc ip,in one node is ok,but another is err.
I compare two iptables through iptables-save, rules are same.

**Comment by timchenxiaoyu** [comment]
curl 10.39.0.6:8080/api/v1/proxy/namespaces/kube-system/services/heapster/api/v1/model/namespaces/default/pods/busybox-1865195333-zkwtt/containers/busybox/metrics/cpu/usage
Error: 'dial tcp 192.168.67.4:8082: getsockopt: connection timed out'
Trying to reach: 'http://192.168.67.4:8082/api/v1/model/namespaces/default/pods/busybox-1865195333-zkwtt/containers/busybox/metrics/cpu/usage'[root@slave2 ~]#

[root@slave2 ~]# curl http://192.168.67.4:8082/api/v1/model/namespaces/default/pods/busybox-1865195333-zkwtt/containers/busybox/metrics/cpu/usage
{
"metrics": [
{
"timestamp": "2017-03-29T11:13:00Z",
"value": 5990209
},
{
"timestamp": "2017-03-29T11:14:00Z",
"value": 5990209
},
{
"timestamp": "2017-03-29T11:15:00Z",
"value": 5990209
}
],
"latestTimestamp": "2017-03-29T11:15:00Z"
}

**Comment by xiangpengzhao** [comment]
@timchenxiaoyu Do you use a CNI plugin or not? If not, I think you can call svc successfully in one node only if one of the backend pods is in this node. In such case, a pod is not accessible from outside of its node via pod ip.

@thockin Would you please confirm this or assign someone of sig-network guys? Correct me if I'm wrong please.

**Comment by thockin** [comment]
There's simply not enough information here to even start to debug.

Clearly, it's not systemic since it works in e2e and ~everywhere else that is established.  So it must be some local configuration issue.  I don't know what cloud you're on, what sort of network you are using, overlays, underlays, CNI, kubenet, etc.

Can you confirm that any pod on machineA can ping any pod on machineB?  That's the fundamental requirement, and seems to be failing here.  I'm going to close this for now, since it's exceedingly unlikely to be a direct problem of kubernetes, but please reopen if you have more info indicating it is something in standard setup.

**Comment by timchenxiaoyu** [comment]
sorry to response later, after I set  --cluster-cidr= to kube-proxy ,this problem solve . I use flannel vxlan network.
