### ISSUE TITLE
404 for docs link

### ISSUE THREAD

**Issue by arun-gupta** [kubernetes/kubernetes#43834]
Following link give a 404:

https://kubernetes.io/docs/user-guide/scheduled-jobs/

It used to work earlier.

https://kubernetes.io/docs/concepts/jobs/ is a logical link that should work, particularly since https://kubernetes.io/docs/concepts/jobs/run-to-completion-finite-workloads/ is a working link.

**Comment by supereagle** [comment]
> https://kubernetes.io/docs/concepts/jobs/ is a logical link that should work, particularly since https://kubernetes.io/docs/concepts/jobs/run-to-completion-finite-workloads/ is a working link.

https://kubernetes.io/docs/concepts/jobs/ is just a folder which contains several children links, not really a logical link.

You can verify this by testing https://kubernetes.io/docs/tutorials/object-management-kubectl/object-management/

**Comment by supereagle** [comment]
Maybe this issue should be created in [kubernetes.github.io](https://github.com/kubernetes/kubernetes.github.io)

**Comment by xiangpengzhao** [comment]
@arun-gupta ScheduledJobs has been renamed to CronJobs(#36021). Current doc link is:
https://kubernetes.io/docs/user-guide/cron-jobs/

**Comment by arun-gupta** [comment]
@xiangpengzhao Understood but existing links should not break and should be redirected.

**Comment by xiangpengzhao** [comment]
@arun-gupta Is there any documents in which you find an existing link directed to https://kubernetes.io/docs/user-guide/scheduled-jobs/ or, do you just visit this url directly in your browser? 

If former, we should fix the link. If latter, we can do nothing to fix it, because when you visit any non-existent url of kubernetes.github.io, it will return a 404 error. e.g. https://kubernetes.io/docs/user-guide/foo-jobs/

**Comment by FlorianOnmyown** [comment]
From what I can see, this issue is now solved.
