### ISSUE TITLE
Make apply to it's own package 

### ISSUE THREAD

**Issue by shiywang** [kubernetes/kubernetes#43886]
For now apply command and it's subcommand are becoming bloated
1. I will try to move all those command into a independent package like `kubectl set` did.

2. I will try to reduce duplicated code like comments here: https://github.com/kubernetes/kubernetes/pull/41694#discussion-diff-102018502R38

3. current `set-last-applied`'s validate function does not do validate, will move all the code to run and leave this function empty.

here is apply subcommand
- [x] edit https://github.com/kubernetes/kubernetes/pull/42256

- [x] set https://github.com/kubernetes/kubernetes/pull/41694

- [x] view https://github.com/kubernetes/kubernetes/pull/41146

- [ ] diff https://github.com/kubernetes/kubernetes/pull/46560

cc @ymqytw @adohe @kubernetes/sig-cli-misc

**Comment by ymqytw** [comment]
@shiywang Don't forget to update the auto completion for your new commands. It is located in `pkg/kubectl/cmd/cmd.go`

**Comment by adohe** [comment]
@shiywang cool, what we have already talked about, really like to see this.

**Comment by julianvmodesto** [comment]
Could we also add a task to add documentation for these commands?

**Comment by shiywang** [comment]
@julianvmodesto sure, what kind of document do you want ? the basic workflow of those four command are [here](https://github.com/pwittrock/community/blob/572c1e0a26a05892c9ecbbf0dbf6b067677cdc32/contributors/design-proposals/sig-cli/kubectl_apply_getsetdiff_last_applied_config.md#example-workflow-to-stop-managing-a-field-with-apply---using-getset).

**Comment by julianvmodesto** [comment]
Ahh, I do like the example workflows in that doc.

Would be great to have an article similar to this one, since these commands are related to declarative app config:
https://kubernetes.io/docs/tutorials/object-management-kubectl/declarative-object-management-configuration/

i.e. the replicaless Deployment workflow above doesn't make it clear that the last-applied annotation needs to be set properly first

**Comment by julianvmodesto** [comment]
Regarding `diff-last-applied`, should we prefer `kubectl apply diff-last-applied` instead of `kubectl apply --dry-run`? i.e. will `diff-last-applied` show the complete 3-way calculation and patch? I guess this is pending current refactors to `kubectl apply`, but there's a problem where `kubectl apply --dry-run` doesn't always reflect what will actually happen on `kubectl apply`.

For example, in https://github.com/kubernetes/kubernetes/issues/25238#issuecomment-337519654, here's the issue with `kubectl apply --dry-run` described by @shiywang, when you `kubectl apply` a replica-less Deployment onto a Deployment w/ replicas specified in the `last-applied` annotation:

> dry-run's definition: only print the object that would be sent, without sending it.
this apply to more generic POST, PUT command like kubectl create/replace, but for kubectl apply which use 3-way calculate and do a patch, maybe it doesn't apply to dry-run that much cuz currently we didn't show user the patch we sent. we currently only show user the Object fetch from server iirc, ...
