### ISSUE TITLE
Change patch strategy of Env from merge to replace

### ISSUE THREAD

**Issue by ymqytw** [kubernetes/kubernetes#44111]
We are considering changing patch strategy of Env from merge to replace. After changing, it will preserve the order of the env list. It will fix the issues like #40373.
But the concern is if someone replies on the merge behavior. (i.e having an automate tool adding new environment variables to the list)

```
type Container struct {
	// List of environment variables to set in the container.
	// Cannot be updated.
	// +optional
	Env []EnvVar `json:"env,omitempty" patchStrategy:"merge" patchMergeKey:"name" protobuf:"bytes,7,rep,name=env"`
...
}
```

cc: @pwittrock @lavalamp

**Comment by liggitt** [comment]
You can't change the strategy from merge to replace if there are any clients computing strategic merge patches from built-in structs (which there are). Those clients will only send adds/deletes, which a new server would apply as a replace, dropping all unmodified envvars

**Comment by liggitt** [comment]
I don't think it is viable to change the API this way and stay backwards compatible

**Comment by ymqytw** [comment]
@liggitt You are right. This way is not backwards compatible unless the client moves to use openapi instead of compiled-in types someday.

**Comment by liggitt** [comment]
The API compatibility requirements go well beyond one release version. If we add versioning to the patching system (which I guess would be orthogonal to the API version) we'd have to maintain multiple systems simultaneously.

**Comment by pwittrock** [comment]
Marking this as closed per @liggitt 's comments.

**Comment by bgrant0607** [comment]
@pwittrock @ymqytw I agree with the backward-compatibility issue raised by @liggitt. 

I'll also point out that we do want to be able to inject env vars, such as using PodPreset. 

Today we don't allow updates of env on pods, but some day we will, and we currently use the same merge definition for pod templates in controllers as for pod specs in pods.

However, since the ordering is not currently guaranteed, we could change the ordering while retaining the merge strategy. I like the idea of retaining the original order where patching existing list elements.
