### ISSUE TITLE
Modeling distributed stateful application state vs pod state

### ISSUE THREAD

**Issue by rvrignaud** [kubernetes/kubernetes#44145]
**Is this a request for help?** : no

**What keywords did you search in Kubernetes issues before filing this one?** : I scanned every `area/stateful-apps` issues

---

**Is this a BUG REPORT or FEATURE REQUEST?** : Feature Request

We are currently using statefulset to manage a distributed datastore (Elasticsearch). We would like to use PodDisruptionBudget to ensure that draining node, rescheduling etc do not damage our data.
My problem is that AFAIK currently we only have a state of health for each of the pod in the statefulset. However in a distributed datastore, every pod may be in a healthy state but the global application state may be not healthy. In my case elasticsearch can have 3 different states (red, yellow and green). What I would like to be able to model is that something (in similar way of PodDisruptionBudget) would prevent to intentionally evict a pod of a stateful app when this app is still recovering (red or yellow state). So in my case if all pods of my elasticsearch cluster are healthy but elasticsearch itself is in yellow or red state it should prevent eviction of any pod of this cluster.

**Kubernetes version** : I'm using 1.5 but AFAIK there is nothing in 1.6 on that subject

**Environment**:
- **Cloud provider or hardware configuration**: GKE
- **OS** (e.g. from /etc/os-release): COS
- **Kernel** : 4.4
- **Install tools**: GKE
- **Others**: Elasticsearch

**What happened**:
If draining node with pod of stateful app in recovery state, I can't prevent eviction of this pod.

**What you expected to happen**:
I would like the scheduler to prevent pod eviction untill stateful app state is in recovery

**Comment by kargakis** [comment]
One solution would be to have a controller/operator that adjusts your PDB accordingly, eg. in a state where all Pods are Ready but Elasticsearch is red or yellow, your PDB.spec.minAvailable should equal the amount of the ES replicas.

Some related links:
https://github.com/kubernetes/kubernetes/issues/5164
https://coreos.com/blog/introducing-operators.html

cc: @kubernetes/sig-scheduling-misc @kubernetes/sig-apps-misc

**Comment by davidopp** [comment]
What @kargakis would probably work but could be racy and is definitely a bit hacky. :)

This is reminiscent of a request for Horizontal Pod Autoscaler to be able to trigger off of a value provided externally rather than averaging some per-pod value. (I'm not talking about custom metrics, which are still per-pod -- I'm talking about some completely external service that is providing some or all of the data that HPA uses to make the scaling decision.) I'm not sure if they implemented it yet or, if not, if they have a plan to do it.

For PDB I guess we could extend the PDB spec to include an HTTP endpoint that, when it returns anything other than 200, blocks all evictions until it starts returning 200. (So the eviction rule would be what we have today AND endpoint is returning 200.) @rvrignaud would that address your problem?

cc/ @mml @erictune

**Comment by davidopp** [comment]
(Obviously this would insert nontrivial extra latency in the eviction path.)

**Comment by rvrignaud** [comment]
Thank you @kargakis and @davidopp for your answers.

@davidopp your proposition of an HTTP endpoint would cover all my use-cases. As far as I am concerned eviction speed is way less important to me than data integrity for my stateful sets.

**Comment by jlz27** [comment]
+1 on the issue and also on extending PDB with http endpoints.

We ran into a similar issue with etcd (but the problem extends to other quorum based stateful sets).

Suppose we run a replica 3 statefulset and use a PDB with "MaxUnavailable 1".

**Case 1**: etcd readiness returns 200 when etcd server is healthy

t0: evicting etcd-0 pod is successful -> resulting state: 2 healthy pods, 1 unavialable pod, and quorum is maintained

t1: evict etcd-1 fails because there is currently 1 unavailable pod and that will violate the PDB
 
t2: etcd-0 pod gets rescheduled, server comes up and reports `ready` BUT does not join the quorum (due to network issues, corrupted member id, lots of other reasons). current state: 3 healthy pods, but quorum is maintained only by 2 pods.

t3: evicting etcd-1 now succeeds because there were 0 unavailable pods but this now causes downtime because quorum cannot be maintained with only 1 pod.

In an attempt to fix this issue, we tried writing an etcd readiness check that calls `etcdctl cluster-health` and checking that the number of healthy members > 2.

This fixes the PDB issue but causes a different issue with rollout. Whenever the statefulset loses quorum, whether it is the initial stateful rollout or recovering from an unexpected failure. The initial etcd node does not have quorum so the statefulset controller will no longer attempt to create the other pods.

Even if you were to set the rollout policy for statefulset to be `parallel`, it is still problematic to use a quorum based readiness check because network routing is also dependent on `readiness` so even if I can get all 3 etcd pods to start, they will not be mutually routable so they will never establish quorum.

Some potential ideas:

- allow pods to specify custom checks in addition to readiness/liveness. For stateful sets especially, the concept of overall health affects both etcd and things like cassandra
- extend PDB api to add HTTP probes. I think initially the global block all evictions based on a HTTP call is sufficient but we may want to extend PDBs to call custom checks per pod?

**Comment by kow3ns** [comment]
In general I think we need to add a "health check" for under replication and quorum disruption that is separate from availability.  See [50363](https://github.com/kubernetes/kubernetes/issues/50363). The intention is to make the sts controller sensitive to under replication and quorum stability during a rolling update. We could also make PDB sensitive to this signal.

**Comment by hjacobs** [comment]
This looks interesting for the mentioned scenario of running Elasticsearch (or similar) with potential "under replication". A configurable HTTP endpoint like proposed by @davidopp seems to make sense for me.

/remove-lifecycle stale
