### ISSUE TITLE
[Federation] selfLink for clusters is wrong

### ISSUE THREAD

**Issue by marun** [kubernetes/kubernetes#44186]
The selfLink field for a cluster seems to be missing a ``/`` separator between ``clusters`` and the cluster name: 

```yaml
apiVersion: federation/v1beta1
kind: Cluster
metadata:
  creationTimestamp: 2017-04-06T23:02:28Z
  name: openshift
  resourceVersion: "2"
  selfLink: /apis/federation/v1beta1/clustersopenshift
  uid: 1b3b0ace-1b1d-11e7-8eeb-0242ac110006
spec:
  secretRef:
    name: openshift
  serverAddressByClientCIDRs:
  - clientCIDR: 0.0.0.0/0
    serverAddress: https://192.168.77.75:8443
status: {}
```

cc: @kubernetes/sig-federation-bugs

**Comment by BertrandD** [comment]
Same for namespaces :

```yaml
apiVersion: v1
items:
- apiVersion: v1
  kind: Namespace
  metadata:
    creationTimestamp: 2017-03-21T14:08:59Z
    name: default
    namespace: ""
    resourceVersion: "11"
    selfLink: /api/v1/namespacesdefault
    uid: edd6f456-0e3f-11e7-a9a9-fa163e87b25a
  spec:
    finalizers:
    - kubernetes
  status:
    phase: Active

```

**Comment by henriquetruta** [comment]
Taking a look at the code to see the problem with clusters, my best guess is that the problem is in this file: https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/rest.go 
I can reproduce it in a running k8s federation, but where is the place I can add a unit test to reproduce it?

**Comment by spxtr** [comment]
Possibly a dupe of #37622

**Comment by marun** [comment]
Closing in favor of #37622.
