### ISSUE TITLE
BeforeSuite on Node 1 failing 70 builds per hour

### ISSUE THREAD

**Issue by fejta** [kubernetes/kubernetes#44242]
02bd8b - 20 builds/hr, 480 tests/hr - The 1.5 GKE jobs fail to setup all nodes correctly. Spiked Wednesday
143ba8 - 50 builds/hr, 70 tests/hr - A different cluster of BeforeSuite failures, on both 1.5 and serial jobs (summary). Spiked Wednesday.

https://storage.googleapis.com/k8s-gubernator/triage/index.html#02bd8ba009292ae49af5
https://storage.googleapis.com/k8s-gubernator/triage/index.html#143ba813b745195b5eca

/assign @lukemarsden @roberthbailey @mikedanese @jlowdermilk

**Comment by fejta** [comment]
Here is another cluster that the triage tool thinks is different but I suspect is part of the same problem: https://storage.googleapis.com/k8s-gubernator/triage/index.html#143ba813b745195b5eca

A couple example jobs where this is happening (see the triage links for full list):
https://k8s-testgrid.appspot.com/release-1.6-all#gci-gke-reboot-1.6
https://k8s-testgrid.appspot.com/google-kubectl-skew#gke-1.5-1.4-cvm

**Comment by roberthbailey** [comment]
All of the logs that you point to show an unhealthy node where neither fluentd nor kube-proxy is in the ready state. Both of those are pods launched from static manifests on the nodes, and since the pods are running (but not ready), I think this is more likely to be a node issue than a lifecycle issue. 

@dchen1107

**Comment by fejta** [comment]
Sent a message to sig-node on slack -- https://kubernetes.slack.com/archives/C0BP8PW9G/p1491864388573585

**Comment by yujuhong** [comment]
In https://k8s-testgrid.appspot.com/release-1.6-all#gci-gke-reboot-1.6, every kubelet in the tests were complaining about not getting the pod CIDR assigned:
```
E0410 20:50:44.191244    1286 kubelet.go:2067] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: Kubenet does not have netConfig. This is most likely due to lack of PodCIDR
E0410 20:50:49.192730    1286 kubelet.go:2067] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: Kubenet does not have netConfig. This is most likely due to lack of PodCIDR
```
Someone should check the node controller logs on the master node. Those logs are not uploaded since these are GKE clusters. I don't think @derekwaynecarr can help debug this.

**Comment by mikedanese** [comment]
maybe same issue as https://github.com/kubernetes/kubernetes/issues/44243

**Comment by yujuhong** [comment]
> maybe same issue as #44243 which is caused by a broken controller manager.

That sounds very likely.

**Comment by Random-Liu** [comment]
Not sure whether it is the same issue. But there is also a user complaining about this https://github.com/kubernetes/kubernetes/issues/44273.

**Comment by derekwaynecarr** [comment]
I would have been happy to help if I could help ;-)
