### ISSUE TITLE
Document administration of credentials for system roles/bindings/groups

### ISSUE THREAD

**Issue by jimmycuadra** [kubernetes/kubernetes#44418]
The new RBAC documentation includes a section that enumerates the [default roles and role bindings](https://kubernetes.io/docs/admin/authorization/rbac/#default-roles-and-role-bindings), which is very helpful. However, it doesn't explain how a component should be configured to actually authenticate as a member of one of these groups.

Specifically, the following auth groups are included in the tables:

* system:authenticated
* system:unauthenticated
* system:masters
* system:kube-scheduler
* system:kube-controller-manager
* system:nodes
* system:kube-proxy

(I happen to know that system:authenticated and system:unauthenticated are automatically added to incoming requests as appropriate, but this is never mentioned in the linked document.)

Traditionally, cluster setup tools have not created separate client certificates for all of the core Kubernetes components, but the default cluster roles and cluster role bindings suggest much more granular authentication. The documentation should explain:

* The `--authorization-rbac-super-user` option to the API server has been removed and replaced with the system:masters group. How should a user authenticate as a member of this group? Should credentials that place them in that group be created via normal means (e.g. creating a client certificate) or is this membership determined some other way?
* How is a given Kubernetes core component or add on determined to be a member of one of these groups? Does each one need its own credentials, or is there some magical way that a components can authenticate as a member of the correct group without configuration? (This is kind of a generalization of the previous bullet point.)
* How do the various cluster creation tools (kops, kubeadm, etc.) actually provision credentials for each component?
* What are the requirements for creating system component credentials for those of us building clusters from scratch without one of the official tools?
* What happens if a system component is _not_ configured to be a member of a group that would bind it to the appropriate role? (For example, what happens if the controller manager is started without credentials that assign it the system:kube-controller-manager group? Does it completely fail? And what about the per-control-loop controller manager roles like system:controller:replication-controller? There's no explanation of how to create credentials for the controller manager such that different credentials are used for each control loop. How is this expected to work?)
* There are also quite a few cluster roles with the "system" prefix that don't have a default cluster role binding, even though they are clearly intended for a specific component, such as Heapster and the Node Problem Detector. It's not clear how what the cluster administrator is expected to do when installing an add on component that maps to one of these roles/bindings. Is the add on itself supposed to provide instructions on adding appropriate role bindings? If so, why are the roles included by Kubernetes itself and not the add on? This should be explained so cluster administrators know what to expect.

Finally, the use of the "system" prefix on these roles/bindings/groups could be interpreted to mean that they are managed _by_ the system, and should never be modified by a cluster administrator. It's not clear if this prefix is just a way of grouping resources that are related to system functionality, or if they're supposed to be "private" (in the sense of a private method in code.) It would be very helpful if the documentation clarified this.

If someone can answer these questions here, I'd be happy to open a PR on the docs repo myself.

**Comment by liggitt** [comment]
Answering questions here... can decide how we want to roll them into doc updates.

> Should credentials that place them in that group be created via normal means (e.g. creating a client certificate) or is this membership determined some other way?

Yes, via the normal means (either a token file or a client certificate, etc) set up by the cluster installation mechanism.

> How is a given Kubernetes core component or add on determined to be a member of one of these groups? Does each one need its own credentials, or is there some magical way that a components can authenticate as a member of the correct group without configuration?

Yes, they need their own credentials, set up by the cluster installation mechanism, that identifies them as a member of that group in order to take advantage of the default role bindings.

> How do the various cluster creation tools (kops, kubeadm, etc.) actually provision credentials for each component?

That is out of scope for the RBAC doc... I think most set up client certificates or bearer tokens.

> What are the requirements for creating system component credentials for those of us building clusters from scratch without one of the official tools?

Also out of scope for the RBAC doc... most of the authentication mechanisms described in the authentication documentation (https://kubernetes.io/docs/admin/authentication/) could be used, but which ones are enabled on a particular cluster is up to the cluster installer.

> What happens if a system component is not configured to be a member of a group that would bind it to the appropriate role? (For example, what happens if the controller manager is started without credentials that assign it the system:kube-controller-manager group? Does it completely fail? And what about the per-control-loop controller manager roles like system:controller:replication-controller? There's no explanation of how to create credentials for the controller manager such that different credentials are used for each control loop. How is this expected to work?)

If you run the controller manager in subdivided mode (`--use-service-account-credentials=true`), the controller manager's credential only needs to be given the `system:kube-controller-manager` role. If the credential it is started with (`--kubeconfig=...`) identifies it as the user `system:kube-controller-manager`, it gets that role automatically. Otherwise, the role must be granted to it by the cluster installer. In this mode, the service accounts the controller manager uses to start the controller loops are automatically given their roles.

If you run the controller manager in monolithic mode (`--use-service-account-credentials=false`), whatever credential it is given must be given the `system:kube-controller-manager` role (just as before) AND all the individual controller roles (which is never done automatically).

> There are also quite a few cluster roles with the "system" prefix that don't have a default cluster role binding, even though they are clearly intended for a specific component, such as Heapster and the Node Problem Detector.

This is typically done for components that are expected to be part of all clusters, but which have various deployment mechanisms (and so have no standard user). The roles could be defined in the add-on, but not everyone uses the add-on manager.

> Finally, the use of the "system" prefix on these roles/bindings/groups could be interpreted to mean that they are managed by the system, and should never be modified by a cluster administrator. It's not clear if this prefix is just a way of grouping resources that are related to system functionality, or if they're supposed to be "private" (in the sense of a private method in code.)

For users/groups, the `system:` prefix is intended to prevent conflicts with usernames and group names coming from external authentication sources.

The explanation in the doc is accurate:

> Many of these are system: prefixed, which indicates that the resource is “owned” by the infrastructure. Modifications to these resources can result in non-functional clusters.
