### ISSUE TITLE
manpage artifacts are not being generated in a release

### ISSUE THREAD

**Issue by aespinosa** [kubernetes/kubernetes#44533]
**Kubernetes version** (use `kubectl version`): 1.6.1

**What happened**:
I downloaded https://dl.k8s.io/v1.6.1/kubernetes.tar.gz
The files `doc/man/man1/kube-apiserver.1`and others just contains the 'this is an autogenerated doc place holder`

The markdown docs like in `doc/admin/kube-apiserver.md` etc. also just contains the placeholder text.

**What you expected to happen**:
I'm expecting the release tarball to contain the generated manpages similar to the markdown ones in https://github.com/kubernetes/kubernetes.github.io/blob/release-1.6/docs/admin/kube-apiserver.md

**Comment by kargakis** [comment]
@enisoc

**Comment by ixdy** [comment]
Looks like this has been broken for a while - I just checked v.1.3.1, and it similarly contains the placeholder docs. Looks like https://github.com/kubernetes/kubernetes/pull/26820 caused it, and I guess we forgot to update `anago` to generate docs before release?

**Comment by david-mcmahon** [comment]
This should happen [here](https://github.com/kubernetes/release/blob/master/anago#L376).  Checking further.

**Comment by david-mcmahon** [comment]
Seems to be related to https://github.com/kubernetes/release/pull/328.  The doc generation does happen at branch time, but due to recently introduced issues with verify-all failing on the branch, update-all.sh has been run by the release managers which undoes the doc generation because it runs the update-generated-docs.sh.

Once we sort out https://github.com/kubernetes/release/pull/328, this problem will resolve. 
Unfortunately for those releases already out, there's not obvious path for resolution.  In the mean-time release-managers @enisoc can run hack/generate-docs.sh on the branch to fix docs for future releases on existing branches.

**Comment by enisoc** [comment]
According to the comment above by @ixdy, the generated docs are no longer checked in. Doesn't that mean anago needs to generate them every time it runs?

**Comment by david-mcmahon** [comment]
Anago generates them at branch time on new branches [here](https://github.com/kubernetes/release/blob/master/anago#L376).

**Comment by enisoc** [comment]
Ah I see. I thought "no longer checked in" meant that the generated files are placed in an output directory that's ignored by git. But actually what it means is that we check in the stubs in-place on top of the real files.

Is your plan that eventually we will stop running update-all.sh on the release branch? I thought that should be a normal part of the workflow for any PR - some parts are needed even for cherrypicks (e.g. update-bazel). It would be confusing if running update-all on a cherrypick produces a PR that wipes out all the docs. Also won't verify-generated-docs start to fail if the files are not stubs?

Should we fix update/verify-generated-docs to detect when they're run on a branch that's supposed to have docs? Perhaps we could create and check in a hidden marker file upon branching off of master?

**Comment by enisoc** [comment]
Alternatively, we could let the docs stay as stubs in the release branch, and have anago run generate-docs.sh at release build time, rather than at branch cut time.

**Comment by david-mcmahon** [comment]
At one point the workflow precluded running update-all.sh on branches and/or update-generate-docs.sh was not part of that.  I haven't done the archaeology yet to determine how we got to this point recently, but  @lavalamp created this split some time last year and it was to avoid the doc churn on master and generate the docs *once* at branch time.

**Comment by kargakis** [comment]
> At one point the workflow precluded running update-all.sh on branches and/or update-generate-docs.sh was not part of that. I haven't done the archaeology yet to determine how we got to this point recently, but @lavalamp created this split some time last year and it was to avoid the doc churn on master and generate the docs once at branch time.

FWIW we did the same switch in Openshift, and moved the generation during the RPM build.

**Comment by ixdy** [comment]
IMO generating the docs at release-time makes the most sense, since things may change on a release branch over time as fixes get cherry-picked in.

**Comment by david-mcmahon** [comment]
As a general rule, yes, you want to generate the docs "at release time", but you also don't want to create churn or changes where none are needed.  It could be that things have changed enough to where it's more appropriate now to run this with each release vs. at branch time, but what data do we have to back that up?
What changes have landed on branches over the past few releases that required regenerating the docs that were generated at branch time?

**Comment by kargakis** [comment]
Usually you shouldn't have diffs in release branches since new changes mean either additions; new features and we are not backporting features, it seems, or updates/deletions which are likely non-backwards compatible. @david-mcmahon are you suggesting to have the docs generated when a branch is cut and leave them off just master?

**Comment by kargakis** [comment]
Also even if we generated them at branch time, cherry-picks would merely be required to update those generated changes which doesn't seem like a big deal? I can get behind that.

**Comment by david-mcmahon** [comment]
Right, the branches are the 'stabilized' bit here.  If cherrypicks are coming from master that require update-all.sh changes, then *all* of those related commits should come over (from master) and land as a unit on the branch.  At least that's the way it's been working til now since the great doc move/shift of last year when update-generated-docs.sh got repurposed to generate stubs and generate-docs.sh was introduced and [versionize-docs disappeared](https://github.com/kubernetes/release/pull/176).
 @lavalamp @thockin

**Comment by ixdy** [comment]
I'm not sure exactly how docs are generated, but if we generate docs only at branch time, how will we know if a cherry-picked change affects docs, since the docs aren't checked into the master branch?

e.g. Suppose we generate docs for release-1.7 when we cut the branch. Later, we cherry-pick some change to kubectl which would affect the manpages, but we also cherry-pick 5 other changes which don't. How will we know when to regenerate docs on release-1.7, and when will that happen? Do we regenerate docs every time we make a cherry-pick to the release branch, just in case?

**Comment by david-mcmahon** [comment]
This issue hasn't come up since we implemented the at-branch-time doc generation several months ago, but there is a good point made here.  Now that we're considering this again, would it make more sense for the cherrypick process to generate any doc changes in order to couple them with a specific cherrypick and to have them reviewed as part of that change?  The other alternative as suggested is to simply regenerate all docs (which may or may not be a no-op) with each release on a branch.
