### ISSUE TITLE
Revisit deleted e2e test jobs to determine whether SIGs want to undelete and fix or disable them

### ISSUE THREAD

**Issue by fejta** [kubernetes/kubernetes#44647]
https://github.com/kubernetes/test-infra/issues/2453

/assign @mtaufen 

https://github.com/kubernetes/test-infra/pull/2486
https://github.com/kubernetes/test-infra/pull/2487
https://github.com/kubernetes/test-infra/pull/2489
https://github.com/kubernetes/test-infra/pull/2526
https://github.com/kubernetes/test-infra/pull/2524
https://github.com/kubernetes/test-infra/pull/2525
https://github.com/kubernetes/test-infra/pull/2526

**Comment by quinton-hoole** [comment]
Thanks @mtaufen, @fejta  I have just joined SIG-testing, and will gladly help with this:

I think it's super-important for the SIG's/domain experts to re-review all of these deleted tests, and re-enable the ones that provide useful coverage as soon as they've been fixed.

@fejta @kubernetes/sig-testing-misc Do we have any test coverage metrics?

@fejta Are they going down as a result of removing all these failing tests?

I must say, I find it a bit crazy to blindly delete tests without any understanding of what impact that has on test coverage (I guess the assumption is that if nobody has invested the time to get the tests to pass in X months then the tests can't be providing useful test coverage - this is patently a false assumption).

My gut feel (which is all I can fall back on in the absence of test coverage metrics) is that in general our test coverage is very low, and that by blindly deleting failing tests without:

1. trying to determine whether they provide useful test coverage
2. if they do, determining roughly why they are failing (e.g. broken test config, critical system bug).

has the effect of monotonically reducing our test coverage over time, the logical end-point of which is zero test coverage.

I have just joined SIG-testing and will try to assist in ways other than chirping from the sidelines like this in future.

**Comment by fejta** [comment]
Please sign up and fix (and maintain) any suite and/or test that provides you with an important signal. 

We absolutely want to run tests that people are interested in maintaining. 

Unfortunately there are a myriad of ignored, useless, redundant and unloved suites that were randomly added. 

The goal is to identify the valuable suites from the rest.

**Comment by quinton-hoole** [comment]
@fejta Do you have answers to the two questions I asked?  To repeat them...

@fejta @kubernetes/sig-testing-misc Do we have any test coverage metrics?

@fejta Are they going down as a result of removing all these failing tests?

@fejta @kubernetes/sig-testing-misc I don't see any OWNERS files in https://github.com/kubernetes/test-infra ? Is that perhaps how all of these ignored, useless, redundant and unloved suites got merged in the first place?  It seems that should be fixed (by adding OWNERS files, and the related merge checks)?

I understand that the goal is to understand valuable suites from the rest, but deleting failing ones, or threatening to delete them if not passing by the end of the month does not seem to be an effective strategy to achieve this.  I have no objection to disabling consistently failing tests so that they do not waste resources etc, as consistently failing tests are about as valuable as disabled tests, only more expensive.  Then the next step could be for SIGS to review all their disabled tests and decide whether and when to fix and re-enable them, or delete them permanently if they are no longer required.

Seem sane? 

If so, lets undelete all of these tests, disable them, and assign ownership of each test suite to a SIG (one of which is sig-testing) to properly review and decide whether to fix or delete.

**Comment by quinton-hoole** [comment]
@fejta Oh, and just so we're clear on the terminology I'm using, I consider a "deleted" test job to be one that no longer exists in test configuration files (like the ones you deleted in the PR's linked above).  By disabled, I mean test configurations that exist in the configuration files, but which are not routinely run by our continuous integration machinery (e.g. with a DISABLED=true flag or similar, which can ideally be overridden by anyone who wants to run them somewhere else to debug, fix and ultimately re-enable).

**Comment by fejta** [comment]
Once someone demonstrates a suite passes we can add it back. 

Constantly failing tests that no one is fixing have negative value. They are worse than no tests. Ignored failures reduce the visibility of other failures. And teach the community that failures are not important to investigate and resolve. 

I agree it is important to find owners for each suite that we can expect to maintain the health of the suite and delete when no longer needed.

**Comment by fejta** [comment]
I do not know what/whether the deleted scenarios cover and whether it is important. 

Empirically it does not appear that any of them are valuable enough for someone to consider them worth their time to step up and maintain them.

**Comment by quinton-hoole** [comment]
@fejta, I think you might have misunderstood my proposal to undelete and disable the tests.  There would be no constantly failing tests, as they would be disabled and hence not be running.  So I don't think that what you've mentioned applies at all.

To your other point. To give an example of a test suite that failed for over a year, but provided great value, the soak tests.  They demonstrated conclusively that while it was possible to build a new cluster, execute a single run of all e2e tests against it, have them pass, and tear down the cluster again (and it was possible to do this consistently, hundreds and hundreds of times over), it was not possible to run the e2e tests repeatedly and indefinitely against a single cluster.  After a few hours (initially) the cluster would fall over, for a variety of reasons.  Over many, many months we resolved those issues in the system (they were not the tests), and eventually the soak tests could run forever (until we recycled them) without failing (I don't know whether they succeed any more, but they did at one point).

If one had deleted those tests every few months, or had repeated arguments about why they were failing and whether or not they were useful, it would simply have created busy work for everyone, or worse still we would have lost that signal completely (which will happen with all of the tests you have deleted unless others take the trouble to reverse it).

**Comment by fejta** [comment]
Another example are the federation suites, many of which have passed zero times in 2017. When flagged sig-federation stepped up to the plate and prioritized fixing them (yay!). These still exist. 

Happy to do the same for any other suite someone is willing to maintain. 

Also clearing them out of head on the master branch is equivalent to disabling them: they still exist at earlier commits. And this issue tracks them in case someone wants to find them. 

The only suites we want to disable/delete/eliminate are ones that no one is willing to maintain.

**Comment by quinton-hoole** [comment]
@fejta sig-federation had already prioritized fixing their e2e tests before you proposed deleting them.  So doing that just created busy work.

Do you have an answer to the question I posed above?  To repeat:

@fejta @kubernetes/sig-testing-misc I don't see any OWNERS files in https://github.com/kubernetes/test-infra ? Is that perhaps how all of these ignored, useless, redundant and unloved suites got merged in the first place? It seems that should be fixed (by adding OWNERS files, and the related merge checks)?

**Comment by fejta** [comment]
See previous reply about ownership.

**Comment by quinton-hoole** [comment]
I think you misunderstood my question about OWNERS. The main kubernetes
repo has an OWNERS file in every directory, which specifies who has to
review and approve changes to files in that directory. You are saying that
people have added redundant, useless and otherwise bad test suites. If so,
who reviewed and approved those additions.  If you follow my suggestion
above, and e.g. add yourself as a reviewer or approver, you can help to
prevent the addition of such unwanted test suites (rather than coming along
after the fact and deleting them, along with useful ones).

On Apr 22, 2017 11:27, "Erick Fejta" <notifications@github.com> wrote:

See previous reply about ownership.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/44647#issuecomment-296392285>,
or mute the thread

**Comment by spiffxp** [comment]
/close
Please /reopen if we're going to revisit these.  I've got some more suggestions for jobs that we should stop running: http://velodrome.k8s.io/dashboard/db/bigquery-metrics?panelId=2&fullscreen&orgId=1
