### ISSUE TITLE
support label selector in RBAC

### ISSUE THREAD

**Issue by xilabao** [kubernetes/kubernetes#44703]
I found the pull request in Openshift (https://github.com/openshift/origin/pull/8610 by @deads2k ).  I think it could be very useful If kubernetes can support it.

/cc @deads2k @liggitt @smarterclayton @pweil- @kargakis

**Comment by liggitt** [comment]
cc @kubernetes/sig-auth-feature-requests

**Comment by liggitt** [comment]
the three main issues I see:

* inconsistencies of availability of label-selecting rules across verb types
* split nature of authorizing based on labels and ensuring the current/resulting object is covered by those labels (called out in https://github.com/openshift/origin/pull/8610#issuecomment-213556833)
* can we evaluate/apply this performantly?

I'd expect this to be considered after the core functionality of RBAC reaches v1

**Comment by liggitt** [comment]
copied relevant discussion from https://github.com/kubernetes/ingress/issues/816#issuecomment-309229262 since I keep wanting to reference that as part of this

@davidopp:
> @liggitt As you know there has been some discussion in the past of allowing RBAC  Roles to use a label selector to select the objects they apply to  (instead of explicit resourceNames). What is your view on that? It would solve this problem and be useful for other purposes as well. Obviously there are a bunch of details to work out.

@liggitt:

> Depends on what you mean. There are several different things that could fall under "make RBAC label selector aware":
> 
> 1. Authorizing API operations that already support label selectors (list, watch, deletecollection)  based on what label selector is used ("you may list secrets with label selector x=y"). This would be possible to do while keeping authorization a clean layer that does not require request bodies or storage details.
> 
> 2. Authorizing write operations based on the labels of the object being provided (for create/update), and/or the labels of the existing object (for update/delete). This is not possible to do without access to both the request body and backing storage, and has several downsides:
>     * it makes authorization decisions stateful ("you are only authorized to update object foo if it currently has a label x=y"), which doesn't play nicely with the authorization decision caches used to make delegated authz performant
>     * it increases the information needed by the authorizer to include the incoming object, which doesn't play nicely with the APIs used for delegated authz checks
>     * it bases authorization decisions on mutable attributes of objects, which is a pretty big change (currently, we authorize on namespace, name, resource, and subresource object attributes, all of which are immutable). It means you could be allowed to change an object in a way would cause you to lose access to it.
>     * it either requires authorizing layers to decode and pull label info out of request bodies, or to coordinate between the authorization layer and the admission layer, which ranges from tricky (in the case of a single server), to extremely difficult (in the case of an aggregated API server)
> 
> 3. Authorizing read operations like `get` based on the labels of the existing object. This has almost all the same issues as authorizing write operations, with the added wrinkle of admission not handling `get` operations today.

**Comment by CaoShuFeng** [comment]
> I'd expect this to be considered after the core functionality of RBAC reaches v1

Hi, @liggitt . Is there some new situation about this?

**Comment by liggitt** [comment]
No, all the same issues mentioned in https://github.com/kubernetes/kubernetes/issues/44703#issuecomment-324826356 still apply

**Comment by WanLinghao** [comment]
@liggitt ,Hello~I propose the following ideas about label selector in RBAC:

1.When the request reaches the RBAC in the authorization filter, the RBAC component looks for the RoleBinding information in the system as it does for the existing model. Suppose the request's <verb, resource, namespace> triple  hits a match, say rule A.  If rule A has no selector,  just allow this request. Otherwise, if rule A contains selector, firstly, RBAC will write selector info into authorization AttributesRecord.Then just continue to the next authorizer. After all authorizate checks done, the selector info extracted from AttributeRecord will be wrote into user info. At last, update context with this new user info.

2. To complete check, a new admission plugin will be added.It extracts rule selector information from user info as well as Labels info from Object.Then, it simply compares them and decides if the request should go throw.

3. For remote authentication such as WebHook, I want to add a new Selector filed in SubjectAccessReview. When remote call returns, similar to local RBAC, local server writes new user info which contains Selector info from SubjectAccessReview into context.And it will be checked in admission plugin.


Of course, I recognize that this model contains some problems.
1.Currently, only Create,Update,Delete operations do admission check.
2.Admission plugin can not get label info of target Object in Delete request.
3.It is not a good choice to rewrite info into user info.

I want to know your opinion about this,thanks

**Comment by liggitt** [comment]
>  if rule A contains selector, firstly, RBAC will write selector info into authorization AttributesRecord

a few issues with this:
1. the authorization attributes aren't mutable
2. there could be multiple rules that allowed with different selectors... so the structure would have to accumulate N possible selectors to evaluate, any of which could allow the request
3. selector information is not part of user info or authentication, it's either part of the request attributes or would be part of the authorization rules

> 1. Currently, only Create,Update,Delete operations do admission check.

Correct. I think adding selector restrictions that didn't apply on get/list/watch would be surprising to people.

> 2. Admission plugin can not get label info of target Object in Delete request.

Not only that, but this would be the first mutable thing we would be authorizing on... making authorization decisions based on an attribute of the object that can change raises several questions: can you make a change that places the object into your allowed objects? can you make a change that removes the object from your allowed objects?

> 3. It is not a good choice to rewrite info into user info

I agree that that is not a good choice

**Comment by bgrant0607** [comment]
ref #15390

**Comment by hmodi23** [comment]
Hello,

Checking in on this one, was the support for LabelSelector added to KubernetesPolicyRule? Basically, is there any support for defining KubernetesRole/KubernetesClusterRole for say e.g. pods with certain labels?

If this functionality is not present as of now then, are there any plans to support this soon?

Thanks!

**Comment by liggitt** [comment]
> was the support for LabelSelector added to KubernetesPolicyRule? Basically, is there any support for defining KubernetesRole/KubernetesClusterRole for say e.g. pods with certain labels?

No, the fundamental issues raised in https://github.com/kubernetes/kubernetes/issues/44703#issuecomment-364693917 are still germane, and other items have been prioritized

> If this functionality is not present as of now then, are there any plans to support this soon?

it is not currently planned

**Comment by mtparet** [comment]
Networkpolicy can already be applied to labels, from an user perspective it's weird to have RBAC not behaving the same.

**Comment by tyrone-grech** [comment]
This would be helpful for us as well, to be able to for example allow developers additional access to certain pods (test environments) than others (Continuous Integration tools like Jenkins).

**Comment by liggitt** [comment]
> Networkpolicy can already be applied to labels, from an user perspective it's weird to have RBAC not behaving the same.

Network policy does not authorize modification of API objects. The details in https://github.com/kubernetes/kubernetes/issues/44703#issuecomment-324826356 describe some of the problems authorizing mutation of an object based on the content of the object being mutated causes.

**Comment by redbaron** [comment]
@liggit,

There some tech challenges indeed, but probably something can be worked out.

> it makes authorization decisions stateful ("you are only authorized to update object foo if it currently has a label x=y"), which doesn't play nicely with the authorization decision caches used to make delegated authz performant

Isn't it already somewhat stateful? Authz results depends on current moment in time group membership and rolebinding objects presence. How do caches cope with it? Can current caching technique be extended to accommodate another piece of state?

> it increases the information needed by the authorizer to include the incoming object, which doesn't play nicely with the APIs used for delegated authz checks

there is no need for whole object, just labels. What would be the downside of optionally adding labels from ObjectMeta to SubjectAccessReview used for authz delegation ? Looks like backward compatible and relatively straightforward  change. 

> it bases authorization decisions on mutable attributes of objects, which is a pretty big change (currently, we authorize on namespace, name, resource, and subresource object attributes, all of which are immutable). It means you could be allowed to change an object in a way would cause you to lose access to it.

Not necessary, we can impose restriction that any modification of an object must keep intact labels, which used to authorize such modification. So if user allows to modify object with label selector A, then modified object must continue to match same selector A after modification, if it is not action is rejected. It is similar to how users can't transfer file ownership in Linux, works reasonably well .

> it either requires authorizing layers to decode and pull label info out of request bodies, or to coordinate between the authorization layer and the admission layer, which ranges from tricky (in the case of a single server), to extremely difficult (in the case of an aggregated API server)

Why accessing request body is bad? This work has to be done anyway ,so decoding it a bit earlier doesn't make it worse is grant scheme of things. Plus, it is only small part of ObjectMeta which is required, maybe it opens some optimization possibilities

**Comment by liggitt** [comment]
> Isn't it already somewhat stateful?

Not with respect to the resource being authorized. For a given authorization policy and request attributes, the results are static. This change would make them depend on the current state of the resource being authorized.

> There is no need for whole object, just labels. What would be the downside of optionally adding labels from ObjectMeta to SubjectAccessReview used for authz delegation? Looks like backward compatible and relatively straightforward change.

Not all clients of subjectaccessreview currently provide labels (e.g. kubelets when authorizing access to the kubelet API do not populate the labels of the node resource).

> Why accessing request body is bad? This work has to be done anyway

Request bodies are not decoded at all for aggregated API requests, they are simply authorized and proxied through to the backing server. Requiring access to request bodies makes authorization more expensive and means it cannot be performed by transparent authorization proxies with no knowledge of object content.

**Comment by deads2k** [comment]
Much of the kubernetes ecosystem is built around the idea that a resourcecversion is consistent across all time.  Even ignoring the distinctions you'd have around multiple readers getting inconsistent views of the API for a given resourceversion, you actually end up with cases where the *same subject* will get different responses for a given resourceversion over time.

If their permissions change between one list and another, they'll get different results.  An even the common case of list/watch becomes fraught as your list may not have permissions to see itemA, but your watch from RV=X assumes you've seen itemA because you got permissions in between the list and watch, but itemA will never appear because the RV adding it already passed.

OpenShift has had one resource type (projects) where the content can change based on permissions updates and while it is incredibly useful for humans, it is too fraught for general use with strong guarantees like the rest of the API.

I don't think we will pursue this feature.

**Comment by tap52384** [comment]
Please open this back up! This seems to be an easy way to allow users to select resources with dynamic names without adding too much overhead.

**Comment by ctrought** [comment]
+1 for this

**Comment by ghostsquad** [comment]
Any chance this can be reopened?

**Comment by Dobry-kot** [comment]
+1

**Comment by abdennour** [comment]
@k8s-ci-robot  Please reopen it & let me work on it. I will send PR soon . just open it please
/reopen
/re-open

**Comment by pierluigilenoci** [comment]
@xilabao @liggitt could you please help @abdennour to work on this?

**Comment by kmathewmk** [comment]
How can the issue be reopened so that the improvement gets implemented?

**Comment by Yayg** [comment]
Hi to all the kubernetes team,

I'm just going to add a coin in the jukebox here but is there any alternative for people looking to cut their clusters into "projets" and give access to people to theses "projects" including all the namespaces and sub-resources attached to it?

I know about hierachical namespace (https://kubernetes.io/blog/2020/08/14/introducing-hierarchical-namespaces/) but since the project does not seem active and/or entirely supported I'm not sure it's a viable way to go.

Another alternative was to thing about wildcarding resources in rbac (https://github.com/kubernetes/kubernetes/issues/56582) but I thing most people would agree this can easily cause inconsistencies and open the door to security issues.
So having label on resources and matchLabels on ressources allowed in rbac rules would have been nice.

I'm not sure what is the recommendation of the consortium on a "project scoped k8s resources" architecture but I would be glad to have some insight about how most architects leverage this.

Sincerely

**Comment by ringerc** [comment]
This is very relevant for non-namespaced cluster-scoped resources like namespaces and nodes.

Currently there's no way to control access to them. You cannot allow a workload to see a subset of nodes or subset of namespaces, etc.

**Comment by guilhem** [comment]
If this issue is closed, what is the standard way to do RBAC on pods (like exec) in a namespace?
As usually the pod name is auto-generated, so we can't use `resourceNames:`

**Comment by gpongelli** [comment]
> If this issue is closed, what is the standard way to do RBAC on pods (like exec) in a namespace? As usually the pod name is auto-generated, so we can't use `resourceNames:`

+1 

how is possible to bind a role to a pod if its name is dynamically generated ? using `resources: ["pods"]`  can be too wide within a namespace.

`matchLabels`, as per [aggregated clusterroles](https://kubernetes.io/docs/reference/access-authn-authz/rbac/#aggregated-clusterroles) could be the solution.

thanks.
