### ISSUE TITLE
Not able to links two pods in kubernetes cluster.

### ISSUE THREAD

**Issue by Rishabhjain123456** [kubernetes/kubernetes#44728]
i am trying to deploy simple food truck application with two tier:
python+nginx-1st tier
elastic search -2nd tier.

But after deploying both pods i m getting unable to connect from ft(app) tier to es tier.
Below are my pods and service file:

**es service yml:**

apiVersion: v1
kind: Service
metadata:
  name: es
  labels:
    name: es
    app: foodtruck
spec:
  ports:
    # the port that this service should serve on
  - port: 9200
    name: es
    targetPort: 9200
  selector:
   name: es
   app: foodtruck

**ft service yml**
apiVersion: v1
kind: Service
metadata:
  name: ft
  labels:
    name: ft
    app: foodtruck
spec:
  selector:
    name: ft
  type: NodePort
  ports:
   - port: 80
     targetPort: 5000
     protocol: TCP

**es pod yml**

apiVersion: v1
kind: Pod
metadata:
  name: es
  labels:
    name: es
    app: foodtruck
spec:
  containers:
  - name: es
    image: elasticsearch:latest
    ports:
    - containerPort: 9200

**ft pod yml**

apiVersion: v1
kind: Pod
metadata:
   name: ft
   labels:
     name: ft
     app: foodtruck
spec:
  containers:
  - name: ft
    image: prakhar1989/foodtrucks-web
   
    ports:
    - containerPort: 5000
      name: http
      protocol: TCP                            

**Error i m getting:**

ft pods is continously starting and stopping.

[root@kuber-master foodtruck]# kubectl logs ft
Unable to connect to ES. Retying in 5 secs...
Unable to connect to ES. Retying in 5 secs...
Unable to connect to ES. Retying in 5 secs...
Out of retries. Bailing out...

Could anyone help?
I can provide any more info if neede.

Regards,
Rishabh

**Comment by saad-ali** [comment]
Please re-post your question to [Stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases.

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search Stackoverflow for answers to similar questions, and also familiarize yourself with:
  * [User guide](http://kubernetes.io/docs/user-guide/)
  * [Troubleshooting guide](http://kubernetes.io/docs/admin/cluster-troubleshooting/)

Again, thanks for using Kubernetes.

The Kubernetes Team
