### ISSUE TITLE
Service endpoints latency should not be very high flakes

### ISSUE THREAD

**Issue by fejta** [kubernetes/kubernetes#44791]
/assign @dcbw @thockin @caseydavenport @bowei 

The `[k8s.io] Service endpoints latency should not be very high [Conformance]` test flaked six times last week during blocking presubmit testing of PRs.

The http://go.k8s.io/triage page can focus on a single test: [link](https://storage.googleapis.com/k8s-gubernator/triage/index.html?ci=0&pr=1&test=Service%20endpoints%20latency%20should%20not%20be%20very%20high)

13 out of 24 failures match the following pattern:
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:126
Apr 20 21:00:07.509: Couldn't delete ns: "e2e-tests-svc-latency-7vht8": namespace e2e-tests-svc-latency-7vht8 was not deleted with limit: timed out waiting for the condition, namespaced content other than pods remain (&errors.errorString{s:"namespace e2e-tests-svc-latency-7vht8 was not deleted with limit: timed out waiting for the condition, namespaced content other than pods remain"})
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:279
```

**Comment by liggitt** [comment]
namespace cleanup is @kubernetes/sig-api-machinery-test-failures

**Comment by liggitt** [comment]
cc @derekwaynecarr

**Comment by thockin** [comment]
Is there a "reasonable" amount of time to wait for an NS?  Default is 5 minutes.

**Comment by liggitt** [comment]
For everything but pods (which can hang waiting for graceful deletion), cleanup should be *very* quick (limited only by load and API QPS throttling by the namespace controller). I'd expect on the order of single digit seconds. Do we know what non-pod resources still exist in these namespaces the test is complaining about?

**Comment by bowei** [comment]
This does not seem to be related to networking, it is testing when the service endpoints are populated in the API server.

**Comment by thockin** [comment]
We sort of own the endpoints controller.

**Comment by fejta** [comment]
Expectations:
* This work should interrupt and take priority over other activity while it is assigned to you.
* Expectation for sig leads is to identify someone to fix the issue, `/assign` them and `/unassign` yourself.
* Expectation for assignees are to investigate the issue and either a) resolve it or b) `/assign` it to a more appropriate person and b) `/unassign` yourself.

**Comment by bowei** [comment]
There seem to be two major sets of failures:
* 11 failures -- namespace deletion. The namespace deletion errors appear to be part of a general failure to delete namespaces in the test run. All instances where the test failed, other tests in the suite also failed with "namespace is empty but is not yet removed".
* 8 failures -- all part of a set of broken test runs (many failures in non-networking tests) that occurred at around 4/23/2017, 2:43 PM. It hasn't reoccurred since, I will keep track of this.

Can someone from @kubernetes/sig-api-machinery-test-failures take a look?

**Comment by cmluciano** [comment]
May be related https://github.com/kubernetes/kubernetes/pull/45124/files

**Comment by liggitt** [comment]
https://github.com/kubernetes/kubernetes/pull/45124 only affects the PV e2e tests, not this one

**Comment by fejta** [comment]
It looks like @bowei from sig-networking is attempting to hand off this issue to @kubernetes/sig-api-machinery-test-failures...

Bowei, when you do this will you please `/unassign` any networking people:
/unassign @thockin @dcbw @caseydavenport @thockin 

And `/assign` leads for the api-machinery group?
/assign @lavalamp @deads2k 

Thanks!

**Comment by deads2k** [comment]
Namespace deletion makes me thing about https://github.com/kubernetes/kubernetes/pull/45304

**Comment by bowei** [comment]
@fejta -- looks like your comment did the trick

**Comment by jagosan** [comment]
@deads2k can you elaborate?  Are you suggesting that #45304, when merged, may resolve?  That you are looking into it?  None of the above?

**Comment by deads2k** [comment]
> @deads2k can you elaborate? Are you suggesting that #45304, when merged, may resolve? That you are looking into it? None of the above?

If the problem is slow namespace cleanup, then *some* of that slowness can be addressed by #45304 which ensures that the cleanup controller won't be throttled during its discovery which is extremely chatty.

Some of the slowness may be graceful deletion timing, but we don't even get to graceful deletion timing without addressing the discovery rate limiting on the namespace controller.

**Comment by jagosan** [comment]
Thanks @deads2k.  Propose leaving issue as-is until post- #45304 merge.  At that point: if still flaky, 

Related question in the comments above about 'reasonable time'.  It appears that test timeouts are convention rather than some SLO commitment; unless that interpretation is incorrect, I would propose increasing the timeout to resolve test flakiness and opening a new issue to investigate graceful deletion timing.  (Note:  I understand this is sub-optimal.  Trying to address flakiness as top priority; please let me know if this goes against the goals or is a taboo suggestion!)

**Comment by deads2k** [comment]
> Thanks @deads2k. Propose leaving issue as-is until post- #45304 merge.

That's fine with me.



> I would propose increasing the timeout to resolve test flakiness and opening a new issue to investigate graceful deletion timing. (Note: I understand this is sub-optimal. Trying to address flakiness as top priority; please let me know if this goes against the goals or is a taboo suggestion!)

I don't have strong feeling on this issue, though I would be annoyed if queue were closed instead of increasing a timeout.

**Comment by jagosan** [comment]
@fejta - it appears that the situation has improved based on early readout of the [link](https://storage.googleapis.com/k8s-gubernator/triage/index.html?ci=0&pr=1&test=Service%20endpoints%20latency%20should%20not%20be%20very%20high) you provided, but perhaps still too early to tell.  Many thanks @feiskyer for quick review on the related issue.

**Comment by fejta** [comment]
Sweet! Also check out https://github.com/kubernetes/test-infra/tree/master/metrics.

@cjwagner wrote some infra to provide daily updates to the data used to power the thursday flaky email. Notice from http://storage.googleapis.com/k8s-metrics/flakes/flakes-latest.json that this job is no longer flagged, whch seems sufficient to me to close this issue.
