### ISSUE TITLE
Saltbase installer doesn't generate certificates for kube-apiserver

### ISSUE THREAD

**Issue by benjigoldberg** [kubernetes/kubernetes#44854]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Kubernetes version** (use `kubectl version`): v1.6.2

**Environment**:
- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release): 
```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```
- **Kernel** (e.g. `uname -a`):
`Linux k8s-master 3.10.0-327.10.1.el7.x86_64 #1 SMP Tue Feb 16 17:03:50 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`
- **Install tools**:
Terraform and the Saltbase installer in this repository
- **Others**:

**What happened**:
The saltbase installer does not generate certificates for the kube-apiserver. The kube-apiserver.manifest expects a `kubeapiserver.cert` and a `kubeapiserver.key`. Specifically, the command generated in the `kube-apiserver.manifest` includes the following lines:
```
--kubelet-client-certificate=/srv/kubernetes/kubeapiserver.cert --kubelet-client-key=/srv/kubernetes/kubeapiserver.key
```
but the two files are not generated using the saltbase cert generator.

**What you expected to happen**:
The two files above would be automatically generated and present in `/srv/kubernetes/` from the salt installer.

**How to reproduce it** (as minimally and precisely as possible):
Provision a salt master on CentOS 7 using the saltbase in this repository

**Anything else we need to know**:
If this issue is accepted I am happy to submit a patch as per the contributing guidelines.

**Comment by kargakis** [comment]
@kubernetes/sig-cluster-lifecycle-misc

**Comment by roberthbailey** [comment]
The automation that uses the salt configuration (e.g. kube-up) generates the cert locally and uploads it to the master VM. This is done so that the public cert can also be copied to all of the node VMs. 

If you'd like to fix it, I'd be happy for you to submit a patch, but unless you are testing to make sure it keeps working it's likely to break again in the future since we don't run any CI jobs that provisions masters via salt. 

@mikedanese and I were chatting today about whether we should remove salt support for masters altogether (since it isn't tested) but if folks in the community are still using it then that's a good reason to keep it (even if it's deprecated and on life support) until we have a fully fledged replacement ready.

**Comment by benjigoldberg** [comment]
@roberthbailey as far as the deprecation of salt for provisioning the master, I actually had missed that it was deprecated. That being said, with the development of `kubeadm` it's probably about time for us to begin shifting in that direction. I will close this out and make an item for us internally to investigate deprecating our usage of salt for master in favor of `kubeadm`. 

Thanks for the response!

**Comment by roberthbailey** [comment]
From https://github.com/kubernetes/kubernetes/tree/master/cluster:

**Deprecation Notice: This directory has entered maintenance mode and will not be accepting new providers. Please submit new automation deployments to kube-deploy. Deployments in this directory will continue to be maintained and supported at their current level of support.**

Since that was written we've removed a number of providers from the cluster directory and we are actively working on removing more of them.
