### ISSUE TITLE
API Machinery: Validating core types in external API groups

### ISSUE THREAD

**Issue by pmorie** [kubernetes/kubernetes#44995]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

`client-go validation`

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

feature request

---

In [service-catalog](https://github.com/kubernetes-incubator/service-catalog), we are building an API that has fields which are Kubernetes API types.  Currently, we do not export any type of validation in client-go to allow the validation of complex types in external APIs - it would be very convenient if this was possible to do.  Example use-cases:

1.  Validate a secret name
2.  Validate a `PodPresetSpec`

Possibly related: https://github.com/kubernetes/kubernetes/issues/39434

**Comment by pmorie** [comment]
@k8s-mirror-api-machinery-feature-rqusts

**Comment by smarterclayton** [comment]
OpenAPI?

**Comment by pmorie** [comment]
Anything would work for me, but I think this is a general gap we need to fill for people building APIs outside the core which have controllers that create objects in the core.

For now, I think I'm left with making a parallel set of validations for these objects in service-catalog, which sucks, but I'd rather do something like that than try to get fancy prematurely.

**Comment by pmorie** [comment]
cc @pwittrock

**Comment by pmorie** [comment]
Recasting this issue to be generally for the problem of validating types between API groups.

Stated as a use-case:

As a API developer in the Kubernetes ecosystem, I want to be able to validate arbitrary API types (which may not be API *resources*) effectively client side, so that I can build APIs that embed kubernetes API types like `PodTemplateSpec` while providing the validation semantics that users expect from the core.

Ideally the validation would be specifically tied to the server, either through a spec published by the server or from an API endpoint.

I could live driving this feature from OpenAPI/swagger, but I'm agnostic on what specific implementation we use. Most important to me is generating validation clients and exporting them in `client-go`, which of course we would re-use in other repos to generate the same types of clients for the APIs we build for those other repos.

**Comment by lavalamp** [comment]
I think the best solution is to have a "dry-run" option to `POST` requests. Linking in the code is asking for major problems around version upgrades.

**Comment by MikeSpreitzer** [comment]
/reopen
I have this exact use case now.  I have an out-of-tree object type that embeds a `v1.PodTemplateSpec`.  I would like my custom apiserver to invoke the regular code for validating a `v1.PodTemplateSpec`.  I realize that the actual validation works against the internal AKA unversioned type.  I would be happy if my own internal AKA unversioned type could include the one for PodTemplateSpec.  Right now the only way to do these things is to import from k8s.io/kubernetes, which is a big thing to take on.  And in a similar vein,  I also have a controller that looks a lot like one for DaemonSets.  So much so that it wants to make the same calls to the packages k8s.io/kubernetes/pkg/api/v1/pod, k8s.io/kubernetes/pkg/controller, k8s.io/kubernetes/pkg/util/hash, and k8s.io/kubernetes/pkt/labels.

**Comment by lavalamp** [comment]
cc @apelisse @kwiesmueller @sttts 

Perhaps something WG API Expression should look at.

I think my current suggestion is that if you want to exhaustively pre-validate this, do a dry-run CREATE. Just calling the code means you could have version skew with apiserver, and it means that you wouldn't notice if some webhooks would block the otherwise-valid pod.

**Comment by kwiesmueller** [comment]
I added it to the Agenda of next Week. Please join if you are interested in discussing it:
https://docs.google.com/document/d/1CSpNaicbEqKJoW306qaQEBIkwC1mGIcKl3yiB_C0HZk/edit#

https://github.com/kubernetes/community/tree/master/wg-api-expression#meetings
