### ISSUE TITLE
daemonset: when node lost, the pod's "READY" is incorrect

### ISSUE THREAD

**Issue by zhangxiaoyu-zidif** [kubernetes/kubernetes#45016]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Kubernetes version** (use `kubectl version`): v1.5.1

**Environment**:
- **Cloud provider or hardware configuration**: 4 core 8 Gi
- **OS** (e.g. from /etc/os-release): ubuntu
- **Kernel** (e.g. `uname -a`):Linux default-np113 4.4.0-31-generic #50~14.04.1-Ubuntu SMP Wed Jul 13 01:07:32 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
- **Install tools**:
- **Others**: 

**What happened**:
daemonset: when node lost, the pod's "READY" is incorrect
![image](https://cloud.githubusercontent.com/assets/5154334/25481184/a06552b0-2b7e-11e7-81c9-288617356e34.png)

**What you expected to happen**:
the "READY" should be 0/1, not 1/1. I think.

**How to reproduce it** (as minimally and precisely as possible):
deploy daemonset, and shutdown one assigned node.

**Anything else we need to know**:

**Comment by liggitt** [comment]
After the node TTL period expires (5 minutes by default, I think) the node controller should mark those pods as dead (or delete them, I forget which). Is that not happening?

**Comment by zhangxiaoyu-zidif** [comment]
No, it doesnot happen. I wait more than twenty minutes.  The phenomenon disappears until I restart that node shutdown-ed before.

**Comment by xiangpengzhao** [comment]
>If the Status of the Ready condition is “Unknown” or “False” for longer than the pod-eviction-timeout, an argument passed to the kube-controller-manager, all of the Pods on the node are scheduled for deletion by the Node Controller. The default eviction timeout duration is five minutes. In some cases when the node is unreachable, the apiserver is unable to communicate with the kubelet on it. The decision to delete the pods cannot be communicated to the kubelet until it re-establishes communication with the apiserver. In the meantime, the pods which are scheduled for deletion may continue to run on the partitioned node.
In versions of Kubernetes prior to 1.5, the node controller would force delete these unreachable pods from the apiserver. However, in 1.5 and higher, the node controller does not force delete pods until it is confirmed that they have stopped running in the cluster. One can see these pods which may be running on an unreachable node as being in the “Terminating” or “Unknown” states. In cases where Kubernetes cannot deduce from the underlying infrastructure if a node has permanently left a cluster, the cluster administrator may need to delete the node object by hand. Deleting the node object from Kubernetes causes all the Pod objects running on it to be deleted from the apiserver, freeing up their names.

According to [the doc](https://kubernetes.io/docs/concepts/nodes/node/#condition), this might be right as expected? After five minutes, the NC will delete its pods and update their status, but the status of containers cannot be updated. And since apiserver cannot confirm whether these pods are still running on the node, it will not really delete these pods. So we will see the ready containers to be `1/1`.

cc @dchen1107 @derekwaynecarr could you please confirm this? Thanks!

**Comment by zhangxiaoyu-zidif** [comment]
If the "READY" was "0/1", I will appreciate it very much.
"1/1" really confuses users.

**Comment by xiangpengzhao** [comment]
yes we might want to enhance it.
