### ISSUE TITLE
SSL termination at ELB and internal communication over http on port 80

### ISSUE THREAD

**Issue by ericln** [kubernetes/kubernetes#45173]
This is what I would like to setup

**Would like to have**
External access `only` via https on 443 and ssl terminated at ELB and all the requests get routed to the internal services via http on port 80. Also, all the internal services communications are all over http port 80.

**What's happening right now**
With the following setup, it results in ELB with https on port 443 and aws cert setup correctly. Internal ports are all mapped to port 443 as well, internal services cannot communicate via port 80.

**Work around**
current workaround is to create similar setup for port 80 and manually change the ELB to https port 443.

k8s service definition 
```
kind: Service
apiVersion: v1
metadata:
  name: test-app
  labels:
    name: test-app
    environment: dev
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: <cert arn>
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
spec:
  type: "LoadBalancer"
  ports:
    - name: "https"
      port: 443
      targetPort: 80
  selector:
    name: ecommerce
    environment: dev
```

**Kubernetes version** : 1.4.x, 1.5.x

**Environment**:
- **Cloud provider**: AWS
- **OS** : Debian GNU/Linux 8 (jessie)

**Comment by cmluciano** [comment]
@kubernetes/sig-aws-misc

**Comment by iMartyn** [comment]
This is still a bug in my eyes, there is a workaround but it is not complete.
Using `service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"` will create the LoadBalancer on port 443.

This however is a broken setup, you should never have to access a service as `http://myservice:443`.  You can _add_ another port block to listen on port 80 as well, but this does not stop traffic on port 443 being unencrypted. 

The Service (a kubernetes concept) should not be modified and made to do wrong things (like listen and respond to plain http on port 443) for AWS concepts to work.  The annotation should overwrite the "guess" of the port based on the Service Port.

Again, for clarity because I've had a lot of people not understand why this riles me quite so much - ELB and Service are separate entities.  Automatic ELB provisioning is nice but should not affect my service definition, which should be cloud neutral.  If I have an unencrypted http service, It should listen only on the port I want it to (80) and not on 443 just so that the external load balancer listens on the correct port.

**Comment by iMartyn** [comment]
Digging into the code, it appears that this was a conscious decision and I cannot for the life of me understand why, but pushing myself hard not to have hubris, this appears to be the code that makes this choice : https://github.com/kubernetes/kubernetes/blob/d0301aa6e87c337f40bb529932d01a2c398f5d38/pkg/cloudprovider/providers/aws/aws.go#L2922

*further* If you do not specify that you want to listen on port 443 at all (no annotation) it DOES listen on port 443, but if you DO specify it, it creates a non-ssl listener on port 80!

My proposed fix is to respect the request of the user and tell AWS to listen on the port requested, perhaps like this : https://github.com/iMartyn/kubernetes/blob/fix/respect-elb-ssl-anotation/pkg/cloudprovider/providers/aws/aws.go#L2922

I'll open that as a pull request but happy to see it implemented another way.

**Comment by hubt** [comment]
I don't see a bug here that needs to be fixed. The proper annotations and settings work fine for me. The original reporter didn't have the `service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"` set up properly, but with that, everything works as expected.

**Comment by iMartyn** [comment]
Half of the bug is that if you have `service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"` and your service is internally listening on `Port: 80`, the ELB does not listen on port 443, does not terminate ssl.
If you REMOVE the annotation, suddenly it WILL listen on port 443!

The other half is if you DO have the annotation you MUST have your service listen unencrypted on Port 443 which means that your service is then available unencrypted on port 443 - http://myservice.namespace.svc.cluster.local:443/ is bad.

**Comment by iMartyn** [comment]
I've put some detail here :
https://gist.github.com/iMartyn/3ef82c5e6e8c0ab0416fc624873ee3d2

**Comment by justinsb** [comment]
I think I understand the issue now.  We don't have a way to say that the ELB should listen on a port that the service does not listen on (?).  So there's no way to say "this is an http service, so port 80, but when we expose it through the ELB it should be port 443 (only)"  

One workaround - which isn't great, but just trying to understand the problem space - is to create two separate services: one for the ELB (with the spec as in the OP), and one for internal communications (which listens on port 80).  Is that correct?

If so, we could probably have a new annotation or a new syntax on an annotation - I worry that making an existing annotation mean something different (however sensible) might break someone (but I have to think more deeply about that I guess).

One syntax _could_ be:

`service.beta.kubernetes.io/aws-load-balancer-ssl-ports: 443->80,..`

Very open to persuasion that isn't necessary - just trying to understand the issue better and the proposed fix!

**Comment by iMartyn** [comment]
Thanks for joining in @justinsb, but I think it's simpler not to change the syntax.

Consider the current situation - I have a http app listening on port 80, and I give the annotations of an ssl certificate (that should be enough to say I want ssl) and a port for ELB to listen on (443).  There's no need for the annotation to do re-mapping.

The point is, as soon as you're saying you want SSL termination at the ELB, you'll always want to be listening on a different port externally (except in the rare case of STARTTLS which ELBs don't support anyway).

My frustration here comes from the very fact that a http kubernetes service should not be accessible on a port other than 80 internally and should be accessible on the LoadBalancer on 443.   If you were terminating an SSL service in kube land, sure, port 443 internally and externally but you wouldn't be giving a cert ID at all to aws.

I'll rephrase again, in case my waffling attempts to clarify have failed (and I take 100% of the blame for that) :
* a kubernetes service should not have it's core spec change to be exposed externally (or, much as I appreciate the suggestion have a separate service defined IMO) - just an added annotation.
* a loadbalancer config should not depend at all on the core spec of the service being specific to the loadbalancer

Hope that helps?

**Comment by iMartyn** [comment]
@justinsb Any more thoughts on that one? It's infuriating me every time I have to explain why the services are listening on port 443 internally.

**Comment by iMartyn** [comment]
@justinsb prod.  This is still bugging me and the PR just needs a rebase afaict

**Comment by iMartyn** [comment]
This is somewhat crazy, the PR is there to fix this, just noone cares.

**Comment by iMartyn** [comment]
Round and round and round it goes, where it stops, nobody knows.  Patch exists, multiple people understand, noone cares.

**Comment by mcrute** [comment]
There's still a PR pending for this ...

/reopen
/remove-lifecycle rotten

**Comment by justinsb** [comment]
So here's where I think we are:

We have a service that is http internally, on port 80:

```
kind: Service
apiVersion: v1
spec:
  ports:
    - name: "http"
      targetPort: 80
```

We want to expose that externally, so we add service of `type: LoadBalancer`.  That works except that now our http service is exposed on the internet (on port 80), and we would like it to be encrypted.

We could change our service to port 80 and 443 and manage TLS in our app.  That should also work, but we have to manage certs ourselves.

We could ask AWS ELB to manage the certs & TLS for us.  If we do that, the proposal is that just adding the annotation should be sufficient.  If we specify `service.beta.kubernetes.io/aws-load-balancer-ssl-ports=443` we be able to infer that we should listen on 443 and map to port 80.  I think you're right about that @iMartyn, but I think once we get beyond the simple cases it gets complicated.

Here are the things I think we need to answer:

* Should the ELB also listen on port 80 (unencrypted), or just on port 443? 
* What happens when there is a second port on the service (80 and 81).  Do both get TLS in front of them?
* What happens if someone has configured their service with port 80 and 443, with the `aws-load-balancer-ssl-ports=443`?

I think the confusion is that `service.beta.kubernetes.io/aws-load-balancer-ssl-ports` specifies the ports that should use SSL listeners, not the ports on which we want to listen on SSL.  That doesn't make things as intuitive as they could be, but it does make for simple behaviour.

That's why I think an explicit directive would be easier, something like `443->80`.  That also has the advantage of being illegal in the old syntax, so we can reuse the same annotation.  But I note it still doesn't fix everything - we still don't have a way to _not_ listen on port 80 if we define a service with both port 80 and port 443, for example.

**Comment by iMartyn** [comment]
Personally I think we should deprecate the syntax for this annotation and start fresh with a clean implementation on this one.  Something that fits a good set of cases and is documented why the choices were made.  I tried reaching out to the original author for comment and got no reply.

I think the simple case can and should be fixed - i.e. 99%* of people if giving a certificate name do not want a service internally listening on port 443, they want a service internally listening on port 80 and externally on 443.  This is a reasonable assumption and the simple path is broken right now, because what you get is an ssl listener on port 80 which is useful to pretty much noone.
