### ISSUE TITLE
Evaluate using FlatBuffers as additional media type in the API (next to json and protobufs)

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#45228]
Currently, Kubernetes supports to different formats of data (both for communication at the API level and as a storage type):
- JSON
- protobufs

We introduced protobufs for performance reasons and they solved a lot of our problems.

If at some point it will appear that protobufs are not enough, we may consider evaluating FlatBuffer:
https://google.github.io/flatbuffers/index.html

According to their documentation, they seeom to be even more efficient and use less memory allocations (which seem to be our main problem now).

@k8s-mirror-scalability-feature-requests @k8s-mirror-api-machinery-feature-rqusts

**Comment by wojtek-t** [comment]
But I don't think it's something that we should do now.

**Comment by jagosan** [comment]
For posterity, [nanopb](https://github.com/nanopb/nanopb) and [CBOR](http://cbor.io/) are other options with similar properties.  Protocol translation & support is risky and ought not to be undertaken lightly :)

**Comment by wojtek-t** [comment]
> Protocol translation & support is risky and ought not to be undertaken lightly :)

@jagosan can you clarify what did you mean by that?

**Comment by aardappel** [comment]
Some advantages of using FlatBuffers:

- Can initially use it as "just" a JSON parser, and only gradually extend its role where efficiency is key.
- Strongly typed JSON parsing through a schema, so all JSON type problems get caught at parse time automatically.. at access time, you have strongly typed accessors that are guaranteed to be the correct type. No error handling needed in the access code.
- Parsing faster than most other JSON parsers and uses less memory (see e.g. https://google.github.io/flatbuffers/flatbuffers_benchmarks.html ) In particular, when parsing multiple JSON objects with the same schema.
- Results in all your parsed JSON data sitting in a single compact buffer.
- Compared to Protobuf, doesn't require the allocation/deallocation of an a tree of objects to (de)serialize.

Disadvantages:

- Strongly typed, so doesn't do as well with fields that can contain any value, or objects with unknown fields. It has "unions" for some level of flexibility, but for true "anything goes" data, FlexBuffers ( https://google.github.io/flatbuffers/flexbuffers.html ) is more appropriate. FlexBuffers should at some point be possible to just a field in a FlatBuffer, but not all of that is integrated yet.
- When used a a Protobuf replacement (i.e. serialization without going through JSON), has a stricter ordering of serialization, since it doesn't have an object tree to fall back on.

**Comment by thockin** [comment]
Bear in mind that, unlike the way proto tends to be used (the proto object is the primary representation) all of our code is written around native Go structs, and we unmarshal json/proto into those structs, and use native mechanisms (access a field, test a pointer for nil).

**Comment by aardappel** [comment]
@thockin : that's still a savings, as instead of `proto-wire -> proto-objects -> native-objects` you can now do `flat-wire -> native-objects`. But yes, even bigger savings could be had if you could separate out the relatively "static" data in your native objects, and keep them around as FlatBuffer instead. Doesn't need to be all or nothing though.

**Comment by thockin** [comment]
We already convert proto-wire -> native-objects, I am pretty sure.  It's
more than a little messy because we chose NOT to start with proto types,
and use JSON instead, and then proto got a lot of traction, but changing
was deemed prohibitive.

**Comment by mml** [comment]
cc @jpbetz

**Comment by xigang** [comment]
Performance compare:

Serialization Speed (ops/sec, higher is better):
```
FlatBuffers:    ~850,000
CBOR:           ~650,000
gogo/protobuf:  ~450,000
JSON:           ~250,000
```

Deserialization Speed (ops/sec, higher is better):
```
FlatBuffers:    ~1,200,000 (zero-copy)
CBOR:           ~550,000
gogo/protobuf:  ~400,000
JSON:           ~200,000
```

Message Size (bytes, lower is better):
```
FlatBuffers:    ~180
CBOR:           ~210
gogo/protobuf:  ~220
JSON:           ~350
```

Memory Allocations (number of allocs per op, lower is better):
```
FlatBuffers:    2
CBOR:           8
gogo/protobuf:  6
JSON:           12
```

@wojtek-t @thockin Comparing the performance of each, FlatBuffers is the best. Can we evaluate the possibility of supporting FlatBuffers?

**Comment by thockin** [comment]
We have CBOR now but only for CRD, right?  We can't exactly GET RID of anything, so adding ANOTHER format would need to meet a very high bar for risk/reward.
