### ISSUE TITLE
kube-dns per node

### ISSUE THREAD

**Issue by jrynyt** [kubernetes/kubernetes#45363]
**Is this a request for help?**:
No

**What keywords did you search in Kubernetes issues before filing this one?**
kube-dns local
kube-dns each
kube-dns node

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Feature Request

**Kubernetes version** (use `kubectl version`):
1.6.2

Containers' resolv.conf contain the kube-dns Service ClusterIP as the one and only nameserver. Given that Services distribute traffic among backing pods randomly, even when there are multiple kube-dns pods in the cluster, it is likely that every DNS query ends up going to another node, adding latency. The kube-dns pod is also the nearest cache.

And since the kube-dns-autoscaler only scales based on number of cores/nodes, not actual load, this critical service is susceptible to becoming overloaded -- especially with the defaults of `coresPerReplica":256,"nodesPerReplica":16`

This performance and reliability could be easily improved by either:

1. Running an additional dns cache on each node:
   - caching and forwarding to the kube-dns ClusterIP
   - putting that as the first nameserver in resolv.conf, leaving kube-dns second

or

2. run one kube-dns pod per node, using that as the one and only nameserver in resolv.conf

**Comment by MrHohn** [comment]
/area dns

Also see #32749. There was a WIP (#34523) that tried deploy dnsmasq on each node.

**Comment by bgrant0607** [comment]
Ref #7470, #26707, #32749

**Comment by krmayankk** [comment]
is anyone still working on this, what are the blockers to getting this done ? I heard Openshift is already using this method @smarterclayton  can confirm. One thing i am not sure is wont running a kube-dns per node , ddos the apiserver for watching pods and services ?

**Comment by dannyk81** [comment]
Actually, I was thinking about running only `dnsmasq` on each node and point it to kube-dns.

Like it was suggested here https://github.com/kubernetes/kubernetes/issues/7470#issuecomment-263695219

This seems quite straight-forward, with the exception of the required iptables rule, that part is a show stopper for me as I'm not sure how to manage it properly so it won't be overridden/etc..

**Comment by krmayankk** [comment]
@dannyk81 why do we need iptables rule for running dnsmasq per node. Could you clarify ?

**Comment by dannyk81** [comment]
@krmayankk K8s populates `/etc/resolv.conf` with the name server address that is specified in kubelet arg: `--cluster_dns=x.x.x.x`.

So, somehow we need to NAT the dns queries sent to `x.x.x.x` over to the node's localhost/public_ip (?)

I don't think we can use `--cluster_dns=127.0.0.1` as that would simply send the queries to the container's namespace localhost (not the hosts).

WDYT?

**Comment by bowei** [comment]
The ideal mechanism is some (does not yet exist) topology mechanism (i.e. go to local dnsmasq). Otherwise, it will be not expressible via the k8s service API.

**Comment by tpounds** [comment]
We had the same issues 2-3 years ago in a very large deployment with requests saturating our self-hosted DNS servers which manifested as 5, 10, 15 second DNS lookup delays in our applications. The dealys being multiples of 5s is glibc default retry delay is 5s. Google `DNS 5 second delays` for more info.

We resolved the saturation issues by deploying `dnsmasq` instead of `pause` as the stage1 container for the pod. The `dnsmasq` we deploy is statically compiled (e.g. musl) with all non-DNS facilities (TFTP, DHCP) stripped out. In practice this works extremely well and doesn't require any iptables hackery or other magic since the stage1 container is what establishes the networking configuration for the other pod containers. If folks are interested I can provide more details about our setup and/or work on a patch set to upstream these changes.

I'll cross link this comment in #26707, #32749 since this is long standing issue.

**Comment by krmayankk** [comment]
@tpounds I am interested in more details of what you did here .

**Comment by HcgRandon** [comment]
@tpounds I am very interested in more details. With how dns is now I simply can't run my application in k8s. Which is a real bummer. You solution might be just what I need

**Comment by dannyk81** [comment]
@tpounds hoping for more details on this as it sounds very interesting.

I assume that dnsmasq in each pod has the kube-dns service defined as a server? and `--cluster_dns` in kubelet is set to `127.0.0.1`?

**Comment by tpounds** [comment]
Here is more or less a high-level breakdown of how we are doing it today.

1. Build a custom stage1 `dnsmasq` container. We are using the latest v2.79 release and build it using `i386/alpine:3.7` image. It's built as a 32-bit binary to reduce the memory footprint.

Built with the following command.

```
make install \
   CFLAGS="-Wall -W -Os -fno-omit-frame-pointer" \
   COPTS="-DNO_DHCP -DNO_SCRIPT -DNO_TFTP" \
   LDFLAGS=-static
```

Started with the following entrypoint command.

```
dnsmasq \
   --cache-size=512 \
   --keep-in-foreground \
   --no-negcache \
   --no-resolv \
   --server=10.96.0.10
```

Note, a sizeable cache is enabled here which will increase per pod footprint. If that isn't desirable it can be lowered to suite specific needs. Negative caching is also disabled locally due to some issues we ran into with some misbehaving runtimes. The cluster IP (10.96.0.10) configured by `kubeadm` is hardcoded with reading from `/etc/resolv.conf` disabled to force all requests to hit the `kube-dns`
services.

2. Configure `kubelet` to use custom `dnsmasq` as the stage1 (aka sandbox image).

Set the following `kubelet` option to the custom `dnsmasq` image.

`--pod-infra-container-image=<repo>/dnsmasq:1.2.3`

Note, this will likely only work when the container runtime is docker since `rkt`, `cri-o`, etc. have their own policies for establishing the stage1 container. It should be possible to setup for other CRI drivers but I haven't investigated what that would take.

3. Configure `kubelet` to use localhost DNS.

Set the following `kubelet` option to `127.0.0.1`

`--cluster-dns=127.0.0.1`

Keep in mind this doesn't solve the `kube-dns` HA concerns, however, it does offer DNS tiering at the pod level. This can reduce substantial load on `kube-dns` for large deployments with many hot records.

**Comment by szuecs** [comment]
FYI https://github.com/kubernetes/kubernetes/issues/56903#issuecomment-410353015 links to configurations how to run node-local dnsmasq + coredns cluster.local resolver on AWS.

**Comment by fvigotti** [comment]
just one question , but how you made `--cluster-dns=127.0.0.1` work? the host `127.0.0.1` is different from pod `127.0.0.1` if the dnsmasq is serving from host how can your solution work ? 

regards,
Francesco

**Comment by kruczjak** [comment]
@fvigotti I've setup my own CoreDNS on daemonset:

1. Make sure coredns or kubedns daemonset has `hostNetwork: true`, `hostPort`s and is binded to `0.0.0.0`
2. Make sure to add or keep also service for those pods in case pod which is on local node fails.
3. Run for example `ifconfig lo:0 192.168.0.1 up` on each node at startup (I have Debian Stretch, command to alias loopback interface can be different on other OSes). For first time you can just run it in node terminal :D.

I'm doing it using systemd service before kubelet on nodes starts:
```
Type=oneshot
ExecStart=/bin/bash -c "ifconfig lo:0 192.168.0.1 up"
```
You should be now able to hit node using 192.168.0.1 address on each pod.

4. Change cluster-dns to `192.168.0.1,100.64.0.10`
`100.64.0.10` - is my service's clusterIP from step 2. You should add your IP here.

5. Reboot all the nodes.

Have fun with local node DNS resolvers with fallback if something bad happens :)
(remember to test it first on some kind of test cluster :D )

**Comment by prameshj** [comment]
PR https://github.com/kubernetes/kubernetes/pull/70555 adds support for running a nodelocal dns cache. This uses CoreDNS as the cache, but does not include the kubernetes plugin, so the cache instances do not watch pods and services.

**Comment by blakebarnett** [comment]
@prameshj is the version in #70555 redirecting all queries to the default kube-system DNS service and caching cluster addresses then? I'm currently running gcr.io/pavithrar-k8s-dev/coredns-dnscache:latest and it's got the k8s plugin I'm assuming because all is working well... I'm wondering what the recommended/default deployment for this will be in 1.13 on GKE?

**Comment by prameshj** [comment]
You can check by listing all daemonsets in kube-system namespace and checking if there is "node-local-dns" in the list.
How are you creating the cluster? Setting  KUBE_ENABLE_NODELOCAL_DNS environment variable to true will run this feature. It is disabled by default.
KUBE_ENABLE_NODELOCAL_DNS=true go run hack/e2e.go -v --up

It will be disabled by default on GKE too.

**Comment by blakebarnett** [comment]
@prameshj we create the cluster via terraform and deploy the node-local-dns daemonset separately. I'm just concerned because it sounds like the functionality will change for this when it's deployed via GKE in the future (the lack of the kubernetes plugin). Is that the case? Should we continue using your other image?

**Comment by prameshj** [comment]
Are you modifying the node-local-dns configmap in the yaml to include the kubernetes plugin?
If you are using the yaml as is from #70555, then the caches are not using kubernetes plugin. You can verify this by checking the configmap or the configfile by logging into one of the cache pods. The cache will still cache both cluster addresses and external hostnames, but cache misses will be forwarded to kube-dns or coreDNS, whatever is your clusterDNS.
In this case, using either image should work.

**Comment by blakebarnett** [comment]
Great, thanks!

**Comment by prameshj** [comment]
cool, thanks for trying this out! It would be great to get your feedback on the changes after enabling this - improvements in latency? any issues you are running into? Thanks for your earlier comment on the update to Calico Network policy rules, I added it in the readme.

**Comment by blakebarnett** [comment]
Yes it's a _dramatic_ latency improvement. We were seeing an uncomfortably large percentage of queries hitting the 5 second timeout, and even more taking 50 - 70ms. With this installed we see effectively 0 queries over 7ms.

On our AWS clusters we use kube-dns as a DaemonSet and were hoping for the ability to set `--cluster-dns` for kubelets in GKE as well, but this works well. Thanks for your work!

**Comment by prameshj** [comment]
Great to hear, thanks for the feedback!

**Comment by luxas** [comment]
cc @kubernetes/sig-cluster-lifecycle

**Comment by dthorsen** [comment]
One thing we have run into is dnsmasq effectively not caching due to the --no-negcache flag. This appears to be caused by resolver libraries querying both A and AAAA for hostnames. Since the AAAA nearly always return NXDOMAIN it seems that dnsmasq fails to cache the A record.  The end result is a lot of extra traffic going to kube-dns as well as our external resolvers. The issue is multiplied by the long list of search domains and having ndots set to 5.

**Comment by blakebarnett** [comment]
@dthorsen we worked around this issue by specifying the most frequently queried domains in the dnsmasq args like:

```
  --address=/org.cluster.local/org.svc.cluster.local/
  --address=/net.cluster.local/net.svc.cluster.local/
  --address=/com.cluster.local/com.svc.cluster.local/
```

This tells dnsmasq to just return NXDOMAIN without even looking it up (note the lack of a server to send the query to at the end).  It's a bit of a hacky trick but it dramatically reduced the amount of bogus search path queries we were actually processing/forwarding. The big downside is adding _every_ permutation in the search path can be quite tedious.

I'm not sure if CoreDNS allows something similar or if it just handles these cases better by default...

**Comment by prameshj** [comment]
> Dane Thorsen we worked around this issue by specifying the most frequently queried domains in the dnsmasq args like:
> 
> ```
>   --address=/org.cluster.local/org.svc.cluster.local/
>   --address=/net.cluster.local/net.svc.cluster.local/
>   --address=/com.cluster.local/com.svc.cluster.local/
> ```
> This tells dnsmasq to just return NXDOMAIN without even looking it up (note the lack of a server to send the query to at the end). It's a bit of a hacky trick but it dramatically reduced the amount of bogus search path queries we were actually processing/forwarding. The big downside is adding _every_ permutation in the search path can be quite tedious.
> 
> I'm not sure if CoreDNS allows something similar or if it just handles these cases better by default...

Looks like the nxdomain plugin in coredns can do this too - https://github.com/miekg/nxdomain
This is not part of the coredns repo, but looks like the plugin.cfg can be modified to include out-of-repo plugins too.
https://github.com/coredns/coredns/blob/master/plugin.cfg

**Comment by prameshj** [comment]
Closing since node-local-dns addon runs a dns cache per node, similar to what the issue is requesting. Please reopen if that's not the case.
/close

**Comment by JamesTGrant** [comment]
@prameshj The trouble with node-local-dns-cache is that it's just a cache, typically caching records for 30sec. In my application(s), my typical cluster size is 3 k8s masters and maybe 10 worker nodes, the number of pods on a node is typically about 30-60, but they are usually doing asyncronus, orthoginal DNS requests with little overlap in requested records.  The problem of sending a DNS request to the global cluster-dns service, which forwards to a different node to the requesting pod still remains. Unless one could configure the node-local dns pod to watch k8s endpoints (and effectively become a fully fledged DNS pod) I can't see that this improves my situation? Am I missing something I think there are two options:
1 - allow node-local-dns-cache to interface with k8s API to be a fully fledged DNS responder
2 - have node-local-dns cache watch all ep and cache everything always - which would not be at all scalable and overlap with the intended fuction of kube-proxy

**Comment by szuecs** [comment]
@JamesTGrant I can recommend to use a daemonset pod for cache+coredns. We used dnsmasq+coredns and switched to unbound+coredns, both are great solutions. Unbound uses less resources than dnsmasq.
