### ISSUE TITLE
[Proposal] Per-container automountServiceAccountToken 

### ISSUE THREAD

**Issue by luksa** [kubernetes/kubernetes#45386]
Consider an app that is exposed publicly and for some reason needs to be able to modify cluster state (create pods, modify secrets or whatever). The more complex the app, the higher the changes of it including a vulnerability, which may expose the service account's token. 

Splitting the part that talks to the k8s API server into a separate sidecar container, having the app communicate to the sidecar through localhost and mounting the service account token only into the sidecar would make the whole system much more secure. 

AFAICT it is currently not possible to toggle automouting for individual containers, just for the pod as a whole, although I think I remember someone mentioning somewhere that if you mount some other volume at the serviceaccount dir, the token won't be mounted.

**Comment by liggitt** [comment]
I'm not sure about it being much more secure once you're in the same process space

@kubernetes/sig-auth-feature-requests

**Comment by luksa** [comment]
Maybe, but if, for example, the main container only has a path traversal vulnerability, allowing the token to be exposed to an external client (and there's no way to execute malicious code in the container itself), the proposed feature would make sense, right?

And even if we forget about the security aspect, it makes sense for an "automount" setting to primarily be at the container level, since that's where you mount volumes.

**Comment by DavidSimner** [comment]
/remove-lifecycle rotten

I agree with this proposal.

Our pods have 2 containers: the application, and the other is the Istio sidecar.  Istio requires us to have `automountServiceAccountToken` be `true`, see: https://github.com/istio/istio/issues/14311 but we don't want to have the service token mounted in the application container.  The reason for this is that we would like to design our system so that if an attacker somehow got access to the application container, then their ability to attack the system further is limited (defense in depth), and for this reason we would like the `automountServiceAccountToken` setting to be available at the container scope.

**Comment by DavidSimner** [comment]
@luksa : can you reopen this please :)

**Comment by 007** [comment]
Ref https://github.com/linkerd/linkerd2/issues/2843 as well, essentially any service mesh that does auto-injection magic is going to fail unless this can be done per-container.

**Comment by mikedanese** [comment]
I commented on the issue. This gets a lot easier with bound service accounts.
