### ISSUE TITLE
 Get a config file from etcd...

### ISSUE THREAD

**Issue by gokhandincer** [kubernetes/kubernetes#45400]
We are using systemd files as below on CoreOS
we couldn't succeed when we create from systemd to pod yaml

İs it possible a way;
 *  to get a config file from etcd
 * to use environment file
 * to create servise directory

Best Regards

```
[Unit]
Description=Redis Service
After=docker.service dockdns.service

[Service]
EnvironmentFile=-/etc/mtx/docker.env
Environment="CON_NAME=cache"
Environment="DATA_DIR=/data/${CON_NAME}"
Environment="CONF_DIR=/etc/mtx/${CON_NAME}"
ExecStartPre=/bin/bash -c ' if [ ! -d "${DATA_DIR}" ] || [ ! -d "${CONF_DIR}" ]; then mkdir -p ${DATA_DIR} ${CONF_DIR}; fi '
ExecStartPre=/bin/bash -c ' etcdctl get /resources/config/redis.conf > ${CONF_DIR}/redis.conf'
ExecStartPre=-/bin/bash -c '/usr/bin/docker rm -f ${CON_NAME}'
ExecStart=/bin/bash -c '/usr/bin/docker run \
--name ${CON_NAME} $DNS_OPTS $TZ\
-v ${DATA_DIR}:/data\
-v ${CONF_DIR}/redis.conf:/usr/local/bin/redis.conf \
redis:latest redis-server /usr/local/bin/redis.conf'
ExecStop=-/bin/bash -c '/usr/bin/docker rm -f ${CON_NAME}'
Restart=always
RestartSec=30

[X-Fleet]
MachineMetadata="platform=global" "ch=1"
```

**Comment by kargakis** [comment]
@kubernetes/sig-api-machinery-misc 
/kind support

**Comment by castrojo** [comment]
Please re-post your question to [Stack Overflow](http://stackoverflow.com/questions/tagged/kubernetes).

Thanks for taking the time to report an issue to us. In the past this tracker has housed both bug reports and user support requests, we are now only using this tracker for software defects and feature tracking.   

We are trying to consolidate the channels to which questions for help/support
are posted so that we can improve our efficiency in responding to requests,
and to make it easier for you to find answers to frequently asked questions and
how to address common use cases.

The Kubernetes team scans Stack Overflow on a regular basis, and will try to
ensure your questions don't go unanswered.

If you're looking for more long-form discussion on best practices, we encourage you to check out the [Kubernetes user list](https://groups.google.com/forum/#!forum/kubernetes-users). 

You can also find more information here:

  * [User Documentation](http://kubernetes.io/docs/)
  * [Troubleshooting Guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/)

Again, thanks for using Kubernetes. If you feel this issue has been closed in error then please reopen it and we can have another look. 

The Kubernetes Team
