### ISSUE TITLE
Refactor visitToPatch() and visitToCreate() to use fewer arguments

### ISSUE THREAD

**Issue by shiywang** [kubernetes/kubernetes#45521]
This issue comes from pr https://github.com/kubernetes/kubernetes/pull/42256 as @mengqiy suggests:
> I like this more than visitToPatch(). It's cleaner to pass a function fewer arguments.
> It will be great to make visitToPatch and visitToCreate use similar style like applyEditPatch
> 
@kubernetes/sig-cli-maintainers

**Comment by mengqiy** [comment]
Sorry. Maybe I'm not clear enough.
What I suggest is using object member variable instead of lots of arguments, i.e. `o.visitToPatch(arg1)` instead of `visitToPatch(arg1, arg2, ..., arg7)`.
It make the code clearer by passing in fewer arguments.

Using iteration access maybe another good idea to refactor the code. Not sure if it will make the code clearer or not.
