### ISSUE TITLE
10 GKE 1.4-1.6 upgrade jobs fail a variety of Job, SchedulePredicate tests

### ISSUE THREAD

**Issue by fejta** [kubernetes/kubernetes#45567]
Testgrid: https://k8s-testgrid.appspot.com/release-1.6-upgrade-skew#gke-container_vm-1.4-container_vm-1.6-upgrade-master&sort-by-failures=

Failure cluster: https://storage.googleapis.com/k8s-gubernator/triage/index.html#5e1dbad0da736548d58a

/assign @foxish

**Comment by foxish** [comment]
These tests appear to be running 1.4 e2es.
I looked at the job e2e failures and they're running e2es that no longer exist. Jobs e2e was rewritten in 1.5 and the tests showing failures don't appear to exist anymore.

Additionally, I wouldn't expect them to pass because:
1.6: [Remove extensions/v1beta1 Jobs resource, and job/v1beta1 generator.](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG.md#deprecations) (#38614, @soltysh) 
1.5: [extensions/v1beta1.Jobs is deprecated, use batch/v1.Job](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG.md#deprecations-1) (#36355, @soltysh)
1.4: extensions/v1beta1.Jobs existed.

I suspect that pod affinity and anti-affinity fields also broke compatibility from 1.4 -> 1.6 in a similar fashion.
/assign davidopp to confirm

**Comment by davidopp** [comment]
Yeah I wouldn't worry about those scheduler test failures.

**Comment by soltysh** [comment]
Yup, there are at least two additional issues mentioning the same problem (1.4 -> 1.6 upgrade) and Jobs which changed between those versions like @foxish pointed out. These are https://github.com/kubernetes/kubernetes/issues/43023 and https://github.com/kubernetes/kubernetes/issues/42451. We can safely ignore those.

**Comment by foxish** [comment]
Same with CronJob (https://github.com/kubernetes/kubernetes/pull/36021). @fejta , I think we can close this if all the open questions are answered w.r.t: CronJob, Job, Scheduler Affinity.

**Comment by fejta** [comment]
Tests are still failing aren't they? That needs to change to close this bug.

**Comment by foxish** [comment]
If we're running 1.4 e2es, the tests aren't even expected to pass. But it does beg the question - why are we running 1.4 e2es against the 1.6 cluster?
cc @krousey

In the job related failures, it appears they're running 1.4 e2es. 
For example, the test failure points me to https://github.com/kubernetes/kubernetes/blob/475c9a28832e82/test/e2e/job.go#L168 which was rewritten in 1.5.

**Comment by foxish** [comment]
Based on offline conversation with @krousey and paraphrasing:

* The tests are still useful because of our 2 version skew commitment
* These specific tests are for alpha features which we make no guarantees about 

His suggestion is to add the [Feature: alpha] tag to these tests in the 1.4 branch which should disable them from running here. @fejta, does that seem reasonable to you?

**Comment by crimsonfaith91** [comment]
@foxish Noted! This will be a great reference! Thanks! :)

**Comment by fejta** [comment]
Sure, the intent of not running the tests we don't expect to work sounds great!

It is not obvious to me why adding `[Feature: alpha]` to the test name will cause these tests not to run.

Looking at the specification of the job:

https://github.com/kubernetes/test-infra/blob/783324e006cba095b2817d667fc4b01c4e690810/jobs/config.json#L1551

And the `--env-file` references:

https://github.com/kubernetes/test-infra/blob/master/jobs/ci-kubernetes-e2e-gke-container_vm-1.4-container_vm-1.6-upgrade-master.env

I do not see where a `--ginkgo.skip` flag would be set.

Here is an example of a job that does set this flag to skip tests: https://github.com/kubernetes/test-infra/blob/a621353356bbe1301ac361105bc2b64ccb16f905/jobs/ci-kubernetes-e2e-gce-etcd3.env#L2

So that change is also necessary (and an alternative would just be to include a regex that skips the known-bad tests, rather than just `[Feature:alpha]` tests.

**Comment by soltysh** [comment]
👍 for explicitly skipping known-bad tests

**Comment by soltysh** [comment]
There are some alpha features that will work and you want to test them.

**Comment by foxish** [comment]
/close

This is no longer relevant in the 1.9+ world.
