### ISSUE TITLE
"kubectl [apply|create|replace] --save-config" doesn't save exact config

### ISSUE THREAD

**Issue by atombender** [kubernetes/kubernetes#45609]
**Is this a request for help?**: No

**What keywords did you search in Kubernetes issues before filing this one?**: save-config

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

**Kubernetes version** (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:33:11Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.6", GitCommit:"114f8911f9597be669a747ab72787e0bd74c9359", GitTreeState:"clean", BuildDate:"2017-03-28T13:36:31Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: GKE
- **OS** (e.g. from /etc/os-release): cos

**What happened**:

I apply a service such as this:

```shell
$ cat <<END | kubectl apply --save-config -f -
apiVersion: v1
kind: Service
metadata:
  name: discovery-enclosure1
  labels:
    app: discovery
  annotations:
    prometheus.io/probe: "true"
spec:
  selector:
    app: discovery
    discovery-dbname: enclosure1
    discovery-role: master
  ports:
  - name: http
    port: 8090
    targetPort: 8090
    protocol: TCP
END
```

Here's what's saved:

```
$ kubectl get svc discovery-enclosure1 -oyaml
[...]
    kubectl.kubernetes.io/last-applied-configuration: '{"kind":"Service","apiVersion":"v1","metadata":{"name":"discovery-enclosure1","creationTimestamp":null,"labels":{"app":"discovery"},"annotations":{"prometheus.io/probe":"true"}},"spec":{"ports":[{"name":"http","protocol":"TCP","port":8090,"targetPort":8090}],"selector":{"app":"discovery","discovery-dbname":"enclosure1","discovery-role":"master"}},"status":{"loadBalancer":{}}}'
```

This is not what I applied: `creationTimestamp`, `namespace` and `status` are added.

**What you expected to happen**:
I expected the saved config to be what I applied. Otherwise this feature is arguably near-useless: It can't be reliably used to diff a local resource manifest against the active one stored in Kubernetes, because it will always yield false positives. The only way to detect changes would be store a separate, custom annotation, which surely defeats the point of having `--save-config` in the first place.

**How to reproduce it** (as minimally and precisely as possible):
See above.

**Comment by suyogbarve** [comment]
@atombender : This issue is already resolved, please try upgrading your server 

kubectl version
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.1+coreos.0", GitCommit:"9212f77ed8c169a0afa02e58dce87913c6387b3e", GitTreeState:"clean", BuildDate:"2017-04-04T00:32:53Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.1+coreos.0", GitCommit:"9212f77ed8c169a0afa02e58dce87913c6387b3e", GitTreeState:"clean", BuildDate:"2017-04-04T00:32:53Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}


apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"prometheus.io/probe":"true"},"labels":{"app":"discovery"},"name":"discovery-enclosure1","namespace":"default"},"spec":{"ports":[{"name":"http","port":8090,"protocol":"TCP","targetPort":8090}],"selector":{"app":"discovery","discovery-dbname":"enclosure1","discovery-role":"master"}}}
    prometheus.io/probe: "true"
  creationTimestamp: 2017-05-13T05:44:21Z
  labels:
    app: discovery
  name: discovery-enclosure1
  namespace: default
  resourceVersion: "16925"
  selfLink: /api/v1/namespaces/default/services/discovery-enclosure1
  uid: 3680687e-379f-11e7-88a5-080027c30a85
spec:
  clusterIP: 10.233.13.60
  ports:
  - name: http
    port: 8090
    protocol: TCP
    targetPort: 8090
  selector:
    app: discovery
    discovery-dbname: enclosure1
    discovery-role: master
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}

Note: Small typo in your request, you can use "create --save-config"   or "apply"
but not "apply --save-config"

**Comment by atombender** [comment]
@suyogbarve Awesome. We've been deferring the upgrade to 1.6.x to minimize disruption, but we'll make it a priority now. (Yeah, that should have been `replace`, not `apply`.)
