### ISSUE TITLE
ping pod ip failed

### ISSUE THREAD

**Issue by xbsura** [kubernetes/kubernetes#45703]
hi, all:

I install k8s, with one master and two nodes(one in master, one in another node) on aws, and create some pods and services, now the problem is:

If the pod or service is created on node1, node2 and node 1 is able to ping this pod and is able to access service via serviceip, but if the pod is created on node2, just node2 is able to ping this pod and access it via serviceip, node1 can not ping or access it via podip/serviceip

I can not find out the reason

1. I use nc tring to connect 8472 from node1 => node2, and from node2 => node1, both ok
2. when node1 can not access pod on node2, arp -a in node1 can find mac of flannel on node2
3. it seems that flannel on node2 is useless

so, what's the problem may be, thanks

**Comment by LinEricYang** [comment]
I ran into the similar issue on vagrant environment, only can ping pod on the same node. The root cause is flannel daemon use the first network interface by default, unfortunately the first one in vagrant one is NAT which is not connect with other nodes. So Using "--iface=" in flannel daemon to specifying correct interface works for me.

**Comment by erictune** [comment]
Please post to stack overflow for support questions
