### ISSUE TITLE
More detailed plan for TPR migration

### ISSUE THREAD

**Issue by deads2k** [kubernetes/kubernetes#45728]
https://github.com/kubernetes/community/blob/master/contributors/design-proposals/thirdpartyresources.md#migration-from-existing-tpr sketches out how migration could be done, but the devil is in the details.  We need to try the migration using the CRUD available now, actually see the pieces work, and see if we can think of improvements or ways to make it easier.

@enisoc is taking the lead on this effort, but if other community members have bandwidth to help, this is a good spot to raise your hand.

@adohe @philips @erictune @nikhita @sdminonne had all expressed interest
@kubernetes/sig-api-machinery-misc 

xref: https://github.com/kubernetes/features/issues/95

**Comment by enisoc** [comment]
I started brainstorming various ways to do migration.

My concerns with the [manual flow](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/thirdpartyresources.md#migration-from-existing-tpr) are:
* Is there a way to revoke edit writes that works on all clusters? RBAC is optional, right?
* Orphaning is risky in general. You might have a Pod that will get adopted by someone else once you orphan it.
  * If you don't orphan, GC may delete your dependents. That means an application that relies on TPR will have to be torn down in order to migrate safely.
* Because of such risks, TPR publishers (e.g. CoreOS publishing etcd Operator which uses TPR) cannot safely automate the migration, which means every end-user has to perform manual steps to migrate.

Even if we don't provide seamless migration out-of-the-box, I think we should ensure there exists a viable mechanism by which a sufficiently interested party could execute seamless migration. However, I can't see a way to do this from outside the apiserver because migrating without downtime (tearing down the application) and without orphaning (to avoid having dependents stolen) requires that the existing TPR data be visible at all times (to prevent GC of dependents).

Where I'm going with all this is I think it's actually easier to build in a semi-automatic migration in apiextensions-server, than it would be to document all the pitfalls of migrating externally.

By semi-automatic, I mean a flow like:
* Upgrading to 1.7 doesn't touch any existing TPR data.
* TPR publisher (e.g. etcd Operator) releases new version that uses CRD.
* Upon upgrade of Operator, it creates a CRD with an optional field `MigrateFromTPR: tpr-name`.
* The migration happens on the server side (writing directly to CRD storage to bypass the problem of overlapping REST endpoints) and the TPR gets deleted.

@deads2k I think I could make this work. Would you be opposed to such an approach on principle, or do you see a reason it couldn't work?

**Comment by smarterclayton** [comment]
Won't work with multiple masters.  So at minimum you have to lock all
API servers to transfer over, and maybe even manage a transactional
lock on the read path.

**Comment by liggitt** [comment]
> requires that the existing TPR data be visible at all times (to prevent GC of dependents)

fyi, GC doesn't currently work with TPR data

**Comment by deads2k** [comment]
> Upon upgrade of Operator, it creates a CRD with an optional field MigrateFromTPR: tpr-name.

I'm opposed to muddying a new API (CRD).  However, if you were to implement the link in the TPR resource, I'm not philosophically opposed.



> @deads2k I think I could make this work. Would you be opposed to such an approach on principle, or do you see a reason it couldn't work?

I think it can work.  It's not a straight storage copy since the TPR implementation has some wrappers around its storage and you're not guaranteed that the contained data is valid, but the data could be moved internally.  Such code should live outside of the CRD implementation.

Given that GC on TPRs doesn't currently do anything, is breaking already broken links really that bad?

**Comment by enisoc** [comment]
@smarterclayton You're right that it may not be feasible to do this safely with multiple masters - at least not with an implementation that's simple enough to get into 1.7. I'm not sure if you meant this should be a blocker, but I think automation that works only for some use cases is better than making everyone do it manually, in the absence of other proposals for automation.

@liggitt Is the GC still going to ignore TPR in 1.7+? If so, I can rethink some of this and we may have additional options.

@deads2k That's a good point about keeping the new API clean. I'll do some more brainstorming today with that goal in mind.

**Comment by enisoc** [comment]
@deads2k If it's possible to let TPR take precedence over CRD in the case of REST path overlap, then it may enable an approach like the following:

1. Upgrading to 1.7 doesn't touch any existing TPR data.
1. TPR author writes a corresponding CRD.
1. End-user (or Operator on their behalf) passes the TPR name and CRD to a generic tool, which will:
   1. Set the TPR read-only.
   1. Temporarily rename the CRD's `Spec.Names.Plural` to something unique so it is not shadowed, and create the CRD.
   1. Read from the TPR and write to the CRD.
   1. Rename the CRD resource to match the TPR. The CRD will be shadowed (API calls will still flow to the TPR).
   1. Delete the TPR. API calls flow to the CRD.

Requirements:
1. A way to set a TPR read-only.
1. TPR should take precedence over CRD.
1. It must be possible to rename the resource of an active CRD with CR data.

Note that if the above requirements are met in 1.7, then the generic tool could be implemented out-of-tree and separated from the Kubernetes release cycle.

**Comment by deads2k** [comment]
> Temporarily rename the CRD's Spec.Names.Plural to something unique so it is not shadowed, and create the CRD.

This bit isn't possible.  Particular resource instance names in kubernetes are pinned and the plural name matches the CRD object name to ensure that the REST handler registration can never collide.



> If it's possible to let TPR take precedence over CRD in the case of REST path overlap, then it may enable an approach like the following:

I'll find a way to make this happen for you.  I want the migration to be as smooth as reasonably possible without forcing unfortunate compromises in the design or implementation of CRD.  I'll work on patches today and tomorrow for the handling chain and the finalization controller.


> Read from the TPR and write to the CRD.

I'm ok with TPR code living in k8s.io/kubernetes depending on code from k8s.io/kube-apiextensions-server since it layers reasonably cleanly and will be easy to delete in 1.8 or 1.9.  Running in process would give you the option of direct to storage or access via REST using the internal server handling chain.  It means we have to meet dcut, but pieces are place now.



> A way to set a TPR read-only.

I think all your proposed scenarios require this. Can you chase it up?  I'll dedicate review time to it.  If you need congruent functionality in CRD, it'll be easy to do, but I don't know how to do it in TPR.

**Comment by enisoc** [comment]
Ok if renaming isn't possible, we can move migration back into kube-apiserver and go direct to storage or passthrough down the chain as you mentioned.

We could also keep CRD before TPR in the chain if CRD knows how to passthrough to TPR when it knows a given CRD is still migrating, but that comes back to muddying the new API. I don't know how involved it will be to swap the precedence but that's a trade-off that's available.

I'll start digging into the details of how the TPR->CRD passthrough could be done in code, as well as the TPR read-only mode.

**Comment by deads2k** [comment]
@enisoc I'm approving this.  I think a guide and an announcement on kubernetes dev are requirements before closure.

**Comment by enisoc** [comment]
Migration guide was [announced](https://groups.google.com/d/msg/kubernetes-dev/R749_-L_ssc/p-3tyl6mAQAJ).
