### ISSUE TITLE
Internal LoadBalancers should be supported by a field

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#45762]
AWS has supported internal ELBs for a long time with an annotation, I just saw support for the comparable feature on Azure (https://github.com/kubernetes/kubernetes/pull/45473), and GCE apparently has a comparable feature: https://cloud.google.com/compute/docs/load-balancing/internal/

We should probably create a field in the Service definition, seeing as this is widely supported, and deprecate (but retain the functionality of) the annotation.

cc @kubernetes/sig-network-feature-requests

**Comment by caseydavenport** [comment]
IIUC, internal LBs are meant for load balancing across instances (Nodes), rather than being aware of and load balancing to _Pods_, and Pod->Pod load-balancing is already provided through kube-proxy + ClusterIP Services.

@justinsb could you describe a bit more why a user of Kubernetes would want to use an internal cloud-provided load balancer?

**Comment by thockin** [comment]
I'm wary of making things API features without broad support, but this
might be OK.  I'm not keen on how this whole resource has evolved, partly
because expressing this is not at all clean.

@nicksardo for GCE ILB

Casey - the "internal" here means "inside my network" as opposed to inside
my cluster.  For example, in GCP, exposing a kube service to other GCE
VMs.  It is still node-based as before, but the net behavior is correct.

**Comment by smarterclayton** [comment]
I'd be cautious about adding more things to Service, especially as other
groups are gearing up to build policy objects around service.  Could we
safely model options for internal load balancing as a separate resource
object without having potential conflicts?

The ingress extensions discussion is extremely relevant here re: support.

**Comment by justinsb** [comment]
My thought process is:

1. All the clouds should use the same annotation
2. We're not using annotations any more, we're using fields

And I agree @thockin it seems that we don't want to add fields for features that e.g. only AWS has.  The challenge is that AWS therefore creates an annotation, and then Azure & GCE create their own annotations.  That is just pointlessly annoying for users, and not good for k8s strategically.  Not sure how to solve that.

**Comment by thockin** [comment]
The intent was always that various clouds could do their own thing, and
if/when a preponderance of platforms supported a feature, we would
centralize it.

The problem is that Service has grown unwieldly.  It's not that we don't
have other loadBalancer and externalTraffic fields - we do.  They are just
awful and getting worse.  I will have more time to think of this next
week...
