### ISSUE TITLE
/healthz of the apiserver should return ok first when ready to serve requests

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubernetes#45786]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

BUG REPORT

**Kubernetes version** (use `kubectl version`):

v1.6.3 (and HEAD I think)

**What happened**:

The apiserver returns `ok` on `/healthz` before it's ready to serve requests correctly.

Example of the race condition when doing self-hosting with kubeadm:
```
[self-hosted] Found 1 self-hosted-kube-apiserver pods
[self-hosted] Pod self-hosted-kube-apiserver-2d146 status: Pending
[self-hosted] Found 1 self-hosted-kube-apiserver pods
[self-hosted] Pod self-hosted-kube-apiserver-2d146 status: Running
[apiclient] All control plane components are healthy after 4.550770 seconds
[self-hosted] self-hosted kube-apiserver ready after 13.904822 seconds
failed to create self-hosted "kube-scheduler" deployment [deployments.extensions "self-hosted-kube-scheduler" is forbidden: not yet ready to handle request]
```

**What you expected to happen**:

The api server should actually be ready when `/healthz` is `ok`

**How to reproduce it** (as minimally and precisely as possible):

* Install kubeadm v1.6.3
* Create this config file:
   ```yaml
   kind: MasterConfiguration
   apiVersion: kubeadm.k8s.io/v1alpha1
   selfHosted: true
   ```
* Run kubeadm: `kubeadm init --config kubeadm.yaml`

cc @kubernetes/sig-cluster-lifecycle-misc 

Is this a sig-apimachinery bug? @kubernetes/sig-api-machinery-bugs

**Comment by lavalamp** [comment]
Thoughts:

* /healthz is liveness - i.e., kubelet please don't kill this process. You're looking for a "ready" concept. We don't have that for apiserver but probably need it. (alternatively, if we co-opt /healthz to be readiness, then we need a liveness endpoint.)
* You need retry logic in your app anyway-- /healthz doesn't give you a lock, the server could go unhealthy after you check it
* also in a multi-master set up, your second request could go to a different apiserver than the first one did.

Additionally, we think the specific message came from an admission control plugin. Since these are dynamic (alpha right now) there's not a good way to tell if they are all ready.
