### ISSUE TITLE
kubelet unit test flake

### ISSUE THREAD

**Issue by shashidharatd** [kubernetes/kubernetes#45803]
here is one such instance where kubelet unit tests are failing
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/45798/pull-kubernetes-unit/30523/

**Comment by wongma7** [comment]
This can happen if an earlier test, e.g. one of the reconciler tests, called fakevolumeplugin.Setup, which creates a pod fake volume plugin directory. This directory can then gets mistakenly detected and "reconstructed" in later tests that actually Run the volume manager, like this TestListVolumesForPods one. As part of the volume manager's reconstruction process, each directory's plugin's ConstructVolumeSpec is called. The fake plugin returns a nil spec which leads to a nil pointer exception.

I guess it's flaky because the reconstruction/syncStates only happens after 3 minutes, so it will only happen on test runs that take too long.

**Comment by ntfrnzn** [comment]
I just ran into this and went digging to find the cause (unfortunately I did that _before_ looking for/finding this issue)

The plugin does this https://github.com/kubernetes/kubernetes/blob/d86bf8a0b8546dae8705c33cbc0c4df43608e0d8/pkg/volume/testing/testing.go#L305 
which seems really unfortunate to me.  It's a violation of expectations to return (nil, nil) and so the tests fail later. I don't know what the consequences of changing it to 
```
   return nil, fmt.Errorf("FakeVolumePlugin.ConstructVolumeSpec isn't implemented")
```
would be, but the results would be _a lot_ easier to interpret
