### ISSUE TITLE
Federation: Handling deviations from k8s service registry

### ISSUE THREAD

**Issue by shashidharatd** [kubernetes/kubernetes#45812]
This issue is to continue the discussion in #45798, The fix in the PR is temporary and would be reverted as soon as the permanent solution is arrived at.

We want to implement the defaulting `ExternalTrafficPolicy` logic for Service in registry, (for both create and update). We at federation are currently not using the same set of Rest functions for Service. This was agreeable as some of the logic implemented in k8s registry for Service(cluster-ip allocator, NodePort allocator,  NodePort vallidity check) may not be applicable for federated services. Now going forward federation registry also should have some logic implemented which is similar to k8s registry.

@nikhiljindal, request to provide some inputs on this about the right approach.

cc @kubernetes/sig-federation-bugs, @MrHohn @madhusudancs

**Comment by liggitt** [comment]
isn't this just one instance of the type of issues a version skewed federation server will encounter? it seems like the answer is to make federation deal with objects more generically, not replicate cluster logic into federation registries

**Comment by nikhiljindal** [comment]
We discussed this in sig meeting in the morning. 
Yes, this is similar to the version skew problem, but is not exactly that since in this case the problem even exists in same version of federation and kubernetes.

@madhusudancs @MrHohn and I discussed this more just now.

@MrHohn will send a PR to move the defaulting logic to defaults.go (which is the right place to put that code). That way federation will also get the same code.
We should also update our service registry code to reuse the same code as kubernetes to prevent such mismatches.

**Comment by quinton-hoole** [comment]
@nikhiljindal @shashidharatd Can this be closed now that the above two PR's have merged?

**Comment by nikhiljindal** [comment]
We still need to fix the following:

> We should also update our service registry code to reuse the same code as kubernetes to prevent such mismatches.

**Comment by irfanurrehman** [comment]
This issue was labelled only for sig/multicluster and is thus moved over to kubernetes/federation#138.
If this does not seem to be right, please reopen this and notify us @kubernetes/sig-multicluster-misc.
/close
