### ISSUE TITLE
Separate predicate and priority metrics in scheduler

### ISSUE THREAD

**Issue by ravisantoshgudimetla** [kubernetes/kubernetes#45972]
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
FEATURE REQUEST

As of now in metrics.go https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/scheduler/metrics/metrics.go, we have 3 metrics, for end2endLatency, algorithmLatency and BindingLatency. 

The problem with algorithmLatency is 
- it is a combination of predicate and priority latencies. 

So breaking down this metric into predicate and priority latencies would be really helpful for performance analysis. For example, as part of the analysis after these metrics were added, we were able to find latencies when we have taints & tolerations alone. In fact, ability to drill down on every predicate and priority would be ideal but want to know other's opinions on this.

**Comment by gmarek** [comment]
+1 please send a PR.

**Comment by jayunit100** [comment]
We also have some demonstrations of how this helps with things like highlighting taint and toleration performance and so on.  We should update readme info on how to use these along side the scheduler perf stuff as we've done internally .

**Comment by wojtek-t** [comment]
You need to be careful about what latency means if we are computing multiple different predicates in parallel (if we decide to split it by predicate).

Splitting predicate vs priority is definitely a good idea.

**Comment by jayunit100** [comment]
Please label this as part of our 1.7 scheduling forensics milestone .

**Comment by jayunit100** [comment]
Let's remove the idea of latency entirely, it is confusing - this is just an attempt at measuring predicate and priority timescales, and there is no response latency that we care about in those small (20ms) timescales , (with the exception of maybe the latency of an etcd hit that might happen in a client if the cache is missing information I guess)

**Comment by gmarek** [comment]
Not really - there were cases of predicates which computation could take over a second.

**Comment by jayunit100** [comment]
Yes, and even longer on large clusters with things light affinity....

However here  I'm just disputing use of the term latency since latency is usually used to refer to the time between the end of a request and the beggining of a response.  

What we endeavor to do here is really measure round trip execution time, for predicates, in isolation. 

If we want to measure some kind of latency then I believe we would need to define some notion of a request/response, which has diminished  value outside of something like RPC.

If we truly were measuring latency, then we might thus look at the time between writing a new unscheduled pod to the system, and the time it takes to start running the scheduler or something.

**Comment by gmarek** [comment]
OK, IIUC you object usage of the word 'latency', right? We use it in this context for quite some time, and as I agree that it doesn't fit formal definition, there's no point in changing it now, as it would confuse people even more.

**Comment by jayunit100** [comment]
yeah, i really think they should all be refactored to not be named as such, that is my broader point . but if we want to keep those metrics id suggest we at least update the definition in the `help` fields to clarify that latency is defined WRT `fit` rather then to a RPC.
