### ISSUE TITLE
kube-proxy is not preserving iptables counters

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#46172]
I swear we have logic to preserve counters, but I can see that it is not working.

Probably something easy, could use a good test.  May be great for a newcomer.

@kubernetes/sig-network-bugs

**Comment by thockin** [comment]
I can't seem to make it work at all.

New chains are always [0:0] and restore is resetting chains it ought not.  Observe:

```
$ iptables-save -c > 1

$ echo -e "*nat\n:TEST - [1:2]\nCOMMIT\n" | iptables-restore -c -n

$ iptables-save -c > 2

$ diff 1 2
3c3
< :PREROUTING ACCEPT [18:1128]
---
> :PREROUTING ACCEPT [0:0]
5,6c5,6
< :OUTPUT ACCEPT [92:6010]
< :POSTROUTING ACCEPT [7:420]
---
> :OUTPUT ACCEPT [0:0]
> :POSTROUTING ACCEPT [0:0]
32a33
> :TEST - [0:0]

$ iptables --version
iptables v1.4.14
```

Secondly, from logs, it does not look like we are properly extracting old counter values, anyway.

**Comment by qiujian16** [comment]
@thockin I would like to take a look at it if no one is working on this.

**Comment by thockin** [comment]
Please!  If you can find out why iptables-restore is not saving counters,
I'd love to know.

**Comment by qiujian16** [comment]
Check the details of iptables...It seems that user defined chain does not have a counter, so setting counter to a user defined chain does not work at all. Add a user defined chain always refresh counter of all built-in chain, but I still need to find the reason.

I think we should preserve the counter of each rule rather than each chain, but currently we do not add counters for each rule when iptables-restore. @thockin is there performance penalty to preserve counter per rule?

**Comment by thockin** [comment]
I have no idea - please find out and tell me! :)

**Comment by PengTaoWW** [comment]
@thockin 
8.4. iptables-restore
The iptables-restore command is used to restore the iptables rule-set that was saved with the iptables-save command. It takes all the input from standard input and can't load from files as of writing this, unfortunately. This is the command syntax for iptables-restore:

iptables-restore [-c] [-n]

The -c argument restores the byte and packet counters and must be used if you want to restore counters that were previously saved with iptables-save. This argument may also be written in its long form --counters.

The -n argument tells iptables-restore to not overwrite the previously written rules in the table, or tables, that it is writing to. The default behavior of iptables-restore is to flush and destroy all previously inserted rules. The short -n argument may also be replaced with the longer format --noflush.

look like iptables-save will restore counters , but  iptables-restore not

**Comment by waynr** [comment]
I currently have very little understanding of the issue here, but according to this serverfault post, there seems to be a bug in Linux related to what y'all are describing:
https://serverfault.com/questions/606043/iptables-counters-restore-when-using-quotas-not-working-as-expected

I've got an RC build of linux 4.15 checked out on my computer and it doesn't look like a whole lot has changed. In fact, the first few commits displayed by `git log net/netfilter/xt_quota.c` from the root of the Linux repository shows:

```
commit ec23189049651b16dc2ffab35a4371dc1f491aca
Author: Willem de Bruijn <willemb@google.com>
Date:   Mon Jan 2 17:19:46 2017 -0500

    xtables: extend matches and targets with .usersize

    In matches and targets that define a kernel-only tail to their
    xt_match and xt_target data structs, add a field .usersize that
    specifies up to where data is to be shared with userspace.

    Performed a search for comment "Used internally by the kernel" to find
    relevant matches and targets. Manually inspected the structs to derive
    a valid offsetof.

    Signed-off-by: Willem de Bruijn <willemb@google.com>
    Signed-off-by: Pablo Neira Ayuso <pablo@netfilter.org>

commit 3a9a231d977222eea36eae091df2c358e03ac839
Author: Paul Gortmaker <paul.gortmaker@windriver.com>
Date:   Fri May 27 09:12:25 2011 -0400

    net: Fix files explicitly needing to include module.h

    With calls to modular infrastructure, these files really
    needs the full module.h header.  Call it out so some of the
    cleanups of implicit and unrequired includes elsewhere can be
    cleaned up.

    Signed-off-by: Paul Gortmaker <paul.gortmaker@windriver.com>

commit 49daf6a22622d4e1619aeaad5f9f0472bf89daff
Author: Changli Gao <xiaosuo@gmail.com>
Date:   Fri Jul 23 14:07:47 2010 +0200

    xt_quota: report initial quota value instead of current value to userspace

    We should copy the initial value to userspace for iptables-save and
    to allow removal of specific quota rules.

    Signed-off-by: Changli Gao <xiaosuo@gmail.com>
    Signed-off-by: Patrick McHardy <kaber@trash.net>
```
Just to confirm that very little has changed since that serverfault post.

Again, my understanding of the issue here is very limited so I apologize if this is a red herring. I may have some time off in the next few weeks that I could put toward investigating this issue in more depth. I'll comment back here when I know if I am able to commit.

**Comment by nikhita** [comment]
/remove-lifecycle rotten

rotten and help-wanted labels don't go hand in hand :)
