### ISSUE TITLE
kubectl create service should accept --selector

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#46191]
It should be possible to pass a selector to create services of type != ExternalName.  The default selector isn't very useful.

**Comment by shiywang** [comment]
will take a look

**Comment by xiangpengzhao** [comment]
I guess Clayton was saying `kubectl create service`.

**Comment by suyogbarve** [comment]
@shiywang are you fine if I take this up, I am half way with my solution for this.

**Comment by shiywang** [comment]
@suyogbarve go ahead, I will help to review : )

**Comment by suyogbarve** [comment]
@smarterclayton : since api.Service only support map[string]string or equality based labels (something=otherthing), new selector for "kubectl create svc " will be different from what we have present on parent command 

Selector already present only for parent command -->
-l, --selector='': Selector (label query) to filter on, supports '=', '==', and '!='.

Proposed Selector for "kubectl create svc" --->
-l, --selector='': Selector to filter on, supports '=' 

Or am I missing something?

@shiywang thanks for helping

**Comment by suyogbarve** [comment]
@smarterclayton @shiywang PR #46546

**Comment by fabiand** [comment]
/remove-lifecycle rotten

The use-case iss till very limited, as neither the selector nor namespace can be configured.

**Comment by fabiand** [comment]
Side note, yes `-l` is present but does not work:

```
kubectl create -l bar=bar service nodeport my-ns2 --tcp=5678:8080 --dry-run -o yaml 
Error: unknown shorthand flag: 'l' in -l
…
```

**Comment by enriquecatala** [comment]
Please <mark>reopen this issue</mark>. This is an example of what do i need to do to create a selector to a service created with the kubectl create command. This makes no sense for me :(

kubectl create service clusterip clusterip-nginx \
                                  --namespace=modulo3 \
                                  --tcp=8080:80 \
                                  --dry-run=client \
                                  -o yaml \
 | kubectl set selector "tier=backend" --local -f - \
                                               -o yaml

**Comment by kentwongg** [comment]
I'm surprised after all these years this still was never implemented. I am going through a Kubernetes learning course and this seems like an oversight.
