### ISSUE TITLE
Some kubemark tests are failing to start the kubemark cluster

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#46195]
Some example runs:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-kubemark-5-gce/12417
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-kubemark-5-gce/12417

**Comment by wojtek-t** [comment]
@kubernetes/sig-scalability-bugs

**Comment by wojtek-t** [comment]
@gmarek

**Comment by shyamjvs** [comment]
Seems like we are facing the same problem as we saw in kubemark-100 (issue https://github.com/kubernetes/kubernetes/issues/46109) of not having kubemark-master logs in case of startup failure.
We need to fix it asap to know the reason for these failures.

**Comment by shyamjvs** [comment]
The issues we originally saw are potentially outdated now. But I've studied the last few flakes and there are 3 kinds of them:
- listNodes after up'ing e2e cluster fails : solved this by checking api reachability (with retries) before doing that [e.g runs 16865, 16860, 16848, 16839, ..]. Ref kubernetes/test-infra#3616
- failing while checking AllNodesReady as AfterSuite : solved by not letting the condition fail on failing api call [e.g runs 16896]
- gcloud side issues in creating VM, SSH'ing etc (this just happens) [e.g runs 16840, ..]

**Comment by shyamjvs** [comment]
Ok.. So after those fixes, the only flakes we're seeing currently (e.g runs [17326](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-kubemark-5-gce/17326), [17313](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-kubemark-5-gce/17313), [17285](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-kubemark-5-gce/17285), [17263](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-kubemark-5-gce/17263), ...) is due to:

`error during ./cluster/kubectl.sh version --match-server-version=false: exit status 1`

This should be fixed by adding retrying to the corresponding command in kubetest. I'll send out a PR for it.
