### ISSUE TITLE
how to stop a running kube-proxy? or start one against a port other than 8001?

### ISSUE THREAD

**Issue by bfznj** [kubernetes/kubernetes#46232]
Hello, I'm a newbie to kubernetes, still learning through minikube.

While going through the tutorials, at the spot where I run "kubectl proxy" to start a proxy. I got the response "proxy.go:137] listen tcp 127.0.0.1:8001: bind: address already in use". 

Apparently, in an earlier exercise of sort, I already ran the same command. How can I stop the existing process listening to that port? I tried to "kill -9" the process, but it starts right away.

since the command "kubectl proxy" contains no port as parameter, how to configure it to use a different port?

thanks much,

**Comment by apelisse** [comment]
Please re-post your question to [stackoverflow]
(http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support
are posted so that we can improve our efficiency in responding to your requests,
and to make it easier for you to find answers to frequently asked questions and
how to address common use cases.

We regularly see messages posted in multiple forums, with the full response
thread only in one place or, worse, spread across multiple forums. Also, the
large volume of support issues on github is making it difficult for us to use
issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to
ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to
similar questions, and also familiarize yourself with:

  * [user guide](http://kubernetes.io/docs/user-guide/)
  * [troubleshooting guide](http://kubernetes.io/docs/admin/cluster-troubleshooting/)

Again, thanks for using Kubernetes.

The Kubernetes Team

**Comment by tomwparsons** [comment]
How did you solve this? as it's not in the trouble shooting docs

Thanks

**Comment by apelisse** [comment]
> I tried to "kill -9" the process, but it starts right away.

I'm not sure what you mean by that.

Anyway, I can see by running `kubectl help proxy` that there is a `-p, --port` option to change the port. But you should really be able to kill the existing process anyway ...

PS: I'm using kubectl 1.8.7.

**Comment by tomwparsons** [comment]
It's how to stop kubectl proxy, as running kubectly proxy gives:
`F0315 16:04:34.149372   39941 proxy.go:153] listen tcp 127.0.0.1:8001: bind: address already in use
`
Killing that process doesn't help as it immediately restarts. We're using 1.9.4

**Comment by apelisse** [comment]
> Killing that process doesn't help as it immediately restarts

which process? Did you try `killall kubectl`?

**Comment by mayuchau** [comment]
> > Killing that process doesn't help as it immediately restarts
> 
> which process? Did you try `killall kubectl`?

Worked for me

**Comment by camilamacedo86** [comment]
solution: 

1. Get the process:

```shell
$ ps aux | grep kubectl
camilamacedo      1549   0.0  0.1  5053188  25152 s000  T     3:47pm   0:02.31 kubectl proxy
camilamacedo      4020   0.0  0.0  4287536    884 s000  S+    4:45pm   0:00.01 grep kubectl
```

2. kill the process:
```shell
$ kill -9 1549
[1]   Killed: 9               kubectl proxy
```

3. now it will work

```shell
$ kubectl proxy
Starting to serve on 127.0.0.1:8001
```

**Comment by endlesslight0** [comment]
@camilamacedo86 better use `kill -15 pid`

**Comment by sk-sharique** [comment]
1. Get the list of running jobs.
```
$ jobs
[1]+  Running           kubectl proxy &
```
2. Select the job that you want to stop using fg <process_id>. fg brings the job with the <process_id> into the foreground, resuming it if it was suspended.
```
$ fg 1
kubectl proxy
```
3. Press Ctrl + C to end this process.
