### ISSUE TITLE
Need an API call for "teardown all external resources"

### ISSUE THREAD

**Issue by zmerlynn** [kubernetes/kubernetes#4630]
See #4627 / #4530: These are both the wrong approach, as also noted in https://github.com/GoogleCloudPlatform/kubernetes/issues/4411#issuecomment-74209939. We need to delete these things on the master, prior to deleting the VM itself. For system add-ons, this is basically the API hook necessary for #3579 cleanup, but it's also required for any user services that were created as well.

**Comment by zmerlynn** [comment]
cc @roberthbailey @jlowdermilk

**Comment by fgrzadkowski** [comment]
cc @jszczepkowski 

Can you please explain what this API would look like? I'm not sure that widening API for a central component is the right approach.
If external resource is tightly related to a resource (e.g. service) it'd be strange to have a separate API call just to remove it's external parts (e.g. load balancer). Also it may leave a resource (service) in an inconsistent state.
Additionally you will still need something like kube-down.sh to clear other things (e.g. remove machines etc.) so what's the benefit?

**Comment by fgrzadkowski** [comment]
Just to be clear - I think that removing of internal services should be handled by master itself, but I see no reason why we need an API call to delete external resources for user defined services.

**Comment by zmerlynn** [comment]
First, the meta-point: kube-down.sh isn't the only setup and teardown
"client". (GKE is, others might come along.) That was the meta-point for
#3579 as well. To the extent that we can push this logic onto the server,
we should.

The second meta-point: today ELBs are the biggest issue. There are
discussions around, say, firewall rules - those would also need teardown.
Or xyz cloud provider network widget. The point is, that shell script is
going to keep creeping.

As far as what the API looks like, we were envisioning something like:
"kubectl clusterteardown", that made one API call to the master (call it
teardown, or destroy, or destroyExternalResources or whatever) that could
even just have a loop on Go very similar to rejected PR #4530. (And yes,
we'd make one addition to kube-down.sh, right before the VM itself was
annihilated.)

The API should probably be best-effort semantics, since it's going down
anyways.

**Comment by zmerlynn** [comment]
I just saw your next comment. Why a distinction between user services and
add-ons here? They both represent external resources owned by cluster
services. Some might be owned by the user, so you could argue that we need
policy bits like "don't delete on teardown", but that doesn't mean the
client should delete them.

**Comment by zmerlynn** [comment]
Also, to be clear, the API can just outright delete the services, too. I don't see a reason it has to delete the underlying resources versus the services themselves, since it's running in the shutdown path. If we really want to be delicate, we can terminate all objects (#1535) first.

**Comment by jszczepkowski** [comment]
I'll be happy working on this. I hope no one is working on it now.

**Comment by alex-mohr** [comment]
We need to support deletion of clusters, both for GKE and for e.g. e2e tests.  The master will create and delete various CloudProvider objects, so it should own those objects.  We need a way to (a) crease accepting new objects, (b) change desired state for existing objects to does-not-exist, (c) block until the CloudProvider reconciler (or equivalent) finishes actually deleting all of those, then (d) the master can be deleted.

Given the master knows what it created and has code to delete such things (for whatever version of k8s it's running), we should use the master itself to clean up a cluster that needs to be deleted, not require some out-of-band tool to do so.

**Comment by bgrant0607** [comment]
Discussion is occurring in #5025.

**Comment by brendandburns** [comment]
I don't think that this makes the 1.0 cut.

**Comment by alex-mohr** [comment]
> I don't think that this makes the 1.0 cut.

@brendandburns Without this, we orphan resources in GCE on cluster delete.  And if e.g. user spins up a new cluster with the same name, there will be all sorts of fun from dangling rules.  I think this falls under operational reliability.

**Comment by amygdala** [comment]
Just a vote that this seems fairly important -- e.g. since kube-down.sh doesn't clean up the external load balancer forwarding rules, it's easy to accumulate a whole slew of them.  I know enough to go in and clean them up by hand every once in a while, but we shouldn't expect our users to know to do that.

**Comment by bgrant0607** [comment]
Does deleting the services cause the forwarding rules to be deleted? If not, then that's the first thing we should fix. If so, then we could start by just deleting all services, from all namespaces.

**Comment by a-robinson** [comment]
Yes, deleting the services causes the forwarding rules to be deleted.

**Comment by bgrant0607** [comment]
cc people  who commented on #5025: @smarterclayton @derekwaynecarr @erictune @thockin 

I proposed an alternative in #10179 -- a `protected` field, which could be unset prior to shutdown, allowing recursive deletion of namespaces to clean up everything. I agree that we shouldn't require external/centralized knowledge of which Kubernetes resources provision which external resources in the long run. (In fact, the implementation in #5025 violated that principle, by hardcoding that knowledge in the `teardown()`.)

Summarizing concerns about the proposed /teardown call:
1. It's something that should O(NEVER) happen in long-lived clusters, as @thockin implied in https://github.com/GoogleCloudPlatform/kubernetes/pull/5025#issuecomment-77415890. We don't have a such a call in Borg. In fact, we have measures to ensure that, once created, a cluster's state is protected under all circumstances, even when the persistent state appears to be lost -- the master freezes all changes until the state is manually recovered or the configuration of the master is changed to allow a fresh start.
2. It doesn't handle the case of externally managed resources mentioned in https://github.com/GoogleCloudPlatform/kubernetes/pull/5025#issuecomment-77417618 and https://github.com/GoogleCloudPlatform/kubernetes/pull/5025#issuecomment-77448018. That's what the finalizers on Namespace address.
3. It doesn't fit the API's REST model. 

I could imagine that we'd want a way to block creation of new namespaces and of new resources in namespaces that are being deleted. Since the cleanup process may be long and at least some (eventually all) control-plane components will be self-hosted, it would need to be possible to allow creation of new pods in some namespaces (e.g., Kubernetes and Openshift infrastructure namespaces) while others are being deleted to ensure that the process can complete successfully in the presence of infrastructure failures. 

With the `protected` field proposed in #10179, we could try to delete all namespaces, and then go back and delete protected namespaces that weren't deleted in the first round.

**Comment by lavalamp** [comment]
I don't think a 'protected' field is necessary for this. Today we have RBAC, finalizers, and GC. I think a client w/ super admin powers could delete all namespaces and then wait for the namespace count to go to 0. (There's probably a corner case or two around the default and kube-system namespaces that this would turn up.)

**Comment by zmerlynn** [comment]
I might be missing it, but I haven't found a way to delete `default` and `kube-system`. If you come up with one, I'll close the bug. :)

**Comment by roberthbailey** [comment]
It still isn't possible to delete the following namespaces: `kube-system`, `kube-public`, `default`. So we can't rely on finalizers / GC for resources in those namespaces. 

We also don't have a way to put the apiserver into a lame duck mode to prevent new namespaces from being created during cluster teardown.

**Comment by neolit123** [comment]
seems like a FR for api-machinery, that can eventually land in kubectl (sig-cli).
sig-cluster-lifecycle tools can adapt it via client-go if they need to.

/sig cli api-machinery
