### ISSUE TITLE
ip-masq-agent needs docs

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#46475]
We need a "how to set up IP masquerade" doc or similar for ip-masq-agent.

@dnardo @mtaufen

**Comment by dnardo** [comment]
@thockin 

What is the scope of the doc we are looking to add.
We have the readme here which describes the agent and how to apply the daemon set;
https://github.com/kubernetes-incubator/ip-masq-agent

Is the goal to explain masquerading in general and why the agent is necessary in k8s?

**Comment by thockin** [comment]
I would look at a GKE doc on the configmap and maybe a Kubernetes doc (
https://github.com/kubernetes/kubernetes.github.io/tree/master/docs/tasks)
or blog post?

**Comment by prateekgogia** [comment]
@thockin, I am creating the documentation for ip-masq-agent, while trying out the agent I deployed it with flannel and calico network plugins. These both plugins add the masq rule for everything non local from the pod. Adding this agent with these plugins seems redundant, because the private ranges ignored by this agent, eventually get masquerade by rules added by the network plugins. 

I just wanted to double check with which network plugin or functionality, this agent is being intended to be used. I also tried using local-cluster-up.sh script to bring up one node cluster and tried with that, in this case it uses Docker subnet for pods and Docker iptables rules masq everything non-local.

**Comment by dnardo** [comment]
@prateekgogia 
I cannot speak to flannel, however, we had Calico remove this functionality which is handled in this pr: https://github.com/kubernetes/kubernetes/pull/47188/commits/8ef6b06d3982afda14de7335afa953e12ea8452d

The ip-masq agent was mainly added to decouple masquerading from the "kubenet" plugin which is the default for k8s.  Since we are trying to deprecate kubenet in favor of CNI we needed a way to decouple that behavior from kubenet.  I think the reason these plugins do this now is because kubenet was doing it before, and once you switch to "cni" as the network provider, you lose this functionality  and something needs to set these masq rules up so the plugin authors handled it themselves.  Since we now have ip-masq-agent these plugins do not have to handle their own masquerading setup.   That said, since the ip-masq-agent is optional, it doesn't require that someone install it, especially if the cni plugin they are using already has this functionality, but it would be nice for consistency if they did.

**Comment by bowei** [comment]
filed PR here https://github.com/kubernetes/kubernetes.github.io/pull/4064
