### ISSUE TITLE
Service Account entry in deployment backward compatible

### ISSUE THREAD

**Issue by kleuf** [kubernetes/kubernetes#46491]
Hi there

We have a test cluster on k8s 1.6.3 and i adjusted the ingress controller deamonset file to include the line "serviceAccountName: ingress" in it for 1.6.
Our DEV cluster is still on k8s 1.5, will i have to remove that line or can i leave it in, and simply make sure that that service account "ingress" exists on that cluster also?

Regards

**Comment by grodrigues3** [comment]
Please re-post your question to [stackoverflow]
(http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support
are posted so that we can improve our efficiency in responding to your requests,
and to make it easier for you to find answers to frequently asked questions and
how to address common use cases.

We regularly see messages posted in multiple forums, with the full response
thread only in one place or, worse, spread across multiple forums. Also, the
large volume of support issues on github is making it difficult for us to use
issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to
ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to
similar questions, and also familiarize yourself with:

  * [user documentation](http://kubernetes.io/docs/)
  * [troubleshooting guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/)

Again, thanks for using Kubernetes.

The Kubernetes Team
