### ISSUE TITLE
FUSE client support for K8s CephFS

### ISSUE THREAD

**Issue by viprat** [kubernetes/kubernetes#46636]
The goal of this issue is to design a CephFS driver using FUSE client for Kubernetes.</br>
Existing Ceph kernel client has the following drawbacks:</br>
•	Kernel client does not support client-enforced quotas.
•	Kernel CephFS doesn't support quota or capacity, capacity requested by PVC is not enforced or validated.
•	Kernel CephFS doesn't work with SELinux, setting SELinux label in Pod's security context will not work.

@kubernetes/sig-storage

**Comment by strigazi** [comment]
Just a detail. Since we will rely on ceph-fuse, we will need the ceph-fuse client to be available on all kubernetes nodes.

We can add a parameter to allow the use of the kernel client as well. I would say better make the fuse client opt-in and keep the kernel one as the  default option. The kernel client might support quotas in the future.

Thanks

**Comment by wjin** [comment]
We are also inclined to use fuse instead of kernel client ,any progress on this issue?

**Comment by zhangxiaoyu-zidif** [comment]
I like to continue this job and prepare to send a PR to make kubernetes support cephfs fuse mounting.

**Comment by zhangxiaoyu-zidif** [comment]
/assign @rootfs 
I think this task would be valuable. =)

**Comment by x1957** [comment]
@zhangxiaoyu-zidif waiting for the PR, do you have a plane to support s3 fuse https://github.com/s3fs-fuse/s3fs-fuse ?

**Comment by zhangxiaoyu-zidif** [comment]
@x1957
No, no plan for s3fs-fuse currently

**Comment by rootfs** [comment]
also see https://github.com/kubernetes/kubernetes/issues/44486 and http://tracker.ceph.com/issues/20851

cc @renhwztetecs

**Comment by renhwztetecs** [comment]
@rootfs
ceph-fuse support in the command to display the specified secret, it may take some time to support, because it involves LibFUSE(I will follow up this demand). On the other hand, ceph-fuse stability, quota function, expansion, upgrade and other advantages of the k8s community is anxious. Although ceph-fuse only supports the secret file way, but if it can be pushed to the k8s community, there is a very meaningful thing.

thank you!
