### ISSUE TITLE
Kubernetes Master node High Availability.

### ISSUE THREAD

**Issue by jobz** [kubernetes/kubernetes#46766]
We have a Kubernetes multi master  setup with 3 master nodes and 5 worker.
We have used HA Proxy for load balancing and high availability . But due to single point of failure on the side of HA Proxy we are trying for a new approach.

We tried the following methods:-
 1. Giving multiple ip address of al the API servers against the --master parameter in in kube-controller-manger, kube-scheduler,kubelet,kube-proxy. But it was not working since it not supported in Kubernetes.
2. Created temporary iptable rule in master and worker nodes to reach the api-servers via service IP.
    But there was a conflict between the temporary iptable rules and kube-proxy generated chains. So   kube-proxy was continuously flushing and adding iptable rules. 

Is there any other way to achieve high availability of masters ?

**Kubernetes version** : v1.6.3

**Environment**:
- **Cloud provider or hardware configuration**:
- **OS** : Ubuntu 16.04.2 LTS
- **Kernel** :4.4.0-62-generic

**Comment by xiangpengzhao** [comment]
sorry, didn't notice @yastij already labeled `kind/support` when I wrote comment:)

**Comment by castrojo** [comment]
Please re-post your question to [Stack Overflow](http://stackoverflow.com/questions/tagged/kubernetes).

Thanks for taking the time to report an issue to us. In the past this tracker has housed both bug reports and user support requests, we are now only using this tracker for software defects and feature tracking.   

We are trying to consolidate the channels to which questions for help/support
are posted so that we can improve our efficiency in responding to requests,
and to make it easier for you to find answers to frequently asked questions and
how to address common use cases.

The Kubernetes team scans Stack Overflow on a regular basis, and will try to
ensure your questions don't go unanswered.

If you're looking for more long-form discussion on best practices, we encourage you to check out the [Kubernetes user list](https://groups.google.com/forum/#!forum/kubernetes-users). 

You can also find more information here:

  * [User Documentation](http://kubernetes.io/docs/)
  * [Troubleshooting Guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/)

Again, thanks for using Kubernetes. If you feel this issue has been closed in error then please reopen it and we can have another look. 

The Kubernetes Team

**Comment by castrojo** [comment]
/close

Here's the link to sig-cluster ops if you want to follow up with them, thanks! https://github.com/kubernetes/community/tree/master/sig-cluster-ops
