### ISSUE TITLE
LocalStorageCapacityIsolationEviction tests are flaky

### ISSUE THREAD

**Issue by mindprince** [kubernetes/kubernetes#47128]
They are resulting in https://k8s-testgrid.appspot.com/sig-node#kubelet-serial-gce-e2e failing again and again.

https://storage.googleapis.com/k8s-gubernator/triage/index.html?test=LocalStorageCapacityIsolationEviction

Example of failures:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-serial/1472
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-serial/1477
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-serial/1480

**Comment by mindprince** [comment]
cc - @jingxu97

**Comment by jingxu97** [comment]
In this test, the expected behavior should be
1. Pod is created successfully and test waits it enters running state
2. Pod writes a large file to EmptyDir so it gets eviected
3. Check the pod status should be failed

 From the log, it seems like the pod is evicted right after it was created because of large file writing, the test failed with unexpected "pod run to competition error". Will change the command in pod to sleep a number of seconds before writing large files so that step 1 can pass.
