### ISSUE TITLE
Is the cluterIP support Ping command ?

### ISSUE THREAD

**Issue by yan234280533** [kubernetes/kubernetes#47156]
In k8s service, every service has an clusterIP. But in 1.4 version, can not "ping clusterIP", can it support in newest k8s ?

**Comment by xiangpengzhao** [comment]
/sig network
/kind support
/cc @smarterclayton 

AFAIK, k8s doesn't but openshift does.

**Comment by cmluciano** [comment]
@yan234280533 The cluster IPs do not support ICMP traffic and ping will not work.

**Comment by yan234280533** [comment]
@cmluciano Can it do an feature to support it ? For sometimes it an very important feature for user.

/sig network

**Comment by cmluciano** [comment]
Since the cluster IP is through iptables, I do not believe that this would be supported. 

cc @kubernetes/sig-network-misc

**Comment by danwinship** [comment]
The iptables proxier could make pings work, but it would be much more complicated for the userspace proxier. And there's not any clear benefit to it anyway...

> AFAIK, k8s doesn't but openshift does.

Nope. OpenShift doesn't do it either

**Comment by thockin** [comment]
Why do you need pings and with what semantics?

If you ping it, do you expect to actually ping a backend?  Or just to
return true if any backend exists?  What if one backend is dead, or not
ready?

Additionally, I don't think all implementations can support this, so I
would like to know what you are trying to achieve.

On Jun 9, 2017 10:15 AM, "Dan Winship" <notifications@github.com> wrote:

The iptables proxier could make pings work, but it would be much more
complicated for the userspace proxier. And there's not any clear benefit to
it anyway...

AFAIK, k8s doesn't but openshift does.

Nope. OpenShift doesn't do it either

—
You are receiving this because you are on a team that was mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/47156#issuecomment-307447261>,
or mute the thread

**Comment by xiangpengzhao** [comment]
I guess users want this for troubleshooting. Suppose they create a service but cannot access it (e.g. `curl clusterIP:port` fails), the first thing they try to do might be `ping clusterIP` to see if the clusterIP is reachable. Then they can decide to check the network or the backend itself. But "the clusterIP is reachable" might mean "the service is healthy" in users' mind.

@yan234280533 do I understand your use case correctly?

**Comment by yan234280533** [comment]
@xiangpengzhao  Yes, it is surely what I want to say. I know that  even though it give an ping clusterIP  reachable, it cannot prove anything. If we use curl clusterIP:port fails, I must to check the iptables and get infomation from iptable logs. So many thanks for everybody.

**Comment by yan234280533** [comment]
To make  ping clusterIP reachable cannot prove anything.  So it not an good idea to make  ping clusterIP reachable . Close the issue.

**Comment by yan234280533** [comment]
I think

**Comment by cmluciano** [comment]
/close 

After discussion in SIG-Network, this is not a feature that we are prepared to support.

**Comment by parkybyang** [comment]
support already
