### ISSUE TITLE
Fill in *ByID methods for the various clouds in Kubernetes

### ISSUE THREAD

**Issue by wlan0** [kubernetes/kubernetes#47257]
This is required to make Cloud Controller Manager operational on the various clouds that Kubernetes runs on.

We have already added PRs for the following clouds:

GCE - https://github.com/kubernetes/kubernetes/pull/45313
AWS - https://github.com/kubernetes/kubernetes/pull/47215
Azure - https://github.com/kubernetes/kubernetes/pull/46940
OpenStack - https://github.com/kubernetes/kubernetes/pull/47593

The following clouds still need to be addresses:

CloudStack
Mesos
OVirt
Photon
Rackspace
vSphere

If anyone is interested in contributing to this effort, please ping me directly (on kubernetes slack or through email)

**Comment by divyenpatel** [comment]
cc: @luomiao @BaluDontu @rohitjogvmw @tusharnt

**Comment by luomiao** [comment]
I will take care of the vSphere and Photon.

**Comment by FengyunPan** [comment]
@wlan0 I will take care of the Rackspace.

**Comment by dims** [comment]
Merging #47593 for OpenStack

**Comment by tamalsaha** [comment]
Reposting  https://github.com/kubernetes/kubeadm/issues/408

I am trying to use my custom out-of-tree cloud provider with Kubernetes. I am able to run it thanks to help from @luxas . But I noticed that kubelet calls apis like `NodeAddressByProviderID()` with empty `providerID` for `external` cloud provider. Digging in the code for 1.7 branch, I see that `Kubelet.Cloud` is null for `external` cloud-providers. As a result `GetInstanceProviderID(..)` returns empty string. As a result, ByID() methods don't work for `external` cloud providers since `providerID` is not set.
