### ISSUE TITLE
[e2e] Namespaces [Serial] should ensure that all pods are removed when a namespace is deleted.

### ISSUE THREAD

**Issue by ericchiang** [kubernetes/kubernetes#47350]
Test is constantly failing. https://github.com/kubernetes/kubernetes/blob/0cb3cb254909d7a2c271f91caaf77eaa46eea48a/test/e2e/namespace.go#L267-L268

https://k8s-testgrid.appspot.com/release-master-blocking#gce-serial&width=20

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/namespace.go:265
Expected error:
    <*errors.errorString | 0xc421a2cc80>: {
        s: "an empty namespace may not be set when a resource name is provided",
    }
    an empty namespace may not be set when a resource name is provided
not to have occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/namespace.go:95
```

https://k8s-testgrid.appspot.com/release-master-blocking#gce-serial&width=20

/cc @kubernetes/sig-api-machinery-bugs @kubernetes/kubernetes-release-managers @dchen1107

**Comment by dchen1107** [comment]
After https://github.com/kubernetes/kubernetes/pull/47212 was manually merged last Friday, serial tests is back to normal flaky stage except this test which is constantly failing. Raise the priority.

**Comment by derekwaynecarr** [comment]
i will take a look.

**Comment by caesarxuchao** [comment]
Is https://github.com/kubernetes/kubernetes/pull/47191 supposed to fix this?

**Comment by ericchiang** [comment]
@caesarxuchao they seem like different issues.

https://github.com/kubernetes/kubernetes/issues/47135 is about slow namespace deletion. This seems to be an issue with the namespace objects being created?

**Comment by ericchiang** [comment]
@ethernetdan spotted a bug in the tests. Sent https://github.com/kubernetes/kubernetes/pull/47364

**Comment by derekwaynecarr** [comment]
@ericchiang -- i think this is a separate issue.. for some reason, an empty namespace name is being passed into client which doesnt appear possible at first glance.

**Comment by smarterclayton** [comment]
I'm going to necro this bug because I figured out why it's failing

1. create pod
2. kubelet starts trying to get pod
3. delete namespace
4. kubelet starts trying to get the service account secret, but it's been deleted
5. kubelet keeps trying and trying and trying

```
Mar  7 23:19:10.033: INFO: error from create uninitialized namespace: <nil>

...

Mar 07 23:19:10 ip-10-0-160-63 systemd[1]: Started e2e-tests-nsdeletetest-7nsnl/test-pod-uninitialized/POD.
...
Mar 07 23:19:17 ip-10-0-160-63 hyperkube[4094]: W0307 23:19:17.678563    4094 kubelet_pods.go:854] Unable to retrieve pull secret e2e-tests-nsdeletetest-7nsnl/default-dockercfg-p7kct for e2e-tests-nsdeletetes
...
Mar 07 23:20:22 ip-10-0-160-63 hyperkube[4094]: E0307 23:20:22.217103    4094 nestedpendingoperations.go:267] Operation for "\"kubernetes.io/secret/6976f055-412f-11e9-a2af-0e0988945c7c-default-token-27wj2\" (
\"6976f055-412f-11e9-a2af-0e0988945c7c\")" failed. No retries permitted until 2019-03-07 23:21:26.217059437 +0000 UTC m=+2074.523191255 (durationBeforeRetry 1m4s). Error: "MountVolume.SetUp failed for volume
\"default-token-27wj2\" (UniqueName: \"kubernetes.io/secret/6976f055-412f-11e9-a2af-0e0988945c7c-default-token-27wj2\") pod \"test-pod-uninitialized\" (UID: \"6976f055-412f-11e9-a2af-0e0988945c7c\") : secrets
 \"default-token-27wj2\" not found"
...
Mar 07 23:21:26 ip-10-0-160-63 hyperkube[4094]: I0307 23:21:26.241773    4094 reconciler.go:181] operationExecutor.UnmountVolume started for volume "default-token-27wj2" (UniqueName: "kubernetes.io/secret/6976f055-412f-11e9-a2af-0e0988945c7c-default-token-27wj2") pod "6976f055-412f-11e9-a2af-0e0988945c7c" (UID: "6976f055-412f-11e9-a2af-0e0988945c7c")
Mar 07 23:21:26 ip-10-0-160-63 hyperkube[4094]: I0307 23:21:26.247861    4094 operation_generator.go:698] UnmountVolume.TearDown succeeded for volume "kubernetes.io/secret/6976f055-412f-11e9-a2af-0e0988945c7c-default-token-27wj2" (OuterVolumeSpecName: "default-token-27wj2") pod "6976f055-412f-11e9-a2af-0e0988945c7c" (UID: "6976f055-412f-11e9-a2af-0e0988945c7c"). InnerVolumeSpecName "default-token-27wj2". PluginName "kubernetes.io/secret", VolumeGidValue ""
Mar 07 23:21:26 ip-10-0-160-63 hyperkube[4094]: I0307 23:21:26.342115    4094 reconciler.go:301] Volume detached for volume "default-token-27wj2" (UniqueName: "kubernetes.io/secret/6976f055-412f-11e9-a2af-0e0988945c7c-default-token-27wj2") on node "ip-10-0-160-63.ec2.internal" DevicePath ""
```

Logs above are from 1.12.

When a pod is detected as deleted, we're trying to unmount a secret that can't / doesn't exist.  The fact that the pod is deleted should abort mount much faster, even if mount is in backoff.

@kubernetes/sig-storage-bugs this is a flaky conformance test (and fixing this should have an impact on other failure modes like this).

**Comment by smarterclayton** [comment]
It is different than the other cause but we should assess which linked issues are actually this problem.

**Comment by msau42** [comment]
cc @gnufied fixed a secret teardown issue in the past

**Comment by gnufied** [comment]
@smarterclayton I am not sure if it is a bug as such.  It is true that when pod is removed, volumemanager tries to mount the volume anyways and since it fails to fetch secret, it keeps failing.  

1. Failing to fetch secret is a non-fatal error and volumemamanger is right in retrying that operation.
2. I think bit that is problematic is - mount and unmount operation basically share the exponential backoff . I have filed https://github.com/kubernetes/kubernetes/issues/75209 to track this.

A workaround might be to increase the wait period in following code:

```
maxWaitSeconds := int64(60) + *pod.Spec.TerminationGracePeriodSeconds
	framework.ExpectNoError(wait.Poll(1*time.Second, time.Duration(maxWaitSeconds)*time.Second,
		func() (bool, error) {
			_, err = f.ClientSet.CoreV1().Namespaces().Get(namespace.Name, metav1.GetOptions{})
			if err != nil && errors.IsNotFound(err) {
				return true, nil
			}
			return false, nil
		}))
```

But I can see how having this shared exp. backoff may have dominos effect on other tests and may be pod teardown time can be improved in general if mount and unmount did not share the exp. backoff.

**Comment by johnSchnake** [comment]
As far as I can see the issue has now been resolved; on test grid I see only green for this test:
https://k8s-testgrid.appspot.com/sig-release-master-blocking#gce-cos-master-serial
https://k8s-testgrid.appspot.com/sig-api-machinery-gce-gke#gce-serial

https://github.com/kubernetes/kubernetes/pull/75213 was the PR that seems to have fixed this.

/close
