### ISSUE TITLE
Test Failure: Scaling should happen in predictable order and halt if any stateful pod is unhealthy

### ISSUE THREAD

**Issue by monopole** [kubernetes/kubernetes#47378]
Scaling should happen in predictable order and halt if any stateful pod is unhealthy"

Has been failing forever - possibly checking deprecated behavior?

[jenkins](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-cvm-1-6-cvm-1-7-upgrade-cluster/7#k8sio-statefulset-k8sio-basic-statefulset-functionality-statefulsetbasic-scaling-should-happen-in-predictable-order-and-halt-if-any-stateful-pod-is-unhealthy)

[test-grid](https://k8s-testgrid.appspot.com/1.6-1.7-upgrade#gke-cvm-upgrade-cluster&include-filter-by-regex=%5EOverall%24%7C%5C%5Bk8s%5C.io%5C%5D%5C%20StatefulSet%5C%20%5C%5Bk8s%5C.io%5C%5D%5C%20Basic%5C%20StatefulSet%5C%20functionality%5C%20%5C%5BStatefulSetBasic%5C%5D%5C%20Scaling%5C%20should%5C%20happen%5C%20in%5C%20predictable%5C%20order%5C%20and%5C%20halt%5C%20if%5C%20any%5C%20stateful%5C%20pod%5C%20is%5C%20unhealthy)

/assign @lavalamp 
/sig scalability

**Comment by kow3ns** [comment]
@monopole The semantics of the API changed between 1.6 and 1.7. The 1.6 tests will break against a 1.7 drop due to StatefulSetStatus being updated to conform to DaemonSetStatus and DeploymentStatus. The 1.7 version of e2e seems stable against a 1.7 cluster and the 1.6 e2e should work against a 1.6 cluster.

**Comment by monopole** [comment]
@kow3ns This failure is part of ci-kubernetes-e2e-gke-cvm-1-6-cvm-1-7-upgrade-cluster, meant to ensure that things continue to work properly during an upgrade when a skew is unavoidable. My understanding is that stuff should work with a delta of one in the minor version number.

So is this test a good test that is failing (and hence blocks the 1.7 release), or a bad test that should not exist?

**Comment by kow3ns** [comment]
@monopole It's a test that was written without consideration for any type of API skew back in the 1.4 - 1.5 time frame when upgrade validation was still manual and before we were running e2e with version skew.  It shouldn't block 1.7 release. We also shouldn't remove it yet, as its one of the only indicators that the 1.6.x version of StatefulSet is working as intended. We do need to redesign the StatefulSet e2e so that its better suited to handling version skew, and that should have probably been a priority prior to (or in conjunction with) automating upgrade testing, but its on the radar now at least. We need to update the 1.6.x branch and 1.7.x branch with e2e that is better suited to what we're trying to achieve.

**Comment by crimsonfaith91** [comment]
@kow3ns I can work on redesigning this test.

This test examines `Replicas` when running against v1.6 cluster (by calling `WaitForStatus()`) and `ReadyReplicas` when running against v1.7 cluster (by calling `WaitForStatusReadyReplicas()`). When running the v1.6-v1.7 upgrade test, this test examines `Replicas` against v1.7 cluster.

I speculate that the order is changed due to presence of non-ready replicas.

IMO, a potential fix is to rewrite this test in a way that it examines `Replicas` for _both_ v1.6 and v1.7 cluster. In addition, we can add a new e2e test for v1.7+ cluster.

**Comment by monopole** [comment]
Thanks so much for wanting to re-engineering these tests.

But can you disable them first please?  They are red and we need a green dashboard for release.  

Please add a skip as in 
https://github.com/kubernetes/kubernetes/blob/97212f5b3a2961d0b58a20bdb6bda3ccfa159bd7/test/e2e/service_accounts.go#L246

**Comment by crimsonfaith91** [comment]
@monopole definitely! I will do it asap. :)

**Comment by crimsonfaith91** [comment]
/close
It has been resolved during last quarter.
