### ISSUE TITLE
How can I schedule my pods on wanted nodes with my custom policy?

### ISSUE THREAD

**Issue by dearboll** [kubernetes/kubernetes#47648]
Hello, I have a cluster with two IP ranges, which are x.x.x.7 and x.x.x.8. Now I have a new schedule requirement that all the Pods should run on x.x.x.7 nodes. It is too late for me to label the two IP ranges. So I think I should use custom scheduler. But I have read https://github.com/kubernetes/community/blob/master/contributors/devel/scheduler.md#scheduler-extensibility but still have no ideas and do not understand how the policy works. Can I use "Predicates" to filter out x.x.x.8 nodes?

**Comment by bowei** [comment]
@dearboll It is recommended to send support issues to the kubernetes slack channel or stackoverflow:

https://kubernetes.slack.com
https://stackoverflow.com/questions/tagged/kubernetes

Issues are meant to track bugs/features.

**Comment by castrojo** [comment]
Please re-post your question to [Stack Overflow](http://stackoverflow.com/questions/tagged/kubernetes).

Thanks for taking the time to report an issue to us. In the past this tracker has housed both bug reports and user support requests, we are now only using this tracker for software defects and feature tracking.   

We are trying to consolidate the channels to which questions for help/support
are posted so that we can improve our efficiency in responding to requests,
and to make it easier for you to find answers to frequently asked questions and
how to address common use cases.

The Kubernetes team scans Stack Overflow on a regular basis, and will try to
ensure your questions don't go unanswered.

If you're looking for more long-form discussion on best practices, we encourage you to check out the [Kubernetes user list](https://groups.google.com/forum/#!forum/kubernetes-users). 

You can also find more information here:

  * [User Documentation](http://kubernetes.io/docs/)
  * [Troubleshooting Guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/)

Again, thanks for using Kubernetes. If you feel this issue has been closed in error then please reopen it and we can have another look. 

The Kubernetes Team
