### ISSUE TITLE
alpha features are enabled by default

### ISSUE THREAD

**Issue by caesarxuchao** [kubernetes/kubernetes#47687]
In https://github.com/kubernetes/kubernetes/blob/master/pkg/master/master.go#L384,
```
admissionregistrationv1alpha1.SchemeGroupVersion,
rbacv1alpha1.SchemeGroupVersion,
settingv1alpha1.SchemeGroupVersion,
```
These alpha versions are enabled by default, is it intentional?

I can answer for admissionregistration, it's not intentional.
cc @liggitt for rbac
cc @pwittrock for setting

**Comment by caesarxuchao** [comment]
Not sure what sig it belongs to.

**Comment by pwittrock** [comment]
> settingv1alpha1.SchemeGroupVersion

This should be off by default

**Comment by dchen1107** [comment]
Good finding! But shouldn't by default, all alpha features are disabled; then enabled through the feature-gate?

**Comment by dchen1107** [comment]
@caesarxuchao I am assigning this to you since you are the last one touching above three alpha api resources. ;-) Please feel free to delegate to others.

**Comment by liggitt** [comment]
yes, alpha API versions are supposed to be disabled by default. Storage and API group enablement predate feature gates, so the mechanism is different.

That said, API group enablement and storage enablement are distinct, and once a storage version is enabled, it should not be disabled to ensure that etcd data from previous releases can continue to be read.

RBAC v1alpha1 storage was enabled [in 1.5](https://github.com/kubernetes/kubernetes/blob/release-1.5/pkg/master/master.go#L379). Since it was enabled in a previous release, I would not make it conditional at this point. The default storage version is v1beta1 as of 1.6, so no new alpha data is being written.

**Comment by caesarxuchao** [comment]
@liggitt it seems the `DefaultAPIResourceConfigSource()` controls not only the storage enablement, but also if the groupversion shows in the discovery doc. Is there a separate knob to turn of the alpha versions in the discovery doc?

**Comment by caesarxuchao** [comment]
Are you saying it was a mistake to enable rbac v1alpha1 by defautl in 1.5, but we can't fix it know, so we should just leave it there?

Also, what are the feature gates? Could you point me to the code? Thanks.

**Comment by liggitt** [comment]
> Are you saying it was a mistake to enable rbac v1alpha1 by default in 1.5, but we can't fix it know, so we should just leave it there?

Something like that, though it appears that reading v1alpha1 data out of etcd still works fine even with the API group not exposed in discovery.

> Also, what are the feature gates? Could you point me to the code? Thanks.

https://github.com/kubernetes/kubernetes/blob/master/pkg/features/kube_features.go

used in places like https://github.com/kubernetes/kubernetes/blob/master/cmd/kubelet/app/server.go#L455

**Comment by dchen1107** [comment]
Now I remembered that we enabled rabac v1alpha1 by mistake in v1.5. Let's leave it as is, but including one comment, so that next release, the release management team wouldn't be confused like us.

**Comment by caesarxuchao** [comment]
settings/v1alpha1 is enabled in 1.6: https://github.com/kubernetes/kubernetes/blob/v1.6.1-beta.0/pkg/master/master.go#L383
