### ISSUE TITLE
[k8s.io] ESIPP [Slow] should only target nodes with endpoints flaky

### ISSUE THREAD

**Issue by caesarxuchao** [kubernetes/kubernetes#47745]
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/service.go:1388
Jun 19 14:59:16.138: Could not reach HTTP service through 35.188.108.201:80 after 5m0s: received non-success return status "404 Not Found" trying to access http://35.188.108.201:80/echo?msg=hello; got body: default backend - 404
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/service_util.go:764
```

https://k8s-testgrid.appspot.com/release-1.7-blocking#gci-gce-slow-release-1-7

It's quite flaky.

@kubernetes/kubernetes-release-managers

**Comment by caesarxuchao** [comment]
There are two failures in gci-gce-slow, so it's not specific to gke.
https://k8s-testgrid.appspot.com/release-master-blocking#gci-gce-slow

**Comment by MrHohn** [comment]
This is strange, seems like this test is trying to reach the test-netexec pod through servicePublicIP:serivcePort, but the request hit the gce default backend instead.

cc @nicksardo

**Comment by MrHohn** [comment]
There is another type of failure:
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/service.go:1388
Jun 13 23:53:21.095: Could not reach HTTP service through 35.189.240.206:80 after 5m0s: received non-success return status "404 Not Found " trying to access http://35.189.240.206:80/echo?msg=hello; got body: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN">
<HTML>
  <HEAD><TITLE>Not Found</TITLE></HEAD>
  <BODY>
    <H1>Not Found</H1>
    `/echo' not found.
    <HR>
    <ADDRESS>
     WEBrick/1.3.1 (Ruby/2.1.5/2014-11-13) at
     35.189.240.206:80
    </ADDRESS>
  </BODY>
</HTML>

/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/service_util.go:764
```
Seems to be the port collision between test service and fluentd daemonset, which changed to use 31337 few days ago (#47402).

**Comment by MrHohn** [comment]
cc @crassirostris

**Comment by MrHohn** [comment]
> Seems to be the port collision between test service and fluentd daemonset, which changed to use 31337 few days ago (#47402).

Checked the kube-proxy logs and found this is not the case. Port 31337 was not allocated (although that could happen in theory) to any service during test: https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-slow-release-1-7/306/artifacts/bootstrap-e2e-minion-group-4cbf/kube-proxy.log

**Comment by MrHohn** [comment]
This turned out to be an interesting corner case. It happens at the beginning after we set up the GCE network LoadBalancer for OnlyLocal service --- when the LB still forwarding traffic onto nodes that don't have endpoints on.

For more context, when network LB forward traffic to nodes, packet arrives node with below src:dst:
| src - clientIP:clientPort        |
| dst - lbPublicIP:servicePort |

If no endpoints are on the node, and there happens to have a pod using hostPort with the same port number, packet will be DNAT to that pod IP instead. These are observations and I haven't traced down to the exact iptables entries.

I'm changing service port in test to avoid collision for now.

cc @dnardo
