### ISSUE TITLE
SchedulerPredicates - failures in 1.6 to 1.7 upgrade tests

### ISSUE THREAD

**Issue by monopole** [kubernetes/kubernetes#47767]
## [triage query](https://storage.googleapis.com/k8s-gubernator/triage/index.html?job=1-5-.*-1-7.*upgrade&test=SchedulerPredicates)

Within the above link can be found failures for
* SchedulerPredicates [Serial] validates that Inter-pod-Affinity is respected if not matching
* SchedulerPredicates [Serial] validates that InterPodAntiAffinity is respected if matching 2
* SchedulerPredicates [Serial] validates that NodeAffinity is respected if not matching
* SchedulerPredicates [Serial] validates that taints-tolerations is respected if not matching
* SchedulerPredicates [Serial] validates that InterPodAffinity is respected if matching
* SchedulerPredicates [Serial] validates that InterPod Affinity and AntiAffinity is respected if matching
* SchedulerPredicates [Serial] validates that embedding the JSON PodAffinity and PodAntiAffinity setting as a string in the annotation value work
* SchedulerPredicates [Serial] validates that InterPodAffinity is respected if matching with multiple Affinities

### Sampled failures:

[SchedulerPredicates [Serial] validates that Inter-pod-Affinity is respected if not matching](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-cvm-1-5-cvm-1-7-upgrade-cluster/18#k8sio-schedulerpredicates-serial-validates-that-inter-pod-affinity-is-respected-if-not-matching)

```
go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scheduler_predicates.go:461
Not scheduled Pods: []api.Pod(nil)
Expected
    <int>: 0
to equal
    <int>: 1
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scheduler_predicates.go:930
```

[SchedulerPredicates [Serial] validates that InterPod Affinity and AntiAffinity is respected if matching](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-cvm-1-5-cvm-1-7-upgrade-cluster/18#k8sio-schedulerpredicates-serial-validates-that-interpod-affinity-and-antiaffinity-is-respected-if-matching)
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scheduler_predicates.go:640
Expected
    <string>: gke-bootstrap-e2e-default-pool-efb8e5cb-rvjc
to equal
    <string>: gke-bootstrap-e2e-default-pool-efb8e5cb-nt2j
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scheduler_predicates.go:639
```

Other failures look similar.

/sig scheduling
/assign @davidopp

**Comment by dchen1107** [comment]
@davidopp we need to triage this issue to decide if there are release blocking or not.

cc/ @kubernetes/sig-scheduling-misc

**Comment by k82cn** [comment]
I'll check what happened as input for triage

**Comment by timothysc** [comment]
This is all expected.  Affinity changed from annotation to field and broke compat from alpha to beta.

**Comment by monopole** [comment]
@timothysc Did you have someone in mind to fix the broken test?

**Comment by davidopp** [comment]
@monopole These should all be disabled for 1.5-1.7 upgrade, not fixed.

**Comment by timothysc** [comment]
> These should all be disabled for 1.5-1.7 upgrade, not fixed. 

Yup, There was another issue open where I said pretty much the same thing.  We need to collect a skip expression to pass to ginkgo that simply skips these. 

/cc @fejta @spiffxp

**Comment by monopole** [comment]
@timothysc 

I agree.  Will you disable the test please?

FWIW, I'm working w/ some others to get upgrade tests against master up as soon as possible so we'll see failures like this sooner - i.e. within 24h of the breaking change.

**Comment by monopole** [comment]
Ginkgo "skip" or modify the go on the 1.5 release branch as in
https://github.com/kubernetes/kubernetes/blob/97212f5b3a2961d0b58a20bdb6bda3ccfa159bd7/test/e2e/service_accounts.go#L246

**Comment by timothysc** [comment]
@monopole who is your test lead?  They can/should do it.. I'm not even certain where the upgrade tests live.

**Comment by davidopp** [comment]
@bsalamat Can you take care of getting this test disabled in the 1.5-1.7 upgrade suite?

**Comment by davidopp** [comment]
^ That should say "these tests"

**Comment by bsalamat** [comment]
I can add something similar to what @monopole [pointed out](https://github.com/kubernetes/kubernetes/blob/97212f5b3a2961d0b58a20bdb6bda3ccfa159bd7/test/e2e/service_accounts.go#L246), but I wonder if it addresses the upgrade scenarios. The check would skip the test if the cluster was not 1.6 or higher, but the check wouldn't be in 1.5 tests and if we ran those tests against a 1.7 cluster, they would still fail. So, I think we should probably do a Gingko skip for these tests.

**Comment by monopole** [comment]
So Dawn, Phil and i are agreed that we're going to ignore these for the 1.5->1.7 case (no need to skip).
Bad practice, but meh.

Retitling bug to focus on 1.6->1.7.   We still have failures there in SchedulerPredicates family.

Please click on this [1.6->1.7 triage link](https://storage.googleapis.com/k8s-gubernator/triage/index.html?job=1-6-.*-1-7.*upgrade&test=SchedulerPredicates) and look at the dates on the failures.

At time of writing (today in 23), there were failures on 22, 21, 20.

**Comment by monopole** [comment]
ptal @bsalamat , and thanks for your help!  Narrowing it all down takes time.

**Comment by bsalamat** [comment]
@monopole I looked at several tests from [your link](https://storage.googleapis.com/k8s-gubernator/triage/index.html?job=1-6-.*-1-7.*upgrade&test=SchedulerPredicates). It looks like the predicate tests have failed when many other tests have failed and they have passed when most tests have passed, so maybe those failures are caused by bad builds.
Lets look at a few examples:
[[k8s.io] SchedulerPredicates [Serial] validates that NodeAffinity is respected if not matching](https://k8s-testgrid.appspot.com/1.6-1.7-upgrade#gke-cvm-gci-upgrade-master&include-filter-by-regex=%5EOverall%24%7C%5C%5Bk8s%5C.io%5C%5D%5C%20SchedulerPredicates%5C%20%5C%5BSerial%5C%5D%5C%20validates%5C%20that%5C%20NodeAffinity%5C%20is%5C%20respected%5C%20if%5C%20not%5C%20matching) has failed at 06-22 19:45, 06-20 23:09 & 03:43. Now, let's take a look the [test grid for all tests](https://k8s-testgrid.appspot.com/1.6-1.7-upgrade#gke-cvm-gci-upgrade-master): We see many other failures at 6-22 19:45. A bad build maybe. 06-20 23:09 & 03:43 are better, but in those builds almost all of the scheduler tests have failed.

[[k8s.io] SchedulerPredicates [Serial] validates that InterPodAffinity is respected if matching with multiple Affinities](https://k8s-testgrid.appspot.com/1.6-1.7-upgrade#gke-cvm-gci-upgrade-cluster&include-filter-by-regex=%5EOverall%24%7C%5C%5Bk8s%5C.io%5C%5D%5C%20SchedulerPredicates%5C%20%5C%5BSerial%5C%5D%5C%20validates%5C%20that%5C%20InterPodAffinity%5C%20is%5C%20respected%5C%20if%5C%20matching%5C%20with%5C%20multiple%5C%20Affinities) has failed at 06-21 16:20, 06-20 19:04, 06-19 03:30. If we look at [the full test grid](https://k8s-testgrid.appspot.com/1.6-1.7-upgrade#gke-cvm-gci-upgrade-cluster), there are many other test failures at these times.

Similarly, we see many other test failures in [the full test grid](https://k8s-testgrid.appspot.com/1.6-1.7-upgrade#gke-cvm-upgrade-cluster) when [[k8s.io] SchedulerPredicates [Serial] validates that taints-tolerations is respected if not matching](https://k8s-testgrid.appspot.com/1.6-1.7-upgrade#gke-cvm-upgrade-cluster&include-filter-by-regex=%5EOverall%24%7C%5C%5Bk8s%5C.io%5C%5D%5C%20SchedulerPredicates%5C%20%5C%5BSerial%5C%5D%5C%20validates%5C%20that%5C%20taints%5C-tolerations%5C%20is%5C%20respected%5C%20if%5C%20not%5C%20matching) has failed.

**Comment by marun** [comment]
@bsalamat @monopole Any update on this?

**Comment by bsalamat** [comment]
@marun My update is already there. I think these tests are fine.

**Comment by marun** [comment]
@bsalamat So should the issue continue blocking 1.7?  If not, please remove the 'approved-for-milestone' label.

**Comment by davidopp** [comment]
I've removed the label.

**Comment by spiffxp** [comment]
/close
I'm taking an educated guess that this issue won't get worked on as we're now in the 1.10 release cycle.  Please /reopen if you disagree or notice these tests failing in a later version of the upgrade tests
