### ISSUE TITLE
Changelog not formatted correctly

### ISSUE THREAD

**Issue by janetkuo** [kubernetes/kubernetes#47805]
The v1.7.0-alpha.4 [changelog](https://github.com/kubernetes/kubernetes/blame/master/CHANGELOG.md#L1191) generated from #39164 PR description has weird format:

![image](https://user-images.githubusercontent.com/4876867/27349803-54e4f120-55ad-11e7-9a1f-ebd771ceddec.png)

cc @danwinship

**Comment by caesarxuchao** [comment]
cc @david-mcmahon

**Comment by danwinship** [comment]
Hm... I wonder if it's because the second line starts with a backtick? It would be easy to reword/rewrap to change that.

The "1. ..." "2. ..." second is also indented too much... I had written it to look right as plain text since that's how it got displayed in the release note field in the PR, but I guess it's supposed to be markdown?

**Comment by david-mcmahon** [comment]
Yeah, there's a bunch of translations happening here (pandoc) to get HTML formatted email notifications and md for the changelog from the same human curated md source extracted out of the PR descriptions. 

Release notes really should be much simpler than this.    There's no need to add an "Action Required" headline as that happens automatically with the `release-note-action-required` label and there's a lot of formatting going on in this release note (multiple paragraphs, indenting, numbering.  KISS is best for release notes.

At this point, the release notes can be hand-modified within changelog as needed to correct any formatting issues.

**Comment by dchen1107** [comment]
We need to fix this, but I don't think this is the release blocker.
