### ISSUE TITLE
Generation and ObservedGeneration should not be optional

### ISSUE THREAD

**Issue by khogeland** [kubernetes/kubernetes#47871]
These fields are marked optional on every type that uses them. This makes it impossible to _reliably_ use ObservedGeneration as a sanity check. It should always be populated so that it can be used to verify you are looking at a status for the correct version of the resource.

In Kubernetes 1.5, the ObservedGeneration in StatefulSetStatus was never populated ([this appears to have been fixed in later versions](https://github.com/kubernetes/kubernetes/commit/1b55f57391f5a648b1f9859118a2d1fef7017ffe#diff-daa5b073ddfa8e3390bee583280edb5bR260)). This made deleting a StatefulSet by scaling it down and then deleting it an unreliable operation, because there was no way to know that the reported number of replicas was current. If it were enforced that these fields were populated, it would not have been possible to introduce this bug.

As these fields are optional, it's possible that a future update will introduce similarly difficult behavior.

**Comment by kargakis** [comment]
Generation is always set on the creation of a resource to 1 so once a controller observes a resource for the first time, the resource's ObservedGeneration is never going to be nil again. The statefulset case was a bug that got fixed in 1.6 (https://github.com/kubernetes/kubernetes/pull/42429).

**Comment by khogeland** [comment]
Right, so semantically the field is not actually optional. The observed generation could be initialized to `-1` instead of attaching meaning to a nil value, which also makes it possible to treat

**Comment by khogeland** [comment]
On my phone, misclicked :-)

**Comment by khogeland** [comment]
>Generation is always set on the creation of a resource to 1 so once a controller observes a resource for the first time, the resource's ObservedGeneration is never going to be nil again

Right, so semantically the field is not actually optional. The observed generation could be initialized to `-1` instead of attaching meaning to a nil value.

**Comment by kargakis** [comment]
Why is it unreasonable for clients to assume that the lack of the field means that the controller still hasn't observed the resource? Should we consider meaning on nil values an anti-pattern? Pretty sure we have other fields too where nil has meaning, eg. RevisionHistoryLimit.

**Comment by khogeland** [comment]
>Why is it unreasonable for clients to assume that the lack of the field means that the controller still hasn't observed the resource?

Clients can't assume that because the meaning of the nil value does not appear to be documented. As a consumer of this API, neither the godoc comments, API Reference, nor the API Conventions tell me what the absence of the field means.

Meaning on nil values should be considered an anti-pattern (IMHO), because it is difficult to know what it means as a consumer of the API. In the case of the StatefulSet bug, there was no way of knowing whether the nil value was intentional or accidental. If the value was supposed to be initialized to something like `-1`, and it wasn't documented as optional, it would have been obvious if it was missing.

**Comment by kargakis** [comment]
So this seems to me more of a documentation issue because even in the -1 case we would have to document that. Between the two, I prefer nil - negative values are invalid for Generation/ObservedGeneration today. I also dislike the fact that we have to choose a special value basically for communicating the absence of the controller observation when we already have nil by default. I know @smarterclayton and @kow3ns were discussing this recently and they have opinions on this one too.

**Comment by khogeland** [comment]
I agree it could be solved with documentation. A few clarifying questions:
- How and why is it possible to get a status object for an resource that hasn't yet been observed? Why isn't the status itself nil instead of the ObservedGeneration field?
- Why is the Generation field marked optional if it is set to 1 upon the creation of the resource?

**Comment by smarterclayton** [comment]
Generation is not allowed to be zero (unless something scary changed),
which is why in the other issue I preferred 0

On Jun 22, 2017, at 12:30 PM, Michail Kargakis <notifications@github.com>
wrote:

So this seems to me more of a documentation issue because even in the -1
case we would have to document that. Between the two, I prefer nil -
negative values are invalid for Generation/ObservedGeneration today. I also
dislike the fact that we have to choose a special value basically for
communicating the absence of the controller observation when we already
have nil by default. I know @smarterclayton
<https://github.com/smarterclayton> and @kow3ns <https://github.com/kow3ns>
were discussing this recently and they have opinions on this one too.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/47871#issuecomment-310448586>,
or mute the thread
