### ISSUE TITLE
How to get Node metrics using API?

### ISSUE THREAD

**Issue by vectar31** [kubernetes/kubernetes#47895]
So, I am writing a custom auto rescheduler  which should get node metrics (lets take memory usage in this case) and then if it is high reschedule a pod in another node with lesser memory usage. I know that cAdvisor picks up the metrics and gives it to heapster which are available at a rest endpoint. I don't have heapster deployed on my server and I use prometheus for scraping metrics. Is there any Kubernetes API which can be used to directly get node metrics, because I couldn't find any.

**Comment by vectar31** [comment]
@kubernetes/sig-monitoring

**Comment by cblecker** [comment]
Please re-post your question to [Stack Overflow](http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases.

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans Stack Overflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search Stack Overflow for answers to similar questions, and also familiarize yourself with:

  * [user documentation](http://kubernetes.io/docs/)
  * [troubleshooting guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/)

Again, thanks for using Kubernetes.

The Kubernetes Team

---
/close
