### ISSUE TITLE
Can a pod have two containers of different privilege level? For example Container 'A' is a regular container and Container 'B' is a privileged container that can alter the network stack. Both containers will be packaged in a single pod. Now if the pod's privileged parameter is set true, would it mean that both of the containers are now privileged? or otherwise? thanks.  /sig <area/docker> 

### ISSUE THREAD

**Issue by ZirakZaheer** [kubernetes/kubernetes#47907]

**Comment by castrojo** [comment]
Please re-post your question to [Stack Overflow](http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support
are posted so that we can improve our efficiency in responding to your requests,
and to make it easier for you to find answers to frequently asked questions and
how to address common use cases.

We regularly see messages posted in multiple forums, with the full response
thread only in one place or, worse, spread across multiple forums. Also, the
large volume of support issues on github is making it difficult for us to use
issues to identify real bugs.

The Kubernetes team scans Stack Overflow on a regular basis, and will try to
ensure your questions don't go unanswered.

Before posting a new question, please search Stack Overflow for answers to
similar questions, and also familiarize yourself with:

  * [user documentation](http://kubernetes.io/docs/)
  * [troubleshooting guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/)

Again, thanks for using Kubernetes.

The Kubernetes Team

**Comment by xiangpengzhao** [comment]
Please follow @castrojo comment, but FYI, you can set different security context for different containers. See: https://github.com/kubernetes/community/blob/master/contributors/design-proposals/security_context.md

**Comment by yujuhong** [comment]
Replied on stackoverflow already. Closing.
https://stackoverflow.com/questions/44702944/kubernetes-pod-having-containers-of-different-privileges
