### ISSUE TITLE
Image gc using overlay2 on fedora 26 appears broken. 

### ISSUE THREAD

**Issue by timothysc** [kubernetes/kubernetes#47943]
**What happened**:
Everything was running fine until image layers filled up all the free space for overlay2 and the kubelet died and tore down my masters.  

**What you expected to happen**:
It not to blow up my master

**How to reproduce it (as minimally and precisely as possible)**:
Have a reasonably small sized partition, fill it up with images by doing builds.  Doing a ```make release``` is a nice way to waste tons of space.  

Current supposition that overlay2 <> cadvisor stats monitoring is fubar.  

/cc @eparis @runcom @kubernetes/sig-node-bugs @derekwaynecarr

**Comment by derekwaynecarr** [comment]
we should get a corresponding issue opened in cAdvisor.

**Comment by dchen1107** [comment]
@derekwaynecarr Do you have time looking into the issue in detail? Based on the initial bug description, I think the root cause might be cAdvisor doesn't report overlay2 image usage properly, thus disk-based eviction manager doesn't take an action properly. 

cc/ @dashpole

**Comment by dashpole** [comment]
I tested this on a COS image using overlay2:

`docker info`
...
Server Version: 17.03.2-ce
Storage Driver: overlay2
...

The inode eviction test passed, and looking at the log had correct stats for container writable layer metrics and volume metrics.

Even if overlay2 metrics did not work, it should not result in a permanently filled filesystem.  DiskPressure is triggered by running low on disk space or inodes in the partition.  The stats used for triggering DiskPressure are collected from /proc/diskstats, and shouldnt have anything to do with the overlay driver being used.

If overlay2 was not working, we should observe incorrect summary metrics, and should observe "random" evictions rather than evictions targeting the largest consumers of the starved resources.

**Comment by dims** [comment]
@timothysc @derekwaynecarr @dashpole - Is there a PR in progress? Do we kick this to next-milestone/1.9?

**Comment by jdumars** [comment]
@timothysc @derekwaynecarr @dashpole - we need to determine (today if possible) if this is truly release blocking.  If so, please add the release-blocker label.  And, if not, how do we best continue work on this for 1.8.x/1.9.0?

**Comment by jdumars** [comment]
@timothysc @derekwaynecarr @dashpole @dchen1107 I'm going to pull this out of the milestone later today if there is no additional work being done here.

**Comment by dchen1107** [comment]
This is not a release blocker for 1.8 according to the analysis at https://github.com/kubernetes/kubernetes/issues/47943#issuecomment-330347721

**Comment by timothysc** [comment]
@dashpole The issue explicitly called out fedora 26, so unless you had vetted on that platform the experimental results are invalid, as the interaction on the sub-stack is non-trivial.

**Comment by dashpole** [comment]
@timothysc I intended to confirm two things:
1. Overlay2 storage driver stats collection is not generally broken. (confirmed by testing on COOS)
2. Your particular issue is not related to Overlay2. This is because the stats the kubelet uses to trigger disk pressure are node level stats, and thus are not related to the overlay storage driver.
So this issue is about node level disk metrics on Fedora 26.

**Comment by runcom** [comment]
This should be https://github.com/google/cadvisor/pull/1770

**Comment by derekwaynecarr** [comment]
this should now be fixed by the referenced change in cAdvisor.
