### ISSUE TITLE
Unable to mount volumes for pod

### ISSUE THREAD

**Issue by stijndehaes** [kubernetes/kubernetes#47956]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
My cassandra pod could not connect to it's persistent volume.

**What you expected to happen**:
My cassandra pod connects to it's persistent volume

**How to reproduce it (as minimally and precisely as possible)**:
After deleting the node it was impossible to reproduce. It happens sporadically again.

**Anything else we need to know?**:

This cassandra is started up using the example provided here: https://github.com/kubernetes/kubernetes/tree/master/examples/storage/cassandra
It is the StatefulSet example

**Environment**:
- Kubernetes version (use `kubectl version`): 1.6.5
- Cloud provider or hardware configuration**: AWS
- OS (e.g. from /etc/os-release): k8s-1.6-debian-jessie-amd64-hvm-ebs-2017-05-02 (ami-72aaa814)
- Kernel (e.g. `uname -a`):
- Install tools: kops
- Others:

Kubectl describe events:
```
Unable to mount volumes for pod "cassandra-0_cassandra(6d253337-575a-11e7-ada9-027f82b6849c)": timeout expired waiting for volumes to attach/mount for pod "cassandra"/"cassandra-0". list of unattached/unmounted volumes=[cassandra-data]
Error syncing pod, skipping: timeout expired waiting for volumes to attach/mount for pod "cassandra"/"cassandra-0". list of unattached/unmounted volumes=[cassandra-data]
```

Logs of kubelet:

```

Jun 23 05:38:49 ip-172-20-94-1 kubelet[1643]: I0623 05:38:49.170462    1643 aws.go:937] Could not determine public DNS from AWS metadata.
Jun 23 05:38:52 ip-172-20-94-1 kubelet[1643]: I0623 05:38:52.375923    1643 operation_generator.go:597] MountVolume.SetUp succeeded for volume "kubernetes.io/secret/08c118f5-575c-11e7-ada9-027f82b6849c-calico-token-1qlpn" (spec.Name:
Jun 23 05:38:56 ip-172-20-94-1 kubelet[1643]: I0623 05:38:56.287883    1643 operation_generator.go:597] MountVolume.SetUp succeeded for volume "kubernetes.io/secret/6d50eb3b-57d5-11e7-ada9-027f82b6849c-fluentd-token-g63h0" (spec.Name
Jun 23 05:38:59 ip-172-20-94-1 kubelet[1643]: I0623 05:38:59.194327    1643 aws.go:937] Could not determine public DNS from AWS metadata.
Jun 23 05:39:02 ip-172-20-94-1 kubelet[1643]: W0623 05:39:02.365130    1643 container_manager_linux.go:741] CPUAccounting not enabled for pid: 1320
Jun 23 05:39:02 ip-172-20-94-1 kubelet[1643]: W0623 05:39:02.365150    1643 container_manager_linux.go:744] MemoryAccounting not enabled for pid: 1320
Jun 23 05:39:02 ip-172-20-94-1 kubelet[1643]: I0623 05:39:02.365156    1643 container_manager_linux.go:397] [ContainerManager]: Discovered runtime cgroups name: /system.slice/docker.service
Jun 23 05:39:02 ip-172-20-94-1 kubelet[1643]: W0623 05:39:02.365222    1643 container_manager_linux.go:741] CPUAccounting not enabled for pid: 1643
Jun 23 05:39:02 ip-172-20-94-1 kubelet[1643]: W0623 05:39:02.365227    1643 container_manager_linux.go:744] MemoryAccounting not enabled for pid: 1643
Jun 23 05:39:02 ip-172-20-94-1 kubelet[1643]: I0623 05:39:02.651119    1643 qos_container_manager_linux.go:285] [ContainerManager]: Updated QoS cgroup configuration
Jun 23 05:39:05 ip-172-20-94-1 kubelet[1643]: I0623 05:39:05.211583    1643 server.go:778] GET /stats/summary/: (16.875887ms) 200 [[Go-http-client/1.1] 172.20.110.126:39798]
Jun 23 05:39:07 ip-172-20-94-1 kubelet[1643]: I0623 05:39:07.542687    1643 server.go:778] GET /metrics: (16.186222ms) 200 [[Prometheus/1.7.0] 172.20.83.16:36968]
Jun 23 05:39:09 ip-172-20-94-1 kubelet[1643]: I0623 05:39:09.215262    1643 aws.go:937] Could not determine public DNS from AWS metadata.
Jun 23 05:39:11 ip-172-20-94-1 systemd[1]: Started Kubernetes Kubelet Server.
Jun 23 05:39:14 ip-172-20-94-1 kubelet[1643]: E0623 05:39:14.275347    1643 kubelet.go:1549] Unable to mount volumes for pod "cassandra-0_cassandra(152dfb95-57d5-11e7-ada9-027f82b6849c)": timeout expired waiting for volumes to attach
Jun 23 05:39:14 ip-172-20-94-1 kubelet[1643]: E0623 05:39:14.275369    1643 pod_workers.go:182] Error syncing pod 152dfb95-57d5-11e7-ada9-027f82b6849c ("cassandra-0_cassandra(152dfb95-57d5-11e7-ada9-027f82b6849c)"), skipping: timeout
Jun 23 05:39:14 ip-172-20-94-1 kubelet[1643]: I0623 05:39:14.450420    1643 server.go:778] GET /metrics: (36.441527ms) 200 [[Prometheus/1.7.0] 172.20.32.123:54326]
Jun 23 05:39:19 ip-172-20-94-1 kubelet[1643]: I0623 05:39:19.235194    1643 aws.go:937] Could not determine public DNS from AWS metadata.
lines 6748-6801/6801 (END)
```

**Comment by wangycc** [comment]
I have also encountered the same problem, has not been able to solve.

Kubernetes version (use kubectl version): 1.6.4
Cloud provider or hardware configuration**: AWS
OS (e.g. from /etc/os-release): Centos7.2/Ubuntu 14.04.5 LTS
Kernel (e.g. uname -a):Ubuntu14:"Linux ip-10-100-6-251.cn-north-1.compute.internal 3.13.0-100-generic #147-Ubuntu SMP Tue Oct 18 16:48:51 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux",Centos7.2:"Linux ip-10-100-101-252 3.10.0-514.10.2.el7.x86_64 #1 SMP Fri Mar 3 00:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux"
Install tools: manual

kubelet config:

             /data/apps/kubernetes/bin/kubelet --address=10.100.101.252 --port=10250 --pod-infra-container-image=hub.xxxxxx.com/google_gcr/pause-amd64:3.0 --cgroup-driver=cgroupfs --cluster-dns=10.254.0.2 --experimental-bootstrap-kubeconfig=/data/apps/kubernetes/conf/bootstrap.kubeconfig --kubeconfig=/data/apps/kubernetes/conf/kubelet.kubeconfig --require-kubeconfig --cert-dir=/etc/kubernetes/ssl --cluster-domain=cluster.local. --hairpin-mode promiscuous-bridge --serialize-image-pulls=false --allow-privileged=true --logtostderr=false --v=0 --log-dir=/data/logs/kubernetes --cloud-provider=aws

events log:
  
             LASTSEEN   FIRSTSEEN   COUNT     NAME                              KIND      SUBOBJECT                         
             TYPE      REASON             SOURCE                                                    MESSAGE
		51m        51m         1         devops-algalon-1498698300-f35cr   Pod                                         Normal    Scheduled          {default-scheduler }                                      Successfully assigned devops-algalon-1498698300-f35cr to ip-10-100-101-252.cn-north-1.compute.internal
		51m        51m         1         devops-algalon-1498698300-f35cr   Pod       spec.containers{devops-algalon}   Normal    Pulled             {kubelet ip-10-100-101-252.cn-north-1.compute.internal}   Container image "hub.xxxx.com/devops/algalon-phpfpm:2.0.1" already present on machine
		51m        51m         1         devops-algalon-1498698300-f35cr   Pod       spec.containers{devops-algalon}   Normal    Created            {kubelet ip-10-100-101-252.cn-north-1.compute.internal}   Created container with id 27de07434848d67fd847ee015ef4777073ff86eb7410385e644736098ea0e95f
		51m        51m         1         devops-algalon-1498698300-f35cr   Pod       spec.containers{devops-algalon}   Normal    Started            {kubelet ip-10-100-101-252.cn-north-1.compute.internal}   Started container with id 27de07434848d67fd847ee015ef4777073ff86eb7410385e644736098ea0e95f
		49m        49m         1         devops-algalon-1498698300-f35cr   Pod                                         Warning   FailedMount        {kubelet ip-10-100-101-252.cn-north-1.compute.internal}   Unable to mount volumes for pod "devops-algalon-1498698300-f35cr_livechat(fd2a4ea8-5c66-11e7-8fd3-020312bf3de8)": timeout expired waiting for volumes to attach/mount for pod "livechat"/"devops-algalon-1498698300-f35cr". list of unattached/unmounted volumes=[default-token-n2zvw]
		49m        49m         1         devops-algalon-1498698300-f35cr   Pod                                         Warning   FailedSync         {kubelet ip-10-100-101-252.cn-north-1.compute.internal}   Error syncing pod, skipping: timeout expired waiting for volumes to attach/mount for pod "livechat"/"devops-algalon-1498698300-f35cr". list of unattached/unmounted volumes=[default-token-n2zvw]



kubelet logs:


E0629 10:00:08.028853   30980 nestedpendingoperations.go:262] Operation for "\"kubernetes.io/secret/7278f74d-56f8-11e7-82f5-020312bf3de8-default-token-98xbk\" (\"7278f74d-56f8-11e7-82f5-020312bf3de8\")" failed. No retries permitted until 2017-06-29 10:02:08.028828967 +0800 CST (durationBeforeRetry 2m0s). Error: UnmountVolume.TearDown failed for volume "kubernetes.io/secret/7278f74d-56f8-11e7-82f5-020312bf3de8-default-token-98xbk" (volume.spec.Name: "default-token-98xbk") pod "7278f74d-56f8-11e7-82f5-020312bf3de8" (UID: "7278f74d-56f8-11e7-82f5-020312bf3de8") with: rename /var/lib/kubelet/pods/7278f74d-56f8-11e7-82f5-020312bf3de8/volumes/kubernetes.io~secret/default-token-98xbk /var/lib/kubelet/pods/7278f74d-56f8-11e7-82f5-020312bf3de8/volumes/kubernetes.io~secret/wrapped_default-token-98xbk.deleting~195121711: device or resource busy
				E0629 10:02:08.033617   30980 nestedpendingoperations.go:262] Operation for "\"kubernetes.io/secret/7278f74d-56f8-11e7-82f5-020312bf3de8-default-token-98xbk\" (\"7278f74d-56f8-11e7-82f5-020312bf3de8\")" failed. No retries permitted until 2017-06-29 10:04:08.033593665 +0800 CST (durationBeforeRetry 2m0s). Error: UnmountVolume.TearDown failed for volume "kubernetes.io/secret/7278f74d-56f8-11e7-82f5-020312bf3de8-default-token-98xbk" (volume.spec.Name: "default-token-98xbk") pod "7278f74d-56f8-11e7-82f5-020312bf3de8" (UID: "7278f74d-56f8-11e7-82f5-020312bf3de8") with: rename /var/lib/kubelet/pods/7278f74d-56f8-11e7-82f5-020312bf3de8/volumes/kubernetes.io~secret/default-token-98xbk /var/lib/kubelet/pods/7278f74d-56f8-11e7-82f5-020312bf3de8/volumes/kubernetes.io~secret/wrapped_default-token-98xbk.deleting~574998084: device or resource busy
				E0629 10:04:08.127294   30980 nestedpendingoperations.go:262] Operation for "\"kubernetes.io/secret/7278f74d-56f8-11e7-82f5-020312bf3de8-default-token-98xbk\" (\"7278f74d-56f8-11e7-82f5-020312bf3de8\")" failed. No retries permitted until 2017-06-29 10:06:08.127271925 +0800 CST (durationBeforeRetry 2m0s). Error: UnmountVolume.TearDown failed for volume "kubernetes.io/secret/7278f74d-56f8-11e7-82f5-020312bf3de8-default-token-98xbk" (volume.spec.Name: "default-token-98xbk") pod "7278f74d-56f8-11e7-82f5-020312bf3de8" (UID: "7278f74d-56f8-11e7-82f5-020312bf3de8") with: rename /var/lib/kubelet/pods/7278f74d-56f8-11e7-82f5-020312bf3de8/volumes/kubernetes.io~secret/default-token-98xbk /var/lib/kubelet/pods/7278f74d-56f8-11e7-82f5-020312bf3de8/volumes/kubernetes.io~secret/wrapped_default-token-98xbk.deleting~971354646: device or resource busy
				E0629 10:06:08.128618   30980 nestedpendingoperations.go:262] Operation for "\"kubernetes.io/secret/7278f74d-56f8-11e7-82f5-020312bf3de8-default-token-98xbk\" (\"7278f74d-56f8-11e7-82f5-020312bf3de8\")" failed. No retries permitted until 2017-06-29 10:08:08.128595113 +0800 CST (durationBeforeRetry 2m0s). Error: UnmountVolume.TearDown failed for volume "kubernetes.io/secret/7278f74d-56f8-11e7-82f5-020312bf3de8-default-token-98xbk" (volume.spec.Name: "default-token-98xbk") pod "7278f74d-56f8-11e7-82f5-020312bf3de8" (UID: "7278f74d-56f8-11e7-82f5-020312bf3de8") with: rename /var/lib/kubelet/pods/7278f74d-56f8-11e7-82f5-020312bf3de8/volumes/kubernetes.io~secret/default-token-98xbk /var/lib/kubelet/pods/7278f74d-56f8-11e7-82f5-020312bf3de8/volumes/kubernetes.io~secret/wrapped_default-token-98xbk.deleting~206991485: device or resource busy

**Comment by copland** [comment]
@wangycc @stijndehaes Out of curiosity, do you know what the storage settings are for the docker daemon running on those nodes?

**Comment by xauthulei** [comment]
@copland ， I met the same error， could you check it 
 systemctl status kubelet  -l 
● kubelet.service - kubelet: The Kubernetes Node Agent
   Loaded: loaded (/etc/systemd/system/kubelet.service; enabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/kubelet.service.d
           └─10-kubeadm.conf, 90-local-extras.conf
   Active: active (running) since Mon 2017-11-06 03:13:48 EST; 1 day 18h ago
     Docs: http://kubernetes.io/docs/
 Main PID: 28578 (kubelet)
   Memory: 48.3M
   CGroup: /system.slice/kubelet.service
           └─28578 /usr/bin/kubelet --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf --pod-manifest-path=/etc/kubernetes/manifests --allow-privileged=true --network-plugin=cni --cni-conf-dir=/etc/cni/net.d --cni-bin-dir=/opt/cni/bin --cluster-dns=10.96.0.10 --cluster-domain=cluster.local --authorization-mode=Webhook --client-ca-file=/etc/kubernetes/pki/ca.crt --cadvisor-port=0 --cgroup-driver=systemd --rotate-certificates=true --cert-dir=/var/lib/kubelet/pki --fail-swap-on=false

Nov 07 03:14:31 huleib.eng.platformlab.ibm.com kubelet[28578]: E1107 03:14:31.808084   28578 helpers.go:468] PercpuUsage had 0 cpus, but the actual number is 1; ignoring extra CPUs
Nov 07 03:14:31 huleib.eng.platformlab.ibm.com kubelet[28578]: E1107 03:14:31.978519   28578 helpers.go:468] PercpuUsage had 0 cpus, but the actual number is 1; ignoring extra CPUs
Nov 07 03:14:39 huleib.eng.platformlab.ibm.com kubelet[28578]: E1107 03:14:39.062104   28578 helpers.go:468] PercpuUsage had 0 cpus, but the actual number is 1; ignoring extra CPUs
Nov 07 03:14:39 huleib.eng.platformlab.ibm.com kubelet[28578]: E1107 03:14:39.759644   28578 helpers.go:468] PercpuUsage had 0 cpus, but the actual number is 1; ignoring extra CPUs
Nov 07 03:14:44 huleib.eng.platformlab.ibm.com kubelet[28578]: E1107 03:14:44.909501   28578 helpers.go:468] PercpuUsage had 0 cpus, but the actual number is 1; ignoring extra CPUs
Nov 07 03:14:47 huleib.eng.platformlab.ibm.com kubelet[28578]: E1107 03:14:47.603325   28578 helpers.go:468] PercpuUsage had 0 cpus, but the actual number is 1; ignoring extra CPUs
Nov 07 03:16:15 huleib.eng.platformlab.ibm.com kubelet[28578]: E1107 03:16:15.249650   28578 kubelet.go:1628] Unable to mount volumes for pod "etcd-huleib.eng.platformlab.ibm.com_kube-system(489f230dc7238b6318db3760ff18730b)": timeout expired waiting for volumes to attach/mount for pod "kube-system"/"etcd-huleib.eng.platformlab.ibm.com". list of unattached/unmounted volumes=[etcd]; skipping pod
Nov 07 03:16:15 huleib.eng.platformlab.ibm.com kubelet[28578]: E1107 03:16:15.249690   28578 pod_workers.go:182] Error syncing pod 489f230dc7238b6318db3760ff18730b ("etcd-huleib.eng.platformlab.ibm.com_kube-system(489f230dc7238b6318db3760ff18730b)"), skipping: timeout expired waiting for volumes to attach/mount for pod "kube-system"/"etcd-huleib.eng.platformlab.ibm.com". list of unattached/unmounted volumes=[etcd]
Nov 07 03:16:15 huleib.eng.platformlab.ibm.com kubelet[28578]: E1107 03:16:15.284724   28578 kubelet.go:1628] Unable to mount volumes for pod "etcd-huleib.eng.platformlab.ibm.com_kube-system(7fd661a5cd3b7123b4dbc2142d0a8aae)": timeout expired waiting for volumes to attach/mount for pod "kube-system"/"etcd-huleib.eng.platformlab.ibm.com". list of unattached/unmounted volumes=[etcd]; skipping pod
Nov 07 03:16:15 huleib.eng.platformlab.ibm.com kubelet[28578]: E1107 03:16:15.284766   28578 pod_workers.go:182] Error syncing pod 7fd661a5cd3b7123b4dbc2142d0a8aae ("etcd-huleib.eng.platformlab.ibm.com_kube-system(7fd661a5cd3b7123b4dbc2142d0a8aae)"), skipping: timeout expired waiting for volumes to attach/mount for pod "kube-system"/"etcd-huleib.eng.platformlab.ibm.com". list of unattached/unmounted volumes=[etcd]

This is my docker daemon info ：
[root@huleib ~]# systemctl status docker  -l 
● docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; enabled; vendor preset: disabled)
  Drop-In: /usr/lib/systemd/system/docker.service.d
           └─flannel.conf, http-proxy.conf, https-proxy.conf
   Active: active (running) since Mon 2017-11-06 02:15:26 EST; 1 day 19h ago
     Docs: https://docs.docker.com
 Main PID: 23099 (dockerd)
   Memory: 356.7M
   CGroup: /system.slice/docker.service
           ├─ 6358 docker-containerd-shim a01af592d57c54b3884a7c572551552536f08a2a24ea3f787080837689bf24d2 /var/run/docker/libcontainerd/a01af592d57c54b3884a7c572551552536f08a2a24ea3f787080837689bf24d2 docker-runc
           ├─ 6495 docker-containerd-shim cf0b8a1c58328b77b37d79f88996c3bd102def63d0d7cf432cdad282372ecbae /var/run/docker/libcontainerd/cf0b8a1c58328b77b37d79f88996c3bd102def63d0d7cf432cdad282372ecbae docker-runc
           ├─23099 /usr/bin/dockerd
           ├─23103 docker-containerd -l unix:///var/run/docker/libcontainerd/docker-containerd.sock --metrics-interval=0 --start-timeout 2m --state-dir /var/run/docker/libcontainerd/containerd --shim docker-containerd-shim --runtime docker-runc --runtime-args --systemd-cgroup=true
           ├─28632 docker-containerd-shim 6ab8dd4556ad3204b3d311a16a5a9bd7371fc59781047f38b329a02ea8ecd687 /var/run/docker/libcontainerd/6ab8dd4556ad3204b3d311a16a5a9bd7371fc59781047f38b329a02ea8ecd687 docker-runc
           └─28660 docker-containerd-shim 8f49b5d00934fd538a38d8aeb36a624cc2f7d2b15f2d9e2a63f0999975f29685 /var/run/docker/libcontainerd/8f49b5d00934fd538a38d8aeb36a624cc2f7d2b15f2d9e2a63f0999975f29685 docker-runc

Nov 07 02:23:57 huleib.eng.platformlab.ibm.com dockerd[23099]: time="2017-11-07T02:23:57.815700819-05:00" level=warning msg="Unknown healthcheck type 'NONE' (expected 'CMD') in container d40960317c10449be9ccc3c8f1fc6c47b45979beb819915bc3da9d66f9aa659e"
Nov 07 02:29:06 huleib.eng.platformlab.ibm.com dockerd[23099]: time="2017-11-07T02:29:06.818583231-05:00" level=warning msg="Unknown healthcheck type 'NONE' (expected 'CMD') in container bb8c55222ee635ee1de4d2dae9b8e6ad875176232ca96349ae390898e058ff1f"
Nov 07 03:02:41 huleib.eng.platformlab.ibm.com dockerd[23099]: time="2017-11-07T03:02:41.705610445-05:00" level=warning msg="Unknown healthcheck type 'NONE' (expected 'CMD') in container 697f373e7d454dbe7a48b2e9795dfacbc072208702e5f44711110241a1e299a4"
Nov 07 03:02:43 huleib.eng.platformlab.ibm.com dockerd[23099]: time="2017-11-07T03:02:43.120071992-05:00" level=warning msg="Unknown healthcheck type 'NONE' (expected 'CMD') in container db9bd631e19c49a811fa2021d2a68c0a4c22e3f8bf3d2a5757942f94c5345c9d"
Nov 07 03:02:56 huleib.eng.platformlab.ibm.com dockerd[23099]: time="2017-11-07T03:02:56.824183311-05:00" level=warning msg="Unknown healthcheck type 'NONE' (expected 'CMD') in container a0b34ee26979d7e0c336279d6aa35a6c8ad77e0c6bd5ba0e6f89e5ca621b230f"
Nov 07 03:03:21 huleib.eng.platformlab.ibm.com dockerd[23099]: time="2017-11-07T03:03:21.814799526-05:00" level=warning msg="Unknown healthcheck type 'NONE' (expected 'CMD') in container 54cb516a6382fa51a03cc4f92f4e85d3ab7c300293ad5299f4977ef3863f1d67"
Nov 07 03:04:03 huleib.eng.platformlab.ibm.com dockerd[23099]: time="2017-11-07T03:04:03.818869768-05:00" level=warning msg="Unknown healthcheck type 'NONE' (expected 'CMD') in container df68791b3daefbd2ce4248766d3759fe0af7b1ad73905df0e70b9da19dcf844c"
Nov 07 03:05:35 huleib.eng.platformlab.ibm.com dockerd[23099]: time="2017-11-07T03:05:35.819464527-05:00" level=warning msg="Unknown healthcheck type 'NONE' (expected 'CMD') in container d75f297021308b7c150c12c3a2da16518fa6431d0985206025e50318259b9f77"
Nov 07 03:08:23 huleib.eng.platformlab.ibm.com dockerd[23099]: time="2017-11-07T03:08:23.816263868-05:00" level=warning msg="Unknown healthcheck type 'NONE' (expected 'CMD') in container 68c5200927de86cd934a04bba0bedfae3c42f7ec0c8fdcafe0ee9bcd6b026ad2"
Nov 07 03:13:31 huleib.eng.platformlab.ibm.com dockerd[23099]: time="2017-11-07T03:13:31.817896310-05:00" level=warning msg="Unknown healthcheck type 'NONE' (expected 'CMD') in container d2a589446819183ea8fd64b3fc8dff0cfb01a4d0acf8f2e86041ebedd0f18de3"
