### ISSUE TITLE
e2e flaky: [k8s.io] Pod Disks should be able to detach from a node which was deleted [Slow] [Disruptive] [Volume] 

### ISSUE THREAD

**Issue by dchen1107** [kubernetes/kubernetes#48008]
Since 2 days ago, the test is becoming more and more flaky, and one of the examples is:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-serial-release-1-7/81

```
[k8s.io] Pod Disks should be able to detach from a node which was deleted [Slow] [Disruptive] [Volume] 4m1s
go run hack/e2e.go -v -test --test_args='--ginkgo.focus=Pod\sDisks\sshould\sbe\sable\sto\sdetach\sfrom\sa\snode\swhich\swas\sdeleted\s\[Slow\]\s\[Disruptive\]\s\[Volume\]$'
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/pd.go:469
Expected
    <int>: 2
to equal
    <int>: 3
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/pd.go:433from junit_01.xml
```

**Comment by dchen1107** [comment]
@msau42 please triage this one. Currently I put it as the release blocker, and please feel free to remove that if you think it is not. Thanks!

**Comment by msau42** [comment]
The test deletes the node, and at the end, waits 5 minutes for the node to become ready, but it timed out.

cc @verult

**Comment by verult** [comment]
The test logic hasn't changed after I last modified it, so the test deletes the node through gcloud, and the instance should be restarted automatically by GCE because it's part of an instance template.

The likely possibility, as @msau42 pointed out, is that another change made node discovery take longer, so extending the timeout would be enough. The very unlikely possibility is there's a problem discovering brand new instances.
