### ISSUE TITLE
New images with Docker 1.12

### ISSUE THREAD

**Issue by mashayev** [kubernetes/kubernetes#48064]
Hi,

I'm creating my K8S cluster in CGE with `kube-up.sh`, I see that the default docker is 1.11. 
Is there any ETA when new images with Docker 1.12 will be released as default?

**Comment by dchen1107** [comment]
@mashayev In 1.6 release, sig-node team already announced that docker 1.12.6 is compatible and support with Kubernetes. Same with k8s 1.7 release.

**Comment by mashayev** [comment]
@dchen1107 When I'm creating new cluster with `kube-up.sh` in GCE it's being created with K8S version 1.6 and Docker version is 1.11

I was trying to create it with updated images `e2e-node-ubuntu-trusty-docker12-v2-image` but it failed.

Any idea how can I set K8S cluster with `kube-up.sh` script to be with update docker version?

**Comment by mashayev** [comment]
I'm trying to create it with:
`NUM_NODES=1 KUBE_OS_DISTRIBUTION=container-linux KUBE_GCI_VERSION=e2e-node-ubuntu-trusty-docker12-v2-image KUBE_GCE_MASTER_PROJECT=kubernetes-node-e2e-images cluster/kube-up.sh`

**Comment by dchen1107** [comment]
In v1.6.4, we support Ubuntu 16.04. Please trying something like this:

KUBE_GCE_NODE_IMAGE=ubuntu-gke-1604-xenial-v20170420-1 KUBE_NODE_OS_DISTRIBUTION=ubuntu KUBE_GCE_NODE_PROJECT=ubuntu-os-gke-cloud cluster/kube-up.sh

cc/ @yguo0905 anything I missed above?

Ubuntu Trusty support was dropped from GCE K8S since 1.5 release. sig-node is still carrying on the node e2e tests for the image qualification for the open source community. You can still bring up Ubuntu Trusty cluster on GCE, but you need to update the kube-up related scripts.

**Comment by mashayev** [comment]
@dchen1107 Hi thanks for the help. Is there any way to consult with someone about how to do it properly? There are bunch of things I would like to change and fit to my needs. creating and destroying the K8S cluster each time is kind of headache.

**Comment by yguo0905** [comment]
@mashayev, the envs provided by @dchen1107 should allow you to create a cluster with Ubuntu node image and docker 1.12.6. Does it work?

**Comment by mashayev** [comment]
@yguo0905 Yes it works.
I would like to make more changes, But I don't find any good documentation for how to do it properly with `kube-up.sh`. Is there any documentation?
