### ISSUE TITLE
Add possibility to change fluentd requests on master and nodes independently

### ISSUE THREAD

**Issue by piosz** [kubernetes/kubernetes#48071]
Master is fully packed and we need more space there. We want to decrease fluentd cpu request from 100m to 90m. Currently it's not possible without changing it on nodes also and we don't want to decrease it there.

Follow up #47906 #48066

**Comment by piosz** [comment]
cc @gmarek @mwielgus @mikedanese @fgrzadkowski

**Comment by crassirostris** [comment]
I don't see the difference between fluentd on master and fluentd on the node, from their point of view the environment is the same. I think we have more benefits from keeping them consistent that from slitting, especially since the most important problem now is a memory limit and fluentd inability to gracefully degrade, not lack of resources per se.

**Comment by fgrzadkowski** [comment]
The difference is significant - in GKE we cannot easily increase resource in user node, while we can on master. That's why we should also configure them separately. Keeping them consistent is of course beneficial, but not at the cost of degraded performance. We've seen in the past CPU being extensively used; it's just that problems with memory are more explicit (it just dies).

**Comment by crassirostris** [comment]
OK, I agree that it would be nice to have a way to change the resources independently without many manual steps, when you deploying fluentd in your cluster

However, I don't agree that it's a P0 and that we can't change 100m to 90m in the currently used configuration, both on the nodes and on the master, even with load tests passing. It's not a bottleneck, so it's just occupying the resources at the moment. I would say the only reason there's number 100m is because there're no estimates of what this number should be, not because it's a reasonable number. Here's the PR with the initial introduction of the resource requests on fluentd pod: https://github.com/kubernetes/kubernetes/pull/8657, number 100m comes from a default number and the only validation of this number is passing tests.

**Comment by fgrzadkowski** [comment]
The reason it's P0 is because we've reverted PR changing resources to 90m cores. The reasons we've reverted that PR are the following:
* I don't think that tests we have are good enough to say with 100% confidence that 90m is ok
* Increasing it back to 100m is almost impossible (at least now)
* if/once we will solve the problem with memory it's quite possible that cpu might be the next bottleneck
* 100KB that we test against is not very high and we do have customers expecting more

How much work is to split configuration? Is it 1 day, 1 week, 1 month? This is an important argument in this discussion.

**Comment by crassirostris** [comment]
@fgrzadkowski 1 day

**Comment by fgrzadkowski** [comment]
Than I'd suggest to just implement this. It will give us flexibility on the master, while being extra-safe on the user nodes. WDYT?

**Comment by crassirostris** [comment]
@fgrzadkowski Sure, agree

**Comment by crassirostris** [comment]
@fgrzadkowski OK, after carefully thinking about it, I found some problems that makes this effort more complex:

* As a result of https://github.com/kubernetes/kubernetes/issues/44445, https://github.com/kubernetes/kubernetes/pull/45715 and https://github.com/kubernetes/kubernetes/pull/48182 fluentd cannot be repelled by the master taint
* There's nothing to use to schedule a pod to master only, like `is_master` label or smth like it

/cc @gmarek

**Comment by gmarek** [comment]
Taint logic would not allow you to achieve this, as we can't say "tolerate everything except 'isMaster' taint (or sth)". Additionally I don't thing there's an agreement on whether we should taint the master.

**Comment by crassirostris** [comment]
@gmarek Yes, I remember there was a taint there and now I can't see it (at least in gce deployment)

**Comment by fgrzadkowski** [comment]
How about just using hostname and node selector?

--
Filip

**Comment by gmarek** [comment]
I'm not sure we can depend on hostname to identify the master.

**Comment by crassirostris** [comment]
Problem is, for example in GCE deployment, there's no difference in labels on master and on the nodes. If we add a special label to mark the masters, then we can use nodeAffinity.

**Comment by fgrzadkowski** [comment]
@gmarek why not? For GCE we explicitly define the name in our configuration.

**Comment by fgrzadkowski** [comment]
Just to be clear - I know it'd be a hack, but I think it'd work :)

**Comment by gmarek** [comment]
Only for clusters created by kube-up and/or using the same naming scheme.

**Comment by fgrzadkowski** [comment]
Correct, but I think these are the clusters we need to fix, right?

--
Filip

**Comment by gmarek** [comment]
For tests yes, this is a fine hack. The problem is that it won't work on production setups on GCE. Maybe that's fine, I don't know.

**Comment by fgrzadkowski** [comment]
Why it wouldn't work in production on GCE? I think we are still deploying
on GCE using kube-up.sh, right?

--
Filip

**Comment by crassirostris** [comment]
@fgrzadkowski Well, there's kopf, there're clusters deployed manually

What about adding a `kubernetes.io/ismaster=true` label to the master and `kubernetes.io/ismaster=false` to the nodes together with the fluentd change? It doesn't seem breaking something, 'tis just a label

**Comment by fgrzadkowski** [comment]
That's true, but we don't control how they manage/deploy add-ons and we
don't plan to change resources there.

--
Filip
