### ISSUE TITLE
how to get service token in kuberenetes controller manager  to talk to kubernetes API?

### ISSUE THREAD

**Issue by selvakumarnms** [kubernetes/kubernetes#48250]
/kind feature
How to get the service token from kubernetes controller manager pod to talk to kuber API?

**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by castrojo** [comment]
Please re-post your question to [Stack Overflow](http://stackoverflow.com/questions/tagged/kubernetes).

Thanks for taking the time to report an issue to us. In the past this tracker has housed both bug reports and user support requests, we are now only using this tracker for software defects and feature tracking.   

We are trying to consolidate the channels to which questions for help/support
are posted so that we can improve our efficiency in responding to requests,
and to make it easier for you to find answers to frequently asked questions and
how to address common use cases.

The Kubernetes team scans Stack Overflow on a regular basis, and will try to
ensure your questions don't go unanswered.

If you're looking for more long-form discussion on best practices, we encourage you to check out the [Kubernetes user list](https://groups.google.com/forum/#!forum/kubernetes-users). 

You can also find more information here:

  * [User Documentation](http://kubernetes.io/docs/)
  * [Troubleshooting Guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/)

Again, thanks for using Kubernetes. If you feel this issue has been closed in error then please reopen it and we can have another look. 

The Kubernetes Team
