### ISSUE TITLE
Hostname shouldn't be set to the pod name

### ISSUE THREAD

**Issue by bparees** [kubernetes/kubernetes#4825]
Kubernetes is setting the hostname of the container in docker here:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubelet/kubelet.go#L673

however we've recently discovered there appears to be a limit of 64 characters on at least some systems which results in the sethostname call failing.

Is this explicit setting of the hostname to the podname strictly necessary?  if so, we need to impose some additional checking in this logic.

@smarterclayton we're hitting this in OpenShift now that we're prepending the buildname on podnames.

**Comment by smarterclayton** [comment]
It's a downward api, I think we would keep it, but we need to probably safe trim it.  I think this might be something docker should handle.

**Comment by thockin** [comment]
I agree Docker should handle it.  Given that they don't, we should.  Belts
and suspenders.  Well this puts to rest the idea that hostname is a
reliable way to pass down the name or UID

**Comment by smarterclayton** [comment]
What's worse is that it apparently is only broken on some systems.  Ben, can we be sure to file OS bugs if that's any of the red hat distros?

**Comment by bgrant0607** [comment]
We shouldn't pass the pod uid as the hostname, as per #3949. We could generate a shorter string.

**Comment by thockin** [comment]
I would suggest a different ID, but still a UID (I think we called it VUID
internally).  But we don't really have a VUID yet, and I don't know we want
one.  Just random?  A hash of the pod name?

**Comment by bgrant0607** [comment]
Just random SGTM. Can be set in the defaulting pass.

**Comment by thockin** [comment]
Oh I was not suggesting to store it in the API, just to hash the pod name
in kubelet and use that as hostname to docker.  We can add VUID later when
we really need it.

**Comment by bgrant0607** [comment]
I'm concerned about hashing on the pod name, since the pod name would change in the case of migration.

**Comment by thockin** [comment]
I assumed that the name would stick but the UID would change.  I don't want
to go down a hypothetical rabbithole on migration right now, so I'll roll
with whatever - I think the goals are pretty clear.

**Comment by bgrant0607** [comment]
In order to implement live migration, a replacement pod must be created while the original still exists. Name will change.

**Comment by thockin** [comment]
Again, I don't want to go to far hypothetically.  I'm concerned that such
an implementation makes Name a nearly worthless field.

**Comment by bgrant0607** [comment]
The object name is a management handle and ensures idempotence and uniqueness.

The hostname is used for network identity.

Conflating object name and hostname goes against our entire design, with decoupled services and replication controllers, ephemeral pods, etc. Setting hostname using podID was a mistake, and it should be fixed.

**Comment by smarterclayton** [comment]
The hostname identifies a unique instance of a machine in external systems.  I assume from what you're saying is not against a hostname being stable to network identity or presence on a host?  It seems reasonable that the hostname value should be stable on a given node for a pod as long as it is not replaced / moved / gets a different ip?

**Comment by bgrant0607** [comment]
I agree hostname should be stable. It just shouldn't be tied to the object's identity, since we know we'll want to be able to reuse the same hostname across objects in the future.

**Comment by bgrant0607** [comment]
Proposal: set hostname to hash of uid (and name, creationTimestamp, whatever), and record it in a pod spec field. It should not be updatable.

**Comment by bparees** [comment]
was https://github.com/GoogleCloudPlatform/kubernetes/pull/5830 the final solution for this issue?

seems like the solution in that PR risks collisions.

**Comment by bgrant0607** [comment]
Not final, no. We need to change how the hostname is set.

**Comment by thockin** [comment]
What's the risk of collisions?  DNS lookups of colliding services is all I
can think of, and not much we can do to prevent that in general.

**Comment by brendandburns** [comment]
We need a way for a Pod to look up itself.  We could automatically mount in a special file with the ID of the pod (probably not a bad idea, long term)

However, this is definitely _not_ a v1.0 blocker.  Punting to P2 and out of the v1 milestone.

**Comment by bgrant0607** [comment]
Hostname is totally the wrong way for pods to look themselves up, and it's not even sufficient -- namespace is required, for instance. That problem is being solved by the downward API -- see PR #6739 for the first cut.

**Comment by thockin** [comment]
What does "look itself up" mean?  We could make reverse DNS work, but I am
unconvinced it is what people actually want.

**Comment by pmorie** [comment]
@mfojtik I believe you have a case like this.  Testify?

**Comment by bgrant0607** [comment]
The pod name can be passed via environment variables:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/downward_api.md

**Comment by pnovotnak** [comment]
Need to be able to set hostname to do some things, eg; [rabbitmq persistence](https://github.com/docker-library/rabbitmq/issues/6). Is it still possible to do this?

**Comment by thockin** [comment]
There is no way to set this as of kubernetes v1.0. I forget what the
conclusion was last time we discussed this, but it seems like a good
candidate for v1.1 to me.

**Comment by ReSearchITEng** [comment]
Hi thockin, bgrant0607,
As more legacy apps are migrating, this becomes one of the hot topics, as it's blocking many apps to migrate to docker containers in Kube.
I would say that this sounds like a "quick win", as it sounds as a low complexity coding to expose the container hostname, while unlocking many legacy apps to migrate to containers.
It seems posts keep on coming on the web, and more and more people are interested: https://stackoverflow.com/questions/31552455/setting-the-hostname-for-a-container-running-in-kubernetes

We would appreciate if this functionality is exposed in the next milestone.

**Comment by thockin** [comment]
@ReSearchITEng Is this something you want to implement or something you want us to do?  I can not say for sure what the prio of this is, with respect to everything else.

There seem to be two issues here, both reasonably approachable as starter projects:

1) Add API + plumbing to set hostname for (all containers in) a pod

2) Change the default hostname value to something less obvious.

**Comment by lvlv** [comment]
Hi Tim,

Does this mean we will have some other string as hostname? Any candidates?
Thanks!
For the API to set hostname, is it possible to add the functionality to set
it same as the node hostname? This would be helpful if we want to deploy
pods with host network.

**Comment by thockin** [comment]
My instinct says that setting hostname to node's hostname is the wrong
tack.  It leads to a coupling that I don't think we want.  In general
hostname has little practical meaning.

**Comment by lvlv** [comment]
I agree setting hostname same as node's hostname is somehow a hack, while
we can think it another way: for pods using host network, is it possible
for them to share the UTS namespace with node? This feature is already
supported in docker.

For the other question, any candidate (other than pod name) are we
considering for the hostname? Pod name is already a random string, changing
that to a more random one couldn't lead to any benefit from my limited
knowledge, why bother? :-)

The overall background is: I'm deploying HDFS/HBase on kubernetes, they
heavily depend on the hostname for their clients to find the servers. Let
me know if you want to know more about this.

**Comment by thockin** [comment]
I would like to hear more about how they use hostname.

**Comment by lvlv** [comment]
Let's talk about HBase as an example, we can see hostname almost everywhere.
1. Master uses ZooKeeper to run master election, the winner puts its
hostname:port in ZooKeeper.
2. RegionServers will register themselves to the winning Master through its
hostname registered in ZooKeeper.
3. We have a RegionServer with meta table/region (which stores Region ->
RegionServer map), it stores its hostname:port in ZooKeeper.
4. When a client starts a request to HBase, it gets the hostname of the
RegionServer with meta table from ZooKeeper, scan the meta table, and find
out the hostname of the RegionServer it interests, and finally talks to the
RegionServer through hostname.

**Comment by thockin** [comment]
In all these cases, is it hostname because the code is hardcoded to store
the result of a call to uname() (or the equivalent in whatever languages),
or is that a parameter that can be injected?  How do the things that write
their "hostname" learn their hostname?

If they instead wrote their IP address, would things break?

Does port need to be well-known or can it be random?

Tim

**Comment by lvlv** [comment]
Yes, the code is hardcoded to store the hostname in ZooKeeper, currently I
haven't find any parameter to inject.

It is okay to write their IP address, but it will need a lot of code
changes in many components. I thought it was easy ... but it is not when I
have too many components to migrate.

The port is specified in its config, it could be changed, it will also
write its port into ZooKeeper. Currently the port can't be random.

**Comment by thockin** [comment]
How does the master find its own hostname?

To be clear: I am not advocating changing the underlying system, just
understanding the edges better.

You said "the winner puts its hostname:port in ZooKeeper"  How does it know
which port - that's part of the config for the software?

**Comment by lvlv** [comment]
Happy to re-visit the logic, it's great k8s could consider supporting this
natively.

The hostname is by default
InetAddress.getLocalHost().getCanonicalHostName(), but it could also find
hostname through reverse DNS.
The port is part of the config.

**Comment by bgrant0607** [comment]
So the hostname needs to be resolvable via DNS. Right now, you'd need to create a Service for each instance and populate the hostname with the service name.

The Zookeeper case was also discussed on #260.

**Comment by lvlv** [comment]
Yes the hostnames needs to be resolvable via DNS. Currently I hack into
kube2sky and add sth like podname.namespacename.pod.k8s.local

By "create a Service for each instance", do you mean create a service for
each replica in RC? For HBase case, it is impossible as we may have a lot
of RegionServer pods, we don't even know how many replicas we need when we
write the replication controller config.
Furthermore, even with "a service for each instance", we still need to
modify the hostname of different pods from same replication controller to
different service IPs, which is also far from ideal.

ZooKeeper case is somehow different, it has to specify the IP/hostname in
the config before the pod is created. I've other workarounds but it is out
of scope of this thread.

**Comment by ghodss** [comment]
We also have code internally which relies on discovering the hostname of the server through a shell out to `hostname`, then puts that information in zookeeper and uses it to actually send HTTP requests to other hosts that have also registered (for health checking and quorum purposes). I like @lvlv's solution: if networking of the pod is host networking, automatically set the hostname of the pod to be the same as the hostname of the host. Would that approach be acceptable?

**Comment by bgrant0607** [comment]
How would the hostname of the host be determined?

**Comment by thockin** [comment]
We have thus far avoided pod DNS.  I'm less against it than I once was, though there are some issues to overcome to make cases of "I queried my own hostname, told someone about it, and expected them to find me".

1. Docker only has a hostname field, not a dnsdomainname field, so we'd have to at LEAST set the hostname to `$pod.$ns.pod` and home that all clients have .cluster.local in their search

2. The original point of this bug was that hostname should be limited to 64 characters so #1 is already problematic.  On top of that we define pod names to be a DNS_SUBDOMAIN, not a DNS_LABEL.

We could do something like hash(pod.name, pod.namespace) into a shortish name (less than 60 characters) and set `$hash.pod` as the hostname.  We can serve DNS for that `$hash.pod.cluster.local`, but (as with all hashes) we run the risk of collision.  We could use the pod UID instead, we already assume that is unique enough.   `d6f591f0-3992-11e5-b77c-42010af02851.pod.svc.cluster.local`.  That sort of sucks for migration, as mentioned up-bug, but we don't have migration.  If, as Brian points out, we don't want to actually expose the pod UID to apps, lest they thing it is meaningful, we could do as Brian also suggests - hash enough unique bits to produce a new form of UID, and set hostname to that.

Options I see:

1) Just generate a new UUID and save it on the pod object.  I propose `VUID` as a name.  Set pod hostname to `$VUID.pod`.  If/when live migration happens we can link pods by that.  Do not allow updates to VUID.  Do not allow users to set VUID (until we have migration, at which point we can formalize that maybe as a subresource).  Serve DNS for $vuid.pod.cluster.local.  TBD whether that includes SRV and PTR records.

2) Hash pod name, namespace, and ctime and save it on the pod object.  I propose `VUID` for the same reasons as above.  DNS as above.

3) Same as #1 or #2 but save it in annotations.

I like #1.  Net result, given a pod's hostname, you CAN look it up, but you can't know the name a priori.

Now, is SRV and PTR valuable for this?  @ArtfulCoder FYI

**Comment by lvlv** [comment]
1. Docker do have a Domainname in its create container api:
https://docs.docker.com/reference/api/docker_remote_api_v1.20/#create-a-container

2. If VUID is only introduced for the 64 byte limit, I'm a little
struggling with it. pod name + namespace is already something unique, at
least for pods whose "podname.namespace.pod" are shorter than 63, using
that directly seems quite straight forward, it will be much user-friendly.

**Comment by lvlv** [comment]
Instead of getting hostname from somewhere, I'm wondering if we can use
docker run flag "--uts=host" to share the same uts namespace with host.

**Comment by thockin** [comment]
I don't understand the goal of using uts from the host.  What are you
trying to achieve with that?

As for hostname being pod name, I think there is value in obfuscation here
- DNS to pods is generally not what people should be doing.

**Comment by smarterclayton** [comment]
On Aug 15, 2015, at 9:48 PM, Tim Hockin <notifications@github.com> wrote:

We have thus far avoided pod DNS. I'm less against it than I once was,
though there are some issues to overcome to make cases of "I queried my own
hostname, told someone about it, and expected them to find me".

   1.

   Docker only has a hostname field, not a dnsdomainname field, so we'd
   have to at LEAST set the hostname to $pod.$ns.pod and home that all
   clients have .cluster.local in their search
   2.

   The original point of this bug was that hostname should be limited to 64
   characters so #1 <https://github.com/kubernetes/kubernetes/issues/1> is
   already problematic. On top of that we define pod names to be a
   DNS_SUBDOMAIN, not a DNS_LABEL.

We could do something like hash(pod.name, pod.namespace) into a shortish
name (less than 60 characters) and set $hash.pod as the hostname. We can
serve DNS for that $hash.pod.cluster.local, but (as with all hashes) we run
the risk of collision. We could use the pod UID instead, we already assume
that is unique enough.
d6f591f0-3992-11e5-b77c-42010af02851.pod.svc.cluster.local. That sort of
sucks for migration, as mentioned up-bug, but we don't have migration. If,
as Brian points out, we don't want to actually expose the pod UID to apps,
lest they thing it is meaningful, we could do as Brian also suggests - hash
enough unique bits to produce a new form of UID, and set hostname to that.

Options I see:

1) Just generate a new UUID and save it on the pod object. I propose VUID
as a name. Set pod hostname to $VUID.pod. If/when live migration happens we
can link pods by that. Do not allow updates to VUID. Do not allow users to
set VUID (until we have migration, at which point we can formalize that
maybe as a subresource). Serve DNS for $vuid.pod.cluster.local. TBD whether
that includes SRV and PTR records.


For all the cases where you get this, don't you really want to get it from
a service?  Why not make endpoints semi stable with a nominal service and
attach the identity both in the name given to the recursive SRV record and
provide into the pod?   Then you have stable identity and a DNS address.
All VUID is a reusable nominal pod identity.  Why have two concepts?

2) Hash pod name, namespace, and ctime and save it on the pod object. I
propose VUID for the same reasons as above. DNS as above.

3) Same as #1 <https://github.com/kubernetes/kubernetes/issues/1> or #2
<https://github.com/kubernetes/kubernetes/issues/2> but save it in
annotations.

I like #1 <https://github.com/kubernetes/kubernetes/issues/1>. Net result,
given a pod's hostname, you CAN look it up, but you can't know the name a
priori.

Now, is SRV and PTR valuable for this? @ArtfulCoder
<https://github.com/ArtfulCoder> FYI

—
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/4825#issuecomment-131474579>
.

**Comment by lvlv** [comment]
It seems we have multiple threads in this issue :-(

[QUOTE] I don't understand the goal of using uts from the host.  What are you
trying to achieve with that? [/QUOTE]

My proposal was: For pods using host network, by default share the UTS namespace with node. Or at least provide this as an option.
Reason: For pods binding their services on host network, it looks natural for them to bind on "host hostname":port instead of "sth random":port.

[QUOTE] As for hostname being pod name, I think there is value in obfuscation here
- DNS to pods is generally not what people should be doing. [/QUOTE]

[QUOTE] For all the cases where you get this, don't you really want to get it from
a service?  Why not make endpoints semi stable with a nominal service and
attach the identity both in the name given to the recursive SRV record and
provide into the pod?   Then you have stable identity and a DNS address.
All VUID is a reusable nominal pod identity.  Why have two concepts? [/QUOTE]

It seems necessary to clarify how important "DNS to POD" is during the migration of existing applications.
In many applications, replicas use something like ZooKeeper to register their "hostname:port" and expose ZK path to their users. Without DNS to POD, we have to modify all the register logic, and convert all of them into IP.
Here are some examples: HBase register masters to ZK, HBase register regionservers to meta table, HDFS register datanodes to namenodes, Spark register executors to Spark context, etc ... All of them by default use hostname:port as their identity.

[QUOTE] hostname should be limited to 64 characters [/QUOTE]
[QUOTE] Options #1 #2 #3 [/QUOTE]

My proposal #4: By default, use `${podname}.${namespacename}.pod` as DNS to POD, and ensure `hostname -f` equals to that. In some cases, where `${podname}.${namespacename}.pod` is longer than 63 characters, use podname-prefix+hash or something like VUID.pod.
Reason: we are introducing this for "DNS to POD" use cases, it is more readable and user friendly to see 'podname.namespace.pod' in ZK/Namenode/Spark, especially when debugging, it cost an extra lookup for developer to understand 'd6f591f0-3992-11e5-b77c-42010af02851.pod'.

**Comment by thockin** [comment]
> For all the cases where you get this, don't you really want to get it from
> a service? Why not make endpoints semi stable with a nominal service and
> attach the identity both in the name given to the recursive SRV record and
> provide into the pod? Then you have stable identity and a DNS address.
> All VUID is a reusable nominal pod identity. Why have two concepts?

We have, thus far, not settled on an implementation for nominal
services, or really even proposed anything concrete that "feels
right".  The loose coupling between Services and Pods means that a Pod
generally doesn't know anything about Services it serves under.  I am
loathe to give that up.  Brian made good arguments for why the
nominality should not be part of the RC.  That leaves Pod as a
nominalizable (I just made that up, look for it in the 2016 scrabble
dictionary) thing.

**Comment by thockin** [comment]
@lvlv


> It seems we have multiple threads in this issue :-(

indeed

> [QUOTE] I don't understand the goal of using uts from the host. What are you
> trying to achieve with that? [/QUOTE]
>
> My proposal was: For pods using host network, by default share the UTS namespace with node. Or at least provide this as an option.
> Reason: For pods binding their services on host network, it looks natural for them to bind on "host hostname":port instead of "sth random":port.

yeah, for host network, host UTS sounds right, but I have not thought
deeply about that.  @vmarmol

> [QUOTE] As for hostname being pod name, I think there is value in obfuscation here

> It seems necessary to clarify how important "DNS to POD" is during the migration of existing applications.
> In many applications, replicas use something like ZooKeeper to register their "hostname:port" and expose ZK path to their users. Without DNS to POD, we have to modify all the register logic, and convert all of them into IP.
> Here are some examples: HBase register masters to ZK, HBase register regionservers to meta table, HDFS register datanodes to namenodes, Spark register executors to Spark context, etc ... All of them by default use hostname:port as their identity.

What @smarterclayton was proposing (I think) is the idea that a pod in
a "nominal service" can get a name and/or IP that it can publish and
that others can use to reach that pod.  Same as a hostname and
DNS-to-pods.  Th emain difference is that in a nominal service the
pool of names is approximately fixed, whereas pod names are not.

So let me propose a scenario and you tell me how important it is.

You spin up a set of N pods.  They each publish their hostname to each
other, and verify that they can all talk to the others.  Now one of
those pods is deleted and comes up on a different machine.  It has a
different IP and a different hostname.

How bad is it that the IP and hostname changed?  The truth is that the
constituents of that set of pods DID change.  Is it required that the
pod which is killed and restarted elsewhere comes back with the same
DNS name?  How about the same IP?

> [QUOTE] hostname should be limited to 64 characters [/QUOTE]

> My proposal #4: By default, use ${podname}.${namespacename}.pod as DNS to POD, and ensure hostname -f equals to that. In some cases, where ${podname}.${namespacename}.pod is longer than 63 characters, use podname-prefix+hash or something like VUID.pod.
> Reason: we are introducing this for "DNS to POD" use cases, it is more readable and user friendly to see 'podname.namespace.pod' in ZK/Namenode/Spark, especially when debugging, it cost an extra lookup for developer to understand 'd6f591f0-3992-11e5-b77c-42010af02851.pod'.

Counter-arguments:

1) If the name is USUALLY the pod and namespace, people will come to
rely on that.  When it turns out not to be true they will be broken.
Better to break the association entirely.  This is the same reason
that replicas in an RC have random suffixes rather than sequential
numbers.  Humans are pattern-matching machines.

2) Pod names can have dots in them and I don't want to deal with the
DNS ramifications of that.

Lastly, I stand corrected - the Docker API does have a domainname
param, just not the CLI.  That opens other possible schemes for
structure, but I don't think we want to go there (e.g.
`hash(pod.name).hash(pod.namespace).pod.cluster.local` )

**Comment by lvlv** [comment]
@thockin 

[QUOTE] What @smarterclayton was proposing (I think) is the idea that a pod in
a "nominal service" can get a name and/or IP that it can publish and
that others can use to reach that pod. [/QUOTE]

I totally agree nominal service is useful, while I believe "DNS to POD" is also useful. They stand for different discovery patterns.
For nominal service scenario, pods are PASSIVELY waiting to get connected, so we provide approximately fixed names, and pods could be reached through fixed names even when they got recreated.
While "DNS to POD" stands for a different pattern: pods ACTIVELY report themselves (by hostname) to some pre-defined shared discovery service, and clients discover them through that. We have to give pods hostnames that are reachable by other clients. (Unless we can set pod hostname to the name assigned by "nominal service", if it is possible.)

[QUOTE] Counter-arguments: [/QUOTE]

1) I agree we should entirely break this, how about combine some chars from pod name and always add some suffixes, like substr(${podname}, 0, 32)-${vuid or random suffixes}? Just like replicas names in RC, we keep rc name in front and add some random suffixes.
2) I'd prefer entirely invalidate dots from pod names, does anyone really using dot in pod name? At least we can directly remove dots from pod.name as we are already converting it.

Lastly:
https://github.com/kubernetes/kubernetes/blob/master/Godeps/_workspace/src/github.com/fsouza/go-dockerclient/container.go#L180

**Comment by smarterclayton** [comment]
> Unless we can set pod hostname to the name assigned by "nominal service",
if it is possible

is what I was implying.

Nominalizing pods in advance of services does seem risky.  I would prefer
not to make pods nominizable and try to solve services first, because
everyone needs nominal services and if you create nominal pods without that
design... well...

On Mon, Aug 17, 2015 at 2:25 AM, Lv Lv <notifications@github.com> wrote:

> @thockin <https://github.com/thockin>
>
> [QUOTE] What @smarterclayton <https://github.com/smarterclayton> was
> proposing (I think) is the idea that a pod in
> a "nominal service" can get a name and/or IP that it can publish and
> that others can use to reach that pod. [/QUOTE]
>
> I totally agree nominal service is useful, while I believe "DNS to POD" is
> also useful. They stand for different discovery patterns.
> For nominal service scenario, pods are PASSIVELY waiting to get connected,
> so we provide approximately fixed names, and pods could be reached through
> fixed names even when they got recreated.
> While "DNS to POD" stands for a different pattern: pods ACTIVELY report
> themselves (by hostname) to some pre-defined shared discovery service, and
> clients discover them through that. We have to give pods hostnames that are
> reachable by other clients. (Unless we can set pod hostname to the name
> assigned by "nominal service", if it is possible.)
>
> [QUOTE] Counter-arguments: [/QUOTE]
>
> 1) I agree we should entirely break this, how about combine some chars
> from pod name and always add some suffixes, like substr(${podname}, 0,
> 32)-${vuid or random suffixes}? Just like replicas names in RC, we keep rc
> name in front and add some random suffixes.
> 2) I'd prefer entirely invalidate dots from pod names, does anyone really
> using dot in pod name? At least we can directly remove dots from pod.name
> as we are already converting it.
>
> Lastly:
>
> https://github.com/kubernetes/kubernetes/blob/master/Godeps/_workspace/src/github.com/fsouza/go-dockerclient/container.go#L180
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kubernetes/kubernetes/issues/4825#issuecomment-131693308>
> .
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by ghodss** [comment]
> I don't understand the goal of using uts from the host.  What are you
> trying to achieve with that?

@thockin Our use case for is that we have many services that depend on being able to query for the hostname of the host that the service is running on. The use cases for it are extremely varied - in one case, it's a worker service operating on a storage node which has identity and the service needs to be aware of which storage node it's operating on. In another case, the service dynamically stands up a servlet on a port and asks another service to post back some information to it.

We are working on going through and rewriting most of these services to not require hostname, but in the mean time the simple ability to enable a pod to access the uts of the host (when host networking is turned on) would allow us to migrate many more of our services over immediately to Docker and Kubernetes and deprecate our current deployment infrastructure. Otherwise we are blocked on these services getting updated (and sometimes substantially rewritten), which will significantly delay the deployment of kube.

**Comment by bgrant0607** [comment]
Quick comment re. "For pods using host network, by default share the UTS namespace with node."

That makes sense to me.

**Comment by ghodss** [comment]
That would solve all our issues.

**Comment by bgrant0607** [comment]
Quick comment re. "Unless we can set pod hostname to the name assigned by "nominal service", if it is possible."

Nominal services should set the hostname.

More general design of nominal services should happen on #260.

**Comment by bgrant0607** [comment]
Hostname should not be set to nor derived from pod name.

**Comment by bgrant0607** [comment]
How about we set the hostname to some name derived from IP address by default (except for the other cases discussed, such as host network)?

**Comment by bgrant0607** [comment]
cc @senorflor

**Comment by thockin** [comment]
Regarding host networking:  I forked #12893 - let's not mention it in this thread again :)

**Comment by thockin** [comment]
@bgrant0607 

> Hostname should not be set to nor derived from pod name.
> How about we set the hostname to some name derived from IP address by default (except for the other cases discussed, such as host network)?

I do not buy your first statement as absolute, but I'm not actually arguing for that.  I'm advocating generating a new UUID or something similarly opaque and just setting hostname to that.  We will need to debate what domainname should be.  I'm thinking `pod.cluster.local` in case we ever do want to do DNS.

I don't like deriving it from IP precisely because of your "except for ..." clause.

I'm not as against DNS for pods as I once was.  I'll go catch up on the nominal services issue, maybe a mental model will finally emerge for me.  so far it hasn't.  NB: DNS for pods makes it difficult or impossible to ever let people assign their own hostname.  Probably OK, but worth mentioning.  I thought we had an open issue on that but I can't find it.

**Comment by bgrant0607** [comment]
What is the point of setting the hostname to something random but unresolvable? There are other sources of random bits.

The need for "except for" clause is unaffected by your proposal.

Using the pod IP address would be more friendly to humans, would match the lifetime of the corresponding pod, without being permanently bound to the specific pod resource, and would naturally move if/when we could migrate the IP. I'd be ok with allowing users to set the hostname but defaulting it to a name derived from the IP, though we'd need to think about possible attack surfaces. 

I am firmly against both publishing DNS names derived from pod names and deriving the hostname from the pod name, at least automatically. However, if users exploited the the ability to set the hostname to assign the pod name as the hostname despite our admonitions, there's not much we could do about that, other than take away that feature entirely.

**Comment by thockin** [comment]
I'm going to stop the discussion here, even though I have more to say,
until we figure out nominal services.  The need to re-use a given hostname
within a set makes my proposal largely untenable anyway.

**Comment by ReSearchITEng** [comment]
Hi Tim,
I also think nominal services would solve quite some challenges.
Till then, we can work-around few issues only by opening the posibility to
set the hostname from the specs. This might be both easier and give some
breathing time till final solution.

What do you think?

**Comment by thockin** [comment]
I'm very wary of allowing users to set hostname if we think that might not
be a user-configurable param later.  Also, the fact that hostname is not a
"reachable" name (no DNS) seems to make it less useful.

I'd rather hold off on this until we get a bit more clue on nominal

**Comment by soupdiver** [comment]
@thockin I want to give an example where the hostname is important.

I have **sendmail** installed in a container to forward emails to a relay mail server. sendmail takes something between 30 and 60 seconds to process my mail because it expects the hostname to be a FQDN. I tested with a container where I added **-h foo.localdomain** and processing was done immediately.

So it would be cool to have the possibility to set the hostname

**Comment by thockin** [comment]
You mean that sendmail expects `hostname` to return "foo.bar.com" or that
it expects to be able to DNS-lookup it's own IP address?

**Comment by soupdiver** [comment]
It somehow expects a hostname with a domain. So **foo** would be problematic but **foo.localdomain** would be good

**Comment by Hokutosei** [comment]
+1 to be able to set `hostname`
as a mongodb user, this really is a problem to me now. my use case is replicaSets are set to services names `"mongodb-shard2-service:27038"` , `"mongodb-shard3-service:27039"` ...

if a pod dies (pod-A), it won't be in a replicaSet unless i manually do `rs.reconfig()`, replicaSet Member  (pod-A) will report me `Our replica set configuration is invalid or does not include us`

what happens here is, mongodb will look on to its hostname on each nodes that is resolvable, hence a restarted pod, will have a different hostname, resulting to an invalid config. I could set `mongodb-shard2-service` on to its 

```
      containers:
      - name: mongodb-shard2-service
```

yet this would still give me a `-dbv2d`
```
        "host" : "mongodb-shard2-master-dbv2d",
	"version" : "3.0.7",
	"process" : "mongod",
```

**Comment by remh** [comment]
Another use case is when using daemonsets where the coupling node <-> container makes sense, there are a lot of use cases where it makes sense to pass the node hostname to the container (e.g. Monitoring tools running in containers but that monitors the whole node).
So it would be great to have that in the Downward API 
Thanks!

**Comment by Hokutosei** [comment]
Greetings,

Hi, have any follow ups on this? is there anyone I could get on advice about this? 

my problem is just when a mongodb instance restarted, it's replica config becomes invalid. it will find out that its current hostname is not in the mongodb replica config. because of its dynamic hostname, being set in the podname.. I tried using the service ipaddress instead, but the problem still persists..

this is the exact error of a restarted/rescheduled mongodb instance
```
> rs.status()
{
	"state" : 10,
	"stateStr" : "REMOVED",
	"uptime" : 2110,
	"optime" : Timestamp(1448462710, 6),
	"optimeDate" : ISODate("2015-11-25T14:45:10Z"),
	"ok" : 0,
	"errmsg" : "Our replica set config is invalid or we are not a member of it",
	"code" : 93
}
```

thanks!!

**Comment by bgrant0607** [comment]
PetSet proposal, for those interested: #18016

**Comment by bgrant0607** [comment]
See #19295, #20688

**Comment by ArtfulCoder** [comment]
we truncate pod hostname to 63 chars. so we should not have this issue anymore.
