### ISSUE TITLE
Forbidden: may not specify more than 1 volume type

### ISSUE THREAD

**Issue by r0fls** [kubernetes/kubernetes#48285]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature

**What happened**:
I was not able to deploy a secret as volume in addition to a PVC.

**What you expected to happen**:
I expected I would be able to.

**How to reproduce it (as minimally and precisely as possible)**:
Mount a pvc and a secret, or any two volume types.

**Anything else we need to know?**:
This is probably just a request for a documentation enhancement, unless there are plans to allow multiple volume types in the future.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4", GitCommit:"d6f433224538d4f9ca2f7ae19b252e6fcb66a3ae", GitTreeState:"clean", BuildDate:"2017-05-19T20:41:24Z", GoVersion:"go1.8.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.3+coreos.0", GitCommit:"8fc95b64d0fe1608d0f6c788eaad2c004f31e7b7", GitTreeState:"clean", BuildDate:"2017-02-15T19:52:15Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration**:
AWS
- OS (e.g. from /etc/os-release):
CoreOS
- Kernel (e.g. `uname -a`):
Not sure, don't have root access to the nodes or master.
- Install tools:
I was using helm to deploy but it should occur with kubectl as well.

**Comment by r0fls** [comment]
The validator throws that error here: https://github.com/kubernetes/kubernetes/blob/master/pkg/api/validation/validation.go#L392-L601

**Comment by JustinAzoff** [comment]
Hi, I ran into this but figured out what was wrong.  The validator is really only evaluating ONE volume specification.  It is trying to prevent you from doing something like

      volumes:
        - name: data
          emptyDir: {}
          persistentVolumeClaim:
            claimName: bro-logs-nfs

In a single volume.  I was getting the error because I was trying to get a specific volume type to work, but went to switch back to emptyDir using kubectl apply.  However, the OLD volume still existed server side, so kubectl was trying to merge the two volume specs together causing the issue.

In your case you probably did the same thing, started with an emptyDir and then tried to switch it to a        - name: logs.

**Comment by msau42** [comment]
Is this an issue with kubectl apply?

/sig api-machinery
