### ISSUE TITLE
Kubernetes v1.6.4 -> v1.7.0 update breaks statefulsets

### ISSUE THREAD

**Issue by CallMeFoxie** [kubernetes/kubernetes#48327]
/kind bug

**What happened**:
Updated from Kubernetes v1.6.4 environment to v1.7.0 environment with existing statefulsets. After seeing some errors regarding to scheduling I noticed repeated event:

> 8m		17s		32	statefulset			Warning		FailedUpdate	update Pod affinity-test-0 in StatefulSet affinity-test failed error: Pod "affinity-test-0" is invalid: spec: Forbidden: pod updates may not change fields other than `spec.containers[*].image`, `spec.initContainers[*].image`, `spec.activeDeadlineSeconds` or `spec.tolerations` (only additions to existing tolerations)

It seems that the statefulset is trying to update all its pods but with something that is immutable. Trying to figure out what and my current best guess is serviceAccount (which was not there previously when it was created).

**What you expected to happen**:
Delete and re-create the pods since it is changing immutable fields

**How to reproduce it (as minimally and precisely as possible)**:
- create statefulset in 1.6.4 with some features missing (SA?)
- update to v1.7.0

I have logs from controller-manager but they are rather spammy at --v=8 so if you have something to look for - here is what I guessed should be relevant (private info removed): https://gist.github.com/CallMeFoxie/353971434e20a3048b368d3fc835ab76

**Environment**:
- Kubernetes version (use `kubectl version`): v1.6.4 -> v1.7.0
- Cloud provider or hardware configuration**: self-hosted
- Install tools: manual

**Comment by CallMeFoxie** [comment]
Deleted the first affinity-test-0 POD and this is  the difference between new (affinity-test-0.yaml) and old (affinity-test-1.yaml) PODs, a lot has changed! 
https://gist.github.com/CallMeFoxie/91d242d08985add50f42431eef76fd00

**Comment by tpetr** [comment]
Seeing this issue as well when upgrading from 1.6.4 to 1.7.3.

**Comment by bbeaudreault** [comment]
This was broken in https://github.com/kubernetes/kubernetes/pull/44137

**Comment by bbeaudreault** [comment]
cc @k82cn

**Comment by liggitt** [comment]
Re: migration, there's no way to migrate from a beta annotation to a stable field and support both simultaneously without introducing significant issues affecting both server and client interpretation of data (see prior attempts at doing this with initContainers)

**Comment by PaulFurtado** [comment]
Hey @liggitt you actually already supported both simultaneously for quite some time and the hostname/subdomain annotations have been deprecated for a while.

The problem is that even brand new StatefulSet pods on 1.6.8 were still using the annotations instead of the spec fields. See: https://github.com/kubernetes/kubernetes/blob/v1.6.8/pkg/controller/statefulset/stateful_set_utils.go#L182-L190

Additionally, the problem introduced by not transitioning to the new fields is that all statefulset pods stopped resolving in DNS as soon as the apiservers were upgraded, which is a very serious and surprising operational problem. I think bugs related to not taking updates are much less severe by comparison since they don't cause an immediate application outage.

Furthermore, there is absolutely no possible upgrade path other than deleting all Statefulsets before the upgrade and re-creating them after since the hostname and subdomain fields are immutable. Surely, there has to be something better that could be done.

This is the change that broke everything: https://github.com/kubernetes/kubernetes/commit/2899f47bc86695ac8093c66cef2cc02d55c6a23d#diff-2ad3f4a4088a7249756d1b81af193493L188

It switched StatefulSets to use the spec fields, and removed the code in the getter that would honor the annotations in the same PR, leaving no versions of kubernetes pre-1.7 that would create statefulsets that can be safely upgraded.

I think the fix that would help the most people is:
- Cut a 1.6.9 release that makes Statefulsets use the hostname and subdomain fields when creating pods
- Document that every statefulset pod needs to be replaced on 1.6.9 before upgrading to 1.7

**Comment by bbeaudreault** [comment]
FYI @liggitt we used the above admission controller (https://github.com/HubSpot/kubernetes/pull/7) to safely migrate our few hundred statefulsets to the new fields before upgrading.  So I see no reason why @PaulFurtado's 1.6.9 suggestion wouldn't be possible. Is there some context we don't get?

**Comment by enisoc** [comment]
Another proposal being considered:

* Revert the change to stop respecting the annotation.
* Fix StatefulSet controller to not try to set the immutable hostname/subdomain fields when updating existing Pods.
* StatefulSet will continue to set the fields instead of the annotation on new Pods, from 1.7.0 onward.

This should get us back to a safe state as far as I can tell. We would then have time to work out a plan for how to eventually stop respecting the annotation.

**Comment by kow3ns** [comment]
#50942 and #51149 should at least allow a viable, safe upgrade path between 1.6.[x>=9] and 1.7.[y>=5] as per the suggestion of @PaulFurtado. I'm going to meet with the API Machinery SIG lead and see if there is more that we can do here.

**Comment by kow3ns** [comment]
So we landed on relaxing the validation in 1.7.x to make fields mutable if empty and modifying the controller to set them if empty. There still may be disruption to the network if you don't go through 1.6.9 and do a rolling recreate of all of the Pods, but at least it should be self healing.

**Comment by enisoc** [comment]
v1.6.9 is out now: https://github.com/kubernetes/kubernetes/releases/tag/v1.6.9

**Comment by kow3ns** [comment]
We've addressed this in the referenced PRs.
