### ISSUE TITLE
Allow for UDP/TCP services that retain the IP address of the client

### ISSUE THREAD

**Issue by toonsevrin** [kubernetes/kubernetes#48367]
@kubernetes/sig-network-services
It would be great if there was an option for service packets to retain their origin IP address. This could be done in a channel manner, where the service endpoint receives a packet, puts it on a channel to the destination node, the destination node takes it off the channel and gives it to the destination container, all without changing the origin address.

I'm very illiterate on systems like this but this seems quite feasible, except if I'm missing something. Of course there would be overhead but being able to retain ip address on your packets seems useful to me and probably a lot of users + this would be a non-default service type.

**Comment by toonsevrin** [comment]
@kubernetes/sig-network-*

**Comment by toonsevrin** [comment]
@kubernetes/sig-network-services

**Comment by lxpollitt** [comment]
@toonsevrin Can you clarify this feature request a little?  There a few different hops a packet destined for a service goes through that might hide the origin IP address from the service (typically due to NAT of some sort, without DSR).  For your use case, is the origin IP address somewhere outside the cluster, with the destination address being a service node port within the cluster?  Is the packet getting to the node port with the origin IP address intact?  And the feature you are requesting is for kube-proxy to be able to forward to another node in a way that maintains the origin IP address (instead of doing SNAT)?

**Comment by rturk** [comment]
@toonsevrin Not clear for me what problem you're trying to solve. If I understood your use case did you teste the proxy protocol?

**Comment by cmluciano** [comment]
/assign

You might be interested in source-IP addresses https://kubernetes.io/docs/tutorials/services/source-ip/. This feature is now GA in 1.7.

**Comment by toonsevrin** [comment]
sorry about the poor explanation: NodePort currently masks ip.

**Comment by toonsevrin** [comment]
@lxpollitt I'm basically looking for a NodePort variant without the loss of the SourceIP.

**Comment by cmluciano** [comment]
Are you looking for sessionAffinity?

**Comment by toonsevrin** [comment]
@cmluciano nope

**Comment by thockin** [comment]
Did you look at the `externalTrafficPolicy` field?  That does what you want.

**Comment by toonsevrin** [comment]
@thockin this is sufficient for my use case :)
