### ISSUE TITLE
Get Jobs command fails with an error

### ISSUE THREAD

**Issue by v-antech** [kubernetes/kubernetes#48411]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug
/sig cli
@kubernetes/sig-cli-*

**What happened**:
On our GKE cluster, running `kubectl get jobs --all-namespaces` fails with:
`Error from server: no kind "Job" is registered for version "extensions/v1beta1"`
Trying to delete any job in the namespace that causes the issue (even though no pods are running) fails with the same message.

**What you expected to happen**:
A list of jobs was expected, or an empty list.
Alternatively one should at least be able to delete the job, as the extensions/v1beta1 was replaced by batch/v1 (https://kubernetes.io/docs/api-reference/extensions/v1beta1/definitions/)

**How to reproduce it (as minimally and precisely as possible)**:
I am unfortunately uncertain as exactly what happened. I guess the job with `extensions/v1beta1` was created and then it did not get deleted properly (or maybe did not get deleted at all?)

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
kubectl version
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4", GitCommit:"d6f433224538d4f9ca2f7ae19b252e6fcb66a3ae", GitTreeState:"clean", BuildDate:"2017-05-19T18:44:27Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4", GitCommit:"d6f433224538d4f9ca2f7ae19b252e6fcb66a3ae", GitTreeState:"clean", BuildDate:"2017-05-19T18:33:17Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}

`kubectl api-versions`:
`apps/v1beta1
authorization.k8s.io/v1beta1
autoscaling/v1
batch/v1
certificates.k8s.io/v1beta1
extensions/v1beta1
policy/v1beta1
rbac.authorization.k8s.io/v1beta1
storage.k8s.io/v1
storage.k8s.io/v1beta1
v1`

- Cloud provider or hardware configuration**: 
GKE hosted k8s

`uname -a`
`Linux gke-cluster-1-n1-standard-16-2-2a6f2afb-kqbj 4.4.35+ #1 SMP Wed Apr 5 13:00:57 PDT 2017 x86_64 Intel(R) Xeon(R) CPU @ 2.30GHz GenuineIntel GNU/Lin`

Any help is greatly appreciated, thank you!
Jivko Vantchev

**Comment by v-antech** [comment]
I get that https://github.com/kubernetes/kubernetes/pull/38614 was removed in 1.6, but it seems that we missed the transition period to upgrade the job, now it the command simply fails. The main problem is that there doesn't see a legit way of deleting the job, as the delete command fails with the same exception.

Do you think that deleting the whole namespace and recreating it again will solve the problem?

**Comment by janetkuo** [comment]
@kubernetes/sig-api-machinery-misc 
/sig api-machinery

**Comment by liggitt** [comment]
The issue is that etcd has extensions/v1beta1 job objects stored that cannot be decoded. I'm not sure if these can be deleted without modifying etcd directly, since most code paths that deleting via the API server first do a decoding get to ensure there are no finalizers associated with the object

**Comment by liggitt** [comment]
> Do you think that deleting the whole namespace and recreating it again will solve the problem?

No, since the deletion of the namespace blocks on deletion of individual objects

**Comment by soltysh** [comment]
Cohabitation was introduced somewhere in 1.3, looking back into sources ([1.3](https://github.com/kubernetes/kubernetes/blob/release-1.3/cmd/kube-apiserver/app/server.go#L146), [1.4](https://github.com/kubernetes/kubernetes/blob/release-1.4/cmd/kube-apiserver/app/server.go#L178) and [1.5](https://github.com/kubernetes/kubernetes/blob/release-1.5/cmd/kube-apiserver/app/server.go#L180)) it clearly show since when cohabitation was introduced jobs where kept under `batch`, but with possibility to still read `extensions.Job`. [1.6](https://github.com/kubernetes/kubernetes/commit/9f064c57ce66809b10e088471fdf0a732ed95161) dropped entirely support for `extensions.Job`. 

@v-antech with all that, how did you got to the point where you still have `extensions.Job`, did you performed upgrade omitting one of the previous versions (definitely, not recommended!). Although it might be that, since you haven't touched the job in none of the 3 mentioned releases, the job was never re-saved which would update its location to batch. 

At this point in time, the only solution would be to:

1. remove that single job directly from etcd (be sure to make backup beforehand!) 
2. if you still have 1.5 around, invoke a dummy edit operation so that the jobs is re-saved under batch. 

For the latter I'm guessing we should have some info like that in the upgrade docs (@kubernetes/sig-release-misc next time wdyt?). 

@liggitt @janetkuo I'm not sure there's anything else aside from the two above solution to this.

**Comment by soltysh** [comment]
OpenShift [forces users](https://github.com/openshift/openshift-ansible/blob/506b2df261c9224f3e6a8328edad5c6de5a12b66/playbooks/common/openshift-cluster/upgrades/v3_5/storage_upgrade.yml#L16-L17) to perform such 'dummy write' upon upgrade to make sure the migration happens. I think k8s could do the same as part of the release process.

**Comment by janetkuo** [comment]
Agree with @soltysh on the [proposed solution](https://github.com/kubernetes/kubernetes/issues/48411#issuecomment-319352995). The underlying issue is proper migration upon cluster upgrades. Closing.

**Comment by caesarxuchao** [comment]
Ref https://github.com/kubernetes/kubernetes/issues/52185
