### ISSUE TITLE
Cluster versioning

### ISSUE THREAD

**Issue by zmerlynn** [kubernetes/kubernetes#4855]
This issue is a proposal and collection of work-items for the cluster versioning mechanics for 1.0. It is meant to contain concepts from #2524 and decisions from the 2015/02 Kubernetes Meet-up as to what to encapsulate/cut for 1.0: 
### Versioning requirements for `kubelet`:
- [x] `kubelet` version tuple must be reported for the cross-product of, at least, (kubelet, docker, kernel).
  `apiserver`. Since, as we'll see in the Upgrade section, these versions are bundled, the tuple itself may be encodable linearly (i.e. "kubelet image 97" for a given cloud provider / node image.) (#5948)
- [x] It should be easy to query the current versions of all kubelets from the API.
- [ ] `apiserver` must speak only the capabilities of the least capable `kubelet` software version (the first part of the tuple)
- [ ] `apiserver` of version `n.x` must be accessible to a kubelet of version `n.y` if `x>=y`. When in doubt, the [versioning policy](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/versioning.md) trumps this issue as to what API versions are required to interoperate, except that for 1.0 master components are always allowed to assume they're ahead of kubelet.

**Comment by rsokolowski** [comment]
Hi @zmerlynn , do you need any help with this issue ? If yes, which work items could I work on ? Thanks !

**Comment by roberthbailey** [comment]
This is a P1 and needs an owner. @zmerlynn if you are planning to drive it, please assign to yourself, otherwise it sounds like @rsokolowski is interested in starting on it.

**Comment by zmerlynn** [comment]
I think a chunk of this work is actually on Dawn, but let me figure out how to piece it out.

**Comment by zmerlynn** [comment]
cc @dchen1107

I think the first bullet, reporting the actual version *somewhere*, is probably somewhere on the node team. It seems like it could hook in with the status update mechanism for #4562 so that we're just doing one status update, but we don't necessarily need to update that often.

The second bullet (keeping track of all the versions) is ostensibly the NodeController.

The third bullet, having apiserver only speak the minimum, I'm not sure where it fits: ideally in a rolling upgrade scenario, you'd have some interconnection from NodeController to the `apiserver` that specifies the minimum, and when the last node reports in, an event fires back to `apiserver`. I'm not sure what follows this pattern right now.

The last bullet is waiting on the merge of #4833, and is otherwise, I think a testing and policy bullet. Which is complicated in its own right, but doesn't need a lot of upfront design.

**Comment by mbforbes** [comment]
This is awesome, @zmerlynn&mdash;thanks for nailing down the version requirements and writing out the 1.0 upgrade plan in understandable English.

I'm going to be removing the upgrade parts of this to shove them in the other rollups (master #6075 and node #6079). That way, this can be specifically the versioning rollup and we can split the work nicely into three separate issues. I think I've covered everything upgrade-related in those, but I really liked the clear description of upgrades for 1.0 you wrote in this, so I'm going to transfer that to one or both of them.

Let me know if I missed something in this transition, and sorry if I confused anyone's issue linking by doing this!

**Comment by mbforbes** [comment]
+ assigning @zmerlynn as the overall owner to drive, even if individual work items are handled across teams

**Comment by davidopp** [comment]
@bgrant0607 I'm interested in this topic, so if you want to start planning this before 1.0 please loop me in.

**Comment by dchen1107** [comment]
cc/ @saad-ali

**Comment by bgrant0607** [comment]
Broadening the discussion a bit. Hopefully it will become obvious why by the end.

No new feature can be depended upon until there's no risk of rolling back any control-plane component required for its functionality, and the feature has been adequately validated, perhaps by end-to-end tests and also perhaps by user trials. 

However, new features generally need to be exposed for at least testing, experimentation, or validation purposes earlier. 

SaaS providers delivering such features typically want to control their visibility and/or access along multiple axes:
* Lifecycle: Test, Experimental, Dogfood, Trusted Tester, Limited Availability, General Availability, Deprecated, etc.
* Audience: Admin, Partners, Public, Premium Customer, etc.

Re. access control / authorization policy:

Lifecycle-based access could be gated by tagging each new field with an API minor version, configuring which version is in each lifecycle stage, and enabling the client to select the desired stage of maturity, with General Availability as the default.

Audience-based access could be achieved by tagging each field with one or more categories, providing a way to map audiences to feature categories, and then imposing audience-based authorization.

Re. cluster assumptions:

Work on HA is underway. There will be multiple instances of apiserver and other cluster-level control-plane components. Not all control-plane components will run on the same nodes as the apiservers, and not all the components will be upgraded simultaneously. It would be nice if we could update apiserver using rolling update, as well. The control-plane components are essentially clients of apiserver, and will choose an arbitrary ready apiserver to connect to.

Like cluster-level control-plane components, kubelet is a client of apiserver. 

Re. visibility and API/client compatibility:

We currently have no mechanism to gate visibility of new API fields, in kubectl, in apiserver responses, nor in swagger.

We must ensure that older clients work with newer versions of the server. Clients need to be permissive in unmarshaling responses, but we want to perform strict validation of requests in the client (#7598) and server (#5889). If we do that, we either need to eliminate API conversions in kubectl (#3955), or we need to ensure that kubectl isn't updated until there's no risk of rolling back the apiserver, since new spec fields with default values may be added.

Re. API and component versioning:

We are planning to introduce multiple, independently versioned API groups (#6363, #635, #3201). 

Eventually some of these API groups will be implemented by plugin components. These plugins may not be part of our github repo. We will likely need to extend our [versioning methodology](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/versioning.md) to handle that, though I think we can ignore that case for now.

We should consider what we want to do about the etcd version, since that's at least one component with its own independent version, and I imagine there will be scenarios where it may not be updated at the same time, due to concerns about non-Kubernetes clients, as much as we would like there to not be any (see discussion in #1957). Since Kubelet also needs to surface multiple software versions (Docker, Rocket, OS), we should just accept that we'll need a map of components and desired versions.

We currently have only "major" API versions, which advance only when incompatible API changes are made (https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/api.md). The introduction of lifecycle-based feature access control implies the need for minor versions.

Re. "apiserver must speak only the capabilities of the least capable kubelet software version":

We must ensure that newer apiserver versions work with older versions of Kubelet, which is mostly the same requirement as for other clients. 

It would also be useful to control access to new features, as discussed above. I don't think that's a hard requirement at the current time, however, so long as we publish the current version(s) that is considered ready to use, which would be advanced when an upgrade is considered "done".

The component/tool orchestrating the cluster upgrade will want to validate that components reach their desired versions and are ready, stable, performing acceptably, etc. At some point, we'll want to replace nodes with kubelets that can't be updated in place, if we do in place updates. If the kubelets can't be replaced (e.g., on bare metal), we'll want to disable scheduling until they are updated to a minimum acceptable Kubelet version. I don't think we should track fine-grain kubelet capabilities.

**Comment by bgrant0607** [comment]
Re. versioning/validation discussion here: https://github.com/GoogleCloudPlatform/kubernetes/issues/3338#issuecomment-99549781

A good point was made about using the same client to talk to multiple clusters, which might make it infeasible to ensure the client was strictly no newer than any of those clusters. However, I still think the above proposals accommodate that case. In general, the client won't function as expected if it tries to use unsupported features. This suggests that we will want to eventually eliminate round-tripping in kubectl and to add lifecycle-based feature access. Only performing the validation in kubectl prior to round-tripping isn't sufficient, because it wouldn't help non-kubectl clients.

cc @smarterclayton @thockin

**Comment by thockin** [comment]
From #3338 

> > > > thockin said:
> > > > We do this inside Google with proto because we do not generally have
> > > > versioned APIs. With versioned APIs, I think that rejecting unknown
> > > > fields is much more tenable. Specifically, you asked for something
> > > > and we don't know how to handle it. Ignoring it MIGHT be OK, but it
> > > > might also cause the result to be semantically different than what I
> > > > asked for.
> 
> > > smarterclayton said:
> > > That means we can no longer add new fields to v1beta1. Instead every new
> > > field requires a new api version....
> 
> > thockin said: 
> > No, it means you have to not try to use fields before your master
> > supports them. That's very different. Now, this may be a problem as
> > long as kubectl is doing version conversions and defaulting.
> 
> This is a big problem for people who have existing stable deployments and new
> clients that need to talk to multiple servers. It effectively means that the
> client you use to talk to X servers has to be min(version){X}, which is
> practically impossible to manage.

No, again it just means you can't *use* features of newer masters on older
masters.  Isn't that semantically correct?  Assume you have a dozen masters.
half of them have the new Service.Spec.Frobnicator field.  Half do not.  My new
service depends on the Frobnicator - it's not useful without it.

If I send my service to a master that doesn't have Frobnicator support do I
want:

a) master says "OK, I can run that" and then does the wrong things
b) master says "EINVALID unknown field 'spec.frobnicator'".

?

**Comment by smarterclayton** [comment]
----- Original Message -----
> From #3338
> 
> > > > > thockin said:
> > > > > We do this inside Google with proto because we do not generally have
> > > > > versioned APIs. With versioned APIs, I think that rejecting unknown
> > > > > fields is much more tenable. Specifically, you asked for something
> > > > > and we don't know how to handle it. Ignoring it MIGHT be OK, but it
> > > > > might also cause the result to be semantically different than what I
> > > > > asked for.
> > 
> > > > smarterclayton said:
> > > > That means we can no longer add new fields to v1beta1. Instead every
> > > > new
> > > > field requires a new api version....
> > 
> > > thockin said:
> > > No, it means you have to not try to use fields before your master
> > > supports them. That's very different. Now, this may be a problem as
> > > long as kubectl is doing version conversions and defaulting.
> > 
> > This is a big problem for people who have existing stable deployments and
> > new
> > clients that need to talk to multiple servers. It effectively means that
> > the
> > client you use to talk to X servers has to be min(version){X}, which is
> > practically impossible to manage.
> 
> No, again it just means you can't *use* features of newer masters on older
> masters.  Isn't that semantically correct?  Assume you have a dozen masters.
> half of them have the new Service.Spec.Frobnicator field.  Half do not.  My
> new
> service depends on the Frobnicator - it's not useful without it.
> 
> If I send my service to a master that doesn't have Frobnicator support do I
> want:
> 
> a) master says "OK, I can run that" and then does the wrong things

Technically it's doing the exact same thing you asked it to do before.  Your additive new thing just doesn't work quite right.  The WhatsIts and WhooZats are all still busy churning away, it's the Frobnicator that's ignored.

> b) master says "EINVALID unknown field 'spec.frobnicator'".
> 

I agree with the general *principle*.  I just have never seen it work well in the messy world of enterprises for people limited time and budgets who use shoddy open source libraries written by folks who have other things to do.  Every generic client will be broken as soon as anyone in the world introduces a feature that someone else wants.  

I'm totally in favor of having tools for making these sorts of checks - feature flags, schema versions, schema parsing, strict mode, etc.  I'm fairly scared though that the outcome of the strict behavior is just going to be that it's a nightmare of incompatible tools maintained by other people, none of which work against the servers you have available, and then you get StackOverflow posts like "Hey, if you want to make it work checkout commit 9347387 and then change line 34 of library.py and then never update it again".

I do want tools that allow clients to easily recognize they are out of date and that the experience is degraded.

**Comment by bgrant0607** [comment]
@pwittrock

**Comment by bgrant0607** [comment]
A notion of minor API versions would facilitate bundling of API versions across groups, as discussed here: https://github.com/kubernetes/kubernetes/pull/12951/files#r38804675

**Comment by smarterclayton** [comment]
I would like to consider schema versions for individual objects or groups
to allow controlling defaulting/conversion behavior from clients more
precisely.  A lot of our behavior challenges is back compat - smaller
increments of version might be possible to do more precisely from our
clients and server.  Things like precedence order of old fields.

On Sep 9, 2015, at 7:07 PM, Brian Grant <notifications@github.com> wrote:

A notion of minor API versions would facilitate bundling of API versions
across groups, as discussed here:
https://github.com/kubernetes/kubernetes/pull/12951/files#r38804675

—
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/4855#issuecomment-139068536>
.

**Comment by bgrant0607** [comment]
cc @davidopp @mml

**Comment by lavalamp** [comment]
@zmerlynn do you intend to do further work on this for 1.2?

**Comment by zmerlynn** [comment]
Nope.

**Comment by bgrant0607** [comment]
See also:

https://github.com/kubernetes/kubernetes/blob/master/pkg/features/kube_features.go

#34508

**Comment by bgrant0607** [comment]
https://github.com/kubernetes/community/blob/master/contributors/design-proposals/runtimeconfig.md

**Comment by bgrant0607** [comment]
Discussion for that proposal: https://github.com/kubernetes/kubernetes/pull/30003

**Comment by bgrant0607** [comment]
Field gate proposal: https://docs.google.com/document/d/1wuoSqHkeT51mQQ7dIFhUKrdi3-1wbKrNWeIL4cKb9zU/edit#

Note also that the concept of "profiles" is being discussed, for multiple purposes.

**Comment by roberthbailey** [comment]
@zmerlynn - can you triage this issue?

**Comment by bgrant0607** [comment]
/remove-lifecycle stale
/lifecycle frozen

I'd like to keep this open. We have a number of challenges around cluster lifecycle that I'd like to consider holistically:

* Field-level versioning: #34508
* HA masters mangle data: #46073
* Storage upgrade: #52185
* Teardown: #4630
* Run levels: #54522
* I don't remember which issue covers resource stranding upon rollback.
* Add-on management: #23233

**Comment by bgrant0607** [comment]
cc @jagosan

**Comment by bgrant0607** [comment]
Operations:
* Turn up
* Upgrade
* Downgrade
* Teardown

Strawman upgrade sequence:
1. Upgrade masters (apiserver, controller manager, scheduler)
2. Enable new APIs
3. Upgrade addons (caveats: don't remove old DaemonSets, maybe support API version discovery)
4. Disable old APIs
5. Upgrade nodes

**Comment by krmayankk** [comment]
@bgrant0607  why is this frozen ? it seems it was originally created for 1.0 in 2015, but has lot of relevant details that could become a documentation link or KEP for how clusters should be upgraded , but not sure i have seen any of those documentation.

**Comment by bgrant0607** [comment]
@krmayankk It's fine to close this issue, though AFAIK, neither the upgrade/downgrade sequencing, nor lifecycle stages, nor teardown operations, nor the other proposals mentioned above (https://github.com/kubernetes/kubernetes/issues/4855#issuecomment-359481116) have been implemented. More specific issues, such as #54522 have been filed.

/close
