### ISSUE TITLE
RFC: kubectl should not depend on internal types?

### ISSUE THREAD

**Issue by mengqiy** [kubernetes/kubernetes#48564]
As part of the efforts to move kubectl out of the main repo, kubectl may not depend on the internal types in the main repo.
We @kubernetes/sig-cli-maintainers want to come up with a plan for kubectl with the help from @kubernetes/sig-api-machinery-misc.

Paste some discussion in slack #sig-api-machinery channel.

@deads2k:
>given that `kubectl` wants to move itself out of tree, it can't use internal types for long.
if that's the direction they want to go, internal types either have to go or have to be copied, so they'll want a plan
it's a lot of work.  I'm still not convinced its good for us, but @lavalamp feels very strongly about it being the wave of the future.  You could try interfaces to abstract the difference out for the various versions, but its still a lot work for kubectl and every controller

@lavalamp:
> It's more that I want per-binary/source tree internal types. By definition, we don't provide any compatibility guarantees on the internal types (as that would destroy their intended function of letting us move fast without breaking wire format), so we can't put them in any public library like client-go.

@bgrant0607 @thockin @lavalamp @smarterclayton @deads2k @liggitt @caesarxuchao 
@pwittrock @fabianofranz @monopole @adohe

**Comment by deads2k** [comment]
So boiling down that paste, I saw two concrete suggestions:

 1. create interfaces to abstract the differences between versions and use them. -  This actually works reasonably well for commands that do get, mutation, put (we did it openshift for one set of types).  That means it works for something like the node management commands.  It would not work as well for commands that create requests: `can-i` stands out as an example of an API with multiple versions that constructs a request.

 2. Create your own internal types.  This means that you'll need to maintain the conversions for those types, but it doesn't have the creation from scratch issues that an interface has.  The good news is that you wouldn't have that many. The bad news is that you'd not only have to write the internal versions and their conversions and not lose fields on round trips, you'd also have to shim your clients to create interfaces that can do the conversion for you.

A third option occurred to me while typing this.  You could actually duplicate the commands and their logic multiple times.  I don't think I'd recommend it, but it's one the alternatives @DirectXMan12 man considered for the HPA controller before he took advantage of his access to the internal types and converted to internal.

**Comment by lavalamp** [comment]
kubectl long had a problem where it round-tripped through internal types, which caused it to inappropriately apply defaulting etc. We mostly fixed that a few releases ago.

My own roadmap for kubectl involves all custom command implementations moving to the server, where they will be available for other clients as well. With that in mind, I have a 4th option to consider in addition to @deads2k's three: Just don't implement special code on more than one version of a resource. That should make kubectl much simpler. It would still be able to do CRUD on versions it doesn't understand. But if you do something fancy, it's fine to make it stick to one version and rely on the backward compatibility promises of the control plane.

I think the internal types don't actually add a lot of value to kubectl anyway. I think they make more sense for controllers and maybe apiserver. I think having conversion logic distributed among clients is actually a bad thing, because it is way harder to fix clients than to fix the control plane.

So the options as I see them, in my preference order, are:

1. Don't do multi-version custom operations at all. (and if it becomes absolutely necessary, fix by copy-paste, which is @deads2k's third option.)
2. Use ordinary go interfaces. Go interfaces are actually powerful and can make for clean, readable code.
3. Give kubectl its own copy of the internal types.

**Comment by pwittrock** [comment]
The current plan is to do as @lavalamp suggested - things that rely on specific compiled in types should pick a version and use the external client-go library.

**Comment by soltysh** [comment]
As far as it stands this is already implemented.
/close

**Comment by liggitt** [comment]
The convert command still depends on internal types, right?

**Comment by soltysh** [comment]
> The convert command still depends on internal types, right?

Correct, and from what the discussions we've had I'm not sure this will change. That's why it was decided to make `kubectl convert` a plugin and build from the main k/k repository.
