### ISSUE TITLE
"kubectl create" subcommands need to validate printer flags before creating a resource

### ISSUE THREAD

**Issue by alexandercampbell** [kubernetes/kubernetes#48738]
/kind bug

**What happened**:

I ran

```bash
kubectl create deployment test-output --image=nginx --output="invalid"
```

The deployment "test-output" was created, but then I got this error message: `error: output format "invalid" not recognized`.

**What you expected to happen**:

The "kubectl" command should have errored out immediately when I provided a bad "--output" flag.

This is because the logic currently runs:
1. Create deployment. [code](https://github.com/kubernetes/kubernetes/blob/0744964956abdb17586361dee59853f6167b58d7/pkg/kubectl/cmd/create.go#L281)
2. Validate the "--output" flag (and related printer flags). [code](https://github.com/kubernetes/kubernetes/blob/0744964956abdb17586361dee59853f6167b58d7/pkg/printers/printers.go#L128-L129)
3. Print the deployment info. [code](https://github.com/kubernetes/kubernetes/blob/0744964956abdb17586361dee59853f6167b58d7/pkg/kubectl/cmd/create.go#L298)

Steps 1 and 2 should be switched.

**How to reproduce it (as minimally and precisely as possible)**:

Run the command I gave.

**Why didn't I just fix this?**:

Because the printer system is very complicated and tightly coupled to Cobra.Command. There is no way to validate that the printer flags are valid without actually printing something. A solution might be to make a struct `PrintOptions{}` that can be read from Cobra and validated independently.

Credit goes to @mengqiy for discovering this issue.

**Comment by xingzhou** [comment]
I think for kubectl, all the validation work shall be done in the `validate` phase, before the `run` stage. @alexandercampbell, are you working on this? if not, I would like to take a look

**Comment by alexandercampbell** [comment]
@xingzhou sure, you can give this a shot. I don't think it's a trivial fix.

**Comment by xingzhou** [comment]
thx, let me take a try

**Comment by xingzhou** [comment]
@alexandercampbell, after some look at the code, I'm planning the following changes in the code, to discuss with you first:

1. Merge `printers.PrintOptions` and `printers.OutputOptions` into new `printers.PrintOptions` which can cover all the option fields provided by these two structs. This change can simplify the code, as now, many of the printing related methods depend on both of these two options as parameters. 

2. Create a new method named `extractAndValidatePrintOptions` to extract and validate all the options from `Cobra` command object. Each of the kubectl command will call this new method before they creating/updating any resources in K8s.

3. Change the printing related method like `PrintForCommand` or `PrintForMapping` to pass the new `printers.PrintOptions` instead of `Cobra` command object as their arguments, so that those methods will no longer need to extract printing options from command object any more and no longer depend on `Cobra` command object any more.

Please let me know your ideas on this, thanks!
