### ISSUE TITLE
New daemon set to support isolated coredump for namespaces/users

### ISSUE THREAD

**Issue by CaoShuFeng** [kubernetes/kubernetes#48787]
**Is this a BUG REPORT or FEATURE REQUEST?**:
 /kind feature

**What happened**:
Now linux coredump doesn't support namespace.
So all containers in kubelet node share the same /proc/sys/kernel/core/core_pattern kernel parameter. Coredump files from differnet pods/namespaces/users have to share the same core_pattern kernel parameter.
**What you expected to happen**:
Coredump files from different namespaces should be isolated. And users should be able to download their coredump files.

Now we are planning to design a new [add-on](https://github.com/kubernetes/kubernetes/tree/master/cluster/addons)
This add-on run as a privileged daemonset in each node. It will wirte the /proc/sys/kernel/core/core_pattern.
$ echo "|/var/bin/my_coredump_detector %p %P %t" > /proc/sys/kernel/core/core_pattern
The my_coredump_detector program will communicate with kube-apiserver to see where should the coredump files put. Then users can download their own coredump files.
The architure:
![default](https://user-images.githubusercontent.com/20855209/28098661-293ac1be-66ea-11e7-90a4-153daf7fede0.png)

**Comment by CaoShuFeng** [comment]
I commit this issue to see whether this idea is acceptable to the community.
I will start writing this daemon set if the community says OK.

**Comment by CaoShuFeng** [comment]
/cc @ixdy @MrHohn @fabiand @luxas 
CC some active contributors in addons for advices.
Thanks very much in advance.

**Comment by luxas** [comment]
@CaoShuFeng why should this go into core? The `cluster/`directory is deprecated and we're not planning to add new functionality in there, but rather move things away from it.

cc @kubernetes/sig-node-feature-requests for this general idea. This might be solvable in various other ways than making a DaemonSet addon and putting it in `cluster/addons/`

**Comment by CaoShuFeng** [comment]
> This might be solvable in various other ways

@luxas Here "other ways" means I have other ways to contribute my idea to community?

**Comment by vishh** [comment]
@CaoShuFeng 

This proposal is a step in the right direction. I'd recommend prototyping this and sharing your experience with the community. Here are some questions to consider along the way:
1. How to limit the size of core dumps?
2. How do limit size and number of core dumps per pod? Would you consider a core dump quota per namespace?
3. Have you considered using any of the existing tools (apport, abrt, etc)?
4. Have you considered injecting your tool to directly copy core dump data from the kernel to a remote filesystem instead of caching it on local node storage?

The overall idea is sound. The more modular you can make this tool, the wider it's adoption will be - that's my feedback.

**Comment by CaoShuFeng** [comment]
> How to limit the size of core dumps?
> How do limit size and number of core dumps per pod? Would you consider a core dump quota per namespace?

I am planning add a new [aggregation api](https://kubernetes.io/docs/concepts/api-extension/apiserver-aggregation/) and make this api running as pod in cluster.
This third party api will contain metadata of coredumps.
Like: which namespace this core dump belongs to? where it is stored?
We can add quota per namespace in this aggregation api too.

> Have you considered using any of the existing tools (apport, abrt, etc)?

Havn't yet. This only relies on the linux kernel core dump feature.
Using these tools will cause more dependency, I think.

>Have you considered injecting your tool to directly copy core dump data from the kernel to a remote filesystem instead of caching it on local node storage?

This should be configurable. And store it on local node should be an option.(But in this case only system administrator can access these core dump files in local node).

**Comment by CaoShuFeng** [comment]
> I'd recommend prototyping this and sharing your experience with the community.

Hi, @vishh ,can you tell me where should I put this "add-on"?
I have to report to my boss in advance.

**Comment by vishh** [comment]
> We can add quota per namespace in this aggregation api too.

How will the aggregation API solve the issue of sharing local storage between pods for core dumps? Explain that in your (future) proposal.

> Using these tools will cause more dependency, I think.

is that necessarily a bad thing? State the pros and cons in your proposal.

> Hi, @vishh ,can you tell me where should I put this "add-on"?

In your own github repository.

**Comment by luxas** [comment]
> In your own github repository.

Yeah, I think that sounds good for prototyping. Then there is a Kubernetes incubator, but that's probably overkill for this kind of thing.

@CaoShuFeng The next steps I see here is writing up a full markdown proposal and creating a PR adding that in the community repo. Sounds good to you?
The details of this proposals (with pros/cons as @vishh said) will then be discussed there.

**Comment by CaoShuFeng** [comment]
> The next steps I see here is writing up a full markdown proposal and creating a PR adding that in the community repo.

Thanks for your suggestion. Do you mean this:
The proposal will be put [here](https://github.com/kubernetes/community)?
And the code will be put in my own repository?

**Comment by luxas** [comment]
@CaoShuFeng Yes, at least initially

**Comment by CaoShuFeng** [comment]
@luxas  @vishh 
Can you take a look at this:
https://github.com/kubernetes/community/pull/1311

**Comment by WanLinghao** [comment]
Hi, all
Found this issue and this is exactly what we want. We need this feature based on following user case:
When a failure occurs to an app on a container,for example, in really late night.  The owner
of the app needs to investigate the root cause of the problem, but if the operator is off-duty
around the time, there's nothing the app owner can do.  Meaning, app problems depend on the
operator, which situation isn't appropriate.If the app owner want to provide 24x7 support service, the operator also needs to work 24x7 so the operator can provide a coredump file that the app owner wants even at really late night.  With this coredump feature , we don't need to have the operator work 24x7 anymore. 
Besides, coredump files are possession of app owener, not the operator.  coredump files contain
some data that the operator shouldn't be able to look.  So also for the security sake, coredump file should be automatically stored in a storage that only the app owner refers.

**Comment by WanLinghao** [comment]
@luxas @vishh  I think this could be a common feature that would be appreciated by many users.
Are there any chances that this feature be part of core?

**Comment by WanLinghao** [comment]
OOM event is not a rare thing in a well-organized cluster, tenants' apps could exceed quota and trigger
 it at any time. When it comes to a busy cluster which got lots of containers and lots of tenants, it 
is a big burden for admin to organize and distribute coredump file. In our case, tenant wants to access 
their coredump files as soon as possible, so cluster admin would be ready all the time to distribute the 
coredump file. I think it may reduce the admin's work significantly with coredump feature. So we reaaally wish communities could considering this feature, thanks!

**Comment by WanLinghao** [comment]
@tallclair @deads2k   Hi,what's your view about this proposal
