### ISSUE TITLE
Resolve ambiguity between default namespace, no namespace, and empty namespace

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#4879]
Forked from #4396 and probably other issues.

Nodes and other infrastructure resources (e.g., persistent volumes) should go into a namespace, such as kubernetes. Not putting them into a namespaces, creates special cases everywhere. 

@derekwaynecarr @smarterclayton @lavalamp @thockin @erictune @markturansky

**Comment by thockin** [comment]
And what about Namespace objects?  Once we have one object outside of
namespaces is it really worse to have O(small) more?  Especially compared
to the "specialness" of a namespace that holds things that are available
from other namespaces...

**Comment by bgrant0607** [comment]
The concrete problem we have now is what to do with Node events vs. events in the default namespace.

However, I think it's useful to put infrastructure resources into namespaces for management reasons, to facilitate dedicated machines, custom schedulers, custom controllers, etc.

I also think that only things that REQUIRE cluster root should not be namespaced. Nodes do not require cluster root, and therefore should be namespaced.

**Comment by bgrant0607** [comment]
It's also inevitable that we're going to have more nuanced permissions. Everyone can read but only certain users can write will be common, for instance, and would be sufficient for nodes.

**Comment by derekwaynecarr** [comment]
A ```Namespace``` is not in a namespace, and per the earlier comment, it's not a concern because it does not produce events, and to be fair, ```Namespace.Name``` is the the effective namespace for that object.  Putting a ```Namespace``` in a name introduces a turtles all the way down which is a use case I do not support.

For a future use case, I would not want to put a ```User``` object in a namespace.  The ability to introduce user's into the system effectively requires cluster root.

/cc @liggitt

**Comment by dchen1107** [comment]
What's this special namespace for node and other infrastructure buying us? Since it is special, we have to deal with it differently. In this case, there is no difference between dealing events with namespace and without namespace, right? Also are we going to keep track of all those special names: special namespace, special infrastructure container name, etc.

**Comment by smarterclayton** [comment]
Agree on that - either cluster resources are exposed into a namespace (in which case there is no canonical url), or they are exposed as a singleton.  Why invent a special namespace for singletons?

We can always expose endpoints in namespaces for returning scoped cluster resources (which elide or limit portions of the resource visible to you).  I.e a node displayed inside a namespace scope has restricted fields, and access can be further enforced in the future.

**Comment by ddysher** [comment]
wow, glad someone creates an issue for this, it causes me a lot of headache !!

My understanding is that our API object doesn't differentiate Namespaced object vs Non-namespaced object, everything is namespaced essentially (i.e. built from ObjectMeta).   We claims that "" means the object is not namespaced, but it just means the object is under Empty namespace, not Non-namspaced;  hench all the corner cases.  For the node event problem, it can be easily solved by moving node from the empty namespace to default namespace, i.e. the namespace proposed in the issue.  I think we should do this.

How hard is it to not differentiate namespace vs non-namespace at all?   Think it other way, namespace actually sits in its own namesapce

**Comment by bgrant0607** [comment]
I know changing titles is annoying, but I just generalized it. We need to resolve the ambiguity between default namespace, no namespace, and empty namespace.

**Comment by smarterclayton** [comment]
Having seen the before and after impact on client code and server code, there was a net win on how we represent and communicate types.  I think it's also reflected in the api and the paths, which are much clearer now.  The problem was mostly in our code, which confused the three scenarios in overlapping ways.  Internally, we *should* have followed dans recommendation to use "*" to mean namespace all from day one.  We still need to do that.

**Comment by derekwaynecarr** [comment]
I am working on a PR to evolve and update the namespaces design to both reflect current state and where we want to go.

I will make a point of putting some base assertions on when objects should or should not have a namespace.  In practice, I thought Brian's summary we discussed in real life was reasonable.  Objects that can support delegated management to something other than cluster root administrators seemed like a good first step.

Either way, will write a doc up while on the plane :-)

**Comment by erictune** [comment]
I disagree with this Issue.
  - To me, a namespace is just a mechanism that permits non-cooperating groups to chose names for object independent of each other. 
  - nodes do not require namespacing.  Nodes already have an IP address (and usually a DNS name), which is unique among the set of nodes that the apiserver knows about.
  - we should avoid attaching too many additional "behaviors" to namespace. Internal experience with projects, has shown them to be inflexible, due to having additional policy assumptions baked into them.
  - nodes are quite different from pods or services or rcs.  If we try to namespace those, we will end up attaching a different, but partly overlapping set of behaviors to namespaces as apply to nodes, vs as applies to pods.  This will be confusing to users.
  - node certainly may be partitioned into dedicated pools.  they may also be divided up by any number of other labels.  Let us attach behavior to specific labels, rather than lumping behaviors onto namespaces.
 - some things clearly don't need namespaces, like "namespace" objects.  Probably others too.  The existence of these invalidates the agument of making nodes namespaced for uniformity sake.
  - some object have something like a namespace, but there is already an established term-of-art for that thing.  In those cases, we should use that term.  For example, users and groups will span our namespaces.  But they are "namespaced" in the sense of being disambiguated, by their domain, or realm.  In those cases, we should include that information somewhere else in the object, such as in the Name, or give it a random Name and put it in the body of the object.

**Comment by erictune** [comment]
To me, "default" namespace should mean only one thing: *the default value for Namespace when one is not provided, when making a REST call on a resource that is namespaced*.

It should **not** mean *the namespace into which we toss any crap that is in some way special*. 

If a resource type is namespaced, then it should not have an empty namespace.

**Comment by erictune** [comment]
I don't think we will find that it is easy to categorize objects as requiring cluster root or not.  
Every component in the system will have different capabilities, with no object that has capabilites which are a superset of all the others.

**Comment by erictune** [comment]
I don't understand the statement *only things that REQUIRE cluster root should not be namespaced.*

**Comment by smarterclayton** [comment]
> On Mar 3, 2015, at 11:08 AM, Eric Tune <notifications@github.com> wrote:
> 
> To me, "default" namespace should mean only one thing: the default value for Namespace when one is not provided, when making a REST call on a resource that is namespaced.
> 
> It should not mean the namespace into which we toss any crap that is in some way special.
> 
Agree - no "special" namespaces.
> If a resource type is namespaced, then it should not have an empty namespace.
> 
Agree.

**Comment by markturansky** [comment]
Can someone provide a good example showing the difference between "no namespace" and "empty namespace"?  I can't think of one where "" is meaningful.

+1 for Eric's definition of "default namespace"

**Comment by erictune** [comment]
@markturansky if a resource type is not namespaced, then its resource URLs have no `.../ns/foo/...` path component.  Otherwise, they do.  No object ever has an URL with `.../ns//...` in it.  The rest is implementation details.

**Comment by markturansky** [comment]
thanks, @erictune, but is there a good example of something in an empty ("") namespace?  What is the point of an empty namespace?  

The distinction between non-namespaced objects and namespaced ones is crystal clear.  The empty one is throwing me off.

**Comment by erictune** [comment]
@markturansky 
The only use case I can think of is it might be convenient in some places in the code to pass an empty string to a Namespace argument of a generic function that handles both namespaced and non-namespaced resources.

**Comment by smarterclayton** [comment]
Which we explicitly disallow in client/request.go now because it causes problems - if you invoke Namespace and the value is empty it will yell at you.

**Comment by bgrant0607** [comment]
@erictune and I discussed this topic this morning. I think we agreed to the following:
1. Empty ("") namespaces should be disallowed, if they aren't already.
2. The default namespace should be made explicit. No duplicate paths in the API. It could be defaulted by the kubeconfig magic or something else in the client, and the default namespace object could be created at cluster birth time somehow.
3. Node occurrences that affect pods should generate pod events as well as node events.

We also discussed the idea of changing events to be a subresource under the affected objects. I'm thinking that might be a good way to go for endpoints, also. We might still want to support paths that list all events/endpoints for infrastructure components.

**Comment by smarterclayton** [comment]
> On Mar 3, 2015, at 5:34 PM, Brian Grant <notifications@github.com> wrote:
> 
> @erictune and I discussed this topic this morning. I think we agreed to the following:
> 1. Empty ("") namespaces should be disallowed, if they aren't already.
> 
They are in both client and server for namespace scoped resources.  Passing a namespace for a cluster scoped resource is also forbidden.
> 2. The default namespace should be made explicit. No duplicate paths in the API. 
> 
I believe it is today
> It could be defaulted by the kubeconfig magic or something else in the client, and the default namespace object could be created at cluster birth time somehow.
> 
It is, during master startup.

...

**Comment by derekwaynecarr** [comment]
Is an accurate summary of this issue the following:

1. A Kind is either associated with a ```Namespace`` or not
2. The ```Namespace``` Kind is not associated with a namespace (no nesting)
3. A Kind associated with a ```Namespace``` will have the namespace in its URL path
4. A Kind not associated with a ```Namespace``` will not have the namespace in its URL path
5. Our client code needs to have mechanisms to handle this
6. A resource cannot get associated with a ```Namespace``` that does not exist

We have items 1-5 already.  

For item 6, we ensure the default namespace is defined as part of master startup.  To complete item 6, we agreed at the meet-up to provision a ```Namespace``` upon first use when putting a Pod, etc in that space to ensure you would not have a situation where a resource was in a Namespace that did not exist.  There was agreement on the desire to support graceful termination of resources at the ```Namespace``` level.  I have the TODO to drive both those topics to completion.

This still leaves me ambiguous on the topic of Event objects produced by a Node.

We discussed putting pods that are placed on a Node by the Kubelet from a file or http source in a namespace on the apiserver so they are known to the scheduler.  I believe we said those pods would go in a namepace associated with the cluster-id.  Is there a reason why Node events cannot go in that cluster-id namespace, and Pod events go in the namespace associated with the Pod?

**Comment by erictune** [comment]
Does /api/v1beta3/pods still work?  If so, then 3 is not done.

The other issue is whether events is a kind that has a namespace, and if it does, what is the namespace for events that contain objrefs to kinds that don't have a namespace.

**Comment by erictune** [comment]
cluster-id-namespace events seems fine in the short-term.
longer term, we talked about getting rid of events as a first-class resource, and having them only be a subresource of other resources.

**Comment by smarterclayton** [comment]
It's the "everything" query, not the "no namespace" query.  I.e. show me all pods across all namespaces.

----- Original Message -----
