### ISSUE TITLE
Help LivenessProbe Kubernetes

### ISSUE THREAD

**Issue by rafaelsilvaa10** [kubernetes/kubernetes#48918]
Hello, 

 I am testing the LivenessProbe in kubernetes. I tried to simulate a possible failure.    
[....
    livenessProbe:
          httpGet:
            path: /
            port: 8074
          initialDelaySeconds: 120
          timeoutSeconds: 1
....]

I put it to start the check after 2 minutes.
In my container there is not port 8074. That is when I do a get curl IPContainer:8074/    ;...Will give refused .... I put it just to simulate a failure in HTTP.

However, The container not restart.

jobs-mobile-1040363144-cgbxw           0/1	 CrashLoopBackOff   7          9m

The container is in CrashLoopBackOff but does not "die" and is reborn ".

Do you know what can happen? Because it does not recreate and it works again, however I understand that after 2minutes again it will fail due to the check.

Thanks

**Comment by cblecker** [comment]
Please re-post your question to [Stack Overflow](http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases.

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans Stack Overflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search Stack Overflow for answers to similar questions, and also familiarize yourself with:

  * [user documentation](http://kubernetes.io/docs/)
  * [troubleshooting guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/)

Again, thanks for using Kubernetes.

The Kubernetes Team

---
/kind support
/close
