### ISSUE TITLE
Deployments with GCE PD fail with "...is already being used by..."

### ISSUE THREAD

**Issue by saad-ali** [kubernetes/kubernetes#48968]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

From user report on [reddit](https://www.reddit.com/r/kubernetes/comments/6na6ef/gce_does_not_release_persistent_volume_from_node/):
```
I have a deployment with persistent volume claim in Google cloud. One pod is using this volume. Deployment is of "recreate" type. But each time node is feeling under the weather and reschedules this pod to another one, it fails to start with:

googleapi: Error 400: The disk resource 'projects/...-pvc-...' is already being used by 'projects/.../instances/..node-bla-bla'     

I've stumbled across some issues on github, but don't see definitive solution. Due to the nature of the problem, I cannot reliably recreate it manually, artificial overload needs to be created.

What I considered doing:
1. Create some sort of gluster/ceph/whateverfs cluster and using it as PV. Con: additional point of failure, needs setup/maintenance of its own.
2. Create separate node pool with 1 node in it and schedule deployment strictly to that pool. Con: doesn't scale neither up nor down, at this point no need in one whole node just for that deployment, but if it grows then problem starts all over.

I've upgraded cluster and nodes to 1.6.7, but don't know if it will matter. Any help appreciated.
```

Other reports here:
* https://github.com/kubernetes/kubernetes/issues/19953#issuecomment-272181659

**What you expected to happen**:
Volume should attach to new node without issue.

**How to reproduce it (as minimally and precisely as possible)**:
-

**Anything else we need to know?**:
-

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by msau42** [comment]
The initial report mentions that the node was not healthy, so the pod got rescheduled.  Does that trigger the update strategy (recreate or rollingupdate)?

**Comment by yuvipanda** [comment]
We've run into this a lot too, and we weren't using deployments. We were simply spawning pods that had a PD attached. After the pods were killed, the disks don't seem to be detached from the underling VM automatically, sometimes for hours? When the pods come back up on a different machine, we often get this exact same error error (and it sometimes clears up in a few minutes, often not).

We wrote a script that just watches for this issue (grepping describe in a loop, ugh) and runs the appropriate gcloud detach command, and that made the problem 'go away' for us.

We were on GKE.

**Comment by tamalsaha** [comment]
We also see this issue happening. The most annoying thing about GCE is that it does "silent" migration of VMs, after which PVs are not released. So, when Kubernetes wants to start pod on that node, it fails with resource already in use type error.

cc: @sadlil

**Comment by wawastein** [comment]
Hello, I'm original reddit poster. Couple more details.

Deployment in question (sans sensitive info):

```apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ...-redis
  labels:
    name: ...-redis
spec:
  selector:
    matchLabels:
      name: ...-redis
  template:
    metadata:
      labels:
        name: ...-redis
        app: ...
      namespace: ...
    spec:
      nodeSelector:
          cloud.google.com/gke-nodepool: pool-1
      volumes:
      - name: redis-data
        persistentVolumeClaim:
          claimName: ...-redis
      containers:
      - name: redis
        image: "gcr.io/.../...-redis:latest"
        ports: 
        - name: redis
          containerPort: 6379
        volumeMounts:
        - mountPath: /data
          name: redis-data
  strategy: 
    type: Recreate
```
The PVC:
```kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ...-redis
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
```
Last time I observed behavior in question, it was induced by faulty job producing high number of faulty pods, which generated disk pressure. Redis was scheduled to different node and the rest is history.
Please let me know if I can be of any additional help.

**Comment by jingxu97** [comment]
@yuvipanda Thank you for reporting the issue. Is that possible you could share us some controller's logs during the issue happened? Thanks!

**Comment by gnufied** [comment]
@yuvipanda can you elaborate on "pod gets killed" ? Previously for terminated pods but not deleted from api server, we never used to perform volume detach but this changed in https://github.com/kubernetes/kubernetes/issues/45191 .

**Comment by yuvipanda** [comment]
@jingxu97 we were running GKE, and I couldn't find a way to get logs of controllers unfortunately.

@gnufied we spawn one pod per user, and then the user can execute arbitrary code inside the pod (via a Jupyter Notebook). We have a script that would watch for users that are inactive, and perform a delete (via the k8s API) of their pods. We found that for a long (and intermittent?) time after that, the volumes would still be attached to the node in which the user's pod was running. So when the user's pod was re-created (maybe they became active again), we need to attach the same volume back to this pod, and *this* would fail with this message.

**Comment by yuvipanda** [comment]
@jingxu97 reached out to me, and I provided a repro case (https://gist.github.com/yuvipanda/0b6aa32192c35b960e91698e1c14690c)

**Comment by jingxu97** [comment]
@wawastein thanks for reporting the error. You mentioned job producing high number of faulty pods. Does each pod uses a different PVC so it creates a new volume? Thanks!

**Comment by wawastein** [comment]
@jingxu97 hi, no, job pods do not use or create any volumes. Problem was in misconfiguration, containers couldn't connect to DB and failed time and time again.

**Comment by yuvipanda** [comment]
I can't reproduce this on 1.7 btw. Can on 1.6

**Comment by jingxu97** [comment]
@yuvipanda I tried on both 1.6.4 and 1.7 cluster with your repro steps, but could not get the errors..

**Comment by wawastein** [comment]
Here we go again. 
Cluster 1.7.2
```
Multi-Attach error for volume "pvc-25580310-76bf-11e7-b22a-42010a84002d" Volume is already exclusively attached to one node and can't be attached to another
Unable to mount volumes for pod "imgs-640158079-lq5rg_imgs(cc617d27-76c1-11e7-b22a-42010a84002d)": timeout expired waiting for volumes to attach/mount for pod "imgs"/"imgs-640158079-lq5rg". list of unattached/unmounted volumes=[nginx-cache]
Error syncing pod
```

**Comment by jingxu97** [comment]
@wawastein could you please share more information about this issue, in what condition this error occurred?  If possible, could you also share the project, zone and cluster name information so that we could check the master log?

**Comment by wawastein** [comment]
@jingxu97 so the timeline was as follows:
1. I created 1 Gi PVC for using with nginx container.
2. Deployed the changed config, deploy was successful
3. Pushed new nginx image to registry and deployed once again
4. Got the error above. 

Project: superlocal-149713
Zone: europe-west1-b
Cluster name: staging-cluster-2

**Comment by jingxu97** [comment]
@wawastein I checked the master log and found the following related information

```
kube-controller-manager.log-20170802-1501632000:I0801 13:41:43.693416       5 gce_util.go:144] Successfully created GCE PD volume gke-staging-cluster-2--pvc-25580310-76bf-11e7-b22a-42010a84002d
kube-controller-manager.log-20170802-1501632000:I0801 13:41:44.494282       5 pv_controller.go:1409] volume "pvc-25580310-76bf-11e7-b22a-42010a84002d" provisioned for claim "imgs/imgs-nginx-cache"
kube-controller-manager.log-20170802-1501632000:I0801 13:41:44.500007       5 pv_controller.go:718] volume "pvc-25580310-76bf-11e7-b22a-42010a84002d" entered phase "Bound"
kube-controller-manager.log-20170802-1501632000:I0801 13:41:44.500046       5 pv_controller.go:853] volume "pvc-25580310-76bf-11e7-b22a-42010a84002d" bound to claim "imgs/imgs-nginx-cache"
kube-controller-manager.log-20170802-1501632000:I0801 13:52:45.861876       5 reconciler.go:272] attacherDetacher.AttachVolume started for volume "pvc-25580310-76bf-11e7-b22a-42010a84002d" (UniqueName: "kubernetes.io/gce-pd/gke-staging-cluster-2--pvc-25580310-76bf-11e7-b22a-42010a84002d") from node "gke-staging-cluster-2-pool-1-bb497dff-9mms" 
kube-controller-manager.log-20170802-1501632000:I0801 13:52:53.731639       5 operation_generator.go:271] AttachVolume.Attach succeeded for volume "pvc-25580310-76bf-11e7-b22a-42010a84002d" (UniqueName: "kubernetes.io/gce-pd/gke-staging-cluster-2--pvc-25580310-76bf-11e7-b22a-42010a84002d") from node "gke-staging-cluster-2-pool-1-bb497dff-9mms" 
kube-controller-manager.log-20170802-1501632000:W0801 14:00:38.804960       5 reconciler.go:262] Multi-Attach error for volume "pvc-25580310-76bf-11e7-b22a-42010a84002d" (UniqueName: "kubernetes.io/gce-pd/gke-staging-cluster-2--pvc-25580310-76bf-11e7-b22a-42010a84002d") from node "gke-staging-cluster-2-pool-1-bb497dff-rqsz" Volume is already exclusively attached to one node and can't be attached to another
```
From the log we can see, around 13:52:53 the pvc is first attached to node gke-staging-cluster-2-pool-1-bb497dff-9mms. Later around 14:00:38, reconciler tries to attached this pvc to a different node and failed since it is still attached to the old node. The problem is here that the old pod is not deleted so the volume is still attached and the new pod is trying to attach then failed. 

From the deployment doc https://kubernetes.io/docs/concepts/workloads/controllers/deployment/,
"For example, if you look at the above Deployment closely, you will see that it first created a new Pod, then deleted some old Pods and created new ones. It does not kill old Pods until a sufficient number of new Pods have come up, and does not create new Pods until a sufficient number of old Pods have been killed. It makes sure that number of available Pods is at least 2 and the number of total Pods is at most 4."

I haven't looked at the deployment controller in detail, but if the new pod failed to start because of volume problem and controller does not kill the old pod, it will struck. 

I also notice that in your master controller log, there are lots of errors like the following, not sure whether they are relevant or not.
```
E0801 13:52:19.659620       5 horizontal.go:206] failed to query scale subresource for Deployment/default/dj: deployments/scale.extensions "dj" not found
E0801 13:52:19.668547       5 horizontal.go:206] failed to query scale subresource for Deployment/default/puma: deployments/scale.extensions "puma" not found
E0801 13:52:26.056806       5 horizontal.go:206] failed to compute desired number of replicas based on listed metrics for Deployment/deals-production/cloudsqlproxy: failed to get cpu utilization: missing request for cpu on container cloudsqlproxy in pod deals-production/cloudsqlproxy-795806673-0g5ch
E0801 13:52:27.566351       5 horizontal.go:206] failed to compute desired number of replicas based on listed metrics for Deployment/staging/rpush: failed to get cpu utilization: missing request for cpu on container rpush in pod staging/rpush-196916759-l2p29
E0801 13:52:29.141446       5 horizontal.go:206] failed to compute desired number of replicas based on listed metrics for Deployment/imgs/imgs: failed to get cpu utilization: missing request for cpu on container app in pod imgs/imgs-3690798063-ct914
I0801 13:52:45.765722       5 replica_set.go:455] Too few "imgs"/"imgs-557785410" replicas, need 1, creating 1
```
I will check with workload team to see whether there is a problem during deployment update.

**Comment by wawastein** [comment]
@jingxu97 the last log messages confused me too, I though it might be because most of the time those pods are idle and don't use resources. HPA ones are related to deleted deployments. 

On the bound PVC however, it's at least counter intuitive. If new pod is scheduled to new node, maybe there ought to be be a check for any detachable volumes of the old pod first.

**Comment by jingxu97** [comment]
@wawastein the scheduler and volume manager are completely separated. When scheduler schedule the pod it will not know whether the volume used by the pod is still attached to some node or not. But normally, old pod should be deleted at some point, so that volume will be detached from the old node, even though it might happen a little bit after the new pod is created

**Comment by jingxu97** [comment]
@wawastein  Could you check the comment here to see whether following the steps could solve your problem? https://github.com/kubernetes/kubernetes/issues/48968#issuecomment-315490408

**Comment by dfcowell** [comment]
I've had this same problem pop up when attempting to schedule single-replica deployments after VM migrations of my nodes on GCP.

Eventually the scheduler gives up trying to reschedule the pod and I have to delete it manually to resolve the issue.

I'm going to try recreating the deployments with strategy: Replace and see if that helps, but I'll report back in this issue if it happens again and I can provide a timestamp, node, project etc.

**Comment by andrewhowdencom** [comment]
I'm noticing this during lots of deploys. Maybe there's a timeout between switching disks between machines, or some other sort of sync loop?

**Comment by wawastein** [comment]
@jingxu97 I'll try it on the new deployment. But I can't really force reschedule for test, I'll just sit there and hope it doesn't happen.

**Comment by wawastein** [comment]
I can confirm that following works:

```
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
```
While `type: Recreate` **does not**.

It still feels clumsy: it does not prevent the situation from happening, but if I understand right, just recreates pod until it gets on "right" node, where the volume was mounted. I can see pod fail after deployment due to volume being stuck with another node, but after a restart or two pod starts working.

**Comment by dfcowell** [comment]
@wawastein are you saying that this gives a **faster recovery time** than `type: Recreate` or that `type: Recreate` just **doesn't work at all**?

I'm seeing a lot of success with `type: Recreate` bringing downtime from interminable (hours, in the worst test case) to 2-3 minutes downtime. If that configuration gives better performance than that I would definitely be interested.

**Comment by wawastein** [comment]
@dfcowell for me `Recreate` didn't work. Maybe I noticed only broken cases, but that's still indicative. With `Recreate` I've had hung deployments and needed to delete pod manually couple of times until it started to work. With `RollingUpdate` I had less than a minute of recovery time yesterday. I will be watching the situation and will post new evidence if I catch any.

**Comment by jingxu97** [comment]
@wawastein "Recreate" strategy means that All existing Pods are killed before new ones are created . So this strategy should work since delete old pod will make sure volume is detached first. When you see hung deployment, could you please use kubectl to check whether the old pod gets deleted? Thanks!

**Comment by wawastein** [comment]
@jingxu97 I'll make sure to look at it if I notice it again

**Comment by jingxu97** [comment]
@dfcowell Could you please provide more details about your failed cases? Are you doing the update of pods or your nodes are migrated (i.e., nodes are deleted and recreated?) Also the kubernetes version you are using? Thanks!

**Comment by dims** [comment]
@saad-ali @kubernetes/sig-storage-bugs Do we still need this fixed? (in 1.8)

**Comment by jingxu97** [comment]
@dims I want to keep this open because we might want to fix something related to this issue. Still working on it.

**Comment by dims** [comment]
@jingxu97 - y, we are already one week late for 1.8 please keep that in mind :)

**Comment by goindwalia** [comment]
I am facing the same on AWS using Kops, issue is not related to GCP but in general. I'll try with rolling update strategies mentioned above by @saad-ali .

**Comment by jingxu97** [comment]
@goindwalia To help us identify the root cause of your issue, could you please provide more details about your setup? If kube controller log is available, that would be also very helpful! Thanks!

**Comment by saad-ali** [comment]
Moving out of 1.8 milestone to unblock release.

**Comment by tadas-subonis** [comment]
And I had the same issue (or very similar) on Azure cloud. Deployment was using a rollingupdate strat (that's now changed) and it got stuck when the pod has moved to another host.

```
Conditions:
  Type           Status
  Initialized    True
  Ready          False
  PodScheduled   True
Volumes:
  rabbitmq-disk:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  rabbitmq-disk-5g
    ReadOnly:   false
  default-token-78pkg:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-78pkg
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     <none>
Events:
  Type     Reason                 Age                 From                  Message
  ----     ------                 ----                ----                  -------
  Normal   Scheduled              37s                 default-scheduler     Successfully assigned rabbitmq-deployment-6c85464c56-jrnjq to kube-node-2
  Normal   SuccessfulMountVolume  36s                 kubelet, kube-node-2  MountVolume.SetUp succeeded for volume "default-token-78pkg"
  Warning  FailedAttachVolume     34s (x25 over 37s)  attachdetach          Multi-Attach error for volume "pvc-b8bcc7f8-a9c4-11e7-8131-000d3a2164cd" Volume is already exclusively attached to one node and can't be attached to another
```

**Comment by jingxu97** [comment]
status/approved-for-milestone

**Comment by jingxu97** [comment]
@tadas-subonis Could you give more details about your failure? Is this Recreate or RollingUpdate strategy?

**Comment by wawastein** [comment]
We've got an incident again today. InfluxDB pod with volume failed and stuck in `Terminating` state. After I pressed delete on the UI, new one started to fire up (with this strategy:
```
strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
```
) and old just was hanging there:
```
NAME                               READY     STATUS              RESTARTS   AGE
yadayada-influxdb-4239716081-1s4xr   2/2       Terminating         0          4h
yadayada-influxdb-4239716081-plcx8   0/2       ContainerCreating   0          1m
```
Then I forcefully removed old one (`--grace-period=0 --force`), but it didn't help, since I still had to delete a couple of new pods because none of them could pick up the volume. I started thinking about cordoning the node with the volume and draining it, but then at last it started working.

**Comment by jingxu97** [comment]
@wawastein it would be easier to debug with controller master log. Do you mind to share the log with us?

**Comment by wawastein** [comment]
@jingxu97 last time you retrieved them for me, here's credentials again
Project: superlocal-149713
Zone: europe-west1-b
Cluster name: staging-cluster-2

**Comment by jingxu97** [comment]
@wawastein I see the following error message related to the issue

I1018 16:19:34.321606       6 graph_builder.go:438] add [v1/Pod, namespace: deals-production, name: deals-production-influxdb-4239716081-dzxnm, uid: 4831890c-b41f-11e7-b5f7-42010a840048] to the attemptToDelete, because it's waiting for its dependents to be deleted
I1018 16:19:34.321641       6 garbagecollector.go:288] processing item [v1/Pod, namespace: XXX, name: XXX-influxdb-4239716081-dzxnm, uid: 4831890c-b41f-11e7-b5f7-42010a840048]
I1018 16:19:34.326285       6 garbagecollector.go:400] remove DeleteDependents finalizer for item [v1/Pod, namespace: XXX, name:XXX-influxdb-4239716081-dzxnm, uid: 4831890c-b41f-11e7-b5f7-42010a840048]

I think even force delete does not work for you because of DeleteDependents finalizer. Do you have some finalizer set up?

**Comment by wawastein** [comment]
@jingxu97 not that I'm aware of, only if GKE comes bundled with one.

**Comment by jingxu97** [comment]
@wawastein https://kubernetes.io/docs/concepts/workloads/controllers/garbage-collection/, this doc explained something related.
The problem you had seems like for some reason the pod is failed to delete quickly which causes volume cannot be detached. But this is not an issue for attach_detach controller since it can only trigger detach after pod is terminated.

**Comment by andrewhowdencom** [comment]
I managed to reproduce a similar condition in which I opened a shell inside the disk mount (where the container is chrooted), and started modifying stuff from the host.

I needed to do this because the disk was full, and I needed to clear some stuff but couldn't in the container as the process boot looped. But I deleted the container before leaving that shell (with the CWD being ${CHROOT_DIR})

This caused the unmounter to loop extremely quickly, attempting to unmount the disk. This was accurately reflected by k8s. However, notably, even once I left the shell (and left it free to be unmounted) k8s still appeared to struggle to unmount it. IIRC it worked eventually, but there was quite some iterations before it did.

Perhaps some sort of stale open file or something similar would explain this? It would also go some way to explaining why it's non-deterministic, as it depends on the application shutdown (crash?) behaviour.

**Comment by mofirouz** [comment]
I'd like to report a problem here as well but on 1.8.3-gke.0. I am however using a StatefulSet and this occured while resizing the StatefulSet from 1 replica to 3 replicas. My SS spec is as follows:

```
apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  namespace: project
  name: project
  labels:
    version: "2"
    statefulset: project
    project: project
    account: account
spec:
  serviceName: "project"
  replicas: 1
  selector:
    matchLabels:
      version: "2"
      app: project
      project: project
      account: account
  template:
    metadata:
      labels:
        version: "2"
        app: project
        project: project
        account: account
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: project-standard-pool
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - project
              topologyKey: kubernetes.io/hostname
      containers:
        - name: project
          image: ...
          volumeMounts:
            - name: datadir
              mountPath: /data
            - name: logdir
              mountPath: /logs
          resources:
            requests:
              memory: "5120Mi"
          env:
            - name: "COCKROACH_METRICS_SAMPLE_INTERVAL"
              value: "1000h"
            - name: "COCKROACH_SKIP_ENABLING_DIAGNOSTIC_REPORTING"
              value: "true"
          command:
            - "/bin/bash"
            - "-ecx"
            - ...
      terminationGracePeriodSeconds: 60
      volumes:
        - name: datadir
          persistentVolumeClaim:
            claimName: datadir
        - name: logdir
          emptyDir: {}
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
    - metadata:
        name: datadir
      spec:
        storageClassName: "project-ssd-storage"
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: 50Gi
```

```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: project-ssd-storage
  version: "2"
provisioner: kubernetes.io/gce-pd
reclaimPolicy: Delete
parameters:
  type: pd-ssd
```

Please note that after a few hours (more than 6hours), this problem resolved itself but the pods and StatefulSet were left in a completely broken state where their state were `Waiting: CrashLoopBackOff`.

**Comment by lunemec** [comment]
Hi, I've run into this issue as well.
We are using the persistent volume to store user uploaded files, much like the  [wordpress example in the google cloud documentation.](https://cloud.google.com/kubernetes-engine/docs/tutorials/persistent-disk)

None of the solutions presented work (strategy Recreate or maxSurge: 0). Both caused the new pod being stuck in ContainerCreating stage locked while waiting on volume mount (even the old pod was removed).

The issue was fixed by deleting the deployment entirely and applying it again. This however leads to **outage** which is terrible for production purposes (which we thought kubernetes should solve). I think these disadvantages should be NOTED in the documentation wery clearly.

Also since this will always lead to outage (unless fixed some other way) maybe kubernetes/GCE should provide some easy way to run GlusterFS or NFS mounted persistent volumes, which would enable users to have persistent storage *and* update their app without outage.

**Comment by msau42** [comment]
Hi @mofirouz, typically if you see the event 'Waiting: CrashLoopBackOff', it means that the volumes did successfully get mounted, but your containers had trouble coming up.  If you can still reproduce this problem, let's try to debug in a different issue.  This issue is specifically for tracking nuances regarding using Deployments and GCE PD.

**Comment by msau42** [comment]
Hi @lunemec, if you use GCE PD as ReadWriteOnce with Deployments, you will have downtime no matter what because your GCE PD can only be attached to one node at a time.  So it's better to architect your solution to use a many reader/writer volume (like nfs/gluster, or GCE PD as read only) + multiple pod replicas if you need availability.  I will update the docs to include best practices with ReadWriteOnce volumes.

Now, that being said, there appears to be some issues with the suggested gce pd deployment config with replicas = 1, strategy recreate, and max surge 0.  We'll try to investigate this further with a few experiments:
* Deleting the pod manually
* Updating the deployment
* Tainting the node to cause pods to get evicted
* Stressing the node to cause pods to get evicted

**Comment by mofirouz** [comment]
@msau42 The pods failing to start was caused by a bad update to the pod command line caused by an internal system that we use. But this is beside the issue at hand...

The issue is that we *need* to use StatefulSets because we run a database with sensitive data replication requirements and cannot have pods being out of action for hours / undetermined amount of time while Kube / GKE sorts itself out.

**Comment by msau42** [comment]
Hi @mofirouz, did you also see the issue being discussed here, where the volume mounts are failing and never recovering because the GCE PD never gets detached from the old node?

**Comment by mofirouz** [comment]
@msau42 Yep I experienced the same thing and I mentioned it. I don't know why in my case it bounced back after some hours (more than 13hrs!) - I suspect maybe an on-site GCE engineer manually detached the disk?

**Comment by msau42** [comment]
Hi @mofirouz sorry I missed it from your original comment.  I only see that you said the error was `Waiting: CrashLoopBackOff`.  This error occurs after the volume has been successfully mounted, and indicates that your container is crashing for some reason.  So I want to make sure we're not confusing two different issues here.  It is normal to see a FailedMount event for a few seconds, but once the volume has been mounted, a SuccessfulMount event should be posted, and the Pod bringup will continue to the next phase where it brings up the containers.

**Comment by jakirpatel** [comment]
I am facing similar issue for statefulsets. I have attached the PV through PVC in GKE. But when the replicas are more than 1, the rest pod will go in waiting: the crashloopbackoff state. 

Any progress on this issue?

**Comment by msau42** [comment]
Hi @jakirpatel, crashloopbackoff generally means that the the volume is successfully mounted, but your container is crashing.  You'll need to check the logs of your container to see why it's crashing.

**Comment by msau42** [comment]
Can you post the events you see with 'kubectl describe pod <pod>'?

**Comment by davidz627** [comment]
I have looked into different failure scenarios with our recommended settings and have the following conclusions:

Note: This may not be an exhaustive list of failure scenarios. Please contact me if you are experiencing issues with a different scenario.

|                              | No deployment strategy       | Deployment strategy: Recreate | Deployment strategy: Rolling update (maxSurge: 0, maxUnavailable: 1) |
|------------------------------|------------------------------|-------------------------------|----------------------------------------------------------------------|
| Deleting pod manually        | Successful new pod           | Successful new pod            | Successful new pod                                                   |
| Updating deployment          | Expected Error: multi-attach | Successful new pod            | Successful new pod                                                   |
| Tainting node to evict pods  | Successful new pod           | Successful new pod            | Successful new pod                                                   |
| Node is killed               | Successful new pod           | Successful new pod            | Successful new pod                                                   |
| Stressing node to evict pods | Successful new pod           | Successful new pod            | Successful new pod                                                   |

**Comment by mofirouz** [comment]
@davidz627 This seems to be inline with what I've experienced as well. The multi-attach error happened when I was updating the StatefulSet and caused pods to be reshuffled on nodes.

**Comment by msau42** [comment]
@davidz627 can you also try this experiment with statefulsets?  Theoretically, you should not see multi-attach errors with StatefulSets because the pod must be completely deleted before a new pod with the same name can be recreated.

@mofirouz if you could paste your full pod events showing the CrashLoopBackOff, that would be helpful in triaging.

**Comment by davidz627** [comment]
Also tested with stateful sets with 3 replicas. Used volumeClaimTemplates with gce-pd. Here are the results

|                              | Stateful Set                                          |
|------------------------------|-------------------------------------------------------|
| Deleting pod manually        | Successful new pods                                   |
| Updating stateful set        | Successful new pods                                   |
| Tainting node to evict pods  | Successful new pods                                   |
| Node is killed               | Successful new pods                                   |
| Stressing node to evict pods | https://github.com/kubernetes/kubernetes/issues/57531 |

**Comment by plkokanov** [comment]
/remove-lifecycle rotten

Hi, we experienced the same problem with kubernetes 1.9.6:

**Kubernetes version (use kubectl version):**
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-27T00:13:02Z", GoVersion:"go1.9.4", Compiler:"gc", Platform:"darwin/amd64"}

Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-03-21T15:13:31Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

**Cloud provider or hardware configuration**: GCE

**Some more details:** We use a statefulset for our POD, configured with RollingUpdate strategy.

Pod was restarted from node1 to node2 and stuck in ContainerCreating state due to 
```
AttachVolume.Attach failed for volume “pvc-id” : googleapi: Error 400: The disk resource ‘projects/blabla/zones/blablazone/disks/gcp-dynam-pvc-id’ is already being used by ‘projects/blabla/zones/blablazone/instances/node1’
```

**controller-manager logs:**
```
I0515 18:04:22.207470       1 reconciler.go:287] attacherDetacher.AttachVolume started for volume "pvc-id" (UniqueName: "kubernetes.io/gce-pd/gcp-dynam-pvc-id) from node "node2"

E0515 18:04:26.778812       1 gce_op.go:88] GCE operation failed: googleapi: Error 400: The disk resource 'projects/blabla/zones/blablazone/disks/gcp-dynam-pvc-id' is already being used by 'projects/blabla/zones/blablazone/instances/node1'

E0515 18:04:26.778879       1 attacher.go:92] Error attaching PD "gcp-dynam-pvc-id" to node "node2": googleapi: Error 400: The disk resource 'projects/blabla/zones/blablazone/disks/gcp-dynam-pvc-id' is already being used by 'projects/blabla/zones/blablazone/instances/node1'

E0515 18:04:26.778969       1 nestedpendingoperations.go:263] Operation for "\"kubernetes.io/gcp-dynam-pvc-id\"" failed. No retries permitted until 2018-05-15 18:06:28.778939119 +0000 UTC m=+19053.925176613 (durationBeforeRetry 2m2s). Error: "AttachVolume.Attach failed for volume \"pvc-id\" (UniqueName: \"kubernetes.io/gce-pd/gcp-dynam-pvc-id") from node \"node2\" : googleapi: Error 400: The disk resource 'projects/blabla/zones/blablazone/disks/gcp-dynam-pvc-id' is already being used by 'projects/blabla/zones/blablazone/instances/node1'"
```
After checking for volumesAttached and volumesInUse for both nodes we saw:
* **on node 1** there were no volumesAttached and no volumesInUse
* **on node 2** there were no volumesAttached, however there was one volumesInUse:
    ``` 
    volumesInUse:
        gcp-dynam-pvc-id
    ```

By draining node 2 and having the POD restart on node 1 (happened by accident since we have more than 2 nodes in our cluster) the problem was fixed

Due to the requirement of a manual fix there is some downtime and this is a critical POD for our cluster

**Comment by msau42** [comment]
@plkokanov to confirm, you saw this problem when you issued a rolling update on your statefulset?

**Comment by jingxu97** [comment]
@plkokanov would you mind to share us the full  controller-manager log to us so we can help triage? You see VolumeInUse in node 2 is normal because controller try to mount gcp-dynam-pvc-id on node 2. The strange thing is why volume is still attached to node 1.

**Comment by plkokanov** [comment]
@msau42 we saw it after the pod was restarted. The reason for the restart was most likely an unsuccessful liveliness probe. I'll make sure to post the exact reason as soon as I manage to reproduce it.
@jingxu97 can't get the controller-manager logs from when the issue happened. I'll see if I can do anything about that.

**Comment by pv93** [comment]
This error is still occuring to me, running GKE 1.9.6-1. Running a pod with a gce-pd PVC. The odd thing is that this error pops up immediately on creation of the pod and its associated PVC. My guess is that the old one has not been deleted in GCP, even though it's gone from Kubernetes and from GCE console. This is a really big problem and is making it impossible to run any stateful apps in my cluster.

**Comment by jingxu97** [comment]
@pv93, sorry to reply late. Could you please let us know more details about your issue? You mentioned -you deleted old pod and PVC. Did you use "--forcedelete" and "--grace-period=0" option? Otherwise, the new pod or PVC (if using the same name as the old one) could not be created without the old one being cleaned up and deleted. For PVC, unless you change the Reclaim policy, by default, if PVC is deleted, the volume should be also deleted. Your new PVC should create a new volume.
