### ISSUE TITLE
Validate selector's value when creating Pods

### ISSUE THREAD

**Issue by k82cn** [kubernetes/kubernetes#49096]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:
In `ValidateLabelSelectorRequirement`, it only validates selector's name; it's better to also validate selector's value, so the other components can use selector directly.

xref https://github.com/kubernetes/kubernetes/pull/46952

**Comment by k82cn** [comment]
> What objects use this validation?

The following object using this func to do the validation; all label selector I think.

PersistentVolumeClaimSpec.Selector, PodAffinityTerm.LabelSelector, StatefulSetSpec.Selector, JobSpec.Selector, DaemonSetSpec.Selector, DeploymentSpec.Selector, ReplicaSetSpec.Selector, NetworkPolicySpec.PodSelector, NetworkPolicySpec.PodSelector, NetworkPolicyPeer.NamespaceSelector, NetworkPolicySpec.PodSelector, NetworkPolicySpec.PodSelector, NetworkPolicyPeer.NamespaceSelector, PodDisruptionBudgetSpec.Selector, PodPresetSpec.Selector

> What will tightening validation do if existing objects have invalid values?

This PR will reject Pod creation; no impact to existing object.

> Will it prevent status updates by controllers?

nop; used in validation

> Do the things that automatically create/update this object tolerate validation rejections well? (backoff, surface error to user)

This return error to its client, so there'll be an error to the user.

**Comment by liggitt** [comment]
> This PR will reject Pod creation; no impact to existing object.

It will also reject updates to all the listed object types if they are already persisted with a bad spec. That can cause problems for controllers, and can wedge things like garbage collection (which does patch/update calls to remove finalizers) resulting in objects that cannot be deleted.

I don't think we can tighten the validation broadly across all the objects. I could *maybe* see tightening it just on create, in order to avoid breaking clusters with existing objects, but that would make the validation code considerably more complicated.

**Comment by k82cn** [comment]
That'll avoid duplicated validation in all components if apiserver can guard it. 

> maybe see tightening it just on create, in order to avoid breaking clusters with existing objects,

I think that's an option, just not sure the complexity :); and ask user to correct the bad sepc, similar the process of "deprecated". WDTY?
