### ISSUE TITLE
REST api - what is the meaning of spec and status sections for namespace entity?

### ISSUE THREAD

**Issue by abonas** [kubernetes/kubernetes#4933]
they seem to be empty after creating a namespace

**Comment by bgrant0607** [comment]
This is future-proofing, as well as following our api conventions.
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/api-conventions.md

@derekwaynecarr

**Comment by abonas** [comment]
@bgrant0607 I'm aware of the api conventions, but the properties should have relevance and meaning to the object they're in, not to be present automatically for future/maybe/simply because others have it.
If they're needed, they should be populated with something that has value to the user and to the system, if they are not needed now, imho they shouldn't be there, and should be added when or if they become relevant.

**Comment by derekwaynecarr** [comment]
Both spec and status will be filled in by a PR this week with more design.

A namespace will have a Status.Phase to denote if it's active or terminating.

A namespace will have a Spec to denote its Finalizers.  Finalizers are the list of objects that may observe when an object is undergoing graceful termination in order to perform their own cleanup before the Namespace could be terminated.

Basically, more data will be used soon when i do graceful termination of a namespace.

**Comment by baldwinSPC** [comment]
@derekwaynecarr I'm seeing this issue still running the following version: 

Client Version: version.Info{Major:"0", Minor:"11+", GitVersion:"v0.11.0-dirty", GitCommit:"18ddff0eb6bc069b41832ce47d19b5b89cfb26e3", GitTreeState:"dirty"}
Server Version: version.Info{Major:"0", Minor:"11+", GitVersion:"v0.11.0-dirty", GitCommit:"18ddff0eb6bc069b41832ce47d19b5b89cfb26e3", GitTreeState:"dirty"}

I create a namespace by passing the following to the v1beta3 endpoint: 

{
   "kind":"Namespace",
   "spec":{
      "finalizers":[
         "openshift.com/origin",
         "kubernetes"
      ]
   },
   "apiVersion":"v1beta3",
   "metadata":{
      "labels":{
         "name":"production"
      },
      "name":"production3"
   }
}

ref. doc: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/design/namespaces.md

You'll note I'm using a corrected version the JSON. The example has labels external from metadata. 

I'm seeing the finalizers are not showing up in the namespace. 

kubectl get --api-version="v1beta3" --output=json namespaces production3
{
    "kind": "Namespace",
    "apiVersion": "v1beta3",
    "metadata": {
        "name": "production3",
        "selfLink": "/api/v1beta3/namespaces/production3",
        "uid": "793b845e-d8ad-11e4-b676-22000a1c08f3",
        "resourceVersion": "2427",
        "creationTimestamp": "2015-04-01T20:27:10Z",
        "labels": {
            "name": "production"
        }
    },
    "spec": {},
    "status": {}
}

**Comment by bgrant0607** [comment]
@baldwinSPC Could you please try a more recent version of kubectl? I'm not sure 0.11 was new enough (and we aborted that release).

**Comment by baldwinSPC** [comment]
@bgrant0607 

running: 

Client Version: version.Info{Major:"0", Minor:"13", GitVersion:"v0.13.0", GitCommit:"8d8b9b9a782a9079e6d91ba0e81d4c10e8445941", GitTreeState:"clean"}
Server Version: version.Info{Major:"0", Minor:"13", GitVersion:"v0.13.0", GitCommit:"8d8b9b9a782a9079e6d91ba0e81d4c10e8445941", GitTreeState:"clean"}

seeing this now: 

```
{
    "kind": "Namespace",
    "apiVersion": "v1beta3",
    "metadata": {
        "name": "production3",
        "selfLink": "/api/v1beta3/namespaces/production3",
        "uid": "044dfeae-d8c2-11e4-9afe-22000ae993ed",
        "resourceVersion": "368",
        "creationTimestamp": "2015-04-01T22:54:13Z",
        "labels": {
            "name": "production"
        }
    },
    "spec": {},
    "status": {
        "phase": "Active"
    }
}

So, status seems to be filled in now, but the spec is still missing the finalizers. I'll move to v0.14.0 and test there; however, that version has an issue when registering nodes using kube-register (https://github.com/kelseyhightower/kube-register/issues/13) so I will register manually and test. Just wanted to pass this along.

**Comment by derekwaynecarr** [comment]
Phase went in before the finalizers did. 

You will only see a finalizer field on newly created namespaces.

I will track down what version had the change needed.  

Note: there was a period last week where namespace termination did not work right ( it would always stay in terminating state).  That was fixed today in this PR: 

https://github.com/GoogleCloudPlatform/kubernetes/pull/6246

**Comment by bgrant0607** [comment]
@smarterclayton @thockin @lavalamp @vishh Example problem due to decode/encode in the client (#3955).

**Comment by goltermann** [comment]
We’re going through old support issues and asking everyone to direct your questions to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes). 

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases. 

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.
