### ISSUE TITLE
libapparmor.so.1 not available to containers?

### ISSUE THREAD

**Issue by zmeggyesi** [kubernetes/kubernetes#49385]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**: I tried to use a Kubernetes pod to build Docker images with Jenkins, using the command `docker build`.

**What you expected to happen**: I expected the build to run properly, resulting an a compiled docker image

**How to reproduce it (as minimally and precisely as possible)**: execute `docker build` in a Kubernetes pod

**Anything else we need to know?**: Kuberentes 1.6.4 did not produce the problem, 1.6.6 and 1.7.0 all do. Privileged and non-privileged pods exhibit the same error message (`docker: error while loading shared libraries: libapparmor.so.1: cannot open shared object file: No such file or directory`).

**Environment**:
- Kubernetes version (use `kubectl version`): 1.7.0
- Cloud provider or hardware configuration**: Google Container Engine
- OS (e.g. from /etc/os-release): Container OS
- Kernel (e.g. `uname -a`): `Linux ${HOSTNAME_REDACTED} 4.4.52+ #1 SMP Thu Jun 15 15:23:01 PDT 2017 x86_64 Intel(R) Xeon(R) CPU @ 2.60GHz GenuineIntel GNU/Linux`
- Install tools:
- Others: Jenkins Docker image (https://hub.docker.com/r/jenkins/jenkins/)

**Comment by zmeggyesi** [comment]
@kubernetes/sig-node-docker

**Comment by kelveden** [comment]
Getting this exact same problem with Jenkins running in a 1.7.1 cluster.

**Comment by mhelmer** [comment]
I had the same problem when running docker in docker with Jenkins kubernetes plugin. I'm assuming you are running docker in docker with the `/usr/bin/docker` and `/var/run/docker.sock` mounted as host volumes. I would say the issue here is not a bug in kubernetes or jenkins, but a configuration issue.

It seems like the older version of the docker binary was not linked against any shared libraries that were unavailable inside your container. However, the new one seems to be linked against `libapparmor.so.1` for instance.

You can work around by adding host volume mounts for the necessary shared libraries. It should also work to build a new docker image for `jnlp` (or whatever you're using to build images in jenkins) with a compatible version of docker installed. Then you should only need to mount `/var/run/docker.sock`.

**Comment by zmeggyesi** [comment]
@mhelmer 
In the end, it seems re-building the slave container by including `lxc` is a valid workaround. I tried linking the files via host mounts, but that did not seem to have any effect.

**Comment by mhelmer** [comment]
That might be an issue of different library paths on the host and docker image

Host Path: `/usr/lib64/libapparmor.so.1.3.0`
Mount Path: `/lib/x86_64-linux-gnu/libapparmor.so.1`

Anyway it doesn't seem like a great solution and building a new slave image is probably the right thing to do.
