### ISSUE TITLE
CRD and TPR doesn't support watching one single instance

### ISSUE THREAD

**Issue by mengqiy** [kubernetes/kubernetes#49424]
Follow https://kubernetes.io/docs/tasks/access-kubernetes-api/extend-api-third-party-resource/

1. Create a TPR `crontab`
2. Create an instance `my-new-cron-object`
3. Watch a single instance return 400. (watch a collection of TPR works)
```
$ kubectl get crontab my-new-cron-object -w
NAME                 KIND                            CRON SPEC    IMAGE
my-new-cron-object   CronTab.v1.stable.example.com   * * * * /5   my-awesome-cron-image
Error from server (BadRequest): the server rejected our request for an unknown reason (get crontabs.stable.example.com)
```

master and kubectl version: 1.7.1

CRD has the same issue.

/assign @enisoc

**Comment by enisoc** [comment]
@kubernetes/sig-api-machinery-bugs

**Comment by enisoc** [comment]
I was able to reproduce this with CRD on master. The problem is that kubectl implements a watch on a single object as a watch on the collection with a field selector that filters by `metadata.name`. However, field selectors don't work on CRD objects because they are stored as `Unstructured`, which does not support `ConvertFieldLabel`:

https://github.com/kubernetes/kubernetes/blob/84db0a94878abe9f04123f7e8a64fc5b741a82c1/staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/unstructured/unstructured.go?utf8=%E2%9C%93#L840

This method is used to transform the field selector from versioned to internal field names:

https://github.com/kubernetes/kubernetes/blob/84db0a94878abe9f04123f7e8a64fc5b741a82c1/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/rest.go?utf8=%E2%9C%93#L309

As a test, I bypassed that check for Unstructured objects, and watches on single CRD objects started working. Given that CRD doesn't support multiple versions anyway, it seems feasible to support this with a properly-targeted override of `ConvertFieldLabel` specific to CRD objects.

cc @deads2k

**Comment by deads2k** [comment]
If we could support name and namespace generally on all objects containing object meta, I think I'm in favor of the concept.

**Comment by enisoc** [comment]
I think it's feasible to fix this for CRD at some point. However, given that TPR is already gone in master, I don't think it's worth fixing for TPR unless it's somehow a regression in 1.7.

@mengqiy Do you have any objections to that?

**Comment by mengqiy** [comment]
Having CRD support is good enough for me and service catalog.
Will you backport the fix for CRD to 1.7?

**Comment by deads2k** [comment]
> Will you backport the fix for CRD to 1.7?

At this stage I wouldn't expect that since it isn't a regression (I don't think) for either extension mechanism.

**Comment by caesarxuchao** [comment]
cc @mbohlool

**Comment by kokhang** [comment]
I am also getting the same error when i try to watch CRDs and filter on a specific field. Im a currently using the `client-go/tools/cache.NewListWatchFromClient` to watch for CRDs.

On a related note, i noticed that the `NewListWatchFromClient()` takes a `fieldSelector`. Is there a way to pass a label selector so that i can watch CRDs using labels?

**Comment by kokhang** [comment]
Also is this issue slated for 1.8? (For CRDs that is)

**Comment by enisoc** [comment]
The general issue of supporting field selectors for CRD is tracked in #51046. I don't think it's slated for 1.8.

The methods on `ListWatch` should take a [ListOptions](https://godoc.org/k8s.io/apimachinery/pkg/apis/meta/v1#ListOptions), which can contain an optional `LabelSelector`.
