### ISSUE TITLE
Problem with pulling the images when basic auth is used in custom registry

### ISSUE THREAD

**Issue by dmnord** [kubernetes/kubernetes#49493]
@kubernetes/sig-auth-bugs

/kind bug
/sig auth

**What happened**:

Kubelet can't pull an basic image from docker-distribution repository, but at the same time a sandbox image (named 'pause') pulls normaly from the same repository. Repository stands behind a nginx, which uses a Basic-Auth for docker authentication. I see a message "no user/password was provided for basic authentication", when the Kublet tries to pull a basic image only!

I guess it's a bug!

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.1", GitCommit:"1dc5c66f5dd61da08412a74221ecc79208c2165b", GitTreeState:"clean", BuildDate:"2017-07-17T13:46:52Z", GoVersion:"go1.9beta2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.1", GitCommit:"1dc5c66f5dd61da08412a74221ecc79208c2165b", GitTreeState:"clean", BuildDate:"2017-07-17T13:46:52Z", GoVersion:"go1.9beta2", Compiler:"gc", Platform:"linux/amd64"}
- OS (e.g. from /etc/os-release): Fedora 25 x86_64
- Kernel (e.g. `uname -a`): 4.11.10-200.fc25.x86_64
- Install tools: Bare metall installation

**Comment by dmnord** [comment]
I have created file in my environment /var/lib/kubelet/.docker/config.json and this file helps to pull sandbox image!
```
{
	"auths": {
		"https://registry.domain.local/v1/": {
			"auth": "YWRtaW46MTIzNDU2Nzg="
		}
	}
}
```

Also I have got an error messages in my kubelet log file when the image from my test deploymemnt  pulls:
```
E0724 20:11:50.014248   15876 kuberuntime_manager.go:718] container start failed: ImagePullBackOff: Back-off pulling image "test"
E0724 20:11:50.014310   15876 pod_workers.go:182] Error syncing pod fbc22ba9-7074-11e7-881f-d0509997b30d ("test-deployment-4124448442-x57x8_default(fbc22ba9-7074-11e7-881f-d0509997b30d)"), skipping: failed to "StartContainer" for "test" with ImagePullBackOff: "Back-off pulling image \"test\""
```

**Comment by dmnord** [comment]
Everything works fine, but informativeness in kubernetes logs are very poor!

**Comment by maodage2005** [comment]
@dmnord
how do you fix this problem?

**Comment by worldsayshi** [comment]
https://xkcd.com/979/

**Comment by cbanek** [comment]
so I just ran into this myself.  I totally feel the linked and quite relevant xkcd, so I'll chime in here with the answer as it was for me.  I did have a password set, but the password (and therefore the basic auth string in the docker secret) was wrong.  Instead of saying something like incorrect password, it says no basic auth provided, even when it's trying to log in with that.  Given that you might have multiple repos and sets of creds, I guess it might try all of them even before giving up.

Now on to why my password is wrong.  Which will really grind your gears.  Apparently my password has a \ in it.  In the secret it's fine, I can look at the base64 encoded string, and all is well.  But if you go into the container, and look at it as an environment variable, it's added an extra \, to make it \\ and therefore a wrong password.  Thanks a lot.  I'm not sure if that's a bug or what possibly karma I've earned to lead me down this rabbithole.

As someone who may read this in the future, please have pity on me.  And remember, OP never delivers.

**Comment by huapox** [comment]
work with `/var/lib/kubelet/config.json`

you can just: ` cat /root/.docker/config.json > /var/lib/kubelet/config.json`

- ref1: https://blog.csdn.net/yujia_666/article/details/117998631  
- ref2: https://www.bookstack.cn/read/kubernetes-1.22-zh/dbc22809caac5e2d.md

```bash
# zh: 1.22-zh/dbc22809caac5e2d.md
Docker 将私有仓库的密钥保存在 $HOME/.dockercfg 或 $HOME/.docker/config.json 文件中。如果你将相同的文件放在下面所列的搜索路径中，kubelet 会在拉取镜像时将其用作凭据 数据来源：
    {--root-dir:-/var/lib/kubelet}/config.json
    {--root-dir:-/var/lib/kubelet}/.dockercfg
    {kubelet 当前工作目录}/config.json
    {kubelet 当前工作目录}/.dockercfg
    # 
    ${HOME}/.docker/config.json
    ${HOME}/.dockercfg
    /.docker/config.json
    /.dockercfg
    ########## 说明： 你可能不得不为 kubelet 进程显式地设置 HOME=/root 环境变量。
```
