### ISSUE TITLE
Volume reconciler duplicates attach/detach logic

### ISSUE THREAD

**Issue by jamiehannaford** [kubernetes/kubernetes#49503]
/kind bug

**What happened**:

We deployed a pod with a dynamic Cinder volume (i.e when a PVC is deployed, the Cinder volume driver creates and attaches a Cinder disk). When a node it's on is rebooted, the pod is rescheduled to another node. The volume controller then detaches the Cinder disk from the old node and attaches to the new one. However, instead of leaving it at that, the volume reconciler performs a bunch of additional, completely unexpected detach/attach operations which eventually leaves the pod in a crash loop. I'll give a run through of the lifecycle:

**Step 1: Initial set-up**
```
I0724 13:25:07.521306       1 reconciler.go:208] Started AttachVolume for volume "kubernetes.io/cinder/2e91ae43-5a0d-4ef4-85b1-6dd0c3021071" to node "jamie-terraform-worker-2"
I0724 13:25:09.937732       1 reconciler.go:208] Started AttachVolume for volume "kubernetes.io/cinder/2e91ae43-5a0d-4ef4-85b1-6dd0c3021071" to node "jamie-terraform-worker-2"
I0724 13:25:16.155696       1 reconciler.go:208] Started AttachVolume for volume "kubernetes.io/cinder/2e91ae43-5a0d-4ef4-85b1-6dd0c3021071" to node "jamie-terraform-worker-2"
``` 

**Step 2: Reboot occurs on `jamie-terraform-worker-2`**

**Step 3: Reconciler handles volume migration**

```
I0724 13:39:31.143183       1 reconciler.go:208] Started AttachVolume for volume "kubernetes.io/cinder/2e91ae43-5a0d-4ef4-85b1-6dd0c3021071" to node "jamie-terraform-worker-2"
I0724 13:41:17.605210       1 reconciler.go:208] Started AttachVolume for volume "kubernetes.io/cinder/2e91ae43-5a0d-4ef4-85b1-6dd0c3021071" to node "jamie-terraform-worker-1"
I0724 13:41:20.826216       1 reconciler.go:208] Started AttachVolume for volume "kubernetes.io/cinder/2e91ae43-5a0d-4ef4-85b1-6dd0c3021071" to node "jamie-terraform-worker-1"
I0724 13:41:23.638919       1 reconciler.go:208] Started AttachVolume for volume "kubernetes.io/cinder/2e91ae43-5a0d-4ef4-85b1-6dd0c3021071" to node "jamie-terraform-worker-1"
I0724 13:41:32.893545       1 reconciler.go:208] Started AttachVolume for volume "kubernetes.io/cinder/2e91ae43-5a0d-4ef4-85b1-6dd0c3021071" to node "jamie-terraform-worker-1"
I0724 13:41:40.173304       1 reconciler.go:208] Started AttachVolume for volume "kubernetes.io/cinder/2e91ae43-5a0d-4ef4-85b1-6dd0c3021071" to node "jamie-terraform-worker-1"
I0724 13:41:41.483245       1 reconciler.go:208] Started AttachVolume for volume "kubernetes.io/cinder/2e91ae43-5a0d-4ef4-85b1-6dd0c3021071" to node "jamie-terraform-worker-2"
I0724 13:41:44.728394       1 reconciler.go:208] Started AttachVolume for volume "kubernetes.io/cinder/2e91ae43-5a0d-4ef4-85b1-6dd0c3021071" to node "jamie-terraform-worker-2"
I0724 13:41:47.842169       1 reconciler.go:208] Started AttachVolume for volume "kubernetes.io/cinder/2e91ae43-5a0d-4ef4-85b1-6dd0c3021071" to node "jamie-terraform-worker-2"
I0724 13:41:52.364797       1 reconciler.go:208] Started AttachVolume for volume "kubernetes.io/cinder/2e91ae43-5a0d-4ef4-85b1-6dd0c3021071" to node "jamie-terraform-worker-2"
I0724 13:41:59.698795       1 reconciler.go:208] Started AttachVolume for volume "kubernetes.io/cinder/2e91ae43-5a0d-4ef4-85b1-6dd0c3021071" to node "jamie-terraform-worker-2"
I0724 13:42:24.401188       1 reconciler.go:173] Started DetachVolume for volume "kubernetes.io/cinder/2e91ae43-5a0d-4ef4-85b1-6dd0c3021071" from node "jamie-terraform-worker-2"
I0724 13:42:31.719502       1 reconciler.go:208] Started AttachVolume for volume "kubernetes.io/cinder/2e91ae43-5a0d-4ef4-85b1-6dd0c3021071" to node "jamie-terraform-worker-1"
I0724 13:42:37.685784       1 reconciler.go:208] Started AttachVolume for volume "kubernetes.io/cinder/2e91ae43-5a0d-4ef4-85b1-6dd0c3021071" to node "jamie-terraform-worker-1"
I0724 13:42:49.021248       1 reconciler.go:208] Started AttachVolume for volume "kubernetes.io/cinder/2e91ae43-5a0d-4ef4-85b1-6dd0c3021071" to node "jamie-terraform-worker-1"
```

I'm just selecting `reconciler.go` logs. For full logs, including `attacher.go`, see [here](https://gist.github.com/jamiehannaford/7507ef4e10cb8ff43639549256cbf689).

If we look at when the initial node (`worker-2`) was rebooted:

```
core@jamie-terraform-worker-2 ~ $ last -x reboot
reboot   system boot  4.12.2-coreos    Mon Jul 24 13:41   still running
reboot   system boot  4.11.2-coreos    Mon Jul 24 13:15 - 13:41  (00:25)
```

We can see it began the reboot cycle at 13:41, which is when the volume was migrated by the reconciler. Pods seem to have been rescheduled to the rebooted node 2 minutes later at 13:43.

My question is, why did the reconciler begin attaching to `worker-1`, then attach the same volume to `worker-2` around 20 seconds later when that node was not really schedulable? It then _detached_ from `worker-2`, then reattached to `worker-1`, which is what it did at the very beginning. Why did it attach to `worker-2` in the interim when it was completely unnecessary?

**What you expected to happen**:

When a node is rebooted and pods drained from it, I don't expect the volume manager to ever attach/detach old volumes back to it. The second the pod leaves I expect the cache to be updated.

**How to reproduce it (as minimally and precisely as possible)**:

- Set up 3 worker cluster using Container Linux
- Deploy a pod with a Cinder PV
- Reboot the node with the pod on
- More often than not, the pod will be rescheduled to another node but enter a crash loop

**Anything else we need to know?**:

The actual way this problem manifested itself is similar to https://github.com/kubernetes/kubernetes/issues/47548. The pod enters a crash loop because SELinux disallows relabelling RO mounts. The reason why Cinder/Nova mounts the volume is RO is unclear, but we think it's probably due to the race conditions in volume manager. For example, if the first mount is interrupted by the second unnecessary one, it becomes RO and the kubelet doesn't actually update the mount location to the new device path.

For the reboots we're using the https://github.com/coreos/container-linux-update-operator which drains the node, deletes all pods, then sends a reboot request to systemd. Full reboot cycle can be checked out [here](https://github.com/coreos/container-linux-update-operator/blob/master/pkg/agent/agent.go#L78). 

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.2", GitCommit:"922a86cfcd65915a9b2f69f3f193b8907d741d9c", GitTreeState:"clean", BuildDate:"2017-07-21T19:06:19Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.7+coreos.0", GitCommit:"c8c505ee26ac3ab4d1dff506c46bc5538bc66733", GitTreeState:"clean", BuildDate:"2017-07-06T17:38:33Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration:
Nova and Cinder

- OS (e.g. from /etc/os-release):
```
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1465.2.0
VERSION_ID=1465.2.0
BUILD_ID=2017-07-19-0414
PRETTY_NAME="Container Linux by CoreOS 1465.2.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
```

- Kernel (e.g. `uname -a`):
```
Linux jamie-terraform-worker-2 4.12.2-coreos #1 SMP Wed Jul 19 03:57:51 UTC 2017 x86_64 AMD Opteron 23xx (Gen 3 Class Opteron) AuthenticAMD GNU/Linux
```

**Comment by gnufied** [comment]
Can you search for string - "VerifyVolumesAreAttached" when the attach/detach controller falsely tried to attach volume to old node?

**Comment by jamiehannaford** [comment]
@gnufied No matches.  [Here](https://gist.github.com/jamiehannaford/b521fdd99858f4dde235b0f6b9f23119) are the full logs for that period in time.

**Comment by jamiehannaford** [comment]
@kubernetes/sig-storage-bugs

**Comment by jamiehannaford** [comment]
@saad-ali @gnufied Friendly ping 😄  FWIW I'm willing to do the work to fix this, I'd just like a heads up on the best place to look since I'm not that familiar with how the volume manager works.

**Comment by jingxu97** [comment]
@jamiehannaford Thank you for reporting the issue. Is that possible to share us the full log? Based on my current checking, I found out the issue might be related the following reasons.

1. Attach_detach controller has a syncState loop which will periodically checks whether the volume is actually attached to the node and update the cached actual state if the volume is no longer attached
2. In openstatck_volume, AttachDisk function will first check whether the volume is already attached or not. If the volume is already attached, but to a different node, it will issue DetachDisk.

So the following events happened during node reboot
1. Node reboot, syncState loop noticed that volume is no longer attached to "worker-2", it updated the actual state. Reconciler then tried to attache volume back to "worker-2" since desired state still has it.
2. Attach_detach controller got an update from pod that it (should be a new pod) is scheduled to worker-1 so reconciler try to attached volume to worker-1 but failed because the volume is currently being attached to "worker-2" from above step, so AttachDisk function from opernstatck_volume will issue a DetachDisk request to detach volume from worker-2 again
3. Step 2 might be repeated for several times
4. Attache_detach controller got an update that the original pod is deleted, so reconcile decides to detach volume from worker-2, so detach happened.
5. volume is finally attached to worker-1.

But there are a few things I am not sure that whether the old pod is evicted from worker-2 and a new pod is rescheduled to worker-1. Normally for a single pod, it will not be rescheduled unless you are using an replicaSet or statefulSet. But what I can see is we have the following problems need to be addressed
1. openstack_volume attachDisk function should not invoke DetachDisk function because it might be safe to detachDisk without checking whether it is mounted or not
2. syncState loop might be interfere with reconcile controller during node reboot. 
We will work on the this design issue.

**Comment by jamiehannaford** [comment]
@jingxu97 Thanks for the great response! To answer your first question, these pods are in a Deployment, so they will be rescheduled if a node is rebooted. I have a few questions:

1. So you're saying that the `AttachDisk` function in openstack_volumes should _not_ call DetachDisk because it should trust that the Attach_detach controller will do that? Or is there another reason?

2. If AttachDisk is called, and the volume is still being used (i.e. `if volume.AttachedServerId != ""`), what should openstack_volumes do instead? Just wait and retry, or fail?

3. If the syncState loop interferes with reconcile controller during reboot, will it take a lot of effort to fix this (is it possible for 1.8)? If not, is there anything we can do to make reboots safer? Since we're using CoreOS' reboot controller, I'm wondering if there's a way for it to wait until all PVs are rescheduled after this step: https://github.com/coreos/container-linux-update-operator/blob/master/pkg/agent/agent.go#L148-L159

**Comment by jingxu97** [comment]
@jamiehannaford please see comments below
1. Yes, AttachDisk function in openstack_volumes should not call DetachDisk because it does know whether the volume is still mounted or not. Attach_detach controller should take care of detachDisk and know when it is safe to detach
2. AttachDisk should fail if the volume is still being used. Attach_detach controller will retry
3. We already have some work for fix the unknown problem. But we want to revisit the design to see whether we can make it more stable. 
Since I don't have your full log, I am not sure what happened exactly. But strange thing is that volume should not be detached during node restart. So if your node is restarted within 5 minutes, pod will not be rescheduled at all, and volume should still be attached to the original node. Do you know how long it took for the node restart?

**Comment by jamiehannaford** [comment]
@jingxu97 Do you want to keep this issue open? Although #50042 has been merged, you also mentioned an ongoing design issue:

> syncState loop might be interfere with reconcile controller during node reboot. We will work on the this design issue.
