### ISSUE TITLE
Ingress Doesn't Return Adress (LXD)

### ISSUE THREAD

**Issue by myaspm** [kubernetes/kubernetes#49614]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
/kind bug
> /kind feature

**What happened**: I installed Kubernetes on localhost LXD. When trying to expose containers to outside network (outside cluster but still inside private company network) by ingress, ingress address column comes up empty. All my steps are from official tutorials/documentations. kubectl get events returns 

```
nginx-ingress-controller error: Operation cannot be fulfilled on ingresses.extensions "graylog-ing2": the object has been modified; please apply your changes to the latest version and try again
```

**What you expected to happen**: To see an IP adress which is accessible from outside cluster network.

**How to reproduce it (as minimally and precisely as possible)**: 
Install kubernetes on LXD. Deploy an image. Create a service for that application. Create an ingress for the service.

**Anything else we need to know?**: 

Installed on Ubuntu 16.04. Using LXD and Juju. Kubernetes is conjured up.

**Environment**:
- Kubernetes version (use `kubectl version`):  1.7.0
- Cloud provider or hardware configuration**:  LXD
- OS (e.g. from /etc/os-release): Ubuntu 16.04.2 LTS
- Kernel (e.g. `uname -a`): 4.4.0-31-generic
- Install tools:  conjure-up
- Others:

**Comment by thockin** [comment]
@aledbf

**Comment by aledbf** [comment]
@myaspm I used this guide https://kubernetes.io/docs/getting-started-guides/ubuntu/ as reference to reproduce the issue:

```console
Installed a vm in virtualbox (Ubuntu)
sudo usermod -a -G lxd $USER
sudo snap install conjure-up --classic
conjure-up kubernetes
```

- select core
- select new provider -> localhost
- select template defaults

The issue here is that the installation uses an old version of the nginx ingress controller (14 months to be exact) where there was no update status of the Ingress rule/s
To fix this you can remove the old rc running `kubectl delete rc nginx-ingress-controller` and use this example https://github.com/kubernetes/ingress/tree/master/examples/rbac/nginx to install a newer version

**Comment by myaspm** [comment]
I will try this, thanks a lot!

**Comment by aledbf** [comment]
@myaspm can we close this issue?
