### ISSUE TITLE
Handle cases where node /etc/resolv.conf uses a localhost DNS resolver

### ISSUE THREAD

**Issue by bowei** [kubernetes/kubernetes#49675]
It is common for some Linux distributions to run a local DNS cache as the name resolver, resulting in `nameserver 127.0.0.1` in `resolv.conf`. When this is propagated into the kube-dns container due to `DnsPolicy: Default`, this will result in a DNS lookup loop.

**Comment by m1093782566** [comment]
Besides, if configure kube-dns in node's `/etc/resolv.conf`, it will cause a DNS lookup loop as well.

**Comment by m1093782566** [comment]
@bowei Can we limit the max retry count of resolving? Just like OS limit the maximum reparse points for a symbol link path

**Comment by dcbw** [comment]
@bowei is it the case that *only* localhost is in resolv.conf in these cases, or that resolv.conf is one of the nameservers?  Honestly I can't think of a great excuse to have 127.0.0.1 in a pod's resolv.conf unless that pod is hostNetwork=true.  Otherwise that allows pods to bypass cluster DNS entirely.

**Comment by bowei** [comment]
@dcbw -- yes, there was a comment at some point to remove all mentions to 127.0.0.1 and emit errors (i.e. event) if we are left with no nameservers.
