### ISSUE TITLE
Scheduler spreading using services vs replication controllers

### ISSUE THREAD

**Issue by abhgupta** [kubernetes/kubernetes#4971]
Creating a separate issue since the PR (https://github.com/GoogleCloudPlatform/kubernetes/pull/4674) in which this discussion was initiated is merged and this merits a second look.

I had raised the question of why we used services instead of replication controllers for identifying peer pods for spreading by the scheduler. The argument is that services might not be needed and could be avoided in some cases, whereas replication controller will most likely always be there.

@bgrant0607 's initial response: why use services instead of replication controllers for identifying peer pods for spreading. Discussed in #1965 and #2312. Replication controllers are associated with deployments. We expect there to be multiple per service: canaries, rolling updates, multiple release tracks, etc. What people want is spreading of the whole service. Custom spreading is discussed in #4301 and #367.

While I agree that there can be multiple replication controllers per service, I still believe that spreading of pods should still happen independently for the replication controllers. Also, we have customer use cases where the services are not created at all and routing/load balancing to a group of pods is being handled by custom middleware.

Rolling updates: the new pods coming in should be scheduled on the best possible minions and should not be combined with the existing older pods for achieving a good spread. Eventually, when all the older pods are removed and only the new ones remain, its the spreading of the new pods that really matters.

Canaries: This one is slightly different, but in general the same argument applies here as for rolling updates.

Multiple release tracks: shouldn't we have a good spread within each release track to ensure HA for each release track? Why would we want to jointly consider the pods for different release tracks for a good spread?

**Comment by bgrant0607** [comment]
Falling back to spreading using the full set of labels on a pod (which would also likely be the labels specified by a replication controller's selector) is a reasonable thing to do in absence of a service. Services are useful even when load balancing is not required, however -- see #1607.

I disagree that one wouldn't want multiple deployments to all be spread uniformly rather than spreading each independently. The total capacity of the application is what matters, and failures are possible at any time.

**Comment by danmcp** [comment]
@bgrant0607 

> I disagree that one wouldn't want multiple deployments to all be spread uniformly rather than spreading each independently. The total capacity of the application is what matters, and failures are possible at any time.

Is that for every case Abhishek listed?

I would certainly want a rolling deployment to schedule independent of any existing replication controllers.  Because what matters to me there is that the deployment when it's done is scheduled to the best fit location.  I don't care much about the deployment overlapping with the existing deployment for some period of time.

Really in every case it seems like HA of the thing being replicated is important.  And I would choose better fit over avoiding other pods from the same service.  For example:  If you have 4 nodes.  2 of the nodes are nearly full and 2 are almost empty.  If you then try to schedule 2 new pods belonging to a new replication controller of a service that already has pods on the almost empty nodes.  I would much rather schedule onto the almost empty nodes and collocate with pods from the same service rather than end up on a generally worse fit.

All else being equal, spreading based on service is reasonable.  But it seems like a tertiary concern with the order being:

1) spread by replication controller (and whatever other labels you choose to require spreading on)
2) provide a reasonably good fit
3) spread by service

So I guess I am looking for an example of when spreading across a service (as a first concern) provides a better experience compared to spreading by the thing you are replicating.

**Comment by bgrant0607** [comment]
@danmcp 

Of course, in the case that there is just 1 replication controller, spreading by controller labels is reasonable. However, the controller/service decoupling enables multiple replication controllers to exist indefinitely, which is typical for applications with multiple release tracks (e.g., daily and weekly), which is common for ["high-functioning" DevOps teams](https://puppetlabs.com/blog/5-kpis-that-make-the-case-for-devops).

In the case of rolling update, the overlap is just 1 instance, which doesn't seem like much of a problem in cases where rolling updates make any amount of sense.

Regardless, many processes will perturb binpacking within the cluster. See comments here: https://github.com/GoogleCloudPlatform/kubernetes/issues/2483#issuecomment-76502738

**Comment by danmcp** [comment]
@bgrant0607 

I am not saying ignore service.  Just that it isn't the best first priority.  If you spread with replication controller as the first priority and service after, you still get the service spreading, without the edge cases.

I will mention too it isn't just 1 replication controller cases that are broken only spreading by service.  One example would be:

Start with:

Node1: P1_RC1_S1, P2_RC1_S1, P3_RC1_S1, P4_RC1_S1
Node2: P1_RC2_S1, P2_RC2_S1, P1_RC3_S1, P2_RC3_S1

So you have 3 replication controllers total and 1 service that spans all of them.  The above example is perfectly spread by service.  But if you scale down RC1 to 0.  You are left with the 2 remaining replication controllers with their resources all on 1 node.

I don't have an example that spreading by replication controller then service is worse though.

I don't disagree you have to have self healing still.  Are you arguing you would rather only heal these types of problems after the fact rather than build the logic (with RC labeling or otherwise) into the scheduler?  If so, are you just making an argument of it's too much complexity?

**Comment by derekwaynecarr** [comment]
@danmcp - If a replication controller could 'infect' a pod with a unique label, do you need any other feature to reach your desired case?  Right now, the replication controller takes all the labels on a pod and clones them.  It seems to me that if you allowed a replication controller to infect a pod with a unique label value, you could spread based on that value without baking any additional knowledge into the scheduler to be controller aware.

@bgrant0607 - have you thought about letting controllers in general apply additional labels the resources they create?

**Comment by danmcp** [comment]
@derekwaynecarr The only additional requirement would be that label spreading had a higher priority than service spreading.

**Comment by bgrant0607** [comment]
@derekwaynecarr Early on, replication controller did add a label. I had it removed. As @danmcp points out, it's redundant with user labels.

@danmcp Feel free to submit a PR or ask @abhgupta to make the change.

**Comment by abhgupta** [comment]
@danmcp @bgrant0607 @derekwaynecarr If we are addressing this, we might as well address another key issue. 

Q. How do we identify the group of pods when there are multiple replication controllers (that form a conceptual 'service') but no service resource created, since the routing/load-balancing is done by a custom middleware? 

Option 1) Here the pod labels cannot be used since each pod (or a set of pods) will have labels that are specific to its own replication controller. For this use case, can we allow the pod to specify a label that can be used to identify its peer pods and for spreading?

Option 2) Now, in this scenario, the label-selector aspect of the service is required but not the routing/proxying part of it. Given this, would it make sense to allow service resources be created with proxying/routing disabled (somehow) allowing us to use the label-selector aspect of the service?

**Comment by abhgupta** [comment]
@smarterclayton any thoughts on my comments above?

**Comment by bgrant0607** [comment]
@abhgupta Specifying a single label to use for spreading is not the right way to think about it. It needs to be a label selector.

That said, I'd like to make services useful even for scenarios where our naming, VIPs, and load balancing  aren't needed -- see #1607.

**Comment by smarterclayton** [comment]
For #1607 if the replication controller added a unique label to the pod (and maybe parameterized it via a downward API) that would achieve both spreading and role assignment.

**Comment by smarterclayton** [comment]
I think headless services are strictly better than not having headless services and letting RC's carry the load.  There's a "thing" there, and it's a service, it's just not a "port forwarding" service.

**Comment by abhgupta** [comment]
@bgrant0607 Aah, wasn't careful enough in my comment above - I did mean a LabelSelector on the pod for idenfying the peer pods.

**Comment by abhgupta** [comment]
I would myself prefer a service that did not do proxying to solve this use case. While both options (label selector on pod vs non-proxying service) are explicitly specified by a user, decoupling it from the pod does sound more patalable. 

@bgrant0607 @smarterclayton Is a non-proxying service your preferred option as well? If so, what needs to be done to get things moving for this? #1607 hasn't seen a lot of activity lately. I am open to picking up the implementation if I can get the guidance of what needs to be done for this. Is having none for PortalIP acceptable? Or something else...

**Comment by smarterclayton** [comment]
Tim mentioned in an issue he's looking into it.

----- Original Message -----

**Comment by abhgupta** [comment]
@thockin Refer @smarterclayton 's comments above. Could you point me to any ongoing work on this (issue/PR) that I could follow?

**Comment by bgrant0607** [comment]
#4370 and #4742, but neither directly address #1607. More details on that issue.

**Comment by thockin** [comment]
I don't like a magic out-of-band value for an otherwise typed field, but I
am not confident in any other solution yet, and I'd rather be biased
towards action.

**Comment by timothysc** [comment]
IMHO, we should try to avoid baking in too many default semantics based on primitives, because in the long run you may find it limiting, or not what you really want.  I understand the desire to spread, but in reality different workloads will often have different QoS tiers and thus different constraints.  Keeping the core algorithm simple enough while having the mechanics to enable customized constraints is usually the most flexible, or least limiting, route in the long haul. 

For example, some folks may wish to run a service whose QoS is (never go down) where the spread is based on rack/cluster/dc vs. node.  In contrast with other services, where bin-packing is of greater importance.

**Comment by bgrant0607** [comment]
The goal is to do something reasonably useful by default, perhaps differentiated by class of workload (e.g., services vs. data processing / HPC), but then also support more expressive constraints (#367).

**Comment by abhgupta** [comment]
@timothysc I completely agree on being able to specify (or override) constraints at different resource-levels. Even for spreading, some services may want to be spread at a rack level, whereas others might want rack-level-affinity and be spread at an individual minion level. These are things that we can discuss and build. However, this does not take away from the fact that we need reasonable defaults at the overall level in the scheduler (as @bgrant0607 pointed out) and that is what I was looking for some guidance on.

As far as services are concerned, they do perform multiple functions with proxying being one of them. The other important function is to provide a means to manage/identify peer pods and this can be useful for a variety of different consumers like the kube-proxy, router, scheduler, etc. A non-proxying service is just s a special case where it will perform just one of those functions. I whould actually se it as orthogonal to the scheuler and to the concerns raised by you.

@bgrant0607 @smarterclayton @thockin What can we do to get this going? Are we settled on non-proxying services as the preferred option for achieving this use case (https://github.com/GoogleCloudPlatform/kubernetes/issues/4971#issuecomment-77815864) or is that still an open question?

**Comment by bgrant0607** [comment]
@abhgupta Combined with @danmcp's proposal to also spread by pod labels, I think using a headless service would be entirely reasonable for the default policy. Note that people can use services that way today, by just ignoring the allocated IP address.

If someone wants to develop a detailed API design for #367, we could also start that discussion.

**Comment by abhgupta** [comment]
@bgrant0607 I agree that users can create a service for the use case I described. However, the issue with having services that proxy requests to pod endpoints is that a mechanism to reach your pods exists even though it may not be needed. This coud make users uncomfortable.

I would like to get https://github.com/GoogleCloudPlatform/kubernetes/issues/367 moving as well, once I have some of this basic stuff sorted/implemented.

**Comment by abhgupta** [comment]
@bgrant0607 By the way, I never got your go-ahead on specifying null as PortalIP as a way to implement headless services. If this approach is acceptable, I will make a PR for this at the earliest opportunity.

**Comment by abhgupta** [comment]
@bgrant0607 Ignore my comment above regarding the consent on None for PortalIP. I just checked your comments https://github.com/GoogleCloudPlatform/kubernetes/issues/1607#issuecomment-78169282

**Comment by abhgupta** [comment]
With https://github.com/GoogleCloudPlatform/kubernetes/pull/5556 merged, we now have headless/non-proxying services.

**Comment by gmarek** [comment]
PR related to this: #10667

**Comment by bgrant0607** [comment]
We are now spreading by both.
