### ISSUE TITLE
GPU e2e jobs have started failing

### ISSUE THREAD

**Issue by mindprince** [kubernetes/kubernetes#49839]
Both https://k8s-testgrid.appspot.com/wg-resource-management#gce-gpu and https://k8s-testgrid.appspot.com/wg-resource-management#gke-gpu started failing recently. Their 1.7 counterparts are passing.

The difference between the last passing and the first failing tests is:
https://github.com/kubernetes/kubernetes/compare/72494353c...c25a7e6a7
Probably something in #48846 broke the tests.

/sig scheduling
/cc @vishh @dashpole 
/kind bug

**Comment by dashpole** [comment]
It looks like there isn't enough cpu on the master to run the cos-nvidia-installer daemonset.  Did we add any addons recently?
`INFO: At 2017-07-25 07:39:30 +0000 UTC - event for cos-nvidia-installer: {daemonset-controller } FailedPlacement: failed to place pod on "bootstrap-e2e-master": Node didn't have enough resource: cpu, requested: 150, used: 950, capacity: 1000`

**Comment by dashpole** [comment]
My previous comment is a red herring.
It is an issue with #48846.  Ill post a fix soon.  From the scheduler logs on the master:
`About to try and schedule pod nvidia-gpu-887ee7e7-710d-11e7-95cc-0a580a3c350d`
`Attempting to schedule pod: e2e-tests-gpus-1v6xm/nvidia-gpu-887ee7e7-710d-11e7-95cc-0a580a3c350d`
`Ignoring node bootstrap-e2e-master since it is unschedulable`
`Ignoring node bootstrap-e2e-minion-group-lkqm with OutOfDisk condition status Unknown`
`Ignoring node bootstrap-e2e-minion-group-fkc8 with OutOfDisk condition status Unknown`
`Ignoring node bootstrap-e2e-minion-group-kcjl with OutOfDisk condition status Unknown`
`Failed to schedule pod: e2e-tests-gpus-1v6xm/nvidia-gpu-887ee7e7-710d-11e7-95cc-0a580a3c350d`
`Unable to schedule e2e-tests-gpus-1v6xm nvidia-gpu-887ee7e7-710d-11e7-95cc-0a580a3c350d: no nodes are registered to the cluster; waiting`
`Updating pod condition for e2e-tests-gpus-1v6xm/nvidia-gpu-887ee7e7-710d-11e7-95cc-0a580a3c350d to (PodScheduled==False)`
`Event(v1.ObjectReference{Kind:"Pod", Namespace:"e2e-tests-gpus-1v6xm", Name:"nvidia-gpu-887ee7e7-710d-11e7-95cc-0a580a3c350d", UID:"8881b04c-710d-11e7-b68a-42010a8a0002", APIVersion:"v1", ResourceVersion:"1580", FieldPath:""}): type: 'Warning' reason: 'FailedScheduling' no nodes available to schedule pods`

**Comment by vishh** [comment]
@dashpole that's a benign error. The daemonset is not expected to run on the master. But there is no easy way to express that request in our APIs.

**Comment by dashpole** [comment]
Yes, the pod not scheduling on the master is benign.  The actual error is that we do not report node condition `OutOfDisk`, so it is left as `Unknown`.  The fix is to report that `OutOfDisk` is false.

**Comment by mindprince** [comment]
@dashpole The tests are still failing.
/reopen

**Comment by dashpole** [comment]
I will be updating #50058 to track progress.

**Comment by dashpole** [comment]
tests are green again!
/close
