### ISSUE TITLE
CloudNodeController does not set Node.Spec.ProviderID

### ISSUE THREAD

**Issue by prydie** [kubernetes/kubernetes#49836]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:

[`CloudNodeController.AddCloudNode()`][1] does not populate `Node.Spec.ProviderID` and as such the field never gets set for clusters deployed with external cloud controller managers.

For in-tree cloud providers `kubelet` sets the properties in [`Kubelet.initialNode()`][2].

**What you expected to happen**:

[`CloudNodeController.AddCloudNode()`][1] should call `cloudprovider.Instances.InstanceID()` and set the `Node.Spec.ProviderID` field.

**How to reproduce it (as minimally and precisely as possible)**:

 - Deploy a cluster with `--cloud-provider=external` and an external cloud controller manager
 - Note that `Node.Spec.ProviderID` is not set by the cloud controller manager.

**Anything else we need to know?**:

Kubelet also populates this field using https://github.com/google/cadvisor where possible (at the time of writing for GCE, AWS, and Azure). We could document that as the means of populating `ProviderID` on other clouds (via contributions to cadvisor), however, that seems like a move in the wrong direction.

**Environment**:
- Kubernetes version:
  ```
   Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.2", GitCommit:"922a86cfcd65915a9b2f69f3f193b8907d741d9c", GitTreeState:"clean", BuildDate:"2017-07-21T19:06:19Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
   Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.0", GitCommit:"d3ada0119e776222f11ec7945e6d860061339aad", GitTreeState:"clean", BuildDate:"2017-06-29T22:55:19Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
   ```
- Cloud provider: External cloud provider (Oracle Bare Metal Cloud Services).
- OS (e.g. from /etc/os-release): `OEL 7.3`
- Kernel (e.g. `uname -a`): `Linux apryde-master 4.1.12-94.3.6.el7uek.x86_64 x86_64 GNU/Linux`
- Install tools: `kubeadm`

/cc @luxas @wlan0 @rrati @roberthbailey @tjfontaine @owainlewis

[1]: https://github.com/kubernetes/kubernetes/blob/02b520f0a40be2056d91fc0661c2b4fdb2694c30/pkg/controller/cloud/nodecontroller.go#L266
[2]: https://github.com/kubernetes/kubernetes/blob/02b520f0a40be2056d91fc0661c2b4fdb2694c30/pkg/kubelet/kubelet_node_status.go#L293

**Comment by prydie** [comment]
@kubernetes/sig-cluster-lifecycle-proposals

**Comment by roberthbailey** [comment]
What do you intend for the behavior to be when the cloud controller manager is running and the kubelet is run with the `--cloud-provider=gce|aws|azure` flag? Since we support minor version skew of two versions, we will need to introduce this behavior in a way that is compatible with older kubelets whose flag configuration cannot be updated. 

A few options:
1. Only set the field from the cloud controller manager for kubelets at version > X (where X is agreed to by deployers on the aforementioned platforms)
1. Same as above but use node labels rather than explicit kubelet versions to decide when to set the field from the cloud controller manager
1. Only set the field if it isn't already set by kubelets (this may be racy if the kubelets don't set the field during the initial insertion of the node resource)
1. Assume that the field would be set identically by the kubelet and the cloud controller manager and let them race to set the field (and ensure that if the cloud controller manager wins the kubelet behaves normally)

**Comment by prydie** [comment]
I don't _think_ this is a problem as a node [opts into][1] having [`CloudNodeController.AddCloudNode()`][2] called only when `--cloud-provider=external` is set. Otherwise `AddCloudNode()` will [short circuit and log that the node is not being processed][3].

[1]: https://github.com/kubernetes/kubernetes/blob/02b520f0a40be2056d91fc0661c2b4fdb2694c30/pkg/kubelet/kubelet_node_status.go#L221
[2]: https://github.com/kubernetes/kubernetes/blob/02b520f0a40be2056d91fc0661c2b4fdb2694c30/pkg/controller/cloud/nodecontroller.go#L266
[3]: https://github.com/kubernetes/kubernetes/blob/02b520f0a40be2056d91fc0661c2b4fdb2694c30/pkg/controller/cloud/nodecontroller.go#L277

**Comment by luxas** [comment]
As pointed out by @prydie; I think this will be safe to add due to that the cloud taint isn't added in any case you're already opting into using the external cloud way.

other thoughts @wlan0 @thockin ?

**Comment by jhorwit2** [comment]
It should be safe to add since the kubelet will set the ProviderID on the node object when it's initially created. That means by the time the CCM gets the node object it will already contain a value, so as long as we keep the same `set only if empty` check as the kubelet then backwards compatibility should be kept.
