### ISSUE TITLE
Docker CE for Windows 10 installed  Kubernetes  need  Docker Toolbox

### ISSUE THREAD

**Issue by liust2014** [kubernetes/kubernetes#49848]
/kind problem

I was install docker CE for windows  10 and can use  docker with  command, but after i  installed  kubernetes and use it , it need Docker Toolbox.

Another  computer  have no this problem. 

message like this: VirtualBox is not installed. Please install it via the Docker Toolbox.

**Comment by cblecker** [comment]
Please re-post your question to [Stack Overflow](http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases.

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans Stack Overflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search Stack Overflow for answers to similar questions, and also familiarize yourself with:

  * [user documentation](http://kubernetes.io/docs/)
  * [troubleshooting guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/)

Again, thanks for using Kubernetes.

The Kubernetes Team

---
/kind support
/close
