### ISSUE TITLE
"NotReady" node leads to "Unknown" pod that don't detach disks (and thus can't be recreated)

### ISSUE THREAD

**Issue by apelisse** [kubernetes/kubernetes#49894]
**Is this a BUG REPORT or FEATURE REQUEST?**: BUG REPORT

/kind bug

**What happened**:

My cluster is made of 4 nodes, running pods that are using RW attached GCE disks.

Some of the nodes end-up in "NotReady" state. I can still ssh the nodes, and they seem alive, but for some reason they are reported as "NotReady". They probably fall in that state because of another bug, but I don't know or want to investigate that reason now (might be relevant or not, sorry).

The pods on these nodes end-up in a "Unknown" state, where they can't be killed in any way, or removed. The Kubernetes deployment recreates these pods, but unfortunately, they can't mount the disks that haven't been detached by the "Unknown" pods. I end-up with a completely broken infrastructure where none of my pod go back into a working state. I have to ssh the "dead" machine and reboot it to leave that broken state.

/sig-storage
cc @saad-ali 

**What you expected to happen**:
I want the "Unknown" pods to either die or release the disks so that another pod can be created to replace them.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
master and nodes are running 1.6.6, this is happening on GKE.

**Comment by saad-ali** [comment]
Volumes not getting detached when the pod falls into "Unknown" pod phase was "by design". The "Unknown" pod phase is [not considered "terminated"](https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/util/volumehelper/volumehelper.go#L102) to prevent a disk from being detached while a volume is in use (resulting in data corruption).

That said, given that we have a safety in the Kubelet volume manager that checks for container termination before unmount, and the attach/detach controller waits for unmount (until timeout), before detaching, we could consider reclassifying the "Unknown" pod phase as a valid "termination" state so that volumes get detached. CC @kubernetes/storage-sig-misc

Alternatively, if whatever mechanism that set pod phase to "Unknown" instead set it to "Failed" we could bypass this altogether.

**Comment by saad-ali** [comment]
As a workaround deleting the pods in "Unknown" pod phase would also trigger the detach.

**Comment by jicki** [comment]
Node  Service   reboot

```
kubectl get nodes        

node =  NotReady       
```

Node Can not be recovered

**Comment by Shivang44** [comment]
Is there any updates to this issue? I don't fully understand the need for volumes to remain attached in an unknown state. For example, we have an NFS server pod with an AzureDisk volume. Once its host node dies, the pod is left in an unknown state and recreated on another node. But its backing volume is still attached to the "unknown" state pod stuck in limbo.
