### ISSUE TITLE
[code style] verify pkg/util contains no code

### ISSUE THREAD

**Issue by resouer** [kubernetes/kubernetes#49923]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:

A follow up of https://github.com/kubernetes/kubernetes/issues/15634

**What you expected to happen**:

We should add a script to verify this. e.g. `./hack/verify-util-pkg.sh`

**Comment by resouer** [comment]
@kubernetes/sig-contributor-experience-feature-requests

**Comment by mathspanda** [comment]
@resouer 
Does it mean to write a script to verify that there are no go files except directories in pkg/util?
I am new to k8s, but i believe i can handle this. Can you assign this issue to me?

**Comment by spxtr** [comment]
We're trying to cut back on `hack/verify-*.sh` scripts, although this one is pretty tame. I suggest writing a few-line [`sh_test`](https://docs.bazel.build/versions/master/be/shell.html#sh_test) that uses the [`pkg/util` filegroup](https://github.com/kubernetes/kubernetes/blob/master/pkg/util/BUILD#L5-L10) as a data dependency. Then we don't need any sort of `hack/verify-*.sh` script, since it will just run in the bazel job and it will be cached properly.

**Comment by resouer** [comment]
@mathspanda Right. But please note some exceptions: 

1. non .go file like README, OWNER etc
2. `doc.go` and `types.go` is also OK

**Comment by resouer** [comment]
And please fix this by following @spxtr advice, thank you!

**Comment by resouer** [comment]
Close this by #49993 , thanks @mathspanda @thockin for code and review!
