### ISSUE TITLE
scheduler panic at leader election fail when there a lot of failed-scheduling pods

### ISSUE THREAD

**Issue by kevin-wangzefeng** [kubernetes/kubernetes#49947]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
When a pod failed to get scheduled, scheduler will keep calling get pod to try schedule it.
See 
https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/scheduler/scheduler.go#L174, https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/scheduler/factory/factory.go#L718, and https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/scheduler/factory/factory.go#L926L974.

In our test environment, we met the case that there are lot of failed-scheduling pods, the leader election requests get blocked by client-side RateLimiter and scheduler keep panic/restart.

**What you expected to happen**:
This can be part of more fine grained rate limiting in big clusters.
But for here, to have a quick fix, we can consider use an individual client for leader election and another for data fetching requests e.g. get pods.

**Comment by kevin-wangzefeng** [comment]
assigning to myself as a proxy for @lichuqiang who is working on this.
/assign

**Comment by mml** [comment]
If anyone re-adds sig/api-machinery, please explain why or what we need to do.  Thanks?

**Comment by lichuqiang** [comment]
@mml The key point to the issuse is the mechanism of rate limit, and now the problem is exposed to the client side. As a quick fix, we tried to add individual kubeclient for leader-election in scheduler.
Extremely, if where is a large number of concurrent requests in server side, the controlling request may still be blocked. 
Separating controlling requests and data requests in rate limit behavior might be a way to resolve the matter, but the modification would be of great influence

**Comment by yekaifeng** [comment]
If my understanding is correct, the problems is like this. 

The scheduler leader-election rely on kubeclient sending renew() request to etcd via api-server every 2 seconds, in order to refresh the leader lock. If the scheduler leader can not refresh the lock in 10 seconds, it will lost the lock, and a new leader election process will start.

If there are a lot of failed-scheduling pods because whatever reasons in a large cluster, the scheduler leader keeping re-scheduling the pod via api-server, which is reaching to the rate-limit(KubeAPIQPS, default 50) soon. Since the scheduler leader also need the same channel to update the leader lock, the leader can not update the lock because the channel limit is reached in such situation. This would cause the scheduler leader keeping changing even panic.

That's why lichuqiang said he want another kubeclient to talk with api-server which is like creating a new channel.

My suggestion is to extend the --leader-elect-renew-deadline to 20 s and increase the KubeAPIQPS to see what happen.

**Comment by lichuqiang** [comment]
@yekaifeng In fact, we met the issue in reliability test, not a regular scene. That is, testers created thousands of pods that could never be normally scheduled, so the amount of request would never scale down.  They hold the opinion that process of scheduler should not be impacted this way. So the matter could not be resolved by simply expand the rate of limit.

**Comment by mml** [comment]
OK.  I see how API machinery is involved.  Thanks.

Long term, I think we'd like more sophisticated server-side rate limiting, and we would want a high rate limit specifically for coordinating operations like leader election that, if they block, cause the whole system to fail to make progress.  I would like to see us file a bug to figure that problem out long-term.

Short-term, @lichuqiang, have you tried tweaking `--leader-elect-renew-deadline` in your test?

**Comment by mml** [comment]
/sig api-machinery

See #51817 for the long-term issue.

**Comment by kevin-wangzefeng** [comment]
Close in favor of https://github.com/kubernetes/kubernetes/pull/53793
