### ISSUE TITLE
Submit-queue automatically self-approve PRs

### ISSUE THREAD

**Issue by yutongz** [kubernetes/kubernetes#49967]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug

**What happened**:
I deployed mungegithub to two of our repos, but they have different behaviors. In [istio/istio](https://github.com/istio/istio/pulls), submit-queue seems add "approved" label to every PR create by people in OWNERS file, even without someone commented "/approve". While in [istio/test-infra](https://github.com/istio/test-infra/pulls), it's not that case.

**What you expected to happen**:
I expect the behavior from istio/test-infra

**How to reproduce it (as minimally and precisely as possible)**:
I build Mungegithub from head of [this PR](https://github.com/kubernetes/test-infra/pull/3792), since I have problem dealing with robot-name.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.6.4
- Cloud provider or hardware configuration**: GKE
- OS (e.g. from /etc/os-release): 
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by liggitt** [comment]
this should be opened against kubernetes/test-infra, not the main kubernetes repo. self-approval is expected, at least in kubernetes/kubernetes. explicit lgtm is still required.

**Comment by cjwagner** [comment]
@yutongz I think everything is working properly in those repos. In istio/istio the approved label has been applied to many PRs because an issue number was referenced, linking the PR to the issue. In istio/test-infra the label was not applied to most of the PRs because no issue number was specified and there was no '/approve no-issue' approval command.  The approval notification messages explain why the label was added or is missing.

**Comment by yutongz** [comment]
@cjwagner  Thanks Cole, this explains a lot.

**Comment by cjwagner** [comment]
No problem. This behavior is now configurable with the `approval-requires-issue` option.
