### ISSUE TITLE
PVCs using `standard` StorageClass create PDs in disks in wrong zone in multi-zone GKE clusters

### ISSUE THREAD

**Issue by nfirvine** [kubernetes/kubernetes#50115]
/kind bug

**What happened**:

- Created single-zone cluster in `us-central1-c`
- Expanded to multiple zones after creation using `gcloud container clusters update ... --additional-zones` to `b` and `a`
- Deployed PVC with `storageClassName: standard`, which is a StorageClass included with GKE.
- PV is created in `us-central1-f`, a zone with no nodes from this cluster in it

**What you expected to happen**:

- PV created in one of the zones that the cluster has nodes in

**How to reproduce it (as minimally and precisely as possible)**:

See `What Happened`. I'm not sure the expansion after creation step is necessary.

**Anything else we need to know?**:

May be a duplicate of https://github.com/kubernetes/kubernetes/issues/39178, but that's on AWS

**Environment**:

- Kubernetes version (use `kubectl version`): 
```Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.0", GitCommit:"d3ada0119e776222f11ec7945e6d860061339aad", GitTreeState:"clean", BuildDate:"2017-06-30T09:51:01Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4", GitCommit:"d6f433224538d4f9ca2f7ae19b252e6fcb66a3ae", GitTreeState:"clean", BuildDate:"2017-05-19T18:33:17Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration**: GKE 1.6.4
- OS (e.g. from /etc/os-release): cos

**Comment by msau42** [comment]
From the code, it looks like the GCE cloud provider will use all zones in the region for a multi-cluster configuration.  Instead, it should probably derive the zones from the nodes in the cluster.

/kind bug
/sig storage
/sig gce

**Comment by justinsb** [comment]
Were there _some_ instances running in the project in us-central1-f ?  This comment explains the current heuristic and the limitations of it: https://github.com/kubernetes/kubernetes/blob/3c080e83c7974fa21c5a47264f992a3d0189e143/pkg/cloudprovider/providers/gce/gce_instances.go#L264-L273

Aside: I would _love_ to fix this by having the cloudprovider get access to the kubernetes client, watch the Nodes, and then it could simply iterate over the nodes and pull the zone out of the failure-domain labels.  If the cloudprovider had access to kubernetes API objects (Nodes, really) it would avoid a lot of work in the AWS provider, and I've heard from other cloudproviders that it would also benefit them.

**Comment by wojtek-t** [comment]
The problem is how we initialize GCE cloud provider:
https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/gce/gce.go#L236

This is simply broken.

We should be able to set the list of zones cloud provider is managing (i.e. pass them by flag or sth like that).

**Comment by wojtek-t** [comment]
@msau42 ^^

**Comment by justinsb** [comment]
managedZones has a set of candidate zones, and then we filter that down to zones in which instances are actually running when choosing where to place the disk.   Can you clarify what you mean by "simply broken"?

I agree it would be better if we could configure the set of candidate zones in the multizone case, but that likely relies on componentconfig or a better installation tool, which is why it wasn't done previously.  i.e. we're still paying the kube-up tax.

**Comment by wojtek-t** [comment]
> managedZones has a set of candidate zones, and then we filter that down to zones in which instances are actually running when choosing where to place the disk. Can you clarify what you mean by "simply broken"?

What I mean is that currently it can contain zones in which there just can't be any nodes. 
I would be fine with the definition of "list of zones where there is non-zero probability we have nodes there". But it's not necessarily the case now.

Currently, in GCE you can specify that the cluster can be e.g. in zones: us-central1-a, us-central1-b and us-central1-c. But even if you explicitly do that, managedZones will contain all zones in us-central1 region, which mean also "us-central1-f". There will never be nodes in that zone with this configuration and that seems broken to me.

> I agree it would be better if we could configure the set of candidate zones in the multizone case, but that likely relies on componentconfig or a better installation tool, which is why it wasn't done previously. i.e. we're still paying the kube-up tax.

Agree.

When I'm thinking more about it, I know start to think that actually configuring it (no matter if it is ConfigMap or flag or sth else) is actually not the best option.
On one hand getting this info from Nodes seems like a solution, OTOH cloud provider library for me is something that shouldn't have access to cluster itself.

I think the cleanest solution to me would be to have a cloud provider implementing API: "give me list of zones with at least one node in them". In fact, since `managedZones` concept is actually not external, this may actually be private API of GCE cloud provider.

@thockin for thoughts

**Comment by wojtek-t** [comment]
In fact we already have a function that returns list of zones where we have some nodes it's here:
https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/gce/gce_instances.go#L248
and is called `GetAllZones()`.

**Comment by msau42** [comment]
Yeah, I think the challenge at setting `managedZones` at init time is that nodes/zones can by dynamically added to the cluster.  So `GetAllZones` may be the way to go, but we need to balance calling it everytime vs caching, as it is an expensive call...

**Comment by wojtek-t** [comment]
> So GetAllZones may be the way to go, but we need to balance calling it everytime vs caching, as it is an expensive call...

Yes, I just wanted to write this but forgot. We should probably add some caching to avoid calling this more often than say once a minute. That should solve our problems.

**Comment by nfirvine** [comment]
I figured out a workaround:
```
#move the disk from the zone it's in to a good zone
gcloud compute --project $project disks move $pdname --destination-zone=$goodzone --zone $pdzone
#edit the failure-domain label to be  $goodzone
kubectl edit pv $pvc
```

**Comment by msau42** [comment]
Hi @wojtek-t, I took a closer look at this, we are calling `GetAllZones` already.  So I think the problem is more likely that `GetAllZones` doesn't filter the instances.  So if there was a node not managed by this cluster in that zone, then we would return that zone.  I can think of 2 approaches:

1. Filter the instances by the cluster ID.  This assumes that we tag the instances with the cluster ID, and that the `gceCloud.ClusterID` is the same.
2. Instead of calling the cloud provider, call Kubernetes Nodes.List() and get all the zone labels on the nodes.  This requires a K8s client, which I don't think the cloud provider has.

**Comment by saad-ali** [comment]
Marking `priority/important-soon` indicating we should try and get a fix in ASAP, but this issue should not block the 1.8 release.

**Comment by wojtek-t** [comment]
@msau

>  Hi @wojtek-t, I took a closer look at this, we are calling GetAllZones already. So I think the problem is more likely that GetAllZones doesn't filter the instances. So if there was a node not managed by this cluster in that zone, then we would return that zone. 

We need to be very careful if this expected behavior or not.
The example I have in mind is the following:
- imagine that we have a multizonal cluster which is supposed to have nodes in zones A, B and C
- but since it is now night and there is no load, HPA + cluster autoscaler together scaled the cluster down to: 1 node in A, 1 node in B and 0 nodes in C
- during the day, it will again be scaled up to many nodes in all three nodes

So during this night - do we manage all three zones, or do we manage only two?
To be honest, I'm not sure what the answer is - we just need to carefully answer this question.

> Filter the instances by the cluster ID. This assumes that we tag the instances with the cluster ID, and that the gceCloud.ClusterID is the same.

That is a bit fragile, because if someone will set up cluster differently, they may not have it.
I'm not saying "no" - I'm just pointing out potential problem.


> Instead of calling the cloud provider, call Kubernetes Nodes.List() and get all the zone labels on the nodes. This requires a K8s client, which I don't think the cloud provider has.

GCE has it:
https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/gce/gce.go#L108

I think that's reasonable approach.

**Comment by msau42** [comment]
All the callers of `GetAllZones` are either for volume provisioning or for e2e tests, which expect it to only return zones where there are currently nodes, so I think it is safe to add this filtering.  We can rename this to `GetAllCurrentZones` to be more clear.  If we want to include volume provisioning into HPA in the future, then we may have to revisit this and figure out a way to pass in managed zones instead of just determining the current zones.

We'll try the second approach of getting the K8s nodes list.

**Comment by wojtek-t** [comment]
@msau42 - ok, that sounds reasonable.
And I agree if we proceed with this approach, renaming to GetAllCurrentZones is much better name and we should rename it.

**Comment by dims** [comment]
Looks like the PR #52322 needs v1.8 milestone

**Comment by saad-ali** [comment]
Removing from 1.8 milestone. This issue was not introduced in 1.8 and should not be a blocker for 1.8. If the fix goes in after 1.8, it can be cherry picked back to 1.8, 1.7, 1.6, etc.

**Comment by davidz627** [comment]
So we've worked on this issue a bit and kind of hit a snag (see: https://github.com/kubernetes/kubernetes/pull/52322#issuecomment-331519307)

The solution that was proposed and implemented from the discussions in this issue has led us to some permissions errors that actually brought up some larger questions about the authoritative source of zone info. We note that it is possible that nodes may misreport their zone and that there are already efforts in reducing the scope of node on the node object. Therefore, it seems like the change I have made in my PR is "getting information from the wrong place."

That leads to the question of "where is the right place to be getting this information." After some discussions with @liggitt it seems that the authoritative source of zone information should be the cloud provider. The original issue with getting the information from the cloud provider that spurred the above PR was that we are unable to disambiguate between Kubernetes nodes and generic compute instances in the response object when we list instances in each zone.

It seems to me that it would be beneficial to decorate instances with metadata that lets us tell whether a node is a Kubernetes node. I am not sure if this is done currently, the closest thing I can see is the key "cluster-name" or the like in the "metadata -> items" object.

My question is, is there currently a metadata field that we can consistently use to unambiguously determine whether a compute instance is a Kubernetes node or not. And if there is not such a field, what suggestions do you have to solve this issue?

@mikedanese and @cjcullen specifically, do you have any ideas or other people that may be able to answer this?

**Comment by yujuhong** [comment]
> OTOH cloud provider library for me is something that shouldn't have access to cluster itself.

+1. Seems a bit strange to get the list of nodes from within the cloud provider package. 

> It seems to me that it would be beneficial to decorate instances with metadata that lets us tell whether a node is a Kubernetes node. I am not sure if this is done currently, the closest thing I can see is the key "cluster-name" or the like in the "metadata -> items" object.

+1. I think in general we need some metadata to determine whether GCP resources are managed/owned by a kubernetes cluster. Labeling might be a good solution.
I am not aware of that any existing metadata that you could rely on though.

**Comment by mikedanese** [comment]
https://github.com/kubernetes/community/pull/911 is related to this.

**Comment by msau42** [comment]
@wojtek-t looks like K8s node list approach won't work.  What do you think of the 1st idea to tag gce instances with the clusterID?

**Comment by wojtek-t** [comment]
> @wojtek-t looks like K8s node list approach won't work. What do you think of the 1st idea to tag gce instances with the clusterID?

This is a bigger effort, but I'm fine with that.

**Comment by wojtek-t** [comment]
@msau42 - one thing that we really need to think about if we choose this way is whether we have any reasonable way to backfill the tags for already existing clusters.

**Comment by msau42** [comment]
Yeah, I don't think there's a good way to fix existing clusters.  I imagine that we'll need to modify our install and upgrade paths so only newer or upgraded clusters will get the fix.

**Comment by msau42** [comment]
Another problem is if users deploy clusters on GCE using their own method that doesn't tag the instances, then when we change the cloudprovider code to look for the tags, they could break.

**Comment by wojtek-t** [comment]
> Another problem is if users deploy clusters on GCE using their own method that doesn't tag the instances, then when we change the cloudprovider code to look for the tags, they could break.

Great point. That makes me thing that maybe tagging is not the best option and maybe we should think about something different? I don't have any better suggestion though...

**Comment by msau42** [comment]
Since listing k8s nodes is not an option, the best option may be to support the instance tagging and fallback to the old behavior if no tags are found.

**Comment by msau42** [comment]
@jlowdermilk what do you think of the instance tagging approach?

**Comment by jlowdermilk** [comment]
I still think that if you need a list of nodes that are participating in the cluster, the source of truth for that is the k8s apiserver, but if that is a hard no, then we could use instance labels. The downside with labels is that they are easily modifiable, so they are not a reliable source of truth. Advantage is you can use them in filter queries which makes the GCE instances list call less expensive.

**Comment by wojtek-t** [comment]
> I still think that if you need a list of nodes that are participating in the cluster, the source of truth for that is the k8s apiserver, but if that is a hard no, then we could use instance labels.

I completely agree with @jlowdermilk . I looked again into the original PR implementation, and TBH, I don't think there is "hard no" that has been expressed there. There are some concerns that @liggitt mentioned, but I think we should revisit that approach as the approach using apiserver sounds better in the context of unintentional/intentional user modifications.
Another data point is that: "what if there are VM instances in one zone, but the nodes in that zone didn't manage to initialize due to some issues. Then using VM instances doesn't sound like the correct approach too.

That said, while I agree that cloud-provider shouldn't have permissions to modify nodes, I can't see anything wrong with assigning it read permissions for nodes. @liggitt - can you comment on that?

And to address performance concern, we can easily use the informer framework to "LIST+WATCH" nodes, and every time we need a list of nodes, simply list from cache. That sounds fine from the performance perspective.

**Comment by liggitt** [comment]
> That said, while I agree that cloud-provider shouldn't have permissions to modify nodes, I can't see anything wrong with assigning it read permissions for nodes. @liggitt - can you comment on that?

It's not a concern over permission to view node API objects, it's over the source of truth for the cluster topology. Currently, node API objects are self registered, and self-report zones, addresses, and  labels. The presumption of kubernetes/community#911 is that there is *some* source of truth that doesn't depend on node self-reporting. 

The solution might be as simple as the node controller looking up zone info for registered nodes and applying appropriate labels, but it seems like we should ensure the data is populated in a trustable way before making it the source of truth for the provisioner.

**Comment by wojtek-t** [comment]
@liggitt - thanks for the comment. Now I see your point.
Regarding the solution - the "node-controller" approach is how I would also solve it.

That said, before we are at this point, I think that using those "self-reported" zone information is still better than the current code with assumption of all zones in a region.
So personally, I would proceed with the approach of using apiserver, instead of tagging instances (which is mentioned by @jlowdermilk above doesn't sound like the best option too) and then switching back to apiserver-based one a qurter or two from now once this exists.

**Comment by liggitt** [comment]
> That said, before we are at this point, I think that using those "self-reported" zone information is still better than the current code with assumption of all zones in a region.

would like feedback from @mikedanese before proceeding in that direction

**Comment by wojtek-t** [comment]
@mikedanese - ping - WDYT?

**Comment by mikedanese** [comment]
Sorry, this is a long thread and I haven't read the whole thing. What is the progress on the GCE cloud-controller-manager? Where is GetAllZones being called from? If the GetAllZones is being called central, then moving to node labels is orthagonal work to moving to node labels.

**Comment by msau42** [comment]
GetAllZones is only called when dynamically provisioning GCE PDs.  Provisioning is invoked by the controller-manager.

So the conclusion is we should go ahead with the approach of using the Node's zone labels?

**Comment by davidz627** [comment]
@mikedanese GetAllZones gets called when provisioning GCE-PDs. It is used to determine the available zones for the new PD to be provisioned in.

**Comment by mikedanese** [comment]
Yes. That sounds good to me.

**Comment by wojtek-t** [comment]
Cool - thanks @mikedanese !

**Comment by dims** [comment]
@nfirvine @mikedanese @liggitt @wojtek-t - Do we move this to 1.10?

**Comment by nfirvine** [comment]
@dims I'm just a clueless user. Don't ask me to make decisions 😛

**Comment by msau42** [comment]
@davidz627 is working on a PR #52322 to fix this.  We should be able to get it in.

**Comment by wojtek-t** [comment]
The PR is in pretty good shape in my opinion. I hope it will be in this week.

**Comment by nfirvine** [comment]
I'm still experiencing the issue, on GKE 1.9.3-gke.0. I'm struggling to follow exactly what version @davidz627 's PR https://github.com/kubernetes/kubernetes/pull/52322 would have started at, but surely it's in by now.

**Comment by davidz627** [comment]
It should be in 1.9.3. Could you provide steps to repro your issue?

**Comment by waltz-kaijie** [comment]
still having this issue with kubernetes 1.9.8. Currently I have only one worker node in us-east-1c (but I set 1a,1c,1d in kops) while my default gp2 storageclass created pv in us-east-1a

**Comment by jackzzj** [comment]
still having this issue in 1.9.8. Currently I have only one worker node in us-east-1c (but I set 1a,1c,1d in kops) while my default gp2 storageclass created pv in us-east-1a
