### ISSUE TITLE
Requirements for master metrics API for going to beta

### ISSUE THREAD

**Issue by piosz** [kubernetes/kubernetes#50148]
In 1.8 we want to graduate Master Metrics API to beta. This issue is about collecting feedback on the API and what needs to be changed before beta.

The API was defined in [the proposal](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/resource-metrics-api.md) and implemented in [metrics repo](https://github.com/kubernetes/metrics/tree/master/pkg/apis/metrics).

Related effort - [Metrics Server](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/metrics-server.md).
Feature issue: https://github.com/kubernetes/features/issues/271

@DirectXMan12 you had some thoughts on this. Could you please list them here?

cc @kubernetes/sig-instrumentation-misc @kubernetes/api-reviewers

**Comment by DirectXMan12** [comment]
Yeah, so I think my main requirement for the master metrics API going to beta is moving away from the weirdness involving ObjectMeta.  Currently, the API uses ObjectMeta to convey the target object for the metrics.  This seems strange to me (at least in the current model of how Kubernetes APIs work).  It should instead use an ObjectReference (or something of the sort) to indicate the target object (similarly to the custom metrics API).

Otherwise, I think the general design seems reasonable.

**Comment by smarterclayton** [comment]
Hrm, this is something that should be discussed with sig-api-machinery
since we're not totally clear on it.  We have examples of resources of
different kinds sharing the same object meta in other places (virtual
resources, sub resources, binding).

**Comment by smarterclayton** [comment]
Also Scale

**Comment by DirectXMan12** [comment]
> We have examples of resources of different kinds sharing the same object meta in other places (virtual resources, sub resources, binding).

If metrics were positioned the same was as scale (as a "virtual" resource/interface/subresource), I'd agree with you (hence my somewhat cryptic comment about "in the current model...").  I actually thought of that.  But that's not really how they work currently, so it doesn't quite seem like it fits.  I'll jump on the next SIG-API-Machinery meeting if we haven't resolved it by then.

**Comment by piosz** [comment]
There is a great discussion in [the email thread](https://groups.google.com/forum/#!topic/kubernetes-sig-api-machinery/6NrWA6ynvSk).

The open question is:
How should we reference the object described by `PodMetrics`? Should we still use `ObjectMeta` or migrate to `ObjectReference` which is used in CustomMetricsAPI?

Looking for feedback from @kubernetes/sig-api-machinery-misc @kubernetes/sig-architecture-misc

**Comment by piosz** [comment]
cc @deads2k @erictune @lavalamp

**Comment by smarterclayton** [comment]
Will pod metrics ever have different labels, annotations, uuids, creation timestamps, deletion timestamps, or initializers than pods?  If so, object meta is not appropriate.  If not, then object meta would be appropriate (this is an alternate representation of a pod).

**Comment by deads2k** [comment]
> Will pod metrics ever have different labels, annotations, uuids, creation timestamps, deletion timestamps, or initializers than pods? If so, object meta is not appropriate. If not, then object meta would be appropriate (this is an alternate representation of a pod).

I think this is more like a separate object which has an implicit object reference based on namespace and name. If that information were duplicated, it could fall out sync or would have to be enforced by validation.

Either way, this looks like a choice of the API designer, not something that api-machinery would force onto the API one way or the other.

**Comment by lavalamp** [comment]
If I understand correctly, the question is whether the object meta on this line:

https://github.com/kubernetes/metrics/blob/935b1d6f9c67d2e44b344ac6cbc8d9a6f8c0ffbe/pkg/apis/metrics/types.go#L61

should refer to the pod the metrics are for, rather than the metrics themselves?

After thinking about it, I think it would be OK to do this, if (like scale) the object meta could be EXACTLY the object meta from the pod. But since metrics server is a separate binary, presumably an incomplete or out of date object meta would be served. This would be very confusing if people e.g. tried to rely on the labels.

The object meta on the podmetrics object ought to identify the podmetrics object, not the pod. I think it is fine--given that there is a 1:1 relationship--if people use the object meta to deduce which pod it is for. But I do not think it is ideal to e.g. reuse the pod's UID unless the object meta can always be exactly that of the pod. I think you want e.g. the resourceVersion to refer to the podmetrics, not be copied from the last time you observed the pod.

So, I recommend:
* The object meta is about the podmetrics, not the pod.
* If the namespace & name is not sufficient to identify the pod, then it would be appropriate to have an object reference to identify the pod.

I could sorta go either way on this but that's my first take.

**Comment by smarterclayton** [comment]
I agree with Dan.  We in general want alternate "faces" of an object where
1:1 is identical to use the same object meta.  But if there is any chance
that they diverge, then references apply (i.e. object X is not object Y,
and therefore X references Y via some field).

**Comment by piosz** [comment]
Thanks everyone for your feedback!
