### ISSUE TITLE
Example: Kafka/Zookeeper

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#5017]
Forked from #1675.

Users have been asking how to run Zookeeper and Kafka.

One of the recent threads:
https://groups.google.com/forum/#!topic/google-containers/7e1x1r92SV0

Once multi-port services land, we should use them in an example.

**Comment by smarterclayton** [comment]
https://github.com/openshift/origin/pull/1965  We'll back port it once it gets cleaned up.

**Comment by KyleAMathews** [comment]
@smarterclayton what's the status here? Need to setup Kafka soon on Kubernetes and would love an example to work off.

**Comment by smarterclayton** [comment]
No change from before unfortunately.  There have been a few attempts made -
hostname stability and nominal services would make this easier but we
haven't had a change to tackle those yet.

On Jul 31, 2015, at 11:16 PM, Kyle Mathews <notifications@github.com> wrote:

@smarterclayton <https://github.com/smarterclayton> what's the status here?
Need to setup Kafka soon on Kubernetes and would love an example to work
off.

—
Reply to this email directly or view it on GitHub
<https://github.com/GoogleCloudPlatform/kubernetes/issues/5017#issuecomment-126854737>
.

**Comment by KyleAMathews** [comment]
K, thanks for the reply plus your general awesome work on kubernetes. I'll
probably just place Kafka on its own cluster than in the meantime.

**Comment by ckleban** [comment]
Fwiw, I'm super interested in this as well. 

If desired, when it is appropriate (ie, these new features get released), I wouldn't mind helping build out an example of this.

**Comment by davidopp** [comment]
It would be good to get this upstreamed.

BTW do we have an example of how to run etcd on Kubernetes? Is multi-port services sufficient, or do we need nominal services? See for example
http://stackoverflow.com/questions/32703348/how-to-run-an-etcd-cluster-among-pod-replicas

We have an example of running etcd as static pods in the HA docs but it requires harcoding IPs.

@timstclair this is relevant

**Comment by davidopp** [comment]
Ditto for Consul:
http://serverfault.com/questions/701606/dynamic-commands-and-parameters-in-kubernetes-templates/726558#726558

It would be good for us to have a generic explanation of how to handle these in our documentation, even in the absence of specific examples/ for them. And if the answer is "wait for nominal services, see issue #260" then we can just say that. It would at least give us somewhere to point people when they ask about it.

(And if we already have such documentation, my apologies, please let me know where it is.)

**Comment by yichengq** [comment]
@davidopp We have implemented some work to run a static-deployed etcd cluster on kubernetes. The code is here: https://github.com/coreos/etcd/tree/master/hack/kubernetes-deploy . Does this match your expectation?

/cc @xiang90 @polvi

**Comment by ibotty** [comment]
I don't think that's adressing the pain points one might have:

 * When a pod dies (for any reason) it's not getting restarted
 * When the cluster is stopped, you will have to restore etcd from
   a backup (if that's even possible with that etcd setup)
 * When scaling the etcd cluster, you need to copy the etcdN service and
   pod

**Comment by smarterclayton** [comment]
The last one is acceptable (at least for most use cases).  The first two
are definitely blockers to someone making productive use of etcd.

**Comment by yichengq** [comment]
@ibotty @smarterclayton Do you know is there any way in kubernetes that etcd could have persistent volume in the cluster without additional requirements(e.g., a working nfs, gce account)? I have read through https://github.com/kubernetes/kubernetes/blob/master/docs/user-guide/volumes.md#types-of-volumes, but don't find any solutions.

**Comment by davidopp** [comment]
> @davidopp We have implemented some work to run a static-deployed etcd cluster on kubernetes. The code is here: https://github.com/coreos/etcd/tree/master/hack/kubernetes-deploy . Does this match your expectation?

That looks great - would you mind submitting a PR to upstream that to our examples/ directory?

**Comment by davidopp** [comment]
Yeah unfortunately there is no solution right now. What you need is volumes that outlive Pod lifetime. We have been talking about that for a long time but not implemented it yet. Unfortunately I can't find the issue number right now.

**Comment by ibotty** [comment]
That's issue #260, nominal services, that covering that, right?

**Comment by davidopp** [comment]
Nominal services is related but I was thinking about having local storage that outlives the pod. Today we only support networked storage that outlives the pod (via the mechanism described here: https://github.com/kubernetes/kubernetes/blob/master/docs/user-guide/persistent-volumes.md ) - well I guess there is a reference to HostPath there but it says it doesn't work on multi-node clusters (which makes sense because we need integration with Pod scheduling).

**Comment by smarterclayton** [comment]
I really, really, really, really, want an out of the box solution for
best-effort volumes that outlive their pods and can be used as a cheap
replacement for persistent volumes (for dev / test / prod use cases where
you can survive loss).  But as David notes it's probably a ways out.  The
flocker work is close in concept, and someone could build something similar
today.  Anyone sufficiently motivated should dive in!  :)

On Oct 8, 2015, at 4:55 AM, David Oppenheimer <notifications@github.com>
wrote:

Nominal services is related but I was thinking about having local storage
that outlives the pod. Today we only support networked storage that
outlives the pod (via the mechanism described here:
https://github.com/kubernetes/kubernetes/blob/master/docs/user-guide/persistent-volumes.md
) - well I guess there is a reference to HostPath there but it says it
doesn't work on multi-node clusters (which makes sense because we need
integration with Pod scheduling).

—
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/5017#issuecomment-146462465>
.

**Comment by eliaslevy** [comment]
You can find an example of setting up a ZK cluster under Kubernetes using the existing capabilities at https://hub.docker.com/r/elevy/zookeeper/.  The primary requirement is stable IP addresses and hostnames for the ensemble members.  This is accomplished using individual Services for each cluster member.  The only wrinkle is that by default ZK will attempt to bind to the IP its hostname resolves to, but this can be avoided through a config parameter.

**Comment by davidopp** [comment]
@zmerlynn

**Comment by paralin** [comment]
I'm picking this up now, first writing an example for Zookeeper deployment and then after that writing a Kafka specific example

**Comment by davidopp** [comment]
@paralin Please keep an eye on the discussion of PetSet (#18016), which should simplify Zookeeper deployment.

**Comment by zoidbergwill** [comment]
So we're currently running Kafka and Zookeeper in replication controllers (soon deployments), if it helps at all. But I'll add to the PetSet issues if I can help at all.

**Comment by kant111** [comment]
why do we need ZooKeeper to deploy Kafka on kubernetes? why Kuberentes cannot take care of managing zookeper cluster?

**Comment by etotheipi** [comment]
I was in charge of putting together Kafka on Kubernetes and our application is performance-constrained, which I believe eliminated the option of using NFS/HDFS/etc as the PV-backing for Kafka.  Kafka already has data replication built in and to use some kind of replicated PV would really crush our performance.  Also, there's no point in running multiple Kafka pods on physical node, compared to have one, larger pod on that machine.  In other words, a high-performance kafka deployment really benefits from a more traditional deployment (one per machine with direct & persistent disk space).

My solution was to use DaemonSets with `hostPath` volumes.  The Kafka configuration and all its data is stored behind /var/kafka on the host machines, using zookeeper to fetch a unique ID and create the configuration if it has never been run on that system before.  The daemonset guarantees exactly one pod per host, and the host's `/var/kafka` persists between restarts.

PetSets are a great innovation in this kind of problem, but as far as I can tell you still need some kind of DFS backing.  This may work wonderfully for many applications, but we felt we needed to be closer to the bare metal for this particular integration (producing and consuming millions of messages per sec)

I post this as both an idea and recommendation, as well as a "request for comments" since I'm new to Kubernetes and may be overlooking something.  I had not seen this proposed yet.  I have implemented this and done initial testing to confirm it's functional, but we haven't done an actual production run with it yet.

**Comment by paralin** [comment]
I used to use a similar setup to what you describe but for Cassandra @etotheipi. It works, but make sure you use node selectors to be sure you only put the pods on machines you want to have Kafka. Also, afaik daemon set pods do not have persistent identity with ips and hostnames so make sure Kafka can handle that.

**Comment by smarterclayton** [comment]
You can also use (abuse?) PV node selectors to force the scheduler to
assign pets to particular machines.  The evolving proposals for local disk
look like they're going to go down that path.

**Comment by etotheipi** [comment]
@paralin  Thanks -- I am fairly confident that the shifting IP/hostnames is not an issue, but I haven't tested it yet.  I set Kafka's "advertised" hostname to the PodIP which should update its own entry in zookeeper (for other brokers to find) as soon as the new instance is started.   Node selectors are also a good point, which we will use to partition the network as needed.

@smarterclayton: Seems like a bit of a hack of PetSets to make them act more like DaemonSets.  Perhaps necessary, though, if you need the persistent network identity.

**Comment by smarterclayton** [comment]
@etotheipi PVs can influence scheduling, therefore pet sets can be location
aware.  In the long run, PetSets will be the correct way to run all
services where the # of things is more important than where they go, so
it's fine to use DaemonSets this way to work around the gap, but we intend
to fix PetSets and volumes so you can use volumes with data gravity with
PetSets.

**Comment by joan38** [comment]
Really looking forward to see Kafka supported by Kubernetes!

**Comment by aegixx** [comment]
@etotheipi Any update on the progress you made?  Any link to the work-in-progress?  I'm willing to help with this effort.

**Comment by sam-obeid** [comment]
@etotheipi I am willing to help test this too.

**Comment by dminkovsky** [comment]
Great example here: http://kubernetes.io/docs/tutorials/stateful-application/zookeeper/ @KyleAMathews

**Comment by kow3ns** [comment]
FWIW we have ZooKeeper as a [helm chart in incubator](https://github.com/kubernetes/charts/tree/master/incubator/zookeeper). I'm working on a Kafka chart presently, but it will take some time.

**Comment by bamb00** [comment]
What was decided for deploying etcd cluster using Stateful Sets?

**Comment by kow3ns** [comment]
@bamb00 There is a helm chart that uses PetSet here https://github.com/kubernetes/charts/tree/master/incubator/etcd. It could easily be modified to use StatefulSet.

**Comment by bamb00** [comment]
@kow3ns thanks for the response.  I'm a little bit overwhelm looking over the etcd-petset.yaml file in templates.

Can I modified the yaml in templates as a stand-alone? or I need to use it with the helm application.

**Comment by bamb00** [comment]
Can someone tell me what I'm doing wrong from etcd-0 pod log?

2017-03-14T04:21:43.142152232Z sh: cd-1: bad number
2017-03-14T04:21:43.142894287Z Waiting for etcd-0.etcd to come up
2017-03-14T04:22:13.174109903Z ping: bad address 'etcd-0.etcd'
2017-03-14T04:22:14.174744217Z Waiting for etcd-0.etcd to come up
2017-03-14T04:22:44.196713721Z ping: bad address 'etcd-0.etcd'
2017-03-14T04:22:45.197387229Z Waiting for etcd-0.etcd to come up
2017-03-14T04:23:15.224021300Z ping: bad address 'etcd-0.etcd'
2017-03-14T04:23:16.224397053Z Waiting for etcd-0.etcd to come up
2017-03-14T04:23:46.256320372Z ping: bad address 'etcd-0.etcd'

**Comment by joan38** [comment]
What's the reason for closing this issue?

**Comment by codependent** [comment]
I wonder the same thing. ??

**Comment by kow3ns** [comment]
https://github.com/kubernetes/contrib/pull/2554

**Comment by joan38** [comment]
Cheers kow3ns
