### ISSUE TITLE
[Flexvolume] Need to clarify thread safe of flexvolume functions

### ISSUE THREAD

**Issue by resouer** [kubernetes/kubernetes#50210]
It seems we don't have a clear answer to this question: 

> Do users need to make sure functions in flexvolume binary are thread safe, or flexvolume already guaranteed it before executing them (which I guess so)?

I did not find any clarification in documentation or example, but it seems to be a question deserves a explanation somewhere. (correct me if I missed sth)

cc @jingxu97 @saad-ali

**Comment by jingxu97** [comment]
@resouer sorry for the late reply.

For most of the volume plugins, operation_executor.go makes sure that for one volume (uniquely identified by internal volume name), only one operation (e.g., attach/detach, mount/umount device) can be performed at a time. It does allow bind mount concurrently if the volume is used by multiple pods. So there is no need to have thread safe.

However, flexvolume is bit of tricky. the internal volume name constructed for flexvolume is actually not unique. It is just the name in the volume spec inside of the pod spec. So it has the following potential problems
1. If two pods happen to use the same volume name in the pod volume spec, the first volume will be attached/mounted correctly, but the second volume might not try to attach/mount because the actual state shows that the same volume is already attached and mounted.
2. If two pods use different volume name in the pod volume spec but the underlying disk is the same, controller might issue functions on the same disk concurrently.

These are the limitations of the flexvolume implementation. Please let us know if you have issues, we can work on fixing them. Thanks!
