### ISSUE TITLE
IPv6 prefix size is limited to 64 with kube-controller-manager

### ISSUE THREAD

**Issue by rpothier** [kubernetes/kubernetes#50395]
/kind bug

**What happened**:
With https://github.com/kubernetes/kubernetes/pull/43586, 
the controller manager will accept IPv6 addresses
with the  --cluster-cidr flag.
The prefix length is currently limited to /64 with
maxPrefixLength = 64

**What you expected to happen**:
The question here is if this limit should be removed, and allow a greater
prefix size or if this limit should remain.

**How to reproduce it (as minimally and precisely as possible)**:
giving the kube-controller-manager --cluster-cidr a value of 65 or greater

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by rpothier** [comment]
cc @aanm

**Comment by aanm** [comment]
If a user receives an allocation of /64 to its network, and he wants to expose his pods to the outside world, he needs to have a bigger prefix length for its pods. So that he could at least split his network into 2 /80 networks, one for pods and the other for the remaining machines.

The prefix length should not matter as the network plugins will be, or should be at least, in charge of the routing to and from those pods. Giving a node cidr mask size of, for example, /96, each node would still end up with 2^32 addresses to give away for the pod running. Since those addresses are assigned by an IPAM, also provided by the same network plugins, it shouldn't matter the size of the node CIDR.

Does it makes sense?
