### ISSUE TITLE
OpenStack Cinder version detection fails (and is incorrect)

### ISSUE THREAD

**Issue by mnaser** [kubernetes/kubernetes#50461]
/kind bug

**What happened**:
When running Kubernetes against an installation of DevStack which deploys the Cinder service at a path rather than a port (ex: http://foo.bar/volume rather than http://foo.bar:xxx), the version detection fails.

**What you expected to happen**:
The version detection should never happen.  The best way to detect version is by using the OpenStack service catalog.  As per the [service types authority](http://specs.openstack.org/openstack/service-types-authority/), the services will be labeled `cinder` for V1, `cinderv2` for V2 and `cinderv3` for V3.  This is the correct way of detecting the right Cinder version.

**How to reproduce it (as minimally and precisely as possible)**:
Install DevStack and attempt to launch a volume with Kubernetes integrated to that cloud (or any cloud that runs Cinder in a path.

**Anything else we need to know?**:
There should never be a case where `cinder`, `cinderv2` and `cinderv3` don't give the right information as all major documentation (and installation tools) point to doing this:

- [Manual Installation](https://docs.openstack.org/cinder/latest/install/cinder-controller-install-rdo.html)
- [Puppet, TripleO](https://github.com/openstack/puppet-cinder/blob/master/manifests/keystone/auth.pp)
- [OpenStack Ansible](https://github.com/openstack/openstack-ansible-os_cinder/blob/master/tasks/cinder_service_setup.yml)

**Environment**:
- Kubernetes version (use `kubectl version`): 1.7.3
- Cloud provider or hardware configuration**: OpenStack clouds
- OS (e.g. from /etc/os-release): fedora atomic
- Kernel (e.g. `uname -a`): latest
- Install tools: magnum
- Others:

**Comment by j-griffith** [comment]
@mnaser Could you provide the log information for the failure and your config if you get a chance?  If a bsVersion isn't specified I believe the auto detection in openstack.go still works even with the new unified API endpoint names.  It does in fact call out to keystone to find the endpoints, so this should still work but I might be missing something.  I'll try and set up a fresh env today and have a closer look.

**Comment by mnaser** [comment]
@j-griffith 

If you try to setup a devstack environment without specifying bs-version in the cloud configuration, you'll notice errors in version detection.

**Comment by dims** [comment]
yep, i can confirm @mnaser 's observation

**Comment by j-griffith** [comment]
@mnaser I just deployed current devstack and in my cloud_config.conf I omitted the BlockStorage section altogether.  Building/Launching with local-up-cluster.sh all services deployed, the openstack provider fell back to the default auto flag and was succesfully able to create pods and attach cinder volumes.  I did note that omitting the auth url version in the conf does introduce a problem which I'll look at next but that seems unrelated to what your'e reporting here.

Maybe if you provide your conf I can try and duplicate, otherwise here's what my cloud_config.conf looks like (note I've omitted the BlockStorage section comletely):

[Global]
auth-url=http://10.117.36.3/identity/v3
username=admin
password=nomoresecret
region=RegionOne
tenant-id=430a8d416b6a4688a8205c92757ec5a5
domain-name=Default

**Comment by j-griffith** [comment]
@dims hmm.. I missed your post; ok.. I'm obviously missing a key to this somewhere

**Comment by ArchiFleKs** [comment]
I can confirm this on freshly deployed OpenStack Pike deployment.

I have cinder v1, v2 and v3. To make cinder works, I had to add 

```
[BlockStorage]
bs-version=v2
```

To cloud_config file.

Maybe we need to support v3 here:

https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/openstack/openstack.go#L660

**Comment by xsgordon** [comment]
@ArchiFleKs unfortunately just updating the check isn't enough for v3, as we need gophercloud support for it. I had filed https://github.com/gophercloud/gophercloud/issues/305 tracking this request a while back, which it looks like https://github.com/gophercloud/gophercloud/pull/415 would resolve. Once *that* merges we can then need to pick that version of gophercloud up and can use this check.

Now that said, I'm wondering if for now as a workaround we could potentially make the check automatically fallback to v2 when it encounters v3? If I'm reading it correctly currently both v2.0 and v3.0 are considered CURRENT/SUPPORTED and this in scope for doBsApiVersionAutodetect but the sort interface ensures that v3.0 is picked because it is higher (which normally would be fine, except for the aforementioned gap in v3.0 support).
