### ISSUE TITLE
DumpClusterLogs is failing for kubeadm e2es

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#50760]
https://k8s-testgrid.appspot.com/release-1.7-blocking#gce-kubeadm-1.7
https://k8s-testgrid.appspot.com/release-1.7-blocking#gce-kubeadm-1.6-on-1.7

@luxas

**Comment by shyamjvs** [comment]
I just looked into this. So apparently DumpClusterLogs was also failing before (when it was happening as part of e2e framework):

```
I0807 23:54:38.549] Aug  7 23:54:38.548: INFO: Running AfterSuite actions on node 1
I0807 23:54:38.816] Aug  7 23:54:38.816: INFO: Error running cluster/log-dump/log-dump.sh: exit status 127
```

(ref: https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-gce-1-6-on-1-7/96/build-log.txt)

However it was silently skipped because e2e framework doesn't fail on failure of logdump. Now (after PR https://github.com/kubernetes/test-infra/pull/3974 got merged), we're doing it as a step inside kubetest which exposed the bug.

**Comment by shyamjvs** [comment]
It says exit status 127, which usually means some command doesn't exist. And since nothing is printed, seems like it failed even before reaching the first echo statement in log-dump.sh.
Which most likely means somewhere in the [setup() function](https://github.com/kubernetes/kubernetes/blob/release-1.7/cluster/log-dump/log-dump.sh#L250)
I'll add some debugging statements to the script.

**Comment by shyamjvs** [comment]
cc @kubernetes/test-infra-maintainers - Is some non-default bash version or sth used in kubeadm test?

**Comment by krzyzacy** [comment]
cc @pipejakob

**Comment by pipejakob** [comment]
@shyamjvs You can see the image definition here: https://github.com/kubernetes/test-infra/blob/master/images/kubeadm/Dockerfile

It extends the normal kubekins-e2e image, so I would be surprised if it has a different version of bash or other inconsistencies (although one of the first steps in building the image is an `apt-get update`, so it's possible that it would pull in a newer version of bash during the subsequent `apt-get install` step).

**Comment by pipejakob** [comment]
Something that immediately comes to mind: if our e2e framework assumes that `$CWD` is the root of the kubernetes/kubernetes repository and invokes `cluster/log-dump/log-dump.sh` as a relative target, it's entirely possible that our current working directory is different. We also clone/use the kubernetes-anywhere repository, and have had path problems in our jobs before (like https://github.com/kubernetes/test-infra/pull/2179).

**Comment by shyamjvs** [comment]
@krzyzacy @pipejakob I don't think the issue is with the path because then it complains saying that the file or directory doesn't exist. Also the dir structure looks fine (I checked from within the container):

```
root@11981aad-82b3-11e7-967d-0a580a6c1150:/workspace# ls
_artifacts  build-log.txt  e2e-runner.sh  gcloud-info.txt  get-kube.sh	google-cloud-sdk.tar.gz  kops-e2e-runner.sh  kubernetes  kubernetes.tar.gz  kubetest  test-infra
```

So kubernetes repo is at the same level as that of kubetest (from where we call the log-dump script).

**Comment by shyamjvs** [comment]
There are at least 2 things I find wrong here:

```
$ echo $KUBE_GCE_INSTANCE_PREFIX 
jenkins-e2e
```

This is clearly wrong and I'm sure it's coming from the Dockerfile - https://github.com/kubernetes/test-infra/blob/master/jenkins/e2e-image/Dockerfile#L48
Though the build-log shows it to be set as the right value - `W0816 00:05:18.423] KUBE_GCE_INSTANCE_PREFIX=e2e-117`

Secondly, the local artifacts path being passed to the log-dump script is wrong:

```
W0816 01:10:15.040] 2017/08/16 01:10:14 util.go:131: Running: ./cluster/log-dump/log-dump.sh /workspace/k8s.io/kubernetes/_artifacts
```

which in turn is coming from kubetest's --dump flag:

```
W0816 01:12:38.411] subprocess.CalledProcessError: Command '('kubetest', '-v', '--dump=/workspace/k8s.io/kubernetes/_artifacts', bla bla bla ...
```

which in turn is coming from kubernetes_e2e.py from this line - https://github.com/kubernetes/test-infra/blob/master/scenarios/kubernetes_e2e.py#L450
And this is weird because the env var WORKSPACE has been set to the right value of `/workspace` (I checked from within the prow container) and it's set in bootstrap.py.

**Comment by shyamjvs** [comment]
Oops - I guess I was looking at the wrong container. Prow led me to the wrong one when I did a `kubectl describe pods` on the prow cluster.

**Comment by wojtek-t** [comment]
@shyamjvs What's the status of it? It's still broken.

**Comment by shyamjvs** [comment]
I made a few changes to kubetest and kubeadm to catch the issue (https://github.com/kubernetes/test-infra/pull/4094).
Waiting for the current run (#123), which has those changes, to finish.

**Comment by shyamjvs** [comment]
Aand.... I just see the result uploaded for it. I'm looking into it.

**Comment by shyamjvs** [comment]
The above PR should give some info where exactly it's failing.

**Comment by pipejakob** [comment]
This is also happening in our master job now. There was a kubelet regression that was causing a failure much earlier, but now that it has been fixed, we're seeing the same failures in the kubeadm-gce job:

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-gce/5157

**Comment by shyamjvs** [comment]
@krzyzacy I've added debug statements in #50914 and none of them are printed, even the first log at the top of the file - https://github.com/kubernetes/kubernetes/blob/release-1.7/cluster/log-dump/log-dump.sh#L30. This should confirm that it's some problem at the kubetest level. Assigning this bug to you as it's test-infra related :)

**Comment by krzyzacy** [comment]
oh wait, why that's committed in release-1.7 instead of master?

**Comment by shyamjvs** [comment]
Because initially it was failing only on 1.7

**Comment by krzyzacy** [comment]
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/periodic-kubernetes-e2e-kubeadm-gce-1-7/750?log#log

**Comment by krzyzacy** [comment]
```
Ginkgo ran 1 suite in 59m18.20928041s
I0822 21:18:53.589] Test Suite Passed
W0822 21:18:53.690] 2017/08/22 21:18:53 util.go:133: Step './hack/ginkgo-e2e.sh --ginkgo.focus=\[Conformance\] --minStartupPods=8 --report-dir=/workspace/k8s.io/kubernetes/_artifacts --disable-log-dump=true' finished in 59m18.893690775s
W0822 21:18:53.705] 2017/08/22 21:18:53 e2e.go:460: Dumping logs locally to: /workspace/k8s.io/kubernetes/_artifacts
W0822 21:18:53.706] 2017/08/22 21:18:53 util.go:131: Running: ./cluster/log-dump/log-dump.sh /workspace/k8s.io/kubernetes/_artifacts
I0822 21:18:53.807] Checking for custom logdump instances, if any
I0822 21:18:53.807] Obtaining IPs and images for cluster nodes
I0822 21:18:53.808] Obtaining KUBE_ROOT
I0822 21:18:53.813] Sourcing kube-util.sh
I0822 21:18:53.822] Detecting project
I0822 21:18:53.865] make: Entering directory '/workspace/kubernetes-anywhere'
I0822 21:18:53.942] /workspace/kubernetes-anywhere/phase1/gce/.tmp/kubeconfig.json
I0822 21:18:53.944] make: Leaving directory '/workspace/kubernetes-anywhere'
I0822 21:18:53.949] make: Entering directory '/workspace/kubernetes-anywhere'
I0822 21:18:53.981] make do WHAT=destroy-cluster
I0822 21:18:53.993] make[1]: Entering directory '/workspace/kubernetes-anywhere'
I0822 21:18:54.025] ( cd "phase1/$(jq -r '.phase1.cloud_provider' .config.json)"; ./do destroy-cluster )
W0822 21:18:54.127] 2017/08/22 21:18:53 util.go:133: Step './cluster/log-dump/log-dump.sh /workspace/k8s.io/kubernetes/_artifacts' finished in 126.685403ms
W0822 21:18:54.128] 2017/08/22 21:18:53 util.go:131: Running: make -C /workspace/kubernetes-anywhere kubeconfig-path
W0822 21:18:54.128] 2017/08/22 21:18:53 util.go:133: Step 'make -C /workspace/kubernetes-anywhere kubeconfig-path' finished in 109.718384ms
W0822 21:18:54.129] 2017/08/22 21:18:53 util.go:131: Running: make -C /workspace/kubernetes-anywhere FORCE_DESTROY=y destroy
W0822 21:18:54.130] + cd .
W0822 21:18:54.130] + case "${1:-}" in
W0822 21:18:54.131] + destroy
W0822 21:18:54.131] + FLAGS=
W0822 21:18:54.132] + [[ y == \y ]]
W0822 21:18:54.133] + FLAGS=-force
W0822 21:18:54.134] + terraform destroy -var-file .tmp/terraform.tfvars -force .tmp
I0822 21:18:54.892] tls_private_key.e2e-750-admin: Refreshing state... (ID: de8b6fc3fb2281dc432634fc2c7269157983955b)
I0822 21:18:54.895] tls_private_key.e2e-750-master: Refreshing state... (ID: d7eed877020336c954fdd00159dd56620ac7be7e)
I0822 21:18:54.896] tls_private_key.e2e-750-root: Refreshing state... (ID: 150a4b5b7613452f27d26cc32556e56a26cb2d0e)
I0822 21:18:54.896] tls_private_key.e2e-750-node: Refreshing state... (ID: bec7c696ff1539ad70fc1f9bb2e56d5794ab3d54)
I0822 21:18:54.913] google_compute_firewall.ssh_all: Refreshing state... (ID: e2e-750-ssh-all)
I0822 21:18:54.914] google_compute_address.e2e-750-master-ip: Refreshing state... (ID: e2e-750-master-ip)
I0822 21:18:54.915] tls_self_signed_cert.e2e-750-root: Refreshing state... (ID: 159893051776131564057319023467906018310)
I0822 21:18:54.921] google_compute_firewall.e2e-750-master-https: Refreshing state... (ID: e2e-750-master-https)
I0822 21:18:54.923] google_compute_firewall.e2e-750-node-all: Refreshing state... (ID: e2e-750-node-all)
I0822 21:18:54.923] google_compute_firewall.e2e-750-master-internal: Refreshing state... (ID: e2e-750-master-internal)
I0822 21:18:54.923] data.tls_cert_request.e2e-750-admin: Refreshing state...
I0822 21:18:54.924] data.tls_cert_request.e2e-750-node: Refreshing state...
I0822 21:18:54.935] tls_locally_signed_cert.e2e-750-admin: Refreshing state... (ID: 143356561666263003762960451637646759288)
I0822 21:18:54.946] tls_locally_signed_cert.e2e-750-node: Refreshing state... (ID: 40611791448404966872352632414765112494)
I0822 21:18:55.260] null_resource.kubeconfig: Refreshing state... (ID: 713210085162247013)
I0822 21:18:55.262] data.tls_cert_request.e2e-750-master: Refreshing state...
I0822 21:18:55.274] tls_locally_signed_cert.e2e-750-master: Refreshing state... (ID: 271029116076692677576127409721216973150)
I0822 21:18:55.279] google_compute_instance.e2e-750-master: Refreshing state... (ID: e2e-750-master)
I0822 21:18:55.442] google_compute_instance_template.e2e-750-node-instance-template: Refreshing state... (ID: e2e-750-node-instance-template)
I0822 21:18:55.578] google_compute_instance_group_manager.e2e-750-node-group: Refreshing state... (ID: e2e-750-node-group)
I0822 21:18:56.033] google_compute_instance_group_manager.e2e-750-node-group: Destroying...... skipping 169 lines ...
I0822 20:14:21.331] Extracting kubernetes-test.tar.gz into /workspace/k8s.io/kubernetes/kubernetes
W0822 20:14:56.706] 2017/08/22 20:14:56 util.go:133: Step '/workspace/get-kube.sh' finished in 51.823651101s
W0822 20:14:58.217] 2017/08/22 20:14:58 util.go:131: Running: make -C /workspace/kubernetes-anywhere kubeconfig-path
I0822 20:14:59.829] make: Entering directory '/workspace/kubernetes-anywhere'
I0822 20:15:00.000] util/config_to_json .config > .config.json
W0822 20:15:01.443] Cannot find kubeconfig file. Have you started a cluster with "make deploy" yet?
W0822 20:15:01.443] make: *** [kubeconfig-path] Error 1
W0822 20:15:01.444] 2017/08/22 20:15:01 util.go:133: Step 'make -C /workspace/kubernetes-anywhere kubeconfig-path' finished in 3.226933871s
W0822 20:15:01.445] 2017/08/22 20:15:01 util.go:131: Running: make -C /workspace/kubernetes-anywhere WAIT_FOR_KUBECONFIG=y deploy
W0822 20:15:01.503] + cd .
W0822 20:15:01.504] + case "${1:-}" in
W0822 20:15:01.504] + deploy
W0822 20:15:01.504] + gen
W0822 20:15:01.505] ++ generate_token
W0822 20:15:01.505] ++ perl -e 'printf "%06x.%08x%08x\n", rand(0xffffff), rand(0xffffffff), rand(0xffffffff);'
I0822 20:15:01.606] Makefile:46: recipe for target 'kubeconfig-path' failed
```

**Comment by krzyzacy** [comment]
(I don't quite understand where are things below `Detecting project` comes from?)

/assign @shyamjvs @pipejakob 
maybe you are more familiar with stuff here and wanna help taking a look?

**Comment by shyamjvs** [comment]
So, I looked into this a bit and here's what I found:
- Something seems weird with the output of commands run using `finishRunning`. They don't seem to be aligned wrt. order of prints to stdout. For e.g from run 755's build-log (https://storage.googleapis.com/kubernetes-jenkins/logs/periodic-kubernetes-e2e-kubeadm-gce-1-7/755/build-log.txt):

```
I0823 07:22:58.832] Ginkgo ran 1 suite in 1h0m49.918719104s
I0823 07:22:58.832] Test Suite Passed
I0823 07:22:58.863] Checking for custom logdump instances, if any
I0823 07:22:58.865] Obtaining IPs and images for cluster nodes
I0823 07:22:58.865] Obtaining KUBE_ROOT
I0823 07:22:58.865] Sourcing kube-util.sh
I0823 07:22:58.867] Detecting project
I0823 07:22:58.869] make: Entering directory '/workspace/kubernetes-anywhere'
I0823 07:22:58.897] /workspace/kubernetes-anywhere/phase1/gce/.tmp/kubeconfig.json
I0823 07:22:58.897] make: Leaving directory '/workspace/kubernetes-anywhere'
I0823 07:22:58.898] make: Entering directory '/workspace/kubernetes-anywhere'
I0823 07:22:58.904] make do WHAT=destroy-cluster
I0823 07:22:58.906] make[1]: Entering directory '/workspace/kubernetes-anywhere'
I0823 07:22:58.910] ( cd "phase1/$(jq -r '.phase1.cloud_provider' .config.json)"; ./do destroy-cluster )
W0823 07:22:59.011] 2017/08/23 07:22:58 util.go:133: Step './hack/ginkgo-e2e.sh --ginkgo.focus=\[Conformance\] --minStartupPods=8 --report-dir=/workspace/k8s.io/kubernetes/_artifacts --disable-log-dump=true' finished in 1h0m51.115301451s
W0823 07:22:59.011] 2017/08/23 07:22:58 e2e.go:460: Dumping logs locally to: /workspace/k8s.io/kubernetes/_artifacts
W0823 07:22:59.011] 2017/08/23 07:22:58 util.go:131: Running: ./cluster/log-dump/log-dump.sh /workspace/k8s.io/kubernetes/_artifacts
W0823 07:22:59.011] 2017/08/23 07:22:58 util.go:133: Step './cluster/log-dump/log-dump.sh /workspace/k8s.io/kubernetes/_artifacts' finished in 35.312199ms
``` 

The logs `Sourcing kube-util.sh`, `Detecting project`, etc are from log-dump.sh script while the script itself is shown to be running later (see last 2 lines). Maybe it's due to stdout coming from 2 processes? I never understood stdout and buffered writes so well, but it would be good to have this fixed (cc @kubernetes/test-infra-maintainers)

- @krzyzacy : Those logs from kubernetes-anywhere are coming from some scripts inside kubernetes-anywhere repo (more specifically - https://github.com/kubernetes/kubernetes-anywhere/blob/master/phase1/gce/do). It seems to be an alternative way of cluster setup that kubeadm is using.

- I'm almost sure the log-dump script itself is failing in the `detect-project` step (since we seem to use a different setup here). I'll make a change to expose why it's failing.

**Comment by luxas** [comment]
Renamed this as it happens on master as well.

Latest failure log extract for reference:
```
W0823 12:47:12.591] 2017/08/23 12:47:12 util.go:133: Step 'make -C /workspace/kubernetes-anywhere FORCE_DESTROY=y destroy' finished in 2m25.611304723s
W0823 12:47:12.591] 2017/08/23 12:47:12 main.go:204: Saved XML output to /workspace/k8s.io/kubernetes/_artifacts/junit_runner.xml.
W0823 12:47:12.591] 2017/08/23 12:47:12 main.go:245: Something went wrong: encountered 1 errors: [error during ./cluster/log-dump/log-dump.sh /workspace/k8s.io/kubernetes/_artifacts: exit status 127]
W0823 12:47:12.591] Traceback (most recent call last):
W0823 12:47:12.592]   File "/workspace/./test-infra/jenkins/../scenarios/kubernetes_e2e.py", line 682, in <module>
W0823 12:47:12.592]     main(parse_args())
W0823 12:47:12.592]   File "/workspace/./test-infra/jenkins/../scenarios/kubernetes_e2e.py", line 545, in main
W0823 12:47:12.592]     mode.start(runner_args)
W0823 12:47:12.592]   File "/workspace/./test-infra/jenkins/../scenarios/kubernetes_e2e.py", line 223, in start
W0823 12:47:12.592]     check_env(env, self.command, *args)
W0823 12:47:12.592]   File "/workspace/./test-infra/jenkins/../scenarios/kubernetes_e2e.py", line 62, in check_env
W0823 12:47:12.592]     subprocess.check_call(cmd, env=env)
W0823 12:47:12.592]   File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
W0823 12:47:12.592]     raise CalledProcessError(retcode, cmd)
W0823 12:47:12.592] subprocess.CalledProcessError: Command '('kubetest', '-v', '--dump=/workspace/k8s.io/kubernetes/_artifacts', '--gcp-service-account=/etc/service-account/service-account.json', '--up', '--down', '--test', '--cluster=e2e-5185', '--gcp-network=e2e-5185', '--deployment=kubernetes-anywhere', '--extract=ci/latest', '--gcp-zone=us-central1-f', '--kubernetes-anywhere-kubernetes-version=latest', '--provider=kubernetes-anywhere', '--test_args=--ginkgo.focus=\\[Conformance\\]|\\[Feature:BootstrapTokens\\]|\\[Feature:NodeAuthorizer\\] --minStartupPods=8', '--timeout=300m', '--kubernetes-anywhere-path=/workspace/kubernetes-anywhere', '--kubernetes-anywhere-phase2-provider=kubeadm', '--kubernetes-anywhere-cluster=e2e-5185', '--kubernetes-anywhere-kubeadm-version=gs://kubernetes-release-dev/bazel/v1.8.0-alpha.3.57+33821862cef030/bin/linux/amd64/')' returned non-zero exit status 1
E0823 12:47:12.593] Command failed
I0823 12:47:12.593] process 290 exited with code 1 after 65.3m
E0823 12:47:12.593] FAIL: ci-kubernetes-e2e-kubeadm-gce
I0823 12:47:12.593] Upload result and artifacts...
I0823 12:47:12.593] Gubernator results at https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-gce/5185
I0823 12:47:12.593] Call:  gsutil ls gs://kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-gce/5185/artifacts
W0823 12:47:14.200] CommandException: One or more URLs matched no objects.
E0823 12:47:14.301] Command failed
I0823 12:47:14.301] process 2560 exited with code 1 after 0.0m
W0823 12:47:14.301] Remote dir gs://kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-gce/5185/artifacts not exist yet
I0823 12:47:14.301] Call:  gsutil -m -q -o GSUtil:use_magicfile=True cp -r -c -z log,txt,xml _artifacts gs://kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-gce/5185/artifacts
I0823 12:47:16.542] process 2693 exited with code 0 after 0.0m
I0823 12:47:16.543] Call:  git rev-parse HEAD
I0823 12:47:16.643] process 3037 exited with code 0 after 0.0m
```

cc @jdumars for the tracking of this infra failure

**Comment by luxas** [comment]
(meta: should we mark this v1.8 as it affects that as well and is more important to track?)

**Comment by pipejakob** [comment]
@shyamjvs Based on the job output, it looks like the flag `--disable-log-dump=true` is being set. Do we know why this isn't fully short-circuiting the `log-dump.sh` invocation altogether?

**Comment by krzyzacy** [comment]
is that because we are not dumping from ginkgo anymore, but always route to log-dump.sh now?

**Comment by shyamjvs** [comment]
@pipejakob It is short-circuiting the invocation. The logs you see are from the `DumpClusterLogs` invocation inside kubetest. Like @krzyzacy said, we're not doing it as part of ginkgo anymore.

**Comment by pipejakob** [comment]
Got it. Is there a new flag to disable the new log dumping until it's working for these jobs?

**Comment by krzyzacy** [comment]
https://github.com/kubernetes/test-infra/blob/master/kubetest/anywhere.go#L170-L172

I think you can always disable/implement your own logdump method there.

**Comment by pipejakob** [comment]
@krzyzacy Great, I didn't realize that's how it was implemented. Definitely seems like we should just disable this call until we can get it working (which should be tracked in https://github.com/kubernetes/kubeadm/issues/256). I'll open a PR for it.

**Comment by pipejakob** [comment]
Still testing locally, but https://github.com/kubernetes/test-infra/pull/4164 should disable the cluster log dumping altogether.

**Comment by shyamjvs** [comment]
I'll send a fix for this and revert https://github.com/kubernetes/test-infra/pull/4164 (as we shouldn't disable log-dump just because it's failing).

**Comment by pipejakob** [comment]
With https://github.com/kubernetes/test-infra/pull/4164 merged, our kubeadm e2e tests went back to green. Our 1.7 tests are still green, but now the master tests have gone back to failing for a new problem in `BeforeSuite`.

Since log dumping was never supported for these e2e jobs, and was only turned on accidentally, I think keeping it disabled is a fine fix for now. @shyamjvs if you want to work on getting log dumping working, we should probably follow up in the original issue https://github.com/kubernetes/kubeadm/issues/256 that was meant for tracking adding the support. As of now, though, the original intent of this issue is resolved, so I'm closing.

**Comment by shyamjvs** [comment]
I'm not sure if you should close this issue in favour of the other (which you filed in the kubeadm repo).
Technically this is an issue in test-infra (or more loosely k8s repo). But I wouldn't push hard.

> Since log dumping was never supported for these e2e jobs, and was only turned on accidentally, I think keeping it disabled is a fine fix for now.

IIUC log-dumping was always turned on for these e2e jobs (it was just failing in a way that went unnoticed unitl recently). So I don't think this is a fix The real problem still remains. :)

**Comment by shyamjvs** [comment]
That said, I've discovered the exact problem and explained it in https://github.com/kubernetes/kubernetes/issues/50760#issuecomment-324618175.
I can fix it, but I'm having some more pressing issues on my plate currently - so this has to wait.

**Comment by pipejakob** [comment]
> I'm not sure if you should close this issue in favour of the other (which you filed in the kubeadm repo).
Technically this is an issue in test-infra (or more loosely k8s repo). But I wouldn't push hard.

True. I often struggle with exactly where an issue should live, and wouldn't mind it moving to test-infra instead. I think different developers tend to look at issues in different repositories. I would assume that mostly the EngProd and SIG Testing teams would be tracking the issues in test-infra, but would want to ignore this particular issue. Since the core audience who would care about this functionality, want it implemented, and actually own the implementation are the kubeadm developers, it felt natural to place https://github.com/kubernetes/kubeadm/issues/256 in the kubeadm repository at the time, even though the actual changes to be made would live in test-infra, kubernetes-anywhere, and possibly even kubernetes.

> IIUC log-dumping was always turned on for these e2e jobs (it was just failing in a way that went unnoticed unitl recently).

You are probably technically correct, so I'll revise my claim: I was the one who originally wrote these jobs, and I didn't expect that cluster log dumping was actually working at all :-). The jobs might have been invoking it and failing silently up until now (or invoking it and basically being a no-op), so I don't consider this a defect that needs to be fixed because the functionality was never actually working. I consider it a new feature that I would like to see implemented. That's probably splitting hairs, though.

In either case, if you would like to do the work to make cluster log dumping happen for these jobs, then awesome!
