### ISSUE TITLE
zero-value settings for kube-proxy being overwritten by default values

### ISSUE THREAD

**Issue by tpetr** [kubernetes/kubernetes#50787]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
We run instances of `kube-proxy` outside of our Kubernetes cluster to make cluster IPs work everywhere. Conntrack settings are already tuned on these machines, so we use the following args to ensure `kube-proxy` does not alter them:
- `--conntrack-max-per-core=0`
- `--conntrack-tcp-timeout-close-wait=0`
- `--conntrack-tcp-timeout-established=0`

When we upgraded `kube-proxy` from 1.5.5 to 1.7.3 we noticed that these args became invalid (timeouts are now a `Duration`), so we switched over to a proper config file:

```yaml
apiVersion: componentconfig/v1alpha1
clientConnection:
  kubeconfig: /path/to/kubeconfig.yaml
conntrack:
  maxPerCore: 0
  tcpCloseWaitTimeout: 0s
  tcpEstablishedTimeout: 0s
kind: KubeProxyConfiguration
mode: iptables
```

The issue is that`kube-proxy` started setting the default conntrack values, even though we set these keys to zero (as the help docs suggested) in the config file. We ultimately had to set these values to `-1` and `-1s` to make things work properly.

My gut is telling me that when `kube-proxy` merges together the configs, it's treating zero values as if they were not set at all (thus falling back to the default values). Can we either fix this or update the help docs?

**What you expected to happen**:
I expected the help docs (`kube-proxy -h`) to be accurate; that zero values would cause `kube-proxy` to not alter conntrack settings.

**How to reproduce it (as minimally and precisely as possible)**:
Set `kube-proxy` conntrack args to `0` / `0s`, observe that `kube-proxy` still attempts to change conntrack settings.

**Anything else we need to know?**:
- Appears to have started in 1.7
- I only had a chance to test conntrack-related args, but I believe this affects all of `kube-proxy`'s numeric settings that advertise zero as a "disabled" value.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.7.3
- Cloud provider or hardware configuration**: AWS
- OS (e.g. from /etc/os-release): CentOS
- Kernel (e.g. `uname -a`): `Linux deep-shape 4.9.35-hs343.el6.x86_64 #1 SMP Wed Jul 12 01:59:52 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by MrHohn** [comment]
cc @ncdc

**Comment by ncdc** [comment]
I think that prior to the config file, the defaulting functions for things like `KubeProxyConfiguration.ConntrackMax` were not being invoked, which allowed the zero value to mean "don't change anything". This is just a guess as I haven't done a thorough audit of the code prior to my change going in for 1.7.

I can say with certainty that when the config file is loaded, we do execute the defaulting functions, and the current ones for conntrack-related fields do this:

https://github.com/kubernetes/kubernetes/blob/2c2fe6e8278a5db2d15a013987b53968c743f2a1/pkg/apis/componentconfig/v1alpha1/defaults.go#L84-L123

This does mean that if we have a defaulting function for a field/subfield under KubeProxyConfiguration, it is being applied with whatever logic it contains.

**Comment by tpetr** [comment]
@ncdc Thanks for the insight -- it seems like the best course of action is to update the docs to say "less than zero" instead of "equal to zero" (see: https://github.com/kubernetes/kubernetes/blob/v1.7.3/cmd/kube-proxy/app/server.go#L151-L162). Are we publishing documentation for KubeProxyConfiguration? I'm happy to open a PR.

**Comment by ncdc** [comment]
@tpetr I have some code I'm working on to get the docs for the config file included as part of `kube-proxy --help`. It's not finished yet, but it takes all of the comments from the fields in the structs and displays them in the help. So as long as we get those comments adjusted, they eventually will be in documentation.

**Comment by ncdc** [comment]
We also could consider if we want the defaults at all. Someone would need to go back to the 1.5/1.6 code and see what happens when you specify 0 vs not specifying anything. Do defaults get applied in either case? I'm not a kube-proxy expert (I just happened to do the conversion from flags to the config file), so someone from @kubernetes/sig-network-misc would need to weigh in here for this option.

**Comment by ncdc** [comment]
@thockin do we need to remove the defaulting for conntrack settings?

**Comment by pmichali** [comment]
Some comments that I had from 53329, which is a duplicate of this...

From what I can tell, the default creation logic will set conntrack max per core to 32K, if both conntrack max and conntrack max per core are zero. I don't see where the incoming values come from (not the CLI), so they would be zero and default logic will set max per core, AFAICT.

Later during init processing, a config file is loaded (which has no conntrack settings), and the defaults are used.

One issue seems to be that any CLI arguments specified, are ignored, when loading the config file and then calling NewProxyServer(), preventing any override from that source.

A second issue seems to be that there is no way to tell when a user is specifying zero values from the CLI and when no setting is being specified. So, even if CLI values were to override, there's no way to tell if these zero values should be used (the attempt by kubeadm-dind-cluster repo is to set conntrack max and conntrack max per core to zero, so no changes occur).

Third, the command line help implies that zero can be used, to leave settings alone, but I don't see how that can happen, given there is no differentiation between unset and zero setting, AFAICT.

Ideally, fixing #25543 would allow settings to be properly applied (systems with large conntrack max, would get their hashsize increased), and then the only issue would be handling the claim that one can set values to zero to leave them alone (maybe just remove that clause) and the acceptance of CLI values.

As it stands now though, because of #25543 we cannot change hashsize, and because CLI args are ignored we cannot override conntrack max (I tried setting to 256K, and kubeadm-dind-cluster tries to set to zero via command line) to prevent the need to change hashsize.

**Comment by ncdc** [comment]
We have deprecated the command line flags for kube-proxy and they will be removed in a future version. For the time being, they are still supported. However, if you specify both `--config` and some other flag(s), the other flags are ignored and the values from the config file are what is used. If you have converted to using the config file and need to change a setting, you will need to modify the config file. If you want to use the flags, don't specify `--config`.

None of this really addresses the conntrack defaulting issue, though. Re-ping to @thockin and @kubernetes/sig-network-bugs @kubernetes/sig-network-misc - do we need to remove the defaulting for conntrack settings?

**Comment by pmichali** [comment]
The script that I'm using (part of kubeadm-dind-cluster repo for Docker In Docker running of Kubernetes on a single machine), is using (only) command line args. The issue is that they are being ignored. The code reads from a file, of which there are no conntrack settings, and then uses the defaults.

The logic for forming the defaults, checks to see if conntrack max is zero, and if so, it checks conntrack max per core. If that is also zero, it sets it to a default value. This is inconsistent with what is done via the command line, where setting  both of those to zero, does not set any default and leaves them at zero.

**Comment by ncdc** [comment]
Ok, I have figured out the history on this and know how to fix. In the config structs, if a field with a value of zero actually means zero, and not unset, then that field must be a pointer. We need to adjust the proxy config fields and defaulting functions accordingly.

**Comment by danehans** [comment]
@ncdc thanks for finding the source of this issue. sig-network is hard at work adding ipv6 alpha support for 1.9. We are seeing this issue effect our ipv6 test deploys. Do you have time to implement the fix or does someone from sig-network need to take it on?

**Comment by ncdc** [comment]
I was planning on waiting for #53645 to merge before fixing it.

**Comment by danehans** [comment]
Makes sense. We are tracking that one as well for ipv6 alpha.

**Comment by ncdc** [comment]
I'm working on a fix for this now

**Comment by ncdc** [comment]
PR: https://github.com/kubernetes/kubernetes/pull/55261
