### ISSUE TITLE
Enable `kubefed init` support `tolerations`

### ISSUE THREAD

**Issue by gyliu513** [kubernetes/kubernetes#50815]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug

/kind feature

**What happened**:
The `kubefed init` can not specify `tolerations`, this will cause that I cannot deploy my federation panel on node which has `taint`, it is better to enable the `kubefed init` can specify the `tolerations` so that I can deploy federation panel on node which have `taint` that the federation panel can tolerate.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/sig federation

/cc @kubernetes/sig-federation-feature-requests

**Comment by tengqm** [comment]
To be honest, I don't like the way things are coded today.
Too many things hard coded into the process.
The opposite side of the problem is that it is too restrictive.
It is true we can add this "tolerations" today, then tomorrow, people will ask for "min-ready-seconds",
"replicas", "rolling-update-strategy", "termination-grace-seconds", ...
There won't be an end of this, given that both Deployment and Pod are evolving.

So the question I am really asking is: whether and how do we hide these "implementation" details from the users?

**Comment by gyliu513** [comment]
It seems difficult go get rid of such things just like `nova boot` in `OpenStack`, what I'm thinking now is can we enable `kubefed init` accept a file as I requested at https://github.com/kubernetes/kubernetes/issues/50817 , and we can put those parameters in a file, and end user can just update this file as they want and then `kubefed init -f <file>` which maybe more user friendly. @tengqm

**Comment by dixudx** [comment]
> enable `kubefed init` accept a file

SGTM. This is exactly the `kubectl` way, just like `kubectl create -f <file>`.

@tengqm 
> There won't be an end of this, given that both Deployment and Pod are evolving.

You're right. Definitely. But we should provide more ways to accept params. Actually even for `kubectl run`, we still have so many params. This does not have conflicts with `kubectl create -f`. For simple deployments, I think there is no need to prepare a yaml/json file. A single CLI will make it simple to use. @gyliu513 But we still need to make some restrictions on such params, otherwise we will be far away from the track just as @tengqm said.

I also suggest we can create another cmd `kubefed create -f` to not mix up with `kubefed init`, just like `kubectl run` and `kubectl create`. We don't want to make `kubefed init` as the only way.

**Comment by irfanurrehman** [comment]
This issue was labelled only for sig/multicluster and is thus moved over to kubernetes/federation#33.
If this does not seem to be right, please reopen this and notify us @kubernetes/sig-multicluster-misc.
/close
