### ISSUE TITLE
AWS CreateVolume should include tags

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#50898]
EC2 CreateVolume (to create an EBS volume) supports tags at creation time (not sure if new or not).  We should use that:

* for idempotency: create then tag can leak
* for IAM policies, which could then filter CreateVolume

**Comment by justinsb** [comment]
Tracked down why we didn't do this previously - the functionality was only introduced in March 2017: https://github.com/aws/aws-sdk-go/blob/44376742d0a0cb0a97c3e472b00fad8d350af166/CHANGELOG.md#release-v184-2017-03-28

cc @KashifSaadat BTW.

**Comment by lpabon** [comment]
could we also add annotations to the PVC which can be added as tags to the EBS volume, something akin to #45932 ?

**Comment by discordianfish** [comment]
This is required for limiting IAM permissions. Right now I have to give the controller unrestricted DeleteVolume/CreateaTags access, allowing it to delete all volumes in the same VPC. With a tag, I could grant it only permissions to delete volumes it created.

**Comment by gtaylor** [comment]
Can we get this one protected from fejta? This would be a great thing to have.

**Comment by discordianfish** [comment]
/remove-lifecycle stale
/lifecycle freeze

I think this should do it.

**Comment by gtaylor** [comment]
Thanks, @discordianfish !

**Comment by emmanuel** [comment]
I would also like to be able to tag EBS volumes by way of annotations on the PVC, as @lpabon mentioned. There is a closed PR (https://github.com/kubernetes/kubernetes/pull/49390) where the discussion seems to have explored generalizing the feature and then lost momentum. 

I would like to see that PR land and establish parity between ELB and EBS w/r/t user-supplied tags.

**Comment by GregHila** [comment]
Tagging EBS volumes on a PVC would be a much needed feature for us too. I would like to see the above mentioned  PR (#49390) be actually re-opened and approved

**Comment by alexvanbelle** [comment]
Same here. Would be appreciated to get consolidated billing on AWS.

**Comment by ricktbaker** [comment]
I'd find this useful as well.   We are doing automated backups of our EBS volumes we are using in kubernetes, but some are not needed, so would be nice to be able to add tags so our automation can pick up which ones to backup and which to ignore.

**Comment by discordianfish** [comment]
Just realize this wasn't mentioned here. I was initially interested in this primarly because it should allow creating IAM roles that are allowed to create volumes but are only allowed to attach/modify volumes only volumes that k8s created. That's impossible right now because k8s needs to be able to modify *all* volumes to attach the tags in a separate step.

**Comment by mgoodness** [comment]
We (Ticketmaster) have a controller that watches PVCs and reconciles EBS tags from a `volume.beta.kubernetes.io/aws-ebs-additional-resource-tags` annotation. We'd love to get it into the AWS cloud-provider if there's interest.

**Comment by leakingtapan** [comment]
@justinsb https://github.com/kubernetes/kubernetes/pull/67812 address this. Should we close this issue?

**Comment by emmanuel** [comment]
Based on my (admittedly brief) reading of the changes in #67812, I believe they address different issues. 

This is about allowing the user to specify arbitrary tags in a PVC, whereas #67812 is about atomicity of the volume creation and tagging (performing both in a single operation, as opposed to the previous two operations).

If I'm correct, then I believe this issue still remains.

**Comment by falken** [comment]
My corporate security group requires that all policies be scoped to either a specific AWS arn, or scoped to require a specific tag which is defined by them. If I can't specify that tag then I can't use AWS EBS volumes at all.

**Comment by leakingtapan** [comment]
@falken @emmanuel do you really need to specify tag through PVC annotation? will a storageclass parameter suffice? Looking forward in long run, the existing in-tree EBS plugin will be deprecated in favor of [EBS CSI driver](https://github.com/kubernetes-sigs/aws-ebs-csi-driver). And all the new features are supposed to be added there. The good news is there is an [existing PR](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/180) there to tackle this problem. And it is using storageclass. Feel free to comment there with your opinions.

**Comment by ryan-dyer-sp** [comment]
@leakingtapan Being able to specify at the PVC level would be highly valuable (though at this point I'll take additional tagging of EBS volume at any level I can get).  My previous employer required billing tags which were extremely granular as various applications running within the cluster were from different depts and needed to be billed to those depts accordingly.  Technically, you could work around this by creating different storage classes with just having the tags section of the definition be different.  But having the ease and flexibility of adding this at the PVC level would be great.

**Comment by msau42** [comment]
Can folks here provide some more details on their use cases?  For example, what kind of information to you want to associate with a tag and an example of tag values?  Instead of blindly allowing any arbitrary PVC annotations to be passed (which [breaks portability](https://github.com/kubernetes-csi/external-provisioner/issues/170#issuecomment-465833825)), we can investigate other means to be able to pass this information through to the driver.

**Comment by swestcott** [comment]
@msau42 Sure, we operate soft multi-tenant clusters and have the following use cases.

Firstly, the [Security pillar](https://d1.awsstatic.com/whitepapers/architecture/AWS-Security-Pillar.pdf) of the [AWS Well Architected Framework](https://aws.amazon.com/architecture/well-architected/) has a section on data protection. This recommends that AWS resources should be tagged with a data classification rating according to the type of data it handles/stores.

To achieve this we'd like to be able to describe the data classification of resources in Kubernetes yaml and have this passed through to the underlying AWS resource (EBS, ELB, etc).

We currently have 6 StorageClasses - gp2, io1 medium IOPs, io1 high IOPs with encrypted and non-encrypted variants of both. Adding *secret*, *restricted*, *confidential* and *public* data classifications would take that to 24 combinations. Doable, but a arguably painful to manage and scale further.

Example,
```
tags {
  data_classification: secret
}
```

Secondly, we'd like to use AWS tags for cost attribution to service owners. Again, this should be applied in Kubernetes yaml and be passed through to AWS.

Example,
```
tags {
  cmdb_service: foobar
}
```

HTH

**Comment by falken** [comment]
@leakingtapan I could probably get by with using a storage class annotation. I think the PVC annotation idea comes from trying to be consistent with the ELB annotations. But I could make it work.

@msau42 My use case:

My clients corporate cloud management group requires that all items be tagged with two tags I.E. "component" and "Name". These tags are then mapped inside their system to specific projects/teams/groups for security auditing and charge backs. If these tags are not present the instance they are attached to will be automatically "quarantined" within the network. 

In addition the clients corporate security requires that all IAM policies be scoped to specific resources by name, or via a specific tag I.E. "component". The system that approves changes to the policies only allow scoping by tag to that specific tag, otherwise I would scope to one of the annotations that are already created when creating the volume.

**Comment by xdrus** [comment]
Our use case is combination of swestcott and falken, DLP/Security team requires us to have data classification tag on every storage resource + we operate multitenancy clusters where we need tag's for accounting and billing purpose.

**Comment by saad-ali** [comment]
> To achieve this we'd like to be able to describe the data classification of resources in Kubernetes yaml and have this passed through to the underlying AWS resource (EBS, ELB, etc).

PVCs are not the correct place to specify implementation specific parameters. The Kubernetes PVC object is intended for application portability. When we start leaking cluster/storage implementation specific details in to it, we are violating that principle. And considering that workload portability is a cornerstone of Kubernetes, we should have very strong justification to violate it.

So, we have to be very cognizant of not opening up "holes in the API". Let's focus on individual use cases, and see if we can come up with focused solutions for each of those uses cases.

> We currently have 6 StorageClasses - gp2, io1 medium IOPs, io1 high IOPs with encrypted and non-encrypted variants of them. Adding secret, restricted, confidential and public data classifications would take that to 24 combinations. Doable, but a arguably painful to manage and scale further.

We can consider if "encryption" makes sense as a first class field in the Kubernetes PVC object. But we would need to find use cases to justify that the field is valuable to Kubernetes components, and not just a pass through to the storage system (which is what the StorageClass parameters are for).

Another option is to use Kubernetes secrets. Kubernetes secrets allow you to store an arbitrary set of keys/values. Presumably you could map "no secret" to "public", and make "secret/restricted/confidential" a field in the secret. CSI Provisioner templating for provisioners is not very flexible right now, so you'll probably want to wait until 
 https://github.com/kubernetes-csi/external-provisioner/issues/233 is resolved so that in your StorageClass you can have each provision operation use a different secret (either per PVC namespace or name).

The explosion of StorageClass options, while not a great solution, is the one I would recommend for now.

> @leakingtapan I could probably get by with using a storage class annotation. I think the PVC annotation idea comes from trying to be consistent with the ELB annotations. But I could make it work.

Great. 

> Secondly, we'd like to use AWS tags for cost attribution to service owners. Again, this should be applied in Kubernetes yaml and be passed through to AWS.

> Our use case is combination of swestcott and falken, DLP/Security team requires us to have data classification tag on every storage resource + we operate multitenancy clusters where we need tag's for accounting and billing purpose.

I would recommend writing a small controller that looks at provisioned volumes and applies the correct tags to them -- this will allow you to customize this logic as much as you want and allows your ground state to change over time and still be reflected correctly in your tags (since its continuously reconciled rather then applied once at provision time).

CC @msau42 @liggitt

**Comment by jonstacks** [comment]
We would also really love to see something like this get added into Kuberentes. It looks like #49390 got closed before it made its way in. If it helps in the discussion, we released a project, [lambda-ebs-backup](https://github.com/c2fo/lambda-ebs-backup) that runs in lambda on a schedule and takes automated EBS snapshots of volumes with certain tags. It also supports keeping a certain number of snapshots. We would love to try moving more of our stateful workloads to Kubernetes and this feature would help us feel more confident that the data is safe from someone accidentally deleting a pvc. More specifically, we would be planning on using helm to add these additional annotations for backups to only our prod environment and not our dev/test/CI environments.

**Comment by tibers** [comment]
We're in the same boat at my company. They want to use [Cloud Custodian](https://github.com/cloud-custodian/cloud-custodian) to make sure ownership is declared properly to track resource use and so we need to tag EBS volumes somehow.

**Comment by RMcD** [comment]
@jonstacks Not to mention that AWS Backup supports automatic snapshots of EBS based on tags.

https://aws.amazon.com/about-aws/whats-new/2019/01/amazon-ebs-integrates-with-aws-backup-to-protect-your-volumes/
https://docs.aws.amazon.com/aws-backup/latest/devguide/whatisbackup.html#tag-based-backup-policies

**Comment by RMcD** [comment]
@kubernetes/sig-cloud-provider-aws

**Comment by msau42** [comment]
Discussed this a bit with @saad-ali some more.  The main recommendations we have to address this are:

* Specify tags through StorageClass.Parameters. This is currently where all provider-specific configuration for provisioning exists. This requires the underlying storage provider to expose the option.
* A new feature to pass specific Kubernetes metadata to the storage driver, namely PVC name and namespace.  This lets users match their underlying resources to the Kubernetes objects.

Another idea is to have a cloud-provider controller that understands Kubernetes objects and tag all cloud resources (not just disks) per namespace or label selector (via some CRD).  This could be a nice solution that can consistently tag all cloud resources in a cluster instead of having one specific way for disks, and another way for load balancers, etc.

**Comment by seb-steuer** [comment]
2 years have passed and we still don't have custom EBS tags via PVC annotation 😞

**Comment by leakingtapan** [comment]
Since volume plugin will be migrated to CSI, please comment here for the same feature for EBS CSI driver:
* add static tags: https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/333
* add dynamic tags: https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/180

**Comment by gibsonje** [comment]
This issue has been closed for about 1 year now but I don't know of a solution to this problem. This issue is linked to in various places that discuss this problem but I haven't found a simple solution yet. 

I'm trying to get PVC EBS Volumes backed up using [AWS Backup](https://aws.amazon.com/backup/). It's virtually impossible to do this with just the features available in AWS and Kubernetes as far as I can tell.

For those who aren't familiar, you can either explicitly list resources to backup, or it can be tag driven. 

On the AWS side there's several limitations. 

- Backup plan selections **only** support a single STRINGEQUALS on tags. 
- There's no way to match on two tags.

On the Kubernetes side there's nothing to make this easier:
- PVC Volumes get tagged with `kubernetes.io/cluster/<cluster>`: `owned`
- PVC Volumes get tagged with `kubernetes.io/created-for/pvc/name`
- No ability to add custom tags to PVC definitions.

There's enough identifying information to clearly identify volumes belonging to a given cluster, for a given PVC.

But since I cannot match on two tags, I have no options here. 

What I really want to do is add a static tag to PVCs I want to have backed up. The tag would be:
`Backup`:`<cluster>-pvc`

But everything I'm reading in this thread and others is that there's no way to set tags on PVC resulting EBS volumes. 

This pull request:
https://github.com/kubernetes/kubernetes/pull/49390

Does exactly what I would want. There's debate in that thread about whether it _should_ be done, but from my perspective the ability to tag PVC via annotations is exactly the kind of solution that would make this easy for me. If I weren't doing this for backups, I'd likely also want this for billing.

So where that leaves me I don't think there's an out of the box solution that will let me tag my volumes for AWS Backups.  

I'd like to avoid solutions like this:
https://github.com/almariah/k8s-metadata-injector
https://github.com/sstarcher/kube-ebs-tagger

I don't see a way around implementing a custom solution.
