### ISSUE TITLE
env too big causes failure of creating deployment

### ISSUE THREAD

**Issue by chris612ku** [kubernetes/kubernetes#50930]
/sig scalability
Hi,

I encounter an issue and totally have no idea how to resolve it even though I've discussed with some other users on slack.
I'm wondering if Kubernetes developer/contributor could help me with this.

The situation is as followed:
I created about 60~70 deployments in my k8s system; however, after that, when I tried to create a new deployment, the creation failed.
Then I open /var/log/messages, and found that the error is complaining a docker error "Config file too huge".
So I stepped further to runlike the docker container (k8s pod), and I found that env has been cumulated too many... I'm wondering if these so many env would cause my problem of failing to create deployment?

Also, I'm wondering, for Client-Go library, when we try to delete service by Client-Go API, how do we delete the service env from the server? Do I have to do anything for v1.DeleteOptions parameter? For now, I'm just passing a nil for v1.DeleteOptions...

Thanks in advance for your help.

Best,
Chris

**Comment by cblecker** [comment]
Please re-post your question to [Stack Overflow](http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases.

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans Stack Overflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search Stack Overflow for answers to similar questions, and also familiarize yourself with:

  * [user documentation](http://kubernetes.io/docs/)
  * [troubleshooting guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/)

Again, thanks for using Kubernetes.

The Kubernetes Team

---
/kind support
/close
