### ISSUE TITLE
OpenAPI spec Quantity field should accept integer

### ISSUE THREAD

**Issue by garethr** [kubernetes/kubernetes#50957]
/kind bug

**What happened**:

Validating Quantity fields against the OpenAPI spec fails if the value is an integer, however Kubernetes happily accepts integers. 

**What you expected to happen**:

Validating Quantity fields should pass for integer or string values.

As noted on https://groups.google.com/forum/#!topic/kubernetes-sig-api-machinery/dLCXrZRwWpU

> This is not really a bug. It's a convenience feature specific to Quantity. Most of our users write yaml, 
> and it would be tedious to quote numbers, but strings like "100m" are also supported.

**How to reproduce it (as minimally and precisely as possible)**:

This issue arose with Kubeval as https://github.com/garethr/kubeval/issues/22. The issue shows how it was discovered.

**Anything else we need to know?**:

Worth noting the full type from the OpenAPI spec: 

``
io.k8s.apimachinery.pkg.api.resource.Quantity: {
  type: "string"
},
```

I think the fix would be for this to be rendered as:

``
io.k8s.apimachinery.pkg.api.resource.Quantity: { "oneOf": [
  { "type": "integer" }, 
  { "type": "string" }
]},
```

/area swagger
cc @kubernetes/sig-api-machinery-bugs

**Comment by mbohlool** [comment]
I am not sure about the content of the API so I suggest you find the team(s) responsible for those APIs and ask them about it. My hunch is Quantity here is not int-or-string or it would have been represented as IntOrString.

Also, what you suggested is will be possible in OpenAPI v3 (not yet). I am going to remove sig-api-machinery as this is the content of the API and not related to API machinery (each types can customize their OpenAPI spec). The fix is related to OpenAPI v3 support though that I will create an issue for.

**Comment by mbohlool** [comment]
I did a manual fix for IntOrString to make it `object` in client generators, does it make sense to do the same here?

```
io.k8s.apimachinery.pkg.api.resource.Quantity: {
    "type": "object" 
}
```

**Comment by lavalamp** [comment]
Quantity objects should always be represented by strings. It is correct to
reject ints IMO and I am surprised to hear that the ordinary API allows
them. I disagree w/ the email referenced by the OP.

Quantities are numbers with special properties and the point of dealing
with them this way is to make sure that users understand the properties and
enforce them in their own code.

Specifically, unquoted numbers in json are floating-point, which we're
taking great pains to avoid.
