### ISSUE TITLE
query dns for http port

### ISSUE THREAD

**Issue by nkravi** [kubernetes/kubernetes#51151]
area/dns 
sig/network

I have kubedns running.
I am able to get cluster IP 
```
nslookup my-ngnix-service.default
```
But I when i do the query for port I am not getting any output

```
nslookup _http._tcp.my-ngnix-service.default
```

kind: Service
apiVersion: v1
metadata:
  name: my-ngnix-service
spec:
  selector:
    app: nginx
  ports:
    - name: http
      protocol: TCP
      port: 9888
      targetPort: 9376

**Comment by nkravi** [comment]
area/dns sig/network

**Comment by FengyunPan** [comment]
sig/network

**Comment by anfernee** [comment]
@nkravi I cannot reproduce it. Did you add `-q=SRV`? 

This is the nslookup output for me.
```bash
# nslookup -q=SRV _http._tcp.my-ngnix-service.default
Server:		10.0.0.10
Address:	10.0.0.10#53

_http._tcp.my-ngnix-service.default.svc.cluster.local	service = 10 100 9888 my-ngnix-service.default.svc.cluster.local.
```

k8s versions:
```bash
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.4", GitCommit:"793658f2d7ca7f064d2bdf606519f9fe1229c381", GitTreeState:"clean", BuildDate:"2017-08-17T08:48:23Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.0", GitCommit:"d3ada0119e776222f11ec7945e6d860061339aad", GitTreeState:"clean", BuildDate:"2017-07-26T00:12:31Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

```

**Comment by c-knowles** [comment]
Are SRV queries for the port expected to work for externalName Services? Not sure if this is the right place to ask, I queried on [stackoverflow](https://stackoverflow.com/questions/43543014/kubernetes-service-externalname-with-port-dns-srv) previously. The reason I'd like that is so the port definition is centralised with the host rather than spread across multiple apps. i.e. make the port more discoverable.
