### ISSUE TITLE
ResourceQuota should support limiting the number of terminated pods

### ISSUE THREAD

**Issue by hanikesn** [kubernetes/kubernetes#51150]
When using cronjobs and jobs it's very easy to create a very large number of pods. E.g. in one of our clusters with etcdv3 a single cronjob created over 10k pods in about two days. With etcdv2 the apiserver would already have been unusable and in this case the large number of pods has caused IOPs starvation on our etcd nodes and the same on prometheus volumes.

ResourceQuotas right now only support limiting the number of non-terminal pods, which means they don't help preventing this failure mode:
>The total number of pods in a non-terminal state that can exist in the namespace. A pod is in a terminal state if status.phase in (Failed, Succeeded) is true.

Also allowing the an upper limit on the total number of pods would solve this kind of resource starvation.

/kind enhancement
@kubernetes/sig-cluster-ops-feature-requests

**Comment by hanikesn** [comment]
This just caused another outage of our production cluster. Not being able to limit the number of non-running pods is the number one reason our clusters became unavailable.

**Comment by hanikesn** [comment]
cc @deads2k @derekwaynecarr

**Comment by derekwaynecarr** [comment]
since 1.9, we support generic object count quota for all namespaced resources.

for pods in particular, its right that `pods` maps to non-terminal pods, but you can also use `count/pods` and it maps to all pods (terminal and non-terminal).
there are two syntaxes.

"pods" - controls number of non-terminal pods.
"count/pods" - controls number of pods (terminal or not)

see https://github.com/kubernetes/kubernetes/pull/54320
