### ISSUE TITLE
problems with kubelet 1.6-1.7 working with RHEL/Selinux

### ISSUE THREAD

**Issue by sokoow** [kubernetes/kubernetes#51187]
/kind bug
**What happened**:

Same as in https://github.com/rancher/rancher/issues/8491 , I'm experiencing the following when starting kubelet:

```
I0823 10:18:54.292916    5842 kubelet.go:1820] skipping pod synchronization - [Failed to start ContainerManager mkdir /sys/fs/cgroup/cpuacct,cpu: read-only file system container runtime is down PLEG is not healthy: pleg was last seen active 2562047h47m16.854775807s ago; threshold is 3m0s]
I0823 10:18:59.293100    5842 kubelet.go:1820] skipping pod synchronization - [Failed to start ContainerManager mkdir /sys/fs/cgroup/cpuacct,cpu: read-only file system]
I0823 10:19:04.293902    5842 kubelet.go:1820] skipping pod synchronization - [Failed to start ContainerManager mkdir /sys/fs/cgroup/cpuacct,cpu: read-only file system]
```

**What you expected to happen**:
Start kubelet normally

**How to reproduce it (as minimally and precisely as possible)**:
RHEL/Centos with SELinux on it

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.7.3
- Cloud provider or hardware configuration**: aws
- OS (e.g. from /etc/os-release): centos 7.3
- Kernel (e.g. `uname -a`): 3.10.0-514.26.2.el7.x86_64 #1 SMP Tue Jul 4 15:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: docker Version:      17.05.0-ce

**Comment by derekwaynecarr** [comment]
@sjenning -- any idea here?  is this a containerized kubelet?

**Comment by sjenning** [comment]
The name of the controller is `cpu,cpuacct` in RHEL/CentOS.  This is due to a kernel change that flipped the ordering in v3.14 (not the intent, but a side effect of the patch)

https://github.com/torvalds/linux/commit/3ed80a62b

I believe if you use `--cgroup-driver=systemd` however, this is abstracted away and should work.

Also docker 17.05.0-ce is not the version of docker in the repos for RHEL/CentOS so this must be an upstream release. YMMV as this is not tested by anyone.  Even the Kubernetes project itself does not test against that version of docker.  kube 1.8 is tested against up to docker 1.13.

https://github.com/kubernetes/kubernetes/blob/master/test/e2e_node/jenkins/image-config.yaml

**Comment by timchenxiaoyu** [comment]
you should add -v /sys/fs/cgroup:/sys/fs/cgroup:rw append to you run parameter

**Comment by israelshirk** [comment]
Running on kubernetes-incubator/kubespray with the centos AMI, adding @timchenxiaoyu's solution to /usr/local/bin/kubelet resolves the issue of the kubernetes API not starting.
