### ISSUE TITLE
TestApps always failed in package pkg/kubectl/apps

### ISSUE THREAD

**Issue by NickrenREN** [kubernetes/kubernetes#51253]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind flake

**What happened**:
TestApps always failed

**Anything else we need to know?**:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/49610/pull-kubernetes-unit/48887/
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/50889/pull-kubernetes-unit/48881/

/sig testing

**Comment by zjj2wry** [comment]
my pr appear same problem. i will investigate the cause later.

**Comment by tcharding** [comment]
`TestApps` fails when run by `k8s-ci-robot`. Stress testing `TestApps` runs >1000 times locally without any errors.

```
go test -c -race
stress ./apps.test -test.run=TestApp
[snip]
1012 runs so far, 0 failures
```

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/51332/pull-kubernetes-unit/50119/

**Comment by tcharding** [comment]
Hit this again here
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/51001/pull-kubernetes-unit/50133/

**Comment by liggitt** [comment]
this is odd... the test output actually shows TestApps succeeding in that run:

https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/51001/pull-kubernetes-unit/50133/artifacts/junit_f7172f2cb122b44f1a8919fff68dd59e6d916b66_20170828-235653.stdout
```
=== RUN   TestApps
Running Suite: Apps Suite
=========================
Random Seed: [1m1503965088[0m
Will run [1m8[0m of [1m8[0m specs

[32mâ€¢[0m[32mâ€¢[0m[32mâ€¢[0m[32mâ€¢[0m[32mâ€¢[0m[32mâ€¢[0m[32mâ€¢[0m[32mâ€¢[0m
[1m[32mRan 8 of 8 Specs in 0.002 seconds[0m
[1m[32mSUCCESS![0m -- [32m[1m8 Passed[0m | [91m[1m0 Failed[0m | [33m[1m0 Pending[0m | [36m[1m0 Skipped[0m --- PASS: TestApps (0.00s)
PASS
ok  	k8s.io/kubernetes/pkg/kubectl/apps	1.032s
```

**Comment by yujuhong** [comment]
Happened again: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/51986/pull-kubernetes-unit/52070/

```
=== RUN   TestApps
Running Suite: Apps Suite
=========================
Random Seed: [1m1504654611[0m
Will run [1m8[0m of [1m8[0m specs

[32mâ€¢[0m[32mâ€¢[0m[32mâ€¢[0m[32mâ€¢[0m[32mâ€¢[0m[32mâ€¢[0m[32mâ€¢[0m[32mâ€¢[0m
[1m[32mRan 8 of 8 Specs in 0.002 seconds[0m
[1m[32mSUCCESS![0m -- [32m[1m8 Passed[0m | [91m[1m0 Failed[0m | [33m[1m0 Pending[0m | [36m[1m0 Skipped[0m --- PASS: TestApps (0.00s)
PASS
```

The messages were interleaved . `PASS: TestApps (0.00s)` was appended at the end. I think that threw `go-junit-report` off.

**Comment by spiffxp** [comment]
By the looks of test grid, it's looks like it's been failing consistently in both presubmit and postsubmit builds:
- https://k8s-testgrid.appspot.com/kubernetes-presubmits#pull-kubernetes-unit&sort-by-failures=&include-filter-by-regex=TestApps&include-filter-by-regex=TestApps%24
- https://k8s-testgrid.appspot.com/release-master-blocking#test-go&include-filter-by-regex=TestApps%24&width=10

The logs are happy, the junit output is not.  Maybe it has something to do with the fact that ginkgo is used to run the test cases?  It's used for TestOpenapi tests as well.

There was an issue on those tests failing for what looks like the same reason https://github.com/kubernetes/kubernetes/issues/45279.  Looks like they were fixed by https://github.com/kubernetes/kubernetes/pull/45320

/kind bug
/priority failing-test

**Comment by pwittrock** [comment]
cc @seans3
