### ISSUE TITLE
Use Initializer only in specific namespace

### ISSUE THREAD

**Issue by fiunchinho** [kubernetes/kubernetes#51290]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:
There is no way to add [kubernetes initializers](https://kubernetes.io/docs/admin/extensible-admission-controllers/#initializers) to specific namespaces.

**What you expected to happen**:
When running a multi-tenant cluster, it'd be useful to apply some policies in just certain namespaces. It'd be interesting to do both:
- Apply initializer to ALL namespaces
- Apply initializer to this namespace in particular

**How to reproduce it (as minimally and precisely as possible)**:
Currently, Initializers are applied to all namespaces.

**Anything else we need to know?**:
No

**Environment**:
- Kubernetes version (use `kubectl version`): Any
- Cloud provider or hardware configuration**: Any
- OS (e.g. from /etc/os-release): Any
- Kernel (e.g. `uname -a`): Any
- Install tools: N/A
- Others: N/A

**Comment by ahmetb** [comment]
@caesarxuchao @smarterclayton I think this is a sane feature request.

Instead of building the namespace choosing logic inside the controller (and thus probably hardcoding it), maybe we can have a `namespaceSelector` in the InitializerConfiguration?

Has this been discussed before? I looked at the proposal at https://github.com/kubernetes/community/blob/master/contributors/design-proposals/admission_control_extension.md and https://github.com/kubernetes/community/blob/f929dac3046c3a75652b3731c4ab88ce1912e39b/contributors/design-proposals/dynamic-admission-control-configuration.md but I can't find a discussion about namespace selection for initializers.

**Comment by smarterclayton** [comment]
It was discussed in some out of band channels, but I'm not sure we'd implement it at the cluster scope (it's more likely we'd add NamespaceInitializers or something so that they are distinct objects).  It's a valid request, but would have to be considered for 1.9 (unlikely) or 1.10.

**Comment by lavalamp** [comment]
I would like to see a clear, concrete use case for this.

**Comment by catherinetcai** [comment]
@lavalamp - I'd prefer for initializers to not be applicable to the kube-system namespace, hence my desire for initializers that apply to specific namespaces. If apiserver were to crash and the sidecar that runs with the initializer doesn't come up for some reason, then pods in the kube-system namespace potentially get stuck for forever. That's not desirable behavior.

**Comment by liggitt** [comment]
Omitting a namespace (and possibly selector within that namespace) for purposes of unblocking an initializer running on the platform could make sense to me

**Comment by smarterclayton** [comment]
We should talk about the handoff between an admin (who knows which namespaces are critical) and an initializer author (who doesn't).

**Comment by ahmetb** [comment]
Unblocking an initializer can be done through `metadata.initializers.pending: []`. So I tend to think that wouldn't be the primary use case. Having a `namespaceSelector` would make it possible to configure the initializer on InitializerConfiguration, rather than command-line arguments that would depend on initializer controller's implementation.

Imagine a use case that restricts images per namespace:

```yaml
kind: InitializerConfiguration
initializers:
- name: "imagepolicy.mycompany.com/allow-test-images"
  namespaceSelector:
     purpose: test
  ...
- name: "imagepolicy.mycompany.com/allow-test-images"
  namespaceSelector:
     purpose: dev
  ...
- name: "imagepolicy.mycompany.com/allow-prod-images"
  namespaceSelector:
     purpose: prod
  ...
```

The controller basically looks at name of the pending initializer and takes the appropriate action. You can hardcode this logic into the initializer controller but it would be a lot less flexible. I'm not sure this is a solid enough use case, though.

**Comment by liggitt** [comment]
> Unblocking an initializer can be done through metadata.initializers.pending: []

the API server shouldn't generally allow setting the initializers field directly in a creation request for pods created by the controller manager from a replicaset, which is what you'd want to be keeping your initializer controller running

**Comment by fiunchinho** [comment]
Our use case is the following. We have a multi-tenant cluster, where different teams have different namespaces for different environments (dev, pre and production). We want different Quality of Service (QoS) on each environment/namespace. We'd like Pods running on `dev` kind of namespaces to be `Best Effort`, while Pods running on `pro` kind of namespaces to be `Guaranteed`. The current way of setting QoS for Pods is by configuring the limits and requests for the Pod. So Initializers would be a nice way of removing the limits and requests from the Deployment object that our teams use to deploy, only when deploying into a `dev` namespace.

**Comment by caesarxuchao** [comment]
> Omitting a namespace (and possibly selector within that namespace) for purposes of unblocking an initializer running on the platform could make sense to me

@liggitt could you elaborate on why we need to restrict to a "selector"? 
Can we reserve a namespace called "initialization-exempted", and ask the cluster-admin to deploy initializer controllers there?

**Comment by liggitt** [comment]
I prefer one mechanism to two. Selection can cover targeting a specific namespace.

**Comment by caesarxuchao** [comment]
Will it be tedious to go over each initializer configuration to exempt a certain namespace?

**Comment by liggitt** [comment]
I'd expect any exemption mechanism to be specifiable per initializer config, just like resource selection is

**Comment by rshriram** [comment]
We have several clusters at that are fully managed and tightly controlled due to the nature of the application (govt/healthcare). Installing a cluster wide feature is a no go. Allowing teams to define initializers for their specific namespace would be the cleaner solution in this scenario, as it allows smooth operability with teams using  other namespaces where initializers are not required.

**Comment by ahmetb** [comment]
Perhaps in addition to namespace selectors, what do you think of something like "kube-system pods cannot have initializers"? I reckon most people will deploy their initializers to here.

**Comment by liggitt** [comment]
> Perhaps in addition to namespace selectors, what do you think of something like "kube-system pods cannot have initializers"? I reckon most people will deploy their initializers to here.

We should not add magic name exceptions for general purpose mechanisms. I'd actually like to see the kube-system monolith broken up and addons, initializers, extension API servers run in their own namespaces

**Comment by smarterclayton** [comment]
Yeah, Kube-system is one giant security bomb waiting to go off.  We
should never have allowed as many system components to congregate
there, and will need to much more strictly control that in the future
as well as begin gradually moving them out.

**Comment by smarterclayton** [comment]
The only concrete use case for exemption I've seen so far is the deployment, statefulset, daemonset, replicaset, or replication controller that runs a particular intializer.  That is solvable in many ways, including possibly a ref or owner ref from initializer config to the actual object.

Tenant initializer configs (where an umprivileged user can register configs) sounds a lot like "api aggregation or CRD just for my tenant" and the two of those should be solved together.

**Comment by dixudx** [comment]
A summary for #53859, so we can close it and discuss here.

Got two ways to implement this,

1. Use `[]string` to list all the enforced namespace.
2. Use `NamespaceSelector `.

Option 1 is more obvious, but error-prone and time-consuming to list all the wanted namespaces exhaustively. Also it is not flexible, especially for new-added namespaces.

Option 2 works like other **label selectors** and **field selectors**. Also there is no need to add explicit label `namespace=xxx`, since `namespace` can be retrieved when admitting checks for `create` requests to add initializers. Already submitted a PR #53879. 

kubernetes/community#1191 is the design protocol.

@gyliu513 @ahmetb We could close #53859 now and discuss here.

**Comment by liggitt** [comment]
the alpha initializers feature has been removed in 1.14, and admission webhooks allow for targeting namespaces by label selector

/close
