### ISSUE TITLE
StatefulSet validation should include pvc validation

### ISSUE THREAD

**Issue by hzxuzhonghu** [kubernetes/kubernetes#51306]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> /kind bug

**What happened**:
the validation of statefulset is not complete, it not include the StatefulSetSpec.VolumeClaimTemplates validation, VolumeClaimTemplates  is an array of PersistentVolumeClaim, it should be checked.
**What you expected to happen**:
PersistentVolumeClaim in statefulset should be validated
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by kargakis** [comment]
cc @kow3ns

**Comment by jianglingxia** [comment]
Does this issue refer to a scenario where if you manually create a PVC and PV beforehand, and the PVC definition is different from some of the fields in the Volumeclaimtemplate, is this a hint of error?for example:
I manually create pv  pvc 
kubectl get pv
![image](https://user-images.githubusercontent.com/25783555/30358680-a3ce71c2-9878-11e7-9538-e292fc311358.png)
kubectl get pvc
![image](https://user-images.githubusercontent.com/25783555/30358690-b6c7404c-9878-11e7-9f01-e193bfd630e1.png)
but the statefulset define
volumeClaimTemplates:
  - metadata:
      name: nfs
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Mi
the capacity is Different,I use k8s1.6version，does not automatically create Extra pvc and not use the template
@hzxuzhonghu

**Comment by hzxuzhonghu** [comment]
@jianglingxia Not that scenario. Here just validate pvc as creating validation

**Comment by jianglingxia** [comment]
thanks for your reply,and I'd like to ask you a few questions：
1、事先手动创建好pv、pvc，其中pvc的名称符合statefulset的名称匹配规则，为什么volumeclaimtemplate不再创建了呢？是不是因为存在同名的pvc？这部分代码我找了很久不清楚在哪里？
2、场景二，如果事先定义的pv pvc中capacity与volumeclaimtemplate中定义的不同，为什么也不再自动创建额外的pvc呢？还是因为重名的原因吗？谢谢您的答复！ @hzxuzhonghu

**Comment by hzxuzhonghu** [comment]
I think u can find some clue in `pkg/controller/statefulset/stateful_pod_control.go`

By the way, better use English instead of  Chinese., Kubernetes contributors are from all over the world.

**Comment by hzxuzhonghu** [comment]
Actually, It only checks name here. As you say, storage capacity and some other important fields should also be checked here.

**Comment by jianglingxia** [comment]
but another problem occurred，user maybe want Different app has different capacity,but dynamic create pvc can not Achieve，for example，log Component maybe need more capacity。

**Comment by hzxuzhonghu** [comment]
If want use dynamic pvc, I think must assign PersistentVolumeClaim.Spec.Resources.Requests
you can assign storage request just as below.  But also I have never try this yet.
```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: task-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
```

**Comment by kow3ns** [comment]
@jianglingxia VolumeClaimsTemplates are not PVC's, and validation using the exiting PVC validation code would fail.

1. If you try to name your PVC in the VolumeClaimsTemplate the controller will overwrite the name. The PVC(s) for a StatefulSet Pod is named by the controller using a convention. The convention is important as it ensures that the CloudProvider provisions volumes correctly according to zonal spreading implemented in the provider itself
1. You can not set the namespace for the PVC, it must be in the same namespace as the StatefulSet.
1. This is not a bug, and if it is a feature request, we'd need to know more about the behavior that you desire. What use case are you trying to realize?

**Comment by jianglingxia** [comment]
thanks @kow3ns 
I want to know that the Following some Questions：
1、if use dynamic pvc ，can Force binding pv？for example，pv0 binding pvc0，pv1 binding pvc1；because dynamic can not ensure that，maybe pv0 binding pvc1.later the k8s can implement it？
2、why I Manually Create the pvc named ”www-nfs-0” and binding one pv before creating statefulset that the volumeclaimtemplate's name it www and statefulset name it nfs ,why not create extra pvc that the volumetemplate dynamic create?because the pvc named "www-nfs-0"has existing?
3、based the above 2，if Manually Create the pvc and pv，but the capacity different the volumeclaimtemplate define,for example manually created the pvc  request 4G,but volumeclaimtemplate   
defined 1G,why not create extra pvc that the capacity is 1G? also the same name of pvc?this is k8s's feature?not bug?
thanks for your reply @kow3ns

**Comment by kow3ns** [comment]
1. This [tutorial](https://kubernetes.io/docs/tasks/configure-pod-container/configure-persistent-volume-storage/) demonstrates how you can manually bind a PVC to a PV.
2. If you manually create a PVC that corresponds to naming convention and VolumeClaimsTemplate of the StatefulSet's Pod it will use that PVC/PV.
3. If I understand what you are trying to do, you should create a volume with 4GB and bind it to a PVC of 1GB. This should work as the volume satisfies the storage requirement of the claim.

In general, what are you trying to accomplish? That is, why not configure a dynamic provisioner for your storage and allow the StatefulSet to create the volumes for you? I'm afraid that the manual approach you are taking will not scale well (in terms of supportability).

**Comment by hzxuzhonghu** [comment]
@kow3ns I think @jianglingxia just wonder the third case may not work as expected, if you create a volume with 1GB, but create a statefulset with VolumeClaimsTemplate of pvc requiring 4GB storage.
Because , statefulset controller only check the name of pvc.

**Comment by kow3ns** [comment]
@hzxuzhonghu @jianglingxia True we don't check the storage constraints of manually provisioned PVCs when used with a StatefulSet. 
1. The intention of the design is to use the controller to create the PVCs for you. You  declare the storage you want inside of the VolumeClaimsTemplates and then provision PVs (not PVCs) either manually or via a dynamic provisioner. 
2. If you're manually creating PVCs to match the naming convention of the StatefulSet and mismatching the storage allocation, that is outside of the intended usage of the API and a user error.

**Comment by hzxuzhonghu** [comment]
thanks , i see.

**Comment by jianglingxia** [comment]
the second point that if I manually creating pvc  to match the naming convention of the StatefulSet ,and volumeclaimtemplate define storage is 1Gi，but manually creating pvc define the capacity is 4Gi，k8s will create it and work well,but the behavior is not correct？
and if I delete the volumeclaimtemplate's spec only left the metadata.name,the above case is ok?and the behavior is correct?
thanks for your reply @hzxuzhonghu @kow3ns 
another question:if use dynamic provisioner,can not sure pv0 binding pvc0,pv1 binding pvc1;maybe pv0 binding pvc1,because in k8s Website said that " Note that currently, a PVC with a non-empty selector can’t have a PV dynamically provisioned for it."
https://kubernetes.io/docs/concepts/storage/persistent-volumes/#class

and some one has the problem
https://stackoverflow.com/questions/44311915/template-persistentvolumeselector-labels-in-statefulsets-volumeclaimtemplate

**Comment by jianglingxia** [comment]
cc @hzxuzhonghu @kow3ns  can help me reply the question？thanks very much。

**Comment by kow3ns** [comment]
You may manually create the PVC and the StatefulSet controller will adopt it. However, you should let the controller create the PVC for you.

Once you create a StatefulSet you may not mutate the volumeClaimTemplates.

Once the PVC is bound to a PV, if you unbind or delete the PVC, you can not manually recover the storage association. If you use a dynamic provisioner it will create a PV to match your PVC and bind it. If you manually provision a PV, the pv controller will select an appropriate PV and bind it for you.

**Comment by jianglingxia** [comment]
Q:if I delete the volumeclaimtemplate's spec only left the metadata.name,the above case is ok?and the behavior is correct?
A:“Once you create a StatefulSet you may not mutate the volumeClaimTemplates.”
I mean that the yaml is like this:
`apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: sc
spec:
  serviceName: "cinder"
  replicas: 2
  template:
    metadata:
      labels:
        app: cinder
    spec:
      containers:
      - name: cinder
        image: index.tenxcloud.com/docker_library/nginx:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /mnt/scjlx
  volumeClaimTemplates:
  - metadata:
      name: www
`
only left metadata.name,and spec all not use,the case is ok?
why I not use dynamic pvc or pv because in our project need ensure pv0 binding pvc0,maybe dynamic created let pv0 binding pvc1;another Reason is that dynamic created pvc the capacity both the same size;but user maybe want deffierent app use deffierent size
so in our project use manually created pv and pvc,user can Custom the capacity  and ensure the binding relation,what about you?
later the k8s Community can resolve the problem?thanks for your reply! @kow3ns

**Comment by kow3ns** [comment]
I'm closing this for now as this is not a bug.

**Comment by hzxuzhonghu** [comment]
@kow3ns  Though you closed the issue, I think the pvc validation is necessary when create statefultset. Validation should cover all possible parts.
