### ISSUE TITLE
kube-dns does not work with IPv6

### ISSUE THREAD

**Issue by danehans** [kubernetes/kubernetes#51371]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

kube-dns fails readiness probe when k8s uses IPv6 addressing.

**What you expected to happen**:

kube-dns pod to pass readiness and health probes.

**How to reproduce it (as minimally and precisely as possible)**:
1. Setup IPv6 network
2. Download, install and configure CNI [0.6.0 bins](https://github.com/containernetworking/plugins/releases/tag/v0.6.0) using IPv6.
3. Deploy k8s using IPv6 addresses for master and node services.
4. Deploy kube-dns use stock [manifests](https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/dns)

**Anything else we need to know?**:
N/A

**Environment**:
N/A

**Comment by luxas** [comment]
Hi!

Thank you for filing this issue. We appreciate your interest in Kubernetes and kubeadm.
In order to make the kubernetes/kubernetes issue tracker more usable, we're routing issues to different repositories with different focuses.

I think this issue belongs in the kubeadm repository. Please move this issue to the [kubeadm repo tracker](https://github.com/kubernetes/kubeadm/issues) in order for the kubeadm team to be able to track this efficiently. If you disagree with my assessment of moving this issue, please speak up and/or reopen the issue.

Thank you and have a good day!
