### ISSUE TITLE
default limit sometimes acts as max limit

### ISSUE THREAD

**Issue by rohitagarwal003** [kubernetes/kubernetes#51430]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
I created a `LimitRange` with the following spec:
```
apiVersion: v1
kind: LimitRange
metadata:
  name: mem-limit-range
spec:
  limits:
  - default:
      memory: 512Mi
    defaultRequest:
      memory: 256Mi
    type: Container
```

Now,
- When I create a pod without specifying both requests and limits. It gets request=256Mi and limit=512Mi. Working as expected.
- When I create a pod with limit=x and unspecified request, it gets created with limit=x and request=x. Working as expected.
- When I create a pod with request=x and unspecified limit, it gets created with request=x and limit=512Mi. This is okay when x is less than 512Mi. **But when x is greater than 512Mi, I get an error**:
  ```
  The Pod "blah" is invalid: spec.containers[0].resources.limits: Invalid value: "512Mi": must be greater than or equal to memory request
  ```

**What you expected to happen**:
The default limit should not act as the max limit. It should have allowed me to create a pod with request greater than the default limit. I am not sure what limit value LimitRanger should set in this case, we can either set it equal to request or we can keep it unspecified.

However, if this is expected behavior, I should get a better error message that clearly says that if I am only specifying request, I need to specify it less than the default limit.

**Environment**:
- Kubernetes version (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.4", GitCommit:"793658f2d7ca7f064d2bdf606519f9fe1229c381", GitTreeState:"clean", BuildDate:"2017-08-17T17:03:51Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.0", GitCommit:"d3ada0119e776222f11ec7945e6d860061339aad", GitTreeState:"clean", BuildDate:"2017-07-26T00:12:31Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
```
minikube version: v0.21.0
```

/sig scheduling
/cc @vishh

**Comment by vishh** [comment]
This is WAI. Limit Range is used not only for smarter defaulting, but also for enforcing policies over namespaces. The policy in your example is that memory limits cannot exceed 512 Mi which means that requests cannot be greater than 512 Mi.

What are you trying to achieve with LimitRanges?

> However, if this is expected behavior, I should get a better error message that clearly says that if I am only specifying request, I need to specify it less than the default limit.

This I agree. May be Limit Range logic can reject pods due to invalid requests rather than letting API server validation fail the pod.
@derekwaynecarr WDYT?

**Comment by mindprince** [comment]
Note that I have only set the default limit and request, I have not set the max limit or request:
```
$ kubectl describe limitrange
Name:		mem-limit-range
Namespace:	default
Type		Resource	Min	Max	Default Request	Default Limit	Max Limit/Request Ratio
----		--------	---	---	---------------	-------------	-----------------------
Container	memory		-	-	256Mi		512Mi		-
```

And I am indeed able to create pods with limits greater than `512Mi`. For example, when I set the limit to `1Gi` the pods gets created. It's only when I have an unspecified limit and a specified request that is greater than the default limit that this behavior is taking place.

**Comment by vishh** [comment]
@mindprince got it. As I mentioned earlier LimitRange does both defaulting and policy enforcement.
Your configuration is about defaulting which is not enforcing any policies.

**Comment by dixudx** [comment]
@mindprince @vishh IIUC, our `LimitRange` has enabled the default value but failed to enforce the policies. If no one is working on this, I'd like to add some validations on the enforcement of `LimitRange`.

Actually from the source code,

```
// Default resource requirement limit value by resource name.
// +optional
Default ResourceList
```

`limits.Default` actually stands for limit value. 

> When I create a pod with limit=x and unspecified request, it gets created with limit=x and request=x. Working as expected.

This operation should be rejected for `x>512Mi`, since `limits.Default=512Mi` has been set. Right?

Also to avoid such misunderstandings, shall we rename `limits.Default` to `limits.DefaultLimit`.

If there is a consensus, I'll submit a PR on this.

**Comment by mindprince** [comment]
>> When I create a pod with limit=x and unspecified request, it gets created with limit=x and request=x. Working as expected.

> This operation should be rejected for x>512Mi, since limits.Default=512Mi has been set. Right?

No, it should not be rejected. In the example above, `LimitRange` was not supposed to do any enforcement. I only set the default fields (`Default` and `DefaultRequest`) in the `LimitRange`. Enforcement is supposed to be done only when you set the min/max fields (`Min` and `Max`).

```
        // Max usage constraints on this kind by resource name
        // +optional
        Max ResourceList
        // Min usage constraints on this kind by resource name
        // +optional
        Min ResourceList
```

**Comment by weiwei04** [comment]
enter into the same issue:

- When I create a pod with request=x and unspecified limit, it gets created with request=x and limit=512Mi. This is okay when x is less than 512Mi. But when x is greater than 512Mi, I get an error:
```
The Pod "blah" is invalid: spec.containers[0].resources.limits: Invalid value: "512Mi": must be greater than or equal to memory request
```

since I supplied a request=x (and x is in the limitrange max.request/max.limit), in k8s without limitrange, on the kubelet, it will set limit = request. for this case, shall we change the limitrange admissioncontroller Admit logic (https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/admission/limitranger/admission.go#L203) a bit? like

- request = x, limit is unset, if x is less than limitrange default limit, we set the limit = default limit.
- request = x, limit is unset, if x is great than limitrange default limit but less than limitrange max limit, we set the limit = request.

@vishh @mindprince ?

**Comment by derekwaynecarr** [comment]
defaulting is different than max.  agree with issue reporter, looking at pr.

**Comment by derekwaynecarr** [comment]
actually, i need to think on this more.

in this case, by asserting a default limit, the operator is implicitly requiring that a limit be set on pods.  so it does not act as the effective max, but it does force the pod author to make a decision.

**Comment by derekwaynecarr** [comment]
ok, reflected on this more.  sorry for spam.

we have min / max / default (which applies to limit) / defaultRequest

user omits limit, sets request, we should only apply the default limit if its > request.  the implication here is that users will be able to create pods that are not bounded if the operator did not set a max.  so if the operator wants to enforce bounds, just use max, but we should not apply bad defaults.

**Comment by weiwei04** [comment]
So the expected behavior here is:

if the default is set and max is unset, we set container.Resource.Limit = default iff resource.Request <= default, otherwise we left container.Resource.Limint unset, am I getting this right? 

@derekwaynecarr

**Comment by pacoxu** [comment]
/assign
If this is still needed, I will work on this.

**Comment by pacoxu** [comment]
/remove-lifecycle frozen
/priority important-longterm
as it will be fixed by #98295

**Comment by ehashman** [comment]
@pacoxu why was the PR that fixed this closed?

**Comment by pacoxu** [comment]
Sorry, I mistakenly deleted an old branch. 

I cannot reopen the PR as it shows that I have force-pushed a new branch. 
So I have to recreate a PR #103170 for it.

**Comment by SergeyKanzhelev** [comment]
/assign @pacoxu 

since you are working on PR.

/triage accepted

**Comment by pacoxu** [comment]
PR is still in review.

**Comment by SergeyKanzhelev** [comment]
This was documented here: https://kubernetes.io/docs/concepts/policy/limit-range/#limitrange-and-admission-checks-for-pods as an expected behavior.

> However, if this is expected behavior, I should get a better error message that clearly says that if I am only specifying request, I need to specify it less than the default limit.

This will help a little bit: https://github.com/kubernetes/kubernetes/pull/112925 by printing the actual value it was compared to.

**Comment by SergeyKanzhelev** [comment]
/close 

this is as designed
