### ISSUE TITLE
Bazel builds require certain tools pre-installed on host os.

### ISSUE THREAD

**Issue by kad** [kubernetes/kubernetes#51623]
**Is this a BUG REPORT or FEATURE REQUEST?**: FEATURE REQUEST

/kind feature

**What happened**: In normal installation of bazel and running `make bazel-build` user will most probably hit certain set of errors, like absence of g++ compiler or absence of glibc development headers or something else.

**What you expected to happen**: It will be good if bazel build rules will validate environment and warn users about missing components.

**How to reproduce it (as minimally and precisely as possible)**: CentOS 7 or OpenSuSE 42.x environment. Install JDK, bazel, make, gcc normally. Run `make bazel-build` and it will result in series of errors either for `missing dependency declaration for /usr/include/foo.h` (in case of g++ missing) or `/usr/bin/ld: error: cannot find -lc` ( in case of static devel files are missing)

**Anything else we need to know?**:
cc @ixdy 

**Environment**:
- Kubernetes version (use `kubectl version`): master branch
- Cloud provider or hardware configuration**: n/a
- OS (e.g. from /etc/os-release): CentOS 7, OpenSuSE 42.3
- Kernel (e.g. `uname -a`): n/a
- Install tools: 
- Others:

**Comment by BenTheElder** [comment]
Hmm, if you want to run in docker with all the tools supplied you can use [planter](https://github.com/kubernetes/test-infra/tree/master/planter), the only reasons building without bazel doesn't get similar errors with the cgo bits in particular are:
- we build inside docker images with the tools for make (quick-)?release
- we don't build things like Debians / RPMs (to my knowledge) except with bazel-build

We should probably encourage the usage of `make bazel-release` which is roughly equivalent to `make quick-release` (builds linux/amd64 tarballs)

I've also previously filed an upstream issue (since fixed) about warning when lacking RPM tooling specifically https://github.com/bazelbuild/bazel/issues/4065
