### ISSUE TITLE
HPA counts pods that are not ready and doesn't take action

### ISSUE THREAD

**Issue by kilianc** [kubernetes/kubernetes#51650]
> /kind bug

**What happened**:
HPA
```
NAME              REFERENCE                      TARGETS           MINPODS   MAXPODS   REPLICAS   AGE
service-entrata   Deployment/service-entrata     0% / 25%          2         100       2          1d
```

Deployment
```
NAME                        DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
service-entrata             2         2         2            0           4d
```

**What you expected to happen**:

HPA should take action and start 2 new pods

**How to reproduce it (as minimally and precisely as possible)**:

Create a deployment with a strict readiness probe `timeoutSeconds=1` `periodSeconds=2` and make CPU go up until the the pods become not ready.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): `1.7.3`
- Cloud provider or hardware configuration**: `GKE`
- OS (e.g. from /etc/os-release): `alpine-node`

**Comment by kilianc** [comment]
@kubernetes/sig-autoscaling-bugs

**Comment by DirectXMan12** [comment]
Can we get output of `kubectl describe` for that HPA, since that has more information, and read `kubectl get` output without column names isn't particularly easy?

I see 0% CPU usage on those pods, but by default, unready pods aren't considered unless a scale-up would occur, in which case, they count as 0%, in order to be conservative about scaling up when we already have unready pods waiting in the wings.

**Comment by kilianc** [comment]
@DirectXMan12 I updated the first post with the the table headers as requested, I had to delete the HPAs and deploy a custom controller to fix the issue so I can't give you additional output.

> when we already have unready pods waiting in the wings.

This is where I get confused, and this is probably me misreading the docs, but isn't it true that a pod can go from ready to not ready because of the `readinessProbe`? I thought that was the whole point, I configured my deployment to "un-ready" the pods if they are being hammered and CPU goes up and wait 30s before the liveness check kills them in the hope that the HPA would be fast enough to scale up.

If HPA ignores unready pods this becomes a problem.

As I said I wrote a custom HPA that does exactly what I described and I am getting the behavior that I want, but I will be happy to throw it away if this is a bug.

Thanks for your time!

**Comment by mattjmcnaughton** [comment]
Re the [liveness and readiness docs](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/) it looks like you're correct re pods going from ready to not ready because of the `readinessProbe`.

I'd be really interested to know more about your use case. Is the load on your application highly variable or fairly consistent? If the latter, I'm confused about the benefits of "unreadying" overloaded pods, as I would think the same number of requests shared across fewer pods would overload the other pods in the service, leading to a cycle of overloading and "unreadying". 

For my own curiousity, would you mind explaining more about how leaving the hammered pods ready while the HPA creates the new pods isn't working?

**Comment by aleksandra-malinowska** [comment]
cc @mwielgus

**Comment by kilianc** [comment]
@mattjmcnaughton you are correct yes we have traffic spikes. Unreadying the pods allows them to stop receiving new traffic and successfully recover without a full container restart.

The problem is, if the HPA doesn't take into account pods that are not new, but become not ready, I won't be able to scale accordingly to serve *new* traffic. Also the minimum amount of available pods is not enforced and the deployment is left with 0 with no action taken.

**Comment by kilianc** [comment]
> the same number of requests shared across fewer pods would overload the other pods in the service, leading to a cycle of overloading and "unreadying"

That's exactly where the HPA should take action.

**Comment by DirectXMan12** [comment]
> I thought that was the whole point, I configured my deployment to "un-ready" the pods if they are being hammered and CPU goes up and wait 30s before the liveness check kills them in the hope that the HPA would be fast enough to scale up.

Ah, you have a fundamentally different definition of "unready" than we assume in the HPA.  In order to deal with pod initialization CPU spikes we assume that unready pods will be back soon-ish, and that unready pods are probably unready because they're *not yet* ready.  This means that we don't keep scaling up while new pods are starting, and we don't accidentally overscale because a pod consumes a lot of resources while initializing.

However, it also means (somewhat inadvertently) that when pods go from ready to unready, the HPA is *much* more conservative about scaling up new pods.  I can definitely see how this behavior could be detrimental.  I'm imagining a system like this:

- a readiness probe checks that the maximum request processing time is less that some desired amount
- one pod goes unready, more traffic is shifted to the rest
- each existing pod goes unready in turn
- HPA doesn't add new pods, since it's being fairly conservative
- all pods become unready, and eventually ready again

Ideally, two factors mitigate this issue:

1. if the other pods are experiencing sufficiently high CPU usage, the HPA should kick in anyway -- it's more conservative about scale ups, but that doesn't mean it won't scale up at all.
2. the HPA should kick in *before* this happens.  This is easier to target once you have a good handle on CPU, or if you autoscale on the same metric that you use to determine readiness.  For instance, with HPA v2, you could set your readiness probe to check "free space" in the workqueue, and then autoscale based off of an expected queue length (e.g. go unready at a queue of 10, have HPA scale around a queue length of 5).

Howevever, based on this bug, those two mitigating factors might not be enough.  We may want to make some more explicit considerations somehow for pods going unready because they're "full".  @kubernetes/sig-autoscaling-feature-requests.

**Comment by DirectXMan12** [comment]
@kilianc does that scenario above describe what you were seeing?

**Comment by kilianc** [comment]
@DirectXMan12 I think you nailed it.

> Howevever, based on this bug, those two mitigating factors might not be enough.

This has been battle tested in production with thousands of users to the point that didn't matter which metric we were using or how low the target was, the number of timeouts and `500`s spikes until every single pod stops working waiting for new nodes to spawn.

What we're doing at the moment is, we distinguish between new and unready pods, and we always take into account pods that have been unready'd because they reached capacity (response time > 500ms)

I hope we can figure out a way to improve current behavior!

Thanks again for looking into this, we really appreciate it.

**Comment by DirectXMan12** [comment]
/remove-lifecycle stale

cc @mwielgus re the new changes

**Comment by grischa** [comment]
I wonder if any solution has appeared. Our application has this two endpoints for liveness and readiness testing. Here you can see the behaviour (port-forwarded pod to 8080):
```bash
$ curl -D - http://localhost:8080/status
HTTP/1.1 503 Service Unavailable
Connection: Close
Content-Length: 45

Process is currently unavailable - PROCESSING
$ curl -D - http://localhost:8080/healthz
HTTP/1.1 200 OK
Connection: Close
Content-Length: 2
Content-Type: text/text
```

Each pod basically handles one request (a minute long processing job). It turns out that when HPA ignores all unready, i.e. busy, pods, it won't scale up to make sure at least one ready pod is available for new requests.

According to the the readiness documentation ready means "ready to handle requests", and hence unready means "really busy", too, not just "on holiday", so please update HPA accordingly, at least give an option to not ignore unready pods.

**Comment by DirectXMan12** [comment]
we've landed some changes in the current release that should fix this.

**Comment by grischa** [comment]
@DirectXMan12 Thanks for the quick response! Do you know what version this is? It might take a while for AWS to update EKS...
@kilianc, could you share your custom HPA?

**Comment by DirectXMan12** [comment]
I'll be in 1.12

**Comment by kilianc** [comment]
@grischa I have to ask my prev company because it's unlicensed software. I can probably share pseudo code in private tho.

**Comment by kilianc** [comment]
@DirectXMan12 is a changelog available already? can you point out the commits/pr and test suite changes? This is amazing!

**Comment by DirectXMan12** [comment]
it was included as a side effect of https://github.com/kubernetes/kubernetes/pull/67252

**Comment by kilianc** [comment]
bump

**Comment by mgazza** [comment]
This is still an issue, I think I have managed to cut down the tests to demonstrate it. https://gist.github.com/mgazza/f01d03464ac480a2de1fa9f6edeee1f6#file-horizontal_test-go

**Comment by probenx** [comment]
Hey, 
I am facing this issue now, is there some recommended way around it?

**Comment by ErwanDL** [comment]
Is this issue really solved ? I have a very similar use case as OP : we have very sudden traffic spikes, and on top of that we make use of persistent connections (SSE and WebSockets) which cause imbalances in resource consumption between the different pods of a same deployment. As a consequence, we use readiness probes as a way to make pods temporarily unavailable, so that they stop receiving new requests for a little while and are able to cool down, otherwise they would just end up crashing because of overload.

When we have a massive traffic spike, all our pods end up being in the "unready" state before the HPA even realizes that they are over the CPU threshold. And then the HPA seems to ignore the unready pods, says that the overall cpu consumption of the deployment is `<unknown>/threshold`, and thus doesn't scale up although the deployment is completely overloaded.

**Comment by mfine** [comment]
We're running into the same issue with overloaded pods going from "ready" to "unready" - we are using the failed "readiness" probes to take the overloaded pods out of their service and to keep requests away from them. Having the ability to distinguish between autoscaling with pods that are getting "ready" on startup and pods that become "unready" during normal service would be very useful - while ignoring the former makes sense to avoid spiking scaling on startup, ignoring the latter impacts the ability to scale up during an overloaded situation. Our current poor workaround has been to stop having overloaded pods go "unready" and instead continue to take traffic. We are using custom metrics to drive our scaling so we're unclear whether `--horizontal-pod-autoscaler-cpu-initialization-period` would be applicable to our use case.

**Comment by mgazza** [comment]
Would it help people if I made the "ready-hpa" public?

**Comment by Tristan971** [comment]
> Would it help people if I made the "ready-hpa" public?

It'd be great yeah; ran into just that... Turns out 75% CPU target can mean the following is "all fine"...
- 2 ready pods at 100%
- 1 unready pod at 0%
