### ISSUE TITLE
Couldn't find Kubernetes java API to retrieve pod metrics.

### ISSUE THREAD

**Issue by Akhila27** [kubernetes/kubernetes#51772]
We are creating and spawning the kubernetes pods using java API (io.fabric8.kubernetes.* and few other) but we are stuck with the issue of finding the pod metrics .We got the suggestion of using heapster and grafana but we trying to find metrics through java of no use.
Can you please throw some light on this issue .

Thank you.

/sig kubernetes pod metrics through java api/kubernetes

**Comment by cblecker** [comment]
Please re-post your question to [Stack Overflow](http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases.

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans Stack Overflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search Stack Overflow for answers to similar questions, and also familiarize yourself with:

  * [user documentation](http://kubernetes.io/docs/)
  * [troubleshooting guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/)

Again, thanks for using Kubernetes.

The Kubernetes Team

---
/kind support
/close
