### ISSUE TITLE
Proposal: support unequivocal DENY in union authorizer

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/kubernetes#51862]
Problem: GKE wants to take advantage of componentconfig for kubelet, monitoring, kube-dns config deployment. We need a way to protect these resources from user error to maintain our SLA. In our current permission model, we allow users to grant themselves system:cluster-admin ("\*/\*/\*") and moving away from this model would be difficult. A solution would be to support unequivocal DENY form an authorizer. This could be implemented by either:

* turning .sar.status.allowed to a tristate (YES, DONT_CARE, NO)
* adding a .sar.status.break that defaults to false

In both cases, authorizers would need to be able to register with the union authorizer as 'critical' (i.e. authorizers that might return unequivocal DENYs).

Drawbacks:
* The current model of the union authorizer allows for failures of individual authorizers. Failures of "crictical" authorizer will need to fail closed. This means the GKE api (which serves the webhook authorizer) would need to be up for the kubernetes API to be functional.
* RPC to GKE API is required on every auth (although webhook authorizer does some caching). Right now if the Node,RBAC,ABAC authorizers can serve a SAR, no RPC is required.

@kubernetes/sig-auth-feature-requests @roberthbailey @erictune @mtaufen

**Comment by smarterclayton** [comment]
We've traditionally said no to deny rules because they complicate the model.

Are there any other alternative solutions considered?  Admission?


On Sep 2, 2017, at 4:12 PM, Mike Danese <notifications@github.com> wrote:

Problem: GKE wants to take advantage of componentconfig for kubelet,
monitoring, kube-dns config deployment. We need a way to protect these
resources from user error to maintain our SLA. In our current permission
model, we allow users to grant themselves system:cluster-admin ("*/*/*")
and moving away from this model would be difficult. A solution would be to
support unequivocal DENY form an authorizer. This could be implemented by
either:

   - turning .sar.status.allowed to a tristate (YES, DONT_CARE, NO)
   - adding a .sar.status.break that defaults to false

In both cases, authorizers would need to be able to register with the union
authorizer as 'critical' (i.e. authorizers that might return unequivocal
DENYs).

One major drawback: The current model of the union authorizer allows for
failures of individual authorizers. Failures of "crictical" authorizer will
need to fail closed. This means the GKE api would need to be up for the
kubernetes API to be functional.

@kubernetes/sig-auth-feature-requests
<https://github.com/orgs/kubernetes/teams/sig-auth-feature-requests>
@roberthbailey <https://github.com/roberthbailey> @erictune
<https://github.com/erictune> @mtaufen <https://github.com/mtaufen>

—
You are receiving this because you are on a team that was mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/51862>, or mute the thread

**Comment by erictune** [comment]
RBAC does not have deny rules because results can be surprising.  Particularly when there are many allow and deny rules.  This is an opinion that RBAC has about how to do authorization. 

We also have a webhook authorizer which can hook out to some other authorization system.  That other system might support deny (like [XACML does](https://www.axiomatics.com/blog/understanding-xacml-combining-algorithms/) -- it calls this PERMIT, DENY, and NEITHER).

So, at the level of plugins, I don't think we can say we have a "tradition".

Yes, you can hackily do this as admission control.  But then Access Reviews don't work.

**Comment by bgrant0607** [comment]
@smarterclayton Mike started with an admission controller for this purpose and it looked to me like a lot of extra mechanism and config-based APIs for another authorization mechanism to prevent mutation and/or deletion. Arguably the authorization hook would be a better place for it if we could AND authorizers, which also would have helped with the ABAC->RBAC transition.

**Comment by luxas** [comment]
Side note, if we had something like this, it'd be much easier to self-host certificates in Secrets.
Putting the CA key or similar up in the cluster now is just not possible (in the reasonable secure vs convenience tradeoff)
I haven't considered all edge cases with the even when having an authorizer that could unconditionally DENY requests (from anyone but users with `cluster-admin` privs in this case), but it would at least make it possible to start thinking about that then

**Comment by liggitt** [comment]
> Side note, if we had something like this, it'd be much easier to self-host certificates in Secrets.
> Putting the CA key or similar up in the cluster now is just not possible (in the reasonable secure vs convenience tradeoff)

It wouldn't solve list/watch exposure/filtering issues... I think this would be more useful for denying specic write cases

**Comment by bgrant0607** [comment]
allowed is a bool in the v1 API:
https://github.com/kubernetes/api/blob/master/authorization/v1/types.go#L173

```
type SubjectAccessReviewStatus struct {
	// Allowed is required.  True if the action would be allowed, false otherwise.
	Allowed bool `json:"allowed" protobuf:"varint,1,opt,name=allowed"`
	// Reason is optional.  It indicates why a request was allowed or denied.
	// +optional
	Reason string `json:"reason,omitempty" protobuf:"bytes,2,opt,name=reason"`
	// EvaluationError is an indication that some error occurred during the authorization check.
	// It is entirely possible to get an error and be able to continue determine authorization status in spite of it.
	// For instance, RBAC can be missing a role, but enough roles are still present and bound to reason about the request.
	// +optional
	EvaluationError string `json:"evaluationError,omitempty" protobuf:"bytes,3,opt,name=evaluationError"`
}
```

https://kubernetes.io/docs/admin/authorization/

"When multiple authorization modules are configured, each is checked in sequence, and if any module authorizes the request, then the request can proceed. If all modules deny the request, then the request is denied."

Are there use cases for the current OR behavior?

In all scenarios I can imagine, combinations of policies (ABAC+RBAC or RBAC+Webhook) would be more useful with AND behavior.

**Comment by bgrant0607** [comment]
Admission control also uses AND behavior for this reason.

**Comment by bgrant0607** [comment]
Here is the union authorizer:
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/authorization/union/union.go#L36

```
	for _, currAuthzHandler := range authzHandler {
		authorized, reason, err := currAuthzHandler.Authorize(a)

		if err != nil {
			errlist = append(errlist, err)
		}
		if len(reason) != 0 {
			reasonlist = append(reasonlist, reason)
		}
		if !authorized {
			continue
		}
		return true, reason, nil
	}

	return false, strings.Join(reasonlist, "\n"), utilerrors.NewAggregate(errlist)
```

It seems not hard to also create an Intersection authorizer.

**Comment by bgrant0607** [comment]
Tri-state can be conveyed via `reason` as `DontCare`

**Comment by deads2k** [comment]
> In all scenarios I can imagine, combinations of policies (ABAC+RBAC or RBAC+Webhook) would be more useful with AND behavior.

In the +webhook case, I can imagine cases where RBAC says deny because someone doesn't match a rule, but a webhook has other knowledge about that user being awesome and says "allow".

Moving to a tri-state of `Allowed`, `NotAllowed`, and `Denied` would allow backward compatible composition.  You could also build it as a series of unions with `DenyEarly` behavior, but I don't know that I'd find that to be easier to understand.

**Comment by bgrant0607** [comment]
@deads2k Why wouldn't someone use a superuser credential in that scenario instead?

**Comment by deads2k** [comment]
> @deads2k Why wouldn't someone use a superuser credential in that scenario instead?


The general case of a subset of users managed by a different authorization system.  You have a set of people (say tenant admins), which aren't super-users, but your webhook authorizer makes sure that these people always have the power to view pods across all the tenant's namespaces.  Not the ops-owned namespaces (so you can't have a cluster role), but all the user owned ones.

Slightly less likely, but also possible and one I've heard pitched: perhaps they aren't a super-user, but have temporarily elevated access.  Maybe they have used user.Extra (also powered by webhook), to have a extra field that their authorizer webhook understands and lets them add nodes.  This lets the audit trail look normal.

Or another case pitched by the openstack guys a while back involved an authorizer that had a secondary check based a lookup in a separate system.

**Comment by mattmoyer** [comment]
+1 for this, I also have a similar use case where I would like a specific authorizer to return a hard deny in some scenarios.

One tricky case is how to configure a webhook authorizer such that you can choose to interpret timeouts/errors as soft denies (`NotAllowed`/`DontCare`) or hard denies (`Denied`).

**Comment by mikedanese** [comment]
Any webhook authorizer that can return a hard deny should fail closed.

**Comment by mikedanese** [comment]
I don't understand how an intersection authorizer would be used to integrate with a system like GCP IAM which is default deny with the current bool return. Does the intersection authorizer assume the tristate?

**Comment by liggitt** [comment]
if the authorizer interface was modified to include tri-state, then yes, the union authorizer would assume the tristate.

the webhook impl would need to:
* treat current responses in a backwards compatible way (meaning "no opinion")
* treat current request failures in a backwards compatible way (meaning "no opinion")
* expand the response status to allow returning an explicit denial
* allow configuring to treat a request failure as a hard deny
