### ISSUE TITLE
error in running hyperkube on ubuntu 

### ISSUE THREAD

**Issue by drneo-mehdi** [kubernetes/kubernetes#51878]
hi 
i got this error when i try to run kubernetes api-master container with hyperkube 

my docker version is 1.12.6, build 78d1802  on ubuntu 16.04
i try to run kubernetes 1.7.5 
 
my command 
`docker run -d --net=host gcr.io/google-containers/hyperkube:v1.7.5 /hyperkube apiserver --bind-address=172.16.2.14 --service-cluster-ip-range=172.16.85.0/24 --etcd-servers=http://127.0.0.1:4001 --allow-privileged=true --insecure-bind-address=172.16.2.14  --admission-control=NamespaceLifecycle,LimitRanger,DefaultStorageClass,ResourceQuota --v=2`

then i check the log output of api container and i got this error 
`E0903 21:08:50.327826       1 autoregister_controller.go:167] v1beta1.authentication.k8s.io failed with : Operation cannot be fulfilled on apiservices.apiregistration.k8s.io "v1beta1.authentication.k8s.io": the object has been modified; please apply your changes to the latest version and try again`

**Comment by cblecker** [comment]
Please re-post your question to [Stack Overflow](http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases.

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans Stack Overflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search Stack Overflow for answers to similar questions, and also familiarize yourself with:

  * [user documentation](http://kubernetes.io/docs/)
  * [troubleshooting guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/)

Again, thanks for using Kubernetes.

The Kubernetes Team

---
/kind support
/close
