### ISSUE TITLE
[DaemonSet] rejected pods are re-created too fast to get any log or event

### ISSUE THREAD

**Issue by resouer** [kubernetes/kubernetes#51884]
**Is this a BUG REPORT or FEATURE REQUEST?**:

 /kind feature

**What happened**:
I have a pod which is expected to be rejected by admission. It was rejected, and here's what I got:

```
root@stackube:~/code/kubernetes# kubectl get pods -n test
NAME         READY     STATUS    RESTARTS   AGE
test-x3th8   0/1       Pending   0          0s
root@stackube:~/code/kubernetes# kubectl get pods -n test
NAME         READY     STATUS    RESTARTS   AGE
test-6xt8d   0/1       Pending   0          1s
```
But the problem is **the rejected pod is re-created too fast** by ds controller, I have no way to check the details (e.g. events) of those pods. For example, check which admission plugin is rejecting my pod.

And the events in ds do not include pod's information either:
```
  39m		39m		1	daemonset-controller			Warning		FailedDaemonPod		Found failed daemon pod test/stackube on node test-bv9b5, will try to kill it
  39m		39m		1	daemon-set				Normal		SuccessfulCreate	Created pod: test-wt1fc
  39m		39m		1	daemonset-controller			Warning		FailedDaemonPod		Found failed daemon pod test/stackube on node test-jphr8, will try to kill it
  39m		39m		1	daemon-set				Normal		SuccessfulDelete	Deleted pod: test-jphr8
  39m		39m		1	daemonset-controller			Warning		FailedDaemonPod		Found failed daemon pod test/stackube on node test-wt1fc, will try to kill it
  39m		39m		1	daemon-set				Normal		SuccessfulDelete	Deleted pod: test-wt1fc
  39m		0s		3475	daemon-set				Normal		SuccessfulCreate	(combined from similar events): Created pod: test-m4t68
  39m		0s		3474	daemonset-controller			Warning		FailedDaemonPod		(combined from similar events): Found failed daemon pod test/stackube on node test-n4rjr, will try to kill it
  39m		0s		3474	daemon-set
```

**What you expected to happen**:

We need some mechanism to check the events of failed pod at least.

**How to reproduce it (as minimally and precisely as possible)**:

Create a DaemonSet which expected to be rejected by admission and try to debug its failure reason.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by resouer** [comment]
I am thinking we may need to set a retry limit in DS if Pod keeps stay in `PENDING` status? 

`PENDING` status usually means pod is stuck in some phase and worth to take a deeper look. It's meaningless to keep recreating it (will aways stuck)

**Comment by resouer** [comment]
@kubernetes/sig-apps-feature-requests

**Comment by lichuqiang** [comment]
+1 I met the same situation

**Comment by dixudx** [comment]
@resouer  Which plugin are you using. I tested using `ResourceQuota`, it works as expected.

**Comment by resouer** [comment]
@dixudx It's about rejected pod is re-creating too fast without frequency limit

**Comment by nikolas-hermanns** [comment]
I met the same issue. But from your answers I cannot see the solution. Should I edit the deamon set somehow?

**Comment by ZloyDyadka** [comment]
Same problem

**Comment by elasti-jeans** [comment]
/reopen

The issue is still there as of Kubernetes 1.11
In my case, the pod is running ok on 2 out of 3 nodes - but the last one has some issue, which I'm unable to debug due to the pod repeatedly getting into Pending and getting replaced with another one. Some kind of gradual backoff mechanism would be useful in this case.

This is what I see:
`
$ kubectl describe daemonset csi-mypod
Name:           csi-mypod
Selector:       app=csi-mypod
Node-Selector:  <none>
Labels:         <none>
Annotations:    deprecated.daemonset.template.generation: 1
Desired Number of Nodes Scheduled: 3
Current Number of Nodes Scheduled: 3
Number of Nodes Scheduled with Up-to-date Pods: 3
Number of Nodes Scheduled with Available Pods: 2
Number of Nodes Misscheduled: 0
Pods Status:  2 Running / 1 Waiting / 0 Succeeded / 0 Failed
...
Events:
  Type     Reason            Age   From                  Message
  ----     ------            ----  ----                  -------
  Normal   SuccessfulCreate  57s   daemonset-controller  Created pod: csi-mypod-rhztq
  Normal   SuccessfulCreate  57s   daemonset-controller  Created pod: csi-mypod-p989p
  Normal   SuccessfulCreate  57s   daemonset-controller  Created pod: csi-mypod-llnxd
  Warning  FailedDaemonPod   57s   daemonset-controller  Found failed daemon pod default/csi-mypod-llnxd on node gke-cluster-1-default-pool-4425673a-245r, will try to kill it
  Normal   SuccessfulDelete  57s   daemonset-controller  Deleted pod: csi-mypod-llnxd
  Normal   SuccessfulCreate  57s   daemonset-controller  Created pod: csi-mypod-l27z6
  Warning  FailedDaemonPod   57s   daemonset-controller  Found failed daemon pod default/csi-mypod-l27z6 on node gke-cluster-1-default-pool-4425673a-245r, will try to kill it
  Normal   SuccessfulDelete  57s   daemonset-controller  Deleted pod: csi-mypod-l27z6
  Normal   SuccessfulCreate  57s   daemonset-controller  Created pod: csi-mypod-n4hsz
  Warning  FailedDaemonPod   57s   daemonset-controller  Found failed daemon pod default/csi-mypod-n4hsz on node gke-cluster-1-default-pool-4425673a-245r, will try to kill it
  Normal   SuccessfulDelete  57s   daemonset-controller  Deleted pod: csi-mypod-n4hsz
  Normal   SuccessfulCreate  57s   daemonset-controller  Created pod: csi-mypod-hpsjb
  Warning  FailedDaemonPod   57s   daemonset-controller  Found failed daemon pod default/csi-mypod-hpsjb on node gke-cluster-1-default-pool-4425673a-245r, will try to kill it
  Normal   SuccessfulDelete  57s   daemonset-controller  Deleted pod: csi-mypod-hpsjb
  Normal   SuccessfulCreate  57s   daemonset-controller  Created pod: csi-mypod-j49g9
  Warning  FailedDaemonPod   56s   daemonset-controller  Found failed daemon pod default/csi-mypod-rhztq on node gke-cluster-1-default-pool-4425673a-245r, will try to kill it
  Normal   SuccessfulDelete  56s   daemonset-controller  Deleted pod: csi-mypod-rhztq
  Normal   SuccessfulCreate  56s   daemonset-controller  Created pod: csi-mypod-lm678
  Warning  FailedDaemonPod   56s   daemonset-controller  Found failed daemon pod default/csi-mypod-lm678 on node gke-cluster-1-default-pool-4425673a-245r, will try to kill it
  Normal   SuccessfulDelete  56s   daemonset-controller  Deleted pod: csi-mypod-lm678
  Normal   SuccessfulCreate  56s   daemonset-controller  Created pod: csi-mypod-fb5q5
  Warning  FailedDaemonPod   55s   daemonset-controller  Found failed daemon pod default/csi-mypod-fb5q5 on node gke-cluster-1-default-pool-4425673a-245r, will try to kill it
  Normal   SuccessfulDelete  55s   daemonset-controller  Deleted pod: csi-mypod-fb5q5
  Normal   SuccessfulCreate  55s   daemonset-controller  (combined from similar events): Created pod: csi-mypod-p7czr
  Warning  FailedDaemonPod   54s   daemonset-controller  Found failed daemon pod default/csi-mypod-p7czr on node gke-cluster-1-default-pool-4425673a-245r, will try to kill it
`
