### ISSUE TITLE
Volumes that finish attaching after pod is deleted take non-trivial amount of time before becoming available

### ISSUE THREAD

**Issue by gnufied** [kubernetes/kubernetes#52036]
We have hit on a problem more than once, where a user creates a pod but before volume could finish attaching to the node, he goes ahead and deletes the pod.

Such volumes aren't detached quickly enough because all attached volumes are assumed to be mounted (on attach) and hence https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/volume/attachdetach/reconciler/reconciler.go#L201 check prevents ADC from attempting to detach until 6 minute expires.

I am wondering, what is the purpose of following if condition is:

```
if attachedVolume.MountedByNode && !timeout {
				glog.V(12).Infof(attachedVolume.GenerateMsgDetailed("Cannot detach volume because it is still mounted", ""))
				continue
			}
```

We don't even try if `attachedVolume.MountedByNode` is set - until timeout expires.

**Comment by gnufied** [comment]
I have opened 2 follow up PRs for fixing this - first is https://github.com/kubernetes/kubernetes/pull/52037 which simply removes the check for `MountedByNode` condition. @saad-ali do yo remember why we shouldn't detach volumes which aren't in desired state of world and not-in-use by a node? 

The second approach as proposed by @tsmetana  is https://github.com/kubernetes/kubernetes/pull/52038 which makes sure that we don't attach volumes to a node until it is in use by a node.

**Comment by saad-ali** [comment]
This check is in place as a safety. In case a volume mount starts but has not yet been reported in VolumesInUse (race condition), we want to make sure that we don't start a detach volume operation resulting in data corruption. Therefore, removing this check, PR #52037, would remove this safety and I am strongly against that. PR #52038 proposes delaying the attach operation until a volume is reported as in use (i.e. mounting begins), I would prefer not do that because it would slow down the majority case to optimize for this edge case.

I would go as far as saying the system is working as intended in this case, it is optimized to prevent data corruption over speed of attach/detach. As an application developer, you should not depend on the availability of a single pod (or the speed of its attach/detach cycles).

**Comment by gnufied** [comment]
@saad-ali Yes I was thinking about same reason, but we have a check in place where we only start mounting a volume *after* it has been reported in `VolumesInUse` and we do this *after* writing to node status. https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/util/operationexecutor/operation_generator.go#L656 

in fact @jingxu97 pointed me to this code. I have written/writing an e2e test to reproduce the problem and make sure path we take doesn't break the behaviour - https://github.com/kubernetes/kubernetes/pull/52101

**Comment by jsafrane** [comment]
I agree with Saad. I think there is a possible race condition between A/D controller and kubelet.

1. A/D controller attaches a volume to a node
2. kubelet on the node is not responsive from some reason
3. kubelet wakes up (or is re-started) and sees the pod.
5. A/D controller finishes attaching the pod and writes "VolumesAttached"
6. kubelet writes VolumesInUse and starts mounting the volume
7. user deletes the pod
8. A/D controller still sees the old node status (without VolumesInUse) but it sees that the pod is gone. It **must not detach the volume at this point**, because kubelet is mounting.

5-8 need to happen really quickly, but it's possible.

**Comment by jingxu97** [comment]
@jsafrane I dont think step 7 will happen because VolumeInUse is already updated before mounting. In step 5 Before kubelet tries to mount, it makes sure that VolumeInUse is updated. The code is https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/util/operationexecutor/operation_generator.go#L656

There are four main events involves here
At Master
m1. Before detaching, mark volume not attached (remove from VolumeAttached list from node status)
m2. Check VolumeInUse list from node status. If volume is not in use, trigger detach
At node
n1. Before mount, mark volumeInUse in node status
n2. Check volumeAttached from node status, if volume is attached, trigger attach

For the step 5 and 7 happen mentioned in above, it means that m1 and n1 already happen first (doesn't matter in which order), it is not possible for both m2 and n2 check pass.

**Comment by jsafrane** [comment]
I talked to @gnufied and my race is indeed not possible. Both ADC and kubelet synchronously check that volume is safe for detach or mount and I did not find a way how **both** of them could detach and mount at the same time. One of them will end up with error and will either not detach or not mount.

It's really hard to spot it in the controller / volume manager though.

**Comment by saad-ali** [comment]
PR https://github.com/kubernetes/kubernetes/pull/52221 is also removing safety checks in order to speed up attach detach operations in edge cases. I would rather we operate slower and lean towards preventing data corruption. Optimizing this case seems counter productive to me. We should not be reducing this pain for users (we can never reduce the attach/detach to zero, and it can always take a very long time), instead we should be using this to encourage users not to rely on a single pod and encourage HA design architecture.

**Comment by jingxu97** [comment]
@saad-ali The safety check removed by PR #52221 is that volume must be marked as mounted by kubelet at least once before it can be seen as unmounted by attach_detach controller. If the volume is never been marked by kubelet, attach_detach controller assumes that volume is still mounted even if node status shows that it is not. My understanding for the purpose of this check is that when the pod is added, kubelet might not yet update the volumeInUse list. If during this time pod is deleted, attach_detach controller will pass the safe check and start to detach. But the key is that in this case,  reconciler on node will definitely not issue mount. 

As mentioned in my previous comment, reconciler on node always makes sure that the volume is already updated in VolumeInUse before triggering mount operation. It is possible that the VolumeInUse update might happen after detach operation checks the node status, but clearly in this case, mount will not be triggered because volume is no longer attached from node status (attach_detach controller updates this before checking volume mounted and detaching.)

The events happen on master and node are

At Master
```
m1. Before detaching, mark volume not attached (remove from VolumeAttached list from node status)
m2. Check VolumeInUse list from node status. If volume is not in use, trigger detach
```
At node
```
n1. Before mount, mark volumeInUse in node status
n2. Check volumeAttached from node status, if volume is attached, trigger attach
```
Here we can list all the the possible permutations of event sequence. None of them can result in detach while it is still mounted or is being mounted. 
A: m1 m2 n1 n2
B: m1 n1 m2 n2
C: n1 n2 m1 m2
D: n1 m1 m2 n2

So this extra check is not necessary from the analysis here. Another point is that this check counts the total number of mounts ever happened for this volume on the node. It is possible that this number is updated some time ago for other pods. So it might not work as intended. 

Please let me know if you think I miss some points. Thanks!

**Comment by gnufied** [comment]
Just to add my 2 cents. I have more than once gone through the code flow and again discussed same with @jsafrane and race against which the `if` check protects doesn't exist.  I wouldn't mind waiting for 6 minutes, if the check helped but as @jingxu97 points out - it doesn't. 

The first thing I had to convince myself about is, a mount on node can not proceed without marking the `VolumeInUse` in `node.Status` field. And by marking `VolumeInUse` - I mean actually writing to node object and updating it, not just marking the volume in memory.  So, if a  mount is in progress - ADC can *never* detach that volume. 

Also @jingxu97 thank you for detailed write up. 

@saad-ali it is still possible that we missed something and it doesn't hurt to err on the side of caution, but before we do that - I would like to document race against which this check guards, so as we have better code comments and clear documentation of why we are doing, what we are doing.
