### ISSUE TITLE
kubeadm offline installer support

### ISSUE THREAD

**Issue by helphi** [kubernetes/kubernetes#52068]
We hope `kubeadm` can support offline installer such as `kubectl` and `minikube`, because we can't access google cloud in China.

**Comment by hzxuzhonghu** [comment]
+1

**Comment by kevin-wangzefeng** [comment]
kubeadm supports to download images from custom repositories.
You can first download the images with from google cloud and upload them to your own repository, and then use the command like below.
```shell
KUBE_REPO_PREFIX=${kube_repo_prefix} kubeadm init 
```

**Comment by helphi** [comment]
I mean how to install `kubeadm` itself offline. 

For example, i can download `minikube` from <https://github.com/kubernetes/minikube/releases>, and then put it in `/usr/local/bin`, but i can't download `kubeadm` from somewhere because it is in google cloud apt repository.

**Comment by roberthbailey** [comment]
@helphi - please reopen this issue in the [kubeadm repository](https://github.com/kubernetes/kubeadm).

**Comment by ghaering** [comment]
This link does (no longer?) exist: https://kubernetes.io/docs/admin/kubeadm/#running-kubeadm-without-an-internet-connection

**Comment by katanyoussef** [comment]
kevin-wangzefeng : thanks for the big help, to install the kubeadm need to install 3 pckgs and the CNI pckgs and copy them i have done it all good and Kevin provide what i was messing thanks you are great...NOW i need to know how to deploy : see that Master Node is listed as not ready. Because the cluster does not have a Container Networking Interface (CNI).

Let’s deploy a Calico CNI for the Master Node with the following command:

kubectl apply -f X yaml file ??? the yaml file from where and how to creat one : Kevin any suggestion thanks Again.
