### ISSUE TITLE
Clean up history jobs for cronjob

### ISSUE THREAD

**Issue by gyliu513** [kubernetes/kubernetes#52390]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug

/kind feature
/sig apps

**What happened**:

Currently, if I was running a cronjob, then there will be quite a lot of completed jobs in my environment, and the completed jobs may impact the performance of API server.

**What you expected to happen**:
Add some parameters or annotations to define how many completed jobs can be kept in cronjob history.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by dixudx** [comment]
@gyliu513 @janetkuo I would like to implement this.

Simply changing current `GarbageCollectionPolicy` is not working, since the cronjob is still running. And the pods are not orphan.

https://github.com/kubernetes/kubernetes/blob/be78d113b1fa40cfa17e4973d3aa1b1c2e709edd/pkg/registry/batch/cronjob/strategy.go#L40-L44

I think we could follow current [`ImageGC`](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/images/image_gc_manager.go#L41). There are several options for this.

1. Add new flag for `kubelet`;
2. Set default `GCPeriod = 5 * time.Minute` for `CronJob`;

**Comment by dixudx** [comment]
ping @gyliu513 @janetkuo Any comments on above options.

**Comment by janetkuo** [comment]
You can have history jobs garbage collected by setting `.spec.successfulJobsHistoryLimit` and `.spec.failedJobsHistoryLimit` fields. 

The old default value is unlimited (keep all history jobs). In 1.8, batch/v1beta1 CronJobs have new default values (keep 3 successful jobs and 1 failed job).

**Comment by janetkuo** [comment]
Closing, as this is already fixed and [documented](https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/#jobs-history-limits). New default values are also documented in https://github.com/kubernetes/kubernetes.github.io/pull/5556
