### ISSUE TITLE
support GPU Resource reserved for each user/namespace

### ISSUE THREAD

**Issue by pineking** [kubernetes/kubernetes#52412]
**Is this a BUG REPORT or FEATURE REQUEST?**:

 /kind feature

**What you expected to happen**:
Support GPU reserved for each user/namespace, for example, if we can reserve 2 GPUs for each user, the user can use 2 GPUs at any time without pending or waiting for the GPU resources to free.

**Comment by pineking** [comment]
@vishh @cmluciano

**Comment by vishh** [comment]
Kubernetes provides a feature called Quota that is expected to help distribute compute resource capacity between namespaces. Support for GPU quota will not land anytime soon because we need better APIs to represent an extensible resource in the Quota sub-system.

How serious of an issue is this @pineking ? You should be able write your own quota admission controller that interacts with your user GPU allocation administration pipeline until upstream supports it. 

@cmluciano may be it's worth publishing a quota extension sample code that will help users add quota support for GPUs via CRDs.

**Comment by pineking** [comment]
@vishh I hope this feature can be implemented as soon as possible. that's great if @cmluciano can give some sample code. 

BTW， I search the issues and find https://github.com/kubernetes/kubernetes/issues/46639#issuecomment-324414548, does this mean the Quota feature will be released until v1.10 or 6 months later ?

**Comment by vishh** [comment]
Dates are TBD. For now, we are focussing on stabilizing core
implementation. I'd recommend running Initializer based extensions for now.

**Comment by seelam** [comment]
we (IBM) has a prototype implementation of GPU quota support, @cmluciano will help to bring it out and share it.

**Comment by pineking** [comment]
@seelam @cmluciano Thank you! please let me know when you share it, I can test it.

**Comment by cmluciano** [comment]
@vishh Sounds good, will try something out

**Comment by pineking** [comment]
@cmluciano do you have the plan to implement this in v1.9?

**Comment by jiayingz** [comment]
@pineking @lichuqiang is working on supporting quota for extended resources that covers gpu: https://github.com/kubernetes/kubernetes/pull/57302
Please take a look and let us know if that satisfies your use case.

**Comment by pineking** [comment]
@jiayingz Yes, I have commented on #57302 and waiting it merged, I can test that on the later of this week.

**Comment by pineking** [comment]
close this issue, since #57302 is merged now.

**Comment by mingfengwuye** [comment]
@seelam could you share some info with me about GPU quota support ?

**Comment by pineking** [comment]
@mingfengwuye this feature is merged, see https://github.com/kubernetes/kubernetes/pull/57302
