### ISSUE TITLE
AllowPrivilegeEscalation missing API validation

### ISSUE THREAD

**Issue by tallclair** [kubernetes/kubernetes#52454]
**What happened**:
The new `AllowPrivilegeEscalation` feature has silent defaulting logic performed in the kubelet, related to whether the container requests privileged mode or the CAP_SYS_ADMIN capability. Instead, the kubelet should just use the value of the field if specified, and validation should be added to prevent setting the field to true for privileged or CAP_SYS_ADMIN containers.

/cc @jessfraz

**Comment by jessfraz** [comment]
crap sorry about this

**Comment by jessfraz** [comment]
I assigned myself

**Comment by liggitt** [comment]
Assigning to the milestone to fix before release

**Comment by liggitt** [comment]
@jessfraz @tallclair what's the plan for this for 1.8?

**Comment by jessfraz** [comment]
I will open a PR today

**Comment by jessfraz** [comment]
so hmmm, the default is `nil` and the function `AddNoNewPrivileges` isn't doing the default, it is setting the `NoNewPrivs` for the cri used, ex. https://github.com/kubernetes/kubernetes/blob/b32639f9e7d47d0f69bb41b5535803ae4c9d835a/pkg/kubelet/kuberuntime/security_context.go#L72 and https://github.com/kubernetes/kubernetes/blob/9737efccf0e026e2e2437aa31c4365577d628bd5/pkg/kubelet/rkt/rkt.go#L442

Is this still something that should be done in `pkg/api/v1/defaults.go, because the field `NoNewPrivs` is in the CRI api: https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/apis/cri/v1alpha1/runtime/api.pb.go#L1413

**Comment by tallclair** [comment]
I was thinking the field `SecurityContext.AllowPrivilegeEscalation` could be defaulted in `pkg/api/v1/defaults.go`, and then https://github.com/kubernetes/kubernetes/blob/b32639f9e7d47d0f69bb41b5535803ae4c9d835a/pkg/kubelet/kuberuntime/security_context.go#L72
could just be simplified to `synthesized.NoNewPrivs = !*effectiveSc.AllowPrivilegeEscalation` (plus handle nil)

**Comment by dims** [comment]
@tallclair @jessfraz - quick question from the release team, do we have any PR's for this issue? (getting a bit late for 1.8)

**Comment by jessfraz** [comment]
Sorry I'm working on it I'll open something today

**Comment by jdumars** [comment]
@jessfraz @tallclair - we need to determine (today if possible) if this is truly release blocking.  If so, please add the release-blocker label.  And, if not, how do we best continue work on this for 1.8.x/1.9.0?

**Comment by spiffxp** [comment]
this awaiting approval and cherry-picking of https://github.com/kubernetes/kubernetes/pull/52803

**Comment by jessfraz** [comment]
Here is the cherry-pick as well https://github.com/kubernetes/kubernetes/pull/53003
