### ISSUE TITLE
OpenStack cloud provider should support project instead of tenant

### ISSUE THREAD

**Issue by henriquetruta** [kubernetes/kubernetes#52563]
OpenStack cloud provider receives variables `tenant-id` and `tenant-name`. 'tenant' is a term that corresponds to OpenStack v2.0 identity API, which is deprecated and is going to be removed in the next OpenStack release (Queen). 

We should support user providing `project-id` and `project-name`, that come from v3, the current Identity API. The ideal behavior would be that when project and tenant are both provided, the tenant values are ignored

/kind bug

**Comment by bugosiphionah** [comment]
I am applying for outreachy and would love to work on this.

**Comment by xsgordon** [comment]
@bugosiphionah great! Thanks for reaching out, you can find us in #sig-openstack on the Kubernetes slack if you want to discuss further.

**Comment by arthur0** [comment]
The **Keystone V2 API** is deprecated and **will be removed in the next OpenStack release** (Queens).
Since Mitaka [release notes](https://docs.openstack.org/releasenotes/keystone/mitaka.html):
Keystone supports `project_id` in the catalog. It works the same as `tenant_id`. Use of `tenant_id` is deprecated and catalog endpoints should be updated to use `project_id`.

**Comment by dims** [comment]
/close 

right now we support both v2 and v3 and things seem to be working. we can revisit when we drop v2 keystone api
