### ISSUE TITLE
kubectl apply should have a way to indicate "no change"

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#52577]
Some configuration management systems distinguish between "no change", "changed", and "failed".  It should be possible to use kubectl apply and know when any changes were applied from normal shell scripting

Since "no-op" is also success, and we don't expect clients to parse our stdout/stderr, it seems reasonable that we should allow a kubectl apply caller to request that a no-op be given a special exit code that we ensure no other result can return.  Since today we return 1 for almost all errors, we have the option to begin defining "special" errors.

Possible options: 

* `kubectl apply ... --fail-when-unchanged=2` returns exit code 2 (allows user to control exit code)
* `kubectl apply ... --fail-when-unchanged` returns exit code 2 always (means we can document the exit code as per UNIX norms)

The latter is probably better.  Naming of course is up in the air.

@kubernetes/sig-cli-feature-requests 

I rate this as high importance for integration with config management (like Ansible) which expects to be able to discern this.

**Comment by shiywang** [comment]
sounds interesting, @fabianofranz @pwittrock I would like to dibs on it.

**Comment by shiywang** [comment]
hi, @smarterclayton also need confirm you, this is only for apply right ? we do not currently want other declarative/Imperative object configuration commands or even every command to have this flag right ?
otherwise the tittle would be like `implement a custom return error code mechanism for kubectl`

**Comment by smarterclayton** [comment]
In the future this would likely be extended to other declarative commands.
We should pick a pattern that would translate to all other declarative
commands.  Apply is the important one right now.

**Comment by pwittrock** [comment]
Sounds like a good idea.  I remember sometime back there were issues where apply see detect that there were changes when there in fact were none.  This may have since been resolved.  I *think* it was due to an interaction with round tripping and defaulting, but don't quite remember.

This would fit nicely with the other apply renovations we are doing to address long standing issues.

RE priority art for other unix utils.

`diff` exits 0 on no differences, 1 on differences found, and 1> on error
`grep` exits 0 on lines found, 1 on no lines found, and 1> on error

If we had a green field, it might be worth trying to do something consistent - perhaps exit 1 if we make changes and 0 if we don't make any changes.  That might lend itself to a retry loop to - fetch recent, apply, retry on non-0 exit (expecting that the next apply will return 0 if no changes, and maybe doing exponential backoff for exit >1).

This of course may impact existing scripts, so doing as you suggested and making it opt-in is the better route, and then add this to the list of things we would like to change when we do something that allows us to break backward compatibility (e.g. introducing a new "version" of the command or something). 

Re naming: maybe something like `--exit-failure-unchanged`?

**Comment by mengqiy** [comment]
This feature will be helpful. And it doesn't require big change since apply already can distinguish if there is a change (but it only print it out).

I agree with @pwittrock's opinion, make it opt-in for now and change the behavior in future major version change.

**Comment by mengqiy** [comment]
> it doesn't require big change since apply already can distinguish if there is a change (but it only print it out).

@shiywang Sorry, I was wrong. It is actually `kubectl edit` that can distinguish if there is a change and print `no changes made`.

**Comment by huyqut** [comment]
Is there any progress on this?

**Comment by soltysh** [comment]
There's a server-side apply working group, which is working on moving the apply command to the server. I'd be good to sync with them for the update.

**Comment by tpoindessous** [comment]
Hi @soltysh , could be please re-open this issue if it's not finished ?

Thanks !

**Comment by cardil** [comment]
@soltysh Can we get this re-opened? It looks like it's still a valid concern.
