### ISSUE TITLE
Surface cloud-provider-specific information in Services of type LoadBalancer

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#52670]
Service of type LoadBalancer is backed by a cloud-provider-specific load balancer. Due to the inherent differences in networking, each cloud provider supports a very different sets of features and/or configurations exposed via annotations. For example, the Service annotations supported on AWS:
https://github.com/kubernetes/kubernetes/blob/8c025bc2f23a3be059bf9a7d05867a8cb6f52ea8/pkg/cloudprovider/providers/aws/aws.go#L83-L145

There are many known downsides of using annotations (e.g., lack of validation, defaulting, etc), but that's not the focus of this issue. 

One problem with hiding all these vastly different implementations behind a generic Service object is that it's hard for users to introspect the status using the kubernetes API.
In fact, the `LoadBalancerStatus` contains only a single field, LoadBalancerIngress, which is the lowest common denominator of all possible load balancers. 
```go
// LoadBalancerStatus represents the status of a load-balancer.
type LoadBalancerStatus struct {
	// Ingress is a list containing ingress points for the load-balancer.
	// Traffic intended for the service should be sent to these ingress points.
	// +optional
	Ingress []LoadBalancerIngress `json:"ingress,omitempty" protobuf:"bytes,1,rep,name=ingress"`
}
```
Users would not be able to verify whether a LB is configured as expected, or whether a change to an annotation has taken effect or not (and all annotations are mutable). To actually verify the correctness of a load balancer, a user would need in-depth understanding of the both cloud networking and the implementation of cloud-provider code in the controller while interacting directly with the cloud platform UI. That doesn't lead to great user experience. 

Some potential solutions that have been brought up in previous discussions:
 1. Add an opaque key-value map as part of `LoadBalancerStatus`. 
 2. Include cloud-provide-specific information in Events. (caveat: events are ephemeral and can be spammy when used this way).

Thoughts?

@kubernetes/sig-network-feature-requests @thockin @bowei

**Comment by thockin** [comment]
I like the idea of status for this.  We've tried to stay away from string-string maps in general, but it seems appropriate here.  Something like:

```
status:
  loadBalancer:
    ingress:
    - 1.2.3.4
    properties:
        cloud.google.com/fowarding-rule: a1234567890abcdef
        cloud.google.com/somethign: SomeValue
```

"properties" is a terrible name, but you get the idea.  Better than storing annotations perhaps, though it is sort of a slippery distinction.

@smarterclayton @bgrant0607

**Comment by bowei** [comment]
Should there be something like a `HasError: bool` field at the top level? Seems useful to make that piece generic

**Comment by yujuhong** [comment]
> Should there be something like a HasError: bool field at the top level? Seems useful to make that piece generic

I agree that some generic fields will be useful (in addition to the opaque field), and I think it can be more than a boolean field. There is a long discussion thread on state/phase/condition/outlook in #7856. I am not sure whether any conclusion has been drawn yet.

**Comment by smarterclayton** [comment]
Another option (for consistency) - have the controller write to a new typed
object that is mostly status (AWSLoadBalancerService) and have the service
point to it via Ref.  Do it as a CRD to start.


On Sep 18, 2017, at 8:47 PM, Yu-Ju Hong <notifications@github.com> wrote:

Should there be something like a HasError: bool field at the top level?
Seems useful to make that piece generic

I agree that some generic fields will be useful (in addition to the opaque
field), and I think it can be more than a boolean field. There is a long
discussion thread on state/phase/condition/outlook in #7856
<https://github.com/kubernetes/kubernetes/issues/7856>. I am not sure
whether any conclusion has been drawn yet.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/52670#issuecomment-330395718>,
or mute the thread

**Comment by thockin** [comment]
That level of reconciliation feels heavy for something we don't really know
we'll use beyond map[string]string...

**Comment by bgrant0607** [comment]
As for general properties, such as cases where the LB is not functioning, I agree those should just be fields, as proposed in #7856. Further motivation is discussed in #34363 and #1899.

As for cloud-specific properties or other types of extensions (e.g., with kube-proxy replaced by another solution), I think we have a number of cases where we need that across the system. Some are discussed in #31571 and in the architectural roadmap.

I can see why @smarterclayton suggested a CRD in this case.

Rather than annotations, I would like to be able to express a schema for extension parameters, sort of like StorageClass, but also with parameter descriptions and types. That starts to look like what was proposed for [CRD validation](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/api-machinery/customresources-validation.md). Not only could we then validate the parameters, but users could also see what options were available.

Similarly for status, we'd want to at least document what information the user could expect to be provided. And the cloud provider controller would need a mechanism to report it. A CRD with a [status subresource](https://github.com/kubernetes/community/pull/913) would provide such a mechanism.

That seems much cleaner than annotations and a map of strings.

Whether we choose a status map or a CRD, I think we're going to need significant changes to Service next year, before moving it to a new API group, so we will have an opportunity to change this in the future.

OOC, is the Service type NodePort for AWS rather than type LoadBalancer? Do we need to support the additional status properties for multiple types of services?

cc @kubernetes/sig-architecture-proposals

**Comment by thockin** [comment]
> As for general properties, such as cases where the LB is not functioning, I agree those should just be fields, as proposed in #7856. Further motivation is discussed in #34363 and #1899.
>
> As for cloud-specific properties or other types of extensions (e.g., with kube-proxy replaced by another solution), I think we have a number of cases where we need that across the system. Some are discussed in #31571 and in the architectural roadmap.
>
> I can see why @smarterclayton suggested a CRD in this case.

I can see it too, but it feels like a heavy answer.  It is more
elegant, especially for pure status.  How would life-cycle work?

Google's CloudProvider registers CRD for `GoogleCloudLoadBalancerStatus`.
User creates Service `type: LoadBalancer`
Google's service LB controller actuates against GCP
Google's CloudProvider instantiates `GoogleCloudLoadBalancerStatus`
and links it from Service.status.LoadBalancer
User deletes Service

Now what?  We don't want to leave that status laying around.  A
finalizer, I guess?

> Rather than annotations, I would like to be able to express a schema for extension parameters, sort of like StorageClass, but also with parameter descriptions and types. That starts to look like what was proposed for CRD validation. Not only could we then validate the parameters, but users could also see what options were available.

Yeah, if this is to be schema'd, I don't want to do that more than one place.

> Similarly for status, we'd want to at least document what information the user could expect to be provided. And the cloud provider controller would need a mechanism to report it. A CRD with a status subresource would provide such a mechanism.

"With a status subresource" or "as a status expander"?  I don't know
that this would have any non-status fields, but I guess consistency?

> That seems much cleaner than annotations and a map of strings.
>
> Whether we choose a status map or a CRD, I think we're going to need significant changes to Service next year, before moving it to a new API group, so we will have an opportunity to change this in the future.

Agree.  I want to be expedient, and I think a string-map is honestly
good enough here, but I see the allure of a CRD for consistency across
many situations.

> OOC, is the Service type NodePort for AWS rather than type LoadBalancer? Do we need to support the additional status properties for multiple types of services?

AWS uses LoadBalancer and NodePort types the same as GCP.  AWS
LoadBalancer is more like GCP's ingress - a full proxy.

**Comment by smarterclayton** [comment]
On Mon, Oct 9, 2017 at 1:50 AM, Tim Hockin <notifications@github.com> wrote:

> > As for general properties, such as cases where the LB is not
> functioning, I agree those should just be fields, as proposed in #7856.
> Further motivation is discussed in #34363 and #1899.
> >
> > As for cloud-specific properties or other types of extensions (e.g.,
> with kube-proxy replaced by another solution), I think we have a number of
> cases where we need that across the system. Some are discussed in #31571
> and in the architectural roadmap.
> >
> > I can see why @smarterclayton suggested a CRD in this case.
>
> I can see it too, but it feels like a heavy answer. It is more
> elegant, especially for pure status. How would life-cycle work?
>
> Google's CloudProvider registers CRD for `GoogleCloudLoadBalancerStatus`.
> User creates Service `type: LoadBalancer`
> Google's service LB controller actuates against GCP
> Google's CloudProvider instantiates `GoogleCloudLoadBalancerStatus`
> and links it from Service.status.LoadBalancer
> User deletes Service
>
> Now what? We don't want to leave that status laying around. A
> finalizer, I guess?



Garbage collection



>
>
> > Rather than annotations, I would like to be able to express a schema for
> extension parameters, sort of like StorageClass, but also with parameter
> descriptions and types. That starts to look like what was proposed for CRD
> validation. Not only could we then validate the parameters, but users could
> also see what options were available.
>
> Yeah, if this is to be schema'd, I don't want to do that more than one
> place.



A CRD is supposed to be as easy as a map[string]string but typed.



>
>
> > Similarly for status, we'd want to at least document what information
> the user could expect to be provided. And the cloud provider controller
> would need a mechanism to report it. A CRD with a status subresource would
> provide such a mechanism.
>
> "With a status subresource" or "as a status expander"? I don't know
> that this would have any non-status fields, but I guess consistency?



And until we have a status subresource, you can still fetch the CRD (you
just have to remember that it's not "trusted" nor is any RBAC enforced).



>
>
> > That seems much cleaner than annotations and a map of strings.
> >
> > Whether we choose a status map or a CRD, I think we're going to need
> significant changes to Service next year, before moving it to a new API
> group, so we will have an opportunity to change this in the future.
>
> Agree. I want to be expedient, and I think a string-map is honestly
> good enough here, but I see the allure of a CRD for consistency across
> many situations.



As above, if CRD isn't as easy as map[string]string and better in every way
(get, explain, validation support) then CRD has failed.

**Comment by bgrant0607** [comment]
Ref #18451, #8992

**Comment by bgrant0607** [comment]
Probably nothing prevents the service controller from writing annotations via the service /status endpoint. Is there a reason to not do that for now?

**Comment by thockin** [comment]
No, annotations work, for now.  Just looking for patterns.

**Comment by bgrant0607** [comment]
In terms of patterns, I would like to be able to express application "topology" in a fully portable manner, but then also automatically discover provider-specific spec and status extensions. I think that implies we will want to embed the extensions in the portable resources, but that we do need a way to specify the schema for discovery purposes. I had originally wanted to specify such extension schemas in FooClass-style resources, but with something more like JSON schema than just a map of strings. We could potentially even automatically inject the schemas into the appropriate places in our OpenAPI spec at runtime, once we have the ability to express unions.

That may seem heavyweight, but we need more formal specs in order to build the kinds of docs and tools we need. The mass of annotations and maps of arbitrary strings we have is undiscoverable and incomprehensible to almost everyone but core project contributors.

Ref #31571.

**Comment by thockin** [comment]
Why embed rather than link-to-CRD or similar, as we discussed previously?

**Comment by thockin** [comment]
Moving discussion to https://github.com/kubernetes/kubernetes/issues/70159

**Comment by sftim** [comment]
For tidiness
/close not-planned
