### ISSUE TITLE
Make kube-apiserver play nice with logrotate

### ISSUE THREAD

**Issue by 2rs2ts** [kubernetes/kubernetes#52865]
/kind feature

We use logrotate at my workplace to handle log rotation and to update rsyslog when file handles change after rotation. The problem is that the apiserver rotates its own audit logs, so when this happens rsyslog loses the file handle. If we could use logrotate instead to rotate the audit logs, then we'd be able to notify rsyslog to update its file handle. But the apiserver does not have an option to turn its own rotation off.

If the apiserver could be configured to not rotate its logs (and maybe to gracefully handle when its own logs get rotated by receiving a SIGHUP) that would go a long way towards making the audit logs fit nicely in our (and probably others') existing log rotation strategies.

Of course you can use the `reopenOnTruncate` feature in rsyslog >8.16.0 but not everyone has access to that. In my case I was able to upgrade but I'm sure not everyone uses rsyslog >8.16.0. Their logging solution may not handle the way the apiserver rotates its logs.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.7.0

**Comment by 2rs2ts** [comment]
@kubernetes/sig-api-machinery-feature-requests

**Comment by caesarxuchao** [comment]
cc @mml

**Comment by r7vme** [comment]
We are using (wanted to use) `logrotate` for audit log, because native rotation does not support compression. Unfortunately neither default option (when file moved) neither `copytruncate` are working.

With `copyrtuncate` i'm getting binary thrash in log file and apiserver just keeps writing to the same file (size just keep growing).

Looks like latest [lumberjack.v2](gopkg.in/natefinch/lumberjack.v2) has compression support.

**Comment by 2rs2ts** [comment]
@nikhita it's been a long time since I filed this but isn't

>If the apiserver could be configured to not rotate its logs (and maybe to gracefully handle when its own logs get rotated by receiving a SIGHUP) that would go a long way towards making the audit logs fit nicely in our (and probably others') existing log rotation strategies.

clear enough?

**Comment by nikhita** [comment]
@2rs2ts Sorry, I should have added more details.

The intent and the idea behind it is definitely clear. :+1: 

However, since issues labelled as `help wanted` are for new contributors, we also require that details about _how_ the change be made be included in the issue. Example: what files should be changed, what part of code to modify, etc.

More details about help-wanted labels here: https://github.com/kubernetes/community/blob/master/contributors/devel/help-wanted.md.

Once these details are added, please feel free to add the label back! Also, thank you for coming back to this issue even if it was filed an year ago! :)

**Comment by terinjokes** [comment]
/reopen

Still no way to disable lumberjack's rotation.
