### ISSUE TITLE
Audit usages of prometheus.MustRegister

### ISSUE THREAD

**Issue by cheftako** [kubernetes/kubernetes#52872]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**: #52801 Shows that prometheus.MustRegister will panic on things like dashes in the metric name. There are currently 138 calls to prometheus.MustRegister in the Kubernetes code base almost exclusively from controllers. We should audit the code to ensure that panic is the desirable response to a bad metric name for these calls vs. something like prometheus.Register which will instead return an error.

**What you expected to happen**: See above

**How to reproduce it (as minimally and precisely as possible)**: See #52801 

**Anything else we need to know?**: No

**Environment**: All
- Kubernetes version (use `kubectl version`): 1.9
- Cloud provider or hardware configuration**: All
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by frodenas** [comment]
I did an analysis on this issue, and this is what I found:

1. Most of the `prometheus.MustRegister`calls use a static metric name (hardcoded at the method invocation via a string and/or constant);
2. There is only a single case where the metric name is constructed dynamically (from a parameter), at the [pkg/util/metrics/util.go](https://github.com/kubernetes/kubernetes/blob/master/pkg/util/metrics/util.go#L50) file (and happens to be where #52801 panicked);

My proposal is:

a. For static metric names (1), leave them as they are;
b. For dynamic metric names (2), where the caller might not know that a parameter will be used to construct a metric name:
  1. Update the [pkg/util/metrics/util.go](https://github.com/kubernetes/kubernetes/blob/master/pkg/util/metrics/util.go#L50) file to use `prometheus.Register` instead of `prometheus.MustRegister`, and return the error if the metric cannot be registered (already submitted PR #53571);
  2. A quick search from the `metrics.RegisterMetricAndTrackRateLimiterUsage` method invocation (from the above file) results in 17 invocations, mostly controllers, but although `metrics.RegisterMetricAndTrackRateLimiterUsage` returns an error, no one of those 17 results is catching the error. So, we need to update all `metrics.RegisterMetricAndTrackRateLimiterUsage` invocations to catch the error (I plan to submit new PRs to address this).

/sig instrumentation

**Comment by wackxu** [comment]
- [x] ddd
- [x] ddd
- [x] ddd
- [x] ddd
- [x] ddd
- [ ] ddd
- [ ] ddd
- [ ] ddd
- [ ] ddd

**Comment by wackxu** [comment]
@frodenas We can trace all the task for update metrics.RegisterMetricAndTrackRateLimiterUsage invocations, and I am very happy to help fix it.
- [x] bootstrapsigner.go
- [x] tokencleaner.go
- [x] core.go
- [x] cronjob_controller.go
- [x] daemon_controller.go
- [x] deployment_controller.go
- [ ] endpoints_controller.go
- [ ] gc_controller.go
- [ ] job_controller.go
- [ ] namespace_controller.go
- [ ] node_controller.go
- [ ] replica_set.go
- [ ] replication_controller.go
- [ ] route_controller.go
- [ ] service_controller.go
- [ ] serviceaccounts_controller.go
- [ ] tokens_controller.go

**Comment by frodenas** [comment]
@wackxu Please go ahead with the ones not yet updated if you want.

**Comment by wackxu** [comment]
@frodenas OK, thanks!

**Comment by wackxu** [comment]
> but although metrics.RegisterMetricAndTrackRateLimiterUsage returns an error, no one of those 17 results is catching the error.

@frodenas now, we catch the error and when there return an error, we return `nil`  in the  `newcontroller` function . But in the test file we use `newcontroller` function for many times and Then there will be a lot of error in the test file, such as:

`Failed to create endpoint controller: Metric for endpoint_controller already registered`

then the test will always go fail. I think we should distinguish the error and when the error is Duplicate registration we dhould ignore it and return the normal controller.

**Comment by frodenas** [comment]
@wackxu Can you please provide an example where this is happening? I ran the tests on several controllers and haven't found that error. Ignoring this error doesn't seem a good idea IMO, if there're some tests that fail, we should investigate why are failing and fix them appropriately.

**Comment by frodenas** [comment]
@wackxu Sorry, I thought you were talking about the unit tests, didn't see the integration tests problem. I've submitted #53834 to fix this and ran the integration tests to check that creating multiple controllers don't fail anymore.

**Comment by wackxu** [comment]
@frodenas actually in some cases the unit tests is also failed such as endpoint controller、replicaset controller. because different set up before test. So we should take a action to resolve it.
