### ISSUE TITLE
AWS KMS for apiserver encryption

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#52916]
The APIServer now supports encryption of objects in etcd, and there is also support for storing the keys in GCE KMS (e.g. https://github.com/kubernetes/kubernetes/pull/48574)  We should also add support storing the keys in AWS KMS.

This likely means:

* Adding the appropriate integration with the AWS KMS APIs, probably the equivalent of the GCE KMS PRs
* Documenting the additional IAM policies needed
* Getting support into e.g. kops and getting e2e test coverage.

**Comment by justinsb** [comment]
cc @arun-gupta

**Comment by ericchiang** [comment]
cc @kubernetes/sig-auth-feature-requests

**Comment by luxas** [comment]
This is part of beta graduation requirements in that case https://github.com/kubernetes/kubernetes/issues/51965
I'd be a bit hesitant to add many more providers... See the discussion in https://github.com/kubernetes/kubernetes/pull/48574

**Comment by ericchiang** [comment]
Just an update, the Google Cloud KMS provider has been removed from the API server. https://github.com/kubernetes/kubernetes/pull/54759

KMS providers will be implemented externally. Discussion of that plugin interface can be followed here https://github.com/kubernetes/kubernetes/issues/51965

**Comment by ericchiang** [comment]
Support for a gRPC-based KMS integration point will be alpha in 1.10. We strongly recommend trying it out so we can get appropriate feedback for beta.

Feature issue: https://github.com/kubernetes/features/issues/460
Docs: https://github.com/kubernetes/website/pull/7479

Closing since the ability to integrate with AWS KMS merged.

/close
