### ISSUE TITLE
Patching a Pod removes the ownerReferences

### ISSUE THREAD

**Issue by cartmanume** [kubernetes/kubernetes#52979]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
We created a StatefulSet with one replicas to start with, what we wanted to do is to change the label on the Pod so that the Service that will send traffic to this Pod can be controlled depending on the labels that the Pod has. Later on we want to scale and have a hot standby where we do not want any traffic at all until failover is done. Changing the label worked just fine but we lost the ownerReferences from the Pod that points to the StatefulSet, and the StatefulSet is kind of broken after this since it does not see the pod anymore. We tried updating both with the Kube API and with `kubectl edit`.

**What you expected to happen**:
That the ownerReferences is kept when doing `kubectl edit` or patching with the Kube API.

**How to reproduce it (as minimally and precisely as possible)**:
Create a StatefulSet with one replica, check out the Pod with `kubectl get.... -o yaml`.
Run `kubectl edit` on the pod and change(or add) a label on the pod.
Check out the Pod again with `kubectl get.... -o yaml` 

Here is a diff showing this.
```
$ diff before.yaml after.yaml 
21c21
<     role: standby
---
>     role: master
24,31c24
<   ownerReferences:
<   - apiVersion: apps/v1beta1
<     blockOwnerDeletion: true
<     controller: true
<     kind: StatefulSet
<     name: foo-postgresql
<     uid: 0f6b9000-9ed0-11e7-9f91-0800270e339d
<   resourceVersion: "469568"
---
>   resourceVersion: "469642"
```

**Anything else we need to know?**:
I am not sure if this is by design, that you should not update pods in a StatefulSet?

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.6", GitCommit:"4bc5e7f9a6c25dc4c03d4d656f2cefd21540e28c", GitTreeState:"clean", BuildDate:"2017-09-15T08:51:09Z", GoVersion:"go1.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.5", GitCommit:"17d7182a7ccbb167074be7a87f0a68bd00d58d97", GitTreeState:"clean", BuildDate:"2017-09-07T18:20:02Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
minikube version: v0.22.0

**Comment by cartmanume** [comment]
@kubernetes/sig-api-machinery-bugs

**Comment by caesarxuchao** [comment]
I suspect that the ownerReference was removed by the kube-controller-manager after you changed the pod's label, because the label didn't match the stateful set's selector anymore. You can confirm that by checking the kube-apiserver log.

cc @kubernetes/sig-apps-misc for suggestion on what's the recommended way in your case.

**Comment by enisoc** [comment]
> Run kubectl edit on the pod and change(or add) a label on the pod.

Are you sure it still happens if you only *add* a label to the Pod, without changing any existing labels? If @caesarxuchao's explanation is right, then adding a label that was never mentioned in the original StatefulSet spec should not cause the ownerRef to disappear.

I think this technique should work as long as you're careful with your StatefulSet selector. For example, if you intend to change the `role` label to control whether it matches a Service, but you still want newly-created Pods to have a default value for that label, it should work to do something like this:

```yaml
apiVersion: apps/v1beta1
kind: StatefulSet
...
spec:
  selector:
    matchLabels:
      component: mything
  template:
    metadata:
      labels:
        component: mything
        role: standby
...
```

Note that if you don't specify the selector explicitly, it defaults to requiring matches on all the labels in the Pod template.

**Comment by kow3ns** [comment]
@cartmanume Is there any chance that you could post the following please?
1. The statefulset selector specification
1. The pods labels prior to the edit
1. The pods labels after the edit

**Comment by cartmanume** [comment]
Thanks for the quick support everyone. @enisoc pointed me to the solution, I was not aware of the selector in the StatefulSet, maybe too lazy to read the whole docs...
