### ISSUE TITLE
Master configs should be similar across kubemark and real cluster

### ISSUE THREAD

**Issue by shyamjvs** [kubernetes/kubernetes#53021]
There are a few flags that are mismatching/missing across both setups. A notable e.g is audit-logging was not turned on for kubemark, but was for real cluster which didn't allow us to catch a serious scalability regression on kubemark (ref: https://github.com/kubernetes/kubernetes/issues/51899). Few other differences:
- admission plugins
- feature gates
- request timeout
- etcd-quorum-read
...

We need to fix this.

cc @kubernetes/sig-scalability-misc @gmarek @wojtek-t

**Comment by smarterclayton** [comment]
You don't have etcd quorum read on?

Oh dear...

**Comment by gmarek** [comment]
We don't have etcd quorum read on?! I can only quote Clayton: Oh dear...

**Comment by gmarek** [comment]
OK - I asked @mborsz about that and in HA cluster we do enable quorum reads.

**Comment by shyamjvs** [comment]
We seem to have etcd quorum reads turned off by default for real cluster (i.e. in [config-test.sh](https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/config-test.sh#L91)) - and for kubemark we're not specifying the flag (which fwiu also defaults to false). So at least they're the same.

@smarterclayton Should I change the default to true for both? Also given that we're using single etcd instance for our tests - how much does turning it on actually matter?

**Comment by shyamjvs** [comment]
Btw - I can't find any non-gke jobs on our CI which have `ENABLE_ETCD_QUORUM_READ=true`.

**Comment by gmarek** [comment]
Quorum read in single-master setups doesn't change anything (as there's no quorum).

**Comment by smarterclayton** [comment]
Not true - it changes how etcd responds to certain errors and failure
modes.  Etcd can lose quorum with a single member because the logic is the
same.  We found a lot of subtle changes between quorum mode and non-quorum
mode, most of which weren't impactful, but still matter.  I don't think you
can get stale reads, but it's not a zero impact.

I thought that kubeadm always set it to true but can't see it doing it now
if it's not in HA.

Just keep in mind that turning it on changes how the cluster works even in
single master mode.

**Comment by wojtek-t** [comment]
> Just keep in mind that turning it on changes how the cluster works even in
single master mode.

Interesting. I didn't know about it - I've always thought it only affects clustered etcd.
