### ISSUE TITLE
Suspicious retry logic in azure_blobDiskController

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#53052]
I was looking for examples of our exponential backoff usage, and found some suspicious code.

wait.ExponentialBackoff exits immediately if `err != nil || ok`
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/util/wait/wait.go#L203-L205

```
		if ok, err := condition(); err != nil || ok {
			return err
		}
```

But in this loop, we always return `err != nil` || `ok`, so we will never retry.

https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/azure/azure_blobDiskController.go#L469-L484

```
		err = kwait.ExponentialBackoff(defaultBackOff, func() (bool, error) {
			_, provisionState, err := c.getStorageAccountState(storageAccountName)

			if err != nil {
				glog.V(4).Infof("azureDisk - GetStorageAccount:%s err %s", storageAccountName, err.Error())
				return false, err
			}

			if provisionState == storage.Succeeded {
				return true, nil
			}

			glog.V(4).Infof("azureDisk - GetStorageAccount:%s not ready yet", storageAccountName)
			// leave it for next loop/sync loop
			return false, fmt.Errorf("azureDisk - Account %s has not been flagged Succeeded by ARM", storageAccountName)
		})
```

**Comment by itowlson** [comment]
That does look suspicious.  What's the expected return of a retryable function (ConditionFunc)?  `(true, nil)` for 'succeeded', `(false, err)` for 'fatal error, do not retry' and `(false, nil)` for 'retryable error, let the retry policy decide whether to try again' (and it's up to the retryable function to log such errors as it encounters them rather than propagating the last error to its caller)?  (Forgive me if this is a newbie question, I am... a newbie.)

**Comment by justinsb** [comment]
Your description sounds right.  The pattern seems to be to log the error in the `false,nil` case.   Some other callers seem to stash the error for future use, but most simply return timeout on a timeout (not the "real" error, hence the need to log it).   It's a pretty caller hostile API, IMO :-)
