### ISSUE TITLE
[downgrade test failure] SchedulerPredicates [Serial] validates resource limits of pods that are allowed to run [Conformance]

### ISSUE THREAD

**Issue by ericchiang** [kubernetes/kubernetes#53066]
cc @kubernetes/sig-scheduling-test-failures 
cc @kubernetes/kubernetes-release-managers 

Seeing a failure on our downgrade test. Can someone please look at this?

https://k8s-testgrid.appspot.com/release-1.8-upgrade-skew#gke-1.8-1.7-downgrade-cluster

Example failure https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-gci-stable1-gci-stable2-downgrade-cluster/20#k8sio-schedulerpredicates-serial-validates-resource-limits-of-pods-that-are-allowed-to-run-conformance

Seeing timeouts on the downgrade test

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scheduling/predicates.go:222
Expected error:
    <*errors.errorString | 0xc4220f8090>: {
        s: "Error waiting for 8 pods to be running - probably a timeout: Timeout while waiting for pods with labels \"startPodsID=52f7cbb2-a2cb-11e7-b977-0a580a3c16f7\" to be running",
    }
    Error waiting for 8 pods to be running - probably a timeout: Timeout while waiting for pods with labels "startPodsID=52f7cbb2-a2cb-11e7-b977-0a580a3c16f7" to be running
not to have occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scheduling/predicates.go:208
```

**Comment by ericchiang** [comment]
Since we're so late in the release process and this is the first time we're seeing this fail, going to mark as non-release-blocking for now.

**Comment by spiffxp** [comment]
It fails in more places than just the downgrade job, but when the downgrade job fails that test, that timeout appears to be the consistent error that it fails with
https://storage.googleapis.com/k8s-gubernator/triage/index.html?test=validates%20resource%20limits%20of%20pods%20that%20are%20allowed%20to%20run

**Comment by bsalamat** [comment]
/assign

I looked at the logs. The test creates a few pods to saturate the existing nodes and then creates an additional pod and ensures that this last pod stays pending. The problem we observe is that those saturating pods are often not scheduled, causing a test timeout. Those pods use all the resources on the nodes. So, any small changes to the amount of available node resources or even rounding errors could cause those saturating pods to not schedule. I will test this theory by cutting down the amount of resources that the saturating pods use, but I would like to check if the problem is fixed before submitting the PR. Where can I get the steps these cluster downgrade tests take?

**Comment by ericchiang** [comment]
> Where can I get the steps these cluster downgrade tests take?

The test setups are in the test-infra repo. E.g. https://github.com/kubernetes/test-infra/pull/4659

**Comment by mml** [comment]
@bsalamat see my analysis in #53216.
