### ISSUE TITLE
'kube-up.sh' should allow user to customize the manifests of the cluster

### ISSUE THREAD

**Issue by ccll** [kubernetes/kubernetes#53133]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:

I'm trying to add '--runtime-config=batch/v2alpha1=true' (for CronJob) to the startup command of kube-apiserver.manifest, but the manifest file always reset to original content after reboot. After some digging I found out that GCE VM nodes created with 'kube-up.sh' always completely re-install k8s binaries and manifests on each boot. Is there anyway I can customize the manifests on a 'kube-up.sh' cluster?

**What you expected to happen**:

I expect that 'kube-up.sh' (or configure-helper.sh) provide a way to allow the user make persistent changes to the manifests.

**How to reproduce it (as minimally and precisely as possible)**:

1. 'kube-up.sh' to bootstrap a cluster on GCE.
2. 'ssh' into kube-master, make some changes to '/etc/kubernetes/manifests/kube-apiserver.manifest'.
3. Reboot kube-master, and the manifest is reset.

**Comment by ccll** [comment]
@kubernetes/sig-cluster-lifecycle-feature-requests

**Comment by luxas** [comment]
kube-up has been deprecated for a while, you should not use it for new clusters unless you really have to.
Can you maybe use [kubeadm](https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/) instead, which supports this feature?

cc @roberthbailey

**Comment by luxas** [comment]
But generally, should kube up add this functionality anymore?

**Comment by roberthbailey** [comment]
kube-up is already really flexible (since we've historically used it to e2e test new features) so much of the configurability is already there, just really difficult to discover and use. 

We've been only adding new features to kube-up to enable testing and aren't planning to take feature requests for general functionality improvements. But since most new features require testing, the side effect of the first half of that statement is that you can generally get them from clusters created by kube-up if you know what variables to set....

**Comment by ccll** [comment]
@roberthbailey Thanks! I'll try `RUNTIME_CONFIG` and `kubeadm`.
Closing now.
