### ISSUE TITLE
[downgrade tests] cluster downgrade should maintain a functioning cluster

### ISSUE THREAD

**Issue by ericchiang** [kubernetes/kubernetes#53145]
/kind bug

One of our downgrade test started failing last evening https://k8s-testgrid.appspot.com/release-1.8-upgrade-skew#gke-1.8-1.7-downgrade-cluster-parallel

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/cluster_upgrade.go:149
Expected error:
    <*url.Error | 0xc420dcced0>: {
        Op: "Get",
        URL: "https://104.154.223.144/api/v1/namespaces/e2e-tests-hpa-upgrade-8cvv5/replicationcontrollers/res-cons-upgrade",
        Err: {
            Op: "dial",
            Net: "tcp",
            Source: nil,
            Addr: {
                IP: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 255, 255, 104, 154, 223, 144],
                Port: 443,
                Zone: "",
            },
            Err: {
                Syscall: "getsockopt",
                Err: 0x6f,
            },
        },
    }
    Get https://104.154.223.144/api/v1/namespaces/e2e-tests-hpa-upgrade-8cvv5/replicationcontrollers/res-cons-upgrade: dial tcp 104.154.223.144:443: getsockopt: connection refused
not to have occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/common/autoscaling_utils.go:320
```

cc @kubernetes/kubernetes-release-managers 
cc @kubernetes/test-infra-maintainers 
cc @kubernetes/sig-cluster-lifecycle-test-failures

**Comment by ericchiang** [comment]
This passed on the latest running. Considering this a flake a non-release blocking.

**Comment by DirectXMan12** [comment]
unless I'm misreading that issue, it looks like the test failed because the code that sends signals to (and waits for) the ResourceConsumer failed to be able to contact the master properly.  While I can't see the controller manager logs for make sure that nothing went wrong there, it doesn't actually look like this is the fault of the HPA, or the HPA test.

Looks like the failure was post-upgrade, checking to see if the HPA had scaled up to 3 replicas, we failed to contact the master.  Looks like another test around that point failed for the same reason.

**Comment by ericchiang** [comment]
Any action we want to take here? cc @kubernetes/sig-autoscaling-test-failures 

I believe these downgrade test will still be used for future point releases of 1.8

**Comment by DirectXMan12** [comment]
I don't think there's any action we need to take, unless this shows up again.  It doesn't look like anything's wrong from the HPA side, as far as I can tell.

**Comment by ericchiang** [comment]
Works for me.

/close
