### ISSUE TITLE
No Ability to Skip Certain Upgrade Tests

### ISSUE THREAD

**Issue by jessicaochen** [kubernetes/kubernetes#53213]
There is no way to choose to skip certain upgrade tests as they are [hardcoded](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/lifecycle/cluster_upgrade.go#L42). This is problematic when some of the upgrade tests make assumptions that may not apply to a setup (eg. StorageClass, heapster, cloud provider). 

/kind bug

**Comment by luxas** [comment]
cc @kubernetes/sig-cluster-lifecycle-bugs @kubernetes/sig-testing-bugs @krousey

**Comment by krousey** [comment]
This is an unfortunate side effect of how the upgrade tests had to be written. Because of the way Ginkgo's test runner works, the upgrade tests had to be written as a single Ginkgo test case to allow for the level of coordination needed. The fact that they show up as separate rows is only because the upgrade framework writes out its own JUnit files. This means that Ginkgo focus and skip flags don't know about and cannot target the upgrade tests. If we used Golang's standard testing library, we could have the coordination we need and run the individual upgrade tests as subtests (Go 1.7). The `-run` flag can target subtests. But we'd have to re-write a lot to not depend on Ginkgo or Gomega. Another option is to add skip and focus flags solely for these tests.

But also, it seems like these tests should check their assumptions and skip if they are not met. A lot of tests do this already, and those mechanisms should work just as well for upgrade tests.

**Comment by luxas** [comment]
This is still relevant. cc @kubernetes/sig-cluster-lifecycle-bugs @kubernetes/sig-testing-bugs 
/lifecycle frozen

**Comment by timothysc** [comment]
@stevekuznetsov @BenTheElder - Is there anyone on test-infra side looking at this?  From what I saw it was totally a test-infra issue.

**Comment by BenTheElder** [comment]
No? This is a bug in the test framework, not the infra.

**Comment by neolit123** [comment]
/sig cloud-provider
/area provider/gcp
/remove-sig cluster-lifecycle

i don't think we are running these upgrade tests in CI anymore, or at least not in release blocking.
/remove lifecycle-frozen
