### ISSUE TITLE
Promote alternate API representations to beta

### ISSUE THREAD

**Issue by ironcladlou** [kubernetes/kubernetes#53224]
This is to track a discussion around promoting alternate API resource representations (https://github.com/kubernetes/kubernetes/pull/33900, https://github.com/kubernetes/community/pull/123) to beta. More specifically, the `PartialObjectMetadata` type via `Accept` header media type parameters is important for:

* Garbage collector optimization (https://github.com/kubernetes/kubernetes/issues/49718, https://github.com/kubernetes/kubernetes/issues/30180)
* Efficient object count quota support (https://trello.com/c/ayBfZlz8, Kubernetes issue forthcoming)

It's not entirely clear to me if there's a single PR, issue, or commit to reference in service of the promotion, so I've collected a list of what I think are relevant historical links:

* https://github.com/kubernetes/kubernetes/pull/44685
* https://github.com/kubernetes/community/pull/363
* https://github.com/kubernetes/kubernetes/commit/f203e42cb98ed4bac7ad8ebbed717d3bd42f55b6
* https://github.com/kubernetes/kubernetes/pull/40848

/kind feature
@kubernetes/sig-api-machinery-feature-requests

**Comment by smarterclayton** [comment]
I need to get the proposal cleared.

Right now we have two alpha features in place that leverage it (but are not consumed externally):

1. Server side get (Table) which was continued but not completed in 1.8
2. PartialObjectMetadata, intended for garbage collector.

The outstanding negotiation issue was raised in the proposal was "familiar name" mime types like `application/json+meta.k8s.io+v1+table` which would have to be preregistered in order to avoid collisions, while using the content type variant options (`v=v1`) for other newer fields.

**Comment by mbohlool** [comment]
cc @mml

**Comment by errordeveloper** [comment]
```
/lifecycle frozen
```

**Comment by smarterclayton** [comment]
Slated as part of 1.10 under moving server GET to beta.
