### ISSUE TITLE
Better handling of device plugin resource deletion

### ISSUE THREAD

**Issue by jiayingz** [kubernetes/kubernetes#53395]
/kind feature

Spun off from https://github.com/kubernetes/kubernetes/issues/53342, there was a regression introduced by device plugin change in 1.8 that we might remove opaque integer resource or non-device extended resources. We fix this problem in 1.8 by never removing any extended resources from kubelet node status and requires cluster admins to manually remove extended resources exposed via device plugins when they remove plugins. This issue is to track better handling of device plugin resource removal after 1.8 so that we can better manage device plugin resource life cycle.

As @ConnorDoyle summarized in https://github.com/kubernetes/kubernetes/issues/53342, there are a few options to solve this:

Option 1: With the assumption that ContainerManager owns the full control of the resources listed in its GetCapacity(), track resource deletion in ContainerManager and mark it in the returning data structure of GetCapacity() by either explicitly introducing a new state field for each resource type or implicitly from special quantity value of a resource (e.g., -1).

Option 2: Introduce some naming convention for device plugin resources. This will simplify device plugin resource lifecycle management, but will probably require broader discussions.

Other than distinguishing device plugin resources from other extended resources, we also need to avoid temporary capacity drop for device plugin resources after kubelet restarts. Otherwise, Pods restarted at that time gap window would fail and it is a regression from using device plugin to manage a resource compared to the native resource management by Kubelet (e.g., gpu resource currently managed by GpuManager). Possible options to solve this:
Option 1: Tracks a grace period after Kubelet restart and avoid updating device plugin resource capacity during grace period.
Option 2: Wait for some time period during ContainerManager Start() for device plugins to re-register.

**Comment by vishh** [comment]
My recommendation is as follows for device plugin lifecycle management:

1. Kubelet checkpoints resource name to device plugin mapping on first registration
2. Kubelet on startup waits for registered device plugins to re-register for some (possibly configurable?) time and if they don't kubelet taints that node to prevent new pods from being scheduled to the node. A cluster admin is expected to step in and fix the node.
3. If device plugins registers with kubelet within a timeout duration, then kubelet proceeds with normal operation. 
4. During runtime, if a device plugin drops out and fails to re-register within a timeout duration, then again the kubelet taints the node. A cluster admin is expected to step in and fix the node. Running pods are not affected.
5. If a cluster admin wants to remove a device plugin, then they have to cordon and drain the node, and then remove the plugin from that node (using node anti-affinity for example). 

Now this approach is not ideal for a Day 0 scenario where an admin may want to deploy and remove device plugins dynamically. My argument is that such a Day 0 workflow is very risky in production.
If kubelet were to remove an extended resource from Node Status because a device plugin failed to re-register within a timeout, then the existing pods are consuming a resource that's not even on the node. The health check guarantees that kubelet provides are off the table. 
An alternative is to evict such pods. But evictions are disruptive and users will be very unhappy about it. Device plugins are expected to be robust and reliable.
Another important thing to consider is that Node health issues are expected to be expressed via Node Conditions and Node Taints (future). If kubelet were to dynamically remove an extended resource due to device plugin unavailability, this event can be marked by a kubernetes event and/or monitoring signals. I don't think it's ideal to expect our current users to monitor events and kubelet metrics to track health issues. This to me is not a good production experience. 

My take is that it is better to fail obviously and have simple error handling logic in production.

Thoughts?

cc @derekwaynecarr @dchen1107 @jiayingz @ConnorDoyle @jeremyeder kindly post your thoughts. 
We need to make a decision and fix the logic in kubelet in v1.9

**Comment by jiayingz** [comment]
Thanks a lot for the recommendation, @vishh !

My major concern for this approach is that tainting a node just because some checkpointed device plugin fails to re-register within timeout after kubelet restarts, or disappears for various reasons may be too aggressive, given that device plugin may be used to manage various kinds of devices and some of them may not be that critical.

**Comment by derekwaynecarr** [comment]
@vishh -- this is complicated.  can we discuss this in resource mgmt wg call?

**Comment by dchen1107** [comment]
+1 on discussing this at tomorrow's resource mgmt.

**Comment by vishh** [comment]
SGTM.

**Comment by dchen1107** [comment]
RE: https://github.com/kubernetes/kubernetes/issues/53395#issuecomment-334879265

@vishh your proposal was made based on an assumption:  The node was not sharable with other workloads which doesn't requires such device, for example, GPU. Otherwise, if a given cluster does not only lost GPU resource, but also lost CPU & Memory & Disk etc. capacity too.

**Comment by derekwaynecarr** [comment]
in my perspective, if any device on a node reported unhealthy, we would most likely immediately mark the node as unschedulable, and look to deprovision and provision a new node.

**Comment by jiayingz** [comment]
A quick summary from an offline discussion among @vishh @mindprince and me.

We feel even though the most desirable operation to recover unhealthy device plugin is probably to mark the node as unschedulable, the decision and its implementation should probably leave out of Kubelet or device plugin. That means we will need some extra component to watch for device plugin resource health and performs proper recovery mechanism. This brings extra requirement to complete the device plugin resource lifecycle management and the response time may also be too long to limit the damage caused by single device/device-plugin failure.

Dropping resource capacity to zero upon device plugin re-registration failure could prevent future pods from being scheduled on the node. This approach is also more consistent with how we handle unhealthy devices which are currently excluded from resource capacity. One potential problem with this approach is that we don't want pods that are already scheduled on the node to fail to restart upon device plugin registration failure. We have discussed a few possible solutions to this problem. First, we have planned to move device plugin resource allocation to the admission phase (An issue is already opened for this feature: #51592). We could cache device runtime information and also add it to device plugin checkpoint to avoid calling device plugin Allocate even after kubelet restart. There is still a remaining problem. Currently because we run General Predicate during pod admission, the pod would fail with insufficient resource error if we drop capacity to zero. One possible solution to this problem is to set resource capacity as max of in-use capacity and successfully registered capacity, i.e., we gradually reduce device plugin resource capacity. The other discussed approach is to modify scheduler predicate to not fail with insufficient resource error for extended resources if pod has already been scheduled on the node.

**Comment by jiayingz** [comment]
Here is our current plan for 1.9 after an offline discussion between @vishh and me.

Upon device plugin failure (i.e., disappears for some reason or fails to re-register after kubelet restarts), kubelet will remove its registered resource from its capacity. This will prevent future pods from being scheduled on the node. It also gives a good monitoring signal that we may use to surface device plugin failures. Because we can't clearly identify a resource managed by device plugin from its naming, we will need to extend device plugin checkpoint to include any registered device plugin resources.

To solve the problem that pods that are already scheduled on the node wouldn't fail to restart upon device plugin failure, we will do two things. First, we will cache and checkpoint device runtime information to avoid calling device plugin Allocate for devices already allocated to a Pod. Second, we will expose a PluginResourceUpdater from ContainerManager and pass it to lifecycle.NewPredicateAdmitHandler(). predicateAdmitHandler calls this function after it gets nodeInfo and before calling GeneralPredicates. In PluginResourceUpdater, we use the cached device allocation information to update NodeInfo.allocatableResource to at least equal to in-use capacity.

**Comment by resouer** [comment]
@jiayingz Sorry, a stupid question. Do we already have checkpoint design/implementation for device runtime information in kubelet?

**Comment by lichuqiang** [comment]
@resouer You can take a look at comments in #51895

**Comment by resouer** [comment]
Found it here: https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/cm/device_plugin_handler.go#L254 thanks!

**Comment by resouer** [comment]
That's why I'm asking, checkpoint logic should be extracted: https://github.com/kubernetes/kubernetes/pull/54085

**Comment by ddysher** [comment]
@jiayingz Thanks for the detailed post.

Do you have any attack plan for the extra component? This sounds like within the scope of node problem detector.
> That means we will need some extra component to watch for device plugin resource health and performs proper recovery mechanism.

How do we measure `response time` here?  Is it the latency for the component to observe the unhealthy device, or the interval for cluster admin to take action?
> This brings extra requirement to complete the device plugin resource lifecycle management and the response time may also be too long to limit the damage caused by single device/device-plugin failure.

My take is that 'capacity=0' is used as a signal for re-registration failure, so what about the case where plugin is healthy but there is just no device? Is there semantic conflict between the two cases?
> Dropping resource capacity to zero upon device plugin re-registration failure could prevent future pods from being scheduled on the node.

Another thought. Imagine the case where a node has one device and a pod is consuming it. The node is taken offline by cluster admin and the device is removed. Later when node comes up and kubelet uses checkpointed information to admin the pod, the pod is allowed to run but since no device exists, it keeps failing. However, the expectation of cluster admin might be to reschedule the pod.  Haven't diged device plugin detail so not sure if this is a valid scenario, but I expect the argument is that we don't want to complex the logic in kubernetes and require admin to deal with it?

**Comment by lichuqiang** [comment]
> My take is that 'capacity=0' is used as a signal for re-registration failure, so what about the case where plugin is healthy but there is just no device? Is there semantic conflict between the two cases?

I think we don't treat plugins with no devices as "healthy", @RenaudWasTaken has an idea, to remove plugins that does not report deivces after registration for a period of time

> Imagine the case where a node has one device and a pod is consuming it. The node is taken offline by cluster admin and the device is removed. Later when node comes up and kubelet uses checkpointed information to admin the pod, the pod is allowed to run but since no device exists, it keeps failing. However, the expectation of cluster admin might be to reschedule the pod

I  thought about this scene too, I'm afraid we need to  rely on admin to deal with it in current implementation.
Would love to hear opinion from @vishh and @jiayingz

**Comment by jiayingz** [comment]
@ddysher How we may implement the extra component to monitor device plugin resource health is still TBD. It is possible we may surface certain failure conditions through node problem detector, but we haven't actively investigate this yet. By "response time", I mean the failure recovery time. Device resource capacity is meant to be used with other signals (e.g., some signal to indicate the node actually has the physical resources) for monitoring purpose. That monitoring part is also outside of kubelet or device plugin.

For your described case, I think when node is taken offline, all pods scheduled on it are supposed to be rescheduled. I.e., there should be no active pods consuming devices and the checkpoint file should be empty. Or do I miss something?

**Comment by ddysher** [comment]
We've seen cases when node is offline but pod still exists on the node (I guess this is due to node not ready toleration).  The problem only occurs when node is not properly taken offline, if we use node drain, all pods will be evicted.

**Comment by jiayingz** [comment]
Our current suggestion is to drain node before any maintenance work. It would be great that we verify the possible upgrade/maintenance processes and document them during alpha phase.

**Comment by vishh** [comment]
This issue still does not capture upgrade story for device plugins. Capturing some possible options. The decisions made as part of this issue should be moved to a user guide @jiayingz 

1. Until device plugin API goes GA, device plugin themselves have support for multiple device plugin API versions. If registration fails for the newest version, it would try the previous known version. This would allow for decoupling device plugin version from kubelet versions.
2. Have kubelet expose it's own version as node labels - K8s deployments can then run multiple versions (daemonsets) of device plugins each with their own affinity towards one or more kubelet versions. 
3. Bundle device plugins as part of kubelet deployment bundle and upgrade them on the node while upgrading kubelet. With this option, the device plugins can either be run as a system daemon or via a DaemonSet with an image pull policy "never" where the assumption is the device plugin container image is versioned/controlled independent of the daemonsets themselves.

My suggestion would be to go with option `2` since it's more generic. Kubelet will have to expose appropriate node labels as described [here](https://github.com/kubernetes/kubernetes/pull/51006#issuecomment-346471305)

@jiayingz @RenaudWasTaken @nqn being one of the developers for device plugins, can one of you ensure that we publish user guides for consuming device plugins in v1.9?

**Comment by jiayingz** [comment]
I think this issue is specific about how we want to handle/surface device plugin resource removal. We probably want to have a separate discussion on how to handle the device plugin upgrade.

**Comment by jiayingz** [comment]
/close
The issue should be resolved with https://github.com/kubernetes/kubernetes/pull/54488 and https://github.com/kubernetes/kubernetes/pull/55088

**Comment by singlecheeze** [comment]
https://github.com/NVIDIA/k8s-device-plugin/issues/240#issuecomment-1327867768
