### ISSUE TITLE
Failed to access NodePort if kube-proxy running in ipvs mode

### ISSUE THREAD

**Issue by song-jiang** [kubernetes/kubernetes#53393]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
Failed to access a remote NodePort.

**How to reproduce it (as minimally and precisely as possible)**:
- Create a cluster with three nodes (node A,B,C). Network plugin is calico.
- Create a pod on node C and expose it as a NodePort service.
- Node A tries to access NotePort with ip:port where ip is the ip address of node B.
Remote node (node A) -> node ip:port (node B) -> remote pod (node C)

**Anything else we need to know?**:
It seems missing masquerade rule on node B. I can see pod receives packet with source ip of node A.

/sig network
/area kube-proxy

**Environment**:
- Kubernetes version (use `kubectl version`): 1.8.0
- Calico version: 2.6
- OS (e.g. from /etc/os-release): CoreOS 1465.8.0
- Kernel (e.g. `uname -a`): 4.12.14
- Install tools:
- Others:

**Comment by m1093782566** [comment]
Thanks for reporting it, @song-jiang 

Did you access NodePort inside container or outside container?

**Comment by m1093782566** [comment]
> It seems missing masquerade rule on node B. I can see pod receives packet with source ip of node A.

Seems you are right. My worry is that we may introduce too many iptables rules if we use the iptables way.

**Comment by song-jiang** [comment]
@m1093782566 I have seen this issue if access NodePort from a container or from a host.  How about having an ipset tracking all the entries from ipvs kernel table and match against that? WDYT

**Comment by m1093782566** [comment]
It works for me if I access NodePort from a host - seems strange...

**Comment by m1093782566** [comment]
> How about having an ipset tracking all the entries from ipvs kernel table and match against that? WDYT

ipset seems workable and I feel like somebody else has discuss with me about it for a few times. For now, I will try the iptables way to fix the bug and then to see if migrate iptables to ipset can bring some benefits especially performance.

**Comment by fasaxc** [comment]
@m1093782566, @song-jiang pointed out to me that kube-proxy is still maintaining an iptables table with a list of service IPs in it in order to set the masquerade flag correctly.  A `hash:ip,port` IP set would efficiently solve that problem (and remove the need to update iptables for each service), and, if the node ports and service IPs were all included, it should cover all the bases.

I.e., you'd add the `<ip>:<port>` of each service/node port to a KUBE-SERVICE `hash:ip,port` IP set, then you'd only need a single static iptables rule to match packets against all services.

Updating an IP set is much more efficient than updating iptables because the kernel protocol uses deltas instead of a read-modify-write of the whole table (as for iptables).

**Comment by song-jiang** [comment]
What kind of network plugin you are using? Maybe it got some encapsulation or SNAT rules already in your case?

**Comment by m1093782566** [comment]
> What kind of network plugin you are using? 

Calico.

**Comment by m1093782566** [comment]
> I.e., you'd add the <ip>:<port> of each service/node port to a KUBE-SERVICE hash:ip,port IP set, then you'd only need a single static iptables rule to match packets against all services.

> Updating an IP set is much more efficient than updating iptables because the kernel protocol uses deltas instead of a read-modify-write of the whole table (as for iptables).

Sounds great!

**Comment by song-jiang** [comment]
@fasaxc and I are core developers of project calico. We are in the process of adding ipvs support for the project. I think you may have calico running in IPinIP mode so it does an encapsulations for you.

**Comment by fasaxc** [comment]
Just in case it wasn't clear where this came from, @song-jiang and I are core developers on Calico and we're working on adding support to Calico for IPVS since currently IPVS bypasses Calico's security policy.

> Do you mean

@m1093782566 Yes, that's the sort of rule.  In Calico, that rule is only enabled when IPIP mode is turned on.  Normally, Calico (deliberately) avoids adding SNAT to the datapath but that IPIP rule is a special case workaround.  We'd like kube-proxy's rules to be self contained so that it doesn't rely on Calico (or flannel) for SNAT.  I think that's already the case on some datapaths but node ports weren't covered by the existing rules.

**Comment by m1093782566** [comment]
MAKE SENSE, I am trying ipset now. Will let you know if I have some updates.

**Comment by fasaxc** [comment]
@cmluciano I'm not familiar enough with that mode to know.  Calico only works with iptables mode  (until our IPVS compatibility changes are merged) so that's what we test with.

**Comment by Lion-Wei** [comment]
@song-jiang Have you use iptables mode tested this situation? Cause I use iptables mode, try to use nodeB ip access pod in nodeC, and never successed...
I am using kubeadm cluster, with 3 node, calico 2.6.2, kubernetes in 1.8.2.
Maybe there is something wrong with my cluster, but I am not sure, so if iptables works well in your situation, please let me know, thanks...

**Comment by song-jiang** [comment]
@Lion-Wei iptables mode works for me. I am running calico 2.6.2, k8s 1.8.2 but with vagrant/coreos on three nodes. Can you check if iptables mode works on other access patterns to be sure it is not a  setup issue?

**Comment by song-jiang** [comment]
@Lion-Wei I think the root cause of this issue is with iptable mode, each NodePort gets a masquerade rule, for instance 
`-A KUBE-NODEPORTS -p tcp -m comment --comment "policy-demo/nginx:" -m tcp --dport 32712 -j KUBE-MARK-MASQ`

This is similar to each local pod gets a masquerade rule to support hairpin access, for instance
`-A KUBE-SEP-4F3IDBRE6Z6F7Y23 -s 192.168.44.194/32 -m comment --comment "policy-demo/nginx:" -j KUBE-MARK-MASQ`

WIth ipvs mode, those rules do not exist. I think @m1093782566 is going to fix node port and hairpin issue with ipsets.

**Comment by m1093782566** [comment]
@song-jiang Seems you are right.

I think both the hairpin mode and cross-node masquerade issue can be solved when the PR https://github.com/kubernetes/kubernetes/pull/54219 gets in. This PR is ready for review and any comments are welcome.

Thanks all!

**Comment by m1093782566** [comment]
Actually, I added some high level design details in the comments. People whom don't want to review codes can take a look at the design document.

**Comment by m1093782566** [comment]
cc @thockin

**Comment by m1093782566** [comment]
/area ipvs

@song-jiang the bug fix already goes in - at least it works for me. Would you please check the HEAD?

**Comment by song-jiang** [comment]
@m1093782566 Tested with HEAD, works as expected.
