### ISSUE TITLE
Pod lifetime based PersistentVolumeClaim

### ISSUE THREAD

**Issue by anlu** [kubernetes/kubernetes#53407]
/kind feature
/sig storage
@kubernetes/sig-storage

It would be useful to have a PersistentVolumeClaim that is tied to the lifetime of a pod. We currently have a use case where we have a data export type job that dumps a significant amount of data to disk. However, the data is ultimately sent to other locations, and so once the job is complete, we do not need the EBS volume to persist anymore.

The underlying idea is to be able to specify for a pod n GBs of disk, just like you CPU / memory, without having to worry about external operator cleanup of this state. The overlay filesystem is meant to solve this problem, but unfortunately it's restricted to the underlying node's disk size (and potentially problematic if two disk heavy containers get scheduled onto the same node).

I'm happy to work on this feature if someone can point me in the right direction!

**Comment by anlu** [comment]
/sig storage
@kubernetes/sig-storage

**Comment by msau42** [comment]
@kubernetes/sig-storage-feature-requests 

In 1.8, we added the ability to specify size limits on EmptyDir volumes in order to provide capacity isolation.  But like you mentioned, it's possible that you need more space than the root filesystem has available.  An idea of "inline PVs" was briefly mentioned [here](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/storage/local-storage-overview.md), but no work or investigation has been done with this.
