### ISSUE TITLE
[Proposal] Make scalability tests part of conformance suite

### ISSUE THREAD

**Issue by shyamjvs** [kubernetes/kubernetes#53600]
One of the key characteristics of kubernetes is its performance at scale. We (sig-scalability) are load-testing clusters at a large scale and measuring the performance every release.
Starting from 1.6 we're "supporting" 5000-node k8s clusters (defined concretely as correctness and performance tests passing against them).
We should consider incorporating scalability as part of conformance too - as a distro which doesn't scale beyond a few tens of nodes isn't really conformant with ones which scale to hundreds of nodes.

Some options:
1. We're able to start/stop an X-node cluster on that distro, where X needs to be reported by the distro
2. In addition to 1, the X-node cluster also needs to pass our current set of conformance tests
3. In addition to 1, the X-node cluster also needs to pass our current set of performance tests (which as of now includes - load test (which checks api call latency SLO) and density test (which checks pod startup latency SLO)). Ref on SLOs - http://blog.kubernetes.io/2017/03/scalability-updates-in-kubernetes-1.6.html
4. Both 2 and 3 (which is what we're currently [doing](https://github.com/kubernetes/features/blob/master/release-1.8/scalability_validation_report.md) for our releases)
5. Run performance tests on an X-node kubemark cluster (which would be much less resource-intensive than an X-node real cluster, but will not validate few things on the node side)
6. ...?
7. Not include scalability at all

Opening this issue for discussion/suggestions.

cc @kubernetes/sig-scalability-misc @wojtek-t @gmarek @jagosan

**Comment by shyamjvs** [comment]
fyi - @wasylkowski @ignacyk

**Comment by jagosan** [comment]
I agree strongly that there is a user expectation of some reasonable level of performance. I raised this in an early brainstorming / discussion [doc on conformance](https://docs.google.com/document/d/17y8Jw8Jd7HWME-ruQYKDtajJjh54uulhcvqkjLKlBxs/edit#heading=h.a3yw62lth2gs). There was general consensus on the core concept, but concern around the implementation and the ability to test rigorously. See the section at the end of that doc, where performance was agreed to be out of scope for initial launch. That said, I am very much in favor of establishing at least a low bar for performance, violation of which would indicate that the cluster is virtually unusable. From there, we can establish a stronger position over time and allow participants to both collaborate on the metrics and have time to prepare and confirm their offerings. 

@WilliamDenniss FYI

**Comment by shyamjvs** [comment]
Sgtm. Let's begin with a bar of 100-node cluster (with load and density tests passing on it)? - which is the lowest scale at which we're scale-testing as of today.
Could you provide some pointers on what all to do in order to add them to the conformance suite?

**Comment by jeremyeder** [comment]
@sjug @mbruzek

**Comment by countspongebob** [comment]
Just a note of caution here. Note that I say this with continued deep interest in kubernetes scaling. 

Do we really want to combine this kind of scaling tests for certification? For example, a small embedded appliance approach ought to be able to scale appropriate to the the target market, and as long as it passes functional certification requiring a general purpose scale up seems inappropriate.

Likewise I'd like to suggest to that a general purpose distro should support community-based best practices for control plane config per here:

https://github.com/kubernetes/community/blob/master/sig-scalability/provider-configs.md

...but I do that VERY cautiously as a system that can satisfy the scaling and ha needs of their market while remaining API compliant should, IMHO, get certification.

Scaling down to very efficient small systems is a worthwhile endeavor and I don't think we should withhold certification from such systems.

**Comment by countspongebob** [comment]
As an alternative, we could advocate for additional "badges" for certification for the general purpose large scale cluster setups at the 100/1000/5000 sizes.

**Comment by shyamjvs** [comment]
Makes sense. However (correct me if I got something wrong):

> For example, a small embedded appliance approach ought to be able to scale appropriate to the the target market

An embedded appliance has hardware limitations, and IIUC the conformance is for the k8s distro, which is at the software level. Using insufficient hardware for large scale tests would of course fail, but that shouldn't invalidate the scalability of the distro. So let me restate it more clearly as follows:

`Given a k8s distro and enough compute (and other) resources to support the scale, the k8s cluster should pass the performance tests`

> Likewise I'd like to suggest to that a general purpose distro should support community-based best practices for control plane config per here:

Different distros may need to tweak their parameters differently in order to make the tests pass (for e.g a distro with a custom replication-controller may have to increase worker-parallelism in order to create/delete pods within a reasonable timeframe, another distro with some extra addons running on the master may have to use a bigger VM, etc). IMO that should be fine, as long as the custom configuration is clearly stated as part of the conformance testing report. This will also help users of the distro know better about how to use it at scale. And the config stated in that doc can actually help different distros eliminate a lot of ambiguity wrt running the performance tests.

> As an alternative, we could advocate for additional "badges" for certification for the general purpose large scale cluster setups at the 100/1000/5000 sizes.

That sounds reasonable. However, I'm slightly inclined towards the other choice as badges sound more like an optional thing - which a distro may choose to skip (possibly knowing that there are performance issues with it). OTOH, if we really want to avoid not certifying some distros based on scale tests, we could make the conformance test report the number X instead of making a binary decision based on pass/fail on 100-node cluster.

**Comment by timothysc** [comment]
It's not in the purview of this sig-scale to decide this.  Only @kubernetes/sig-architecture-feature-requests has that power, and @kubernetes/sig-testing-feature-requests to enforce it.  

Right now the means of validation is not there, and we can not/should not add the [Conformance] unless there are non-flakey tests that the field can trust.

**Comment by countspongebob** [comment]
Agree about sig-scale's role in this as a decider. It is IMHO in the purview of SIG-scale to formulate a proposal to the relevant groups should there be energy people want to put into it, though. I will argue against it as useful per my points above as a general certification criteria.  As Tim points out -  the testing suites would need considerably further development so as a practical issue it's not manageable in the short term.

**Comment by wojtek-t** [comment]
I agree with the concerns about state of out tests. But maybe the first step is to actually say that "all the conformance correctness tests are also passing in large-enough clusters"?

> Do we really want to combine this kind of scaling tests for certification? For example, a small embedded appliance approach ought to be able to scale appropriate to the the target market, and as long as it passes functional certification requiring a general purpose scale up seems inappropriate.

That sounds like a very good point. OTOH, is this still a Kubernetes if it only scales to say 5 or 10 nodes? In my opinion not really - it's something like "small-scale Kubernetes", but that doesn't mean to me that it's Kubernetes.

I 100% agree that requiring 5000-node cluster support for certification is a "no-go". But in my opinion we should require some reasonable scale from really "Kubernetes-certified" solutions (I need to think more about what size of cluster would be reasonable in my opinion though).

Going back to @countspongebob point, yes I agree that scalability may not be required by some (potentially large) group of users. But there are still users that need it. And if we certify such distro as Kubernetes, and they decide to use it they may be disappointed later.

I don't have a good proposal to solve it though (the one thing that comes to mind which is having few levels of certification, e.g. "small-scale Kubernetes", "medium-scale Kubernetes", "Kubernetes", doesn't sound like a good option to me - it simply doesn't scale if we encounter more such dimensions.

And speaking about other dimensions - did we thought about other "not-feature-like" aspects of Kubernetes at all? Reliability is one thing that comes to my mind.
Imagine a patological scenario, where all master-components are crashlopping every 10s. Most of our tests are written in a way, that I believe they may still be passing in such scenario, assuming control plane will be able to make some progress (because they do retries, etc.). But is this really a Kubernetes distro? In my personal opinion not really.

I think that we should really start thinking about those not "purely-features-based" aspects of the system. Scalability appeared as a first such thing, but my personal feeling is that there may be more.

**Comment by shyamjvs** [comment]
> I think that we should really start thinking about those not "purely-features-based" aspects of the system. Scalability appeared as a first such thing, but my personal feeling is that there may be more.

Strongly agree :)

@countspongebob @timothysc Your arguments sound quite reasonable. Can we discuss this further (maybe in sig-architecture weekly?

**Comment by bgrant0607** [comment]
I am not in favor of a specific bar for non-functional attributes.

I am in favor of requiring vendors to inform users of the limitations.

**Comment by gmarek** [comment]
I somewhat disagree - I'm not sure we can depend on vendors to do exhaustive testing if they're not obliged to by the conformance. I may be too cynical, but I expect conformance tests, even though it's officially a minimal bar, will be close to maximal testing scenario of among vendors as well. Everything boils down to what user experience we want to guarantee.

**Comment by countspongebob** [comment]
I'm also not in favor. It ought to be possible to pass conformance testing on anything from a raspberry pi to gold plated enterprise super-servers which both ought to pass conformance, would be entirely appropriate to the use case and would have wildly different performance.

Related thought: I think the path here could be to have a standard benchmark that the vendor can publish the result of in a standard way. Are we too early for this kind of thinking?

**Comment by bgrant0607** [comment]
@countspongebob Yes, reporting benchmark results is along the lines of what I was thinking.

**Comment by wojtek-t** [comment]
I don't fully agree here. While I understand your concerns for non-functional attributes, if we explicitly exclude them from conformance noone will be thinking about them.

That said, I also see the point that some distribution is by design not targetted for e.g. large-scale usecases. And that is something we need to keep in mind.
But if we say that "you can publish benchmark results" I really doubt people will be doing that (maybe except from 2-3 biggest players), also due to costs. And if we claim that k8s supports 5k node clusters, and someone wants to prove that it just works on 10-node clusters, what incentive of doing it he/she has? In my opinion there is completely no incentive and people won't be doing that.


So I started thinking that maybe the solution would be to actually **require** some benchmark results, but not require any scale. How I would see that is:
- to be k8s-conformant, you **have to** publish  results of a benchmark that we have
- benchmark is designed in a way that can be run on cluster of any size X and returns results that confirm/reject scalability at such scale
- k8s provider can choose at what level he wants to be certified (e.g. it.s fine to be prove scalability only for 5-node clusters)

With this approach on one hand we won't impose too many limitations on providers (it's fine to not scale), but on the other hand we will be fair to our users because they will know at what scale the provider is "certified".

@bgrant0607 @countspongebob - WDYT?

**Comment by timothysc** [comment]
@wojtek-t this is worthy of a sig-discussion.  I'm a general NAK on [Conformance] , but a +1 to [Performance] suite @ X-scale.

**Comment by smarterclayton** [comment]
I would be willing to bet that 95% of all kubernetes clusters in the world
are smaller than 5 nodes.  Agree a sig discussion is in order.

I would be willing to say a distribution that takes 500ms to create a pod
is not conformant.  But I wouldn't be willing to say that a hosted service
that has a single control plane in the US with nodes in Europe is not
conformant because it takes 500ms for a pod to start running in Europe.

On Mon, Nov 27, 2017 at 5:55 PM, Timothy St. Clair <notifications@github.com

**Comment by wojtek-t** [comment]
+1 for sig-discussion (though, can we move it to the next one, I can't join this Thu)?

> I would be willing to bet that 95% of all kubernetes clusters in the world
are smaller than 5 nodes. 

Agree. That's why in https://github.com/kubernetes/kubernetes/issues/53600#issuecomment-343881220 I suggested that different distribution may decide that what scale the announce. And I think it's completely fine for a distribution to say that it supports 5 or 10 node clusters only. But I think we need we need to require from a distro to say something.

Regarding second part of Clayton`s comment, I'm fully open how exactly those tests should look like. I'm not going to claim that our current tests are exactly what we want, because I don't really think it's the case. But I think choosing how/what exactly we want to test is a separate issue, and we need to answer the more fundamental question "if" first.
[BTW - I think 50th % of startup time, is still above 500ms, but assuming a different number, I agree with the high level point].

**Comment by wasylkowski-a** [comment]
@wasylkowski-a

**Comment by timothysc** [comment]
closing, this is not deemed to fall into the conformance category.
