### ISSUE TITLE
After 1.8, scheduler could reject unknown extended resource names

### ISSUE THREAD

**Issue by jiayingz** [kubernetes/kubernetes#53616]
> /kind bug

**What happened**:
Not sure yet whether this should be considered as a regression or WAI.

Basically, with PR https://github.com/kubernetes/kubernetes/pull/48922, we introduced ExtendedResources that covers all resources outside the default kubernetes.io namespace. In scheduler PodFitsResources(), for every extended resource, we check whether the node has enough resource quantity for it. This introduced a behavior change for non OIR resources outside the default kubernetes.io namespace. I.e., before PR 48922, scheduler wouldn't reject them even if there was no actual resource advertised by the node, but after PR 48922, scheduler will reject them with InsufficientResourceError.

I am opening this issue to discuss whether this behavior change is ok. Please feel free to add any related folks to the discussion.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.8+
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by yguo0905** [comment]
https://github.com/kubernetes/kubernetes/issues/50658. Looks like this is the intended behavior going forward.

**Comment by ConnorDoyle** [comment]
I think this behavior is desirable, since it is consistent with what users already expect when requests for other resources are not satisfiable. Also, if matching resources are freed on a node or a new node appears with matching resources then the pod can be scheduled in a later iteration.

@jiayingz did you expect something else to happen? If so what are the alternatives?

**Comment by lichuqiang** [comment]
I've no idea. Scheduler could only check if the names of resources requested follow the _naming scheme_, but could not tell if corresponding resources exists indeed.
I'm afraid users have to know what they really want, and the resources they requested are "in legal".

**Comment by jiayingz** [comment]
My major concern is that before 1.8, people can implement a scheduler extender to manage some cluster-level resources that are not necessarily advertised on individual nodes, but now pods requesting such resources would be marked with InsufficientResourceError before even reaching the scheduler extender.

**Comment by ConnorDoyle** [comment]
Added this issue to the sig-scheduling agenda for Oct 12

**Comment by jiayingz** [comment]
A quick summary from today's sig-scheduling discussion. We feel we will need more discussions on how to better support cluster-level extended resources in longer term. It is ok to leave the 1.8 behavior as is given that there is no official way to support cluster-level extended resources in Kubernets as of now.

**Comment by ConnorDoyle** [comment]
@jiayingz do you want to keep this issue around to capture the interaction between scheduler extenders and extended resources? Otherwise we could roll this requirement into issues on cluster-level resources.

**Comment by jiayingz** [comment]
Thanks for reminding, @ConnorDoyle 
The issue probably fits into the requirements on how to better support cluster-level extended resources.
I guess we can keep it fresh for now before we have a concrete plan on how to solve the problem.
/remove-lifecycle stale

**Comment by yguo0905** [comment]
@vishh @jiayingz @bsalamat 

Discussions on how to support cluster level resources with scheduler extenders.

Currently, pods requesting the extended resources that are not managed/advertised by device plugins will not be scheduled. Cluster level resources are such resources. We need to teach kube-scheduler to understand these resources so that it can skip the checks in the `PodFitsResources` predicate.

Since cluster level resources are usually handled by scheduler extenders, we can change kube-scheduler configuration to support a mapping between resource name and the extender which handles that resource. Iff kube-scheduler sees a pod requesting resources that are manged by extender, it will (1) send the pod to the extender, and (2) skip checking the resources in the `PodFitsResources` predicate.

(1) is being done in https://github.com/kubernetes/kubernetes/pull/58851, while (2) is to be done.

**Comment by vishh** [comment]
@yguo0905 your summary matches my thoughts. Let me highlight the use case a bit more:

A user intends to expose cluster level resources. They start with running a scheduler extender which understands their new resource. Along the way they realize that the scheduler requires all resources, including cluster level ones, to be attached to a node (part of node capacity/allocatable). This then requires extenders to attach cluster level resources to nodes as part of scheduling which is not desirable.

The solution proposed in the [previous comment ](https://github.com/kubernetes/kubernetes/issues/53616#issuecomment-364581866) solves this problem by giving scheduler hints on cluster level resources which lets the scheduler not require all resources to be part of node capacity. 

We have an unrelated need for wanting the scheduler to not reach out to extenders unless a pod requests a resource that the extender exposes. This is meant to make extenders safe to use in large (or high churn) clusters. For this purpose, the extender configuration can include an optional list of resources that the extender supports. The scheduler can then reach out to the extender only when it processes a pod that specifies a resource supported by the extender. By default, the extender will be invoked for all pods, thereby preserving existing behavior.
This config change can also be used by the scheduler to track cluster level resources. For instance, if the extender config where to include additional metadata that classifies certain resources it supports as cluster level ones, scheduler can then stop expecting such resources to be tied to nodes.

This is only part of the story though since the node also performs feasibility checks and it also expects all compute resources to be available in node capacity/allocatable. For the purposes of supporting cluster level resources and enabling overall compute resource extensibility, the node needs to ignore extended resources that do not belong to any device plugins that are currently registered. There can be a scenario where a device plugin un-registered itself after a scheduler had placed a pod requesting a resource the plugin exposed. With the proposed model, kubelet may incorrectly admit the pod eventhough the device plugin expected to handle one of the resources the pod wants is missing. We consider this to be a known limitation of the system and the recommendation is to tie the health of the node to the availability and health of device plugins.
That is, a node is marked "unhealthy" and drops all incoming pods if a device plugin on that node fails.

**Comment by jiayingz** [comment]
Given that with https://github.com/kubernetes/kubernetes/pull/58851, the scheduler can know the scheduling for some specified resource can be delegated to certain scheduler extender, it seems reasonable to also use this information to bypass node capacity check for that resource in the general predicate. @bsalamat do you think this change is acceptable on the scheduler side?

On node side, I do have concerns on dropping the capacity check for any unknown extended resource and the requirement of tieing the health of the node to the availability of any device plugins that have run on the node. We have previously discussed whether we need to support dynamic life cycle of device plugin resource in https://github.com/kubernetes/kubernetes/issues/53395 and decided we should provide this support. I think dynamic resource life cycle is an important feature that will be needed by certain types of device plugins.

Instead of dropping the capacity check for any unknown extended resource on a node, can we explore some alternative solution to keep this check? E.g., is it possible for the scheduler extender to update node status capacity/allocatable to reflect the availability of the resource after it binds the resource on the node? I guess one problem with this approach is that there will be some propagation delay for the node status update to reach Kubelet and it is likely that Kubelet will see the pod update first before seeing the node status update. As I heard, local storage also has the similar problem and they solve it by waiting up to podAttachAndMountTimeout in WaitForAttachAndMount() during pod processing. Perhaps we can follow a similar approach for extended resource attaching?

**Comment by bsalamat** [comment]
As discussed with @vishh  and @yguo0905, scheduler extender config can be enhanced to receive a list of resources per extender that the extender cares about. Pods that request at least one of such resources are sent to the extender. The config can also tell scheduler whether scheduler should ignore these resources or not. Basically, each of such resources can have a flag to indicate this intention.

**Comment by jberkus** [comment]
adding priority to this so it can stay in 1.10.  Please update.

/priority important-soon

**Comment by jberkus** [comment]
is this issue on-track for 1.10 in 5 days?  If so, please add status/approved-for-milestone.  thanks!

**Comment by bsalamat** [comment]
@jiayingz is 1.10 still a valid target for this issue?

**Comment by jiayingz** [comment]
@vishh and @yguo0905 do you plan to target https://github.com/kubernetes/kubernetes/pull/59835 for 1.10? Do we also need to make a change on the scheduler side to use the extender config info?

**Comment by jberkus** [comment]
as a reminder, this issue will be automatically removed from 1.10 in 7 hours for Code Freeze, unless a sig lead adds status/approved-for-milestone to it.  Thanks!  @jiayingz @vishh
