### ISSUE TITLE
Not complete support for flags of Boolean type in kubectl plugins

### ISSUE THREAD

**Issue by ayaranga** [kubernetes/kubernetes#53640]
When invoking any plugin by kubectl, it exports the options specified in plugin YAML file as env vars. If there are any options that need to be designed as Boolean type, for example, if you want to have a Boolean type option "create-instance" then the plugin should always be invoked as follows:
```
kubectl plugin <plugin_name> --create-instance=true
``` 
instead of just 
```
kubectl plugin <plugin_name> --create-instance
```
You need to explicitly specify the value otherwise the env var values get messed up especially when you have multiple various type options.

**Comment by dixudx** [comment]
@ayaranga I don't think we should mark this as a bug. A feature should be okay, since only `string` is currently supported as `kubectl plugin` flags for default subcommand runner. Alternatively you can have your own command runner to handle this, please refer to [kubectl plugin aging](https://github.com/kubernetes/kubernetes/tree/master/pkg/kubectl/plugins/examples/aging) for an example.

@pwittrock FYI.

**Comment by ayaranga** [comment]
Currently as only string is supported as a kubectl plugin flag, I want to mark this as a feature request as suggested by @dixudx .
@kubernetes/sig-cli-feature-requests

**Comment by carolynvs** [comment]
@dixudx I am developing a plugin for Service Catalog and have run into this limitation as well. I don't quite understand your workaround though.

> Alternatively you can have your own command runner to handle this, please refer to kubectl plugin aging for an example.

I don't see where that aging plugin registers its own runner? How would we go about doing that?

For context, the plugin is a reguar go binary. I'd like to be able to support commands like `svcat --version` and when it's used as a plugin `kubectl plugin svcat --version`. 

Right now cobra in kubetl is configured to consume all of the os args. I've tried omitting version from my plugin manifest flags but then cobra complains about an unrecognized flag. When I do include it in the manifest, cobra complains that I didn't assign a value, for example `--version='true'`, since it is defined as a string flag.

I don't see how to accomplish a boolean flag for a plugin without changes to kubectl's code?

**Comment by dixudx** [comment]
> I don't see where that aging plugin registers its own runner? How would we go about doing that?

@carolynvs Please refer to [how-to-install-kubectl-plugins](https://kubernetes.io/docs/tasks/extend-kubectl/kubectl-plugins/#installing-kubectl-plugins). The runner will be called the command defined in the yaml file.

> since it is defined as a string flag

Right. Currently only string flag is supported by kubectl plugin.

> I don't see how to accomplish a boolean flag for a plugin without changes to kubectl's code?

Take below plugin yaml file as an example.

```
name: "svcat"                 # REQUIRED: the plugin command name, to be invoked under 'kubectl'
shortDesc: "svcat plugin"    # REQUIRED: the command short description, for help
longDesc: ""                      # the command long description, for help
example: ""                       # command example(s), for help
command: "./svcat"             # REQUIRED: the command, binary, or script to invoke when running the plugin
flags:                            # flags supported by the plugin
  - name: "version"                  # REQUIRED for each flag: flag name
    shorthand: "v"                # short version of the flag name
    desc: "version info"             # REQUIRED for each flag: flag description
    defValue: "false"           # default value of the flag
tree:                             # allows the declaration of subcommands
  - ...                           # subcommands support the same set of attributes
```

You can try to set a default value to false/true. And then parse these flag values in your own command scripts.

**Comment by carolynvs** [comment]
@dixudx I've tried what you suggested and I believe this is a limitation in how cobra works.

The default value for a flag is only used when the flag is omitted entirely. When the flag is present, but no value is specified, cobra considers the command invalid and prints help usage. A plugin doesn't get a chance to do its own parsing because cobra is consuming and validating all flags.

```console
$ kubectl plugin svcat --version
Error: flag needs an argument: --version

Available Commands:
... # truncated help text

$ kubectl plugin svcat --version=true
svcat v1.0.0
```

I'd be happy to help figure out how we could support boolean flags for kubectl plugins, if that would be a welcome contribution? For example, adding a plugin manifest field specifying that the flag is boolean. Or cobra's `DisableFlagParsing` would allow delegating flag parsing to the plugin, enabling a command like `kubectl -n my-ns plugin FOO --bar` where flags specified before FOO, like `-n`, would be parsed by kubectl, and flags after FOO, like `--bar`, could be passed on to the plugin.

**Comment by dixudx** [comment]
> I'd be happy to help figure out how we could support boolean flags for kubectl plugins, if that would be a welcome contribution?

@carolynvs Yeah, sounds great to me. I can help review it. Thanks so much for the contribution.

> For example, adding a plugin manifest field specifying that the flag is boolean.

SGTM.

**Comment by soltysh** [comment]
This is addressed with the new pluging mechanism from https://github.com/kubernetes/kubernetes/pull/66876.
/close
