### ISSUE TITLE
[RFC] kubernetes should have the ablility  upgrade safe.

### ISSUE THREAD

**Issue by netroby** [kubernetes/kubernetes#53773]
I installed kubernetes 1.7.3 last month, works well. then the kubernetes 1.8 released. I ran yum update(My system is CentOS x64). the kubernetes cluster failed to upgrade. after kube-* package upgrade. 
The cluster network not working. we can not access network (both in/out) 
And failed to find a solution.
We setup our cluster by kubeadm. 
We try to delete all node, and recreate kubernetes cluster . but still failed. the network not working.

There hardly to find out how to upgrade kubernetes from old version to latest version.
No enough test ,not enough document/guide. If we occures problems. no one knows how to resolve it. 
The system not clear to show us why the upgrade success or failed.

Kubernetes release quickly, but not test well. why not make more test for upgrade ?

**Comment by dixudx** [comment]
@netroby Here is a doc on [how to upgrade kubeadm clusters from 1.7 to 1.8](https://kubernetes.io/docs/tasks/administer-cluster/kubeadm-upgrade-1-8/).

If you're using other methods to provision your cluster, like what you mentioned above, a simpler and safe way is to directly modify related kube unit-files and binaries, instead of upgrading from the scratch.
