### ISSUE TITLE
Unable to connect to the server: dial tcp [::1]:8080: connectex: No connection could be made because the target machine actively refused it. Windows 10

### ISSUE THREAD

**Issue by Dev1969** [kubernetes/kubernetes#53881]
Hello Experts,

I want to learn Kubernetes and installed it on my laptop that is running Windows 10.

Installed:
minikube using minikube-installer
python-3.6.3
Git-2.14.2.2-64-bit
VirtualBox-5.1.28-117968-Win
kubectl

Install went fine. In the firewall Exception list, I have put minikube and kubectl. 

I am getting below error

kubectl version
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"6e937839ac04a38cac63e6a7a306c5d035fe7b0a", GitTreeState:"clean", BuildDate:"2017-09-28T22:57:57Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"windows/amd64"}

Unable to connect to the server: dial tcp [::1]:8080: connectex: No connection could be made because the target machine actively refused it.

What could be possible reason for this error? How to fix it?

Please let me know what all information you need to help me on this. I searched for other similar issues but that did not help much.

Thank you in advance.

Regards,
Dev

**Comment by ddlaat** [comment]
+1

**Comment by andyzhangx** [comment]
AFAIK, k8s could run on windows 2016 server. Could your win10 run docker service successfully? I think you could run "docker run -d microsoft/aspnet", try a windows container first.

**Comment by rjmorse** [comment]
This doesn't look related to running Kubernetes on Windows, but getting Minikube running inside a VM on Windows. This should probably be closed in favor of creating a new question on Stack Overflow, or finding one that is already answered. 

A number of related troubleshooting issues exist: https://stackoverflow.com/search?q=%5Bminikube%5D+windows

**Comment by akochnev** [comment]
I just ran into this issue with VirtualBox, and without minikube.

**Comment by akochnev** [comment]
I looked a bit further into my issue, and it turned out that I had a different issue of kubectl not being properly configured with a kubeconfig that points to an actually running API server. 

@Dev1969 - there could be many issues that could be causing this issue for you, including the api server not running, kubectl on your windows machine not being configured correctly, and that's on top of networking issues in your VirtualBox setup. Without further details (logs , etc) it would not be possible to further diagnose this issue. As previously mentioned, this is unlikely to be windows (or sig-windows) related.

With that, it does seem like this issue should be closed . @michmike - can you please close this issue to reduce clutter ?

**Comment by msiddharthareddy** [comment]
Windows10
--------------

Step 1 : 
I have installed kubectl in directory 
C:\Users\msiddhartha\play\kubernetes\vagrant-provisioning>curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.17.0/bin/windows/amd64/kubectl.exe

Step 2 : 
Came back to home directory 
C:\Users\msiddhartha>C:\Users\msiddhartha\play\kubernetes\vagrant-provisioning\kubectl 
It gives options to run Kubectl

Step 3: 
Please   copy admin.conf file from master server location(/etc/kubernetes) to  C:\Users\msiddhartha\.kube 

step 4:
rename admin.conf to config in the C:\Users\msiddhartha\.kube directory
step5: 

C:\Users\msiddhartha>C:\Users\msiddhartha\play\kubernetes\vagrant-provisioning\kubectl cluster-info
Kubernetes master is running at https://192.168.42.100:6443
KubeDNS is running at https://192.168.42.100:6443/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy

**Comment by Henry-Asante** [comment]
$ kubectl get nodes
Unable to connect to the server: dial tcp 34.229.22.26:443: connectex: No connection could be made because the target machine actively refused it.

Even after setting up the KUBECONFIG env variable.

**Comment by sarojsingh002** [comment]
How do you set up environment variable for config. Could some one please explain in details. I am using windows home and trying to docker-compose.yml to k8 but when i do kompose up it says:
`Error while deploying application: Get http://localhost:8080/api: dial tcp [::1]:8080: connectex: No connection could be made because the target machine actively refused it.`

Thanks in advance

**Comment by utsavakru** [comment]
1. Issue : Kubectl get nodes
Unable to connect to the server: dial tcp [::1]:6445: connectex: No connection could be made because the target machine actively refused it.

2. To fix this issue, Run the command below to tell the kubernetes where to find the configuration file:
[Environment]::SetEnvironmentVariable("KUBECONFIG", $HOME + "\.kube\config", [EnvironmentVariableTarget]::Machine)
 
3. Reset Kubernetes cluster settings.

Hope this checking configuration properly method helps...

**Comment by vedantdave77** [comment]
Hello, I have windows 10 and I also had the same problem, by resetting the kubernetes cluster, now I solved problem. 
I was using the docker- desktop and also have the minikube setup. so first I deleted the minikube from the programs and disable the kubernetes from docker desktop. 

Then I restart my computer to make sure that the other files removed properly from the file system as well. 

For, new installation I used minikube downloading instructions. (https://minikube.sigs.k8s.io/docs/start/). And go with the procedure. After step no. 2, I faced the problem with setup and diverted to "driver page" where, I use the installation with docker section instructions. And, noew my kubernetes works fine. 

Short CLI Commands: 

`choco install minikube`
`minikube start`             
`minikube start --driver=docker`
`minikube config set driver docker`

Now, run any kubectl command, if you have the deployment yaml file then,...
`kubectl apply -f <file path with name>`

Give me feed back. Thank you.

**Comment by Hamza-Aziz** [comment]
you can just run the command `minikube start --driver=virtualbox` with the driver option if you're working with virtualbox

**Comment by rparwani16** [comment]
Client Version created . Server version : Unable to connect to the server: dial tcp 127.0.0.1:8080: connectex: No connection could be made because the target machine actively refused it.

**Comment by Hamza-Aziz** [comment]
Try to run the command as an administrator if you're on Windows

**Comment by LQss11** [comment]
Have you checked that your docker service is started and running properly?

**Comment by RomitMehta** [comment]
For me, minikube was in stopped state. Try running `minikube start` and then accessing it

**Comment by arman-zhumakhan** [comment]
I solved it without restarting minikube. 
1. I stopped it `minikube stop`,
2. Started again `minikube start --driver=docker`

**Comment by Bhaskar1312** [comment]
I somehow modfied/deleted config for docker-desktop (windows 10) which I got to know after running `kubectl config use-context`
I got the same error
I used `kubectl config use-context docker-desktop` which resolved the issue for me

**Comment by RNJEGA** [comment]
@Bhaskar1312 **kubectl config use-context docker-desktop** works. 👌

**Comment by swapna2021** [comment]
> I somehow modfied/deleted config for docker-desktop (windows 10) which I got to know after running `kubectl config use-context` I got the same error I used `kubectl config use-context docker-desktop` which resolved the issue for me

Thank you
