### ISSUE TITLE
DaemonSet can create multiple pods per node during failover, does not give at-most-one semantics

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#54096]
Extracted from a long discussion in https://github.com/kubernetes/community/pull/977

Briefly:

1. DaemonSets intend to give at-most-one semantics to reduce confusion and make them easier to reason about for new users
2. DaemonSets are not currently implemented in a way that guarantees at-most-one (controller failure and a slow pod cache can result in two pods scheduled on a node), which means users that do not provide defensive measures may experience data corruption in the worst case
3. In general, we (as a project) try to avoid giving the impression of at-most-one if we don't offer it
4. It should be possible to have at-least-one semantics for daemonsets for HA rolling upgrades - probably as a spec field on DaemonSet that weakens the guarantee at user request (opt-in acknowledgement of behavior)

We need to verify that the solutions to the current at-most-one gaps would not implicitly break the API guarantees in order to make DaemonSets v1.

Explanation of scenarios leading to multiple pods:

1. New node added at RV=9
2. DaemonSet adds pod to node at RV=10
3. Controller process crashes and is restarted
4. New controller reads initial cache state from server, but api server has not yet processed the pod creation into its cache (so state of pod cache is RV=9)
5. Controller performs pod list, sees no pod, creates a new one

Another scenario is when the controller loses its lease - there can be two controllers running on the cluster, and the second controller gets a slightly lagging pod cache.  Design wise we have to assume that controller caches can be arbitrarily delayed and no process state may be present for those caches.

**Comment by kow3ns** [comment]
1. If we do this, I think we should use deterministic (based on Node name) naming to ensure that the API server records at most one Pod per Node per DaemonSet. This is a straight forward approach, and it is consistent with, though not identical to, how we handle idempotent creation for Deployment, ReplicaSet, StatefulSet, and ControllerRevision. This pattern was arrived at after our discussions about StatefulSet and DaemonSet history.

1. If we want DeamonSet to ever support a version of maxSurge, we should use Node name and revision to create a unique name so that we can allow for create first then delete semantics.

1. I'm still not entirely convinced that we should do this. I can't find any concrete examples of catastrophic failures based on the current semantics. However, deterministic vs random naming and idempotent creation are more consistent with what we've done for the other controllers.
