### ISSUE TITLE
After device is attached, devicepath of FC and iSCSI plugin are empty 

### ISSUE THREAD

**Issue by mtanino** [kubernetes/kubernetes#54108]
**Is this a BUG REPORT or FEATURE REQUEST?**: BUG

/kind bug

**What happened**:

FC and iSCSI plugins have attacher interface, these plugins need to run attach operations at kubelet node. Therefore attach operations are called during `volumeAttacher.WaitForAttach()` call currently.

`WaitForAttach()` is called during `GenerateMountVolumeFunc()`, and in this method even if plugin attaches a volume to kubelet node, kubelet doesn't update `devicePath` into actualStateOfWorld by using `MarkVolumeAsAttached()`.

As a result, we hit following errors during `GenerateUnmountDeviceFunc()` call.

```
E1017 19:44:49.165870   30726 nestedpendingoperations.go:264] Operation for "\"kubernetes.io/fc/[50060e801049cfd1]:0\"" failed. No retries permitted until 2017-10-17 19:44:49.665850506 -0400 EDT (durationBeforeRetry 500ms). Error: "UnmountDevice.DeviceOpened failed for volume \"file-pv001\" (UniqueName: \"kubernetes.io/fc/[50060e801049cfd1]:0\") on node \"127.0.0.1\" : PathIsDevice failed for path \"\": stat : no such file or directory" 
I1017 19:44:49.726788   30726 reconciler.go:283] operationExecutor.UnmountDevice started for volume "file-pv001" (UniqueName: "kubernetes.io/fc/[50060e801049cfd1]:0") on node "127.0.0.1"  
W1017 19:44:49.727215   30726 mount.go:165] could not determine device for path: "/var/lib/kubelet/plugins/kubernetes.io/fc/50060e801049cfd1-lun-0" 
W1017 19:44:49.727433   30726 util.go:94] Warning: Unmount skipped because path does not exist: /var/lib/kubelet/plugins/kubernetes.io/fc/50060e801049cfd1-lun-0 
E1017 19:44:49.727469   30726 nestedpendingoperations.go:264] Operation for "\"kubernetes.io/fc/[50060e801049cfd1]:0\"" failed. No retries permitted until 2017-10-17 19:44:50.727452685 -0400 EDT (durationBeforeRetry 1s). Error: "UnmountDevice failed for volume \"file-pv001\" (UniqueName: \"kubernetes.io/fc/[50060e801049cfd1]:0\") on node \"127.0.0.1\" : fc: failed to detach disk: \nError: fc detach disk: invalid device name: " 
```

Also this problem affects FC plugin's block volume support.
https://github.com/kubernetes/kubernetes/pull/51493

At the block volume support, we will have `GenerateUnmapDeviceFunc()` which has similar functionality to the `GenerateUnmountDeviceFunc()`.

In this method, we need devicePath at step 2 & 3.
1. Check global map path if symbolic links exist
2. Remove loopback device which takes file descriptor lock for block device(/dev/sdX)
3. Check DeviceOpened()

**What you expected to happen**:

Plugins which attach volume during WaitForAttach() can store devicePath into actualStateOfWorld properly.

**How to reproduce it (as minimally and precisely as possible)**:
- Create FC PV/PVC then create pod with a PVC
- Delete the pod

**Anything else we need to know?**:
/cc @msau42 @jingxu97  @rootfs 

Similar problem was reported from @rootfs in previous and then solution was proposed, but this wasn't merged.
https://github.com/kubernetes/kubernetes/pull/35433

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4", GitCommit:"d6f433224538d4f9ca2f7ae19b252e6fcb66a3ae", GitTreeState:"clean", BuildDate:"2017-05-19T18:44:27Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.0-alpha.1.1281+e3e2e24cc59161-dirty", GitCommit:"e3e2e24cc59161736be459abc2581f2a10b9252d", GitTreeState:"dirty", BuildDate:"2017-10-17T23:19:04Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release): Fedora 25
- Kernel (e.g. `uname -a`): 4.11.3-200.fc25.x86_64
- Install tools: ./hack/local-up-cluster.sh
- Others:

/sig storage
cc @kubernetes/sig-storage-bugs

**Comment by saad-ali** [comment]
I don't think this is the right approach. The fact that iSCSI and FC are doing attach inside `WaitForAttach()` is wrong. And modifying these interfaces to support that is making it worse. Let's revisit if it makes sense to have FC and iSCSI implement a attacher interface.

**Comment by mtanino** [comment]
@saad-ali 
Thank you for the comment. I understand. I'll revisit this for v1.10.

IIUC, the attacher interface was introduced to enforce accessModes=ReadWriteOnce via A/D controller.
If there is an alternative way to enforce accessModes without A/D controller, we could use it for FC and iSCSI.

Thanks,

**Comment by mlmhl** [comment]
I'm working on this.

**Comment by mlmhl** [comment]
@mtanino 
I'm not sure if this [method](https://github.com/kubernetes/kubernetes/blob/a6710f3b8751154596ebf29feecd4b90d06ad4bc/pkg/controller/volume/attachdetach/reconciler/reconciler.go#L139) is the **AccessModes enforce via A/D controller** as you mentioned above.

IIUC, this method is introduced to let attach operation fails fast for special case(`AzureDisk`), avoid A/D controller hangs on a single attach operation for a long time, see this PR: #45346 . For local volumes(`fc`, `iscsi`, `rbd`, etc.), their `Attach` method does nothing, so the attach workflow in A/D controller doesn't consume much time for these volumes, in other words, the above check is not necessary for local volumes.

Then these local volume plugins do not need to implement `AttachableVolumePlugin`  any more, so we can refactor them, execute all actual host attach/mount operations inside `Mounter`.

**Comment by mtanino** [comment]
@mlmhl 

From the godoc of isMultiAttachForbidden(), main purpose of this method is to check accessModes if attaching this volume to multiple nodes is definitely not allowed/possible. For example, FC and iSCSI plugin don't allow attaching a volume to multiple pods which are running on different kubelet nodes.(ReadWriteMany is required but these plugins don't support it)

Then if PV has accessMode = ReadWriteOnce, isMultiAttachForbidden() return true, as a result, if a volume is already attached to one node, Multi-Attach error is generated and skip attaching a volume to another node. Therefore this method is enforcing AccessModes via A/D controller.

**Comment by mtanino** [comment]
>> Then these local volume plugins do not need to implement AttachableVolumePlugin any more, so we can refactor them, execute all actual host attach/mount operations inside Mounter.

I think these local attach volume plugins still need `AttachableVolumePlugin` to use isMultiAttachForbidden().

Also please see the video after 44:45. @saad-ali explains refactor of attacher for local attach volume plugins. We should follow his idea for this refactor.
https://www.youtube.com/watch?v=KEXjN33csT0&feature=youtu.be

I'm not fully understand his idea for this refactor right now, so please talk to him directly then get whole idea for the refactor.(also please share it)

**Comment by saad-ali** [comment]
I agree with @mlmhl. Specifically this:

> I'm not sure if this method is the AccessModes enforce via A/D controller as you mentioned above.
> 
> IIUC, this method is introduced to let attach operation fails fast for special case(AzureDisk), avoid A/D controller hangs on a single attach operation for a long time, see this PR: #45346 . For local volumes(fc, iscsi, rbd, etc.), their Attach method does nothing, so the attach workflow in A/D controller doesn't consume much time for these volumes, in other words, the above check is not necessary for local volumes.

To expand on this, Kubernetes never really enforced access modes. Although the API let you mark a PV/PVC as read-write once if two different pods on two different nodes referenced the same volume, the first one to schedule would attach successfully, and then the attach operation would fail on for the second one leaving the pod in pending state. `accessModes` enforcement was added as a hack because `AzureDisk`, in this case, would take a very long time to fail attach and cause user visible slowness. iSCSI does not suffer from these issues so I would be happy with these changes:

* In volumes.go:
  * Introduce a new `DeviceMounter` interface:
  ```GO
  // These methods will only be called by kubelet on nodes, not the attach/detach controller.
  type DeviceMounter interface {
        // Logic to mount the device corresponding to spec to a global mount path.
        // Volume plugin will internally generate the device mount path, so no GetDeviceMountPath(spec *Spec) (string, error) method is needed.
        // Volume plugin will internally generate the path of the device to mount, so no GetDevicePath(spec *Spec) method is needed.
        // Some attachable volumes (like AWS) require the path of the device to mount to be returned by the Attach method and passed from the A/D controller to kubelet, in this case the new SetMountDevicePath(spec *Spec, devPath str) can be used to set the path.
        // For other volumes (like GCE PD, iSCSI, etc.), this can be generated from the spec.
  	MountDevice(spec *Spec) error

        // For attachable volumes (like AWS) that require the path of the device to mount to be returned by the Attach method and passed from the A/D controller to kubelet, this method can be used by the kubelet volume manager to set the MountDevice path it retrieves from the Node API object.
        // For volume that can generate the path internally, this is a no-op
        SetMountDevicePath(spec *Spec, devPath str)
  }
  ```
  * Remove the device mounter methods from `Attacher` and add the new `DeviceMounter` interface in to `Attacher` so that to implement `Attacher` plugins must also implement `DeviceMounter`:
  ```GO
  // These methods will be called by the attach/detach controller.
  type Attacher interface {
  	Attach(spec *Spec, nodeName types.NodeName) (string, error)
  	VolumesAreAttached(specs []*Spec, nodeName types.NodeName) (map[*Spec]bool, error)
  	WaitForAttach(spec *Spec, devicePath string, pod *v1.Pod, timeout time.Duration) (string, error)
  	DeviceMounter
  }
  ```
  * Apply similar changes to `Detach` and `UnmountDevice`
* In plugins.go
  * Introduce a new `DeviceMountableVolumePlugin` interface:
  ```GO
  type DeviceMountableVolumePlugin interface {
  	VolumePlugin
  	NewMounter() (DeviceMounter, error)
  	NewUmounter() (DeviceUmounter, error)
  	GetDeviceMountRefs(deviceMountPath string) ([]string, error)
  }
  ```
  * Remove the methods from `AttachableVolumePlugin` and add the new `DeviceMountableVolumePlugin` interface in to `AttachableVolumePlugin` so that to implement attachable plugins must also implement `DeviceMountableVolumePlugin`.
* Modify plugins
  * Local volume plugins, like iSCSI can implement `DeviceMounter` only.
  * Attachable volume plugins, like GCE and AWS can implement `Attacher` and `DeviceMounter`.
* Modify Kubernetes code (volume manager and attach/detach controller)
  * For attachable plugins and device mounter plugins kubelet volume manager will call the `DeviceMounter.MountDevice()` method.
  * For attachable plugins, if the device path passed from A/D controller via the Node API object's `VolumesAttached` field is not empty, call `SetMountDevicePath()` to make the volume plugin aware of the device path.

**Comment by mtanino** [comment]
@saad-ali 
Thank you for the detail explain. Seems this update needs a spec like volume reconstruction update which jinxu proposed.

Quick question, if local volume plugins such as iSCSI, FC will have DeviceMountableVolumePlugin instead of AttachableVolumePlugin, can these plugins avoid following multi attach case? Which operation avoids it?

```
Although the API let you mark a PV/PVC as read-write once if two different pods on two different
nodes referenced the same volume, the first one to schedule would attach successfully, and then
the attach operation would fail on for the second one leaving the pod in pending state.
```

**Comment by saad-ali** [comment]
> Seems this update needs a spec like volume reconstruction update which jinxu proposed?

Do you mean a design doc? If so, I agree, this is big enough a change that a design doc would be useful.

> Quick question, if local volume plugins such as iSCSI, FC will have DeviceMountableVolumePlugin instead of AttachableVolumePlugin, can these plugins still avoid following multi attach case? Do you suppose which operation avoids it?

They will not have "fast fail" that the A/D controller implements. But as long as the MountDevice operation fails, then this will apply:

Although the API let you mark a PV/PVC as read-write once, if two different pods on two different
nodes reference the same volume, Kubernetes does not explicitly block both volumes from trying to attach/mount. For plugins that implement `DeviceMounter`, the first volume to schedule would Mount the device successfully, and the second volume to schedule would fail to start leaving the pod in pending state (as long as the `MountDevice` operation for the volume plugin fails if the device is already mounted on a different node).

**Comment by mtanino** [comment]
@saad-ali 

>> Do you mean a design doc? If so, I agree, this is big enough a change that a design doc would be useful.

Ah, yes. Design doc I mean.

>> (as long as the MountDevice operation for the volume plugin fails if the device is already mounted on a different node).

I think local volume plugins are not managing volume attach/mount status if the volume is attached and mounted on a pod on different node. Therefore even if the volume is attached to another node and then `MountDevice` is called to mount a volume to different pod,  `MountDevice` can't be failed.
Am I missing something?

I still prefer the way to avoid multi attach using "fast fail" via the A/D controller implements because we can avoid `volume attach operation` to a kubelet node instead of avoiding mount operation.
Also block volume doesn't have `MountDevice`, we need to care of it.

@rootfs 
Any comments?

**Comment by mlmhl** [comment]
@saad-ali 
I'm not sure if the `SetMountDevicePath` method of `DeviceMounter` is necessary or not.  Instead of adding a `SetMountDevicePath` method, maybe we can keep only the `MountDevice` method and add a `devicePath string` parameter to it, looks like this:

```go
type DeviceMounter interface {
    MountDevice(spec *Spec, devicePath string) error
}
```

For cloud volumes(like `AWS`), A/D controller will update the device path to node API object after attach operation finished, then kubelet retrieves this device path from the Node API object and caches it in `ActualStateOfWorld`, see this [code](https://github.com/kubernetes/kubernetes/blob/b7100f1ee7231617891a100dd34b3490a1f578e4/pkg/volume/util/operationexecutor/operation_generator.go#L1185). After that, kubelet can pass this cached device path to `MountDevice`(This is exactly what kubelet currently does). For local volumes, we can just pass an empty `devicePath` as they can generate the path internally. This keeps the code simple and clear.

By the way, maybe we should also add the `GetDeviceMountPath` method to `DeviceMounter`, as it is used in `operationGenerator.GenerateUnmountDeviceFunc`.

All of the above is a preliminary design, I will post a more detailed design doc for this refactor soon.

**Comment by mlmhl** [comment]
@mtanino 
I'm not sure if there is a method to exclusive volume for `fc` and `iscsi`. For `rbd`, if the volume is requested as `ReadWrite`(in other words, `ReadOnly` not set), maybe we can try to lock the volume first, if failed, it means this volume is already attached to a different node, then we can just report an error and remain according pod in `pending` state.

By the way, I think the A/D controller's multi attach validation is not very accurate. As `fc`, `iscsi` and `rbd` all supports two access modes: `ReadWriteOnce` and `ReadOnlyMany`, so if a `PersistentVolume.Spec.AccessModes` has both these two modes, `isMultiAttachForbidden` will just simply return `false`,\ even if the volume is requested as `ReadWrite`, ultimately A/D controller cannot avoid the volume mounts to different nodes.

As you mentioned, we also need to take care of block volumes, it looks like the main work is move the attach operation from `WaitForAttach` to `SetUpDevice`, I will take a deep look later.

**Comment by saad-ali** [comment]
> I think local volume plugins are not managing volume attach/mount status if the volume is attached and mounted on a pod on different node. Therefore even if the volume is attached to another node and then MountDevice is called to mount a volume to different pod, MountDevice can't be failed.
> Am I missing something?
> 
> I still prefer the way to avoid multi attach using "fast fail" via the A/D controller implements because we can avoid volume attach operation to a kubelet node instead of avoiding mount operation.
> Also block volume doesn't have MountDevice, we need to care of it.

If the volume plugin has no way to know that the volume is attached on another node and `MountDevice`  for the second volume will succeed, then why try to stop it?

>I'm not sure if there is a method to exclusive volume for fc and iscsi. For rbd, if the volume is requested as ReadWrite(in other words, ReadOnly not set), maybe we can try to lock the volume first, if failed, it means this volume is already attached to a different node, then we can just report an error and remain according pod in pending state.

+1

> I'm not sure if the SetMountDevicePath method of DeviceMounter is necessary or not. Instead of adding a SetMountDevicePath method, maybe we can keep only the MountDevice method and add a devicePath string parameter to it, looks like this:
> ...
> For local volumes, we can just pass an empty devicePath as they can generate the path internally. This keeps the code simple and clear.

This gets confusing because it's hard to determine if the string is required but empty, or just not required. The `mountPath` will be only be required by some plugins (AWS). If we make it a parameter then we have no clean way to validate it for the plugins that require it. But I don't feel too strongly about this, so I will leave it to you to decide.

> By the way, maybe we should also add the GetDeviceMountPath method to DeviceMounter, as it is used in operationGenerator.GenerateUnmountDeviceFunc.

You mean `DeviceUnmounter`? Sure, if it is cleaner that way. 

> All of the above is a preliminary design, I will post a more detailed design doc for this refactor soon.

SGTM!

**Comment by mtanino** [comment]
@saad-ali 

>> If the volume plugin has no way to know that the volume is attached on another node and MountDevice for the second volume will succeed, then why try to stop it?

If a FC volume with ext4 filesystem is mounted to two pods on different kubelet nodes, and then these pods issue I/O to the FC volume simultaneously, issued data may be lost or volume may be corrupted since ext4 is not network shared filesystem.
I think to avoid this situation, attacher was introduced to local volume plugins.

**Comment by mtanino** [comment]
@mlmhl 

>> I'm not sure if there is a method to exclusive volume for fc and iscsi. For rbd, if the volume is requested as ReadWrite(in other words, ReadOnly not set), maybe we can try to lock the volume first, if failed, it means this volume is already attached to a different node, then we can just report an error and remain according pod in pending state.

For the SCSI device like iSCSI and FC, if storage supports SCSI reservation to take LUN lock, this might be one of solution. As you may know SCSI reservation is usually used by cluster software.
But this depends on backend vendor's storage also I suppose this make more complex for plugin implementation and also recovery process from error state.

I don't have alternative ideas to take lock for volume between multiple nodes.

**Comment by mtanino** [comment]
@mlmhl 

>> if a PersistentVolume.Spec.AccessModes has both these two modes, isMultiAttachForbidden will just simply return false,\ even if the volume is requested as ReadWrite, ultimately A/D controller cannot avoid the volume mounts to different nodes.

I was surprised that AccessModes is slice(`[]PersistentVolumeAccessModes`), so as you mentioned PVSpec can be defined with multiple access modes.
As a result, there is a case that A/D controller cannot avoid the volume mounts to different nodes.

But I thought this case is acceptable since user specifies two types of accessModes even if the volume doesn't work properly with multi-attach situation. But ideally, this situation should be avoided by Kubernetes.
I'm not sure but why API doesn't validate and make error if accessModes combinations are conflicting.

**Comment by mlmhl** [comment]
I'm also not sure if we need a more strict validation on `AccessModes` or not. @saad-ali  Any comments?

**Comment by mtanino** [comment]
I think we shouldn't add more strict validation because it breaks API's backward compatibility.

**Comment by saad-ali** [comment]
> If a FC volume with ext4 filesystem is mounted to two pods on different kubelet nodes, and then these pods issue I/O to the FC volume simultaneously, issued data may be lost or volume may be corrupted since ext4 is not network shared filesystem.

Thank you for pointing out this use case. I think it is important that we have an answer for this.

> For the SCSI device like iSCSI and FC, if storage supports SCSI reservation to take LUN lock, this might be one of solution. As you may know SCSI reservation is usually used by cluster software.
> But this depends on backend vendor's storage also I suppose this make more complex for plugin implementation and also recovery process from error state.
> 
> I don't have alternative ideas to take lock for volume between multiple nodes.

If we go with this solution, will there be any user visible issues?

>> I was surprised that AccessModes is slice([]PersistentVolumeAccessModes), so as you mentioned PVSpec can be defined with multiple access modes.
>> As a result, there is a case that A/D controller cannot avoid the volume mounts to different nodes.
>> 
>> But I thought this case is acceptable since user specifies two types of accessModes even if the volume doesn't work properly with multi-attach situation. But ideally, this situation should be avoided by Kubernetes.
>> I'm not sure but why API doesn't validate and make error if accessModes combinations are conflicting.
> I'm also not sure if we need a more strict validation on AccessModes or not

My understanding is that `[]PersistentVolumeAccessModes` was initially an array so that a volume could describe the *exact* mode of operations that they exposed. And binding logic was initially an exact match. But eventually the binding logic was relaxed (see https://github.com/kubernetes/kubernetes/pull/10833) to allow, for example, a RWO PVC to match with RWO+RWX. I opened an issue a long time ago to revisit and clean up this logic (https://github.com/kubernetes/kubernetes/issues/13686), but never got around to it. I would be ok with revisiting it, but we need to be careful: making validation stricter can break backwards compatibility.

**Comment by mtanino** [comment]
@saad-ali 

>>For the SCSI device like iSCSI and FC, if storage supports SCSI reservation to take LUN lock, this might be one of solution. As you may know SCSI reservation is usually used by cluster software.
But this depends on backend vendor's storage also I suppose this make more complex for plugin implementation and also recovery process from error state.
>>I don't have alternative ideas to take lock for volume between multiple nodes.

>If we go with this solution, will there be any user visible issues?

I'm not much familiar with SCSI reservation, but as I mentioned, it depends on software target or vendor storage whether SCSI reservation is supported or not. For example, some vendor iSCSI/FC storage supports the functionality but others may not support it. Therefore I thought using this solution introduces a restriction for available storage, then some of storage may not be used for Kubernetes anymore.

This isn't user visible issue, but admin facing issue.

Instead, I thought managing attach status via pv_controller is more flexible way for local volume attach plugins too.

**Comment by saad-ali** [comment]
This feature made it in to 1.9 as alpha:
* 11/30 - Everything merged except change in scheduler. Change in scheduler is nice to have but not critical.
* 11/29 - unmerged PR (scheduler): https://github.com/kubernetes/kubernetes/pull/55957
* 11/29 - merged PRs (PVC Protection controller, admission controller plugin, CLI): https://github.com/kubernetes/kubernetes/pull/55824 https://github.com/kubernetes/kubernetes/pull/55873
* 11/9 - Design merged. Implmentation in progress.
Design: https://github.com/kubernetes/community/pull/1174  ready to be final review/merged

Planned to move to beta in 1.10

**Comment by jingxu97** [comment]
@mlmhl @mtanino Actually, I think my PR of new design of reconstruct volume can address the issue here https://github.com/kubernetes/kubernetes/pull/58177/files#diff-450e811a4953f760ff1594ede8b2037eL526, right?

**Comment by mtanino** [comment]
@jingxu97 

I think your volume reconstruction refactor keeps `deviceMountPath` into asw.attachedVolumes but local volumes('rbd', `fc`, `iscsi`) needs `devicePath` in this case.
As you know I proposed a patch which keep `devicePath` into attachedVolume at (https://github.com/kubernetes/kubernetes/pull/54264), but the proposed patch wasn't accepted.

So I think your `new reconstruction proposal` and `local volume attach/detach refactor` are different.

**Comment by jingxu97** [comment]
@mtanino I see. I think updating devicePath proposed at #54264 is actually ok. I will talk to Saad about it. Thanks!

**Comment by mtanino** [comment]
@jingxu97 
Thank you for taking care of this problem.

**Comment by jingxu97** [comment]
@mtanino Talked to Saad about this issue, we can update the devicePath after local attach finishes to solve the problem. I can made the changes in my PR https://github.com/kubernetes/kubernetes/pull/58177

**Comment by mtanino** [comment]
@jingxu97

Great! Thank you for your help.

**Comment by jingxu97** [comment]
@mtanino Could you please help test PR #58177 to see whether it solves the issue? Thanks!

**Comment by calvix** [comment]
Hello, what is the progress of this? I seem to be hitting a similar issue. I the fix already included in some of the beta releases of 1.10?

**Comment by mtanino** [comment]
@calvix @jingxu97 
IIUC, this issue isn't fixed. Still wating second PR of https://github.com/kubernetes/community/pull/1601.

**Comment by jingxu97** [comment]
For empty device path issue,
1. #58177 solves the main problem: After volume is attached and mounted, the actual device path should be updated into the actual state so that volume teardown process can get this information correctly.
2. In a corner case, when pod is deleted forcefully (with --force option) during kubelet restarts, kubelet no longer has the pod object so that reconciler cannot build the actual state by going though the volume setup procedure. So volume reconstruction process will try to use the volume paths information obtained directly from disk to update the actual state. The devicePath is obtained from node status before which might not work for some block volumes. PR #61418 should fix this issue.

**Comment by saad-ali** [comment]
> @mtanino Talked to Saad about this issue, we can update the devicePath after local attach finishes to solve the problem. I can made the changes in my PR #58177

There might've been some miscommunication, but I don't recall agreeing to doing local volume attach inside `WaitForAttach()`. That is the same objection I raised in https://github.com/kubernetes/kubernetes/pull/54264#issuecomment-346447093. I'm not happy that this went in, but I failed to keep an eye on this issue and did not review https://github.com/kubernetes/kubernetes/pull/58177 so it's my fault.

Since https://github.com/kubernetes/kubernetes/pull/58177 is merged, we have to live with it for now. In the future we should come up with a better way to handle Local Attach with the concerns that @mtanino raised in https://github.com/kubernetes/kubernetes/issues/54108#issuecomment-358530942.
