### ISSUE TITLE
Kubelet shows the Status of a mirror/static pods as Running, even though the host is down

### ISSUE THREAD

**Issue by luckyfengyong** [kubernetes/kubernetes#54171]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
I launch kube-proxy as static pod. When I shutdown the host, the kubectl still shows the pods of kube-proxy as running. 

**What you expected to happen**:
It is expected to show its status as something like unknown, as kube apiserver cannot contact kubelet

**How to reproduce it (as minimally and precisely as possible)**:
1. Run kube-proxy as static pod
2. Shutdown the host

**Anything else we need to know?**:
The podcondition of ready shows as false which is correct.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.7.3o
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release): RHEL 7.2
- Kernel (e.g. `uname -a`): 3.10.0-327.el7.x86_64
- Install tools:
- Others:

**Comment by k82cn** [comment]
how about enable [TaintBasedEviction](https://github.com/kubernetes/features/issues/166) feature; when the node is unreachable, the mirror pod should be delete.

**Comment by tengqm** [comment]
@k82cn are you sure taint based eviction can handle static/mirror pods?

**Comment by dchen1107** [comment]
This is by design. Each Pod is initiated with Unknown state, and never go back to it. Node condition might be moved back to UNKNOWN state by node_controller if Kubelet doesn't post NodeStatus for some period (configurable, and default: 5mins). When a particular node is at UNKNOWN condition, node_controller will mark every pods on that node NotReady. There is no PodPhase / PodCondition transition at this stage. The related logic can be found: https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/node/node_controller.go#L608

**Comment by luckyfengyong** [comment]
@dchen1107 Thanks for the response. It is OK to mark the pod as NotReady, however the current behavior is that Pod is still shown as running.
