### ISSUE TITLE
Have garbage collector use patch to update finalizers, not update

### ISSUE THREAD

**Issue by jim-minter** [kubernetes/kubernetes#54430]
When the garbage collector runs against an object which contains RawExtension fields, currently it will decode the nested object into an unstructured.Unstructured, then re-encode it when it posts an update.  This may have the side effect of changing the serialisation of the nested object (e.g. field orderings) and is more CPU and bandwidth intensive than is necessary.

It would be better if Patch were used to remove the object finaliser instead.

/kind bug

@deads2k 
@ironcladlou

**Comment by deads2k** [comment]
/assign ironcladlou
/assign caesarxuchao

If it's just about writing a patch for finalizers, you should be able to do a json replace of the entire field and also assert a resourceVersion to avoid conflicting.

We should create a polymorphic `/finalize` subresource so that we can ACL these separately.

**Comment by caesarxuchao** [comment]
Working on this now.

**Comment by nilebox** [comment]
@caesarxuchao @liggitt should this issue be reopened?

**Comment by liggitt** [comment]
Fixed in https://github.com/kubernetes/kubernetes/pull/75972

/close
