### ISSUE TITLE
Error creating Flexvolume plugin from directory flexvolume

### ISSUE THREAD

**Issue by cablespaghetti** [kubernetes/kubernetes#54494]
/kind bug
/sig Storage

**What happened**:
After upgrading from v1.7.8 to v1.8.1 I can't get any FlexVolume plugins to work. Including the nfs plugin from here: https://github.com/kubernetes/kubernetes/tree/master/examples/volumes/flexvolume

It seems to be trying to parse the bash scripts as JSON now.

**What you expected to happen**:
The plugin to be loaded and my volumes to be mounted.

**How to reproduce it (as minimally and precisely as possible)**:
Set the volume-plugins-dir to /etc/kubernetes/volumeplugins
Put the nfs plugin in /etc/kubernetes/volumplugins/flexvolume~nfs/nfs

Restart kubelet and look at the output which looks something like this:
`Oct 24 16:26:15 localhost kubelet-wrapper[2702]: E1024 16:26:15.624996    2702 driver-call.go:237] Failed to unmarshal output for command: init, output: "-ne {\"status\": \"Success\", \"capabilities\": {\"attach\": false}}\n", error: invalid character 'n' in numeric literal
Oct 24 16:26:15 localhost kubelet-wrapper[2702]: E1024 16:26:15.625082    2702 plugins.go:515] Error dynamically probing plugins: Error creating Flexvolume plugin from directory flexvolume~nfs, skipping. Error: invalid character 'n' in numeric literal`

**Environment**:
- Kubernetes version (use `kubectl version`): 1.8.1
- Cloud provider or hardware configuration**: VMWare
- OS (e.g. from /etc/os-release): CoreOS 1409.5.0
- Kernel (e.g. `uname -a`): Linux localhost 4.11.6-coreos-r1 #1 SMP Thu Jun 22 22:04:38 UTC 2017 x86_64 Intel(R) Xeon(R) CPU E5-2690 0 @ 2.90GHz GenuineIntel GNU/Linux

Thanks in advance

**Comment by fvigotti** [comment]
Me too , I can't get my previous flexvolume running, I got this error
```
.......... Bad substitution\n-e {\"status\": \"Success\", \"capabilities\":{\"attach\":False}}\n", error: invalid character '/' looking for beginning of value
```
in kubelet.log
while the cifs plugin `init` output is : 
```
./cifs init
{"status": "Success", "capabilities":{"attach":False}}
```

I think that this is a quite severe issue, we are at second update and not yet fixed ? :) no one is using flexvolumes in production with version 1.8  ??

**Comment by fvigotti** [comment]
because it was strange for me to see the "-e" in the error ( which is an arg passed to echo in the flexvolume ) I've removed it.. but still.. somewhere seems that there is a prepended "/" at the beginning of the command output but I think that something is wrong in the source of kubernes... 
here is the errror 
```
Nov  2 11:50:16 xxx kubelet[7939]: E1102 11:50:16.442842    8027 driver-call.go:237] Failed to unmarshal output for command: init, output: "/etc/kubernetes/volumeplugins/fvigotti~cifs/cifs: 22: /etc/kubernetes/volumeplugins/fvigotti~cifs/cifs: Bad substitution\n{\"status\": \"Success\", \"capabilities\":{\"attach\":False}}\n", error: invalid character '/' looking for beginning of value
```

**Comment by fvigotti** [comment]
I have some insight , after a small investigation.. 
done because I still not understand why the "-ne" in your case and "-e" in my case params gets logged from kubelet.. while those are `echo` arguments in bash script..

I've found that there must be something strange in the flexvolume driver caller because some standard-and-working-in-1.7.x bash  commands doesn't work anymore..
replacing those two lines helped
```
#DIR=$( dirname ${BASH_SOURCE[0]})
DIR="/etc/kubernetes/volumeplugins/fvigotti~cifs/"
```
replacing `echo -e` with plain `echo` worked
I mean removing all bash commands that seems incompatible with this current kubernetes release.. my flexvolume bash script plugin works!

but I don't know why.. what they do during the call of the flexvolume that changed ? 

I mean , my workaround may partially-work for some but it's absurd that I cannot leverage full bash environment in my flexvolume plugin, so THIS STILL REMAINS AS MAJOR BUG in my opinion,

**Comment by cablespaghetti** [comment]
Thanks Francesco. I'll try hacking around with the driver I'm using. The most puzzling thing for me is that the example drivers don't seem to work either! If I have some spare time, I'll go digging around in the source code.

**Comment by fvigotti** [comment]
eureka,
after deeper investigation I've found the root of all that bad sentiment... 
the environment  of the new coreos images is f***ed ;)
docker run --rm -ti quay.io/coreos/hyperkube:v1.8.2_coreos.0 bash
then try to run "echo -e hello" and you see the error that we are seeing :) the -e is printed!, and so for all other commands that didn't work! 
what the hell... probably this hyperkube image is here to say, stop using me and build your hyperkube yourself ;(

**Comment by cablespaghetti** [comment]
Maybe use /bin/echo or something instead? Very strange...

**Comment by fvigotti** [comment]
using the full url of the command is the first thing I've tried at the end I was trying to run my script wrapped in another script ( exec bash $CIFSPLUGIN ) but the problem is that bash itself is broken
enven the `if [ "" == "" ]; then` doesn't work.. I don't  even can see which version of bash they are using,
results? stop using hyperkube, but anyway they should have informed us before.. I'm going to create a dedicated issue

**Comment by fvigotti** [comment]
#55012
