### ISSUE TITLE
Create pod latency increase

### ISSUE THREAD

**Issue by dashpole** [kubernetes/kubernetes#54651]
The node e2e density tests have been failing consistently: https://k8s-testgrid.appspot.com/sig-node-kubelet#kubelet-serial-gce-e2e&include-filter-by-regex=create%20a%20batch%20of%20pods
The only PRs in the diff that touch the kubelet seem related to CNI: https://github.com/kubernetes/kubernetes/compare/88975e98d...03cb11f02, with the likely candidate being #51250
In the run prior to it failing, the latency ranged from 3s to 4s.  In the first failing run, 50% percentile latency ranged from ~16s to ~19s, which is a major increase..

cc @kubernetes/sig-node-bugs @kubernetes/sig-network-bugs 
cc @dixudx

**Comment by dixudx** [comment]
Wow, this is a huge increase.
@squeed Any comments on the performances? I wonder whether this would have any impacts on kubelet and GC.
/cc @luxas

**Comment by squeed** [comment]
Interesting, taking a look.

**Comment by dixudx** [comment]
@squeed Thanks for your help.

**Comment by squeed** [comment]
Ah, I think I know the issue. The new CNI plugins wait for DAD to finish before proceeding, which takes 3 seconds on Linux. Still need to do some testing (helpfully, my laptop drive died yesterday).

**Comment by squeed** [comment]
The address-settle adds about 1 second of delay. Is that likely the complete cause, or is it also something else? (I'm not familiar with this test)

**Comment by squeed** [comment]
Ah, network setup is also serialized behind a mutex; the increase from 20ms to 1020ms for network setup in the critical path is almost certainly the culprit.

The CNI plugins could avoid the DAD delay for now (since we're not doing IPv6), this will eventually become a problem when ipv6 is supported.

Since the CNI plugin execution itself doesn't need to be synchronized, I think I can move that outside the mutex.

**Comment by luxas** [comment]
This seems to be a v1.9-blocking issue that needs to be fixed/tracked, right?

**Comment by bowei** [comment]
@dnardo @freehan

**Comment by freehan** [comment]
Good catch... This is why we need to bump CNI version at the early stage of a release cycle.

**Comment by danehans** [comment]
@squeed sig-network is planning to add ipv6 alpha support for the 1.9 release.

**Comment by porridge** [comment]
To be honest it does not seem like https://github.com/kubernetes/kubernetes/pull/54800 has fixed this. We are still seeing high pod startup in large ane medium scale tests: https://github.com/kubernetes/kubernetes/issues/55060#issuecomment-342122318

**Comment by feiskyer** [comment]
Reopen the issue based on https://github.com/kubernetes/kubernetes/issues/54651#issuecomment-342124062

**Comment by porridge** [comment]
Pretty graph for a dramatic effect:
![wx44anuahff](https://user-images.githubusercontent.com/489420/32440353-102e7e62-c2f3-11e7-9a3c-290818758135.png)

**Comment by squeed** [comment]
So, a question, then, is this a problem in the mind of the community?  More concretely, is it acceptable to run these tests with `--network-plugin=none`?

That will, of course, mean they do not as accurately test the full pod creation path. Another choice would be to move the baseline.

There isn't really any avoiding the DAD wait. While it could be skipped for ipv4-only workloads, as soon as the test runs on an ipv6-enabled cluster, the latency will come back.

**Comment by porridge** [comment]
It is definitely **not** acceptable to run these tests without a networking plugin.
I don't know enough about IPv6 to speak about whether duplicate address detection needs to be in the critical path for pod startup.

One thing that sounds certain though is that unless this regression is mitigated somehow, it needs a prominent mention in the release notes.

**Comment by porridge** [comment]
Also, FWIW merging of https://github.com/kubernetes/kubernetes/pull/54800 (merged on Nov 2nd) did not have any noticeable effect over the latency visible in the sig-scalability tests:

![i8tpze3km74](https://user-images.githubusercontent.com/489420/32457295-e46194aa-c328-11e7-9beb-baadbc12a0c1.png)

The above graph shows results between Oct 31st and Nov 3rd. (kubernetes/test-infra#5357 makes it hard to tell which run exactly had the change).

**Comment by squeed** [comment]
@porridge that makes sense; the metric I was fixing was "pods-created-per-second," which was badly broken by the lock contention. The metric "average pod creation time" shouldn't be improved by my changes.

In the case of IPv6, the network is unusable until DAD has completed (also, routes cannot be manipulated), so the CNI plugin really does need to wait for DAD. There's no getting around it for IPv6 clusters.

So, I see 3.5 solutions:
1. We decide that this is "the new normal." Pods-per-second is still largely unaffected, only individual pod creation latency.
2. The CNI plugin stops waiting for DAD. This is "kicking the can down the road," since ipv6 will still have this delay, and the tests will fail when we start to test that (and we all will have forgotten why this was a problem)
3. We disable DAD when using kubenet. Since Kubenet has external guarantees that addresses won't collide, this is safe.

And, the last, non-solution: revert to a very old version of the CNI plugins.

I prefer numbers 1 and 3 - and am happy to do the work.

**Comment by luxas** [comment]
Crazy idea: Can we do things conditionally for IPv4 and IPv6?
Does this only affect kubenet or any CNI plugin (like Weave, Flannel, etc)?

**Comment by porridge** [comment]
Since my knee-jerk reaction to discovering what the DAD acronym stands for
was "why do we need this anyway", I think that option (3) sounds most
compelling.
OTOH I clearly am missing the big picture since I didn't know that there is
an option for using anything else than kubenet.

**Comment by yujuhong** [comment]
> We disable DAD when using kubenet. Since Kubenet has external guarantees that addresses won't collide, this is safe.

I thought kubenet would be deprecated sooner or later. If that's still true, does that mean we'd need yet another solution for a non-kubenet setup?

**Comment by porridge** [comment]
Another question from a layman: do we know why it's so slow on Linux? Is it talking to other nodes (something like gratitious ARP)? Does it have a chance to become faster in the future? Does the delay depend on the size of the network/number of nodes, etc?

**Comment by squeed** [comment]
One way to make it faster on Linux is to enable "optimistic DAD" (RFC4429), which allows usage of tentative addresses. This is still considered to be an "experimental" feature, and is not enabled in all kernels. IIRC, the latest Ubuntu still has it disabled. CoreOS CL, Debian *do* have it. This is a sysctl that would need to be set in the container's network namespace, since it's a namespaced sysctl (and new network namespaces take the default configuration, rather than inheriting from the host).

**Comment by squeed** [comment]
@yujuhong yeah, you're right. Hopefully by then optimistic_dad is enabled on all kernels...

**Comment by luxas** [comment]
> I thought kubenet would be deprecated sooner or later.

it will

> If that's still true

yes

> does that mean we'd need yet another solution for a non-kubenet setup

probably, like @squeed said above.

pinging @kubernetes/kubernetes-release-managers already -- this MIGHT be one of the big things we need to notify people about if this doesn't get solved.

**Comment by shyamjvs** [comment]
@spiffxp Could you approve this for the milestone?

This issue needs to be resolved urgently, as it's causing 5k-node performance job (which is [release-blocking](https://k8s-testgrid.appspot.com/sig-release-master-blocking#gce-scale-performance)) to fail.

**Comment by squeed** [comment]
I'm working on disabling dad in kubenet (option 3).

 Should be ready soon.

**Comment by squeed** [comment]
OK, PR filed.

**Comment by spiffxp** [comment]
/status approved-for-milestone
FYI @shyamjvs it looks like @luxas already added to this to the v1.9 milestone, and @dchen1107 already added the label manually.

**Comment by shyamjvs** [comment]
PR https://github.com/kubernetes/kubernetes/pull/55247 seems to have done the trick. The latency has decreased

[from](https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/7781/artifacts/PodStartupLatency_density_2017-11-09T09:29:39Z.json):

```
    {
      "data": {
        "Perc100": 4762.418815,
        "Perc50": 3308.810795,
        "Perc90": 3955.747742,
        "Perc99": 4756.553711
      },
```

[to](https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/7782/artifacts/PodStartupLatency_density_2017-11-09T10:16:19Z.json):

```
    {
      "data": {
        "Perc100": 3178.085005,
        "Perc50": 2186.109036,
        "Perc90": 2768.180504,
        "Perc99": 3126.759942
      },
```

Closing the issue. Thanks everyone for working on this!

**Comment by luxas** [comment]
@shyamjvs Do we have any coverage what happens with these numbers if you're using a 3rd party CNI provider (Weave, Calico, Flannel, whatever)? If this ONLY fixes kubenet but throws a perf penalty to everyone non-GCE, I think we should reopen this issue.

**Comment by porridge** [comment]
sig-scalability does not run tests with other CNI providers, AFAIK

**Comment by squeed** [comment]
The delay was on the CNI executable side; so it depends on the plugin being used. That said, it would be good to have that codepath under test in general.

**Comment by shyamjvs** [comment]
We're not scale-testing with other CNI providers. One, because it seems to be the default option being used at head. Two, because it's simply not possible to scale test different configurations exhaustively due to resource and time constraints of running large cluster tests. So we choose to validate against (mostly) the default configs.

That said, opening this issue to study those options sg. However, it would be hard to get this under sig-scale's purview atm.

**Comment by porridge** [comment]
I'd suggest opening a separate issue to track this, as it's unlikely to fit
in 1.9.

**Comment by luxas** [comment]
Ok, thanks.
cc @timothysc FYI

**Comment by yujuhong** [comment]
> I'd suggest opening a separate issue to track this, as it's unlikely to fit
> in 1.9.

+1. Is this tracked anywhere?

**Comment by luxas** [comment]
Not AFAIK @yujuhong, please open one

**Comment by purva-n** [comment]
> Crazy idea: Can we do things conditionally for IPv4 and IPv6?
> Does this only affect kubenet or any CNI plugin (like Weave, Flannel, etc)?

Any ideas on this?
