### ISSUE TITLE
CAs, certs and keys passed to apiservers are incomprehensible

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#54665]
kube-apiserver (and extension apiservers) take a number of different auth related command line flags. Often but not always in triplets (-CA, -cert, -key). Many of the names of these flags are similar even though the flags do completely different things. (e.g. see https://github.com/kubernetes/kubernetes/issues/53828#issuecomment-339832669)

This issue is a request for a comprehensive, simply written guide to what these certs are, what they do, what powers they give, what their lifecycle ought to be, when users should rotate them, etc.

The follow up request is to change their names to make them less confusing, more consistent, etc.

**Comment by lavalamp** [comment]
Maybe this is a duplicate of #11000

**Comment by ericchiang** [comment]
Here's my initial list. Will try to find a home in github.com/kubernetes/website when I get a chance.

| flag | kind | from | to | notes |
|---|---|---|---|---|
| `--client-ca-file` | CA | (clients)  | API server | Clients can still use other creds (e.g. bearer token) instead of client cert. |
| `--etcd-cafile` | CA | API server | etcd | |
| `--etcd-certfile` | client cert | API server | etcd | |
| `--etcd-keyfile` | client key | API server | etcd | |
| `--experimental-keystone-ca-file` | CA | API server | Keystone instance | Only used for Keystone auth. | 
| `--kubelet-certificate-authority` | CA | API server | kubelet | If not provided, kubelet serving cert isn't verified. |
| `--kubelet-client-certificate` | client cert | API server | kubelet ||
| `--kubelet-client-key` | client key | API server | kubelet ||
| `--oidc-ca-file` | CA | API server | OpenID Connect provider | Only used for OIDC auth. |
| `--proxy-client-cert-file` | client cert | API server | Webhook admission servers | CA bundle is specified in webhook config. |
| `--proxy-client-key-file` | client key | API server | Webhook admission servers  | |
| `--requestheader-client-ca-file` | CA | Authenticating proxy | API server | https://kubernetes.io/docs/admin/authentication/#authenticating-proxy |
| `--service-account-key-file` | public key | N/A | N/A | Public (or private) key to verify service account JWTs. Defaults to `--tls-private-key-file`. | 
| `--tls-ca-file` | CA | (service accounts) | API server | CA to pass to service accounts to trust API server. ||
| `--tls-cert-file` | serving cert | (clients) | API server | |
| `--tls-private-key-file` | serving key | (clients) | API server | |
| `--tls-sni-cert-key` | serving cert/key | (clients) | API server | Can be used to serve traffic based on SNI/ |

**Comment by liggitt** [comment]
There are logical groupings of config, which is extremely difficult to see as flags sorted by name with no other structure. Structured apiserver config would make a lot of these clearer.

## TLS traffic to API server (serving certificates)
--tls-cert-file, --tls-private-key-file, --tls-sni-cert-key

## API server communication with other components:

### apiserver -> etcd
--etcd-cafile, --etcd-certfile, --etcd-keyfile

### apiserver -> kubelet
--kubelet-certificate-authority, --kubelet-client-certificate, --kubelet-client-key

### apiserver -> aggregated servers
--proxy-client-cert-file, --proxy-client-key-file

## Authentication methods to API server

### x509 client cert auth
--client-ca-file

### service account token auth (for verifying service JWT signatures)
--service-account-key-file

### auth proxy mTLS verification (for trusting incoming request with user headers)
--requestheader-client-ca-file

### oidc trust bundle (for fetching OIDC discovery doc)
--oidc-ca-file
