### ISSUE TITLE
GCECloud: Should Delete return NotFound error

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/kubernetes#54717]
Some Delete methods in GCECloud return resource NotFound errors while others mask it.

For ex: DeleteHealthCheck returns NotFound: https://github.com/kubernetes/kubernetes/blob/5cb1cccd403d9d9b9c24d04ee7092e1064523afa/pkg/cloudprovider/providers/gce/gce_healthchecks.go#L68 while DeleteTargetHttpProxy masks it:https://github.com/kubernetes/kubernetes/blob/5cb1cccd403d9d9b9c24d04ee7092e1064523afa/pkg/cloudprovider/providers/gce/gce_targetproxy.go#L58

I think we should be consistent in either all of them should return NotFound or none of them

cc @csbell @bowei @nicksardo @freehan @G-Harmon thoughts?

**Comment by nikhiljindal** [comment]
https://github.com/kubernetes/kubernetes/pull/54746 updates the cloud provider to consistently return NotFound errors for all resources.

**Comment by nicksardo** [comment]
+1 for returning NotFound to the consumer. I don't recall the specifics, but I believe I've hit a use case that required me to know whether it was deleted or not.

Agreed, each invocation of all changed funcs need to be checked for logic changes. Thankfully, it's easily fixed with a helper `ignoreNotFound(...)`

**Comment by nicksardo** [comment]
Fixed in #58436.
