### ISSUE TITLE
Pod started before hostname is updated in kube-dns

### ISSUE THREAD

**Issue by sisteming** [kubernetes/kubernetes#54798]
**Is this a BUG REPORT or FEATURE REQUEST?**: 

 /kind bug

**What happened**: 

Using statefulsets (and hence a headless service) to run MongoDB. The initial setup comes up correctly. When a pod is deleted, on GKE the new pod restarted will get a new IP address that has to be updated in kube-dns. There seems to be a race condition where the following scenario can happen:
- The pod process starts
- The new IP is not yet updated in kube-dns for that pod, which means that the hostname points to the old IP.

In that case, the process will show an error like below (or similar):
```
getaddrinfo("mongo-0.mongo") failed: Name or service not known
```

**What you expected to happen**:

The pod should get a new IP assigned and kube-dns should be updated before the process starts, so that any reference to its hostname can resolve to the correct IP address.

**How to reproduce it (as minimally and precisely as possible)**:

* Using headless service (https://github.com/sisteming/mongo-kube/blob/master/demo3/demo3-headlessService.yaml)
* Using statefulset (https://github.com/sisteming/mongo-kube/blob/master/demo3/demo3-statefulSet-2703.yaml)
* Deploy the statefulset following [mongo-kube demo3](https://github.com/sisteming/mongo-kube/tree/master/demo3):
* Delete pod mongo-0 so that it is recreatew, using a new IP
```
echo "-----------"
gdate +'%d/%m/%Y %H:%M:%S:%3N'
echo "-----------"
kubectl get pods -o wide
kubectl delete pod mongo-0 --now
echo "..........."
sleep 15
echo "****"
gdate +'%d/%m/%Y %H:%M:%S:%3N'
echo "****"
kubectl get pods -o wide
echo "****"
gdate +'%d/%m/%Y %H:%M:%S:%3N'
echo "****"
#kubectl describe pod mongo-0
kubectl describe service mongo
echo "****"
gdate +'%d/%m/%Y %H:%M:%S:%3N'
echo "****"
kubectl run mm --image=busybox -i -t --rm --restart=OnFailure -- nslookup mongo-0.mongo 
echo "****"
gdate +'%d/%m/%Y %H:%M:%S:%3N'
echo "****"
kubectl exec -it mongo-1 ping mongo-0.mongo
echo "****"
gdate +'%d/%m/%Y %H:%M:%S:%3N'
echo "****"
kubectl exec -it mongo-0 more /data/db/mongod.log 
echo "-----------"
```
* Check the logs in mongo-0: this is not deterministic but it is very likely that the logs will show an error like `no route to host` or `getaddrinfo("mongo-0.mongo") failed: Name or service not known`.

**Anything else we need to know?**:

I have been reviewing quite a few issues and posts on this type of behaviour. From now, my hypothesis about possible ways to solve this are:
- Avoid using a new IP address.
- Reduce time from DNS.
- Add a delay when starting the container process.
- Add readinessProbe and livenessProbe.

I believe this might be just an implementation issue or a bug specific to stateful set for specific applications. This seems to occur on Google Container Engine (where a new IP address is used for the pod restarted) and not on minikube (where IP addresses are re-used for the pod being restarted).

**Environment**:
- Kubernetes version (use `kubectl version`):
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.5", GitCommit:"17d7182a7ccbb167074be7a87f0a68bd00d58d97", GitTreeState:"clean", BuildDate:"2017-08-31T09:14:02Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.6-gke.1", GitCommit:"407dbfe965f3de06b332cc22d2eb1ca07fb4d3fb", GitTreeState:"clean", BuildDate:"2017-09-27T21:21:34Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration:
Google Container Engine only (in minikube the IP address is re-used so this issue does not occur).

- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by sisteming** [comment]
@kubernetes/sig-network

**Comment by phsiao** [comment]
I would have assumed that DNS entry for mongo-0 be deleted as the pod got deleted, so the second error message `getaddrinfo("mongo-0.mongo") failed: Name or service not known` makes sense.

Does your resolver cache responses?

**Comment by stszap** [comment]
I know this is old, but just for the sake of others who may face the same problem. Using the full service names for replica set config solves this for me (e.g. "mongo-0.mongo.default.svc.cluster.local" instead of just "mongo-0.mongo") because the full name is added to /etc/hosts by kubernetes. I'm not 100% sure if it completely eliminates the possibility of race conditions with dns names (when I used rancher I saw sometimes that /etc/hosts or /etc/reslov.conf only get populated after entrypoint starts). 

I also tried to use a script to delay mongod start until it's own dns name becomes resolvable, but dns requests are distributed between different kube-dns/coredns pods (I think) and sometimes dns request from the test script may go to a dns server that already "knows" the new ip, but dns request from mongod itself may go to another one which doesn't.

I use k8s 1.11.1 with coredns 1.2.0 and weave-net 2.3.0

**Comment by chenmin1992** [comment]
@stszap I face same issue now, full domain name is surely added to /etc/hosts, but the other pods' are not added to /etc/hosts, still need reliable dns resolving before pod start.

did you resolve this problem?

**Comment by stszap** [comment]
@chenmin1992 I no longer work on the project where we were running mongo cluster on k8s, but as far as I remember the problem was that mongod process just hangs if it can't resolve it's own hostname on the first try. For other replicaset members it just keeps trying so it's ok if dns server doesn't update for a while for them. Actually, I think that an application should be more robust and keep trying or just crash and let k8s restart it. Sorry, but I'm not aware of a method to delay a pod start before dns server update records for some other pods.
