### ISSUE TITLE
kubelet should run CNI plugins as network=host containers

### ISSUE THREAD

**Issue by anguslees** [kubernetes/kubernetes#54836]
/kind feature

Currently CNI plugins need to be "manually" distributed and installed onto the host filesystem, and hope they match the target filesystem's ABI, etc so that they can eventually be executed by kubelet.  We already have a much more sophisticated mechanism for managing all of that - containers!

We should run CNI plugins *as containers* in the host network namespace.  That way they can be fetched on demand (assuming we know the image name), there are no library/static executable hassles since they will come with their own rootfs, we have a good answer to versioning / garbage collection, etc.

**Comment by cmluciano** [comment]
Do you have a request for anything beyond examples like https://kubernetes.io/docs/tasks/administer-cluster/calico-network-policy/ or https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/#pod-network ?

I think many CNI plugin maintainers are already distributing their software in containers.

**Comment by anguslees** [comment]
> I think many CNI plugin maintainers are already distributing their software in containers.

Yep, but these are "installer" containers, that copy binaries onto the host filesystem - because kubelet currently just uses naive `exec()` and needs host filesystem executables.  I'm suggesting we modify kubelet to run plugins as containers directly and avoid this need to go via the host filesystem at all.

**Comment by cmluciano** [comment]
cc @kubernetes/sig-network-feature-requests @kubernetes/sig-node-feature-requests 

cc some CNI devs:
@squeed 
@caseydavenport 
@bboreham 
@dcbw

**Comment by squeed** [comment]
This is a fine idea. Some interesting issues:

1. The "installer" sidecars copy both the binaries and the CNI configuration file. So there would still need to be an installer until we clean up how the kubelet picks which CNI configuration to use.
2. The plugins need access to `/var/run/netns`, which will need to be a recursive bind mount.
3. CNI plugins tend to "delegate" to other plugins. This includes delegating to a separate IPAM plugin, or even delegating to the `ptp` plugin. The administrator would be responsible for packaging all plugins in a single container. Chained plugins (conflists) need not be packaged together, since the runtime (libcni) is responsible for executing them.
4. Plugins often need to share a state file (e.g. Flannel) or unix socket (cni dhcp). So the administrator needs to provide a directory that is bind-mounted in to a network daemonset *and* the CNI plugin.
5. Plugins also may maintain their own state on disk (e.g. host-local IPAM) that must persist between invocations
6. Plugins should be able to be executed in parallel.

**Comment by thockin** [comment]
This is too high a coupling to a particular container runtime.  If you had a heavier runtime, like Hyper, you might not be able to do what you want.  I'd prefer to make network drivers be daemons, like all the other plugin mechanisms have become.  All you need is a network endpoint, even a UNIX socket.  I'm going to write that up separately.
