### ISSUE TITLE
kube-dns crashloopbackoff after flannel/weave install

### ISSUE THREAD

**Issue by kumarganesh2814** [kubernetes/kubernetes#54910]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

**What happened**:
$ sudo kubeadm reset
$ sudo systemctl restart kubelet.service
$ sudo kubeadm init --pod-network-cidr=10.244.0.0/16
$ kubectl create -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
$ kubectl get pod --all-namespaces
kube-system   kube-dns-545bc4bfd4-jp5kf                                                 2/3       RunContainerError   1          1m

Issue on RHEL 7.4 for kube dns
Failed 
kubelet, ec2bcf.compute-xxxxxx.xxxxx.internal  
Error: failed to start container "kubedns": Error response from daemon: oci runtime error: container_linux.go:262: 
starting container process caused "process_linux.go:261: 
applying cgroup configuration for process caused \"No such device or address\""

**What you expected to happen**:
kube-dns should be running fine
**How to reproduce it (as minimally and precisely as possible)**:
ON RHEL 7.4 Execute below 

$ sudo kubeadm reset
$ sudo systemctl restart kubelet.service
$ sudo kubeadm init --pod-network-cidr=10.244.0.0/16
$ kubectl create -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
$ kubectl get pod --all-namespaces

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):kubectl/kubeadm version v1.8.1
- Cloud provider or hardware configuration: 4 Intel(R) Xeon(R) CPU E5-2699 v3 @ 2.30GHz /16 GB Mem
- OS (e.g. from /etc/os-release):Red Hat Enterprise Linux Server release 7.4 (Maipo)
- Kernel (e.g. `uname -a`):4.1.12-103.7.3.el7uek.x86_64
- Install tools:
- Others:

**Comment by cmluciano** [comment]
This seems related to the CNI tests. Can you try the same with 1.8.2 ?

**Comment by donutloop** [comment]
The same issue here

kubeadm version: &version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.2", GitCommit:"bdaeafa71f6c7c04636251031f93464384d54963", GitTreeState:"clean", BuildDate:"2017-10-24T19:38:10Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/arm"}

**Comment by cookeem** [comment]
I meet the same problem when I use v1.8.2, finally I figured out that can not use`--cgroup-driver=systemd`, it must use cgroupfs!

- Set the docker daemon to use cgroupfs:
```
cat << EOF > /etc/docker/daemon.json
{
  "exec-opts": ["native.cgroupdriver=cgroupfs"]
}
EOF
```

- Set kubelet use cgroupfs too:
```
$ vi /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
#Environment="KUBELET_CGROUP_ARGS=--cgroup-driver=systemd"
Environment="KUBELET_CGROUP_ARGS=--cgroup-driver=cgroupfs"
```
- Reload daemon setting then restart kubelet and docker
```
systemctl daemon-reload && systemctl restart kubelet docker 
```

Everything works great!
```
kubectl get pods --all-namespaces
NAMESPACE     NAME                                  READY     STATUS    RESTARTS   AGE
kube-system   etcd-cookeem.com                      1/1       Running   2          36m
kube-system   kube-apiserver-cookeem.com            1/1       Running   2          36m
kube-system   kube-controller-manager-cookeem.com   1/1       Running   2          36m
kube-system   kube-dns-7465b7fc85-tfzbj             3/3       Running   27         32m
kube-system   kube-flannel-ds-fjsqb                 1/1       Running   2          33m
kube-system   kube-proxy-54wgw                      1/1       Running   2          37m
kube-system   kube-scheduler-cookeem.com            1/1       Running   2          36m
```

**Comment by llxxbb** [comment]
@cookeem it works! The command "kubeadm join" on the other nodes run ok, but "kubectl get nodes" can't find them!

**Comment by kumarganesh2814** [comment]
@cookeem and Others in Group 
Thanks for instruction are helpful to me 
So what I did here is enable cgroupfs on both Docker and Kubelet then restart whole cluster again now its looks fine , Also this is case with RHEL only on CentOS systemd works fine but yeah it has to be same for kubelet and docker deamon.

@llxxbb Have you setup KUBECONFIG var in env 

 env |grep KUBE
KUBECONFIG=${HOME}/admin.conf

you need to copy same file admin.conf from Master to nodes then set KUBECONFIG
export KUBECONFIG=${HOME}/admin.conf

Add into bash_profile so it load up everytime you login

Ex:
From Mater Node
scp /etc/kubernetes/admin.conf user@worke-node:/home/user/
Then on Worker Node
export KUBECONFIG=${HOME}/admin.conf

It not working still check issues in /var/log/messeage 

Also check kubelet status on Worker Node 

Best Regards
Ganesh

**Comment by iramsey85** [comment]
Having a similar issue installing kubernetes on a raspberry pi cluster (Hypriot image). After installing Flannel on the master and creating the pod network, my kube-dns pod gives the CrashLoopBackOff error.

flannel installation commands:
1. $ curl -sSL https://rawgit.com/coreos/flannel/v0.7.1/Documentation/kube-flannel-rbac.yml | kubectl create -f -
2. $ curl -sSL https://rawgit.com/coreos/flannel/v0.7.1/Documentation/kube-flannel.yml | sed "s/amd64/arm/g" | kubectl create -f -


partial output from kubectl get po --all-namepaces

Namespace	Name		  Ready	Running			     Restarts
kube-system	kube-dns-###	  2/3	         CrashLoopBackOff	      35

all other services running fine.

**Comment by kumarganesh2814** [comment]
@iramsey85 

Can you Please see /var/log/message log and also check kubelet log

systemctl status kubelet -l

Check there is no firewall issue between Master Node and Worker Node

Check iptable 

try turning off firewall and drop rule which may close connectivity 

But best solution would be on basis of error which you are getting, so check deamon log at /var/lib/messeges and systemctl status kubelet -l

Best Regards
Ganesh

**Comment by Ascendance** [comment]
Very disappointing as weave net worked for so long without problems. Does Calico work?

**Comment by kumarganesh2814** [comment]
I think we can close this issue for now.

For Kube dns mostly issue are kubelet and docker not in sync i.e. check kubelet and docker using same cgroup driver

No earlier Install mess up things 

Issue : kube-dns crashloopbackoff after flannel/weave install
Solution:
We can not use--cgroup-driver=systemd, it must use cgroupfs!
Set the docker daemon to use cgroupfs:
cat << EOF > /etc/docker/daemon.json
{
  "exec-opts": ["native.cgroupdriver=cgroupfs"]
}
EOF
Set kubelet use cgroupfs too:
$ vi /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
#Environment="KUBELET_CGROUP_ARGS=--cgroup-driver=systemd"
Environment="KUBELET_CGROUP_ARGS=--cgroup-driver=cgroupfs"
Reload daemon setting then restart kubelet and docker
systemctl daemon-reload && systemctl restart kubelet docker

**Comment by XinhaiWang** [comment]
I follow the instruction below in order to fix kube-dns crashloopbackoff error. But after changing the configuration, I got The connection to the server 10.10.80.105:6443 was refused - did you specify the right host or port?

docker log 
`
Jun 01 10:36:25 shawujing dockerd[18901]: time="2018-06-01T10:36:25.335825435+08:00" level=warning msg="failed to retrieve docker-runc version: exec: \"docker-runc\": executable file not found in $PATH"
Jun 01 10:36:25 shawujing dockerd[18901]: time="2018-06-01T10:36:25.335875071+08:00" level=warning msg="failed to retrieve docker-init version"
Jun 01 10:36:25 shawujing dockerd[18901]: time="2018-06-01T10:36:25.370822005+08:00" level=warning msg="failed to retrieve docker-runc version: exec: \"docker-runc\": executable file not found in $PATH"
Jun 01 10:36:25 shawujing dockerd[18901]: time="2018-06-01T10:36:25.370882954+08:00" level=warning msg="failed to retrieve docker-init version"
Jun 01 10:36:35 shawujing dockerd[18901]: time="2018-06-01T10:36:35.808379963+08:00" level=warning msg="failed to retrieve docker-runc version: exec: \"docker-runc\": executable file not found in $PATH"
Jun 01 10:36:35 shawujing dockerd[18901]: time="2018-06-01T10:36:35.808433618+08:00" level=warning msg="failed to retrieve docker-init version"
Jun 01 10:36:35 shawujing dockerd[18901]: time="2018-06-01T10:36:35.836425716+08:00" level=warning msg="failed to retrieve docker-runc version: exec: \"docker-runc\": executable file not found in $PATH"
Jun 01 10:36:35 shawujing dockerd[18901]: time="2018-06-01T10:36:35.836474993+08:00" level=warning msg="failed to retrieve docker-init version"
Jun 01 10:36:35 shawujing dockerd[18901]: time="2018-06-01T10:36:35.867067726+08:00" level=warning msg="failed to retrieve docker-runc version: exec: \"docker-runc\": executable file not found in $PATH"
Jun 01 10:36:35 shawujing dockerd[18901]: time="2018-06-01T10:36:35.867125629+08:00" level=warning msg="failed to retrieve docker-init version"
Hint: Some lines were ellipsized, use -l to show in full.
`
