### ISSUE TITLE
controller-manager crash loops if gc controller doesn't have access to extension apis

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/kubernetes#55022]
```
E1102 20:08:46.999099       5 controllermanager.go:480] Error starting "garbagecollector"
F1102 20:08:46.999145       5 controllermanager.go:155] error starting controllers: failed to get supported resources from server: unable to retrieve the complete list of server APIs: identity.k8s.io/v1alpha1: forbidden: User "system:serviceaccount:kube-system:generic-garbage-collector" cannot get path "/apis/identity.k8s.io/v1alpha1"
```

This is a fatal error. Is this the expected behavior?

/sig auth
/sig api-machinery

@kubernetes/sig-api-machinery-bugs

**Comment by ironcladlou** [comment]
The GC is currently treating all discovery client errors as fatal to discovery. The discovery client may (as in this case) return the partial discovery list as well as an error list in a `ErrGroupDiscoveryFailed` error. I think in these cases the GC could use whatever it was able to get from discovery, log warnings for the failures, and move on. If the particular group failure isn't transient (i.e. the GC will probably never have access to the group), it might be spammy, but that seems preferable to just falling over.

/cc @caesarxuchao

**Comment by caesarxuchao** [comment]
Agree in general, though we might want to make sure all the native k8s groups are successfully discovered, otherwise it will break core functionalities of the cluster.

**Comment by ironcladlou** [comment]
@caesarxuchao 
>Agree in general, though we might want to make sure all the native k8s groups are successfully discovered, otherwise it will break core functionalities of the cluster.

Good idea. Maybe adding in a hard-coded "required" group list to validate against or something.

**Comment by liggitt** [comment]
> Agree in general, though we might want to make sure all the native k8s groups are successfully discovered, otherwise it will break core functionalities of the cluster

GC shouldn't distinguish between native and non-native... GC can make some progress even in the face of discovery errors, but cannot successfully complete orphan or foreground deletion operations until it has successfully discovered and has a complete graph.

**Comment by justinsb** [comment]
So I hit this today after a master restart with an aggregated apiserver registered.  The aggregated apiserver runs as a daemonset on the masters, which I think needs KCM to schedule a node.  But KCM exits on start because of this error.

I don't think this would be different on a deployment either, in the case of a full cluster power-off and recovery.

The only way I could recover was to directly delete my apiservice objects and recreate them once KCM was up.

**Comment by justinsb** [comment]
So I think that k-c-m is a bundling of various logically separate processes into a single process, largely as an optimization.  I think we should consider whether any single k-c-m controller should be able to stop all of k-c-m: it doesn't make logical sense to me to do so.  And if we say "ah, but controller X is critically important", then what happens when half our controllers are run out of process and are _not_ stopped? 

I propose instead all controllers in k-c-m should not exit the process, but should self-restart, with a delay (and possibly backoff).  Yes, this is recreating the kubelet backoff, but that's what we get for bundling them all into one uber-jar :-)

We should probably also randomize the start order of the controllers to avoid any assumptions there.

cc @kubernetes/sig-architecture-bugs

**Comment by mbohlool** [comment]
cc @mml @cheftako

**Comment by smarterclayton** [comment]
None of the controller manager loops should be exiting the process post fatal.  Both namespace controller and GC have to deal with partial discovery (and there will be others in the future), so they definitely have to converge.

**Comment by justinsb** [comment]
Which sig owns k-c-m though?

**Comment by bgrant0607** [comment]
API machinery owns the binary and controller libraries (informers, etc.).

**Comment by bgrant0607** [comment]
Recovery and restart sounds like a good idea. We need to ensure adequate monitoring signals are emitted to trigger alerts, as well as log entries for debugging.

**Comment by lavalamp** [comment]
> GC shouldn't distinguish between native and non-native

Agree, GC must have access to everything.

**Comment by lavalamp** [comment]
> We should probably also randomize the start order of the controllers to avoid any assumptions there.

That sounds like a recipe for occasional disaster orderings. Maybe in tests it would be OK. But we *must* understand any dependencies or we can't be sure we can make a cluster that will bootstrap. See: https://github.com/kubernetes/kubernetes/issues/54522. We need to work out the "run level" of each individual controller. We should probably consider breaking controller manager apart by run level, or having it at least start the controllers ordered by run level.

**Comment by lavalamp** [comment]
>  I think in these cases the GC could use whatever it was able to get from discovery, log warnings for the failures, and move on.

This, and retry again in the future. But I think it already does that, thanks to you, actually. @ironcladlou do you have time to make this change? I can look around here when more people get in.

**Comment by brendanburns** [comment]
I'd like to argue really strongly against run levels. That's a small step
away from upstartd style dependencies and state machines. Far better to
make every controller atomic and capable of handling uncertain/unknown
situations (with appropriate logging, of course)

Brendan

**Comment by liggitt** [comment]
>> We should probably also randomize the start order of the controllers to avoid any assumptions there.
> 
> That sounds like a recipe for occasional disaster orderings.

This is already done. There are two controllers run first in order to provide clients/credentials to the others, then all other controllers are started out of a map of controllerName->startFunc

**Comment by liggitt** [comment]
Agree that I don't want to introduce additional blocking dependencies, controller loops should run/recover independently. The trick is surfacing health and actually recovering per controller loop

**Comment by deads2k** [comment]
> That sounds like a recipe for occasional disaster orderings.

We do this already.  It was part of the initial pull (multiple releases ago) to ensure that trick dependencies would be caught.

**Comment by lavalamp** [comment]
haha, OK :)

> I'd like to argue really strongly against run levels.

The problem is that some items (webhooks) fail closed, which breaks the cluster if the webhook service is not available. We have to make sure that starting the webhook service will work when the webhook is not around. We went to the idea of runlevels because that reduces the dependency DAG to something manageable/understandable.

**Comment by lavalamp** [comment]
@ironcladlou says he has time to make a fix.

**Comment by smarterclayton** [comment]
Things that can fail a cluster closed right now:

1. web hook authorizers
2. web hook authenticators
3. web hook admission
4. initializers
5. api extensions that are required by a core controller (intentionally or accidentally), like GC and namespace
6. scheduler and daemon set controller for self hosting

I think there are a few more, but the list is growing.

**Comment by lavalamp** [comment]
Filed #55271 to try and prevent more instances of this class of failure.

**Comment by mumoshu** [comment]
I have a seemingly related issue to this [in kube-aws](https://github.com/kubernetes-incubator/kube-aws/issues/1039#issuecomment-348978375).
The surface error message isn't the same, but one source of problem was controller-manager.

In nutshell, apiserver was getting super slow to serve custom metrics API due to missing route to metrics-server, which resulted in controller-manager to fall into a crash-loopback, which then resulted in our daemonset-backed kube-proxy pods never created, keeping apiserver super slow.

For me, it looks like enhancing either apiserver or controller-manager would work - apiserver shouldn't get super slow when only one of apiservice is failing, while controller-manager shouldn't fail when only the custom metrics API is failing.

Would this really relate to our issue, or should I file an another issue?

**Comment by mumoshu** [comment]
For apiserver part of problem, probably https://github.com/kubernetes/kubernetes/issues/56430 is related.
