### ISSUE TITLE
Kubelet does not delete evicted pods

### ISSUE THREAD

**Issue by rfranzke** [kubernetes/kubernetes#55051]
/kind feature

**What happened**:
Kubelet has evicted pods due to disk pressure. Eventually, the disk pressure went away and the pods were scheduled and started again, but the evicted pods remained in the list of pods (`kubectl get pod --show-all`).

**What you expected to happen**:
Wouldn't it be better if the kubelet would have deleted those evicted pods? The expected behaviour would therefore be to not see the evicted pods anymore, i.e. that they get deleted.

**How to reproduce it (as minimally and precisely as possible)**:
Start kubelet with `--eviction-hard` and `--eviction-soft` with high thresholds or fill up the disk of a worker node.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.8.2
- Cloud provider or hardware configuration: AWS
- OS (e.g. from /etc/os-release): Container Linux 1465.7.0 (Ladybug)
- Kernel (e.g. `uname -a`): 4.12.10-coreos

**Comment by felixPG** [comment]
Evicted pods in 1.7.5 are a madness, the deletion of those pods are delayed by days!!!!, for example, I have a pod since 17 days was evicted an appear in the pod list:

mynamespace nginxrepo-2549817493-0p91t                                     0/1       Evicted             0          17d
mynamespace linting-umbrellabird-monocular-api                            0/1       Evicted             0          17d

In the case of nginxrepo, the deployment does not exist anymore, but the pods are present in the list of pods as evicted!!!

Also delete pods that does not match node selector criteria:

nfs-3970785943-5rnn7          0/2       MatchNodeSelector   0          17d

**After 17 days the pod appear in the list!!**. This behavior affect for example in Grafana, because the pods appear in the list of available pods for monitoring, and of course, are evicted!!.

Regards

**Comment by felixPG** [comment]
Thank you @rfranzke

**Comment by liggitt** [comment]
is this a duplicate of https://github.com/kubernetes/kubernetes/issues/54525

from https://github.com/kubernetes/kubernetes/issues/54525#issuecomment-340035375 it sounds like this is intentional, though I'm not sure what is expected to clean up pods in this case

**Comment by yujuhong** [comment]
> though I'm not sure what is expected to clean up pods in this case

The PodGCController in the controller manager?

**Comment by krallistic** [comment]
A quick workaround we use is to delete all evicted pods manually after an incident:
`
kubectl get pods --all-namespaces -ojson | jq -r '.items[] | select(.status.reason!=null) | select(.status.reason | contains("Evicted")) | .metadata.name + " " +  .metadata.namespace'  |   xargs -n2 -l bash -c 'kubectl delete pods $0 --namespace=$1'
`

**Comment by felixPG** [comment]
thank you @krallistic, I apply your workaround as cronjob a long time ago but is not a right way!

**Comment by kabakaev** [comment]
I suppose, this issue can be closed, because the evicted pods deletion can be controlled through settings in kube-controller-manager.

For those k8s users who hit the kube-apiserver or etcd performance issues due to too many evicted pods, i would recommend updating the kube-controller-manager config to set `--terminated-pod-gc-threshold 100` or similar small value. The default GC threshold is 12500, which is too high for most etcd installations. Reading 12500 pod records from etcd takes seconds to complete.

Also ask yourself why are there so many evicted pods? Maybe your kube-scheduler keeps scheduling pods on a node which already reports DiskPressure or MemoryPressure? This could be the case if the kube-scheduler is configured with a custom `--policy-config-file` which has no `CheckNodeMemoryPressure` or `CheckNodeDiskPressure` in the list of policy predicates.

```
$ kube-controller-manager --help 2>&1|grep terminated
      --terminated-pod-gc-threshold int32                                 Number of terminated pods that can exist before the terminated pod garbage collector starts deleting terminated pods. If <= 0, the terminated pod garbage collector is disabled. (default 12500)
```

**Comment by rfranzke** [comment]
Thanks @kabakaev for pointing that out. Didn't know that this can be configured. Let's close the ticket then.

**Comment by so0k** [comment]
@kabakaev - wouldn't pod gc cover all pods (including terminated pods for other reasons) - what if we just want evicted pods to be cleaned up periodically?

**Comment by serg060606** [comment]
the issue still opened, there no reply for @so0k commented on Feb 27, 2018

**Comment by shelbaz** [comment]
I created a cron job using a Yaml file with this config (need to fix the formatting, check https://kubernetes.io/docs/tasks/job/automated-tasks-with-cron-jobs/) :
********************************************************************************
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: delete-failed-pods
spec:
  schedule: "*/30 * * * *"
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: kubectl-runner
            image: wernight/kubectl
            command: ["sh", "-c", "kubectl get pods --all-namespaces --field-selector 'status.phase==Failed' -o json | kubectl delete -f -"]
          restartPolicy: OnFailure


****************************************************************************

Create the task with ` kubectl create -f "PATH_TO_cronjob.yaml" `

Check the status of the task with `kubectl get cronjob delete-failed-pods `

Delete the task with `delete cronjob delete-failed-pods`

**Comment by andyxning** [comment]
Statefulset will auto delete Failed pod https://github.com/kubernetes/kubernetes/blob/52eea971c57580c6b1b74f0a12bf9cc6083a4d6b/pkg/controller/statefulset/stateful_set_control.go#L386. For now Deployment and DaemonSet do not do this.

**Comment by gosoon** [comment]
Why does kubernetes keep evicted pod, and what is the purpose of this design？

**Comment by webersebastien** [comment]
When I have too many Evicted pods I use the following command: ```kubectl get pods -A | grep Evicted | awk '{print $2 " --namespace=" $1}' | xargs kubectl delete pod --force --grace-period=0```
