### ISSUE TITLE
Force detaches on EBS can leave stale entry in /proc/mounts

### ISSUE THREAD

**Issue by gnufied** [kubernetes/kubernetes#55074]
Currently we perform detach of a mounted volume if volume failed to umount within 6 minutes of time window. 

We have noticed that in certain cases - a stale device entry like "/dev/xvdba" is left in `/proc/mounts` if volume was force detached. When this happens, the device is not shown in `lsblk` output but just a stale entry is left in `/proc/mounts`.

If this happens, next attach on same device (`/dev/xvdba`) although works and new volume is mounted but this new volume can never be successfully umounted because MountRef count will find more than one entry for device in mount table and it will not perform umount.

/sig storage
/sig aws

cc @kubernetes/sig-storage-bugs

**Comment by gnufied** [comment]
cc @kubernetes/sig-storage-pr-reviews

**Comment by jsafrane** [comment]
That's the reason we should not force detach volumes. Arbitrary 6 minute timeout is IMO wrong:

1. something deletes a pod
2. 
   * kubelet starts unmounting
   * a/d controller starts 6 minute timer
3. a/d controller detaches the volume after 6 minutes.

What makes us sure that 6 minutes are enough to stop and unmount a pod? kubelet may be perfectly working, it just takes longer time. At this point, we're 1) corrupting user data and 2) breaking AWS logic.

A/D controller should not detach volumes if kubelet is responsive. We can see that in `node.status.conditions["Ready"] == true`.

If a node becomes `Ready==false`, something in kubelet should taint the node "internally" (because API server may not be reachable) after X minutes and kubelet should evict kill pods that don't tolerate the taint. Something outside of the node (a controller?) must set the same taint on API server after the same X minutes so the same pods can be deleted from API server and be rescheduled elsewhere.

Only after X+Y minutes, A/D controller can detach the volumes, giving kubelet some time to unmount everything gracefully.

**Comment by jingxu97** [comment]
@gnufied @jsafrane maybe we should find some help working on this?
