### ISSUE TITLE
Better usability for the join token

### ISSUE THREAD

**Issue by 1605200517** [kubernetes/kubernetes#55108]
/kind feature
@kubernetes/sig-cli
**What happened**:
I have discovered that if it is not so easy to add new machines if you do not have original joun string output from kubeadm. "Is there a way to generate the whole join command? **I feel like I have to reset the entire cluster to be able to "reach" the magic string**" (c) @alexellis 

**What you expected to happen**:
Likewise in Docker Swarm, you can always tell the master to print a copy-pastable join string to add.. or assimilate? more machines.

Example input:

`kubeadm token string`

Example output:

`kubeadm join --token TOK MASTER_IP:6443 --discovery-token-ca-cert-hash sha256:HASH`

**Anything else we need to know?**:
You are awesome!

(Follow-up from: https://github.com/kubernetes/kubernetes/pull/41663)
@luxas  @mattmoyer  @jamiehannaford

**Comment by luxas** [comment]
Hi!

Thank you for filing this issue. We appreciate your interest in Kubernetes and kubeadm.
In order to make the kubernetes/kubernetes issue tracker more usable, we're routing issues to different repositories with different focuses.

I think this issue belongs in the kubeadm repository. Please move this issue to the [kubeadm repo tracker](https://github.com/kubernetes/kubeadm/issues) in order for the kubeadm team to be able to track this efficiently. If you disagree with my assessment of moving this issue, please speak up and/or reopen the issue. Finally, please try to reproduce the bug with the latest Kubernetes version, it might as well already have been fixed :)

Thank you and have a good day!

**Comment by 1605200517** [comment]
https://github.com/kubernetes/kubeadm/issues/519
