### ISSUE TITLE
Statefulset : CreateControllerRevision function bug

### ISSUE THREAD

**Issue by orainxiong** [kubernetes/kubernetes#55159]
**Is this a BUG REPORT**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug

**What happened**:

When a statefulset object is created, a lot of controllerrevisions are created at the same time.
the controllerrevisions have differenct hash value but the same Data.Raw.

**How to fix it**:

two controllerrevisions are seen as the same , when Controllerrevision.labels[ControllerRevisionHashLabel] , Controllerrevision.Data.Raw , Controllerrevision.Data.Object are strictly the same 

 // this line shoud be added to fix the bug
```
clone.Labels[ControllerRevisionHashLabel] = strconv.FormatInt(int64(hash), 10)
```

like below: 

```
func (rh *realHistory) CreateControllerRevision(parent metav1.Object, revision *apps.ControllerRevision, collisionCount *int32) (*apps.ControllerRevision, error) {
    if collisionCount == nil {
        return nil, fmt.Errorf("collisionCount should not be nil")
    }

    // Clone the input
    clone := revision.DeepCopy()

    // Continue to attempt to create the revision updating the name with a new hash on each iteration
    for {
        hash := HashControllerRevision(revision, collisionCount)
        // Update the revisions name and labels
        clone.Name = ControllerRevisionName(parent.GetName(), hash)
        clone.Labels[ControllerRevisionHashLabel] = strconv.FormatInt(int64(hash), 10)
        created, err := rh.client.AppsV1beta1().ControllerRevisions(parent.GetNamespace()).Create(clone)
        if errors.IsAlreadyExists(err) {
            *collisionCount++
            continue
        }
        return created, err
    }
}
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.7.8
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by wackxu** [comment]
I would help fix it

**Comment by janetkuo** [comment]
StatefulSet uses the following code to construct its history object (controllerrevision):
https://github.com/kubernetes/kubernetes/blob/296bc649241a20294da11000c6c6e82cca280c81/pkg/controller/history/controller_history.go#L250-L260

However, collisionCount shouldn't be blindly increased when there's name collision. Because controller uses a cache store, the name collision could be due to a controllerrevision created but not yet observed by the controller. 

The right way to handle it is to first check if the controllerrevision with the same name has the same content as the one we're going to create, like how DaemonSet controller handles it:

https://github.com/kubernetes/kubernetes/blob/296bc649241a20294da11000c6c6e82cca280c81/pkg/controller/daemon/update.go#L333-L366
