### ISSUE TITLE
[job failure] ci-kubernetes-test-go, ci-kubernetes-verify-master, pull-kubernetes-unit failing

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/kubernetes#55276]
/priority critical-urgent
/priority failing-test
/kind bug
@kubernetes/sig-testing-test-failures 

These are release-blocking
- https://k8s-testgrid.appspot.com/sig-release-master-blocking#test-go
- https://k8s-testgrid.appspot.com/sig-release-master-blocking#verify

This is blocking presubmits:
- https://k8s-testgrid.appspot.com/presubmits-kubernetes#pull-kubernetes-unit

Using test-go as an example:
- last good: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-test-go/11559
- first bad: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-test-go/11560
- the kubernetes commit range doesn't look like it should have caused this, so I suspect test-infra
- manual guess at suspect range based on infra-commit: https://github.com/kubernetes/test-infra/compare/3f126e390...e58e59703

/assign @BenTheElder

**Comment by BenTheElder** [comment]
will be fixed in https://github.com/kubernetes/test-infra/pull/5393

**Comment by BenTheElder** [comment]
the fix has been merged

**Comment by xiangpengzhao** [comment]
@BenTheElder will kubernetes/test-infra#5393 fix #55239?

**Comment by BenTheElder** [comment]
@xiangpengzhao I think not, that looks like flaking in the verify job trying to download packages

**Comment by BenTheElder** [comment]
Adding that we're now doing a number of tests over in bazel-test instead of unit, so failures may be observed there instead (xref: https://github.com/kubernetes/kubernetes/pull/55279)

This job is now in master and 1.9 blocking so that we don't ignore all of the unit tests that were in the now increasingly poorly name `*-kubernetes-unit` job which does basically anything but unit tests 🤷‍♂️ , but this also means we've just regained a failing job..

**Comment by spiffxp** [comment]
/remove-priority failing-test
/close
I should have closed this a while ago, all the aforementioned jobs are passing
