### ISSUE TITLE
Eliminate test/OWNERS

### ISSUE THREAD

**Issue by fejta** [kubernetes/kubernetes#55330]
We should move things into test/FOO/OWNERS instead

https://github.com/kubernetes/kubernetes/pull/55319#issuecomment-342905734

/assign
/cc @spiffxp

**Comment by spiffxp** [comment]
/priority important-soon
/sig testing
I think it's on us and anyone else in test/OWNERS to get out of this mess, and we can tag with other sigs if there are dirs in here they ought to be owning but aren't

/sig scalability
I think @shyamjvs has a few specific dirs he could be in instead of test/OWNERS
