### ISSUE TITLE
Add cpu limit for fluentd-gcp addon

### ISSUE THREAD

**Issue by crassirostris** [kubernetes/kubernetes#55416]
Currently CPU consumption is not capped, which can be problematic in some setups

**Comment by jonastl** [comment]
/remove-lifecycle stale
This is still relevant. If k8s back plane cluster components on the nodes are not resource constrained, user workload deployed to those nodes have zero guarantees and can make no assumptions regarding available resources _while they are executing_.

Mick's ticket is definitely something that warrants fixing, since we've been affected by this precise limitation ourselves in production.
