### ISSUE TITLE
sample-controller / apiextensions-apiserver / sample-apiserver / kube-aggregator rely on ./vendor/k8s.io/code-generator, do not have it

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#55535]
sample-controller relies on ./vendor/k8s.io/code-generator (https://github.com/kubernetes/sample-controller/blob/master/hack/update-codegen.sh)  but does not vendor it: (https://github.com/kubernetes/sample-controller/tree/master/vendor/k8s.io)

**Comment by justinsb** [comment]
@kubernetes/sig-api-machinery-bugs

**Comment by lavalamp** [comment]
Who owns this? Who made it?

**Comment by gregory-m** [comment]
I was involved in sample-controller.

Will fix it.

**Comment by lavalamp** [comment]
Thanks!

**Comment by gregory-m** [comment]
Here some conclusions after discussion in #sig-api-machinery:
1. Godeps doesn't explicit imports.
2. We can't create `foo.go` and import all needed generators because go can't import `main` package
3. For main repo we use `godep-save.sh` to workaround
4. `godep-save.sh` dosn't sport staging repos.
5. @sttts will release code-generators as docker image.

I think we just need to wait for docker image to be released and not introduce a lot code to workaround godep in staging repos.

**Comment by sttts** [comment]
Updated the title. We have many repos with the same issue. And "rely" means that you cannot regenerate the generated code. There is no Go import that is failing.

**Comment by justinsb** [comment]
Correct - the `hack/update-codegen.sh` script does not work.

**Comment by ncdc** [comment]
> @ncdc will release code-generators as docker image.

I don't have any time to work on this at the moment. Maybe after Kubecon.

**Comment by nikhita** [comment]
Looks like this has been fixed in https://github.com/kubernetes/publishing-bot/pull/35. :tada: 

> release code-generators as docker image.

Not official, but https://github.com/slok/kube-code-generator exists.
