### ISSUE TITLE
No e2e test for CRD watch (?)

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#55538]
I am suspicious that CRD watch is not working, but was unable to find e2e test coverage to persuade myself that it is working.

cf  #24441.

@kubernetes/sig-api-machinery-bugs

**Comment by justinsb** [comment]
(in particular, I'm looking for the update tests.)

**Comment by justinsb** [comment]
I think this was due to enabling protobuf, though it also failed in a curl for me, so something strange is happening.  (Maybe we have to _explicitly_ ask for json?)

**Comment by lavalamp** [comment]
@enisoc

**Comment by enisoc** [comment]
We test CRD watch in [kubectl tests](https://github.com/kubernetes/kubernetes/blob/d2153dff8e31fe0c7ad72bd58ccd55dd077a4a1e/hack/make-rules/test-cmd-util.sh#L1695-L1719) and in [apiextensions integration tests](https://github.com/kubernetes/kubernetes/blob/d2153dff8e31fe0c7ad72bd58ccd55dd077a4a1e/staging/src/k8s.io/apiextensions-apiserver/test/integration/basic_test.go#L105-L146), but not in [e2e](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/apimachinery/custom_resource_definition.go).

I agree we should add e2e tests as a requirement before GA, and also for the sake of defining compliance.

**Comment by sttts** [comment]
Are we talking about CRD or CR watch and protobuf? The later with protobuf obviously does not work, as commented.

**Comment by justinsb** [comment]
@sttts I'm not sure "obviously" is correct - list works, for example.  IIRC watch with protobuf just silently fails to do anything - it doesn't return an error.

And yes I mean CR watch :-)

**Comment by sttts** [comment]
@justinsb it should obviously not work with protobuf, but in the sense that the negotiating serializer switches to JSON if you offer it json and protobuf as alternatives. This seems to be broken.

**Comment by ayushpateria** [comment]
I'd like to take this up. I'm familiarising myself with the apiextension code base, please give me some time to come up with a PR :)

**Comment by nikhita** [comment]
We already have integration tests for this.

Is an e2e test really needed?

**Comment by enisoc** [comment]
I think we do need an e2e test for CRD watch (among other things) as a requirement for CRD going GA. The most pressing need is to define conformance (which only e2e tests can do). Currently we only test that you can create and delete a CRD, but we don't test that you can actually do anything with it:

https://github.com/kubernetes/kubernetes/blob/master/test/e2e/apimachinery/custom_resource_definition.go

We should expand the conformance (e2e) test for CRD to include checking that the custom resource gets installed and is usable, including watches.

If not for conformance, I think an e2e test for CRD watch would still be appropriate since it's an important end-user flow (a thing we expect users to do on purpose; not an edge case). For example, the apiextensions-apiserver integration test might miss problems that come from embedding into kube-apiserver.

Similarly, the kubectl tests are meant to test kubectl client functionality, not to protect against regressions on the server side. Someone might reasonably change those tests in a way that suits kubectl, without realizing that doing so could leave some server code untested at the e2e level. We also need the e2e test to make sure we honor the guarantees of the raw API, to ensure clients other than kubectl will work.

**Comment by sttts** [comment]
> I think we do need an e2e test for CRD watch (among other things) as a requirement for CRD going GA. The most pressing need is to define conformance (which only e2e tests can do). Currently we only test that you can create and delete a CRD, but we don't test that you can actually do anything with it:

For our developer purpose I would say that e2e tests are not needed when integration tests are in-place. We can even test with a real kube-apiserver including embdded into kube-apiserver if we want that.

With conformance tests @enisoc might have a point. Though I wonder where the line is between e2e and features we test in integration or unit tests only. We don't test all behaviour in e2e today, by far.

**Comment by nikhita** [comment]
Since this has the help-wanted label, adding some useful info for new contributors to get started:

**About CRDs**:

- If you are new to the Kubernetes API in general, I'd recommend reading the [API conventions](https://github.com/kubernetes/community/blob/master/contributors/devel/api-conventions.md) first.
- CustomResourceDefinition (CRD) is a way to extend the Kubernetes API. You can read more about it here: https://kubernetes.io/docs/tasks/access-kubernetes-api/extend-api-custom-resource-definitions/.
- If you'd like to do some additional reading about this, I had written something up during the time I did GSoC (shamless plug): https://nikhita.github.io/gsoc-kubernetes-making-customresources-more-awesome.

**About testing**:

- There are lots of integration tests for CRDs [here](https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io/apiextensions-apiserver/test/integration) and you can get a general idea about testing for CRDs and apiextensions-apiserver in general.
-  There is [one e2e test](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/apimachinery/custom_resource_definition.go) for CRDs. You can use this and other e2e tests to understand how to write them.
- [This doc](https://github.com/kubernetes/community/blob/master/contributors/devel/testing.md) contains useful information about how you can run tests.
- [This doc](https://github.com/kubernetes/community/blob/master/contributors/devel/e2e-tests.md) gives general info about e2e tests and [this doc](https://github.com/kubernetes/community/blob/master/contributors/devel/writing-good-e2e-tests.md) mentions tests about writing good e2e tests.

Also, you can ping me on Slack (I am @nikhita there) if you have further questions or need help! :)
