### ISSUE TITLE
Test "[sig-storage] Dynamic Provisioning DynamicProvisioner External should let an external dynamic provisioner create and delete persistent volumes [Slow]" fails at large scale

### ISSUE THREAD

**Issue by porridge** [kubernetes/kubernetes#55780]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug
/priority failing-test

**What happened**:

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-correctness/28

```
[sig-storage] Dynamic Provisioning DynamicProvisioner External should let an external dynamic provisioner create and delete persistent volumes [Slow] 6m25s
go run hack/e2e.go -v -test --test_args='--ginkgo.focus=\[sig\-storage\]\sDynamic\sProvisioning\sDynamicProvisioner\sExternal\sshould\slet\san\sexternal\sdynamic\sprovisioner\screate\sand\sdelete\spersistent\svolumes\s\[Slow\]$'
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/volume_provisioning.go:596
Expected error:
    <*errors.errorString | 0xc43e0fd420>: {
        s: "PersistentVolumeClaim pvc-9brzx not in phase Bound within 5m0s",
    }
    PersistentVolumeClaim pvc-9brzx not in phase Bound within 5m0s
not to have occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/volume_provisioning.go:89
```
@kubernetes/sig-storage-bugs please investigate ASAP, this is a release-blocking test group.

**Comment by porridge** [comment]
Umbrella issue - #55194

**Comment by msau42** [comment]
From the test log:
```
I1114 21:36:18.129] Nov 14 21:35:53.795: INFO: PersistentVolumeClaim pvc-9brzx found but phase is Lost instead of Bound.

I1114 21:36:18.132] Nov 14 21:35:56.068: INFO: At 2017-11-14 21:30:55 +0000 UTC - event for pvc-9brzx: {example.com/nfs external-provisioner-9dwpr 186218bb-c983-11e7-8162-0a580a53a403 } Provisioning: External provisioner is provisioning volume for claim "e2e-tests-volume-provisioning-vtd74/pvc-9brzx"
I1114 21:36:18.132] Nov 14 21:35:56.068: INFO: At 2017-11-14 21:30:55 +0000 UTC - event for pvc-9brzx: {example.com/nfs external-provisioner-9dwpr 186218bb-c983-11e7-8162-0a580a53a403 } ProvisioningSucceeded: Successfully provisioned volume pvc-18b37d42-c983-11e7-8959-42010a8e0002
I1114 21:36:18.132] Nov 14 21:35:56.068: INFO: At 2017-11-14 21:30:55 +0000 UTC - event for pvc-9brzx: {persistentvolume-controller } ClaimLost: Bound claim has lost its PersistentVolume. Data on the volume is lost!
```

kube-controller-manager.log only has this single message:
```
59244 I1114 21:30:55.090827       7 event.go:218] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"e2e-tests-volume-provisioning-vtd74", Name:"pvc-9brzx", UID:"18b37d42-c983-11e7-8959-42010a8e00      02", APIVersion:"v1", ResourceVersion:"1253067", FieldPath:""}): type: 'Warning' reason: 'ClaimLost' Bound claim has lost its PersistentVolume. Data on the volume is lost!
```

**Comment by msau42** [comment]
cc @jsafrane @wongma7

**Comment by wongma7** [comment]
thanks for those logs.

seems there's a race in the external provisioner...the kubernetes side appears to be working just fine, though I'm not 100% sure because unfortunately the pv controller isn't logging anything

apiserver.log:
I1114 21:30:55.070117       7 wrap.go:42] POST /api/v1/persistentvolumes: (9.545259ms) 201 [[nfs-provisioner/v0.0.0 (linux/amd64) kubernetes/$Format] 35.185.45.68:47384]
* provisioner creates PV

I1114 21:30:55.073207       7 wrap.go:42] POST /api/v1/namespaces/e2e-tests-volume-provisioning-vtd74/events: (2.074502ms) 201 [[nfs-provisioner/v0.0.0 (linux/amd64) kubernetes/$Format] 35.185.45.68:47384]
* provisioner posts ProvisioningSucceeded to PVC

I1114 21:30:55.086668       7 wrap.go:42] DELETE /api/v1/persistentvolumes/pvc-18b37d42-c983-11e7-8959-42010a8e0002: (3.533325ms) 200 [[nfs-provisioner/v0.0.0 (linux/amd64) kubernetes/$Format] 35.185.45.68:47384]
* provisioner immediately deletes the PV?!?! why? the volume should be in Available state

I1114 21:30:55.090516       7 wrap.go:42] PUT /api/v1/namespaces/e2e-tests-volume-provisioning-vtd74/persistentvolumeclaims/pvc-9brzx/status: (3.281342ms) 200 [[kube-controller-manager/v1.9.0 (linux/amd64) kubernetes/95b4312/system:serviceaccount:kube-system:persistent-volume-binder] [::1]:41876]
* PV controller updates claim to `Lost`

I1114 21:30:55.093306       7 wrap.go:42] POST /api/v1/namespaces/e2e-tests-volume-provisioning-vtd74/events: (2.119586ms) 201 [[kube-controller-manager/v1.9.0 (linux/amd64) kubernetes/95b4312/system:serviceaccount:kube-system:persistent-volume-binder] [::1]:41876]
* PV controller posts `Lost` event

Is there any way to get the pod logs? else I will need to modify the test to get the provisioner pod's logs to figure out why it would delete a PV right after creating it

**Comment by msau42** [comment]
I don't think pod logs are automatically collected.

**Comment by wongma7** [comment]
ok, I see

Here is my current theory for what happened, difficult to confirm without pv controller logs though
* PVC is created but not processed by PV controller and not added to its cache yet
* PV is added and processed by PV controller, this is possible since the PVC and PV queue are distinct (?)
  * Instead of going here https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/volume/persistentvolume/pv_controller.go#L530 and setting PV to Bound, the PV controller goes here https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/volume/persistentvolume/pv_controller.go#L489 because the claim is not in the cache and presumed deleted, and sets PV to Released
* Provisioner deletes PV because it is Released
* PV controller finally processes PVC and sets it to Lost

@jsafrane need your expertise.

Solution maybe is for external provisioners to leave volume.Spec.ClaimRef.UID blank.

**Comment by msau42** [comment]
The PV controller is supposed to set the annotation to signal to external provisioners that they can start provisioning:
https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/volume/persistentvolume/pv_controller.go#L1238

Does the external provisioner library wait for that annotation?

But I guess it's also possible that the user could create the PVC with the annotation already set.

**Comment by wongma7** [comment]
Oh yeah you are right!

The provisioner is supposed to wait for the annotation, but we do not wait atm, we simply fallthrough to checking claim.Class which is wrong
https://github.com/kubernetes-incubator/external-storage/blob/master/lib/controller/controller.go#L580

will fix.

**Comment by jsafrane** [comment]
> the PV controller goes here because the claim is not in the cache and presumed deleted, and sets PV to Released

That should not happen, the controller set the provisioning annotation so it *must* be in its cache...

**Comment by porridge** [comment]
/priority critical-urgent
this blocks #55194

**Comment by msau42** [comment]
@wongma7 was this fixed on the external provisioner side?

**Comment by porridge** [comment]
Ping?

**Comment by msau42** [comment]
@wongma7 looks like the external provisioner code still hasn't been fixed.  Do you plan on making that change soon?

**Comment by wongma7** [comment]
fix will be done today. I will merge https://github.com/kubernetes-incubator/external-storage/pull/521, update nfs-provisioner image, then update the test to point to the new image
