### ISSUE TITLE
framework.ConformanceIt() fails with "called with non-literal argument"

### ISSUE THREAD

**Issue by xiangpengzhao** [kubernetes/kubernetes#55949]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
Running conformance test and getting below error:
```
ERROR at test/e2e_node/runtime_conformance_test.go:316:29: framework.ConformanceIt() called with non-literal argument
```

ref: https://github.com/kubernetes/kubernetes/pull/54837#issuecomment-345091220

**What you expected to happen**:
The conformance test can be run successfully.

**How to reproduce it (as minimally and precisely as possible)**:
Below line is in a for loop.
https://github.com/kubernetes/kubernetes/blob/eff1a8463834c737da366b18cd7e65236e6a226e/test/e2e_node/runtime_conformance_test.go#L316

After changing it to `framework.ConformanceIt(testCase.description, func() {` and run `bazel test //test/conformance/...`, it throws the above error.

**Anything else we need to know?**:
If changing the above line to `framework.ConformanceIt("any literal string", func() {`, the tests pass.

/cc @mml 

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by mml** [comment]
This is intentional.  We perform analysis statically on source code and are trying to minimize the amount of go language knowledge we need (I don't want to end up writing a buggy go interpreter).  In order to document the individual cases properly with doc comments (see #52863) we need each conformance test to be a standalone call as well.  I think we need to restructure these case-oriented tests a bit when they are conformance tests.  Today we have something like this

```
cases := {...}
for _, c := range cases {
...
  framework.ConformanceIt(c.description, func() {...})
}
```

We need a way that makes it easy to create these tables but still declare each test on its own... How about something like the below?

```
type testCase struct{...}
cases := map[string]testCase{
  "foo": {...},
  "bar": {...},
}

func runThisTest(c testCase) {
...
}

// Special comment that describes case foo
framework.ConformanceIt("foo", runThisTest(cases["foo"]))

// Special comment that describes case bar
framework.ConformanceIt("bar", runThisTest(cases["bar"]))
```

It is a little more verbose, so I am open to finding easier ways to do this, but ultimately each test needs to be documented and named in such a way that it and its documentation can be identified statically.

**Comment by xiangpengzhao** [comment]
@mml SGTM. @Random-Liu @tallclair @vishh @derekwaynecarr @yujuhong as you folks are owners of the node e2e conformance tests, WDYT?

**Comment by xiangpengzhao** [comment]
cc @yanxuean
