### ISSUE TITLE
Devices are not re-used when paired with init containers

### ISSUE THREAD

**Issue by RenaudWasTaken** [kubernetes/kubernetes#56022]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug
/area hw-accelerators 

**What happened**:
In the context of the device plugin, when using init containers in your pod spec, the current behavior will  not reuse devices between init containers and regular containers.

This is problematic as Pod scheduling is currently wrong: 
[In the scheduler](https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/scheduler/algorithm/predicates/predicates.go#L550), the current predicate algorithm rightly assumes the maximum number of devices in use at one time is `max(NumDevices(Ctr1, Ctr2, ...), NumDevices(InitCtr1),  ...)`.

However, the pod predicate ran on the node is the sum of devices used by regular and init containers. Meaning that your pod can bounce back between the scheduler and a node infinitely.

Also given that many of the extended resources are typically more expensive that the built-in ones like CPU, Memory and Storage this bug has very real financial drawbacks in terms of resource usage (e.g: using 4 GPUs on a pod that only uses 2 GPUs at a time).

Furthermore, this unexpected behavior was caught during implementation (but we did not catch the scheduling implications) and decision was taken to ignore it for the first implementation. We need to document it for 1.9

**What you expected to happen**:
- Devices can be reused by Init Containers
- Correct resource accounting

In terms of the current behavior of the Allocate call to the device plugin, I'd expect the allocate call to be done before every Init containers start and once at the end of the last Init container (for regular containers).

/assign @jiayingz @vishh

**Comment by lichuqiang** [comment]
Yep, I realized the inconsistency between the predicate behavior of scheduler and that of node too. Having said that, considering we treat a pod as a whole when predicating currently, it's difficult to reuse the runtime informations between init containers and regular containers.
The real crux of the matter might be whether the scenario of requiring extended resources in init containers is common, if so, the issue should be addressed ASAP.

**Comment by resouer** [comment]
@RenaudWasTaken The current design to improve DP includes a reconciliation in admit phase of Pod, it should be able to fix Allocate call for `initContainer`

**Comment by RenaudWasTaken** [comment]
@resouer can you point me to said design ?
I'm not sure that the Allocate call for init containers is planned to be fixed as described.

**Comment by vikaschoudhary16** [comment]
@resouer 
> reconciliation in admit phase of Pod

Is it possible to add few more words in explanation?

**Comment by RenaudWasTaken** [comment]
@vikaschoudhary16 PR that added the mentioned change: https://github.com/kubernetes/kubernetes/pull/54488

Code in question is here: https://github.com/kubernetes/kubernetes/blob/40e7101844fd4cce86e3c6df3f7d093d74337418/pkg/kubelet/cm/deviceplugin/device_plugin_handler.go#L251

**Comment by vikaschoudhary16** [comment]
@RenaudWasTaken @lichuqiang 

> However, the pod predicate ran on the node is the sum of devices used by regular and init containers. Meaning that your pod can bounce back between the scheduler and a node infinitely.

Above looks incorrect description. Predicate that run on the scheduler and on the node is same i.e max(init, regular). Pod admission will pass at the node. Problem might happen at allocation where allocated resources is not the max but the sum of (init, regular). And in that case, pod would hang there in fail state rather 'bounce back infinitely'.

**Comment by lichuqiang** [comment]
>Problem might happen at allocation where allocated resources is not the max but the sum of (init, regular). And in that case, pod would hang there in fail state rather 'bounce back infinitely'.

Absolutely correct, sorry to make you confused, I think Renaud name it `predicate`  mainly bacause the allocate func is supposed to be called during the predicate phase, that is, passed in [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/lifecycle/predicate.go#L71) as a part of PredicateAdmitHandler.

**Comment by resouer** [comment]
@vikaschoudhary16 @RenaudWasTaken The original idea was onced listed in #53497 as a sub-task:
> Allocate devices during pod creation rather than during every container (re)start [Owner TBD]

But now it's removed (I don't know why). I believe the original idea was:

1. Handle device resources allocation during pod admit phase. This comment https://github.com/kubernetes/kubernetes/pull/51895#issuecomment-336995772 is related
2. Call Allocate() if needed during reconcile in 1 and cache these devices info 
3. Use cached devices later during container create phase

**Comment by lichuqiang** [comment]
>Handle device resources allocation during pod admit phase. This comment #51895 (comment) is related
Call Allocate() if needed during reconcile in 1 and cache these devices info
Use cached devices later during container create phase

@resouer Current code behaviors exactly as you described, but to address the issue, the key point might be  to decide which devices of init  containers could be reused by which regular containers, and generate  cache accordingly in step2, when creating containers, we simply fetch runtime info from cache.

**Comment by jiayingz** [comment]
Thanks a lot for filing this issue, @RenaudWasTaken 

I think for 1.9, we probably want to list this as a known issue and may advise people to not request gpu resources in init containers. We can target to fix this problem in 1.10.

**Comment by RenaudWasTaken** [comment]
> I think for 1.9, we probably want to list this as a known issue and may advise people to not request gpu resources in init containers.

Agreed
We don't have a clear solution for this tough. It's pretty clear to me that device resources allocation during pod admit phase is not the right model when init containers comes into the picture.

GPUs are pretty simple example. On of the things we plan to do is scrub the GPU memory during the Allocate phase. If GPUs are re-used between initContainers and regular containers the current model doesn't fit.

**Comment by jiayingz** [comment]
@lichuqiang do you think if you have time to implement the solution you mentioned in the above comment https://github.com/kubernetes/kubernetes/issues/56022#issuecomment-345951373? We can try to get it into a 1.9 sub release.

@RenaudWasTaken I think for now, lets just support device reuse among initContainers and normal containers. We can revisit this part when we need to guarantee an Allocate call per container.

**Comment by RenaudWasTaken** [comment]
> @RenaudWasTaken I think for now, lets just support device reuse among initContainers and normal containers.

Right what I am mentioning here is that it is not possible to do that.
The point of the device plugin is so that we can execute vendor specific code before making the device available to the user (e.g: Scrub the GPU memory).

I don't think the proposed solution addresses this problem.

**Comment by lichuqiang** [comment]
@jiayingz Sure. But to clarify, I think if we dont't expect big shock on current implementation, we could only provide limited support on the point, that is, without re-generate runtime information for regular containers, only those containers whose requested resource is equal to or is a subset of that in init containers could make a resuse(e.g. if we have two init containers, each requests 2 devices, then a regular container that request 3 devices still could not reuse the devices.)
Besides, if a initcontainer requests 2 devices, and we have two regular containers, each requests 1 device, then due to the lack of runtime info re-generation, the devices  could only be reused by one of the containers, not both of them.
In sum, since we don't re-generate runtime information, we could only reuse devices per container, not per device, like we do in scheduler. Is this what you mean?

**Comment by jiayingz** [comment]
Hmm, that is a good question. I forgot that we now return the combined runtime information in AllocResponse. Then for now, perhaps we should just return an error in device plugin manager Allocate() in case both init containers and containers request the same device plugin resource? Alternatively, we could consider to not return error in that case but leaves some containers un-assigned and adds a call to m.allocateContainerResources(pod, &container) at the beginning of GetDeviceRunContainerOptions().

**Comment by lichuqiang** [comment]
> in case both init containers and containers request the same device plugin resource

Not quite sure about your meaning here. Isn't it a reuse we expect?

>Alternatively, we could consider to not return error in that case but leaves some containers un-assigned and adds a call to m.allocateContainerResources(pod, &container) at the beginning of GetDeviceRunContainerOptions().

I would prefer we implement it in allocation phase, for example in `m.devicesToAllocate` . 

>if we have two init containers, each requests 2 devices, then a regular container that request 3 devices still could not reuse the devices.

Think it a little more deeply, maybe we could support the scenario by adding a flag like `reused` in the store of devices, and to make a distinction, adding a specific suffix for the key of init containers when storing its deivces. However, it may request change in device store

**Comment by lichuqiang** [comment]
And a premise for reusing devices this way is that we suppose the device stateless, that is, after a init container terminates, its devices could be reused directly, without calling plugins to do some recycle and allocation actions.

**Comment by lichuqiang** [comment]
> perhaps we should just return an error in device plugin manager Allocate() in case both init containers and containers request the same device plugin resource?

@jiayingz You mean we give up reuse and prohibit users to request same kind of device in init containers and regular containers? that seems a bit weird.

**Comment by jiayingz** [comment]
I think for 1.9, we just return an error when both init containers and normal containers of a pod request the same device resource, and document this in the device plugin user guide. The reason is because in the current device plugin implementation, we don't have a good way to free devices used by init containers of an active pod. It is hard to do this at API level or even scheduler because we can't know whether an extended resource is device resource or not. So for now, I think we should probably just return a clear error message during admission handler. I am not sure yet whether there will be strong use cases that need to share devices between init containers and normal containers. We can revisit this based on user feedback.

**Comment by lichuqiang** [comment]
>e.g. if we have two init containers, each requests 2 devices, then a regular container that request 3 devices still could not reuse the devices.

Sorry I had a mistake here, because init-containers run sequentially, we need to consider the reuse between init containers too, so the scenario above might not occur.

**Comment by lichuqiang** [comment]
>It is hard to do this at API level or even scheduler because we can't know whether an extended resource is device resource or not. 

Oh, you are right, I ignored the resource awareness issue. I also agree that it's hard to address the issue without big change to current implementation. But I still feel the inconsistency of behavior between API and kubelet might confusing users.

**Comment by lichuqiang** [comment]
>something we could do is to differentiate init containers and normal containers in podDevices, and free up devices used by init containers when any normal container is about to run. That would request some code structure change

Agreed that to address the issue, it requires big changes in the overall workflow. And as I commented above, because init-containers run sequentially, we need to consider not only the reuse between init containers and normal containers, but also that in init containers themselves.
And we haven't see clearly if its a common user case that deserve such a big change.

**Comment by jiayingz** [comment]
Right. So for now, perhaps just return an error when this happens, to give clear error signals.

**Comment by lichuqiang** [comment]
@jiayingz Oh, I'm afraid we miss something, the check may not work as expected.
As I commented, because init-containers run sequentially, we did reuse between init containers in [scheduler](https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/scheduler/algorithm/predicates/predicates.go#L583), that is, if we have two init containers, each request 1 device, then we expect 1 device in total, but 2 in deviceplugin. The check could not cover the scenario.

**Comment by jiayingz** [comment]
Thinking about this problem a bit more, I wonder whether we may tackle this issue from the following approaches, ordered by their complexities:

1) Just return an error whenever an init container requests a device plugin resource, and document in the device plugin user guide that requiring device plugin resource in init containers are not supported. This may be the short-term change we can try to get into 1.9.

2) Maintain a list of devices allocated to init containers in ManagerImpl.Allocate(). Try to allocate from this list first for later init containers and normal containers. The required no. of devices we pass to ManagerImpl.devicesToAllocate() should subtract the no. of devices we have allocated to init containers. This may require some code structure change around ManagerImpl.Allocate(), ManagerImpl.allocateContainerResources(), and ManagerImpl.devicesToAllocate(). However, Allocate gRPC call is still issued during Admission all together, and it is possible that we issue an Allocate gRPC for [dev1] (say dev1 allocated to initContianer1), followed by another Allocate gRPC call for [dev1, dev2] (say dev1 and dev2 allocated to initContainer2), with none of containers started or finished. This assumes containers running in the same pod share the same security context, and device plugin doesn't need to perform per-container allocation operations. We just use Allocate gRPC call to learn container runtime settings.

3) Take a further step from 2), during Admission, we just determine what devices to allocate to containers without issuing the actual Allocate gRPC calls. I.e., we only fill deviceIds field in podDevices.deviceAllocateInfo but leaves allocResp field empty. During ManagerImpl.GetDeviceRunContainerOptions(), we check for this case and issue the actual Allocate gRPC call for the container. This ensures we can issue a gRPC Allocate call per container. However, if a pod is restarted multiple times, we don't guarantee Allocate gRPC call will be issued during subsequent pod runs.

4) Take a further step from 3), we can check for overlapping device allocations in ManagerImpl.GetDeviceRunContainerOptions() and invalidate their allocResp so that an Allocate gRPC call will be issued next time for containers using re-allocated devices. E.g., for containerA, if we find it is allocated with [dev1, dev2] and dev1 is also allocated to containerB, we set containerB's allocResp to nil so that next time before containerB is running, we will issue an Allocate gRPC call for dev1. Note that this approach does have the drawback that device plugin failure would cause previously running pods not be able to restart, so we need to carefully evaluate our use cases to see whether we need to implement this.

My suggestion is to implement 1) now and gather some user feedbacks to determine whether we need to implement the following approaches.

**Comment by vikaschoudhary16** [comment]
> Just return an error whenever an init container requests a device plugin resource, and document in the device plugin user guide that requiring device plugin resource in init containers are not supported. This may be the short-term change we can try to get into 1.9.

I see this a very big limitation. Special devices/resources in init containers is a very common use case IMO. Therefore we should try to fix this.

> 
> Maintain a list of devices allocated to init containers in ManagerImpl.Allocate(). Try to allocate from this list first for later init containers and normal containers. The required no. of devices we pass to ManagerImpl.devicesToAllocate() should subtract the no. of devices we have allocated to init containers. This may require some code structure change around ManagerImpl.Allocate(), ManagerImpl.allocateContainerResources(), and ManagerImpl.devicesToAllocate(). However, Allocate gRPC call is still issued during Admission all together, and it is possible that we issue an Allocate gRPC for [dev1] (say dev1 allocated to initContianer1), followed by another Allocate gRPC call for [dev1, dev2] (say dev1 and dev2 allocated to initContainer2), with none of containers started or finished. This assumes containers running in the same pod share the same security context, and device plugin doesn't need to perform per-container allocation operations. We just use Allocate gRPC call to learn container runtime settings.

This approach perfectly makes sense to me. What is your concern in implementing this? 

> 
> 

> Take a further step from 2), during Admission, we just determine what devices to allocate to containers without issuing the actual Allocate gRPC calls. I.e., we only fill deviceIds field in podDevices.deviceAllocateInfo but leaves allocResp field empty. During ManagerImpl.GetDeviceRunContainerOptions(), we check for this case and issue the actual Allocate gRPC call for the container. This ensures we can issue a gRPC Allocate call per container.

Even today, IIUC, Allocate call is made per container. Is there any other value that this approach is adding over 1) ?

> 
> Take a further step from 3), we can check for overlapping device allocations in ManagerImpl.GetDeviceRunContainerOptions() and invalidate their allocResp so that an Allocate gRPC call will be issued next time for containers using re-allocated devices. E.g., for containerA, if we find it is allocated with [dev1, dev2] and dev1 is also allocated to containerB, we set containerB's allocResp to nil so that next time before containerB is running, we will issue an Allocate gRPC call for dev1. Note that this approach does have the drawback that device plugin failure would cause previously running pods not be able to restart, so we need to carefully evaluate our use cases to see whether we need to implement this.

I am not able to see any gains with 2) or 3) over 1). Comments please.

**Comment by jiayingz** [comment]
I feel we may not be able to implement 2) for 1.9 timeframe. Option 2) also doesn't address the case @RenaudWasTaken mentioned above: https://github.com/kubernetes/kubernetes/issues/56022#issuecomment-348001390
Option 3) covers that case for pods without restarts. Option 4) fully covers the requirement we we will scrub old container data before giving it to a new container, even if they both run in the same pod, bug it does have the mentioned drawback during device plugin failure.

**Comment by lichuqiang** [comment]
>Take a further step from 3), we can check for overlapping device allocations in ManagerImpl.GetDeviceRunContainerOptions() and invalidate their allocResp so that an Allocate gRPC call will be issued next time for containers using re-allocated devices. E.g., for containerA, if we find it is allocated with [dev1, dev2] and dev1 is also allocated to containerB, we set containerB's allocResp to nil so that next time before containerB is running, we will issue an Allocate gRPC call for dev1. Note that this approach does have the drawback that device plugin failure would cause previously running pods not be able to restart, so we need to carefully evaluate our use cases to see whether we need to implement this.

How about make the allocation call optional? That is , if we find a contaienr using re-allocated devices, we'd try to issue an Allocate gRPC call first, and still use the cached setting if allocation failed.

And, if we decide not to address the issue in v1.9, which means we have enough time to work on it later, I think approach 2) might not be a good choice. Because it has a premise that devices are stateless, recycle actions before reuse(e.g: Scrub the GPU memory mentioned above) could not be supported. And this way, as I commented above, we could only reuse devices per container, not per device, like we do in scheduler.

**Comment by lichuqiang** [comment]
@jiayingz I noticed that you have already add the limitation into the [document](https://github.com/kubernetes/website/pull/6501), so I think it's already the decision that we add the limitation as a short-time solution in v1.9
So I posted a PR to add the check in code,#56659, PTAL :)

**Comment by vikaschoudhary16** [comment]
@jiayingz @RenaudWasTaken 

> The point of the device plugin is so that we can execute vendor specific code before making the device available in the container (e.g: Scrub the GPU memory).

**Use Case:**
Let say there is a  which node has two Devices of a resource type X and the device IDs are X1 and X2. User pod has one init container, lets call it cont-init and one regular container, lets call it cont-reg. Both cont-init and cont-reg requests 2 unit of resource X. cont-init will run some vendor specific code on allocated Devices and then cont-reg will use these 'initiated' devices.

I think this is the use case that @RenaudWasTaken  mentioned. And i feel 2) can handle this. 2) approach will allocate both the devices, X1 and X2, to both the containers. When the containers start, init container, cont-init, will be run first and will run to completion and here devices will get initialized. Strictly after this cont-reg will be started and now this regular container has initialized devices.

Where i am wrong?

**Comment by lichuqiang** [comment]
@vikaschoudhary16 
I think in RenaudWasTaken 's case, the initialization task is considered to be managed in the plugin, not in init-container, and in init-container we only _use_ the device, so then we might need to call plugin to do recycle action before the device reused by reguler containers.
In practical use, both of the two scenarios may exist, it depends on the request of user.

Besides, if we don't issue an Allocate gRPC call, we could not ensure a ”complete reuse“:
say an init-container requests 2 devices, and we have two regular containers, each requests 1 device, then due to the lack of runtime info re-generation, the devices could only be reused by one of the containers, not both of them.

**Comment by vikaschoudhary16** [comment]
> I guess in RenaudWasTaken 's case, the initialization task is considered to be managed in the plugin, not in init-container, and in init-container we only use the device, so then we might need to call plugin to do recycle action before the device reused by reguler containers.
> In practical use, both of the two scenarios may exist, it depends on the request of user.

It is the init containers' job to initialize things and if in some special case device plugin is doing the initialization part, in that case, init containers will not be needed and serve no purpose in pod spec. 
Specific to @RenaudWasTaken example of memory scrubbing, i think this also makes more sense to be done in init container. Once Device's memory is scrubbed, it can be used by regular container.

> 
> Besides, if we don't issue an Allocate gRPC call, we could not ensure a ”complete reuse“:
> say an init-container requests 2 devices, and we have two regular containers, each requests 1 device, then due to the lack of runtime info re-generation, the devices could only be reused by one of the containers, not both of them.

Let try to run your use case with approach 2). There are three containers in pod, cont-init(requested 2 unit or resource X), cont-reg1(requested 1 unit of resource X) and cont-reg2(requested 1 unit of resource X).
Now in approach 2), 
- gRPC Allocate call is made for cont-init requesting X1 and X2.  
- Next, gRPC Allocate call is made for cont-reg1. This time resource id will be send in Allocate from the previously allocated [X1, X2]. Lets say X1 is requested for cont-reg1
- Next, gRPC Allocate for cont-reg2 and resource with ID X2.
All this allocation info gets stored in internal cache.

Now when container runs, runtimeOptions will be collected from internal cache.

Where do you see a problem in this flow?

**Comment by lichuqiang** [comment]
@vikaschoudhary16 
Yep, it could work if the plugin behavior the way you described, but I'm not sure if all kinds of devices could support "pre-allocation", that is, doing allocation on a same device multiple times at the same time, to prepare runtime informations for several containers that reuse the device.
Also I have no idea if all plugin developers consider there plugins "stateless", that is, managing initialization in init-containers.
As I don't have enough knowledge of hardware, would like to hear opinions from other guys :)

**Comment by RenaudWasTaken** [comment]
> It is the init containers' job to initialize things and if in some special case device plugin is doing the initialization part, in that case, init containers will not be needed and serve no purpose in pod spec.
> Specific to @RenaudWasTaken example of memory scrubbing, i think this also makes more sense to be done in init container. Once Device's memory is scrubbed, it can be used by regular container.

This would defeat the purpose of a container.
In the case of GPUs, when you run a container you expect the GPU to always be in the same state.
Furthermore GPUs can't be shared (exclusive usage) between containers meaning that Init containers should behave in the same way as regular containers.
With the only difference being that they are executed sequentially and before regular containers.

Additionally, operations to setup a device before making them available in a container, whether functionally (load the driver, insert libraries, ....) or security wise (scrub the memory), should be handled by the infrastructure not the users pod spec.

**Comment by RenaudWasTaken** [comment]
@jiayingz I think it's a sane behavior to forbid the use of Device Plugin Resources in Init Containers for the 1.9 release

**Comment by tengqm** [comment]
moving forward, #56398

**Comment by jiayingz** [comment]
/cc @cmluciano @sameo @flx42 @3xx0

I think what long-term solution we decide to implement will largely depend on use-case requirements from different device plugins. Would like to hear some thoughts from different device plugin developers on this. Can people cc-ed in this issue take a look at the proposed options mentioned in https://github.com/kubernetes/kubernetes/issues/56022#issuecomment-348286184 and provide some feedbacks on which one may better fit your use cases?

**Comment by RenaudWasTaken** [comment]
- Solution 1 makes sense for the moment
- Solution 2 defeats the purpose of the device plugin, setting up a device before making it available to a container.
- solution 4 seems to be a sane solution.

As mentioned in my previous comment, as long as devices are exclusive, I expect the devices exposed in my container to be in the same state at the start of my container.

**Comment by ConnorDoyle** [comment]
Solution number 1 seems totally reasonable short-term.

Long term, simplifying and documenting the relationship between plugin callbacks and container lifecycle would help plugin authors.

**Comment by vikaschoudhary16** [comment]
@RenaudWasTaken 

> As mentioned in my previous comment, as long as devices are exclusive, I expect the devices exposed in my container to always be in the same state at the start of my container.

If we go by Solution 2), I think above holds true. How do you see GPUs' state changing once app containers are using them?

> Solution 2 defeats the purpose of the device plugin, which is setting up a device before making it available to a container.

IMO, init containers have the same goal documented, i.e to prepare the env/devices ready before app containers come up.
https://kubernetes.io/docs/concepts/workloads/pods/init-containers/#what-can-init-containers-be-used-for
Quoting the relevant documentation:

> Because Init Containers have separate images from app Containers, they have some advantages for start-up related code:
> They can contain and run utilities that are not desirable to include in the app Container image for security reasons.

Also:

> A Pod cannot be Ready until all Init Containers have succeeded.

**Comment by jiayingz** [comment]
For reference, I implemented option 2 solution in PR https://github.com/kubernetes/kubernetes/pull/56818. The change itself is small. This is an alternative short-term fix we may consider to get into a 1.9 patch release. I think the main benefit of taking this fix compared to Option 1 solution is that we can change the underlying implementation to support init containers later with less user-facing impact.

**Comment by jiayingz** [comment]
No mater we take PR https://github.com/kubernetes/kubernetes/pull/56659 or PR https://github.com/kubernetes/kubernetes/pull/56818 for 1.9, I think we need to have this issue approved for 1.9 milestone.

@vishh or @dchen1107 or @derekwaynecarr can any of you approve this issue for 1.9? Thanks!
