### ISSUE TITLE
[job failure] gci-gce-ingress

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/kubernetes#56089]
/priority critical-urgent
/priority failing-test
/kind bug
/status approved-for-milestone
@kubernetes/sig-network-test-failures
FYI @kubernetes/sig-gcp-test-failures

This job has been failing since 2017-11-17.  It's on the [sig-release-master-blocking dashboard](https://k8s-testgrid.appspot.com/sig-release-master-blocking),
and prevents us from cutting [v1.9.0-beta.1] (kubernetes/sig-release#34). Is there work ongoing to bring this job back to green?

https://k8s-testgrid.appspot.com/sig-release-master-blocking#gci-gce-ingress

- last good: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-ingress/14403
- first bad: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-ingress/14404
- latest bad: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-ingress/14496
- suspect commit range: https://github.com/kubernetes/kubernetes/compare/56e62b684...3ec7487c0

**Comment by janetkuo** [comment]
Test panicked at `AllNodesReady`, possibly because `f.ClientSet` is `nil`. 
https://github.com/kubernetes/kubernetes/blob/849d7f859599d4aa327d773b4de4839867523e61/test/e2e/framework/framework.go#L363 https://github.com/kubernetes/kubernetes/blob/849d7f859599d4aa327d773b4de4839867523e61/test/e2e/framework/util.go#L3649-L3656

My theory is that #55525 is related. Note that #55525 isn't a bug -- it just removed dup functions and pointed call to the right function. It then triggered some old bug (we didn't find this bug because the code was never called.)

**Comment by MrHohn** [comment]
Seems to have the same symptom as gci-gce-slow (https://github.com/kubernetes/kubernetes/issues/56079), test panicked while cleaning up:
```
I1121 00:48:07.264] SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSNov 21 00:48:07.263: INFO: Running AfterSuite actions on all node
I1121 00:48:07.264] Nov 21 00:48:07.263: INFO: Waiting up to 3m0s for all (but 0) nodes to be ready
I1121 00:48:07.264] Nov 21 00:48:07.263: INFO: Running AfterSuite actions on node 1
I1121 00:48:07.264] Nov 21 00:48:07.263: INFO: Skipping dumping logs from cluster
I1121 00:48:07.264] 
I1121 00:48:07.264] ------------------------------
I1121 00:48:07.265] Panic [0.000 seconds]
I1121 00:48:07.265] [AfterSuite] AfterSuite 
I1121 00:48:07.265] /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/e2e.go:254
I1121 00:48:07.265] 
I1121 00:48:07.265]   Test Panicked
I1121 00:48:07.265]   runtime error: invalid memory address or nil pointer dereference
I1121 00:48:07.265]   /usr/local/go/src/runtime/panic.go:491
I1121 00:48:07.265] 
I1121 00:48:07.265]   Full Stack Trace
I1121 00:48:07.265]   	/usr/local/go/src/runtime/panic.go:491 +0x283
I1121 00:48:07.266]   k8s.io/kubernetes/test/e2e/framework.AllNodesReady.func1(0xc420d2b0d0, 0x928e7d, 0x36b1440)
I1121 00:48:07.266]   	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/util.go:3656 +0x68
I1121 00:48:07.266]   k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.pollImmediateInternal(0xc420f40140, 0xc4209c8780, 0xc420f40140, 0xc4209c8780)
I1121 00:48:07.266]   	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:245 +0x2b
I1121 00:48:07.266]   k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.PollImmediate(0x77359400, 0x29e8d60800, 0xc4209c8780, 0x2, 0x2)
I1121 00:48:07.266]   	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:241 +0x4d
I1121 00:48:07.266]   k8s.io/kubernetes/test/e2e/framework.AllNodesReady(0x0, 0x0, 0x29e8d60800, 0x3b95fd9, 0x7)
I1121 00:48:07.266]   	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/util.go:3653 +0x1b2
I1121 00:48:07.266]   k8s.io/kubernetes/test/e2e/framework.(*Framework).AfterEach(0xc421085440)
I1121 00:48:07.267]   	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:363 +0x556
I1121 00:48:07.267]   k8s.io/kubernetes/test/e2e/framework.(*Framework).AfterEach-fm()
I1121 00:48:07.267]   	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:135 +0x2a
I1121 00:48:07.267]   k8s.io/kubernetes/test/e2e/framework.RunCleanupActions()
I1121 00:48:07.267]   	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/cleanup.go:59 +0x70
I1121 00:48:07.267]   k8s.io/kubernetes/test/e2e.glob..func3()
I1121 00:48:07.267]   	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/e2e.go:257 +0x56
I1121 00:48:07.267]   k8s.io/kubernetes/vendor/github.com/onsi/ginkgo/internal/leafnodes.(*runner).runSync(0xc421559500, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
I1121 00:48:07.267]   	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/e2e.go:332 +0x219
I1121 00:48:07.267]   k8s.io/kubernetes/test/e2e.TestE2E(0xc4207542d0)
I1121 00:48:07.268]   	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/e2e_test.go:49 +0x2b
I1121 00:48:07.268]   testing.tRunner(0xc4207542d0, 0x3cdf888)
I1121 00:48:07.268]   	/usr/local/go/src/testing/testing.go:746 +0xd0
I1121 00:48:07.268]   created by testing.(*T).Run
I1121 00:48:07.268]   	/usr/local/go/src/testing/testing.go:789 +0x2de
```

Possibly introduced by https://github.com/kubernetes/kubernetes/pull/55525.
@miaoyq @janetkuo

**Comment by bowei** [comment]
@janetkuo what is the recommended fix?

**Comment by bowei** [comment]
Is this a framework bug or a networking bug? If it is a framework bug, who is the right owner to get this resolved?

**Comment by janetkuo** [comment]
This is a framework bug. The most naive fix is check if `f.ClientSet` is nil before calling `AllNodesReady`. However this should be handled in a more proper way. I'm not sure why the clientset is nil, maybe because the framework's namespace creation is skipped? 

I'm not sure who owns this.

**Comment by abgworrall** [comment]
Given it's release blocking, and it is test infra, I think the 1.9 test infra lead owns in - @BenTheElder

**Comment by BenTheElder** [comment]
I'm not particularly familiar with this code. I'm happy to look but I don't know how long it will take me to resolve this properly, perhaps someone from [test/OWNERS](https://github.com/kubernetes/kubernetes/blob/849d7f859599d4aa327d773b4de4839867523e61/test/OWNERS) would be more approrpiate?

**Comment by BenTheElder** [comment]
I also don't particularly think this is test-infra:
https://github.com/kubernetes/sig-release#test-infra-lead
> Test Infra Lead
> - Sets up and maintains all CI for the release branch

**Comment by abgworrall** [comment]
Fair enough.

I took a quick look at recent commits into the framework, and didn't see anything obvious; @janetkuo , I think you currently know the most about this. Can you own it, even if just until you can figure out a better owner ?

**Comment by MrHohn** [comment]
I think I figured out what happened. Just checked all affected CIs and found all of them are running ingress tests. Turned out in ingress suite we made a duplicated call to `framework.BeforeEach()`:
https://github.com/kubernetes/kubernetes/blob/2e1d61a0d54c0bc76c84c7fcfdf9812efc1652a3/test/e2e/network/ingress.go#L51-L55

For more context  `framework.BeforeEach()` is supposed to be set up automatically during `NewFramework()`:
https://github.com/kubernetes/kubernetes/blob/2e1d61a0d54c0bc76c84c7fcfdf9812efc1652a3/test/e2e/framework/framework.go#L126-L138

And during the actual BeforeEach function we register AfterEach function as one of the CleanupActions. This means if BeforeEach is called twice, we will be cleaning up the same framework twice.
https://github.com/kubernetes/kubernetes/blob/2e1d61a0d54c0bc76c84c7fcfdf9812efc1652a3/test/e2e/framework/framework.go#L140-L146

If we took a look at the AfterEach function, we reset `f.ClientSet` to nil in the very end:
https://github.com/kubernetes/kubernetes/blob/2e1d61a0d54c0bc76c84c7fcfdf9812efc1652a3/test/e2e/framework/framework.go#L244-L282

So during the second call to AfterEach, test paniked on nil pointer (`f.ClientSet`).

Also try to explain why this didn't happen before --- previously `ginkgo.SynchronizedAfterSuite()` is calling RunCleanupActions from a separate set of function, which is fixed by #55525:
https://github.com/kubernetes/kubernetes/pull/55525/commits/16aa5820fb0061462fbe21e0f7e69d8d9b18d71a#diff-53314d6a19fc22810420c6bee965f5b8L300

Sent out a fix on https://github.com/kubernetes/kubernetes/pull/56128.

**Comment by BenTheElder** [comment]
Thank you @MrHohn, awesome sleuthing!

I've been after https://github.com/kubernetes/test-infra/issues/5617 which caused some of our nodes to fill their disks :( have a fix going out.

**Comment by MrHohn** [comment]
https://k8s-testgrid.appspot.com/sig-network-gce#gci-gce-ingress
Test is no longer failing, seems #56128 fixed it.

/close
