### ISSUE TITLE
should support AWS NVMe device

### ISSUE THREAD

**Issue by rootfs** [kubernetes/kubernetes#56155]
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG REPORT
/kind bug

**What happened**:
AWS NVMe device path starts with `/dev/nvme` according to [doc](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/device_naming.html), it fails aws device probe [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/aws/aws.go#L1429)
```go
	for _, blockDevice := range info.BlockDeviceMappings {
		name := aws.StringValue(blockDevice.DeviceName)
		if strings.HasPrefix(name, "/dev/sd") {
			name = name[7:]
		}
		if strings.HasPrefix(name, "/dev/xvd") {
			name = name[8:]
		}
		if len(name) < 1 || len(name) > 2 {
			glog.Warningf("Unexpected EBS DeviceName: %q", aws.StringValue(blockDevice.DeviceName))
		}
		deviceMappings[mountDevice(name)] = awsVolumeID(aws.StringValue(blockDevice.Ebs.VolumeId))
	}
```

**What you expected to happen**:
NVMe device should be supported.
**How to reproduce it (as minimally and precisely as possible)**:
Code reading

**Anything else we need to know?**:
@kubernetes/sig-storage-bugs @kubernetes/sig-aws-misc 

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration: AWS
- OS (e.g. from /etc/os-release): 
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by justinsb** [comment]
So I'm not sure how important this is.  It means volumes can't be mounted on c5 instances, but there might well be more instance types announced at reinvent that use nvme (I have no knowledge, but it seems like a pretty safe bet!)

Prototyping how to handle in kubernetes/kops#3914  (using the nvme tool with json output immediately segfaulted for me, which was a little bit of a red-flag)

**Comment by justinsb** [comment]
Put up a PoC / WIP PR #56354.  It uses the ioctls rather than the nvme command, so that we don't need the nvme command installed, and because I've observed segfaults from the `nvme list` command.

**Comment by justinsb** [comment]
I'm leaning towards the idea that we _should_ fix this in 1.9, because if we don't fix this realistically it'll be 6 months from now until a stable kubernetes release has support for volumes on these instance types (1.10 release late March, then 2 or 3 months to stabilize).  That's true even for c5s, and I can't imagine there won't be more instance types coming.

The risk is fairly low: it's only in the AWS code path, and the code does a directory listing looking for nvme devices in /dev/ first (hopefully I didn't screw _that_ up!), so the higher risk code that does syscalls shouldn't be triggered unless you're running on one of these otherwise-broken instances.  And there aren't that many cases of this in the wild (yet), so the testing grid isn't going to be too large.

There's also another advantage, in that these volumes could side-step some of the EBS problems we sometimes see, because the volume mountpoint isn't significant, and we have a cross-check by EBS volume ID now.  So this could be _more_ reliable than what we have today.

I'm going to work more on validating the fix etc

cc @enisoc

**Comment by jberkus** [comment]
Progress report, please?  If this is going to be in 1.9, we need to know its status.

**Comment by justinsb** [comment]
@jberkus PR is available.  I'm going to rework it to be safer per @gnufied 's suggestion.
