### ISSUE TITLE
Record event when pod was evicted by kubelet successfully!

### ISSUE THREAD

**Issue by jiaxuanzhou** [kubernetes/kubernetes#56272]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind feature

**What happened**:
As we know that there are two kinds of pod evictions by node controller or kubelet.
for node controller eviction , when the pod was evicted , the event will be recorded, but on the other hand ,when the pod was evicted by kubelet, it just log the event ,but no record for the event, I think the event should be recorded. 
**What you expected to happen**:
record the pod eviction event by kubelet.
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by jiaxuanzhou** [comment]
@m1093782566 what's ur opinion?

**Comment by m1093782566** [comment]
cc @resouer @feiskyer 

Any comments?

**Comment by resouer** [comment]
I think the eviction event is properly recorded, or I misunderstood something here. e.g. https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/eviction/eviction_manager.go#L575

**Comment by jiaxuanzhou** [comment]
@resouer 
yes ,this line records that kubelet is preparing to do the eviction ,but  the pod is successfully evicted or not is not recorded ,please see here : 
https://github.com/kubernetes/kubernetes/blob/e7ad6e60081887d67b987cb0429b52c5a4ff878c/pkg/kubelet/eviction/eviction_manager.go#L579
and 
https://github.com/kubernetes/kubernetes/blob/e7ad6e60081887d67b987cb0429b52c5a4ff878c/pkg/kubelet/eviction/eviction_manager.go#L581

**Comment by hzxuzhonghu** [comment]
Also find evict failed return true ?

**Comment by jiaxuanzhou** [comment]
@hzxuzhonghu we can not figure out whether the pod was evicted successfully or not just due to the events.

**Comment by stewart-yu** [comment]
return bool and  err better? @hzxuzhonghu

**Comment by hzxuzhonghu** [comment]
@jiaxuanzhou  @stewart-yu I mean when failed to evict , it also return true. I think it is not appropriate.

**Comment by stewart-yu** [comment]
yes, so i think it return err also to distinguish evict's result.

**Comment by jiaxuanzhou** [comment]
@stewart-yu @hzxuzhonghu the return value(always return true) is another case of arch design

**Comment by jiaxuanzhou** [comment]
@resouer @feiskyer any updates?

**Comment by resouer** [comment]
Why do you need evict result may I ask? Basically you can not do anything to fix the eviction (or means a lot to me to fix eviction).

If just for monitoring purpose, I think log is quite enough.

**Comment by jiaxuanzhou** [comment]
@resouer we can image a third-party monitor system  in production scenario, when we want to monitor resource at pod level, we just monitor the pod was to evicted but no results reported due to the events, and it is unreasonable to  filter the key words from the log files.

**Comment by mattdodge** [comment]
I'm curious about this as well. And even though [this code](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/eviction/eviction_manager.go#L575) makes it seem like a kubelet eviction is logged as an event somewhere, I cannot see that event anywhere. I've checked the evicted pod, the replicaset, and the deployment. All of them (when using `kubectl describe`) show a `<none>` in the Events section.

In a way that feels weird to complain about, kubernetes is making it somewhat difficult to determine when things go wrong because it recovers them so quickly. I see an evicted pod with `kubectl get pods -a` but there's really nowhere else (that I can find) to see that something happened. The deployment and RS both say they are "ok" because a new pod spun up. What is the recommended way to monitor clusters for events like this?

**Comment by jiaxuanzhou** [comment]
i still recommend to record the event when the delete api was sent and record it

**Comment by kilianc** [comment]
@mattdodge is spot on. Eviction is kind of a big deal. Developers should almost treat it as a bug in their code or configuration. Most of the time is a memory leak but the event is never logged anywhere instead of being in your face when it happens.

**Comment by tpo** [comment]
:+1: me too

I'd need to know when a pod was evicted in order to do event correlation - aka our monitoring system tells us some service went down and I'd like to know wheter that happend at the moment when some pod was evicted.

The eviction time does not seem to be visible with `kubectl describe pod pod-xxxx`

**Comment by tpo** [comment]
I can't reopen this issue since I'm not the author. Could you please reopen this issue @jiaxuanzhou or maybe @stewart-yu ?
