### ISSUE TITLE
Device plugin handling of partial allocation failures

### ISSUE THREAD

**Issue by tengqm** [kubernetes/kubernetes#56307]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
In the current device allocation workflow, init-containers and regular containers are treated in separate steps due to the lack of a pod-level request/limit representation. There will be cases where the init-containers successfully allocated devices but the regular containers failed to do so.

**What you expected to happen**:
There are at least two options to solve this. In the near term, treat the Pod as a whole when allocating device resources. Either the allocation succeeds or it fails as a whole. We cannot allow partial successes. 
In the long term, we are about to advocate a usage pattern where init-containers and regular containers are using the same collection of device resources. The init-containers are tasked to do device, driver and sdk preparation, and the regular containers simply assume that the devices are usable.

**Comment by vikaschoudhary16** [comment]
IMO this is not a valid issue. If a resource allocation is success for init containers and allocation fails for regular containers, pod will not be in active state eventually. And for any allocation calls in future, `m.allocatedDevices` is updated again before starting allocation process.
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/cm/deviceplugin/manager.go#L603

**Comment by tengqm** [comment]
hehe, fine. Whatever you say.
The protocol design doesn't provide a "release" or "dealloc" function. No one cares if there are "partial failures" and no one cares if the "allocate" operation at the plugin side is costly or not.
From a device plugin's perspective, say my FPGA device needs to do some pre-allocation preparation work... no one cares how expensive an operation it could be, right? The kubelet now says: give me 2 GZIP units. The plugin said okay. And two units allocated and recorded by the plugin. Later on, the Pod creation fails because there are other requirements not satisfied. But ... kubelet won't tell me that the 2 GZIP units it allocated is no longer used... 
Why? Because all device allocation requests were issued prematurely. Kubelet has been eagerly issuing device allocate requests without knowing for sure how many devices in total a Pod needs. And ... kubelet turns its back to me when it cannot complete such a transaction. There is no rollback, there is no notification.

**Comment by vikaschoudhary16** [comment]
In this case, let say those two gzip unit were, unit1 and unit2. Let say pod1 was the pod which failed with partial allocation and is not using unit1 and unit2 anymore. Now a new pod, pod2 comes and requests for two GZIP units. Kubelet before making any allocation, updates `m.allocatedDevices` using active pods and thus removes unit1 and unit2 from the allocated devices. Moving ahead, kubelet allocated unit1 and unit2 for pod2 now and Allocate call is invoked at device plugin. Device plugin resets unit1 and unit2 and sends back success response to kubelet with the required env, mounts etc.
Even if kubelet send an early notification of releasing the devices, just after the failure and not waiting till next allocate:
- Functionality wise at kubelet, there will be no difference
- cpu cycle consumption wise at device plugin, no difference
- Allocate call will return faster in cases where device reset/init is a lengthy process and device plugin has performed this init/reset before hand when it did receive a dealloc on a partial failure in the past.

Adding a dealloc call makes sense to me because of last point. I was saying "invalid' because from the issue description, it looks like there is a functionality issue because of partial allocations. If I am correct till now, may be we would want to add details somewhere that it is about adding a release/deallocate call.

**Comment by tengqm** [comment]
The core of the problem is ... we are not treating device allocations as a transaction. We are allowing for partial success (or partial failure) today. What I was trying to do is *do not* call "allocate" when you are not sure if there are enough devices left for a Pod. Once you do that, it is a "virtual contract". From device plugin side, it will treat every allocate request seriously.
By partial failure, I mean the "completeness" of a device allocation "transaction" for a Pod. kubelet should not *prematurely" do device allocations on a per-container basis. If it knows that the Pod is going to fail due to insufficient resources, don't even ask for one. If a pod needs 2 accelerators to operate, by definition, 2 is guaranteed, 1 is not acceptable.

**Comment by vikaschoudhary16** [comment]
Then your concern should get addressed by this PR, https://github.com/kubernetes/kubernetes/pull/58282

With this PR, "completeness" of transaction will get validated at admission predicate and actual "allocate" will be invoked at a later point of time at container start. If available devices are not sufficient enough, no "allocate" will be invoked at device plugin.

**Comment by tengqm** [comment]
Okay, you may want to reference this issue in that PR. :)

**Comment by RenaudWasTaken** [comment]
@tengqm sorry for the delay.
I think your concerns are a valid concern. But I think the current model is pretty much broken and should be reworked.

It has way too many edge cases to try and work around not calling Allocate on container start.

**Comment by RenaudWasTaken** [comment]
> Why? Because all device allocation requests were issued prematurely. Kubelet has been eagerly issuing device allocate requests without knowing for sure how many devices in total a Pod needs. And ... kubelet turns its back to me when it cannot complete such a transaction. There is no rollback, there is no notification.

The problem we had with a release or dealloc function was that it had either `At most once` or `At least once` semantics and we couldn't agree to add the latest.

I do intend to get to that `Deallocate` at some point some people have been requesting it.
