### ISSUE TITLE
Continuous polling of webhook admission registration objects

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#56357]
with `hack/local-up-cluster.sh`, I see continuous polling of mutatingwebhookconfigurations and validatingwebhookconfigurations objects (once a second, without end):

```
I1124 17:47:38.496403   25281 wrap.go:42] GET /apis/admissionregistration.k8s.io/v1beta1/mutatingwebhookconfigurations: (941.788µs) 200 [[hyperkube/v1.10.0 (darwin/amd64) kubernetes/2952d7c] 127.0.0.1:51994]
I1124 17:47:38.496367   25281 wrap.go:42] GET /apis/admissionregistration.k8s.io/v1beta1/validatingwebhookconfigurations: (950.094µs) 200 [[hyperkube/v1.10.0 (darwin/amd64) kubernetes/2952d7c] 127.0.0.1:51994]
I1124 17:47:39.498264   25281 wrap.go:42] GET /apis/admissionregistration.k8s.io/v1beta1/mutatingwebhookconfigurations: (666.13µs) 200 [[hyperkube/v1.10.0 (darwin/amd64) kubernetes/2952d7c] 127.0.0.1:51994]
I1124 17:47:39.498292   25281 wrap.go:42] GET /apis/admissionregistration.k8s.io/v1beta1/validatingwebhookconfigurations: (726.744µs) 200 [[hyperkube/v1.10.0 (darwin/amd64) kubernetes/2952d7c] 127.0.0.1:51994]
```

/kind bug
/sig api-machinery
/assign @caesarxuchao @cheftako

**Comment by hzxuzhonghu** [comment]
@liggitt Seen from https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/admission/configuration/mutating_webhook_manager.go#L55 , we can see the admission configuration manager using poller to sync configuration from apiserver.  

But may be a shared informer is better.  If agree, I can fix it.

**Comment by liggitt** [comment]
this should definitely be using an informer

**Comment by jberkus** [comment]
Is this critical for 1.9?  If so, we need to add the milestone and priority labels.  If not, please remove it from the 1.9 milestone (or wait for automation to do it).

**Comment by caesarxuchao** [comment]
Some [history](https://github.com/kubernetes/community/pull/611#discussion_r116286033) on why we made the configuration manager polling based.

The gist is that "admin needs to be able to ensure the webhook config eventually applies within some bound". If the configuration manager is polling based, it can detect if the apiserver is not responding and if so, it can fail the webhooks and log the error. On the contrary, if the configuration manager uses WATCH, it can't detect if the WATCH has a big delay.

I think the complete solution would be converting the configuration manager to use informer, and report back the observed generation (tracking issue https://github.com/kubernetes/kubernetes/issues/54712).

I don't think we should change the configuration manager to use informer without the proper API fix. The extra QPS caused by the polling equals the number of apiservers, which is tolerable IMO.

**Comment by liggitt** [comment]
> report back the observed generation

That's unlikely to happen soon, without API server representation in the API. There are N servers that would need to indicate they had observed the generation. 

I don't think polling on a one second interval per server replica, per apiserver, is reasonable

**Comment by caesarxuchao** [comment]
Talked with @liggitt on slack:
* The extra QPS is likely to be "5 apiservers * 3 replicas for HA * 2 api types means 30 requests per second", which is not negligible for a small master. 
* The rbac authorizer faces the same situation and is using informer to fetch the configuration, and it's working fine.
* We can set the informer to do a relist periodically if we want to keep the latency bound.

So I think we can switch to using informer.

**Comment by hzxuzhonghu** [comment]
OK, I can work for this.

**Comment by jberkus** [comment]
ACK.  In progress
ETA: 1.9.1 release
Risks: Fix code is difficult, requires test changes

According to SIG as of 12/1, a fix is being worked on, but may not be ready for 1.9.0 release.  SIG believes that the issue is not a showstopper, but will be user-visible.  Team is working to get a PR by 1.9.0 but may not be able to fix issue until 1.9.1.

**Comment by enisoc** [comment]
I'm removing the v1.9 milestone since it appears this is targeting 1.9.1. Please let me know if you have any objections.

**Comment by cheftako** [comment]
I believe 1.9.1 is correct.
