### ISSUE TITLE
kubectl attach to terminating pods prints bad output

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#56450]
```
$ k attach -ti init-ctr-demo
If you don't see a command prompt, try pressing enter.
                                                      error: unable to upgrade connection: container busybox not found in pod init-ctr-demo_demos
$ k get pods
NAME            READY     STATUS        RESTARTS   AGE
init-ctr-demo   0/1       Terminating   1          2m
```

First, the formatting.

Second, "init-ctr-demo_demos" is an internal artifact, not fit for human-facing errors.

Third, the container DOES exist, it's just in a terminating state.

**Comment by vfreex** [comment]
The formatting issue should be fixed by #56483.

Regarding to the pod name, I think `$namespace/$podName` is better.
As for the pod name, the error message is from the HTTP response of kubelet server. I've looked at the code, functions defined in interface `HostInterface` are using `podFullName` ($podName_podNamespace) to identify a pod. Without spiting the parameter into two separated parameters, it could be tricky to change the output format of an error message.  Personally I would prefer to change the signatures, but I don't know if we are planing to do it.

In order to improve the readability, I added a client-side check for pod status. See #56922.
