### ISSUE TITLE
Pods with stdinOnce hang on attach

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#56453]
Using `stdin` works:

```
$ cat p1.yaml
apiVersion: v1
kind: Pod
metadata:
  name: stdin
spec:
  containers:
  - name: busybox
    image: busybox
    tty: true
    stdin: true
$ k attach -ti stdin
If you don't see a command prompt, try pressing enter.
/ # 
/ # 
/ # Session ended, resume using 'kubectl attach stdin -c busybox -i -t' command when the pod is running
```

Using stdinOnce does not:
```
$ cat p2.yaml 
apiVersion: v1
kind: Pod
metadata:
  name: stdin-once
spec:
  containers:
  - name: busybox
    image: busybox
    tty: true
    stdinOnce: true
$ k create -f p2.yaml 
pod "stdin-once" created
$ k attach -ti stdin-once
If you don't see a command prompt, try pressing enter.
/ #
```

I have to `killall -9 kubectl` to recover.

**Comment by vfreex** [comment]
Hi @thockin ,

I did some investigation on this issue. Here's what is going on:
1. When `kubectl attach` is issued, the TTY that kubectl is using is set to raw mode (https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/util/term/term.go#L96). All keys 
  pressed, including ^C (CTRL+C), will be forwarded as-is to the remote pseudo TTY of the Pod, so no `SIGINT` signal will be sent to the local `kubectl` process.
2. Changing the command of `stdin` pod to `sleep 1800` in `p1.yaml`, which doesn't handle `SIGINT` by itself, will also hang on attach.
3. Using `docker attach` to attach to the `stdin-once` pod on the remote node where the pod is running leads to an interesting result: `docker attach` just quits without terminating the process in the Pod. It seems to me the process in the Pod didn't get the signal.
4.  When `docker attach` to `stdin` pod, `CTRL+C` works as expected: The process in the Pod receives `SIGINT` then exits.

Hence, I suspect this issue is caused by Docker, not kubectl. However I didn't look at the code of Docker client nor test sending `^C` via Docker engine API.

I think forwarding special keys like `^C` to the remote as-is should be expected. We may also enhance this by letting user choose forwarding or not, adding a `timeout` option, or introduce escape keys like what `ssh` does.

What do you think?

**Comment by vfreex** [comment]
@shiywang would also like to hear suggestions from you :)
