### ISSUE TITLE
Should alpha e2e suites run all tests?

### ISSUE THREAD

**Issue by msau42** [kubernetes/kubernetes#56507]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug
/sig testing

**What happened**:
Right now alpha suites only run specific tests for alpha features.  But we could potentially catch regressions in existing functionality earlier (caused by alpha features) if the suites also ran the regular tests.

**What you expected to happen**:
Maybe it would be useful to have two alpha suites: one for just the alpha feature tests, and one for regression testing.

**Comment by krzyzacy** [comment]
IMO sig-testing don't decide which test to run on alpha e2e, maybe this is
/sig gcp
?
cc @abgworrall

**Comment by abgworrall** [comment]
I've forgotten why sig-gcp is considered the owner of alpha testing; it's not as if all alpha features are GCP features or anything.

That said, I'd agree, it makes sense to run the regular test suite against an alpha-feature-enabled instance of K8s. (If someone is going to look at the results, that is ...)

**Comment by msau42** [comment]
At least in sig storage, we recently had 2 encounters of regressions in alpha clusters that went unnoticed for at least 1 or 2 releases, and could have been easily caught by regression testing.  So we are definitely interested in monitoring the tests we own at least...

**Comment by msau42** [comment]
cc @Random-Liu @yujuhong

**Comment by yujuhong** [comment]
The Alpha feature suite should at least run some functional tests (e.g., conformance) to ensure that no GA features are broken. This will also help smooth out the graduation of the Alpha features to Beta. 

I don't think this issue should be owned by sig-gcp. It's a general issue across all SIGs. sig-release *might* be interested in the discussion since this concerns the quality of the release. @kubernetes/sig-release-feature-requests

**Comment by msau42** [comment]
Looks like this has been added:
https://k8s-testgrid.appspot.com/google-gce#gci-gce-alpha-enabled-default
