### ISSUE TITLE
Make it easy to include a kubernetes client library in a separate Go project

### ISSUE THREAD

**Issue by roberthbailey** [kubernetes/kubernetes#5660]
Right now if you want to create an application that talks to the kubernetes apiserver you can either put the code into the kubernetes GitHub repository or you can include the entire repository as a dependency (as OpenShift does). Neither of these options is particularly compelling if all you want to do is have a dependency on a client library that makes it simple to communicate with the apiserver.

**Comment by lavalamp** [comment]
We are close, but this isn't quite going to land in 1.2. We'll have a generated versioned client, but we won't have addressed the import graph problem yet.

**Comment by lavalamp** [comment]
This is mostly a dup of #4874. Slightly different focus.

**Comment by Raffo** [comment]
@lavalamp Can you tell us what needs to be done and how we can help?

**Comment by lavalamp** [comment]
@Raffo It's a bit out of date now, but take a look at my proposal here: https://github.com/kubernetes/kubernetes/pull/16062

We're mostly there. We need to start tightly controlling the import paths, and engineer things so that you can import the client without importing e.g. our scheme, conversion functions, etc.

**Comment by lavalamp** [comment]
I'm gonna steal this since I sorta started some related refactorings...

**Comment by justinsb** [comment]
Can we close now that we have https://github.com/kubernetes/client-go ?

**Comment by smarterclayton** [comment]
Yes.
