### ISSUE TITLE
Kube proxy issue 

### ISSUE THREAD

**Issue by mmanishpandey** [kubernetes/kubernetes#56642]
**Is this a BUG REPORT or FEATURE REQUEST?**:

 /kind bug

**What happened* 

Getting following issue in kube proxy running on master Node 

**What you expected to happen**:

.12.154:6443: getsockopt: connection refused
E1114 19:39:37.146635       1 reflector.go:201] k8s.io/kubernetes/pkg/proxy/config/api.go:49: Failed to list *api.Endpoints: Get https://10.196.12.154:6443/api/v1/endpoints?resourceVersion=0: dial tcp 10.196.12.154:6443: getsockopt: connection refused
E1114 19:39:37.147411       1 reflector.go:201] k8s.io/kubernetes/pkg/proxy/config/api.go:46: Failed to list *api.Service: Get https://10.196.12.154:6443/api/v1/services?resourceVersion=0: dial tcp 10.196.12.154:6443: getsockopt: connection refused
E1114 19:39:38.156190       1 reflector.go:201] k8s.io/kubernetes/pkg/proxy/config/api.go:49: Failed to list *api.Endpoints: Get https://10.196.12.154:6443/api/v1/endpoints?resourceVersion=0: dial tcp 10.196.12.154:6443: getsockopt: connection refused
E1114 19:39:38.156820       1 reflector.go:201] k8s.io/kubernetes/pkg/proxy/config/api.go:46: Failed to list *api.Service: Get https://10.196.12.154:6443/api/v1/services?resourceVersion=0: dial tcp 10.196.12.154:6443: getsockopt: connection refused
E1114 19:39:39.156977       1 reflector.go:201] k8s.io/kubernetes/pkg/proxy/config/api.go:49: Failed to list *api.Endpoints: Get https://10.196.12.154:6443/api/v1/endpoints?resourceVersion=0: dial tcp 10.196.12.154:6443: getsockopt: connection refused
E1114 19:39:39.158919       1 reflector.go:201] k8s.io/kubernetes/pkg/proxy/config/api.go:46: Failed to list *api.Service: Get https://10.196.12.154:6443/api/v1/services?resourceVersion=0: dial tcp 10.196.12.154:6443: getsockopt: connection refused
E1114 19:39:40.157790       1 reflector.go:201] k8s.io/kubernetes/pkg/proxy/config/api.go:49: Failed to list *api.Endpoints: Get https://10.196.12.154:6443/api/v1/endpoints?resourceVersion=0: dial tcp 10.196.12.154:6443: getsockopt: connection refused
E1114 19:39:40.159497       1 reflector.go:201] k8s.io/kubernetes/pkg/proxy/config/api.go:46: Failed to list *api.Service: Get https://10.196.12.154:6443/api/v1/services?resourceVersion=0: dial tcp 10.196.12.154:6443: getsockopt: connection refused
E1114 19:39:41.158537       1 reflector.go:201] k8s.io/kubernetes/pkg/proxy/config/api.go:49: Failed to list *api.Endpoints: Get https://10.196.12.154:6443/api/v1/endpoints?resourceVersion=0: dial tcp 10.196.12.154:6443: getsockopt: connection refused
E1114 19:39:41.160075       1 reflector.go:201] k8s.io/kubernetes/pkg/proxy/config/api.go:46: Failed to list *api.Service: Get https://10.196.12.154:6443/api/v1/services?resourceVersion=0: dial tcp 10.196.12.154:6443: getsockopt: connection refused
E1114 19:39:42.159291       1 reflector.go:201] k8s.io/kubernetes/pkg/proxy/config/api.go:49: Failed to list *api.Endpoints: Get https://10.196.12.154:6443/api/v1/endpoints?resourceVersion=0: dial tcp 10
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4+1a3f593", GitCommit:"1a3f593cf0182255938f48eb2e68110c4c049c54", GitTreeState:"clean", BuildDate:"2017-08-02T18:32:44Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4+59f69d2", GitCommit:"59f69d284801d7df9639d83f4407cad73ea467be", GitTreeState:"clean", BuildDate:"2017-07-24T23:56:46Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
VM 24 GB ram 16 CPU 
- OS (e.g. from /etc/os-release): ORACAL lunix 7.3 
- Kernel (e.g. `uname -a`):Linux den01tdz 4.1.12-61.1.27.el7uek.x86_64 #2 SMP Fri Feb 3 12:31:56 PST 2017 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:
- Others:

**Comment by cblecker** [comment]
Please re-post your question to [Stack Overflow](http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases.

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans Stack Overflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search Stack Overflow for answers to similar questions, and also familiarize yourself with:

  * [user documentation](http://kubernetes.io/docs/)
  * [troubleshooting guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/)

Again, thanks for using Kubernetes.

The Kubernetes Team

---
/kind support
/close
