### ISSUE TITLE
Advanced Audit tests failing in 5k node cluster despite retries

### ISSUE THREAD

**Issue by porridge** [kubernetes/kubernetes#56683]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug
@kubernetes/sig-auth-bugs 
@kubernetes/sig-scalability-misc 
/priority failing-test
/priority critical-urgent
umbrella issue: https://github.com/kubernetes/kubernetes/issues/55194
Please investigate ASAP, this broke a release-blocking job. 

**What happened**:

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-correctness/40 failed with the following despite `--ginkgo.flakeAttempts=2`

```
[sig-auth] Advanced Audit should audit API calls 1m34s
go run hack/e2e.go -v -test --test_args='--ginkgo.focus=\[sig\-auth\]\sAdvanced\sAudit\sshould\saudit\sAPI\scalls$'
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/auth/audit.go:59
error reading audit log
Expected error:
    <http2.StreamError>: {StreamID: 725, Code: 2, Cause: nil}
    stream error: stream ID 725; INTERNAL_ERROR
not to have occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/auth/audit.go:672
```

```
[sig-auth] Advanced Audit should audit API calls 1m42s
go run hack/e2e.go -v -test --test_args='--ginkgo.focus=\[sig\-auth\]\sAdvanced\sAudit\sshould\saudit\sAPI\scalls$'
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/auth/audit.go:59
Expected error:
    <*json.SyntaxError | 0xc422c96300>: {
        msg: "unexpected end of JSON input",
        Offset: 342,
    }
    unexpected end of JSON input
not to have occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/auth/audit.go:665
```

**Comment by crassirostris** [comment]
/assign @loburm 

Please take a look

**Comment by shyamjvs** [comment]
Discussed with @loburm about this offline. There were 2 attempts of the test. One of them failed with:

- 'unexpected end of JSON input' which is coming from [this line](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/auth/audit.go#L665) while parsing an audit log line. IMO we shouldn't be failing the test there as that line maybe:
  - an unrelated log wrt our e2e test (so we don't mind not parsing it)
  - related to our e2e test (in this case also, we don't need to fail here as later we'd anyway fail due to a missing log that we expected for)
- 'stream error: stream ID 725; INTERNAL_ERROR' which is coming while [streaming logs](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/auth/audit.go#L657) from the audit-log file. Given that the audit-log file is huge for our 5k-node cluster, it is possible that the stream maybe broken in b/w. IMO we should add retries there instead of failing.

SG?

**Comment by porridge** [comment]
FWIW, https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-correctness/41 failed again, this time both times with "unexpected end of JSON input"
BTW, since this bug is blocking the release (via #55194) it needs to be added to v1.9 milestone @spiffxp
