### ISSUE TITLE
AssumePod failed when scheduling StatefulSet

### ISSUE THREAD

**Issue by ahume** [kubernetes/kubernetes#56682]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> /kind bug

**What happened**:

Pod created by StatefulSet failed to schedule, with error:

```
AssumePod failed: pod <namespace>/<pod> state wasn't initial but get assumed
```

**What you expected to happen**:

Pod scheduled to node correctly.

**How to reproduce it (as minimally and precisely as possible)**:

I don't yet have reproducible steps, from a fresh cluster. I'm using the Prometheus Operator to create a StatefulSet running alertmanager. I have deleted the StatefulSet and recreated numerous times, but always end up with this error. Changing the name of the StatefulSet fixes the problem.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.8.4-gke.0
- Cloud provider or hardware configuration: GKE
- OS (e.g. from /etc/os-release): Google cos

Also wondering if there is another workaround for this on GKE where I can't restart the scheduler (which I suspect would fix this?)

**Comment by dixudx** [comment]
This pod is supposed to be bound to a node successfully, but failed. However the pod gets assumed in the scheduler cache.

@ahume Have you tried to fully delete the pod and sts, since it may take several mins for gc? And retry again.

/cc @kubernetes/sig-scheduling-bugs

**Comment by jsuchenia** [comment]
I was hit by this problem, restart of all schedulers helped

**Comment by aveshagarwal** [comment]
it seems that https://github.com/kubernetes/kubernetes/pull/54008 should address this. I will see we can cherry pick, if not done already, it for 1.8.

@bsalamat wdyt?

**Comment by bsalamat** [comment]
@aveshagarwal I don't think #54008 addresses this issue. Problems like this happens when entries in scheduler cache are stale. These usually happen when scheduler does not receive update events from etcd (or maybe errors happen when processing the updates). We recently addressed the issue of removed node remaining in scheduler cache. This is somewhat of a similar problem in the sense that cache has stale information, but this one happens for pods. Let me think how we can remedy this when it happens.

**Comment by krmayankk** [comment]
@bsalamat we are experiencing the same issue . Is this fixed in 1.9 ? we are experiencing it quite often, is there any other fix then restarting the schedulers ?

**Comment by bsalamat** [comment]
The cache having stale information or not receiving events is a known issue, but the root-cause is not yet identified. So, 1.9 does not have a fix for the issue.

**Comment by frairon** [comment]
We were facing the same problem using GKE and kubernetes version 1.9.2-gke.1
The only workaround except renaming the components was turning off auto-scaling on the pool.
I'm not sure whether auto-scaling itself triggers the bug or if updating the cluster restarts the kubernetes scheduler.

**Comment by kimocode** [comment]
Experiencing this in 1.8.6, are there any workarounds, for example, invalidating the scheduler's cache?

**Comment by bsalamat** [comment]
I think I have identified an issue in the scheduler logic that causes this. I will run some experiments to ensure that my understanding is correct and will update here.

**Comment by jbrownsc** [comment]
@bsalamat Would love to see an update on the logic you found.  Perhaps there is a workaround identified in that debugging?

**Comment by bsalamat** [comment]
In the case of the current issue where scheduler logs "`AssumePod failed: pod <namespace>/<pod> state wasn't initial but get assumed`", a pod that is being considered for scheduling may be deleted in the middle of scheduling process, leaving the "assume" cache invalid at least temporarily. This happens because scheduler does not use pod UID in its assume cache and uses a pod's namespace and name which can collide with replacement pod created later with the same name and namespace. 
Here are steps that could lead to this error log:
1. Scheduler picks a pod from scheduling queue and tries to schedule it.
2. Scheduler finds a node for the pod and "assumes" the pod.
3. Scheduler kicks off the binding in a separate go routine.
4. Before the bind routine has a chance to run, the pod is deleted and replacement pod is created.
5. Scheduler tries to schedule the replacement pod, but it clashes with the old instance of the pod in the assume cache because scheduler uses "namespace/name" as the key for the pod in its scheduler cache.

This could be seen specially if the API server is busy and the bind takes a long time to finish.
I believe we should use pod UID instead of "namespace/name" as the key in scheduler cache to avoid the above scenario.

**Comment by geosword** [comment]
That description doesn't quite fit with what I am seeing. Specifically:

4. Before the bind routine has a chance to run, the pod is deleted and replacement pod is created.

I'm not deleting my pod, I just create it once using kubectl. "AssumePod failed" is being reported, almost immediately, but as before, the only way it will actually start the pod, is to restart the scheduler.

**Comment by krmayankk** [comment]
@bsalamat does this AssumePod issue apply to StatefulSets only or it can happen in Deployment as well. Although i have never seen it occur for Deployment ? Also any fixes in 1.10 ?

**Comment by gmile** [comment]
@bsalamat I'm facing this very issue. A pod under StatefulSet is stuck in "Pending" state, with the message:

```
Events:
  Type     Reason            Age               From               Message
  ----     ------            ----              ----               -------
  Warning  FailedScheduling  4s (x4 over 52s)  default-scheduler  AssumePod failed: pod logging/elasticsearch-0 state wasn't initial but get assumed
```

If I understand correctly from reading https://github.com/kubernetes/kubernetes/issues/56682#issuecomment-371742634, the issue is that cache gets invalid. Is there a way to "poke" scheduler to invalidate / refresh the cache? Normally I'd have the scheduler `kube-scheduler-k8s-master` pod restarted, but the problem is that I'm on GKE.

**Comment by resouer** [comment]
@gmile Even on GKE, you should be able to delete the scheduler pod, no?

And what's the version you are using btw?

**Comment by gmile** [comment]
@resouer this is all I have in the `kube-system` namespace:

```kubectl get pods --context ehealth-dev -n kube-system
NAME                                      READY     STATUS    RESTARTS   AGE
event-exporter-v0.1.7-5c4d9556cf-jsvf4    2/2       Running   0          49d
fluentd-gcp-v2.0.10-2fhzc                 2/2       Running   1          49d
fluentd-gcp-v2.0.10-rz89c                 2/2       Running   0          49d
heapster-v1.5.0-6884475984-t5kn4          3/3       Running   0          49d
kube-dns-6d4bcb9c6b-wzn4f                 4/4       Running   0          49d
kube-dns-autoscaler-7db47cb9b7-24nlt      1/1       Running   0          49d
kube-proxy-gke-dev-pool-1-bd3dd344-7pfz   1/1       Running   0          49d
kube-proxy-gke-dev-pool-1-bd3dd344-jfm1   1/1       Running   0          49d
kubernetes-dashboard-74f855c8c6-z98wm     1/1       Running   0          49d
l7-default-backend-6497bcdb4d-vhqk7       1/1       Running   1          49d
metrics-server-v0.2.1-7f8dd98c8f-64bwj    2/2       Running   0          49d
stash-operator-666c67d4f5-mdl2k           2/2       Running   1          49d
tiller-deploy-76649fc4f-zmngd             1/1       Running   0          9d
traefik-traefik-f7cd47c9d-mfqng           1/1       Running   0          49d
traefik-traefik-f7cd47c9d-n9dwd           1/1       Running   0          49d
```

Can't see the scheduler pod anywhere. I might be missing something.

Here's the version info:

```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-13T22:29:03Z", GoVersion:"go1.9.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.4-gke.1", GitCommit:"10e47a740d0036a4964280bd663c8500da58e3aa", GitTreeState:"clean", BuildDate:"2018-03-13T18:00:36Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by resouer** [comment]
@gmile what if `kubectl get pods --all-namespaces`?

**Comment by gmile** [comment]
@resouer nothing... weird:

```
$ kubectl get pods --context ehealth-dev --all-namespaces | grep sched
$
```

**Comment by resouer** [comment]
@gmile I see, should be GKE magic :-)

Anyway, we have a fix patch in 1.10: https://github.com/kubernetes/kubernetes/pull/61069, which seems not included in v1.9.4 cc @krmayankk

**Comment by krmayankk** [comment]
@resouer is this a possible fix or a confirmed fix which will resolve this issue ? Also why doesnt this issue happen in Deployment ?

**Comment by resouer** [comment]
@krmayankk It should be THE fix. 

The key point of this bug is "replacement pod with the same name and namespace created", which is common in StatefulSet whose Pod has fixed identity and index, but rare for Deployment as Pods are created with random names.

**Comment by nikhita** [comment]
> @krmayankk It should be THE fix.

@resouer @krmayankk should this be closed given https://github.com/kubernetes/kubernetes/pull/61069 fixes the issue?

/remove-lifecycle stale

**Comment by suveerrao** [comment]
kube-proxy was down on one of the nodes.. rebooting the node has fixed kube-proxy and this issue for me.. hope this helps..

**Comment by krmayankk** [comment]
@nikhita yes please close
