### ISSUE TITLE
Emit useful error with invalid instance types for AWS NLB services

### ISSUE THREAD

**Issue by micahhausler** [kubernetes/kubernetes#56700]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

An error is returned when creating an NLB service on a 1.9 cluster with M3 instance types. (among others)

```
ingress-nginx   2017-11-30 22:13:33 -0300 -03   2017-11-30 22:13:33 -0300 -03   1         ingress-nginx.14fc06957b23cd0c   Service             Warning   CreatingLoadBalancerFailed   service-controller   Error creating load balancer (will retry): failed to ensure load balancer for service ingress-nginx/ingress-nginx: Error registering targets for load balancer: "InvalidTarget: Targets {i-005b2e0924616f909} are not supported\n\tstatus code: 400, request id: d9c4db56-d634-11e7-858b-f9c79dc2380d"
```

**What you expected to happen**:

The NLB should omit the M3 instance as a target

**How to reproduce it (as minimally and precisely as possible)**:

Launch a 1.9 cluster in AWS with an M3 Instance class. Create an NLB service.

**Anything else we need to know?**:

[AWS documents](http://docs.aws.amazon.com/elasticloadbalancing/latest/network/target-group-register-targets.html#register-deregister-targets) which instance types are not available for NLB. 

Kubernetes should not add the specified instance types to the NLB target groups when registering instances by InstanceID (currently the only way Kubernetes registers instances for NLB)

**Environment**:
- Kubernetes version (use `kubectl version`): 1.9 beta
- Cloud provider or hardware configuration: AWS
- OS (e.g. from /etc/os-release): any
- Kernel (e.g. `uname -a`): any

**Comment by justinsb** [comment]
Not entirely sure how we should go about this TBH.  Silently or quietly dropping nodes may be worse behaviour.  It might be better to raise a clear error, because users have a few options - they can change their instance type, or they can set the new annotation to exclude nodes: https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/service/service_controller.go#L72-L74

ELBs still work, so the annotation might be overly broad.  But I also don't think people will be mixing and matching too much.

If we do filter, and we end up with no nodes remaining, that should definitely be an error.  I'm just not sure what we should do if we end up with one or two - users would probably be surprised if everything was being funneled through a small number of nodes.

Did you have an approach in mind?

**Comment by micahhausler** [comment]
Thats a good point. I wouldn't want any surprising behavior, or no nodes in service.

I'll add a PR to the NLB docs about using the `alpha.service-controller.kubernetes.io/exclude-balancer` annotation with older instance types.

Another option is to add another nlb-specific annotation, specifying that targets sohuld be registered by IP address. That would support all instance types, but you would loose the source IP.
