### ISSUE TITLE
Seeing a decrease in scheduler throughput

### ISSUE THREAD

**Issue by shyamjvs** [kubernetes/kubernetes#56714]
Following from an offline discussion.
I'm noticing that the scheduler throughput of our latest successful [5k-node run](https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/67/build-log.txt) seems to be ~300 pods per 10s:

```
I1122 21:22:07.066] Nov 22 21:22:07.065: INFO: Density Pods: 150000 out of 150000 created, 147773 running, 49 pending, 2178 waiting, 0 inactive, 0 terminating, 0 unknown, 0 runningButNotReady 
I1122 21:22:17.020] Nov 22 21:22:17.020: INFO: Density Pods: 150000 out of 150000 created, 148027 running, 53 pending, 1920 waiting, 0 inactive, 0 terminating, 0 unknown, 0 runningButNotReady 
I1122 21:22:26.990] Nov 22 21:22:26.989: INFO: Density Pods: 150000 out of 150000 created, 148310 running, 45 pending, 1645 waiting, 0 inactive, 0 terminating, 0 unknown, 0 runningButNotReady 
I1122 21:22:37.017] Nov 22 21:22:37.017: INFO: Density Pods: 150000 out of 150000 created, 148566 running, 53 pending, 1381 waiting, 0 inactive, 0 terminating, 0 unknown, 0 runningButNotReady 
I1122 21:22:46.998] Nov 22 21:22:46.997: INFO: Density Pods: 150000 out of 150000 created, 148843 running, 56 pending, 1101 waiting, 0 inactive, 0 terminating, 0 unknown, 0 runningButNotReady
```

IIRC it was considerably higher before. Also,

```
E2E startup time for 150000 pods: 1h28m53.009192542s
```

It's weird that it is that high in comparison with [2k-node](https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-large-performance/18/build-log.txt) test:

```
E2E startup time for 60000 pods: 11m10.450099342s
```

/assign @porridge 

cc @kubernetes/sig-scheduling-bugs @kubernetes/sig-scalability-bugs @bsalamat @wojtek-t

**Comment by shyamjvs** [comment]
Indeed it seems like it decreased. Earlier it was:

E2E startup time for 150000 pods: 1h4m31.349005395s (in [run 52](https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/52/build-log.txt))
E2E startup time for 150000 pods: 1h5m11.387550071s (in [run 54](https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/54/build-log.txt))

It's about 1.5 times slower now.

**Comment by bsalamat** [comment]
Are alpha features enabled in these tests? Scheduler uses a new alpha scheduling queue in 1.9. That might be causing the slow down.

**Comment by shyamjvs** [comment]
@bsalamat Are those features turned on by default? Those jobs are mostly following the [default configs](https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/config-test.sh) of kube-up. The only ones we're overriding are [these](https://github.com/kubernetes/test-infra/blob/master/jobs/env/ci-kubernetes-e2e-gce-scale-performance.env).

**Comment by bsalamat** [comment]
@shyamjvs No, the new queue is off by default and the overrides that you linked do not enable it.

**Comment by wojtek-t** [comment]
In the past, the throughput was significantly higher initially, and it was dropping with the number of scheduled pods in the system. Is it still the case? Or is the throughput roughly constant over time this time?

**Comment by shyamjvs** [comment]
Wojtek: IIRC it was constant for almost the whole time at ~300 pods per 10s. Hmm.. that's strange that the throughput was affected by the #scheduled pods already in the system, especially given that we're not even using any affinity-related features.

After thinking a bit, I have the following hypothesis:
- throughput in small clusters is bottlenecked by qps, while in large clusters it is bottlenecked by scheduling computation. This explains why we're scheduling much less than 1000 pods per 10s (even though 100 qps allows for it).
- scheduling computation takes time linear in #nodes (which imo sounds reasonable). This explains why throughput in 2k node (800) is roughly 2.5 times that of 5k node (300). @bsalamat - Could you confirm if this is true?
- The overall E2E times for pod startup I mentioned above (which basically can be called overall scheduling time, as that seemed to be the bottleneck anyway) for 2k node (11m) and 5k node (1h5m) have that much difference because a factor of 2.5 is coming from scheduling speed and another factor of 2.5 is coming from #pods we're creating.

If the above is correct, the only part which remains unexplained is why did we have the increase from 1h5m -> 1h28m? regression?

**Comment by wojtek-t** [comment]
> Wojtek: IIRC it was constant for almost the whole time at ~300 pods per 10s. Hmm.. that's strange that the throughput was affected by the #scheduled pods already in the system, especially given that we're not even using any affinity-related features.

That isn't strange. There is a bunch of things in scheduler that are still dependeng on the number of scheduled pods. One of them is spreading priority.

> scheduling computation takes time linear in #nodes (which imo sounds reasonable). This explains why throughput in 2k node (800) is roughly 2.5 times that of 5k node (300). @bsalamat - Could you confirm if this is true?

That isn't fully true - see above.

**Comment by porridge** [comment]
Obligatory pretty graph. We can clearly see that current best is worse than old worst...

![chart](https://user-images.githubusercontent.com/489420/33543785-9bb4603c-d8d8-11e7-87b7-af74ca052821.png)

**Comment by porridge** [comment]
FWIW, there is a slight decrease in throughput while pods are scheduled, but the rate seems similar, and negligible compared to the drop we're seeing between run 52 and 67.

![time](https://user-images.githubusercontent.com/489420/33546865-79f9ada8-d8e2-11e7-82da-7960f6cc0ff0.png)

**Comment by porridge** [comment]
Seeing that it matches the mean value of the samples in above graphs pretty well, I took a look at the throughput reported in the `Throughput (pods/s) during cluster saturation phase` message in past runs, and it seems that there were several regressions that took it from ~38 pods/sec level to ~28 pods/sec level, not a single one. However I think we should first focus on what happened [between runs 64 and 66](https://github.com/kubernetes/kubernetes/compare/b2625857a...3df3c580b). Let me see if I can reproduce this on a 100-node cluster first.

![throughput-run](https://user-images.githubusercontent.com/489420/33548407-592502bc-d8e7-11e7-8fae-87836ee3428b.png)

![throughput-time](https://user-images.githubusercontent.com/489420/33548291-0870d080-d8e7-11e7-8771-372bd7a938f2.png)

**Comment by porridge** [comment]
Unfortunately on a 100-node cluster the throughput has been almost always exactly `18.75` since the beginning of October - I guess it's bound by something else than scheduler.

**Comment by porridge** [comment]
Interestingly, there is also no recent throughput performance drop in the kubemark-5000 runs:

![kubemark5k](https://user-images.githubusercontent.com/489420/33549699-b26f58be-d8eb-11e7-87f4-44f89e94f37b.png)

**Comment by porridge** [comment]
And the data for the 2k node tests is all over the place:
![large](https://user-images.githubusercontent.com/489420/33550010-b990eb2a-d8ec-11e7-8864-95ec4663c43f.png)

**Comment by wojtek-t** [comment]
In small clusters, it's limited by qps limits.

**Comment by porridge** [comment]
Looks like the way to go ahead is to bisect on a 5k-node cluster :-/

**Comment by wojtek-t** [comment]
Or bump QPS limits in 100-node cluster locally to do bisection.

**Comment by porridge** [comment]
Unfortunately I'm not able to make scheduler the bottleneck in a 100-node test:
```
Dec  4 14:33:22.040: INFO: Created replication controller with name: density3000-0-b1afb355-d8f7-11e7-a13a-ecb1d7404c25, namespace: e2e-tests-density-30-1-xn862, replica count: 3000
I1204 14:33:22.040446   78313 runners.go:178] Created replication controller with name: density3000-0-b1afb355-d8f7-11e7-a13a-ecb1d7404c25, namespace: e2e-tests-density-30-1-xn862, replica count: 3000
Dec  4 14:33:31.486: INFO: Density Pods: 1018 out of 3000 created, 798 running, 219 pending, 1 waiting, 0 inactive, 0 terminating, 0 unknown, 0 runningButNotReady 
Dec  4 14:33:41.486: INFO: Density Pods: 2016 out of 3000 created, 1573 running, 442 pending, 1 waiting, 0 inactive, 0 terminating, 0 unknown, 0 runningButNotReady 
Dec  4 14:33:51.487: INFO: Density Pods: 3000 out of 3000 created, 2454 running, 546 pending, 0 waiting, 0 inactive, 0 terminating, 0 unknown, 0 runningButNotReady 
Dec  4 14:34:01.488: INFO: Density Pods: 3000 out of 3000 created, 3000 running, 0 pending, 0 waiting, 0 inactive, 0 terminating, 0 unknown, 0 runningButNotReady 
Dec  4 14:34:02.049: INFO: E2E startup time for 3000 pods: 40.564111831s
Dec  4 14:34:02.049: INFO: Throughput (pods/s) during cluster saturation phase: 75
STEP: Scheduling additional Pods to measure startup latencies
```
even using the `*_ARGS` settings [from gce-scale-performance](https://github.com/kubernetes/test-infra/blob/master/jobs/env/ci-kubernetes-e2e-gce-scale-performance.env)

**Comment by wojtek-t** [comment]
You can try bumping it even more, though I'm not sure if this won't cause some other issue.

**Comment by bsalamat** [comment]
Thanks guys for looking into this. IIUC, scheduler's throughput is at least 75 pods/s in a 100 node cluster. With this throughput we can achieve our SLO of 1000 pods in 15 seconds. That said, I think we should continue our investigations and make scheduler faster if possible.
One potential problem that I found while looking into scheduler's code several weeks ago is the fact that we keep running all predicates even when some of them have already failed. I am specifically referring to [this loop](https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/scheduler/core/generic_scheduler.go#L441). I think we should break out of the loop when `fit` is false.
@davidopp believes that we continue running all predicates so that we report all the predicates that have failed for the node. I think it'd be fine if we reported just the first predicate that failed, instead of all predicates that failed. An optimization like this will probably not change performance numbers much for scheduling simple pods, but it will probably make things better for pods with more advanced scheduling requirements, particularly affinity/anti-affinity. The effects will be even more visible in large clusters.

We are in the process of adding an order for the execution of predicates. So, predicates with least amount of computation overhead can be executed first and if they fail, we won't run any other predicate.

**Comment by porridge** [comment]
Bobby, we didn't change anything yet, so far I'm just trying
(unsuccessfully) to reproduce the issue of throughput being ~28 in a
5k-node cluster.

**Comment by wojtek-t** [comment]
@bsalamat - as @porridge wrote above, we are not thinking how to improve a scheduler. This issue is all about regressions that happened and we need to investigate it.

**Comment by porridge** [comment]
Still no luck with the following. Looks like I'll need to bring up a full-sized cluster after all:
```
export SCHEDULER_TEST_ARGS='--kube-api-qps=100'
export CONTROLLER_MANAGER_TEST_ARGS='--kube-api-qps=100 --kube-api-burst=100'
export APISERVER_TEST_ARGS='--max-requests-inflight=9000 --max-mutating-requests-inflight=4000'
```

**Comment by shyamjvs** [comment]
@porridge Maybe it's not needed to go all the way till 5000 nodes (which
also our project quota won't allow atm) - can we check if we see some
difference on 1000 or 2000 nodes? Also bisection should be relatively fast
if you run just density test (should take about 2-3 hrs per run iirc).

**Comment by porridge** [comment]
See above, 2k node clusters don't show this regression.

**Comment by porridge** [comment]
I'm also using a doctored density test which runs the bare minimum we need.

**Comment by wojtek-t** [comment]
I looked into a period when the regression happened, and the only PR that seems suspicious to me is https://github.com/kubernetes/kubernetes/pull/51192
It would be surprising to me if this would cause regression, but it may be possible.

**Comment by k82cn** [comment]
Is it possible to enable `pprof` for the scheduler for investigation? It'll show which part is the slowest, and may give a clue on whether it's broken by recently PR.

**Comment by porridge** [comment]
I had some problems bringing up a full-sized cluster. I was finally able to run the test on a 4150-node cluster with the code from 3df3c580b7, and scheduler throughput was ~41.5 pods/s.

**Comment by porridge** [comment]
@k82cn can you point me at rough instructions how to do that?

**Comment by wojtek-t** [comment]
https://github.com/kubernetes/community/blob/930ce65595a3f7ce1c49acfac711fee3a25f5670/contributors/devel/profiling.md

I think profiling is enabled by default in test-env, but I'm not sure. If not - there has to be some flag somewhere.

**Comment by k82cn** [comment]
Regarding the scheduler performance improvement, I'd suggest to open an issue to trace all related ideas here, and evaluate the priority/impact.

**Comment by k82cn** [comment]
> If not - there has to be some flag somewhere.

The flag is `profiling` :).

**Comment by resouer** [comment]
> I am specifically referring to this loop. I think we should break out of the loop when fit is false.

@bsalamat If I remembered correctly, it was a feature requested by user to have all failed predicates reported at once. We may need a option instead of completely remove this logic maybe?

**Comment by porridge** [comment]
Trying to bring up the cluster at b2625857a failed when checking master health. Curiously, I can see the GETs made with curl in `kube-apiserver.log`, and they are all successful (code `200`), but the latency is staggering: initial 10 responses around 4.6s, remaining at around 17 minutes! :open_mouth: 
If anyone wants to take a look at the cluster, it's `gcloud --project=k8s-scale-testing compute ssh --zone us-east1-a e2e-test-porridge-master`. Otherwise I'll resume investigation tomorrow.

**Comment by porridge** [comment]
Re-trying with #56888 applied locally.

**Comment by porridge** [comment]
Turns out the throughput with the same size cluster at b2625857ad is *lower*, ~38 pods/s. :confused: 
![bisect](https://user-images.githubusercontent.com/489420/33672416-6b2b2b0c-daaa-11e7-82ef-f302130a91b6.png)

This is exactly the **opposite** of what we saw with 5k-node clusters, so it's rather surprising.

For lack of better ideas, I think I'm going to try and move the kubemark tests to another project to make space for a 5k-node cluster to reproduce this properly.

**Comment by porridge** [comment]
It took a while, but it seems I was able to reproduce the low throughput (~27.5 pods/s) at 3df3c58 with a proper 5k-node cluster.
 
![1212](https://user-images.githubusercontent.com/489420/33875620-1523b152-df23-11e7-993b-a80da06bed9d.png)

**Comment by porridge** [comment]
At b2625857ad I got ~29.8 pods/s. This is at least higher than what I got at 3df3c58 but still a far cry from what we saw in run 64 at the same commit b2625857ad (~over 33 pods/s).

This suggests that there is something else other than code under test that affects performance of scheduling of those density pods.

**Comment by porridge** [comment]
I started looking at API server's logs for these two runs of b262585 the period:
- starting when all density pods are created,
- ending when all density pods are scheduled.

In the old scheduled test, mean latency is well below 1ms. In the recent manual one - it's all over the place, frequently 3 orders of magnitude higher. I don't know whether latency would affect scheduler throughput, but clearly the conditions of these two runs are radically different.

![auto](https://user-images.githubusercontent.com/489420/33929315-547e3950-dfe9-11e7-814c-ac77685a9836.png)

![manual](https://user-images.githubusercontent.com/489420/33929314-544b2e8e-dfe9-11e7-877f-755b7e9b12e7.png)

**Comment by porridge** [comment]
Actually the above is somewhat misleading. When I look at 50, 90, 100th latency percentiles of kube-scheduler in the period overall, they are nearly identical for both runs:
- old run:  0.001, 0.48, 596 ms
- manual run: 0.002, 0.2, 597 ms

The reason for the above crazy graph is that in the manual run there are mysterious long periods of inactivity. Here are queries per 10s graphs for both runs:

![qps-manual](https://user-images.githubusercontent.com/489420/33933681-c15cbc10-dff6-11e7-9fa4-50624fa85f09.png)
![qps-auto](https://user-images.githubusercontent.com/489420/33933682-c17aeed8-dff6-11e7-8594-fa027cd351a4.png)

**Comment by bsalamat** [comment]
Thanks, @porridge for investigating this issue. So, looks like 90th percentile of API calls is < 1ms. How much scheduler throughput changes with the cluster size. For example, if the cluster has 100 nodes, what is scheduler's throughput. Sorry, if I keep asking this question. I think we should prioritize optimizing for most common scenarios.

**Comment by porridge** [comment]
@bsalamat didn't https://github.com/kubernetes/kubernetes/issues/56714#issuecomment-348929249 answer your question?

**Comment by porridge** [comment]
The spikes in https://github.com/kubernetes/kubernetes/issues/56714#issuecomment-351346087 are possibly connected with the fact that 22 out of 50 RCs continued to create more than the 3000 nodes they were supposed to: 12 of them created 3500, 2 created 4000, 3: 4500, 2: 5000, 2: 5500 and one even 6000.

In total over 171k pods were created, rather than 150k. Given the higher load this generated, and that we already know that scheduler slows down with total number of pods present, the lower observed throughput is not that surprising.

**Comment by porridge** [comment]
Keeping a note of which RCs created how many pods (calculated by counting "Created pod" events in the controller-manager log):
```
 0   4000
 1    4500 
 3    3500 
 4    3500 
 6    3500 
 7    3500 
 8    3500 
 9    3500 
10    5500
11    3500
12    5000   
14    4000   
15    4500   
16    3500   
19    4500   
21    5500   
22    3500   
23    3500   
24    3500   
31    3500   
36    6000  
45    5000   
```

**Comment by porridge** [comment]
@wojtek-t here is how all RCs grew over time
![growth](https://user-images.githubusercontent.com/489420/33980644-0eec108a-e0aa-11e7-8cd4-ad1faef14db8.png)

**Comment by bsalamat** [comment]
> @bsalamat didn't #56714 (comment) answer your question?

@porridge It kind of does, but the fact that [throughput is higher in larger clusters](https://github.com/kubernetes/kubernetes/issues/56714#issuecomment-350987431) does not make sense.

**Comment by porridge** [comment]
@bsalamat that in turn was answered in https://github.com/kubernetes/kubernetes/issues/56714#issuecomment-348932542 :-)

**Comment by porridge** [comment]
Ooops, it seems that the latency graphs for the manual test in https://github.com/kubernetes/kubernetes/issues/56714#issuecomment-351321707 and https://github.com/kubernetes/kubernetes/issues/56714#issuecomment-351346087 were off by an hour - because the test output for manual run was in CET and the master-side logs - in UTC. So I actually graphed latency for the time period when the test was over and the RCs were being deleted.

The pod creations happening in that period are still surprising to me, and perhaps should be investigated, but are likely irrelevant to the question of low scheduler throughput which I'm debugging here.

**Comment by porridge** [comment]
The binding submission request latency for the correct time period of the manual run looks much more in line with the graph from the automatic run:

![manual_](https://user-images.githubusercontent.com/489420/33986669-935da2ca-e0be-11e7-9cd2-4548dd754996.png)

**Comment by bsalamat** [comment]
> @bsalamat that in turn was answered in #56714 (comment) :-)

I saw that too, but it means that we still don't know what is the actual throughput of scheduler itself in a 100 node cluster without rate-limitation, and possible other restrictions.

**Comment by bsalamat** [comment]
In other words, I would like to know if we can count on at least 75 pods/s that you had seen in 100-node clusters.

**Comment by wojtek-t** [comment]
> In other words, I would like to know if we can count on at least 75 pods/s that you had seen in 100-node clusters.

You're asking purely about scheduler right? I'm not sure if the system would be able to handle that throughput in general (if we don't increase master size or sth like that). We would need to check it.

But if we focus just on scheduler, then in most of cases 75 should be easily achievable. But I think if we have many pods with pod affinity/anti-affinity, this would no longer be the case.

**Comment by bsalamat** [comment]
Thanks, @wojtek-t! Yes, I am asking about scheduler and assuming that API server handles the associated load. I am aware that affinity/anti-affinity can drop performance a lot, but we are interested in scheduler's performance in scheduling simple pods, i.e., no fancy spec like affinity/anti-affinity.

**Comment by porridge** [comment]
Adding a graph of CPU usage of kube-scheduler across gce-scale-performance runs. There is a major difference between runs but does not seem to be correlated with the drop in throughput that we're seeing in https://github.com/kubernetes/kubernetes/issues/56714#issuecomment-348924075

![scwqlher1uy](https://user-images.githubusercontent.com/489420/34108869-0f0c7af4-e402-11e7-9ff7-a5d2ab95b26b.png)

**Comment by porridge** [comment]
I ran another test today (blue) with the same commit b262585, on the same cluster that I used in https://github.com/kubernetes/kubernetes/issues/56714#issuecomment-351300904 and obtained a very similar result to the previous one (red).

One interesting thing is how the throughput visibly improved in the last quarter:

![chart 1](https://user-images.githubusercontent.com/489420/34114751-e37fbd26-e413-11e7-8890-4164d06c8311.png).

Whatever changed at that point, made a big difference.

I checked the CPU usage of kube-scheduler with htop a few times during the test and it was between 7.2 and 8.2 cores. Unfortunately I did not look during that last part.

**Comment by porridge** [comment]
I shut down the master, changed it to use `Intel Ivy Bridge` rather than `Intel Broadwell` (which was used so far by that cluster's master) and re-ran the test. Now I can see the throughput observed in the automatic test (34.3 pods/s).

![chart 2](https://user-images.githubusercontent.com/489420/34127744-7cbda3ac-e43e-11e7-8b00-11619760b706.png)

**Comment by porridge** [comment]
Strange things continue: I changed master back to Broadwell and repeated the test, and got the same high-throughput result as with Ivy Bridge. So clearly it's not the variance in CPU type, but perhaps some cache which gets cleared on restart of one of the components.

![chart 3](https://user-images.githubusercontent.com/489420/34144770-5e2a32d4-e493-11e7-9f2d-2cf38b8f185b.png)

**Comment by porridge** [comment]
I bounced a couple of large things in the cluster: the kube-dns deployment and the fluentd-gcp-v2.0.10 daemonset, and ran the test again. This time I got low throughput:
![chart 4](https://user-images.githubusercontent.com/489420/34152112-c1e88dce-e4ad-11e7-8d57-2902e57a9acd.png)

**Comment by porridge** [comment]
I ran another test, and the throughput was similarly low. Then in the middle of the run I restarted kube-scheduler. The throughput did not increase. Then I tried to similarly restart kube-apiserver, but this was not a good decision. With ~100k pods running, ~50k pods still waiting to be scheduled, and ~70 pending, the load on API server is so high that it is not able to recover. Most requests are refused with a 429, and the health checks done by master kubelet fails, causing a crashloop. Bumping the grace period of the health check to several minutes is not enough.

**Comment by porridge** [comment]
Summary of findings so far:
- this slowdown is definitely and certainly not due to a single one code change,
- it is also most likely not connected to code changes at all, but rather something in the context in which the scheduler runs, in particular restarting the master node causes subsequent test to show higher throughput than before restart,
- in general throughput falls as the number of pods in the system rises, however we sometimes see a noticeable throughput *increase* during a test,
- the two points above suggest this may be related to caching effects somewhere (but I confirmed restarting the scheduler alone does not change throughput),
- master VM processor version (Broadwell vs Ivy Bridge) does not seem to have an impact,
- I spent majority of last 2 weeks on this, and don't feel like the above is a lot of progress, and frankly I ran out of ideas how to proceed
- it's not all lost time, though:
  - I learned quite a bit about the system,
  - fixed a couple of bugs: https://github.com/kubernetes/kubernetes/pull/56888 https://github.com/kubernetes/kubernetes/pull/56401
  - tidied up the GCP projects (https://github.com/kubernetes/test-infra/pull/5891 https://github.com/kubernetes/test-infra/pull/5856) which will make future investigations easier and kubemark tests more robust, and
  - uncovered two issues along the way:
    - "kube-apiserver cannot recover under load" #57405 and
    - "Deleting Replication Controllers causes them to create massive amounts of extra pods" #57191

Given:
- the small amount of progress so far despite relatively large time investment,
- relatively small effect on performance (10-20% of scheduler throughput which is not normally the bottleneck except in largest clusters, and the fact that this is not putting us outside SLOs),
- the fact that my test cluster is blocking other users of the testing GCP project

I decided to stop here an un-assign this for now bug. If anyone has some ideas how to approach it, I might come back to this.

**Comment by dhilipkumars** [comment]
cc: @deepak-vij & @shivramsrivastava
