### ISSUE TITLE
admission/webhook: a non-working webhook on namespace lets apiserver launch fail

### ISSUE THREAD

**Issue by sttts** [kubernetes/kubernetes#56761]
Put an admission webhook on the namespace resource which fails (e.g. due to a certificate error). During launch of the apiserver a namespace is created (kube-system? kube-public?) which fails:

```
Dec 03 18:10:28 master-3a4b-0.sur.space hyperkube[11278]: E1203 18:10:28.017345   11278 client_ca_hook.go:78] Internal error occurred: failed calling admission webhook "namespacereservations.admission.online.openshift.io": an error on the server ("tls: failed to find \"CERTIFICATE\" PEM block in certificate input after skipping PEM blocks of the following types: [PUBLIC KEY]") has prevented the request from succeeding
Dec 03 18:10:28 master-3a4b-0.sur.space hyperkube[11278]: F1203 18:10:28.017716   11278 hooks.go:188] PostStartHook "ca-registration" failed: unable to initialize client CA configmap: timed out waiting for the condition
```

Kube-apiserver never starts successfully anymore. You have to recover this cluster e.g. via etcdctl. This is probably not acceptable.

Maybe we have to exclude webhooks from loopback connection?

**Comment by justinsb** [comment]
Perhaps we need a special connection where all these hooks can be skipped, like the `insecure-port` gets us out of authn issues.

**Comment by caesarxuchao** [comment]
This sounds like what [namespaceSelector](https://github.com/kubernetes/kubernetes/blob/050956b08e8bdcec3a7afe91b1be2665a74cc362/staging/src/k8s.io/api/admissionregistration/v1beta1/types.go#L191) is designed for. We can label the kube-system namespace with a run-level label and let webhooks skip the kube-system namespace and resources in it.

**Comment by hzxuzhonghu** [comment]
Similar issue I met #56478, when AdmissionWebhook enabled but admissionregistration.k8s.io/v1beta1 is disabled.

**Comment by sttts** [comment]
> This sounds like what namespaceSelector is designed for.

That should work. For that to work we have to label our kube-* namespaces.

**Comment by caesarxuchao** [comment]
Run-level tracking issue: https://github.com/kubernetes/kubernetes/issues/54522

**Comment by lavalamp** [comment]
Why would apiserver be making namespaces on startup? It should only do that in uninitialized clusters, which shouldn't have webhooks?

**Comment by lavalamp** [comment]
Actually I am going to reopen this. You should not be able to add a webhook which then causes `kube-apiserver` to not start at all. Run levels are about allowing the entire system to bootstrap. apiserver needs to be able to start no matter what webhooks are in; otherwise you have to talk directly to etcd to fix a cluster broken in this way, which IMO is unacceptable.

It also doesn't make sense that this would block apiserver from starting; apiserver must have successfully started previously (or there couldn't be a webhook in the system), so it ought to have made those namespaces already. My hypothesis is that apiserver issues a POST without checking whether the namespaces already exist, and that the webhook feature sends POSTs through the admission chain before they are checked for key violations, so what used to be an "already exists" error is now a "500" error. This seems like a bug, but I'm not sure if it's in the admission stack or the apiserver namespace creation stack.

**Comment by sttts** [comment]
> This seems like a bug, but I'm not sure if it's in the admission stack or the apiserver namespace creation stack.

Good point. I guess it is about kube-system, kube-public and default. I don't see a create though on a second apiserver run:

first run: https://gist.github.com/sttts/98550b68bc9adce6a6e1284a34c9a75e
second run: https://gist.github.com/sttts/d7d2ffb4c45aedc1027df222054cc939

I have to prepare a talk in the next days around admission webhooks. I will try to reproduce the issue.

**Comment by lavalamp** [comment]
@caesarxuchao looked up the code: https://github.com/kubernetes/kubernetes/blob/7fe25af6b1310a567250675f349527d621e3815d/pkg/master/client_ca_hook.go#L77

It definitely has the bug I was talking about :(

Does the audit log not show failed POSTs?

The ordinary path does it correctly: https://github.com/kubernetes/kubernetes/blob/7fe25af6b1310a567250675f349527d621e3815d/pkg/master/controller.go#L204

**Comment by jennybuckley** [comment]
This should be closed I think, because https://github.com/kubernetes/kubernetes/pull/59073 merged.

**Comment by jennybuckley** [comment]
/close
because #59073 merged.
