### ISSUE TITLE
[kube-apiserver] Document default value of --watch-cache-sizes

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#57105]
Is everything on? Everything off? Some special things on?

Update the flag's documentation.

**Comment by yliaog** [comment]
1. the global default value of watch cache size is given by the flag --default-watch-cache-size
2. the global default value can be overridden by the system computed heuristic cache size for the following resources: (https://github.com/kubernetes/kubernetes/blob/46c7ec209ab315656fc271708df46d266474d8f9/pkg/registry/cachesize/cachesize.go#L37)
  a) replicationcontrollers: maxInt(5*clusterSize, 100)
  b) endpoints: maxInt(10*clusterSize, 1000)
  c) nodes: maxInt(5*clusterSize, 1000)
  d) pods: maxInt(50*clusterSize, 1000)
  e) services: maxInt(5*clusterSize, 1000)
  f) apiservices, Group: "apiregistration.k8s.io": maxInt(5*clusterSize, 1000) 
3. the global default in 1. and the system computed heuristic in 2. could be overridden by the flag --watch-cache-sizes

**Comment by yliaog** [comment]
the global default value of watch cache size is 100. It can be overriden by the flag  --default-watch-cache-size

**Comment by MikeSpreitzer** [comment]
There are a total of three relevant command line flags --- `--default-watch-cache-size`, `--watch-cache`, and `--watch-cache-sizes` --- and the syntactic help generated from the code does not tell a new administrator what she needs to know in order to use these flags well.  There needs to be documentation about the semantics of watch caching in general, how these three flags interact with each other and the built-in heuristic, and guidance for how to choose good settings.

**Comment by yliaog** [comment]
I agree it's good to have a doc to explain how the cache should be configured. I think the doc should sit somewhere in the cluster operator guide.

the command line flags can provide brief description, but for more detailed explanations, better leave it for a doc.

https://github.com/kubernetes/community/blob/master/contributors/design-proposals/api-machinery/apiserver-watch.md
is the design doc for the watch cache.

**Comment by MikeSpreitzer** [comment]
I agree.  Thanks for the pointers.

**Comment by cblecker** [comment]
https://github.com/kubernetes/kubernetes/pull/57114 has been opened for this
/remove-help
