### ISSUE TITLE
How can I update the single replica out of three replica of the running POD?

### ISSUE THREAD

**Issue by AnkitVaidya01** [kubernetes/kubernetes#57129]
I have three replicas running on my k8 cluster. I want to upgrade only one replica. So how can I do it?
@wanghaoran1988 @foxylion 
/sig windows
/assign
@kubernetes/sig-windows-feature-requests

**Comment by rjmorse** [comment]
Please re-post your question to [Stack Overflow]
(http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support
are posted so that we can improve our efficiency in responding to your requests,
and to make it easier for you to find answers to frequently asked questions and
how to address common use cases.

We regularly see messages posted in multiple forums, with the full response
thread only in one place or, worse, spread across multiple forums. Also, the
large volume of support issues on github is making it difficult for us to use
issues to identify real bugs.

Members of the Kubernetes community use Stack Overflow to field support
requests. Before posting a new question, please search Stack Overflow for answers 
to similar questions, and also familiarize yourself with:

  * [user documentation](http://kubernetes.io/docs/)
  * [troubleshooting guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/)
