### ISSUE TITLE
Node podCIDR should be EOL'ed

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#57130]
This field was added with best intentions but is too highly coupled to network implementations to be useful.  It sort of acts as a poor-man's IPAM, but it falls down for a number of reasons:

1. Eventually we have to have more than one CIDR, both for dual-stack (#47924) and for IP efficiency (multiple smaller blocks).

2. Not every network plugin wants a single block.

3. Some networks don't use it at all (#45001)

Also xref #56949

What we should do is deprecate the field (since it has no universal meaning) and make this a per-cloud annotation (for clouds that care) which is configured by the cloud controller and consumed by a CNI IPAM driver.  We can make a single IPAM driver that reads a generic annotation, to replace this functionality, and anyone who wants something different can do their own thing.

**Comment by bzub** [comment]
On bare-metal, I assume kube-controller-mananger would still provide `--cluster-cidr` and `--node-cidr-mask-size` options? The only change would be to remove podCIDR from the Node spec and instead write a podCIDR annotation to nodes?

**Comment by thockin** [comment]
I'd say no - all of the flags around CIDR management should go away and
become part of the network plugin subsystem.  If you want the same
behavior, we should produce a "simple IPAM controller" which takes a CIDR,
watches nodes, and decorates them.

There is an open question about if/how other pieces of the system
can/should learn about IPAM.  I lean towards "they should not".

**Comment by andrewsykim** [comment]
I'm in favour of this, I think a reasonable first step we can do now is to allow updates on `node.Spec.PodCIDR`, right now it's an immutable field so people can't remove it from their node objects which makes things confusing when you're trying to move to a solution that no longer relies on the field. Any objections if I open a PR that would allow `node.Spec.PodCIDR` to be removed?

**Comment by thockin** [comment]
I'd rather start at the other end, and figure out the details.  Let's brainstorm.

If we make a CNI IPAM driver that supports reading an annotation we either have to pass the name of that annotation to the IPAM driver (making an out-of-the-box default hard) or we standardize the name (in which case it might as well be a field, maybe?).

If we leave it as a field (maybe deprecate the old and come up with a better structure and name?) we can document it as "just a hint", at least.

Another option could be to make it part of the driver with a fallback of the node OS.   e.g. the on-node "from CIDR" IPAM driver looks for a file with structured data in it.  How that file gets there is irrelevant.  Cloud-specific drivers can get that info from the cloud provider or from an annotation on Node or from metdata servers or whatever.  The fallback is that the host OS can have a cron job that pulls that data from wherever and writes it to the file.  This still doesn't make a great out-of-box experience.

How can we make it so that simple users can `kubeadm` their machine and have it just work, without having polluted the Kubernetes API further?

**Comment by vhosakot** [comment]
I think `kube-controller-manager`'s `--cluster-cidr` should be changed to `--pod-cidr` as it is pod's CIDR (`--cluster-cidr` can still exist so that existing clusters don’t break). Isn't `--pod-cidr` more meaningful than `--cluster-cidr`? Thoughts?

https://kubernetes.io/docs/reference/command-line-tools-reference/kube-controller-manager/

https://github.com/kubernetes/kubernetes/issues/38946 kinda talks about the confusion around `--cluster-cidr` of `kube-controller-manager` which is pod's CIDR.

**Comment by thockin** [comment]
Renaming flags is ugly, and I'd rather compartmentalize the whole problem
if we can -- it's very provider-specific.

**Comment by vhosakot** [comment]
> compartmentalize the whole problem

Agreed, good to compartmentalize it as it could be per-cloud config (not universal) and specific to provider / CNI / if dual-stack or not.

**Comment by caseydavenport** [comment]
I think this would be great to do. I think the way this is done today is a common point of confusion I see regularly for folks getting into Kubernetes networking. 

I think something like what Tim suggested above would be a decent approach, mainly because it makes a clear point that IPAM is a responsibility of a network plugin / extension, and not part of Kubernetes itself. 

Roughly:

- A CNI IPAM plugin which stores allocations on disk (a la host-local), gets configuration from arbitrary node annotations, supports a list of CIDRs perhaps. 
- Pull out the controller which assigns CIDRs to nodes, make it write the annotation.
- Deprecate spec.PodCIDR, switch consumers of it over to the annotation instead. 

> (making an out-of-the-box default hard) or we standardize the name (in which case it might as well be a field, maybe?).

And yeah, I feel this tension as well. I _think_ even with a well-known annotation there is value in breaking the asymmetry that exists today where some implementations use a native field for IPAM and some use some other mechanism. Making it an annotation makes it clear that this is the responsibility of a particular plugin or extension, and that implementations aren't required to respect it.

**Comment by thockin** [comment]
I like the decoupling.  Making the plugins read an arbitrary annotation
moves it down to a node-config problem, which I think seems OK.

E.g.

Foo cloud provider controller observes a node has been assign x.y.z.0/24 in
the fabric.

Foo cloud provider controller writes annotation `foo.com/node-ip-range:
x.y.z.0/24` to the node

On-node plugin config knows that `foo.com/node-ip-range` is the trigger


This gets even better if we follow the readiness gates idea and make the
network config participate in node readiness.

@vishh


As with everything - needs an owner

**Comment by andrewsykim** [comment]
The need for node readiness gates is something that comes up often (e.g. https://github.com/kubernetes/kubernetes/pull/33573). I think in previous discussions in SIG CP we agreed to wait and see how pod readiness gates progress until we adopt the same for nodes. I'm happy to own this and move it forward as it will address some of the other problems we face with node registration with cloud providers. 

As for EOLing `spec.PodCIDR`, I agree with what has already been said. I think a really good starting point is to:
* agree on a set of well known annotations 
* have the existing IPAM controllers update both `spec.PodCIDR` and the well known annotations. 
* push CNI plugins to use the well known annations
* deprecate Spec.PodCIDR - though we can't effectively do this until there is a node v2

Both node readiness gates & EOLing PodCIDR seem they will require KEPs with buy-in from various SIGs. Any objections if I start working on those (likely after KubeCON)?

**Comment by andrewsykim** [comment]
@vishh based on discussions here and in https://github.com/kubernetes/kubernetes/pull/33573 I think there's enough of a need to reopen your KEP (at the very least to continue the discussion).

**Comment by vishh** [comment]
@andrewsykim Acknowledged. I'll work on completing kubernetes/community#2640.

**Comment by andrewsykim** [comment]
@vishh seems like https://github.com/kubernetes/kubernetes/issues/57130 got closed out with the migration to enhancements repo. Will you be able to follow-up on this?

**Comment by matthyx** [comment]
since there's a KEP
/triage accepted

**Comment by sftim** [comment]
Where's the KEP? I'd like to hyperlink to it.

**Comment by matthyx** [comment]
This one, no?
https://github.com/kubernetes/enhancements/tree/0e4d5df19d396511fe41ed0860b0ab9b96f46a2d/keps/sig-network/2450-Remove-knowledge-of-pod-cluster-CIDR-from-iptables-rules

**Comment by aojea** [comment]
> This one, no?
> https://github.com/kubernetes/enhancements/tree/0e4d5df19d396511fe41ed0860b0ab9b96f46a2d/keps/sig-network/2450-Remove-knowledge-of-pod-cluster-CIDR-from-iptables-rules

The issue is about deprecating the field, that KEP is to remove the kube-proxy dependency on that field.

However, the field is still used by other components and CNIs, there is a controller in the controller-manager that manages that field, and it is possible that instead of deprecating the field new funtionality is added
https://github.com/kubernetes/enhancements/pull/1811

**Comment by matthyx** [comment]
Ah, I see, sorry then...
/triage needs-information

**Comment by thockin** [comment]
I am giving up on this dream :)
