### ISSUE TITLE
CSI - Remove unused plugin call  in kube-controller-manager

### ISSUE THREAD

**Issue by vladimirvivien** [kubernetes/kubernetes#57161]
**Is this a BUG REPORT or FEATURE REQUEST?**:
 /kind bug

Listing this as a bug since it's not a feature.

The following if-block, for feature-gate guard, in func `ProbeExpandableVolumePlugins` should be removed all together since the CSI plugin type does not implement ExpandableVolumePlugin interface:

https://github.com/kubernetes/kubernetes/blob/master/cmd/kube-controller-manager/app/plugins.go#L109

**Comment by mlmhl** [comment]
Yes, it should be removed, and this if-block has one more problem: It will add the CSI plugin to `ExpandController` if `CSIPersistentVolume` not enabled. Have you fixed this? If not, can I submit a PR for this?

**Comment by vladimirvivien** [comment]
@mlmhl not fixed yet.  PR welcome :)

**Comment by mlmhl** [comment]
Hi @vladimirvivien 
I read this code again and find that currently only five volume plugins implement `ExpandableVolumePlugin` interface: `aws ebs`, `cinder`, `gce pd`, `glusterfs` and `rbd`, bu we passed all volume plugins to expand controller, include CSI plugin. If we want to remove CSI plugin here, maybe we need to remove all other plugins not implement `ExpandableVolumePlugin` too?

However, we pass all volume plugins to expand controller is also OK, since expand controller will check the expandability of each plugins. So I just post a PR #58182 to fix the if statement, PTAL.

**Comment by vladimirvivien** [comment]
Closed, see #58182
