### ISSUE TITLE
Deleting Replication Controllers causes them to create massive amounts of extra pods

### ISSUE THREAD

**Issue by porridge** [kubernetes/kubernetes#57191]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug
@kubernetes/sig-apps-bugs 

**What happened**:
This was noticed in https://github.com/kubernetes/kubernetes/issues/56714#issuecomment-351631811

sig-scalability's large-scale [density test](https://github.com/kubernetes/kubernetes/blob/ceda4c3/test/e2e/scalability/density.go#L256-L277) created 50 RCs, each of them set to create 3000 pods at around 11:53.

The following graph shows the cumulative number of "Created pod" events in the controller-manager log. 

![growth](https://user-images.githubusercontent.com/489420/33986223-417f9ee6-e0bd-11e7-91eb-6fdd79652ebb.png)

The test then waited until all pods are created (which was done at ~12:16). Then it waited until all pods scheduled (flat lines on the following graph).

So far so good.

The unexpected thing started at ~13:16, when the test started deleting RCs.

Some (but not all) RCs started creating massive amount of pods. As shown by the graph,  one reached 6000 nodes in total.

**What you expected to happen**:

No new pod creation events should happen when RCs are being deleted.

**Comment by enisoc** [comment]
It seems like the [cleanup code](https://github.com/kubernetes/kubernetes/blob/ceda4c31f99315c540fcf0cbcd5b6d1a9d3a7d8f/test/e2e/scalability/density.go#L308-L334) uses the GC for RCs.

It could be that the RC does not yet know it's deleted because of watch latency or dropped events, and is fighting with the GC. We do a cache-bypassing read to prevent this race during GC orphaning, because in that case the race could result in a permanently broken state. We don't do that for GC deletion, because the state should eventually converge to the correct one once RC catches up on watch events or does a periodic cache resync.

I think this could explain the behavior in your graph. The cleanup code goes through one RC at a time, and each one tends to have a spike of creations when its turn comes around. This is likely due to watch latency under high load, combined with burst Pod creation. In some cases, the RC continues to fight the GC for a while; this could be due to a dropped event in the watch stream, or just really bad latency.

cc @caesarxuchao

**Comment by enisoc** [comment]
Hm on second thought maybe the GC prevents this by waiting for ObservedGeneration. Will need more investigation or someone with expertise.

**Comment by enisoc** [comment]
On third thought, ObservedGeneration wouldn't help here because we delete the RC in [background mode](https://github.com/kubernetes/kubernetes/blob/95552b077e57d5d0d22b9f9314e51e1b74a63d6b/test/e2e/framework/util.go#L3000), so the actual RC object is immediately gone (no chance to coordinate via ObservedGeneration). I also didn't find anything in the GC code that mentions generation.

So, I'll stick to my first thought for now.

**Comment by enisoc** [comment]
cc @kubernetes/sig-apps-bugs for a fourth opinion.

**Comment by liggitt** [comment]
GC doesn't use generation.

**Comment by mattfarina** [comment]
cc: @caesarxuchao @lavalamp

**Comment by porridge** [comment]
@shyamjvs FYI

**Comment by mattfarina** [comment]
cc @kow3ns
