### ISSUE TITLE
Add PROXY protocol support for AWS Network Load Balancers

### ISSUE THREAD

**Issue by micahhausler** [kubernetes/kubernetes#57250]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature
/sig aws

**Anything else we need to know?**:

AWS has added support for [PROXY protocol on Network Load Balancers](http://docs.aws.amazon.com/elasticloadbalancing/latest/network/load-balancer-target-groups.html#target-group-attributes), which is very useful if nodes are registered by IP address (See #57249) to get the original client IP to the end pods.

**Comment by jnicholls** [comment]
Would love to see the `service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"` annotation flip on the PROXY support for `service.beta.kubernetes.io/aws-load-balancer-type: "nlb"` network load balancer Services.

**Comment by itskarthikholla** [comment]
Hi @micahhausler Does kubernetes  support Proxy protocol for NLB ? What is the current status ?

**Comment by micahhausler** [comment]
@itskarthikholla  it isn't supported right now

/reopen

**Comment by ajfriesen** [comment]
I am not a developer and just started learning go but I want to know if this could be a low hanging fruit?
Maybe this is possible to solve for me with some guidance?!

I checked the go package which already provides the value to enable Proxy Protocol V2 for the target groups:

```
    // The following attribute is supported only by Network Load Balancers:
    //
    //    * proxy_protocol_v2.enabled - Indicates whether Proxy Protocol version
    //    2 is enabled. The value is true or false. The default is false.
    Key *string `type:"string"`
```

[Proxy Protocol in Go package elbv2](https://docs.aws.amazon.com/sdk-for-go/api/service/elbv2/#TargetGroupAttribute)

There is already an annotation which will check if proxy protocol is enabled:
 ```ServiceAnnotationLoadBalancerProxyProtocol = "service.beta.kubernetes.io/aws-load-balancer-proxy-protocol"``` 

Could this be used to enable this setting on aws?

**Comment by tsuna** [comment]
Things mostly work when I enable PROXY protocol on the target group and configure it on the nginx ingress, the only thing that seems broken is that the healthchecks don't work.  When I `tcpdump` I see a weird packet that precedes the `GET` for the healthcheck. Here's the `tcpdump` output immediately following the 3-way handshake:
```
00:07:54.980271 IP 172.20.35.89.21603 > 172.20.50.61.30922: Flags [P.], seq 1:101, ack 1, win 229, length 100
    0x0000:  4500 008c ea27 4000 e806 fa84 ac14 2359  E....'@.......#Y
    0x0010:  ac14 323d 5463 78ca 9572 76ee 38e0 1877  ..2=Tcx..rv.8..w
    0x0020:  5018 00e5 db13 0000 0d0a 0d0a 000d 0a51  P..............Q //<---- notice the "QUIT" in ASCII here
    0x0030:  5549 540a 2011 0054 0300 04bc e595 1f04  UIT....T........
    0x0040:  004a 0000 0000 0000 0000 0000 0000 0000  .J..............
    0x0050:  0000 0000 0000 0000 0000 0000 0000 0000  ................
    0x0060:  0000 0000 0000 0000 0000 0000 0000 0000  ................
    0x0070:  0000 0000 0000 0000 0000 0000 0000 0000  ................
    0x0080:  0000 0000 0000 0000 0000 0000            ............
00:07:54.980288 IP 172.20.50.61.30922 > 172.20.35.89.21603: Flags [.], ack 101, win 53, options [nop,nop,TS val 45104841 ecr 2996819529], length 0
    0x0000:  4500 0034 26be 4000 4006 6647 ac14 323d  E..4&.@.@.fG..2=
    0x0010:  ac14 2359 78ca 5463 38e0 1877 9572 7752  ..#Yx.Tc8..w.rwR
    0x0020:  8010 0035 ade5 0000 0101 080a 02b0 3ec9  ...5..........>.
    0x0030:  b29f d649                                ...I
00:07:54.980294 IP 172.20.35.89.21603 > 172.20.50.61.30922: Flags [P.], seq 101:236, ack 1, win 229, options [nop,nop,TS val 2996819529 ecr 45104806], length 135
    0x0000:  4500 00bb ea27 4000 e806 fa55 ac14 2359  E....'@....U..#Y
    0x0010:  ac14 323d 5463 78ca 9572 7752 38e0 1877  ..2=Tcx..rwR8..w
    0x0020:  8018 00e5 5bc4 0000 0101 080a b29f d649  ....[..........I
    0x0030:  02b0 3ea6 4745 5420 2f68 6561 6c74 687a  ..>.GET./healthz // <---- actual HTTP request but WTF is the QUIT packet before?!
    0x0040:  2048 5454 502f 312e 310d 0a48 6f73 743a  .HTTP/1.1..Host:
    0x0050:  2031 3732 2e32 302e 3335 2e38 393a 3830  .172.20.35.89:80
    0x0060:  0d0a 436f 6e6e 6563 7469 6f6e 3a20 636c  ..Connection:.cl
    0x0070:  6f73 650d 0a55 7365 722d 4167 656e 743a  ose..User-Agent:
    0x0080:  2045 4c42 2d48 6561 6c74 6843 6865 636b  .ELB-HealthCheck
    0x0090:  6572 2f32 2e30 0d0a 4163 6365 7074 3a20  er/2.0..Accept:.
    0x00a0:  2a2f 2a0d 0a41 6363 6570 742d 456e 636f  */*..Accept-Enco
    0x00b0:  6469 6e67 3a20 2a0d 0a0d 0a              ding:.*....
00:07:54.980301 IP 172.20.50.61.30922 > 172.20.35.89.21603: Flags [.], ack 236, win 55, options [nop,nop,TS val 45104841 ecr 2996819529], length 0
    0x0000:  4500 0034 26bf 4000 4006 6646 ac14 323d  E..4&.@.@.fF..2=
    0x0010:  ac14 2359 78ca 5463 38e0 1877 9572 77d9  ..#Yx.Tc8..w.rw.
    0x0020:  8010 0037 ade5 0000 0101 080a 02b0 3ec9  ...7..........>.
    0x0030:  b29f d649                                ...I
00:07:54.980348 IP 172.20.50.61.30922 > 172.20.35.89.21603: Flags [P.], seq 1:104, ack 236, win 55, options [nop,nop,TS val 45104841 ecr 2996819529], length 103
    0x0000:  4500 009b 26c0 4000 4006 65de ac14 323d  E...&.@.@.e...2=
    0x0010:  ac14 2359 78ca 5463 38e0 1877 9572 77d9  ..#Yx.Tc8..w.rw.
    0x0020:  8018 0037 ae4c 0000 0101 080a 02b0 3ec9  ...7.L........>.
    0x0030:  b29f d649 4854 5450 2f31 2e31 2034 3030  ...IHTTP/1.1.400
    0x0040:  2042 6164 2052 6571 7565 7374 0d0a 436f  .Bad.Request..Co
    0x0050:  6e74 656e 742d 5479 7065 3a20 7465 7874  ntent-Type:.text
    0x0060:  2f70 6c61 696e 3b20 6368 6172 7365 743d  /plain;.charset=
    0x0070:  7574 662d 380d 0a43 6f6e 6e65 6374 696f  utf-8..Connectio
    0x0080:  6e3a 2063 6c6f 7365 0d0a 0d0a 3430 3020  n:.close....400.
    0x0090:  4261 6420 5265 7175 6573 74              Bad.Request
```
This can be seen also when `strace`ing `kube-proxy`:
```
[pid  9336] read(12, "\r\n\r\n\0\r\nQUIT\n \21\0T\3\0\4\274\345\225\37\4\0J\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0GET /healthz HTTP/1.1\r\nHost: 172.20.35.89:80\r\nConnection: close\r\nUser-Agent: ELB-HealthChecker/2.0\r\nAccept: */*\r\nAccept-Encoding: *\r\n\r\n", 4096) = 235
[pid  9336] write(12, "HTTP/1.1 400 Bad Request\r\nContent-Type: text/plain; charset=utf-8\r\nConnection: close\r\n\r\n400 Bad Request", 103) = 103
```
This weird packet doesn't show up when proxy protocol isn't enabled.

**Comment by tsuna** [comment]
Looking at the [PROXY protocol spec](https://www.haproxy.org/download/1.8/doc/proxy-protocol.txt), this makes more sense now:

> So the 16-byte version 2 header can be described this way :
> ```c
>     struct proxy_hdr_v2 {
>         uint8_t sig[12];  /* hex 0D 0A 0D 0A 00 0D 0A 51 55 49 54 0A */
>         uint8_t ver_cmd;  /* protocol version and command */
>         uint8_t fam;      /* protocol family and address */
>         uint16_t len;     /* number of following bytes part of the header */
>     };
> ```

Which is consistent with that first packet:
```
    0x0020:  5018 00e5 db13 0000 0d0a 0d0a 000d 0a51  P..............Q
                                 <--------sig[12]---
    0x0030:  5549 540a 2011 0054 0300 04bc e595 1f04  UIT....T........
             --------> ^^<> <--> <------... 84 bytes that follow
                       | fam  ^-len = 84 bytes
               ver_cmd-'
    0x0040:  004a 0000 0000 0000 0000 0000 0000 0000  .J..............
    0x0050:  0000 0000 0000 0000 0000 0000 0000 0000  ................
    0x0060:  0000 0000 0000 0000 0000 0000 0000 0000  ................
    0x0070:  0000 0000 0000 0000 0000 0000 0000 0000  ................
    0x0080:  0000 0000 0000 0000 0000 0000            ............
```

and the AWS [documentation](https://docs.aws.amazon.com/elasticloadbalancing/latest/network/load-balancer-target-groups.html#proxy-protocol) says:
> After you enable Proxy Protocol, the Proxy Protocol header is also included in health check connections from the load balancer. However, with health check connections, the client connection information is not sent in the Proxy Protocol header.

So it seems that `kube-proxy` simply doesn't expect the healthcheck itself to be PROXY'ed.

**Comment by ajfriesen** [comment]
@tsuna 
I do not understand where do you do the health checks?

**Comment by tsuna** [comment]
AWS' NLB healthchecks the targets to know which ones to send traffic to. From what I understand, every node in the cluster is added as a target but only those nodes that actually run an instance of the ingress will pass the healthcheck and therefore be eligible to receive traffic.  With the fun caveat that when all the nodes fail their healthcheck (e.g. due to the issue above) then NLB just uniformly sprays the traffic across all the targets, which _guarantees_ that X% of the traffic will be dropped on the floor, where X = number of nodes running the ingress divided by total number of nodes.

**Comment by aranair** [comment]
> AWS' NLB healthchecks the targets to know which ones to send traffic to. From what I understand, every node in the cluster is added as a target but only those nodes that actually run an instance of the ingress will pass the healthcheck and therefore be eligible to receive traffic. With the fun caveat that when all the nodes fail their healthcheck (e.g. due to the issue above) then NLB just uniformly sprays the traffic across all the targets, which _guarantees_ that X% of the traffic will be dropped on the floor, where X = number of nodes running the ingress divided by total number of nodes.

Isn't this only the case when `externalTrafficPolicy` is set to Local? If that is set to Cluster, the health check would be done on the traffic port (and since the port is opened up on all the nodes, they should all pass the health checks.)

Side note, I enabled proxy support on the target groups of a cluster-health-checked NLB that health-checks on the traffic port and it seems to work fine.. hmmm.

**Comment by dreverri** [comment]
Yes, this is related to `externalTrafficPolicy: Local`. A cluster health checked NLB will use a TCP health check on the traffic port which won't care about the proxy protocol:
https://github.com/kubernetes/kubernetes/blob/d7103187a37dcfff79077c80a151e98571487628/pkg/cloudprovider/providers/aws/aws.go#L3409

If `externalTrafficPolicy` is `Local`, Kubernetes forces the allocation of a health check node port:
https://github.com/kubernetes/kubernetes/blob/eb6a1b651c43aa74d2dfcf2ca6115f77cb06b6ce/pkg/registry/core/service/storage/rest.go#L197

The presence of `service.Spec.HealthCheckNodePort` creates an HTTP based health check which fails when proxy protocol support is enabled.
https://github.com/kubernetes/kubernetes/blob/1c557b9ce866d67ec6088f37058e8594b89606ee/staging/src/k8s.io/cloud-provider/service/helpers/helper.go#L76
https://github.com/kubernetes/kubernetes/blob/d7103187a37dcfff79077c80a151e98571487628/pkg/cloudprovider/providers/aws/aws.go#L3451

This means that proxy protocol support does not work when `externalTrafficPolicy` is `Local` which means there is no way to preserve the client source IP when using an NLB.

Manually creating an NLB with proxy protocol support enabled and TCP based health checks to the traffic port seems to work fine when `externalTrafficPolicy` is `Local`. I'm not sure why Kubernetes requires an HTTP health check when `externalTrafficPolicy` is `Local`.

**Comment by brunojcm** [comment]
I just started testing enabling proxy protocol on my setup here, I have
`service.beta.kubernetes.io/aws-load-balancer-type: nlb`
`externalTrafficPolicy: Cluster`

The issue I was experiencing, as expected, is that my upstream apps were receiving `X-Forwarded-For` headers with cluster-local addresses since cluster policy (`externalTrafficPolicy: Cluster`) needs SNAT.

I just had to do two things to make it work:
1. Change my config map to look like this
```
kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-configuration
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
data:
  use-proxy-protocol: "true"
```
2. Go to the NLB in the AWS web console and enable `Proxy protocol v2` for all my target groups connected to the NLB.
<img width="494" alt="image" src="https://user-images.githubusercontent.com/251695/58475749-67939400-8181-11e9-9a35-a0adbfd4aff8.png">

It seems NLB takes a few seconds to in fact enable the proxy protocol, but after a short breakage everything is working fine so far. All my upstream servers are now receiving the real ip instead of the cluster-internal one.

I ended up finding this issue through https://github.com/kubernetes/ingress-nginx/issues/3857, but I'm really confusing as to why they closed that issue saying "Ok, so kuberentes needs to implement this first before it can be used in the nginx ingress controller itself!".

Can someone clarify what's really missing and how anyone interested could help? I understand we need to have some annotation like (disclaimer: this doesn't exist yet, don't copy!) `service.beta.kubernetes.io/aws-nls-proxy-enabled: true`, but this seems more like a ingress job, not a "kubernetes" one.

**Comment by tsuna** [comment]
@brunojcm what version of k8s are you on? Can you check that your target groups are passing health checks? When I enabled proxy protocol exactly as you described above, all the targets are showing as unhealthy, because NLB is using the PROXY protocol to perform the health check as well, which k8s doesn't support.
<img width="1199" alt="NLB targets all unhealthy" src="https://user-images.githubusercontent.com/128281/58617932-347efc80-8276-11e9-8655-cbdb01ad6987.png">

When all the targets are unhealthy you will have the incorrect impression that things work because NLB will just spread the requests across all the nodes in the cluster, but only those nodes that run an ingress pod will be able to serve the requests. So things will more or less mostly work, except for the unlucky requests that land on the "wrong" nodes.

**Comment by brunojcm** [comment]
@tsuna They are healthy!
![image](https://user-images.githubusercontent.com/251695/58629541-52e50680-830f-11e9-9a0a-159e4b63828c.png)

@aranair said the following [above](#issuecomment-484921203), that might explain why health checks pass:
> Isn't this only the case when externalTrafficPolicy is set to Local? If that is set to Cluster, the health check would be done on the traffic port (and since the port is opened up on all the nodes, they should all pass the health checks.)

How is your `externalTrafficPolicy` set?

> what version of k8s are you on?
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.6-eks-d69f1b", GitCommit:"d69f1bf3669bf00b7f4a758e978e0e7a1e3a68f7", GitTreeState:"clean", BuildDate:"2019-02-28T20:26:10Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}

Well, I'm afraid I can't help much... Still learning k8s.

**Comment by tsuna** [comment]
ah thanks @brunojcm, I had missed the piece about setting the `externalTrafficPolicy` to `Cluster` instead of `Local`. NLB + PROXY protocol works fine now, even though the AWS console still shows all the nodes as unhealthy.

Previously when they were showing nodes as unhealthy I would see 25% of the traffic getting dropped (I have 4 nodes and 3 replicas of the nginx ingress, so the traffic that landed on the node without an ingress would get dropped), but I haven't observed any loss yet, for some reason things seem to be working fine now.

**Comment by smrutiranjantripathy** [comment]
> > AWS' NLB healthchecks the targets to know which ones to send traffic to. From what I understand, every node in the cluster is added as a target but only those nodes that actually run an instance of the ingress will pass the healthcheck and therefore be eligible to receive traffic. With the fun caveat that when all the nodes fail their healthcheck (e.g. due to the issue above) then NLB just uniformly sprays the traffic across all the targets, which _guarantees_ that X% of the traffic will be dropped on the floor, where X = number of nodes running the ingress divided by total number of nodes.
> 
> Isn't this only the case when `externalTrafficPolicy` is set to Local? If that is set to Cluster, the health check would be done on the traffic port (and since the port is opened up on all the nodes, they should all pass the health checks.)
> 
> Side note, I enabled proxy support on the target groups of a cluster-health-checked NLB that health-checks on the traffic port and it seems to work fine.. hmmm.

Hi ,
I enabled proxy support + externalTrafficPolicy: Cluster . The NLB endpoint responded to requests but after a while it started showing me  400 Bad Request. Enabling the proxy-support breaks the NLB. 
And most surprising thing is even if it is showing 400 to Bad Request to curl , the target group shows all targets as healthy.
Any thoughts about it.

**Comment by brunojcm** [comment]
@tsuna Is your VPC CNI plugin updated? Maybe that is affecting these health checks somehow. Mine is now at version 1.4.1, it was 1.2.1 before, both seem to work well in this regard.
Ref.: https://docs.aws.amazon.com/eks/latest/userguide/cni-upgrades.html

**Comment by tsuna** [comment]
I'm using the AWS VPC CNI version 1.4.1 as well.

**Comment by frittentheke** [comment]
@smrutiranjantripathy with ExternalTrafficPolicy=Local and an attachment of type "instance" of the nodes to your NLB the source IP of the incoming connection is preserved. Using PROXY protocol, for that reason, seems unnecessary then. I've run into issues with Kubernetes 1.13.7 still applying SNAT (with the ClusterIP) to such traffic causing the source IP to be overwritten/SNATTed away again.
And looking at the many many issues with health checks and External Traffic policies this area still seems buggy.

But... this particular issue should be seen in a more generic manner: Services of Type Loadbalancer can be switched to be of type NLB. But contrary to ELBs / classic loadbalancers there is no annotation to control the PROXY protocol being enabled or not. See: https://kubernetes.io/docs/concepts/services-networking/#proxy-protocol-support-on-aws

**Comment by jstaf** [comment]
So I tried this out on a few staging clusters and it appears to be work just fine - here are the steps (these instructions assume you're using nginx-ingress with an AWS NLB load balancer):

* Make sure `externalTrafficPolicy` for nginx-ingress is set to `Cluster`
* Enable proxy protocol v2 in the NLB target groups manually via the AWS EC2 dashboard (click on the target group and hit "edit attributes").
* Enable proxy protocol in the nginx-ingress controller, by setting `use-proxy-protocol: "true"` in the nginx-ingress-controller ConfigMap.

Just as a warning - all network traffic will be absolutely borked during the time between when you activate proxy protocol in the AWS dashboard and the nginx-ingress-controller. They both have to have proxy protocol activated at the same time or the nginx-ingress-controller cannot understand the incoming traffic. Ideally you'd do those changes at the same time, but sometimes the changes for the AWS NLB can lag for a few minutes and you'll drop traffic during that time.

@smrutiranjantripathy You need to have proxy protocol enabled on your nginx-ingress-controller or it cannot understand traffic coming in from the NLB.

**Comment by lmgnid** [comment]
It has been over 2 years, cannot believe we still cannot set "Proxy protocol v2" directly without manual works with AWS GUI/CLI :-(

**Comment by jnicholls** [comment]
Yeah, it is a shame the AWS cloud provider implementation has not solved this by now.

I did create https://github.com/jnicholls/k8s-aws-nlb-proxy-protocol-operator to fill the gap as a simple Kubernetes Operator, allowing you to use the standard `service.beta.kubernetes.io/aws-load-balancer-proxy-protocol` annotation to turn on PROXYv2 support on an NLB.

I have to get back to it to clean it up, switch away from some base container things that my company expected but that no longer matter, and write some documentation on running it. It definitely works well for automatically turning on and off PROXYv2 support for NLBs based on the presence of that annotation. I can post back here when it's ready for easy public consumption, but feel free to try it out on your own if you don't mind a little self-education on building the project and Docker container.

**Comment by angegar** [comment]
I am encountering the same issue today and I don't want to go in production with unhealthy instances in my target group. 

Is there a way to fix this ?

**Comment by ysaakpr** [comment]
Looks like the community doesn't want to support new features from AWS I guess.

**Comment by demisx** [comment]
I confirm that with removed `use-proxy-protocol: 'true'` from ingress config map (e.g. no proxy protocol enabled) and this in the ingress:

```yaml
controller:
  service:
        type: LoadBalancer
        externalTrafficPolicy: Local
        annotations:
          service.beta.kubernetes.io/aws-load-balancer-type: nlb
```

the Network Load Balancer is created with healthy nodes in each target and the client IP is preserved. I am using the latest nginx-ingress `v1.36.3` .

**Comment by raelga** [comment]
Is not recommend to use `externalTrafficPolicy: Local`, as you will impact on the load balancing.

https://medium.com/pablo-perez/k8s-externaltrafficpolicy-local-or-cluster-40b259a19404

**Comment by demisx** [comment]
@raelga Thank you for sharing. Unfortunately, we still need `externalTrafficPolicy: Local` in order to preserve the client IP address.

**Comment by Josbrafe** [comment]
@jstaf. What version of ingress controller are you currently running in your cluster?
Tested version version: 1.36.3 and 1.39.0, base on the below comments: 
Configs: 

controller:
  config:
    use-proxy-protocol: "true"
    real-ip-header: "proxy_protocol"

  service:
    type: LoadBalancer
    externalTrafficPolicy: Cluster
    annotations:
        service.beta.kubernetes.io/aws-load-balancer-type: nlb
        service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: 'tcp'




Error: 
* Closing connection 0
curl: (35) error:1408F10B:SSL routines:ssl3_get_record:wrong version number

> So I tried this out on a few staging clusters and it appears to be work just fine - here are the steps (these instructions assume you're using nginx-ingress with an AWS NLB load balancer):
> 
> * Make sure `externalTrafficPolicy` for nginx-ingress is set to `Cluster`
> * Enable proxy protocol v2 in the NLB target groups manually via the AWS EC2 dashboard (click on the target group and hit "edit attributes").
> * Enable proxy protocol in the nginx-ingress controller, by setting `use-proxy-protocol: "true"` in the nginx-ingress-controller ConfigMap.
> 
> Just as a warning - all network traffic will be absolutely borked during the time between when you activate proxy protocol in the AWS dashboard and the nginx-ingress-controller. They both have to have proxy protocol activated at the same time or the nginx-ingress-controller cannot understand the incoming traffic. Ideally you'd do those changes at the same time, but sometimes the changes for the AWS NLB can lag for a few minutes and you'll drop traffic during that time.
> 
> @smrutiranjantripathy You need to have proxy protocol enabled on your nginx-ingress-controller or it cannot understand traffic coming in from the NLB.

**Comment by raelga** [comment]
> @raelga Thank you for sharing. Unfortunately, we still need `externalTrafficPolicy: Local` in order to preserve the client IP address.

For my use case, using `externalTrafficPolicy: Local` was not an option due to the impact on performance and resilience. I ended developing a new Kubernetes operator/controller to manage the NLB Target Group attributes using annotations in the service object.

For this use case, allows enabling the `Proxy-Protocol` on service creation using the `aws-nlb-helper.3scale.net/enable-targetgroups-proxy-protocol: "true"` annotation. With proxy protocol, if is supported by the app/web server, the client IP will be available with `externalTrafficPolicy` set to `Cluster`.  

Is in the early stages, but it works and is quite inoffensive.

https://github.com/3scale/aws-nlb-helper-operator

**Comment by mikewied** [comment]
Is there anyone on this issue that is an owner for the AWS code base in Kubernetes? I can submit a patch to resolve this, but I think there are a few options to do so and think we should get consensus on how to make the change.

1) Amazon allows disabling proxy protocol on health checks. This would need to be done by an internal team at Amazon and I suspect this would be challenging to get scheduled even if they wanted to add it.
2) Add proxy protocol support to health checks. I suspect that the Kubernetes community will not want to take this change because my understanding is that you cannot support both proxy protocol on and off at the same time. This means that there would need to be an annotation or parameter in the service config that would enable proxy protocol on the health check. Given that this is so far specific to AWS network load balancers and not a general issue I suspect that the Kubernetes community would want Amazon to support option 1 above as opposed to adding this special case.
3) Add annotations for the nlb load balancer to allow specifying the health check port and path. This would allow users to add a health check api on their proxy or application which already supports proxy protocol. With these annotations a corresponding change could be made on the AWS load balancer controller to make the proxy protocol annotation actually have an affect on nlb load balancers and users would just need to configure their health check port and path in the annotations to make everything work correctly when externalTrafficPolicy is set to local.

**Comment by TBBle** [comment]
The annotations needed for option 3 should land in k8s 1.20. #92556 has been approved, but appears to be waiting for the 1.19 release to be completed.

**Comment by adnan-kamili** [comment]
I use following script to enable proxy protocol on target groups after installing ingress-inginx:

```
hostname=$(kubectl get services ingress-nginx-controller --output jsonpath='{.status.loadBalancer.ingress[0].hostname}')
loadBalancerArn=$(aws elbv2 describe-load-balancers  --query "LoadBalancers[?DNSName==\`$hostname\`].LoadBalancerArn"  --output text)
targetGroup1Arn=$(aws elbv2 describe-target-groups --load-balancer-arn $loadBalancerArn --query TargetGroups[0].TargetGroupArn --output text)
targetGroup2Arn=$(aws elbv2 describe-target-groups --load-balancer-arn $loadBalancerArn --query TargetGroups[1].TargetGroupArn --output text)
aws elbv2 --region us-east-1 modify-target-group-attributes --target-group-arn $targetGroup1Arn --attributes Key=proxy_protocol_v2.enabled,Value=true --output text
aws elbv2 --region us-east-1 modify-target-group-attributes --target-group-arn $targetGroup2Arn --attributes Key=proxy_protocol_v2.enabled,Value=true --output text

```

**Comment by TBBle** [comment]
A thought on option 3. It might be possible for the AWS Cloud Provider (or a LB-specific controller, see https://github.com/aws/containers-roadmap/issues/981#issuecomment-657634101) to auto-create a nodeport health check with proxy-protocol support as you describe, as part of applying the Service to an NLB. This would be similar to the way that currently a nodeport health-check HTTP service is created by kube-proxy for `externalTrafficPolicy: Local` Services.

That way, the user doesn't need to do anything special to support health-checks when they enable proxy protocol on NLB.

The advantage of this approach is that it keeps the AWS-specific details in AWS-specific services, so we don't need to make the case to Kubernetes as a whole.

**Comment by otterley** [comment]
This feature is now available via the new [AWS Load Balancer Controller](https://github.com/kubernetes-sigs/aws-load-balancer-controller) version 2.0 and later for IP mode targets.

To enable it, set the following annotation on your service:

```
service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
```

**Comment by austinorth** [comment]
Any word on support for using Proxy Protocol _without_ IP Mode?

**Comment by kishorj** [comment]
@austinorth I've been split between whether to add support for NLB instance mode in the [AWS Load Balancer Controller](https://github.com/kubernetes-sigs/aws-load-balancer-controller) instead or add this feature in the in-tree service controller. With the external controller, we can iterate faster.

**Comment by TBBle** [comment]
Per https://github.com/kubernetes/cloud-provider-aws/pull/128#issuecomment-705178404 and https://github.com/aws/containers-roadmap/issues/981#issuecomment-665934998 the plan appears to be to move NLB Instance support into the [AWS Load Balancer Controller](https://github.com/kubernetes-sigs/aws-load-balancer-controller) anyway, if that helps with the decision?

It seems like [AWS Cloud Provider v2](https://github.com/kubernetes/cloud-provider-aws/issues/125) will only support CLB, and delegate all NLB to AWS Load Balancer Controller, so implementing NLB instance support in the AWS Load Balancer Controller would help accelerate that migration, I guess, although I'm not clear how the cut-over will work. Will we need to support a situation where AWS Cloud Provider v1 or in-tree AWS Cloud Provider are active and trying to manage NLB instance-mode at the same time as AWS Load Balancer Controller with NLB instance-mode support is running.

**Comment by austinorth** [comment]
@kishorj Thanks for the reply! As a user, I would be cool with using either of those options, although the in-tree would make it a little easier for me personally to roll out. As @TBBle mentioned tho, I think if this functionality were to be set up in the [AWS Load Balancer Controller](https://github.com/kubernetes-sigs/aws-load-balancer-controller), the cut-over may be difficult to engineer, and I would love some clear documentation on how to migrate if you decide to go that route.
That all said, I appreciate your work on this so very much, and looking forward to using whatever you end up making!

**Comment by mihailgmihaylov** [comment]
As far as I can see from the information in this issue and the other issues linked here, the roadmap is to move the NLB functionality away from the in-tree cloud integration and embed it in the aws-load-balancer-controller. That is perfect for us as we are already using this for ALBs. However, I see that it only supports NLB in IP mode and not in instance mode.

Is the plan to migrate the in-tree NLB instance mode to aws-load-balancer-controller as well with the Proxy Protocol setting?
I am asking because we cannot use NLB in IP mode due to the fact that we cannot use the [amazon-vpc-cni-k8s](https://github.com/aws/amazon-vpc-cni-k8s) CNI plugin. So we have no other option to rely on the in-tree NLB right now.

**Comment by kishorj** [comment]
NLB instance mode will be supported by the [AWS Load Balancer Controller](https://github.com/kubernetes-sigs/aws-load-balancer-controller) in the upcoming 2.2.0 release. The support for PROXY protocol will be available with the instance mode.

The legacy cloud provider is deprecated and new releases will be limited to critical bug fixes only.

The [ AWS Cloud Provider for Kubernetes ](https://github.com/kubernetes/cloud-provider-aws/) will provide new features in future. Please direct any features/concerns to the AWS Cloud provider project. 

/close
