### ISSUE TITLE
Multiple CRD APIVersions and migration

### ISSUE THREAD

**Issue by tatsuhiro-t** [kubernetes/kubernetes#57316]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:

I defined a CRD whose APIVersion is v1alpha1.  Now things went well, I want to change APIVersion to v1.  But CRD.Spec.Version is immutable, and I could not change it.  CRD requires its name must match plural, and group, I could not add another CRD with the different version.
Backup custom objects, and delete current CRD, and create new CRD, then importing custom objects will work, but I want easier migration.

**What you expected to happen**:

CRD can have multiple versions.
A way to migrate between versions (just like we can get Deployment from both apps/v1beta1 and apps/v1beta2) is highly desirable.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by sttts** [comment]
We cannot support multiple versions of a CRD because there is no mechanism that can dynamically convert between them. There is a discussion going on in sig-apimachinery whether multiple versions are in scope or not, and if yes, how to add conversions for CRDs.

For the use-case here though the question is whether we can at least allow to change the (one and only) version of CRD without loosing any data. Right now this is not possible. Technically, this could certainly be done. The big question is whether we want to offer that.

Semantically, this would mean that all existing CRs are "suddenly" returned with the updated version string, but the old, unchanged schema. In other words, the consumers of the CR have to make sure that all CRs are migrated (trivial if the migration is a Noop).

/cc @nikhita @caesarxuchao @deads2k @enisoc

**Comment by nikhita** [comment]
Just for the record, relevant sig-api-machinery mailing list topics:

- https://groups.google.com/forum/#!topic/kubernetes-sig-api-machinery/07JKqCzQKsc
- https://groups.google.com/forum/#!topic/kubernetes-sig-api-machinery/rX99p_YWObA

**Comment by nikhita** [comment]
CRD versioning feature issue: https://github.com/kubernetes/features/issues/544.

**Comment by nikhita** [comment]
WIP is in https://github.com/kubernetes/kubernetes/pull/60113.

**Comment by nikhita** [comment]
xref https://github.com/kubernetes/kubernetes/pull/63518 - CRD Versioning with no-op Conversion

**Comment by liggitt** [comment]
addressed by no-op conversion, released in 1.11

/close
