### ISSUE TITLE
test-cmd run_plugins_tests flaky

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/kubernetes#57342]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug

**What happened**:  `test-cmd run_plugins_tests` in the `pull-kubernetes-unit` job is the flakiest test in the unit job tied with [`TestCascadingDeletion`](https://github.com/kubernetes/kubernetes/issues/56121) which makes for the overall flakiest test in the repo. 

**What you expected to happen**: Tests shouldn't flake this much.

**How to reproduce it (as minimally and precisely as possible)**: Open a PR with no changes, run `/test pull-kubernetes-unit` a few times and see that it still both passes and fails arbitrarily on these tests.

**Anything else we need to know?**: This hurts merge rates.

**Environment**:
- kubernetes's CI/CD

**Comment by BenTheElder** [comment]
Per the nearest `OWNERS` to the kubectl plugins this appears to be testing:
@kubernetes/sig-cli-test-failures 
/kind bug
Last person to touch `run_plugins_tests`:
/cc @mengqiy 
Flakiness metrics:
- http://storage.googleapis.com/k8s-metrics/flakes-latest.json
- http://velodrome.k8s.io/dashboard/db/bigquery-metrics?orgId=1

**Comment by mengqiy** [comment]
@BenTheElder Can you point to me the build log of a failing test?
I'm not the last one touched this test case, but @shiywang is: https://github.com/kubernetes/kubernetes/blame/master/hack/make-rules/test-cmd-util.sh#L4370

**Comment by BenTheElder** [comment]
Here's two examples: 
- https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/56317/pull-kubernetes-unit/71527/
- https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/batch/pull-kubernetes-unit/71492/

https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-unit

**Comment by shiywang** [comment]
@BenTheElder will take a look

**Comment by shiywang** [comment]
Those plugin failing tests randomly failed in some string sanity check like [here](https://github.com/kubernetes/kubernetes/blob/3ef674188d3fcd4140bcd98e532b8a7f6875ccce/hack/make-rules/test-cmd-util.sh#L4432), [here](https://github.com/kubernetes/kubernetes/blob/3ef674188d3fcd4140bcd98e532b8a7f6875ccce/hack/make-rules/test-cmd-util.sh#L4491) and [there](https://github.com/kubernetes/kubernetes/blob/3ef674188d3fcd4140bcd98e532b8a7f6875ccce/hack/make-rules/test-cmd-util.sh#L4469) which is weird because the output messages actually do exist (see log @BenTheElder pasted above), but seems [grep](https://github.com/kubernetes/kubernetes/blob/1010916c1adc3b74f3ffaf5a2a5fae7d0bc2ef77/hack/lib/test.sh#L268) here didn't catch them. I don't think this is a problem of kubectl, more like our test infra stdout printing logs problem.
@kubernetes/sig-testing-bugs @kubernetes/test-infra-maintainers  have you met this kind of problem before?

**Comment by mengqiy** [comment]
@BenTheElder What's the failing rate?

**Comment by fejta** [comment]
This flakes 122 PRs a week: http://velodrome.k8s.io/dashboard/db/bigquery-metrics?orgId=1

**Comment by shiywang** [comment]
I think @fejta is talking about the whole unit tests, `run_plugins_tests` flakes 36 PRs a week. btw, @mengqiy do you have any ideas on this ? it seems only failed in kubernetes CI/CD, I mean is there any possiblities some external environment problem cause this flake ?

**Comment by BenTheElder** [comment]
CI/CD only runs this in a kubernetes pod and should not be causing this flake, tons of other tests run in the same environment even just in `pull-kubernetes-unit`. We're not doing anything to the stdout of this script, the code for how output is handled is all in kubernetes/kubernetes... (shell2junit).

36 PRs in a week both passing and failing this test strongly suggests that it is holding up *at least* 36 PRs/week (not including only failing PRs...)

My guess is whatever the test script is using to grep isn't reliable, that smells like flake potential (incompletely regex?)

**Comment by liggitt** [comment]
Fixed in https://github.com/kubernetes/kubernetes/pull/57805

/close
