### ISSUE TITLE
CRI: Revisit Image Filesystem Storage Identifier

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes/kubernetes#57356]
Currently, we use disk UUID as the image filesystem storage identifier. https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/apis/cri/v1alpha1/runtime/api.proto#L1057

However, when implementing this in cri-containerd, we found it hard to implement.
1) Today we are relying on `/dev/disk/by-uuid` to implement it (both cri-containerd and cadvisor). However `/dev/disk/by-uuid` is specific to [`udev`](https://en.wikipedia.org/wiki/Udev) device manager. Another device manager, such as [`mdev`](https://wiki.gentoo.org/wiki/Mdev) may not have it. We've got several issues for this in `cri-containerd` https://github.com/kubernetes-incubator/cri-containerd/issues/509, https://github.com/kubernetes-incubator/cri-containerd/issues/399 and https://github.com/kubernetes-incubator/cri-containerd/pull/292.
2) Another option is to use `libblkid`. However, because there isn't go implementation, we need to:
  a) Either use the C library, which introduces a hard dependency on cgo and `libblkid-dev`.
  b) Or shell out [`blkid`](https://linux.die.net/man/8/blkid) which is part of `util-linux-ng` package. This is not impossible, but needs to introduce one extra dependency in both the container runtime and cadvisor.

For linux other than UUID, there are other options. The pros and cons:
* UUID: Cons - Relatively hard to get and use in golang; Pros - Unique. For remote container runtime, kubelet won't be confused.
* Device Number: Cons - For remote container runtime, kubelet may assume it's local device and can probably actually find a corresponding device locally; Pros - Easy to get. Actually `cri-containerd` [converts device number to UUID](https://github.com/kubernetes-incubator/cri-containerd/blob/master/pkg/server/service.go#L250), and cadvisor [converts UUID to device name](https://github.com/google/cadvisor/blob/7d11f4243f6e11700c0d644a468dfd48ba0ae588/fs/fs.go#L172) today. With device number, the logic will be simpler.
* Device Name: Similar with device number.

I'm not sure whether we should consider remote runtime today. Since if the runtime is remote, all the resource management and cgroup stuff won't work anyway today.

Other than the problems above, there are some other problems:
1) How to handle ZFS?
  a) Should container runtime return device UUID/name/number? If yes, container runtime need to understand ZFS, and get device name/number from ZFS pool name.
  b) Or should container runtime return ZFS pool name and let kubelet pass that to cadvisor?
The former seems better. Ref https://github.com/kubernetes-incubator/cri-containerd/issues/325.
2) What about windows? It seems that windows also have the notion of [device number](https://technet.microsoft.com/en-us/library/cc957341.aspx), I'm not sure whether it's similar thing. @feiskyer 
3) How about VM-based container runtime?

@yujuhong @mikebrow @abhi @ijc @mrunalp @feiskyer 
/cc @kubernetes/sig-node-api-reviews

**Comment by fntlnz** [comment]
Also @runcom might be interested

**Comment by resouer** [comment]
For `KataContainers` do we support `ImageFsInfo` API now? @sameo, seems not? While the notion of  `image filesystem storage identifier` also is different a little bit in this case.

**Comment by gnawux** [comment]
@resouer it is part of the metrics collection APIs, and I think the virtualized container runtimes are not well supported the existing metrics right now.

**Comment by sameo** [comment]
@resouer we do not support it for now.

**Comment by Random-Liu** [comment]
@resouer @gnawux @resouer For linux containers, kubelet need to know:
* Which disk partitions are container images on.
* What is the disk/inodes usage and capacity of those disk partitions.
* How much disk/inodes are used by actual container images.

Kubelet needs the information to do container eviction and image garbage collection. Does this make sense to VM-based containers? How are images stored for VM-based containers?

**Comment by gnawux** [comment]
@Random-Liu It depends on the different cases. Image/rootfs is managed on the host for vm-based containers as well, which makes it reasonable to get these informations from CRI runtime. While in some special cases, such as using a block device (or a remote device/fs) as the rootfs of a container, the rootfs may not be a filesystem mounted on the host.

**Comment by Random-Liu** [comment]
@gnawux Thanks for your explanation. I think kubelet will still need to manage the on-host image/rootfs. But for the remote device/fs, kubelet can't do much.

**Comment by feiskyer** [comment]
cc @PatrickLang @taylorb-microsoft for windows containers

**Comment by taylorb-microsoft** [comment]
cc @jstarks, @jhowardmsft, @darrenstahlmsft

I think for Windows hosts (which support both Windows and Linux containers w/Windows supporting both process and VM isolation and Linux only as VM isolation) we are just taking in a host path, which typically could be a drive letter (f:\; a mount point c:\mydrive; or a volume path \\.\volume\{GUID}).  John(s) Darren is that correct?

**Comment by PatrickLang** [comment]
The windows management model can give you both UUID for LUNs, and also the UUID for partitions. As Taylor pointed out, you can use the partition's UUID with the format `\\?\Volume{guid}`

```
PS C:\WINDOWS\system32> Get-PhysicalDisk | ft UniqueId, DeviceId, FriendlyName

UniqueId                               DeviceId FriendlyName
--------                               -------- ------------
{43b781f2-be3f-c41e-8499-1bcb2e862081} 3        WD My Passport 0748
{c66da493-b4fe-4192-2476-3a309fb655ed} 0        MTFDDAK256MBF-1AN15ABHA
{e741c68c-6e8b-4e94-1ee3-dcc07f429fff} 1        CT480BX300SSD1
{fe374ac2-86e4-4383-4912-76b479bd238b} 2        WDC WD10EZEX-60WN4A0


PS C:\WINDOWS\system32> Get-Disk -Number 1 | Get-Partition | ft PartitionNumber, AccessPaths

PartitionNumber AccessPaths
--------------- -----------
              1
              2 {D:\, \\?\Volume{7b861875-4e88-4d63-9552-58df8d1194c9}\}
```

**Comment by Random-Liu** [comment]
I see issue related to this again.

In the ubuntu image used in GKE, I see cadvisor report this error for cri-containerd:
```
E0131 11:01:34.250057 6468 cri_stats_provider.go:236] Failed to get the info of the filesystem with id "03dca1c3-208e-4cf1-aeb3-e3f4be780531": cannot find device "/dev/sda1" in partitions.
```

The reason is that cadvisor does see `/dev/sda1` in UUID map at `/dev/disk/by-uuid`, but doesn't see `dev/sda1` in mount table `/proc/self/mountinfo`:
```
I0131 11:01:33.856427 6468 fs.go:140] Filesystem UUIDs: map[03dca1c3-208e-4cf1-aeb3-e3f4be780531:/dev/sda1]
I0131 11:01:33.857247 6468 fs.go:141] Filesystem partitions: map[tmpfs:{mountpoint:/dev/shm major:0 minor:19 fsType:tmpfs blockSize:0} /dev/root:{mountpoint:/var/lib/docker/aufs major:8 minor:1 fsType:ext4 blockSize:0}]
```

There are several possible solutions:
1) Let cadvisor get device number from UUID, and use device number to find corresponding partition.
2) Change CRI to return device number directly.

Since we've encountered several issues about disk UUID (see https://github.com/kubernetes/kubernetes/issues/57356#issue-283040072).

I propose we change CRI to return device number instead.

**Comment by PatrickLang** [comment]
I don't think device numbers are a good idea, especially when it comes to Windows. I think the right thing here is to allow an OS/distro specific implementation in that string. On Windows, I'd propose using the volume path because it doesn't change if a drive letter changes.

Would it be possible to have an ordered priority of what's used?

1. zfs / NTFS identifier that uniquely identifies that volume
2. if not present, use disk uuid (Linux) / windows UniqueId
3. else use disk number

```powershell
PS C:\WINDOWS\system32> Get-PhysicalDisk | ft DeviceId, SerialNumber, UniqueId, Model

DeviceId SerialNumber    UniqueId                               Model
-------- ------------    --------                               -----
0        1707164CA4D1    {c66da493-b4fe-4192-2476-3a309fb655ed} MTFDDAK256MBF-1AN15ABHA
1        1732E100FC02    {e741c68c-6e8b-4e94-1ee3-dcc07f429fff} CT480BX300SSD1
2        WD-WCC6Y5ZPE752 {fe374ac2-86e4-4383-4912-76b479bd238b} WDC WD10EZEX-60WN4A0


PS C:\WINDOWS\system32> get-disk | ft Number, UniqueId, Model

Number UniqueId                                                             Model
------ --------                                                             -----
     1 SCSI\DISK&VEN_&PROD_CT480BX300SSD1\4&23861807&0&010000:plang-h1      CT480BX300SSD1
     0 SCSI\DISK&VEN_&PROD_MTFDDAK256MBF-1A\4&23861807&0&000000:plang-h1    MTFDDAK256MBF-1AN15ABHA
     2 SCSI\DISK&VEN_WDC&PROD_WD10EZEX-60WN4A0\4&23861807&0&050000:plang-h1 WDC WD10EZEX-60WN4A0


PS C:\WINDOWS\system32> get-volume | ft Driveletter, Path

Driveletter Path
----------- ----
            \\?\Volume{0a612440-fda8-47f1-a567-57f76a169772}\
            \\?\Volume{64dfa4a6-a233-4333-9417-ddaa12e88248}\
D           \\?\Volume{7b861875-4e88-4d63-9552-58df8d1194c9}\
C           \\?\Volume{d47d3839-6dd0-446b-bcfb-dfaba3e5a051}\
```

**Comment by Random-Liu** [comment]
> I don't think device numbers are a good idea, especially when it comes to Windows. I think the right thing here is to allow an OS/distro specific implementation in that string. On Windows, I'd propose using the volume path because it doesn't change if a drive letter changes.

We can keep the string, but just assume it is device number for linux.
We can also return multiple fields. :)

**Comment by filbranden** [comment]
So I think in Linux/Unix using {major, minor} pair should be better than using the UUID, since essentially we end up mapping a UUID to a {major, minor}, so we're just removing a layer of indirection there by using {major, minor} directly.

I thought of cases where {major, minor} would present problems. One is that a device would be removed, a new device would be added and then it would end up getting the same {major, minor} of the original device. UUID would work better there, since the new device would have a different UUID so it would fail with an error (unable to find device with that UUID) rather than access the wrong device... But the way it works right now (caching the mapping UUID -> device) it wouldn't *actually* behave better with UUID, and this case of removing devices is probably unusual enough that we might be OK with that...

Another thing I thought of was whether namespaces might affect device {major, minor} numbers, but it doesn't seem so. I only found one proposal for namespaces that would affect {major, minor} numbers and they didn't really go anywhere, so probably no concerns with view of devices inside and outside containers getting {major, minor} pairs wrong...

Regarding the concern about remote runtime, I think either UUID and {major, minor} would have the same problems... Confusing local devices with remote devices is a problem in either case... Again, UUID failure might be more *obvious* since the UUID is unique and wouldn't be found on the other system, but ultimately if the {major, minor} is handled properly this shouldn't be a problem.

@Random-Liu and I also briefly discussed the case of ZFS (and Btrfs) where a single {major, minor} doesn't identify a filesystem but identifies a "pool" and many volumes/subvolumes/filesystems exist within it. So to handle that, in the future we might want to extend "message StorageIdentifier" to carry both the {major, minor} and an optional identifier of the volume/subvolume/filesystem. We might be able to do this in a generic way, as a string, and simply append it to the mountpoint in a way that we can find it in the mountinfo of the target... I think that's a separate problem from this one though, so I'd treat it as an extension.

Windows handling is probably a separate issue, since I don't expect {major, minor} will make sense there... So I'm thinking we'll need special code to handle Windows anyways. Perhaps in Windows we could ignore the {major, minor} fields altogether and just use the "subvolume" field (we'll introduce for ZFS/Btrfs) and encode the unique volume path for Windows there?

I can probably help with some experiments on Btrfs (and I don't think I have easy access to ZFS... but I'm expecting it will behave similarly) to investigate how to extend the scheme to support filesystems with subvolumes.

Cheers!
Filipe

**Comment by andyzhangx** [comment]
@PatrickLang @taylorb-microsoft In current Windows implementation, it uses LUN --> Windows disk number([code](https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/azure_dd/azure_common_windows.go#L42)) --> Windows driver letter ([code](https://github.com/kubernetes/kubernetes/blob/master/pkg/util/mount/mount_windows.go#L313))) to identify the disk in Windows.

**Comment by AkihiroSuda** [comment]
Has anyone looked into whether `f_fsid` can be used for this purpose?
http://man7.org/linux/man-pages/man2/statfs.2.html



```
 The general idea is that f_fsid contains some random stuff such that
       the pair (f_fsid,ino) uniquely determines a file.  Some operating
       systems use (a variation on) the device number, or the device number
       combined with the filesystem type.  Several operating systems
       restrict giving out the f_fsid field to the superuser only (and zero
       it for unprivileged users), because this field is used in the
       filehandle of the filesystem when NFS-exported, and giving it out is
       a security concern.
```

btrfs implementation: https://github.com/torvalds/linux/blob/e237f98a9c134c3d600353f21e07db915516875b/fs/btrfs/super.c#L2168-L2175
zfs implementation: https://github.com/zfsonlinux/zfs/blob/1b66810bad0a893031c6d49613aa83dc359bf034/module/zfs/zfs_vfsops.c#L1302-L1303

My only concern is that it might not work for (future) rootless containers

**Comment by Random-Liu** [comment]
@AkihiroSuda Thanks a lot! This is very useful. Given so, I don't think `f_fsid` will be useful, because it doesn't seem that we can use the id to retrieve the information. Given how `statvfs` is defined, I think we should just let container runtime return a path to the image filesystem.

And kubelet can use `statvfs` to get file system information.

**Comment by Random-Liu** [comment]
It turns out that cadvisor is using `statfs` today (see [here](https://github.com/google/cadvisor/blob/master/fs/fs.go#L621)), so we can just rely on it.

The only thing we need to change is:
1) Let container runtime return the path of image filesystem.
2) Kubelet pass it to cadvisor and get filesystem stats.
3) Kubelet pass it to cadvisor to get device name, and compare with rootfs to identify whether they are on the same filesystem.

A path should also work for Windows, and they can potentially use function like [this](https://msdn.microsoft.com/en-us/library/windows/desktop/aa364937(v=vs.85).aspx) to get stats.

Note that only mountpoint is not sufficient for device mapper. IIUC, device mapper still needs pool name to work.
In the future, we can possibly let CRI container runtime return pool name if the image filesystem is on device mapper, but we are not going to address that in the first version. @mrunalp @runcom Are you OK with that?

**Comment by shuaichang** [comment]
Hi @Random-Liu, we are facing something similiar regarding `Note that only mountpoint is not sufficient for device mapper. IIUC, device mapper still needs pool name to work.`.

It seems to me with device mapper snapshotter, containerd-cri ImageFsInfo will only return filesystem info for `c.imageFSPath` which in our case is `/var/lib/containerd/io.containerd.snapshotter.v1.devmapper/`. This is the host filesystem instead of the thin pool utilization percentage, which is pretty much useless for Kubelet GarbageCollect.

Do containerd-cri currently support the accurate accounting of devmapper snapshotter or it's not yet available? Does it mean to use devmapper, we have to do thin-pool GC by ourselves, e.g. having a GC daemon on a node?
