### ISSUE TITLE
The node was low on resource: nodefs

### ISSUE THREAD

**Issue by KeithTt** [kubernetes/kubernetes#57442]
kube version: 1.8.5
docker version: 17.06.2-ce

```
The node was low on resource: nodefs
The node was low on resource: [DiskPressure].
```
 It seems a BUG about monitoring?

![image](https://user-images.githubusercontent.com/15189954/34199622-52aaef7c-e5a9-11e7-8c50-23fb09144550.png)

**Comment by KeithTt** [comment]
@dims This issue is from ui?

**Comment by KeithTt** [comment]
@dashpole

**Comment by dashpole** [comment]
Looks like your dashboard was evicted due to low disk space.  Do you know if your node actually ran out of disk?
IIRC, the dashboard is run as a deployment, so it should have come back up after being evicted.  Did that not happen?

**Comment by KeithTt** [comment]
@dashpole Yes, you are right, the pod restarts all the time, and on different node, why this happened?

**Comment by dashpole** [comment]
When a node runs out of disk space, it will evict pods in order to free up space.  The scheduler attempts to place them on a different node to reduce the chance that they are evicted again.  I think in your case this is working as intended.  The bug you previously referenced was about DiskPressure triggering when the disk was only ~50% full, and should be fixed in the version you are running.  I would recommend either using larger disks, or trying to reduce your container image sizes.  That is usually the culprit when people are running out of disk very frequently.

**Comment by KeithTt** [comment]
@dashpole In fact, I only use less than 20% of the disk, apparently there should not trigger this error...

**Comment by dashpole** [comment]
Does your disk have multiple partitions?  If so, the kubelet only monitors the partition that includes the /var/lib/kubelet (or wherever you placed the kubelet).
Is that the disk usage now, or when the eviction took place?  Is that node still showing `DiskPressure` when you do `kubectl get nodes`?

**Comment by KeithTt** [comment]
I do have two partitions, but the partition where kubelet is placed is also less than 50%...Maybe there is something else have something to do with this...

I find a problem in my HA cluster, a cert issue, and after I resolve the cert issue this issue disappeared. It is very strange...

**Comment by KeithTt** [comment]
Close it.
