### ISSUE TITLE
API Server not listening on cluster service IP when there's no default gateway

### ISSUE THREAD

**Issue by dnoland1** [kubernetes/kubernetes#57534]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
I can't get Kubernetes cluster (v1.8.2) running in an air gapped environment that does not have a default gateway defined in routing table within the OS. When the k8s kubelet starts, I see the error: 
```
Dec 18 19:22:51 server-001 kubelet[23357]: W1218 19:22:51.967098   23357 kubelet_node_status.go:973] Failed to set some node status fields: can't get ip address of node server-001. error: No default routes.
```
in /var/log/syslog and the API server is not listening on the service cluster network, which causes failures in other pods. If I create a dummy default route, all is good - k8s comes up clean, all pods are happy.

Route table:
```
root@server-001:~# route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
10.0.0.0        10.69.255.79    255.0.0.0       UG    0      0        0 p0
10.68.0.0       0.0.0.0         255.252.0.0     U     0      0        0 p0
172.17.0.0      0.0.0.0         255.255.0.0     U     0      0        0 docker0
```

**What you expected to happen**:
Kubernetes to work properly regardless of whether the default gateway is set or not.

**How to reproduce it (as minimally and precisely as possible)**:
Try to run Kubernetes on server that does not have a default gateway route defined. Then try to run a curl on the API extension server and will get a connection refused (curl -k https://172.16.0.1/)

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.8.2
- Cloud provider or hardware configuration: bare metal, Intel(R) Xeon(R) CPU E5-2683 v4 @ 2.10GHz, 64 cores, 512GB RAM
- OS (e.g. from /etc/os-release): Ubuntu 16.04.3 LTS
- Kernel (e.g. `uname -a`): Linux server-001 4.4.0-38-generic #57-Ubuntu SMP Tue Sep 6 15:42:33 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: Installed by custom Ansible script
- Others: Calico v2.6.2

**Comment by dims** [comment]
@dnoland1 did you try the `node-ip` parameter in kubelet?  will that work for you?

**Comment by dnoland1** [comment]
Yes, that parameter is already being set. Here are all the flags I'm setting:
```
/usr/bin/kubelet
  --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf
  --kubeconfig=/etc/kubernetes/kubelet.conf
  --pod-manifest-path=/etc/kubernetes/manifests
  --allow-privileged=true
  --network-plugin=cni
  --cni-conf-dir=/etc/cni/net.d
  --cni-bin-dir=/opt/cni/bin
  --node-ip=10.69.11.83
  --cluster-dns=172.16.0.10
  --cluster-domain=cluster.local
  --authorization-mode=Webhook
  --client-ca-file=/etc/kubernetes/pki/ca.crt
  --cadvisor-port=0
  --rotate-certificates=true
  --cert-dir=/var/lib/kubelet/pki
  --pod-infra-container-image=gcr.io/google_containers/pause-amd64:3.0
```

**Comment by luckyfengyong** [comment]
@kennethredler It is just my opinion based on the customer environments we are working with, and the problems we met and resolved. 

If system cannot be configured with a default gateway, explicit routes probably should be configured for service ip range. Otherwise, user will meet the issue I mentioned above. 

If there is any solution to make k8s working without configuring default gateway or explicit routes, I am more than happy to adopt.

**Comment by kennethredler** [comment]
Thanks for clarifying, @luckyfengyong . From my perspective/experience leveraging explicit service cidr routes is a viable solution. I hope it remains a viable solution in the absence of default gateway.

**Comment by luckyfengyong** [comment]
@kennethredler Yes.

**Comment by NicolasT** [comment]
Just ran into this as well, an environment where nodes are only connected to specific networks without any kind of `default` route. Took me quite a while to debug what was going on, despite the fact I ran into this exact same issue a couple of months ago.

Anyway, the work-around is quite simple: create *a* (*any*) valid route for the *Service* network on the host(s) such that requests to them get routed (and then intercepted by `kube-proxy` `iptables` rules) instead of `ENETUNREACH`, so e.g.

```
$ modprobe dummy
$ ip l set dummy0 up
$ ip r add 10.96.0.0/12 dev dummy0
```

I'm wondering, given this network should never be 'really' routable on the host (at least when using `kube-proxy`), would it make sense for `kube-proxy` to always create such interface and set up the appropriate route? (I tried using a `blackhole` route not to need the `dummy0` interface, but that doesn't work).

**Comment by aojea** [comment]
@dnoland1 can you confirm that the problem is trying to reach Services IPs?
If that is the case, this is working as expected, if you need to reach services IP, you need to tell the system how to go to the Services IP range, it can a be a default route or a route to the service subnet like in https://github.com/kubernetes/kubernetes/issues/57534#issuecomment-527653412

**Comment by arianvp** [comment]
To me it sounds like this issue could be resolved by adding a preflight check to kubeadm that makes sure that 

```
ip route get {{ service_cidr }}
```

returns a route; and if it fails instructs the user to either set up a default gateway or a dummy routte.

**Comment by arianvp** [comment]
This is still an issue. But the solution i suggested seems valid? Should I cross-post it to the kubeadm issue tracker?

**Comment by aojea** [comment]
> If that is the case, this is working as expected, if you need to reach services IP, you need to tell the system how to go to the Services IP range, it can a be a default route or a route to the service subnet like in [#57534 (comment)](https://github.com/kubernetes/kubernetes/issues/57534#issuecomment-527653412)

is not a kubernetes issue, is networking configuration issue, the installers should configure the route to the service network ... 

> This is still an issue. But the solution i suggested seems valid? Should I cross-post it to the kubeadm issue tracker?

that is a kubeadm decision , cc @neolit123

**Comment by neolit123** [comment]
you can log an issue in k/kubeadm.
`ip` is a mandatory binary on Linux, so a preflight check can be run with it.
