### ISSUE TITLE
Volume operation metrics inconsistent with cloud provider metrics

### ISSUE THREAD

**Issue by verult** [kubernetes/kubernetes#57565]
/kind bug

The cloud provider latency metric includes latency of requests with errors:
https://github.com/kubernetes/kubernetes/blob/13c80a99a36efcdc7e76102b6154e15edc17b69d/pkg/cloudprovider/providers/gce/metrics.go#L59-L67

while the volume operation latency metric does not:
https://github.com/kubernetes/kubernetes/blob/13c80a99a36efcdc7e76102b6154e15edc17b69d/pkg/volume/util/metrics.go#L52-L64

This is confusing when comparing the two latencies for troubleshooting purposes (e.g. the cloud provider metric with request=disk_attach vs. the volume operation metric with request=volume_attach). IMO They should have the same conventions in terms of whether or not to include errors.

/sig storage
/cc @gnufied @wongma7

**Comment by gnufied** [comment]
hmm, this appears to be GCE specific thing. IMO - we should not measure latency of calls that errored out, the reason I can think of is - when an operation errors out, it may error out prematurely. For example, if detach api call if on average takes 10s then if there is error (because of invalid state of something), that api call may return sooner. 

It matters even more for volume operation latencies because including errors in the metrics will skew the average or mean that user may be interested in.  For example - if volume attach operation takes 20s then with if something goes wrong then it can be over in 2s and naturally this data point will not accurately reflect time it takes for volume attach operation to succeed.

**Comment by gnufied** [comment]
cc @bowei
