### ISSUE TITLE
Can not use specified storage account in other resource group for azure disk&file dynamic provisioning

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes/kubernetes#57605]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug
> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

**What happened**:
According to below code, azure file & disk dynamic provisioning only supports storage account in the same resource group with k8s cluster:
https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/azure/azure_storageaccount.go#L66

There are two scenarios:
1) If user specify a storage account, I think we should not restrict the resource group
2) if user does not specify a storage account, then only storage accounts in the same resource group should be searched.

**Update:**
From the SDK level, resource group name must be provided to get storage account, so a new parmater `resourceGroup` for azure disk & file storage class must be provided.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.10.0
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/assign
/sig azure

**Comment by khenidak** [comment]
Having resources spanning two or more resource groups is a bad idea. And is discouraged. Access Management / Lifecycle are all tied to group's scope. Eventually we will not even to _get_ keys to create page blobs because storage account access will be tied to MSI/Node identity.

We really have to drive this from user requirements and specific use cases. Do we have a user requirements/use case for this?

**Comment by andyzhangx** [comment]
@khenidak You are right, there is no strong customer requrement for this issue, just a thought in my mind. Just closed this issue.
