### ISSUE TITLE
Prometheus metrics for PVC showing stale volume data

### ISSUE THREAD

**Issue by gamer22026** [kubernetes/kubernetes#57686]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug
/sig node

**What happened**:
Prometheus metrics endpoint for PVC volume stats is showing stale data for volumes no longer mounted to node
**What you expected to happen**:
Prometheus metrics endpoint for PVC volume stats only shows metrics for currently mounted volumes.

**How to reproduce it (as minimally and precisely as possible)**: Migrate a pod with a PVC/volume mount to a different node. Observe that the PVC volume metrics on the previous node still report the last known values.

**Anything else we need to know?**:
The /stats/summary endpoint correctly reports only the currently mounted PVCs. It's only the /metrics endpoint that reports stale volume metrics

**Environment**:
- Kubernetes version (use `kubectl version`): 1.8.3
- Cloud provider or hardware configuration: AWS
- OS (e.g. from /etc/os-release): Debian GNU/Linux 8 (jessie)
- Kernel (e.g. `uname -a`): 4.9.0-0.bpo.2-amd64 #1 SMP Debian 4.9.18-1~bpo8+1 (2017-04-10) x86_64
- Install tools:
- Others:

**Comment by gnufied** [comment]
I think that is inherent limitation (or feature) of prometheus client library or many other metrics libraries. Once you register and emit a metric - it is always emitted until you restart the component.

**Comment by gamer22026** [comment]
If that is indeed the case the metrics for PVC are worthless and should be removed as there is no way to tell which PVC metrics are current and which ones are emitting metrics for mounts that no longer exist.

**Comment by gnufied** [comment]
Hmm, I might be not entirely correct about prometheus not offering a way of implementing "ephemeral" metrics like this. @brancz will implementing a custom collector interface will get around the problem of - once a metric is registered and emitted, it is always emitted until component is restarted?

**Comment by gnufied** [comment]
assigning this to myself for investigation and finding possible way of fixing this.

**Comment by brancz** [comment]
In Prometheus, a time-series goes stale as soon as it disappears from a target or the target itself disappears. So yes, with a custom collector this is perfectly possible, as you can generate metrics on a metrics request from Prometheus :slightly_smiling_face: . Aside from that, the Prometheus client lib for go also allows removing metrics at runtime, only caveat is you need the previously registered metric object.

**Comment by cbandy** [comment]
> the Prometheus client lib for go also allows removing metrics at runtime

That is,
- https://godoc.org/github.com/prometheus/client_golang/prometheus#Registry.Unregister or
- https://godoc.org/github.com/prometheus/client_golang/prometheus#Unregister

**Comment by ekimekim** [comment]
Hi. I'm also being affected by this bug. I thought I'd share a really hacky workaround I plan on using until it is fixed.

The idea is, since the stale values will not change, but the values we are interested in will change regularly (in particular my use-case is interested in the `kubelet_volume_stats_available_bytes` metric), we can determine the "true" value by looking at which value changed most recently.

However, this turned out to be rather hard to do in PromQL. I'd welcome any suggestions for simplifying the following:

1. Create a recording rule that records as points the times at which changes occurred: `change_times = timestamp(available_bytes) and changes(available_bytes[5m]) > 0`

2. Work out the timestamp of the most recent change within a certain time window, here 48h: `latest_change_time = max_over_time(change_times[48h])`

3. Filter the original series vector by only keeping the series which match the labels of the `latest_change_time` series which has the largest value out of your group of series at that point: `true_available_bytes_parts = available_bytes and latest_change_time == on(persistentvolumeclaim) max(latest_change_time) by (persistentvolumeclaim)`

4. Combine the filtered series with `max` so that you end up with one whole series that smoothly uses data from one kubelet then another depending on which one contained the most recent change to the actual data: `true_available_bytes = max(true_available_bytes_parts) by (persistentvolumeclaim)`

Also, while we're discussing how to fix the actual bug: One idea that would work without the need to explicitly `Unregister` or mess with the prom library internals would be to have a gauge `is_mounted{persistentvolumeclaim}`. If it were `1` when the data was good and `0` when the data was stale, my entire hack above could be simplified down to:
`true_available_bytes = max(available_bytes and is_mounted > 0) by (persistentvolumeclaim)`.
It's not an ideal solution but it may be better than none if a proper fix is too difficult.

**Comment by cofyc** [comment]
@gnufied @ekimekim @gamer22026 
I submitted a PR to fix this: https://github.com/kubernetes/kubernetes/pull/59170.

**Comment by cofyc** [comment]
@ekimekim @gamer22026 @brancz @gnufied @cbandy 
FYI. 
I also wrote a simple [kubelet-exporter](https://github.com/cofyc/kubelet-exporter) to translate information of kubelet `stats/summary` endpoint to work around this issue in our production clusters temporarily. External exporters can be deployed & updated independently.

**Comment by gamer22026** [comment]
Thx for the kubelet-exporter.

**Comment by jsafrane** [comment]
I tested it with OpenShift (Kubernetes 1.9.1) and I can confirm that usage stats are updated when a PVC "leaves" a node (i.e. a pod that used the PVC is killed).

**Comment by jsafrane** [comment]
Sorry, wrong issue. Deleting my previous comment.
