### ISSUE TITLE
Internet connection lost on pods when downscaling nodes is in progress

### ISSUE THREAD

**Issue by wmarra** [kubernetes/kubernetes#57798]
**Is this a BUG REPORT or FEATURE REQUEST?:**
bug

**What happened:**
My cluster need to use auto scaling everyday based on demand, but something strange is happening. Everytime when cluster have down scaling some containers lost internet connection returning timeout to access any service outside of the cluster. I don't if that is a bug or a normal behavior caused by auto scaling, but I'd like to share that information with you all to we discussting more about that and if we can do something to improve it.

**What you expected to happen:**
That my pods don't lost internet connection when down scaling happens.

**How to reproduce it (as minimally and precisely as possible):**
Create a k8s cluster into AWS using Kops and _flannel_ like your network cni. Launch some pod making a simple ping in any url and does a manual autoscaling using the aws autoscaling created by kops to your k8s nodes. Done, you'll get some seconds of internet lost.

**Anything else we need to know?:**
The internet connection lost doesn't happening on upscaling, just on downscaling.

**Environment:**

**Kubernetes version (use kubectl version):** v1.8.4
**Cloud provider or hardware configuration:** AWS
**OS (e.g. from /etc/os-release):** Debian
**Kernel (e.g. uname -a):** Linux ip-172-20-62-215 4.4.65-k8s
**Install tools:** Kops
**Others:**  aws autoscaling  group
  
/sig aws
/sig autoscaling

**Comment by mattjmcnaughton** [comment]
Hi @wmarra - thanks for reporting this!

Just to confirm - when you say "my cluster need to use auto-scaling..." are you saying you're using the [kubernetes autoscaler](https://github.com/kubernetes/autoscaler)? If so, you might find that the [autoscaler repo](https://github.com/kubernetes/autoscaler) is more helpful.

Or are you using EC2's auto-scaling (i.e. letting EC2 auto-scale the nodes without any input from Kubernetes)?

Final question - would you mind posting your auto-scaling configuration file and also any pertinent logs (perhaps for a pod that is loosing internet connection during downscaling)?

Thanks!

**Comment by zetaab** [comment]
are your pods running in nodes which are scaled down?

**Comment by leogdiniz** [comment]
Hi @mattjmcnaughton. I work with @wmarra.
I'll see if he can share the autoscaling information.

What I know is that we are using EC2 auto-scaling to add and remove instances from the cluster.
Sometimes when instances are removed from the cluster and Kubernetes removes the nodes all the running pods losses internet connection for around 15 seconds.
It happens to all pods. Not only to the ones that were running in the removed node.

We thought it could be something related to this issue:
https://github.com/moby/moby/issues/11407#issuecomment-97746220

Check the comment from brudrafon.

The only log from the application that I have with me know is this one:

`AmazonClientException: getQueueUrl.
com.amazonaws.SdkClientException: Unable to execute HTTP request: sqs.us-east-1.amazonaws.com
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleRetryableException(AmazonHttpClient.java:1069)`

SQS was working just fine and out of a sudden, it just stopped. The reason was that the pod couldn't reach the internet. About 15 to 30 seconds after this, everything would work just fine again.

**Comment by mattjmcnaughton** [comment]
Ah very interesting! I'll be honest, I'm not sure I have enough context on `moby` to weigh on if that could be the cause. It definitely seems like a possibility.

I suppose one debugging test could be trying auto-scaling with a cluster using the `rkt` container runtime, and seeing if you still experience the same issue. (https://coreos.com/rkt/docs/latest/using-rkt-with-kubernetes.html). But that may be a lot of work to set up...

Given your description of the problem, I think you'll have the best luck at https://github.com/kubernetes/autoscaler or the moby issues. Good luck! This sounds like a tricky one :)
