### ISSUE TITLE
How should I use the key value to execute the command

### ISSUE THREAD

**Issue by shoneSolomon** [kubernetes/kubernetes#57881]
**# How should I use the key value to execute the command, like the following:**

the normal: python main.py --network=network --name=alex;
the new in kubenetes: 
sudo kubectl exec pod_name -c containner_name -- /usr/bin/python2 /root/main.py -network=network -name=alex

**Comment by tpepper** [comment]
Please re-post your question to [Stack Overflow]
(http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support
are posted so that we can improve our efficiency in responding to your requests,
and to make it easier for you to find answers to frequently asked questions and
how to address common use cases.

We regularly see messages posted in multiple forums, with the full response
thread only in one place or, worse, spread across multiple forums. Also, the
large volume of support issues on github is making it difficult for us to use
issues to identify real bugs.

Members of the Kubernetes community use Stack Overflow to field support
requests. Before posting a new question, please search Stack Overflow for answers
to similar questions, and also familiarize yourself with:

  * [user documentation](http://kubernetes.io/docs/)
  * [troubleshooting guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/)

Again, thanks for using Kubernetes.

The Kubernetes Team
