### ISSUE TITLE
kube-proxy NodePort access via localhost, with externalTrafficPolicy=Local => martian source

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#57922]
/kind bug
/sig network

If I set up a service with a NodePort and set `externalTrafficPolicy=Local`, and try to access it as `myhostname:port` it works.  If I try to access it as `localhost:port`, it triggers a martian source error - the packet gets forwarded as 127.0.0.1.  We need some masquerade in there.

Applies to iptables mode.  Maybe ipvs mode, not sure?

**Comment by m1093782566** [comment]
If we set `externalTrafficPolicy=Local` for NodePort, we don't do any masq for packets. Possibly masq will solve the issue in iptables mode, but my question is "do we still need to preserve source ip of packets when externalTrafficPolicy=Local"?

**Comment by m1093782566** [comment]
BTW, with the fix of #57942, `127.0.0.1:nodeport` is reachable, but `localhost:nodeport` does not work.

The iptables created by #57942 is 

```
-A KUBE-NODEPORTS -d 127.0.0.1/32 -p tcp -m comment --comment "default/nginx-service:http" -m tcp --dport 32516 -j KUBE-MARK-MASQ
```

**Comment by beatlejuse** [comment]
this is not entirely true. key "externalTrafficPolicy=Local" needs to be a solution to the problem of obtaining the real IP of the client, but this is not happening. If we do masq, we will not lose the source IP, because now he doesn't work (version 1.8.1)

the problem with the inaccessibility of the actual source IP (https://github.com/kubernetes/kubernetes/issues/58139) in version 1.8.1 is still relevant and is a very big problem for deployment in kubernetes most web services on a production.

besides, in my cluster key "externalTrafficPolicy : false" leads to a hollow stop traffic to the pods.

**Comment by m1093782566** [comment]
@beatlejuse 

Without masq, nodeport for localhost when set "externalTrafficPolicy=Local" won't work. If service is not reachable, say "how to preserve source IP" won't make sense.

Listen, masq is used for someone who want to visit node via localhost when set "externalTrafficPolicy=Local" and don't require preserving source IP. If source IP is really important to you, you can just ignore the `127.0.0.1`.

**Comment by beatlejuse** [comment]
@m1093782566 
I do not understand what do you mean "you can just ignore the 127.0.0.1". could you describe in detail how to configure the service to get the real source IP?

**Comment by m1093782566** [comment]
1. ClusterIP type service, externalTrafficPolicy=[Local | Cluster]

2. NodePort type service, externalTrafficPolicy=Local, but don't try to access `127.0.0.1:port`

3. LoadBalancer type service, externalTrafficPolicy=Local

**Comment by beatlejuse** [comment]
@m1093782566 
2. as i wrote above, NodePort type service with externalTrafficPolicy=Local blocking the transmission of traffic to the pod. I'm trying to connect to node_ip:port.
maybe this is a bug? I could demonstrate this.

**Comment by beatlejuse** [comment]
oh, sorry )) i'm connecting to wrong node ))
yes, now traffic is gone.
but ip is not source!
with "externalTrafficPolicy=Cluster" i getting ip 10.1.29.21 (node ip)
with "externalTrafficPolicy=Local" i getting ip 10.4.62.1 (pods network ip - not real source ip)

**Comment by beatlejuse** [comment]
@m1093782566 
oh, sorry )) i'm connecting to wrong node ))
yes, now traffic is gone.
but ip is not source!
with "externalTrafficPolicy=Cluster" i getting ip 10.1.29.21 (node ip)
with "externalTrafficPolicy=Local" i getting ip 10.4.62.1 (pods network ip - not real source ip)

**Comment by m1093782566** [comment]
You probably should check the iptables applied in your host, is there any masq rules created by other processes other than kube-proxy?

> NodePort type service, externalTrafficPolicy=Local

It preserves the source IP of client - I double checked it.

BTW, you can create another thread for discussing your problems. I feel like this issue is orthogonal with your question.

**Comment by utsav2307** [comment]
@m1093782566 Will setting ClusterIP type service and externalTrafficPolicy=Local  for a service to a DaemonSet, route traffic only to the daemonSet pod in that node when i access the service using DaemonSetServiceIP?

**Comment by m1093782566** [comment]
no. local service does not work for cluster IP
