### ISSUE TITLE
admission webhooks: broken for cluster-scoped resources

### ISSUE THREAD

**Issue by sttts** [kubernetes/kubernetes#57964]
If I am not mistaken, https://github.com/kubernetes/kubernetes/blob/7945ae68d0c7cffb070d60ad4d8bfe6ef585c279/staging/src/k8s.io/apiserver/pkg/admission/plugin/webhook/namespace/matcher.go#L96 means that cluster-scoped resources other than namespaces are broken with admission webhooks.

There is even a unit test checking that: https://github.com/kubernetes/kubernetes/blob/7945ae68d0c7cffb070d60ad4d8bfe6ef585c279/staging/src/k8s.io/apiserver/pkg/admission/plugin/webhook/namespace/matcher_test.go#L116.

**Comment by caesarxuchao** [comment]
To clear any ambiguity around the word "broken", the current code behavior is that most cluster-scoped resources are not subjected to any webhooks.

I wrote them like this because I was concerned with the potential bootstrapping deadlocks: a webhook that enacts policies for cluster-scoped resources might cause bootstrapping deadlocks for the cluster or for its own deployment.

Thinking out loud, perhaps for cluster-scoped resources, the apiserver should only call the webhooks if the resources' labels matching the [webhookConfig.namespaceSelector](https://github.com/kubernetes/api/blob/master/admissionregistration/v1beta1/types.go#L191), so that the critical bootstrapping resources can be excluded from the webhooks, thus breaking the bootstrapping deadlocks. This aligns with what we do for `namespaces` (see [here](https://github.com/kubernetes/api/blob/master/admissionregistration/v1beta1/types.go#L149)). The downside is that the field name "namespaceSelector" becomes inappropriate.

**Comment by sttts** [comment]
> The downside is that the field name "namespaceSelector" becomes inappropriate

I think we still need namespaceSelectors. We don't want to label pods. But I agree we actually want another objectLabelSelector. For namespaces these two coincide, i.e. we only have to define how they are applied if both are set or we forbid both at the same time. I tend to the later.

**Comment by caesarxuchao** [comment]
@lavalamp raised up a security issue regarding `objectLabelSelector`. A user can change labels to skip webhooks. `namespaceSelector` doesn't have this issue because a user usually doesn't have permission to change the namespace's labels.

**Comment by sttts** [comment]
Users normally cannot create cluster-scoped objects either. But techincally it's a valid point.

On the other hand, my main use-case are CRDs. They are not critical to the cluster health (maybe self-hosted clusters are different with etcd operator), i.e. you normally cannot shoot yourself into the foot with a webhook on them. For CRDs we do not need a selector at all.

In other words: IMO we should enable webhooks for cluster-scoped objects, even if we have no  `objectLabelSelector` in place.

**Comment by caesarxuchao** [comment]
> In other words: IMO we should enable webhooks for cluster-scoped objects, even if we have no objectLabelSelector in place.

Sounds reasonable. I'll create a PR.

**Comment by mdruskin** [comment]
We would like to have the ability to apply the admission controller on specific namespaces only, and not on cluster level resources.
This is useful if the list of possible resource Kinds that we want to apply the controller for is large, and we want to limit when it runs as much as possible to avoid affecting the whole cluster in case there's an issue.

I think this can be done by adding a SkipClusterResources flag (or something similar) in addition to the NamespaceSelector, to the Webhook struct. What do you think?

**Comment by lavalamp** [comment]
Zeroth thought: s/SkipClusterResources/scope=[cluster|namespace|both]/g

First thought: can't you just exclude cluster scoped resources, or include only namespace scoped resources in the webhook definition?

Second thought: can a namespace selector be crafted that excludes the empty string?

**Comment by mdruskin** [comment]
0: Are you sure that's cleaner? The namespace selector picks which namespaces to use, and skipCluster decides whether to include cluster resources or not. Not setting it maintains current behavior (skipCluster=false) and whether cluster level resources are included is very clear. scope=cluster/namespace/both will require us to default to "both" which I find slightly more confusing. Also what to do if I specify cluster AND include  namespace selector - is that an invalid spec or do we ignore the selector?

1: Yes. This is the current best thing we can do. If the list of resources is large though (for example, if I am implementing an alternative resource quota controller) then this solution requires us to maintain and update a long list of resources. This may be ok, since as long as our controller can't support certain types of resources it doesn't make sense to watch for them...

2: Doesn't look like it - the current code specifically checks if the attribute is a cluster level resource and skips the entire label matching process.

**Comment by lavalamp** [comment]
Re: 0: fair point, but let's at least name it in the positive: matchClusterScopedResources=true|false or something like that.

**Comment by mdruskin** [comment]
I proposed it in the negative to make it backwards compatible, so that "false" keeps current behavior. I agree that negatively named booleans are not not bad. I'll treat it as true if unspecified and use matchClusterScopedResources.

**Comment by caesarxuchao** [comment]
> Second thought: can a namespace selector be crafted that excludes the empty string?

In today's semantic, such a namespace selector will exclude namespaced objects whose namespace has no label. I find it confusing if we make it to also exclude non-namespaced objects.
