### ISSUE TITLE
Support volume parameters configuration in each PVC

### ISSUE THREAD

**Issue by mlmhl** [kubernetes/kubernetes#57985]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
/kind feature

**What happened**:

Currently(v1.9), when using the dynamic provisioning mechanism of PVC, the parameters required to create a volume are stored in `StorageClass.Parameters`, includes the file system type. If we want to support more than one fs type for a specific volume plugin(such as cinder, rbd, etc.),we need to create a `StorageClass` for each fs type, even though other parameters are the same. This approach makes things tricky, consider the following scenario:

1. We use both `cinder` and `rbd` in a single k8s cluster, and each provisioner supports both `ext4` and `xfs` file system type, so we need to create four `StorageClass`: `cinder-ext4`, `cinder-xfs`, `rbd-ext4`, `rbd-xfs`

2. At the same time we want to set quota for each volume plugin. This is possible as we can't treat the quota of `cinder` and `rbd` as same. This requires us to set a quota for `cinder-ext4` and `cinder-xfs`, and set another quota for `rbd-ext4` and `rbd-xfs`. However we can't meet this requirement right now as we can only set quota for each single `StorageClass` or for the whole `resources.storage`.

So maybe different file system types do not represent different `StorageClass` in some usage scenarios.

**Proposed solution 1**

We use `StorageClass.Parameters` as  default volume creation parameters and allow user to overwrite some parameters(such as file system type) in PVC.

1. alpha: We allow users overwriting volume cereation parameters in `PersistentVolumeClaim.Annotations`, each volume provisioner should read the parameters here before creating a volume. This approach ensures that the API is constant.

2. beta: Add a `Parameters map[string]string` field in `PersistentVolumeClaimSpec` instead of store parameters in `PersistentVolumeClaim.Annotations`. This approach will make API change.

**Proposed solution 2**

Of course we can allow users setting a quota for a series of `StorageClass` instead of for a single `StorageClass` only, such as specified by a common name prefix or a name regex, but this is another topic. We can open another issue to talk about it if this is a reasonable demand.

/kind feature
/sig storage

**Comment by wenlxie** [comment]
+1

**Comment by liggitt** [comment]
> allow user to overwrite some parameters

API mechanisms aside, putting parameter control in the hands of the namespaced pvc creator shouldn't be done for all parameters. Some parameters control things like the namespace and name of the secret to use for mounting the volume, and should obviously not be under the PVC creator's control. 

Special-casing some parameters to be overridable via the PVC would mean they are no longer opaque parameters to the provisioner, which isn't ideal

**Comment by jsafrane** [comment]
There is an old feature https://github.com/kubernetes/features/issues/244 and even proposal https://github.com/kubernetes/community/pull/543 that tried to achieve this, however we gave up as nobody was interested in it enough to lead the design and implementation.

This feature looks easy at the first sight, however there are several complications:

- As @liggitt pointed out, cluster admin must have control over the  parameters that are available to end users.
- Since this is end-user facing API, it must be possible to discover all configurable options and their values so one can write a GUI that shows the options in a way it can be used by "average user". I.e. some discovery API with clear description of the configuration options, allowed values / value ranges and so on.
- All this must be generic enough to accommodate external provisioners, which can expose any configurable option to admin and/or user.

In addition, this configuration breaks portability of PVCs. Right now, you can take all your PVC yaml files and create it in **any** Kubernetes installation. All you need to do is to create storage class that will have expected characteristics (speed, fs type, ...) With PVCs containing any parameters, you need to update the PVCs for the target Kubernetes.

Feel free to resurrect the feature and proposals, however be ready to invest some effort into proper design and implementation.

**Comment by mlmhl** [comment]
Thanks @jsafrane , I will try to improve the proposals as best as I can.
