### ISSUE TITLE
Output from Kubelet's configz endpoint is missing volumePluginDir field

### ISSUE THREAD

**Issue by elemental-lf** [kubernetes/kubernetes#58151]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

Rook uses the Kubelet's configz endpoint to discover the volume plugin directory. This discovery no longer works as the volumePluginDir field has been removed from the kubeletconfig structure by https://github.com/kubernetes/kubernetes/pull/55562 which is included in 1.9.0 and later.

**What you expected to happen**:

Rook should be able to discover the volume plugin directory via the configz endpoint. This field has been removed because it was marked as alpha. I'd argue that this is wrong because the FlexVolume feature has been GA since 1.8 so the --volume-plugin-dir option of Kubelet should be present in the kubeletconfig structure.

**How to reproduce it (as minimally and precisely as possible)**:

```
kubectl proxy --port=8001 &
curl -sSL http://localhost:8001/api/v1/proxy/nodes/$NODE/configz | jq
```
I'd expect the kubeletconfig structure to contain the volumePluginDir field.

**Anything else we need to know?**:

The documentation https://kubernetes.io/docs/tasks/administer-cluster/reconfigure-kubelet/ also mentions the Kubelet configz endpoint for generating a resource from the current Kubelet configuration. This configuration will currently be incomplete when the Kubelet --volume-plugin-dir command line directive is used. DynamicKubeletConfig is currently in alpha so it's seems okay that it's a little bit broken. Just wanted to mention it.

There is a Rook issue open for this at https://github.com/rook/rook/issues/1330.

**Environment**:
- Kubernetes 1.9.1
- CoreOS 1576.5.0

**Comment by elemental-lf** [comment]
I'm unsure which sig labels to add. Adding both node (because of kubelet) and storage (because of volume plugin relation).

@kubernetes/sig-node-bugs
@kubernetes/sig-storage-bugs

**Comment by mtaufen** [comment]
I wouldn't rely on configz (at least as it stands today) for a production use case. It only exists for debugging the Kubelet. It's mentioned in that tutorial for no other reason than that it's a convenient shortcut, the tutorial even calls it out as a hack:
>there is a dirty trick you can use to generate a config file containing a Node’s current configuration.

I will look into why the field is missing, however.

**Comment by mtaufen** [comment]
Regarding the field: if you think it should be in the KubeletConfiguration struct, feel free to send a PR w/ justification to add it back in.

**Comment by kokhang** [comment]
Thanks @mtaufen. I think it would still beneficial for flexvolume consumers to get this field added so that it can be dynamically configured.

**Comment by elemental-lf** [comment]
I concur with @kokhang for the short term. In the medium term an official API  might be best, especially when DynamicKubeletConfig goes forward, but I'm not knowledgeable enough in this area to be qualified to judge this. And unfortunately I can't help with the PR for adding back the field. Sorry.

**Comment by mtaufen** [comment]
I wrote a doc a while back to enumerate some of the things it would take for a more production-ready /configz: https://docs.google.com/document/d/1kNVSdw7H9EqyvI2BYH4EqwVtcg9bi9ZCPpJs8aKZFmM/edit?usp=sharing (you have to join kubernetes-dev@googlegroups.com to view the doc).

Keep in mind that your problem also stems from the fact that the KubeletConfiguration type currently exposed on /configz is considered an alpha API, and is subject to change (but hopefully will move to beta soon).

**Comment by mtaufen** [comment]
Closing this, as the reported problem was effectively "a field disappeared from an alpha API."

**Comment by yasker** [comment]
Sorry to come back to this after it's closed. But I think this worth a second consideration.

The issue we have is:
1. Before removing this parameter, the user can use one official yaml file to start a storage system without any modification.
2. But after removing this parameter, there is no way for the storage system to know where to install the Flexvolume plugin. The user will have to figure that out by themselves, then modify the yaml file before starting the storage system. It's the only missing piece prevents automatic deployment, at least in our cases.
3. The worse thing is, since there is no way for the storage system to tell if the Flexvolume plugin has been installed at the correct directory specified by kubelet, the deployment will success anyway. The user can only find out if it's right after trying to use a volume, which will result in failure if the directory wasn't right. It's bad user experience.
4. It's also hard for the user to know where the `--volume-plugin-dir` is. It wasn't exposed in any kind of API. The user cannot find it through kubectl. The user will have to login to every machine, run `ps` to figure out the parameter.

Considering Flexvolume is GA since Kubernetes 1.8, it's really weird that the automatic deployment of Flexvolume plugin was blocked by the lacking of this parameter. It's the only missing piece since 1.9.

I understand it's alpha API and it can be changed without notice. But given the impact of this change, I want to propose to add it back. I think for the short term, getting the field back to `/configz` makes sense. Also giving CSI is becoming mainstream (and that directory is fixed, at least for now), we may not need to worry about it this time next year.

I can contribute a patch to add it back. But I am not very familiar with K8s's stable release process. Can we make 1.9 and 1.10 pick it up for the stable release?

**Comment by mtaufen** [comment]
/config should not become a critical part of your deployment workflow right
now. You can't guarantee stable APIs to your customers if you build on top
of unstable ones.

I understand /configz looks like an easy solution to your problem, but it
just plain should not be relied on in it's current state.

I would like its API to eventually stabilize (
https://docs.google.com/document/d/1kNVSdw7H9EqyvI2BYH4EqwVtcg9bi9ZCPpJs8aKZFmM/edit?usp=drivesdk),
and I would eventually like all the Kubelet config to be available there
after flags finish migrating to our versioned config API (
https://github.com/kubernetes/kubernetes/issues/61650).

Even then, I question whether /configz is the correct way to discover node
filesystem topology. This is not what it is intended for - you just got
lucky that volumePluginDir was in it at one point.

I understand that this is painful for you, and wouldn't it be great if we
just had to do this one thing to make it work, but I can't make the kind of
stability commitment you are asking for from /configz.

**Comment by mtaufen** [comment]
No time estimate, unfortunately. I don't think anyone is allocated to complete that work right now. I'm happy to review any related PRs, of course :).
