### ISSUE TITLE
Improve autoclosing of properly labeled issues 

### ISSUE THREAD

**Issue by discordianfish** [kubernetes/kubernetes#58170]
Hi,

@fejta-bot closes all(?) issues after 90d of inactivity. I understand the reasons but find that quite aggresive.

If an issue was labeled properly and there isn't any other indicator that it might got stale (as in nobody cares anymore about it), it shouldn't get auto-closed. There is no reason to believe it got stale if in fact just nobody had time to look into it. It also sets an incentive to leave `+1` on each issues you run into, just leading to more noise.

Maybe stale issues should just get labeled as such and it's up to the sig maintainers to actually close it.

/cc @fejta
/sig testing

**Comment by discordianfish** [comment]
Oh this irony.
/remove-lifecycle stale
/lifecycle freeze

**Comment by BenTheElder** [comment]
filing this against [test-infra](https://github.com/kubernetes/test-infra) instead will get more eyes, fejta-bot is project wide and this repo has wayyyy too many issues.

> @fejta-bot closes all(?) issues after 90d of inactivity. I understand the reasons but find that quite aggresive.

It also doesn't close them after 90 days, it marks them stale after 90days with a comment, then if there is no response it marks them rotten with another comment after another 30 days, and then after _another_ 30 days it closes rotten issues if there is still no response.

see some previous discussion here: https://groups.google.com/forum/#!searchin/kubernetes-sig-testing/issues$20close%7Csort:date/kubernetes-sig-testing/_5AUPG8kbKM/Ppq393goCQAJ

Issues can also be frozen with `/lifecycle frozen` and fejta-bot will not interact with them.

**Comment by discordianfish** [comment]
For the record, I'm really frustrated by this responds and lack of discussion around this. In the future I'll only create issues for things I can commit myself to fixing it.

**Comment by BenTheElder** [comment]
There's a lack of further discussion here because it's the wrong place to discuss it and that discussion already occurred in depth elsewhere. If you'd like to discuss please bring it to the contributor experience sig, issues in this repo are for the kubernetes core components (which have code here). Even feature requests are generally redirected to github.com/kubernetes/features and kubeadm issues to github.com/kubernetes/kubeadm (despite the code being in this repo) to keep the issue trackers more manageable.

Issues close after 150 days of no human interaction because at that point neither the contributors nor the author nor anyone else with a GitHub account have been involved for nearly half a year. The issue still exists and can be reopened, but keeping it out of the open issues helps triage new issues that may actually be fielded by one of the contributiors. If you think your issue needs no interaction for some reason, you can comment `/lifecycle frozen` once, as mentioned above.

**Comment by BenTheElder** [comment]
Unfortunately the best way to get an issue looked at is to actually bring it to the attention of contributors (ideally one of the SIGs specifically) through any other channel as the volume of GitHub issues is so high.
