### ISSUE TITLE
In some admission plugins Validate is called twice

### ISSUE THREAD

**Issue by hzxuzhonghu** [kubernetes/kubernetes#58196]
**Is this a BUG REPORT or FEATURE REQUEST?**:

 /kind bug

**What happened**:
in some admission plugins, ValidationInterface.Validate will be called twice, like `ServiceAccount`.
https://github.com/kubernetes/kubernetes/blob/a19f6d147c3775efd2d91c69be95e9a02934223f/plugin/pkg/admission/serviceaccount/admission.go#L180

Secondly called https://github.com/kubernetes/kubernetes/blob/a19f6d147c3775efd2d91c69be95e9a02934223f/staging/src/k8s.io/apiserver/pkg/admission/chain.go#L51

I think this is a redundant work

**What you expected to happen**:

Validate be called only once, in validating stage.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by hzxuzhonghu** [comment]
open a pr #58197 to fix it.

**Comment by liggitt** [comment]
this is not a bug, it is an intentional factoring.

during the Admit phase, these plugins do some mutation and some validation. if the validation fails, we want to reject early.

during the Validate phase, they recheck that the result is still valid (and hasn't been invalidated by other things in the Admit phase)
