### ISSUE TITLE
kubectl patch should not exit with a non-zero exit code on no changes 

### ISSUE THREAD

**Issue by wknapik** [kubernetes/kubernetes#58212]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
`kubectl patch` exits with exit code 1 when there are no changes.

**What you expected to happen**:
I expected the exit code to be 0.
A warning could be printed to stderr, but the exit code should be 0, since no error occurred.
This is really annoying in automation, where the non-zero exit code means "something went wrong, bail".

**How to reproduce it (as minimally and precisely as possible)**:
```
$ kubectl create configmap foo
configmap "foo" created
$ kubectl patch configmap/foo --patch $'data:\n  foo: bar'
$ kubectl patch configmap/foo --patch $'data:\n  foo: bar'
configmap "foo" not patched
$ echo "$?"
1
$
```

**Anything else we need to know?**:
Don't think so.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2017-12-15T21:07:38Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.4", GitCommit:"9befc2b8928a9426501d3bf62f72849d5cbcd5a3", GitTreeState:"clean", BuildDate:"2017-11-20T05:17:43Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
AWS
- OS (e.g. from /etc/os-release):
Arch Linux
- Kernel (e.g. `uname -a`):
4.14.11
- Install tools:
?
- Others:
N/A

**Comment by wknapik** [comment]
If it was at least a unique exit code, I could do `|| [[ "$?" -eq 1 ]]` and be done with it, but exit code 1 is used for actual errors, like "Error from server (NotFound)", etc.

**Comment by wknapik** [comment]
Also, the 'configmap "foo" not patched' is printed to stdout, instead of stderr.

**Comment by yangyumo123** [comment]
/sig maybe this is not a bug, if you think this is a bug, you can modify like this,
remove below code in pkg/kubectl/cmd/patch.go   RunPatch function.
or add some condition，like GCE or AWS platform judge，first patch，second patch，and so on.

// if object was not successfully patched, exit with error code 1
if !didPatch {
  return cmdutil.ErrExit
}

**Comment by liggitt** [comment]
Related to https://github.com/kubernetes/kubernetes/pull/52647#issuecomment-335114382 and #52577

**Comment by shiywang** [comment]
Firstly, this change was introduced in https://github.com/kubernetes/kubernetes/pull/52450, and apologies for that I didn't have a thoughtful review.

Here is my understanding: (@liggitt please correct me if I'm wrong)

1. From k8s developer perspective, `apply` `patch` should consider as `idempotent ("make-it-so") commands` and according to conventions [here](https://github.com/kubernetes/community/blob/master/contributors/devel/kubectl-conventions.md#exit-code-conventions), patch should not directly throw an error when `not patched` it should only if user set the flag `--error-unchanged`, which is my pr here: https://github.com/kubernetes/kubernetes/pull/52647 was going to implement.

2. But since @juanvallejo change the behaves to directly throw an error (exit 1), if that is user want, or it could be more acceptably consider as "normal" user behavior, then I could also add an `--ignore-unchanged` flag to address this issue, but it will mess up with the convention docs  [here](https://github.com/kubernetes/community/blob/master/contributors/devel/kubectl-conventions.md#exit-code-conventions)

I lean to option1(which is also my pr https://github.com/kubernetes/kubernetes/pull/52647 here currently working on)  

@juanvallejo @liggitt @smarterclayton which one do you prefer, or have any better ideas ?

**Comment by shiywang** [comment]
Also we distinguish idempotent or non-idempotent commands by HTTP method right ? @liggitt

**Comment by wmlynch** [comment]
I found this issue:  https://github.com/kubernetes/kubernetes/issues/58212

**Comment by filipnowakswissre** [comment]
i don't want to create new bug for this, but for me main problem is that in case of rc == 1 you are writing to stdout instead of stderr - like it was the case before breaking release of kubectl.

**Comment by bendrucker** [comment]
Here's how I'm working around this in scripts to get an idempotent patch in case it's helpful for anyone:

```sh
set +e
result=$(kubectl patch serviceaccount default --namespace "$namespace" --patch '{"imagePullSecrets": [{"name": "jfrog"}]}')
code="$?"
if [[ "$code" != "0" && "$result" == *" not patched" ]]; then
  echo "$result" 1>&2
  exit "$code"
fi
set -e
```

Happy to help if needed on #52647, seems like that's pretty much good to go though.

**Comment by kivagant-ba** [comment]
I don't know if there is a separate issue for that, but same problem with `set resources`

```
kubectl set resources deployment -n kube-system tiller-deploy --requests=cpu=10m,memory=100Mi,ephemeral-storage=100Mi --limits=memory=512Mi,ephemeral-storage=1Gi
error: info: {extensions v1beta1 deployments} "tiller-deploy" was not changed
```
