### ISSUE TITLE
The BestEffort pod maybe rejected by kubelet with toleration

### ISSUE THREAD

**Issue by k82cn** [kubernetes/kubernetes#58505]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**Description**:

According to the preemption's doc, we'll take priority over Qos; but in [kubelet eviction manager](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/eviction/eviction_manager.go#L134), the higher priority BestEffort pod maybe rejected because of memory pressure. If TaintNodesByCondition enabled, the pod need memory pressure toleration.

/cc @bsalamat @dashpole , correct me if any mis-understanding.

**Comment by dashpole** [comment]
If the node has memory pressure, it rejects all pods that do not tolerate it.  This is orthogonal to QoS and Priority.

**Comment by bsalamat** [comment]
@k82cn,
Preemption and node evictions do not work with the same exact metrics. Preemption is unaware of usage, while node evictions has pod and node resource usage information. Node eviction takes usage into account both when admitting a new pod and when evicting an existing pod. @dashpole has recently sent out [this PR](https://github.com/kubernetes/website/pull/6949) to update node eviction doc.

**Comment by k82cn** [comment]
@dashpole , but [managerImpl.Admit](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/eviction/eviction_manager.go#L134) will also reject it if pod tolerate it :(

**Comment by k82cn** [comment]
@dashpole , please refer to #58580 for what I mean :).

BTW, you need to configure out `CheckNodeMemoryPressure` and `CheckNodeDiskPressure` predicates, and enable `TaintNodesByCondition` alpha feature.

/cc @gmarek

**Comment by gmarek** [comment]
I'm not familiar with the Preemption/Priority design, so I don't know where is preemption happening (Node or control plane).

But despite that I wouldn't read what you wrote as inconsistency. Priority takes precedence over QoS when it can. But if some QoS Pods are not allowed to run somewhere it's not an issue with preemption/priority or QoS. It's a separate predicate.

Slight OT, but related to your proposal, I think we should go another way. We should prevent BE pods to get MemoryPressure toleration. Having this can result with bad user experience, as Pod will get scheduled on a Node, and then immediately killed, because Kubelet ignores tolerations. Or we can teach kubelet respect tolerations for NC created taints. I'd consider it a blocker for beta of TaintNodeByCondition.

**Comment by k82cn** [comment]
> Having this can result with bad user experience, as Pod will get scheduled on a Node, and then immediately killed, because Kubelet ignores tolerations

Yes; but if BE pod has higher priority, the other pods with lower priority will be evicted by kubelet.

> We should prevent BE pods to get MemoryPressure toleration.

This maybe better, no idea on which pod will be BE but with higher priority :) @bsalamat , do you think we should reject BE pod with MemoryPressure toleration, even it has a higher priority?

**Comment by bsalamat** [comment]
I would like to mention several points here:
1. First of all, I should say that a high priority BE pod is a result of bad configuration and we should not optimize for it, but given that it is not rejected by the system, we must handle it.
1. A BE pod will never cause preemption due to lack of resources, because a BE pod needs zero resources from scheduler's point of view.
1. Because of point #1, I think we should not worry about a high priority BE pod getting rejected by kubelet or causing other pods to be evicted from a node. We should document the system behavior and have clear guidelines and point out the problems that could be caused by bad configurations. After that we should leave it to the user to decide if a configuration makes sense for their use-case.

**Comment by k82cn** [comment]
Overall, I agree :). Personally, I'd like to keep components behavior align: reject by admission/kubelet or accept by them. Currently, apiserver/scheduler accept and handle it and kubelet will reject it.

**Comment by bsalamat** [comment]
> Currently, apiserver/scheduler accept and handle it and kubelet will reject it.

Kubelet does not reject a BE pod with high priority either.

**Comment by k82cn** [comment]
> Kubelet does not reject a BE pod with high priority either.

I mean BE pod with Memory Pressure toleration :)

**Comment by bsalamat** [comment]
> I mean BE pod with Memory Pressure toleration

I see. The pod may still be scheduled without any problem if another node in the cluster is found that does not have memory pressure. So, I wouldn't call this inconsistent behavior of components.
Anyway, I leave it up to SIG node to decide whehter the current behavior should be changed.
