### ISSUE TITLE
Support for attach/detach of Local PVs to pod without pod restart

### ISSUE THREAD

**Issue by kmova** [kubernetes/kubernetes#58569]
FEATURE REQUEST

/kind feature

**What happened**:
I contribute to openebs - (which falls into the category of container native storage, orchestrated storage or container attached storage. It is comparable to glusterfs, rook, portworx etc.,). These storage solutions run within K8s and provide storage (persistent volumes) to stateful workloads. 

These storage solutions comprise of two types of pods:
(a) core storage pod (typically run as daemon sets) that access the underlying disks by mounting "/dev"
(b) storage operator pods that typically help with:
    - maintain inventory of disks attached to the nodes and which are already used etc,. 
    - extending the available storage by adding new disks.
    - adding cache (an NVMe partition)
    - replacing a failed disk on the node with a new one

I am trying to explore the possibility of delegating (or using) some of the functionality provided by the Local Storage PV supported recently added to K8s. Specifically the inventory management, scheduling of core storage pods based on the availability of disk etc.).

However, the hard requirement for having to restart a pod whenever Local PVs are attached/dettached to/from a pod is not a desirable behaviour when it comes to core storage pods -- which can in turn have performance impacts to the stateful workloads they serve. 

**What you expected to happen**:

There should be a mechanism that will help attach/detach Local Storage PVs to the pods without requiring a pod-restart. 

**How to reproduce it (as minimally and precisely as possible)**:
NA

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by dashpole** [comment]
cc @kubernetes/sig-storage-feature-requests  

> - extending the available storage by adding new disks.
> - adding cache (an NVMe partition)
> - replacing a failed disk on the node with a new one

I am not very familiar with the inner workings of container storage, but at first glance it seems like a mechanism to modify storage "underneath" a pod without needed to attach/detach or restart pods is more in-line with how kubernetes treats container resources.  Generally, we strive to ensure applications don't require knowledge of infrastructure (e.g. having to know which volumes are currently mounted).

**Comment by msau42** [comment]
Sorry I've been busy this week. I will think about this next week.

**Comment by msau42** [comment]
@kmova are you ok with the container restarting?  I don't think container runtimes support live mounting new volumes to a running container.  Restarting a container might be slightly faster than restarting a pod, but if the issue is the application startup time, then I'm not sure if avoiding a pod restart will help much.

Regardless, changing the volume manager to handle live-updating of volumes to running pods will be a very large undertaking.  This would impact the coordination between setup and teardown of volumes, maybe also the coordination with the attach controller, and would need very careful consideration to handle data safety.

Instead, I would like to explore other ways that you can still take advantage of the scheduling capabilities with Local PVs.  

The first challenge I see is the use of Daemonsets.  Local PV, as it stands, is designed for StatefulSets, where each replica gets is own PVCs.  Daemonsets currently don't support PVC templates (although there was some talk about adding it), so if you specify a PVC in a DaemonSet, all your DaemonSet pods are going to share the same PVC, which is not going to work for local storage.  Another problem with DaemonSets is it bypasses the scheduler, which is where the Local PV binding logic lives.  If those two issues are fixed with DaemonSets, then they should be able to use Local PV just like StatefulSets.  Although, StatefulSets currently has some more [advanced upgrading capabilities](http://blog.kubernetes.io/2017/09/kubernetes-statefulsets-daemonsets.html) that may be worth considering.  I'm unsure if there are plans to support these for DaemonSets in the future.

The next challenge is exposing the PVs to the core storage pods.  There are two ways I can think of to do this without having to modify the Pod spec and restart the Pod:
1. Expose the device directory as a Local PV, similar to what you're doing already with hostpath "/dev", but with scheduling support.  This has the advantage that it can support different storage configuration on different nodes.  For example, if you enumerated every disk as a PVC in the StatefulSet template, that means all the replicas of your StatefulSet have to have the same number of PVCs, which is not very realistic in a non-cloud environment.  Your disk inventory pod could put the disks under a special directory so your core storage pod doesn't need to figure out which devices it needs to manage.
2. Combine all the disks into a single shared volume, ie LVM.  I believe this is what gluster does.  Add RAID for transparently handling disk failures.  Whenever you add a new disk, you just increase the size of the VG.  Although I think the volume resize feature may require a Pod restart so that we can expand the filesystem when the volume is unmounted.  cc @gnufied for resizing, @humblec for gluster.  I'm also unsure of the performance impact by aggregating the disks together.

In general, I think specifying heterogeneous storage config with a higher level pod templating specification (ie statefulsets, daemonsets) is not possible unless you can abstract the different configs under a common structure, like a single directory or shared volume.

cc @ianchakeres @dhirajh  -- they're using Local PVs for distributed storage with StatefulSets and may be able to provide some further insights and challenges

**Comment by kmova** [comment]
Thanks @msau42 for the very detailed response. It helped me to make my choice. I am currently exploring the option 1 suggested above to expose the device directory. Making some progress with getting this implemented in a generic way. https://github.com/openebs/node-disk-manager/pull/1
