### ISSUE TITLE
kubelet configmap and secret cache cleared every time pod is updated regardless of ttl

### ISSUE THREAD

**Issue by anfernee** [kubernetes/kubernetes#58639]
**Is this a BUG REPORT or FEATURE REQUEST?**: 
/kind bug

**What happened**: If a configmap/secret is referenced by one pod on a node (which is a very common case), whenever the pod is updated for whatever fields that is not related to configmap/secret, the configmap/secret cache will be cleared, regardless what "node.alpha.kubernetes.io/ttl" is configured.

Another thing is the secret package and configmap package inside kubelet are line-to-line identical.

**What you expected to happen**: The ttl should still be honored. 

**How to reproduce it (as minimally and precisely as possible)**: as described above.

**Comment by anfernee** [comment]
From the comment it says this:

https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/configmap/configmap_manager.go#L239-L240

but it seems it's not doing this in the real implementation, confusing. Need to double check.

**Comment by liggitt** [comment]
>  If a configmap/secret is referenced by one pod on a node (which is a very common case), whenever the pod is updated for whatever fields that is not related to configmap/secret, the configmap/secret cache will be cleared, regardless what "node.alpha.kubernetes.io/ttl" is configured.

That is intentional. Otherwise, updating a source secret or configmap, then updating a pod's image or deploying a new pod would not be guaranteed to see the new secret/configmap content.

when a secret or config map reference is added, the cached object is cleared and is fetched on next Get():

https://github.com/kubernetes/kubernetes/blob/ddea2dd56ff76168d2597c9cea62aa110a78f81c/pkg/kubelet/secret/secret_manager.go#L146-L147

https://github.com/kubernetes/kubernetes/blob/ddea2dd56ff76168d2597c9cea62aa110a78f81c/pkg/kubelet/configmap/configmap_manager.go#L146-L147

/close
