### ISSUE TITLE
Target in prometheus is showing down.

### ISSUE THREAD

**Issue by AnkitVaidya01** [kubernetes/kubernetes#58670]
Below is my prometheus.yml file 

![image](https://user-images.githubusercontent.com/34238738/35262213-b164aac6-0039-11e8-982f-2ef6c74e3058.png)

But on prometheus UI the target is showing as down.

![image](https://user-images.githubusercontent.com/34238738/35261981-948d40e4-0038-11e8-8e22-4d92ecad6e39.png)

Also prometheus not giving any stats for application running on node.

@brancz @grobie @tomwilkie @matthiasr @jimmidyson@fabxc @kubernetes/sig-instrumentation

**Comment by brancz** [comment]
You're using the wrong config. Use this one: https://github.com/prometheus/prometheus/blob/master/documentation/examples/prometheus-kubernetes.yml

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue on Kubernetes. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
