### ISSUE TITLE
v1 API cannot be used to access GKE regional clusters

### ISSUE THREAD

**Issue by pavank1933** [kubernetes/kubernetes#58736]
Tried to create GKE cluster in europe-west3.
Command:
**gcloud container clusters create test-cluster  --num-nodes=3 --zone europe-west3**
Facing the below issue:-
ERROR: (gcloud.container.clusters.create) ResponseError: code=400, message=v1 API cannot be used to access GKE regi
onal clusters. See http://goo.gl/Vykvt2 for more information

Tried many scenarios, still the same issue

**Comment by pavank1933** [comment]
Resolved the above issue by executing the below two commands:
    $ gcloud config set project PROJECT_ID
    $ gcloud config set compute/zone eu-*****

**Comment by JordieB** [comment]
Pavank1933's solution didn't work for me (i.e. setting my project id and compute/zone).

The real reason why Pavank and I were getting this error was because for `--zone` we chose regions and not zones specifically.

For example, I received this error because I set `--zone=us-west1` which is a region and not a zone. I instead chose `--zone=us-west1-a` which worked. The regions and their subsequent zones can be found here: https://cloud.google.com/compute/docs/regions-zones/#available

**Comment by Winterflower** [comment]
Thank you @JordieB - very helpful!

**Comment by venumurthy** [comment]
gcloud is turning out to be as problematic as every other google product.... have sorted this issue and now facing ERROR: (gcloud.container.clusters.create) ResponseError: code=403, message=Required "container.clusters.create" permission for "projects/xxxx".

**Comment by zeroasterisk** [comment]
I ended up having to supply a zone vs. a region, but that did get it working:
```
$ gcloud container clusters create mytest1 --num-nodes=2 --zone=us-central1-a --enable-autorepair
```

**Comment by pomodroizer** [comment]
If you go to your Kubernetes cluster (in the web page https://console.cloud.google.com/kubernetes/list) and click `connect`, it will prompt you with the correct command:
`export CLOUDSDK_CONTAINER_USE_V1_API_CLIENT=false && export CLOUDSDK_CONTAINER_USE_V1_API=false && gcloud beta container clusters get-credentials <PROJECT_ID>-gke-cluster --region europe-west2 --project <PROJECT_ID>`

**Comment by poram** [comment]
Thanks @JordieB, very helpful.
