### ISSUE TITLE
cluster autoscaling not working on multizone.. scaling up only in first zone?

### ISSUE THREAD

**Issue by dineshsckloud9** [kubernetes/kubernetes#58796]
**Wants to confirm Bug or Issue in configuration**:

Trying to create multizone cluster with autoscaling. I am able to create multizone cluster and second managed instance group instance added to the master and works fine until that.

When load increases kube-control-manager spinning up nodes only in first zone, it is not multizone autoscaling, it seems...

What could be the issue? Is this a bug?

**What happened**:
cluster autoscaling not working on multizone..

**What you expected to happen**:
cluster autoscaling in multiple zones. It not scaling on second zone.

**How to reproduce it (as minimally and precisely as possible)**:

using following command :

MULTIZONE=true KUBERNETES_PROVIDER=gce KUBE_GCE_ZONE=europe-west1-b  ENABLE_ETCD_QUORUM_READS=true ENABLE_CLUSTER_AUTOSCALER=true AUTOSCALER_MIN_NODES=1 AUTOSCALER_MAX_NODES=4 NUM_NODES=1 ./kube-up.sh

==> using ENABLE_ETCD_QUORUM_READS to enable HA master which is not required,

KUBE_USE_EXISTING_MASTER=true MULTIZONE=true KUBERNETES_PROVIDER=gce KUBE_GCE_ZONE=europe-west1-c NUM_NODES=1 ENABLE_CLUSTER_AUTOSCALER=true AUTOSCALER_MIN_NODES=1 AUTOSCALER_MAX_NODES=4 NUM_NODES=1 ./kube-up.sh

==> It creates 2 MIG and works well, checked with scaling pods and pods are being scaled in second zone node.

==> But when scale pods over 20 it needs more nodes to handle so it started scaling,

But did not scale in second zone, only scale 4 nodes in first zone.. also checked with 10 nodes and 100 pods. still same issue

**Environment**:
- Kubernetes version (use `kubectl version`): v1.9.2
- Cloud provider or hardware configuration: GCE
- OS (e.g. from /etc/os-release): Container-Optimized OS
- Kernel (e.g. `uname -a`):Linux kubernetes-master 4.4.64+ #1 SMP Wed Aug 30 20:27:36 PDT 2017 x86_64 Intel(R) Xeon(R) CPU @ 2.60GHz GenuineIntel GNU/Linux
- Install tools:
- Others:

/sig scalability
/sig multizonclustering

**Comment by dineshsckloud9** [comment]
For second node kube-control-manager is saying no node group config


I0125 07:22:04.001560       5 static_autoscaler.go:280] Calculating unneeded nodes
I0125 07:22:04.205565       5 utils.go:398] Skipping kubernetes-minion-group-scg7 - no node group config
I0125 07:22:04.205606       5 utils.go:407] Skipping kubernetes-minion-group-1cxd - node group min size reached

**Comment by mwielgus** [comment]
cc: @bskiba @wojtek-t

**Comment by bskiba** [comment]
The problem here is that the kube-up.sh scripts are not set up to work well with multiple zones and Cluster Autoscaler, and we do not plan to add such support. 

However, you can tell autoscaler about the node groups in other zones so that it can start to scale them up.
SSH to the master node and take a look at /etc/kubernetes/manifests/cluster-autoscaler.manifest
It contains a parameter --nodes=<min>:<max>:<MIG link>. This flag can be used to point autoscaler to MIGs that it should autoscale. You can specify it multiple times if you have multiple MIGs. 

In your case there is at the moment probably only one --nodes flag containing the node group in the main zone (europe-west1-b). If you add --node flags for the MIG(s) in the additional zone(s), autoscaler should start scaling them up too.

As a side note, there is an MIG autodiscovery feature coming to Cluster Autoscaler on GCE, where you will be able to specify a MIG prefix and autoscaler will automatically discover and scale MIGs with this prefix.

**Comment by dineshsckloud9** [comment]
In my case i tried adding flag --nodes=:: 2 times and its not scaling at all.. Even in first zone its not scaling

**Comment by bskiba** [comment]
I'm sorry, I've made a mistake in my post, I updated it. 

The flag should be following: --nodes={min}:{max}:{MIG link}, where min=minimum number of nodes, max=maximum number of nodes, MIG link is sth like:
https://www.googleapis.com/compute/v1/projects/{project-name}/zones/{mig-zone}/instanceGroupManagers/{mig-name}

**Comment by dineshsckloud9** [comment]
Will it work if i give region instead of zone?

https://www.googleapis.com/compute/v1/projects/{project-name}/regions/{REGION}/instanceGroupManagers/{mig-name}

**Comment by bskiba** [comment]
Unfortunately no, Kubernetes works with zonal MIGs on GCE

**Comment by dineshsckloud9** [comment]
I'm running cluster-autoscaler v1.1.0 and trying from kubernetes 1.9.2 in GCE

**Comment by dineshsckloud9** [comment]
Multizone scaling with MIG per zone seems working but could not launch more than 3 instances.. MIG showing 1 -> 2 but its not launching in gce... What could be the problem?
