### ISSUE TITLE
kubectl apply -o yaml does not output proper yaml when changing multiple objects

### ISSUE THREAD

**Issue by davidhao3300** [kubernetes/kubernetes#58834]
**Is this a BUG REPORT or FEATURE REQUEST?**: Bug report

/kind bug

**What happened**: Given the following file:
```
kind: ConfigMap
apiVersion: v1
metadata:
  name: test
data:
  key1: apple
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: test2
data:
  key2: apple
```
returns 
```
apiVersion: v1
data:
  key1: apples
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"key1":"apples"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"test","namespace":"some-namespace"}}
  creationTimestamp: 2018-01-25T22:43:35Z
  name: test
  namespace: somenamespace
  resourceVersion: "12144"
  selfLink: /api/v1/namespaces/some-namespace/configmaps/test
  uid: 2dc1c468-0221-11e8-bce4-8ece3fb0c49d
apiVersion: v1
data:
  key2: apples
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"key2":"apples"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"test2","namespace":"some-namespace"}}
  creationTimestamp: 2018-01-25T22:43:35Z
  name: test2
  namespace: some-namespace
  resourceVersion: "12145"
  selfLink: /api/v1/namespaces/some-namespace/configmaps/test2
  uid: 2dc2d982-0221-11e8-bce4-8ece3fb0c49d
```
which is not valid yaml (needs a document separator)
**What you expected to happen**: For the output to be a List object containing the 2 ConfigMaps

**How to reproduce it (as minimally and precisely as possible)**: Described above

**Anything else we need to know?**: The -o json flag returns something similar, where it's just JSON bodies concatenated one after another. Not sure if that's considered valid json.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.8.6 client/server
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): 17.3.0 Darwin Kernel Version 17.3.0: Thu Nov  9 18:09:22 PST 2017; root:xnu-4570.31.3~1/RELEASE_X86_64 x86_64
- Install tools:
- Others:

**Comment by davidhao3300** [comment]
I do need to confirm whether this is still occurring on master

**Comment by davidhao3300** [comment]
Confirmed on latest stable version
@kubernetes/sig-cli-bugs

**Comment by yue9944882** [comment]
Additionally for `-o yaml`, Should the output be printed in the form of `[{...},{...}]`, but now instead it is:

```
{
    "apiVersion": "v1",
    "data": {
        "key1": "apple"
    },
    "kind": "ConfigMap",
    "metadata": {
        "annotations": {
            "kubectl.kubernetes.io/last-applied-configuration": "{\"apiVersion\":\"v1\",\"data\":{\"key1\":\"apple\"},\"kind\":\"ConfigMap\",\"metadata\":{\"annotations\":{},\"name\":\"test\",\"namespace\":\"default\"}}\n"
        },
        "creationTimestamp": "2018-02-08T03:05:33Z",
        "name": "test",
        "namespace": "default",
        "resourceVersion": "241812",
        "selfLink": "/api/v1/namespaces/default/configmaps/test",
        "uid": "eda47399-0c7c-11e8-bb1d-0800276d87e5"
    }
}
{
    "apiVersion": "v1",
    "data": {
        "key2": "appleZ"
    },
    "kind": "ConfigMap",
    "metadata": {
        "annotations": {
            "kubectl.kubernetes.io/last-applied-configuration": "{\"apiVersion\":\"v1\",\"data\":{\"key2\":\"appleZ\"},\"kind\":\"ConfigMap\",\"metadata\":{\"annotations\":{},\"name\":\"test2\",\"namespace\":\"default\"}}\n"
        },
        "creationTimestamp": "2018-02-08T03:05:33Z",
        "name": "test2",
        "namespace": "default",
        "resourceVersion": "241814",
        "selfLink": "/api/v1/namespaces/default/configmaps/test2",
        "uid": "edafefca-0c7c-11e8-bb1d-0800276d87e5"
    }
}
```
Which is also not a legal json either.

**Comment by k1-hedayati** [comment]
It seems like if there is multiple objects in `yaml` output kubectl already wraps them in `kind: List` type and generated `yaml` is valid.

**Comment by davidhao3300** [comment]
I will verify if this is true on the master branch, it's possible that the change is not on 1.8.6, which is the version we use

**Comment by k1-hedayati** [comment]
I've checked this with `v1.9.3`

**Comment by evandigby** [comment]
This is also true for `kubectl create -f`...

**Comment by davidhao3300** [comment]
@k1-hedayati how did you get kind: List to be returned? I just verified that 1.9.3 has the same bug

**Comment by mengqiy** [comment]
The reason is that there is an API call for each object, and it simply prints whatever the API call returns.
@juanvallejo We may want to aggregate them before printing, or you may have some a better solution.

**Comment by evandigby** [comment]
@davidhao3300 Were you hoping to work on this? If not, I would like to take this on.

cc @seans3 @mengqiy I would like to take this

**Comment by davidhao3300** [comment]
I don't think the PR quite addresses the issue - I'm waiting for @k1-hedayati to get back on how they got the `kubectl apply` command to return a List object instead of the malformed yaml objects

**Comment by davidhao3300** [comment]
in response to @mengqiy's comment, given the behavior of calling `kubectl convert` or just `kubectl get`'ing a list of objects from the server, it seems the best way is to wrap the return response in a List object if there's multiple items

**Comment by mengqiy** [comment]
> given the behavior of calling kubectl convert or just kubectl get'ing a list of objects from the server, it seems the best way is to wrap the return response in a List object if there's multiple items

You can't POST or PATCH the a list of resources.
The aggregation should happen client-side.

**Comment by k1-hedayati** [comment]
Ok sorry I thought issue is about `kubectl get` and totally missed `apply` on issue title :/
So that PR is not relevant to this issue. I'm not sure if I can work on this for a few days, @evandigby if you're still interested  feel free to take this issue on

**Comment by nbaztec** [comment]
I glanced over the issue and it seems the real discussion is if and what should actually be fixed. This issue seems to originate from YAMLs doc separators - whereas the json equivalent would be to `cat kube-service-*.json | kubectl apply -f - `. And since JSON doesn't have doc separators, the result objects would need to be aggregated into a `api.List`, so they look something like below.

However, it can also be seen as results to 2 distinct operations and the behavior be kept as-is given that there's no other way to implement a `---` approach for JSON.

Output for `List` type:
```
apiVersion: v1
items:
- apiVersion: v1
  data:
    key1: apple
  kind: ConfigMap
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","data":{"key1":"apple"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"test","namespace":"default"}}
    creationTimestamp: 2018-03-08T12:24:57Z
    name: test
    namespace: default
    resourceVersion: "196"
    selfLink: /api/v1/namespaces/default/configmaps/test
    uid: b6c84b87-22cb-11e8-a4e9-d481d7ee6c75
- apiVersion: v1
  data:
    key2: apple
  kind: ConfigMap
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","data":{"key2":"apple"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"test2","namespace":"default"}}
    creationTimestamp: 2018-03-08T12:24:57Z
    name: test2
    namespace: default
    resourceVersion: "197"
    selfLink: /api/v1/namespaces/default/configmaps/test2
    uid: b6c8e58f-22cb-11e8-a4e9-d481d7ee6c75
kind: List
metadata: {}
```
- which to some extent makes sense since we can create the two resources via `List` kind input as well.

I already have some code written there, so if we wish to proceed with this approach I can submit a PR.

**Comment by evandigby** [comment]
I agree with @nbaztec that there is complexity in dealing with both JSON and YAML output. Ultimately what's coming out are two distinct "files"--the output from two different operations. 

The original report describes the expected output to being a list, which agrees with @nbaztec described solution. 

As a user I'd be fine with the list output for programmatic use; however, visually to me it doesn't distinguish the two distinct outputs (neither does the current output). For that reason only I prefer the separators for YAML, but then we have to apply a different solution for JSON--not ideal.

I'm happy to move on from this one if @nbaztec's approach and PR are accepted, otherwise I'm also game for working on a different solution. In the meantime I'll browse for another first contribution!

Side note: whatever the approach, is there any chance that users are depending on the output being in this format? Is that something to be considered in this?

**Comment by nbaztec** [comment]
Ideally we should strive to keep things as _non breaking_ as possible but that all depends in how the maintainers define this issue as - a bug or an enhancement. If a bug then the discussion leads to the following:
* Decide on how (or if) to handle json input files. JSON supports multiple resource concatenation:
```
{  "kind": "ConfigMap",   ... }
{  "kind": "ConfigMap",   ... }
```
So the resulting input is without any separator and so is the resulting output. As such it _feels_ consistent.

* Should we add an exception `---` only for `yaml` input when exists. YAML does not support multiple resource concatenation (it will always pick the last resource via key overrides), so requires document separators. `cat *.yaml | kubectl ...` doesn't work as intended for YAML configs due to the standard specification rules.
```
kind: ConfigMap
metadata:
  name: test2...
kind: ConfigMap
metadata:
  name: test2 ...
```
In the absence of the doc separator `kubectl` will only create the second resource. As such for inputs with doc separator:
```
kind: ConfigMap ...
---
kind: ConfigMap ...
``` 
it makes sense to have the output contain that as well. (?)

* However, when we come to other formats like `wide`, `name`, etc.
Currently wide format will give two sets of headers:
```
NAME      DATA      AGE
test1     1         0s
NAME      DATA      AGE
test2     1         0s
```
Again this output is enforcing the paradigm that these are separate unrelated operations - maybe implying that the YAML output should stay as-is too.

So the final decision would be to either:
1. Identify it as a bug *only* for YAML (doc-separated) inputs and append `----` on `apply / create / convert` outputs.
2. Migrate these multiple resource operations to a `List` result
3. Keep the behavior as-is citing *Intended Behavior* and maybe document it as such.

Thoughts?

**Comment by grantbow** [comment]
@nbaztec @evandigby and others, thanks for the good analysis and breaking out the different parts and different kubectl subcommands. From my outsider's perspective, perhaps further breaking apart the input and output could help.

As reported, this is about a proper YAML input **file** containing --- giving proper YAML output. The original request was for a list output, however if the --- is just saved and passed through that may be enough for compliant YAML without much code.

The broader case discussed is `cat *.yaml | kubectl`. Input file separation may be both more useful and more difficult but `(for x in *.yaml ; do cat $x ; echo --- ; done) | kubectl` might be OK for YAML after the above is implemented. A `List` result (breaking enhancement) or other things might be even more useful in the future but might be separate.

**Comment by davidhao3300** [comment]
Thanks for fixing!
