### ISSUE TITLE
OpenAPI custom columns don't work with `--watch` flag 

### ISSUE THREAD

**Issue by jhorwit2** [kubernetes/kubernetes#58931]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

I have custom columns defined via the openapi attribute for resources in my apiserver. They show up just fine when I run `kubectl get instances` but they do not show up when I run `kubectl get instances -w`

```
kubectl get instances -w
NAME                      AGE
generic-node-pool-kbsc4   51s
generic-node-pool-nf2l8   51s
generic-node-pool-rndrc   51s
```

**What you expected to happen**:

I expect the same columns that show up in `kubectl get` to show up when I watch. 

**How to reproduce it (as minimally and precisely as possible)**:

Create a custom resource that use the openapi custom columns, then watch for updates. 

/sig api-machinery
/sig cli
/area kubectl

**Comment by swapnilgm** [comment]
This issue persist till v.1.10.2, But the issue has been already fixed in master branch because of refactoring in https://github.com/kubernetes/kubernetes/commit/191a48f4c3cddbba5669b2f4412508c581305c38#diff-7650a51eb24776a0115b675dd3842d63. Although because of change in
https://github.com/kubernetes/kubernetes/pull/62584, by default openapi custom columns are not printed in output; one will have to pass flag `--use-openapi-print-columns=true` to `kubectl get`.
