### ISSUE TITLE
macvlan packets not access host iptables

### ISSUE THREAD

**Issue by sykpour** [kubernetes/kubernetes#59044]
if I make k8s network bridge mode，when I  set bridge-nf-call-iptables is 1, the packets of container can access host iptables;

However, if I make k8s network macvlan mode,  the packets of container  can not access host iptables. How I should config,  make packets of container access host iptables in macvlan mode

**Comment by oilbeater** [comment]
Meet same problem, macvlan seems transfer traffic directly to outside without passing through host network stack and iptables didn't take effect.

**Comment by xiaoxubeii** [comment]
Same problem. This makes cni macvlan weakness.

**Comment by sykpour** [comment]
can not solve it

**Comment by skrcup** [comment]
I got the same issue, container with macvlan interface inside, the host iptables rules without effect on traffic from container.

**Comment by danwinship** [comment]
Presumably you are talking about using the "macvlan" plugin from the CNI reference plugins? That is not part of kubernetes itself, that is part of a separate project, http://github.com/containernetworking/plugins/.

And the behavior your are describing is expected in that case: in the bridge case, traffic from the pod goes:

```
   pod net namespace   |                host net namespace                 |
                       |                                                   |
pod -> veth (inside) --|--> veth (outside) -> bridge -> iptables -> eth0 --|--> external network
                       |                                                   |
```
while in the macvlan case it goes
```
    pod netns    |
                 |
pod -> macvlan --|--> external network
                 |
```

iptables rules exist only in a particular network namespace, so the iptables rules in the host net namespace are irrelevant when using macvlan because the packet never passes through the host net namespace. (You could add iptables rules to the pod's net namespace, but you would have to do it for every pod individually.)

/close
