### ISSUE TITLE
admission webhooks: Test: kube-apiserver should start even if webhooks block every API action.

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#59124]
Please write a test that:

* Starts kube-apiserver
* Adds a webhook which blocks everything it is possible to block.
* Re-starts kube-apiserver
* Verifies that kube-apiserver comes back up
* Verifies that it can remove the broken webhook.

This would have caught #56761

**Comment by jennybuckley** [comment]
cc @jennybuckley

**Comment by ivange94** [comment]
Hi I'm new to kubernetes but eager to contribute. I think this will be a good first issue for me but I'll need some guide on how to proceed
I will need the first two points explained and also which file I'm supposed to be making my changes to.

**Comment by ivange94** [comment]
Hi I'm new to kubernetes but eager to contribute. I think this will be a good first issue for me but I'll need some guide on how to proceed
I will need the first two points explained and also which file I'm supposed to be making my changes to.

**Comment by sttts** [comment]
Here is a good example of how to start a realistic kube-apiserver in integration tests: https://github.com/kubernetes/kubernetes/blob/master/test/integration/master/kube_apiserver_test.go#L34.

**Comment by sttts** [comment]
"Verifies that it can remove the broken webhook." sounds dangerous. The apiserver should come up and it should be possible to remove a webhook via the API. But removing a potentially broken (or intentionally DoS'ed) webhook asks for security attacks.

**Comment by jennybuckley** [comment]
@sttts 
I assume that "Verifies that it can remove the broken webhook." is just to ensure that no webhook can be registered which could potentially deny its own (or another webhook's) deletion.

Broken webhooks definitely shouldn't be treated differently in terms of determining who can delete them, but validation should probably prevent webhooks from applying to webhooks, wildcard selectors should exclude webhooks, etc. Also, this behavior would need to be documented.

I think the safest way to ensure that a webhook does not get deleted is with RBAC rules, rather than using a validating webhook to prevent its deletion.

**Comment by sttts** [comment]
@jennybuckley I have the same understanding. Excluding webhooks from webhooks seems reasonable. But it's only one piece in the (restart when webhook broke) puzzle. We reconcile RBAC rules, create namespaces (or keep them when they exist already). So I expect some more exceptions.

**Comment by jennybuckley** [comment]
@ivange94 Is this still something you are working on?

**Comment by lavalamp** [comment]
If you can make a webhook which prevents the apiserver from starting at all, this is a problem, no matter what the webhook is verifying/doing, because you can't recover from that state.

I'm not suggesting that the system should automatically remove a broken webhook, which would be a security problem, rather that it needs to be possible for an appropriately authenticated sysadmin to do so.

Especially since making a broken webhook non-broken may require executing API calls that the broken webhook is preventing.

**Comment by sttts** [comment]
@jennybuckley as you assigned this to you, can you sketch what the plan is for this?

**Comment by jennybuckley** [comment]
@sttts The plan was to use an integration test, (i.e. https://github.com/kubernetes/kubernetes/blob/master/test/integration/master/kube_apiserver_test.go#L34) which I implemented in #60771 but it turns out that since the integration test apiserver does not follow exactly the same startup chain as the real one, that it is insufficient to ensure the apiserver can actually come up with a broken webhook installed. The integration test doesn't even fail against the code before #59073 merged.

So currently the plan is to do it as an e2e test, probably with the [Slow] and [Destructive] tags.

**Comment by sttts** [comment]
> integration test apiserver does not follow exactly the same startup chain as the real one

@jennybuckley it should be 99.9% the same. What are you missing?

I think an integration test would be much better than an e2e test. We have much more control there.

**Comment by jennybuckley** [comment]
@sttts I think the bug #59073 fixed was something a controller was doing, not the apiserver

**Comment by sttts** [comment]
@jennybuckley those bootstrap controller are also executed by the testserver. So I would expect that the bug could be hit in testserver integration tests too.

Compare https://github.com/sttts/kubernetes/blob/691a7d43588692501e27be2375bebad1c30b7ae5/cmd/kube-apiserver/app/server.go#L136 with the real start code and https://github.com/sttts/kubernetes/blob/cfdea234c3608123db26d86dc65a1bd517ba0287/cmd/kube-apiserver/app/testing/testserver.go#L107 for the test server start code. They are the same. The only difference is that we tweak the options beforehand a bit to run with a random port and random etcd prefix.

**Comment by jennybuckley** [comment]
@sttts 
Hmm, then I think the reason that the test doesn't fail pre-#59073 is because that post start hook isn't set up unless api-aggregation is being used. I guess the integration test for this will have to do that as well. Although the one in #60771 is still somewhat valuable to make sure new startup namespace creations in non aggregated apiservers are done correctly.

**Comment by wojtek-t** [comment]
@jennybuckley @sttts - you probably already thought about it, but one more thing to ensure here is that:

- apiserver can starte responding "OK" to "/healthz" even if all webhooks are broken
[that means e.g. finishing all post-startup hooks]

Without that, apiserver would be consistently being killed + restarted by Kubelet on which it is running (at least in some setups).

**Comment by lavalamp** [comment]
Yeah, the post-start hooks are the thing that inspired this issue :)
