### ISSUE TITLE
Strip unknown fields in custom resources

### ISSUE THREAD

**Issue by nikhita** [kubernetes/kubernetes#59151]
For native resources, if an unknown field is specified, it will be ignored and dropped.

Current behaviour of custom resources: all (valid) fields are accepted and persisted. This means that custom resources do not behave like native resources now.

This can be fixed by mentioning fields in the `properties` construct of the CRD validation schema. New fields which are not specified here will be stripped.

As discussed in the sig api-machinery meeting:

- We add this to beta but this will be off by default. We warn when objects will be stripped.

- For GA, flip default to on.

Note: `additionalProperties` will not be allowed to set to false and we will not allow it to be set a schema. It will always be set to true. See discussion in https://github.com/kubernetes/kubernetes/pull/58746.

/sig api-machinery
/area custom-resources
/kind feature
/assign

/cc @sttts @deads2k @liggitt @ash2k @mbohlool @lavalamp @jennybuckley @munnerz @colemickens @frankgreco

**Comment by nikhita** [comment]
PR for pruning fields: https://github.com/kubernetes/kubernetes/pull/63604

**Comment by lavalamp** [comment]
> For native resources, if an unknown field is specified, it will be ignored and dropped.

For clarity, this is a **bug report**, not a feature request. The sensible thing to do is to give a validation error.

...we can't just add that validation without (likely) breaking a bunch of user workflows that are currently sending invalid stuff.

But if we are fixing this problem for CRDs, please don't make it worse by just silently dropping fields; give the user a validation error instead.

**Comment by liggitt** [comment]
> The sensible thing to do is to give a validation error.

that depends on how the API evolves and what clients want. see discussion in https://github.com/kubernetes/kubernetes/pull/59972#issuecomment-367082497

> if we are fixing this problem for CRDs, please don't make it worse by just silently dropping fields; give the user a validation error instead.

that is inconsistent with how our other API resources work, and means adding a new API field makes new manifests fail against previous servers. as discussed in the above thread, getting validation failures on unknown fields should be an opt-in strict mode.

**Comment by lavalamp** [comment]
> adding a new API field makes new manifests fail against previous servers

OK this argument I buy, but: will CRD authors find themselves in this situation? Hm. I guess maybe.

**Comment by lavalamp** [comment]
I think we need micro versions, so apiserver can figure out if an unknown field is a mistake or might refer to a future version of the API.

**Comment by apelisse** [comment]
> that is inconsistent with how our other API resources work, and means adding a new API field makes new manifests fail against previous servers.

With the existing client-side validation, apply will reject an object that has unknown fields specified. We very deliberately made it that way specifically for the reasons @lavalamp is mentionning: we don't want to silently drop parts of the configuration. Of course that's only true for apply ...

**Comment by apelisse** [comment]
> For native resources, if an unknown field is specified, it will be ignored and dropped.

I don't think this is true for `kubectl apply`.

**Comment by lavalamp** [comment]
kubectl apply can still have this issue if it reads the discovery doc from a newer apiserver and sends the request to an older apiserver in the middle of an apiserver upgrade.

**Comment by lavalamp** [comment]
Further thoughts: no, I was right to begin with ;) apiservers that don't understand a field should reject it no matter what, even if it's correct but from a future version of the schema: they can't know that. Clients deserve to know they're talking to an old apiserver, and that new features won't work. The error message should be different, true ("not a valid field" vs "I don't speak that revision of the API"), but that's a nice-to-have.

Literally the ONLY people happy we're dropping the field on the floor are people with a bunch of old, broken manifests that they don't want to fix. And we don't know how many people there are like that, and we don't even know for sure they don't want to fix their broken manifests.

@liggitt @sttts thoughts?

**Comment by liggitt** [comment]
> apiservers that don't understand a field should reject it no matter what, even if it's correct but from a future version of the schema: they can't know that. Clients deserve to know they're talking to an old apiserver, and that new features won't work

As noted before, I think an opt-in strict mode is a good feature. Absent that, the current behavior is more compatible.

New fields are typically added to allow control over a previously implicit behavior, with a default value that matches the previously implicit behavior. Just taking our Pod type, there are several cases:
* `pod.spec.containers[*].terminationMessagePolicy` was added with a backwards-compatible default of `File`
* `pod.spec.schedulerName` was added with a backwards-compatible default of `default-scheduler`
* `pod.spec.volumes[*].hostPath.type` was added with a backwards-compatible default of `""` (meaning no type checking is done)

Pods with those fields set to those defaults are semantically equivalent to pods with those fields missing. A previous version of the API server defaulting to rejecting pods with those fields set to those default values is bad.

> Literally the ONLY people happy we're dropping the field on the floor are people with a bunch of old, broken manifests that they don't want to fix.

Not true. Case in point - in 1.11, we're dropping an alpha annotation for sysctls and adding a field for it (https://github.com/kubernetes/kubernetes/pull/63717). During this transition from 1.10 to 1.11, I'd definitely want the ability to have a manifest that specified both the annotation and the field so that my creating controller could seamlessly operate against either level of server.

**Comment by apelisse** [comment]
> New fields are typically added to allow control over a previously implicit behavior, with a default value that matches the previously implicit behavior. [...]

Right, as you say, that's backward compatible. An object written for 1.X will have the same behavior in 1.(X+1). It's very important. We should probably focus on that rather than forward compatibility.
My configuration from 1.X will certainly NOT have the same behavior in 1.(X-1) if some fields are silently dropped, and we don't know what the consequences might be (even more so for CRDs)

Now, I understand that you already know that :-)

> A previous version of the API server defaulting to rejecting pods with those fields set to those default values is bad.

How would the previous API server know that a future version of itself will default some fields to this value? I agree that it's bad, but I don't think it's nearly as bad as having random behavior because of dropped fields. I still believe that in most cases, people will want to know if their config suddenly has a different meaning.

> Not true. Case in point - in 1.11, we're dropping an alpha annotation for sysctls and adding a field for it (#63717). During this transition from 1.10 to 1.11, I'd definitely want the ability to have a manifest that specified both the annotation and the field so that my creating controller could seamlessly operate against either level of server.

Sounds like a good use-case for opt-out ;-)

**Comment by smarterclayton** [comment]
Our API guarantee is that we never add new fields that don't have a default.  So the forward compatibility case you describe 1.X lacking a field from 1.(X-1) is already an error.  Our existing pattern (consistency of API behavior over everything) is to silently drop that field at the API.  Our client behavior is to default to validate=true.  A client can absolutely perform stricter validation.  A server cannot without being internally inconsistent.

I would totally be in support of strict api validation being opt in on the API server and clients generally opt-ing in with an escape tach.  I am against it being out-out because that means different APIs behave differently.   I'm still not sure opt in on the CRD level makes sense, but I can rationalize it because CRDs are weak at other things.

**Comment by smarterclayton** [comment]
If we enforced strict at the API server level, we'd also have to wait to apply strict validation until after all API servers were upgrade, because otherwise we could store an object in etcd that a client couldn't update.  Or we'd have to drop those fields coming out of etcd (which we do today) until we knew all apiservers were updated.

**Comment by bgrant0607** [comment]
Optional server-side validation is #5889

Coordination of exposure of new features with cluster upgrades is #4855

**Comment by nikhita** [comment]
Defaulting and pruning feature issue on k/features: https://github.com/kubernetes/features/issues/575

**Comment by liggitt** [comment]
fixed in https://github.com/kubernetes/kubernetes/pull/77333

/close
