### ISSUE TITLE
What does the HandlePodUpdates actually do?

### ISSUE THREAD

**Issue by mjaow** [kubernetes/kubernetes#59320]
HandlePodUpdates seems not a in-place update of pod.What does it actually do?It's a rolling-update? Or it is in reponsibility of updating pod status?I was confused.

/sig node

**Comment by jhorwit2** [comment]
@mjaow We are trying to consolidate the channels to which questions for help/support
are posted so that we can improve our efficiency in responding. Please reach out in slack at #sig-node or one of their other contact method. You can find those [here](https://github.com/kubernetes/community/tree/master/sig-node#contact). 

/close
