### ISSUE TITLE
Deployment issue

### ISSUE THREAD

**Issue by dshamanthreddy** [kubernetes/kubernetes#59327]
~# kubectl create -f nginx-v1.yaml
error: could not read an encoded object from nginx-v1.yaml: API version "apps/v1" in "nginx-v1.yaml" isn't supported, only supports API versions ["v1"]
error: no objects passed to create

**Comment by dshamanthreddy** [comment]
cat nginx-deployment.yml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80

kubectl create -f nginx-deployment.yml
error: could not read an encoded object from nginx-deployment.yml: API version "apps/v1" in "nginx-deployment.yml" isn't supported, only supports API versions ["v1"]
error: no objects passed to create

**Comment by islinwb** [comment]
@dshamanthreddy  What's the Kubernetes version you were using? The `apps/v1` works for v1.9.x and later.

**Comment by dshamanthreddy** [comment]
@islinwb 
# kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2017-12-15T20:55:30Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}

# kubectl version
Client Version: version.Info{Major:"1", Minor:"0", GitVersion:"v1.0.4", GitCommit:"65d28d5fd12345592405714c81cd03b9c41d41d9", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean"}


Is this the right way or is there any command to get the version

**Comment by jhorwit2** [comment]
@dshamanthreddy you need to update kubectl. You're using version 1.0.

**Comment by dshamanthreddy** [comment]
It works, Thanks

**Comment by dshamanthreddy** [comment]
@jhorwit2 @islinwb  How can I get dashboard  on kubernetes.

**Comment by cblecker** [comment]
Please re-post your question to [Stack Overflow](http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases.

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans Stack Overflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search Stack Overflow for answers to similar questions, and also familiarize yourself with:

  * [user documentation](http://kubernetes.io/docs/)
  * [troubleshooting guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/)

Again, thanks for using Kubernetes.

The Kubernetes Team

---
/kind support
/close
