### ISSUE TITLE
BASIC authentication not generated on python client lib

### ISSUE THREAD

**Issue by charly37** [kubernetes/kubernetes#59387]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Probably not a bug...more like a removed feature

/kind feature

**What happened**:
BASIC auth not generated on client libraries

**What you expected to happen**:
I am reviewing a ticket on the Python kubernetes-client generated library. This issue is related to the lack of support of BASIC authentication on the python generated library and track here:  

https://github.com/kubernetes-client/python/issues/430 

After investigation I assume this is because the swagger file does not contain the BASIC security definition (as explained more in detail in the ticket).  

I have very limited on Kubernetes and I think this is done on purpose but the official doc still contains this method of authentication: 

"Kubernetes uses client certificates, bearer tokens, an authenticating proxy, or HTTP basic auth to authenticate...." (from https://kubernetes.io/docs/admin/authentication/).  

In addition, I also confirm that it is usable (after modifying the swagger file and generate again the python client library with a kubernetes cluster created on GKE). 

I try to find more info on why the BASIC auth could had been removed from the swagger file but did not find too much except the following issue: 

https://github.com/kubernetes/kubernetes/issues/10351 

I wonder if anybody know why the BASIC auth is not present on the swagger file (and thus not available on the generated client library) even if it seems supported and working?

**Comment by roycaihw** [comment]
Basic auth was removed from the openapi spec https://github.com/kubernetes/kubernetes/pull/34691#issuecomment-255258786 because swagger-codegen didn't work with multiple mechanisms using the same header key ("authorization") https://github.com/kubernetes/kubernetes/pull/34691#issuecomment-254577973, but username/password can still pass as the header key. Not sure if it's still true. I checked swagger-codegen's recent releases and didn't see related fix. cc @mehdy 

For client-python, you can use basic auth with [kube config loader](https://github.com/kubernetes-client/python-base/blob/11da619c9ef7b2e26fe162e5feeb72d5bedcc5c9/config/kube_config.py#L180). 

Note that we are also [discouraging the use of basic auth](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/api-machinery/csi-new-client-library-procedure.md#client-capabilities) and only use for testing. https://kubernetes.io/docs/admin/authentication#static-password-file mentioned "basic authentication is currently supported for convenience while we finish making the more secure modes described above easier to use".
