### ISSUE TITLE
[DevicePlugin] Support Unlimited Resources

### ISSUE THREAD

**Issue by RenaudWasTaken** [kubernetes/kubernetes#59380]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature
/sig node
/area hw-accelerators
/cc @vishh @jiayingz @vikaschoudhary16 @fabiand 

**What happened**:

@fabiand mentioned there are non limited resources, things like "capabilitites" of a host (i.e. /dev/kvm) which his important to consider during scheduling, but not really limited how often it can be consumed by pods.

Currently a hack would be to set the number of resources advertised by the device plugin to a very high mumber.

**What you expected to happen**:

one model could be to have the device plugin advertise labels on the node which could also be "triggers" for invoking the `Allocate` call.
Though the problem with this API is that we don't know on what container to invoke the Allocate call and are therefore forced to invoke it on every container.

Other models could be:
- Introduce "container" labels / annotations (which might be something we want to introduce later)
- Try and do that through the Resource Class API (though not sure how we could fit it there)

**Comment by iwankgb** [comment]
@RenaudWasTaken are you aware of this project: https://github.com/kubernetes-incubator/node-feature-discovery? It could suite your needs, I believe. Maybe it is tome to consider adding its features to main Kubernetes repository?
CC: @balajismaniam, @ConnorDoyle

**Comment by jiayingz** [comment]
cc @dchen1107 @yguo0905 

For the record, as we have discussed on slack, I think one way to support "unlimited resource" is to treat it as re-allocatable resource. I think the current inefficient part of doing this through DP is you need to advertise a extreme large number of devices and handcrafted some "device ids". If we can introduce a type of "re-allocatable" resources, a device plugin can advertise a single "device", and kubelet device manager can allocate the same resource to different containers requesting this resource. The allocatable quantity from kubelet to scheduler may still need to use some "extreme large value" trick, but it is out side device plugin concern. Also, for "re-allocatable" resources, it may still have some upper bound on how many containers it can support. Kubelet can learn this from device plugin and use it as the "extreme large value". As for the scope, I think most of the change should be local to kubelet devicemanager.

**Comment by fabiand** [comment]
@jiayingz could you please elaborate a little on how 're-allocateable' differs from 'shareable' for you?

**Comment by fabiand** [comment]
@iwankgb To me NFD is really valuable for certain cases - i.e. specific CPU flags, locality, … - but this approach (auto labeling of nodes) only works for resources which do not need any allocation to a pod or container, but are rather an inherent feature of the host which you can consume _without_ allocation.

This is why NFD does not work for i.e. `7dev/kvm` (which could be considered to be a capability), because `dev/kvm` requires allocation to a container.

**Comment by jiayingz** [comment]
To me, I usually use "shareable" to mean that a container can require partial device resource through container resource request API. E.g., if a nic has 10G bandwidth and we allow a container to request 5G of that bandwidth, the device is "shareable". On the other hand, "re-allocateable" to me means that a container still requests device access as a whole object. The container isolation and performance guarantees are totally handled by the resource itself and hidden from kubelet or scheduler. I think the resources that may potentially benefit from the "re-allocatable" device resource support are perhaps those that can be dynamically provisioned for a large number of containers on a node yet need to pass some container runtime config information to Kubelet .

**Comment by vishh** [comment]
If the end goal is to expose a file declaratively into containers with policy,I'd prefer using CSI plugins. 
I'm yet to be convinced infinite resources need to be supported in the API as a formal construct.

**Comment by vikaschoudhary16** [comment]
I think current API is sufficient to handle all the discussed use-cases of re-allocatable/unlimited/infinite resources.
For "Capabilities"(resources which are not consumed directly by containers but still to be considered by steering pods to the nodes), i think NFD is a good candidate to consider.

**Comment by resouer** [comment]
I would +1 for this feature request which already has valid use case. While the design/implementation still need discussion. One of my inputs is: users will want to specific the device path on the host.

**Comment by phoracek** [comment]
Do we need to open another Issue for shareable resources support? (I don't know much about Resource Manager, but I guess shareable resources should be taken into account while designing unlimited resources support.)

It would provide us more QoS support and it could directly benefit from Resource Classes. Maybe it would be even easier to first support shareable resources only since they, unlike unlimited resources, do not require changes in container spec API (with shareable, resource request could remain a key-value pair, with unlimited, there is no point keeping the value).

Unlimited resources would improve DP API for network device plugins where we currently need to request access to "unlimited" resources, e.g. connection to an overlay, as a "device". However, such connections are in fact limited by network interface bandwidth, so having shareable resources support would be great.

**Comment by jiayingz** [comment]
My feeling is there are a lot missing pieces today to support shareable device resources. How about we wait after the f2f rwmg meeting during which I think there will be a good amount discussions on this topic? At the time we may have better ideas on the road blockers to support shareable device resources.

**Comment by kad** [comment]
I think we should keep that item on our radar still. 

/remove-lifecycle rotten
