### ISSUE TITLE
Node status down -> pod status unknown k8s v.1.9.2 can't  terminating

### ISSUE THREAD

**Issue by JackyBeatles** [kubernetes/kubernetes#59467]
![image](https://user-images.githubusercontent.com/1269261/35904925-9824e096-0c17-11e8-98d7-d1f31dad074d.png)

![image](https://user-images.githubusercontent.com/1269261/35905241-eeee0eb0-0c18-11e8-8ac1-7eb46510275b.png)

**Comment by tombee** [comment]
I believe this is the expected behaviour, as per:
https://github.com/kubernetes/kubernetes/issues/43279
https://github.com/kubernetes/kubernetes/issues/51333

My understanding of this is that pods that are in this state need to be forcefully removed by an admin using:

```
kubectl delete pod <pod_name> --grace-period=0 --force
```

**Comment by dims** [comment]
/close

please reopen if necessary

**Comment by lsylvain** [comment]
As things stand now at release 1.9.2, even when using --grace-period=0 --force a pod in this state may not be deleted. The status may change to Terminated, but the web UI shows the status with a "moon" incon that displays the tooltip "This pod is in a pending state" and the status column displaysTerminated:ExitCode:$. But this is only the beginning of many potential other woes.

If the pod was part of a daemonset the pod cannot be replaced. And, BTW, the dameonset cannot be deleted because it refererences the terminated but pending pod. I hate cliche terms, but the term "zombie pod" someone used in another post out there almost seems appropriate here.

The only way I can at the moment I can see to resolve this is to clean up the etcd data. Since there are no etcd cleanup tools, that means the etcd data must be waxed, which really means the K8S cluster must be torn down and stood up again. That is obviously not very elegant and is disruptive, which in most production scenarios is not an acceptable alternative.
@lsylvain

**Comment by lsylvain** [comment]
/open

Please see above.
