### ISSUE TITLE
Kubernetes cluster is suddenly down

### ISSUE THREAD

**Issue by hpham04** [kubernetes/kubernetes#59462]
Yesterday, my kubernetes cluster is suddenly down
I tried to investigate as the follows but not sure what the reason was:
- Unable to access Kube Dashboard, it returns HTTP ERROR 502
- Unable to access deployed apps on cluster, it also returns 502 error
- Cannot use kubectl command, it shows the message: "Unable to connect to the server: x509: certificate has expired or is not yet valid"
With this error, I googled and got the article: https://medium.com/@AnushkaSandaru1/how-to-change-expired-certificates-in-kubernetes-cluster-5d3feb9d9838 
But I'm not sure if this is correct or not
Can you please help to advise
Thank you so much

Environment: 
Kubernetes 1.5
Kube-aws

**Comment by jhorwit2** [comment]
Please re-post your question to [Stack Overflow](http://stackoverflow.com/questions/tagged/kubernetes) or to [Slack](https://kubernetes.slack.com/)

We are trying to consolidate the channels to which questions for help/support
are posted so that we can improve our efficiency in responding to your requests,
and to make it easier for you to find answers to frequently asked questions and
how to address common use cases.

We regularly see messages posted in multiple forums, with the full response
thread only in one place or, worse, spread across multiple forums. Also, the
large volume of support issues on github is making it difficult for us to use
issues to identify real bugs.

Members of the Kubernetes community use Stack Overflow to field support
requests. Before posting a new question, please search Stack Overflow for answers 
to similar questions, and also familiarize yourself with:

  * [user documentation](http://kubernetes.io/docs/)
  * [troubleshooting guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/)

Again, thanks for using Kubernetes.

/close
