### ISSUE TITLE
Kube-proxy in IPVS mode flushes other IPVS configs not configured by it

### ISSUE THREAD

**Issue by GoelDeepak** [kubernetes/kubernetes#59507]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
Kube-proxy in IPVS mode periodically reconciles the IPVS configuration as part of which it takes out the configuration that might be configured by other application running on the system.

**What you expected to happen**:
Kube-proxy should only remove the configuration that it added to the IPVS table.

**How to reproduce it (as minimally and precisely as possible)**:
Assuming you have a Kubernetes cluster with kube-proxy in IPVS mode. The issue is easy to reproduce with ipvsadm tool:
```
1. Configure a dummy IPVS configuration only any node
       sudo ipvsadm -A -t 207.175.44.110:80 -s rr
       sudo ipvsadm -a -t 207.175.44.110:80 -r 192.168.10.1:80 -m
2. Check the IPVS configuration  (it might already be gone)
       sudo ipvsadm -L
```
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.9.1
- OS (e.g. from /etc/os-release):  CoreOS 1465.6.0

**Comment by GoelDeepak** [comment]
cc @pires

**Comment by pires** [comment]
`kube-proxy` is indeed (or was last time I checked) highly opinionated when it comes to IPVS rules management. I'm also curious to learn if this is or will be changing any time soon.

**Comment by rramkumar1** [comment]
cc @m1093782566

**Comment by m1093782566** [comment]
@pires 

Do you have any good idea of cleaning up out-of-dated IPVS rules?

**Comment by m1093782566** [comment]
@rramkumar1 The root cause is that we have no better way to determine what rules are created by us.

We created a `--cleanup-ipvs` flag when clean up all proxy rules.

**Comment by m1093782566** [comment]
@rramkumar1 

In each sync loop, we only know active service and can not get any information on legacy services from API Server.

**Comment by rramkumar1** [comment]
So for example, if kube-proxy restarted, we currently have no way of knowing what services we created and what were created by another process?

**Comment by m1093782566** [comment]
Probably yes, sadly. I have been seeking a way to identify IPVS service, but no interesting finding yet.

**Comment by GoelDeepak** [comment]
@m1093782566  Can we rely on subnet used to create IPVS service and flush only the entries belonging to that subnet?

**Comment by m1093782566** [comment]
Hi Deepak,

subnet can only be used to create/delete ClusterIP. We should consider nodeport IP, externaIPs and LoadBalancer IPs.

**Comment by GoelDeepak** [comment]
Another idea is to have a `--exclude-cidrs` flag that takes a list of cidrs to be excluded

**Comment by m1093782566** [comment]
a `--exclude-cidrs` flag sounds a no-bad idea, but it means kube-proxy will flush IPVS services one by one - currently we can flush it within a command.

**Comment by m1093782566** [comment]
@kubernetes/sig-network-misc

**Comment by m1093782566** [comment]
ping @murali-reddy for thoughts :)

**Comment by rramkumar1** [comment]
@m1093782566 Each service will at the very least have a k8s cluster IP right? Why don't we use that to track what services IPVS has created? That seems slightly better since the user will not have to set a flag.

**Comment by m1093782566** [comment]
@rramkumar1 

Make your idea work seems a lot of work. In each sync loop, Kube-proxy get service/endpoints states after applying changes - do you remember the PR #52528. So, we have no way to know "what service is deleted". 

Apart from Cluster IP, we also create IPVS services for NodeIP, external LB IP and Load Balancer ingress IP.

**Comment by GoelDeepak** [comment]
@m1093782566 What is our final take on this? Are we going with `--exclude-cidrs` approach?

**Comment by m1093782566** [comment]
probably Yes，if No better resolution. Sorry for delay because I am on vocation.

**Comment by murali-reddy** [comment]
@m1093782566 i suggest use of `Finalizers`. In general some of the controllers logic of figuring out diff and reconciliation is very convoluted and some times not possible like in this case.

If kube-proxy IPVS proxies always process the add/delete/updates to the service and endpoint, then it can be sure of what it can add/delete.

**Comment by m1093782566** [comment]
@murali-reddy 

>  i suggest use of Finalizers

I am not very clear about that, would you please explain a bit more?

**Comment by murali-reddy** [comment]
@m1093782566 

From the problem definition of this issue 

> Kube-proxy in IPVS mode periodically reconciles the IPVS configuration as part of which it takes out the configuration that might be configured by other application running on the system.

First why should there be a reconicilization. This is in order to cleanup any stale configuration (service and server) that are no longer added (apart from adding missing any service and server). Now how do you end up in a state configuration? Becuase the control loop in the kube-proxy does not necessarily process all the updates to service and endpoint deletetion. If kube-proxy miss processing an update it will end-up resulting in stale configuration. Kube-api server will send update to kube-proxy controller only one update when service or endpoint object is deleted. 

[Finalizers](https://kubernetes.io/docs/tasks/access-kubernetes-api/extend-api-custom-resource-definitions/#finalizers) provides a way in which a controller gets a chance to take a action on deleted object. 

What I am suggesting is design by which kube-proxy controller that is in control of processing service and endpoint updates and never endup in stale configuration.

**Comment by m1093782566** [comment]
Do you mean CRD? At least, your link provided is about CRD.

**Comment by murali-reddy** [comment]
> Do you mean CRD? At least, your link provided is about CRD.

Finalizers applies to both core and CRD objects. 

For a better perspective take a look at https://github.com/kubernetes/kubernetes/pull/54569

**Comment by rramkumar1** [comment]
@thockin any thoughts on the finalizer approach?

**Comment by thockin** [comment]
I think Finalizers is a very heavy hammer to hit this problem which, to be honest, doesn't affect that many people.  First, finalizers are designed for *a* controller, not a controller per-node.  So we'd need a kube-proxy centralizer, which waits for check-in from every kube-proxy.  That reduces to an already hard problem dealing with timeouts and assumed death of nodes.

If someone wants to prototype this, I encourage it, just as an exploration of how complicated this can get.  That's not to say it's not solvable, just that it is more work and complexity than this corner-case deserves.  We'd honestly do better trying to get the kernel and IPVS tools to adopt a convention of storing an "owner" string for each rule (similar to iptables chain names and comments)

A flag to exclude some CIDRs for IPVS is not horrible, since it's just not a common case.

A "checkpoint" of IPVS and ipset rules that have been written seems even cleaner.  Every sync loop, update it.  When you need to clean up, only clean up rules we know we wrote.  The design of this is a little subtle (e.g. you really want a 2-item journal because it is non-atomic wrt actual in-kernel configs), but it requires no user input.  Not sure the work required for this is justified vs. a flag.

**Comment by pires** [comment]
A flag does sound a lot easier and could be delivered in time for 1.11. The checkpoint can then be prototyped, designed and proposed properly. Thoughts?

**Comment by murali-reddy** [comment]
Agree. I totally missed the point of additional complexity of using Finalizers with controller per-node. Indeed its heavy hammer to hit this problem.

**Comment by m1093782566** [comment]
/assign @rramkumar1 

because he is interested in this task :)

**Comment by rramkumar1** [comment]
@m1093782566 @GoelDeepak @pires 
PR is ready for review.
