### ISSUE TITLE
Improve azure disk operations for vm and vmss

### ISSUE THREAD

**Issue by feiskyer** [kubernetes/kubernetes#59736]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

/kind cleanup

**What happened**:

VirtualMachineScaleSetVM and VirtualMachine are different data structures (because of different API versions), so the disk attach operation seems duplicate between vm and vmss. That means although disk operations are in same logic, some duplication are still required now.

They should use same api version in the future and should be merged into same code base, e.g. move sharing logic to azure_controller_common.go.

Refer https://github.com/kubernetes/kubernetes/pull/59716#issuecomment-364728621.

**What you expected to happen**:

vmss and vm disk operations should share same code logic.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by andyzhangx** [comment]
@khenidak 
I have checked with @feiskyer, currently we can’t merge, e.g. following two structs are different since they using different sdk-for-azure versions.
```
ManagedDisk: &compute.ManagedDiskParameters  #vmav version
ManagedDisk: &computepreview.ManagedDiskParameters  #vmss preview now
```

While in the end when sdk-for-azure version is upgraded, above two versions should be same and at that time,  we should merge functions like ‘AttachDisk’, ‘DetachDiskByName’, 'GetDiskLun', GetNextDiskLun, DisksAreAttached
