### ISSUE TITLE
[job failure] ci-kubernetes-e2e-kubeadm-gce

### ISSUE THREAD

**Issue by krzyzacy** [kubernetes/kubernetes#59762]
/priority failing-test
/kind bug
/status approved-for-milestone

@kubernetes/sig-cluster-lifecycle-test-failures

https://k8s-testgrid.appspot.com/sig-release-master-blocking#kubeadm-gce
the job is on the [master-blocking dashboard](https://k8s-testgrid.appspot.com/sig-release-master-blocking) and been failing to bring up the cluster.

cc @jdumars @luxas @jessicaochen

**Comment by xiangpengzhao** [comment]
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-gce/9579 shows:
```
I0212 20:21:34.308] Trying to fetch kubeconfig from master... 60/60
W0212 20:21:34.408] + for tries in '{1..60}'
W0212 20:21:34.409] + echo Trying to fetch kubeconfig from master... 60/60
W0212 20:21:34.409] + gcloud compute ssh --project k8s-jkns-gci-gce-reboot --zone us-central1-f prow@e2e-9579-master --command 'echo STARTFILE; sudo cat /etc/kubernetes/admin.conf'
W0212 20:21:35.328] cat: /etc/kubernetes/admin.conf: No such file or directory
W0212 20:21:35.393] + sleep 5
W0212 20:21:40.395] + echo Exhausted attempts to fetch kubeconfig.
W0212 20:21:40.395] Exhausted attempts to fetch kubeconfig.
W0212 20:21:40.395] + exit 1
W0212 20:21:40.395] make[1]: *** [do] Error 1
W0212 20:21:40.396] make: *** [deploy-cluster] Error 2
W0212 20:21:40.396] 2018/02/12 20:21:40 util.go:174: Step 'make -C /workspace/kubernetes-anywhere WAIT_FOR_KUBECONFIG=y deploy' finished in 7m35.644506508s
```

Haven't find more clues yet. Other kubeadm jobs fail due to the same reason:
https://k8s-testgrid.appspot.com/sig-release-master-blocking#kubeadm-gce-selfhosting
https://k8s-testgrid.appspot.com/sig-cluster-lifecycle-all#kubeadm-gce-cni-calico
https://k8s-testgrid.appspot.com/sig-cluster-lifecycle-all#kubeadm-gce-cni-flannel
https://k8s-testgrid.appspot.com/sig-cluster-lifecycle-all#kubeadm-gce-dns-coredns

**Comment by errordeveloper** [comment]
As discussed this in the SIG meeting yesterday, we'd like to get rid of kubernetes-anywhere. I'm tempted to start looking at it as part of this, but maybe someone has an idea of a quick fix or where to look? I don't know enough about test infra to try bisecting this or do anything like that.

**Comment by krzyzacy** [comment]
sounds like the kubeadm suites should not be in master-blocking dashboard anymore
cc @jdumars @spiffxp @jberkus

**Comment by jberkus** [comment]
That's up to SIG-cluster-lifecycle, not me.  I just track the issues, I don't decide what's blocking.  Same for @spiffxp.

**Comment by jdumars** [comment]
@lukemarsden @jbeda @roberthbailey @luxas can you PTAL?

**Comment by jessicaochen** [comment]
When I manually run, it looks like there is an issue installing the cni deb. Is this a known issue?
 
From my master VM logs:
```
Feb 15 23:23:42 ubuntu startupscript: + gsutil rsync gs://kubernetes-release-dev/bazel/v1.10.0-beta.0.54+c03edcc58eeaca/bin/linux/amd64/ /tmp/k8s-debs

Copying gs://kubernetes-release-dev/bazel/v1.10.0-beta.0.54+c03edcc58eeaca/bin/linux/amd64/kubernetes-cni.deb

Feb 15 23:24:22 ubuntu startupscript: Unpacking kubernetes-cni (0.5.1) ...
Feb 15 23:24:22 ubuntu startupscript: dpkg: error processing archive /tmp/k8s-debs/kubernetes-cni.deb (--install):
Feb 15 23:24:22 ubuntu startupscript:  error creating directory '/opt/cni/bin': No such file or directory
Feb 15 23:24:22 ubuntu startupscript: dpkg-deb (subprocess): decompressing archive member: pass-through copy error: failed to write (Broken pipe)
Feb 15 23:24:22 ubuntu startupscript: dpkg-deb: error: subprocess <decompress> returned error exit status 2
Feb 15 23:24:22 ubuntu startupscript: dpkg-deb (subprocess): cannot copy archive member from '/tmp/k8s-debs/kubernetes-cni.deb' to decompressor pipe: failed to write (Broken pipe)
Feb 15 23:24:22 ubuntu startupscript: dpkg: dependency problems prevent configuration of kubelet:
Feb 15 23:24:22 ubuntu startupscript:  kubelet depends on kubernetes-cni (>= 0.5.1); however:
Feb 15 23:24:22 ubuntu startupscript:   Package kubernetes-cni is not installed.

```

**Comment by cmluciano** [comment]
@danehans Does the problem that @jessicaochen mention match the problem that you mentioned on our SIG meeting last week?

cc @dixudx I think we updated this package recently to require a certain version constraint. Do you have any ideas here?

**Comment by danehans** [comment]
@cmluciano I think @leblancd may be the person that mentioned the problem. @leblancd can you please confirm?

**Comment by leblancd** [comment]
@cmluciano , @danehans , @jessicaochen , @mikedanese , @luxas
Yes!!! This is the exactly the issue that I referred to in this proposed (admittedly kludgy) workaround: https://github.com/kubernetes/kubernetes-anywhere/pull/514. I believe that this may have been introduced when we changed to CNI version 0.6.1, but that's just a guess.

I could be wildly wrong here, but I believe that the contents of the debs package for kubernetes-cni are wrong. Here's what the contents look like:
```
root@bxb-ds-58:~/temp/new_kube_debs# dpkg -c kubernetes-cni.deb 
tar: Removing leading `/' from member names
drwxr-xr-x root/root         0 2017-08-17 13:03 /opt/cni/bin/
-rwxr-xr-x root/root   2814104 2017-08-17 13:02 /opt/cni/bin/flannel
-rwxr-xr-x root/root   3877986 2017-08-17 13:03 /opt/cni/bin/ptp
-rwxr-xr-x root/root   2991965 2017-08-17 13:03 /opt/cni/bin/host-local
-rwxr-xr-x root/root   3470464 2017-08-17 13:02 /opt/cni/bin/portmap
-rwxr-xr-x root/root   2808402 2017-08-17 13:02 /opt/cni/bin/tuning
-rwxr-xr-x root/root   3475750 2017-08-17 13:03 /opt/cni/bin/vlan
-rwxr-xr-x root/root   2605279 2017-08-17 13:03 /opt/cni/bin/sample
-rwxr-xr-x root/root   9921982 2017-08-17 13:03 /opt/cni/bin/dhcp
-rwxr-xr-x root/root   3475802 2017-08-17 13:02 /opt/cni/bin/ipvlan
-rwxr-xr-x root/root   3520724 2017-08-17 13:02 /opt/cni/bin/macvlan
-rwxr-xr-x root/root   3026388 2017-08-17 13:02 /opt/cni/bin/loopback
-rwxr-xr-x root/root   3890407 2017-08-17 13:02 /opt/cni/bin/bridge
root@bxb-ds-58:~/temp/new_kube_debs#
```
What I believe is missing are the parent directories of /opt/cni/bin, i.e. it should look like:
```
root@bxb-ds-58:~/temp/new_kube_debs# dpkg -c kubernetes-cni.deb 
tar: Removing leading `/' from member names
drwxr-xr-x root/root         0 2017-08-17 13:03 /opt/
drwxr-xr-x root/root         0 2017-08-17 13:03 /opt/cni/
drwxr-xr-x root/root         0 2017-08-17 13:03 /opt/cni/bin/
-rwxr-xr-x root/root   2814104 2017-08-17 13:02 /opt/cni/bin/flannel
-rwxr-xr-x root/root   3877986 2017-08-17 13:03 /opt/cni/bin/ptp
-rwxr-xr-x root/root   2991965 2017-08-17 13:03 /opt/cni/bin/host-local
-rwxr-xr-x root/root   3470464 2017-08-17 13:02 /opt/cni/bin/portmap
-rwxr-xr-x root/root   2808402 2017-08-17 13:02 /opt/cni/bin/tuning
-rwxr-xr-x root/root   3475750 2017-08-17 13:03 /opt/cni/bin/vlan
-rwxr-xr-x root/root   2605279 2017-08-17 13:03 /opt/cni/bin/sample
-rwxr-xr-x root/root   9921982 2017-08-17 13:03 /opt/cni/bin/dhcp
-rwxr-xr-x root/root   3475802 2017-08-17 13:02 /opt/cni/bin/ipvlan
-rwxr-xr-x root/root   3520724 2017-08-17 13:02 /opt/cni/bin/macvlan
-rwxr-xr-x root/root   3026388 2017-08-17 13:02 /opt/cni/bin/loopback
-rwxr-xr-x root/root   3890407 2017-08-17 13:02 /opt/cni/bin/bridge
root@bxb-ds-58:~/temp/new_kube_debs#
```

When I manually add the parent directories to the debs package, I can then correctly install the package.

I haven't had time to figure out where the kubernetes-cni debs packages get built (kubernetes/kubernetes or kubernetes/release ???), or how the build could be broken. Anyone have suggestions on where to look?

**Comment by leblancd** [comment]
@cmluciano , @danehans , @jessicaochen , @mikedanese , @luxas
I'm convinced that all of these kubeadm related CI tests are failing because of the way that the kubernetes-cni.deb package is being created by Bazel, that is, because this package is being created without the /opt and /opt/cni parent directory entries as I described earlier. To summarize, the failure sequence for these CI tests is:
- Startup script tries to install kubernetes-cni, kubelet, and kubeadm from deb packages
- Install of kubernetes-cni fails because /opt/cni/bin can't be created by dpkg (missing /opt and /opt/cni).
- Install of kubelet fails because it depends on kubernetes-cni, and is later removed.
- Install of kubeadm fails because it depends on kubelet, and is later removed.
- Because kubeadm is missing, 'kubeadm init ...' can't be run, cluster never comes up.

I believe that the creation of kubernetes-cni.deb package is failing to include the parent directories because of a quirk in Bazel pkg_tar() functionality (and/or because of the way that the CNI release packages are built). Here's part of the recipe for kubernetes-cni.deb in build/debs/BUILD:
```
 pkg_tar(
     name = "kubernetes-cni-data",
     package_dir = "/opt/cni/bin",
     deps = ["@kubernetes_cni//file"],
 )
```
Here, the 'deps' entry indicates that the CNI release package tarball should be unpacked and included into the kubernetes-cni.deb package (https://docs.bazel.build/versions/master/be/pkg.html#pkg_tar).
If we look at the contents of the CNI release tarball:
```
openstack@bxb-ds-58:~/Downloads$ tar -tf cni-plugins-amd64-v0.6.0.tgz 
./
./flannel
./ptp
./host-local
./portmap
./tuning
./vlan
./sample
./dhcp
./ipvlan
./macvlan
./loopback
./bridge
openstack@bxb-ds-58:~/Downloads$ 
```
we see that the files are referenced w.r.t. "./" (CNI isn't opinionated as to where you install these binaries, so paths are all relative).

Here's the problem: It seems that for "deps" entries in Bazel's pkg_tar(), Bazel seems to assume that the tarball that it's unpacking contains all of the parent directories (i.e. it expects to work with tarballs with absolute paths). So in this particular case, it doesn't look at the package_dir definition:
```
     package_dir = "/opt/cni/bin",
```
and automatically create the parent directories needed in kubernetes-cni.deb, as we would hope:
```
drwxr-xr-x root/root         0 2017-08-17 13:03 /opt/
drwxr-xr-x root/root         0 2017-08-17 13:03 /opt/cni/
```
Note that pkg_tar() DOES do this automatic addition of parent directories if there is a "srcs" or a "files" config. So for example, as an experiment, if we modify the pkg_tar() entry for kubernetes-cni.deb to include the /build/debs/BUILD file in the deb package:
```
 pkg_tar(
    name = "kubernetes-cni-data",
    package_dir = "/opt/cni/bin",
    deps = ["@kubernetes_cni//file"],
    srcs = ["BUILD"],
 )
```
then the /opt and /opt/cni parent directories WILL get automatically added to kubernetes-cni.deb.

I don't think we want to force the CNI plugin release tarball to use an absolute path of /opt/cni/bin, since that's not the location that other CNI plugin users install their binaries.

Is there some existing pkg_tar() configuration that can trigger Bazel to include the parent directories?
Or is this behavior something we can change in pkg_tar()?

**Comment by leblancd** [comment]
@cmluciano , @jessicaochen , @mikedanese , @luxas
Unless anyone has any better ideas... I opened an bazelbuild/bazel issue to enhance bazel to add the descending parent directories ("/opt" and "/opt/cni" in this case): [bazelbuild/bazel issue #4651](https://github.com/bazelbuild/bazel/issues/4651)
In the meantime, would it make sense to get the kubernetes-anywhere workaround [kubernetes-anywhere issue #514](https://github.com/kubernetes/kubernetes-anywhere/pull/514) merged as a temporary measure so that we can get the kubeadm CI tests unblocked? I've added a TODO comment to this PR saying that the mkdir workaround should be removed when the [bazelbuild/bazel issue #4651](https://github.com/bazelbuild/bazel/issues/4651) gets resolved.
(Note: If/when the [kubernetes-anywhere issue #514](https://github.com/kubernetes/kubernetes-anywhere/pull/514) workaround gets merged, we would also have to modify the version of kubernetes-anywhere that gets checked out in test-infra/images/kubeadm/runner, so that the workaround change gets included in CI test runs.)

**Comment by leblancd** [comment]
@cmluciano , @jessicaochen , @luxas, @krzyzacy , @errordeveloper 
Looks like the [kubernetes-anywhere PR # 514 workaround](https://github.com/kubernetes/kubernetes-anywhere/pull/514) eliminated one problem: [pull-kubernetes-e2e-kubeadm-gce jobs are unblocked](https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-e2e-kubeadm-gce/).

However, for ci-kubernetes-e2e-kubeadm-gce jobs (and some other kubeadm jobs), there's (at least) an additional problem. For example, if you look at these [recent test logs](https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-gce/9615/artifacts/e2e-9615-master/serial-1.log), it looks like the test is trying to pull packages from a non-existent bucket:
```
Feb 21 20:53:05 e2e-9615-master startup-script: INFO startup-script: + TMPDIR=/tmp/k8s-debs
Feb 21 20:53:05 e2e-9615-master startup-script: INFO startup-script: + mkdir /tmp/k8s-debs
Feb 21 20:53:05 e2e-9615-master startup-script: INFO startup-script: + gsutil rsync gs://kubernetes-release-dev/bazel/v1.11.0-alpha.0.243+7a50f4a12fc158/bin/linux/amd64/ /tmp/k8s-debs
```
This bucket doesn't seem to exist:
https://console.cloud.google.com/storage/browser/kubernetes-release-dev/bazel?prefix=v1.11.0-alpha.0.2

So later, when dpkg -i is called, it doesn't find any .deb packages in the local /tmp/k8s-debs directory:
```
Feb 21 20:53:07 e2e-9615-master startup-script: INFO startup-script: Building synchronization state...
Feb 21 20:53:08 e2e-9615-master startup-script: INFO startup-script: Starting synchronization
Feb 21 20:53:08 e2e-9615-master startup-script: INFO startup-script: + mkdir -p /opt/cni/bin
Feb 21 20:53:08 e2e-9615-master startup-script: INFO startup-script: + dpkg -i /tmp/k8s-debs/kubelet.deb /tmp/k8s-debs/kubeadm.deb /tmp/k8s-debs/kubectl.deb /tmp/k8s-debs/kubernetes-cni.deb
Feb 21 20:53:08 e2e-9615-master startup-script: INFO startup-script: dpkg: error processing archive /tmp/k8s-debs/kubelet.deb (--install):
Feb 21 20:53:08 e2e-9615-master startup-script: INFO startup-script:  cannot access archive: No such file or directory
Feb 21 20:53:08 e2e-9615-master startup-script: INFO startup-script: dpkg: error processing archive /tmp/k8s-debs/kubeadm.deb (--install):
Feb 21 20:53:08 e2e-9615-master startup-script: INFO startup-script:  cannot access archive: No such file or directory
Feb 21 20:53:08 e2e-9615-master startup-script: INFO startup-script: dpkg: error processing archive /tmp/k8s-debs/kubectl.deb (--install):
Feb 21 20:53:08 e2e-9615-master startup-script: INFO startup-script:  cannot access archive: No such file or directory
Feb 21 20:53:08 e2e-9615-master startup-script: INFO startup-script: dpkg: error processing archive /tmp/k8s-debs/kubernetes-cni.deb (--install):
Feb 21 20:53:08 e2e-9615-master startup-script: INFO startup-script:  cannot access archive: No such file or directory
```
Does this ring a bell?
Could the CI test job GCS bucket pointers be out of sync with the buckets where bazel build places built packages?
Is it possible the associated bazel build job failed?

**Comment by dixudx** [comment]
> Feb 15 23:24:20 ubuntu startupscript: + dpkg -i /tmp/k8s-debs/kubelet.deb /tmp/k8s-debs/kubeadm.deb /tmp/k8s-debs/kubectl.deb /tmp/k8s-debs/kubernetes-cni.deb

Feb 15 23:24:22 ubuntu startupscript: Unpacking kubernetes-cni (0.5.1) ...
Feb 15 23:24:22 ubuntu startupscript: dpkg: error processing archive /tmp/k8s-debs/kubernetes-cni.deb (--install):
Feb 15 23:24:22 ubuntu startupscript:  error creating directory '/opt/cni/bin': No such file or directory
Feb 15 23:24:22 ubuntu startupscript: dpkg-deb (subprocess): decompressing archive member: pass-through copy error: failed to write (Broken pipe)
Feb 15 23:24:22 ubuntu startupscript: dpkg-deb: error: subprocess <decompress> returned error exit status 2
Feb 15 23:24:22 ubuntu startupscript: dpkg-deb (subprocess): cannot copy archive member from '/tmp/k8s-debs/kubernetes-cni.deb' to decompressor pipe: failed to write (Broken pipe)
Feb 15 23:24:22 ubuntu startupscript: dpkg: dependency problems prevent configuration of kubelet:
Feb 15 23:24:22 ubuntu startupscript:  kubelet depends on kubernetes-cni (>= 0.5.1); however:
Feb 15 23:24:22 ubuntu startupscript:   Package kubernetes-cni is not installed.

@cmluciano @jessicaochen @danehans  This is a known issue #57334. Fixes has already been created kubernetes/release#489.

**Comment by leblancd** [comment]
@dixudx - Thanks for bringing this up... I think there may be multiple problems here. As I pointed out in [test-infra issue # 6978](https://github.com/kubernetes/test-infra/issues/6978), the test job seems to be pulling build results from the wrong GCS bucket.
Your log snippet also shows that the CNI version that's getting unpacked is incorrect:
```
Feb 15 23:24:22 ubuntu startupscript: Unpacking kubernetes-cni (0.5.1) ...
```
The CNI version should be 0.6.0 for Kubernetes version >= 1.9.

**Comment by dixudx** [comment]
> The CNI version should be 0.6.0 for Kubernetes version >= 1.9.

Correct. Also version `0.5.1` is not accurate, which should be `0.5.1-00` instead.

**Comment by krzyzacy** [comment]
hola - looks like https://k8s-testgrid.appspot.com/sig-release-master-blocking#kubeadm-gce starts to fail between 2/24 - 2/25

diff https://github.com/kubernetes/kubernetes/compare/9714b6476...049b76201

anyone aware of what change slipped in?

**Comment by krzyzacy** [comment]
cc @BenTheElder @cjwagner ^^

**Comment by BenTheElder** [comment]
Yep, I am working on this a bit today, there's some discussion in test-infra

**Comment by krzyzacy** [comment]
priority/critical-urgent
/assign @BenTheElder

**Comment by BenTheElder** [comment]
We publish `ci/latest-bazel(-1.X)?` tags now, and I've switched `ci-kubernetes-e2e-kubeadm-gce` to pull from these which should avoid serialization issues, but this job still fails to get a kubeconfig. I'm not sure what's wrong currently.

**Comment by jessicaochen** [comment]
@BenTheElder - I was just looking at the latest failures and it is trying to pull kubelet binaries from the following location: gs://kubernetes-release-dev/bazel/v1.11.0-alpha.0.1028+e2dee6073933c9-bazel/

Are the binaries for things like kubelets for this new bazel build located in gs://kubernetes-release-dev/bazel/... or gs://kubernetes-release-dev/ci ? If the prior, we will need to update either whatever generates the binaries or the kubetest logic to match the new binary location.

**Comment by BenTheElder** [comment]
I found this bug last night, that location is wrong, there's now a kubeadm bug in kubernetes_e2e.py, I have a patch in progress, for some reason that script computes the shared path locations even in CI.

**Comment by jessicaochen** [comment]
xref: https://github.com/kubernetes/test-infra/pull/7139

**Comment by BenTheElder** [comment]
> As discussed this in the SIG meeting yesterday, we'd like to get rid of kubernetes-anywhere. I'm tempted to start looking at it as part of this, but maybe someone has an idea of a quick fix or where to look? I don't know enough about test infra to try bisecting this or do anything like that.

@errordeveloper Getting rid of it in favor of what? I know a thing or two about test-infra and I'd be happy to commit some time to help.

**Comment by BenTheElder** [comment]
We've got more progress on this, I think I've managed to configure a working run again. Once it goes green I'll PR kubeadm jobs

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-gce/9702/

**Comment by BenTheElder** [comment]
I think this is sorted [waiting for this run](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-gce/9704/) to be green after the fix, I'll keep an eye out though.

**Comment by BenTheElder** [comment]
I think we can close this now.
