### ISSUE TITLE
v1.10 known issues / FAQ accumulator 

### ISSUE THREAD

**Issue by krzyzacy** [kubernetes/kubernetes#59764]
Please link to this issue or comment on this issue with known errata for the 1.10.x release. This follows what we have done for prior releases.

We will be populating the "Known Issues" section of 1.10.0 and above release notes based on this issue

cc @jdumars @calebamiles @jberkus
cc @kubernetes/kubernetes-release-managers

**Comment by jdumars** [comment]
Is this part of the release process documented somewhere?

**Comment by krzyzacy** [comment]
cc @spiffxp 
I was referencing https://github.com/kubernetes/kubernetes/issues/53004 and made one for 1.10

**Comment by jberkus** [comment]
There's two CRI changes which break backwards compatibility for some users:

https://github.com/kubernetes/kubernetes/pull/59475

https://github.com/kubernetes/kubernetes/pull/58973

**Comment by jberkus** [comment]
adding kind

/kind design

**Comment by jberkus** [comment]
Adjusting labels to keep this tracker in the milestone.

/kind cleanup
/remove-kind design
/priority critical-urgent
/remove-priority important-soon

**Comment by krzyzacy** [comment]
(seems this issue is not as useful and not documented as part of release process, I'll just close it, but feel free to reopen if necessary)

**Comment by jberkus** [comment]
https://github.com/kubernetes/kubernetes/issues/60764
Known issue, downgrade extra steps with PVC

**Comment by Bradamant3** [comment]
Clarification, please? Do y'all want a relnote for https://github.com/kubernetes/kubernetes/issues/60933?

**Comment by Bradamant3** [comment]
Add https://github.com/kubernetes/kubernetes/issues/60764 plus related doc https://github.com/kubernetes/website/pull/7731

**Comment by jberkus** [comment]
Mount propagation manual steps: https://github.com/kubernetes/kubernetes/pull/61126

**Comment by jberkus** [comment]
>  Clarification, please? Do y'all want a relnote for #60933?

My opinion: yes.

**Comment by jdumars** [comment]
ACK.  In progress
ETA: 29/03/2018
Risks: The bot nagging will drive us slowly mad

**Comment by jberkus** [comment]
From release burndown as of March 19:

[Flaky timeouts while waiting for RC pods to be running in density test](https://github.com/kubernetes/kubernetes/issues/61189)
[Controller-manager sees higher mem-usage when load test runs before density](https://github.com/kubernetes/kubernetes/issues/61041)
[HostPath mounts failing with "Path is not a shared or slave mount"](https://github.com/kubernetes/kubernetes/issues/61058)
[kubeadm: etcd certs missing in self-hosted deploy](https://github.com/kubernetes/kubernetes/issues/61322) (will be fixed in point release)

**Comment by Bradamant3** [comment]
@nickchase in case it's helpful here: think you don't need to worry about #61126 bc the relnote content is in the PR (such as it is ...). BUT it might not be in the right place in the generated relnotes. It's an action required thing.

**Comment by jberkus** [comment]
We need to doc downgrading and PVC protection.  TL;DR: if you have PVCs, and need to downgrade, you need to downgrade to 1.9.6, which will be released next Wednesday, and not to an earlier version of 1.9.

**Comment by Bradamant3** [comment]
Yup. @nickchase see also comment from liggitt in https://github.com/kubernetes/website/pull/7731

**Comment by Bradamant3** [comment]
https://github.com/kubernetes/kubernetes/issues/61446 
https://github.com/kubernetes/kubernetes/issues/61456

@nickchase let's coordinate with @msau42 about relnotes/docs. Slack discussion also.

**Comment by msau42** [comment]
We also need to add those 2 known issues to 1.9, 1.8, 1.7 patch releases as well.

**Comment by msau42** [comment]
The workaround for #61446 and #61456 is to not use subPath with hostPath volumes, and instead just specify the whole path in the hostPath volume.

**Comment by nickchase** [comment]
Adding:

* Use of subPath module with hostPath volumes can cause issues during reconstruction ([#61446](https://github.com/kubernetes/kubernetes/issues/61446)) and with containerized kubelets ([#61456](https://github.com/kubernetes/kubernetes/issues/61456)). The workaround for this issue is to specify the complete path in the hostPath volume.

**Comment by nickchase** [comment]
Flaky timeouts while waiting for RC pods to be running in density test -- Appears to be fixed?
Controller-manager sees higher mem-usage when load test runs before density -- Does this need a Relnote?
HostPath mounts failing with "Path is not a shared or slave mount" -- Resolved with addition to "Before Upgrading" section
kubeadm: etcd certs missing in self-hosted deploy (will be fixed in point release) -- Added

**Comment by nickchase** [comment]
Added * In large clusters (~2K nodes) scheduling logs can explode and crash the master node. ([#60933](https://github.com/kubernetes/kubernetes/issues/60933))

**Comment by jberkus** [comment]
@nickchase 

Yes on Controller-manager. Suggested text:

"Some users, especially those with very large clusters, may see higher memory usage by the kube-controller-manager in 1.10."
