### ISSUE TITLE
[e2e test failure] each node by dropping all outbound packets for a while and ensure they function afterwards

### ISSUE THREAD

**Issue by krzyzacy** [kubernetes/kubernetes#59889]
http://k8s-testgrid.appspot.com/sig-release-master-blocking#gci-gce-reboot

/priority failing-test
/kind bug
/status approved-for-milestone
/sig cluster-lifecycle

the job is on the master-blocking dashboard and the e2e test has been failing, please take a look

cc @jdumars @jberkus @luxas @roberthbailey @kubernetes/sig-cluster-lifecycle-bugs

**Comment by krzyzacy** [comment]
testgrid change suggests https://github.com/kubernetes/kubernetes/compare/6590ea6d5...7b678dc40

**Comment by roberthbailey** [comment]
@JulienBalestra (author of the change in that range) -- any idea whether https://github.com/kubernetes/kubernetes/pull/57106 might have broken reboot tests?

**Comment by JulienBalestra** [comment]
I reverted the change as it may lead to this regression.

The other change is really small ([see](https://github.com/kubernetes/kubernetes/pull/57106/files#diff-c74869ee030004ef061f0e2b6573491cR144)) and unlikely related to this.

Still the [test grid](https://k8s-testgrid.appspot.com/google-gce#gci-gce-reboot) continues to say otherwise, I think we can reopen this issue.

**Comment by Random-Liu** [comment]
The reboot test is still failing.

**Comment by JulienBalestra** [comment]
Just opened #59948 to achieve the revert.

**Comment by jberkus** [comment]
Is the test passing now?  Can this issue be closed?

**Comment by krzyzacy** [comment]
looks green now
