### ISSUE TITLE
[test failure] verify.openapi-spec

### ISSUE THREAD

**Issue by krzyzacy** [kubernetes/kubernetes#59895]
@calebamiles looks like you've merged https://github.com/kubernetes/kubernetes/commit/c007efcceb0516e8ba2e4ecb8715c01bd07e98e2 into master branch? That seems have broken http://k8s-testgrid.appspot.com/google-unit#verify-master and http://k8s-testgrid.appspot.com/presubmits-kubernetes-blocking#pull-kubernetes-verify

can you take a look?

/priority failing-test
/assign @calebamiles

**Comment by krzyzacy** [comment]
/sig release
cc @jiayingz

**Comment by cblecker** [comment]
This looks to have been resolved, but root cause unknown:
failed: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-verify-master/18553
passed: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-verify-master/18554
same repo commit, different infra commit

**Comment by krzyzacy** [comment]
I'll leave @calebamiles to close this? I'm not sure the root cause yet, but if that manual merged commit is related, we should probably avoid it in the future.

**Comment by calebamiles** [comment]
@krzyzacy, I believe that commit was made "automagically" by anago while I was attempting to cut the 1.10 branch. @david-mcmahon noticed other problems and has magically cleaned up after the tool. Will follow up with him and you tomorrow.

**Comment by david-mcmahon** [comment]
Root cause was two tags landing on the same commit due to [this recent change](https://github.com/kubernetes/release/pull/507).  Solution was to temporarily remove the -beta tag from that commit so it doesn't interfere with the -alpha tag.  master branch is now fine.  Still need to tag the branch, but the question is, how given we don't make a change to the branch at branch time.   When it gets worked out will update this issue.

**Comment by jberkus** [comment]
adding priority, move to critical if it is

/priority important-soon

**Comment by jberkus** [comment]
adding kind as well, sorry I missed that.

/kind bug

**Comment by jberkus** [comment]
now critical, since we're in Code Freeze.

/priority critical-urgent
/remove-priority important-soon

**Comment by krzyzacy** [comment]
the test is fixed, we can move discussion to https://github.com/kubernetes/sig-release/issues/85
