### ISSUE TITLE
Priority admission controller should support enforcing and applying priority classes to pods by namespace

### ISSUE THREAD

**Issue by jhorwit2** [kubernetes/kubernetes#60018]
/kind feature
/sig scheduling
/sig api-machinery

As a cluster admin I'd like the ability to enforce that specific priority classes are only used in specific namespaces. I'd also like the ability to apply specific priority classes to namespaces by default. This helps ensure that lower priority namespaces, like dev and test, cannot use priority classes that make it equal to or more important than production namespaces. This also helps ensure that production namespaces automatically have a higher priority than dev/test. 

The idea for this comes from the [PodTolerationRestriction](https://kubernetes.io/docs/admin/admission-controllers/#podtolerationrestriction) and [PodNodeSelector](https://kubernetes.io/docs/admin/admission-controllers/#podnodeselector) admission controllers which provide the cluster admin the ability to enforce specific rules by namespace. 

I propose we add support for two new annotations on namespaces to cover restricting access to the priority classes and applying defaults per namespace.

```
scheduler.alpha.kubernetes.io/defaultPriorityClass 
```

and 

```
scheduler.alpha.kubernetes.io/priorityClassWhitelist
```

**Comment by derekwaynecarr** [comment]
I am in favor of this.   We have the same concerns.

**Comment by derekwaynecarr** [comment]
In OpenShift, we have a project request template that lets us manage creation of namespaces and default them with these type of controls.  Having a whitelist like this would be a big help for our flows.

**Comment by lavalamp** [comment]
Why did this get labeled sig api-machinery? Are existing extension points not sufficient?

(This should not imply I endorse using an annotation like this :) ) 

cc @cheftako

**Comment by jhorwit2** [comment]
> Why did this get labeled sig api-machinery?

@lavalamp according to the community page api-machinery owns admission controllers which is why i added the label. 

> Are existing extension points not sufficient?

Are you referring to webhook admission controllers?

**Comment by bsalamat** [comment]
Annotations are not meant to configure clusters. In order to have default priority class for a namespace, I would add a new field to the namespace object to specify the default prioirty class. And, whitelisting priority classes per namespace should be done via resource quota. We are already working on adding [priority class to resource quota](https://github.com/kubernetes/kubernetes/issues/48648). I think we should not create multiple parallel features that serve the same purpose.

**Comment by ravisantoshgudimetla** [comment]
> In order to have default priority class for a namespace, I would add a new field to the namespace object to specify the default prioirty class

You mean, while creating namespace, we specify the priorityClass? But how would we ensure that pods created in this namespace will have that priorityClass by default, shouldn't that be taken care of priority admission controller?


>  I think we should not create multiple parallel features that serve the same purpose.

 I think, the problem here is we already have chosen approach of admission controller for tolerations but while using quota to control priority(we wanted to limit the usage of resources at priority level) in namespace we got this whitelisting as a side-effect. AFAIU, we could have used quota on tolerations etc but we did not, so this may not be much of divergence. (AFAIU, at a high level, we can use the current approach of using scopes(LimitedResource struct) to whitelisting of any object but not sure if it is makes sense.)

**Comment by vikaschoudhary16** [comment]
> But how would we ensure that pods created in this namespace will have that priorityClass by default, shouldn't that be taken care of priority admission controller?

I think priority admission controller will need this field in namespace object to take care this.

**Comment by vikaschoudhary16** [comment]
Extending quota approach to access control tolerations make sense to me because of the two primary reasons:
1. Practical use case exist
2. On analogy based comparison, tolerations allow allow access to tainted nodes in a way similar to how priority classes allow operations in a namespace.

**Comment by ravisantoshgudimetla** [comment]
Update: Discussion on how to implement this feature has been going on here. https://docs.google.com/document/d/1HjAE8Aky3ebyHcbxIMkwaITBcz9j5-cCA21wBuUWoyA/edit?ts=5a9c92b0.

**Comment by bsalamat** [comment]
Should this be closed as #61185 is now our plan to deliver a super set of features including the feature requested in this issue?

**Comment by jhorwit2** [comment]
@bsalamat does that cover both defaults and whitelisting?

**Comment by bsalamat** [comment]
Yes, the pod scheduling policy is supposed to cover defaulting, whitelisting, blacklisting, and requiring certain pod scheduling properties, including priority.

**Comment by ravisantoshgudimetla** [comment]
> Should this be closed as #61185 is now our plan to deliver a super set of features including the feature requested in this issue? 

@bsalamat I am fine with closing this issue. The only concern I have is if the policy implementation takes more than a release(>1.12 or for graduating to beta), what should we have in interim?

**Comment by bsalamat** [comment]
@ravisantoshgudimetla Unfortunately, we cannot introduce temporary API changes. Users rely on such features and won't be able to upgrade easily when we drop them. Besides it doesn't make sense to split our efforts on two parallel efforts.

**Comment by ravisantoshgudimetla** [comment]
@bsalamat Thanks, I share your concerns but was curious if there is a better alternative to carrying a patch in OpenShift.

@jhorwit2 - To be clear even now, with quota for priorityClasses, we can achieve whitelisting but defaulting a priorityClass is a missing piece even now(until policy lands in).
