### ISSUE TITLE
Garbage collector in controller manager stops working

### ISSUE THREAD

**Issue by mcginne** [kubernetes/kubernetes#60037]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
I am running etcd-operator in kubernetes, and noticed that when I deleted the etcdcluster (Custom resource definition) the pods & services did not get cleaned up. I looked on another kube environment I had running, and on that env everything worked as expected. I checked logs, and could see on the env that was working I saw the following messages in Controller manager logs:
```
I0215 08:59:06.659783       1 garbagecollector.go:371] processing item [v1/Pod, namespace: etcd-operator, name: example-etcd-cluster-thcr8pfv89, uid: c9cdb6d7-122d-11e8-b4ac-068cfe9de373]
I0215 08:59:06.659871       1 garbagecollector.go:371] processing item [v1/Service, namespace: etcd-operator, name: example-etcd-cluster-client, uid: c9d238bc-122d-11e8-b4ac-068cfe9de373]
```
I didn't see these in the env that wasn't working, so I started looking at the garbage collector on there.

I noticed that there hadn't been any log message from garbage collecor since 31st Jan, when this was logged:
```
I0131 10:14:31.617880       1 controller_utils.go:1041] Waiting for caches to sync for garbage collector controller
```
Around this time we experienced some environmental network issues, which caused lots of errors around that time, such as:
```
E0131 10:13:31.691887       1 cronjob_controller.go:113] can't list Jobs: the server was unable to return a response in the time allotted, but may still be processing the request (get jobs.batch)
E0131 10:13:58.322978       1 node_controller.go:1022] Error updating node 10.143.115.218: the server was unable to return a response in the time allotted, but may still be processing the request (put n
odes 10.143.115.218)
E0131 10:14:31.617808       1 memcache.go:150] couldn't get current server API group list; will keep using cached value. (the server was unable to return a response in the time allotted, but may still b
e processing the request)
```

It looks like these issues may have caused the garbage collector to get into some sort of hung state?

When I restarted controller manager everything started working as expected.

**What you expected to happen**:
Garbage collector should have kept running, and working as expected.

**How to reproduce it (as minimally and precisely as possible)**:
Not sure on the exact sequence that caused it, but suspect it was related to a time period when errors were occurring.

**Anything else we need to know?**:
We have `--leader-elect=false` set, and had previously hit this garbage collector issue -> https://github.com/kubernetes/kubernetes/issues/57044
However, we are running with Kube 1.8.6 with the fix for that issue cherry-picked (commit f5d5d18b2c2320e19ea3c0697c37a95d0009e628)

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.6-4+9c2a4c1ed1ee7e", GitCommit:"9c2a4c1ed1ee7e2e121203aa9a87315633a89eca", GitTreeState:"clean", BuildDate:"2018-01-22T08:23:41Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.6-4+9c2a4c1ed1ee7e", GitCommit:"9c2a4c1ed1ee7e2e121203aa9a87315633a89eca", GitTreeState:"clean", BuildDate:"2018-01-22T08:23:41Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
IBM Cloud
- OS (e.g. from /etc/os-release):
Ubuntu "16.04.3 LTS (Xenial Xerus)"
- Kernel (e.g. `uname -a`):
4.4.0-78-generic #99-Ubuntu SMP Thu Apr 27 15:29:09 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:

I will attach logs from Controller manager.

**Comment by mcginne** [comment]
[cm_trimmed.log.zip](https://github.com/kubernetes/kubernetes/files/1736987/cm_trimmed.log.zip)

**Comment by lavalamp** [comment]
cc @jpbetz

**Comment by janetkuo** [comment]
I saw garbage collector stopped working in 1.9.2 too. Most controllers (such as node controllers or deployment controllers) stopped reporting logs in controller-manager.log when this happened. Manually restarting controller-manager fixed the problem. 

I think somehow some controllers got stuck (could it be because of some bugs in watch cache?) and it's not specific to garbage collector. When the issue happened, `kubectl get cs` reported healthy for controller-manager.

**Comment by janetkuo** [comment]
> When the issue happened, `kubectl get cs` still reported healthy for controller-manager.

#60601 tracks this

**Comment by dwradcliffe** [comment]
This is happening in production for us too.

**Comment by caesarxuchao** [comment]
> Most controllers (such as node controllers or deployment controllers) stopped reporting logs in controller-manager.log

@mcginne @dwradcliffe did this happen to you to? Or is it that only the garbage collector disappeared from the logs?

**Comment by dwradcliffe** [comment]
For me the other controllers still have logs; it was just the GC that crashed.

**Comment by jennybuckley** [comment]
> when I deleted the etcdcluster (Custom resource definition)
@dwradcliffe does your cluster also use CRDs?

**Comment by dwradcliffe** [comment]
> does your cluster also use custom resources

Yes, although this happened in one cluster where we don't have any resources yet (the type exists).

> backed by Aggregated API servers

I'm not sure what that means

**Comment by mcginne** [comment]
@caesarxuchao I still see messages from `service_controller.go:323` and `deployment_controller.go:483` and `controller_utils.go:180] Updating ready status of pod` after the garbage collector stops working - so looks like some controllers are still working. Is there anything specific you were looking for?

**Comment by jennybuckley** [comment]
I think the cause of this garbage collector hanging here is this:

1. The [Sync](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/garbagecollector/garbagecollector.go#L169) function periodically calls [GetDeletableResources](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/garbagecollector/garbagecollector.go#L586)

2. According to the comment above GetDeletableResources, ```All discovery errors are considered temporary. Upon encountering any error, GetDeletableResources will log and return any discovered resources it was able to process (which may be none).```, an error in discovery causes the discovery client to no longer discover resources in the cluster, but instead of failing and returning an error, it simply logs the error as ```garbagecollector.go:601] failed to discover preferred resources: %vthe server was unable to return a response in the time allotted, but may still be processing the request``` and returns an empty list of resources

3. The Sync function, upon recieving an empty resource list from discovery, detects that the resources have changed, and calls [resyncMonitors](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/garbagecollector/garbagecollector.go#L121), which calls [dependencyGraphBuilder.syncMonitors](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/garbagecollector/graph_builder.go#L222) with ```map[]``` as the argument as shown in the log as ```garbagecollector.go:189] syncing garbage collector with updated resources from discovery: map[]```, which sets the list of monitors to an empty list because it thinks there are no resources to monitor.

4. Lastly the Sync function calls controller.WaitForCacheSync, which calls [cache.WaitForCacheSync](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/tools/cache/shared_informer.go#L107), which will continually retry the [garbagecollector.IsSynced](https://github.com/kubernetes/kubernetes/blob/550c0155fa084912d5c8d5d52877b992d36f6216/pkg/controller/garbagecollector/graph_builder.go#L304) function until it returns true, but it will always return false because ```len(gb.monitors)``` is 0.
