### ISSUE TITLE
kops is broken in 1.8 and 1.9 branches

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#60155]
See e.g. these:
https://k8s-testgrid.appspot.com/sig-release-1.9-all#kops-aws-1.9

as well as those two cherrypicks:
https://github.com/kubernetes/kubernetes/pull/60078
https://github.com/kubernetes/kubernetes/pull/60077

@kubernetes/sig-aws-misc @justinsb

**Comment by justinsb** [comment]
This is the problem:

```
E0221 18:07:46.988123    1224 remote_image.go:108] PullImage "k8s.gcr.io/kube-proxy:v1.9.4-beta.0.11_1d6e114ce7a090" from image service failed: rpc error: code = Unknown desc = unauthorized: authentication required
```

I'm guessing that's because we aren't double tagging the images on the older branches.

**Comment by justinsb** [comment]
cc @thockin

**Comment by justinsb** [comment]
I believe this is going to be the fix: https://github.com/kubernetes/kops/pull/4494

**Comment by justinsb** [comment]
Actually, question for you @thockin ... it looks like we need to use the legacy names for when we're running a CI build of an older branch, because I don't think the double-tagging exists on those older branches.

But what are the medium term plans for the gcr.io/google_containers/kube-apiserver:v1.8.8 for non CI builds ?  Should we force users to the new name there (which risks confusing them)?  Or is it OK to continue using the gcr.io/google_containers name for < 1.10 and we can just let these clusters age-out?

**Comment by wojtek-t** [comment]
@mbohlool @jpbetz - FYI

**Comment by wojtek-t** [comment]
This has been fixed by @justinsb - thanks a lot Justin!
