### ISSUE TITLE
Device Plugin failure handling in kubelet is racy

### ISSUE THREAD

**Issue by vishh** [kubernetes/kubernetes#60176]
As of now Kubelet removes a resource owned by device plugins as soon as it notices that a plugin has failed (plugin socket is removed, or ListWatch fails). This behavior is undesirable because trivial plugin restarts would result in Node Capacity changes which is most likely going to be monitored in production clusters resulting in alerts. 

As discussed in https://github.com/kubernetes/kubernetes/issues/53395, we should have kubelet reduce the capacity and allocatable to `0` if a device plugin has failed and then after a timeout remove the resource completely from the Node object. 
This timeout ensures that random restarts do not raise alerts for production cluster admins, while continue failure does raise an alert. It also let's us track scenarios where all devices fail while the device plugin stays healthy. 
Similarly, during startup, kubelet should wait to known plugins to re-register prior to declaring a plugin to be unavailable.
I'd ideally expect this bug to be fixed as part of beta.

@vikaschoudhary16 @RenaudWasTaken @jiayingz @kubernetes/sig-node-bugs @ConnorDoyle

**Comment by vishh** [comment]
This logic is a potential blocker for https://github.com/kubernetes/kubernetes/pull/59835 because spurious device plugin restarts will result in compute resource being removed from the node object. https://github.com/kubernetes/kubernetes/pull/59835 will result in kubelet admitting pods even though it requires a resource belonging to a device plugin that is temporarily offline.

Another question to consider is if a Node should be marked unhealthy as soon as a device plugin goes offline, assuming most cluster admins will treat device plugin failures as critical failures. 
With a timeout in the kubelet, cluster admins can mark a node unhealthy whenever a Node object does not include an expected plugin resource in capacity, thereby not ping ponging between Unhealthy and Healthy phases while device plugins restart.

Overall, I do not think we intended to support dynamic un-registration of device plugins on a healthy node yet. We need to document this explicitly in the user facing guide. That's required at minimum for beta.

**Comment by jiayingz** [comment]
Regarding to how long a device plugin failure should trigger an alert, I think that logic should probably be set in the monitoring/alerting system instead of having to be built into Kubelet. I think the discussion is more related to the change proposed in #59835, with which Kubelet will run a Pod even though its requested resource may not exist on the node, so the failure signal becomes less obvious.

**Comment by ConnorDoyle** [comment]
+1 for a modest timeout before unadvertising the plugin's resources.

> Another question to consider is if a Node should be marked unhealthy as soon as a device plugin goes offline

If this happens after the timeout described above then sure. Otherwise this could make upgrading a device plugin more disruptive than necessary.

**Comment by vikaschoudhary16** [comment]
Just for a sec lets leave alerting and marking node unhealthy. Updating `allocatable` to zero in node status for a plugin which has got disappeared and holding the corresponding endpoint in the device manager cache for couple of secs, will ensure that in-flight pods which are requesting this particular resource will fail to admit because of Allocate RPC failure.

If there are no major concerns with this approach, i will start implementing it.
@jiayingz @vishh @ConnorDoyle

**Comment by jiayingz** [comment]
@vishh and I just discussed this offline. For simplicity, I think devicemanager can just cache the device information in its local cache (either by adding a new field or reusing some existing field like unhealthyDevices) even after endpoint fails/disappears, without any timeout bound. We will still remove the resource from capacity/allocatable as we currently do to signal scheduler from landing more pods on the node. The cached information can be updated when a device plugin re-registers. For now, I don't think we need to checkpoint this data because double side failure should be rare.

For the general problem on how to prevent ping-pong plugin failure and re-registration, we perhaps need to implement a general rate limiting and graceful period in plugin watcher. That should be an orthogonal FR from this issue.

**Comment by vishh** [comment]
> For now, I don't think we need to checkpoint this data because double side failure should be rare.

If we are choosing to not checkpoint, then we should document this as a known issue, as cluster admins may want to build monitoring systems that can deal with this scenario. I'd also suggest thinking hard about checkpointing since it will make the UX simpler for admins. 

As an aside, I think we should consider making plugins a first class construct in the Node Object and most of kubelet level checkpoints can now be moved to the Node API object thereby reducing kubelet complexity and improving introspectability of the system. This will also allow monitoring rules to be implemented on top of k8s APIs which would for rules to be potentially re-used across plugins.

**Comment by jdumars** [comment]
Could you go ahead and add "approved-for-milestone" label to this, as well priority and status? That will help it stay in the milestone if this is a 1.10 blocker. Thanks!

**Comment by jberkus** [comment]
Increasing priority to critical-urgent because we are now in Code Freeze.  Please update the issue regularly with status.

/priority critical-urgent

**Comment by jiayingz** [comment]
Note that the gpu device plugin e2e_node test has been flaky recently because of this race issue. I think the reason that the problem started to surface out recently is probably due to some recent improvements on kubelet restart speed that we now run pods earlier on kubelet start.
