### ISSUE TITLE
Understanding Node port

### ISSUE THREAD

**Issue by ChrisOnToure** [kubernetes/kubernetes#60182]
Hello,

Im having difficulties understanding the NodePort in combination with the service. On a bare metal setup This is how I understood it.

**Service**: The service in Kubernetes its actually a bunch of iptable rules distributed on all of the worker nodes. If inbound traffic hits the service the iptable rules will RoundRobin to one of the containers. This is done by SNAT & DNAT. The service also translates the internal listening port which is e.g 80 to an external listening port which is e.g. 33333.

**NodePort**: Will expose a service on the external IP of the Worker node.

Lets say I have a single worker node and I expose a Pod with 2 containers on a service with node port, how is it possible that two containers listen on the same physical machine on the same internal port in this example 33333? This should be conflict?

**Comment by simplytunde** [comment]
It creates one nodePort per service port that you specify for each container. Take for example;
```bash
kind: Service
apiVersion: v1
metadata:
  name: my-service
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 80
  - name: redis
    protocol: TCP
    port: 6379
    targetPort: 6379
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
       - name: nginx
         image: nginx:1.9.1
         livenessProbe:
           tcpSocket:
             port: 80
       - name: redis
         image: redis
         livenessProbe:
           tcpSocket:
             port: 6379
```
If you deploy this using minikube and describe service, it will create nodePort per service port(per container).
```bash
Name:			my-service
Namespace:		default
Labels:			<none>
Annotations:		kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"my-service","namespace":"default"},"spec":{"ports":[{"name":"http","port":8080...
Selector:		app=nginx
Type:			LoadBalancer
IP:			10.0.0.197
Port:			http	8080/TCP
NodePort:		http	32430/TCP
Endpoints:		172.17.0.4:80,172.17.0.5:80,172.17.0.6:80
Port:			redis	6379/TCP
NodePort:		redis	30210/TCP
Endpoints:		172.17.0.4:6379,172.17.0.5:6379,172.17.0.6:6379
Session Affinity:	None
Events:			<none>
```

**Comment by ChrisOnToure** [comment]
@simplytunde Thanks for your answer. Still in your example nginx this would create 3x Containers (3x replicas) sitting on a single worker node. So 3x containers would listen on 8080 which is not possible and create a port conflict. 

Whats Im missing here?

**Comment by jhorwit2** [comment]
Please re-post your question to [Stack Overflow](http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support
are posted so that we can improve our efficiency in responding to your requests,
and to make it easier for you to find answers to frequently asked questions and
how to address common use cases.

We regularly see messages posted in multiple forums, with the full response
thread only in one place or, worse, spread across multiple forums. Also, the
large volume of support issues on github is making it difficult for us to use
issues to identify real bugs.

Members of the Kubernetes community use Stack Overflow to field support
requests. Before posting a new question, please search Stack Overflow for answers 
to similar questions, and also familiarize yourself with:

  * [user documentation](http://kubernetes.io/docs/)
  * [troubleshooting guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/)

Again, thanks for using Kubernetes.

The Kubernetes Team

/close
