### ISSUE TITLE
Cadvisor metric "container_network_tcp_usage_total" always "0"

### ISSUE THREAD

**Issue by Sartner** [kubernetes/kubernetes#60279]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
The cadvisor metrics "container_network_tcp_usage_total" from "http://my-host:4194/metrics" always "0"
Both of my 2 k8s cluster with different version has the same problem

**What you expected to happen**:
I want to get the count of container tcp connections 

**Environment1**:
- Kubernetes version (use `kubectl version`): 1.9.0
- OS (e.g. from /etc/os-release): Ubuntu 16.04 LTS 
- Kernel (e.g. `uname -a`): 4.4.0-98-generic

**Environment2**:
- Kubernetes version (use `kubectl version`): 1.8.7
- OS (e.g. from /etc/os-release): CentOS Linux release 7.4.1708
- Kernel (e.g. `uname -a`): 3.10.0-693.5.2.el7.x86_64

**Comment by yastij** [comment]
This is caAdvisor related.

**Comment by huzhengchuan** [comment]
cadvisor default disable container_network_tcp_usage_total, so always return 0.
can see detail [here](https://github.com/google/cadvisor/blob/master/docs/runtime_options.md#metrics) 
say like this 

>  --disable_metrics=tcp, udp: comma-separated list of metrics to be disabled. Options are 'disk', 'network', 'tcp', 'udp'. Note: tcp and udp are disabled by default due to high CPU usage. (default tcp,udp)

**Comment by yuzhiquan** [comment]
but how can i to modify cadvisor config, this is an default part for k8s.

**Comment by kongbo1987** [comment]
it  is hard code  in  kubernetes  file  */cadvisor_linux.go
ignoreMetrics := cadvisormetrics.MetricSet{
		cadvisormetrics.NetworkTcpUsageMetrics:  struct{}{},
		cadvisormetrics.NetworkUdpUsageMetrics:  struct{}{},
		cadvisormetrics.PerCpuUsageMetrics:      struct{}{},
		cadvisormetrics.ProcessSchedulerMetrics: struct{}{},
	}

**Comment by bboreham** [comment]
If you metrics which are disabled by kubelet you should run your own instance of cAdvisor, and ignore the one inside kubelet.

**Comment by bboreham** [comment]
As noted above, you don't get nonzero values because data collection is disabled.
The reason you _do_ get lots of zeros is https://github.com/google/cadvisor/issues/1925.

**Comment by blakebarnett** [comment]
@bboreham I notice it says these metrics are disabled because they require high CPU, is this primarily for very large clusters? Testing it out on a small cluster the usage seems fairly negligible, maybe a way to customize cadvisor configuration via kubelet would be justifiable?  

I'm also having a hard time tracking down all places where k8s uses cavdisor metrics to make decisions, is this all changing with the new metrics-server?

**Comment by bboreham** [comment]
@blakebarnett cAdvisor metrics are local to a single node. Collecting thousands of data points from the kernel, via `/proc` interface in ascii, has a cost.

As I understand the bigger picture (I'm not involved with the decision-making here): kubelet needs some metrics for management, and has implemented this by copying in the code from cAdvisor.  That's its business: if you need specific metrics then run your own cAdvisor.

**Comment by blakebarnett** [comment]
will do, just seems silly to run multiple cadvisors on all the nodes, I guess I'll try disabling the metrics kubelet is already collecting in our instance and matching up the prometheus labelling so we can have a consistent view.

**Comment by tanner-bruce** [comment]
This looks to have been resolved in cAdvisor as of https://github.com/google/cadvisor/releases/tag/v0.31.0

**Comment by bboreham** [comment]
The change in cAdvisor fixes the bug that exported zeros; it doesn’t help with the request:

> I want to get the count of container tcp connections

for which the answer is still to run your own instance of a program which has that feature, eg cAdvisor.

**Comment by blakebarnett** [comment]
Yeah, we're going this route. Seems this can be closed.

**Comment by rcsavage** [comment]
I agree, having this option but not allowing operators to turn it on is completely useless.   I just love the excuses... can we work together to get this re-enabled vs coming up with excuses not to?   Myself, as well as some of my other colleagues at a few ISP/telecommunications companies would love to have this enabled.   I may perhaps, build my own kubelet.   Having to run a second cadvisor to work around this problem seems more 'costly' from a maintenance perspective.   

So just to confirm there is no option AT ALL, within Kubelet to re-enable TCP and UDP metrics from cadvisor (embedded in Kubelet)??

**Comment by yastij** [comment]
cc @dashpole

**Comment by dashpole** [comment]
The original bug was fixed in k8s version 1.12, as mentioned above.  If you need tcp-specific metrics, you can [run a daemonset](https://github.com/google/cadvisor/tree/master/deploy/kubernetes) with [tcp metrics enabled](https://github.com/google/cadvisor/blob/master/docs/runtime_options.md#metrics).
