### ISSUE TITLE
PVC status: "Lost" (AWS volumes)

### ISSUE THREAD

**Issue by mthoretton** [kubernetes/kubernetes#60298]
/kind bug

**Problem**:

`kubectl get pvc`
![screen shot 2018-02-23 at 11 50 07](https://user-images.githubusercontent.com/6221533/36590685-be39844c-188f-11e8-9854-ba16ee9e0a0b.png)

We are running a kafka cluster in k8s. kafka-servers run as "StatefulSet". They're using PVC to store data:
```
# kafka manifest
# ...
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      storageClassName: generic
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 50Gi
```
This was working pretty well.
At some point, all PVCs for the kafka StatefulSet got a "Lost" status. Running pod/containers are still bound to the AWS volumes though (=> we can still access those volumes mounted in pods filesystem). The main problem is, when we run an update for instance, the pods won't be able to start as the PVC state is not OK.
kubectl is logging a few times/second this:
```
Feb 23 09:46:37 worker-generic3.xxx.com kubelet-wrapper[913]: E0223 09:46:37.509228     913 desired_state_of_world_populator.go:274] Error processing volume "data" for pod "kafka-1_namespace(28f9e78e-165f-11e8-b0b4-02f219457d76)": error processing PVC "namespace"/"data-kafka-1": PVC namespace/data-kafka-1 has non-bound phase ("Lost") or empty pvc.Spec.VolumeName ("pvc-e50392dc-161f-11e8-b0b4-02f219457d76")
```

AWS volumes are still running and healthy/with the right tags:
![screen shot 2018-02-23 at 13 07 43](https://user-images.githubusercontent.com/6221533/36593593-a78b26f0-189a-11e8-8472-04a0ca3d4262.png)

We did check many things already but no way to find any explanation. Also we didn't find that much about what's the meaning of "Lost" status for PVCs.
As It's a sandbox cluster (we run manual commands and potentially broken configs) we could have broken something accidentally, but I don't see how it can lead to this situation.

**How to reproduce it (as minimally and precisely as possible)**:

No idea. It's the first time we see that in a few months. Also, it only happened on one sandbox cluster so far.

**Anything else we need to know?**:

I don't think so but I'll provide everything needed to help resolving this issue. Thanks for looking into this :)

---

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-09T21:51:54Z", GoVersion:"go1.9.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.5", GitCommit:"cce11c6a185279d037023e02ac5249e14daa22bf", GitTreeState:"clean", BuildDate:"2017-12-07T16:05:18Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: AWS
- OS (e.g. from /etc/os-release): 
```
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1632.3.0
VERSION_ID=1632.3.0
BUILD_ID=2018-02-14-0338
PRETTY_NAME="Container Linux by CoreOS 1632.3.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
```
- Kernel (e.g. `uname -a`):
```
Linux XXX 4.14.19-coreos #1 SMP Wed Feb 14 03:18:05 UTC 2018 x86_64 Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz GenuineIntel GNU/Linux
```
- Install tools:
- Others:

**Comment by mthoretton** [comment]
@kubernetes/sig-storage-bugs

**Comment by jsafrane** [comment]
"Lost" means that something deleted PVs that were bound to the PVCs. Check your audit logs what and when did that.

**Comment by mthoretton** [comment]
Do you mean AWS audit logs? (cloudtrail) if yes we don't have this service enabled :/ On k8s side I've checked different logs, I've found that line from kube-apiserver logs which doesn't say anything but could give the time when it happened:

**Comment by mthoretton** [comment]
For now our best guess about what happened is: AWS API was not working properly this night and it returned no/incomplete data. Then k8s decided to remove some PV and never tried anymore later in time to check on AWS if the volumes does exist or not. 
Another interesting fact, it only affected volumes created 3d ago, and not the ones created 2d ago.

**Comment by msau42** [comment]
Can you search master apiserver and controller manager logs for the PV name (pvc-750...)?

**Comment by mthoretton** [comment]
apiserver  logs: no occurence of "pvc-"
controller manager logs: (i've filtered lines containing data-kafka-N PVCs): https://gist.github.com/mthoretton/42f28ed2b8e7c04a098220deb686f197

Tell me if you would need the full logs (unfiltered) or data from other sources. Thanks for your help.

**Comment by msau42** [comment]
Claims become lost if one of the following occurs:
* PVC.Spec.VolumeName gets set to ""
* The PV got deleted
* The PV.Spec.ClaimRef.UID doesn't match the PVC's UID

Can you check which condition it was?

**Comment by mthoretton** [comment]
In our case, PV got deleted. We managed to recover by recreating deleted PVs applying manifests where we set data like pvc name or awsElasticBlockStore.volumeID manually.

**Comment by msau42** [comment]
Hm if PV got deleted then there must be some logs in apiserver that showed who deleted it.  How long ago did it happen? Is it possible it was too long ago and apiserver logs got rotated out?

**Comment by gseshagirirao** [comment]
Hi,

While trying to restore the EBS volumes from the snapshot it returns status as lost. we are using AWS KMS CMK keys with policy having kms* permission. The backup operation went fine.. the restore operation is able to restore all k8s resources expect the PVC. 

k get pvc -n nginx-example 
NAME         STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
nginx-logs   Lost     pvc-bda55207-a1e5-11ea-b7e6-02b82f6b7f4e   0                         gp2-encrypt    4m22s

k get pv
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS     CLAIM                      STORAGECLASS   REASON   AGE
pvc-bda55207-a1e5-11ea-b7e6-02b82f6b7f4e   1Gi        RWO            Retain           Released   nginx-example/nginx-logs   gp2-encrypt             33m

We noticed the UID of PV and PVC are not matching after the PVC is restored. 
 
The service account used by velero pod has below policy as 
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
                "ec2:DeleteSnapshot",
                "kms:Decrypt",
                "ec2:CreateTags",
                "kms:GenerateDataKeyWithoutPlaintext",
                "s3:ListBucket",
                "kms:GenerateDataKeyPairWithoutPlaintext",
                "ec2:DescribeSnapshots",
                "kms:GenerateDataKeyPair",
                "kms:ReEncryptFrom",
                "ec2:CreateVolume",
                "s3:ListMultipartUploadParts",
                "s3:PutObject",
                "s3:GetObject",
                "s3:AbortMultipartUpload",
                "ec2:DescribeVolumes",
                "ec2:CreateSnapshot",
                "kms:GenerateDataKey",
                "kms:ReEncryptTo",
                "s3:DeleteObject"
            ],
            "Resource": "*"
        }
    ]
}

we are using the below yaml to define storageclass and PVC

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp2-encrypt
parameters:
  type: gp2
  encrypted: "true"
  fsType: ext4
  kmsKeyId: arn:aws:kms:us-east-XXXXXX
provisioner: kubernetes.io/aws-ebs
reclaimPolicy: Retain

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nginx-logs
  namespace: nginx-example
  labels:
    app: nginx
spec:
  # Optional:
  storageClassName: gp2-encrypt 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: [50Mi]

Below are logs from velero pods..

time="2020-05-29T19:59:04Z" level=info msg="Starting restore of backup cluster-addons/nginx-backup-5" logSource="pkg/restore/restore.go:394" restore=cluster-addons/nginx-backup-5-20200529155858
time="2020-05-29T19:59:04Z" level=info msg="Restoring cluster level resource 'persistentvolumes'" logSource="pkg/restore/restore.go:779" restore=cluster-addons/nginx-backup-5-20200529155858
time="2020-05-29T19:59:04Z" level=info msg="Getting client for /v1, Kind=PersistentVolume" logSource="pkg/restore/restore.go:821" restore=cluster-addons/nginx-backup-5-20200529155858
time="2020-05-29T20:09:04Z" level=info msg="Restoring resource 'persistentvolumeclaims' into namespace 'nginx-example'" logSource="pkg/restore/restore.go:777" restore=cluster-addons/nginx-backup-5-20200529155858
time="2020-05-29T20:09:04Z" level=info msg="Getting client for /v1, Kind=PersistentVolumeClaim" logSource="pkg/restore/restore.go:821" restore=cluster-addons/nginx-backup-5-20200529155858
time="2020-05-29T20:09:04Z" level=info msg="Executing item action for persistentvolumeclaims" logSource="pkg/restore/restore.go:1030" restore=cluster-addons/nginx-backup-5-20200529155858
time="2020-05-29T20:09:04Z" level=info msg="Executing AddPVFromPVCAction" cmd=/velero logSource="pkg/restore/add_pv_from_pvc_action.go:44" pluginName=velero restore=cluster-addons/nginx-backup-5-20200529155858
time="2020-05-29T20:09:04Z" level=info msg="Adding PV pvc-bda55207-a1e5-11ea-b7e6-02b82f6b7f4e as an additional item to restore" cmd=/velero logSource="pkg/restore/add_pv_from_pvc_action.go:66" pluginName=velero restore=cluster-addons/nginx-backup-5-20200529155858
time="2020-05-29T20:09:04Z" level=info msg="Skipping persistentvolumes/pvc-bda55207-a1e5-11ea-b7e6-02b82f6b7f4e because it's already been restored." logSource="pkg/restore/restore.go:910" restore=cluster-addons/nginx-backup-5-20200529155858
time="2020-05-29T20:09:04Z" level=info msg="Executing item action for persistentvolumeclaims" logSource="pkg/restore/restore.go:1030" restore=cluster-addons/nginx-backup-5-20200529155858
time="2020-05-29T20:09:04Z" level=info msg="Executing ChangeStorageClassAction" cmd=/velero logSource="pkg/restore/change_storageclass_action.go:63" pluginName=velero restore=cluster-addons/nginx-backup-5-20200529155858
time="2020-05-29T20:09:04Z" level=info msg="Attempting to restore PersistentVolumeClaim: nginx-logs" logSource="pkg/restore/restore.go:1136" restore=cluster-addons/nginx-backup-5-20200529155858
time="2020-05-29T20:09:04Z" level=info msg="Done executing ChangeStorageClassAction" cmd=/velero logSource="pkg/restore/change_storageclass_action.go:74" pluginName=velero restore=cluster-addons/nginx-backup-5-20200529155858

The cloudtrail does not have much information.  Would you please let us know any additional. settings needed here?
