### ISSUE TITLE
Disable or override parts of a Cloud Provider implementation (AWS Custom Load Balancer Controller)

### ISSUE THREAD

**Issue by plombardi89** [kubernetes/kubernetes#60326]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:

I want to override the AWS Cloud Provider integration that creates Elastic Load Balancers when specifying `type: LoadBalancer` on a `v1.Service`. My use case is that I want to use a custom load balancer implementation that will route traffic into the Kubernetes cluster instead of relying on the ELB, however, at the same time I do not want to lose access to other AWS features such as EBS volumes when using the `aws` cloud provider integration. I would write my own control loop that can provision my custom load balancer when Service records change.

**What you expected to happen**:

There should be way to disable or override various features of the cloud provider integrations such that I could write my own control loops for various features such as LoadBalancer creation.

**How to reproduce it (as minimally and precisely as possible)**:

Spin up any Kubernetes Cluster with the `aws` cloud provider and you'll realize there is no way to disable or override aspects of its implementation.

**Anything else we need to know?**:

No.

**Comment by jhorwit2** [comment]
@plombardi89 You'll need to write your own cloud controller manager to accomplish this. That'd let you use AWS controllers when you want and write your own for the others. 

https://kubernetes.io/docs/tasks/administer-cluster/developing-cloud-controller-manager/

If you have any questions about the cloud controller manager I'd recommend joining #wg-cloud-provider on k8s slack. 

/kind cloudprovider
/close

**Comment by plombardi89** [comment]
@jhorwit2 Why should users need to effectively implement, build, distribute and then deploy their own cloud provider just to handle what is essentially a very simple conditional usage case? That response is basically the equivalent of telling a user to go build a car from scratch when all they want is the option to select between a manual and automatic transmission on an existing model.

**Comment by jhorwit2** [comment]
@plombardi89 

> My use case is that I want to use a custom load balancer implementation that will route traffic into the Kubernetes cluster instead of relying on the ELB, however, at the same time I do not want to lose access to other AWS features such as EBS volumes when using the aws cloud provider integration.

In order to implement a custom load balancer implementation you need to implement the servie cloud provider interface and use the built-in service controller to call it. If you're familiar with go you could use the existing aws implementation then override the ~5 or so lb specific methods. That way you re-use all the other logic. 

> That response is basically the equivalent of telling a user to go build a car from scratch when all they want is the option to select between a manual and automatic transmission on an existing model.

I'd say it's more like you take an existing car then swap the transmission ;). 

You can re-use almost all of the AWS implementation for the cloud controller manager. Please note that most of the cloud specific logic isn't contained in the CCM. The CCM only contains persistent volume labeler, node controller and service controller. The EBS logic is separate, so that won't be touched.
