### ISSUE TITLE
Request path alway returns Kubernetes internal end point

### ISSUE THREAD

**Issue by hpham04** [kubernetes/kubernetes#60416]
Let's say I have an end point like: http://xxx.amazonaws.com
Normally, if I call a function in server side such as: request.get_host() , it would return http://xxx.amazonaws.com but in my case, it return an internal end point url in Kubernetes like xxx.svc.cluster.local
Is it possible to get the external end point instead of kubernetes internal end point?
Please help to advise. My scenario is that, from our app, users are able to upload a file to s3 and I need an end point, so after user upload file successfully, amazon would redirect to my end point

**Comment by jhorwit2** [comment]
@hpham04 Quick answer is that you need to use the host network in order for that to work or if the node name is the FQDN you could use the downward api to expose an env var to the pod. 

If you need further assistance please re-post your question to [Stack Overflow](http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support
are posted so that we can improve our efficiency in responding to your requests,
and to make it easier for you to find answers to frequently asked questions and
how to address common use cases.

We regularly see messages posted in multiple forums, with the full response
thread only in one place or, worse, spread across multiple forums. Also, the
large volume of support issues on github is making it difficult for us to use
issues to identify real bugs.

Members of the Kubernetes community use Stack Overflow to field support
requests. Before posting a new question, please search Stack Overflow for answers 
to similar questions, and also familiarize yourself with:

  * [user documentation](http://kubernetes.io/docs/)
  * [troubleshooting guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/)

Again, thanks for using Kubernetes.

The Kubernetes Team
