### ISSUE TITLE
Need a health / liveness check for master component pod

### ISSUE THREAD

**Issue by dchen1107** [kubernetes/kubernetes#6047]
#5011 is going to put all master components into a pod for v1 release. When any master component container exit, Kubelet will restart it. But sometimes, the component might be stuck somewhere unhealthy without being terminated. In such case, we need to 

1) detect such problem
2) kill bad container and restart it
3) generate status / events related to such failure 
4) alert? 

@bgrant0607 @thockin @brendanburns @alex-mohr

**Comment by dchen1107** [comment]
@davidopp

**Comment by alex-mohr** [comment]
If they each self-monitor and export /healthz, kubelet could monitor that?

Of course, that doesn't address system-wide issues or interactions between the components or what to do when the component is unstartable, but perhaps still worth doing anyway?

**Comment by bgrant0607** [comment]
Don't all of these components already export /healthz?

**Comment by yujuhong** [comment]
Yes, they export /healthz, and you can check via the apiserver /validate endpoint. E.g.,
```
curl -L http://127.0.0.1:8080/validate
[
  {
    "component": "scheduler",
    "health": "success",
    "msg": "ok",
    "err": "nil"
  },
  {
    "component": "etcd-0",
    "health": "success",
    "msg": "{\"action\":\"get\",\"node\":{\"dir\":true,\"nodes\":[{\"key\":\"/registry\",\"dir\":true,\"modifiedIndex\":4,\"createdIndex\":4}]}}\n",
    "err": "nil"
  },
  {
    "component": "node-0",
    "health": "success",
    "msg": "ok",
    "err": "nil"
  },
  {
    "component": "controller-manager",
    "health": "success",
    "msg": "ok",
    "err": "nil"
  }
```

**Comment by wojtek-t** [comment]
cc/ me

**Comment by roberthbailey** [comment]
GKE uses the /validate endpoint to verify that a cluster is healthy. We should be using it for OSS as well instead of the separate (but similar) checks that we currently do in [validate-cluster.sh](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cluster/validate-cluster.sh) and they need to be re-aligned. 

At the moment the implementation of /validate is a bit unfortunate: each time you hit it the apiserver creates an http request to each master component and each node in the system. The apiserver should already have a pretty good idea of whether the nodes are healthy, so doing an on-demand check seems superfluous. @erictune has some strong opinions here as well.

**Comment by derekwaynecarr** [comment]
@pmorie we discussed health check of api server today.  See previous comment.

**Comment by yujuhong** [comment]
I will look into optimizing the implementation of /validate.

**Comment by roberthbailey** [comment]
Thanks @yujuhong - that would be much appreciated.

**Comment by yujuhong** [comment]
In #6597, @bgrant0607 suggested that we remove node statuses from /validation completely. If we go with that route, we don't need to optimize the performance anymore.

Kubelet only needs health check of the master components (not all the nodes), so it could either continue using /validate or just probe the individual /healthz endpoint of the components.

**Comment by roberthbailey** [comment]
I think kubelet should just healthcheck each pod on the master individually. 

We still need some sort of cluster-wide health indication (as @fabioy mentions in #6597) but we'd like to transition away from an unversioned endpoint.

**Comment by yujuhong** [comment]
@dchen1107, would the current heathcheck point for individual master components work for you? Do you have any other requirements?

**Comment by smarterclayton** [comment]
So /healthz is liveness check and /validate is readiness check?  Just want to know so we can copy in OpenShift.

**Comment by roberthbailey** [comment]
@smarterclayton /validate (currently only on the master and @bgrant0607 hopes to deprecate since it's unversioned) is an overall cluster liveness check. It currently combines /healthz from the master components and the nodes.

**Comment by smarterclayton** [comment]
So then what can we defined as /healthz?  /healthz/ready?

**Comment by smarterclayton** [comment]
Define a new /readyz?

**Comment by bgrant0607** [comment]
What we should have:
* Single-component liveness probe (kill if not responsive). More or less the current /healthz for most components. I'd prefer to rename this endpoint since (a) it's ambiguous and (b) it pollutes the API space with an inconsistent unversioned endpoint. We use /debug for profiling and monitoring. I suggest /debug/live. Only kubelet or other process manager should hit this endpoint. /status/live would also be fine.
* Single-component readiness probe (component is functional). Clients may want to hit this endpoint, similar to /version. I don't think it needs to be versioned, but it would ideally be unambiguous and should return a structured json response similar to our other unversioned endpoints. I suggest /status/ready.
* Cluster control-plane component status. This should be the new versioned /api/v1beta*/componentstatuses -- we need to eliminate node status from this. I really wanted a component registration API, /api/v1beta*/components, which would provide a way for plugins and add-ons to register themselves.
* Node status. This is just the /api/v1beta*/nodes API.

**Comment by roberthbailey** [comment]
I believe that @alex-mohr falls on the side of the argument saying there should be a single endpoint on the master that rolls up both component status and node status -- adding him here so he can chime in.

**Comment by alex-mohr** [comment]
Re: single endpoint vs. multiple, I'd prefer for the master know its current status as a usable cluster or not, along with all the supporting details, and report that as a single API call, rather than rely on clients to stitch together various bits of separate data and implement their own (diverging) logic for determining whether a cluster is healthy or not.  E.g., /status/{live,ready} at the cluster scale.

That said, I don't know the details in this area, and I'm mostly in favor of something expedient and reasonable to make progress towards v1 without generating lots of short-term complexity/work.  If the union of /api/v1betaN/{components,nodes} is actually the same data as /validate, that seems potentially reasonable, though adds costs to the clients in terms of handling partial data vs. a single call.  It also seems reasonable to have a /validate (under whatever name/path) that pulls in that relevant data into a single synthesized value.

**Comment by derekwaynecarr** [comment]
/sub , need to track what we can do for readiness probe separate from healthz for OpenShift.  To elaborate on readiness probe, there are cases for us where we want to make sure certain caches are primed, or that certain things were created.  For example, for Kube, it seems like you would not report readiness until the 'default' namespace is provisioned in etcd.

**Comment by davidopp** [comment]
Actually I'm no longer sure what the difference is between this issue and #7092

**Comment by davidopp** [comment]
@roberthbailey and @yujuhong explained to me offline. All that's left here is to verify that /healthz endpoint on the master components works and that Kubelet restarts them when /healthz check fails, then we can close this issue. #7092 is different; for that @roberthbailey said they will use the new ComponentStatus to check master components' health, and NodeStatus from /nodes endpoint to check nodes health.

**Comment by davidopp** [comment]
@yujuhong can we close this issue?

**Comment by roberthbailey** [comment]
I noticed the other day that the etcd pod is the only pod running on the master that doesn't have a liveness check ([kube-apiserver](https://github.com/kubernetes/kubernetes/blob/master/cluster/saltbase/salt/kube-apiserver/kube-apiserver.manifest#L122), [kube-scheduler](https://github.com/kubernetes/kubernetes/blob/master/cluster/saltbase/salt/kube-scheduler/kube-scheduler.manifest#L35), [kube-controller-manager](https://github.com/kubernetes/kubernetes/blob/master/cluster/saltbase/salt/kube-controller-manager/kube-controller-manager.manifest#L67) all do but there isn't one in [etcd.manifest](https://github.com/kubernetes/kubernetes/blob/master/cluster/saltbase/salt/etcd/etcd.manifest)). 

@cjcullen and I were talking about this but I can't remember if we filed an issue for it or just each thought the other would send a PR to fix it.

**Comment by yujuhong** [comment]
@roberthbailey, I couldn't find the etcd issue that you two may have filed. I am assigning this issue to you assuming you plan to add a health check to etcd. Feel free to unassign if that's not the case. Thanks!

**Comment by roberthbailey** [comment]
@cjcullen is going to add a liveness probe for the etcd pod.
