### ISSUE TITLE
Pods take a long time to terminate when running two containers that don't exit simultaneously  

### ISSUE THREAD

**Issue by jkemp101** [kubernetes/kubernetes#60518]
/kind bug

**What happened**:
I have a pod running a python app as the main container with a statsd sidecar container.  I'm running 100 of these in a StatefulSet.  It takes over a minute to stop and start a new version of this pod.  The python app exits within 5 seconds of receiving the SIGTERM and the statsd container exits almost immediately.  After the two containers exit the pod is stuck for up to a minute with a status of `Terminating` and Ready of `0/2` as seen with the `kubectl get pod` command. 

**What you expected to happen**:
Restarts of this pod should occur within 10 seconds. 

**How to reproduce it (as minimally and precisely as possible)**:
I was able to reproduce the issue using the python code below by running two containers in the same pod and using two different exit delays.  The issue seems to be caused by the two containers having some gap between exiting.  I could trigger the issue with as little as a 2 second difference between the containers exiting.  That means I can deploy updates significantly faster if both containers take 10 seconds to exit than I can if one container takes 1 second to exit and the other takes 3 seconds.

After watching a bunch of these it also seems like the Pod stays in the ready state longer than it should but I'm not sure what the official spot is to check if it is really `ready`.  It seems like as soon as the SIGTERM is sent the pod should be marked not ready.

```
import signal
import sys
import time

loop = True

def signal_handler(signum, frame):
    global loop
    print 'Got signal, sleeping'
    time.sleep(int(sys.argv[1]))
    print 'Done sleeping'
    loop = False

signal.signal(signal.SIGTERM, signal_handler)

while loop:
    time.sleep(1)

print 'Exiting'
```
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.8.8
- Cloud provider or hardware configuration: AWS provisioned
- OS (e.g. from /etc/os-release): Debian jessie
- Kernel (e.g. `uname -a`): 4.4.115-k8s
- Install tools: Kops 1.8.1
- Others: Flannel networking

**Comment by jkemp101** [comment]
@kubernetes/sig-node-bugs

**Comment by mshaverdo** [comment]
I have the exactly same problem with multi-container pods with different shutdown duration. It could be reproduced using following pod:

```
---
apiVersion: v1
kind: Pod
metadata:
  name: demo
spec:
  containers:
  - name: test-1
    image: mshaverdo/delayer
    imagePullPolicy: Always
    args: ["3"]
  - name: test-2
    image: mshaverdo/delayer
    imagePullPolicy: Always
    args: ["5"]
```



Due to my investigation, problem in the `kubelet.notRunning()` function and related to  `kubelet.cleanUpContainersInPod()` function and `kubelet.minDeadContainerInPod` constant. 

There are 3 cases of cleanUpContainersInPod() invocation:

**I. Pod running, one of it's containers occasionally dies.** 

1. `Kubelet.cleanUpContainersInPod` triggered
4. `Kubelet.cleanUpContainersInPod` calls `kubelet.notRunning()`, 
5. `kubelet.notRunning()` checks that pod has running containers and  returns **false**
6. `Kubelet.cleanUpContainersInPod` calls `podContainerDeletor.deleteContainersInPod()` with `removeAll == false`
7. `podContainerDeletor.deleteContainersInPod()` leaves `podContainerDeletor.containersToKeep` (at least 1) dead containers in the pod due to `removeAll == false`
3.  **It's OK**

**II. Deleting Pod with single container or multiple containers that DO exit simultaneously** 

1. kubelet sends TERMINATE to all containers
2. all containers are dead
3. `Kubelet.cleanUpContainersInPod` triggered
4. `Kubelet.cleanUpContainersInPod` calls `kubelet.notRunning()`, 
5. `kubelet.notRunning()`check that all containers are dead and  returns **true** 
6. `Kubelet.cleanUpContainersInPod` calls `podContainerDeletor.deleteContainersInPod()` with `removeAll == true`
7. `podContainerDeletor.deleteContainersInPod()` **removes all containers from the pod**.
8. `kubelet.status.manager.syncPod()`  calls `manager.canBeDeleted()`
9. `manager.canBeDeleted()` calls `kubelet.PodResourcesAreReclaimed()`
10. `kubelet.PodResourcesAreReclaimed()` checks that pod has no containers and returns `true`
11. `kubelet.status.manager.syncPod()` deletes pod
12. **It's OK**

**III. Deleting Pod with multiple containers that don't exit simultaneously** 

1. kubelet sends TERMINATE to all containers
2. container-1 dead, container-2 still alive
3. `KubeletcleanUpContainersInPod` triggered
4. `KubeletcleanUpContainersInPod` calls `kubelet.notRunning()`, 
5. `kubelet.notRunning()` checks that pod has 1 running container (container-2) and  returns **false** <-- **After this point we have wrong aftermath** 
6. `KubeletcleanUpContainersInPod` calls `podContainerDeletor.deleteContainersInPod()` with `removeAll == false`
7. `podContainerDeletor.deleteContainersInPod()` **leaves `podContainerDeletor.containersToKeep` (at least 1) dead containers in the pod due to `removeAll == false`
8. `kubelet.status.manager.syncPod()`  calls `manager.canBeDeleted()`
9. `manager.canBeDeleted()` calls `kubelet.PodResourcesAreReclaimed()`
10. `kubelet.PodResourcesAreReclaimed()` checks that pod has some containers have not been cleaned up and returns **false** due to p. 7
11. `kubelet.status.manager.syncPod()` **don't delete pod and leaves it in `terminating` state** due to `manager.canBeDeleted()` returns false
12. in next garbage collection cycle (up to 1 minute due to `kubelet.ContainerGCPeriod` constant) GC removes dead  containers
13. in next sync cycle (up to 10 seconds due to`kubelet.status.manager.syncPeriod` constant) `kubelet.status.manager.syncPod()` runs again and deletes pod successfully
14. **It's wrong and leads up to 70 seconds delay**

It seems impossible to distinguish case III from case I in kubelet.notRunning() using existing data (ContainerStatus). Maybe, someone from @kubernetes/sig-node-bugs team could advise a solution.

**Comment by jkemp101** [comment]
It looks like this PR https://github.com/kubernetes/kubernetes/pull/63321 might fix this. Has anyone had a chance to try it?
