### ISSUE TITLE
TestKMSProvider is flaky

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#60614]
TestKMSProvider is flaking slightly in head:

https://storage.googleapis.com/k8s-gubernator/triage/index.html?test=TestKMSProvider

```
--- FAIL: TestKMSProvider (10.47s)
	testserver.go:106: Starting kube-apiserver on port 37352...
	testserver.go:118: Waiting for /healthz to be ok...
	kms_transformation_test.go:109: failed to get DEK from KMS: timed-out while getting encryption request from KMS Plugin Mock
```

The timeout block is suspect:

https://github.com/kubernetes/kubernetes/blob/07240b7166d83bed49d783e0ecdfa7ee7e62cfca/test/integration/master/kms_transformation_test.go#L140-L147

If this is asynchronous, 1 ms is a super tight tolerance for an integration test. looking at the test, though, it's unclear which piece would be asynchronous.

**Comment by liggitt** [comment]
@immutableT can you take a look?

**Comment by BenTheElder** [comment]
definitely flaky https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/60524/pull-kubernetes-integration/49/

**Comment by immutableT** [comment]
@liggitt Thank you for #60615

I just ran the test (without your fix) 100 times locally without any issues.
Interactions between the Test and Mock KMS Plugin are synchronized via a read to etcd, so the increased time-out should not be necessary. I believe that something else is at fault here.
Once 60615 merges I will improve logging of KMS Plugin Mock so that we could pin-point the issue if it re-surfaces.

**Comment by liggitt** [comment]
> Interactions between the Test and Mock KMS Plugin are synchronized via a read to etcd, so the increased time-out should not be necessary

Agreed. Will leave this reopen to track.

**Comment by liggitt** [comment]
no flakes seen in last triage period, closing

https://storage.googleapis.com/k8s-gubernator/triage/index.html?pr=1&test=TestKMSProvider

/close
