### ISSUE TITLE
Kubelet leaves orphaned directories and mounts after downtime

### ISSUE THREAD

**Issue by jsafrane** [kubernetes/kubernetes#60645]
/kind bug

**What happened**:
kubelet logs lot of `Orphaned pod "2663ce08-d054-11e7-b7ee-00505684022a" found, but volume paths are still present on disk.` when it starts and a pod was deleted while it was offline.

**How to reproduce it (as minimally and precisely as possible)**:

1. run a pod with AWS EBS volume (should work also with GCE or any other volume)
2. stop kubelet
3. delete the pod
4. start kubelet

It's not always reproducible, is there some sort of race?

My current theory:

* desiredStateOfWorldPopulator scans pods and adds this pod to DSW

* reconciler.syncStates() runs.
  * it finds mounted volume
  * but it does **not** add it to actual state of world because it's in DSW:
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/volumemanager/reconciler/reconciler.go#L361

* When kubelet fully starts, it kills the pod and cleans DSW, but the volume never reached AWS so nothing is unmounted. 

**Environment**:
- Kubernetes version (use `kubectl version`): today's master

I have troubles reproducing this on master.

/sig storage
/sig node
@jingxu97 @gnufied

**Comment by jsafrane** [comment]
Ok, check at reconciler.go#L361 won't add the volume to ASW. But the volume is in DSW and subsequent reconcile() should check that the volume is attached and mounted and add it to ASW. This does not happen, because:

```
E0301 14:53:44.642427   25567 nestedpendingoperations.go:267] Operation for "\"kubernetes.io/aws-ebs/aws://us-east-1d/vol-086a6e0314e420457\"" failed. No retries permitted until 2018-03-01 14:53:45.142385594 +0000 UTC m=+4.255208860 (durationBeforeRetry 500ms). Error: "Volume has not been added to the list of VolumesInUse in the node's volume status for volume \"pvc-09616501-1d60-11e8-89c8-0e8a79e1ed62\" (UniqueName: \"kubernetes.io/aws-ebs/aws://us-east-1d/vol-086a6e0314e420457\") pod \"testpod\" (UID: \"0ad21b6f-1d60-11e8-89c8-0e8a79e1ed62\") "
```

Volume is not in `node.Status.VolumesInUse`  because it was overwritten by new kubelet (?)

**Comment by gnufied** [comment]
This problem goes beyond a simple logging error. The problem also is - such volumes never get unmounted correctly and hence volume can not be used anywhere. IMO this is kind of serious.

Steps to reproduce:
1. Create a pod on node X
2. Stop kubelet
3. Delete the pod. The pod will be stuck in "Terminating" state
4. Bring back the kubelet

There is a race which is rather easy to reproduce and what happens is - volume gets added to DSW at kubelet but it never makes into ASW because volume is indeed never in use on node (because pod was deleted while kubelet was down). 

This results in volume never getting unmounted and hence any attempt to use the volume on different node fails.

**Comment by jsafrane** [comment]
IMO, this happens:

1. `reconciler.syncStates()` is called only once at kubelet startup and at that point the pod still exists (it's in Terminating state). The volume is in DSW and it's not added to ASW.

2. `reconciler.reconcile()` is called periodically. It could add the volume to ASW, but it does not, because the volume is not in node.status.volumesInUse yet.

3. kubelet kills pod containers and confirms it's deleted. The pod is deleted from API server.

4. kubelet removes the pod from DSW

5. setNodeVolumesInUseStatus() is called and the volume is not added there because it's not in DSW.

We have mounted volume that's not in DSW nor in ASW.


There are several possible solutions:

a. kubelet can add the volume to ASW in `reconciler.syncStates()` regardless of DSW.
b. kubelet can update node status earlier, just after `reconciler.syncStates()`. Will there still be race when pod is deleted during `reconciler.syncStates()` and thus it won't reach `setNodeVolumesInUseStatus`?
c. kubelet could call `reconciler.syncStates()` regularly.

I am inclined to a), it looks robust to me and it just reflects reality in ASW. It should not matter if the volume is in DSW or not at this point - `reconcile()` will sort it out and do the right thing.

**Comment by jsafrane** [comment]
solution d.: in reconciler.syncStates() try to reconstruct volume from DSW, fall back to `plugin.ConstructVolumeSpec` only if the volume is not there. DSW already has spec and other useful info.

**Comment by jsafrane** [comment]
Experimental fix (solution d.): #60846

**Comment by jsafrane** [comment]
@saad-ali, FYI, this might be another 1.10 (or 1.10.1) candidate. We need thorough review though, volumeManager is quite complicated.

**Comment by gnufied** [comment]
@jsafrane @jingxu97 another simpler option is perhaps to mark a volume as "ReportedInUse" if it was found on the disk during reconstruction phase.  That will make sure that, volume gets added correctly to ASW via reconciler(rather than us doing it on reconstruction) and it will make sure that volume is unmounted when volume does get removed from DSW.

**Comment by jsafrane** [comment]
I closed #60846, it would blow up when kubelet was restarted at wrong time when creating a pod.

> mark a volume as "ReportedInUse" if it was found on the disk during reconstruction phase

Interesting idea, I opened #60888 with it. I am not sure it covers all the corner cases though. Newly started kubelet does not overwrite its own status until `syncState()` runs, I hope it's ensured by something and not just a coincidence.

**Comment by jingxu97** [comment]
I think #60888 might still hit a race condition issue as below

1. Pod is normally deleted (without force delete) during kubelet restart
2. Kubelet restarts, pod is received again so it is add to the pod Manager
3. Pod is added to desired state, so reconciler skip to reconstruct to the actual state
4. Kubelet kill containers and then try to delete the Pod from API server. If actual state has not yet updated from reconciler, pod will be deleted from pod manager and desired state too
5. reconciler will reconcile actual state and desired state. But if step 4 happened first, it will not be able to update actual state since volume is removed from desired state.

Depending on which happens first between step 4 and 5, volume might or might not have a chance to get into the actual state. I am thinking #60846 seems better to solve the issue with some additional protection. The idea is to avoid letting kubelet to delete pod before actual state has updated the volume. We can set a flag in actual state to indicate when reconstruction finishes.

**Comment by gnufied** [comment]
@jingxu97 what hook you are planning to use to stop kubelet from deleting pod unless it has been processed into asw?

**Comment by jingxu97** [comment]
My thought is to add a flag (e.g., finishReconstruct) in actual_state_of_world to indicate whether reconstruction finished or not. volume_manager will add a function (e.g., IsActualStateReconstructed) to check the flag is set or not. When status_manager.go call canBeDeleted() function, the PodResourcesAreReclaimed in  kubelet_pod.go will return false if actual state has not yet finished reconstructing.

**Comment by jingxu97** [comment]
Talked with @jsafrane offline, come up with a solution which combines both #60888 and #61071.
The proposal still follows the idea of
1. If pod is added to desired state (no matter whether it might be removed soon or not), do not reconstruct directly (reconstruction does not has the full information which might fail or cause problem having wrong information since there is not enough checking), instead reconcile should have a chance to reconcile actual state by going through the volume set up process.
2. Only if the pod was force deleted from API server during kubelet down, reconciler tries to clean up mounts directly if possible.

The main problem currently is that pod might be deleted from desired state before reconciler updates the actual state.   #61071 is trying to prevent of this. #60888 makes sure that reconciler can update the actual state as soon as possible.

**Comment by gnufied** [comment]
@jberkus @saad-ali @childsb please add this to 1.10 milestone. This should be a 1.10 blocker.

**Comment by jberkus** [comment]
SIG-leads, please confirm, thanks!

**Comment by jberkus** [comment]
Adding to 1.10 as blocker per @saad-ali

**Comment by saad-ali** [comment]
I spoke with @jingxu97 offline. The volume reconstruction work (PR https://github.com/kubernetes/community/pull/1601) is non-critical but touches critical mount/unmount code paths. While the PRs that @jsafrane and @jingxu97 have (https://github.com/kubernetes/kubernetes/pull/61071 and https://github.com/kubernetes/kubernetes/pull/60888) may resolve the issue identified here, I'm afraid there may be other regressions introduced that we are not aware of. Therefore, I'm asking Jing to revert the volume reconstruction PR. We can reintroduce it along with the patches early in 1.11 along with more extensive testing.

Unfortunately, because changes went in on top, an automatic revert is not possible. Jing is working on a manual revert. @gnufied could you please help test her revert PR when it is ready?

**Comment by saad-ali** [comment]
Update on this issue: @jingxu97 spent the morning trying to create a revert PR https://github.com/kubernetes/kubernetes/pull/58177, but it turns out a couple of other big refactors (including https://github.com/kubernetes/kubernetes/pull/56454) went in on top of her volume reconstruction PR, making it much more difficult to revert.

At this point says she can either spend more time backing out her changes and, in doing so, possibly introduce new bugs or spend time making sure the proposed fixes are rock solid. She says she feels confident that the bugs are understood, and the proposed PRs fixing it should be sufficient, and would like to spend time to double and triple checking it with @gnufied instead. So @jingxu97 and @gnufied will proceed with this.

**Comment by dims** [comment]
@saad-ali i support this approach 👍

**Comment by jdumars** [comment]
I support this as well. Thank you @jingxu97 and @gnufied for working on this.

**Comment by gnufied** [comment]
okay I integrated both the PRs in a branch and tested both on AWS and GCE . Ran e2e tests as well and it looks all good.

**Comment by gnufied** [comment]
I lied about e2e test run. A second run surfaced some failures:

```
• Failure in Spec Setup (BeforeEach) [405.746 seconds]
[sig-storage] PersistentVolumes[Disruptive][Flaky]
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/utils/framework.go:22
  when kubelet restarts
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/persistent_volumes-disruptive.go:196
    Should test that a file written to the mount before kubelet restart is readable after restart. [BeforeEach]
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/persistent_volumes-disruptive.go:235

    Pod "pvc-tester-dpqhx" timed out waiting for phase: Running
    Expected error:
        <*errors.errorString | 0xc420053570>: {
            s: "timed out waiting for the condition",
        }
        timed out waiting for the condition
    not to have occurred

    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/persistent_volumes-disruptive.go:267
------------------------------
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS

[sig-storage] PersistentVolumes[Disruptive][Flaky]
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/utils/framework.go:22
  when kubelet restarts
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/persistent_volumes-disruptive.go:196
    Should test that a volume mounted to a pod that is deleted while the kubelet is down unmounts when the kubelet returns. [BeforeEach]
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/persistent_volumes-disruptive.go:235

    Pod "pvc-tester-j7bnc" timed out waiting for phase: Running
    Expected error:
        <*errors.errorString | 0xc420053570>: {
            s: "timed out waiting for the condition",
        }
        timed out waiting for the condition
    not to have occurred

    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/persistent_volumes-disruptive.go:267
------------------------------
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
------------------------------
```

**Comment by jingxu97** [comment]
@gnufied the error message indicates the pods failed to enter running condition. I think my fix should not affect pod creation.

**Comment by gnufied** [comment]
@jingxu97 yeah I agree. I noticed that these tests use NFS based PVs which are not ideal source for testing the bug we are trying to reproduce.  In this case the NFS server itself may not start correctly and hence the test may fail. 

I am looking into refactoring the test suite, so as it can use GCE/EBS sources as well.

**Comment by gnufied** [comment]
I created a follow up issue for creating the disruptive e2e tests so that bugs like these can be more easily caught - https://github.com/kubernetes/kubernetes/issues/61150 . Will follow up with PR tomorrow.

**Comment by jdumars** [comment]
@gnufied thanks for your work here. How did it come out?

**Comment by gnufied** [comment]
@jdumars we still have some problems that needs to be addressed for https://github.com/kubernetes/kubernetes/pull/61071 . I will sync up with @jingxu97 is online.

**Comment by jdumars** [comment]
Perfect, thank you.

**Comment by gnufied** [comment]
@jdumars can we keep it open, we still need the second PR

**Comment by jberkus** [comment]
re-opening per @gnufied

**Comment by gnufied** [comment]
The second PR got merged late night yesterday as well. So we can close this.

/close
