### ISSUE TITLE
APIService: caBundle should (optionally?) be a pointer to an out-of-band ConfigMap/Secret

### ISSUE THREAD

**Issue by anguslees** [kubernetes/kubernetes#60690]
As it stands (apiregistration.k8s.io/v1beta1), it's very hard to declaratively install an apiserver since you need to create the CA keypair/certificate *before* specifying the APIService.

It would be nice if the APIService instead pointed to an external ConfigMap (or maybe Secret, although I acknowledge that the caBundle contents are not secret), so that an in-cluster controller of some sort could generate the CA material asynchronously.

/sig api-machinery

**Comment by anguslees** [comment]
I guess what I'm saying is that I disagree with the "I don't see why it would be easier" conclusion of the basically duplicate issue #45144 :P

The issue with the current schema is that the APIService registration is static information from a chart/upstream-manifest/whatever, whereas the caBundle needs to vary for every install.  Because of this, the provenance of the two parts of the registration is *always* different, and it is much easier to automate this if they are represented as two separate resources (and thus covered by separate RBAC rules, etc).

Right now an installer tool needs to *also* generate CA and keys (which eg kubectl is a long way from being able to do), or an in cluster operator/initializer needs to *also* be able to create the APIRegistration (which sounds like a scary permission to grant to something in-cluster).  Each of these is a far simpler problem when they are allowed to be solved separately.

**Comment by lavalamp** [comment]
Why is there a need to permission the ca data differently from the rest of the object? It is not sensitive.

**Comment by anguslees** [comment]
As I was describing above, the provenance of the data is different (for a self-hosted api service).  The workflows _writing_ the two (conceptual) parts of the APIService information are different, and (with the existing schema) I need a weaker RBAC security policy in order to allow one part of that workflow to potentially also write to the output of the other part.

As a specific example: I want to automate the install of an apiserver (service-catalog).

Since this requires generating unique self-signed TLS keys, this can't be done with any reproducible/idempotent process like a naive `kubectl apply`, ksonnet, etc.  So I need to use some sort of in-cluster "bootstrapping" process (init containers/controller/whatever) to create the TLS keys - which is fine!.
What is _less fine_ is that this in-cluster bootstrapping process can't just write a CA bundle to a dedicated Secret/ConfigMap, but _instead_ needs to actually create/update the APIService resource itself. Because of this, my init process has to be a) specific to APIService, and not a reusable TLS-signing service like cert-manager or k8s CSR requests, and b) my init process serviceAccount needs to be able to create/update APIService objects, which (if compromised) allows it to do more terrible things to my cluster than just provide broken TLS material.

To be clear, it's all _possible_ with the current all-in-one APIService object, it would just be _better_ if the caBundle was separate :stuck_out_tongue:

**Comment by lavalamp** [comment]
I'd like to see what @deads2k or @liggitt think about that.

My initial thought is that some part of your system is writing the APIService resource and will be priviledged, and it's not obvious to me why adding the ca setup code to that thing makes it more dangerous. I can imagine ways of doing it where this is more true or less true, but I don't see a compelling reason to do it in one of the latter ways, esp. given that this is how the system works and a change would take at least 2 releases (aggregation is GA now).

**Comment by deads2k** [comment]
I don't think that pointing to references is a good idea.  You would either have a fixed one (which wouldn't solve this use-case) or you'd be trying to reference a location that something less trusted can write to.  The most "obvious" choice is the namespace of the service itself, but that's a bit like trusting a process to self-mutate it's own configuration.  If you're willing to trust the process to provides it's on CA, you could just as easily have it mutate its APIService.  The cluster-admin creates an impossible one first (a cert you generated and destroyed the key for as one possible way) and then grant update permissions **for a specific apiservice that it is managing**.

I think that instead of that, I'd focus on creating a thing that can produce serving certificates for you that the cluster-admin could configure a default bundle and configure the default.

Making a required field optional is a thing we can do in the API, so allowing nil and secure is a valid change.  It's not obvious how this proposal is better than existent alternatives available today.

**Comment by liggitt** [comment]
> allowing nil and secure is a valid change

that's already allowed by API validation, we could (and should) mark the caBundle field optional so openapi is accurate

**Comment by deads2k** [comment]
> that's already allowed by API validation (uses system trust roots if caBundle is omitted), we could (and should) mark the caBundle field optional so openapi is accurate

sounds like this use-case is already possible.

**Comment by anguslees** [comment]
ok, so I think we're saying I should write an apiservice-bootstrap controller that takes an APIService template (via CRD, or a oneshot job with command line flags), creates the self-signed TLS keys, and then outputs a Secret for the serving job, and creates the completed APIService resource (including caBundle).

That feels like more special-case work than should be required just to authenticate a k8s endpoint to the same cluster, but I understand that we have to work within the API that we have.  I'll close this bug, but please followup with any other comments to my above plan.

**Comment by munnerz** [comment]
This is burning me a bit as I am now trying to automate the deployment of a ValidatingWebhookConfiguration resource for cert-manager itself 😅 

In order to workaround these issues, as @anguslees has suggested, I have created a small tool that sets `caBundle` fields on a few different core k8s resource types (APIService, *WebhookConfiguration): https://github.com/munnerz/apiextensions-ca-helper

This works okay, but is far from ideal. If the Secret resource changes, or if the APIService resource is updated out-of-band, I have to trigger a re-run of the tool.

The only alternative I can think of right now is to require users generate their own initial root CA so that its certificate can be templated into the *WebhookConfiguration resources at deploy time. This is a bit painful for end-users in my mind, and I wish there were some cleaner way to do it 😬.

Could this be a use-case for a polymorphic 'caBundle' subresource (similar to the `scale` subresource?). If we could define some kind of endpoint to post a certificate bundle to, we'd get the benefit of finer-grained RBAC permissions (plus this idea seems to support @lavalamp's statement above: `Part of the point of the Kubernetes API is to make it possible / easy for separate workflows to own separate parts of an object.`)

**Comment by anguslees** [comment]
Grumble, grumble.  I note there's now a chapter in the kubebuilder docs detailing the steps required to workaround this issue :(
 https://book.kubebuilder.io/cronjob-tutorial/cert-manager.html

**Comment by dims** [comment]
long-term-issue (note to self)
