### ISSUE TITLE
Custom immortals namespaces to NamespaceLifecycle admission controller

### ISSUE THREAD

**Issue by rsaraiva** [kubernetes/kubernetes#60733]
/kind feature

**What happened**:
`NamespaceLifecycle` do not permit to add custom namespaces to prevent deletion. We have differents environments (e.g. `dev` and `prod`) and we occasionally switch between `kubernetes` and `minikube`. Custom immortals namespaces could help us to avoid human mistakes. 

**What you expected to happen**:
`NamespaceLifecycle` could accept a configuration file like `PodNodeSelector`.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create NS
2. Create a pod.
3. Delete NS

**Anything else we need to know?**:
We found [this code](https://github.com/kubernetes/apiserver/blob/master/pkg/admission/plugin/namespace/lifecycle/admission.go#L56) that has the 3 hard coded immortals namespaces.

As it is a feature request I'm able to contribute with some PRs.

**Comment by rsaraiva** [comment]
@kubernetes/sig-apps-feature-requests

**Comment by liggitt** [comment]
this is not intended to be a general purpose deletion prevention mechanism. the only reason `kube-system` is protected at that level is because the controllers responsible for namespace cleanup are associated with that namespace, and deleting it could put a cluster in a state that could not self-recover.

if you want to prevent deletion of other namespaces, I'd suggest a custom webhook admission plugin - https://kubernetes.io/docs/admin/admission-controllers/#validatingadmissionwebhook-alpha-in-18-beta-in-19

/close
