### ISSUE TITLE
[job failed] 1.9-master upgrade|downgrade jobs

### ISSUE THREAD

**Issue by krzyzacy** [kubernetes/kubernetes#60764]
this is an unbrella issue for k8s-testgrid.appspot.com/sig-release-master-upgrade

there are multiple test failures, and I will open individual issues for each failing test

/priority failing-test
/priority critical-urgent
/kind bug
/status approved-for-milestone
/sig cluster-lifecycle
/sig gcp

cc @jdumars @jberkus 
and also cc @krousey who's our upgrade expert

**Comment by krzyzacy** [comment]
cc @kubernetes/sig-cluster-lifecycle-bugs 
I think sig-cluster-lifecycle want to triage the downgrade suite which is timing-out on downgrading
/assign @roberthbailey @luxas @lukemarsden @jbeda
assign you folks for now, please reassign as appropriate

**Comment by krousey** [comment]
Downgrades are failing to delete the stateful set test's namespace because PVCs remain. All the other tests are actually passing.

**Comment by krzyzacy** [comment]
@krousey do you know who I need to bug next?

**Comment by krousey** [comment]
In particular: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-master-new-downgrade-cluster-parallel/1910

```
I0305 18:18:01.917] STEP: Destroying namespace "e2e-tests-sig-apps-statefulset-upgrade-86ffb" for this suite.
I0305 18:28:01.928] Mar  5 18:28:01.928: INFO: Waiting up to 30s for server preferred namespaced resources to be successfully discovered
I0305 18:28:02.233] Mar  5 18:28:02.233: INFO: namespace: e2e-tests-sig-apps-statefulset-upgrade-86ffb, resource: bindings, ignored listing per whitelist
I0305 18:28:02.237] Mar  5 18:28:02.236: INFO: namespace: e2e-tests-sig-apps-statefulset-upgrade-86ffb, resource: persistentvolumeclaims, items remaining: 3
I0305 18:28:02.244] Mar  5 18:28:02.243: INFO: namespace: e2e-tests-sig-apps-statefulset-upgrade-86ffb, DeletionTimetamp: 2018-03-05 18:18:01 +0000 UTC, Finalizers: [kubernetes], Phase: Terminating
I0305 18:28:02.246] Mar  5 18:28:02.246: INFO: namespace: e2e-tests-sig-apps-statefulset-upgrade-86ffb, total namespaces: 12, active: 11, terminating: 1
I0305 18:28:02.249] Mar  5 18:28:02.249: INFO: Couldn't delete ns: "e2e-tests-sig-apps-statefulset-upgrade-86ffb": namespace e2e-tests-sig-apps-statefulset-upgrade-86ffb was not deleted with limit: timed out waiting for the condition, namespaced content other than pods remain (&errors.errorString{s:"namespace e2e-tests-sig-apps-statefulset-upgrade-86ffb was not deleted with limit: timed out waiting for the condition, namespaced content other than pods remain"})
```

**Comment by krousey** [comment]
@krzyzacy We should pull in someone from storage and maybe someone from apps.

**Comment by krzyzacy** [comment]
/sig storage
/sig apps

cc @kow3ns @saad-ali ^^

**Comment by jdumars** [comment]
@kow3ns @saad-ali any update on this?

**Comment by krzyzacy** [comment]
cc @msau42 @verult  @janetkuo 
cc more folks to see if you have any idea here

**Comment by saad-ali** [comment]
@verult has agreed to take a look at the failing Storage tests.

**Comment by jdumars** [comment]
Thank you very much!

**Comment by verult** [comment]
Update: my hypothesis is the failure is due to PVC Protection going to beta this release. In 1.10, a PVC contains a PVC protection finalizer while a pod is using it. After cluster downgrade, this finalizer is no longer recognized, so the PVC can never be deleted.

**Comment by jberkus** [comment]
@krousey @krzyzacy I've pinged sig-apps and sig-storage.

However, that sounds to me like a bug in the test, not in the code.  I mean, PVCs aren't supposed to be deleted when their statefulset is dropped.  They are *supposed* to hang around.  Or am I misunderstanding the fail?

**Comment by verult** [comment]
/cc @caesarxuchao @childsb @jsafrane 

If my hypothesis is correct, this is a real 1.10 -> 1.9 downgrade issue.

**Comment by verult** [comment]
Sorry @jberkus didn't see your comment until now. The test is failing because it got stuck waiting for namespace (and all of the associated namespaced resources, including PVC) to be deleted as part of the cleanup routine.

**Comment by jberkus** [comment]
Oh, got it, and then there's the protection.

So, this sounds like a real bug, but not a release-blocker?  PVC protection isn't on by default, is it?

**Comment by verult** [comment]
It's in beta for 1.10, so it's on by default unfortunately. But do we handle beta features differently?

I'll look into other tests as well to verify my hypothesis. It's interesting other tests (like the PersistentVolumeUpgradeTest) didn't catch this problem.

**Comment by jberkus** [comment]
No, I mean is it on by default for all PVCs?

**Comment by jdumars** [comment]
I'd like some more opinions on this. If it's on by default and usage-impacting, I am inclined to consider it release-blocking. Either way, we need all hands on deck for this ASAP.

**Comment by verult** [comment]
I'm not familiar enough with the feature to say for certain, but I believe it's on by default for all PVCs. @childsb @jsafrane could you verify?

**Comment by verult** [comment]
The PersistentVolumeUpgradeTest failed with the same error:
```
I0305 18:29:09.881] [1mSTEP[0m: Destroying namespace "e2e-tests-persistent-volume-upgrade-sig-storage-rjbz9" for this suite.
I0305 18:39:09.900] Mar  5 18:39:09.900: INFO: Waiting up to 30s for server preferred namespaced resources to be successfully discovered
I0305 18:39:10.045] Mar  5 18:39:10.045: INFO: namespace: e2e-tests-persistent-volume-upgrade-sig-storage-rjbz9, resource: persistentvolumeclaims, items remaining: 1
I0305 18:39:10.077] Mar  5 18:39:10.077: INFO: namespace: e2e-tests-persistent-volume-upgrade-sig-storage-rjbz9, resource: bindings, ignored listing per whitelist
I0305 18:39:10.084] Mar  5 18:39:10.083: INFO: namespace: e2e-tests-persistent-volume-upgrade-sig-storage-rjbz9, DeletionTimetamp: 2018-03-05 18:29:09 +0000 UTC, Finalizers: [kubernetes], Phase: Terminating
I0305 18:39:10.087] Mar  5 18:39:10.086: INFO: namespace: e2e-tests-persistent-volume-upgrade-sig-storage-rjbz9, total namespaces: 8, active: 6, terminating: 2
I0305 18:39:10.090] Mar  5 18:39:10.089: INFO: Couldn't delete ns: "e2e-tests-persistent-volume-upgrade-sig-storage-rjbz9": namespace e2e-tests-persistent-volume-upgrade-sig-storage-rjbz9 was not deleted with limit: timed out waiting for the condition, namespaced content other than pods remain
```

I'm not sure if this is something that could be fixed in Kubernetes core. Question for sig/cluster-lifecycle: what's the usual solution for migration API objects from one version to another, and if such solution exists, does it live in the kubernetes/kubernetes repo? i.e. is it a release blocker?

**Comment by jsafrane** [comment]
Trying to rephrase the problem in my own words: PV/PVC protection is on by default in 1.10 and it's off by default in 1.9. If you have 1.10 cluster with a PVC, it gets a finalizer when it's created (via admission plugin). The finalizer is removed by a protection controller when it's safe to delete the PVC. When you downgrade 1.10 to 1.9, the controller won't be enabled and nobody removes the finalizer -> PVCs are not deleted -> this bug.

I am not sure what's correct way out of this. Something must remove the finalizer on downgrade.

**Comment by jdumars** [comment]
Should this be a known issue and not be part of the downgrade suite? There some actions that simply don't lend themselves to downgrade without intervention.

**Comment by gnufied** [comment]
The only possible way is when we downgrade the cluster to 1.9.x then the PV/PVC protection feature must be enabled for finalizer to be deleted (so as PVC can be deleted). We will have to perhaps document this somewhere.

**Comment by krousey** [comment]
Another option is to disable the admission controller for 1.10, but leave
the controller that removes the finalizers. Then enable the admission
controller in the next release.

I'm not saying it's a good option, but it is a way to gracefully introduce
a feature like this.

**Comment by jberkus** [comment]
So, recommendation from SIG-Release per Mar. 13 burndown meeting:

1. Document steps for manually removing finalizers on downgrade;
2. add a Known Issue on this with link to steps;
3. add finalizer removal to the test.

Starting a slack thread involving all parties on this issue, as well as sig-storage and sig-lifecycle leads to finalize this solution.

**Comment by saad-ali** [comment]
Can we get owners for each of these tasks.

**Comment by pospispa** [comment]
I agree with @jsafrane 's [description of the problem](https://github.com/kubernetes/kubernetes/issues/60764#issuecomment-372624533)
I agree with [the proposed recommendation](https://github.com/kubernetes/kubernetes/issues/60764#issuecomment-372754234) by @jberkus

**Comment by rootfs** [comment]
dropping  StorageObjectInUseProtection admission controller plugin and patch pvc can remove the finalizers:
Test was done using the following flow:

- disable `StorageObjectInUseProtection` and restart apiserver
- kubectl patch pvc `pvc-name` -n `pvc-namespace` --type=json -p='[{"op": "remove", "path": "/metadata/finalizers"}]' 
- verify the pvc no longer has finalizers

**Comment by pospispa** [comment]
I completely forgot to mention that there is very similar issue with PVs as with PVCs.

Let me sum up the `StorageObjectInUse` feature development:
1. K8s 1.9 PVC Protection is in alpha. PVC Protection adds finalizers to PVCs.
2. K8s 1.10 PVC Protection goes to beta, PV Protection is added and goes directly to beta and the feature is renamed to `StorageObjectInUseProtection`. So finalizers are being added to boths PVs and PVCs in K8s 1.10 by default.

That's why I think we should have also problem deleting PVs after downgrade from K8s 1.10 to K8s 1.9. Interestingly no tests failed because of not being able to delete a PV protected by a finalizer.

After downgrade to K8s 1.9 finalizer from PVs must be deleted manually as there's no controller in K8s 1.9 that would delete finalizers from PVs.

**Comment by verult** [comment]
Another related concern is when the beta feature gate is turned off, we run into the same problem of PVCs and PVs not getting deleted properly. Ideally it should be the controller's duty to make sure feature gates can be turned off cleanly.

It may be worthwhile to add this logic in the `StorageObjectInUseProtection` controller: when the feature gate is off, operate in "finalizer deletion" mode where it scans PVs and PVCs to make sure existing `StorageObjectInUseProtection` finalizers are removed. This would also need to be cherry-picked to 1.9. Credit to @danderson for the idea.

What does everyone think?

**Comment by gnufied** [comment]
This will also require that pvcProtection controller always runs, no matter feature gate is on or off. Currently starting of that controller is feature gated, so as controller does not run if feature gate is off. Allowing controller to always run will be somewhat of a departure from existing practices.

**Comment by verult** [comment]
On the other hand, without it users have to manually delete the finalizers in addition to turning off the feature gate if they wish to disable StorageObjectInUseProtection cleanly

**Comment by danderson** [comment]
Agreed, it's a departure from the "standard" assumption that feature gates just bypass code.

I guess the question is about what feature gates should do: do they bypass new code, or do they turn a feature on/off? If it's the latter, then turning the feature gate off should turn off the feature, _and take explicit action if necessary to make the feature be actually off_.

Some feature gates already do this naturally, e.g. kube-proxy cleans up after itself when you switch different modes on/off. Other feature gates don't require explicit cleanup, so "just bypass this codepath" is the correct way to turn the feature back off.

In this case, turning the feature off requires explicit action to unwedge the cluster state. In alpha, it's okay to say that it's the user's problem to do this. But I believe that in beta, this is no longer acceptable, and rolling back should get you back to a working cluster with no further action.

WDYT?

**Comment by danderson** [comment]
For context, I'm with GKE SRE, and my specific concern is this: when we make 1.10 available for use in GKE, customers expect the ability to roll forward and back. So, let's say they roll forward, do a couple of their normal website deploys, kick the tires... And discover a horrible bug that affects their workflow, not related to PVCs.

They correctly decide that they need to roll back to 1.9 until that bug is fixed by a 1.10 patch release. So, they roll back... And now their cluster is wedged in a differently broken state, because PVCs no longer work the same. From the user's perspective, rollback is simply broken here, because it did not roll back to "the way things were before I did the upgrade."

We have options to fix this just for GKE (e.g. run an extra "cleanup PVC finalizers" pod on our controller machines, or disable this feature in GKE), but I think this is actually a more general problem with how Kubernetes does feature rollouts, and expectations about what user journeys should Just Work vs. which ones require intimate knowledge of the current k8s roadmap to work around.

I believe we should fix this in a way that benefits the entire community, rather than roll a private fix for ourselves. I would love to hear how people feel we should address downgrade compat problems like this.

**Comment by saad-ali** [comment]
> I believe we should fix this in a way that benefits the entire community, rather than roll a private fix for ourselves. 

+1 I'm not sure how feasible that will be to do before 1.10 is cut. So we can carry on as planned and pursue this in parallel?

1. Document steps for manually removing finalizers on downgrade from PV and PVC objects.
2. Add a Known Issue on this with link to steps above indicating that PV and PVC objects may not delete if...
3. Add manual finalizer removal to the down grade tests to force them to proceed.

@rootfs I believe is already working on this^^.

And in parallel:
1. Modify the `pvcProtection` controller to run in finalizer deletion only mode if disabled.
2. Remove the manual finalizer removal from the downgrade tests to verify this fixes the downgrade issue.

@pospispa can you work on this^^?

**Comment by danderson** [comment]
@saad-ali To be clear, the "in parallel" point 1, "modify the `pvcProtection` controller"... We would modify it in both 1.10 and 1.9, and make a patch release for both, right? That way we can instruct people "to be downgrade-safe, make sure you're at least on 1.9.X before you upgrade, and downgrade back to 1.9.X if you need to roll back" ?

**Comment by danderson** [comment]
With my GKE hat on: "proceed with caveats on 1.10" sgtm. We can make 1.10 available with a downgrade caveat for early adopters, and delay wider upgrades until we have a clean downgrade path.

What kind of timeline would we be looking at for a 1.9 patch release that includes the `pvcProtection` cleanup-when-disabled change?

**Comment by saad-ali** [comment]
> @saad-ali To be clear, the "in parallel" point 1, "modify the pvcProtection controller"... We would modify it in both 1.10 and 1.9, and make a patch release for both, right? That way we can instruct people "to be downgrade-safe, make sure you're at least on 1.9.X before you upgrade, and downgrade back to 1.9.X if you need to roll back" ?

Right, no reason this behavior can't be included in 1.10.x as well as 1.9.x.

> What kind of timeline would we be looking at for a 1.9 patch release that includes the pvcProtection cleanup-when-disabled change?

@pospispa can you confirm if you can work on this? If so can you provide an eta?

**Comment by pospispa** [comment]
@saad-ali I left Red Hat on Monday and returned company's notebook with K8s development and testing environment.
I've never tried to build and run K8s on my home computer that may not be good enough for this purpose. So I can't provide any ETA.
I plan to try to build and run K8s on my home computer tomorrow.

**Comment by saad-ali** [comment]
Thanks for the update @pospispa! Please let us know know ASAP if you're able to work on modifying it. If you are not, @rootfs has volunteered to pick up that work as well.

**Comment by verult** [comment]
Adding the controller logic might be simpler than adding the temporary fix to the downgrade test - something to consider if the test fix isn't near completion yet.

**Comment by rootfs** [comment]
adding temporary workaround in the e2e test itself to force remove the finalizers is more complicated than fixing the problem

**Comment by verult** [comment]
In that case my opinion is to focus on the fix. Regarding whether a feature gate should "bypass new code" or "turn a feature on/off": choosing the former in this case means the system could potentially be left in a bad state, and there should be an automated system in Kubernetes to clean up, either in the controller or elsewhere. Implementing this in the controller might be the easiest.

**Comment by jdumars** [comment]
@verult @rootfs @saad-ali given how little time is left in this release cycle, I need all of your help to decide and act on a course forward. My concern about fixing the issue in 1.10 is that it could insert unknown risks that will have very little soak time. If the fix is low-impact, low-risk, that seems reasonable.  Otherwise, it might be prudent to have an advisory for 1.10 and a fix in 1.10.1  Please advise, and let me know who is stepping up to do the work. 

Thank you all for your attention on this!

**Comment by pospispa** [comment]
@saad-ali I'm actively working on this. So far I've created PR https://github.com/kubernetes/kubernetes/pull/61282

**Comment by saad-ali** [comment]
Thanks @pospispa!! Let us know when it is ready to review.

@jdumars:

The advisory must still go out! So we must still do the following for the 1.10 release:

1. Document steps for manually removing finalizers on downgrade.
2. Add a Known Issue on this with link to steps.

@rootfs is working on these steps.

The only open question is about:

* Add manual finalizer removal to the down grade tests to force them to proceed.

This step is only required to make the downgrade tests green. But based on what @rootfs said doing so is non-trivial. Because we understand the root cause of the issue and have mitigated it with the advisory in the release notes, I suggest this should not be a blocker and we can ship with that test red if the test is not fixed.

In the mean time, independent of the 1.10 release, we will continue the effort to update the controller to handle this more gracefully (these are not 1.10 release blockers):

3. Modify the pvcProtection controller to run in finalizer deletion only mode if disabled.
4. Remove the manual finalizer removal from the downgrade tests (if they end up getting added) to verify this fixes the downgrade issue.

@pospispa is already working on this @rootfs will help review.

Hope that clears things up.

**Comment by pospispa** [comment]
@saad-ali @rootfs let me sum up options I can think of.

Option A

In K8s 1.10:
1. Document steps for manually removing finalizers on downgrade from PV and PVC objects.
2. Add a Known Issue on this with link to steps above indicating that PV and PVC objects may not delete if...
3. Add manual finalizer removal to the down grade tests to force them to proceed.

In K8s 1.9 before K8s 1.10 release:
1. Modify the `pvc-protection-controller` to run in finalizer deletion only mode if disabled.
2. Backport `pv-protection-controller` to run in finalizer deletion only mode if disabled.
3. Remove the manual finalizer removal from the downgrade tests to verify this fixes the downgrade issue.

In K8s 1.10 before K8s 1.11 release:
1. Modify the `pvc-protection-controller` to run in finalizer deletion only mode if disabled.
2. Backport `pv-protection-controller` to run in finalizer deletion only mode if disabled.

***

Option B

In K8s 1.10 before it's release:
1. Return `StorageObjectInUseProtection` feature from beta back to alpha.

***

I'm currently working on Option A. However, Option B seems a better option to me now.

@saad-ali @rootfs please, what do you think?

**Comment by saad-ali** [comment]
> Because we understand the root cause of the issue and have mitigated it with the advisory in the release notes, I suggest this should not be a blocker and we can ship with that test red if the test is not fixed.

I spoke with the release team and there feedback is that the test not being green blocks other tests from running, which means that it might mask other issues. Therefore getting the test green must remain a requirement for 1.10.

@pospispa summarized this well! Option A is a lot of work and is jeopardizing the release. Option B is the path of least resistance, it means we keeping this feature in alpha, and delay moving it to beta until next quarter. I am fine with option B. @childsb @jsafrane @rootfs thoughts?

**Comment by saad-ali** [comment]
> I'd expect our priority to be protecting people's data. That would make me lean toward enabling PVC protection in 1.10 and documenting how to go about deleting PVs created in 1.10 if you downgrade to 1.9.

Since it is a requirement to get a green signal from the downgrade test, in order to ship (even with just an advisory) we would need to at least fix the test as proposed step 3 of option A, but according to @rootfs doing so is non-trivial. 


Considering we've lived without object protection until 1.9, delaying it one more release vs risking the release shipping causes me to lean towards option B.

**Comment by danderson** [comment]
I would concur with delaying PVC protection. In my opinion, documenting that downgrades require manual intervention is a failure condition, and we should only be doing that when left with no other choice. This is especially true when the choice is between graduating an alpha feature, or breaking "just works" downgrades.

Downgrades are only executed by users who are already desperate, e.g. because 1.10 was horribly broken for them somehow. Landing them in a situation where they rollback and have a differently broken cluster that they need to debug is an awful user experience, and sends the message that k8s cannot be depended on.

In my perfect world, I would like to ship 1.10 with option A, since that's the best of both worlds... Assuming we have any soak time left. In the absence of that, I feel we should "fail safe" and err on the side of not graduating a new feature that breaks supported workflows.

**Comment by liggitt** [comment]
discussed offline with @saad-ali, @dims, @jberkus, @childsb 

we are going to pursue a targeted fix to the downgrade test itself to encode the documented approach of removing the 1.10-added finalizer from pv and pvc objects after downgrading to 1.9.

> I would concur with delaying PVC protection. In my opinion, documenting that downgrades require manual intervention is a failure condition

The PVC protection feature is important to prevent PV corruption by enforcing deletion order between Pods and PVCs. To be clear, downgrading works fine. Intervention is required to complete deletion of a PV/PVC after downgrading (it fails safe)

**Comment by krousey** [comment]
I disagree that this is preventing other tests from running. I only see evidence of a timeout on the downgrade step and leaked disks due to this issue. I do not see a timeout in the test suite that follows the downgrade. I see

```
I0316 17:06:11.193] Ran 354 of 786 Specs in 727.020 seconds
I0316 17:06:11.197] SUCCESS! -- 354 Passed | 0 Failed | 0 Pending | 432 Skipped 
```
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-master-new-downgrade-cluster-parallel/2040

All the downgrade tests actually pass too. It's just the automated namespace cleanup that fails for this. It seems that everything is being run and the only red in this dashboard is directly attributable to PVC protection. https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gce-master-1.9-downgrade-cluster-parallel&sort-by-failures=

Is there something else blocking?

**Comment by krzyzacy** [comment]
ah, @krousey you are right

```
W0316 16:54:02.107] 2018/03/16 16:54:02 process.go:150: Running: ./hack/e2e-internal/e2e-status.sh
W0316 16:54:02.150] Project: k8s-jkns-gce-ubuntu-1-6-slow
W0316 16:54:02.150] Network Project: k8s-jkns-gce-ubuntu-1-6-slow
W0316 16:54:02.150] Zone: us-central1-f
I0316 16:54:02.337] Client Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.5-beta.0.43+904135993a855c", GitCommit:"904135993a855c7bd88a52fa4349a57ecd9e8922", GitTreeState:"clean", BuildDate:"2018-03-16T10:27:08Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
I0316 16:54:02.338] Server Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.5-beta.0.43+904135993a855c", GitCommit:"904135993a855c7bd88a52fa4349a57ecd9e8922", GitTreeState:"clean", BuildDate:"2018-03-16T09:58:46Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

looks like the cluster was successfully downgraded - (I was under the impression `cluster downgrade should maintain a functioning cluster` was a hard fail that will affect the cluster functionality)

**Comment by danderson** [comment]
> The PVC protection feature is important to prevent PV corruption by enforcing deletion order between Pods and PVCs

All new features are important to some section of the userbase, otherwise we wouldn't be building them. I'm worried that this is being used repeatedly (not specific to this issue) to justify pushing toil onto the users of Kubernetes.

With that said, if that's the concerted decision of the people here, I'll bow out and go figure out what we can do to make this experience better on GKE.

**Comment by krousey** [comment]
@danderson I think the plan is to document this and bandaid the test for 1.10 so they can get test signal. I think they still plan to pursue a proper patch fix to 1.9 and 1.10 to clean up these finalizers when the feature is disabled.

@liggitt @saad-ali @dims @jberkus @childsb Is that correct?

**Comment by saad-ali** [comment]
> @liggitt @saad-ali @dims @jberkus @childsb Is that correct?

That is correct. That said, we will likely end up disabling this feature on GKE until the automatic clean up of finalizers is available in 1.9.x and 1.10.x releases.

**Comment by verult** [comment]
I believe the core logic of the controller fix is very similar to the logic added to the downgrade test; the biggest difference is finalizers need to be checked periodically (or event-based) rather than just once. Is this correct? If this is the case, I would argue the amount of risk in adding the fix to 1.10 is fairly low. I agree with the current plan, but if time allows I think it's reasonable to add the fix in both 1.9 and 1.10 before the release.

**Comment by pospispa** [comment]
ACK.  Waiting on reviews and approvals (PRs https://github.com/kubernetes/kubernetes/pull/61282 and https://github.com/kubernetes/kubernetes/pull/61316)
ETA: depends on reviews and approvals
Risks: N/A

**Comment by pospispa** [comment]
> In K8s 1.10 before K8s 1.11 release:
> 1. Modify the pvc-protection-controller to run in finalizer deletion only mode if disabled.
> 2. Modify pv-protection-controller to run in finalizer deletion only mode if disabled.

I've created PR https://github.com/kubernetes/kubernetes/pull/61324 for the above.

**Comment by jberkus** [comment]
@krzyzacy @childsb @saad-ali where are we on this?  I thought we had a plan, and it was executed, and the remaining open PRs were for the future 1.9 patches.   What's waiting to be done so that we can move this issue out of the milestone?

**Comment by liggitt** [comment]
1.9 PR was merged in #61370 mid-day yesterday. four green runs since then on https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gce-master-1.9-downgrade-cluster-parallel&sort-by-failures=

**Comment by liggitt** [comment]
some tests are still flaking in the job, but no solid red tests

**Comment by krzyzacy** [comment]
I think we can close this issue, and I'll keep an eye there and open a few more flake issues
