### ISSUE TITLE
PODs Request/Limits in Hz for workaround case with non heterogeneous processors in cluster

### ISSUE THREAD

**Issue by Nefelim4ag** [kubernetes/kubernetes#60787]
/kind feature

The problem:
We have not heterogeneous cluster with several types of Xeon CPUs and different speed.
That leads to some scheduling problems where cpu 200m on one server != 200m other.
Currently we maintain some duck tapes to beat that.

May be that make a sense to add a general feature that can scale cpu capacity based on cpu speed?

i.e. example:
set per cluster 2 GHz as 100%, and then count cpu with 1.8 Ghz, as 0.9 CPU and cpu with 3 GHz as 1.5 CPU.

& etc.

That make a sense?

Thanks.

**Comment by resouer** [comment]
This does not sound like a default behavior for kube-scheduler. Could you workaround it by using request/limit with node selector?

**Comment by Nefelim4ag** [comment]
@resouer,
That's will not work as expected i think.
i.e. example:
Let's assume we have a cluster like youtube which decode/encode video to different scale.

We buy some CPU's with 1.8Ghz, which process videos.
Assume that stateless deployment app which scale down 1080p to 720p, will constantly use 250m. So we can set cpu request limit on pod 250m.
We scale-out server park, buy new servers and all works good enough.
But after some time we buy "new" more powerful/effective servers (i mean with new/different CPU) which can convert video with cpu usage like 200m.

So if i use the same deployment and just scale-out it, i will hit a problem, because new servers will be underutilized by 20%.
Because requests CPU usage what i set was 250m for that deployment.

You can replace video converting with something else, i hope i explain the problem.
That problem need some workarounds =\
 - - -
TIP: I think that https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#extended-resources can help address that problem.

**Comment by embano1** [comment]
> So if i use the same deployment and just scale-out it, i will hit a problem, because new servers will be underutilized by 20%.
Because requests CPU usage what i set was 250m for that deployment.

I don't see a problem here. Since you do **not** specify MHz in the cpu spec, but relative core values (e.g. 200m = 0.2 of a core, no matter how fast it is) the scenario you describe would not lead to stranded resources. 

The scheduler does not track MHz/GHZ, but rather cpu cores as reported by `node.allocatable`. So in your case the pods on the new (faster) hardware would ran faster. 

Did I understand you correctly?

**Comment by Nefelim4ag** [comment]
@embano1, they will run faster, but i mean that we set
cpu 250m request in deployment.

So on old hardware all will work fine, but on new HW, we get a underutilization by that.

i.e. i mean 200/250 as cpu usage, and in same time 250 as a bare minimum in example to successful run of pod.

**Comment by embano1** [comment]
Sorry, now I understood the real problem you describe :) In my words: dynamically configure `requests.cpus` based on the hw (cpu speed), e.g. fractions, right?

Please let me ask: why not just go with a "good enough" value for your systems and let jobs finish faster on newer hardware? The new hw node wouldn't really by underutilized, because it's using 25% core_mhz, finishing faster and freeing up the cycles again for new jobs. 

Just trying to understand the need for an API change.

**Comment by Nefelim4ag** [comment]
@embano1, because it's just example, but that also possible to have a same case with pods, nod jobs.

To not very change example topic, look at that as some television.
i.e. App that doing video re-translation from A to B and do some work with that video, as example apply "Gryffindor Sign" at right bottom corner.

Or as example monitoring app, which do some math's on some input data from various stable sources. Like cloud manager for Smart Home.
It will use cpu constantly most, and cpu usage will depends on CPU speed.
 - - -
May be a bad example, but VMware in vSphere have mostly same concept, and not restrict on cpu time, but on Hz used. i.e. operator can set limit/reservation to 500 Mhz.
 - - -
P.S.
I think that looks like basic idea implementation.
https://github.com/kubernetes/kubernetes/pull/39950

**Comment by dinfyru** [comment]
/reopen
I also need `node capacity based on GHz`
