### ISSUE TITLE
Node upgrades: graceful node evacuation

### ISSUE THREAD

**Issue by mbforbes** [kubernetes/kubernetes#6080]
See issue #6079 as the roll-up for node upgrades.

This extension smartly evacuates nodes before they are downed to be upgraded. Here's a strawman mechanism:
1. Make the node unschedulable so no more pods are placed on it
2. Remove any pods running on the node
3. Remove any storage mounted on the node (or, will these be automatically moved when pods are moved?)
4. Kill the node

**Comment by pmorie** [comment]
@tobarja

**Comment by bgrant0607** [comment]
See also discussion here: https://github.com/kubernetes/kubernetes/pull/14054#issuecomment-144229094

**Comment by bgrant0607** [comment]
Draining nodes has many more uses than just node upgrades, especially on bare metal (repairs, reprovisioning, etc.), so let's keep the draining discussion in #3885 and just discuss the specific use for node upgrades here.

**Comment by davidopp** [comment]
Notes from a brief discussion with @brendandburns today:

Initial version (client-driven):
```
for (each node in sequence) {
    client marks node unschedulable
    client kills pods one at a time (triggering them to get their graceful deletion notice before being forcefully killed), doesn't kill next one until it reschedules
}
```

Things we can do later to make it more sophisticated
* move it to server-side (i.e. somehow tell the server "I want you to shut down machine X" and it does the orchestration itself; the request could be represented by a new field in NodeSpec and handled by node controller, or whatever)
* have the killing respect collection-level SLOs rather than requiring each pod reschedule before moving on to the next one, which would allow us to kill more aggressively (see #12611)

**Comment by davidopp** [comment]
@mikedanese mentioned that a form of this is already available in OpenShift:
https://docs.openshift.com/enterprise/3.0/admin_guide/manage_nodes.html#evacuating-pods-on-nodes

**Comment by davidopp** [comment]
(And the corresponding code is here:
https://github.com/openshift/origin/blob/master/pkg/cmd/admin/node/evacuate.go)

Compared to what I described in the earlier comment, the main differences are
* oadm takes list of nodes on the command line, rather that iterating through all nodes
* oadm checks to make sure the node has already been marked unschedulable, rather than marking the node unschedulable itself
* oadm inserts no delays between killing, either between killing pods on a machine or between machines
* oadm skips (doesn't kill) pods that aren't managed by an RC, unless you use --force option

**Comment by mikedanese** [comment]
oadm evacuation can also select a list of nodes by label.

**Comment by derekwaynecarr** [comment]
I could easily see a delay on killing pods being added in a future
iteration of oadm.  I think the current code base may predate graceful
termination.

**Comment by bgrant0607** [comment]
@davidopp How would node updates be triggered from the client? Without triggering the update, rolling evacuation doesn't make sense.

**Comment by smarterclayton** [comment]
Admins today have mechanism outside to manage update.  If we are explicitly managing update internally, then it's really a different problem.  For instance, our ops teams integrate evacuate with other tools for rotation.  They'd probably need hooks to have a Kube internal flow, especially for IaaS management.  Hence why oadm evacuate is structured for admin control, rather than cluster control

**Comment by davidopp** [comment]
> How would node updates be triggered from the client? Without triggering the update, rolling evacuation doesn't make sense.

Along the lines of what Clayton said, I think you could divide the workflow into multiple pieces. Evacuation prepares the machine for upgrade, and then upgrade can be done via a separate tool.

That said, I put my comment from a few days ago in the wrong issue -- I hadn't seen your comment "let's keep the draining discussion in #3885 and just discuss the specific use for node upgrades here" and really should have put my comments in #3885, not here.

**Comment by bgrant0607** [comment]
cc @mml

**Comment by mml** [comment]
If we're willing to tolerate running this from the command line, it's pretty easy to do a 1-in-flight version using the implementation of `drain` from #16698 

```
for node in $nodes; do
  kubectl drain $node
  # however you trigger updates
  kubectl unlame $node
  # maybe sleep if you like
done               
```  

Assuming we don't have in-place kubelet upgrades, this is a step up from graceless termination.

Do we want to implement > 1 in flight at this time, or are we planning to do in-place kubelet upgrades for 1.2?

**Comment by davidopp** [comment]
@dchen1107 @roberthbailey

**Comment by roberthbailey** [comment]
@mml the way that we do upgrades is a rolling update to a new MIG instance template. Without a lot of machinery on our side (constantly pausing an un-pausing the rolling update) it would be difficult to add the drain / unlame commands at the appropriate times in the upgrade process.

**Comment by mml** [comment]
@roberthbailey Unless we want to drain the whole MIG, we need *some* machinery for coordination.  In the simplest case:  Either the admin is running a kubectl drain loop and as each node drains it tells gcloud to roll one specific instance (AFAICT not an option with the current gcloud API), or GCE needs to drain and wait on each machine in turn.

A more complicated approach could be (see #17393) to have the upgrade process begin by creating a drain and then, as each node is fully drained (it would watch the nodes via the api server), roll the rolling update over the node in question.

**Comment by roberthbailey** [comment]
I talked with some of the instance group manager folks earlier this week and they suggested that we use gce shutdown scripts to have nodes drain themselves. The idea would be that when a node comes up it checks to see if it's currently drained and undrains itself and when a node shuts down it drains itself. Obviously if a node terminates abruptly it wouldn't get drained, but this might be an easy way to hook into the existing update process.

**Comment by mml** [comment]
@roberthbailey how do you mean "drains itself"?  Do we mean the kubelet simply requests "to be drained", or that it drives the drain process itself, issuing requests to DELETE pods from itself in sequence?

**Comment by roberthbailey** [comment]
I meant that it would send a request to the apiserver to be drained.

**Comment by mml** [comment]
@roberthbailey Suppose the drain takes 15 minutes (or longer).  Does shutdown wait, polling the apiserver, to actually do the reboot?  And if so, does that much latency in the reboot still work OK with the way the instance group manager is driving the rolling update?

**Comment by roberthbailey** [comment]
Shutdown scripts are given somewhere around 90 seconds to run (https://cloud.google.com/compute/docs/instances/stopping-or-deleting-an-instance#delete_timeout), so that wouldn't work well if a drain took 15 minutes.

**Comment by mml** [comment]
Yeah.  Given that drains take an arbitrarily long time--perhaps we can cap that administratively, but exceeding 90s seems reasonably likely--draining in this fashion won't work unless we were able to raise the deadline.

**Comment by MikaelCluseau** [comment]
Hi there, what about having a "kube-node" program that would share the lifecycle of a node's boot?

It should be minimal so it doesn't required update very often and have a very low probability of failing, and probably include a "reexec" mechanism to update itself for instance on SIGHUP. On SIGTERM, it would run a fast "kill pods and detach volumes". It may also help to assert the node's state (ie up/down) by sending an heartbeat on etcd or the api-server (node up/down state could bring node locks too, right?).

**Comment by ihmccreery** [comment]
I'm adding this to next-milestone, with the understanding that we'll most likely want something like this for v1.4.

We should also think about a sticky-drain option for workloads where pods should remain on the machine (e.g. would prefer to tolerate downtime than machine migration):

A sticky-drain would:

1. mark the node unschedulable, where unschedulable in this case also means Kubelet leaves pods PENDING even if they're scheduled.
1. gracefully terminate pods on the machine, but move to PENDING on that node rather than deleting entirely and moving to a different node.

... Undrain marks the node as schedulable and able to move pods from PENDING to RUNNING

This machinery also seems like the right way to handle mirror pods and daemons for non-sticky-drains, so that they can get the benefits of graceful termination.

**Comment by smarterclayton** [comment]
On May 11, 2016, at 7:46 PM, Isaac Hollander McCreery <
notifications@github.com> wrote:

I'm adding this to next-milestone, with the understanding that we'll most
likely want something like this for v1.4.

We should also think about a sticky-drain option for workloads where pods
should remain on the machine (e.g. would prefer to tolerate downtime than
machine migration):


I would like to introduce forgiveness with that (or tie disruption budget
into the calculation).


A sticky-drain would:

   1. mark the node unschedulable, where unschedulable in this case also
   means Kubelet leaves pods PENDING even if they're scheduled.
   2. gracefully terminate pods on the machine, but move to PENDING on that
   node rather than deleting entirely and moving to a different node.


Per the API we state that pods can't move back to Pending from running,
which would potentially have major impacts on clients.   But we can
terminate all the containers and mark them unready.




... Undrain marks the node as schedulable and able to move pods from
PENDING to RUNNING

This machinery also seems like the right way to handle mirror pods and
daemons for non-sticky-drains, so that they can get the benefits of
graceful termination.

**Comment by bgrant0607** [comment]
Forgiveness is #1574

**Comment by timothysc** [comment]
For stateful services, you'll likely want eviction life-cycle hooks for "gracefulness".  Policy can be decided by pod authors in this way.  As there are often degrees of "stickiness".

**Comment by mml** [comment]
Can we call this done?  We have PDBs, drain, and a node upgrade implementation for GCE that respects this (in flight but should merge soon).

**Comment by mml** [comment]
I am closing this as fixed as well.  Same rationale as #3885.

**Comment by whitecolor** [comment]
@mml 
> We have PDBs, drain, and a node upgrade implementation for GCE that respects this (in flight but should merge soon).

What in what version should it be, how the feature will be called?

**Comment by mml** [comment]
Alex, the feature does not have a name, but it should be in 1.7.  See
#45748.

**Comment by whitecolor** [comment]
@mml thanks for pointing to PR.
