### ISSUE TITLE
[feature] pod level resource request and limit

### ISSUE THREAD

**Issue by shenlanse** [kubernetes/kubernetes#60834]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:

See the discussion:

https://groups.google.com/forum/#!topic/kubernetes-users/VMCftsSYgBI

**What you expected to happen**:

Maybe we can add new field , pod.Spec.ResourceRequirements to express the pod-level-resource meaning

**Comment by shenlanse** [comment]
#3608

**Comment by shenlanse** [comment]
related issues:
[#3608](https://github.com/kubernetes/website/issues/3608)

**Comment by shenlanse** [comment]
sig/scheduling
sig/api-machinery

**Comment by WanLinghao** [comment]
track

**Comment by lavalamp** [comment]
Removing the sig/api-machinery label: SIG API Machinery doesn't own the *contents* of the API.
/remove-sig api-machinery
/sig scheduling
/sig node

**Comment by resouer** [comment]
Sorry but this feature request does not make sense to me.

1. Kubernetes already setup Pod level resource limit by [Pod level QoS](https://github.com/kubernetes/kubernetes/issues/27204) and many node features now consume it, which, answered the question in original thread.

2.  As for @shenlanse's question, scheduler always count resources of pod containers as a whole, which means, you can just set your resource to a random one of your container. Then it should work.

3. Even for container runtime which does not support container level resource, like KataContainers, we can still read pod level cgroups as the pod's resource boundary.

btw, you should switch to use [Extended Resource](https://kubernetes.io/docs/tasks/configure-pod-container/extended-resource/) instead of hacking node object and scheduling process.

**Comment by shenlanse** [comment]
@resouer Thank you for your reply. 
2. Firtly, some kind of resources is pod level,not container level. Also, pod.Spec.Containers is not stable, user may update deployment to remove/add/update one of them. So we can't  set pod-level resourcerequirement in containers, which might be lost.

Extended Resource doesn't work for pod-level-resources.

Of course, if pod.spec.containers can't be updated, we can set pod-level-resourcerequirement in pod.Spec.Containers.
