### ISSUE TITLE
Node upgrades: e2e test: ensure persistent volumes survive when pods die

### ISSUE THREAD

**Issue by mbforbes** [kubernetes/kubernetes#6084]
See issue #6079 as the roll-up for node upgrades.

Use case: we upgrade nodes by tearing them down (deleting the instances) and bringing up new ones. Do data on the nodes survive?

This might go beyond just 'volumes' if there are other ways that data should persist on Kubernetes—anything that might rely on the presence of a node.

This issue will contain anywhere from zero to a significant amount of work to ensure that storage is migrated safely, and as a stretch goal, smartly.

References:
- The most relevant discussion regarding storage and upgrades is in #3333.
- This is ostensibly part of smartly evacuating nodes before upgrading them #6080

**Comment by markturansky** [comment]
This is possible for pods that use persistent volumes.  #5105.

**Comment by lavalamp** [comment]
@mbforbes I thought our rule was going to be that we don't save stuff in volumes-- if you want something to outlive your pod/node, you need to have it in some sort of persistent volume.

**Comment by mbforbes** [comment]
@lavalamp I know close to nothing about volumes, so it could be that "persistent volume" is the right term to use here?

The requirement I'm trying to hit is that tearing down all the nodes doesn't destroy data that the user wants and expects to persist.

Any clarification of exactly the mechanism that should be used is hugely appreciated, and I welcome edits to this issue (also happy to edit myself).

**Comment by markturansky** [comment]
@mbforbes A Persistent Volume should tear down cleanly and be able to be mounted again elsewhere when a pod comes back into the cluster.  It should follow the pod from node to node.  There are no local persistent volumes (only "network volumes" like GCEPD, AWSEBS, NFS, etc), so no data should be expected to remain on the node.

Regular volumes have no promise of persistence, so I would not expect any of them to retain data between nodes.

**Comment by mbforbes** [comment]
@markturansky OK, thanks for the clarification!

So, it looks like from my reading of the [PD test](https://github.com/mbforbes/kubernetes/blob/master/test/e2e/pd.go), we don't quite have something yet that exercises the "dramatically tear nodes down" case... or really anything that actually verifies whether the data on the PD survives between pod shuffling. I have no idea if, given the implementation of persistent volumes, this is a silly thing to want to test, or whether it would be good, at least as a sanity check?

As a strawman, this could go in the PD test, and add a few more checks, and maybe an additional test case that brings down a node (either via rebooting it or deleting the instance).

**Comment by markturansky** [comment]
There was a recent bug that accidentally deleted the contents of the volume before unmounting it, so a test that verifies data persists would probably be a good thing.

Each plugin is only as good as its provider.  The GCEPD plugin is only as reliable as GCE Persistent Disks, so long as we don't delete the data or the PD by ID using the API (until we want to).

**Comment by mbforbes** [comment]
Ack, great to hear. I'll keep this open, then. Once node reboot & re-reate get in, this shouldn't be hard, and I can hop on it then if no one else has.

**Comment by quinton-hoole** [comment]
As far as I can determine, the test that you're proposing boils down to ensuring that the data written to a persistent disk by one pod, should be be visible when the persistent disk is attached to another pod. As you say, this will be pretty easy to implement.  I don't think that it's a v1.0 blocker though.  Marking as such.

**Comment by mbforbes** [comment]
If we don't test this, we can't claim it's true. If this isn't true, upgrades don't work. (These statements are both modulo whether we care about tests and whether we care if users' data get destroyed.) I'm not arguing against v1.0-post, but do want to make clear what (I think) the implications are if this isn't supported at 1.0.

**Comment by quinton-hoole** [comment]
Sounds good Max. Given that we already have tests to verify that we can write to and read from a PD, I think that the chances of the proposed test failing are pretty slim, but definitely worth having.  If you have spare cycles, go for it, but I'd suggest prioritising it lower than explicit v1.0 blockers.

**Comment by mbforbes** [comment]
Ack!

**Comment by spothanis** [comment]
@markturansky, when you say "A persistent volume should cleanly tear-down", 
 can this include any cloud provider specific operations. Speaking with openstack as cloud 
 provider, when a pod with cinder volume attached dies due to a node failure, the cinder 
 volume associated with the pod is still attached to the dead node. Any subsequent attempts 
 to bring the pod back up on a different node will fail.
 You could say that the cinder plugin should handle such cases, by detaching
 the volume from the previous node before attempting to re-attach it, but since attaching 
 involves formatting the volume according to the fs type in the spec, if there was any user-error 
 in specifying the volume, while using cinder plugin **with-out** PV, it could potentially
 wipe out the wrong volume. 
@thockin would love to hear your thoughts on this

**Comment by markturansky** [comment]
Either Kubernetes needs some kind of health check for volumes (mounted, available, and otherwise) or the provider needs a health check for its volumes and performs the detach from its side when the node dies.

Kubelet has a volume manager and understands what it has mounted (which can track all these PVs), but the scheduler does not.   If the node dies, I don't think anything in the cluster knows if the volume is attached anywhere.

**Comment by thockin** [comment]
I have not tested what GCE, for example, does if a PD is attached to a VM
and that VM dies.  This is a good point and it yet another fun complication
of storage :)

@saad-ali

**Comment by spothanis** [comment]
Now that I think about it, there could be other things, cloud specific, that might have to be done for ex: we remove the nodes from SDN, clean up the virtual routers and so on. So would there be any benefit to adding a offBoardNode equivalent to cloudprovider, which can be invoked right after evicting pods from node controller?

**Comment by mbforbes** [comment]
I'm leaving the project, so reassigning to... @zmerlynn! The other upgrade czar!

**Comment by quinton-hoole** [comment]
This is more about improving our PD testing than it is about upgrades.  
Also, as per my comment above, we have some coverage of this case already:
https://github.com/kubernetes/kubernetes/issues/6084#issuecomment-101468907

Dropping priority and assigning to the cluster team for triage.  
@saad-ali FYI

**Comment by bprashanth** [comment]
@saad-ali confirms that if a node is deleted gce should detach the volume, so when the pod gets re-scheduled on another node it'll get the volume. This won't work if the node simply falls off the network, because the volume will remain attached to the node, but that's tracked in various other bugs, so dropping this to next-release.

**Comment by saad-ali** [comment]
> but that's tracked in various other bugs

https://github.com/kubernetes/kubernetes/issues/20262

**Comment by saad-ali** [comment]
Closing old issue. As of the 1.3 volume redesign, if a node goes down, volumes will still be detached by the attach/detach controller.
