### ISSUE TITLE
Should support webhook timeout configuration

### ISSUE THREAD

**Issue by hzxuzhonghu** [kubernetes/kubernetes#60914]
Currently we can set several webhooks for mutating and validating admission, but  we do not provide a way to set http timeout. And now they all use a default 30s. 

I think the timeout should be set according to particular cases.

/sig api-machinery
/sig auth

**Comment by hzxuzhonghu** [comment]
@caesarxuchao @liggitt @sttts @deads2k @lavalamp

**Comment by lavalamp** [comment]
Our gut instinct is that webhooks should be fast and this should be globally like 1s :)

**Comment by patrickshan** [comment]
@hzxuzhonghu I couldn't find the documentation about the default 30s timeout. Will it also apply to the case when all the webhook backend pods get killed ? like webhook service returns 503

**Comment by hzxuzhonghu** [comment]
There is no doc about this.  check `staging/src/k8s.io/apiserver/pkg/util/webhook/webhook.go#L36`

**Comment by Paxa** [comment]
Yes it would be nice to configure timeout per webhook

**Comment by djboris9** [comment]
I think it should be implemented in the kubeconfig spec and then https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/util/webhook/webhook.go#L64 can be made to use this value

**Comment by lavalamp** [comment]
/reopen
/lifecycle frozen

I still think we should have a discussion before doing anything that would encourage people to make really slow webhooks, esp mutating ones which run in serial. Add a few 30s webhooks to the system and you have a terrible user experience. Slow stuff should be done by controllers IMO. Webhooks should ideally execute in milliseconds.

**Comment by djboris9** [comment]
@lavalamp I would like to do the opposite with the authorization webhook. If there is a network issue that blocks the connection between the kube-apiserver and an authorizer, the requests will have to wait for 30s.
To reduce this risk, I use a daemon on localhost that times out after 1s to return fast.
This is a special use-case where the authorizer can work with a best-effort strategy and has no negative security impact.

**Comment by patrickshan** [comment]
we would like to reduce the time out as well as it doesn't make sense to wait for 30s if kube-apiserver couldn't talk to webhook.

**Comment by alban** [comment]
We were debugging an issue related to timeouts on a test cluster: we have a webhook admission controller with `failurePolicy: Ignore` on resources of kind `namespaces` (among other kinds). Due to a bad installation, the webhook always timeouts. The cluster was slow but otherwise working.

Then, we had the controller manager election that started at some point. It works by patching the annotations on the `kube-system` namespace resource, but with a shorter timeout, 10 seconds. I guess it comes from the [--leader-elect-renew-deadline](https://kubernetes.io/docs/reference/command-line-tools-reference/kube-controller-manager/) option. We see the following in the controller manager logs:

```
Put https://kube-apiserver/api/v1/namespaces/kube-system/endpoints/kube-controller-manager?timeout=10s: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
```

This `Put` command can never succeed since the controller manager timeout (10s) is shorter than the webhook timeout (30s). As a result, the controller manager election does not succeed. And deployments don't progress.

If we could configure the webhook timeouts to be less than the controller manager timeout, our test cluster would still be working (despite being slow).

/cc @schu

**Comment by liggitt** [comment]
fixed in https://github.com/kubernetes/kubernetes/pull/74562

/close
