### ISSUE TITLE
Verify deps for dev environment doesn't happen on make all

### ISSUE THREAD

**Issue by NerdsvilleCEO** [kubernetes/kubernetes#61016]
/kind bug
/sig cli
/assign

**What happened**:
Running make all w/out rsync installed resulted in a failed local build.

**What you expected to happen**:
A run to verify dependencies like happens when running make clean

**How to reproduce it (as minimally and precisely as possible)**:
Run make all without rsync installed

**Anything else we need to know?**:
I have a fix local which extracts verfiying the deps into a Makefile target, just wanted to make sure this is a desired behavior. This would allow both the all and the clean targets (or any future target which requires the deps to be set up) to use the verify-deps target.

Here is my naive attempt at a fix for this: https://github.com/NerdsvilleCEO/kubernetes/commit/54f88b337d8ab6d0c846fd1de9f9959585580554

**Comment by liggitt** [comment]
Does this rely on or modify the state of GOPATH outside the k8s.io/kubernetes folder? If so, I wouldn't expect it to run in make all

**Comment by NerdsvilleCEO** [comment]
@liggitt I don't think it does, I am just moving the verify_prereqs to a separate verify_deps target which I use everywhere it needs to happen https://github.com/NerdsvilleCEO/kubernetes/commit/54f88b337d8ab6d0c846fd1de9f9959585580554#diff-d9c2fbed1afd68d84fa4c7027beaaea0R158

**Comment by NerdsvilleCEO** [comment]
Let me check the verify_prereqs function, will get back to you

**Comment by cblecker** [comment]
The `kube::build` functions are a part of the hermetic container build system, where as the `make [all|WHAT=]` target assumes that you have a working local development environment. The `kube::golang::place_bins` function is the only non-build system function that uses rsync.

All we probably need is a clearer error message (using `kube::log::error`) in the place_bins function if you don't have rsync installed. I don't really want to form dependencies between the build system (`kube::build` functions) and the `hack/` scripts.

Otherwise, you can use `make quick-release` to use the container build system instead.

**Comment by NerdsvilleCEO** [comment]
Ok, want me to make a PR to make clearer errors?

**Comment by cblecker** [comment]
Yes, feel free to! You can `/assign @cblecker` to me for review.
