### ISSUE TITLE
Kube-up script with Vagrant behaves weirdly

### ISSUE THREAD

**Issue by ekatek** [kubernetes/kubernetes#6112]
This is best described by describing the replication.

`cluster/kube-up.sh`;`cluster/kube-up.sh`

First, get a clean checkout. Then, run the kube-up script with Vagrant. It will tell you to go compile K8S, which makes sense. Now... do it again, without compiling anything. You may expect the script to tell you to compile again, but it won't -- what happens is, it sees that the master VM exists, and doesn't do anything with it. Then it tries to launch the minion, etc.

This is not a huge issue now that we know that this happens, but it made debugging somewhat unpleasant -- what actually happened, was that the K8S compilation process would fail partway through the integration tests (for unrelated reason), but it wasn't clear if it had actually finished the compilation or not. We theorized that the answer was 'yes', but, I think, it might have only succeeded partway. Regardless, the master was a dud, but the minion was running, causing some ... confusion about what was going on. 

Fixing this would be neat.

**Comment by roberthbailey** [comment]
Please direct your questions to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes). 

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases. 

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to similar questions, and also familiarize yourself with:
  * [the user guide](http://kubernetes.io/v1.0/)
  * [the troubleshooting guide](http://kubernetes.io/v1.0/docs/troubleshooting.html)

Again, thanks for using Kubernetes.

The Kubernetes Team
