### ISSUE TITLE
Create policy API specifying constraints on scheduling properties

### ISSUE THREAD

**Issue by bsalamat** [kubernetes/kubernetes#61185]
Today, we do not have any mechanism to control what scheduling properties a user is allowed to add to their pods. As an example, a user may add tolerations to their pod allowing the pods to run on machines tainted with special hardware taint while the pods do not need the special hardware. Or, a user may add anti-affinity rules to their pods preventing other pods from running on the same node or even a larger group of nodes. These are concerning specially in multi-tenant clusters.
We need to create policy API specifying constraints on scheduling properties admins would like to control, such as:

allowed priority classes
allowed tolerations
required node selectors/affinity
allowed pod anti-affinity
required/allowed schedulers

**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature
/sig scheduling

**Comment by bsalamat** [comment]
cc/ @yastij

**Comment by yastij** [comment]
@bsalamat - we've wrote @arnaudmz & me draft of the design doc, we'll PR it tomorrow to kick-off discussions.

**Comment by liggitt** [comment]
cc @kubernetes/sig-auth-feature-requests

**Comment by ericchiang** [comment]
Ref https://github.com/kubernetes/kubernetes/issues/48041
Ref https://github.com/kubernetes/kubernetes/issues/59366

**Comment by ericchiang** [comment]
cc @colemickens

**Comment by tallclair** [comment]
BTW, this is done through annotations for:
Tolerations: https://github.com/kubernetes/kubernetes/tree/master/plugin/pkg/admission/podtolerationrestriction
NodeSelector: https://github.com/kubernetes/kubernetes/tree/master/plugin/pkg/admission/podnodeselector

**Comment by bsalamat** [comment]
> BTW, this is done through annotations for:
Tolerations: 
NodeSelector: 

Yes, we are aware of those. Both of those are alpha features. We are trying to build proper API without the use of annotations.

**Comment by bgrant0607** [comment]
See also: #17190, #17151, #17097, #14573

**Comment by NickrenREN** [comment]
cc @angao

**Comment by vikaschoudhary16** [comment]
@vikaschoudhary16

**Comment by ryanmcnamara** [comment]
We are also finding ourselves needing something pretty similar to this use case. In our case we need to enforce that for some instance only some (escalated) users can schedule pods on this instance. To the initial list in the description I would also add "setting the node name explicitly".

Re: the node name explicit setting, the concern here is that even if a taint is "no execute" and a pod doesn't tolerate the taint, a user can schedule the pod on some node directly and it will run until the kube controller manager (I believe it's the eviction controller?) removes it. This seems to not provide enough security because the system is effectively in a compromised (from our perspective) state.

We're plan on solving these problems ourselves via an admissions webhook that
1. Verifies that when pods are scheduled on a node the pod doesn't violate any of the taints
2. Add a taint to the node and authorize that any pod tolerating the taint is created by the escalated user mentioned before.

**Comment by alculquicondor** [comment]
Hello @yastij, I'm interesting in picking up this work, if that's fine with you.

**Comment by yastij** [comment]
@draveness  - is already working on refreshing the KEP for this

**Comment by draveness** [comment]
> @draveness - is already working on refreshing the KEP for this

Thanks @yastij 

/assign

**Comment by alculquicondor** [comment]
I think this is more in the domain of sig-auth and wg-policy than sig-scheduling. I honestly don't know if there had been any progress.

@excavador could you work with them for prioritization?
