### ISSUE TITLE
Manage resources created by the cloud provider 

### ISSUE THREAD

**Issue by dlaidlaw** [kubernetes/kubernetes#61199]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature

**What happened**:
The cloud providers create resources such as load balancers, block storage, etc. Administrators would like to know which cloud resources were created by the kubernetes cloud provider. There should be the ability to query for a list of those resources, or potentially even delete them.

A typical use case for this information is when tearing down the cluster, you first need to delete any Kubernetes-create resource. Due to cloud provider dependencies it may not be possible to tear down the cloud resources until the resources created by Kubernetes are remove. For example, in AWS if you use a CloudFormation stack to create subnets and an ASG with worker nodes, you will not be able to tear down the CloudFormation stack unless any Kubernetes-created load balancers and EBS volumes are removed first. AWS will report dependency errors when trying to remove some items because the CloudFormation stack does not include the items created by Kubernetes.

Automation used to tear down the cluster will need to remove any resources created by Kubernetes before removing the items create by the automation.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): n/a
- Cloud provider or hardware configuration: AWS, for one
- OS (e.g. from /etc/os-release): n/a
- Kernel (e.g. `uname -a`): n/a
- Install tools: n/a
- Others:

/sig AWS
/wg cloud provider

**Comment by jhorwit2** [comment]
cc @wlan0

**Comment by wlan0** [comment]
@dlaidlaw thanks for adding this request. 

If you delete the resources (Ingresses, Services (type: LoadBalancer), Nodes) in Kubernetes before deleting the cluster from the cloud provider, then the cloud resources associated with Kubernetes would be deleted.

I know this is true for LBs and Routes, however I'm not sure of Volumes. @yastij might know the answer. 

If you're looking for a mechanism to group resources from the cloud, so that they can be easily managed, then it makes sense to "tag" resources created by Kubernetes in the cloud, and allow it to be queried, and operated on. 

I Imagine this concern goes beyond any one cloudprovider and applies to pre-existing resources used by Kubernetes as well. Here's a quick solution I've mapped out:

These are the two calls that create resources (via cloud provider interfaces)

```go
// in pkg/cloudprovider/cloud.go

func CreateRoute(ctx context.Context, clusterName string, nameHint string, route *Route) error {}

func EnsureLoadBalancer(ctx context.Context, clusterName string, service *v1.Service, nodes []*v1.Node) (*v1.LoadBalancerStatus, error) {}
```

Similarly, there are other calls to use existing resources from the cloudprovider.

Each of these calls pass a `clusterName` parameter. Since it is possible to have multiple Kubernetes clusters in any given cloud, we might have to tag the resources (LB and routes) with a label/annotation that uses this name.

for eg.

```
(Created by Kubernetes)
k8s.io/cluster-resource-owned-by: $cluster-name

(Used by Kubernetes)
k8s.io/cluster-resource-in-use-by: $cluster-name
```

Better suggestions welcome :)

These changes would have to be made in the cloudproviders plugins themselves, and we cannot enforce cloudproviders to tag the resources via api. 

We could provide guidelines to the various cloudproviders on the above interfaces to always tag any and all resources created via these calls, and hope that the individual clouds follow the guidelines. 

The volume management is transparent to the cloudprovider - i.e. cloudprovider interfaces cannot enforce or provide guidelines for volume management.

If you would like to discuss this further, do reach out on kubernetes slack channel #wg-cloud-provider

**Comment by dlaidlaw** [comment]
Yes, in general deleting the services, etc deletes the load balancers, etc. However you have to know what you need to delete. I suppose you could just go an delete everything.

But there is another use for this information: auditing the things created by the cloud provider. In general we want to be able to relate the resources created by the cloud provider back to the cluster and the resource that created it. The names of the things created by the cloud provider are generally random strings, which is not very conducive to intuiting relationships. Tags would definitely help in this regard.

**Comment by wlan0** [comment]
Thanks for explaining the use case in more detail over slack

Here's the gist of what we discussed

For auditing, and management purposes, it is important to establish the identity of the creator (clusterName/userName) of the resources in the Cloud managed by Kubernetes.

This is important because cloudproviders have their own mechanisms for managing resources. In clusters such as @dlaidlaw's, where security and auditing policies are in place at the infrastructure level. Kubernetes does not follow these policies while managing resources in the cluster.

The missing piece is the customized "tag" on Kubernetes managed resources. Auditing and Security tools can use this "tag" to infer the management policies enforced.

Is this accurate @dlaidlaw?

**Comment by yastij** [comment]
@wlan0 @dlaidlaw - when deleting the PV, the storage asset still exists in the cloud provider.

**Comment by dlaidlaw** [comment]
@wlan0 Thanks for your time on this. 

This is exactly what is needed. I would add one more thing: it would also be valuable to annotate or label the kubernetes resource that was created with the same tag value to allow tracking the cloud resource to a kubernetes clusterName/userName/resource. The resource is not critical, but it does enhance the value of the audit by improving traceability.

**Comment by ewbankkit** [comment]
@wlan0 On AWS there seem to be some tag keys/values that could be re-used:
* [`TagNameKubernetesClusterPrefix `](https://github.com/kubernetes/kubernetes/blob/ca06cc43f787e0a32db7993314784f30ecae0f0a/pkg/cloudprovider/providers/aws/tags.go#L34)
* [`ResourceLifecycleOwned `](https://github.com/kubernetes/kubernetes/blob/ca06cc43f787e0a32db7993314784f30ecae0f0a/pkg/cloudprovider/providers/aws/tags.go#L47)/[`ResourceLifecycleShared `](https://github.com/kubernetes/kubernetes/blob/ca06cc43f787e0a32db7993314784f30ecae0f0a/pkg/cloudprovider/providers/aws/tags.go#L51)

maybe hoisted up to the provider-independent package?

Also, on AWS individual routes can't be tagged, only the route table and I think the route table is already tagged (as that's how we find which route table to manipulate).

**Comment by wlan0** [comment]
@ewbankkit thanks for the information!

@dlaidlaw The tags are already present for AWS. This should solve your issue in your existing cluster.

**Comment by dlaidlaw** [comment]
Yes, the tags created by AWS are excellent. I can use the tags created in AWS. However, these are created by AWS, but should this be made a standard or recommended practice? And standardize the tag names that are to be created? Or has this already been done?

**Comment by dlaidlaw** [comment]
Closing, since the AWS tags are sufficient for AWS usage. I still think it should be standardized for audit purposes, however.
