### ISSUE TITLE
Node objects gets ipv4 addresses in a ipv6 cluster

### ISSUE THREAD

**Issue by uablrek** [kubernetes/kubernetes#61319]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug
/area ipv6

**What happened**:

The node objects in a ipv6 cluster gets ipv4 addresses. This doesn't seem to affect function but it looks bad.

```
> kubectl get nodes -o yaml vm-004
...
spec:
  externalID: vm-004
status:
  addresses:
  - address: 192.168.0.4
    type: InternalIP
  - address: vm-004
    type: Hostname
  allocatable:
    cpu: "2"
    ephemeral-storage: "1841976113"
    memory: 657368Ki
    pods: "110"
...
```

If `hostNetwork: true` it becomes very visible for those pods;

```
# kubectl get pods -o wide
NAME                               READY     STATUS    RESTARTS   AGE       IP               NODE
cgen-deployment-7784d68dfb-2qq5q   1/1       Running   0          33s       fd00:3000:1::2   vm-001
cgen-deployment-7784d68dfb-fh6f2   1/1       Running   0          33s       fd00:3000:3::2   vm-003
cgen-deployment-7784d68dfb-lxnlh   1/1       Running   0          33s       fd00:3000:2::2   vm-002
cgen-deployment-7784d68dfb-vlmwj   1/1       Running   0          33s       fd00:3000:4::2   vm-004
ekvm-router-5xgcc                  1/1       Running   0          37s       192.168.0.3      vm-003
ekvm-router-mkbqb                  1/1       Running   0          37s       192.168.0.4      vm-004
```

**What you expected to happen**:

The addresses for nodes should be ipv6 addresses.

**How to reproduce it (as minimally and precisely as possible)**:

Make sure the hostname of the nodes resolves to *both* ipv4 and ipv6 addresses.

Start a ipv6 cluster

Check the address in the node object with `kubectl get node -o yaml node`

**Anything else we need to know?**:

If the hostname resoves to **only** ipv6 it works as expected, both node objects and `hostNetwork: true` pods.

I suspect that a lookup on hostname is made and the first address entry is taken whenever it's ipv4 or ipv6. Can't figure out if it is `kubelet` or other (--register-node=true).

I also install the-hard-way without kubeadm on an own made system so I can have missed something and in that case I apologize for wasting your time, but it doesn't look that way.

I am also aware that ipv6 is alpha, that's why I tested on 1.10-beta4 to see if the problem was already fixed. First discovered on 1.9.3.

**Environment**:
- Kubernetes version (use `kubectl version`):

```
# kubectl version
Client Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.0-beta.4", GitCommit:"a2dacb6f846e9d64d02c5dc5ab3972287d337405", GitTreeState:"clean", BuildDate:"2018-03-14T05:58:05Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.0-beta.4", GitCommit:"a2dacb6f846e9d64d02c5dc5ab3972287d337405", GitTreeState:"clean", BuildDate:"2018-03-14T05:45:34Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration:
Kvm VMs on Ubuntu 16.04. No cloud provider

- OS (e.g. from /etc/os-release):
None (own minimum system)
- Kernel (e.g. `uname -a`):
```
# uname -a
Linux vm-003 4.15.5 #2 SMP Sat Mar 3 17:24:14 CET 2018 x86_64 GNU/Linux
```
- Install tools:
None
- Others:

**Comment by pmichali** [comment]
If there are both IPv4 and IPv6 addresses, the IPv4 addresses will take precedence.

**Comment by uablrek** [comment]
That seems to be a dual-stack thing and then both addresses should be stored in the "addresses" record in the node object. In an `ipv6-only` cluster only the ipv6 address should be stored even if an ipv4 address exist. IMHO this is a bug and should not be hard to fix.

**Comment by pmichali** [comment]
@StuCurry IIRC, I think the decision was not to have a specific knob to select the IP mode, but instead to rely on the general configuration.

What tool are you using to bring up the cluster?

Can you share the kubeadm.conf that you are using?

Are you deploying on bare-metal or in a VM/other?

For bare-metal, I have a tool that helps with config... https://github.com/pmichali/lazyjack

For running in nested containers, you can use https://github.com/kubernetes-sigs/kubeadm-dind-cluster

**Comment by leblancd** [comment]
@uablrek , @StuCurry - Is it possible in your configuration to have *only* IPv6 address(es) for your node in each node's /etc/hosts file? This should cause the IPv6 address to get chosen for the node (and I believe that the /etc/hosts entry supersedes any DNS lookup when it comes to choosing the node IP, IIRC).
That said, I agree that we should consider fixing (enhancing?) this. I don't remember the execution context for where the choice is made for node IP, but there should be some (IPv4 vs IPv6) configuration that we can use to decide, rather than requiring a new knob.

**Comment by uablrek** [comment]
@leblancd Yes, an ipv6-only /etc/hosts is my workaround and works fine. I agree that no new knod should be added. The master processes seem to figure out if ipv6 shall be used already and if the problem is in those it should be an easy fix. If the problem is `kubelet` (I use --register-node=true) it may be a little trickier, but I think the `--address` must be given to kubelet in ipv6 and be an ipv6 address.

Anyway, I will take a look at this again, it may already be fixed in "master", if not I'll will try to get time to do a PR.

**Comment by uablrek** [comment]
I can't see this problem on master (v1.14.0-alpha.0.197+bcef72bf06a89b) so it seems fixed already and I let this issue remain closed.

**Comment by StuCurry** [comment]
@uablrek @leblancd The /etc/hosts file is not configured on my node, but this should also be a solution.

Now I have configured --node-ip=9f01::90 (IPv6 address on the node) in the kubelet, the node object and hostNetwork: true pod will use the address I configured instead of the IPv4 address on the node.

**Comment by leblancd** [comment]
@uablrek , @StuCurry , @pmichali - Glad to hear that the /etc/hosts workaround is viable for you. @uablrek , I'm surprised this is fixed in master... I could be wrong, but I believe that the code in question is here:
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/nodestatus/setters.go#L164-L175
The for loop here is designed with a preference for IPv4 addresses. The enhancement to consider, I suppose, would be to have this code prefer an IP family based on some IPv4/IPv6 Kubelet configuration, e.g. the advertise address for the Kube API server. I don't know how programmatically available that configuration would be in this block of code. That would be the tricky part.

**Comment by uablrek** [comment]
Maybe it is the `--node-ip=` param to kubelet that does it? I will make a test today.

**Comment by uablrek** [comment]
Confirmed;
* Without `--node-ip=` specified to `kubectl` and ipv4 addresses first in `/etc/hosts` the nodes gets ipv4 addresses
* Same as above but ipv4 addresses **last** in `/etc/hosts` the nodes gets ipv6 addresses
* If `--node-ip=` is specified with an ipv6 address the node gets that address regardless of `/etc/hosts`

The first/last thing in `/etc/hosts` is resolver specific I guess. I use libs from Ubuntu 18.04.

**Comment by uablrek** [comment]
@leblancd Do you think this is worth fixing in ipv6-only or can it wait to dual-stack is supported?
If this is not fixed it should be a requirement to specify `--node-ip=` to kubelet if this is not fixed IMO.
