### ISSUE TITLE
Bump etcd to 3.3

### ISSUE THREAD

**Issue by tylerauerbeck** [kubernetes/kubernetes#61326]
**Is this a BUG REPORT or FEATURE REQUEST?**:
 /kind feature

**What happened**:
It looks like there are a handful of issues waiting on a bump of etcd to v3.3. Is there any timeline on pushing this? Is there any work already being done on this?

**Comment by tylerauerbeck** [comment]
Not sure what would be most appropriate for this, so I'll start with the sigs from the issues that are already open: #48297 #45037 #46705

/sig instrumentation
/sig api-machinery
/sig scalability

If anybody has suggestions on something more appropriate, please let me know.

**Comment by jpbetz** [comment]
Yes and Yes.  But are you asking about the etcd server or client? Kubernetes 1.10 (slated for release tomorrow) will use the etcd 3.2 client and default to etcd 3.1 for the server (although kubernetes cluster operators can run any etcd server version they want).

Kubernetes 1.11 will be upgraded to use the etcd 3.3 client (https://github.com/kubernetes/kubernetes/pull/58551 already validated this upgrade is safe and will be cloned shortly to make the actual upgrade on master).  It is likely the the default etcd server version for 1.11 will be etcd 3.2 since for downgrade reasons we can only upgrade by one minor etcd version per k8s minor version.  But again, cluster operators can run whatever version they want.

**Comment by jpbetz** [comment]
/remove-lifecycle stale

We'll do this bump once 1.12 opens for PRs.

**Comment by lavalamp** [comment]
I set the milestone to 1.14; let's try to get this out as soon as master reopens so we have lots of soak time.

**Comment by luxas** [comment]
Just to clarify here -- etcd 3.3.x _client_ is shipped in v1.13, and etcd 3.3.x _server_ is targeted for v1.14?

**Comment by gyuho** [comment]
@luxas Yes, etcd v3.3 client was merged here https://github.com/kubernetes/kubernetes/pull/69322, but etcd server bump-up to v1.13 never happened (hence targed for v1.14).

**Comment by jpbetz** [comment]
Sorry for the belated response on this. Yes v1.14 is best for etcd server 3.3 bump. We don't require the etcd client and server be bumped together, and given the large volume of vendoring changes pulled in by the etcd 3.3 client we went with a full Kubenetes release cycle to bake the client bump in isolation from server changes.

**Comment by timothysc** [comment]
@jpbetz @ixdy - Now that 1.14 is open could a googler please push an updated image. 

/cc @kubernetes/sig-release

**Comment by jpbetz** [comment]
@timothysc Starting build/push of 3.3.10 image now

**Comment by jpbetz** [comment]
Build and staging push complete. We've requested promotion of the staging images to k8s.gcr.io. Client upgrade PR is https://github.com/kubernetes/kubernetes/pull/71615.

**Comment by luxas** [comment]
Shall we reopen this to track the scalability implications or will you create a different issue to track that @jpbetz @gyuho?

**Comment by gyuho** [comment]
@luxas Was there any scalability issue related to etcd 3.3 upgrade?

**Comment by luxas** [comment]
@gyuho I don't know, but we should track and investigate if there is :wink:
