### ISSUE TITLE
WebHookConfiguration should allow specifying apiVersion for handler

### ISSUE THREAD

**Issue by tamalsaha** [kubernetes/kubernetes#61348]
Currently (1.9), `(Validation|Mutation)WebhookConfiguration` does not allow specifying the apiVersion of object received by webhook handler. So, the choices for an implementer are: 

- Implement actual logic in all possible version or reject objects in unsupported versions.

- Use a pipeline of conversion similar to:
`src -> internal -> target -> applyChanges(target) -> modInternal -> modSrc -> default(modSrc) generatePatch(src, modSrc)`

None of this these options look good. I am hoping that webhook handlers behave the same way other controllers does in that apiserver does the conversion necessary and send the version requested by user to the webhook handler.

Thanks @sttts @deads2k @liggitt  for helping with this issue.

**Comment by tamalsaha** [comment]
cc: @lavalamp @erictune

**Comment by liggitt** [comment]
> None of this these options look good

The performance cost of converting 2*N times per resource write also doesn't look good. 

> I  am hoping that webhook handlers behave the same way other controllers does in that apiserver does the conversion necessary and send the version requested by user to the webhook handler.

In order to satisfy N webhooks in a single resource, the server could be required to do 2 conversions for every webhook (out to version M for the webhook, then back to internal for the apiserver)

**Comment by deads2k** [comment]
> In order to satisfy N webhooks in a single resource, the server could be required to do 2 conversions for every webhook (out to version M for the webhook, then back to internal for the apiserver)

Since the hub types aren't exposed, the cost of not doing this is very high as it requires every webhook author to either duplicate a large amount of code to write a set of interfaces which are huge (we've done both before).  Also, as an author, I'm fairly likely to exactly the conversion you're speaking of to handle it on the receiving side, so at best you're just shuffling it around.

I don't think we should downplay the developer cost of not exposing the hub types.  Our controllers can't even function without those (hpa and RC/RS as examples), because the cost of maintaining duplicate code paths was so high it was untenable.  I think we're going to have to do one or the other.

**Comment by lavalamp** [comment]
The current state is very annoying. We (or at least I) wanted to allow apiserver and webhook to negotiate a version for the object, and then the configuration would be over storage paths rather than external object versions. Unfortunately we weren't able to come to an agreement on how this should work and dropped it due to time constraints.

Today it is actually hard to catch all mutations with certainty. e.g., a change to deployments happen via a write to a different *group*.

My own position is that all conversions must be done in apiserver (with exactly one exception). Hub types are not serializable, so exposing them doesn't really help with this problem.
