### ISSUE TITLE
client-go external credential provider: support x509 client certs

### ISSUE THREAD

**Issue by ericchiang** [kubernetes/kubernetes#61421]
/sig auth
/kind feature
/priority important-longterm

Ref https://github.com/kubernetes/features/issues/541

This was planned in the original proposal but wasn't implemented for alpha in 1.10 https://github.com/kubernetes/community/blob/master/contributors/design-proposals/auth/kubectl-exec-plugins.md

**Comment by zjj2wry** [comment]
@ericchiang I want to know how this feature integrates kubernetes CertificateSigningRequest?
this is my conception，please correct it:
cluster-admin create a bootstrap token to user-A, user-A create csr, csr controller approve it. so i need a command like ```kubectl get csr xxx ...  --token=bootstrap-token```
(Suppose it can output certificate information to stdout). so bootstrap token need have permission get csr？and how key ratation？ thanks

**Comment by ericchiang** [comment]
@zjj2wry this feature isn't directly tied to certificate signing requests. As stated in the proposal it only lets a plugin provide raw TLS client cert data to client-go https://github.com/kubernetes/community/blob/master/contributors/design-proposals/auth/kubectl-exec-plugins.md#tls-client-certificate-support

**Comment by mikedanese** [comment]
We definitely want hardware bound keys, but it's not our highest priority right now. I'd like to move service account token private key operations out of the apiserver soon. For TLS:
* RSA cipher suites without ephemeral DH require private keys that implement crypto.Decrypter although non-DHE suites are lower priority for our kubernetes clients and servers by default and we should probably recommend against using them. 
* Both spiffe and boringcrypto are going the route of offloading the entire handshake. We should consider this as an alternative to implementing escrowed crypto.PivateKeys for use with go tls: https://boringssl-review.googlesource.com/c/boringssl/+/25387
* Where hardware oracles are available, they are often far to slow to be practical. "soft-hardware" oracles like SGX and vTPMs will likely be usable. Also, handshake performance matters a lot less for clients than servers.
* TLS 1.3 0-RTT (and 1.2 session resumption?) don't require key proof of possesion, negating a lot of benefits hardware bound keys since session state is easy to steal. We are going to have to disable some features (and trade perf for security) if we want strong client auth.
Probably we should split this into a separate issue.

**Comment by zjj2wry** [comment]
@ericchiang got, thanks ：）
