### ISSUE TITLE
Deployment is incompatible with apps/v1 ReplicaSet

### ISSUE THREAD

**Issue by enisoc** [kubernetes/kubernetes#61433]
All controllers in apps/v1 now have immutable selectors. While working on [converting Deployment to use apps/v1](https://github.com/kubernetes/kubernetes/pull/61419), I discovered that Deployment is incompatible with apps/v1 ReplicaSet because it expects to be able to add `pod-template-hash` to the ReplicaSet's selector if it's missing.

According to @janetkuo, this was a convenience feature to allow Deployments to adopt user-created ReplicaSets that weren't created directly by any Deployment. Given that this feature is incompatible with immutable ReplicaSet selectors, it seems that we need to consider either dropping/weakening the feature, or relaxing ReplicaSet selector immutability.

Since we already launched `apps/v1` Deployment with this feature, it would be a breaking change to weaken it or stop supporting it. That means Deployment would need to keep using ReplicaSet via `extensions/v1beta1` (which allows selector mutation) until `apps/v2` exists (with this feature deprecated and disabled by default) *and* `apps/v1` is removed (so the controller no longer needs to implement the feature at all). That would put us in the awkward position of supporting `extensions/v1beta1` for longer than `apps/v1`.

An alternative would be to go ahead with a breaking change in `apps/v1` (dropping/weakening the feature in question). The impact would depend on whether people actually rely on this behavior, and on whether any existing documentation explicitly recommends doing this. Note that this would only help if we *also* break the feature in `extensions/v1beta1` Deployment; if the controller still needs to implement the feature, it's stuck using ReplicaSet via `extensions/v1beta1`.

On the other hand, relaxing ReplicaSet selector immutability (possibly only to allow certain types of mutations) in `apps/v1` would be a backwards-compatible change. The original selector immutability proposal called out this possibility as justification for starting out fully immutable -- you can relax, but you can't tighten. This would mean in 1.11 we relax ReplicaSet selector immutability, and then in 1.12 we can finally move Deployment to use ReplicaSet via `apps/v1` (since the controller needs to work against +/-1 minor version skewed apiservers during HA upgrades).

I'm opening this issue to start a discussion about which path we should take, or other suggestions for how to resolve this.

/sig apps
/kind bug

cc @kow3ns @kubernetes/sig-apps-bugs @kubernetes/sig-apps-api-reviews 

This is a blocker for #55714.

**Comment by janetkuo** [comment]
I'm leaning towards relaxing ReplicaSet selector immutability. It's backward compatible and we get to avoid getting stuck in `extensions/v1beta1`.

**Comment by kow3ns** [comment]
> This was a convenience feature to allow Deployments to adopt user-created ReplicaSets that weren't created directly by any Deployment.

What is the use case for having Deployments adopt user created ReplicaSets, and is this a pattern we want to support?

**Comment by janetkuo** [comment]
Orphan/adoption of resources is a Kubernetes pattern, ref. some pod orphan/adoption use cases: https://github.com/kubernetes/kubernetes/issues/14961#issuecomment-144942320

[This](https://github.com/kubernetes/kubernetes/blob/df0518d07c182b253fd6288efd6f9680c8ac18dc/pkg/controller/deployment/sync.go#L160) was originally implemented so that RS produced by Deployment won't overlap with pre-existing ones that aren't constrained by the pod-template-hash (#20755). Now that we have controller ref, we can revisit if we still need it.

**Comment by crimsonfaith91** [comment]
In my opinion, relaxing ReplicaSet selector immutability should be the _better_ way to go. Although it is suggested by documentation to create a Deployment to manage pods via ReplicaSet (rather than creating ReplicaSet directly), there are some valid use cases that end up requiring ReplicaSet orphaning / adoption (e.g., combining ReplicaSets of 2 redundant Deployments).

**Comment by janetkuo** [comment]
If we break the behavior and make the Deployment not to add pod-template-hash RS's selector, the Deployment can still adopt the RS and its pods, but just don't add hash label/selector. 

Thinking about this more, it's actually not that bad, because the RS and pods will still be adopted and controller ref can prevent them from conflicting with other RSes (they'll have overlapping label/selector). 

The breaking change would be that the adopted pods and RSes won't have pod-template-hash anymore.

**Comment by crimsonfaith91** [comment]
As the RSs and pods can be adopted correctly without any conflict with controllerRef, I think we can consider removing the pod-template-hash by apps/v2 (simply because it is unnecessary). This breaking change is justifiable.

If we decide to remove the pod-template-hash, I think we can retain the selector immutability for RSs, but I may be wrong.

**Comment by tnozicka** [comment]
I am in favor of retaining selector immutability for RS. 

We have controllerRef and general rules of adoption to deal with overlapping selectors. Seems like this feature was created before controllerRefs and is not needed anymore. Or is there another reason we need it?

Maybe we can just stop using the pod-template-hash for all RSs and reach consistency?  That isn't part of any API or anything we have a contract for backwards compatibility, just an internal implementation detail, right?

Not setting it to adopted RS seem like a reasonable first step.

**Comment by liggitt** [comment]
> Maybe we can just stop using the pod-template-hash for all RSs and reach consistency? That isn't part of any API or anything we have a contract for backwards compatibility, just an internal implementation detail, right?

I would be strongly in favor of that. Spec hash computation has proven very problematic over the past several years.

**Comment by janetkuo** [comment]
> Not setting it to adopted RS seem like a reasonable first step.

Agree.

> Spec hash computation has proven very problematic over the past several years.

Yes, but in Deployment controller, the hash is _only_ used to generate ~unique label/selector, not for spec comparison. 

Note that `pod-template-hash` is mentioned in user guide: https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#pod-template-hash-label. IIRC, it's documented mostly to warn users not to touch that label. 

Because hash label is visible to users, I think some users still depend on it. At the very least, I've seen  users use the hash label to query against things like "all pods of a RS (i.e. all pods of a Deployment revision)" in `kubectl`. Removing it would make it harder for them to do so, since they'll need to list and then check controllerRef. If we're removing this label, we need to mark it as a breaking change.

**Comment by crimsonfaith91** [comment]
IMO, removing pod-template-hash is a breaking change that deserves more community discussion. For this issue, we should think about whether it is justifiable to _not adding_ pod-template-hash to adopted ReplicaSets (and pods). In either case, Deployments will still add pod-template-hash to ReplicaSets created by it.

To clarify, I lean towards not adding pod-template-hash to adopted ReplicaSets. There are 2 reasons:
1. pod-template-hash was added to adopted ReplicaSets to prevent adoption conflicts, which has been readily achieved by ControllerRef (i.e., pod-template-hash is unnecessary for this use case anymore)
2. preferably, all core controllers should uphold selector immutability for consistency purpose (leaving out ReplicaSet alone is inconsistent)

**Comment by janetkuo** [comment]
I filed #61615 for not setting pod-template-hash to adopted RSes and pods
