### ISSUE TITLE
Pod's PVCs using feature "Local Volume Scheduling" maybe not support re-scheduling 

### ISSUE THREAD

**Issue by orainxiong** [kubernetes/kubernetes#61620]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind feature

**What happened**:

When one Node crashes, the Pods running on the Node will restart at surviving Node.

While the pods are in rescheduling process, the Pods using feature "Local Volume Scheduling" will raise "ErrVolumenodeConflict" and rescheduling failed.

**What you expected to happen**:
When One pod failed because of node crashing, We could image workflow as fellow:
* nodeLifecycleController evicts the pod after podEvictionTimeout seconds,
* And then, StatefulSetController re-create the pod to meet spec.relplicas requirements,
* And then, Scheduler start to re-scheduling the pod,
* Finally, new predicate _VolumeBindingChecker_ find that it's all bounded PVCs has node affinity conflict and

**How to reproduce it (as minimally and precisely as possible)**:

code as follow:

```
func (c *VolumeBindingChecker) predicate(pod *v1.Pod, meta algorithm.PredicateMetadata, nodeInfo *schedulercache.NodeInfo) (bool, []algorithm.PredicateFailureReason, error) {

	if !utilfeature.DefaultFeatureGate.Enabled(features.VolumeScheduling) {
		return true, nil, nil
	}

	node := nodeInfo.Node()
	if node == nil {
		return false, nil, fmt.Errorf("node not found")
	}

	unboundSatisfied, boundSatisfied, err := c.binder.Binder.FindPodVolumes(pod, node.Name)
	if err != nil {
		return false, nil, err
	}

	failReasons := []algorithm.PredicateFailureReason{}
	if !boundSatisfied {
		glog.V(5).Infof("Bound PVs not satisfied for pod %v/%v, node %q", pod.Namespace, pod.Name, node.Name)
		failReasons = append(failReasons, ErrVolumeNodeConflict)
	}
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version 1.9.3

**Comment by msau42** [comment]
Can you clarify more what you expect the behavior to be?

If you're using local volumes, and the node crashes, your pod cannot be rescheduled to a different node.  It must be scheduled to the same node.  That is the caveat of using local storage, your Pod becomes bound forever to one specific node.

**Comment by orainxiong** [comment]
I plan to deploy MySQL Galera Cluster with statefulset and local volume atop k8s.
MySQL Galera Cluster, aka MGR, is a widely used solution to build MySQL Multi-Master cluster to avoid a single-point-of-failure

The basic idea is this: 
* Initial and build MGR cluster with one statefulset with three pods, and other corresponding resources;
* Hence node crash, k8s-scheduler can reschedule the pod to survival node;
* Newborn pod can initial and rejoin MGR cluster by using MGR data replication protocol;

In order to avoid distributed storage lock-in and reduce maintenance cost, There has a strong demanding for the customer to deploy MGR.

MGR more details : https://github.com/kubernetes/kubernetes/tree/8fd414537b5143ab039cb910590237cabf4af783/examples/storage/mysql-galera

**Comment by msau42** [comment]
If I understand correctly, the behavior you want is on a node failure, to have the Pod release its local PVC and obtain a blank new PVC on a different node.

We discussed this scenario a bit during the last storage f2f, and it was decided at that time that this behavior is very application, environment, and operator dependent, and would be very dangerous to implement something like this inside Kubernetes itself.  Instead, application specific operators should be written to handle all the necessary failover actions for their application.  One of those actions, could be to delete the PVC for pods that are pending on nodes that are gone/unhealthy.

If, over time, we find that there is enough commonality across many applications, then we could consider some generic mechanism.  But for now, it is safer to handle these situations per application.

@NickrenREN started working on a proposal for an external controller that could monitor specific statefulsets: kubernetes/community#1484, although it focuses more on local disk failures, rather than entire node failures.

**Comment by orainxiong** [comment]
@msau42 Thanks for your reply. I got it.

I plan to encode delete PVC action into the operator, to allow kube-scheduler to reschedule the database instances to the surviving node.

But I am not sure  if there maybe has a conflict with _postpone-pvc-deletion-if-used-in-a-pod_ 
[https://github.com/kubernetes/kubernetes/issues/45143](url).

**Comment by msau42** [comment]
Ah, I think you need to delete both PVC and pod.

**Comment by orainxiong** [comment]
OK.
It is grateful of you. I will close this issue.
