### ISSUE TITLE
Provide a solution for os-specific component config

### ISSUE THREAD

**Issue by mtaufen** [kubernetes/kubernetes#61649]
The Kubelet currently has a single os-specific flag: `--windows-service`.

We anticipate that the Kubelet, and other components, will require more os-specific flags in the future.

We should standardize how os-specific configuration is structured and managed across componentconfig API groups.

Some options:
- Separate `--windows-config`, `--linux-config`, etc. flags, with corresponding `KubeletWindowsConfiguration`, `KubeletLinuxConfiguration`, etc. objects.
- Separate objects, as above, but paths to the files are provided via `KubeletConfiguration`, allowing deployment via dynamic config.
- Simply add fields to `KubeletConfiguration`, with os-specific prefixes, e.g. `WindowsField`, `LinuxField`, `DarwinField`, etc. (this is perhaps the simplest approach).
- Substructures in `KubeletConfiguration` for each os. I'm personally against this one, as I suspect it will be uglier than a flat namespace.

Note: I'm ignoring cadvisor's linux-specific flags, since most are deprecated in the Kubelet and it's questionable how long we'll have cadvisor as a dependency. 

/assign @mtaufen @liggitt @thockin

**Comment by thockin** [comment]
Can you illustrate your options with simple examples?

I agree we should solve this holistically and set good precedent.  We have similar (ish) issues with things like kube-proxy that have fundamentally different operating modes that can be used, and some flags that overlap some modes.  Blech

**Comment by justinsb** [comment]
I described in https://github.com/kubernetes/kubernetes/issues/61647#issuecomment-388223891 how kops does kubelet configuration.  TLDR: we have a cluster level kubelet configuration, and then we allow overrides for each InstanceGroup (our NodePool / MachineDeployment).  That seems to work well for users.
  
I think it would be wrong to mix OSes in a MachineDeployment.  But we do have a choice in clusters where we are mixing OSes: we either require that `--windows-service` be defined on every windows MachineDeployment, or we entirely ignore `windows-service` on Linux, so it can safely be defined at top-level.  repetitiveness vs stricter validation.

Another option could be to introduce a third layer, so a MachineDeployment would combine the MachineDeployment configuration, then an OS configuration and then a cluster-wide configuration.  However this can also be done by tooling e.g. gitops + kustomize.

My inclination is that it's reasonable to ignore flags like `windows-service` on Linux - I think that's consistent with what we do elsewhere (e.g. in a discriminated union it's not an error to specify extra values IIRC).   The more tolerant approach means we can then punt this to tooling like kustomize, where - as long as configuration can be specified at the MachineDeployment level - it should be relatively easy to manage.  And for the case of simple clusters, we can just specify a single kubelet componentconfig.

We could still choose to organize these fields into other structures or with consistent prefixes if we want to, but I don't think we need to for deployment reasons.  I do like the prefix on WindowsService, but I'm not sure I want to have the debates about whether something _could_ be implemented on Linux / in IPVS in future...

But OTOH it is then potentially unclear (e.g. in the kube-proxy case) which fields do actually apply to the OS / networking mode we're using.  We do use the discriminated union approach for e.g. volumes, and it does clearly express what fields apply to each, and offers the most validation.  It also side-steps the "is this Windows only" debate, because we have chosen to duplicate fields.  So if it was my call I'd probably go with the substructure approach, but only because I think it makes things more explicit for the administrator, and it feels more consistent with what we've done elsewhere in the API.

**Comment by mtaufen** [comment]
I think I agree that a discriminated union at the top-most level is the clearest to the user.
We should think about what makes sense for componentconfig APIs that are already beta (or GA), since these can't cleanly move to a top-level union in the same minor version - I'm thinking of just using prefixes here.

**Comment by luxas** [comment]
cc @kubernetes/sig-cluster-lifecycle-feature-requests

**Comment by neolit123** [comment]
> Separate objects, as above, but paths to the files are provided via KubeletConfiguration, allowing deployment via dynamic config.

seems like the most reasonable option to me.
separate objects in separate files, even if the potential of flag duplication can occur. easier to maintain too.
one OS can transparently ignore the config for a different OS if it encounters it.
preferably no OS specific CLI flags.

**Comment by luxas** [comment]
Random idea, what about (re)using something like what kustomize (https://github.com/kubernetes-sigs/kustomize) does?

**Comment by neolit123** [comment]
> separate objects in separate files, even if the potential of flag duplication can occur. easier to maintain too.

yet, separate files are not _that easy_ to maintain. it's the Unix way to sparse a configuration all over the place.

using the `---` separator is arguably better:
https://github.com/kubernetes/kubernetes/blob/master/hack/testdata/multi-resource-yaml.yaml

**Comment by fromanirh** [comment]
all the PRs merged or closed, no updates since 2+ years, please file an actionable issue if still work to be done
/close
