### ISSUE TITLE
Let descheduler handle preemption

### ISSUE THREAD

**Issue by ravisantoshgudimetla** [kubernetes/kubernetes#61737]
**Is this a BUG REPORT or FEATURE REQUEST?**:

 /kind feature

I have started looking into implementing priorities while evicting pods in descheduler.

Following are my observations:

As of now, scheduler is doing preemptions to accomodate higher priority pods which cannot find nodes. We are having a overlapping functionality with descheduler which also evicts pods but with a broader goal of balancing the load in the cluster.

The idea here is to run descheduler as an extender. The flow in steps would be:

- Scheduler couldn't find any nodes using standard predicates and goes through preempt stage. 
- Descheduler could be called as an extender(or plugin based model in future) in this stage and it would return a single node after evicting pods on the nodes and updating the pod's nominatedNodeName. The entire logic of preemption could be moved to descheduler while it is evicting pods.(I know that we are deleting pod in preemption).

The second operation ensures atomicity as this is happening within a scheduling cycle there by eliminating the chance of race conditions.

There are some gaps in the current implementations of descheduler. For example on descheduler side, we don't have
- predicates & predicates being used(This is on roadmap though).
- No HTTP server through which extender can be called.
- Taking priorities into consideration while deleting pods. (As of now in descheduler supports evictions and *eviction* of pods which cannot be recreated(ex which could be re-created: RS, jobs etc) is not possible).

Did I miss something on scheduler side? Is this something worth investigating?

/cc @bsalamat @aveshagarwal

**Comment by bsalamat** [comment]
I have already explained [in the comments of this doc](https://docs.google.com/a/google.com/document/d/1v7hsusMaeImQrOagktQb40ePbK6Jxp1hzgFB9OZa_ew/edit?disco=AAAABjLhOI0) why a single component cannot perform preemption in a system that supports multiple schedulers, including custom schedulers.
In a system that supports multiple schedulers, each scheduler may have its own scheduling criteria. When a Pod is created, one of the scheduler is responsible for scheduling the Pod. That scheduler knows which Node(s) are appropriate for running the Pod based on its own scheduling criteria and the Pod's spec. The component that performs preemption must be able to verify that the Pod can be assigned to the Node picked for preemption. If a single component in a cluster were to do the preemption, such component would need to have the union of all schedulers criteria, which is quite hard to implement and scale.
Even in a single scheduler cluster were scheduler is customized, the preempting component would need to know about all the customization of the scheduler in order to verify that the picked Node for preemption can eventually run the Pod.
For these reasons, I believe we cannot use descheduler (or any single component) to perform preemption. I think the same scheduler responsible for running a Pod should perform preemption for the Pod as well.

**Comment by ravisantoshgudimetla** [comment]
Thanks @bsalamat. My ideas are: 
- Decouple default scheduler from preemption but not having descheduler as component for preemption for entire cluster.
- Let descheduler do preemptions for _default scheduler only_.

Apologies, if this intention was not clear fro my earlier comments.

Let us take the example of multiple scheduler scenario with kube-scheduler(default scheduler) and some other scheduler named X are used. 

(A.) Current scheduling decision is being made by default scheduler.
 - We will use descheduler in HTTP mode for preemption and let it be called as scheduler extender from default scheduler. Descheduler will have predicates and priorities to check if there is a potential node which could preempt pods. Whatever I proposed in my earlier comment is specific to default scheduler.

(B.) Current scheduling decision is being made by X
- It is upto X to decide how to do preemption. I agree that we should not do a centralized preemption.

>  If a single component in a cluster were to do the preemption, such component would need to have the union of all schedulers criteria, which is quite hard to implement and scale.

I agree with you that a single component should not do preemption in entire cluster. Every scheduler needs to have its own preemption logic just that in case of default scheduler we should let specialized descheduler to do preemptions. Even in current preemption logic, I think we are checking for only the default scheduler's predicates and priorities and for no other scheduler, so decoupling it and then putting it in a component that could do evictions seems more natural to me. In this case, it is descheduler I believe.

> Even in a single scheduler cluster were scheduler is customized, the preempting component would need to know about all the customization of the scheduler in order to verify that the picked Node for preemption can eventually run the Pod.

Can you please elaborate. I think if we have less of customized code and a plugin based model(which in a way we have) and use predicates/priorities as a library, we could import that library in descheduler(or any component) and check if pod fits on a node and set nominatedNodeName.

**Comment by bsalamat** [comment]
> We plan to consider priorityClasses(priorities), predicates and priorities in descheduler to do just evictions, so the missing part is running descheduler as extender, so I proposed that we could move the preemption logic to descheduler to avoid code duplication.

The only common part between descheduler eviction and preemption is the Pod deletion. Otherwise, they are very different. I don't think descheduler ever needs to duplicate the logic of preemption. Almost all of the logic of preemption is about choosing nodes and the minimum set of lower priority pods to preempt in oder to make room for a higher priority pod. After the set of victims are identified and the node is chosen, then it deletes the victims. This victim deletion part is tiny compared to the whole preemption logic and this is the only part that is common between descheduler and scheduler.

**Comment by ravisantoshgudimetla** [comment]
> The only common part between descheduler eviction and preemption is the Pod deletion.

I think, in preemption 
- We are checking if the node could run the pod after removing certain pods.(podFitsOnNode) is being checked in selectVictimsOnNode function.
- The actual eviction of pod happens on one of the potential nodes after checking for PDBs etc.

In descheduler,
- We need to check if there is a node where the current pod could run before eviction happens. (As of now, we are not checking if the podFitsOnNode(basically predicates)). Once we add this logic for predicates in descheduler, same logic could be used for new incoming pod before preemption happens in case descheduler is used for preemption. 
- If previous step is successful, we will evict pods from node. I think while choosing node, if we could cover the cases that you have considered while preempting, it might be useful further or do you think it will be overkill?

So, I think there is a overlap of larger functionality.

I am not suggesting that we should move the preemption logic to descheduler only option. It is one of the options to have larger decoupling but as you suggested earlier, if we could break down the preemption code into a plugin that could be used in descheduler, it will be much more helpful.

**Comment by bsalamat** [comment]
> We are checking if the node could run the pod after removing certain pods.(podFitsOnNode is being checked in selectVictimsOnNode function.)

This is part of the general scheduling workflow which is used during preemption as well, but it is not specific to preemption. In other words, you cannot remove this part and place it in descheduler even if you move preemption to descheduler. So, the code duplication would continue to exist. If you need this piece, you should convert it to a library that can be called from another module and then use the library in descheduler.

> The actual eviction of pod happens on one of the potential nodes after checking for PDBs etc.

You are right that this part is preemption specific, but I don't think this part should be used by descheduler. In particular, the way preemption handles PDB should not be used in descheduler. In preemption logic, when there is a high priority pod that cannot be scheduled, scheduler tries to find a node where killing lower priority pods does not violate PDB, but if there is no choice than killing pods whose PDB is violated, scheduler will go ahead and kill those pods. This should not be done in descheduler. Descheduler optimizes and defrags resources of the cluster. It should not optimize at the cost of violating PDB.

> we could break down the preemption code into a plugin that could be used in descheduler, it will be much more helpful.

I am fine with this as long as the pieces are useful in other components.
