### ISSUE TITLE
admission controller should be able to add private claims to serviceaccount ID tokens

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/kubernetes#61795]
We need an extension point that can intercept TokenRequests, apply extra validation and add private claims to the provision token. Admission control seems like a reasonable place to extend the TokenRequest API in this way. This is required to support implementation of https://github.com/kubernetes/community/pull/1604 out of tree.

Questions:
1. Is admission control reasonable?
1. If so, how should an admission controller communicate extra private claims to the TokenRequest REST?

cc @liggitt @cjcullen @kubernetes/sig-auth-feature-requests 

ref #58790

**Comment by liggitt** [comment]
extra validation is easy. private claims are tricky

anything you want an admission plugin to add into the object must be in the API, and will be indistinguishable from data submitted by the user once the object makes it into the REST handler.

**Comment by cjcullen** [comment]
Strawman: Add a `RequestedClaims map[string]string` to `TokenRequestSpec` to let a mutating admission hook add whatever claims it wants to the incoming token request.

Like @liggitt said, this also advertises to all callers that extra claims are something that you can request. It feels weird to have claims be requested by clients rather than only ever applied by the server. Would we by default allow any claims, and rely on cluster admins to put an admission controller in front? We could maybe disallow the [known public claims](https://www.iana.org/assignments/jwt/jwt.xhtml)? Or maybe only allow claims that followed our annotation format (e.g. `foo.bar/my-claim`).

Please commence attacking the straw man.

**Comment by mikedanese** [comment]
To prototype I'd suggest an annotation `auth.alpha.kubernetes.io/extra-claims` to string encoded json. It would be good to wipe out that annotation before the webhook admission controller.

**Comment by micahhausler** [comment]
/reopen 
/remove-lifecycle rotten

I'd love be able to add additional metadata to tokens, but as mentioned above, it is a difficult problem to validate and implement private claims.

What if we bypassed the kube-apiserver completely and not just [external signing of tokens](https://github.com/kubernetes/enhancements/tree/master/keps/sig-auth/740-service-account-external-signing), but external generating of them too? The external generator could receive default claims from the kube-apiserver, and its up to an implementor to decide what additional claims to add to a token.

**Comment by enj** [comment]
> What if we bypassed the kube-apiserver completely and not just external signing of tokens, but external generating of them too

I feel that it would be strange to require an external signer to get private claims.  I am also unsure how the client would request specific private claims.  I do not think it would be sufficient to say that the signer gets to inject arbitrary claims with no coordination from the client (that seems too limited).
