### ISSUE TITLE
Cluster setup: getting started guides rely on directories/scripts not included in kubernetes.tar.gz

### ISSUE THREAD

**Issue by alex-mohr** [kubernetes/kubernetes#6180]
User report: "I was unable to use the walkthroughs provided (as READMEs on github) to get a cluster up and running on CentOS, CoreOS, or even Google Compute Engine.  I eventually determined that there are directories/scripts present in the git repo that are not in the kubernetes.tar.gz tarball that the documentation says to use."

This issue tracks fixing the core supported docs.  @erictune as FYI due to previous interest in getting starteds.  Will file a separate issue for release validation tests to ensure that getting started guide instructions continue to work (#6181)

**Comment by roberthbailey** [comment]
@erictune -- @zmerlynn can easily add extra directories as necessary to the .tar.gz file. Are there any that we don't want to include (or can you prune them later if so)?

**Comment by erictune** [comment]
The GCE getting started guide only mentions directory `cluster`.  It may have changed since this issue was filed ... probably to convert to the https://get.k8s.io instructions.

CentOS and CoreOS are community supported, not project supported, so I'm not going to audit them.  

I don't think we should grow the release tarball unless we understand what we are adding.

**Comment by erictune** [comment]
I verified that I can start a cluster on GCE using the GCE instructions.  
I think this cane be removed from v1.

**Comment by zmerlynn** [comment]
Done

**Comment by roberthbailey** [comment]
Is this still an issue or can we close it?

**Comment by bgrant0607** [comment]
This has been superseded by other work.
cc @mikedanese
