### ISSUE TITLE
Lot of restarts on Kube-proxy pod

### ISSUE THREAD

**Issue by disha94** [kubernetes/kubernetes#61901]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> /kind bug

**What happened**:
I am recently facing issues with Kubernetes version 1.8.9 as I am getting a lot of restarts on Kube-proxy pod for few nodes. Due to which all service pods scheduled on that node are crashing again and again.
**What you expected to happen**:
Stable setup
**How to reproduce it (as minimally and precisely as possible)**:
Happening randomly on few of the nodes so not able to reproduce
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.8.9
- Cloud provider or hardware configuration: Installed with Kops 1.8.1 on AWS
- OS (e.g. from /etc/os-release): Debian GNU/Linux 9 (stretch)
- Kernel (e.g. `uname -a`): 4.9.0-6-amd64
- Install tools: Kops
- Docker Run Time: docker://1.13.1

@kubernetes/sig-node
Could someone please help me with this as this is causing a lot of problems in our setup.

**Comment by disha94** [comment]
When I check the node events and kube-proxy pod logs, I am getting the following errors:
server.go:480] starting metrics server failed: listen tcp 127.0.0.1:10249: bind: address already in use
<img width="1147" alt="screen shot 2018-04-06 at 3 59 43 pm" src="https://user-images.githubusercontent.com/14833876/38417463-0542b628-39b6-11e8-91fc-f230365ee063.png">

This is happening not just for the metrics server / healthz, it's happening for all the node ports that are exposed.
When I did "**sudo netstat -tulpn | grep LISTEN**" inside one of the node, I am getting this:
<img width="672" alt="screen shot 2018-04-06 at 4 34 22 pm" src="https://user-images.githubusercontent.com/14833876/38418237-33f70d5e-39b9-11e8-9917-b8a7389a0b84.png">

Tried restarting / deleting the node but no use.

**Comment by disha94** [comment]
The issue is still open if anyone can take a look at this??

**Comment by MrHohn** [comment]
@kubernetes/sig-node-bugs It seems like two instances of kube-proxy were running and causd one of them failed to bind any ports?

**Comment by ValeryNo** [comment]
I had the same issue after. Happened couple of days after 1.7.x -> 1.9.x cluster upgrade. Initially, everything was fine, but then I was deploying more services one node became NotReady, and the rest shortly followed. We're using Kops on AWS. Problem was solved by a complete cluster restart (workers scaled to 0, each master restarted, then workers scaled back to initial #

**Comment by arminmor** [comment]
FYI, deleting the kube-proxy and calico pods on the node with the issue resolved the problem form me.
It takes a few minutes to have updates on the cluster. During this period I was monitoring the calico-node logs and I realized that as soon as the following logs appear, service access is updated:

```
bird: Graceful restart done
bird: Mesh_172_21_87_86: State changed to feed
bird: Mesh_172_21_87_88: State changed to feed
bird: Mesh_172_21_87_93: State changed to feed
bird: Mesh_172_21_87_95: State changed to feed
bird: Mesh_172_21_87_96: State changed to feed
bird: Mesh_172_21_87_106: State changed to feed
bird: Mesh_172_21_87_86: State changed to up
bird: Mesh_172_21_87_88: State changed to up
bird: Mesh_172_21_87_93: State changed to up
bird: Mesh_172_21_87_95: State changed to up
bird: Mesh_172_21_87_96: State changed to up
bird: Mesh_172_21_87_106: State changed to up
```

**Comment by rodcloutier** [comment]
Did you check if there were more than one kube-proxy process? I had the issue on 1 node in GKE where 2 kube-proxy processes where live.

**Comment by GarethLewin** [comment]
We also have multiple instances of kube-proxy on one of our nodes, but we have no idea how that occured, is this a known issue?

**Comment by milosgajdos83** [comment]
We have noticed similar problem with exactly the same symptoms as described in this issue.

As @arminmor mentioned in his description we too have noticed exactly the same `calico-node` errors in the logs when multiple instances of `kube-proxy` are found on the worker nodes.

This makes me think if there is some kind of correlation in cause->effect fashion i.e. `calico-node` experiences issues which somehow causes `kube-proxy` to "crash", which for whatever reason doesn't seem to clean up after itself and leaves "stale" instance running whilst spinning out a new `kube-proxy` instance.

This [comment](https://github.com/kubernetes/kops/issues/4549#issuecomment-385676470) in a different issue mentions running out of disk space as a potential cause of similar problems. We too have noticed some "correlation" between resource pressure on the node and the `kube-proxy` issue, however we can't confirm it with absolute certainty since we can't reproduce it.  Either way, both `calico` daemon set and `kube-proxy` pods have `critical-pod` annotations on them so I wouldn't expect them to be killed off by scheduler due to lack of node resources.

**Comment by aabed** [comment]
the problem was solved with those versions

Kube 1.10.3
Calico-node v2.6.7
Calico-cni v1.11.2

**Comment by milosgajdos83** [comment]
Do you know the root cause @aabed ? Which one of those components were at fault and how?

**Comment by aabed** [comment]
I really don't know the root cause
but we started cluster with kops, it was k8s 1.9.3 
the problem existed

after upgrading to 1.10.3 it disappeared

in both cases Calico versions were the same

so I'd say it was solved by upgrading kubernetes itself
