### ISSUE TITLE
client-go: on Windows, homedir should prefer USERPROFILE

### ISSUE THREAD

**Issue by davidovich** [kubernetes/kubernetes#61946]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

In [client-go](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/util/homedir/homedir.go), which is used by many clients, homedir favors a concatenation of %HOMEDRIVE% and %HOMEPATH% over %USERPROFILE%

**What you expected to happen**:

HOME should be favored if it is set, then fallback to USERPROFILE, then maybe HOMEDRIVE and HOMEPATH combination.

**Anything else we need to know?**:

The current implementation of https://github.com/kubernetes/client-go/blob/master/util/homedir/homedir.go resolves a homedir in this order:

1. HOME
2. a concatenation of HOMEDRIVE and HOMEPATH
3. USERPROFILE

I believe that this is wrong, notably the HOMEDRIVE and HOMEPATH construct.

In the corporate environment where I work, these variables are hard set to network drives which are not writable. This results in many problems for dependant projects like minikube, kubectl kubernetes/kubectl#227 (which would benefit from using client-go code).

There are almost no mention of using HOMEDRIVE and HOMEPATH, but authoritative information on the subject is hard to find.

Relevant documentation: 

https://stackoverflow.com/questions/606483/what-is-the-meaning-of-these-windows-environment-variables-homedrive-homepath/648265#648265

https://blogs.msdn.microsoft.com/patricka/2010/03/18/where-should-i-store-my-data-and-configuration-files-if-i-target-multiple-os-versions/

**Environment**:

- Windows

**Comment by lavalamp** [comment]
cc @mbohlool @yliaog

**Comment by yliaog** [comment]
sounds reasonable. but I'd like to have sig/windows folks to chime in.

**Comment by davidovich** [comment]
Additional profiles directory information:
https://msdn.microsoft.com/en-us/library/windows/desktop/bb776896(v=vs.85).aspx

Microsoft makes it difficult to reason about these environment variables as they are not readily mentioned/searchable in the online documentation. Even in the previously mentioned doc on profiles, no mention of the %USERPROFILE% environment variable is made.

Python already does this resolution in the order suggested: HOME, USERPROFILE, and HOMEDRIVE/ HOMEPATH: https://docs.python.org/3.6/library/os.path.html#os.path.expanduser

There could be another way to implement this:

If it is possible, call the Windows API [SHGetKnownFolderPath()](https://msdn.microsoft.com/en-us/library/windows/desktop/bb762188(v=vs.85).aspx) to know the path, regardless of env variables.

**Comment by nikhita** [comment]
/remove-lifecycle stale

still relevant

**Comment by mbrancato** [comment]
This continues to be an issue in 1.11.0.

Basically, the HOMEDRIVE/HOMEPATH is a holdover from NT4 days with roaming profiles. This is not a standard env variable anymore. The existence of HOMEDRIVE / HOMEPATH should be ignored if USERPROFILE is set.

Neither HOMEDRIVE nor HOMEPATH are standard environment variables:
https://technet.microsoft.com/en-us/library/hh825266.aspx

They are not use in any known folder locations:
https://msdn.microsoft.com/en-us/library/dd378457(v=vs.85).aspx

The existence of a HOMEDRIVE / HOMEPATH will cause `kubectl` to look in the wrong home folder for the `.kube/config`. A use-case here is with AKS -  the Azure CLI (written by Microsoft) will correctly place credentials into `%USERPROFILE%\.kube\config`, however `kubectl` will look in `%HOMEDRIVE%\%HOMEPATH%\.kube\config`. Because of this, `kubectl` will think it should connect to localhost until the HOMEDRIVE and HOMEPATH variables are unset or removed in the session.

**Comment by mbrancato** [comment]
Since @liggitt has proposed a different approach, I wanted to discuss it in the original issue for clarity.

I do not believe we should not favor the use of `HOMEDRIVE/HOMEPATH` at all as is proposed with #73923 here: https://github.com/kubernetes/kubernetes/blob/1321ca7511a1b332449cadb21a274b054acca56d/staging/src/k8s.io/client-go/util/homedir/homedir.go#L43-L48

Based on the use-case raised by @davidovich and experienced by myself as well, this will cause more problems if we continue to prefer `HOMEDRIVE/HOMEPATH`. I understand moving existing configs from a prior path to be more aligned valid environment variables (which `HOMEDRIVE/HOMEPATH` is not) will cause some breakage without migrating old configs.

To illustrate the issue, some tools on Windows like the Azure CLI do not honor `HOMEDRIVE/HOMEPATH` and thus, when authenticating users to Microsoft's own managed Kubernetes offerings, it writes the configuration to `USERPROFILE`. When the config is written to `USERPROFILE`, but `client-go` is looking in `HOMDRIVE/HOMEPATH`, the client does not get the correct configuration. With the PR proposed, I'm afraid we may further fracture things with clients writing to non-standard environment variables and where some outlier cases would end up with a `.kube` folder in both `HOMEDRIVE/HOMEPATH` and `USERPROFILE`.

The `HOME`, then `USERPROFILE`, then `HOMEDRIVE/HOMEPATH` would follow what I think most tools and languages use. I believe this is in wide adoption and the evaluation of environment variables should be in that order. For example, python's ordering: 
https://github.com/python/cpython/blob/18618e652c56e61a134e596b315a13c7cb997a89/Lib/ntpath.py#L302-L313
