### ISSUE TITLE
Users should be able to know which namespaces they have permissions against

### ISSUE THREAD

**Issue by alexmavr** [kubernetes/kubernetes#61958]
/kind feature

I wasn't able to find a way for users to view the list of namespaces that they may be able to perform operations against, if they don't have explicit permissions to perform a `list` operation on the `namespace` resource.

For example, with the built-in RBAC system a user may only have a single `RoleBinding`, for a role that grants only `PodCreate` on namespace `foo`. The user would have to know to set `foo` as their context.

Is this possible today for the RBAC authorizer? If not, what would the addition of such an API require, given the various options for authorization (webhook, ABAC, RBAC)?

**Comment by alexmavr** [comment]
@kubernetes/sig-auth-feature-requests

**Comment by liggitt** [comment]
> I wasn't able to find a way for users to view the list of namespaces that they may be able to perform operations against, if they don't have explicit permissions to perform a list operation on the namespace resource.

Correct. there are no ACL-filtered APIs in core kubernetes. Filtering resources through ACL breaks  resourceVersion semantics that allow `watch` to function properly.

If you don't care about those semantics (or about supporting `watch` in a way that works reliably with informers, etc), you could build an API like https://github.com/openshift/kube-projects. That is an example of an ACL-filtered API you could build by combining the kube namespaces API and RBAC ACL checks.

As a general-purpose feature, however, that isn't possible to make work against all the supported kube authorizers, since the external ones are not efficient to do bulk access queries against, and do not have the ability to notify the filtering API when access rules have changed.

**Comment by liggitt** [comment]
closing this, as the issues with ACL-filtered list APIs are fairly well understood not to play well with watch semantics and external authorizers, and there no near-term plans to bring something like https://github.com/openshift/kube-projects into tree

/close
