### ISSUE TITLE
Reason: Unauthorized

### ISSUE THREAD

**Issue by jamespinkerton** [kubernetes/kubernetes#61978]
Hi. I'm occasionally getting the following error on kubectl requests through the python API to GKE.

The exception is when calling BatchV1Api->list_job_for_all_namespaces.

kubernetes.client.rest.ApiException: (401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Audit-Id': 'ffa6c4c6-4ba9-4de7-b3c7-23437edbe4ff', 'Content-Type': 'application/json', 'Www-Authenticate': 'Basic realm="kubernetes-master"', 'Date': 'Sat, 31 Mar 2018 09:15:44 GMT', 'Content-Length': '129'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Unauthorized","reason":"Unauthorized","code":401}

Is this expected behavior?

Thanks!
James

**Comment by cblecker** [comment]
Please re-post your question to [Stack Overflow](http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases.

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans Stack Overflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search Stack Overflow for answers to similar questions, and also familiarize yourself with:

  * [user documentation](http://kubernetes.io/docs/)
  * [troubleshooting guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/)

Again, thanks for using Kubernetes.

The Kubernetes Team

---
/kind support
/close

**Comment by zq-david-wang** [comment]
I am having similiar issue, when trying to retrieve lots of items, api would sometimes return 401. 
and in apiserver log, there would line "invalid bearer token"

I think this is a bug, not sure which module

**Comment by zq-david-wang** [comment]
I experience the 401 issue with 1.10 1.12 clusters, but with 1.14 cluster so far I did not detect any 401 yet. The following commit make massive changes to authentication, but it is only merged into 1.13 and above,  Maybe the bug has already been fixed.
https://github.com/kubernetes/kubernetes/commit/e5227216c0796d725c695e36cfc1d54e7631d3a6#diff-8597799c5c0959ab94ebd84365b915af
