### ISSUE TITLE
multi-port support in openstack load-balancers

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#6198]
Once #6182 lands, the openstack load balancer will have a non-supported case of multi-port services.

@anguslees

**Comment by spothanis** [comment]
@anguslees @thockin Neutron currently does not allow multiple vips and pools be created with the same name in the same tenant. Since we have to create as many number of vips per service as ports, I think, one way would be to come up with different names for them by appending the derived name with -port 

For example for a 2 port service with ports 7077 and 8080 
service id:  `040cd118-4dc5-11e5-aefb-74dbd1a0b3e8`
vip1: `a040cd1184dc511e5aefb74dbd1a0b3e-8080`
vip2: `a040cd1184dc511e5aefb74dbd1a0b3e-7077`

Similarly for pools as well. 

With this approach changes that will be required are:

1. EnsureTCPLoadBalancer: We would have to create one pool per port. 
Each host would be represented as member per port in the appropriate  pools created above. Monitor creation would also have to follow pools. If externalIP is specified that will be passed to create vip for the 1st time, for later ports, ip got back on the 1st vip will be passed in.

2. UpdateTCPLoadBalancer and EnsureTCPLoadBalancerDeleted:  During these operations we have to query Neutron for existing vip and pool; [getVipByName] (https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/openstack/openstack.go#L469) and getPoolByName will have to be changed such that they are regex searches in the tenant.

Sample code could look like:

```
func getVipByName(client *gophercloud.ServiceClient, name string, tenantid string) ([]vips.VirtualIP, error) {
	opts := vips.ListOpts{
		TenantID: tenantid,
	}
	pager := vips.List(client, opts)
	var fullVipList []vips.VirtualIP
	var vipList []vips.VirtualIP
	err := pager.EachPage(func(page pagination.Page) (bool, error) {
		v, err := vips.ExtractVIPs(page)
		if err != nil {
			return false, err
		}
		fullVipList = append(fullVipList, v...)
		return true, nil
	})
	if err != nil {
		if isNotFound(err) {
			return nil, ErrNotFound
		}
		return nil, err
	}

	for _, vip := range fullVipList {
		if strings.Contains(vip.Name, name) {
			vipList = append(vipList, vip)
		}
	}

	if len(vipList) == 0 {
		glog.V(4).Infof("No vips found with name: %s", name)
		return nil, ErrNotFound
	}
	return vipList, nil
}
```
I did explore are little to see if Neutron natively supports regex search like nova, but unfortunately at this point it does not. With this approach it does take a little more time to search through the list if pools and vips, how ever the other alternative is to modify UpdateTCPLoadBalancer and EnsureTCPLoadBalancerDeleted calls to cloudprovider to include ports (currently only EnsureTCPLoadBalancer gets port list)

We currently have it working with this approach, however no scale tests have been run. Please let me know if there is any merit to this, I would be more than happy to send a PR

**Comment by thockin** [comment]
I'm not against adding parameters to these functions if that is a net
simpler solution.

**Comment by spothanis** [comment]
It would definitely make searching vips and pools way more simpler since their names can easily be derived off the service and port combination.

**Comment by thockin** [comment]
It's been a while since I touched that code, so I'll defer to @a-robinson
if he has objections

**Comment by anguslees** [comment]
Alternatively, a generic mechanism where the provider plugin can stash some private data along with the service/loadbalancer object and use it again during destroy would be useful.  The above name-games are only so we can find the various objects later (complicated by the fact that not all relevant openstack objects can _have_ user-provided names).

**Comment by spothanis** [comment]
True; On the lines of provider id of node, a struct to stash all of the cloud provider artifacts

**Comment by a-robinson** [comment]
Yup, I have no issue with adding the ports to the functions' arguments if it'll make the implementation simpler.

Stashing private data would have to be done carefully, since everything still has to function properly if the process gets restarted (or even replaced by a newer version on a different machine). There's no real concept of persistent state in the master other than what's in etcd.

**Comment by spothanis** [comment]
@a-robinson sounds good. I think just being able to get ports in update and delete functions will solve the naming problems.

**Comment by kiall** [comment]
Resolved by https://github.com/kubernetes/kubernetes/pull/30649 ?

**Comment by anguslees** [comment]
@kiall: Yes, we should close this issue now.
