### ISSUE TITLE
Restore ability to enable or disable individual resources

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#62044]
#57228 removed the ability to enable or disable individual resources, which is a breaking change (to apiserver command line flag). This was somehow merged without an action-required release note (actually without any release note), it didn't follow our deprecation policy, and it wasn't announced on any mailing list (so far as I know).

The most obvious thing to do is to roll back this PR and anything that depends on it.

We should also have a discussion about how we can catch breaking changes like this. (My own triage missed it because it didn't have the sig/api-machinery label, for example)

**Comment by lavalamp** [comment]
cc @hzxuzhonghu @deads2k

**Comment by perotinus** [comment]
+1 to rolling back, or somehow reintroducing this functionality. We are depending on runtime-config supporting enabling or disabling individual resources.

**Comment by hzxuzhonghu** [comment]
I can do that if possible.

**Comment by deads2k** [comment]
Rather than roll it back, it probably makes more sense to re-implement the feature just for the kube-apiserver.  Managing individual resources is a really bad idea, only supported for the extensions group today (or rather yesterday) because they weren't related.



> We are depending on runtime-config supporting enabling or disabling individual resources.

You'll really want to rethink that.  Deprecation gives 2 releases for admin facing commands and even when re-added, it'll go back on a cut list.  Removing certain APIs from a group makes for unpredictable behavior.  

I am curious what you're doing with it though..

 1. Scale - always exposed no matter what you do.
 2. RCDummy - in core (you don't disable this)
 3. Deployment - in apps, do you disable that entire group?
 4. DaemonSet - in apps, do you disable that entire group?
 5. Ingress - wouldn't you just not install a controller?
 6. ReplicaSet - in apps, do you disable that entire group?
 7. PodSecurityPolicy - wouldn't you just not enable the admission plugin?
 8. NetworkPolicy - in networking, do you disable that entire group?

Not a single one of those seems very useful to disable without disabling other entire groups.  And we'll never expand the "disable resources" feature to other API groups since it makes it impossible to reason about how the group works as a unit.

**Comment by deads2k** [comment]
> only supported for the extensions group today (or rather yesterday) because they weren't related.

Hrm. I wonder if I accidentally fixed it in the distant (1.3) past: https://github.com/kubernetes/kubernetes/pull/23208 .  That brings back some terrible memories.

**Comment by lavalamp** [comment]
I'm pretty sure it worked for the core group, too.

**Comment by sttts** [comment]
Will work on the 1.11 fix for this, without reverting.

**Comment by nikhita** [comment]
I guess this is still relevant.

/reopen
/remove-lifecycle rotten

**Comment by liggitt** [comment]
We'll want this specifically for the extensions/v1beta1 group as we start turning off the deprecated resources in that group. Opened https://github.com/kubernetes/kubernetes/pull/72249 to add back support for it specifically in that API group.
