### ISSUE TITLE
Feature Request: Create a node's automatic node labels on its pods 

### ISSUE THREAD

**Issue by ghost** [kubernetes/kubernetes#62078]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug

/kind feature

**What happened**:
Cannot tell Kafka broker pod which failure domain it is in for rack-awareness.

**What you expected to happen**: 
Pods would inherit these labels from the node:
https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#interlude-built-in-node-labels

**How to reproduce it (as minimally and precisely as possible)**:
N/A

**Anything else we need to know?**:
This approach would be a kind of alternative to these:
- https://github.com/kubernetes/kubernetes/issues/40610
- https://github.com/kubernetes/kubernetes/pull/25957
- https://github.com/Yolean/kubernetes-kafka/pull/41

Also relevant:
- https://github.com/minio/minio/issues/5738

**Environment**:
- Kubernetes version (use `kubectl version`): v1.10.0
- Cloud provider or hardware configuration: AWS
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools: Kops
- Others:

**Comment by josdotso** [comment]
/sig scheduling  

(?)

**Comment by natronq** [comment]
Related: https://github.com/kubernetes/kubernetes/issues/61906

**Comment by discordianfish** [comment]
@josdotso Any reason you think this is better than providing this in the downward API as #40610 suggested? Feels like the better way to me. I'll try to get #40610 revived.

**Comment by josdotso** [comment]
@discordianfish whatever way works is best for me :) 

Getting access to the node labels natively works for me!

Thanks!

**Comment by solsson** [comment]
In the meantime maybe we could collaborate on a docker image that implements this feature as init container? Preferrably using a k8s lib rather than [bash](https://github.com/Yolean/kubernetes-kafka/pull/41). Env and/or args would tell which node labels to transfer to which labels/attributes. Init containers lend themselves nicely to composition.

**Comment by frittentheke** [comment]
Even the Kubernetes own cluster-autoscaler would benefit from a simple way to get i.e. the AWS_REGION - https://github.com/kubernetes/autoscaler/issues/1208

**Comment by discordianfish** [comment]
@frittentheke Yes, that's what brought me here. Though I feel like this should be part of the downyard API, so personally would close this issue and focus on #40610 instead.

**Comment by gmaslowski** [comment]
@solsson Hi, regarding your comment I've recently stumbled upon the same issue. Here's how I've dealt with it: https://gist.github.com/gmaslowski/117f3535173d733e007d0c6c83564888

**Comment by discordianfish** [comment]
I'd say we close this one and focus on #40610 instead. That seems to be the more idiomatic way to do this.

**Comment by PaulFurtado** [comment]
I want https://github.com/kubernetes/kubernetes/issues/40610 a lot more than these labels, however, I don't think that it eliminates all of the use-cases for these labels. Labels are great because they're possible to query and possible to use in service selectors, disruption budgets etc.

If nothing else, using kubectl or the API to get pods in a given availability zone is difficult right now: you basically need to get all the pods and then cross-reference the list of nodes to get the availability zones the pods are in. Even just the ability to display the availability zone of a pod in kubectl alone would be a big win.

**Comment by PaulFurtado** [comment]
Although, that said, if this issue is implemented for propagating node labels onto pods, then #40610 might not be necessary since the propagated labels would be accessible by the downward api for the pod automatically...

**Comment by danfromtitan** [comment]
Full solution to the problem is [included here](https://github.com/danfromtitan/envars-from-node-labels), the admission controller turns node labels into container env vars for selected container names that are deployed in a specific namespace.

**Comment by mateuszdrab** [comment]
I just banged my head against the wall when I realized the downward API doesn't support pulling node labels into pod envs.
Your solution seems like a good workaround, just deployed it and made it work 😊
Though the deployment steps are quite cumbersome as I had to make lots of changes to rename the target namespace and remove the AWS dependencies. 
I think a docker hub image + helm chart are needed here 🙏
