### ISSUE TITLE
Feature request: CSI plugin support expand volume size

### ISSUE THREAD

**Issue by wavezhang** [kubernetes/kubernetes#62096]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature
/sig storage

**Description**:

Let CSI volume plugin  support expand volume size

/cc @kubernetes/sig-storage-feature-requests

**Comment by sarjeet2013** [comment]
Is there any update on it? Is this being worked on for CSI? Thanks

**Comment by venkatsc** [comment]
@sarjeet2013 look at the proposal thread https://github.com/container-storage-interface/spec/pull/222

**Comment by mlmhl** [comment]
@gnufied   Could we split this feature into smaller phases so that we can track the progress more easily?  As far as I know, we have at least two phases:

1. Add volume expansion API to CSI spec, we already have a proposal: [container-storage-interface/spec#222](https://github.com/container-storage-interface/spec/pull/222)
2. Add expansion support to CSI volume plugin in kubernetes core code. This is also a relatively large work, and maybe we need to split it into more sub jobs.

**Comment by msau42** [comment]
Feature issue: https://github.com/kubernetes/enhancements/issues/556

**Comment by msau42** [comment]
CSI expansion is available as alpha starting with 1.14. See https://kubernetes-csi.github.io/docs/volume-expansion.html for how to implement expansion in your CSI driver.

/close
