### ISSUE TITLE
`daemon-set-controller` bootstrap RBAC policy does not include `get` permission for `controllerrevisions`

### ISSUE THREAD

**Issue by frodenas** [kubernetes/kubernetes#62145]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug
/sig auth

**What happened**:

Testing a daemon-set spec, I deleted/recreated it multiple times. At one of the recreations, the daemon-set was not scheduled anymore, and the number of desired pods went to 0 (on a 3 nodes cluster):

```
$ kubectl get ds -n pks-infrastructure
NAME             DESIRED   CURRENT   READY     UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
nsx-node-agent   0         0         0         0            0           <none>          2m
```

The kube-apiserver stderr logs shows:

```
I0404 14:33:01.871517    5724 wrap.go:42] POST /apis/extensions/v1beta1/namespaces/pks-infrastructure/daemonsets: (7.588801ms) 201 [[kubectl/v1.9.5 (linux/amd64) kubernetes/f01a2bf] 30.0.1.3:38984]
I0404 14:33:01.880581    5724 wrap.go:42] POST /apis/apps/v1beta1/namespaces/pks-infrastructure/controllerrevisions: (7.853889ms) 409 [[kube-controller-manager/v1.9.5 (linux/amd64) kubernetes/f01a2bf/system:serviceaccount:kube-system:daemon-set-controller] 30.0.1.2:50964]
I0404 14:33:01.881572    5724 rbac.go:116] RBAC DENY: user "system:serviceaccount:kube-system:daemon-set-controller" groups ["system:serviceaccounts" "system:serviceaccounts:kube-system" "system:authenticated"] cannot "get" resource "controllerrevisions.apps" named "nsx-node-agent-8f5d66fd6" in namespace "pks-infrastructure"
I0404 14:33:01.881971    5724 wrap.go:42] GET /apis/apps/v1beta1/namespaces/pks-infrastructure/controllerrevisions/nsx-node-agent-8f5d66fd6: (633.24µs) 403 [[kube-controller-manager/v1.9.5 (linux/amd64) kubernetes/f01a2bf/system:serviceaccount:kube-system:daemon-set-controller] 30.0.1.2:50964]
```
The kube-controller stderr logs shows:

```
E0404 14:57:48.743754   10416 daemon_controller.go:265] pks-infrastructure/nsx-node-agent failed with : failed to construct revisions of DaemonSet: controllerrevisions.apps "nsx-node-agent-8f5d66fd6" is forbidden: User "system:serviceaccount:kube-system:daemon-set-controller" cannot get controllerrevisions.apps in the namespace "pks-infrastructure"
```

The (default) permissions for the `system:controller:daemon-set-controller` cluster role are:

```
$ kubectl describe  clusterroles system:controller:daemon-set-controller
Name:         system:controller:daemon-set-controller
Labels:       kubernetes.io/bootstrapping=rbac-defaults
Annotations:  rbac.authorization.kubernetes.io/autoupdate=true
PolicyRule:
  Resources                         Non-Resource URLs  Resource Names  Verbs
  ---------                         -----------------  --------------  -----
  events                            []                 []              [create patch update]
  nodes                             []                 []              [list watch]
  pods                              []                 []              [create delete list patch watch]
  pods/binding                      []                 []              [create]
  controllerrevisions.apps          []                 []              [create delete list patch update watch]
  daemonsets.apps                   []                 []              [get list watch]
  daemonsets.apps/finalizers        []                 []              [update]
  daemonsets.apps/status            []                 []              [update]
  daemonsets.extensions             []                 []              [get list watch]
  daemonsets.extensions/finalizers  []                 []              [update]
  daemonsets.extensions/status      []                 []              [update]
```

Seems to be missing a `get` permission for the `controllerrevisions.apps` resource. I edited manually the cluster-role adding the `get` permission and then the daemonset was scheduled again.

**What you expected to happen**:

The `system:controller:daemon-set-controller` cluster role default permissions should allow getting the `controllerrevisions.apps` resource.

**How to reproduce it (as minimally and precisely as possible)**:

I tried to reproduce it again, but I'm unable to find the exact pattern to reproduce it. 

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): `v1.9.2`
- Cloud provider or hardware configuration: `vSphere`
- OS (e.g. from /etc/os-release): 
```
NAME="Ubuntu"
VERSION="14.04.5 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.5 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
```
- Kernel (e.g. `uname -a`): `Linux dc9711b4-9208-444b-9eac-78048ca082a5 4.4.0-116-generic #140~14.04.1-Ubuntu SMP Fri Feb 16 09:25:20 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools:
- Others:

**Comment by cnedeljkovic** [comment]
Same here (5 node cluster, k8s version 1.9.3, Ubuntu 16.04 LTS, 4.4.0-109-generic).

Deamonset we were trying to create/delete is part of official elastic yaml for metricbeat installation. Problem is specific to daemonset part, other parts of manifests behave correctly on deletion/creation. (https://raw.githubusercontent.com/elastic/beats/6.2/deploy/kubernetes/metricbeat-kubernetes.yaml).

* On 1st create - all 5 nodes were populated (kubectl create -f metricbeat-kubernetes.yaml).
* On 1st subsequent delete followed by create we were stuck with desired 0 and error in scheduler log (E0405 14:09:46.160676       1 daemon_controller.go:265] kube-system/elk-metricbeat failed with : failed to construct revisions of DaemonSet: controllerrevisions.apps "elk-metricbeat-5846d79b77" is forbidden: User "system:serviceaccount:kube-system:daemon-set-controller" cannot get controllerrevisions.apps in the namespace "kube-system").
* However if we changed name of deamonset (metricbeat-v1 for example) it would bring pods on 4 nodes (master missing), setting desired to 4 (instead of 5).
* Again if deleted, neither that name or any previously used name would work (desired 0), while new name would spawn 4 pods (desired 4 instead 5 master missing).
* No stucked pods or jobs, all other not-affected deamonsets (wave-net, kube-proxy, weave-scope) all work fine.

**Comment by cnedeljkovic** [comment]
@krmayankk, maybe this is related: "However if we changed name of deamonset (metricbeat-v1 for example) it would bring pods". New name of deamonset would spaws pods, but any subsequent retry with any of previous names would fail (until we change to new name again). Once we added get to controllerrevisions.apps we were able to spawn pods with previously given names as well, so it might be related...
