### ISSUE TITLE
AWS does not fail when provisioning a volume encrypted with inaccessible KSM key.

### ISSUE THREAD

**Issue by jsafrane** [kubernetes/kubernetes#62171]
This is continuation of #48438 and #48936.

**What happened**:
When StorageClass refers to a key that is not accessible to Kubernetes (i.e. AWS API returns AccessDeniedException), AWS plugin still tries to provision a volume under assumption that while Kubernetes can't access the key, the other components may access it and create the volume and attach it to a node later.

Related code is [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/aws/aws.go#L2205) - `checkEncryptionKey` checks only for `NotFoundException`. Other errors are just logged and provisioning continues.

Problem is that when AWS really can't access the key, it **will** provision some volume (ec2.CreateVolume returns success + valid AWS EBS), but this AWS EBS disappears after few seconds. Therefore Kubernetes does not know that something went wrong and creates a PV for the returned EBS. Kubernetes later fails to run a pod that refers to such PV, because the PV does not exist.

**What you expected to happen**:
Kubernetes must not create PV in this case and must report error during provisioning of such volume.

Ideas:

* According to [AWS documentation](https://docs.aws.amazon.com/kms/latest/developerguide/services-ebs.html), the only signal that AWS produces is an event in Amazon CloudWatch Events that a key could not be used for encryption. Kubernetes AWS cloud provider is not subscribed to these events and does not get this notification. We would need new permission for controller-manager to get the events and some new code to filter them and report back to user.

* Kubernetes AWS cloud provider could wait for X seconds and re-check that created volume still exists and did not disappear because of inaccessible key. What would be reliable value of X?

* Kubernetes volume plugin for AWS could return both a warning "I failed to check encryption key, created volume may not work" that would be propagated to user **and** the suspicious volume at the same time, but the API between volume plugins and Kubernetes allows only one - either error or volume. It could be extended, still the user experience would be suboptimal.

* Kubernetes could send an error to user during volume attach (!) that a volume does not exist, please check your KMS key permissions. Again, UX is quite bad here.

/kind bug
/sig aws

**Comment by randomvariable** [comment]
Checking the KMS key feels wrong here, as you could still create an encrypted EBS volume and not have the DescribeKey permission in IAM or via the key policy.

If the main source of errors are sent via CloudWatch Events, then best practice would seem to be to subscribe via SNS to receive those events.

Possibly fall back to vague "send an error to user during volume attach (!) that a volume does not exist, please check your KMS key permissions," where a SNS topic isn't provided, but otherwise use CloudWatch events to enrich state/messages. 

Would then also need to change docs to reflect needing to set up CloudWatch Events -> SNS topic. 

Big drawback of going down this route is a fair few downstream cluster bootstrap projects would likely need updating to support it in their CloudFormation / Terraform bits.

**Comment by jsafrane** [comment]
According to @gnufied it takes quite a long time until an event is available in CloudWatch events.

@gnufied, what was the average / maximum delay?

**Comment by gnufied** [comment]
I haven't calculated the metrics accurately but the cloudwatch events arrival vary(and standard deviation was high).  Using cloudwatch events was also considered for maintaining instance cache and @justinsb @chrislovecnm as well concluded that - they are not realtime (AWS itself documents them as "near realtime"). It may be - we need to measure them again and find out if we can use them for the purpose here.

>Checking the KMS key feels wrong here, as you could still create an encrypted EBS volume and not have the DescribeKey permission in IAM or via the key policy.

@randomvariable from jan's analysis above it appears that - if IAM does not have permission to DescribeKey then EBS volume gets created but then it disappears soon. So net result still is - if "current user" can't describekey, she can't provision the volume. Is there any documentation that indicates otherwise? cc @arun-gupta

**Comment by randomvariable** [comment]
Testing this for real now.

User creates volume with no access to underlying CMK, or insufficient permissions does not seem to generate events with sufficient information as to what went wrong, i.e. don't appear to receive events for create volume failure, only deletion. E.g.:
```
{
    "version": "0",
    "id": "<guid>",
    "detail-type": "EBS Volume Notification",
    "source": "aws.ec2",
    "account": "<accountid>",
    "time": "2018-04-11T13:57:04Z",
    "region": "eu-west-2",
    "resources": ["arn:aws:ec2:eu-west-2:<account>:volume/<volid>"],
    "detail": {
        "result": "deleted",
        "cause": "",
        "event": "deleteVolume",
        "request-id": "<requestid>"
    }
}
```

This policy is sufficient to allow the creation of volumes - `DescribeKey` isn't necessary for the volume to be created.
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "Minimal_EBS_Permissions",
            "Effect": "Allow",
            "Action": [
                "kms:Decrypt",
                "kms:GenerateDataKeyWithoutPlaintext"
            ],
            "Resource": "<key arn>"
        }
    ]
}
```
It isn't sufficient to attach the volume however, creating the following error,
```
An error occurred (CustomerKeyHasBeenRevoked) when calling the AttachVolume operation: Volume <vol_id> cannot be attached. The encrypted volume was unable to access the KMS master key.
```

The `CreateGrant` permission's required to fix this, to delegate access to EC2 itself:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "Minimal_EBS_KMS_Create_and_Attach",
            "Effect": "Allow",
            "Action": [
                "kms:Decrypt",
                "kms:GenerateDataKeyWithoutPlaintext",
                "kms:CreateGrant"
            ],
            "Resource": "key arn"
        }
    ]
}
```

Bit of experimentation shows that only `CreateGrant` is required for attaching - the ones for creating the volume aren't needed at the attachment stage.

The docs at https://github.com/awsdocs/aws-kms-developer-guide/blob/master/doc_source/services-ebs.md#amazon-ebs-encryption is therefore correct for volume creation, but doesn't describe the volume attachment scenario.

**Comment by jsafrane** [comment]
So, what is our solution then? From the above it seems Kubernetes can't reliably check if a key is usable for encryption of a PV. And it can't get an usable event either.

**Comment by randomvariable** [comment]
Possibly one of the following:

1. No change. Live with the pain.

2. Run "GenerateDataKey" and "Decrypt" on the generated ciphertext blob prior to volume creation as a preflight check.
The advantage being that we can throw an error that this isn't going to work beforehand, but with the disadvantage of doubling up API calls. This is probably fine, and I think if you're creating encrypted volumes at a rate that's likely to run into API call limits or get super expensive, you might have other problems?

We then also do the CreateGrant check during volume attachment (as an optional extra).

3. Do the same check, but only after an error. Problem being that we get much less in the way of guaranteeing what the root cause is, but we don't add to the API calls in the happy path.

In any case, is this bug biting sufficiently to fix here, or should we start thinking about the CSI implementation?

**Comment by jsafrane** [comment]
@randomvariable, thanks a lot for detailed investigation. I'll try to get some time to implement 2. even before CSI. Users are very innovative in setting up their cluster permissions wrong and the messaging to user is very confusing in this particular issue.

**Comment by jsafrane** [comment]
@randomvariable, 2. does not work.

Kubernetes does not need to have GenerateDataKey and Decrypt permissions to create encrypted volume. My AWS account is severely limited (I am using shared company account) and I can't call GenerateDataKey on a key:

```
User: arn:aws:iam::<censored>:user/jsafrane is not authorized to perform: kms:GenerateDataKey on resource: arn:aws:kms:us-east-1:531415883065:key/55c387de-201e-4dd0-9a22-3802c96d038b
```

But I can create encrypted EBS using the same key:

```
$ aws ec2 create-volume --encrypted --kms-key-id arn:aws:kms:us-east-1:531415883065:key/55c387de-201e-4dd0-9a22-3802c96d038b  --availability-zone us-east-1d  --size 1
{
    "AvailabilityZone": "us-east-1d",
    "CreateTime": "2018-06-19T09:02:40.000Z",
    "Encrypted": true,
    "KmsKeyId": "arn:aws:kms:us-east-1:531415883065:key/55c387de-201e-4dd0-9a22-3802c96d038b",
    "Size": 1,
    "SnapshotId": "",
    "State": "creating",
    "VolumeId": "vol-07466ac2e94d3d295",
    "Tags": [],
    "VolumeType": "standard"
}
```
The volume gets created successfully. It's not the user who runs Kubernetes who needs permissions for GenerateDataKey, it's AWS itself.

**Comment by randomvariable** [comment]
And the volume stayed created and didn't get reaped after a few seconds?

I was confused about this part, it didn't seem to follow how the APIs should work. Has anyone ever created a volume with that key, or is it a new one? I'll try what I did previously in a bit across a few regions.

**Comment by jsafrane** [comment]
> And the volume stayed created and didn't get reaped after a few seconds?

Yes, the volume stayed around for several minutes, then I deleted it manually. The key is our default encryption key, so when I create an encrypted volume with no key, I get this one. No zones, no regions involved.

**Comment by jsafrane** [comment]
I got an idea, the volume is "creating" and then it gets "available". I could `DescribeVolumes` in a loop until newly created volume either gets "Available" or deleted. This will abuse the API quota (`Describe*` is cheap, right?) + it will slow down provisioning a bit - all volumes I tried were Available in a second or two. Will it work reliably enough?

**Comment by randomvariable** [comment]
Might be the difference then, as I don't think the same perms as I described above are needed for the default key as I assume that it gets automatically delegated to the EC2 service. I only tested & documented the explicit, alternate key path above.

Your approach should work, but I don't know when EC2 API limits will kick in and how soon users would see that happen. Worth a shot though?

**Comment by jsafrane** [comment]
It takes ~4 seconds for a volume to reach "available", it's quite a long time. This will affect encrypted volumes with explicit keys only.

**Comment by jsafrane** [comment]
Fix: https://github.com/kubernetes/kubernetes/pull/65223
