### ISSUE TITLE
Automated and standard build for kubernetes project Docker images

### ISSUE THREAD

**Issue by vmarmol** [kubernetes/kubernetes#6222]
This is particularly useful for those images used in e2e tests. Today each image has its own scripts to build and deploy, there is no automation and no conventions throughout.

/cc @ArtfulCoder who has done some work on auto-building images.

**Comment by pmorie** [comment]
@lavalamp @vmarmol FWIW this seems like it would be nice to have for 1.0

**Comment by jayunit100** [comment]
hi this is a greate idea.  we've been talking about it in #6183 and #5465 also

**Comment by jayunit100** [comment]
There are many proposed ways to solve the kubernetes images problem

- secure docker builds
- putting a Makefile in with each docker recipe in the examples/
- having a top level `images` directory in kuberntes, which builds a bunch of images as part of the standard build.

each has its own benefits.  i prefer the "put all docker content in one directory" approach, from a code hygeine perspective, otherwise its almost impossible to gaurantee that people are really properly leveraging the unified kube docker build infrastructure, and Dockerfiles will just have a tendency to creep up in random places.

**Comment by chrislovecnm** [comment]
This is awesome!

**Comment by abitrolly** [comment]
Building Docker images in a unified way is a common problem for any multi-part application or Kubernetes. Here is my alpha attempt to tackle this problem - https://github.com/cyberFund/cybernode/tree/master/images - I tried to decouple application build scripts from Docker to leave space for trying LXD, rkt and etc.

Critics and feedback is welcome. Explaining Kubernetes requirements and workflows where image build process is used will allow me to send pull request for this issue.
