### ISSUE TITLE
Some cluster components still using JSON for api calls

### ISSUE THREAD

**Issue by shyamjvs** [kubernetes/kubernetes#62277]
Today, while looking at some e2e metrics for our scale tests I saw that there are still few things that are using json instead of protobuf.
Should these be moved to protobuf or do we have a reason to not?

Here's a rough list of components using json ([ref](https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/114/artifacts/MetricsForE2E_density_2018-02-21T11:40:45Z.json)):

- event-exporter/v0.0.0 (for `watch events`)
- glbc/v0.0.0 (for `get configmaps`, `watch nodes`, `watch pods`, `watch services`, `watch ingresses`)
- kube-controller-manager/v1.11.0:generic-garbage-collector (for `get pods`, `delete pods`, `watch scalingpolicies`, `watch networkpolicies`)
- kubectl (for various calls) - seeing issue https://github.com/kubernetes/kubernetes/issues/50403 for this
- node-problem-detector/v1.4.0 (for `patch node-status`)

cc @kubernetes/sig-api-machinery-bugs @liggitt @wojtek-t

**Comment by shyamjvs** [comment]
The one with NPD was surprising even for me - as those 'patch node' calls
are made in huge numbers and this may be a low-hanging fruit for us.

cc @Random-liu

**Comment by wenjiaswe** [comment]
cc @mbohlool

**Comment by mbohlool** [comment]
Only one part of this (kube-control-manager) is api-machinery. I suggest you divide this issue into more specific issues and assign them to the right sig.

**Comment by lavalamp** [comment]
You can't send patches in proto format. So NPD is likely correct. Only if it is *reading* in json is it incorrect.

**Comment by lavalamp** [comment]
Ah, the OP lists the methods used. Please file issues for the below:

* GC "get pods" in JSON is wrong. (this is ours)
* event-exporter watch events in JSON is wrong.
* glbc - don't actually know what that is, but likely those things should be in proto :)

**Comment by wojtek-t** [comment]
> GC "get pods" in JSON is wrong. (this is ours)

@lavalamp - as I wrote before, I think this is because GC is using dynamic client, which from what I know (at least few months ago) didn't even support protobufs. Was it fixed in the meantime?

**Comment by liggitt** [comment]
> this is because GC is using dynamic client, which from what I know (at least few months ago) didn't even support protobufs. Was it fixed in the meantime?

Not all APIs support protobuf, so no

**Comment by wojtek-t** [comment]
> Not all APIs support protobuf, so no

Can't we solve that by passing accept header set to: "application/kubernetes.protobuf.vnd, */*" which would result in negotiation code choosing:
- protobuf it is supported for a given API
- json otherwise

In the client we already decode data based on ContentType header value IIRC, so assuming it will be set correctly, it should work.

What am I missing?

**Comment by smarterclayton** [comment]
It would not be able to today, not without enforcing some extra constraints
that we haven’t dealt with.  So not possible without a lot more work.

If the generic client wants to get only objectmeta, we should be doing that
via the generic conversion support, in which case you can get a
PartialObjectMetadata as protobuf but you won’t be able to do anything
generic.

On Apr 14, 2018, at 9:18 AM, Jordan Liggitt <notifications@github.com>
wrote:

That might work, but I think receiving protobuf requires the client to have
the schema for the particular type it is receiving. I'm not sure if the
generic client could interpret a proto response from an extension apiserver
enough to extract objectmeta data (it might… @smarterclayton
<https://github.com/smarterclayton> might know)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/62277#issuecomment-381328624>,
or mute the thread

**Comment by smarterclayton** [comment]
Accept: application/vnd.kubernetes.protobuf;as=PartialObjectMetadataList;g=meta.k8s.io;v=v1beta1

Should result in a list you can decode from any compatible apiserver.  If you add the fallback to raw json you can then fallback for older extension apiservers.

**Comment by wojtek-t** [comment]
@liggitt @smarterclayton - thanks for clarification.

That said, I have a follow-up question. If I would imagine a situation, that I'm using a dynamic client just for convenient implementation, but I know what exact types I'm using and I know I have their proto schemas linked in, the what I proposed with accept header, should work, right?

**Comment by wojtek-t** [comment]
Was the NPD using json fixed?

**Comment by makoscafee** [comment]
@smarterclayton Hello! I'm bug triage shadow for the 1.16 release cycle and considering this issue is tagged for 1.16, but not updated for a long time, I'd like to check its status. The code freeze is starting on August 29th (about 1.5 weeks from now), which means that there should be a PR ready (and merged) until then.

Do we still target this issue to be fixed for 1.16?

**Comment by smarterclayton** [comment]
The k/k specific issues are now resolved.

**Comment by xmudrii** [comment]
@smarterclayton What should be done before this issue can be closed or removed from the milestone?

**Comment by wojtek-t** [comment]
I looked into it for our scalability tests recently, and there are 8 components that are still using json:
- Prometheus server
- Prometheus operator
- ClusterLoader [this one is expected, we want to send json calls too]
- event-exporter
- glbc
- kubectl [I think this one is addon-manager, TBV]
- metrics-server
- pod-nanny

I already started migrating some of those.

**Comment by wojtek-t** [comment]
To update:
- event-exported was fixed in https://github.com/kubernetes/kubernetes/pull/83396
- metrics-server was fixed in https://github.com/kubernetes/kubernetes/pull/83015 [still SubjectAccessReviews are being send via JSON, but that would be a larger effort to address it, so we're going to keep as is]

PRs to fix in glbc were merged, we're waiting for the glbc patch release.

**Comment by josiahbjorgaard** [comment]
Bug triage for 1.17 here. This issue has been open for a significant amount of time and since it is tagged for milestone 1.17, we want to let you know that the 1.17 code freeze is coming in less than one month on Nov. 18th. Will this issue be resolved before then?

**Comment by wojtek-t** [comment]
glbc was fixed in https://github.com/kubernetes/kubernetes/pull/84018

The remaining are:
- prometheus and its operator
- addon-manager

Tracking those in this umbrella bug doesn't make sense. So I'm closing this one.
