### ISSUE TITLE
Creating a deployment ignores apiVersion

### ISSUE THREAD

**Issue by lainekendall** [kubernetes/kubernetes#62283]
**Is this a BUG REPORT or FEATURE REQUEST?**:
 /kind bug

**What happened**:
`kubectl apply -f deploy.yaml` where `deploy.yaml` is copied directly from the documentation https://kubernetes.io/docs/concepts/workloads/controllers/deployment/:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80
```
Then `kubectl get deployment nginx -o yaml` produces:
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"nginx"},"name":"nginx-deployment","namespace":"booking-ci"},"spec":{"replicas":3,"selector":{"matchLabels":{"app":"nginx"}},"template":{"metadata":{"labels":{"app":"nginx"}},"spec":{"containers":[{"image":"nginx:1.7.9","name":"nginx","ports":[{"containerPort":80}]}]}}}}
    kubernetes.io/change-cause: kubectl create --filename=nginx.yaml --save-config=true
      --record=true
  creationTimestamp: 2018-04-09T14:45:01Z
  generation: 1
  labels:
    app: nginx
  name: nginx-deployment
  namespace: booking-ci
  resourceVersion: "1262711"
  selfLink: /apis/extensions/v1beta1/namespaces/booking-ci/deployments/nginx-deployment
  uid: 953da97b-3c04-11e8-89a6-12c80c583b80
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nginx
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx:1.7.9
        imagePullPolicy: IfNotPresent
        name: nginx
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 3
  conditions:
  - lastTransitionTime: 2018-04-09T14:45:05Z
    lastUpdateTime: 2018-04-09T14:45:05Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: 2018-04-09T14:45:01Z
    lastUpdateTime: 2018-04-09T14:45:05Z
    message: ReplicaSet "nginx-deployment-6c54bd5869" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 3
  replicas: 3
  updatedReplicas: 3
```

**What you expected to happen**:
To have a deployment named `nginx` that is of `apiVersion: apps/v1` or whatever `apiVersion` is specified in the yaml. Or to get an error saying `cannot create deployment with apiVersion apps/v1`.
**How to reproduce it (as minimally and precisely as possible)**:
Above has all necessary steps. 

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-09T21:50:44Z", GoVersion:"go1.9.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"archive", BuildDate:"2018-02-16T10:14:13Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
`kubectl api-versions`
```
admissionregistration.k8s.io/v1beta1
apiextensions.k8s.io/v1beta1
apiregistration.k8s.io/v1beta1
apps/v1
apps/v1beta1
apps/v1beta2
authentication.k8s.io/v1
authentication.k8s.io/v1beta1
authorization.k8s.io/v1
authorization.k8s.io/v1beta1
autoscaling/v1
autoscaling/v2beta1
batch/v1
batch/v1beta1
certificates.k8s.io/v1beta1
events.k8s.io/v1beta1
extensions/v1beta1
networking.k8s.io/v1
policy/v1beta1
rbac.authorization.k8s.io/v1
rbac.authorization.k8s.io/v1beta1
settings.k8s.io/v1alpha1
storage.k8s.io/v1
storage.k8s.io/v1beta1
v1
```

Also if `apiVersion` is changed to `apps/v1beta1` or `apps/v1beta2` before creating the deployment resource, it also defaults to `extensions/v1beta1`.

**Comment by janetkuo** [comment]
`kubectl get` uses server-preferred order, which will prefer the `extensions` API group for backward compatibility, until `extensions` is removed. That is to say, `kubectl get deployment` uses extenions/v1beta1 endpoint by default. 

To get deployments under `apps` API group, you can use `kubectl get deployment.apps`, which returns you `apps/v1` deployments. 

Note that the API version used to create deployments does not affect what API version you get from `kubectl`. The differences between API versions are things like default values and field names. Because API versions are round-trippable, you can safely get the same deployment object with different API version endpoints. 

Closing because it's not a bug.

**Comment by lainekendall** [comment]
Thanks for the response! Very interesting behavior. Is there documentation for this?

**Comment by midhun-mohan** [comment]
@janetkuo can you please let me know how to find the api version an object is deployed to k8s ?

Context of the question : 
I was able to see the same deployments in both api groups apps/v1  and extensions/v1beta1
although the objects were deployed with apps/v1.

i was also trying to find the objects which i need to migrate due to the deprecation of apis in 1.16.

**Comment by janetkuo** [comment]
@midhun-mohan you only need to convert the version stored in etcd from deprecated version to the supported version. This is usually done automatically by k8s when you edit a resource after upgrading your cluster. 

Please take a look at this tool to help you migrate storage version in bulk. https://github.com/kubernetes-sigs/kube-storage-version-migrator

As for your question: 
> I was able to see the same deployments in both api groups apps/v1 and extensions/v1beta1
although the objects were deployed with apps/v1.

This simply means that both API versions are supported in your cluster. The version that matters is the version that's used to store the resource in etcd. 

For more details, please reach out to API machinery SIG.

**Comment by yuskul** [comment]
@janetkuo
If 
> this simply means that both API versions are supported in your cluster. 

then please, explain, why `hpa` (HorizontalPodAutoscaler) does not work with newer features, from the newer API, like scaling on non CPU-metrics (RAM-, custom-metrics)?

As you mentioned above, by default it shows (or provides) older API, for backward compatibility.
How to set to use the newer one for `hpa`? In the output is shows different spec (with out any metrics), then I provided.

Thanks in advance.

**Comment by wyardley** [comment]
If you're, for example, doing reporting on _which_ versions are out of date in the first place, how would one use `kubectl` to find the deployment version?

I do personally find it pretty confusing that the last applied version annotation (and web UI, for GKE) show `apps/v1`, and `kubectl get deployment -oyaml` shows `extensions/v1beta1` (when the only deployment that exists is an `apps/v1` one), especially since `kubectl describe deployments` doesn't support viewing this information either. It may not be a bug in your opinion, but it seems pretty confusing.

**Comment by yuripastushenko** [comment]
/reopen
We provide k8s cluster as a service.
Now we run an old version of kubernetes.
In a few weeks we plan to upgrade cluster version to latest 1.16.x.
We have a lot of users that deploys their applications from different CI.
Part of them uses actual version for deployments (apps/v1) and the other part is using apps/v1beta1,  that is absent in 1.16.1.
We, as cluster administrators, want to notify only them (who use apps/v1beta1) to change the version of api for deployments to apps/v1, before upgrading.
But we don't know how to separate this 2 groups of users.
When we do `kubectl get deploy --all-namespaces` - all deployments are in version extensions/v1beta1.
The users use helm to deploy the applications - so we don't have the field "kubectl.kubernetes.io/last-applied-configuration".
Is there any solution for our case?

**Comment by yuripastushenko** [comment]
We found a workaround in our case.
All deployments in our cluster are created using helm.
So we parsed output of "helm get manifest -n $NAMESPACE $RELEASE".

**Comment by mailjunze** [comment]
Deep diving into this I found objects  created in K8s stored in the latest stable API group. In case of deployment that is apps/v1. When you create a deployment using "extensions/v1beta1" in k8s 1.15, it will be stored in ETCD within the "apps/v1" API group, however, when retrieving you can request for  any supported API group for that k8s version.
## 1.15
```
ec2-user@ip-172-31-9-12:~
▶ kubectl get deployment.apps nginx-deployment -o json  | jq .apiVersion
"apps/v1"
```
```
ec2-user@ip-172-31-9-12:~
▶ kubectl get deployment.extension nginx-deployment -o json  | jq .apiVersion
"extensions/v1beta1"
```
##  1.16
```
ec2-user@ip-172-31-9-12:~
▶ kubectl get deployment.apps nginx-deployment -o json  | jq .apiVersion
"apps/v1"
```

```
ec2-user@ip-172-31-9-12:~
▶ kubectl get deployment.extension nginx-deployment -o json  | jq .apiVersion
error: the server doesn't have a resource type "deployment"
```
Without mentioning the API group, In k8s 1.15 for backwards compatibility, client retrieves extensions API group first. 
```
kubectl get deployment nginx-deployment -o json  | jq .apiVersion
"extensions/v1beta1"
```
There is no extension API group supported for deployment in 1.16, so client retrieves  only apps/v1
```
kubectl get deployment nginx-10range -o json  | jq .apiVersion
"apps/v1"
```

[sig-architecture/api_changes.md](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api_changes.md)
https://github.com/kubernetes/kubernetes/issues/58131#issuecomment-356823588

**Comment by jvanwygerden** [comment]
In order to verify K8s resources are using the apps/v1 API version, can anybody confirm the following commands are valid for testing that ? 

It is currently the best test I can think of, to verify

____________________

1) K8s Deployments (Command - verify K8s Deployment resource is using apps/v1)

kubectl -n <desired-namespace> get deployments.apps <K8s-deployment> -oyaml | grep apiVersion

# Example Output: 

# apiVersion
# apiVersion: apps/v1
#              apiVersion: v1

2) K8s Deployments (Command - verify K8s ReplicaSet resource is using apps/v1)

kubectl -n <desired-namespace> get rs <desired-replica-set> -oyaml | grep apiVersion

# Example Output:

# apiVersion: extensions/v1beta1
#  - apiVersion: apps/v1

**Comment by jvanwygerden** [comment]
In order to verify K8s resources are using the apps/v1 API version, can anybody confirm the following commands are valid for testing that ?

It is currently the best test I can think of, to verify

1) K8s Deployments (Command - verify K8s Deployment resource is using apps/v1)
kubectl -n get deployments.apps -oyaml | grep apiVersion

Example Output:
apiVersion: apps/v1
              apiVersion: v1

K8s Deployments (Command - verify K8s ReplicaSet resource is using apps/v1)
kubectl -n get rs -oyaml | grep apiVersion

Example Output:
apiVersion: extensions/v1beta1
  - apiVersion: apps/v1

**Comment by jvanwygerden** [comment]
In order to verify K8s resources are using the apps/v1 API version, can anybody confirm the following commands are valid for testing that ?

It is currently the best test I can think of, to verify

1) K8s Deployments (Command - verify K8s Deployment resource is using apps/v1)
kubectl -n get deployments.apps -oyaml | grep apiVersion

Example Output:
apiVersion: apps/v1
apiVersion: v1

2) K8s Deployments (Command - verify K8s ReplicaSet resource is using apps/v1)
kubectl -n get rs -oyaml | grep apiVersion

Example Output:
apiVersion: extensions/v1beta1
apiVersion: apps/v1

**Comment by wyardley** [comment]
For us, using the `last-applied-configuration` field worked pretty reliably. I would suggest using `jq` or `yq` over grep.

**Comment by jvanwygerden** [comment]
Thank you for the feedback @wyardley !

**Comment by shyamjos** [comment]
I am using this command 
`kubectl apply view-last-applied deployment/nginx-ingress-controller -n ingress-nginx`

**Comment by moskit** [comment]
One obvious problem with this approach is that if a target definition includes the API version, one cannot get it from the declarations and have to fetch the actual version from etcd first.
Well, not a real problem, but a little frustrating.

**Comment by chanchalmishradevops** [comment]
Guys, 

When I use the command:
kubectl get deployments.apps deploymentname ==> with this command, I am able to see all my deployments shows ApiVersion as apps/v1  ( Here , Do I still need to edit the ApiVersion?)
and when I use 
kubectl get deployments deploymentname ==>With this command, I am able to see all my deployments shows ApiVersion as extensions/v1beta1

Now my questions is:

Do I still need to edit my ApiVersion in my Yaml files?  as you can see above 1st command, gives me the apps/v1, does that mean, I am ok to go for EKS1.16 deployment, and once its deployed, it will automatically fetch the apps/v1 deployment.

Please advise.
