### ISSUE TITLE
Archival log of K8s resources

### ISSUE THREAD

**Issue by jlewi** [kubernetes/kubernetes#62492]
FEATURE REQUEST?

/kind feature

Opening this issue to see if there is any work or thought about emitting a log of K8s jobs to some durable storage system for archival purposes.

The use case is you submit a bunch of batch workloads (K8s Jobs, Argo Workflows, Spark jobs, TF Jobs). There is a lot of valuable information the K8s job spec (e.g. Docker image used, command line arguments, resource spec). For data provenance purposes its often useful to persist this information long after we would want to delete the object from the APIServer.

It would be nice if K8s provided a general mechanism (similar to cluster level logging) to export these records to a suitable backend.

There's a proposal floating around in Kubeflow to do this kubeflow/kubeflow#264; but there's nothing about this proposal that's Kubeflow specific as opposed to K8s.

/cc @vishh

**Comment by foxish** [comment]
[Ark](https://github.com/heptio/ark) does part of this - backing up all the config for the purpose of restoration; part of that could be leveraged to build this. I think right now, applications solve this in different ways - for example, Spark has the [History Server](https://spark.apache.org/docs/latest/monitoring.html#viewing-after-the-fact). I think that's because these applications represent history in specific ways. However, irrespective of how we expect consumption of this information, it seems useful to have a way to publish it elsewhere.
