### ISSUE TITLE
Add K8S_POD_UID argument in CNI Runtime Config

### ISSUE THREAD

**Issue by jyparketc** [kubernetes/kubernetes#62900]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind feature

**What happened**:
kubelet passes pod informations(K8S_POD_NAMESPACE, K8S_POD_NAME) to CNI Network Plugin.
(https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockershim/network/cni/cni.go#L286,L325)
And the plugins use that informations to register pod.
Generally pod name is randomly generated.
But when the pod name is specified (statefulesets) and the pod is created as soon as the pod is deleted with same name, the plugin registers same name pod before previous pod is deleted in registry.
It causes pod registration conflict.
So if kubelet passes pod UID and the plugins use it,  this issue will not be occurred.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by edwardbadboy** [comment]
Agree.

When K8S performs a rolling update for a Stateful Set, the old and new Pod names are the same, the only field for distinguishing old and new Pods is  K8S_POD_INFRA_CONTAINER_ID. 

K8S_POD_INFRA_CONTAINER_ID value is the 'pause' container ID, so it is local to the node. It would be great if the Pod UID is added to the CNI request. This would help the CNI plugins a lot to simplify the processing for this case.

**Comment by edwardbadboy** [comment]
Add a comment to see if we can reopen the issue.

**Comment by abhiraut** [comment]
probably related to area/kubelet ?

**Comment by jayunit100** [comment]
so, making sure i understand this question - workaround: could a CNI provider just have its own controller which monitored pods by name, and kept an up to date UUID mapping ?

**Comment by edwardbadboy** [comment]
Thanks, Abhshek, Jay.

> question: Is there a high implementation cost to increasing the amount of args we send?

I also think the answer is no. It's adding 1 more field to the existing arguments. The length of the Pod uid value is limited, too.

> workaround1: could a CNI provider just have its own controller which monitored pods by name, and kept an up to date UUID mapping ?

I think the problem is that if kubelet doesn't provide Pod uid, it's not possible to keep the mapping correct for StatefulSet. Suppose the CNI plugin knows all Pod names and uids from Kubernetes apiserver. When Kubernetes performs a rolling update on a StatefulSet, there would be two Pod uids under the same name. The CNI plugin doesn't know if a CNI request is for the old Pod uid or the new Pod uid.

> question: Is the only issue here the fact that we want to know if a pod is new ? Or do we need the UUID of the exact pod for something very specific?

As mentioned earlier for StatefulSet rolling update, it's possible for old Pod being destroyed and new Pod being created at the same time on the same worker node. It's also possible for the old and new Pod CNI requests to be issued in any order. The CNI plugin wants to correlate the CNI requests to the Pod uids. No more info is needed.

> workaround2: could a CNI use the timestamp of the add directive to unambiguously determine wether a pod is 'new' or not?

I think using a timestamp is not perfect. Usually the CNI plugin is stateless. It then needs to store elsewhere and keep it up-to-date.

So the key requirement here is allowing CNI plugins to correlate various kind(ADD/DEL) of CNI requests to a particular Pod uid.
