### ISSUE TITLE
Failing Test : [sig-scalability] Density [Feature:Performance] should allow starting 30 pods per node using { ReplicationController} with 0 secrets, 0 configmaps and 0 daemons

### ISSUE THREAD

**Issue by AishSundar** [kubernetes/kubernetes#63030]
## Failing Job
[sig-release-master-blocking#gce-scale-performance](https://k8s-testgrid.appspot.com/sig-release-master-blocking#gce-scale-performance)

Failing Test
[[sig-scalability] Density [Feature:Performance] should allow starting 30 pods per node using { ReplicationController} with 0 secrets, 0 configmaps and 0 daemons](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/142)

Triage results
https://storage.googleapis.com/k8s-gubernator/triage/index.html?sig=scalability&job=ci-kubernetes-e2e-gce-scale-performance

/kind bug
/priority failing-test
/priority important-soon
/sig scalability
/milestone v1.11
@kubernetes/sig-scalability-bugs -bugs 

cc @jberkus @tpepper

/assign @shyamjvs for triage

**Comment by shyamjvs** [comment]
This issue is being taken care of in https://github.com/kubernetes/kubernetes/issues/62064 and https://github.com/kubernetes/kubernetes/issues/62808.

**Comment by AishSundar** [comment]
I still see these failing consistently. https://k8s-testgrid.appspot.com/sig-release-master-blocking#gce-scale-performance

**Comment by AishSundar** [comment]
@shyamjvs @wojtek-t is there an ETA on fixing this test failure? This is currently on of the few tests failing our sig-release master blocking suite. If this is not fixed we will have to delay beta for 1.11 

@tpepper @jberkus as FYI

**Comment by AishSundar** [comment]
We also have another test failing in  https://k8s-testgrid.appspot.com/sig-release-master-blocking#gce-scale-performance

Logs
[[sig-scalability] Load capacity [Feature:Performance] should be able to handle 30 pods per node { ReplicationController} with 0 secrets, 0 configmaps and 0 daemons](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/148)

Triage results
https://storage.googleapis.com/k8s-gubernator/triage/index.html?sig=scalability&job=ci-kubernetes-e2e-gce-scale-performance

**Comment by shyamjvs** [comment]
The load capacity test failures were mostly because of #60372 IIUC and that was fixed by it's reverting PR few days later.
The longer term density test failures seems to be another regression (I'm currently looking into it). At this point, I'd say this EOW as a reasonable ETA.

**Comment by shyamjvs** [comment]
So I took a look into the density test failures and ~all the failures in the streak were due to high latencies of 'DELETE pods' request (and sometimes 'POST configmaps' also).
E.g from [run-150](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/150):

```
WARNING Top latency metric: {Resource:pods Subresource: Verb:DELETE Scope:namespace Latency:{Perc50:7.023ms Perc90:1.232998s Perc99:1.846284s Perc100:0s} Count:310025}
WARNING Top latency metric: {Resource:configmaps Subresource: Verb:POST Scope:namespace Latency:{Perc50:2.119ms Perc90:13.776ms Perc99:1.260952s Perc100:0s} Count:764}
```

From the graph of the latency across runs, there was a jump across runs 141 and 142:

![lat](https://user-images.githubusercontent.com/4333971/39819657-4468a22e-53a4-11e8-95c3-f183a616ecf9.png)

**Comment by liggitt** [comment]
> cc @enj @deads2k @liggitt - Any idea why this happened? Also, can we revert the change?

Does the scale test environment enable the OwnerReferencesPermissionEnforcement admission plugin? That's the only plugin using that rest mapper that I can see, and I didn't think it was on by default

**Comment by enj** [comment]
It is the only plugin we have that uses that REST mapper...

**Comment by shyamjvs** [comment]
Let me run twice with and without the change to confirm.

**Comment by liggitt** [comment]
It looks like the QPS on the client used for internal loopback requests is set to 50 here:
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/server/config_selfclient.go#L40-L45

Using that client for discovery uses ~25 requests every 10 seconds to maintain the list of active resources.

That client is also used by the node restriction admission plugin in pod deletion cases:
https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/admission/noderestriction/admission.go#L185-L187

During a deletion storm, it seems likely that client is throttling itself already, and also using it for discovery could have affected it slightly, though I wouldn't have expected nearly a doubling effect (50 QPS == 500 available requests per 10 second period, of which the newly added discovery would have taken 5%)

As a first step, I'd likely try:
* bumping QPS by ~10 made a difference
* lengthen the resource rediscovery period to 20-30 seconds

As a next step, I'll look into reworking the node restriction plugin to work off the node->pod graph we already have in place rather than requiring live lookups on deletion

**Comment by shyamjvs** [comment]
On a somewhat related note (though from a different time - around yesterday) we started seeing failures in even our 100-node performance tests - https://k8s-testgrid.appspot.com/sig-scalability-gce#gce

And the reason there is also exactly the same, i.e increased `delete pod` latency:

```
WARNING Top latency metric: {Resource:pods Subresource: Verb:DELETE Scope:namespace Latency:{Perc50:65.177ms Perc90:2.010244s Perc99:2.051307s Perc100:0s} Count:6207}
```

That's a super high bump for such a small cluster. And the [diff](https://github.com/kubernetes/kubernetes/compare/b00d600b4...51d75a7b1) is pointing to this change around GC client - https://github.com/kubernetes/kubernetes/pull/63444

I'm not sure if this is a right hypothesis, but using dynamic client seems to hurt the performance?

@liggitt @deads2k

**Comment by shyamjvs** [comment]
FYI - Filed another issue https://github.com/kubernetes/kubernetes/issues/63610 for the GC regression which is a different one.

**Comment by wojtek-t** [comment]
@liggitt - it seems that your #63606 helps (which looking into the code is expected, given that you're reducing number of generated QPSes).
I took a look and I'm happy to approve it once you remove the "do-not-submit" commit from it :)

**Comment by wojtek-t** [comment]
This weeks regression seem to be fixed - but we're still not in a good shape.
The run that is happening now seems to suffer mostly from slow etcd. 

In particular, I'm seeing this:
```
tcd_debugging_snap_save_marshalling_duration_seconds_bucket{le="0.001"} 1126
etcd_debugging_snap_save_marshalling_duration_seconds_bucket{le="0.002"} 1127
etcd_debugging_snap_save_marshalling_duration_seconds_bucket{le="0.004"} 1129
etcd_debugging_snap_save_marshalling_duration_seconds_bucket{le="0.008"} 1130
etcd_debugging_snap_save_marshalling_duration_seconds_bucket{le="0.016"} 1134
etcd_debugging_snap_save_marshalling_duration_seconds_bucket{le="0.032"} 1138
etcd_debugging_snap_save_marshalling_duration_seconds_bucket{le="0.064"} 1140
etcd_debugging_snap_save_marshalling_duration_seconds_bucket{le="0.128"} 1140
etcd_debugging_snap_save_marshalling_duration_seconds_bucket{le="0.256"} 1140
etcd_debugging_snap_save_marshalling_duration_seconds_bucket{le="0.512"} 1140
etcd_debugging_snap_save_marshalling_duration_seconds_bucket{le="1.024"} 1140
etcd_debugging_snap_save_marshalling_duration_seconds_bucket{le="2.048"} 1140
etcd_debugging_snap_save_marshalling_duration_seconds_bucket{le="4.096"} 1140
etcd_debugging_snap_save_marshalling_duration_seconds_bucket{le="8.192"} 1140
etcd_debugging_snap_save_marshalling_duration_seconds_bucket{le="+Inf"} 1140
etcd_debugging_snap_save_marshalling_duration_seconds_sum 0.30749476599999986
etcd_debugging_snap_save_marshalling_duration_seconds_count 1140
# HELP etcd_debugging_snap_save_total_duration_seconds The total latency distributions of save called by snapshot.
# TYPE etcd_debugging_snap_save_total_duration_seconds histogram
etcd_debugging_snap_save_total_duration_seconds_bucket{le="0.001"} 0
etcd_debugging_snap_save_total_duration_seconds_bucket{le="0.002"} 119
etcd_debugging_snap_save_total_duration_seconds_bucket{le="0.004"} 1092
etcd_debugging_snap_save_total_duration_seconds_bucket{le="0.008"} 1128
etcd_debugging_snap_save_total_duration_seconds_bucket{le="0.016"} 1130
etcd_debugging_snap_save_total_duration_seconds_bucket{le="0.032"} 1136
etcd_debugging_snap_save_total_duration_seconds_bucket{le="0.064"} 1139
etcd_debugging_snap_save_total_duration_seconds_bucket{le="0.128"} 1140
etcd_debugging_snap_save_total_duration_seconds_bucket{le="0.256"} 1140
etcd_debugging_snap_save_total_duration_seconds_bucket{le="0.512"} 1140
etcd_debugging_snap_save_total_duration_seconds_bucket{le="1.024"} 1140
etcd_debugging_snap_save_total_duration_seconds_bucket{le="2.048"} 1140
etcd_debugging_snap_save_total_duration_seconds_bucket{le="4.096"} 1140
etcd_debugging_snap_save_total_duration_seconds_bucket{le="8.192"} 1140
etcd_debugging_snap_save_total_duration_seconds_bucket{le="+Inf"} 1140
etcd_debugging_snap_save_total_duration_seconds_sum 3.218769367000001
etcd_debugging_snap_save_total_duration_seconds_count 1140
```
Which according to https://github.com/coreos/etcd/blob/master/Documentation/faq.md#what-does-the-etcd-warning-apply-entries-took-too-long-mean is not very good sign.

I think we should finally exclude the hypothesis that our problems are due to etcd disk.
In particular two things that we should try doing is:

1. increase etcd disk and at the same time move events-data to somewhere else (separate disk?) to ensure they are not contributing to this problem
2. try also local-ssd and tmpfs to check if that would help with our problems (for the purpose of experiment)

**Comment by wojtek-t** [comment]
Sorry - I pasted bad metrics - now it should be better.

**Comment by AishSundar** [comment]
Here is the error in [the latest test run](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/151)

/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scalability/density.go:365
There should be no high-latency requests
Expected
    <int>: 2
not to be >
    <int>: 0
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scalability/density.go:407

**Comment by liggitt** [comment]
delete pods no longer shows up in top latency metrics. latest job failed on two high latency requests (patch node, post rc):

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/152/

```
May 11 11:48:22.290: INFO: Top latency metric: {Resource:pods Subresource: Verb:LIST Scope:cluster Latency:{Perc50:2.398045s Perc90:5.702903s Perc99:6.135539s Perc100:0s} Count:8051}
May 11 11:48:22.290: INFO: Top latency metric: {Resource:nodes Subresource: Verb:LIST Scope:cluster Latency:{Perc50:638.259ms Perc90:2.002614s Perc99:4.492171s Perc100:0s} Count:2236}
May 11 11:48:22.290: INFO: Top latency metric: {Resource:pods Subresource: Verb:LIST Scope:namespace Latency:{Perc50:52.874ms Perc90:178.721ms Perc99:2.142308s Perc100:0s} Count:10573}
May 11 11:48:22.290: INFO: WARNING Top latency metric: {Resource:nodes Subresource:status Verb:PATCH Scope:cluster Latency:{Perc50:11.611ms Perc90:659.127ms Perc99:1.508054s Perc100:0s} Count:7119953}
May 11 11:48:22.290: INFO: WARNING Top latency metric: {Resource:replicationcontrollers Subresource: Verb:POST Scope:namespace Latency:{Perc50:3.743ms Perc90:666.977ms Perc99:1.354669s Perc100:0s} Count:5050}
```

**Comment by wojtek-t** [comment]
Yup - as I wrote above in https://github.com/kubernetes/kubernetes/issues/63030#issuecomment-388356739

> This weeks regression seem to be fixed - but we're still not in a good shape.

We will be looking into that deeper.

**Comment by AishSundar** [comment]
@wojtek-t @shyamjvs is there an ETA for fixing the latest failure? Is it even Beta blocking? we are due to cut v1.11 on Tuesday 5/15. Please let us know if this failure is blocking or not.

**Comment by shyamjvs** [comment]
@AishSundar We've fixed a couple of issues last week. There's still https://github.com/kubernetes/kubernetes/issues/62064 pending, which is causing the current flakes.
I'd say 2 weeks as a realistic ETA for fixing it and IMO we don't need to block the beta release on it (based on its seriousness). If someone thinks otherwise, please comment.

**Comment by wojtek-t** [comment]
> we don't need to block the beta release on it 

+1 - this should be blocker for GA, but I'm fine with not blocking Beta on it.

**Comment by wojtek-t** [comment]
So I finally got back to it and looked into it (note that I'm explicitly ignoring the second regression @shyamjvs is debugging in https://github.com/kubernetes/kubernetes/issues/62808).

This one I'm explicitly talking about the high API call latencies.
So looking into perf-dash it's pretty clear that some runs are waaay better than the others:
![screenshot from 2018-05-29 09-55-30](https://user-images.githubusercontent.com/10743879/40645419-9363f9f0-6326-11e8-85ee-f9d402dad611.png)

So I looked into logs from those and the correlation is obvious:
- density test running first => run is bad
- load test running first => run is good

The next step is looking to apiserver logs and understanding where are those "LIST pods" calls coming from. And those that different between those two groups of runs are:
- api calls coming from rescheduler - O(1000) of those
- api calls coming from node-controller - O(3000+) of those

So I first focused on the second group (those coming from node-controller), which I think are the main factor contributing with high latencies for RC-related API calls (only those collide in time with latency phase of Density test).
And all those calls are coming from here:
https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/nodelifecycle/scheduler/taint_manager.go#L111

That function is called from `handleNodeUpdate` function in the same file which:
- for every node update that is changing set of taints on a node, it lists all pods from that node and evicts/stops eviction of all pods affected by the changes in taints

What is really problematic here is that:
- this processing is coming from cluster startup really (and from initial node tainting/untainting)
- but since processing a single node takes between 0.5s to 6s (due to listing all pods), this whole phase of processing all nodes takes a couple hours (and is significantly affecting the test itself)

It's pretty clear that processing update of node taints two hours after the taints changed is useless...
The question is how to fix that problem.

I think there are two main options to fix that:
- list pods from cache (though it's not perfect, because it may lead to race and not evicting some pods already on that node)
- increasing parallelism of handling node taints updates (which I think is what we should do)

Let me send out a PR for this.

**Comment by wojtek-t** [comment]
@kubernetes/sig-node-bugs @gmarek @k82cn ^^

**Comment by wojtek-t** [comment]
BTW - wrt rescheduler, the problem seems to be exactly the same:
https://github.com/kubernetes/contrib/blob/master/rescheduler/rescheduler.go#L408
But I think we will switch off rescheduler in 1.11 (will try to confirm that today), so probably shouldn't spend too much time on it.

**Comment by k82cn** [comment]
> increasing parallelism of handling node taints updates (which I think is what we should do)

Agree, that's better for 1.11; the impact to api server seems acceptable, just add 7 api call concurrently (in the PR).

**Comment by wojtek-t** [comment]
The mitigation for two different issues are now merged - I have a hope that we may finally be out of regressions.

**Comment by AishSundar** [comment]
Will monitor the runs and keep the issue updated

**Comment by AishSundar** [comment]
@shyamjvs @wojtek-t I still see [the gce-scale-performance job](https://k8s-testgrid.appspot.com/sig-release-master-blocking#gce-scale-performance) fail alternatively on either the Density or the Load test for 30 pods. Does [#62808](https://github.com/kubernetes/kubernetes/issues/62808) address the remaining issue?

**Comment by wojtek-t** [comment]
@shyamjvs - I looked into run 161, and that will be tricky.
We don't have logs from that particular moment in time, because of log-rotation.
Last log from the previous file:
```
I0601 17:00:16.265434       1 wrap.go:42] GET /api/v1/namespaces/e2e-tests-load-30-nodepods-23-blq4g/pods?labelSelector=name%3Dload-small-10272&limit=500&resourceVersion=0: (57.180707ms) 200 [[e2e.test/v1.12.0 (linux/amd64) kubernetes/0ea07c4] 35.193.89.205:37456]
```
First log from the next file:
```
I0601 17:01:03.256345       1 wrap.go:42] POST /api/v1/namespaces/e2e-tests-load-30-nodepods-21-lmkr4/events: (3.224842ms) 201 [[kube-controller-manager/v1.12.0 (linux/amd64) kubernetes/0ea07c4/system:serviceaccount:kube-system:replication-controller] [::1]:40688
```

However, I looked into the code and we obviously have one problem with the code itself - note that scaler retries only conficts;https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/scale.go#L92

So there are two AIs from this failure:
- [ ] fix the "ScaleWithRetries" so that it really retries errors:
https://github.com/kubernetes/kubernetes/blob/master/test/utils/update_resources.go#L39
- [ ] figure out if we can somehow improve log rotation so that we won't lose logs in the meantime

[BTW - I think that it happened during log-rotation is not a coincidence here...]

**Comment by wojtek-t** [comment]
@krzysied - can you please take a look into the two AIs from above ^^

**Comment by shyamjvs** [comment]
I agree with Wojtek that it's an unrelated flake, which needs to be addressed by making our test framework more robust.
And for the part about log-rotation setup - it's also another thing we should try to improve.

 @krzysied - If you might be interested taking a look into it.

**Comment by shyamjvs** [comment]
I'm going to wait for one more run to confirm we're not suffering from any other scalability issues. And it things look good, I'll bump down the priority and kick it out of release blockers.

**Comment by AishSundar** [comment]
Thanks @shyamjvs and @wojtek-t for followup.

**Comment by shyamjvs** [comment]
@krzysied Btw, to add some context - we were seeing losses in the past during log-rotation and made some changes in our large-cluster test setup to help with it.
See https://github.com/kubernetes/kubernetes/issues/49941 for ref. You might find some clues there.

**Comment by shyamjvs** [comment]
Maybe experiment by setting `LOGROTATE_MAX_SIZE` quite high that rotation never takes place? (I don't know what the consequences of this will be though)

**Comment by wojtek-t** [comment]
>Maybe experiment by setting LOGROTATE_MAX_SIZE quite high that rotation never takes place? (I don't know what the consequences of this will be though)

No - we've been there already. You're ending up with files of a size that you can't easily open anywhere :)

BTW - the first point (fixing retries) is significantly more important than fixing log rotation.

**Comment by shyamjvs** [comment]
Sgtm - let's neglect the log-rotation for now (I think it's a hard problem in general from stories @crassirostris used to tell me:)

/assign @krzysied

**Comment by wojtek-t** [comment]
Given that the last run also succeeded (well, test-infra part failed to update build log, but test passed), I'm removing it from release blockers list.

**Comment by wojtek-t** [comment]
Actually, it's not marked as release blocker...

**Comment by shyamjvs** [comment]
I've removed all the milestone related labels (as it's not really relevant for the remainder of this issue imo).

@kubernetes/test-infra-maintainers - Could someone explain what went wrong with this run - https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/162 ? (I see not all artifacts are present)

**Comment by wojtek-t** [comment]
I filed https://github.com/kubernetes/kubernetes/issues/64760 for the logrotation thing.
Let's fix the retries and close this bug when that is fixed.

**Comment by krzysied** [comment]
@wojtek-t I've created PR with retries fix.

**Comment by krzyzacy** [comment]
@shyamjvs last line of the log:
```
I0605 01:32:07.654] Call:  gsutil -m -q -o GSUtil:use_magicfile=True cp -r -c -z log,txt,xml /workspace/artifacts gs://kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/162
```

I think that gcloud cp call did not finish. Again I saw logexporter failed on >1k nodes, is this normal? We probably should retry?

**Comment by shyamjvs** [comment]
Seems like we're seeing this problem with artifacts upload failing a bit too frequently - https://k8s-testgrid.appspot.com/sig-scalability-gce#gce-scale-performance
I'll send out a change increasing the logexporter step timeout to see if that helps.

**Comment by krzyzacy** [comment]
@shyamjvs that gcloud call I pasted above never returns

**Comment by shyamjvs** [comment]
There's no active work left here. The scaling-related flakes should be fixed with https://github.com/kubernetes/kubernetes/pull/64768 merged.
And for logexporter issue, I've filed #65018 (we're looking into it, but it's not very critical).

/close
