### ISSUE TITLE
Unable connect to any pod from master

### ISSUE THREAD

**Issue by roman-shuhov** [kubernetes/kubernetes#6311]
Hi,

I'm trying to setup Kubernetes in Openstack + CoreOS. 

I have master 10.240.63.84 and 2 minions .63 and .83. I also created 3 redis pods:

    redis-gopher-gziey        10.244.32.2     10.240.63.66/10.240.63.66
    redis-managed-oh43e   10.244.32.3     10.240.63.66/10.240.63.66
    redis-primary-fplln          10.244.54.2     10.240.63.83/10.240.63.83  

master's routing table looks like:

    10.240.63.0     *               255.255.255.0   U     0      0        0 eth0
    10.240.63.1     *               255.255.255.255 UH    1024   0        0 eth0
    10.244.0.0      *               255.255.0.0     U     0      0        0 flannel.1
    10.244.50.0     *               255.255.255.0   U     0      0        0 docker0

and output of ifconfig -a is :

    docker0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
            inet 10.244.50.1  netmask 255.255.255.0  broadcast 0.0.0.0
            inet6 fe80::542f:6fff:fe4a:adf3  prefixlen 64  scopeid 0x20<link>
            ether 56:84:7a:fe:97:99  txqueuelen 0  (Ethernet)
            RX packets 0  bytes 0 (0.0 B)
            RX errors 0  dropped 0  overruns 0  frame 0
            TX packets 1  bytes 90 (90.0 B)
            TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

    eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500  
            inet 10.240.63.84  netmask 255.255.255.0  broadcast 10.240.63.255
            inet6 fe80::f816:3eff:fe89:e9a0  prefixlen 64  scopeid 0x20<link>
            ether fa:16:3e:89:e9:a0  txqueuelen 1000  (Ethernet)
            RX packets 430706  bytes 559764129 (533.8 MiB)
            RX errors 0  dropped 0  overruns 0  frame 0
            TX packets 238519  bytes 116083693 (110.7 MiB)
            TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

    flannel.1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1450
            inet 10.244.50.0  netmask 255.255.0.0  broadcast 0.0.0.0
            inet6 fe80::601f:62ff:feed:1556  prefixlen 64  scopeid 0x20<link>
            ether 62:1f:62:ed:15:56  txqueuelen 0  (Ethernet)
            RX packets 20  bytes 1504 (1.4 KiB)
            RX errors 0  dropped 0  overruns 0  frame 0
            TX packets 79  bytes 7686 (7.5 KiB)
            TX errors 0  dropped 19 overruns 0  carrier 0  collisions 0

Flanneld config used for initialization is:

Master:
```
        - name: flanneld.service
          command: start
          drop-ins:
            - name: 50-network-config.conf
              content: |
                [Service]
                ExecStartPre=/usr/bin/etcdctl set /coreos.com/network/config '{"Network":"10.244.0.0/16", "Backend": {"Type": "vxlan"}}'
                ExecStart=
                ExecStart=/usr/libexec/sdnotify-proxy /run/flannel/sd.sock \
                    /usr/bin/docker run --net=host --privileged=true --rm \
                        --volume=/run/flannel:/run/flannel \
                        --env=NOTIFY_SOCKET=/run/flannel/sd.sock \
                        --env-file=/run/flannel/options.env \
                        --volume=${ETCD_SSL_DIR}:/etc/ssl/etcd:ro \
                        quay.io/coreos/flannel:${FLANNEL_VER} /opt/bin/flanneld --ip-masq=true --iface=eth0
```

Minion:
```
        - name: flanneld.service
          command: start
          drop-ins:
            - name: 50-network-config.conf
              content: |
                [Service]
                ExecStartPre=/usr/bin/etcdctl set /coreos.com/network/config '{"Network":"10.244.0.0/16", "Backend": {"Type": "vxlan"}}'
                ExecStart=
                ExecStart=/usr/libexec/sdnotify-proxy /run/flannel/sd.sock \
                    /usr/bin/docker run --net=host --privileged=true --rm \
                        --volume=/run/flannel:/run/flannel \
                        --env=NOTIFY_SOCKET=/run/flannel/sd.sock \
                        --env-file=/run/flannel/options.env \
                        --volume=${ETCD_SSL_DIR}:/etc/ssl/etcd:ro \
                        quay.io/coreos/flannel:${FLANNEL_VER} /opt/bin/flanneld -etcd-endpoints     http://10.240.63.84:4001 --ip-masq=true --iface=eth0
```
So the issue is that i can't ping any of the pods from master, as well as connect to any port, error is:

    ncat -v -t 10.244.32.2 6379
    Ncat: Version 6.40 ( http://nmap.org/ncat )
    Ncat: No route to host.

**Comment by bprashanth** [comment]
@ArtfulCoder

**Comment by roman-shuhov** [comment]
It happens again when i tried to re-create cloud from scratch.

I think this information will be helpful

minion - https://gist.github.com/roman-shuhov/819d26f402699d63edb0
master - https://gist.github.com/roman-shuhov/02432247fce7a9603fe7

additional information 
https://gist.github.com/roman-shuhov/335ad0f54ce49bc84582

**Comment by thockin-cc** [comment]
Your service iptables rules look right for the two built-services.  If you
run two docker containers on two nodes, can they ping each other?  That is
step 1.

**Comment by roman-shuhov** [comment]
They can't ping each other, here is some output https://gist.github.com/roman-shuhov/4acc09609a349b7becf0

**Comment by thockin-cc** [comment]
So this is the root of the problem.  Please check your network install - I
think you said it was flannel?  I am out until Tuesday, but the other smart
folks here can help in the mean time :)

**Comment by roman-shuhov** [comment]
thanks, do you have any thoughts what can be wrong with flannel?

**Comment by ArtfulCoder** [comment]
On the master we can confirm that docker bridge sits correctly behind the flannel bridge.
The docker net address is within the flannel.1 net.
docker:    inet 10.244.50.1  netmask 255.255.255.0
flannel.1: inet 10.244.50.0  netmask 255.255.0.0 

You can do the same check on the minions. If this check fails on the minions, obviously, that is the problem. 
Though, I must that that I would be surprised if this were a problem, since it is a core setup that flannel strives to get right. 
Also, all the docker subnets across the various kubernetes nodes must be unique.

You already did the connectivity test without using kubernetes service-ips, so we know its not a kubernetes service-ip problem.

A side-note: currently, your flannel uses etcd running on kubernetes master. As of friday afternoon, I have checked in code to make etcd of kubernetes, private to kubernetes-master, where it listens only on 127.0.0.1:4001.  So, you will have to run on your own etcd for flannel to use.

**Comment by goltermann** [comment]
We’re going through old support issues and asking everyone to direct your questions to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes). 

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases. 

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.
