### ISSUE TITLE
API connection failure does not log out to systemctl or journalctl -u kubelet

### ISSUE THREAD

**Issue by emenare** [kubernetes/kubernetes#63320]
/kind bug

**What happened**:
Error due to failure to connect to openstack cloud provider is not shown in systemctl status or journalctl -u kubelet logs. It can only be seen in the full system journalctl log.

"kubelet-wrapper[14427]: Error: failed to run Kubelet: could not init cloud provider "openstack": Post http://x.x.x.x:5000/v3/auth/tokens: dial tcp x.x.x.x:5000: getsockopt: connection timed out"

**What you expected to happen**:

I expect to be able to see this error show up in systemctl status kubelet or journalctl -u kubelet.

**How to reproduce it (as minimally and precisely as possible)**:
Using an invalid or unroutable ip for the AUTH_URL, try to start up kubelet.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.9.6
- Cloud provider or hardware configuration: OpenStack Newton
- OS (e.g. from /etc/os-release): NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1688.5.3
- Kernel (e.g. `uname -a`): 4.14.32-coreos #1 SMP Tue Apr 3 05:21:26 UTC 2018 x86_64 Intel Core Processor (Haswell, no TSX) GenuineIntel GNU/Linux
- Install tools: Tectonic
- Others:

**Comment by dims** [comment]
@emenare thanks for the report, kubelet currently fails using `glog.Fatal`:
https://github.com/kubernetes/kubernetes/blob/master/cmd/kubelet/app/server.go#L238

BUT since you are using kubelet-wrapper which is a wrapper around kubelet, there is a layer of indirection for the logs and you may not be seeing it where you expected it:

https://github.com/coreos/coreos-overlay/blob/master/app-admin/kubelet-wrapper/files/kubelet-wrapper

Can you please chase it with the CoreOS folks? (open an issue in that repo?)

cc @databus23 

Thanks,
Dims

/close
