### ISSUE TITLE
fluentd logging fails to start: fails to start: Path /var/lib/docker/containers is mounted on /var/lib/docker/containers

### ISSUE THREAD

**Issue by rudymccomb** [kubernetes/kubernetes#63447]
What I did 
kubectl apply -f kubernetes/cluster/addons/fluentd-elasticsearch/fluentd-es-ds.yaml

What I expected:
For the daemonset to deploy correctly

What happend
```
 Normal   SuccessfulMountVolume  10m               kubelet, ip-172-20-59-186.ec2.internal  MountVolume.SetUp succeeded for volume "varlog"
  Normal   SuccessfulMountVolume  10m               kubelet, ip-172-20-59-186.ec2.internal  MountVolume.SetUp succeeded for volume "varlibdockercontainers"
  Normal   SuccessfulMountVolume  10m               kubelet, ip-172-20-59-186.ec2.internal  MountVolume.SetUp succeeded for volume "config-volume"
  Normal   SuccessfulMountVolume  10m               kubelet, ip-172-20-59-186.ec2.internal  MountVolume.SetUp succeeded for volume "efk-ca-cert"
  Normal   SuccessfulMountVolume  10m               kubelet, ip-172-20-59-186.ec2.internal  MountVolume.SetUp succeeded for volume "fluentd-es-token-mxsrp"
  Normal   Created                9m (x4 over 9m)   kubelet, ip-172-20-59-186.ec2.internal  Created container
  Normal   Started                9m (x4 over 9m)   kubelet, ip-172-20-59-186.ec2.internal  Started container
  Normal   Pulled                 8m (x5 over 9m)   kubelet, ip-172-20-59-186.ec2.internal  Container image "k8s.gcr.io/fluentd-elasticsearch:v2.0.4" already present on machine
  Warning  BackOff                4m (x23 over 9m)  kubelet, ip-172-20-59-186.ec2.internal  Back-off restarting failed container
```

**How to reproduce it (as minimally and precisely as possible)**:
Deploy fluentd logging with fluentd-es-ds.yaml and fluentd-es-configmap.yaml

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.9.3
- Cloud provider or hardware configuration: AWS
- OS (e.g. from /etc/os-release): ubuntu
Related Bug: https://bugzilla.redhat.com/show_bug.cgi?id=1569106

**Comment by gnufied** [comment]
I am not sure if you have same problem as linked issue in openshift Bugzilla because that is specific to Openshift-3.10 and hence Kubernetes-1.10.

Underlying root cause of that problem is - we enabled "slave" as default mount propagation option in 1.10 but we are reverting the behaviour. Your cluster is on 1.9 and hence it should not be affected by that bug, unless you explicitly enabled MountPropagation feature.

Please post logs from controller-manager and kubelet. There may be something there, as such it looks like a different issue.

**Comment by coffeepac** [comment]
@nikhita are you seeing this issue  with the same k8s and OS versions as well?  if so, can you please post the logs from controller-manager and kubelet?

**Comment by nikhita** [comment]
> @nikhita are you seeing this issue with the same k8s and OS versions as well? if so, can you please post the logs from controller-manager and kubelet?

Oh sorry, I was just marking this issue as non-stale so that the bot does not close down issues accidentally in the project.

> There may be something there, as such it looks like a different issue.

From this, I gathered that there is indeed _some_ underlying issue. 

If not, maybe we could wait for @rudymccomb to respond and close this. If someone comes across this again, we can reopen anytime (just my 2 cents).

@rudymccomb are you still able to reproduce this? if yes, could you post the logs? would be super helpful, thanks!!

**Comment by coffeepac** [comment]
Gotcha.  I normally let the issues decay and if no one comes back to comment with more info just let it go.  Oftentimes the issue is resolved but the original poster doesn't come back to close the issue.  Which is fine, that's what the bot is for.  

This is against 1.9 which is going out of support this quarter so I'm pretty inclined to let it turn to dust.
