### ISSUE TITLE
Failing tests: [sig-autoscaling] Multiple Horizontal pod tests are failing in sig-release-master-upgrade 

### ISSUE THREAD

**Issue by AishSundar** [kubernetes/kubernetes#63501]
## Failing Tests
* [sig-autoscaling] [HPA] Horizontal pod autoscaling (scale resource: CPU) [sig-autoscaling] [Serial] [Slow] Deployment Should scale from 1 pod to 3 pods and from 3 to 5 
* [sig-autoscaling] [HPA] Horizontal pod autoscaling (scale resource: CPU) [sig-autoscaling] [Serial] [Slow] Deployment Should scale from 5 pods to 3 pods and from 3 to 1 
* [sig-autoscaling] [HPA] Horizontal pod autoscaling (scale resource: CPU) [sig-autoscaling] [Serial] [Slow] ReplicaSet Should scale from 1 pod to 3 pods and from 3 to 5 
* [sig-autoscaling] [HPA] Horizontal pod autoscaling (scale resource: CPU) [sig-autoscaling] [Serial] [Slow] ReplicaSet Should scale from 5 pods to 3 pods and from 3 to 1 
* [sig-autoscaling] [HPA] Horizontal pod autoscaling (scale resource: CPU) [sig-autoscaling] [Serial] [Slow] ReplicationController Should scale from 1 pod to 3 pods and from 3 to 5 and verify decision stability 
* [sig-autoscaling] [HPA] Horizontal pod autoscaling (scale resource: CPU) [sig-autoscaling] [Serial] [Slow] ReplicationController Should scale from 5 pods to 3 pods and from 3 to 1 and verify decision stability 
* [sig-scheduling] SchedulerPredicates [Serial] validates MaxPods limit number of pods that are allowed to run [Slow]

## Failing Jobs
* [gce-1.10-master-upgrade-cluster](https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gce-1.10-master-upgrade-cluster)
* [gce-1.10-master-upgrade-cluster-new](https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gce-1.10-master-upgrade-cluster-new)
* [gke-gci-1.10-gci-master-upgrade-master](https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gke-gci-1.10-gci-master-upgrade-master)

## Gubernator Logs from recent runs
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-new-master-upgrade-cluster/2118

## Triage results for Failing tests
https://storage.googleapis.com/k8s-gubernator/triage/index.html?date=2018-04-16&test=Horizontal%5C%20pod%5C%20autoscaling%5C%20%5C(scale%5C%20resource%3A%5C%20CPU%5C)%5C%20%5C%5Bsig%5C-autoscaling%5C%5D%5C%20%5C%5BSerial%5C%5D%5C%20%5C%5BSlow%5C%5D

This test is currently failing in sig-release master-upgrade suite. This could potentially block Beta cut which is on 5/15. Please investigate and fix at the earliest. @DirectXMan12 can you please triage this issue and assign to the rightful owner.

/kind bug
/priority failing-test
/priority important-soon
/sig autoscaling
/milestone v1.11
@kubernetes/sig-autoscaling-bugs

cc @jberkus @tpepper

/assign @DirectXMan12

**Comment by DirectXMan12** [comment]
Looking at the controller-manager logs from https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-new-master-upgrade-cluster/2118#sig-autoscaling-hpa-horizontal-pod-autoscaling-scale-resource-cpu-sig-autoscaling-serial-slow-replicaset-should-scale-from-1-pod-to-3-pods-and-from-3-to-5, for instance, it looks like the HPA is doing the right thing, in that it's scaling up to 3 pods (event at 08:09:20).  It looks like the RS controller is actually launching 3 pods as well (status update around 08:09:21), but those replicas are never becoming ready according to the RS controller (watch the lines that start with "Updating status for"), except for the initial replica.  This is causing issues, because the "wait for replicas" function we use (`"test/e2e/common".ResourceConsumer#GetReplicas`) looks at ready replicas in all cases.

Some of the other tests ("Should scale from 5 to 3...") seem like they're not actually "starting" all the pods required for a precondition to the test.  Looking at the code for that (`"test/utils".ComputeRCStartupStats`), we can see the the criterion for "running" is running and ready, so here again we're coming up against a pod not being ready.

Similarly to the first case above, for https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-new-master-upgrade-cluster/2118#sig-autoscaling-hpa-horizontal-pod-autoscaling-scale-resource-cpu-sig-autoscaling-serial-slow-replicationcontroller-should-scale-from-1-pod-to-3-pods-and-from-3-to-5-and-verify-decision-stability, we get to 3 replicas, and then on the move to 5 replicas, one of the replicas never goes ready, according to the RS controller.

So, there (to me) are thus two questions here: why do we care about pods becoming ready in test cases where it doesn't matter, and why are the pods not becoming ready.  Curiously, we don't actually set a readiness probe on any of our pods, so it shouldn't be the readiness probe failing.

Looking at the scheduler logs from https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-new-master-upgrade-cluster/2118#sig-autoscaling-hpa-horizontal-pod-autoscaling-scale-resource-cpu-sig-autoscaling-serial-slow-replicationcontroller-should-scale-from-1-pod-to-3-pods-and-from-3-to-5-and-verify-decision-stability, we can see that it's actually the pod failing to schedule.  (2 of the nodes have insufficient CPU, 2 are unschedulable).

Looking at the logs from https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-new-master-upgrade-cluster/2118#sig-autoscaling-hpa-horizontal-pod-autoscaling-scale-resource-cpu-sig-autoscaling-serial-slow-replicaset-should-scale-from-1-pod-to-3-pods-and-from-3-to-5, we see something similar: the pods are unschedulable, with 1 node with insufficient CPU, and 3 which are unschedulable.

@kubernetes/sig-testing-misc @kubernetes/test-infra-maintainers did we recently change the sizing on the machines we run tests on?  I find it strange that we're only seeing it on the HPA tests.  Maybe we use more CPU request than other sample pods?  The failing tests request 500 millicores per pod, I believe.

**Comment by krzyzacy** [comment]
yep, you have control to your e2e cluster shape

**Comment by DirectXMan12** [comment]
Alright.  It's weird that it popped up suddenly then.  I wonder if we started running extra infra pods during the tests or something?  At any rate, the easy solution should be to drop down the requests on the pods.  What's the size of the nodes that we have to work with?  Based on the error messages, it looks like we've got between 1 and 2 scheduable nodes (that's kind of weird that it's not constantly two) to work with.  @kubernetes/test-infra-maintainers How big are they (and/or how do I check)?

@mwielgus any reason we shouldn't shrink the resource consumer request below 500 millicores?  Is it that big to avoid flakiness?

**Comment by BenTheElder** [comment]
>  @kubernetes/test-infra-maintainers How big are they (and/or how do I check)?

nodes.yaml in the artifacts covers this for some jobs
https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-new-master-upgrade-cluster/2121/artifacts/nodes.yaml

The [logs](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-new-master-upgrade-cluster/2121?log#log) also include the cluster-up output so you can see:
```
W0508 23:02:26.503] NAME                  ZONE           MACHINE_TYPE   PREEMPTIBLE  INTERNAL_IP  EXTERNAL_IP    STATUS
W0508 23:02:26.503] bootstrap-e2e-master  us-central1-f  n1-standard-1               10.128.0.2   35.232.25.230  RUNNING
I0508 23:02:26.604] Creating nodes.
```

```
W0508 23:02:32.682] Created [https://www.googleapis.com/compute/v1/projects/k8s-gce-upg-1-5-1-6-up-mas/global/instanceTemplates/bootstrap-e2e-minion-template].
W0508 23:02:32.847] NAME                           MACHINE_TYPE   PREEMPTIBLE  CREATION_TIMESTAMP
W0508 23:02:32.847] bootstrap-e2e-minion-template  n1-standard-2               2018-05-08T16:02:29.166-07:00
W0508 23:02:45.205] Created [https://www.googleapis.com/compute/v1/projects/k8s-gce-upg-1-5-1-6-up-mas/zones/us-central1-f/instanceGroupManagers/bootstrap-e2e-minion-group].
I0508 23:02:45.540] NAME                        LOCATION       SCOPE  BASE_INSTANCE_NAME          SIZE  TARGET_SIZE  INSTANCE_TEMPLATE              AUTOSCALED
I0508 23:02:45.540] bootstrap-e2e-minion-group  us-central1-f  zone   bootstrap-e2e-minion-group  0     3            bootstrap-e2e-minion-template  no
```

And for completeness you can also check for lines like:
https://github.com/kubernetes/test-infra/blob/02bc556d770730a2512929553734ca2736025e55/jobs/config.json#L11350`
```
      "--gcp-node-size=n1-standard-4",
```
in the job definition, otherwise they're using the standard cluster-up scripts for the release they're running against IIRC.

**Comment by MaciekPytel** [comment]
@aleksandra-malinowska Can this be related to https://github.com/kubernetes/kubernetes/pull/63616?

**Comment by AishSundar** [comment]
These seems to be cleaning up in the latest run. I am closing this now and will re-open as needed
