### ISSUE TITLE
MaxPodsPerNode - be able to set hard and soft limits for deployments / replicasets

### ISSUE THREAD

**Issue by salluvada** [kubernetes/kubernetes#63560]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
 /kind feature

**What happened**:
I have a two node cluster (node01, node02 in addition to a master node), and scheduled a deployment with 10 replicas. The pods were scheduled 5 per node which is good. Then I went and drained node01. The pods were evicted from node01 and all pods were scheduled on node02 which is also good. When I uncordoned node01, I still see that all the pods are still on node02.

**What you expected to happen**:
I was expecting to see that five pods from node 02 are rescheduled back to node01. In essence I want a way to tell kubernetes that for the deployment with 10 replicas, I want a max of 5 pods per node and be able to set a soft/hard limit for the same. If I set a hard limit, it should fail on the drain stating that it cannot satisfy the 5 MaxPodsPerNode rule and if I set a soft limit, it should allow to drain and cordon the node01 but once the node01 is uncordoned, I would expect the pods to be rescheduled as per the MaxPodsPerNode rule or atleast attempted to satisfy the 5 MaxPodsPerNode rule.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a deployment simpleweb with 10 replicas of nginx
kubectl run simpleweb --image=nginx --replicas=10

2. Drain the node01, ignoring daemonsets
kubectl drain node01 --ignore-daemonsets

3. Uncordon node01
kubectl uncordon node01
 
**Anything else we need to know?**:
None.

**Environment**:
- Kubernetes version (use `kubectl version`):
Client and Server @ 1.10.2

- Cloud provider or hardware configuration:
3 Linux VMs (one master, 2 worker nodes) using virtual box running on a Mac. 2CPUs and 4GB RAM

- OS (e.g. from /etc/os-release):
NAME="Ubuntu"
VERSION="18.04 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

- Kernel (e.g. `uname -a`):
Linux master 4.15.0-20-generic #21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
kubeadm

- Others:

**Comment by k82cn** [comment]
Similar requirement with https://github.com/kubernetes/kubernetes/issues/40358 :)

/cc @wojtek-t

**Comment by krmayankk** [comment]
i think some form of rescheduling can also be acehived by using https://github.com/kubernetes-incubator/descheduler

**Comment by davinchia** [comment]
Commenting on this to indicate more use cases.

We are currently running high throughput/low latency apiservers on kube in the order of hundreds of thousands of request per second. We are running into a case where instead of spreading the pods out as much as possible, Kube sometimes bunches them together(for resource constraint reasons, since there are other pods also running), so we end up with a couple of nodes having more pods than the rest. The underlying node is not able to handle the number of incoming connections and starts erroring out (this is even with strict sysctl tuning). As that node's pods become unhealthy and die, other pods take on more traffic and start becoming overloaded, till the cluster becomes unstable. 

We do see this happening even when the pods are well spread out, especially with high network load. It would be great to be able to specify the max number of replicas a node should contain, especially since, afaik, there is still no fencing around iops or networking (if there is let me know). 

We are currently experimenting with limiting 1 pod to a node. The trouble with this is scaling up becomes expensive i.e. it requires a new node to be created. It also increases the cost of running the cluster. Happy to accept ideas, or temporary solutions, if people have any.

Kube has been great for us thus far, and it'll be a pity to not utilise this due to lack of networking fencing/inability to specify max pods per node.

**Comment by davinchia** [comment]
I want to add I'd be happy to contribute on this since its something we want. As someone new to the Kubernetes project, it'll be great if someone else is willing to point me in the right direction with design docs/approaches, if my help is needed on this.

**Comment by sidewinder12s** [comment]
We're also running into a similar problem with the scheduler seemingly scheduling most pods on a couple of nodes, leading to a couple nodes having a ton of utilization while others are less so. Primary problem for us is that the hot nodes get close to their pod per node limit leading to alerting on our part. There doesn't seem to be any category for the scheduler to get it to no run right into the Pod per Node limit.

**Comment by davinchia** [comment]
@sidewinder12s fwiw, we ended up fixing this by changing the deploy to a daemonset. Since there is no good way of expressing 'at most n pod per node', the concession is to express 'exactly n pods per node'. Running this on a GCP node pool is how we control the total number of pods of that type we have. If you are AWS, taints will work too. Hope this helps.

**Comment by sidewinder12s** [comment]
@davinchia Thanks for the tip, we're seeing it with just general number of pods overall so we don't really have another toggle to switch unfortunately.
