### ISSUE TITLE
Kubernetes cluster NOT coming up

### ISSUE THREAD

**Issue by kushortiz** [kubernetes/kubernetes#63772]
Attempt 1 to check for SSH to master [ssh to master not working yet]
Attempt 2 to check for SSH to master [ssh to master working]
Attempt 1 to check for salt-master [salt-master not working yet]
Attempt 2 to check for salt-master [salt-master not working yet]
Attempt 3 to check for salt-master [salt-master not working yet]
Attempt 4 to check for salt-master [salt-master not working yet]
Attempt 5 to check for salt-master [salt-master not working yet]
Attempt 6 to check for salt-master [salt-master not working yet]
Attempt 7 to check for salt-master [salt-master not working yet]
Attempt 8 to check for salt-master [salt-master not working yet]
Attempt 9 to check for salt-master [salt-master not working yet]
Attempt 10 to check for salt-master [salt-master not working yet]
Attempt 11 to check for salt-master [salt-master not working yet]
Attempt 12 to check for salt-master [salt-master not working yet]
Attempt 13 to check for salt-master [salt-master not working yet]
Attempt 14 to check for salt-master [salt-master not working yet]
Attempt 15 to check for salt-master [salt-master not working yet]
Attempt 16 to check for salt-master [salt-master not working yet]
Attempt 17 to check for salt-master [salt-master not working yet]
Attempt 18 to check for salt-master [salt-master not working yet]
Attempt 19 to check for salt-master [salt-master not working yet]
Attempt 20 to check for salt-master [salt-master not working yet]
Attempt 21 to check for salt-master [salt-master not working yet]
Attempt 22 to check for salt-master [salt-master not working yet]
Attempt 23 to check for salt-master [salt-master not working yet]
Attempt 24 to check for salt-master [salt-master not working yet]
Attempt 25 to check for salt-master [salt-master not working yet]
Attempt 26 to check for salt-master [salt-master not working yet]
Attempt 27 to check for salt-master [salt-master not working yet]
Attempt 28 to check for salt-master [salt-master not working yet]
Attempt 29 to check for salt-master [salt-master not working yet]
Attempt 30 to check for salt-master [salt-master not working yet]
Attempt 31 to check for salt-master [salt-master not working yet]
Attempt 32 to check for salt-master
(Failed) output was:

salt-master failed to start on 18.237.87.8. Your cluster is unlikely
to work correctly. Please run ./cluster/kube-down.sh and re-create the
cluster. (sorry!)

**Comment by dims** [comment]
Please re-post your question to [Stack Overflow]
(http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support
are posted so that we can improve our efficiency in responding to your requests,
and to make it easier for you to find answers to frequently asked questions and
how to address common use cases.

We regularly see messages posted in multiple forums, with the full response
thread only in one place or, worse, spread across multiple forums. Also, the
large volume of support issues on github is making it difficult for us to use
issues to identify real bugs.

Members of the Kubernetes community use Stack Overflow to field support
requests. Before posting a new question, please search Stack Overflow for answers
to similar questions, and also familiarize yourself with:

user documentation
troubleshooting guide
Again, thanks for using Kubernetes.

The Kubernetes Team
