### ISSUE TITLE
Expose more information about server version.

### ISSUE THREAD

**Issue by iocanel** [kubernetes/kubernetes#64089]
/kind feature

I would like to be able to determine version/distro related information about the server, without having to make an API call.

** Internally
Internally the information provided by `kubectl version` could exposed as environment variables (e.g. SERVER_GIT_VERSION, SERVER_GIT_COMMIT and son on).

This way code that run inside Kubernetes could easily determine the server version without much effort.

** Externally 
There are cases, where it would be handy to have this piece of information even outside of kubernetes (mostly useful for tooling and development). For this case I am wondering if it would make sense to expose this information in `.kube/config` or a similar file.

If any of this make sense, I wouldn't mind working on a PR.

**Comment by liggitt** [comment]
> I would like to be able to determine version/distro related information about the server, without having to make an API call.


Can you clarify this? In most cases, kubectl is not being run on the server

**Comment by geoand** [comment]
@liggitt What @iocanel means if I am not mistaken has nothing to do with `kubectl`. 

The requested feature is about having Kubernetes inject new environment variables into each pod that would provide the Kubernetes distro and version. 
This information could also perhaps be in a some file under `/var/run/kubernetes` instead of / in addition to being in environment variables.

The point of the request is to allow applications running in Kubernetes to "know" more about the Kubernetes environment they are running in without having to make an API call to the Kubernetes master.

**Comment by liggitt** [comment]
ah. that is discoverable today via `https://kubernetes.default.svc/version`

I wouldn't anticipate that being added as envvars

**Comment by geoand** [comment]
@liggitt Exactly, we would like to avoid having to make a network call in order to retrieve such information. 

If not envvars, perhaps adding the information to a `/var/run/kubernetes` file?

**Comment by liggitt** [comment]
since the information is already available via an API, I don't think the complexity of adding options for also injecting it into containers is warranted

**Comment by dims** [comment]
marking this as wont-fix per last comment from @liggitt 

/close
