### ISSUE TITLE
AWS: Salt install sometimes stalls, causing install to fail

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#6413]
On AWS, the minion will sometimes fail to install:

```
...
Attempt 9 to check Docker on node deploy-justinsb-minion-1 @ 54.148.45.242 ... [not working yet]
Attempt 10 to check Docker on node deploy-justinsb-minion-1 @ 54.148.45.242 ... [not working yet]
Attempt 11 to check Docker on node deploy-justinsb-minion-1 @ 54.148.45.242 ...
Docker failed to install on node deploy-justinsb-minion-1. Your cluster is unlikely
to work correctly. Please run ./cluster/kube-down.sh and re-create the
cluster. (sorry!)
```

Logging in to minion-1, I can see that apt-get install is stuck on salt-minion.

```
root      6820  6216  3 15:57 ?        00:00:00 apt-get install -y -o DPkg::Options::=--force-confold salt-minion
root      6825  6820  0 15:57 ?        00:00:00 /usr/lib/apt/methods/http
root      6826  6820  0 15:57 ?        00:00:00 /usr/lib/apt/methods/http
```

I think GCE uses a reliable mirror for all external dependencies.  We should probably do the same for AWS.

**Comment by zmerlynn** [comment]
@justinsb: We've actually done a few things in this area. First, yes, when we actually go to install Salt, we do [grab it directly from GCS](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cluster/gce/configure-vm.sh#L133). We also, in the same function, [bang our head against the wall](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cluster/gce/configure-vm.sh#L156) to install the unmet deps. That said, two things:
* I've filed an itnernal bug just to bake this straight into ContainerVM, because just to `install-salt` function itself has a non-trivial failure percentage. 
* Even then, we actually do a sprinkling of package installs outside the `configure-vm` function, any one of which could fail. :(

**Comment by justinsb** [comment]
Closing as we now use the same kube-up infrastructure that GCE does
