### ISSUE TITLE
garbage characters (\x00) generating on container logs after logrotate

### ISSUE THREAD

**Issue by iam404** [kubernetes/kubernetes#64133]
We are using logrotate (mumoshu/kube-logrotate) deployed as a daemonsets to rotate all logs inside the directory (/var/lib/docker/containers) . In few cases I could see some garbage logs are being generated after logs are rotated:-

`failed to get parse function: unsupported log format: "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x`

Any idea what could be the issue ? happens mostly for the java applications.

**Comment by dims** [comment]
Please re-post your question to [Stack Overflow](http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases.

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans Stack Overflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search Stack Overflow for answers to similar questions, and also familiarize yourself with:

[user documentation](http://kubernetes.io/docs/)
[troubleshooting guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/)
Again, thanks for using Kubernetes.

The Kubernetes Team

/close

**Comment by koenkarsten** [comment]
@iam404 I'm experiencing the same issue now, did you manage to find the answer somewhere?

**Comment by tracyshen** [comment]
any idea...

**Comment by iam404** [comment]
Moving to docker's builtin log rotate solved this for us. - https://docs.docker.com/config/containers/logging/json-file/
