### ISSUE TITLE
configmap with springboot-application.properties

### ISSUE THREAD

**Issue by hppx5456** [kubernetes/kubernetes#64131]
What happened:
I want to mount the configuration file in the springboot with configmap to achieve the application auto heel when modifying the configmap, but now you don't use the configuration data in the configmap when you start the project

Anything else we need to know?:
this is my deployment.yaml
![image](https://user-images.githubusercontent.com/26714352/40343946-ff8d3928-5dc4-11e8-8b2c-cb04f97c478c.png)

this is configmap
![image](https://user-images.githubusercontent.com/26714352/40343973-2b5f4a50-5dc5-11e8-8d8a-32e53af635cd.png)

when i use kubectl exec -it springboot-mychart-78657856c7-cjsv7 /bin/bash
i see Configmap has been mounted in the container
![image](https://user-images.githubusercontent.com/26714352/40344011-606eb67c-5dc5-11e8-8f01-d841f930250a.png)
![image](https://user-images.githubusercontent.com/26714352/40344026-748bbcfe-5dc5-11e8-80ec-0c00a566aa44.png)

But when I looked at docker logs, I found that the port that the container started was 8080, not the 8999 I set in configmap.
![image](https://user-images.githubusercontent.com/26714352/40343961-17926868-5dc5-11e8-9bfc-13e87bc4eb5e.png)

Environment:

Kubernetes version (use kubectl version):
Cloud provider or hardware configuration:
OS (e.g. from /etc/os-release):
Kernel (e.g. uname -a):
Install tools:
Others:

**Comment by stefanosirplay** [comment]
I think you should check if spring boot takes the configuration from that path. At enviroment levels everything seems to be correct. Take another check on spring boot.

**Comment by dims** [comment]
Please re-post your question to [Stack Overflow](http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases.

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans Stack Overflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search Stack Overflow for answers to similar questions, and also familiarize yourself with:

[user documentation](http://kubernetes.io/docs/)
[troubleshooting guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/)
Again, thanks for using Kubernetes.

The Kubernetes Team

/close
