### ISSUE TITLE
Foreground deletion for daemonset doesn't work

### ISSUE THREAD

**Issue by soltysh** [kubernetes/kubernetes#64313]
/kind bug
/priority critical-urgent

**What happened**:
In https://github.com/kubernetes/kubernetes/pull/63979 I'm removing all the reapers, unfortunately when invoking foreground deletion on a DaemonSet the delete operation hangs and controller indefinitely tries to manage a removed DS. 

**What you expected to happen**:
A foreground deletion properly removes DaemonSet and all its dependents. 

**How to reproduce it (as minimally and precisely as possible)**:
Invoke a delete operation against kube API (without using `kubectl delete` command). 

**Anything else we need to know?**:
This behavior makes it so that none of the consumers of the API is not able to remove the DS controller due to [this custom logic](https://github.com/kubernetes/kubernetes/blob/8b442973ac950faa1ecc580df75b756062a937a5/pkg/kubectl/delete.go#L300-L324) present in the DS reaper. A working fix that passed the tests with the aforementioned PR is in https://github.com/kubernetes/kubernetes/pull/64306 but I'm not 100% it's correct. 

This is an issue that needs fixing before 1.11 goes out.

/assign @kow3ns @janetkuo 
/sig apps

/cc @deads2k

**Comment by soltysh** [comment]
@kubernetes/sig-apps-bugs fyi

**Comment by janetkuo** [comment]
I filed #64797 to fix it. 

As mentioned in the PR, this is because that DaemonSet controller races with garbage collector when it tries to update DaemonSet status of the DaemonSet being deleted. 

Here's what happened:
1. Someone/something performs a foreground deletion on a DaemonSet
1. DaemonSet finalizer and DeletionTimestamp are both set
1. DaemonSet history objects (ControllerRevisions) and pods are being deleted by garbage collector; meanwhile, DaemonSet controller tries to update DaemonSet status. 
    * Updating DaemonSet status requires constructing DaemonSet history objects, to figure out current revision and which pods do/don't belong to current revision
1. When updating DaemonSet status, DaemonSet controller tries to create a DaemonSet history object that matches current DaemonSet spec
1. Garbage collector then tries to delete that DaemonSet history object. And repeat. 

Because we can't make DaemonSet pods be deleted before DaemonSet history objects (DaemonSet history objects don't own DaemonSet pods!), we cannot reliably calculate DaemonSet status without history objects anyways. Therefore, we don't update DaemonSet status for DaemonSet being deleted. 

Note that the reason why the kubectl delete hack works is because it forces DaemonSet pods to be removed before history objects.
