### ISSUE TITLE
Node stay in NotReady state (Ubuntu Single Node)

### ISSUE THREAD

**Issue by artto** [kubernetes/kubernetes#6440]
> > kubectl get nodes
> NAME &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; LABELS&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; STATUS
> 127.0.0.1 &nbsp;&nbsp;&nbsp;`<none>` &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  NotReady

Therefore all pods stay in Pending state. What might be the reason?

> > kubectl get events
> FIRSTSEEN                         LASTSEEN                          COUNT               NAME                            KIND                SUBOBJECT           REASON              SOURCE              MESSAGE
> Tue, 31 Mar 2015 18:33:34 +0300   Tue, 31 Mar 2015 19:56:05 +0300   211                 redis-master-controller-fplln   Pod                                     failedScheduling    {scheduler }        Error scheduling: no minions available to schedule pods

**Comment by yujuhong** [comment]
Hi @artto, what version of kubelet are you running? HEAD?

You can check if kubelet process is running on the node. You can also run `curl -L http://127.0.0.1:10250/healthz` to see if kubelet responds with `ok`.

We changed to posting the node status from kubelet recently, so if you are running HEAD and kubelet is running, you could open `kubelet.log` to see if there is any error about updating the node status.

**Comment by xuhuiy** [comment]
Hi @artto,

I had the same issue with you, did your resolve your problem yet? If yes, could you share your method please? Thanks advance. BTW, I try to check the log in kubelet.log, but I cannot found this file in the master or minion machine.

**Comment by yujuhong** [comment]
@xuhuiy, `kubelet.log` should be in in `/var/log` or `/tmp`. Here is some general [debugging FAQ](https://github.com/GoogleCloudPlatform/kubernetes/wiki/Debugging-FAQ) that might be of help too.

**Comment by Dekarti** [comment]
@xuhuiy, I just updated to latest version of `Docker`.

**Comment by xuhuiy** [comment]
@Dekarti  Thanks...

**Comment by wpc009** [comment]
I got the same `NotReady` forever situation. But it seems the reason is different.
First. The `kubelet` fail to listen on port `10250`, after checking the log in `/var/log/upstart/kubelet.log` 
```
Failed to execute Info() call to the Docker client: dial unix /var/run/docker.sock: no such file or directory
```

It seems something wrong with the docker daemon.
`ps aux | grep docker` shows there's no docker daemon running.
Then a `service docker start`, it still can not running.
checking `/var/log/upstart/docker.log`
```
invalid value "" for flag --mtu: strconv.ParseInt: parsing "": invalid syntax
See '/usr/bin/docker daemon --help'.
```
checking `/etc/default/docker`
```
DOCKER_OPTS=" -H tcp://127.0.0.1:4243 -H unix:///var/run/docker.sock --bip= --mtu="
```
Ok, seems faulty `DOCKER_OPTS`, 
checking  `cluster/ubuntu/reconfDocker.sh#L57` 
```
56   echo DOCKER_OPTS=\"${DOCKER_OPTS} -H tcp://127.0.0.1:4243 -H unix:///var/run/docker.sock \
57        --bip=${FLANNEL_SUBNET} --mtu=${FLANNEL_MTU}\" > /etc/default/docker
```

It overrides the `/etc/default/docker` file with a empty `FLANNEL_MTU` variable. 
And, there no mentioning this variable in the [tutorial](http://kubernetes.io/v1.0/docs/getting-started-guides/ubuntu.html), also no default value in `cluster/ubuntu/config-default.sh`

**Comment by wpc009** [comment]
By the way, I'm using the `v1.2.0-alpha.2` release

**Comment by bgrant0607** [comment]
FLANNEL_MTU also looks like it is used but not set in https://github.com/kubernetes/kubernetes/blob/master/docs/getting-started-guides/docker-multinode/master.sh

**Comment by roberthbailey** [comment]
Both `cluster/ubuntu` and the docker-multinode getting started guides have been removed so I'm going to close this as obsolete.
