### ISSUE TITLE
`ListImages()` handle docker.io/library not consistently across different CRI runtimes

### ISSUE THREAD

**Issue by resouer** [kubernetes/kubernetes#64413]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:

/kind bug

**What happened**:

Kubelet  will set images list fetched by `ListImages()` to `NodeStatus`, but this result actually varies from different CRI runtimes.

e.g. a pod has spec of `docker.io/library/nginx:1.7.9` image, then the `NodeStatus` is:

cri-containerd (and maybe the same for other CRI shims):
 ```
  - names:
    - docker.io/library/nginx:1.7.9
    sizeBytes: 39947836
```
Docker:
```
  - names:
    - nginx@sha256:e3456c851a152494c3e4ff5fcc26f240206abac0c9d794affb40e0714846c451
    - nginx:1.7.9
    sizeBytes: 91664166
```

**What you expected to happen**:

The problem is: these image names in `NodeStatus` is now used in scheduler to make scheduling decision, and many other third-party systems also consume this information, I will expect a consistent result be set in `NodeStatus`. 

I proposed a fix on node level: #64487,  but I am open for future discussion, for example, if we should solve this in runtime shims and return consistent results. 

Ref: #63842, I have shipped a temporary workaround so we will not block this scheduling feature from 1.11. 

**How to reproduce it (as minimally and precisely as possible)**:

Kubernetes with different runtimes, then diff the NodeStatus.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by resouer** [comment]
Also cc @mtaufen should be interested in this issue.

**Comment by mtaufen** [comment]
Agree the status should be backwards-compatible with existing consumers no matter which runtime is used.

**Comment by dchen1107** [comment]
I am also wondering why the sizes of the same image are different here:

cri-containerd (and maybe the same for other CRI shims):
```
   sizeBytes: 39947836
```
Docker:
```
    sizeBytes: 91664166
```

**Comment by Random-Liu** [comment]
> Would like to know your thoughts, I can send a fix if we agree this inconsistency is not expected.

It depends on whether we are ok with treating `docker.io/library` as default in Kubernetes.
* If yes, we can normalize the image name in Kubelet, and get rid of the prefix.
* If not, we can normalize the image name in Kubelet to ensure the prefix.

I'm fine with either, but leaning to not treating `docker.io/library` as default. No matter which one we choose, we should do the same thing in both scheduler and kubelet to make sure they see the same image name.

> I am also wondering why the sizes of the same image are different here.

Containerd reports compressed content size (part of OCI image spec, actual image size in image registry); Dockershim reports the image "virtual size" (uncompressed on disk image size).

CRI doesn't define what this size means.

Kubelet may care more about the uncompressed on-disk size to do disk management. Today, kubelet uses the size to order images and do image garbage collection. However, that is not that accurate as well because kubelet does not consider layer sharing.

@resouer Does scheduler care about the image size? What kind of "size" does scheduler care about more?

**Comment by mtaufen** [comment]
>leaning to not treating docker.io/library as default

I agree with this, prefer to be explicit in all cases.

**Comment by resouer** [comment]
@Random-Liu The `ImageLocalityPriority` will prefer node with image already exists if that image size large enough. 

So it should be the `compressed content size` as containerd reports. We need to fix it somehow. 

I agree not treat `docker.io/library` as default in Kubernetes, so if you read #64487, I proposed using full qualified name for both scheduler and node status.

**Comment by yujuhong** [comment]
> @Random-Liu The ImageLocalityPriority will prefer node with image already exists if that image size is large enough. So it should be the compressed content size as we want to save pulling time.

Does ImageLocalityPriority use an absolute threshold for size? If not, whether the size refers to compressed or uncompressed should not matter much, should it?


+1 for not treating `docker.io/library` as default in kubernetes. However, users often don't specify the full registry name in the pod spec. As a result of that, the scheduler would have a hard time matching `nginx:1.7.9` in the pod spec to `docker.io/library/nginx:1.7.9` reported in the node status. @resouer does your PR solve that issue?

**Comment by resouer** [comment]
@yujuhong Yes, the scheduler side PR is #63842, it always converts user's image spec to full name before matching and I will let that change in first. 

> Does ImageLocalityPriority use an absolute threshold for size? If not, whether the size refers to compressed or uncompressed should not matter much, should it?

`ImageLocalityPriority` do have a threshold like this to calculate score:
```go
const (
	mb         int64 = 1024 * 1024
	minImgSize int64 = 23 * mb
	maxImgSize int64 = 1000 * mb
)
```
That's why I am a bit concerned here.

**Comment by Random-Liu** [comment]
> It depends on whether we are ok with treating `docker.io/library` as default in Kubernetes.
> * If yes, we can normalize the image name in Kubelet, and get rid of the prefix.
> * If not, we can normalize the image name in Kubelet to ensure the prefix.

Hm, a bit too tired today, I don't remember what I meant here...... :P 

What I want to say is that:
* If yes, we can normalize the image name in both scheduler and kubelet, and make sure they see the same image name.
* If not, we can enforce container runtime to return normalized image name.

> +1 for not treating docker.io/library as default in kubernetes. However, users often don't specify the full registry name in the pod spec. As a result of that, the scheduler would have a hard time matching nginx:1.7.9 in the pod spec to docker.io/library/nginx:1.7.9 reported in the node status.

Yeah, if so, we may need container runtime to either return all possible image names...

**Comment by resouer** [comment]
@Random-Liu Yes, I actually re-used `dockerref` in parser so all the corner cases you mentioned have been covered, I just amended a test in  #64487 to verify it.

**Comment by mtaufen** [comment]
>docker.io/busybox == docker.io/library/busybox == library/busybox == busybox

ugh

**Comment by yujuhong** [comment]
@resouer I am not sure that we can reasonably assume all container runtimes use `docker.io` as the default registry, AND follow all the flexible interpretations in `dockerref`. 
(I know it's not configurable in docker, but that doesn't mean other runtimes or forks do not allow any override)

If we had to assume there is a single default registry per kubernetes cluster, we should at least make it configurable -- but that'd lead to a series of issues too (e.g., backward-compatibility, admin needs to ensure this is true on all nodes, etc).

I'd suggest we ignore the corner cases @Random-Liu mentioned above for this feature (since it's inherently a best-effort attempt), and return the image name used to pull AND the canonical name (with full registry name). WDYT?

**Comment by resouer** [comment]
@yujuhong Thanks yuju, I totally understand your concern. I think this compromise is acceptable, as the only flaw will be: `docker.io/image:tag` can not be matched with `image:tag`. 

I will update  #64487 and ping you folks when it's ready.

**Comment by resouer** [comment]
I'd choose to keep the normalization workaround in scheduler for 1.11 since this exception is not common.
