### ISSUE TITLE
CSI attach/detach should use shared informer

### ISSUE THREAD

**Issue by jsafrane** [kubernetes/kubernetes#64429]
/kind bug
/sig storage

CSI volume unnecessarily abuses API server with Create/Watch/Delete VolumeAttachment calls, while A/D controller already has a shared informer for `VolumeAttachment` objects. CSI's `Attach()` and `Detach()` should use the shared informer from A/D controller:

- to check if `VolumeAttachment` exist before creating it at https://github.com/kubernetes/kubernetes/blob/4a7a18653cf1790fa946b8e87f68d86ce1612d8f/pkg/volume/csi/csi_attacher.go#L89

- to watch for `VolumeAttachment` changes at https://github.com/kubernetes/kubernetes/blob/4a7a18653cf1790fa946b8e87f68d86ce1612d8f/pkg/volume/csi/csi_attacher.go#L156

- to check if `VolumeAttach` is deleted or marked for deletion at https://github.com/kubernetes/kubernetes/blob/4a7a18653cf1790fa946b8e87f68d86ce1612d8f/pkg/volume/csi/csi_attacher.go#L380 and associated watch at https://github.com/kubernetes/kubernetes/blob/4a7a18653cf1790fa946b8e87f68d86ce1612d8f/pkg/volume/csi/csi_attacher.go#L423

Perhaps we could smuggle the shared informer into the plugin as a new parameter to `ProbeVolumePlugins()` at https://github.com/kubernetes/kubernetes/blob/4a7a18653cf1790fa946b8e87f68d86ce1612d8f/pkg/volume/csi/csi_plugin.go#L50 (but more investigation is needed).

**Comment by misterikkit** [comment]
+1 to this. The current implementation creates a Watch per Attach operation, and that could result in dozens of concurrent watch requests during a spike.

**Comment by chrishenzie** [comment]
Looking into this. The CSI plugin has access to a volume attachment lister which we can use to check for the existence of volume attachments:
https://github.com/kubernetes/kubernetes/blob/58bd3e5230df253cb23c22641883b87da92e5f43/pkg/volume/csi/csi_plugin.go#L197

**Comment by chrishenzie** [comment]
I've been working on this for quite a while now and keep getting tangled in the process. Below are some notes and open questions.

- As an intermediate step, I tried replacing the API `get()` calls with `volumeAttachmentLister.get()`, however this is not possible because
  - We clear the `volumeAttachmentLister` if the volume host is a `KubeletVolumeHost`
https://github.com/kubernetes/kubernetes/blob/476afe93f119578389b4e7810fa1f64ac24ddbfe/pkg/volume/csi/csi_plugin.go#L214-L215
  - Even if you remove this, you get a nil pointer deference trying to fetch the VolumeAttachment object from the lister in `waitForVolumeAttachmentInternal()`
- Do we want to use a SharedInformer for both the `AttachDetachVolumeHost` and `KubeletVolumeHost` types? Or just `AttachDetachVolumeHost`? 
  - The way the CSI attacher tries to support both interfaces makes it so that we have to adjust the implementation on the fly depending on which interface the volume host implements
    - For example, in `waitForVolumeAttachDetachStatus()` we would need to do something like
      - If `AttachDetachVolumeHost`, then watch for change using SharedInformer
      - Else if `KubeletVolumeHost`, watch for change by creating a watch in the API
    - As an alternative, are we comfortable allowing each Kubelet to have a SharedInformer for VolumeAttachments?
- Are there any efforts to split this attacher into separate types, one for the AttachDetachController, and one for Kubelet?
  - All signs point me to thinking this needs to be split up, adding more logic to this CSI attacher to try and support both makes this more challenging to piece apart
