### ISSUE TITLE
API Server Start Failed with no clearly exception details

### ISSUE THREAD

**Issue by JokerMonitor** [kubernetes/kubernetes#64430]
The kube-apiserver.service as below:
`
[Unit]
Description=Kubernetes API Server
Documentation=https://github.com/GoogleCloudPlatform/kubernetes
After=network.target

[Service]
User=root
ExecStart=/usr/bin/kube-apiserver \
  --admission-control=NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,ResourceQuota \
  --advertise-address=172.18.71.208 \
  --allow-privileged=true \
  --apiserver-count=3 \
  --audit-log-maxage=30 \
  --audit-log-maxbackup=3 \
  --audit-log-maxsize=100 \
  --audit-log-path=/var/lib/audit.log \
  --authorization-mode=Node,RBAC \
  --bind-address=172.18.71.208 \
  --enable-swagger-ui=true \
  --etcd-servers=http://172.18.71.208:2379 \
  --event-ttl=1h \
  --kubelet-https=true \
  --insecure-bind-address=127.0.0.1 \
  --runtime-config=rbac.authorization.k8s.io/v1alpha1 \
  --service-cluster-ip-range=10.254.0.0/16 \
  --enable-bootstrap-token-auth \
  --token-auth-file=/etc/kubernetes/token.csv \
  --endpoint-reconciler-type=lease \
  --v=2
Restart=on-failure
RestartSec=5
Type=notify
LimitNOFILE=65536

[Install]
WantedBy=multi-user.target
`
when I execute journalctl -xe after systemctl restart kube-apiserver failed,
I got the error logs that without clearly details : 

![image](https://user-images.githubusercontent.com/23333395/40646755-baab3632-635c-11e8-838f-10a5dd8828c3.png)

I checked the kube-apiserver.service but seems there has no invalid arguments.

**Anything else we need to know?**:
The  etcd server has already started without certification.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.8.2
- Linux iZwz95pz734d3ef79lnd61Z 4.4.0-105-generic #128-Ubuntu SMP Thu Dec 14 12:42:11 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by dims** [comment]
Please re-post your question to [Stack Overflow](http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases.

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans Stack Overflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search Stack Overflow for answers to similar questions, and also familiarize yourself with:

[user documentation](http://kubernetes.io/docs/)
[troubleshooting guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/)
Again, thanks for using Kubernetes.

The Kubernetes Team
