### ISSUE TITLE
already in flight abandoning

### ISSUE THREAD

**Issue by qiyongxiao** [kubernetes/kubernetes#64552]
hi, I am use the kubernetes(1.10.3) and docker(1.13.1). And I exec the command:
`kubectl create -f influxdb.yaml`
and the docker show the issues was this:
`May 31 18:53:59 kubernetes-master01v dockerd-current[75498]: W0531 10:53:59.280830       1 factory.go:1304] Request for pod kube-system/monitoring-influxdb-55bbd4b96-97dp7 already in flight, abandoning
May 31 19:02:18 kubernetes-master01v dockerd-current[75498]: W0531 11:02:18.496300       1 factory.go:1324] A pod kube-system/monitoring-influxdb-55bbd4b96-97dp7 no longer exists
`
Then I'll to see the pos status, there is show "pending"
`kube-system   monitoring-influxdb-55bbd4b96-97dp7   0/1   Pending   0    5m  <none>    <none>`
How should I to solve it?
Please give me an mind.

**Comment by dims** [comment]
Please re-post your question to [Stack Overflow](http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases.

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans Stack Overflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search Stack Overflow for answers to similar questions, and also familiarize yourself with:

[user documentation](http://kubernetes.io/docs/)
[troubleshooting guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/)
Again, thanks for using Kubernetes.

The Kubernetes Team
