### ISSUE TITLE
TestVersionedClusterScopedCRD is flaky

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#64571]
both in PR and CI runs

see https://storage.googleapis.com/k8s-gubernator/triage/index.html?pr=1&test=TestVersionedClusterScopedCRD

/assign @mbohlool

**Comment by mbohlool** [comment]
Interesting fact: `TestVersionedNamspacedScopedCRD` is not flaky, only `TestVersionedNamspacedScopedCRD`. The test codepath for these two are almost identical. I wonder if this is a real bug not a flaky test.

**Comment by liggitt** [comment]
still seeing flakes like https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/65256/pull-kubernetes-integration/16674/

the loop that ensures the watch cache is primed goes version-by-version, and creates and observes the delete event for that version. it does not ensure the delete event is drained from the watch caches for the other versions.

**Comment by liggitt** [comment]
a better approach would be probably be to:

Poll(
  create object
  delete object
  for v := range version {
    observe delete event or fail
  }
)

**Comment by liggitt** [comment]
Moves the version loop inside the poll

Today we loop over versions and poll per version, which can leave unconsumed delete events in prior versions

**Comment by sttts** [comment]
Cannot follow. Now we have the following without a poll:

```
for v := range version {
  create object as v
  for v2 := range version {
      <- v2 watch channel or timeout
  }
  delete object as v
  for v2 := range version {
      <- v2 watch channel or timeout
  }
}
```

**Comment by liggitt** [comment]
https://github.com/kubernetes/kubernetes/blob/debc5387fe1f038c28903bf68996222fbe218182/staging/src/k8s.io/apiextensions-apiserver/test/integration/testserver/resources.go#L261-268

**Comment by sttts** [comment]
Ok, so we were talking about different code. good.

To understand:

- we do a `isPrimed` call per version, each creating and deleting an object, and waiting for the delete event with a `rv=createdResourceVersion` watch call.
- a following `rc=0` watch will not see the events of the `isPrimed` calls of itself (because they use the same versioned watch cache) and of any version in front of it in the version slice (is this true?), but it might see events of `isPrimed` calls of versions later in the version slice.

So with your outer poll and inner version loop we would make sure that we drain every version's cache for following rv=0 watch requests. Sounds plausible.

**Comment by sttts** [comment]
Where do we have the official watch axioms?

**Comment by mbohlool** [comment]
I think I know what is the problem here. We make sure the watch is primed for `v1`. then we move on to `v2` and make sure the watch is primed by creating another object in `v2`. The watch cache is drained for `v2` but the watch cache for `v1` is not and that is the problem here. will send a fix.

**Comment by mbohlool** [comment]
I didn't see your comment when I commented. Your description is accurate.
