### ISSUE TITLE
`PodTolerationRestriction` admission controller: add default cluster tolerations to the default whitelisted tolerations

### ISSUE THREAD

**Issue by edganiukov** [kubernetes/kubernetes#64616]
**What happened**:
After enabling the admission controller "PodTolerationRestriction",  I've added to the `scheduler.alpha.kubernetes.io/tolerationsWhitelist` namespace annotation and to the Pod spec a toleration (e.g `[{"operator": "Exists", "key": "node-role.kubernetes.io/master", "effect": "NoSchedule"}]`).
But it doesn't allowed to schedule a Pod and fails with an error:
```
pod tolerations (possibly merged with namespace default tolerations) conflict with its namespace whitelist
```

To solve the issue necessary to add to the `scheduler.alpha.kubernetes.io/tolerationsWhitelist` annotation  more tolerations (which are cluster default tolerations):
```
{"operator": "Exists", "effect": "NoSchedule", "key": "node.kubernetes.io/memory-pressure"},
{"operator": "Exists", "tolerationSeconds": 300, "effect": "NoExecute", "key": "node.kubernetes.io/unreachable"},
{"operator": "Exists", "tolerationSeconds": 300, "effect": "NoExecute", "key": "node.kubernetes.io/not-ready"}
```
 

I think it makes sense to add these tolerations as default whitelisted tolerations (having default toleration whitelisted) or, at least, to mention this in the documentation.
When there is no tolerationsWhitelist, all tolerations are whitelisted, thats why this issue occurs when 

**Environment**:
- Kubernetes version (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.1", GitCommit:"3a1c9449a956b6026f075fa3134ff92f7d55f812", GitTreeState:"clean", BuildDate:"2018-01-04T11:40:06Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.1", GitCommit:"3a1c9449a956b6026f075fa3134ff92f7d55f812", GitTreeState:"clean", BuildDate:"2018-01-04T11:40:06Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
```

/kind bug
/sig scheduling

**Comment by lbernail** [comment]
/remove-lifecycle stale

We would also be interested in this (merging default cluster tolerations with the whitelist to avoid having to add them explicitly)

**Comment by rvadim** [comment]
There are no documentation about this case. I spent a few hours in order to get proper configuration.

**Comment by aauren** [comment]
For what it's worth, this issue bit us during our usage of the admissions controller as well. I think that it's unreasonable to expect teams constructing this annotation to have to understand all of the default tolerations that may be applied to a pod. Especially when this can be different depending on the controller that creates the resulting pod from the higher level archetype.

In our example, when we attempted to use this annotation we did a good set of testing using deployments and it took a while to figure out why the whitelist was conflicting until we found this issue and accounted for the default deployment tolerations. Then we happily deployed that into our production zone. Until we realized that we could no longer schedule daemonsets because [the daemonset controller provides an entirely different set of default tolerations](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/daemon/util/daemonset_util.go#L49) that we had not whitelisted.

While the tolerations, have stayed static now for the last couple of Kubernetes releases, there's certainly no guarantee that a future version of k8s might not add or change one of these causing another round of debugging. In the end we concluded that `tolerationsWhitelist` was too problematic to use for our use-case.

**Comment by edganiukov** [comment]
@aauren I had to compile the apiserver with some debug statements in order to find this list of default tolerations.
I think you should not expect that such kind of bugs (and I still think it is a bug) would be fixed quickly, it is not a new feature for google cloud, azure, etc. Even though it is an open source project, but it is quite a big project, that has many code owners that are mostly hired to do the job. 
Yeah, there is no guarantee that it won't be changed anytime soon or deprecated, so you have to be very careful with upgrades.

**Comment by kfox1111** [comment]
Until this is resolved, would anyone be willing to share the config they needed to get deployments/daemonsets to work here? May help others needing to do the same save some time.

**Comment by edganiukov** [comment]
@kfox1111 but I've described in the issue what you need to do to solve the problem.

**Comment by kfox1111** [comment]
@edganiukov, I was kind of intending to ask @aauren if he had more annotations not in the original issue description he could share. Maybe a complete scheduler.alpha.kubernetes.io/tolerationsWhitelist line. I worded my question badly though. Sorry.

**Comment by mtb-xt** [comment]
@kfox1111 

At least my tolerations whitelist looks like this. Notice 2 custom ones in the first two lines, and the rest are the 'default' ones

```
    scheduler.alpha.kubernetes.io/tolerationsWhitelist: '
      [
        { "key":"lifecycle", "operator":"Equal", "value":"ondemand", "effect":"PreferNoSchedule" }, 
        { "key":"special", "operator":"Exists", "effect":"NoSchedule"
        {"operator": "Exists", "effect": "NoSchedule", "key": "node.kubernetes.io/memory-pressure"}, 
        {"operator": "Exists", "tolerationSeconds": 300, "effect": "NoExecute", "key": "node.kubernetes.io/unreachable"},
        {"operator": "Exists", "tolerationSeconds": 300, "effect": "NoExecute", "key": "node.kubernetes.io/not-ready"},
      }]'
```

**Comment by kfox1111** [comment]
Great. Thanks. :)

**Comment by gischethans** [comment]
Does anyone know what needs to be added in the tolerations whitelist for a statefulset? The keys quoted by @mtb-xt did not work in my case. I tried including the following but that did not help - 

```
{"operator": "Exists", "effect": "NoSchedule", "key": "node.kubernetes.io/pid-pressure"}, 
{"operator": "Exists", "effect": "NoSchedule", "key": "node.kubernetes.io/disk-pressure"}
```
CC @edganiukov
