### ISSUE TITLE
Support clusterIPs as endpoints in services

### ISSUE THREAD

**Issue by alvaroaleman** [kubernetes/kubernetes#64668]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature
/sig network

This is a follow-up on #40870 which has been closed by updating the documentation via kubernetes/website#8028 to state

>The endpoint IPs [..] cannot be the cluster IPs of other Kubernetes services either because the 
> `kube-proxy` component doesn't support virtual IPs as destination yet.

Also it was mentioned that one could use services of type `ExternalName` instead. However I think this does not cover all use-cases because:

* `ExternalName` services can only be used in-cluster, they can not be used to forward traffic from a service type `LoadBalancer` to a different service
* There are use-cases where it is desirable to have one public IP that forwards on different ports to different backends, e.G. a Git solution that forwards on 443/tcp to an ingress controller and on 22/tcp to the ssh server
* There are organizations that require whitelisting public IPs in order to access them from internal systems, being forced to have one service type `loadBalancer` with a distinct IP per service instead of being able to use different ports for different backing services makes introducing new services running in a k8s cluster unnecessary time-consuming
* `ExternalName` has the drawback that changing the target may not cause the clients that use it to immediately switch, because DNS tends to get cached

However adding this feature has a drawback, namely that it requires special handling for the IPTables and IPVS backends in `kube-proxy` (In the userspace mode this already works). Please see my pull at #63039 as a sample on how that could look in IPTables.

I want to use this issue to clarify if this is a feature we want, assuming someone is willing to implement it.

CC @thockin and @caseydavenport as you suggested in the original issue to use `ExternalName` services and just document this limitation.

**Comment by robhaswell** [comment]
In the same section as the updated documentation there is this example:

> You want to point your service to a service in another Namespace or on another cluster.

I don't know how you can point a service to another service while still observing the restriction "They cannot be the cluster IPs of other Kubernetes services either because the kube-proxy component doesn't support virtual IPs as destination yet."

If my understanding is correct and these are conflicting statements then at very least the documentation should be accurate. However I found a use for pointing a service at another service. We run both prerelease and live versions of our application in two namespaces, and we route the traffic to whichever is the current namespace. The routing is done using a HAProxy container, but we would have less to maintain if we could use service-to-service routing as advertised.

I would vote :+1: to implementing this feature.

**Comment by thockin** [comment]
Some clouds (e.g. GCP) allow this by using the same IP on 2 different Services, but it is not part of the portable Kubernetes feature set.

I guess I am not against the general idea - the git HTTP vs SSH model is a good example - but I am not sure "adding a service IP as an endpoint" is how I would model it.  

If we went this route, it feels like a mux or a meta-service.  Allocate an IP with multiple subsections, each of which is a set of incoming ports and target services.  I am not sure that I would model this as a Service at all.  I can sort of see how the iptables implementation would look, and ipvs seems plausible.

The bigger issue I see is that there's a general trend towards more "native" handling of Kubernetes and away from complex intermediate representations (e.g. iptables).  e.g. external load-balancers that know how to contact pods directly.  I don't know the programability of them, so it's hard to guess how these would interact.  I would love if someone did a survey of existing kube-supported LBs to see how many allow different ports to target different backends.
