### ISSUE TITLE
match pause pod can not found

### ISSUE THREAD

**Issue by loveai88** [kubernetes/kubernetes#64676]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
I found that some pod not has match pause container,so kubelet can not stop the pod .How dose it happened.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (1.8.5):
- Cloud provider or hardware configuration:
- OS (centos 7):
- Kernel (3.10.0-514):
- Install tools:
- Others:

**Comment by dims** [comment]
Please re-post your question to [Stack Overflow](http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases.

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans Stack Overflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search Stack Overflow for answers to similar questions, and also familiarize yourself with:

[user documentation](http://kubernetes.io/docs/)
[troubleshooting guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/)
Again, thanks for using Kubernetes.

The Kubernetes Team
