### ISSUE TITLE
terminationGracePeriodSeconds is overloaded

### ISSUE THREAD

**Issue by unclewizard** [kubernetes/kubernetes#64715]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind feature

**What happened**:

Currently, terminationGracePeriodSeconds is used for both normal termination and when a liveness probe fails. I have a service that serves long-running connections, and which uses a long termination period to allow those connections to drain during normal termination of services. However, this causes problems when the service is failing and needs to be restarted because the same grace period is being applied to shutdowns that occur as the result of a failed liveness probe.

**What you expected to happen**:

Liveness probe failures should immediately terminate the pod, or have a different setting to control the timeout.

**How to reproduce it (as minimally and precisely as possible)**:

- Create a deployment with a container that has a liveness probe
- Don't respond to sigterm or the liveterm in the main container process
- add a long terminationGracePeriodSeconds
- Note that the liveness probe fails immediately but the pod hangs around for terminationGracePeriodSeconds

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.9.7-gke.0
- Cloud provider or hardware configuration: gke
- OS (e.g. from /etc/os-release): 
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by vishal-biyani** [comment]
@unclewizard Have you noticed this for readiness probe as well?

**Comment by unclewizard** [comment]
I haven't tried it for the readiness probe.

**Comment by smarterclayton** [comment]
This is definitely a bug / underspecified / unintended linkage.

liveness failures trigger container kill processing in the Kubelet, which by default follows graceful rules.  But stop in happy path (termination grace) is intended to be othogonal to stop in unhappy path (liveness) so that you can tune independently (very long shutdown for services that want to handle requests).  The current coupling prevents apps from being responsive to liveness failure and graceful shutdown, which is bad.

Needs some discussion but this is definitely not intended behavior.

**Comment by smarterclayton** [comment]
It’s possible people are abusing / unintentionally depending on this coupling - https://stackoverflow.com/questions/63138138/is-it-possible-to-specify-a-delay-for-pod-restart-when-kubernetes-liveness-probe implies some people might assume that this is how it should work.  The counter argument is that the expectation for liveness is to maintain the availability of your pod when it is not ready or working, so the time bounds for the liveness probe to react to failure are a better indicator of your tolerance for delay than the grace period.  We may have to introduce a way to tune that tolerance if we decouple.

**Comment by smarterclayton** [comment]
There are several use cases for terminationGracePeriodSeconds:

1. Delay shutdown to continue processing requests (from seconds to minutes to hours) in combination with app code that waits or a preStop hook (grace period must be set *longer* than the expected wait time)
2. Ensure that the process has time to react to SIGTERM before SIGQUIT is sent, because the process may not be crash safe (historically this was the primary reason for the introduction of terminationGracePeriodSeconds because crash-safety isn't universal for linux processes and was less common 6 years ago than it is today) or because the process can avoid a lengthy restart by recording some set of info prior to shutdown
3. To delay the drain process of a node (`kubectl drain`) by "guarding" other pods like daemonsets or system services, or as a simulated PDB blocker for preserving quorum of operators (PDB is not very effective for sharded services today)

Reason 2 above is the one most at risk if we change the current behavior of liveness shutdown (bypass grace period), since applications that are currently "safe" because the process waits long enough suddenly start receiving SIGQUIT earlier.

Reason 1 is the one most impacted by this coupling bug - a user who increases their grace period to better handle termination and long running requests becomes less resilient because their liveness probes are silently going to take longer to react.  In the extreme, for ingress controllers today using grace periods of intervals from minutes to hours, when liveness kicks in they are also waiting an hour for the process to be terminated, which is very undesirable.

Some fix options:

* Introduce a new field to livenessProbe `gracePeriodSeconds` which if set overrides `terminationGracePeriodSeconds` for liveness termination
  * PRO: Avoids impacting users who want livenessProbes to shutdown according to terminationGracePeriodSeconds
  * CON: Any user with long grace period who hasn't yet noticed livenessProbes take forever to react stays broken until they notice (at the worst time, when their apps go down)
* Infer the maximum grace period for liveness from `num failures * probe period`, implying that a user with short liveness reaction wants a fast reaction from their pod
  * PRO: Any user unaware of the coupling reacts to liveness failures faster, normal pods (including reason 2 above) are less likely to be impacted
  * CON: If we later want to change the API to indicate this field, the default behavior makes less sense (i.e. complicates choosing the option above)
  * CON: A user with a long grace period who wants liveness to take more than tens of seconds (not sure why they would) suddenly sees that behavior impacted
  * CON: This sort of implicit calculation feels pretty arbitrary (we generally make defaults explicit vs calculated)
* Introduce a new toleration, similar to execute toleration for node not ready (how long the pod should be left on the node while unready before being evicted), that controls how long liveness tolerates
  * PRO: avoids API change
  * CON: basically a hack to avoid an API change, tolerations for execution don't really make sense for conditional stuff

**Comment by smarterclayton** [comment]
The scenario that triggered the reopen here was a a long outage reported by an ingress controller - the controller uses a 3600s grace period so that it can drain long requests from end user app traffic, but when the controller wedges it takes an hour to resolve, which is the worst outcome (the process wedges immediately, but kube has to wait the full hour to kill it).

**Comment by derekwaynecarr** [comment]
@unclewizard @smarterclayton i think having a separate termination period for liveness probe failures makes sense.  i think only backward compatible way to do it is a new field per option @smarterclayton enumerated.

**Comment by ehashman** [comment]
I agree that this option has the least likelihood of breaking things or unintended consequences:

> Introduce a new field to livenessProbe gracePeriodSeconds which if set overrides terminationGracePeriodSeconds for liveness termination 

I'll put together a short KEP for it.

**Comment by dchen1107** [comment]
@smarterclayton Thanks for the detail writeup. The issue was discussed at SIG Node in the past, and similar production issue like the ingress controller was reported before. If I remembered it correctly, the decoupling was rejected by API review due to the complexities (couldn't find the PRs / issues). To move forward for the production, we had to introduce some other per node maximum shutdown value, etc.

I agreed with you on the decoupling above.

**Comment by smarterclayton** [comment]
Thanks Dawn, will follow up with that.  I will put my terminationGracePeriod author hat on and say "I never intended this coupling!  I should have specified!".  Hopefully we can find the places where we were concerned and address it.
