### ISSUE TITLE
Deployment on Google cloud kubernetes

### ISSUE THREAD

**Issue by robinwu0411** [kubernetes/kubernetes#64764]
I'm trying to create a deployment on kubernetes cluster on google cloud via bitbucket pipelines. I have docker-compose file and use kompose to convert it to the format which can be run on kubernetes...and i'm trying to create it locally and send it to kubernetes cluster using TCP connection.....but I always got this error:
FATA Error while deploying application: Get http://localhost:8080/XXX: dial tcp [::1]:8080: getsockopt: connection refused 
....seems like the port 8080 is not opened on google cloud...i tried curl and telnet but neitherway, I was able to get access to this port or any other port except for 23(SSH)

Does any body know how to open this port?(I tried to add firewall rule for a ton of times but failed...), also what does 8080 here mean? does it relate to some port with kuberntes config file?
Thank you!

**Comment by dims** [comment]
Please re-post your question to [Stack Overflow](http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases.

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans Stack Overflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search Stack Overflow for answers to similar questions, and also familiarize yourself with:

[user documentation](http://kubernetes.io/docs/)
[troubleshooting guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/)
Again, thanks for using Kubernetes.

The Kubernetes Team

/close
