### ISSUE TITLE
kubectl pkcs11 smartcard support

### ISSUE THREAD

**Issue by jfrederickson** [kubernetes/kubernetes#64783]
IMO, it would be nice if kubectl was able to take advantage of x509 client certificates stored on an attached smartcard. When using client certs for user authentication, this keeps the private key (in theory) safe from exfiltration in the event of e.g. malicious browser extensions. For a client cert that potentially has admin access to a k8s cluster, this is very desirable.

This may be a long-term wishlist sort of thing as I don't believe Go's TLS library supports PKCS11 at the moment.

/kind feature

**Comment by forsberg** [comment]
I'm imagining this is something that could be implemented as an [authentication plugin](https://kubernetes.io/docs/reference/access-authn-authz/authentication/#client-go-credential-plugins) (new in K8S 1.11). 

To save on work, this plugin could talk to a GnuPG gpg-agent, that talks to a GPG-compatible smartcard, for example a Yubikey.

**Comment by jfrederickson** [comment]
While authentication plugins look useful, I'm not sure this is something that could be implemented that way. `kubectl` expects a cert and key when doing client cert auth, but it won't have the key in the case of a hardware token.

GPG is an option here, though it's not quite the same thing... I'm trying to think about what that auth flow would look like. (The auth plugin system seems to expect you to reach out to an external service for a token, but I feel like you'd want some sort of challenge-response system for pubkey auth.)

**Comment by forsberg** [comment]
Right, of course, the private part is on the hardware token - and stays there! I had some bad luck thinking there.. 

I'm imagining this could be implemented as a combination of an auth plugin and a serverside component, where the serverside component is listening for TLS requests from the plugin and returns a bearer token, which the API server can then verify. 

So something along the lines of:

1. Plugin gets call from kubectl to authenticate.
2. Plugin calls endpoint on cluster via TLS, with client authentication.
3. Endpoint on cluster generates Bearer token and stores its association with the CN of the client certificate used to authenticate. Bearer token is returned to kubectl auth plugin.
4. Kubectl sends bearer token to API server. 
5. API Server uses webhook token authentication to check Bearer token, and gets back the CN of the client (and possibly other information).

Quite complicated, so might be easier to just make kubectl understand PKCS11 directly.

**Comment by cristiklein** [comment]
We have been contracted to pick this issue up and implement it. Can someone please re-open the issue, assign it to me, and label it accordingly? Otherwise, should I open a new issue?

**Comment by cypherfox** [comment]
@cristiklein do plan to do this as an extension of `kubectl`, or extend the golang crypto lib to use an external crypt engine (as @jfrederickson )?
The latter would help solve so many other problems in one fell swoop. And I would assume that the technical difficulty is about on-par. 
That your contract may say something different or the politics of getting stuff in the golang library may make this harder I cannot fathom.

**Comment by cristiklein** [comment]
@cypherfox Thank you for your feedback.

Our contract stipulates that we are to do whatever is required to make the feature accepted upstream, of course, as cheap as possible. If extending `kubectl` is more acceptable then we do that, otherwise, if extending golang is the only way forward, then we do that.

Currently, we think using [crypto11](https://github.com/ThalesIgnite/crypto11), which has a `crypto.Signer` compatible interface is the easiest, and that would require rather small changes in `kubectl`, at the expense of pulling crypto11 as a dependency.

Note that, even if we extend golang, we likely need to change `kubectl` anyway. Putting something like a PKCS#11 URI inside the KeyData which is then passed to [X509KeyPair](https://golang.org/pkg/crypto/tls/#X509KeyPair) is unlikely to be accepted as a clean way to add PKCS#11 support in golang.

Let me know what you think?

**Comment by enj** [comment]
Feel free to add a discussion topic on to the [SIG Auth Agenda](https://docs.google.com/document/d/1woLGRoONE3EBVx-wTb4pvp4CI7tmLZ6lS26VTbosLKM).  I responded on slack as well.

**Comment by cristiklein** [comment]
@enj Thanks! In case you haven't received my request email, could you please allow cristian.klein@elastisys.com to edit the SIG Auth Agenda?

**Comment by cristiklein** [comment]
For the early adopters, please find a first draft here: https://github.com/elastisys/kubernetes/releases/tag/v1.18.0-alpha.2-pkcs11-alpha.1

Feedback from sig-auth:
- Pulling in PKCS#11 dependencies and forcing CGO on kubectl (as in the version above) is unacceptable for upstream inclusion.
- An `execCredentials`-like authentication plugin that delegates TLS client authentication to an external process is preferred. Note that, unlike the current `execCredentials` plugin, the new plugin would not return a token or a private key to `kubectl`, but would perform signing -- as required for TLS client authentication -- on behalf of `kubectl`.
- User storied need to be clarified, e.g., how does PIN entering / caching work.
- Check whether TLS session restart is performed by `kubectl` and document how to disable it. (The TLS session token is a credential that may defeat the purpose of PKCS#11 of not having any credentials in host memory.)
- Contribution seems large enough to warrant a KEP to receive feedback from a larger community.

Next steps:
- Write KEP

**Comment by neolit123** [comment]
i'd be curious to understand more about the benefits of the extension, compared to the alternative of having an external host (OS specific, hardware specific) tooling request short lived key/cert pairs from e.g. an YubiKey and writing those to a common path for kubectl to consume from a kubeconfig.

is the per-API request PIN authentication a requirement?

**Comment by mikedanese** [comment]
This needs some clear requirements:

* What are the specific compliance standards have requirements for this?
* What security guarantees do you hope to would achieve?

Other comments:

* The second factor achieved by touchid and yubi key touch policy is to establish physical user presence. I leave my yubikey in my computer but it's not useful unless I'm present to respond to a touch request. Touchid is permanently attached to my mac book and doesn't support a pin policy. As far as the threat model, if an attacker has some access to a machine they can read the certificate. Storing a kubikey pin in a kubeconfig improves that scenario by requiring an attacker to maintain physical presence on the machine to continue to authenticate as a compromised user. This feels weaker. However, if we require touch on every connection establishment, we normalize the act of touching the key which reduces the benefit (same reason why "Accept Cookie Policy" pops have been criticized by the community).
* The standard integration for authenticating end users in conjunction with hardward keys is to use FIDO as part of the login. Additionally, identity providers can only issue short term (e.g. 24 hour) credentials to force users to periodically authenticate. I do enable MFA on my github account but I don't need to interact with my hardware key every time I switch between pages.
* Since we are talking about mTLS, we need to consider resumption. TLS sessions carry an identity and having access to a [resumption_master_secret](https://tools.ietf.org/html/rfc8446#section-7.1) is equivalent to having access to the private key for a limited amount of time. Thus, the security guarantees can easily devolve to be equivalent or weaker to the FIDO on login + short lived credential approach. 
* The presented implementation exposes a crypto.PrivateKey which offers no way for an extension to control TLS handshake options. The boringssl split handshake model: https://boringssl-review.googlesource.com/c/boringssl/+/25387, give more control and flexibility to extensions and would, e.g. allow someone to implement SPIFFE based authentication where hostname validation is not compatible with crypto/tls, or to set specific TLS parameters like cipher suite, or experiment with random TLS extensions or...
* An approach that would work for both non-human client and server TLS auth would be ideal here.

**Comment by mikedanese** [comment]
Also the presentation to sig-auth was super awesome 👍 💯

**Comment by cristiklein** [comment]
Update on this issue, my college @jakubkrzywda has taken over and produced a [KEP](https://github.com/kubernetes/enhancements/pull/1749) to address the above feedback.

**Comment by liggitt** [comment]
hoisting from the [linked enhancement proposal](https://github.com/kubernetes/enhancements/pull/1749#issuecomment-755738311):

> Following discussion in the December 9th and January 6th sig-auth meetings, rather than adding APIs around external TLS signing, using a local proxy (kubectl -> local proxy -> apiserver) is preferred. This proxy could be configured globally via proxy envvars or per-cluster with the proxy-url field in a kubeconfig file. This would allow the proxy to use any method it desired to establish the TLS connection to the API server, as well as do any other desired transformations.
> 
> If there are gaps that would block doing this in a reasonable way (for example, supporting talking to a proxy over a unix domain socket), requests/proposals to address those specific gaps would be welcome.

/close

**Comment by piyifan123** [comment]
FWIW, https://medium.com/@piyifan123/use-yubikey-to-secure-kubernetes-authentication-client-cert-8978c04a2b90 is an example of the proposed local proxy strategy by using a Yubikey PIV slot to store the client certificate (and the private key).

Currently the example uses a localhost http connection from kubectl to the proxy which is not secure. Looking forward to the future discussion on "supporting talking to a proxy over a unix domain socket".

> hoisting from the [linked enhancement proposal](https://github.com/kubernetes/enhancements/pull/1749#issuecomment-755738311):
> 
> > Following discussion in the December 9th and January 6th sig-auth meetings, rather than adding APIs around external TLS signing, using a local proxy (kubectl -> local proxy -> apiserver) is preferred. This proxy could be configured globally via proxy envvars or per-cluster with the proxy-url field in a kubeconfig file. This would allow the proxy to use any method it desired to establish the TLS connection to the API server, as well as do any other desired transformations.
> > If there are gaps that would block doing this in a reasonable way (for example, supporting talking to a proxy over a unix domain socket), requests/proposals to address those specific gaps would be welcome.
> 
> /close

**Comment by cristiklein** [comment]
@piyifan123 Nice article, thanks for sharing! Indeed, the local proxy solution is less intrusive and works without changing `kubectl`. Would be cool to have this packaged as a [Krew](https://krew.sigs.k8s.io/).

**Comment by andsens** [comment]
Based on the work by @piyifan123 I have created [step-plugin-kmsproxy](https://github.com/orbit-online/step-plugin-kmsproxy). It's the same kind of reverse-proxy, but for keys that are available through [Smallstep](https://smallstep.com/) (including YubiKeys). In our org I have set it up using TPM and a half-hourly renewed certificate :-)

I created #131053 so we can proxy through unix domain sockets instead of TCP ports.

**Comment by salrashid123** [comment]
not that it works with kubectl, but here are two standalone samples of cert auth using a key on a TPM and one via softHSM

* [kubernetes_tpm_client](https://github.com/salrashid123/kubernetes_tpm_client)
* [kubernetes_pkcs11_client](https://github.com/salrashid123/kubernetes_pkcs11_client)

(its just a small api based sample; throughly unverified/reviewd)
