### ISSUE TITLE
Refactor volume.Attacher interface so that MountDevice is no longer coupled with Attach

### ISSUE THREAD

**Issue by davidz627** [kubernetes/kubernetes#64781]
Currently MountDevice and Attach are part of the same interface volume.Attacher. This means that any plugin implementing Attach MUST also implement MountDevice and vice versa. 

In practice this is not a strict requirement, there are use cases where you may want one or the other alone. Ideally you should be able to implement MountDevice without an Attach. Looking forward, these interfaces are also not coupled in CSI so this change would bring it more in line with the capabilities CSI supports.

We want to refactor MountDevice and related methods into a new seperate `LocalAttacher` interface.

/sig storage
/kind enhancement
/cc @saad-ali @jingxu97 @msau42 @verult

**Comment by msau42** [comment]
Is this related? https://github.com/kubernetes/community/pull/1683

**Comment by davidz627** [comment]
Ah I was unaware of this, it looks like a design that addresses this exact issue. Will see if we can get the work restarted on this after codefreeze

**Comment by msau42** [comment]
https://github.com/kubernetes/kubernetes/pull/66884 makes it so that you can implement MountDevice without Attacher.  However, it does not separate Attacher from MountDevice, as we couldn't find a use case for the other way around.  Also, it turns out, that the CSI Kubernetes plugin still has to implement the Attacher and MountDevice interfaces regardless of what the underlying driver supports.

**Comment by davidz627** [comment]
/close
due to @msau42 comment
