### ISSUE TITLE
The format of docker version is not so good

### ISSUE THREAD

**Issue by GodQ** [kubernetes/kubernetes#64863]
**What happened**:   
The format of docker client version is not so good
`$ docker version
Client:
 Version:       17.12.1-ce
 API version:   1.35
 Go version:    go1.9.4
 Git commit:    7390fc6
 **Built: Tue Feb 27 22:13:43 2018**
 OS/Arch:       linux/amd64

Server:
 Engine:
  Version:      17.12.1-ce
  API version:  1.35 (minimum version 1.12)
  Go version:   go1.9.4
  Git commit:   7390fc6
  Built:        Tue Feb 27 22:20:43 2018
  OS/Arch:      linux/amd64
  Experimental: false`

**What you expected to happen**:
This format should be consistent with server version

**Environment**:
- Kubernetes version (use `kubectl version`):    docker 17.12.1-ce in Minikube.iso
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): Minikube
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
Maybe it is a bug of docker

**Comment by jhorwit2** [comment]
@GodQ I notice you're using minikube, so in order to ensure your question gets answered in a timely manner please open this under that projects issue tracker: https://github.com/kubernetes/minikube/issues/

I'm fairly certain though this is a problem with docker itself and not of minikube, but i'm not familiar with their installation process to provide a definitive answer. 

/close
