### ISSUE TITLE
Access a specific pod from external

### ISSUE THREAD

**Issue by sqsw** [kubernetes/kubernetes#64876]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
 /kind feature

**What happened**:
We have an old service discovery system that requires process to register its ip:port during startup. On a kubernetes cluster, we exposed a service that enables NodePort. The processes within container can register to the old system with their Pod Ip:port + HostIp. 

For the clients within the same kubernetes cluster, they should be able to connect to the right process via specific Pod Ip:port. 

For an external client, it knows the HostIp+NodePort and the specific Pod Ip:port, so it can arrive the node via HostIP+NodePort, is there an efficient way to route the client’s request to the specific Pod giving the PodIP:port? Running a proxy on each node to route the traffic (nodeport -> pod) seems inefficient due to additional proxy layer (user space copy).

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by jhorwit2** [comment]
@sqsw How you may solve this is going to depend largely on your cluster setup. For example, if you're in a cloud that offers native routing to pod ips then this is easy, but if you're on baremetal you'll need to use something like flannel host-gw with routes setup on nodes that need to talk to pods. Another solution may be using anti-affinity to ensure only 1 pod is on a given host and use hostPort or local external traffic policy on a service so that the node port only goes to the local pod. 

Since this is a support question please re-post your question to [Stack Overflow](http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support
are posted so that we can improve our efficiency in responding to your requests,
and to make it easier for you to find answers to frequently asked questions and
how to address common use cases.

We regularly see messages posted in multiple forums, with the full response
thread only in one place or, worse, spread across multiple forums. Also, the
large volume of support issues on github is making it difficult for us to use
issues to identify real bugs.

Members of the Kubernetes community use Stack Overflow to field support
requests. Before posting a new question, please search Stack Overflow for answers 
to similar questions, and also familiarize yourself with:

  * [user documentation](http://kubernetes.io/docs/)
  * [troubleshooting guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/)

Again, thanks for using Kubernetes!

/kind support
/close
