### ISSUE TITLE
Needs about 10s time to schedule a pod 

### ISSUE THREAD

**Issue by wenlxie** [kubernetes/kubernetes#64908]
> /kind bug

**What happened**:
our cluster has about 10k pods and 1k nodes 
When I try to create 200 pods , which is in the same namespace and all have inter-pod anti-affinity rules.
That namespace already have 1.5k pods, which have inter-pod anti-affinity rules too. 
Then i found that it takes about 10 seconds to schedule 1 pod.
So some pods need to wait 30 minutes to be scheduled

**What you expected to happen**:
Need to schedule the pod more quickly

**How to reproduce it (as minimally and precisely as possible)**:
Create pod large scale with inter-pod affinity rules

**Anything else we need to know?**:
I try to do some debug.
Dump the scheduler's stack

I can see the PodAffinityChecker predicate is acquiring locks
```
goroutine 9029790 [semacquire]:
sync.runtime_SemacquireMutex(0xc42040c61c)
    /usr/local/go/src/runtime/sema.go:62 +0x34
sync.(*Mutex).Lock(0xc42040c618)
    /usr/local/go/src/sync/mutex.go:87 +0x9d
k8s.io/kubernetes/plugin/pkg/scheduler/schedulercache.(*schedulerCache).FilteredList(0xc42040c600, 0xc4536dc3b0, 0x23621c0, 0xc4308adaa0, 0x0, 0x0, 0x0, 0x0, 0x0)
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/plugin/pkg/scheduler/schedulercache/cache.go:102 +0x8a
k8s.io/kubernetes/plugin/pkg/scheduler/algorithm/predicates.(*PodAffinityChecker).satisfiesPodsAffinityAntiAffinity(0xc4204a5d40, 0xc4485e2380, 0xc43a1098c0, 0xc44f227d60, 0xc43a1098c0)
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/plugin/pkg/scheduler/algorithm/predicates/predicates.go:1228 +0x161
k8s.io/kubernetes/plugin/pkg/scheduler/algorithm/predicates.(*PodAffinityChecker).InterPodAffinityMatches(0xc4204a5d40, 0xc4485e2380, 0x23526e0, 0xc441046960, 0xc43a1098c0, 0xc42016ec28, 0x0, 0xc4202749c0, 0xc42016ec20, 0x23c6fb0, ...)
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/plugin/pkg/scheduler/algorithm/predicates/predicates.go:1003 +0xe8
k8s.io/kubernetes/plugin/pkg/scheduler/algorithm/predicates.(*PodAffinityChecker).InterPodAffinityMatches-fm(0xc4485e2380, 0x23526e0, 0xc441046960, 0xc43a1098c0, 0xc449f23501, 0x0, 0x0, 0x0, 0x0, 0x0)
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/plugin/pkg/scheduler/algorithm/predicates/predicates.go:983 +0x59
k8s.io/kubernetes/plugin/pkg/scheduler/core.podFitsOnNode(0xc4485e2380, 0x23526e0, 0xc441046960, 0xc43a1098c0, 0xc4202749c0, 0x0, 0x8, 0x0, 0xc441afbf40, 0x404bf5, ...)
```
Then there are many other go routine are also acquiring the locks.

From the cache.go https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/cache/cache.go

Many method need to acquire the lock, especially like updatePod and updateNode, which happens very frequently.

**Environment**:
We are using  k8s 1.8  and centos 3.10

**Comment by wenlxie** [comment]
@k82cn @liggitt  PTAL

**Comment by CaoShuFeng** [comment]
Will multi-scheduler help?

https://kubernetes.io/docs/tasks/administer-cluster/configure-multiple-schedulers/

**Comment by wgliang** [comment]
@wenlxie 
We can speed up the read operation by the concurrent read feature of sync.RWMutex. If you have test environment, please checkout the #64910 code.

**Comment by k82cn** [comment]
Would you have chance to try this https://github.com/kubernetes/kubernetes/pull/62211 :)

**Comment by ravisantoshgudimetla** [comment]
@wenlxie - Thanks for raising the issue. I have some questions here.

- What are the specs of machine that is running scheduler?
- Is the cluster setup in HA mode?
- What about pods without affinity rules, what is scheduling latency for them?
- I think we need some more logs before could jump to conclusion. How are we sure that lock acquisition is the culprit here. If you could do some profiling and provide data, it would be helpful for further debugging.

@wgliang - While I am sure that RWMutex is better than sync.Mutex for concurrent reads, I think in case of add and update we need to wait on writes. Another point to note is RWMutexes are not known to scale well(https://github.com/golang/go/issues/17973).

**Comment by wenlxie** [comment]
https://github.com/kubernetes/kubernetes/pull/65714

**Comment by resouer** [comment]
@wenlxie  #65714 is used to improve equivalence class cache, not scheduler cache. The scheduler cache does not hold global lock in scheduling path AFAIK.

While #65714 does improve cache performance to some extend, but if it's really caused by lock contention there, I will assume the problem won't be fixed.

Also, would be great if provided with your cluster spec and if any alpha feature is enabled.

**Comment by wenlxie** [comment]
@ravisantoshgudimetla No, we didn't enable it.

@resouer  Sorry, not take full look of that PR.
But #65714 changes the scheduler cache's lock to RW Lock. 
I think the performance will be improved.
For our cluster(k8s 1.9), we just enable feature:
```
--feature-gates=BlockVolume=true,PersistentLocalVolumes=true,ExperimentalCriticalPodAnnotation=true,VolumeScheduling=true
```

We will start to do more analyze this issue next month. 
I will paste the full result here.
