### ISSUE TITLE
Creating Config Map from a configuration file available in a running pod

### ISSUE THREAD

**Issue by tutaidalal** [kubernetes/kubernetes#64958]
I have a application which run in each 1 hours. In case any changes in the configuration i just want to create a config map from existing configuration and then do the changes and apply the configuration to the running pod without restarting the pod.. is it possible ?

My Application wakeup in each 1 hour and then read configuration from a local file.

Example : /opt/myapplication/application.properties.

What is the way to create a configMap from the file available in /opt/myapplication/application.properties in the running pod?

And how I can chnage the config and apply so that the  /opt/myapplication/application.properties will have the latest config and on the next wakeup the process will able to get the latest data.

Note: I dont want to restart the pod.

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:05:37Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

**Comment by dims** [comment]
Please re-post your question to [Stack Overflow](http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases.

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans Stack Overflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search Stack Overflow for answers to similar questions, and also familiarize yourself with:

[user documentation](http://kubernetes.io/docs/)
[troubleshooting guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/)
Again, thanks for using Kubernetes.

The Kubernetes Team

/close
