### ISSUE TITLE
@kubernetes/sig-testing-misc kube-dns getting  CrashLoopBackOff 

### ISSUE THREAD

**Issue by SHUFIL** [kubernetes/kubernetes#65007]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> kind bug
> /kind feature

**What happened**:

**What you expected to happen**:
I have installed kubernetes, and Docker, removed swap , disabled firewall, then i build up the kubernetes master using kubeadm init --pod-network-cidr 10.10.10.0/16
#kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml

#kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/k8s-manifests/kube-flannel-rbac.yml
Then added node system sudo kubeadm join --token a2d.. etc
currently showing server and node correctly using kubectl get nodes
But the same i getting error kube-dns   CrashLoopBackOff  - kubectl get pods --all-namespaces, i have chked the syslog , i got below error message 
###"Jun 12 12:46:57 server kubelet[17532]: W0612 12:46:57.349698   17532 cni.go:171] Unable to update cni config: No valid networks found in /etc/cni/net.d
Jun 12 12:47:02 server kubelet[17532]: W0612 12:47:02.352133   17532 cni.go:113] Error loading CNI config list file /etc/cni/net.d/10-flannel.conflist: error parsing configuration list: no 'plugins' key"
##

**How to reproduce it (as minimally and precisely as possible)**:
I have installed kubernetes, and Docker, removed swap , disabled firewall, then i build up the server
kubeadm init --pod-network-cidr 10.10.10.0/16
#kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml

#kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/k8s-manifests/kube-flannel-rbac.yml
Then added node system sudo kubeadm join --token a2d.. etc
currently showing server and node correctly using kubectl get nodes
But the same i getting error kube-dns   CrashLoopBackOff  - kubectl get pods --all-namespaces, i have chked the syslog , i got below error message 
###"Jun 12 12:46:57 server kubelet[17532]: W0612 12:46:57.349698   17532 cni.go:171] Unable to update cni config: No valid networks found in /etc/cni/net.d
Jun 12 12:47:02 server kubelet[17532]: W0612 12:47:02.352133   17532 cni.go:113] Error loading CNI config list file /etc/cni/net.d/10-flannel.conflist: error parsing configuration list: no 'plugins' key"
##

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):v1.10.4
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):"Ubuntu 16.04.3 LTS"
- Kernel (e.g. `uname -a`):Linux server 4.13.0-43-generic #48~16.04.1-Ubuntu SMP Thu May 17 12:56:46 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

- Install tools: kubernetes , Docker only
- Others:nothing
@kubernetes/sig-testing-misc

**Comment by SHUFIL** [comment]
@kubernetes/sig-testing-misc

**Comment by SHUFIL** [comment]
/remove-sig testing
/sig cluster-lifecycle
kind bug

**Comment by SHUFIL** [comment]
Hi,

I have updated same in   kubernetes/test-infra
<https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:>

https://github.com/kubernetes/test-infra/issues/8334

**Comment by cblecker** [comment]
Please re-post your question to [Stack Overflow](http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases.

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans Stack Overflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search Stack Overflow for answers to similar questions, and also familiarize yourself with:

  * [user documentation](http://kubernetes.io/docs/)
  * [troubleshooting guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/)

Again, thanks for using Kubernetes.

The Kubernetes Team

---
/triage support
/close

**Comment by rafis** [comment]
Any solution?
