### ISSUE TITLE
Istio shouldn't use :latest

### ISSUE THREAD

**Issue by destijl** [kubernetes/kubernetes#65160]
This commit and another subsequent one:
https://github.com/kubernetes/kubernetes/commit/30714148c894a8daf539138c67a9be77a6fb6fc8#diff-ff2c2410a27bca372a9d79aacb8ac837R2593

introduced some istio containers that depend on the :latest tag.

We can't depend on latest tags and have a stable production infrastructure. It needs to be a specific version tag. Please tag a specific version.

/kind bug

**Comment by destijl** [comment]
@ostromart

**Comment by destijl** [comment]
Code is here:
https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/istio/noauth/istio.yaml

**Comment by liggitt** [comment]
/assign @ostromart @mikedanese 

does this need to be resolved before 1.11 release?

**Comment by ostromart** [comment]
No it doesn't. We would like to mirror OSS Istio behavior as much as possible, this issue will be addressed in the next release (1.0).

**Comment by ostromart** [comment]
The config is used only for Istio on GKE (https://sites.google.com/corp/google.com/istio/programs/istio-for-gke) which is going to be label controlled in GKE to be for alpha customers.
Issue is being tracked here and should make it into the next release (1.0): https://github.com/istio/istio/issues/6400.
Is it reasonable to keep this here until new addon manager is in place?

**Comment by tallclair** [comment]
As far as the scanner is concerned, latest is just another tag that can be scanned. Typically latest will also correspond with a versioned tag that gets scanned. However, we don't expect tags to change a lot, so tracking whether the issue is patched is harder. Similarly, it is very hard to tell whether the version running in a cluster is patched when tagged with latest, since even if ":latest" is patched, that isn't necessary the actual image that's running.

**Comment by mikedanese** [comment]
:latest also makes rolling updates of deployments and daemonsets with the addon manager difficult because a hash of the podspec needs to change. Usually that's the image tag. I'll defer to @destijl to make a decision.

**Comment by liggitt** [comment]
fixed in https://github.com/kubernetes/kubernetes/pull/65381

/close
