### ISSUE TITLE
Add a 'kind/test' category for release milestone PRs

### ISSUE THREAD

**Issue by shyamjvs** [kubernetes/kubernetes#65180]
I've created/reviewed multiple changes around code freeze that purely touch test code or testing framework. The convention fmu is that we need `kind/X` label as a precondition for milestone PRs to be merged, where allowed X values are bug/feature/cleanup. IMO there should be another category for 'test' (which often doesn't fall into any of earlier categories). It'll make flagging/explaining such changes to release team easier.

cc @kubernetes/sig-release-feature-requests @kubernetes/test-infra-maintainers

**Comment by BenTheElder** [comment]
@jberkus @cblecker

**Comment by cblecker** [comment]
@shyamjvs Do you have an example of such a PR that would not be considered a feature, cleanup, design, documentation, or bug?

**Comment by shyamjvs** [comment]
Yes. Couple e.gs I could recollect from recent past (I'm sure there are more):

- https://github.com/kubernetes/kubernetes/pull/64768
- https://github.com/kubernetes/kubernetes/pull/64521

**Comment by shyamjvs** [comment]
Another example - https://github.com/kubernetes/kubernetes/pull/65179

**Comment by nikhita** [comment]
maybe nitpicking: would PRs which fix bugs and add features but have tests need to be labelled with `kind/test`?

**Comment by jberkus** [comment]
/remove-lifecycle stale

Since kind/failing-test now exists as a label, it seems like we should add it to tide to accept PRs during code freeze with that label for 1.13.

@AishSundar ?

**Comment by nikhita** [comment]
/reopen

This came up again on slack: https://kubernetes.slack.com/archives/C2C40FMNF/p1558084193313400

@sttts can you add an example of such a PR here?

**Comment by sttts** [comment]
Here is an example: https://github.com/kubernetes/kubernetes/pull/77756

We have had a couple of them recently while working towards graduating APIs: pure test coverage PRs.

**Comment by cblecker** [comment]
@spiffxp Thoughts on this? IIRC you had opinions on `kind/*` labels

**Comment by nzoueidi** [comment]
Do we still need this? I might work on it..

**Comment by BenTheElder** [comment]
another PR like https://github.com/kubernetes/kubernetes/issues/65180#issuecomment-493385520 just brought this issue back up. I went with `kind/feature` for now but imho `kind/test` makes a little more sense ...

**Comment by justaugustus** [comment]
I'm in favor of this.

/sig testing
/priority important-soon
/milestone v1.16
/help

**Comment by spiffxp** [comment]
I pushed us to [the magic number of 7 +/- 2](https://en.wikipedia.org/wiki/The_Magical_Number_Seven,_Plus_or_Minus_Two) `kind/` labels so we could avoid an intimidating list of label choices at our contributors.  We are at 8, we could add one more to stay within those bounds.  But why do we need this?

We no longer gate PR's based on the presence of specific kind labels, so I question whether the original ask is still relevant.  What does the release team need here?  How will `kind/test` differ from `area/test`?  Would `kind/cleanup area/test` describe "improving test coverage"?

**Comment by spiffxp** [comment]
FWIW, the `kind/` labels used across all repos (shoutouts to the dog emoji)
```
   1 kind/cluster-api-vsphere
   1 kind/clusterctl
   1 kind/discuss
   1 kind/gray-area
   1 kind/kanarynetes 🐦
   1 kind/kep
   1 kind/libs
   1 kind/mesos-flake
   1 kind/meta
   1 kind/proposal
   1 kind/refactor
   1 kind/repository-infra
   1 kind/security
   1 kind/tracking-issue
   1 kind/umbrella
   1 kind/ux
   1 kind/velocity-improvement
   1 kind/versioning
   1 kind/🐶
   2 kind/postmortem
   2 kind/regression
   2 kind/release
   2 kind/testing
   3 kind/test
   4 kind/question
 182 kind/api-change
 182 kind/bug
 182 kind/cleanup
 182 kind/design
 182 kind/documentation
 182 kind/failing-test
 182 kind/feature
 182 kind/flake
```

The number of repos that happen to have a `kind/test` or `kind/testing` on their own doesn't convince me this is a large pain point
```
kubernetes-sigs/gcp-compute-persistent-disk-csi-driver
kubernetes-sigs/azurefile-csi-driver
kubernetes-sigs/azuredisk-csi-driver
kubernetes/cloud-provider-azure
kubernetes/kompose
```

Same feeling when I look at labels that have the word "test" in them
```
   1 area/kubetest
   1 area/testgrid
   1 team/test-infra
   1 test-infra
   1 tests-missing
   1 type/code-test-coverage
   2 kind/testing
   2 reviewed/needs tests
   2 test
   2 testing
   3 area/e2e-test-framework
   3 kind/test
   4 area/test-infra
   5 area/test
   7 area/testing
 182 kind/failing-test
 182 needs-ok-to-test
 182 ok-to-test
 182 sig/testing
```

**Comment by nikhita** [comment]
/remove-help 

I believe this still need consensus

**Comment by cpanato** [comment]
ok, i will try to get this issue
first need to know:
- do we all agree to add the new label or is not a label? and that will be `kind/test`? i
- if yes what is the process to create that, can someone point the repo or similar pr?

/cc @nikhita @spiffxp @tpepper @justaugustus

**Comment by spiffxp** [comment]
I feel like my questions above remain unanswered.
- The original ask is no longer relevant since we no longer gate on the presence of specific `kind/` labels, so what is the ask?
- What does the release team need here?
- How will `kind/test` differ from `area/test`?
- Would `kind/cleanup area/test` describe "improving test coverage"?

**Comment by cpanato** [comment]
Ok so, I need to know who has the domain knowledge/decision for that and to clarify the questions above

**Comment by jberkus** [comment]
So, the one reason I could see having a more concrete "this PR affects testgrid/test-coverage" label is that we've wanted to implement at "test freeze" during code freeze for a while.  

However, I'm not convinced that a kind/ label does that any better than the current area/ labels do.  Many contributors would still use kind/bug or king/cleanup for text fixes, because they'd ignore the new label.

It would also break the existing conceptual division between kind and area.  Currently, kind refers to "what kind of change this is" and area refers to "what has been changed".  So even if new labels are needed, it seems like they should be area/ labels, not kind/.

**Comment by liggitt** [comment]
this is not release blocking

**Comment by tpepper** [comment]
/kind 🐶

This issue is really dogging us.

From my perspective I feel we already have kind and area labels which cover the general situation for the type of patches discussed.  We also have these comment chains in PRs on GitHub.  A PR submitter should be fully justifying their commits and PR here, regardless of the labels (which are more about triage imho).  I don't see us using a "kind/test" or "kind/cleanup" giving clear signal to a reviewer that a PR would be simple and safe to always merge quickly.

**Comment by andrewsykim** [comment]
Bumping this old thread, I agree with @spiffxp that a `kind/testing` label is not really needed if we don't gate PRs without a kind label. But I think today we still require PRs to have a kind label? 

I personally have encountered many PRs that are just adding more tests, it's less so an issue around signal and more so that it's awkward to label them as either `kind/cleanup` or `kind/feature` when it's not doing either.
