### ISSUE TITLE
the addon fluentd-elasticsearch could not collect log data

### ISSUE THREAD

**Issue by jiuchongxiao** [kubernetes/kubernetes#65210]
the addon fluentd-elasticsearch could collect log,why?
![image](https://user-images.githubusercontent.com/13093730/41590913-cde78e78-73ea-11e8-9ca9-dab19818ee5d.png)

the Index Patterns (logstash-* and *) all no have result show  after i run myowner test kubernetes example.

**version**
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-12T14:14:26Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

**Comment by coffeepac** [comment]
@jiuchongxiao the plugin will load data in time order so if the cluster has been running for awhile, it may take an hour or two for data to show up for the last 15 minutes.

I've seen another issue from you about log data, can I assume that this issue is resolved?

**Comment by aleks-mariusz** [comment]
i have this issue too.. i believe this is because recent versions of docker use systemd (and journald) to store logs, but the way fluentd is configured it wants *.log files in /var/log/containers, none of which exist on my system:

here's my setup:
centos 7.5
kubernetes (kubeadm/kubectl/kubelet/etc) v1.11.2
docker 1.13.1

so fluentd cannot find any container data to send to elastic search :-(

**Comment by coffeepac** [comment]
@aleks-mariusz this issue has been closed as resolved.  if you are experiencing these symptoms and simply waiting for a few minutes doesn't resolve the issue (i don't think it will, but that's the fix for this issue) please open a new issue with your information.

I have some ideas but I'd like to address them in its own issue so its more easily discoverable by others.  feel free to assign me and add sig-instrumentation
