### ISSUE TITLE
scheduler: fix API inconsistencies and test compatibility

### ISSUE THREAD

**Issue by nikhita** [kubernetes/kubernetes#65414]
/kind bug
/sig scheduling

There are many APIs which have been excluded in https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/algorithmprovider/defaults/compatibility_test.go. For instance, `ExtenderConfig` is absent (found during https://github.com/kubernetes/kubernetes/issues/65413).

The tests should include all API types to ensure backward compatibility and API consistency. 

/cc @liggitt

**Comment by liggitt** [comment]
some of the problems noted:
* BindVerb omits a json tag, so requires "BindVerb" when using a case-sensitive decoder
* Uses time.Duration, which requires specifying times as 1000000000 to get 1 second (should have used metav1.Duration, which allows specifying "1s")
* Uses restclient.Config, which is not a serializable struct (has no json tags, carries no guarantee it will remain compatible with data serialized from it in a previous release)

**Comment by liggitt** [comment]
Opened #65415 (and [1.11](https://github.com/kubernetes/kubernetes/pull/65416), [1.10](https://github.com/kubernetes/kubernetes/pull/65417), [1.9](https://github.com/kubernetes/kubernetes/pull/65418), and [1.8](https://github.com/kubernetes/kubernetes/pull/65419) cherry-picks) to continue decoding this particular config struct in a case-insensitive way to preserve current behavior while this issue is resolved

**Comment by liggitt** [comment]
/priority important-soon

this should be addressed immediately. the lack of rest.Config cross-version serialization safety is especially concerning

**Comment by resouer** [comment]
Thanks @nikhita 

also, cc the user of scheduler extender I knew: @ravigadde

**Comment by ravigadde** [comment]
Thanks @resouer @liggitt Is there a precedence for breaking API changes like these on the callouts? Any suggestion for how to handle this?

@liggitt Do you have an alternate suggestion for an existing TLS Config struct or it could be defined here with json tags?

**Comment by liggitt** [comment]
> Thanks @resouer @liggitt Is there a precedence for breaking API changes like these on the callouts? Any suggestion for how to handle this?

There aren't great options for fixing the inconsistencies since they've been released. The targeted change in https://github.com/kubernetes/kubernetes/pull/65424 lets you document/use "normal" case keys in the scheduler config JSON, only because it makes that one struct continue to be case-insensitive.

> @liggitt Do you have an alternate suggestion for an existing TLS Config struct or it could be defined here with json tags?

I'd recommend copying the struct into the scheduler types as-is to insulate you from changes to the rest.TLSClientConfig struct, and copy the values from the scheduler config struct into a rest.TLSClientConfig struct when instantiating

**Comment by nikhita** [comment]
/remove-lifecycle stale

PR open.

**Comment by alculquicondor** [comment]
/open

Perhaps it's time to solve this in component config v1beta1. But we need to keep supporting both deserialization methods once we graduate to v1.

cc @pancernik I think we can start by just duplicating the Extender types in v1beta1 folder.

**Comment by alculquicondor** [comment]
It looks like we only need to do 2 things, after copying the type into v1beta1 folder:

- [ ] Remove the special decoding https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/kube-scheduler/config/v1/types.go#L232-L242
- [ ] Change HTTPTimeout to metav1.Duration
