### ISSUE TITLE
Populate env file from pod filesystem

### ISSUE THREAD

**Issue by jeusdi** [kubernetes/kubernetes#65438]
Guess the next situation.

 1. An Init Container creates an env file into pod filesystem.
 2. The other containers in the pod, need this file content to propagate its content as environment variables.

How could I propagate this file content as environment variables?

**Comment by jeusdi** [comment]
All of them, init and main containers shares the same volume mount.
So, init container creates the env file into /etc/secrets which is mounted on a volume. The same volume is mounted on main containers.

So, all of them, have access to the same content.

The problem is, how to populate this content file in order to populate as environment variables and main container are able to use them?

I don't know if I'm able to explain so well...

**Comment by CaoShuFeng** [comment]
> how to populate this content file in order to populate as environment variables and main container are able to use them?

Looks like this is not a k8s question.
```
$ cat env.sh 
export key=value
$ source env.sh
$ echo $key
value
$ run your app
```

**Comment by jhorwit2** [comment]
As CaoShuFeng has mentioned, you can source the file in the container. You can share the file via an empty dir volume that the init container and main container share. 

If you feel this doesn't satisfy your needs please re-post your question to [Stack Overflow](http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support
are posted so that we can improve our efficiency in responding to your requests,
and to make it easier for you to find answers to frequently asked questions and
how to address common use cases.

We regularly see messages posted in multiple forums, with the full response
thread only in one place or, worse, spread across multiple forums. Also, the
large volume of support issues on github is making it difficult for us to use
issues to identify real bugs.

Members of the Kubernetes community use Stack Overflow to field support
requests. Before posting a new question, please search Stack Overflow for answers 
to similar questions, and also familiarize yourself with:

  * [user documentation](http://kubernetes.io/docs/)
  * [troubleshooting guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/)

Again, thanks for using Kubernetes.

The Kubernetes Team
