### ISSUE TITLE
Containerized kubelet may not see local volume block device paths

### ISSUE THREAD

**Issue by wongma7** [kubernetes/kubernetes#65445]
/kind bug
Using https://github.com/kubernetes-incubator/external-storage/tree/master/local-volume, if a block device is symlinked to the discovery directory e.g. `/mnt/local-storage/block-devices`, then MapVolume will fail with 
`volume_path_handler_linux.go:75] Failed device create command for path: /mnt/local-storage/block-devices/vdb exit status 1 losetup: /mnt/local-storage/block-devices/vdb: failed to set up loop device: No such file or directory` since the containerized kubelet cannot see the path on host.

`/dev` is mounted by containerized kubelet, so if before we try to map the device we set devicePath to the evaluation of symlink `/mnt/local-storage/block-devices/vdb` and end up with a devicePath of `/dev/*`, containerized kubelet will see the device and successfully map the device. Are there any issues with this solution? This is on Kubernetes 1.10
@msau42 @???

**Comment by msau42** [comment]
ah yes containerized kubelet has many issues when dealing with symlinks.  Check out Mounter.GetMode(), it calls a nsenter EvalSymlinks which should be able to do what you need.  But actually, one thing to consider, is do you need to do the losetup on the host, or does inside the container work?

**Comment by wongma7** [comment]
Yes it appears to work from inside the container, on the host I run
```
$ losetup -a
/dev/loop0: [0005]:172323 (/dev/vdb)
```
which disappears after I delete the pod using the device. My understanding of running losetup in MapVolume is not that great but I suppose that as long as that /dev/loop0 is created we are fine.
Thanks for the quick response, I'll create a PR using that function and tag you

**Comment by msau42** [comment]
Does it create it on the host or in the containerized kubelet? What happens when containerized kubelet is restarted?

The purpose of losetup is to do "refcounting" on the block device to prevent possible naming collisions when devices are attached/detached under unhealthy conditions.  Ie, if a device showed up as /dev/sdb and you gave that to a pod, and then for some reason it become unhealthy and disappeared (while the pod is still running), another device (maybe even another volume type) could get attached to the node and reuse /dev/sdb.  Now the pod has access to a device it's not supposed to.

With filesystem volumes, the refcounting is done with mount points, but for block device, loopback is the equivalent.

**Comment by wongma7** [comment]
It is created on the host (and also visible in the container), and stays around through restart.

I understand now, thank you.

**Comment by wongma7** [comment]
Actually after I restart it becomes /vdb instead of /dev/vdb in the losetup output, idk what that is about.
```
$ losetup -a
/dev/loop0: [0005]:172323 (/vdb)
```
There is no such thing as /vdb and /dev/vdb is still intact of course. Seems inconsequential since it is disappearing after all pods using the device are deleted, i.e. it's still serving as a refcounter
