### ISSUE TITLE
rpc error: code = 14 desc = grpc: the connection is unavailable

### ISSUE THREAD

**Issue by anupam4881** [kubernetes/kubernetes#65464]
**Environment**:  Details 
- Kubernetes version (use `kubectl version`): [root@TPSERVER168 ~]# kubectl version 
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:05:37Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
[root@TPSERVER168 ~]# 

- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): [root@TPSERVER168 ~]# cat /etc/redhat-release 
CentOS Linux release 7.5.1804 (Core) 
- Kernel (e.g. `uname -a`): [root@TPSERVER168 ~]# uname -a
Linux TPSERVER168 3.10.0-693.17.1.el7.bug14347.centos.plus.x86_64 #1 SMP Tue Feb 6 16:27:03 PST 2018 x86_64 x86_64 x86_64 GNU/Linux

- Install tools: [root@TPSERVER168 ~]# kubeadm version 
kubeadm version: &version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:05:37Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
[root@TPSERVER168 ~]# 

- Others:

Hi Team , 

We are getting   grpc daily two three times  error and every time we have to restart the docker demon and all pods again to restore  the services back , this error is very frequent and we are not sure that above error is bug of kubernetes or docker , kindly provide some workaround else we will be on big trouble for us. 

Thanks in advance & waiting for sore help. 

Regards
Anupam Narayan

**Comment by nikhita** [comment]
> We are getting grpc daily two three times error and every time we have to restart the docker demon and all pods again to restore the services back , this error is very frequent and we are not sure that above error is bug of kubernetes or docker , kindly provide some workaround else we will be on big trouble for us.

@anupam4881 Can you elaborate on what you did which made you get this error? Is there a way to reproduce this?

**Comment by anupam4881** [comment]
Unfortunately no. 

but we observed that it normally happen during deployment or restart during image set process  . When it comes we need to restart docker services to resume services.   There is no any fix step to reproduce. 

Regards
Anupam

**Comment by anupam4881** [comment]
Is there any update on same ? , today again we are getting  same error, if you need any log for diagnose kindly let me know . 

Regards
Anupam

**Comment by anupam4881** [comment]
Dear Team,

any help will he appreciate, during deployment we are getting this error some time also during creation of new services.

**Comment by nikhita** [comment]
@anupam4881 This doesn't look like a Kubernetes bug. Please re-post your question to [Stack Overflow]
(http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support
are posted so that we can improve our efficiency in responding to your requests,
and to make it easier for you to find answers to frequently asked questions and
how to address common use cases.

We regularly see messages posted in multiple forums, with the full response
thread only in one place or, worse, spread across multiple forums. Also, the
large volume of support issues on github is making it difficult for us to use
issues to identify real bugs.

Members of the Kubernetes community use Stack Overflow to field support
requests. Before posting a new question, please search Stack Overflow for answers 
to similar questions, and also familiarize yourself with:

  * [user documentation](https://kubernetes.io/docs/home/)
  * [troubleshooting guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/)

Again, thanks for using Kubernetes.

The Kubernetes Team

/close
