### ISSUE TITLE
Add support for namespace-local CRD

### ISSUE THREAD

**Issue by nicolaferraro** [kubernetes/kubernetes#65551]
/kind feature

Custom Resource Definitions are currently cluster-wide objects, so users need cluster-level authorizations to create them.

But current trend is to use CRDs in combination with "Operators" to perform management of complex applications inside a namespace.
CRDs used in this context should be namespaced, as namespaced are the applications they describe.

I think Kubernetes shoud allow creation of CRDs that exist only inside a namespace and for this reason can be created by users without cluster-level authorizations.

**Comment by liggitt** [comment]
> I think Kubernetes shoud allow creation of CRDs that exist only inside a namespace and for this reason can be created by users without cluster-level authorizations.

While the desire is understandable, I think this is unlikely to happen any time soon, for many reasons:
* the intent behind CRDs was to allow for dynamically defined resource types that behaved as much as possible like standard kubernetes resources. Operations like `kubectl get <namespaced-type> --all-namespaces` would be nonsensical if a type was non-homogenous or non-existent across namespaces
* Discovery documents are cluster wide and scale with the number of types defined. This would make them scale by the number of namespaces times the number of types
* controllers responsible for enforcing standard resource behavior like garbage collection would have to maintain many more watches, since they would be per-namespace, per-type
* group/version/kind would no longer fully qualify a type, since the schema could depend on which namespace you were submitting the object to
* CRDs avoid resource name conflicts by making their name match the fully-qualified resource.version.group they specify. This would allow a cluster scoped and namespaced CRD to both attempt to define the same resource.

**Comment by nikhita** [comment]
Closing this issue because we probably won't get to this anytime soon. If this is ever decided to get done, let's reopen/open a new issue with the approach in mind.

/close

**Comment by shinebayar-g** [comment]
Any updates on namespace scope CRDs?

**Comment by lavalamp** [comment]
It's still very, very unlikely to ever happen.

**Comment by shinebayar-g** [comment]
I see.. That's rather unfortunate. Now I'm wondering how folks managing multiple versions of CRDs in a same cluster.

**Comment by YevheniiPokhvalii** [comment]
The problem with CRD is that they are **Custom** Resource Definitions. They are not like, for example `pods` API resource definition that is managed centrally by the Kubernetes team. They are managed by third party developers, that means it can lead to some problems like API resource name coincidence on the cluster, or, for instance, developers updated their CRDs but did not update their versions and it broke compatibility with the old application versions on the cluster when multiple application versions are installed in different namespaces - some sort of a shared cluster. Some technicians do not have permissions to install CRDs on a cluster and only have access to a namespace - that's another example.
I think the Kubernetes team need to find some workaround if they don't want to implement namespaced CRDs.

**Comment by FabianKramm** [comment]
A currently working workaround/alternative for this problem can be [virtual clusters](https://kubernetes.io/docs/concepts/security/multi-tenancy/#virtual-control-plane-per-tenant) that essentially deploy a mini control plane inside another cluster and reuse the computing and networking of the "host" cluster to emulate a separate cluster. Within the virtual cluster you can then install your own custom CRDs or operators and use those independently from the CRDs in the host cluster.

**Comment by mogul** [comment]
Thanks for mentioning that! I'm kind of agog that it has not been mentioned previously. Going to take a look at loft.sh's implementation now.

**Comment by caniko** [comment]
+1
