### ISSUE TITLE
Complete atomic update code for all objects and create

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#656]
In order to allow optimistic concurrency in the face of edits, the apiserver, storage layers, and the registries should support at a minimum:
- Return an opaque value with each resource that corresponds to its modification state via the API
  - For simplicity, the etcd modification index
  - As an Etag?  Or as a value in the object?
- Allow clients to pass the opaque modification value back to the apiserver on PUT and down into the storage/registry layer
  - As If-Match?  Or as a value in the object on PUT?
  - Return 409 on conflict detection
  - If not passed/specified, no update detection is provided

**Comment by smarterclayton** [comment]
This also needs to cover overwrite (PUT without conflict) and create-if-does-not-exist as per https://github.com/GoogleCloudPlatform/kubernetes/issues/3085#issuecomment-68282619

**Comment by bgrant0607** [comment]
We should try to use standard REST/HTTP conventions. In addition to being more understandable to REST developers, it should help ensure correct behavior in the presence of caching proxies and reverse proxies between the client and master (primarily hosted cluster scenarios).

I think kubectl and the apiserver should correctly set the HTTP headers based on resourceVersion from the provided json (or from command-line arguments for resize and other updates). We probably still want the API server to look at resourceVersion from the json for curl users. Maybe it should look at both the headers and resourceVersion.

Some details about expected behavior, such as status codes (precondition failed, resource exists):
http://oclc.org/developer/develop/worldshare-platform/architecture/resource-versioning-using-etags.en.html

/cc @nikhiljindal

**Comment by bgrant0607** [comment]
Proposal: apiserver should use the resourceVersion from the JSON only. 

The client should automatically populate Etag and If-match from the resourceVersion for the benefit of intermediate HTTP components, such as caching reverse proxies. 

The only actual storage-layer precondition we need to support is one based on resourceVersion. 

We should also support operations based on UID, once we have a UID-based index and multi-object transactions. 

We can support additional preconditions in the client (as we currently do for resize) and/or apiserver (e.g., once we implement a size subresource), for convenience, by using resourceVersion under the hood.

**Comment by bgrant0607** [comment]
Obsolete
