### ISSUE TITLE
nslookup: can't resolve '(null)': Name does not resolve

### ISSUE THREAD

**Issue by jy1779** [kubernetes/kubernetes#65672]
nslookup: can't resolve '(null)': Name does not resolve
nslookup: can't resolve 'kubernetes': Try again

**Comment by jhorwit2** [comment]
@jy1779 Please re-post your question to [Stack Overflow](http://stackoverflow.com/questions/tagged/kubernetes). If you think this is a bug in kubernetes core, then please reopen or recreate an issue following the issue template. 

We are trying to consolidate the channels to which questions for help/support
are posted so that we can improve our efficiency in responding to your requests,
and to make it easier for you to find answers to frequently asked questions and
how to address common use cases.

We regularly see messages posted in multiple forums, with the full response
thread only in one place or, worse, spread across multiple forums. Also, the
large volume of support issues on github is making it difficult for us to use
issues to identify real bugs.

Members of the Kubernetes community use Stack Overflow to field support
requests. Before posting a new question, please search Stack Overflow for answers 
to similar questions, and also familiarize yourself with:

  * [user documentation](http://kubernetes.io/docs/)
  * [troubleshooting guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/)

Again, thanks for using Kubernetes.

The Kubernetes Team

/close
