### ISSUE TITLE
Feature Request: SubNamespaces

### ISSUE THREAD

**Issue by santiagopoli** [kubernetes/kubernetes#65728]
/kind feature

Hi there!

At my company, we are currently provisioning different Kubernetes clusters for each product team. Recently, we were talking about the possibility of provisioning a single cluster, and giving each team its own namespace. The problem relies on the fact that several teams are using more than one namespace within their clusters. For example, Team A has two namespaces: Infrastructure (where they deploy things like ingress controllers or databases) and Services (where they deploy microservices). 
If we migrate to a single cluster we could then provision two namespaces: **teamA-Infrastructure** and **teamA-Services**. 
It would be nice to provision a single namespace called teamA and allow the team to provision sub namespaces under it (something like **teamA/infrastructure**).

This would enable the possibility of doing something like:

`kubectl get pods -n teamA`

*** all pods of teamA (in all subnamespaces)  ***

`kubectl get pods -n teamA/infrastructure`

*** all infrastructure pods of teamA ***

What are your thoughts regarding this feature?

Regards,

**Comment by liggitt** [comment]
> What are your thoughts regarding this feature?

This has been discussed many times (including when the original namespaces feature was designed and implemented). Until now, it has not been accepted as a direction because of the internal and external complexity it would introduce. It's also difficult to see how this could be added in a way that would remain compatible with existing API clients

**Comment by liggitt** [comment]
@kubernetes/sig-api-machinery-feature-requests
