### ISSUE TITLE
No timeout when Kubelet Calling cni plugin

### ISSUE THREAD

**Issue by liucimin** [kubernetes/kubernetes#65743]
**BUG REPORT**:

/kind bug

**What happened**:
When the kubelet create sandbox by cni plugin.
It will just use exec.Cmd to call the cni binary file.
In some cni plugin,such as contiv,the cni binary file may be locked and no return.
In this case, when kubelet first time call RunPodSandbox got a ctx timeout. the next time kubelet re-creates PodSandbox, it will always report this timeout.

![image](https://user-images.githubusercontent.com/8232349/42195729-f27d870c-7eac-11e8-97a9-ed5106a9dee9.png)

**What you expected to happen**:
Next time  kubelet re-creates PodSandbox it will do call cni again.

**How to reproduce it (as minimally and precisely as possible)**:
Create a pod in a node,and make the cni binary file not return.

**Environment**:
- Kubernetes version (use `kubectl version`):v.1.9.2

@kubernetes/sig-node-bugs

**Comment by liucimin** [comment]
sig/node

**Comment by huydinhle** [comment]
we are also got affected by this issue https://github.com/kubernetes/kubernetes/issues/45419, can someone take a look at this PR. we will be happy to test this out

**Comment by liucimin** [comment]
@huydinhle 
Yes, i m trying to fix this problem.
My change is first set a timeout in cni.
When the cni merge my code,then kubelet will fix more easy.
https://github.com/containernetworking/cni/pull/568

**Comment by nikopen** [comment]
https://github.com/containernetworking/cni/pull/568 got merged, this is resolved I presume? @liucimin 

/close

**Comment by nikopen** [comment]
Just saw that a fix is needed in kubelet as well, can you confirm @liucimin ?

/reopen

**Comment by bboreham** [comment]
Yes kubelet needs to be changed.
And add a test for this case.

**Comment by liucimin** [comment]
@nikopen 
Yes,kubelet should update the cni version.
I will change the kubelet when the cni  project release a new version

**Comment by nikopen** [comment]
@bboreham what are the plans for cutting a new CNI release and bumping it in k8s? Does it need a new major k8s release to be bumped, v1.13?

[Here](https://github.com/containernetworking/plugins/releases) I can see the latest  is v0.7.3, seen as plain 'cni' in [fedora](https://release-monitoring.org/project/15246/),  but in [the official page](https://github.com/containernetworking/cni/releases) the latest is 0.6.0 with some 0.7.0-alpha versions. Maybe because on the v1.12 changelogs I can see k8s is still using 0.6.0, but it's still inconsistent?

It's an old issue affecting many ( https://github.com/kubernetes/kubernetes/issues/45419 ), if the fix in kubelet is straightforward then this can be a great addition, given v1.13 is marked as a stability release.

**Comment by nikopen** [comment]
@liucimin feel free to prepare the Kubelet PR, it will then be easier to coordinate the full fix.

**Comment by bboreham** [comment]
There is no relevant change in CNI plugins. 

The change you are waiting for is in libcni, and is already merged to master. Do not wait for it: test at will.  

(I expect the calling code will need changing to make use of the new timeout, but I haven’t studied it)

**Comment by roywangtj** [comment]
The .go files that are under [https://github.com/kubernetes/kubernetes/tree/master/vendor/github.com/containernetworking/cni/libcni] were all two years ago. Where can we find the libcni code merged?

**Comment by bboreham** [comment]
@roywangti the repo for libcni is https://github.com/containernetworking/cni/

Part of the next step is to copy updated files into the location you pointed at.

**Comment by roywangtj** [comment]
@bboreham, got it, Thanks!

**Comment by liucimin** [comment]
#71653
