### ISSUE TITLE
Make webhook support more auth review API

### ISSUE THREAD

**Issue by WanLinghao** [kubernetes/kubernetes#65744]
/kind feature
Currently, the webhook authorizer doesn't support selfsubjectrulesreview API. It just returns a empty list as well as an error like `webhook authorizer does not support user rule resolution`. In the future, with more authorization review API imported, users are deserved to have more options on webhook authorization review.One possible solution is keeping current webhook RESTClient configuration model unchanged, and modify  how it requests remote auth service.
For example:
Request A:
When user wants to know if user "bob" could get pod on namespace "ns1", webhook authorizer would request remote auth service like: `RestClient.Post().Resource("subjectaccessreview").Body(subjectAccessReview).Do().Into(result)`
Request B:
When user wants to know what user "bob" can do on namespace "ns1", webhook authoerizer would request remote auth service like:
`RestClient.Post().Resource("selfsubjectrulesreview").Body(selfSubjectRulesReview).Do().Into(result)`
For request A, the remote auth service would receive a request like:
xx/xx/xx/subjectaccessreview
For request B, the remote auth service would receive a request like:
xx/xx/xx/selfsubjectrulesreview
So remote auth service can split authorization requests and response them respectively.
I think we could make this feature optional, for users who requires simple webhook authorization, just use current model.

**Comment by liggitt** [comment]
/close
This is currently tracked in https://github.com/kubernetes/kubernetes/issues/52745

There’s a variety of additional pieces of information we want to feed to the webhook authorizer:
* ability to indicate what apiversion to speak, so we can move to v1 and away from v1beta1
* ability to indicate the failure policy (fail deny or fail no opinion)
* ability to indicate support for rules review. For this in particular, we’d need a different object than SelfSubjectRulesReview, because the API server would be requesting rules for a particular user info, which would necessitate designing a SubjectRulesReview. Before we committed to that, we’d want to resolve the allow/deny ordering questions, since it would be the same object used by the kube-apiserver to serve an eventual SubjectRulesReview API

those are all things we have an interest in seeing happen eventually, but are not short-term priorities. Immediate priorities are around bringing audit to v1, progressing dynamic service account tokens, and improving node isolation/restriction
