### ISSUE TITLE
kubectl wait ignores timeout

### ISSUE THREAD

**Issue by chucky2305** [kubernetes/kubernetes#65868]
/kind bug
/sig cli

Either i am doing something wrong or i misunderstood the concept behind kubectl wait.

I use kubectl wait in my gitlab ci pipeline.

Stage 1: Deploy my app
Stage 2: Detect if the app is deployed and running.

In Stage 2 i wanted to use
kubectl wait --timeout=60s --for condition=ready pod -l release=branch123,pod-name=php-nginx

When the deployment is not ready and no pod can be found with a labels "release=branch123" and "pod-name=php-nginx" kubectl wait ignores the define timeout (60 seconds) in my example.
Why is this so? I was expecting to always wait 60 seconds.

I hope my request is clear. Maybe i am just doing something wrong here?

**Comment by Lion-Wei** [comment]
I think `kubectl wait` will error out if can't get resource. 
@deads2k , is this by design?

**Comment by deads2k** [comment]
> I think kubectl wait will error out if can't get resource.
> @deads2k , is this by design?

Resource identification happens and then it waits on those resources.  That means the initial set of resources is predictable.  Otherwise you end up with a race of "how many of these should I wait for if they keep appearing".

Try waiting for the condition on the deployment (which should exist) instead of the individual pods.

**Comment by chucky2305** [comment]
This was actually my Plan B. First kubectl wait on the deployment and in second step kubectl wait to see if the pod is ready.
