### ISSUE TITLE
leaderelection lost, kube-controller-manager and kube-scheduler FATAL restart

### ISSUE THREAD

**Issue by lf1029698952** [kubernetes/kubernetes#65966]
/kind bug
 /sig kube-controller-manager

**What happened**:
Kubernetes v1.7.11  
kube-controller-manager and kube-scheduler FATAL restart, and all nodes update node status failure.

kube-controller-manager fatal logs:
```
Running on machine: master-1
Binary: Built with gc go1.8.3 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
F0709 10:49:37.947502  574544 controllermanager.go:220] leaderelection lost
goroutine 1 [running]:
k8s.io/kubernetes/vendor/github.com/golang/glog.stacks(0xc42000c001, 0xc4284f1000, 0x88a, 0x2710)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/golang/glog/glog.go:766 +0xa7
k8s.io/kubernetes/vendor/github.com/golang/glog.(*loggingT).output(0x519afc0, 0xc400000003, 0xc420954bb0, 0x5054be2, 0x14, 0xdc, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/golang/glog/glog.go:720 +0x1a3
k8s.io/kubernetes/vendor/github.com/golang/glog.(*loggingT).printf(0x519afc0, 0x3, 0x36e8455, 0x13, 0x0, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/golang/glog/glog.go:655 +0x14f
k8s.io/kubernetes/vendor/github.com/golang/glog.Fatalf(0x36e8455, 0x13, 0x0, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/golang/glog/glog.go:1145 +0x67
k8s.io/kubernetes/cmd/kube-controller-manager/app.Run.func3()
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kube-controller-manager/app/controllermanager.go:220 +0x51
k8s.io/kubernetes/pkg/client/leaderelection.(*LeaderElector).Run.func1(0xc42068c240)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/client/leaderelection/leaderelection.go:146 +0x4a
k8s.io/kubernetes/pkg/client/leaderelection.(*LeaderElector).Run(0xc42068c240)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/client/leaderelection/leaderelection.go:153 +0xb4
k8s.io/kubernetes/pkg/client/leaderelection.RunOrDie(0x50e0820, 0xc42037b7a0, 0x37e11d600, 0x2540be400, 0x77359400, 0xc4203e4c80, 0x37c0448, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/client/leaderelection/leaderelection.go:162 +0x5a
k8s.io/kubernetes/cmd/kube-controller-manager/app.Run(0xc420528000, 0x37c7240, 0xc420058ea0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kube-controller-manager/app/controllermanager.go:223 +0x890
main.main()
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kube-controller-manager/controller-manager.go:54 +0x102

goroutine 5 [chan receive]:
k8s.io/kubernetes/vendor/github.com/golang/glog.(*loggingT).flushDaemon(0x519afc0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/golang/glog/glog.go:879 +0x7a
created by k8s.io/kubernetes/vendor/github.com/golang/glog.init.1
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/golang/glog/glog.go:410 +0x21d
```
kube-scheduler fatal logs:
```
Running on machine: master-1
Binary: Built with gc go1.8.3 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
F0709 10:49:37.947676  574545 server.go:141] lost master
goroutine 1 [running]:
k8s.io/kubernetes/vendor/github.com/golang/glog.stacks(0xc42000c001, 0xc4245d0000, 0x84d, 0x2710)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/golang/glog/glog.go:766 +0xa7
k8s.io/kubernetes/vendor/github.com/golang/glog.(*loggingT).output(0x30da120, 0xc400000003, 0xc42023c4d0, 0x301bd03, 0x9, 0x8d, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/golang/glog/glog.go:720 +0x1a3
k8s.io/kubernetes/vendor/github.com/golang/glog.(*loggingT).printf(0x30da120, 0x3, 0x2180ad2, 0xb, 0x0, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/golang/glog/glog.go:655 +0x14f
k8s.io/kubernetes/vendor/github.com/golang/glog.Fatalf(0x2180ad2, 0xb, 0x0, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/golang/glog/glog.go:1145 +0x67
k8s.io/kubernetes/plugin/cmd/kube-scheduler/app.Run.func2()
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/plugin/cmd/kube-scheduler/app/server.go:141 +0x51
k8s.io/kubernetes/pkg/client/leaderelection.(*LeaderElector).Run.func1(0xc42071a240)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/client/leaderelection/leaderelection.go:146 +0x4a
k8s.io/kubernetes/pkg/client/leaderelection.(*LeaderElector).Run(0xc42071a240)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/client/leaderelection/leaderelection.go:153 +0xb4
k8s.io/kubernetes/pkg/client/leaderelection.RunOrDie(0x306c740, 0xc421126c60, 0x37e11d600, 0x2540be400, 0x77359400, 0xc4244d4610, 0x220a7e8, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/client/leaderelection/leaderelection.go:162 +0x5a
k8s.io/kubernetes/plugin/cmd/kube-scheduler/app.Run(0xc42025a140, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/plugin/cmd/kube-scheduler/app/server.go:144 +0xb4a
main.main()
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/plugin/cmd/kube-scheduler/scheduler.go:40 +0x81

goroutine 5 [chan receive, 2 minutes]:
k8s.io/kubernetes/vendor/github.com/golang/glog.(*loggingT).flushDaemon(0x30da120)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/golang/glog/glog.go:879 +0x7a
created by k8s.io/kubernetes/vendor/github.com/golang/glog.init.1
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/golang/glog/glog.go:410 +0x21d

goroutine 49 [chan receive, 1422 minutes]:
k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache.(*controller).Run.func1(0xc4203f73e0, 0xc420224780)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache/controller.go:103 +0x40
created by k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache.(*controller).Run
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache/controller.go:105 +0x9c

```
kube-apiserver ERROR logs
```
kube-apiserver[52063]: E0709 11:14:45.887298   52063 writers.go:142] apiserver was unable to write a JSON response: http: Handler timeout
kube-apiserver[52063]: E0709 11:14:45.890642   52063 writers.go:142] apiserver was unable to write a JSON response: http: Handler timeout
kube-apiserver[52063]: E0709 11:14:45.894027   52063 status.go:62] apiserver received an error that is not an metav1.Status: http: Handler timeout
kube-apiserver[52063]: E0709 11:14:45.927790   52063 writers.go:142] apiserver was unable to write a JSON response: http2: stream closed
kube-apiserver[52063]: E0709 11:14:45.929795   52063 writers.go:142] apiserver was unable to write a JSON response: http: Handler timeout
kube-apiserver[52063]: E0709 11:14:46.012641   52063 status.go:62] apiserver received an error that is not an metav1.Status: http: Handler timeout
kube-apiserver[52063]: E0709 11:14:46.083986   52063 status.go:62] apiserver received an error that is not an metav1.Status: http: Handler timeout
```
kubelet ERROR logs:
```
kubelet[2294]: E0709 10:37:18.537442    2294 event.go:200] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", A     PIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"java-tianpeng-club-dubbo.product-2154283552-sjsjd.1535a35cb19bc0ae", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", Reso     urceVersion:"223147998", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriod     Seconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalize     rs:[]string(nil), ClusterName:""}, InvolvedObject:v1.ObjectReference{Kind:"Pod", Namespace:"default", Name:"java-tianpeng-club-dubbo.product-2154283552-sjsjd", UID:"21da492f-68b1     -11e8-8e1d-fa163e92a7d1", APIVersion:"v1", ResourceVersion:"191230821", FieldPath:"spec.containers{app}"}, Reason:"Unhealthy", Message:"Readiness probe failed: Get http://10.105.37.54:8087/zbjcheck: net/http: request canceled (Client.Timeout exceeded while awaiting headers)", Source:v1.EventSource{Component:"kubelet", Host:"10.20.128.187"}, FirstTimestam     p:v1.Time{Time:time.Time{sec:63663904067, nsec:0, loc:(*time.Location)(0x58de000)}}, LastTimestamp:v1.Time{Time:time.Time{sec:63666699863, nsec:211579284, loc:(*time.Location)(0x     58de000)}}, Count:99541, Type:"Warning"}': 'Timeout: request did not complete within allowed duration' (will not retry!)
kubelet_node_status.go:357] Error updating node status, will retry: error getting node "10.20.128.120": Get https://10.20.128.251:8443/api/v1/nodes/10.20.128.120: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
transport: http2Server.HandleStreams failed to read frame: read unix /var/run/dockershim.sock->@: use of closed network connection
transport: http2Client.notifyError got notified that the client transport was broken EOF.
```
I have migrated the etcd database to another machines, Everything was normal at that time. But I'm not sure whether it's about etcd, because etcd logs is normal. 
After a period of time, kube-controller-manager and kube-scheduler FATAL restart, and all nodes update node status, all nodes status are NotReady, Last for more than ten minutes and then recovery, It happens every few days.
What's wrong with kube-controller-manager and kube-scheduler,
I'm very anxious, Thanks!

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.11", GitCommit:"b13f2fd682d56eab7a6a2b5a1cab1a3d2c8bdd55", GitTreeState:"clean", BuildDate:"2017-11-25T18:34:52Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.11", GitCommit:"b13f2fd682d56eab7a6a2b5a1cab1a3d2c8bdd55", GitTreeState:"clean", BuildDate:"2017-11-25T17:51:39Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
- OS (e.g. from /etc/os-release):
CentOS Linux release 7.4.1708 (Core)
- Kernel (e.g. `uname -a`):
Linux 3.10.0-693.17.1.el7.x86_64

**Comment by lf1029698952** [comment]
I'm not sure whether it's a network problem between nodes and master. Will network problems cause kube-controller-manager fatal to restart?

**Comment by hzxuzhonghu** [comment]
obvious network problem

**Comment by lf1029698952** [comment]
Thank you for your reply, The possible problem occurs between apiserver and etcd, I will continue to observe my cluster.

**Comment by lf1029698952** [comment]
It's caused by the network, fix network and the problem no more appear, Thanks!

**Comment by victor-anubavam** [comment]
kube-controller-manager and kube-scheduler keeps on restarting
 Docker Version: 19.3.11
 Kube Proxy Version: v1.16.0
`**Logs` are :** I1228 16:59:28.077293       1 leaderelection.go:241] attempting to acquire leader lease  kube-system/kube-scheduler...
E1228 16:59:45.353862       1 leaderelection.go:330] error retrieving resource lock kube-system/kube-scheduler: Get https://IPaddress/namespaces/kube-system/endpoints/kube-scheduler?timeout=10s: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
I1228 16:59:47.969930       1 leaderelection.go:251] successfully acquired lease kube-system/kube-scheduler
I1228 17:00:42.008006       1 leaderelection.go:287] failed to renew lease kube-system/kube-scheduler: failed to tryAcquireOrRenew context deadline exceeded
F1228 17:00:42.008059       1 server.go:264] leaderelection lost

**Comment by jagadeeshanubavam** [comment]
kube-controller-manager and kube-scheduler keeps on restarting. I googled lot but no documents found to debug the issue .
**Docker Version:** 19.3.11
**Kube Proxy Version:** v1.16.0
**kube scheduler Logs  :** I1228 16:59:28.077293 1 leaderelection.go:241] attempting to acquire leader lease kube-system/kube-scheduler...
E1228 16:59:45.353862 1 leaderelection.go:330] error retrieving resource lock kube-system/kube-scheduler: Get https://IPaddress/namespaces/kube-system/endpoints/kube-scheduler?timeout=10s: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
I1228 16:59:47.969930 1 leaderelection.go:251] successfully acquired lease kube-system/kube-scheduler
I1228 17:00:42.008006 1 leaderelection.go:287] failed to renew lease kube-system/kube-scheduler: failed to tryAcquireOrRenew context deadline exceeded
F1228 17:00:42.008059 1 server.go:264] leaderelection lost

kube-system kube-controller-manager Logs :
W1228 17:00:04.721378 1 actual_state_of_world.go:506] Failed to update statusUpdateNeeded field in actual state of world: Failed to set statusUpdateNeeded to needed true, because nodeName="node4" does not exist
I1228 17:00:04.726825 1 shared_informer.go:204] Caches are synced for certificate
I1228 17:00:04.732538 1 shared_informer.go:204] Caches are synced for TTL
I1228 17:00:04.739613 1 shared_informer.go:204] Caches are synced for ClusterRoleAggregator
I1228 17:00:04.754683 1 shared_informer.go:204] Caches are synced for certificate
I1228 17:00:04.760101 1 shared_informer.go:204] Caches are synced for stateful set
I1228 17:00:04.768974 1 shared_informer.go:204] Caches are synced for namespace
I1228 17:00:04.769914 1 shared_informer.go:204] Caches are synced for deployment
I1228 17:00:04.790541 1 shared_informer.go:204] Caches are synced for daemon sets
I1228 17:00:04.790710 1 shared_informer.go:204] Caches are synced for ReplicationController
I1228 17:00:04.796386 1 shared_informer.go:204] Caches are synced for disruption
I1228 17:00:04.796403 1 disruption.go:341] Sending events to api server.
I1228 17:00:04.804131 1 shared_informer.go:204] Caches are synced for ReplicaSet
I1228 17:00:04.806910 1 shared_informer.go:204] Caches are synced for GC
I1228 17:00:04.809821 1 shared_informer.go:204] Caches are synced for taint
I1228 17:00:04.809909 1 node_lifecycle_controller.go:1208] Initializing eviction metric for zone:
W1228 17:00:04.809999 1 node_lifecycle_controller.go:903] Missing timestamp for Node node3. Assuming now as a timestamp.
W1228 17:00:04.810038 1 node_lifecycle_controller.go:903] Missing timestamp for Node node4. Assuming now as a timestamp.
W1228 17:00:04.810065 1 node_lifecycle_controller.go:903] Missing timestamp for Node node1. Assuming now as a timestamp.
W1228 17:00:04.810086 1 node_lifecycle_controller.go:903] Missing timestamp for Node node2. Assuming now as a timestamp.
I1228 17:00:04.810101 1 node_lifecycle_controller.go:1108] Controller detected that zone is now in state Normal.
I1228 17:00:04.810145 1 event.go:255] Event(v1.ObjectReference{Kind:"Node", Namespace:"", Name:"node2", UID:"68d34fcf-fd86-42a5-9833-57108c93baee", APIVersion:"", ResourceVersion:"", FieldPath:""}): type: 'Normal' reason: 'RegisteredNode' Node node2 event: Registered Node node2 in Controller
I1228 17:00:04.810164 1 taint_manager.go:186] Starting NoExecuteTaintManager
I1228 17:00:04.810224 1 event.go:255] Event(v1.ObjectReference{Kind:"Node", Namespace:"", Name:"node3", UID:"dc80b75f-ce55-4247-84e3-bf0474ac1057", APIVersion:"", ResourceVersion:"", FieldPath:""}): type: 'Normal' reason: 'RegisteredNode' Node node3 event: Registered Node node3 in Controller
I1228 17:00:04.810233 1 event.go:255] Event(v1.ObjectReference{Kind:"Node", Namespace:"", Name:"node4", UID:"c9d859df-795e-4b2a-9def-08efc67ba4e3", APIVersion:"", ResourceVersion:"", FieldPath:""}): type: 'Normal' reason: 'RegisteredNode' Node node4 event: Registered Node node4 in Controller
I1228 17:00:04.810242 1 event.go:255] Event(v1.ObjectReference{Kind:"Node", Namespace:"", Name:"node1", UID:"8bfe45c3-2ce7-4013-a11f-c1ac052e9e00", APIVersion:"", ResourceVersion:"", FieldPath:""}): type: 'Normal' reason: 'RegisteredNode' Node node1 event: Registered Node node1 in Controller
I1228 17:00:04.811241 1 shared_informer.go:204] Caches are synced for node
I1228 17:00:04.811367 1 range_allocator.go:172] Starting range CIDR allocator
I1228 17:00:04.811381 1 shared_informer.go:197] Waiting for caches to sync for cidrallocator
I1228 17:00:04.859423 1 shared_informer.go:204] Caches are synced for HPA
I1228 17:00:04.911545 1 shared_informer.go:204] Caches are synced for cidrallocator
I1228 17:00:04.997853 1 shared_informer.go:204] Caches are synced for bootstrap_signer
I1228 17:00:05.023218 1 shared_informer.go:204] Caches are synced for expand
I1228 17:00:05.030277 1 shared_informer.go:204] Caches are synced for PV protection
I1228 17:00:05.059763 1 shared_informer.go:204] Caches are synced for endpoint
I1228 17:00:05.060705 1 shared_informer.go:204] Caches are synced for persistent volume
I1228 17:00:05.118184 1 shared_informer.go:204] Caches are synced for attach detach
I1228 17:00:05.246897 1 shared_informer.go:204] Caches are synced for job
I1228 17:00:05.248850 1 shared_informer.go:204] Caches are synced for resource quota
I1228 17:00:05.257547 1 shared_informer.go:204] Caches are synced for garbage collector
I1228 17:00:05.257566 1 garbagecollector.go:139] Garbage collector: all resource monitors have synced. Proceeding to collect garbage
I1228 17:00:05.260287 1 shared_informer.go:204] Caches are synced for resource quota
I1228 17:00:05.305093 1 shared_informer.go:204] Caches are synced for garbage collector
I1228 17:00:44.906594 1 leaderelection.go:287] failed to renew lease kube-system/kube-controller-manager: failed to tryAcquireOrRenew context deadline exceeded
F1228 17:00:44.906687 1 controllermanager.go:279] leaderelection los

**Comment by psingarakannan** [comment]
Any solution to the above problem? Even I'm facing the same problem with the same stack trace.

**Comment by empinator** [comment]
as suggested by [this comment](https://github.com/rancher/rancher/issues/33651#issuecomment-885269904) we ended up giving more RAM to our rancher instances. After that we haven't seen any crashes anymore
