### ISSUE TITLE
Reduce flakiness of density test

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#66239]
Based on this run:
https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/179/build-log.txt
there are a couple things that went wrong:

1. Since failure of deleting RC shouldn't break the whole test:
https://github.com/kubernetes/kubernetes/blob/master/test/e2e/scalability/density.go#L365
[That should just cause an error, but don't break the whole test]

2. If one of a node failed due to some reason, we should *force* deletion of pods from that, to avoid deleting a namespace to take 1h and fail after that.
[It's probably enough to:
- when deleting RC fails, list all pods with that selector and force deletiong of them]

3. Probably reduce timeout for namespace deletion.

/assign @shyamjvs 

Shyam - please take a look or delegate.

**Comment by shyamjvs** [comment]
Yes, I definitely agree we should improve our deletions logic - it's not very robust currently. I can remember some RC deletion timeout flakes even from our smaller jobs.

> Since failure of deleting RC shouldn't break the whole test:

I was suggesting such an idea (in a very rough sense) to you sometime ago if you remember - but in a more general sense, solving for all such flakes instead of doing point-by-point. My idea's roughly the following:

- whenever some operation in the test (that's not super-critical) fails, we log it to some `flakes.txt` file and proceed without causing failures in our tests
- at the end, as part of the CI job we detect if any flakes happened by looking into that file (this would be at test-infra level)
- if yes (and more than some allowed threshold) we will just mark a separate 'flakes' step in the job as red (instead of making our tests red)
- we can later process offline those flakes and try to fix those

Pros of that approach:

- we can clearly separate flakes from genuine test failures (so it'll avoid giving wrong signal to community about scalability tests)
- tests can continue to run until end and give some useful info instead of failing in between
- it will allow us to capture flakes systematically - helping plan/prioritize their fixes

Cons of that approach:

- Sometimes genuine scalability issues may be hidden as 'flakes'. While this can happen, my feeling is we should be able to spot that from the flakes.txt file just as we currently do from build-log. Also, we can limit the flakes threshold to a very low value (for e.g <5) to avoid masking serious issues

Wdyt?

**Comment by shyamjvs** [comment]
cc @mborsz (who's currently looking into addressing our test flakiness)

Maciej - Would you be willing to look into this?

**Comment by wojtek-t** [comment]
@shyamjvs - yes I know we were talking about that.
But given the ClusterLoader effort I don't want to spend too much effort on fixing that.

So if you can do that in a way that we will be able to reuse with ClusterLoader - I'm fine with that.
If not - do the simplest possible thing without fixing all possible problems.

**Comment by shyamjvs** [comment]
> But given the ClusterLoader effort I don't want to spend too much effort on fixing that.

IMO isolating flakes is independent problem from moving stuff to cluster-loader :)

> So if you can do that in a way that we will be able to reuse with ClusterLoader - I'm fine with that.

Yes - I'm trying to make some changes in test-framework that'll also be reusable by cluster-loader.

**Comment by wojtek-t** [comment]
Density test has been merged with load test in the meantime. There are also pretty stable now.
Closing.
