### ISSUE TITLE
Inject Container OS environments using ETCD or otherwise

### ISSUE THREAD

**Issue by obenziane21** [kubernetes/kubernetes#66258]
I'd like a recommendation solution from anyone for using service discovery
We want to have the ability to start up containers and automatically inject `application`, `databases`, etc... `environment variables` from one central tool.
I could not find anything like that using `ETCD` or maybe I'm missing something in there ?

**Comment by krmayankk** [comment]
@obenziane21 please follow guidelines when opening issue and provide additional details with better example of what you want to achieve. I don't fully understand your scenario, but please read this https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#initializers and see if it helps.

**Comment by jhorwit2** [comment]
Please re-post your question to [Stack Overflow](http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support
are posted so that we can improve our efficiency in responding to your requests,
and to make it easier for you to find answers to frequently asked questions and
how to address common use cases.

We regularly see messages posted in multiple forums, with the full response
thread only in one place or, worse, spread across multiple forums. Also, the
large volume of support issues on github is making it difficult for us to use
issues to identify real bugs.

Members of the Kubernetes community use Stack Overflow to field support
requests. Before posting a new question, please search Stack Overflow for answers 
to similar questions, and also familiarize yourself with:

  * [user documentation](https://kubernetes.io/docs/home/)
  * [troubleshooting guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/)

Again, thanks for using Kubernetes.

The Kubernetes Team

/close
