### ISSUE TITLE
Best practice to generate --tls-cert-file and --tls-private-key-file for thousands of kubelets?

### ISSUE THREAD

**Issue by haoqing0110** [kubernetes/kubernetes#66281]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind feature

**What happened**:

What's the best practice to generate `--tls-cert-file` and `--tls-private-key-file` for thousands of kubelet? 

I know if `--tls-cert-file` and `--tls-private-key-file` are not provided, there will be self-signed certificate and key by default. BUT that's not what I want. 
As CIS(Center for Internet Security) suggests, I want to specify CA in ` --kubelet-certificate-authority` in apiserver, to verify kubelet's certificate before establishing connection.

I have thought about 2 methods:
1. Generate a common cert, it's efficient, but currently can't find a method to support wildcard IP in certificate.
2. Generate cert&key for each kubelet with it's IP. When there are thousands of nodes, that's a huge number of cert&key.

Any other ways? Like, can I specify a CA in kubelet, and kubelet can maintain key and cert automatically? 

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by liqlin2015** [comment]
It would be good that the cert/key used by kubelet server can be generated by specified CA.

**Comment by jhorwit2** [comment]
@haoqing0110 please take a look at https://kubernetes.io/cn/docs/admin/kubelet-tls-bootstrapping/ which includes kubelet server and client certificate management plus rotation.

If you have any further questions please post your question to [Stack Overflow]
(http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support
are posted so that we can improve our efficiency in responding to your requests,
and to make it easier for you to find answers to frequently asked questions and
how to address common use cases.

We regularly see messages posted in multiple forums, with the full response
thread only in one place or, worse, spread across multiple forums. Also, the
large volume of support issues on github is making it difficult for us to use
issues to identify real bugs.

Members of the Kubernetes community use Stack Overflow to field support
requests. Before posting a new question, please search Stack Overflow for answers 
to similar questions, and also familiarize yourself with:

  * [user documentation](https://kubernetes.io/docs/home/)
  * [troubleshooting guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/)

Again, thanks for using Kubernetes.

/close
