### ISSUE TITLE
Failing Tests: [sig-cluster-lifecycle] Reboot [Disruptive] [Feature:Reboot]

### ISSUE THREAD

**Issue by mohammedzee1000** [kubernetes/kubernetes#66339]
# Failing Jobs
[sig-release-master-blocking#gci-gke-reboot](https://k8s-testgrid.appspot.com/sig-release-master-blocking#gci-gke-reboot)

# Failing Tests
[each node by ordering clean reboot and ensure they function upon restart](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gke-reboot/16044)
[each node by switching off the network interface and ensure they function upon switch on](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gke-reboot/16044)
[each node by dropping all inbound packets for a while and ensure they function afterwards](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gke-reboot/16044)
[each node by dropping all outbound packets for a while and ensure they function afterwards](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gke-reboot/16044)
[each node by ordering unclean reboot and ensure they function upon restart](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gke-reboot/16044)
[each node by triggering kernel panic and ensure they function upon restart](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gke-reboot/16044)

Tests failing on sig-master-blocking

/cc @tpepper @AishSundar 
/kind bug
/priority failing-test
/priority important-soon
/sig cluster-lifecycle
/milestone v1.12

**Comment by neolit123** [comment]
this is a flaky one that had the same behavior since as long as test grid allows you to go back (May).
is this test maintained by sig-cluster-lifecycle?

i'm seeing some kubelet errors here:
https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gke-
reboot/16082/artifacts/gke-e2e-16082-344e3-default-pool-07f2b410-9rsd/kubelet.log

there are some node timeouts too here:
https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gke-reboot/16082/artifacts/gke-e2e-16082-344e3-default-pool-07f2b410-9rsd/node-problem-detector.log

**Comment by soltysh** [comment]
I don't see why this is marked as sig-cli related. I went through the failures none of them is cli-related. Dropping the label.

**Comment by mohammedzee1000** [comment]
/priority critical-urgent
/remove-priority important-soon
Do we have any eta of when these will be fixed

**Comment by neolit123** [comment]
@kubernetes/sig-gcp-test-failures 
/sig gcp
/remove-sig node

@mohammedzee1000 
the test flakes due to network conditions. it does have green runs from time to time.
as release blocking, is it a requirement for it to be non-flaky?

/assign @quinton-hoole
/assign @jszczepkowski 
as per this PR from 2015:
https://github.com/kubernetes/kubernetes/commit/346b8473a32922d3bdb9499f07964ff612ca84cf
to ping the right folks that know how to debug this properly.

i think the culprit is here, but this is GCE releated:
https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gke-reboot/16465/artifacts/gke-e2e-16465-344e3-default-pool-bca7d2d2-872b/kubelet.log
```
F0806 11:00:32.633939    1036 server.go:260] failed to run Kubelet: cannot create certificate signing request: Post https://35.232.38.100/apis/certificates.k8s.io/v1beta1/certificatesigningrequests: dial tcp 35.232.38.100:443: i/o timeout
```

**Comment by mohammedzee1000** [comment]
This is green now closing
/close
