### ISSUE TITLE
Add e2e tests for ceph-csi(rbd/cephfs) volume

### ISSUE THREAD

**Issue by mkimuram** [kubernetes/kubernetes#66388]
**Is this a BUG REPORT or FEATURE REQUEST?**:
 /kind feature

**What happened**:
e2e tests for ceph-csi(rbd/cephfs) volume don't exist.

**What you expected to happen**:
e2e tests for ceph-csi(rbd/cephfs) should exist.

**How to reproduce it (as minimally and precisely as possible)**:
Run e2e tests, for example with ```--ginkgo.focus=".*CSI Volumes.*".```

**Anything else we need to know?**:
/sig storage

**Environment**:
- Kubernetes version: k8s v1.12-alpha

**Comment by aruneli** [comment]
I can contribute to this

**Comment by mkimuram** [comment]
@aruneli 

Thank you for your interest.

I think that we are ready to make a pull request for https://github.com/mkimuram/kubernetes/commit/b461cb7acad0a0912fda198b8df46cd5ae452f0a, once  https://github.com/ceph/ceph-csi/issues/48 is resolved. I'm welcome to your review and tests, before doing it.

**Comment by mkimuram** [comment]
@msau42 @davidz627 @pohly 

[This patch](https://github.com/mkimuram/kubernetes/commit/5390ac71df912e596bcfd5e13fcf0db7724442b2) will make csi rbd driver works with latest e2e test code.
I'm sharing it:
  - to discuss if it would be worth merging this to k/k until we make e2e test library for each driver
  - to make this a start point for developing e2e library for each driver

**Comment by pohly** [comment]
I think the criteria for testing more CSI drivers directly in k/k should be:
- does it increase code coverage for Kubernetes code, for example by exercising additional code paths because the CSI driver is different from others
- is the CSI driver an open source project that Kubernetes wants to support
- does the driver depend on external resources
- is it stable and are developers willing to investigate and fix issues

It doesn't look bad for ceph-rbd: I think we need a more diverse set of drivers to weed out bugs in Kubernetes and the sidecar containers, ceph and ceph-csi are community-driven open source projects, it can be set up without some external storage backend, and I assume that both @mkimuram and @rootfs would help to keep this working. I myself also recently fixed a few issues.

But in which jobs should these additional tests run? If it is pre-merge, then testing time for a PR might go up too much.

**Comment by davidz627** [comment]
/cc @BenTheElder @krzyzacy 
I believe we wouldn't want to add them as pre-submits, AFAIK we're trying to get the GCE ones as presubmits as well

**Comment by BenTheElder** [comment]
Yeah, I think we'd want to run presubmits in the driver's repos, not k/k presubmits. It is of course to the driver maintainers on their own presubmits on their own repos, but k/k should minimize external dependencies in presubmit... which is something we need to improve. It sounds like run time is also a concern.

We can also add CI (not PR) testing that uses various drivers to help drive kubernetes release signal.

**Comment by BenTheElder** [comment]
@kfox1111 this is a quirk in the re-open ACLs that is known ...
/assign
