### ISSUE TITLE
 Kubelet should respect ACPI shutdown #22494 

### ISSUE THREAD

**Issue by kevincox** [kubernetes/kubernetes#66393]
See https://github.com/kubernetes/kubernetes/issues/22494

/kind feature

**Comment by ccope** [comment]
What would respecting the ACPI shutdown involve? Wouldn't the init system just tell all of the services (such as kubelet) to terminate? Does kubelet's handler for SIGTERM need to do something different?

**Comment by kevincox** [comment]
You would want a graceful shutdown. This allows services to finish processing active requests as well as allowing the pod state to propagate to things like load balancers before being killed and before the node goes offline.

**Comment by kevincox** [comment]
For example I am currently running services on Google Container Engine with some preemptable nodes. Currently when these nodes are killed I see a small spike of errors because the Kubelet doesn't respect the ACPI shutdown. It would be nice to have graceful shutdown when possible.

**Comment by rhefner1** [comment]
@kevincox though solving this issue is the right answer, you can use the node-termination-handler [1] project as a daemonset to monitor the GCE metadata APIs for an impending shutdown. If you look into the code it just runs a delete on each pod on the node and hopefully that completes in the 30 second window that you have. The most important thing is that it will take those pods out of the load balancer so they don't get new traffic. 

I have been using it in our staging and production clusters for the past few weeks and it does eliminate the spike of errors but I've also observed that it doesn't shut down the pods gracefully. It seems like a SIGKILL. But I'm not 100% sure.

[1] https://github.com/GoogleCloudPlatform/k8s-node-termination-handler
