### ISSUE TITLE
should delete node when hostname-override set

### ISSUE THREAD

**Issue by tianshapjq** [kubernetes/kubernetes#66493]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature

**What happened**:
When hostname-override is set(or changed) in kubelet, we can find that there will be new node coming up while the original one becomes NotReady. Maybe deleting the original node is better, right?

**What you expected to happen**:
delete original node when hostname-override is set.

**How to reproduce it (as minimally and precisely as possible)**:
1. specify a new name in the hostname-override.
2. restart kubelet.
3. `kubectl get node`, and you will find the original one becomes NotReady.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.10, all versions in fact.
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by tianshapjq** [comment]
I try to figure this out, but stuck in identifying the specific node. There are no params which can be used to identify one node, the UID changes when hostname-override is set. Is identified by IP or machineID possible?

**Comment by liggitt** [comment]
> we can find that there will be new node coming up while the original one becomes NotReady.

that is expected. in non-cloud envs, setting --hostname-override changes the identity of the node. it does not have a record of it's previous identity.

> Maybe deleting the original node is better, right?

in a cloud provider environment, the node controller will delete nodes that are not found in the cloud provider metadata. in a non-cloud provider environment, you are responsible for deleting those nodes.

having nodes delete themselves is a non-goal, since it removes the ability of cluster admins to taint compromised nodes effectively.

/close
