### ISSUE TITLE
Add end to end tests for volume plugins

### ISSUE THREAD

**Issue by vishh** [kubernetes/kubernetes#6650]
Gluster and iscsi volume plugins were added recently. Ceph plugins are underway. We need end to end tests for all these plugins. These tests are necessary for ownership and maintenance of these plugins.

cc @thockin @rootfs

**Comment by vishh** [comment]
@thockin, if these plugins are part of our v1.0 product, then we need to have tests working before v1.0.

**Comment by rootfs** [comment]
okie dokie

**Comment by thockin** [comment]
What we don't have is an established procedure to say "this feature was verified by e2e on Huamin's platform, but not our because it is not supported here".  We need something like this.

@quinton-hoole @zmerlynn @ixdy

**Comment by rootfs** [comment]
I can offer vagrant/containerized gluster and ceph cluster for being consistency.

**Comment by vishh** [comment]
How hard would it be to run a gluster cluster inside kubernetes?

**Comment by thockin** [comment]
Even if we ran gluster, ceph, flocker, iscsi, and NFS in our e2e clusters,
we still can't test things like EBS.

**Comment by quinton-hoole** [comment]
The best answer that we have to this sort of thing at the moment is explicit switch statements in the e2e test code, for example:

https://github.com/GoogleCloudPlatform/kubernetes/blob/master/test/e2e/es_cluster_logging.go#L63

I think Vish's suggested approach of running gluster, ceph, flocker, iscsi and NFS servers inside kubernetes for e2e testing purposes is a good one.  I don't immediately see any problems with that.  For EBS, a switch statement like the one above should be sufficient to ensure that the test only runs in EC2. The test should tell Ginkgo via something like Skip() (it that's possible) that it's skipping on non-EC2 - rather than just logging an info message like the above code does.

**Comment by quinton-hoole** [comment]
PS:  A better approach would of course be some sort of e2e test plugins, but we're not there yet.

**Comment by ixdy** [comment]
I don't think Gingko currently supports programmatically skipping tests, but you can supply --skip=REGEXP to the runner to skip tests if they were named appropriately. This doesn't seem like a very good solution, though, since it seems like it would be very easy to mess this up (and I'm not sure we'd want to have to remember which things to skip on each platform, either).

**Comment by ixdy** [comment]
And this issue raises a good point in that whatever solution we end up using to aggregate e2e test results from various providers we need to somehow highlight tests that only run in particular configurations (or ignore them in others, or something).

**Comment by jsafrane** [comment]
NFS e2e test: #6755

**Comment by zmerlynn** [comment]
Thanks for this bug, @vishh. These volume plugins shouldn't've been added without some e2e testing infrastructure behind it, somewhere, or some sort of effective promissory note (like a "TODO: Remove before 1.0 if no e2e test.")  We don't have the resources to just chase these tests by having issues filed (thank you @jsafrane!!).

**Comment by asalkeld** [comment]
Do we want to still have this bug open? 
If you look here: https://github.com/kubernetes/kubernetes/blob/master/test/e2e/volumes.go
NFS, Gluster, iSCSI, RBD, CephFS, Cinder and GCE PD tests exist.

Is it not better to create an issue for the remaining volume types so it is more obvious what is still to be done?

**Comment by nhlfr** [comment]
From what I see, the volume plugins which are missing the e2e test are:

* AWS EBS
* Azure File
* Fibre Channel
* Flex volume
* Flocker
* Git
* secret
* vSphere

I agree with @asalkeld that it'd be better to create separate issues for them.

**Comment by quinton-hoole** [comment]
@kubernetes/sig-storage

**Comment by childsb** [comment]
We should investigate federated testing as a solution to this.

**Comment by justinsb** [comment]
I believe we have e2e on storage now, right @saad-ali ?
