### ISSUE TITLE
CRD additionalPrinterColumns does not work with kubectl get SOMETHING -w

### ISSUE THREAD

**Issue by tatsuhiro-t** [kubernetes/kubernetes#66538]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind feature

**What happened**:

Without -w option, I can see that kubectl get SOMETHING shows additional columns for my CRD instances.  But with -w flag, just NAME and AGE are shown.

**What you expected to happen**:

additionalPrinterColumns should work with -w flag as well.

**How to reproduce it (as minimally and precisely as possible)**:

1. Define a CRD with additionalPrinterColumns and create its instance.
2. Get it using kubectl get SOMETHING -w

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:17:28Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:43:26Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by nikhita** [comment]
> Without -w option, I can see that kubectl get SOMETHING shows additional columns for my CRD instances. But with -w flag, just NAME and AGE are shown.

Can confirm that kubectl watch does not support `additionalPrinterColumns`. This happens because we pass each `*unstructured.Unstructured` object to `PrintObj`, instead of the `Table`.

https://github.com/kubernetes/kubernetes/blob/28b2b2128723d382ce241e9b67c7e875b9dfba78/pkg/kubectl/cmd/get/get.go#L542-L556

The printer checks if the object is `Unstructured` and then checks if it has a `handler` (handlers contain the `ColumnDefinition`) entry for this type (which it doesn't). We have entries only for built-in objects.

https://github.com/kubernetes/kubernetes/blob/28b2b2128723d382ce241e9b67c7e875b9dfba78/pkg/printers/internalversion/printers.go#L74-L76

https://github.com/kubernetes/kubernetes/blob/28b2b2128723d382ce241e9b67c7e875b9dfba78/pkg/printers/humanreadable.go#L297-L305

Since it doesn't find a handler entry, it uses the default handler (which contains just NAME and AGE).

https://github.com/kubernetes/kubernetes/blob/28b2b2128723d382ce241e9b67c7e875b9dfba78/pkg/printers/humanreadable.go#L320

https://github.com/kubernetes/kubernetes/blob/28b2b2128723d382ce241e9b67c7e875b9dfba78/pkg/printers/internalversion/printers.go#L434-L442

**Comment by nikhita** [comment]
Since `PrintObj` takes tables, we can get a `Table` response by doing something like this: https://github.com/nikhita/kubernetes/commit/630b8128144d63a364afcb13c935a4bb1f6622b2 and pass it down. However, this would print the columns correctly only for the _first time_. :/

```sh
kubectl get crontabs -w      
NAME                   SPEC      REPLICAS   AGE
my-new-cron-object     * * * *   15         29s
my-new-cron-object-2   * * * *   16         8s
NAME                   AGE
my-new-cron-object-3   0s
```

All other values would just show NAME and AGE because the watch event just gives us the `Object` (https://github.com/nikhita/kubernetes/commit/630b8128144d63a364afcb13c935a4bb1f6622b2#diff-7650a51eb24776a0115b675dd3842d63R598) and not a tabular response.

**Comment by nikhita** [comment]
@sttts @deads2k @liggitt any suggestions? ^^

**Comment by nikhita** [comment]
also from @smarterclayton's comment in https://github.com/kubernetes/kubernetes/pull/48033#discussion_r125116894:

> So I think the right solution here is not to pass individual unstructured down into print obj, but to pass tables down. And Get should be trying to convert responses from the server into tabular output. We don't want two different unstructured from a single list to have different columns, and PrintObj can now accept tables.

> So as the replacement for the previous dynamic logic, in 1.8 Get will take on the responsibility for turning server lists into Tables and passing them to PrintObj. That means that the default handler for unstructured won't be used anymore.

**Comment by sttts** [comment]
> All other values would just show NAME and AGE because the watch event just gives us the Object

Is it just missing Table support for the watch endpoint in apiextensions-apiserver?

**Comment by liggitt** [comment]
none of the watch endpoints support table output:

```
$ curl -k 'https://localhost:6443/api/v1/namespaces?limit=500&watch=true' -H "Accept: application/json;stream=watch;as=Table;v=v1beta1;g=meta.k8s.io"

{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "only the following media types are accepted: application/json;stream=watch, application/vnd.kubernetes.protobuf;stream=watch",
  "reason": "NotAcceptable",
  "code": 406
}
```

**Comment by liggitt** [comment]
additional considerations:
* some websocket clients (like browsers) are not able to set `Accept` headers on websocket requests, so we'd need to consider how a watcher indicates they want table output
* would we echo column headers with every event (could get very large), or send them once per watch stream? need to consider objects that can change their columns dynamically like CRDs (the watch handler might get built per version of CRD)

**Comment by liggitt** [comment]
cc @jwforres @spadgett

**Comment by jwforres** [comment]
/remove-lifecycle rotten

would still like to see this for improved CLI UX around CRDS

**Comment by damemi** [comment]
I've got a couple recent reports of this problem, and have been digging into it before finally finding this GH issue.

Like @nikhita said, it looks easy to add the `as=Table` header to the first request, but the following requests come from a watch. From catching up on this thread it seems that the watch endpoints don't support `as=Table`, is that still true?

If so, would it be possible to manually try to convert unstructured CRD objects returned from watch events to a `Table`? How (where) does the resource builder currently handle the table header, because it must be doing something similar right?

**Comment by liggitt** [comment]
watch supports table events in the 1.15 dev stream as of https://github.com/kubernetes/kubernetes/pull/71548

**Comment by liggitt** [comment]
kubectl still needs to be updated to request table output on watch (with a fallback to application/json, as today), and print table output on watch (with a fallback to object output, as today)
