### ISSUE TITLE
Jobs with deterministic pod names

### ISSUE THREAD

**Issue by liyinan926** [kubernetes/kubernetes#66620]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:

Within the community working on Apache Spark on Kubernetes, there's some recent discussions around high-availability (HA) support for Spark drivers, particularly for Spark streaming applications for which HA is critical. Currently the Spark driver runs in a bare pod and if it the pod dies for whatever reason, the application terminates. To address this, there's a proposal on using a Job of size 1 to run the driver, and PR https://github.com/apache/spark/pull/21067 was created to implement that. However, the following concern was raised: there is **no guarantee** that the Job controller **won't** spin up 2 driver pods when we only asked for 1. The exactly-once semantic is important for Spark as typically Spark is used for data processing and running more than one instance of the same application can cause race conditions around input/output data so is undesirable.

The problem of exactly-once semantic can be solved if Jobs have an option of using deterministic pod names such that a Job pod may be restarted if and only if an old pod instance with the same name has been successfully deleted.

**Anything else we need to know?**:

/sig apps
/sig big-data

@foxish @erikerlandson @mccheah @soltysh @kow3ns @erictune

**Comment by tnozicka** [comment]
> The exactly-once semantic is important for Spark as typically Spark is used for data processing and running more than one instance of the same application can cause race conditions around input/output data so is undesirable.

What are the reasons you can't use a Pod? Job with exactly once semantics seems like a Pod to me.

Also note that the exactly once semantic is not enforceable unless you accept that you can be blocked indefinitely when the node goes down or network splits. Or you timeout, making the exactly once guarantee best effort only.

(You can't delete the Pod if the node is down/split, otherwise the container could just be running anyways.)

**Comment by erikerlandson** [comment]
@tnozicka the pod `restartPolicy` doesn't quite cover the desired behaviors.  `Never` not right because it won't restart a streaming job that requires it.  A streaming job up in HA mode, but neither is `Always` because spark jobs _can_ terminate. IIRC `OnFailure` does not capture all possible container failure scenarios (and is a per-container failure response, not pod level) 
cc @liyinan926
