### ISSUE TITLE
CRD /scale labelSelectors shouldn't need to be under status

### ISSUE THREAD

**Issue by DirectXMan12** [kubernetes/kubernetes#66688]
Right now (in master, which is cef2d325ee1be894e883d63013f75cfac5cb1246 at the time of writing), if you implementing the scale subresource for a CRD, you have to point `labelSelectorPath` to a field under the CRD's `.status` field
(see the documentation for that field, plus https://github.com/kubernetes/kubernetes/blob/cef2d325ee1be894e883d63013f75cfac5cb1246/staging/src/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/validation/validation.go#L511)

This restriction doesn't make a ton of sense for objects that use labelSelector as part of their spec to discover the objects that they own (e.g. ReplicaSet), and contridicts the way labelSelector works for built-in objects (e.g. for ReplicaSets, it points at `.spec.labelSelector`).

We should remove this restriction.

cc @kubernetes/sig-api-machinery-bugs  @nikhita 

/kind bug

**Comment by sttts** [comment]
/assign @nikhita 

What does the design proposal say?

**Comment by nikhita** [comment]
> What does the design proposal say?

It doesn't really say anything about `labelSelectorPath` being under `.status`. I think this was decided during implementation because `autoscaling/v1.Scale` has the selector path under it's status:

https://github.com/kubernetes/kubernetes/blob/963adda7f9a58e7d8ef803e5052c07e9fc9da207/staging/src/k8s.io/api/autoscaling/v1/types.go#L133-L143

But I agree we should remove this restriction. Created https://github.com/kubernetes/kubernetes/pull/67824.

**Comment by enisoc** [comment]
Here's some background on why we expect this to always be in .status. Sorry this is so long; I didn't have time to make it shorter.

As @liggitt pointed out, ScaleStatus.Selector is not the same format of selector used in Spec.Selector, and this is intentional.

Spec.Selector is a human-readable object for easy manipulation by people. This form can and does vary across different objects and API versions. For example, compare Spec.Selector in ReplicationController and Service versus in ReplicaSet and StatefulSet. A machine looking at Spec.Selector in a given resource needs to know the schema of that resource to know how to interpret it.

ScaleStatus.Selector is a machine-readable, serialized form that is intended to abstract away the different forms of Spec.Selector. The contract of the /scale subresource is that a component looking at ScaleStatus must be able to send this opaque Selector value to the server without needing to understand it, and get back the right set of Pods.

In built-in resources that support /scale, we have [code that converts the form in the user-facing API into an opaque serialized form](https://sourcegraph.com/github.com/kubernetes/kubernetes@e567c791aabc058e012be8b33480e1cb1ce841fd/-/blob/pkg/registry/apps/replicaset/storage/storage.go#L217-239). Thanks to static typing, the code implicitly knows the schema of ReplicaSet.Spec.Selector and calls the right functions to convert it.

When designing /scale for CRD, we knew we needed an equivalent way to accomplish this conversion, but we couldn't justify the complexity of introducing a mechanism for apiextensions-apiserver to understand the schema of Spec.Selector and do the conversion for everyone. The general pattern for the rest of Scale was very simple: copy some fields from Spec into Scale.Spec, and copy some fields from Status into Scale.Status. The object returned by /scale could be considered a limited "view" onto part of the main object, just like /status represents another such view.

So we decided the cleanest solution is to ask the custom controller to do the conversion for us, since that controller always knows the schema and we don't always know it. In other words, the meaning of `labelSelectorPath` is not "where is your Spec.Selector?" but rather, "where in your Status do you report to us the serialized, version-agnostic form of your Spec.Selector?"

Given all this, it doesn't make sense for `labelSelectorPath` to point into Spec of the custom resource. Spec is where you put inputs to the controller, not where the controller puts outputs, and we certainly don't expect users to manually input both Spec.Selector and some hypothetical Spec.SerializedVersionAgnosticSelector which is in the format required for ScaleStatus.Selector.

**Comment by lavalamp** [comment]
/reopen
/lifecycle frozen

@jpbetz @liggitt @roycaihw This sounds like something that we might want to change for the v1 api.

**Comment by liggitt** [comment]
if we think we're going to loosen this eventually anyway, and it's only a validation change, I'm in favor of doing it before v1. We should make certain the API doc on this field explains the requirements for the field this points to
