### ISSUE TITLE
How to allow port range in kubernetes clusterIP kind service

### ISSUE THREAD

**Issue by ronakpandya7** [kubernetes/kubernetes#66700]
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG REPORT

> Uncomment only one, leave it on its own line:
>
> /kind bug

Hello,

We are using kubernetes cluster with version 1.10.3.
We want to allow range of ports in the ClusterIP kind kubernetes service.
But we don't know how to do this, it is not possible for us to allow each and every ports one by one in the service port section.

We want to allow hundreds of ports.

**Environment**:
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-12T14:26:04Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3+coreos.0", GitCommit:"f1b890dbbf11abe58280b3ffe17d67749f5ae70e", GitTreeState:"clean", BuildDate:"2018-05-21T17:27:17Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
- OS (e.g. from /etc/os-release):
```
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1745.7.0
VERSION_ID=1745.7.0
BUILD_ID=2018-06-14-0909
PRETTY_NAME="Container Linux by CoreOS 1745.7.0 (Rhyolite)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
```
- Kernel (e.g. `uname -a`):

`
Linux node1.example.com 4.14.48-coreos-r2 #1 SMP Thu Jun 14 08:23:03 UTC 2018 x86_64 Intel(R) Xeon(R) CPU L5640 @ 2.27GHz GenuineIntel GNU/Linux`

so can any one help us in this issue?

**Comment by ronakpandya7** [comment]
@kubernetes/sig-contributor-experience-bugs

**Comment by ronakpandya7** [comment]
Thanks for the reply @charrywanganthony 

PodSecurityPolicy is the cluster level resource, by creating it we can do whitelist the specific ports, but we have to give ports in our service too.

So our purpose will not solve.

Do you have any idea how we solve our purpose using PodSecurityPolicy?

Thanks in advance :)

**Comment by cblecker** [comment]
Please re-post your question to [Stack Overflow](http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases.

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans Stack Overflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search Stack Overflow for answers to similar questions, and also familiarize yourself with:

  * [user documentation](http://kubernetes.io/docs/)
  * [troubleshooting guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/)

Again, thanks for using Kubernetes.

The Kubernetes Team

---
/triage support
/close
