### ISSUE TITLE
deployment doesn't manage already created pod with appropriate labels

### ISSUE THREAD

**Issue by Hayyk** [kubernetes/kubernetes#66742]
/kind feature

**What happened**: created pod with "x" and "y" labels, then created deployment which actually must manage pods with "x" and "y" labels. set replicas: 1. but it doesn't take management of the pod created above and creates new one. I see 2 pods in deployments descriptions , the one that created earlier than the deployment is not active and there is a message "This pod matches the deployment's label selector but is not managed by it". 
Actually, I've just "migrated" from replication controller to deployment. When I was using replication controller instead of deployment it worked fine and was able to manage my already created pod. 

**What you expected to happen**: deployment could manage the pod that has been created before it and has the right labels to deployment be able to manage it.

**How to reproduce it (as minimally and precisely as possible)**: create pod, add label role: master. then create deployment with selector config matchLabels: role: master . deployment will not manage the already created pod. but if you create replication controller instead of deployment it will.

**Anything else we need to know?**:

**Environment**: kubernetes cluster on google cloud
- Kubernetes version (use `kubectl version`): 1.9.7-gke
- Cloud provider or hardware configuration: google cloud
- OS (e.g. from /etc/os-release): container OS
- Kernel (e.g. `uname -a`):
- Install tools: 
- Others:

**Comment by sadjad-chrono** [comment]
For anyone else who might still be curious about this question:

The deployment creates a replicaset which will ensure that a specified number of pod replicas are running at any given time. The auto-generated replicaset has the same labels in the "matchLabels" section as the deployment, plus a new label called "pod-template-hash." You can read about this new label in the documentation here:
[https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#pod-template-hash-label]

So, if you already have a pod with label x and have a deployment with "matchLabels" set to x, you shouldn't expect the deployment to manage that already existing pod because the underlying replicaset has both label x and pod-template-hash in its matchLabels (not only x).

**Comment by sadjadteh** [comment]
For anyone else who might still be curious about this question:

The deployment creates a replicaset which will ensure that a specified number of pod replicas are running at any given time. The auto-generated replicaset has the same labels in the "matchLabels" section as the deployment, plus a new label called "pod-template-hash." You can read about this label in the [documentation](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#pod-template-hash-label).

So, if you already have a pod with label _**x**_ and have a deployment with "matchLabels" set to _**x**_, you shouldn't expect the deployment to manage that already existing pod because the underlying replicaset has both label _**x**_ and _**pod-template-hash**_ in its matchLabels (not only _**x**_).
