### ISSUE TITLE
Failing Tests: [sig-api-machinery] AdmissionWebhook Should be able to deny pod and configmap creation

### ISSUE THREAD

**Issue by mohammedzee1000** [kubernetes/kubernetes#66776]
# Failing Jobs
[sig-release-master-upgrade#gce-1.10-master-upgrade-master](https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gce-1.10-master-upgrade-master)
# Failing Tests
[AdmissionWebhook Should be able to deny pod and configmap creation](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-new-master-upgrade-master/1681)
# Triage Results
[ci-kubernetes-e2e-gce-new-master-upgrade-master](https://storage.googleapis.com/k8s-gubernator/triage/index.html?job=ci-kubernetes-e2e-gce-new-master-upgrade-master)

/cc @tpepper @AishSundar 
/kind bug
/kind failing-test
/sig api-machinery
/priority important-soon
/milestone v1.12

**Comment by caesarxuchao** [comment]
Need to cherrypick https://github.com/kubernetes/kubernetes/pull/66616, to 1.10? I'll send a fix.

**Comment by tpepper** [comment]
Is there an associated test-infra change here to move the test to be from 1.11 to 1.12, and do we expect this test to start passing again as of the 1.11.2 release today?

**Comment by mohammedzee1000** [comment]
/reopen
These tests are still not green, what is the eta?

**Comment by caesarxuchao** [comment]
@krzyzacy plans to make the test-infra change to more forward tests to be from 1.11 to 1.12.

Also, after the test-infra change, the cherrypick #66941 needs to be merged into 1.11 branch to fix the test.

**Comment by tpepper** [comment]
Status check @krzyzacy ?

**Comment by caesarxuchao** [comment]
@tpepper https://github.com/kubernetes/kubernetes/issues/66776#issuecomment-412596363 should have been fixed, stable-1 points to 1.11 now, according to the test-infra [readme](https://github.com/kubernetes/test-infra#create-a-new-job).

The test is still failing because the last test run was earlier than the merge of the [fix](https://github.com/kubernetes/kubernetes/pull/66941). I expect it to be passing in the next run. Feel free to ping me on slack if it still fails..

**Comment by tpepper** [comment]
Confirmed test is now passing.
/close
