### ISSUE TITLE
Issues a single Allocate gRPC call per pod in kubelet device manager 

### ISSUE THREAD

**Issue by jiayingz** [kubernetes/kubernetes#66804]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
/kind feature

**What happened**:

**What you expected to happen**:
Basically implements this TODO in device manager allocateContainerResources():
"TODO: refactor this part of code to just append a ContainerAllocationRequest
in a passed in AllocateRequest pointer, and issues a single Allocate call per pod."

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by tianshapjq** [comment]
Hi~ I'm willing to do this job. Is anyone already working on this?

**Comment by jiayingz** [comment]
Hi @tianshapjq I am not aware anyone is working on this right now. Feel free to grab it. Thanks!

**Comment by tianshapjq** [comment]
@jiayingz hi~ I commit a pr about this issue, would you pls review that? What I concern most is about the params to pass to Allocate() interface, because that would change the compatability with v1beta1, which is not great for the beta version IMO.
please leave your notes and I will recommit ASAP :)
