### ISSUE TITLE
Misleading "Pending" status is returned when pod fails with "Error: ErrImagePull"

### ISSUE THREAD

**Issue by nmousavi** [kubernetes/kubernetes#66828]
If pod fails in pulling a docker image, we have inconsistency in pod status.

2) kubectl get pods

NAME  READY     STATUS             RESTARTS   AGE
my_pod_1  0/1       ErrImagePull   0          59m
my_pod_2  0/1       ImagePullBackOff   0          39m

2) kubectl get pod my_pod_1 -o jsonpath={.status.phase}
Pending

3) kubectl get pod my_pod_2 -o jsonpath={.status.phase}
Pending

Another issue (beside the inconsistency): pod keeps trying to pull image even with restartPolicy set to Never? Why isn't it considered as failure, and thus failure status?

**Comment by adombeck** [comment]
/reopen

Same issue here, it would be great if the status would reflect that the pod failed.

**Comment by yashvardhan-kukreja** [comment]
would like to pick this up

**Comment by yashvardhan-kukreja** [comment]
@troy0820 can I pick this up

**Comment by troy0820** [comment]
@yashvardhan-kukreja This issue is closed and the comments from issue #96186 discuss the possible resolution for this and that issue.

**Comment by warisamir** [comment]
hey @nmousavi i am currently working on a project related to microservices , i am facing this since a week longer i humble all of you si there any way to make this pod running please help 
![image](https://github.com/kubernetes/kubernetes/assets/77074869/f3a90b7a-44cc-4fdf-9647-7eddb33b456f)
![image](https://github.com/kubernetes/kubernetes/assets/77074869/c4671ac5-2988-4f87-a046-c6da64e9894a)
