### ISSUE TITLE
ubuntu-cluster setup does not include DNS

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#6704]
@mazswojejzony DNS is a pretty important part of kubernetes - it really ought to be started when the cluster comes up.

**Comment by WIZARD-CXY** [comment]
@thockin I am the maintainer of k8s deployment of ubuntu.I have already include dns deployment with v0.15.0.Once this pr is merged https://github.com/GoogleCloudPlatform/kubernetes/pull/8047, the dns should work well with v0.15.0 k8s. Since the higher k8s version need dns token to successfully deploy dns service,and as far as I know only gce/gke can use saltstack to do this now, I am working on it now.
