### ISSUE TITLE
Dry-run: Add more e2e tests

### ISSUE THREAD

**Issue by apelisse** [kubernetes/kubernetes#67128]
Dry-run needs many e2e tests to validate that nothing is persisted change when the dry-run flag is provided.

Things that can be done (and/or to be discussed):
- [ ] Test pod-binding, since it's asynchronous
- [ ] Add tests in [resttest.go](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/registry/rest/resttest/resttest.go) (#67136)
- [ ] Add tests similar to [etcd_storage_path_test.go](https://github.com/kubernetes/kubernetes/blob/master/test/integration/etcd/etcd_storage_path_test.go) (https://github.com/kubernetes/kubernetes/pull/66466#issuecomment-409343401)

@deads2k @liggitt @lavalamp @jennybuckley

**Comment by lavalamp** [comment]
Let's talk about this, why do we need e2e tests instead of integration tests? I can't think of anything additional we get from the e2e environment?

I think we need to test, in integration tests:
* CRD: one cluster scoped, one namespace scoped, with each having multiple versions -- we don't get additional certainty from testing additional CRDs. 
* One APIService of an extension apiserver that supports dry run, one that doesn't (is an old version)
* all built in types.
* one mutating and one validating webhook that support dry run, one each that don't.

We should test POST, PUT, PATCH.

It'd be OK to have an e2e test that verifies that exec, attach, proxy, portforward are all blocked by dry-run, since those things can't work in integration tests at all. That's the only use for an e2e test I can think of.

**Comment by lavalamp** [comment]
@deads2k / @liggitt did one of you have some specific reason for wanting e2e tests?

**Comment by deads2k** [comment]
> @deads2k / @liggitt did one of you have some specific reason for wanting e2e tests?

Not from me.  I think that the integration test that checks all resources (including scale, status, and binding)  via discovery like the etc storage test is requirement for turning it on the through the rest handler, but that test isn't helped by being an e2e test.

**Comment by liggitt** [comment]
as far as I know, we don't have working extension apiservers in integration tests (don't have kubelets/pods), so that bit would have to be exercised via e2e as well.

agree on exercising the subresources as well, but I think all the built-in types and CRDs could be exercised via integration like the etcd storage test does.

**Comment by jennybuckley** [comment]
Will we ever want this as a conformance test?

**Comment by lavalamp** [comment]
Re: extension apiservers: you should be able to make an APIService object &
manual service w/ endpoint that references another in-memory server. No one
has done it, I think, but it'd be way faster of a test than an e2e, I
think? I don't object to doing that as an e2e test for expediency.

Jenny, good point, we will need this to be conformance tested at some
point, sigh.

Is there any chance we can write a test that can run against an
integration-created apiserver and also against an existing cluster? I've
been wanting to write tests that work like that for years at this point :(
