### ISSUE TITLE
Removing spec.replicas of the Deployment resets replicas count to single replica

### ISSUE THREAD

**Issue by kirs** [kubernetes/kubernetes#67135]
/kind bug

**What happened**:

A Deployment spec with hardcoded `replicas` parameter was applied:

```yml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: critical-service
  name: critical-service
spec:
  replicas: 100
  ...
```

Later, we've decided to let the `replicas` value be dynamic to be able to manage it with `kubectl scale`, without changing YAML every time. So we applied another spec, without the `replicas` key:

```diff
diff --git a/deployment.yml b/deployment.yml
index 339531d..f5a3e5f 100644
--- a/deployment.yml
+++ b/deployment.yml
@@ -5,5 +5,4 @@ metadata:
     name: critical-service
   name: critical-service
 spec:
-  replicas: 100
   ...
```

After the updated spec was applied, Kubernetes ignored existing `replicas` count and scaled the RS down to 1 replica. This was a very unexpected behaviour to scale down an existing deployment.

**What you expected to happen**:

We expected that skipping `replicas` line in YAML would **preserve** existing replicas count, but in fact it reset all of them to default value which is `1` replicas. This effectively scaled lack of capacity and a severe service distruption to a service that had > 1000 replicas.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a deployment from a YAML file with hardcoded `replicas` count, with the value above `1`
2. Remove `replicas` line from the YAML and apply the file
3. See ReplicaSet being scaled down to `1` replicas, instead of preserving existing value above `1`

**Anything else we need to know?**:

**For us this feels that scaling down by default is an extremely dangerous behaviour.** It makes sense to use the default of 1 replica for new resources, but not for existing resources that have thousands of replicas running.

**Environment**:

- Kubernetes version: v1.10.5-gke.3
- Cloud provider or hardware configuration: GKE

**Comment by liggitt** [comment]
defaults are applied for missing values on both create and update.

to let the replicas field be ignored by apply, omit it from the initial applied manifest

to stop replicas from being managed by apply, use `kubectl apply edit-last-applied` (or `kubectl apply set-last-applied`) to remove the replicas field from the saved "last applied" state prior to applying the new manifest to keep `apply` from removing the replicas field (which makes the apiserver default back to 1)

/close

**Comment by kirs** [comment]
@liggitt thanks for the tip! `apply set-last-applied` is indeed helpful in this case.

I understand that it comes from the default value of `1` being set because `replicas` line is missing.

My intention for opening this issue was more about starting a conversation about what's the best default behaviour for Kubernetes. 

As for me and for my colleagues, it seems like scaling down by default is an _extremely dangerous_ behaviour. It makes sense to use the default of 1 replica for new resources, but Kubernetes should not scale down existing resources that have thousands of replicas live.

I'll be looking forward to make a change for ReplicaSet controller to make this behaviour slightly safer and a bit less unexpected. Let me know what you think!

**Comment by ravihugo** [comment]
Just got hit by this too. Our CI environment does not currently set the replica value because we would rather manage this separately. So now it looks like we'll need to start managing this in the CI environment. Also the suggested work-around seems a bit strange. Is that equivalent of the first apply setting the replica size to 1 and then re-apply it back to 100 (for example).

Wouldn't that massively affect what the rolling update would look like?

**Comment by chrissound** [comment]
This seems to be in  contradiction to what `kubectl apply` is documented as.  It (replica count) also does not show up as a change when using `kubectl diff -f`...

**Comment by rwenz3l** [comment]
Stumbled upon this today and I also find it difficult to handle. I've started to deploy services with 2, 8 and 20 replicas in certain places and just resetting them to 1 when removing the line seems dangerous to me as well. I always check with `kubectl diff -f ...` before `apply`ing.. but changing with the `kubectl apply set-last-applied` is annoying as well. I'd love to get a different behavior/flag/whatever. Maybe at least a small snippet for batch-editing the deployments.

**Comment by collimarco** [comment]
I also find [this behavior](https://technologyconversations.com/2018/10/10/to-replicas-or-not-to-replicas-in-kubernetes-deployments-and-statefulsets/) extremely confusing and against the declarative approach of Kubernetes.

**Maybe a solution would be to have a `replicas: auto` instead of leaving out the key/value pair?** In this way K8s knows that we want to change that option and not keep the key/value pair of a previous `apply`.

**Comment by ayk33** [comment]
Is there a reason this issue was closed? This behavior seems very troubling.. Running a deployment with 300+ pods and losing them instantly can cause some serious issues.

**Comment by mhash17** [comment]
I don't get it. What's the problem here? you give k8s no number (replicas) - k8s falls back to default (1). You hardcode replicas, delete them afterwards and expect k8s to have remembered your replicas from before to further work with that number - that is illogical. Either you tell k8s to handle it or you handle it yourself. But you want k8s to tidy up your jam session from before - there is nothing "dangerous" as stated few times here. Some nontechnical issues have to be managed by humans (who/what should have the final say about replicas - and all have to know that)- "try this and that" should be part of dev and not prod - in that case you would't call it dangerous. seeing something "dangerous" is nothing but: you don't understand a concept - you think you would use it in some way, which would then expose the system to some unexpected situtation - you call it with an emotion: dangerous. It isn't, it's you (sorry)!

**Comment by EronWright** [comment]
Here's some documentation on how to handle this situation where you want to safely transfer ownership of the replicas field to an autoscaler:
https://kubernetes.io/docs/reference/using-api/server-side-apply/#transferring-ownership

To recap why the replicas was being reset to one, it is because you took ownership of the field in the first step, and when you cleared it, nobody was left as the owner and so the default value was applied.  You were "unsetting" the value.
In CSA mode, the "last-applied-configuration" annotation tracks ownership, and that's why one must edit it to relinquish ownership as mentioned [here](https://github.com/kubernetes/kubernetes/issues/67135#issuecomment-411429723).
In SSA mode, ownership is tracked on the server via `.metadata.managedFields`, and must be transferred to another owner as described in the above link. Either way, ownership must be transferred beforehand.

**Comment by Zeouterlimits** [comment]
> I also find [this behavior](https://technologyconversations.com/2018/10/10/to-replicas-or-not-to-replicas-in-kubernetes-deployments-and-statefulsets/) extremely confusing and against the declarative approach of Kubernetes.

Maybe a solution would be to have a replicas: auto instead of leaving out the key/value pair? In this way K8s knows that we want to change that option and not keep the key/value pair of a previous apply.

This is a great idea by @collimarco

**Comment by younsl** [comment]
I'd like to share a recent production incident that demonstrates the severity of this issue in real-world scenarios.

<details>
<summary>Production Incident Report - Dangerous Replica Reset Behavior</summary>

## Background

initially encountered pod count yo-yo effects described in [issue #25238](https://github.com/kubernetes/kubernetes/issues/25238), where deployment updates with HPA caused replicas to jump unexpectedly (e.g., from 3 to 9, then scale down to 6, then back to HPA target). To resolve this replicas flapping behavior, we decided to [remove spec.replicas from our Deployment manifests](https://argo-cd.readthedocs.io/en/stable/user-guide/best_practices/#leaving-room-for-imperativeness) when HPA is enabled.

However, this solution led us directly into the dangerous behavior described in this issue - we avoided one problem only to encounter a much more severe single replica reset issue.

## Incident Timeline:

1. Initial State: Production deployment was running with spec.replicas: 10
2. Configuration Change: Applied conditional logic to remove spec.replicas when HPA is enabled in deployment template

```yaml
# my-app/templates/deployment.yaml
spec:
  # Do not include replicas in the manifests if you want replicas to be controlled by HPA
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
```

3. Manual Sync: Both HPA and Deployment resources were managed within a single ArgoCD Application. Manually triggered sync in ArgoCD UI to apply the changes.
4. Critical Issue: spec.replicas was reset from 10 to 1 (default value)
5. Service Disruption: 9 of 10 pods were immediately terminated, leaving only 1 pod running
6. Recovery: HPA eventually scaled back from 1 to 10 pods, but significant downtime occurred

</details>

What would be the best approach to prevent this dangerous behavior? This unexpected behavior is very horrible in production workloads. Can't imagine if this had been a mission-critical production workload running 100 replicas.

**Comment by alexgo84** [comment]
Since this surprising behavior is still taking place, I'm resorting to use heuristics for setting the replicas explicitly, even when HPA is enabled.
A solution, or at least the reopening this issue, would be most welcome!

**Comment by pradudev** [comment]
We use Kyverno policy to dynamically patch the replicas filed of the deployment based on the HPA current replica count.

**Comment by josegonzalez** [comment]
@pradudev do you have an example for that policy?

**Comment by ahjert** [comment]
We ran into this exact issue when trying to hand off replica management to HPA. Our setup uses `kubectl apply` (not Helm), so the `last-applied-configuration` annotation is the source of truth for field diffing.

Solution: Before removing `replicas` from your manifests, strip it from the annotation on each live Deployment first:

```sh
# interactive, per deployment
kubectl -n <namespace> apply edit-last-applied deployment/<name>
# or non-interactively
kubectl -n <namespace> get deployment <name> \
  -o jsonpath='{.metadata.annotations.kubectl\.kubernetes\.io/last-applied-configuration}' \
  | jq 'del(.spec.replicas)' \
  | xargs -0 kubectl -n <namespace> annotate deployment <name> \
    kubectl.kubernetes.io/last-applied-configuration= --overwrite
```

Then remove `replicas` from your manifests and deploy normally. Since `kubectl apply` diffs against the annotation, no `replicas: null` PATCH is sent and the live count is preserved.

Verify with:

```sh
kubectl -n <namespace> get deployment <name> \
  -o jsonpath='{.metadata.annotations.kubectl\.kubernetes\.io/last-applied-configuration}' \
  | jq .spec.replicas
# should return null/empty
```

For Helm users, [max0ne/helm-omit-replicas-for-hpa](https://github.com/max0ne/helm-omit-replicas-for-hpa) applies the same concept against Helm's release secrets.
