### ISSUE TITLE
TestVolumeBindingRescheduling `out of sync; retrying` flakes

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#67260]
seeing `out of sync; retrying` errors in TestVolumeBindingRescheduling:

http://storage.googleapis.com/k8s-metrics/flakes-latest.json shows TestVolumeBindingRescheduling in the top 3 flakes for its job

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/67207/pull-kubernetes-integration/22583/

```
E0810 14:10:47.907031   30434 factory.go:1409] Error scheduling volume-scheduling1250e95d-9ca7-11e8-ad13-0242ac110002/pod-reschedule-onclassadd-static: v1.PersistentVolume "pv-reschedule-onclassadd-static" is out of sync; retrying
E0810 14:10:47.908643   30434 factory.go:1409] Error scheduling volume-scheduling1250e95d-9ca7-11e8-ad13-0242ac110002/pod-reschedule-onclassadd-static: v1.PersistentVolume "pv-reschedule-onclassadd-static" is out of sync; retrying
E0810 14:10:47.910120   30434 factory.go:1409] Error scheduling volume-scheduling1250e95d-9ca7-11e8-ad13-0242ac110002/pod-reschedule-onclassadd-static: v1.PersistentVolume "pv-reschedule-onclassadd-static" is out of sync; retrying
E0810 14:10:47.912168   30434 factory.go:1409] Error scheduling volume-scheduling1250e95d-9ca7-11e8-ad13-0242ac110002/pod-reschedule-onclassadd-static: v1.PersistentVolume "pv-reschedule-onclassadd-static" is out of sync; retrying
I0810 14:10:47.928002   30434 pv_controller_base.go:287] Shutting down persistent volume controller
I0810 14:10:47.928033   30434 pv_controller_base.go:398] claim worker queue shutting down
I0810 14:10:47.928574   30434 pv_controller_base.go:341] volume worker queue shutting down
--- FAIL: TestVolumeBindingRescheduling (49.76s)
	volume_binding_test.go:344: Failed to schedule Pod "pod-reschedule-onclassadd-static": timed out waiting for the condition
```

@kubernetes/sig-storage-test-failures

**Comment by lichuqiang** [comment]
I'll take a look :)
And @cofyc might have knowledge of the case

**Comment by cofyc** [comment]
/assign
I'll take a look too, I wrote this test.

**Comment by cofyc** [comment]
Perhaps because invalidating predicate cache invalidates latest cache, but in-flight `VolumeBindingChecker.predicate` goroutine may write stale result into cache again.

Possible ways to fix:

- Add flag to indicate whether we invalidated cache when predicate check was in flight, like [PriorityQueue.receivedMoveRequest](https://github.com/kubernetes/kubernetes/blob/v1.12.0-alpha.1/pkg/scheduler/core/scheduling_queue.go#L176). When updating cache, skip if this flag is true.
- [Skip if PVs are stale](https://github.com/kubernetes/kubernetes/blob/v1.12.0-alpha.1/pkg/scheduler/core/equivalence/eqivalence.go#L249) when updating cache.

I'll try to fix it next week.

**Comment by misterikkit** [comment]
@bsalamat and I chatted about this, and we think we identified the root of the problem.

This is the same bug as https://github.com/kubernetes/kubernetes/issues/62921, and we now realize that the fix for that had holes in it. Specifically, we rely on the scheduler cache `NodeInfo` to be stale when we check whether to write data into the eCache.

For this bug, events for PV, PVC, and SC are invalidating eCache entries **without modifying the scheduler cache**. As a result, the `NodeInfo` never becomes stale.

https://github.com/kubernetes/kubernetes/pull/67308 is the right approach, but needs a number of changes. I will put those comments on the PR.
