### ISSUE TITLE
test/integration/daemonset TestLaunchWithHashCollision is flaking

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubernetes#67273]
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/batch/pull-kubernetes-integration/22609/

```
[]v1.DaemonSetCondition(nil)}}: Operation cannot be fulfilled on daemonsets.apps "foo": the object has been modified; please apply your changes to the latest version and try again
I0810 18:48:44.078211   28282 daemon_controller.go:265] Shutting down daemon sets controller
daemonset_test.go:880: Failed to update DaemonSet: Operation cannot be fulfilled on daemonsets.apps "foo": the object has been modified; please apply your changes to the latest version and try again
```

/sig apps
/priority critical-urgent
/assign @mortent

PR that added the test:
https://github.com/kubernetes/kubernetes/pull/66476
/cc @janetkuo @mikedanese

**Comment by janetkuo** [comment]
The test is still flaky, but with different symptom: 
```
daemonset_test.go:420: Expected collisionCount to be 1, but found 2
```
An example flake: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/67406/pull-kubernetes-integration/23378/

It's likely because the collision count was updated in a previous sync loop, but the `ds` in the cache store hasn't been updated and we used a stale collision count while calculating the new hash:
https://github.com/kubernetes/kubernetes/blob/939f08a24eb75aec246073ec119fd0141e7e4c1f/pkg/controller/daemon/update.go#L318

/assign
