### ISSUE TITLE
Error connecting to cluster when certificate is added to OSX keychain

### ISSUE THREAD

**Issue by dmfenton** [kubernetes/kubernetes#67345]
/kind bug

**What happened**:

Attempting to run `kubectl get pods` against a cluster when the certificate has been added as trusted to the OSX keychain receive the following error:

`Unable to connect to the server: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "kubernetes")`

**What you expected to happen**:

I expected to see a list of pods.

**How to reproduce it (as minimally and precisely as possible)**:

- add the kubernetes API cert to OSX keychain
- create and use a kube context that **does not** point to certificate authority data
- run `kubectl get pods`

**Anything else we need to know?**:

This problem does not occur on kubectl v1.9.6

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-18T11:37:06Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
- Cloud provider or hardware configuration:
AWS
- OS (e.g. from /etc/os-release):
Darwin
- Kernel (e.g. `uname -a`):
Darwin 17.6.0 Darwin Kernel Version 17.6.0: Tue May  8 15:22:16 PDT 2018; root:xnu-4570.61.1~1/RELEASE_X86_64 x86_64
- Install tools:
- Others:

**Comment by dmfenton** [comment]
@kubernetes/sig-cli

**Comment by dmfenton** [comment]
Hello, has anyone been able to look at this issue yet?

**Comment by dmfenton** [comment]
Any updates?

**Comment by structurefall** [comment]
I'm having a very similar issue. Due to some complexities of my environment, I need kubectl to hit a proxy with an internally-signed cert whose CA is trusted in the keychain, which was resulting in the following:

`$ kubectl get pods
Unable to connect to the server: x509: certificate signed by unknown authority`

I'm getting around it for now by printing the CA with `security find-certificate -p` converted to base64 and then using that as `certificate-authority-data`, but it's very awkward.

Here's my environment:

**Environment:**

- Kubernetes version (use kubectl version):
  Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.3", GitCommit:"435f92c719f279a3a67808c80521ea17d5715c66", GitTreeState:"clean", BuildDate:"2018-11-27T01:15:02Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"darwin/amd64"}
- Cloud provider or hardware configuration:
- GKE
- OS (e.g. from /etc/os-release):
- Darwin
- Kernel (e.g. uname -a):
- Darwin 17.7.0 Darwin Kernel Version 17.7.0: Wed Oct 10 23:06:14 PDT 2018; root:xnu-4570.71.13~1/RELEASE_X86_64 x86_64

**Comment by dmfenton** [comment]
@soltysh @seans3 Is there anything I can do to help this issue move towards resolution? Thank you.

**Comment by Sicaine** [comment]
Same issue here.

I would like to be able to access a GKE Master and need something in between as the private gcp vpc will not be routed through a gcp router (i need something inbetween).

I put our company ca into a file under .kube/company.crt and reference it inside my .kube/config with certificate-authority: <filepath>. It is working but feels strange.

It would be great to be able to reconfigure the master to add specific IP addresses as SAN to use a TCP LB and not having to terminat the TLS.

Or that kubectl allows to validate server certs against the trust chain on the developer machine.

**Comment by soltysh** [comment]
I'm open to any proposals/fixes, I'm personally working on a linux so I won't be of any help, sorry.

**Comment by Sicaine** [comment]
@soltysh i would propose some default mechanism to check the server certificate based on the default trust store of the users os. Very similiar to what browsers do.

**Comment by soltysh** [comment]
@Sicaine go for it

**Comment by mshahat** [comment]
@dmfenton Hi Daniel, have you every figured this out? I'm trying to know what ca store kubectl refers to? and whether ca in keychain on macOS could be used.   Cheers,
