### ISSUE TITLE
Add ability to include intermediates in CSR-issued certificates

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#67436]
Currently, if an intermediate CA is used to sign certs, the csr signing controller does not include the intermediate chain in the CSR status. This means that anything requesting a cert via the CSR API has to know the intermediates themselves (unlikely) or anything interacting with a component presenting or serving using an intermediate-issued cert must know about the intermediate issuer.

Ideally, we would have a way to:
1. indicate to the signing controller an optional intermediate bundle to include
2. include intermediates in the CSR status (appending to the existing `Certificate` field, having a separate `Intermediates []byte` field, etc)

/kind feature
/sig auth
/cc @mikedanese

**Comment by liggitt** [comment]
@sdodson

**Comment by sdodson** [comment]
CC @mrogers950

**Comment by mikedanese** [comment]
We'd probably have to change less if we just added it to `Certificates`. I assume that since no one reported this yet, no one is using a depth > 2 PKI spanning multiple clusters to provision node certs. Is that what you intend to do or do you intend to use the certificates API for something else? Those certs aren't going to be constrained to the cluster, so beware.

**Comment by liggitt** [comment]
folded into CSR v1 issue https://github.com/kubernetes/kubernetes/issues/69836

/close
