### ISSUE TITLE
PVC finalizers should be removed on pod deletion if the node that pod running on is down

### ISSUE THREAD

**Issue by NickrenREN** [kubernetes/kubernetes#67466]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

If pod is requested to be deleted, but node is down, PVC finalizer will never be removed

**What you expected to happen**:

If pod is requested to be deleted, but node is down, PVC finalizer should be removed if there are no other pods referencing it.

/assign
/sig storage

cc @msau42 @jsafrane @pospispa

**Comment by msau42** [comment]
When node/kubelet is down and is unable to update the Pod object, we can't be 100% sure that the volumes have been unmounted, and that it would be safe to delete.

In https://github.com/kubernetes/kubernetes/issues/65552#issuecomment-413232259, you suggested an approach to check for podTerminationGracePeriod.  I believe this grace period only determines the time period when kubelet should start force killing containers, and has the same issue that volumes may still be mounted at this time.

How about following a similar approach as attach/detach controller, and using the same force detach grace period (which is 5 minutes)?

@verult has also been brainstorming ideas on how to handle this node/kubelet down scenario to actually force delete Pods.

cc @saad-ali

**Comment by orainxiong** [comment]
@msau42 

> how to handle this node/kubelet down scenario to actually force delete Pods

IMO, from the stateful application(especially database just like MySQL) perspective, we should clarify the differences between **node is down** and **kubelet is down**. 

In the case of **kubelet is down**, the present controller-planes(statefulset for example) can't guarantee **at most one** pod semantic, that means it very likely cause data corruption due to more than one pod instances access the backend volumes at the same time. 

> The original pod is still running on the unavailable node, and then the newly created pod is scheduled to another available node and start running.

Practically, it is very hard to figure out the exact reason which causes **Node Condition Unknown**, probably **kubelet is down** or **node is down** or **network partition** or that sort of things.

I consider a fencing policy should be introduced to guarantee **at most one** pod semantic. 

As far as I know, probably we could accomplish the fencing policy by the following logic : 

* In terms of controller side: When **FenceController**, a newly introduced controller, observes the status of the node is unknown, and then it should choose one of the following workarounds to perform hard eviction operation to ensure all pods running on this node are actually force deleted. 
  1. Power off unreachable node by IPMI;
  2. Blocking the unavailable node access backend storage system;

* In terms of worker side: When **kubelet** observe lost access to Kube API server over a threshold time duration, and then it is supposed to roughly power off itself to protect volume, just like clustered stateful software (Oracle RAC for example)once implemented.
