### ISSUE TITLE
Minikube start with error getting Pods with label selector “k8s-app=kube-proxy” on win10

### ISSUE THREAD

**Issue by wuwdd** [kubernetes/kubernetes#67533]
/help-wanted
/sig network
/sig windows
/sig VMware
I want to build up the kubernetes environment on my local win10 system.

Installed virtualBox and minikube on my win10 laptop.
<img width="230" alt="wechat image_20180817150958" src="https://user-images.githubusercontent.com/33924918/44259305-b94add80-a243-11e8-823f-795d36a1b689.png">

Then try to start the cluster by follow command:

  >  minikube start --vm-driver=virtualbox --logtostderr

After "Starting cluster components...", it says error as below 
`**I0817 15:12:23.987899   16328 kubernetes.go:119] error getting Pods with label selector "k8s-app=kube-proxy" [Get https://192.168.99.100:8443/api/v1/namespaces/kube-system/pods?labelSelector=k8s-app%3Dkube-proxy: dial tcp 192.168.99.100:8443: connectex: No connection could be made because the target machine actively refused it.]**`

<img width="953" alt="wechat image_20180817151400" src="https://user-images.githubusercontent.com/33924918/44259376-e39c9b00-a243-11e8-8189-40b15a98eccb.png">
<img width="955" alt="wechat image_20180817151500" src="https://user-images.githubusercontent.com/33924918/44259380-e5665e80-a243-11e8-8fd5-05a12d672360.png">

Can somebody help?Thanks very much!

**Comment by wuwdd** [comment]
@kubernetes/sig-contributor-experience-cluster-ops

**Comment by sj0509** [comment]
Hi,
How did you resolve this issue ? I'm getting the same error - am looking at more detailed logs, I see it failing to get kube-proxy

I0204 10:38:55.638449   17396 kubernetes.go:119] error getting Pods with label selector "k8s-app=kube-proxy" [Get https://10.6.104.30:8443/api/v1/namespaces/kube-system/pods?labelSelector=k8s-app%3Dkube-proxy: Service Unavailable]
I0204 10:38:56.138119   17396 round_trippers.go:383] GET https://10.6.104.30:8443/api/v1/namespaces/kube-system/pods?labelSelector=k8s-app%3Dkube-proxy
I0204 10:38:56.138119   17396 round_trippers.go:390] Request Headers:
I0204 10:38:56.139837   17396 round_trippers.go:393]     Accept: application/json, */*
I0204 10:38:56.141810   17396 round_trippers.go:393]     User-Agent: minikube.exe/v1.10.0 (windows/amd64) kubernetes/fc32d2f
I0204 10:38:57.138116   17396 round_trippers.go:408] Response Status:  in 995 milliseconds


Am behind a firewall, so that may be affecting this, or even an anti-virus. But need some leads on what to do to resolve that. 

Thanks.

**Comment by wuwdd** [comment]
sorry for reply so late.I solved this issue by remove the current minikube and follow the https://blog.csdn.net/Maggie_up/article/details/80738331 to start minikube by using "Docker Toolbox"

**Comment by sj0509** [comment]
Hi,

Thanks for the response. I ended up doing the same thing :). Uninstalled minikube, and went with the version of Kubernetes that comes packaged with "Docker for Windows"
