### ISSUE TITLE
k8s 1.11 custom object resource version changes on no-op status patch

### ISSUE THREAD

**Issue by juliantaylor** [kubernetes/kubernetes#67541]
> /kind bug

**What happened**:

In kubernetes 1.11.2 patching a status subresource of a custom object with a body that effectively does nothing increases the resource version of the object and triggers modify events.

In kubernetes 1.10.6 with the custom object subresources feature gate enabled this did not happen.

Maybe this is an intentional change due to the custom object subresources becoming beta, but I did not find this documented and it also does not not happen when patching the status of non custom objects (e.g. services) which is odd.

**What you expected to happen**:
Applying a patch that does not change the resource the object resource version should not change and no modify event be triggered.

**How to reproduce it (as minimally and precisely as possible)**:
Executing a merge patch (application/merge-patch+json) against a custom object changing the status multiple times will increase the resource version each time even when the object does not change.
E.g. via the python client:
api.patch_namespaced_custom_object_status(group=GROUP, version=version, plural=RESOURCE_NAME, namespace=namespace, name=object, body={"status": {"test": "data"}})

**Anything else we need to know?**:

**Environment**:
kubernetes version:
```
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:08:19Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by nikhita** [comment]
Thanks for the bug report, @juliantaylor!

> patching a status subresource of a custom object with a body that effectively does nothing increases the resource version of the object and triggers modify events.

This is not only for patching the status subresource of a custom resource. It occurs on even the scale subresource and the main resource itself.

This regression occurs due to https://github.com/kubernetes/kubernetes/pull/64267. Specifically, because of the json marshalling and unmarshalling we do. If we remove this condition (at all places it occurs), it works fine again:

https://github.com/kubernetes/kubernetes/blob/b44a768052d7cb1f6e9c373ad463f2ed6a25ba35/staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/customresource_handler.go#L744-L748

Without this, the object would be:

```
&unstructured.Unstructured{Object:map[string]interface {}{"kind":"WishIHadChosenNoxu", "metadata":map[string]interface {}{"clusterName":"", "creationTimestamp":"2018-08-18T11:11:38Z", "generation":1, "name":"foo", "namespace":"", "resourceVersion":"8", "selfLink":"", "uid":"7a563c76-a2d7-11e8-8780-54e1ad9de0be"}, "num":map[string]interface {}{"num2":999, "num1":9223372036854775807}, "apiVersion":"mygroup.example.com/v1beta1", "content":map[string]interface {}{"key":"value"}}}
```

With this, the object is:

```
&unstructured.Unstructured{Object:map[string]interface {}{"num":map[string]interface {}{"num1":9223372036854775807, "num2":999}, "apiVersion":"mygroup.example.com/v1beta1", "content":map[string]interface {}{"key":"value"}, "kind":"WishIHadChosenNoxu", "metadata":map[string]interface {}{"generation":1, "creationTimestamp":"2018-08-18T11:13:34Z", "name":"foo", "uid":"bf4111db-a2d7-11e8-828e-54e1ad9de0be", "resourceVersion":"9"}}}
```

Because of the round trip marshalling+unmarshalling, we loose the `omitempty` terms like `"clusterName":""`, etc. It looks like due to these differences, the objects are treated as differently and the resource version is incremented.

However, I am still a little suspicious of this reason - because I think the resource version is incremented by checking semantic equality and if so, this should not happen... (taking another look into this)

**Comment by liggitt** [comment]
> I think the resource version is incremented by checking semantic equality and if so, this should not happen... (taking another look into this)

Resource version is incremented every time data is written to etcd. 

Writes to etcd short-circuit if the bytes being written are identical to the bytes already present. It is not a semantic equality check.

**Comment by liggitt** [comment]
We have a test for native resources that ensures no-op writes don't increment resourceVersion. As part of fixing this, the same test should be added for custom resource storage.
