### ISSUE TITLE
PATCH with {"$patch": "delete"} creates key if non-existing

### ISSUE THREAD

**Issue by bronger** [kubernetes/kubernetes#67546]
Having a deployment like:

    apiVersion: extensions/v1beta1
    kind: Deployment
    spec:
      template:
        spec:
          containers:
          - name: mycontainer
    ...
and applying the following patch:

    kubectl patch deployment mydeployment -p '{"spec": {"template": {"spec": {"containers": [{"name": "mycontainer", "env": [{"$patch": "delete", "name": "FOOBAR"}]}]}}}}'
results in:

    apiVersion: extensions/v1beta1
    kind: Deployment
    spec:
      template:
        spec:
          containers:
          - name: mycontainer
            env:
            - name: FOOBAR
    ...

Applying it over and over again results in oscillating behaviour: The key is deleted and re-created over and over again.

Expected behaviour is that the operation is idempotent, leaving the key non-existing.

Kubernetes v1.11
/kind bug

**Comment by yue9944882** [comment]
@liggitt i thought it's the buggy merge key this time again.. but i finally found out that it's the strategic patch stops recursion at the following lines when it does the patch for a container without `env`. so it won't go on respect the directives inside `env` like `$patch: delete` in this case.

[https://github.com/kubernetes/kubernetes/blob/39e341c11f9a18d7fcbf78e4dce6801131e2ba38/staging/src/k8s.io/apimachinery/pkg/util/strategicpatch/patch.go#L1332-L1337](https://github.com/kubernetes/kubernetes/blob/39e341c11f9a18d7fcbf78e4dce6801131e2ba38/staging/src/k8s.io/apimachinery/pkg/util/strategicpatch/patch.go#L1332-L1337)

i open a fix and wrote another integration test to verity the patch behavior according to this issue in #67586.

**Comment by lavalamp** [comment]
This sounds like something that will be fixed by apply...

**Comment by yue9944882** [comment]
@bronger FYI we're planing to replace SMP w/ server-side apply by which will fix this issue together.

**Comment by lavalamp** [comment]
SMP == "strategic merge patch", the weird custom patch format k8s allows, which the example in the OP is using (rather than JSON patch or JSON merge patch).

**Comment by lavalamp** [comment]
We should still take @yue9944882

**Comment by yue9944882** [comment]
sure, will get it 👌🏻

**Comment by furkanmustafa** [comment]
Oh god. Everytime I hit into a (real) issue, it is closed by a bored robot.
How is that okay with anybody?

Dear robots @k8s-ci-robot @fejta-bot please /repoen /remove-lifecycle-rotten /stop-closing-issues.

---

Late to the party but I have realized that when removing taints from nodes, kubectl does it **on client side**, like most of the other things one should be surprised to hear (like node drain).

So I have though, I could use this strategic merge patch thing, and voila! I had 3 taints before I sent the patch, `A`, `B`, `C`. I told it to remove `C`. It removed all, and kept `C`. I bet it would even create `C` if it didn't exist before.

Details of my patch request;

```
PATCH ~> /api/v1/nodes/abcdef
Content-Type: application/strategic-merge-patch+json
```

```json
{
  "spec": {
    "taints": [
      { 
        "$patch": "delete",
        "key": "node.cloudprovider.kubernetes.io/uninitialized",
        "effect": "NoSchedule"
      }
    ]
  }
}
```
Added `effect` property just because API asked for it.
