### ISSUE TITLE
Failing Test : [sig-scalability] Density, Scalability should allow starting 30 pods per node using { ReplicationController} with 0 secrets, 0 configmaps and 0 daemons

### ISSUE THREAD

**Issue by mohammedzee1000** [kubernetes/kubernetes#67670]
# Failing Jobs
[sig-release-master-blocking#gce-scale-performance](https://k8s-testgrid.appspot.com/sig-release-master-blocking#gce-scale-performance)
# Failing Tests
[[sig-scalability] Density [Feature:Performance] should allow starting 30 pods per node using { ReplicationController} with 0 secrets, 0 configmaps and 0 daemons](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/196)
[[sig-scalability] Load capacity [Feature:Performance] should be able to handle 30 pods per node { ReplicationController} with 0 secrets, 0 configmaps and 0 daemons](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/196)
# Triage Results
[ci-kubernetes-e2e-gce-scale-performance](https://storage.googleapis.com/k8s-gubernator/triage/index.html?job=ci-kubernetes-e2e-gce-scale-performance)

/kind failing-test
/priority critical-urgent
/sig scalability
/milestone v1.12

/cc @tpepper @AishSundar 
@kubernetes/sig-scalability-test-failures

**Comment by mborsz** [comment]
The root cause is https://github.com/kubernetes/kubernetes/issues/67644. We rolled back incorrect configuration change. This should make the test green.

**Comment by mborsz** [comment]
The latest run was still running without the fix. We need to the next run to see if there is anything else.
Right now we believe that the failure was caused by our configuration change and is not a real regression.

**Comment by mborsz** [comment]
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/198 has failed due to our unsuccessful attempt to speedup RC removal. It was reverted in https://github.com/kubernetes/kubernetes/pull/67801, but 198 has started before the revert was merged.

**Comment by mohammedzee1000** [comment]
@mborsz status please?

**Comment by mohammedzee1000** [comment]
@mborsz can you please provide update on fix

**Comment by guineveresaenger** [comment]
@mohammedzee1000 - update from Slack #sig-scalability pinging - this is tricky but it's in progress. 

@shyamjvs @krzysied - since you are working on this, could you please update this issue with a daily status report?

**Comment by shyamjvs** [comment]
So there have been 3 regressions from past week that affected scale tests:

- https://github.com/kubernetes/kubernetes/pull/68084#issuecomment-417639412 (fixed now)
- https://github.com/kubernetes/kubernetes/issues/68355 (fixed now)
- https://github.com/kubernetes/kubernetes/issues/67823 (this one still needs some more to be done)

Right now we're running some manual tests locally to see if there are any issues still currently. We may need to do a bisection if we find something - that can take about a week as these tests take longer due to the scale. Will keep posting any updates we get here.

**Comment by shyamjvs** [comment]
Update: We ran the density test couple of times locally against ~HEAD and it passed. Still waiting on results for load test.
In the meanwhile, I suggested @krzysied to increase the frequency of our 5k-node performance job to running daily instead of every other day in order to get a better CI signal (xref - https://github.com/kubernetes/test-infra/pull/9334).

**Comment by shyamjvs** [comment]
We should now have a run once every weekday (starting tomorrow).

**Comment by shyamjvs** [comment]
@guineveresaenger We already have results (more than once) after that issue's fix went in and we know it fixed the problem with taint-controller. We now have 2 latest runs (211 and 212) with density test passing - https://k8s-testgrid.appspot.com/sig-scalability-gce#gce-scale-performance

And for load test we understand the cause of the failures and it is being tracked under this release-blocking issue - https://github.com/kubernetes/kubernetes/issues/68613 (and the fix for that is in and being tested on the current CI run). So I think this bug can now be closed in favour of that.

/close
(reopen if you think otherwise)
