### ISSUE TITLE
API Server memory/goroutines increase over time after v1.11 upgrade

### ISSUE THREAD

**Issue by cespo** [kubernetes/kubernetes#67732]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug
/sig api-machinery

**What happened**:
After v1.11 upgrade the API Server memory started steadily increasing using eventually all resources.
At the same time we observed goroutines and open fds going up

Graphs: https://www.dropbox.com/sh/9fla8up2t70b80d/AAAnAmDydT5gF0OMz9rIfsvBa?dl=0

**What you expected to happen**:
API Server to release chunks of memory after the use.
Possible memory leak in the API Server process

**How to reproduce it**:
- upgrade Kubernetes to v1.11

**Anything else we need to know?**:
The cluster has ~45k namespaces

**Environment**:
- Kubernetes version (use `kubectl version`):
`Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:43:26Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}`
- Cloud provider or hardware configuration:
`AWS`
- OS (e.g. from /etc/os-release):
`CoreOS-stable-1800.7.0`
- Kernel (e.g. `uname -a`):
`Linux ip-10-155-64-206.ec2.internal 4.14.63-coreos #1 SMP Wed Aug 15 22:26:16 UTC 2018 x86_64 Intel(R) Xeon(R) Platinum 8175M CPU @ 2.50GHz GenuineIntel GNU/Linux`
- Install tools:
`Terraform`

**Comment by cespo** [comment]
@kubernetes/sig-api-machinery-bug

**Comment by dims** [comment]
@liggitt any thoughts?

**Comment by liggitt** [comment]
a few questions:
* do you have your full apiserver invocation available?
* are you running any extension apiservers (like service catalog or metrics server)?
* what version of etcd are you running?

**Comment by liggitt** [comment]
@kubernetes/sig-scalability-bugs have we seen anything like this in our scale tests?

**Comment by cespo** [comment]
> - are you running any extension apiservers (like service catalog or metrics server)?
Yes, we are running metrics-server

> - what version of etcd are you running?
etcdctl version: 3.3.8

We don't see the memory spikes on different cluster with ~40 namespaces running the same config

**Comment by tuminoid** [comment]
I'm getting something similar to this on k8s `1.10.4` (etcd `3.2.22`) with no pods running beyond monitoring (Prometheus, metrics-server, kube-state-metrics, influxdb, grafana, heapster).

Based on previous comments, removed metrics-server `0.3.0`, and memory consumption dropped about 100MB, but memory usage keeps growing, just much slower.

![apiserver memory consumption past 24 hours](https://user-images.githubusercontent.com/853790/45211705-a56f2600-b29b-11e8-8012-8d2d5aff83c4.png)

**Comment by salilgupta1** [comment]
We're loading testing our cluster as well to figure out what levers to pull to be able to support 750 nodes. However, we are seeing similar issues with with the api server swallowing memory along with high response latency, high number of dropped requests ... essential it isn't scaling :(

Cluster config:
- K8s Version: 1.11
- etcd Version: 2.2.1
- 3 Master nodes running on m4.4xlarge (16 cores/ 64 Gib mem) instances
- We do have the metrics server running (gcr.io/google_containers/metrics-server-amd64:v0.2.1)

**Memory Usage**
![screen shot 2018-09-07 at 11 42 17 am](https://user-images.githubusercontent.com/5280219/45231842-1c53f100-b293-11e8-999a-b445de8425ac.png)

**CPU Usage**
![screen shot 2018-09-07 at 11 43 02 am](https://user-images.githubusercontent.com/5280219/45231879-368dcf00-b293-11e8-8b94-47e74bec23b0.png)

**Number of Nodes, pods, containers**
Note: We actually had closer to 584 nodes at the peak of our
![screen shot 2018-09-07 at 11 43 43 am](https://user-images.githubusercontent.com/5280219/45231909-4c9b8f80-b293-11e8-995e-9975a6ae9449.png)

**99th and 95th percentile**
![screen shot 2018-09-07 at 11 46 50 am](https://user-images.githubusercontent.com/5280219/45232064-c764aa80-b293-11e8-94ed-54a0b42e3213.png)

**Goroutines**
![screen shot 2018-09-07 at 11 54 29 am](https://user-images.githubusercontent.com/5280219/45232368-cd0ec000-b294-11e8-96b7-ef87813c1149.png)

**open File descriptors**
![screen shot 2018-09-07 at 11 53 47 am](https://user-images.githubusercontent.com/5280219/45232343-b5373c00-b294-11e8-8c9a-3b52dbe18f94.png)


Our load can be bursty since we use this cluster to to run client jobs. There could be a large influx of jobs at any given point which can lead to bursts of pods and instances into the cluster. From previous load tests we have seen that CPU will increase steadily with the burst of nodes and pods added but then come back down once the burst has been handled. However, we have never seen this issue with memory. 

Any help would be appreciated!

**Comment by gyuho** [comment]
@tuminoid Can you share metrics output from etcd?

**Comment by tuminoid** [comment]
@gyuho etcd metrics: https://gist.github.com/tuminoid/12e5cc36d9d866379553cedd1326438f

Left this empty system running over the weekend (without metrics server), and it actually seems to cap around 3GB. Its a single master/worker node for testing, with no load.

![over-weekend](https://user-images.githubusercontent.com/853790/45279571-38959f00-b4da-11e8-88e2-4f475f783c24.png)

On another cluster, with 3 masters, without monitoring, but with our application running, it was linear growth to 10GB over 72 hours, then it purged 8GB and started creeping up again. In both cases, apiserver did not crash.

And for reference, apiserver invocation:
```
      command:
        - /usr/local/bin/kube-apiserver
        - --v=0
        - --logtostderr=false
        - --log-dir=/var/log/kubernetes/apiserver
        - --allow-privileged=true
        - --delete-collection-workers=4
        - --repair-malformed-updates=false
        - --apiserver-count=1
        - --request-timeout=1m
        - --event-ttl=8h
        - --profiling=false
        - --advertise-address=192.168.10.30
        - --bind-address=192.168.10.30
        - --secure-port=6443
        - --insecure-port=0
        - --service-cluster-ip-range=10.254.0.0/16
        - --storage-backend=etcd3
        - --etcd-servers=https://192.168.10.30:2379
        - --etcd-cafile=/etc/etcd/ssl/etcd-ca.pem
        - --etcd-certfile=/etc/etcd/ssl/etcd.pem
        - --etcd-keyfile=/etc/etcd/ssl/etcd-key.pem
        - --enable-admission-plugins=NamespaceLifecycle,LimitRanger,SecurityContextDeny,ServiceAccount,NodeRestriction,DefaultStorageClass,ResourceQuota,DefaultTolerationSeconds,AlwaysPullImages,DenyEscalatingExec
        - --disable-admission-plugins=PersistentVolumeLabel
        - --authorization-mode=RBAC,Node
        - --service-account-key-file=/etc/kubernetes/ssl/serviceaccount.pem
        - --service-account-lookup=true
        - --client-ca-file=/etc/kubernetes/ssl/ca.pem
        - --tls-cert-file=/etc/kubernetes/ssl/apiserver.pem
        - --tls-private-key-file=/etc/kubernetes/ssl/apiserver-key.pem
        - --kubelet-https=true
        - --kubelet-certificate-authority=/etc/kubernetes/ssl/ca.pem
        - --kubelet-client-certificate=/etc/kubernetes/ssl/apiserver.pem
        - --kubelet-client-key=/etc/kubernetes/ssl/apiserver-key.pem
        - --kubelet-timeout=15s
        - --feature-gates=AdvancedAuditing=false
        - --audit-log-format=legacy
        - --audit-log-path=/var/log/kubernetes/audit/audit.log
        - --audit-log-maxage=30
        - --audit-log-maxbackup=10
        - --audit-log-maxsize=100
        - --requestheader-client-ca-file=/etc/kubernetes/ssl/ca.pem
        - --requestheader-allowed-names=aggregator
        - --requestheader-extra-headers-prefix=X-Remote-Extra-
        - --requestheader-group-headers=X-Remote-Group
        - --requestheader-username-headers=X-Remote-User
```

**Comment by tuommaki** [comment]
We hit this same issue and I've been investigating this for a while now and seems that this is coming from `apimachinery`.

Following describes process rss memory usage for one of our apiservers over last two days:
![k8s-apiserver-memory-rss](https://user-images.githubusercontent.com/1947505/45838210-d6c70780-bd19-11e8-9ef4-6edc990e7b2d.png)

Two from the left are upstream `v1.11.1`, the red spikey one is my experiment with forced `debug.FreeOSMemory()` call once a minute and rightmost is `v1.11.1` with [this](https://github.com/kubernetes/apimachinery/commit/f315b2200ee5986e50e452c6daaf3ab1308ba3aa) `apimachinery` patch.

We tried earlier various `v1.11.x` releases but this problem appeared in all of them. Now with this `apimachinery` patch we see only very gradual increase in memory usage and so far I'm unable to clearly point out from where that is coming. The difference to release is still big so it seems that this patch is crucial for `v1.11.x`.

**Comment by dims** [comment]
we can close this right?

/close
