### ISSUE TITLE
CSI - VolumeAttachment obj not recreated after abrupt node deletion

### ISSUE THREAD

**Issue by vladimirvivien** [kubernetes/kubernetes#67853]
/kind bug
/sig storge

Under normal circumstances:
- The internal CSI attacher is invoked to attach a CSI when a PV is created (manually or dynamically).
- The CSI internal attacher then creates a `VolumeAttachment` CSI object
- The external CSI attacher picks up the new `VolumeAttachment` and makes a ControllerPublish volume to the extenal CSI driver.
- Conversely, when a PV is deleted, which kicks the internal CSI machinery which then deletes the related `VolumeAttachment` object.
- The extenal CSI AD controller watches for deleted `VolumeAttachment` and makes `ControllerUnpublish` calls to the appropriate external CSI drivers.

So it would seem that only the deployment/deletion of a PV will cause a full CSI `VolumeAttachment` lifecycle to occur. This may be a problem, as pointed out by [Fatih in kubernetes.slack.com](https://kubernetes.slack.com/archives/C8EJ01Z46/p1534913689000100).  If a node is removed abruptly, causing a pod reschedule, it appears that the `VolumeAttachment` object is not getting recreated.  This could be because the PV is not getting created during rescheduling (maybe).

**Environment**:
- Kubernetes version (use `kubectl version`): 1.10+

**Comment by fatih** [comment]
I tried to reproduce it so I could collect some informations to make it easier for us to debug and also have something we can use to reproduce. 

Versions I use:

* Kubernetes: `v1.10.3`
* DigitalOcean CSI plugin version `v0.1.4` which implements the CSI Spec `v0.2.0`

To observe the issue:

1. Install CSI-digitalocean plugin: https://github.com/digitalocean/csi-digitalocean#installing-to-kubernetes This might be not needed, but this is the CSI plugin I use. 

2. Create following `pvc` and `deployment` :

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-csi-app
spec:
  selector:
    matchLabels:
      app: my-csi-app
  replicas: 1
  template:
    metadata:
      labels:
        app: my-csi-app
    spec:
      containers:
        - name: my-frontend
          image: busybox
          volumeMounts:
          - mountPath: "/data"
            name: my-do-volume
          command: [ "sleep", "1000000" ]
      volumes:
        - name: my-do-volume
          persistentVolumeClaim:
            claimName: csi-pvc
```

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: do-block-storage
```


3.  Confirm everything works fine:

```
$ kubectl get pods -o=wide
NAME                          READY     STATUS    RESTARTS   AGE       IP            NODE
my-csi-app-58c7b697fb-hqhsl   1/1       Running   0          1m        10.244.77.2   worker-7156

$ kubectl get pvc -o=wide
NAME      STATUS    VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS       AGE
csi-pvc   Bound     pvc-b8a3265d-a9d7-11e8-a066-cee23271f171   5Gi        RWO            do-block-storage   2m

$ kubectl get pv -o=wide
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS    CLAIM             STORAGECLASS       REASON    AGE
pvc-b8a3265d-a9d7-11e8-a066-cee23271f171   5Gi        RWO            Delete           Bound     default/csi-pvc   do-block-storage             2m

$ kubectl get volumeattachment
NAME                                                                   AGE
csi-5477b216f07551f0a257c5cde4c77688dba41207d26bc83dd50c8a9a450cc3b8   2m

$  kubectl describe volumeattachment csi-5477b216f07551f0a257c5cde4c77688dba41207d26bc83dd50c8a9a450cc3b8
Name:         csi-5477b216f07551f0a257c5cde4c77688dba41207d26bc83dd50c8a9a450cc3b8
Namespace:
Labels:       <none>
Annotations:  <none>
API Version:  storage.k8s.io/v1beta1
Kind:         VolumeAttachment
Metadata:
  Creation Timestamp:  2018-08-27T09:01:02Z
  Finalizers:
    external-attacher/com-digitalocean-csi-dobs
  Resource Version:  5160
  Self Link:         /apis/storage.k8s.io/v1beta1/volumeattachments/csi-5477b216f07551f0a257c5cde4c77688dba41207d26bc83dd50c8a9a450cc3b8
  UID:               b9737d7c-a9d7-11e8-a066-cee23271f171
Spec:
  Attacher:   com.digitalocean.csi.dobs
  Node Name:  worker-7156
  Source:
    Persistent Volume Name:  pvc-b8a3265d-a9d7-11e8-a066-cee23271f171
Status:
  Attached:  true
Events:      <none>
```

4. Delete the Node where the pod from the deployment is running, either from the UI or by using the following command to delete it via the AP. To find the node name we can use the following command:

```
$ kubectl get pods -l app=my-csi-app -o json | jq -r '.items[].spec.nodeName'
worker-7156
```

and then delete the node (I'm using the [doctl](https://github.com/digitalocean/doctl) CLI, but doesn't matter how we delete):

```
$ doctl compute droplet delete worker-7156
```

5. After a while we should see that the node disaapears:

```
$ kubectl get nodes -o wide
NAME          STATUS    ROLES     AGE       VERSION   EXTERNAL-IP      OS-IMAGE                       KERNEL-VERSION   CONTAINER-RUNTIME
worker-7157   Ready     <none>    1h        v1.10.1   178.128.157.18   Debian GNU/Linux 9 (stretch)   4.9.0-7-amd64    docker://18.6.0
worker-7158   Ready     <none>    1h        v1.10.1   104.248.52.224   Debian GNU/Linux 9 (stretch)   4.9.0-7-amd64    docker://18.6.0
```

and a new node will appear (this is due the fact that Kubernetes on DigitalOcean re-cycles nodes and makes sure it always has the same number of nodes when it was configured. Think of a ReplicaSet that always tries makes sure up to N pods are running based on the `replica` field). 

This particular cluster was configured to have 3 nodes. Note that the new node has a different IP and was just created 10 seconds ago:

```
$ kubectl get nodes -o wide
NAME          STATUS     ROLES     AGE       VERSION   EXTERNAL-IP      OS-IMAGE                       KERNEL-VERSION   CONTAINER-RUNTIME
worker-7156   NotReady   <none>    10s       v1.10.1   142.93.52.133    Debian GNU/Linux 9 (stretch)   4.9.0-7-amd64    docker://18.6.0
worker-7157   Ready      <none>    1h        v1.10.1   178.128.157.18   Debian GNU/Linux 9 (stretch)   4.9.0-7-amd64    docker://18.6.0
worker-7158   Ready      <none>    1h        v1.10.1   104.248.52.224   Debian GNU/Linux 9 (stretch)   4.9.0-7-amd64    docker://18.6.0
```

7. Observe the current state of resources

```
$  kubectl get volumeattachment
No resources found.

$  kubectl get pods -o=wide
NAME                          READY     STATUS              RESTARTS   AGE       IP        NODE
my-csi-app-58c7b697fb-r2pmx   0/1       ContainerCreating   0          1m        <none>    worker-7157

$  kubectl get pv -o=wide
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS    CLAIM             STORAGECLASS       REASON    AGE
pvc-b8a3265d-a9d7-11e8-a066-cee23271f171   5Gi        RWO            Delete           Bound     default/csi-pvc   do-block-storage             30m

$ kubectl get pvc -o=wide
NAME      STATUS    VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS       AGE
csi-pvc   Bound     pvc-b8a3265d-a9d7-11e8-a066-cee23271f171   5Gi        RWO            do-block-storage   30m

$ kubectl describe pods -l app=my-csi-app
Name:           my-csi-app-58c7b697fb-r2pmx
Namespace:      default
Node:           worker-7157/10.136.116.189
Start Time:     Mon, 27 Aug 2018 12:29:55 +0300
Labels:         app=my-csi-app
                pod-template-hash=1473625396
Annotations:    <none>
Status:         Pending
IP:
Controlled By:  ReplicaSet/my-csi-app-58c7b697fb
Containers:
  my-frontend:
    Container ID:
    Image:         busybox
    Image ID:
    Port:          <none>
    Command:
      sleep
      1000000
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /data from my-do-volume (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-26np4 (ro)
Conditions:
  Type           Status
  Initialized    True
  Ready          False
  PodScheduled   True
Volumes:
  my-do-volume:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  csi-pvc
    ReadOnly:   false
  default-token-26np4:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-26np4
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     <none>
Events:
  Type     Reason                 Age   From                     Message
  ----     ------                 ----  ----                     -------
  Normal   Scheduled              2m    default-scheduler        Successfully assigned my-csi-app-58c7b697fb-r2pmx to worker-7157
  Warning  FailedAttachVolume     2m    attachdetach-controller  Multi-Attach error for volume "pvc-b8a3265d-a9d7-11e8-a066-cee23271f171" Volume is already exclusively attached to one node and can't be attached to another
  Normal   SuccessfulMountVolume  2m    kubelet, worker-7157     MountVolume.SetUp succeeded for volume "default-token-26np4"
  Warning  FailedMount            2s    kubelet, worker-7157     Unable to mount volumes for pod "my-csi-app-58c7b697fb-r2pmx_default(c228c94c-a9db-11e8-a066-cee23271f171)": timeout expired waiting for volumes to attach or mount for pod "default"/"my-csi-app-58c7b697fb-r2pmx". list of unmounted volumes=[my-do-volume]. list of unattached volumes=[my-do-volume default-token-26np4]
```

Some observations:

* pod is stuck in `ContainerCreating` status
* no `VolumeAttachment` was created`
* pod was scheduled to a new node `worker-7157` instead of the old one `worker-7156`
* We see an error from the `a/d controller`: `  Warning  FailedAttachVolume     30m                 attachdetach-controller  Multi-Attach error for volume "pvc-b8a3265d-a9d7-11e8-a066-cee23271f171" Volume is already exclusively attached to one node and can't be attached to another`

I piped the logs from `kube-controller-manager` into a file and upload it here for a better understanding. It contains logs from the `a/d controller` during these actions:  https://gist.github.com/fatih/68061df39d407726417e088032d3f6dc

I'll continue to write more if I find something.

**Comment by fatih** [comment]
What's interesting is, the `VolumeAttachment` associated with the `PV` is absent after the node deletion. But according to the logic that @vladimirvivien posted, it should be deleted only after a `PV` deletion. 

I tried to check the logs, but there are no logs that indicate the deletion of the `VolumeAttachment`. After a while, we start seeing log messages in the form of:


```
Aug 27 09:36:21 E0827 09:36:21.384251 csi_attacher.go:384] 
kubernetes.io/csi: detacher.Detach failed to delete VolumeAttachment 
[csi-5477b216f07551f0a257c5cde4c77688dba41207d26bc83dd50c8a9a450cc3b8]: 
volumeattachments.storage.k8s.io 
"csi-5477b216f07551f0a257c5cde4c77688dba41207d26bc83dd50c8a9a450cc3b8" not found
```

If you look carefully, you'll see the `csi-5477b216f07551f0a257c5cde4c77688dba41207d26bc83dd50c8a9a450cc3b8` is the `VolumeAttachment` that's gone.

Gonna increase the log level to gather more information.

**Comment by fatih** [comment]
Correction, seems like the `VolumeAttachment is deleted when a Pod referencing a CSI volume is deleted or terminated (which happens in our case due the `node` deletion): https://github.com/kubernetes/community/blob/master/contributors/design-proposals/storage/container-storage-interface.md#detaching-volumes

**Comment by fatih** [comment]
It seems like there is a `dangling` reference to the delete `VolumeAttachment` , which puts the `a/d controller` in a bad state. The dangling reference to this VolumeAttachment is in the cache. When I restart `kube-controller-manager` it fixes itself and a `VolumeAttachment` is **recreated* again, the pods and pv/pvcs are then all good and running successfully.

I think the issue is, after a Node deletion, the `VolumeAttachment` is deleted indeed, but the reference to this is not, which prevents it to create a new `VolumeAttachment`.

**Comment by fatih** [comment]
I believe I found the issue. And I think there might be several solutions to fix this issue based on how we can approach it. Here is what's happening:

1. Node is deleted (meanwhile in background, DigitalOcean Kubernetes product brings up a new node with the same node). Pod running inside the node is terminated, the `a/d controller` sees this event:
2. `a/d reconciler`  [calls `DetachVolume()` ]([kubernetes/reconciler.go at 029bb4e213502268af6222cc2f6903ab90de751b · kubernetes/kubernetes · GitHub](https://github.com/kubernetes/kubernetes/blob/029bb4e213502268af6222cc2f6903ab90de751b/pkg/controller/volume/attachdetach/reconciler/reconciler.go#L231))
3. CSI in tree plugin (`pkg/volume/csi`) deletes VolumeAttachment and waits for the external-attacher via `waitForVolumeDetachmentInternal()`
4. external-attacher picks up VA deletion, calls `csiDetach()` in csi_handler.go
5. inside csiDetach(), GetNodeInfo() is called:
```
func GetNodeID(driver string, node *v1.Node) (string, error) {
	nodeIDJSON, ok := node.Annotations[nodeIDAnnotation]
	if !ok {
		return "", fmt.Errorf("node %q has no NodeID annotation", node.Name)
	}
```

It returns `has no NodeID annotation` because the newly created node doesn't have it yet (driver-register didn't kicked in yet for the newly created node, see step 1)
6. `csiDetach()` saves the error to `attach.Status.DetachError`
7. inside CSI in-tree plugin, `waitForVolumeDetachmentInternal()` fails with error:
```
kubernetes.io/csi: detachment for VolumeAttachment [csi-9f98afda89d0bac567466e2c2f9d1c538c270bcaac391b32444e2be229723a15] for volume [1803f2c0-aa8c-11e8-bc72-0242ac114503] failed: node \"worker-7325\" has no NodeID annotation
```
8. reconciler errors, therefore is added back to `ReportAsAttached` list  because of (inside `pkg/volume/util/operationexecutor/operation_generator.go`:
```
	getVolumePluginMgrFunc := func() (error, error) {
		var err error
		if verifySafeToDetach {
			err = og.verifyVolumeIsSafeToDetach(volumeToDetach)
		}
		if err == nil {
			err = volumeDetacher.Detach(volumeName, volumeToDetach.NodeName)
		}
		if err != nil {
			// On failure, add volume back to ReportAsAttached list <<<<<<<<<< HERE ....
			actualStateOfWorld.AddVolumeToReportAsAttached(
				volumeToDetach.VolumeName, volumeToDetach.NodeName)
			return volumeToDetach.GenerateError("DetachVolume.Detach failed", err)
		}

		glog.Infof(volumeToDetach.GenerateMsgDetailed("DetachVolume.Detach succeeded", ""))

		// Update actual state of world
		actualStateOfWorld.MarkVolumeAsDetached(
			volumeToDetach.VolumeName, volumeToDetach.NodeName)

		return nil, nil
	}
```
9. reconciler, kicks in and runs `DetachVolume` again
10. this time, the internal CSI in tree plugin returns the following error: 
```
kubernetes.io/csi: detacher.Detach failed to delete VolumeAttachment [csi-dd47fd59ec205781a202e494aec2c5fc482569c457e7ddd3ae1c60f1c9f9b319]: volumeattachments.storage.k8s.io \"csi-dd47fd59ec205781a202e494aec2c5fc482569c457e7ddd3ae1c60f1c9f9b319\" not found"
```

The CSI in tree plugin already deleted the volume, so it doesn't exist anymore (see step 3), it returns an error 
11. Reconciler sees the error, adds back the volumeName to `ReportAsAttached` (see step 8) and continue running `DetachVolume` again (step 9)

There is a loop now between step 9 and step 11

**Comment by fatih** [comment]
Ok, we were using `v1.10.1`.Seems like there is a fix that returns a `nil` if the VA doesn't exist anymore. This is basically breaking the infinite loop between step 9 and 11 above: https://github.com/kubernetes/kubernetes/pull/63295

I upgraded my cluster to `v1.10.4` and after deleting a Node, our reconciler brought a new one and the node was able to attach it. 

However, if no new nodes are created, then it doesn't still attach. I'll make sure to test with `v1.10.4` again to see how it behaves.

**Comment by vladimirvivien** [comment]
@fatih Sorry havent had a chance to look into this. Let's keep it going and address upcoming quarter after release.

**Comment by vladimirvivien** [comment]
Also thank you @fatih for the incredible research.  It will definitely help fixing this.

**Comment by TonyApuzzo** [comment]
Has this been resolved?  It seems that I am experiencing this as a DO customer where I cannot successfully re-start nodes anymore and I have a wedged PVC that looks bound even though the purported user was deleted.

**Comment by timoreimann** [comment]
hey there @vladimirvivien 👋 can I ask if this issue was closed because it got fixed?

**Comment by vladimirvivien** [comment]
@timoreimann I don't believe this was addressed explicitly.
@jsafrane @msau42 do you know of any forced reconciliation in external-attacher that would garbage collect orphaned VolumeAttachment objects if the node goes away suddenly?
