### ISSUE TITLE
What is the basis for forbidding volume multi-attach ?

### ISSUE THREAD

**Issue by NickrenREN** [kubernetes/kubernetes#67936]
We expect the AccessModes in PV spec to be the `all ways` the volume supports,
https://github.com/kubernetes/kubernetes/blob/029bb4e213502268af6222cc2f6903ab90de751b/pkg/apis/core/types.go#L278-L280
and AccessModes in PVC spec is what user wants.
https://github.com/kubernetes/kubernetes/blob/029bb4e213502268af6222cc2f6903ab90de751b/pkg/apis/core/types.go#L393-L395

then which one should we take into account to forbid multi-attach  ? 
For example: RBD for now support `RWO` and `ROX` (we can create a PV with AccessModes setting to `RWO` and `ROX`), if a user create a PVC with `RWO`, should we forbid multi-attach ?

**What happened**:
Depending on AccessModes in PV spec. Will not forbid multi-attach in the situation described above.

**What you expected to happen**:
Depending on AccessModes in PVC spec (what user wants) 

/assign
/sig storage
/cc @jsafrane @msau42 @jingxu97

**Comment by adampl** [comment]
@NickrenREN Did you test this on a multi-node cluster? Keep in mind that Access Modes work on node level, so multiple pods on the same node can access an RWO volume: https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes
I guess this is because volumes are mounted by nodes, not individual pods.

BTW, I don't understand why `AccessModes` in PVC is an array, because according to docs a PV can be mounted in only one access mode at the same time. I suspect it's an array because the volume provisioner copies this array to the PV spec, but IMHO it should rather create a single-item array from the single access mode defined in the PVC spec.
