### ISSUE TITLE
Failing Test: IP SANs (cert subject alternative names) missing

### ISSUE THREAD

**Issue by mohammedzee1000** [kubernetes/kubernetes#67975]
# Failing Jobs
[sig-release-master-upgrade#gke-gci-new-gci-master-upgrade-master](https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gke-gci-new-gci-master-upgrade-master)
# Failing Tests
[[sig-apps] statefulset-upgrade](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-gci-new-gci-master-upgrade-master/1440)
# Triage Results
[[sig-apps] statefulset-upgrade](https://storage.googleapis.com/k8s-gubernator/triage/index.html?job=ci-kubernetes-e2e-gke-gci-new-gci-master-upgrade-master&test=%5C%5Bsig%5C-apps%5C%5D%5C%20statefulset%5C-upgrade)

/sig apps
/priority critical-urgent
/kind failing-test

/cc @tpepper @AishSundar @kubernetes/sig-apps-test-failures

**Comment by liggitt** [comment]
cc @awly @mikedanese

**Comment by liggitt** [comment]
(to be clear, the test failure has nothing to do with statefulsets... it's an apiserver -> kubelet communication issue affecting the exec call the test is trying to make, related to the serving certificate the kubelet has and how the apiserver verifies it)

**Comment by liggitt** [comment]
/sig cluster-lifecycle

more of a "how was this cluster deployed" question. do we have the apiserver and kubelet invocations for 1.11 and 1.12?

**Comment by neolit123** [comment]
here is my take on ownership.

the gce/gke/gci upgrade and upgrade skew jobs are defined and tagged under sig-cluster-lifecycle:
https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-cluster-lifecycle/k8s-upgrade-gke.yaml#L86-L110

the tests use GKE as the deployer and **not** any of the tools that sig-cluster-lifecycle maintains.
arguably, the ownership of the jobs needs to change because nobody from sig-cluster-lifecycle understands or maintains them.

SIG cluster-lifecylce's definition:
https://github.com/kubernetes/community/tree/master/sig-cluster-lifecycle
WIP charter to be merged:
https://github.com/kubernetes/community/blob/7b78ede38b10c6fa9436df7d9cf39af83176e1bd/sig-cluster-lifecycle/charter.md

> The SIG owns the framework for upgrade / downgrade testing of Kubernetes. However, **the SIG does not own the individual tests for each feature**. While the SIG is often involved in triaging and debugging upgrade or downgrade test failures, the SIG will normally delegate issues to the feature owner for the failing test.

let's have a look at this as an example which is tagged `[sig-cluster-lifecycle]`:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-gci-stable3-gci-stable1-upgrade-master/5456#sig-cluster-lifecycle-upgrade-featureupgrade-master-upgrade-should-maintain-a-functioning-cluster-featuremasterupgrade

this is clearly a GCE/compute/ingress API missmatch type of issue. we had a similar one last month that @rramkumar1 fixed.
^ /cc @andrewsykim 

the SIG maintains a separate set of tests which are kubeadm upgrade specific (and also broken ATM):
https://k8s-testgrid.appspot.com/sig-cluster-lifecycle-all
these are going to be looked at soon.

2c.

/cc @timothysc @spiffxp

**Comment by mikedanese** [comment]
@awly figured this out and is looking into it

**Comment by mikedanese** [comment]
It's a version skew issue. We need to wait a few releases before enabling server auth validation when making connections from apiserver to kubelets. Fix is merged as of 1pm yesterday and we are waiting for a successful deployment. However the release pipe is clogged for reasons unrelated right now.

**Comment by tpepper** [comment]
This symptom's now looking green as of last night.

@mikedanese can you give a repo and commit id, or PR link to what's believed as the fix, for future reference if we see a similar regression?

Will close once that's recorded here.

**Comment by awly** [comment]
@tpepper unfortunately, this was fixed in our internal codebase.

The root cause was setting `--kubelet-certificate-authority` flag on kube-apiserver to cluster CA cert. In clusters where nodes are older version and didn't yet provision signed serving certs.

**Comment by guineveresaenger** [comment]
/close

Thank you @awly!

**Comment by tpepper** [comment]
Thanks @awly!  If I'm parsing that right, then this means it's not a forward breakage that would suggest others will hit this and thus a release note needed.  Part of my concern on this symptom was we should be informing users how not to similarly hit this, but that looks unlikely.
