### ISSUE TITLE
Proposal: Add "Termination Notice"

### ISSUE THREAD

**Issue by piosz** [kubernetes/kubernetes#6804]
Pods running on Kubernetes cluster may be stopped for a various reasons (e.g. resizing Replication Controller, rolling update, autoscaling number of nodes). The goal is to let them shut down gracefully by providing preemption notice a while before being stopped.

Possible errors caused by pods being killed instantly:
* not freed resource,
* broken TCP sessions,
* inconsistent state of PD.

### Draft solution

Once Kubelet observes request to delete a pod it manages from master’s state (etcd), each container running in the pod will receive SIGTERM signal. If a container has any cleanup stuff to do it must handle the signal. After defined time period Kubelet will actually delete the pod.

We need an additional support from cloud provider to handle preemption notice. We assume that cloud provider will notify the intention to remove a node from the cluster before actually removing it (ie. [STOPPING](https://cloud.google.com/compute/docs/instances#checkmachinestatus) state in GCE). After receiving the notification, node controller will delete pods on the node to allow Kubelet to send preemption notices to containers and then remove pods. Also Node Controller will mark the node as Unschedulable.

**Comment by piosz** [comment]
cc @brendandburns @bgrant0607 @davidopp @thockin @jszczepkowski

**Comment by bgrant0607** [comment]
See also #1535, #2789, #5085, and
[pre-stop hooks](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/container-environment.md#hook-details).

**Comment by bgrant0607** [comment]
cc @smarterclayton

**Comment by bgrant0607** [comment]
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/api/v1beta3/types.go#L1256
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/api/v1beta3/types.go#L637

**Comment by smarterclayton** [comment]
Can you extend the proposal to answer whether the time period for preemption (called grace period in existing code) should be per container or per pod, and what the default for pods should be in the absence of that value?

**Comment by bgrant0607** [comment]
FWIW, what you're describing we generally call "eviction" internally rather than "preemption".

There are multiple parts to this:
1. Complete the work to support graceful termination of pods.
2. Create a mechanism to evict pods from nodes. Currently we only have a way to stop scheduling.
2. Use graceful termination to evict those pods.

**Comment by smarterclayton** [comment]
I believe everything with graceful termination is wired up, you just need to add the mechanisms to define the period, and then have the kubelet react to it.  Hopefully :)

----- Original Message -----

**Comment by bgrant0607** [comment]
This might be a good time to decide what to do about SIGTERM vs. pre-stop hooks.

@piosz FYI, we do send SIGTERM to containers already -- that's done by docker stop. We just don't allow the grace period to be configured. Prior to sending SIGTERM, we execute the pre-stop hook, if specified, without any deadline.

**Comment by erictune** [comment]
As @bgrant0607 says, we call this eviction internally.  Eviction suggests getting kicked out of your house, and going to live somewhere else.  Which makes sense in our internal system, where the Pod and ReplicationControllerOfSizeOne concepts are combined into a single object.  But, in Kubernetes, a Pod dies rather than going to live somewhere else.  So, maybe we should call this Termination Notice.  There may be a replication controller, or not.

**Comment by davidopp** [comment]
killContainerByID() in pkg/kubelet/kubelet.go is what you're looking for. The hard-coded 10 is the current notice we tell Docker to give containers when terminating them. You probably want to start there if you want to make it configurable.

I'm not sure we've fully thought through the node lifecycle in the case of dynamic cluster size, i.e. the scenario you described where we are shrinking the cluster and want to give containers notice before they are killed due to their node being removed. That might be worthy of a separate issue--all the things that happen when scaling down. I would suggest to approach it from the perspective of manually invoked (e.g. human invoked stop node), then later you could add details on how auto-scaler would invoke it.

And I agree with the others, you should call this eviction notice.

**Comment by thockin** [comment]
Can I say that I find signals to be a poor form of signalling?  Can we
offer better signalling by the same mechanisms we use for probes?  HTTP get
and exec in particular.

On Tue, Apr 14, 2015 at 1:36 PM, David Oppenheimer <notifications@github.com

**Comment by bgrant0607** [comment]
@thockin Currently we do both.

**Comment by davidopp** [comment]
@bgrant0607 Can you explain? I thought we are just using the Docker mechanism (same as "docker stop") which uses SIGTERM.

**Comment by piosz** [comment]
Thank you guys for feedback. I'll update the proposal soon.

@davidopp answering to your idea @jsz is working on {auto, manula}-scaling, so he is a good POC.

**Comment by piosz** [comment]
AFAIU the remaining work is:
* handle grace period in kubelet
* add grace period option in Node Controller
* add grace period option to kubectl

Am I right? @smarterclayton are you going to work on it?

**Comment by smarterclayton** [comment]
* Add grace period to pod API
* add grace period defaults to pod/rest.go

I probably will not be able to start this for another few weeks, but I can advise someone else

**Comment by bgrant0607** [comment]
We need to discuss/design what semantics we want before we run off building anything.

Apparently, the PreStop hook was never implemented. We should either decide we want to support it, or delete it from the API. It's been in the API since August.

**Comment by piosz** [comment]
@smarterclayton I'm happy to work on that

@bgrant0607 definitely yes. I'll create a proposal and then set up a VC with you

**Comment by bgrant0607** [comment]
FYI, unschedulable was added in PR #4585.

**Comment by piosz** [comment]
#### Semantic
The first problem to discuss is how a user should specify grace period. The current solution to specify it while requesting pod stop doesn’t cover all cases. Especially when replication controller is resized there is no info about the grace period. I suggest to add `terminationGracePeriod` immutable field to `PodSpec`, which means: “I need such time to terminate gracefully”. It could be overwritten (but only decreased) by specifying `gracePeriod` argument in delete request. Sample use case:
* user creates replication controller with size 5 and specify `terminationGracePeriod` to 120 sec; pods are created,
* user resizes RC to 3; two pods are deleted with grace period 120 sec,
* node controller notices a node in “being removed” state; one of mentioned pods is running on the node, so node controller sends a stop request with `gracePeriod` specified to 60 sec; the pod is deleted with grace period 60 sec.

#### Corner cases:
1. If any of values `terminationGracePeriod` or `gracePeriod` is specified to 0 delete immediately.
2. If none of those values is specified a default value specified by a flag will be used (should be small like 3 secs).
3. If a pod is already being deleted the solution suggested by @smarterclayton seems to be right:

> If a delete is already in progress and gracePeriod is shorter than the existing period, the grace period will be shortened.

#### hooks vs. signals
According to hooks vs. signals discussion I propose to use signals in the first version just because they are supported in Docker and then consider adding also hooks (actually implement it). Both solutions can simply coexist.

**Comment by smarterclayton** [comment]
----- Original Message -----
> #### Semantic
> The first problem to discuss is how a user should specify grace period. The
> current solution to specify it while requesting pod stop doesn’t cover all
> cases. Especially when replication controller is resized there is no info
> about the grace period. I suggest to add `terminationGracePeriod` immutable
> field to `PodSpec`, which means: “I need such time to terminate gracefully”.
> It could be overwritten (but only decreased) by specifying `gracePeriod`
> argument in delete request. Sample use case:
> * user creates replication controller with size 5 and specify
> `terminationGracePeriod` to 120 sec; pods are created,
> * user resizes RC to 3; two pods are deleted with grace period 120 sec,
> * node controller notices a node in “being removed” state; one of mentioned
> pods is running on the node, so node controller sends a stop request with
> `gracePeriod` specified to 60 sec; the pod is deleted with grace period 60
> sec.
> 
> #### Corner cases:
> 1. If any of values `terminationGracePeriod` or `gracePeriod` is specified to
> 0 delete immediately.
> 2. If none of those values is specified a default value specified by a flag
> will be used (should be small like 3 secs).

The default container grace period should probably be 30 seconds or longer for containers - most software I'm familiar with should NOT be SIGKILLed without a lot of advance warning, and that default is likely to cause a lot of serious issues for people.  Database pod authors know to increase time.

**Comment by bgrant0607** [comment]
A quick nit: duration fields should specify the units (e.g., terminationGracePeriodSeconds) or use time.Duration #6013. The former is probably easiest and most consistent for now. If we're going to set it to a non-zero default value, it needs to be a pointer.

**Comment by bgrant0607** [comment]
Plug for Borg paper, which mentions termination notice (search for SIGTERM): https://research.google.com/pubs/pub43438.html

Seems reasonable. Thanks for writing up the proposal.

I don't think terminationGracePeriodSeconds needs to be immutable.

I agree that once set it should only be possible to reduce the grace period set via delete, though.

30s seems a reasonable default.

The node controller should respect the grace periods on all pods, and should "right align" notifications. When a node is to be removed from service (is there a proposal for that?), the max of all grace periods should be computed in order to determine the removal time. At removal time minus the grace period, each pod should be notified.

The admission controller should be able to enforce maximum grace periods. 

Since every process manager I'm aware of supports SIGTERM, I'm in favor of maintaining that mechanism.

However, we should think about the prestop hook a bit. I like the proposal https://github.com/GoogleCloudPlatform/kubernetes/issues/1535#issuecomment-75556839 to deliver SIGTERM after the prestop hook completes. Both must be included in the grace period. If we want to send SIGABRT 1s before SIGKILL, I'm ok with that. Ideally, the prestop hook would be told what the grace period is. The period could be reduced subsequently, but that's ok.

By its nature, notice is not 100% reliable, and we should document that. It may be delivered multiple times or not at all.

We should recommend that containers start to report not ready as soon as they receive the notification.

As for whether to add a new phase, let's discuss that in #6951.

**Comment by bgrant0607** [comment]
If we send SIGKILL at the same time or after the etcd TTL expires, then we'll still have the problem mentioned by #6951 where events are generated after the namespace is deleted. I don't know how to resolve that without leaving around the namespace for a while as a tombstone.

**Comment by davidopp** [comment]
The proposal seems reasonable. I agree putting the requested grace period in PodSpec makes sense. I don't see any reason why it has to be non-user-updatable, but I guess it makes things a little simpler and probably updating isn't a feature many people would need anyway. 

I didn't understand where the 60 sec came from in the third bullet. Can you explain?

I wanted to make sure I understand the condition you're describing for when a pod will get less grace period than it requested. IIUC you're talking about the following scenario: the pod requested some grace period G, the pod gets deleted, then while it is deleting someone deletes it again with a shorter grace period T; we don't send it another SIGTERM but we do kill it T seconds from when the second delete arrives, rather than G seconds from when the initial delete arrives. Is that right? (And it sounds like you're proposing to never lengthen the actual grace period, only shorten it.)

We definitely need to integrate this with machine shutdown, but AFAICT we haven't fully implemented machine shutdown yet. I guess there are two cases

(1) Operator does "kubectl stop node" or "kubectl delete node" I just tested these and neither does anything on GCE; the first one gives an error "no reaper has been implemented for "Node"" and the second one claims to work (prints node name in response, gives no error) but nothing happens (node is still there, pod is still running, etc.)

(2) Operator deletes the VM instance. This is surprisingly hard to do on GCE because we use managed instance groups to auto-restart the VM very quickly, and at least via the UI you can't delete the MIG without deleting the VMs, so I'm not sure how to test this (this being delete the VM, wait a while, and see how the pod is treated). But the NodeController code (that I guess is being moved into Kubelet soon) calls into the API server to delete the node
https://github.com/GoogleCloudPlatform/kubernetes/blob/65d132a3eecee38fc22e82ff5fd9e100aae342be/pkg/cloudprovider/nodecontroller/nodecontroller.go#L324
which I assume is basically the same as (1) hence it doesn't really do anything. Have we tested anything with regard to machine shutdown?

Anyway, I think the semantics we want for machine shutdown ("stop node", whether triggered by deleting the VM or deleting the object through the API server) are basically what @bgrant0607 described, that the machine gets deleted at now + (max of all requested grace periods of pods running on the machine), and that you give each pod notice at machine_shutdown_time - its_own_pod_grace_period so that all pods get killed -9 simultaneously. Of course we need to ensure we don't schedule new pods onto a machine that is in the middle of shutting down for various reasons that should be obvious. Analogously to the discussion about vacating/stopping phase for pod (or some alternative representation thereof), we probably want such a phase (or alternative representation, like a machine_shutdown_time that is non-zero when the machine is shutting down) for machines.

**Comment by smarterclayton** [comment]
As noted in another thread all describe and get formatters in kubectl need to handle the pending deletion state.

**Comment by derekwaynecarr** [comment]
One way to solve the namespace issue is to have each node that has a scheduled pod in a namespace claim itself as a named finalizer on the pod namespace.  Then when the node is no longer managing any pods with that namespace it removes itself from the finalizer list after it dispatched the events for the pod.

Another option is to stop auto provision of a namespace for v1 and require explicit creation.  This is good from a separation of concerns issue with enforcement of policy, but it could mean that in total destitution of the namespace the death rattle events could be forbidden by admission control.  

In any event, I think a node inserting itself in the finalizer list is not a bad option, but I am not sure the ramifications for upper bound of that list size.  It is theoretically limited by cluster size so at worse you have 1000 host names in that finalizer list.

**Comment by piosz** [comment]
@bgrant0607 do you want to have it for v1?

**Comment by davidopp** [comment]
BTW @piosz as we discussed in person, when you have a chance please file an issue for the machine shutdown future work.

**Comment by piosz** [comment]
Increasing priority since it is prerequisite for #7091

**Comment by bgrant0607** [comment]
Also related to #6080.

**Comment by davidopp** [comment]
Moving to post-1.0 (along with #7091)

**Comment by piosz** [comment]
Assigned to Clayton since he is working on it.

**Comment by yujuhong** [comment]
@smarterclayton, can we close this now that #8641 has completed?

**Comment by smarterclayton** [comment]
Yes
