### ISSUE TITLE
cluster nodes won't never scale down to default number of counts if I update/deploy a deployment on scaled-up node

### ISSUE THREAD

**Issue by cpwujoewu** [kubernetes/kubernetes#68052]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug

**What happened**:
I have a three-node cluster, called node A, B, C, and it scales up because I have a deployment with HPA. When HPA scales up, the cluster nodes scales up too. 

The situation is when the cluster is scaled up due to cluster auto-scaling, at this time, I re-deploy a deployment(due to update), this deployment will be deployed on a scaled-up node. Since the spec.replica is set to 1 as default, this deployment will never be moved back to original nodes even if the original node have enough resources. It will cause the scaled-up node never scale down thereafter. Therefore extra node fee will be charged.

**What you expected to happen**:
I expect the deployments on scaled-up nodes should be migrated back to original node if the original node has enough resources

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a cluster with cluster auto-scaling enabled
2. deploy a deployment with HPA
3. increase HPA loading, trigger the cluster to scale up
4. re-deploy other deployment(called Z) at this time, and this deployment(Z) will be deployed on the scaled-up node
5. decrease HPA loading, trigger the cluster to scale down
6. the node with deployment(Z) will never scale down thereafter

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.10.4-gke.3
- Cloud provider or hardware configuration: GCP
- OS (e.g. from /etc/os-release): Optimized OS
- Kernel (e.g. `uname -a`): 
- Install tools:
- Others:

**Comment by cpwujoewu** [comment]
I can't tell if this is a feature request or a bug.
I don't config any PDB,  but because spec.replica in a deployment is set to 1 as default, this has the same meaning, right? [How Disruption Budgets Work](https://kubernetes.io/docs/concepts/workloads/pods/disruptions/#how-disruption-budgets-work)

So, when HPA scales up a deployment, it will use up resources that original cluster nodes have and then trigger CA. At this moment, updating another deployment will deploy a new pod into scaled-up node. This behavior will end up a node can't be scaled down thereafter.

**Comment by MaciekPytel** [comment]
All HPA does is set the number of replicas on deployment. It doesn't have any control over what pods are created or removed, or where they're scheduled. In general there is no built-in rescheduling in Kubernetes and once the pod gets scheduled on a node it will generally stay there. 

You probably need to figure out why Cluster Autoscaler is not scaling down afterwards (usually the reason is pretty clear from logs) and update the settings so it will remove that node.  

You may also look at https://github.com/kubernetes-incubator/descheduler, which is designed to move pods around if it thinks they're scheduled in wrong places. The problem is it probably follows the same logic as scheduler and tries to spread your pods as much as possible, not pack them tightly. I don't know that much about descheduler though, so I may be wrong on this one.

**Comment by cpwujoewu** [comment]
hi, 
I solve this problem by using 'kubectl drain <node-name>' manually. I think this is just a workaround.

I will write shell scripts to check the cluster status. If there are nodes under utilized and other nodes can accept the deployments, then use kubectl drain to drain the node.
The side-effect is that the cluster will has downtime when draining the node.
