### ISSUE TITLE
Flaky test: [sig-storage] In-tree Volumes [Driver: nfs] [Testpattern: Dynamic PV (default fs)] volumeIO should write files of various sizes, verify size, validate content [Slow]

### ISSUE THREAD

**Issue by msau42** [kubernetes/kubernetes#68097]
**Is this a BUG REPORT or FEATURE REQUEST?**:
@kubernetes/sig-storage-bugs 

**What happened**:
Only the newly added nfs external provisioner volume IO test is flaking.

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/testsuites/volume_io.go:152
Expected error:
    <*errors.errorString | 0xc4210e8030>: {
        s: "size of file /opt/volume/e2e-tests-volumes-rbzqh/nfs_io_test_e2e-tests-volumes-rbzqh-1048576 is 123904, expected 1048576",
    }
    size of file /opt/volume/e2e-tests-volumes-rbzqh/nfs_io_test_e2e-tests-volumes-rbzqh-1048576 is 123904, expected 1048576
not to have occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/testsuites/volume_io.go:157				
```

I wonder if the pod is getting killed due to cpu/memory limits.  Could it be a problem with limits set by ganesha?

**Comment by mkimuram** [comment]
@msau42 

> Only the newly added nfs external provisioner volume IO test is flaking.

One of the cause of this issue might be that only nfs driver sets FileSizeLarge to [MaxFileSize](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/storage/drivers/in_tree.go#L83).
We will be able to change it to FileSizeMedium as other drivers do, if the root cause of this issue is clear.

I suspect that it is caused by the difference of the nfs backend between dynamic provisoner pod and containerized nfs server pod for in-line volume and pre-provisioned PV.

Note that the difference of size was originally coming from [this code](https://github.com/kubernetes/kubernetes/commit/9ca7ffdf592fe7b5d6ddc05d139874d199d27c55#diff-ebaf1d0f6ec1d25c87102a2b59e3099aL293)
And only NFS seems to have been tested for 1GiB since [volumeIO test was introduced](https://github.com/kubernetes/kubernetes/commit/a113d8ac4170245e5a3347318532a50eeabb552b#diff-ebaf1d0f6ec1d25c87102a2b59e3099aR273)

**Comment by msau42** [comment]
I'm fine with reducing the write size just for this or disable the test for this

**Comment by mkimuram** [comment]
@wongma7 

Is it possible for nfs external provisioner to utilize containerized nfs server, instead of ganesha?

I'm thinking about moving ```NewNFSServer``` from ```CreateVolume``` to ```CreateDriver``` and share it from all of the volume types.

In that case, how [```startExternalProvisioner```](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/storage/drivers/in_tree.go#L150) will be?
From [document](https://github.com/kubernetes-incubator/nfs-provisioner/blob/master/docs/deployment.md), I think below are needed:
```
-run-server=false 
-use-ganesha=false
```

And what else?

Does ```server-hostname``` accept container IP?
Is it O.K. to just delete delete Ports, Env, VolumeMounts, and Volumes from the external provisioner pod spec, in this case?

**Comment by wongma7** [comment]
@mkimuram I want to move the test to use https://github.com/kubernetes-incubator/external-storage/tree/master/nfs-client + NewNFSServer. We can reduce write size etc. in the meantime.

**Comment by msau42** [comment]
If we plan to remove the test altogether, can we just not support dynamic PV for nfs then?

**Comment by mkimuram** [comment]
I just implemented @wongma7 's suggested version. If the cause is ganesha, it wil fix this issue.
I will make a PR, soon.

**Comment by mkimuram** [comment]
@msau42 

> If we plan to remove the test altogether, can we just not support dynamic PV for nfs then?

Of course, I will agree to drop dynamic PV for nfs test in this release, if necessary. I understand that we have a lot of things to do before code freeze, and above fix can be in next release.

**Comment by msau42** [comment]
@mkimuram is this issue resolved?

**Comment by mkimuram** [comment]
@msau42 

Is this test still flake with the same error?
Then, we need to consider working on this.

And for short term workaround, we might reduce write size, as discussed [here](
https://github.com/kubernetes/kubernetes/issues/68097#issuecomment-417785486).
(If the issue is due to ganesha, this won't 100% avoid the flake, though.)

**Comment by msau42** [comment]
I don't see the size error anymore, but there are pod timeout errors now.

https://storage.googleapis.com/k8s-gubernator/triage/index.html?test=nfs.*volumeIO%20should%20write%20files%20of%20various%20sizes%2C%20verify%20size%2C%20validate%20content

**Comment by mkimuram** [comment]
@msau42 

I checked by changing the query like below and started to think that these issues are caused just because timeout is short for worst case, because similar error occurs in other drivers and other tests.

- [Time out issue for volumeIO tests](https://storage.googleapis.com/k8s-gubernator/triage/index.html?text=io-client%5C%22.*%3A%20timed%20out%20waiting%20for%20the%20condition&test=.*volumeIO.*)  --> timeout for deleting/running pod happens other drivers than nfs
- [Time out (not deleted) issue for all tests](https://storage.googleapis.com/k8s-gubernator/triage/index.html?text=not%20deleted%3A%20timed%20out%20waiting%20for%20the%20condition) --> timeout for deleting pod happens other test than volumeIO tests
- [Time out (not running) issue for all tests](https://storage.googleapis.com/k8s-gubernator/triage/index.html?text=not%20running%3A%20timed%20out%20waiting%20for%20the%20condition) --> timeout for running pod happens other test than volumeIO tests

If we need to avoid this kind of flake, we would need to make timeout longer.

**Comment by msau42** [comment]
Are you able to see from the logs if IO was still going on when the test timed out?

**Comment by msau42** [comment]
Increasing the timeout makes sense if we think it's too short

**Comment by msau42** [comment]
This hasn't flaked in a while, at least in the blocking suites
/close
