### ISSUE TITLE
apiserver bind-address is not configuration through kubeadm MasterConfiguration

### ISSUE THREAD

**Issue by ochinchina** [kubernetes/kubernetes#68109]
Currently only the advertise-address for the kube-apiserver can be configured and the bind-address for kube-apiserver can not be configured. And kube-apiserver will listen on 0.0.0.0, this will cause some security issues for the kubernetes.

**Comment by neolit123** [comment]
thank you for the report.

> And kube-apiserver will listen on 0.0.0.0, this will cause some security issues for the kubernetes.

`--bind-address` is bound on a security port for HTTPS and this is about security connections.
also if `0.0.0.0` is the value, the api-server will fallback to the address in your default network interface.
e.g. 192.168.0.1.

if you wish to modify `--bind-address` from kubeadm you can pass it to the APIServer the following way:
https://kubernetes.io/docs/setup/independent/control-plane-flags/

/sig cluster-lifecycle
/sig api-machinery

/close

**Comment by stealthybox** [comment]
> --bind-address is bound on a security port for HTTPS and this is about security connections.
also if 0.0.0.0 is the value, the api-server will fallback to the address in your default network interface.
e.g. 192.168.0.1.

Just noting here for future readers:

This is not how binding to `0.0.0.0` behaves.
If the kube-apiserver or any other process binds to 0.0.0.0 + some port, all interfaces on that machine will respond to the --bind-port.
This includes any CNI bridges as well as interfaces that could be exposed to the internet or other networks.

Binding to `0.0.0.0` will not fallback to the default interface.
The default interface calculation is used by kubeadm to automatically set the apiserver's --advertise-address which is not the same as the --bind-address.

The advertise address is used to configure the kubernetes Service VIP that is installed by default in kube clusters and configured for per-node load-balancing by kube-proxy.
Kubeadm additionally will add the advertise address to the APIServer TLS Certificate's SAN list. This allows clients with the proper CA bundle to validate the apiserver's identity, but it does not stop clients from connecting to the apiserver while ignoring TLS on other invalid interfaces which could be listening on `0.0.0.0:6443`.

**Comment by haqa** [comment]
I believe this issue should be re-opened - not being able to specify where Kubernetes does all its internal admin is a security risk.

Where we have configured a multi-homed cluster, with a management private network, and a public front facing network we will almost certainly want to block MOST ports on the internet facing interface for all scenarios except (or potentialy even including) the "commercial public cloud" use case. Certainly I'd expect we would want any external api access to come through a WAF, not direct to a control-plane node.

If you actually try to do this you find that not only does apiserver listen everywhere (because unless you configure it manually you can't tell it not to) but kube-proxy assumes that all interfaces are equal and uses MASQUERADE to translate internal to clusterwide traffic: It should instead SNAT from an address on the interface that has the most specific route to the control-plane (Which, of course, means you need to have been able to tell the apiserver which one that is). Of course the internet facing interface has to have the default route, so this is where all management traffic ends up sourced from, reducing the effectiveness of any attempts to firewall off admin traffic on the internet facing interface.

Kubeadm is the primary tool used by platform managers to deploy their environments (again possibly with the exception of large public clouds), and it not being able to cope with multihomed servers in the cluster really needs looking at.

The alternative is effectively stating that kubeadm, kube-proxy, and by extension Kubernetes, are not designed for internet facing clusters, and I'm not sure that's the messaging the project is looking to present.
