### ISSUE TITLE
Ensure that csiDriver informers are synced before use

### ISSUE THREAD

**Issue by gnufied** [kubernetes/kubernetes#68261]
We aren't checking if informers are synced before using them - https://github.com/kubernetes/kubernetes/pull/67945#discussion_r215105859

We should ensure that, informers are synced before use in kubelet/attach-detach controller.

/sig storage
/assign

**Comment by gnufied** [comment]
cc @jsafrane

**Comment by jsafrane** [comment]
From #67945:

> Do you check HasSynced() in non-test code to ensure the initial list/watch has completed prior to making use of the store? If so, what does that do if the CRD is not installed?

I don't check `HasSynced()` in the volume plugin code, because the CRD does not need to be installed at that time. The plugin behavior is the same for "CRD not installed" and "CRD installed, but CR does not exist" cases.

The case "CRD installed, CR created, but HasSynced is false" is the same as "CRD installed, CR created, HasSynced is true, but CR did not reach the cache yet because it was created after the cache has been synced".

Long story: when CRD is not installed, `factory.Start()` tries to `List` and `Watch` the non-existing CRD and it fails. The informer factory re-tries that every 1-2 seconds, so eventually it starts working when the CRD is installed. Until then, the informer cache is empty ("no CR exists") and the CSI volume plugin falls back to original behavior (all volumes are attachable).

So, in the worst case, a pod with CSI volume is being started and CRD + CR is not installed yet. CSI volume plugin goes through the "attaching" path and tries to attach the volume by creating VolumeAttachment instance. There is no external attacher processing that, from A/D and kubelet point of view the volume is "being attached". `Attach()` times out and A/D controller re-tries it with exp. backoff.

Now, CRD is installed + CR is created and it's stored in the informer cache. Subsequent `Attach()` will succeed because it checks the informer cache and skips attach completely and kubelet will mount the volume.

You can notice that `VolumeAttachment` is not deleted. It will be deleted in `Detach()`. Maybe it could be deleted when `Attach()` skips attachment...

**Comment by kfox1111** [comment]
The code around passing pod info to the csi driver will also be effected by the lack of sync.

> The case "CRD installed, CR created, but HasSynced is false" is the same as "CRD installed, CR created, HasSynced is true, but CR did not reach the cache yet because it was created after the cache has been synced".

No, this isn't quite true. The admin creating the CRD knows approximately how long to wait before knowing a driver will work and allow users to start using it in that case. Having a kubelet be restarted (possibly due to a crash and getting it auto restarted) can potentially happen randomly, so there is a greater unknown to operators when the cache is not synced but still used.

Putting a wait for sync on the enabled path before using it I think is pretty important.

**Comment by jsafrane** [comment]
I've been thinking about this and I've not come to a clean solution. The main problem is that the CSI volume plugin should work without CSIDriver CRD installed. In 1.12 the CRD is optional, installed by driver registrar during driver registration. `Informer.HasSynced()` returns false both when the CRD does not exists and when the CRD exists but the cache has not been synced yet. The volume plugin needs to distinguish between these two cases so it knows it should wait for informer sync(the CRD exists) or be sure that no CSIDriver exists because the CRD does not exist.

There are several possible solutions, all of them with some drawbacks:

1. The CSI volume plugin can `Watch()` CRDs. When CRD for CSIDriverInfo is created, the plugin starts informer on it and syncs its cache. Downside of this solution is that kubelet + A/D controller need to have List + Watch permissions on CRDs, which looks weird.

2. If `Informer.HasSynced()` returns false, the CSI volume plugin can try to GET the CSIDriver from API server to be 100% sure that the CRD does not exists (or it exists and the CSIDriver exists too). This way, the plugin may abuse API server until the CRD is installed.

3. We can require that CRD must be installed when CSIDriverRegistry feature is enabled. Without the CRD and/or until CSIDriver informer is synced, the CSI volume plugin returns error to all calls that need a CSIDriver.

During alpha, I'd probably go with 3., but we need to solve it properly before beta. The CRD should be installed by something during  Kubernetes installation / startup, so we can minimize time when the CRD is not installed.

@saad-ali @davidz627 @verult @msau42 @pohly @vladimirvivien

**Comment by jsafrane** [comment]
I am removing the informer for now in #69416. We should restore it when we know that CSIDriver is installed on cluster startup.

**Comment by msau42** [comment]
This is being handled by https://github.com/kubernetes/kubernetes/pull/75129

**Comment by davidz627** [comment]
@msau42 can this issue now be safely closed that #75129 has merged

**Comment by msau42** [comment]
Yes I think so
/close
