### ISSUE TITLE
add proxy disable support in http liveness probe

### ISSUE THREAD

**Issue by WanLinghao** [kubernetes/kubernetes#68607]
/kind feature

Currently the liveness probe in container will use node's local proxy settings by default. 
For example, if the node has environment set like: `http_proxy=xxxx`,  the http liveness probe will use this proxy. But I think for most situation, the proxy is not set to do liveness probe. This would cause liveness probe failure which should not.
So I think we need provide a way for users to choose if the http liveness probe should use node's local proxy settings.

**Comment by WanLinghao** [comment]
@smarterclayton WDTY about this proposal

**Comment by smarterclayton** [comment]
Yeah, this seems like a bug.  I can’t offhand think of a use case for respecting the http_proxy on a node, and plenty of disadvantages.  We need to verify that assumption.

/kind bug

**Comment by WanLinghao** [comment]
@smarterclayton  Do you think we should provide some mechanism to let users choose using node's proxy or not.  Or just simply disable the use of node's proxy.

**Comment by smarterclayton** [comment]
I’m not sure when a user would need a remote proxy to access pods from the
kubelet, so without a use case I don’t think it should be made a choice.

Let’s try to find out whether there is a legitimate reason for this.

On Sep 26, 2018, at 8:13 AM, WanLinghao <notifications@github.com> wrote:

@smarterclayton <https://github.com/smarterclayton> Do you think we should
provide some mechanism to let users choose using node's proxy or not. Or
just simply disable the use of node's proxy.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/68607#issuecomment-424692508>,
or mute the thread

**Comment by mshutt** [comment]
Wait, is this an issue wherein the Kubelet's HTTP(S)_PROXY settings are always used for a Liveness/Readiness check?

**Comment by WanLinghao** [comment]
@mshutt yes

**Comment by WanLinghao** [comment]
https://github.com/kubernetes/kubernetes/pull/68663 has fixed this ,close
