### ISSUE TITLE
Make more than one Security Group for the AWS ELB to accommodate more than 50 loadBalancerSourceRanges

### ISSUE THREAD

**Issue by 2rs2ts** [kubernetes/kubernetes#68684]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**: I created a LoadBalancer Service with a list of loadBalancerSourceRanges, with 100 elements in it. The ELB could not be created because there is a limit of 50 security group rules per security group. Here is a snippet from the kube-controller-manager logs.

```
type: 'Warning' reason: 'CreatingLoadBalancerFailed' Error creating load balancer (will retry): failed to ensure load balancer for service kube-system/kubernetes-dashboard: error authorizing security group ingress: "RulesPerSecurityGroupLimitExceeded: The maximum number of rules per security group has been reached.\n\tstatus code: 400
```

**What you expected to happen**: I expected that kube-controller-manager would simply create more than one security group to facilitate the extra rules after the first 50. AWS says that you can have up to 5 security groups attached per ELB, and while there's that group that lets the ELB and the nodes talk to each other, that still leaves 3 more security groups available, right?

**How to reproduce it (as minimally and precisely as possible)**: Create a LoadBalancer Service with more than 50 elements in its loadBalancerSourceRanges list.

**Anything else we need to know?**: N/A

**Environment**:
- Kubernetes version (use `kubectl version`): 1.10.5
- Cloud provider or hardware configuration: AWS
- OS (e.g. from /etc/os-release): Debian Stretch
- Kernel (e.g. `uname -a`): `4.9.0-6-amd64 #1 SMP Debian 4.9.88-1+deb9u1 (2018-05-07)`
- Install tools: N/A
- Others: N/A

**Comment by 2rs2ts** [comment]
@kubernetes/sig-aws-bugs

**Comment by 2rs2ts** [comment]
weird, the /sig command didn't work.

**Comment by dstockton** [comment]
Keep in mind that not all AWS accounts have 50 as their limit - ```rules-per-group * groups-per-interface < 250``` is the limit where ```rules-per-group``` and ```groups-per-interface``` can be defined per account.
Either looking these values up via the API or at least making ```maximum-rules-per-group``` a configurable option would be amazing!

**Comment by christhomas-msm** [comment]
I don't think this ticket needs to be kept alive:

https://kubernetes.io/docs/concepts/cluster-administration/cloud-providers/

describes the use of:
 
service.beta.kubernetes.io/aws-load-balancer-extra-security-groups

which can be used to negate the issue.

**Comment by 2rs2ts** [comment]
Hacky workarounds are not great

**Comment by nckturner** [comment]
I think your request is more of a feature request, because the current behavior is that AWS has an inherent limitation that does not allow it to support more than 50 loadBalancerSourceRanges, and it already notifies the user that its not supported.  Whether or not your proposed solution is a good idea is a worthy discussion though.  

/kind feature

**Comment by 2rs2ts** [comment]
@nckturner

>it already notifies the user that its not supported

It does not. That is an AWS SDK message being bubbled up. This limitation isn't documented (docs [here](https://kubernetes.io/docs/tasks/access-application-cluster/configure-cloud-provider-firewall/)) so as far as I'm concerned this is a bug.

**Comment by mohag** [comment]
There are also unnecessary ranges being added. If a NLB LoadBalancer's access is not filtered, 0.0.0.0/0 is added, but the public subnets are also added, even though they are included in 0.0.0.0/0 (at least on 1.17)

**Comment by richardst89** [comment]
I've encountered this issue when more than 50 ingress rules...
I've combined them onto the same ALB via `alb.ingress.kubernetes.io/group.name`
Is there a way to pre-define the exposed ports as ranges, to avoid each one added as a singular?

(e.g. 6000-6100, instead of 6000, 6001, 6002 rules)

**Comment by ricardojdsilva87** [comment]
Hello everyone,
This would be a good feature to support multiple SG creation in case the list of IPs in the `loadBalancerSourceRanges` would pass the limitation from AWS max of **50 rules per servicegroup**.
We've hit that also during the service creation:
![image](https://user-images.githubusercontent.com/12953702/212017821-69f418ce-d61e-42eb-bf90-f80b4b340326.png)
The only workaround we've found was to create the SG separately using terraform and associate them with the annotation:
`service.beta.kubernetes.io/aws-load-balancer-security-groups: "sg-1,sg-2,sg-3,etc"`
This way the default security group is not created and only these ones would be attached to the classic load balancer.
Thanks!

**Comment by kishorj** [comment]
The issue is due to AWS quota which is 60 by default. An end user can request the quota increase, but the cap is 1000 rules per interface - with the default number of security groups per interface, this translates to 200 rules per SG max. Supporting arbitrary number of rules is not feasible currently.

We could add a feature to provision multiple SG for LB to provide some relief, but the max rules we can get in the default case is 300. You could already extend the quota to 200 rules from the console, so the added complexity of managing auto-provisioning multiple SG doesn't sound worth at the moment. Besides we want to deprecate CLB and move to NLB provisioned via the AWS LBC.

This issue is related to KCM, which is already replaced by CCM. I recommend we close the issue.
Please raise the issue in the following repositories instead:
CCM: https://github.com/kubernetes/cloud-provider-aws/
AWS product/service side features: https://github.com/aws/containers-roadmap
AWS LBC: https://github.com/kubernetes-sigs/aws-load-balancer-controller/
