### ISSUE TITLE
Why do I see all services environment variables in every Service?

### ISSUE THREAD

**Issue by ikercrg** [kubernetes/kubernetes#68731]
**Is this a BUG REPORT or FEATURE REQUEST?**:

 /kind bug

But I am not sure if this is the correct behaviour or I need something in configuration to solve it. 

**What happened**:

I see the environment variables of all deployments I have created in every pod

**What you expected to happen**:

To see only the environment variables defined in the deployment.

**How to reproduce it (as minimally and precisely as possible)**:

Create two deployments with different environment variables. Start the deployments. Go into the one of the pod with "exec -it" and then execute "env". There I see the environment variables of both deployments.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.11.2
- Cloud provider or hardware configuration: AWS
- OS (e.g. from /etc/os-release): ubuntu
- Kernel (e.g. `uname -a`): Linux ip-192-168-1-29 4.4.0-1066-aws #76-Ubuntu SMP Thu Aug 16 16:21:21 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:
/sig environment variables

**Comment by Raffo** [comment]
@ikercrg I'm seeing the same issue, can you share some more info and if you found the root cause of this?

**Comment by Raffo** [comment]
Given that yesterday I was also fooled by this, I think this deserves a better explanation. 

There is no issue of any sort and the behaviour is the expected one: whenever you have a service, some kubernetes defined environment variables for the service will be added as documented here: https://kubernetes.io/docs/concepts/services-networking/service/#environment-variables .

This behaviour can be somehow confusing, especially for newcomers to kubernetes, because of the variables name. I had to look closely to understand what was really happen as the reports from the users of the cluster confused me, don't take for granted that something is really not working 😉
