### ISSUE TITLE
CSI E2E tests: fail with upcoming CSI release

### ISSUE THREAD

**Issue by pohly** [kubernetes/kubernetes#68819]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

When testing k8s master with the "canary" CSI images (= the images which will be tagged as the next release end of this week), the CSI volume tests fail.

PVCs remain pending because the external-attacher runs into a permission issue (from its log):
```
E0919 08:34:56.218106       1 leaderelection.go:224] error retrieving resource lock e2e-tests-csi-mock-plugin-l84wg/csi-hostpath: endpoints "csi-hostpath" is forbidden: User "system:serviceaccount:e2e-tests-csi-mock-plugin-l84wg:csi-hostpath-service-account" cannot get resource "endpoints" in API group "" in the namespace "e2e-tests-csi-mock-plugin-l84wg"
I0919 08:34:56.218136       1 leaderelection.go:180] failed to acquire lease e2e-tests-csi-mock-plugin-l84wg/csi-hostpath
```

**What you expected to happen**:

Should work?

**How to reproduce it (as minimally and precisely as possible)**:

* build k8s master
* start cluster: `RUNTIME_CONFIG= ALLOW_PRIVILEGED=1 FEATURE_GATES="BlockVolume=true,MountPropagation=true,KubeletPluginsWatcher=true"  hack/local-up-cluster.sh -O`
* run tests: `make WHAT=test/e2e/e2e.test && go run hack/e2e.go -- --provider=local --test --test_args="--ginkgo.focus=CSI.plugin.test.using.CSI.driver:.hostPath -csiImageVersion=canary"`

**Anything else we need to know?**:

It works with the latest released versions of the CSI containers (i.e. without `-csiImageVersion=canary`). That is how this test currently runs in the k8s CI.

If new permissions are needed, then https://kubernetes-csi.github.io/docs/Example.html also needs to be updated.

**Comment by pohly** [comment]
/sig storage

@jsafrane the stable version is v0.2.1, which didn't have the leadership election. Which permissions are needed for "endpoints" - obviously "get", probably "set", anything else?

**Comment by pohly** [comment]
It looks like these additional permissions must go into `plugin/pkg/auth/authorizer/rbac/bootstrappolicy/policy.go`, right?

**Comment by pohly** [comment]
I have a fix, but I have no idea whether it is the right one - let's discuss in https://github.com/kubernetes/kubernetes/pull/68821

**Comment by liggitt** [comment]
> were there any issues with Endpoints?

Yes. Constant Endpoint modification floods kubelet and kube-proxy watchers. Prefer the dedicated Lease object. 

> We should add a new ClusterRole for leader election that can edit Endpoints. Say leader-election (or system:leader-election?) The catch is, we should do RoleBinding of this ClusterRole, so attacher + provisioner can modify Endpoints only in their namespaces.

I'd recommend granting access to the lease object in a dedicated role, not configmaps or endpoints. 

Is there a reason not to set up a role that allows read/write access to the specific lease object the component will use?

**Comment by wongma7** [comment]
1. I am reluctant to switch to configmaps so soon because it will be disruptive to users who have already been disrupted by the need to add endpoints permissions. (I thought endpoints was the default from looking at the leaderelection package...and did not check what external-attacher was doing). But this needs to be corrected anyway so I guess it's better to do it sooner, I'll switch it to configmaps.

3. Atm my test creates a `Role` which gives namespace access https://github.com/kubernetes/kubernetes/blob/master/test/e2e/storage/volume_provisioning.go#L799. Giving access only to the specific object is better, I will change the provisioner test to do that, the only thing is that the name of the object depends on the name of the csi driver/storageclass (for external-attacher/external-provisioner respectively)

**Comment by jsafrane** [comment]
> Is there a reason not to set up a role that allows read/write access to the specific lease object the component will use?

I'd prefer to have a pre-created Role/ClusterRole that the deployment of CSI driver would use. We may add  new permissions later and it's easier to update the role than telling all users to update their deployment tools.

**Comment by liggitt** [comment]
> I'd prefer to have a pre-created Role/ClusterRole that the deployment of CSI driver would use.

I understand that is more convenient, but is problematic to couple in-tree roles with out-of-tree components. Such components should be providing their own role and rolebinding definitions for deployer to make use of.

**Comment by liggitt** [comment]
The guideline is that if the component is defined out of tree, the role/binding should be as well

**Comment by jsafrane** [comment]
> Such components should be providing their own role and rolebinding definitions for deployer to make use of.

Is there any prior art? *How* exactly should external component provide roles/binding?

> The guideline is that if the component is defined out of tree, the role/binding should be as well

So, should we remove system:csi-external-attacher role then?

**Comment by liggitt** [comment]
> Is there any prior art? How exactly should external component provide roles/binding?

See examples in the cluster/addons folder, like:

https://github.com/kubernetes/kubernetes/blob/259a59d93618f0266151a50018f3b3f3cbcfc0e4/cluster/addons/dns/coredns/coredns.yaml.base#L12-L47

https://github.com/kubernetes/kubernetes/blob/259a59d93618f0266151a50018f3b3f3cbcfc0e4/cluster/addons/fluentd-elasticsearch/fluentd-es-ds.yaml#L11-L46

> should we remove system:csi-external-attacher role then?

Probably so, after providing the role definitions along with the attacher deployment manifests, announcing deprecation of the built in role, and waiting out the deprecation period.

**Comment by wongma7** [comment]
system:csi-external-provisioner and system:persistent-volume-provisioner should be removed at the same time too then.

**Comment by jsafrane** [comment]
> The guideline is that if the component is defined out of tree, the role/binding should be as well

That makes perfect sense, however it complicates e2e tests - kubernetes/test/e2e either needs the roles to be installed by something or install it by itself (by having a copy of the roles either as yaml or go code in the test).

In addition, users don't read docs and some of them got surprised that they should add new permissions after update. Sure, we can always add more / better docs.

> (or should be in a manifest along with the add-on deployment, not in a compiled-in bootstrap role)

That would be great, only if CSI was an addon. It's not a generic component running in a cluster and providing some useful functionality. It needs a driver provided by admin to work. It can run in any namespace.

Would it be possible to add just the RBAC rules to cluster/addons/rbac/ instead of the default, compiled-in policy? But then the roles are quite far from the external components and we need to sync them once in a while. I have no issues with that and it seems that cluster/addons/rbac/cluster-autoscaler uses that already.

**Comment by liggitt** [comment]
>> (or should be in a manifest along with the add-on deployment, not in a compiled-in bootstrap role)
>
> That would be great, only if CSI was an addon. It's not a generic component running in a cluster and providing some useful functionality. It needs a driver provided by admin to work. It can run in any namespace.

I'm using "add-on" in the generic sense. Providing required function for a given cluster, being admin-installed, and being deployed in an arbitrary namespace are all reasonable characteristics for an add-on. 

> Would it be possible to add just the RBAC rules to cluster/addons/rbac/ instead of the default, compiled-in policy? But then the roles are quite far from the external components and we need to sync them once in a while. I have no issues with that and it seems that cluster/addons/rbac/cluster-autoscaler uses that already.

That would be better than compiling in these permissions. The canonical source should probably be defined in a manifest in the csi component repo. Is there such a manifest there already for setting up the deployment or daemonset?

**Comment by jsafrane** [comment]
`Lease` is not supported by `client-go/tools/leaderelection/leaderelection.go`. So we must stick to endpoints / config maps in 1.12. Since endpoints "floods kubelet and kube-proxy watchers", I propose the provisioner switches to config map. In 1.13 we may add Lease (and users need to update their RBAC once again).

@wongma7, that means new external-storage release and rebase of external-provisioner, right? Do we still have time for that in 1.12 or shall we stick to endpoints there and move everything to Lease in 1.13? It's ugly, but perhaps it's better than rushed releases.

Regarding RBAC rules, we'll keep them in external components (some extra yaml + documentation won't harm) and have a copy in kubernetes/test/e2e/testing-manifests for e2e tests. No addons (for now). We need to sync when  the external components evolve.

@pohly, would this work? The e2e tests need to insert ClusterRoles / Roles manually before the tests.

**Comment by pohly** [comment]
Jan Šafránek <notifications@github.com> writes:

> `Lease` is not supported by `client-go/tools/leaderelection/leaderelection.go`. So we must stick to endpoints / config maps in 1.12. Since endpoints "floods kubelet and kube-proxy watchers", I propose the provisioner switches to config map. In 1.13 we may add Lease (and users need to update their RBAC once again).
>
> @wongma7, that means new external-storage release and rebase of external-provisioner, right? Do we still have time for that in 1.12 or shall we stick to endpoints there and move everything to Lease in 1.13? It's ugly, but perhaps it's better than rushed releases.
>
> Regarding RBAC rules, we'll keep them in external components (some extra yaml + documentation won't harm) and have a copy in kubernetes/test/e2e/testing-manifests for e2e tests. No addons (for now). We need to sync when  the external components evolve.
>
> @pohly, would this work? The e2e tests need to insert ClusterRoles /
> Roles manually before the tests.

That sounds like a good plan, with one nitpick: I don't like that tests depend on a
Kubernetes-specific package like e2e/manifest, because then they aren't
reusable outside of the Kubernetes repo. I am trying to fix that with
the E2E refactoring
(https://github.com/kubernetes/kubernetes/issues/66649). But as that's
something for 1.13, let's not worry about it now.

Shall I try to implement that in
https://github.com/kubernetes/kubernetes/pull/68821 or will you do it?
The current code there doesn't work and it wasn't obvious to me why.

**Comment by pohly** [comment]
One question about the predefined roles and how to replace them with custom roles defined in the E2E tests or some deployment file: `system:csi-external-provisioner` has one optional rule for `csinodeinfos` that only gets added if the `CSINodeInfo` feature is enabled:
https://github.com/kubernetes/kubernetes/blob/4ca39ef0edfcbf4361754fcae2a426009f8e2053/plugin/pkg/auth/authorizer/rbac/bootstrappolicy/policy.go#L504-L518

How can this `if` check be replicated outside of Kubernetes itself? Or is it that this rule now always has to be added, just in case that it is needed (which might not be the case)?

**Comment by jsafrane** [comment]
I created #68887. That's enough for me to run hostpath tests on my machine.

**Comment by jsafrane** [comment]
> How can this `if` check be replicated outside of Kubernetes itself.

I think that it's fine to add permissions even for features behind a feature gate in this case.

**Comment by wongma7** [comment]
>  @wongma7, that means new external-storage release and rebase of external-provisioner, right? Do we still have time for that in 1.12 or shall we stick to endpoints there and move everything to Lease in 1.13? It's ugly, but perhaps it's better than rushed releases.

Yes it means another release. Actually I didn't know about this `Lease` object so, I think if we are going to move to it in 1.13 anyway let's keep external-provisioner on endpoints for 1 release and avoid rushing yet another release within 1.12 timeframe. Waiting until 1.13 will be easier to communicate and easier for users to stomach, they can update external-attacher+external-provisioner in one go. So let's stick to endpoints for now, just 1 release. :+1:

**Comment by pohly** [comment]
I ended up coding up a slightly different solution in https://github.com/kubernetes/kubernetes/pull/68821.

**Comment by davidz627** [comment]
Hi all, I noticed that the conversation kind of floated between this issue and 2 other PR's so in an effort to understand what was going on and what was decided I made a little summary that I will share here. Let me know if there is any misunderstanding or omission and I can edit this comment.

Assumptions:
1. Each driver may require a different set of cluster roles to function
2. Tests should be able to run in parallel
3. Cluster roles should be easy(ish) to patch
4. ClusterRoles in production deployment and test should not differ

Conclusions:
1. We should use manifest yamls instead of bootstrapped roles or roles in code (1) (3) (https://github.com/kubernetes/kubernetes/pull/68821#issuecomment-423252660)
2. We should deprecate the bootstrapped cluster roles ASAP (3) (1) (https://github.com/kubernetes/kubernetes/issues/68819#issuecomment-422834929)
2. Cluster Role names should be unique, potentially even tagging UUID's onto the end of the names when creating from manifests (2) (1)
3. Ideally some sort of sync/import of the manifests between the external repo (source of truth) and the test manifest (4)

**Comment by pohly** [comment]
David Zhu <notifications@github.com> writes:
> Assumptions:
> 1. Each driver may require a different set of cluster roles to function
> 2. Tests should be able to run in parallel
> 3. Cluster roles should be easy(ish) to patch
> 4. ClusterRoles in production deployment and test should not differ
>
> Conclusions:
> 1. We should use manifest yamls instead of bootstrapped roles or roles in code (1) (3) (https://github.com/kubernetes/kubernetes/pull/68821#issuecomment-423252660)
> 2. We should deprecate the bootstrapped cluster roles ASAP (3) (1) (https://github.com/kubernetes/kubernetes/issues/68819#issuecomment-422834929)
> 2. Cluster Role names should be unique, potentially even tagging UUID's onto the end of the names when creating from manifests (2) (1)
> 3. Ideally some sort of sync/import of the manifests between the external repo (source of truth) and the test manifest (4)

I agree that this is a good direction. Both PRs address a subset of this
(Jan's starts to use manifests, mine drops usage of the boostrapped
cluster roles). I'm fine with merging PR #68887 first and then
continuing the work based on that.

**Comment by pohly** [comment]
Jordan Liggitt <notifications@github.com> writes:
> The guideline is that if the component is defined out of tree, the role/binding should be as well

The CSI WG confirmed today that this is the way forward, which now begs
the question: can we just outright remove the already incomplete builtin
roles (system:csi-external-provisioner and system:csi-external-attacher)
from
https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/auth/authorizer/rbac/bootstrappolicy/policy.go
or is some kind of deprecation period needed?

To the best of my knowledge those rules were never really
documented. The
https://github.com/kubernetes-csi/docs/blob/master/book/src/example
didn't use them and neither did the sidecar container docs (as far as
they exist, see
https://github.com/kubernetes-csi/external-attacher/commits/master/deploy/kubernetes/deployment.yaml).

Personally I'm in favor of simply removing them. I can create a PR which
drops them together with adding a replacement for their usage in the
test/e2e/storage test.

@liggitt what do you think?

**Comment by liggitt** [comment]
> Personally I'm in favor of simply removing them. I can create a PR which drops them together with adding a replacement for their usage in the test/e2e/storage test. @liggitt what do you think?

It costs us very little to maintain them. I'd prefer we announce deprecation and add a comment to remove at the end of the deprecation period.

**Comment by pohly** [comment]
Jordan Liggitt <notifications@github.com> writes:
>> Personally I'm in favor of simply removing them. I can create a PR which drops them together with adding a replacement for their usage in the test/e2e/storage test. @liggitt what do you think?
>
> It costs us very little to maintain them.

But what does "maintain" really mean for them? Update them in parallel
to the .yaml files that replace them (or, probably, have always been
used instead)?

We'd have to have E2E testing in two flavors, once without the builtin
rules and once with, so maintenance does come with a certain cost.

> I'd prefer we announce
> deprecation and add a comment to remove at the end of the deprecation
> period.

What is the deprecation period in this case?
