### ISSUE TITLE
CSI E2E: per-test ClusterRoles

### ISSUE THREAD

**Issue by pohly** [kubernetes/kubernetes#68888]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> /kind feature

**What happened**:

At the moment, the E2E CSI test creates ClusterRoles under fixed names and never deletes or overwrites them. This is intentional, the argument being that it allows running tests in parallel:
https://github.com/kubernetes/kubernetes/blob/d1111a57d9243c55e02e0e66af55c2ddb36f3767/test/e2e/storage/csi_objects.go#L62-L64

**What you expected to happen**:

This behavior is surprising. For example, I just ran the test, updated rules, then ran the test again. The second run didn't use the updated rules.

I think it would be better to create unique names for each test run and then destroy them when the test is done. That supports parallel test runs *and* avoids leaving behind garbage.

@davidz627 what do you think?
/sig storage

**Comment by davidz627** [comment]
Hmm that'a an interesting use case I didn't anticipate. It's interesting because `system:csi-external-provisioner` and `system:csi-external-attacher` are bootstrapped when bringing the cluster up. The driver registrar cluster role creation in the test here is just a "temporary hack" to get things to work until the Kubelet registration work is Beta (we no longer need the driver registrar IIUC).

So in the interest of consistency I would prefer the driver registrar cluster role here be treated as if it were a cluster bootstrapped role and not torn down at the end of the test. If it needs to be changed it could be changed manually just liked how you'd need to change `system:csi-external-provisioner` and `system:csi-external-attacher` if you wanted to try different things with those.

Thanks for looping me in, let me know if you disagree or have a compelling reason to change it! :+1:

**Comment by pohly** [comment]
David Zhu <notifications@github.com> writes:
> Hmm that'a an interesting use case I didn't anticipate. It's
> interesting because `system:csi-external-provisioner` and
> `system:csi-external-attacher` are bootstrapped when bringing the
> cluster up.

Which actually turned out be problematic, too. See
https://github.com/kubernetes/kubernetes/issues/68819. The current
trend there is to not use bootstrapped roles and instead rely on the
deployment to have proper rules.

> The driver registrar cluster role creation in the test
> here is just a "temporary hack" to get things to work until the
> Kubelet registration work is Beta (we no longer need the driver
> registrar IIUC).

Creating roles might become a permanent solution. Let's wait for the
other discussion to settle and then come back to the question of how to
do it. I just didn't want to forget it, hence this issue.

**Comment by davidz627** [comment]
I see, looks like we should wait for consensus on the problem in general before coming to a implementation decision about teardown.

**Comment by pohly** [comment]
RBAC roles are now namespaced or renamed where necessary (see test/e2e/framework/create.g), so this can be considered resolved.
