### ISSUE TITLE
Run-once daemonset

### ISSUE THREAD

**Issue by IvanovOleg** [kubernetes/kubernetes#69001]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:

/kind feature

**What happened**:
I want to add a kubernetes extended resource to each node that appears in the cluster. I created a daemonset that creates that resource, but it performs endless restarts of the completed pods.

**What you expected to happen**:
Daemonset doesn't restart completed pods

**How to reproduce it (as minimally and precisely as possible)**:
Any daemonset with completed pod.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T17:53:03Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration: Azure
- OS (e.g. from /etc/os-release): CoreOS
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by IvanovOleg** [comment]
@kubernetes/sig-feature-requests

**Comment by IvanovOleg** [comment]
@kubernetes/sig-apps-feature-requests

**Comment by k82cn** [comment]
This should be a requirement to Job instead of DaemonSet.

**Comment by kow3ns** [comment]
This is a dup of [36601](https://github.com/kubernetes/kubernetes/issues/36601). This was closed because its unlikely to be implemented as a core resource and we won't be modifying DaemonSet to be run once. You should consider implementing an extension that meets this use case using [kubebuiler](https://github.com/kubernetes-sigs/kubebuilder) or [metacontroller](https://github.com/GoogleCloudPlatform/metacontroller). The general direction of the project is moving towards a small stable core with better support for custom extensions to meet use cases like this.
/close

**Comment by ant31** [comment]
Also I'd recommend to just use a ds with a control-loop if the state of the node.

Instead of deploying a job that install something once, I d deploy a daemonset that checks if it's deployed every n minutes. 

This way it would sustain misconfiguration/reboot/manual edit or anything that would maybe reset the state.
