### ISSUE TITLE
The provider 'libvirt' could not be found,

### ISSUE THREAD

**Issue by wkevils** [kubernetes/kubernetes#6900]
Hi all, 

I am following "Getting started with Vagrant" directions in:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/vagrant.md

I am running on Fedora 21, where the following vagrant rpm is installed: vagrant-1.7.2-3.fc21.1.noarch
I installed Virtual Box on this machine, as required.

When I run
export KUBERNETES_PROVIDER=vagrant
and 
curl -sS https://get.k8s.io | bash

I get this error:
"The provider 'libvirt' could not be found, but was requested to
back the machine 'master'. Please use a provider that exists."

The full log is following:
Downloading kubernetes release v0.14.1 to /work/down/kubernetes.tar.gz
--2015-04-16 13:01:38--  https://storage.googleapis.com/kubernetes-release/release/v0.14.1/kubernetes.tar.gz
...
Saving to: ‘kubernetes.tar.gz’

kubernetes.tar.gz    100%[=======================>]  60.98M  3.78MB/s   in 19s

2015-04-16 13:01:57 (3.25 MB/s) - ‘kubernetes.tar.gz’ saved [63947089/63947089]

Unpacking kubernetes release v0.14.1
Creating a kubernetes on vagrant...
Starting cluster using provider: vagrant
... calling verify-prereqs
... calling kube-up
Using credentials: vagrant:vagrant
/usr/share/vagrant/lib/vagrant/pre-rubygems.rb:31: warning: Insecure world writable dir /work/tools/scripts in PATH, mode 040777
/usr/share/gems/gems/bundler-1.7.6/lib/bundler/runtime.rb:222: warning: Insecure world writable dir /work/tools/scripts in PATH, mode 040777
The provider 'libvirt' could not be found, but was requested to
back the machine 'master'. Please use a provider that exists.

Any idea what the problem is ? 

Kevin

**Comment by erictune** [comment]
I can't find that error string in the kubernetes git tree, so I think it may be coming out of vagrant or virtualbox.

**Comment by erictune** [comment]
Are you able to create a VM directly using vagrant?

**Comment by wkevils** [comment]
>Are you able to create a VM directly using vagrant?

To avoid misunderstanding: what should I try ? I only followed the directions, and do not have experience with vagrant.

**Comment by derekwaynecarr** [comment]
What vagrant plug-ins do you have installed?

**Comment by wkevils** [comment]
First, "rpm -qa | grep vagrant" shows only one rpm, the vagrant rpm, and not plugin.
Second, trying 
vagrant init hashicorp/precise32 and then
vagrant up
gives the same error:

The provider 'libvirt' could not be found, but was requested to
back the machine 'master'. Please use a provider that exists."

Any ideas? 
Can somebody try one of these two sequences to see if it works for him ? 


Kevin

**Comment by erictune** [comment]
`vagrant init hashicorp/precise32 and then
vagrant up
`
works fine for me on my OS X machine.
It uses the virtualbox provider.

You might need to do:
`vagrant plugin install libvirt`


Or poke around http://docs.vagrantup.com/v2/plugins/usage.html

**Comment by derekwaynecarr** [comment]
Can you output the result of 

```shell
$ vagrant plugin list
```

**Comment by kjiwa** [comment]
You can resolve this issue on Fedora 21 by installing the "vagrant-libvirt" package.

**Comment by ssb22** [comment]
If you're stuck on an old Fedora box and want Vagrant to use VirtualBox instead of libvirt (for example because something has gone wrong with your SELinux or kvm configuration that prevents you from bringing up boxes on libvirt), you could try putting `export VAGRANT_DEFAULT_PROVIDER=virtualbox` into your `~/.bashrc`—this is the upstream default, but at least some versions of Fedora's packages override it.  If VirtualBox then complains the kernel module is not loaded, you might have to run `sudo /etc/init.d/vboxdrv setup`—and if that says your kernel headers cannot be found, do `sudo yum install kernel-devel` first (I don't know why Fedora didn't make `kernel-devel` a dependency of the `dkms` package).  If `vboxdrv` then tells you to look at `make.log` and the log says "void value not ignored as it ought to be", edit the `SUPDrv-linux.c` file it mentions and change `rc = misc_deregister` to `rc=0; misc_deregister` (in two places), and also make the same changes to `/usr/share/virtualbox/src/vboxhost/vboxdrv/linux/SUPDrv-linux.c` and try again. You might then run into other problems compiling those kernel modules. This is the kind of thing that makes me feel Debian is better than Red Hat.  At least Docker works on both even if Vagrant doesn't.
