### ISSUE TITLE
RFE: E2E: Upstream kube_conformance container 

### ISSUE THREAD

**Issue by timothysc** [kubernetes/kubernetes#69110]
**Is this a FEATURE REQUEST?**:
This container: https://github.com/heptio/kube-conformance should really live upstream and be a build artifact owned by k/k.

/sig testing 
/kind feature
/cc @kubernetes/sig-testing @kubernetes/cncf-conformance-wg

**Comment by stevekuznetsov** [comment]
Questions I had in the meeting all surround how the container will run `ginkgo` - are we expecting it to self-resolve cloud provider details or be fed them? How will it choose a parallelism value? Overall idea here is great.

**Comment by BenTheElder** [comment]
> are we expecting it to self-resolve cloud provider details or be fed them

conformance tests are not supposed to be cloud provider aware! so that solves that :-)

for other details like parallelism, supply via args / env? worst case as long as the binaries are in PATH or a well known location the image user can always orchestrate it further however they need but still have canonical binaries to execute packaged up in an image.

**Comment by timothysc** [comment]
@stevekuznetsov 

>How will it choose a parallelism value? 

It's already option enabled in the wrapped runner. 

> are we expecting it to self-resolve cloud provider details or be fed them?

In the long haul cloud-providers will move as a separate apply step, so they should be discoverable by the suite at startup.

**Comment by dims** [comment]
This is done in principle. please see follow ups in: https://github.com/kubernetes/kubernetes/issues/69778 and https://github.com/kubernetes/kubernetes/issues/69777

/close
