### ISSUE TITLE
k8s.io/api 1.12.0 is not tagged properly

### ISSUE THREAD

**Issue by tamalsaha** [kubernetes/kubernetes#69214]
I am trying to revendor my repos to use Kubernetes 1.12 and it seems that k8s.io/api repo is not tagged properly. This is the error message I am getting:

```
# github.com/appscode/kutil/vendor/k8s.io/kubernetes/pkg/apis/core/v1
vendor/k8s.io/kubernetes/pkg/apis/core/v1/conversion.go:385:10: undefined: "github.com/appscode/kutil/vendor/k8s.io/api/core/v1".ProcMountType
vendor/k8s.io/kubernetes/pkg/apis/core/v1/conversion.go:386:6: out.ProcMount undefined (type *"github.com/appscode/kutil/vendor/k8s.io/api/core/v1".SecurityContext has no field or method ProcMount)
vendor/k8s.io/kubernetes/pkg/apis/core/v1/zz_generated.conversion.go:4077:42: in.FSType undefined (type *"github.com/appscode/kutil/vendor/k8s.io/api/core/v1".LocalVolumeSource has no field or method FSType)
vendor/k8s.io/kubernetes/pkg/apis/core/v1/zz_generated.conversion.go:4088:5: out.FSType undefined (type *"github.com/appscode/kutil/vendor/k8s.io/api/core/v1".LocalVolumeSource has no field or method FSType)
vendor/k8s.io/kubernetes/pkg/apis/core/v1/zz_generated.conversion.go:6729:57: in.ProcMount undefined (type *"github.com/appscode/kutil/vendor/k8s.io/api/core/v1".SecurityContext has no field or method ProcMount)
vendor/k8s.io/kubernetes/pkg/apis/core/v1/zz_generated.conversion.go:6747:5: out.ProcMount undefined (type *"github.com/appscode/kutil/vendor/k8s.io/api/core/v1".SecurityContext has no field or method ProcMount)
vendor/k8s.io/kubernetes/pkg/apis/core/v1/zz_generated.conversion.go:6747:20: undefined: "github.com/appscode/kutil/vendor/k8s.io/api/core/v1".ProcMountType
vendor/k8s.io/kubernetes/pkg/apis/core/v1/zz_generated.conversion.go:7258:41: cannot convert in.APIGroup (type string) to type unsafe.Pointer
vendor/k8s.io/kubernetes/pkg/apis/core/v1/zz_generated.conversion.go:7270:15: cannot use (*string)(unsafe.Pointer(in.APIGroup)) (type *string) as type string in assignment
```

I see no `FSType` in `LocalVolumeSource` https://github.com/kubernetes/api/blob/kubernetes-1.12.0/core/v1/types.go#L1601:6

But k8s.io/kubernetes seem to point to it https://github.com/kubernetes/kubernetes/blob/v1.12.0/pkg/apis/core/v1/zz_generated.conversion.go#L4075

/kind bug
/sig api-machinery
/sig release

**Comment by tamalsaha** [comment]
k8s.io/api is tagged correctly for staging repo. The staging repo has out-dated types. https://github.com/kubernetes/api/blob/kubernetes-1.12.0/core/v1/types.go#L1601

**Comment by nikhita** [comment]
Thanks, taking a look.

**Comment by tamalsaha** [comment]
@sttts has confirmed that this is a tagging issue in Slack. Here is the link to slack conversation: https://kubernetes.slack.com/archives/C0EG7JC6T/p1538130457000100 .

**Comment by nikhita** [comment]
@sttts can you ptal if this makes sense? I suspect this is the reason but I still have qualms if I'm understanding the git behaviour right.

I think we can discuss this in real time on slack better but I thought I'd dump my thoughts here instead of writing a huge slack message. And it's also good for others following along and future reference. :)

---

Some background for people reading this about how we publish the tags: First, we get a list of first-parents in k/k's release-1.12 branch (`kFirstParents`) and a list of first-parents in the repo's release-1.12 branch (`dstFirstParents`). Then we create a map of kube's first parents to destination's first parents (some commits are collapsed, more on that below).

Looking at the recent [logs](https://gist.githubusercontent.com/sttts/ce2e592052531e3ae9ff02687b881c5c/raw/4d52ad81f10b35708792ba462206fd442489bacb/gistfile1.txt) for `SourceCommitToDstCommits`'s output for k8s.io/api, that show the kubehash, dstHash and the kube commit message, it can be seen that the first four dstHashes are wrong.

```
30fae457d593d04783223d60c7d6c804e60cab7e 1b7003d0d679cdd8fa4121a3304319ec4c6139f2 Add/Update CHANGELOG-1.12.md for v1.12.0.
8c99de67175609f0cc9e6ecad347970488fcb649 1b7003d0d679cdd8fa4121a3304319ec4c6139f2 Kubernetes version v1.12.1-beta.0 openapi-spec file updates
0ed33881dc4355495f623c6f22e7dd0b7632b7c0 1b7003d0d679cdd8fa4121a3304319ec4c6139f2  wsBcBAABCAAQBQJbqrLxCRBK7hj4Ov3rIwAAdHIIALBfEQrnLWW/lEb9l6IvBP6I
b2dcf742240ee37e50f0cc8d51709c2540e577fe 1b7003d0d679cdd8fa4121a3304319ec4c6139f2 Merge remote-tracking branch 'origin/master' into release-1.12
aa8089fd81e2b5ee46ec02d486f8fe855e38320b b9bd491cc8f21b9461d2a6cf277542dc4c53e7fc Add/Update CHANGELOG-1.12.md for v1.12.0-rc.2.
```

They point to an old commit. When we try to create a tag, we check the kubehash's corresponding dstHash in the map and point to it. Since this dstHash is an old one, the tag gets pointed to an older commit and we end up missing commits.

---

Why this occurs:

Looking at the pattern in how this occurs across other staging repos, I found that the old commit that the tags point to is always the latest first-parent commit in the destination repo, whose corresponding Kube commit is _not_ a first-parent in k/k.

I suspect this occurs because of the [`MergePoints`](https://github.com/kubernetes/publishing-bot/blob/a17f79a4dc0541198e77f1c6dd2a88e359265ff6/pkg/git/mainline.go#L68) func which calculates the mapping of feature branch commits to mainline commits in kube.

The function loops through all mainline commits and updates a mainline commit's parents' `bestMergePoints` to this mainline commit. In this process, if it comes across another mainline commit, it ignores it. I suspect that while doing so if one of the mainline commits (M1) is a ff merge commit and has other merge commits as parents, this can lead to a lot (I'm guessing all?) of non-mainline merge commits getting marked as the same position as M1.

For instance, in the k8s.io/api's case, looking at the path from 1b7003d0d679cdd8fa4121a3304319ec4c6139f2's corresponding Kube commit 37b29297aa4096d293637af148a0b371cfe66b5f to the latest ff merge commit in k/k b2dcf742240ee37e50f0cc8d51709c2540e577fe by `git rev-list --ancestry-path 37b29297aa4096d293637af148a0b371cfe66b5f...b2dcf742240ee37e50f0cc8d51709c2540e577fe`, we see that this path can be walked through by using only non-mainline merge commits.

So when we build the map for `dstFirstParents` against Kube mainline commits by looping through `dstFirstParents` in [this code](https://github.com/kubernetes/publishing-bot/blob/a17f79a4dc0541198e77f1c6dd2a88e359265ff6/pkg/git/mapping.go#L53-L67) and we reach the latest `dstFirstParent` whose corresponding Kube commit is not a mainline/first-parent commit in k/k, it gets mapped against the latest mainline ff merge commit from k/k. Or in other words, the latest ff merge commit gets mapped to an old commit.

---

About why this got fixed with subsequent tagging for rc1, rc2 and beta2 tags for 1.12: Only the _latest_ mainline ff merge commit (and the commits created after that) get mapped to the old commit. Commits before that get mapped correctly.

When these tags were first pushed, they were pointing to the latest mainline merge commit. When we pushed them again after sometime, the branch had moved forward and contained new merge commits. Since the tags weren't pointing to the latest merge commits anymore, they were mapped correctly and tags were published right.

**Comment by nikhita** [comment]
Also, I can verify the above behaviour on 1.11 tags as well. :scream: 

However, we don't loose much info there because the only commits that are missing are merge commits which don't contain any diffs. The 1.12 tags had a significant difference which made it easier for us to find them.

**Comment by sttts** [comment]
Fixed by https://github.com/kubernetes/publishing-bot/pull/116.
