### ISSUE TITLE
apiextensions: extract content of labelSelectorPath of custom resource as a LabelSelector?

### ISSUE THREAD

**Issue by hex108** [kubernetes/kubernetes#69257]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:

Now apiextensions extracts content of `labelSelectorPath` of custom resource as a string. And we point `labelSelectorPath` to a `LabelSelector` in our CRD, does it make more sense to extract it as a `LabelSelector`?

`Spec.Selector` in `deployment`/`replicaset`/`replicationcontroller`/... is a map, and converted to a string when used for HorizontalPodAutoscaler scale. e.g. for `deployment`:

`pkg/registry/extensions/deployment/storage/storage.go`

```
func scaleFromDeployment(deployment *extensions.Deployment) (*autoscaling.Scale, error) {
       	selector, err := metav1.LabelSelectorAsSelector(deployment.Spec.Selector)
         ...
	Selector: selector.String(), 
```

BTW: if we allow `labelSelectorPath` under `spec` in #67824, it will be more convenient to point `labelSelectorPath` to `.spec.Selector`.

**Comment by hex108** [comment]
/area custom-resources
cc @sttts @DirectXMan12 @liggitt @nikhita

**Comment by roycaihw** [comment]
Hi @hex108, I see that you're already on the https://github.com/kubernetes/kubernetes/pull/67824 thread. Does the background provided in https://github.com/kubernetes/kubernetes/pull/67824#issuecomment-425999094 and https://github.com/kubernetes/kubernetes/issues/66688#issuecomment-425996199 answer your question in this issue? From what I read, `labelSelectorPath` was designed intentionally to be a string to hide the complexity of `user-facing API <-> opaque serialized form` conversion to custom controllers. 

cc @enisoc 
who is the expert on this. Please correct me if I interpreted it wrong.

**Comment by enisoc** [comment]
@roycaihw I think you interpreted it correctly.

This issue represents an idea for how to rethink the design for how apiextensions-apiserver fills in ScaleStatus.Selector for you. I think it's worth discussing since it would be nice for custom controller authors to not have to do the conversion themselves.

I'm not sure if this was clear from the top post in this thread, but one requirement is that whatever form we use to extract the Spec.Selector, we need to convert it to the string (query param) form before putting it in ScaleStatus.Selector.

In order to know how to do this conversion, we need to know the schema of Spec.Selector. Is it a `map[string]string` like in Service and ReplicationController? Or a `metav1.LabelSelector` like in Deployment and StatefulSet?

One could argue it would be reasonable to say `map[string]string` is deprecated and assume all CRDs use `metav1.LabelSelector`, but then what if hypothetically there is a `metav2.LabelSelector` someday?

That seems to imply we need to design a way for CRD authors to tell us what form to assume for `Spec.Selector`. That's probably feasible, but it does require some thought.

**Comment by liggitt** [comment]
> We could also just have the selector types all just implement an interface, and then rely on calling a method in that interface

not quite sure what you mean by that... serialized API fields (which is what this jsonpath points at) don't have code associated

**Comment by DirectXMan12** [comment]
Yeah, I realized that after I wrote it, but couldn't find the tab with the comment again ;-).  I may or may not be particularly awake this morning :-)

**Comment by hex108** [comment]
@roycaihw @enisoc I get it now, thanks! 

Is it possible to add a filed(e.g. `labelSelectorType`) to indicate the type of `labelSelector` for some commonly used types(e.g. `string`, `map[string]string`, `metav1.LabelSelector`)?

**Comment by enisoc** [comment]
@hex108 At first glance, something like that sounds reasonable given that we have the current mechanism as a fallback for anything not supported. We should also consider whether the burden of spitting out a stringified label selector is heavy enough to justify adding a convenience feature for something that's already possible in a more general but less convenient way. I don't have a strong opinion either way; I'm just saying someone will probably raise that point on a hypothetical KEP about such a feature.
