### ISSUE TITLE
GKE bind: address already in use error on container network.

### ISSUE THREAD

**Issue by astorath** [kubernetes/kubernetes#69364]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind feature

**What happened**:
We are using GKE with preemptible instances and flannel network (`--no-enable-network-policy`). _Sometimes_, we get pods in a crash loop with `address already in use` error. This happened with **nginx-ingress** pods and **tiller** pods (neither make use of host networking). Deleting a pod gets it scheduled on other node and everything works fine.

**What you expected to happen**:
-

**How to reproduce it (as minimally and precisely as possible)**:
No idea -/

**Anything else we need to know?**:
Example error message for **tiller**:
```
"[main] 2018/09/25 15:51:32 Server died: listen tcp :44134: bind: address already in use"
```
Example error message for **nginx-ingress-controller**:
```
jsonPayload: {
  message:  "listen tcp :10254: bind: address already in use"   
  pid:  "6"   
  source:  "main.go:308"   
 }
```

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-08T16:31:10Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.7-gke.2", GitCommit:"8d9503f982872112eb283f78cefc6944af640427", GitTreeState:"clean", BuildDate:"2018-09-13T22:19:55Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
GKE, version 1.10.7-gke.2 (this happened on 1.10.6-* also), COS
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`): ?
- Install tools: ?
- Others: ?

/sig gcp
/sig node
/sig cloud-provider

**Comment by mrIncompetent** [comment]
We're running into this problem as well. This happened so far across multiple pods (not specific to a application).
We use the same versions as above, though we have normal instances and network policies enabled.

**Comment by mkozjak** [comment]
Just ran into this one as well, using Tiller. Managed to get tiller working by killing the pod with kubectl.
/remove-lifecycle stale

**Comment by japettyjohn** [comment]
Ran into the same thing on my cluster, nodes running 1.10.7-gke.9 and master 1.11.7-gke.12. This started happening during a spike in CPU usage which caused autoscaling on one of the deployments, then resulting in autoscaling in the node pool. The few pods where the error was happening was on an existing node, not the one added as a part of scaling. Network on my cluster is not native VPC.

**Comment by thockin** [comment]
Can anyone help me to repro this?  I have never seen it, and I don't have a lot to go on...

**Comment by japettyjohn** [comment]
@thockin I still have some pods doing this (going on 3 weeks), I left them up so they could be used for forensics.

In my case the process is trying to bind to 8080 and fails, "Error stopping HTTP server on port :8080 - listen tcp :8080: bind: address already in use". At the time it started there was another deployment which autoscaled out of control and had a far lower memory request than was needed, resulting in some OOM on the node. Possibly there is a derelict process in the network space of the pod.

What data can I pull which would be useful?

**Comment by erichorwath** [comment]
> 
> 
> Ran into the same thing on my cluster, nodes running 1.10.7-gke.9 and master 1.11.7-gke.12. This started happening during a spike in CPU usage which caused autoscaling on one of the deployments, then resulting in autoscaling in the node pool. The few pods where the error was happening was on an existing node, not the one added as a part of scaling. Network on my cluster is not native VPC.
> 
> This appears to have started with OOM on the node. The node went from a READY to NOT READY, freaked out for a bit and recovered without terminating the VM. During this process it appeared to attempt to kill containers with limited success and some orphan pods left around.
> 
> Given the above this situation may be able to be recreated with a few grossly underestimated memory request.

This perfectly describes our (reproducible!) problem what we have with Kubernetes 1.18.12!


Our journey started with some nginx containers with low limit of 96Mi, they were going crazy:
![image](https://user-images.githubusercontent.com/70013998/107333928-61109180-6ab6-11eb-8e08-7cd4bbab5d99.png)
![image](https://user-images.githubusercontent.com/70013998/107333613-0414db80-6ab6-11eb-9c07-6b33afa89046.png)
"containerd continues to bubble up [OOM] events and dockerd blindly log such events." -> https://github.com/docker/for-linux/issues/670 
That's why we saw dockerd memory growth until node crashed hard:
![image](https://user-images.githubusercontent.com/70013998/107334044-86050480-6ab6-11eb-9940-8ac1ee2e2d9d.png)
![image](https://user-images.githubusercontent.com/70013998/107334059-8c937c00-6ab6-11eb-8ec4-106666f5850c.png)

meanwhile the node-problem-detector was doing nothing but producing a bunch of logs:
![image](https://user-images.githubusercontent.com/70013998/107334292-cebcbd80-6ab6-11eb-8eeb-3a129a9904d7.png)
Probably related to https://github.com/kubernetes/kubernetes/issues/96746

After the node has crashed multiple times, we manually deleting the node and added a new node. Then we finally got into the `bind: address already in use` error in calico:
![image](https://user-images.githubusercontent.com/70013998/107334510-193e3a00-6ab7-11eb-8a08-fb7107c07f59.png)

Not sure, if I'm in the correct Github issue but I would love if somebody could look into this calico problem :)
