### ISSUE TITLE
New field in Pod spec cause issues with DaemonSet

### ISSUE THREAD

**Issue by mortent** [kubernetes/kubernetes#69445]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

The change in #68754 added a new field (`enableServiceLinks`) to the Pod spec that is set to true by default. This is causing problems for DaemonSets in some situations. 

DaemonSets are using ControllerRevisions to keep track of previous configurations and each revision will contain among other things the Pod spec for the DaemonSet. If a DaemonSet is created with the enableServiceLinks property is set to true, the ControllerRevision will also contain this field. If the cluster is rolled back to a previous version of kubernetes, the DeamonSet struct does not have this field and so the ControllerRevision and the DaemonSet will no longer match. This leads to a new ControllerRevision being created and a rolling update of all pods in the DaemonSet.

Would it be a better solution to rename the field to `disableServiceLinks` and enable service links whenever the field is not set? This would fix the problem with the DaemonSets unless the field is explicitly set before the rollback.

This is causing the master upgrade tests to fail as reported in #69356

/sig apps
/cc @kow3ns
/cc @dchen1107
/cc @thockin

**Comment by k82cn** [comment]
@kubernetes/sig-apps-bugs

**Comment by tnozicka** [comment]
I guess the change in podSpec and the defaulting will break all the workload resources as they are based on comparing the template's podSpec.

Is the new value defaulted to true also for the DaemonSet's podSpec template? If not, controller might go hot loop like with mutating admission controllers.

I don't like us making such changes to v1 podSpec. The other way around seems more sensible.

/cc @smarterclayton

**Comment by smarterclayton** [comment]
> This leads to a new ControllerRevision being created and a rolling update of all pods in the DaemonSet.

Why is this a bad thing?

> I don't like us making such changes to v1 podSpec

We will continue to add fields to podSpec - the issue isn't the defaulting (this would happen regardless of which way it defaulted), it's that the controller can't really be version aware.

The new value would default to true in the daemonset as well.

**Comment by smarterclayton** [comment]
> Would it be a better solution to rename the field to disableServiceLinks and enable service links whenever the field is not set? 

I'm not sure that a rollback requiring daemonsets to recreate is a bug.  I think that's potentially "the best possible thing that we can do in that case".

**Comment by AishSundar** [comment]
/cc @kow3ns 

SIG Release blocking dashboard with upgrade test failures - https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gce-new-master-upgrade-master

**Comment by kow3ns** [comment]
@smarterclayton 

So the problem isn't the fact that a field has been added. It the way in which the field was added. enableServiceLinks is bool pointer that defaults to true. To be backward compatible it should be something like 
```golang 
disableServiceLinks *bool
```
where the new default behavior is to assume that service links are enabled, and the field should be set on an opt out basis to disable the service links.
compatiblity
As it is if you create a new DaemonSet and then roll back cluster to a prior version, or if you have a failover in a HA setup, you can trigger a simultaneous rolling restart of all DaemonSets you created even though you didn't explicitly configure (and may not even be aware of) the new feature.

If we respect backward compatibility and make the feature explicitly opt-out (that is the semantics we are going for here in either ca
So the problem isn't the fact that a field has been added. It the way in which the field was added. enableServiceLinks is bool pointer that defaults to true. To be backward compatible it should be something like 
```golang 
disableServiceLinks *bool
```
where the new default behavior is to assume that service links are enabled, and the field should be set on an opt out basis to disable the service links.
compatiblity
As it is if you create a new DaemonSet and then roll back cluster to a prior version, or if you have a failover in a HA setup, you can trigger a simultaneous rolling restart of all DaemonSets you created even though you didn't explicitly configure (and may not even be aware of) the new feature.

If we respect backward compatibility and make the feature explicitly opt-out (that is the semantics we are going for here in either case), you won't trigger the rolling restart on rollback or controller manager failoverse), you won't trigger the rolling restart on rollback or controller manager failover unless you explicitly opt out of the behavior.

I don't see why the former behavior is more desirable than the latter.

**Comment by bradhoekstra** [comment]
For background/context, the choice between enable/disable was initially discussed here:
https://github.com/kubernetes/community/pull/1249

**Comment by thockin** [comment]
@kow3ns Are you saying that the issue is that default value is not the same as the Go "zero value" ?

The concept of zero value is interesting but it forces APIs to bend into unnatural shapes to respect it.  Since forever Kubernetes has explicitly said that we have version-specific default values which ARE NOT governed by zero values, but instead are governed by the API version.  It is safe to assume that if a field is documented as having a default in a version, you can  rely on that field being populated with that default, with a few exceptions.

We generally ask for boolean fields to be "in the affirmative direction", as in this case.

Now, we could revisit this.  It would be a significant change in direction, but it's not impossible.  But I don't think that solves your problem in general -- if this field were optional string, with a default value of "Hello there", you would be in the same boat right?

**Comment by kow3ns** [comment]
So the underlying issue is that we are defaulting into the PodSpec [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/core/v1/defaults.go#L185) which gets adopted into all of the PodTemplateSpecs of every object. That sort of defaults the users declared intent. 

Why not just default the value into the Pod itself [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/core/v1/defaults.go#L162).

Is the intention really to default this in all Templates or to make it optional in the Template and default it in the Pod itself?

**Comment by bradhoekstra** [comment]
@kow3ns I can't speak to the ideology of whether to default the field in all PodSpecs or just the Pod, but your suggestion makes sense to me. I'm not sure of the past reasoning for adding other defaulted fields, most recently SchedulerName in Jan. 2017 (https://github.com/kubernetes/kubernetes/pull/38871/files#diff-14b477f6f8ca5978c702f4d21641e43f), to all PodSpecs instead of just to the Pod object. Did we not have these same tests in place then?

This would effectively be saying we should never add new defaulted fields to PodSpec.

If this is the plan, I can create a PR for the fix and I'll add a big warning comment to SetDefaults_PodSpec.

**Comment by soltysh** [comment]
As an example of where we don't default the template we have a CronJob that embeds JobTemplate, we never default that template, only an actual Job gets defaulting. I agree with @kow3ns that not defaulting any templates does make sense.

**Comment by smarterclayton** [comment]
Agree to only default this in pods.  Agree to adding the comment.

Most important defaulting happens in pods to keep higher level pod specs simpler.  We may need to raise the general pattern in a discussion with api review in general, since this is a change from previous strategy, but the previous strategy was not explicitly chosen (to my recollection at least)

**Comment by AishSundar** [comment]
Hi all do we have an agreed path forward for fixing this issue in 1.13? if so can we have an ETA for the fix to land? the release team would like for the tests to get passing in the blocking suites in an effort to unmask any other failures that might show up once these are fixed. 

/assign @kow3ns

**Comment by mortent** [comment]
We have a PR with a fix that will hopefully merge today or tomorrow. I will keep an eye on the dashboard to make sure it fixes the failing daemonset tests.

**Comment by AishSundar** [comment]
Thanks @mortent. Can we link the PR here plz. 

/cc @jberkus

**Comment by jberkus** [comment]
Reopening, because of the auto-close.  Tests are not passing yet.

/reopen

**Comment by mortent** [comment]
PR that should (hopefully) close this issue is here: https://github.com/kubernetes/kubernetes/pull/69988

**Comment by nikopen** [comment]
DaemonSet tests passed on run 1842, seems to have been fixed: https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gce-new-master-upgrade-master

if it doesn't pop up again -

/close
