### ISSUE TITLE
Move CSIDriver feature flag to beta

### ISSUE THREAD

**Issue by verult** [kubernetes/kubernetes#69539]
/kind feature

Tracking for 1.13 release. This includes moving the object and the associated logic interacting with the object (e.g. skip attach & passing workload information) to beta

/sig storage
/cc @msau42 @saad-ali @jsafrane @ddebroy

**Comment by wongma7** [comment]
Just want to make sure that for 1.13 moving the object versions as @bertinatto has done in https://github.com/kubernetes/kubernetes/pull/70367 to beta is all we are going to do, the feature has to stay alpha and disabled by default. Because this and https://github.com/kubernetes/kubernetes/issues/69538 are blocked by CRD Installation Mechanism https://github.com/kubernetes/enhancements/issues/615? The add-on manager workaround works but enabling it for every install method is basically impossible, I think: kubeadm, cluster/*, local-up-cluster, https://kubernetes.io/docs/setup/ etc. all need to explicitly enable the add-on. I tried to see what happens if we flip the feature gates without having the crds installed and no csi drivers work since they simply fail to register, as you would expect...

**Comment by wongma7** [comment]
@verult right, failing nicely is probably better. In fact I took a more thorough look at a code and I think https://github.com/kubernetes/kubernetes/blob/e133ab274d17c65efab05852eec50c511428b6a4/pkg/volume/csi/nodeinfomanager/nodeinfomanager.go#L97 where we try to update a CSINodeInfo anytime a driver is installed is the only problem. CSIDriverRegistry should already be tolerant because it has something of a check here https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/csi/csi_plugin.go#L177. So let's call this assumption that the feature gate being enabled means the respective CRD is installed a bug, I will fix it in the PR and see what happens. If it turns out to be hard to untangle I guess we can simply add a check that CRD is installed inside every feature gate check.

@bertinatto's PR is ostensibly only about moving the objects to v1beta1 so clarification on what our goal for 1.13 is appreciated, thanks :]

**Comment by wongma7** [comment]
Also, I suppose that while wrangling all the different kubernetes installation methods to install the CRDs is "basically impossible" we can make a good effort and at least ensure our CI's gce/aws clusters install them. There's also local-up-cluster https://github.com/kubernetes/kubernetes/issues/70791. I think something to this effect was mentioned in the meeting today but it went over my head at the time, sorry

**Comment by wongma7** [comment]
How should we determine if the CRD is installed or not? Discovery client? Try to create a CR (doesn't seem foolproof, depends on auth things)? I was wrong about CSIDriverRegistry, the check at https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/csi/csi_plugin.go#L177 is not sufficient. There needs to be a way to check if the CRD is installed or not for both features.

**Comment by wongma7** [comment]
I will try plumbing a discovery client through volume host (ew :))

**Comment by msau42** [comment]
@wongma7 I discussed with @saad-ali and we agree that CSI plugin registration can fail if the CRD is not installed.  What we want to make sure is that kubelet still works (minus CSI drivers) if the CRD is not installed.

**Comment by msau42** [comment]
Sorry we discussed again.  There's the challenge that all the tests will fail once we move to beta because the CRD is not installed in all the deployers yet.  So we may need to fallback to old behavior if the CRD doesn't exist, and only fail if a plugin needs to use a feature that requires the CRDs, like topology, pod information, skip attach etc.  We will also have to keep all the tests feature gated until we can fix the deployers.

**Comment by kfox1111** [comment]
Should the apiserver create crd's for system things if they don't exist rather then have every deployment tool do it? Doesn't it do something like this for other objects?

**Comment by msau42** [comment]
The addon manager is the one responsible for creating the CRDs.  However, we need to update all the deployment tools to enable the CSI CRD addon when the CSI CRD feature gates are set.

**Comment by msau42** [comment]
Sorry we're not planning this for 1.13

**Comment by msau42** [comment]
Fixed by https://github.com/kubernetes/kubernetes/pull/74283
/close
