### ISSUE TITLE
Flaking Test: 5K nodes: [sig-scalability] Load capacity [Feature:Performance] should be able to handle 30 pods per node ReplicationController with 0 secrets, 0 configmaps and 0 daemons

### ISSUE THREAD

**Issue by jberkus** [kubernetes/kubernetes#69600]
Testgrid: https://k8s-testgrid.appspot.com/sig-release-master-blocking#gce-scale-performance

Logs: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/229

This isn't an uncommon flake, but it seems to be happening more this week, with 4 failures out of the last 7 runs.  Has something changed to push us closer to the timeout boundary?  CoreDNS?

/sig scalability
/kind flake
/priority important-soon

**Comment by wojtek-t** [comment]
Each of those flake seem to be different one (no it's not related to coredns).

The goal for this quarter is to deflake this job completely, so we will definitely be looking into soon.

**Comment by chrisohaver** [comment]
... and CoreDNS is not deployed in an any scale tests at this time.

**Comment by jberkus** [comment]
This test has been pretty consistent for the last week.  Did y'all fix it?

**Comment by wojtek-t** [comment]
I don't think everything is fixed (we were at least a bit lucky).

/assign @mborsz

**Comment by jberkus** [comment]
It's still green, so I'm going to lower the priority of the fix.

/priority important-longterm
/remove-priority important-soon

**Comment by mariantalla** [comment]
Hey, this is failing/flaking again.

**Which jobs are failing**:
[sig-release-master-blocking#gce-cos-master-scalability-100](https://k8s-testgrid.appspot.com/sig-release-master-blocking#gce-cos-master-scalability-100)

**Which test(s) are failing**:
[sig-scalability] Density [Feature:Performance] should allow starting 30 pods per node using ReplicationController with 0 secrets, 0 configmaps, 0 token projections, and 0 daemons

*Example failure*: https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/19421

**Since when has it been failing**:
November 6th, 2018; [a13599be7](https://github.com/kubernetes/kubernetes/commit/a13599be7e0bb9fcf98628a7ebbd318ba41d9b97)

**Testgrid link**:
https://k8s-testgrid.appspot.com/sig-release-master-blocking#gce-cos-master-scalability-100

**Anything else we need to know**:
Timing coincides with the bump to golang 1.11.2 ([slack conversation](https://kubernetes.slack.com/archives/C2C40FMNF/p1541449261078000), [test-infra commit](https://github.com/kubernetes/test-infra/commit/2e864b795b68e73cd53e44b070db5663385b1e02)).

**Comment by mariantalla** [comment]
Increasing priority to `important-soon` as it's failed twice in a row and we're nearing code freeze.

/priority important-soon

**Comment by jberkus** [comment]
adding milestone in case this is related to the go upgrade, and we need to make it a blocker

/milestone v1.13

**Comment by wojtek-t** [comment]
@mariantalla @jberkus - this test was originally filed for gce-scale-performance suite.
(which is 5000-node cluster)

However, the last update is about cos-master-scalability-100 (100-node cluster).

Even though we are running the same test in those two, the problems are (in many cases) completely different. So please in the future don't mix those two things.

The problem from @mariantalla update is tracked in #70708 so I'm lowering the priority here.

/remove-priority important-soon
/priority important-longterm

**Comment by AishSundar** [comment]
@wojtek-t  we didnt get a run of the large scale-performance job today. Can you please look into whats going on? Thanks

**Comment by AishSundar** [comment]
As commented by @BenTheElder [here](https://github.com/kubernetes/kubernetes/issues/70708#issuecomment-436877788) its a broader Prow / k8s issue. lets wait for one more run.

**Comment by AishSundar** [comment]
We got a new large scale run for 11/7 - https://testgrid.k8s.io/sig-release-master-blocking#gce-master-scale-performance

@wojtek-t can you look it is ok from performance and CPU consumption and then close this issue? Thanks

**Comment by wojtek-t** [comment]
> Even though we are running the same test in those two, the problems are (in many cases) completely different. So please in the future don't mix those two things.

@AishSundar - please don't mix different suites in the same issues.
This issue was opened for problems with 5k-node clusters, and those flakes were not yet fully addressed.

**Comment by jberkus** [comment]
I'm removing this from the blocker list, given.

/remove-milestone

**Comment by wojtek-t** [comment]
I'm closing this as obsolete - we should open a new one if needed.
