### ISSUE TITLE
GKE - Wrong scalability

### ISSUE THREAD

**Issue by bappr** [kubernetes/kubernetes#69722]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind feature

/sig scalability

**What happened**:
In the GKE UI -> Clusters, my cluster is scaled up to 14 nodes (105GB and 28CPU).
- Sum of the Memory for all the pods running in the cluster is only 20GB (`kubectl top pod --all-namespaces`). Sum of all the memory limits is only 50GB and sum of all the memory requests is 26GB. (`kubectl get nodes --no-headers | awk '{print $1}' | xargs -I {} sh -c 'echo {}; kubectl describe node {} | grep Allocated -A 5 | grep -ve Event -ve Allocated -ve percent -ve -- ; echo'`)
- Sum of the cpu for all the pods running in the cluster is only 3000m  (`kubectl top pod --all-namespaces`). Sum of all the cpu limits is 20000m and sum of all the cpu requests is 16000m. (`kubectl get nodes --no-headers | awk '{print $1}' | xargs -I {} sh -c 'echo {}; kubectl describe node {} | grep Allocated -A 5 | grep -ve Event -ve Allocated -ve percent -ve -- ; echo'`)

**What you expected to happen**:
Based on the CPU requests - 16CPU - and Memory requests - 26GB, I would expect the scaling to be up to 9 nodes (18CPU, 67.5GB RAM)

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Server Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.7-gke.5", GitCommit:"9b635efce81582e1da13b35a7aa539c0ccb32987", GitTreeState:"clean", BuildDate:"2018-08-02T23:42:40Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
```
GKE - 1.9.7-gke.5
n1-standard-2 (2 vCPUs, 7.5 GB memory)
```
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by Shnatsel** [comment]
Most likely this is happening because your workload requests an amount that's below the actually available amount of CPU and memory on the nodes. The actually available resources differ from the advertised ones in two ways:

1. Some resources are occupied by kubelet and dockerd. You can look up how much is actually available to the pods by running `kubectl describe nodes | grep --after-context=5 Allocatable:`
1. Some resources are occupied by system pods such as kubedns, logging, etc. The resource requests for them can be viewed using `kubectl describe pods`.

Since the amount of CPU and memory consumed by system pods is (almost) constant, using nodes with more CPU and memory might help.

To find out why cluster autoscaler made a certain decision we'd need logs from k8s master which are not available to users on GKE, so there is nothing we can do to debug this. Your only option is to contact GKE support who have access to the logs.

/close

**Comment by losipiuk** [comment]
As @Shnatsel pointed it is impossible for us to fully understand the cause what you are seeing without access to cluster itself. Please consult GKE support.
