### ISSUE TITLE
Make it possible for LoadBalancer type Service to not allocate a NodePort?

### ISSUE THREAD

**Issue by berlinsaint** [kubernetes/kubernetes#69845]
**Is this a BUG REPORT or FEATURE REQUEST?**:

 /kind bug
 /sig network

**What happened**:

When we use the Service type LoadBalancer, it will automatically use nodePort? 
[when i use the metalb layer2 mode](https://github.com/google/metallb/issues/328) , i found this, dose the LoadBalancer really need nodePort?
shall we remove this feature?
the nodePort  will cause the port limited, and the number   we can create the LoadBalacner 
is 2767 .

**What you expected to happen**:
LoadBalancer not use the NodePort

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.11
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by toruksmakto** [comment]
How to disable nodeport-binding on LoadBalancer Type Service?

**Comment by thockin** [comment]
There is no way, currently to bypass this.  The design is that they are concentric.  I am going to re-title this as a feature request, but it's worth pointing out that on some platforms LB uses the node port, so bypassing it would just fail.

**Comment by dohnto** [comment]
@thockin I am willing to work on this. 

1. What should be a next step of mine?
2. Does this need a KEP?.
3. Is a FeatureGate with toggle turning on/off this a right place for this?

Thank you for your answer a guidance.

**Comment by junkiebev** [comment]
Watching - I'm also interested in being able to conditionally disable this.

**Comment by andrewsykim** [comment]
@thockin would you be opposed to a flag on the apiserver to disable the node port allocation for Service Type=LoadBalancer (node ports being allocated by default)? Sounds like it's useful in the context of MetalLB and other external controllers consuming Service Type=LoadBalancer but not requiring the node port on kube-proxy.

**Comment by thockin** [comment]
I am curious why "I need to not expose nodeports", as opposed to "I don't need to expose NodePorts".

It's not clear to me if this is a per-Service option or a global thing (e.g. apiserver flag).  I feel obligated to point out that a global flag here might make your cluster non-conformant (I actually can't see where, but the service tests are twisty).

What would happen if I ask for type=NodePort?

What would happen if I ask for type=NodePort and then upgrade to type=LoadBalancer?

I think the nest step would be a proposal considering a few different implementation options and the relative pros/cons.  Then we can discuss as a SIG

**Comment by sakserv** [comment]
I would lean towards the per-Service option. However, the reasoning is for a feature that doesn't exist, but probably should down the road.

The overall ask here is due to MetalLB, which does not require a NodePort to function. However, other future on-prem LBs might need NodePorts, similar to how the cloud offerings work.

Today, we can only have one LoadBalancer implementation in the cluster AFAIK, but I can see use cases where it would be desirable to have more than one type of LoadBalancer. This would be similar to how it is possible to run and target multiple Ingress controllers.

Let's say I have an expensive, hardware load balancer that only critical services should be exposed on. I also have MetalLB for exposing less critical services. In this theoretical case, MetalLB does not need to leverage NodePorts, but the expensive hardware load balancer does. Having the control at the per-Service level would allow this use case to work, while limiting port usage.

That said, this means users now need to understand their LoadBalancer, and if it needs the NodePort or not, so I can see the value in being able to provide an administrative default.

**Comment by andrewsykim** [comment]
The original ask was to only disable NodePorts for Service Type=LoadBalancer via a flag on the apiserver. Type=NodePort behavior would not change.

**Comment by andrewsykim** [comment]
The main use-case similar to what @sakserv mentioned is that NodePorts themselves are useful, but depending on the cloud provider's implementation of load balancers, node port allocation for Service Type=LoadBalancer could be unnecessary. The two main problems are: 
* # of LBs is now limited to # of available node ports (not problematic in most clusters)
* node ports are exposed for an LB even though they are not used

**Comment by thockin** [comment]
@andrewsykim 

> disable NodePorts for Service Type=LoadBalancer via a flag 

There are tests that presume LB is a superset of NodePort - I am not 100% sure, but this cluster would almost certainly fail e2e and possibly conformance.  It would also introduce some weird semantics (which are already present in the downgrade path) where users have to clear the NodePort field in order to change type from NodePort to anything else.

It's not that I disagree with the goal, it's that past mistakes have to be dealt with, and Service is lacking as an API.

>  The two main problems are:
> * number of LBs is now limited to number of available node ports (not problematic in most clusters)

I have heard exactly one user complain about this, but I agree it's plausible

> * node ports are exposed for an LB even though they are not used

This is not a "problem", but more of an inconvenience?

As I said, I am open to a proposal, but it has to work through issues like these.

**Comment by lllamnyp** [comment]
This is a problem for us. We're trying to run Jupyterhub, where multiple notebooks may want to connect to a hadoop cluster via spark. Every such connection requires two ports. We expected, that hooking them up to a load balancer ip would be a solution, but in fact we're still using two ports per node per connection.

This makes things unfeasible in large multitenant clusters, since the pool of nodeports does not scale neither with the size of the machine, nor with the number of workers.

**Comment by andrewsykim** [comment]
FYI folks, @maplain and I are working on a KEP for this. Initial KEP PR probably won't be out for another month as I am taking paternity leave for a few weeks. Please reach out to @maplain if you'd like to help contribute.

**Comment by uablrek** [comment]
Use `nodePortAddresses` as work-around for the security issue see; https://github.com/kubernetes/kubernetes/pull/89998#issuecomment-611590526.

**Comment by uablrek** [comment]
Will be fixed by https://github.com/kubernetes/kubernetes/pull/92744

**Comment by uablrek** [comment]
@bowei Can you approve the API change in https://github.com/kubernetes/kubernetes/pull/92744? @thockin seems very busy.

**Comment by aojea** [comment]
/close
https://github.com/kubernetes/kubernetes/pull/92744 merged
This took a bit longer than expected :upside_down_face: 
Thanks
