### ISSUE TITLE
kubectl port-forward command fails with error "incompatible key usage"

### ISSUE THREAD

**Issue by vishal49naik49** [kubernetes/kubernetes#69841]
Hi,

I have generated my own certs for my kubernetes cluster. All components (apiserver, controller, scheduler, kubelet, etcd, docker) run as system-md service on linux.

kubectl get pods, get svc, create, apply commands work just fine

kubectl port-forward command fails with error "error: error upgrading connection: unable to upgrade connection: Unauthorized". 
My kubelet log says " server.go:226] Unable to authenticate the request due to an error: x509: certificate specifies an incompatible key usage"

I used cfssl gen cert command with client profile to generate certs for my user.  I even generated a CSR with usage as "client auth" referencing the request as the csr of my user. 

Please advise!

Thanks!

**Comment by liggitt** [comment]
make sure the certificate given to the apiserver with `--kubelet-client-certificate` has the correct client auth usage. if that checks out, can you provide the output of the following:

```
openssl x509 -in /path/to/user/cert -text  | grep "Extended Key Usage" -A 1
openssl x509 -in /path/to/kubelet-client-certificate -text  | grep "Extended Key Usage" -A 1
```

**Comment by vishal49naik49** [comment]
Here are my results for the two commands:

openssl x509 -in /path/to/user/cert -text  | grep "Extended Key Usage" -A 1

            X509v3 Extended Key Usage:
                TLS Web Client Authentication

openssl x509 -in /path/to/kubelet-client-certificate -text  | grep "Extended Key Usage" -A 1

            X509v3 Extended Key Usage:
                TLS Web Server Authentication


Thanks!

**Comment by liggitt** [comment]
the kubelet-client-certificate is the issue... it must be a client certificate

/close

**Comment by Protopopys** [comment]
> проблема с kubelet-client-Certificate ... это должен быть сертификат клиента
> 
> /близко
@liggitt 
Can you help me with kubelet-client-certificate authentication on Kubelet?
Kube-apiserver:
```
  --kubelet-certificate-authority={{ kube_cert_dir }}/kube-ca.pem \
  --kubelet-client-certificate={{ kube_cert_dir }}/apiserver-kubelet-client.pem \
  --kubelet-client-key={{ kube_cert_dir }}/apiserver-kubelet-client-key.pem \

```
openssl x509 -in /path/to/kubelet-client-certificate -text | grep "Extended Key Usage" -A 1

```
X509v3 Extended Key Usage:
            TLS Web Client Authentication
```

Kubelet:
```
  --client-ca-file={{ kube_cert_dir }}/kube-ca.pem \
  --tls-cert-file={{ kube_cert_dir }}/{{ inventory_hostname }}-kubelet.pem \
  --tls-private-key-file={{ kube_cert_dir }}/{{ inventory_hostname }}-kubelet-key.pem \
```

openssl x509 -in /path/to/kubelet -text | grep "Extended Key Usage" -A 1

```
X509v3 Extended Key Usage:
            TLS Web Client Authentication
```
I have an error (kubectl exec to pod) 
**Kube-apiserver** -` " Unable to authenticate the request due to an error: x509: certificate specifies an incompatible key usage"`
**Kubelet** - `"TLS handshake error from Apiserver"`

When i generated Kubelet certificates with:
```
        X509v3 Extended Key Usage:
            TLS Web Server Authentication
```
The error disappeared.


Kubeadm generated Kubelet certificates with:
openssl x509 -in /path/to/kubelet -text | grep "Extended Key Usage" -A 1
```
X509v3 Extended Key Usage:
            TLS Web Client Authentication
```

Which of the parameters is correct for Kubelet certificates?
TLS Web Client Authentication or TLS Web Server Authentication

**Comment by liggitt** [comment]
--kubelet-client-certificate must be a client certificate

--tls-cert-file passed to the kubelet must be a serving certificate
