### ISSUE TITLE
[Logging] no event generated when namespaces are created

### ISSUE THREAD

**Issue by lliknart** [kubernetes/kubernetes#69873]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature
/sig logging

**What happened**:
kube-controller-manager generates an event when a namespace is deleted (via kubectl)
`Namespace has been deleted <namespace_name>`

However, nothing happen when a namespace is created

**What you expected to happen**:
I expect the same kind of event when a namespace is created (via kubectl)
for example: 
`Namespace has been created <namespace_name>`

**How to reproduce it (as minimally and precisely as possible)**:
1: Create a namespace
`kubectl create namespace test-namespace-log`

2: Delete the namespace
`kubectl delete namespace test-namespace-log`

3: Check kube-controller-manager logs

**Environment**:
- Kubernetes version (use `kubectl version`): v1.11.0

**Comment by vbmade2000** [comment]
@dims Is this issue still open for work ? If so I want to work on this.

**Comment by liggitt** [comment]
Logging a deletion event in the controller manager log is a good idea, since the controller is responsible for cleaning up resources in deleted namespaces, and that log line can help track when the controller started cleanup. 

Logging a message in response to namespace creation does not really make sense any more than it would make sense for the controller to log creation of all objects. 

/close
