### ISSUE TITLE
Failing test: [sig-scheduling] SchedulerPriorities [Serial] Pod should be preferably scheduled to nodes which satisfy its limits

### ISSUE THREAD

**Issue by mortent** [kubernetes/kubernetes#69989]
Testgrid: https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gke-gci-new-gci-master-upgrade-cluster-new
https://k8s-testgrid.appspot.com/sig-release-master-blocking#gke-cos-master-serial

Example: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-gci-new-gci-master-upgrade-cluster-new/2362

This seems to be related to #69437

/sig scheduling
/kind failing-test
/priority important-soon

/cc @ravisantoshgudimetla

**Comment by ravisantoshgudimetla** [comment]
Looked at the kube-scheduler logs for GCE, seems the feature_gate was enabled.

`Creating scheduler with fit predicates 'map[MaxCSIVolumeCountPred:{} GeneralPredicates:{} NoVolumeZoneConflict:{} MatchInterPodAffinity:{} CheckVolumeBinding:{} MaxAzureDiskVolumeCount:{} NoDiskConflict:{} CheckNodeUnschedulable:{} MaxEBSVolumeCount:{} MaxGCEPDVolumeCount:{} PodToleratesNodeTaints:{}]' and priority functions 'map[InterPodAffinityPriority:{} LeastRequestedPriority:{} BalancedResourceAllocation:{} NodePreferAvoidPodsPriority:{} NodeAffinityPriority:{} TaintTolerationPriority:{} ImageLocalityPriority:{} SelectorSpreadPriority:{}]'`

I don't see `ResourceLimitsPriorityFunction` enabled, will setup the cluster locally to test if this is the issue.

**Comment by jberkus** [comment]
@ravisantoshgudimetla  hey, any progress on this?  It's still broken in the test.

**Comment by jberkus** [comment]
@ravisantoshgudimetla have you been able to look into this?  These tests are broken right now for unrelated reasons, but once they get fixed I expect to keep seeing the scheduler failure.

**Comment by AishSundar** [comment]
@ravisantoshgudimetla is the one open PR #70401 expected to fix the remaining failures we are seeing the release dashboards? If not fixed by this week, these failures will block Beta cut targeted for 11/6.

**Comment by ravisantoshgudimetla** [comment]
@AishSundar - Apologies for the delay. Yes, this PR should fix the failure, if not, I will disable this test for now as revert the feature promotion PR associated with this test. Also, I need to rethink, if e2e is an appropriate test scenario to handle this feature or should unit tests/integration suffice. I could not find a test which does something like resizing a node in the existing e2e test suite.

**Comment by justinsb** [comment]
I'm looking at this, and I'm not sure this is going to fix the failures.

I'm looking at the tests, and it seems to be setting the node status capacity/allocatable to pretend to be a 12 core machine, and then it tries to allocate a pod on every node such that every node is 50% utilized.

It thus tries to allocate a pod of ~ 6 cores on the resized node.  But that node still only has 2 cores, so it fails to schedule:

`Oct 31 13:57:26.840: INFO: At 2018-10-31 13:47:26 +0000 UTC - event for 80a6890c-dd13-11e8-b8c2-0a580a3c135f-0: {kubelet bootstrap-e2e-minion-group-s6qw} OutOfcpu: Node didn't have enough resource: cpu, requested: 5250, used: 450, capacity: 2000`

I think that's why the test has been failing, at least for the past few runs which I checked.

What I have yet to figure out is how this passed here... https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-new-master-upgrade-cluster-new/1750

**Comment by AishSundar** [comment]
@ravisantoshgudimetla the test still failed on the last [run #4295](https://k8s-testgrid.appspot.com/sig-release-master-blocking#gce-cos-master-serial&show-stale-tests=). Even though it was a couple of hours after PR #70401 merged, I dont see it in the delta changes [for that test run](https://github.com/kubernetes/kubernetes/compare/d05622bee...d265e7eef?). I will watch for the next run result.

Assuming it still doesnt pass (as @justinsb pointed out about) we need to figure out what this e2e test failure means and should it block 1.13 Beta0 for next Tuesday.  Considering the test did pass very few times since its introduction, this seems like an issue with the test design itself and not the feature.  Do you have other tests (unit or integration or different approach to e2e) that can infirm us on the health of thew feature? If those exist and are green we can unblock Beta on those results while you determine the right way to author the e2e. Barring those being present right idea, I think we will have to err on the side of caution and roll back the feature itself before Beta.  Either way we need to take a call and submit relevant PRs by tomorrow so we get  green CI over the weekend, in time for Beta cut on Tuesday.

 @jberkus

**Comment by ravisantoshgudimetla** [comment]
> Assuming it still doesnt pass (as @justinsb pointed out about) we need to figure out what this e2e test failure means and should it block 1.13 Beta0 for next Tuesday. 

This is not a blocker, as I told earlier as well, e2e may not be good avenue for this test. I actually thought more about this problem last day. The problem is I updated the node capacity and I was checking if the node could handle the pod based on the scheduler cache which we get from kubelet. But kubelet on the other side is updating it's node information(like CPU, memory etc) in the API server there by causing a race condition. So, it could pass with a very little chance. So, I will remove this test from e2e.

>  Do you have other tests (unit or integration or different approach to e2e) that can infirm us on the health of thew feature? 

Yes, we have unit tests, that help in validating the feature. I will try to get an integration test but this is not a blocker for feature.

**Comment by AishSundar** [comment]
Thanks for the explanation and analysis @ravisantoshgudimetla. do you plan on adding more e2e tests later or stick to unit and integration for validating this feature? @bsalamat,  @jberkus and @justinsb to weigh in on the path forward i.e., remove e2e tests for this feature and rely on unit and integration.

**Comment by ravisantoshgudimetla** [comment]
@AishSundar - We discussed internally in the sig meeting yesterday and it was decided to have an integration test instead of e2e test. I plan to add an integration test(which we don't have today) later.

**Comment by AishSundar** [comment]
@ravisantoshgudimetla  since this PR is actually tracking an enhancement work graduating to Beta in 1.13, it should have been tracking via a corresponding issue in k/enhancements repo in 1.13 timeframe. We are now past Feature freeze for 1.13 and its late to open an issue against it. Also we are missing integration tests for this feature, which we are [solely relying on for qualification](https://github.com/kubernetes/kubernetes/issues/69989#issuecomment-435412091).

Given the above two points and from offline discussions with SIG leads regarding the criticality of this feature going to Beta now vs in 1.14 timeframe, I am asking for it to be punted to 1.14. 

As AIs 
* Please prepare a PR to remove it from Beta in 1.13
* Please open a tracking issue in https://github.com/kubernetes/enhancements/issues for 1.14 milestone.

@kacole2 @bsalamat @davidopp
