### ISSUE TITLE
Errors after installation

### ISSUE THREAD

**Issue by marcosanfilippo** [kubernetes/kubernetes#70009]
**Is this a BUG REPORT or FEATURE REQUEST?**:

Bug report

**What happened**:
After install kubectl, I have this errors when I open my terminal.
```
-sh: `_kubectl_api-resources': not a valid identifier
-sh: `_kubectl_api-versions': not a valid identifier
-sh: `_kubectl_apply_edit-last-applied': not a valid identifier
-sh: `_kubectl_apply_set-last-applied': not a valid identifier
-sh: `_kubectl_apply_view-last-applied': not a valid identifier
-sh: `_kubectl_auth_can-i': not a valid identifier
-sh: `_kubectl_cluster-info_dump': not a valid identifier
-sh: `_kubectl_cluster-info': not a valid identifier
-sh: `_kubectl_config_current-context': not a valid identifier
-sh: `_kubectl_config_delete-cluster': not a valid identifier
-sh: `_kubectl_config_delete-context': not a valid identifier
-sh: `_kubectl_config_get-clusters': not a valid identifier
-sh: `_kubectl_config_get-contexts': not a valid identifier
-sh: `_kubectl_config_rename-context': not a valid identifier
-sh: `_kubectl_config_set-cluster': not a valid identifier
-sh: `_kubectl_config_set-context': not a valid identifier
-sh: `_kubectl_config_set-credentials': not a valid identifier
-sh: `_kubectl_config_use-context': not a valid identifier
-sh: `_kubectl_create_secret_docker-registry': not a valid identifier
-sh: `_kubectl_port-forward': not a valid identifier
```

**What you expected to happen**:
No errors

**How to reproduce it (as minimally and precisely as possible)**:
Install kubectl on OSX
Open a terminal

**Environment**:
- Kubernetes version (use `kubectl version`): last
- Cloud provider or hardware configuration: macbook pro
- OS (e.g. from /etc/os-release): OSX
- Kernel (e.g. `uname -a`): Darwin Kernel Version 17.7.0
- Install tools: brew
- Others:

**Comment by marcosanfilippo** [comment]
@kubernetes/sig-contributor-experience-bugs

**Comment by TYsewyn** [comment]
It looks like this is being triggered by `bash_completion` when calling `/usr/local/etc/bash_completion.d/kubectl`.

**Comment by nikhita** [comment]
@TYsewyn Thanks for the bug report. I'll close this since it does not look like an issue with kubectl. Please reopen if needed.

/close

**Comment by ducquoc** [comment]
I also met this issue, it only happens on MacOSX with default shell (Bash 3.2 apple-darwin), and bash-completion from Brew. 

By default, the bash-completion folder of Brew is: **/usr/local**/etc/bash_completion.d/
(i.e. `$(brew --prefix)/etc/bash_completion.d/` , you can check with `brew --prefix` )

As commented above, https://github.com/kubernetes/kubernetes/issues/70009#issuecomment-433714755 , it can be fixed by installing new Bash version (4.x):
https://medium.com/merapar/fixing-bash-autocompletion-on-macos-for-kubectl-and-kops-e87f019652e8

This might also be fixed by using an old script of `kubectl completion bash` : 
https://www.arulraj.net/2016/01/bash-completions-for-kubectl.html
(manual download and put into Brew bash_completion.d folder)
