### ISSUE TITLE
Conntrack entities for SCTP are not flushed for deleted Service endpoints

### ISSUE THREAD

**Issue by KomorkinMikhail** [kubernetes/kubernetes#70020]
/kind bug
/sig network

I have the K8s 1.12.1 deployment with SCTP support implementation from #64973. I have faced an issue while running SCTP traffic and it’s the same issue as #19029 with UPD protocol. SCTP conntrack doesn’t flush entries for deleted pods. Thus associations which were established on that deleted pod can not be reestablished since conntrack still tries to route all the SCTP packets (INIT/DATA) to not existent IP. Unless the association is explicitly ABORTed from remote side (this way conntrack will delete the entry).
Reproduction steps are the same as in UDP case:
1.	Create a Service for SCTP port
2.	Create pods that bind to this Service 
3.	Start a client Pod that uses the Service. This client establishes SCTP association to the Service and sends data via this assoc
4.	Check which Pod handles all the traffic in scope of the association (collect tcpdump for example)
5.	Delete that Service endpoint by, for example, killing the corresponding Pod which the client is communicating with
6.	Observe that the Pod's IP no longer appears in endpoints (e.g. using kubectl)
7.	BUG: Observe that conntrack still NATs all SCTP traffic to deleted endpoint.
8.	WORKAROUND 1: use client Pod to explicitly ABORT and reestablish the association.
9.	WORKAROUND 2: use conntrack –D to manually remove the entity in conntrack Hash Table
I guess the solution will be just the same as [here](https://github.com/kubernetes/kubernetes/pull/22573/commits/4fa6f3841ad362844c3c1e04c8657cacad5decde#diff-d51765b83fe795b469e8a86276b12dc9R591) and [here](https://github.com/kubernetes/kubernetes/pull/22573/commits/4fa6f3841ad362844c3c1e04c8657cacad5decde#diff-d51765b83fe795b469e8a86276b12dc9R608).(reusing these functions for SCTP protocol). Basically it’s just adding api.ProtocolSCTP into a couple of checks in solution #22573

**Comment by KomorkinMikhail** [comment]
Hi @janosi 
Please check this out. Do you agree this is a bug in kube-proxy?

**Comment by janosi** [comment]
Hi @KomorkinMikhail 
Definitely, unfortunately, this is a bug :(

**Comment by MaximProshin** [comment]
Hi,

The timer will not help in general as 
- firstly you must guarantee that the timer is not short enough to not remove connections mistakenly which requires SCTPs send DATA/HB at lest once per that timer
- secondly you must guarantee that the timer is not long enough so that when SCTP pod is lost, the peer doesn't have enough time to send a new INIT because in that case the INIT will keep the connection in conntrack alive. 
So, it's very hard to operate by timers in that case and it's better to immediately remove connections belonging to the lost SCTP pod.

**Comment by KomorkinMikhail** [comment]
@janosi I didn't have any experience with TCP in k8s but I agree that there might be the same issue with TCP as well and it needs to be enhanced as well. I beleive that timeout configuration should not be a common solution.

**Comment by janosi** [comment]
Hello,

I did not mean a k8s specific new timer. I mean the conntrack timers in the kernel: https://github.com/torvalds/linux/blob/84df9525b0c27f3ebc2ebb1864fa62a97fdedb7d/net/netfilter/nf_conntrack_proto_sctp.c#L56
As we can see, conntrack itself has its own timers to supervise SCTP conntrack entries - already now. This is very similar to TCP.
In case of UDP the k8s mechanism was required because UDP does not have congestion windows neither it has any heartbeat mechnism to check the accessibility of the remote peer. But in case of TCP and SCTP there are such L4 protocol level ways to check the peer's health. That is why k8s does not have conntrack management mechanisms for TCP, and because SCTP is very similar, there is no need for such for SCTP either. See SCTP endpoint failure detection mechanisms here: https://tools.ietf.org/html/rfc4960#page-100
That is, even if the conntrack timers are long in the kernel, the L4 protocol (TCP and SCTP) has congestion control/failure detection mechanisms, unlike UDP.
So, if we assume, that TCP connection tracking is OK nowadays in k8s  I wonder if SCTP connection tracking is worse. The default idle timeout timer value for TCP is 1 day currently, so definitely that is not the fast reaction method for TCP conntrack entries.
If I assume this, then I would say: yes, we could implement an enhancement to enable to configuration of SCTP related conntrack timers in the kernel, but the situation when compared to UDP is different, and SCTP's own L4 mechanisms should provide fast endpoint failure detection.

**Comment by KomorkinMikhail** [comment]
I understand that you are talking about conntrack timers. Regarding SCTP endpoint failure detection: it's not a problem for a remote SCTP to detect failure, but if this remote SCTP doesn't close the connection explicitly (sending ABORT/CLOSE) then conntrack will still contain the entry towards not existing pod. Remote SCTP will send INIT chunk, and conntrack will DNAT it to that pod (conntrack handles INIT chunk for existing associations the same way as DATA chunks - forwards it according to existing entry and restarts internal timer). So if remote SCTP is continuously trying to reestablish the association then conntrack entry will never be cleared.
My guess is that in TCP case the connection reestablishment is handled differently on conntrack (e.g. when receiving SYN packet for existing connection conntrack deletes the entry and creates is again or something like that)

**Comment by janosi** [comment]
According to the Linux kernel the kernel level SCTP implementation aborts the association when the number of max retransmissions reaches the max threshold. It is like that since 3.8, the relevant patch: https://patchwork.ozlabs.org/patch/200493/

A discussion about it from a later time: http://lkml.iu.edu/hypermail/linux/kernel/1501.2/05029.html
According to this e.g. BSD also follows this behavior, i.e. BSD sends ABORT, too.

According to the TCP conntrack state transition table in the kernel if SYN is received when the conntrack entry is in ESTABLISHED state, the SYN is ignored from conntrack's perspective, the SYN is let through and the server can decide how to handle that.

**Comment by MaximProshin** [comment]
Sending of ABORT is not a guarantee either. RFC4960 doesn't require to send ABORT. Even if all SCTP implementations support it, ABORT might be lost in the network.

**Comment by KomorkinMikhail** [comment]
@MaximProshin agree on this statement. @janosi what do you think?

**Comment by janosi** [comment]
Indeed, it can be lost on the network, though my understanding is, that the conntrack entries in question are on the same host with the client that sends the ABORT.
If ABORT comes later than a 2nd INIT (i.e. with a new tag) then the ABORT is ignored in conntrack, but if I understand the code right, the ABORT is let through (i.e. not dropped).

What I think: I think the SCTP situation is the same or very similar to that of TCP.  As I can see, there is no consensus yet about how to handle similar TCP issues in k8s, please see here (I admit, the original problem is not the same to the one that we have here, but there is a discussion also about the handling of TCP connection related conntrack entries in general):
https://github.com/kubernetes/kubernetes/issues/48719

On the other hand, of course, if someone would like to enhance the current functionality, I am OK with that. Unfortunately I am not a perfect expert of conntrack vs SCTP, but if you feel comfortable with such a change, please go forward.

**Comment by MaximProshin** [comment]
@janosi not sure I follow your argumentation about ABORT. Imagine you have SCTP pod in a k8s cluster and some other SCTP on the peer side, e.g. LKSCTP. When an association is established between the pod and LKSCTP, conntrack in the k8s cluster will have the entry in the table. Then SCTP pod can be lost, e.g. it's ungracefully killed. Today conntrack will not detect it and will still have the same entry. LKSCTP will continue to send traffic there and conntrack will still continue to dnat it which will result in traffic discard. LKSCTP will trigger losses and increment the error counter so eventually it will close the association and send ABORT. If ABORT is received by conntrack in the k8s cluster, it will remove the entry. If ABORT is lost, conntrack will not remove the entry.

**Comment by janosi** [comment]
@MaximProshin I mean, the conntrack entry in relation with the nat rule is created on the node where the client app resides. kube-proxy configures the same nat rules on every nodes in the cluster, and when a client sends a request to the ClusterIP of the service the nat rule is evaluated on the node of the client and DNAT changes the dst IP of the packet to the IP of the selected server pod. The corresponding nat related conntrack entries are managed on the same node. So, when the client sends ABORT due to reaching the error threshold on the association that ABORT has to have effect on the local node. I meant, that losing ABORT on the local node has pretty low probability.

**Comment by MaximProshin** [comment]
@janosi Yes, loosing ABORT originated locally has very low probability but I'm talking about ABORT originated remotely. When the pod is lost ungracefully, it doesn't have a chance to send ABORT to update conntrack.

**Comment by KomorkinMikhail** [comment]
@janosi Maxim describes the scenario when client resides outside the cluster (when ABORT is lost somewhere in the network or not sent at all)

**Comment by janosi** [comment]
@MaximProshin Yes, I know that when a pod is lost ungracefully it cannot send ABORT. On the other hand so far we talked about losing a pod behind a ClusterIP :)
But OK, I understand, yes, ABORT from remote clients may be lost.

**Comment by MaximProshin** [comment]
Sorry for any confusion! I had in mind the general case.

**Comment by freehan** [comment]
Ping? still an issue?

**Comment by KomorkinMikhail** [comment]
@freehan 
Hi, yes this is still an issue.There is a PR #74073 to fix it, but it's on review for a long time.
