### ISSUE TITLE
Add an impersonation test case to the audit E2E test

### ISSUE THREAD

**Issue by tallclair** [kubernetes/kubernetes#70198]
We don't currently have any test coverage of impersonation for audit logging. I think the audit e2e test (https://github.com/kubernetes/kubernetes/blob/master/test/e2e/auth/audit.go) would be a good place to do so.

/area audit
/area test
/sig auth
/help
/good-first-issue

**Comment by riya-17** [comment]
\assign
@tallclair I would like to work on this issue. 
Please give me some tips and instructions which i should take into consideration and will help me accomplishing this task successfully.

**Comment by tallclair** [comment]
Take a look at the existing audit tests (linked in description), and the documentation on [impersonation](https://kubernetes.io/docs/reference/access-authn-authz/authentication/#user-impersonation). I recommended doing a manual test first, so you understand how it works. The audit test actually already uses impersonation (https://github.com/kubernetes/kubernetes/blob/12cf5451952c8425a47334465f3e03d7ca181956/test/e2e/auth/audit.go#L72-L80), so you can just do something similar and then verify that it is logged correctly (the `ImpersonatedUser` field).

**Comment by tallclair** [comment]
Also, if you need help with the e2e framework, https://github.com/kubernetes/community/blob/master/contributors/devel/e2e-tests.md is the place to start.

**Comment by riya-17** [comment]
Ok, thank you :)

**Comment by dczombera** [comment]
@riya-17 How is it going? Do you need some help?

**Comment by simonsheng** [comment]
Just watch around.

**Comment by dczombera** [comment]
@riya-17  Can you give me more details about what it is you are struggling with? Writing test cases in general? I'm also new to the project but perhaps I can help you out. :)

**Comment by riya-17** [comment]
@dczombera Yes, I am struggling with writing test cases in general

**Comment by Pradip-Khakurel** [comment]
@riya-17 Are you still struggling with test cases in general? @tallclair Please tell me if I am wrong, but I think here a test case is just testing that a particular call to the api logs specific information (represented by the struct AuditEvent). If I am correct, we don't need to create a complete new test case, but rather edit the exiting ones by checking one more info.

Additionally, I am not sure that we can test this locally with kubetest, since the test seems to only accept the gce provider (google cloud engine).

https://github.com/kubernetes/kubernetes/blob/12cf5451952c8425a47334465f3e03d7ca181956/test/e2e/auth/audit.go#L60

Hope this helps.

**Comment by riya-17** [comment]
@Pradip-Khakurel  yes, I am struggling for writing test case as well as this was in my concious as well that how I am gonna test this test case

**Comment by dczombera** [comment]
OK, I think I got what the issue is about. @riya-17  Please let me know if you are still struggling and prefer to hand it over. I'd like to give it a shot but don't want to steal the opportunity to make a first contribution to the project from you.

**Comment by riya-17** [comment]
@dczombera yaa sure you can give it a shot

**Comment by dczombera** [comment]
FYI I'm working on this issue. I'm trying to get audit logging activated in minikube so I can manually test impersonation and see the log output (in order to see what the test has to cover). However, trying to get it activated in minikube is more difficult than I thought.  :grimacing:

**Comment by Pradip-Khakurel** [comment]
Hey @dczombera, how is it going with the manual test? The only way I found with minikube, is to start it with the following command (I use minikube v0.30.0). This activates audit logs, and configures the logs file path in the minikube's VM. 
> minikube start --feature-gates=Auditing=true

Then you could use an api call using kubectl, with and without impersonation, and see the difference in logs. Notice that it does not matter if we have not created any pods at this point, because we just want to test the audit.
> kubectl get pods
> kubectl get pods --as=superman --as-group=system:masters

To look into the logs you need to ssh into Minikube and look into a particular file.
> minikube ssh 
> cat /var/log/kubernetes/audit/audit.log

The manual test is a good thing to see how it works. But you don't actually need to code the whole thing. as the current audit test already loads and parses the log file (see inside CheckAuditLines, and then parseAuditLine).

https://github.com/kubernetes/kubernetes/blob/12cf5451952c8425a47334465f3e03d7ca181956/test/utils/audit.go#L77-L90

**Comment by dczombera** [comment]
Hey @Pradip-Khakurel , thanks for your extensive anser. 👍 
I managed to get in tested manually with minikube a couple of days ago, though it was not possible for me to get an costum audit policy file loaded even though it was available (somehow the extra config flag `audit-policy-file string`was ignored).
Anyway, I spent the last couple of days figuring out how to best run the e2e tests on my macbook (I'm using Vagrant right now since there were some problems with running the tests in docker on mac). 
As you already mentioned in a previous comment, the audit tests only accept gce as a provider. I tried to simply comment that line out in order to see what happens if it runs on my local machine, but (unsuprisingly) it blew up.

So the current status is, that I'm now trying to write the test case for impersonation relying on the CI to see if it runs through (since I cannot run the test locally) which is not ideal but I don't have a better idea atm.
