### ISSUE TITLE
Multiple test job failures in diffResources

### ISSUE THREAD

**Issue by jberkus** [kubernetes/kubernetes#70191]
Testgrid:

*    https://k8s-testgrid.appspot.com/sig-release-master-blocking#gce-cos-master-default
*    https://k8s-testgrid.appspot.com/sig-release-master-blocking#gke-cos-master-default
*    https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gce-new-master-upgrade-cluster-new-parallel
*    https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gke-gci-new-gci-master-upgrade-cluster-new-parallel

Sample failures:

* https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce/31199
* https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-gci-new-gci-master-upgrade-cluster-new-parallel/82

This started failing across multiple test jobs last night.  The culprit appears to be PR #69441 

@mkimuram @msau42 @davidz627 over to you.  

/kind failing-test
/priority critical-urgent
/sig storage

**Comment by msau42** [comment]
@mkimuram I think `cleanupResource` should delete the PVC and wait for it to be deleted.

**Comment by mkimuram** [comment]
@msau42 

Thank you for your comment.
I haven't yet catching up, but as for the PVC deletion code in provisioning.go, which is changed in the PR, PVC deletion is done inside [```TestDynamicProvisioning```](https://github.com/kubernetes/kubernetes/pull/69441/commits/4fcb36e205b0a589806debf9ea20d873d8657f7d#diff-6dc833c65b9c544adfb2d654d2f7cbd3R301). Also, waiting for PV deletion is done in [here](https://github.com/kubernetes/kubernetes/pull/69441/commits/4fcb36e205b0a589806debf9ea20d873d8657f7d#diff-6dc833c65b9c544adfb2d654d2f7cbd3R312) for delete policy case or [here](https://github.com/kubernetes/kubernetes/pull/69441/commits/4fcb36e205b0a589806debf9ea20d873d8657f7d#diff-6dc833c65b9c544adfb2d654d2f7cbd3R198) for retain policy case. 

Isn't it enough?

In addition, could you let me know how I can check the matrix for the failure that we are focusing? 
I couldn't find the failure for provisioning tests themselves, there.

**Comment by mkimuram** [comment]
@msau42 

Is my understanding right that the purpose of ```diffResources``` is to check whether resource is leaking by checking the diff of resource between the test?

If so, is it correct that the sample output above means that one pd is leaking, not the leak of pv or pvc itself?

I found that [deleting pd logic](https://github.com/kubernetes/kubernetes/compare/327a2bb87...83d3f7033?#diff-921d685551b184e272cde1307bb72338L575) in the test for retain policy is removed in this PR when it is moved to [here](https://github.com/kubernetes/kubernetes/compare/327a2bb87...83d3f7033?#diff-6dc833c65b9c544adfb2d654d2f7cbd3R195), because it is gce specific logic and looks unnecessary. Do you think that it could be a cause of this issue?

If so, should deleting the backend storage be generally required before removing the dynamic provisioned PV with retain policy?
