### ISSUE TITLE
PDB maxUnavailable doesn't work on pods without controllers.  minAvailable does.

### ISSUE THREAD

**Issue by bkruger99** [kubernetes/kubernetes#70312]
Referencing here as it points more things out: 
https://github.com/mikkeloscar/pdb-controller/issues/17

PDB maxUnavailable doesn't work with standalone pods.  This would be extremely useful for when you have jobs that shouldn't be evicted if they don't need to be until they finish.   CronJobs, Jenkins slaves, etc.  Things that can have a finite life that should probably complete otherwise.

minAvailable does work with standalone pods.  This seems counter intuitive in the docs to have one method work one way and the other to not.

I am not sure if this should be considered a bug or a feature request, so I am marking as a bug due to operational difference.

/kind bug
/sig apps

**Comment by kow3ns** [comment]
/assign @mortent 
PTAL

**Comment by mortent** [comment]
So the current behavior matches the documentation [https://kubernetes.io/docs/tasks/run-application/configure-pdb/#arbitrary-controllers-and-selectors](https://kubernetes.io/docs/tasks/run-application/configure-pdb/#arbitrary-controllers-and-selectors) that points out that only `.spec.minAvailable` can be used with bare pods.

I do think this makes sense. In order to use `.spec.maxUnavailable` there needs to be some way to determine the expected number of pods. For the standard kubernetes application controllers, this is given in their specs. But for standalone/bare pods, there is no way to know this and therefore no way for the DisruptionController to know how many pods are unavailable at any time. 

Did you have any specific use cases in mind for where maxUnavailable could be used?

**Comment by bkruger99** [comment]
Jobs that are spun up as one-time data processing jobs that can run and then disappear.  One can use minAvailable, but if you scale beyond the limit, you're subject to your jobs getting killed if resources get shuffled around.    (one real world example: jenkins slaves)

Provided maxUnavailable worked, I viewed it as something that "anything that matches this selector, let it finish unless the underlying machine goes away".    Rather than having to keep pace with matching numbers.

**Comment by mortent** [comment]
I don't think the pod disruption budget is a good fit for what you are trying to do. The pod disruption budget is to limit the number of pods that are unavailable at any time across an application, but not to prevent pods from being terminated all together.
 
Sounds like you want kubernetes to never terminate the pods, but instead wait for them to complete. If you completely control your cluster, you should be able to prevent pods from being terminated (unless something goes wrong, like a node going down). Make sure there is no autoscaler running and manually drain nodes before terminating them. 
And if you just need to give your pods some extra time to complete once they have been scheduled for termination, you can set a high value for `terminationGracePeriodSeconds`.

I don't have a lot of experience with it, but maybe pod priority can help: https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/
