### ISSUE TITLE
Support instance action notification in AWS

### ISSUE THREAD

**Issue by rbtcollins** [kubernetes/kubernetes#70342]
**What would you like to be added**:

Have kubelet react to instance action notifications from the EC2 metadata API. This is documented https://docs.aws.amazon.com/AWSEC2/latest/WindowsGuide/spot-interruptions.html but in short

`http://169.254.169.254/latest/meta-data/spot/instance-action` will either be 404, or  from 2 minutes in advance of an action happening, a JSON hash - `{"action": "stop", "time": "2017-09-18T08:22:00Z"}`. Where action is one of hibernate, stop, and terminate.

Once this is set : 
 - the kubelet should immediately go NotReady
 - the action should be exported on the node metadata
 - and work eviction should start
   - and other controllers that are honouring PDB should be aware of the coming disruption

**Why is this needed**:

This reduces the impact of losing nodes in a spot fleet by providing about 2 minutes to transfer work to other nodes that have not been disrupted (and may not be - disruption is somewhat arbitrary).

/kind feature

**Comment by edify42** [comment]
@rbtcollins  seen this? https://github.com/mumoshu/kube-spot-termination-notice-handler

**Comment by legal90** [comment]
> seen this? https://github.com/mumoshu/kube-spot-termination-notice-handler

It has been moved to https://github.com/kube-aws/kube-spot-termination-notice-handler

**Comment by rbtcollins** [comment]
Thanks! I'm glad thats been written; I'm not sure that having it be a separate container makes sense. I'll need to see how it interacts with kube-iam and instance-meta-data access.

**Comment by rajakshay** [comment]
I think there is value in adding this feature to kubelet. There are projects out there to handle this:
1. https://github.com/aws/aws-node-termination-handler
2. https://github.com/kube-aws/kube-spot-termination-notice-handler

The problem in running another container to do this:
* Wastage of resource (since they run as Daemonset).
* Allowing container to read EC2 Instance Metadata.

It just seems that kubelet is a more appropriate place to add this feature (reading ec2 metadata, updating Node status, and issuing a drain command).
