### ISSUE TITLE
Should external name service have spec.port(s) field?

### ISSUE THREAD

**Issue by yue9944882** [kubernetes/kubernetes#70429]
/triage support
/sig network
/sig api-machinery

if not, can we add restrcitive validation for external name service?

@kubernetes/sig-network-misc

**Comment by danwinship** [comment]
I guess the question is "Given that you can connect to any port on the IP of an ExternalName service, does that mean that ExternalName services shouldn't have specific ports defined? (And so should we prevent people from creating such Services?)"

I'd say "no". The port can still serve as documentation/clarification of what the intended use for the service is. (I suppose it could also serve as misdirection; you could create a service pointing to port X to hide the fact that you're really planning to connect to port Y. But if you're concerned about that, that's more of a NetworkPolicy issue than a Service issue, since people could always just connect to the external IP directly anyway.)

**Comment by yue9944882** [comment]
> I guess the question is "Given that you can connect to any port on the IP of an ExternalName service, does that mean that ExternalName services shouldn't have specific ports defined? (And so should we prevent people from creating such Services?)"

thats exactly my question. or further, can an external name service associated w/ ingress? the ingress reference a service by its name and its port. if we dont allow ports field on external name, then it also forbids references from any ingress object.

> The port can still serve as documentation/clarification of what the intended use for the service is. 

for sure its fine if the ports fields are kept as a clarification. while that would not prevent developers from constructing facilities on this documentational field. e.g. [traefik](https://github.com/containous/traefik) which is an ingress controller are reading ports from external name to build an url query. just want to make sure it will be always supported in the future releases.
