### ISSUE TITLE
Test output of installing rbac policies is too noisy

### ISSUE THREAD

**Issue by gnufied** [kubernetes/kubernetes#70448]
Looks like after https://github.com/kubernetes/kubernetes/pull/69868 got merged, our test output has become too noisy and we are printing entire globs of RBAC policies.

```
Oct 30 14:34:41.307: INFO: patching original content of *v1.ServiceAccount:
{
  "kind": "ServiceAccount",
  "apiVersion": "v1",
  "metadata": {
    "name": "csi-driver-registrar",
    "namespace": "default",
    "creationTimestamp": null
  }
}
Oct 30 14:34:41.307: INFO: patching original content of *v1.ClusterRole:
{
  "kind": "ClusterRole",
  "apiVersion": "rbac.authorization.k8s.io/v1",
  "metadata": {
    "name": "driver-registrar-runner",
    "creationTimestamp": null
  },
```

I do not think, this is necessary. 

/sig storage

cc @pohly

**Comment by pohly** [comment]
It was useful while we started with loading .yaml and patching it and it might be useful again for some other developer who starts to do the same. But I agree, for continuous usage in CI it's less useful.

How about we remove the"patching original content" message (because it mostly represents what's in the .yaml file, except when it uses deprecated aliases) and keep the "creating ..." message? Should that be:
- multiple lines (as right now)
- a single line with a JSON dump of the item
- just a single line with the name of the item?

I'd prefer to see the content, but would be fine with having that in a single line because while less readable, the information is at least there when needed.

**Comment by davidz627** [comment]
+1 we seem to be logging all the deployment yamls including statefulsets etc. None of these verbose yamls should be logged, they are not actions taken in the test or errors and it is simply logging some objects for debug purposes.

I would recommend not dumping the items at all in the standard case and only logging actions i.e. `creating csi-gce-pd-controller` and errors i.e. `failed creating csi-gce-pd-controller: {json_dump_here}`.
