### ISSUE TITLE
Plugin registration mechanism of CSI is broken

### ISSUE THREAD

**Issue by gnufied** [kubernetes/kubernetes#70485]
It looks like plugin registration mechanism of CSI might be broken:

```
Oct 31 13:57:11 foobar-csi-test-minion-group-xxx kubelet[1987]: E1031 13:57:11.226647    1987 plugin_watcher.go:115] error failed to get plugin info using RPC GetInfo at socket /var/lib/kubelet/plugins/com.google.csi.gcepd/csi.sock, err: rpc error: code = Unimplemented desc = unkno
wn service pluginregistration.Registration when handling create event: "/var/lib/kubelet/plugins/com.google.csi.gcepd/csi.sock": CREATE
```

**Comment by gnufied** [comment]
cc @verult @msau42

**Comment by msau42** [comment]
Is this with/without feature gates? On head or 1.12? Does this impact other functionality like attach, mount, etc?

**Comment by jsafrane** [comment]
I think that it's dynamic registration that discovers **all** sockets in `/var/lib/kubelet/plugins`, including a socket created by a driver in a subdirectory. It tries to talk to it with dynamic registration gRPC and it fails.

Driver registrar exposes a different socket (`/var/lib/kubelet/plugins/*.sock`, no subdirectory) and that one should be discovered and used by kubelet.

The message is harmless, at least on my machine, however, it pollutes logs and we should do something about it. Should the dynamic registration watch only `/var/lib/kubelet/plugins` without subdirectories?

/sig node

**Comment by jsafrane** [comment]
cc @RenaudWasTaken for dynamic registration expertise.

**Comment by gnufied** [comment]
Okay, so this could not be reason of volume limits not being registered for csi plugins. hmm.  it looked suspicious.

**Comment by RenaudWasTaken** [comment]
Hello!

Yep this seems to be related to https://github.com/kubernetes/kubernetes/issues/69015 which is a known harmless bug.

Basically what happens is that the plugin watcher will iterate recursively over that directory and try to register every file. In your case the csi.sock doesn't seem to implement the gRPC service, since this is the case, the pluginwatcher mechanism will ignore this file.

We are considering limiting the recursive behavior to one level, and making sure that the files we try to contact always end with `.sock` in the next release.

**Comment by msau42** [comment]
Red herring

**Comment by kremers** [comment]
Same issue with trident v19.10.0
