### ISSUE TITLE
CSI Readonly issues

### ISSUE THREAD

**Issue by saad-ali** [kubernetes/kubernetes#70505]
**What happened**:

Kubernetes readonly flags are a mess (see https://github.com/kubernetes/kubernetes/issues/70503), and readonly flags are broken in the beta implementation of CSI.

We should explicitly define and implement what the mapping of Kubernetes readonly flags is for CSI before moving CSI to GA.

**What you expected to happen**:

*Current (CSI beta) behavior:*

1. PVC/PV access modes may be `ReadOnlyMany`.
    * PVC Access Mode
      * Set by end user.
      * Controls "required access mode" of volume to provision.
        * Passed to CSI via `CreateVolumeRequest.volume_capabilities`.
        * external-provisioner ([link](https://github.com/kubernetes-csi/external-provisioner/blob/a8d9d8dd0a1aebba48d15811e38026f53203380e/pkg/controller/controller.go#L531))
    * PV Access Mode
      * Set by provisioner: Copy of PVC access modes.
      * Used for PV/PVC binding.
      * If PV is created without error, the assumption is that the provisioned volume satisfied all the PVC access modes, so PV access mode should just be copied from the PVC access mode (https://github.com/container-storage-interface/spec/pull/82).     
2. `Pod.spec.volumes.persistentVolumeClaim.readOnly` boolean
    * Specified by end user.
    * Controls if volume is **mounted** readonly.
      * Passed to CSI via `NodePublishVolumeRequest.readonly`.
      * kubelet ([link](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/volumemanager/populator/desired_state_of_world_populator.go#L503))
3. `PersistentVolume.spec.CSIPersistentVolumeSource.readOnly` boolean
    * Specified by CSI provisioner: but not currently set (so always defaults to false).
      * See [link](https://github.com/kubernetes-csi/external-provisioner/blob/a8d9d8dd0a1aebba48d15811e38026f53203380e/pkg/controller/controller.go#L538)
    * Controls if volume is **attached** readonly.
      * Passed to CSI via `ControllerPublishVolumeRequest.readonly`.
      * external-attacher ([link](https://github.com/kubernetes-csi/external-attacher/blob/master/pkg/controller/util.go#L187))
4. `Pod.spec.containers.volumeMounts[x].readOnly` boolean.
    * Specified by end user.
    * Controls if last mile bind **mount** in to container is readonly
      * Controlled entirely by Kubernetes and container via CRI. Not passed to CSI.
      * See [link](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet_pods.go#L240).

Number 3 is NOT doing the right things. Problems include:
* 3 is being used but never set -- and suffers from all the problems pointed out in https://github.com/kubernetes/kubernetes/issues/70503#issuecomment-434876013.

*Proposal:*

1. Add new  `csiControllerPublishVolumeReadOnly` `StorageClass` parameter to CSI `external-provisioner`.
    * This will enable control of the `PersistentVolume.spec.CSIPersistentVolumeSource.readOnly` boolean for newly provisioned volumes.
2. Automatically set `PersistentVolume.spec.CSIPersistentVolumeSource.readOnly` based on PVC access mode.
    *  Specifically, if the `csiControllerPublishVolumeReadOnly` StorageClass parameter is not specified, and the PVC for which the volume is being provisioned has only one access mode `ReadOnlyMany`, then set  `PersistentVolume.spec.CSIPersistentVolumeSource.readOnly` for the newly provisioned PV `CSIPersistentVolumeSource.readOnly` to `true`.
    * This will enable more intuitive control of the `PersistentVolume.spec.CSIPersistentVolumeSource.readOnly` boolean for newly provisioned volumes.

This will fix the issue of not being able to control `CSIPersistentVolumeSource.readOnly` but the value, once set will still be immutable, and will still require user to manually create a new PV object if they want to change it.

CC @msau42 @jsafrane @vladimirvivien @cduchesne @thockin 

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
/sig storage
/milestone v1.13

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/kind bug

**Comment by saad-ali** [comment]
Action item if someone wants to pick up this bug:

* Change `NewBlockVolumeMapper(...)` and `NewMounter(...) in `pkg/volume/csi/csi_plugin.go` set `readonly` from `Pod.spec.containers.volumeMounts[x].readOnly` instead of `getReadOnlyFromSpec(...)`.

**Comment by jsafrane** [comment]
>  i) For 2 - Modify external-attacher to set ControllerPublishVolumeRequest.readonly to Pod.spec.volumes.persistentVolumeClaim.readOnly instead of PersistentVolume.spec.CSIPersistentVolumeSource.readOnly.

External attacher does not have access to pods. We need a new field in `VolumeAttachment.Spec` to the pass `ReadOnly` flag.

**Comment by saad-ali** [comment]
I was mistaken about the current behavior of number 2: it is used by CSI. Fixed it.

**Comment by msau42** [comment]
I tested out 4).  While it is not passed through to csi, it is passed to the CRI, which will bind mount into the runtime as read-only.  So I think there is no issue with 4), and is consistent with in-tree volumes.

I am fixing an additional issue with 2) wrt subpath volumes: https://github.com/kubernetes/kubernetes/issues/70549

**Comment by saad-ali** [comment]
> I tested out 4). While it is not passed through to csi, it is passed to the CRI, which will bind mount into the runtime as read-only. So I think there is no issue with 4), and is consistent with in-tree volumes.

Ack, thanks for testing, will update.

**Comment by mariantalla** [comment]
@saad-ali  @vladimirvivien Could we chat[1] about this issue? Would you be happy for @hoegaarden and me to pick up work on it?

[1] Mainly what priority this issue is for 1.13 - would it block the rest of the CSI work targeted for 1.13?

**Comment by saad-ali** [comment]
@mariantalla Yes that would be great. It is a blocker for 1.13. But the changes in the current version of the proposal only requires changes out of tree (to the CSI `external-provisioner`). We can chat more about it on the CSI call on Wed if you'd like?

**Comment by saad-ali** [comment]
The current proposal is trying to improve the case where a volume is provisioned as readonly. But provisioning a new (empty) volume and using it as readonly doesn't make a lot of sense unless you are pre populating that volume with data (e.g. restore snapshot, clone, etc.). 

This issue exist with current in-tree plugins as well. Therefore this is not a blocker for 1.13. 

We'll take some time next quarter to think through a solution.

**Comment by soggiest** [comment]
Greetings!
mountain_snow code freeze mountain_snow is coming in about 3 days, is this intented to be implemented in the next few days?

**Comment by msau42** [comment]
nope, we will consider fixing this in 1.15

**Comment by xmudrii** [comment]
Hello! We have started the code freeze for 1.15. Is this issue still planned for the 1.15 cycle?

**Comment by jsafrane** [comment]
nope, we will consider fixing this in 1.16

**Comment by xmudrii** [comment]
@saad-ali @jsafrane Hello! I'm bug triage lead for the 1.16 release cycle and considering this issue is tagged for 1.16, but not updated for a long time, I'd like to check its status. The code freeze is starting on August 29th (about 1.5 weeks from now), which means that there should be a PR ready (and merged) until then.

Do we still target this issue to be fixed for 1.16?

**Comment by msau42** [comment]
No, we are not working on this for 1.16.  Please remove the milestone.

**Comment by gnufied** [comment]
Is it correct to store `readonly` flag into `CSIPersistentVolumeSource` which maps to `ControllerPublish` call and hence is temporary? Similar problem exists with adding this field to storageClass or PVC.

It sounds like we need a field in pod spec to request readonly attachment of volumes to properly support this. cc @bswartz

**Comment by msau42** [comment]
I believe the proposal was to add a readonly field to VolumeAttachment object?

**Comment by msau42** [comment]
Or infer from access mode

**Comment by bswartz** [comment]
Pod specs do have a field for read only volume attachements...
https://github.com/kubernetes/api/blob/release-1.16/core/v1/types.go#L170

It's on the persistent claim volume source object in the volumes array.

**Comment by msau42** [comment]
The pod readonly is #2 from the initial comment. It's currently used to determine if a volume is *mounted* readonly, but not attached.  While I really would like to simplify the readonly handling here and reduce as many different ways to specify readonly, if we also used the pod readonly for attach readonly, then that might break cases where you have multiple pods attached to the same node, and one writable, and another readable.

**Comment by bswartz** [comment]
@msau42 Oh sorry I didn't read all the way through the history. It's true that we never know if a future pod will request a writable attachment to the same volume on the same node, so the **only** case where it's safe to attach the volume to the node readonly is if the volume is marked permanently readonly (case #3 above). This doesn't seem problematic to me, as long as we're able to trust nodes to properly enforce read-only-ness.

The only case I'm aware of where you might get undesired behavior is that certain filesystems will perform writes to the block device even when mounting readonly. This can occur with ext4 because it needs to replay the journal after an unclean shutdown, and it _must_ write to the block device, even if the mount is read only, or else the mount will fail. This might lead to strange problems if the cluster assumes that it's safe to have multiple nodes mount the same volume in readonly mode, but the CSI layer allows both nodes to write to the block device.

**Comment by gnufied** [comment]
If we really need permanently readonly volumes (which is a valid usecase), it should have been part of `Volume` type in CSI specs as how it is part of `CSIPersistentVolumeSource` type.

**Comment by bswartz** [comment]
Nothing in the CSI spec prevents us from implementing permanently readonly volumes on the k8s side. The main consideration is that it only makes sense for volumes that are populated with data at creation time. Since such volumes are a relatively new concept in k8s, it's not surprising that we don't have a good system for handling them yet.

If I'm missing something and we need better support from CSI for readonly volumes, then that's something we should address soon.

**Comment by liggitt** [comment]
@saad-ali can details be added on a direction here, or the priority lowered?

**Comment by shalini-b** [comment]
@saad-ali Can I know what is the expected behavior of an SP if user chooses an access mode of `ROM` for PVC as well as PV and does not specify `Pod.spec.volumes.persistentVolumeClaim.readOnly` as `true`? Is the SP supposed to read the access mode of PVC from Volume Capabilities and set the read-only flag while mounting the volume during NodeStage/NodePublish?

**Comment by bswartz** [comment]
> @saad-ali Can I know what is the expected behavior of an SP if user chooses an access mode of `ROM` for PVC as well as PV and does not specify `Pod.spec.volumes.persistentVolumeClaim.readOnly` as `true`? Is the SP supposed to read the access mode of PVC from Volume Capabilities and set the read-only flag while mounting the volume during NodeStage/NodePublish?

Access modes are merely a minimum access level requested by the user. ReadOnlyMany means the user wants to attach the volume to multiple pods, and only requires read access, but higher access is acceptable. You have to specify read only in the pod spec as well if you want k8s to actively prevent write access.

**Comment by shalini-b** [comment]
@bswartz Thank you for the explanation :)

**Comment by humblec** [comment]
imo, we should also consider the scenario of node stage/publish for ROM volume case, I see only controller publish mentioned in the discussion here. Because a node stage operation can also populate the volume as RO ( but then the assumption here is, the volume could be static PVs or Cloned PVC with different access modes .etc and this volume already has a filesystem on it).   One other question I have here is, suppose the nodestage or controller publish are `readonly` mounts in the kubelet node,  whats the expectation if user specify `readonly: false` in pod spec? Is it valid to node publish a RO volume to RW to target/publish path and make it available for pod application to write? iic, no validation is present at the moment which blocks the pod user to consume a volume in read-write mode even though the PVC of volume mount mentioned in the pod spec is `readonly`.   
In any case, we should add `readonly` flag in provisioner sidecar either based on the SC or PVC access mode. My preference goes with setting it based on PVC access mode though compared to based on SC param though. 

@msau42 @jsafrane @bswartz @saad-ali please share your thoughts if any.

**Comment by YiannisGkoufas** [comment]
Hi everyone, apologies if I am missing some of the context. While implementing a CSI plugin, I noticed that the readonly value of
```
NodePublishVolume(ctx context.Context, req *csi.NodePublishVolumeRequest)
```
is false, even though the PVC is mounted as readonly in the pod
```
volumeMounts:
        - mountPath: "/data"
          name: my-csi-volume
          readOnly: true
```
I am missing something? apologies if I am commenting on the wrong issue

**Comment by YiannisGkoufas** [comment]
Maybe this one? https://github.com/kubernetes/kubernetes/issues/61008 ?

**Comment by msau42** [comment]
@YiannisGkoufas the NodePublishVolume readonly field is toggled by 'Pod.spec.volumes.persistentVolumeClaim.readOnly'.

/remove-lifecycle rotten

**Comment by YiannisGkoufas** [comment]
thanks @msau42 ! will try it out

**Comment by bswartz** [comment]
See also: https://github.com/kubernetes-csi/external-provisioner/pull/469
