### ISSUE TITLE
Plugin registration: create and delete events could be handled out of order

### ISSUE THREAD

**Issue by verult** [kubernetes/kubernetes#70516]
Right now the Plugin Watcher spawns a separate goroutine to handle fsnotify events for both socket add and delete events, so it's possible that the delete event arrives at the deregistration handler before the add event arrives at the registration handler.

https://github.com/kubernetes/kubernetes/blob/c81a4a09cf07083265591a9f48c53e80c13d3ebd/pkg/kubelet/util/pluginwatcher/plugin_watcher.go#L109

The CSI handler keeps a record of existing CSI drivers in the cluster. If the events arrive at the handlers out of order (in the case where a driver is added and deleted quickly in succession), there's no way for the CSI handler to know what the correct order is, so the record will be inconsistent.

The plugin watcher should guarantee that events for the same plugin must be passed to handlers in the correct order.

/sig node
/sig storage
/cc @RenaudWasTaken @vikaschoudhary16 @vladimirvivien @davidz627 @msau42 

/kind bug

**Comment by RenaudWasTaken** [comment]
Hello @verult !

> it's possible that the delete event arrives at the deregistration handler before the add event arrives at the registration handler

The pluginwatcher [defines a state machine](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/util/pluginwatcher/types.go) which prohibits the behavior you describe. Meaning that If you did see this behavior in production it is an implementation bug.

That being said the behavior you describe should not be possible with the current implementation as, if the plugin wasn't added, no Deregistration error can be sent, see the [`handleDeleteEvent`](https://github.com/kubernetes/kubernetes/blob/c81a4a09cf07083265591a9f48c53e80c13d3ebd/pkg/kubelet/util/pluginwatcher/plugin_watcher.go#L279-L312) function.

So should this unlikely race ever happen (a plugin created and then immediately deleted) the `DeRegister` call will not be issued as well as the `Register` call one (since the gRPC server won't be reachable on a deleted socket).

Feel free to re-open if you do however manage to trigger this behavior :)
/close
