### ISSUE TITLE
Failing Test: [sig-scheduling] TaintBasedEvictions [Serial] Checks that the node becomes unreachable

### ISSUE THREAD

**Issue by jberkus** [kubernetes/kubernetes#70627]
**Which jobs are failing**: ci-kubernetes-e2e-gce-new-master-upgrade-cluster-new

**Which test(s) are failing**: [sig-scheduling] TaintBasedEvictions [Serial] Checks that the node becomes unreachable

**Since when has it been failing**: Nov. 3rd

**Testgrid link**: https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gce-new-master-upgrade-cluster-new

**Reason for failure**: 

Proximate error:

`Nov  4 17:57:57.062: node "bootstrap-e2e-minion-group-cshn" doesn't turn to NotReady after 3 minutes`

However, this test has a whole bunch of disregarded RBAC errors, and I'm wondering if this is just a permissions problem.  Filing an issue just so the scheduling folks take a look at it, in case it does represent a real upgrade problem.

https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-new-master-upgrade-cluster-new/1772

**Anything else we need to know**:

This particular test is unreliable, and is likely to be taken out of blocking.

/kind failing-test
/sig scheduling
/sig cluster-lifecycle
/priority important-soon

**Comment by Huang-Wei** [comment]
@jberkus The e2e test "TaintBasedEvictions [Serial] Checks that the node becomes unreachable" simulates blocking network connection to master like this: sshing into a worker node, and issue an iptables command to block traffic to master, then wait for the worker node to be NotReady status.

And it passed in [regular sig-scheduling dashboard](https://k8s-testgrid.appspot.com/sig-scheduling#gce-serial). Not sure if there is something particular in the job "ci-kubernetes-e2e-gce-new-master-upgrade-cluster-new". I will take a close look.

**Comment by Huang-Wei** [comment]
From the log, there is no error on "sshing into the worker node and run iptables command to block traffic to master". I'm a little stuck why this worker node doesn't show NotReady..

**Comment by Huang-Wei** [comment]
One possibility is that in the upgrade testing env, there is only one worker node?

So that it enters a "fully disrupted" mode, and node lifecycle manager doesn't update node to NotReady state, per its design.

@jberkus may I know the output of `kubectl get node -o wide` on this "master upgrading" test env?

**Comment by jberkus** [comment]
Link to original PR: #69796

**Comment by AishSundar** [comment]
@justinsb @roberthbailey to help answer any questions relating to upgrade test setup and env.

**Comment by Huang-Wei** [comment]
I think the root cause is described in https://github.com/kubernetes/kubernetes/issues/56787:

> After GCE cluster upgrade, the nodes talk to the master using the in-cluster IP.

From latest failure test, I do see [api-server logs](https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-new-master-upgrade-cluster-new/1775/artifacts/bootstrap-e2e-master/kube-apiserver.log) showing it's communicating using private ip.

Kindly ping @foxish: do we have plan to fix #56787 in 1.13? If not, I think I will have to work around this problem by disabling this e2e test in gce env.

**Comment by Huang-Wei** [comment]
Also cc @bsalamat @k82cn @ravisantoshgudimetla for awareness.

**Comment by AishSundar** [comment]
@justinsb I see that your PR #70681 merged as a fix for #56787. I see the test passing in the lagtest run https://testgrid.k8s.io/sig-release-master-upgrade#gce-new-master-upgrade-cluster-new !! Thanks much.

Is there any more work needed @Huang-Wei or can we close this?

**Comment by Huang-Wei** [comment]
Latest running of ci-kubernetes-e2e-gce-new-master-upgrade-cluster-new is green (after #70681 got merged).

**Comment by AishSundar** [comment]
cool.. lets watch for a few more runs and close this issue.

**Comment by AishSundar** [comment]
Closing this issue now since latest run was green. Thanks much @justinsb  and @Huang-Wei for quick turnaorunds
