### ISSUE TITLE
Flaky Upgrade Tests: Decide whether to remove flaky upgrade tests

### ISSUE THREAD

**Issue by jberkus** [kubernetes/kubernetes#70660]
The following upgrade these have been super-flaky, failing an average of 7 out of 8 runs for at least the last 3 months:

* https://testgrid.k8s.io/sig-release-master-upgrade#gce-new-master-upgrade-master
* https://testgrid.k8s.io/sig-release-master-upgrade#gce-new-master-upgrade-cluster-new
* https://testgrid.k8s.io/sig-release-master-upgrade#gce-new-master-upgrade-cluster

Given this, it's hard to consider these blocking tests.  Questions:

* Who owns these jobs?
* Do we want to retain any of these jobs in master-upgrade(blocking), and if so, who is going to de-flake them?
* If we're removing these jobs from master-upgrade, do we want to continue running them at all?
* If we remove them, are there major areas of upgrade functionality that aren't being tested?

/kind flake
/sig release
/sig cluster-lifecycle
/sig gcp
/sig testing
/priority critical-urgent

attn:
@AishSundar
@timothysc
@spiffxp

**Comment by AishSundar** [comment]
@justinsb @roberthbailey

**Comment by jberkus** [comment]
Looks like the only job whose failures have led to useful fixes in the last 3 months is gce-new-master-upgrade-cluster.

**Comment by spiffxp** [comment]
Discussed during meeting.  The -upgrade-master test hasn't yet been broken up into a parallel/non-parallel variant the way the other jobs have been.  @jberkus will follow up

Once that happens I would be willing to discuss whether the "parallel" tests provide us sufficient blocking signal, while the serial/slow tests could be shuffled to -optional or -informing.  This is much the same pattern we're looking at for non-upgrade jobs that involve parallel vs. serial tests.

**Comment by justinsb** [comment]
I'll take a look at gce-new-master-upgrade-master - likely split it.  I think it's also hitting https://github.com/kubernetes/kubernetes/issues/70305 

Otherwise, I see flaky tests, not a flaky job.  Do we have a querying interface where we can slice test results by test, not by job?

Looking at https://testgrid.k8s.io/sig-release-master-upgrade#gce-new-master-upgrade-cluster-new

That looks like a bad new test "[sig-scheduling] TaintBasedEvictions [Serial] Checks that the node becomes unreachable", the prior failure was "[sig-scheduling] SchedulerPriorities [Serial] Pod should be preferably scheduled to nodes which satisfy its limits" but I guess when we removed that test and thus we dropped it from testgrid?

**Comment by AishSundar** [comment]
@justinsb you are looking for something like the [Triage Dashboard](https://storage.googleapis.com/k8s-gubernator/triage/index.html?sig=cluster-lifecycle) where you can filter failures by a combination of SIG, job, test and also by date (go back in of 2 week windows to see how the test/job fared in the past).

I agree we have had recent failures / flake that are specific to some new tests additions, but in general we have some test or the other fail on each run preventing us from completely relying on the job for Go/NoGo purposes. 

As for the current [TaintBasedEvictions failures](https://testgrid.k8s.io/sig-release-master-upgrade#gce-new-master-upgrade-cluster-new) failures, 
they have been attributed to a [long open upgrade test setup issue](https://github.com/kubernetes/kubernetes/issues/56787)

**Comment by AishSundar** [comment]
That said I am apprehensive about moving these jobs completely out of release blocking mainly because
(i) we dont know what coverage we will be loosing and don't have a good replacement (proven to be less flaky) for upgrade testing yet
(ii) historically I have relied on these jobs to indicate if something is horribly broken. IOW flakes tend to add noise, but widespread failure did give us some useful signal.

**Comment by jberkus** [comment]
This is related to #56787

**Comment by jberkus** [comment]
@AishSundar that's what the category of "informing" is for: tests that are still useful, but where you don't depend on green signal.

**Comment by justinsb** [comment]
And I'm working on a maybe-fix for #56787 in #70681, though I haven't got it green yet!
