### ISSUE TITLE
Transition ServiceAccount admission controller to improved service account token volumes

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/kubernetes#70679]
Over the next N releases, we would like to transition the ServiceAccount admission controller to injecting service account token volumes based on the TokenRequest API and volume projection designed here:

https://github.com/kubernetes/community/blob/master/contributors/design-proposals/auth/bound-service-account-tokens.md
https://github.com/kubernetes/community/blob/master/contributors/design-proposals/storage/svcacct-token-volume-source.md

I propose we use the feature mechanism, with plenty of lead time and noisy announcements, to phase this change in.

### Proposed Plan

*This following is pretty close to what the announcement will look like.*

With the enablement of a new feature, SecureServiceAccountTokenVolume, we will switch the service account admission control to injecting service account token volumes that use the new TokenRequest API to provision tokens. We will loudly announce a new feature that will be Alpha in 1.13 called SecureServiceAccounTokenVolume. 

The new service account token volumes are preferred over the old volumes because:

* Tokens provisioned into the new volumes are only valid for a short TTL and are rotated automatically, minimizing the impact of a token exfiltration.
* Tokens provisioned into the new volumes are bound to the pod, which greatly reduces the difficulty of a forced credential rotation. Operators need only redeploy their application (e.g. trigger a deployment rolling update). This operation is complex to execute without application disruption with the old volumes, and we don’t have any official guidance on the process.
* Tokens provisioned into the new volumes are audience bound to the API server which should dissuade integrators from accepting them as identity proof elsewhere, thus improving the security posture of authentication to the Kubernetes API server.
* Tokens provisioned into the new volumes do not depend on data stored in Kubernetes secrets and are not persisted in any database, reducing the impact and value of a read compromise of the secrets API.
* Tokens provisioned into the new volumes do not depend on data stored in Kubernetes secrets that must be replicated per service account instance which will solve long standing scalability issues with the implementation of service accounts once the migration is complete. See https://github.com/kubernetes/kubernetes/issues/48408
* Tokens provisioned into the new volumes are not referable in environment variables via the Downward API.
* Tokens provisioned into the new volumes have stricter file permission. They must be either `0600` or `0640` when using the "fsGroup" feature. They do not allow overrides to more permissive permissions.

The SecureServiceAccounTokenVolume feature will:

*Switch the service account admission controller to using a projected volume (with a token projection) to implement the old service account volume’s filesystem API.
* Make --service-account-issuer a required flag thus requiring that TokenRequest will be enabled.

Users who use the alpha release track to canary what’s coming down the pike will encounter this and will notice that:

* Their API servers won’t start until they add the flags required to enable TokenRequest
* In-cluster clients of the kubernetes apiserver that don’t reload service account tokens will start failing an hour after deployment. They will need to update these clients. (Partial fix in https://github.com/kubernetes/enhancements/commit/d62f9c9df4e0c3f4dc71a6bb900f619cadc5f9a5)
* PodSecurityPolicies that allowed secret volumes but not projected volumes will no longer be usable with newly created pods that auto-mount service account volumes. They will need to allow projected volumes now. 
* Pre-1.11 Kubelets (assuming they also enable alpha features) will no longer run new pods that mount service account volumes.
* ~~Pods running as non root need an fsGroup or they will not have permission to read the token.~~

We will continue to announce this new behavior each release. We will leave this feature in alpha for a release or more then graduate it to beta and enable it by default. At this point, users will either have to make the changes to upgrade or explicitly disable the beta feature. After a long deprecation, we will promote the feature to GA and remove the ability for clusters to opt out.

### Notified Parties

* sig-apimachinery to consult on plan
* sig-arch to consult on plan
* kubernetes-dev to notify of intent to make this change
* kubernetes-announce to notify of intent to make this change

/kind feature
/sig auth
/sig api-machinery

@kubernetes/sig-auth-feature-requests 
@kubernetes/sig-api-machinery-feature-requests 
@kubernetes/sig-architecture-feature-requests
@liggitt @tallclair @cjcullen @smarterclayton

**Comment by mikedanese** [comment]
This is done.

**Comment by mikedanese** [comment]
Eh, I don't know why I said that.

**Comment by dims** [comment]
@mikedanese i'll remove arch from this now. please re-add when there is a KEP or some other plan for us to look at. is this ok?

/remove-sig architecture

**Comment by mikedanese** [comment]
@dims will do. Thanks.

**Comment by linki** [comment]
We recently started experimenting with expiring BoundServiceAccountTokens and reported https://github.com/kubernetes/kubernetes/issues/87028. Thanks for providing a fix so quickly!

We're now thinking of how we'd roll this out to our clusters in a safe manner knowing that there's probably applications that rely on the fact that ServiceAccount tokens didn't expire in the past. A common pattern we see out there is reading a token at application startup and then never reading it again or by using older version of `client-go` etc.

### Proposed Solution

One way to solve this would be the following: Kubernetes rotates ServiceAccount tokens [at least once per day](https://github.com/kubernetes/kubernetes/blob/v1.18.0-alpha.1/pkg/kubelet/token/token_manager.go#L176-L178). During the transition to BoundServiceAccountTokens we could provision ServiceAccount tokens with a longer expiration time than 1h, say 30 days. We could then monitor the tokens received at the API server and if we see ServiceAccount tokens that are older than 1h we know that there's an application not reading a fresh token from the mounted volume. We can then track it down and update it.

Meanwhile, that application would keep working just fine for at least the next 30 days since the token is considered valid by the API server. Depending on the time window you need to upgrade all your applications you would pick a suitable expiration time for the automatically mounted tokens. Since previous tokens were valid for eternity even a very long expiration time wouldn't compromise security.

Once you're certain all relevant clients refresh their tokens you can reduce the expiration time of the automatically mounted tokens to the proposed default of 1h.

To achieve that all we need is to be able to configure the value [hard-coded value](https://github.com/kubernetes/kubernetes/blob/v1.18.0-alpha.1/plugin/pkg/admission/serviceaccount/admission.go#L525) via a flag or a field in the kubelet config. 

There are at least three alternatives to this approach but I feel they are inferior:
* Disable rejection of expired ServiceAccount tokens in the auth subsystem of the [apiserver itself](https://github.com/kubernetes/kubernetes/blob/v1.18.0-alpha.1/pkg/serviceaccount/claims.go#L106-L107). (basically allowing expired tokens during the transition)
* Disable the built-in AdmissionPlugin and [rebuild the same functionality](https://github.com/kubernetes/kubernetes/blob/v1.18.0-alpha.1/plugin/pkg/admission/serviceaccount/admission.go#L521-L554) as an out-of-tree AdmissionController but using a different expiration time
* Changing the hard-coded value in-place and running a fork for a while

/cc @liggitt @mikedanese @mikkeloscar @szuecs

**Comment by liggitt** [comment]
> One way to solve this would be the following: Kubernetes rotates ServiceAccount tokens at least once per day. During the transition to BoundServiceAccountTokens we could provision ServiceAccount tokens with a longer expiration time than 1h, say 30 days. We could then monitor the tokens received at the API server and if we see ServiceAccount tokens that are older than 1h we know that there's an application not reading a fresh token from the mounted volume. We can then track it down and update it.

That is similar to an approach we discussed in sig-auth, and I think I'm in favor of it. I would actually go further and make the "stale token used" metric trigger when a token older than the minimum bound token age (10 minutes) is used, since that means it is a client that would have problems with the default injected configuration.

Offhand, the specific pieces we need for this would probably be:
1. An option to the kubelet to mint projected token volumes for longer than requested
2. A metric in the API server that counts use of legacy service account tokens (would indicate presence of clients that are extracting/using tokens from Secret objects)
3. A metric in the API server that counts use of pod-bound service account tokens older than 10 minutes (would indicate presence of clients using injected tokens and not refreshing them)
4. Addition of audit annotations for both scenarios so that audit logs can be swept to locate the specific namespace/serviceaccount being used with legacy tokens or stale bound tokens (@logicalhan can confirm, but I would not expect to put the service account name or namespace in the metrics because of cardinality concerns)

Then, our instructions to cluster admins would be:
1. Enable projected tokens, and enable the "mint longer than requested" option in the kubelet
2. Monitor your clusters for legacy token use or stale token use metrics
3. On clusters with either of those metrics present, sweep audit logs to identify the offending application
4. Repeat 2-3 until metrics are clear
5. Disable the "mint longer than requested" option in the kubelet

**Comment by liggitt** [comment]
@linki - for 1.18, I'm focusing on getting the CSR API positioned to graduate to v1, but if you wanted to work with @mikedanese to update the bound service account token KEP with a description of this rollout, and help to get these additions in place, that could help accelerate progress here

**Comment by lavalamp** [comment]
(Drive by idle thought: the suggestions to provide visibility are very similar to what we'd need for ratcheting validation.)

**Comment by mikedanese** [comment]
Thanks for writing this up. This approach can probably be implemented entirely inside the kube-apiserver.

I'm happy to tackle this portion of the problem independently but we'll need a decision on what to do about file permissions as well before we can turn this on by default.

**Comment by happinesstaker** [comment]
I'm going to draft a proposal on safely rolling out projected token while not breaking in-cluster clients.

> Offhand, the specific pieces we need for this would probably be:
> 
> 1. An option to the kubelet to mint projected token volumes for longer than requested
> 2. A metric in the API server that counts use of legacy service account tokens (would indicate presence of clients that are extracting/using tokens from Secret objects)
> 3. A metric in the API server that counts use of pod-bound service account tokens older than 10 minutes (would indicate presence of clients using injected tokens and not refreshing them)

I believe for step 1, we could implement the exception in kube apiserver by providing a flag to treat expired token as valid for up to 30 days. Make all metric/exception code in one place would make it easier to manage.
I would rather define "stale token" as expired token used. To include more "potential breaking" cases, tokens older then 24 hours or older than 80% of their life time could also be considered.

Please remind me if implementing this option in kube apiserver would cause essential tradeoff instead of implementing in kubelet. 

> 4. Addition of audit annotations for both scenarios so that audit logs can be swept to locate the specific namespace/serviceaccount being used with legacy tokens or stale bound tokens (Han Kang can confirm, but I would not expect to put the service account name or namespace in the metrics because of cardinality concerns)

I agree with not exposing SA name or namespace in metric, maybe we could log these info for stale token in case we want to trace down towards which in-cluster client is causing problem.

**Comment by tedyu** [comment]
```
 to treat expired token as valid for up to 30 days.
```
Doesn't this (serving expired token) expose some kind of security hole ?

**Comment by liggitt** [comment]
> I would rather define "stale token" as expired token used.

I would not expect us to intentionally honor/validate tokens past their expiration

**Comment by happinesstaker** [comment]
> Doesn't this (serving expired token) expose some kind of security hole ?
Well this option is served as a temporary transition state from current SA token to projected token. Current token has is not time-bound, so anyway (either issue a 30 day token, or treat expired token up to 30 days as valid) this is not reducing security level.

> I would not expect us to intentionally honor/validate tokens past their expiration
Essentially this should have the same effect as issue a token longer than expected in kubelet (both way the token is valid longer then customers thought), unless there are other tokens sent to kube apiserver for authentication in additional to in-cluster clients. 
Though making an exception in authentication might looks worse, I must agree.
By issue token longer than requested, do you mean always +30 days (for example) to what customer requested? I thought people already using alpha feature would already set some expiration time longer than 10 minutes.

**Comment by liggitt** [comment]
> By issue token longer than requested, do you mean always +30 days (for example) to what customer requested? I thought people already using alpha feature would already set some expiration time longer than 10 minutes.

The expiration time for an admission-injected token is 1 hour.

When the API server is running in this compatibility/warning mode, if a tokenrequest is made for a pod-bound token, by a kubelet, with an expiration time matching the admission-injected projected token volume, the server can mint the token for a longer duration and embed the original requested expiration time in the token as a private `"kubernetes.io":{"warn-after":...}` claim.

The service account token authenticator can annotate the audit log and increment the warning metric if it encounters a token with a warn-after claim used past the warning time.

**Comment by mikedanese** [comment]
I'm 👍 on anything that can help us minimize kubelet changes so we can get this out there. The expirationSeconds magic number sounds reasonably worthwhile.

**Comment by happinesstaker** [comment]
Sounds good to mint longer token in kube apiserver if we see specific expiration time requested, look less hacky.

**Comment by liggitt** [comment]
note that to make the kubelet [refresh on schedule](https://github.com/kubernetes/kubernetes/blob/ce01a9bad026f04bc956cd2bf72211b72675160d/pkg/kubelet/token/token_manager.go#L163-L186), we'd want the server to set status.expiration on the token response to the original 1 hour timeframe, despite having minted the token for longer

**Comment by tallclair** [comment]
I'm not sure if this has been discussed elsewhere, but I think it would be useful to opt-in individual service accounts to the new bound service account volumes before the global feature is enabled. This would be useful for opting in individual workloads that are known to work with the new token volumes so they can take advantage of the improvements, and also for doing a gradual migration to catch bugs before the global feature is enabled.

I'm picturing something like an annotation on the ServiceAccount object, e.g. `bound-service-account-token-volume.beta.kubernetes.io/enable`. This would 1) skip creating the token secret for that service account, and 2) use the new volume type for automounting. Open question is what to do on update (when the annotation is added or removed).

**Comment by happinesstaker** [comment]
The cluster administrator has the ability to opt-in enable the bound service account token feature. Additionally, by enabling the option described by #1597, they could do this "safely" by get the warning instead of failing. We are not going to enable the feature by default globally until we watch from the metrics that a number of clusters have opt-in and the client-side issue are fixed.
Given that, maybe we do not need an extra safe-proof step to provide the option for individual service account to opt-in.

**Comment by tallclair** [comment]
@happinesstaker I respectfully disagree. I think those are good measures that significantly decrease the risk, but a gradual rollout is always a good idea. Furthermore, I want to be able to take advantage of bound service account tokens for our managed workloads before we're ready to force it on our customers.

**Comment by happinesstaker** [comment]
@tallclair  Make sense. Forcing some of the SA for managed workloads to use bound SA token sounds like a nice use case we want this.
Let me evaluate how we could opt-in invidual service account and put your suggestion together as a modification to the KEP.

**Comment by mikedanese** [comment]
@tallclair I think you are looking for https://github.com/kubernetes/kubernetes/issues/77599

**Comment by enj** [comment]
> > * PodSecurityPolicies that allowed secret volumes but not projected volumes will no longer be usable with newly created pods that auto-mount service account volumes. They will need to allow projected volumes now.
> 
> Given that PodSecurityPolicies are deprecated, we should just special case them to allow projected service account token volumes if they allow secret volumes.

They will be deprecated in 1.22 which is still a year away #90603

**Comment by cben** [comment]
I want to start working on auth renewal in Ruby kubeclient lib (https://github.com/abonas/kubeclient/issues/393,) and want to cover this use case too.  Can you help me understand what applications are expected to do? 🙏

Will this affect the default "in-cluster config"?  Or this only for manually granting apps access to some service account?  [this may be a silly question, I don't understand service accounts enough]

What file(s) should the app periodically reload?  Is the whole kubeconfig file being rotated?  Or a separate file with just the token (and is it referenced by path from the kubeconfig)?

Can there be cases where a single kubeconfig would contains multiple contexts using different tokens, each from a volume that needs periodic reloading?

**Comment by mikedanese** [comment]
@cben yes, this mostly only affects clients using in-cluster-config. All you need to do is reload the token from disk every minute. This might be a helpful starting point:

https://github.com/kubernetes-client/ruby/pull/53/files

**Comment by neolit123** [comment]
https://github.com/kubernetes/enhancements/blob/master/keps/sig-auth/1205-bound-service-account-tokens/README.md#scalability

> it adds a token minting operation in the API server every ~48 minutes for every pod.

do we have scale testing plans for this upstream?
my understanding is that if a lot of pods are spawned at once, the rotation would be scheduled for them all at once at the api server.

**Comment by liggitt** [comment]
> do we have scale testing plans for this upstream?

the normal scale tests will exercise this, both in the density and load tests

> my understanding is that if a lot of pods are spawned at once, the rotation would be scheduled for them at the same time at the api server

@mikedanese, do you remember if the renewal time was jittered at all? @msau42, do you know if volume remount operations for multiple pods on the same node happen in parallel or serially?

**Comment by zshihang** [comment]
> if the renewal time was jittered at all?

no, i didn't see we are adding any jittering.

> if volume remount operations for multiple pods on the same node happen in parallel or serially?

serially. https://github.com/kubernetes/kubernetes/blob/2729b8e375143434fc4977fe49eaea572567dac3/pkg/kubelet/volumemanager/reconciler/reconciler.go#L204

**Comment by liggitt** [comment]
> no, i didn't see we are adding any jittering.

Probably worth adding to a list to consider while in beta. If there are issues, I'd expect them to also appear in the "lots of pods startup" phase of scale tests.

> serially

that's good, it means we won't get a thundering herd from a single node

**Comment by msau42** [comment]
> do you know if volume remount operations for multiple pods on the same node happen in parallel or serially?

For every mount operation, we spawn a go routine per unique volume, so the same volume will remount serially, but different volumes will happen in parallel

**Comment by liggitt** [comment]
> For every mount operation, we spawn a go routine per unique volume, so the same volume will remount serially, but different volumes will happen in parallel

ok, good to know. @zshihang, let's add jittering the node renewal to the list for 1.21

**Comment by liggitt** [comment]
jittering added in https://github.com/kubernetes/kubernetes/pull/96037

**Comment by liggitt** [comment]
This feature graduates to beta in 1.21 and is enabled by default. Remaining items to GA are tracked in https://github.com/kubernetes/enhancements/issues/542 and https://github.com/orgs/kubernetes/projects/51

**Comment by TheKangaroo** [comment]
Quick question @mikedanese:
you changed `Pods running as non root need an fsGroup or they will not have permission to read the token.` to strikethrough but I cannot find a way to make non root pods accessing the token without setting fsGroup on that pod. 
Is there something I'm missing? 🤔
