### ISSUE TITLE
CSI alpha tests are failing

### ISSUE THREAD

**Issue by msau42** [kubernetes/kubernetes#70760]
**What happened**:
Probably caused by https://github.com/kubernetes/kubernetes/pull/70193

/kind bug

**Comment by msau42** [comment]
https://k8s-testgrid.appspot.com/sig-storage#gce-alpha-enabled-default

/assign @saad-ali 
@kubernetes/sig-storage-bugs

**Comment by mkimuram** [comment]
@msau42 @saad-ali

I understand that a679486 moved crd creation logic to e2e test's k8s cluster deployment code.
On the other hand, I tested it with manually deployed k8s cluster. 

So, in my case, I guess that in addition to enable ```CSIDriverRegistry``` and ```CSINodeInfo``` feature gates enabled, I need to create crd manually before tests, like below: 

```
# kubectl create -f staging/src/k8s.io/csi-api/pkg/crd/manifests/csidriver.yaml
# kubectl create -f staging/src/k8s.io/csi-api/pkg/crd/manifests/csinodeinfo.yaml
```

I could make two of three SkipAttach tests pass in my environment by above way. 
For "non-attachable volume does not need VolumeAttachment" case, I'm still looking into it. (It doesn't seem to skip creating volumeAttachment, properly)

**Comment by mkimuram** [comment]
@msau42 @saad-ali

I found a typo in ```createCSIDriver```'s argument. While  hostpath driver's ```GetDynamicProvisionStorageClass``` connects driver name and unique name without "-", it connects them with "-". This makes "non-attachable" test fail, due to the mismatch between volume name in crd and provisioner name, as a result, creating volumeAttachment isn't skipped. I will create a PR to fix it.

For above bug, a679486 is unrelated. It just changed the way in how to test in manually deployed k8s cluster as I mentioned in above comment. So, there should be no problem for the PR, at least for the CI testing if it works well in CI environments.

**Comment by saad-ali** [comment]
I can verify that the CRDs are not getting installed on the alpha cluster. Investigating why.

**Comment by wangzhen127** [comment]
I don't think this is fully resolved. There are still failures on
https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-alpha-features
https://k8s-testgrid.appspot.com/google-gce#gci-gce-alpha-features

/reopen

**Comment by msau42** [comment]
@mkimuram can you help take a look at these failures? It's testing CSI filesystem volume mode.

I think it is unrelated to the crd installation issue that Saad fixed.

**Comment by mkimuram** [comment]
@msau42 

I tested with AllAlpha flag and manually created csi crds and confirmed that filesystem volume mode test passed in my environment and also other tests passed there. If I delete csi crds, other tests also fail, so I agree that the issue that Saad fixed is not related.

However, above also means that this issue can't be reproduced in my environment.

**Comment by msau42** [comment]
I1109 14:56:01.141] Nov  9 14:56:01.131: INFO: At 2018-11-09 14:50:54 +0000 UTC - event for security-context-dc2399cc-e42e-11e8-9b95-0a580a3c2a84: {attachdetach-controller } FailedAttachVolume: AttachVolume.Attach failed for volume "pvc-d6000e8b-e42e-11e8-880b-42010a800002" : node "bootstrap-e2e-minion-group-3wtg" has no NodeID annotation

**Comment by msau42** [comment]
Hostpath also seems to be failing because of driver registration issues? Not sure why other alpha tests are passing if that's the case

**Comment by wangzhen127** [comment]
Those 2 failing tests are newly introduced in https://github.com/kubernetes/kubernetes/commit/b89b367247039f4a46a1ca2f0e4e906d723d79d2 and started to fail from the beginning. Is that PR blocking 1.13? If not, can we revert and fix later? I have recently set up optional presubmit tests for alpha features at [pull-kubernetes-e2e-gce-alpha-features](https://k8s-testgrid.appspot.com/presubmits-kubernetes-nonblocking#pull-kubernetes-e2e-gce-alpha-features), which will pick up those 2 tests.

Currently this failure is blocking https://github.com/kubernetes/kubernetes/pull/70034.

**Comment by AishSundar** [comment]
@msau42 @mkimuram  apart from the 2 failing tests, I see ```[sig-storage] CSI Volumes [Driver: com.google.csi.gcepd][Serial] [Testpattern: Dynamic PV (filesystem volmode)] volumeMode[Feature:BlockVolume] should create sc, pod, pv, and pvc, read/write to the pv, and delete all created resources``` which @saad-ali addressed with #70780 is also flaky. 

These failures are now blocking PRs as mentioned above. As we enter code slush today, its very critical to have the PRs get in sooner than later. Can we plz revert the feature and the tests until they are fully resolved and ready to go. Thanks

**Comment by msau42** [comment]
I prefer disabling the specific tests instead of reverting the entire pr. We will lose important signal for csi

**Comment by wangzhen127** [comment]
> I prefer disabling the specific tests instead of reverting the entire pr. We will lose important signal for csi

That works for me. Can you cc me on the PR that disables those tests?

When you re-enable the tests, remember to try them out on [pull-kubernetes-e2e-gce-alpha-features](https://k8s-testgrid.appspot.com/presubmits-kubernetes-nonblocking#pull-kubernetes-e2e-gce-alpha-features). :)

**Comment by mkimuram** [comment]
@AishSundar 

Let me consider if we can just skip these test for CSI, instead of reverting the entire patch.

**Comment by gnufied** [comment]
@mkimuram you mean just skipping them in Alpha cluster right?

**Comment by mkimuram** [comment]
@gnufied 

I was thinking about skipping the below test with the combination of below drivers:

[Test]
 -  [Testpattern: Dynamic PV (filesystem volmode)] volumeMode[Feature:BlockVolume] should create sc, pod, pv, and pvc, read/write to the pv, and delete all created resources

[Driver]
 - csi-hostpath
 - com.google.csi.gcepd

Won't it enough? Or, do we need to skip it only with alpha cluster?

**Comment by mkimuram** [comment]
@AishSundar 

> If we just disable the tests alone and not revert the feature, we are just masking the issue. 

Actually, there is no feature added in either of culprit commits. It added tests or intended to improve the way it is tested.

Therefore, it must be a test issue or another issue which is found by the test added, not an issue introduced by the commits themselves.

> My fear is we might forget the fact that its disabled since there's no active reporting on it.

In the code, there is a clear comment that the test is skipped due to this issue with the reference to this issue#, so this won't be forgot. If you still worry about this issue is not tracked, we might be able to keep this issue open.

**Comment by AishSundar** [comment]
@mkimuram IIUC the test that were failing (and are being reverted) were added for the new CSI festures going to Alpha in 1.13, right? so even these 2 culprit commits do not contain feature work, it is testing some new code additions to 1.13 and now those will be untested until we re-enable these tests.

Is there an ETA to re-enable them, preferably sometime early next week? Yes +1 to keeping this issue open to track the skipped tests.

**Comment by mkimuram** [comment]
@AishSundar 

> IIUC the test that were failing (and are being reverted) were added for the new CSI festures going to Alpha in 1.13, right? so even these 2 culprit commits do not contain feature work, it is testing some new code additions to 1.13 and now those will be untested until we re-enable these tests.

The two failing tests themselves are not for new alpha features that are added in v1.13.
Instead, they are just to test csi driver works well as it works in existing in-tree driver.
(And failed because they might be affected by some other alpha features added or some of specific configurations in gce.)

In addition, #68025 added ~50 tests for csi driver, so it would be better not to remove all of the tests by reverting the PR, just for the 2 failing tests. I think that just reverting the patch won't help improving quality of k8s. 

> Is there an ETA to re-enable them, preferably sometime early next week?

As for ETA to solve the issue, I found difficulty in debuging in my local environment.
It seems that the two tests fail in gce environment w/ AllAlpha=true,
however, as I've already mentioned, at least csi-hostpath tests in my local environment w/ AllAlpha=true doesn't fail.(And I don't have test environment for gce.)

Of course, I will help solving the issue next week. However, I will need someone's help for testing combinations of alpha features in gce environment to narrow down which flag really affects this issue.
At least I would like to know the results:
  - w/ MountPropagation=true,CSIPersistentVolume=true,BlockVolume=true,CSIBlockVolume=true
  - all alpha flags except CSIDriverRegistry and CSINodeInfo

**Comment by AishSundar** [comment]
/reopen

@mkimuram Thanks for the detailed explanation. I think the revert is fine in this case then. I am keeping this issue open however to track and fix the failures in these 2 tests

@msau @cjwagner @BenTheElder can any of you help answer [the ques above](https://github.com/kubernetes/kubernetes/issues/70760#issuecomment-437556455) w.r.t alpha features on gce environment. thanks

**Comment by msau42** [comment]
I can help debug when I'm back on Tuesday. In the meantime, I would suggest looking through the failing test logs to try to triage what's going on

**Comment by msau42** [comment]
Here's one failing run: https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-alpha-features/26000

**Comment by msau42** [comment]
The hostpath plugin should be deployed as a DaemonSet, so it's strange that it's only getting registered on only one node.

**Comment by davidz627** [comment]
@msau42 could you link the PR for skipping [external-gcepd] tests into this issue when you do that as well

**Comment by msau42** [comment]
skipping gcePD-external is here: https://github.com/kubernetes/test-infra/pull/10142

**Comment by jberkus** [comment]
Since gce-cos-alphafeatures is now passing, do we need to keep this issue open?  Should it morph into a non-blocking issue for longterm work on a better test?

**Comment by msau42** [comment]
We have root caused 2 of the 3 failures, which were problems in the test and test conifg. Fixes will be out soon. Still triaging the 3rd failure, which could be a real bug in alpha clusters

**Comment by mkimuram** [comment]
@msau42 

I've root caused csi-hostpath failure issue. It just failed to set the node properly in test code side.
I will make a PR to fix it.

**Comment by mkimuram** [comment]
@msau42 

Or should it be done in your PR too, to avoid modifying ```skipTestUntilBugfix``` twice in the separate PR?

Actually, the fix are as below:
(Failing to set node before pod creation)

```
# git diff
diff --git a/test/e2e/framework/pv_util.go b/test/e2e/framework/pv_util.go
index 53483fd193..bc6e5c97b2 100644
--- a/test/e2e/framework/pv_util.go
+++ b/test/e2e/framework/pv_util.go
@@ -880,12 +880,13 @@ func CreateSecPod(client clientset.Interface, namespace string, pvclaims []*v1.P
 // create security pod with given claims
 func CreateSecPodWithNodeName(client clientset.Interface, namespace string, pvclaims []*v1.PersistentVolumeClaim, isPrivileged bool, command string, hostIPC bool, hostPID bool, seLinuxLabel *v1.SELinuxOptions, fsGroup *int64, nodeName string, timeout time.Duration) (*v1.Pod, error) {
        pod := MakeSecPod(namespace, pvclaims, isPrivileged, command, hostIPC, hostPID, seLinuxLabel, fsGroup)
+       // Setting nodeName
+       pod.Spec.NodeName = nodeName
+
        pod, err := client.CoreV1().Pods(namespace).Create(pod)
        if err != nil {
                return nil, fmt.Errorf("pod Create API error: %v", err)
        }
-       // Setting nodeName
-       pod.Spec.NodeName = nodeName
 
        // Waiting for pod to be running
        err = WaitTimeoutForPodRunningInNamespace(client, pod.Name, namespace, timeout)
```

**Comment by mkimuram** [comment]
Created https://github.com/kubernetes/kubernetes/pull/71039 for csi-hostpath fix, to prepare for the case that we need a separate PR. We can discuss more on this there, if needed.

**Comment by davidz627** [comment]
/unassign
found possible root cause, @verult has the most context for the fix
/assign @verult

**Comment by verult** [comment]
The symptom of the remaining test failure is the test pod fails to create because it fails to attach with the error: `Attach failed for volume <volumename>: node <nodename> has no NodeID annotation`. The test succeeds the first time it's run in a cluster, and always fails after that.

Two issues caused this error message.
1. When the CSI external-attacher tries to fetch the `CSINodeInfo` object to get the NodeID, it does so through an informer. The first time the test is run, `CSINodeInfo` objects are created for the very first time, and the informer returns the correct object. In subsequent test runs, `CSINodeInfo`s from the first run is kept, and for some reason the informer fails to detect the object and returns empty. Making the API call directly works, I'll patch the external-provisioner with this to mitigate the issue, and this is sufficient to get the test to pass. The informer bug will need to be eventually fixed.
https://github.com/kubernetes-csi/external-attacher/blob/9da8c6d20d58750ee33d61d0faf0946641f50770/pkg/controller/csi_handler.go#L500
1. Kubelet fails to post the NodeID annotation sometimes, likely due to node status patch not being retried correctly. This is crucial for clusters without `CSINodeInfo` feature flag set, and this is the default for 1.13. Will add the appropriate retry mechanism.
https://github.com/kubernetes/kubernetes/blob/12402742041386b82c89b1c64cb855bdc1691928/pkg/volume/csi/nodeinfomanager/nodeinfomanager.go#L176

**Comment by verult** [comment]
Opened #71052 to track the informer issue

**Comment by AishSundar** [comment]
@msau @verult Are #71058 and potential PR for #71052 the only 2 fixes being actively worked on for this issue?

**Comment by msau42** [comment]
Only #71058 is needed.  We have a workaround for #71052

**Comment by AishSundar** [comment]
@msau will you have a followup PR to enable the CSI alpha tests back? or is that already in flight?

**Comment by msau42** [comment]
#71058 also reenables the tests

**Comment by AishSundar** [comment]
OK with #71058  merged we should see the CSI alpha tests re-enable. 

@jberkus @mariantalla @mortent to keep an eye out for CI signal

**Comment by jberkus** [comment]
The tests got reenabled 5 days ago, and alpha tests are passing.  Closing this issue.  Thanks everyone for your rapid turnaround!

/close
