### ISSUE TITLE
Pod API Clients, Certificates, and Pod External API Clients

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#7081]
Some requirements:
- Pods that need to reach the APIserver need to know where it is.  
- The method should support multiple apiservers.
- The client needs to know what name to expect on the cert that the master presents.
- The client needs to know what root CAs it trusts for the master's cert when setting up TLS with the master.
- The client needs to know what root CAs it trusts when establishing TLS with external services, like cloud.google.com, github.com, etc.

Some master discovery options:
- static list of master IPs 
  - doing that in #7055
- via a kubernetes serviceIP
- via DNS
  - requires that all K8s distros have a way to put the kubernetes service into DNS.  

How do pods get root certs to verify identity of external remote service:
- Use Node OS root certs, like in #6916?  
- Use Container Image root certs (should gcr.io provide a curated base image with trusted root certs, like https://registry.hub.docker.com/u/centurylink/ca-certs/ 
- Assume people use a OS distro with root certs as their base image

How do pods get root cert to verify identity of self-signed cert on master?

**Comment by erictune** [comment]
@roberthbailey @thockin @cjcullen @ArtfulCoder we have talked about these issues.

**Comment by cjcullen** [comment]
For pods getting root certs, I think container image root certs (instead of Node OS certs) makes sense in the general case. Then if you want to build a container image from scratch, you can build the CA cert you need into your image or mount it in a "root CAs" RO volume for your whole cluster.

For the kube-master cert, we could add the self-signing CA's cert as a secret to the cluster at the end of cluster bring-up (a la system tokens). Then there would be a standard way for pods that need to talk to the apiserver to mount the CA cert and configure tools to use it to verify the master's cert.

**Comment by roberthbailey** [comment]
> Pods that need to reach the APIserver need to know where it is

From what I understand, there's currently a service available for this. Can you explain the shortcomings of the current implementation?

> The client needs to know what root CAs it trusts when establishing TLS with external services, like cloud.google.com, github.com, etc.

I don't think this relates to discovering the master or connecting securely, and shouldn't be dictated by the system. There are many ways that folks can configure their trusted root CAs in their pods, and we should allow them to do it in the way that works best for them.

**Comment by erictune** [comment]
When I wrote this I was thinking particularly about  kube-proxy, and the components on master node, where there is no kube-proxy.  So service doesn't work there.  But, for the more general case, I agree service should work.

**Comment by erictune** [comment]
I am a little fuzzy on how the client verifies the identity of the master via the service, using the master's cert.   Does the master's cert have DNS name "kubernetes", or does it have a fully qualified DNS name, like "kubernetes.blah.example.com." or does it have an URI?  I was hoping you knew, @roberthbailey

**Comment by roberthbailey** [comment]
I can explain how it works for kubectl, and then we can talk about how it should work for services. For kubectl, the client has a copy of the CA root that signed the master cert (embedded within the kubeconfig file). It constructs a tls.Config that contains the CA root so that it will trust the certificate provided by the master (see [pkg/client/transport.go#L148-L175](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/client/transport.go#L148-L175)). 

The master's cert has 'kubernetes-master' as the common name (CN) and the master IP as a subject alternative name (SAN) as per `./easyrsa --subject-alt-name=IP:$cert_ip build-server-full kubernetes-master nopass > /dev/null 2>&1` in [cluster/saltbase/salt/generate-cert/make-ca-cert.sh](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cluster/saltbase/salt/generate-cert/make-ca-cert.sh). kubectl stores the server's IP address so it connects via IP and verifies that the presented cert matches (using the SAN). 

For services, we are generating a kubeconfig file that will need to have a copy of the root CA embedded (otherwise the connection will fall back to being insecure, which we don't want). Then the client will need to either connect to a common name that matches the cert or the IP address of the master. Since the CN is set to 'kubernetes-master' we should either rename it to 'kubernetes' to match the proposed service name or rename the service to match the CN.

**Comment by thockin** [comment]
Is there work to do here?  It feels like this is done.

**Comment by erictune** [comment]
I'm not sure if anyone has tested HA master recently.  If that works, then the first two requirements from the first post must be done.

I think the third one is not done.  The kubernetes TLS client just checks that the master has a cert which has a known root, but it does not check that it is the right cluster, as opposed to an impostor cluster with a different name but the same root.  This feels bad.

The fourth requirement is done because a service account's secret has the root cert used by this cluster.

The fifth requirement is done to the extent that we are happy with the source of root certs (For other than K8s) being the base image used by the container.

So, not quite done.
