### ISSUE TITLE
TestReadConfigData needs a better util.ReadConfigDataFromReader() which succeeds on success and fails on failure

### ISSUE THREAD

**Issue by quinton-hoole** [kubernetes/kubernetes#7104]
I couldn't help but wonder whether this error that I'm seeing locally is related to #6954 . I've just rebased against upstream head.

--- FAIL: TestReadConfigData (15.25s)
helpers_test.go:246: unexpected non-error for http://some.non.existent.foobar
FAIL
FAIL github.com/GoogleCloudPlatform/kubernetes/pkg/kubectl/cmd/util 15.333s

I'll debug further in the morning.

**Comment by jlowdermilk** [comment]
This is passing at head both on Travis and locally, so it must be related to changes you've made. If it's not returning an error in that case, it means that `http.Get` returned a valid response [here](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubectl/cmd/util/helpers.go#L190). Did you perhaps change the tests to mock/intercept outgoing http requests?

**Comment by quinton-hoole** [comment]
No, the only changes I've made are to test/e2e/pods.go.  Agreed through, it must be something to do with my local environment, as nobody else seems to be running into this problem.  Never mind, I'll sort it out.

**Comment by quinton-hoole** [comment]
I fixed my local environment with some sudo make clean voodoo.  Closing.

**Comment by seh** [comment]
I ran into this same failure building for the first time on Mac OS, so it's hard to blame it on the environment not being clean.

**Comment by seh** [comment]
By modifying the failing test, I was able to determine that the test fails because requesting the URL _http://some.non.existent.foobar_ from the test server yields a response with the following prefix:
```<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">
<html>
  <head>
    <meta http-equiv=\"refresh\" content=\"0;url=http://searchassist.verizon.com/main?InterceptSource=...
```
That's my ISP providing an unhelpful response to a failed DNS lookup. I guess the test is expecting that the HTTP client will fail to connect, but in this case it succeeds because my overeager ISP fakes a response, defeating expectations.

The `util.ReadConfigDataFromReader` function collects the response body, makes sure it's not empty, and calls it a success. Given that it doesn't matter what the content is, as long as it's nonempty, this test can't prove its intended point without relying on apparently unreliable DNS behavior.

**Comment by quinton-hoole** [comment]
Yes, thanks for doing a better job of debugging than I did @seh . We should fix this test.  Updating title accordingly, and re-opening.

**Comment by quinton-hoole** [comment]
@seh , a PR to fix this would be very well received :-)

**Comment by cjellick** [comment]
@quinton-hoole I got this failure for the same reason. The thing is, the URL returns a 200 response code and a non-empty body. So, I think `util.ReadConfigDataFromReader()`, it is doing its job. Would switching the URL to something on localhost that _shouldnt_ be listening be reasonable? Maybe `http://localhost:9999/foobar`

**Comment by AdoHe** [comment]
@quinton-hoole @cjellick I met the same problem today when I was running `hack/test-go.sh`, and when I run this command: `curl -v -L http://some.non.existent.foobar`, after two 302 responses, I get a 200 response, so the `TestReadConfigData` just failed, guess we should replace the non-existent to a local url which doesn't exist indeed.

**Comment by smarterclayton** [comment]
Closing due to age, reopen if this is re-creatable.
