### ISSUE TITLE
gce-master-scale-performance tests are timing out

### ISSUE THREAD

**Issue by mariantalla** [kubernetes/kubernetes#71215]
**Which jobs are failing**:
[sig-release-master-blocking#gce-master-scale-performance](https://k8s-testgrid.appspot.com/sig-release-master-blocking#gce-master-scale-performance)

**Which test(s) are failing**:
The tests are timing out.

**Since when has it been failing**:
2018-11-16

**Anything else we need to know**:
The diff since last passing test (Nov 15th) is [here](https://github.com/kubernetes/kubernetes/compare/4fdac1960...7ff49c99d?). 

/kind failing-test

**Comment by AishSundar** [comment]
The latest run failed the Density test - https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/260

**Comment by mborsz** [comment]
I just checked this and it's safe to ignore: it's problem with the test itself and not the regression.

I see in gce activity logs that the following vms were restarted due to hostError:
* gce-scale-cluster-minion-group-4-ttff
* gce-scale-cluster-minion-group-q9bw
* gce-scale-cluster-minion-group-2-9sbz
* gce-scale-cluster-minion-group-1-v8jc
* gce-scale-cluster-minion-group-3-2dk9

Our test doesn't support cases when nodes disappear for that reason well and fails in that case. I'm working on fixing the test to be resistant to cases like that.

**Comment by AishSundar** [comment]
The latest run of this job passed - https://k8s-testgrid.appspot.com/sig-release-master-blocking#gce-master-scale-performance

**Comment by jberkus** [comment]
OK, switching this to a long-term fix non-blocker

/priority important-longterm
/kind flake
/remove-kind failing-test

**Comment by jberkus** [comment]
ooops

/remove-priority important-soon

**Comment by wojtek-t** [comment]
This is a duplicate of: https://github.com/kubernetes/test-infra/issues/10188

The problem is that prow started the job for the second time, which killed the underlying cluster from this run. And without cluster, it's not unexpected that the test timedout.
