### ISSUE TITLE
Add a test for "graceful" CSI upgrade between 1.12 to 1.13

### ISSUE THREAD

**Issue by saad-ali** [kubernetes/kubernetes#71282]
**What happened**:

Kubernetes v1.13 supports CSI 1.0.
Kubernetes v1.12 and 1.11 support CSI 0.3).

CSI 1.0 is not backwards compatible with CSI 0.3 (see https://github.com/kubernetes/kubernetes/issues/71228#issuecomment-440434852).

Therefore the upgrade from an earlier version to 1.13 will be disruptive for anyone depending on the CSI driver.

A vendor may choose to make a version of a CSI driver that supports both versions. But that is unlikely.

The disruptive upgrade path is: Remove the old CSI drivers from the cluster before upgrading. Upgrade master and node to k8s v1.13, and wait until master and all nodes are upgraded to 1.13, and then deploy the new CSI 1.0 compatible version of the driver.

This approach will be disruptive for the duration of the cluster upgrade as it would mean that during the upgrade no volumes of that type can be provisioned/attached/mounted/etc. After the cluster/driver upgrade things should just start working again with the existing PV/PVCs/objects (unless the driver name changed, or the driver had some other change between 0.3 and 1.0 that prevents it from operating on the old PV/PVC/Storageclass objects).

**What you expected to happen**:

A possible path for non-disruptive upgrade:

Before upgrade:

1. Deploy 2 driver daemonsets: one that is 1.12 (CSI 0.3) compatible and one that is 1.13 (CSI 1.0) compatible.
2. Replace the CSI 0.3 compatible driver controller with a CSI 1.0 compatible driver controller.

After the upgrade:

1. Remove the CSI 0.3 compatible daemonset.

This *should* enable non-disruptive upgrades as long as the driver name does not change across upgrades, and other then CSI version the driver remains backwards compatible.

This is possible because v1.13 changes the CSI driver registration directory, and a 1.12 kubelet will ignore the CSI 1.0 deployment, and a 1.13 kubelet will ignore the CSI 0.3 deployment.

Action item here is to write an upgrade test to verify this.

CC @davidz627 @msau42 @AishSundar @msau42 

/sig storage
/milestone v1.13

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/kind bug

**Comment by davidz627** [comment]
@saad-ali here's my state dump for today. 

Attempted to investigate this today but was unable to upgrade a cluster from `1.12->1.13` not for lack of trying. 

Some learnings and thoughts:
- Deployments of driver pods has to be namespaced or have different deployment names as to not collide
- `registration-dir` must be changed to `DirectoryOrCreate` since the new ` /var/lib/kubelet/plugins_registry/` directory doesn't exist in `1.12`
- Its possible that registration may not work properly after upgrade to `1.13` due to socket already pre-existing in the directory. Not sure if the Plugin Watcher will reconcile or if it just reacts to "new" sockets.
  - @RenaudWasTaken might be able to confirm/deny
- Driver name must be stable between versions (for storage class to be stable (for finding the driver to do operations on a pre-existing pod to work))
- Naive method of running double driver will have 2 versions of `external-provisioner` and `external-attacher` running which will race to react to `PVC` and `VolumeAttachment` objects respectively.
  - User would have to modify "old" deployment to remove controller components and only deploy "new" controller components, provisioning/attaching will be either down or racey in transition state depending on ordering of operations
- We should have docs somewhere for updating clusters or have the scripts be easier to use

Attempted (and unsuccessful) upgrade methods:
`cluster/gce/upgrade.sh ci/latest`
`kubetest --provider=gce --gcp-project=dyzz-test --test --check-version-skew=false --test_args="--ginkgo.focus=\[Feature:ClusterUpgrade\]"`
`kubetest --provider=gce --gcp-project=dyzz-test --test --check-version-skew=false --test_args="--ginkgo.focus=\[Feature:ClusterUpgrade\]" --upgrade_args="--upgrade-target=ci/latest"`
none of which were particularly successful.

**Comment by liggitt** [comment]
This is resolved by 
https://github.com/kubernetes/kubernetes/pull/71314

/close
