### ISSUE TITLE
Tracking: Complete list of Storage-related flakes for 1.13

### ISSUE THREAD

**Issue by jberkus** [kubernetes/kubernetes#71434]
Per discussion at the burndown this morning, here's the list of test jobs that have storage-related flakes currently, and which tests are flaking on each.  If all get closed, we'll be able to close this issue.

The goal of this is to see if the current PRs we have in flight are expected to address a majority of test flakes.  As such, I've only included flakes that either occurred more than once, seem to be independant of general test job fails, or seem to be contributing to a generally flaky test.

* [gce-cos-master-default](https://k8s-testgrid.appspot.com/sig-release-master-blocking#gce-cos-master-default) (blocking)  Currently *passing*, some of the flakes might have been resolved.  The first flake occured multiple times in the last week, most of the other flakes only once.
  * [sig-storage] Detaching volumes should not work when mount is in progress
  * [sig-storage] In-tree Volumes [Driver: nfs] [Testpattern: Pre-provisioned PV (default fs)] subPath should support readOnly directory specified in the volumeMount
  * [sig-storage] In-tree Volumes [Driver: nfs] [Testpattern: Pre-provisioned PV (default fs)] subPath should support readOnly directory specified in the volumeMount
  * [sig-storage] PersistentVolumes-local [Volume type: dir-link-bindmounted] One pod requesting one prebound PVC should be able to mount volume and write from pod1
  * [sig-storage] PersistentVolumes-local [Volume type: dir] One pod requesting one prebound PVC should be able to mount volume and write from pod1
  * [sig-storage] Projected secret should be consumable from pods in volume as non-root with defaultMode and fsGroup set [NodeConformance] [Conformance]
  * [sig-storage] EmptyDir volumes when FSGroup is specified [NodeFeature:FSGroup] new files should be created with FSGroup ownership when container is root
  * [sig-storage] In-tree Volumes [Driver: gcepd] [Testpattern: Inline-volume (default fs)] subPath should support non-existent path
  * [sig-storage] In-tree Volumes [Driver: gcepd] [Testpattern: Inline-volume (default fs)] volumes should be mountable
  * [sig-storage] In-tree Volumes [Driver: gluster] [Testpattern: Inline-volume (default fs)] subPath should support readOnly directory specified in the volumeMount
  * [sig-storage] PersistentVolumes-local [Volume type: dir] Set fsGroup for local volume should set same fsGroup for two pods simultaneously
  * [sig-storage] In-tree Volumes [Driver: hostPathSymlink] [Testpattern: Inline-volume (default fs)] subPath should support existing directory
  * [sig-storage] In-tree Volumes [Driver: nfs] [Testpattern: Dynamic PV (default fs)] subPath should support existing directory
* [gce-cos-master-slow](https://k8s-testgrid.appspot.com/sig-release-master-blocking#gce-cos-master-slow) (blocking) and [gce-cos-1.13-slow](https://k8s-testgrid.appspot.com/sig-release-1.13-blocking#gce-cos-1.13-slow) This is a flaky test in general, but the host of subpath failures seems to indicate that something is wrong.  Currently passing
  * [sig-storage] In-tree Volumes [Driver: gluster] [Testpattern: Pre-provisioned PV (default fs)] volumeIO should write files of various sizes, verify size, validate content [Slow]
  * [sig-storage] CSI Volumes [Driver: csi-hostpath-v0] [Testpattern: Dynamic PV (default fs)] subPath should fail if subpath file is outside the volume [Slow]
  * [sig-storage] CSI Volumes [Driver: csi-hostpath-v0] [Testpattern: Dynamic PV (default fs)] subPath should fail if subpath with backstepping is outside the volume [Slow]
[sig-network] Services should have session affinity work for LoadBalancer service with ESIPP on [Slow] [DisabledForLargeClusters]
  * [sig-storage] CSI Volumes [Driver: csi-hostpath] [Testpattern: Dynamic PV (default fs)] subPath should fail if non-existent subpath is outside the volume [Slow]
  * [sig-storage] CSI Volumes [Driver: csi-hostpath] [Testpattern: Dynamic PV (default fs)] subPath should fail if subpath file is outside the volume [Slow]
  * [sig-storage] Mounted flexvolume expand[Slow] Should verify mounted flex volumes can be resized
  * [sig-storage] CSI Volumes [Driver: csi-hostpath] [Testpattern: Dynamic PV (default fs)] subPath should fail if subpath directory is outside the volume [Slow]
  * [sig-storage] CSI Volumes [Driver: csi-hostpath-v0] [Testpattern: Dynamic PV (default fs)] subPath should fail if non-existent subpath is outside the volume [Slow]
  * [sig-storage] CSI Volumes [Driver: csi-hostpath-v0] [Testpattern: Dynamic PV (default fs)] subPath should fail if subpath directory is outside the volume [Slow]
  * [sig-storage] In-tree Volumes [Driver: hostPathSymlink] [Testpattern: Inline-volume (default fs)] subPath should fail if subpath with backstepping is outside the volume [Slow]
  * [sig-storage] CSI Volumes [Driver: csi-hostpath] [Testpattern: Dynamic PV (default fs)] subPath should fail if subpath with backstepping is outside the volume [Slow]
  * [sig-storage] In-tree Volumes [Driver: gcepd] [Testpattern: Inline-volume (default fs)] subPath should fail if subpath directory is outside the volume [Slow]
  * [sig-storage] In-tree Volumes [Driver: nfs] [Testpattern: Inline-volume (default fs)] subPath should fail if subpath directory is outside the volume [Slow]
  * [sig-storage] In-tree Volumes [Driver: emptydir] [Testpattern: Inline-volume (default fs)] subPath should support creating multiple subpath from same volumes [Slow]
  * [sig-storage] In-tree Volumes [Driver: gluster] [Testpattern: Inline-volume (default fs)] subPath should fail if subpath file is outside the volume [Slow]
* [gce-cos-master-serial](https://k8s-testgrid.appspot.com/sig-release-master-blocking#gce-cos-master-serial) and [gce-cos-1.13-serial](https://k8s-testgrid.appspot.com/sig-release-1.13-blocking#gce-cos-1.13-serial) only a few flakes, which are scattered among the tests, but some of them involve storage/CSI
  * [sig-storage] CSI Volumes [Driver: csi-hostpath-v0] [Testpattern: Dynamic PV (default fs)] subPath should unmount if pod is gracefully deleted while kubelet is down [Disruptive][Slow]
  * [sig-storage] [Serial] Volume metrics should create prometheus metrics for volume provisioning and attach/detach
  * [sig-storage] GenericPersistentVolume[Disruptive] When kubelet restarts Should test that a volume mounted to a pod that is deleted while the kubelet is down unmounts when the kubelet returns.
  * [sig-storage] CSI Volumes [Driver: pd.csi.storage.gke.io][Serial] [Testpattern: Dynamic PV (default fs)] subPath should support existing directory
* [gce-new-master-upgrade-master](https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gce-new-master-upgrade-master) Only a few flakes
  * [sig-storage] [Serial] CSI Volumes CSI plugin test using CSI driver: hostPath [Serial] should provision storage
  * sig-storage] GenericPersistentVolume[Disruptive] When kubelet restarts Should test that a volume mounted to a pod that is deleted while the kubelet is down unmounts when the kubelet returns.
  * [sig-storage] [Serial] Volume metrics PVController should create bound pv/pvc count metrics for pvc controller after creating both pv and pvc
* [gce-new-master-upgrade-master-parallel](https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gce-new-master-upgrade-master-parallel) again, just a few flakes, and they seem to be subpath-related
  * [sig-storage] In-tree Volumes [Driver: gluster] [Testpattern: Inline-volume (default fs)] subPath should support file as subpath
  * [sig-storage] In-tree Volumes [Driver: gluster] [Testpattern: Pre-provisioned PV (default fs)] subPath should support existing directory
* [gce-new-master-upgrade-cluster-parallel](https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gce-new-master-upgrade-cluster-parallel) same as other upgrade tests
  * [sig-storage] EmptyDir volumes volume on default medium should have the correct mode [NodeConformance] [Conformance]
  * [sig-storage] In-tree Volumes [Driver: gluster] [Testpattern: Pre-provisioned PV (default fs)] subPath should support existing directory
  * [sig-storage] In-tree Volumes [Driver: gcepd] [Testpattern: Inline-volume (default fs)] subPath should support existing directory
  * [sig-storage] In-tree Volumes [Driver: nfs] [Testpattern: Dynamic PV (default fs)] subPath should support readOnly directory specified in the volumeMount
* [gce-master-new-downgrade-cluster](https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gce-master-new-downgrade-cluster)
  * [sig-storage] In-tree Volumes [Driver: gluster] [Testpattern: Inline-volume (default fs)] volumeIO should write files of various sizes, verify size, validate content [Slow]
* [gce-new-master-upgrade-cluster-new](https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gce-new-master-upgrade-cluster-new)
  * [sig-storage] [Serial] Volume metrics PVController should create bound pv/pvc count metrics for pvc controller after creating both pv and pvc
  * [sig-storage] [Serial] Volume metrics should create prometheus metrics for volume provisioning and attach/detach
* [gce-new-master-upgrade-cluster-new-parallel](https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gce-new-master-upgrade-cluster-new-parallel) mostly notable for the additional failure of "detach volume"
  * [sig-storage] Detaching volumes should not work when mount is in progress
  * [sig-storage] CSI Volumes [Driver: csi-hostpath-v0] [Testpattern: Dynamic PV (default fs)] subPath should fail if subpath file is outside the volume [Slow]

/kind flake
/sig storage
/priority important-soon
/milestone v1.13
attn:
@saad-ali @msau42 @AishSundar @mkimuram

**Comment by msau42** [comment]
These are all the PRs and issues I know about tracking storage flakes

#71428 should solve most "subPath should fail" flakes, especially for csi plugins
#71429 should solve the "mount in progress" flakes
#64474 root causes the "local PV fsgroup" flake, but actually fixing it is very complicated. We're still deciding if we want to add such complication to fix a small corner case, or just not support the corner case.
#64047 tracks the "gluster volumeIO" flake. No progress has been made on triaging, I am trying to find a new owner

**Comment by msau42** [comment]
cc @gnufied for volume metrics flakes

**Comment by msau42** [comment]
@jberkus is there a way to sort these by flakiness so we can prioritize investigation/fixes?

**Comment by msau42** [comment]
> Josh Berkus is there a way to sort these by flakiness so we can prioritize investigation/fixes?

Using the triage tool helps sort by most failing, although it also gives us test failures that are not being tracked here:
https://storage.googleapis.com/k8s-gubernator/triage/index.html?test=sig-storage

**Comment by AishSundar** [comment]
I see https://github.com/kubernetes/kubernetes/issues/64474 and https://github.com/kubernetes/kubernetes/issues/64047 have been open since May of this year. So I would take these off the blocker list for 1.13 unless
(i) error trace is different from before
(ii) its showing up way more frequently now (i.e., not much of a corner case anymore)

@jberkus can you help confirm that please?

**Comment by msau42** [comment]
Opened https://github.com/kubernetes/kubernetes/issues/71438 to track local PV flaky tests

**Comment by jberkus** [comment]
@msau42 I'll bug the Gluster team about it, see if I can get some help from that end.

**Comment by AishSundar** [comment]
Since there are a few tests that fail across multiple jobs, here's a pivot on the tests instead of the job. @msau42 can you please edit this comment with known open issues tracking these failures? 

Basically I see the following 4 categories of failures

**1.  PersistentVolumes-local  failures - Tracked by #71438 and #64474 **
*  [sig-storage] PersistentVolumes-local [Volume type: dir-link-bindmounted] One pod requesting one prebound PVC should be able to mount volume and write from pod1
* [sig-storage] PersistentVolumes-local [Volume type: dir] One pod requesting one prebound PVC should be able to mount volume and write from pod1
* [sig-storage] PersistentVolumes-local [Volume type: dir] Set fsGroup for local volume should set same fsGroup for two pods simultaneously

**2.  In-tree Volumes for various drivers** 
 * [sig-storage] In-tree Volumes [Driver: nfs] [Testpattern: Pre-provisioned PV (default fs)] subPath should support readOnly directory specified in the volumeMount
 * [sig-storage] In-tree Volumes [Driver: nfs] [Testpattern: Dynamic PV (default fs)] subPath should support existing directory
 * [sig-storage] In-tree Volumes [Driver: nfs] [Testpattern: Inline-volume (default fs)] subPath should fail if subpath directory is outside the volume [Slow]
 * [sig-storage] In-tree Volumes [Driver: nfs] [Testpattern: Dynamic PV (default fs)] subPath should support readOnly directory specified in the volumeMount
 * [sig-storage] In-tree Volumes [Driver: gcepd] [Testpattern: Inline-volume (default fs)] subPath should support non-existent path
 * [sig-storage] In-tree Volumes [Driver: gcepd] [Testpattern: Inline-volume (default fs)] volumes should be mountable
 * [sig-storage] In-tree Volumes [Driver: gcepd] [Testpattern: Inline-volume (default fs)] subPath should support existing directory
 * [sig-storage] In-tree Volumes [Driver: gcepd] [Testpattern: Inline-volume (default fs)] subPath should fail if subpath directory is outside the volume [Slow]
 * [sig-storage] In-tree Volumes [Driver: gluster] [Testpattern: Inline-volume (default fs)] subPath should support readOnly directory specified in the volumeMount
 * [sig-storage] In-tree Volumes [Driver: gluster] [Testpattern: Pre-provisioned PV (default fs)] volumeIO should write files of various sizes, verify size, validate content [Slow]
 * [sig-storage] In-tree Volumes [Driver: gluster] [Testpattern: Inline-volume (default fs)] subPath should fail if subpath file is outside the volume [Slow]
 * [sig-storage] In-tree Volumes [Driver: gluster] [Testpattern: Pre-provisioned PV (default fs)] subPath should support existing directory
 * [sig-storage] In-tree Volumes [Driver: gluster] [Testpattern: Inline-volume (default fs)] volumeIO should write files of various sizes, verify size, validate content [Slow]
 * [sig-storage] In-tree Volumes [Driver: hostPathSymlink] [Testpattern: Inline-volume (default fs)] subPath should support existing directory
 * [sig-storage] In-tree Volumes [Driver: hostPathSymlink] [Testpattern: Inline-volume (default fs)] subPath should fail if subpath with backstepping is outside the volume [Slow]
 * [sig-storage] In-tree Volumes [Driver: emptydir] [Testpattern: Inline-volume (default fs)] subPath should support creating multiple subpath from same volumes [Slow]

**3. CSI Volumes subpath issues - "subpath should fail" flake Tracked by https://github.com/kubernetes/kubernetes/issues/71383**
 * [sig-storage] CSI Volumes [Driver: csi-hostpath-v0] [Testpattern: Dynamic PV (default fs)] subPath should fail if subpath file is outside the volume [Slow]
 * [sig-storage] CSI Volumes [Driver: csi-hostpath-v0] [Testpattern: Dynamic PV (default fs)] subPath should fail if subpath with backstepping is outside the volume [Slow]
 * [sig-storage] CSI Volumes [Driver: csi-hostpath] [Testpattern: Dynamic PV (default fs)] subPath should fail if non-existent subpath is outside the volume [Slow]
 * [sig-storage] CSI Volumes [Driver: csi-hostpath] [Testpattern: Dynamic PV (default fs)] subPath should fail if subpath file is outside the volume [Slow]
 * [sig-storage] CSI Volumes [Driver: csi-hostpath] [Testpattern: Dynamic PV (default fs)] subPath should fail if subpath directory is outside the volume [Slow]
 * [sig-storage] CSI Volumes [Driver: csi-hostpath-v0] [Testpattern: Dynamic PV (default fs)] subPath should fail if non-existent subpath is outside the volume [Slow]
 * [sig-storage] CSI Volumes [Driver: csi-hostpath-v0] [Testpattern: Dynamic PV (default fs)] subPath should fail if subpath directory is outside the volume [Slow]
 * [sig-storage] CSI Volumes [Driver: csi-hostpath] [Testpattern: Dynamic PV (default fs)] subPath should fail if subpath with backstepping is outside the volume [Slow]
 * [sig-storage] CSI Volumes [Driver: csi-hostpath-v0] [Testpattern: Dynamic PV (default fs)] subPath should unmount if pod is gracefully deleted while kubelet is down [Disruptive][Slow]
 * [sig-storage] CSI Volumes [Driver: pd.csi.storage.gke.io][Serial] [Testpattern: Dynamic PV (default fs)] subPath should support existing directory
 * [sig-storage] [Serial] CSI Volumes CSI plugin test using CSI driver: hostPath [Serial] should provision storage

**4. Misc failure**
* [sig-storage] Detaching volumes should not work when mount is in progress - Tracked by https://github.com/kubernetes/kubernetes/issues/71426
* [sig-storage] Projected secret should be consumable from pods in volume as non-root with defaultMode and fsGroup set [NodeConformance] [Conformance]
* [sig-storage] EmptyDir volumes when FSGroup is specified [NodeFeature:FSGroup] new files should be created with FSGroup ownership when container is root
* [sig-storage] Mounted flexvolume expand[Slow] Should verify mounted flex volumes can be resized
* [sig-storage] [Serial] Volume metrics should create prometheus metrics for volume provisioning and attach/detach
* [sig-storage] [Serial] Volume metrics PVController should create bound pv/pvc count metrics for pvc controller after creating both pv and pvc
* [sig-storage] GenericPersistentVolume[Disruptive] When kubelet restarts Should test that a volume mounted to a pod that is deleted while the kubelet is down unmounts when the kubelet returns.
* [sig-storage] EmptyDir volumes volume on default medium should have the correct mode [NodeConformance] [Conformance]

**Comment by msau42** [comment]
I don't have permission to edit your comment, but:
* [sig-storage] In-tree Volumes [Driver: gluster] [Testpattern: Inline-volume (default fs)] volumeIO should write files of various sizes, verify size, validate content [Slow] - Tracked by #64047

Also these CSI flakes are not covered by #71383:
* [sig-storage] CSI Volumes [Driver: csi-hostpath-v0] [Testpattern: Dynamic PV (default fs)] subPath should unmount if pod is gracefully deleted while kubelet is down [Disruptive][Slow]
* [sig-storage] CSI Volumes [Driver: pd.csi.storage.gke.io][Serial] [Testpattern: Dynamic PV (default fs)] subPath should support existing directory
* [sig-storage] [Serial] CSI Volumes CSI plugin test using CSI driver: hostPath [Serial] should provision storage

The remaining tests do not have any open issues that I'm aware of.  It would be good to sort the remaining by frequency to prioritize triage

**Comment by jberkus** [comment]
Let me see how many disappear after the subpath merge, and then I can sort the rest by frequency.

**Comment by AishSundar** [comment]
@saad-ali @msau42 @jberkus  I did a quick pass of all the above failures in triage to see which ones are new in 1.13 timeframe (i.e., post 10/01/2018) and beloq is the list (minus the CSI subpath and Detaach volume issues being fixed). I tried to order them by frequency, but all of these are pretty infrequent and seem to be passing now. still worth investigating to see if they should block 1.13

* [[sig-storage] In-tree Volumes [Driver: gcepd] [Testpattern: Inline-volume (default fs)] volumes should be mountable](https://storage.googleapis.com/k8s-gubernator/triage/index.html?date=2018-11-01&sig=network,storage&test=volumes%20should%20be%20mountable#71c48180c1af06ef324d)
  * Started around 10/19
  * https://k8s-testgrid.appspot.com/sig-release-master-blocking#gce-cos-master-default 

* [[sig-storage] CSI Volumes [Driver: csi-hostpath-v0] [Testpattern: Dynamic PV (default fs)] subPath should unmount if pod is gracefully deleted while kubelet is down [Disruptive][Slow]](https://storage.googleapis.com/k8s-gubernator/triage/index.html?date=2018-11-26&sig=network,storage&test=CSI%5C%20Volumes%5C%20%5C%5BDriver%3A%5C%20csi%5C-hostpath%5C-v0%5C%5D%5C%20%5C%5BTestpattern%3A%5C%20Dynamic%5C%20PV%5C%20%5C(default%5C%20fs%5C)%5C%5D%5C%20subPath%5C%20should%5C%20unmount%5C%20if%5C%20pod%5C%20is%5C%20gracefully%5C%20deleted%5C%20while%5C%20kubelet%5C%20is%5C%20down)
  * New since 11/26
  * Just 1 occurrence thus far
  * https://k8s-testgrid.appspot.com/sig-release-master-blocking#gce-cos-master-serial

* [[sig-storage] CSI Volumes [Driver: pd.csi.storage.gke.io][Serial] [Testpattern: Dynamic PV (default fs)] subPath should support existing directory](https://storage.googleapis.com/k8s-gubernator/triage/index.html?date=2018-11-26&sig=network,storage&test=subPath%20should%20support%20existing%20directory#0212d5e426125e519b8b)
  * New since 11/21
  * Infrequent, hasn't happened in a while now.
  * https://k8s-testgrid.appspot.com/sig-release-master-blocking#gce-cos-master-serial

* [[sig-storage] Mounted flexvolume expand[Slow] Should verify mounted flex volumes can be resized](https://storage.googleapis.com/k8s-gubernator/triage/index.html?date=2018-11-15&sig=network,storage&test=Mounted%20flexvolume%20expand)
  * Started since 11/15 
  * https://k8s-testgrid.appspot.com/sig-release-master-blocking#gce-cos-master-slow

* [[sig-storage] In-tree Volumes [Driver: emptydir] [Testpattern: Inline-volume (default fs)] subPath should support creating multiple subpath from same volumes [Slow]](https://storage.googleapis.com/k8s-gubernator/triage/index.html?date=2018-11-01&sig=network,storage&test=subpath%20should%20support%20creating%20multiple%20subpath%20from%20same%20volumes#af21b40a04632bd60184)
  * Seems newer since 11/1
  * Infrequent
  * Though we had similar failures for different driver (nfs) since 1.12
  * https://k8s-testgrid.appspot.com/sig-release-master-blocking#gce-cos-master-slow

* [[sig-storage] In-tree Volumes [Driver: gluster] [Testpattern: Inline-volume (default fs)] subPath should fail if subpath file is outside the volume [Slow]](https://storage.googleapis.com/k8s-gubernator/triage/index.html?sig=network,storage&test=subPath%20should%20fail%20if%20subpath%20file%20is%20outside%20the%20volume)
  * Seemed to happen before but infrequently. Seeing new error traces now
  * https://k8s-testgrid.appspot.com/sig-release-master-blocking#gce-cos-master-slow

* [[sig-storage] In-tree Volumes [Driver: hostPathSymlink] [Testpattern: Inline-volume (default fs)] subPath should fail if subpath with backstepping is outside the volume [Slow]](https://storage.googleapis.com/k8s-gubernator/triage/index.html?sig=network,storage&test=subPath%20should%20fail%20if%20subpath%20with%20backstepping%20is%20outside%20the%20volume#719e67ed67ffe8253cc4)
  * Seemed to happen before but infrequently. Seeing new error traces now
  * https://k8s-testgrid.appspot.com/sig-release-master-blocking#gce-cos-master-slow

* [[sig-storage] Projected secret should be consumable from pods in volume as non-root with defaultMode and fsGroup set [NodeConformance] [Conformance]](https://storage.googleapis.com/k8s-gubernator/triage/index.html?date=2018-10-15&sig=network,storage&test=Projected%20secret%20should%20be%20consumable%20from%20pods%20in%20volume%20as%20non-root%20with%20defaultMode%20and%20fsGroup%20set)
  * Started since 10/12
  * Very infrequent
  * https://k8s-testgrid.appspot.com/sig-release-master-blocking#gce-cos-master-default

**Comment by msau42** [comment]
Flexvolume expand is new for 1.13. cc @gnufied 

For 1.13, I would focus on triaging the two CSI volumes failures you mentioned above.  @davidz627 can help look at the PD driver failure.  I will look at the hostpath csi test failure.

We did a big test refactoring around the end of 1.12 and beginning of 1.13 that may have drastically changed the test case names and line numbers of failures, which could be contributing to some of the "in-tree volumes" tests showing up as new for 1.13, but not actually being new.  @mkimuram can you help triage some of the in-tree volume subpath flakes?

**Comment by AishSundar** [comment]
@jberkus @mariantalla @mortent can we please separate flaky test issues for each of the failing tests above and add them to 1.13 milestone for initial triage? thanks.

**Comment by msau42** [comment]
Opened https://github.com/kubernetes/kubernetes/issues/71473 for `[sig-storage] CSI Volumes [Driver: csi-hostpath-v0] [Testpattern: Dynamic PV (default fs)] subPath should unmount if pod is gracefully deleted while kubelet is down [Disruptive][Slow]`.

**Comment by msau42** [comment]
Opened https://github.com/kubernetes/kubernetes/issues/71476 for `[sig-storage] In-tree Volumes [Driver: gcepd] [Testpattern: Inline-volume (default fs)] volumes should be mountable`

**Comment by saad-ali** [comment]
Thanks @davidz627 and @msau42.


@AishSundar:

> * [sig-storage] CSI Volumes [Driver: pd.csi.storage.gke.io][Serial] [Testpattern: Dynamic PV (default fs)] subPath should support existing directory
> 
>   * New since 11/21
>   * Infrequent, hasn't happened in a while now.
>   * https://k8s-testgrid.appspot.com/sig-release-master-blocking#gce-cos-master-serial

Based on David's analysis this^^^ `pd.csi.storage.gke.io` flake is not a blocker for 1.13.

> * [[sig-storage] CSI Volumes [Driver: csi-hostpath-v0] [Testpattern: Dynamic PV (default fs)] subPath should unmount if pod is gracefully deleted while kubelet is down [Disruptive][Slow]](https://storage.googleapis.com/k8s-gubernator/triage/index.html?date=2018-11-26&sig=network,storage&test=CSI%5C%20Volumes%5C%20%5C%5BDriver%3A%5C%20csi%5C-hostpath%5C-v0%5C%5D%5C%20%5C%5BTestpattern%3A%5C%20Dynamic%5C%20PV%5C%20%5C(default%5C%20fs%5C)%5C%5D%5C%20subPath%5C%20should%5C%20unmount%5C%20if%5C%20pod%5C%20is%5C%20gracefully%5C%20deleted%5C%20while%5C%20kubelet%5C%20is%5C%20down)
>    * New since 11/26
>    * Just 1 occurrence thus far
>    * https://k8s-testgrid.appspot.com/sig-release-master-blocking#gce-cos-master-serial

And based on @msau42's analysis the root cause of this^^^ `csi-hostpath-v0` flake is not sig-storage related (and is a known issue for many months).

**Comment by gnufied** [comment]
I investigated flexvolume expansion issue. More detailed comment is here - https://github.com/kubernetes/kubernetes/issues/71470#issuecomment-442248513 but basically this failure should not be a release blocker. It is not a regression but in worst case will cause addition of an extra condition to the PVC. I am working on a fix but we can get this in for 1.13.1 as well.

**Comment by AishSundar** [comment]
@davidz627 @saad-ali here's the triage link for the ```[sig-storage] CSI Volumes [Driver: pd.csi.storage.gke.io][Serial] [Testpattern: Dynamic PV (default fs)] subPath should support existing directory``` specifically in release blocking jobs

https://storage.googleapis.com/k8s-gubernator/triage/index.html?sig=network,storage&job=ci-kubernetes-e2e-gce-new-master-upgrade-cluster-new&test=subPath%20should%20fail%20if%20subpath%20file%20is%20outside%20the%20volume

I do see it happens more frequently than once in past 14 days. Can we please triage these failures?

**Comment by AishSundar** [comment]
Ah this is so confusing. So many different cases with different drivers :)

**Comment by msau42** [comment]
I encountered another flake today: https://github.com/kubernetes/kubernetes/issues/71578

**Comment by mariantalla** [comment]
Still relevant (wish it wasn't)
/remove-lifecycle stale
