### ISSUE TITLE
Can't get resource object（deployment、namespaces、configmap）  from kube-apiserver

### ISSUE THREAD

**Issue by GitHubxsy** [kubernetes/kubernetes#71454]
**What happened**:
Can't get resource object（deployment、namespaces、configmap）  from kube-apiserver，but can get configmap and other resource object。

> I1126 22:24:17.822162      18 wrap.go:42] GET /api/v1/endpoints?limit=500&resourceVersion=0: (504.009µs) 429 [[kube-proxy/v2.11.19 (linux/amd64) kubernetes/1e57adb] 192.255.189.109:52472]
> I1126 22:24:17.822744      18 wrap.go:42] GET /api/v1/services?limit=500&resourceVersion=0: (445.541µs) 429 [[kube-proxy/v2.11.19 (linux/amd64) kubernetes/1e57adb] 192.255.189.109:52472]
> I1126 22:24:17.840712      18 wrap.go:42] GET /api/v1/namespaces/fst-manage/pods/ingressproxy-ber-29rjd: (4.433369ms) 200 

**What you expected to happen**:
get all resource object from kube-apiserver。
**How to reproduce it (as minimally and precisely as possible)**:
Low probability，maybe happen after etcd server change leader.

**Anything else we need to know?**:
Restart kube-apiserver can be restored
**Environment**:
- Kubernetes version (use `kubectl version`): K8S 1.9.10 

/kind bug

**Comment by liggitt** [comment]
that response occurs when the apiserver is overwhelmed with requests. that can occur because of a hot-looping client, or because the apiserver's `--max-requests-inflight` is not set high enough for the amount of traffic you expect. larger servers should set that higher than the default, after testing to ensure they have sufficient capacity to serve higher numbers of requests

/close
