### ISSUE TITLE
Document or remove KUBERNETES_CONFORMANCE_PROVIDER

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/kubernetes#71579]
It's unclear to me why the env var `KUBERNETES_CONFORMANCE_PROVIDER` is necessary.  We should either document why it exists and when it is needed, or eliminate it.  My hope or current understanding is that `KUBERNETES_PROVIDER` should be sufficient

Brought to my attention in https://github.com/kubernetes/test-infra/pull/10250

/area conformance
/priority important-longterm
/kind cleanup

**Comment by dims** [comment]
we may have to ping @zmerlynn as he has a TODO :) `TODO(zmerlynn): This is gross.`

https://github.com/kubernetes/test-infra/blob/master/kubetest/gke.go#L210-L220

**Comment by soggiest** [comment]
Hello!
1.14 code freeze is coming in about 3 days, will this be implemented in the following week?

**Comment by spiffxp** [comment]
/milestone clear
This won't be happening

**Comment by oomichi** [comment]
Some NOTE here:
- "eks" is set as KUBERNETES_CONFORMANCE_PROVIDER in k/test-infra
- "gke" is set ..
- "aws" is set ..
- "azure" is set as KUBERNETES_CONFORMANCE_PROVIDER in k/cloud-provider-azure
- "skeleton" is used if  KUBERNETES_CONFORMANCE_PROVIDER is not set in k/k
- KUBERNETES_CONFORMANCE_PROVIDER was introduced since https://github.com/kubernetes/kubernetes/pull/36005 for making cloud provider configuable on e2e tests from static "skeleton"

According to https://github.com/kubernetes/kubernetes/issues/74432 conformance tests should not depend on cloud providers. So I feel the original static "skeleton" seems valid for conformance tests to avoid unexpected test skipping.
