### ISSUE TITLE
detach-keys support

### ISSUE THREAD

**Issue by axot** [kubernetes/kubernetes#71765]
By default docker use ctrl-p as detach-keys which caused ctrl-p(previous-history) not work.
If it is possible to add detach-keys option will be great.

/kind feature

**Comment by Shnatsel** [comment]
@axot could you clarify whether this applies to Docker in general or to Kubernetes specifically?

If it's a generic Docker issue, it should be filed on the Docker bug tracker, since there is nothing we can do in Kubernetes to fix it. If it's an issue specific to Kubernetes, could you provide a step-by-step example of reproducing the issue?

Thanks!

**Comment by Shnatsel** [comment]
@kubernetes/sig-cli-feature-requests

**Comment by arbach** [comment]
Any update on this ?

**Comment by schellj** [comment]
This feature would be useful for me as well as I make use of `kubectl exec` and `kubectl attach` and it's quite annoying that `Ctrl-p` doesn't behave as it does in other terminals and the Docker detach-keys workaround isn't available.

**Comment by TeCHiScy** [comment]
Really need this feature, any collaborator can mark it as open?

**Comment by Hughen** [comment]
Is there any progress?
Custom `detach-keys` are very meaningful.

**Comment by kcburge** [comment]
Please reopen.

**Comment by saltbo** [comment]
Please reopen.

**Comment by schellj** [comment]
Please reopen.

**Comment by oshadmon** [comment]
This looks like a duplicate of [79110](https://github.com/kubernetes/kubernetes/issues/79110) - given that the feature is still not there, would also appreciate reopening the issue.

Thanks!

`/reopen`

**Comment by SerikDM** [comment]
`/reopen`
please
