### ISSUE TITLE
How to control the access to certain Nodeport from external via iptables

### ISSUE THREAD

**Issue by Cherishty** [kubernetes/kubernetes#71810]
We have a lot of services set up by Nodeport and available from external via `<node_ip>:<node_port>`  .

It should be a common requirement that I would like to control the access to certain services, which means the requests from some of IPs may access to it, while others not.

We'd like to use `iptables` to meet this requirement, which gets a lot of **confusion** since kubernetes use it to setup communication as well. 
Do we have any high-level `guidance` to design/create iptable rule to control k8s service?

Specifically, I am confused in below area
1.  which table should I append rules into ?  I find that lots of rules in `nat and filter` are created by k8s
2.  if I what to disable the access of service from one external ip to certain node, such as 
`telnet <node_ip>:<node_port>`
should I REJECT on `FORWARD` or `INPUT`, or `PREROUTING`  directly ?
3. does these rule depend on specific network plugins (eg flannel or weave) ? Whether different plugins have different way to config rule or not?

For my senarios, I have below rules to be set up:

1. all nodes in cluster should have `full access `to each other
2. some core services (API) should only be **ACCEPT** by `certain` IPs
3.  certain services in a port range can be **ACCEPT** by `all` IPs
4. **REJECT** the access to `any other` services from all IPs (outside of cluster)

k8s version: 1.9.5
network plugin: weave

Best Regards!

/triage support

**Comment by thockin** [comment]
I think there's no way to specify allowable source ranges on a NodePort because the `nat` table happens before the `filter` table, so `filter` never sees the node port per se.

We have `loadBalancerSourceRanges` but that only applies to `type: LoadBalancer`.

The assumption here is that firewalling happens BEFORE it hits the node or else that you are using something like `NetworkPolicy` to control access to pods.

I could MAYBE see an argument for extending `loadBalancerSourceRanges` but I *think* (would have to dig and think hard to be sure) that NetworkPolicy almost wholly obviates that.
