### ISSUE TITLE
api_servers, master and server

### ISSUE THREAD

**Issue by mattf** [kubernetes/kubernetes#7181]
there are 3 ways to provide connectivity to the kubernetes api service.
- --master=string :: used by the proxy, scheduler, controller-manager
- --api_servers=list :: used by the kubelet
- --server=string :: used by the kubectl cli

there are two inconsistencies here,
1. the way to pass the information in varies across services and cli
2. the semantics are different (string - the contact, list - a contact)

my proposal is that these differences be simplified to a single --master=list used by all processes and the cli. this will consolidate the naming as well as provide connectivity for a scale-out api service.

i hope at least the name consolidation is uncontroversial.

i'm looking for some agreement on this direction before submitting any changes.

**Comment by roberthbailey** [comment]
I've been wanting to change the kubelet to use --master so I'd be thrilled if you did it for me. :)

**Comment by bgrant0607** [comment]
Consistency would be great.

Keep in mind:
1. The "master" is generally what we call the full collection of cluster-level control-plane components.
2. We're going to replicate apiserver for HA in the very near future.
3. We've previously discussed using dashes in all flags rather than underscores, but right now this is totally inconsistent. It would be better to avoid that issue entire.
4. We can't remove the existing flags for some time, since it would break all Kubernetes turnup code and instructions.

cc @eparis @timothysc

**Comment by bgrant0607** [comment]
See also #2967

**Comment by kargakis** [comment]
@kubernetes/sig-cli-misc

**Comment by euank** [comment]
As of 1.8, the `--api-servers` flag was removed from the kubelet.

Since flags are on the way out in favor of componentconfig/configmaps (e.g. https://github.com/kubernetes/kubernetes/issues/19831 and https://github.com/kubernetes/kubernetes/pull/29459), I think we can actually consider this issue largely a moot point now.

Given the work to move away from flags is underway, I think we can close this issue.

/close
