### ISSUE TITLE
When a PVC is provisioned with delayed binding, it never recovers from a failed provision

### ISSUE THREAD

**Issue by verult** [kubernetes/kubernetes#71928]
**What happened**: If a PVC with delayed binding fails to provision (for example due to a StorageClass parameter error), even when the error is fixed later on, provisioning never succeeds.

**What you expected to happen**: After the error is fixed, provisioning should retry and succeed.

**How to reproduce it (as minimally and precisely as possible)**:
- Create a StorageClass with VolumeBindingMode = WaitForFirstConsumer, and set some garbage parameters to eventually cause provisioning to fail.
- Create a PVC using the StorageClass
- Create a pod that consumes the PVC. Provisioning should fail
- Recreate the StorageClass with parameters removed.
Under correct operation, the provisioner should successfully retry and create a PV, and the pod should proceed to start. But this is not the case.

**Anything else we need to know?**:
When the PVC first fails to provision, the consumer pod has the following events:
```
  Type     Reason            Age                From               Message
  ----     ------            ----               ----               -------
  Warning  FailedScheduling  37s                default-scheduler  selectedNode annotation value "" not set to scheduled node "[node]"
  Warning  FailedScheduling  37s                default-scheduler  pod has unbound immediate PersistentVolumeClaims (repeated 2 times)
  Warning  FailedScheduling  37s                default-scheduler  AssumePod failed: pod 8e98377a-fcd7-11e8-beb7-42010a800002 is in the cache, so can't be assumed
  Warning  FailedScheduling  0s (x18 over 37s)  default-scheduler  pod has unbound immediate PersistentVolumeClaims (repeated 3 times)
```

after the error is fixed, the last event (unbound immediate PVCs) keeps firing.

For some reason the scheduler doesn't think the PVC uses delayed binding:
https://github.com/kubernetes/kubernetes/blob/67bc6d2083d94b38e5c8b249fe91aeafa1a0af19/pkg/controller/volume/persistentvolume/scheduler_binder.go#L504

One possible cause is somehow the scheduler thinks the selectedNode annotation still exists in the PVCCache (the provisioner removed the annotation after provisioning failure):
https://github.com/kubernetes/kubernetes/blob/67bc6d2083d94b38e5c8b249fe91aeafa1a0af19/pkg/controller/volume/persistentvolume/pv_controller.go#L297
Or the scheduler failed to get the StorageClass. I'm not sure atm why either could happen.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.12.3, 1.13
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/sig storage
/cc @msau42 

/kind bug

**Comment by msau42** [comment]
cc @cofyc

**Comment by verult** [comment]
Once the scheduler fails to schedule a pod, the pod goes back into the scheduler queue to be retried, right? Then during the next attempt, the scheduler assumes the pod's volumes again, which sets the annotation in the AssumeCache, and then propagates to the API through `bindVolumes()`.

But the annotation is missing. Looking at the controller manager logs, the log message indicating the annotation was removed (`failed to provision volume for claim %q with StorageClass %q: %v`) is absent later on. Maybe somehow the annotation was never propagated to the API after the first removal?

**Comment by verult** [comment]
I see this behavior in 1.12.3 as well.

**Comment by cofyc** [comment]
hi, @verult

Do you has this issue with internal or external provisioner?

I reproduced this issue with external provisioner (`csi-hostpath`) and find external provisioning has issue you described.

Currently, there are two dynamic provisioning paths:

- internal

PV controller call in-tree plugin `Provision` method to provision, if failed, it remove `annSelectedNode` to signal back to the scheduler to retry dynamic provisioning (see `PersistentVolumeController.rescheduleProvisioning`).

- external

For external provisioning, `annSelectedNode` will not be removed on failure, `PersistentVolumeController.shouldDelayBinding` will think it do not need to do delay binding now. Even after scheduler bind timeout (default: 600s). This annotation still exists. So, scheduler will enter into loop with "pod has unbound immediate PersistentVolumeClaims" error forever.

Note that, in practice, scheduler may add pod into queue to schedule again even if pod is in bind phase, xref #72013. So error may appear before bind timeout.

External provisioner may retry provisioning again and succeed because storage class is fixed, pod is going to work. But this depends on external provisioner next retry time.

I'm not sure how to fix or improve for now, but did some investigations here: https://github.com/kubernetes/kubernetes/issues/72031

If you have issue with internal provisioner, then this is not the case.

**Comment by verult** [comment]
I was actually using an internal provisioner (kubernetes.io/gce-pd). The PVC object doesn't have the annotation after provisioning fails, but the pod still reports the "unbound immediate volumes" error even after the StorageClass is fixed.

**Comment by cofyc** [comment]
Thanks! I'm going to test with internal provisioner (kubernetes.io/gce-pd).

**Comment by cofyc** [comment]
I reproduced this issue. This is because assumed PVC cached may not be cleared.

Current work flow of scheduler (v1.13.0):

- 1) schedule pod and volumes
- 2) assume volumes
- 3) assume pod
- 4) bind volumes
- 5) bind pod

If volumes are assumed,  but failed to assume pod, assumed volumes will not be cleared. Then, scheduler will fall into an infinite loop with "pod has unbound immediate PersistentVolumeClaims" error.

```
Warning  FailedScheduling  37s                default-scheduler  AssumePod failed: pod 8e98377a-fcd7-11e8-beb7-42010a800002 is in the cache, so can't be assumed
```

This is event reported by scheduler when it failed to assume pod. Why this may happen is because scheduler may schedule a pod while it is in the bind phase in the meantime, xref https://github.com/kubernetes/kubernetes/issues/72013.

For correctness, we must revert assumed pod volumes if failed to assume pod. If there is another instance pod is in bind phrase, it may fail because assumed cache changed. But after retrying, it will succeed eventually.

**Comment by cofyc** [comment]
Created a PR to fix this: https://github.com/kubernetes/kubernetes/pull/72045

**Comment by rohith-vallabhaneni** [comment]
I ran into the same issue, I scheduled deployments using rancher UI and then I saw the same issue, then I realised that the EBS volumes were created in different availability zones, the issue is resolved by creating a new storageclass with only one availability zone in parameters.

**Comment by jingxu97** [comment]
cc @msau42 @cofyc

**Comment by cofyc** [comment]
@rohith-vallabhaneni What's your k8s version?
