### ISSUE TITLE
Support OCI images in API

### ISSUE THREAD

**Issue by vmarmol** [kubernetes/kubernetes#7203]
Today the API assumes Docker images, but we'd like to be able to support other images in the future. This issue specifically targets the [ACI](https://github.com/appc/spec/blob/master/SPEC.md#app-container-image) standard (which is used by [Rkt](https://github.com/coreos/rkt))

Arguably having the flexibility to have a different image type in the API is for v1.0, although actually supporting a different image type is not.

/cc @dchen1107 @bgrant0607 @yifan-gu @jonboulle

**Comment by thockin** [comment]
We have to decide whether the API should reflect the choice of runtime at
all.  Ideally the API is agnostic to all that.  Container image is just a
string that we pass down.  I'm not sure we can do that, though.  I really
dislike the idea of the end user having to change their behavior based on
the admin's choice of runtime.

It's a kubernetic ideal that the dame pod spec should run on a docker
cluster and on a rocket cluster.

**Comment by bgrant0607** [comment]
Other example runtimes / formats:
* Fabric8 Java
* LXC + some image format (targz?)
* Google internal
* Non-Linux platforms: BSD, Solaris, Windows, ...

Eventually we'll need some kind of plugin API in the pod spec. 

Ideally, when running in a cloud, the system would eventually be able to instantiate VMs capable of running whatever image/spec was provided, as necessary.

I agree that differences in semantics should not be implicit based on implementation choices, and the pod spec should not need to be changed in the case that the same semantics are desired on different runtimes.

**Comment by thockin** [comment]
By way of example, I would be very against a solution that required

`image: nginx`

on docker runtimes but required

`image: docker://nginx`

 on rkt

**Comment by bgrant0607** [comment]
Agree, though requiring a prefix for all images would be a breaking change. We could do that in v1 and add a format field in the older APIs.

However, with respect to images, there are multiple issues:
* name/address format
* data format
* image identity, both mutable (tags) and immutable (content-based id)
* location to fetch from

I haven't had time to think about which we want to explicitly represent. In enterprise environments, admins generally want control over the latter 2.

**Comment by vmarmol** [comment]
In the short term, ACI-based images do natively support Docker images so no changes would need to be made to express Docker images. For others we would have to identify and know where to schedule them. Initially it'd be an explicit choice on the user's part I imagine.

If we did have to schedule only on nodes that supported format X, parsing the image string is probably not the best way.

**Comment by jonboulle** [comment]
@vmarmol:
> ACI-based images do natively support Docker images

"ACI-based images" -> "ACI-based runtimes"? Even so, not strictly correct; rkt natively supports Docker images (by transparently converting them to ACIs using docker2aci), but this isn't a provision of the spec (i.e. other implementations might not have this support).

**Comment by jonboulle** [comment]
A little more detail on the ACI side: 

It is definitely a different beast to Docker in that there's no shorthand way to deterministically [1] reference remote images (in part since there's no registry API). Instead, the appc spec currently defines [two processes (strategies) for discovering image locations](https://github.com/appc/spec/blob/master/SPEC.md#app-container-image-discovery) [2], where "location" is an HTTP endpoint, torrent, HDFS URI, etc; but these strategies are not _necessarily_ deterministic, depending on their implementation (essentially this is the "mutable" identity bgrant0607 refers to above). The only canonical image reference is instead the [image ID](https://github.com/appc/spec/blob/master/SPEC.md#image-id) (the immutable, content-based identity).

Taking rkt as an example again, it currently supports three image reference types:
a) a discovery reference
b) a direct URI (either HTTP/S or a file on local disk)
c) an image ID (at the moment this must be already locally cached in rkt's CAS, but you can imagine an implementation where it is available in a well-known remote CAS as well)

[1] For _some_ definition of deterministic; obviously Docker repositories can still be mutated behind the scenes. But there is a general assumption in the ecosystem today that "nginx:14.04" or "foo.com/bar:baz" refer to a consistent image over time. (I know Docker have just added content-based tags to provide this)
[2] Two ordered processes, but soon to be reframed as a [pluggable set of strategies](https://github.com/appc/spec/issues/140)

**Comment by philips** [comment]
I think where we need to end up on this is having the API be very explicit about the users intended image. This is something like how the volume API is explicit about the type of volume and its arguments:

```
  manifest:
    containers:
      - image: kubernetes/pause
        name: testpd
        volumeMounts:
          - mountPath: "/testpd"
            name: "testpd"
    id: testpd
    version: v1beta1
    volumes:
      - name: testpd
        source:
          persistentDisk:
            # This GCE PD must already exist.
            pdName: test
            fsType: ext4
```

So if we take this same approach and change the image we get something like:

```
  manifest:
    containers:
      - name: testpd
        image:
            docker:
                repository: kubernetes/pause
                tag: latest
                digest: sha256:cbbf2...
        volumeMounts:
          - mountPath: "/testpd"
            name: "testpd"
```

```
  manifest:
    containers:
      - name: testpd
        image:
            aci:
                name: kubernetes.io/pause
                labels:
                   version=2.0.9
                id: sha512-a83b3f...
        volumeMounts:
          - mountPath: "/testpd"
            name: "testpd"
```

Possible problems and points of research:

- [ ] Docker has other things like os and arch which need to be accounted for https://github.com/docker/docker/blob/master/image/spec/v1.md#image-json-field-descriptions
- [ ] appc has default labels for runtimes like arch and os, do we let those be implied?

**Comment by philips** [comment]
On @bgrant0607 point of letting the user control where things are fetched from this feels like a configuration problem that is orthogonal to this problem. If the user wants to configure their container runtime to fetch from an NFS share, local store, etc we need to have a cluster-wide or namespace wide API for this sort of thing.

**Comment by pmorie** [comment]
@philips Presumably there will be a validation to ensure that each container in a pod has the same image type, correct?

**Comment by philips** [comment]
@pmorie I don't know if there is a technical reason for this restriction; rkt, for example, can run both docker and ACI images in the same pod.

**Comment by pmorie** [comment]
@philips That is a really good point -- I guess if rocket is available there shouldn't be any problem with letting the rocket pod handle the docker image pull.  That said my gut says there may be some issues to work through -- for example making sure that rkt and docker can pull using the same secret.

**Comment by philips** [comment]
On Tue, Apr 28, 2015 at 1:30 PM, Paul Morie <notifications@github.com>
wrote:

> That said my gut says there may be some issues to work through -- for
> example making sure that rkt and docker can pull using the same secret


It should be easily possible:
https://github.com/coreos/rkt/blob/master/Documentation/configuration.md#configuration-kinds

I think @yifan-gu is hooking up the k8s secret auth configuration to this
rkt feature for docker registry auth.

Brandon

**Comment by pmorie** [comment]
@philips Yep, we've been communicating about that.

**Comment by bgrant0607** [comment]
@philips The fields you propose match the [ACI pod manifest schema](https://github.com/appc/spec/blob/master/SPEC.md#pod-manifest-schema)? What structure would you propose for Docker images?

**Comment by philips** [comment]
@bgrant0607 The first one is for docker images, here it is again:

```
  manifest:
    containers:
      - name: testpd
        image:
            docker:
                repository: kubernetes/pause
                tag: latest
                digest: sha256:cbbf2...
        volumeMounts:
          - mountPath: "/testpd"
            name: "testpd"
```

Based on the [docker image json](https://github.com/docker/docker/blob/master/image/spec/v1.md#image-json-description) and the new Docker 1.6 `namespace/repo:tag@digest` schema which I feel is getting us into a place where the string is too fancy and should be pulled out into separate sections.

**Comment by ncdc** [comment]
Note, the digest format for Docker 1.6 is `namespace/repo@digest` - `:tag` is not part of it when using a digest, and you can only specify either a tag or a digest, but not both.

**Comment by pmorie** [comment]
There is not a one-to-one mapping between container runtime and image pull.  Rocket supports running docker  images, and so it makes sense that you could run a pod that has a docker _image spec_ with a rocket _container runtime_ with no changes.  In the future, the ACI format might be [supported by docker](https://github.com/docker/docker/issues/10777), in which case the opposite would be possible: run a pod with an ACI image spec with the rkt container runtime.

**Comment by pmorie** [comment]
Let me offer the following api skeleton for discussion:

```go
type Container struct {
  // other fields omitted
  Image ImageSpec
}

type ImageSpec struct {
	DockerV1 *DockerV1RegistryImageSpec
    ACI      *ACISpec
    // FUTURE: other formats (fabric8, lxc, etc)
}
```

The image spec ought to be orthogonal from the container runtime.  That said, eventually I think the node should inform the cluster of which image specs it can support and the scheduler will have to ensure that pods get scheduled onto a node that supports the image format.

**Comment by thockin** [comment]
This is another place where a discriminated overlayed one-of type would
make a good API.  #6979

```json
    "image": {
        "kind": "aci",
        "name": "example.com/foobar-worker",
        "id": "afe264840302"
    }
```

vs

```json
    "image": {
        "kind": "docker",
        "name": "gcr.io/google_containers/foobar-worker:1.2"
    }
```

**Comment by philips** [comment]
I agree with @thockin's suggestion here.

**Comment by thockin** [comment]
Sadly, we do not have currently Go infrastructure for decoding JSON this
way, unless you guys have some tricks you want to share...  We have a
sketch of an idea of autogenerating unmarshalling code.  Nothing further.

**Comment by yifan-gu** [comment]
@thockin Doe RawMessage help ?

**Comment by philips** [comment]
@thockin We have manual marshaling code in the appc spec to do this stuff :( https://github.com/appc/spec/blob/master/schema/types/volume.go#L13

**Comment by thockin** [comment]
Manual.  Puke.

**Comment by bgrant0607** [comment]
2 things to keep in mind:
1. For performance reasons, we're almost certainly going to have to change our json parser #3338
2. We can't break [strategic merge patch](https://github.com/GoogleCloudPlatform/kubernetes/blob/f8569dc5d3c27db4d800cf07e6d5e64490955746/docs/api-conventions.md#strategic-merge-patch), which is needed for config reconciliation #1702

**Comment by bgrant0607** [comment]
And we want a strict parsing mode for validation purposes.

**Comment by bgrant0607** [comment]
I agree that discriminated inline unions look better when writing/reading them. When trying to understand the schema, such as during unmarshaling, they are pretty painful. They require data-dependent parsing that's not representable in Swagger AFAIK.  Embedded/inline OneOf isn't sufficient because one can't determine which case it is without understanding the correspondence between the value of the kind field and the selected OneOf struct.

**Comment by thockin** [comment]
Maybe not short term, but it seems bass-ackward to let the current tooling
dictate our API.

**Comment by bgrant0607** [comment]
Not worth the cost, IMO

**Comment by thockin** [comment]
For now. Expect to me to bother you about this for v2 API.

**Comment by bgrant0607** [comment]
Inline unions would also make it impossible to diff objects without the schema.

**Comment by bgrant0607** [comment]
The fact that we're using keyed lists rather than maps is already a big enough PITA. I'm reluctant to add more such quirks.

**Comment by bgrant0607** [comment]
If we did want discriminated inline unions, we should treat them exactly how we'd treat embedded plugin subobjects, with a kind and version.

**Comment by philips** [comment]
On Fri, May 8, 2015 at 7:47 PM, Brian Grant <notifications@github.com>
wrote:

> If we did want discriminated inline unions, we should treat them exactly
> how we'd treat embedded plugin subobjects, with a kind and version.
>

I am having a hard time finding what you mean by this, could you provide a
link?

**Comment by bgrant0607** [comment]
Mostly we've discussed making whole objects pluggable (#991, #3201, #1744, #703, ...), and have some code for that:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/runtime/scheme.go#L109

We've discussed that subobject plugins would be similar -- they would have a kind and apiVersion (and prefix, etc. if we added them).

**Comment by bakins** [comment]
What can we do to push this forward? Would like to get something in before 1.0. the `kind` field on the image seems reasonable if we can figure out the json piece.

**Comment by bgrant0607** [comment]
We're going to decide what's in/out of the v1 API in the next few days.

It doesn't look like we're going to have time to design/develop the plugin mechanism and move all the volume sources to it, so we needn't block on that mechanism for this, either.

We mainly need to decide whether OneOf is really necessary for the image format or not.

Once we support more diverse runtimes, such as Fabric8 or Windows, I could imagine more of the container spec, such as SecurityContext, would need to also be pluggable.

**Comment by yifan-gu** [comment]
I would vote for @philips 's scheme https://github.com/GoogleCloudPlatform/kubernetes/issues/7203#issuecomment-97186239

Pretty much like the `VolumeSource`, and then write the validation manually.

**Comment by bakins** [comment]
Any chance for the scheme like https://github.com/GoogleCloudPlatform/kubernetes/issues/7203#issuecomment-97186239 making it into v1 or is it more realistic to aim for v2?

**Comment by smarterclayton** [comment]
@thockin we are using kind: "DockerImage", name: full spec (no namespace) today as our object references, since we also have resources "ImageStreamTag" and "ImageStreamImage" that have names like "foo:bar" and "foo@bar" within namespaces.  I don't have a particular preference either way.

**Comment by philips** [comment]
I am fine with the kind thing. @thockin @bgrant0607 any final thoughts? Otherwise I will get a patch together.

**Comment by smarterclayton** [comment]
The Kind thing is infinitely flexible at the cost of not being discoverable.  The struct path is discoverable at the cost of being verbose and hard to extend.  Our use case was more natural for refs, so don't take my suggestion as necessarily being the right thing here.  We would want to reserve kinds for the type if we go down that path.  

----- Original Message -----

**Comment by bgrant0607** [comment]
Currently we have:
```
type Container struct {
   ...
   Image string
   ...
}
```
Image (Openshift only currently):
```
type Image struct {
	kapi.TypeMeta
	kapi.ObjectMeta
	DockerImageReference string
	DockerImageMetadata runtime.RawExtension
	DockerImageMetadataVersion string
	DockerImageManifest string
}
```
I could definitely imagine adding an Image API in the future. We have something analogous in Borg. We'd certainly want to refer to it by ObjectReference (or subset thereof, like LocalObjectReference). I think that pushes over the edge for a union (OneOf) of subobjects. 

We don't have API plugins yet, subobject or otherwise. That leaves the struct approach.

VolumeSource looks like:
```
	VolumeSource json:",inline"
...
type VolumeSource struct {
	HostPath *HostPathVolumeSource
	EmptyDir *EmptyDirVolumeSource
...
```

That suggests something like the following:
```
	Image json:",inline"
...
type Image struct {
	DockerImage *DockerImage
}
type DockerImage struct {
	Version string // v1/v2
	Name string // "repository" in v1 registry speak
	Tag string
}
```
So instead of:
```
spec:
  containers:
    - name: redis
      image: redis:latest
```
it would look like:
```
spec:
  containers:
    - name: redis
      dockerImage:
         name: redis
         tag: latest
```
More verbose, but not the end of the world. We're going to need generators to simplify config, anyway.

This change is complicated by the fact that image is a required field. We'll need to continue to pack everything into one string for pre-v1 APIs. After we nuke pre-v1 APIs we can think about adding new types of images.

**Comment by bakins** [comment]
I toyed with the code to implement something similar to https://github.com/GoogleCloudPlatform/kubernetes/issues/7203#issuecomment-104463241. It's not too complex, however, every example/test would need to change to match new structs.  I'd like to get this into v1, I suppose, worse case, we pack the "image kind" into the string and default to docker.

@philips and I are willing to produce a PR if we are open to getting this into v1.

**Comment by bgrant0607** [comment]
I'd appreciate your help @bakins.

I want it in v1, because changing it later will essentially break all API versions, similar to the label selector change. 

I suggest introducing the API and conversions for v1 first. api/types.go (internal rep) should match the v1 rep. The v1betaN reps should remain as is, so their conversions will need to unpack and re-pack the image string. We could put both representations in v1betaN, as we did for cpu and memory resources, but I don't think it's worth it.

**Comment by bgrant0607** [comment]
To be clear, I want the new API schema for Docker images in v1. ACI could then be added after we lift the freeze.

**Comment by yifan-gu** [comment]
> To be clear, I want the new API schema for Docker images in v1. ACI could then be added after we lift the freeze.

This sounds reasonable. Think we should open an issue for it and mark as a v1 milestone.

**Comment by kamalmarhubi** [comment]
@yifan-gu did this happen? It seems like v1 API doesn't include this change. I'm interested in non-Docker runtimes and images and am curious what the latest is here.

**Comment by yifan-gu** [comment]
@kamalmarhubi Not yet. But I believe we still want to make multiple image format happen.

**Comment by slallema** [comment]
I'm really happy to see rkt support in kubernetes but not being able to use ACIs is a real problem for me.
Right now I have compiled my own version of kubelet without the dockerPrefix "docker://" and it works perfectly with ACIs. So if we could find a way to have different kind of images in the api it would be great.

**Comment by runcom** [comment]
any movement on this one? is there a consensus to have a `kind` field to express which kind of image are we dealing with?

I'm asking because the Container Runtime Interface (https://github.com/kubernetes/kubernetes/issues/17048) just receives an anonymous `ImageSpec` which defaults to be a docker image - with docker image I'm saying _docker image reference `host[:port]/namespace/name[:tag|@digest]` + to be downloaded from a docker registry_.

But in https://github.com/containers/image, we developed a _Transport_ type which identifies an image and how it should be fetched/pushed. Currently we support:

* push/pull from/to Docker registries
* push/pull from/to the Atomic Registry in OpenShift
* _push_ to a local directory following the Opencontainers Image Layout spec
* _push_ layers and the manifest to a local directory 

It basically consists of a a `kind` prefix which identifies the kind of the image we're dealing with:

* `atomic:`
* `docker://`
* `oci:`
* `dir:`

Plus an URI like string which is reference dependent (i.e. docker follows its own, OCI and dir their own as well and they're just paths `dir:/local/path`).

I've been thinking it would be great to have a discriminant at least (`kind`) so any CRI implementors can decide if they support the given image kind and not just assume it's a Docker image.

/cc @philips @thockin et all

**Comment by philips** [comment]
@runcom step 1 is to get a proposal for the API change. There is an old proposal that could be used, see the feature for the old proposal link: https://github.com/kubernetes/features/issues/63

**Comment by Fak3** [comment]
any progress on this?

**Comment by dims** [comment]
long-term-issue (note to self)

**Comment by bgrant0607** [comment]
This is obsolete, but I'll leave a ref to #1697
/close
