### ISSUE TITLE
kubelet does not set kubepods/cpu.cfs_quota_us

### ISSUE THREAD

**Issue by namreg** [kubernetes/kubernetes#72050]
**What happened**:
I have ran kubelet with parameter:
 ```
--system-reserved=cpu=2.0,memory=1525Mi
```

cfs quota haven't changed:
```
 cat /sys/fs/cgroup/cpu/kubepods/cpu.cfs_quota_us
-1
```
**What you expected to happen**:
A value `kubepods/cpu.cfs_quota_us` is set to not -1
**How to reproduce it (as minimally and precisely as possible)**:
Run kubelet with parameter above
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
1.12.3
- Cloud provider or hardware configuration:
Virualbox
- OS (e.g. from /etc/os-release):
16.04.4 LTS (Xenial Xerus)
- Kernel (e.g. `uname -a`):
Linux P20B-VR3-R1-K8S-N1 4.14.35.4 #4 SMP Tue Dec 11 15:03:35 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:

/kind bug

**Comment by namreg** [comment]
@kubernetes/sig-node-bugs

**Comment by namreg** [comment]
@kubernetes/sig-node-bugs

**Comment by Joseph-Irving** [comment]
@namreg I think I've identified why this is happening, there's a mismatch between "system-reserved" and "SystemReserved" so the code that should do that is not being executed, I will raise a PR.

**Comment by Joseph-Irving** [comment]
So I did a bit more digging, turns out you also need to set `--enforce-node-allocatable=system-reserved` and set `--system-reserved-cgroup=foo` if you want the `--system-reserved` flag to be used.

It would probably be helpful if this was made clearer, however unless I'm missing something I don't think this is a bug.

**Comment by Nefelim4ag** [comment]
@Joseph-Irving, but why values like cpu.share and mem.limit set correctly?
Without flags mentioned by you above.

**Comment by Joseph-Irving** [comment]
Maybe I should rephrase to being enforced instead of used see https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node/node-allocatable.md for more details, 
`--system-reserved` is used when calculating cpu.shares and memory.limit. 
However I don't see anything in the code that would set cfs_quota_us using them. 
CFSQuota is set on individual pods when using limits but this is not written out to a file.
What are you expecting to be there and why?

**Comment by Nefelim4ag** [comment]
@Joseph-Irving,
```
By explicitly reserving compute resources, the intention is to avoid overcommiting the node and not have system daemons compete with user pods. The resources available to system daemons and user pods will be capped based on user specified reservations.
```
(That proposal just lucks of implementation detail (same for memory limit, cpu quota and share), because 
they very depends on runtime used by k8s.)

```
However I don't see anything in the code that would set cfs_quota_us using them.
```
Yep, thats exactly a problem. 

Let's me describe how I see that:

- Kubelet/CRT use:
  - cpu.cfs_quota for limit cpu usage.
  - cpu_share to try split resources between cgroups (i don't believe in cpu shares, quota works much more predictable)
  - use memory.limit_in_bytes for memory.

But ONLY in system reserved - they decide to use memory limit and cpu share, and just skip cfq_quota.
That at minimum counterintuitive.
If that works good enough, may be just drop cpu.cfs_quota_us from container limits? Because cgroups have cpu.shares and that must work?
**Not use cpu.cfs_quota is irracional and does not have a logic.**

We set system **reserved**, i.e. system must be capable to use that resources in any time without limits.

Okay, let’s get back to the meat.

I think what everybody sometimes use limit != requests, and on every cluster cpu have some grade of overprovisioning. As example i can have 100-200 cpu hungry pods on node. with over provisioned cpu to 200%. every process can have 1-100 threads.
i.e. from 100*1...200*100 cpu intensive tasks (only by k8s in node) based on phase of the moon,
(let's not count other threads)
(and yep, i have bare metal HPC cluster with not predictable workload over day,
so i need to do much things on my end, k8s not almighty).

In described case, such reservation of cpu are useless,
because in any time pods which has running on node can just use 100% of node cpu, that will lead to cpu starvation of system services, may be i run etcd or kube-apiserver on that node,
what will happens to them in such case?
(Or i can use vmware guest agent, and after some time of cpu starvation VM will be killed by hypervisor, great!)
Who knows how many problems can happen depends on end user env?

(Does it look funny? For me answer is yes)
So SystemReserved looks like a security theater.

Thanks.
- - -
(Like not working timeout in liveness exec check in docker runtime (really),
i.e. "yep, you can specify that you want, but that will change nothing, thank you for your cooperation!).

**Comment by Joseph-Irving** [comment]
@namreg yeah, what you said all sounds reasonable, I see you've opened a PR to change that which is great. 

However, it's definitely worth talking to sig-node about this as they will know a lot more about this than me. You can try reaching them via the sig-node slack channel.

**Comment by vishh** [comment]
One of original intentions was to allow burstable & best effort pods to use as much CPU as it can with the assumption that CPU shares enforcement by the kernel would prevent CPU starvation for system daemons as long as kube and/or system reservations are set appropriately. 
Are CPU share not being enforced as expected in certain environments?
As long as system-reserved, kube-reserved, and all k8s system pods (etcd, apiserver, kube-proxy, etc.) have reasonable CPU requests specified, I'd expect the kernel to prevent CPU starvation even in the presence of lots of compute bound workloads.

**Comment by Nefelim4ag** [comment]
@vishh,
you are right, i've tested cpu shares with cgroups and systemd drivers,
both works good
