### ISSUE TITLE
kubectl api-resources error

### ISSUE THREAD

**Issue by yangzhenyu900** [kubernetes/kubernetes#72051]
[webapp@k8s-master-01 ~]$ kubectl api-resources 
error: unable to retrieve the complete list of server APIs: custom.metrics.k8s.io/v1beta1: the server is currently unable to handle the request

**Comment by ahmadnurus** [comment]
please following [bug report](https://github.com/kubernetes/kubernetes/blob/master/.github/ISSUE_TEMPLATE/bug-report.md) issue template. it will help contributors to reproduce your issue

**Comment by mingfang** [comment]
This is a nasty problem on the server side.  
I get this when the metric server is down.

**Comment by surajnarwade** [comment]
@yangzhenyu900 , @mingfang , can you elaborate issue in this format https://github.com/kubernetes/kubernetes/blob/master/.github/ISSUE_TEMPLATE/bug-report.md ?

**Comment by mingfang** [comment]
confirm fixed in v1.14-beta.2
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.0-beta.2", GitCommit:"b1e389e6f7bd798a8dd162f82b918f509ac5291b", GitTreeState:"clean", BuildDate:"2019-03-12T18:10:45Z", GoVersion:"go1.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.0-beta.2", GitCommit:"b1e389e6f7bd798a8dd162f82b918f509ac5291b", GitTreeState:"clean", BuildDate:"2019-03-12T18:01:33Z", GoVersion:"go1.12", Compiler:"gc", Platform:"linux/amd64"}
```

```
kubectl api-resources
NAME                              SHORTNAMES   APIGROUP                       NAMESPACED   KIND
bindings                                                                      true         Binding
componentstatuses                 cs                                          false        ComponentStatus
configmaps                        cm                                          true         ConfigMap
<many more here/>
volumeattachments                              storage.k8s.io                 false        VolumeAttachment
error: unable to retrieve the complete list of server APIs: metrics.k8s.io/v1beta1: the server is currently unable to handle the request
```

**Comment by mcluseau** [comment]
If metrics-server is not wanted anymore, resolution is:
`kubectl delete apiservice v1beta1.metrics.k8s.io`

**Comment by weibeld** [comment]
I get the same error sometimes for the `custom.metrics.k8s.io/v1beta1` API after deleting and reinstalling the [Prometheus Adapter](https://github.com/DirectXMan12/k8s-prometheus-adapter) via the [Helm chart](https://github.com/helm/charts/tree/master/stable/prometheus-adapter):

The `helm install` command fails with the following error:

    Error: could not get apiVersions from Kubernetes: unable to retrieve the complete list of server APIs: custom.metrics.k8s.io/v1beta1: the server could not find the requested resource

The error occurs only sometimes and, strangely enough, after some time disappears on its own.

**Comment by gajus** [comment]
> I get the same error sometimes for the custom.metrics.k8s.io/v1beta1 API after deleting and reinstalling the Prometheus Adapter via the Helm chart:

Did you figure it out?

Same behaviour here.

**Comment by kenwoodjw** [comment]
I have the same issue  /reopen

**Comment by technosophos** [comment]
The solution we implemented in Helm was to trap that particular error and print a warning about the offending registration.

**Comment by Sanket110297** [comment]
**Solution:**

The steps I followed are:

1. `kubectl get apiservices` : If metric-server service is down with the error CrashLoopBackOff try to follow the step 2 otherwise just try to restart the metric-server service using `kubectl delete apiservice/"service_name"`. For me it was v1beta1.metrics.k8s.io .

2. `kubectl get pods -n kube-system` and found out that pods like metrics-server, kubernetes-dashboard are down because of the main coreDNS pod was down.

For me it was:

```
NAME                          READY   STATUS             RESTARTS   AGE
pod/coredns-85577b65b-zj2x2   0/1     CrashLoopBackOff   7          13m
```

3. Use kubectl describe pod/"pod_name" to check the error in coreDNS pod and if it is down because of /etc/coredns/Corefile:10 - Error during parsing: Unknown directive proxy, then we need to use forward instead of proxy in the yaml file where coreDNS config is there. Because CoreDNS version 1.5x used by the image does not support the proxy keyword anymore.

https://stackoverflow.com/questions/62442679/could-not-get-apiversions-from-kubernetes-unable-to-retrieve-the-complete-list
