### ISSUE TITLE
Regular expressions not working in json-path

### ISSUE THREAD

**Issue by hognala** [kubernetes/kubernetes#72220]
This is a duplicate of #61406, which was closed because it was stale (I couldn't reopen it)

**What happened**:
Trying to use the following json-path expression:
`kubectl get secrets -o jsonpath='{.items[?(@.metadata.name=~/^test$/)].metadata.name}'`
resulted in the following error:
`error: error parsing jsonpath {.items[?(@.metadata.name=~/^test$/)].metadata.name}, unrecognized character in action: U+007E '~'`

**What you expected to happen**:
Getting the list of secret names that match the regular expression.
**How to reproduce it (as minimally and precisely as possible)**:
`kubectl get secrets -o jsonpath='{.items[?(@.metadata.name=~/^default-/)]}'`
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.10.2
- Cloud provider or hardware configuration: Dell PC
- OS (e.g. from /etc/os-release):  Ubuntu 18.04.1 LTS
- Kernel (e.g. `uname -a`): Linux pwt-test-cluster-master 4.15.0-34-generic #37-Ubuntu SMP Mon Aug 27 15:21:48 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:

/kind feature

**Comment by liggitt** [comment]
regular expressions are not yet supported in the jsonpath evaluator, marking this as a feature. since this is also used server-side, we need to make sure any addition doesn't open allow pathological expressions to DOS the apiserver

**Comment by DTMad** [comment]
This is still a problem - please fix this

**Comment by krishofmans** [comment]
Also ran into this issue, assuming since there's an `-o jsonPath` that it would be a complete implementation of jsonPath ... apparently it's not.

**Comment by zetas** [comment]
Same here. Just been banging my head against this for hours. It really should at least say on the json path kubectl docs that it isn't fully supported.

**Comment by povsister** [comment]
Ran into the same issue.
At least there should be a WARNING on document saying that jsonpath features are not fully implemented.
Apparently I got nothing from doc and it wasted me 20 minutes checking jsonpath doc to see if I am wrong with syntax.

**Comment by ozbillwang** [comment]
@ashishranjan738 

Any updates?

**Comment by povsister** [comment]
I have implemented the jsonpath regex support for kubectl. It works well on client-side.

New to K8S community... Figuring out how to raise a PR.

**Comment by liggitt** [comment]
Do you have a reference for how jsonpath supports regular expressions? We'd want to make sure any addition we make is standard (there are a couple places we support non-standard filter syntax in jsonpath today that have caused headaches for improving jsonpath support in other ways). See similar discussion in https://github.com/kubernetes/kubernetes/pull/79227#issuecomment-538030944

**Comment by povsister** [comment]
> Do you have a reference for how jsonpath supports regular expressions? 
Yes. I referred [JsonPath Java](https://github.com/json-path/JsonPath) implementation but with a little modification:
- Regex pattern is quoted using a pair of `"` instead of a pair of slash `/`

Because the std `regexp` package does not require quoting pattern with `/`
See [https://godoc.org/regexp](https://godoc.org/regexp)
Double quotation is made for internal token reader to not split it.

As far as I know. There is no offical JSONPath standard.
So I just picked a famous implementation in Java which uses `=~` as regex match operator.


> There are a couple places we support non-standard filter syntax in jsonpath today that have caused headaches for improving jsonpath support in other ways

Yeah, I agree with that.
Because of the existing token reader mechanism implemented in jsonpath, escape special character with a single backslash `\` sometimes won't working.
If you try to escape regex meta character like `+` or `.`
you need to use double backslash `\\`
```
kubectl get pods -A -o jsonpath='{.items[?(@.metadata.name =~ "\\.")].metadata.name}'

Will output all pods name whose `metadata.name` contains a single dot
```
All works well except escape double quotation `"` itself: You need to use single backslash `\`
```
kubectl get pods -A -o jsonpath='{.items[?(@.someField =~ "\"")].metadata.name}'

Will output all pods name whose `someField` contains a double quotation mark
```

But it still can be explained:
- Double backslash works for regex escape,
- Single backslash works for command string escape.

Since content inside double quotation is simply passed through. So the behavior should be consistent with std `regexp` package.
And it really does so.

**Comment by liggitt** [comment]
Thanks for the work, but I think this needs more agreement before proceeding. As mentioned in https://github.com/kubernetes/kubernetes/pull/79227#issuecomment-538030944, ad hoc support for unspecified features is problematic.

> As far as I know. There is no official JSONPath standard.

That is my concern.

> So I just picked a famous implementation in Java which uses =~ as regex match operator.

Picking an arbitrary other implementation to match behavior against is not as principled as I would expect our API support to be, *especially* if we don't actually match that other implementation exactly ("I referred JsonPath Java implementation but with a little modification: Regex pattern is quoted using a pair of " instead of a pair of slash /")

**Comment by povsister** [comment]
Stick to the standards usually make things clear&better. 
But, what if there is no applicable standard ? Or the standard is out of date ?

The only [standard-like description](https://goessner.net/articles/JsonPath/) for jsonpath is written 13 years ago. And no regex-related operators was found.
The java implementation I referred above also claims to have implemented this standard. But it do has a regex operator.

In fact, I am not picking an implementation arbitrarily. The Java implementation is so famous that itself becomes the practical standard.

For many years, no one stepped out for announcing an extend of old standard.
I think this should not be a drag to deliver new features as long as they are properly documented.

The current Go implemented JSONPath is a super-set of the standard.
My suggestion is to keep extending. And document changes.

By the way.
It comes with some reasons to do the "little modification"
1. We are Go programmers, and we are familiar with `regexp` package.
2. `regexp` requires `"pattern"` instead of `/pattern/`
3. To be compatible with existing token reader

**Comment by lavalamp** [comment]
The below is actually shorter. You can also make a jq script to do pretty much anything and even maintain it as a file if you wish. But in this case grep is very simple.

```
kubectl get secrets -o json | jq '.items[].metadata.name' | grep '^test-.*'
```

I only object to jsonpath being in kubectl a little bit, but I would object greatly to it being promoted to an actual api.

**Comment by povsister** [comment]
> The below is actually shorter. You can also make a jq script to do pretty much anything and even maintain it as a file if you wish. But in this case grep is very simple.
> 
> ```
> kubectl get secrets -o json | jq '.items[].metadata.name' | grep '^test-.*'
> ```
> 
`jq` is not installed by default on several Linux distributions.
For maximum compatibility and migration, using `jq` to achieve simple purpose is not a good idea.
Especially for enterprise users, generally their machines can not access Internet. Making it hard to install additional dependency.

>
> I only object to jsonpath being in kubectl a little bit, but I would object greatly to it being promoted to an actual api.
>
JSONPath is widely used on client-side. I prefer it to be a useful tool instead of a concrete API.

For now, I usually use kubectl with jsonpath in shell scripts to fetch a batch of desired resource names/template specs.. etc. Then the result can be directly used in `for` loops to do something bigger.
 It saves me a lot in handling error. One command is dependency-free and obviously better than 3 or 4 command pipes. Isn't it ?

**Comment by survivant** [comment]
I just found this issue after looking for hours.  I'm not alone :)   

we should have to rely on external command like : grep, awk, jq...

so as my understanding.. we can't find with regex in jsonpath for now.

I was trying to find all pods starting with name : test*    (I wanted to add a label only on those pods)

**Comment by reschex** [comment]
Whilst I agree with the rest of the points, I want to dispell this notion before anybody else sees it and gives up on jq:

> What's more.
> If my purpose is not to find all pods names start with `test-`, but to find all images used by pods whose name is `test-*` ?
> Oops.. You need a `for loop` and lots of additional shell codes to do so if there is no jsonpath regex support.
> That's ugly and painful.

This is a perfectly valid use case for jq and doesn't require any further for loops or any other shell code for that matter.

```bash
k get po -o json | jq -r '.items[] | select(.metadata.name | test("test-")).spec.containers[].image'
```

**Comment by webmutation** [comment]
This is very annoying... If JSONPath does not support regex, then it is not very useful, and should probably be removed altogether.

I fully agree with @povsister jq is not present in many linux and windows distributions, creating an additional dependency and in our case we can't even install it since we don't have admin rights to install it. and in some cases grep is also not available only kubectl.

Also you are wasting a lot of developers time, that normally use JSONPath and discover this issue, at least put a note or something in the documentation. https://kubernetes.io/docs/reference/kubectl/jsonpath/

**Comment by lavalamp** [comment]
If kubectl is more commonly available than grep then we have really made it :)

We'd be happy to accept a PR improving the documentation.

**Comment by povsister** [comment]
Actually, there is no RFC standard, and even no ITEF draft for JSONPath syntax.
Till now almost every implement of JSONPath is based on "unofficial" and old [Stefan Goener JSONPath](http://goessner.net/articles/JsonPath/), with some arbitrary modification. (You guess what, regex support is also "arbitrary", because it does not have any standard reference).

Non-standard behavior will cause many long-lasting or legacy problems to application lifecycle and project maintainers which is strongly discouraged.

So, like [JSON Strategic Merge Patch](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-api-machinery/strategic-merge-patch.md)(which is a K8S modified version of JSON merge patch), if we want to extend JSONPath implement of K8S, the first thing is to raise a standard reference called Kubernetes Enhancement Proposal(KEP). I have already done this part in https://github.com/kubernetes/enhancements/pull/1887 
It describes the past and future needs of JSONPath, also with a completed syntax reference book. But associated reviewer does not have enough time and effort for this proposal, seems we need more time to discuss it.

**Comment by webmutation** [comment]
@lavalamp To give context, In the European Commission we (5.000+ developers) have Windows 10 Corporate laptops with no admin rights. That is why grep is not available, but kubectl is available as a virtualized app (App-V) that we can install. We cannot install jq (it has to be requested and an approval process that takes days or weeks), same for mingw it takes time to have it approved since it is not considered a standard request. 

So as you can see having JSONPath regex implemented in the kubectl cli would make our lives a lot simpler, because having to request new utilities just to handle exceptions is a PITA. I don't think we are the only audience of corporate users that have this kind of restriction.

Very well, I will make a PR for the documentation... I think it will save others the same frustrations. However I don't see why this is not added to the cli, I mean kustomize was added to the CLI which is a much more invasive and opinionated decision than to support JSONPath using Go style RegEx. 

Any developer understands RegEx and tooling is simplified making the CLI more useful and less dependent on tooling that only creates drift, because some may use jq, others may use fx or jello or any other json library. Then they have to use the right version of jq... in our case we had to write python scripts to do something in 10 lines that could be done in 1 using the CLI. Its not the end of the world, its just frustrating and affects developer ergonomics, you are developers as well, so when a tool makes you do workarounds I think the feeling of frustration and annoyance is similar. I only mention this because there is already a PR by @povister that could make this problem go away.

**Comment by krishofmans** [comment]
@webmutation while I agree with your general point, I disagree that the factor of an organisation that more or less actively tries to hinder development teams by denying them tools to properly do their job should influence any decision. I know there are plenty of organisations like that, but they should just bleed money for the fact that they prevent people from doing their job for that. Not influence outcomes of PR's :)

In case of the EU they will bleed money because of this, and it's tax payers money, so they will also never fix their organisation.

**Comment by webmutation** [comment]
@krishofmans the point here was to explain why it is not easy to install a lot of tools in corporate environments, it is just one scenario. Just to give context to @lavalamp comment that it very strange that we would have kubectl but not grep, it may seem crazy, but its true, this type of situations exist. In particular in corporate environments. I have collegues that work also on financial and telecom institutions with this type of restrictions. It's 💩

I fully agree with you and I fight/negotiate everyday to improve things... currently we are not even allowed to install docker in development laptops, but we have Corporate PKS and we can run there (something that took 5 years of negotiation). Luckily we have AWS environments where we have freedom, but deployment environments (ACC, PRD) are hosted on DC, a lot of restrictions in the name of security, so we are restricted.

Anyway, the point that I try to make and nevermind the context (corproate or not), is that one tool is better than many tools from a developer ergonomics point of view. And in particular its better than having a half implemented feature like JSONPath with no RegEx... Since there is already a PR and the reason seems to be its not standard, but there is no JSONPath standard currently supported, it would make more sense to support Go style RegEx, since most of Kubernetes community is used to it and document the usage.

**Comment by lavalamp** [comment]
Don't get me wrong, that sounds like a super frustrating situation to be in, I'm sorry you have to live with that. (This is a horrible hack and probably not approved by corporate overlords, but, if you're allowed to run things in a cluster, you could run grep or jq in a container via kubectl exec and/or attach!)

My own concern is ecosystem fragmentation, I don't want to run a variation of JSONPath that ends up not being standard. E.g., if we go with go regexps and then some other flavor is standardized... then we would have a major problem: no course of action would make both existing and new users happy.

That said, this is only kubectl we're talking about, not the API. So, it's actually SIG CLI members that should be the gatekeeper here, not me.

**Comment by gmile** [comment]
For what it's worth, JSONPath is being standardised at the moment. The work can be tracked here: https://datatracker.ietf.org/doc/draft-ietf-jsonpath-base/
