### ISSUE TITLE
In IPVS mode, host services become available on ClusterIPs

### ISSUE THREAD

**Issue by fasaxc** [kubernetes/kubernetes#72236]
**What happened**:

In IPVS mode, if a service on the host is listening on `0.0.0.0:<some port>`, pods on the local host (or incoming traffic from other hosts if routing allows it) to any ClusterIP on `<some port>` reaches the host service.

For example, a pod can access its host's ssh service at something like `10.96.0.1:22`

**What you expected to happen**:

ClusterIPs should reject or drop traffic to unexpected ports (as is the behaviour in iptables mode).

**How to reproduce it (as minimally and precisely as possible)**:

- Turn on IPVS mode for kube-proxy
- Configure ssh to listen on 0.0.0.0 (the default in most installations)
- Exec into a pod and ssh to, say `10.96.0.1:22`, should reach the host.

**Anything else we need to know?**:

This unexpected behaviour has some security impact; it's an extra, unexpected, way for packets to reach the host.  In addition, it's very hard for a NetworkPolicy provider to secure this path (such as Calico) to secure this path because IPVS captures traffic that, to the kernel's policy engines, looks like it's going to be terminated at the host.  For example, in iptables, there's no way to tell the difference between traffic that is about to be terminated by IPVS and traffic that's going to go to a local service.

Related Calico issue; user was trying to block the traffic with Calico policy but was unable to (because Calico has to whitelist all potential IPVS traffic): https://github.com/projectcalico/calico/issues/2279

**Environment**:
- Kubernetes version (use `kubectl version`): 1.12
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/kind bug

**Comment by cjcullen** [comment]
@rramkumar1 @prameshj @bowei

**Comment by uablrek** [comment]
The ClusterIP addresses (and external addresses) are added to the local `kube-ipvs0` device which must be done to get traffic to ipvs;
```
# ip addr show dev kube-ipvs0
13: kube-ipvs0: <BROADCAST,NOARP> mtu 1500 qdisc noop state DOWN group default 
    link/ether 92:0b:28:ce:3f:77 brd ff:ff:ff:ff:ff:ff
    inet 12.0.0.1/32 brd 12.0.0.1 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 12.0.0.2/32 brd 12.0.0.2 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
```
The `12.0.0.x` addresses are my ClusterIP's for kubernetes and coredns.

The problem however seems to be the route that is automatically added to the `local` routing table;
```
# ip ro show table local
local 12.0.0.1 dev kube-ipvs0 proto kernel scope host src 12.0.0.1 
local 12.0.0.2 dev kube-ipvs0 proto kernel scope host src 12.0.0.2 
```
Now I can ssh to my local machine using these addresses as described in this issue;
```
# ssh 12.0.0.1 hostname
vm-004
```
But if the entry in the `local` routing table is removed it does not work any more;
```
# ip ro del 12.0.0.1/32 table local
# ssh 12.0.0.1 hostname
(hangs...)
```
I think removing the entry in the `local` routing table immediately after adding the address to the `kube-ipvs0` interface is the best way to fix this problem.

**Comment by uablrek** [comment]
Related `kube-router` issue; https://github.com/cloudnativelabs/kube-router/issues/282

**Comment by uablrek** [comment]
Pod-to-pod traffic does not work when the local table entry is removed.

So I must withdraw my proposal.

Please read more in https://github.com/cloudnativelabs/kube-router/issues/623

**Comment by m1093782566** [comment]
@emptywee 

You should use ping instead of telnet.

**Comment by emptywee** [comment]
@m1093782566 maybe I misread the original description of the issue, but I took it as it was possible to ssh to the sshd service running on a host from a pod using the IP address of any service created in Kubernetes when kube-proxy is in the ipvs mode, as opposed to iptables mode. In my case the behavior is the same with either mode.

Why should I use ICMP and ping when @fasaxc was talking about ssh'ing as the provided example?

**Comment by m1093782566** [comment]
ping clusterip inside cluster.

ssh/telnet clusterip:port outside cluster.

**Comment by emptywee** [comment]
/shrug 

I can ping clusterip and I can telnet to host's sshd from a pod using clusterip:22 address. Regardless of kube-proxy mode.

**Comment by song-jiang** [comment]
@emptywee The issue is about accessing a service (`10.149.0.1:80`) but with an invalid port (`22`) from a pod. Since the port `22` is invalid for the service, with iptables mode accessing `10.149.0.1:22` should fail. However, ipvs mode attaches `10.149.0.1` to a local eth, accessing `10.149.0.1:22`from a pod will be directed to local host sshd process.

**Comment by emptywee** [comment]
@song-jiang I understand that, and in my case even with iptables it's still working as though I am in the ipvs mode. As I've shown above: https://github.com/kubernetes/kubernetes/issues/72236#issuecomment-454233194

**Comment by fasaxc** [comment]
@emptywee did you happen to switch from IPVS to iptables mode without rebooting?  I'm wondering if there was an old kube-ipvs device hanging around to give the IPVS behaviour.  I don't have a rig handy to check the iptables behaviour but I thought I'd seen that traffic get dropped before.

**Comment by fasaxc** [comment]
@emptywee that's odd then, does the service's IP show up in `ip addr` on the host?  Is it the the host that you're able to reach (service traffic typically gets forwarded to the default gateway if  kube-proxy's rules get missed)?

**Comment by emptywee** [comment]
@fasaxc yeah it could be the case, as we have BGP routing set up so services and pods IP space is routable in our network.

**Comment by lbernail** [comment]
I'm not sure if there is an easy way to solve this
We could probably use a drop iptables rule with an ipset and drop everything sent to clusterIPs and not matching clusterIP:servicePort

@uablrek when you remove the kube-ipvs0 entries from the local route table, are ClusterIPs still working? I would expect IPVS to require a local address in the routing table (I'm not sure though, the IPVS datapath is a bit complicated)

**Comment by uablrek** [comment]
@lbernail The clusterIP worked from the k8s node main netns but not from a pod on that node. I can't say I understand why. I totally argee on;

> the IPVS datapath is a bit complicated

**Comment by thockin** [comment]
@m1093782566 do you think this is the same as the overly-loose "local" matching for hostPorts or something else?  Do you have a diagnosis for this?

@emptywee I can not reproduce this in iptables mode at all

@fasaxc Any way to get you to test against 1.14 (which should have all the latest fixes in place)?

**Comment by m1093782566** [comment]
@thockin 

> @m1093782566 do you think this is the same as the overly-loose "local" matching for hostPorts or something else?

I don't think it's same as the hostPorts issue. The root cause is we bind ClusterIP to `kube-ipvs0` interface in the host. However, if we don't bind the ClusterIP to the interface, IPVS won't work.

I am not sure if we can drop the packets?

**Comment by lbernail** [comment]
Yes, IPVS hooks in the LOCAL_IN netfilter chain so clusterIPs have to be considered local by the kernel (ILB IPs on gcp behave the same by adding ILB internal IPs to the local route table: all host services are accessible on the internal IP).

I think the only way to prevent this is to filter traffic in the INPUT chain. We probably have everything we need in ipsets already. My only concern is the additional complexity but if we decide we need it, I'm happy to help

**Comment by thockin** [comment]
I understand better now.  What happens is we install a :0 rule for the service IP and then a more specific port rule?  Does IPVS take the most specific match?  My testing is not working right now, not sure why...

**Comment by lbernail** [comment]
Yes there are two steps:
- every clusterIP is added to the kube-ipvs0 interface so traffic is locally delivered in the kernel
- we create and ipvs entry for every clusterIP:proto/port (virtual servers) and add each pod backing the service to the real servers for this virtual server

We require a local address because IPVS hooks into netfiler LOCAL_IN, but the consequence is that clusterIPs are valid addresses for the host so any service binding 0.0.0.0 will be accessible from pods using a clusterIP

**Comment by thockin** [comment]
What I am looking for (and I don't know IPVS well enough to design) is a back-stop rule for each service cluster IP that blackholes anything not explicitly handled.  A :0 rule in IPVS seems to do that (sent to a non-existent IP) but I can't seem to test the interplay between that and an explicit port rule

**Comment by fasaxc** [comment]
I'd use the IP sets for this, create a `hash:ip` IP set that contains all the IPs attached to the kube-ipvs0 interface and a second `hash:ip,port` IP set that contains all the service `IP:port` combinations that kube-proxy is implementing.  Then you just need a single iptables rule that says "if the dest IP is in the kube-ipvs0 set but the IP and port is not in the valid services set then DROP".

**Comment by rmt** [comment]
For the kids wanting to try this at home, the following will drop all host packets except for those going to service IPs:
```
# iptables -A INPUT -j DROP -i cali+ -m set '!' --match-set KUBE-CLUSTER-IP dst,dst
```
I imagine the actual implementation in kube-proxy might not want to drop _all_ packets, though, so the implementation will probably be slightly different.. but for me, this replaced my catch-all DROP rule.

**Comment by song-jiang** [comment]
Any updates on this issue? @m1093782566

**Comment by unconfigured** [comment]
Any chance to get the nodes local services off the intra-/internet soon? @lbernail maybe?

I think this unexpected behavior is a serious security issue, calico has fail safe rules that open ssh, bgp, dhcp and others per default and there is currently no way to block this traffic with default methods. Using metallb this also means your ports might be exposed publicly.

**Comment by lbernail** [comment]
So far the simplest solution is to add an iptables rule to drop offending traffic. It's not ideal as IPVS was designed to limit iptables usage but it's too bad because it should a single simple rule using an already existing ipset.

We still need to only match traffic from pods which is not easy because CNI plugins use different naming conventions for pod veths (cali+, veth+, lxc+ for instance). I'm not sure there is a way to filter on interface type (in which case we could filter on type veth).

cc @andrewsykim

**Comment by fasaxc** [comment]
> We still need to only match traffic from pods

Why is that?  Lot of users use routes to expose their cluster IPs on the wider network.

**Comment by lbernail** [comment]
> Why is that? Lot of users use routes to expose their cluster IPs on the wider network.

True, we can actually just drop all traffic to cluster IPs that are not sent to service ports

**Comment by andrewsykim** [comment]
> True, we can actually just drop all traffic to cluster IPs that is not sent to service ports 

As many people have already mentioned, I think doing ^ with iptables seems like the worse case scenario (not a bad worse case scenario IMO). I would like to spend a bit more time thinking through the problem though before resorting to that given how hard it would be to undo those rules in the future.

**Comment by rmt** [comment]
Any luck finding an IPVS only solution?  My understanding was that it wouldn't be possible, but I'd very much like to be surprised.

**Comment by juliantaylor** [comment]
If there is no quick solution in sight this should be more prominently documented at least on https://kubernetes.io/docs/concepts/services-networking/service/#proxy-mode-ipvs I did not find anything interesting.

A workaround is to configure your host services to only bind to the node ip addresses instead of the wildcard interface 0.0.0.0 if possible and (probably) use the `NodePortAddresses` config to keep nodeports from being public.

Unfortunately this is quite inconvenient with kube-proxy itself as the addresses it binds are in a configuration map so you cannot use an environment variable filled with `fieldRef.fieldPath: status.hostIP` via its deployment but need to write the configmap dynamically via a initcontainer (command line --bind-address, --metrics-bind-address, --healthz-bind-address do not work anymore)
Also it is not a very reliable workaround, as you need to take care of it each time you open a new port on the hosts.

**Comment by rmt** [comment]
/reopen

We shouldn't let security issues be swept under the rug, especially not by upstart bots. ;-)

**Comment by andrewsykim** [comment]
I've been steeping on this for the last few months and I have not thought of a good solution yet. This is ultimately a side effect of how IPVS binds to a dummy interface on the host which is not something we can change at this point. I think iptables may have be involved here which is not ideal but better than nothing. Thoughts @lbernail @cmluciano?

**Comment by uablrek** [comment]
> I've been steeping on this for the last few months and I have not thought of a good solution yet.

Me too. I don't think there is any way to avoid iptables. The "other way" to get traffic to ipvs seems to be with fw-marks, but they are set in iptables (and would be horrible to manage).

> True, we can actually just drop all traffic to cluster IPs that is not sent to service ports

If the service ip range is `12.0.0.0/16` a rule may look like;
```
iptables -A INPUT -d 12.0.0.0/16 -m set ! --match-set KUBE-CLUSTER-IP dst,dst -j REJECT
```

**Bad news**; this does not work for traffic from main netns on a node. Access to ClusterIPs hangs (not rejected).

It does the job of blocking access to ports in main netns (the problem in this issue) and it works to access the ClusterIP from PODs.

**Good (and bad?) news**; It can be fixed, but the addresses can't be assigned to `kube-ipvs0`, which means a larger job for implementation.

### The problem

To find the reason took a long time for me and if someone with deep knowledge of linux routing can either confirm or tell what's really happens I would appreciate it.

When adding an address to `kube-ipvs0` (or any interface) entries are automatically created in the "local" routing table;
```
$ kubectl get svc
NAME            TYPE           CLUSTER-IP        EXTERNAL-IP   PORT(S)          AGE
kubernetes      ClusterIP      12.0.0.1          <none>        443/TCP          3m17s
mconnect-ipv4   LoadBalancer   12.0.125.1        10.0.0.0      5001:32200/TCP   3m1s
mconnect-ipv6   LoadBalancer   fd00:4000::9796   1000::        5001:31293/TCP   3m1s
$ ip addr show dev kube-ipvs0
15: kube-ipvs0: <BROADCAST,NOARP> mtu 1500 qdisc noop state DOWN group default 
    link/ether be:f4:b1:7d:ad:1d brd ff:ff:ff:ff:ff:ff
    inet 12.0.159.48/32 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 12.0.0.1/32 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 12.0.125.1/32 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 10.0.0.0/32 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet6 1000::/128 scope global 
       valid_lft forever preferred_lft forever
    inet6 fd00:4000::9796/128 scope global 
       valid_lft forever preferred_lft forever
$ ip route show table local
...
local 12.0.125.1 dev kube-ipvs0 proto kernel scope host src 12.0.125.1 
local 12.0.159.48 dev kube-ipvs0 proto kernel scope host src 12.0.159.48 
...
```
Note that the "src" is the same as the target so return packets will have 12.0.125.1 as destination.

When the iptables rule is applied it will be hit for the reply packets since they will be NAT'ed back to have dest 12.0.125.1 but with another port and will be rejected;

```
$ ptables -L -nv
Chain INPUT (policy ACCEPT 85 packets, 48929 bytes)
 pkts bytes target     prot opt in     out     source               destination         
  416  570K KUBE-FIREWALL  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
    5   300 REJECT     all  --  *      *       0.0.0.0/0            12.0.0.0/16          ! match-set KUBE-CLUSTER-IP dst,dst reject-with icmp-port-unreachable
```

### A solution

Fortunately route in the "local" table is sufficient. The address does *not* have to be assigned to an interface;
```
$ ip route replace 12.0.125.1/32 table local dev lo src 192.168.1.3
```
This fixes the problem. Reply packets will have 192.168.1.3 (node-ip) as dest and will not hit the reject rule.

And here is the good part;

The route in the "local" table can be a range, like the cluster cidr;
```
$ ip route replace 12.0.0.0/16 table local dev lo src 192.168.1.3
```
Nothing more has to be added for ClusterIPs *ever*! This have potential to simplify code greatly and remove extensive cpu waste in the sync function, see https://github.com/kubernetes/kubernetes/issues/88212.

If the dst,port is removed from the KUBE-CLUSTER-IP set if the service has no endpoints attempts to connect to the (empty) service will be rejected and fix another issue; https://github.com/kubernetes/kubernetes/issues/78994.


### Where can kube-proxy find the cluster CIDRs?

The cluster CIDRs are needed by `kube-proxy` for this.

Can the cluster CIDRs be read in some object in the API server?


### WIP PR (PoC)?

As I see it we can fix 3 issues and simplify the code with this solution.

I have tested to *not* assign ClusterIPs to `kube-ipvs0` (with a hack) and replace it with the one route above. It seem to works fine, both for ipv4 and ipv6.

If you agree I would like to start a [WIP] PR and see where it leads. First;

* Add the route for cluster CIDRs and omit them in `kube-ipvs0`

* Add the iptables rule to reject access


### External addresses

ExternalIPs and loadBalancerIPs opens the same security issue as ClusterIPs but are harder to fix since there is no CIDR to match.

The only idea I have at the moment is a new set `hash:ip` with all external addresses (without port) then match on this and after that reject all requests not in KUBE-LOAD-BALANCER or KUBE-EXTERNAL-IP.

**Comment by uablrek** [comment]
If external-ips also are replaces by entries in the local table and not assigned to `kube-ipvs0` should solve https://github.com/kubernetes/kubernetes/issues/79783

**Comment by lbernail** [comment]
@uablrek this is very interesting and worth exploring
This is actually what the google_network_daemon does on gce for Internal Load Balancers (traffic reaches the instances with the ILB VIP and in order for this address to be considered local the daemon adds the VIP to the local route table).

This would greatly improve performances too.
Just to summarize, this would mean:
- dropping the IPVS interface
- adding a the service CIDR to the local route with the node IP as source
- adding the iptables rule to drop traffic to the service cidr but not maching the set KUBE-CLUSTER-IP

My main concern is this is a huge change which could trigger a lot of edge cases and would require very serious testing (potentially on multiple kernels)

**Comment by lbernail** [comment]
@uablrek as explained in the other issue we would still need to add loadbalancer IP to the local route table

Having look into it some more it's not easy:
- we don't have the service cidr in the kube-proxy configuration
- the pod cidr is optional

What we could do is add an iptables rule dropping all traffic from the pod CIDR to the service cidr but not matching the set KUBE-CLUSTER-IP but this would require having both the pod and service cidr in the configuration.

Requiring cluster and pod cidr in the configuration is interesting because it would allow several optimizations but it's not a small change and we would to fallback to the current behavior if they are not set
@andrewsykim what do you think?

**Comment by andrewsykim** [comment]
Agreed that @uablrek's suggestion is definitely worth exploring.

> What we could do is add an iptables rule dropping all traffic from the pod CIDR to the service cidr but not matching the set KUBE-CLUSTER-IP but this would require having both the pod and service cidr in the configuration.

I think we can use --cluster-cidr for pods. For services, I think a reasonable compromise is an entry in the local route table per Service. This seems reasonable since we know each Service's cluster IP but we don't know the full range. Performance-wise this wouldn't be any worse than what we have today.

**Comment by Lion-Wei** [comment]
/assign
I'll dig into it.

**Comment by Jc2k** [comment]
Any update on this behaviour? It's very surprising and not ideal. Is there some sort of security tag the issue should have? As suggested in by the original filer it seems like there is a security component to this too.

**Comment by Jc2k** [comment]
/remove-lifecycle stale

Are there any updates on this? The security issue still where you have an external ip on kube-ipvs0 and can now access internal ports still seems to be present?

**Comment by Jc2k** [comment]
FWIW, looks like kube-router did a similar fix to the one proposed by @rmt [here](https://github.com/kubernetes/kubernetes/issues/72236#issuecomment-483452622).

**Comment by Jc2k** [comment]
I tried escalating this to the security team but they weren't able to help!

> At this point, the public issue is the right place to continue the discussion. You can also propose it as an agenda item at the SIG Network Kube Proxy meeting.

Unfortunately I can't easily reproduce it at the moment (too many mitigations) so I don't feel like I can strongly campaign to get this fixed on my own. Can you detail your setup a bit to help? Were the load balancers on internet facing IPs? What's your cni?

**Comment by jpiper** [comment]
In my test rig I'm on bare metal, and I put kube-proxy in ipvs mode, and then metallb to assign the VIPs from some private IP space. I have tried both Cilium and Calico for the CNI and both have this bug (my hunch would be that if I tried cilium's kube-proxy replacement this wouldn't be an issue).

I haven't looked into it, but I wouldn't be surprised if the cloud load balancer providers (e.g. https://github.com/kubernetes-sigs/aws-load-balancer-controller) put a security policy on the loadbalancer itself that only allow access on the configured ports, so this dodgy behaviour won't be seen as the LB itself is dropping non-configured ports before it gets to the host.

On bare metal, however, BGP just tells the switch "give me all traffic for this IP" and if your network ACLs allow it, it will just forward all traffic to the LB IP onto the k8s host, which then happily exposes the host services on this IP.

**Comment by jpiper** [comment]
or (and I suspect this is more likely) none of the cloud providers support IPVS out of the box so this isn't really on anyone's radar

https://github.com/Azure/AKS/issues/1846
https://github.com/aws/containers-roadmap/issues/142
https://stackoverflow.com/questions/54238807/is-there-a-way-to-enable-ipvs-proxy-mode-on-gke-cluster

**Comment by Jc2k** [comment]
Thanks @jpiper. Yeah thats basically my setup (Calico + MetalLB), with VIP's coming from public ip space (not RFC1918).

In the original calico ticket (https://github.com/projectcalico/calico/issues/2279) @KashifSaadat had calico managed iptable rules that couldn't block this traffic. So there was a bug in kube-proxy *AND* calico couldn't even mitigate it.

I think calico managed pre-dnat rules can block this traffic, but at this point in my environments I have too many other layers of filtering in place to drawn and be confident in any experimental conclusions.

And even if it does its not a replacement for the bug being fixed.

kube-router's kube-proxy replacement *did* have this issue, their fix is [here](https://github.com/cloudnativelabs/kube-router/pull/618).

I do wonder how many live systems are unknowingly exposed like this.

**Comment by jpiper** [comment]
@Jc2k How do we go about proposing this as an agenda item then? This seems like an awful bug to have.

**Comment by Jc2k** [comment]
@jpiper I was given [this link](https://docs.google.com/document/d/1yW3AUp5rYDLYCAtZc6e4zeLbP5HPLXdvuEFeVESOTic/edit) but thats all.

That doc mentions someone called hanamant is involved in IPVS at that meeting, is that @hanamantagoudvk? Maybe they can help us get this security issue resolved.

**Comment by Jc2k** [comment]
@jpiper given you reproduced it on cilium, maybe worth dropping a line to security@cilium.io as well?

**Comment by jpiper** [comment]
@Jc2k in the mean time, I'm just going to use `kube-router`'s IPVS proxy implementation. I can delete the old kube-proxy daemonset and then install `kube-router` and it clears up all the old cruft and just works, I don't get this issue or the other one in `https://github.com/kubernetes/kubernetes/issues/75262` either. I verified this approach works with calico, will need to verify cilium as well

**Comment by Jc2k** [comment]
Oh thats a really good tip. I've been bitten by #75262 too.

**Comment by uablrek** [comment]
An open PR exist that fixes this problem.

/remove-lifecycle stale

**Comment by uablrek** [comment]
And there was much rejoicing :smile:
