### ISSUE TITLE
storage e2e: TestDriver should be unique per driver instance

### ISSUE THREAD

**Issue by msau42** [kubernetes/kubernetes#72288]
**What happened**:
From https://github.com/kubernetes/kubernetes/pull/70862#discussion_r243667417, I think it's not a clean abstraction to have to reset TestDriver state at the beginning of CreateDriver.  Since we are creating a driver for every test case, we should create a new TestDriver object with every driver instance.

@kubernetes/sig-storage-misc 
/kind cleanup

**Comment by msau42** [comment]
cc @pohly @mkimuram

**Comment by msau42** [comment]
I'd prefer to avoid defining too many types and interfaces; it will get confusing to test writers and driver implementations quickly.  Separating per driver-instance information may be cleaner.  Is it harmful if even static information gets reset with every driver instance?

cc @verult for thoughts

**Comment by pohly** [comment]
Indeed, let's forget the idea with `CreateDriver` returning a new driver variant. It occurred to me later that this probably can't work as originally intended because then test suite code won't have access to any driver pointer until the test actually runs, which makes it impossible to skip test definitions.

To make the code easier to read, we might even be able to get rid of all these per-test "input" structs that just copy other variables:
https://github.com/kubernetes/kubernetes/blob/dfaf10f46955158c2715875a23c2352713a3162b/test/e2e/storage/testsuites/provisioning.go#L126-L129

`testProvisioning` could be inlined into `execTest` and use automatic Go variable binding if needed.

**Comment by msau42** [comment]
Agree, I don't think a separate struct for test case input, and another function that copies them is necessary
