### ISSUE TITLE
CrashLoopBackoff Pod cannot be evicted because of PodDisruptionBudget

### ISSUE THREAD

**Issue by tatsuhiro-t** [kubernetes/kubernetes#72320]
**What happened**:

My StatefulSet created 3 Pods.  They got deployed onto the same node and in CrashLoopBackoff state for some reason.  PodDisruptionBudget was set for them with default 25% maxUnavailable.
I created new Node and ran `kubectl drain --force=true` against the old Node where 3 CrashLoopBackoff Pods were running.   kubelet could not evict any of Pods in CrashLoopBackoff state because of PodDisruptionBudget.

**What you expected to happen**:

Pods in CrashLoopbackBackoff are effectively considered dead, so I expect that kubelet can evict them and scheduler creates new Pod in the another Node.

**How to reproduce it (as minimally and precisely as possible)**:

1.  Create 1 worker k8s cluster.
2. Deploy StatefulSet with replicas count 3 and make it CrashLoopBackoff.  Set PodDisruptionBudget for them with 25% maxUnavailable.
3. Create new worker Node.
4. Run `kubectl drain --force=true` against old Node.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.13.1
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/kind bug

**Comment by surajssd** [comment]
One of the pods managed to evict:

```console
[root@c0 ~]# kubectl get pods,poddisruptionbudget -o wide                                                                                                                                     
NAME               READY   STATUS             RESTARTS   AGE    IP          NODE   NOMINATED NODE   READINESS GATES
pod/postgresql-0   0/1     CrashLoopBackOff   7          17m    10.40.0.1   w0     <none>           <none>
pod/postgresql-1   0/1     CrashLoopBackOff   5          8m8s   10.38.0.1   w1     <none>           <none>
pod/postgresql-2   0/1     CrashLoopBackOff   7          17m    10.40.0.3   w0     <none>           <none>

NAME                                    MIN AVAILABLE   MAX UNAVAILABLE   ALLOWED DISRUPTIONS   AGE
poddisruptionbudget.policy/postgresql   N/A             25%               0                     20m
```

**Comment by tatsuhiro-t** [comment]
I've got the same result.  One of the pod could be evicted but overall there were pods which could not be evicted.  I guess that STATUS gets Running in a short period of time and eviction logic grants a eviction.

**Comment by krmayankk** [comment]
/sig apps
for comments
was the pod not evicted because of statefulset or because or pdb ? My guess is ,even if you remove the pdb, this wont get evicted by how statefulset is designed

**Comment by tedyu** [comment]
Looking at EvictionREST#checkAndDecrement, there are two places where the "Cannot evict pod as it would violate" would be given:
```
	if pdb.Status.ObservedGeneration < pdb.Generation {
```
```
	if pdb.Status.PodDisruptionsAllowed == 0 {
		err := errors.NewTooManyRequests("Cannot evict pod as it would violate the pod's disruption budget.", 0)
```
I think it would be better if the error messages carry slightly different wording.

**Comment by 2rs2ts** [comment]
This is a big problem for us because our developers will often test broken stuff in our development clusters and leave it there and it breaks cluster-autoscaler and our other automation. Nodes that are "too far gone" should not block eviction

**Comment by mortent** [comment]
So what happens is that the disruption controller decides `allowedDisruption` based on the ready condition of pods. So while the PDB in the example above initially starts out allowing 1 disruption, whenever the container in one or more of the pods completes, this will be reduced to 0. Note that the phase of the pod remains `Running` even while the container are being restarted.

The eviction controller looks at the phase of pods when deciding whether they can be evicted and pods in either the Failed or Complete phases are evicted without considering PDBs. But in the example above, the pod phase remains Running, so eviction of these pods will always be subject to the PDB. In the example the PDB will block eviction unless all the three pods have the Ready condition set to True.

https://github.com/kubernetes/kubernetes/pull/83906 will allow deletion of pods in the pending phase without looking at the PDB, but it will not fix this situation since the pods remain in the Running phase. To allow eviction of pods which are in CrashLoopBackoff, the eviction controller would have to look at pod conditions and possibly the container statuses.

**Comment by DavidWHarvey** [comment]
We just hit this, and it made an outage not automatically recover.  Arguably there were other things wrong, but Pods in CrashLoopBackoff or Pending are already disrupted, so no evicting them from a draining node makes no sense. In our case, if any of the nodes with *no working pods* had terminated, the node would have drained, ad a new node would have be created that would have been able to take on the load.

Our indicent intersected with this weird rule where the cluster autoscaler won't add nodes because too many nodes are draining.   The "all nodes draining" was a bug of ours that didn't properly handle a CloudFormation Internal Error that AWS decided to report rather than that they were just throttled.  
So we had draining nodes with no working Pods but some pods with CrashLoopBackOff.   
If any of the nodes had drained, the instance would have terminated, and the node would have been replaced with a non-draining one.   The CrashLoopBackOff was due to those pods depending on services that could not restart because they were pending.   We are still trying to determine why we lost some of the service.

**Comment by michaelgugino** [comment]
@DavidWHarvey not sure what drain library you're using for your automation, but here's a patch that could potentially help you: https://github.com/kubernetes/kubernetes/pull/85571

So, whatever is doing your draining, if you are certain you can ignore PDBs, you could use that option to 'complete' the drain.

**Comment by mortent** [comment]
This issue was brought up at the sig-apps meeting in early December. There are some discussions related to this in #81175 and #83906. I think the core issue here is that the rules for when a pod is considered ready in the disruption controller and when a pod can be evicted are different.

/cc @kow3ns @janetkuo @tnozicka

**Comment by michaelgugino** [comment]
I've been thinking more about this recently.  Looks like https://github.com/kubernetes/kubernetes/pull/83906 should be merging soon.

I think this issue is more or less the same as https://github.com/kubernetes/kubernetes/issues/80389

In this case, we're talking about pods in CrashLoopBackOff.  In the other issue, we're talking about pods in various other states.

What I think we're ultimately talking about here is pods with condition "Ready=False".  If we couple that with enforcing resourceVersion as we're doing in PR 83906, then we could probably forego the PDB check as long as we confirm there are enough healthy replicas.

IMO, we always want to check for enough healthy replicas because a pod in CrashLoopBackOff may have valid data, and it may return from that state once some condition is restored.  EG, I write an application that, instead of having a while loop to check connection to some external resource, I exit 1 knowing k8s will restart me.  After a few seconds, I'm back, I check, and then exit again, etc.  Eventually, the remote thing comes back and I'm back in ready mode.

Checking that resourceVersion hasn't changed, along with verifying there are minimum ready pods elsewhere, ensures that when we mark the pod for deletion, it is not going to be counted in the ready pods, and thus should be safe to delete.

**Comment by skraga** [comment]
Hello, we're facing the same issue. We use Prometheus StatefulSet with VerticalPodAutoscaler and when Prometheus got OutOfMemory it stuck in CrashLoopBack forever. VPA is not able to evict the pod to increase the resources (infinite loop).

**Comment by mortent** [comment]
@skraga The question about whether it is safe to evict crashlooping pods when they are covered by a PDB is discussed in some detail in https://github.com/kubernetes/kubernetes/pull/94381. The current stance on this is that it would not be safe to evict them and therefore this is a situation that will require manual intervention.

**Comment by pasimoes** [comment]
I am facing the same issue trying to drain a worker node to upgrade the cluster. The drain command is in a loop trying to evict the calico-kube-controllers pod and could not because of PDB. And, calico-kube-controllers is in CrashLoopBackOff.

**Comment by skraga** [comment]
@mortent I think it might be better to have it configurable with defaults to the safe option. VPA helps a lot with setting proper resources and in this case, we're forced to stop using PDB.

**Comment by michaelgugino** [comment]
The current state of the world (as of kube 1.20 I believe) is that if one or more pods are disrupted AND you have enough healthy replicas according to the PDB (eg, 1 pod in crashloop, 2 healthy, PDB configured to allow 1 disruption), you can successfully drain a node with the crashing pod.

If you have not enough healthy pods, the entire point of PDB is to prevent pods from being drained.  The best course of action is to ensure you have other alerting or means to prevent always-crashing pods from running on the cluster.

**Comment by DaveWHarvey** [comment]
This behavior is better.   
There are two CrashLoopBackoff cases that are still interesting:

- When deleting the pod and allowing the controller to recreate will resolve the problem.   This is orthogonal to eviction. 
- Where the node itself if the cause of the pod not working.
Allow the controller define behavior on crashLoopBackoff, e.g., allow it to recreate the pod rather than the pod continually restarting, would be a better general solution.

**Comment by 2rs2ts** [comment]
@pasimoes I believe `calico-kube-controllers` has to be run with a single replica, so you should not use a PDB for it. So I think in your case you can bypass this issue.

**Comment by ehashman** [comment]
I think the crux of the issue is this:

> Pods in CrashLoopbackBackoff are effectively considered dead,

They are not. They are considered Running, and that's how the Kubelet will account for them.

>  Arguably there were other things wrong, but Pods in CrashLoopBackoff or Pending are already disrupted, so no evicting them from a draining node makes no sense.

The kubelet has no reliable way to know why they are disrupted. A Pending pod is waiting to start; it might have just been scheduled. A CrashLoopBackoff pod could have restarted for any number of reasons: failing liveness probe, disruption on the host outside of Kubernetes' control such as the OOMKiller, an application level failure, etc.

Perhaps this is a user expectation mismatch and we need to update documentation? There might be an opportunity to improve the docs or UX around PodDisruptionBudget.

/kind documentation
/help

**Comment by DaveWHarvey** [comment]
We want to evict a pod that is currently unavailable (involuntarily disrupted), and the PDB is trying to maintain a number of available pods, and actions of the unavailable pods do not affect the purpose of the PDB.   But the wording for the PDB is around not evicting when number of available pods is below some threshold, but it would make more sense if it was worded to not evict if the number of available pods is below/at some threshold if the eviction will decrease the number of available pods.

The statement that a pod in CrashLoopBackoff is running just  because kubelet says so seems is not a strong argument.

**Comment by 2rs2ts** [comment]
Yeah, why is a `CrashLoopBackOff` state considered in the `Running` phase and not the `Failed` phase? Because it will eventually try to run again to see if the container won't crash? As far as I'm concerned, if the kubelet is not currently attempting to run the containers, and the last thing that happened with the containers was them exiting with a non-0 code or being forcefully terminated, then that should be `Failed`. I think the docs would back me up here: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-phase

**Comment by johngmyers** [comment]
The main issue is whether the pod has state local to the node that would adversely affect the application were it to be lost. If so, evicting a `CrashLoopBackOff` pod outside of the budget could be undesirable. Otherwise, evicting it is desirable.

The clusters that are earlier in our deployment pipeline are much more prone to having Deployments which are in constant CrashLoopBackOff. Doing rolling updates of nodes in those clusters takes a lot of work manually terminating those busted pods.

I'm thinking an additional field in the PDB might be warranted.

There probably is also a need to add to `drain.Helper` a timeout after which eviction turns from voluntary to involuntary.

**Comment by DaveWHarvey** [comment]
So the concern is that we have say 2 pods that store state in the root filesystem or on a local SSD, and it replicates it between nodes, one pod is dead, and the other is in Crash Loop Backoff?  If the evict the latter, we will go to zero copies of the state.   If we leave it stuck, then there is opportunity for manual intervention?   
I think I agree there would need to be a new setting to enable the eviction.

**Comment by 2rs2ts** [comment]
@DaveWHarvey I would suggest using PersistentVolumes for that use case, not just because of this issue, but also because of any number of things that could cause trouble (such as sudden host failure.) That is a tangential matter for this issue, though.

**Comment by ehashman** [comment]
/remove-priority awaiting-more-evidence

> Yeah, why is a `CrashLoopBackOff` state considered in the `Running` phase and not the `Failed` phase? Because it will eventually try to run again to see if the container won't crash?

Correct. A `Failed` pod is considered terminated and will never restart.

> As far as I'm concerned, if the kubelet is not currently attempting to run the containers, and the last thing that happened with the containers was them exiting with a non-0 code or being forcefully terminated, then that should be `Failed`. I think the docs would back me up here: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-phase

I don't think this is accurate. If a pod is in `CrashLoopBackOff` the kubelet is still attempting to run containers, it's just rate limiting the process. Since the docs are misleading, I suggested we fix them.

> If `Failed` is not the right phase, I think a new phase would be needed, because `Running` is certainly not the right phase when the container is not "in the process of starting or restarting" because it's in a backoff period.

I don't think there is currently any appetite to add a new pod phase.

**Comment by 2rs2ts** [comment]
I'm all for updating the docs regardless of whatever other solution comes out of this issue!

To add on to that: from my perspective, if `kubectl get` is capable of telling me that a pod is in a `CrashLoopBackOff` state, so kubelet is also capable of seeing that information and acting upon it. If that doesn't manifest as a pod phase, so be it; that Pod in a `CrashLoopBackOff` state isn't contributing to the available replicas, no matter what we call it. It's also neither making sure that whatever local state it wrote to its host is preserved, nor is it helping preserve quorum in whatever distributed data store scheme it might be involved in.

I think if a user has the kind of HA requirements that lead them to use a PDB in the first place, and they rely on local state, then they should take advantage of things like PersistentVolumes, which in our case of the crash looping Pod would not only preserve their data, but also, if kubelet would treat that Pod as equivalent to Failed and let that Pod be evicted, could make their application auto-heal from host degradation.

Making it more cumbersome to evict problematic hosts for the sake of protecting precarious setups reliant on node local storage seems a bit strange to me. We could encourage users to choose more highly available designs *and* make it easier to get rid of degraded hosts automatically, improving everyone's 9 counts.

**Comment by DaveWHarvey** [comment]
statefulSets and deployments control the number of pods in existence.  As with Jobs, we could set the pod's restartPolicy:Never, and  that should cause the pod to terminate if it crashes, and the statefulSet should recreated it.    But unlike Jobs, statefulSets have no mechanism for controlling behavior on pod failures, and therefore it would try to create the pod forever as fast as possible.   Perhaps the right path is to enhance statefulSets/deployments to throttle pod restarts, and some of the learnings from Jobs about keeping the pod around on failure so that it can be debugged.

restartPolicy:Never allows me to say there is no interesting state on the node.

**Comment by michaelgugino** [comment]
> Making it more cumbersome to evict problematic hosts for the sake of protecting precarious setups reliant on node local storage seems a bit strange to me. We could encourage users to choose more highly available designs _and_ make it easier to get rid of degraded hosts automatically, improving everyone's 9 counts.

As of kube-1.20 (or perhaps earlier, I don't recall) you can successfully evict a crashed pod (or any other not-ready pod) as long as you have not exceeded your disruption budget.  If you have a disruption budget of 1, and 1 pod is in crash loop backoff, you can successfully evict that pod.

> We could encourage users to choose more highly available designs and make it easier to get rid of degraded hosts automatically

If you're using drain as a library in an automated controller, there's an ability to add custom pod filters to ignore pods you don't care about.  Additionally, you can also opt to use 'delete' instead of 'evict' via drain after some amount of time.  You could write a controller that deletes crash loop backoff pods after X time on your cluster. (These options are dangerous IMO).

One use case to consider: canary pods.  In OpenShift, we use pods as canaries to protect etcd quorum (which runs as static pods).  If evict were to ignore pods in CrashLoopBackoff, and we encountered some problem with our canary pods, that would allow an automated process to disrupt too many control plane hosts.  There are probably other use cases of canary pods as well.

**Comment by 2rs2ts** [comment]
>Additionally, you can also opt to use 'delete' instead of 'evict' via drain after some amount of time.

Yeah, that's what we're forced to do now when we run manual operations, but it's just annoying and a waste of time. Why wait all that time if we already know that Pod's dead?

>One use case to consider: canary pods. In OpenShift, we use pods as canaries to protect etcd quorum (which runs as static pods).

I'm not sure I understand how this is set up, especially since I don't use static pods, but as I understand it, static pods aren't managed with a replication controller or anything of the sort, so I'm not quite sure where the crashlooping pod is going to go anyway. And, it's not contributing to the etcd quorum anyway, so why would it be bad to evict it?

The way I use canary pods is to treat them as surplus for my actual replication needs, i.e. I don't select them with my PDB. They exist to tell me if the code I am rolling out is stable or not, that's it. So my perspective is very limited to that; I hope you'll be patient with me not quite grokking this use case.

**Comment by michaelgugino** [comment]
> I'm not sure I understand how this is set up, especially since I don't use static pods, but as I understand it, static pods aren't managed with a replication controller or anything of the sort

Static pods can't be drained.  We use canary pods (normal pods) that a pod-affinity scheduled to the static pods.  This in effect keeps too many static pods from being stopped (eg, a node gets automatically removed).

**Comment by liggitt** [comment]
https://github.com/kubernetes/kubernetes/pull/105296 is proposed to always allow evicting not ready pods, which (I think) would address this issue

**Comment by SergeyKanzhelev** [comment]
/remove-lifecycle stale

I am removing the stale lifecycle as this is still the issue. However as mentioned in the linked closed PR the consensus needs to be found thru the KEP process.

**Comment by 2rs2ts** [comment]
I believe that since #113375 is merged, this issue might be resolved. What do y'all think?

**Comment by liggitt** [comment]
Yes, https://github.com/kubernetes/kubernetes/pull/113375 enables resolving this as an alpha feature, by setting `spec.unhealthyPodEvictionPolicy` to `AlwaysAllow` in the PDB

https://github.com/kubernetes/enhancements/tree/master/keps/sig-apps/3017-pod-healthy-policy-for-pdb is where to track the progress of that feature to beta → GA

**Comment by liggitt** [comment]
/close
in favor of https://github.com/kubernetes/enhancements/tree/master/keps/sig-apps/3017-pod-healthy-policy-for-pdb

**Comment by tatsuhiro-t** [comment]
Thank you for fixing this long standing issue.
