### ISSUE TITLE
PD multizone tests are flaky

### ISSUE THREAD

**Issue by msau42** [kubernetes/kubernetes#72378]
**Which jobs are failing**:
gce/gke multizone/regional jobs

**Which test(s) are failing**:
Only PD tests

**Since when has it been failing**:
Around 12/21 with the 16:49 run

**Testgrid link**:
https://k8s-testgrid.appspot.com/sig-storage#gce-multizone

**Reason for failure**:
TBD

**Anything else we need to know**:

/kind failing-test

**Comment by msau42** [comment]
@kubernetes/sig-storage-test-failures

**Comment by msau42** [comment]
The runs started flaking after https://github.com/kubernetes/kubernetes/pull/70862 merged. cc @pohly @verult 

Here's one failing run:
https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-multizone/26745

Pod pod-subpath-test-gcepd-dynamicpv-pfsm failed to schedule because of conflicting node selectors:
```
I1227 19:03:12.381780       1 factory.go:1102] Unable to schedule volumes-5284/pod-subpath-test-gcepd-dynamicpv-pfsm: no fit: 0/10 nodes are available: 1 node(s) were unschedulable, 3 node(s) had volume node affinity conflict, 6 node(s) didn't match node selector.; waiting
```

We shouldn't need to set the node selector for PD tests using PVs.

**Comment by pohly** [comment]
The PR broke the subpath test because the modification to the config struct embedded in the driver info now persists across tests:
https://github.com/kubernetes/kubernetes/blob/a9c7dfba51a36959ccab0301c868bf622bad11d2/test/e2e/storage/drivers/in_tree.go#L1250-L1255

A quick fix would be to reset that field in CreateDriver. The long-term fix is the change discussed in https://github.com/kubernetes/kubernetes/issues/72288

My preference is to do the quick fix now, then either merge or close PRs in this order:
* https://github.com/kubernetes/kubernetes/pull/70992 (needs a decision about logging of tests that aren't getting defined, see https://github.com/kubernetes/kubernetes/pull/70992#discussion_r243769787)
* https://github.com/kubernetes/kubernetes/pull/72002
* a future PR for https://github.com/kubernetes/kubernetes/issues/72288

What I'd like to avoid is having to rebase PR #70992 on top of the long-term solution for issue #72288 - that'll be lots of code conflicts.

**Comment by pohly** [comment]
/assign

PR is here: PR #72410
