### ISSUE TITLE
CSI plugin registration problem after kublet restarts

### ISSUE THREAD

**Issue by jingxu97** [kubernetes/kubernetes#72500]
After kubelet restarts, CSI plugin might not be re-registered soon. This cause a problem for volume reconstruction procedure. When kubelet found some mounts that need to be cleaned up, it will fail to do so because driver is not registered yet. 
```
reconciler.go:429] Reconciler sync states: could not find information (PID: d302836e-0255-11e9-8683-42010a800002) (Volume SpecName: pvc-cd03c7e0-0255-11e9-8683-42010a800002) in desired state, clean up the mount points

csi_plugin.go:359] kubernetes.io/csi: setting up unmounter for [name=pvc-cd03c7e0-0255-11e9-8683-42010a800002, podUID=d302836e-0255-11e9-8683-42010a800002

reconciler.go:442] volumeHandler.UnmountVolumeHandler for UnmountVolume failed for volume "" (UniqueName: "pvc-cd03c7e0-0255-11e9-8683-42010a800002") pod "d302836e-0255-11e9-8683-42010a800002" (UID: "d302836e-0255-11e9-8683-42010a800002") : UnmountVolume.NewUnmounter failed for volume "" (UniqueName: "pvc-cd03c7e0-0255-11e9-8683-42010a800002") pod "d302836e-0255-11e9-8683-42010a800002" (UID: "d302836e-0255-11e9-8683-42010a800002") : driver name pd.csi.storage.gke.io not found in the list of registered CSI drivers
```

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/kind bug

**Comment by jingxu97** [comment]
cc @msau42

**Comment by msau42** [comment]
One possible solution is to run reconstruction on only the csi driver at the end of the registration callback.  And in the normal reconstruction case, skip any csi plugins

@kubernetes/sig-storage-bugs

**Comment by msau42** [comment]
FYI all the CSI reconstruction tests are failing: https://k8s-testgrid.appspot.com/sig-storage-kubernetes#gce-serial

**Comment by saad-ali** [comment]
Possible link: https://github.com/kubernetes/kubernetes/pull/72008

**Comment by msau42** [comment]
It should be noted that the tests are passing on 1.13, so it's caused by some new change in 1.14.

Also the graceful deletion tests are failing, but the force delete tests are passing.  I believe reconstruction only comes into play with force deletion.

**Comment by msau42** [comment]
I think the latest test failures are a different issue than this.  I updated #72931 with test failure details

**Comment by cofyc** [comment]
Current `reconciler.reconstructVolume` initializes [`volume.Mounter`](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/volumemanager/reconciler/reconciler.go#L505) and [`volume.BlockVolumeMapper`](https://github.com/kubernetes/kubernetes/blob/218642e84ed0e3fcfda1447c8564ba24b90c1f5a/pkg/kubelet/volumemanager/reconciler/reconciler.go#L524), but if driver of CSI plugin is not registered yet, it will fail with error. If `reconciler.reconstructVolume` fails with an error, volume mount is going to be cleaned up. It may succeed or may not succeed, which depends on its driver is registered or not at that time.

One possible solution is to delay reconstruction of CSI volume until its driver is registered (suggested by @msau42 [here](https://github.com/kubernetes/kubernetes/issues/72500#issuecomment-456925363)). But I found it is complex because in theory driver can be registered or deregistered on the fly. And IMO the real problem here is reconstruction logic depends on existence of CSI driver which I don't think is right.

Actually, information of CSI volume on the host can be reconstructed successfully without driver client. I think the best and simpler solution is to put its information into actual and desire state of the world, let reconciler of volume manager to clean up later.

To archive this, we can delay CSI client initialization, CSI plugin mounter and blockVolumeMapper can be initialized if volume information is reconstructed successfully, like other plugins. Volume manger main reconciliation loop will handle the rest.

I've created a PR trying to address this: https://github.com/kubernetes/kubernetes/pull/74652

**Comment by davidz627** [comment]
I don't think this has been resolved?
/open

**Comment by msau42** [comment]
Pr #74652 should hopefully address this issue.  It just merged this morning, so it will take some time to see if the serial tests start passing

**Comment by jingxu97** [comment]
is it resolved? 
cc @msau

**Comment by msau42** [comment]
Yes
/close
