### ISSUE TITLE
Use semantic import versioning for published staging repos

### ISSUE THREAD

**Issue by nikhita** [kubernetes/kubernetes#72638]
Published staging repos like [`kubernetes/api`](https://github.com/kubernetes/api/), etc have tags like `kubernetes-1.13.1` which correspond to the `v1.13.1` tag in `kubernetes/kubernetes`. Due to the `kubernetes-` prefix, tools like `dep` don't pick up the new version.

We could start using semantic versioning for tags in published repos as well. One way to do that (as pointed by @sttts on slack) is to have the tags as `13.0.1`. This is also a faithful representation of our compatibility guarantees.

This would require a change to the publishing-bot.

/sig api-machinery
/sig release
/area release-infra
/cc @sttts @pohly @lavalamp @deads2k @liggitt

**Comment by pohly** [comment]
I understand that each new Kubernetes release must bump the major version of the mirrored repos, because in each major release new features might have been added and there might have been breaking API changes.

Is that what is meant with the compatibility guarante, i.e. it is not about the compatibility of some Kubernetes client built using these repos and the next Kubernetes release?

I'm fine with using 13.0.1, I'm just trying to understand.

**Comment by neolit123** [comment]
>  repos like kubernetes/api, etc have tags like kubernetes-1.13.1 which correspond to the v1.13.1 tag in kubernetes/kubernetes

this ain't good.

>  is to have the tags as 13.0.1

and it will break once 2.0.0 is out?

**Comment by pohly** [comment]
When k8s 2.0.0 comes along, the mirrored repos can switch to 100.0.0 and then increment major by one for following releases.

**Comment by neolit123** [comment]
> We could start using semantic versioning for tags in published repos as well. One way to do that (as pointed by sttts on slack) is to have the tags as 13.0.1. This is also a faithful representation of our compatibility guarantees.

one question i had there is what happens once the k8s MAJOR becomes 2.

**Comment by nikhita** [comment]
> one question i had there is what happens once the k8s MAJOR becomes 2.

I believe the idea is `v215.0.1` for `v2.15.1` of k/k. cc @sttts

**Comment by nikhita** [comment]
xref https://github.com/kubernetes/publishing-bot/pull/196

**Comment by neolit123** [comment]
given k/k is not following semver directly (breaking api changes for MINOR), i don't see why we should diverge the staging repos to comply with semver and have different tags - i.e. why not simply do 1to1 mapping and have breaking API changes in MINORs there too?

**Comment by nikhita** [comment]
> why not simply do 1to1 mapping and have breaking API changes in MINORs there too?

k/k is not expected to be imported directly so it doesn't matter if it doesn't respect semver. However, the published repos are expected to be imported and if we want to use semantic versioning with versioned imports for it, we need to respect semver because versioned imports will have the major version in the import paths. And users will be expected to update their import paths only when there are breaking changes.

**Comment by neolit123** [comment]
i see, so it's a problem with the semantic MAJOR imports go does.
in any case, `v215.0.1` or `15.0.1` will surely end up as being confusing.

**Comment by pohly** [comment]
This leads to the next question: will the published packages use versioned imports themselves?

If I import one package, the expectation is that it imports the correct version of all its dependencies.

**Comment by neolit123** [comment]
if someone starts doing `v15/` imports it means they have to update their imports on a much higher rate because this `v15` maps to a MINOR behind the lines that updates every 3 months.

the diffs for such changes will be big and frequent.

versioned imports have the benefits of mixing APIs and code from different MAJORs, but do we have use cases for that outside of core (v1)? the alternative the users have here is pinning at the `go.mod` side, which is certainly less flexible.

**Comment by nikhita** [comment]
> If I import one package, the expectation is that it imports the correct version of all its dependencies.

Yes, this is the intention.

> if someone starts doing v15/ imports it means they have to update their imports on a much higher rate because this v15 maps to a MINOR behind the lines that updates every 3 months.

This is true, such is the curse of versioned imports and a faster release cycle. :)

Experimenting in https://github.com/kubernetes/publishing-bot/pull/196 to figure out how disruptive versioned imports could be.

> versioned imports have the benefits of mixing APIs and code from different MAJORs, but do we have use cases for that outside of core (v1)? 

Honestly, I'm not sure how useful combining different major versions will be for our repos since a bunch of them use global variables and things can quickly get :fire: with them. I think the biggest benefit will be to seamlessly work with go modules.

Having said that, we will publish two tags for each tag of k/k - one with versioned imports and one without them.

**Comment by dims** [comment]
@liggitt @sttts WDYT?

**Comment by nikhita** [comment]
xref https://github.com/kubernetes/client-go/issues/631

**Comment by justaugustus** [comment]
@nikhita -- Is this still relevant?

**Comment by xmudrii** [comment]
Currently, there are no plans for implementing this. It has been decided to leave the issue open to avoid duplicates. Ref: https://kubernetes.slack.com/archives/CJH2GBF7Y/p1600779436038700?thread_ts=1600768354.032500&cid=CJH2GBF7Y

**Comment by pohly** [comment]
I vaguely remember a plan (or at least the intention) to ensure that different tags really reference different commits. Do I remember correctly and is that still planned even if the bigger changes around semantic versioning don't get implemented?

Right now it can happen that v0.20.0 and v0.21.0-beta.1 (or so - I'm making this specific example up) reference the same commit if nothing in the code changed. This becomes confusing during code review because then `go get foo@v0.20.0` records `foo` as being imported from `v0.21.0-beta.1` in go.mod.

**Comment by justaugustus** [comment]
@kubernetes/publishing-bot-reviewers -- is this still something we'd like to pursue?

**Comment by dims** [comment]
probably not!

/close
