### ISSUE TITLE
Different outputs from kubectl rollout history deployment (for different output formats) 

### ISSUE THREAD

**Issue by hawran** [kubernetes/kubernetes#72782]
/sig cli

**What happened**:
Hi,
I've been experiencing strange behaviour of the `kubectl rollout history deployment` command with different output formats set up.
Based on the state as follows:
```
$ kubectl rollout history deployment XXX
deployment.extensions/XXX 
REVISION  CHANGE-CAUSE
39        kubectl apply --record=true --filename=/builds/Y/XXX/deployment/kubernetes/
40        kubectl apply --record=true --filename=/builds/Y/XXX/deployment/kubernetes/
41        kubectl apply --record=true --filename=/builds/Y/XXX/deployment/kubernetes/
$
```
I'm getting strange outputs (a pod with two containers, just snippets):
```
$ kubectl rollout history deployment XXX --revision=40|egrep 'revision|cpu'
deployment.extensions/XXX with revision #40
      cpu:      1
      cpu:      1
      cpu:      500m
      cpu:      500m
$
```
vs. (note different values)
```
$ kubectl rollout history deployment XXX --revision=40 -oyaml|egrep 'revision|cpu'
    deployment.kubernetes.io/revision: "41"
            cpu: 400m
            cpu: 200m
            cpu: 400m
            cpu: 200m
$

```
and
```
$ kubectl rollout history deployment XXX --revision=40 -ojson|egrep 'revision|cpu'
            "deployment.kubernetes.io/revision": "41",
                                "cpu": "400m",
                                "cpu": "200m",
                                "cpu": "400m",
                                "cpu": "200m",
$
```

vs. (correct values)
```
$ kubectl rollout history deployment XXX --revision=41|egrep 'revision|cpu'
deployment.extensions/XXX with revision #41
      cpu:      400m
      cpu:      200m
      cpu:      400m
      cpu:      200m
$
```
vs.
```
$ kubectl rollout history deployment XXX --revision=41 -ojson|egrep 'revision|cpu'
            "deployment.kubernetes.io/revision": "41",
                                "cpu": "400m",
                                "cpu": "200m",
                                "cpu": "400m",
                                "cpu": "200m",
$
```
where really (the deployment in use)
```
$ kubectl get deployment XXX -oyaml|egrep 'revision|cpu'
    deployment.kubernetes.io/revision: "41"
            cpu: 400m
            cpu: 200m
            cpu: 400m
            cpu: 200m
$
```
and
```
$ kubectl get deployment XXX -ojson|egrep 'revision|cpu'
            "deployment.kubernetes.io/revision": "41",
                                "cpu": "400m",
                                "cpu": "200m",
                                "cpu": "400m",
                                "cpu": "200m",
$
```

**What you expected to happen**:
I would expect same values for same revisions, regardless of the output format.
Or what am I missing?

**How to reproduce it (as minimally and precisely as possible)**:
Deploy a couple of deployments and try to get info about deployment's revisions.

**Anything else we need to know?**:
This behaviour is same for all older deployments (with the output format specification).

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.4-dirty", GitCommit:"f49fa022dbe63faafd0da106ef7e05a29721d3f1", GitTreeState:"dirty", BuildDate:"2018-12-18T07:57:52Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.6", GitCommit:"a21fdbd78dde8f5447f5f6c331f7eb6f80bd684e", GitTreeState:"clean", BuildDate:"2018-07-26T10:04:08Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
N/A
- OS (e.g. from /etc/os-release):
Ubuntu 16.04.3 LTS
- Kernel (e.g. `uname -a`):
4.14.40-infra (customised)
- Install tools:
N/A
- Others:

**Comment by hawran** [comment]
Have I missed anything?

**Comment by juborto** [comment]
I experienced the same issue. I suppose that the `revision` number is not taking into account when the format option `-o` is passed also, and the result is always given on the latest revision loaded.

**Comment by hawran** [comment]
> I experienced the same issue. I suppose that the `revision` number is not taking into account when the format option `-o` is also given, and the result is always displayed for the latest revision loaded.

Which is pretty confusing.
The question is: _Is it a feature or a bug_?

**Comment by hawran** [comment]
As have been asked:
_The question is: Is it a feature or a bug?_
/remove-lifecycle stale

**Comment by hawran** [comment]
Oops, closed unintentionally, sorry for the mess.

**Comment by Duerno** [comment]
I am experiencing the same issue here 😕 
Kubernetes version:
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.7", GitCommit:"65ecaf0671341311ce6aea0edab46ee69f65d59e", GitTreeState:"clean", BuildDate:"2019-01-24T19:22:45Z", GoVersion:"go1.10.7", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by odacremolbap** [comment]
This one might be tricky to tackle.

Revisions are saved as `ReplicaSets` owned by the `Deployment`. Returning the latest version when asking for the deployment full data, be it JSON or YAML, is the only right  approach since there is no other deployment revision stored.

When using the `NamePrint` (non JSON, YAML, template), the deployment replicasets are being retrieved and the template object for the matching revision is used for printing the output:

https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/kubectl/pkg/polymorphichelpers/history.go#L123

It wouldn't sound right for the revision output using the JSON, YAML, template printer to:
- Output a `Pod` template.
- Output a `ReplicaSet` (although this would be the closest to having all the information you may need, but returning this object in a rollout context might sound confusing)
- Output the latest `Deployment` which is the current behaviour.

I don't think `kubectl rollout history deployment/my-deployment --revision 40 -oyaml` should be bringing any extra data we are not already retrieving from that same command without the YAML formatter.

I would say to make `--revision` not compatible with `-o{yaml|json|...}`

**Comment by halfvector** [comment]
Running into this same issue. This output is needed to identify the configuration change introduced by a deployment.

If the `-o{yaml|json|...}` flag is not going to be supported on the `rollout history` command, then `kubectl get deployment/my-deployment --revision 40 -o yaml` could be an intuitive alternative to support this use-case.

**Comment by yonran** [comment]
I ran into this bug today when I tried to find out which revision rolled out a particular `image`. Since `kubectl rollout history` does not support `-o`, you have to get this information from the ReplicaSet. Here is my command to create a table of rollout history including the `image`: `kubectl get ReplicaSet -l $(kubectl get deploy $DEPLOYMENT -o json | jq '.spec.selector.matchLabels | to_entries | [.[] | "\(.key)=\(.value)"] | join(",")' -r) -o custom-columns="REVISION:{.metadata.annotations['deployment\.kubernetes\.io/revision']},IMAGE:{.spec.template.spec.containers[0].image}" --sort-by="{.metadata.annotations['deployment\.kubernetes\.io/revision']}"`
