### ISSUE TITLE
Horizontal Pod Autoscaler should use resource limit as its base for calculation

### ISSUE THREAD

**Issue by zq-david-wang** [kubernetes/kubernetes#72811]
**What would you like to be added**:
I hope hpa could make its calculation based on resource limit.
**Why is this needed**:
HPA is all about scale up/down at runtime, it is counter-intuitive to calculate target based on resource request.  If request is 50% of limit, a 80% percent hpa target would trigger scale up when average usage is over 40% limit....

**Comment by Fleuri** [comment]
Yes, this would also help optimizing the resource usage as there would be no need to request resources as buffer for scaling.

**Comment by mossuchida** [comment]
I am experimenting VPA (vertical pod autoscaler) with HPA.  The issue is that VPA changes resource requests up & down, which messes up HPA as HPA is based on resource request (sometimes VPA sets resource request very low like 25m when it is not used for a long time.  When suddenly the app is used, it starts using over 250m cpu, then HPA thinks it is 1000% of 25m, then scales up to the max allowed number of pods.  but actually HPA to scale out when resource request is 80% of 1000m for Node app).  Default scheduler also uses resource request to schedule a pod to be deployed on the best node, VPA & default scheduler are in sync.  so, if HPA uses resource limit, it will solve the compatibility issue with VPA.  I would like this change or it should be configurable so that user can choose to use resource limit instead.

**Comment by WandersonAlves** [comment]
+1, currently my services are growing like crazy, so i removed all my HPA's, and resources requests/limits.

**Comment by Lemmork** [comment]
Is there any workaround for this problem? I was wondering why my pods scale up with no traffic. Now I know why.

**Comment by WandersonAlves** [comment]
+1

This Is a critical issue, and kubernetes are used by everyone, so...how people deal with this?

**Comment by yiqian987** [comment]
Yes, I also encountered this problem because the reserved value is often less than the limit value.

**Comment by diegosucaria** [comment]
In case this helps someone:

You can put any % value in the autoscaler...  
for example, you can set a resource request of **100m** and set the autoscaler to **500%**
that will create new pods when the CPU usage is 500m.

btw, I think the autoscaler should use the limit too.

**Comment by AdityaBhansali1** [comment]
Fully agree with this. It is more intuitive to calculate the targets as a percentage of limits because a service should be scaled when approaching the limits.

Setting the right limit in current form needs a calculation based on resource requests and limits both. It can be simplified by just needing to calculate based on one variable ( which is the limits ).

**Comment by kong62** [comment]
+1. Hpa based on request is very tasteless!

**Comment by Leulz** [comment]
To add to this: if you have a container using CPU requests different from its CPU limits, the HPA using the requests makes no sense. After all, if requests != limits, we want the CPU usage to be able to surpass the CPU requests.

But if the HPA will scale up based on CPU requests, then the horizontal scaling will be done without allowing the container to be able to deal with its workload normally by using more CPU than it has requested.

**Comment by dewanymca** [comment]
Is there any update on this, we are also struggling with this and HPA kicking based on request looks bit weird.

**Comment by meezaan** [comment]
I haven't written or looked at the Kubernetes code, but I imagine because pods are scheduled based on requests, scaling on limits may not make a lot of sense and will certainly not be very trivial.

As I understand from having read about this over the last many weeks and tried many different variations over the last couple of years, the limit should be there for you to be able to handle a traffic burst for long enough to spin up more pods.

For instance, you might set request to 100m and limit to 250m. Set HPA to 200% cpu utilisation - this way the pods will scale when CPU usage hits 200m. My experience has been that this has resulted in more efficient use of the nodes across the cluster as opposed to setting both request and limit to 250m and scaling at 75% CPU utilisation. With requests at 100m, I can spin up more pods faster when HPA kicks in (because with the same infrastructure I have more free capacity) and at the same time it allows some time for an existing VM to come up and join the cluster for more capacity.

**Comment by Lanpice** [comment]
It’s been almost two years, using resource limit for calculation is still not supported...

**Comment by lceni** [comment]
As @meezaan mentioned above, it makes sense for me as well to set HPA utilization higher than 100%, limits are basically there to make your system to support bursts, until k8s spins more pods.

**Comment by jmcdonagh** [comment]
I honestly cannot even wrap my head around why anyone would base the scale out around requests... requests is supposed to be set to the bare minimum to run a service. Makes it conceptually difficult to reason about this thing when you go look and you're saying scale out when it's at 500%.

**Comment by m1o1** [comment]
We did a workaround by taking the desired limit utilization (say 60%) and multiplying by (resource_limit / resource_request). Our quantities are small enough to do `resLimit.MilliValue() / resRequest.MilliValue()` without worrying about MilliValue overflowing the int64. This sets the target utilization in HPA above 100% but seems to translate properly to the percentage of the limit.

**Comment by indera-shsp** [comment]
But the limit is not guaranteed to be reached if there are no resources available to the OS, so your pod might never scale even if there is a spike in resource needs - this might explain why this ticket will be never fixed.

**Comment by zq-david-wang** [comment]
Guys, this is not a right or wrong issue,  I raise the issue because I feel  counter-intuitive to use request as a base for calculation,
The formula is quite clear, it makes no sense to argue which one is wrong-er....  @indera-shsp   using request as base for calculation would not make different,  you can set a value bigger than 100%

As for counter-intuitive, my reasoning is that request is hardly observable during runtime in most setup, and hpa is all about runtime behavior, using limit make "me" feel more comfortable . (I do notice there were some setup where cpu share would be used as a capacity, JVM?.)

**Comment by indera-shsp** [comment]
@zq-david-wang Can you please explain what you mean by `request is hardly observable during runtime`?

Request is the only measure respected at runtime by kubernetes.

**Comment by zq-david-wang** [comment]
Application's **runtime** starts **after** its request is "respected" by k8s  @indera-shsp (If k8s denies, the application just do not run)
You can observer application's cpu usage reach its limit, but how could you tell  where the request is? cpu share only take effect when a cpu core is saturated and it  happens per cpu core, meaning requesting 1cpu does not guarantee your  1 cpu resources.  

The best practice for setting up the request/limit is out of the scope of this discussion, I think there would be tons of discussions out there.

**Comment by indera-shsp** [comment]
@zq-david-wang are you using any metrics? metrics can show what the actual usage is when the application runs
https://itnext.io/k8s-monitor-pod-cpu-and-memory-usage-with-prometheus-28eec6d84729

**Comment by sechunOH** [comment]
I think about this for a while with cluster-autoscaler together.

CA may manages increase of cluster nodes with resource requests. 
( = new pod will be in pending state if there is no enough resource. k8s maybe determine it with request)

If hpa manages scaling with resource limits, no pod horizontal scaling occurs when all the resources of node are used, because pods cannot use more resource upto limit. (just upto request) The nearer to the node's resource capacity sum of pods resource usage is, the harder increase of pod replica is I think.

For example, I have a node (4G mem) and my pods have resource request of momory is 1G, limit of memory is 2G.
My hpa resource is defined with 75% avg memory usage. If hpa use request limit, pod increase occurs when first pod use 1.5G. If there are already upto 4, pods cannot use more memory upto limit because there is no enough resource.
If you use cloud provider and cluster autoscaler, it may increase a node to a cluster and run a pod on that node. But it is difficult to reach upto 75% of avg memory usage because pods in first node cannot use more memory above its request memory.

How do guys think about it? Please let me get some opinions of your. 
It is not easy for me to define HPA as there are many argues about it.

**Comment by debu99** [comment]
Another use case,  java application -XX:MaxRAMPercentag is based on the limit memory resource, so which means if the gap between request resource and limit resource is large like 1:1.5, then the HPA is useless as that HPA will scale to maximum easily due to heap size

**Comment by rennokki** [comment]
2021 and this is still an issue. I have to set requests values too much more than needed and I have spare computing power that I don't use because of that. Congrats Kubernetes, something broke that got ignored. 👍

**Comment by fengchenghu** [comment]
+1

**Comment by Warxcell** [comment]
> 2021 and this is still an issue. I have to set requests values too much more than needed and I have spare computing power that I don't use because of that. Congrats Kubernetes, something broke that got ignored. +1

Use >100%, as suggested above. You can achieve same thing.

**Comment by Elyytscha** [comment]
well weird, but i'm fine with cpu requests: 100m, cpu limit: 1, autoscaling percentage: 850 (85% before limit will throttle) :D

**Comment by LinkMaq** [comment]
Most of the time we set a few cpu.request for pods , and set a reasonable value to cpu.limit.  we expect the application to auto-scale during runtime based on actual cpu percentage（cpu.usage / cpu.limit).

This is more intuition for users.(come on, don't discuss whether to use >100% )

**Comment by Hello-Linux** [comment]
I think cpu/mem percentage in HPA should be based on limits!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!11

**Comment by Hello-Linux** [comment]
@kipusoep @Lemmork @Lanpice @Fleuri @meezaan

**Comment by Hello-Linux** [comment]
Hurry up and add this function, it's been many years, and it hasn't been done yet

**Comment by kipusoep** [comment]
@Hello-Linux mate calm your tits. You're shouting and telling people what to do, that's totally not cool and not how you should treat people.

**Comment by RafaelHGBotelho** [comment]
@kipusoep I'm looking for a way to be able to help, even at the moment I don't know exactly how to do it. I started by reading all the documentation regarding the HPA here. 

https://github.com/kubernetes/community/blob/master/sig-autoscaling/README.md

In addition, it would be important to participate in the meetings to get a sense of what is being discussed at the moment. Anything we can do to add, will certainly be welcome. Remembering that the open source community are not our employees, if we want something ready as soon as possible, we must look for a way to start the movement ourselves.

**Comment by RafaelHGBotelho** [comment]
I did a lot of research to understand why the HPA is based on request and not on limit. I even started studying Golang in order to understand the code better.

Reading some articles and the comments on Slack's #sig-autoscaling, I understand why.

https://github.com/kubernetes/design-proposals-archive/blob/8da1442ea29adccea40693357d04727127e045ed/node/resource-qos.md#compressible-resource-guaranteess

_If a pod is successfully scheduled, the container is guaranteed the amount of resources requested. Scheduling is based on requests and not limits._

_Excess CPU resources will be distributed based on the amount of CPU requested._

**ringtail** answered that question for @zq-david-wang on Slack.

_@zq-david-wang because request works for scheduling and limit works for killing. In fact limit can not be perceived by kube-scheduler._

The **hubt** answered too.

_the pod request is also used as a cluster scheduling reservation._

Analyzing all this, reading other articles and comments, it really made much more sense to use the HPA considering the request and not the limit.

For example:

I have 1 Node with 10CPU, considering that my Pod needs 1CPU to work, I can configure a 1CPU request. The K8s will allocate this 1CPU to the Pod, regardless of whether it is actually being used by the Pod.

Being 1CPU = 100%, if I need it to scale when it gets to 0.9CPU, I set the HPA to 90%. If I need it to scale when I get to 2CPU, I set the HPA to 200%.

What confused me a lot was the fact that I didn't know exactly how much I could increase the consumption of the Pod. But over time the application becomes more mature, and you begin to understand exactly what consumption is needed. It is not even a good thing to configure limits for CPU, I leave the text below as reading on this subject. One more reason why the HPA is not used considering the limit, but the resquest.

https://home.robusta.dev/blog/stop-using-cpu-limits/

*If I'm wrong in the interpretation, please correct me. I hope it can help someone.

**Comment by zq-david-wang** [comment]
Actually, The cpu request based on cgroup v1 is not "guaranteed",  k8s official doc is kind of misleading,  cpu request based on cgroup v1 would set  cpu.shares accordingly, but cpu.shares in kernel is used for calculation on each cpu core seperately, not the whole.  A pod which requests 1cpu would get way less cpu than another pod which also requests 1cpu when all cpus are fully utilized, if those pod manage quite different number of tasks.  (The pod with less tasks would have its share cut out by other pods, cgoup v2 seems to fix this issue.)

**Comment by will-molloy** [comment]
I don't think you're understanding limit/request correctly.

Limits are there for bursty loads (expensive startup, lag in scaling, etc.). The pods aren't even guaranteed to get the limit cpu/mem, only the requested. Limit is only given if the underlying node has enough resources, so you can't rely on it.

That's why it scales based on request and why its commonly recommended to set limit = request.

**Comment by ndunks** [comment]
FYI, you can set the `averageUtilization` above 100%, describe on HPA and you will find the current/target value:
![image](https://user-images.githubusercontent.com/5500313/198945329-d89034e8-f813-4d79-9e7d-e488b0e0001e.png)

**Comment by xiaoping378** [comment]
为了说服自己，我是这么理解的，request是影响调度的，如果从节点的角度看，比如说cpu的资源紧张了，pod按request算利用率也比较高了，那意味着cpu已经快超分了，业务的pod为了不被cpu限流，应该扩容新的pod出来（新增pod到别的节点上）。

**Comment by meezaan** [comment]
> > I don't think you're understanding limit/request correctly.
> 
> > 
> 
> > Limits are there for bursty loads (expensive startup, lag in scaling, etc.). The pods aren't even guaranteed to get the limit cpu/mem, only the requested. Limit is only given if the underlying node has enough resources, so you can't rely on it.
> 
> > 
> 
> > That's why it scales based on request and why its commonly recommended to set limit = request.
> 
> 
> 
> what about the situation when a container consumes a lot of resources at creation and during the normal work doesn't consumes much, but the requests are much higher then a container is really allocates? In this case we have a waste of resources which are allocated by requests but not really used.
 
This sounds like a problem that needs to be fixed outside of the container.

**Comment by haorenfsa** [comment]
But why can't we support both of them?
I mean we could add a metric type like `UtilizationOfLimit` compared to current `Utilization`. Wouldn’t that be better? we could all get what we want.

**Comment by meezaan** [comment]
> But why can't we support both of them?
> 
> I mean we could add a metric type like `UtilizationOfLimit` compared to current `Utilization`. Wouldn’t that be better? we could all get what we want.

Perhaps unrelated to specifically this, but wanting is the root of all the problems. We all need to look to our needs and be grateful that they get fulfilled, always.

This has really, at least, helped me simplify life.
