### ISSUE TITLE
why need different cgroup path between cgroupfs and systemd

### ISSUE THREAD

**Issue by yanghaichao12** [kubernetes/kubernetes#72853]
@dashpole yesterday,i switch cgroup-driver from cgroupfs to systemd for kubelet and docker,but always got this info:
`Jan 12 15:03:25 host-10-47-223-19 kubelet: F0112 15:03:25.286483   28583 kubelet.go:1374] Failed to start ContainerManager Failed to enforce Kube Reserved Cgroup Limits on "/kubelet.slice": "/kubelet.slice" cgroup does not exist`
my part cofiguration of kubelet is like this
`--kube-reserved-cgroup=/kubelet.slice`
and  i'm very sure there are the directory "kubelet.slice" in every cgroup subsystem path.
then i view  codes and find the sections :
![image](https://user-images.githubusercontent.com/20693362/51070777-c8627a00-1681-11e9-8d5b-a737132a459f.png)
so i modified my kubelet configeration:
`--kube-reserved-cgroup=/kubelet`
then everything is well.

so ,my question is why the  systemd and cgroupfs  use different paths? and do you know more differences between them？could you tell me？
thanks a lot！

**Comment by dashpole** [comment]
The "name" of the systemd unit is what precedes `.slice`.  See https://www.freedesktop.org/software/systemd/man/systemd.slice.html#.  `.slice` is the type of systemd unit.  I'm not sure why we decided to use the name instead of the literal cgroupfs path, though.  cc @filbranden, if he knows more details on that.

**Comment by yanghaichao12** [comment]
@dashpole i think the error information is misleading when we use 'systemd':
`Jan 12 15:03:25 host-10-47-223-19 kubelet: F0112 15:03:25.286483 28583 kubelet.go:1374] Failed to start ContainerManager Failed to enforce Kube Reserved Cgroup Limits on "/kubelet.slice": "/kubelet.slice" cgroup does not exist`
in fact the missing path isn't '/kubelet.slice' but '/kubelet.slice.slice' when '--kube-reserved-cgroup=/kubelet.slice'. i found the section:
![image](https://user-images.githubusercontent.com/20693362/51178233-f30c3700-18fc-11e9-9cdc-3d3ef2e8c12d.png)
if set '--v=5', we'll see the correct path. do you think if the log level is too high, or should we use 'glog.Error' directely?

**Comment by filbranden** [comment]
To answer the question: We keep an internal name (which I actually recently converted into a slice of strings) for the cgroup path since libcontainer uses two separate interfaces and naming for cgroupfs vs. systemd and we didn't want these implementation details to leak *everywhere* in our source code.

So we actually represent cgroup `/kubepods.slice/burstable.slice/pod-XYZ.slice/container-ABC.scope` as `[]string{"kubepods", "burstable", "pod-XYZ", "container-ABC"}` internally, and only care about cgroupfs or systemd in our own ContainerManager abstraction, which is the only place where this slice of strings is converted into a cgroupfs/systemd name and back.

For that reason, we try to take (in `--kube-reserved-cgroup`) and print (in logs outside of ContainerManager) a representation of our internal name, that doesn't include the systemd suffixes. It turns out our representation is *basically* just cgroupfs.

So I can see why this causes some confusion... But I still think leaking the detail of which cgroup implementation is in use to these logs is the wrong approach... (i.e. complaining about `/kubelet.slice.slice` here looks wrong to me.)

I think we'll end up seeing more work in this area, particularly in making libcontainer more robust, so we might be able to address some of these in the future, as the code gets refactored to deal with that. There hasn't been much movement in that area though, so not sure when that will actually materialize.

Cheers,
Filipe

**Comment by yanghaichao12** [comment]
ok，i understand, thank you :)
