### ISSUE TITLE
setting quotas while creating a pod fails

### ISSUE THREAD

**Issue by donfranio** [kubernetes/kubernetes#72878]
**What happened**:
A pod of my deployment suddenly doesn't come up again and hangs in "CrashLoopBackOff"

**What you expected to happen**:
When a pod of a deployment is killed for some reason, I expect it to come up again.

**How to reproduce it (as minimally and precisely as possible)**:
This only happens sometimes and cannot be reproduced dependably, I am still trying ...

**Anything else we need to know?**:
kubectl describe pod shows this error-message:
```OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"process_linux.go:367: setting cgroup config for procHooks process caused \\\"failed to write 200000 to cpu.cfs_quota_us: write /sys/fs/cgroup/cpu,cpuacct/container.slice/kubepods/burstable/pod6ba8075b-132e-11e9-ab2e-246e9674888c/a5f752a5a36fafeab7f16beb4763521cf2370efc3ba961e85a8ac1faef721b48/cpu.cfs_quota_us: invalid argument\\\"\"": unknown```

**Environment**:
- Kubernetes version (use `kubectl version`): Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.3", GitCommit:"435f92c719f279a3a67808c80521ea17d5715c66", GitTreeState:"clean", BuildDate:"2018-11-26T12:46:57Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration: Hardware
- OS (e.g. from /etc/os-release): coreos 1967.3.0
- Kernel (e.g. `uname -a`): 4.14.88
- Install tools: terraform
- Others:

**Comment by donfranio** [comment]
Btw: there is a ResourceQuota in place:
```
apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
spec:
  hard:
    cpu: "20"
    memory: 130Gi
    services: "20"
```

**Comment by ghouscht** [comment]
We experience the same issue with k8s 1.14.1 installed with kubeadm and docker as cri:
```
Error: failed to start container "kube-flannel": Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:424: container init caused \"process_linux.go:390: setting cgroup config for procHooks process caused \\\"failed to write 5000 to cpu.cfs_period_us: write /sys/fs/cgroup/cpu,cpuacct/kubepods.slice/kubepods-pode7dac811_5d23_11e9_8ff8_005056935735.slice/docker-kube-flannel.scope/cpu.cfs_period_us: invalid argument\\\"\"": unknown
```

The problem seems to be related in the combination of setting a custom `cpuCFSQuotaPeriod` (in our case 5ms) and the use of `systemd` as cgroup driver. As soon as I reconfigure docker to use cgroupfs and redeploy the cluster everything works as I would expect.

/var/lib/kubelet/kubeadm-flags.env:
```
KUBELET_KUBEADM_ARGS=--cgroup-driver=systemd --network-plugin=cni 
```

docker config as described [here](https://kubernetes.io/docs/setup/cri/#docker):
```
{
  "exec-opts": ["native.cgroupdriver=systemd"],
  "bip": "10.127.1.1/24",
  "log-opts": {
    "max-size": "2g"
  },
  "storage-driver": "overlay2",
  "storage-opts": [
    "overlay2.override_kernel_check=true"
  ]
}
```

**Comment by joshk0** [comment]
We're still experiencing this in GKE 1.12 at our company. refreshing the issue

**Comment by joshk0** [comment]
```
oci runtime error: container_linux.go:247: starting container process caused "process_linux.go:291: setting cgroup config for ready process caused \"failed to write 100000 to cpu.cfs_period_us: write /sys/fs/cgroup/cpu,cpuacct/kubepods/pod7beb03fa-d009-11e9-a6b4-42010a800245/592ee7f21ec5021c279f87476775f041a044d4cb3c6bc70fefe967512c264c35/cpu.cfs_period_us: invalid argument\""
```

or

```
OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:424: container init caused \"process_linux.go:390: setting cgroup config for procHooks process caused \\\"failed to write 100000 to cpu.cfs_period_us: write /sys/fs/cgroup/cpu,cpuacct/kubepods/burstable/podd97b5de1-c855-11e9-828e-42010a800264/CONTAINER-NAME-REDACTED/cpu.cfs_period_us: invalid argument\\\"\""
```

**Comment by luhkevin** [comment]
We are seeing this too, on GKE 1.13.6-gke.13

**Comment by xueweiz** [comment]
Hi @joshk0 , @luhkevin ,

You might be seeing a different issue than https://github.com/kubernetes/kubernetes/issues/76704

I wonder if you could let me know your kernel version? And could you run below command on your affected node?
```
sudo find /sys/fs/cgroup -name cpu.cfs_period_us -printf "%p\t" -exec cat {} \; | grep -v 100000
```

If the command doesn't show anything, please ignore my comment.

And if this command shows any output like below, you might potentially be affected by https://lore.kernel.org/patchwork/patch/1135155/
```
/sys/fs/cgroup/cpu,cpuacct/kubepods/burstable/pod9649f0a1-e3c1-11e9-b00c-42010a8000cf/cpu.cfs_period_us	114843
```

In that case, could you then run below command and share the output? Thanks!
```
# replace the podxxxx with your folder name

sudo find /sys/fs/cgroup/cpu,cpuacct/kubepods/burstable/pod9649f0a1-e3c1-11e9-b00c-42010a8000cf/ -name cpu.cfs_*_us -printf "%p\t" -exec cat {} \;
```

**Comment by mcginne** [comment]
@xueweiz I also hit this running Kube 1.14.7.

Output from the commands you mentioned showed:
```
/var/log# sudo find /sys/fs/cgroup -name cpu.cfs_period_us -printf "%p\t" -exec cat {} \; | grep -v 100000
/sys/fs/cgroup/cpu,cpuacct/kubepods/burstable/pod4fef3676-ea69-11e9-8f45-2aa9b6c96438/46f7831bae4db89a9ce47c2919f2528c515039132de16b6761f43950e4c3e60e/cpu.cfs_period_us	20000
/sys/fs/cgroup/cpu,cpuacct/kubepods/burstable/pod238b4d27-eacf-11e9-8937-0ef046406669/9fcb1b8a52cace4fa2fa897be135a6646cad4e0a6d00ed84c77ef6e459205fff/cpu.cfs_period_us	22968
/sys/fs/cgroup/cpu,cpuacct/kubepods/burstable/pod238b4d27-eacf-11e9-8937-0ef046406669/cpu.cfs_period_us	20000
/sys/fs/cgroup/cpu,cpuacct/kubepods/burstable/pod4fefe111-ea69-11e9-8f45-2aa9b6c96438/a1986cba505c6dfdd610fd9e7bb06e9fcffcb115045bdf725a4c5bc835337e72/cpu.cfs_period_us	20000
/sys/fs/cgroup/cpu,cpuacct/kubepods/burstable/podf7c42703105208a3a084f29631cc01c3/9899a97bb9b6ea1bed5539a36f634ff920ef5202f4b8deae13d165670fa91f12/cpu.cfs_period_us	20000
/sys/fs/cgroup/cpu,cpuacct/kubepods/burstable/podf7c42703105208a3a084f29631cc01c3/514b0963491390cd50814da04e9ebcc014caf2fd7fc90470af8ef264ef9a1d52/cpu.cfs_period_us	20000
/sys/fs/cgroup/cpu,cpuacct/kubepods/besteffort/podac392997-eb32-11e9-8937-0ef046406669/a5f2494ec851b600ebbf0a9c544f11cc60212fe408efe158dbe4dec9a596c4c8/cpu.cfs_period_us	20000
```

I then ran the 2nd command against a few of them:
```
sudo find /sys/fs/cgroup/cpu,cpuacct/kubepods/burstable/pod238b4d27-eacf-11e9-8937-0ef046406669/ -name cpu.cfs_*_us -printf "%p\t" -exec cat {} \;
/sys/fs/cgroup/cpu,cpuacct/kubepods/burstable/pod238b4d27-eacf-11e9-8937-0ef046406669/6aed5052f80f85f5f35589ce9f4648dd8bd237514ccc996317f6760ea5c7adbe/cpu.cfs_quota_us	-1
/sys/fs/cgroup/cpu,cpuacct/kubepods/burstable/pod238b4d27-eacf-11e9-8937-0ef046406669/6aed5052f80f85f5f35589ce9f4648dd8bd237514ccc996317f6760ea5c7adbe/cpu.cfs_period_us	100000
/sys/fs/cgroup/cpu,cpuacct/kubepods/burstable/pod238b4d27-eacf-11e9-8937-0ef046406669/9fcb1b8a52cace4fa2fa897be135a6646cad4e0a6d00ed84c77ef6e459205fff/cpu.cfs_quota_us	6890
/sys/fs/cgroup/cpu,cpuacct/kubepods/burstable/pod238b4d27-eacf-11e9-8937-0ef046406669/9fcb1b8a52cace4fa2fa897be135a6646cad4e0a6d00ed84c77ef6e459205fff/cpu.cfs_period_us	22968
/sys/fs/cgroup/cpu,cpuacct/kubepods/burstable/pod238b4d27-eacf-11e9-8937-0ef046406669/cpu.cfs_quota_us	6000
/sys/fs/cgroup/cpu,cpuacct/kubepods/burstable/pod238b4d27-eacf-11e9-8937-0ef046406669/cpu.cfs_period_us	20000
```
And:
```
sudo find /sys/fs/cgroup/cpu,cpuacct/kubepods/burstable/pod4fef3676-ea69-11e9-8f45-2aa9b6c96438/ -name cpu.cfs_*_us -printf "%p\t" -exec cat {} \;
/sys/fs/cgroup/cpu,cpuacct/kubepods/burstable/pod4fef3676-ea69-11e9-8f45-2aa9b6c96438/15d823c3fd3b433952607fde15504df97e053b723fc55ce7ced76ed197db4235/cpu.cfs_quota_us	-1
/sys/fs/cgroup/cpu,cpuacct/kubepods/burstable/pod4fef3676-ea69-11e9-8f45-2aa9b6c96438/15d823c3fd3b433952607fde15504df97e053b723fc55ce7ced76ed197db4235/cpu.cfs_period_us	100000
/sys/fs/cgroup/cpu,cpuacct/kubepods/burstable/pod4fef3676-ea69-11e9-8f45-2aa9b6c96438/cpu.cfs_quota_us	-1
/sys/fs/cgroup/cpu,cpuacct/kubepods/burstable/pod4fef3676-ea69-11e9-8f45-2aa9b6c96438/cpu.cfs_period_us	100000
/sys/fs/cgroup/cpu,cpuacct/kubepods/burstable/pod4fef3676-ea69-11e9-8f45-2aa9b6c96438/46f7831bae4db89a9ce47c2919f2528c515039132de16b6761f43950e4c3e60e/cpu.cfs_quota_us	-1
/sys/fs/cgroup/cpu,cpuacct/kubepods/burstable/pod4fef3676-ea69-11e9-8f45-2aa9b6c96438/46f7831bae4db89a9ce47c2919f2528c515039132de16b6761f43950e4c3e60e/cpu.cfs_period_us	20000
```

Not sure if this is relevant, but I also noticed this message in kern.log several hours after I was seeing the problem:
```
Oct 10 06:21:51 test-bmeo5ju20l2ml1t8cih0-dmlarge1-default-0003d181 kernel: [81657.951153] cfs_period_timer[cpu0]: period too short, scaling up (new cfs_period_us 22968, cfs_quota_us = 6890)
```

**Comment by xueweiz** [comment]
Hi @mcginne  thanks for sharing these output! And they do confirm my theory. Basically this is not a Kubernetes bug, but a Linux kernel bug.

Yes you are right about the kernel log message, it is the culprit. It's a kernel bug caused by https://github.com/torvalds/linux/commit/2e8e19226398db8265a8e675fcc0118b9e80c9e8

I proposed this patch to fix it: https://lore.kernel.org/patchwork/patch/1135155/
The patch has just been accepted by Linux maintainers yesterday. You would probably need to talk to your OS provider to make sure that they cherry-pick this patch in their kernel.

**Comment by xueweiz** [comment]
Hi @mcginne , sorry, I took a closer look, now I'm not that sure you got affected by the bug I mentioned.
Can you show me the detail of your "OCI runtime create" failure message? Does it look like the one below?

`OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"process_linux.go:367: setting cgroup config for procHooks process caused \\\"failed to write 200000 to cpu.cfs_quota_us: write /sys/fs/cgroup/cpu,cpuacct/container.slice/kubepods/burstable/pod6ba8075b-132e-11e9-ab2e-246e9674888c/a5f752a5a36fafeab7f16beb4763521cf2370efc3ba961e85a8ac1faef721b48/cpu.cfs_quota_us: invalid argument\\\"\"": unknown`

**Comment by mcginne** [comment]
Yes, here is mine - looks very similar:
```
Message:failed to create containerd task: OCI runtime create failed: container_linux.go:346: starting container process caused "process_linux.go:449: container init caused \"process_linux.go:415: setting cgroup config for procHooks process caused \\\"failed to write 20000 to cpu.cfs_period_us: write /sys/fs/cgroup/cpu,cpuacct/kubepods/burstable/pod3e4ed5da-eaad-11e9-8937-0ef046406669/ea44991ca46b99c2c8887f83fd16ccb576b44eab1de15e4bf6e7d3a6707b63dc/cpu.cfs_period_us: invalid argument\\\"\"": unknown
```

**Comment by donnyv12** [comment]
Ran into this issue as well this morning on GKE 1.12.

**Comment by wenjun8888** [comment]
@xueweiz 
hey，we match the same promblems when we use kubernetes v1.13.4.
twice durnig six month and the second time only use 60% cpu.
the current kenerl version is 5.14 and we find the newest is 5.31
can we just use it? thanks!

**Comment by xueweiz** [comment]
Hi @wenjun8888 , the [patch](https://lore.kernel.org/patchwork/patch/1135155/) was accepted and first released in Linux kernel 5.4-rc3. See [here](https://github.com/torvalds/linux/blob/v5.4-rc3/kernel/sched/fair.c#L4934).

If you could use Linux 5.4-rc3, or somehow apply the patch to your current kernel, that might be helpful :)

**Comment by wenjun8888** [comment]
@xueweiz 
hey, i still wait the stable release which newer than 5.4-rc3。
the problem now happend everytime when we apply a new deployment.
it feel bad and can you tell me how it happend? thanks~

**Comment by xueweiz** [comment]
Hi @wenjun8888 , I described the bug+cause+fix that I was observing in this [Google Doc](https://docs.google.com/document/d/13KLD__6A935igLXpTFFomqfclATC89nAkhPOxsuKA0I/edit#heading=h.8way5x93xckx).

I am not 100% sure that you are affected by the same bug. You can try to read the doc, and see whether a similar CFS quota/period precision loss could affect you. The same bug can show up as different symptoms. Probably the easiest way, is to get a kernel having the [patch](https://lore.kernel.org/patchwork/patch/1135155/), and try it out.

And if you want to mitigate the issue, you can consider trying this [Python2 script](https://github.com/xueweiz/scripts/blob/master/fix-cfs/fix-cfs.py). It *may* help you :)

To use the script, you need to SSH into the affected node, and run it like `sudo python fix-cfs.py`. It has more options you could tune.

**Comment by wenjun8888** [comment]
@xueweiz 
thanks！ i read the doc first...

**Comment by wenjun8888** [comment]
@xueweiz 
hey，thanks a lot for your help.
i decide to install a stable kernel having the patch which you mentioned,
but i am not good at this well, could you tell me which stable kernel should i take?

**Comment by wenjun8888** [comment]
@xueweiz 
hey, i think it's the right to run your py scripts.
but it failed and this is the return:

Warning: failed to fix cfs at container_dir %s,  the directory may have disappeared.
Found a problem:
container /sys/fs/cgroup/cpu/kubepods/burstable/pod1c7fd182-fa52-11e9-b422-525400530fa1/6c52873b77877db62fb64cddbb7b4cae9cd37b6f0f7ed6d291b48668e1d98ebe has quota 114843, period 114843
Warning: failed to fix cfs at container_dir %s,  the directory may have disappeared.

**Comment by xueweiz** [comment]
Hi @wenjun8888 , sorry for the error running the scripts. I had a small bug for the newly added print statements, I just fixed it [here](https://github.com/xueweiz/scripts/commit/6bb935e52b23b97f66a7848d52fc1094628af80a). Could you try running the latest script again? Thanks! 

The `Warning:` messages are not critical failures. It basically says that "a container with a broken cfs configuration cannot be repaired, because it was removed before the repair can take place". It's very likely that kubelet/runc is creating this container, then failed to create it successfully, and the removed it.

Quick question, when you ran the script during the weekend, did it fix your problem? If not, then the bug I encountered is probably unrelated to yours.

> i decide to install a stable kernel having the patch which you mentioned,
but i am not good at this well, could you tell me which stable kernel should i take?

Sorry, I haven't requested backporting that patch to stable yet. (It on a long to-do list of mine :P )
You probably have to use a newer kernel version for now :(

If you have more question on how to get a kernel with the patch applied, I can try to help. It wouldn't be interesting for the Kubernetes community, so let's use [Email](mailto:kentxuewei@gmail.com) to for that discussion.

**Comment by xueweiz** [comment]
@donnyv12 , @joshk0 , @luhkevin ,
Could you try out the 1.13.12-gke.13 release? It uses Container-optimized OS version [cos-73-11647-329-0](https://cloud.google.com/container-optimized-os/docs/release-notes/m73#cos-73-11647-329-0), which has the fix for [a bug that we observed](https://docs.google.com/document/d/13KLD__6A935igLXpTFFomqfclATC89nAkhPOxsuKA0I/edit#heading=h.8way5x93xckx).

We don't know whether it is the same root cause as this issue, but the symptom is **identical**.
Please let me know if the new release either fixes or does not fix the problem you are observing :)
If it fixes the problem, then we should close this issue, and we know the bug is actually a Linux kernel bug rather than a Kubernetes bug.

**Comment by etcshad0vv** [comment]
@xueweiz due to the reason I face this issue quite often lately, can you please tell me if the patch is backported or it's only available to kernel 5.4rc3? I couldn't figure it out from the Google doc. Thank you

**Comment by xueweiz** [comment]
@etcshad0vv It's not backported into any stable branches yet. I'll submit a backport request in a few days, will update here when: 1. The stable kernel backport request is filed 2. Some stable release happens with this patch.

**Comment by xueweiz** [comment]
Requested to backport a kernel patch to stable kernels for 4.19, 4.14, 4.9, 4.4 and 3.16.

See the discussion thread at https://www.spinics.net/lists/stable/msg346612.html

**Comment by xueweiz** [comment]
@etcshad0vv Just learnt that the patch has also been released in Linux stable v5.3.9.
See the [release note](https://lwn.net/Articles/804021/) and the [backport commit](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=v5.3.9&id=b0771e86502351ef5ee7cc3aaf4387f7ca38e773) for v5.3.9.

I wonder if that can unblock you? (I'm not sure whether you are able to pick up a v5.3.9 kernel or do you have to stuck with your current kernel version)

**Comment by liqlin2015** [comment]
@xueweiz Do you know if there is workaround for the kernel issue? Reboot node?
And I still not get how this issue happened sometimes. Because we only see the problem in a few env with ubuntu 16.04 OS + docker ce 18.09.7 (using cgroupfs ).

**Comment by etcshad0vv** [comment]
> 
> 
> Requested to backport a kernel patch to stable kernels for 4.19, 4.14, 4.9, 4.4 and 3.16.
> 
> See the discussion thread at https://www.spinics.net/lists/stable/msg346612.html

You rock man, i appreciate it. I will be waiting for the patch to rollout in stable kernels, and i will provide feedback. Thank you so much!

**Comment by xueweiz** [comment]
Hi @liqlin2015 

> @xueweiz Do you know if there is workaround for the kernel issue? Reboot node?

Yeah reboot would for sure mitigate the problem. Until you hit it again after the reboot :)

Another mitigation that we used and has worked for us is this script:
https://github.com/xueweiz/scripts/blob/master/fix-cfs/fix-cfs.py

To verify whether it works for you, you can find a broken node and SSH into it, then do:
```
git clone https://github.com/xueweiz/scripts.git
sudo python2 scripts/fix-cfs/fix-cfs.py
```
Please share the output logs with me if it didn't work for you.
If it worked, then we can consider deploying it in production as a mitigation.

You should already observed that on a broken node, you cannot create any additional pods through k8s. So you cannot fix a broken node by deploying any DaemonSet.

But what you can do, is to run my script in a DaemonSet, give it proper privileges and mount points, and run it continuously (e.g. once per minute). That should help you repair your nodes once the problem happens quickly.
If you verified that the script works for you, we can together write a DaemonSet for deploying it.

> And I still not get how this issue happened sometimes, any steps to reproduce the problem?

Yes it's reproducible. But I'm not sure whether you'll like it or not...It's pretty clean and simple (if you know what is it trying to do), however a bit complicated...

The bug is caused by this [kernel logic](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=2e8e19226398db8265a8e675fcc0118b9e80c9e8), where kernel may scale the CFS quota and period by 147/128. If that happens on a Pod cgroup, it would cause the [inconsistency](https://docs.google.com/document/d/13KLD__6A935igLXpTFFomqfclATC89nAkhPOxsuKA0I/edit#) between the pod and its containers.

So to reproduce it, you need to find a long-running Pod (on GKE, `prometheus-to-sd` would do), then do this:
```
daemon_set=prometheus-to-sd
kubectl get pods --all-namespaces | grep ${daemon_set}
# find one of the pod from above output, and record it
pod_name=prometheus-to-sd-kkws9
pod_uid=$(kubectl get pod $pod_name -n kube-system -o yaml | yq -y .metadata.uid | head -n 1)
node_name=$(kubectl get pod $pod_name -n kube-system -o yaml | yq -y .spec.nodeName | head -n 1)
container_id=$(kubectl get pod $pod_name -n kube-system -o yaml | yq -y .status.containerStatuses[0].containerID | head -n 1)
container_id=${container_id#"docker://"}

echo "POD=$pod_uid"
echo "CONTAINER=$container_id"
echo "gcloud compute ssh $node_name"
```

The you should SSH into the node (`gcloud compute ssh $node_name`), and run below commands:
```
# Set POD and CONTAINER environment variables
cat /sys/fs/cgroup/cpu,cpuacct/kubepods/burstable/pod$POD/$CONTAINER/cpu.cfs_quota_us
cat /sys/fs/cgroup/cpu,cpuacct/kubepods/burstable/pod$POD/$CONTAINER/cpu.cfs_period_us
cat /sys/fs/cgroup/cpu,cpuacct/kubepods/burstable/pod$POD/cpu.cfs_quota_us
cat /sys/fs/cgroup/cpu,cpuacct/kubepods/burstable/pod$POD/cpu.cfs_period_us
```
You should see the period_us for both POD and CONTAINER is 100000. And you should see the quota_us for both POD and CONTAINER should be equal, and should be between [1000, 100000].
**If not, find another Pod :)**. In GKE, `prometheus-to-sd` should have the above properties.
 
Then you want to scale the POD's quota/period by 147/128. You cannot do this because kernel will tell you it is invalid (and interestingly when kernel does this operation by itself, it does not check it :) ).
So you have to first scale all of the CONTAINERs under the POD, then scale the POD. For `prometheus-to-sd`, there is only one container with quota=1000 and period=100000, so we have:
```
echo 114843 > /sys/fs/cgroup/cpu,cpuacct/kubepods/burstable/pod$POD/$CONTAINER/cpu.cfs_period_us
echo 1148 > /sys/fs/cgroup/cpu,cpuacct/kubepods/burstable/pod$POD/$CONTAINER/cpu.cfs_quota_us
echo 1148 > /sys/fs/cgroup/cpu,cpuacct/kubepods/burstable/pod$POD/cpu.cfs_quota_us
echo 114843 > /sys/fs/cgroup/cpu,cpuacct/kubepods/burstable/pod$POD/cpu.cfs_period_us
```
Then you can stop the CONTAINER via `docker stop $CONTAINER`. Now we have reproduced the root cause!

Then to trigger the k8s symptom, you can either wait for it for a few minutes, or you could use `crictl` to hack around and accelerate the process:
```
$ crictl pods | grep prometheus-to-sd
83013cc154a31       27 hours ago        Ready               prometheus-to-sd-sh7kh                              kube-system         1

# Get the container in that pod using the pod id from above
$ crictl ps -a | grep 83013cc154a31
c72d0d73c7a88       5b48699744eaf        8 seconds ago       Created             prometheus-to-sd            318                 83013cc154a31

# start the container!
$ crictl start c72d0d73c7a88
FATA[0002] Starting the container "c72d0d73c7a88" failed: rpc error: code = Unknown desc = failed to start container "c72d0d73c7a88": Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:424: container init caused \"process_linux.go:390: setting cgroup config for procHooks process caused \\\"failed to write 1000 to cpu.cfs_quota_us: write /sys/fs/cgroup/cpu,cpuacct/kubepods/burstable/pod542047ca-d678-11e9-8bed-42010a8001c1/c72d0d73c7a88c514d933e1de43c4b3d9db646342ae989da756b01888de5faa6/cpu.cfs_quota_us: invalid argument\\\"\"": unknown
```

> we only see the problem in a few env with ubuntu 16.04 OS + docker ce 18.09.7 (using cgroupfs ).

Sorry I'm not that familiar with your environment. But I think you just need to verify two things:

1. Are you using a kernel containing [this patch](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=2e8e19226398db8265a8e675fcc0118b9e80c9e8)?
To answer this, you should fetch your kernel source code, then look at `kernel/sched/fair.c`, and search for "115%". If you see anything, then you are using the patch. If not, you are not using it.

2. Are your containers/pods managed by cfs?
To answer this, you should see if there is anything under directory `/sys/fs/cgroup/cpu,cpuacct/kubepods/burstable/`. If yes, then you are using cfs. If not, **probably** not.

If your answer to both questions are true, then very likely you are affected by the same bug :)

**Comment by xueweiz** [comment]
@etcshad0vv The patch I mentioned has been [backported](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=v4.14.159&id=c294780a80b0fb2e92ab4e2fd584029ced994186) and [released](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/log/?h=v4.14.159) in [4.14.159](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tag/?h=v4.14.159) stable kernel :)

(It is also being cherry-picked into other stable kernels ([3.16](https://lore.kernel.org/stable/20191207011321.123774-1-xueweiz@google.com/), [4.4](https://lore.kernel.org/stable/20191207011102.120954-1-xueweiz@google.com/), [4.9](https://lore.kernel.org/stable/20191207011025.119151-1-xueweiz@google.com/), [4.19](https://lore.kernel.org/stable/20191207010831.115345-1-xueweiz@google.com/)), but they are not released yet.

Sorry for the long wait. Backporting a patch and get a stable kernel release does take some time...

@etcshad0vv , could you let me know whether 4.14.159 kernel fixes the problem for you? Thanks!

**Comment by etcshad0vv** [comment]
Thank you for following up @xueweiz , I will have to wait for 4.4 release. So far it has been really helpful using the python script through a scheduled task fixing the period, I am checking regularly kernel.org for new release in 4.4 plus I will have to wait for a couple of days the rollout of kernel in Ubuntu's repositories in xenial branch (16.04). I will definitely let you know how it will go.

**Comment by etcshad0vv** [comment]
@xueweiz indeed the issue is solved, thank you so much for working on the kernel patching. :)

**Comment by xueweiz** [comment]
Great :) thanks for confirming @etcshad0vv 

For posterity, here are all the patched Linux stable kernel version that contains the fix: [v4.14.159](https://kernel.googlesource.com/pub/scm/linux/kernel/git/stable/linux-stable/+/c294780a80b0f), [4.19.89](https://kernel.googlesource.com/pub/scm/linux/kernel/git/stable/linux-stable/+/742f2319cbd61). The patch is also included on HEAD from [v5.4](https://kernel.googlesource.com/pub/scm/linux/kernel/git/stable/linux-stable/+/4929a4e6faa0f13289a67cae98139e727f0d4a97).

For curious minds, feel free to read up this [doc](https://docs.google.com/document/d/13KLD__6A935igLXpTFFomqfclATC89nAkhPOxsuKA0I/edit) explaining the bug.

/assign @xueweiz 
/close

**Comment by felipecrs** [comment]
It seems that Ubuntu 18.04 HWE kernel (current is 5.4.0-99) still hasn't applied the fix.

**Comment by felipecrs** [comment]
Never mind, the fix is included:

https://kernel.ubuntu.com/git/ubuntu/ubuntu-bionic.git/tree/kernel/sched/fair.c?h=Ubuntu-hwe-5.4-5.4.0-100.113_18.04.1#n4990
