### ISSUE TITLE
[sig-storage] unmount tests are failing in master-blocking and master-upgrade dashboards

### ISSUE THREAD

**Issue by mariantalla** [kubernetes/kubernetes#72931]
**Which jobs are failing**:
- [sig-release-master-blocking#gce-cos-master-serial](https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-serial)
- [sig-release-master-upgrade#gce-new-master-upgrade-cluster-new](https://testgrid.k8s.io/sig-release-master-upgrade#gce-new-master-upgrade-cluster-new)

**Which test(s) are failing**:
- [sig-storage] CSI Volumes [Driver: csi-hostpath-v0] [Testpattern: Dynamic PV (default fs)] subPath should unmount if pod is gracefully deleted while kubelet is down [Disruptive][Slow]
- [sig-storage] CSI Volumes [Driver: csi-hostpath] [Testpattern: Dynamic PV (default fs)] subPath should unmount if pod is gracefully deleted while kubelet is down [Disruptive][Slow]
- [sig-storage] CSI Volumes [Driver: pd.csi.storage.gke.io][Serial] [Testpattern: Dynamic PV (default fs)] subPath should unmount if pod is gracefully deleted while kubelet is down [Disruptive][Slow]

**Since when has it been failing**:
2019-01-15 (when they were added)

**Testgrid link**:
- [master-blocking](https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-serial/4554)
- [master-upgrade](https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-new-master-upgrade-cluster-new/1966)

**Reason for failure**:
They all seem to be failing with:
```
Expected grep stdout to be empty (i.e. no mount found).
```

The failures seem to start with [commit 72895](https://github.com/kubernetes/kubernetes/commit/148248353b883f0dbbefa38100b675a7ed3ba587).

**Comment by mariantalla** [comment]
Summoning @saad-ali and @childsb 

This seems to have been failing since it was added in master-blocking.

**Comment by msau42** [comment]
This is the same as https://github.com/kubernetes/kubernetes/issues/72500

**Comment by mariantalla** [comment]
Thanks @msau42, closing this one.

/close

**Comment by msau42** [comment]
/reopen

I took a look at the latest test failures and I think it is a different issue than #72500

**Comment by msau42** [comment]
Looking at one test failure here:
https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-serial/4624/artifacts/bootstrap-e2e-minion-group-t099/kubelet.log

Sequence of events:

1. Kubelet stopped, pod deleted:
 ```
I0129 18:45:22.903] Jan 29 18:45:22.902: INFO: ssh prow@35.247.90.167:22: command:   sudo systemctl stop kubelet
I0129 18:45:59.797] [1mSTEP[0m: Deleting Pod "pod-subpath-test-pd-csi-storage-gke-io-dynamicpv-v4f7"
```
2. Kubelet started again: 
`I0129 18:46:01.575] Jan 29 18:46:01.574: INFO: ssh prow@35.247.90.167:22: command:   sudo systemctl start kubelet`
3. Add volume to dsw
 `I0129 18:46:03.642387   23246 desired_state_of_world_populator.go:318] Added volume "test-volume" (volSpec="pvc-f6455870-23f5-11e9-8c7f-42010a8a0002") for pod "fb5259be-23f5-11e9-8c7f-42010a8a0002" to desired state.`
4. VerifyControllerAttach started and failed because it's not in the node's volumesinuse list. This repeats for a while.
```
I0129 18:46:03.692534   23246 reconciler.go:207] operationExecutor.VerifyControllerAttachedVolume started for volume "pvc-f6455870-23f5-11e9-8c7f-42010a8a0002" (UniqueName: "kubernetes.io/csi/pd.csi.storage.gke.io^projects/k8s-jkns-gci-gke-reboot-1-4/zones/us-west1-b/disks/pvc-f6455870-23f5-11e9-8c7f-42010a8a0002") pod "pod-subpath-test-pd-csi-storage-gke-io-dynamicpv-v4f7" (UID: "fb5259be-23f5-11e9-8c7f-42010a8a0002")
E0129 18:46:03.696485   23246 nestedpendingoperations.go:267] Operation for "\"kubernetes.io/csi/pd.csi.storage.gke.io^projects/k8s-jkns-gci-gke-reboot-1-4/zones/us-west1-b/disks/pvc-f6455870-23f5-11e9-8c7f-42010a8a0002\"" failed. No retries permitted until 2019-01-29 18:46:04.196436349 +0000 UTC m=+2.656446060 (durationBeforeRetry 500ms). Error: "Volume has not been added to the list of VolumesInUse in the node's volume status for volume \"pvc-f6455870-23f5-11e9-8c7f-42010a8a0002\" (UniqueName: \"kubernetes.io/csi/pd.csi.storage.gke.io^projects/k8s-jkns-gci-gke-reboot-1-4/zones/us-west1-b/disks/pvc-f6455870-23f5-11e9-8c7f-42010a8a0002\") pod \"pod-subpath-test-pd-csi-storage-gke-io-dynamicpv-v4f7\" (UID: \"fb5259be-23f5-11e9-8c7f-42010a8a0002\") "
```
5. Reconstruction also started, but we skipped cleaning up because the volume is in dsw so we want to let volume manager gracefully cleanup
```
I0129 18:46:03.694948   23246 csi_plugin.go:390] kubernetes.io/csi: plugin.ConstructVolumeSpec [pv.Name=pvc-f6455870-23f5-11e9-8c7f-42010a8a0002, path=/var/lib/kubelet/pods/fb5259be-23f5-11e9-8c7f-42010a8a0002/volumes/kubernetes.io~csi/pvc-f6455870-23f5-11e9-8c7f-42010a8a0002]
I0129 18:46:03.694954   23246 csi_util.go:75] kubernetes.io/csi: loading volume data file [/var/lib/kubelet/pods/fb5259be-23f5-11e9-8c7f-42010a8a0002/volumes/kubernetes.io~csi/pvc-f6455870-23f5-11e9-8c7f-42010a8a0002/vol_data.json]
I0129 18:46:03.694994   23246 csi_plugin.go:398] kubernetes.io/csi: plugin.ConstructVolumeSpec extracted [map[string]string{"attachmentID":"csi-9370f9da48da2cff2e97f2c161718cd8c046cad9d3bb8f1baa5a34d556ad26ef", "driverName":"pd.csi.storage.gke.io", "nodeName":"bootstrap-e2e-minion-group-t099", "specVolID":"pvc-f6455870-23f5-11e9-8c7f-42010a8a0002", "volumeHandle":"projects/k8s-jkns-gci-gke-reboot-1-4/zones/us-west1-b/disks/pvc-f6455870-23f5-11e9-8c7f-42010a8a0002"}]
I0129 18:46:03.695015   23246 reconciler.go:390] Volume exists in desired state (volume.SpecName pvc-f6455870-23f5-11e9-8c7f-42010a8a0002, pod.UID fb5259be-23f5-11e9-8c7f-42010a8a0002), skip cleaning up mounts
```
6. We don't remove volume from dsw because actual state has not been updated?
`I0129 18:46:33.547264   23246 desired_state_of_world_populator.go:262] Actual state has not yet has this information skip removing volume from desired state for volume "pvc-f6455870-23f5-11e9-8c7f-42010a8a0002" (UniqueName: "kubernetes.io/csi/pd.csi.storage.gke.io^projects/k8s-jkns-gci-gke-reboot-1-4/zones/us-west1-b/disks/pvc-f6455870-23f5-11e9-8c7f-42010a8a0002") pod "pod-subpath-test-pd-csi-storage-gke-io-dynamicpv-v4f7" (UID: "fb5259be-23f5-11e9-8c7f-42010a8a0002")`


So it seems like there's a problem with populating the node's volumesinuse after a kubelet restart.

**Comment by msau42** [comment]
@kubernetes/sig-storage-test-failures

**Comment by msau42** [comment]
cc @jingxu97

**Comment by msau42** [comment]
/assign
will continue investigating. i will try repro-ing at without different commits to try to figure out which pr introduced the regression

**Comment by msau42** [comment]
I ran these tests against a cluster with the NodeLease feature disabled, and the tests pass.  So I think the issue is related to the new NodeLease feature enabled a month ago: https://github.com/kubernetes/kubernetes/pull/72096

cc @wojtek-t @wangzhen127

**Comment by msau42** [comment]
@kubernetes/sig-node-test-failures

**Comment by msau42** [comment]
I discussed with @jingxu97.  VolumesInUse is updated periodically in the Node.Status.  So we need to make sure this flow is working well with the NodeLease feature.

**Comment by msau42** [comment]
@jingxu97 @wangzhen127 and I walked through the code.  The NodeLease feature introduced an early exit to the node status update function, so our theory is we need to add a call to `MarkVolumesReportedAsInUse` [here](https://sourcegraph.com/github.com/kubernetes/kubernetes/-/blob/pkg/kubelet/kubelet_node_status.go#L430).

I will make the change and test it out
