### ISSUE TITLE
Very flaky - [sig-autoscaling] [HPA] Horizontal pod autoscaling (scale resource: CPU) [sig-autoscaling] [Serial] [Slow] ReplicationController Should scale from 5 pods to 3 pods and from 3 to 1 and verify decision stabilityChanges failing in gce-cos-1.11-serial

### ISSUE THREAD

**Issue by foxish** [kubernetes/kubernetes#73045]
**Which jobs are failing**: sig-release-1.11-blocking

**Which test(s) are failing**:  [sig-autoscaling] [HPA] Horizontal pod autoscaling (scale resource: CPU) [sig-autoscaling] [Serial] [Slow] ReplicationController Should scale from 5 pods to 3 pods and from 3 to 1 and verify decision stabilityChanges

**Since when has it been failing**: lots of flakes over a long time

**Testgrid link**: https://k8s-testgrid.appspot.com/sig-release-1.11-blocking#gce-cos-1.11-serial&width=20

**Reason for failure**: unknown

@kubernetes/sig-autoscaling-bugs

**Comment by MaciekPytel** [comment]
@jbartosik I think you know the most about those test by now. Any ideas why it's flaky?

**Comment by jbartosik** [comment]
All recent failures fail with the following error:

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/autoscaling/horizontal_pod_autoscaling.go:64
Expected error:
    <*errors.errorString | 0xc4233195f0>: {
        s: "number of replicas below target",
    }
    number of replicas below target
not to have occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/autoscaling/horizontal_pod_autoscaling.go:125
```

So the failures happen when testing stabilization after the first scale down ([horizontal_pod_autoscaling.go:125](https://github.com/kubernetes/kubernetes/blob/release-1.11/test/e2e/autoscaling/horizontal_pod_autoscaling.go#L125)). I think this is just resource consumer not being perfect at generating load.

I think this is because resource consumer is imperfect at generating cpu load and something changed that makes it generate less CPU usage than it used to. If I'm right increasing [totalInitialCpuUsage](https://github.com/kubernetes/kubernetes/blob/release-1.11/test/e2e/autoscaling/horizontal_pod_autoscaling.go#L160) will help. I'll also add some logging in case it doesn't.

**Comment by jbartosik** [comment]
Teh PR merged, let's see if it fixes the issue.

**Comment by jbartosik** [comment]
The test had 8 green and 0 red runs in the 2 days since the PR merged. Is it ok to close this issue now?

**Comment by jbartosik** [comment]
@foxish please close this issue.

**Comment by jbartosik** [comment]
@foxish the test has been consitently passing for 4 days now, please close this issue (I can't).

**Comment by jbartosik** [comment]
/close
All runs green for 5 days.
