### ISSUE TITLE
Add events to kube-proxy

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#7304]
As soon as #7303 merges, kube-proxy will be able to send events.  

We should take advantage of that.

This is a good starter project.

Steps: 
- Import `github.com/GoogleCloudPlatform/kubernetes/pkg/client/record` into `cmd/kube-proxy/app/server.go` and `pkg/proxy/...`.
- Record BirthCry, like kubelet does, so that restarts are visible.
- Record an event when service/endpoint watching fails for an extended time.
- Record an event when proxying fails unexpectedly.
- Ensure that event rate is not too high in pathological cases 
  - ensure that successive events are identical except for time field so they are compacted.
  - check with @saad-ali about what he did with kubelet event compaction

**Comment by jiangyaoguo** [comment]
@erictune  Is there anyone working on this?  May I work on it?

**Comment by erictune** [comment]
Nobody is working in it that I know of.  I'd be happy for you to work on it.
I can't readily set you as the assignee, but I don't think that will be a problem.

**Comment by aveshagarwal** [comment]
If nobody is looking into it, I would be happy to work on it.

**Comment by jiangyaoguo** [comment]
@aveshagarwal Now the kube-proxy has new iptables proxy. I'm waiting for its code stable and make events in userspace and iptables proxy uniformed.

**Comment by aveshagarwal** [comment]
@jiangyaoguo Not yet. I am just starting to looking into it. And yes happy to cooperate with you.

**Comment by aveshagarwal** [comment]
@jiangyaoguo one way would be to write wrapper functions around various events and call them from similar points from both iptables and userspace proxiers.

**Comment by thockin** [comment]
xref https://github.com/kubernetes/kubernetes/issues/6716

**Comment by xiangpengzhao** [comment]
We currently have four places to fire events for kube-proxy:
- [birthCry](https://github.com/kubernetes/kubernetes/blob/master/cmd/kube-proxy/app/server.go#L776)
- [a `readOnlySysFS` error occurs](https://github.com/kubernetes/kubernetes/blob/master/cmd/kube-proxy/app/server.go#L682)
- [Failed to open local port](https://github.com/kubernetes/kubernetes/blob/master/pkg/proxy/iptables/proxier.go#L1210)
- [Failed to start healthcheck](https://github.com/kubernetes/kubernetes/blob/master/pkg/proxy/healthcheck/healthcheck.go#L158)

Do we still think we need more events as discussed in this issue? Since this issue is stale, I'd prefer to close this issue and the xref issue #6716 for now.

**Comment by freehan** [comment]
Some events have been added. Open new issue if more needs to be added. Closing this one.
