### ISSUE TITLE
kubectl exec can unexpectedly exit 0

### ISSUE THREAD

**Issue by tsuna** [kubernetes/kubernetes#73056]
**What happened**:

A little while after running `kubectl exec -it <pod> bash`, in the middle of running a long command I got kicked out of the `kubectl exec` back into the outer shell, with `kubectl` exiting 0.  The pod didn't restart or anything like that.

**What you expected to happen**:

`kubectl exec` should never exit 0 unless the command it was executing exits 0 itself.

**How to reproduce it (as minimally and precisely as possible)**:

Not sure.

**Anything else we need to know?**:

Here is an excerpt of the logs that is relevant:
```
docker-desktop:/var/lib/log# fgrep 2d15caa40e0b44d0640ff2bd8a679107f8a9cd888d157fe22c42debf620b29ee *
docker.log:2019-01-17T23:49:37Z docker time="2019-01-17T23:49:37.025234900Z" level=debug msg="Calling POST /v1.38/exec/2d15caa40e0b44d0640ff2bd8a679107f8a9cd888d157fe22c42debf620b29ee/start"
docker.log:2019-01-17T23:49:37Z docker time="2019-01-17T23:49:37.025894500Z" level=debug msg="starting exec command 2d15caa40e0b44d0640ff2bd8a679107f8a9cd888d157fe22c42debf620b29ee in container e41e3d8c4373adbb199b0a287191427391b789e7a42d8ee90609f416bbbe3de8"
docker.log:2019-01-17T23:49:37Z docker time="2019-01-17T23:49:37.033666200Z" level=debug msg="Calling POST /v1.38/exec/2d15caa40e0b44d0640ff2bd8a679107f8a9cd888d157fe22c42debf620b29ee/resize?h=56&w=204"
docker.log:2019-01-17T23:56:05Z docker time="2019-01-17T23:56:05.619356500Z" level=debug msg="Calling GET /v1.38/exec/2d15caa40e0b44d0640ff2bd8a679107f8a9cd888d157fe22c42debf620b29ee/json"
docker.log:2019-01-17T23:56:07Z docker time="2019-01-17T23:56:07.619562100Z" level=debug msg="Calling GET /v1.38/exec/2d15caa40e0b44d0640ff2bd8a679107f8a9cd888d157fe22c42debf620b29ee/json"
docker.log:2019-01-17T23:56:09Z docker time="2019-01-17T23:56:09.619597700Z" level=debug msg="Calling GET /v1.38/exec/2d15caa40e0b44d0640ff2bd8a679107f8a9cd888d157fe22c42debf620b29ee/json"
docker.log:2019-01-17T23:56:11Z docker time="2019-01-17T23:56:11.620721000Z" level=debug msg="Calling GET /v1.38/exec/2d15caa40e0b44d0640ff2bd8a679107f8a9cd888d157fe22c42debf620b29ee/json"
docker.log:2019-01-17T23:56:13Z docker time="2019-01-17T23:56:13.619711500Z" level=debug msg="Calling GET /v1.38/exec/2d15caa40e0b44d0640ff2bd8a679107f8a9cd888d157fe22c42debf620b29ee/json"
docker.log:2019-01-17T23:56:13Z docker E0117 23:56:13.621199    1281 exec.go:127] Exec session 2d15caa40e0b44d0640ff2bd8a679107f8a9cd888d157fe22c42debf620b29ee in container e41e3d8c4373adbb199b0a287191427391b789e7a42d8ee90609f416bbbe3de8 terminated but process still running!
kubelet.log:2019-01-17T23:56:13Z kubelet E0117 23:56:13.621199    1281 exec.go:127] Exec session 2d15caa40e0b44d0640ff2bd8a679107f8a9cd888d157fe22c42debf620b29ee in container e41e3d8c4373adbb199b0a287191427391b789e7a42d8ee90609f416bbbe3de8 terminated but process still running!
```

It's not clear why `kubectl exec` suddenly exited, however looking at the code, it's obvious that it can potentially exit 0 when this weird situation occurs (from [`kubelet/dockershim/exec.go`](https://github.com/kubernetes/kubernetes/blob/954996e231074dc7429f7be1256a579bedd8344c/pkg/kubelet/dockershim/exec.go#L126)):

```go
	err = client.StartExec(execObj.ID, startOpts, streamOpts)
	// ...
	for {
		inspect, err2 := client.InspectExec(execObj.ID)
		// ...

		count++
		if count == 5 {
			klog.Errorf("Exec session %s in container %s terminated but process still running!", execObj.ID, container.ID)
			break // <--- bug if we break here with err == nil
		}

		<-ticker.C
	}

	return err
```

If we hit the `break` annotated above, I believe that will cause `kubectl exec` to exit 0, despite this being an error condition.  This means that error handling at the level above is not possible.  We need to be able to trust that `kubectl exec` only ever exits 0 if the underlying command it ran exited 0.

So I believe if `err == nil` before hitting the `break` it should be set to something that will make `kubectl exec` exit with a non-zero exit code.

**Environment**:
- Kubernetes version (use `kubectl version`)

```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T19:44:10Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T20:56:12Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration: Docker for Mac version 2.0.1.0 (30090)
- OS (e.g. from /etc/os-release): macOS 10.13.6
- Kernel (e.g. `uname -a`): `Darwin hactar.localdomain 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64`
- Install tools: k8s through Docker for Mac
- Others: Docker 18.09.1

/sig cli

**Comment by tsuna** [comment]
@kubernetes/sig-cli-bug

**Comment by tsuna** [comment]
let's try again:

/sig cli

**Comment by tsuna** [comment]
Cc @ncdc, judging from the history of this code you might have an opinion on the matter :)

**Comment by lllamnyp** [comment]
I think I've encountered this. I have a CronJob trigerring a backup of our gitlab server. The script goes something like
`´´
... && kubectl exec -t <gitlab-container> gitlab-rake gitlab:backup:create && echo done && ls ...
```
Looking at the logs I see that a message such as [backing up container registry images] comes along at a certain time, then all is silent for a while, while gitlab is copying tens of GB of images to an archive. Precisely 30 minutes later I see done echoed and ls returns a list of files resembling a backup still in the process of assembly. Is there some sort of timeout hidden somewhere for this type of command?

This is being thrown by kubectl v 1.13.5 and we've got k8s 1.14.1 on the server side.

**Comment by Reinkaos** [comment]
Hey,

I think that I am encountering this issue as well, my use case is that I am running a long query on Mongo via kubectl exec and after about 20 minutes I am kicked out of the pod. In the syslog of the Node I have this error:

```
Exec session in container <id> terminated but process still running!
```

Would be great to know what the solution is for this.

Thanks,
Richard

**Comment by bkSentinel** [comment]
I have the same problems (occuring when creating a backup for gitlab with kubectl exec). 
Kubernetes: 1.13.5
Kubectl: 1.12.x, 1.13.5, 1.15.0

I can add as additional information that this "exit 0" occurs about exactly 600 seconds after starting the "exec".

**Comment by TheAifam5** [comment]
Thats really annoying bug. It costs me so much time . First, I was thinking that the Pod got restarted because of memory limit or something, then after disabling the limits, has same issue so I tried to port-forward but my internet went down 🤯

**Comment by wu0407** [comment]
the kubectl  exec is idle exit with  use http_proxy  to apiserver  in my case, the timeout of http proxy server is 10min and streamingConnectionIdleTimeout: 4h0m0s

**Comment by n-raymond** [comment]
Hi everyone !

I am having the same issue using `kafka-console-consumer` tool (e.g. A java program that shows messages incomming from a kafka queue). After a while where the program shows nothing on standard output (no more messages), `kubectl exec` exits with following code 0.

A precision that might interest you : Whereas `kubectl exec` has quit, the process `kafka-console-consumer` was still running on the container and it caused me some more troubles...

Thus, until the issue is resolved and if you encounter the bug, **don't forget to kill the process** if it should not live forever !

**Comment by tsuna** [comment]
I can confirm that in my case too when this happened the command was left running inside the container as well.

**Comment by Tran-Hoang-Lam** [comment]
Look like v1.14.8 doesn't have this problem, can some one confirm that? I'm using docker for windows

`Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.8", GitCommit:"211047e9a1922595eaa3a1127ed365e9299a6c23", GitTreeState:"clean", BuildDate:"2019-10-15T12:11:03Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.8", GitCommit:"211047e9a1922595eaa3a1127ed365e9299a6c23", GitTreeState:"clean", BuildDate:"2019-10-15T12:02:12Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}`

**Comment by tsuna** [comment]
I have v1.16.3 on macOS and I still see this issue nearly on a daily basis. It generally appears when I leave my laptop to sleep overnight. Seems like something under the hood is timing out but `kubectl exec` exits zero and the command it started keeps running in the container.

**Comment by Tran-Hoang-Lam** [comment]
> I have v1.16.3 on macOS and I still see this issue nearly on a daily basis. It generally appears when I leave my laptop to sleep overnight. Seems like something under the hood is timing out but `kubectl exec` exits zero and the command it started keeps running in the container.

Is that your client version or both?

**Comment by tsuna** [comment]
These days I'm on client version v1.17.0 and server version v1.15.5 but I've seen it with all combinations of clients and servers over the months

**Comment by lllamnyp** [comment]
I'm surprised, this has gone on for so long. Apparently, this is by design: 

`"--streaming-connection-idle-timeout=30m"`
(see https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/)

in my deployment gives me the observed exact 30 minutes before disconnecting. What's worse is that it exits with an exit code of 0. This may be fine in some cases, but problematic in others. It seems, for example, that gitlab's kubernetes executor sends the entire job script into its pod as a single kubectl exec and should it time out, it aborts mid-job, but returning a "Job succeeded".

**Comment by chief93** [comment]
Not sure if my case is related to this one, but I have encountered almost same behavior for SOME of my pods (not everyone (for example the bashing into `busybox` works as expected)): when I'm trying to execute something like this:
```bash
kubectl -n mynamespace exec pod/mypod -- /bin/bash
```
then `kubectl` just exits, without any `bash` prompt or anything like this

On other hand, if I execute this:
```bash
kubectl -n mynamespace exec pod/mypod -- cat /myfile.txt
```
then I'm able to get the contents of this file

Maybe it would be helpful, but I'm using the `supervisord` for application lifecycle management, maybe this can be somehow related for this issue.
And one another important note: the using same command within a `Docker` container works fine - bash prompt is reached:
```bash
docker exec -it mycontainer /bin/bash
```

**Comment by lllamnyp** [comment]
@chief93 see how you have docker exec **-it** but just plain old kubectl exec? Thats the cause.

**Comment by chief93** [comment]
@lllamnyp I'm not sure I get your idea properly, but regardles of `docker` command example - I said that `docker exec` works just fine for CONTAINER, in opposite for `kubectl exec` for POD

**Comment by lllamnyp** [comment]
@chief93 you missed my emphasis on the importance of passing the correct flags to the exec command:

```
$ docker run --help | grep -- ' -t'
  -t, --tty                            Allocate a pseudo-TTY
$ kubectl exec --help | grep -- ' -t'
  kubectl exec mypod -c ruby-container -i -t -- bash -il
  # unless that is how you would execute it normally (i.e., do ls -t /usr, not "ls -t /usr").
  kubectl exec mypod -i -t -- ls -t /usr
  -t, --tty=false: Stdin is a TTY
```

it's a coincidence that some containers give you an interactive shell without `-it`, but it is usually mandatory. Besides that, there is no concept of `kubectl exec`ing into a pod. A pod is nothing more than a collection of containers with some shared properties. At the end of the day `kubectl exec`s into one of the pod's containers, defaulting to the first one in the `containers` list of the `podSpec`.

**Comment by chief93** [comment]
@lllamnyp thanks for reply! I've used it also with `-it`, but with absolutely same behavior, more of that - the executing with `-it` is DEEPRECATED for `kubectl`

**Comment by koxu1996** [comment]
exit code 0 is completely unexpected...

**Comment by vamshi-aruru** [comment]
Still facing this issue. We run a script in kubernetes pods by exec'ing into them, and if the script takes too long, the exec session ends. The script does run to completion, but it is still annoying to not be able to see the logs.

**Comment by rikatz** [comment]
/lifecycle active
/assign
Starting to work on a KEP to normalize this

**Comment by mikechengwei** [comment]
Also meet this question.

**Comment by ehashman** [comment]
/remove-sig node

Happy to participate in a KEP but this doesn't appear to be a SIG Node issue.

**Comment by tsuna** [comment]
This is still happening.

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:52:14Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"darwin/amd64"}
```

I was in a `kubectl exec -it` session and my VPN session broke down and I got kicked out and `kubectl` exited 0.

**Comment by SangameswaranRS** [comment]
Any update?

**Comment by ShethR** [comment]
I am facing a similar issue. 
Do we have any updates on this?

**Comment by rudolfbyker** [comment]
/remove-lifecycle stale

It does not seem to have anything to do with the runtime, or whether data is sent or not. Still trying to figure out what triggers it. In any case, a PR that ensures that `kubectl` does proper error reporting will go a long way in figuring out what makes it bail.

### Notes

Below are some tests on my Drupal pod. But first, some notes:

- I'm piping it through `pv` on my machine to see how much data is transferred.
- Each command in this list is prefixed with `kubectl -n ns -it exec deploy/drupal-deployment --container=drupal --`, but I leave it out for brevity.
- Wherever I say a test "has the issue", I mean that `kubectl exec` stops with code 0, but the process keeps running in the container.
- When I do something like `kubectl -n ns -it exec deploy/drupal-deployment --container=drupal -- cat /dev/urandom | pv > /dev/null`, the pipe to `pv` is done on my local machine, but `cat /dev/urandom` runs in the container.

### The pipe tests

- `drush sql-dump --gzip | pv > tmp/db.sql.gz` — has the issue. The `.sql.gz` file has "unexpected end of file". Transfers about 50MiB in 23s before it dies.
- `drush sql-dump | pv > tmp/db.sql` — has the issue. The `.sql` file also stops in the middle of a table, so we don't have the entire database. Transfers about 387MiB in 3min before it dies.
- `watch date | pv > /dev/null` — does NOT have the issue. It keeps running for a very long time without issues, so it rules out the possibility of a timeout somewhere. I'll edit this if it dies at some point.
- `cat /dev/urandom | pv > /dev/null` — does NOT have the issue. Same as `watch date`. Transferred about 1GiB in 0:07:42 at the time of writing, and still going strong, So that rules out a network bandwidth limitation.

### Exit code test

This works as expected, so it rules out the possibility of the exec'd command completing with non-zero exit code:

```shell
$ kubectl -n ns -it exec deploy/drupal-deployment --container=drupal -- /bin/sh -c "exit 1"
command terminated with exit code 1
$ echo $?
1
```

### Running the same commands interactively

I opened an interactive bash shell, and tried the failing commands from above:
```
$ kubectl -n ns -it exec deploy/drupal-deployment --container=drupal -- /bin/bash
```

No problem here. database dump is complete, and kubectl stays connected:

```shell
bash-5.1# drush sql:dump | pv > /tmp/db.sql
 394MiB 0:00:11 [35.5MiB/s]
bash-5.1# tail -n 1 /tmp/db.sql
-- Dump completed on 2022-02-04  9:31:24
```

Also works with gzip. kubectl stays connected:

```shell
bash-5.1# drush sql:dump --gzip | pv > /tmp/db.sql.gz
49.9MiB 0:00:18 [2.69MiB/s]
bash-5.1# zcat /tmp/db.sql.gz | tail -n 1
-- Dump completed on 2022-02-04  9:33:50
```

So that rules out the exec'd command using too much CPU or memory, because these are the same commands as in the above tests.

### `cat` existing file test

This left be wondering if the exec'd command writes something to the stream that makes kubectl choke up, and it just hasn't come up in `/dev/urandom yet`, but it's part of my database dump. So let's test that...

```shell
$ kubectl -n ns -it exec deploy/drupal-deployment --container=drupal -- cat /tmp/db.sql | pv > tmp/db.sql
 392MiB 0:02:59 [2.18MiB/s]
$ less tmp/db.sql
```

I can see in `less` that the file is cut off before the end! It should have transferred 394MiB, but we only have 392MiB.

```shell
$ kubectl -n ns -it exec deploy/drupal-deployment --container=drupal -- cat /tmp/db.sql.gz | pv > tmp/db.sql.gz
48.1MiB 0:00:21 [2.20MiB/s]
```

This is cut short again: 48.1MiB instead of 49.9MiB.  But this is where it gets really weird. Compare the first few lines of the file on the source, vs. the file we got by downloading it through `kubectl exec ... cat > ...`:

```shell
$ kubectl -n ns -it exec deploy/drupal-deployment --container=drupal -- /bin/sh -c "zcat /tmp/db.sql.gz | head"
-- MariaDB dump 10.19  Distrib 10.5.13-MariaDB, for Linux (x86_64)
--
-- Host: db-primary    Database: drupal
-- ------------------------------------------------------
-- Server version       10.5.13-MariaDB-log

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;
```

```shell
$ zcat tmp/db.sql.gz | head
-- MariaDB dump 10.19  Distrib 10.5.13-MariaDB, for Linux (x86_64)
--
-- Host: db-primary    Database: drupal
-- ------------------------------------------------------
-- Server version       10.5.13-MariaDB-log

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTIONb-primary    Databrupal
--UeES utf8mb4ry    Databr3LD_COLLATITIME_ZONEATITIME_ZONEry    Databr3LD_COTIME_ZONEA'+00:00'ry    Data014LD_COLLATIUNIQUETERECKRACTUNIQUETERECKR, UNIQUETERECKRA0ry    Data014LD_COLLATIFOREIGN_KEYTERECKRACTFOREIGN_KEYTERECKR, FOREIGN_KEYTERECKRA0!40101 SET @OLD_COLLATISQL_MODEATISQL_MODE, SQL_MODEA'NO_AUTO_VALUETECTZERO'ry    Data11OLD_COLLATISQL_NOTESATISQL_NOTES, SQL_NOTESA0!4010Host: dTable 0.5ucturenux (table `batch`Host
```

Not surprisingly, the downloaded file can't be extracted completely:

```shell
$ zcat tmp/db.sql.gz > /dev/null

gzip: tmp/db.sql.gz: invalid compressed data--format violated
```

Trying to verify that the problem is not with different versions of gzip or something like that, I tried `kubectl cp`, and that works fine. The `.sql.gz` file has the proper size, and can be extracted on my local machine just like in the container.

```shell
$ kubectl cp ns/drupal-deployment-66795dfd9d-ft56s:/tmp/db.sql.gz -c drupal tmp/cp_db.sql.gz
tar: Removing leading `/' from member names
$ zcat tmp/cp_db.sql.gz | tail -n 1
-- Dump completed on 2022-02-04  9:33:50
```

### Verdict

kubectl exec has issues transferring stdout data to the local machine.

**Comment by rudolfbyker** [comment]
If I run this command over and over, eventually I get lucky, and get a complete file that works:

```shell
kubectl -n ns -it exec deploy/drupal-deployment --container=drupal -- drush sql-dump --gzip | pv > tmp/db.sql.gz
```

That smells like a race condition or at least some time-dependent issue somewhere in `kubectl exec`.

**Comment by teji8895** [comment]
Was struggling with this for one month.
For me it was the kubectl version . was v1.10.0
Change the client version same as server version i.e v1.21.0

this made the container not to exit abruptly in 15 minutes.

**Comment by TheAifam5** [comment]
Fight with the "automation" begins :)

**Comment by rudolfbyker** [comment]
This seems to be fixed since I upgraded both my k8s cluster AND my kubectl client to v1.30. Probably due to the transition from SPDY to Websockets: [github.com/kubernetes/enhancements/issues/4006](https://github.com/kubernetes/enhancements/issues/4006)
