### ISSUE TITLE
Make it easy to get client/server certs into chrome (or other browsers)

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#7307]
It's pretty annoying to have to grab an extension to set a token header, likewise to use kubectl to proxy apiserver locally. Additionally, the old way with basic auth (and the header method) are easy to MITM. Therefore, let's do it right, and make it easy to get the ca and client certs imported into your browser.

Setting as P1 because we just turned off the basic auth method.

**Comment by roberthbailey** [comment]
After a bit of poking at the server, I figured out how to verify that the client certificate I'm presenting is accepted by the server:

```
OpenSSL s_client -connect 104.197.40.182:443 -CAfile ca.crt  -tls1 -cert kubecfg.crt -key kubecfg.key
...
GET /validate HTTP/1.1
HTTP/1.1 200 OK
Date: Sat, 25 Apr 2015 04:41:05 GMT
Content-Length: 624
Content-Type: text/plain; charset=utf-8

[
  {
    "component": "controller-manager",
    "health": "success",
    "msg": "ok",
    "err": "nil"
  },
  {
    "component": "scheduler",
    "health": "success",
    "msg": "ok",
    "err": "nil"
  },
  {
    "component": "etcd-0",
    "health": "success",
    "msg": "{\"action\":\"get\",\"node\":{\"dir\":true,\"nodes\":[{\"key\":\"/registry\",\"dir\":true,\"modifiedIndex\":3,\"createdIndex\":3}]}}\n",
    "err": "nil"
  },
  {
    "component": "node-0",
    "health": "success",
    "msg": "ok",
    "err": "nil"
  },
  {
    "component": "node-1",
    "health": "success",
    "msg": "ok",
    "err": "nil"
  }
]
```

Now to figure out how to convince chrome to do this...

**Comment by roberthbailey** [comment]
Ok, I figured it out (for the mac at least -- will work on Linux next week). It isn't the most straightforward thing (so we need to make it simpler) but here's what you need to do: 

Fetch cert files from the master. These are the same files that are fetched during cluster creation and stored in the `kubeconfig` file, but we want them un-embedded so it's easiest to just do it again: 
```
$ gcloud compute copy-files --zone=<zone> root@<cluster-name>-master:/srv/kubernetes/{kubecfg.crt,kubecfg.key,ca.crt} .
```
Import the CA root into your keychain. This will ask you to trust the cert and will probably prompt you for your admin password. At this point you will be able to connect to the master without getting the ugly certificate warning in your web browser. 

Generate a `pkcs12` file from the kubecfg cert/key pair. This is the format that you can import into the keychain that Chrome/Safari will use as a client cert:
```
$ openssl pkcs12 -export -clcerts -inkey kubecfg.key -in kubecfg.crt -out kubecfg.p12 -name "kubecfg"
```
This will ask you for an export password. I tried leaving it blank and that prevented me from adding it to the Keychain so make sure you enter something for the password.

At this point I had to restart Chrome for it to find the client cert (otherwise it gave a 401 Unauthorized result) but Safari picked it up right away.

**Comment by roberthbailey** [comment]
Oh, and for this to work you need to pass a new flag to the apiserver so that it knows what CA to trust. I've sent PR #7326 to enable this for GCE.

**Comment by lavalamp** [comment]
Let's fix this at the same time we do this: https://github.com/kubernetes/kubernetes/issues/10351#issuecomment-133247177

**Comment by liggitt** [comment]
Client certs in the browser count as an "automatic authentication" mechanism that would make a browser vulnerable to CSRF attacks

**Comment by roberthbailey** [comment]
Is that universally true? I've definitely had experiences where my browser prompted me for a client cert when visiting a website so I'm not sure what it would do if that site was hit with a XHR.

**Comment by liggitt** [comment]
Behavior varies by browser (of course), but typically they do something like this http://blogs.msdn.com/b/ieinternals/archive/2009/09/03/client-certificate-selection-prompt.aspx:

> * If the user has no suitable client certificates, no prompt is shown, and no certificate is sent to the server
> * If the user has only one suitable client certificate, no prompt is shown, and that certificate is sent to the server
> * If the user has multiple suitable client certificates, the certificate selection prompt is shown

Some browsers will modify that by prompting you the first time to select a client certificate, then using the selected one after that point.

In general, though, any mechanism where the browser automatically sends credentials (cookie, basic-auth, client-cert, etc) based only on the target host isn't appropriate to use for browser calls to an API unless you pair it with CSRF prevention techniques.

**Comment by roberthbailey** [comment]
Bumping this down to a P2 and unassigning since it isn't clear that this is something we actually want to do.

**Comment by brendandburns** [comment]
I'm closing this as it's nearly a year old and I don't think we really want to do it.

**Comment by roberthbailey** [comment]
agreed

**Comment by vaughnkoch** [comment]
Note for people who stumble on this thread and are just trying to develop in localhost: 
Firefox can allow exceptions to cert compliance.
For chrome and localhost (e.g. using docker's k8s and a nodePort), you can use this flag:
chrome://flags/#allow-insecure-localhost
