### ISSUE TITLE
Use a security group for loadBalancerSourceRanges rules and another to ICMP rules on aws services

### ISSUE THREAD

**Issue by yagonobre** [kubernetes/kubernetes#73086]
**What would you like to be added**:
Use a security group to rules on loadBalancerSourceRanges and another to ICMP rules.

**Why is this needed**:
On [1.12](https://github.com/kubernetes/kubernetes/pull/63572) release we start to create one ICMP rule per loadBalancerSourceRanges, that decrease the rule limit by a half. So it would be nice if we use 2 security group to avoid this.

/sig aws
/kind feature
/cc @kubernetes/sig-aws-misc

**Comment by rlees85** [comment]
This is actually a really good idea (or at least something along these lines) and should not have been closed in my opinion. Putting a line in the security group for do not fragment for each IP address allowed seemed excessive (0.0.0.0/0 was fine it seemed it got merged just because some people did not like the LOOK of 0.0.0.0/0 being in a SG).

Now the limit has been halved....
