### ISSUE TITLE
Add .kube/plugins to the search path for kubectl plugin discovery

### ISSUE THREAD

**Issue by mauilion** [kubernetes/kubernetes#73289]
**What would you like to be added**:
I'd like to append ~/.kube/plugins to the default search path for kubectl plugins.

**Why is this needed**:
In some cases (like windows) it's difficult to install a kubectl-plugin binary in the path or to require that the user define the path to pick up the location of the kubectl-plugin that has been added. 
As an alternative I think it makes sense to define some default "well known" path to place plugins into so that we can keep some sense of portability without having to modify the system path. 

I propose we use ~/.kube/plugins for this as we already use ~/.kube for config options.

**Comment by ncdc** [comment]
cc @soltysh @juanvallejo

**Comment by soltysh** [comment]
That's fair suggestion, let's talk this through during our next SIG call, next Wed.

**Comment by mattfarina** [comment]
Since I shared this on the SIG CLI meeting...

* Over on Helm we've gotten request for a system install location or plugins. There are cases where plugins are needed but access is not available in the users directory to add them but you can have system admin install them in a location they manage. I would look at this case and would not be surprised if this case came to kubectl as well.
* There is a standard for the hierarchy on this at https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html. This may be useful to look at. It has been done on both posix and windows.

**Comment by soltysh** [comment]
@mauilion I've looked through the specification that @mattfarina linked and I think it nicely aligns with your proposal. I've tried on several machines (all linux) and haven't seen those envs from spec filled in, so I'm :+1: on just implementing that dir, the majority of SIG participants on Wednesday were in agreement.
