### ISSUE TITLE
Need System OOM testing on Windows

### ISSUE THREAD

**Issue by PatrickLang** [kubernetes/kubernetes#73417]
Kubelet and System-reserve are implemented on Windows along with pod/container reserves which can help prevent overprovisioning, but we still need to test OOM behavior. We need a test case that will:

1. Set kubelet & system reserve
2. Schedule pods until node is full
3. Run something that will take up system ram so that OOM is triggered

/sig windows
/milestone v1.14

**Comment by jsturtevant** [comment]
I have started to look into this test case and have a few questions:

What is the expected behavior we are testing for?  What does "run something that will take up system ram" mean?  Does that mean run a pod that uses up memory or run a system service that uses memory?

After setting the reserves `kubelet --system-reserved` and `--kube-reserved` as mentioned in [release notes for 1.13](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.13.md#sig-windows-1) we should be able to schedule pods until full and then once we trigger OOM (either by pod or system service) kubelet should continue running becuase of the reserves?  

Do the two settings need to be tested independently or they should be tested together?  I found [this test](https://github.com/kubernetes/kubernetes/blob/master/test/e2e_node/node_container_manager_test.go) that seems to be doing something similar but it is in node-e2e.  Is sig-windows running node-e2e tests currently?

**Comment by jsturtevant** [comment]
After researching this further and talking with @PatrickLang I found that the [node container manager test](https://github.com/kubernetes/kubernetes/blob/master/test/e2e_node/node_container_manager_test.go) does test the allocatable memory but uses CGroups to set reserves to test the reported vs actual.  As windows does not have CGroups this test will not port as is.  

There is [no OOM Killer in the windows kernal](https://github.com/kubernetes/kubernetes/issues/73418#issuecomment-461906189) and the `--enforce-node-allocatable` is not implemented so [eviction based tests](https://github.com/kubernetes/kubernetes/blob/addcd7bb079d2b2709d4a1a06cb121db09347870/test/e2e_node/eviction_test.go#L134) will not work either.  

The proposed testing solution would be two parts:

1. Set kubelet & system reserve and verify allocatable is reporting properly.  

    - Schedule pods with known memory consumption values and verify the allocatable is correclty updated. 

    - Schedule until full and verify scheduling is not allowed.

2. Set kubelet & system reserve and verify allocatable is reporting properly.  

    - Schedule Schedule until full and verify scheduling is not allowed.

    - ssh into machine and run process that consumes memory and verify kubelet and pods remain running.

There is an open question on the second test as to whether kubelet and will be have properly.  If it does not we will submit test 1 and open an issue to resolve 2.

**Comment by rhockenbury** [comment]
I would suggest adding a third case that would test the behavior when excessive memory pressure is exerted on the node from the pods.  This is perhaps a more common use case than 2 since the pod workloads are more likely to exhibit greater resource variability than node system processes.   It would also carry over as a test for when/if node allocatable enforcement get implemented for windows nodes. 

Additionally, to complement this work would it be suitable to test windows pod memory limit enforcement?  Or is this tested elsewhere?

**Comment by jsturtevant** [comment]
> This is perhaps a more common use case than 2 since the pod workloads are more likely to exhibit greater resource variability than node system processes. It would also carry over as a test for when/if node allocatable enforcement get implemented for windows nodes.

Agreed this is a more common case. 

> Additionally, to complement this work would it be suitable to test windows pod memory limit enforcement? Or is this tested elsewhere?

I am not sure that it is.  Is this tested on linux somewhere?

**Comment by jsturtevant** [comment]
I am seeing strange numbers reported when performing a test case.  I scheduled a few pods to test memory limits and then schedule a pod with no memory limit and a process that will consume all of the available memory 500mb at a time:

```
apiVersion: v1
kind: Pod
metadata:
  name: memory-win-oom
spec:
  containers:
  - name: memory-win-oom
    image: jsturtevant/win-stress
    args: ["-d", "500"]
  nodeSelector:                                               
    beta.kubernetes.io/os: windows 
```

After the pod consumes all available memory, When I compare Node Allocatable/Node usage/Pod Usage I am not seeing the numbers add up properly:

```
k top pods                         
NAME                   CPU(cores)   MEMORY(bytes)      
memory-demo            36m          150Mi              
memory-demo-2          324m         869Mi              
memory-win-limit       0m           90Mi              
memory-win-oom         7m           6367Mi             
memory-win-overlimit   0m           85Mi                                              

k top nodes          
NAME                       CPU(cores)   CPU%      MEMORY(bytes)   MEMORY%                                           
1024k8s000                 38m          1%        6962Mi          115%                                              
k8s-linuxpool-10245084-0   424m         21%       1402Mi          20%                                               
k8s-master-10245084-0      195m         9%        1966Mi          24%  

k describe node 1024k8s000 
Capacity:   
    attachable-volumes-azure-disk:  4                             
    cpu:                            2                      
    ephemeral-storage:              132655100Ki            
    memory:                         8388148Ki              
    pods:                           30                    
Allocatable:                                            
    attachable-volumes-azure-disk:  4                      
    cpu:                            2                      
    ephemeral-storage:              122254939958           
    memory:                         6188596Ki             
    pods:                           30     
```

My node is staying online and kubelet is reporting no memory pressure.  The total node memory consumption is over the Allocatable memory.  

```
Type             Status    LastHeartbeatTime                 LastTransitionTime                Reason                       Message 
----             ------    -----------------                 ------------------                ------                       -------                                                                   
MemoryPressure   False     Mon, 18 Feb 2019 19:20:39 +0000   Wed, 13 Feb 2019 01:56:23 +0000   KubeletHasSufficientMemory   kubelet has sufficient memory available  
```

What is the expected behavior and what should the test look like?

**Comment by rhockenbury** [comment]
I believe node allocatable will always just be capacity minus reserves (system and kubelet) - https://github.com/kubernetes/kubernetes/pull/69960.  So in this scenario it looks like you have `--kube-reserved` and/or `--system-reserved` set?  The memory % on the node is relative to the allocatable amount, and still seems to be under the total memory capacity - are you sure that all available memory has been consumed by your oom pod?  

The node should be tainted with memory-pressure when a hard or soft eviction threshold is met (https://kubernetes.io/docs/tasks/administer-cluster/out-of-resource/#node-conditions).   What do you have set for `--eviction-hard` and `--eviction-soft`?

**Comment by jsturtevant** [comment]
Thanks for the clarification.  I currently have these settings: 

```
--eviction-hard=memory.available<100Mi,nodefs.available<10%,nodefs.inodesFree<5%
--system-reserved=memory=2Gi 
```

And on the machine I am seeing most memory being used:

```
PS C:\Users\adminuser>  systeminfo | findstr "Memory"                                                                                            Total Physical Memory:     8,192 MB                                                                                                              Available Physical Memory: 238 MB                                                                                                                Virtual Memory: Max Size:  16,288 MB                                                                                                             Virtual Memory: Available: 17 MB                                                                                                                 Virtual Memory: In Use:    16,271 MB 
```

If I understand correctly,  I start to see memory-pressure once I get into the `--eviction-hard` setting above. In that case I should start to see pods get evicted, so for a valid test I could adjust the values to be easier to hit then test to see that pods get evicted properly which would be similar the [PriorityMemoryEviction test](https://github.com/kubernetes/kubernetes/blob/b67126e350fdba6d89a0ee64310cac7db14e33d3/test/e2e_node/eviction_test.go#L284).

I am going to adjust a few of the settings and manually test that this is working then see what it will take to port the PriorityMemoryEviction, which currently uses cgroups which won't work on windows. This combined with testing that Memory Allocatable is being properly set should give us a good test coverage for windows on this scenario.

**Comment by jsturtevant** [comment]
I performed manual testing and found that even when memory was used up on the machine the "Memory Pressure" notification was not fired.  

After looking deeper I found [threshold notification](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/eviction/threshold_notifier_unsupported.go) is not implemented for windows.   The [evictionmanger ](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/eviction/eviction_manager.go), which uses cgroups, provides the [Memory Pressure condition](https://github.com/kubernetes/kubernetes/blob/ad403f8e2054d0dcd322e287af17cc3d69b38bf3/pkg/kubelet/kubelet_node_status.go#L544).   This means even though `--eviction-hard` is being subtracted from node allocatable for windows it isn't used.  

On Windows, Node allocatable when used with limits and requests does prevent the node from over scheduling.  I believe the the test `[sig-api-machinery] ResourceQuota should create a ResourceQuota and capture the life of a pod.` and [`validates resource limits of pods that are allowed to run`](https://github.com/kubernetes/kubernetes/blob/6b2a01709cb5636fb2bb2f71768c5c929320abd1/test/e2e/scheduling/predicates.go#L227) (this only shows cpu and I could not find a test that demonstrated memory) demonstrate this works.  But this doesn't stop a pod from consuming all the memory on the node and since eviction (hard/soft/node allocatable) is not implemented on windows this means a node can end up resource starved. 

I think the only valid test to be written for this scenario, as it stands now, is validating that Node Allocatable is being reported properly.  Beyond that there is no functionality that can be validated around OOM behavior for the windows node.

**Comment by rhockenbury** [comment]
Yeah, that sounds to be in agreement with what I've observed on the windows nodes that I run. 

To prevent resource starvation (as a workaround), would setting mem/cpu requests equal to mem/cpu limits for all windows pods work?  I think the request / limit values get passed down into the docker daemon when it starts a container, so is it possible that docker could enforce the memory limit?

**Comment by jsturtevant** [comment]
Yes, setting limits==requests would help the scheduler not over provision the nodes.  

@craiglpeters @PatrickLang I think the best way to approach this particular issue for 1.14 is to make sure docs call out what works/doesn't work and give guidance to on how to prevent resource starvation on nodes.  Is there a place in the docs that would make sense for this information?

The call outs would be:
-   `--kubelet-reserve`, `--system-reserve` , and `--eviction-hard` flags do update Node Allocatable
-  `--enforce-node-allocable` is not implemented
- `--eviction-hard` and `--eviction-soft` are not implemented
- `MemoryPressure` Condition is not implemented in Windows
- There are no OOM actions taken by kubelet
- As a work around to previous, `Requests` and `Limits` should always be equal to prevent memory resource starvation as this allows the scheduler to to use limits and `node-allocatable`
- Kubelet running on the windows node does not have memory restrictions.  `--kubelet-reserve` and system-reserve does not set limits on kubelet or processes running the host.  This means kubelet or a process on the host could cause memory resource starvation outside the `node-allocatable` and scheduler

**Comment by michmike** [comment]
thank you for the thorough investigation @jsturtevant
