### ISSUE TITLE
Implement terminationGracePeriodSeconds on Windows

### ISSUE THREAD

**Issue by PatrickLang** [kubernetes/kubernetes#73434]
`V1.Pod.terminationGracePeriodSeconds` is not implemented correctly on Windows. Currently, Docker doesn't have a configurable timeout on Windows, see: [reference](https://github.com/moby/moby/issues/25982), so it can't be implemented. The behavior today is that the ENTRYPOINT process is sent `CTRL_SHUTDOWN_EVENT`, then Windows waits 5 seconds by hardcoded default, and finally shuts down all processes using the normal Windows shutdown behavior. The 5 second default is actually in the Windows registry [inside the container](https://github.com/moby/moby/issues/25982#issuecomment-426441183), so it can be overridden when the container is built.

To fix this the right way, we need to:

1. Migrate to CRI-ContainerD
2. Separate the calls to send`CTRL_SHUTDOWN_EVENT`
3. Wait for the requested `terminationGracePeriodSeconds`
4. Proceed with forceful shutdown of the containers and pod

**Comment by PatrickLang** [comment]
This may work on recent versions of Docker and Windows Server 2019, but needs testing.

/milestone 1.16

**Comment by sirdank** [comment]
FWIW, this is working for me using AKS with a container image built on mcr.microsoft.com/dotnet/framework/aspnet:4.7.2-20190611-windowsservercore-ltsc2019.

**Comment by PatrickLang** [comment]
/reopen

We should be able to fix this after migrating to containerD - ETA by end of 2020.

Until then there's a workaround you can do by setting a regkey inside the container to give it more time to shut down the app

**Comment by marosset** [comment]
/reopen
This requires containerD as Patrick mentioned previously.
We'll prioritize enabling/testing this scenario in 1.19

**Comment by marosset** [comment]
I have manually validated that termination grace period works today on Windows with recent builds of containerd using this project

https://github.com/marosset/windows-container-graceful-shutdown/tree/master/go

I want to add some e2e coverage in k/k.

**Comment by coderanger** [comment]
At a minimum it would be good if the Kubelet would yell loudly about pods with a non-default value. Silently accepting config that is ignored is frustrating.

**Comment by marosset** [comment]
The issue here is that docker on Windows is ignoring shutdown messages the kubelet is sending.
Kubelet itself things everything is OK and is behaving correctly.
We do not want to disable graceful termination behavior on Windows because this functionality does work if using containerd as the container runtime instead of docker.

**Comment by jingxu97** [comment]
@marosset Just want to check when it is possible to have this implemented in containerD? Thanks!

**Comment by marosset** [comment]
It actually should be working in containerD today :)

**Comment by jingxu97** [comment]
So since containerD already supports it. For users, they don't need to handle CTRL_SHUTDOWN_EVENT, kubelet should perform this automatically during pod termination. Is that correct?

**Comment by jingxu97** [comment]
@marosset has an example of graceful shutdown https://github.com/marosset/windows-container-graceful-shutdown
Thanks!

**Comment by marosset** [comment]
/close

Termination grace period is working for Windows pods/containers with CRI-ContainerD and there are no plans to update docker / moby to get support this.

**Comment by chrismilson** [comment]
I came across this thread while trying to implement lengthy grace periods for windows containers. We eventually got @marosset's example working in our cluster, but to do that we also had to set the registry key, [`HKLM:\SYSTEM\CurrentControlSet\Control\WaitToKillServiceTimeout`](https://docs.microsoft.com/en-us/windows/win32/services/service-control-handler-function?redirectedfrom=MSDN), so that the container didn't kill itself either. This is set to 5s by default.

We used the following powershell script in our Dockerfile to change that to our intended `terminationGracePeriod`:

```dockerfile
RUN Set-ItemProperty -Path "HKLM:\CurrentControlSet\Control" -Name "WaitToKillServiceTimeout" -Value "30000"
```

The problem with this is that we are now required to know the intended grace period at image build, rather than being able to change it on the fly by updating `terminationGracePeriod` on the pods etc. If anyone comes up with any novel ideas to work around this it would be great to hear about.

**Comment by AbelHu** [comment]
> /close
> 
> Termination grace period is working for Windows pods/containers with CRI-ContainerD and there are no plans to update docker / moby to get support this.

terminationGracePeriodSeconds works with nanoserver based container images but not servercore based images
https://github.com/microsoft/Windows-Containers/issues/164
