### ISSUE TITLE
ELB Security Group not cleaned up when extra specified

### ISSUE THREAD

**Issue by mat285** [kubernetes/kubernetes#73480]
**What happened**:

Security groups created for k8s elbs on AWS are not deleted when the service and load balancer are deleted.  This caused the number of security groups to keep growing even as the number of services did not.

**What you expected to happen**:

When deleting a load balancer service, the load balancer's associated security group should also be deleted.

**How to reproduce it (as minimally and precisely as possible)**:

Create a load balancer service on aws specifying `service.beta.kubernetes.io/aws-load-balancer-extra-security-groups`

Wait for the load balancer and security group to be created.

Delete the service on kube.

Observe that the elb is deleted, but the security group created for the elb still exists.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.10.11
- Cloud provider or hardware configuration: AWS
- OS (e.g. from /etc/os-release): Ubuntu 16.04.4 LTS (Xenial Xerus)
- Kernel (e.g. `uname -a`): Linux 61-Ubuntu  x86_64 GNU/Linux
- Install tools: Kops . v1.10.0

**Comment by M00nF1sh** [comment]
The root cause is [updateInstanceSecurityGroupsForLoadBalancer](https://github.com/kubernetes/kubernetes/blob/a780dd78d30616c5bbf254244013d784a73c5d39/pkg/cloudprovider/providers/aws/aws.go#L3909) doesn't play well with "service.beta.kubernetes.io/aws-load-balancer-extra-security-groups" and "service.beta.kubernetes.io/aws-load-balancer-security-groups"(added in v1.13). 

And this behavior is unpredicatable, and totally depends on the order of securityGoup returned by ELB.  
I don't know how the order of sgs returned by ELB API is determined(or just pure random), but i'm capable to manipulate the order either my manually adding/remove sg from aws console, or toggle the annotations on service. So the code should be changed to support multiple securityGroups on ELB.

**Comment by chris-brace** [comment]
I'm seeing this too but in a totally different situation. Im getting strange results trying to add and remove `nginx-ingress` helm chart via terraform. Terraform hangs when deleting:

```0s    Warning   DeletingLoadBalancerFailed   Service   Error deleting load balancer (will retry): timed out deleting ELB: nginx-ingress-singleton-controller. Could not delete security groups sg-0deb0d409fe5f1c99```

As far as i can tell, its deleting the ELB, then trying to delete the security group it set up which fails because it appears to have created a rule in another security group referencing the one it created. AWS does not allow you to delete security groups with live references from other resources (ec2, other sgs, etc.)

**Comment by lolzyloz** [comment]
@M00nF1sh\ @mat285 Hi, regarding this issue, what about the case when we are trying to associate an existing security group to a load balancer that we are creating, but we do not wish to delete the security group after we delete the load balancer?

**Comment by kverstr** [comment]
As an addition to @lolzyloz comment. We were under the impression we could add existing SG's to the ELB by adding the "service.beta.kubernetes.io/aws-load-balancer-extra-security-groups" annotation.
This works, **however the "service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags" annotation is adding tags to this existing SG as well. Which is not what you want for an existing SG.** This could break a lot because of the SG name being changed.

**Comment by jlforester** [comment]
We're also seeing this issue.  Manually deleting the service deletes the ELB, but not the the SG or the reference it creates inside the node SG.  Same thing with Terraform and Helm releases.  Using EKS with v1.14.8-eks-b8860f.

**Comment by iTaybb** [comment]
We're seeing this issue as well.

**Comment by ozankabak** [comment]
Running into this issue too.

**Comment by caphrim007** [comment]
I am seeing this behavior for EKS 1.16. The SG associated with the ELB is not removed due to a failure to remove that SG's entry from the Node SG's ingress list.

**Comment by Shahard2** [comment]
I'm also facing it,
Any workaround so far?

**Comment by Shahard2** [comment]
> I'm also facing it (EKS 1.17)
> Any workaround so far?

@nckturner 
@M00nF1sh

**Comment by Shahard2** [comment]
> Issues go stale after 90d of inactivity.
> Mark the issue as fresh with `/remove-lifecycle stale`.
> Stale issues rot after an additional 30d of inactivity and eventually close.
> 
> If this issue is safe to close now please do so with `/close`.
> 
> Send feedback to sig-testing, kubernetes/test-infra and/or [fejta](https://github.com/fejta).
> /lifecycle stale

don't close it, still relevant

**Comment by mmbcn** [comment]
Having same issue here. When deleting ingress ELB gets deleted but SG stay behind and that causes the VPC module in Terrafomr to fail ( not being able to delete VPC cause of X resources, SG from ELB,  that are not created by Terraform exist - dependency ). 

Any ideas on how to fix this or get attention of the right people?

Thx!

**Comment by iTaybb** [comment]
Can someone please open this issue? This is still relevant
