### ISSUE TITLE
hack/godep-restore.sh fails if GOPATH is not set

### ISSUE THREAD

**Issue by vllry** [kubernetes/kubernetes#73504]
**What happened**:
Running `hack/godep-restore.sh` will fail if GOPATH is not set. This is invisible if called from a context like `make update`.

This seems to specifically be caused in `kube::util::godep_restored`, in `hack/lib/util.sh`.

**What you expected to happen**:
The script should be able to use the default implicit GOPATH.

**How to reproduce it (as minimally and precisely as possible)**:
`unset GOPATH && ./hack/godep-restore.sh`

**Anything else we need to know?**:

**Environment**:
go version go1.11.4 darwin/amd64

**Comment by vllry** [comment]
cc @cblecker

**Comment by cblecker** [comment]
/sig testing contributor-experience
cc: @kubernetes/bash-firefighters

I’m sure there’s lots of places where we expect a GOPATH.. should review and either error more explicitly, or just Do The Right Thing.

**Comment by BenTheElder** [comment]
@cblecker can we do the right thing and get rid of `godep` though? 😉

**Comment by ixdy** [comment]
hm, this appears to have been added in https://github.com/kubernetes/kubernetes/pull/42726, well after we were using `vendor/`. @sttts commented
> Moreover, call `hack/godep-restore.go` from `hack/update-all-staging.sh`. This was an actual bug.

but I'm not sure what the bug was or if this is still necessary.

(My understanding is that nowadays you really only need to use `hack/godep-restore.sh` and `hack/godep-save.sh` when updating deps, and ideally you call those using `hack/run-in-gopath.sh` so you don't pollute your real GOPATH.)
