### ISSUE TITLE
Implement "machine shutdown"

### ISSUE THREAD

**Issue by piosz** [kubernetes/kubernetes#7351]
As @davidopp wrote:
(1) Operator does "kubectl stop node" or "kubectl delete node" I just tested these and neither does anything on GCE; the first one gives an error "no reaper has been implemented for "Node"" and the second one claims to work (prints node name in response, gives no error) but nothing happens (node is still there, pod is still running, etc.)

(2) Operator deletes the VM instance. This is surprisingly hard to do on GCE because we use managed instance groups to auto-restart the VM very quickly, and at least via the UI you can't delete the MIG without deleting the VMs, so I'm not sure how to test this (this being delete the VM, wait a while, and see how the pod is treated). But the NodeController code (that I guess is being moved into Kubelet soon) calls into the API server to delete the node
https://github.com/GoogleCloudPlatform/kubernetes/blob/65d132a3eecee38fc22e82ff5fd9e100aae342be/pkg/cloudprovider/nodecontroller/nodecontroller.go#L324
which I assume is basically the same as (1) hence it doesn't really do anything. Have we tested anything with regard to machine shutdown?

Extracted from #6804

cc @davidopp @bgrant0607

**Comment by zmerlynn** [comment]
We recently tested reboot, which is different but similar. (See #5666, #7051)

**Comment by roberthbailey** [comment]
I can't speak to how this works today, but I actually did this test over the weekend by deleting a node from the MIG by just resizing the MIG on my e2e cluster from 2 nodes to 1 node. I didn't get to pick which node was replaced, but one of them went away. 

I was running this test against #6949 to see what happens and I observed that (after my change) the NodeController saw the Kubelet go from Ready --> NotReady, checked the cloud provider (GCE) and saw that the node no longer existed and then removed the node from the cluster (along with all of the pods on the node). The pods were then restarted on the remaining node (because they were underneath a replication controller).

**Comment by bgrant0607** [comment]
Is this about temporary shutdown/disruption, permanent deletion, both?

Deletion should follow the graceful termination pattern (#1535), using DeleteOptions. 

For temporary administrative shutdown, we could add another bool similar to unschedulable, but which would have the additional effect of evicting all existing pods.

**Comment by davidopp** [comment]
Graceful node evacuation came up in a meeting today, so adding 
@lavalamp @dchen1107 @mbforbes @zmerlynn @alex-mohr @roberthbailey

**Comment by roberthbailey** [comment]
@zmerlynn too

**Comment by gosharplite** [comment]
I have created an openstack-coreos-kubernetes cluster based on @kelseyhightower [osdc-2015 demo](https://github.com/kelseyhightower/osdc-2015). Since it is very easy to delete a VM instance in openstack, I did a quick test relate to this issue.

My replica controller created 3 pods on different nodes. When one of the node is deleted, I observed 'kubectl get mi' of the deleted node went from Ready --> NotReady. After a while, kubernetes killed the pod on the deleted node but immediately tried to reschedule a pod on the same deleted node. It then killed the pod again and rescheduled a pod on a 'Ready' node. System became stable.

I resized replicas to 10 and observed kubernetes still tried to schedule pods on the 'NotReady' node. After I performed 'kubectl delete mi (NotReady node ip)', pods with 'Pending' status on the NotReady node were frozen in the system. kubernetes took no action to kill them.

I observed two strange behaviors.
(1) Schedule pod to a NotReady node. 
(2) Pending pods frozen in the system.

Hopefully graceful termination pattern (#1535) will fix these behaviors.
```
$ kubectl version
Client Version: version.Info{Major:"0", Minor:"15", GitVersion:"v0.15.0", GitCommit:"831f3e60d7cd64c61a775d6c78acce1673dd8aa9", GitTreeState:"clean"}
Server Version: version.Info{Major:"0", Minor:"15", GitVersion:"v0.15.0", GitCommit:"831f3e60d7cd64c61a775d6c78acce1673dd8aa9", GitTreeState:"clean"}
```

**Comment by piosz** [comment]
@gosharplite we are aware of the issue you described. For more context please take a look #7222

**Comment by wojtek-t** [comment]
@gosharplite - as @piosz wrote, we are aware of that and this should be fixed within days

**Comment by gosharplite** [comment]
@piosz @wojtek-t Got it, thanks!

**Comment by mingfang** [comment]
+1

**Comment by Scentus** [comment]
+1

**Comment by davidopp** [comment]
Related to #3885 but not the same.

**Comment by bgrant0607** [comment]
cc @mml

**Comment by mml** [comment]
After draining as in #3885 the node has no pods running and is marked unschedulable.  Reading the original report, (1) seems to want a way to administratively remove the node entirely (kubectl delete node), which I agree *should* work.  (2) is about implementing a more useful policy when a node completely disappears.  In this case, a VM was deleted, but any machine, virtual or physical, can break in such a way that it's indistinguishable from the outside.

Assuming the administrator does not come along and delete the node, (2) is about gracefully dealing with unreachability.  I think we should separate this into two bugs.

**Comment by Scentus** [comment]
Something else that came up during some testing is that a node being shut down should be removed from any LoadBalancer pools early with kube-proxy either verified to be idle or given a timeout to become as such so that the loss of active connections is minimized.

**Comment by ihmccreery** [comment]
I believe (1) and (2) in the original comment are distinct ((1) being initiated through the API somehow, (2) being initiated by the node or cloud provider), and so I've separated (2) out into #22494.

**Comment by kargakis** [comment]
Related: https://github.com/kubernetes/kubernetes/issues/6080

**Comment by bgrant0607** [comment]
We have drain and cordon
