### ISSUE TITLE
Doesn't HPA is honored when we execute "kubectl scale deploy" ?

### ISSUE THREAD

**Issue by gautammoulik** [kubernetes/kubernetes#73614]
**What happened**:
I have deployed a service using helm chart, I can see my service, hpa etc. 
In my hpa setting: the min pod count is set to 1. 
I can see my Pod is running and able to handle service request. 

After a while ---
I ran "kubectl scale deploy <my deployment name> --replicas=0"
Once I run the above above command I can see my pod is deleted (although the hpa min pod setting was set to 1), I was expecting after a while hpa will upscale to min pod count i.e. 1. However I don't see that happened, I have waited more than an hour no new pod created by hpa.

**What you expected to happen**:
The expectation was, the Pod should be getting deleted however the hpa should bring back the Pod.I have waited for an hour however hpa didn't bring back the pod.
I can see the service, deployment and hpa is still available however the pods doesn't come back even after an hour.
I have also tried sending a request to my Kubernetes service and I was thinking now hpa will scale up the pod, since there is no pod to serve the request, however the hps doesn't seem to do that. 

Here is what I can see in kubectl get hpa 
**NAME      REFERENCE             TARGETS                  MINPODS   MAXPODS   REPLICAS   AGE****
test          Deployment/xxxx    <unknown>/1000%    1                    4                   0          1h

Interestingly, 
1. hpa downscale works quickly: when I execute "kubectl scale deploy <deployment name> --replicas=2" (please note that the in hpa count is 1), I can see 2 pods gets created quickly however within 5 mins 1 pod gets removed by hpa (hence hpa is scaling down).

Is this is expected behavior of Kubernetes (particularly hpa) ? 
as in, if we delete all pods by executing --"kubectl scale deploy <deployment name> --replicas=0", 
1) the hpa won't block to reduce the replica count less than pod count configured.
2 ) the hpa won't scale up (based on the hpa spinning cycle) to the min number of pods as configured and 3) until we redeploy or execute another round of ""kubectl scale deploy" to update the replica count there will be no pods.

Please confirm.

**How to reproduce it (as minimally and precisely as possible)**:
Deploy a Kubernetes service, configure the hpa for this service and set min pod count as 1. 
Execute "kubectl scale deploy <deployment name> --replicas=0" 

I have deployed the service using helm, because it is easy keep all these resources configuration( pod, hpa, service) in one yaml file. 
Please note that the similar issue is observed in (https://github.com/kubernetes/kubernetes/issues/25238 and https://github.com/kubernetes/kubernetes/issues/66385 )

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): Client version 1.10.8, Server version 1.8.7
- Cloud provider or hardware configuration: AWS
- OS (e.g. from /etc/os-release): Ubuntu 16.04.5 
- Kernel (e.g. `uname -a`): Ubuntu
- Install tools: 
- Others:

**Comment by gautammoulik** [comment]
Can someone help me adding the sig label ?
Is it something I have mention part of the description above ? as in, 
sig # @kubernetes/sig-contributor-experience-bugs

**Comment by cblecker** [comment]
Please re-post your question to [Stack Overflow](http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases.

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans Stack Overflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search Stack Overflow for answers to similar questions, and also familiarize yourself with:

  * [user documentation](https://kubernetes.io/docs/)
  * [troubleshooting guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/)

Again, thanks for using Kubernetes.

The Kubernetes Team

---
/triage support
/close
