### ISSUE TITLE
Downward API for service environment vars

### ISSUE THREAD

**Issue by pmorie** [kubernetes/kubernetes#7365]
Forking from discussion on #6739

We should be able to set environment vars for service information using the downward API mechanism from #6739.  Since services are not local to the object, we need a way to specify them in the API.  How about:

``` go
type EnvVarSource struct {
  FieldPath        *ObjectFieldSelector
  ServiceFieldPath *NamedObjectFieldSelector
}

type NamedObjectFieldSelector {
    ObjectFieldSelector

    Name string
}
```

This will definitely lurch us closer to a full `ObjectReference`.

@thockin @bgrant0607 @smarterclayton

**Comment by thockin** [comment]
Quoting myself:

Services wanders into a whole different discussion - the pre-declaring
service-deps topic.  I don't yet have an opinion as to whether we should
have an env var source way to do this, but I do think it is more
complicated that you have listed here.

Service have multiple ports - do I have to call out each one I want?  How
do I express named ports, rather than indexed? etc.

**Comment by smarterclayton** [comment]
To that question - how does anyone do simple service discovery with multiport services today (answer, they don't).  I think of env injection as enabling simple cases (why am I hardcoding ports in my config files) vs necessarily being infinitely useful.  So "first port" or "named port" or "port by index" are probably descending levels of importance (referencing a port by its index makes me shudder a bit).  Still, because we allow port remapping for service authors, it may be more acceptable to hardcode port values.

**Comment by thockin** [comment]
I agree that port discovery is less important than IP discovery, but we
have DNS and we have teh relatively agnostic FOO_SERVICE_HOST env vars.  Do
we really need more complexity?

**Comment by bgrant0607** [comment]
There's quite a bit of discussion on service downward API in #1768.

**Comment by pmorie** [comment]
> but we have DNS and we have teh relatively agnostic FOO_SERVICE_HOST env vars.

Hrm.  Since we can fully control entrypoint now, technically you can always set params in your command if your image has a shell.

**Comment by thockin** [comment]
We also have env-expansion into other env vars, so I am calling this done.

**Comment by bgrant0607** [comment]
@pmorie @thockin Reopening. The implicit nature of current service link variables is problematic. I'd like explicit object references, similar to what we have for ConfigMap and Secret.

ref #1768

**Comment by bgrant0607** [comment]
see also #15844

**Comment by smarterclayton** [comment]
Cockroachdb had an example of this surprising a user.

**Comment by thockin** [comment]
Yeah, the utility of this might be nearing the end of its life, though a few are very special (KUBERNETES_SERVICE_HOST and friends).  Sadly, it will have to be opt-out for v1..
