### ISSUE TITLE
Failing storage tests: In-tree Volumes [Driver: local] [Testpattern: Pre-provisioned PV (xfs)]

### ISSUE THREAD

**Issue by shyamjvs** [kubernetes/kubernetes#74095]
**Which jobs are failing**:
- ci-kubernetes-e2e-kops-aws
- pull-kubernetes-e2e-kops-aws

**Which test(s) are failing**:
- [sig-storage] In-tree Volumes [Driver: local][LocalVolumeType: block] [Testpattern: Pre-provisioned PV (xfs)] volumes should allow exec of files on the volume
- [sig-storage] In-tree Volumes [Driver: local][LocalVolumeType: block] [Testpattern: Pre-provisioned PV (xfs)] volumes should be mountable

**Since when has it been failing**:
Don't know.. as the job was down for a while due to https://github.com/kubernetes/kubernetes/issues/73444

**Testgrid link**:
- https://testgrid.k8s.io/google-aws#kops-aws
- https://testgrid.k8s.io/presubmits-kubernetes-nonblocking#pull-kubernetes-e2e-kops-aws

**Reason for failure**:
To be found..

**Anything else we need to know**:

This issue is a blocker for turning on the kops-aws presubmit, see - https://github.com/kubernetes/kubernetes/issues/73444#issuecomment-463830125.

/cc @kubernetes/sig-storage-bugs 
/kind failing-test
/sig storage

**Comment by shyamjvs** [comment]
cc @davidz627 @leakingtapan

**Comment by leakingtapan** [comment]
By looking at the log this line is suspicious:
```
FailedMount: MountVolume.MountDevice failed for volume "local-q86vl" : local: failed to mount device /dev/loop0 at /var/lib/kubelet/plugins/kubernetes.io/local-volume/mounts/local-q86vl (fstype: xfs), error executable file not found in $PATH
```
Both testcases share similar error message

**Comment by msau42** [comment]
Looks like the test needs to skip XFS on environments that do not support XFS

**Comment by msau42** [comment]
This is where the environment is checked to skip xfs: https://sourcegraph.com/github.com/kubernetes/kubernetes/-/blob/test/e2e/storage/testsuites/base.go#L126

**Comment by shyamjvs** [comment]
Thanks Michelle!

@leakingtapan - Could you comment if we need to skip it in aws tests?

**Comment by justinsb** [comment]
Looks like this was broken by #72002 - shall we revert?

cc @pohly

**Comment by justinsb** [comment]
Actually looking at the GCE tests for kops it was broken before #72002.  I'm wondering if we assumed xfs back in #73525

**Comment by zetaab** [comment]
/priority critical-urgent

this is blocker for kops currently

**Comment by zetaab** [comment]
@cofyc do you have idea could #73525 break this?

**Comment by cofyc** [comment]
> Actually looking at the GCE tests for kops it was broken before #72002. I'm wondering if we assumed xfs back in #73525

Yes, in #73525, I added tests for local volume which use `xfs` [in supported types](https://github.com/kubernetes/kubernetes/pull/73525/files#diff-d1a5ece2215eb348ea751cd0ac48592fR1647). Because [`xfs` is skipped in GCI environment](https://github.com/kubernetes/kubernetes/blob/c90bf8d8ea6e02014008ee9e1afe490bee4a0bcf/test/e2e/storage/testsuites/base.go#L126), PR is not blocked by gce e2e test.

hi, @zetaab  Quick way to fix is to remove `xfs` from supported types, I'm going to submit a PR for this.

**Comment by cofyc** [comment]
Alternatively, we can skip `xfs` for environments which do not support XFS [here](https://github.com/kubernetes/kubernetes/blob/c90bf8d8ea6e02014008ee9e1afe490bee4a0bcf/test/e2e/storage/testsuites/base.go#L126).

What do you think?

**Comment by zetaab** [comment]
@cofyc I do not know what is the best solution in long term but in short term we should get kops e2e tests working. So if removing xfs from supported types is fastest solution - i would go with that. After that tests could be fixed how those should be.

Could you do that PR and remove `xfs` from supported types?

**Comment by pohly** [comment]
Hard-coding the knowledge which clusters or tests support XFS (because that's what it is - a dependency on a kernel feature, right?) in the test source code is just bound to fail eventually.

What if the presence of xfs support depends on the "gci" version? This line doesn't cover that:
https://github.com/kubernetes/kubernetes/blob/c90bf8d8ea6e02014008ee9e1afe490bee4a0bcf/test/e2e/storage/testsuites/base.go#L126

I would prefer to mark tests which depend on XFS kernel support with `[Feature: xfs]`or something like it (no idea how descriptive feature tags need to be) and then enable those test cases only in jobs where the target cluster is known to have XFS.

If you extend that check as a short-term solution, then please file an issue about it and link to it next to the check.

/cc @msau42

**Comment by chrisz100** [comment]
Agreeing with @pohly here... Isn't there a way to check if the kernel we test for/ against is supporting it more directly? Building a huge list of whats compatible and what's not sounds not perfect to me.

**Comment by msau42** [comment]
Long term we can enhance the check to ssh into a random node and see if the mount.xfs binary exists.

Short term let's just remove xfs testing for local volumes.

**Comment by leakingtapan** [comment]
If these two are newly added tests, agree to skip (or remove) xfs testing to unblock PRs.

**Comment by jayunit100** [comment]
assuming all these in-tree tests will be less important over the course of the year as CSI moves forward...

**Comment by msau42** [comment]
The local volume driver plan is to remain in-tree for the medium-term future.  I think we should continue to add the environment check for xfs so we can add it back.
