### ISSUE TITLE
Can't run kubernetes within boot2docker

### ISSUE THREAD

**Issue by acroca** [kubernetes/kubernetes#7428]
I'm following the docker tutorial (https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/docker.md) but I can't make it work.

etc runs without problems, but the master shows some errors on the log: https://gist.github.com/acroca/dac7cdc196b26c6ae65d

I get the following error running containers too:
```
$ kubectl run-container nginx --image=nginx --port=80          
Error from server: the server could not find the requested resource (post replicationControllers)
```
I use boot2docker and docker 1.6.0.

**Comment by a-robinson** [comment]
cc @brendandburns looks like the apiserver didn't come up?

**Comment by acroca** [comment]
Is there anything else I can do to help troubleshooting this issue?

**Comment by erictune** [comment]
Those instructions seem totally broken. The step that is entitled "Run the
master" is actually running the kubelet.

**Comment by erictune** [comment]
Never mind, I see the comment that says "This actually runs the kubelet,
which in turn runs a pod that contains the other master components."

**Comment by erictune** [comment]
Okay, I followed the instructions, and my cluster came up okay.  I also see
similar error messages in my logs (by the way, the logs in the gist are
from kubelet not apiserver).

acroca: what happens when you follow the next steps (setup ssh tunnel, and
then run `kubectl -s http://localhost:8080 get pods`)

**Comment by acroca** [comment]
I can get the pods, nodes and so on, but the problem comes when I try to run a container, create a service or a rc.

**Comment by erictune** [comment]
I'm out next week, so I am not going to be able to work on this.  Someone should try to repro this.

**Comment by Kangmo** [comment]
I have the same problem. I followed instructions on examples/meteor/README.md on master branch, but deployed my k8s cluster with v0.16.2 tag.

**Comment by goltermann** [comment]
We’re going through old support issues and asking everyone to direct your questions to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes). 

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases. 

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.
