### ISSUE TITLE
create podsandbox fails intermittently 

### ISSUE THREAD

**Issue by kumar-shantanu** [kubernetes/kubernetes#74298]
**What happened**:

We are running kubernetes on coreos which is configured to autoupdate itself and reboot as it sees fit. We have noticed after a particular restart pods are unable to schedule itself on the particular nodes with the below error,

Feb 19 10:32:40 ip-172-22-126-113.eu-west-2.compute.internal kubelet[1273]: E0219 10:32:40.696303    1273 kuberuntime_sandbox.go:54] CreatePodSandbox for pod "XXXXX(9ec4f952-3136-11e9-9c40-0a85432fd7ce)" failed: rpc error: code = Unknown desc = NetworkPlugin cni failed to set up pod "XXXXXXXX" network: Get https://100.64.0.1:443/api/v1/namespaces/XXXXXX/pods/XXXXXX-765677978-9rwb5: dial tcp 100.64.0.1:443: i/o timeout
**What you expected to happen**:
Pods should be able to schedule itself on the particular node
**How to reproduce it (as minimally and precisely as possible)**:
If we restart manually for 10-15 times we see this behaviour after one of the restarts.

**Anything else we need to know?**:
The suggested error seems to come every-time when a node restarts, however most of the times it is able to recover from this error and finally pods can schedule themselves on the particular node.

**Environment**:
- Kubernetes version (use `kubectl version`):
v1.9.9
- Cloud provider or hardware configuration:
AWS
- OS (e.g: `cat /etc/os-release`):
Coreos
- Kernel (e.g. `uname -a`):
- Install tools:
Kops
- Others:

**Comment by dcbw** [comment]
What CNI plugin are you using?

**Comment by kumar-shantanu** [comment]
We are using calico version 2.6.7 - and yes 100.64.0.1 is the cluster apiserver

**Comment by dcbw** [comment]
The message after "NetworkPlugin cni failed to set up pod "XXXXXXXX" network:" comes from the network plugin itself, so in this case that would be Calico. It appears that Calico is not able to contact the apiserver for some reason, so you'd want to follow up with Calico/Tigera about what that error occurs. It shouldn't be caused by kubernetes itself.

**Comment by kumar-shantanu** [comment]
sig/Calico

**Comment by caseydavenport** [comment]
>  Get https://100.64.0.1:443/api/v1/namespaces/XXXXXX/pods/XXXXXX-765677978-9rwb5: dial tcp 100.64.0.1:443: i/o timeout

The Calico CNI plugin makes calls to the Kubenretes API usually using the `kubernetes.default` service, so it's relying on kube-proxy to get there. Often when this fails, it's due to something on the kube-proxy side (e.g, not running, misconfigured, etc).

> We have noticed after a particular restart pods are unable to schedule itself on the particular nodes with the below error

Is the error persistent? Or does it eventually resolve itself and the Pod launches? I'm wondering if this might be a transient effect of the restart, where Calico CNI is trying to set up networking for pods prior to the kube-proxy running.

I'd check to see if the kube-proxy is running and healthy on that node at the time you see that error.

**Comment by kumar-shantanu** [comment]
Most of the times it is able to recover from this error and finally pods can schedule themselves on the particular node. However sometimes it never recovers.

**Comment by caseydavenport** [comment]
@kumar-shantanu in the cases where it never recovers, it would be useful to see if the kube-proxy is in fact running and healthy on those nodes. Could you check that?

I suspect that this is not a Kubernetes or Calico bug, but rather something to do with the installation or underlying network itself, but it would be good to understand the root cause.

I'd also note that Calico v2.6 is _very_ old, so independent of this issue I'd suggest upgrading to v3.x. However, like I said above, this currently feels unlikely to be a Calico or Kubernetes bug at its root.

**Comment by caseydavenport** [comment]
I'm going to close this for now since I don't think it is a bug in Kubernetes, but feel free to keep discussing here.

/close
