### ISSUE TITLE
e2e tests for RBAC

### ISSUE THREAD

**Issue by maxbischoff** [kubernetes/kubernetes#74309]
**What would you like to be added**:

I would like e2e tests for RBAC, so that I can test that RBAC is enforced in a running cluster.

**Why is this needed**:

I couldn't find any e2e tests that test RBAC but think that there should be some to ensure that it actually works. Did I miss those tests? Is there a good reason for not having them? Is there interest in contributions of e2e tests for RBAC?

**Comment by liggitt** [comment]
related to https://github.com/kubernetes/kubernetes/issues/62988

since RBAC is an optional feature, adding e2e tests is fine but cannot currently be required as part of conformance

can look at what the PSP tests do to check if RBAC is enabled before deciding if they will run:

https://github.com/kubernetes/kubernetes/blob/master/test/e2e/auth/pod_security_policy.go#L55-L57

**Comment by mikedanese** [comment]
More coverage is always good, but I'd prefer integration tests over e2e tests.
