### ISSUE TITLE
Support a list of namespaces for informers

### ISSUE THREAD

**Issue by skonto** [kubernetes/kubernetes#74415]
**What would you like to be added**:
Enhance the api here: https://godoc.org/k8s.io/client-go/informers to support a list of namespaces
**Why is this needed**:
Operators may need to monitor a subset of all namespaces or even dynamically add one.
I think it could benefit the multi-tenancy story.
 @kubernetes/sig-api-machinery-feature-requests

**Comment by rajathagasthya** [comment]
@kubernetes/sig-api-machinery-feature-requests

**Comment by skonto** [comment]
Any response to this?

**Comment by liggitt** [comment]
I wouldn't anticipate a server-side API being added for this. A layer on top of informers that allows adding/removing watches of specific namespaces could be done client-side.

**Comment by skonto** [comment]
@liggitt there is a discussion about this and the multi-tenancy issue [here](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/kubernetes-wg-multitenancy/Jzaty0FLiy0/yaVJ6RpbCAAJ), you might be aware of it already. There are trade offs when you do that at the client side, many watchers etc..

**Comment by zgfh** [comment]
promethues opeator have support multiwatch,should we copy this? :
https://github.com/coreos/prometheus-operator/blob/master/pkg/prometheus/operator.go#L218
https://github.com/coreos/prometheus-operator/tree/master/pkg/listwatch

**Comment by redbaron** [comment]
@liggitt , client-side code has to revert to quite ugly hacks on resourceVersion (https://github.com/coreos/prometheus-operator/blob/6fb6a3422bdc4ab80afaf14d97f59e45a59af76a/pkg/listwatch/listwatch.go#L156-L158) to transparently implement multi namespace watcher.

**Comment by liggitt** [comment]
That example is not how I expected to accomplish this goal. Rather than constructing a union lister/watcher that munged resource versions, I would recommend a union informer that maintains per-namespace informers and simply routes the resulting AddFunc/UpdateFunc/DeleteFunc calls to a single cross-namespace handler.

**Comment by lavalamp** [comment]
> I would recommend a union informer that maintains per-namespace informers and simply routes the resulting AddFunc/UpdateFunc/DeleteFunc calls to a single cross-namespace handler.

Right. I'm open to making this easy in client-go.

I actually do anticipate eventually having the server permitting watching multiple but not all namespaces; but this is a huge change and I'm not at all convinced we'd do it by actually specifying namespaces individual instead of e.g. adding a shard concept.

**Comment by lilic** [comment]
We are moving away from the above example multi namespace listwatch in prometheus operator right now :) , due to similar problems to what @liggitt mentioned, this was done in the very early days of kuberenetes and we are planning on refactoring it.

I am curious if there were any updates on the following @lavalamp so we can just make use of that instead of making something custom again in prometheus-operator: 
> Right. I'm open to making this easy in client-go.

Thanks!

**Comment by howardjohn** [comment]
@lilic do you have any info on what prom operator is doing instead if you are moving away from that approach?

**Comment by lilic** [comment]
@howardjohn Our current plan is to replace it with an informer per namespace, was searching around right now for the right approach for this and came across this issue.

But we would be interested in contributing to client-go if they are still interested in having the multi namespace abstraction there. Would prefer to maintain the least custom stuff in Prometheus-operator as we can, as we found a few too many bugs around this.

We also use the same custom multi namespace listwatch package in kube-state-metrics from prometheus-operator and we (I am one the maintainers there as well) would be interested in moving away from custom package there as well.

**Comment by howardjohn** [comment]
@lilic we are doing pretty much the same thing in https://github.com/istio/istio/pull/25692 - would also love to see something official in client-go so we don't need to maintain a bunch of stuff. We are even considering doing codegen to get typed multinamespace clients which will be even worse to maintain.

**Comment by lilic** [comment]
ha :) yes the codegen part would be much harder to maintain yes.

I will open a new issue for feature request for this in client-go and cc you and link to this issue.

**Comment by alvaroaleman** [comment]
FTR, controller-runtime has something for this exact usecase: https://godoc.org/sigs.k8s.io/controller-runtime/pkg/cache#MultiNamespacedCacheBuilder

**Comment by sbueringer** [comment]
I would like to implement this feature
/assign 

I guess it makes sense to write a KEP first. I have a few questions, just to make sure I'm not thinking in the completely wrong direction.

Some assumptions:
* We're talking about providing multi-namespace variants of SharedInformer and SharedIndexInformer:
  * not regular Informers which are just (Store/Indexer, Controller) pairs
* This feature should be implemented on the client-side for now:
  * leads to one watch per namespace, but avoids server-side changes for now
  * it's not easily possible to use just one `cache.ListWatcher` implementation for multiple namespaces (see resourceVersion  hack mentioned above)

The rough idea would be to implement `cache.MultiNamespaceSharedIndexInformer` and `MultiNamespaceSharedInformer` by leveraging one 
informer per namespace under the hood. These informers could be created manually via a `cache.NewMultiNamespaceSharedIndexInformer` func
similar to `cache.NewSharedIndexInformer`. 

`SharedIndexInformer` is currently only shared (and only for its factory) when it's created e.g. via:
```go
factory := informers.NewSharedInformerFactory(client, 10*time.Second, informers.WithNamespace("kube-system"))
factory.Core().V1().Pods().Informer()
```
If the `cache.SharedIndexInformer` is created via `cache.NewSharedIndexInformer`, it's not really shared.
So I assume the `MultiNamespaceSharedInformers` should also be available via a factory similar to the existing `informers.sharedInformerFactory`.

I have a few concerns when extending the existing `informers.sharedInformerFactory`:

* We could add a `WithNamespaces` `SharedInformerOption`:
  * the problem is to pass the namespaces through the `Core()` (uses `core.New`) and `V1()` (uses `v1.New`)
    * both exported `New` funcs take only one `namespace` as parameter
  * => I guess we would have to add `New` funcs which take multiple namespaces as param
* For example the `PodInfomer` has a `Informer()` func which returns a `cache.SharedIndexInformer`. 
  * I don't think a `MultiNamespaceSharedIndexInformer` could fullfill the `cache.SharedIndexInformer` as the following funcs don't really make sense in this case:
    * `GetStore` usually returns the *one* backing store of the informer (same for `GetController` and `GetIndexer`)
    * `LastSyncResourceVersion` returns the last sync resource version. I guess when we have multiple concurrent ListWatcher we cannot really caculate what the last one is 
  * => We could add `MultiNamespaceInformer()` instead of `Informer()`

WDYT?

cc @deads2k 

P.S. Not sure about the process, if this is better discussed directly in a KEP, just let me know

**Comment by MikeSpreitzer** [comment]
We also ran into this in https://github.com/MikeSpreitzer/kube-examples/tree/add-kos/staging/kos .
I support looking for an easy-to-use general solution.
@MikeSpreitzer

**Comment by sbueringer** [comment]
/unassign

Unfortunately, I won't have the time to implement this.

**Comment by SpecialYang** [comment]
How is this great feature going?

**Comment by lavalamp** [comment]
This feature lacks agreement that it should be implemented. So I would say it is not going well. Jordan gave a rough design above. Probably the most effective thing to do is to construct an out-of-tree implementation and demo it to the SIG.

**Comment by FillZpp** [comment]
It is already supported by [multiNamespaceCache  in controller-runtime](https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/cache/multi_namespace_cache.go#L46), which will actually create multiple informers (one informer for one namespace) and users have not to manage those informers manually.

But I don't think it is a good idea here to change one informer support for multiple namespaces.

**Comment by skonto** [comment]
> It is already supported by [multiNamespaceCache in controller-runtime](https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/cache/multi_namespace_cache.go#L46)

I was looking for some lighter support eg. push down filtering and managing one entity. How this is going to be supported (if at all) is under discussion anyone but not everyone uses controller-runtime.

**Comment by redbaron** [comment]
looks like it is not going to be fixed and community came up with workarounds. I'd let it rot

**Comment by Ryu-Z** [comment]
+1
