### ISSUE TITLE
Improve test coverage for raw block feature

### ISSUE THREAD

**Issue by msau42** [kubernetes/kubernetes#74545]
**What would you like to be added**:
- [ ] Reconstruction of block devices
- [ ] Multiple pods requesting same block volume
- [ ] Single pod requests both filesystem and raw block volumes for the same volume
- [ ] Multiple pods: one requests filesystem and one requests raw block for the same volume

**Why is this needed**:
We're starting to find more issues, such as:
https://github.com/kubernetes/kubernetes/issues/74313

**Comment by msau42** [comment]
@kubernetes/sig-storage-feature-requests 
cc @bswartz @wongma7 @mkimuram

**Comment by wongma7** [comment]
For "Multiple pods requesting same block volume" and "Multiple pods: one requests filesystem and one requests raw block for the same volume", do we want to try in these tests deleting one pod to make sure that it does not cause problems for the other? That would basically be a test against the kubelet actualstateofworld, because kubelet should not call UnmountDevice at all as there is still >0 pods using it

For the iscsi bug https://github.com/kubernetes/kubernetes/issues/74313, there need to be additional iscsi-specific tests for when portal+iqn is the same but the lun is different. In this case, we expect UnmountDevice to be called but the iscsi plugin must be smart enough not to log out of the target. Working on the fix+these tests (""Multiple pods requesting same-ish iscsi block volume" and "Multiple pods: one requests filesystem and one requests raw block for the same-ish iscsi volume") in https://github.com/kubernetes/kubernetes/pull/74627

**Comment by jsafrane** [comment]
>  Single pod requests both filesystem and raw block volumes for the same volume
>  Multiple pods: one requests filesystem and one requests raw block for the same volume

kubelet will reject to mount / prepare one of those volumes, because pv.volumeMode does not match expected usage.

I don't think we have a test for mismatched volumeMode and its usage in a pod, it would be great to have one, but I don't think it needs to run with multiple pods.

**Comment by jsafrane** [comment]
>  Reconstruction of block devices
https://github.com/kubernetes/kubernetes/pull/75071 (not merged)

>  Multiple pods requesting same block volume
https://github.com/kubernetes/kubernetes/pull/74693 (merged)

**Comment by wongma7** [comment]
@jsafrane there is a corner case where kubelet will mount such a volume but only if its feature gate is off: https://github.com/kubernetes/kubernetes/issues/76044

**Comment by jsafrane** [comment]
> Single pod requests both filesystem and raw block volumes for the same volume

sort of covered here: https://github.com/kubernetes/kubernetes/pull/79796
(not sure if it makes sense to have a single pod requesting the same volume in both modes)

**Comment by jsafrane** [comment]
Block reconstruction test enhanced to check also global directory: https://github.com/kubernetes/kubernetes/pull/83451

**Comment by jsafrane** [comment]
@msau42, from the description:

*  Reconstruction of block devices - done (#83451)
*  Multiple pods requesting same block volume - done (#74693)

*  Single pod requests both filesystem and raw block volumes for the same volume - kubelet will reject to mount / prepare one of those volumes, because pv.volumeMode does not match expected usage. We do have unit tests for this.
*  Multiple pods: one requests filesystem and one requests raw block for the same volume - dtto

Is there any remaining work or can we close this?

**Comment by jsafrane** [comment]
> *  Single pod requests both filesystem and raw block volumes for the same volume - kubelet will reject to mount / prepare one of those volumes, because pv.volumeMode does not match expected usage. We do have unit tests for this.

We do have e2e test: #79796

**Comment by msau42** [comment]
Sounds good to me thanks!
/close
