### ISSUE TITLE
Local PV filesystem mode with block source does not support reconstruction

### ISSUE THREAD

**Issue by msau42** [kubernetes/kubernetes#74552]
**What happened**:
Followup on https://github.com/kubernetes/kubernetes/pull/74493#discussion_r260028479: Without a valid ConstructVolumeSpec(), UnmountDevice() is not called during reconstruction, so the global block mount will leak.

Also need to check if raw block local PV supports reconstruction.  There are no reconstruction e2es for raw block (https://github.com/kubernetes/kubernetes/issues/74545), so maybe this needs to be verified manually for now unless we can quickly adapt the existing tests.

**What you expected to happen**:
We may have to store metadata in a local file to support reconstruction, similar to what [csi does](https://sourcegraph.com/github.com/kubernetes/kubernetes/-/blob/pkg/volume/csi/csi_plugin.go#L362)

**Comment by msau42** [comment]
@kubernetes/sig-storage-bugs 
cc @cofyc @gnufied

**Comment by cofyc** [comment]
> 
We may have to store metadata in a local file to support reconstruction, similar to what [csi does](https://sourcegraph.com/github.com/kubernetes/kubernetes/-/blob/pkg/volume/csi/csi_plugin.go#L362)

Yes, to store metadata in a local file is a genernal solution because I found it's not possible to obtain correct volume source path because of symlinks. 

But it requires to migrate to new directory layout and for local PVs we don't need to detach or unmap devices like other volumes (e.g. gce pd, rbd). All we need to clean is to volume mount and global block mount if present. So I guess we can use a simpler solution for local PV.

/assign

**Comment by msau42** [comment]
cc @jsafrane

**Comment by jsafrane** [comment]
When fixing this, please enable also its e2e test (i.e. revert https://github.com/kubernetes/kubernetes/pull/83946)

**Comment by cofyc** [comment]
I'll look at this soon.
