### ISSUE TITLE
Invalid path to check in volume existence test for CSI volumes

### ISSUE THREAD

**Issue by cofyc** [kubernetes/kubernetes#74650]
In [`Kubelet.getMountedVolumePathListFromDisk`](https://github.com/kubernetes/kubernetes/blob/076af3d1b5cc1c368dd00f64ceefda8a87c1dfc7/pkg/kubelet/kubelet_getters.go#L307) and [`operationExecutor.CheckVolumeExistenceOperation`](https://github.com/kubernetes/kubernetes/blob/076af3d1b5cc1c368dd00f64ceefda8a87c1dfc7/pkg/volume/util/operationexecutor/operation_executor.go#L900), we check mount on first level directory in pod volume directories. 

It is true for many volume plugins, but not for CSI plugin which [mounts on sub-directory `mount`](https://github.com/kubernetes/kubernetes/blob/076af3d1b5cc1c368dd00f64ceefda8a87c1dfc7/pkg/volume/csi/csi_mounter.go#L75).

cc @msau42

**Comment by cofyc** [comment]
@kubernetes/sig-storage-bugs

**Comment by jkryl** [comment]
Pardon my ignorance of kubelet source code, but this looks very much similar to an issue we have been running to many times recently, when developing a CSI plugin. The problem is that when CSI volume publish is called and the mount point is not propagated from the CSI plugin pod (either missing bidirectional flag in yaml or not supported by underlaying k8s cluster implementation), the kubelet nevertheless starts a pod using the volume. The volume is not there, so the app writes to root filesystem in fact, leading to all other kinds of problems - i.e. losing data, filling up root fs.

IMHO what kubelet should do is to check that the mounted filesystem is indeed visible after publish call and if not it should fail the volume attach request. If this ticket was fixed, would it solve the issue we are seeing or should I open a new ticket? thanks

**Comment by msau42** [comment]
@jkryl I think we can potentially add that check but we need to make sure first it can work with ephemeral CSI drivers.  Ephemeral drivers would have to "stage" their directories somewhere, like /var/lib/kubelet/plugins/<csi driver>/, and then bind mount it to the publish path.

cc @vladimirvivien @kfox1111

**Comment by kfox1111** [comment]
Hmm... That is a good question. Does csi require a mount to be made or only that the specified directory be created? Will have to go read through the spec...

**Comment by kfox1111** [comment]
The only place in the spec I could find was this comment:
  // For volumes with an access type of mount, the SP SHALL place the
  // mounted directory at target_path.

So I think having Kubelet enforce that check would be ok with the spec, and a good thing to do.

**Comment by msau42** [comment]
@kubernetes/sig-storage-bugs 

cc @jsafrane @gnufied @jingxu97 

CSI spec says that the target path has to be a mount. Shall we go ahead and enforce it then? Are we going to break drivers that may not be doing this?

**Comment by jingxu97** [comment]
The issue mentioned here involves two functions [`Kubelet.getMountedVolumePathListFromDisk`](https://github.com/kubernetes/kubernetes/blob/076af3d1b5cc1c368dd00f64ceefda8a87c1dfc7/pkg/kubelet/kubelet_getters.go#L307) and [`operationExecutor.CheckVolumeExistenceOperation`](https://github.com/kubernetes/kubernetes/blob/076af3d1b5cc1c368dd00f64ceefda8a87c1dfc7/pkg/volume/util/operationexecutor/operation_executor.go#L900). 

Now with PR #74653, the issue in CheckVolumeExistenceOperation is solved by checking mount path instead of volume path. The only issue here is for getMountedVolumePathListFromDisk which is used during pod deletion.

This function was introduced by PR #61071. Now I am questioning whether we need to check the mount point or just need to check pod dirs exist before deleting the pod. Firstly, for some plugins, there might not be mount point. Secondly, without checking mount point, it means that pod cannot be deleted as long as there are pod volume dirs. In normal case, volume dirs should be cleanedup during volume teardown. For cases that kubelet restarts, we have reconciler try to clean up volume mounts if possible. 
So we can propose a couple of solutions here 
1. Remove mount point check. It solves the problem, the downside is that there might be some rare case that reconciler could not clean up dirs after kubelet restarts.
2. Still check mount point, and also check the next level "/mount" dir. This might still cause problem for some plugins that do not have mounts.
cc @msau42

**Comment by jingxu97** [comment]
Discussed offline with @msau42, 
For proposal 1., pod will not be deleted from api server if there are still volume dirs exist. So to make sure it works well, we need to have reliable way to clean up dirs. Normally when kubelet restarts, reconciler will either add it into actual state (if reconstruction works) or try to clean it up directly once unless volume is still in desired state. So if reconstruction does not work, and it fails to clean up during reconciler sync, there is no other chance to clean up the dirs. Or if volume was in desired state and removed quickly afterwords, the dir might not get the chance to be cleaned up at all. We are thinking to improve this part, we could use mark volume "uncertain" in actual state feature. During reconstruction, we can remove the check for mounted points (since the mount might be gone during node reboots or driver does not have moutns at all). Reconciler could mark those volumes as uncertain (even if it was in desired state) to make sure those volume got cleaned up or remount whenever needed with retries.
With this change, I think it is safe to remove the mount point check for pod deletion too.
