### ISSUE TITLE
Daemonset fluentd-es-v2.4.0 is not available!

### ISSUE THREAD

**Issue by liukaii** [kubernetes/kubernetes#74886]
I put these files in addone
```
mash@mash:~/lk/ELK/cloudmanELK/addone$ ls
es-service.yaml  es-statefulset.yaml  fluentd-es-configmap.yaml  fluentd-es-ds.yaml  kibana-deploymant.yaml  kibana-service.yaml
```
 when I run "kubectl apply -f addone/",  It seems good.
```
mash@mash:~/lk/ELK/cloudmanELK$ kubectl apply -f addone/
service/elasticsearch-logging created
serviceaccount/elasticsearch-logging created
clusterrole.rbac.authorization.k8s.io/elasticsearch-logging created
clusterrolebinding.rbac.authorization.k8s.io/elasticsearch-logging created
statefulset.apps/elasticsearch-logging created
configmap/fluentd-es-config-v0.2.0 created
serviceaccount/fluentd-es created
clusterrole.rbac.authorization.k8s.io/fluentd-es created
clusterrolebinding.rbac.authorization.k8s.io/fluentd-es created
daemonset.apps/fluentd-es-v2.4.0 created
deployment.apps/kibana-logging created
service/kibana-logging created
```
But when I want to check if the pods work well, 
```
mash@mash:~/lk/ELK/cloudmanELK/addone$ kubectl get --namespace=kube-system daemonset fluentd-es-v2.4.0
NAME                DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR                              AGE
fluentd-es-v2.4.0   0         0         0       0            0           beta.kubernetes.io/fluentd-ds-ready=true   19m
```
the daemonset fluentd-es-v2.4.0 is not available! 
```
mash@mash:~/lk/ELK/cloudmanELK/addone$ kubectl get --namespace=kube-system pod -l k8s-app=fluentd-es
No resources found.
```

I don't know why

**Comment by andreykaipov** [comment]
I also came across this when I manually tried to apply the manifests. To save the next person some time - I got this to work by removing the `addonmanager.kubernetes.io/mode: Reconcile` and `kubernetes.io/cluster-service: "true"` labels from each resource.

I'm guessing the addons in this repo are meant to be used when bootstrapping your own cluster and not using a managed service like GKE. The addon-manager must be one of the things running in the managed control plane hidden from the user, since something is definitely listening for that label and reconciling the resources (see https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/addon-manager).
