### ISSUE TITLE
Add e2e test to check for volume device mount cleanup

### ISSUE THREAD

**Issue by msau42** [kubernetes/kubernetes#74923]
**What happened**:
Currently the reconstruction tests only check that the pod volume mount is cleaned up. This misses issues if the plugin incorrectly implements reconstruction that cause only UnmountVolume to be called. 

ref: https://github.com/kubernetes/kubernetes/issues/74552

cc @cofyc

**Comment by msau42** [comment]
@kubernetes/sig-storage-bugs

**Comment by cofyc** [comment]
it's hard to test because this is no reliable and consistent way to check global mount path in e2e, for example:

- local: `/var/lib/kubelet/plugins/kubernetes.io/local-volume/mounts/spec.Name()`
- rbd: `/var/lib/kubelet/plugins/kubernetes.io/rbd/mounts/<pool>-image-<image>`

the only way to check the global mount path is to registering all volume plugins and call `GetDeviceMountPath`, but it requires access to the kubelet VolumeHost.

the workaround solution is to check mount refs which exist in `/var/lib/kubelet/plugins` and have the same source as pod volume mount.

**Comment by msau42** [comment]
Actually @jsafrane added an e2e test in https://github.com/kubernetes/kubernetes/pull/83451, but we had to disable it for local volumes since it doesn't support it yet.

**Comment by cofyc** [comment]
it's different, the disabled test is for check block volume map path and fixed in https://github.com/kubernetes/kubernetes/pull/84173.

for filesystem volume with block source, pod volume and subpath mounts are checked in subpaths suite but the global mount path in plugin directory is not checked.

**Comment by jsafrane** [comment]
This is quite ugly, but as the last resort we can list `/var/lib/kubelet/plugins/<plugin name>` before the test starts + after the tests and compare them. Disruptive tests are [Serial], so no other pod can create a new subdir there in the meantime.

**Comment by cofyc** [comment]
> This is quite ugly, but as the last resort we can list /var/lib/kubelet/plugins/<plugin name> before the test starts + after the tests and compare them. Disruptive tests are [Serial], so no other pod can create a new subdir there in the meantime.

I've tried the second option [here](https://github.com/kubernetes/kubernetes/pull/84218/files#diff-0d21a89b3adc375caf1b557b014e1111R240). You suggestion is simpler and doesn't need to parse mount information.

**Comment by cofyc** [comment]
instead of checking directories, we can check all mount points instead because some parent directories will be created on first use and not cleaned later.

I think we can simply cache all global mount points under `/var/lib/kubelet/plugins` before the test and verify after the test that we do not leak global mount points. Then we don't need to assume how plugin generates its sub-directory under `/var/lib/kubelet/plugins`.

**Comment by jsafrane** [comment]
>I think we can simply cache all global mount points under /var/lib/kubelet/plugins before the test and verify after the test that we do not leak global mount points. Then we don't need to assume how plugin generates its sub-directory under /var/lib/kubelet/plugins.

+1
