### ISSUE TITLE
Statefulset should be able to evicted if the worker node goes down

### ISSUE THREAD

**Issue by gyliu513** [kubernetes/kubernetes#74947]
**What would you like to be added**:
If the worker nodes goes down for a while after a specified timeout window or a specified retry number, all of the pods on this node should be evicted including statefulset pods so that pods for statefulset can be rescheduled.

**Why is this needed**:
This issue has been raised many times in community like https://github.com/kubernetes/kubernetes/issues/55934 and https://github.com/kubernetes/kubernetes/issues/54368 , the current workaround solution is for such case, we may need to an `alert system` to trigger the deletion of pods on failure nodes so as to trigger statefulset pods can be rescheduled. Like we can define some alerts and rules in `alert manger` to see if there are nodes goes down, then try to delete all of the pods for statefulset, and then those pods for statefulset will be rescheduled.

But the problem for now is many customers or end users may have such thinking:  "Oh, so I thought K8s was this easy, hands-off scheduling/keeping things alive, but you're saying that anything with StatefulSet might not be.... I was always told not to worry when things die, K8s will just restart it, but you're saying my entire world view of k8s is wrong?"

I feel like this chisels away at folks embracing K8s long term when they realize that classic middleware/stuff with state  is not the easy-peasy stateless microservices and therefore I would really like to see a back door of some sort introduced to StatefulSet that would allow us to force reschedule. I mean, even if SS sticks to "hey, I'm not going to tell you if your node is really down", and we figure out some other automated way to detect that and that it's not coming back up, then like after the Nth unsuccessful retry to bring the node back up, then automatically force the reschedule of any SS still on the down node.

/area stateful-apps
/sig apps

**Comment by gyliu513** [comment]
/cc @@smarterclayton @gmarek 

Can you please show some of your comments here?

**Comment by kow3ns** [comment]
1. StatefulSet does not do Node failure detection. 
1. > If the worker nodes goes down for a while after a specified timeout window or a specified retry number, all of the pods on this node should be evicted including statefulset pods so that pods for statefulset can be rescheduled.
This describes what happens if node permanently fails today. See [Node Controller](https://kubernetes.io/docs/concepts/architecture/nodes/#node-controller)
1. Given 1. and 2. can you describe what you are looking for a bit more concretely?

**Comment by gyliu513** [comment]
Hi @kow3ns , what I was looking for is that I want to statefulset pods can be evicted automatically like other stateless pods, so that the statefulset pods can be recovered on other nodes automatically. Comments?

**Comment by msau42** [comment]
Related discussion: https://github.com/kubernetes/enhancements/pull/719

**Comment by smarterclayton** [comment]
If you detect a machine fails, and isn't coming back, you delete the node API object.  The linked issue describes a way of simplifying how a higher level component could use this.  No proposal at this point exists to add "non-cloud provider node failure detection" but I would be open to sponsoring that since it is commonly requested.

However, the use of such a system has to be done within the following guarantees:

1. the admin can guarantee the node isn't coming back (requires host / power / network control, aka fencing)
2. the workload opts in to this (requires the workload use the "tolerate down nodes X")
3. the component that does this eviction is a component on top of Kube, not part of it (like cloud controller)

**Comment by gyliu513** [comment]
Thanks @msau42 and @smarterclayton , this really helps and glad to see a enhancement was under discussion. Will go through kubernetes/enhancements#719 and check the detail soon.

**Comment by anguslees** [comment]
Intuitively, this is more about the PV than the node, since pods are always temporary and persistent state is stored externally.  So provided the PV is still available (ie: mount succeeds), why should we care about the original node?

I assume the concern is that the original node might not actually be dead (might be isolated-but-up or down-but-coming-back-sometime), and so we could possibly end up with two instances of the same statefulset member.
1. If we assume a "well behaved" node, then the kubelet will kill its pods after the declared timeout talking to apiserver.  This is risky, since by definition a failing node is a misbehaving node.
1. I always assumed (I think from the original design doc discussions) that statefulsets assumed that the PV would do fencing (effectively locking), since it's the only mechanism statefulset _has_ to prevent duplicates beyond trusting the state machine.

So: I propose we opt-in (or opt-out) at the PV level.  If the statefulset PV does fencing (most rwo implementations do), then we should be able to forcibly reschedule pods (after a timeout), and the PV implementation will ensure the old+new don't have access concurrently.

**Comment by msau42** [comment]
I wouldn't draw the line at PV.  Your pods could be using object storage, and may not be able to handle concurrent writers.

**Comment by anguslees** [comment]
> I wouldn't draw the line at PV.

Sigh, yes you're correct - we can have StatefulSets where the state is somewhere unknown to k8s :(

In this case we have no choice but to trust the state machine - which requires a human to indicate that the original node is appropriately fenced (ie: pods have been killed and any relevant attached PVs have been unmounted/detached.), and we can reschedule just like a "clean" pod eviction.

Note that strictly the Node doesn't have to be deleted/recreated - provided we can assert that something like a reboot (ie: pods killed and volumes detached) has happened.  I know a previous storage/cloud-provider discussion floundered on trying to describe the possible "down" variations however.

The point I'm trying (poorly) to steer towards is dropping (2) from clayton's list [above](https://github.com/kubernetes/kubernetes/issues/74947#issuecomment-473325337).  I don't think the workload needs to opt-in to this since it should look like a combination of unclean reboot with a clean reschedule - both of which every workload needs to already handle.

**Comment by smarterclayton** [comment]
Changing the behavior of kube as it relates to 2 is a "semantic change" to the API of pods (a pod persists until the node is down).  You can't do that across the board for all apps without a) making it opt-in for cluster admins or b) making it opt-in for apps.  Otherwise existing apps that don't specify this value would see different behavior across clusters.

This has nothing to do with PV or StatefulSets - it's about Pods.  A pod provides a bedrock guarantee of the "pod exclusion principle" - if a pod A is listed on node A via the API, it is *not* running on any other node in the cluster.

**Comment by vasicvuk** [comment]
In on-premise deployments without cloud provider --pod-eviction-timeout should be used to automatically  delete node and reschedule pods from that Node.

There is no sense in waiting for lost node to became available forever.

**Comment by kolonelkrazy** [comment]
Around the time of original issue filing (circa march 2019) Kubernetes was at [v1.14.0](https://github.com/kubernetes/kubernetes/releases/tag/v1.14.0).At this point in time when a node hard failed it would likely be marked with `node.kubernetes.io/unreachable:NoExecute`

Since Kubernetes 1.28 there have been several options to taint nodes with additional attributes that are more communicative of the ongoing situation. The swiss-army-knife option is to taint a node with `node.kubernetes.io/out-of-service=nodeshutdown:NoExecute` which will allow stateful sets with finalizers to reclaim PVCs properly; which is one of the pain points of a ungraceful shutdown of a node.

`kubectl taint nodes <NODE NAME> node.kubernetes.io/out-of-service=nodeshutdown:NoExecute`

As of [Kubernetes v1.34.1](https://github.com/kubernetes/kubernetes/releases/tag/v1.34.1), the default behavior of a non-graceful (hard down) node failure, kube will apply a taint of `node.kubernetes.io/unreachable:NoExecute` and the above taint needs to be applied manually. 

https://kubernetes.io/docs/concepts/cluster-administration/node-shutdown/#non-graceful-node-shutdown

If you're running bare-metal or custom kubernetes platforms I was recommend node problem detector

https://github.com/kubernetes/node-problem-detector
