### ISSUE TITLE
"kubectl help xxx" / "kubectl xxx -h" should print usage at the bottom, not the top

### ISSUE THREAD

**Issue by davidopp** [kubernetes/kubernetes#7496]
Putting the usage info at the top makes it likely that this info (which is the thing the user actually wants) will scroll off the screen. We should move it to the bottom, after the flags and additional help topics (I'm not sure we should be showing additional help topics, but that's another story).

**Comment by bgrant0607** [comment]
cc @kubernetes/kubectl @kubernetes/docs

**Comment by asalkeld** [comment]
If no one is working on this, I could take it on. To clarify, do we just want to switch the flags and commands? Or turn this into something more like "git help" (which is quite nice I think).

There are so many issues open with overlapping scope and ideas all over the place that it is hard to see what is needed here.

**Comment by janetkuo** [comment]
@asalkeld are you working on this? @dims has a PR for this #25640

**Comment by asalkeld** [comment]
@janetkuo I posted the comment above as @dims put up his PR (I didn't start work on it yet). This was the reason I got frustrated and sent the email to k8s-dev about not being able to assign ourselves to issues...

**Comment by dims** [comment]
@asalkeld My apologies!

**Comment by smarterclayton** [comment]
So one note on this (after I noticed it) is that if we add less paging support (as many command lines do) on long help pages, this change would have the opposite effect (it would be in the wrong spot).

**Comment by dims** [comment]
@janetkuo we can close this issue as the PR is merged. @smarterclayton ack on that observation.

**Comment by duglin** [comment]
I know this one is on the verge of being closed because the PR  is merged already but I'd like to ask that we revisit this.  Looking at this issue's first sentence:
> Putting the usage info at the top makes it likely that this info (which is the thing the user actually wants) will scroll off the screen.

I disagree that what the user wants is the usage statement - we don't know what they want. True some may care about the usage but some may want to remember the exact wording of a certain `--` flag.  But that's actually secondary to my bigger concern.  Moving this to the bottom makes `kubectl` different than normal Linux command's output.  Obviously, I can't try **all** commands, but I was not able to find one in my testing that acted this way.  They all seemed to show their help in a man-ish way.  For better or worse that's the pattern I'm seeing on Linux commands.  I don't think `kubectl` should deviate from a well established pattern like that.  It just leads to confusion and annoyances for our users.  

Now, having said that, we could take an approach similar to what Docker has done. Try these two commands: `docker run` and `docker run --help`.  You'll see that `docker run` (w/o any flags/args) will shows **just** the usage. While the 2nd one  will show the full help text.  I think that's a nice compromise position w/o introducing a help-text pattern this will be foreign to our users.

**Comment by kargakis** [comment]
@kubernetes/sig-cli-misc

**Comment by shiywang** [comment]
will take a look

**Comment by shiywang** [comment]
will take a look on how `docker command`  implement this
