### ISSUE TITLE
[Umbrella issue for tracking] ci-kubernetes-e2e-gce-master-new-downgrade-cluster is flaky

### ISSUE THREAD

**Issue by mariantalla** [kubernetes/kubernetes#75047]
**Which jobs are flaking**:
* [`gce-master-new-downgrade-cluster`](https://testgrid.k8s.io/sig-release-master-upgrade#gce-master-new-downgrade-cluster) (a.k.a. `ci-kubernetes-e2e-gce-master-new-downgrade-cluster`)

**Which test(s) are failing**:
A variety of tests, owned primarily by sig-storage and sig-network (see more detailed issues per SIG below).
* `subpath unmount when kubelet is down` tests (SIG-storage)
* `session affinity` tests (SIG-network)

The job is release blocking; it's currently flaking just under 80% of the time, which makes it impossible to get CI signal from them in an automated way.

**More detailed issue breakdown**
* https://github.com/kubernetes/kubernetes/issues/75045
* https://github.com/kubernetes/kubernetes/issues/71423

**Related**
* https://github.com/kubernetes/kubernetes/issues/71383

/area deflake
/sig release
/kind flake
/priority critical-urgent

**Comment by mariantalla** [comment]
cc @smourapina @alejandrox1 @kacole2 @mortent @spiffxp

**Comment by alejandrox1** [comment]
`[sig-storage] CSI Volumes [Driver: csi-hostpath-v0] [Testpattern: Dynamic PV (default fs)] subPath should unmount if pod is gracefully deleted while kubelet is down [Disruptive][Slow]` has been flaking since the beginning of time.
original issue: https://github.com/kubernetes/kubernetes/issues/71473
and showed up in 1.13 https://github.com/kubernetes/kubernetes/issues/71434
