### ISSUE TITLE
Nvidia-device-plugin for Kubernetes version v1.13.4 

### ISSUE THREAD

**Issue by vinilvadakkepurakkal** [kubernetes/kubernetes#75089]
I would like to know, is there is any new Nvidia-device-plugin for Kubernetes version v1.13.4 ?. How can I use the Nvidia GPU resource in Kubernetes version v1.13.4?

Any guidance in this would be of great help

**Comment by mrbobbytables** [comment]
@vinilvadakkepurakkal - Please re-post your question to [Stack Overflow](http://stackoverflow.com/questions/tagged/kubernetes). 

The Kubernetes project does not manage the nvidia device plugin. It is managed by nvidia.

We are trying to consolidate the channels to which questions for help/support
are posted so that we can improve our efficiency in responding to your requests,
and to make it easier for you to find answers to frequently asked questions and
how to address common use cases.

We regularly see messages posted in multiple forums, with the full response
thread only in one place or, worse, spread across multiple forums. Also, the
large volume of support issues on github is making it difficult for us to use
issues to identify real bugs.

Members of the Kubernetes community use Stack Overflow to field support
requests. Before posting a new question, please search Stack Overflow for answers
to similar questions, and also familiarize yourself with:

  * [user documentation](https://kubernetes.io/docs/home/)
  * [troubleshooting guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/)

Again, thanks for using Kubernetes.

The Kubernetes Team

/assign
