### ISSUE TITLE
Windows GMSA tests are failing.

### ISSUE THREAD

**Issue by adelina-t** [kubernetes/kubernetes#75100]
Test added by: https://github.com/kubernetes/kubernetes/pull/74738 is failing on WIndows.

**Reason for failure**:

1. The way the test is set up it does not actually wait for the pod to be Running.

Here: https://github.com/kubernetes/kubernetes/blob/master/test/e2e/windows/gmsa.go#L71 
It should be using PodClient().CreateSync() in order to wait for the pod.

2. Running the command on the pods created by the tests ( when they finally start ) outputs the following: 

```
/usr/local/bin/kubectl --server=https://k8s-cbelu-2.eastus.cloudapp.azure.com --kubeconfig=/home/ubuntu/kube/config_2 exec --namespace=gmsa-test-windows-4891 with-correct-gmsa-annotations --container=container1 -- nltest /PARENTDOMAIN
Getting parent domain failed: Status = 1722 0x6ba RPC_S_SERVER_UNAVAILABLE
command terminated with exit code 1
```

@ddebroy Is there something that needs to be set up on the nodes in order for the test to run? Does it expect that the nodes are joined in a domain?

**Comment by wk8** [comment]
@adelina-t : sorry for the failing test, and thanks for being on top of this! :)

To address your points above:
1. I believe the current test does wait for the pod to be up & running (https://github.com/kubernetes/kubernetes/blob/dcbe588f76127cd7a3360e70f2260cd7c5ebbc73/test/e2e/windows/gmsa.go#L73-L87); now `CreateSync` does indeed seem to be a better alternative - less verbose, and better leveraging the existing framework, but it essentially ends up doing much the same thing? (https://github.com/kubernetes/kubernetes/blob/dcbe588f76127cd7a3360e70f2260cd7c5ebbc73/test/e2e/framework/util.go#L1503-L1517)
Happy to change it though, and please let me know if I'm missing something here.

2. That's the main issue here I believe :) It's because the `WindowsGMSA` feature flag is not enabled on the node running the test. I asked about how to go about this in the `Special notes for your reviewer` section of the original PR's message (https://github.com/kubernetes/kubernetes/pull/74738#issue-257177071):

> This e2e test has been verified to pass on a cluster with a Windows node with the
WindowsGMSA=true feature gate enabled (and the kubelet compiled from
#74737); however, I don't believe that feature gate is enabled when running a "regular" build. Would it be possible to:
> 1. enable that feature gate when running Windows e2e tests in a build?
> 2. or else enable dynamic Kubelet config for these tests, so that each spec can
set the config it needs?

Advice on this is greatly appreciated :)

3. This test does not require the nodes to be joined to an AD domain. That's the nice thing about the `nltest /PARENTDOMAIN` command, it simply reads the local config and never tries to talk to the AD controller that config points to. Please feel free to double-check this by running e.g.
```powershell
docker run --rm --security-opt "credentialspec=file://win.json" mcr.microsoft.com/powershell nltest /parentdomain
```
on any Windows box, provided that `C:\ProgramData\docker\credentialspecs\win.json` contains any well-formed cred spec, eg
```json
{
   "ActiveDirectoryConfig":{
      "GroupManagedServiceAccounts":[
         {
            "Name":"WebApplication",
            "Scope":"NOTAVALID"
         },
         {
            "Name":"WebApplication",
            "Scope":"notavalid.domain"
         }
      ]
   },
   "CmsPlugins":[
      "ActiveDirectory"
   ],
   "DomainJoinConfig":{
      "DnsName":"notavalid.domain",
      "DnsTreeName":"notavalid.domain",
      "Guid":"244818ae-87ca-4fcd-92ec-e79e5252348a",
      "MachineAccountName":"WebApplication",
      "NetBiosName":"NOTAVALID",
      "Sid":"S-1-5-21-2126729477-2524175714-3194792973"
   }
}
```

**Comment by adelina-t** [comment]
@wk8 

1. Answered inline in the PR

2. The feature flag is tricky to enable in aks-engine jobs. Basically we need to make some changes in kubetest, I think, I need to check. It might take some time to have a PR approved + proper testing before adding it to the running jobs. 

     From my side, on the flannel CI I can make that change much faster.

3. That's good to hear, because setting a AD domain machine is a whole different animal :)

**Comment by wk8** [comment]
@adelina-t 
1. Er, thanks, good catch ;)
2. I'm looking into what it might take to start having windows e2e_node tests. That would be better suited for this particular test (it really only tests the kubelet's behaviour, and could do additional tests like checking that no GMSA registry keys are leaked); and there already is support for dynamic config there.
3. 🎉

**Comment by michmike** [comment]
@wk8 and @adelina-t i will go ahead and let the PR merge. please file a separate issue for the feature flag issue and add it to the 1.15 backlog (or send me the link)

**Comment by ddebroy** [comment]
https://github.com/kubernetes/kubernetes/issues/75147 to track skipping feature gated tests.
