### ISSUE TITLE
Unable to Promote e2e which are using optional Condition fields such as Reason or Message

### ISSUE THREAD

**Issue by mgdevstack** [kubernetes/kubernetes#75324]
**Issue**: Many e2e are using optional condition fields such as Reason or Message to verify whether pod is failed or reached to the expected state having known expected reason and message. 

These are valid scenarios but we can not promote such e2e to Conformance as these Reasons and Messages may change over a period of time. 

This is observed mostly if we are expecting Pods/Jobs to get failed due to certain expected reason and message but failure may have tons of other reasons.

References:
1) https://github.com/kubernetes/kubernetes/pull/74979#discussion_r263207428
2) https://github.com/kubernetes/kubernetes/pull/75018#pullrequestreview-213817494
3) https://github.com/kubernetes/kubernetes/blob/60d0ec579b376b357ca6029f8cc1cd6e70a54601/test/e2e/apps/cronjob.go#L183
4) https://github.com/kubernetes/kubernetes/blob/master/test/e2e/apps/cronjob.go#L222
5) https://github.com/kubernetes/kubernetes/blob/60d0ec579b376b357ca6029f8cc1cd6e70a54601/test/e2e/autoscaling/cluster_size_autoscaling.go#L181
6) https://github.com/kubernetes/kubernetes/blob/60d0ec579b376b357ca6029f8cc1cd6e70a54601/test/e2e/common/init_container.go#L298 [Conformance e2e]
7) https://github.com/kubernetes/kubernetes/blob/60d0ec579b376b357ca6029f8cc1cd6e70a54601/test/e2e/common/init_container.go#L408 [Conformance e2e]
........

**So how such situations can be taken care while writing e2e?**
_- verifying status and message against non-empty field would resolve this issue but there would not be preciseness of e2e behavior._ 

@kubernetes/sig-architecture-misc-use-only-as-a-last-resort
@kubernetes/cncf-conformance-wg

**Comment by mgdevstack** [comment]
What if we emphasize on using core libraries const for such reasons and messages, would it be fine?
e.g.
https://github.com/kubernetes/kubernetes/blob/60d0ec579b376b357ca6029f8cc1cd6e70a54601/test/e2e/common/init_container.go#L408

https://github.com/kubernetes/kubernetes/blob/350dfccfe98c71a46eb881c0837b8f348b3f3ab4/test/e2e/common/runtime.go#L292-L296

**Comment by bgrant0607** [comment]
@mgdevstack No

**Comment by bgrant0607** [comment]
Guidance on enum-like fields:
https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api_changes.md#backward-compatibility-gotchas
https://github.com/kubernetes/kubernetes/issues/7856

Status fields:
https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#typical-status-properties

Old event guidance:
https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#events

Event guide:
https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/event-style-guide.md

Events and contents of condition reasons and messages are not covered by API compatibility guarantees. They are passed through for human consumption, not machine consumption. Operational behaviors may be tuned by parameters, added, or removed and not be considered breaking changes. For instance, when CrashLoopBackoff and ImagePullBackoff were introduced, they were new reasons not previously reported. Clients erroneously dependent on the previously reported reasons would no longer work. 

Similarly, when we change events to conform to the new style guide, their message text will change. Events may be aggressively garbage collected or even completely disabled in order to reduce apiserver load, and watching events is discouraged.

We run old e2e tests against newer releases of Kubernetes. When those tests have been dependent on specific reasons, messages, and events, they have broken in the past. When contributors are encouraged to patch old e2e tests in order to pass version-skew testing, that should be a red flag that we are breaking backward compatibility. We really need a policy that does not require significant technical analysis on a test-by-test basis.

Tests that are dependent on such text may also indicate API deficiencies, or the tests may simply be testing what the code currently does rather than the API contract, and should be unit tests instead.

I'll comment with case by case analysis in a bit.

**Comment by bgrant0607** [comment]
1. Test is overly specific and shouldn't be checking the message.

2. Test is overly specific and shouldn't be checking the reason.

3. Test shouldn't be checking for events, or lack thereof.

4. Ditto.

5. Shouldn't be checking an event, and cluster autoscaling shouldn't be covered by conformance, anyway.

6. Shouldn't be checking condition reason or message, or number of conditions. This is testing the implementation, not the required behavior.

7. Ditto.

As written, none of those tests are acceptable e2e tests, much less conformance tests.

**Comment by timothysc** [comment]
I'm going to PR the main doc with a distillation of this and close this issue.

**Comment by bgrant0607** [comment]
Note that this seems to be partly due to an organically evolved pattern to leave broken pods on nodes in order to work around bad controller behavior:
https://github.com/kubernetes/kubernetes/issues/74405
https://github.com/kubernetes/kubernetes/issues/76370
https://github.com/kubernetes/kubernetes/issues/32837
https://github.com/kubernetes/kubernetes/issues/2529
