### ISSUE TITLE
[Flaking test] CSI Volumes [Driver: pd.csi.storage.gke.io][Serial] [Testpattern: Dynamic PV (default fs)] subPath should unmount if pod is gracefully deleted while kubelet is down

### ISSUE THREAD

**Issue by mariantalla** [kubernetes/kubernetes#75326]
**Which jobs are flaking**:
* ci-kubernetes-e2e-gce-new-master-upgrade-cluster
* ci-kubernetes-e2e-gce-master-new-downgrade-cluster
* ci-kubernetes-e2e-gce-new-master-upgrade-master

**Which test(s) are flaking**:
`[sig-storage] CSI Volumes [Driver: pd.csi.storage.gke.io][Serial] [Testpattern: Dynamic PV (default fs)] subPath should unmount if pod is gracefully deleted while kubelet is down [Disruptive][Slow]`

**Testgrid link**:
* https://testgrid.k8s.io/sig-release-master-upgrade#gce-new-master-upgrade-cluster
* https://testgrid.k8s.io/sig-release-master-upgrade#gce-master-new-downgrade-cluster
* https://testgrid.k8s.io/sig-release-master-upgrade#gce-new-master-upgrade-master

**Reason for failure**:
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/testsuites/subpath.go:305
Expected grep stdout to be empty (i.e. no mount found).
Expected
    <string>: /dev/sdb on /var/lib/kubelet/pods/e7cca97f-3b9e-11e9-9081-42010a8a0002/volumes/kubernetes.io~csi/pvc-e2c79d44-3b9e-11e9-9081-42010a8a0002/mount type ext4 (rw,relatime,data=ordered)
    /dev/sdb on /var/lib/kubelet/pods/e7cca97f-3b9e-11e9-9081-42010a8a0002/volumes/kubernetes.io~csi/pvc-e2c79d44-3b9e-11e9-9081-42010a8a0002/mount type ext4 (rw,relatime,data=ordered)
    /dev/sdb on /home/kubernetes/containerized_mounter/rootfs/var/lib/kubelet/pods/e7cca97f-3b9e-11e9-9081-42010a8a0002/volumes/kubernetes.io~csi/pvc-e2c79d44-3b9e-11e9-9081-42010a8a0002/mount type ext4 (rw,relatime,data=ordered)
    /dev/sdb on /home/kubernetes/containerized_mounter/rootfs/var/lib/kubelet/pods/e7cca97f-3b9e-11e9-9081-42010a8a0002/volumes/kubernetes.io~csi/pvc-e2c79d44-3b9e-11e9-9081-42010a8a0002/mount type ext4 (rw,relatime,data=ordered)
    
to be empty
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/utils/utils.go:255
```

**Anything else we need to know**:
* This fails about 15%-18% (up to 23%) of the time in sig-release dashboards
* Important to resolve due to significant flake rate, (https://github.com/kubernetes/kubernetes/issues/75045 and https://github.com/kubernetes/kubernetes/issues/75275 are higher priority)
* The same test for a different driver was recently stabilised: https://github.com/kubernetes/kubernetes/issues/75196
* [triage link](https://storage.googleapis.com/k8s-gubernator/triage/index.html?job=ci-kubernetes-e2e-gce.*master.*&test=pd.csi.storage.gke.io.*gracefully%20deleted%20while%20kubelet%20is%20down) (points to jobs on sig-release dashboards only)

/sig storage
/kind flake
/remove-kind failing-test
/priority important-soon

**Comment by mariantalla** [comment]
@msau42 Could you have a look please? (this is for graceful pod deletion, pd.csi.storage.gke.io driver)

Adding it to v1.14 unless we learn otherwise.

/milestone v1.14

**Comment by msau42** [comment]
gce-new-master-upgrade-master: this test job only upgrades the master, and not the nodes.  The fix is only in master/1.14, so we'll need to backport it to 1.13 to fix the flakiness here.

gce-new-master-upgrade-cluster: the failure is due to cluster-upgrade failing, which left the nodes at 1.13 which still has the issue.  Fixing the cluster upgrade should address this.  We can also backport the fix to 1.13.

gce-master-new-downgrade-cluster: this job downgrades the cluster to 1.13, which doesn't have the fix. We'll need to backport the fix to 1.13 to fix the flakiness.

**Comment by msau42** [comment]
@cofyc can you look at cherry picking the two fixes to 1.13?

**Comment by msau42** [comment]
I think I figured out the root cause for the CSI hostpath flakiness (not the pd driver flakiness though).  It is the same issue as https://github.com/kubernetes/kubernetes/issues/72346#issuecomment-466347067.  Pod deletion uses IsLikelyNotMountPoint to check if there are no more mounted pod directories, but it doesn't work for hostpath csi driver since it is just a directory in the container rootfs.

**Comment by cofyc** [comment]
hi, @msau42 
I guess, this flakiness and https://github.com/kubernetes/kubernetes/issues/75196 are because of this race condition (https://github.com/kubernetes/kubernetes/issues/75345). It has been fixed in https://github.com/kubernetes/kubernetes/pull/75458.

I've reproduced this issue, after kubelet restarts, kubelet does not try to unmount the volume. (example: https://transfer.sh/lPoY3/k8s-75326.log)

**Comment by alejandrox1** [comment]
Will continue to keep an eye on this one
/remove-milestone v1.14
/milestone v1.15

**Comment by alejandrox1** [comment]
[ci-kubernetes-e2e-gce-new-master-upgrade-cluster triage](https://storage.googleapis.com/k8s-gubernator/triage/index.html?job=ci-kubernetes-e2e-gce-new-master-upgrade-cluster&test=subPath%20should%20unmount%20if%20pod%20is%20gracefully%20deleted%20while%20kubelet%20is%20down)

**Comment by alejandrox1** [comment]
Tests have been reorganized. Will open a new issues if this test failure appears again.
/close
