### ISSUE TITLE
Service creation fails after cluster recreation

### ISSUE THREAD

**Issue by andrewchambers** [kubernetes/kubernetes#7538]
What happened:
Created a google compute cluster.
Created a working service and replication controller.
deleted cluster from gce console.
recreate cluster with same name as old one.
delete all kubernetes config on system.
setup kubernetes config again to point to new master.
Can no longer create a service.
```
andrew@andrew-laptop:buppysrv $ kubectl create -f ./kuberconfig/service-buppyapi.json 
Error: The resource 'projects/buppy-io-dev/regions/us-central1/targetPools/k8s-cluster-default-buppyapi' already exists
andrew@andrew-laptop:buppysrv $ kubectl stop -f ./kuberconfig/service-buppyapi.json
andrew@andrew-laptop:buppysrv $ kubectl delete -f ./kuberconfig/service-buppyapi.json 
andrew@andrew-laptop:buppysrv $ kubectl create -f ./kuberconfig/service-buppyapi.json 
Error: The resource 'projects/buppy-io-dev/regions/us-central1/targetPools/k8s-cluster-default-buppyapi' already exists
andrew@andrew-laptop:buppysrv $ 
```

The service config is as follows:
```
{
   "kind":"Service",
   "apiVersion":"v1beta3",
   "metadata":{
      "name":"buppyapi",
      "labels":{
         "name":"buppyapi"
      }
   },
   "spec":{
      "createExternalLoadBalancer": true,
      "ports": [
        {
          "port":80,
          "targetPort": 12345,
          "protocol":"TCP"
        }
      ],
      "selector":{
         "name":"buppyapi"
      }
   }
}
```

**Comment by roberthbailey** [comment]
Please direct your questions to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes). 

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases. 

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to similar questions, and also familiarize yourself with:
  * [the user guide](http://kubernetes.io/v1.0/)
  * [the troubleshooting guide](http://kubernetes.io/v1.0/docs/troubleshooting.html)

Again, thanks for using Kubernetes.

The Kubernetes Team
