### ISSUE TITLE
Can't remove ports with patch_namespaced_service

### ISSUE THREAD

**Issue by mkornacker** [kubernetes/kubernetes#75394]
**What happened**:

A call to (Python CoreV1Api) patch_namespaced_service() did not remove a specific port that was dropped from the V1ServiceSpec.

Using patch_namespaced_service() to *add* a port works fine.

**What you expected to happen**:

For the Service to be updated and the port removed.

**How to reproduce it (as minimally and precisely as possible)**:
svc = client.read_namespaced_service('service', 'ns')
svc.spec.ports.pop()
res = client.patch_namespaced_service('service', 'ns', svc)
res.spec.ports will still contain the port that was removed.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.6", GitCommit:"b1d75deca493a24a2f87eb1efde1a569e52fc8d9", GitTreeState:"clean", BuildDate:"2018-12-16T04:39:52Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.6", GitCommit:"b1d75deca493a24a2f87eb1efde1a569e52fc8d9", GitTreeState:"clean", BuildDate:"2018-12-16T04:30:10Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
AWS

- OS (e.g: `cat /etc/os-release`):
NAME="Ubuntu"
VERSION="16.04.4 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.4 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

- Kernel (e.g. `uname -a`):
Linux marcel-XPS-8930 4.15.0-46-generic #49~16.04.1-Ubuntu SMP Tue Feb 12 17:45:24 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:
- Others:

**Comment by danielqsj** [comment]
@mkornacker I recommend that you can file an issue in https://github.com/kubernetes-client/python.

**Comment by zq-david-wang** [comment]
It seems that when patch a service port, the behaviour is only "add" , I am not sure whether this is apiserver bug.  but the behaviour is inconsistent with other resources (I do know some other resources of type list which can be delete by just "replacing" its parent element., e.g. delete some ingress paths.) My guess is that the parent element for ports is spec, which can only be updated, but not "entirely" replaced.  (Sounds more like a apiserver issue......)

 You can delete a port using http patch extension, following is an example:
` res = client.patch_namespaced_service('service', 'ns', body=[ { "op": "remove", "path": "/spec/ports/<the index you want to remove, 0-based>" } ]) `
and you need to determine the index of the port you want to remove.

**Comment by mkornacker** [comment]
Great, thanks for pointing out that workaround.

Please let me know if this is *not* an apiserver bug but a Python SDK bug, in which case I will refile the issue over there.

**Comment by zq-david-wang** [comment]
Just check with k8s.io/api, the patch strategy for ports in service is merge:
`// ServiceSpec describes the attributes that a user creates on a service.
type ServiceSpec struct {
	// The list of ports that are exposed by this service.
	// More info: https://kubernetes.io/docs/concepts/services-networking/service/#virtual-ips-and-service-proxies
	// +patchMergeKey=port
	// +patchStrategy=merge
	Ports []ServicePort `json:"ports,omitempty" patchStrategy:"merge" patchMergeKey:"port" protobuf:"bytes,1,rep,name=ports"`
`
while there is no merge strategy for ingress path resource
`// HTTPIngressRuleValue is a list of http selectors pointing to backends.
// In the example: http://<host>/<path>?<searchpart> -> backend where
// where parts of the url correspond to RFC 3986, this resource will be used
// to match against everything after the last '/' and before the first '?'
// or '#'.
type HTTPIngressRuleValue struct {
	// A collection of paths that map requests to backends.
	Paths []HTTPIngressPath `json:"paths" protobuf:"bytes,1,rep,name=paths"`
	// TODO: Consider adding fields for ingress-type specific global
	// options usable by a loadbalancer, like http keep-alive.
}
`
I seems more like a behavior by design, not an issue.

**Comment by zq-david-wang** [comment]
Maybe the reason that some list resources  do not have specific  merge strategy is that they do not have a proper primary key for its element, hence cannot be merged, and the patch would always replace it... it makes sense to "merge" list with identifiable elements, and "replace" the while list otherwise. Just some guess.... 

And maybe this is not an issue, just by design

**Comment by roycaihw** [comment]
this is by design, but it's missing documentation/example in python client

patch_namespaced_service uses strategic merge patch by default. To remove a key from a list, you could do one of the following: 
1. use strategic merge patch
```
svc = client.read_namespaced_service('service', 'ns')
p = svc.spec.ports.pop()
svc.spec.ports.append({"$patch":"delete","port":p.port})
res = client.patch_namespaced_service('service', 'ns', svc)
```
2. use json patch as @zq-david-wang suggested https://github.com/kubernetes/kubernetes/issues/75394#issuecomment-473232331
3. use update
```
svc = client.read_namespaced_service('service', 'ns')
svc.spec.ports.pop()
res = client.replace_namespaced_service('service', 'ns', svc)
```

ref https://github.com/kubernetes-client/python/issues/641 for more info

**Comment by Darren-wh** [comment]
The kubectl apply -f  command also can't remove sevice port or containers port.
