### ISSUE TITLE
CNI version sprawl throughout codebase

### ISSUE THREAD

**Issue by philips** [kubernetes/kubernetes#75485]
**What would you like to be added**:

Today bumping the CNI version requires touching a bunch of disparate files. [See this PR](https://github.com/kubernetes/kubernetes/pull/75455)

**Why is this needed**:

- centralize this for everyone's sanity
- decrease mistakes in backports

/cc @kubernetes/sig-network-feature-requests

**Comment by dcbw** [comment]
Also this PR from kubernetes/release is required for the release images (?): https://github.com/kubernetes/release/pull/683

**Comment by neolit123** [comment]
@dcbw 
> Also this PR from kubernetes/release is required for the release images (?): kubernetes/release#683

the package tooling is planned to be moved in k/k, which falls under sig-release and cluster-lifecycle.

issue:
https://github.com/kubernetes/kubernetes/issues/71677
kep:
https://github.com/kubernetes/enhancements/pull/858

the rest from https://github.com/kubernetes/kubernetes/pull/75455 seems to fall under a different problem where we don't have a centralized, machine readable location for "third party" dependencies. this problem is owned by sig-release and there was a discussion for a KEP, but nothing concrete.

**Comment by squeed** [comment]
Thanks for looking in to this. We got away with this for so long, mostly because it took CNI two years to do a release.

**Comment by vegemitecheesetoast** [comment]
Hi! I'd like to take this. I've spoken with thockin and I think it would be a good way for me to start gaining confidence as a first contributor!

**Comment by squeed** [comment]
Hi there, @vegemitecheesetoast . Welcome to the (wonderful?) world of CNI and kubernetes.

There are two loosely coupled CNI artifacts consumed by Kubernetes:

- `libcni`, the go library (which is only used by dockershim's CNI and Kubenet drivers) that executes CNI plugins),
- the CNI plugin binaries, which are installed directly on disk and *may* be used, or may not be, depending on the user configuration

I know that @justaugustus has been desperately trying to fix the second problem in #78819 with no luck, mostly because it's a trivial change that somehow requires near-infinite work with the packaging and build infrastructure. I believe it can only be fixed by a Googler, so I haven't looked too closely at it. It would be awesome to pull in CNI plugin builds more frequently, as we tend to do quarterly releases with bugfixes (after a few years of utter silence, sorry...).

So, if you have spare cycles, sync with @justaugustus and see what sort of help he needs.

Bumping libcni does need to happen, but it's at a slower release pace and is pretty stable. When this PR was filed, the plugins and libcni were in the same repository, but we've since split them out. It will eventually go away as the dockershim moves out-of-tree. Someday I'd like to consolidate all of the various CRI runtimes' CNI drivers to a single sigs.k8s one, but haven't had the time.

**Comment by vegemitecheesetoast** [comment]
Hi @squeed! Thanks for the background here. Let me reach out to @justaugustus and see how I can help here. Given it's my first time, working with someone would be ideal to get my head around everything.
