### ISSUE TITLE
pods naming convention

### ISSUE THREAD

**Issue by reddysainathn** [kubernetes/kubernetes#75557]
The current naming convention is
|--- Deployment: < name >
│-----└─ Replica Set: < name >-< rs >
│--------└─ Pod: < name >-< rs>-< RandomString >

Instead of <RandomSting>, is there a way to have an incremented number value or some custom way of labeling?

something like : sample-app-5tydcggg-1

Reference : https://stackoverflow.com/questions/46204504/kubernetes-pod-naming-convention

Thanks.

**Comment by vllry** [comment]
Incrementing pod names would create a scalability issue. The tracking counter would need a lock to prevent concurrent changes. This introduces scalability issues by itself (pods must "wait their turn") to get an ID, and goes against how the database for Kubernetes works.

Kubernetes uses an "AP" database (etcd) according to the CAP theorem, which means by design it doesn't allow users to gain exclusive write access to a value. It seems awkward, but it allows the system to keep functioning and self-heal if some etcd instances temporarily get out of sync with one another.

Hope this makes sense!

/close

**Comment by reddysainathn** [comment]
Thank you @vllry
