### ISSUE TITLE
incorrect etcd client usage 

### ISSUE THREAD

**Issue by timothysc** [kubernetes/kubernetes#7566]
After several conversations with CoreOS, we've settled that the current usage of the client library is incorrect.  https://github.com/coreos/etcd/issues/2677

1.) The client is technically **not** thread safe, and round-robin rotation will never occur because we share the client (EtcdHelper).  The intended usage was a client per context, and would rotate operations across the quorum. 

2.) If we want keepalives we will need to option enable on the transport and pass to the etcd-client.   

#5589 , #6559 

I don't see an easy work-around for this 

@smarterclayton , @abhgupta, @wojtek-t, @filbranden, @eparis

**Comment by yichengq** [comment]
@timothysc Some part of the description is incorrect. Let me clarify it more:
1) go-etcd does round-robin rotation when failure occurs, even if it is shared. For example, if the member that go-etcd connects to is hard killed, go-etcd will fail on the first attempt with the killed member, and succeed on the second attempt with another member.
2) go-etcd insists on one single etcd member when the connected member works well, and this behavior is intentional. It saves socket resources, and improves efficiency.
3) the default transportation for go-etcd has 1s dial timeout, and 1s TCP keepAlive period. If you want to adjust it, you could call 
http://godoc.org/github.com/coreos/go-etcd/etcd#Client.SetTransport .

We are working on the documentation of caveat go-etcd to clarify these problems.

**Comment by smarterclayton** [comment]
Ok, so at a minimum we need to look at how EtcdHelper is used.  Ugh.  

----- Original Message -----

**Comment by smarterclayton** [comment]
Can we easily/safely copy the go-etcd client and expect it to work?  Or do we have to run through the NewClient part?  The ideal case here would be that anyone who gets passed an etcdhelper calls a .Copy() method to be unique.

**Comment by smarterclayton** [comment]
Correct me if I'm wrong, but it looks like if we create multiple go-etcd Clients, each one would have a unique idle connection pool, which means none of our code (if we were creating our own) would be reusing connections.  Is that accurate?

**Comment by timothysc** [comment]
@smarterclayton that doesn't jive with what we are seeing.  From what I grok, one client gets created in the helper, then the helper gets copied around.

**Comment by smarterclayton** [comment]
No, I mean if we switched to use different go-etcd clients because they aren't thread safe, looking at go-etcd code there would be no connection sharing, so the number of connections to etcd would go up by a significant factor.

**Comment by lavalamp** [comment]
> Correct me if I'm wrong, but it looks like if we create multiple go-etcd Clients, each one would have a unique idle connection pool, which means none of our code (if we were creating our own) would be reusing connections. Is that accurate?

We should be able to make them share transports, no?

**Comment by smarterclayton** [comment]
They look like they create and manage their own transports when TLS is in play, and we can't pass one in.

----- Original Message -----

**Comment by lavalamp** [comment]
I just read through coreos/etcd#2677, it's not clear to me what we need to do.

The README says ["go-etcd is not thread-safe, and it may have race when switching member or updating cluster."](https://github.com/coreos/go-etcd), so it sounds like we are supposed to not emit concurrent requests on a single client? @xiang90 or @yichengq, can you tell us what circumstances would trigger this race, so that we'll be able to write a test to tell when we've fixed it?

I guess we can use the sync.Pool thingy, it shouldn't be too bad to fix.

**Comment by lavalamp** [comment]
OK well, that's kind of a deal-breaker. We can't have O(hundreds) of open
connections for every client we make.

**Comment by smarterclayton** [comment]
I have to say... it would be more convenient if the client object was threadsafe so we could share it simply.  Is there a significant downside to the client *becoming* threadsafe?  I'd certainly be willing to help that.

**Comment by lavalamp** [comment]
Yeah, I agree that would be easier.

**Comment by lavalamp** [comment]
Filed https://github.com/coreos/go-etcd/issues/211

**Comment by timothysc** [comment]
@kelseyhightower perhaps the coreos folks who are working on k8s could lend a hand here.

**Comment by timothysc** [comment]
Now that 1.0 is out, we should really re-evaluate this, the issue will be maintaining the abstractions that have been created around "storage" vs. raw helper utils.  So the helper per context would get a bit weird, and may not apply to other storage back-ends. 

cc @wojtek-t

**Comment by countspongebob** [comment]
This one has come up in the scaling working group as something we need to fix. Target 1.1 perhaps?

cc @timstclair

**Comment by timothysc** [comment]
@countspongebob sadly your hitting my alter ego... my handle is timothysc

**Comment by wojtek-t** [comment]
@timothysc 
There is a plan to start using the new etcd client - see #11962 - IIUC we would like to do it relatively soon.
So we should first check whether the new client has the same problems (I didn't have chance to do that so far).

**Comment by timothysc** [comment]
FWIW, ^ I didn't do that unassignment, that it said I did...

**Comment by timothysc** [comment]
I'm going to close this issue in favor of https://github.com/kubernetes/kubernetes/issues/11962 as it appears close now.
