### ISSUE TITLE
E2E proposal: To verify preference for activeDeadlineSeconds over backOffLimit

### ISSUE THREAD

**Issue by globervinodhn** [kubernetes/kubernetes#75757]
**What would you like to be added**: A new E2E test for validating the preference among the two different parameters for deciding on pod failure status. activeDeadlineSeconds refers to the duration of the job, no matter how many pods are created and backOffLimit refers to the number of retries before the job is deemed to have failed. In a scenario wherein both the parameters are specified, activedeadlineSeconds takes precedence even if the backOffLimit isn't reached.

Link: https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/#job-termination-and-cleanup
Extract from the link: "Note that a Job’s .spec.activeDeadlineSeconds takes precedence over its .spec.backoffLimit. Therefore, a Job that is retrying one or more failed Pods will not deploy additional Pods once it reaches the time limit specified by activeDeadlineSeconds, even if the backoffLimit is not yet reached."

**Why is this needed**: This E2E is needed so as to verify the pod lifecycle behaviour in case of specifying both activeDeadlineSeconds and backOffLimit in the configuration.

--------------------------------------------------------------------------------------------------------------------------------
Sample configuration file:

apiVersion: batch/v1
kind: Job
metadata:
  name: pi
spec:
  template:
    spec:
      containers:
      - name: pi
        image: polinux/stress
        resources:
         requests:
           memory: "10Mi"
         limits:
           memory: "11Mi"
        command: ["stress"]
        args: ["--vm", "1", "--vm-bytes", "2100M", "--vm-hang", "1"]
      restartPolicy: OnFailure
  backoffLimit: 3
  activeDeadlineSeconds: 60

--------------------------------------------------------------------------------------------------------------------------------
In the above scenario, activeDeadlineSeconds duration is reached even before backOffLimit count and the pod is removed.

/sig apps

cc @brahmaroutu @mgdevstack

**Comment by mgdevstack** [comment]
Observed the following points -

1. **Can we use failing pods instead of bounding to use system resources**?
 -- One failing and another running busybox. Provide parallelism=2 && completion=2. Job that is retrying one or more failed Pods will not deploy additional Pods once it reaches activeDeadlineSeconds.
2. **Add intermediate steps to make sure Jobs is retrying to start failed pod till backoffLimit count (atleast 2-3 times)**. 
-- This is to verify restart attempts of pod till backoffLimit count as discussed in https://github.com/kubernetes/kubernetes/pull/75632#issuecomment-475900766. Existing e2e has parallelism=1 && backoffLimit=1, is not precisely verifying behavior and might fail when parallelism=2 && completion=2 (wrt. to above 2 Pods case).
