### ISSUE TITLE
Zero Downtime deployment not working - 503 Service Temporarily Unavailable

### ISSUE THREAD

**Issue by kanibs** [kubernetes/kubernetes#75813]
**What happened**:
I am trying to achieve zero-downtime deployment using Kubernetes. But every time I do the upgrade of the deployment using a new image, I am seeing 2-3 seconds of downtime. I have to do this for one of my projects but failed to achieve it. 
So I tried to test the same using a Hello-World sort of application, but still could not achieve it. I am deploying my application using the Helm charts.

Following the online blogs and resources, I am using Readiness-Probe and Rolling Update strategy in my Deployment.yaml file. But this gives me no success.  
I have created a `/health` end-point which simply returns `200` status code as a check for readiniess probe. 

The images of my config files are given at the end of this issue.

Please suggest me what am I doing wrong ?

**What you expected to happen**:
I expected that after using readiness probes and RollingUpdate strategy in Kubernetes I would be able to achieve zero-downtime of my service when I upgrade the image of the container. 

**How to reproduce it (as minimally and precisely as possible)**:
While doing the upgrade using the `helm upgrade` I continuously hit my application in a loop using the below command

`while true :; do sleep 1; echo 'OK' ; curl --insecure -X GET 'https://myservice-myCompanydns.com/health'; done`

As soon as the `helm upgrade` completes I see 2-3 seconds of downime in the application giving  `503 Service Temporarily Unavailable` error
**Anything else we need to know?**:
The request to the above `myservice-myCompanydns.com` goes through an Amazon ELB.
I am not able to attach the yaml files. How should I send my yaml files?

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:17:28Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.8-eks-7c34c0", GitCommit:"7c34c0d2f2d0f11f397d55a46945193a0e22d8f3", GitTreeState:"clean", BuildDate:"2019-03-01T22:49:39Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration: 
AWS

- OS (e.g: `cat /etc/os-release`): 
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

- Kernel (e.g. `uname -a`):
Linux wine-deployment-645c8b58dd-pwggj 4.14.94-89.73.amzn2.x86_64 

- Install tools:
None
- Others:

Below are my resource files

![Deployment-yaml](https://user-images.githubusercontent.com/40738665/55136369-392f1380-5154-11e9-80b5-ff7e557ab22f.png)
![ingress-yaml](https://user-images.githubusercontent.com/40738665/55136374-3c2a0400-5154-11e9-9c4b-433b0eff9a0e.png)
![service-yaml](https://user-images.githubusercontent.com/40738665/55136382-3f24f480-5154-11e9-934a-0fd7d2fc1d73.png)

**Comment by kanibs** [comment]
@kubernetes/sig-contributor-experience-bugs

**Comment by cblecker** [comment]
Please re-post your question to [Stack Overflow](http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases.

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans Stack Overflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search Stack Overflow for answers to similar questions, and also familiarize yourself with:

  * [user documentation](https://kubernetes.io/docs/)
  * [troubleshooting guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/)

Again, thanks for using Kubernetes.

The Kubernetes Team

---
/triage support
/close
