### ISSUE TITLE
Enforce minimum kubectl version on API server

### ISSUE THREAD

**Issue by krisdock** [kubernetes/kubernetes#75886]
**What would you like to be added**:
Would like to see a mechanism added to the kube-apiserver for enforcing a minimum kubectl version.

**Why is this needed**:
To protect both the cluster and end users in light of the recent kubectl CVE.

**Comment by ncdc** [comment]
/sig api-machinery
cc @deads2k @liggitt @sttts

**Comment by anguslees** [comment]
A version check cannot be used as a security mechanism since it trusts whatever version the client declares - a malicious client would just lie about the version.  Specifically, this would _not_ help with CVE-2019-1002100 (malicious json-patch).

There are also many other API clients out there, and kubectl is only one of them.  What does the "kubectl version" mean for kubecfg, for example?

A simple user-agent regex match _might_ be useful for some accidental DoS scenarios, provided clients report unique/accurate user-agent strings (this is hard atm given the link-time versions reported by client-go) but I'm quite worried we're straying into false security here.

**Comment by krisdock** [comment]
@anguslees thank you for the update. That makes sense. I'll go ahead and close this.
