### ISSUE TITLE
Two consecutive dollar signs in env translate to single dollar sign.

### ISSUE THREAD

**Issue by afield-sfdc** [kubernetes/kubernetes#75907]
I have an env var like so

```
          env:
            - name: TEST_FOO
              value: "$$WHAT"
```

kubectl shows

```
    Environment:
      TEST_FOO:                                  $$WHAT

```

When my container runs I see `TEST_FOO=$WHAT`

Possibly this is working as designed, but I don't see it documented anywhere.

**Comment by afield-sfdc** [comment]
kubectl version
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:08:12Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-10T23:28:14Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by neolit123** [comment]
/triage support
/sig node

i think it's how variables can be escaped in the Downward API.
https://docs.openshift.com/container-platform/3.6/dev_guide/downward_api.html#dapi-escaping-environment-variable-references
although escaping any `"$$"` sequence in a random string such as `"$$A$$B$$" -> "$A$B$"` seems a bit odd.

**Comment by liggitt** [comment]
See documentation at https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.14/#envvar-v1-core

/close

**Comment by mattfeury** [comment]
i get that this would be a breaking change to revert, but at the least it would be great if there was a way to just turn this functionality off. we got bit as well because a secret value had $$ in it and things just broke unexpectedly. we're now having to do string replace on every env var to work around this. luckily found this post which proved we weren't crazy: https://jellepelgrims.com/posts/dollar_signs
