### ISSUE TITLE
CSI topology doesn't handle non-prefixed keys correctly

### ISSUE THREAD

**Issue by msau42** [kubernetes/kubernetes#76113]
**What happened**:
The CSI spec allows topology keys to be non-prefixed.  In that case, we should be prepending our own prefix to the key, but right now it just [directly applies](https://github.com/kubernetes/kubernetes/blob/ad27abde622f9d9dec9977466bb2c0dace4e30a3/pkg/volume/csi/nodeinfomanager/nodeinfomanager.go#L348) that non-prefixed label to the Node object.

**What you expected to happen**:
We should prefix the Node label with the csi driver name

**Comment by msau42** [comment]
@kubernetes/sig-storage-bugs 
cc @verult on what the correct behavior should be

**Comment by avorima** [comment]
If I may chime in for a user perspective opinion; I think this is good. It gives me complete control over what my topology key is supposed to look like. I'd rather not see an error or warning for "incorrect" topology key, or even worse that it's just ignored.

**Comment by msau42** [comment]
It opens up the possibility for conflicting topology keys between different drivers. Also need to consider the security implications

**Comment by mucahitkurt** [comment]
@msau42, @verult if the correct behaviour is `prefix the Node label with the csi driver name` I can fix this issue?

**Comment by verult** [comment]
I want to point out that simply prefixing the node may not be enough. In order to keep the prefix as an implementation detail rather than something exposed to the user, the external provisioner might need to be changed in how to deal with StorageClass AllowedTopologies for example. Should AllowedTopologies be specified with the k8s label format or the driver-provided topology format? See [here](https://github.com/kubernetes/community/pull/911#pullrequestreview-169036949) for a previous proposal on how changing the topology prefix could be done.

Another potential problem is, if there is a k8s label -> driver-provided topology translation step (maybe there isn't), how to recognize a label has a prefix generated by kubelet and remove it.

If the CSI spec allows un-prefixed topology keys and doesn't claim keys must be unique across drivers, and k8s claims to implement the spec, IMO we should respect the possibility of overlapping keys. If it's allowed in the spec, it should be possible for users to take advantage of it.

A driver could add labels that conflict with a different driver, affecting the topology behavior of the other driver, but this problem exists for both prefixed and un-prefixed topology keys. A more fault-proof solution would be to prevent a driver from registering if its topology keys already exist in the cluster, but I don't think this conflict should be guarded based on my argument above.

Cluster admins should only install drivers they trust. The CSI spec recommends storage vendors to use prefixes and explains the risks of not doing so.

Given the above considerations I'm leaning towards leaving the behavior as is.

**Comment by msau42** [comment]
Thanks for the explanation! I think nothing needs to be done here.
/close
