### ISSUE TITLE
[Failing Test]: [sig-storage] CSI Volumes (pull-kubernetes-e2e-gce)

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubernetes#76166]
**Which jobs are failing**:
pull-kubernetes-e2e-gce

**Which test(s) are failing**:
```
[sig-storage] CSI Volumes [Driver: csi-hostpath] [Testpattern: Dynamic PV (block volmode)] multiVolume should access to two volumes with different volume mode and retain data across pod recreation on the same node
```

```
test/e2e/storage/testsuites/multivolume.go:180
Unexpected error:
    <*errors.errorString | 0xc0028b7e60>: {
        s: "PersistentVolumeClaims [pvc-dt6vs] not all in phase Bound within 5m0s",
    }
    PersistentVolumeClaims [pvc-dt6vs] not all in phase Bound within 5m0s
occurred
test/e2e/storage/testsuites/base.go:330
```

**Since when has it been failing**:
unknown

**Testgrid link**:
https://prow.k8s.io/job-history/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-e2e-gce

**Reason for failure**:
unknown

**Anything else we need to know**:
PR that introduces the new test:
https://github.com/kubernetes/kubernetes/pull/74693

/assign @msau42 @mkimuram @wongma7 
@kubernetes/sig-storage-bugs 
/sig storage
/kind flake
/priority critical-urgent

the job is PR blocking and is flaking mutliple times in a row.

**Comment by neolit123** [comment]
@Katharine from SIG Testing mentioned that probably the whole job is timing out, so this might not be a SIG Storage problem per-se.
we need the `pull-kubernetes-e2e-gce` owners to triage the problem.

**Comment by msau42** [comment]
Here's one example run:
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce/1113867644991180803

**Comment by neolit123** [comment]
> we need the pull-kubernetes-e2e-gce owners to triage the problem.

i've sent an email to k-dev to see who reacts.
increasing the timeout is the preferred option for now.

**Comment by Katharine** [comment]
To clarify I think this is a real failure that really happened at least twice, but it is likely not the primary cause of pull-kubernetes-e2e-gce currently being broken, and almost all failed pull-kubernetes-e2e-gce runs that I see had this test pass.

**Comment by msau42** [comment]
Let's use this bug to triage this specific test case

**Comment by msau42** [comment]
The first provision succeeded:
0404 18:32:48.073587       1 controller.go:926] provision "multivolume-4799/pvc-mvjvq" class "multivolume-4799-csi-hostpath-multivolume-4799-scjmgx4": started

The second one failed because it couldn't find the storage class:
I0404 18:32:50.107076       1 controller.go:926] provision "multivolume-4799/pvc-985xh" class "multivolume-4799-csi-hostpath-multivolume-4799-scm9tnq": started
E0404 18:32:50.145867       1 controller.go:949] provision "multivolume-4799/pvc-985xh" class "multivolume-4799-csi-hostpath-multivolume-4799-scm9tnq": error getting claim's StorageClass's fields: storageClass "multivolume-4799-csi-hostpath-multivolume-4799-scm9tnq" not found

**Comment by wongma7** [comment]
The provisioner doesn't retry/requeue if the storageclass is not found. I guess it is flaky because the pvc is created immediately after the sc and even though the provisioner has watches on both, it's possible it sees pvc before sc? It's a bug in the external library, not an issue with in-tree because it retries everything every 15s. So I'll need to update the library, update hostpath plugin, then update our manifests here.

btw, how did you find that log @msau42?

**Comment by wongma7** [comment]
There is probably something else wrong because every other dynamic provisioning test creates pvc immediately after the sc. Why does only this one flake?

**Comment by msau42** [comment]
We store all the CSI driver logs for each test case under artifacts

**Comment by mkimuram** [comment]
> There is probably something else wrong too* because every other dynamic provisioning test creates pvc immediately after the sc.

Should we just add wait before [here](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/storage/testsuites/base.go#L207) and [here](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/storage/testsuites/provisioning.go#L247)?

Or are there any ways to ensure that storageClass is ready? (like checking that storageClass can be got after creation.)

**Comment by wongma7** [comment]
I don't think wait is the solution. Even if the test does a Get after Create, there is no guarantee that the provisioner pod's informer has seen the StorageClass too.

I've opened https://github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/pull/38 for now

I am still unsure why only this test is flaking frequently, if the issue is race between controller seeing PVC first or SC first, one would expect a lot of other external provisioner tests to fail too...

**Comment by wongma7** [comment]
@mkimuram I guess given the frequency of failures, waiting for SC to exist after the Create call could be a good stopgap solution. Fixing the lib->hostpath plugin->test will take a lot more time.

**Comment by mkimuram** [comment]
@msau42 

Can we wait until @wongma7 's actual fix for this issue or do we need workaround to reduce this flake?

**Comment by msau42** [comment]
Let's go with @wongma7 's fix. I don't think it should take too long

**Comment by msau42** [comment]
https://github.com/kubernetes-csi/external-provisioner/releases/tag/v1.1.0-rc2
