### ISSUE TITLE
HPA not scaling down after pods failed to start

### ISSUE THREAD

**Issue by Myridor** [kubernetes/kubernetes#76187]
**What happened**:
HPA is not scaling down with 0% usage after pods failed to start (while having high usage) due to insufficient cpu

**What you expected to happen**:
HPA scaling down

**How to reproduce it (as minimally and precisely as possible)**:
- Use simple cluster and the php-apache example
- Asign more CPU/MaxPods than possible
- Do the test until some pods cant start due to insufficient cpu
- Wait

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.14.0
- OS (e.g: `cat /etc/os-release`): Ubuntu 18.04 LTS
- Others: VirtualBox VM

I waited around 20 minutes now and still not downscaled.
If you need more information please let me know.

![GetPods](https://user-images.githubusercontent.com/14092331/55619308-b122bc80-5798-11e9-9401-8542964db837.png)
![DescribePod](https://user-images.githubusercontent.com/14092331/55619312-b3851680-5798-11e9-9e7f-86ecf36f93ee.png)
![GetHpa](https://user-images.githubusercontent.com/14092331/55619324-ba138e00-5798-11e9-8fef-9521efa28585.png)
![DescribeHpa](https://user-images.githubusercontent.com/14092331/55619326-bbdd5180-5798-11e9-9158-ca9b7e86811d.png)

**Comment by SaltedEggIndomee** [comment]
I have the exact same problem using Kubernetes 1.12. 

The problem was that 1 of the kubelet in 1 of the Node went down due to expired certificate. 
> failed to run Kubelet: failed to create kubelet: failed to initialize certificate manager: failed to initialize server certificate manager: could not decode the first block from "/var/lib/kubelet/pki/kubelet-server-current.pem

Solution : 
1) SSH into node 
2) rm /var/lib/kubelet/pki/kubelet-server-current.pem
3) systemctl restart kubelet 

Now the Node is back up, the HPA is able to schedule the Pod on the Node, and the scaling up/down of HPA is working fine. 

ATTENTION : this is not the solution to the above bug by HPA. It's one solution to ensure your scaled Pods start successfully, to avoid running into the above bug.

**Comment by thlearn** [comment]
having exct issue any updates on this
