### ISSUE TITLE
Kustomize in kubectl should be marked experimental, CLI process gap

### ISSUE THREAD

**Issue by ibuildthecloud** [kubernetes/kubernetes#76232]
There seems to be some major gap in the adoption process of CLI features.  I do not follow SIGs or kubernetes PRs closely, which puts me in the same category as 99.9% of your users. One of the nice outcomes of the k8s alpha/beta/GA graduation is that users have the ability to try and comment on features before they become GA and they don't need to track the development of k8s or be a member of SIGs.

I've seen some references that kustomize had some disagreements or discusses around why it was merged.  I don't know what that was and really don't care.  What I don't particularly like in this case is that k8s developers have graduated a component and integrated it in k8s without any proper way for users to give feedback before being declared GA.

Features shouldn't just land in CLI without going through some graduation.

**Comment by pwittrock** [comment]
Thanks for your concern.

Kustomize graduated to **Beta** after a lengthy pre-Beta process as a stand alone component, during which time, valuable feedback from real world users was solicited and acted upon.

- Kustomize had been available as a separate sig-cli downloadable binary for a year before being integrated into kuberctl and was seeing active adoption.
- Graduation criteria was defined 7 months prior to the PR to introducing it into kubectl being merged, and included real world use - (which has not typically been a requirement cli commands to graduate from Alpha).
- Sig-CLI developers worked with Kustomize users to iterate on functionality
- Kustomize addressed long standing bugs in the `kubectl apply` command.

Before graduating to **Beta**, Kustomize was being used by multiple companies, start ups had developed products around it, and it was the topic of Kubecon talks.  AFAIK, this is a more rigorous standard than has been used for introducing or graduating any other feature to the cli.

If you are asking that new features to be added directly to kubectl under the `alpha` subcommand, or as `hidden` (not appearing in help) rather than as stand alone components, this would be good to know.  One disadvantage of the `alpha subcommand` approach is that (for things tied to the k8s release cycle) it provides fewer iterations to apply the feedback.

Hope this clears things up.

See the discussion in [this thread](https://groups.google.com/forum/#!searchin/kubernetes-sig-cli/kustomize$20in$20kubectl%7Csort:date/kubernetes-sig-cli/6NFaDdc0Q8U/3AzbmECwDQAJ) for specifics on the precise process followed.
