### ISSUE TITLE
Need a way to run tests not marked `[Serial]` in parallel

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#76344]
Follow up from https://github.com/kubernetes/kubernetes/issues/62161

Right now, say for example in the conformance tests, we always force sonobuoy to run *all* the tests in Serial mode, since we have a few tests that are marked `[Serial]` in that bucket. It would be nice to run all the ones not marked `[Serial]` in parallel before we run the `[Serial]` tests to save on time.

/area conformance

**Comment by neolit123** [comment]
/sig testing
/area e2e-test-framework

i think this becomes a question if ginkgo supports controllable number of nodes per test.
i don't think it does.

if the suite is already in parallel mode, and if the suite reaches a SERIAL test it would have to block running this tests until the rest of the nodes have finished.

the alternative would be run all single-node-demanding tests up front and only then ramp up the node numbers. this will result in minimal execution time per single mixed pass. but again the problem here is that this is unsupported.

the 2 options i see for this are:
- A) multiple conformance suites one for serial one for parallel.
- B) multiple passes on the same suites with nodes=1 and nodes>1, fully skipping the according tests.

cc @timothysc @andrewsykim @johnSchnake

**Comment by johnSchnake** [comment]
The recommendation we always give people from a Sonobuoy perspective is this:
 - By default (in Sonobuoy) everything is run in serial which helps reduce flakes based on unintended interactions or load on the system.
 - If you want to reduce testing time for CI purposes, you should do 2 separate runs manually separating out the serial tests

I don't particularly like the idea of this being handled by the test framework itself, especially since the users can manually accomplish the same thing.

It seems like option (A) is just a convenience which makes it a little easier to do this 2-separate-run flow but isn't really different. Meanwhile, starting to separate out a new suite seems like it would inevitably lead to other issues (duplicate tests, confusion over when/where to put certain things, etc)

Option (B) sounds like we'd accomplish the same thing (run one set of tests in parallel, then the other) but all the logic is baked farther down. This makes the model more confusing about how the pieces work together (e2e tests, the test framework logic, ginkgo, conformance image and env vars).

Years ago this seems to have come up for the same reason and ginkgo argued the same thing: just do it manually so that you simplify the execution model and avoid complicated corner cases: https://github.com/onsi/ginkgo/issues/294

**Comment by neolit123** [comment]
> Years ago this seems to have come up for the same reason and ginkgo argued the same thing: just do it manually so that you simplify the execution model and avoid complicated corner cases: onsi/ginkgo#294

thanks for the link. this is a ticket i was looking for myself.

> - By default (in Sonobuoy) everything is run in serial which helps reduce flakes based on unintended interactions or load on the system.

the kind non-serial tests provide some history on recent runs against master.
https://k8s-testgrid.appspot.com/sig-testing-kind#conformance,%20master%20(dev)%20%5Bnon-serial%5D

i'd say that the flakes are close to 0, possibly that is why @dims wants to push the conformance image to be tested in parallel by default, minus the serial tests.

> - If you want to reduce testing time for CI purposes, you should do 2 separate runs manually separating out the serial tests

this is my immediate preference to solve the problem (which is the same as B).
i don't see any other way to accomplish the desired outcome, except multi-pass.

**Comment by timothysc** [comment]
Well there are some broader questions I have about some of the serial tests.  I would think it should be the exception versus the norm that we are forced to run things serially and if we should try to fix most of the tests to be able to run in parallel.  

This is not an easy answer, but I do think it's the right one.  Some tests are just poorly written to be run in a parallel fashion.  On the sonobuoy front we can still default to serial but unblock the rest of the e2e-suite/framework.

**Comment by johnSchnake** [comment]
I'm not perfectly clear on the direction here; @timothysc you're suggesting that we just make as many serial tests non-serial, right?

Also, is `Serial` a supposed to be a no-go for conformance tests? Just using grep (haven't run a dry run to check if there are more) I found one serial, conformance test: ```
test/e2e/storage/empty_dir_wrapper.go:	framework.ConformanceIt("should not cause race condition when used for configmaps [Serial]"
```

**Comment by johnSchnake** [comment]
By the way, that test was introduced years ago: https://github.com/kubernetes/kubernetes/commit/8ff00d17d82832422d428d4b39d8282378403216#diff-39348fe7d9d178b32bb2a4744f3d00ecR155

It says it needed serial because:
```
	// They need to be [Serial] and [Slow] because they try to induce
	// the race by creating pods with many volumes and container volume mounts,
	// which takes considerable time and may interfere with other tests.
```

I don't see why creating many pods with many volumes/mounts would interfere with any other tests.

As part of this ticket, does anyone have a problem with removing the serial tag from this test? At least at that point we would have 0 conformance tests being serial.

**Comment by aojea** [comment]
This can be done with Ginkgov2 https://github.com/kubernetes/kubernetes/issues/111944 but as Ben mentioned there, we should understand the consequences and the intersection with current tests, we don't want to increase significatively the time to run the tests  .... maybe we can do this only for Conformance?
