### ISSUE TITLE
Support additional health probe types for Azure Load Balancer

### ISSUE THREAD

**Issue by amargherio** [kubernetes/kubernetes#76657]
**What would you like to be added**: Support for additional load balancer health probe configurations (specifically HTTP and HTTPS) for Azure Load Balancers.

**Why is this needed**: The generated Azure Load Balancers for `LoadBalancer` type services only support TCP health probes. Those guarantee that the backend pool consists of nodes listening on the target port but do not validate whether or not anything is responding. We've also noticed elevated volumes  SSL handshake errors generated by the TCP health checks targeting 443 when using more verbose log level configurations in ingress-nginx.

It would be valuable to configure the type of health probe used by the AKS-created Azure Load Balancer.

**Comment by singhania** [comment]
Is there any update on this?

**Comment by feiskyer** [comment]
@justaugustus @craiglpeters what do you think about this feature requests?

**Comment by pascalgn** [comment]
I had a look at a possible implementation. I did not create a PR yet, because the relevant files are in `legacy-cloud-providers` and the [README](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/legacy-cloud-providers/README.md) said there should only be bug fixes, no new features.

---

In azure_loadbalancer.go, there is some logic which would lead to the load balancer created with protocol HTTP (which is what we want)

https://github.com/kubernetes/kubernetes/blob/3edbc6afff17ea8dfe5c10b2677dcdc8767f67e2/staging/src/k8s.io/legacy-cloud-providers/azure/azure_loadbalancer.go#L1039-L1052

The check is from here:

https://github.com/kubernetes/kubernetes/blob/3edbc6afff17ea8dfe5c10b2677dcdc8767f67e2/staging/src/k8s.io/cloud-provider/service/helpers/helper.go#L102-L107

and the "RequestsOnlyLocalTraffic" is about the `externalTrafficPolicy`: https://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/#preserving-the-client-source-ip

However, I do not understand the relationship here, why setting `externalTrafficPolicy: Local` should result in HTTP health check.

---

What I think we could do is add a new annotation like

```go
ServiceAnnotationLoadBalancerProtocolHttp = "service.beta.kubernetes.io/azure-load-balancer-protocol-http"
```

and when this is set to `"true"`, the health check will use the HTTP protocol in [azure_loadbalancer.go](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/legacy-cloud-providers/azure/azure_loadbalancer.go#L1021).

We could also add an additional annotation to set the `RequestPath` property of the health check probe, this could be used so that people can set the path to `/healthz` or similar.

**Comment by vavenk-ms** [comment]
We have a similar requirement for having an http health probe with a custom path. According to @pascalgn's comment, we could get an http probe by setting `externalTrafficPolicy: Local` but our service expects health probes on a different path, not `/healthz`. Looks like @pascalgn's proposed solution would work for us too. Are there any workarounds to achieve this currently?
