### ISSUE TITLE
Flag deprecation messages should be sent to klog

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#76873]
Flag deprecate messages e.g. `Flag --resource-container has been deprecated, This feature will be removed in a later release.` are sent only to stderr (I believe), and are not logged to the log-file.

With the move to make the logfiles canonical, and to stop redirect stdout/stderr to log files, we should probably tackle this if we expect deprecation notices to be seen.

**Comment by neolit123** [comment]
/sig architecture
cc @dims @vincepri 

for further details:

flags like that are marked using pflag:
https://github.com/kubernetes/kubernetes/blob/a9ab371f46ac746c8e3d293d83d485b1fdfc5f26/cmd/kube-proxy/app/server.go#L157

pflag prints using stderr by default, unless SetOutput is set to something else:
https://github.com/spf13/pflag/blob/master/flag.go#L473
https://github.com/spf13/pflag/blob/master/flag.go#L246-L251
https://github.com/spf13/pflag/blob/master/flag.go#L255-L257

if we have to modify all deprecation notices to use klog() calls it might be quite tricky.

**Comment by erain** [comment]
Looks like this is really old. 

I search the current `HEAD` and the only place I found the flag `resource-container` is in the [1.16 CHANGELOG](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/C:HANGELOG-1.16.md) which said the `resource-container` flag has been deprecated. 

So I think this issue is not relevant anymore and we can close it.
