### ISSUE TITLE
[Failing Test] openstack conformance is failing in master-informing

### ISSUE THREAD

**Issue by alejandrox1** [kubernetes/kubernetes#76896]
**Which jobs are failing**:
`ci-cloud-provider-openstack-acceptance-test-e2e-conformance`

**Which test(s) are failing**:
`Overall` ([spyglass](https://prow.k8s.io/view/gcs/k8s-conformance-openstack/periodic-logs/ci-cloud-provider-openstack-acceptance-test-e2e-conformance/1555907386))

**Since when has it been failing**:
Since 4/18.

**Testgrid link**:
https://testgrid.k8s.io/sig-release-master-informing#Conformance%20-%20OpenStack

**Reason for failure**:
It may be a test configuration issue because all tests passed:
```
Ran 214 of 4082 Specs in 5331.224 seconds
SUCCESS! -- 214 Passed | 0 Failed | 0 Pending | 3868 Skipped
PASS
Ginkgo ran 1 suite in 1h28m52.607588602s
Test Suite Passed
Apr 22 06:00:33.999: DONE
```

/kind failing-test
/priority important-soon
/milestone v1.15
/cc @kubernetes/sig-openstack-test-failures 

/cc @jimangel @smourapina @rarchk @alenkacz

**Comment by mrhillsman** [comment]
/cc @dims 
ack @alejandrox1 
will consult with the team. i thought that overall failure cell was a result of tests being back active and only have one result set.

**Comment by mrhillsman** [comment]
@alejandrox1 I have found the issue, maybe others will/have experienced it. Also, for OpenLab at least, the change would need to happen within kubernetes/test-infra and I do not know who to reach out to but here it is.

When we run conformance we use the upload_e2e.py script[0]. Within this file there is a regex match used to create finished.json which Overall uses to color its cell red or green:

```vim
 59 # Ginkgo gives a line like the following at the end of successful runs:
 60 # SUCCESS! -- 123 Passed | 0 Failed | 0 Pending | 587 Skipped PASS
 61 # we match this to detect overall success
 62 E2E_LOG_SUCCESS_RE = re.compile(r'SUCCESS! -- .* PASS')
```

However the PASS portion is not on the same line, it comes after in our log:

```txt
Apr 22 05:58:38.044: INFO: Skipping dumping logs from cluster

Ran 214 of 4082 Specs in 5331.224 seconds
SUCCESS! -- 214 Passed | 0 Failed | 0 Pending | 3868 Skipped
PASS

Ginkgo ran 1 suite in 1h28m52.607588602s
Test Suite Passed
Apr 22 06:00:33.999: DONE
```

Because of this finished.json is reporting failure[1] for these jobs. I looked at the following bucket[2].




[0] https://raw.githubusercontent.com/kubernetes/test-infra/master/testgrid/conformance/upload_e2e.py
[1] https://storage.googleapis.com/k8s-conformance-openstack/periodic-logs/ci-cloud-provider-openstack-acceptance-test-e2e-conformance/1555907386/finished.json
[2] https://console.cloud.google.com/storage/browser/k8s-conformance-openstack/periodic-logs/ci-cloud-provider-openstack-acceptance-test-e2e-conformance/1555907386

**Comment by dims** [comment]
@mrhillsman please file a PR with a fix to the regex :)

**Comment by BenTheElder** [comment]
Is something else wrapping the output? I didn't think ginkgo did that. I've never seen wrapped output from running the tests directly or from sonobuoy. :O

**Comment by alejandrox1** [comment]
Tests are running, test are green. We hereby close this issue.
/close
