### ISSUE TITLE
Inconsistency imports of core/v1 package 

### ISSUE THREAD

**Issue by draveness** [kubernetes/kubernetes#77045]
**What would you like to be added**:

Currently, there are many `k8s.io/api/core/v1` imports in the project, and we could see two approaches for imports. I used ag to count the pkg imports and found out as below.

```go
$ ag -c "\t\"k8s.io/api/core/v1\"" | wc -l
    1215

$ ag -c "\tv1 \"k8s.io/api/core/v1\"" | wc -l
     120
```

There are 1215 imports with `"k8s.io/api/core/v1"` and 120 imports with `v1 "k8s.io/api/core/v1"`.

I met this problem for quite a long time since the first day I started to submit commits and PRs to kubernetes - goimports keep adding alias before this pkg imports, and I have to delete it in the text editor.

The way of importing this pkg with alias is preferred as discussion in https://github.com/kubernetes/kubernetes/pull/76337/files#r273625182, and I quote from @johnSchnake 

> goimports does this now for performance reasons since the path uses a symlink and the import path isnt the real path.

**Why is this needed**:

+ Maintain the consistency of ways to import packages.
+ Performance improvement for goimports

/cc @johnSchnake

**Comment by johnSchnake** [comment]
Consistent with my attempt here:
https://github.com/kubernetes/kubernetes/pull/76863

It becomes a large diff and I think I may have hit a bug with goimports (I was ending up with duplicate imports, one aliased and the other not) in some cases. I haven't had time in the past few days to try and analyze the failure cases.

Ideally, we'd be able to just fix goimports and then get something like this in. It does help with consistency (your stated goal) but it also helps with large refactors where you may need to change the imports of hundreds of files.

Until it is fixed, it will just be a manual process.

**Comment by draveness** [comment]
> Consistent with my attempt here:
> #76863
> 
> It becomes a large diff and I think I may have hit a bug with goimports (I was ending up with duplicate imports, one aliased and the other not) in some cases. I haven't had time in the past few days to try and analyze the failure cases.
> 
> Ideally, we'd be able to just fix goimports and then get something like this in. It does help with consistency (your stated goal) but it also helps with large refactors where you may need to change the imports of hundreds of files.
> 
> Until it is fixed, it will just be a manual process.

Maybe we could replace the `"k8s.io/api/core/v1"` manually with `v1 "k8s.io/api/core/v1"` which could solve the major part of this problem.

**Comment by draveness** [comment]
We could have something like [.golint_failures](https://github.com/kubernetes/kubernetes/blob/master/hack/.golint_failures), make the `goimports` as the CI check, and label this issue with "good first issue" let the community help us with this.

/cc @andrewsykim @timothysc

**Comment by cblecker** [comment]
We don't use goimports.. as you noticed it does some weird things and isn't needed. Why is this an issue?

**Comment by draveness** [comment]
> We don't use goimports.. as you noticed it does some weird things and isn't needed. Why is this an issue?

I think the problem we want to solve here is the inconsistency. And many kubernetes contributors do use `goimports` when submitting commits. That's the reason why there are many imports with alias like `v1 "k8s.io/api/core/v1"`. It is helpful to put some constraints on packages import, and `goimports` may be a good choice.

**Comment by johnSchnake** [comment]
So another option which I've been told is more preferable (and is certainly more clear) is `corev1` which actually requires effort to introduce but just like how we are using `e2essh` and `e2elog` it is definitely more clear.

Putting up a PR to change the framework folder to that alias. Will need to be piecemeal since this changes every reference to every core v1 object; there were ~7k in all of e2e so I scoped my PR just to the e2e/framework which was about 1k.

**Comment by johnSchnake** [comment]
Multiple conversations on slack and in PRs has me at the understanding that:
 - there is no desire to default to goimports
 - there is little desire for consistency of imported names when otherwise we don't have a reason to touch those lines
 - goimports aliases like v1 on core/v1 code is an annoyance that doesn't generally block PRs but it isn't any form of endorsement of the alias itself and it wouldn't hurt to discourage the practice, especially if they are doing large PRs.

My PR for updating to the corev1 alias I think is going to get closed (trying to get final confirmation) but as a corollary I think this issue may be closed as `Won't Do` as well.

Thats my understanding; tell me if I'm mistaken @dims

**Comment by dims** [comment]
@johnSchnake if you can get in some code cleanup when you touch some code, that's perfectly fine as long as it is ok with the reviewers. I don't want to start a "cleanup-all-the-imports-everywhere" right now given all the discussion about the various tools etc.

**Comment by dims** [comment]
/close

@johnSchnake @draveness ok to close this for now?

**Comment by Huang-Wei** [comment]
The `v1` is introduced by `goimports` which is the default option in vscode I guess.

Here is the journey I fight with the annoying `v1` alias :) FYI:

Sometime late last year, I happened to see some of files autosaved with an unnecessary import alias like:

```go
import (
    v1 "k8s.io/api/core/v1"
)
```

This really annoyed me, and finally I found the solution to change default formatting tool from `goimports` to `gofmt`.

Everything works fine since then.

Recently after switching to gomod, I found the "Go to definition" (CMD+click) gets really slow. And I found a solution to enable `go.useLanguageServer` which dramatically improves the performance. However, it brings in back the annoying "unnecessary v1 alias" issue. I guess it's because the builtin formatting tool in `gopls` is `goimports`. I tried to disable the formatting in "go.languageServerExperimentalFeatures", but didn't work. Then surprisingly I found a magic combination with (1)source.organizeImports=false and (2)languageServerExperimentalFeatures.format=false can resolve the issue. FYI my configuration:

```json
{
    "[go]": {
        "editor.snippetSuggestions": "none",
        "editor.formatOnSave": true,
        "editor.codeActionsOnSave": {
            "source.organizeImports": false
        },
    },
    "go.useLanguageServer": true,
    "go.languageServerExperimentalFeatures": {
         "format": false
    },
    "go.formatTool": "gofmt"
}
```
