### ISSUE TITLE
Add unit tests for Migration scenarios for Operation Generator

### ISSUE THREAD

**Issue by davidz627** [kubernetes/kubernetes#77141]
/sig storage
/kind cleanup
/kind enhancement

This is necessary to make sure that operation generator functions use the correct plugins when being run with migration on/off. Additionally we should check that the metrics generated from the `CompleteFunc` are generated with the correct plugin name

**Comment by mucahitkurt** [comment]
Hey @davidz627 , I would like to work on this issue, initially I try to write unit tests for the metrics generated from the `CompleteFunc`.

**Comment by davidz627** [comment]
Hi @mucahitkurt, thanks for your interest. That sounds great and could you please clarify some details on what tests you plan to rwrite?

**Comment by mucahitkurt** [comment]
> Hi @mucahitkurt, thanks for your interest. That sounds great and could you please clarify some details on what tests you plan to write?

@davidz627 ,

For the `CompleteFunc` I try to test which plugin name is used to generate metric, as creating `CompleteFunc` both `csiMigration` enabled and disabled cases. 

To do this I initialize both plugins that's are `csiMigration` enabled plugin like `gcePdVolumePlugin` and `csiPlugin`, and then generate the function, check the produced metric labels.

I try to write tests like this one https://gist.github.com/mucahitkurt/1232cecd02c4884a197d7e3b51f1d331.

For the generated function tests I don't have very clear ideas about how to test which plugin is used when those functions are executed for now, because there are different use cases for those functions, someone uses the plugin that's found the outside of the generated function, someone uses the plugin that's found the inside of the generated function, every function use this plugin for different purpose etc.
