### ISSUE TITLE
Use worker pool for killing Pods

### ISSUE THREAD

**Issue by tedyu** [kubernetes/kubernetes#77166]
**What would you like to be added**:
Add worker pool which is used to kill Pods.

**Why is this needed**:
Currently in Kubelet#podKiller, when we retrieve PodPair, we spin off goroutine (per PodPair).

By using worker pool which kills Pods, we can limit resource consumption - in case there is surge in pod killing requests.

**Comment by mattjmcnaughton** [comment]
Thanks for opening this issue @tedyu :)

Can you please share more about the practical ramifications of creating goroutines as necessary instead of having a worker pool? Specifically, are you concerned about the resource consumption of the goroutines themselves or the resource consumption of the code executing within the goroutine if there is no bound on how many pods are being killed in parallel?

If the former, I'm not sure that's something we need to worry about. Re the [go documentation](https://golang.org/doc/faq#goroutines), goroutines are exceptionally cheap, so even if there are thousands of them running at once, it still shouldn't be a problem.

Overall, I'm not opposed to using a worker pool, but I think I need a little more detail to be confident its going to have a practical impact.

Would love to talk more about this :)

**Comment by tedyu** [comment]
My concern was w.r.t. resource consumption of the potentially concentrated pod killing.
I think using worker pool serves as rate limiting so that related components are not stressed even if there are high number of pods to be killed in a short period of time.

Thanks

**Comment by mattjmcnaughton** [comment]
On Tue, Apr 30, 2019 at 08:41:25AM -0700, Ted Yu wrote:
> My concern was w.r.t. resource consumption of the potentially concentrated pod killing.
> I think using worker pool serves as rate limiting so that related components are not stressed even if there are high number of pods to be killed in a short period of time.
> 
> Thanks
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/kubernetes/kubernetes/issues/77166#issuecomment-488003129

Thanks for clarifying :) Do we have evidence of related components being
stressed when a high number of pods are killed in a short time? I ask because
transitioning to a worker pool may mean pods take longer to be killed, and we
only want to occur that cost if its necessary.
