### ISSUE TITLE
What about adding this project to sonarqube?

### ISSUE THREAD

**Issue by 030** [kubernetes/kubernetes#77212]
By adding this project to sonarcloud, codesmells, vulnerabilities could be reported.

**Comment by dims** [comment]
@030 will you be able to help try this out? essentially fork kubernetes/kubernetes into your own org, try sonarqube and share results for us to look at? This will help decide if the service is useful enough to point at the kubernetes/kubernetes directly.

**Comment by 030** [comment]
```
ERROR: 

The only way to get an accurate analysis of C/C++/Objective-C files is by using the SonarSource build-wrapper
and setting the property "sonar.cfamily.build-wrapper-output", but it was not specified.

If you don't want to analyze C/C++/Objective-C files, then prevent them from being analyzed by setting the following properties:

    sonar.c.file.suffixes=-
    sonar.cpp.file.suffixes=-
    sonar.objc.file.suffixes=-


INFO: ------------------------------------------------------------------------
INFO: EXECUTION FAILURE
INFO: ------------------------------------------------------------------------
INFO: Total time: 2:30.162s
INFO: Final Memory: 47M/1591M
INFO: ------------------------------------------------------------------------
ERROR: Error during SonarQube Scanner execution
ERROR: 

The only way to get an accurate analysis of C/C++/Objective-C files is by using the SonarSource build-wrapper
and setting the property "sonar.cfamily.build-wrapper-output", but it was not specified.

If you don't want to analyze C/C++/Objective-C files, then prevent them from being analyzed by setting the following properties:

    sonar.c.file.suffixes=-
    sonar.cpp.file.suffixes=-
    sonar.objc.file.suffixes=-


ERROR: 
ERROR: Re-run SonarQube Scanner using the -X switch to enable full debug logging.
```

It the first issue that occurred. I will try again and then added the suggested exclusions.

**Comment by 030** [comment]
@dims and @neolit123 

![k8s-sonarqube](https://user-images.githubusercontent.com/7524528/56931604-d88f4f80-6ae0-11e9-9853-4f5095cde681.png)

![k8s-sonarqube2](https://user-images.githubusercontent.com/7524528/56931608-dcbb6d00-6ae0-11e9-9b5f-4997f01cd951.png)

![k8s-sonarqube3](https://user-images.githubusercontent.com/7524528/56931611-df1dc700-6ae0-11e9-9f9a-092aedd6bfc4.png)

**Comment by neolit123** [comment]
https://sonarcloud.io/dashboard?id=030_kubernetes

**Comment by neolit123** [comment]
i had a look and some of these are good suggestions for cleanups, but most of the high severity items are nothing "critical".

maybe we can leverage this website data WRT `good-first-issue`.
but a lot of static analysis based PRs are sent today already.

**Comment by dims** [comment]
@neolit123 i agree. it's just another lint tool at this point

**Comment by mansinahar** [comment]
@030 I came across the same issue as you today on a different Go project and just wanted to share that the behavior you saw was because, some of Go's core packages have `.c` files. For example: https://github.com/golang/sys/blob/master/cpu/cpu_gccgo.c. Since the [Kubernetes](https://github.com/kubernetes/kubernetes) project commits the [vendor](https://github.com/kubernetes/kubernetes/tree/master/vendor) directory, SonarQube tries to scan it too and in order for it to scan the `.c` files, it requires some kind of a special wrapper which it doesn't have unless you specifically install it and thus complains.

I was able to fix this by excluding the vendor directory from sonar analysis. You can do so by adding `sonar.exclusions=**/vendor/**` to your `sonar-project.properties` file unless you want to scan dependencies too which, IMHO shouldn't be needed for this project. Also, I'd assume this to reduce the scanning time too.

**Comment by dims** [comment]
/close

Looks like there's a way to run sonarqube and then folks can work on reviewing the results and propose issues and PRs. we don't want to do anything more "officially" at the moment so closing this out
