### ISSUE TITLE
Support multi size hugepages at host level

### ISSUE THREAD

**Issue by cheng1li** [kubernetes/kubernetes#77251]
**What would you like to be added**:

If I have two sizes of hugepages allocated on the node, the node stuck in notready status. I think this was discussed [in the proposal](https://github.com/kubernetes/community/pull/837/files#r133337110).  
I wonder if we can allow multiple sizes of hugepages on the host/node.

**Why is this needed**:

We can launch numbers of pods on one node. There are cases at where one pod needs 2M hugepages while another one needs 1G hugepages.

**Comment by mattjmcnaughton** [comment]
For context, here's the relevant discussion in the proposal: https://github.com/kubernetes/community/pull/837/files#diff-5b796e498a8c17ce3e0ec1afdd49b8e1R166

Could you please describe your use case in more detail @danielqsj ?

My understanding of the discussion in the proposal is that supporting multiple hugepage sizes requires some non-trivial API changes, and we'd only want to undertake these if there was significant community need.

**Comment by cheng1li** [comment]
@mattjmcnaughton , openstack-helm is a project which deploys openstack using kubernetes.
Users can create VM of hugepages size 2M. At the meaning while, user can also create 2G hugepage VM on the same host. So it needs both 2M hugepages and 1G hugepages on the host.
Until now, there is no needs for kuberntes hugepage support. As kuberntes doesn't support 2 sizes of hugepages existing on the host, we can turn off hugepage feature.

But recently, openstack-helm is supporting ovs-dpdk which needs hugepages in container(either 2M or 1Gi), so we will have to turn on kubernetes hugepages feature.  I can understand we don't support multiple hugepage sizes in a single pod, but is it necessary to limit it at host level?

**Comment by mattjmcnaughton** [comment]
Ahh, thanks @cheng1li - that helps better understand what you're trying to do.

It looks like from the discussion in @derekwaynecarr 's original PR (https://github.com/kubernetes/kubernetes/pull/50859), this was an intentional decision, but perhaps one we intended to revisit in a later release.

Would love to hear thoughts from @derekwaynecarr and @dchen1107  :)

**Comment by cheng1li** [comment]
Thanks for your attention on this issue and fast reply @mattjmcnaughton

**Comment by cheng1li** [comment]
@derekwaynecarr , @dchen1107 , could you please have a look of this at your convenience? Thanks

**Comment by odinuge** [comment]
With the feedback from this issue and https://github.com/kubernetes/kubernetes/issues/80452, I think it is time to look at this again. It looks like this is causing numerus issues for the users, and it looks like there are some legitimate use cases for using multiple sizes. The current implementation doesn't even allow reserving all the pre-allocated huge pages for a given size to the system, via the `--kube-reserved` flag, while allowing pods to use another one.

Adding support for multiple huge page sizes on the node level will be fully backwards compatible, and will only require some small changes in the code. Ill be happy to create a patch if we agree that we should add support for it.

Also, the [KEP 20190129-hugepages](https://github.com/kubernetes/enhancements/blob/master/keps/sig-node/20190129-hugepages.md) does not mention that the node should only support a single page size.

cc @derekwaynecarr, @mattjmcnaughton, @danielqsj

**Comment by mattjmcnaughton** [comment]
On Wed, Aug 21, 2019 at 09:38:59AM -0700, Odin Ugedal wrote:
> With the feedback from this issue and https://github.com/kubernetes/kubernetes/issues/80452, I think it is time to look at this again. It looks like this is causing numerus issues for the users, and it looks like there are some legitimate use cases for using multiple sizes. The current implementation doesn't even allow reserving all the pre-allocated huge pages for a given size to the system, via the `--kube-reserved` flag, while allowing pods to use another one.
> 
> Adding support for multiple huge page sizes on the node level will be fully backwards compatible, and will only require some small changes in the code. Ill be happy to create a patch if we agree that we should add support for it.
> 
> Also, the [KEP 20190129-hugepages](https://github.com/kubernetes/enhancements/blob/master/keps/sig-node/20190129-hugepages.md) does not mention that the node should only support a single page size.
> 
> cc @derekwaynecarr, @mattjmcnaughton, @danielqsj
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/kubernetes/kubernetes/issues/77251#issuecomment-523542269

Would it require an api-change? If yes, a good next step might be drafting a
concise KEP w/ the proposal? Iirc, all code which changes the API requires a
KEP.

Additionally if the code is lightweight and you have the capacity, maybe creating a WIP
PR so that there's actual code to discuss in the KEP.

cc @derekwaynecarr to weigh in?

**Comment by andyzheung** [comment]
> With the feedback from this issue and #80452, I think it is time to look at this again. It looks like this is causing numerus issues for the users, and it looks like there are some legitimate use cases for using multiple sizes. The current implementation doesn't even allow reserving all the pre-allocated huge pages for a given size to the system, via the `--kube-reserved` flag, while allowing pods to use another one.
> 
> Adding support for multiple huge page sizes on the node level will be fully backwards compatible, and will only require some small changes in the code. Ill be happy to create a patch if we agree that we should add support for it.
> 
> Also, the [KEP 20190129-hugepages](https://github.com/kubernetes/enhancements/blob/master/keps/sig-node/20190129-hugepages.md) does not mention that the node should only support a single page size.
> 
> cc @derekwaynecarr, @mattjmcnaughton, @danielqsj


Ill be happy to create a patch if we agree that we should add support for it.

===>We also need use multiple hugepagesize, and could you show your patch so that we can refer to?
@odinuge

**Comment by odinuge** [comment]
> We also need use multiple hugepagesize, and could you show your patch so that we can refer to?

If you refer to support on node level, here is an example patch: https://github.com/kubernetes/kubernetes/pull/82820

Doing pod level will be a bit tricker, as we would have to rethink the pod spec defining the `hugetlbfs` mount. All the infrastructure behind that is already implemented with full support, so it should be more or less ok as long as we agree about the mounting format. https://github.com/kubernetes/enhancements/pull/1199 will add container level isolation. That will also make the podspec a bit more difficult with support for multi pages, although that has to be sorted out when adding container level isolation.

**Comment by cheng1li** [comment]
@odinuge Thanks for your patch. Seem the patch is to remove the multi-size check. But considering the [discuss](https://github.com/kubernetes/community/pull/837/files#r133337110) in the proposal, not sure if this brings new issue?

**Comment by bg-chun** [comment]
Hi guys. @odinuge @cheng1li 
Support muti size hugepages, it is an interesting topic.
Now, I'm writing a new commit to propose to extend the CRI message [`LinuxContainerResources`](https://github.com/kubernetes/cri-api/blob/24ae4d4e8b036b885ee1f4930ec2b173eabb28e7/pkg/apis/runtime/v1alpha2/api.proto#L531) to specify hugepages.

The [runime-spec](https://github.com/opencontainers/runtime-spec/blob/master/config-linux.md#huge-page-limits) says `hugepageLimits` as an array of objects, and each object(entry) has `pageSize` and `limit` so that I am going to respect it.
The example that runime-spec says is below.
```
    "hugepageLimits": [
        {
            "pageSize": "2MB",
            "limit": 209715200
        },
        {
            "pageSize": "64KB",
            "limit": 1000000
        }
   ]
```
My idea to extend CRI messge to specify hugepages is below.
Would it be okay for you guys?

```
message LinuxContainerResources {
    ...
    //  this is new field for huge pages
    hugepageLimits huge_pages = 8;
}

message hugepageLimits
{
    // to allow specifying multi sizeof huge pages
    repeated hugepageLimit = 1;
}

message hugepageLimit
{
    // hugepage size The value has the format <size><unit-prefix>B (64KB, 2MB, 1GB),
    string pageSize = 1;
    // limit in bytes of hugepagesize HugeTLB usage
    uint64 pageSize = 2;
}
```

**Comment by andyzheung** [comment]
I have read the patch，but it seems that pod is restricted by only one hugepage type in  empty_dir.go.

// getPageSizeMountOptionFromPod retrieves pageSize mount option from Pod's resources
// and validates pageSize options in all containers of given Pod.
func getPageSizeMountOptionFromPod(pod *v1.Pod) (string, error) {
	pageSizeFound := false
	pageSize := resource.Quantity{}
	// In some rare cases init containers can also consume Huge pages.
	containers := append(pod.Spec.Containers, pod.Spec.InitContainers...)
	for _, container := range containers {
		// We can take request because limit and requests must match.
		for requestName := range container.Resources.Requests {
			if v1helper.IsHugePageResourceName(requestName) {
				currentPageSize, err := v1helper.HugePageSizeFromResourceName(requestName)
				if err != nil {
					return "", err
				}
				// PageSize for all volumes in a POD are equal, except for the first one discovered.
				if pageSizeFound && pageSize.Cmp(currentPageSize) != 0 {
					return "", fmt.Errorf("multiple pageSizes for huge pages in a single PodSpec")
				}
				pageSize = currentPageSize
				pageSizeFound = true
			}
		}
	}

	if !pageSizeFound {
		return "", fmt.Errorf("hugePages storage requested, but there is no resource request for huge pages")
	}

	return fmt.Sprintf("%s=%s", hugePagesPageSizeMountOption, pageSize.String()), nil

}

You only remove the validation on the node level?
@odinuge

**Comment by andyzheung** [comment]
I have read the patch，but it seems that pod is restricted by only one hugepage type in empty_dir.go.

`
// getPageSizeMountOptionFromPod retrieves pageSize mount option from Pod's resources
// and validates pageSize options in all containers of given Pod.
func getPageSizeMountOptionFromPod(pod *v1.Pod) (string, error) {
pageSizeFound := false
pageSize := resource.Quantity{}
// In some rare cases init containers can also consume Huge pages.
containers := append(pod.Spec.Containers, pod.Spec.InitContainers...)
for _, container := range containers {
// We can take request because limit and requests must match.
for requestName := range container.Resources.Requests {
if v1helper.IsHugePageResourceName(requestName) {
currentPageSize, err := v1helper.HugePageSizeFromResourceName(requestName)
if err != nil {
return "", err
}
// PageSize for all volumes in a POD are equal, except for the first one discovered.
if pageSizeFound && pageSize.Cmp(currentPageSize) != 0 {
return "", fmt.Errorf("multiple pageSizes for huge pages in a single PodSpec")
}
pageSize = currentPageSize
pageSizeFound = true
}
}
}

if !pageSizeFound {
	return "", fmt.Errorf("hugePages storage requested, but there is no resource request for huge pages")
}

return fmt.Sprintf("%s=%s", hugePagesPageSizeMountOption, pageSize.String()), nil
}

`
You only remove the validation on the node level?
@odinuge

**Comment by odinuge** [comment]
> @cheng1li: Thanks for your patch. Seem the patch is to remove the multi-size check. But considering the discuss in the proposal, not sure if this brings new issue?

It should work as is, since all the infrastructure behind the scenes supports multiple page sizes on node level. We should add a proper e2e test tho, but it looks like cos on gce only support `2MiB` huge pages.

> @bg-chun My idea to extend CRI messge to specify hugepages is below.
> Would it be okay for you guys?

That looks like the correct approach! Thanks for the work you are doing on the topic!

Not that into protobufs, but is there a reason to not use this instead (or are they equal in practice?):

```protobuf
message LinuxContainerResources {
    ...
    //  this is new field for huge pages
    repeated hugepageLimit hugepages_limit = 8;
}

message hugepageLimit {
    // hugepage size The value has the format <size><unit-prefix>B (64KB, 2MB, 1GB),
    string pageSize = 1;
    // limit in bytes of hugepagesize HugeTLB usage
    uint64 limit = 2;
}
```

> @andyzheung: You only remove the validation on the node level?

Yes, #82820 only affects node level.

> @andyzheung: I have read the patch，but it seems that pod is restricted by only one hugepage type in empty_dir.go.

Yes, the only technical problem is how to deal with it in `emptyDir`. Should we add a new attr called something like `hugePageSize` in `emptyDir`, or maybe add one mount type per huge page size? I am not sure what the best approach is. The rest should be quite easy to implement I think.

I am willing to write a KEP and implement it, but awaiting some more feedback from sig-node before doing so. :smile:

**Comment by bart0sh** [comment]
+1 for enabling multi size hugepages at both node and pod level. Enabling this on the node level looks like a good step in the right direction to me. This would make it possible to run workflows that require different hugepage sizes on the same node. It would also make load balancing more flexible and efficient.

Should we discuss this in more details on the next signode meeting?

**Comment by satishsept7** [comment]
I am facing issue with kubernet installation on node where 2Mi and 1Gi both size huge page exist.
GitVersion:"v1.18.2"
Could you please let me know,Which version supports multiple size huge Page?

**Comment by odinuge** [comment]
Hi @satishsept7,

This will start working properly in v0.19.0, ref. https://github.com/kubernetes/kubernetes/pull/89252. :smile:
