### ISSUE TITLE
Allow jobs to be rerun

### ISSUE THREAD

**Issue by mcandre** [kubernetes/kubernetes#77396]
**What would you like to be added**:

The ability to instruct Kubernetes to execute a job again, after it has already run once.

**Why is this needed**:

Kubernetes has scheduled jobs, and Kubernetes has the ability to delete and create jobs, but no way to trigger an existing job to run again. This forces users into a more awkward workflow than necessary, for jobs expected to be triggered at intermittent intervals.

**Comment by sftim** [comment]
@mcandre: If there were a contributed [plugin](https://kubernetes.io/docs/tasks/extend-kubectl/kubectl-plugins/) for `kubectl` that let you retrigger a job, would that count as a fix?

**Comment by kow3ns** [comment]
We are unlikely to change the v1 Jobs API in order to support this. You can always copy a complete job to create a new one. You can always use a plugin in kubectl as suggested above.

**Comment by kow3ns** [comment]
Another option would be to look at the kubectl restart command.

**Comment by mattfarina** [comment]
@mcandre an option is to write your own tooling that:

1. Gets the job you want to rerun and then...
2. Creates a new job based on the completed one

**Comment by confiq** [comment]
yes, we know that we can delete and create a new job. However, if we want k8s to be perfect, maybe it would be cool to have an API for rerun the jobs...

**Comment by oblogic7** [comment]
I think that some mechanism for reusing jobs would be very beneficial.  I have a use case where I need to execute a job each time a specific pipeline is executed.  Currently, the spec for this job must be customized for each environment since config maps and other dependent resources are changed by kustomize prefixing.  The job config cannot be included with kustomized configuration because I need it to run separately and before any other changes are applied to the cluster.

Similar to how cron jobs work, it would be nice to have some kind of job type that can be run repeatedly via manual triggering.
