### ISSUE TITLE
Apply managedFields conversion only understands served types

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#77519]
Found by failing TestApplyConvertsManagedFieldsVersion test in https://github.com/kubernetes/kubernetes/pull/70672 (https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/70672/pull-kubernetes-integration/1125470649859444738/)

It seems that conversion depends on schema info that is collected from *served* API versions only. However, managedFields stores data in etcd from REST versions served in previous releases which may no longer be served. 

That means that we have to be able to deal with managedFields persisted via API calls to versions that are no longer served, but which we still have and understand conversions for.

/cc @jennybuckley @apelisse 
/sig api-machinery
/wg apply
/priority important-soon

**Comment by jennybuckley** [comment]
This may be fixed in a more recent version of structured-merge-diff. I'll look into it

**Comment by jennybuckley** [comment]
At one point we were using the types registered to the scheme to generate the openAPI definitions used by apply, but we switched to using the installed endpoints instead, because it was less invasive (We needed to expose which types are convertible to which other types, and also a way to skip generating openAPI for internal types). We might want to revisit the first approach, given this use case.
