### ISSUE TITLE
Pod logs: long lines are corrupted when using timestamps=true

### ISSUE THREAD

**Issue by aermakov-zalando** [kubernetes/kubernetes#77603]
**What happened**:

Docker has a hardcoded 16K limit on log line length, which splits lines longer than that into multiple messages in the log file. `ReadLogs` in [logs.go](https://github.com/kubernetes/kubernetes/blob/255a73ffc64d1c4e0f9a378ebf8d0005edfe6962/pkg/kubelet/kuberuntime/logs/logs.go), however, doesn't account for this when `timestamps` is set to `true` and prints the timestamp in front of every entry in the log file instead of every logical line. This leads to random timestamps appearing in the middle of log lines, potentially breaking the applications that parse these logs.

**What you expected to happen**:

`ReadLogs` inserts timestamps once per logical line, so original log data is preserved. Alternatively, allow `/logs` API to request the logs in a sane format like JSON, which would allow merging the lines back and combining them with the timestamps more intelligently on the application side.

**How to reproduce it (as minimally and precisely as possible)**:

* Create `foo.yaml`:

      apiVersion: v1
      kind: Pod
      metadata:
        name: log-lines
      spec:
        containers:
        - name: main
          image: busybox
          command: ['sh', '-c', 'while sleep 1; do echo -n ___; for i in $(seq 1 18000); do echo -n A; done; echo ___; done']

 * Start the pod with `kubectl apply -f foo.yaml`
 * Fetch the logs with `kubectl logs log-lines --timestamps`, or using the API (`curl https://…/api/v1/namespaces/default/pods/log-lines/log?timestamps=true&container=main`)
 * Observe random timestamps inserted in the middle of the log lines.

**Environment**:
- Kubernetes version (use `kubectl version`):
```Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-19T22:12:47Z", GoVersion:"go1.12.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by aermakov-zalando** [comment]
@kubernetes/sig-node-bugs

**Comment by YoubingLi** [comment]
@aermakov-zalando 
    I will work on it.

/sig cli
/remove-sig node

**Comment by aermakov-zalando** [comment]
The logs are being corrupted by the API endpoint in kubelet, so shouldn't it be in scope of SIG node?

**Comment by YoubingLi** [comment]
@aermakov-zalando 

    The log is not corrupted by k8s.

    The same log could be got using "docker container logs -t CONTAINER_ID"

**Comment by aermakov-zalando** [comment]
@YoubingLi kubelet doesn't rely on Docker when reading logs, it reads the files itself (see the `ReadLogs` code linked in the issue). I don't think Docker would change the forced line splitting (see https://github.com/moby/moby/issues/34855 for example), so this should be fixed in Kubernetes.

**Comment by YoubingLi** [comment]
@aermakov-zalando 

   Your are right and kubelet read log file from host such as 
         /var/log/pods/pods/NAMESPACE_POD-NAME_xxx/....(JSON format)

  I will post a PR for it.

/remove-sig cli
/sig node

**Comment by astefanutti** [comment]
I also face this issue on OpenShift 4, that uses CRI-O as container runtime.

@aermakov-zalando, would you mind updating the title and remove the "_when using Docker_" part, so that it's clear it happens also for other runtimes?

**Comment by SergeyKanzhelev** [comment]
I saw the attempt fixing this https://github.com/kubernetes/kubernetes/pull/77822 but it was scary (echo this comment: https://github.com/moby/moby/issues/34855#issuecomment-384759118). I suggested a way it may be improved. Also the proposed fix didn't introduce any e2e tests to validate that runtime behavior is not changed and runtimes keep the no-newline-on-splitted-log logic.

@YoubingLi are you or anybody on this thread are still interested to work on this? Please re-open if so. Meanwhile closing this ahead of bot doing it because the inactivity.

/close

**Comment by rphillips** [comment]
I received a bug report about this issue. The root cause is that the buffer reads up to a new line and the buffer may become full (4096 bytes) thus printing the timestamp and the partial line. We will need to refactor the ReadLogs function to allow for a partial line read.

https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kuberuntime/logs/logs.go#L325
