### ISSUE TITLE
NodeLifecycleController is overloading kube-apiserver 

### ISSUE THREAD

**Issue by mborsz** [kubernetes/kubernetes#77733]
**What happened**:

The current implementation of NodeLifecycleController generates "GET /api/v1/pods?fieldSelector=spec.nodeName=X" request for each node becoming unavailable. This request can be expensive when there is a high number of pods (O(100k)) running in the cluster.

The problem is that to prepare answer for that request, kube-apiserver needs to fetch all the data from etcd and then filter out almost all of them (only ~100 pods can be running on a single nodes).

In scalability tests we are seeing that killing ~50 nodes in 5000 node cluster is able to overload master in a way that kube-controller-manager/kube-scheduler is not able to renew leader lock due to request timeout.

https://github.com/kubernetes/kubernetes/blame/master/pkg/controller/util/node/controller_utils.go#L125

**What you expected to happen**:

I expected that killing 50 nodes in 5000 won't affect master's performance.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

In my opinion we should consider reimplementing this in some other way that will reduce master load.

Some potential options:
* Migrate to watch interface for pods (likely unfeasible due to freshness requirements)
* Investigate what etcd offers for such requests
* Implement some k8s-level index for spec.nodeName field (e.g. dedicated objects that for each node keeps a list of pods running on that node).

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

/cc @wojtek-t @krzysied 
/sig scalability

**Comment by wojtek-t** [comment]
I've been discussing it with @jpbetz some time ago, and what the way that we're thinking about is:
- use "etcd progress notifications" to ensure that watchcache resource version is being updated frequently even when no objects of a given type are actually changing
- introduce an index in watchcache to handle "spec.nodeName" requests more efficiently
- introduce the following patter for serving "LIST requests"
  (a) list from etcd with limit=0, just to get resource version
  (b) wait until watchcache becomes at least at the returned RV (with some relatively small timeout, like 0.5s or maybe even less?)
  (c) list from watchcache if it become fresh enough, otherwise fallback to etcd

**Comment by lavalamp** [comment]
Why doesn't the controller watch all pods and filter locally, like all other controllers?

**Comment by lavalamp** [comment]
It needs to do that for correctness, anyway. (Imagine a new pod somehow getting assigned to a node that's already gone unavailable.)

**Comment by wojtek-t** [comment]
Yeah - exactly. It's for correctness reasons.

**Comment by lavalamp** [comment]
@mborsz Can we change the OP to be a bug report about the controller rather than a bug report about apiserver? And/or file a new issue. We won't be changing apiserver to fix this.

**Comment by wojtek-t** [comment]
@lavalamp - I actually think we *will* be changing apiserver:
https://github.com/kubernetes/kubernetes/issues/77733#issuecomment-491691206
[Something I was already briefly discussing with @jpbetz ]

**Comment by lavalamp** [comment]
> use "etcd progress notifications" to ensure that watchcache resource version is being updated frequently even when no objects of a given type are actually changing

Bookmarks are great and already in progress, no? They don't need to be part of this issue.

> introduce an index in watchcache to handle "spec.nodeName" requests more efficiently

Please don't do this. I don't want to set the precedent that we're willing to add indexes in apiserver unless we're prepared to actually do a good job of that, and I don't think we are. @deads2k 

> introduce the following patter for serving "LIST requests" ...

I would also vote against this. There is no reason for this controller to be issuing list requests.

**Comment by wojtek-t** [comment]
> Bookmarks are great and already in progress, no? They don't need to be part of this issue.

This is something different - this is about "notify progress from etcd".

> Please don't do this. I don't want to set the precedent that we're willing to add indexes in apiserver unless we're prepared to actually do a good job of that, and I don't think we are. @deads2k

We're kind of doing something very similar already. We have this "trigger function" in watchcache already. Introducing predefined indexes is kind of the same thing for me [i kind of see that as "introducing corresponding indexes to trigger functions that we already have].

> There is no reason for this controller to be issuing list requests.

I don't understand this one - there is no other way we can do that.
BTW - this pattern would solve other issues to - i.e. kubelets are listing pods from their node on startup as an example [this is not controller-specific solution]

**Comment by lavalamp** [comment]
Why is a list from apiserver necessary? Why is a local list from cache not sufficient?

**Comment by lavalamp** [comment]
Link to the trigger function?

**Comment by deads2k** [comment]
> introduce an index in watchcache to handle "spec.nodeName" requests more efficiently

> Please don't do this. I don't want to set the precedent that we're willing to add indexes in apiserver unless we're prepared to actually do a good job of that, and I don't think we are. @deads2k

I agree on all counts. I don't want the watch cache to drift any more from backing storage and one off indexes or list implementations will complicate future choices.

If the controller can already see all pods, then I think working through a Lister makes the most sense.  See how we build the store,indexer,lister client-side.

**Comment by wojtek-t** [comment]
> Link to the trigger function?

@lavalamp 
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/storage/cacher/cacher.go#L253
[BTW, it was you who was approving that years ago...]

> Why is a list from apiserver necessary? Why is a local list from cache not sufficient?

We've had that discussing like 3 years ago or so. And the argument was that local cache may be lagging, and we want to really evict *all* pods that were scheduled on that node.
From purely scalability perspective I would obviously support listing from local cache, but here we have clear correctness issue if we do that. We're risking that due to staleness of the cache, we will miss some pod that was already scheduled on that node, and we will never evict it in the future, which is pretty bad.

> I agree on all counts. I don't want the watch cache to drift any more from backing storage and one off indexes or list implementations will complicate future choices.

I think I don't buy this argument. The watchcache is already crucial for some resources (like pods or nodes) and there is no way we can remove it without completely breaking scalability. So I don't think we're talking about future choices here.

I actually think that such indexes doesn't really change almost anything from apimachinery perspective, and they would help us a lot. The main arguments are:

- we already have the triggerFunc I mentioned above. The purpose for it is to not go over all watchers when a new event is coming, but somehow be able to efficiently discard majority of them in one shot.
[The example is for pods we have triggerFunc that is checking `pod.spec.nodeName`, and each watcher is assigned to be either watcher a specific value of that field or any value - given that majority of watchers are from kubelets watching specific fields, this feature is crucial.]
It's actually important to say, that if we would remove this triggerFunc, there is no way we would scale.

- the index would be complementary to it - we will be just using the same triggerFunc (i.e. no new configuration at all), but instead of having `cache.Store`, we would have `cache.Indexer` with an index build from the triggerFunc:
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/storage/cacher/watch_cache.go#L115
And on List() requests, we would be checking if the selector is "matching index": https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/storage/selection_predicate.go#L131 and if so using ListByIndex instead of List.

- the changes are quite minimal, the interface doesn't change, and we have clear performance gains

- and as I mentioned above, it's not addressing only this specific issue. As an example, all Kubelets are listing pods from their node on start - this would visibly help this case too.

- finally, I obviously agree that we don't want to allow creating custom indexes. And in my opinion this is what would make the potencial future choices harder.

**Comment by lavalamp** [comment]
>> Why is a list from apiserver necessary? Why is a local list from cache not sufficient?

> We've had that discussing like 3 years ago or so. And the argument was that local cache may be lagging, and we want to really evict all pods that were scheduled on that node.

Like I tried to say earlier, for correctness, it **cannot** do this with only a list (no matter the source of the list!), because it needs to respond to pods added to the node **after** the node goes into this state. Modifying the nodes based on the list needs to use a precondition anyway, so it doesn't matter if the list is stale.

Still reading the rest.

**Comment by lavalamp** [comment]
> And the argument was that local cache may be lagging, and we want to really evict all pods that were scheduled on that node.

One more thing--the watch cache may also be lagging. You can't really argue against a local cache as compared to the watch cache, especially when the controller already has the local cache available to it.

> As an example, all Kubelets are listing pods from their node on start - this would visibly help this case too.

Kubelets are a legitimate thing to have this discussion over, as we don't really even want them to see pods not assigned to them, at least not in an ideal world. I'm reluctant to get this property by modifying the watch cache, because it smells like something that should be guaranteed by the auth system.

> notify progress from etcd

This sounds great, and also seems like a separate issue from this topic.

**Comment by wojtek-t** [comment]
> Like I tried to say earlier, for correctness, it cannot do this with only a list (no matter the source of the list!), because it needs to respond to pods added to the node after the node goes into this state. Modifying the nodes based on the list needs to use a precondition anyway, so it doesn't matter if the list is stale.

I think we actually can - everything that will be scheduled on the node later, will be rejected by Kubelet itself, I think. No?

> One more thing--the watch cache may also be lagging. You can't really argue against a local cache as compared to the watch cache, especially when the controller already has the local cache available to it.

I think there may be misunderstanding - I don't want to *simply list from watchcache*.
What I want is to:
- list from etcd with limit=0 to get current etcd RV
- wait until watchcache caught up to that RV (with timeout, and fallback to etcd)
- and list from cache only when it reached particular RV
So it will be at least as fresh as list from etcd...

> Kubelets are a legitimate thing to have this discussion over, as we don't really even want them to see pods not assigned to them, at least not in an ideal world. I'm reluctant to get this property by modifying the watch cache, because it smells like something that should be guaranteed by the auth system.

I think I'm not fully following this - even if I conceptually agree we are years from it (etcd doesn't support auth per key or sth like that, it's probably even more becase it depends on the value). I don't think it will happen before 2022 :) And this probably is hitting us now - we need some solution in the next release timeline or so.

**Comment by lavalamp** [comment]
> I think we actually can - everything that will be scheduled on the node later, will be rejected by Kubelet itself, I think. No?

The whole point of this condition is that the node is unavailable, I thought?

**Comment by lavalamp** [comment]
> [list catchup desc]

I think that's unnecessary; both controllers and kubelets can watch; I think watching is necessary for correctness anyway. Controllers need to handle all possible states of the world, it's a dangerous assumption that the entire rest of the system will never ever e.g. make a late pod assignment.

> etcd doesn't support auth per key or sth like that, it's probably even more becase it depends on the value

I didn't have a solution in mind, definitely not one that involved driving the computation into etcd rather than e.g. adjusting how we store things or apiserver-based computation.

**Comment by wojtek-t** [comment]
> I think that's unnecessary; both controllers and kubelets can watch; I think watching is necessary for correctness anyway.

OK - let me clarify one thing. I agree watching is necessary for correctness.
But at least on startup, listing is necessary to set starting point for watching.
And listing currently is *unnecessarily* expensive, in large clusters by orders of magnitude.
We should fix that independently from what we will do with the controllers.

**Comment by lavalamp** [comment]
> But at least on startup, listing is necessary to set starting point for watching.
> And listing currently is unnecessarily expensive, in large clusters by orders of magnitude.

Only for kubelet. Controllers actually need to (and already do) list everything anyway.

**Comment by wojtek-t** [comment]
> Only for kubelet. Controllers actually need to (and already do) list everything anyway.

Modulo this node controller manager, but yes I agree.

But the important point is that with a shared cache, we have O(1) list on initialization from controller. And in 5k-node cluster, you have 5k kubelets...

**Comment by hormes** [comment]
In 5k-node cluster list pod by nodeName will take 0.5s without nodeName index, we have to do that 
from our experience.

**Comment by lavalamp** [comment]
I agree that this is a problem for kubelets (and similar things). But this issue is specifically about the controller.

**Comment by mborsz** [comment]
I was thinking about some potential solutions here and this one seems to be interesting to me:

1. kube-controller-manager keeps in memory list of all NotReady nodes
2. kube-controller-manager keeps in memory watch-based list of pods (or simply uses shared listeners for this)
3. If any node becomes NotReady, adds to the NotReady nodes and evicts all pods using cache.
4. If there is any change to pod list in 2., we check whether this pod shouldn't be evicted based on NotReady nodes.

For performance this is good as we don't trigger any expensive per-node list.
For correctness this is more complex question, but I think this solution should be "eventually consistent" assuming that watch will be progressing (I think it should be safe to assume this, no?): if in "3." we don't catch pod change due to watch cache staleness, we should fix this in 4. when the watch cache reaches that change.

WDYT?

**Comment by wojtek-t** [comment]
I think it's definitely worth exploring further. We're kind of "eventually correct" already, because there can be significant time before taint-manager process the change in node and when it is processed (it's triggered by watch, and actually queued in the controller).
I was thinking about that in the past and thought there would be a race, but now I can't figure out what the race could be.

So I actually would support that if we're sure that there won't be races (i.e. when we have implementation of it).

**Comment by jfbai** [comment]
@wojtek-t @mborsz Hi, is there any progress on this issue? I observed the same problem in my testing cluster with thousands of nodes when doing scalability test. And @mborsz's idea looks reasonable, so, I'd like to implement it and run on my testing cluster, if no side effect occurs, I will run it on production.

Do you have any suggestions? Thanks a lot.

**Comment by wojtek-t** [comment]
Yes - it's happening - I hope it will be merged within the next couple days:
https://github.com/kubernetes/kubernetes/pull/81167

**Comment by jfbai** [comment]
> Yes - it's happening - I hope it will be merged within the next couple days:
> #81167

Thanks for this info, it would be a great improvement in a large scale cluster.

**Comment by tedyu** [comment]
I was the discussion.
Here is the code which used to be cacher.go#L253 :
```
	// indexedTrigger is used for optimizing amount of watchers that needs to process
	// an incoming event.
	indexedTrigger *indexedTriggerFunc
```
FYI
