### ISSUE TITLE
Stop timeout isn't respected at shutdown/reboot

### ISSUE THREAD

**Issue by mrunalp** [kubernetes/kubernetes#77873]
**What happened**:
Containers are getting terminated by systemd without respecting the `terminationGracePeriodSeconds` set in the pod yaml on reboot or shutdown of a node.

**What you expected to happen**:
`terminationGracePeriodSeconds` is respected by systemd when using systemd as the cgroup manager. 

**How to reproduce it (as minimally and precisely as possible)**:
1. Use systemd as the cgroup manager in your container runtime.
1. Create a pod yaml with `terminationGracePeriodSeconds` set to `120` seconds.
1. Reboot the node.
1. You will notice that the containers get SIGTERM, followed by systemd default stop timeout (typically 90 seconds) and then they are SIGKILLed.

**Anything else we need to know?**:
This can be fixed by passing the stop timeout to the containers as part of the CreateContainer CRI API. This will allow the container runtimes to set the systemd property for the scope to override the default stop timeout to the value set through `terminationGracePeriodSeconds`.
This needs changes across the stack as runc doesn't currently provide a way to set the TimeoutStopUSec for the systemd scope created for a container.
The behavior with `cgroupfs` cgroup manager will need further investigation.

**Environment**:
- Kubernetes version (use `kubectl version`): All versions.

**Comment by mrunalp** [comment]
cc: @derekwaynecarr @dchen1107

**Comment by derekwaynecarr** [comment]
while this impacts all pods, it is particularly an issue with static pods or daemon set backed pods which typically are not drained before a maintenance action.

/milestone v1.15

**Comment by yujuhong** [comment]
@derekwaynecarr IIUC, this is a feature request, since kubernetes has never supported this. Is there a reason why this is marked milestone 1.15 when we are already past enhancement freeze and almost reaching code freeze?

**Comment by Random-Liu** [comment]
I'm not sure whether we want the user configured grace period to block node reboot.

If I specify a 10min grace period, will it block the node from reboot for 10min? Is it fair to the other pods?

**Comment by mrunalp** [comment]
We can restrict it similar to how privileged is restricted. This is useful for daemon sets and static pods that are system owned.

**Comment by Random-Liu** [comment]
> We can restrict it similar to how privileged is restricted. This is useful for daemon sets and static pods that are system owned.

If that is the case, it seems that we need to define Kubernetes api for that. Kubelet doesn't know whether a pod belongs to a daemonset or not.

**Comment by soggiest** [comment]
Is this issue release blocking or can we move it to 1.16?

**Comment by liggitt** [comment]
If this is not a regression in 1.15, I'd expect it can be moved

**Comment by josiahbjorgaard** [comment]
Hi all, code freeze for v1.16 is coming up on Aug. 29 (in just 6 days). This issue is set for milestone v1.16, will it be solved by then? It will need to have a PR merged beforehand. If not, we will remove the v1.16 milestone.

**Comment by liggitt** [comment]
I'm not aware of any activity on this issue targeting 1.16

**Comment by dtolmachev** [comment]
@mrunalp 
I've found this issue trying to fix the same problem as it is described in "How to reproduce it" section. 

We run static pod with Docker container. Also we have kubelet and containerd on VM. 

The problem: I want to make graceful shutdown with 60s duration for container. But currently, we have only 10 seconds. That's because Docker receives `SIGTERM` and it is interpreted as [docker stop](https://docs.docker.com/engine/reference/commandline/stop/) with default 10s timeout 
It is possible to set `--stop-timeout` for [docker run](https://docs.docker.com/engine/reference/commandline/run/) but we run container with kubelet and `terminationGracePeriodSeconds` in `pod.yaml` doesn't change the shutdown duration.
The [pull-request](https://github.com/opencontainers/runc/pull/2062) in containerd project is still open. 

Can I help with finishing this PR? What job needs to be done?

Thanks a lot for supporting Kubernetes and containerd!

**Comment by mrunalp** [comment]
Can this be reopened? I am opening a PR to address this.

**Comment by mrunalp** [comment]
@dims Thanks :)
