### ISSUE TITLE
azure: waiting for cluster initialization

### ISSUE THREAD

**Issue by kunchenguid** [kubernetes/kubernetes#7826]
Following the instructions on https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/azure.md, cluster/kube-up.sh creates the VMs but hangs forever at "waiting for cluster initialization". 

I can see the master and minion VMs are all up and running, but it looks like kubernetes cannot reach the APIs. Is this a known issue? What's the best way to investigate?

**Comment by kunchenguid** [comment]
looks like the same issue with #6966.

**Comment by kunchenguid** [comment]
looked further and it seems people are recommending that we provision kube clusters on azure with coreos and weave: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/coreos/azure/README.md

is there any advantage that https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/azure.md does not provide? 

and still I don't see a conclusion on why the default azure cluster setup script is not working.

**Comment by mbforbes** [comment]
unsure who the azure goto is; @brendandburns ?

**Comment by mbforbes** [comment]
+cc @colemickens @jeffmendoza @ahmetalpbalkan @bgrant0607

**Comment by ahmetalpbalkan** [comment]
This is currently being investigated at Microsoft Azure side. I believe we will have a fix soon.

**Comment by kunchenguid** [comment]
@ahmetalpbalkan good to know! once Azure fixed this, do we get full networking capabilities with the default azure setup?

**Comment by cusspvz** [comment]
+1, couldn't finish cluster setup...

**Comment by cusspvz** [comment]
And my azure's trial subscription is ending up tomorrow...

**Comment by cusspvz** [comment]
`user:pass:host:443/api/v1beta1/pods` has `502 Bad Gateway` response from `nginx`

**Comment by errordeveloper** [comment]
> is there any advantage that https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/azure.md does not provide?

The whole approach is different entirely, in many ways.

**Comment by srakesh28** [comment]
+1 I have same issue

**Comment by cusspvz** [comment]
I'm currently working on a [coreos cluster management](https://github.com/findhit/coreos) module (and cli) that supports multiple providers (I did start with azure because of this issue). Already got kubernetes working by deploying manually the services into the cluster.

**Comment by errordeveloper** [comment]
@cusspvz that's very very interesting, I wonder whether you have consider using a declarative tool, e.g. Azure Resource Manager or Terraform for this?

**Comment by cusspvz** [comment]
@errordeveloper didn't knew **Terraform**, looks awesome!

I had some points about using a third-party cloud provisioning tool so we didn't had to write code for each provider, but happens that every provider has their differences such as how do you get latest `stable`, `beta` or `alpha` image, or how you handle your VM's endpoints. Based on that I have decided to implement their provisioning differences on their constructors.

Our main goal with [our coreos module](https://github.com/findhit/coreos) wasn't only the CLI but having the ability scaling the cluster horizontally with multiple provider-accounts with another module, thats why you can find `persistent` option on each node. :)

My milestone for today is to code ssh communication where you can deploy and manage services to fleetctl without having to handle with identity files and such things. I had a lot of troubles with it using scripts, had to bind ports over ssh to allow dynamic identities handling (just because fleetctl doesn't have identity options when working over ssh tunnels... :/ )

**Comment by cusspvz** [comment]
@errordeveloper you can already do some things with [our coreos module](https://github.com/findhit/coreos).

https://github.com/findhit/coreos/blob/master/docs/cli/README.md

Today i will bring up `deploy` methods so we can easily deploy kubernetes or other services into the cluster.

**Comment by cmdrkeene** [comment]
Bump. Any movement on this?

**Comment by camechis** [comment]
Still no word? Or is the coreos method the way we should be doing things.

**Comment by coreyperkins** [comment]
I'm getting the 502 Bad Gateway with the default Azure setup. It also stuck on cluster initialization and never finished. I'm going to get into the logs next and see what I can report back.

**Comment by kgoerlitz** [comment]
I am also having this problem.  The 502 Bad Gateway error appears to be a bad configuration of Nginx on Ubuntu. In addition, I see errors like:
error: couldn't read version from server: Get https://xxxxx.cloudapp.net/api: x509: certificate is valid for .cloudapp.net, not xxxxx.cloudapp.net
This looks like the salt scripts did not successfully get the cloud service name.

On the master node, I see /var/log/kube-addons.log file filling up with the following error:
error: couldn't read version from server: Get http://localhost:8080/api: dial tcp 127.0.0.1:8080: connection refused.

**Comment by ahmetalpbalkan** [comment]
cc: @snesha

**Comment by ahmetalpbalkan** [comment]
PR #12097 should be fixing this issue.

**Comment by coreyperkins** [comment]
I integrated the changes from PR #12097 into 1.0.1 release in a local repo just a few minutes ago, the problem still exists.

**Comment by kgoerlitz** [comment]
Is anyone working on the Azure cluster configuration?  If not, then maybe it should be removed from the kubernetes distribution.

**Comment by coreyperkins** [comment]
kgoerlitz, I agree. I've been waiting for a response for a couple of weeks, but nothing yet. Hopefully it'll get addressed soon...

This is an exciting Kubernetes addition, I hope it doesn't get dropped or ignored!

**Comment by thockin** [comment]
Summoning everyone I can:

@ahmetalpbalkan @jeffmendoza @errordeveloper @squillace @chanezon @crossorigin 

If we can't get a stable Azure experience we'll have to take Azure off the list of platforms.

**Comment by mikedanese** [comment]
@errordeveloper @squillace @chanezon @crossorigin work on coreos/azure which is stable and maintained. This issue is regarding the azure/ubuntu/saltstack setup which has no community maintainers according to this doc. https://github.com/kubernetes/kubernetes/tree/master/docs/getting-started-guides

**Comment by mbforbes** [comment]
@mikedanese ah thanks for the summary. Given that coreos is stable and maintained on Azure, but Ubuntu on Azure has issues, maybe we should have our top-level getting started guide for Azure point to the setup that is stable and maintained? 

Otherwise it seems that anyone trying out the project will go to the Azure guide and get stuck.

**Comment by coreyperkins** [comment]
Not to confuse things, the coreos example does seem stable, but I have reported a problem here (https://github.com/kubernetes/kubernetes/issues/12224) for anyone interested.

**Comment by kgoerlitz** [comment]
Yes, the coreos/azure setup works, but if the azure/ubuntu/saltstack setup worked, it would be a cleaner deployment.  (It is easier to configure (i.e. control over cloud service, virtual network, and hostnames), uses the standard cluster setup/tear-down scrpts, etcd on master instead of requiring addiotnal VMs, heapster included by default, ...).

**Comment by camechis** [comment]
Agree with the previous comment.

**Comment by johngossman** [comment]
We are working on updating this for Ubuntu. https://github.com/kubernetes/kubernetes/pull/12097 was a fix for the earlier issue, but a change to cert generation broke that before it was even merged. Fix incoming. But coreos works in the meantime.

**Comment by kgoerlitz** [comment]
On the azure/ubuntu/saltstack cluster setup, it would be better if it did not configure the cloud service to expose the nginx proxy for kuba api on port 443 since an application deployed in the cluster may need to be exposed on port 443.

**Comment by jiasir** [comment]
I have the same issue:
```
Waiting for cluster initialization.

  This will continually check to see if the API for kubernetes is reachable.
  This might loop forever if there was some uncaught error during start
  up.
```
The API can not  be reached.

**Comment by bbirand** [comment]
Thanks for looking into this, I am having the same issue.. :+1: 

Maybe it might be interesting to have a sort of Jenkins test that regularly tries these kube-up scripts to make sure they return on time or so?

**Comment by freedev** [comment]
+1 I have same issue

**Comment by danielschonfeld** [comment]
Just ran into this myself, being a new user to Azure.

It appears that when SSHed into kube-master it has kube-master-addons.sh and kube-addons.sh scripts stuck in their respective loops.  With kube-master-addons waiting on docker to be installed.

It appears mostly as if salt hasn't done any of it's magic or not called to run.

I have noticed that in salt-master.sh the command `install-salt --master` doesn't exist, but `salt-call state.highstate` does.  With the latter stated, I'm not sure why it couldn't complete its duties properly.

**Comment by Snesha** [comment]
There are a number of issues. I submitted a patch that fixed some of them and have more fixes that I'm working through for azure. The reason why the setup doesnt complete is because the salt scripts are missing the azure cloud in a number of places. Additionally there are certificate issues and openvpn hasn't been configured right with the cert changes that went in. Right now the layer I'm peeling is to with the manifests not being placed in /etc/kubernetes. Essentially with the underlying setup scripts changing for k8s (unification of setup), setup on azure was broken in multiple places.
