### ISSUE TITLE
make kubectl delete pod busybox -o json work

### ISSUE THREAD

**Issue by grosser** [kubernetes/kubernetes#78343]
I want to atomically delete an object and know it's last configuration.
`DELETE api/v1/pod/NAME` already returns the json, so please allow passing it back to the user.

@kubernetes/sig-cli-feature-requests

**Comment by liggitt** [comment]
Not all delete methods return object json, so kubectl could not implement this consistently

**Comment by grosser** [comment]
Which ones don't ?
I'd still prefer if it was possible for the ones where it returns Json.

**Comment by liggitt** [comment]
> Which ones don't ?

these don't:
* APIService
* AuditSink
* CertificateSigningRequest
* ClusterRole
* ClusterRoleBinding
* ConfigMap
* ControllerRevision
* CronJob
* CustomResourceDefinition (and custom resources)
* DaemonSet
* Deployment
* Endpoint
* Event
* HorizontalPodAutoscaler
* Ingress
* Job
* Lease
* LimitRange
* MutatingWebhookConfiguration
* NetworkPolicy
* Node
* PodDisruptionBudget
* PodPreset
* PriorityClass
* ReplicaSet
* ReplicationController
* Role
* RoleBinding
* RuntimeClass
* Secret
* Service
* StatefulSet
* ValidatingWebhookConfiguration

these do:
* CSIDriver
* CSINode
* Namespace
* PersistentVolume
* PersistentVolumeClaim
* Pod
* PodSecurityPolicy
* ResourceQuota
* ServiceAccount
* StorageClass
* VolumeAttachment

> I'd still prefer if it was possible for the ones where it returns Json.

the wait behavior associated with delete makes it fairly difficult to do... since we can't do it consistently across resources, I'm not hugely in favor of it.

**Comment by grosser** [comment]
oh boy, did not expect it to be that complicated :(
