### ISSUE TITLE
Introduce node cache to aws library

### ISSUE THREAD

**Issue by zhan849** [kubernetes/kubernetes#78409]
**What would you like to be added**:
Add a informer-fed cache for v1.Node to aws.go

**Why is this needed**:
Currently in aws library, we are making a lot of `DescribeInstances()` calls with query filters to cloud provider directly, which is sometimes unnecessary and inefficient. 

One benefit is that in addition to #78140 , which tries to translate instance Name to instance ID and optimized cloud provider calls, an informer-fed cache can further reduce unnecessary GET calls to k8s server.

Node cache can also provider useful information such as current zones in a handy way.

/kind feature
/sig aws
/sig cloud-provider
/sig scalability

/assign zhan849

**Comment by justinsb** [comment]
We discussed in sig-aws and agreed that this is a great goal that we should strive towards.  Not assigning it to a particular milestone as we imagine there will be many smaller PRs towards achieving this.

**Comment by zhan849** [comment]
Update - #78140 added informer-fed node cache and query aws cloud provider by ID if possible. 

`GetCandidateZonesForDynamicVolume()` is another function we need to revise to see if we are able to leverage node cache. The current impl filters out master, which is not something we can leverage node cache, but since other cloud providers don't filter out master node (i.e. gce), if we can do the same, we don't have to query cloud provider for such information.

**Comment by wongma7** [comment]
Most of the work has been done by fixing getInstancesByNodeName and GetCandidateZonesForDynamicVolume https://github.com/kubernetes/kubernetes/pull/78276, thank you.

There is also this minor getInstancesByNodeNames func which is only used in DisksAreAttached https://github.com/kubernetes/kubernetes/blob/5e4abfb94613339d585e5d811e4fcec278ff06dc/staging/src/k8s.io/legacy-cloud-providers/aws/aws.go#L2682 which is called once every minute via VerifyVolumesAreAttached. https://github.com/kubernetes/kubernetes/blob/54c4428eb4e7c99c825e96d2a480ad4e79bc580f/pkg/controller/volume/attachdetach/reconciler/reconciler.go#L134 I think the call can be replaced by getInstancesByIDs, I'll work on a PR.

getInstancesByNodeNames does not seem so bad because it does a DescribeInstances for 150 nodes at a time using some filters. But if these DescribeInstances return some stale data and the data says some volumes are not yet attached when in fact they are, then we will also waste at least one extra DescribeInstance call for each volume that is mistakenly marked detached:
https://github.com/kubernetes/kubernetes/blob/14e5adfc85119b0fca6bed1dabfca8bc94d9f923/pkg/volume/util/operationexecutor/operation_generator.go#L324 
https://github.com/kubernetes/kubernetes/blob/5e4abfb94613339d585e5d811e4fcec278ff06dc/staging/src/k8s.io/legacy-cloud-providers/aws/aws.go#L2244
