### ISSUE TITLE
Clean up ObjectSelector wiring

### ISSUE THREAD

**Issue by caesarxuchao** [kubernetes/kubernetes#78554]
See:
https://github.com/kubernetes/kubernetes/pull/78505#discussion_r289214592
https://github.com/kubernetes/kubernetes/pull/78505#discussion_r289217169

cc @liggitt 
/assign
/sig api-machinery

**Comment by Pothulapati** [comment]
Hello! I'm part of the bug triage team for the 1.16 release cycle and considering this issue is tagged for 1.16, but not updated for a long time, I'd like to check its status. The code freeze is starting on August 29th (about 1.5 weeks from now), which means that there should be a PR ready (and merged) until then.

Do we still target this issue to be fixed for 1.16? If not please re-tag the issue to the planned milestone.

**Comment by ttousai** [comment]
Bug triage for 1.17 here with a gentle reminder that code freeze for this release is on Nov. 18. Is this issue still intended for 1.17?

**Comment by ttousai** [comment]
***Correction:*** Code freeze is on Thursday, November 14.

Sorry for the mix up.

**Comment by ttousai** [comment]
@liggitt any plans for this issue for 1.17?

**Comment by liggitt** [comment]
no

**Comment by tedyu** [comment]
Is this task still needed ?
