### ISSUE TITLE
Make minimal kubelet image

### ISSUE THREAD

**Issue by pmorie** [kubernetes/kubernetes#7855]
Currently the docker image for the kubelet is based on centos.  Instead, we should make a scratch image that just contains the `kubelet` and `nsenter` binaries.  A few things need to be worked out:
1.  cAdvisor has some issues with being built statically after go 1.4 (source, @vmarmol)
2.  Where do we source a statically built nsenter binary?   There's a [well-known docker image that builds a static nsenter](https://github.com/jpetazzo/nsenter), perhaps we could use this.

@dchen1107 Has reported being able to build a static kubelet binary w/o cAdvisor support; hopefully that means there are no issues intrinsic to the kubelet code itself.

See #7805 for some additional discussion.

**Comment by vmarmol** [comment]
I would argue that we should use `busybox` (or something like it) instead of `scratch`. The difference is a few MBs (Just the Kubelet binary is 20MB+ `nsenter` would be a few MBs as well). It solves most of the above issues and gives us access to `sh` and other tools so we can exec into the container and debug.

**Comment by pmorie** [comment]
@vmarmol I think `busybox` is a good idea, with the caveat that the busybox image we use today doesn't have selinux support compiled in, so you cannot `ls -lZ` a file or otherwise work with selinux.  Ideally our busybox binary should be built w/ selinux support.
