### ISSUE TITLE
Bump of cos version results in increased usage of CoreDNS

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#78562]
Forked from https://github.com/kubernetes/kubernetes/issues/76579

COS version was bumped in this PR: https://github.com/kubernetes/kubernetes/pull/75149 and that results in increased Memory usage of CoreDNS.
In the meantime the new CoreDNS version was released which reduced by by 2-3x, so it's no longer that big deal, but we should understand the root cause of that to avoid it in the future.

**Comment by spiffxp** [comment]
/milestone v1.15
Pulling this in ref: https://github.com/kubernetes/kubernetes/pull/78691

**Comment by soggiest** [comment]
Once https://github.com/kubernetes/kubernetes/pull/78851 is merged this should resolve any issues around CoreDNS version.

**Comment by mborsz** [comment]
I made small experiment: reran 330 gce-scale-performance test (330 is first run with upgraded cos and it still uses coredns 1.3.1) with DNS_MEMORY_LIMIT=300Mi to see what is the amount of memory that coredns needs after the regression. The max usage is 180.2Mi (which is higher than default 170Mi limit causing some pods OOMing).

The coredns upgrade to 1.5.0 was reducing the memory usage to values like 60Mi, but we cannot do that due to upgrade issues.

**Comment by chrisohaver** [comment]
Is the memory usage of CoreDNS of 1.3.1 with COS-beta consistently higher in all the scale tests (500, 2k, 5k, etc), or just the 5k test?  Is "330" test 330 nodes?

**Comment by mborsz** [comment]
Sorry, by 330 I meant https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/330/

We have only 100 node tests and 5000 node tests and in 100 node tests I can't see any visible increase and in 5000 node test there was a significant memory increase right after "330" build of ci-kubernetes-e2e-gce-scale-performance.

**Comment by chrisohaver** [comment]
Is there a way to tell in the logs/artifacts of the test you just ran if CoreDNS restarted during the test at all? Not via OOM kills but otherwise exiting and getting re-spawned?

**Comment by soggiest** [comment]
Since #78551 is moved to 1.16 I'll be bumping this milestone as well
/milestone v1.16

**Comment by mborsz** [comment]
> Is there a way to tell in the logs/artifacts of the test you just ran if CoreDNS restarted during the test at all? Not via OOM kills but otherwise exiting and getting re-spawned?

We don't collect coredns logs for periodic tests. I'm rerunning the "330" test, I will collect logs and will post them here.

**Comment by mborsz** [comment]
In my test attempt, e.g. `coredns-5b969f4c88-hlccw` has OOMed:

```
State:          Running
      Started:      Wed, 12 Jun 2019 17:46:13 +0200
    Last State:     Terminated
      Reason:       OOMKilled
      Exit Code:    137
      Started:      Wed, 12 Jun 2019 12:20:05 +0200
      Finished:     Wed, 12 Jun 2019 17:46:11 +0200
    Ready:          True
    Restart Count:  1
```

Logs for previous pod run doesn't contain anything useful:
```
$ kubectl logs -n kube-system coredns-5b969f4c88-hlccw -p      
.:53
2019-06-12T10:20:05.941Z [INFO] CoreDNS-1.3.1
2019-06-12T10:20:05.941Z [INFO] linux/amd64, go1.11.4, 6b56a9c
CoreDNS-1.3.1
linux/amd64, go1.11.4, 6b56a9c
2019-06-12T10:20:05.942Z [INFO] plugin/reload: Running configuration MD5 = 983e0715b6345402acc1b47b2543ece7
```
Full "kubectl describe pods" and kubelet logs are available here:
https://gist.github.com/mborsz/3020c369d4ca38803307b50539b1695d

**Comment by chrisohaver** [comment]
> In my test attempt, e.g. coredns-5b969f4c88-hlccw has OOMed:

That was _with_ the with DNS_MEMORY_LIMIT=300Mi memory bump?

**Comment by mborsz** [comment]
With default DNS_MEMORY_LIMIT=170Mi

**Comment by chrisohaver** [comment]
OK, I was hoping to see if the coredns was restarted at all during the DNS_MEMORY_LIMIT=300Mi test.

The reason: If a CoreDNS Pod was to restart during the test for any non-OOM reason, then this could start a OOM kill cycle. When CoreDNS initializes, the k8s api client will spike memory when syncing a large endpoints/services lists ([known issue in k8s client-go](https://github.com/kubernetes/kubernetes/issues/73497)).  If that spike exceeds 170Mi, then we'd enter an OOM cycle (until the number of endpoints/services drops).

CoreDNS 1.3.1 has a [known bug](https://github.com/coredns/coredns/pull/2529) that causes it to crash if the k8s api client tries to log an error/warning (fixed in 1.4.0).  That lines up with things mysteriously being resolved in 1.5.0.   But the scenario above could be triggered by any restart/respawn.

If in the DNS_MEMORY_LIMIT=300Mi test shows that there are no coredns pod restarts, then the issue lies elsewhere.

**Comment by wojtek-t** [comment]
> OK, I was hoping to see if the coredns was restarted at all during the DNS_MEMORY_LIMIT=300Mi test.

It's not - it's not trying to use more than ~180MB across whole test.

**Comment by chrisohaver** [comment]
> It's not - it's not trying to use more than ~180MB across whole test.

Thats not exactly what I was asking.  I was asking if it had been restarted for _any_ reason at any point during the test - not just OOM death.  The point being that _any_ restart (including non-OOM) will a cause a memory spike for a client watching endpoints, as the API will flood the client with an enormous endpoint list.

Although, perhaps there is little value to try to solve the mystery at this point (i.e. release is over).

**Comment by wojtek-t** [comment]
Aaah ok - that's what you meant.
No - the only restarts that we observed were OOMs (i.e. the first one restart was also an OOM).

**Comment by Pothulapati** [comment]
Hello! I'm part of the bug triage team for the 1.16 release cycle and considering this issue is tagged for 1.16, but not updated for a long time, I'd like to check its status. The code freeze is starting on August 29th (about 1.5 weeks from now), which means that there should be a PR ready (and merged) until then.

Do we still target this issue to be fixed for 1.16? If not please re-tag the issue to the planned milestone.

**Comment by chrisohaver** [comment]
@Pothulapati, AFAIK the root cause of this issue was not identified.  The plan is to move up to CoreDNS 1.6.2 for the 1.16 release, at which point I would expect this issue go away (as it did in 1.5.0).

**Comment by xmudrii** [comment]
@chrisohaver Any update on this? Should we move it from the milestone?

**Comment by chrisohaver** [comment]
@wojtek-t, I presume this issue is not occurring with the current version of COS (whatever that is) and CoreDNS (1.6.2)?

**Comment by wojtek-t** [comment]
Resource usage of CoreDNS 1.6.2 is amazing - it's way better than it was and this one could be closed as obsolete.
