### ISSUE TITLE
kubelet eviction should respect pod QoS

### ISSUE THREAD

**Issue by yuchengwu** [kubernetes/kubernetes#78561]
**What happened**:

Otherwise there are possibility that `Burstable` pods can be evicted before `Best-Effort` pods, `Guaranteed` pods can be killed before `Burstable` pods.

**What you expected to happen**:
Pod QoS should be considered when eviction happens

**How to reproduce it (as minimally and precisely as possible)**:
The current eviction policy:
https://github.com/kubernetes/kubernetes/blob/990695c839a99cbd0e00fd3806f9802e2af7c2e0/pkg/kubelet/eviction/helpers.go#L667-L672

- Round 1: evict a pod that resource usage exceeds its request
- Round 2: evict a pod that has lower priority
- Round 3: evict a pod that has higher (usage - request) value

Let's consider the following two scenarioes without PodPriority enabled or all pods have same priority

- scenario 1: `Burstable` pods can be evicted before `Best-Effort` pods
pod1 is a `Burstable` pod, pod2 is a `Best-Effort` pod, both resource usage exceeded their request, kubelet failed to make a decision at first two rounds.
Enter round 3, if pod1 consuming far above requests that is to say [pod1 usage - request] greater than [pod2 usage - request], pod2 request should be zero I think, 
then pod1 will be evicted.

- scenario 2: `Guaranteed` pods can be evicted before `Burstable` pods
pod1 is a `Guaranteed` pod, pod2 is a `Burstable` pod, both resource usage not exceeded their request, kubelet failed to make a decision at first two rounds.
Enter round 3, if [pod1 usage - request] greater than [pod2 usage - request], pod1 will be evicted.

**Anything else we need to know?**:

**Mitigation** 
Enable PodPriority and manually set pod priority to explictly distinguish pod QoS with the priority: `Guaranteed` > `Burstable` > `Best-Effort`,  so kubelet can make a decision at round 2. 
This is however sort of unnecessary as pods already have implict priorities [by design, by their QoS](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node/resource-qos.md), additionaly that will enforce user enable pod priority feature.

**Environment**:
- Kubernetes version (use `kubectl version`):
1.15
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by yuchengwu** [comment]
As pod priority mentationed here, I personally beleive it's worth to discuss whether we should take a critical `Burstable` pod into special consideration.

The requirement comes from our production env, pod resource usage is volatile and changes with the business. To maximize resource utilization, we config it a `Burstable` pod at most time, so it can consume more resouces by evicting trivial pods, like low priority and `Best-Effort` pods during peak performance, whereas during low usage state allowing us to schedule more workloads on the node. 

Meanwhile, we also config it with higher or even highest priority(config it a critial pod), wishing it always keep alive, but kubelet is not aware of pod priority at round 1, and the pod could be killed. I am afraid this is not user expected.

**Comment by yuchengwu** [comment]
/sig @node
/assign @dashpole
/cc @mtaufen @dchen1107  @derekwaynecarr

Correct me if I overlooked something.

**Comment by dashpole** [comment]
There is a lot here, I'll do my best to answer it all.

> scenario 2: Guaranteed pods can be evicted before Burstable pods

Scenario 2 is not, except in rare scenarios.  Requests are not allowed to exceed `Allocatable` on the node, so for the node to be under memory pressure requires at least 1 pod to be exceeding its requests.

>scenario 1: Burstable pods can be evicted before Best-Effort pods

Scenario 1 can happen, but that is by design.  A relatively well-behaved best-effort pod will be kept over Burstable pods which are using far more resources.

> This is however sort of unnecessary as pods already have implict priorities by design, by their QoS, additionaly that will enforce user enable pod priority feature.

QoS is not an implicit priority anymore.  At the time QoS was added, we hoped it would evolve to encompass access to resources on the node and influence CPU and IO scheduling to differentiate between "latency-sensitive" and "batch" workloads, but that never really happened.  We initially used it as an approximation for priority, but that resulted in poor user incentives, such as users setting CPU limits on their containers to prevent memory eviction.  CPU limits don't play nicely with latency-sensitive workloads.

> As pod priority mentationed here, I personally believe it's worth to discuss whether pod priority should take precedence over pod resource usage when ranking pods.

I assume you mean pod priority should take precedence over whether a pod is exceeding its requests, as pod priority already takes precedence over usage-based ranking.  We guarantee pods have access to their requested resources.  If pod priority takes precedence over whether a pod is exceeding its requests, we can no longer guarantee this.

> To maximize resource utilization, we config it a Burstable pod at most time, so it can consume more resouces by evicting trivial pods, like low priority and Best-Effort pods during peak performance, whereas during low usage state allowing us to schedule more workloads on the node.

I would think of requests not as estimates of what the pod will use, but as a "soft limit".  In other words, at what usage would it be reasonable to evict this pod?  For pods that you want to lower the chance of eviction for, you should set requests far above the expected usage.  For pods where you don't mind if they are evicted or not, and want them to run even in situations where the resources they use may not be available, set requests below expected usage.  Requests only come into play on the node when performing out-of-resource handling, so you should set them according to the behavior you want to achieve at that point in time, rather than in "normal" scenarios.

PodPriority is a useful tool for dividing up the "extra" resources on a node.  If, for example, you had a pod which requests far more than it consumes (e.g. your "important" pod above), you can use PodPriority to determine which other pods get access to the resources that the "important" pod requests, but isn't using.  If you have two pods whose normal usage exceeds its requests, these pods are both using "extra" resources on the node.  PodPriority lets you decide which of these two pods would be given access to those resources, and which would be evicted.

**Comment by yuchengwu** [comment]
Thanks for the explanation.

> I assume you mean pod priority should take precedence over whether a pod is exceeding its requests

Yes, this is what I mean.

Sounds like there is nothing we should do in this issue, closing.
