### ISSUE TITLE
why delete job created pod when job failed ?

### ISSUE THREAD

**Issue by fudali113** [kubernetes/kubernetes#78644]
**What happened**:
if my job failed, i can`t find this job created pods, so i can`t find my application error logs 

**What you expected to happen**:
if my job failed, this job created pod not delete

**How to reproduce it (as minimally and precisely as possible)**:
run a error job

**Anything else we need to know?**:
https://github.com/kubernetes/kubernetes/blob/4b4420f53e5b6681bbfa5cbf22d8133c4eea6069/pkg/controller/job/job_controller.go#L520

**Environment**:
- Kubernetes version (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:08:19Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

**Comment by fudali113** [comment]
@kubernetes/sig-apps-job

**Comment by Joseph-Irving** [comment]
Once a job had failed, (this occurs when it's exceeded its active deadline seconds or backoff limit) any active pods are deleted to prevent them from running/crashlooping forever. Any pods that aren't active e.g they are in a Pod phase of `Failed` or `Succeeded`, should be left around. 

If you want your pods to be left around after failure, changing the restart policy of your pods to `Never` should prevent them from being immediately cleaned up, however this does mean that a new pod will be created each time your pods fail until the backoff limit is reached. 

It's also generally a good idea to having some sort of logging pipeline in your cluster so that you can inspect the logs of pods long after they've been deleted.

**Comment by fudali113** [comment]
have a logging pipeline can fixed this question, but this solution need external depend； i think that is not easy to use and delete active pods is not my first feel when job completed(it make me so puzzled on meet this question at first), stop pods is my first feel, have any way to stop active pods but not delete?

**Comment by Joseph-Irving** [comment]
There's no mechanism in kubernetes to "stop/pause" a pod, the pod can enter a non-active state (Failed/Succeeded) by your processes exiting with success (exit code: 0, restart policy: OnFailure/Never) or failure (restart policy: Never). So if your processes are still running when the job becomes failed the only way to stop the pod from continuing to run is to delete the pod.

Also see https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/ for some more info.

**Comment by fudali113** [comment]
ok, i got it; 

but i think this knowledge need write on [job document](https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/#handling-pod-and-container-failures), let user can fast get it when them meet with this question;

such as:
`if your job have some error but you restartPolicy is not `Never`, so your job created pods will be deleted`

What do you think? @Joseph-Irving

**Comment by alanmoment** [comment]
I have same question. And my case is no Pod has keep when job is failed. My job setting is `failedJobsHistoryLimit=3`
