### ISSUE TITLE
have a saner default value of --terminated-pod-gc-threshold 

### ISSUE THREAD

**Issue by nikopen** [kubernetes/kubernetes#78693]
controller-manager 's config flag `--terminated-pod-gc-threshold ` currently has a default value of `12500` - that's quite a lot! 

/sig apps 
/kind bug

**Comment by alanjcastonguay** [comment]
Reference https://github.com/kubernetes/kubernetes/blob/c48ed1c5aca6e06b6a3d70d5f189216df3150379/pkg/controller/podgc/config/v1alpha1/defaults.go#L23-L31

**Comment by qiutongs** [comment]
Revive this issue and see if we can come up with a more reasonable default value for the threshold.

**Comment by qiutongs** [comment]
Job controller currently relies on Pods not being removed to keep track of completions. https://github.com/kubernetes/kubernetes/issues/28486

Therefore it seems we'd better keep the current threshold before fixing that issue.

**Comment by alculquicondor** [comment]
/reopen
as this is still relevant in the future.

**Comment by dlouzan** [comment]
@qiutongs Since https://github.com/kubernetes/kubernetes/pull/98238 implemented better job tracking in 1.22, should this be reopened and a saner default be applied? 12500 still feels like quite a lot.

/cc @nikopen

**Comment by alculquicondor** [comment]
I'm not sure changing the default is a good idea. Users might be relying on this. For example, I'm aware that Argo requires the pod to also stay in the API to do its accounting.

If you are sure that your cluster doesn't have these problems, why not change the value on your end?

**Comment by dlouzan** [comment]
@alculquicondor Hey, thanks for the answer. Not an issue on our end, we can ofc modify the defaults. It's even mentioned on the [CIS hardening for k3s](https://rancher.com/docs/k3s/latest/en/security/hardening_guide/#control-1-3-1), as this might be a too-high value for certain environments.

But since I don't know all implications of that change, and the docs do not explain it in detail, this feedback is actually kind-of what I was looking for 😀
