### ISSUE TITLE
[Failing Test] timeouts in ci-kubernetes-e2e-gce-scale-performance

### ISSUE THREAD

**Issue by alejandrox1** [kubernetes/kubernetes#78734]
**Which jobs are failing**:
ci-kubernetes-e2e-gce-scale-performance

**Which test(s) are failing**:
* `testing/density/config.yaml`
* `testing/load/config.yaml`
* `ClusterLoaderV2`

**Since when has it been failing**:
Due to [previous issues with prow](https://github.com/kubernetes/test-infra/blob/master/docs/post-mortems/2019-05-30.md) we cannot at this time determine (we are working on resolving this issue in testgrid) the exact moment these tests started failing but they were passing on 5/30 and failed on 6/2.

**Testgrid link**:
https://testgrid.k8s.io/sig-release-master-informing#gce-master-scale-performance

**Reason for failure**:
There failures seem to be related to pods not reaching the desired state within the timeout period.
```
W0604 03:17:19.141] E0604 03:17:19.140882 12669 wait_for_controlled_pods.go:497] WaitForControlledPodsRunning: test-jfyird-5/saturation-rc-0 timed out
```
There were also issues with reaching prow:
```
I0604 03:41:37.997] error dialing prow@35.227.71.123:22: 'dial tcp 35.227.71.123:22: connect: connection timed out', retrying
```
and 
```
W0604 03:43:44.069] E0604 03:43:44.069271 12669 profile.go:101] failed to gather profile for simple.profileConfig{componentName:"kube-scheduler", provider:"gce", host:"35.227.71.123", kind:"heap"}: failed to execute curl command on master through SSH: error getting SSH client to prow@35.227.71.123:22: 'dial tcp 35.227.71.123:22: connect: connection timed out'
```

It was mentioned in a previous issue, #76670, that #77127 may be a contributor to failures in this job.

/cc @kubernetes/sig-scalability-test-failures 
/kind failing-test
/priority important-soon
/milestone v1.15

/cc @jimangel  @smourapina @rarchk @alenkacz
/cc @wojtek-t

**Comment by oxddr** [comment]
It seems, that we have an actual problem with test, not only issues with Prow (https://github.com/kubernetes/test-infra/issues/12940). We have two runs, where apiserver blew up. @krzysied is looking into this issue and hopefully by the end of the day (CET time) will be able to provide more insights. Right now I'd claim we have a regression. 

/cc @krzysied @mborsz

**Comment by krzysied** [comment]
I've run gce 5k test manually. It failed in similar way as the prow job. We have regression.

I'm not sure what is the root cause of the regression yet.

Good thing is that regression affected density test, which allows to "quickly" verify if k8s build is good or bad. I will try to run bisection to find the root cause.

**Comment by alejandrox1** [comment]
@oxddr  @krzysied any updates on this? :eyes:

**Comment by krzysied** [comment]
@alejandrox1 We are working on this. We haven't found the root cause yet.

I'm running bisection to find the problematic commit. Based on the current results, it looks like it is something from this range https://github.com/kubernetes/kubernetes/compare/59f0f2d2f9cf24...7929c15ec7a

**Comment by alejandrox1** [comment]
For more context on this issue, from https://github.com/kubernetes/test-infra/issues/12940 :
> We suspect this might cause by log-exporter not working correctly (e.g. due to lack of permissions to GCS). I am hoping that the current run will give us more insight.

The problem was first noted in here https://github.com/kubernetes/test-infra/issues/11594#issuecomment-499605601 .

**Comment by oxddr** [comment]
@alejandrox1 the problem you mentioned has been mitigated using larger disk in the build cluster. At the moment we have a regression in Kubernetes itself - for a yet unknown reason apiserver is dying in the middle of density tests.

**Comment by krzysied** [comment]
> At the moment we have a regression in Kubernetes itself 

+1 I'm running manual tests that aren't using test-infra infrastructure, kubetest version remains unchanged between the runs. Some of the test passed, some failed. This regression should be unrelated to test-infra.


About the regression... Current scope of bisection is https://github.com/kubernetes/kubernetes/compare/163ef4d22c925f02f38565d2ac22b6611f82d042...5e185544421 so it's only few commits left.
Most of them are comments/doc/tests fixes.
My random guess would be: https://github.com/kubernetes/kubernetes/commit/b094dd9bc3a4617b587b04993931a6110691ddc0, but it still needs to be verified.

I will post next update tomorrow.

**Comment by claurence** [comment]
@oxddr @krzysied are either of y'all able to join our burndown call tomorrow to get some clrity on this issue and if we need a fix for 1.15?  

Burndown is at 9am PT

**Comment by oxddr** [comment]
That's 6pm CEST - I can make it then. Hopefully we'll be able to provide more insight tomorrow.

**Comment by krzysied** [comment]
It looks like the klog update is root cause of the issue. We are going to revert the change to fix the tests -  #78931.

**Comment by krzysied** [comment]
I've just finished testing HEAD w/o klog update. Test passed without a problem.
It seems there is no other regressions (regarding density test).

**Comment by liggitt** [comment]
hoisting [discussion from slack](https://kubernetes.slack.com/archives/C09QZTRH7/p1560358427043000) for posterity:

1. --log-file was not working properly, causing things to get logged multiple times to the same file (unknown if this issue pre-existed in glog, or if klog regressed in the <= 1.14 timeframe, but there were no --log-file related changes in klog between v1.14.0 and master as of the revert back to klog v0.3.1)

2. this was noticed by scale tests when we started trying to use --log-file in https://github.com/kubernetes/kubernetes/pull/76396/files#diff-6e3b476b9225d1213dc6ad13e453fc16R2083, so that PR was reverted in https://github.com/kubernetes/kubernetes/pull/77904 to stop using --log-file

3. an attempt was made to fix the multi-logging issue in klog (https://github.com/kubernetes/klog/pull/65), included in 0.3.2, and bumped in kube in https://github.com/kubernetes/kubernetes/pull/78465

4. that klog change by itself caused perf regressions (even before reintroducing the PR to start using --log-file again, which is still open at https://github.com/kubernetes/kubernetes/pull/78466/files#diff-6e3b476b9225d1213dc6ad13e453fc16R1863)

so that's where we are today... with the same klog handling of --log-file we had in kube v1.14, and without use of --log-file in our manifests (because it's buggy)

**Comment by mm4tt** [comment]
Yesterday's run, with reverted https://github.com/kubernetes/kubernetes/pull/78465, passed. 
I believe we can close this one.

**Comment by alejandrox1** [comment]
The specific perf regression due to klog v0.3.2 was revert.
However this job is not completely green due to https://github.com/kubernetes/kubernetes/issues/79096

/close
