### ISSUE TITLE
Flexvolume master driver is blocking controller-manager from moving to distroless

### ISSUE THREAD

**Issue by verult** [kubernetes/kubernetes#78737]
There is an effort underway to move to core k8s component images to distroless. One side effect is that shell access is unavailable inside these containers.

Dummy Flexvolume drivers in e2e tests are written as shell scripts, and it's possible that many drivers are written this way as well. These drivers are a problem for controller managers going distroless - the driver Init() call will fail.

Going forward here are some of the possible options:
1. Don't move to distroless for controller manager
2. Deprecate Flex (but we've already issued a statement that k8s 1.x is always going to support Flex)
3. Limit Flexvolume support on master to only drivers that don't require shell
4. Ban Flexvolume master installations.

If distroless for controller manager is a definite requirement, #3 sounds the most reasonable. Translating the Flexvolume API from shell to a different language shouldn't be too bad, and presumably drivers running in production already have something written in non-shell.

SIG storage what do you think?

/sig storage
/cc @yuwenma @tallclair @saad-ali @chakri-nelluri 
/priority important-soon

**Comment by msau42** [comment]
Let's also bring this up at the sig meeting tomorrow. 2-4) has the possibility to break many drivers in production.

**Comment by saad-ali** [comment]
@verult brought this up at the June 6 SIG meeting. Decision was to send out messaging to figure out who was effected. Cheng sent message to kubernetes-sig-storage on June 6 with a followup on July 2 (see [message](https://groups.google.com/d/msg/kubernetes-sig-storage/618lBlJo8rU/wYkqMI-zAgAJ)). But didn't hear anything back. 

Current plan of record is to continue to communicate this change (distroless is coming and may break Flex master drivers)  widely, and announce it in release notes when it happens.

**Comment by msau42** [comment]
We missed a deprecation notice for 1.17.  Should we send out the message to a wider audience and then deprecate for 1.18?

**Comment by tallclair** [comment]
/remove-lifecycle rotten

@msau42 - did the deprecation notice make it into 1.18?

/cc @dekkagaijin

**Comment by msau42** [comment]
We sent an email out to sig-storage in July 2019 and got no response. We just forwarded the email to the wider kubernetes-dev mailing list.

This is our proposed plan for moving forward with moving kube-controller-manager to distroless:
- [x] Send out the email notice that this change is coming
- [ ] Mention this change in release notes for 1.19
- [ ] We can continue to support flexvolume master behavior for attaching/resizing, however it will require that affected users build their own kube-controller-manager images using a non-distroless base image.
- [ ] We can add a "[Feature: FlexvolumeMaster]" tag to the k/k e2e tests so that users who need this behavior can still run the e2e tests for this feature.

Open question is when can we make the change to distroless? Our proposal here does not require removing the feature. It can continue to work if you build your own image. And I think that also aligns with the approach we're taking for other previously prepackaged binaries, like in #85454

**Comment by dims** [comment]
@msau42 let's do it in time for 1.19 like you said, we are not removing a feature here. ( cc @liggitt )

**Comment by BenTheElder** [comment]
Noting that this doesn't just mean not writing them in shell, you won't be able to depend on the presence of a userspace (IE your binary can't shell out to typical userspace utils)

**Comment by justaugustus** [comment]
/assign @dims @msau42 
Can we close this given https://github.com/kubernetes/kubernetes/pull/91329 has merged and maybe track the other items Michelle [mentions](https://github.com/kubernetes/kubernetes/issues/78737#issuecomment-627021732) in another issue?

**Comment by dims** [comment]
No objections from me @justaugustus

**Comment by msau42** [comment]
All other items have been addressed as well
/close
