### ISSUE TITLE
Handling E2E tests using to be deprecated features like 'NodeSelector'

### ISSUE THREAD

**Issue by globervinodhn** [kubernetes/kubernetes#78891]
**What would you like to be added**:
As per the link, https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity - NodeSelector is to be deprecated.
Extract:- "nodeSelector continues to work as usual, but will eventually be deprecated, as node affinity can express everything that nodeSelector can express."

Under this scenario, I have the following queries:-
   1. Should we avoid using NodeSelector feature for new E2E tests?
   2. How to handle the current E2E tests which aren't conformance promoted?
         a. Can they be promoted as it is, provided they meet the conformance needs? or
         b. Should the tests be altered to use NodeAffinity and then promoted?

**Why is this needed**:
To have a confirmed way to handle 'to be deprecated' features.

**Comment by mgdevstack** [comment]
IMO,
>Should we avoid using ~~NodeAffinity~~ NodeSelector feature for new E2E tests?

+1 for all new e2e to use NodeAffinity instead of NodeSelector as NodeAffinity can handle broader range constraints.

> Can they be promoted as it is, provided they meet the conformance needs?

+1, for upcoming release i.e. v1.6, this is definitely a candidate for promotion. There is no such clarity about the release since when `NodeSelector` would be deprecated. Once it is deprecated, respective Conformance e2e can be demoted following [Conformance Test Version Skew Policy](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/conformance-tests.md#conformance-test-version-skew-policy)

>Should the tests be altered to use NodeAffinity and then promoted?

-1, As it is not yet deprecated and aligned with version-skew-policy, it shouldn't be altered. Instead writing new e2e to support NodeAffinity would be good expressing various `nodeSelectorTerms`.

**Comment by k-toyoda-pi** [comment]
Hi, I found some tests use deprecated feature which is `kubectl run --generator`.
If we can demote these tests from conformance, should we change `framework.ConformanceIt` to `ginkgo.It` and delete it from test/conformance/testdata/conformance.txt?

**Comment by johnbelamaric** [comment]
I agree with @mgdevstack here. We should not ignore "this will be deprecated one day" for current tests, but for new tests use NodeAffinity.

@k-toyoda-pi which tests specifically? In general, we should not demote these tests. If they use it in passing, we should fix them to not use it. If they are explicitly testing a deprecated feature, then we still need to do that until the deprecation period is over, after which the tests can be removed.

**Comment by spiffxp** [comment]
/priority awaiting-more-evidence
when is `NodeSelector` going to be deprecated?

**Comment by draveness** [comment]
FYI: https://github.com/kubernetes/kubernetes/issues/82331

**Comment by draveness** [comment]
We won't deprecate fields after it graduates to a stable version. And based on this, can we close this issue for now?

**Comment by spiffxp** [comment]
/close
Agree we can close, this is something to consider if/when a v2 API comes around
