### ISSUE TITLE
Need to check migrated PVs get deleted through CSI if CSI migration was enabled post provisioning

### ISSUE THREAD

**Issue by ddebroy** [kubernetes/kubernetes#79043]
**What happened**:
If an in-tree volume is provisioned with in-tree provisioner (without migration enabled) and later migration gets enabled, the PV controller is expected to coordinate with the CSI external provisioner to make sure it does get deleted.

For above to happen, this [piece of code](https://github.com/kubernetes/kubernetes/blob/ffffd6b6f55d15c6868bc2080419740dc7a0d93d/pkg/controller/volume/persistentvolume/pv_controller.go#L1684) in the PV controller needs to return nil, nil even if `AnnDynamicallyProvisioned` is set to a plugin prefixed with `kubernetes.io/`.

The CSI external provisioner also needs to be enhanced to delete PV's whose `AnnDynamicallyProvisioned` is set to a plugin prefixed with `kubernetes.io/`. 

We also need to prevent a race between external provisioner and in-tree PV controller in the delete path when CSI Migration flag is disabled. To achieve this synchronization, PV controller will need to mark the in-tree PVs that need to be deleted by external provisioner with an additional annotation to signal that CSI Migration flag is enabled in-tree and the CSI external provisioner needs to process the deletion.

**What you expected to happen**:
CSI driver should process the deletion.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.15
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by davidz627** [comment]
> PV controller will need to mark the in-tree PVs that need to be deleted by external provisioner with an additional annotation to signal that CSI Migration flag is enabled in-tree and the CSI external provisioner needs to process the deletion.

Instead of this would it be possible to just change the `provisioned-by` annotation on the `PV`. That *is* the signal. Otherwise we run the risk of adding yet another condition to the already complex logic. I wonder if its possible to have the PV controller go in and switch them all on `init` when it detects `CSIMigrationPlugin` is on.

**Comment by dims** [comment]
cc @xing-yang

**Comment by davidz627** [comment]
This is a high priority to be fixed and should be cherry-picked as well if possible

**Comment by rfranzke** [comment]
I'd like to raise the priority for this one as well, especially after the explicit end-user ask for migration to CSI (for AWS EBS and GCE PD, at least) in the official 1.17.0 release notes. IMO it's not possible to migrate because deletion of PVs created before CSI migration does not work due to this bug. 

See also: https://kubernetes.slack.com/archives/CG04EL876/p1578492699010800

**Comment by davidz627** [comment]
/open
no current released versions of Kubernetes or External-provisioner where this is fixed. Likely to be `k8s 1.17.4+` and `external-provisioner 1.6+`
