### ISSUE TITLE
Provide more reliable restrictions for secrets

### ISSUE THREAD

**Issue by medmedchiheb** [kubernetes/kubernetes#79080]
By default in kubernetes, secrets can be consumed by pods or users in the specified namespace.

**What would you like to be added**:

I suggest, doing more restrictions for secrets.
By RBAC, is great.
But, we could also enhance the restrictions

I'm thinking about adding `podSelector` In the secret object itself, by doing this, secrets are restricted by default until you specify the `podSelector`.
`podSelector` can have `matchLabels` or `matchExpression`.
I'm assuming that the validation can be added through the admission control.

**Why is this needed**:

Provide more restrictions for consuming secrets.

**Comment by liggitt** [comment]
Early on in the project, there was a goal of associating secrets with service accounts and only allowing secrets to be mounted into a pod if the pod's service account was associated with the secret. Even that level of specification was seen as too fiddly, and gained effectively no adoption.

Since pod labels are not ACLed, any pod author could shape their pod's labels to match any secret's selector, and continue to mount any secret in their namespace.

This sounds like a good candidate for external policy control (like opa or gatekeeper), rather than something built into the core API.
