### ISSUE TITLE
Promote PodTemplate Test to Conformance

### ISSUE THREAD

**Issue by devaips** [kubernetes/kubernetes#79116]
Using the list of tested stable endpoints referenced in https://github.com/kubernetes/kubernetes/issues/78748, we can pick out the endpoints which are part of the PodTemplate kind:

[createCoreV1NamespacedPodTemplate](https://apisnoop.cncf.io/?zoomed=operationId-stable-core-createCoreV1NamespacedPodTemplate&showUntested=false&showConformanceTested=false)

This is a stable core endpoint which has existing testing, potentially making for low-hanging fruit to upgrade to Conformance.

/area test
/area conformance
/sig testing

**Comment by hh** [comment]
Promoting either of these test will increase Conformance Coverage by 1 endpoint.
```
[sig-api-machinery] Servers with support for API chunking should return chunks of results for list calls
[sig-api-machinery] Servers with support for Table transformation should return chunks of table results for list calls
```

**Comment by hh** [comment]
```
[sig-api-machinery] Servers with support for API chunking should return chunks of results for list calls
```
This test focuses on chunking the results of API list calls. It happens to create and list PodTemplates, which is why it's on the radar.

I think we should evaluate whether it's a good conformance test or not separately from the fact that it happens to hit endpoints that would increase endpoints hit by conformance tests.

**Comment by timothysc** [comment]
Closing due to rube-goldburg coverage.
