### ISSUE TITLE
pull-kubernetes-integration#TestUnreservePlugin fails frequently

### ISSUE THREAD

**Issue by cwdsuzhou** [kubernetes/kubernetes#79166]
**Which jobs are failing**:

pull-kubernetes-integration

**Which test(s) are failing**:

TestUnreservePlugin

**Since when has it been failing**:

It happens frequently this week

**Testgrid link**:

https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/79164/pull-kubernetes-integration/1141308395165323264/

**Reason for failure**:

I0619 11:55:31.165887  109629 wrap.go:47] PUT /api/v1/namespaces/default/endpoints/kubernetes: (2.062872ms) 200 [scheduler.test/v0.0.0 (linux/amd64) kubernetes/$Format 127.0.0.1:54252]
framework_test.go:577: test #3: Expected the unreserve plugin to be called 2 times, was called 1 times.

**Anything else we need to know**:

**Comment by cwdsuzhou** [comment]
This  seems to be  a issue in scheduler integration tests

/sig scheduling

**Comment by alenkacz** [comment]
I was analyzing that failure based on the logs from given link. Based on my analysis the problem lies in here https://github.com/kubernetes/kubernetes/blob/55ff3893ceb9f25256c0f0919ce583abf92de334/test/integration/scheduler/framework_test.go#L584

We wait for the pod to being unschedulable, and then we compare the counts of pre-bind and unreserve called. But this is done asynchronously so it can happen that between `waitForPodUnschedulable` and us reading the counts the pod has already been scheduled and pre-bind was called while unreserve was not yet called.

A simple solution would be to assert `unresPlugin.numUnreserveCalled < 1` instead of `unresPlugin.numUnreserveCalled != pbdPlugin.numPrebindCalled`

I'll try to submit PR with that fix to see what people think about that :)

**Comment by draveness** [comment]
> I was analyzing that failure based on the logs from given link. Based on my analysis the problem lies in here
> 
> https://github.com/kubernetes/kubernetes/blob/55ff3893ceb9f25256c0f0919ce583abf92de334/test/integration/scheduler/framework_test.go#L584
> 
> We wait for the pod to being unschedulable, and then we compare the counts of pre-bind and unreserve called. But this is done asynchronously so it can happen that between `waitForPodUnschedulable` and us reading the counts the pod has already been scheduled and pre-bind was called while unreserve was not yet called.
> 
> A simple solution would be to assert `unresPlugin.numUnreserveCalled < 1` instead of `unresPlugin.numUnreserveCalled != pbdPlugin.numPrebindCalled`
> 
> I'll try to submit PR with that fix to see what people think about that :)

FYI: 

+ https://github.com/kubernetes/kubernetes/pull/77574
+ https://github.com/kubernetes/kubernetes/pull/77598

/assign @alenkacz
/kind flake

**Comment by draveness** [comment]
cc/ @danielqsj @bsalamat
