### ISSUE TITLE
Clarify HPA Value vs. AverageValue

### ISSUE THREAD

**Issue by josephburnett** [kubernetes/kubernetes#79272]
The autoscaling v2 APIs allow users to specify either `Value` or `AverageValue` for custom and external metrics.  On the surface, it looks like the only difference between them is whether the metric value is divided by the number of Pods or not.  However in implementation (and I believe in design) they behave quite differently.

## Value

When `Value` is given as a target for a custom or external metric, the replica count is calculated in the [`GetObjectMetricReplicas`](https://github.com/kubernetes/kubernetes/blob/737d74d12de86481b17d2f361edd70b26580b139/pkg/controller/podautoscaler/replica_calculator.go#L237) or [`GetExternalMetricReplicas`](https://github.com/kubernetes/kubernetes/blob/737d74d12de86481b17d2f361edd70b26580b139/pkg/controller/podautoscaler/replica_calculator.go#L305) methods respectively.  These methods calculate a usage ratio by dividing the metric value by the target value.  Then multiply the current ready Pod count by the usage ratio to determine the desired replica count.

https://github.com/kubernetes/kubernetes/blob/737d74d12de86481b17d2f361edd70b26580b139/pkg/controller/podautoscaler/replica_calculator.go#L243

https://github.com/kubernetes/kubernetes/blob/737d74d12de86481b17d2f361edd70b26580b139/pkg/controller/podautoscaler/replica_calculator.go#L255

## AverageValue

When `AverageValue` is given as a target for a custom or external metric, the replica count is calculated by the [GetObjectPerPodMetricReplicas](https://github.com/kubernetes/kubernetes/blob/737d74d12de86481b17d2f361edd70b26580b139/pkg/controller/podautoscaler/replica_calculator.go#L262) or [GetExternalPerPodMetricReplicas](https://github.com/kubernetes/kubernetes/blob/737d74d12de86481b17d2f361edd70b26580b139/pkg/controller/podautoscaler/replica_calculator.go#L337) methods respectively.  These methods calculate usage ratio by first multiplying the target value by the number of Pods, then dividing the metric value.  This is expected.

However when calculating the desired number of replicas, neither usage ratio or the current pod count is taken into consideration.  Instead, the `PerPod` methods divide the metric value by the target value only.

https://github.com/kubernetes/kubernetes/blob/737d74d12de86481b17d2f361edd70b26580b139/pkg/controller/podautoscaler/replica_calculator.go#L272

## Feedback loop or not

By specifying `Value` the user is targeting a specific value for the metric.  The autoscaler implements a feedback loop to increase the number of Pods to achieve that value.  It will make more Pods.  And if those Pods are not enough to move the metric value, it will make still more Pods.

However by specifying `AverageValue` the user is pinning the number of metric units "assigned" to each Pod.  No feedback loop is created.  The autoscaler just "reconciles" the number of pods to the current metric value to maintain the desired per-pod value.

This difference in behavior is subtle and not conveyed in the [type comments](https://github.com/kubernetes/kubernetes/blob/737d74d12de86481b17d2f361edd70b26580b139/staging/src/k8s.io/api/autoscaling/v2beta2/types.go#L198-L215) or the [documentation](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/#autoscaling-on-multiple-metrics-and-custom-metrics). 

## Why this behavior

I believe this behavior is by design (@MaciekPytel to confirm) because most of the examples cited are specifying a desired number of messages per Pod given an input queue.

> For example if your application processes tasks from a hosted queue service, you could add the following section to your HorizontalPodAutoscaler manifest to specify that you need one worker per 30 outstanding tasks.

([source](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/#autoscaling-on-metrics-not-related-to-kubernetes-objects))

And the original [proposal](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/autoscaling/hpa-external-metrics.md#example).

## Documentation request

The public documentation, types comments and implementation itself should explain this difference in behavior more clearly.  In particular, the feedback loop or not behavior.  The `AverageValue` could very well be implemented with a feedback loop so it would be useful to explain why it is not.

**Comment by kim0** [comment]
Hello @josephburnett .. Was this clarified somewhere by now ? 
I'm still finding it a bit confusing. I was trying to scale GKE pods based on the number of waiting tasks in a queue. It seems what I need is `AverageValue`, which fits my mental model of how this should work. I can't however understand what `Value` is supposed to be doing. That's why I'm looking for some clarifying docs if this has been handled. Thanks!

**Comment by bpinske** [comment]
To further illustrate the difference between these two interpretations of a metric, consider the following kafka lag scenario with the metric being interpreted as an averageValue.

100 partitions each at a lag of 50k units for a sum of 5000k lag with a lag threshold of 100k per-consumer with 10 consumers will result in a per-consumer lag of 500k. A scale up will occur to process the 5000k lag.

100 partitions each at a lag of 50k units for a sum of 5000k lag with a lag threshold of 100k per-consumer with 50 consumers will result in a per-consumer lag of 100k. You will just be dancing at the precipice of the threshold and no action will be taken (due to the default tolerance window of .1) even though you have 5000k unprocessed messages!

In the above case, I'm not particularly interested that I may have 50k lag units per partition. I care that I have lag at all. If I have 5000k units of lag, I should scale up regardless of how many workers I may already have: If I have 5000k units of lag I clearly need more processing power. This is where you would want to use the Value interpretation.

I can easily imagine most cases of an external measure of 'lag' from a message bus, or some prometheus query being most appropriately represented as a Value.

**Comment by liubog2008** [comment]
I think `Value` is not reasonable...

I find `Value` is introduced in HPA v2 and named as `TargetValue` in `Object` type. `Object` type is designed for some metrics from k8s objects such as `Ingress`. And these metrics are not directly related to pods.

Now desired replica for `Value` target is calculated as below

```
replicaCount = int32(math.Ceil(float64(utilization) / float64(targetUtilization) * float64(readyPodCount))) 
```
`utilization` is the sum of metric.
`targetUtilization` is user defined `Value`.

We will find that `utilization * readyPodCount` is hard to explain. Only when `utilization` means average value per pod such as `QPS per pod` or `CPU usage per pod`, `utilization * readyPodCount` has a real meaning. 

However, at this situation, `utilization * readyPodCount` will have the same meaning with `utilization` in `AverageValue` algorithm.

```
replicaCount = int32(math.Ceil(float64(utilization) / float64(targetAverageUtilization))) 
```

And all meaningful metrics for `Value` such as `QPS per pod` are calculated by `QPS / readyPodCount` in fact. So why not use `AverageValue` directly?

I don't know whether there is a meaningful metric which is out of my scope, but for all examples I find, `AverageValue` is more reasonable.

**Comment by MarkAmeryCurative** [comment]
The docs on this are still very unclear.

* The API docs at https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/horizontal-pod-autoscaler-v2/ give no indication of what `value` means. They indicate an `averageValue` relates to "the average of the metric across all relevant pods" while value just relates to "the metric", but what does the latter mean? Based on the comment above and the description of averageValue being "divided by the number of Pods" at https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/, it sounds like `value` is the *sum* of the metric across all pods, but that's not obvious at all!

* As @liubog2008 notes, it's hard to imagine a scenario where having a target value for the *sum* of a metric across all pods makes any sense.

* The example of using `Value` at https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/ is confusing; it sets a target `Value` of 2000 requests-per-second. But how could this possibly be a thing that makes sense? If scaling a service impacts the total number of requests per second it receives at all, it probably *increases* it (by getting responses to clients faster and thus letting them move on to making their next request faster), so how can scaling a service to try to achieve a target number of requests per second across the service possibly by a coherent thing to do?

/reopen

**Comment by eero-t** [comment]
Oh, this ticket is so right.  AverageValue is both fundamentally different and important, which should be highlighted upfront, not stuffed into a corner as an afterthought.  There are quite lot of (old) tickets related to this functional difference (people not finding AverageValue, and without that, HPA not really working for them at all, as I describe in #109920).

**Comment by pbetkier** [comment]
/reopen
/remove-lifecycle rotten

I don't want to loose this issue, it's still important.

**Comment by hoojos** [comment]
Value and AverageValue also makes my workmates confused，doc and note is unclear. And it's also related with Custom Metrics or  External Metrics how to implemented API.

**Comment by Bikraji** [comment]
What is the final resolution on this?

**Comment by warumponp** [comment]
another explanation.

The **targetValue** usually mean acceptable value that you want the metric to meet. 
**usecase: Average CPU Utilization with targetValue 60%**
for example, if your current metric(Average CPU Utilization) value is about 95%. The autoscaler would increase the number of pods to share the loads until the metric meet the acceptable value(60%)

The **targetAverageValue** usually mean the value that you want a single pod to bare.
**usecase: rabbitmq_message_ready(messages in a queue) with targetAverageValue 1**
for example, if your current number of messages waiting in a queue is 3 and the number of pods is 3. So, a single pod bare one message. The autoscaler would do nothing because the number of workers(pods) satisfy their workloads(messages in a queue)

**Comment by Dentrax** [comment]
Hey, is still still the case? Looking at the docs: https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/ and https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/

I'm still confused on what does `AverageValue` mean or how does get calculated. Can someone please refer me to docs?

Not sure why this issue is closed as not planned.

**Comment by eero-t** [comment]
> Not sure why this issue is closed as not planned.

Me neither, a there are lot of bugs filed about this, see e.g: https://github.com/kubernetes/kubernetes/issues/109920

**Comment by bpinske** [comment]
This is an older issue, but I had once needed to fork Keda to discriminate between Value and AverageValue types a few years ago. This was unpleasant to debug :)

I would have to look into main Kubernetes' code to really understand how the core HPA objects handle this, and I don't feel like it.
But I can tell you that Keda's wrappers DO properly expose the difference between Value and AverageValue now.

[This ](https://github.com/kubernetes/kubernetes/issues/79272#issuecomment-2582022612) explanation is still value to my understanding. of the difference between the types.

Keda now properly supports this on the mainline branch is using that is a viable solution for anybody that gets bit by this.
https://github.com/kedacore/keda/issues/2030

**Comment by eero-t** [comment]
The changes needed to the doc are listed here: https://github.com/kubernetes/kubernetes/issues/109920#issuecomment-1228509170

**Comment by warumponp** [comment]
Let me explain these two formula in some details,

The `Value` formula considers the number of replicas from
`usageRatio = Utillization/TargetUtillization`
This Ratio means proportion of under/overutillize that based on the Target(acceptable value)
Ideally, the Ratio should be 1(60%/60%CPU) and it would be surely acceptable. In this case autoscaler would do nothing.
But sometime something went wrong, the Ratio is 0.5 (30%/60%CPU), it means pods were underutillized and seem unacceptable. So, the autoscaler cut down one half and remians another half amount of pods to make every single pod bare more CPU loads. So the Ratio should be back to 1(60%/60%CPU) and would be nice to back to acceptable state.
So, this following formula that reconsider the reasonable replicas make senses.
`replicaCount = int32(math.Ceil(usageRatio * float64(readyPodCount)))`



The `AverageValue` formula considers the number of replicas directly from `Utillization/TargetAverageUtillization`
Utillization is analogue to amount of current workloads.
TargetAverageUtillization is analogue to reasonable workloads for a single pod to bare.
So, the reasonable number of pods that satisfy the workloads (as above formula)should be 
currentWorkloads/singlePodReasonableWorkloads.
