### ISSUE TITLE
Can't query apiserver from a pod

### ISSUE THREAD

**Issue by dermusikman** [kubernetes/kubernetes#7933]
I'm trying to query the api server from within a pod, and I get a connection reset. I can query the API from outside of the Kubernetes cluster, and `kubectl` works fine. I just can't get it from within a pod.

On the hunch that it may have been a permissions issue, I've tried this with the default apiserver settings (`KUBE_ADMISSION_CONTROL="--admission_control=NamespaceAutoProvision,LimitRanger,ResourceQuota"`) and attempting the AlwaysAdmit setting (`KUBE_ADMISSION_CONTROL="--admission_control=AlwaysAdmit,LimitRanger,ResourceQuota"`). This setting is undocumented, for which I've already created an Issue.

```
[root@my-pod-abcdef /]# echo $KUBERNETES_RO_PORT
tcp://10.250.0.1:80
[root@my-pod-abcdef /]# echo $KUBERNETES_PORT
tcp://10.250.0.2:443
[root@my-pod-abcdef /]# curl -v http://10.250.0.1/api/v1beta3/pods
* About to connect() to 10.250.0.1 port 80 (#0)
*   Trying 10.250.0.1...
* Connected to 10.250.0.1 (10.250.0.1) port 80 (#0)
> GET /api/v1beta3/pods HTTP/1.1
> User-Agent: curl/7.29.0
> Host: 10.250.0.1
> Accept: */*
>
* Recv failure: Connection reset by peer
* Closing connection 0
curl: (56) Recv failure: Connection reset by peer
[root@my-pod-abcdef /]# curl -v https://10.250.0.2/api/v1beta3/pods
* About to connect() to 10.250.0.2 port 443 (#0)
*   Trying 10.250.0.2...
* Connected to 10.250.0.2 (10.250.0.2) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* NSS error -5961 (PR_CONNECT_RESET_ERROR)
* TCP connection reset by peer
* Closing connection 0
curl: (35) TCP connection reset by peer
[root@my-pod-abcdef /]#
```

I'm using 0.15.0, packaged for Fedora 21 (kubernetes-0.15.0-8.fc21.x86_64), and I believe this is [051dd96c542799dfab39184d2a7c8bacf9e88d85f21 upstream](http://pkgs.fedoraproject.org/cgit/kubernetes.git/commit/?h=f21)? I'm using flanneld on AWS.

Please let me know if there is more information I can provide to help in finding a solution for me or the community.

**Comment by goltermann** [comment]
We’re going through old support issues and asking everyone to direct your questions to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes). 

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases. 

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.
