### ISSUE TITLE
Kubelet should pull from alternative registry if main image failed to pull

### ISSUE THREAD

**Issue by icelynjennings** [kubernetes/kubernetes#79389]
**What would you like to be added**:
Inside any Pod, Kubelet should try to pull from an alternative registry if it could not pull a container's image defined in the container's `image` key. This could be due to a DNS error, the target image being deleted or missing, or the registry being under maintenance or down.

**Why is this needed**:
A large amount of Kubernetes clusters are configured to pull images from third-party image registries for their deployments to work. These providers may not always be available, and the health of processes used by projects that depend on them may be degraded during their downtime. This can be especially painful in environments which do not cache their images, or the image cache is pruned periodically. Integration tests will fail if one or more components cannot to pull their images, potentially freezing delivery pipelines until the `image` key is manually edited to point to a new registry, or until the connectivity issue is resolved.

**Comment by icelynjennings** [comment]
One solution would be to extend the PodSpec with a key which takes a list of registry paths to try when the main `image` has failed to pull. I have drafted a KEP for a `fallbackImages` key to be added to the PodSpec which would do that. The KEP is available for viewing and commenting [here](https://docs.google.com/document/d/1ho1SOZ5PzkcKeSpRYVYVOht4pG5758uP_34twOWVabA/edit?usp=sharing), and will be brought up during sig-node meeting on July 2nd.

**Comment by mattjmcnaughton** [comment]
Hi @icelynjennings !

Interesting idea :) I agree with you 100% that filing a KEP with a proposal is a great next step as well as chatting about it at a sig-node meeting. Thanks for doing so :)

**Comment by mattjmcnaughton** [comment]
I think the current method of sharing sigs is via https://github.com/kubernetes/enhancements - would you mind creating a issue/PR for your sig in that repo?

**Comment by kfox1111** [comment]
+1 for a kep at kubernetes/enhancements. Not 100% clear which sig this would belong to though. sig-node seems likely to me.

**Comment by kfox1111** [comment]
Copied from the google doc by request:

Can I add an alternate suggestion?
Could we make alternate images first class citizens with their own kind? It would make mirroring images to easier if you could load up the main pod/deployment/daemonset/whatever, and then upload an object saying what mirrors it can come from instead. that way the writer of the main object and the person deploying can be different. It would make clusters without internet access easier to deal with.

**Comment by justaugustus** [comment]
@icelynjennings -- looks like a great idea! You should definitely file an official KEP for this and raise it with @kubernetes/sig-node-proposals at a meeting. :)

ref: https://docs.google.com/document/d/1ho1SOZ5PzkcKeSpRYVYVOht4pG5758uP_34twOWVabA/edit?usp=drivesdk

**Comment by dchen1107** [comment]
@icelynjennings we missed you earlier at today's SIG Node weekly, and decided to move it to next week's SIG Node. Please let us know if you can join us.

I did read your proposal though, and have a few comments:

In your proposal, you listed two use cases, but both are related to a down registry. If a broken register is the only reason / cause here, shouldn't configuring container runtime with registry mirror can address the issue here? AFAIK, all CRI-compatible container runtimes (CRI-O, docker, containerd) have the feature included. For example, here is the doc describing how to config containerd: https://github.com/containerd/cri/blob/master/docs/registry.md#configure-registry-endpoint
Given an image, containerd tries each mirror one by one until success. 

If that is the only reason to propose such change, I am not sure whether we want to do this at Kubernetes api level for a given complexity.

**Comment by jaypipes** [comment]
I disagree that the containerSpec is the appropriate place to put this information. Instead, I think a more appropriate strategy is to allow kubelet to make use of the OCI image specification's multiple fetch URLs feature:

https://github.com/opencontainers/image-spec/blob/da296dcb1e473a9b4e2d148941d7faa9ac8fea3f/schema/image-index-schema.json#L37-L40

At the end of the day, multiple retrieval locations is a property of the image itself, not the container, which is why I think the better place for this information to live is in the image specification itself. Thoughts?

**Comment by icelynjennings** [comment]
Discussed on sig-node meeting, concluding to close this issue & KEP.

Presented use cases should be met by configuring Kubelet's container runtime - @dchen1107 
An advantage of defining mirroring in the containerSpec would be that Kubelet could provide authentication to registries, whereas setting it in the container runtime means having to provide authentication manually. - @mrunalp

**Comment by mattjmcnaughton** [comment]
Thanks for initiating this convo and helping move it along at sig-node @icelynjennings  :)

**Comment by rajeshkodali** [comment]
@icelynjennings What's the conclusion of the sig-node meeting?

**Comment by icelynjennings** [comment]
Hi @rajeshkodali, the sig-node meeting on July 16 2019 (https://github.com/kubernetes/community/blob/master/sig-node/archive/meeting-notes-2019.md#july-16) concluded that this should be configurable from the container runtime level. I have not researched the issue further since then but took to understand it relates to the Kubernetes CRI (https://kubernetes.io/blog/2016/12/container-runtime-interface-cri-in-kubernetes/) which is developed by sig-node.

**Comment by icelynjennings** [comment]
Should there be renewed interest from sig-node to implement a new container Spec field (a list of alternative images to be used as fallback), I would volunteer to implement. Otherwise, I suspect there are alternative ways to implement such a function outside of the container Spec; such as an operator which tracks the image pull failure events of annotated Pods.
