### ISSUE TITLE
kubelet config file, resolverConfig option not used

### ISSUE THREAD

**Issue by r0bj** [kubernetes/kubernetes#79421]
**What happened**:

When using kubelet config file, `resolverConfig` option is not used by kubelet.

**What you expected to happen**:

kubelet config option `resolverConfig` is used to set resolver configuration file by kubelet.

**How to reproduce it (as minimally and precisely as possible)**:

kubelet config file:
```
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
[...]
resolverConfig: /var/lib/kubelet-config/resolv.conf
```

During kubelet start, default `/etc/resolv.conf` is used:
```
Jun 26 13:02:53 dev-k8s-worker-r3 kubelet[30137]: I0626 13:02:53.550870   30137 flags.go:33] FLAG: --resolv-conf="/etc/resolv.conf"
```

I confirmed it examining `resolv.conf` inside container, content is taken from node `/etc/resolv.conf` instead of `/var/lib/kubelet-config/resolv.conf`.

On the other hand when using deprecated kubelet parameter `--resolv-conf=/var/lib/kubelet-config/resolv.conf` everything works fine, kubelet is using proper path:

```
Jun 26 13:06:49 dev-k8s-worker-r3 kubelet[6501]: I0626 13:06:49.235306    6501 flags.go:33] FLAG: --resolv-conf="/var/lib/kubelet-config/resolv.conf"
```

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:36:19Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: bare-metal
- OS (e.g: `cat /etc/os-release`): Ubuntu 18.04.1
- Kernel (e.g. `uname -a`):
```
Linux dev-k8s-deployer-r1 4.15.0-42-generic #45-Ubuntu SMP Thu Nov 15 19:32:57 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by zouyee** [comment]
`resolvConf` not `resolverConfig `

**Comment by bavarianbidi** [comment]
we still facing the same issue but with the `allowedUnsafeSysctls` option. The `resolverConfig` works on our side.

Cluster is provisioned with kubeadm.

Verified with `1.14.6` and `1.15.3`.

head of the ConfigMap:
```
apiVersion: v1
kind: ConfigMap
data:
  kubelet: |
    apiVersion: kubelet.config.k8s.io/v1beta1
    kind: KubeletConfiguration
    # begin custom values
    address: 0.0.0.0
    allowedUnsafeSysctls:
    - net.ipv4.tcp_keepalive_*
...
```

the revision
```
kubectl get configmap -n kube-system kubelet-config-custom-flavor -n kube-system -o json | jq '.metadata.uid'
"71246442-d43f-11e9-a735-fa163e8415af"
```
of the configmap is used by the node
```
kubectl get nodes kube-node01 -o json | jq '.status.config.active.configMap.uid'
"71246442-d43f-11e9-a735-fa163e8415af"
```

but a  `kubectl get --raw /api/v1/nodes/kube-node01/proxy/configz | jq '.kubeletconfig'` doesn't show me the defined `allowedUnsafeSysctls`.
Other `kubeletConfiguration` values are used.

defining the `unsafe` sysctls via command-line arg `--allowed-unsafe-sysctls 'net.ipv4.tcp_keepalive_*'` and a restart of `kubelet` works.

KubeletConfiguration knows the `allowedUnsafeSysctls` value: https://godoc.org/k8s.io/kubelet/config/v1beta1#KubeletConfiguration

**Comment by bavarianbidi** [comment]
@zouyee

**Comment by brandond** [comment]
This is still present. The issue is caused by a mismatch in the json field name between the internal and public structs:
* https://github.com/kubernetes/kubernetes/blob/d902351c991a68fa76de9935a485afeb1f780c11/pkg/kubelet/apis/config/types.go#L281
https://github.com/kubernetes/kubernetes/blob/d902351c991a68fa76de9935a485afeb1f780c11/staging/src/k8s.io/kubelet/config/v1beta1/types.go#L448

When the kubelet unmarhals the config file as a `kubeletconfiginternal.KubeletConfiguration`, it ends up ignoring the `resolvConf` field due to it having the wrong name in the json, due to lack of `json:"resolvConf,omitempty"` tag on the internal struct .
* https://github.com/kubernetes/kubernetes/blob/d902351c991a68fa76de9935a485afeb1f780c11/cmd/kubelet/app/server.go#L312

**Comment by brandond** [comment]
cc @mattjmcnaughton @mtaufen since I see you were tagged on a misguided previous attempt to fix this.

**Comment by haircommander** [comment]
I understand the motivation here, as the json field doesn't match the CLI name. But since it can be set with `resolvConf` in the kubelet configuration, I think this is okay. Maybe we need a documentation update to make clearer this distinction. What would folks here like us to do about this?

/triage needs-information

**Comment by brandond** [comment]
I would be against a docs fix, it needs to be fixed in the actual struc tags. The current behavior is broken if you try to generate a KubeletConfig from code since the field is incorrectly marshaled. You have to do dumb things like this:

```golang
import (
  kubeletconfig "k8s.io/kubelet/config/v1beta1"
)

func writeKubeletConfig(path string, config *kubeletconfig.KubeletConfiguration) error {
	b, err := yaml.Marshal(config)
	if err != nil {
		return err
	}

	// replace resolvConf with resolverConfig
	// ref: https://github.com/kubernetes/kubernetes/issues/79421
	b = bytes.ReplaceAll(b, []byte("resolvConf: "), []byte("resolverConfig: "))
	return os.WriteFile(filepath.Join(path, "kubelet.conf"), b, 0600)
}
```

**Comment by haircommander** [comment]
I see, yeah that's not great. I don't think the fix will be easy, we may need to create a new kubelet config type, or duplicate the field for a period..

/triage accepted
/priority backlog

**Comment by brandond** [comment]
`k8s.io/kubelet/config/v1beta2` 😬 😬😬

**Comment by brandond** [comment]
> or duplicate the field for a period

That seems like probably the best way to do that. A little ugly but shouldn't be too invasive.

**Comment by thockin** [comment]
We can make a v1beta2 with a different field name or JSON name, but you shouldn't really change it within v1beta1.  Configs are APIs.

Whichever direction we choose, something changes.

**Comment by aojea** [comment]
@thockin I think the problem is here https://github.com/kubernetes/kubernetes/pull/121193/files#diff-5167bfceb87d4b085e13f6f6b01b55cecb505ab9e2f3289dd1fcc437a98d761b

It is not converting the read file to the internal type, hence it ends keeping the external type keys not doing the conversation, and the patch is not doing the expected.

It seems the motivation is to avoid the problem with the default values https://github.com/kubernetes/kubernetes/pull/121193#discussion_r1377881069 , my understanding is that the dropin files are supposed to use only the configured values and leave the empty ones as non-existent.

cc: @liggitt

**Comment by liggitt** [comment]
I'm confused about the issue... I don't think the comment at https://github.com/kubernetes/kubernetes/issues/79421#issuecomment-2248608624 is correct

In general, JSON tags only exist on the versioned types (as intended), and do not need to be identical to the struct field names. Is kubelet config merging doing something unusual that requires internal / versioned types to have json tags or perfectly match the struct fields? If so, that's a bug in that feature and should be fixed, not a bug with this field.

**Comment by liggitt** [comment]
[mergeKubeletConfigurations](https://github.com/kubernetes/kubernetes/blob/master/cmd/kubelet/app/server.go#L317) is buggy... it is JSON-marshaling the internal config (which is not right), then merging with versioned JSON from drop-in files, then decoding that back into the internal config.

All serialized merging has to happen in the same versioned config, to/from versioned config API types, not internal ones.

**Comment by liggitt** [comment]
@brandond, are you only seeing this when using `--config-dir`?

**Comment by liggitt** [comment]
Opened https://github.com/kubernetes/kubernetes/pull/127421 with a fix
