### ISSUE TITLE
taint --overwrite returns "modified" even when no changes were made

### ISSUE THREAD

**Issue by ReSearchITEng** [kubernetes/kubernetes#79470]
**What happened**:
```kubectl taint nodes --selector node-role.kubernetes.io/infra= node-role.kubernetes.io/infra=:NoSchedule --overwrite```

Even if identical taint and effect already exists, it always returns:
```
node/machine04 modified
```

**What you expected to happen**:
return
"node/machine04 not tainted"
or 
"node/machine04 not modified"

**Anything else we need to know?**:
Labels behave differently. When label already exists, and we rerun the labeling with "--overwrite", they return:
"node/machine04 not labeled"
It's expected both would respond in same manner.
Ideally with messages with are aligned:
either both return : "not modified", 
or
"not labeled" and "not tainted".

**Environment**:
- Kubernetes version (use `kubectl version`): 1.15
- Cloud provider or hardware configuration: NA
- OS (e.g: `cat /etc/os-release`): NA
- Kernel (e.g. `uname -a`): NA
- Install tools: kubeadm (https://github.com/ReSearchITEng/kubeadm-playbook)
- Network plugin and version (if this is a network-related bug): NA
- Others: NA

**Comment by jaypipes** [comment]
Interesting bug. I dug into this and it turns out that it's actually the `kubectl label` command that is the problem. The `kubectl taint` command prints "modified" any time overwrite is supplied because underneath the covers, the Node object is indeed modified. The `kubectl label` command ALSO always modifies the underlying Node object whenever `--overwrite` is supplied, however it does not report that it modified the underlying object.

I'm torn on what the correct solution for this should actually be. AFAICT, there are two possible ways to go:

1) Bias towards the commands describing (accurately) whether the object was modified by the operation. This means adding "modified" to the `kubectl label` output. It also means modifying the code for both `kubectl taint` and `kubectl label` to actually NOT perform a Patch or Replace operation when nothing ACTUALLY changes (neither command currently avoids changing an object when no updates were found);

2) Just remove the entire concept of "modified" entirely from the output of `kubectl taint` command. I question what value this string output gives us, especially since ALL calls to `kubectl taint` really do modify the object underneath, regardless of whether `--overwrite` is specified.

I think I'm tending towards 2). Thoughts?
-jay

**Comment by ReSearchITEng** [comment]
Thanks for digging into it.
I am looking from the ansible p.o.v., how should we mark the task: "changed" or "unchanged". From this angle IMO option 1 is ideal, and have the output match what code does. But it means changing quite some code I guess.

**Comment by jaypipes** [comment]
@ReSearchITEng well, if you want Ansible to be accurate, it should always say "changed", since in both labels and taints, the object will always be updated in backing storage (etcd).

I've decorated this issue with sig-cli and will ask for their input on Slack.

**Comment by tedyu** [comment]
I lean towards to option #2 as well.

**Comment by aarongershmanmc** [comment]
Just ran into this today. Thought it was a little weird. Glad to see it's not unexpected though.

**Comment by aarongershmanmc** [comment]
Just ran into this today. Thought it was a little weird. Glad to see it's not unexpected though.
