### ISSUE TITLE
gce-scale-performance fails due to long LIST ReplicationControllers

### ISSUE THREAD

**Issue by oxddr** [kubernetes/kubernetes#79596]
**Which jobs are failing**:
ci-kubernetes-e2e-gce-scale-performance

**Which test(s) are failing**:
load

**Since when has it been failing**:
2019-06-28 however we've observing this behavior earlier as well

**Testgrid link**:
https://k8s-testgrid.appspot.com/sig-scalability-gce#gce-master-scale-performance

**Reason for failure**:
too long latency on `LIST ReplicationController`

**Anything else we need to know**:
@krzysied should know more details

/assign @krzysied

**Comment by alejandrox1** [comment]
Hi all, want to help keep track of this issue
/milestone v1.16
/priority critical-urgent

@krzysied do you have any updates on this?

**Comment by krzysied** [comment]
Currently I'm investigating the issue.

Based on [latency plot](http://perf-dash.k8s.io/#/?jobname=gce-5000Nodes&metriccategoryname=APIServer&metricname=LoadResponsiveness&Resource=replicationcontrollers&Scope=cluster&Subresource=&Verb=LIST) I wouldn't say this issue is critical/urgent - it has potential to make test flaky but not to break it.

The problem with replication controller "started" after fixing the prometheus metrics. It fixed displaying percentiles of metrics buckets with not many samples and our rc list graph looked like this https://github.com/kubernetes/kubernetes/issues/78111#issuecomment-493975605. The latency didn't increased in k8s tests - we started to display it properly. IMHO it's not a regression.

I've done a debugging session, it looks like the problem is related to networking. Next goal is to determine whether there is a problem with k8s code, system or infrastructure.

**Comment by scottilee** [comment]
@krzysied Fortunately the job has been green for a while but I wanted to ping you to see if you had found out the root cause of the issue?

**Comment by oxddr** [comment]
There were two things in here

1) For cluster-scoped latencies we used a limit of 10s, while the actual SLO for this API calls is 30s. This has been fixed in https://github.com/kubernetes/perf-tests/pull/673
2) clusterloader2 which was sender of those API calls were on the other side of the world IIRC, this can add up to the observed latency

/close
