### ISSUE TITLE
Pod securityContext should support options supported both by PodSecurityPolicy & container securityContext

### ISSUE THREAD

**Issue by eero-t** [kubernetes/kubernetes#79602]
**What would you like to be added**:

I would expect the same security options to be available in Pod securityContext as what are in *both* PodSecurityPolicy and container securityContext.  Specifically, adding/removing capabilities and privilege escalation.

**Why is this needed**:

Typing same thing to all container securityContexts is tiresome and error prone when one could just set them once in Pod level securityContext.

PS. I know I could use PodSecurityPolicy, but I don't see any good reason why Pod securityContext is specifically limited like this.

**Comment by eero-t** [comment]
> /priority awaiting-more-evidence

What kind of evidence?

**Comment by liggitt** [comment]
That the benefits outweigh the complexity introduced by additional API fields and multi-level precedence. Most of the fields that exist in both levels started at the pod level and were added to the container level because more granularity was required. Going the other direction for convenience isn't as compelling.

/sig node
