### ISSUE TITLE
Pod should not be pending if there is a fundamental error (e.g. Image cannot be found)

### ISSUE THREAD

**Issue by aronchick** [kubernetes/kubernetes#7960]
Repro:
- Create an RC.yml with an unknown image
- Attempt to create RC with Kubectl

Expected:
- Error/alert that image cannot be found

Actual:
- Indicates "pending"

Generally speaking, it's best to not have a term overloaded in this way - "pending" means things are going on properly, and all will be right soon. "error" means nothing is going to happen unless you fix it.

**Comment by yujuhong** [comment]
@aronchick, "pending" means that kubelet is still trying to achieve the desired state -- it's retrying repeatedly to pull the image. In the cases where kubelet is certain that it's *not* going to be able run the pod, it would outright set the state of the pod to "failed". Examples are host port conflict or insufficient capacity.

I agree that "pending" may be a bit confusing at times, but unless kubelet is certain that the error is not transient, it'd continue trying. To add more clarity, #7981 includes the pulling failure reason in `kubectl get pods` so that it'd be clear that some containers are failing.

**Comment by aronchick** [comment]
Agreed - we need to improve surfacing the error here.

**Comment by aabed** [comment]
but won't that make kubectl block until it makes sure everything went well, otherwise report error?
