### ISSUE TITLE
Multiple GCE test suites in master-blocking are failing

### ISSUE THREAD

**Issue by alenkacz** [kubernetes/kubernetes#79652]
**Which jobs are failing**:
gce-cos-master-slow
gce-cos-master-alpha-features
gce-cos-master-ingress
gce-cos-master-default

**Which test(s) are failing**:
It fails during the test suite start up

**Since when has it been failing**:
01:31 PDT today

**Testgrid link**:
https://k8s-testgrid.appspot.com/sig-release-master-blocking#gce-cos-master-slow
https://k8s-testgrid.appspot.com/sig-release-master-blocking#gce-cos-master-alpha-features
https://k8s-testgrid.appspot.com/sig-release-master-blocking#gce-cos-master-ingress
https://k8s-testgrid.appspot.com/sig-release-master-blocking#gce-cos-master-default

**Reason for failure**:
```
Downloading kubernetes release v1.16.0-alpha.0.1787+b3c6e2189576c9
I0702 09:12:50.430]   from https://storage.googleapis.com/kubernetes-release-dev/ci/v1.16.0-alpha.0.1787+b3c6e2189576c9/kubernetes.tar.gz
I0702 09:12:50.430]   to /workspace/kubernetes.tar.gz
W0702 09:12:52.863] 2019/07/02 09:12:52 main.go:316: Something went wrong: failed to acquire k8s binaries: U=https://storage.googleapis.com/kubernetes-release-dev/ci R=v1.16.0-alpha.0.1787+b3c6e2189576c9 get-kube.sh failed: error during ./get-kube.sh: exit status 22
```

**Anything else we need to know**:

/milestone v1.16
/kind failing-test
/priority critical-urgent
CC @alejandrox1 @jimangel @Verolop

**Comment by oxddr** [comment]
https://k8s-testgrid.appspot.com/sig-scalability-gce#gce-cos-master-scalability-100 is also affected. 

I've checked some latest GCS buckets and they are missing *tar.gz packages.

**Comment by oxddr** [comment]
I had a brief look at [ci-kubernetes-build](https://prow.k8s.io/?job=ci-kubernetes-build) and it seems, that for a reason tars are not created.
```
W0702 12:10:24.696] tar: *: Cannot stat: No such file or directory
W0702 12:10:24.697] tar: Exiting with failure status due to previous errors
W0702 12:10:24.697] tar: /go/src/k8s.io/kubernetes/_output/release-stage/client/-- darwin-386 darwin-amd64 linux-386 linux-amd64 linux-arm linux-arm64 linux-ppc64le linux-s390x windows-386 windows-amd64/kubernetes/client/bin: Cannot open: No such file or directory
W0702 12:10:24.697] tar: Error is not recoverable: exiting now
W0702 12:10:24.697] tar: This does not look like a tar archive
W0702 12:10:24.697] tar: Exiting with failure status due to previous errors
```

On the other hand ci/latest.txt file is created. This file is used by get-kube.sh script to determine Kubernetes version to run tests with. 
```
I0702 12:10:37.352] push-build.sh::release::gcs::publish(): /google-cloud-sdk/bin/gsutil acl ch -R -g all:R gs://kubernetes-release-dev/ci/latest.txt
```

I think there are two thing to do:
1. fix ci-kubernetes-build so it start to create tars, so we can stop the bleeding
2. fix ci-kubernetes-build so it fails the job and doesn't write latest.txt, when tars (or any other piece of build script) fails

**Comment by justaugustus** [comment]
I _think_ we're unblocked with https://github.com/kubernetes/release/issues/797 merged.

**Comment by dims** [comment]
One more - https://github.com/kubernetes/release/pull/800

**Comment by justaugustus** [comment]
This was caused by changes to the build/release tooling, which have since been reverted (https://github.com/kubernetes/release/pull/814).

Here are the aforementioned jobs and their first green run of the `Extract` test since the k/release revert:
- https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-slow/1146183904512708613
- https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-alpha-features/1146178619962298370
- https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-ingress/1146182898454368257
- https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce/1146183904512708612
- https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/1146182394634571776

Closing this out, but continued discussion on tooling/process improvement is happening here: https://github.com/kubernetes/release/issues/816
/close
/assign
