### ISSUE TITLE
You should be able to get logs for everything in a namespace

### ISSUE THREAD

**Issue by ORESoftware** [kubernetes/kubernetes#79676]
This should work as expected:

```bash
 kubectl logs --namespace=foo
```

**Comment by almiche** [comment]
What would be the purpose of doing this I'm curious. This seems similar to the [issue](https://github.com/kubernetes/kubernetes/issues/79678) you created previously about --all-namespaces being the default on all commands. The problem with this is when you run a large scale cluster with dozens of k8s resources within the same cluster getting all logs dumped at the same time doesn't really serve a purpose in my opinion.

**Comment by ORESoftware** [comment]
so what command do you use to get all the logs for the pods in a namespace etc?

**Comment by almiche** [comment]
So the logs command requires a resource to be specified one option would be to do the following `kubectl logs deployment/<deployment> -n <namespace>` this would return the logs of all the pods within a given deployment. There is also a `all-containers` option for when fetching the logs of a given pod which is available.

 For reference from the source code:
>"the argument must be RESOURCE/NAME"

**Comment by neolit123** [comment]
/close
please re-open if you think the issue is still viable.

**Comment by josecrosa** [comment]
I would like this feature as a test engineer that regularly looks at logs from failed CICD runs where the root cause could be *anywhere* in the pod logs in a namespace.

**Comment by adamacosta** [comment]
Use case here is running any application similar to Gitlab in Kubernetes. The full application is not one deployment. It's several deployments plus a statefulset (possible several if you opt for node-local storage instead of object storage to back the registry). They provide a correlation ID for each request that is used to search logs across all Gitlab components to find the root of a problem, which works well enough when you're doing an Omnibus server installation and all the logs are in a single directory on the server. It doesn't work so well when it's in Kubernetes and there is no simple way to view all logs across multiple controller kinds that are all part of the same application.

**Comment by EmileSonneveld** [comment]
I used this command:
`kubectl get pods -n my-namespace -o name | xargs -I{} kubectl logs -n my-namespace --all-containers -f {}`

**Comment by rkitindi-kr** [comment]
@EmileSonneveld your command collected logs from first pod in a list, can you fix it?

**Comment by rkitindi-kr** [comment]
> True, I removed the `-f` so it prints all

I thought we need -f if we want to stream, what's alternative in this context?

**Comment by EmileSonneveld** [comment]
I don't know how to steam multiple logs at the same time in a one-liner. It might become a mess quickly too.
The xargs command would just print and exit
