### ISSUE TITLE
Kubectl takes a long time to execute

### ISSUE THREAD

**Issue by timyinshi** [kubernetes/kubernetes#79691]
/kind bug
/sig cli

**What happened**:
When I executed the kubectl get pod command in the k8s cluster, I found that the first execution time was very long, and it was very fast after the second execution. May I ask why? Is there any configuration of apiserver that can solve this problem?
my command is:
kubectl get pod -n kube-system

**What you expected to happen**:
I want to be able to quickly return results when I execute kubectl.

**How to reproduce it (as minimally and precisely as possible)**:
my command is:
kubectl get pod -n kube-system

**Anything else we need to know?**:
my cluster has 23 nodes,3master,20 slave

**Environment**:
- Kubernetes version (use `kubectl version`):1.12.1
- OS (e.g: `cat /etc/os-release`):ubuntu 16.04.4 LTS (Xenial Xerus)
- Kernel (e.g. `uname -a`):4.4.0-116-generic
- Network plugin and version (if this is a network-related bug):calico 3.4.0

**Comment by alanjcastonguay** [comment]
The first=slow one is populating a resource cache, and the second=fast one benefits from that cache. Kubectl doesn't natively know that "pod" exists or what the URL routes for a pod are; it asks the server for a list of resources. Look for the cache directories in `~/.kube/`.

Delete the cache. Run `kubectl get pods -v=6` twice. See second one makes far fewer http requests. 

Run `kubectl get resourcenotexisting -v=6` and see that kubectl recreates the cache, since it has no knowledge of a resourcenotexisting type and the server may have recently gotten one that needs to be discovered. That's the same reason typos `kubectl get podds foo` are slow.

See also #47977

**Comment by CamelCaseNotation** [comment]
@alanjcastonguay is there any way to point to a pre-existing `.kube/cache/discovery` entry even if the server value has changed?

**Comment by Chrislevi** [comment]
Happens to me aswell, with  `-v=99` I can see different output when I remove the cache and re run.. but it seems like its still having these long pauses afterwards

**Comment by karthikeayan** [comment]
I found some kubectl process as zombie in my jumpbox instance, cpu and network were constantly high... once i killed those zombie processes all back to normal again..

**Comment by timyinshi** [comment]
i have two methods about the problem:
1、change etcd storage to SSD type for increasing etcd's processing speed
2、Increase the CPU of apiserver for increasing the processing speed of apiserver
