### ISSUE TITLE
eviction request make a performance spike to etcd

### ISSUE THREAD

**Issue by ricky1993** [kubernetes/kubernetes#79697]
**What happened**:
We have about 8000 pdbs in our cluster. When we call several eviction requests at the same time, etcd will meet a performance spike.
**What you expected to happen**:
eviction request read pdbs from apiserver cache
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by yue9944882** [comment]
/sig scalability
/cc @wojtek-t 

throttling evictions at server-side may be a better fix i presume

**Comment by ricky1993** [comment]
> /sig scalability
> /cc @wojtek-t
> 
> throttling evictions at server-side may be a better fix i presume

We use eviction to auto migrate pods. If throttling eviction requests, it will make migration latency too long. 
I am not sure if list without rv by designed (get pdb consistently) or not (just forget to add rv).

**Comment by wojtek-t** [comment]
What does eviction do (I can't remember from the top of my head)? Would you be able to quickly point me to the code?

**Comment by ricky1993** [comment]
> What does eviction do (I can't remember from the top of my head)? Would you be able to quickly point me to the code?

pkg/registry/core/pod/storage/eviction.go:104 Create
create a eviction will list all pdbs, make sure eviction the pod won't break any pdb. If check passed, it will create the eviction, otherwise it will return 429 to reject.

**Comment by wojtek-t** [comment]
Thanks - so this is what is problematic:
https://github.com/kubernetes/kubernetes/blob/master/pkg/registry/core/pod/storage/eviction.go#L236

So what you're saying is that you have 8000 PDBs in a single namespace? [because we only list pdbs from pod`s namespace].

> I am not sure if list without rv by designed (get pdb consistently) or not (just forget to add rv).

I'm we should list from etcd, because otherwise we risk using old version of pdb (e.g.we are allowed to evict only 1 pod, and we just did it, but that wasn't yet propagated to apiserver cache and we would evict another pod).

My personal guess would be that the problem may not really be number of PDB, but amount of concurrent requests touching the same pdb - because that would be resulting in conflicts and retrying them in:
https://github.com/kubernetes/kubernetes/blob/master/pkg/registry/core/pod/storage/eviction.go#L136

I'm not sure we can do much about it (at least I don't see any immediate low-hanging fruit).

**Comment by wojtek-t** [comment]
@kubernetes/sig-apps-bugs

**Comment by ricky1993** [comment]
> Thanks - so this is what is problematic:
> https://github.com/kubernetes/kubernetes/blob/master/pkg/registry/core/pod/storage/eviction.go#L236
> 
> So what you're saying is that you have 8000 PDBs in a single namespace? [because we only list pdbs from pod`s namespace].
> 
> > I am not sure if list without rv by designed (get pdb consistently) or not (just forget to add rv).
> 
> I'm we should list from etcd, because otherwise we risk using old version of pdb (e.g.we are allowed to evict only 1 pod, and we just did it, but that wasn't yet propagated to apiserver cache and we would evict another pod).
> 
> My personal guess would be that the problem may not really be number of PDB, but amount of concurrent requests touching the same pdb - because that would be resulting in conflicts and retrying them in:
> https://github.com/kubernetes/kubernetes/blob/master/pkg/registry/core/pod/storage/eviction.go#L136
> 
> I'm not sure we can do much about it (at least I don't see any immediate low-hanging fruit).

Thanks a lot for your reply.
How about retrying conflict update pdb, instead of re-listing all pdbs?
https://github.com/kubernetes/kubernetes/blob/75a39b70072954634169f7bc0731795019d04bac/pkg/registry/core/pod/storage/eviction.go#L223

**Comment by wojtek-t** [comment]
> Thanks a lot for your reply.
How about retrying conflict update pdb, instead of re-listing all pdbs?

Hmm - I'm not sure I understand.
Ohh, but I know what else we can do (maybe that's what you had on your mind).

In case of conflict, instead of relisting all PDBs, we should simply GET the current version of that PDB (we already know that there is exactly one which we are supposed to use).
That would reduce the cost of retries significantly.

@ricky1993 - would you be able to take a look into it and prepare a PR? I'm happy to review it.

**Comment by ricky1993** [comment]
@wojtek-t  - That's what I mean. 
I will take a look and send a PR in a few days.

**Comment by wojtek-t** [comment]
@ricky1993 - great!
Please ping me on slack if I won't be responding to it.

**Comment by yue9944882** [comment]
alternatively, will pagination probably help ease the pressure? it'll skip the cache tho but presents us from a "spike"..

**Comment by ricky1993** [comment]
> alternatively, will pagination probably help ease the pressure? it'll skip the cache tho but relaxes the "spike"..

Does pagination mean range key prefix with limit?
