### ISSUE TITLE
Consider ClusterIP traffic routed to a node (from outside the cluster) as "external" for local-only

### ISSUE THREAD

**Issue by smekkley** [kubernetes/kubernetes#79866]
Some what re-opening the issue #10921 

With solution like the following that expose ClusterIP to outside the cluster, it would be very beneficial if there was an option to enable pods to see the source IP address instead of the node address.
https://www.projectcalico.org/kubernetes-service-ip-route-advertisement/

In an environment with type:LoadBalancer available, people can use externalTrafficPolicy: Local, but on-premise solutions shouldn't have to deploy loadbalancer agent to expose the service to internal resources.

**Comment by smekkley** [comment]
@kubernetes/network

**Comment by smekkley** [comment]
#67202 seems like the same issue. Kube proxy having no ability to disable SNATing causing a problem.  But it was closed without being solved.

**Comment by smekkley** [comment]
With `--cluster-cidr=0.0.0.0/0` , I see the original source IP from the pod. But then on the return traffic, it doesn't do SNAT, so the client never gets the response from ClusterIP, but only from the pod IP address. I'm not sure if this is something that should be solved with network plugin or kube-proxy.

**Comment by dgunjetti** [comment]
which network plugin are u using? can we track down to iptables rule that does SNAT.

**Comment by thockin** [comment]
In order for traffic policy = local to work, you'd have to advertise ONLY routes to nodes that actually have backends for that service.  Instead of advertising the whole range for all nodes, it would have to be much more dynamic.

That said, I think we could maybe consider "routed to this node" as "external", if we can express it cleanly.  For example, if we could assume an interface prefix, we could say "all traffic from interfaces other than veth-* is external".  today we use the cluster CIDR for somethign similar but that was always a hack.

I'll retitle this and file it as a feature

**Comment by caseydavenport** [comment]
> In order for traffic policy = local to work, you'd have to advertise ONLY routes to nodes that actually have backends for that service. Instead of advertising the whole range for all nodes, it would have to be much more dynamic

Yep. The Calico implementation linked above does actually do this dynamic advertising or /32 routes for services with `externalTrafficPolicy: Local` as do others like kube-router, I think.

However, right now the Kubernetes API validates against setting `externalTrafficPolicy: Local` on services with `type: ClusterIP` (which of course makes sense given the original semantics of each).

**Comment by thockin** [comment]
If someone wants to tackle this (specifically how to tell local vs remote
traffic apart, preferably WITHOUT using cluster CIDR) it might be workable.

This is part of why I have advocated for a more holistic network driver
model which includes both kube-proxy and pod networking.

**Comment by smekkley** [comment]
I guess this is impossible from kube-proxy side?

By setting --cluster-cidr=0.0.0.0/0, you can see the original IP from the pod, but because it doesn't do SNAT, network plugin doesn't know anything about Cluster IP, so there is no way to SNAT with ClusterIP on return traffic from the network plugin side.

Kube-proxy needs to somehow forward the traffic to a pod without SNATing, then with the return traffic to the client, it needs to SNAT with the cluster IP, which sounds also impossible from kube-proxy side because kube-proxy doesn't know anything about the return traffic destined to the original client ip from the pod.

I wonder how type: Loadbalancer is handling this when it's set to externaltrafficpolicy to local.

**Comment by thockin** [comment]
> Kube-proxy needs to somehow forward the traffic to a pod without SNATing, then with the return traffic to the client, it needs to SNAT with the cluster IP

I think this is plain-old conntrack.  

The setup is this:

1) Traffic from pods on "this" node to a service ClusterIP never needs MASQ, because return path comes to the same place, so the DNAT connection tracking is reversed correctly.

2) Traffic from "other" machines to a service ClusterIP routed "through" this node *might* need MASQ. 

2a) Traffic from "other" machines to a service ClusterIP routed "through" this node to a backend NOT ON this node always needs MASQ, to ensure that we can do the reverse part of the DNAT connection tracking. 

2b) Traffic from "other" machines to a service ClusterIP routed "through" this node to a backend ON this node never needs MASQ.

2c) Today we assume "might" means "always".

What we want is to enable (2b) to bypass MASQ.

The problem is that it's not trivial to know the difference between "traffic from pods on this node" and "traffic from other machines routed through this node".

Today we use the cluster CIDR for that.  It's kind of a hack and assumes that no traffic from any node will be routed through another node.  Pretty safe assumption.  The hacky part is that each node has to be aware of the cluster CIDR which means
  a) updating that CIDR is extra hard
  b) allowing multiple CIDRs is hard

I'd very much like to be able to get rid of the idea of a "cluster CIDR" and let clusters become sets of smaller, disjoint IP ranges.  to that end, I do not want to add more stuff depending on cluster CIDR.

Depending on the per-node CIDR is better, but still hacky because even that makes too many assumptions about IPAM that I want to break.

Depending on a bridge (as we do in kube-proxy in at least one place - grep for physdev-is-in) is hacky because Calico and many other plugins don't use bridges.

Depending on a hardcoded interface prefix is no good because we don't mandate that prefix, though maybe we should have.

What I need is a way to determine if the incoming traffic came from "this machine" or not.  But I don't really know how to express that.

Help wanted.

@satyasm who has put some thought into this.

**Comment by smekkley** [comment]
Oh, yes. I was only thinking in terms of SNAT.

Now I see the problem as well. I thank you very much for the detailed explanation.

In this case I have to agree that if we had a holistic network plugin would be better because of the assumption we might be forced to make to solve this issue.

**Comment by thockin** [comment]
I'm really hoping for a great "why not do this, you moron" sort of
solution, but I am trying to be sanguine :)

I might be open to a set of configs, e.g.
`--detect-external-traffic=netdev-prefix=<nic-prefix>` vs
`--detect-external-traffic=cluster-cidr=<cluster-cidr>` or something that
specifies different ways of testing traffic locality.

**Comment by smekkley** [comment]
I've been trying to read the code.
There is even a nice comment in `pkg/proxy/iptables/proxier.go`
`#867				// If/when we support "Local" policy for VIPs, we should update this.`

**Comment by aojea** [comment]
> Depending on a hardcoded interface prefix is no good because we don't mandate that prefix, though maybe we should have.

@thockin I've been playing with this idea of using interface prefixes instead of the cluster-cidr.
I have a working prototype [that is able to differentiate internal and external traffic using a prefix obtained automatically parsing the containers interface names](https://github.com/kubernetes/kubernetes/compare/master...aojea:proxyExternal?expand=1)

The good things are that as you are pointing out you don't need to be aware anymore of the cluster-CIDR.

The problem that I see with the prefix is:
* if you have no-containers interfaces that can overlap with the containers prefix
* if the network plugins are not consistent with the interface naming that makes impossible obtain a prefix

Do you think that those problems can be avoided?

**Comment by maxstr** [comment]
Assuming we allow `externalTrafficPolicy` on clusterIPs can we assume that if `externalTrafficPolicy: local` (or whatever equivalent is determined) is set for a clusterIP that we can skip MASQ for that service and require whatever is advertising the IPs to handle the routing correctly? 

I also feel like exposing cluster VIPs outside the cluster is probably the wrong abstraction and should probably be done with `externallP`, but that's a discussion for a different thread.

**Comment by caseydavenport** [comment]
Relevant KEP was merged for this here: https://github.com/kubernetes/enhancements/pull/1354

/remove-lifecycle rotten

**Comment by smekkley** [comment]
Wow, amazing work. Thank you guys, all.
