### ISSUE TITLE
kube-controller-manager memory/cpu increased after switching from RCs to Deployments

### ISSUE THREAD

**Issue by krzysied** [kubernetes/kubernetes#79898]
**Which jobs are failing**:
ci-kubernetes-e2e-gci-gce-scalability

**Which test(s) are failing**:
Density test

**Since when has it been failing**:
07/08/2019 08:45 PDT

**Testgrid link**:
https://testgrid.k8s.io/sig-scalability-gce#gce-cos-master-scalability-100

**Reason for failure**:
Kube-controller-manager cup usage increased.

**Anything else we need to know**:

**Comment by krzysied** [comment]
This could be a result of [changing Rcs to deployments](https://github.com/kubernetes/perf-tests/pull/616). Probably we should bump up cpu limit for kube-controller-manager if handling deployment is intended to be more cpu than handling RCs.
I will also look if there were no k8s changes that time (apart from documentation/comments changes)

**Comment by wojtek-t** [comment]
Yeah - I'm pretty sure change do deployment will increase cpu-usage.Though, looking into perf-dash the size of increase is quite surprising...

**Comment by mm4tt** [comment]
for the time of investigation I'll raise the limits, this should deflake the presubmits

**Comment by mm4tt** [comment]
/retitle kube-controller-manager memory/cpu increased after switching from RCs to Deployments

**Comment by mm4tt** [comment]
Density 5K test:

Baseline (RCs):
![RtNn3eOEjzN](https://user-images.githubusercontent.com/2604887/60877666-88e6a600-a23e-11e9-9a2e-ca4435c6b08c.png)

Run with deployments:
![4Jb93J4vzZV](https://user-images.githubusercontent.com/2604887/60877720-ab78bf00-a23e-11e9-8d1a-accbdb322add.png)

Looks like memory went up, which I think is reasonable given that now there are additional Deployment objects (in addition to ReplicaSets), so of the CPU increase might be due to garbage collection, but there might be something more there.

**Comment by mm4tt** [comment]
I run density test on 100 node cluster with prometheus enabled, the increase in CPU is significant when using Deployments:
![LF70YfW7EkD (1)](https://user-images.githubusercontent.com/2604887/60892512-88aad280-a25f-11e9-88b1-11813f42330c.png)

**Comment by mm4tt** [comment]
Once https://github.com/kubernetes/kubernetes/pull/79937 gets merged we should wait ~1 day and then check perf-dash and see if it'll be good to lower the thresholds.

**Comment by mm4tt** [comment]
With the https://github.com/kubernetes/kubernetes/pull/79937 the memory is almost back to what it was before switching to Deployments:
![JfALdwTU58t](https://user-images.githubusercontent.com/2604887/61126507-e54efd00-a4ac-11e9-9f18-3aafdcc71f76.png)

The CPU went down, but it still visible higher than what it was for RCs:
![L9H1WAxYokp](https://user-images.githubusercontent.com/2604887/61126569-17f8f580-a4ad-11e9-991b-8301bb99cc1b.png)

I'll take a look in the next week to see whether this is satisfactory or whether we should do something about it.

**Comment by mm4tt** [comment]
Summarizing,

With the https://github.com/kubernetes/kubernetes/pull/79937, GCE 5K looks very similar to what it was before (with RCs instead of Deployments):

![UaNJjNUN0SV](https://user-images.githubusercontent.com/2604887/61217428-f9deff80-a70f-11e9-8742-fc3a15f3501a.png)

![mwGKNve5ZDL](https://user-images.githubusercontent.com/2604887/61217446-01060d80-a710-11e9-9648-4db4999e5043.png)


When it comes to gce-100 there is a visible difference when it comes to CPU (I guess that's the overhead introduced by the deployment controller which is much more visible in the small clusters), and a minimal memory increase:

![aX401KvC6Kq](https://user-images.githubusercontent.com/2604887/61217693-8be70800-a710-11e9-88f9-54aefd230274.png)
![4RfbmYAedEU](https://user-images.githubusercontent.com/2604887/61217695-8c7f9e80-a710-11e9-925e-3eb59b963ce1.png)


I propose to change the gce-100 cpu threshold to 1.5 (currently 2.0 was 1.2) and close this issue.
The increase in CPU usage is unfortunate, but I'm afraid there isn't much we can do, the deployment controller is just more complex than RC controller, in fact it's RC controller + additional controller for managing deployment objects so the increase is inevitable.

Will send a PR to do that shortly.
