### ISSUE TITLE
k8s 1.14.4 rpms not available in yum repo

### ISSUE THREAD

**Issue by robertrbruno** [kubernetes/kubernetes#79935]
Hopefully a simple answer.  I saw k8s 1.14.4 was released yesterday but still no rpms showing up in the repo index.  Any info on when they should show up would be great.  

Any chance this can be part of the automated build process so yum is updated when the official release happens?

**Comment by robertrbruno** [comment]
@kubernetes/sig-release-bug

**Comment by robertrbruno** [comment]
I did notice the rpms seemed to have just showed up!  Is a delay normal?  Just wanted to set expectations.

**Comment by justaugustus** [comment]
@robertrbruno -- Yep! We have a separate process for staging and releasing the artifacts to GitHub. Once that happens, we build the debs/rpms, so there's a bit of a delay.

We always wait until the debs/rpms are built to [announce to the community](https://groups.google.com/d/topic/kubernetes-announce/rk9Ev9jWuuI/discussion) though, so that's the signal that everything is good to go (for future reference). :)

Enjoy!
/milestone v1.16
/priority important-soon
/close
