### ISSUE TITLE
e2e test "RuntimeClass should run a Pod" only supports docker runtime

### ISSUE THREAD

**Issue by aojea** [kubernetes/kubernetes#80098]
**What would you like to be added**:

The test should support more runtimes, currently only support `docker` and `test-handler` handlers

https://github.com/kubernetes/kubernetes/blob/b8ba75bcd9d3be31e4b53105b2cc67538c9c2d1b/test/e2e/common/runtimeclass.go#L64

**Why is this needed**:

The test is not working with kind that is using containerd 

xref: https://github.com/kubernetes-sigs/kind/pull/701

**Comment by BenTheElder** [comment]
I don't think that's true?https://github.com/kubernetes/kubernetes/blob/b8ba75bcd9d3be31e4b53105b2cc67538c9c2d1b/test/e2e/common/runtimeclass.go#L63

This is definitely
/sig node

**Comment by BenTheElder** [comment]
See:
https://github.com/kubernetes/kubernetes/blob/416a717effeb3b0ff69e3363b15a9f6570a1a4a1/test/e2e/common/runtimeclass.go#L39-L44

https://github.com/kubernetes/test-infra/blob/e4e1d0529df0ff5de95497fd9d251d8defaf82e8/jobs/e2e_node/containerd/config.toml#L19-L21

I think the issue here is that the test requires that you've already configured such a handler or no-ops on docker. This should be documented or handled differently.

Cc @yujuhong @random-liu

**Comment by dims** [comment]
@BenTheElder @aojea please see https://github.com/kubernetes/kubernetes/issues/78249 as well

**Comment by BenTheElder** [comment]
we ultimately just added this magical runtime handler to kind's node configurations, but this shouldn't be a thing, and definitely isn't documented. I'm not sure where we'd document it or what a realistic next step would be.
