### ISSUE TITLE
debian hyperkube images affected by CVE-2019-1543

### ISSUE THREAD

**Issue by cjschaef** [kubernetes/kubernetes#80374]
**What happened**: Debian hyperkube images built for the `v1.12`, `v1.13`, `v1.14`, and `v1.15` releases contain `openssl` security vulnerability [CVE-2019-1543](https://nvd.nist.gov/vuln/detail/CVE-2019-1543)

**What you expected to happen**: Latest debian hyperkube images built using community automation should have patches to address existing `openssl` security vulnerability.

**How to reproduce it (as minimally and precisely as possible)**: Build debian hyperkube images for the `v1.12`, `v1.13`, `v1.14`, and `v1.15` releases and check the vulnerable version of `openssl` that is installed within the images.

**Anything else we need to know?:**

**Environment:**

- Kubernetes version (use kubectl version): debian hyperkube images `v1.12`, `v1.13`, `v1.14`, and `v1.15`
- Cloud provider or hardware configuration: not applicable
- OS (e.g. from /etc/os-release): `Debian GNU/Linux 9 (stretch)`
- Kernel (e.g. uname -a): `Linux df8a35282637 3.10.0-862.14.4.el7.x86_64 #1 SMP Fri Sep 21 09:07:21 UTC 2018 x86_64 GNU/Linux`
- Install tools: [build/release.sh](https://github.com/kubernetes/kubernetes/blob/master/build/release.sh)
- Others:

/kind bug
/sig release

**Comment by justaugustus** [comment]
@kubernetes/release-engineering -- can you investigate?

/priority critical-urgent
/milestone v1.16
/area release-eng

**Comment by dims** [comment]
`Due to the limited scope of affected deployments this has been assessed as low severity and therefore we are not creating new releases at this time` (note from https://nvd.nist.gov/vuln/detail/CVE-2019-1543)

Also, not sure if the code path for ChaCha20-Poly1305 is triggered from anywhere when hyperkube is used ...

**Comment by xmudrii** [comment]
@dims Hello! I'm the bug triage lead for the 1.16 release cycle and considering this issue is tagged for 1.16, I'd like to check its status. The code freeze is starting on August 29th EOD PST (about 5 days from now) and once the code freeze starts, only release-blocking changes will be considered to be merged. Is this issue still planned to be fixed for the 1.16 release?

**Comment by justaugustus** [comment]
Closing in favor of https://github.com/kubernetes/kubernetes/issues/71719.
/close
