### ISSUE TITLE
[Failing Test] openstack conformance is failing in master-informing

### ISSUE THREAD

**Issue by droslean** [kubernetes/kubernetes#80401]
**Which jobs are failing**:
` ci-cloud-provider-openstack-acceptance-test-e2e-conformance`

**Which test(s) are failing**:
`Overall` [spyglass](https://prow.k8s.io/view/gcs/k8s-conformance-openstack/periodic-logs/ci-cloud-provider-openstack-acceptance-test-e2e-conformance/1563337047)

**Since when has it been failing**:
Since 16/7

**Testgrid link**:
https://testgrid.k8s.io/sig-release-master-informing#Conformance%20-%20OpenStack

**Reason for failure**:
```

• Failure [947.618 seconds]
[sig-autoscaling] [HPA] Horizontal pod autoscaling (scale resource: CPU)
/home/zuul/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/autoscaling/framework.go:23
  [sig-autoscaling] ReplicationController light
  /home/zuul/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/autoscaling/framework.go:23
    should scale from 1 pod to 2 pods [Conformance] [It]
    /home/zuul/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:698
     timeout waiting 15m0s for 2 replicas
    Unexpected error:
        <*errors.errorString | 0xc000279cd0>: {
            s: "timed out waiting for the condition",
        }
        timed out waiting for the condition
    occurred
     /home/zuul/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/autoscaling/horizontal_pod_autoscaling.go:131
```

/kind failing-test
/priority important-soon
/milestone v1.16
/cc @kubernetes/sig-openstack-test-failures

/sig autoscaling

**Comment by alejandrox1** [comment]
This has been resolved.
The underlying cause was that pod autoscaling was momentarily promoted to the conformance suite in https://github.com/kubernetes/kubernetes/pull/79954 but it was later reverted in https://github.com/kubernetes/kubernetes/pull/80261 and thus fixed.
The issue is that pod autoscaling (hpa) requires metrics server which is an optional addon (probably not installed in the clusters used by this job).
/close
