### ISSUE TITLE
Treat all static pods as critical regardless of their priority

### ISSUE THREAD

**Issue by bsalamat** [kubernetes/kubernetes#80489]
A static pods is created directly on a node and then a mirror pod object is created for it on the API server. When a static pods is created on a node, there is no mirror pod yet on the API server.
Priority of pods are resolved from `PodSpec.PriorityClassName` to the integer value of priority by an API server admission plugin. So, when a static pods is created and goes through Kubelet admission, it does not have an integer priority. If the static pods is critical, the kubelet will not realize it, since the priority value determines whether the pod is critical or not. This caused #80203 when we removed the deprecated critical pod annotation.
In order to solve this issue, SIG Node decided to consider all static pods as critical regardless of their `PodSpec.PriorityClassName`.

SIG node recommends using regular pods over static pods and limiting the usage of static pods to cases, such as cluster bootstrapping, that other solutions are not feasible.

/sig scheduling
/sig node

cc/ @dchen1107

**Comment by bsalamat** [comment]
More specifically, we need to check if a pod [is static](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/pod/mirror_client.go#L109), in [IsCriticalPod](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/types/pod_update.go#L148) and return true if so.

**Comment by timothysc** [comment]
/cc @kubernetes/sig-cluster-lifecycle  

@neolit123 @fabriziopandini we should be set the PriorityClass explicitly

**Comment by neolit123** [comment]
we are already setting this for all kubeadm static pods:
> priorityClassName: system-cluster-critical

to my understanding the priority will be implicitly critical from now on:
> In order to solve this issue, SIG Node decided to consider all static pods as critical regardless of their PodSpec.PriorityClassName.

**Comment by bsalamat** [comment]
> to my understanding the priority will be implicitly critical from now on

Yes

**Comment by bsalamat** [comment]
> we should set the PriorityClass explicitly

@timothysc You mean PriorityClass of the mirror pod?

**Comment by yuchengwu** [comment]
If my understanding is correct,  we are going to deprecate the priority semantic for static/mirror pod in  #80491, that means a static pod with arbitrary priority value will always be treated as critical. 

I am afraid this is a breaking change because scheduler preemption based on pod priority is it possible that scheduler preempt a low priority static pod to make room for a higher priority pod? If so, then we may want preserve the priority semantic, this can be done by restricting static pods priorityClassName to `system-critical-critical` or `system-node-critical` when they are go through admission check.

Well, I am not familiar with how scheduler preemption works, but I am curious about it. As far as I know deleting a mirror pod through `kubectl delete <mirror-pod>` will happen nothing except the the mirror pod will be recreated, leaving the containers continue running. So scheduler may skip preempt mirror pods, just use their requested value to compute the remaining allocatable resources during scheduling, if it is the case, then the above concern can be ignored. But even that, it is still a little confusion that a low priority pod can be treated as critical.

**Comment by yuchengwu** [comment]
@bsalamat  @dchen1107  Why not following the original idea, `resolve PriorityClassName to the numeric value of priority for static pods` seems more reasonable and harmless.
https://github.com/kubernetes/kubernetes/issues/80203#issuecomment-512624578

**Comment by tedyu** [comment]
```
priorityClassName to system-critical-critical
```
I guess you meant system-cluster-critical

**Comment by bsalamat** [comment]
> Why not following the original idea, resolve PriorityClassName to the numeric value of priority for static pods seems more reasonable and harmless.
#80203 (comment)

@dchen1107 In the SIG node meeting, I heard that they do not want to create such dependency on API server. My understanding is that such dependency causes problem in cluster bring-up.
