### ISSUE TITLE
Moving `k8s.io/kuberbetes/pkg/serviceaccount` to a staging repo

### ISSUE THREAD

**Issue by JoshVanL** [kubernetes/kubernetes#80574]
**What would you like to be added**:
I would like to see `k8s.io/kubernetes/pkg/serviceaccount` moved out of `k8s.io/kubernetes` into a staging repo. I'm not sure where would be the best place to put this - perhaps `k8s.io/apiserver`?

**Why is this needed**:
I would like to depend on this package on an external project but am restricted on importing `k8s.io/kubernetes/*`. My current solution is to copy the code into the project which is not ideal. 

Is this feasible to do and does this make sense?

/cc @munnerz

**Comment by munnerz** [comment]
It looks like the only package from `k8s.io/kubernetes` that is imported is the *internal* core API group `k8s.io/kubernetes/pkg/api/core` here: https://github.com/kubernetes/kubernetes/blob/10005d2e1e1425904f8c7bf5615e730fb0fea7c9/pkg/serviceaccount/claims.go#L50

Ideally I'd guess this method would also be usable externally, although I'm not sure if that's a hard req. for you @JoshVanL?

This could either be left behind, or otherwise the areas that use this adapted to accept an external representation and call-sites updated to convert to this version before calling?

**Comment by munnerz** [comment]
`util.go` includes a function that uses the `v1` version of Pod here too: https://github.com/kubernetes/kubernetes/blob/10005d2e1e1425904f8c7bf5615e730fb0fea7c9/pkg/serviceaccount/util.go#L64

So it looks like there may be some precedent for switching to all-external?

**Comment by munnerz** [comment]
The one and only call-site for this `pkg/registry/core/serviceaccount/storage/token.go`, is part of the registry package and therefore I think will be difficult to adapt to accept a `getter` that returns versioned types, meaning the code will need to be adapted to consume a `scheme` and *convert* to versioned types.

It may therefore be better to simply move `claims.go` elsewhere and/or leave it where it is, assuming it doesn't use any other unexported methods in `pkg/serviceaccount`.

/cc @mikedanese 

You wrote this original portion of code (2y ago! 😬) so I wonder if you have any opinions on the above?

**Comment by mikedanese** [comment]
Because it's touched inside the registry, it necessarily has to work off internal versions.

> would like to depend on this package on an external project

What part of the package do you need?

**Comment by JoshVanL** [comment]
> What part of the package do you need?

I want to use both the new and legacy token authenticators;
https://github.com/jetstack/kube-oidc-proxy/pull/72/files#diff-2642ce8b43502140f383918f8d6b84ccR71
https://github.com/jetstack/kube-oidc-proxy/pull/72/files#diff-2642ce8b43502140f383918f8d6b84ccR75
https://github.com/jetstack/kube-oidc-proxy/pull/72/files#diff-2642ce8b43502140f383918f8d6b84ccR93
https://github.com/jetstack/kube-oidc-proxy/pull/72/files#diff-2642ce8b43502140f383918f8d6b84ccR105

**Comment by mikedanese** [comment]
As @munnerz pointed out, pkg/serviceaccount needs to work of internal API types because it's evaluated inside the API server handling path. This means that it would have to be copied to move into staging/ and both implementations would need to be maintained for the forseeable future. It's also pretty heavy weight. It requires an informer caches of all secrets, pods and service accounts.

Is it feasible for you to use the delegated authenticator?

https://github.com/kubernetes/kubernetes/blob/7c23e1a4ac690aa60bfe677bfdf49f60b38113fd/staging/src/k8s.io/apiserver/pkg/authentication/authenticatorfactory/delegating.go#L40-L57

This is what aggregated API servers are expected to do, which seems to mesh with kube-oidc-proxy's situation. Alternatively, you could just forward tokens that you don't recognize in kube-oidc-proxy directly to the API server.

**Comment by JoshVanL** [comment]
Hi @mikedanese, that does make sense. I'm going to go ahead continue with the following approach using token review that you've posted.

Thanks for looking into things, I'd consider this resolved for me now and so will close the issue.

/close
