### ISSUE TITLE
pkg/util/workqueue/prometheus should be in client-go

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/kubernetes#80623]
**What would you like to be added**:
#33497 was great; now we need the other shoe to drop.

**Why is this needed**:
k/k is a big import.  A developer of a client should not have to import all of k/k just to get workqueue metrics wired to Prometheus.

**Comment by roycaihw** [comment]
cc @logicalhan

**Comment by logicalhan** [comment]
The reason it isn't in client-go is because there was a rather large-ish previous effort to extract out all explicit prometheus references from client-go, so that it wouldn't automatically drag in a bunch of prometheus stuff. Currently, all metrics which are instrumented in client-go use a dependency injection pattern (we inject our prometheus metrics through a provider if we care to do so), which causes the weird sort of pattern where we have what looks like client-go metrics living in a place which isn't quite client-go. What is likely is that these prometheus adaptors will likely end up moving into component-base. 

/cc @caesarxuchao @brancz @sttts

**Comment by MikeSpreitzer** [comment]
The complaint here is that a client wanting to inject a dependency on Prometheus has to drag in all of k/k.  Perhaps the linkage should be separate from client-go, but it should also be separate from k/k.

**Comment by logicalhan** [comment]
Any user of client-go is free to re-implement these metric providers so they aren't necessarily bound to all of k/k. The existing adaptors exist, as I understand it, mostly for the benefit of internally configuring these client-go metrics for the various control-plane binaries.

**Comment by logicalhan** [comment]
Would moving these into component-base be sufficient to address your concerns?

**Comment by brancz** [comment]
I understand and agree with the desire to have this be part of client go. If the experience with component base is close or the same I think I’d be fine with that as well.

**Comment by MikeSpreitzer** [comment]
I understand that a client of client-go is free to re-implement the code that injects the Prometheus dependency, and have in fact done so.  My complaint is that it seems silly to have to do so.  Now that the client-go code has been organized around dependency injection, and Kubernetes is using go modules, would there be a problem with putting the code that injects Prometheus in a new client-go package dedicated to this purpose?

Regarding the idea of putting the code that injects Prometheus in component-base, that would be OK with me.  I note that it has been said in future tense, and indeed component-base presently denies any versioning or compatability guarantees.  A client of client-go would want a dependency injector that is in sync with client-go releases.

**Comment by MikeSpreitzer** [comment]
This is moot now.  component-base is doing the job.
