### ISSUE TITLE
[ Failing test ] build-packages-debs, build-packages-rpms

### ISSUE THREAD

**Issue by droslean** [kubernetes/kubernetes#80715]
**Which jobs are failing**:
build-packages-debs
build-packages-rpms

**Since when has it been failing**:
Since job has started. See [PR](https://github.com/kubernetes/test-infra/pull/13343/files)

**Testgrid link**:
https://testgrid.k8s.io/sig-release-master-informing#build-packages-debs
https://testgrid.k8s.io/sig-release-master-informing#build-packages-rpms

**Reason for failure**:
```
make: *** No rule to make target 'build-debs'.  Stop.
```
```
 make: *** No rule to make target 'build-rpms'.  Stop. 
```

**Anything else we need to know**:
@justaugustus

**Comment by droslean** [comment]
Job configuration: [test-infraconfig/jobs/kubernetes/sig-release/kubernetes-builds.yaml#L62-L90](https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-release/kubernetes-builds.yaml#L62-L90)

**Comment by droslean** [comment]
Related PR that updates `Makefile` is  [kubernetes/release/pull/818](https://github.com/kubernetes/release/pull/818)

**Comment by alejandrox1** [comment]
Thank you for filing this issue @droslean !

/priority critical-urgent
/milestone v1.16

**Comment by alejandrox1** [comment]
Same failure in https://testgrid.k8s.io/sig-release-master-informing#build-packages-rpms

**Comment by alejandrox1** [comment]
@justaugustus could you give an update on these dashboards?

**Comment by justaugustus** [comment]
The issue was originally opened because the [additional make targets hadn't merged](https://github.com/kubernetes/release/pull/818) ahead of [turning on the CI jobs](https://github.com/kubernetes/test-infra/pull/13343).

The jobs are still failing because the scripts expect docker to be running, but there are a few extra buttons that need to tweaked to enable docker-in-docker for prow jobs, which the image I was using didn't account for.

I've opened https://github.com/kubernetes/test-infra/pull/13960 to switch to using the kubekins image, which should get us past that error, but in the long-term, I'm planning to refactor those package build scripts to not require docker when running in CI.

**Comment by justaugustus** [comment]
(Deprioritizing this as the package jobs didn't exist before, so them failing isn't truly the end of the world.)
/remove-priority critical-urgent
/priority important-soon

**Comment by droslean** [comment]
@justaugustus There is another solution that requires GCS account. [openshift/ci-vm-operator](https://github.com/openshift/ci-vm-operator) was initialy be written by @stevekuznetsov and one of the main intentions was to make prow to run jobs that require docker by spawning a VM to GCS and run the tests there. It worths to take a look.

**Comment by alejandrox1** [comment]
for tracking
/reopen

**Comment by alejandrox1** [comment]
Thank you for the update @justaugustus

**Comment by dims** [comment]
got past the problem with docker starting up properly, next problem in the ci job is being tackled here:
https://github.com/kubernetes/release/pull/861

**Comment by scottilee** [comment]
@dims will you be working on removing the dependency on Docker per the comments in https://github.com/kubernetes/release/pull/861?

**Comment by dims** [comment]
@scottilee not me, please ping @justaugustus about it.

**Comment by justaugustus** [comment]
Recently merged:
- https://github.com/kubernetes/test-infra/pull/14068
- https://github.com/kubernetes/release/pull/863
- https://github.com/kubernetes/release/pull/864
- https://github.com/kubernetes/test-infra/pull/14103

**Comment by justaugustus** [comment]
Still tweaking the images that these jobs run on. This PR moves to specific images for deb/rpm building instead of kubekins: https://github.com/kubernetes/test-infra/pull/14142

With the periodics running more frequently, it'll be faster to debug an image dependency failures now.

**Comment by justaugustus** [comment]
Fixed with:
- https://github.com/kubernetes/release/pull/866
- https://github.com/kubernetes/test-infra/pull/14147
- https://github.com/kubernetes/test-infra/pull/14148

ref:
- https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-release-build-packages-debs/1167356860500545542
- https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-release-build-packages-rpms/1167214678489698305

There are still some tweaks I'd like to do on the packaging scripts in the future, but this is good to close now! :)
/close
