### ISSUE TITLE
Add a metric to track the number of nodes filtered by the scheduler because of taints

### ISSUE THREAD

**Issue by ahg-g** [kubernetes/kubernetes#80812]
**What would you like to be added**:
A metric to the scheduler that tracks the number of nodes filtered because of taints

**Why is this needed**:
Helps tracking how taints are impacting a workloads.

/sig scheduling
/priority important-soon

**Comment by alculquicondor** [comment]
Shouldn't we generalize this to every filter (predicate)? Otherwise, what's the use case?

**Comment by liu-cong** [comment]
I have a few clarification questions.
1. What's the use case?
Do we want to record the number of pods rejected for each pod? What insights can we get from this info? Since the number of rejected nodes heavily depends on the pod itself, I don't see how useful it is to have an overall metric for all pods. 

Or maybe we want to record the number of pods rejected by the "taint" predicate. But again, what insights can we get from it?

2. This questions is easier to answer once the use case is clarified. Do we want number of rejected nodes per pod as a data point (Gauge metric type)? Or do we want the number of nodes rejected by the "taint" predicate regardless of which pod? In this case it can be a Counter metric type. Or do we want something else?

**Comment by liu-cong** [comment]
@bsalamat Can you help clarify some of the questions?

**Comment by SataQiu** [comment]
I am confused, too. What's the use case? @ahg-g
