### ISSUE TITLE
Add Metacontroller to the core project

### ISSUE THREAD

**Issue by luisdavim** [kubernetes/kubernetes#80948]
**What would you like to be added**:
I would like to propose that [Metacontroller](https://metacontroller.app/) is made default in Kuberetes.

**Why is this needed**:
The UX for creating controllers with Metacontroller is very similar to the current one for admission and validation webhooks. I think that Metacontroller would be a great addition to the core Kuberntes project and would make creating custom controllers and operators much more accessible to everyone.

Metacontroller allows developers looking to extend kuberntes to use any language of their choice and with much less boiler plate than the other options, allowing them to focus on their business logic and reducing toiling. It also makes keeping controllers compatible with new versions of Kubernertes much simpler.

I've opened an equivalent issue on the Metacontroller project:
https://github.com/GoogleCloudPlatform/metacontroller/issues/180

**Comment by DirectXMan12** [comment]
We'd be happy to host metacontroller under the KubeBuilder/server-sdk subproject.  We've discussed it in the past, but left it as-is for various maintenance reasons, but if the metacontroller folks decide they want to move the project, server-sdk seems like a reasonable place to put it.

**Comment by luisdavim** [comment]
Thanks, that would be great. 

/cc @enisoc

**Comment by DirectXMan12** [comment]
You mean "built in" to Kubernetes?  That's *highly* unlikely to happen.  Practically, there's not a good technical reason to have this "built-in" (dynamic admission webhooks need to be built-in because they have to hook into the API server), and with more and more of push to have things as extensions, there's little justification for this.

**Comment by luisdavim** [comment]
The reason is UX, it would make extending kubernetes much easier. It doesn't have to be "in tree" but it could be installed by default.

**Comment by luisdavim** [comment]
some discussion also on the metacontroller side: https://github.com/GoogleCloudPlatform/metacontroller/issues/184

**Comment by nikhilk** [comment]
@DirectXMan12 I personally think extensibility of the platform should be part of the platform.
Furthermore, in this case it is especially helpful, as one developing a controller doesn't have to impose their metacontroller dependency on users of the controller.

At the very least it ought to be a standard addon that controller authors can assume is installed.

**Comment by luisdavim** [comment]
Yes, making Metacontroller a standard addon would be awesome.

**Comment by liggitt** [comment]
> At the very least it ought to be a standard addon that controller authors can assume is installed.

I don't anticipate that happening. The number of required addons that provide API-like surfaces is *very* small (something providing DNS according to the kubernetes DNS schema, something providing metrics for HPA to consume, and that's about it). Making it easily consumable so that controllers that want to make use of it sounds like a good idea, but not adding it to core.

/close
