### ISSUE TITLE
Disks are not detached on Azure

### ISSUE THREAD

**Issue by MSSedusch** [kubernetes/kubernetes#81079]
**What happened**:
Pods with PVs could not be moved from one node to another. According to the controller-manager logs, K8s tried to detach to Azure disks from the same node. One of the detach operation waited for this lock (https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/legacy-cloud-providers/azure/azure_controller_common.go#L136). While it waited for the lock, the controller-manager pod was restarted (for whatever reason, not related to this bug, lets assume an operator restarted the pod). After the restart, K8s only tried to attach the disk to the new node but is not trying to detach it first.

**What you expected to happen**:
After a restart of the controller-manager, it should continue unfinished detach operations

**How to reproduce it (as minimally and precisely as possible)**:
* 2 Pods with PVs running on one node
* Move both pods to another node
* restart the controller-manager shortly after the move

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.15.1
- Cloud provider or hardware configuration: Azure
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by andyzhangx** [comment]
/area provider/azure
@MSSedusch that's expected behavior, k8s controller won't continue detach volume if controller manager restarted, user needs to detach that disk volume manually.

**Comment by dkistner** [comment]
@andyzhangx Could you please elaborate why this behaviour is expected. I would assume that the controller manager tries to reach the desired state after a restart? Then it would need to detect that the volume is still attached to the wrong node and should try to detach it once more, before it continuing to attach the (still attached) volume? This leads to many `ConflictingUserInputs` ...

Why is it required to resolve this situation by manual interaction?

**Comment by vlerenc** [comment]
I can't imagine that "manual intervention" is "desired behaviour" (yes, you wrote "expected", but that doesn't matter, if you make no proposal, how to improve this).

If this isn't fixed, we can't use Azure, period. We can't have clusters that need to be babysitted / you cannot expect people running workloads on Azure clusters and babysit them and manually fixing what should/can fix itself. Level-triggered behaviour and resilience is what made Kubernetes so successful... please bring that also to Azure's KCM/CCM.

**Comment by andyzhangx** [comment]
@dkistner do you know why controller manager is restarted, it's not a common scenario, we cannot guarantee disk attach/detach functionality works if  controller manager restarted at that time.

**Comment by MSSedusch** [comment]
related to #81097

**Comment by dkistner** [comment]
@andyzhangx I think there can be many reasons why the controller-manager is restarted during running detach or attach operations e. g. the hosting machine turn into error state, if you run the controller-manager in k8s -> vertical pod autoscaling,... etc.

I understand you can't guarantee that attach/detach works when the controller-manager is restarted, but I don't understand why the controller-manager can't recover the situation autonomously after a restart. 

After restart it tries to attach the volume of the rescheduled pod and this does not work because the volume is still attached to another machine. This is indicated by a `ConflictingUserInput` error from the arm and the controller-manager could react to it properly, right?

**Comment by andyzhangx** [comment]
This is an upstream issue, and there is a discussion in #81097, let's check whether we can fix it in cloud provider driver in that thread. Thanks.

**Comment by andyzhangx** [comment]
I will try to fix this issue in azure disk driver, thanks all for the discussion.
details: https://github.com/kubernetes/kubernetes/issues/80488#issuecomment-519663496
/assign

**Comment by vlerenc** [comment]
Thank you very much @andyzhangx. It means a lot to us, that there are no manual operations. I wonder how you guys deal with it in AKS, since Azure uses the same controllers, right? Anyway, it helps tremendously, that the clusters are self-healing.

**Comment by andyzhangx** [comment]
@vlerenc AKS use same kube-controller-manager, while it won't be restarted easily.

**Comment by vlerenc** [comment]
OK, but how? I understand that AKS only supports 100 nodes. So, I guess you have some upper limit and just hope, nobody stresses it, because if this happens, you it either restarts or you need to scale it up and then it gets restarted as well. Also, regular maintenance, low-level as well as Kubernetes updates, all must impact it. Considering the probably thousands over thousands of clusters (I don't know, but I expect you run many), any such problem, even if unlikely by itself, must be in your interest to fix, simply because the number of clusters increases the likelihood that it happens, I would think. Anyway, thank you for making this change @andyzhangx!

**Comment by andyzhangx** [comment]
@vlerenc Yes, that's reasonable, I will try to fix it as my top priority.
