### ISSUE TITLE
TOB-K8S-028: Kubernetes does not facilitate certificate revocation

### ISSUE THREAD

**Issue by cji** [kubernetes/kubernetes#81111]
This issue was reported in the [Kubernetes Security Audit Report](https://github.com/kubernetes/community/blob/master/wg-security-audit/findings/Kubernetes%20Final%20Report.pdf)

**Description**
Kubernetes uses certificates for authentication, authorization, and transport security. However, in its current state Kubernetes does not support certificate revocation. Therefore, users must regenerate the entire certificate chain to remove a certificate from the system. This problem has been documented in issue #18982.

**Exploit Scenario**
Eve successfully gains access to a node in Alice's Kubernetes cluster. Alice wants to revoke that node's certificate so that it is not viewed as valid by other components of the system. Also, Alice wants to avoid the cost of re-generating the certificate tree. Because Kubernetes does not help facilitate certificate revocation, this is not possible. Eve is free to abuse the certificate until Alice replaces certificates across the entire cluster.

**Recommendation**
Short term, consider having nodes maintain a certificate revocation list (CRL) that must be checked whenever they are presented with a certificate.

Long term, consider supporting OCSP stapling, where the cluster administrator can revoke certificates across the cluster through an OCSP server. In this scenario, each certificate holder would query the OCSP server to get time-stamped evidence that a certificate is valid before using it.

**Anything else we need to know?**:

See #81146 for current status of all issues created from these findings.

The vendor gave this issue an ID of TOB-K8S-028 and it was finding 2 of the report.

The vendor considers this issue High Severity.

To view the original finding, begin on page 23 of the [Kubernetes Security Review Report](https://github.com/kubernetes/community/blob/master/wg-security-audit/findings/Kubernetes%20Final%20Report.pdf)

**Environment**:

- Kubernetes version: 1.13.4

**Comment by joelsmith** [comment]
Product Security Committee response:
This is a known issue (see #18982) and we agree that it should be addressed.

**Comment by savek-cc** [comment]
The referenced issue is almost 4 years old (and still unresolved). The "interesting take" is on general OCSP-problems in large infrastructures with independent actors - not really applicable to the attack scenario given in the security analysis.

**Comment by joelsmith** [comment]
@savek-cc Thanks for your participation in the Kubernetes project.

I'd like to see this solved too. I don't claim to know what the right solution is. It may be that OCSP turns out to be the right solution, or it may be that its drawbacks cause us to go in a different direction. That was my reason for referencing the blog post. I'm not sure what the connection to public wifi is... as I see it, most networks are susceptible at some point to ARP spoofing and potential MITM attacks assuming at least one host on the network is untrusted or could become compromised.

I think the other issue (#18982) is the right place to discuss implementation trade-offs and ideas, since this issues is technically just a duplicate of that one.

**Comment by raesene** [comment]
One thing to note about the blog post on imperial violet is that it (as far as I can see) looks at the problem of certificate revocation at Internet scale where there are a large number of certificate authorities and therefore the problem of not being able to access the revocation list is more serious.  Also it looks at the Internet scale case, which has problems which may not be present at k8s cluster-scale

It would see possible that revocation could be implemented in k8s more easily as there are services which should always be reachable to facilitate checking.  Specifically every cluster has an `etcd` or similar datastore which has to be available for the cluster to operate, so an API server could query data stored there for revoked certificates without fear of inappropriately refusing connections due to inability to communicate with the revocation service.

**Comment by mikedanese** [comment]
Closing as a dup of https://github.com/kubernetes/kubernetes/issues/18982
