### ISSUE TITLE
TOB-K8S-031: Adding credentials to containers by default is unsafe

### ISSUE THREAD

**Issue by cji** [kubernetes/kubernetes#81128]
This issue was reported in the [Kubernetes Security Audit Report](https://github.com/kubernetes/community/blob/master/wg-security-audit/findings/Kubernetes%20Final%20Report.pdf)

**Description**
Kubernetes uses secrets for multiple aspects of the system. In order to provide containers with these secrets, a directory is created and secrets are effectively mounted on the container within this directory. This practice presents two major concerns:

1. By default, the directories under /var/run/secrets are world-readable, similar to TOB-K8S-004: Pervasive world-accessible file permissions.
2. The default service account is also included within this bundle, allowing an attacker to parlay access to a container into wider-cluster access.

```
root@wordpress-dccb8668f-mzg45:/var/www/html# curl -H "Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" "https://172.31.28.169:10250/logs/" -k
<pre>
<a href="alternatives.log">alternatives.log</a>
<a href="amazon/">amazon/</a>
<a href="apt/">apt/</a>
<a href="auth.log">auth.log</a>
<a href="auth.log.1">auth.log.1</a>
```
Figure 20.1: An example of parlaying access to a container into wider-cluster access

**Exploit Scenario**
Alice wishes to run a service within a container on her Kubernetes cluster. Eve has transited system boundaries, and has read access to the various secrets stored within the container. Eve then uses this access to attack cluster infrastructure as a whole, such as the /logs/ or /run/ routes.

**Recommendation**
Short term, do not add secrets to containers in a world-readable fashion. Instead, restrict them, either by permission of file system access control list, or to a specific user who truly needs access.

Long term, define a mechanism by which secrets may be filtered, and only mounted within containers that truly need them. This may go so far as to leave secrets unmounted until the user describing the container specifically requests it, and the cluster administrator specifically allows it. 

**Anything else we need to know?**:

See #81146 for current status of all issues created from these findings.

The vendor gave this issue an ID of TOB-K8S-031 and it was finding 20 of the report.

The vendor considers this issue Medium Severity.

To view the original finding, begin on page 59 of the [Kubernetes Security Review Report](https://github.com/kubernetes/community/blob/master/wg-security-audit/findings/Kubernetes%20Final%20Report.pdf)

**Environment**:

- Kubernetes version: 1.13.4

**Comment by tallclair** [comment]
@joelsmith I think the categorization of feature was correct. Why did you relabel this as a bug?

> Long term, define a mechanism by which secrets may be filtered, and only mounted within containers that truly need them. This may go so far as to leave secrets unmounted until the user describing the container specifically requests it, and the cluster administrator specifically allows it.

Isn't this covered by only mounting secret volume into some containers? Or is this just asking for changes / new defaults for `automountServiceAccountToken`?

**Comment by joelsmith** [comment]
Hi @tallclair, originally when all the issues were opened, they were opened as features. I knee-jerk changed them all to bug since most of them were bugs, not paying attention to the fact that some were features. If you see any others that you consider features, feel free to flip them back.
/remove-kind bug
/kind feature

**Comment by cji** [comment]
> originally when all the issues were opened, they were opened as features. 

Yeah, I used the wrong template to start with on all of these and made a mess. Really appreciate the help cleaning up and labeling them all properly!

**Comment by mikedanese** [comment]
Partial dup of https://github.com/kubernetes/kubernetes/issues/57601

**Comment by liggitt** [comment]
/close

One part of this issue is already addressed, and one part will not be addressed.

For the file permission issue, as of 1.22, injected tokens use projected service account tokens. https://github.com/kubernetes/kubernetes/pull/89193 made those tokens set file permissions as tightly as possible, rather than be world-readable.

For the default injection issue, API authors can choose not to inject credentials by setting spec.automountServiceAccountToken=false on pods, or by setting automountServiceAccountToken=false on service accounts. Changing the automountServiceAccountToken default is a disallowed breaking change.
