### ISSUE TITLE
TOB-K8S-037: Kubelet supports insecure TLS ciphersuites

### ISSUE THREAD

**Issue by cji** [kubernetes/kubernetes#81145]
This issue was reported in the [Kubernetes Security Audit Report](https://github.com/kubernetes/community/blob/master/wg-security-audit/findings/Kubernetes%20Final%20Report.pdf)

**Description**
Kubelet allows administrators to configure TLS connections to use a variety of insecure cipher suites. In particular it supports the use of RC4 and 3DES in its symmetric suites. RC4 has known bias in its output and should never be used, while 3DES is an extremely deprecated 64-bit block cipher which is both slow and unneeded. Additionally, non-forward secure key exchange is supported (TLS_RSA_*). This, along with SHA-based cipher suites, should be deprecated and replaced.

**Recommendation**
Remove support for any cipher suite that uses RC4 or 3DES as well as non-forward secure key exchange suites (TLS_RSA_*). Deprecate all but the following cipher suite options for TLS versions up through 1.2:

TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256
TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256

Use the following cipher suites for TLS 1.3:

TLS_AES_128_GCM_SHA256 
TLS_CHACHA20_POLY1305_SHA256
TLS_AES_256_GCM_SHA384

**Anything else we need to know?**:

See #81146 for current status of all issues created from these findings.

The vendor gave this issue an ID of TOB-K8S-037 and it was finding 37 of the report.

The vendor considers this issue Informational Severity.

To view the original finding, begin on page 89 of the [Kubernetes Security Review Report](https://github.com/kubernetes/community/blob/master/wg-security-audit/findings/Kubernetes%20Final%20Report.pdf)

**Environment**:

- Kubernetes version: 1.13.4

**Comment by pathcl** [comment]
I was able to disable 3DES using this: 

      tls-cipher-suites: "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,TLS_RSA_WITH_AES_128_GCM_SHA256,TLS_RSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_128_CBC_SHA,TLS_RSA_WITH_AES_256_CBC_SHA"

**Comment by stlaz** [comment]
> Use the following cipher suites for TLS 1.3:
> TLS_AES_128_GCM_SHA256
> TLS_CHACHA20_POLY1305_SHA256
> TLS_AES_256_GCM_SHA384

Currently it is impossible to configure TLS 1.3 cipher suites as these would always be ignored - https://github.com/golang/go/blob/0fb95e788e8639712b7200a5c08ec023fb3588cb/src/crypto/tls/handshake_server_tls13.go#L151-L157

That means that such ciphers are automatically enabled if you build with TLS1.3-allowing flags.

I'm not sure it would be desirable to remove the ability to set ciphers that are not mentioned in this issue, but it might be good to use the above cipher list as the defaults (omitting the TLS 1.3 suites that are either always or never there) :thinking:

**Comment by vinayus** [comment]
adding this on my machine fixed it for a time being

```
cat /etc/sysconfig/kubelet
KUBELET_EXTRA_ARGS="--tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384"
```

**Comment by pjbgf** [comment]
TL;DR
---
This is a non-issue in places where HTTP2 is enforced and cannot be disabled. As HTTP2 won't accept ciphers within their list of [bad cipher suites][] - which covers all ciphers this issue wants to remove from the kubelet.

From a security perspective, this may be a false positive if cluster admins have no way to disable HTTP2 on the kubelet, which I could not confirm. If that is the case, I think we should exclude all  [bad cipher suites][] from the flag's  [possible values][], as it is counter productive to provide options that cannot be used.

However, this issue can be reproduced against the api-server, when misconfigured to support weak/insecure ciphers (scenarios C and D below). But that sounds like a separate point.


Further Details
---

**API Server**
A few scenarios I tested:
A) Using _only_ weak/insecure ciphers on `--tls-cipher-suites` makes the api-server fail to start with error:
https://github.com/kubernetes/kubernetes/blob/3b024339bd67b80e79a161bc295f6fe609eff076/vendor/golang.org/x/net/http2/server.go#L255

B) Adding weak/insecure ciphers before HTTP2's ciphers on `--tls-cipher-suites` make the api-server fail to start with error:
https://github.com/kubernetes/kubernetes/blob/3b024339bd67b80e79a161bc295f6fe609eff076/vendor/golang.org/x/net/http2/server.go#L251

C) Manually setting [DisableHTTP2][] to true on code, and forcing only insecure/weak ciphers through `--tls-cipher-suites` allows the api-server to operate normally.

D) Adding weak/insecure ciphers on `--tls-cipher-suites` after more secure options, makes the api-server to operate normally.

To make the connection I had to use a modified `kubectl` that only supports weak and insecure ciphers. For scenario D it also required HTTP2 to be disabled at client-side by using an environment variable:
```
$ DISABLE_HTTP2=true kubectl_weak get pods --all-namespaces
I0514 09:03:11.918628   16970 http.go:122] HTTP2 has been explicitly disabled
NAMESPACE     NAME                       READY   STATUS    RESTARTS   AGE
kube-system   kube-dns-c74654849-jqv9t   2/3     Running   0          45s
```
**kubelet**
Similar behaviour to the api-server for cases A and B. Scenarios C and D could not be reproduced for kubelet, as I could not find a way to disable HTTP2 through code or otherwise. 


[DisableHTTP2]:https://github.com/kubernetes/kubernetes/blob/3b024339bd67b80e79a161bc295f6fe609eff076/staging/src/k8s.io/apiserver/pkg/server/config.go#L267
[bad cipher suites]:http://http2.github.io/http2-spec/#BadCipherSuites
[possible values]:https://github.com/kubernetes/kubernetes/blob/7580666e0c58b0a34a87fb19beeb682a88e50fac/staging/src/k8s.io/component-base/cli/flag/ciphersuites_flag.go#L28

**Comment by pjbgf** [comment]
@liggitt Is there a way to disable HTTP2 on the kubelet? If so, shall we remove those ciphers from the kubelet's flags?

**Comment by liggitt** [comment]
> @liggitt Is there a way to disable HTTP2 on the kubelet?

I don't think there is.

**Comment by pjbgf** [comment]
I just confirmed with Bobby from Trail the Bits through the wg-security-audit channel, and the issue was raised based on the configuration being available. No TLS connection was established to the kubelet. Given the points I made above, we should probably 1) close this issue and create a new one for api server or 2) repurposed it for the api server.

@cji what would be your thoughts on options 1 and 2?

**Comment by cji** [comment]
@pjbgf thanks for the analysis! If you'd like to create a new one for API server, I'd be happy to close this and link to that here and in the master issue tracking the audit findings.

**Comment by pjbgf** [comment]
@cji I have just created a new issue and linked to this one. I haven't used the same prefix, as it wasn't on the original report.

**Comment by cji** [comment]
Thanks @pjbgf I'll close this

**Comment by AndrewSav** [comment]
@pjbgf can you explain a bit more why is this a non-issue? I just ran this on a master:

```
curl -vk --http1.1 --cert /etc/kubernetes/pki/apiserver-kubelet-client.crt --key /etc/kubernetes/pki/apiserver-kubelet-client.key "https://localhost:10250/runningpods/"
```

And I got (in addition to response body and other output):

```
< HTTP/1.1 200 OK
```

It seems to me that it _is_ an issue in the default configuration, no? HTTP2 is offered by the server, but it is the client that can chose 1.1 and then we have a vulnerability on our hands. The fact that you cannot disable HTTP2 does not seem to play a role here, since HTTP2 does not need to be disabled for an attack on legacy ciphers to succeed as long as HTTP1.1 is supported and it it. I might have missed something, and I would appreciate an explanation.

**Comment by pjbgf** [comment]
@AndrewSav the explanation is here: https://github.com/kubernetes/kubernetes/issues/81145#issuecomment-628533749.

Please note that the focus of this issue was the Kubelet, and not the apiserver. For the latter you can refer to [this issue](https://github.com/kubernetes/kubernetes/issues/91444). However, users are able to protect themselves by picking safe ciphers via `--tls-cipher-suites` on their apiserver.

**Comment by AndrewSav** [comment]
@pjbgf Thank you for responding. I did read the original explanation, and I would like an extra clarification. That explanation the way I understand it says that:

a) http2 protects from the weak ciphers
b) it is not possible to turn http2 off in a kubelet
and thus c) kubelet should be secure

I'm requesting clarification about this logic and my understanding of it. In my view it is not true that c) follows from a) and b), because along with http2, _http1.1 is also offered_ by the kubelet, and it is the client who selects the protocol. So if one tries to use http1.1 and request a weak insecure cipher they will end up on the week insecure cipher, and thus we have an issue.

Could you please explain a bit more, what I'm missing here.

**Comment by huornlmj** [comment]
This still doesn't seem to be fixed as I'm still seeing kubelets on 10250/tcp exposing weak ciphers.
