### ISSUE TITLE
Cut and vendor cAdvisor release for 1.16

### ISSUE THREAD

**Issue by dashpole** [kubernetes/kubernetes#81228]
For each kubernetes release, we cut a new cadvisor release, and vendor it in.  This issue tracks this for the 1.16 release.

**Comment by dashpole** [comment]
/kind bug
since there are many bug-fixes included in this release
cc @sjenning 

@dchen1107 can you add this to the 1.16 release?

**Comment by dchen1107** [comment]
@dashpole I cannot see v1.16 milestone here. Maybe the permission for me to update the milestone is removed now?

**Comment by ttousai** [comment]
Hello @dashpole ! I'm a bug triage shadow for the 1.16 release cycle and considering this issue is tagged for 1.16, I'd like to check its status. Code freeze is starting on August 29th (about 2 days from now), which means that this PR must merged by then.

Do we still target this issue to be fixed for 1.16?
