### ISSUE TITLE
Volumes require filesystem clients and utilities on host

### ISSUE THREAD

**Issue by childsb** [kubernetes/kubernetes#8124]
The various filesystem plugins currently work by mounting a filesystem on the host then passing that mounted dir to the pod for access.  This requires that the host system has the filesystems client & utils installed and configured.

I would like to containerize the filesystem client pieces and run it as a sidecar to the POD requesting the volume.

This is currently impossible as a PODs mount isn't in the hosts proper namespace.  So a filesystem mounted within a POD isn't visible to other pods on the host.

**Comment by thockin** [comment]
Not sure what to do with this.  You're correct that mounting from withing a container to be visible outside that container is tricky.  Are you filing a bug so that we are aware (we are aware)?  Or is this something you intend to pursue and are looking for guidance?

@pmorie did a lot of this same work

**Comment by eparis** [comment]
So I think this can be fixed in a couple of steps...

In docker 1.6 they defaulted to making volume mounts slave of the init mount namespace. We need a new flag where we can make volume mounts shared with the init mount namespace.  aka, mounts that happen inside the container show up outside the container in the host namespace.

The second step would be to write a new kubernetes mounter (possibly one per mount type?) which instead of calling mount(8) on the host calls a container and that container does the mount.  The container might be able to do the mount inside the container, but if the volume is shared with the init mount namespace the mount will show up in the host.  Thus the next container would be able to use it!

This also would mean that all of the work that pmorie did hacking together an 'escape the kubelet' mounter could disappear.  The kubelet wouldn't need to do mount at all.  It would instead need to make sure that the container did that mount.

Step one is going to be changes to docker....

**Comment by childsb** [comment]
Crosslinking with Docker patch required: https://github.com/docker/docker/pull/16773
