### ISSUE TITLE
[Scheduler] Expand the internal range of score to [0, 100]

### ISSUE THREAD

**Issue by draveness** [kubernetes/kubernetes#81281]
/sig scheduling
/priority important-soon
/assign

**What would you like to be added**:

We plan to update the internal score range to [0, 100].

**Why is this needed**:

[The [0, 10] range is not differentiating](https://github.com/kubernetes/enhancements/pull/1178#discussion_r311312001) enough. Now that we are transitioning to the framework, we can consider expanding the range.

We'll add two constant into the framework interface and multiply the original score by 10:

https://github.com/kubernetes/kubernetes/blob/92e14d79e91ad49a1fa847cf8d27fc8df84b2cda/pkg/scheduler/framework/v1alpha1/interface.go#L58-L64

https://github.com/kubernetes/kubernetes/blob/92e14d79e91ad49a1fa847cf8d27fc8df84b2cda/pkg/scheduler/core/generic_scheduler.go#L805-L806

This is an internal change and compatible (forward and backwards) the developers won't feel it. 

**See also**:

+ https://github.com/kubernetes/kubernetes/pull/81015 which try to introduce the change.
+ https://github.com/kubernetes/enhancements/pull/1178 

cc/ @bsalamat @ahg-g @Huang-Wei

**Comment by ahg-g** [comment]
@bsalamat @misterikkit @Huang-Wei I have a couple of questions:

Q1: Any idea why MaxPriority is exposed in the scheduler API? are you aware of any gotchas if we are to increase the value from 10 to 100?

Q2: If we are to change MaxPriority to 100, the final ranking of nodes will change since we are using a wider range. How do we safely roll such a change that impact core scheduling decisions?

**Comment by draveness** [comment]
> Q2: If we are to change MaxPriority to 100, the final ranking of nodes will change since we are using a wider range. How do we safely roll such a change that impact core scheduling decisions?

An alternative could be expanding the MaxNodeScore to 100 and keep the MaxPriority as it is.

**Comment by mtcode** [comment]
Is there still ongoing work as part of this?  I have a use case where the scoring is not precise enough, and I'm running a custom scheduler now that increases the scoring range to 1000.

**Comment by draveness** [comment]
> Is there still ongoing work as part of this? I have a use case where the scoring is not precise enough, and I'm running a custom scheduler now that increases the scoring range to 1000.

We're in the migration of the scheduling framework and I'll send a PR soon.

**Comment by ahg-g** [comment]
@draveness the only place were we should maintain the value 10 is in Extender replies. This is because extender api is v1, and we can't change the range of values we expect from extenders without upping the version, and so for now we need to scale it to the range we set for scheduler internal scoring functions.

I suggest we do the following:
PR 1. Get rid of MaxPriority
 1.1 Remove the variable ```MaxPriority```, and set ```MaxNodeScore``` explicitly to 10
 1.2 Update all priority functions to use ```MaxNodeScore```
1.3 Define constants for for extender's expected priority (```MinExtenderPriority```/```MaxExtenderPriority```) that is set to 0/10 in the new [pkg/scheduler/apis/extender/v1/api.go package](https://github.com/kubernetes/kubernetes/pull/83262).

PR 2. Scale [extender output](https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/core/generic_scheduler.go#L842) from MinExtenderPriority-MaxExtenderPriority to MinNodeScore-MaxNodeScore 


PR 3. Actually change of MaxNodeScore to 100. The reason we do it in a separate PR is to be able to revert it back easily if we faced problem.
