### ISSUE TITLE
//test/instrumentation:list_stable_metrics fails due to argument list

### ISSUE THREAD

**Issue by cblecker** [kubernetes/kubernetes#81400]
```
bazel-out/darwin-fastbuild/bin/test/instrumentation/list_stable_metrics.genrule_script.sh: line 2: ./bazel-out/host/bin/test/instrumentation/darwin_amd64_stripped/instrumentation: Argument list too long
```

/assign @serathius
/cc @logicalhan @brancz 
/sig instrumentation

**Comment by serathius** [comment]
Hey @cblecker,
Looks like this test is passing on testgrid, https://k8s-testgrid.appspot.com/presubmits-kubernetes-blocking#pull-kubernetes-bazel-test&include-filter-by-regex=instrumentation%3Averify_stable_metric
Which would point to problem being related to specific environment. 

From your log looks like problem is specific to **Macs**. I will try to reproduce it to confirm it.

My current ideas for solution are:
* Disabling test on Mac
* Instead of passing files as arguments, pass them in STDIN

WDYT?

**Comment by BenTheElder** [comment]
FWIW ARG_MAX can technically vary even on linux ...?
STDIN SGTM
