### ISSUE TITLE
Allow specification of preferred CRD deletion propagationPolicy

### ISSUE THREAD

**Issue by cadedaniel** [kubernetes/kubernetes#81628]
**What would you like to be added**:
A way for CRDs to specify a custom preferred propagationPolicy for deletion.

**Why is this needed**:
I am speaking as a developer of a CRD with a corresponding controller (using [Kubebuilder](https://github.com/kubernetes-sigs/kubebuilder)).

CRD developers must use `ownerReferences` so that CRD controllers can remove finalizers from managed CRDs during deletion. This requires that users delete the controller using `{"kind":"DeleteOptions","apiVersion":"v1","propagationPolicy":"Foreground"}` (JSON because [kubectl does not support setting a propagationPolicy yet](https://github.com/kubernetes/kubectl/issues/672)).

Given this setup, if a user forgets to specify the propagation policy, or does not know implementation details of my controller and intentionally deletes the controller without the foreground propagation policy, their delete operation will hang and they must remove the finalizers manually or reinstall the controller onto the cluster.

If CRDs were able to specify a preferred propagation policy for deletes, which would be the default unless overridden, then CRDs would be able to hide unnecessary implementation details from users who do not need to know.

**Comment by cadedaniel** [comment]
Note that controller developers can implement this functionality on the controller side with finalizers and a manual search for dependent objects as done [here](https://github.com/kubernetes-sigs/cluster-api/pull/1180/files). However, given that all CRDs which manage resources could use this, I think it should be a candidate for implementation on the server side.

**Comment by cadedaniel** [comment]
setting sig
/sig api-machinery

**Comment by cadedaniel** [comment]
@liggitt this is something I was not aware of, and would solve the problem equally well as my option 2. Thank, sorry for making a feature request for something that could have been answered by a stack overflow question :)

**Comment by 85danf** [comment]
Hey @liggitt sorry for bumping an old issue but I'd like to suggest a usecase as well:

We built a controller for our `CRD` where the reconciliation involves creating a set of resources/`CRD`s that other components are watching for.

As @cadedaniel points out, Since I'm using `kubeuilder` it compels me to add an `OwnerReference` referencing my 'main' `CRD` to all 'secondary' resources.
This is because I want my controller to get events for the secondary resources as well (so it can reconcile), and the only way it knows to make the connection between secondary to primary resource is by the `OwnerReference`

My controller also adds a `Finalizer` on the primary resource and when it gets deleted there are certain cases where I don't want to delete all of the corresponding secondary resources.

Because the default deletion propagation policy is background, whenever my primary resource is deleted it cascades all of the secondary resources which messes up my state.

One thing to note is that, for the most part, I control the deletion of the primary resource through another component where I can pass an `Orphan` policy with delete options to the API. But:
1. As you point out, I totally agree it's not a very good idea to rely on a certain deletion policy in my controller finalization logic.
2. My users should not (and that is exactly why they will for sure) delete the primary resource, but experience teaches us we should prepare for these cases as well.

I would love to get your feedback please - given what you said about not implementing a choice of policy for `CRD`s is there a way I can work around the gc behavior?
