### ISSUE TITLE
"v2" API (API/client redesign umbrella issue)

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#8190]
It's clear we're not going to be able to make all the changes we'd like in the v1 API (#7018), so this issue is to track/brainstorm things we might want in the v2 API.

Last updated 6/19/2015

API/client overhaul:
- Top-level API object plugins: #991, #3201, #1744, #703, #6923
  - Convert ReplicationController to a plugin #3058, rename it to ReplicaSet #3024, and recursively delete pods by default (see graceful termination #1535, below)
  - Daemon #1518
  - Job #1624
  - Deployment #1743
  - ConfigData #6477, #1553, #1627, #2068, #5582
  - Rename PersistentVolumeClaim to PersistentVolume, PersistentVolume to StorageVolume (or similar) as per [comment](https://github.com/kubernetes/kubernetes/pull/14095/files#r39791183)
- Subobject plugins: discussed in #7203 and lots of other places
  - I'd also like to consider replacing annotations with a list of plugins #12226
  - volume sources should be converted to plugins
- Multiple API prefixes/groups, including an experimental API prefix: #3806, #6363, #10009, #635, #1490
  - API group in addition to kind and apiVersion: #7111, #10009, #12951 
  - Modular API: #1744, #3481 (API subsets), https://github.com/kubernetes/kubernetes/issues/9633#issuecomment-113712917 (separate client objects from API objects)
  - Provider/domain field (e.g., kubernetes vs. docker) -- https://github.com/projectatomic/atomicapp
  - Some hypothetical API groups:
    - end-user execution objects: pod, pod template, secret, config data, persistent volume claim
    - end-user networking-related objects: service, ingress
    - end-user app deployment objects: replica set, deployment
    - end-user batch objects: job, scheduled job
    - app admin objects: namespace, limit range, resource quota
    - identity/auth objects: service account, user (future)
    - system / tooling objects: event, endpoints, component status, resource metrics
    - infrastructure / cluster admin deployment objects: daemon set
    - infrastructure / cluster admin infrastructure objects: node, persistent volume
    - experimental apis and plugins
- Binary encoding: #3338, #8132 (proto)
- Split objects in etcd to mitigate false conflicts: #8625
- API support for apply: #17333
- Restructuring: #1451, #2306, #2742, #4851, #5660, #6210, #7111, #7311, #7337, #7584, #3933
- Client versioning: #3955, #4874
- Fork versioned client on every breaking change
- Versioned validation: #8550, #3084
- Strict validation: #5889
- Tag-driven, swagger-documented validation: #8116
- Fine-grain versioning: #4855, #2953
- Return more info on failure: #6132
- Fix syntax for field validation errors: https://github.com/kubernetes/kubernetes/pull/12035/files#r36374661
- API test fixtures: #5121, #4894
- Cleanup object references and selfLink: #6596, #2797, #1490, #4651, #4549
- Kubelet to use apiserver: #2098
- REST best practices and HTTP correctness: #4187, #5672, #6387, #656
- Swagger correctness: #6842, #6167, #2968, #2971, #4700, #3714
- Swagger 2.0: https://github.com/emicklei/go-restful/issues/157
- Form and client generation: #6487, #4210, #3685
- Improved API documentation: #10933, #5331 
- Change all fields to pointers for uniform detection of unspecified fields
- Scale to 1000 nodes / 50k pods

API feature changes:
- Finish subresource work, such as #2726, #4909, #8337, #10043
- Bulk API: #9633, #3279
- Initializers: #3585
- Dependencies and graceful termination for all objects: #1535
- Per-object generation numbers for all objects: #7328
- Generalized label selector: #341
- Generalized field selectors: #1362, #4476
- Reverse label lookup: #1348
- Get by uid: #4817
- Get subset of fields: #1459, #2740
- Generalized image representation: #8702
  - ACI images: #7203
- Eliminate most volume sources
- Eliminate gitRepo in favor of a generic container volume mechanism #831
- Eliminate phase #6951
- A usable mechanism for waiting for conditions #1899
- Replace object names with specialized object references: https://github.com/kubernetes/kubernetes/issues/7018#issuecomment-102536924, #8503
- Links to related objects in status #3676
- Watch improvements: https://github.com/kubernetes/kubernetes/issues/7018#issuecomment-101008710, https://github.com/kubernetes/kubernetes/issues/7018#issuecomment-101079247, #3295, #1685, #5130
- Endpoints: We'll need a way to avoid quadratic behavior (one endpoint changing returns whole set).
- Final resolution on minion #1111
- More service changes #2585
- Generalize deletion/mutation prevention: #10179

**Comment by derekwaynecarr** [comment]
Mechanism to set initializers / places for hooks prior to scheduling #3585

**Comment by lavalamp** [comment]
Replace ServiceAccountSecret secret type with a cluster account secret type. Secret types should be named for their contents, not their sources, IMO. (source can live in an annotation or something)

**Comment by bgrant0607** [comment]
@lavalamp Is there a reason we can't fix ServiceAccountSecret now? It was just merged recently.

**Comment by pmorie** [comment]
Agree, why not just fix it now?

**Comment by liggitt** [comment]
serviceaccounts and their tokens were intentionally namespaced... it would be very difficult to partition access to a cluster-scoped resource. The ability to give someone control over machine accounts and their credentials in a namespace is valuable... I wouldn't want to lose that

**Comment by lavalamp** [comment]
@bgrant0607 I'm OK with changing it now, but lack cycles to do it myself.

**Comment by lavalamp** [comment]
@liggitt... wrong issue? or maybe you can explain in more detail?

**Comment by liggitt** [comment]
@lavalamp my bad, I misread "cluster account secret type" as "cluster-scoped"

**Comment by bgrant0607** [comment]
Issue filed for ServiceAccount secrets: #8271.

**Comment by bgrant0607** [comment]
Punted from v1:
* Eliminate most volume sources
* Eliminate phase #6951
* Replace object names with specialized object references: https://github.com/GoogleCloudPlatform/kubernetes/issues/7018#issuecomment-102536924

**Comment by bgrant0607** [comment]
Other use cases for subobject plugins:
* Secret providers, such as dockercfg
* Cloud-provider-specific load-balancing info communicated from service controller to kube-proxy (or plugin)

**Comment by bgrant0607** [comment]
LocalReference: #8503

**Comment by erictune** [comment]
@bgrant0607 I assume you are just looking to collect breaking changes here, and not few features?

**Comment by erictune** [comment]
Suggest we change pointer-to-scalar to pointer-to-struct everywhere, for possible future compat with proto.

**Comment by bgrant0607** [comment]
@erictune Yes, you are correct.

**Comment by bgrant0607** [comment]
Generalized image representation: #8702

**Comment by bgrant0607** [comment]
In addition to eliminating volume sources obsoleted by persistent volume claims (gcePersistentDisk, awsElasticBlockStore, nfs, iscsi, glusterfs, rbd), I'd also like to eliminate gitRepo in favor of a generic container volume mechanism (#831).

**Comment by pmorie** [comment]
+100 to container volume

**Comment by lavalamp** [comment]
> I'd also like to eliminate gitRepo in favor of a generic container volume mechanism

+1

**Comment by lavalamp** [comment]
@bgrant0607 I have been thinking for a while now that it's bad that we have gcePersistentDisk and awsElasticBlockStore as volume types that *pods* need to specify. It seems to me that if we want true workload mobility, we need to abstract this into a separate type, so that you can use the same pod descriptions on any cloud provider. IOW pods shouldn't depend on on the implementation of persistence, they should just request a persistent volume, and (cluster admin via config? cloud provider?) determines the implementation that pods get.

**Comment by bgrant0607** [comment]
@lavalamp That's what persistentVolumeClaim is for. We just haven't removed the old fields yet.

**Comment by bgrant0607** [comment]
Generalized label selector: #341

**Comment by bgrant0607** [comment]
@erictune Re. object references, see:
* https://github.com/GoogleCloudPlatform/kubernetes/issues/7018#issuecomment-102208733
* https://github.com/GoogleCloudPlatform/kubernetes/issues/7018#issuecomment-102536924
* #3676
* #4549
* https://github.com/GoogleCloudPlatform/kubernetes/issues/170#issuecomment-69819671

**Comment by bgrant0607** [comment]
cc @smarterclayton @timothysc

**Comment by bgrant0607** [comment]
I expanded this issue into an umbrella issue for overhauling the apiserver, API machinery, and client libraries. See the updated description on github.

**Comment by bgrant0607** [comment]
An idea: Eliminate the "internal" representation.

Why?
* We try to keep api/types.go similar to the latest API version, anyway, necessitating pervasive code and test changes every time we make such a change.
* The so-called "internal" representation is used by all clients currently, which we'd like to change for all clients and components other than apiserver and Kubelet (#4874, #3955).
* Some of the api/types.go objects are serialized when they shouldn't be (#3933). 
* Additionally, the conversions are expensive, and even if an object is sent to the apiserver in the same form we want to serialize it in etcd, we perform at least 2 conversions (version->internal and internal->version).

The alternative would be:
1. Use the latest stable, available-by-default API version for any given resource (taking into account multiple API groups, as discussed in #10009) in all components that are pure API clients (e.g., scheduler, controllers).
2. Convert any resource directly to the storage version for that resource in apiserver and Kubelet, and in kubectl, where conversion is really necessary.

**Comment by smarterclayton** [comment]
Interesting.  Would that force us to upgrade all objects in the code base at the same time (from v1 to v2) because we only want to maintain one version as the hub of the scheme?  I guess we could could convert through the storage version (no worse than today).

Also removes any possibility of having the internal version having conveniences like maps or simpler structures (although I'm provisionally ok with that, because if our public API objects are hard to use we need to fix that anyway).

**Comment by thockin** [comment]
for v2: generalize services to something more like storage claims - ingress pools or something.

for v2: something like equiv classes for storage (for replication controllers) and dynamic provisioning.

**Comment by thockin** [comment]
Re: getting rid of internal, how would it play out with something like a v2beta1 API?  We fork v1 to v2beta1, but it's not a stable API yet, so we can accumulate breaking changes in there.  But all of our internal code will still use v1 structures.  At some point we say v2beta1 is frozen and let people outside the core cabal use it.  But all of our internal code will still use v1 structures, so we won't really get any playtime with it.  Eventually we promot v2betaN to v2, and we convert all of our code to use it at once (or per component at-once).

Am I understanding correctly?  I prefer the incremental evolution of the code that we get today.  It's possible to change a feature across the codebase and test just that one change without bulk converting.  The auto-converters are fine for converting data blobs to other versions, and the round-trip tests ensure that pretty much just works.  But changing code is a lot scarier.

Also, this necessitates a large shift in how we do defaulting (which we need anyway).  Today I never create a v1 object, I always have internal objects.  This means I can sort of assert that the internal object has some invariants that the conversion process from v1 to internal is supposed to ensure.  For example Enum-strings are valid values and not "".  This is not always the case with internal objects today (we need constructors) but at least with internal objects we COULD centralize that into constructor-like things.  If every test creates versioned objects we need to re-think defaulting and construction.

This also means that some of the "unset vs 0" detection that we do with pointers exists "beyond the versioned API barrier".  Today, v1 RC.Spec.Replicas is a pointer, but internal is just an int.  Defaulting and conversion ensures that internal gets the right value.  It's a relatively minor point, but now we have another potentially-nil thing all over the code.

This also means we can't really use "smart" objects in our API-related code, because JSON decoding is insufficient to init them (see Resource).

The direction I imagined we'd be going is more like "smart" or "rich" internal objects which are constructed from "very dumb" versioned objects.  But I ACK the cost of conversions and the desire to be API-pure and not leak internal representations.

**Comment by bgrant0607** [comment]
Other than apiserver and some parts of Kubelet, all our components are clients: scheduler, controller manager, kube-proxy. They should use versioned client libraries just like any other client, and they shouldn't be doing any conversion at all. They can't use experimental APIs, at least not be default.

**Comment by bgrant0607** [comment]
I agree we need to rethink defaulting and construction, but also think using versioned objects in tests would make test maintenance simpler rather than harder. For instance, every time we add a new field with a default we currently have to change every single test that uses that object. We'd get the default for free if using a versioned object, at least the way it works now.

**Comment by bgrant0607** [comment]
We need to hash out a design for smart objects. Which components would use them? Would they all use the same smart objects? IMO, that would be a disaster. I don't want classes with hundreds of methods because every component that wanted some convenience methods added them to the shared class, and I don't want implicit behavior attached to the objects that should be explicit in the API -- like the original "how do we do defaulting" discussion. I also don't want constructors that don't accept essentially the full dumb object as an argument, or that have version-independent defaulting behavior.

**Comment by smarterclayton** [comment]
Agree in principle with that.

On Thu, Jul 23, 2015 at 4:06 PM, Brian Grant <notifications@github.com>
wrote:

> We need to hash out a design for smart objects. Which components would use
> them? Would they all use the same smart objects? IMO, that would be a
> disaster. I don't want classes with hundreds of methods because every
> component that wanted some convenience methods added them to the shared
> class, and I don't want implicit behavior attached to the objects that
> should be explicit in the API -- like the original "how do we do
> defaulting" discussion. I also don't want constructors that don't accept
> essentially the full dumb object as an argument, or that have
> version-independent defaulting behavior.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleCloudPlatform/kubernetes/issues/8190#issuecomment-124225520>
> .
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by thockin** [comment]
I certainly have not hashed it all out, I think the only way to arrive at
answers will be to try a few attacks and see what sticks.  I have been
chewing on it off-and-on, and I think I can get behind the
no-internal-version thing.

I'm going to write stream of consciousness, mostly.  No filter, all my
idiocy in one post...

In my mind it was something like:

pkg/api/v1/foo.go:
```
type Foo struct {
    api.TypeMeta   `json:",inline"`
    ObjectMeta `json:"metadata,omitempty"`

    Spec FooSpec `json:"spec,omitempty"`
}

// Optional method, called if provided.
func (foo *Foo) ApplyDefaults() {
    if foo.Spec == nil {
        foo.Spec = NewFooSpecFromJSON(nil)
    }
}

// Optional method, called if provided.
func (foo *Foo) Validate() []api.Error {
    errs := []api.Error{}
    if foo.Spec == nil {
        errs = append(errs, api.FieldRequired("spec"))
    }
    return errs
}

func NewFooFromJSON(jsonData []byte) *Foo {
    foo := &Foo{}
    json.Unmarshal(jsonData, &foo)
    api.Init(foo)
    return foo
}

type FooSpec struct {
    FrobCount *int64 `json:"frobCount",omitempty`
    Timestamp util.Time `json:"timestamp"`
}

// Optional method, called if provided.
func (spec *FooSpec) ApplyDefaults() {
    if spec.FrobCount == nil {
        spec.FrobCount = new(int64)
        *spec.FrobCount = 13  // default value
    }
}

// Optional method, called if provided.
func (spec *FooSpec) Validate() []api.Error {
    errs := []api.Error{}
    if spec.FrobCount == nil {
        errs = append(errs, api.FieldRequired("frobCount"))
    }
    return errs
}

func NewFooSpecFromJSON(jsonData []byte) *Foo {
    spec := &FooSpec{}
    json.Unmarshal(jsonData, &spec)
    api.Init(spec)
    return spec
}
```
I'm wildly waving my hands at this point.  The key here is that the methods
that construct, default, and validate objects are right there next to the
object, not registered from some faraway place.  One thing I hope we can do
is elide anything that is redundant from these.  For example, the simplest
caller who wants to use a Foo does:

```
foo := v1.NewFooFromJSON(`{"spec":{"frobCount": 9}}`)
```

Aside: after writing it out, maybe `NewFoo(onlyFieldsWeCareAbout *foo)` is
a better signature?

This would return an initialized but not defaulted Foo.  In this case
initialized means internal fields are normalized (recall the case of
resource.Quantity, but this is rare).  The way `api.Init()` might work is
to crawl (reflection or code-gen) the structure definition of Foo, calling
the .Init() method of any field it finds.  This should probably be a
depth-first search.  That way, types do not have to be responsible for
calling all of their childrens' .Init() methods (anyone who wrote C++ knows
what happens when you forget one).

If you want default values applied:

```
foo := v1.NewFooFromJSON(`{"spec":{"frobCount": 9}}`)
api.ApplyDefaults(foo)
```

`api.ApplyDefaults()` would follow the same DFS as `api.Init()`.  In
general, this would only be done server-side, but (if we do API compat
right) it should never be WRONG for a client to call it, just sort of
pointless.

If you want to do validation of the Foo:

```
foo := ReadFooFromSomewhere()
api.ApplyDefaults(foo)
errs := api.Validate(foo)
```

`api.Validate()` would follow the same DFS pattern.  At each level, if it
called a .Validate() method on a field and got back >0 errors, it would
prepend the field name from the JSON tag to each error.  This is done
manually now and we screw it up in a lot of places.  This is a little
tricky when you have cross-sub-object validations,  inside a single object,
so maybe we need to librarify it.  The common case will be easy, anyway.

The last thing is version conversion.  I think this is largely the same as
today, but with the above pattern applied.  Every object can carry
`.ToLatest()` and `.fromLatest(obj)` methods.

Maybe we can do something similar with `.Equal()` methods for semantic
deep-equal, but that's a bit fuglier.

Maybe we can do something similar with Fuzz() (though that's test-only
code).

I want to make each API object have as little code as possible, and to
centralize that code RIGHT NEXT TO the object, but to avoid easy traps like
"if you implement a copy ctor, you have to call it on all your child
fields".  I am concerned that the DFS approach will cause a lot of churn on
some of these - maybe smart code-gen can help?  Or maybe I back off on the
"you must delegate your child fields".

**Comment by bgrant0607** [comment]
The types described above could be used by apiserver and kubelet, where the kubelet creates pods, but should not be used by any other components, such as controller manager or the scheduler. So if we had receivers implemented directly using the interface definition types, then we'd need separate types for clients.

**Comment by smarterclayton** [comment]
How would a user define YAML serialization?  BSON?  MsgPack or some other
format?  Add methods in to the same location?

If I want to implement a non-standard validation path for objects, how do I
do that (wrap the object with a different implementation of Validate)?  We
have use cases today where validation is different for a sub object
depending on what context the validation is done in (PodSpec in a
PodTemplate is validated differently than when in an RC)

Is ToLatest a concern of the object, or of the scheme that defines it?
Latest seems like something that already varies based on config, params,
and behavior.  I definitely agree it should be easy, it just doesn't seem
to be part of the objects methods.

On Thu, Jul 30, 2015 at 4:06 PM, Brian Grant <notifications@github.com>
wrote:

> The types described above could be used by apiserver and kubelet, where
> the kubelet creates pods, but should not be used by any other components,
> such as controller manager or the scheduler. So if we had receivers
> implemented directly using the interface definition types, then we'd need
> separate types for clients.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleCloudPlatform/kubernetes/issues/8190#issuecomment-126464821>
> .
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by thockin** [comment]
@bgrant0607 In terms of absolute correctness, other clients might not be well served by calling defaulting and validation, but is it actually WRONG for them to?  One published, things 
like default values basically can't change, so it may be pointless (or even counter-productive) to call those methods, but I'm not sure it's WRONG.  That said, we could put the New and Init code in the v1 pkg, and wrap all the types in methods for internal use

pkg/api/for-kube-components-only/foo.go
```
type Foo struct {
    v1.Foo
}

// Optional validate and defaults methods go here
```

Mere mortal clients get mostly dumb structs with us-defined constructors.  Super-human clients use our extended structs

**Comment by thockin** [comment]
@smarterclayton 

> How would a user define YAML serialization?  BSON?

How would a user define YAML or BSON or whatever today?  They do it themselves, and if we decide it is useful enough, we upstream it.  Maybe I am missing your question's point.

> If I want to implement a non-standard validation path

The standard Go answer if you don't like a method is to embed it and define your own, right?  Yes, some cases of validation depend on context.  In those cases, don't implement it in the context-sensitive object, but in the context-providing object.  Or use different types that embed the same core type.  Go has a type system and we're mostly not using it, to our own detriment, I think.

> Is ToLatest a concern of the object, or of the scheme that defines it?

I honestly can not wrap my head around Scheme, it's just too generic a term.  Something needs to know how to convert "abc" to "xyz".   I posit that the closer that conversion code is to the "abc" struct, the more comprehensible it is and the more likely it is to be correct.  Today that is the per-version conversion code and "xyz" is "internal".  Whenever internal changes form, a human runs through and changes every per-version conversion.  s/internal/$latest/ and you have this idea.

I agree that "latest" is a bit weird when "storage version" can be changed.  This is part of the cost of not having a neutral internal representation.  We really don't want to keep a matrix of conversions fro every version to every other version, and I'll argue that keeping more than one or MAYBE two conversions per version is ludicrous.

**Comment by bgrant0607** [comment]
I don't want clients linking against the internal implementation of apiserver. That kind of coupling is asking for trouble, IMO. Additionally, it's dangerous for us to run defaulting in our clients everywhere, since that significantly reduces test coverage for "raw" use of the API that other clients experience. And, it obscures user intent, if we were ever to try to analyze what types of requests users were sending us.

As for what to use as the conversion target if we dropped the internal representation -- I wouldn't allow that to be configurable. If someone changed the storage version from the default, they should incur additional conversions.

**Comment by thockin** [comment]
> I don't want clients linking against the internal implementation of apiserver.

My point was that defaulting and validation are NOT an implementation
detail of apiserver, they are actually part of the per-version API.
They are not very useful (perhasp even counter-productive) for most
clients, but they are part of the API contract.

> it's dangerous for us to run defaulting in our clients everywhere, since that significantly reduces test coverage for "raw"
> use of the API that other clients experience. And, it obscures user intent

I agree, and the normal MO would be that clients DON'T run defaulting.
But the alternative (having a second pkg that carried the defaulting
and validation etc as wrappers on per-version objects) is viable too.
It just moves the code further away from the structs, which means it
is less likely to be correct over time.  Not a huge deal, but worth
mentioning.

> As for what to use as the conversion target if we dropped the internal representation -- I wouldn't allow that to be
> configurable. If someone changed the storage version from the default, they should incur additional conversions.

That makes it easier.

**Comment by bgrant0607** [comment]
So I don't forget: It's worth investigating API management platforms as a solution to federation. Here's one:
https://getkong.org/

**Comment by bgrant0607** [comment]
Interesting validation library: https://github.com/pengux/check

**Comment by sinzone** [comment]
+1 for https://github.com/Mashape/kong ;)

**Comment by wojtek-t** [comment]
Ref #13969

**Comment by smarterclayton** [comment]
Added item on possible rename of PersistentVolumeClaim -> PersistentVolume (created by end user) and PersistentVolume -> StorageVolume or PhysicalStorage or just Volume (created by admin) to more closely mirror Pod -> Node (it's not a PodClaim)

**Comment by philips** [comment]
@bgrant0607 In [your comment](https://github.com/kubernetes/kubernetes/issues/8190#issuecomment-135920896) you mentioned federation and API management solutions. Are the problems rate-limiting, auth, and logging? If so we might consider vulcand.io. Or, more crazily, using grpc.io and https://github.com/gengo/grpc-gateway

**Comment by smarterclayton** [comment]
We've been discussion integrating [APIMan](http://www.apiman.io/) very closely with Openshift, and leveraging the discussed "service catalog" and "service claim" concepts to bridge the gap between lower level cluster operations to interconnect namespaces and higher level logical API management.

I agree federation is hard, although there's enough discovery aspects and overlap with services that I still believe some simple opinionated solution will allow this to function.

**Comment by bgrant0607** [comment]
@philips Thanks for the suggestions. Will take a look at Vulcan. I'd heard of it in the HTTP reverse-proxy context.  We've been talking to the GRPC team. It solves some problems, but creates others. The GRPC gateway wouldn't provide compatibility with our existing API, and we also need the Swagger support at this point.

@smarterclayton Hadn't seen apiman. If you're familiar with it that might be a good way to go.

**Comment by smarterclayton** [comment]
We're implementing more for consumers - I'm still in favor of the OpenStack
keystone pattern (service list used to seed clients with API endpoints).

On Oct 8, 2015, at 6:17 PM, Brian Grant <notifications@github.com> wrote:

@philips <https://github.com/philips> Thanks for the suggestions. Will take
a look at Vulcan. I'd heard of it in the HTTP reverse-proxy context. We've
been talking to the GRPC team. It solves some problems, but creates others.
The GRPC gateway wouldn't provide compatibility with our existing API, and
we also need the Swagger support at this point.

@smarterclayton <https://github.com/smarterclayton> Hadn't seen apiman. If
you're familiar with it that might be a good way to go.

—
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/8190#issuecomment-146702015>
.

**Comment by philips** [comment]
On Thu, Oct 8, 2015 at 8:19 PM Clayton Coleman <notifications@github.com>
wrote:

> We're implementing more for consumers - I'm still in favor of the OpenStack
> keystone pattern (service list used to seed clients with API endpoints).


Have you seen these service catalogs provide value? Do you have an example
of an application that makes good use of one? I found the service catalog
to be rather useless in OpenStack and found most people relied on
configuration instead.

In any case the service catalog and "API services library" likely should be
separate things. I see rate-limiting, auth, etc as separate concerns to
service discovery/catalog.

**Comment by philips** [comment]
On Thu, Oct 8, 2015 at 6:18 PM Brian Grant <notifications@github.com> wrote:

> @philips <https://github.com/philips> Thanks for the suggestions. Will
> take a look at Vulcan. I'd heard of it in the HTTP reverse-proxy context.
> We've been talking to the GRPC team. It solves some problems, but creates
> others. The GRPC gateway wouldn't provide compatibility with our existing
> API, and we also need the Swagger support at this point.
>

The goal is for the v2 API to be compatible with the v1 API? Won't we have
to hand roll a compat layer anyways?

What are the problems created by gRPC? etcd v3 is gRPC so any problems
would be great to know before we finalize that.

Add swagger support to grpc-gateway is one of the things on our TODO list
and a hard requirement for me before we call the etcd v3 API final.

**Comment by smarterclayton** [comment]
The OpenStack cli and fog gem as far as I knew were primarily dependent on
the keystone list for discovering the core service urls.  If that's
incorrect or has changed, then yes, I would agree.  Specifically for client
discovery however the option of tell users to invoke a "connect/login" op
on each unique API group seems excessive, so we'll end up with some list
available via http.

Client discovery of primary endpoints and API management seem mostly
orthogonal to me (and above, I was not attempting to conflate them).  But
the API management endpoint is itself one of those ones I would discover,
so that's another argument about using it.  You could potentially put it in
front, and have it rewrite your service endpoints to flow through itself.
That seems somewhat Byzantine for most environments.

On Oct 11, 2015, at 8:27 AM, Brandon Philips <notifications@github.com>
wrote:

On Thu, Oct 8, 2015 at 8:19 PM Clayton Coleman <notifications@github.com>
wrote:

> We're implementing more for consumers - I'm still in favor of the
OpenStack
> keystone pattern (service list used to seed clients with API endpoints).


Have you seen these service catalogs provide value? Do you have an example
of an application that makes good use of one? I found the service catalog
to be rather useless in OpenStack and found most people relied on
configuration instead.


In any case the service catalog and "API services library" likely should be
separate things. I see rate-limiting, auth, etc as separate concerns to
service discovery/catalog.

—
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/8190#issuecomment-147187183>
.

**Comment by rafael** [comment]
:+1 for using Kong. I've been using it myself with Kubernetes and they integrate pretty nicely.

**Comment by smarterclayton** [comment]
I think we should stop pluralizing resource names in URLs - it's a holdover from blogging sites and early web engines that tried to be clever: https://github.com/kubernetes/kubernetes/issues/18622

**Comment by sinzone** [comment]
For the ones interested small Kong + Kubernetes tutorial http://k8s.uk/using-kong-with-kubernetes.html

**Comment by thockin** [comment]
minor but annoying: "clusterIP: None" is a hack and we should instead have a "useClusterIP: false" flag.  I think similar magic values are in other fields, we should hunt those down.

**Comment by timothysc** [comment]
rfe for batched operations.  (adding count to pod additions).   

rc's fork go-routines for each api-call for pod rectification, which then triggers a bunch of work busy work.  It's woefully inefficient.  This is one such example. 

/cc @kubernetes/sig-scalability

**Comment by smarterclayton** [comment]
I'd like to see services be factored so that the user intent parts can be cleanly decoupled from the admin controlled / unsafe parts, in more of a "pod phase" pattern than our current "do everything synchronously" approach).  I.e. today nodePorts and clusterIP must be allocated with a shared lock on the entire cluster (via access to a single resource), but externalIP has no such control (allowing a service to "hijack" ports on nodes in specific cases).  We probably want to use externalIP as an allocated field as well (a controller handing them out) which means we need a consistent pattern of "ask" -> "receive" like pods provide.

**Comment by jbeda** [comment]
Agree with @smarterclayton on services.  They are a bit of a kitchen sink right now that conflate a bunch of things:
* Named label query for service discovery
* configuration information for kubeproxy (including ClusterIP allocation)
* external access control (via LB or not)

The fact that there is a "type" field smells wrong.

I'd love to see a way for other folks to replace the kube proxy with "smarter" load balancers/proxies (linkerd, weave flex) but having so much in the service makes that difficult.

As we build higher order config systems it'll be less painful to have more granular API objects as we can offload common configuration patterns to those config systems.

**Comment by smarterclayton** [comment]
We've started conceptually making services the center of our application
design universe (which has been discussed a few times in various threads
around the future of services but is worth rehashing here).  Objects above
services try to line up in a 1:1 way (even if they're 1:N, it's really 1:1,
1:2-N) so that there is a logical default.  Some examples of that are
routes (ingresses) which we by convention make 1-1 with services, TLS
serving cert secrets automatically generated for a service based on an
annotation (signed for the DNS name of the service), and naming and API
discovery.  Services and their name are the star in a topology, so
spreading out some of the other concepts on services out to other objects
where possible (especially less commonly used options) is a good long term
approach.  Keeping the "name" at the center, and the "how" at the edges
opens up more doors for customization.

**Comment by thockin** [comment]
NIT: 

```
     PersistentVolumeReclaimPolicy PersistentVolumeReclaimPolicy `json:"persistentVolumeReclaimPolicy,omitempty"`
```

field and JSON should not have "PersistentVolume" in them

**Comment by mikedanese** [comment]
Remove node.spec.unschedulable. Replace with a taint.

**Comment by thockin** [comment]
discriminated unions to be explicit rather than implicit:

https://github.com/kubernetes/kubernetes/issues/24238#issuecomment-209780488

**Comment by thockin** [comment]
Endpoints as subresources:

The link between a Service and its Endpoints object is very weak (same name). It might be interesting in v2 API to manifest this as a subresource of Service. We will one day need to paginate Endpoints, but I think that still applies in both cases. Not sure if watch on sub-resources would work, but we could still have an Endpoints object, and carry the subresource as a reference to a more randomly named Endpoints (or a list of them when paginated, or a selector)

**Comment by thockin** [comment]
Rename downward API `items` to `files`.

The downward API volume source established a pattern of using Items for the array variable for a list of projections into a volume. It should be called Files instead, but it looks like we are going to follow the existing pattern in #17554 for consistency, so this volume should also be refactored in the next version of the pod API.

**Comment by bgrant0607** [comment]
My plan for this is to eventually migrate all existing "core" v1 APIs to relevant groups and to deprecate v1. The first of these is actually ReplicationController/ReplicaSet. The second will likely be Events. 

It's a required step towards the layered architectural model, as well as being necessary to move towards independent evolution of logical subparts of the API surface and to fix things that really need to be fixed, such as Endpoints scalability and Service/Ingress evolution. We'll have to prioritize other changes.

**Comment by thockin** [comment]
Maybe it's just me, but there's a low-level annoyance I experience every time I try to look at API files - we document our API fields in terms of javascript-style names (leading lower-case) but Go demands we use leading upper-case.  This makes for inconsistent comments and docs.  Worse, Go will ignore case for JSON keys if it needs to, so there are probably lurking issues.

So my proposal is that if/when we start the v2 process, we consider explicitly using Go-style field names (leading upper-case).  Other APIs (e.g. Docker) do it, and it's not so bad.

As a nice side-effect, `go vet` will stop complaining at us for a bunch of things.

**Comment by thockin** [comment]
Adding here so we don't forget (I hope).  

Node.status.addresses uses 'type' as merge key but that is not sufficiently unique.

https://github.com/kubernetes/kubernetes/pull/73977

**Comment by thockin** [comment]
https://github.com/kubernetes/kubernetes/issues/81301

Probe.SuccessThreshold validation is contextual and ugly.  "must be 1" in an API field is silly.

**Comment by bgrant0607** [comment]
Associative lists with non-standard keys (and even multi-field keys) were totally a mistake. We should have just used maps. Merging would have been so much simpler.

**Comment by alvaroaleman** [comment]
> Associative lists with non-standard keys (and even multi-field keys) were totally a mistake. We should have just used maps. Merging would have been so much simpler.

@bgrant0607 So [this](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#lists-of-named-subobjects-preferred-over-maps) is not true anymore? Or is it kept as a convention, but third parties that e.G. develop CRD-based APIs should consider using maps instead?

**Comment by wojtek-t** [comment]
As mentioned in https://github.com/kubernetes/kubernetes/issues/73527, we should use proper LabelSelector types for selector (instead of `map[string]string` as e.g. in Service or even `string` as in ListOptions) - they cost to much when being processed later many times.

**Comment by dprotaso** [comment]
related to #92226 it'd be nice to drop service links - or make them opt-in rather than opt-out.

**Comment by bgrant0607** [comment]
This issue should really be moved to a doc (or multiple docs, as not everything is API machinery) and updated.

**Comment by MadhavJivrajani** [comment]
/remove-kind design
/kind feature

`kind/design` will soon be removed from `k/k` in favor of `kind/feature`. Relevant discussion can be found here: https://github.com/kubernetes/community/issues/5641

**Comment by sftim** [comment]
Given https://github.com/kubernetes/kubernetes/issues/8190#issuecomment-645690618, should we close this?

**Comment by bgrant0607** [comment]
I recommend closing. This issue is not actionable at this point.

**Comment by thockin** [comment]
If we ever do core/v2 (we should!!) this thread is a goldmine of ideas
