### ISSUE TITLE
Failure building tarball for gce deployment

### ISSUE THREAD

**Issue by pmorie** [kubernetes/kubernetes#8197]
I reliably get the following error while doing `go run hack/e2e.go --build -v`:

```
--- FAIL: TestSelectPlugin (0.00s)
        exec_test.go:77: Failed to select the desired plugin: Network plugin "test81" failed init: Invalid exec plugin. Executable 'test81' does not have correct permissions.
--- FAIL: TestSelectVendoredPlugin (0.00s)
        exec_test.go:94: Failed to select the desired plugin: Network plugin "mycompany/test887" failed init: Invalid exec plugin. Executable 'mycompany/test887' does not have correct permissions.
--- FAIL: TestPluginSetupHook (0.00s)
        exec_test.go:146: Expected nil: fork/exec /tmp/fake/plugins/net/test81/test81: permission denied
        exec_test.go:151: Expected nil
        exec_test.go:155: Mismatch in expected output for setup hook. Expected 'setup podNamespace podName dockerid2345', got ''
--- FAIL: TestPluginTearDownHook (0.00s)
        exec_test.go:168: Expected nil
        exec_test.go:173: Expected nil
        exec_test.go:177: Mismatch in expected output for teardown hook. Expected 'teardown podNamespace podName dockerid2345', got ''
FAIL
FAIL    github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet/network/exec      0.027s
```

**Comment by goltermann** [comment]
We’re going through old support issues and asking everyone to direct your questions to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes). 

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases. 

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.
