### ISSUE TITLE
1.19: stop serving admissionregistration.k8s.io/v1beta1 by default

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#82021]
The admissionregistration.k8s.io/v1 API is available in v1.16 and the v1beta1 API deprecated.

Stop serving the admissionregistration.k8s.io/v1beta1 API by default in v1.19.

/area admission-control
/kind cleanup
/sig api-machinery
/assign

**Comment by kbruner** [comment]
Hello from the bug triage team! This issue has not been updated for a long time, so I'd like to check what's the status. The code freeze is starting June 25th (about 4 weeks from now) and while there is still plenty of time, we want to ensure that each PR has a chance to be merged on time.

As the issue is tagged for 1.19, is it still planned for this release?

**Comment by liggitt** [comment]
no, removal has been retargeted at 1.22

**Comment by liggitt** [comment]
covered by code to automatically stop serving APIs once their declared removed release arrives
