### ISSUE TITLE
Server-side Apply: Ownership not tracked for scale subresource

### ISSUE THREAD

**Issue by apelisse** [kubernetes/kubernetes#82046]
Whenever someone sends a scale sub-resources request, the managed fields are not changed for that specific request, which means that the scale will typically not grab the ownership of the "replicas" field. This is obviously a bug, but we don't exactly know how to fix it for now.

**Comment by lavalamp** [comment]
There still exists a "new" deployment object, though: https://github.com/kubernetes/kubernetes/blob/master/pkg/registry/apps/deployment/storage/storage.go#L300

**Comment by apelisse** [comment]
Yeah, we might be able to address this bug specifically by updating the managed fields there somehow

**Comment by julianvmodesto** [comment]
If we write a single field manager named `/scale` to storage such that it takes ownership of `.spec.replicas`, then any `kubectl apply`s would conflict if they attempt to take ownership of `.spec.replicas` as intended.

Also, the HorizontalPodAutoscaler and a user can share ownership of `.spec.replicas` w/ `kubectl scale`. Is this the intended behavior, or do we want `kubectl scale` to conflict?

**Comment by lavalamp** [comment]
Setting `.spec.replicas` via scale should be exactly the same as setting it by using the main endpoint, conflicts and all.

**Comment by julianvmodesto** [comment]
We could use the same mechanism proposed in https://github.com/kubernetes/enhancements/pull/923 to declare the field manager on the scale subresource.

If we expect scale to produce a conflict, then ideally we do use a server-side apply.

Will users eventually receive conflicts for [other imperative `kubectl` commands like `kubectl scale`](https://kubernetes.io/docs/tasks/manage-kubernetes-objects/imperative-command/#how-to-update-objects)?

**Comment by lavalamp** [comment]
To be clear. Using scale via PUT or non-apply patch should not produce a conflict. It should force, causing the folks APPLYing to the base resource (or APPLYing to scale) to get a conflict.

I'd expect `kubectl scale` to force and never give a conflict; you'd get a conflict when you subsequently tried to APPLY and own the `.spec.replicas` field.

Make sense?

**Comment by julianvmodesto** [comment]
Ahhh yes

**Comment by jennybuckley** [comment]
Is it really right to not go through, say, the regular deployment mutating admission/webhooks when someone modifies a deployment through `/scale`? Because that seems to be the current behavior.

For example, if I made a mutating webhook which maintains a label on deployments based on the replica count, it wouldn't work since someone could get around it by doing a `/scale`

**Comment by lavalamp** [comment]
No, that is a bug, I think.

**Comment by jennybuckley** [comment]
I think it's a bug too, but we already [support](https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#request) making, say, a `deployment/scale` webhook, which looks at the `autoscaling/v1.Scale` being sent to that endpoint. So if we wanted to fix this for admission in general, I think we would have to call both the scale admission chain and then the regular admission chain.

Not sure if that's feasible, or if we should just do what @apelisse was suggesting in https://github.com/kubernetes/kubernetes/issues/82046#issuecomment-525930084 and just do the managed fields update (since it's just for the one field)

**Comment by julianvmodesto** [comment]
Seems lower priority, but I think we'd want to track a TODO somewhere for similar changes for updating the manager for /scale on CRDs

https://github.com/kubernetes/apiextensions-apiserver/blob/aef9cf9c74430318df9fb4ddc9a728d7666e9815//pkg/registry/customresource/etcd.go#L239

**Comment by julianvmodesto** [comment]
This is related to https://github.com/kubernetes/kubernetes/issues/84530

**Comment by julianvmodesto** [comment]
> So if we wanted to fix this for admission in general, I think we would have to call both the scale admission chain and then the regular admission chain.
> 
> Not sure if that's feasible, or if we should just do what @apelisse was suggesting in #82046 (comment) and just do the managed fields update (since it's just for the one field)

Since we're tracking the admission chain issue in https://github.com/kubernetes/kubernetes/issues/84530, it seems possible to for now do the managed fields update for /scale sooner.

**Comment by liggitt** [comment]
deployment scale subresource addressed in 1.21, remaining scale subresources will be addressed before closing this

/milestone v1.22

**Comment by apelisse** [comment]
> deployment scale subresource addressed in 1.21

The PR didn't merge and was milestone-cleared.
