### ISSUE TITLE
Add Priority field to the Plugin struct in the Scheduling framework

### ISSUE THREAD

**Issue by draveness** [kubernetes/kubernetes#82050]
/sig scheduling
/priority important-soon
/assign

**What would you like to be added**:

Add an extra `Priority` field to the Plugin struct in the Scheduling framework which controls the execution order of the scheduling framework plugins

```go
type Plugin struct {
	// Name defines the name of plugin
	Name string
	// Weight defines the weight of plugin, only used for Score plugins.
	Weight int32
	// Weight defines the priority of plugin, which defines the execution order the plugins.
	Priority int32
}
```

> An alternative name could be `order`

The cluster admin can override the default order for plugins in each extension point. This gives the administrator the maximum flexibility regarding scheduler behaviour and enables the scheduler to adapt to cluster usage. Please note that the order must be a positive integer, also, when providing an equal ordering for many plugins, the scheduler will determine the order and won't guarantee that the order will remain the same between them. 

**Why is this needed**:

**Currently**, enabled plugins are called in the order specified here, after default plugins. If they need to
be invoked before default plugins, default plugins must be disabled and re-enabled here in the desired order.

When converting the binding function to a default binder plugin, the custom plugin has to run before the default plugins. otherwise, they won't be called since the default plugin is interested in all the pods.

https://github.com/kubernetes/kubernetes/blob/8aca2c148018770e4ad0f4b21d98a81ff714f731/plugin/pkg/scheduling/defaultbinder/plugin.go#L43-L57

The execution order is also important in the filter plugin since the execution order of predicates is quite important

https://github.com/kubernetes/kubernetes/blob/586d200e35163d441cd4d6411a957a47f4c0b895/pkg/scheduler/algorithm/predicates/predicates.go#L133-L154

**Reference**
+ https://github.com/kubernetes/community/blob/master/contributors/design-proposals/scheduling/predicates-ordering.md#end-user-ordering

**Comment by draveness** [comment]
cc/ @bsalamat @ahg-g @hex108

**Comment by hex108** [comment]
> Enabled plugins are called in the order specified here, after default plugins. If they need to
be invoked before default plugins, default plugins must be disabled and re-enabled here in the desired order.

I think `default plugins` are also needed be configured in config file if they are needed, e.g. if there are multiple bind plugins: `bindPlugin1`, `bindPlugin2`, `defaultBindPlugin`, we could configure `bindPlugin1` and `defaultBindPlugin` in order if we want use them. Then enabled plugins are called in the order specified.

**Comment by draveness** [comment]
> I think `default plugins` are also needed to be configured in config file if they are needed, e.g. if there are multiple bind plugins: `bindPlugin1`, `bindPlugin2`, `defaultBindPlugin`, we could configure `bindPlugin1` and `defaultBindPlugin` in order if we want to use them. Then enabled plugins are called in the order specified.

Emmm.. Sorry, it's the current approach on how to reorder the plugins, I'll update the statement...

**Comment by Adirio** [comment]
If I understand correctly you want to provide a explicit way of ordering plugins instead of the implicit same-order-as-they-are-configured current way. Integer priorities are ok if you provide a deterministic way of solving draws. Basically the current way is a single priority level and the draw-solving mechanism is definition order, starting by the default plugins. This draw solving mechanism can also be used for multi-level set ups (like the integer priority you mentioned).

About the implementation, I don't know if this has to be a field of the `Plugin` struct or just a value that gets passed to the registering function. Priority levels are usually implemented as a collection of queues or arrays (in our case are filters are not consumed, slices are the proper way). Each of these queues/arrays represent a priority level. The collections could be a simple map, where the priority level is the key and the values would be the slice of plugins registered at that endpoint. Keeping some kind of sorted keys would help during execution.

If you go for this aproach, default plugins could be assigned any priority level by default, while the cluster admin could still change it. Limiting the priority levels to positive integers is not that important. Imagine we set default plugins as prio 0 so that they are executed first and a user develops a plugin that needs to go before prio 0. He could use prio -1 if we do not limit it or he can change all default plugins to prio 1 so that he can use prio 0 for his plugin.
