### ISSUE TITLE
Add AuditEvent annotation 'swagger.io/operationId' support to APIServer

### ISSUE THREAD

**Issue by hh** [kubernetes/kubernetes#82089]
- [audit/v1 verb](#sec-1)
- [audit/v1 annotations](#sec-2)

APISnoop generates test and conformance coverage of the kubernetes api.

We compare audit logs to the OpenAPI spec.

Specifically match each `audit.k8s.io/v1` event to a `swagger.io/operationId`

This currently takes around 30 minutes utilizing 56 Xeon Cores to process 300k+ audit events using [cncf/apisnoopregexp](https://github.com/cncf/apisnoopregexp/blob/master/cmd/rmatch/rmatch.go#L51-L78)

Ideally the `audit.k8s.io/v2` will include a high level field mapping to the `swagger.io/operationId`.

But until then we could create a PR for APIServer using `audit.k8s.io/v1/annotations` to include `swagger.io/operationId` or similar.

-   **swagger.io/path:** <https://swagger.io/specification/v2/#pathsObject> includes <https://swagger.io/specification/v2/#pathTemplating> (our regexes are based on this)
-   **swagger.io/http_method:** each path has a hash, one of get, put ,post, delete, options, head, patch or parameters - see <https://swagger.io/specification/v2/#pathItemObject>
-   **swagger.io/operation_id:** each method maps to a unique operation id <https://swagger.io/specification/v2/#operationObject>

```json
{
  "kind": "Event",
  "apiVersion": "audit.k8s.io/v1",
  "level": "Request",
  "auditID": "6dfb7495-7cae-44d7-a341-b71676ce2a11",
  "stage": "ResponseComplete",
  "requestURI": "/api/v1/namespaces/kube-system/pods/kube-controller-manager-bootstrap-e2e-master",
  "verb": "get",
  "userAgent": "kubelet/v1.17.0 (linux/amd64) kubernetes/bdfc8f6",
  "annotations": {
    // ADDING THIS WOULD SAVE TIME AND MONEY
    "swagger.io/operationId": "readCoreV1NamespacedPod"
  }
}
```

# audit/v1 verb<a id="sec-1"></a>

Not a directy mapping between 'swagger.io/http_method' and  'x-kubernetes-action'.
We use a many to one to map back and doesn't feel very clean.
Adding the one to one mapping using operation_id feels like the best strategy.

[k8s.io/apiserver/pkg/apis/audit/v1/types.go#verb](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/apis/audit/v1/types.go#L85:L87)

```go
// Verb is the kubernetes verb associated with the request.
// For non-resource requests, this is the lower-cased HTTP method.
Verb string `json:"verb" protobuf:"bytes,5,opt,name=verb"` 
```

# audit/v1 annotations<a id="sec-2"></a>

Adding an annotation here wouldn't require an API update, just some minor changes to APIServer when creating the audit log and annotation.

[k8s.io/apiserver/pkg/apis/audit/v1/types.go#annotations](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/apis/audit/v1/types.go#L129:L135)

```go
// Annotations is an unstructured key value map stored with an audit event that may be set by
// plugins invoked in the request serving chain, including authentication, authorization and
// admission plugins. Note that tbest way forward.hese annotations are for the audit event, and do not correspond
// to the metadata.annotations of the submitted object. Keys should uniquely identify the informing
// component to avoid name collisions (e.g. podsecuritypolicy.admission.k8s.io/policy). Values
// should be short. Annotations are included in the Metadata level.
// +optional
Annotations map[string]string `json:"annotations,omitempty" protobuf:"bytes,15,rep,name=annotations"`
```

**Comment by tallclair** [comment]
I'm curious why you're using a regex to parse the URL rather than using the objectRef? Is there information in the URL that is missing from the objectRef, or is it actually faster to avoid parsing the json?

**Comment by hh** [comment]
objectRef will get us to the specific schema object:
https://swagger.io/specification/v2/#schemaObject

There is a one to many relationship between the objectRef and the operation id: 
https://swagger.io/specification/v2/#operationObject

The operation id is unique and gives context for the specific usage of a particular objectRef / kind.

Is there a way for us to calculate the object id from the json available in the audit log in a way other than trying to match the swagger via the path (with a regex) and the verb/action?

**Comment by zachmandeville** [comment]
That's a good question, @tallclair .  We want to confidently map an audit event to its corresponding operationId within a swagger.json.  The objectRef feels nearly correct, but the relation between its values and the swagger.json didn't feel clear enough for confidence.

For example, The contents of the objectRef change event to event.  Some have `name` and `namespace` and some don't, and some have `resource` and `subresource` and some don't. Checking the presence of certain keys can help construct the format of the path we should look up, but the logic felt more assumptive than a regex matching.  

An issue we're facing, though, is that the regex parsing isn't giving consistent results.  Running the same data through two systems that have the same underlying logic in their regex parsers is producing different numbers.  This issue proposes a guaranteed way to match event to operationIds, but if there's an authoritative way to do it within the existing event data, we'd love that too.

**Comment by lavalamp** [comment]
The openapi spec doc should have enough information to build a deterministic mapping from url -> operation ID if you want to do that. Regexps don't seem like the right tool for that job, unless you're writing a script that processes the "paths" section of the openapi spec document and combines all the paths into an enormous, monster regexp. Probably better to just write something or use e.g. https://github.com/emicklei/go-restful/blob/master/curly.go which is I think what we use under the hood if I followed the code right.

OperationID isn't actually something tracked by the system, it's generated and massaged to make the spec read OK-ish; I think it's computed in post-processing and not even available to the handlers, and (IIRC) it can change from release to release depending on what needs disambiguation. So, putting it in audit events is going to be a tough sell.

Finally I don't think we'd want add this without it being useful for the more general case--your use is pretty specialized.

**Comment by lavalamp** [comment]
...and it's probably good to make sure you use the live spec document from the cluster in question to be certain you don't have any skew issues.

**Comment by lavalamp** [comment]
(P.S. if you are using regexp due to something like working with a DB, I suggest just pre-processing the data to add whatever identifier you want.)

**Comment by hh** [comment]
That's excellent information @lavalamp

We've tried preprocessing before but still had to spend a lot of Memory and CPU to match the path and verb to locate the correct operation id.

We could try and retrieve the live spec during our prow jobs and save it, however I'm unsure if this makes sense for Conformance as it's my understanding we are wanting to compare against a static definition.

I think if we can find a way to map this efficiently it could continue to be one way, but we would need to do something similar to go-restful/curly.go.

Regarding `area/conformance`:

- Do we want operation_id to continue to be the primary metric we want to be using for measuring Conformance? 
- Do we want to process the swagger.json spec from the live apiserver or the one  in git matching the api server git commit hash. (or compare the two)

/cc @smarterclayton @timothysc @belamaric @spiffxp

**Comment by johnbelamaric** [comment]
> Do we want operation_id to continue to be the primary metric we want to be using for measuring Conformance?

Not in the long run. However, if it's just for the purpose of calculating coverage it's still at least roughly meaningful. I don't see a need to shift right now. Instead, let's get the behavior lists done and then use those. I think I am the blocker right now on that, I need to get back and add more implementation details to the KEP.

> Do we want to process the swagger.json spec from the live apiserver or the one in git matching the api server git commit hash. (or compare the two)

Interesting question. Coverage is trying to measure our tests, not really measuring the specific cluster. If the issue is that the mappings may change a little and give inaccurate coverage info, then we should retrieve the spec from the cluster. However, if we need to do pre-processing of the spec, and can do that once instead of every run, then I am OK with not pulling the exact spec from every cluster, but capturing them by version.

**Comment by lavalamp** [comment]
It's the opposite, you need to pre-process the audit data.

You should use a pre-built (i.e., minimal) spec for judging conformance
coverage.

You can use the cluster's live spec for determining if the cluster has
absent functionality or has disabled it, instead of running the tests
anyway and claiming it's broken. (Either way it'd be a failure, of
course, unless there's some sort of profile thingy.)

Part of conformance should compare the cluster's live spec to the expected
one-- they don't have to be exactly the same but the cluster shouldn't be
omitting resources, functionality, or fields.

Another test: if the cluster advertises a resource, and the test equipment
has permissions, you should be able to write and read objects with the
normal verbs.

**Comment by johnbelamaric** [comment]
@hh is talking about how we measure the progress of our conformance test development/program, not how we measure the conformance of a specific cluster. That is, we are measuring coverage right now by looking at the APIs hit by the e2e conformance tests vs the ones defined in the spec for things that are "potential conformance" APIs - meaning non-optional GA things. 

> Part of conformance should compare the cluster's live spec to the expected
one-- they don't have to be exactly the same but the cluster shouldn't be
omitting resources, functionality, or fields.

This would be uncovered today by failing conformance tests that try to use those resources, functionality, or fields. We possibly could add a tests that compares specs, but that doesn't quite get to the meat of it since without actually trying the functionality we don't know if it's just false advertising.

> Another test: if the cluster advertises a resource, and the test equipment
has permissions, you should be able to write and read objects with the
normal verbs.

If you are suggesting a sort of resource-agnostic test, I think it's is an interesting idea. It's essentially testing that the cluster doesn't lie in its discovery. But I don't think it would be simple to do, and we can't really know the consequences of creating arbitrary (unknown) resources, so I am not sure that's feasible.

**Comment by lavalamp** [comment]
Ah, OK.

> We possibly could add a tests that compares specs, but that doesn't quite get to the meat of it since without actually trying the functionality as we don't know if it's just false advertising.

I think both are needed-- not having the right spec will also break clients. How well do we cover the spec in the test suite?

> If you are suggesting a sort of resource-agnostic test, I think it's is an interesting idea. It's essentially testing that the cluster doesn't lie in its discovery. But I don't think it would be simple to do, and we can't really know the consequences of creating arbitrary (unknown) resources, so I am not sure that's feasible.

I think API Machinery should own this, it's been thought of numerous times before and just never prioritized. There's probably issues out there for it already. We'd need some example "inert" objects to run it, but that seems like a reasonable thing to require.

**Comment by hh** [comment]
We can move the discover discussion to another issue, but I was able to process the data in a way that reduced load time considerably.

We shouldn't need to add operationId to the logs, so I'm closing.

**Comment by hh** [comment]
Thanks for the suggestion  @lavalamp
> (P.S. if you are using regexp due to something like working with a DB, I suggest just pre-processing the data to add whatever identifier you want.)
