### ISSUE TITLE
Creating containers on systemd systems is broken

### ISSUE THREAD

**Issue by rjnagal** [kubernetes/kubernetes#8215]
from IRC:

using CgroupParent=/ and moving all containers to top-level causing wrong scope name creation on systemd systems. We should fix this in libcontainer, but this needs a workaround in kube for now:

kubelet[864]: E0513 22:17:27.633873     864 manager.go:1436] Failed to create pod infra container: API error (500): Cannot start container 5382b876ff71055afc01ca53c763655dfe67d96d1444cc5e7cf2e1a034d6fd14: 
System error: Unit name /-5382b876ff71055afc01ca53c763655dfe67d96d1444cc5e7cf2e1a034d6fd14.scope is not valid.

**Comment by vmarmol** [comment]
Will:
- Revert #8084
- Add short-term fix for Container VM
- Work on getting the right fix in libcontainer.

The last one will probably take a while since we'd need to add a startup option to Docker to say "I know it's a systemd system, but please pretend it is not". The community seems to be supportive of this last time I checked so we should be able to get it in.

**Comment by rjnagal** [comment]
I am not sure we can rely on resetting docker daemon flags on all platforms.

Another fix might be to create a pod-level service/cgroup. All containers for the cgroup can go under that.

**Comment by vmarmol** [comment]
Looked a little more into this. The issue is that Docker turns around and asks systemd to create the unit. `/` is not valid in the unit name so we actually can't use `--cgroup-parent` with containers not relative to our current container.

The fix will probably be to get libcontainer to not use systemd if `--cgroup-parent` is specified. That will take time to rollout.

In the meantime, I will enable this on non-systemd setups.

**Comment by rjnagal** [comment]
Is it worth doing this now and have to think about two different setups? As we start making change over this, we always have to go back and verify these on systemd machines.

WDYT about creating a top-level pod container or a pod service?

**Comment by justinsb** [comment]
@vmarmol I really can't claim to understand this issue, but I hit it while trying to run with Ubuntu Vivid Vervet (which runs systemd), as part of my neverending quest to find a supported AWS image that doesn't require a reboot.

I was able to get it to work by doing this in kubelet:

```
   {% set system_container = "--system-container=/system" -%}
   {% set cgroup_root = "--cgroup_root=/" -%}
 {% endif -%}
+{% if grains['oscodename'] == 'vivid' -%}
+  {% set cgroup_root = "--cgroup_root=docker" -%}
+{% endif -%}
```

But, honestly, I have absolutely no idea what I am doing here.  I guess I'm setting the root of the cgroup hierarchy to use, and that Docker infers the systemd unit name to use from the cgroup path; but I don't know why we change this, whether I need to set up other things to match etc.

And of course the most important question - should I set it to be "k8s" instead of "docker" :-)

Any quick pointers you can give me on what else I might need to do?  It did pass my initial hand-testing though, without a reboot, so hopefully I can get an OK from you and then I can get this submitted (including support for systemd in our salt files on non-Redhat systems, which is mostly just a matter of changing the tests)

**Comment by vmarmol** [comment]
We don't do a particularly good job of detecting when we can set this option. We check if the distro is Debian instead of whether is has systemd or not. Libcontainer has a "feature" wherein if systemd is present it behaves very differently. We're working on trying to remove that and make this work.

**Comment by justinsb** [comment]
I believe we have now addressed the issues with running with systemd.  Anyone object if I close?
