### ISSUE TITLE
[Failing Test] deletion error in ci-kubernetes-e2e-gce-scale-performance

### ISSUE THREAD

**Issue by jimangel** [kubernetes/kubernetes#82182]
**Which jobs are failing**:
- ci-kubernetes-e2e-gce-scale-performance

**Which test(s) are failing**:
- ClusterLoaderV2
- testing/load/config.yaml

**Since when has it been failing**:
Started failing on 8/28 at around 10.02 PDT

**Testgrid link**:
https://testgrid.k8s.io/sig-release-master-informing#gce-master-scale-performance

**Reason for failure**:
```
namespace test-d5g7lv-41 object small-deployment-37 deletion error: Delete https://35.185.88.244/apis/apps/v1/namespaces/test-d5g7lv-41/deployments/small-deployment-37: dial tcp 35.185.88.244:443: connect: connection refused
namespace test-d5g7lv-48 object small-deployment-279 deletion error: Delete https://35.185.88.244/apis/apps/v1/namespaces/test-d5g7lv-48/deployments/small-deployment-279: dial tcp 35.185.88.244:443: connect: connection refused
namespace test-d5g7lv-3 object small-deployment-238 deletion error: Delete https://35.185.88.244/apis/apps/v1/namespaces/test-d5g7lv-3/deployments/small-deployment-238: dial tcp 35.185.88.244:443: connect: connection refused
namespace test-d5g7lv-30 object small-deployment-159 deletion error: Delete https://35.185.88.244/apis/apps/v1/namespaces/test-d5g7lv-30/deployments/small-deployment-159: dial tcp 35.185.88.244:443: connect: connection refused
namespace test-d5g7lv-25 object small-deployment-223 deletion error: Delete https://35.185.88.244/apis/apps/v1/namespaces/test-d5g7lv-25/deployments/small-deployment-223: dial tcp 35.185.88.244:443: connect: connection refused
namespace test-d5g7lv-46 object small-deployment-229 deletion error: Delete https://35.185.88.244/apis/apps/v1/namespaces/test-d5g7lv-46/deployments/small-deployment-229: dial tcp 35.185.88.244:443: connect: connection refused
namespace test-d5g7lv-27 object small-deployment-65 deletion error: Delete https://35.185.88.244/apis/apps/v1/namespaces/test-d5g7lv-27/deployments/small-deployment-65: dial tcp 35.185.88.244:443: connect: connection refused
namespace test-d5g7lv-45 object small-deployment-28 deletion error: Delete https://35.185.88.244/apis/apps/v1/namespaces/test-d5g7lv-45/deployments/small-deployment-28: dial tcp 35.185.88.244:443: connect: connection refused
namespace test-d5g7lv-12 object small-deployment-144 deletion error: Delete 
```

**Anything else we need to know**:

k/k diff from the last successful run to the first failed run: [419dccb7b...d7ecc8523](https://github.com/kubernetes/kubernetes/compare/419dccb7b...d7ecc8523?)

/milestone v1.16
/priority critical-urgent
/kind failing-test
/cc @alejandrox1 @alenkacz @Verolop @soggiest 
/cc @kubernetes/sig-scalability-test-failures
/cc @wojtek-t @shyamjvs

**Comment by lachie83** [comment]
This appears to be a flake 8/30 8/31 runs are GREEN

**Comment by alejandrox1** [comment]
Failed again. Moving it back to "new"

**Comment by oxddr** [comment]
I will try to have a look at this. 
/assign @oxddr

**Comment by alejandrox1** [comment]
It appears that this one is a pure flake.
Will keep it open to monitor the job's health

**Comment by jkaniuk** [comment]
Problem was caused by slow etcd (both main and event one), that resulted in apiserver unresponsiveness.

Both etcd instances failed, then apiserver:
Both etcd logged: wal: sync duration ~22s, expected less than 1s
Both etcd were restarted
It seems that etcd-events stopped responding after the restart.
Apiserver did not fully recover afterwards.
etcd Version: 3.3.10

etcd.log
2019-08-30 01:34:26.561016 I | [...]
2019-08-30 01:34:28.000542 W | etcdserver: read-only range request "key:\"/registry/health\" " with result "error:context deadline exceeded" took too long (2.000140378s) to execute
...
2019-08-30 01:34:35.619528 W | etcdserver: read-only range request "key:\"/registry/services/endpoints/kube-system/kube-controller-manager\" " with result "error:context canceled" took too long (9.999977716s) to execute
...
2019-08-30 01:34:39.560918 W | etcdserver: timed out waiting for read index response (local node might have slow network)
restart:
2019-08-30 01:34:47.445502 N | pkg/osutil: received terminated signal, shutting down...
...
2019-08-30 01:34:47.510468 W | wal: sync duration of 21.970410317s, expected less than 1s
...
2019-08-30 01:34:50.260337 I | etcdmain: etcd Version: 3.3.10
...
running fine afterwards (a bit slow, but probably due to system load)


etcd-events.log
2019-08-30 01:33:54.108650 I | mvcc: store.index: compact 2047829
2019-08-30 01:33:54.693529 I | mvcc: finished scheduled compaction at 2047829 (took 544.24288ms)
2019-08-30 01:34:32.987360 W | etcdserver: timed out waiting for read index response (local node might have slow network)
2019-08-30 01:34:32.987503 W | etcdserver: read-only range request "key:\"/registry/events/kube-system/fluentd-gcp-v3.2.0-8pq9f.15bf8b6e91a55af8\" " with result "error:etcdserver: request timed out" took too long (7.00043071s) to execute
restart:
2019-08-30 01:34:47.466748 N | pkg/osutil: received terminated signal, shutting down...
...
2019-08-30 01:34:47.513433 W | wal: sync duration of 21.558207802s, expected less than 1s
...
2019-08-30 01:34:49.722529 I | etcdmain: etcd Version: 3.3.10
...
2019-08-30 01:34:51.296643 I | embed: ready to serve client requests
2019-08-30 01:34:51.298425 N | embed: serving insecure client requests on [::]:4002, this is strongly discouraged!
proto: no coders for int
proto: no encoder for ValueSize int [GetProperties]
END log

**Comment by jkaniuk** [comment]
There was one Persistent Disk attached to the master instance that reported being unhealthy during the window of 01:34:40-01:37:30 GMT.

Root cause is then unrelated to Kubernetes.
There is still an issue of etcd and apiserver that did not recover afterwards.
It could be related to data corruption on the etcd PD.

**Comment by alenkacz** [comment]
@jkaniuk 👋 is someone still working on this?

**Comment by jkaniuk** [comment]
There is ongoing work on Priority and Fairness for API Server Requests:
https://github.com/kubernetes/enhancements/issues/1040
which should help with/fix the problem of apiserver not recovering under load.

The problem did not occur recently.

**Comment by lavalamp** [comment]
The claim is that apiserver was so loaded it couldn't reconnect to etcd? That doesn't seem super probable to me, can you say more specifically what was happening to it to keep it from recovering?

**Comment by jkaniuk** [comment]
Problem started with long response times from etcd, but later on apiserver was overwhelmed with incoming requests (lists by controllers which watches timed out, lost leases, etc.) and never managed to clear its incoming queue. Priority and Fairness should help with recovering in such cases.
Separately, we also discovered problem with go http library, where load on incoming requests to apiserver causes etcd connection to degrade https://github.com/kubernetes/kubernetes/issues/82069. That was probably one of the causes as well.

**Comment by liggitt** [comment]
Is this still a current issue?

**Comment by jkaniuk** [comment]
It should not be 1.17 milestone at this point.
I think we could close this issue.
As mentioned above, this specific issue did not repeat and there is ongoing, independent work that address similar failures (kubernetes/enhancements#1040, but it seems to slip into further releases)

**Comment by alenkacz** [comment]
Thanks @jkaniuk 

/close
