### ISSUE TITLE
Kubelet sometimes fails to GetRef for probes

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#8239]
Specifically:
1. Start a pod with a readiness probe.
2. Restart kubelet
3. Force the readiness probe to fail
4. Observe the event does not get generated and the log says "No ref for pod ..."

**Comment by yifan-gu** [comment]
Sounds like upon restarting the kubelet, the refs are all gone...

**Comment by yujuhong** [comment]
What I saw from a quick code search (may not be 100% accurate):
The refs in the reference managers are all gone after the restart. We only set the refs in runContainerInPod (dockertools/manager), and this function would never be called after the restart because the containers were alive.

Perhaps we should fall back to generating the refs in this case.
