### ISSUE TITLE
Move all scheduler API-related code to a single place

### ISSUE THREAD

**Issue by ahg-g** [kubernetes/kubernetes#82390]
Currently there are two api packages in the scheduler: [scheduler/api](https://github.com/kubernetes/kubernetes/tree/master/pkg/scheduler/api/) and [scheduler/apis](https://github.com/kubernetes/kubernetes/tree/master/pkg/scheduler/apis/), we should move everything under scheduler/api to scheduler/apis:
 
1) configuration-related APIs, specifically Policy, should be moved to apis/config, it should be under v1 though, and should be double register under both ```apiVersion: kubescheduler.config.k8s.io/v1``` and ```apiVersion: v1```

2) extender-related apis should move to apis/extenders

/sig scheduling

**Comment by Huang-Wei** [comment]
`scheduler/apis` makes sense.

`api` folder exists in API machinery due to historic reason, that folder doesn't represent another api instead of the core API.

**Comment by danielqsj** [comment]
@ahg-g @Huang-Wei I'd like to take this task.
/assign

**Comment by SataQiu** [comment]
Hi @danielqsj It seems like a big Job !
Can you break down some sub-tasks? Then more people can help with this.

**Comment by Huang-Wei** [comment]
This belongs to a line item called "API Cleanup" in the next release cycle. We will first define the overall scope and then divide it into several pieces for contributors who are interested to pick up.

**Comment by ahg-g** [comment]
Thanks Daniel, during the sig meeting yesterday @Huang-Wei expressed interest in owning this umbrella item.

/assign @Huang-Wei

**Comment by ProgramerGu** [comment]
It will make Code structure more clearly，but why do k8s put them in two path at the first time?

**Comment by ahg-g** [comment]
> It will make Code structure more clearly，but why do k8s put them in two path at the first time?

Historical reasons.

**Comment by Huang-Wei** [comment]
@ProgramerGu for some historical reason, we don't have the concept of `apiGroup`; we just have `apiVersion`, that's what the path `/api` comes into, which now represents a "particular" group called "core group". While along with the Kubernetes development, `apiGroup` was brought up and each API resource has its GVK (group, version, kind). So since then `/apis` aggregates all the resources which have explicit "gropu" info.

BTW: the "apiVersion" in `pod.spec.apiVersion` actually means "apiGroupVersion". It's not changed also due to the same historical reason.

**Comment by ahg-g** [comment]
The other reason is that config APIs under apis/config is published [under a separate external repo](https://github.com/kubernetes/kube-scheduler) that provides external, versioned API types that can be vendored and used by third-party code instead of vendoring the scheduler code directly.
