### ISSUE TITLE
Add metrics to track filter and scoring behavior of the scheduler

### ISSUE THREAD

**Issue by ahg-g** [kubernetes/kubernetes#82427]
**What would you like to be added**:

The scheduler currently provides a number of useful metrics to track its health. We would like to add more metrics to track the impact of various filter/predicate and score/priority functions on scheduling decisions.

A couple of suggestions:
1) Add a vector counter to track the number of nodes filtered by different filters/predicates.
2) Add a vector histogram to track the scores provided by different scores/priorities

**Why is this needed**:
We currently have no easy way to track which features impact the scheduling decisions. We have logs, but metrics provides an easier way to debug the general behavior of the scheduler at the cluster level.

/sig scheduling
/assign @liu-cong

**Comment by liu-cong** [comment]
Proposed metrics to be added:


metric name | metric definition | Description
-- | -- | --
scheduler_filtered_nodes_total | Type: CounterLabels:plugin={filter plugin names} | Number of nodes filtered by filter plugins.
scheduler_score | Type: HistogramLabels:plugin={filter plugin names} | Score results by different score plugins.

**Comment by liu-cong** [comment]
Though more about this and I don't think these metrics make sense. The filtering and scoring heavily depend on the pod and node spec/status. As a result, it hard to reason about the metric values. Is the value high because of the filter/score logic? Or is it because of the specific combination of pod and node spec? I doubt if we can get any useful information from these metrics.

The way we run filter plugins also creates challenge to record the filter_nodes metric. First, we run filters for a given node, and return early if a filter returns false. The order of filters matters. As a result, the last filter has the least chance to even get executed.
```
for each node:
     for each filter:
         return false if filter result is false
     return true
```
