### ISSUE TITLE
Drop `VolumeLifecycleModes` field from `CSIDriver` API before GA

### ISSUE THREAD

**Issue by saad-ali** [kubernetes/kubernetes#82507]
**What happened**:

v1alpha1 Storage API has a field `VolumeLifecycleModes` in `CSIDriverSpec`:

https://github.com/kubernetes/kubernetes/blob/6348200c92dec8848e55552f3e8039b3da95bd91/staging/src/k8s.io/api/storage/v1beta1/types.go#L306-L319

This field made sense (see https://github.com/kubernetes/community/pull/2273#issuecomment-414495411) when we planned to allow 2 modes of operations for Pod Inline CSI volumes (https://github.com/kubernetes/enhancements/issues/596): 1) kubernetes generated volume handle and 2) user generated volume handle

Since then, we decided that inline volumes will only support we only support 1 not 2. The current API doesn't allow 2 at all.

**What you expected to happen**:

Unless we have a strong reason otherwise, let's remove the `VolumeLifecycleModes` field from `CSIDriverSpec` before promoting `CSIDriver` to GA.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

CC @msau42 @pohly @vladimirvivien 

/sig storage

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by pohly** [comment]
> This field made sense (see kubernetes/community#2273 (comment)) when we planned to allow 2 modes of operations for Pod Inline CSI volumes (kubernetes/enhancements#596): 1) kubernetes generated volume handle and 2) user generated volume handle

The `VolumeLifecycleModes` isn't about that. It's a sanity check that prevents kubelet from calling `NodePublishVolume` for an inline volume when the CSI driver doesn't support that mode. The outcome would be unspecified, because the call isn't valid (doesn't follow the CSI spec regarding prior calls, volume context not what the driver expects). Who knows what a badly written driver then does...

@kfox1111 confirmed that the check is needed when asked about it prior to implementing it (don't have a link at hand, though).

**Comment by kfox1111** [comment]
@saad-ali  This actually happened the other way around. We initially decided that there would only be support for one mode of operation. Either Persistent or Ephemeral. Since the alpha, drivers have started to show up that could realistically be used in either mode. Persistent for backing PV's and Ephemeral for backing ephemeral inline. So the spec was updated to cover this and the field was added. So, I believe this is working as designed and should not be removed before GA.

**Comment by kfox1111** [comment]
Maybe some more specifics...

We don't currently have no plans on supporting pod inline volumes for any mode other then 
ephemeral.
If the driver is marked as ephemeral, it can be used pod inline in an ephemeral way (no volumeHandle specified by the user, k8s managed volumeHandle). Currently it can not be used pod inline if it is not marked as supporting ephemeral.
If the driver is marked as persistent, it can be used in a pv.

This does not run afoul of the original design restriction where we didn't want to support the full csi lifecycle in kubelet to do dynamic provisioning of ephemeral backing volumes. Nor can a Persistent supporting driver be used in pod inline without it also being Ephemeral and following the Ephemeral api. This should be safe.

**Comment by pohly** [comment]
For reference: the API change was requested and discussed in https://github.com/kubernetes/kubernetes/issues/75222.

**Comment by gnufied** [comment]
cc @huffmanca

**Comment by saad-ali** [comment]
> The VolumeLifecycleModes isn't about that. It's a sanity check that prevents kubelet from calling NodePublishVolume for an inline volume when the CSI driver doesn't support that mode. The outcome would be unspecified, because the call isn't valid (doesn't follow the CSI spec regarding prior calls, volume context not what the driver expects). Who knows what a badly written driver then does...

Agreed, in retrospect, the `CSIDriver.VolumeLifecycleModes` field protects Kubernetes from doing "non-standard" CSI behavior against an unsuspecting CSI Driver which is very important. I withdraw this suggestion.

Tangentially related, before moving to GA we should consider if we want to make ephemeral volumes more first class in the CSI spec or not.
