### ISSUE TITLE
apimachinery change breaks clients generated against v1.14

### ISSUE THREAD

**Issue by ibuildthecloud** [kubernetes/kubernetes#82859]
**What happened**:

apimachinery from v1.16.0 drops serializer.DirectCodecFactory https://github.com/kubernetes/kubernetes/pull/79263

This field was renamed in 1.15 and then dropped in 1.16.  Generated clientsets directly reference this field so any clients generated against k8s 1.14 are incompatible with apimachinery from 1.16.  This seems like a pretty aggressive window to drop an API that has about 17k reference on Github.  I'm not sure what policy is around deprecating and dropping k8s.io APIs but this seems a bit fast.

It would be nice to revert https://github.com/kubernetes/kubernetes/pull/79263

**Comment by ibuildthecloud** [comment]
@kubernetes/sig-api-machinery

**Comment by yue9944882** [comment]
- if the client-generation works in your project (instead of vendored project), you can re-generate using 1.16 generator and it will be backward-compatible..
- if a vendored project w/ generated clients from 1.14 (which directly references `DirectCodecFactory`), that will indeed prevent us from upgrading `k8s.io/apimachinery` to 1.16.. probably consider to hold until the other project switches to 1.16 generated clients..

**Comment by ibuildthecloud** [comment]
I'm having issues with vendored projects.  My project depends on k8s 1.16 and a library generated against 1.14.  I can't downgrade to 1.15 because I specifically need 1.16 and I need the library I'm depending on. This is not an easily fixable problem, it would be far better to not break this API. The only solution I have at the moment is to revert the offending commit and run from a fork of apimachinery.

**Comment by dims** [comment]
cc @draveness @liggitt

**Comment by deads2k** [comment]
This is a common transitive dependency problem in the golang language itself.  k8s.io/client-go release-X branches correctly reference their dependencies on k8s.io/apimachinery and k8s.io/api.  Drifting from the dependency set is not a thing that we support or intend to support.

I would be supportive of an effort decouple dependencies from k8s.io/api and attempt to build a more conveniently semver'd client-go on top, but that would take a concerted effort with multiple people.

**Comment by ibuildthecloud** [comment]
Holy crap this is closed? That sucks. This is a tiny, literally one line change I'm asking for that would really help the community of existing code out there.  I'm not asking that you adopt some strenuous compatibility guideline (which you should consider given the enterprise audience of k8s) I'm point out a one line change that break a crap ton of code. This just adds to my ever increasing frustration that managing kubernetes dependencies is an absolute nightmare.

I'm doing my best to try do do everything according to the rules you set and it's a pain. I work full time in k8s, I can work around this so no big deal, but I think you should reconsider this specific issue for the community. If there's something obvious I'm missing please let me know. I already stated there isn't a simple fix beyond forking I can find.

**Comment by deads2k** [comment]
We don't maintain or promise compatibility across releases.  Due to the size of this change, I could see considering the alias for one more release, but once 1.14 is out of support (once 1.17 comes out I think) we would remove it.

This would not be a guarantee that the skew will work for you (I have no idea if it works) and we will still be willing to merge changes to k8s.io/apimachinery that instantly break any version skew.  We just haven't done that this release.  This particular one happens to be very low cost to keep one more release.

I think the consideration will be dependent upon how many people find this to be a real stumbling block.  This a unique opportunity to gain significant insight into how our community operates.  I'm inclined to wait to see many projects are bit are skew issues and cannot update.

**Comment by smarterclayton** [comment]
We are likely to refactor the core internals of client go pretty dramatically over the next few releases as we remove cruft that has accumulated over the years.  This is just the first change, the second will change rest.Config more dramatically to prevent common failure modes, the third will remove some of the conversion baggage, etc.  Locking to versions is the best bet, which is why we have api stability.

**Comment by smarterclayton** [comment]
Actually, an even more impactful change coming - CodecFactories themselves are likely to be removed because they add expensive abstraction to high level components (and cause problems like this).  

I do understand how irritating this is to deal with.  But most of these abstractions cause more problems for new users than removing the issue-causing-abstraction causes advanced users like us and you.

**Comment by deads2k** [comment]
You can also see efforts like the idea of finally making a proper client-go-base (rediscussed at last week's [sig-apimachinery call](https://docs.google.com/document/d/1x9RNaaysyO0gXHIr1y50QFbiL1x8OWnk2v3XnrdkT5Y)) causing significant changes in a single release.

The API itself remains compatible and previous client-go levels still support skew, but the golang code is not going to remain source compatible across release boundaries.  We ensure the dependency metadata is correct for each release, but mixing and matching is coloring outside the lines.

**Comment by stealthybox** [comment]
> CodecFactories themselves are likely to be removed because they add expensive abstraction to high level components

Interesting. I'm +1 for removing CodecFactory, but I do think we'd need an acceptable replacement abstraction.

Dealing with the mass of generated code and dependencies in the community creates inertia for change. If we choose to break clients like this, we have to expect that it will take months or longer for the ecosystem to catch up.

People like @ibuildthecloud will need to fork and assemble unsupported solutions which is difficult.

This is why when we did #76805 and #74111, we focused on not breaking signature and providing equivalent functionality.

**Comment by smarterclayton** [comment]
> People like @ibuildthecloud will need to fork and assemble unsupported solutions which is difficult.

Pairing clients generated with 1.14-level libraries with 1.16-level libraries is already unsupported.

**Comment by vllry** [comment]
Would it be realistic to include these kind of changes in deprecation policies? I understand the pressure to make changes quickly, but this kind of speed is very disruptive in the broader ecosystem.

**Comment by smarterclayton** [comment]
Mismatched libraries?

**Comment by ibuildthecloud** [comment]
@smarterclayton This issue isn't a generic issue and shouldn't be treated as such.  I know managing inter-dependencies is hard and you can't make guarantees.  I really just want this one tiny change to add back the type alias.  I really don't think you appreciate how hard it is to managed this.

I'll give you a specific example.  I must support k8s 1.16.  Because of the statically typed clients, if you are talking to k8s to 1.16 you must use a 1.16 client or you risk getting dropped fields on updates.  So I have to update the k8s 1.16 client-go/api.  But my application also needs to interact with tekton so I use the published clientset/informers etc from tekton.  They compile against k8s 1.12 so it doesn't work.  So my options are either get tekton to update or maintain a generated client for them for my project.  Neither of these options are desirable when you consider that I have multiple dependencies in this situation.

So this issue was just, "hey it would really help if you reverted this one line change." not, "you need to guarantee API compatibility forever."  Projects using client-go in the most mundane way are broken, it's not like this was anything out of the norm.  It's the generated code that is referring to the dropped field.
