### ISSUE TITLE
make cluster/get-kube.sh more resilient to unclean GCE project starting state

### ISSUE THREAD

**Issue by davidopp** [kubernetes/kubernetes#8285]
@roberthbailey

**Comment by gmarek** [comment]
We need to decide on semantics of this resilience. IIUC this issue is about making kube-up-ish things work given that something bad happened with previous attempt: previous kube-up failed at unspecified point or kube-down was not called. The question is what to do in such case. 

Easiest and probably the best thing to do is to recreate a cluster from currently present binaries, i.e. tear down what's present and create a new one. This is more or less clear for not-fully-set-up-cluster, but less so for already running one. I think that by default we should do exactly the same, i.e. tear down current cluster and start a brand new one.

Alternative approach is to work like 'push' for running cluster, but this would require specifying what 'running cluster' exactly mean (which parts of it need to be healthy, and how to check it). As it's v1.0 I don't think we should go this way.

**Comment by davidopp** [comment]
@roberthbailey any opinion on this? Seems to me that deleting all the existing GCE objects that might have been created by a previous run of this script (if you get any kind of error that indicates pre-existing object), and then running the script from the beginning, is the right thing to do. (i.e. @gmarek's second paragraph)

**Comment by roberthbailey** [comment]
> if you get any kind of error that indicates pre-existing object

I think it would make more sense to do a pre-creation validation step that checks for any existing resources. If it finds any, it would prompt the user (by default, but could be skipped for automated testing) about whether they want to tear them down and create a new cluster or abort. 

The problem with trying to tear things down in the middle of cluster creation is that it is going to make the logic for trying to figure out what the shell script is doing incredibly opaque (for each command, if you get an http 409 error, jump to the tear-down flow and then start the script over from the beginning -- also try not to introduce any infinite loops while doing so).

**Comment by goltermann** [comment]
Couldn't we do this by just calling validate-cluster.sh and parsing the result somehow?  Then if it doesn't validate (for whatever reason) call kube-down before kube-up?

**Comment by roberthbailey** [comment]
I think that might be reasonable if kube-down.sh was a bit quieter about failing to delete non-existent resources. Right now, if you create a cluster but none exists, validate-cluster.sh will fail (as expected), then kube-down.sh will give you a whole bunch of red error text about not being able to delete existing resources, then kube-up.sh will create a cluster. The errors during the kube-down.sh run are expected, but will be confusing to a new user.

**Comment by goltermann** [comment]
Working on that in #8348

**Comment by alex-mohr** [comment]
I'm marking #9066 as a dup of this one (GCE Cluster turnup should fail if stale routes exist), but add some more wrinkles:
- it's not just the kube-up.sh created stuff that we should GC, but also all the various load balancers and disks and such that the master creates that can be a problem.
- since tracking each create point and adding a specific GC step for it is going to miss stuff, this may be best as a wildcard match for any existing k8s-$clustername-.* resources before doing a kube-up.  And/or augmenting kube-down to delete all of those.   And be strict about ensuring all resources fit in that poor man's namespacing approach?

**Comment by davidopp** [comment]
This was also mentioned yesterday at the meeting we had to discuss friction issues.

**Comment by davidopp** [comment]
BTW this is currently assigned to @goltermann and it is marked as 1.0 but there haven't been any PRs merged related to this issue. Should we reassign it?

**Comment by alex-mohr** [comment]
@davidopp Thanks -- I don't think TJ was working on this, so unassigned.

Marking P2: I think this is less important than other things we're trying to land for 1.0-RC, but makes sense to address before we get to v1 proper.

**Comment by davidopp** [comment]
My only nit on the PR is that it would be nice to tell the user about *all* of the leftover artifacts, rather than just the first one that is found in check-resources.

@alex-mohr can you take a quick check of #9859 and see if there's anything else you think we should be doing here? If not, please close the issue.

**Comment by alex-mohr** [comment]
Yeah, nits would be:
(1) could tell the user about all resources
(2) would be nice if kube-down used the same logic.  As is, no guarantee kube-down will actually fix things, or that its code stays in sync with this?

Moving to v1.0-post for now, though.

**Comment by gmarek** [comment]
cc @fgrzadkowski

**Comment by smarterclayton** [comment]
Closing due to age and general lack of interest, reopen if this is important (and probably should be cluster lifecycle doing the leading here).
