### ISSUE TITLE
installed kubernetes with kubeadm have an error!

### ISSUE THREAD

**Issue by eastonliu** [kubernetes/kubernetes#83225]
**What happened**:
I installed kubernetes with kubeadm ,executing kubeadm init have an error:
[etcd] Creating static Pod manifest for local etcd in "/etc/kubernetes/manifests"
[wait-control-plane] Waiting for the kubelet to boot up the control plane as static Pods from directory "/etc/kubernetes/manifests". This can take up to 4m0s
[kubelet-check] Initial timeout of 40s passed.

Unfortunately, an error has occurred:
	timed out waiting for the condition

This error is likely caused by:
	- The kubelet is not running
	- The kubelet is unhealthy due to a misconfiguration of the node in some way (required cgroups disabled)

If you are on a systemd-powered system, you can try to troubleshoot the error with the following commands:
	- 'systemctl status kubelet'
	- 'journalctl -xeu kubelet'

Additionally, a control plane component may have crashed or exited when started by the container runtime.
To troubleshoot, list all containers using your preferred container runtimes CLI, e.g. docker.
Here is one example how you may list all Kubernetes containers running in docker:
	- 'docker ps -a | grep kube | grep -v pause'
	Once you have found the failing container, you can inspect its logs with:
	- 'docker logs CONTAINERID'
error execution phase wait-control-plane: couldn't initialize a Kubernetes cluster
To see the stack trace of this error execute with --v=5 or higher

journalctl -xeu kubelet:
Sep 27 14:45:06 master1 kubelet[6681]: E0927 14:45:06.986855    6681 controller.go:135] failed to ensure node lease exists, will retry in 7s, error: Get https://172.21.23.141:6443/apis/coordination.k8s.io/v1/namespaces/kube-n
Sep 27 14:45:07 master1 kubelet[6681]: E0927 14:45:07.042356    6681 reflector.go:123] k8s.io/kubernetes/pkg/kubelet/kubelet.go:459: Failed to list *v1.Node: Get https://172.21.23.141:6443/api/v1/nodes?fieldSelector=metadata.
Sep 27 14:45:07 master1 kubelet[6681]: E0927 14:45:07.060401    6681 kubelet.go:2267] node "master1" not found
Sep 27 14:45:07 master1 kubelet[6681]: E0927 14:45:07.153298    6681 remote_runtime.go:105] RunPodSandbox from runtime service failed: rpc error: code = Unknown desc = failed to start sandbox container for pod "kube-scheduler
Sep 27 14:45:07 master1 kubelet[6681]: E0927 14:45:07.153354    6681 kuberuntime_sandbox.go:68] CreatePodSandbox for pod "kube-scheduler-master1_kube-system(c18ee741ac4ad7b2bfda7d88116f3047)" failed: rpc error: code = Unknown
Sep 27 14:45:07 master1 kubelet[6681]: E0927 14:45:07.153376    6681 kuberuntime_manager.go:710] createPodSandbox for pod "kube-scheduler-master1_kube-system(c18ee741ac4ad7b2bfda7d88116f3047)" failed: rpc error: code = Unknow
Sep 27 14:45:07 master1 kubelet[6681]: E0927 14:45:07.153440    6681 pod_workers.go:191] Error syncing pod c18ee741ac4ad7b2bfda7d88116f3047 ("kube-scheduler-master1_kube-system(c18ee741ac4ad7b2bfda7d88116f3047)"), skipping: f
Sep 27 14:45:07 master1 kubelet[6681]: I0927 14:45:07.156079    6681 kubelet_node_status.go:286] Setting node annotation to enable volume controller attach/detach
Sep 27 14:45:07 master1 kubelet[6681]: E0927 14:45:07.160519    6681 kubelet.go:2267] node "master1" not found
why?
**What you expected to happen**:
Everything is all right
**How to reproduce it (as minimally and precisely as possible)**:
installed kubernetes with kubeadm
**Anything else we need to know?**:
no
**Environment**:
- Kubernetes version (use `kubectl version`):v1.16.0
- Cloud provider or hardware configuration:8CPU,16Gmen
- OS (e.g: `cat /etc/os-release`):CentOS Linux 7.6
- Kernel (e.g. `uname -a`):3.10.0-957.el7.x86_64
- Install tools:kubeadm v1.16.0
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by tedyu** [comment]
```
Sep 27 14:45:07 master1 kubelet[6681]: E0927 14:45:07.060401 6681 kubelet.go:2267] node "master1" not found
```

**Comment by neolit123** [comment]
- are you passing a configuration file to `kubeadm init`?
- what is your `kubeadm init` command line?
- is `master1` the host of the node (check `hostname` command), are you overriding it?

**Comment by enstor-ng** [comment]
hit the same problem, while trying to install it on AWS  EC2 instance.   Followed [install steps](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/) . Decided to try with Kube-router, so  --pod-network-cidr  was passed.  

Tried with short name and then with FQDN using the  --node-name option. Kubelet service fails to start. Anyway around this?

[root@m1 ~]# kubeadm init --node-name m1.us-west-1.compute.internal
[init] Using Kubernetes version: v1.16.1
[preflight] Running pre-flight checks
[preflight] Pulling images required for setting up a Kubernetes cluster
[preflight] This might take a minute or two, depending on the speed of your internet connection
[preflight] You can also perform this action in beforehand using 'kubeadm config images pull'
[kubelet-start] Writing kubelet environment file with flags to file "/var/lib/kubelet/kubeadm-flags.env"
[kubelet-start] Writing kubelet configuration to file "/var/lib/kubelet/config.yaml"
[kubelet-start] Activating the kubelet service
[certs] Using certificateDir folder "/etc/kubernetes/pki"
[certs] Generating "ca" certificate and key
[certs] Generating "apiserver" certificate and key
[certs] apiserver serving cert is signed for DNS names [m1.us-west-1.compute.internal kubernetes kubernetes.default kubernetes.default.svc kubernetes.default.svc.cluster.local] and IPs [10.96.0.1 172.31.6.166]
[certs] Generating "apiserver-kubelet-client" certificate and key
[certs] Generating "front-proxy-ca" certificate and key
[certs] Generating "front-proxy-client" certificate and key
[certs] Generating "etcd/ca" certificate and key
[certs] Generating "etcd/server" certificate and key
[certs] etcd/server serving cert is signed for DNS names [m1.us-west-1.compute.internal localhost] and IPs [172.31.6.166 127.0.0.1 ::1]
[certs] Generating "etcd/peer" certificate and key
[certs] etcd/peer serving cert is signed for DNS names [m1.us-west-1.compute.internal localhost] and IPs [172.31.6.166 127.0.0.1 ::1]
[certs] Generating "etcd/healthcheck-client" certificate and key
[certs] Generating "apiserver-etcd-client" certificate and key
[certs] Generating "sa" key and public key
[kubeconfig] Using kubeconfig folder "/etc/kubernetes"
[kubeconfig] Writing "admin.conf" kubeconfig file
[kubeconfig] Writing "kubelet.conf" kubeconfig file
[kubeconfig] Writing "controller-manager.conf" kubeconfig file
[kubeconfig] Writing "scheduler.conf" kubeconfig file
[control-plane] Using manifest folder "/etc/kubernetes/manifests"
[control-plane] Creating static Pod manifest for "kube-apiserver"
[control-plane] Creating static Pod manifest for "kube-controller-manager"
[control-plane] Creating static Pod manifest for "kube-scheduler"
[etcd] Creating static Pod manifest for local etcd in "/etc/kubernetes/manifests"
[wait-control-plane] Waiting for the kubelet to boot up the control plane as static Pods from directory "/etc/kubernetes/manifests". This can take up to 4m0s
[kubelet-check] Initial timeout of 40s passed.

Unfortunately, an error has occurred:
	timed out waiting for the condition

This error is likely caused by:
	- The kubelet is not running
	- The kubelet is unhealthy due to a misconfiguration of the node in some way (required cgroups disabled)

If you are on a systemd-powered system, you can try to troubleshoot the error with the following commands:
	- 'systemctl status kubelet'
	- 'journalctl -xeu kubelet'

Additionally, a control plane component may have crashed or exited when started by the container runtime.
To troubleshoot, list all containers using your preferred container runtimes CLI, e.g. docker.
Here is one example how you may list all Kubernetes containers running in docker:
	- 'docker ps -a | grep kube | grep -v pause'
	Once you have found the failing container, you can inspect its logs with:
	- 'docker logs CONTAINERID'
error execution phase wait-control-plane: couldn't initialize a Kubernetes cluster
To see the stack trace of this error execute with --v=5 or higher
**[root@m1 ~]# systemctl status kubelet**
● kubelet.service - kubelet: The Kubernetes Node Agent
   Loaded: loaded (/usr/lib/systemd/system/kubelet.service; enabled; vendor preset: disabled)
  Drop-In: /usr/lib/systemd/system/kubelet.service.d
           └─10-kubeadm.conf
   Active: active (running) since Thu 2019-10-03 11:22:40 PDT; 6min ago
     Docs: https://kubernetes.io/docs/
 Main PID: 5939 (kubelet)
   CGroup: /system.slice/kubelet.service
           └─5939 /usr/bin/kubelet --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf --config=/var/lib/...

Oct 03 11:28:44 m1 kubelet[5939]: E1003 11:28:44.780184    5939 kubelet.go:2267] node "m1.us-west-1.compute.internal" not found
Oct 03 11:28:44 m1 kubelet[5939]: E1003 11:28:44.833243    5939 reflector.go:123] k8s.io/client-go/informers/factory.go:134: Failed to list *v1beta...on refused
Oct 03 11:28:44 m1 kubelet[5939]: E1003 11:28:44.880414    5939 kubelet.go:2267] node "m1.us-west-1.compute.internal" not found
Oct 03 11:28:44 m1 kubelet[5939]: E1003 11:28:44.980617    5939 kubelet.go:2267] node "m1.us-west-1.compute.internal" not found
Oct 03 11:28:45 m1 kubelet[5939]: E1003 11:28:45.033949    5939 reflector.go:123] k8s.io/client-go/informers/factory.go:134: Failed to list *v1beta...on refused
Oct 03 11:28:45 m1 kubelet[5939]: E1003 11:28:45.080859    5939 kubelet.go:2267] node "m1.us-west-1.compute.internal" not found
Oct 03 11:28:45 m1 kubelet[5939]: E1003 11:28:45.181057    5939 kubelet.go:2267] node "m1.us-west-1.compute.internal" not found
Oct 03 11:28:45 m1 kubelet[5939]: E1003 11:28:45.233596    5939 reflector.go:123] k8s.io/kubernetes/pkg/kubelet/kubelet.go:450: Failed to list *v1....on refused
Oct 03 11:28:45 m1 kubelet[5939]: E1003 11:28:45.281274    5939 kubelet.go:2267] node "m1.us-west-1.compute.internal" not found
Oct 03 11:28:45 m1 kubelet[5939]: E1003 11:28:45.381500    5939 kubelet.go:2267] node "m1.us-west-1.compute.internal" not found
Hint: Some lines were ellipsized, use -l to show in full.

**Comment by SantosRay** [comment]
I have the same problem building a simple cluster with Ubuntu 18.4:

===========================================================
root@master-node:~# kubeadm init --pod-network-cidr=10.244.0.0/16
[init] Using Kubernetes version: v1.16.1
[preflight] Running pre-flight checks
        [WARNING IsDockerSystemdCheck]: detected "cgroupfs" as the Docker cgroup                                                                                                                     driver. The recommended driver is "systemd". Please follow the guide at https:/                                                                                                                    /kubernetes.io/docs/setup/cri/
[preflight] Pulling images required for setting up a Kubernetes cluster
[preflight] This might take a minute or two, depending on the speed of your inte                                                                                                                    rnet connection
[preflight] You can also perform this action in beforehand using 'kubeadm config                                                                                                                     images pull'
[kubelet-start] Writing kubelet environment file with flags to file "/var/lib/ku                                                                                                                    belet/kubeadm-flags.env"
[kubelet-start] Writing kubelet configuration to file "/var/lib/kubelet/config.y                                                                                                                    aml"
[kubelet-start] Activating the kubelet service
[certs] Using certificateDir folder "/etc/kubernetes/pki"
[certs] Generating "ca" certificate and key
[certs] Generating "apiserver" certificate and key
[certs] apiserver serving cert is signed for DNS names [master-node kubernetes k                                                                                                                    ubernetes.default kubernetes.default.svc kubernetes.default.svc.cluster.local] a                                                                                                                    nd IPs [10.96.0.1 192.168.5.114]
[certs] Generating "apiserver-kubelet-client" certificate and key
[certs] Generating "front-proxy-ca" certificate and key
[certs] Generating "front-proxy-client" certificate and key
[certs] Generating "etcd/ca" certificate and key
[certs] Generating "etcd/server" certificate and key
[certs] etcd/server serving cert is signed for DNS names [master-node localhost]                                                                                                                     and IPs [192.168.5.114 127.0.0.1 ::1]
[certs] Generating "etcd/peer" certificate and key
[certs] etcd/peer serving cert is signed for DNS names [master-node localhost] a                                                                                                                    nd IPs [192.168.5.114 127.0.0.1 ::1]
[certs] Generating "etcd/healthcheck-client" certificate and key
[certs] Generating "apiserver-etcd-client" certificate and key
[certs] Generating "sa" key and public key
[kubeconfig] Using kubeconfig folder "/etc/kubernetes"
[kubeconfig] Writing "admin.conf" kubeconfig file
[kubeconfig] Writing "kubelet.conf" kubeconfig file
[kubeconfig] Writing "controller-manager.conf" kubeconfig file
[kubeconfig] Writing "scheduler.conf" kubeconfig file
[control-plane] Using manifest folder "/etc/kubernetes/manifests"
[control-plane] Creating static Pod manifest for "kube-apiserver"
[control-plane] Creating static Pod manifest for "kube-controller-manager"
[control-plane] Creating static Pod manifest for "kube-scheduler"
[etcd] Creating static Pod manifest for local etcd in "/etc/kubernetes/manifests                                                                                                                    "
[wait-control-plane] Waiting for the kubelet to boot up the control plane as sta                                                                                                                    tic Pods from directory "/etc/kubernetes/manifests". This can take up to 4m0s
[kubelet-check] Initial timeout of 40s passed.

Unfortunately, an error has occurred:
        timed out waiting for the condition

This error is likely caused by:
        - The kubelet is not running
        - The kubelet is unhealthy due to a misconfiguration of the node in some                                                                                                                     way (required cgroups disabled)

If you are on a systemd-powered system, you can try to troubleshoot the error wi                                                                                                                    th the following commands:
        - 'systemctl status kubelet'
        - 'journalctl -xeu kubelet'

Additionally, a control plane component may have crashed or exited when started                                                                                                                     by the container runtime.
To troubleshoot, list all containers using your preferred container runtimes CLI                                                                                                                    , e.g. docker.
Here is one example how you may list all Kubernetes containers running in docker                                                                                                                    :
        - 'docker ps -a | grep kube | grep -v pause'
        Once you have found the failing container, you can inspect its logs with                                                                                                                    :
        - 'docker logs CONTAINERID'
error execution phase wait-control-plane: couldn't initialize a Kubernetes clust                                                                                                                    er
To see the stack trace of this error execute with --v=5 or higher
==============================================================

I got the warning: 

[WARNING IsDockerSystemdCheck]: detected "cgroupfs" as the Docker cgroup                                                                                                                     driver. The recommended driver is "systemd". Please follow the guide at https:/                                                                                                                    /kubernetes.io/docs/setup/cri/

but my root@master-node:~# cat /etc/docker/daemon.json
{
  "exec-opts": ["native.cgroupdriver=systemd"],
  "log-driver": "json-file",
  "log-opts": {
    "max-size": "100m"
  },
  "storage-driver": "overlay2"
}

Any ideas?

**Comment by tedyu** [comment]
Can you see if cgroupfs appears in the output of:
```
	out, err := execer.Command("docker", "info", "-f", "{{.CgroupDriver}}").Output()
```

**Comment by SantosRay** [comment]
Yes it does.
root@master-node:~# docker info -f "{{.CgroupDriver}}"
cgroupfs

**Comment by SantosRay** [comment]
@tedyu, thanks for the tip!

root@master-node:~# docker info -f "{{.CgroupDriver}}"
cgroupfs

/etc/systemd/system/docker.service.d was missing

root@master-node:~# ls /etc/systemd/system
cloud-final.service.wants              default.target.wants    iscsi.service                open-vm-tools.service.requires  snap-docker-384.mount        sshd.service          ubuntu-fan.service
cloud-init.target.wants                final.target.wants      kubelet.service.d            paths.target.wants              snap.docker.dockerd.service  sysinit.target.wants
dbus-org.freedesktop.resolve1.service  getty.target.wants      multi-user.target.wants      snap-core-7270.mount            snap-powershell-39.mount     syslog.service
dbus-org.freedesktop.thermald.service  graphical.target.wants  network-online.target.wants  snap-core-7713.mount            sockets.target.wants         timers.target.wants

I created it, reloaded the daemon and restarted docker
root@master-node:~# mkdir -p /etc/systemd/system/docker.service.d

root@master-node:~# ls /etc/systemd/system
cloud-final.service.wants              default.target.wants  graphical.target.wants   network-online.target.wants     snap-core-7713.mount         sockets.target.wants  timers.target.wants
cloud-init.target.wants                docker.service.d      iscsi.service            open-vm-tools.service.requires  snap-docker-384.mount        sshd.service          ubuntu-fan.service
dbus-org.freedesktop.resolve1.service  final.target.wants    kubelet.service.d        paths.target.wants              snap.docker.dockerd.service  sysinit.target.wants
dbus-org.freedesktop.thermald.service  getty.target.wants    multi-user.target.wants  snap-core-7270.mount            snap-powershell-39.mount     syslog.service

root@master-node:~# systemctl daemon-reload
root@master-node:~# systemctl restart docker

root@master-node:~# docker info -f "{{.CgroupDriver}}"
systemd

**Comment by SantosRay** [comment]
BTW,

Problem solved!
...

Your Kubernetes control-plane has initialized successfully!

To start using your cluster, you need to run the following as a regular user:

  mkdir -p $HOME/.kube
  sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
  sudo chown $(id -u):$(id -g) $HOME/.kube/config

You should now deploy a pod network to the cluster.
Run "kubectl apply -f [podnetwork].yaml" with one of the options listed at:
  https://kubernetes.io/docs/concepts/cluster-administration/addons/
...

**Comment by goldwinner** [comment]
> BTW,
> 
> Problem solved!
> ...
> 
> Your Kubernetes control-plane has initialized successfully!
> 
> To start using your cluster, you need to run the following as a regular user:
> 
> mkdir -p $HOME/.kube
> sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
> sudo chown $(id -u):$(id -g) $HOME/.kube/config
> 
> You should now deploy a pod network to the cluster.
> Run "kubectl apply -f [podnetwork].yaml" with one of the options listed at:
> https://kubernetes.io/docs/concepts/cluster-administration/addons/
> ...

same problem for me。could you please share the solution or workaround？thanks a lot

**Comment by Charles-one** [comment]
Nov 23 19:48:00 mm.com kubelet[19303]: E1123 19:48:00.306432   19303 reflector.go:125] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: Failed to list *v1.Pod: Get https://<ip>:6443/api/v1/pods?fiel
Nov 23 19:48:00 mm.com kubelet[19303]: E1123 19:48:00.355661   19303 kubelet.go:2252] node "mm.com" not found

I hava same problem

**Comment by neolit123** [comment]
>  node "mm.com" not found

this is not a fatal error. the kubelet might show it for a while but then succeed.
the full logs might help diagnose the problem better.

**Comment by Charles-one** [comment]
$:  journalctl -xeu kubelet

Nov 23 20:09:16 mm.com kubelet[22940]: E1123 20:09:16.099034   22940 reflector.go:125] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: Failed to list *v1.Pod: Get https://118.89.82.205:6443/api/v1/pods?fiel
Nov 23 20:09:16 mm.com kubelet[22940]: E1123 20:09:16.099975   22940 reflector.go:125] k8s.io/client-go/informers/factory.go:133: Failed to list *v1beta1.CSIDriver: Get https://118.89.82.205:6443/apis/storage.k8s
Nov 23 20:09:16 mm.com kubelet[22940]: E1123 20:09:16.105501   22940 reflector.go:125] k8s.io/client-go/informers/factory.go:133: Failed to list *v1beta1.RuntimeClass: Get https://118.89.82.205:6443/apis/node.k8s
Nov 23 20:09:16 mm.com kubelet[22940]: E1123 20:09:16.106774   22940 reflector.go:125] k8s.io/kubernetes/pkg/kubelet/kubelet.go:445: Failed to list *v1.Service: Get https://118.89.82.205:6443/api/v1/services?limi
Nov 23 20:09:16 mm.com kubelet[22940]: E1123 20:09:16.108392   22940 reflector.go:125] k8s.io/kubernetes/pkg/kubelet/kubelet.go:454: Failed to list *v1.Node: Get https://118.89.82.205:6443/api/v1/nodes?fieldSelec
Nov 23 20:09:16 mm.com kubelet[22940]: E1123 20:09:16.196190   22940 kubelet.go:2252] node "mm.com" not found
Nov 23 20:09:16 mm.com kubelet[22940]: E1123 20:09:16.296374   22940 kubelet.go:2252] node "mm.com" not found
Nov 23 20:09:16 mm.com kubelet[22940]: E1123 20:09:16.396539   22940 kubelet.go:2252] node "mm.com" not found
Nov 23 20:09:16 mm.com kubelet[22940]: E1123 20:09:16.496707   22940 kubelet.go:2252] node "mm.com" not found
Nov 23 20:09:16 mm.com kubelet[22940]: E1123 20:09:16.596884   22940 kubelet.go:2252] node "mm.com" not found
Nov 23 20:09:16 mm.com kubelet[22940]: E1123 20:09:16.697044   22940 kubelet.go:2252] node "mm.com" not found
Nov 23 20:09:16 mm.com kubelet[22940]: E1123 20:09:16.797225   22940 kubelet.go:2252] node "mm.com" not found
Nov 23 20:09:16 mm.com kubelet[22940]: E1123 20:09:16.897396   22940 kubelet.go:2252] node "mm.com" not found
Nov 23 20:09:16 mm.com kubelet[22940]: E1123 20:09:16.997560   22940 kubelet.go:2252] node "mm.com" not found
Nov 23 20:09:17 mm.com kubelet[22940]: E1123 20:09:17.053858   22940 controller.go:125] failed to ensure node lease exists, will retry in 7s, error: Get https://118.89.82.205:6443/apis/coordination.k8s.io/v1beta1
Nov 23 20:09:17 mm.com kubelet[22940]: E1123 20:09:17.097695   22940 kubelet.go:2252] node "mm.com" not found
Nov 23 20:09:17 mm.com kubelet[22940]: E1123 20:09:17.101372   22940 reflector.go:125] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: Failed to list *v1.Pod: Get https://118.89.82.205:6443/api/v1/pods?fiel
Nov 23 20:09:17 mm.com kubelet[22940]: E1123 20:09:17.102606   22940 reflector.go:125] k8s.io/client-go/informers/factory.go:133: Failed to list *v1beta1.CSIDriver: Get https://118.89.82.205:6443/apis/storage.k8s
Nov 23 20:09:17 mm.com kubelet[22940]: E1123 20:09:17.107802   22940 reflector.go:125] k8s.io/client-go/informers/factory.go:133: Failed to list *v1beta1.RuntimeClass: Get https://118.89.82.205:6443/apis/node.k8s
Nov 23 20:09:17 mm.com kubelet[22940]: E1123 20:09:17.109152   22940 reflector.go:125] k8s.io/kubernetes/pkg/kubelet/kubelet.go:445: Failed to list *v1.Service: Get https://118.89.82.205:6443/api/v1/services?limi
Nov 23 20:09:17 mm.com kubelet[22940]: E1123 20:09:17.110691   22940 reflector.go:125] k8s.io/kubernetes/pkg/kubelet/kubelet.go:454: Failed to list *v1.Node: Get https://118.89.82.205:6443/api/v1/nodes?fieldSelec

**Comment by neolit123** [comment]
You should take the kubelet logs right after the failure. The above logs
don't reveal any apparent problems.

**Comment by dammyboss** [comment]
i have the same issue and i seem not to understand what Santos did to resolve his. somebody should assist a brother here please

**Comment by Charles-one** [comment]
if you init k8s with "kubeadm init --pod-network-cidr=10.244.0.0/16 --apiserver-advertise-address=111.222.22.3 " .
use command "ip a "  or "ifconifg", 
apiserver-advertise-address must can be seen.
VPC network not support, you need connect your Service provider.

**Comment by tariqkipkemei** [comment]
Getting the same problem on RedHat 8.1

kubelet.service - kubelet: The Kubernetes Node Agent
   Loaded: loaded (/usr/lib/systemd/system/kubelet.service; enabled; vendor preset: disabled)
  Drop-In: /usr/lib/systemd/system/kubelet.service.d
           └─10-kubeadm.conf
   Active: active (running) since Thu 2020-03-05 12:17:29 EAT; 2h 2min ago
     Docs: https://kubernetes.io/docs/
 Main PID: 18260 (kubelet)
    Tasks: 19 (limit: 26213)
   Memory: 52.1M
   CGroup: /system.slice/kubelet.service
           └─18260 /usr/bin/kubelet --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf --config=/var/lib/kubelet/config.yaml --cgroup-driver=systemd --network-plugin=cni --pod-infra-container-image=k8s.gcr.io/pause:3.1


Mar 05 14:20:04 SVOMNIADM01DEV.CO-OPBANK.CO.KE kubelet[18260]:             }
Mar 05 14:20:04 SVOMNIADM01DEV.CO-OPBANK.CO.KE kubelet[18260]:         },
Mar 05 14:20:04 SVOMNIADM01DEV.CO-OPBANK.CO.KE kubelet[18260]:         {
Mar 05 14:20:04 SVOMNIADM01DEV.CO-OPBANK.CO.KE kubelet[18260]:             "type": "firewall",
Mar 05 14:20:04 SVOMNIADM01DEV.CO-OPBANK.CO.KE kubelet[18260]:             "backend": "iptables"
Mar 05 14:20:04 SVOMNIADM01DEV.CO-OPBANK.CO.KE kubelet[18260]:         }
Mar 05 14:20:04 SVOMNIADM01DEV.CO-OPBANK.CO.KE kubelet[18260]:     ]
Mar 05 14:20:04 SVOMNIADM01DEV.CO-OPBANK.CO.KE kubelet[18260]: }
Mar 05 14:20:04 SVOMNIADM01DEV.CO-OPBANK.CO.KE kubelet[18260]: : [plugin bridge does not support config version "0.4.0" plugin portmap does not support config version "0.4.0" failed to find plgin "firewall" in path [/opt/cni/bin]]
Mar 05 14:20:04 SVOMNIADM01DEV.CO-OPBANK.CO.KE kubelet[18260]: W0305 14:20:04.529031   18260 cni.go:237] Unable to update cni config: no valid networks found in /etc/cni/net.d


Please advise.

**Comment by neolit123** [comment]
> [plugin bridge does not support config version "0.4.0" plugin portmap does not support config version "0.4.0" failed to find plgin "firewall" in path [/opt/cni/bin]]

this message is saying that you need to install the `firewall` CNI plugin.
to be able to use CNI you need to install the `kubernetes-cni` package using e.g. apt or rpm.

you can also get the plugins for your ARCH from here:
https://github.com/containernetworking/plugins/releases

**Comment by tariqkipkemei** [comment]
That is strange since that package is already installed

'Package kubernetes-cni-0.7.5-0.x86_64 is already installed.
'

**Comment by neolit123** [comment]
is the plugin `firewall` found in `/opt/cni/bin`?

**Comment by tariqkipkemei** [comment]
No. Strange too

**Comment by tariqkipkemei** [comment]
this solved my problem:
cp /usr/libexec/cni/firewall   /opt/cni/bin

**Comment by neolit123** [comment]
this seems to be related to this ticket:
https://github.com/kubernetes/release/issues/242

the k8s CNI plugins should install to  /usr/libexec/cni RedHat based OSes.
but the long term plan is for k8s to stop shipping the CNI package and make the users install it manually from https://github.com/containernetworking/plugins/releases

/close

**Comment by Shridharbhandar** [comment]
> BTW,
> 
> Problem solved!
> ...
> 
> Your Kubernetes control-plane has initialized successfully!
> 
> To start using your cluster, you need to run the following as a regular user:
> 
> mkdir -p $HOME/.kube
> sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
> sudo chown $(id -u):$(id -g) $HOME/.kube/config
> 
> You should now deploy a pod network to the cluster.
> Run "kubectl apply -f [podnetwork].yaml" with one of the options listed at:
> https://kubernetes.io/docs/concepts/cluster-administration/addons/
> ...

What have you done to troubleshoot the issue?

**Comment by K1ngram4** [comment]
> > 顺便提一句，
> > 问题解决了！
> > ...
> > 您的 Kubernetes 控制平面已成功初始化！
> > 要开始使用您的集群，您需要以普通用户身份运行以下命令：
> > mkdir -p $HOME/.kube 
> > sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config 
> > sudo chown $(id -u):$(id -g) $HOME/.kube/config
> > 您现在应该将 pod 网络部署到集群。
> > 使用以下列出的选项之一运行“kubectl apply -f [podnetwork].yaml”：
> > [https](https://kubernetes.io/docs/concepts/cluster-administration/addons/) ://kubernetes.io/docs/concepts/cluster-administration/addons/ 
> > ...
> 
> 你做了什么来解决这个问题？

restart docker service
