### ISSUE TITLE
Scalability dimension: # access tokens

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#83375]
There's some practical limit on the number of concurrent access tokens that can be used in a Kubernetes cluster before it begins to spend all of its time in the authn stack verifying them. Absent fixes to https://github.com/kubernetes/kubernetes/issues/78766 it was < 500; with the fixes linked there it's still not infinitely scalable-- I still hit (what I believe to be) https://github.com/kubernetes/kubernetes/issues/83259 with ~ 5k unique tokens @ ~700QPS.

This request is to
1. Give this dimension an official name & definition, and list it with others, e.g. here: https://github.com/kubernetes/community/blob/master/sig-scalability/configs-and-limits/thresholds.md
2. Measure it
3. Make it have a useful value (I think it should be > 10k)

/kind bug
/sig scalability

**Comment by lavalamp** [comment]
oh and 4. add tests which verify it is as high as believed.

**Comment by liggitt** [comment]
cc @mikedanese since projected tokens will increase the number of unique tokens

**Comment by mikedanese** [comment]
LRUs are not good at scaling and sharding has some major pitfalls as @lavalamp  pointed out. I would suggest that we try to drop the LRU cache for successful authentication results in the token cache.

The main benefit of using an LRU here is bound cache size. Entries in the token cache have a fast expiration independent of the LRU policy. The records probably take up O(2kb) (guesstimate) of memory. Given that these are successful attempts with presumably valid tokens, I don't think we are getting any benefit from the LRU. If we don't have a constraint on fixed cache size, we can back the token cache with a sync.Map and run a single background goroutine to periodically walk the map and remove expired entries. This would fix the problematic locking and eviction due to nonuniform distribution of tokens over shards.

The failure cache is less important and we don't cache failures by default. If we consider this the "slowpath", we can probably leave it as. If that's not good enough, we have a couple options (with various tradeoffs) to improve it.

**Comment by mikedanese** [comment]
> The failure cache is less important.

If off by default is not enough, more reasoning why the failed cache is not super useful. It might help with an accidental DoS but it doesn't prevent anything actively malicious DoS. I think we can focus our improvements on the success cache.

**Comment by wojtek-t** [comment]
/assign @mm4tt 
He is already working on adding an explicit test for it.

**Comment by mm4tt** [comment]
@jprzychodzen has taken it over and is actively working on this.
Unfortunately, I cannot assign this issue to him as he's not a k8s member yet

**Comment by jprzychodzen** [comment]
It's not closed - all testes must be submitted and appropriate documentation must be added

**Comment by lavalamp** [comment]
Thanks everyone!!
