### ISSUE TITLE
Access external MongodB database from kubernetes cluster

### ISSUE THREAD

**Issue by farooqte96** [kubernetes/kubernetes#83393]
Hi

1. I have deployed a kubernets cluster using kops
2. Created deployment for a flask micro-service which will use a remote mongoDB database (which is not exposed to public internet).

To interface my remote mongodb, i created an endpoint which points to private ip of mongodB server and also port. But from microservice, i am unable to connect to that database:

Files for mongodb.yaml, services.yaml, workloads.yaml are added

and from my micro-service, i am accessing mongodb service named as "db" as follows:

client = MongoClient("mongodb://db:27017")

[mongodb.txt](https://github.com/kubernetes/kubernetes/files/3680740/mongodb.txt)
[services.txt](https://github.com/kubernetes/kubernetes/files/3680741/services.txt)
[workloads.txt](https://github.com/kubernetes/kubernetes/files/3680742/workloads.txt)

Can somebody tell me where i am wrong because POST request to mongodb give timeout as that request doesn't reach my mongodb from pod inside kubernetes cluster.

@kubernetes/sig-Network-feature-requests

Thanks

**Comment by php-coder** [comment]
@farooqte96 hi,
in order to make it easier to others to help you, could you modify the issue body and include the manifests instead of the links? There is a special markdown syntax with triple ticks that you can use.

Regarding the question: one I had exactly the same issue and after days of debugging I found out that it wasn't related to Kubernetes but rather with our network configuration. So, I'd advise to double check that.

**Comment by neolit123** [comment]
/sig cloud-provider
if you are not getting a response here, you can also try the #kops channel on slack or stackoverflow, or even reddit.
