### ISSUE TITLE
[RFC] Proposal for automatic API conversion tool for yaml/json files embedded in markdown

### ISSUE THREAD

**Issue by caesarxuchao** [kubernetes/kubernetes#8341]
Currently we manually convert the yaml/json files embedded in markdown files. To automate this process, we propose to add features to the kube-version-change tool:
- we need to remove the default fields in the output of kube-version-change tool
- we need to add a flag to kube-version-change that commands the tool to recursively convert all the .md files in a directory

Some code that maybe reused:
- `sampleRegexp` in examples/examples_test.go matches yaml/json block in markdown files

@nikhiljindal  @krousey @bgrant0607 could you @ more folks? Thank you.

**Comment by krousey** [comment]
Regarding the second bullet point, I think we could call break it out into 2 different steps.

 * Modify kube-version-change so that it understands and can convert YAML/JSON embedded in markdown files
 * Add a mode to kube-version-change so that it can recurse through directories and process all recognized file types.

**Comment by caesarxuchao** [comment]
I agree.

**Comment by nikhiljindal** [comment]
cc @lavalamp @bgrant0607

**Comment by bgrant0607** [comment]
See also #7576 -- the plan is to support conversion in kubectl

Instead of scraping markdown, how about we extract the examples into separate files and then generate the markdown (since github doesn't support imports/includes). That would reduce duplication with the runnable configs and would make testing simpler, also.

**Comment by krousey** [comment]
As far as properly handling default fields, the best way to handle this might be writing custom MarshalJSON or MarshalText methods on our API types. Currently Go does not omit zero valued structs with omitempty (this include time.Time). An alternative would be to use pointers with structs so nil will be omitted. Neither really seem ideal.

**Comment by krousey** [comment]
Alternatively, we could do a dirty hack just for this tool.

http://play.golang.org/p/El0eQVtb_X

Essentially, encode to JSON, decode into map[string]interface{}, recursively clean out nils and empty collections, re-encode to JSON.

Just had to post this for laughs.

**Comment by nikhiljindal** [comment]
cc @RichieEscarez

**Comment by RichieEscarez** [comment]
One thing to keep in mind is that I'll soon be moving all the user docs to "Kubernetes.io" (which means that these files will move out of the master branch, and into the gh-pages branch in github), so please consider that in the tool implementation.

**Comment by RichieEscarez** [comment]
Something i just stumbled across: "GitHub pages" which is what Kubernetes.io uses, does support includes, this troubleshooting topic outlines the requirements: https://help.github.com/articles/page-build-failed-file-does-not-exist-in-includes-directory/
