### ISSUE TITLE
Re-write Kubernetes in bash

### ISSUE THREAD

**Issue by jdumars** [kubernetes/kubernetes#83477]
1.) Improve readability of code
2.) Testing will be easier, since we can just skip them
3.) Will run everywhere using industry standard tools like grep and echo
4.) Who doesn't love bash??

**Comment by justaugustus** [comment]
Yes, we can follow the model that already exists in https://github.com/kubernetes/release
@kubernetes/bash-firefighters -- your time is here!
/priority important-longterm

**Comment by jdumars** [comment]
Some prior art from @rothgar 
https://github.com/rothgar/bashScheduler

**Comment by justaugustus** [comment]
As a first step, I think we need required presubmits that enforce `#!/usr/bin/env bash` shebangs on all files.
It'll allow us to easily catch all of the pesky Go code that's already in this repo, as well as enforce some consistency with the existing bash work.

**Comment by guineveresaenger** [comment]
Hi. This is your release team lead.

Is there a KEP for this enhancement?

**Comment by justaugustus** [comment]
We can have one in before Enhancements Freeze. 
@cblecker to author, @jdumars and I can do the review for it.

We'll probably be able to remove the `Test Plan` section from KEPs once this work lands.

**Comment by justaugustus** [comment]
**rolls up sleeves**
I got this.
/milestone v2.0

**Comment by jdumars** [comment]
I've got bashernetes.com all ready to go!

**Comment by rothgar** [comment]
Some good places to start include

bocker https://github.com/p8952/bocker
cni in bash https://github.com/eranyanay/cni-from-scratch
controller https://github.com/sterburg/bash-kubernetes-controller

I'm assuming we'll also need to rewrite kubectl, or at least wrap it
https://github.com/johanhaleby/kubetail

**Comment by cblecker** [comment]
/sig architecture
/shrug

You people are ridiculous. Also, you're amazing and I'm lucky to get to work with all of you. ❤️

**Comment by justaugustus** [comment]
Love you, @cblecker! So happy you got elected!!!

For the sake of inclusivity (for those who aren't in on this) and clarity... because I know someone will ask the question somewhere...
- This is a joke issue. There are no current plans, nor will there probably ever be plans to move Kubernetes to bash
- If by happenstance you ended up here via Twitter or some other means and want to contribute, here's a great starting point: https://github.com/kubernetes/community/blob/master/contributors/guide/contributor-cheatsheet/README.md

**Comment by lavalamp** [comment]
https://twitter.com/originalavalamp/status/848310500664332290

**Comment by stealthybox** [comment]
I'd like to propose we have a test-runner for the bash migration. It's important that we keep API compatibility as we move forward with these improvements.

Since containers are mostly bash already, projects like runC and docker-swarm use https://github.com/bats-core/bats-core for testing.
We could use bats or just write our own solution like we usually do.

We should be able to `sed` the existing [runC test suite](https://github.com/opencontainers/runc/tree/master/tests/integration) for our POSIX sh replacement of runC.

I definitely have free cycles to help port tests.
/sig testing

**Comment by ilyash-b** [comment]
Let's rewrite in [Next Generation Shell](https://ngs-lang.org/) (NGS)

* Highly popular (sorry you never heard about it)
* Only need to
  * Add support for sockets
  * Make sure GC works for long running processes (if not - fix GC)
  * Improve speed - just add static code analyzer, etc
  * Fix thread safety issues (or ask the author how to avoid)

**Comment by jdumars** [comment]
Unfortunately, I think this idea is waaaaaay ahead of its time, so I am going to close this issue and let future generations take this on.

**Comment by cblecker** [comment]
Thanks for being the visionary you are, @jdumars ❤️

**Comment by J00MZ** [comment]
> Let's rewrite in [Next Generation Shell](https://ngs-lang.org/) (NGS)
> 
> * Highly popular (sorry you never heard about it)
> * Only need to
>   
>   * Add support for sockets
>   * Make sure GC works for long running processes (if not - fix GC)
>   * Improve speed - just add static code analyzer, etc
>   * Fix thread safety issues (or ask the author how to avoid)

**#shameless-plug**

**Comment by ilyash-b** [comment]
> > Let's rewrite in [Next Generation Shell](https://ngs-lang.org/) (NGS)
> > 
> > * Highly popular (sorry you never heard about it)
> > * Only need to
> >   
> >   * Add support for sockets
> >   * Make sure GC works for long running processes (if not - fix GC)
> >   * Improve speed - just add static code analyzer, etc
> >   * Fix thread safety issues (or ask the author how to avoid)
> 
> **#shameless-plug**

I knew I forgot something! Thanks! Updated the original comment.

**Comment by cblecker** [comment]
Thanks for joining in on the fun. I'm going to lock this issue for posterity :)
