### ISSUE TITLE
kubelet should remove containers associated with deleted pods

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#8347]
Currently, the container garbage collector removes oldest (with some per-container constraints) containers when the maximum of 100 dead containers is exceeded. It is not aware of the notion of pods. However, once a pod has been deleted, there is really no reason to keep their dead containers around. We should remove those containers as soon as possible to free up space.

**Comment by zhengguoyong** [comment]
Do you mean we should not use MaxContainerCount to limit it ?  or just lower MaxContainerCount  value??

**Comment by jiangyaoguo** [comment]
I think this means removing containers of pod once we kill this pod. Does anyone has some opposite ideas?  Or we can working on this right now?

**Comment by dustymabe** [comment]
Since we closed #19571 I'd like to copy some of that issue contents here:

In the past there have been some issues (#1148 is one) about cleaning up containers. Now in kubelet there are a few options to control garbage collection of containers.. (the docs for these was added in https://github.com/kubernetes/kubernetes/pull/13087)

- maximum-dead-containers-per-container
- maximum-dead-containers

Should we add an option to kubelet:

- delete-containers-on-pod-deletion=false

Then the user could change it to `true` as an option to kubelet and after pod deletion all related containers would go away.

**Comment by dchen1107** [comment]
@timstclair I am assigning this one to you. I want to change kubelet flag to support 100 pods by default, meanwhile, we have to change maximum-dead-containers to some bigger numbers, like 200ish so that we wouldn't lose previous termination information. But there is a catch is that gc is only trigered when dead containers are reached maximum-dead-containers value, which is not good.

**Comment by timstclair** [comment]
Should we respect the MinAge to GC for deleted pods?

**Comment by yujuhong** [comment]
> Should we respect the MinAge to GC for deleted pods?

No, I don't think we need to, but if it's keeps the implementation cleaner/easier, I think it's ok.

**Comment by dchen1107** [comment]
I think we do need to respect the MinAge since this is part of gc policy being documented already. We introduced MinAge initially is for some good reasons, for example, even with removed pods on node, we want to leave some buffer time so that out-of-band daemon on the node can collect logs of removed pods if necessary. We don't really use that today, but that is the initial design.

**Comment by dchen1107** [comment]
For 1.2 release, I really want to have some low low hanging fruits so that we can unblock the feature of supporting 100 pods per node by default (#21570):

* Container gc should be triggered periodically to make sure the dead containers of per container is capped by maximum-dead-containers-per-container no matter maximum-dead-containers is hit or not
* Once a pod is removed (not terminated) by upstream layer, container gc should kick in to remove those dead containers with the respect to MinAge.

**Comment by timstclair** [comment]
> Container gc should be triggered periodically to make sure the dead containers of per container is capped by maximum-dead-containers-per-container no matter maximum-dead-containers is hit or not

It looks like that is already the case? Or is there a bug in the current implementation (https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockertools/container_gc.go#L195)

**Comment by yujuhong** [comment]
> It looks like that is already the case? Or is there a bug in the current implementation (https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockertools/container_gc.go#L195)

Yes, that's already the case today. 


> I think we do need to respect the MinAge since this is part of gc policy being documented already. We introduced MinAge initially is for some good reasons, for example, even with removed pods on node, we want to leave some buffer time so that out-of-band daemon on the node can collect logs of removed pods if necessary. We don't really use that today, but that is the initial design.

I think what we really need is the MinAge since the container stopped (#13562). We currently use the "Created" time, which doesn't mean much because the container may have been created a long time ago, but just recently stopped. We still need time to inspect the container and get logs. This will change the semantics of the GC policy, so it may not be for v1.2.

Also, IIUC, if we hit the limit of maximum dead containers, we may not respect maximum-dead-containers-per-container anymore. Not sure if this was documented properly.

**Comment by dchen1107** [comment]
> It looks like that is already the case? Or is there a bug in the current implementation (https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockertools/container_gc.go#L195)

Ok, that is great. @yujuhong are you observing a different behavior with stress test? Can we verify it?

> I think what we really need is the MinAge since the container stopped (#13562). We currently use the "Created" time, which doesn't mean much because the container may have been created a long time ago, but just recently stopped. We still need time to inspect the container and get logs. This will change the semantics of the GC policy, so it may not be for v1.2.

Agreed.
