### ISSUE TITLE
TopologyManager: Add a suite of E2E tests

### ISSUE THREAD

**Issue by klueska** [kubernetes/kubernetes#83481]
In order to graduate the `TopologyManager` to `beta` we need a suite of E2E tests to verify functionality in a more realistic setting than simple unit tests.

We plan to model the E2E tests we build for the `TopologyManager` after the `CPUManager` E2E tests from:
https://github.com/kubernetes/kubernetes/blob/master/test/e2e_node/cpu_manager_test.go

The matrix of tests we plan to build are being captured in the following spreadsheet:
https://docs.google.com/spreadsheets/d/1hxEhFle_GcWrJYHs8xaFulxugjETLWflEXmdeSeeufo

For the tests themselves we will need to somehow emulate a custom CPU topology so we can test various edge cases and large topologies. If we run the kubelet for the test in a container, maybe we can 'bind-mount` a new `/proc/cpuinfo` file into the container so that `cadvisor` detects a fake topology.

For devices, we can build multiple device plugins directly into the test binary that:
* Enumerate fake list of devices with NUMA affinity
* Set `ENVVAR` in `Allocate()` call to be able to inspect what was allocated

After the test we can compare the `ENVVAR` set to ensure the expected list of devices have been allocated with the proper alignment.

**Comment by vpickard** [comment]
Hi Kevin,
I've started looking at the CPUManager E2E tests that you reference above. I don't have access to the test matrix sheet yet, request has been sent. But, I did see if last week, had a short mtg with Louise to go over some of this stuff.

I'll start out with some basic tests for topology manger in my local env.  Perhaps, we could setup a short mtg next week to sync up?

**Comment by vpickard** [comment]
https://github.com/kubernetes/test-infra/pull/15599

**Comment by vpickard** [comment]
This PR adds some initial E2E tests for Topology Manager. Currently, this test suite loops through all of the Topology Manager policies, and runs a subset of CPU Manager tests.

https://github.com/kubernetes/kubernetes/pull/86184

**Comment by derekwaynecarr** [comment]
"If we run the kubelet for the test in a container"...

Since we have deprecated the ability to run kubelet in a container, I would avoid pursuing this strategy.  I prefer we write a test that skips when it runs in a single-numa node environment, but runs properly when on multi-numa node hardware that anyone can run and reproduce on proper hardware.  The whole point of an e2e test is to validate on a proper setup, and we can defer to unit testing to do the mock style testing.  We can run this test and provide a periodic publishing of its status to ensure we don't regress.

**Comment by vpickard** [comment]
@klueska I think it is ok to go ahead and close this issue. The only test code that has not merged is some upgrade tests.
