### ISSUE TITLE
rkt: Import trusted pub keys for ACI verification.

### ISSUE THREAD

**Issue by yifan-gu** [kubernetes/kubernetes#8351]
In order to enable the ACI signature verification in rkt, we need to provide the rkt runtime a list of trusted public keys. I am thinking maybe we can do this during the creation of the runtime?

For example, provide a flag to specify a `trusted_keys.json` file, which looks like:

```
{
    {
        "prefix": "coreos.com/etcd",
        "pubkey":"PUBKEY_STRING",
        "root": false
    },
    {
        "prefix": "fluentd.org/fluentd",
        "pubkey": "PUBKEY_STRING",
        "root": false
    },
    ...
}
```

/cc @dchen1107 @vmarmol @bakins @philips

**Comment by yifan-gu** [comment]
Or maybe we can use the Secret to pass the pubkeys and prefix, then let kubelet/rkt to write those keys in the /etc/rkt/trustedkeys/

**Comment by erictune** [comment]
That would preclude use of images for file based pods when the master is
unavailable (during bootstrap or a failure).  Needs to be per-node at
least, and maybe also per container.

 @pmorie because you wrote #7627

This is sort of like a pull secret, but not so secret, since it is a public
key.

@deads2k because you wrote  #7894

@lavalamp because you are reviewing  #7894

**Comment by lavalamp** [comment]
Yes, it sounds like this could be another type of pull secret. (see also #8517)

**Comment by deads2k** [comment]
Is the `trusted_keys.json` based on an existing format or is it a representation you're working on now?  If it's the latter, then I think it would be useful to allow the file to contain the public key itself, similar to how we do with `.kube/config` files today.  That makes it very easy to ensure that the information is fully portable.

Since this information isn't used to authenticate the kubelet to the repository, I think I like the idea of having this be per-node.  The public keys will be the same for every image pull attempt against the particular prefix and it's not privileged information.

**Comment by yifan-gu** [comment]
Also by now this is a one-time setup per node, we only need to receive the pubkeys once and write it down on the config file. So I think I am not very worried when master is unreachable.

**Comment by yifan-gu** [comment]
After a little bit more thought and playing with secrets, I think I am going to take the original approach, which provides the `trusted_keys.json`. Because it's easier to let rkt do the trust during the bootstrapping.

**Comment by runningwild** [comment]
This hasn't been touched in a while, but I'm interested in getting this in.  Yifan: is your PR still reasonable to get merged?  If you aren't planning on actually getting it merged in I will work on this issue.

**Comment by yifan-gu** [comment]
@runningwild I am not able to go back to this in a week or two. Feel free to take the work :)
