### ISSUE TITLE
[Failing test] [sig-storage] CSI Volumes [Driver: pd.csi.storage.gke.io][Serial] [Testpattern: Dynamic PV (block volmode)] disruptive[Disruptive] Should test that pv written before kubelet restart is readable after restart.

### ISSUE THREAD

**Issue by droslean** [kubernetes/kubernetes#83524]
**Which jobs are failing**:

`gce-cos-master-serial`

**Which test(s) are failing**:
`[sig-storage] CSI Volumes [Driver: pd.csi.storage.gke.io][Serial] [Testpattern: Dynamic PV (block volmode)] disruptive[Disruptive] Should test that pv written before kubelet restart is readable after restart.`

**Since when has it been failing**:
There is not a successful run for this particular test case (tracked from 21 Sep)

**Testgrid link**:
[sig-release-master-blocking#gce-cos-master-serial](https://k8s-testgrid.appspot.com/sig-release-master-blocking#gce-cos-master-serial)

**Reason for failure**:
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-serial/1179888488984612874#1:build-log.txt%3A27813
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/testsuites/disruptive.go:145
Oct  4 01:50:13.819: waiting for csi driver node registration on: timed out waiting for the condition
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/drivers/csi.go:470
```

**Anything else we need to know**:
@childsb @saad-ali

**Comment by alejandrox1** [comment]
This test is not currently running in this dashboard but it seems to be a problem overall. See triage for all recent failures https://storage.googleapis.com/k8s-gubernator/triage/index.html?test=Should%20test%20that%20pv%20written%20before%20kubelet%20restart%20is%20readable%20after%20restart

Looking at the logs from the latest run, where the test was not run ([prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-serial/1180415602414587908](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-serial/1180415602414587908#1:build-log.txt%3A21301)):
```
I1005 11:45:40.704] S [SKIPPING] [1.378 seconds]
I1005 11:45:40.705] [sig-storage] CSI Volumes
I1005 11:45:40.705] /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/utils/framework.go:23
I1005 11:45:40.705]   [Driver: pd.csi.storage.gke.io][Serial]
I1005 11:45:40.705]   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/csi_volumes.go:56
I1005 11:45:40.705]     [Testpattern: Dynamic PV (block volmode)] disruptive[Disruptive]
I1005 11:45:40.705]     /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/testsuites/base.go:92
I1005 11:45:40.705]       Should test that pv written before kubelet restart is readable after restart. [It]
I1005 11:45:40.706]       /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/testsuites/disruptive.go:145
I1005 11:45:40.706] 
I1005 11:45:40.706]       Driver pd.csi.storage.gke.io doesn't support Block -- skipping
I1005 11:45:40.706] 
I1005 11:45:40.706]       /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/testsuites/disruptive.go:93
```

We can see that it the test mentioned in this issue should not be run because "Driver pd.csi.storage.gke.io doesn't support Block".

For reference, it looks like the code for this test can be found here https://github.com/kubernetes/kubernetes/blob/master/test/e2e/storage/testsuites/disruptive.go#L126
and specifically the problematic part seems to be this snippet
https://github.com/kubernetes/kubernetes/blob/master/test/e2e/storage/testsuites/disruptive.go#L92-L94 :
```go
if pattern.VolMode == v1.PersistentVolumeBlock && !driver.GetDriverInfo().Capabilities[CapBlock] {
		framework.Skipf("Driver %s doesn't support %v -- skipping", driver.GetDriverInfo().Name, pattern.VolMode)
}
```

/cc @kubernetes/sig-storage-test-failures 
/priority critical-urgent
/milestone v1.17

**Comment by msau42** [comment]
Test was prematurely enabled and then subsequently disabled in https://github.com/kubernetes/kubernetes/pull/83409.

So the test being skipped now is intended.

/close
