### ISSUE TITLE
Getting no route to host when trying to access Kubernetes service from pod

### ISSUE THREAD

**Issue by vishal49naik49** [kubernetes/kubernetes#83606]
Kubernetes service is running in default namespace.
Launched pods in default namespace and in other ones likes dev, prod etc.

Cannot access Kubernetes service from the pods.

Getting "No route to host". Please advise.

**Comment by vishal49naik49** [comment]
sig/network

**Comment by vishal49naik49** [comment]
sig/testing

**Comment by vishal49naik49** [comment]
@kuberntes/sig-networking

**Comment by vishal49naik49** [comment]
The pod has no internet access whatsoever. if launch a simple docker container on the worker node, it has internet access however the pod does not.

**Comment by aojea** [comment]
@vishal49naik49 what CNI are you using? are you using kube-proxy? ipvs or iptables?

**Comment by aojea** [comment]
You have to check your CNI configuration and try to make your CNI plugin work, 
try to verify that iptables is working correctly too

/triage support

**Comment by johscheuer** [comment]
Can you try the following from one of your nodes:

```bash
kubectl get svc
NAME         TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)   AGE
kubernetes   ClusterIP   10.96.0.1       <none>        443/TCP   20h
```

use this IP address and try to curl it:

```bash
curl -k https://10.96.0.1/apis
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "forbidden: User \"system:anonymous\" cannot get path \"/apis\"",
  "reason": "Forbidden",
  "details": {
    
  },
  "code": 403
}
```

How did you setup your cluster? Please check the following things:
- Ensure that the `podSubnet` (default for calico: `192.168.0.0/16`) is not overlapping with a real subnet
- Ensure that the `serviceSubnet` (default: `10.96.0.0/12`) is not overlapping with a real subnet (e.g. your workers)

The service IP should be working without CNI since kube-proxy implements it. I assume that you have some overlapping subnets in your setup.
if you used kubeadm you can run `kubeadm config view` to see this information

**Comment by duiniwukenaihe** [comment]
my kubernets 1.16.2 cluster update to 1.163 have this program too

**Comment by thockin** [comment]
For people seeing this - please run through https://kubernetes.io/docs/tasks/debug-application-cluster/debug-service/ and if you still can't figure it out, come back to this.
