### ISSUE TITLE
topology manager not behaving as expected in 1.16

### ISSUE THREAD

**Issue by cbf123** [kubernetes/kubernetes#83695]
**What happened**:
I think I'm seeing a problem with the topology manager.  I have two numa nodes, 22 cores per node.  Kubelet has "--cpu-manager-policy=static --topology-manager-policy=single-numa-node ", and when I try to create a simple pod with 3 cpus and 500Mi of RAM in the guaranteed class it fails.  Describing the pod gives "Resources cannot be allocated with Topology Locality", but I know there's lots of CPU and RAM available on both NUMA nodes.  I'm instrumenting the topology manager kubelet code, currently there's not enough debug logs to actually be able to tell what's going wrong.

**What you expected to happen**:
I expect the pod container to be created on one or the other numa node and get allocated exclusive CPUs (via the static policy) on that NUMA node, and be affined to those CPUs.

**How to reproduce it (as minimally and precisely as possible)**:
On a kubernetes node with multiple NUMA nodes, enable kubelet with static cpu manager policy and single-numa-node topology manager policy.  Try to create a basic pod with a single container in the guaranteed QoS class.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
sysadmin@controller-0 chris(keystone_admin)]$ kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"archive", BuildDate:"2019-10-09T05:41:44Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:27:17Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
wildcat pass hardware, 22 cores per NUMA node, two NUMA nodes.  64GB RAM per NUMA node.

- OS (e.g: `cat /etc/os-release`): CentOS 7
- Kernel (e.g. `uname -a`): 3.10.0-957.21.3.el7.2.tis.x86_64

**Comment by cbf123** [comment]
@kubernetes/sig-node-bugs

**Comment by cbf123** [comment]
oops, I thought the "close" meant the comment, not the whole issue. :)

**Comment by klueska** [comment]
I was able to reproduce this issue.

The following (new) uint test in `topology_manager_tests.go` fails unexpectedly:
```
        {
            name: "Two providers, one with no preference",
            policy: NewSingleNumaNodePolicy(),
            hp: []HintProvider{
                &mockHintProvider{
                    map[string][]TopologyHint{
                        "resource1": {
                            {
                                NUMANodeAffinity: NewTestBitMask(0),
                                Preferred:        true,
                            },
                            {
                                NUMANodeAffinity: NewTestBitMask(1),
                                Preferred:        true,
                            },
                            {
                                NUMANodeAffinity: NewTestBitMask(0,1),
                                Preferred:        false,
                            },
                        },
                    },
                },
                &mockHintProvider{
                    map[string][]TopologyHint{
                        "resource2": {
                            {
                                NUMANodeAffinity: NewTestBitMask(0,1),
                                Preferred:        true,
                            },
                        },
                    },
                },
            },
            expected: TopologyHint{
                NUMANodeAffinity: NewTestBitMask(0),
                Preferred:        true,
            },
        },
```

With any policy other than the `SingleNumaNodePolicy()` this test passes.

This is due to 3 factors:
1) The CPUManager is the only hint provider passing actual valid hints `[{01 true}, {10 true}, {11 false}]`
2)The devicemanager passes `nil` back as its hints, resulting in a single `{11 true}`
3) We added a special casing for the `SingleNumaNodePolicy()` in the device manager that essentially turns the devicemanager's hint into a `{11 false}`: https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/cm/topologymanager/topology_manager.go#L243

Because the single hint from the devicemanager now has a `false` preference, there is no chance to have it combine with any of the CPUManager hints to result in a successful hint.

This should ultimately be addressed as part of the following in 1.17 
https://github.com/kubernetes/kubernetes/issues/83478

But we should put a one-off patch into the 1.16.x branch to fix this in 1.16.

**Comment by mrunalp** [comment]
@rphillips @zvonkonk ptal

**Comment by pperiyasamy** [comment]
I've just updated #413 with my observations. 
can you have a look and comment ?
