### ISSUE TITLE
apiserver_request_count is very big in prometheus

### ISSUE THREAD

**Issue by ajax-2** [kubernetes/kubernetes#83703]
# Event
Yesterday, my apiserver always crashed because "the number of 
"secrets" sent by kubelet to apiserver" was very large and was not released."
# Enviorment
kubernetes: 1.8
# picture
![image](https://user-images.githubusercontent.com/29370146/66538540-5dce6400-eb57-11e9-8aa1-d6881e8be35d.png)

**Comment by ajax-2** [comment]
@kubernetes/sig-kubelet-request-count

**Comment by liggitt** [comment]
prior to 1.14, kubelets would poll the API server for updates to secrets/configmaps they have mounted into pods, in order to know whether the contents have changed and they need to update the mounted data. it is expected that the request count will increase over time.

in 1.14+, kubelets watch for changes, which is more efficient.

/close
