### ISSUE TITLE
Undo traffic shaping config when annotations are removed

### ISSUE THREAD

**Issue by zanetworker** [kubernetes/kubernetes#83723]
**What would you like to be added**:
Since https://github.com/kubernetes/kubernetes/pull/63194/files traffic shaping has been supported in the form of annotation. However, there is no way to undo the config, if the annotations are removed for example, then the config would still be there. 

My expectation is that if the ingress/egress annotations are removed, then the traffic shaping config on the interface should also be removed. 

**Why is this needed**:
This is needed to prevent un-necessary side effects. 

/sig network

**Comment by thockin** [comment]
This is a big part of why the annotations were considered a poor API.  There's no CNI calls after startup to re-program these.

The most correct answer is that we're probably not going to fix this until we have a more complete overhaul of the network plugin system, which includes some impact on pod lifecycle.

**Comment by zanetworker** [comment]
mmm do we already have an issue that you can point me too for how that overhaul would look like? To me this annotation is tied to the dockershim, so other CRIs would not have that by default, maybe that should be moved out to be more generic, and also have its own lifecycle?

**Comment by rikatz** [comment]
@thockin So as this is a part of a pod lifecycle, maybe we should make this a field in Pod specification and remove the traffic shaping when this field is also changed, and triggers a reconciliation which will recreate the Pod and all the networking stuff.

If this is a thing I can work on it, proposing the field creation (instead of using the annotation) and changing the bandwidth part in a later PR after (and if) the newer field is accepted.

WDYT?
