### ISSUE TITLE
Pods  error out with 'Topology Affinity Error' if resources and limits are not mentioned as part of the pod spec. This is after #83492 

### ISSUE THREAD

**Issue by Deepthidharwar** [kubernetes/kubernetes#83775]
**What happened**:

With the latest fix #83697 , which aims to resolve the issue of deploying pods with single-numa-node policy, it seems to have resulted in failure to deploy pods if the pod spec does not have resources and limits constraints. This is resulting in Kube-dns and other pods which do not have resource constraints mentioned fail to deploy due to Topology Affinity Error.
kube-system   kube-dns-b54d5f547-22dks   0/3     Topology Affinity Error   0    

**What you expected to happen**:
Ideally, if there are no resource constraints mentioned we will still need the pod to be deployed. 
We cannot have Kube-dns failing to deploy due to Topology Affinity issue.

**How to reproduce it (as minimally and precisely as possible)**:
With the latest fix, enabling single-numa-node policy, Kube-dns errors out on the node. 
One can just try to deploy simple pod without resource constraints in pod spec. 

**Anything else we need to know?**:
This happens only when policy is single-numa-node. Pods do not fail to deploy for best-case policy. 

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T17:01:15Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.0-alpha.1.338+017842d49deca6-dirty", GitCommit:"017842d49deca68dab3a26b76d5dfd5df15a8113", GitTreeState:"dirty", BuildDate:"2019-10-11T10:39:19Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration: 
   Baremetal x86 server with 2 NUMA nodes and 32 cpus.
- OS (e.g: `cat /etc/os-release`): Fedora 28
- Kernel (e.g. `uname -a`): 5.0.13-100.fc28.x86_64

**Comment by Deepthidharwar** [comment]
@kubernetes/sig-node-bugs

**Comment by lmdaly** [comment]
@Deepthidharwar thanks for alerting us to the issue. Can you try the PR linked?

**Comment by klueska** [comment]
My guess is that this issue was introduced after https://github.com/kubernetes/kubernetes/pull/83492 landed.

Before that, best-effort pods weren't even being considered by the TopologyManager, and the logic for admitting vs. not admitting was skipped.

Which means that we need this fix for this on master, but do not need it on the 1.16 branch.

**Comment by klueska** [comment]
@zvonkok can you verify if it works as expected in the release-1.16 branch. this would verify my claim that it broke with the introduction of #83492 not the fix from #83697

**Comment by zvonkok** [comment]
@Deepthidharwar PTAL

**Comment by Deepthidharwar** [comment]
@klueska , That's right. This fix is needed for the master branch and not 1.16.
 1.16 works well without #83492.

**Comment by klueska** [comment]
/cc @ConnorDoyle for visibility.

This issue appeared as a result of #83492

**Comment by ConnorDoyle** [comment]
Thanks for the ping. So is the proposed fix to always admit best-effort pods in the topology manager?

**Comment by klueska** [comment]
This only affects the single-numa-node policy because of the "hack" we currently have in place for it: https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/cm/topologymanager/topology_manager.go#L248

The right long term fix is to address this as part of: https://github.com/kubernetes/kubernetes/issues/83478

However, if we want to put a short term fix in place to "unbreak" master, @lmdaly has a PR linked above that will fix the immediate problem.
