### ISSUE TITLE
Secrets/service accounts in static pods

### ISSUE THREAD

**Issue by jimmidyson** [kubernetes/kubernetes#8379]
Are secrets or service accounts supported in static pods? It's quite conceivable that static pods will require talking to the API server & providing credentials to do so via secrets or service accounts is the best way to do this.

A particular use case that I'm working on is logging. This requires a per-node pod to capture the container logs, enrich with Kubernetes metadata (labels, etc) which is only available from the API server, before storing via a standard Kubernetes service. See #8001 for more details.

I've discussed this with @pmorie & he has some other use cases for this, one being the ability to run the kubelet itself in a pod.

/cc @satnam6502

**Comment by satnam6502** [comment]
An alternative is to wait for a per-node controller and doing away with static pods. @thockin

**Comment by liggitt** [comment]
+1 for per-node controller. Static pods that require the kubelet to have API access seems very odd to me.

**Comment by jimmidyson** [comment]
Per node controller sounds great but isn't available yet AFAIK? Any ETA?

Why do static pods accessing api server seem weird to you @liggitt?

**Comment by liggitt** [comment]
Because they're independent config sources, and the streams shouldn't cross?

Also, the admission chain is hamstrung when interacting with mirror pods… if anything in the pod spec gets manipulated in the admission chain, the kubelet gets distraught and goes into a delete/recreate loop.

**Comment by liggitt** [comment]
Static pods referencing API objects in their spec is what seems weird.

**Comment by jimmidyson** [comment]
@liggitt Fair points. So in the absence of per-node controllers are there any other options?

**Comment by jimmidyson** [comment]
@liggitt Any more thoughts on this? Need a way for static pods to talk securely to cluster services, secrets seem the natural way to do this but being unusable in static pods would mean finding another way to distribute them, e.g. ansible.

**Comment by satnam6502** [comment]
Can we get rid of static pods when we have a daemon controller?

**Comment by satnam6502** [comment]
@AnanyaKumar

**Comment by AnanyaKumar** [comment]
I'm not entirely familiar with the functionality of static pods. But if the pods don't need to run in a special privileged mode, then we can use the upcoming Daemon API object. #11801

**Comment by jimmidyson** [comment]
@AnanyaKumar Looks great! Probably would need to be privileged containers though, as they are now iirc for logging. Probably no reason to be if selinux contexts are configured properly on the hosts log files I guess.

**Comment by AnanyaKumar** [comment]
I think eventually we hope to support privileged containers in Daemon as well :)

**Comment by dchen1107** [comment]
We definitely can get rid of fluentd static pod soon through daemon controller, but not sure about all master pods, especially kube-apiserver and etcd.

**Comment by liggitt** [comment]
I still don't think static pods can ever assume an API connection exists, which is needed for secrets. I also think the daemon controller will be the "right" way to run something on every node, but I have no idea on the eta of that

**Comment by pmorie** [comment]
The daemon controller won't solve the problem of running static pods that use secrets.

Thinking about it a little, this is perhaps a case where splitting the API into different feature sets makes sense.  You only need the API for secrets and service accounts in order to work with them from mirror pods.  

@satnam6502 I'm not sure we can get rid of static pods once we have the daemon controller.  There's a use-case which you _can_ do (though I don't know of a specific group or individual that _is_) where you run the kubelet in 'run-once' mode to create some pods from a source.  Getting rid of static pods seems like it would make that use-case undoable.  I'd be curious to know whether anyone is actually using the run once functionality in a production-like environment.

**Comment by davidopp** [comment]
@pmorie Why can't daemon controller subsume all the use cases for static pods?

**Comment by pmorie** [comment]
@davidopp Maybe it can and I have a mismatch misunderstanding -- I'll reexamine it

**Comment by pmorie** [comment]
@davidopp 

The specific use case I was thinking of may not be an official one.  I only list it because since you _can_ do it now, someone might be doing it, whether we intended for people to do this or not.  With that in mind, here goes.  Today, I can run the kubelet in run-once mode on a particular host to run things in pods without using the API server.  If I want to run a particular pod this way on _only a subset_ of nodes, I don't think daemon controller solves that.  If that's not a use case we're going to support, that's cool, but I haven't found anything in writing yet in my (admittedly probably incomplete) reading on the subject.  Thoughts?

**Comment by davidopp** [comment]
Daemon controller takes node selector just like ReplicationController. Can you use that to select which node(s) you want to use? (Or maybe I am misunderstanding the problem.)

**Comment by bgrant0607** [comment]
cc @erictune

**Comment by jimmidyson** [comment]
Daemonsets are the way to go.
