### ISSUE TITLE
[migration phase 1] InterPodAffinityPriority as filter plugin

### ISSUE THREAD

**Issue by ahg-g** [kubernetes/kubernetes#83873]
**What would you like to be added**:

Add a filter plugin that calls into InterPodAffinityPriority predicate, example #83460

**Why is this needed**:

Part of  #83554

/sig scheduling
/help
/priority important-soon

**Comment by lichuqiang** [comment]
@ahg-g We have several pod affinity related error types defined: `ErrPodAffinityNotMatch`, `ErrPodAffinityRulesNotMatch`, `ErrPodAntiAffinityRulesNotMatch`, `ErrExistingPodsAntiAffinityRulesNotMatch`.

But I noticed that we only marked `ErrPodAffinityRulesNotMatch` as unresolvable in `unresolvablePredicateFailureErrors`. Any special reason for this?

**Comment by ahg-g** [comment]
This doesn't impact how we do this task, right?

But to answer your question, it seems that ```ErrPodAffinityRulesNotMatch``` is related to node ["didn't match pod affinity rules"](https://github.com/kubernetes/kubernetes/blob/81a8b9804a3bf310cb74446bd8a8e08e0317de22/pkg/scheduler/algorithm/predicates/error.go#L43:2), and that is an unresolvable error preemption wouldn't hep resolving such an error (preemption wouldn't change node labels for example)

**Comment by lichuqiang** [comment]
I see. It has nothing to do with the task itself, except for the expected results in unit tests :)

**Comment by hprateek43** [comment]
Is a PR open for this? If not, I can pick it.

**Comment by lichuqiang** [comment]
@hprateek43 Thanks, I'm working on this.

**Comment by lichuqiang** [comment]
@ahg-g To my surprise, the anti-affinity related test cases cannot get passed after simply migrating to the new framework. I think the only difference is that we don't have predicateMetadata provided in the new framework.

Looking into the code, seems we have difference in the behavior of processing anti-affinity with/without PredicateMetadata provided: [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/algorithm/predicates/predicates.go#L1509) with predicateMetadata provided, it decides pod unschedulable if any of the terms matched; while [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/algorithm/predicates/predicates.go#L1545) without predicateMetadata provided, it won't decide a pod as unschedulable unless all of the terms matched.

cc @Huang-Wei for confirmation. Is this by design? Or we should have a fix?

**Comment by ahg-g** [comment]
The predicate metadata is available in the cycleState, here is an example:
https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/framework/plugins/noderesources/node_resources.go#L45-L48

I will let @Huang-Wei answer to the question why the else path is not behaving the same, that path is executed in the cluster autoscaler case, not the scheduler, we still need to make sure it behaves correctly, but it is not a blocker to this task.

**Comment by lichuqiang** [comment]
Oh, got it! thanks

**Comment by Huang-Wei** [comment]
@lichuqiang You're right. It's a legacy bug, we used to have a PR #69719 working on this. I'm pinging the author to rebase and we will approve that one.

(Let me know if that PR resolves the symptom you observed here)
