### ISSUE TITLE
hack/cherry_pick_pull.sh: fails to fetch kind/priority/sig

### ISSUE THREAD

**Issue by tpepper** [kubernetes/kubernetes#83981]
I've been seeing a lot of cherry picks on patch release branches where kind/priority/sig are not set automatically from the parent PR on master.  I wondered if maybe this was due to the person not being an org member, but I just submitted:

https://github.com/kubernetes/kubernetes/pull/83980

via the cherry pick automation.  It did not automatically get its kind/priority/sig from my

https://github.com/kubernetes/kubernetes/pull/83979

It's possible this is a timing issue, as those labels were only applied a very short time before t the cherry pick was created.  At any rate, this needs investigated as improper labeling leads to slower triage and slower merge approval from OWNERS.

/sig release
/kind bug
/priority important-soon

**Comment by nikhita** [comment]
The labels on the PR are set by looking at the OWNERS files. If an OWNERS file has the `labels` field, the labels specified there are automatically added to the PR.

https://github.com/kubernetes/kubernetes/pull/83980 and https://github.com/kubernetes/kubernetes/pull/83979 don't automatically get kind/priority/sig labels because they touch root files and no SIG label is defined for the root OWNERS file.

> I've been seeing a lot of cherry picks on patch release branches where kind/priority/sig are not set automatically from the parent PR on master.

We don't really have any automation in place that does this right now...though it should be easy to add it to prow. :)

Having said that, I wonder if it's worth adding a new prow plugin for this since the SIG label would automatically be added using OWNERS files (if they aren't, it means that the OWNERS file in the patch release branch does not contain the `labels` field...since most of these fields were added recently). `kind/*` and `priority/*` labels are the only ones that would be needed to be added manually.

To be clear, I don't have strong opinions on automating this. Just curious if it warrants a new plugin or not.

/cc @cblecker

**Comment by cblecker** [comment]
@nikhita is correct, and I also agree that this probably isn't needed.

As there is no bug in the current automation, I'm going to close this. If you'd like to start a conversation about adding new automation, please open up an RFE against test-infra
