### ISSUE TITLE
Document how to limit access to /version api endpoint

### ISSUE THREAD

**Issue by kmoorfield** [kubernetes/kubernetes#84040]
**What would you like to be added**:
The ability to turn off / disable the "/version" api endpoint on the Kubernetes master node.

**Why is this needed**:
To hide the version information for security, so that scanners can't find the current version of the Kubernetes cluster and then know what exploits to use against the cluster.

**Comment by liggitt** [comment]
Security through obscurity is unlikely to actually improve security. An attacker would just iterate through all available exploits.

**Comment by Planktonette** [comment]
This is true, but it's long since been beyond discussion that not giving away information to basic information gathering techniques is in fact a good thing.

If, for instance, the approach was to simply disable /version while not patching for known exploits, then yes, that would indeed be "security through obscurity". On the other hand, shouting your specific version to any tom dick or harry who asks merely makes a given adversaries life easier; doing things like disabling trivial fingerprinting to make an attackers life slightly more difficult is just another layer of good security practise.

There's really no good argument not to.

May I ask why /version is so important?

**Comment by kmoorfield** [comment]
On a similar note, it might not be that hard to just move the /version endpoint behind authentication, as it seems to be one of the only unauthorised endpoints that exist (that I know of currently in v1.16.0).
This would do the same function as just disabling the endpoint.

**Comment by Planktonette** [comment]
Also, if it helps any, tools like kube-hunter and similar list this as a vulnerability:

```
  "vulnerabilities": [
    {
      "location": "x.x.x.x:6443",
      "category": "Information Disclosure",
      "severity": "medium",
      "vulnerability": "K8s Version Disclosure",
      "description": "The kubernetes version could be obtained from the /version endpoint ",
      "evidence": "v1.16.0",
      "hunter": "Api Version Hunter"
    }
```

So from an infosec auditing perspective, being bugged by this on every scan is annoying when there's no option to disable from the vendor.

**Comment by liggitt** [comment]
> On a similar note, it might not be that hard to just move the /version endpoint behind authentication, as it seems to be one of the only unauthorised endpoints that exist (that I know of currently in v1.16.0).

It is already behind authentication/authorization. It is included in the [`system:public-info-viewer`](https://github.com/kubernetes/kubernetes/blob/release-1.16/plugin/pkg/auth/authorizer/rbac/bootstrappolicy/testdata/cluster-roles.yaml#L1177-L1194) role by default.

The healthz/readyz/livez endpoints have the clearest use case (unauthenticated load balancers needing to know whether to include the server in their rotation or not).

**Comment by riking** [comment]
Given that this is in `system:public-info-viewer`, does that mean this is simply a documentation bug for (oneof k8s, kube-hunter)?

**Comment by Planktonette** [comment]
Would that mean that passing --anonymous-auth=false to the API configuration would turn off these public endpoints then?

**Comment by liggitt** [comment]
> Would that mean that passing --anonymous-auth=false to the API configuration would turn off these public endpoints then?

It would.

**Comment by liggitt** [comment]
Added to the [sig-auth agenda](https://docs.google.com/document/d/1woLGRoONE3EBVx-wTb4pvp4CI7tmLZ6lS26VTbosLKM/edit#) for discussion on 2/19

**Comment by enj** [comment]
If one wants to avoid restarting the API server, a simple approach would be to remove the desired `nonResourceURLs`:

```shell
kubectl replace -f - <<EOF
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "false"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: system:public-info-viewer
rules:
- nonResourceURLs:  # /version has been removed
  - /healthz
  - /livez
  - /readyz
  verbs:
  - get
EOF
```

The `rbac.authorization.kubernetes.io/autoupdate: "false"` annotation will prevent the API server from reconciling the cluster role.

I find this to be the most targeted approach.  You do take ownership of maintaining the `system:public-info-viewer` cluster role over time, but it does not really change.

We can decide based on the next SIG Auth meeting if the above is something we would like to document (or if some other approach is more desirable).

**Comment by liggitt** [comment]
Documenting these steps could be added to https://kubernetes.io/docs/reference/access-authn-authz/rbac/#discovery-roles and referenced from https://kubernetes.io/docs/tasks/administer-cluster/securing-a-cluster/#api-authorization

/remove-kind feature
/kind documentation
/help

**Comment by mmerrill3** [comment]
in version 1.17.5 of k8s, the clusterrole system:public-info-viewer is tied to the clusterrolebinding of the same name.  Passing in the --anonymous-auth flag to the kubernetes API server doesn't limit access to the API with this version.  I believe this is since this endpoint is open to unauthenticated users, as well as authenticated users.

The subjects for the clusterrolebinding are here:

`  subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: system:authenticated
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: system:unauthenticated
`

The easiest way to turn off the /version endpoint is by removing it from the  clusterrole system:public-info-viewer.

**Comment by enj** [comment]
Setting `--anonymous-auth=false` will prevent unauthenticated requests from being served anything via the API.  That is, no request will be assigned to the `system:unauthenticated` group.

**Comment by mmerrill3** [comment]
Yeah, I think what I'm seeing is kubehunter running with the default service account, so it's authenticated, but as the default user.  So, kubehunter keeps complaining that it can see the /version API.  Thanks for clarifying.
