### ISSUE TITLE
Kubernetes namespaces stuck in terminating state 

### ISSUE THREAD

**Issue by cmcarey** [kubernetes/kubernetes#84109]
These issues are still present despite the tickets being closed:

- https://github.com/kubernetes/kubernetes/issues/73186
- https://github.com/kubernetes/kubernetes/issues/19317
- https://github.com/kubernetes/kubernetes/issues/60807

**Comment by tedyu** [comment]
Can you provide more information such as controller manager log (snippet) ?

Thanks

**Comment by liggitt** [comment]
Namespaces remain in terminating state until all namespaced resources can be verified to have been cleaned from the namespace. 

That requires ALL registered APIs to be available. Typically when a namespace remains in terminating state, an aggregated API (registered with an APIService object) is unavailable. In 1.16, the namespace cleanup controller adds details to the namespace status if it is blocked waiting for an API to become available. 

What version are you running and what is the content of the namespace object that is in terminating (`kubectl get namespace $name -o yaml`)

**Comment by thyarles** [comment]
Hi guys,

Until we have an fix, I made a script to make life easier: https://github.com/thyarles/knsk. It kill all namespaces in **Terminating** status.

Thanks.

**Comment by hawksight** [comment]
> In 1.16, the namespace cleanup controller adds details to the namespace status if it is blocked waiting for an API to become available.

Does that mean the namespace will identify the actual resources (apiservice or other) that are blocking it's deletion? Making it easier to go and manually clean them up?

**Comment by arunramachandran15** [comment]
Even after fully terminating a namespace by removing finalizer array, seems like there will be orphaned resources. So because of orphaned resources I am not able to **create** a resource with same name before terminating the namespace. I can also list all the resources that were existing as orphans.

Scenario:
1. Kubectl create ns webapps
webapps namespace created
2. Kubectl create secret -f secret1-admin-password.yaml -n webapps
secret admin-password created
3. Kubectl delete ns webapps
webapps namespace deleted
4. Command to terminate namespace with finalizer method 
( NAMESPACE=webapps; kubectl proxy & kubectl get namespace $NAMESPACE -o json |jq '.spec = {"finalizers":[]}' >temp.json; curl -k -H "Content-Type: application/json" -X PUT --data-binary @temp.json 127.0.0.1:8001/api/v1/namespaces/$NAMESPACE/finalize; )
5. Kubectl get ns webapps
Error from server (NotFound): namespaces "**webapps**" not found
6. Kubectl create ns webapps
webapps namespace created
7.  Kubectl create secret -f secret1-admin-password.yaml -n webapps
**Now Resource already exists error is thrown due to the orphan resource that still exists.**

This has been explained in the below blog post. Is there any solution to address this scenario?

(https://www.openshift.com/blog/the-hidden-dangers-of-terminating-namespaces)

**Comment by liggitt** [comment]
> Even after fully terminating a namespace by removing finalizer array, seems like there will be orphaned resources.

Removing the finalizer array is what is causing the orphaned resources.
