### ISSUE TITLE
Add --profiling flag to kubelet

### ISSUE THREAD

**Issue by micahhausler** [kubernetes/kubernetes#84165]
**What would you like to be added**:

The control plane components have a `--profiling` flag that controls `/debug/pprof/*` and `/debug/flags/v` being enabled or disabled. Kubelet has both these endpoints, but it doesn't allow them to be independently disabled from all other debugging endpoints that support `kubectl {exec,logs,portforward}`.

**Why is this needed**:

Administrators who don't want to solely rely on RBAC roles for debug endpoints should be able to disable remote profiling and log level setting. 

See Also:
#64601
#63777

/sig node
/kind feature
/area kubelet

**Comment by prithviramesh** [comment]
I'd like to take a stab at this if that's ok with @xiaoanyunfei

**Comment by tallclair** [comment]
/sig auth

Can you elaborate on the justification?
> Administrators who don't want to solely rely on RBAC roles for debug endpoints should be able to disable remote profiling and log level setting.

Why doesn't the administrator want to solely rely on RBAC? Is it because it's hard to block access to someone with cluster-admin privileges? Would a custom authorizer that denied access to this path cover this use case (along with finer-grained authorization, https://github.com/kubernetes/kubernetes/issues/83465)? Or is this more of a defense-in-depth thing, where it's preferable to just cut out the attack surface completely?

**Comment by micahhausler** [comment]
Yes, this is about defense-in-depth, particularly in our case (Fargate) where the customer doesn't manage the kubelet or compute.

**Comment by tallclair** [comment]
OK, that makes sense. I'm convinced this (and https://github.com/kubernetes/kubernetes/issues/87252) would be useful.

**Comment by enj** [comment]
> Yes, this is about defense-in-depth, particularly in our case (Fargate) where the customer doesn't manage the kubelet or compute.

@micahhausler In this case (and #87252), why do you not just prevent these via a deny authorizer in front of RBAC?

**Comment by tallclair** [comment]
After sig-auth discussion, decided to defer to sig-node on this one.
/remove-sig auth

**Comment by SaranBalaji90** [comment]
@micahhausler instead of single `profiling` flag to control both `/debug/pprof/*` and `/debug/flags/v` should we have separate flags for eg `enableProfiling` and `enableDebuggingFlags`

**Comment by SergeyKanzhelev** [comment]
/remove-lifecycle rotten

since it was discussed today at SIG Node

**Comment by dchen1107** [comment]
@SaranBalaji90 Sorry for not capturing your question / request in detail earlier at SIG Node. Could you please elaborate a little bit more here or follow up through slack? Thanks!

**Comment by SaranBalaji90** [comment]
np @dchen1107 thanks for following up. In the issue description we state that adding flag like `enableProfiling` to configure both `/debug/pprof/*` and `/debug/flags/v`.

But I was wondering if we have to block these endpoints, should we have separate flags for these endpoints. For eg `enableProfiling` for `/debug/pprof/*` and `enableDebuggingFlags` for `/debug/flags/v`.

So that  enableProfiling` doesn't control logging configuration flag `/debug/flags/v`

**Comment by dchen1107** [comment]
@SaranBalaji90 Thanks for the updates. Like what we discussed and agreed at previous SIG Node, introducing a separate flag to enable profiling is reasonable. 

To answer your above question on another separate flag to configure /debug/flags/v, I personally prefer to separate them for the cleanness. I don't have a strong opinion on this particular one. @derekwaynecarr

**Comment by derekwaynecarr** [comment]
@SaranBalaji90 +1 to a dedicated flags for each variant of profiling.
