### ISSUE TITLE
client-go: fake.Clientset doesn't support streaming logs

### ISSUE THREAD

**Issue by poy** [kubernetes/kubernetes#84203]
**What happened**:
I tried to use [`FakePods.GetLogs()`](https://godoc.org/k8s.io/client-go/kubernetes/typed/core/v1/fake#FakePods.GetLogs) in a unit test, however I get a nil pointer panic when `.Stream()` is invoked.

**What you expected to happen**:
`FakePods.GetLogs()` would return a `restclient.Request{}` that doesn't panic on any method call. Ideally, it would allow me to interact with the client in someway for testing.

**How to reproduce it (as minimally and precisely as possible)**:
```go
package main

import (
	v1 "k8s.io/api/core/v1"
	"k8s.io/client-go/kubernetes/fake"
)

func main() {
	cs := fake.NewSimpleClientset()
	req := cs.
		CoreV1().
		Pods("default").
		GetLogs("pod-name", &v1.PodLogOptions{})

	// Panics
	req.Stream()
}
```
**Anything else we need to know?**:

client-go version: https://github.com/kubernetes/client-go/commit/78295b709ec6

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by jjshanks** [comment]
I believe this also impacts returning logs via a reactor as `restclient.Request{}` does not implement `runtime.Object`

**Comment by shimmy568** [comment]
Seems to be a problem with [this](https://github.com/shimmy568/kubernetes/blob/82600c2b0e1f0ff1f007479eaf874560bcf81244/staging/src/k8s.io/client-go/kubernetes/typed/core/v1/fake/fake_pod_expansion.go#L57). Since we're creating the request with all empty fields. Not sure what the best way it to resolve this. The best thing I came up with is to use [a fake rest client](https://github.com/shimmy568/kubernetes/blob/master/staging/src/k8s.io/client-go/rest/fake/fake.go) to return a request with everything set up. But I'm a noob here so that's just a shot in the dark :man_shrugging:

**Comment by harjas27** [comment]
The request returned has a nil `backoff` which is used in the `request.Stream() `
https://github.com/kubernetes/client-go/blob/f099a72e140ab46a70ceb9337c75802c3a2be045/rest/request.go#L751

**Comment by knight42** [comment]
I have filed a PR #91485 trying to fix this issue.
