### ISSUE TITLE
i am crazy，please help me.@ admin

### ISSUE THREAD

**Issue by arraycto** [kubernetes/kubernetes#84653]
env:
vm15
centos7.5
k8s:1.16.2
dashboart:v2.0.0-beta5

Error is now。。。。。

[root@bigdata001 k8s]# kubectl get pods --all-namespaces -o wide
NAMESPACE NAME READY STATUS RESTARTS AGE IP NODE NOMINATED NODE READINESS GATES
default nginx-86c57db685-l847h 1/1 Running 0 36m 172.17.0.3 192.168.186.129 
kube-system calico-kube-controllers-dd597647d-mqwjx 0/1 CrashLoopBackOff 33 151m 192.168.186.129 192.168.186.129 
kube-system kube-flannel-ds-amd64-67tk4 0/1 CrashLoopBackOff 8 19m 192.168.186.130 192.168.186.130 
kube-system kube-flannel-ds-amd64-p24cw 0/1 CrashLoopBackOff 8 18m 192.168.186.129 192.168.186.129 
kubernetes-dashboard dashboard-metrics-scraper-7b64584c5c-dc2zq 0/1 CrashLoopBackOff 6 6m39s 172.17.0.3 192.168.186.130 
kubernetes-dashboard kubernetes-dashboard-6b86b44f87-652pl 0/1 CrashLoopBackOff 5 6m39s 172.17.0.2 192.168.186.130 
[root@bigdata001 k8s]#

log:
[root@bigdata001 k8s]# kubectl describe pod kubernetes-dashboard-6b86b44f87-652pl --namespace=kubernetes-dashboard
Name: kubernetes-dashboard-6b86b44f87-652pl
Namespace: kubernetes-dashboard
Node: 192.168.186.130/192.168.186.130
Start Time: Sat, 02 Nov 2019 00:19:07 +0800
Labels: k8s-app=kubernetes-dashboard
pod-template-hash=6b86b44f87
Annotations: 
Status: Running
IP: 172.17.0.2
IPs:
IP: 172.17.0.2
Controlled By: ReplicaSet/kubernetes-dashboard-6b86b44f87
Containers:
kubernetes-dashboard:
Container ID: docker://57d978298bf2c89ecd8b58fc24fc00ca165295a80435ff353187311af87352ff
Image: kubernetesui/dashboard:v2.0.0-beta5
Image ID: docker-pullable://kubernetesui/dashboard@sha256:ae756074fa3d1b72c39aa98cfc6246c6923e7da3beaf350d80b91167be868871
Port: 8443/TCP
Host Port: 0/TCP
Args:
--auto-generate-certificates
--namespace=kubernetes-dashboard
State: Waiting
Reason: CrashLoopBackOff
Last State: Terminated
Reason: Error
Exit Code: 2
Started: Sat, 02 Nov 2019 00:19:35 +0800
Finished: Sat, 02 Nov 2019 00:19:35 +0800
Ready: False
Restart Count: 1
Liveness: http-get https://:8443/ delay=30s timeout=30s period=10s #success=1 #failure=3
Environment: 
Mounts:
/certs from kubernetes-dashboard-certs (rw)
/tmp from tmp-volume (rw)
Conditions:
Type Status
Initialized True
Ready False
ContainersReady False
PodScheduled True
Volumes:
kubernetes-dashboard-certs:
Type: Secret (a volume populated by a Secret)
SecretName: kubernetes-dashboard-certs
Optional: false
tmp-volume:
Type: EmptyDir (a temporary directory that shares a pod's lifetime)
Medium:
SizeLimit: 
QoS Class: BestEffort
Node-Selectors: beta.kubernetes.io/os=linux
Tolerations: node-role.kubernetes.io/master:NoSchedule
Events:
Type Reason Age From Message

Normal Scheduled default-scheduler Successfully assigned kubernetes-dashboard/kubernetes-dashboard-6b86b44f87-652pl to 192.168.186.130
Normal Pulling 21s (x2 over 31s) kubelet, 192.168.186.130 Pulling image "kubernetesui/dashboard:v2.0.0-beta5"
Normal Pulled 4s (x2 over 21s) kubelet, 192.168.186.130 Successfully pulled image "kubernetesui/dashboard:v2.0.0-beta5"
Normal Created 4s (x2 over 21s) kubelet, 192.168.186.130 Created container kubernetes-dashboard
Normal Started 4s (x2 over 21s) kubelet, 192.168.186.130 Started container kubernetes-dashboard
Warning BackOff 3s (x2 over 4s) kubelet, 192.168.186.130 Back-off restarting failed container
[root@bigdata001 k8s]#

cluser is OK ?
[root@bigdata001 k8s]# kubectl get nodes
NAME STATUS ROLES AGE VERSION
192.168.186.129 Ready 4d7h v1.16.2
192.168.186.130 Ready 4d9h v1.16.2
[root@bigdata001 k8s]#

**Comment by arraycto** [comment]
now. i am is a rookie。the dashborad 2.0.0. is hard 。please watch logs

**Comment by cblecker** [comment]
Please re-post your question to [Stack Overflow](http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases.

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans Stack Overflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search Stack Overflow for answers to similar questions, and also familiarize yourself with:

  * [user documentation](https://kubernetes.io/docs/)
  * [troubleshooting guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/)

Again, thanks for using Kubernetes.

The Kubernetes Team

---
/triage support
/close
