### ISSUE TITLE
Hi! Why am I see it programm in my computer/process?  I never use it.

### ISSUE THREAD

**Issue by Nadya24** [kubernetes/kubernetes#85028]

**Comment by liggitt** [comment]
It's unclear what this issue is asking. 

If you're looking for help, check [Stack Overflow](https://stackoverflow.com/questions/tagged/kubernetes) and the [troubleshooting guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/).

You can also post your question on the [Kubernetes Slack](http://slack.k8s.io/) or the [Discuss Kubernetes](https://discuss.kubernetes.io/) forum.

/close
