### ISSUE TITLE
get.k8s.io / config-default.sh should be more robust

### ISSUE THREAD

**Issue by kprobst** [kubernetes/kubernetes#8514]
Config file issues are very fragile and opaque. E.g. one user added a stray comma when defining the minion scopes.  This led to a 'silent' fail, where the cluster just didn't come up.

**Comment by bgrant0607** [comment]
Which config files?

**Comment by kprobst** [comment]
From Amy: One particular case was with the cluster/gce/config-default.sh file.  The user was trying to add another item to the minion scope lists, and added a stray comma.  This caused the deploy to eventually fail after a long interval, but no information was surfaced as to why.  He spent a long time investigating other things.
[Probably there are lots of similar cases].

I'm guessing that some parsing exception got thrown somewhere, probably causing something to abort, and it would have been useful if that exception trace could have been surfaced back to the user.

**Comment by bgrant0607** [comment]
That's not even a "config file". It's a shell script. Not sure what we can do about that, short of the Big Fix of replacing all the scripts.

**Comment by bgrant0607** [comment]
See also #5472

**Comment by alex-mohr** [comment]
I propose removing this from v1 milestone as I don't think it blocks, and agree with Brian that we don't have good ideas on how to solve absent switching to structured config files and go per #5472.

**Comment by bgrant0607** [comment]
Also `curl -sS https://get.k8s.io | bash` was reported in the friction log.

**Comment by bgrant0607** [comment]
Specific issues include:
If the script fails, it has left resources created that make it impossible to run the script successfully later without manually deleting these resources.
    -- Install script uses us-central-b regardless of default zone specified

We should make it more resilient to errors, and ensure it doesn't leave users in a place where they can't easily re-run the script without having to figure out how to manually delete these resources.

We should reduce the number of unnecessary warnings that are thrown at users:
   -- `curl -sS https://get.k8s.io | bash` prints many warnings that I have nothing to do with particularly: "Lists should be separated by commas"

Should we consider adding an auto-cleanup on failure of the script to remove the partial resource the script started to create? Right now, it's difficult for people to manually go through and find all of the resources the script created because they didn't create them on their own. Suggestion from user:
  -- in case installation fails, give clean up instructions or clean up automatically cluster/kube-down

Another request from users is an estimation of how long this process will take. Can we provide that information either in the documentation or via feedback while script is running?
   -- `curl -sS https://get.k8s.io | bash` says "This will continually check, this might loop forever if there was some error"  --> How long should I wait?

Script found on this help topic: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/gce.md

**Comment by bgrant0607** [comment]
kube-up.sh is deprecated
