### ISSUE TITLE
Should have better information on how to have an external tool consume the pod/container lifecycle event stream

### ISSUE THREAD

**Issue by kprobst** [kubernetes/kubernetes#8527]

**Comment by bgrant0607** [comment]
This is sort of deliberately obscure for now, due to uncertainty about the future of the events API.

**Comment by juliaferraioli** [comment]
@bgrant0607 When is the uncertainty expected to resolve? If it's far out, then deliberate obscurity isn't really a good option for developers, especially if they aren't privy to the reason; it would be better to deprecate instructions after they're no longer needed.

**Comment by bgrant0607** [comment]
Before we discuss solutions, more information about the request would be extremely helpful.

What information specifically do users want, how do they want to process it, and for what purpose / use case?

@vishh @saad-ali @thockin

**Comment by juliaferraioli** [comment]
@kprobst can you elaborate on your issue?

**Comment by vishh** [comment]
Our current model is to consume events via heapster. Heapster currently
exports pod/container lifecycle events to InfluxDB and Google Cloud
Logging.

We need to document the heapster model though.

**Comment by kprobst** [comment]
@amygdala brought up this issue originally. Amy, can you provide more context please?

**Comment by amygdala** [comment]
IIRC, this came from a number of queries on google-containers.  People were trying to figure out how to use the API to e.g. do service config, get cAdvisor statistics, get the status of the cluster, etc.  Maybe there are ~3 sub-issues:
- better publicize how to use kubectl in proxy mode
- improve docs on how to auth against the API (?)
- better docs for some common uses of the api, e.g.:
call  
     `<master-ip>/api/v1beta1/endpoints/<service-name>`
then use that list of IP/Ports to configure HAProxy or Nginx

**Comment by bgrant0607** [comment]
I'm glad we asked, because that's not at all what I thought this was about. We definitely should break this into multiple issues.

Resource metrics: I think we need a tutorial that shows how to determine that there's a resource problem such as OOM (out-of-memory), how to isolate the problem (e.g., which pod/node), how to determine what resources are required, such as by using [Heapster](https://github.com/GoogleCloudPlatform/heapster), and how to update the application specs to make the changes.

HAProxy/Nginx/Vulcan: We should provide plugins for these. We can also document the API better, but plugins would satisfy most users as well as serve as examples.

Auth. with the apiserver: @lavalamp has been working on this recently. We should update the doc:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/accessing-the-cluster.md

**Comment by erictune** [comment]
#9353 will improve docs on auth with apiserver.

**Comment by bgrant0607** [comment]
Heapster doc is in.
