### ISSUE TITLE
Image on container side differs between new-pull image and already-exists image

### ISSUE THREAD

**Issue by fankangbest** [kubernetes/kubernetes#85325]
**What happened**:
When we create a pod with a new pulling image, the container's image looks like: xxxx/xxxx/mysql@sha256:29c23bee9310943cd6bad4d856b37656e0b38a7d3698962f6b628be3f96cc049. However, when we create a pod with image already existing on node, the container's image looks like: sha256:f6c9bc518181fbfadf74033c751a45d569c4729c0ef838310527f31d9124d3a3.

Is this a bug, or just by design?
**What you expected to happen**:
The image should look like the same on container side.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a pod on the node which image is not existed;
2. Check image on container;
3. Create another pod with the same image on the same node;
4. check image on new created container.

**Anything else we need to know?**:

**Environment**:

- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by rvanderboom** [comment]
No idea if our issue is related but we are searching for a strange bug we can not explain.
We have an application running on 3 pods and almost every time when a new release (new image pull) is made, the first pod doesn't start correctly because it compains about missing classes.
The other 2 go ok, and after we restart  (delete te pod) its ok to.
Also when deploying same release we do not have this issue. Also when we run without kubernetes we do not have this issue.  We are unable to figure out the problem :-<
