### ISSUE TITLE
If any pods is stuck in pending state at the time of POD HPA(without node scaling), Scaledown will not work.

### ISSUE THREAD

**Issue by PrakashTrove** [kubernetes/kubernetes#85506]
/sig scalability

**What happened**:
I created one node k8s cluster and deployed a deployment file with two replicas. Then added autoscale to the deployment with min 1 and max 10 pods. Injected the load. Scaled the pods to 10. 8/10 were in running state and 2/10 were the pending state. Stopped the load. Scaledown did not happen. 

Pending PODS(2/10) were expecting another node to be avail Running. and then scale down is happening after the scaledown grace period.

**What you expected to happen**:
Once the load is stopped, the PODs count should be decreased to normal in size after the scaledown period.
The pending PODs need to be removed/scaledown afterload is reduced though the pending pods do not contain any active connections.

**How to reproduce it (as minimally and precisely as possible)**:
Here is the way I tried:
I created a Kubernetes environment using AWS EKS. But I suspect the issue logic needs to be handled in Kubernetes. Below are the steps I tried.
1. Created Kubernetes 1.14 Cluster using one worker node(minions/node).
2. Created and deployed Deployment YAML file with 2 replicas.
`kubectl apply -f deployment.yaml`
4. Created POD AutoScaling(HPA) using below command(POD min=1, max=10)
`kubectl autoscale deployment deploymentname --cpu-percent=20 --min=1 --max=10`
5. Injected load using below commands
```
kubectl run --generator=run-pod/v1 -it --rm load-generator --image=busybox /bin/sh
while true; do wget -q -O- http://application-url; done
```
6. Now increased PODs to 10.
 out of 10 pods, two pods were stuck in the pending state due to non-availability of cluster scaling(Node 1 is occupied 8 pods and two more pods are in the pending state due to cluster scaling not enabled)
7. Stopped the load injected.
8. I did wait more than a scaledown grace period around 30 mins, but PODs are not scaledown(both running and pending pods).

After 1 hour I increased one node in the cluster.
Now the pending PODs are deployed in the new node.
After 5 mins of the grace period, PODs are scale down to a minimum.

My observations:
So If any pods are stuck in pending state while scale-up, Scale down will not work.
Scaledown is expecting all the pods are in running state.

**Anything else we need to know?**:

****Environment**:**
- Kubernetes version (use `kubectl version`):

> Client Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.7-eks-1861c5", GitCommit:"1861c597586f84f1498a9f2151c78d8a6bf47814", GitTreeState:"clean", BuildDate:"2019-09-24T22:12:08Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
> Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.8-eks-b7174d", GitCommit:"b7174db5ee0e30c94a0b9899c20ac980c0850fc8", GitTreeState:"clean", BuildDate:"2019-10-18T17:56:01Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
> 

- Cloud provider or hardware configuration: 

> AWS Cloud

- OS (e.g: `cat /etc/os-release`): 

> NAME="Ubuntu"
> VERSION="18.04.3 LTS (Bionic Beaver)"
> ID=ubuntu
> ID_LIKE=debian
> PRETTY_NAME="Ubuntu 18.04.3 LTS"
> VERSION_ID="18.04"
> HOME_URL="https://www.ubuntu.com/"
> SUPPORT_URL="https://help.ubuntu.com/"
> BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
> PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
> VERSION_CODENAME=bionic
> UBUNTU_CODENAME=bionic
> 

- Kernel (e.g. `uname -a`): 

> Linux 33dna1 4.15.0-46-generic #49-Ubuntu SMP Wed Feb 6 09:33:07 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

- Install tools: metric-server
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by alejandrox1** [comment]
quick pass through
/remove-sig scalability
/sig autoscaling

**Comment by max-rocket-internet** [comment]
What `Events` and `Conditions` are present for your HPA when this happens?

**Comment by jackfrancis** [comment]
I'm able to repro this in regular E2E tests that we do, but only for k8s versions < 1.16. Our repro scenario looks like this:

- we attach HPA configuration to a web listener
- add enough load so that HPA scales up beyond the max pod per node settings, creating a bunch of Pending pods
- validate that cluster-autoscaler scales up
- remove load
- validate that HPA pod count back down to one
- validate that cluster-autoscaler scales down

What happened is our E2E config evolved such that we're creating more pods than our cluster-autoscaler max node count can accommodate, so we never create enough nodes in our tests to schedule all HPA-scaled-up pods. And what we noticed is that HPA in fact doesn't scale back down, ostensibly due to the fact that there are pods in the HPA-attached deployment that are Pending (that's the only symptomatic change that I've observed, anyways).

And this *doesn't* repro on 1.14 or 1.15, so that's interesting. Potentially this was fixed, in which case we should identify how, and possibly close this issue, but mention that it won't be fixed in versions of Kubernetes that are no longer accepting cherry-picks/patch releases (e.g., 1.14).
