### ISSUE TITLE
Duplicated pods exist in SnapShot#nodeInfo

### ISSUE THREAD

**Issue by cwdsuzhou** [kubernetes/kubernetes#85563]
**What happened**:

When we extend the default scheduler by scheduling framework , we found duplicated pods exist in the snapshot nodeInfo.

Here are the logs our scheduler printed.
![image](https://user-images.githubusercontent.com/12230714/69473029-8d29ef00-0dec-11ea-85ec-70712c48a96e.png)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

create a pod
delete the pod 
re-create the pod 

duplicated pods may exist in the snapshot

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.16.0
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by cwdsuzhou** [comment]
See https://github.com/kubernetes/kubernetes/pull/21016#discussion_r52728635

Assumed pods would not be removed when pods have deleted immediately.
Normally, it would not influence the scheduling progress.However since Framework  Handler provides GetShapshot() func, users may use snapShot to implement their own scheduler. e.g. we implemented  gang-scheduling which relies on the snapshot.

I have sent a PR to fix it.

**Comment by ahg-g** [comment]
Just to clarify, those are not duplicate pods, they are two different pods (pods with different UID) with the same name.

When an assumed pod is deleted, the scheduler does not seem to remove it immediately from the cache, rather it just waits until the pod expires (maximum 30 second). The history behind this behavior is not clear to me.

**Comment by ahg-g** [comment]
Copying a comment I made on the PR:


I think we have the following cases:

1) If the binding succeeded before the pod got deleted, then the pod will have NodeName set (i.e., the pod is assigned), and the scheduler will then get an add then a delete event that will be handled by the [delete event handler](https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/eventhandlers.go#L362), which will remove the pod from the cache.

2) If for some reason the scheduler didn't receive the add and delete events in the right order, then it seems that the pod will not be removed from the scheduler cache immediately, but it will eventually expire and get removed at most after 30 sec after the binding finished.

3) If the pod got deleted before the binding is finished, then the binding should fail and the scheduler will call [ForgetPod](https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/scheduler.go#L575), which will remove the pod from the cache.



Remember that the system by design is eventually consistent, and plugins should be designed with that in mind, so I don't see that this is something we necessarily need to address.

**Comment by cwdsuzhou** [comment]
Seems the issue I met does match the cases you mentioned.

From the codes, if the pod is deleted before binding is finished, but pod is assumed.
Then a delete event comes, scheduler will not call` ForgetPod`, it will call https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/eventhandlers.go#L386, because the pod has not been scheduled, then the pod would not be removed from the cache, so the pod exists in the cache util expires.

**Comment by ahg-g** [comment]
ForgetPod will be called [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/scheduler.go#L575) if the binding failed, and this will happen if the delete on the apiserver was performed before the bind was successful.

I think the case you are hitting is that the binding was successful, but the delete happened right after, and the scheduler received a delete event before an add event (i.e., case #2 above).

If that is indeed the case, then we could call ForgetPod in RemovePod if the pod is assumed.

**Comment by ahg-g** [comment]
@cwdsuzhou do you have a test that reproduces this case consistently?

**Comment by cwdsuzhou** [comment]
> ForgetPod will be called [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/scheduler.go#L575) if the binding failed, and this will happen if the delete on the apiserver was performed before the bind was successful.
> 
> I think the case you are hitting is that the binding was successful, but the delete happened right after, and the scheduler received a delete event before an add event (i.e., [case 2](https://github.com/kubernetes/kubernetes/issues/85563#issuecomment-559222479) above).
> 
> If that is indeed the case, then we could call ForgetPod in RemovePod if the pod is assumed.

We are developing a gang-scheduler, so we would not permit the pods util descried number of pods reached, then the pods can not be bound. When we delete the pods , a delete event would receive, but due to not assign(binding), we would not call `ForgetPod`.

So I think do not match `case 2` you mentioned.

If some of the pods are waiting. Then we delete them and re-create them, the case I mentioned may happen.

**Comment by ahg-g** [comment]
so you are issuing a delete while the pod is waiting on permit? if so, who is doing that? the plugin you are developing? shouldn't you reject the pod first?

**Comment by cwdsuzhou** [comment]
Thanks. 

Our plugin is based on 1.16.
However, I find in the latest version, when a pod is deleted, pod would be rejected since this PR https://github.com/kubernetes/kubernetes/pull/84578 merged.
So, the issue may have fixed.
