### ISSUE TITLE
Report Pod mounting the PVC as part of equivalent of "describe PVC" output in K8S Python API

### ISSUE THREAD

**Issue by ps10** [kubernetes/kubernetes#85630]
Hi,

I would like to query the PVC for which Pod is mounting it. I can see that the "describe pvc" output has this, where the "Mounted By: " prints the Pod that is mounting it. But on using read_namespaced_persistent_volume_claim which returns the PVC Object, I don't get it as part of the object.

Are there plans to have, or any current implementation that has, the V1PersistentVolumeClaim have a member that says which Pod has mounted it.

Any pointers on this would of great help.

There is a related discussion in https://github.com/kubernetes/kubernetes/pull/65837 in which the solution was provided at the CLI Level.

Regards

**Comment by piroszhog** [comment]
+1, need this too. For now I have to run kubectl as a subprocess.

**Comment by piroszhog** [comment]
I did a small study, and it seems it's impossible for now to add the same feature to client, since there is no API method to get "mounted by" pods list. 
Kubectl just gets all pods list from `/pods` and iterates them to form "mounted by" list. Not the best way as for me, I think it should be in API.
