### ISSUE TITLE
Move "validates MaxPods limit number of pods that are allowed to run" e2e test to an integration test

### ISSUE THREAD

**Issue by ahg-g** [kubernetes/kubernetes#85900]
[validates MaxPods limit number of pods that are allowed to run [Slow]](https://github.com/kubernetes/kubernetes/blob/c8b123e8e1be6406bace4fe59d5284e1ce6a43a1/test/e2e/scheduling/predicates.go#L118) e2e test fails frequently and should be moved to be an integration test.

This test relies on a particular state of the cluster before the test start that is hard to validate. It should be more than enough to have an integration test for this.

/sig scheduling

**Comment by kitianFresh** [comment]
i can have a try
/remove help
/remove good-first-issue

**Comment by alejandrox1** [comment]
Added the milestone as per questions from the release team: this issue is showing up in testgrid dashboards that potentially block the release of 1.17 which is planned for next week.

Although looking closer it seems like this e2e test failing is not a big deal and it failing does not meant that there is something wrong with 1.17.
Is this correct @ahg-g ?

**Comment by ahg-g** [comment]
yes, this is about the test setup, there is nothing wrong with 1.17. You can remove it from the milestone.

**Comment by alejandrox1** [comment]
Thank you for the info
/remove-milestone
