### ISSUE TITLE
StatefulSet  pod support not reschedule when node reboot

### ISSUE THREAD

**Issue by pytimer** [kubernetes/kubernetes#86196]
I use statefulset create 3 replicas pod on three nodes, when i power off node-2, pod status become `NodeLost` -> `Unknown`, when i power on node-2, i found this pod reschedule and recreate, but i want this pod still running node-2, how can i do?

**Comment by sftim** [comment]
Similar to #86069

**Comment by pytimer** [comment]
@sftim Thanks for you reply.

I found if the node lost 20min, pod will reschedule when node power on. If i want to pod not reschedule or extension reschedule time when node reboot , did i have some ways to do it?

**Comment by sftim** [comment]
I think the scheduler and StatefulSet controller are working as designed. My take on this: someone could (extend Kubernetes)[https://kubernetes.io/docs/concepts/extend-kubernetes/extend-cluster/#user-defined-types) with a new type (not called StatefulSet) that has behavior between DaemonSet and StatefulSet, so that when a Pod fails the controller tries hard to schedule its replacement Pod onto the same Node.

Until someone does that work, though, people who want enumable Pods to stay placed on Nodes might not get the behavior they want.

**Comment by sftim** [comment]
(maybe there already is such a resource and I don't know about it).

**Comment by sftim** [comment]
@pytimer see https://kubernetes.io/blog/2018/04/13/local-persistent-volumes-beta/

/triage support

**Comment by pytimer** [comment]
@sftim Sorry to reply late.

local persistent volume i try, it can solved my question, but if i use this feature, i must be do a lot of things, such as create the local pv on the node before pod running... I found a repository https://github.com/openkruise/kruise/blob/master/docs/concepts/astatefulset/README.md , it maybe can solve my question, i will try it. 

Thanks.
