### ISSUE TITLE
Why pod with Terminating status is considered as Ready? 

### ISSUE THREAD

**Issue by yuyulei** [kubernetes/kubernetes#86209]
**What would you like to be added**:

A confusion that why the pod with terminating status(in graceful shutdown duration) can be looked as ready pod. 

**Why is this needed**:

In Statefulset controller, count ready replicas by using function [isRunningAndReady](https://github.com/kubernetes/kubernetes/blob/9caece8bd9fab55c3300b4a4373c49afcc5f13f8/pkg/controller/statefulset/stateful_set_control.go#L293), no checking if pod is Terminating.

I  just feel confused.

**Comment by ilirosmanaj** [comment]
I am also experiencing the case when a pod in terminating state is receiving incoming requests. Should the terminationGracePeriodSeconds be used to only finish the ongoing tasks and no longer receive other?

**Comment by yanchenko-igor** [comment]
I have an issue when due to unreachable node a pod becomes "Terminating". If I have a statefulset with one replica, it causes a downtime for the service, the expected behavior would be that a pod in Terminating state would not be counted, and new pod would be created. I there a way to implement this? 

/remove-lifecycle stale
