### ISSUE TITLE
Replace gomega.Expect(bool).To(gomega.BeTrue(),...) with framework.ExpectEqual()

### ISSUE THREAD

**Issue by tanjunchen** [kubernetes/kubernetes#86206]
@ixdy   open  this [destroy the "Expect(err).NotTo(HaveOccurred())" anti-pattern in e2e tests](https://github.com/kubernetes/kubernetes/issues/34059) issue about  
``` Expect(err).NotTo(HaveOccurred()) problems ```   

I get this point : 

The begin solutions are :  

```
Expect(err).ToNot(HaveOccurred()) -> Expect(err).ToNot(HaveOccurred(), "some explain")
```  
such as https://github.com/kubernetes/kubernetes/pull/34295 , https://github.com/kubernetes/kubernetes/pull/69583 , https://github.com/kubernetes/kubernetes/pull/72440/
 
Then the solution : 
``` 
Expect(err).NotTo(HaveOccurred(), "some explain")  -> framework.ExpectNoError(err, "some explain") 
```
such as https://github.com/kubernetes/kubernetes/pull/74113/ , https://github.com/kubernetes/kubernetes/pull/77693/

current functions in  test/e2e/framework/expect.go  
see https://github.com/kubernetes/kubernetes/blob/master/test/e2e/framework/expect.go

oomichi open a pr [Add ExpectEqual() to e2e framework](https://github.com/kubernetes/kubernetes/pull/78922) ,  
he opens a helpful and meaningful issue[Use framework.ExpectEqual() for e2e tests] (https://github.com/kubernetes/kubernetes/issues/79686) , thanks .
	
After all the code refactoring is completed in /test, 
the corresponding detection scripts , for example [78485](https://github.com/kubernetes/kubernetes/pull/78485/) , 
are added under the hack/verify-test-code.sh (see https://github.com/kubernetes/kubernetes/blob/master/hack/verify-test-code.sh)  to detect the code that matches 
the ```Expect(.*)\.To(.*HaveOccurred()```  and  ``` Expect\(.*\)\.To\((gomega\.Equal|Equal) ``` , 
and it is suggested that you use framework.ExpectNoError () or framework.ExpectEqual ()

we can replace ```gomega.Expect(foo).To(gomega.Equal(bar))``` code with ```framework.ExpectEqual(foo, bar)``` which is more readable and easy to be understood what the code does.

There is a check script in the hack/verify-test-code.sh.

```
gomega.Expect(bool).To(gomega.BeTrue(), "some explain")
gomega.Expect(bool).To(gomega.BeFalse(), "some explain")
```
Therefore , I think it is possible to perform the same operation on
bool values conforming that we use framework.Equal(bool,true|false,...) for above . 

So I open this  issue to confirm whether we can do this and 
recommend developers to use this framework.Equal ()  
I hope everyone can express their opinions, thank you.

/sig testing

TLTR
ref:https://github.com/kubernetes/kubernetes/pull/86157

**Comment by tanjunchen** [comment]
ping @oomichi  @alejandrox1  @neolit123

**Comment by neolit123** [comment]
thanks for opening the issue @tanjunchen 

we already commented on https://github.com/kubernetes/kubernetes/pull/86157 that this enforcement might not be desired.

but looking for feedback from @oomichi and @alejandrox1 too.

**Comment by oomichi** [comment]
I might be a little confused..
There is already a code check to use `framework.ExpectEqual()` in `./hack/verify-test-code.sh`.
This issue is for proposing to use `framework.ExpectEqual(foo, true)` / `framework.ExpectEqual(foo, false)` only for boolean cases?

At this time, there are not so many lines which call the above patterns.
I don't have strong opinion to implement the rule or not.
(When I created the existing rule, there were a lot of e2e test PRs which add inconsistent usage of `gomega` and `framework`.  Then the rule has made the test implementation consistent)

```
$ grep gomega.BeTrue * -R | grep gomega.Expect | wc
     14     155    1990
$ grep gomega.BeFalse * -R | grep gomega.Expect | wc
      2      11     227
```

**Comment by alejandrox1** [comment]
For context, the big issue in https://github.com/kubernetes/kubernetes/issues/34059 was indeed about adding annotations to anything that looked like a `gomega.Expect(...).To(...)`.
The use of e2e framework functions such as `framework.Ecpect(...)`.

https://github.com/kubernetes/kubernetes/blob/master/hack/verify-test-code.sh (the CI script that prevents the use of `gomega.Expect(err).To(HaveOccurred())` and the like was added in https://github.com/kubernetes/kubernetes/pull/77612 in order to resolve https://github.com/kubernetes/kubernetes/issues/77103.

And there have been many PRs that go and modify the use of gome.Expects for framework.Expects, i.e., https://github.com/kubernetes/kubernetes/pull/77693.

https://github.com/kubernetes/kubernetes/issues/77103 itself doesn't have any reference to a reason why `framework.Expect*` are favored over direct gomega use.
However, there have been many conversation such as https://github.com/kubernetes/kubernetes/pull/86157#issuecomment-564523376
which land in
> ... we shouldn't force test developers to use the framework version.

---

* I think this would be a good time and place to rethink this all...
If we don't want to force people to use frmaework wrappers for ginkgo, should we keep CI blocking checks such as https://github.com/kubernetes/kubernetes/blob/master/hack/verify-test-code.sh
* If we only want to enforce the use of certain framework wrappers, which ones should it be? why? and where do we document the decision? 

/retitle Replace gomega.Expect(bool).To(gomega.BeTrue(),...) with framework.ExpectEqual()
/priority important-longterm

**Comment by spiffxp** [comment]
I agree with @alejandrox1 above.  It's time to rethink all of this.

The original intent of #34059 was that there was no explanation provided alongside these checks.  Why was _this particular error_ not expected? etc. This specific anti-pattern was difficult to debug and triage from logs alone.

It's not clear to me how or why we got from there to what appears to either be:
- move toward "must only use `framework.Expect` wrappers"
- "must use these arbitrary `framework.Expect` wrappers"

None of these wrappers _force_ an explain parameter, so they don't really solve the anti-pattern.  I have seen no consensus for why we need to churn our test code with `framework.Expect` wrapper changes, and I've seen push back.

I think the following managed to make it through, and we should document them, but we should go no further without a proposal and consensus.
- framework.Expect(No)Error
- framework.Expect(Not)Equal

**Comment by BenTheElder** [comment]
+1 @spiffxp 
I'm inclined to close this in favor of a new issue when a proposal is agreed upon that is more productive than this mechanical substitution
/close
