### ISSUE TITLE
PSP MustRunAs minimum without pod spec mutation

### ISSUE THREAD

**Issue by mariusgrigoriu** [kubernetes/kubernetes#86220]
**What would you like to be added**:
I'd like to propose that the pod security policy not mutate the pod spec by inserting the `MustRunAs` minimum UID if it is not specified. Instead it could use UID of the container image and verify that the container UID conforms to the policy just like how `MustRunAsNonRoot` does it.

**Why is this needed**:
If a user does not set the UID in the pod spec, kubernetes assumes the pod needs to run as the minimum UID, which may not be the same UID the image was designed to run as. This forces users to set a security context with their UID in the pod spec. It's an extra step for users to take when a minimum UID is specified, which seems unnecessary.

**Comment by liggitt** [comment]
changing the meaning of MustRunAs would be a breaking change (since it would change admitted pods that currently have the minimum uid in the range set, potentially breaking access to existing persisted volume data)

**Comment by liggitt** [comment]
/close 

since this is not a backwards compatible change, and continued additions to PodSecurityPolicy are not currently planned

**Comment by TBBle** [comment]
It'd be great if this was documented more clearly. I was just about to open the same thing as a bug report, having just found that a pod that *should* have been rejected was being accepted with a different UID than it was built with, due to using `MustRunAs[1-65535]` instead of `RunAsNonRoot`.

It's definitely not clear from the [docs](https://kubernetes.io/docs/concepts/policy/pod-security-policy/#users-and-groups) that `MustRunAs` will not process the `USER` directive, when `RunAsNonRoot` does, and hence will change the UID on already-conforming container images.

In my particular case, the surprise came in the large behaviour difference between
```yaml
spec: 
  runAsUser:
    ranges:
    - max: 65535
      min: 1
    rule: MustRunAs
```

and

```yaml
spec: 
  runAsUser:
    rule: MustRunAsNonRoot
```
