### ISSUE TITLE
hpa get cpu utilization from deleted pod

### ISSUE THREAD

**Issue by zjj2wry** [kubernetes/kubernetes#86297]
**What happened**:
```bash
wlx-prd              33m         Warning   FailedComputeMetricsReplicas   HorizontalPodAutoscaler   horizontal-pod-autoscaler            failed to get cpu utilization: did not receive metrics for any ready pods                                                                                                                 63d          30      epnu-dataquality.15cd6629a893ce13
$ kubectl get po epnu-dataquality.15cd6629a893ce13 -n wlx-prd
Error from server (NotFound): pods "epnu-dataquality.15cd6629a893ce13" not found
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.6-aliyun.1", GitCommit:"4304b26", GitTreeState:"", BuildDate:"2019-04-08T08:50:29Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.6-aliyun.1", GitCommit:"8cb561c", GitTreeState:"", BuildDate:"2019-04-22T11:34:20Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by wy100101** [comment]
I'm running into this and it basically makes the HPA unusable for me because CPU spikes up during graceful termination due to cleanup activities for our app.

I've looked at the code as far I can understand the workings of things like kubernetes delete operations and it looks like a deleted pod should get skipped since DeletionTimestamp should be set before the TERM signal is set so the pods should be skipped by replica_calculator#GroupPods()

Is there a race condition or a bug in the code?

**Comment by wy100101** [comment]
Is the issue that the HPA is using a caching lister to get the pods? Maybe the calculation is based on a cached view of the pod.

**Comment by wy100101** [comment]
I think this is still an issue.
