### ISSUE TITLE
Scheduler throughput regression

### ISSUE THREAD

**Issue by mm4tt** [kubernetes/kubernetes#86302]
Looks like the scheduler throughput regressed over the weekend. Both gce/kubemark tests at scale of 100 and 5K nodes are failing because of that.

GCE 5K perf dash - http://perf-dash.k8s.io/#/?jobname=gce-5000Nodes&metriccategoryname=Scheduler&metricname=SchedulingThroughput

/sig scalability
/sig scheduler

**Comment by mm4tt** [comment]
/sig scheduling

/assign @ahg-g 
@ahg-g, could you take a look?

BTW, it was detected based on an alert for scheduler throughput that we discussed during the last regressions and which I set up recently. The investment is already paying off :)

**Comment by mm4tt** [comment]
Perf-tests presubmits are also affected, e.g. https://github.com/kubernetes/perf-tests/pull/891

**Comment by jkaniuk** [comment]
It was triggered by https://github.com/kubernetes/kubernetes/pull/86224
which adds logging:
https://github.com/kubernetes/kubernetes/pull/86224/commits/c54dbd85e00d1739ac925370b02aab1bce54ce58#diff-c4a6434e8b170fc499461028d284c57bR82
```
E1214 00:49:18.400341       1 node_ports.go:82] not found
E1214 00:49:18.400352       1 node_ports.go:82] not found
E1214 00:49:18.400373       1 node_ports.go:82] not found
```

Run before merge:
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/1205638860017504259

kub-scheduler.log: 100kB, 8k lines

Run after merge:
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/1205648925915090944

kub-scheduler.log: 4.4MB, 720k lines

/assign

**Comment by ahg-g** [comment]
Thanks, we are aware of it, this should solve it: https://github.com/kubernetes/kubernetes/pull/86284

**Comment by ahg-g** [comment]
We will also move the Error log to a V(4) in case CA in the future call Filters without PreFilters.

**Comment by jkaniuk** [comment]
Based on the first run, limiting logging did not help:
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/1206619573504184323
`[measurement call SchedulingThroughput - SchedulingThroughput error: scheduler throughput: actual throughput 89.800000 lower than threshold 90.0000`
/reopen

**Comment by jkaniuk** [comment]
kube-scheduler.log (https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/1206619573504184323)
```

I1216 17:22:49.363327       1 trace.go:116] Trace[1343227737]: "Scheduling" namespace:test-5bif4x-1,name:small-deployment-292-778c64cf8c-c9j5w (started: 2019-12-16 17:22:49.208621601 +0000 UTC m=+1085.779912810) (total time: 154.610311ms):
Trace[1343227737]: [154.606954ms] [153.353881ms] Prioritizing done
I1216 17:22:49.618694       1 trace.go:116] Trace[325819948]: "Scheduling" namespace:test-5bif4x-1,name:small-deployment-172-678bbbf868-g9fmp (started: 2019-12-16 17:22:49.501861223 +0000 UTC m=+1086.073152383) (total time: 116.75238ms):
Trace[325819948]: [116.74944ms] [115.103358ms] Prioritizing done
[...]
I1216 17:22:52.046500       1 trace.go:116] Trace[540276767]: "Scheduling" namespace:test-5bif4x-1,name:small-deployment-120-55f55f9b75-hl278 (started: 2019-12-16 17:22:51.940948051 +0000 UTC m=+1088.512239216) (total time: 105.35662ms):
Trace[540276767]: [25.651117ms] [25.417062ms] Computing predicates done
Trace[540276767]: [105.351522ms] [79.695121ms] Prioritizing done
[...]
I1216 17:22:55.631877       1 trace.go:116] Trace[1814950274]: "Scheduling" namespace:test-5bif4x-1,name:small-deployment-282-5b447855d6-d8qz5 (started: 2019-12-16 17:22:55.477874407 +0000 UTC m=+1092.049165571) (total time: 153.919799ms):
Trace[1814950274]: [16.384479ms] [16.333171ms] Computing predicates done
Trace[1814950274]: [153.917138ms] [137.529725ms] Prioritizing done
[...]
I1216 17:22:56.466993       1 trace.go:116] Trace[1874340739]: "Scheduling" namespace:test-5bif4x-1,name:small-deployment-220-6cddf9b8c7-2flxc (started: 2019-12-16 17:22:56.346567115 +0000 UTC m=+1092.917858273) (total time: 120.208844ms):
Trace[1874340739]: [120.207539ms] [119.099018ms] Prioritizing done
```

**Comment by ahg-g** [comment]
#86284 hopefully will fix it.

**Comment by jkaniuk** [comment]
Actually, reducing logging helped significantly:
https://k8s-testgrid.appspot.com/sig-scalability-gce#gce-cos-master-scalability-100

out of 23 runs since merge, only two were below the threshold::
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/1206619573504184323
`[measurement call SchedulingThroughput - SchedulingThroughput error: scheduler throughput: actual throughput 89.800000 lower than threshold 90.000000]`
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/1206855166494511106
`[measurement call SchedulingThroughput - SchedulingThroughput error: scheduler throughput: actual throughput 78.000000 lower than threshold 90.000000]`

I have found also an older flake, before regression was introduced:
12/11/2019 - https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/1204859707991265282
`[measurement call SchedulingThroughput - SchedulingThroughput error: scheduler throughput: actual throughput 78.200000 lower than threshold 90.000000]`

As well as two recent on 1.16 branch:
12/14/2019 - https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability-stable1/1205820052486492160
`measurement call SchedulingThroughput - SchedulingThroughput error: scheduler throughput: actual throughput 80.400000 lower than threshold 90.000000`
12/16/2019 - https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability-stable1/1206363632812691459
`[measurement call SchedulingThroughput - SchedulingThroughput error: scheduler throughput: actual throughput 86.800000 lower than threshold 90.000000]`

Other branches (1.14, 1.15, 1.17) seems relatively fine, however perf-dash history show pretty chaotic results.

Filed #86345

**Comment by ahg-g** [comment]
Reducing logging does help for sure, the logging you saw wasn't intentional, it was a result of missing PreFilter plugins.

**Comment by jkaniuk** [comment]
Yes, I understand.
Fingers crossed for retest ;)
