### ISSUE TITLE
[Flaky test] [sig-apps] Job should run a job to completion when tasks sometimes fail and are not locally restarted

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#86333]
**Which jobs are flaking**:
pull-kubernetes-e2e-kind

**Which test(s) are flaking**:
* `[sig-apps] Job should run a job to completion when tasks sometimes fail and are not locally restarted`

**Testgrid link**:
https://testgrid.k8s.io/presubmits-kubernetes-nonblocking#pull-kubernetes-e2e-kind&include-filter-by-regex=Job.*completion

**Reason for failure**:

**Anything else we need to know**:
https://storage.googleapis.com/k8s-gubernator/triage/index.html?pr=1&test=Job%20should%20run%20a%20job%20to%20completion%20when%20tasks%20sometimes%20fail%20and%20are%20not%20locally%20restarted

/sig apps

**Comment by liggitt** [comment]
Failure at https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/84735/pull-kubernetes-e2e-kind/1206768560399978496

**Comment by tnqn** [comment]
Hi @liggitt,  I looked into the failures and think it was because the test required the job succeeds 3 times with pseudorandom 50% failure chance within 15 minutes, while there is an exponential back-off delay (10s, 20s, 40s …) capped at 6 minutes before recreating failed pods.
As 7 consecutive failures (1/128 chance) could exceed the timeout, the test failed intermittently because of "timed out waiting for the condition".

For example, in the failure of https://github.com/kubernetes/kubernetes/issues/86333#issuecomment-566383109, the job pods succeeded and failed in the following orders:
```
03:01:44 failed
03:01:44 failed
03:01:51 failed
03:02:01 failed
03:02:21 succeeded
03:02:21 succeeded
03:02:32 failed
03:02:42 failed
03:02:52 failed
03:03:12 failed
03:04:32 failed
03:07:12 failed
03:12:32 failed
```
After the last failure at `03:12:32`, the delay has increased to 640s so no pod was created any more before the test failed at `03:16:44`.
```
Dec 17 03:16:44.680: FAIL: failed to ensure job completion in namespace: job-1607
Unexpected error:
    <*errors.errorString | 0xc0000a1860>: {
        s: "timed out waiting for the condition",
    }
    timed out waiting for the condition
occurred
```

I think it can be fixed by using a deterministic approach to make the job pods succeed and fail alternately, and its executing time can be reduced to tens of seconds stably.

Assigning myself.
/assign
