### ISSUE TITLE
[Flaky test] [sig-api-machinery] CustomResourcePublishOpenAPI flakes

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#86418]
**Which jobs are flaking**:
pull-kubernetes-e2e-gce

**Which test(s) are flaking**:

- [sig-api-machinery] CustomResourcePublishOpenAPI [Privileged:ClusterAdmin] updates the published spec when one version gets renamed [Conformance]
- [sig-api-machinery] CustomResourcePublishOpenAPI [Privileged:ClusterAdmin] works for CRD without validation schema [Conformance]
- [sig-api-machinery] CustomResourcePublishOpenAPI [Privileged:ClusterAdmin] works for multiple CRDs of same group but different versions [Conformance]
- [sig-api-machinery] CustomResourcePublishOpenAPI [Privileged:ClusterAdmin] works for multiple CRDs of same group and version but different kinds [Conformance]
- [sig-api-machinery] CustomResourcePublishOpenAPI [Privileged:ClusterAdmin] works for CRD preserving unknown fields at the schema root [Conformance]
- [sig-api-machinery] CustomResourcePublishOpenAPI [Privileged:ClusterAdmin] works for multiple CRDs of different groups [Conformance]
- [sig-api-machinery] CustomResourcePublishOpenAPI [Privileged:ClusterAdmin] works for CRD preserving unknown fields in an embedded object [Conformance]
- [sig-api-machinery] CustomResourcePublishOpenAPI [Privileged:ClusterAdmin] works for CRD with validation schema [Conformance]
- [sig-api-machinery] CustomResourcePublishOpenAPI [Privileged:ClusterAdmin] removes definition from spec when one version gets changed to not be served [Conformance]

**Testgrid link**:
https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-e2e-gce&include-filter-by-regex=api-machinery&width=5&sort-by-flakiness=200

**Reason for failure**:
All the failures seem to be timeouts waiting for openapi publishing changes to take effect

/assign @roycaihw @sttts

**Comment by liggitt** [comment]
@kubernetes/sig-api-machinery-bugs 
/priority important-soon

**Comment by liggitt** [comment]
four of the top ten flakes according to http://storage.googleapis.com/k8s-metrics/flakes-latest.json

**Comment by roycaihw** [comment]
These tests fail because a CRD spec change isn't reflected in the openapi spec [within 30s](https://github.com/kubernetes/kubernetes/blob/11a31590e432ba9c723b951e1691d5a97c09dba7/test/e2e/apimachinery/crd_publish_openapi.go#L604). I added logging and there were two issues:

1. sometimes the test has to download three different openapi specs before it sees the change (in this previous [analysis](https://github.com/kubernetes/enhancements/pull/1015#discussion_r305535251) I only considered server side, but in this case the test itself is a client and adds one extra race). See the following worst case analysis:
![Untitled drawing](https://user-images.githubusercontent.com/6629765/71914369-5571cf00-312e-11ea-8c5e-0cd6272e281b.png)
2. the [mustSucceedMultipleTimes](https://github.com/kubernetes/kubernetes/blob/11a31590e432ba9c723b951e1691d5a97c09dba7/test/e2e/apimachinery/crd_publish_openapi.go#L544) function ensures we see 10 successive specs with an expected change. Ideally as long as we see the first success, the remaining 9 checks should be trivial given the etag. However sometimes the etag was changed (likely caused by unrelated tests running in parallel) and caused one more downloading. E.g.

```
I0107 03:49:52.098] E0107 03:48:25.485130   11817 crd_publish_openapi.go:645] ----- succeeded
I0107 03:49:52.098] E0107 03:48:25.485143   11817 crd_publish_openapi.go:612] ----- checking
I0107 03:49:52.098] E0107 03:48:27.568637   11817 crd_publish_openapi.go:637] ----- spec changed
I0107 03:49:52.099] E0107 03:48:27.568869   11817 crd_publish_openapi.go:645] ----- succeeded
```

Downloading and deserializing openapi spec is expensive. Depending on the traffic, I've seen a single download taking 1~12s. I'm going to check if we have any configurable throttling being the bottleneck, but at the moment I think we can extend the timeout to see if it helps with the flake.  

Gist of the logging:
https://gist.github.com/roycaihw/be58ec7fa43e7604db64c3f2fc0f8278
https://gist.github.com/roycaihw/694314c7b7ff3f51e001025bc4e3c1de
https://gist.github.com/roycaihw/24837cd7cfac17577e6a658490bf6c3d

**Comment by roycaihw** [comment]
I checked apiserver log. For a case that took 23s, the timeline actually looks like the following: 
![Untitled drawing (1)](https://user-images.githubusercontent.com/6629765/71935007-95e74200-315a-11ea-8db6-96596d45c092.png)

The bottleneck is still in kube-aggregator [building and serving](https://github.com/kubernetes/kubernetes/blob/6099a739d8cb1762cdadf956fae484833b937c5d/staging/src/k8s.io/kube-aggregator/pkg/controllers/openapi/aggregator/aggregator.go#L226-L247) the openapi spec, which typically takes 5~10s. Between two aggregations, there is usually a 3s gap, which is composed by [1s waiting in queue](https://github.com/kubernetes/kubernetes/blob/6099a739d8cb1762cdadf956fae484833b937c5d/staging/src/k8s.io/kube-aggregator/pkg/controllers/openapi/controller.go#L121) and [1~2s downloading and deserializing](https://github.com/kubernetes/kubernetes/blob/6099a739d8cb1762cdadf956fae484833b937c5d/staging/src/k8s.io/kube-aggregator/pkg/controllers/openapi/controller.go#L141) spec from apiextensions-apiserver.

[Building and serving the spec](https://github.com/kubernetes/kubernetes/blob/6099a739d8cb1762cdadf956fae484833b937c5d/staging/src/k8s.io/kube-aggregator/pkg/controllers/openapi/aggregator/aggregator.go#L205-L209) has historically been expensive. I will try to get more detailed measurement. In the meanwhile, I added a small change to the kube-aggregator downloader to use jsoniter to speed up spec deserialization. 

Gist of the test and the kube-apiserver log: 
https://gist.github.com/roycaihw/b5d237964ffabc5814d293ad04732e03
```
I0107 19:36:26.100447       1 aggregator.go:229] Finished OpenAPI spec generation after 6.941513567s
```

**Comment by wojtek-t** [comment]
xref https://github.com/kubernetes/kubernetes/pull/86769#issuecomment-570571160

**Comment by liggitt** [comment]
runs since timeout was lengthened are green - https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-e2e-gce&include-filter-by-regex=api-machinery&width=5&sort-by-flakiness=200&include-filter-by-regex=CustomResourcePublishOpenAPI

issue opened to track improving the openapi aggregation speed at #86967

/close
