### ISSUE TITLE
1.17 & 1.18 clusters are failing during master rolling upgrade

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#86483]
https://github.com/kubernetes/kubernetes/pull/83520 changed the way how reflectors work.
In particular, when we down kube-apiserver, what happens is:
- watches (from kubelets/kube-proxies) are breaking and reconnecting to a different apiserver
- apiserver (when restarting) initializes watch cache at "now"
- given that bookmarks (in the current implementation) are send only right before watch is timing out, when we down kube-apiserver, they are not send

So in large cluster, when we down the last kube-apiserver, in many cases the watches are reconnecting to new enough apiserver and are failing with "error too old".
As a result, with https://github.com/kubernetes/kubernetes/pull/83520, we move the mode for relisting from etcd, and that kills apiserver
(mostly because when kubelet lists pods from its node, from cache we send only those, but from etcd we need to list everything, deserialize and filtter out).

Two main ideas how we can mitigate it is:
- change the reflector to instead try to list from cache - some approach can be find here: https://github.com/kubernetes/kubernetes/pull/86430
- send bookmarks more frequently (though we didn't validate the performance impact and that won't help in all cases)
- improve throttling of LIST requests (but the problem is that with pagination, we risk of not making any progress if continuations will be rejected and then failing with "out-of-window" errors)

I think the most promising and minimal change (given that we should cherrypick that to 1.17) seems to be some variation of (1), but we need more time to evaluate it properly.

@kubernetes/sig-scalability-bugs 
@kubernetes/sig-api-machinery-bugs 
@smarterclayton @liggitt @jpbetz @mm4tt

**Comment by wojtek-t** [comment]
We will provide more exact data once we have concrete numbers and comparisons.

**Comment by liggitt** [comment]
my immediate inclination would be to revert https://github.com/kubernetes/kubernetes/pull/83520 for 1.17.1 until we have more data, rather than leave it as-is or experiment in patch releases.

**Comment by liggitt** [comment]
> change the reflector to instead try to list from cache - some approach can be find here: #86430

isn't dropping the limit on reflector relist likely to crush servers running without the watch cache enabled? @smarterclayton might have better data on what that looks like.

**Comment by tedyu** [comment]
Option #2
```
send bookmarks more frequently
```
Can we send the bookmark right before shutting down api-server (not increasing frequency of sending bookmarks) ?

**Comment by wojtek-t** [comment]
> Can we send the bookmark right before shutting down api-server (not increasing frequency of sending bookmarks) ?

That doesn't work if e.g. machine is hard-rebooted or sth, so I wouldn't treat is as very full solution.


>> change the reflector to instead try to list from cache - some approach can be find here: #86430

> isn't dropping the limit on reflector relist likely to crush servers running without the watch cache enabled? @smarterclayton might have better data on what that looks like.

@liggitt - that is good question. But my claim is that you can't have very large clusters withou watch cache enabled (at least for couple main high-volume resources like endpoints, nodes and pods). So I'm personally not too worried about that.

**Comment by mm4tt** [comment]
I ran the following experiment to confirm that this is an actual regression between `1.16` and `1.17`

## Experiment

1. Set up two 5K node clusters (`VERSION=1.16.4` and `VERSION=1.17.0`)
```
kubetest --up \
  --extract=gs://kubernetes-release/release/$VERSION \
  --gcp-nodes=5000 \
  --gcp-project=$PROJECT \
  --gcp-zone=$ZONE \
  --provider=gce
```

2. Wait for cluster to go up, set up prometheus monitoring using `ClusterLoader2`

3. Reboot master VM
    1. `gcloud compute instances stop --project=$PROJECT --zone=$ZONE $MASTER_NAME`
    1. `sleep 2m`
    1. `gcloud compute instances start --project=$PROJECT --zone=$ZONE $MASTER_NAME`
    1. `sleep 2m && sudo ip route del to local 10.40.0.2/32 dev eth0` (needed due to https://github.com/kubernetes/kubernetes/issues/86547)

4. Observe...

## Results

### **1.16.4**

1. It took ~2 min since the master VM (and network to it) went up till the cluster *stabilized*. By *stabilized* I mean that the traffic pattern and the Scalability SLIs (e.g. api-call-latency) went back to what they were before the restart.
2. Some graphs (with comments)
    ![O5ep5phwiLP (1)](https://user-images.githubusercontent.com/2604887/71368664-cbabf880-25a8-11ea-81c5-b5bda1cdfbc6.png)
    ![L0TkdrMSWqd](https://user-images.githubusercontent.com/2604887/71368796-2b0a0880-25a9-11ea-84de-a82bd41bf37f.png)
3. Overall, this looks really good

### **1.17.0**

1. Master never stabilized after restart, api-server went into crash loop
2. Some graphs with comments, confirming that this is kind of a *thundering herd* issue. After master reboots, **etcd gets hit with 100-200 QPS of LIST requests per resource for multiple resources (SIC!)** which in turn overloads the system. Once this happens we run into the known *vicious circle* problem: system is overloaded -> we hit inflight-requests limits -> some important requests get dropped (e.g. leader election) -> more components restart and issue list request to initialize local cache -> system gets even more overloaded -> ...
    ![okFUcZVcsVk](https://user-images.githubusercontent.com/2604887/71369278-88eb2000-25aa-11ea-9a04-61b89da555bf.png)
    ![shewEYoUzy6](https://user-images.githubusercontent.com/2604887/71369333-b46e0a80-25aa-11ea-86f7-af331a4d0d95.png)


In general, this is really bad. We have to fix it (or revert the https://github.com/kubernetes/kubernetes/pull/83520) in 1.17.1

**Comment by wojtek-t** [comment]
@kubernetes/sig-release @guineveresaenger @alenkacz - FYI

**Comment by justaugustus** [comment]
cc: @kubernetes/patch-release-team @alejandrox1 @droslean

**Comment by alenkacz** [comment]
@wojtek-t for future reference, the best way to contact the CI signal team is @kubernetes/ci-signal :) We introduced it this iteration, I think it's not that well-known yet.

And thanks for filing this!

**Comment by wojtek-t** [comment]
The current version of https://github.com/kubernetes/kubernetes/pull/86430 seem to mitigate the problems that we found internally.
@mm4tt will run his tests (that he described above) to (hopefully) prove that it helps in this case too.

**Comment by mm4tt** [comment]
I ran the tests and can confirm that the fix helps. 
Master stabilized, there was no significant increase in the number of etcd list requests after the restart. 

If someone would like to take a look at the graphs, they can be found at http://35.237.122.182:3000/d/UkaNrXBZk/master-down-up-experiment?orgId=1&var-source=master-down-up-5k-k8s-1-18-fix&from=1577717822588&to=1577721055853

**Comment by hormes** [comment]
> send bookmarks more frequently

Because the watcher will rewatch in 5-10 minutes, we find in practice that it is more appropriate to send a bookmark in 1-2 minutes if no event has been sent.

> change the reflector to instead try to list from cache 

This works well on most cases, and the final bottleneck will become apiserver memory limit. Because apiserver cache does not support page list, list from apiserver cache consumes apiserver memory. There are two solutions to this problem. One is to add an interface to apiserver, which sends list data in a stream similar to watch, and the other is to extend the apiserver to support the page list, but the apiserver does not have multiple versions of data and we can limit the page list support to a single server.

**Comment by liggitt** [comment]
#86824 fixes the issue for 1.17, will be releases in 1.17.1

#86430 will resolve this for 1.18

/close

**Comment by wojtek-t** [comment]
Can we keep it open until 1.18 is also fixed?

I renamed the issue

**Comment by liggitt** [comment]
sure
