### ISSUE TITLE
Improve documents and guidance of each script in hack directory

### ISSUE THREAD

**Issue by hase1128** [kubernetes/kubernetes#86597]
**What would you like to be added**:
There are many useful scripts in "https://github.com/kubernetes/kubernetes/tree/master/hack".
For example, I often use `install-etcd.sh` and `local-up-cluster.sh` for creating simple k8s cluster quickly.
However, there are only few explanation or nothing how to use it.
I think it becomes more useful and helpful if some instruction or guidance is explained in each script.

**Why is this needed**:
It aims and expects to increase new k8s developers by describing how to use each script.

**My proposal**
Add the following description under the copyright for each script file.
 - Overview of the script
 - Simple usage
 - Supplementary explanation(This is option)

**Other concern**
I would like to know the purpose of use about hack directory.
(e.g. Where to put tools for developers(therefore there is no guidance?).)

**Comment by hase1128** [comment]
I don't know who is in charge of each scripts of hack, but if he agree the idea of this feature request , I am going to do this task myself!!

**Comment by zq-david-wang** [comment]
I believe there is a script generating swagger/openapi specfilters under hack, but I am still struggling with it. It could be of great help if there is some how-to doc for each scripts.

**Comment by tanjunchen** [comment]
@hase1128,On this basis, why not create a readme.md file under the hack folder, because a lot of kk CIs are derived from multiple script commands under the hack. There are already 268+ files under the hack file. For contributors unfamiliar with these, these comments and instructions are helpful to them, and it is also helpful for new contributors to handle pr ci error reports.

**Comment by tanjunchen** [comment]
/cc @fejta 
What do you think？

**Comment by hase1128** [comment]
@tanjunchen 
I think it's good idea to create readme.md.
(It may be easy to understand if the script's explanation is described by category or use.)
Apart from that, it is helpful that the script file itself has a brief description.

**Comment by hase1128** [comment]
When we create readme.md, it may tough work if creating it including all scripts explanation at one time.
(There are many scripts and I understand only some scripts now.)

Regarding readme.md, current my idea is to add a description to each script little by little and update the readme.md at the same time.
This means that readme.md will be completed little by little in conjunction with adding the description of each script.

**Comment by fejta** [comment]
Self-documenting commands sound useful.

A high level overview README.md also sounds useful.

**Comment by tanjunchen** [comment]
/cc @fejta 
/cc @hase1128 
Regarding adding help information, I suggest that we can submit pr in one or several files as a unit, so that we can track and statistics. For the documentation, I think it should be concise and not too long. How about this advice?  We can claim tasks through ``` i will pick up xxx ```, the pr title ``` Add some comment to hack/xx.sh ```

@hase1128 
yes , i agree with you.

- [ ] kubernetes/hack/benchmark-go.sh
- [ ] kubernetes/hack/boilerplate/boilerplate.bzl.txt
- [ ] kubernetes/hack/boilerplate/boilerplate.Dockerfile.txt
- [ ] kubernetes/hack/boilerplate/boilerplate.generatebzl.txt
- [ ] kubernetes/hack/boilerplate/boilerplate.generatego.txt
- [ ] kubernetes/hack/boilerplate/boilerplate.go.txt
- [ ] kubernetes/hack/boilerplate/boilerplate.Makefile.txt
- [ ] kubernetes/hack/boilerplate/boilerplate.py
- [ ] kubernetes/hack/boilerplate/boilerplate.py.txt
- [ ] kubernetes/hack/boilerplate/boilerplate.sh.txt
- [ ] kubernetes/hack/boilerplate/boilerplate_test.py
- [ ] kubernetes/hack/boilerplate/BUILD
- [ ] kubernetes/hack/boilerplate/test/BUILD
- [ ] kubernetes/hack/boilerplate/test/fail.go
- [ ] kubernetes/hack/boilerplate/test/fail.py
- [ ] kubernetes/hack/boilerplate/test/pass.go
- [ ] kubernetes/hack/boilerplate/test/pass.py
- [ ] kubernetes/hack/BUILD
- [ ] kubernetes/hack/build-cross.sh
- [ ] kubernetes/hack/build-go.sh
- [ ] kubernetes/hack/cherry_pick_pull.sh
- [ ] kubernetes/hack/conformance/BUILD
- [ ] kubernetes/hack/conformance/check_conformance_test_requirements.go
- [ ] kubernetes/hack/dev-build-and-push.sh
- [ ] kubernetes/hack/dev-build-and-up.sh
- [ ] kubernetes/hack/dev-push-conformance.sh
- [ ] kubernetes/hack/e2e-internal/BUILD
- [ ] kubernetes/hack/e2e-internal/e2e-cluster-size.sh
- [ ] kubernetes/hack/e2e-internal/e2e-down.sh
- [ ] kubernetes/hack/e2e-internal/e2e-grow-cluster.sh
- [ ] kubernetes/hack/e2e-internal/e2e-shrink-cluster.sh
- [ ] kubernetes/hack/e2e-internal/e2e-status.sh
- [ ] kubernetes/hack/e2e-internal/e2e-up.sh
- [ ] kubernetes/hack/e2e-node-test.sh
- [ ] kubernetes/hack/generate-bindata.sh
- [ ] kubernetes/hack/generate-docs.sh
- [ ] kubernetes/hack/gen-swagger-doc/gen-swagger-docs.sh
- [ ] kubernetes/hack/get-build.sh
- [ ] kubernetes/hack/ginkgo-e2e.sh
- [ ] kubernetes/hack/grab-profiles.sh
- [ ] kubernetes/hack/install-etcd.sh
- [ ] kubernetes/hack/jenkins/benchmark-dockerized.sh
- [ ] kubernetes/hack/jenkins/OWNERS
- [ ] kubernetes/hack/jenkins/README.md
- [ ] kubernetes/hack/jenkins/test-dockerized.sh
- [ ] kubernetes/hack/jenkins/verify-dockerized.sh
- [ ] kubernetes/hack/lib/BUILD
- [ ] kubernetes/hack/lib/etcd.sh
- [ ] kubernetes/hack/lib/golang.sh
- [ ] kubernetes/hack/lib/init.sh
- [ ] kubernetes/hack/lib/logging.sh
- [ ] kubernetes/hack/lib/protoc.sh
- [ ] kubernetes/hack/lib/swagger.sh
- [ ] kubernetes/hack/lib/test.sh
- [ ] kubernetes/hack/lib/util.sh
- [ ] kubernetes/hack/lib/version.sh
- [ ] kubernetes/hack/lint-dependencies.sh
- [ ] kubernetes/hack/list-feature-tests.sh
- [ ] kubernetes/hack/local-up-cluster.sh
- [ ] kubernetes/hack/make-rules/BUILD
- [ ] kubernetes/hack/make-rules/build.sh
- [ ] kubernetes/hack/make-rules/clean.sh
- [ ] kubernetes/hack/make-rules/cross.sh
- [ ] kubernetes/hack/make-rules/helpers/cache_go_dirs.sh
- [ ] kubernetes/hack/make-rules/helpers/go2make/BUILD
- [ ] kubernetes/hack/make-rules/helpers/go2make/go2make.go
- [ ] kubernetes/hack/make-rules/helpers/go2make/pkgwalk.go
- [ ] kubernetes/hack/make-rules/helpers/go2make/pkgwalk_test.go
- [ ] kubernetes/hack/make-rules/helpers/go2make/testdata/dir-with-gofiles/bar.go
- [ ] kubernetes/hack/make-rules/helpers/go2make/testdata/dir-with-gofiles/foo.go
- [ ] kubernetes/hack/make-rules/helpers/go2make/testdata/dir-with-gofiles/README
- [ ] kubernetes/hack/make-rules/helpers/go2make/testdata/dir-with-gofiles/skipme/README
- [ ] kubernetes/hack/make-rules/helpers/go2make/testdata/dir-with-gofiles/skipme/subsubdir/README
- [ ] kubernetes/hack/make-rules/helpers/go2make/testdata/dir-with-gofiles/skipme/README
- [ ] kubernetes/hack/make-rules/helpers/go2make/testdata/dir-with-gofiles/README
- [ ] kubernetes/hack/make-rules/helpers/go2make/testdata/dir-with-gofiles/subdir/README
- [ ] kubernetes/hack/make-rules/helpers/go2make/testdata/dir-with-gofiles/README
- [ ] kubernetes/hack/make-rules/helpers/go2make/testdata/dir-with-gofiles/testdata/README
- [ ] kubernetes/hack/make-rules/helpers/go2make/testdata/dir-with-gofiles/testdata/subsubdir/README
- [ ] kubernetes/hack/make-rules/helpers/go2make/testdata/dir-with-gofiles/testdata/README
- [ ] kubernetes/hack/make-rules/helpers/go2make/testdata/dir-with-gofiles/README
- [ ] kubernetes/hack/make-rules/helpers/go2make/testdata/dir-with-gofiles/_underscore/README
- [ ] kubernetes/hack/make-rules/helpers/go2make/testdata/dir-with-gofiles/_underscore/subsubdir/README
- [ ] kubernetes/hack/make-rules/helpers/go2make/testdata/dir-with-gofiles/_underscore/README
- [ ] kubernetes/hack/make-rules/helpers/go2make/testdata/dir-with-gofiles/README
- [ ] kubernetes/hack/make-rules/helpers/go2make/testdata/dir-without-gofiles/README
- [ ] kubernetes/hack/make-rules/Makefile.manifest
- [ ] kubernetes/hack/make-rules/make-help.sh
- [ ] kubernetes/hack/make-rules/test-cmd.sh
- [ ] kubernetes/hack/make-rules/test-e2e-kubeadm.sh
- [ ] kubernetes/hack/make-rules/test-e2e-node.sh
- [ ] kubernetes/hack/make-rules/test-integration.sh
- [ ] kubernetes/hack/make-rules/test.sh
- [ ] kubernetes/hack/make-rules/update.sh
- [ ] kubernetes/hack/make-rules/verify.sh
- [ ] kubernetes/hack/make-rules/vet.sh
- [ ] kubernetes/hack/OWNERS
- [ ] kubernetes/hack/pin-dependency.sh
- [ ] kubernetes/hack/print-workspace-status.sh
- [ ] kubernetes/hack/run-in-gopath.sh
- [ ] kubernetes/hack/testdata/auth-tokens.csv
- [ ] kubernetes/hack/testdata/configmap.yaml
- [ ] kubernetes/hack/testdata/CRD/bar.yaml
- [ ] kubernetes/hack/testdata/CRD/foo-added-subfield.yaml
- [ ] kubernetes/hack/testdata/CRD/foo-deleted-subfield.yaml
- [ ] kubernetes/hack/testdata/CRD/foo-updated-subfield.yaml
- [ ] kubernetes/hack/testdata/CRD/foo.yaml
- [ ] kubernetes/hack/testdata/CRD/multi-crd-list-added-field.yaml
- [ ] kubernetes/hack/testdata/CRD/multi-crd-list-deleted-field.yaml
- [ ] kubernetes/hack/testdata/CRD/multi-crd-list-updated-field.yaml
- [ ] kubernetes/hack/testdata/CRD/multi-crd-list.yaml
- [ ] kubernetes/hack/testdata/CRD/resource.yaml
- [ ] kubernetes/hack/testdata/csr.yml
- [ ] kubernetes/hack/testdata/deployment-label-change1.yaml
- [ ] kubernetes/hack/testdata/deployment-label-change2.yaml
- [ ] kubernetes/hack/testdata/deployment-label-change3.yaml
- [ ] kubernetes/hack/testdata/deployment-multicontainer-resources.yaml
- [ ] kubernetes/hack/testdata/deployment-multicontainer.yaml
- [ ] kubernetes/hack/testdata/deployment-revision1.yaml
- [ ] kubernetes/hack/testdata/deployment-revision2.yaml
- [ ] kubernetes/hack/testdata/deployment-with-UnixUserID.yaml
- [ ] kubernetes/hack/testdata/diff/configmap.yaml
- [ ] kubernetes/hack/testdata/diff/deployment.yaml
- [ ] kubernetes/hack/testdata/diff/pod.yaml
- [ ] kubernetes/hack/testdata/diff/secret.yaml
- [ ] kubernetes/hack/testdata/secret.yaml
- [ ] kubernetes/hack/testdata/filter/pod-apply-selector.yaml
- [ ] kubernetes/hack/testdata/filter/pod-dont-apply.yaml
- [ ] kubernetes/hack/testdata/frontend-controller.yaml
- [ ] kubernetes/hack/testdata/frontend-replicaset.yaml
- [ ] kubernetes/hack/testdata/invalid-rc-with-empty-args.yaml
- [ ] kubernetes/hack/testdata/kubernetes-service.yaml
- [ ] kubernetes/hack/testdata/kustomize/configmap.yaml
- [ ] kubernetes/hack/testdata/kustomize/deployment.yaml
- [ ] kubernetes/hack/testdata/kustomize/kustomization.yaml
- [ ] kubernetes/hack/testdata/kustomize/service.yaml
- [ ] kubernetes/hack/testdata/list.yaml
- [ ] kubernetes/hack/testdata/multi-resource-json.json
- [ ] kubernetes/hack/testdata/multi-resource-json-modify.json
- [ ] kubernetes/hack/testdata/multi-resource-list.json
- [ ] kubernetes/hack/testdata/multi-resource-list-modify.json
- [ ] kubernetes/hack/testdata/multi-resource-rclist.json
- [ ] kubernetes/hack/testdata/multi-resource-rclist-modify.json
- [ ] kubernetes/hack/testdata/multi-resource-svclist.json
- [ ] kubernetes/hack/testdata/multi-resource-svclist-modify.json
- [ ] kubernetes/hack/testdata/multi-resource-yaml-modify.yaml
- [ ] kubernetes/hack/testdata/multi-resource-yaml.yaml
- [ ] kubernetes/hack/testdata/null-propagation/deployment-l1.yaml
- [ ] kubernetes/hack/testdata/null-propagation/deployment-l2.yaml
- [ ] kubernetes/hack/testdata/OWNERS
- [ ] kubernetes/hack/testdata/pod-apply.yaml
- [ ] kubernetes/hack/testdata/pod-changed.yaml
- [ ] kubernetes/hack/testdata/pod-with-api-env.yaml
- [ ] kubernetes/hack/testdata/pod-with-large-name.yaml
- [ ] kubernetes/hack/testdata/pod-with-precision.json
- [ ] kubernetes/hack/testdata/pod.yaml
- [ ] kubernetes/hack/testdata/prune/a.yaml
- [ ] kubernetes/hack/testdata/prune/b.yaml
- [ ] kubernetes/hack/testdata/prune/svc.yaml
- [ ] kubernetes/hack/testdata/prune-reap/a.yml
- [ ] kubernetes/hack/testdata/prune-reap/b.yml
- [ ] kubernetes/hack/testdata/recursive/deployment/deployment/nginx-broken.yaml
- [ ] kubernetes/hack/testdata/recursive/deployment/deployment/nginx.yaml
- [ ] kubernetes/hack/testdata/recursive/deployment/nginx.yaml
- [ ] kubernetes/hack/testdata/recursive/deployment/nginx.yaml
- [ ] kubernetes/hack/testdata/recursive/pod/busybox.yaml
- [ ] kubernetes/hack/testdata/recursive/pod/pod/busybox-broken.yaml
- [ ] kubernetes/hack/testdata/recursive/pod/pod/busybox.yaml
- [ ] kubernetes/hack/testdata/recursive/pod/busybox.yaml
- [ ] kubernetes/hack/testdata/recursive/pod-modify/busybox.yaml
- [ ] kubernetes/hack/testdata/recursive/pod-modify/pod/busybox-broken.yaml
- [ ] kubernetes/hack/testdata/recursive/pod-modify/pod/busybox.yaml
- [ ] kubernetes/hack/testdata/recursive/pod-modify/busybox.yaml
- [ ] kubernetes/hack/testdata/recursive/rc/busybox.yaml
- [ ] kubernetes/hack/testdata/recursive/rc/rc/busybox-broken.yaml
- [ ] kubernetes/hack/testdata/recursive/rc/rc/busybox.yaml
- [ ] kubernetes/hack/testdata/recursive/rc/busybox.yaml
- [ ] kubernetes/hack/testdata/redis-slave-replicaset.yaml
- [ ] kubernetes/hack/testdata/retainKeys/deployment/deployment-after.yaml
- [ ] kubernetes/hack/testdata/retainKeys/deployment/deployment-before.yaml
- [ ] kubernetes/hack/testdata/rollingupdate-daemonset-rv2.yaml
- [ ] kubernetes/hack/testdata/rollingupdate-daemonset.yaml
- [ ] kubernetes/hack/testdata/rollingupdate-statefulset-rv2.yaml
- [ ] kubernetes/hack/testdata/rollingupdate-statefulset.yaml
- [ ] kubernetes/hack/testdata/scale-deploy-1.yaml
- [ ] kubernetes/hack/testdata/scale-deploy-2.yaml
- [ ] kubernetes/hack/testdata/scale-deploy-3.yaml
- [ ] kubernetes/hack/testdata/secret.yaml
- [ ] kubernetes/hack/testdata/service-revision1.yaml
- [ ] kubernetes/hack/testdata/service-revision2.yaml
- [ ] kubernetes/hack/testdata/sorted-pods/sorted-pod1.yaml
- [ ] kubernetes/hack/testdata/sorted-pods/sorted-pod2.yaml
- [ ] kubernetes/hack/testdata/sorted-pods/sorted-pod3.yaml
- [ ] kubernetes/hack/testdata/tls.crt
- [ ] kubernetes/hack/testdata/tls.key
- [ ] kubernetes/hack/test-go.sh
- [ ] kubernetes/hack/test-integration.sh
- [ ] kubernetes/hack/update-all.sh
- [ ] kubernetes/hack/update-bazel.sh
- [ ] kubernetes/hack/update-codegen.sh
- [ ] kubernetes/hack/update-generated-api-compatibility-data.sh
- [ ] kubernetes/hack/update-generated-device-plugin-dockerized.sh
- [ ] kubernetes/hack/update-generated-device-plugin.sh
- [ ] kubernetes/hack/update-generated-docs.sh
- [ ] kubernetes/hack/update-generated-kms-dockerized.sh
- [ ] kubernetes/hack/update-generated-kms.sh
- [ ] kubernetes/hack/update-generated-kubelet-plugin-registration-dockerized.sh
- [ ] kubernetes/hack/update-generated-kubelet-plugin-registration.sh
- [ ] kubernetes/hack/update-generated-pod-resources-dockerized.sh
- [ ] kubernetes/hack/update-generated-pod-resources.sh
- [ ] kubernetes/hack/update-generated-protobuf-dockerized.sh
- [ ] kubernetes/hack/update-generated-protobuf.sh
- [ ] kubernetes/hack/update-generated-runtime-dockerized.sh
- [ ] kubernetes/hack/update-generated-runtime.sh
- [ ] kubernetes/hack/update-generated-swagger-docs.sh
- [x] kubernetes/hack/update-gofmt.sh
- [ ] kubernetes/hack/update-import-aliases.sh
- [ ] kubernetes/hack/update-openapi-spec.sh
- [ ] kubernetes/hack/update-translations.sh
- [ ] kubernetes/hack/update-vendor-licenses.sh
- [ ] kubernetes/hack/update-vendor.sh
- [ ] kubernetes/hack/update-workspace-mirror.sh
- [ ] kubernetes/hack/verify-all.sh
- [ ] kubernetes/hack/verify-api-groups.sh
- [ ] kubernetes/hack/verify-bazel.sh
- [ ] kubernetes/hack/verify-boilerplate.sh
- [ ] kubernetes/hack/verify-cli-conventions.sh
- [ ] kubernetes/hack/verify-codegen.sh
- [ ] kubernetes/hack/verify-conformance-requirements.sh
- [ ] kubernetes/hack/verify-description.sh
- [ ] kubernetes/hack/verify-external-dependencies-version.sh
- [ ] kubernetes/hack/verify-flags/excluded-flags.txt
- [ ] kubernetes/hack/verify-flags/OWNERS
- [ ] kubernetes/hack/OWNERS
- [ ] kubernetes/hack/verify-flags-underscore.py
- [ ] kubernetes/hack/verify-generated-device-plugin.sh
- [ ] kubernetes/hack/verify-generated-docs.sh
- [ ] kubernetes/hack/verify-generated-files-remake.sh
- [ ] kubernetes/hack/verify-generated-files.sh
- [ ] kubernetes/hack/verify-generated-kms.sh
- [ ] kubernetes/hack/verify-generated-kubelet-plugin-registration.sh
- [ ] kubernetes/hack/verify-generated-pod-resources.sh
- [ ] kubernetes/hack/verify-generated-protobuf.sh
- [ ] kubernetes/hack/verify-generated-runtime.sh
- [ ] kubernetes/hack/verify-generated-swagger-docs.sh
- [ ] kubernetes/hack/verify-gofmt.sh
- [x] kubernetes/hack/verify-golint.sh
- [ ] kubernetes/hack/verify-govet.sh
- [ ] kubernetes/hack/verify-import-aliases.sh
- [ ] kubernetes/hack/verify-import-boss.sh
- [ ] kubernetes/hack/verify-imports.sh
- [ ] kubernetes/hack/verify-linkcheck.sh
- [ ] kubernetes/hack/verify-no-vendor-cycles.sh
- [ ] kubernetes/hack/verify-openapi-spec.sh
- [ ] kubernetes/hack/verify-pkg-names.sh
- [ ] kubernetes/hack/verify-publishing-bot.py
- [ ] kubernetes/hack/verify-readonly-packages.sh
- [ ] kubernetes/hack/verify-shellcheck.sh
- [x] kubernetes/hack/verify-spelling.sh
- [ ] kubernetes/hack/verify-staging-meta-files.sh
- [ ] kubernetes/hack/verify-staticcheck.sh
- [ ] kubernetes/hack/verify-test-code.sh
- [ ] kubernetes/hack/verify-test-featuregates.sh
- [ ] kubernetes/hack/verify-test-images.sh
- [ ] kubernetes/hack/verify-typecheck-providerless.sh
- [ ] kubernetes/hack/verify-typecheck.sh
- [ ] kubernetes/hack/verify-vendor-licenses.sh
- [ ] kubernetes/hack/verify-vendor.sh
- [ ] kubernetes/hack/readme.md

**Comment by tanjunchen** [comment]
i will pick up kubernetes/hack/readme.md, i will do it  step by step.

**Comment by hase1128** [comment]
@tanjunchen 
I agree with your idea, and thanks the checkbox to check progress.
there are many scripts, so let's work together!

**Comment by hase1128** [comment]
I will pick up hack/verify-linkcheck.sh

**Comment by hase1128** [comment]
I will pick up hack/verify-imports.sh

**Comment by hase1128** [comment]
I will pick up hack/verify-XXXX.sh (all of verify scripts).
But there are large number of scripts(over 40), I want to split it into two or three PRs.

**Comment by tanjunchen** [comment]
I will pick up hack/update-XXXX.sh

**Comment by KobayashiD27** [comment]
I will pick up these scripts.
>kubernetes/hack/benchmark-go.sh
kubernetes/hack/build-cross.sh
kubernetes/hack/build-go.sh
kubernetes/hack/cherry_pick_pull.sh
kubernetes/hack/dev-build-and-push.sh
kubernetes/hack/dev-build-and-up.sh
kubernetes/hack/dev-push-conformance.sh
kubernetes/hack/e2e-node-test.sh
kubernetes/hack/generate-docs.sh

**Comment by hase1128** [comment]
I will pick up these scripts

get-build.sh
ginkgo-e2e.sh
grab-profiles.sh
install-etcd.sh
lint-dependencies.sh
list-feature-tests.sh
local-up-cluster.sh
pin-dependency.sh
print-workspace-status.sh
run-in-gopath.sh
test-go.sh
test-integration.sh

**Comment by tanjunchen** [comment]
@hase1128  How about this now?
/help
Marking this tag so that others can easily access it.

**Comment by hase1128** [comment]
> @hase1128 How about this now?
> /help
> Marking this tag so that others can easily access it.

I think we've finished adding simple explanations to the almost scripts.

It seems that several scripts of update-XXXX.sh does not complete yet.
I think we may able to close after that work.

**Comment by ZhiFeng1993** [comment]
I will pick up these scripts:
```
 kubernetes/hack/update-generated-pod-resources.sh
 kubernetes/hack/update-generated-protobuf-dockerized.sh
 kubernetes/hack/update-generated-protobuf.sh
 kubernetes/hack/update-generated-runtime-dockerized.sh
 kubernetes/hack/update-generated-runtime.sh
 kubernetes/hack/update-generated-swagger-docs.sh
```
