### ISSUE TITLE
kube-scheduler.log has a lot of PersitentVolumeClaim binding errors in load test

### ISSUE THREAD

**Issue by mm4tt** [kubernetes/kubernetes#86669]
[ I stumbled upon this when debugging [#86434](https://github.com/kubernetes/kubernetes/issues/86434) ]

Example run (100 node) - https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/1210547271494537217
In the [kube-scheduler.log](https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/1210547271494537217/artifacts/e2e-big-master/kube-scheduler.log) there is a lot of errors like this one
```
E1227 13:25:39.219980       1 scheduler.go:641] error selecting node for pod: running "VolumeBinding" filter plugin for pod "medium-statefulset-0-19": pod has unbound immediate PersistentVolumeClaims
E1227 13:25:39.220390       1 factory.go:477] pod: test-f5ajcq-1/medium-statefulset-0-19 is already present in the active queue
E1227 13:25:39.223899       1 factory.go:452] Error scheduling test-f5ajcq-1/medium-statefulset-0-19: running "VolumeBinding" filter plugin for pod "medium-statefulset-0-19": pod has unbound immediate PersistentVolumeClaims; retrying
```

Looks like there are over 300 errors like this (and we create only 35 PVCs in 100 node test). In 5K node test we have almost 14K such errors. 
What's more, all are transient (as eventually all pods are scheduled and the test passes) but are logged as error. 

I'd like to understand why there is so many such errors and, if they are expected, why they're logged as errors and e.g. not as warnings. 

/sig scalability
/sig scheduling

@ahg-g, could you take a look and triage this? Thanks!

**Comment by ahg-g** [comment]
This error is returned by [FindPodVolumes](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/volume/scheduling/scheduler_binder.go#L217), this logic is owned by sig storage.

/sig storage
/assign @msau42 

Michelle can you please triage?

**Comment by msau42** [comment]
We don't schedule pods until the PVCs are provisioned + bound because we need to wait until they are provisioned to know what zone they are in and schedule the pods appropriately. If you want to avoid them in your test, then you could create the PVCs, wait for them to be bound, and then create the Pods, but I would not recommend that because it's not how a StatefulSet would actually behave, and it wouldn't work if you use "WaitForConsumer" binding mode in multi-zone clusters.

I'm not sure what else to do here. They should be errors to prevent the Pod from getting scheduled, and are expected when you initially create a Pod + PVC.  Maybe in the test you can ignore the initial provisioning/bootstrapping sequence, and only start measuring by recreating Pods?

**Comment by mm4tt** [comment]
Thanks, @msau42 

The explanation is sufficient for now. The errors are currently not affecting us (although they might get relevant when we implement the stateful pod startup latency SLI/SLO), I just noticed a lot of them in the scheduler log and wanted to understand what is going on. 

Closing this issue as there isn't any action required here.
