### ISSUE TITLE
[Failing Test] gce-cos-master-reboot (ci-kubernetes-e2e-gci-gce-reboot )

### ISSUE THREAD

**Issue by droslean** [kubernetes/kubernetes#86787]
**Which jobs are failing**:
`gce-cos-master-reboot (ci-kubernetes-e2e-gci-gce-reboot )`

**Which test(s) are failing**:
`[k8s.io] [sig-cloud-provider-gcp] Reboot [Disruptive] [Feature:Reboot] each node by switching off the network interface and ensure they function upon switch on`

**Testgrid link**:
https://testgrid.k8s.io/sig-release-master-informing#gce-cos-master-reboot

**Reason for failure**:
check https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-reboot/1212748364777525249

**Anything else we need to know**:
/cc @kubernetes/ci-signal 
/milestone v1.18
/sig cloud-provider-gcp

**Comment by tpepper** [comment]
Probably related to https://github.com/kubernetes/kubernetes/pull/85962

**Comment by tpepper** [comment]
https://storage.googleapis.com/k8s-gubernator/triage/index.html?date=2019-12-16&job=ci-kubernetes-e2e-gci-gce-reboot shows the #85962 merge
https://storage.googleapis.com/k8s-gubernator/triage/index.html?date=2019-10-23&job=ci-kubernetes-e2e-gci-gce-reboot shows the errant merge that inadvertantly disabled the test

This test was probably failing since forever.

**Comment by droslean** [comment]
@neolit123 Any news?

**Comment by neolit123** [comment]
this one is on cloud provider GCP.

**Comment by droslean** [comment]
@andrewsykim @cheftako Can you please take a look?

**Comment by jpreese** [comment]
Follow up from today's release meeting: If the test has been broken for as long as we know it, theres value in just removing it. If the test owners don't have capacity to look into it, CI Signal can investigate.

**Comment by droslean** [comment]
@dims Any advice on which team is responsible? It seems there is not any maintainer for this job.

**Comment by dims** [comment]
try talking to @cheftako please

**Comment by alejandrox1** [comment]
Turning to the question of whether these tests are actually useful...

One of the tests that has been continuously failing is this one https://github.com/kubernetes/kubernetes/blob/master/test/e2e/cloud/gcp/reboot.go#L114-L117
Which essentially does 
```
nohup sh -c 'sleep 10 && sudo ip link set eth0 down && sleep 120 && sudo ip link set eth0 up && (sudo dhclient || true)' >/dev/null 2>&1 &
```
because
```go
// switch the network interface off for a while to simulate a network outage
// We sleep 10 seconds to give some time for ssh command to cleanly finish before network is down.
```

From the logs (example https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-reboot/1227392723615485953#1:build-log.txt%3A614 ) it waits for 2 minutes (120 seconds) for each node to not be ready
```
I0212 00:50:31.937] Feb 12 00:50:31.936: INFO: Waiting up to 2m0s for node err-e2e-minion-group-f5m4 condition Ready to be false
```

and then for the next couple minutes it just checks this condition until it fails
```
I0212 00:56:20.393] Feb 12 00:56:20.392: INFO: Condition Ready of node err-e2e-minion-group-f5m4 is false instead of true. Reason: NodeStatusUnknown, message: Kubelet stopped posting node status.
I0212 00:56:22.351] Feb 12 00:56:22.350: INFO: Node err-e2e-minion-group-lr85 didn't reach desired Ready condition status (true) within 5m0s
I0212 00:56:22.391] Feb 12 00:56:22.391: INFO: Condition Ready of node err-e2e-minion-group-jnm5 is false instead of true. Reason: NodeStatusUnknown, message: Kubelet stopped posting node status.
I0212 00:56:22.393] Feb 12 00:56:22.392: INFO: Node err-e2e-minion-group-f5m4 didn't reach desired Ready condition status (true) within 5m0s
I0212 00:56:24.428] Feb 12 00:56:24.428: INFO: Condition Ready of node err-e2e-minion-group-jnm5 is false instead of true. Reason: NodeStatusUnknown, message: Kubelet stopped posting node status.
I0212 00:56:26.465] Feb 12 00:56:26.464: INFO: Condition Ready of node err-e2e-minion-group-jnm5 is false instead of true. Reason: NodeStatusUnknown, message: Kubelet stopped posting node status.
I0212 00:56:28.501] Feb 12 00:56:28.501: INFO: Condition Ready of node err-e2e-minion-group-jnm5 is false instead of true. Reason: NodeStatusUnknown, message: Kubelet stopped posting node status.
I0212 00:56:30.537] Feb 12 00:56:30.537: INFO: Condition Ready of node err-e2e-minion-group-jnm5 is false instead of true. Reason: NodeStatusUnknown, message: Kubelet stopped posting node status.
I0212 00:56:32.538] Feb 12 00:56:32.537: INFO: Node err-e2e-minion-group-jnm5 didn't reach desired Ready condition status (true) within 5m0s
I0212 00:56:32.538] Feb 12 00:56:32.537: INFO: Node err-e2e-minion-group-f5m4 failed reboot test.
I0212 00:56:32.538] Feb 12 00:56:32.537: INFO: Node err-e2e-minion-group-jnm5 failed reboot test.
I0212 00:56:32.538] Feb 12 00:56:32.537: INFO: Node err-e2e-minion-group-lr85 failed reboot test.
I0212 00:56:32.539] Feb 12 00:56:32.538: FAIL: Test failed; at least one node failed to reboot in the time given.
```

So it looks like the e2e tests are not failing because of inherent infra issues (i.e., kube-up decided to do some weird thing) but the issue seems to be with the time to reach a condition.
Again if we look at the logs we can see that switching the network interface does have an effect and leads to the nodes reaching a non-ready status but ultimately fail to come back up within the desired 5m time mark - this bit of the tests is where it all goes bad https://github.com/kubernetes/kubernetes/blob/f9250c4f951a65d6eb65b6aceb1ac1f33598c14a/test/e2e/cloud/gcp/reboot.go#L284 .

---

The question then turns to turning off the network interface for a node in such a way (`sudo ip link set eth0 down `) and then expecting the node to come back to live within 5 minutes of turning the interfac back on something reasonable?

If it is, then either we have to look at why it takes longer than 5 minutes or we can increase the timeouts https://github.com/kubernetes/kubernetes/blob/f9250c4f951a65d6eb65b6aceb1ac1f33598c14a/test/e2e/cloud/gcp/reboot.go#L44-L54

If it isn't, then how can we test the ability of nodes to be rebooted?

**Comment by alejandrox1** [comment]
Wanted to triple check on the test looking for nodes to be back up after being rebooted: I dont think 5 minutes is a hard deadline - only SLOs I could find were for scalability https://github.com/kubernetes/community/blob/master/sig-scalability/slos/slos.md.
