### ISSUE TITLE
SelectorFromSet function returns selector that matches everything on invalid labels

### ISSUE THREAD

**Issue by rajathagasthya** [kubernetes/kubernetes#86792]
**What happened**:
While looking into https://github.com/kubernetes-sigs/controller-runtime/issues/740, I noticed that the `SelectorFromSet` function is gobbling up validation errors and returns an empty selector that matches everything. (https://github.com/kubernetes/apimachinery/blob/3253b0a30d67e7e362b8615e463156bac729c82f/pkg/labels/selector.go#L881-L883)

The result is that when you pass labels which have invalid keys or values, you get an "everything" selector that selects the wrong objects (this is dangerous especially on deletion as described in the c-r issue linked above).

Same issue here as well since the same function is called - https://github.com/kubernetes/apimachinery/blob/3253b0a30d67e7e362b8615e463156bac729c82f/pkg/fields/fields.go#L60-L62

**What you expected to happen**:
`SelectorFromSet` to return an error when validation error occurs and not to ignore it. 

**How to reproduce it (as minimally and precisely as possible)**:

```
import (
    "strings"
    "k8s.io/apimachinery/pkg/fields"
)

s := fields.Set{"foo", strings.Repeat("a", 64)}  // invalid label value
sel := fields.SelectorFromSet(s)  // no error, but returns selector which matches everything
```

I'm happy to fix this. But changing that function signature to return an error now is a breaking change, so I'm not sure what the cleanest solution would be. Maybe another function that returns both selector and an error?

**Comment by fedebongio** [comment]
/assign @DirectXMan12 
Solly would you be able to take a look to this one please?

**Comment by DirectXMan12** [comment]
We talked about this a bit in controller-runtime.  Probably the better option is to make `SelectorFromSet` return an error, but that's a whole lotta churn.  At the very least, we should have a godoc comment.  Let's take a look at the internal uses:

In k/k + staging, we have:

```shell
directxman12@💻 ~[go:kubernetes] $ ag 'SelectorFromSet' --go | wc -l
116
directxman12@💻 ~[go:kubernetes] $ ag 'SelectorFromSet' --go --ignore-dir=test | wc -l
43
```

Mostly test uses.  Of the non-test uses, most seem to be constant or pre-validated (e.g. used in conversion logic).  Constant should be migrated to `SelectorFromValidatedSet`, *explicitly* pre-validated should be *very* carefully migrated as well.

I propose we introduce a new method that returns the error instead of swallowing it, mark the old one as deprecated, and gradually migrate.  That avoids churn in external codebases but gives us a reccomended path forward.

Thoughts?

**Comment by alvaroaleman** [comment]
/assign

I went ahead and created a PR for this. The current behaviour is a huge footgun and we neither mention that in the godocs nor do we provide a safe alternate.

**Comment by alvaroaleman** [comment]
This got fixed in https://github.com/kubernetes/kubernetes/pull/89747, `SelectorFromSet` will not attempt to validate anything and instead just construct an invalid selector that will then get rejected by the server.
/close
