### ISSUE TITLE
Support optional projected serviceAccountTokens

### ISSUE THREAD

**Issue by howardjohn** [kubernetes/kubernetes#86827]
**What would you like to be added**:

There are a lot of clusters that do not support projected serviceAccountTokens. To avoid complexity in our installation, we want to fallback from using the projected serviceAccountToken. Ideally, we would just add `optional: true` like we can do with secrets or config maps. 

**Why is this needed**:

So if the feature is no enabled on the cluster, we can gracefully degrade instead of blocking pod startup.

Alternatives:
* Have our installation automagically detect if the cluster supports it. This is impossible with Helm, and sort of hacky for a few reasons
* Make users manually configure this. Bad UX

**Comment by howardjohn** [comment]
/sig storage

^ maybe not right..

**Comment by howardjohn** [comment]
This doesn't really fully solve the problem for us for at least a year though since if this was theoretically merged today, we couldn't add `optional: true` since it would break anyone running an old kubernetes cluster as well. But ti would be nice for the future

**Comment by neolit123** [comment]
adding
/sig auth
as per https://github.com/kubernetes/community/pull/1973

**Comment by liggitt** [comment]
The case for an optional configmap or secret volume is clearer to me… it allows optionally injected configuration. conditionalizing the projected service account volume type because of cluster capabilities is less obviously beneficial. I'd rather see progress on resolving the issues blocking promotion to GA and inclusion in conformance than formalizing a lack of support for the feature in an API. 

/priority awaiting-more-evidence

**Comment by howardjohn** [comment]
That's reasonable to me. I would much rather just being able to always use the project token rather than even having a fallback at all, so that makes sense
