### ISSUE TITLE
Expose minStartupPods as a flag

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#8684]
There are a few cases where one doesn't care about a pod on each node, eg: scalability testing with a 100 node cluster. Another way to solve this would be to remove minStartupPods check form the ginkgo.focus path. Eitherway, would be nice not to have to incur the overhead of this check everytime. 

@mbforbes

**Comment by mbforbes** [comment]
Minor correction: It's not a pod on each node, it's a pod in the entire cluster.

**Comment by mbforbes** [comment]
Oh, unless you'res saying that in checking all pods, if there is a pod on every node, then it will check all of them, yes!

The tricky thing is some tests want to check the health of all pods in the cluster, so it doesn't make sense to begin the tests until that precondition is satisfied. That precondition was being broken during the middle of the tests and no one seemed to notice, so it seemed best to surface this at the beginning of the test.

I think if we're going to skip this check, we'll need to also isolate a subset of tests that don't care about cluster health. Does this seem reasonable? I fear otherwise we'll just start always passing the flag to skip this check, and pods will be silently broken.

**Comment by bprashanth** [comment]
So I see:
```
INFO: 6 / 53 pods in namespace 'default' are running and ready (9m42.549910297s elapsed)
INFO: 6 / 54 pods in namespace 'default' are running and ready (9m47.818861678s elapsed)
INFO: 6 / 58 pods in namespace 'default' are running and ready (9m53.095908778s elapsed)
INFO: 6 / 57 pods in namespace 'default' are running and ready (9m58.343806014s elapsed)

```

This will essentially never pass because I setup my cluster of 100 nodes via the normal e2e pushup, so i got an rc of size 6 (and I really don't want a larger rc because I'm not going to use fluentd etc and don't want them to push more load on the master).

**Comment by bprashanth** [comment]
Ah, in fact I see this in the scalability tests on jenkins as well. @wojtek-t

**Comment by mbforbes** [comment]
Hmm, I'm still a bit confused.

1. [`minStartupPods`](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/test/e2e/e2e_test.go#L60) is currently 0. Why would changing that affect the behavior you're describing? Do you mean you want to turn on/off [`waitForPodsRunningReady(...)`](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/test/e2e/e2e_test.go#L129) as a boolean flag?

2. Why would you want to start e2e tests if only 6 of the 57 pods in the cluster are running and ready? Some e2e tests do exactly this check (waiting until all of the pods are running and ready), so they would immediately fail.

3. This behavior has existed since March 16th (in #5135); we only recently changed this check from Bash to Go, and made it slightly more thorough (checking readiness as well as running). Is there a reason this only became an issue now?

Also, as a small note, the total pod count went from 58 down to 57 in the logs you reported, which suggests a pod is exiting...

**Comment by bprashanth** [comment]
> minStartupPods is currently 0. 

Oh, I haven't synced, it's 1 on mine.

> Why would you want to start e2e tests if only 6 of the 57 pods in the cluster are running and ready? 

The scalability suite on jenkins only runs 1 test called density, which starts 3000 pods and monitors the cluster. Doesn't really care about any of the elasticsearch or fluentd pods. 

>Is there a reason this only became an issue now?

You might have a point. I haven't debugged too deep and jumped at the first weird thing I saw. In essence, previously something like `ginkgo-e2e --focus=Density` would go straight to running Density, now it polls on the pods, always gets stuck at 6/X timing out in 10m. The fact that those 54 seem to be stuck is weird.
