### ISSUE TITLE
Delete pod didn't call CNI "DEL" causing CNI IP leak

### ISSUE THREAD

**Issue by tdihp** [kubernetes/kubernetes#86944]
**What happened**:

Some issue causing fail when initializing Pod, however CNI IP was never recycled by running "DEL".

Eventually new pods stuck due to no more address to assign by Azure CNI.

We identified one pod which has it's pod name in azure-vnet.json (which saves state of each IP), but not present anymore in the clsuter, the following is the related logs in /var/log/messages of it's lifecycle from node. (log has removed node name to avoid to be tediously long)

```
16:16:38 kubelet[3898]: I1125 16:16:38.724199    3898 kubelet.go:1887] SyncLoop (ADD, "api"): "lifestyle-contentservice-api-deployment-green-74bc4ccf86-r9pfn_lifestyle(f733ccfa-0f9e-11ea-af5e-467e88bd3364)"
16:16:38 kubelet[3898]: I1125 16:16:38.861325    3898 reconciler.go:207] operationExecutor.VerifyControllerAttachedVolume started for volume "default-token-bj62h" (UniqueName: "kubernetes.io/secret/f733ccfa-0f9e-11ea-af5e-467e88bd3364-default-token-bj62h") pod "lifestyle-contentservice-api-deployment-green-74bc4ccf86-r9pfn" (UID: "f733ccfa-0f9e-11ea-af5e-467e88bd3364")
16:16:38 kubelet[3898]: I1125 16:16:38.961694    3898 reconciler.go:252] operationExecutor.MountVolume started for volume "default-token-bj62h" (UniqueName: "kubernetes.io/secret/f733ccfa-0f9e-11ea-af5e-467e88bd3364-default-token-bj62h") pod "lifestyle-contentservice-api-deployment-green-74bc4ccf86-r9pfn" (UID: "f733ccfa-0f9e-11ea-af5e-467e88bd3364")
16:16:38 systemd[1]: Started Kubernetes transient mount for /var/lib/kubelet/pods/f733ccfa-0f9e-11ea-af5e-467e88bd3364/volumes/kubernetes.io~secret/default-token-bj62h.
16:16:38 kubelet[3898]: I1125 16:16:38.969572    3898 operation_generator.go:669] MountVolume.SetUp succeeded for volume "default-token-bj62h" (UniqueName: "kubernetes.io/secret/f733ccfa-0f9e-11ea-af5e-467e88bd3364-default-token-bj62h") pod "lifestyle-contentservice-api-deployment-green-74bc4ccf86-r9pfn" (UID: "f733ccfa-0f9e-11ea-af5e-467e88bd3364")
16:16:39 kubelet[3898]: I1125 16:16:39.078573    3898 kuberuntime_manager.go:409] No sandbox for pod "lifestyle-contentservice-api-deployment-green-74bc4ccf86-r9pfn_lifestyle(f733ccfa-0f9e-11ea-af5e-467e88bd3364)" can be found. Need to start a new one
16:16:39 kubelet[3898]: I1125 16:16:39.337038    3898 kubelet.go:1903] SyncLoop (DELETE, "api"): "lifestyle-contentservice-api-deployment-green-74bc4ccf86-r9pfn_lifestyle(f733ccfa-0f9e-11ea-af5e-467e88bd3364)"
16:16:39 kubelet[3898]: I1125 16:16:39.465833    3898 reconciler.go:181] operationExecutor.UnmountVolume started for volume "default-token-bj62h" (UniqueName: "kubernetes.io/secret/f733ccfa-0f9e-11ea-af5e-467e88bd3364-default-token-bj62h") pod "f733ccfa-0f9e-11ea-af5e-467e88bd3364" (UID: "f733ccfa-0f9e-11ea-af5e-467e88bd3364")
16:16:39 kubelet[3898]: I1125 16:16:39.486585    3898 operation_generator.go:815] UnmountVolume.TearDown succeeded for volume "kubernetes.io/secret/f733ccfa-0f9e-11ea-af5e-467e88bd3364-default-token-bj62h" (OuterVolumeSpecName: "default-token-bj62h") pod "f733ccfa-0f9e-11ea-af5e-467e88bd3364" (UID: "f733ccfa-0f9e-11ea-af5e-467e88bd3364"). InnerVolumeSpecName "default-token-bj62h". PluginName "kubernetes.io/secret", VolumeGidValue ""
16:16:39 kubelet[3898]: I1125 16:16:39.566107    3898 reconciler.go:301] Volume detached for volume "default-token-bj62h" (UniqueName: "kubernetes.io/secret/f733ccfa-0f9e-11ea-af5e-467e88bd3364-default-token-bj62h") on node "aks-agentpool-33856301-vmss000002" DevicePath ""
16:16:39 dockerd[3529]: time="2019-11-25T16:16:39.643686400Z" level=info msg="shim containerd-shim started" address="/containerd-shim/moby/3cb3517d1edbc101ec794e809dcfa90222d93d731385becd005a78b49383d6f6/shim.sock" debug=false pid=108918
16:16:40 kubelet[3898]: 2019/11/25 16:16:40 [109066] [cni-ipam] Processing ADD command with args {ContainerID:3cb3517d1edbc101ec794e809dcfa90222d93d731385becd005a78b49383d6f6 Netns:/proc/108942/ns/net IfName:eth0 Args:IgnoreUnknown=1;K8S_POD_NAMESPACE=lifestyle;K8S_POD_NAME=lifestyle-contentservice-api-deployment-green-74bc4ccf86-r9pfn;K8S_POD_INFRA_CONTAINER_ID=3cb3517d1edbc101ec794e809dcfa90222d93d731385becd005a78b49383d6f6 Path:/opt/cni/bin}.
16:16:40 dockerd[3529]: time="2019-11-25T16:16:40.358203900Z" level=info msg="shim reaped" id=3cb3517d1edbc101ec794e809dcfa90222d93d731385becd005a78b49383d6f6
16:16:40 kubelet[3898]: W1125 16:16:40.839920    3898 docker_sandbox.go:384] failed to read pod IP from plugin/docker: NetworkPlugin cni failed on the status hook for pod "lifestyle-contentservice-api-deployment-green-74bc4ccf86-r9pfn_lifestyle": CNI failed to retrieve network namespace path: cannot find network namespace for the terminated container "3cb3517d1edbc101ec794e809dcfa90222d93d731385becd005a78b49383d6f6"
16:16:40 kubelet[3898]: W1125 16:16:40.869931    3898 docker_sandbox.go:384] failed to read pod IP from plugin/docker: NetworkPlugin cni failed on the status hook for pod "lifestyle-contentservice-api-deployment-green-74bc4ccf86-r9pfn_lifestyle": CNI failed to retrieve network namespace path: cannot find network namespace for the terminated container "3cb3517d1edbc101ec794e809dcfa90222d93d731385becd005a78b49383d6f6"
16:16:40 kubelet[3898]: I1125 16:16:40.871787    3898 kubelet.go:1932] SyncLoop (PLEG): "lifestyle-contentservice-api-deployment-green-74bc4ccf86-r9pfn_lifestyle(f733ccfa-0f9e-11ea-af5e-467e88bd3364)", event: &pleg.PodLifecycleEvent{ID:"f733ccfa-0f9e-11ea-af5e-467e88bd3364", Type:"ContainerStarted", Data:"3cb3517d1edbc101ec794e809dcfa90222d93d731385becd005a78b49383d6f6"}
16:16:40 kubelet[3898]: I1125 16:16:40.905369    3898 kubelet.go:1903] SyncLoop (DELETE, "api"): "lifestyle-contentservice-api-deployment-green-74bc4ccf86-r9pfn_lifestyle(f733ccfa-0f9e-11ea-af5e-467e88bd3364)"
16:16:40 kubelet[3898]: I1125 16:16:40.914246    3898 kubelet.go:1897] SyncLoop (REMOVE, "api"): "lifestyle-contentservice-api-deployment-green-74bc4ccf86-r9pfn_lifestyle(f733ccfa-0f9e-11ea-af5e-467e88bd3364)"
16:16:40 kubelet[3898]: I1125 16:16:40.914295    3898 kubelet.go:2100] Failed to delete pod "lifestyle-contentservice-api-deployment-green-74bc4ccf86-r9pfn_lifestyle(f733ccfa-0f9e-11ea-af5e-467e88bd3364)", err: pod not found
16:16:40 kubelet[3898]: E1125 16:16:40.921270    3898 pod_workers.go:190] Error syncing pod f733ccfa-0f9e-11ea-af5e-467e88bd3364 ("lifestyle-contentservice-api-deployment-green-74bc4ccf86-r9pfn_lifestyle(f733ccfa-0f9e-11ea-af5e-467e88bd3364)"), skipping: failed to "StartContainer" for "lifestyle-contentservice-api" with CreateContainerConfigError: "object \"lifestyle\"/\"secret-lifestyle-contentservice-api\" not registered"
16:16:41 kubelet[3898]: W1125 16:16:41.887112    3898 pod_container_deletor.go:75] Container "3cb3517d1edbc101ec794e809dcfa90222d93d731385becd005a78b49383d6f6" not found in pod's containers
```

We can see the following in the log but not sure how to interpret on which is the cause and which is part of symptom.

* The pod has been requested to delete immediately after it’s start.
* A volume for default token secret is unmounted due to the delete.
* Container-shim was started, however immediately failed , CNI “ADD” called.
* Not able to get IP for the container due to container terminated.
* We can see there is error in StartContainer, mentioning not able to mount secret volume. (Is it causing shim-reaped?)
* `pod not found` might be benign because of cache
* `not found in pod's containers` doesn't seem to be in the same code path that lead to `TearDownPod`

Background: current code path leads to CNI DEL
* dockershim/docker_sandpox.go StopPodSandbox -> CNI.TearDownPod
* kubelet_pods.go kl.podKillingCh-> podKiller ->  killPod -> kuberuntime/kuberuntime_manager.go KillPod
* kubelet.go syncLoop-> syncLoopIteration ->  HandlePodRemoves -> deletePod -> kl.podKillingCh

**What you expected to happen**:

Even if pod sandbox fails due to some issue, we expect it to be correctly recycled and call TearDownPod.

**How to reproduce it (as minimally and precisely as possible)**:
Not yet clear, need directions to see possible causes to proceed targeted reproduction.

**Anything else we need to know?**:
#34278 seems to be a historical issue of IP leaking.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.14.8
- Cloud provider or hardware configuration: AKS
- OS (e.g: `cat /etc/os-release`): Ubuntu 16.04
- Kernel (e.g. `uname -a`): 4.15.0-1060-azure (buildd@lgw01-amd64-055) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.10)) #65-Ubuntu SMP Wed Sep 18 08:55:51 UTC 2019
- Install tools:
- Network plugin and version (if this is a network-related bug): Plugin azure-vnet-ipam version v1.0.27
- Others:

**Comment by yuzhiquan** [comment]
We meet same problem, now we have another cycle out of cluster to reuse ip, but may be should to fix this.

**Comment by tdihp** [comment]
Hi @yuzhiquan Any chance you have a way to reproduce this? We are struggling to make a lab reproduction.

**Comment by yuzhiquan** [comment]
> Hi @yuzhiquan Any chance you have a way to reproduce this? We are struggling to make a lab reproduction.

we use sr-iov cni and self-build ipam to allocate ip, ip leak is easy to reproduce, we are not find the cause yet.
k8s version: 1.16.0

**Comment by lyveng** [comment]
We are also facing the same issue. The issue is caused by a race condition between the container GC goroutine and the pod sandbox creation goroutine. We can reproduce it by adding an artificial delay in the cni plugin's cmdAdd(which gets called as part of pod sandbox creation) so that the container GC goroutine gets invoked during the pod sandbox creation and deletes the pod sandbox that is being created.
### Steps to reproduce

1. Modify the cni plugin code to do a sleep of time greater than [containerGcPeriod](https://github.com/kubernetes/kubernetes/blob/80ed28b15be5abc9b40ccfe843152d26f380221b/pkg/kubelet/kubelet.go#L1277) as the last thing in the cmdAdd function and deploy it to a k8s node
2. create a pod that gets scheduled on the k8s node
3. delete the pod immediately

You would notice that for the new pod that was created, cni plugin's cmdAdd would've been called. Whereas cmdDel wouldn't have been called even though the pod is terminated.

I went through the source code a bit to understand what is happening. Just adding my findings here in case it helps others. We are running k8s 1.15.0. I'll give references to code based on v1.15.0.
### Pod Sync Loop (optional implementation detail. can be skipped)
There is a PodSync Loop ([kubelet.go:1871](https://github.com/kubernetes/kubernetes/blob/80ed28b15be5abc9b40ccfe843152d26f380221b/pkg/kubelet/kubelet.go#L1871)) which listens on a updates channel(podConfig.updates). There is a map of sources to channels stored in podConfig.Mux.Sources. For each source in this map, a goroutine is spawned that listens on the corresponding channel and calls podStorage.Merge. The podStorage.Merge splits the updates received into adds, updates, deletes, removes and then pushes them to the updates channel that the PodSync Loop is listening on. One of the sources is API server [pkg/kubelet/config/apiserver.go](https://github.com/kubernetes/kubernetes/blob/012b085ac870d359131f4251213bf2fff1d15aa0/pkg/kubelet/config/apiserver.go#L39) which listens for updates to pods from all namespaces scheduled on the node in which kubelet is running and pushes these updates to the corresponding channel in podConfig.Mux.Sources. These updates from the API server are generally a list of pods that are then converted to updates of types add, delete, remove or update by comparing them to the locally stored state by podStorage.Merge before pushing them into the updates channel on which PodSync Loop is listening on.

### Pod Addition Flow
Now let's look at the new pod addition flow. The PodSync Loop receives an update on the updates channel of type kubetypes.ADD. 

1. [case kubetypes.Add](https://github.com/kubernetes/kubernetes/blob/80ed28b15be5abc9b40ccfe843152d26f380221b/pkg/kubelet/kubelet.go#L1889) executes inside PodSync Loop, i.e., kubelet.syncLoopIteration function
2. [kubelet.HandlePodAdditions:2058](https://github.com/kubernetes/kubernetes/blob/80ed28b15be5abc9b40ccfe843152d26f380221b/pkg/kubelet/kubelet.go#L2058)
3. [kubelet.dispatchWork:1994](https://github.com/kubernetes/kubernetes/blob/80ed28b15be5abc9b40ccfe843152d26f380221b/pkg/kubelet/kubelet.go#L1994)
4. [podWorkers.UpdatePod:221](https://github.com/kubernetes/kubernetes/blob/954996e231074dc7429f7be1256a579bedd8344c/pkg/kubelet/pod_workers.go#L221). This part is executed as a separate goroutine that listens for updates on the channel passed as an argument.
5. The actual pod update for the new pod creation is pushed to the updates channel in [pod_workers.go:226](https://github.com/kubernetes/kubernetes/blob/954996e231074dc7429f7be1256a579bedd8344c/pkg/kubelet/pod_workers.go#L226).

**[ManagedPodLoop](https://github.com/kubernetes/kubernetes/blob/954996e231074dc7429f7be1256a579bedd8344c/pkg/kubelet/pod_workers.go#L157)** - Runs as a separate goroutine as mentioned in step 4.

1. Inside [pod_workers.managedPodLoop](https://github.com/kubernetes/kubernetes/blob/954996e231074dc7429f7be1256a579bedd8344c/pkg/kubelet/pod_workers.go#L157), [podworkers.syncPodFn](https://github.com/kubernetes/kubernetes/blob/954996e231074dc7429f7be1256a579bedd8344c/pkg/kubelet/pod_workers.go#L174) is called which is nothing but kubelet.syncPod
2. A detailed explanation of what happens inside kubelet.syncPod can be found in this excellent article [what happens when k8s](https://github.com/jamiehannaford/what-happens-when-k8s/tree/4ecd5584507615cf1ee4f631866ba79f51655b23#pod-sync). The relevant part for us would be calling CRI's RunPodSandbox which in turn calls CNI's cmdAdd. After this, the init containers followed by actual containers are created and started.
3. In our case the CRI is docker_shim. When dockerService.RunPodSandbox executes successfully without any errors(setting up of the pause container, network namespace and calling cni.cmdAdd), [dockerService.setNetworkReady](https://github.com/kubernetes/kubernetes/blob/19a588eeda50ffb452c15d3017d4872b12f0d916/pkg/kubelet/dockershim/docker_sandbox.go#L121) is invoked to mark the pod sandbox's network as ready.

**Note** An important thing to note that once the actual pod creation is handed over to the Managed Pod Loop, the PodSync Loop can continue to process additional updates from the channel on which it is listening on while the work on pod creation continues asynchronously in [podWorkers.managedPodLoop](https://github.com/kubernetes/kubernetes/blob/954996e231074dc7429f7be1256a579bedd8344c/pkg/kubelet/pod_workers.go#L157)
Because of this when the pod is marked as deleted in the API server before the asynchronous managedPodLoop finishes creating the pod, the pod deletion flow is started parallelly in the PodSync Loop.

### Pod Deletion Flow
Once the asynchronous managedPodLoop starts handling the pod creation, any immediate pod delete sent to the API server will be handled by the PodSync Loop. As part of pod deletion AFAIK, only the pod status is updated and later the container GC goroutine deletes the containers and sandbox marked as deleted in the status manager(Haven't gone deep into this [code flow](https://github.com/kubernetes/kubernetes/blob/19a588eeda50ffb452c15d3017d4872b12f0d916/pkg/kubelet/dockershim/docker_sandbox.go#L254)). In our case, the cni delete that was supposed to be invoked as part of the container GC goroutine [did not get invoked](https://github.com/kubernetes/kubernetes/blob/19a588eeda50ffb452c15d3017d4872b12f0d916/pkg/kubelet/dockershim/docker_sandbox.go#L254) since dockerService.networkReady[podSandboxId] was set to false. This is set to true as part of the asynchronous managedPodLoop Step 3.
So effectively the container GC goroutine deleted the pod sandbox(the pause container) without calling the cni delete causing the IP to be leaked.

Now the question is why does the container GC goroutine pick up the pod for which cni Add has not been completed yet. Because of this it wrongly assumes that cni delete doesn't have to be called. Here is the comment from the [evictSandboxes function](https://github.com/kubernetes/kubernetes/blob/dc1ff116dccb5ea00d36f452ff121ead93fa62fd/pkg/kubelet/kuberuntime/kuberuntime_gc.go#L268) that describes the conditions on which a pod is eligible to be evicted by the container GC goroutine.
> evictSandboxes remove all evictable sandboxes. An evictable sandbox must
> meet the following requirements:
>   1. not in ready state
>   2. contains no containers.
>   3. belong to a non-existent (i.e., already removed) pod, or is not the
>      most recently created sandbox for the pod.

This bug IMO is because of this race condition between the container creation flow, container delete flow, and the container GC flow and probably would be found in all cni plugins. In our case, we use a modified version of the [bridge cni plugin](https://github.com/containernetworking/plugins/tree/1f33fb729ae2b8900785f896df2dc1f6fe5e8239/plugins/main/bridge) with a custom IPAM plugin.

I'm tagging the devs who have worked on the container GC code to get their thought on this bug - @Random-Liu, @feiskyer, @dashpole

**Comment by yuzhiquan** [comment]
@lyveng  Impressive！

**Comment by lyveng** [comment]
A colleague of mine @neerajb pointed out this PR #52864 that had introduced this bug.
The PR is for avoiding non-actionable error logs due to non-existent network namespace that gets generated when cmdDel is called multiple times.
The serialization of cni plugin execution is taken care of inside [PluginManager.SetupPod](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockershim/network/plugins.go#L403). I've thought of the following cases if the above PR was not added:

1. Pod creation goroutine has started, but the cni cmdAdd has not been reached. In between these two events, pod deletion event is processed by the main syncloop and the gc goroutine calls cni cmdDel. In this case the cni delete will fail because the namespace doesn't exist. The error would be logged and the gc goroutine will try deleting it again in the next run.
2. cni cmdAdd is being executed by the pod creation goroutine. During this time, pod deletion event is processed by the main syncloop and gc gorouting attemtps to call cni cmdDel. It will block on the pluginManager.podLock here because cni cmdDel is executing. This way cmdDel will be called after cni cmdAdd finishes executing. The pod creation goroutine would fail in subsequent steps like creating init containers or creating the pod containers and adding them to the deleted network namespace.

So effectively if the PR was not added, the race condition would've been avoided. Although non-actionable log messages would be there. I'm thinking if there would've been any other way of avoiding the log messages.

@dcbw Your thoughts?

**Comment by lyveng** [comment]
> @lyveng Impressive！

Thank You.

**Comment by lyveng** [comment]
I'm working on a fix for this issue and testing it out in our clusters. I've tested it in our clusters and it seems to work. The fix uses a mutex to avoid the race condition between the create pod(cni cmdAdd) and delete pod(cni cmdDel) flow. I'll raise a PR once I'm run the integration tests.
Is anyone aware if it would be possible to add tests for race conditions? If so can you guys point me to some example or docs so that I can add a relevant test case for this.

**Comment by lyveng** [comment]
This bug is specific to dockershim and doesn't happen in containerd. We found this when we were evaluating moving to containerd and tried reproducing this bug on containerd.

**Comment by yuzhiquan** [comment]
`CNI` code do not run in kubelet main loop, but in `CRI` implement, so it's depend on the cluster `CRI` version.

**Comment by lyveng** [comment]
Maybe this is no longer required and closed since dockershim is being deprecated - https://github.com/kubernetes/kubernetes/pull/94624

**Comment by stamm** [comment]
I tried with containerd 1.4.1, and still have obtained ip with pods which have already deleted.
Kubernetes 1.17.12, calico 3.15.1 with calico-ipam

**Comment by aojea** [comment]
> Maybe this is no longer required and can be closed since dockershim is being deprecated - #94624

> This bug is specific to dockershim and doesn't happen in containerd. We found this when we were evaluating moving to containerd and tried reproducing this bug on containerd.


/close

Feel free to reopen if you can reproduce it in an environment WITHOUT dockershim,

**Comment by tongpu** [comment]
@aojea We seem to be running into a similar issues on a kubespray based environment running containerd. Running the command from another issue (see https://github.com/kubernetes/kubernetes/issues/34278#issuecomment-832815653). Show us that we have a lot of IPs in `/var/lib/cni/networks/cbr0` that do not map to a running pod.

**Comment by aojea** [comment]
> @aojea We seem to be running into a similar issues on a kubespray based environment running containerd. Running the command from another issue (see [#34278 (comment)](https://github.com/kubernetes/kubernetes/issues/34278#issuecomment-832815653)). Show us that we have a lot of IPs in `/var/lib/cni/networks/cbr0` that do not map to a running pod.

we should open a new bug and explain the issue in detail, there are multiple components here that can show the same outcome, kubelet, cni, ...
