### ISSUE TITLE
[Failing Test] build-packages-rpms (ci-release-build-packages-rpms)

### ISSUE THREAD

**Issue by droslean** [kubernetes/kubernetes#86965]
**Which jobs are failing**:
`build-packages-rpms (ci-release-build-packages-rpms)`

**Since when has it been failing**:
`7th Jan 04:35 PST`

**Testgrid link**:
https://testgrid.k8s.io/sig-release-master-informing#build-packages-rpms

**Reason for failure**:
```console
 sed: can't read /home/builder/workspace/SOURCES/x86_64/kubelet.spec: No such file or directory 
```

**Anything else we need to know**:
/milestone v1.18
/priority critical-urgent
/cc @kubernetes/ci-signal 
/cc @kubernetes/release-managers 
/sig release

**Comment by justaugustus** [comment]
@droslean -- Yep, this is the one of the ones I was alluding to in the RT meeting.

It's failing because of a restructure of the rpm builder: https://github.com/kubernetes/release/pull/998

Will try to work on this later in the week. Worst case, early next week.
In the meantime, you can treat as not critical.

/assign
/remove-priority critical-urgent
/priority important-soon
/area release-eng

**Comment by droslean** [comment]
This is failing of a restructure of the rpm builder that happened on [k8s/release/998](https://github.com/kubernetes/release/pull/998)

**Comment by justaugustus** [comment]
This should be fixed once https://github.com/kubernetes/test-infra/pull/15871 merges.
