### ISSUE TITLE
how to get image version information from a official place?

### ISSUE THREAD

**Issue by willzhang** [kubernetes/kubernetes#87064]
i don't want to use kubeadm config images list get all images version , is there a place get it in official place?
```
[root@master ~]# kubeadm config images list
W0110 15:02:41.125312   23251 version.go:101] could not fetch a Kubernetes version from the internet: unable to get URL "https://dl.k8s.io/release/stable-1.txt": Get https://dl.k8s.io/release/stable-1.txt: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
W0110 15:02:41.125432   23251 version.go:102] falling back to the local client version: v1.16.1
k8s.gcr.io/kube-apiserver:v1.16.1
k8s.gcr.io/kube-controller-manager:v1.16.1
k8s.gcr.io/kube-scheduler:v1.16.1
k8s.gcr.io/kube-proxy:v1.16.1
k8s.gcr.io/pause:3.1
k8s.gcr.io/etcd:3.3.15-0
k8s.gcr.io/coredns:1.6.2
```

**Comment by neolit123** [comment]
/area kubeadm

for release `x.yy` the control plane and kube proxy are also `x.yy`
the rest - coredns and etcd can be found here:
https://github.com/kubernetes/kubernetes/blob/release-1.17/build/dependencies.yaml

but the tags for etcd can end up with revisions that we do not document - e.g. tag `3.4.3-0` instead of `3.4.3`

here is where the images are stored:
https://console.cloud.google.com/gcr/images/google-containers/GLOBAL

> i don't want to use kubeadm config images list get all images version

kubeadm is your best option to get the tags of these images...
if you specify the version like `kubeadm config images list --kubernetes-version v1.17.0` it will remove the warnings too:
> W0110 15:02:41.125312   23251 version.go:101] could not fetch a Kubernetes version from the internet: unable to get URL "https://dl.k8s.io/release/stable-1.txt": Get https://dl.k8s.io/release/stable-1.txt: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
> W0110 15:02:41.125432   23251 version.go:102] falling back to the local client version: v1.16.1

/close
