### ISSUE TITLE
unable to modify StatefulSet's podManagementPolicy to Parallel?

### ISSUE THREAD

**Issue by biello** [kubernetes/kubernetes#87227]
it seems that I cannot change StatefulSet's podManagementPolicy to Parallel by kubectl edit, is this an expected behavior?

**Comment by biello** [comment]
my k8s version is 1.12，'podManagementPolicy: Parallel' should be supported above 1.7

**Comment by biello** [comment]
/triage/support

**Comment by biello** [comment]
I suppose that the docs should point out this behavior if podManagementPolicy of StatefulSet cannot be modify after creation.

**Comment by f2003495** [comment]
Is it possible to add this in kubernetes documentation? we tried to change the value in the next release but upgrade failed with the below error:

Error: UPGRADE FAILED: release podXXXX failed, and has been rolled back due to atomic being set: cannot patch "podXXX" with kind StatefulSet: StatefulSet.apps
 "podXXX" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', 'updateStrategy', 'persistentVolumeClaimRetentionPolicy' and 'minReadySeconds' are forbidden
