### ISSUE TITLE
Automatically remove labels from node on restart

### ISSUE THREAD

**Issue by inoam** [kubernetes/kubernetes#87288]
**What would you like to be added**:

Ability to automatically remove label from node after reboot.

**Why is this needed**:
Consider the following scenario:
I want to schedule pods on node only after some initiation action is done (in this case, mounting shared volume).
The method I use is having some "nodeman" daemonset, that label the node with "application_ready" after performing the operation.
All other pods  require this label (with nodeAffinity), such that only if it is satisfied, they can be scheduled.
The problem occurs when rebooting node, the label still exists, but the initiation action might be required again. 
Some case I could solve with initContainers - which could wait for condition to happen. But in case of mount for example, after pod is already scheduled before other "init pod" mounted the volume, then pod must be re-scheduiled for the mount to take effect.

**Comment by inoam** [comment]
/sig/node
/sig/scheduling

**Comment by inoam** [comment]
@liggitt : 

1. Could you please elaborate what is the tag you added? 
2. Is there any information I can add here?

**Comment by liggitt** [comment]
That tag is added to feature requests that have not yet been accepted by the owning sig, usually due to insufficient evidence that the use cases it would solve are high enough priority or apply broadly to many uses. If you want this to make progress, I would recommend engaging with sig-node to get feedback on the idea, and participate in proposing the idea officially in a [Kubernetes Enhancement Proposal](https://github.com/kubernetes/enhancements/tree/master/keps/).
