### ISSUE TITLE
Use kube DNS server from Kubelet / Node

### ISSUE THREAD

**Issue by idosh** [kubernetes/kubernetes#8735]
I tried to run the nfs example but the kubelet service couldn't resolve the host ip of nfs-server.default.kube.local.
Running ping from a pod resolves the same address successfully.

**Comment by thockin** [comment]
By default the node can not access the DNS server unless you tell her to
the exact DNS server. This is not working deal, but it's tricky to get our
name server line into  resolv.conf on so many platforms. I spent a bit of
time looking at dnsmasq today, but that still requires configuring your
resolv.conf.

Ideas wanted...

**Comment by ddysher** [comment]
I reached this while trying to setup a private registry.  Basically, allow docker on each node to be able to pull from image "kube-registry.default.cluster.local/myimage".  There are other workaround, but being able to reach kube dns server is definitely a win.

What's the problem of configuring resolve.conf based platform?   I think we have a support matrix right, so it shouldn't be too hard to add support to suppported platform?

Could our old friend iptable helps here?  something like 
```sudo iptables -t nat -A OUTPUT -p udp --dport 53 -j DNAT --to-destination our-dns-server```
where our dns server will fallback to 8.8.8.8 etc.  But iirc, you have to make sure dnsmasq is disabled, which sounds like platform dependent :(

**Comment by thockin** [comment]
We want less host-OS-specific tweaks, not more.  Running dnsmasq seems like
a plausible way to get nodes using the cluster DNS, but details TBD.

**Comment by pwais** [comment]
I also ran into this problem trying to run a docker private registry.  The problem of getting nodes to use cluster DNS is indeed pretty complicated.  FWIW on GCE I noticed that setting up salt to modify resolv.conf was a bad idea since k8s needs host DNS on cluster startup time (e.g. before k8s skydns is even started).

However, this Github issue and the docker registry issue perhaps deal more specifically with the kubelet?  Since the kubelet is aware of cluster DNS, couldn't it just prefer that service (programmatically perhaps?) over host DNS resolution for k8s functionality (e.g. images, volumes, etc) if the cluster DNS add-on is available / --cluster-dns is specified?

**Comment by thockin** [comment]
I have no idea how to get Go code to use a DNS server of my choosing,
rather than standard resolver.  One option is to assign a known clusterIP
to your registry Service, and either use that IP or add it to /etc/hosts.

I think there's a relatively easy solution to use dnsmasq on nodes, but no
time to prototype it just now.

**Comment by pwais** [comment]
Looking at the Kubelet code, it looks like the Kubelet (at the time of writing) interfaces to Docker using (mainly) Docker's standard go client, which talks to the host's Docker daemon (which uses host DNS resolution).  So we probably can't just modify the Kubelet go app to use cluster DNS for pulling Docker images.  I'm not sure how the new k8s volume features work, but clearly no host NFS client will be able to use cluster DNS simply via the Kubelet.

Yea, sounds like dnsmasq is probably the best way to 'bridge' cluster and host DNS.  And yea it would be nice to avoid "host-OS-specific tweaks," but that sort of integration work has thankfully already been done by the dnsmasq maintainers :)

**Comment by thockin** [comment]
So it would be a nice project for someone (hint) to build a dnsmasq
container that runs dnsmasq, forwarding to the cluster DNS server by an env
var or flag.  Use salt to inject the DNS_SERVER into the flags for a
dnsmasq.yaml file that gets dropped on every node.  You could use host
networking since all you are doing is claiming host's port 53.  I'm not
sure if 'localhost' is implicitly tried as part of DNS or not, though...

**Comment by ddysher** [comment]
Sounds very interesting, will try to find some time to play around.  

Not assigning myself though, got fully occupied recently :(

**Comment by ddysher** [comment]
It seems that localhost is not implicitly tried.

I've started a dnsmasq container on localhost, with the simplest config:
```
listen-address=127.0.0.1
bind-interfaces
user=root

no-resolv
server=10.0.0.10
```

I can't reslove kube services:
```
$ host kubernetes.default.svc.cluster.local 
Host kubernetes.default.svc.cluster.local not found: 3(NXDOMAIN)
```

But I can resolve if using localhost explicitly:
```
$ host kubernetes.default.svc.cluster.local localhost
Using domain server:
Name: localhost
Address: 127.0.0.1#53
Aliases: 

kubernetes.default.svc.cluster.local has address 10.0.0.1
```

I'm using GCE, resolve.conf has the following content. it works if I added localhost explicitly
```
domain c.lucid-walker-725.internal.
search c.lucid-walker-725.internal. 344740857756.google.internal. google.internal.
#  nameserver 127.0.0.1   works if this line is added, of course
nameserver 169.254.169.254
nameserver 10.240.0.1
```

**Comment by thockin** [comment]
yeah, short of configuring resolv.conf on nodes, I have not found a good answer, nor have I found a good answer to configuring resolv.conf.,..

**Comment by ddysher** [comment]
Yeah, that's no difference than setting dns service in resolv.conf.....

Sounds like we have to look at how to configure resolve.conf reliably.

**Comment by four43** [comment]
This is an older issue, but still open so I'll comment. Regarding the title, about resolving addresses, using v1.1.0-beta

I found this extremely helpful: https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/dns#how-do-i-test-if-it-is-working

I was able to poke around at what pods could resolve. Instead of `nfs-server.default.kube.local` I found that simply `nfs-server` resolved properly for me.

**Comment by thockin** [comment]
`nfs-server.default.kube.local` is incorrect

Assuming you changed the default `cluster.local` to `kube.local`, you want
`nfs-server.default.svc.kube.local`

**Comment by four43** [comment]
@thockin - Thanks for the info, that works for me when resolving with the busybox test container. 

This does NOT seem to work when trying to reference an NFS share as a volume however. That sounds like a different issue, however.

**Comment by thockin** [comment]
That's right.  The node itself does not have a DNS nameserver pointer to
the kube DNS service.  That turns out to be way more complex.  This impacts
any service that we want to run on kube and use from nodes (NFS, other
storage, docker registry, etc).

**Comment by four43** [comment]
That kind of throws a wrench into that workflow. Since services are supposed to always point at a corresponding pod, is there another way to reference that pod? Use case being: Need to share persistent storage across pods without copying to each pod. But if the host NFS pod moves, it sounds like Kubernetes won't resolve that.

**Comment by thockin** [comment]
The only answers so far are to use a known IP for the service (which is
what we do for DNS) and optionally program each machine's /etc/hosts with
that known IP and a name for it, or else use a local proxy on every machine
(which is what we do for docker registry)

**Comment by four43** [comment]
Sounds good, thanks for the tip @thockin
