### ISSUE TITLE
How can I update secrets dynamically without recreating the pod?

### ISSUE THREAD

**Issue by idosh** [kubernetes/kubernetes#8738]

**Comment by lavalamp** [comment]
@erictune or @deads2k, do we have a plan for triggering a secret change on a pod? How would we notify the pod that the secret has changed?

**Comment by pmorie** [comment]
We still need to define the secrets update story.  Right now, the plugin is idempotent but you'll get the latest state if your node has been rebooted.

There are two parts to solving this:

1.  Changing the plugin to store the last resourceVersion of the secret written and project a newer version when it's available -- there's some overlap with the #5093 volume plugin story here since we would want updates to be atomic.
2.  Making the kubelet aware that a pod should be restarted; it seems like whether your pod is restarted should potentially be a knob to the user.  Some containers may watch the filesystem and be able to respond to changes in secrets in volumes.

**Comment by pmorie** [comment]
Secrets update also touched by #7648

**Comment by liggitt** [comment]
I thought the latest data in the secret got pulled on every pod create. Didn't realize the node only grabbed the secret the first time it was mounted.

**Comment by pmorie** [comment]
Our original design had them being immutable

**Comment by lavalamp** [comment]
I would kinda expect some sort of rotation story rather than direct mutation. But I guess it's nice to support both?

**Comment by pmorie** [comment]
By direct mutation, do you mean having the volume plugin implement some
kind of eventual consistency without restarting the pod?

**Comment by thockin** [comment]
I think we can and probably should implement updates for secrets, atomic in
the same way as downward API should be.  We can add a file that is a
notifier of some sort (design TBD but not very complicated).

Something like a special file we update when a new resourceVersion of the
sercret is written.

Whether this lands before 1.0 is dubious.

**Comment by erictune** [comment]
I don't see this in 1.0

**Comment by pmorie** [comment]
Agree, this should not be a 1.0 item (fwiw)

**Comment by bgrant0607** [comment]
See also #18372

**Comment by thockin** [comment]
This is in.
