### ISSUE TITLE
bad/missing data in Event involvedObject

### ISSUE THREAD

**Issue by travisghansen** [kubernetes/kubernetes#87434]
**What happened**:

I'm attempting to use an `Events` watcher to better re-act to cluster modifications. I've got an `CRD` resource that looks like this using a standard `get`:

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
...
```
The `involvedObject` for respective `Event`s however is represented as such:

```
  involvedObject:
    apiVersion: v1alpha1
    kind: Application
    ...
```

Of note is the discrepancy and loss of information in the `involvedObject`.

**What you expected to happen**:

I would expect the `involvedObject` to follow convention.

**How to reproduce it (as minimally and precisely as possible)**:

I'm not sure if this is only scoped to `CRD`s or what but simply doing a `GET` on the resource and any related `Event` should do.

**Anything else we need to know?**:

It would be ideal if the `involvedObject` simply contained the same data/format/structure as resources speaking generally:

```
involvedObject:
  apiVersion: <foo>
  kind: <bar>
  metadata:
    ...
```

Of particular use/note would be including the `selfLink` of the object as well. The use case would be to systemically react to the event using the rest API. To reconstruct the URL/endpoint for the `involvedObject` as is would be error prone and cumbersome.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.16
- Cloud provider or hardware configuration: bare metal, rancher's rke
- OS (e.g: `cat /etc/os-release`): centos host nodes
- Kernel (e.g. `uname -a`): 3.18, 4.4
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by fedebongio** [comment]
/cc @logicalhan 
who volunteered to dig more to understand the use case

**Comment by liggitt** [comment]
How was the event created?

**Comment by travisghansen** [comment]
That's a good question. I never considered the producer of the event would be responsible for how that data is structured/created. Let me dig through the code and ask the Argo folks I guess.

Does the interface to creating events not simply take a reference for the `involvedObject`?

**Comment by travisghansen** [comment]
Looks like it's here: https://github.com/argoproj/argo-cd/blob/0675ff2fb25fe97856171230f150e6ba5a2563d5/util/argo/audit_logger.go#L75

**Comment by liggitt** [comment]
Events are just API objects, which don't do cross object validation at the API level, so someone is free to record an event with an API version or group that does not exist. That said, if the event was created using the client-go helpers, I would have expected the apiVersion to be extracted correctly from the provided object and recorded in the event.

**Comment by travisghansen** [comment]
Go is not my strength so I'm not sure how to read whether it's using the client or not. I'd assume so.

What's the likelyhood  of getting `selfLink` added to the struct?

**Comment by liggitt** [comment]
> Go is not my strength so I'm not sure how to read whether it's using the client or not. I'd assume so.

It is constructing the event itself, not using the helper that populates the fields from an object instance. 

> What's the likelyhood of getting selfLink added to the struct?

Not likely, given https://github.com/kubernetes/enhancements/blob/master/keps/sig-api-machinery/20190711-remove-selflink.md

Since this issue appears to have been caused by an external client's use of the API, I'll go ahead and close this issue and recommend filing an issue against that project to populate a more usable value there. 

/close

**Comment by travisghansen** [comment]
@liggitt ouch, I really don't like that kep :( unless there's some alternative API endpoint that can be used to generate the link given the standard data from kind/version/etc. Is there some forum/discussion on that or is it a done deal?

Regardless, can you point to a valid example that I can share with the Argo folks for the 'correct' way to generate the event data using the helpers?

**Comment by liggitt** [comment]
> @liggitt ouch, I really don't like that kep :( unless there's some alternative API endpoint that can be used to generate the link given the standard data from kind/version/etc. 

You can use information from the discovery API to determine the API endpoint for a particular group/version/kind. That's what the discovery-based implementations of the RESTMapper interface do:

```go
discoveryClient := cacheddiscovery.NewMemCacheClient(clientset.Discovery())
discoveryRESTMapper := restmapper.NewDeferredDiscoveryRESTMapper(discoveryClient)
mapping, err := discoveryRESTMapper.RESTMapping(schema.GroupKind{Group:"mygroup",Kind:"MyKind"}, "myversion")
if err != nil {
...
}
mapping.Resource holds the discovered API group, version, and resource you can use with the dynamic client
```

> Is there some forum/discussion on that or is it a done deal?

The selfLink field has been fairly problematic and has had minimal use. Since the information needed to construct URLs is available via discovery, I wouldn't anticipate that use case motivating keeping selfLink around.

> Regardless, can you point to a valid example that I can share with the Argo folks for the 'correct' way to generate the event data using the helpers?

If the object you are working with has APIVersion and Kind populated, mimicking the event recorder would work:

https://github.com/kubernetes/kubernetes/blob/dcd0755f84bf8c15fd21e8d697b924991f641ae4/staging/src/k8s.io/client-go/tools/reference/ref.go#L59
https://github.com/kubernetes/kubernetes/blob/dcd0755f84bf8c15fd21e8d697b924991f641ae4/staging/src/k8s.io/client-go/tools/reference/ref.go#L79-L80
https://github.com/kubernetes/kubernetes/blob/dcd0755f84bf8c15fd21e8d697b924991f641ae4/staging/src/k8s.io/client-go/tools/reference/ref.go#L92-L93

**Comment by travisghansen** [comment]
@liggitt fair enough, thanks for sharing all the detail and the help!
