### ISSUE TITLE
[Failing Test] gce-master-scale-correctness: [sig-storage] Detaching volumes should not work when mount is in progress

### ISSUE THREAD

**Issue by oxddr** [kubernetes/kubernetes#87815]
**Which jobs are failing**:
gce-master-scale-correctness

**Which test(s) are failing**:
[sig-storage] Detaching volumes should not work when mount is in progress [Slow]

**Since when has it been failing**:
02/04

**Testgrid link**:
https://k8s-testgrid.appspot.com/sig-release-master-informing#gce-master-scale-correctness

**Reason for failure**:
```
Unexpected error:
    <*errors.errorString | 0xc0024bc5d0>: {
        s: "error waiting for volume flexvolume-k8s/attachable-with-long-mount-flexvolume-6544/test-long-detach-flex to attach to node gce-scale-cluster-minion-group-2-j1r2: timed out waiting for the condition",
    }
    error waiting for volume flexvolume-k8s/attachable-with-long-mount-flexvolume-6544/test-long-detach-flex to attach to node gce-scale-cluster-minion-group-2-j1r2: timed out waiting for the condition
```

**Anything else we need to know**:

/sig storage
/priority critical-urgent
/assign @saad-ali

**Comment by verult** [comment]
The attach op for the test driver simply returns success, so it's surprising attach timed out.

This test has a unique volume name ("test-long-detach-flex"), so the attach operation should be performed in parallel with volume operations from other tests run at the same time. But depending on how many volume operations are happening in parallel, maybe available resources to run goroutines is getting starved? If this were true, it would be surprising to see this test failing multiple times in a row.

@oxddr how many times has this failed so far? In https://k8s-testgrid.appspot.com/sig-release-master-informing#gce-master-scale-correctness looks like it's only been 1 failure, and it's green again on 2/6

As a side note, Flexvolume tests aren't running in any GCE testgrids I could find. They are getting skipped because SSH keys to access nodes are missing

**Comment by oxddr** [comment]
/kind flake

@verult There was a single failure of this test. However please note gce-master-scale-correctness is an expensive test to run and we should strive to deflake as much as possible. Otherwise the signal it provides would be weaker.

**Comment by verult** [comment]
ACK. Created an issue to make sure Flexvolume tests are running in the regular test suites: https://github.com/kubernetes/kubernetes/issues/88132

Since the test has only flaked once, I think the priority should be longterm. WDYT?

I can't find the test in https://k8s-testgrid.appspot.com/sig-release-master-informing#gce-master-scale-correctness anymore. Where did it go?

**Comment by hasheddan** [comment]
@oxddr Is this issue still outstanding? I also cannot find the referenced test

**Comment by oxddr** [comment]
Assuming https://github.com/kubernetes/kubernetes/issues/88132 is a resolution to this flake, then I think it's fine to close this issue. 

/close

**Comment by hasheddan** [comment]
Thanks @oxddr :)
