### ISSUE TITLE
Remove PodBackoffMap

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes/kubernetes#87832]
The PodBackoffMap (pkg/scheduler/internal/queue) is used to calculate backoff for pods.
This structure is cleaned up periodically, losing backoff information. We added a mitigation #87616 which is being backported down to 1.15
However, there are still cases were a backoff for a pod will be lost (such as when a cluster doesn't change much). But, as noted in the PR discussion, we don't need the Map anymore, as the information is stored in PodInfo. We just need the helper method that calculates the backoff from the last schedule attempt and number of retries.

#78849 was going in this direction, but it is now stalled.

/sig scheduling
/good-first-issue

**Comment by notpad** [comment]
@alculquicondor To my understanding, we will remove the data stored in PodBackOffMap, and the PodBackOffMap can be refactored as something like:

```
type PodBackoff struct {
	// initial backoff duration
	initialDuration time.Duration
	// maximal backoff duration
	maxDuration time.Duration
}
```

Is this what you expected?

But after that podBackoff.GetBackoffTime can not check if a pod is inside the podBackoff structure, so the value of "exists" won't be false, this will cause some tests in scheduler_queue_test.go to be failed. There are many places in the test in which `movePodsToActiveOrBackoffQueue` was assumed to move all pods to active queue because pod info doesn't exist in the old podBackoffMap structure, after this change, `movePodsToActiveOrBackoffQueue` actually move all pods to backoff queue.

```
func (p *PriorityQueue) isPodBackingOff(pod *v1.Pod) bool {
	boTime, exists := p.podBackoff.GetBackoffTime(nsNameForPod(pod))
 	if !exists {
 		return false // this won't return false now and cause pod to be moved to backoff queue
 	}
 	return boTime.After(p.clock.Now())
 }
```

**Comment by alculquicondor** [comment]
yes, the PodBackoff struct would just have global configuration. It doesn't need any other information. Everything should accept `PodInfo`, instead of `v1.Pod`. `PodInfo` has the last attempt timestamp and number of attempts.

At the end of the day, every pod that doesn't get scheduled will be "backing off", just with different timeouts.

**Comment by alculquicondor** [comment]
> after this change, movePodsToActiveOrBackoffQueue actually move all pods to backoff queue.

Not true, because the timeout might have passed already :)

**Comment by notpad** [comment]
Thanks @alculquicondor for the confirmation. I have sent a PR.
