### ISSUE TITLE
Mask secrets in kubectl diff output

### ISSUE THREAD

**Issue by loozhengyuan** [kubernetes/kubernetes#87840]
**What would you like to be added**:
Even though secrets are encoded when displayed in the `kubectl diff`, it will be helpful if they can be fully masked so its output can be displayed publicly.

**Why is this needed**:
The `kubectl diff` command is incredibly useful for 'previewing' changes before applying, especially when used in deployment pipelines where we can preview exactly what the changes are. However, if they are exposing the sensitive data, then they are not safe to be displayed in CI/CD pipelines.

An alternative I am using now is running `kubectl apply --server-dry-run`, but it only tells if a resource will be changed and not what will be changed.

**Comment by julianvmodesto** [comment]
cc @apelisse

**Comment by loozhengyuan** [comment]
I thought it would be helpful if I further elaborate the desired outcome of this feature.

Currently, say if I were to [create a Kubernetes secret using Kustomize](https://kubernetes.io/docs/concepts/configuration/secret/#generating-a-secret-from-string-literals), I will run the following command:

```sh
cat <<EOF >./kustomization.yaml
secretGenerator:
- name: db-user-pass
  literals:
  - username=admin
  - password=secret
EOF
```

However, as part of my CI/CD pipeline, I intend to preview all changes before they actually get applied.

**Current Situation**

As mentioned in the opening post, the `kubectl apply --server-dry-run` is insufficient because it does not tell exactly which lines are changing. As such, when I run `kubectl diff`, this is what I get:

```diff
$ kubectl diff -k .                 
diff -u -N /tmp/LIVE-378076332/v1.Secret.default.db-user-pass-dddghtt9b5 /tmp/MERGED-271880731/v1.Secret.default.db-user-pass-dddghtt9b5
--- /tmp/LIVE-378076332/v1.Secret.default.db-user-pass-dddghtt9b5       2020-02-16 19:25:36.979281145 +0800
+++ /tmp/MERGED-271880731/v1.Secret.default.db-user-pass-dddghtt9b5     2020-02-16 19:25:37.011281827 +0800
@@ -0,0 +1,12 @@
+apiVersion: v1
+data:
+  password: c2VjcmV0
+  username: YWRtaW4=
+kind: Secret
+metadata:
+  creationTimestamp: "2020-02-16T11:25:37Z"
+  name: db-user-pass-dddghtt9b5
+  namespace: default
+  selfLink: /api/v1/namespaces/default/secrets/db-user-pass-dddghtt9b5
+  uid: fd6b3c64-5216-45e5-994c-737fbbfe771c
+type: Opaque
exit status 1
```

Evidently, if this is displayed in CI pipeline logs, then anyone is able to decode `c2VjcmV0` to know that the password is the literal `secret`.

**Desired Outcome**

This desired outcome draws inspiration from how Travis CI and GitHub Actions currently masks secrets from their output. Travis CI masks secrets by displaying a `[secret]` placeholder while GitHub Actions does so by using asterisks. Any implementation should work fine, but for the sake of illustrating the desired outcome, asterisks are shown below:

```diff
$ kubectl diff -k .                 
diff -u -N /tmp/LIVE-378076332/v1.Secret.default.db-user-pass-dddghtt9b5 /tmp/MERGED-271880731/v1.Secret.default.db-user-pass-dddghtt9b5
--- /tmp/LIVE-378076332/v1.Secret.default.db-user-pass-dddghtt9b5       2020-02-16 19:25:36.979281145 +0800
+++ /tmp/MERGED-271880731/v1.Secret.default.db-user-pass-dddghtt9b5     2020-02-16 19:25:37.011281827 +0800
@@ -0,0 +1,12 @@
+apiVersion: v1
+data:
+  password: **********
+  username: **********
+kind: Secret
+metadata:
+  creationTimestamp: "2020-02-16T11:25:37Z"
+  name: db-user-pass-dddghtt9b5
+  namespace: default
+  selfLink: /api/v1/namespaces/default/secrets/db-user-pass-dddghtt9b5
+  uid: fd6b3c64-5216-45e5-994c-737fbbfe771c
+type: Opaque
exit status 1
```

With the above, we can now show diff changes before applying them as part of our CI/CD deployment workflows.

**Comment by julianvmodesto** [comment]
@loozhengyuan this is probably a concern delegated to application-layer secrets encryption, since masking output is not provided in our types, by the apiserver nor any client utilities including kubectl and client-go, and any other languages.

What distribution of Kubernetes are you using? If it’s a cloud distribution, does it support a KMS plugin?

- [Kubernetes KMS plugins](https://kubernetes.io/docs/tasks/administer-cluster/kms-provider/)
- [GCP KMS plugin](https://cloud.google.com/kubernetes-engine/docs/how-to/encrypting-secrets)
- [AWS KMS plugin](https://github.com/kubernetes-sigs/aws-encryption-provider/blob/master/README.md)

**Comment by apelisse** [comment]
A few thoughts that I have, some from talking with @justinsb.
- It's not super interesting to show differences between two base64,
- One can probably do it with scripting until there is stronger evidence that this is needed,
- We could create a flag to choose which types to skip and/or skip secrets by default,
- I think it might have value to show new/old keys, but also if the password has changed
- Since diff(1) is computing the diff, we can't replace the base64 with stars before sending it to diff, or it will never show any difference,
- We could hash the password and diff the hashed passwords, but that's still a "risk"

**Comment by loozhengyuan** [comment]
@julianvmodesto I am running the cluster on GKE, so recently I took some time to implement [Application-layer Secrets Encryption](https://cloud.google.com/kubernetes-engine/docs/how-to/encrypting-secrets) as per your suggestion. Unfortunately, even though the secrets are encrypted-at-rest in `etcd`, they [are decrypted when I access them](https://kubernetes.io/docs/tasks/administer-cluster/encrypt-data/#verifying-that-data-is-encrypted) via kubectl. This means to say that, as of current, implementing Application-layer Secrets Encryption will not have any impact on this issue because running `kubectl diff` would compute the diff against a _decrypted_ secret anyway.

**Comment by loozhengyuan** [comment]
@apelisse Thanks for sharing your thoughts on this. Though I don't think there is a good way to handle this, I think that implementing a flag would at least make `kubectl diff` safe for use in CI/CD pipelines. Even if secrets diffs are suppressed, I can combine with the use of `kubectl apply --server-dry-run` to determine if a secret is expected to be changed in that run or otherwise.

**Comment by apelisse** [comment]
We could possibly add a parameter `--exclude` which would take GVKs (or a simplified form) of types that we want to ignore?

**Comment by apelisse** [comment]
I'm actually happy with https://github.com/kubernetes/kubernetes/issues/87840#issuecomment-586696631 now :-)

The only thing is that we need to make "*********" different in before and after, possibly by appending a different string in both, maybe "(before)"/"(after)" so that diff(1) catches the difference.

If anyone wants to try to implement it, I'd be happy to review the change!

**Comment by SEAPUNK** [comment]
I assume we have to type that bot command to keep this issue open?

/remove-lifecycle stale

**Comment by loozhengyuan** [comment]
@apelisse Do we intend to append `before`/`after` even if there is no change? If not, does that means we need to find out which value has changed _before_ appending and sending it to `diff(1)`?

**Comment by apelisse** [comment]
We have to special case secrets and actually compare the values here so
that we can specifically output something different for diff. So I think
that’s a yes to your second question.

I understand that this is not going to extend well to CRDs and other types
that might contain possibly sensitive information, but I don’t think we
have enough information to build something more robust/general right now.

**Comment by apelisse** [comment]
@loozhengyuan Can I do something to help you get this through?

**Comment by szpak** [comment]
It still would be useful.

/remove-lifecycle stale
