### ISSUE TITLE
isolcpus and --reserved-cpus don't work as expected

### ISSUE THREAD

**Issue by pikrzysztof** [kubernetes/kubernetes#87862]
Release notes from 1.17 says:
> A new kubelet command line option, --reserved-cpus, is introduced to explicitly define the CPU list that will be reserved for system. For example, if --reserved-cpus=0,1,2,3 is specified, then cpu 0,1,2,3 will be reserved for the system. On a system with 24 CPUs, the user may specify isolcpus=4-23 for the kernel option and use CPU 4-23 for the user containers

I've got an 8-core, bare-metal machine running k8s 1.17.2 and kernel 5.3.0-24-generic (ubuntu).

I'm configuring kubelet like this:
```
reservedCpus: 0
kubeReserved:
  cpu: "100m"
  memory: 250Mi
systemReserved:
  cpu: "0.5"
  memory: "7Gi"
```

Three test cases:

**Test case 1:** `isolcpus=1-7`
`taskset -c -p $(pidof dockerd)` prints 0. 
`taskset -c -p $(pidof my-process-in-a-burstable-container)` prints 0,2-7.
taskset asked about a container with resources.requests={cpu: 1, mem: 100Mi} resources.limits={cpu: 1, mem: 100Mi} prints 1.

The only way to schedule something on isolated core is to have a Guaranteed QoS container requesting integer number of cores. That would make some sense if not...

**Test case 2:** `isolcpus=5-7`
`taskset -c -p $(pidof dockerd)` prints 0-4
`taskset -c -p $(pidof my-process-in-a-burstable-container)` prints 0,2-7.
taskset asked about a container with resources.requests={cpu: 1, mem: 100Mi} resources.limits={cpu: 1, mem: 100Mi} prints 1.

We could've scheduled this pod on isolated cores but cpumanager won't do it... That's why test case 1 doesn't make sense.

**Test case 3:** `isolcpus=0`
`taskset -c -p $(pidof dockerd)` prints 1-7
`taskset -c -p $(pidof my-process-in-a-burstable-container)` prints 0,2-7.
taskset asked about a container with resources.requests={cpu: 1, mem: 100Mi} resources.limits={cpu: 1, mem: 100Mi} prints 1.

In all cases cpumanager reports `policy_static.go:110] [cpumanager] reserved 1 CPUs ("0") not available for exclusive assignment`. I am wiping cpu_manager_state file every kubelet restart/reboot and I am restarting docker every time I try something new to ensure that there are no lingering containers. 

**What you expected to happen**:

I'd expect k8s to run system daemons on core 0, and other deployments on the rest of the cores, effectively guaranteeing that docker/syslog/... will not pollute cache on cores running latency-critical processes.

**Environment**:
- Kubernetes version (use `kubectl version`): Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:22:30Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration: 
- OS (e.g: `cat /etc/os-release`):
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
- Kernel (e.g. `uname -a`): Linux hex-8c4-pm 5.3.0-24-generic #26~18.04.2-Ubuntu SMP Tue Nov 26 12:34:22 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by marquiz** [comment]
AFAIU kubelet does not take into account `isolcpus` in any way. Thus, whatever you specify there does not have any effect on how workloads are allocated. It looks like you had `--reserved-cpus=1` because that cpu was removed from the cpuset of you container. Otherwise it looks like kubelet behaves as it should.

**Comment by pikrzysztof** [comment]
Thank you for your answer. I'm not sure I understand the current documentation.
 
If `isolcpus` is ignored by kubelet then why is it mentioned in the release notes? I think the documentation should be more explicit on how is this related to 1.17 and `--reserved-cpus`.

Core number 1 was assigned to the container with `resources.requests={cpu: 1, mem: 100Mi} resources.limits={cpu: 1, mem: 100Mi}`. This happened in all three cases. That's why core 1 never belongs to a burstable pod's cpuset. What's confusing me is that this core was still in the system daemons' (ex. dockerd) cpuset. I'm not sure how `--reserved-cpus` is better than `kubeReserved` and `systemReserved`?

**Comment by marquiz** [comment]
> If `isolcpus` is ignored by kubelet then why is it mentioned in the release notes? I think the documentation should be more explicit on how is this related to 1.17 and `--reserved-cpus`.

The documentation is probably a bit misleading. I think `isolcpus` was mentioned to highlight that this way you could ensure that nothing gets scheduled on these cores (except for possibly some kernel rcu callback threads) unless explicitly pinned on those. I don't think that this is necessarily optimal, in general, because those cores are removed from the kernel scheduler load balancing. This means that the workload needs to handle this (cpu affinity) by itself. It is not a problem if only one cpu is reserved for the workload. But, with more cpus all threads of the workload run on a single core, by default, if the workload does not set the cpu affinity by itself.

> What's confusing me is that this core was still in the system daemons' (ex. dockerd) cpuset. I'm not sure how `--reserved-cpus` is better than `kubeReserved` and `systemReserved`

With `--reserved-cpus` you can explicitly specify a list of cpu numbers that will be reserved for system and kube threads. By default, kubelet does not try to enforce (i.e. configure) the system or kube cgroups. You should be able to achieve this by specifying `--system-reserved-cgroup=<cgroup path>`, `--kube-reserved-cgroup=<cgroup path>` and `--enforce-node-allocatable=pods,system-reserved,kube-reserved` settings. To be hones, I haven't tried this setup myself 😬

**Comment by pikrzysztof** [comment]
OK, I got it running. It seems that all the  `--reserved-cpus` flag does is telling the static scheduler not to grant exclusive cores from the pool specified by this flag. It won't rearrange any processes that are already running.

This is useful only if you schedule all system daemons on the cores specified by `--reserved-cpus`, for example by providing systemd with CPUAffinity flag.

No need to specify `--system-reserved-cgroup` or `--enforce-node-allocatable`. In fact, I think one of this flag conflicts with `--reserved-cpus`.

Thank you for your help.
