### ISSUE TITLE
Tests in selinux security_context are failing

### ISSUE THREAD

**Issue by gnufied** [kubernetes/kubernetes#87901]
Tests in https://testgrid.k8s.io/google-gce#gci-gce-flaky&sort-by-flakiness=&width=20&include-filter-by-regex=SELinux are failing because they are faulty.

A container can't read from a file if it has selinux permission denied for it.

More context - https://github.com/kubernetes/kubernetes/pull/87658#issuecomment-582407413

/sig node
/sig storage

**Comment by mrunalp** [comment]
@haircommander @umohnani8 something we can look into.

**Comment by mrunalp** [comment]
Also, @kolyshkin

**Comment by jsafrane** [comment]
The tests expect that SELinux blocks a pod with label "s0:c2,c3" reading a file created by a pod with label "s0:c0,c1". Since the test runs on GCI, where SELinux is not available, nothing blocks the read and the test can't ever pass.

The test should check that the node has SELinux in Enforcing mode and skip the test otherwise. Somewhere around these parts, where we write/read a file in the first "s0:c0,c1" pod:
https://github.com/kubernetes/kubernetes/blob/25651408aeadf38c3df7ea8c760e7519fd37d625/test/e2e/node/security_context.go#L220

Is there an easy way how to test that in /proc or /sys in a non-privileged busybox container?

**Comment by gnufied** [comment]
There are two problems. First one is obviously - the test can't run on non-selinux systems, but second one is - it is also broken on selinux enabled systems as per https://github.com/kubernetes/kubernetes/pull/87658#issuecomment-582407413

**Comment by kolyshkin** [comment]
> Is there an easy way how to test that in /proc or /sys in a non-privileged busybox container?

To check whether SELinux is in enforced mode, one can check that read `/sys/fs/selinux/enforce` returns "1". I've implemented that in a particular case that relies on selinux being enforced: https://github.com/kubernetes/kubernetes/pull/88247/commits/70a28579988915a7832118aa199ab713e05c696b#diff-d396c518f484bf943b4f92eec90c708bR273

To check whether SELinux is enabled (I guess this is a prerequisite for all the test cases in `test/e2e/node/security_context.go`), one can use `SELinuxEnabled()` from `"k8s.io/kubernetes/pkg/util/selinux"` (which of course should be run in a proper context). In case a check for a particular container is needed, the presence of `/sys/fs/selinux` directory should be enough.
