### ISSUE TITLE
Multizone gce tests are failing

### ISSUE THREAD

**Issue by msau42** [kubernetes/kubernetes#87905]
**Which jobs are failing**:
ci-kubernetes-e2e-gce-multizone

**Which test(s) are failing**:
[sig-scheduling] Multi-AZ Clusters should spread the pods of a replication controller across zones
[sig-scheduling] Multi-AZ Cluster Volumes [sig-storage] should only be allowed to provision PDs in zones where nodes exist 

**Since when has it been failing**:
2/6/20

**Testgrid link**:
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-multizone/1225513047829778434

**Reason for failure**:
Debugging PD test.

It gets all current zones in the cluster: https://github.com/kubernetes/kubernetes/blob/6858c25ee474ac2c90b49097c0ad04a61c6c54e1/test/e2e/scheduling/ubernetes_lite_volumes.go#L68
It returns 4 zones, which is wrong:
 I0206 20:36:10.092] Feb  6 20:36:01.730: INFO: Expected zones: map[us-central1-a:{} us-central1-b:{} us-central1-c:{} us-central1-f:{}]

The cluster was only created with 3 zones: 
I0206 20:14:29.373] Args: --job=ci-kubernetes-e2e-gce-multizone --service-account=/etc/service-account/service-account.json --upload=gs://kubernetes-jenkins/logs --timeout=170 --bare --scenario=kubernetes_e2e -- --check-leaked-resources --cluster=bootstrap-e2e-gce-mz --env=MULTIZONE=true '--env=E2E_ZONES=us-central1-a us-central1-b us-central1-f'

This perhaps implies that TestConext.MultiZone is not getting set properly:
https://github.com/kubernetes/kubernetes/blob/46a29a0cc30c0e601febd93a5851fcce615c2964/test/e2e/framework/providers/gce/gce.go#L58

**Anything else we need to know**:

**Comment by msau42** [comment]
/assign @BenTheElder 
to see if the plumbing of E2E_ZONES to TestContext.CloudConfig.MultiZone is correct

**Comment by BenTheElder** [comment]
I know nothing about E2E_ZONES, someone familiar with the GCE provider might.

you can see the env supplied to the pod by scrolling to the bottom of https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-multizone/1225513047829778434 and clicking `yaml`
/unassign

**Comment by BenTheElder** [comment]
this line:
>     - --env=E2E_ZONES=us-central1-a us-central1-b us-central1-f

suggests that bootstrap.py in test-infra is setting E2E_ZONES env to that value before the tests are called

**Comment by jingxu97** [comment]
Continue to debug PD test failure: Multi-AZ Cluster Volumes [sig-storage] should only be allowed to provision PDs in zones where nodes exist

In recent runs, the failure is due to function ListZonesInRegion() does not return zones correctly.
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/legacy-cloud-providers/gce/gce_zones.go#L77
The cause is because the regional link constructed from getRegionLink() is no longer valid.

This code makes an assumption that BasePath is equal with prefix of region URI:

	list, err := g.c.Zones().List(ctx, filter.Regexp("region", g.getRegionLink(region)))

func (g *Cloud) getRegionLink(region string) string {
	return g.service.BasePath + strings.Join([]string{g.projectID, "regions", region}, "/")
}
That is not true anymore, e.g,

BasePath: https://compute.googleapis.com/compute/v1/projects/
Region: "https://www.googleapis.com/compute/v1/projects/gke-scalability-7/regions/us-east1"

A fix is to not use the exact regionalLink, instead we could use regex match

**Comment by alculquicondor** [comment]
scheduler fix is almost merged #92840

**Comment by alculquicondor** [comment]
/assign

I'm working on the scheduler side git.k8s.io/enhancements/keps/sig-scheduling/1258-default-pod-topology-spread

**Comment by alculquicondor** [comment]
/close

grid looking pretty good now: https://testgrid.k8s.io/google-gce#gce-multizone&include-filter-by-regex=Multi-AZ%20Clusters%20should%20spread&width=20
