### ISSUE TITLE
Error to setup kubernetes cluster in Ubuntu 15.04 because of systemd

### ISSUE THREAD

**Issue by tobegit3hub** [kubernetes/kubernetes#8798]
Now Ubuntu 15.04 is using systemd to mange the services. The scripts to setup kubernetes cluster in Ubuntu should support both the init systems.

There's a known issue in https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cluster/ubuntu/util.sh#L366 which fails to start etcd by `service etcd start` in Ubuntu 15.04.

**Comment by WIZARD-CXY** [comment]
It's a problem when using systemd to manage job.You can change systemd to upstart or use docker approach to deploy k8s.

**Comment by benmccann** [comment]
See also https://github.com/GoogleCloudPlatform/kubernetes/issues/9892

**Comment by roberthbailey** [comment]
Please direct your questions to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes). 

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases. 

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to similar questions, and also familiarize yourself with:
  * [the user guide](http://kubernetes.io/v1.0/)
  * [the troubleshooting guide](http://kubernetes.io/v1.0/docs/troubleshooting.html)

Again, thanks for using Kubernetes.

The Kubernetes Team

**Comment by tobegit3hub** [comment]
Thanks @roberthbailey for indicating the usage of stackoverflow. But this is not an question about "user guide" or "troubleshooting". It's the issue of kubernetes to deploy with systemd which is used in Ubuntu 15.04 or others.

I think @WIZARD-CXY is working on this. You're closing this directly without any work and please checkout the problem first.

**Comment by roberthbailey** [comment]
@tobegit3hub -- thanks for responding. We have a huge backlog of issues that haven't been touched in months and are trying to reduce the open issues so that we can appropriately prioritize future work. 

@WIZARD-CXY are you working on this or should I apply the "help-wanted" label?

**Comment by WIZARD-CXY** [comment]
I am not working on 15.04. I recommend using docker approach to deploy k8s if tobe really wants to deploy k8s on 15.04. It is good and easy to use too~

May the force be with you

**Comment by resouer** [comment]
@roberthbailey @tobegit3hub @WIZARD-CXY  See my new proposal: https://github.com/kubernetes/kubernetes/issues/13424

**Comment by lakhindr** [comment]
@roberthbailey I see your request to redirect all questions to Stackoverflow. (I just happened to see this issue regarding 15.04).

The problem is, if you look at the bottom of http://kubernetes.io, it gives a different advise:

> Our  Slack channel is the best way to contact our engineers and share your ideas with them. They hang out at #kubernetes-users on Slack. Our user forum on stackoverflow is a great place to go for community support. 

I guess many of us novices don't exactly know where is the right forum! At least I don't. I have also sent direct emails to some Google engineers, but nobody has ever redirected me to the right forum, or even has responded, actually. Please at least fix the documentation.

Additionally, maybe there should also be a bit of an 'administration' front, and not just raw engineering, that is needed here. The problem again is, who to suggest to?! If some (or all) of Google engineers here are busy just fixing important bugs/features, that doesn't cover the horizon. (And I don't know if Stackoverflow will ever support such needs). Maybe it is just my ignorance that is showing here.

**Comment by roberthbailey** [comment]
@lakhindr Check out the description on https://github.com/kubernetes/kubernetes/wiki/Github-and-Build-Cop-Rotation#traffic-sources-and-responsibilities and see if that clears anything up. 

The idea is that support issues should be put onto stack overflow, both so that they can be answered by the wider community and because it makes them much more easily findable by the next person that asks the same question. It also has the side benefit of allowing people to earn a reward (reputation) for contributing answers, which doesn't happen if you are responding no github issues. 

This leaves github issues for more engineering focused work -- bugs being filed, issues being tracked, rather than overwhelming our issue tracking with support questions. 

If documentation is lacking, feel free to file issues that it needs to be improved.

**Comment by tobegit3hub** [comment]
I'm gonna close this because someone has installed Kubernetes on Ubuntu 15.04+ with the latest `kubeadm`.

Thanks for all your help  @resouer @WIZARD-CXY @roberthbailey and @bgrant0607 😃
