### ISSUE TITLE
Release Notes links is 404

### ISSUE THREAD

**Issue by bitva77** [kubernetes/kubernetes#87993]
**What happened**:

Not a bug in Kubernetes per say but it is inhibiting my style when about to upgrade.  Before upgrading I like to look at what's changed so I check the release notes but they all seem to be missing:

https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.16.md

**What you expected to happen**:

Was hoping to read the notes

**How to reproduce it (as minimally and precisely as possible)**:

Browse to https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.16.md

or  https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.17.md#v1172

or  https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.18.md#v1180-alpha3

you get the point...

**Anything else we need to know?**:

maybe we're on a need to know basis and I don't really need to know(?)

**Comment by bitva77** [comment]
/sig Docs

I think

**Comment by moonek** [comment]
It appears to have been moved to a new folder named `CHANGELOG`.
https://github.com/kubernetes/kubernetes/tree/master/CHANGELOG

The document does not appear to reflect the new link.

**Comment by liggitt** [comment]
That is the new correct location. Are there specific places you see stale links to the old locations?

**Comment by moonek** [comment]
All CHANGELOG-1.XX.md links on the release page are still at the old address.
https://github.com/kubernetes/kubernetes/releases

**Comment by liggitt** [comment]
cc @justaugustus

**Comment by justaugustus** [comment]
Yep, this was changed in https://github.com/kubernetes/kubernetes/pull/87879.
We're working on fixing this. Will update here once it's resolved.

/assign
/priority important-soon
/area release-eng
/milestone v1.18

**Comment by justaugustus** [comment]
/assign @saschagrunert 

Sascha, assigning you as well in case you can get to this before me.

We need to make sure that both the release template that gets uploaded to GH AND the release-notify template that we use for the announce mails are updated to point to the new location.

It's probably easiest if we parameterize (something like `CHANGELOG_BASE_URL`) so the locations stay in sync with each other.

**Comment by saschagrunert** [comment]
Working on fixes now. As a summary:

- We have to be careful that timing might play an important role here. For example, the latest patch releases from yesterday contain the correct links to the CHANGELOG files, for example
  https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.17.md#v1173
  Unfortunately, the only way to fix that for previous releases would be manually.
  We may want to point to commits instead of `master` blobs to avoid that kind of issue in the future.
- Some locations were missing in k/release, which will be fixed with https://github.com/kubernetes/release/pull/1094
- Found some wrong locations on k8s.io, which will be fixed with https://github.com/kubernetes/website/pull/19089

**Comment by smourapina** [comment]
Hello @saschagrunert !
Bug Triage team here for the 1.18 release. This is a friendly reminder that code freeze is scheduled for 5 March, which is a few weeks from now. Thanks in advance!

**Comment by saschagrunert** [comment]
I think this issue can be closed after the merge of https://github.com/kubernetes/website/pull/19089. @bitva77, do you see anything still left open?

**Comment by justaugustus** [comment]
https://github.com/kubernetes/website/pull/19089 has merged. Closing this out.
/close
