### ISSUE TITLE
Move scheduler's framework permit API to the scheduling cycle and wait in the binding cycle

### ISSUE THREAD

**Issue by mateuszlitwin** [kubernetes/kubernetes#88179]
**What would you like to be added**:
I suggest moving execution of permit plugins and the creation of a waiting pod to the scheduling cycle, right after reservation, but keep waiting on a waiting pod's channel in the binding cycle.

- This way permit plugins will be executed sequentially and result of a previous permit plugin execution will be visible during a next execution.
- With this change it will be easier to reason about waiting pods and implementations of the permit plugins will be simpler and less buggy. For example this will make features like gang scheduling much easier to implement correctly. 
- It will also potentially allow to use `SnapshotSharedLister()` in the permit plugin.
- I suspect that execution of the permit plugin will not be very expensive in the most scenarios, so it is okay to move it to the scheduling cycle.

**Why is this needed**:
There are potential races when running a permit plugin that makes them hard to use, e.g.

1. permit plugin for pod A returns "Wait"
2. permit plugin for pod B reads currently waiting pods and allow some of them and return "Allowed"
3. pod A is added to the waiting pods and is never allowed

In general, the issue is that there is no way to know when a pod will become "waiting pod" after returning "Wait" from the plugin. This leads to races where some pods are allowed and then waiting pod arrives and is potentially never allowed.

/sig scheduling

**Comment by Huang-Wei** [comment]
A scheduling cycle blocks the next one. If we move execution of permit plugin to scheduling cycle, you have to run it in a goroutine as permit plugin is meant to perform conditional waiting. In that case, the benefits you listed doesn't sound fair:

> This way permit plugins will be executed sequentially and result of a previous permit plugin execution will be visible during a next execution.

Are you trying to say permit plugins for different pods will be executed sequentially? If so, as I mentioned above, permit plugin shouldn't block scheduling cycle, so you still need to assume permit plugins for a group of pods are running asynchronously.

> I suspect that execution of the permit plugin will not be very expensive in the most scenarios, so it is okay to move it to the scheduling cycle.

It's not related with cost of a permit plugin. It's that a permit plugin would wait, and the wait definitely shouldn't block the main scheduling goroutine.

> 1. permit plugin for pod A returns "Wait"
> 2. permit plugin for pod B reads currently waiting pods and allow some of them and return "Allowed"
> 3. pod A is added to the waiting pods and is never allowed

I didn't quite get this. Isn't that when permit plugins come to pod B, pod A is already in `waitingPod` (due to the lock on it), if at that moment, the permit plugin doesn't want to `Allow` pod A, then it's as expected, why are you concerning about pod A is never allowed? Or, are you trying to say: even pod A is handled ahead of pod B in the scheduling cycle, it's also _possible_ that, in binding cycles, pod B can happen before pod A?

https://github.com/kubernetes/kubernetes/blob/b8e2b0d990ee0b780198aef6cd634afad8ea58ae/pkg/scheduler/framework/v1alpha1/waiting_pods_map.go#L41-L46

**Comment by mateuszlitwin** [comment]
Wait plugin does not actually wait, it returns `Success` or `Wait` status codes (or `Error`, etc.), if `Wait` is returned then scheduler will create `WaitingPod` that can be allowed or rejected. Problem is that after permit plugin returns `Wait` status code, there are not guarantees when pod for which `Wait` was returned will be available as `WaitingPod` in the `FrameworkHandle`.

**Comment by Huang-Wei** [comment]
I see the point.

Instead of separating the Permit extension point into two, is it possible to add a lock in the permit plugin implementation, so that the execution on pod A would block pod B? Per my understanding, why the racing issue can emerge is due to slight slow processing on pod A. In that case, moving Permit plugins to scheduling cycle wouldn't desirable as it would slow down the main scheduling loop.

**Comment by mateuszlitwin** [comment]
I think lock will work as well to address this particular problem, but in my opinion running plugins in the scheduling cycle might be preferable because:

1. It guarantees the order in which permit plugins will be executed relative to other plugins. Consider for example situation where following happens: `reserve(podA), reserve(podB), ..., permit(podB), permit(podA)` in some cases it might lead to incorrect behavior (e.g. `permit(podB)` allowing waiting pods and them `permit(podA)` returning wait) unless there is some synchronization and state shared between pods. Personally I work on gang scheduling plugin and in general it would greatly simplify the logic I currently have in my code.
2. Explicitly locking in the binding cycle might be a little weird to given that these goroutines were meant to run independently. If we are going to lock in the very beginning of the binding cycle, why not simply run that part in the scheduling cycle and guarantee the ordering in which permit() will be called?
3. Also as I mentioned earlier `FrameworkHandle.SnapshotSharedLister()` would be safe to use in permit plugins (though it would not have assumed pod).

**Comment by ahg-g** [comment]
I think this is a fair suggestion, we can split RunPermitPlugins into two phases:

1) RunPermitPlugins doesn't block and returns a Status and WaitingPod instance and is executed at the end of the scheduling cycle.
2) The WaitingPod [channel](https://github.com/kubernetes/kubernetes/blob/1c60045db0bd6efbb2827063e39f515b95c2bfa4/pkg/scheduler/framework/v1alpha1/waiting_pods_map.go#L84) should be buffered, a buffer of size one is sufficient.
3) The [waiting logic (L780-L793)](https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/framework/v1alpha1/framework.go#L780-L793) in RunPermitPlugin is moved to a new framework function named ```WaitOnPermit```, and this new function is invoked in the binding cycle instead of RunPermitPlugins.

**Comment by mateuszlitwin** [comment]
@ahg-g Why the channel should be buffered?

You can see initial draft here https://github.com/kubernetes/kubernetes/pull/88199.

**Comment by Huang-Wei** [comment]
Thanks @mateuszlitwin for the explanation. It sounds fair that the benefits of handling this problem in the framework side outweigh doing so at the Permit Plugin side.

@ahg-g, do you think we should include this in the 1.18 cycle? If so, we are close to code freeze (~2 weeks), we should start updating the KEP and working on the PR right away.

@mateuszlitwin, if we come to a consensus, do you have the bandwidth in the next 2 weeks?

**Comment by Huang-Wei** [comment]
cc/ @everpeace @denkensk @hex108

**Comment by Huang-Wei** [comment]
> Why the channel should be buffered?

That doesn't sound necessary to me either.

**Comment by mateuszlitwin** [comment]
@Huang-Wei Yes, I should have a bandwidth, I should have most of the PR ready today. I really want this to make 1.18.

**Comment by ahg-g** [comment]
> > Why the channel should be buffered?
> 
> That doesn't sound necessary to me either.

Because there could be a race between waiting and allowing/denying: 

1) podA returned wait and is added to the wait map
2) before the binding go routine of podA blocks on channel receive, podB scheduling cycle starts and it tries to allow/deny podA through a non blocking send
3) podA binding go routine blocks on channel receive, hence missing on podB's signal since it wasn't buffered

**Comment by everpeace** [comment]
Thanks for the good suggestion @mateuszlitwin .  I see your point and agree with your suggestion.

And, @ahg-g 's plan also looks good to me.  I think the important thing is that we can guarantee not to block scheduling cycle because of this change. 

// Thanks @Huang-Wei for ping me 👍

**Comment by mateuszlitwin** [comment]
Ready for review.
