### ISSUE TITLE
Please remove bazel based build infrastructure

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#88553]
- it's tough to maintain 2 things in parallel and keep them in sync
- with the switch to go modules/cache, most of the reasons why bazel was used (speed up compilations) are gone
- gets in the way in multiple ways (example, update of golang versions)
- etc...

**Comment by cblecker** [comment]
/sig release

+1 from me

**Comment by justaugustus** [comment]
area: everyone
/area build-infra release-eng
/sig release testing
cc: @kubernetes/release-engineering

**Comment by liggitt** [comment]
Bazel-related/specific issues:

* https://github.com/kubernetes/kubernetes/issues/88190
* https://github.com/kubernetes/kubernetes/issues/87441
* https://github.com/kubernetes/kubernetes/issues/78982

**Comment by justaugustus** [comment]
+1000000000
We've had a bunch of Slack threads about this, so thank you @dims for actually turning this into an issue.

Here's the latest thread: https://kubernetes.slack.com/archives/C2C40FMNF/p1582673341098700?thread_ts=1582668769.091500&cid=C2C40FMNF

The [#bazel channel](https://kubernetes.slack.com/archives/C5NV3MT97) is filled with questions like, "How do I do this thing that should be moderately simple to do if it wasn't wrapped in bazel?"

This is a huge maintainability burden, with our limited set of bazel experts being some of the most bandwidth-constrained contributors in the project.

@kubernetes/release-engineering is on board to help tear this down. 
Just let us know which threads we need to start pulling on to make this happen.

**Comment by SataQiu** [comment]
+1 👍

**Comment by bartsmykla** [comment]
Big +1 from me

**Comment by saschagrunert** [comment]
:+1: from me as well, happy to help with the transition

**Comment by hasheddan** [comment]
👍 happy to help as well :)

**Comment by cpanato** [comment]
+1 count with me

**Comment by xmudrii** [comment]
👍 💯 I’d be happy to help as well. :)

**Comment by gnufied** [comment]
This may be just my local k8s install but I am seeing an error I have not seen before while using bazel - https://github.com/kubernetes/kubernetes/issues/88742 . I mainly run `make bazel-test` locally just to ensure my PR does not fail in CI with bazel. So +1 for removing bazel from build infra (including CI)

**Comment by mrbobbytables** [comment]
+1 from me. I honestly haven't had to deal with bazel too much but each time has been a less than positive experience. :| 

These days it feels more like a vestigial part of the project. 😬

**Comment by cristiklein** [comment]
Sorry for the +1-ish-style comment, but I felt that the Bazel-based infrastructure also increases the  barrier to entry for newcomers.

**Comment by droslean** [comment]
Huge +1. Also, it is worth mentioning that the upstream bazel configuration is not working in all workstations. I found myself many times to try to hack the config to make it work.

**Comment by matthyx** [comment]
I can say I find it really useful in the `test-infra` repo where we can blend with other languages (python, ...) and not bother with writing Makefiles. It's also super useful with the tests...

Maybe we should use only one build tool across all main K8S projects, stick to it and provide resources to educate people.

**Comment by saschagrunert** [comment]
> Maybe we should use only one build tool across all main K8S projects, stick to it and provide resources to educate people.

I think we have to use at least two build systems: The standard golang toolchain and supporting `make` should be enough to handle the project. 

My question would be: Which functionality are we missing from them that bazel provides?

**Comment by matthyx** [comment]
At least for python, the way to provide a virtual env is pretty cool, see here:
https://github.com/kubernetes/test-infra/blob/master/hack/verify-pylint.sh

Another point for bazel, hermetic and reproducible builds: it does not rely on the local version of `go` or nothing on the host computer, making sure we can always generate the artifacts from the sources. All you need is the correct version of bazel and the rest is done for you inside a sandbox.

**Comment by saschagrunert** [comment]
> All you need is the correct version of bazel and the rest is done for you inside a sandbox.

I see that point and I think we could achieve the same with the standard container images we build and use today as well. :)

**Comment by vielmetti** [comment]
Full support for this decision from the arm64 side of the house. Bazel has been a tough dependency to keep on top of for building for Arm servers, as that project does not ship a Bazel binary in its default release, and so Kubernetes full integration on arm64 is just that much more of a hassle to bootstrap.

**Comment by jaypipes** [comment]
> The [#bazel channel](https://kubernetes.slack.com/archives/C5NV3MT97) is filled with questions like, "How do I do this thing that should be moderately simple to do if it wasn't wrapped in bazel?"
> 
> This is a huge maintainability burden, with our limited set of bazel experts being some of the most bandwidth-constrained contributors in the project.

This ^

Remove this obstacle to contribution to Kubernetes and you'll see an increase in contribution, IMHO.

**Comment by mkumatag** [comment]
+1 👍

**Comment by liggitt** [comment]
fwiw, the bazel/gazelle toolchain we have in place is making it significantly more complicated to  pick up a CVE fix on the 1.15 branch - see https://github.com/kubernetes/kubernetes/pull/88416#issuecomment-591970042

**Comment by dims** [comment]
from slack @matthyx https://kubernetes.slack.com/archives/C09QZ4DQB/p1583244228107400

```
matthyx:allthethings:  9:03 AM
well, I am not the specialist we need to discuss on that subject, but I like using Bazel - especially the way we use it for everything in test-infra - and I fear haters will completely crush the debate unless we have people like @fejta in that discussion
9:05
lacking skills on a tool shouldn't be the primary reason to abandon it - otherwise Kubernetes would have switched to Java a long time ago
9:06
I find myself losing 1000x more time on waiting for an approver in k/k than fighting with the build system... but it's another debate
```

**Comment by dims** [comment]
cc @fejta

**Comment by mattjmcnaughton** [comment]
One potentially interesting angle through which to frame this conversation: if we didn't already have Bazel support, would we invest $X resources to add it? And what would be the predominant motivation points to add it?

(Where $X is the amount of resources its costing us to maintain Bazel...)

**Comment by Pensu** [comment]
+1

**Comment by kensipe** [comment]
+1

**Comment by liggitt** [comment]
There are ongoing costs to the current bazel tooling, which are born in small ways by all k8s contributors, and in large ways by a handful of maintainers responsible for releases, dependencies, and go version management. To justify that, there needs to be compelling evidence that it also provides significant and widespread benefits over the standard go toolchain. I don't see that evidence, but would be interested to hear feedback from people who do.

**Comment by thockin** [comment]
The goal with Bazel was to get it to the place where 99% of developers never interact with it, and the only time BUILD files were part of a PR was when something really special was happening.  I think we never got there and the fire that was fueling use of Bazel has died down for other reasons.

Alas, poor bazel.  I wanted to like you.

The "make and go" build could ALSO be simplified in light of recent tooling changes.  I'd rather invest in that.

IMO, if specific sub-projects get real value from bazel, they should be allowed to use it AS LONG AS it's not something 99% of contributors need to be aware of.  E.g. if running `make` invokes `docker run bazel build`, I'm OK with that.

**Comment by Katharine** [comment]
+1 in principle

That said - one key place we actually benefit from bazel is in our CI infrastructure. In particular, we run all k/k unit tests via bazel and it takes about 12 minutes on average. This speed is a feature of our use of bazel - because we cache all the targets (via either greenhouse or RBE), we usually do not actually run most of the tests, in PRs or otherwise.

If we run the tests via `make test` today, we are running all the tests every time. Because of the behaviour of prow's build cluster, this can take potentially wildly varying amounts of time (perhaps 30 to 90 minutes, but I don't have ideal numbers to point at right now - worth gathering). It also leads to much higher flakiness - though some of that is probably real and just being masked by bazel's result caching. Some slowdown is probably tolerable, but I worry that we risk having a new slowest CI job and making the experience of trying to merge an average change even worse.

I don't think this is unsolvable - but I do think we probably need to solve it before ripping out bazel wholesale.

**Comment by saschagrunert** [comment]
> That said - one key place we actually benefit from bazel is in our CI infrastructure. In particular, we run all k/k unit tests via bazel and it takes about 12 minutes on average. This speed is a feature of our use of bazel - because we cache all the targets (via either greenhouse or RBE), we usually do not actually run most of the tests, in PRs or otherwise.

Caching is a good point. I think we could solve that by being able to pass around the `$GOCACHE` contents from one build to another, based on the changes (maybe a SHA) of `go.sum` files.

**Comment by lavalamp** [comment]
I'm in favor of converging on a single system. I currently despise both of our build systems. So, I'm in favor of removing which ever one there's critical mass to remove.

**Comment by vielmetti** [comment]
As an example of Bazel issues that have an impact on building multiple architectures on Kubernetes: 

https://github.com/bazelbuild/bazel/issues/10746#issuecomment-594077062

**Comment by midnightconman** [comment]
Bazel offers much more than just go builds... for instance if using it with Go applications that require embedded data, you can use bazel to convert arbitrary files into go files and store each file as a variable (we would have to invent this is make, or use an external binary for go [like paker]).

https://github.com/bazelbuild/rules_go/blob/master/go/extras.rst#go_embed_data

Bazel is also good at dealing with yaml and json, especially for kubernetes. For instance, making kubernetes manifests with trmplating:

https://github.com/bazelbuild/rules_k8s

I personally have been thankful of the bazel configurations and examples in `kubernetes/test-infra`, it has helped in my adoption and usage of bazel. I vote to keep it and resolve some of the underlying pain points, as those pain points will probably still exist if we move to make and vgo.

**Comment by Katharine** [comment]
Since people keep bringing up test-infra: it is worth noting that that is not the topic of discussion here.

**Comment by PatrickLang** [comment]
Building with Bazel requires about 16GB of RAM from my testing. That's not cheap if you don't have cloud sponsorship, and definitely not cheap in laptops where soldered down RAM is becoming more typical. Make can succeed with 6-8GB.

**Comment by fejta** [comment]
* We are underestimating the cost involved in replacing our bazel usage in CI
  - effort we could otherwise spend improving things.
* We should reach out to the #bazel community to see if there is a critical mass of people willing to improve and maintain these rules
  - a primary problem is that no one has been doing this for some time now.

**Comment by ixdy** [comment]
I was going to make a comment that another useful feature from Bazel was JUnit XML output of test results for unit and integration test runs, which is then consumed by Prow. We had a hacky set of scripts which used to provide this without Bazel using `go-junit-report`, but it was pretty fragile.

It appears now that there's a much less fragile way of doing this, implemented by @liggitt in https://github.com/kubernetes/kubernetes/pull/80822. So I guess we'd need to make sure this works properly with Prow, but it seems likely that this already works.

**Comment by ixdy** [comment]
I think it'd probably be better to spend engineering time on things like figuring out how to make the Go build cache work effectively in CI and simplifying the non-Bazel build than trying to update the [supported Bazel version](https://github.com/kubernetes/kubernetes/blob/master/build/root/.bazelversion) from one that is nearly a [year old](https://github.com/bazelbuild/bazel/issues/7667). Even if we update to the latest Bazel, we still have pretty much all of the same issues that folks are complaining about here.

A few of the core motivations for Bazel included:
- faster builds through caching (natively supported by Go now)
- reproducible builds (Go is much better about this now, especially with the death of GOPATHs)
- avoiding merge conflicts in generated code (we never solved this in Bazel, and the way Kubernetes generates code is not really compatible with Bazel. In general, we applied other workarounds which reduced this problem.)

Many of the non-Bazel build scripts date to 2014 and 2015, when the Go build system and Docker were far less mature. Both of these have improved significantly since then, and many Kubernetes subprojects have demonstrated how to achieve fast, reproducible builds without using Bazel.

I agree that Bazel can make sense in polyglot repos. The core Kubernetes repo is not polyglot.

**Comment by lavalamp** [comment]
> The core Kubernetes repo is not polyglot

Right, it's bash with a few helper .go files.

**Comment by jaypipes** [comment]
> > The core Kubernetes repo is not polyglot
> 
> Right, it's bash with a few helper .go files.

Is there a "just snarfed coffee over my keyboard" emoticon?

**Comment by allisonis** [comment]
+1

**Comment by xiaods** [comment]
anyone can share which another tools better than bazel? use github action?

**Comment by burdiyan** [comment]
Honestly speaking, I’m a big fun of Bazel in general, or better said of the properties that Bazel gives you. It’s true that Go now has many of them. And I understand how Bazel can be a barrier for newer contributors. But I *really can’t* believe that the old build system (a huge pile of bash scripts and Makefiles and hacks with Docker) are any clearer than a Bazel build file. I, personally only started to understand a little bit about how Kubernetes build system works reading Bazel build files. 

Maintaining both is indeed a problem and the main pain point. I’d say that improving Bazel and make it the main build system could work, but probably a lot of people are going to be unhappy (for reasons I will not understand :)).

> anyone can share which another tools better than bazel? use github action?

Take a look at https://github.com/apenwarr/redo.

You can do your bash, but in a lot more module and composable way.

**Comment by thockin** [comment]
The Makefiles may be a tangle but almost nobody ever has to touch them.

I see BUILD file chages in 50% of PRs I review, and I promise that every
single one of them is just autogenerated noise.

**Comment by burdiyan** [comment]
@thockin I see. That's a good point! Therese are indeed probably autogenerated. I believe there's a way to hide them from the review with some GitHub configuration. It will display them collapsed by default. But yeah, you have to remember to generate them before every commit. That's a bit painful I agree. I got used to it pretty easily though.

As an option, we could ignore BUILD files and not check them in, and generate them on CI before each build. Only if something custom is needed, these custom build files could be separate to the autogenerated ones. But that's also far from ideal. Just throwing out ideas here :)

**Comment by tnozicka** [comment]
+1000 for removing bazel

I think some time back someone made stats and BUILD files being the `#1` (or `#2`) source of conflicts on PRs.

Their generation is not idempotent which you will hit when rebasing and restructuring your commits. Sometime you just need to delete all the changes to BUILD files and generate from clean state. Same was hit with backports.

Keeping duplicate dependency information (includes) in 2 files is just not beneficial.

I prefer contributor experience over having to wait a bit longer for the job, well eventually you still wait for e2e. There are options for caching like sharing the go cache, shard the jobs, ...

**Comment by ixdy** [comment]
> I think some time back someone made stats with BUILD files being the #1 (or #2) source of conflicts on PRs.

To give a little data behind this: I wrote [a script](https://github.com/kubernetes/test-infra/blob/master/experiment/find-merge-conflicts.sh) to help with this analysis, yes. [Currently, there are 38 PRs with merge conflicts](https://gist.github.com/ixdy/c0d117037349df5739fd3eb1e44b316c). In those PRs, there are 31 `BUILD` file conflicts (though not necessarily 31 unique PRs) and 24 `go.sum` conflicts. In general, the `BUILD` file conflicts are accompanied by conflicts in the go source files as well.

But I agree that regardless of this, having to regenerate the `BUILD` files is a pain.

**Comment by Katharine** [comment]
I put together a prototype of using `make test` instead of `bazel test`, with caching achieved by periodically uploading a cache to GCS and then fetching it from the jobs. This is one of our two most time-critical CI jobs, as it runs in presubmit and doesn't use a prebuilt tarball (the other important one is trying to build at all, which should be amenable to similar approaches).

The results are encouraging — while `make test` alone takes 30-90 minutes, the runs with caching are well under ten minutes, including restoring the cache from GCS, see e.g. [this](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-cached-make-test/1235401841756344321) or [this](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-cached-make-test/1235405866505605120). There isn't much data yet, so it'll be interesting to see more runs over time, especially at busier times of day as they have more opportunity to diverge from the latest cached run.

The gzipped cache file for this is ~450 MB, which is entirely workable.

(The failures in those runs are unrelated — looks like maybe questionable test to me…)

**Comment by tnozicka** [comment]
> To give a little data behind this: I wrote a script to help with this analysis, yes. Currently, there are 38 PRs with merge conflicts. In those PRs, there are 31 BUILD file conflicts (though not necessarily 31 unique PRs) and 24 go.sum conflicts. In general, the BUILD file conflicts are accompanied by conflicts in the go source files as well.

Yeah, I admit the stats were for sure done before modules, the vendor packages weren't being pruned back then. Modules are the next big offender because they prune unused packages from vendor and don't vendor the whole dependency. The move to go mod is likely the next offender, but at least is comes from a component we actually require. It also has another side effect - by not vendoring the whole package, for using a package from already vendored dependency you need a top level approve which you didn't need before.

I am not much familiar how our infra is setup but I suppose for every branch we could have a postsubmit to push a builder image containing update cache (not modules as we use vendor) and use that for builds from that branch so the only divergence would be the content of your PR.

**Comment by BenTheElder** [comment]
we have experiments for exactly that [go caching in this pattern] live
currently. the results are very promising.

**Comment by justaugustus** [comment]
/priority critical-urgent
cc: @kubernetes/product-security-committee

While working on the [go1.13.9 upgrade](https://github.com/kubernetes/kubernetes/pull/89275), I found that the upgrade requires a `bazelbuild/rules_go` >= [`v0.21.5`](https://github.com/bazelbuild/rules_go/releases/tag/v0.21.5) (ideally [`v0.22.2`](https://github.com/bazelbuild/rules_go/releases/tag/v0.22.2)) bump, which in turn requires bazel >= 1.2.0:

```
W0323 04:58:11.724] ERROR: /go/src/k8s.io/kubernetes/WORKSPACE:53:1: Traceback (most recent call last):
W0323 04:58:11.724] 	File "/go/src/k8s.io/kubernetes/WORKSPACE", line 53
W0323 04:58:11.725] 		go_rules_dependencies()
W0323 04:58:11.725] 	File "/bazel-scratch/.cache/bazel/_bazel_prow/48d5366022b4e3197674c8d6e2bee219/external/io_bazel_rules_go/go/private/repositories.bzl", line 40, in go_rules_dependencies
W0323 04:58:11.725] 		versions.check(MINIMUM_BAZEL_VERSION, bazel_versi...)
W0323 04:58:11.726] 	File "/bazel-scratch/.cache/bazel/_bazel_prow/48d5366022b4e3197674c8d6e2bee219/external/io_bazel_rules_go/go/private/skylib/lib/versions.bzl", line 104, in versions.check
W0323 04:58:11.726] 		fail("\nCurrent Bazel version is {}, ...))
W0323 04:58:11.726] 
W0323 04:58:11.726] Current Bazel version is 0.23.2, expected at least 1.2.0
W0323 04:58:11.726] ERROR: Error evaluating WORKSPACE file
W0323 04:58:11.741] ERROR: error loading package '': Encountered error while reading extension file 'repositories/repositories.bzl': no such package '@io_bazel_rules_docker//repositories': error loading package 'external': Could not load //external package
W0323 04:58:11.745] ERROR: error loading package '': Encountered error while reading extension file 'repositories/repositories.bzl': no such package '@io_bazel_rules_docker//repositories': error loading package 'external': Could not load //external package
W0323 04:58:11.760] INFO: Elapsed time: 11.238s
W0323 04:58:11.760] INFO: 0 processes.
W0323 04:58:11.765] FAILED: Build did NOT complete successfully (0 packages loaded)
W0323 04:58:11.768] FAILED: Build did NOT complete successfully (0 packages loaded)
W0323 04:58:11.774] make: *** [Makefile:625: bazel-release] Error 1
```

Moving to a new major version of bazel means we've got to resolve a variety of problems before getting back to the go upgrade.

Furthermore:

- bazel updates are difficult to test in repo (both the `build/root/.bazelversion` and CI images lock in a bazel version)
- the majority of our e2e presubmits are also dependent on bazel, which means guaranteed failures on a PR like https://github.com/kubernetes/kubernetes/pull/89275.

Given this is now a blocking issue on `kubernetes/kubernetes@master`, I'm echoing @liggitt's [sentiment](https://github.com/kubernetes/kubernetes/issues/88553#issuecomment-593963778) that this is firmly a security posture issue.

So we need to make a call here: can we rip bazel out now or do we need to proceed with multiple bazel upgrades to reenable our ability to update Go?

Some initial tries in both directions...

### Upgrade bazel

- Add a `bazel-experimental` variant to `kubekins-e2e` image building: https://github.com/kubernetes/test-infra/pull/16894

  This will allow us to safely bump the bazel version (to `0.29.1`) within an image that can be used for testing outside of the merge-blocking path
- Create a `bazel-upgrade` feature branch on `kubernetes/kubernetes`
- Add `bazel-experimental` canary presubmits: https://github.com/kubernetes/test-infra/pull/16897

  These presubmits would mirror the following jobs, but use the `bazel-experimental` image:
  - `pull-kubernetes-bazel-build`
  - `pull-kubernetes-bazel-test`
  - `pull-kubernetes-e2e-gce`
- Bump the `bazel-experimental` variant to `1.2.1`
- Watch/fix test results from variant bump

### Remove bazel from merge-blocking path

- Make `pull-kubernetes-bazel-{build,test}` jobs non-blocking: https://github.com/kubernetes/test-infra/pull/16896
- Add a non-blocking presubmit (`pull-kubernetes-e2e-gce-no-bazel`) to test e2e-gce without bazel: https://github.com/kubernetes/test-infra/pull/16895

The obvious next steps for each option would be:

- ???
- PROFIT

Let me know what you all think.

**Comment by Katharine** [comment]
Removing bazel is not a viable immediate-term strategy: we have hard dependencies on it for CI, even if we disregard all developers who choose to use it. Turning it off now would either cause us to lose critical presubmit tests or make presubmits _even slower_. There’s potential for this in the medium/long term, but not today. 

We’ve previously almost-successfully updated bazel - @bentheelder was mostly successful (aside from push-build) a while back, and I hear rumour that @mikedanese more recently got the whole thing working.

**Comment by ixdy** [comment]
It should be possible to manually use a different version of Go without updating rules_go (basically by explicitly specifying the go toolchain to use). I've done this before (usually on release branches), and I can write a change for it later today if someone else doesn't get to it first.

**Comment by mikedanese** [comment]
This fixed push-build: https://github.com/kubernetes/repo-infra/commit/506b905b84c5ecd65a675b34aa53a9d63acfee10
We should be able to bump bazel to 2.2.0. I'm working on it in my free time but would be happy for someone else to take over as well.

**Comment by ixdy** [comment]
https://github.com/ixdy/kubernetes/commit/2a189ad34ee611a02a4bc1cda12deddcf1c15a44 shows how you can update the version of go used for bazel builds without updating `rules_go`. (I copied the list of SDKs from [here](https://github.com/bazelbuild/rules_go/blob/master/go/private/sdk_list.bzl).)

```console
$ bazelisk run //cmd/kubectl -- version --client
INFO: Analysed target //cmd/kubectl:kubectl (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //cmd/kubectl:kubectl up-to-date:
  bazel-bin/cmd/kubectl/linux_amd64_pure_stripped/kubectl
INFO: Elapsed time: 0.552s, Critical Path: 0.21s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action
Client Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.0-alpha.0.1010+2a189ad34ee611", GitCommit:"2a189ad34ee611a02a4bc1cda12deddcf1c15a44", GitTreeState:"clean", BuildDate:"2020-03-23T18:42:29Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by spiffxp** [comment]
@justaugustus The removal of bazel is far-reaching enough that it merits a KEP.  If this is about unblocking you immediately, I would not recommend going that route, and instead look to others' suggestions above.

**Comment by justaugustus** [comment]
>  If this is about unblocking you immediately, I would not recommend going that route, and instead look to others' suggestions above.

I've applied the fix that @ixdy suggested to https://github.com/kubernetes/kubernetes/pull/89275 (which is now merged) and https://github.com/kubernetes/kubernetes/pull/88638, so I think we're good to drop the priority level here:
/remove-priority critical-urgent
/priority important-soon

Given the suggestions here, we'll need to proceed with maintaining bazel in the near-term.
I've opened https://github.com/kubernetes/kubernetes/issues/89414 to track upgrading bazel to v2.2.0 and it looks like @mikedanese and @fejta have already started working on it (PRs linked in that issue).

Thanks everyone for the advice!

---

> @justaugustus The removal of bazel is far-reaching enough that it merits a KEP.

@spiffxp -- Agreed, though I admit I'd be out of my depth providing the level of detail needed to describe all of the interconnected bazel pieces.

Is anyone with sufficient expertise in our bazel infra available to work on a removal KEP for milestone 1.19 (strictly draft, not actual removal)?

**Comment by dims** [comment]
YET another reason to pull our bazel - https://github.com/kubernetes/kubernetes/pull/90575#issuecomment-624993328 ( this one from @thockin )

**Comment by AkihiroSuda** [comment]
What's current status?

**Comment by BenTheElder** [comment]
@AkihiroSuda someone has to actually propose a plan and staff an effort to remove this, which will require non-trivial work.

Switching out bazel would require ensuring alternatives exist and run smoothly in CI at minimum.

We still only have caching in presubmit via bazel and our builds are non trivial, there's a quick prototype of doing something this for go on our CI, but the person who built that has moved on.

This probably deserves a KEP.

Another data point https://github.com/kubernetes/kubernetes/pull/92212#issuecomment-648273928

**Comment by BenTheElder** [comment]
Note that https://github.com/kubernetes/kubernetes/issues/88553#issuecomment-602411809 does not propose a workable plan, we can't just stop testing build & unit in presubmit, and merely switching them will incur non-trivial CI overhead, despite treating it otherwise, our resources there are finite and wg-k8s-infra has not taken ownership of them yet so they are not easily changed. Someone needs to pick up @Katharine's work

https://github.com/kubernetes/kubernetes/issues/88553#issuecomment-593947801 @vielmetti note that building natively on arm w/o bazel does not work currently. bazel is the only functioning build on non-amd64. (builds for these platforms are cross compiled without bazel from amd64 in releases)

https://github.com/kubernetes/kubernetes/issues/88553#issuecomment-594127970 +1

**Comment by fejta** [comment]
> #88553 (comment) +1

Getting these repos update to bazel v1 has already happened, and we have patterns for using `.bazelversion` in presubmit to validate the new version works before flipping it on. 

Whether or not we are using bazel, figuring out a recipe for not downloading many GBs of worth data for each test on each commit on each PR will be a gigantic CI improvement.

**Comment by MonzElmasry** [comment]
Hey :wave: Bug Triage here. Wanted to follow up on the status of this issue as we're approaching code freeze on 12.11.2020. This issue is tagged for 1.20, is it still planned for this release?

**Comment by justaugustus** [comment]
This is unfunded for v1.20.
I'm dropping the milestone, but let's circle up and see what can be done for 2021.

/milestone clear

**Comment by q3k** [comment]
-1 on this from us (Monogon). We use Bazel internally within our codebase to build Kubernetes (as libraries), and being able to just pull in an external repository (with only some minor patches to fix Starlark machinery paths) is crucial for us. I can't imagine working with Kubernetes as a dependency if it required running a bunch of impure scripts before calling `go build`.

If pulling in Kubernetes via Gazelle continues to function we can work with that, otherwise we'll have to maintain our own overlay of Bazel BUILDfiles.

I understand the various pain points working with Bazel sometimes - but for large scale projects this still seems to be the best build system we have. No other system provides this level of granular caching (for incremental builds) and hermeticity (for reproducible builds) simultaneously.

**Comment by BenTheElder** [comment]
After much discussion, attempting to move forward on this is now a KEP https://github.com/kubernetes/enhancements/pull/2421, for the reasons outlined there.

/assign

---

> -1 on this from us (Monogon). We use Bazel internally within our codebase to build Kubernetes (as libraries), and being able to just pull in an external repository (with only some minor patches to fix Starlark machinery paths) is crucial for us. I can't imagine working with Kubernetes as a dependency if it required running a bunch of impure scripts before calling go build.

The Kubernetes project does not support importing this repo directly as a dependency, bazel or otherwise. If you wish to import a [staging](https://github.com/kubernetes/kubernetes/blob/master/staging/README.md) repo like "client-go" the supported version is at github.com/kubernetes/client-go, which does not and has never included BUILD files or required any particular build system, just golang sources consumable from your preferred build solution as a normal go package.

Other packages are not supported as dependencies.

so:
> If pulling in Kubernetes via Gazelle continues to function we can work with that, otherwise we'll have to maintain our own overlay of Bazel BUILDfiles.

It will function as much as it is supported today, and in fact because we check in generated code etc. so that people can build without our make / bazel etc., it will be trivial to wrap. None of our libraries require using any of our build scripts, only our binary artifacts / docker images.

If you're depending on Kubernetes/Kubernetes to get release artifacts, I highly suggest switching to consume our official release builds instead of sources. `rules_k8s` for example consumes `kubectl` binaries, not kubernetes/kubernetes to source build it.

> I understand the various pain points working with Bazel sometimes - but for large scale projects this still seems to be the best build system we have. No other system provides this level of granular caching (for incremental builds) and hermeticity (for reproducible builds) simultaneously.

FWIW, we have ~equally reproducible builds under make (which is getting pretty trivial for go binaries, essentially in modern go you just need to set `-trimpath` and pin dependencies with `go.sum` / GOPROXY, or `vendor` (we use both)).

We also see that `go build` / `go test` has pretty excellent caching now, and that we need to exclude our large docker images from the bazel cache to avoid net performance losses (these rarely cache well when developing kubernetes, binary source changes will invalidate them anyhow).

You can see more on this in https://github.com/kubernetes/enhancements/pull/2421, maintaining both systems is not free, and bazel does not map particularly well to _this_ project

**Comment by q3k** [comment]
> If you're depending on Kubernetes/Kubernetes to get release artifacts, I highly suggest switching to consume our official release builds instead of sources.

We can't, as we need a fully static build of Kubernetes. We also heavily patch it to remove unnecessary (to us) functionality that's not gated behind build tags, the subset of which is specific enough for our usecase that attempting to upstream such buildtags would be at least seen as  uncourteous. Notably, we remove a sizeable amount of in-tree volume providers (that we know aren't compatible with our product, anyway) and nearly all in-tree legacy cloud providers. We also always carry a number of fixes pending upstreaming.

> The Kubernetes project does not support importing this repo directly as a dependency, bazel or otherwise.

We know it's unsupported and we are more than ready to carry the burden of occasionally unbreaking things and running our own QA. Additionally, with Bazel, the line between building from our proejct and building from the k8s.io/kubernetes source itself is quite blurred - it's `bazel build @io_k8s_kubernetes//cmd/kubelet` in both cases. That's why we appreciate the Bazel build system in Kubernetes so much, as we can plainly pull in all of Kubernetes into our main build graph, without having to have intermediary release processes or patched source trees. The same build graph in which we have all of our dependencies, including non-Go code, complex code generation, even the build toolchains themselves.

We also need to be able to build from source that is not within the supported client libraries, eg. to build a hyperkube-like binary containing core control plane services, our own wrapped kubelet, etc.

> You can see more on this in kubernetes/enhancements#2421

Yes, I will review the KEP.

**Comment by BenTheElder** [comment]
> We also heavily patch it to remove unnecessary (to us) functionality that's not gated behind build tags, the subset of which is specific enough for our usecase that attempting to upstream such buildtags would be at least seen as uncourteous. > 

At this point it sounds like you're maintaining a fork. Your fork can maintain a build with bazel then as well, without us carrying this upstream, just like these other patches, and other `go build` dependencies?

And in fact this way you can customize the build as much as you want without colliding with what we do upstream. You can just ignore the makefiles etc.

> We also need to be able to build from source that is not within the supported client libraries, eg. to build a hyperkube-like binary containing core control plane services, our own wrapped kubelet, etc.

Similarly, we stopped maintaining an upstream build for hyperkube, because the costs outweighed the limited usage and the ability to do this downstream for anyone that wants it / lack of these consumers participating in the ongoing costs.

**Comment by q3k** [comment]
> At this point it sounds like you're maintaining a fork. 

Not a true fork - we continue to track upstream as the source of truth, rebasing our changes on top at buildtime. We've also successfully consistently decreased the amount of patches we apply as we continue to upstream our changes. In an ideal world, we would just follow upstream, we have no practical interest in maintaining a fork other than the technical reasons to do that.

If we have to maintain a Bazel compatibility patchset, we will. But I know we're not the only organization that imports Kubernetes into their buildsystem this way, so it's a shame that this will now basically have to fall onto the community, or will have to be repeatedly done by multiple organizations independently.
