### ISSUE TITLE
Update scheduler extender API to be better defined

### ISSUE THREAD

**Issue by damemi** [kubernetes/kubernetes#88634]
As noted in https://github.com/kubernetes/kubernetes/pull/88540, currently the `extender/v1` API in the scheduler is missing a couple things:
* internal version or conversion methods
* typemeta on objects
* json tags on types

Since we can't make these changes to the current version of the type without potentially breaking expectations for existing consumers, this may require bumping to a new api version

**Comment by Huang-Wei** [comment]
One note: if we want to incorporate TypeMeta into the serialized extender APIs, we should ensure "serialized extender API objects" to be passed onto extenders, and also guide users to use newly generated utilities to covert the received objects into v1, or v2 at their extender programs.

To minimize the impact on user side, I'd suggest we only start the refactoring when the fields really need updates (and then bump it to v2). Otherwise, don't bother and keep the current unversioned v1 API.

**Comment by damemi** [comment]
Cross-referencing https://github.com/kubernetes/kubernetes/issues/89396

**Comment by alculquicondor** [comment]
> typemeta on objects

Do we actually need those? Alternatively, do we need to comply to OpenAPI? The extenders API is about IPC and not resources (definition or storage).
What are the precedents to this? The closer I can think of is the communication between kube-apiserver and kubelet around resources usage. IIRC, kubelet offers a GRPC server and some basic json endpoints.

It might be worth asking the API folks for guidance.

**Comment by alculquicondor** [comment]
@liggitt do you know of such precedents?

On the other hand, OpenAPI is probably well-known among kubernetes users.

**Comment by kerthcet** [comment]
Can anyone tell me what unaddressed issues we left here?

**Comment by alculquicondor** [comment]
The extenders API is not something we want to maintain. Unless there is an important use-case that can't be covered with the scheduling framework, I suggest that we close this issue.

**Comment by kerthcet** [comment]
As advised, let us close this issue and reopen if needed. cc @damemi 
/close
