### ISSUE TITLE
Filter/restrict access to http://metadata from containers

### ISSUE THREAD

**Issue by stephenR** [kubernetes/kubernetes#8867]
On GCE, the metadata server gives access to tokens/certs for the master apiserver as well as auth tokens belonging to the project's service account.
We could use an iptable rule to block all connections coming in from a container that doesn't share the host's network interface.
While this is not a perfect solution from a security point of view, it could at least keep users from relying on auth scopes and data from the metadata server that might be removed in the future.

@roberthbailey already noted that some services might rely on the logging scope, so maybe this would need a way to disable the filter in that case?

**Comment by roberthbailey** [comment]
@satnam6502 will this break fluentd logging?
@vishh @vmarmol will this break heapster monitoring?

**Comment by vmarmol** [comment]
This would break GCM and GCL support in Heapster.

Putting my security hat on, it is probably the right thing to do :) We need to find a more secure mechanism to get this type of auth data to jobs.

**Comment by alex-mohr** [comment]
Restricting the metadata server could also break apps other than heapster/fluentd that run in containers that rely on getting those scopes?  I think it's fine to err on the side of exposing functionality now -- we're not at the point where we're trying to harden the VM against malicious containers that run on it.

**Comment by erictune** [comment]
Eventually, I think we would want the set of GCE scopes that a pod can access to be controlled at a per-pod granularity, not a per-node granularity.    This allows principle of least privilege for pods and users.

This is too complex to do for v1.

Notes on what we would need to do to get per-node credentials:

We might want an option to remove the `.internal` from the Pod's dns search path.  This is not sufficient since the user could still access metadata via an IP, 169.254.169.254. It would block access to other nodes, which might be a good or bad thing depending on your perspective.

We'd want a kubelet option which causes the pods networking to be setup in a way that they cannot access the metadata IP, 169.254.169.254. 
  - This could implemented with an iptables rule on the pod's veth to drop traffic to/from 169.254.169.254, though creating an iptables rule from kubelet would fight with kube-proxy, and doing it in kube-proxy would be racy with respect to pod creation.

We would want a way for different pods to have different sets of scopes, without restricting scheduling.  So, we could not use the single service account attached to each node, which has all scopes on it.  We would need to give tokens to the pod which were generated via some other mechanism.  This could be some sort of multi-tenant version of metadata, as yet not designed or implemented.  But it might work better to use the kubernetes "secrets" and "serviceAccounts" mechanisms.   

I'm thinking of some kind of automation that assists the user in:
  1. creating kubernetes secrets which contain GCP credentials, and rotating those secrets.
  1. attaching those secrets to kubernetes serviceAccounts (relationship between kubernetes serviceAccount and GCP service account is TBD.)

**Comment by erictune** [comment]
I'm going to remove v1-candidate and lower priority.

**Comment by erictune** [comment]
If secrets were the only problem, then it might make sense to have a per-node filtering proxy which serves all of the metadata except secrets.

But, exposing metadata also makes pods less portable.
  - a migrated pod or a restarted pod with persistent storage will notice that the node metadata is different.
  - pods which rely on metadata won't work on non-GCE IaaS which makes it harder to write config for "hybrid cloud" apps.

**Comment by satnam6502** [comment]
@roberthbailey I don't know -- I need a few minutes to think about this -- which probably can't happen until Saturday.

**Comment by erictune** [comment]
fluentd does not run in a container, so it would not presumably not be affected by a change that only restricts access to metadata within containers?

**Comment by satnam6502** [comment]
@erictune fluentd does not run in a container? What little I know turns out to be false and now I realize I know less than nothing.

**Comment by erictune** [comment]
Doh!  There are several fluentds, but the one that matters is indeed in a
container.

**Comment by bgrant0607** [comment]
Access to the metadata server compromises isolation of containers from hosts and from the cluster. As with host ports, host networking, host paths, etc., we shouldn't expose these addresses by default. Authorization should be required.

This should apply to all link-local addresses. AWS also exposes its metadata server on 169.254.169.254, IIRC.

**Comment by bgrant0607** [comment]
Whatever credentials Heapster needs should be deployed using a Secret. See also https://github.com/GoogleCloudPlatform/kubernetes/issues/8512#issuecomment-106700908

**Comment by satnam6502** [comment]
@jimmidyson do your changes need access to http://metadata?

**Comment by therc** [comment]
On AWS, people are using tools like https://github.com/dump247/docker-ec2-metadata to filter metadata access. You assign the EC2 instance a role with a superset of all possible roles that can be assumed by containers, then the proxy will return just the one that applies to the container, as specified in an environment variable. That's with the major assumption that you can trust the variable, of course.

**Comment by therc** [comment]
Are this issue and #11936/#14226/#23580 in scope for the 1.3 IAM work?

**Comment by bgrant0607** [comment]
This should apply to other host link-local addresses, also.

**Comment by evmin** [comment]
While I fully understand the desire to limit the access to the metadata endpoint, there still should be an easy way for Pods to get the basics - such as project id of the cluster, etc.

Please consider how this requirement can be met?

**Comment by bgrant0607** [comment]
Access to GCE-specific information from the metadata server compromises application portability, security, pod-to-pod isolation, and pod-to-node isolation.

General cluster topology and metadata could be extracted from node labels, if there were a way to access node information, which would also need to be opt-in, in part since it would compromise the possibility of container migration (#3949).

**Comment by vincentwoo** [comment]
It has come to my attention that the GCP metadata server is *also* available over IPV6, necessitating more thorough blocking for those who are doing so:

```
$ curl -g http://[0:0:0:0:0:FFFF:A9FE:A9FE]
0.1/
computeMetadata/
```

This is kind of unfortunate because it doesn't seem to be mentioned anywhere.

**Comment by vincentwoo** [comment]
Furthermore, is it possible for Google to tell us what IPv4 and IPv6 blocks they plan to use for *all* `*.internal.google` addresses so we can block them en masse?

**Comment by vincentwoo** [comment]
Also, the metadata server *also* happens to be the default resolver itself? Is *THAT* intentional?

```
$ dig metadata.google.internal

; <<>> DiG 9.10.3-P4-Debian <<>> metadata.google.internal
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 12349
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;metadata.google.internal.  IN  A

;; ANSWER SECTION:
metadata.google.internal. 3600  IN  A 169.254.169.254

;; Query time: 0 msec
;; SERVER: 169.254.169.254#53(169.254.169.254)
;; WHEN: Mon Jun 19 21:47:27 UTC 2017
;; MSG SIZE  rcvd: 69

$ cat /etc/resolv.conf 
domain c.civic-wharf-93619.internal
search c.civic-wharf-93619.internal. google.internal.
nameserver 169.254.169.254
```

**Comment by vincentwoo** [comment]
Upon deeper investigation, it seems blocking `169.254.169.254` was sufficient, probably because the ipv6 address was using some link-local magic to just use ipv4 under the covers anyway.

**Comment by Omeryl** [comment]
@vincentwoo Just replying, it being the default resolver is definitely intentional because of: https://cloud.google.com/compute/docs/vpc/internal-dns

(late to the party, I know, but probably helpful for other people who happen to come upon this issue).

**Comment by liggitt** [comment]
@ihmccreery is this resolved by https://github.com/kubernetes/kubernetes/pull/54725?

**Comment by ihmccreery** [comment]
@liggit this feature is going to beta in v1.9.  I'd like to keep this open until it's GA/default.

**Comment by negz** [comment]
https://github.com/GoogleCloudPlatform/k8s-metadata-proxy/blob/e693595/metadata_proxy.go#L22

@ihmccreery @mikedanese I notice the k8s-metadata-proxy blocks access to the `identity` endpoint, but not the `token` endpoint. Does blocking access to `identity` prevent pods using tokens requested via the `token` endpoint?

**Comment by evmin** [comment]
@ihmccreery @mikedanese 

Our production solution uses:

http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/token
and
http://metadata.google.internal/computeMetadata/v1/project/project-id

And my understanding is that we are impacted. Are we? 

If it is the case, can we request the setting to be configurable, please?
Also, what would be the best way to replace these two endpoints?

Thank you!

**Comment by ihmccreery** [comment]
@negz: correct, this blocks `identity` but not `token` ... addons (and e.g. @evmin's workloads) often need to use the `token` endpoint (so, no, blocking `identity` does not prevent pods from using `identity`).  We blocked `identity` because it's a machine-specific identity, not one that any workload should ever need access to, and may also become the basis for asserting kubelet identity in the future.

@evmin: you should be fine with this turned on (neither of those endpoints is blocked), but it's off by default in prod (on by default in test) and configurable via `ENABLE_METADATA_CONCEALMENT` in https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/config-default.sh.  To replace those endpoints, consider injecting that information into your pods via secrets or configmaps, respectively.

**Comment by evmin** [comment]
Thank you for confirming - much appreciated!

**Comment by liggitt** [comment]
@dekkagaijin what's the status of this?

**Comment by mikedanese** [comment]
We support this in GKE, but I don't think there's an equivalent for some other platforms. Kube2iam covers this. Do we need a platform agnostic solution? If not, we can close this.

**Comment by liggitt** [comment]
given this is targeting gce, and the provider-specific nature of metadata access, I think this should be closed

/close
