### ISSUE TITLE
make bazel-test throws version error

### ISSUE THREAD

**Issue by gnufied** [kubernetes/kubernetes#88742]
I have been using `make bazel-test` locally for awhile now but recently it has started throwing:

```
ERROR: The project you're trying to build requires Bazel 0.23.2 (specified in /home/hekumar/redhat/kubernetes/.bazelversion), but it wasn't found in /usr/bin.

Bazel binaries for all official releases can be downloaded from here:
  https://github.com/bazelbuild/bazel/releases

Please put the downloaded Bazel binary into this location:
  /usr/bin/bazel-0.23.2-linux-x86_64
make: *** [Makefile:594: bazel-test] Error 1

```

Bazel version:

```
Build label: 2.1.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Feb 7 00:00:00 2020 (1581033600)
Build timestamp: 1581033600
Build timestamp as int: 1581033600
```

Which does not make sense because my current bazel version is 2.x. Deleting .bazelversion file fixes that error and build proceeds as usual.

**Comment by praseodym** [comment]
This is by design, [e2e tests are currently using Bazel 0.23.2](https://github.com/kubernetes/test-infra/blob/cd2a9be6f3f94a8c5ac85b81257deabcd3b0aee5/images/kubekins-e2e/variants.yaml) and there's no guarantee that using a newer version will work. You can use [Bazelisk](https://github.com/bazelbuild/bazelisk) to automatically download and use the correct Bazel version.

**Comment by justaugustus** [comment]
Tracking bazel upgrade to v2.2.0 here: https://github.com/kubernetes/kubernetes/issues/89414

**Comment by BenTheElder** [comment]
Not surprisngly 2.X isn't compatible with 0.X

A new enough bazel will actually automatically respect .bazelversion though, behaving like bazelisk.

You can either upgrade, use bazelisk, or use this version.
/close
