### ISSUE TITLE
kubectl exec by pod label

### ISSUE THREAD

**Issue by rhcarvalho** [kubernetes/kubernetes#8876]
I often find myself wanting to exec commands on single-container pods, and since pod names are not "stable", I use some wrapper script to avoid constantly updating pod names:

```
kubectl exec -p $(get_current_pod_name) my_script.sh
```

My `get_current_pod_name` returns the name of the first pod matching a label, and that covers the case when I want to execute the script on any one and only one container.

For fetching server logs of different pods/containers, for example, I'm currently giving an argument to `get_current_pod_name` to actually give me the _n-th_ pod from the list of matches, but that's kind ugly... and no multiplexing.

I found this [comment](https://github.com/GoogleCloudPlatform/kubernetes/issues/8448#issuecomment-103235025) by @brendanburns on #8448 which led me to believe that there might be more people who'd like "-l" argument support:

> I would think to do that we'd actually want to use label syntax, e.g.
> 
> ```
> kubectl exec -l stage=production,user=bburns or whatever.
> ```

Would it be reasonable to add label filtering + some way to say "run in any one container" or "run in all containers" (in this case, maybe no support for "-it" flags...)?

**Comment by thockin** [comment]
Interesting idea.  I think it will have to wait for our 1.0 launch, but it sounds reasonable.

**Comment by brendandburns** [comment]
yeah, sadly I think we should punt this past 1.0.  For now, you can hack around this with:

```
kubectl exec `kubectl list -l=<labels> --template=<golang template> -o=template` <cmd>
```

but that's pretty ugly.

**Comment by rhcarvalho** [comment]
I'm currently using:

```bash
POD_INDEX=1 kubectl exec -p `kubectl get pod -l "name=web" \
                         -t "{{ with index .items ${POD_INDEX:-0} }}{{ .metadata.name }}{{ end }}"` -- <cmd>
```

**Comment by bgrant0607** [comment]
This is what we've been calling the "-q" pattern -- we should have an output format that just dumps names in a form that can be used on the kubectl command line. See item 16 here:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/cli-roadmap.md

**Comment by bgrant0607** [comment]
Ah, here: #5906

**Comment by rcoup** [comment]
```
kubectl exec -i -t $(kubectl get pod -l "role=xyz" -o name) -- bash
```
_almost_ works. With kubectl 1.6.0, you currently get:

```
error: invalid resource name "pod/xyz-3930372477-qdq3c": [may not contain '/']
```
Because `-o name` now consistently returns the resource type. `kubectl exec` should ignore a leading `pod/` if it's present.

**Comment by SimenB** [comment]
`sed 's/pod\///'` should work

**Comment by rcoup** [comment]
@SimenB oh, sure -- the shell has infinite hackability :) But making `-o name` output consistently able to be used seems like a good goal.

For other readers, incorporating @SimenB's command means this will work:

```
kubectl exec -i -t $(kubectl get pod -l "role=xyz" -o name | sed 's/pods\///') -- bash
```

**Comment by SimenB** [comment]
I definitely agree it should be usable to `exec` without preprocessing, just pointing out a workaround

**Comment by mshytikov** [comment]
Yet another variation of a workaround
```
kubectl exec -i -t $(kubectl get pod -l "role=xyz" -o jsonpath='{.items[0].metadata.name}') -- bash
```

**Comment by jimethn** [comment]
I have a use-case.

I want to create a systemd service that does a kubectl exec and runs a script inside a pod. The problem is systemd doesn't let you do subshells by design, i.e. this doesn't work:

`ExecStart=kubectl exec -t $(kubectl get pods -l=my=selector -o jsonpath='{.items[0].metadata.name}') -- /somecommand.sh`

The workaround to this systemd feature is to have systemd run bash and pass the command using the -c flag. Since you're in a real bash shell and not systemd, subshells work again:

`ExecStart=/bin/bash -c "kubectl exec -t $(kubectl get pods -l=my=selector -o jsonpath='{.items[0].metadata.name}') -- /somecommand.sh"`

The problem with this approach is that by doing it this way, systemd no longer receives the output of the command that runs inside bash. The command will run, but I have no way of getting the output in the event of a failure which makes debugging difficult. I end up having to do something ugly using temp files...

```
ExecStartPre=/bin/bash -c "kubectl get pods -l=my=selector -o jsonpath='{.items[0].metadata.name}' > /tmp/targetpod"
ExecStartPre=/bin/bash -c "echo kubectl exec -t $(cat /tmp/targetpod) -- /somecommand.sh > /tmp/thecommand.sh && chmod a+x /tmp/thecommand.sh"
ExecStart=/tmp/thecommand.sh
ExecStartPost=rm /tmp/targetpod
ExecStartPost=rm /tmp/thecommand.sh
```

This insecure pattern would be alleviated by being able to pass my selectors directly to kubectl exec.

**Comment by cristi-d** [comment]
Without subshells
`kubectl get pods | grep <pod name pattern> | cut -d ' ' -f 1 | xargs -I{} kubectl exec {} <command>`

**Comment by dhiraj** [comment]
I use fish shell, and this function works well enough for me, inspired by cristi-d's post above. I can type any disambiguating combination from the pod name and it gives me bash directly. Suggestions, improvements welcome!

```fish
# ~/.config/fish/functions/kbash.fish
function kbash
	set pod (kubectl get pods | grep -m 1 $argv | cut -d ' ' -f 1)
	echo Executing bash on $pod
	command kubectl exec -it $pod -- bash
end
```

Invocation on command line looks like this:
```bash
$ kbash yii2api
Executing bash on apibeta-yii2api-7464fb59bf-4xplp
bash-4.4# 
```

**Comment by xofred** [comment]
```bash
kubectl exec -it $(kubectl get pods | grep -m1 ruby|awk '{ print $1 }') bundle exec rails c 
```
This works for me

**Comment by MarkBennett** [comment]
> ```shell
> kubectl exec -it $(kubectl get pods | grep -m1 ruby|awk '{ print $1 }') bundle exec rails c 
> ```
> 
> This works for me

Handy. Do you make an alias or define a function for this somewhere @xofred?

**Comment by xofred** [comment]
@MarkBennett No, I just hit ctrl-r every time I need to manual operate on the cloud k8s master. Alias it in bashrc/zshrc should be better if u need them to be executed by another program

**Comment by kfox1111** [comment]
I'd love a -l option too. while we can play subshell tricks in most places, its hard to give these to folks using kubectl on windows clients. Which are, unfortunately, still a thing.

**Comment by OJFord** [comment]
I more often want a `stern`-like partial name match than I want selector.

e.g. if you have:
```
widget-service-78d6bfc8d5-bftdf
widget-service-78d6bfc8d5-qurh4
# ...
```

I just want to do `kubectl exec -it widget-service- sh` or whatever, i.e. `exec` on any matching pod.

**Comment by cben** [comment]
Another annoyance is that `-o name --show-kind=false` has no effect, it still shows `pod/` (https://github.com/kubernetes/kubectl/issues/669).
If like me you feel go-template and jsonpath are "last resort", your next stop is `-o custom-columns=NAME:.metadata.name`.  That's workable but it adds a `NAME` headers line so you also need `--no-headers`.

I'd say `kubectl exec` is similar to `kubectl logs`, let's learn from that.  Both for uniformity and because `logs` usability is much better:
- It accepts `kubectl logs pod/...` syntax. :heavy_check_mark: 
- It also accepts some "higher" resources like `kubectl logs replicaset/...`,  `kubectl logs job/...`, `kubectl logs deployment/...`, even ``kubectl logs service/...`, resolving to a single (arbitrary?) pod under it.
  This IMHO is a hidden gem, not widely known [citation needed] but extremely useful.  :gem: :clap:
- Help claims it supports `-l` / `--selector` syntax to select pods by label, although it doesn't work for me (but I'm on old version)

**Comment by saamalik** [comment]
So on a Kubernetes 1.17.X server, the following works:
```
kubectl -n hubble-system exec  $(kubectl get pod -n hubble-system -l component=mongo -o name) -it mongo
```

**Comment by asrail** [comment]
> So on a Kubernetes 1.17.X server, the following works:
> 
> ```
> kubectl -n hubble-system exec  $(kubectl get pod -n hubble-system -l component=mongo -o name) -it mongo
> ```


Server version 1.15 already works like your command above, however I suggest adding ` --field-selector=status.phase==Running ` to the `get` command. 

For older versions, I use:

`kubectl -n namespace exec  $(kubectl -n namespace get po -o name --field-selector=status.phase==Running -l app=appname | head -1  | sed 's/pods\?\///' ) -ti `

For 1.15, I use:

`kubectl -n namespace exec  $(kubectl -n namespace get po -o name --field-selector=status.phase==Running -l app=appname' ) -ti `

**Comment by kvaps** [comment]
Not sure if everyone know, but 

```
kubectl exec deploy/<deployname>
```
Solves this issue to me.

**Comment by OJFord** [comment]
Agh! @kvaps, thank you! How long has that been possible without me realising..? :man_facepalming: 

(NB solves the 'run on any one' case that I care about, but not (unless there's some flag) the 'run on all' case that some others want.)

**Comment by willemodendaal** [comment]
@kvaps, I could kiss you!  
I've been trying to get VSCode to attach a debugger to a running Kubernetes pod for two days now. It's tricky because all the documentation shows you need to specify the container name in the launch configuration file, but the container names in K8s are somewhat dynamic, so that doesn't work (eg. [this article](https://blog.avenuecode.com/debugging-remote-containerized-apps-with-vs-code)). 
I even asked about it on the vscode-docker extension repo: https://github.com/microsoft/vscode/issues/89758#issuecomment-721659738

But this did the trick, instead of specifying the pod name in the launch config, I instead specified the deploy/deploymentName, because that always stays the same and it works! 
I can now attach a debugger to a running Kubernetes pod in VSCode.

**Comment by OliverCole** [comment]
Good workaround, but doesn't cover the other cases.
/remove-lifecycle stale

**Comment by soltysh** [comment]
`kubectl exec` along with a few others can easily find the first pod in a any workload (deployment, stateful set, daemon set, etc) and execute desired command.

/close

**Comment by malthe** [comment]
What @soltysh said is elaborated on in this answer: https://stackoverflow.com/a/65982378/647151

Basically, use `deploy/<deployment-name>` as the name passed to `kubectl exec`.

**Comment by OJFord** [comment]
As above, that solves my case, but not the 'run on all' matches that's also mentioned in OP, and what some here are primarily looking for. That's why the closure's unpopular (though I'm happy).

I assume I'm not able to, but:
/open

**Comment by andrewpollock** [comment]
I ended up here also with the same use case (I wanted to run a `df` on all my pods). 

Basically I want clusterssh/pssh type capability.
