### ISSUE TITLE
E0303: API Server unable to authenticate requests

### ISSUE THREAD

**Issue by classic70s** [kubernetes/kubernetes#88772]
**What happened**:
Have been using this cluster for 6+ months for internal application development and performance testing. Yesterday I began noticing kubectl command failures and would return this message:

The connection to the server (HOSTNAME):6443 was refused - did you specify the right host or port?

I discovered the Docker API server container continuously restarting :

[root@com-kube-master .kube]# docker ps -a | grep apiser
cb66685b8933        f15aad0426f5                                                                                                                         "kube-apiserver --..."   About a minute ago   Exited (2) About a minute ago                            k8s_kube-apiserver_kube-apiserver-com-kube-master.nonprod.abcdefg.com_kube-system_be3cd92e0bf5fb87ebcfac139df88836_1261
f34ea70c4cf7        k8s.gcr.io/pause:3.1                                                                                                                 "/pause"                 2 hours ago          Up 2 hours                                               k8s_POD_kube-apiserver-com-kube-master.nonprod.abcdefg.com_kube-system_be3cd92e0bf5fb87ebcfac139df88836_22

And inspecting the logs of these Pods reveals a problem with authentication:

[root@com-kube-master .kube]# docker logs k8s_kube-apiserver_kube-apiserver-com-kube-master.nonprod.abcdefg.com_kube-system_be3cd92e0bf5fb87ebcfac139df88836_1261

...
I0303 17:55:18.382381       1 controller.go:606] quota admission added evaluator for: leases.coordination.k8s.io
E0303 17:55:18.385125       1 authentication.go:89] Unable to authenticate the request due to an error: [invalid bearer token, Token has been invalidated]
...
E0303 17:55:18.388261       1 authentication.go:89] Unable to authenticate the request due to an error: [invalid bearer token, Token has been invalidated]
I0303 17:55:18.428885       1 cache.go:39] Caches are synced for AvailableConditionController controller
I0303 17:55:18.429024       1 cache.go:39] Caches are synced for APIServiceRegistrationController controller
I0303 17:55:18.429100       1 cache.go:39] Caches are synced for autoregister controller
I0303 17:55:18.429331       1 shared_informer.go:204] Caches are synced for crd-autoregister
E0303 17:55:18.435240       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 4334 [running]:
...
**Environment**:
- Kubernetes version (use `kubectl version`):
[root@com-kube-master ~]# kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
The connection to the server 10.190.67.31:6443 was refused - did you specify the right host or port?

- Cloud provider or hardware configuration:
VMWare cluster of VMs

- OS (e.g: `cat /etc/os-release`):
[root@com-kube-master ~]# cat /etc/os-release
NAME="Red Hat Enterprise Linux Server"
VERSION="7.7 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.7"
PRETTY_NAME="OpenShift Enterprise"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.7:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.7
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.7"

- Kernel (e.g. `uname -a`):
[root@com-kube-master ~]# uname -a
Linux com-kube-master.nonprod.abcdefg.com 3.10.0-1062.4.1.el7.x86_64 #1 SMP Wed Sep 25 09:42:57 EDT 2019 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:
- Network plugin and version (if this is a network-related bug):
Using the Weave n/w plugin.  not sure how to check version while cannot use kubectl

Maybe related to bug reported in #22351. However, the solution documented there requires
use of kubectl to cause k8s to regenerate the default token, and that is not available.

**Comment by liggitt** [comment]
Do you have the panic stack?

**Comment by xlw712** [comment]
How to solve this problem? I had this problem with 1.18 as well
---------------
E0509 07:01:01.643956       1 reflector.go:178] k8s.io/client-go/informers/factory.go:135: Failed to list *v1.VolumeAttachment: Get https://localhost:6443/apis/storage.k8s.io/v1/volumeattachments?limit=500&resourceVersion=0: dial tcp 127.0.0.1:6443: i/o timeout
I0509 07:01:01.643945       1 trace.go:116] Trace[1203627422]: "Reflector ListAndWatch" name:k8s.io/client-go/informers/factory.go:135 (started: 2022-05-09 07:00:31.643630565 +0000 UTC m=+3.293550751) (total time: 30.000300112s):
Trace[1203627422]: [30.000300112s] [30.000300112s] END
E0509 07:01:01.643963       1 reflector.go:178] k8s.io/client-go/informers/factory.go:135: Failed to list *v1.RoleBinding: Get https://localhost:6443/apis/rbac.authorization.k8s.io/v1/rolebindings?limit=500&resourceVersion=0: dial tcp 127.0.0.1:6443: i/o timeout
I0509 07:01:01.644015       1 trace.go:116] Trace[1028829824]: "Reflector ListAndWatch" name:k8s.io/client-go/informers/factory.go:135 (started: 2022-05-09 07:00:31.643761123 +0000 UTC m=+3.293681313) (total time: 30.000243455s):
Trace[1028829824]: [30.000243455s] [30.000243455s] END
E0509 07:01:01.644023       1 reflector.go:178] k8s.io/client-go/informers/factory.go:135: Failed to list *v1beta1.IngressClass: Get https://localhost:6443/apis/networking.k8s.io/v1beta1/ingressclasses?limit=500&resourceVersion=0: dial tcp 127.0.0.1:6443: i/o timeout
I0509 07:01:01.644159       1 trace.go:116] Trace[106217547]: "Reflector ListAndWatch" name:k8s.io/client-go/informers/factory.go:135 (started: 2022-05-09 07:00:31.643912996 +0000 UTC m=+3.293833194) (total time: 30.000236567s):
Trace[106217547]: [30.000236567s] [30.000236567s] END
E0509 07:01:01.644167       1 reflector.go:178] k8s.io/client-go/informers/factory.go:135: Failed to list *v1.ClusterRoleBinding: Get https://localhost:6443/apis/rbac.authorization.k8s.io/v1/clusterrolebindings?limit=500&resourceVersion=0: dial tcp 127.0.0.1:6443: i/o timeout
I0509 07:01:01.644229       1 trace.go:116] Trace[1368490643]: "Reflector ListAndWatch" name:k8s.io/client-go/informers/factory.go:135 (started: 2022-05-09 07:00:31.643989862 +0000 UTC m=+3.293910047) (total time: 30.000223779s):
Trace[1368490643]: [30.000223779s] [30.000223779s] END
E0509 07:01:01.644241       1 reflector.go:178] k8s.io/client-go/informers/factory.go:135: Failed to list *v1.PriorityClass: Get https://localhost:6443/apis/scheduling.k8s.io/v1/priorityclasses?limit=500&resourceVersion=0: dial tcp 127.0.0.1:6443: i/o timeout
I0509 07:01:01.644356       1 trace.go:116] Trace[1186381904]: "Reflector ListAndWatch" name:k8s.io/client-go/informers/factory.go:135 (started: 2022-05-09 07:00:31.644157605 +0000 UTC m=+3.294077793) (total time: 30.000185367s):
Trace[1186381904]: [30.000185367s] [30.000185367s] END
E0509 07:01:01.644367       1 reflector.go:178] k8s.io/client-go/informers/factory.go:135: Failed to list *v1.StorageClass: Get https://localhost:6443/apis/storage.k8s.io/v1/storageclasses?limit=500&resourceVersion=0: dial tcp 127.0.0.1:6443: i/o timeout
F0509 07:01:01.645541       1 controller.go:161] Unable to perform initial IP allocation check: unable to refresh the service IP block: Get https://localhost:6443/api/v1/services: dial tcp 127.0.0.1:6443: i/o timeout
E0509 07:01:01.679314       1 authentication.go:53] Unable to authenticate the request due to an error: [invalid bearer token, Token has been invalidated]
