### ISSUE TITLE
Make test/e2e/core.go download compressed log files, not cat plain text over the wire

### ISSUE THREAD

**Issue by quinton-hoole** [kubernetes/kubernetes#8879]
ref: #8852

**Comment by quinton-hoole** [comment]
@fejta FWIW I think that this is probably the root cause behind log uploads to GCS frequently timing out and failing.

**Comment by fejta** [comment]
Thanks for reopening!

Multiple quarters elapsed without anyone making progress. I closed this class of bug because I want to bring attention to any that are still interesting to fix.

This looks like something interesting to fix at the infrastructure level, especially since GCS can compress data for us on the fly.
