### ISSUE TITLE
Support running multiple (out-of-tree) CCMs concurrently and conflict-free

### ISSUE THREAD

**Issue by timoreimann** [kubernetes/kubernetes#88820]
**What would you like to be added**:

I'd like to be able to run multiple out-of-tree cloud controller managers (CCMs) concurrently without conflict. That is, it should be possible to use resources like nodes and load balancers and have exactly one of many running CCMs handle them while others would ignore them.

**Why is this needed**:

My primary use case is the ability to end-to-end-test changes to a CCM implementation in a cluster that already comes with an existing (usually released) CCM. The latter is a consequence of the fact that it is much easier (and suitable) to spin up a cluster for the target cloud of my CCM using cloud-specific tooling (e.g., [`doctl` ](https://github.com/digitalocean/doctl/) in the case of DigitalOcean) than it is to create a vanilla cluster with generic tooling (e.g., `kubeadm` or `kops`). However, the CCM instance that comes pre-built in my production cluster prevents me from testing that CCM-under-test instance because the current architecture assumes a single out-of-tree CCM to run.

**Comment by timoreimann** [comment]
Inspiration could be drawn from Storage or Ingress where classes can be defined and associated with resources so that only a managing controller responsible for a given class takes action.

**Comment by andrewsykim** [comment]
Related discussion here: https://github.com/kubernetes/kubernetes/pull/73171#issuecomment-460077289

**Comment by MorrisLaw** [comment]
Assigned myself the ticket, but @timoreimann will be working on it.

**Comment by timoreimann** [comment]
Outcome of today's SIG meeting: I am going to put together a PoC PR to showcase what an implementation based on labels (and using the existing cluster name flag for the sake of being the easiest) could look like. The result should help us to decide how to move forward, which could be a KEP if the idea finds agreement.

**Comment by akafazov** [comment]
We have setup Kubernetes  to run with nodes on multiple cloud providers within the same cluster. Currently, this issue restricts us on just supporting 1 provider's LoadBalancer.

**Comment by cheftako** [comment]
https://github.com/kubernetes/kubernetes/blob/release-1.21/staging/src/k8s.io/cloud-provider/app/controllermanager.go#L219 is where the leader election configuration is used to determine if this CCM is the primary or a hot backup. The simple version of this (using the defaults) assumes that all the CCMs are running the same set of controllers. You can then run as many instances of the CCM as you want but only 1 will be doing the work. The others will be waiting on the first to lose an election. Then they compete to take over.

The "ResourceName" determines which workers are competing with one another. So if you start up two sets of CCMs configured to use a different ResourceName, they would compete within their set but not with CCMs of the other set. This however does not prevent the different sets from attempting to run the same controllers (which is probably bad). https://github.com/kubernetes/kubernetes/blob/release-1.21/cmd/cloud-controller-manager/main.go#L71 is a partial example of how you can control the controllers for a CCM. You could write code to have you CCM determine is controller set based on the leader election ResourceName. This would help ensure that the set of controllers corresponds to the sets of running CCMs. 

API Machinery has periodically discussed way to shard controller managers. This is problematic however as the individual controllers interact (even if its indirectly through resources), resources such as node and namespace end up correlating along different dimensions. In addition CPU is not our only concern. Currently get good memory usage (relatively) at the cost of CPU. If we try sharding, this may improve our CPU usage but likely at a significant memory cost as our client caches are likely to cache everything, everywhere. (Rather than everything in 1 process)

**Comment by YanzhaoLi** [comment]
Any updates?

**Comment by lubronzhan** [comment]
Hi @timoreimann Could you share the updates on this issue?
Thank you

**Comment by lubronzhan** [comment]
Hi @timoreimann do you have any updates on this? We can also provide help if you needed

**Comment by timoreimann** [comment]
Sorry, I have not been able to work on this myself. Moreover, my org is probably going into the direction of leveraging Cluster API to create clusters on specific CCM versions, which we find more suitable for our case.

If anyone else wants to pick up this issue, feel free to go for it.

/remove-lifecycle rotten

**Comment by sergelogvinov** [comment]
@timoreimann 

Can we add 5-minute uptime wait before trying to delete the uninitialized node?

It is enough to initialize (set ProviderID and other labels) the node by another CCM. After that, CCM with different ProviderID will not touch the foreign node. 

example: https://github.com/sergelogvinov/cloud-provider/commit/ef3c7fed6ddfe7b7525a1c51cf1b7aa90ad75162
