### ISSUE TITLE
Allow for more flexible retry logic with Cloud Controller Manager

### ISSUE THREAD

**Issue by kamaln7** [kubernetes/kubernetes#88902]
**What would you like to be added**:
Currently, CCM uses exponential backoff when failing to process a service change. It would be great if this behavior—not only the minimum and maximum delay values—could be adjusted if needed.

https://github.com/kubernetes/kubernetes/blob/8508875e4d400c1454561aa6d879860984bcdf59/pkg/controller/service/controller.go#L54-L58
https://github.com/kubernetes/kubernetes/blob/8508875e4d400c1454561aa6d879860984bcdf59/pkg/controller/service/controller.go#L150

**Why is this needed**:
It is possible to change the minimum and maximum delay values but in some cases that's not enough. Changing those values affects all kinds of service changes, and it would be great if it were possible to adjust that behavior in specific circumstances.

Take for example a new Load Balancer being created. We might want to reduce the max retry delay to just a few seconds long so it's ready within the cluster with minimal delay, but for other types of sync failures, keep the max retry delay set to 5 minutes as to not overload the API endpoint that is being polled.

/sig cloud-provider

/cc @timoreimann — Timo, could you please take a look and make sure this is in line with what we discussed?

**Comment by timoreimann** [comment]
Thanks for filing the ticket, @kamaln7. That looks right to me.

It's worth mentioning that the way we have implemented waiting for an LB to become ready (after it has been created successfully) in DigitalOcean's CCM is by returning an error to the cloud provider Service controller and leveraging the built-in retry mechanism. In previous versions, we build the is-the-LB-ready retry loop into the `EnsureLoadBalancer` implementation; however, I believe this comes with the downside that further Service updates get blocked until the retry loop has completes, which may cause unnecessary delays if, say, the user decides to delete an LB quickly after creation. (Curious how other cloud providers implement this, by the way.)

Going forward, a change I can imagine is to support two kinds of retry delays: one for true errors and one for "progress polling", where the decision on which one to pick could be based on the error value/type returned by the CCM interface method. For instance, we could introduce a new `ProgressRetryErr` on which the controller would choose the more aggressive retry policy.

With both retry delays configurable, CCM implementors could tune them to their needs.

I'd be happy to hear feedback on this one. Given consent, I'd also be happy to drive the effort needed.

**Comment by timoreimann** [comment]
We discussed this in today's SIG meeting: I'm going to check if the controller really does not allow concurrent reconciles (this was my assumption/understanding but chances are I missed something). If it turns out to support that I think we should be good. Otherwise, we can explore possibilities to distinguish between different retry strategies possibly based on errors returned.

**Comment by timoreimann** [comment]
Quoting myself from a few months ago:

>I'm going to check if the controller really does not allow concurrent reconciles (this was my assumption/understanding but chances are I missed something). If it turns out to support that I think we should be good.

I tested this and confirmed that concurrent reconciles do **not** work: the service controller uses a work queue which [is designed to not invoke multiple workers on the same key at the same time](https://github.com/kubernetes/kubernetes/blob/d633e03cf69ac68074d15873ab777f61aece1127/staging/src/k8s.io/cloud-provider/controllers/service/controller.go#L255-L256). This makes sense because otherwise all kinds of bad, racy things could happen.

I'll move forward with creating a minimalistic PR to demonstrate the progress retry indicator mentioned at https://github.com/kubernetes/kubernetes/issues/88902#issuecomment-595827223.

**Comment by timoreimann** [comment]
Need to find some time to move forward on tgis one, really.

/remove-lifecycle stale

**Comment by timoreimann** [comment]
/reopen

I really still want this...
