### ISSUE TITLE
nodePort == 0 should be omitted

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#8901]
omitEmpty does not omit integer fields, but we really want omitEmpty on nodePort.

@thockin suggested using replica count as an example for how to do this.

(Or is it possible to have omitEmpty recognize int == 0 as empty?)

**Comment by thockin** [comment]
I think we should fix it, but it's not CRITICAL for 1.0

**Comment by hobti01** [comment]
Thanks for the pointer @thockin As a user this is tricky to use.  In a json file I must specify nodePort even though I don't want to use nodePort.  Since it doesn't have omitEmpty I know it's a required field, but the description tells me not to set it.  Maybe more description would help in the short term?

**Comment by thockin** [comment]
You never have to set a value if you're OK with the default.  0 is the
default.  If anything gives you an error which is fixed by setting nodePort
to 0 (with one exception - below) it's a bug.

One exception: downgrading from "type": "LoadBalancer" or "NodePort" to
"ClusterIP" - nodePort must be reset to zero.  This bug would make that
better, I think.

**Comment by bgrant0607** [comment]
The nodePort field shouldn't be considered required. Fix is in #12831.

In order to omit such fields from output, we currently need to convert them to pointers.

**Comment by techtonik** [comment]
So can this be closed?
