### ISSUE TITLE
[Flaking Test] verify-1.18 (ci-kubernetes-verify-beta)

### ISSUE THREAD

**Issue by droslean** [kubernetes/kubernetes#89052]
**Which jobs are failing**:
`verify-1.18 (ci-kubernetes-verify-beta)`

**Since when has it been failing**:
`11 March 00:56 PDT`

**Testgrid link**:
https://testgrid.k8s.io/sig-release-1.18-blocking#verify-1.18

**Reason for failure**:
see https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-verify-beta/1237711230773235713

**Anything else we need to know**:
/cc @kubernetes/ci-signal 
/cc @kubernetes/release-managers 
/sig testing

/priority critical-urgent
/milestone v1.18

**Comment by spiffxp** [comment]
/remove-kind failing test
/kind flaking test
The job isn't continuously failing

The spyglass link isn't helpful, because it shows all tests passing.

So I looked at testgrid for release-1.8, and compared with master
- https://testgrid.k8s.io/sig-release-1.18-blocking#verify-1.18&graph-metrics=test-duration-minutes&width=5
- https://testgrid.k8s.io/sig-release-master-blocking#verify-master&graph-metrics=test-duration-minutes&width=5

It looks like both are occasionally timing out, and it's happening with more frequency over the last week.  Looking at the durations for all of the tests, there's no one test that's the culprit.  Instead, they all seem to jump to 2-3x their normal duration at the same time.

This has the feel of the job occasionally being scheduled on a node with a noisy neighbor, but I'm not sure what resource is contended.

**Comment by spiffxp** [comment]
/retitle [Flaking Test] verify-1.18 (ci-kubernetes-verify-beta)

**Comment by spiffxp** [comment]
Opened https://github.com/kubernetes/test-infra/pull/16749 to see if more cpu resources help

**Comment by spiffxp** [comment]
/remove-priority critical-urgent
/priority important-soon
I'm downgrading priority because timeouts are happening less often now, and I'm seeing three passes in a row against the same commit.

The prow.k8s.io build cluster was increased in size a few days ago.  The PR to add more CPU to the CI jobs landed yesterday.

We are still occasionally hitting timeouts, and I still suspect resource contention of something that isn't CPU.  I can't tell whether this is the verify job having crossed a threshold due to underlying code changes, or the build cluster being more contended than usual.

**Comment by alejandrox1** [comment]
Thank you for looking into this @spiffxp !
/milestone v1.19

**Comment by droslean** [comment]
the job hasn't flake for more than a week. Closing
/close
