### ISSUE TITLE
[Failing Test] gce-cos-.*-scalability tests are failing since 03/06

### ISSUE THREAD

**Issue by droslean** [kubernetes/kubernetes#89051]
**Which jobs are failing**:
`gce-cos-1.18-scalability-100 (ci-kubernetes-e2e-gci-gce-scalability-beta )`

**Since when has it been failing**:
`10th March 05:01 PDT`

**Testgrid link**:
https://testgrid.k8s.io/sig-release-1.18-blocking#gce-cos-1.18-scalability-100

**Reason for failure**:
see https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability-beta/1237710225755082754

**Anything else we need to know**:
/cc @kubernetes/ci-signal 
/priority critical-urgent
/milestone v1.18
/sig scalability

**Comment by oxddr** [comment]
/assign 

I've already started looking into this. I hope to come back with more analysis, tomorrow CEST morning.

**Comment by oxddr** [comment]
Other tests are failing too: https://testgrid.k8s.io/sig-release-1.17-blocking#gce-cos-1.17-scalability-100, https://k8s-testgrid.appspot.com/sig-scalability-gce#gce-cos-1.16-scalability-100, https://k8s-testgrid.appspot.com/sig-scalability-gce#gce-cos-master-scalability-100

/retitle [Failing Test] gce-cos-.*-scalability tests are failing since 03/06

I am going to focus the debugging on 1.18 though - I suspect the problems might be related. 

Quick look at Testgrid: ![zgAnxZmGOaG](https://user-images.githubusercontent.com/30298753/76509679-b2507500-6450-11ea-9b13-4529a171c593.png)

1. tests becoming red is correlated with a change to test-infra; however in the new commit a single test has been removed https://github.com/kubernetes/test-infra/commit/2ff813cfc4f9371aa9c3a9937907aaac2d5fa494
1. there is no correlation between change in k/k commit; commit at which tests started to fail: https://github.com/kubernetes/kubernetes/commit/2df727bdc

**Comment by oxddr** [comment]
Tests for master branch started to fail earlier (03/06) that for release branches (03/10). First commit with failed test: https://github.com/kubernetes/kubernetes/commit/570851149

**Comment by oxddr** [comment]
Failing tests more or less correlate with fixing and enabling node-killer. I've disabled it on master to check if it helps: https://github.com/kubernetes/test-infra/pull/16752

**Comment by oxddr** [comment]
It seems that disabling node-killer helped. However our tests should be resilient to restarts introduced by node-killer and in a longer-term it should be enabled. @jprzychodzen could you please have a look at recent red runs and check if node-killer behaved as expected?

**Comment by hasheddan** [comment]
@oxddr @jprzychodzen this test is looking pretty healthy lately, any updates here?

**Comment by hasheddan** [comment]
Going to close this out as this job has been looking healthy for some time 👍 

/close

**Comment by jprzychodzen** [comment]
Just for cleaning and reference purpose - Node Killer is now disabled, tracking an effort to enable it in kubernetes/perf-tests#1005
