### ISSUE TITLE
Pod lifecycle, termination can be improved around LBs and grace period

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#89263]
**What would you like to be added**:

This is about Pods which have LBs in front of them (even clusterIP).  The normal shutdown sequence today is that the Pod is deleted, which simultaneously triggers it to be removed from endpoints and for kubelet to send SIGTERM (or whatever stopsignal is set to) to all containers.

Because the LB programming and the Pod "grace period" are concurrent, the LBs will still forward packets to the terminating pod.  In many cases that causes errors (e.g. nginx will stop accepting upon SIGTERM.

This turns out to be VERY confusing for people and has caused no end of bug reports and blog posts.  People EXPECT that pods which are Terminating, there is no more traffic coming into them.  We fail that expectation.

The common hack is to add a `preStop` lifecycle to `exec sleep 60` or similar.  This gives the LBs time to de-program before SIGTERM is delivered.  HACK.

 I think we should do better.  To REALLY get it right, we would want something like pod `readinessGates` but for shutdown.  I don't think we need to go that far, but we could formalize the pre-SIGTERM delay independent of preStop.

**Why is this needed**:

Users are documenting the nasty hacks that are needed to work around this gap in our lifecycle model.  It is becoming "de rigeur" to sleep in preStop.  That is sad.

**Comment by vllry** [comment]
This would be extremely useful.

I have worked around this by using a preStop, which curls an internal service, which allows the call to return only when the calling pod is fully deregistered from the load balancer. The preStop is particularly awkward to do as an infra/service boundary crossover. Anyone who uses this ingress needs the preStop to do this, which is extra awkward for custom preStop users.

Would a boolean ready/wait for shutdown suffice? I can see that being enough for the typical user, but rather like readiness gates, some users will have multiple bits of infra that need to block the shutdown.

**Comment by thockin** [comment]
I'm not sure that a bool carries enough info.  I don't have a strong sense
of "correctness" for this design yet.

It could be a `preTerminationGarcePeriod` time (equivalent to the sleep in
preStop).

It could be `podTerminationGates` (akin to readinessGates).

It could be a different `lifecycle` hook maybe.

It could be simply adding a `sleep` action to preStop maybe.

Obviously, time-based models are relatively simple but not sophisticated.
How much sophistication do we actually need here?

**Comment by vllry** [comment]
> Obviously, time-based models are relatively simple but not sophisticated.
How much sophistication do we actually need here?

IMO a preStop sleep would still be a big improvement, but definitely not ideal. I'd be much happier with the assurance that an overly slow drain wouldn't drop connections. There are many ways a drain could take unexpectedly long, e.g. LB API rate limiting or network control plane failures.

I'm not sure if a lifecycle hook would be the right solution. Because they are container-level, it would still require a load balancer (or other infra-related) drain script being built into the applicable container(s). That coupling feels awkward to me. A pod-level preStop would at least allow a dedicated sidecar to handle the process out of band of the user-defined containers.

A counterpart to readiness gates feels like the best API to me, but I appretiate that it's a lot to add for a specific problem.

**Comment by pjferrell** [comment]
Would it be possible to leverage finalizers and a small change to kubelet termination behavior?

Suggested flow:

1. Pod is created and scheduled to a node
2. Endpoints controller determines that it is ready and adds itself to the pod finalizers
3. Pod deletion occurs (deletionTimestamp is set)
4. Kubelet observes Pod deletion but requeues until finalizers list is empty (or only containing standard finalizers of foregroundDeletion / orphan)
5. Endpoints controller observes Pod deletion, removes the Pod reference in Endpoint/EndpointSlice, and requeues the Pod with a drainDelay based on how long we want to allow for LB to observe change.
6. After drainDelay, Endpoints controller reprocesses the Pod deletion, determines that it is not referenced in Endpoint/EndpointSlice, and removes itself from the pod finalizers.
7. Kubelet observes Pod finalizers change and triggers normal termination sequence.

Optionally, kubelet could restrict this behavior of gated deletion to only endpoint/standard finalizers.

**Comment by thockin** [comment]
> 1. Pod is created and scheduled to a node
> 2. Endpoints controller determines that Pod is Ready and adds itself to the pod finalizers and updates Endpoint/EndpointSlice with reference to Pod
> 3. Pod deletion occurs (deletionTimestamp is set)
> 4. Kubelet observes Pod deletion but requeues until finalizers list is empty (or only containing standard finalizers of foregroundDeletion / orphan)

This is interesting.  The SIGTERM would be delayed, so even apps that do the
wrong thing (stop accepting) would be handled.

> 5. Endpoints controller observes Pod deletion, removes the Pod reference in Endpoint/EndpointSlice, and requeues the Pod with a drainDelay based on how long we want to allow for LB to observe change.

We would need to couple this with Andrew's change to track terminating pods.
If there are other viable pods, in-bound traffic would go to them  If ther are
not, we would still route in-bound traffic to the terminating ones.

> 6. After drainDelay, Endpoints controller reprocesses the Pod deletion, determines that it is not referenced in Endpoint/EndpointSlice, and removes itself from the pod finalizers.

The real problem here is that it is still time-based.  What people do today is
`sleep 300` (or however long) in their pod `preStop`.  This just moves the
sleep from kubelet to each endpoint controller.

The complete fix would be (in addition to this kubelet trick) each LB
controller to add itself to the pod's finalizers.  The pod would be blissfully
unaware of the fact that it ws being terminated until each of the controllers
had drained that pod out of their pools. This is basically the
"unreadinessGates" model.

This would kind of make terminationGracePeriod be meaningless, which is not
good.  Kubelet needs to have the authority to really kill pods, which can
probably ONLY be time-based.

> 7. Kubelet observes Pod finalizers change and triggers normal termination sequence.

> Optionally, kubelet could restrict this behavior of gated deletion to only endpoint/standard finalizers.

Unfortunately finalizer values are not ACLed.

The real problem with this is that it s a breaking change.  I don't know what
this would do to people who use finalizers on pods already.

**Comment by otterley** [comment]
Hi @thockin, 

> To REALLY get it right, we would want something like pod readinessGates but for shutdown.

Absent a tighter coupling between pods and load balancers, I think this is the best solution. Basically the inverse of readiness gates.

Just some data to add: we handle customer concerns on a frequent basis who are having trouble with connections being reset because load balancers have not had sufficient time to properly drain connections from pod targets. As you said, adding `preStop` hooks to sleep can work, but it's very hack-ish; and it unnecessarily burdens customers with having to change their otherwise-clean pod specs, often across the board.

One thing I want to add is that a reliable draining procedure is slower than a lot of customers may believe, especially with persistent connections. Drains can take minutes or hours (worst case) if users (clients) are not to notice them. It's important that expectations be calibrated accordingly, since we've probably trained deployment users over time to believe updates are supposed to be fast. They're fast because K8S arguably (and probably unintentionally) cut corners in this functionality to date.

**Comment by foriequal0** [comment]
Any progress on this issue?
