### ISSUE TITLE
Server-side apply doesn't work for APIService

### ISSUE THREAD

**Issue by apelisse** [kubernetes/kubernetes#89264]
It looks like the openapi is not routed properly to set-up the apiservice so apply requests will fail because the fieldmanager is not set-up properly.

/cc @jennybuckley @liggitt 
/sig api-machinery
/priority important-soon
/kind bug

**Comment by liggitt** [comment]
OpenAPIModels is set to nil for the kube-aggregator server config (which serves the APIServices API):
```go
	// Prevent generic API server to install OpenAPI handler. Aggregator server
	// has its own customized OpenAPI handler.
	openAPIConfig := c.GenericConfig.OpenAPIConfig
	c.GenericConfig.OpenAPIConfig = nil
```

This is done because the kube-aggregator has a special openapi handler that aggregates all the other server's openapi docs.

The `GenericConfig.OpenAPIConfig` field controls (at least) two things:
* /openapi endpoint serving (which we want kube-aggregator to continue to customize)
* creation of the field manager (which we want kube-aggregator to behave consistently on)

We need to decouple presence of OpenAPIConfig and construction of StaticOpenAPISpec (which is needed by the field manager) from construction/installation of OpenAPIVersionedService. That might be a little tricky to untangle, since construction of StaticOpenAPISpec includes paths/operations. The field manager only needs the gvk/schemas.

**Comment by apelisse** [comment]
/lifecycle frozen

This is not something we want closed by accident.

**Comment by apelisse** [comment]
For reference:
```go
	// Prevent generic API server to install OpenAPI handler. Aggregator server
	// has its own customized OpenAPI handler.
	openAPIConfig := c.GenericConfig.OpenAPIConfig
	c.GenericConfig.OpenAPIConfig = nil
```
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/kube-aggregator/pkg/apiserver/apiserver.go#L168-L169

**Comment by Jefftree** [comment]
Additional lines for reference:

This is roughly how SSA consumes the openapi spec.

openapi spec -> openapi proto model -> typeconverter -> SSA field manager

For built in types, openapi spec -> openapi model

https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/server/genericapiserver.go#L491

openapi model -> typeconverter

https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/server/genericapiserver.go#L430-L434

A similar thing happens for CRDs

https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/customresource_handler.go#L677-L689

As liggitt mentioned, SSA only requires a subset of the information in the openapi proto model.
