### ISSUE TITLE
Update bazel to v2.2.0

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/kubernetes#89414]
**What would you like to be added**:
- Update bazel to v2.2.0: https://github.com/kubernetes/kubernetes/pull/89430
- Document how to update bazel in kubernetes/kubernetes

**Why is this needed**:
ref: https://github.com/kubernetes/kubernetes/issues/88553#issuecomment-602411809

/assign @justaugustus @ixdy @fejta @BenTheElder @Katharine 
cc: @kubernetes/release-engineering 
/sig testing release
/area release-eng
/milestone v1.19
/priority important-soon
/kind feature documentation

**Comment by justaugustus** [comment]
I've started something here: https://github.com/kubernetes/kubernetes/pull/89342

More than anything, we need to complete this issue with a transfer of some of the tribal knowledge around bazel.
The current maintenance experience leaves a lot to be desired.

**Comment by justaugustus** [comment]
/assign @mikedanese 

Looks like a few PRs were opened up to start moving in this direction: https://github.com/kubernetes/test-infra/pull/16908, https://github.com/kubernetes/test-infra/pull/16910, https://github.com/kubernetes/test-infra/pull/16912, https://github.com/kubernetes/test-infra/pull/16913, https://github.com/kubernetes/test-infra/pull/16916, https://github.com/kubernetes/test-infra/pull/16918

@mikedanese @fejta -- Can you provide details here on how you're proceeding to do the upgrades?

**Comment by mikedanese** [comment]
Bazel build and test are fixed in https://github.com/kubernetes/kubernetes/pull/89430, just waiting on a kubekins version bump. It looks like this one: https://github.com/kubernetes/test-infra/pull/16904 doesn't have @fejta's fix: https://github.com/kubernetes/test-infra/pull/16910

**Comment by mikedanese** [comment]
Friction log so far (tainted by my unfamiliarity with test and release infra):
* We've had a lot of drift with bazel and repo-infra because we've been putting this off for so long.
* There are so many test images that need to be updated and it's hard to know which for a new comer.
* We want this to tie the upgrade with a change in k/k. Because the  spans k/test-infra, k/repo-infra, k/release, there's a fair bit of shenanigans that we need to do to coordinate this cutover. This would have been simpler if the change could have been isolated to a single repo.

**Comment by mikedanese** [comment]
We broke 1.16 and 1.15 branch jobs because those branches did not have a .bazelversion files: https://github.com/kubernetes/test-infra/pull/16910#issuecomment-603540353

**Comment by droslean** [comment]
@justaugustus I moved this to 1.20, but it seems that there was a lot of activity. Is this issue actually done?
