### ISSUE TITLE
Access through clusterip very slow on other node but works well using nodePort

### ISSUE THREAD

**Issue by cy503328434** [kubernetes/kubernetes#89622]
here is my version info
NAME           STATUS   ROLES    AGE   VERSION   INTERNAL-IP     EXTERNAL-IP   OS-IMAGE                KERNEL-VERSION                CONTAINER-RUNTIME

k8s-master01   Ready    master   82m   v1.18.0   1.2.3.4   <none>        CentOS Linux 7 (Core)   3.10.0-1062.12.1.el7.x86_64   docker://19.3.8

k8s-node01     Ready    <none>   78m   v1.18.0   1.2.3.5   <none>        CentOS Linux 7 (Core)   3.10.0-1062.12.1.el7.x86_64   docker://19.3.8

I installed fannel like that

`kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml`

my svc:

kubectl get svc
NAME               TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)          AGE
api-gateway        NodePort    10.107.109.180   <none>        5555:30555/TCP   46m

when I curl 10.107.109.180:5555/test/1 for testing ,but responsing very slow in other node.
It works well using curl nodeip:30555/test/1 

/sig network

**Comment by caseydavenport** [comment]
There was some recent discussion around performance issues with VXLAN checksum offload which manifested themselves when using Flannel or Calico in VXLAN mode - I wonder if that is what you're hitting here.

Here's the mailing list thread: https://groups.google.com/forum/#!topic/kubernetes-sig-network/JxkTLd4M8WM

I bring it up because accessing the pod or service IP will likely use flannel's VXLAN datapath, whereas hitting the node directly will just use the node's network.

You might want to try disabling VXLAN offload on your nodes and see if it helps at all.

You'd need to run something like this:

```
ethtool --offload <flannel device> rx off tx off
```

(disclaimer: I haven't tried that command myself!)

**Comment by aojea** [comment]
should we aggregate/redirect all these flannel/slowness/vxlan issues?

**Comment by rikatz** [comment]
/close 

We'll deal with all those CentOS 7 + vxlan + tx offload issues in #88986
