### ISSUE TITLE
Kubernetes 1.18 re-introduces previously fixed Azure AD OIDC regression

### ISSUE THREAD

**Issue by dharmab** [kubernetes/kubernetes#89663]
https://github.com/kubernetes/kubernetes/pull/87590 re-introduced the regression previously reported in https://github.com/kubernetes/kubernetes/issues/87464. Please see #87464 for technical details of the change and how it blocks cluster upgrades.

As a result, **There is no upgrade path for Kubernetes clusters using Azure AD OIDC to upgrade from 1.17.X to 1.18.0**.

This change should be reverted so that clusters can be upgraded. It should not have been merged without a flag or other option to toggle the behavior.

cc @weinong, @feiskyer @liggitt

**Comment by liggitt** [comment]
Can you provide more details of what you are seeing?

As I understand it, the regression reported in https://github.com/kubernetes/kubernetes/issues/87464 was between kubectl and API server oidc authentication. That was introduced in 1.17.1, and fixed in 1.17.2 by reverting https://github.com/kubernetes/kubernetes/pull/87540.

https://github.com/kubernetes/kubernetes/pull/87590 did not reintroduce the kubectl change, so it is unrelated to what was reported in https://github.com/kubernetes/kubernetes/issues/87464.

**Comment by feiskyer** [comment]
same questions with @liggitt. @dharmab could you share the details of the issues you met?

**Comment by jcrowthe** [comment]
As I was the OP who opened  #87464, I went and tested this. 

I do not see a functionality change in 1.18 that breaks Azure AD OIDC. Upgrades between the two versions appear seamless at this time. I tested with a mixture of kubectl versions as well.

**Comment by weinong** [comment]
@dharmab do you happen to have `spn:` prefix in apiserver-id in kubeconfig?

in the meantime, you may consider to use https://github.com/Azure/kubelogin which uses exec plugin.

**Comment by weinong** [comment]
@jcrowthe i confirmed a bug #89672 where the token audience `spn:` prefix got added apiserver-id in kubeconfig when you run kubectl multiple times.

**Comment by dharmab** [comment]
I think some wires were crossed in my environment, since I'm having trouble reproducing OIDC issues.

Since #89672 exists with more details, I'll close this report. 

Additionally, I'd like to express an apology for the abrasive tone in the original report. It's been a very long and stressful month, but that didn't need to be reflected in the bug report. Thanks @weinong, @feiskyer and @liggitt for your responses and the work you put into this community.
