### ISSUE TITLE
Automatically assign reviewer from sig-instrumentation to PRs changing metrics

### ISSUE THREAD

**Issue by serathius** [kubernetes/kubernetes#89788]
**What would you like to be added**:
Automatically assigning reviewer from sig-instrumentation to PRs changing metrics

**Why is this needed**:
Having sig-instrumentation reviewer will help improving quality of metrics in k8s.  

There were two ideas for this:
* Move all metrics to subdirectories with label in OWNERS 
* Implement plugin in prow (proposed by @logicalhan)
* Presubmit that comments on PR (proposed by @alvaroaleman)

For first solution we would need to protect against missing labels by adding static analysis. We would enforce that verifies that directories that import "k8s.io/component-base/metrics" have a sig/instrumentation label in OWNERS file. 
(+) relies on existing mechanism in OWNERS.
(-) amount of work to move metrics
(-) worse contributor experience

Second idea is to implement prow plugin that assigns additional reviewer. More about prow plugins https://github.com/kubernetes/test-infra/blob/master/prow/plugins/README.md
(+) We can parse only small subset of files that changed
(-) Requires building custom mechanism

Third idea is to add presubmit that can commet on a PR with /cc $some_metrics_reviewer.
(-) Require setting up a github account

/assign
/sig instrumentation
/priority important-longterm
/cc @logicalhan

**Comment by logicalhan** [comment]
Yay!! Awesome!!

**Comment by serathius** [comment]
Updated issue to list two ideas for solution. I will look for someone from sig-testing/prow who can help us decide.
PTAL @logicalhan

**Comment by logicalhan** [comment]
I prefer the second option, because we can do it without buy-in (so we can just do it) from all the other SIGs (except testing, of course), so I suspect it's faster/easier to accomplish.

**Comment by alvaroaleman** [comment]
Hm, this is not a problem that has an obvious ideal solution. The prow plugin has the drawback that development will be cumbersome, because you only get feedback when a new version of Prow is deployed, which happens once a day at most. 

Another option could be to build a tool that runs in a presubmit and comments with a `/cc $some_metrics_reviewer` on the pull if need be. This would require setting up a github account though.

**Comment by logicalhan** [comment]
I did a quick grep across the code base, and it looks like there are ~20ish files named `metrics.go` which also live in a directory called `metrics`. 

Possibly we can add a sub OWNERS files in those existing directories so that we can approve/review/auto-label changes for those files, if people are okay with it. That may be a decent stop-gap but it won't be comprehensive.

**Comment by BenTheElder** [comment]
definitely x-ref https://github.com/kubernetes/test-infra/issues/13994 for the second choice.

this issue is probably best tracked in k/test-infra

https://github.com/kubernetes/kubernetes/pull/90220 seems like a positive step towards implementing this.
at worse you can review PRs after the fact.

@liggitt set up something similar w/ a label for API review

**Comment by ehashman** [comment]
I think this should have been closed with #90220 merging, this is done.

/close
