### ISSUE TITLE
fifo q would be blocking in Pop() while it acquired the lock

### ISSUE THREAD

**Issue by Colstuwjx** [kubernetes/kubernetes#89880]
**What happened**:
I'm going to use [fifo](https://github.com/kubernetes/kubernetes/blob/89c615f9c448503b674a0d61bfa8e413cefa4104/staging/src/k8s.io/client-go/tools/cache/fifo.go#L111) as an util library, and found that it would be blocking by Pop() call, think about the following sample:

```
package main

import (
	"log"
	"strconv"
	"time"

	k8sfifo "github.com/kubernetes/client-go/tools/cache"
)

type dummyStruct struct {
	ID    int
	Value int
}

func (d *dummyStruct) FifoObjectKeyFunc() func(interface{}) (string, error) {
	return func(obj interface{}) (string, error) {
		return strconv.Itoa(obj.(*dummyStruct).ID), nil
	}
}

func handleQueueItemMethod(obj interface{}) error {
	time.Sleep(10 * time.Second)
	log.Printf("processed %v", obj)
	return nil
}

func main() {
	f := k8sfifo.NewFIFO((&dummyStruct{}).FifoObjectKeyFunc())
	go func() {
		id := 0
		for {
			if id >= 10 {
				break
			}
			// this line maybe blocked by the `f.Pop(handleQueueItemMethod)`
                         // since f.Pop hold the lock until it returned.
			f.Add(&dummyStruct{
				ID:    id,
				Value: id,
			})
			log.Printf("added %d", id)
			id++
		}
	}()
	for {
		if f.IsClosed() {
			break
		}
		f.Pop(handleQueueItemMethod)
	}
}
``` 

**What you expected to happen**:
fifo queue Pop() method should NOT hold the lock in the whole processing, and should ONLY hold the lock while it need do write operation.

**How to reproduce it (as minimally and precisely as possible)**:
See the previous example. The code location is [this line](https://github.com/kubernetes/kubernetes/blob/89c615f9c448503b674a0d61bfa8e413cefa4104/staging/src/k8s.io/client-go/tools/cache/fifo.go#L280).

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by Colstuwjx** [comment]
I'm not sure the correct sig, maybe this?
/sig api-machinery

**Comment by fedebongio** [comment]
/assign @yliaog 
would you mind taking a look please? thanks!

**Comment by Colstuwjx** [comment]
I found that the DeltaFIFO(which has been used by informer) would also be blocked while [do Pop()](https://github.com/kubernetes/kubernetes/blob/89c615f9c448503b674a0d61bfa8e413cefa4104/staging/src/k8s.io/client-go/tools/cache/delta_fifo.go#L410), and reflector used `Replace()` to [sync queue items](https://github.com/kubernetes/kubernetes/blob/89c615f9c448503b674a0d61bfa8e413cefa4104/staging/src/k8s.io/client-go/tools/cache/reflector.go#L354), it also [acquires the lock](https://github.com/kubernetes/kubernetes/blob/89c615f9c448503b674a0d61bfa8e413cefa4104/staging/src/k8s.io/client-go/tools/cache/delta_fifo.go#L455).

So our controller are all based on this flow? Is it by designed? That is to say, at each time informer try sync watched item changes into DeltaFIFO queue, if the controller is doing Pop() with process function, the sync process would be blocked until the process done? Looks little odd, I'm not sure if I misunderstood this logic.

**Comment by MikeSpreitzer** [comment]
The documentation on Queue::Pop explicitly notes that the lock is held while the popped accumulator is processed.  This is tolerable because informers process the accumulator quickly.  You can see the specification of informer behavior at https://github.com/kubernetes/kubernetes/blob/440b5c2fbc82f4bba3f5d3653ffbd77dec481aa0/staging/src/k8s.io/client-go/tools/cache/shared_informer.go#L34-L183 and the implementation is outlined at https://github.com/kubernetes/kubernetes/blob/440b5c2fbc82f4bba3f5d3653ffbd77dec481aa0/staging/src/k8s.io/client-go/tools/cache/shared_informer.go#L274-L286 , with the `sharedProcessor` further descdribed at https://github.com/kubernetes/kubernetes/blob/440b5c2fbc82f4bba3f5d3653ffbd77dec481aa0/staging/src/k8s.io/client-go/tools/cache/shared_informer.go#L572-L577 .  Sadly, none of those comments explicitly says that the sharedProcessor's listeners do their work asynchronously --- but they do.
