### ISSUE TITLE
How to force restart a POD based on init-container

### ISSUE THREAD

**Issue by gball14** [kubernetes/kubernetes#90011]
I want to restart the pod if the init container can not execute nslookup successfully i.e. there is an issue with dns set up for the pod. I tried the below command for init-container to understand the behaviour. But, kubernetes just restart the container and not the pod.

command: ['sh', '-c', 'echo The app is running! && exit 1;']

**Comment by skilxn-go** [comment]
What do you mean for "restarting a pod".

**Comment by gball14** [comment]
I want kubernetes to restart the pod so that networking/storage initialization happens again (which changes the POD IP). Right now, it just restarts the init-container. I have ocasionally seen cases where the DNS isn't programmed correctly for a POD (windows containers). I got around the issue by deleting the POD and the new one comes up fine. 

I am trying to do the dns check in the init container and from there I want to return appropriate return values which forces the entire pod to be restarted. Is it possible?

**Comment by alexzimmer96** [comment]
Your init containers should run before the other container even starts. So it can't restart your Pods "main"-containers because they will not come up, unless your init container succeeds. Init containers should only be used to prepare something for your real application, like adding certificates, prepare storage in a database and so on.

You could run another container beside your real application and terminate this one when some criteria is meet. This should restart all other containers inside your Pod (except init containers because theese should already have been exited).

**Comment by gball14** [comment]
Thanks @alexzimmer96. I am doing through init containers only. I just want the POD to be recreated (not the container) otherwise the DNS issue that was there with the original POD creation continue to exist no matter how many times the init container restarts.

**Comment by alexzimmer96** [comment]
You could try to use the init-container to send a API-Request to Kubernetes which deletes container when your DNS does not work. Kubernetes has no on-board resources to force a pod-recreation starting from a pod.

But maybe the "right" solution is to resolve your DNS issues. To recreate your Pods whenever you have DNS-issues seems like a odd workaround for a underlying problem.
