### ISSUE TITLE
Brainstorm on scheduler preemption extension point

### ISSUE THREAD

**Issue by Huang-Wei** [kubernetes/kubernetes#90025]
/sig scheduling

## Background

In the [draft proposal of scheduler preemption extension point](https://docs.google.com/document/d/1lBZOA-vjo2m52242q4dZ1L1W-RrNyr14F63PfQ5YUr8/view), we explored possible ways to define the Preemption extension point. Which are listed as below:

- Several Preemption extension points, with each corresponds to each extensible stage of preemption workflow.
- One Preemption extension point, which is consisted of multiple private methods to accomplish the entire preemption workflow.
- One PostFilter extension point. In this case, we don't enforce the semantics of its implementation as preemption. You can implement it as any logic which is invoked right after Filter phase. (We may enforce it to run only upon Filter failures)

To make the preemption logic run as a plugin, i.e., not depending on some internal/non-exposable structs (such as schedulingQueue), the **latter 2 approaches** need a certain number of **code prefactoring**, and some of them are not trivial. So here I want to raise possible refactoring options for brainstorming, hopefully we can get to a consensus and then eventually come out with an optimal Preemption extension point design.

## Overall preemption workflow

In a nutshell, the general preemption flow can be described as 3 phases:

- **A)** [Run a simulation algorithm to come out with a series of PreemptionStrategy](https://github.com/kubernetes/kubernetes/blob/a5d81727151fb7c6ec1baafe7191f634b7eaa1f7/pkg/scheduler/core/generic_scheduler.go#L286). Any strategy can make the Pod schedulable. If no strategy can be found, quit the whole preemption workflow.
- **B)** [Select one of the PreemptionStrategy](https://github.com/kubernetes/kubernetes/blob/a5d81727151fb7c6ec1baafe7191f634b7eaa1f7/pkg/scheduler/core/generic_scheduler.go#L299-L309). The selection process should be reasonable, for instance, preempt low-priority Pods instead of high-priority ones to avoid recursive preemption.
- **C)** [Execute the PreemptionStrategy](https://github.com/kubernetes/kubernetes/blob/e0adb0ead905d448b8850f58a607984783beb467/pkg/scheduler/scheduler.go#L422-L443). This includes deleting the victims, as well as maintaining the internal state in a good shape.

The phase A and C have dependencies on internal schedulingQueue, profile, and other plugins. We will discuss them in the following sections.

## Prefactoring options on A

This is the most challenging part. The "dryrun" simulation process needs to try add/remove Pods on a PreFilter state, so for sure it  relies on PreFilter:

- prof.RunPreFilterExtensionAddPod **<sup>I</sup>**
- prof.RunPreFilterExtensionRemovePod **<sup>II</sup>**

Also, the process runs through FilterPlugins to see upon a mutated PreFilter state, whether the preepmtor Pod can become schedulable: within g.podPassesFiltersOnNode, it calls:

- g.addNominatedPods
    - g.schedulingQueue.NominatedPodsForNode **<sup>III</sup>**
    - prof.RunPreFilterExtensionAddPod **<sup>I</sup>**
- prof.RunFilterPlugins **<sup>IV</sup>**

#### To make I, II, IV runnable in preemption plugin, we may have several options:

1. surface `Profile` to `frameworkHandle`. (this may be impossible)
1. expose function I, II, IV as closures to `frameworkHandle`.
1. pass Filter and PreFilter plugins through `CycleState`, upon the failure of running Filter plugins.
1. associate Filter and PreFilter plugins to `frameworkHandle`. So that `RunFilterPlugins` and PreFilter state mutation can be implemented inside the preemption plugin.
1. move function I, II, IV from `Framework` to `FrameworkHandle` interface. (proposed by @alculquicondor)
1. none of above looks promising.

#### To make III work, we also the following options:

1. expose function `NominatedPodsForNode` as a closure to `frameworkHandle`.
1. make a "NominatedPodsSnapshot" at the beginning of a scheduling cycle, and expose it to `frameworkHandle`. (see #90310)
1. expose function `NominatedPodsForNode` to interface `PodNominator`, and `PodNominator` is exposed as a `preemptHandle` to postFilter/preemption plugins. (see #90415)
1. none of above looks promising.

## Prefactoring options on C

This is the action phase upon selected Node and victim Pods which are going to be deleted. The dependency here prevents from running as part of preemption plugin are:

- sched.SchedulingQueue.UpdateNominatedPodForNode
- sched.SchedulingQueue.DeleteNominatedPodIfExists

Generally we have a number of options to cut the dependency:

1. expose function `UpdateNominatedPodForNode` and `DeleteNominatedPodIfExists` as closures to the New() method upon plugin instantiation.
1. introduce a channel for plugins to send "NominateEvent" (see #89984), and expose that channel to `frameworkHandle`.
1. expose function `UpdateNominatedPodForNode` and `DeleteNominatedPodIfExists` as an interface to PostFilter(). (see #90356)
1. none of above looks promising.

## Feedback

Please don't hesitate to share your thoughts - either your preference (e.g., A6 + A3 + C3) or some other options. :heart:

**Comment by Huang-Wei** [comment]
cc/ @ahg-g @k82cn @alculquicondor @bsalamat @damemi @ravisantoshgudimetla @everpeace @denkensk

**Comment by everpeace** [comment]
Thanks for writing up plans and options!!

My preference is : A4 + A2 + B(original), and additional(`Score` plugins in `frameworkHandle`).

> Prefactoring options on A 

For I, II, IV, I want +1 for `4.`(associate Filter and PreFilter plugins to frameworkHandle so that ).  It is because preemption plugins would be interested in whether selecting victims can make enough room for the preemptor or not.  I think `2.` is too fine-grained, `3.` would not be intuitive.

For III, I want to +1 for `2.` (make a "NominatedPodsSnapshot" at the beginning of a scheduling cycle, and expose it to frameworkHandle).  Probably we could add this method to `SnapshotSharedLister` ??

For the "DryRun" phase or phase B, would some plugin need `PrioritizeNodes`??  I think some plugin would be interested in comparing nodes in the phase.  Thus, how about associating `Score` and `PreScore` plugins to `frameworkHandle` similar to `Filter` for plugin's convenience?

> Prefactoring options on C

`UpdateNominatedPodForNode` and `DeleteNominatedPodIfExists` can change internal state of `schedulingQueue`.  I think exposing these methods or a channel which plugin can change scheduling queue state in frameworkHandle would be dangerous because all the plugins can ALWAYS access to them.

So, How about passing a short-lived channel that can live within a single scheduling cycle for plugins to send "NominateEvent" as an argument in the plugin method in phase C??

**Comment by Huang-Wei** [comment]
Thanks @everpeace .

A4 + A2 is also my preference.

Regarding your proposal on B (expose `Score` plugins), in your practice, to what extent those `Score` plugins can be re-used to help select a PreemptionStrategy? IMO you have to still mutate the state and the (cloned) NodeInfo (to remove victims from it), so I'm not sure about the real value here. @alculquicondor had a discussion in another issue with you, did you get to a conclusion there?

Regarding your new proposal on C, can you clarify the pros of using N "short live" channels? comparing to #89984, which just uses one channel.

**Comment by alculquicondor** [comment]
Since we are not making preemption just yet, I think we should start by moving the entirety of its implementation to be part of the framework runtime.

1. For (A: I, II, IV) I think the cleanest implementation is to expose them as part of the handle (they can simply be unexported functions during the refactoring). I don't see why they have to be closures though. I don't like the idea of a plugin having to call other plugins.
1. For (A: III) my preference is to make them part of the snapshot. Or at least make it easy to calculate from the snapshot.
1. For (C), what about wrapping them in the framework handle as well?

That said, why are nominated pods part of the scheduling queue instead of the cache? We can start changing that.

**Comment by Huang-Wei** [comment]
> For (A: I, II, IV) I think the cleanest implementation is to expose them as part of the handle (they can simply be unexported functions during the refactoring).

Do you mean to directly move those functions one level up from `Framework` interface to `FrameworkHandle` interface?

> That said, why are nominated pods part of the scheduling queue instead of the cache? We can start changing that.

I was also thinking about that. One safe option is to keep the logic as is, say keep another "NominatedPodsSnapshot" from queue; the other option is like you said, figuring out if the `nomiantedPods` struct can be placed into cache, and then we just need one snapshot.

**Comment by alculquicondor** [comment]
> Do you mean to directly move those functions one level up from Framework interface to FrameworkHandle interface?

Right, they are already part of the framework, so it's just about expanding the Framework Handle to include those functions. But what I meant is that this can be done later, once we have finished refactoring the rest and we are ready to build the "preemption" plugin.

**Comment by Huang-Wei** [comment]
SG. Let me add this option to the issue description.

**Comment by everpeace** [comment]
> Regarding your proposal on B (expose Score plugins) in your practice, to what extent those Score plugins can be re-used to help select a PreemptionStrategy?

As I mentioned in another issue, some preemption plugin implementation would prefer to be consistent with scheduling decisions because one of the main purposes of the plugin would make space for preemptor to be scheduled.   In case using multiple score functions to select optimal node selections,  the preemption plugin would want to use those `Score` functions also in victim node selection.  Of course, as alculquicondor pointed out in another issue, I know there is a case that the preemption plugin calls directly their original score functions.  However, how about the case they depended on some score functions from some OSS components?  I can easily imagine a situation that it would be hard for preemption plugins to call the dependent score functions directly.  So, I wanted Score functions to be exposed in FrameworkHandle.  

>  IMO you have to still mutate the state and the (cloned) NodeInfo (to remove victims from it), so I'm not sure about the real value here.

I prefer to provide easier interfaces for plugins to dry-run `Filter/Score` functions so that plugin doesn't need to manipulate cloned NodeInfo actually.

> Regarding your new proposal on C, can you clarify the pros of using N "short live" channels? 

Sorry for my short explanation, my proposal was that:

- pass short-lived channel which can only live in the single scheduling cycle
- scheduling queue focuses to listen to the channel for the current scheduling cycle

I thought this can restrict the ability to nominate/de-nominating pods to preemption plugins only.  Moreover, passing a short-lived channel can force preemption plugins to focus on the current scheduling cycle.  If not, plugins can keep the channel and it can disturb scheduling cycles.

**Comment by alculquicondor** [comment]
> so that plugin doesn't need to manipulate cloned NodeInfo actually

How else would you simulate removing pods?

> I thought this can restrict the ability to nominate/de-nominating pods to preemption plugins only.

That's a good point. But we could also have a "preemption helpers" interface that can be passed as parameter to the preemption extension point. And that could contain all the functions that we only expect preemption plugins to need.

**Comment by everpeace** [comment]
> How else would you simulate removing pods?

Sorry,  I understood it can't.  But, in preemption plugin,  in most cases,  a plugin would manipulate NodeInfo snapshot so many times.  So, we better document explicitly that a plugin needs to __clone__ NodeInfo snapshot first, mutate to it (remove victim candidates or add preemptor) and passed it to `Filter/Score` function when dry-run.

**Comment by Huang-Wei** [comment]
All working items are tracked at #91038.

**Comment by Huang-Wei** [comment]
Forgot to mention the option I'd like to go with. Generally we will introduce a `PreemptHandle` interface which embed all needed operations during preemption logic, specifically a `PreemptHandle` interface will include several sub-interfaces/functions:
  - `PluginRunner` interface. It's for abstracting calling RunXYZPlugins during plugin runtime
  - `PodNominater` interface with internal nominatedMap (which is related with setting/clearing `.spec.NominatedNodeName` as well as managing internal scheduler status
  - `Extender()` function. It's for interacting with registered extenders.

Back to listing options, it's corresponding to:

- A variant of A2. It's just we don't want to surface RunXYZPlugins to `frameworkHandle` which is too wide.
- A3
- C3
