### ISSUE TITLE
MYSQL In Kubernetes

### ISSUE THREAD

**Issue by narasimhamurthyk3** [kubernetes/kubernetes#90092]
Hi Team,

we are trying to setup mysql server with below configurations.

3 mysql pods with sharing same persistence volume and data should be available across all pods and any pods can execute read and write requests and a load balancer to route the traffic to different pods based on load.
Hope service will take care to route the traffic.
I tried master and salve method here master is only suitable for write and slave for read.
Can anyone explain which method is suitable to suite my requirements.

/sig Scalability

**Comment by mrbobbytables** [comment]
Please re-post your question to the [Kubernetes User Forum](https://discuss.kubernetes.io) or [Stack Overflow](http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases.

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

Members of the Kubernetes community use the Forum or Stack Overflow to field support requests. Before posting a new question, please search there for answers to similar questions, and also familiarize yourself with:

  * [user documentation](https://kubernetes.io/docs/home/)
  * [troubleshooting guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/)

Again, thanks for using Kubernetes.

The Kubernetes Team


---
/triage support
/close
