### ISSUE TITLE
high availability of KMS plugin

### ISSUE THREAD

**Issue by gaorong** [kubernetes/kubernetes#90159]
**What would you like to be added**:
a mechanism to provide high availability of KMS plugin.

**Why is this needed**:
Nowadays, apiserver communicate with KMS-plugin via a domain socket,  however, if the KMS-plugin has crashed accidentally, apiserver located at the same host can not failover automatically. The request of secret fall into this server will fail, although other KMS-plugins work correctly.

As we want to use this in our production environment which serves many customers, this seems to be a potential failure point.

From [original dsicusstion]( https://github.com/kubernetes/kubernetes/pull/55684#issuecomment-351912974), the implementation of KMS plugin been called by local unix domain socket seems to be a short-term solution? 

@liggitt @wu-qiang @destijl @sakshamsharma  PTAL

**Comment by gaorong** [comment]
@kubernetes/sig-auth-feature-requests  PTAL

**Comment by gaorong** [comment]
@immutableT @mikedanese  could you help take a look?

**Comment by immutableT** [comment]
Would not a liveness probe help in the scenario you desribed?

I think that #87438 could also help by reducing the reliance of kube-apiserver on kms-plugin/kms.

**Comment by gaorong** [comment]
We deploy apiserver in the bare-metal hosts behind an L4 load balancer, and the L4 load balancer does not understand the L7 liveness probe meaning.

**Comment by immutableT** [comment]
Sorry, I was not clear. 
I was suggesting to use a liveness probe in the kms-plugin pod. The idea is to use such a probe to restart kms-plugin is it fails to perform encrypt/decrypt operations (example [here](https://github.com/GoogleCloudPlatform/k8s-cloudkms-plugin/blob/master/plugin/healthz.go#L127)).

Based on my memory, the main reason for the decision of using Unix Domain Socket was to avoid the need of dealing with the security implications of passing secrets from kube-apiserver to the remote kms-plugin. To do this securely, we would need to pass yet another TLS bundle to the kube-apiserver. Unix Domain Sockets avoid the need for TLS since we can rely on Linux file access control list to bootstrap the trust between the kube-apiserver and the kms-plugin.

**Comment by gaorong** [comment]
> I was suggesting to use a liveness probe in the kms-plugin pod. The idea is to use such a probe to restart kms-plugin is it fails to perform encrypt/decrypt operations (example [here](https://github.com/GoogleCloudPlatform/k8s-cloudkms-plugin/blob/master/plugin/healthz.go#L127)).

Thanks, this is also the only way we can come up with, for now.
On the other hand, we allocate a big DEK cache for apiserver, which could serve the majority secret read request and no need to invoke kms-plugin. In this way, the majority read request can succeed even thought the kms-plugin crashed. 

All this solution can mitigate the pain, but can not resolve this issue from the root. IMO, we would prefer setting up a TLS bundle than making user requests fail.
