### ISSUE TITLE
Add custom resource list func to SharedInformerOption

### ISSUE THREAD

**Issue by yuyulei** [kubernetes/kubernetes#90262]
**What would you like to be added**:
I want to add custom resource list function as options to SharedInformer, just like [WithCustomResync](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/informers/factory.go#L71)

for example: 
```
func WithCustomResourceListFunc(funcs map[v1.Object]ResouceListFunc) SharedInformerOption {
	return func(factory *sharedInformerFactory) *sharedInformerFactory {
		factory.customResourceListFuncs = customResourceListFuncs
		return factory
	}
}
```

the feature is similar to [WithTweakListOptions](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/informers/factory.go#L81), WithTweakListOptions will take effect to all resources, But I want some resources use my custom list function to list, not for all.

Although, I have got an approach like [provisioner's jobController](https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/blob/master/pkg/deleter/jobcontroller.go#L76), but feel a little complicated.

```
        queue := workqueue.NewRateLimitingQueue(workqueue.DefaultControllerRateLimiter())
	labelset := labels.Set(labelmap)
	optionsModifier := func(options *meta_v1.ListOptions) {
		options.LabelSelector = labels.SelectorFromSet(labelset).String()
	}

	informer := config.InformerFactory.InformerFor(&batch_v1.Job{}, func(client kubernetes.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
		return cache.NewSharedIndexInformer(
			cache.NewFilteredListWatchFromClient(client.BatchV1().RESTClient(), "jobs", namespace, optionsModifier),
			&batch_v1.Job{},
			resyncPeriod,
			cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc},
		)
	})
```

**Why is this needed**:

There are two scenarios. 

1. My crd controller only wants to list pods created by itself, not other pods, like daemonset pods. But my crd controller also want other resources, like configmap, secrets or other crds. My pods share the same label, but the configmap, secrets  and other crds don't. So I can't use  WithTweakListOptions to SharedInformer. If I use the special label is WithTweakListOptions, the SharedInformer can't get  configmap or other crds.

2. I have daemonset pods [provisioner](https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner), which manage the pv(local) of the node. Actually, the provisioner pod only care the pod with label: "kubernetes.io/hostname": "the-node-name-which-the-pv-bind-to". For create pv, we should set storage class, but storageclass don't share the label of "kubernetes.io/hostname". So I can't use WithTweakListOptions and SharedInformer to list pvs of some node. I really don't want to list all pv in the cluster, and these list will affect the stability of apiserver.

**Comment by yuyulei** [comment]
@liggitt ptal

**Comment by liggitt** [comment]
what would the InformerFor method do if a custom list function was already present for a given object type? ignoring the `newFunc internalinterfaces.NewInformerFunc` parameter doesn't seem like a good interaction

**Comment by yuyulei** [comment]
@liggitt right, it will be conflict and confused if WithCustomResourceListFunc[above] and [InformerFor](https://github.com/kubernetes/client-go/blob/master/informers/factory.go#L165) both can define the  list function. 

How about `CustomerListOptions`, like:

```
func WithCustomerListOptions(customerListOptions map[Oject]internalinterfaces.TweakListOptionsFunc) SharedInformerOption {
	return func(factory *sharedInformerFactory) *sharedInformerFactory {
		factory.customerListOptions = costemerListOptions
		return factory
	}
}
```
when generating cache ListFunc, like [NewFilteredStorageClassInformer](https://github.com/kubernetes/client-go/blob/4b7e8bfcc1459c84bad517d607c89b0f41d0a96d/informers/storage/v1/storageclass.go#L60), we first use tweakListOptions  to decorate listOptions, then if resourceType exists in costemerListOptions, we can go on to use costemerListOptions later.

**Comment by yuyulei** [comment]
@liggitt ptal

**Comment by fatedier** [comment]
@liggitt Hi, any update on this issue? We need this feature too.

**Comment by kow3ns** [comment]
@MikeSpreitzer

**Comment by MikeSpreitzer** [comment]
@yuyulei: you noted two scenarios, so there are really two issues here.  Let me address them one at a time.

Scenario 1, tweak informer for your controller's pods but not other resources.  First, note that the existing facility is tweaking informer *factories*, not informers.  Just use two informer factories.  It looks like you have a very static scenario, this should be pretty straightforward.  Create and use a tweaked informer factory for your controller's pods, use an untweaked factory for the other resources.

Scenario 2, making the local-volume-provisioner list only the PVs for its node (I am not entirely sure I understand correctly, is this really the issue you are trying to raise here?).  Since your provisioner is creating the PVs, it can include a label that identifies the node and you can tweak an informer factory to inspect that label.

Also note, and this may be relevant to some comments above about introducing layering (which you won't need once you fix the bug), there is a bug in the code you exhibited
```
	optionsModifier := func(options *meta_v1.ListOptions) {
		options.LabelSelector = labels.SelectorFromSet(labelset).String()
	}
```
This code _overwrites_ the `options.LabelSelector`.  What it _should_ do is _combine_ (by `and`, which is easy to do syntactically) the incoming label selector, if any, with the one from `labels`.
