### ISSUE TITLE
Use allowlist and denylist in public documentation

### ISSUE THREAD

**Issue by Capstan** [kubernetes/kubernetes#90277]
**What would you like to be added**:
The documentation around the APIs, e.g., as seen in field comments in https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/api/policy/v1beta1/generated.proto, uses "white list" and "whitelist", and I suggest changing this to use allowlist instead.

For future internal code and type names, I suggest avoiding terms like "whilelist" and "blacklist" entirely.

**Why is this needed**:
https://developers.google.com/style/inclusive-documentation#features-and-users describes this pretty well. Associating "white" with good/allowed and "black" with bad/disallowed cannot be disentangled from systemic racism. In contrast, allowlist and denylist exactly and merely describe the functions of these fields and variables.

https://github.com/kubernetes/kubernetes/search?p=2&q=%22whitelist%22+OR+%22white+list%22+OR+%22blacklist%22+OR+%22black+list%22&unscoped_q=%22whitelist%22+OR+%22white+list%22+OR+%22blacklist%22+OR+%22black+list%22

**Comment by celestehorgan** [comment]
I stumbled upon this issue WRT Docs PR https://github.com/kubernetes/website/pull/21591 – 

Is there any plan to follow through on this in the existing codebase? I understand that this is the plan going forward, but I'd like to see a retroactive name change of classes, files, and methods in the current codebase for the following reasons:

- As a developer naming a new feature which may involve an allowlist or denylist, I won't look through existing `kubernetes/kubernetes` issues to find this one. Instead, I'll look at _similar classes and functionality within the codebase_ and follow suit.
- As a PR reviewer, I won't look through existing issues either, especially given that I know whitelist/blacklist are currently in use in the codebase. If I see something different (say allowlist/denylist), I'll suggest the developer follow the codebase convention. 
- As an end user developer reading through the documentation, I might want to double-check the underlying implementation of an allowlist or denylist processor. Given that the documentation uses the terminology allowlist and denylist (or simply allow and deny), as an end user developer my expectation is that the underlying codebase does the same. My first instinct is to search the codebase for "allowlist" and "denylist" rather than white/blacklist.


Finally, a personal objection as a technical writer: 

Documentation is often used to make token gestures at product improvement. If an underlying implementation is overengineered, we use documentation to make it seem simpler than it is. We're asked not to document certain fields or features to make an API seem less leaky than it is. When technical writers advocate for codebase change – even those as simple as renaming a feature – we're brushed off or added to endless backlogs.

I realize that asking for change in the codebase raises a number of complex issues: tests need to be rewritten, upgrade paths become an issue, unexpected complications arise. But I don't think that a shift to wards inclusive, non-violent language should be something done in a token way.

**Comment by liggitt** [comment]
The API guidelines aspect seems to fall within sig-architecture's charter ("establishing and documenting conventions for system and user-facing APIs"), so I've added the topic to the agenda for the [next sig-architecture meeting](https://github.com/kubernetes/community/tree/master/sig-architecture#meetings) on 6/18 and started a [mailing list thread](https://groups.google.com/forum/#!topic/kubernetes-sig-architecture/6XUqV1lXb68) per the sig-architecture meeting guidelines.

**Comment by pururaj1908** [comment]
Hi @Capstan I can do this as my first contribution? I could even help changing the terms in codebase if you want.

**Comment by Capstan** [comment]
@pururaj1908 As I'm not a committer or maintainer of k8s, I'd suggest seeing what the outcome of the 6/18 sig-architecture meeting is. My suspicion is that there will be guidance on how to proceed, e.g., what design docs might be necessary for code that would need migration due to release skew between client and server. In the meanwhile, if you've not already, I'd read through https://kubernetes.io/docs/contribute/. In any case, I am not the arbiter of assignments; it seems fairly reasonable that this could be your contribution.

**Comment by pururaj1908** [comment]
@Capstan  Thank you so much for the information. I have read some of the sections provided in the contribution guidelines. I will the look more in style guide section.

**Comment by celestehorgan** [comment]
Hi all, 

There's a PR open for a recommendation on this here: https://github.com/kubernetes/community/pull/5341.

@Capstan – WG Naming has already more or less reached consensus on this, so I think you're good to start a PR and we can merge it once the recommendation merges.

**Comment by Capstan** [comment]
Thanks, @celestehorgan. To set expectations, I am not a maintainer, and I have Q4 commitments to tend to, but would be happy to start submitting PR(s) in late December.

**Comment by spiffxp** [comment]
/sig api-machinery
since this references generated api docs

I'm not sure exactly what the scope of work is here and so am reticent to tag it with /help

**Comment by celestehorgan** [comment]
/unassign

We've done our end of things from WG naming and produced a recommendation. This is ready for action imho.

**Comment by lavalamp** [comment]
Are there still things to be done? The search in the OP doesn't find anything anymore.

**Comment by spiffxp** [comment]
https://cs.k8s.io/?q=blacklist&i=fosho&files=&excludeFiles=vendor&repos=kubernetes/kubernetes

There is a bit more

**Comment by justaugustus** [comment]
/help
This doesn't currently have an assignee. Is someone interested in helping drive this to completion?

**Comment by mgutierrez98** [comment]
@justaugustus I can send a PR to refactor all of this right now.

**Comment by sftim** [comment]
Should we replace `scheduler.alpha.kubernetes.io/tolerationsWhitelist` with a new annotation? I think we should.

**Comment by fedebongio** [comment]
@sftim would you send a PR for that? Thanks

**Comment by lavalamp** [comment]
I would talk to sig scheduling about that. I'm not sure why api machinery is on this bug now? We don't own very many apis and people don't ask us before naming things, they'd ask an api reviewer if anyone.

/sig scheduling
/sig arch
/remove-sig api-machinery

**Comment by sftim** [comment]
@fedebongio I couldn't send a PR for the replacement (no spare cycles to learn Go). However I could file an issue?
