### ISSUE TITLE
regression: wait.Forever runs twice immediately since 1.18

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#90287]
I noticed that this code:

```
	go wait.UntilWithContext(ctx, func(ctx context.Context) {
		now := time.Now()
		refreshAfter := now.Add(-s.refreshInterval)
		var count int
		for _, obj := range s.store.List() {
			comments := obj.(*BugComments)
			if comments.RefreshTime.Before(refreshAfter) {
				s.queue.Add(comments.Name)
				count++
			}
		}
		klog.V(5).Infof("Refreshed %d comments older than %s", count, s.refreshInterval.String())
	}, s.refreshInterval/4)
```

was printing 

```
I0419 16:20:13.714551  976723 comments.go:122] Refreshed 0 comments older than 15m0s
I0419 16:20:13.714603  976723 comments.go:122] Refreshed 0 comments older than 15m0s
```

which should not happen.  Also occurs in wait.Forever.

I suspect that fc8a39d439ea08b006fb7ea1db1058175cc7adf5 in https://github.com/kubernetes/kubernetes/pull/87829 regressed this as that was the most recent major update and I only started seeing this on a recent apimachinery bump.

**Comment by smarterclayton** [comment]
/sig api-machinery
/assign @zhan849 
@lavalamp as the reviewer

**Comment by smarterclayton** [comment]
This is a correctness regression because the wait methods expect not to be run run more often than the period and may guard expensive behavior.  Suggest a revert followed by a more rigorous test and review on merge.

**Comment by zhan849** [comment]
@smarterclayton thanks for reporting this, and I apologize about the regression I made.

I did some quick test, and I am able to reproduce it occasionally, which indicate a race somewhere:

Test: 
```go
func TestJitter(t *testing.T) {
	c := clock.RealClock{}
	ctx, cancel := context.WithCancel(context.TODO())
	start := time.Now()
	go func() {
		UntilWithContext(ctx, func(ctx context.Context) {
			fmt.Printf("Elapsed: %d\n", c.Now().Sub(start).Nanoseconds())
		}, 100 * time.Millisecond)
	}()

	time.Sleep(1 * time.Second)
	cancel()
}
```
Failed output:
```bash
=== RUN   TestJitter
Elapsed: 24744
Elapsed: 71183
Elapsed: 101122103
Elapsed: 203562033
Elapsed: 307499333
Elapsed: 412627825
Elapsed: 512933335
Elapsed: 614431660
Elapsed: 715580695
Elapsed: 820638894
Elapsed: 921562014
--- PASS: TestJitter (1.00s)
PASS
```

Successful output?
```bash
=== RUN   TestJitter
Elapsed: 272958
Elapsed: 104091427
Elapsed: 208611861
Elapsed: 313716044
Elapsed: 418798621
Elapsed: 520015802
Elapsed: 620768041
Elapsed: 725830330
Elapsed: 829402929
Elapsed: 931978271
--- PASS: TestJitter (1.00s)
PASS
```

In the original code I checked in, I initialized the timer in the backoff manager construction time:
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/util/wait/wait.go#L352

However, after I changed to initializing the timer when `Backoff()` is called, I'm not able to reproduce the race.
```go
// NewJitteredBackoffManager returns a BackoffManager that backoffs with given duration plus given jitter. If the jitter
// is negative, backoff will not be jittered.
func NewJitteredBackoffManager(duration time.Duration, jitter float64, c clock.Clock) BackoffManager {
	return &jitteredBackoffManagerImpl{
		clock:        c,
		duration:     duration,
		jitter:       jitter,
		backoffTimer: nil,
	}
}

func (j *jitteredBackoffManagerImpl) getNextBackoff() time.Duration {
	jitteredPeriod := j.duration
	if j.jitter > 0.0 {
		jitteredPeriod = Jitter(j.duration, j.jitter)
	}
	return jitteredPeriod
}

func (j *jitteredBackoffManagerImpl) Backoff() clock.Timer {
	backoff := j.getNextBackoff()
	if j.backoffTimer == nil {
		j.backoffTimer = j.clock.NewTimer(backoff)
	} else {
		j.backoffTimer.Reset(backoff)
	}
	return j.backoffTimer
}
```

The results indicated that the timer initialization is likely to be the place that caused the regression , and seems to be able to get fixed by change the way the timer gets initialized. However I'm unable to identify why it could cause such race the first time. Are you able to provide any insights?

/cc @lavalamp @liggitt

**Comment by liggitt** [comment]
why are we initializing a timer with a zero duration? that looks related to this issue: https://github.com/golang/go/issues/10124#issuecomment-78006112

**Comment by liggitt** [comment]
I see us resetting a timer we have no guarantee is stopped/expired:

https://golang.org/pkg/time/#Timer.Reset

**Comment by liggitt** [comment]
https://github.com/kubernetes/kubernetes/commit/fc8a39d439ea08b006fb7ea1db1058175cc7adf5#diff-9be0989ea698ae219c147e34604ba215L168 dropped the `sawTimeout` information needed to accurately stop/reset the timer as documented

**Comment by zhan849** [comment]
Hi @liggitt thanks for providing the information!

seems like the correct place to initialize the timer is in the "Backoff" method, since zero duration is problematic.

> I see us resetting a timer we have no guarantee is stopped/expired:
When I was putting up the interface, I documented that the timer will not be drained, and the reason is that `Backoff()` returns a timer explicitly for user to block on that, so it might be confusing to block in `Backoff()` itself
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/util/wait/wait.go#L290

Shall we change the impl to always drain the channel in backoff?

btw according to https://golang.org/src/time/sleep.go?s=2391:2418#L101 it seems checking `Stop()` before reset is sufficient, and we don't need `sawTimeout`?

**Comment by wojtek-t** [comment]
@liggitt @smarterclayton  - sorry for that - we hit the bug with resetting timer not the first time, I should have caught that (I remember at least two other bugs with that).

> Suggest a revert followed by a more rigorous test and review on merge.

@smarterclayton I'm not sure revert is a good option, because there were PRs that were chained on that: #87795 - this would have to be a very careful manual revert which I'm not sure it justifies the risk, given that 1.18 is already out.

> I documented that the timer will not be drained

Currently the behavior is unpredictable, because if getNextbackoof() called for the first time is non-zero, it may or may not be ready immediately depending on the race. That is obviously bad.

Initializing with infinity may solve this particular problem, but I need to think more about it to ensure that we don't have any problems in the later phase too...

**Comment by zhan849** [comment]
thanks @wojtek-t ! and sry again I did not read the timer's doc carefully enough but simply followed the Clock interface :(

To fix, we can also initialize the timer to nil and create a fresh one when `Backoff()` is first called. 

But to ensure timer is drained before reset, we need to have user explicitly pass in "if timer is drained" into the `Backoff()` to accurately decide if `Backoff()` needs to drain. Or, is it ok to document the behavior and assume user will drain on `Backoff().C()` before calling next `Backoff()`

**Comment by wojtek-t** [comment]
> But to ensure timer is drained before reset, we need to have user explicitly pass in "if timer is drained" into the Backoff() to accurately decide if Backoff() needs to drain.

Very quick (I might have missed something) glance from the code suggests, that the only place we would need to change is actually BackoffUntil method. So passing the "if timer is drained" bit seems less error prone imho.

**Comment by liggitt** [comment]
> passing the "if timer is drained" bit seems less error prone imho.

We should avoid changing the interface in a patch release.

**Comment by liggitt** [comment]
I think initializing the timer in Backoff() and documenting the returned timer must be expired and drained before calling Backoff() again is the most compatible thing we can do:

```diff
diff --git a/staging/src/k8s.io/apimachinery/pkg/util/wait/wait.go b/staging/src/k8s.io/apimachinery/pkg/util/wait/wait.go
index 4cb0c122c0c..a73d073b4b0 100644
--- a/staging/src/k8s.io/apimachinery/pkg/util/wait/wait.go
+++ b/staging/src/k8s.io/apimachinery/pkg/util/wait/wait.go
@@ -317,7 +317,7 @@ func NewExponentialBackoffManager(initBackoff, maxBackoff, resetDuration time.Du
 			Steps: math.MaxInt32,
 			Cap:   maxBackoff,
 		},
-		backoffTimer:         c.NewTimer(0),
+		backoffTimer:         nil,
 		initialBackoff:       initBackoff,
 		lastBackoffStart:     c.Now(),
 		backoffResetDuration: resetDuration,
@@ -336,7 +336,11 @@ func (b *exponentialBackoffManagerImpl) getNextBackoff() time.Duration {
 
 // Backoff implements BackoffManager.Backoff, it returns a timer so caller can block on the timer for backoff.
 func (b *exponentialBackoffManagerImpl) Backoff() clock.Timer {
-	b.backoffTimer.Reset(b.getNextBackoff())
+	if b.backoffTimer==nil {
+		b.backoffTimer = b.clock.NewTimer(b.getNextBackoff())
+	} else{
+		b.backoffTimer.Reset(b.getNextBackoff())
+	}
 	return b.backoffTimer
 }
 
@@ -354,7 +358,6 @@ func NewJitteredBackoffManager(duration time.Duration, jitter float64, c clock.C
 		clock:        c,
 		duration:     duration,
 		jitter:       jitter,
-		backoffTimer: c.NewTimer(0),
 	}
 }
 
@@ -367,7 +370,11 @@ func (j *jitteredBackoffManagerImpl) getNextBackoff() time.Duration {
 }
 
 func (j *jitteredBackoffManagerImpl) Backoff() clock.Timer {
-	j.backoffTimer.Reset(j.getNextBackoff())
+	if j.backoffTimer == nil {
+		j.backoffTimer = j.clock.NewTimer(j.getNextBackoff())
+	}else{
+		j.backoffTimer.Reset(j.getNextBackoff())
+	}
 	return j.backoffTimer
 }
 ```

**Comment by zhan849** [comment]
Thanks @liggitt and @wojtek-t 
I'm also more inclined to Jordan's proposal, besides avoid interface change, if user are able to accurately pass "if timer is drained" info, it's fair to let user finish draining.

@liggitt do you have a PR already? of if not, I can make one, and add more tests if possible about this failure case.

**Comment by liggitt** [comment]
I do not have a PR open
