### ISSUE TITLE
Expose eviction-related metrics in kubelet

### ISSUE THREAD

**Issue by SeMeKh** [kubernetes/kubernetes#90464]
**What would you like to be added**:
Expose the threshold of each eviction signal, and optionally their current value.

**Why is this needed**:
Since an eviction might cause disruption to the overall quality of service, we'd like to be able to prevent it from happening. Right now, we can collect most of the required metrics from the node exporter, except for the threshold after which an eviction is triggered.

**Comment by SeMeKh** [comment]
I'd like to give this one a try. Can someone please point me in the right direction?

**Comment by dashpole** [comment]
It probably belongs on the kubelet's `/metrics` endpoint (https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/metrics/metrics.go).  You would just need to plumb the eviction configuration.  You would probably want to do something like we do for NodeName, which is to "observe" the node name once during startup so that the metric is exposed thereafter: https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/metrics/metrics.go#L518
