### ISSUE TITLE
Support reflector with tuned backoff manager for informer factory

### ISSUE THREAD

**Issue by huangjiuyuan** [kubernetes/kubernetes#90514]
**What would you like to be added**:
Support reflector with tuned backoff manager for informer factory.

**Why is this needed**:
We have clusters with more than 60k pods, configmaps, and crds in production. Several operators are watching api resources, which list all resources of one kind on start. We have encounterd apiserver oom for a couple of times and our control plane recovers slowly with the [default backoff manager](https://github.com/kubernetes/kubernetes/blob/release-1.18/staging/src/k8s.io/client-go/tools/cache/reflector.go#L138).

Once apiserver is overloading and gets oom, it would be the best for us to have mechanism to tune the reflectors of all operators with regards to the amount of objects they are watching. With the feature to tune the backoff manager, we could recover high priority or light-weighted operators as soon as possible and delay the recovers of heavy-weight operators.

**Comment by fedebongio** [comment]
/cc @lavalamp @MikeSpreitzer 
Seems to be related to the Fairness and Priority feature

**Comment by lavalamp** [comment]
I do think there's room to apply APF ideas to the workqueue, so that controllers don't spend all their time on a big namespace and starve out a little namespace.

Note that some work on this already happened for "endpoint slice", but IIRC there we decided a fixed delay was sufficient for the moment. https://github.com/kubernetes/kubernetes/issues/88967
