### ISSUE TITLE
TestNominatedNodeCleanUp flakes

### ISSUE THREAD

**Issue by Huang-Wei** [kubernetes/kubernetes#90627]
**Which jobs are flaking**:

k8s.io/kubernetes/test/integration/scheduler.TestNominatedNodeCleanUp

**Which test(s) are flaking**:

- https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-integration/1255184557414551553
- https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-integration/1255652298948874240

**Testgrid link**:

https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-integration

**Reason for failure**:

Unknown yet.

**Anything else we need to know**:
- links to go.k8s.io/triage appreciated
- links to specific failures in spyglass appreciated

/sig scheduling
/help

**Comment by ahmad-diaa** [comment]
@Huang-Wei Can I give it a try?

**Comment by Huang-Wei** [comment]
@ahmad-diaa Sure, feel free to take it.

/assign ahmad-diaa
/remove-help

**Comment by ahmad-diaa** [comment]
I keep trying to get it fail locally by running the following command:

```shell
make test-integration WHAT=./test/integration/scheduler GOFLAGS="-v" KUBE_TEST_ARGS="-run ^TestNominatedNodeCleanUp$"
```

but it never does, am I doing something wrong? Is there something else that I should be doing and would be more helpful?

**Comment by Huang-Wei** [comment]
@ahmad-diaa Sometimes the flake is hard to reproduce in local env. You may have to read the error log of the flakes thoroughly to get some clues.

BTW: you can also run the test multiple times using the `-count` directive:

```
make test-integration WHAT=./test/integration/scheduler GOFLAGS="-v" KUBE_TEST_ARGS="-count=10 -run ^TestNominatedNodeCleanUp$"
```

**Comment by ahmad-diaa** [comment]
@Huang-Wei 

After looking through the logs I came up with some information that might be useful
- As far as I understand, the reason for the flake is the `nominatedNodeName` of the medium priority pod not being cleared
- That is because the update request for removing `nominatedNodeName` returns the following error: `Operation cannot be fulfilled on pods "medium-priority": the object has been modified; please apply your changes to the latest version and try again`

So my current guess is that `nominatedPodsToClear` might be outdated in some cases
https://github.com/kubernetes/kubernetes/blob/3c159bb10fa1a86af2d5c49703ce96c04eabe7b2/pkg/scheduler/scheduler.go#L408

As I am not really familiar with the logic, I would like to know whether or not those are valid points so that I could dig deeper. What do you think?

**Comment by Huang-Wei** [comment]
> That is because the update request for removing nominatedNodeName returns the following error:

If that's the case, you can set `podCopy.ResourceVersion = "0"` here:

https://github.com/kubernetes/kubernetes/blob/7937aa60a3dcc2d447e06847ae68fe1d9319630c/pkg/scheduler/scheduler.go#L802

You can raise a PR and manually try `/test pull-kubernetes-integration` for ~20 times to see you can reproduce the flake.

**Comment by cofyc** [comment]
duplicated https://github.com/kubernetes/kubernetes/issues/89259

**Comment by brianpursley** [comment]
Sorry, didn't mean to take this one for you. I worked the duplicate issue and submitted a PR. Feel free to review that PR, or submit your own if you have a different solution.

**Comment by Huang-Wei** [comment]
This sometimes happens. But we usually take the first PR unless it's clearly worked by someone.

In terms of which style to resolve the Conflict error, I'm asking here: https://kubernetes.slack.com/archives/C0EG7JC6T/p1589216075286800.

**Comment by ahmad-diaa** [comment]
>Sorry, didn't mean to take this one for you. I worked the duplicate issue and submitted a PR. Feel free to review that PR, or submit your own if you have a different solution.

No worries, I haven't started implementing yet and your PR seems to be  following the correct approach as well according to this:
https://kubernetes.slack.com/archives/C0EG7JC6T/p1589216911287100
