### ISSUE TITLE
[Flaky Test] kubeadm-kinder-upgrade-1-18-1-19 (ci-kubernetes-e2e-kubeadm-kinder-upgrade-1-18-1-19)

### ISSUE THREAD

**Issue by hkamel** [kubernetes/kubernetes#90761]
**Which jobs are failing**:
> kubeadm-kinder-upgrade-1-18-master (ci-kubernetes-e2e-kubeadm-kinder-upgrade-1-18-master)

**Which test(s) are failing**:
> Overall
> task-06-upgrade

**Since when has it been failing**:
> 05-04 11:52 PDT

**Testgrid link**:
> https://testgrid.k8s.io/sig-release-master-informing#kubeadm-kinder-upgrade-1-18-master

**Reason for failure**:

> # task-12-delete
> kinder delete cluster --name=kinder-upgrade --loglevel=debug
> 
> time="09:17:53" level=debug msg="Running: /usr/bin/docker [docker ps -q -a --no-trunc --filter label=io.k8s.sigs.kind.cluster --format {{.Names}}\\t{{.Label \"io.k8s.sigs.kind.cluster\"}}]"
> Deleting cluster "kinder-upgrade" ...
> time="09:17:53" level=debug msg="Running: /usr/bin/docker [docker ps -q -a --no-trunc --filter label=io.k8s.sigs.kind.cluster --format {{.Names}}\\t{{.Label \"io.k8s.sigs.kind.cluster\"}} --filter label=io.k8s.sigs.kind.cluster=kinder-upgrade]"
> time="09:17:53" level=debug msg="Running: /usr/bin/docker [docker rm -f -v kinder-upgrade-lb kinder-upgrade-control-plane-3 kinder-upgrade-control-plane-2 kinder-upgrade-worker-2 kinder-upgrade-worker-1 kinder-upgrade-control-plane-1]"
>  completed!
> 
> Ran 10 of 13 tasks in 0.000 seconds
> FAIL! -- 9 tasks Passed | 1 Failed | 3 Skipped
> 
> see junit-runner.xml and task logs files for more details
> 
> Error: failed executing the workflow
> + EXIT_VALUE=1
> + set +o xtrace

**Anything else we need to know**:

/cc @kubernetes/ci-signal
/milestone v1.19
/priority critical-urgent
/sig testing

**Comment by neolit123** [comment]
i went trough all the flakes we have at the moment and adjusted a number timeouts. here is the PR:
https://github.com/kubernetes/kubeadm/pull/2131

**Comment by hasheddan** [comment]
@neolit123 was green for a bit since merge, but noticed a timeout on `init` this morning. Do you think it is worth bumping the timeout there as well? It looks like the timeout was quite a large outlier compared to the successful runs (more than double the duration), so maybe we should address underlying problem. 

https://testgrid.k8s.io/sig-release-master-informing#kubeadm-kinder-master-on-1-18&show-stale-tests=&graph-metrics=test-duration-minutes

https://github.com/kubernetes/kubeadm/blob/e99c06166a5b9ffa228b45cf4dfd86236009d25c/kinder/ci/workflows/discovery-tasks.yaml#L58

**Comment by neolit123** [comment]
lets wait for some more singla before bumping the timeouts on init.
locally for me `init` takes a couple of minutes, so i would like to know if this is a temporary GCE/networking issue.

**Comment by neolit123** [comment]
actually something is not right, because in this job:

also this job https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-kinder-master/1257831781441212418/build-log.txt showed that even 10m is not enough for 
`kubeadm join`

it errored with:
> timeout. task did not completed in less than 10m0s as expected

but looking at the log timestamps only ~2 minutes have passed.
i will have another look later today or tomorrow.

**Comment by neolit123** [comment]
/retitle [Flaky Test] kubeadm-kinder-upgrade-1-18-master (ci-kubernetes-e2e-kubeadm-kinder-upgrade-1-18-master)

/priority important-soon
/remove-kind failing-test
/kind flake

the test seems to be timeouting occasionally now.

> i will have another look later today or tomorrow.

this appeared to be a temporary network speed issue.

in the meantime i have created this PR which attempts to catch network flakes early and reduce overall network traffic:
https://github.com/kubernetes/kubeadm/pull/2133

**Comment by neolit123** [comment]
the kubeadm e2e jobs started requiring more than 40 minutes:
https://k8s-testgrid.appspot.com/sig-cluster-lifecycle-kubeadm#kubeadm-kinder-upgrade-1-18-master
https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-kinder-upgrade-1-18-master/1261188643725250562/build-log.txt

so a lot of tests are now failing. this could be due to:
- resource limits in Prow
- more conformance tests were added

during the weekend or next week i will try bumping all jobs to ~60 minutes.

**Comment by neolit123** [comment]
/remove-priority important-soon
(prio is already critical)

**Comment by neolit123** [comment]
xref https://github.com/kubernetes/kubernetes/issues/91128

**Comment by neolit123** [comment]
@hkamel @hasheddan hi, the jobs seem to be now at the state where they were before the ticket was logged - i.e. mostly green.

> during the weekend or next week i will try bumping all jobs to ~60 minutes.

the Prow issue that was discussed in https://github.com/kubernetes/kubernetes/issues/91128 is definitely a factor, so i'm not going to bump the jobs to 60minutes for now.

we do still see 2 occasional types of flakes:
- one of them is known https://github.com/kubernetes/kubeadm/issues/1918 and we don't have a fix for it as it's complicated.
- for the other one i'm going to send a PR and ping you for a quick lgtm.

thanks.

**Comment by hasheddan** [comment]
@neolit123 thanks for following up! I will make sure to take a look at your incoming PR :+1:

**Comment by neolit123** [comment]
i haven't seen the same failure in the last 10 runs:
https://k8s-testgrid.appspot.com/sig-cluster-lifecycle-kubeadm#kubeadm-kinder-upgrade-1-18-master

please re-open this ticket if needed.
thanks.

**Comment by hasheddan** [comment]
@neolit123 I am seeing some pretty regular failures here again. Could you take a look?

/reopen

**Comment by neolit123** [comment]
the job is taking more than 40 minutes.

so this is related to:
https://github.com/kubernetes/kubernetes/issues/90761#issuecomment-630287727

**Comment by sayanchowdhury** [comment]
The runs in last few days have been well under 60m, except for [one](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-kinder-upgrade-1-18-master/1272514756925722626)

**Comment by neolit123** [comment]
i'm suspecting slow CPU/network for some of the recent failures.

**Comment by BenTheElder** [comment]
/remove-sig testing
SIG testing does not own kinder.

**Comment by neolit123** [comment]
looks like the most prominent recent flakes are caused by the inability to prepare the node image or upgrade all nodes in less than 10 minutes.

https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-kinder-upgrade-1-18-master/1275041617769664515/artifacts/task-01-add-kubernetes-versions-log.txt

https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-kinder-upgrade-1-18-master/1275041617769664515/artifacts/task-01-add-kubernetes-versions-log.txt

i will send a PR to increase these timeouts.

**Comment by neolit123** [comment]
> i will send a PR to increase these timeouts.

https://github.com/kubernetes/kubeadm/pull/2193

**Comment by liggitt** [comment]
Is that test now named https://testgrid.k8s.io/sig-release-1.19-informing#kubeadm-kinder-upgrade-1-18-1-19 ?

**Comment by neolit123** [comment]
yes.
i see some occasional flakes of not being able to complete the conformance suite in 25 minutes (parallel).

**Comment by neolit123** [comment]
/retitle [Flaky Test] kubeadm-kinder-upgrade-1-18-1-19 (ci-kubernetes-e2e-kubeadm-kinder-upgrade-1-18-1-19)

**Comment by neolit123** [comment]
i can conform that the suite requires mostly more than 25 minutes in later releases (either due to more tests or slower infra).
this PR increases the e2e test suite in kubeadm to 35 minutes and will close this ticket:
https://github.com/kubernetes/kubeadm/pull/2297

we should create new / separate tickets with flaky tasks in the job.
