### ISSUE TITLE
Problem with hello-world minikube

### ISSUE THREAD

**Issue by a-prezioso** [kubernetes/kubernetes#90798]
Hello guys, I have a problem running hello-minikube in kubernetes. 
This is the command --> 
run hello-minikube --image=gcr.io/google_containers/echoserver:1.4 --port=8080

This the result --> 
error: v1.ReplicationController: ObjectMeta: v1.ObjectMeta: readObjectFieldAsBytes: expect : after object field, parsing 740 ...:{},"k:{\"... at {"kind":"ReplicationController","apiVersion":"v1","metadata":{"name":"hello-minikube","namespace":"default","selfLink":"/api/v1/namespaces/default/replicationcontrollers/hello-minikube","uid":"8c3308f7-eae2-4638-93be-c2c60465629a","resourceVersion":"945","generation":1,"creationTimestamp":"2020-05-06T10:08:33Z","labels":{"run":"hello-minikube"},"managedFields":[{"manager":"kubectl","operation":"Update","apiVersion":"v1","time":"2020-05-06T10:08:33Z","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:labels":{".":{},"f:run":{}}},"f:spec":{"f:replicas":{},"f:selector":{".":{},"f:run":{}},"f:template":{".":{},"f:metadata":{".":{},"f:creationTimestamp":{},"f:labels":{".":{},"f:run":{}}},"f:spec":{".":{},"f:containers":{".":{},"k:{\"name\":\"hello-minikube\"}":{".":{},"f:image":{},"f:imagePullPolicy":{},"f:name":{},"f:ports":{".":{},"k:{\"containerPort\":8080,\"protocol\":\"TCP\"}":{".":{},"f:containerPort":{},"f:protocol":{}}},"f:resources":{},"f:terminationMessagePath":{},"f:terminationMessagePolicy":{}}},"f:dnsPolicy":{},"f:restartPolicy":{},"f:schedulerName":{},"f:securityContext":{},"f:terminationGracePeriodSeconds":{}}}}}}]},"spec":{"replicas":1,"selector":{"run":"hello-minikube"},"template":{"metadata":{"creationTimestamp":null,"labels":{"run":"hello-minikube"}},"spec":{"containers":[{"name":"hello-minikube","image":"gcr.io/google_containers/echoserver:1.4","ports":[{"containerPort":8080,"protocol":"TCP"}],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","imagePullPolicy":"IfNotPresent"}],"restartPolicy":"Always","terminationGracePeriodSeconds":30,"dnsPolicy":"ClusterFirst","securityContext":{},"schedulerName":"default-scheduler"}}},"status":{"replicas":0}}

This is my version of kubectl -->
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"6e937839ac04a38cac63e6a7a306c5d035fe7b0a", GitTreeState:"clean", BuildDate:"2017-09-28T22:57:57Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:50:46Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}

I'm tried to uninstall kubectl because I red that I have an older version on kubectl(client version), but I don't know how can I uninstall It

Can anyone please help me?

**Comment by nikhita** [comment]
> I'm tried to uninstall kubectl because I red that I have an older version on kubectl(client version), but I don't know how can I uninstall It

Please see [here](https://kubernetes.io/docs/tasks/tools/install-kubectl/) for instructions on how to install a newer version of kubectl.

If you need additional help with the issue, please re-post your question to [Stack Overflow](http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support
are posted so that we can improve our efficiency in responding to your requests,
and to make it easier for you to find answers to frequently asked questions and
how to address common use cases.

We regularly see messages posted in multiple forums, with the full response
thread only in one place or, worse, spread across multiple forums. Also, the
large volume of support issues on github is making it difficult for us to use
issues to identify real bugs.

Members of the Kubernetes community use Stack Overflow to field support
requests. Before posting a new question, please search Stack Overflow for answers
to similar questions, and also familiarize yourself with:

  * [user documentation](https://kubernetes.io/docs/home/)
  * [troubleshooting guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/)

Again, thanks for using Kubernetes.

The Kubernetes Team
