### ISSUE TITLE
Expose audit events as list-watchable k8s API resource

### ISSUE THREAD

**Issue by MOZGIII** [kubernetes/kubernetes#90835]
**What would you like to be added**:
Add an `AuditEvent` resource (or similar) that can be list-watched via the k8s API.

**Why is this needed**:
It would enable a simple way to pull out the audit events for tools that already know to talk k8s API server protocol.
This is different to watching the raw `Event`s because there is `Policy` that can affect the data.

**Comment by liggitt** [comment]
Thanks for the feature request, but this would have many of the same problems as the removed dynamic audit capability (combining API-driven access to audit events with static policy configuration produces unpredictable results). See https://groups.google.com/g/kubernetes-sig-auth/c/aV_nXpa5uWU for the reasons the dynamic audit feature was removed before graduating from alpha.

Additionally, this would not include audit events from all servers in multi-server environments (since the API server serving the list/watch would not have access to the audit events generated from other servers).

/close

**Comment by MOZGIII** [comment]
Thanks for the response! Great, we'll just focus on other methods of gathering the audit data then!

**Comment by tallclair** [comment]
To follow up to what Jordan said, this is something that we've previously discussed building as an audit webhook. In other words, implement what you asked for out-of-tree, by setting up the "audit server" as the webhook backend. If this is something you'd be interested in working on, I would sponsor it for kubernetes-sigs.
