### ISSUE TITLE
Un-Pend the FULL namespace drain test 

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/kubernetes#9084]
in #8434  we merged in a test which 
- right now we confirm 90% of 100 namespaces are deleted : ( `func() { extinguish(c, 100, 10, 150) })`) in a timely manner.  
-  Lets remove `PIt` for the 100% drainage test .... `func() { extinguish(c, 100, 0, 150) })` .  Right now, this doesnt always pass easily, but that will clear up eventually.

cc intersted parties @vmarmol  @derekwaynecarr @timothysc @rrati

**Comment by derekwaynecarr** [comment]
So I read the test as follows:

create a 100 namespaces
wait 10 seconds 

[during this period, the system is generating a service account per namespace, and it is generating 2 secrets per acount if I recall]

list all 100 namespaces
delete all 100 namespaces
 [ error if they are not gone in 150 seconds, poll server every 2s to take a look]

In practice, this means that we are deleting 100 namespace entries in etcd, and deleting ~200 tokens, and ~100 service accounts assuming their controllers are keeping pace.

I am ok to remove the ```PIt``` for that test if and only if we NEVER create pods in those namespaces because of their graceful delete semantics, and we remove the ```PIt``` after DELETE collection lands, which looks more like post-1.0 in my book.

**Comment by jayunit100** [comment]
- yup thats the way the test works.
- we can shoot for post-1x to s `PIt`->`It`.
thanks for the update on this derek .  looks like eric set the v1.0-post milestone already, also .

**Comment by timothysc** [comment]
@jayunit100 - update?

**Comment by jayunit100** [comment]
ack @timothysc , lets ask @derekwaynecarr : do you think NS deletion is reliable enough know that we can upend the 100% extinguished namespaces ?

**Comment by timothysc** [comment]
I believe there is still a PR inflight on namespace cleanup that we should cross-ref.

**Comment by derekwaynecarr** [comment]
This still is blocked by a namespace cleanup card I am wanting to get done
this sprint.

**Comment by jayunit100** [comment]
Hi @derekwaynecarr , shall we upend this? Do you think NS cleanup will be 100% now?

**Comment by kargakis** [comment]
Status of this issue?

**Comment by jayunit100** [comment]
lets bump it to 1.7 ~ its not a good time to add a potentially new flake !:)

**Comment by liggitt** [comment]
now that we're at the end of 1.7, it's not a good time now either. If we still think this is valuable, @jayunit100 can you open a PR to implement this and we can merge it at the *beginning* of 1.8?

**Comment by jayunit100** [comment]
Okidoki . Easy one liner anyone can open it .

**Comment by jayunit100** [comment]
I'm going to close this for now since it isn't being tracked by anyone other than me, and I haven't seen issues with this in a while .   I think it's fairly obvious that unpending e2es is a good thing in a flake free alternate reality once we get there :).
