### ISSUE TITLE
Error updating managedFields in custom resource: failed to update ManagedFields: failed to convert old object

### ISSUE THREAD

**Issue by yue9944882** [kubernetes/kubernetes#91006]
**What happened**:

1. following https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#create-a-customresourcedefinition to create a CRD named `crontabs.stable.example.com` and then following https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#create-custom-objects to create a CR named `my-new-cron-object` in a v1.18+ cluster.
2. clearing managedFields by following https://kubernetes.io/docs/reference/using-api/api-concepts/#clearing-managedfields using kubectl:

> kubectl patch ct my-new-cron-object --type json -p '[{"op": "replace", "path": "/metadata/managedFields", "value": [{}]}]'
> kubectl patch ct my-new-cron-object --type merge -p '{"metadata":{"managedFields": [{}]}}' 

3. it will always fail with error messages: `Error from server: failed to update object (json PATCH for stable.example.com/v1, Kind=CronTab) managed fields: failed to update ManagedFields: failed to convert old object: stable.example.com/v1, Kind=CronTab is unstructured and is not suitable for converting to ""`

i tried the same on built-in resources and it works like a charm. is there a way to clear the field from CR?

/cc @kubernetes/sig-api-machinery-misc

**Comment by liggitt** [comment]
the fact that this returns an error is a bug that will be fixed, but note that managedFields are always populated server-side, so even after this is fixed, it will not be possible to persist an update without managedFields set

**Comment by liggitt** [comment]
cc @apelisse 

#90906 will resolve/mask the error, but it would be good to root cause the specific reason for the message

**Comment by apelisse** [comment]
Absolutely, 2nd report for this bug, I don't think it's a big thing, but we're certainly missing a test here.

**Comment by apelisse** [comment]
Thanks for the report @yue9944882, would you be able to share the CRD?

**Comment by liggitt** [comment]
looks like the crontab example at https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#create-a-customresourcedefinition

**Comment by apelisse** [comment]
Cool, thanks, we should be able to build a test with that.

**Comment by yue9944882** [comment]
__update__: to remove some entries from managedFields, i was able to work-around by patching the managedFields w/ a list of single non-empty managedField e.g. a merge patch like:

> {"metadata":{"managedFields":[{"apiVersion":"stable.example.com/v1","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:labels":{"f:foo":{}}},"f:spec":{"f:cronSpec":{},"f:image":{}}},"manager":"foo","operation":"Apply","time":"2020-05-13T02:41:17Z"}]}}

**Comment by kwiesmueller** [comment]
Okay, i think the problem is a difference between the converters for crds and non-crds.
When resetting the managedFields, we have to send `{[]}` insted of just an empty object or null.
This is to allow not sending them without causing them to change (as documented).

For internal resources, that results in an update with a single incomplete/invalid managedFields entry. The Updater then tries to find conflicts with every other manager and to do that, it converts the objects to the respective version:
https://github.com/kubernetes-sigs/structured-merge-diff/blob/master/merge/update.go#L65

This calls the converter and if it's not possible to convert to the specific version, the manager gets removed. This check is done by `s.Converter.IsMissingVersionError(err)` which is implemented here:
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/fieldmanager/internal/versionconverter.go#L100

It checks if the error returned by the objectConvertor is of a specific type and the convertor for internal types returns it if provided with an empty/incomplete version:
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/runtime/scheme.go#L531 (which returns a `NewNotRegisteredErrForKind(s.schemeName, kind)`)

But crds don't return this kind of error:
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/conversion/converter.go#L166
And there is a todo item regarding this in the code.

To fix this problem, we can either handle empty versions in the fieldManager or fix this piece of code. The right error is probably one of those:
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/runtime/error.go#L45

@jennybuckley do you have an opinion on that?

**Comment by liggitt** [comment]
Shouldn't https://github.com/kubernetes-sigs/structured-merge-diff/blob/master/merge/update.go#L65 avoid trying to convert to an empty version that is never valid?

**Comment by kwiesmueller** [comment]
@yue9944882 as a temporary workaround it just worked for me to reset the managedFields with a body like this: `{"metadata":{"managedFields": [{"apiVersion": "stable.example.com/v1"}]}}`

**Comment by kwiesmueller** [comment]
@liggitt yeah, we could check the version before doing the conversion if it's empty.
But as far as i see, the conversion should still be able to remove managers with outdated/removed versions. At least that's what i understood as the reason for it being this way.

**Comment by kwiesmueller** [comment]
And the crd converter does not return any error that is able to hand that information to the updater.

**Comment by liggitt** [comment]
It's unclear to me what a user is supposed to do if they get in a scenario where a field manager update cannot successfully convert… is their object just stuck?

**Comment by liggitt** [comment]
> we have to send `{[]}`

isn't that explicitly an invalid managedFieldEntry?

**Comment by kwiesmueller** [comment]
> isn't that explicitly an invalid managedFieldEntry?
Yes and it should result in the fields being cleared. I suppose we should clear it before going into an update.

Regarding the conversion question, i'm not too sure myself.
As far as I understand, it only fails if there is an existing manager with an old version. If the objects can't be converted to this managers version, because it is not known, we remove said manager.
So if the conversion fails with one of the expected errors, we remove. If not, we fail the update.
I think @apelisse already has a PR to only log those errors in the unknown cases.

But the conversion used seems to be the general conversion mechanism in Kubernetes, so i'd expect a failure for cases other than unknown versions as it means the object is broken. So we're not converting managedFields, but the new and old object to the version stored in managedFields. Correct me if i'm wrong.

If a user gets stuck there, the solution would be to clear the managedFields which will result in no conversions (if the code were correct).

**Comment by apelisse** [comment]
I think this bug is fixed by #91748. There are still things we can do better (and we're actively working on these), but that behavior specifically is fixed.
