### ISSUE TITLE
How to restart 100's of pods at a time

### ISSUE THREAD

**Issue by manojchandrabss** [kubernetes/kubernetes#91087]
Hi team,

we are having 1000's of pods running for our application. due to some reason we need to restart 100's of pods. is there any way we can do it in kubernetes using kubectl or any other tool. Please advice. it should be pure pod restart

**Comment by manojchandrabss** [comment]
sig/cli

**Comment by nikhita** [comment]
@manojchandrabss This looks like a question best suited to a Kubernetes
user forum. Please re-post your question to [Stack Overflow](http://stackoverflow.com/questions/tagged/kubernetes)
or our [Discussion Forums](https://discuss.kubernetes.io).

We are trying to consolidate the channels to which questions for help/support
are posted so that we can improve our efficiency in responding to your requests,
and to make it easier for you to find answers to frequently asked questions and
how to address common use cases.

We regularly see messages posted in multiple forums, with the full response
thread only in one place or, worse, spread across multiple forums. Also, the
large volume of support issues on github is making it difficult for us to use
issues to identify real bugs.

Members of the Kubernetes community use Stack Overflow to field support
requests. Before posting a new question, please search Stack Overflow for answers
to similar questions, and also familiarize yourself with:

  * [user documentation](https://kubernetes.io/docs/home/)
  * [troubleshooting guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/)

Again, thanks for using Kubernetes.

The Kubernetes Team

**Comment by manojchandrabss** [comment]
@nikhita Thanks for your response, I've posted this is stack overflow and kubernetes discussion forums
