### ISSUE TITLE
Scheduler's volume benchmarks errors

### ISSUE THREAD

**Issue by ahg-g** [kubernetes/kubernetes#91157]
**What happened**:
When running the new benchmark suite, volume related benchmarks spam the logs with the following error:

"error selecting node for pod: running "VolumeBinding" filter plugin for pod "pod-fxwv5": pod has unbound immediate PersistentVolumeClaims"

We need to look into that and perhaps adjust the benchmark to make sure it runs as expected.

**How to reproduce it (as minimally and precisely as possible)**:
Here is how to run the benchmarks:
```make test-integration WHAT=./test/integration/scheduler_perf KUBE_TEST_VMODULE="''" KUBE_TEST_ARGS="-alsologtostderr=false -logtostderr=false -run=^$$ -benchtime=1ns -bench=BenchmarkPerfScheduling"```

/assign @ingvagabund 
/sig scheduling

**Comment by ingvagabund** [comment]
I will check it out tomorrow, thanks.

**Comment by ingvagabund** [comment]
Checking the logs there's a lot of `pod has unbound immediate PersistentVolumeClaims`. Though, 
strong majority of them is reported for a different pod and only once. Tracing the code into `VolumeBinding` plugin and `pl.Binder.FindPodVolumes` code, the error says "pvc.Spec.VolumeName" of a specific pvc is not set yet. So it's just a matter of timing since eventually all pods are bound to a node.

Also, notice line in https://github.com/kubernetes/kubernetes/blob/master/test/utils/runners.go#L1372 (in `CreatePodWithPersistentVolume` function):
```
// bind pvc to "pv-$i"
// pvc.Spec.VolumeName = pv.Name
pvc.Status.Phase = v1.ClaimBound
```

After uncommenting `pvc.Spec.VolumeName = pv.Name` line, the error message is gone.

@ahg-g nothing to be done here

**Comment by ingvagabund** [comment]
@ahg-g anything else to be done here?

**Comment by ahg-g** [comment]
/close

no, I just checked again, you are right.

**Comment by ahg-g** [comment]
I was mainly wondering wether that commented out code was done by mistake or not, but it is not, the pv controller will eventually set `VolumeName`.
