### ISSUE TITLE
[8] System error: Activation of org.freedesktop.systemd1 timed out when running pod through replication conroller

### ISSUE THREAD

**Issue by tslater** [kubernetes/kubernetes#9124]
When I run one of my replication controllers, one of the replicas never starts and gives me this error message:
```
Failed to start with docker id 7125bd7fe380a4ef7c2e311cff7e067fdf5a73559d3e2bf8f97f3715da9a77e0 with error: API error (500): Cannot start container 7125bd7fe380a4ef7c2e311cff7e067fdf5a73559d3e2bf8f97f3715da9a77e0: [8] System error: Activation of org.freedesktop.systemd1 timed out
```

**Comment by bgrant0607** [comment]
Kubernetes version, OS distro, docker version, cloud provider?

**Comment by tslater** [comment]
Kubernetes: 
```
Client Version: version.Info{Major:"0", Minor:"17", GitVersion:"v0.17.0", GitCommit:"82f8bdac06ddfacf493a9ed0fedc85f5ea62ebd5", GitTreeState:"clean"}
Server Version: version.Info{Major:"0", Minor:"17", GitVersion:"v0.17.0", GitCommit:"82f8bdac06ddfacf493a9ed0fedc85f5ea62ebd5", GitTreeState:"clean"}
```
OS Distro: ```CoreOS 681.0.0```
Docker: ```Docker version 1.6.2, build 7c8fca2-dirty```
Cloud Provider: ```Vagrant```

**Comment by thenikso** [comment]
+1 all my pods are down for this reason

```
Client Version: version.Info{Major:"1", Minor:"0.0", GitVersion:"v1.0.0", GitCommit:"", GitTreeState:"not a git tree"}
Server Version: version.Info{Major:"0", Minor:"20", GitVersion:"v0.20.2", GitCommit:"323fde5bc5c45e30bbb5451ccf5c1ff01b0717f7", GitTreeState:"clean"}
```

**Comment by goltermann** [comment]
We’re going through old support issues and asking everyone to direct your questions to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes). 

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases. 

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

**Comment by erictune** [comment]
This is https://github.com/coreos/go-systemd/pull/49

**Comment by erictune** [comment]
Need to remove underscores from container name.
