### ISSUE TITLE
Need for ./cluster/kube-halt.sh (which halts cluster gracefully instead of destroying VMs)

### ISSUE THREAD

**Issue by pramttl** [kubernetes/kubernetes#9134]
There are [kube-up.sh](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cluster/kube-up.sh) and [kube-down.sh](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cluster/kube-down.sh) scripts which call `vagrant up` and `vagrant destroy` respectively internally when environment variable KUBERNETES_PROVIDER is set to 'vagrant'.

It would be especially useful to have `kube-halt.sh' which would simply halt the cluster gracefully instead of destroying the VM's as it takes a lot of time to bring the cluster up again using kube-up.sh.

**Comment by javapapo** [comment]
+1 indeed it would be nice if it was added.

**Comment by roberthbailey** [comment]
I'm not sure there is a general need for kube-halt. If it would be useful for vagrant we could add a special script to optimize that specific use case.

**Comment by derekwaynecarr** [comment]
I agree that ```vagrant halt``` should work, but have not had the time to resolve the underlying issue.

We could then update kube-up and kube-push for vagrant to determine that the machines already existed.

PRs welcome.

**Comment by derekwaynecarr** [comment]
So I just tried the following:

```
$ cluster/kube-up.sh
$ vagrant halt
$ cluster/kube-up.sh
```

The cluster comes back up quicker, and appears to be functional.

I would need to run the conformance suite before and after update to ensure networking has no unique issues anymore (I think things are better here now that provision-network.sh moved out of the Salt space).

Let me know if this flow works better for you, and if so we can just doc it.

**Comment by javapapo** [comment]
Hello, for me on version 1.0.2 (with the vagrant script patch) vagrant halt works as expected, the vms are halted.
But when I try to do a kube-up.sh

The master is reported to be up and running, the minion seems to be runnig according to the virtual box console, but the kube-up script reports the following.

he user name and password to use is located in ~/.kubernetes_vagrant_auth.

... calling validate-cluster
Waiting for 1 ready nodes. 0 ready nodes, 1 registered. Retrying.
Waiting for 1 ready nodes. 0 ready nodes, 1 registered. Retrying.
Waiting for 1 ready nodes. 0 ready nodes, 1 registered. Retrying.
Waiting for 1 ready nodes. 0 ready nodes, 1 registered. Retrying.
Waiting for 1 ready nodes. 0 ready nodes, 1 registered. Retrying.

I am not sure if it is due to 1.0.2 version (1.0.3 is broken in terms of vagrant setup) and I am waiting for 1.0.5 to retry 

Thanks for your time

**Comment by derekwaynecarr** [comment]
All things should be fixed now in 1.0.5.
