### ISSUE TITLE
Actual CPU capacity is lower than assigned CPU capacity when gVisor sandbox is enabled in GKE

### ISSUE THREAD

**Issue by sadjunky** [kubernetes/kubernetes#91665]
**What happened**:
Enabling gVisor sandbox lowered actual CPU capacity from the assigned capacity. For example, assigning 6 CPU cores to a node reduces it to 3 CPU cores capacity.

**What you expected to happen**:
CPU capacity and assigned CPU should match.

**How to reproduce it (as minimally and precisely as possible)**:
Enable gVisor sandbox while creating a node pool.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.15.11-gke.11
- Cloud provider or hardware configuration: Google Cloud Platform (Google Kubernetes Engine)
- OS (e.g: `cat /etc/os-release`): Container-Optimized OS with Containerd (cos_containerd)
- Kernel (e.g. `uname -a`): Linux 4.19.104+ #1 SMP Wed Feb 19 05:26:34 PST 2020 x86_64 Intel(R) Xeon(R) CPU @ 2.30GHz GenuineIntel GNU/Linux
- Install tools: N/A
- Network plugin and version (if this is a network-related bug): N/A
- Others: gVisor sandbox enabled node pool

**Comment by Scorpiion** [comment]
Hi, I have also run into the exact same issue. I have tested on two clusters and both show CPU Capacity to be half the number of CPUs on the nodes. 

Do anyone know why this is happening or any workarounds?

**Comment by Scorpiion** [comment]
I just figured out why this is happening, it's a side effect of the GKE sandbox disabling hyperthreading on the nodes. To my understanding on google compute engine (and hence GKE) one vCPU is equal to one hyperthread. When hyperthreading is disabled I'm guessing the definition of a core becomes different, maybe the number of underlying physical cores rather than hyperthreads. 

The second link below shows how to enable hyperthreading combined with GKE sandbox (with a somewhat reduced security/sandbox level). I think this issue can be closed now as this is not a Kubernetes bug, rather something that maybe could be made more clear in GKE's documentation. 

## Source on GKE Sandbox
https://cloud.google.com/kubernetes-engine/docs/concepts/sandbox-pods#hyper-threading_is_disabled

## Source on hyperthread to vCPU
https://news.ycombinator.com/item?id=21765537
