### ISSUE TITLE
[kubelet-check] Initial timeout of 40s passed

### ISSUE THREAD

**Issue by Dunoyer** [kubernetes/kubernetes#91681]
Hi, 
I have two dedicated servers with docker installed on it. I want to configure one of the servers in Master but the kubeadm init command does not work. I have a timeout at step [kubelet-check]. Can you help me ?

![image](https://user-images.githubusercontent.com/8861662/83534901-b4771c80-a4f1-11ea-92ff-fc7692cac390.png)

and 

![image](https://user-images.githubusercontent.com/8861662/83534993-cce73700-a4f1-11ea-9d67-b6210376f1e0.png)

I need help please ?

**Comment by neolit123** [comment]
hi, this usually means that he kubelet is not starting / healthy.
you should use `journalctl -xeu kubelet` and look at the kubelet logs for errors.

but please use the support channels for this instead of this issue tracker:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

thanks.
/remove-kind bug
/triage support
/close
