### ISSUE TITLE
Scheduler: remove dependency on pkg/apis/core/v1/helper

### ISSUE THREAD

**Issue by ingvagabund** [kubernetes/kubernetes#91782]
As part of reducing dependency on the main k8s.io/kubernetes project (see https://github.com/kubernetes/kubernetes/issues/89930) and allowing the scheduling framework to be eventually moved under staging repo.

The goal here is the remove dependency on `k8s.io/kubernetes/pkg/apis/core/v1/helper` package. The following functions from `k8s.io/kubernetes/pkg/apis/core/v1/helper` are still imported from within `pkg/scheduler`:
- **GetAvoidPodsFromNodeAnnotations**: `v1.PreferAvoidPodsAnnotationKey` string used in the function is defined under `k8s.io/kubernetes/staging/src/k8s.io/api/core/v1`. `k8s.io/kubernetes/staging/src/k8s.io/api/core/v1` has a bunch of files with methods defined over the core types. Question is what are the condition for adding new functions/methods to the package.
- **GetPersistentVolumeClaimClass**: `v1.BetaStorageClassAnnotation` string used in the function is defined under `k8s.io/kubernetes/staging/src/k8s.io/api/core/v1`.
- **HugePageResourceName**: `v1.ResourceHugePagesPrefix` string used in the function is defined under `k8s.io/kubernetes/staging/src/k8s.io/api/core/v1`.
- **IsAttachableVolumeResourceName**: `v1.ResourceAttachableVolumesPrefix`
- **IsExtendedResourceName**: `v1.DefaultResourceRequestsPrefix`
- **IsHugePageResourceName**: `v1.ResourceHugePagesPrefix` string used in the function is defined under `k8s.io/kubernetes/staging/src/k8s.io/api/core/v1`.
- **IsScalarResourceName**: depends on `IsHugePageResourceName`, `IsExtendedResourceName`, `IsPrefixedNativeResource` (`v1.ResourceDefaultNamespacePrefix`) and `IsAttachableVolumeResourceName` 
- **MatchNodeSelectorTerms**: depends on `k8s.io/kubernetes/staging/src/k8s.io/api/core/v1` bits.
- **NodeSelectorRequirementsAsSelector**: depends on `k8s.io/kubernetes/staging/src/k8s.io/api/core/v1` bits.
- **TolerationsTolerateTaint**: depends on `v1.Toleration` and `v1.Taint`
- **FindMatchingUntoleratedTaint**: depends on `v1.Toleration` and `v1.Taint`

I am pretty sure there's a reason why all the core v1 helper functions are under `k8s.io/kubernetes/pkg/apis/core/v1/helper` and not under `k8s.io/kubernetes/staging/src/k8s.io/api/core/v1`.

**Comment by ingvagabund** [comment]
Additionally:
- `GetPersistentVolumeClaimClass`:
  - kubernetes org: https://github.com/search?q=org%3Akubernetes+GetPersistentVolumeClaimClass&type=Code (5 times used, 3 times defined)
  - kubernetes-sigs org: https://github.com/search?q=org%3Akubernetes-sigs+GetPersistentVolumeClaimClass&type=Code (3 times used, 0 times defined)
- `HugePageResourceName`:
  - kubernetes org: https://github.com/search?q=org%3Akubernetes+HugePageResourceName&type=Code (3 times used, 0 times defined)
  - kubernetes-sigs: https://github.com/search?q=org%3Akubernetes-sigs+HugePageResourceName&type=Code (0 times used, 0 times defined)
- `IsAttachableVolumeResourceName`:
  - kubernetes org: https://github.com/search?q=org%3Akubernetes+IsAttachableVolumeResourceName&type=Code (7 times used, 2 times defined)
  - kubernetes-sigs org: https://github.com/search?q=org%3Akubernetes-sigs+IsAttachableVolumeResourceName&type=Code (0 times used, 0 times defined)

**Comment by damemi** [comment]
Thank you for this thorough breakdown @ingvagabund! You have explained the questions we're facing perfectly. I am a bit confused by the chart in https://github.com/kubernetes/kubernetes/issues/91782#issuecomment-639084276, is it breaking down "Used (ie, imported from pkg/apis/)" vs "Defined (ie, duplicated into its own definition)"? I ask because some examples, like `NodeSelectorRequirementsAsSelector` has 1/0, but it's actually [duplicated and defined locally](https://github.com/search?q=org%3Akubernetes-sigs+NodeSelectorRequirementsAsSelector&type=Code). Other than that I think you've perfectly explained our questions on import policy.

This ultimately concerns developers of out-of-tree, downstream, and 3rd party components. It also hinges on this assumption:

> The second question deals with the fact that the helper functions can't be currently imported through go modules since the main kubernetes repo is not meant to be a module.

We hit this a couple releases ago, while go modules were still young in k8s. There were some helper packages in k8s.io/kubernetes imported by the descheduler which weren't even available in the tagged k/k module (I think this was around `v0.17.0`). This required us to copy them, and we still hit dependency conflicts depending on `k8s.io/kubernetes`. 

I am assuming that it's still true that this main repo isn't intended to be imported as a module by other components (though I'm not aware of an explicit rule saying "don't import anything from this repo"). If that's the case then a policy on core API helpers would be helpful for out-of-tree developers.

Since these are helpers for the `core/v1` api, I would assume that the underlying types (and so, the helpers that interpret those types) won't change. This would make it safe to duplicate them, and if any semantic changes do arise down the road it will be up to the maintainers of components that duplicate the helpers to be aware of those changes.

If there is a chance that the semantics of such api helpers could change, then I would advocate for hosting them in a staging repo (like apimachinery?) so that developers of external components can depend on them while being confident that their usage will remain consistent with the design of core kubernetes.

**Comment by ingvagabund** [comment]
> I ask because some examples, like NodeSelectorRequirementsAsSelector has 1/0, but it's actually duplicated and defined locally. 

You are right. Entry updated. The table is primarily for pointing out there are serious repositories duplicating the helpers instead of importing them from the main k/k repo.

**Comment by damemi** [comment]
/remove-lifecycle stale
can we reasses which areas of the framework are still dependent on this to evaluate the work that still needs to be done?
