### ISSUE TITLE
Set schedulers default plugins via component config defaulting

### ISSUE THREAD

**Issue by ahg-g** [kubernetes/kubernetes#92037]
Currently the scheduler's default plugins are set in pkg/scheduler/factory.go through ```Configurator```. 

Since the set of plugins that we configure the scheduler with comes from component config, it is more proper to set the default list of plugins through [component config defaulting](https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/apis/config/v1beta1/defaults.go) mechanism.

/sig scheduling
/assign @adtac

**Comment by ahg-g** [comment]
@adtac I can't assign to you since you are not a member yet, but we will consider this on your plate for 1.20.

**Comment by adtac** [comment]
Unassigning myself as I don't think I'll have the time to work on this.

/unassign
/help

**Comment by erismaster** [comment]
👋  Bug Triage here, we're pretty late into code freeze and there are no assignees, I am going to remove the 1.20 milestone.

/milestone clear

**Comment by alculquicondor** [comment]
@gavinfish what is the overall plan you have to achieve this? What is the final state, in terms of imports.

**Comment by gavinfish** [comment]
@alculquicondor I want to move some default plugins like https://github.com/kubernetes/kubernetes/blob/e3de62298a730415c5d2ab72607ef6adadd6304d/pkg/scheduler/factory.go#L262-L274 into `SetDefaults_KubeSchedulerConfiguration` method, so that we do not need set some default settings in factory.

And this will lead `/pkg/scheduler/apis/config/v1beta1` depends on `/pkg/scheduler/framework/plugins/defaultpreemption`. Besides currently defaultpreemption has already depended on v1beta1 passed by core. See below for the details.

```
package k8s.io/kubernetes/pkg/scheduler
	imports k8s.io/kubernetes/pkg/scheduler/algorithmprovider
	imports k8s.io/kubernetes/pkg/scheduler/framework/plugins/defaultpreemption
	imports k8s.io/kubernetes/pkg/scheduler/core
	imports k8s.io/kubernetes/pkg/scheduler/framework/runtime
	imports k8s.io/kubernetes/pkg/scheduler/apis/config/scheme
	imports k8s.io/kubernetes/pkg/scheduler/apis/config/v1beta1
	imports k8s.io/kubernetes/pkg/scheduler/framework/plugins/defaultpreemption: import cycle not allowed
```

**Comment by alculquicondor** [comment]
Other than import cycles, we need to do what is right:
configuration packages cannot depend on runtime packges. But runtimes packages can certainly depend on configuration packages. With that, perhaps plugin names should live in the configuration packages.

BUT....
This discussion comes back to my mind https://github.com/kubernetes/kubernetes/pull/95048#discussion_r500614354
Perhaps the way we are doing defaulting today is better: calculate the plugins that should run at the application layer, rather than configuration layer.
