### ISSUE TITLE
Admission Controller Webhook configuration rule cannot exclude specific resources

### ISSUE THREAD

**Issue by patrick-east** [kubernetes/kubernetes#92157]
**What would you like to be added**:
The webhook configuration (for both `ValidatingWebhookConfiguration` and `MutatingAdmissionWebhook`, reference https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/) support `rules` to select what types of resources should be sent to the webhook endpoint. The rule definitions can have a set of `resources` which specifies which resource types should be selected.

What is missing is the ability to specify what resources to exclude. There does not appear to be a way to give any negative selection criteria.

**Why is this needed**:
In practice, systems where an external policy engine like OPA are being used as the webhook endpoint, it is common to want broad coverage of the admission policy. This is typically done by specifying wildcards in the webhook configuration and allowing the policies in OPA to self select what types of objects they apply to.

In these same systems, with wildcard webhook configurations, if the `failurePolicy` is set to `Fail` it is extremely difficult for the `rules` definitions to allow for a cluster to recover in network failure modes.

For example, if for sake of argument, the network is based on Calico and requires objects in the cluster to be modified (eg ippools, felixconfigurations, clusterinformations, bgpconfigurations, bgppeers, etc) when the network is down, the api-server may not be able to successfully call the webhook, which can prevent the network controllers from converging back to a working state. The only way to correct the issue is to remove the webhook, allow the network to repair, and re-apply it. Throughout this time however it means that the cluster is potentially un-protected.

Ideally a cluster admin could configure the webhook to exclude certain resources. The only option right now appears to be to specify *every* type of resource expected to be in the cluster and omit the ones that should be excluded. In practice, the list of all resources allowed on the cluster is often unknown at the time the webhook is configured, making this approach infeasible.

Note: The namespace selector will not help in this scenario, as there can be cluster scoped resources involved.

**Comment by maxsmythe** [comment]
+1 to the ability to carve out certain kinds being useful.

This would allow users to select between a "lock it all down and open up only what we use" approach and the current approach that emphasizes webhook opt-in.

**Comment by ritazh** [comment]
+1

**Comment by enj** [comment]
@kubernetes/sig-api-machinery-feature-requests 

Perhaps the OPA approach for configuring a webhook via a YAML manifest is incorrect.  I think it may make more sense for OPA to provide a controller that watches all OPA policies and then generates the appropriate admission webhook on the fly (and deletes it when there are no OPA policies).  This seems more sustainable to me because then the cluster admin does not need to manage the allow or deny list at all.  It will also prevent the OPA webhook from being invoked on resources that have no matching policies.  If OPA goes down, then only the resources with a matching policy will be broken.

Note that the complete list of resources on a cluster can be determined by a controller via discovery.  So even if an OPA policy matches on resources like `.*RoleBinding`, the controller could build the flattened list (and it could handle negation as well).

**Comment by patrick-east** [comment]
> Note that the complete list of resources on a cluster can be determined by a controller via discovery. So even if an OPA policy matches on resources like .*RoleBinding, the controller could build the flattened list (and it could handle negation as well).

Thats an interesting point. I guess the downside is that there would be a window of opportunity when a new CRD is added and the proposed controller detecting it and updating the webhook configuration where policies that would otherwise have been applied were ignored. I would hazard a guess that the folks who want fail-closed admission webhooks would not be keen on having that sort of problem.

**Comment by maxsmythe** [comment]
One area where this breaks down is if the policy admin and the cluster admin are two different people. The biggest reason to avoid webhok calls is to prevent downtime in the webhook from causing resources to become un-modifiable. It is certainly reasonable for the policy admin to say something like "I want everyone to set an owner label on their resources" and for the root admin to specifically carve out important resources from that policy because the impact on the cluster would be too great. In larger organizations, the person setting policy and the person managing the cluster may not have overlapping knowledge sets and allowing the cluster admin to prevent sub-admins from breaking there cluster seems a compelling use case.

Setting the policy on the webhook also prevents privilege-escalation-type DOS attacks where a malicious webhook admin (who otherwise has no access to VWH configs) adds resources that they know would bork the cluster, causing the ValidatingWebhookConfiguration to get modified to include those resources.

Probably the biggest reason to avoid doing this is that it potentially closes the "escape hatch" built into validating webhooks. By default, VWH configurations are not subject to webhook validation because doing so could cause a circular dependency whereby the cluster is hard-downed with no remedy. Since VWH configuations can always be removed, a bad webhook can always be disabled. If you have a controller enforcing the existence of this webhook configuration, then that escape hatch is at risk -- a user could attempt to modify/delete the VWH config only to see it recreated, leaving them unable to remedy their webhook issue.

**Comment by maxsmythe** [comment]
Also, +1 to dynamically configuring the webhook config makes it harder to reason about the state of enforcement if the webhook itself is also dynamically configurable.

**Comment by enj** [comment]
> I guess the downside is that there would be a window of opportunity when a new CRD is added and the proposed controller detects it and updates the webhook configuration where policies that would otherwise have been applied were ignored

Just wait until the webhook is updated before granting authorization access?  The webhook itself could enforce that if authorization is done via RBAC.  You can also use a CLI based webhook authorizer to lock this down.

> allowing the cluster admin to prevent sub-admins from breaking their cluster seems a compelling use case

I do not think I follow how this is related to the current issue.

> Setting the policy on the webhook also prevents privilege-escalation-type DOS attacks where a malicious webhook admin (who otherwise has no access to VWH configs) adds resources that they know would bork the cluster, causing the ValidatingWebhookConfiguration to get modified to include those resources.
> ...
> it potentially closes the "escape hatch" built into validating webhooks
> ...
> dynamically configuring the webhook config makes it harder to reason about the state of enforcement if the webhook itself is also dynamically configurable

You could make it "static" and updated via a script if you really wanted more explicit control.

**Comment by maxsmythe** [comment]
> > I guess the downside is that there would be a window of opportunity when a new CRD is added and the proposed controller detects it and updates the webhook configuration where policies that would otherwise have been applied were ignored
> 
> Just wait until the webhook is updated before granting authorization access? The webhook itself could enforce that if authorization is done via RBAC. You can also use a CLI based webhook authorizer to lock this down.
> 
> > allowing the cluster admin to prevent sub-admins from breaking their cluster seems a compelling use case
> 
> I do not think I follow how this is related to the current issue.

In your first post you mentioned that dynamically updating the webhooks would be a better user experience because the user would only have to manage one thing. I was contending that having two control levers with different levels of privilege is a feature, as it allows for organizations to scale operations via specialization and delegation. Such delegation is not currently possible if a root admin wants to say "manage everything except this resource", as the VWH config does not allow admins to express that intent. 

> 
> > Setting the policy on the webhook also prevents privilege-escalation-type DOS attacks where a malicious webhook admin (who otherwise has no access to VWH configs) adds resources that they know would bork the cluster, causing the ValidatingWebhookConfiguration to get modified to include those resources.
> > ...
> > it potentially closes the "escape hatch" built into validating webhooks
> > ...
> > dynamically configuring the webhook config makes it harder to reason about the state of enforcement if the webhook itself is also dynamically configurable
> 
> You could make it "static" and updated via a script if you really wanted more explicit control.

I agree with you on making it static. We think adding this feature would be helpful in allowing us to do so. Updating via script breaks Kubernetes' declarative model and introduces unnecessary latency.

Is there any reason not to add this feature? Increasing the expressiveness in configuring how webhooks are applied seems like a net gain to me.

**Comment by enj** [comment]
> Such delegation is not currently possible if a root admin wants to say "manage everything except this resource", as the VWH config does not allow admins to express that intent.
> ...
> I agree with you on making it static.

I would argue that it is possible.  The OPA webhook managing controller that I mentioned earlier could be configured with the static negative list (which it would then generate the static positive list from using discovery information) in a way that is only accessible to the root admin and not the policy admin.

> Is there any reason not to add this feature? Increasing the expressiveness in configuring how webhooks are applied seems like a net gain to me.

I think it is too niche of a feature that only applies to policy enforcing webhooks like OPA (most webhooks are bound to a set of resources).  Thus I believe the burden for the feature should rest on the policy webhook itself instead of core Kubernetes.  Since building the negative list is relatively trivial, I do not see why OPA cannot simply provide this functionality.

**Comment by lavalamp** [comment]
In general, relying only on front door enforcement and not having a reconciliation plan is not a safe strategy in a distributed system. A common way of making it kind of work anyway is to just report back to the user when their constraint is in place. So, there's already necessarily a delay between "policy is added" and "policy is loaded by all necessary policy enforcers". Adding a script to add or update a new webhook configuration object increases that delay but it doesn't cause a delay to exist where none previously did.

So, I think it is possible to build a controller which compiles a tightly scoped webhook configuration based on the policies that need to be enforced. Call this option "dynamically compiled configuration" DCC.

Now, compare to a hypothetical "negative-preference configuration," NPC.

* DCC has better overall runtime performance, as it means the cost of policy enforcement scales with the number of policies, and not with the number of types in the system. For some systems this will be a huge difference.
* NPC is less work for the policy system developers, for sure.
* But NPC would be a fair amount of work for the api machinery SIG.
* DCC lets you detect whether the webhook is installed correctly without much additional work; for NPC, you'd need to build an entire controller just to watch this. I think it's very important for your system to be aware of this as you can't enforce policy on objects not being sent to your webhook.
* NPC has fewer moving pieces to break.
* NPC means the lag from adding a policy to it being enforced will be a little shorter. But honestly not much.
* Your system has (perhaps not conveniently) available to it a positively specified list of configuration targets already. DCC would express this naturally.

Overall I think DCC is safer anyway, as it means an admin can't accidentally break your policy by excluding things in the webhook configuration layer.

I agree it'll be possible with DCC to make a policy that auto-breaks the cluster whenever the DCC controller can talk to apiserver. I kind of think that you should treat this as intended behavior. If the policy says that the cluster should be broken, then the cluster should break, given the approach of relying on stopping bad things at the front door.

I think you should consider having a policy canary feature that makes a webhook configuration with the "ignore" failure type. Once there's no policy violations for long enough it should be safe to then register with the "fail" type (?). The alternative is probably documenting that policy authors MUST test their policy in a duplicate cluster, but that will certainly not be followed completely and will therefore lead to broken clusters.

One final consideration:
* If we implemented NPC in 1.20 (already too late for 1.19), it'd likely be a year after that before it was universal enough (upgrade lag) for you to rely on it.

**Comment by caesarxuchao** [comment]
Can you use the [ObjectSelector](https://github.com/kubernetes/kubernetes/blob/0a1e58913c5f9cbfe0fe46d11d48e6968b7ce11d/staging/src/k8s.io/api/admissionregistration/v1/types.go#L274) to exclude the system-critical resources? Though note that:
https://github.com/kubernetes/kubernetes/blob/0a1e58913c5f9cbfe0fe46d11d48e6968b7ce11d/staging/src/k8s.io/api/admissionregistration/v1/types.go#L270-L271

Maybe you can add another validating webhook to only allow certain users to set the escaping labels.

**Comment by patrick-east** [comment]
Thanks for all the input @maxsmythe, @lavalamp and @enj ! This is good stuff 👍 

Couple of questions to clarify my understanding:

> I think it is too niche of a feature that only applies to policy enforcing webhooks like OPA (most webhooks are bound to a set of resources).

Can you elaborate on that? I was under the impression that things like image scanner integrations, security checks, etc etc were pretty widely spread. Most of those fall into this policy enforcing webhook bucket that setup wide selectors.

> DCC has better overall runtime performance, as it means the cost of policy enforcement scales with the number of policies, and not with the number of types in the system. For some systems this will be a huge difference.

Can you elaborate more on this point? I'm not sure I follow. The implementation of something like an "excludedResources" (for sake of debate) in the webhook code requires some additional complexity yes, but more than running another controller that is doing a watch on the API server, reconciling the delta between the available objects and currently configured webhook, and sending API requests to update the webhook? I feel like I'm misunderstanding something in this picture.

> But NPC would be a fair amount of work for the api machinery SIG.

Hopefully just review work.. I think there are folks willing to drive this implementation (myself included).

> DCC lets you detect whether the webhook is installed correctly without much additional work; for NPC, you'd need to build an entire controller just to watch this. I think it's very important for your system to be aware of this as you can't enforce policy on objects not being sent to your webhook.

For this type of feature you need a separate controller watching the webhook either way, right? It doesn't seem like much of "pro" in either DCC or NPC.

> Your system has (perhaps not conveniently) available to it a positively specified list of configuration targets already. DCC would express this naturally.

Can you elaborate more on this? I'm not sure I understand what you mean. Some implementations like Gatekeeper do have specifics about types that they apply to, but for other ones like kube-mgmt or ones that aren't OPA based I'm not sure this holds true.

> Overall I think DCC is safer anyway, as it means an admin can't accidentally break your policy by excluding things in the webhook configuration layer.

My understanding is that these types of configuration blacklists would need to be configured by the cluster admin, whereas the policies may be delegated to say a namespace admin. So I guess it changes _where_ the breakage happens but it seems like its just moving the issue around. Am I missing something there?

@caesarxuchao re:
> Can you use the ObjectSelector to exclude the system-critical resources? 

I haven't looked too deeply into that, although it does seem like it might be useful if all the excluded objects can have the labels set on them. I admit I'm not sure how well this would work if there are objects being managed automatically by custom resource controllers. I would want to think there was a way to get labels onto all the sub-resources but that isn't a guarentee, right?

> If we implemented NPC in 1.20 (already too late for 1.19), it'd likely be a year after that before it was universal enough (upgrade lag) for you to rely on it.

Right, I think that is generally understood.

**Comment by caesarxuchao** [comment]
>  I would want to think there was a way to get labels onto all the sub-resources but that isn't a guarentee, right?

What do you mean by sub-resources in this case? Can you make an example?

**Comment by patrick-east** [comment]
> What do you mean by sub-resources in this case? Can you make an example?

Correct me if I'm wrong, but in theory if I go off and create my own CRD, say its a "blog" object that under the hood will generate deployment(s), service(s), PVC(s), etc. I don't have to expose any sort of template to the end-user to allow them to inject their own labels onto the things the "blog" controller creates automatically. Say I go look at https://operatorhub.io/, what I don't have a good idea on is how many of those are going to be nice and allow you to put custom labels on _everything_ they might manage. If someone knows more about this please chime in 😄 

To clarify, I'm not saying this is a blocking issue either. It might even solve the issue for the original calico use-case I brought up. Just wanted to pull on the thread a little more to see how well it can be applied more generally compared to the other options being discussed.

**Comment by tallclair** [comment]
This is going to apply generally to any admission webhooks that need to operate on ObjectMetadata across resource types. In the case of GateKeeper, as soon as you specify any label constraints (e.g. "objects must have a `who-do-i-notify` label set"), which I expect to be fairly common, you lose any performance benefits to DCC.

Also, while it may be acceptable to have a window of inconsistent policy enforcement after a policy is updated (i.e. eventually consistent policy), I'm not sure the same is acceptable when a new CRD is added.

Finally, we should consider how this would interact with [statically configured webhooks](https://github.com/kubernetes/enhancements/pull/1712). Unless we implement "dynamically-updated statically-configured" webhooks, DCC seems infeasible for static webhooks.

**Comment by fedebongio** [comment]
/assign @lavalamp @caesarxuchao 
wondering if we can discuss this one in the bi-weekly meeting?

**Comment by lavalamp** [comment]
Yes, this would be a good SIG meeting topic, but tomorrow's meeting might
be too short notice.

**Comment by deads2k** [comment]
Reading this made me think of initializers again.  For namespaces, we have use-cases where we would like to allow third party controllers to add resources to a namespace before "normal" content could be created in it.  Things like quota for instance.

The use-case for CRDs wanting admission seems similar.  If we had the concept of an initializer on a CRD, you could avoid gaps and have generic capability for any other resource that needed to be present before a CRD should be "on".

**Comment by lavalamp** [comment]
Hm, that wouldn't need to be exactly like an initializer in that there's no need to hide the resource from the rest of the system prior to it being installed, since the system already tolerates CRDs that aren't being run due to an error. It could be more like a gate, like the pod readiness gate or whatever. 

Another potential puzzle piece: I am thinking that maybe it'd be useful to let e.g. statically configured webhooks hook webhook configuration objects.

**Comment by lavalamp** [comment]
> In the case of GateKeeper, as soon as you specify any label constraints (e.g. "objects must have a who-do-i-notify label set"), which I expect to be fairly common, you lose any performance benefits to DCC.

Right, well, that policy is broken, you can't actually have a policy like that. It has to either except the problematic types or list the protected types. The alternative is to selectively not enforce the policy, at the system administrator's discretion. I think if I were using a system like this I'd want the property that all the policies in the system are enforced exactly as written. Even if that occasionally breaks me when I write the wrong thing.

**Comment by patrick-east** [comment]
> Right, well, that policy is broken, you can't actually have a policy like that. It has to either except the problematic types or list the protected types.

But if the webhook can't be called (original scenario being some network issue) then it doesn't really matter what the policy or webhook implementation does. The behavior to skip certain objects has to be on the api server side.

> The alternative is to selectively not enforce the policy, at the system administrator's discretion.

Yes, and I think this is a good summary of what is being proposed. It's a mechanism to allow the system administrator to do just that.

> I think if I were using a system like this I'd want the property that all the policies in the system are enforced exactly as written. Even if that occasionally breaks me when I write the wrong thing.

Agree, although it is unclear how possible that is. It seems like due to the integration point via webhook some of the policy resides in the webhook configuration and some in the policy that is being applied in the webhook implementation. While it may be possible to infer (or explicitly define) the webhook configuration from the policy I'm not sure it applies to _all_ webhook implementations. I'm biased being an OPA maintainer, but I do want to ensure that we can come to some solution that would support other webhook implementations too.

**Comment by maxsmythe** [comment]
Excellent points all, I agree a meeting would be good as there is a lot of data bandwidth in this discussion.

A few counter-points:

> DCC lets you detect whether the webhook is installed correctly without much additional work; for NPC, you'd need to build an entire controller just to watch this. I think it's very important for your system to be aware of this as you can't enforce policy on objects not being sent to your webhook.

I think "installed correctly" is a matter of perspective here. In cases where there is a root system admin placed above the policy admin, they would need the ability to scope webhooks such that they don't interfere with cluster ops. NPC is better for validating scope limitations.

> Overall I think DCC is safer anyway, as it means an admin can't accidentally break your policy by excluding things in the webhook configuration layer.

"safer" is also a matter of perspective. A policy author probably does want as wide an enforcement scope as possible, however a sysadmin may know that calling webhooks on certain objects is too dangerous for the availability of the cluster and detection + manual remediation are the safest course.

> Your system has (perhaps not conveniently) available to it a positively specified list of configuration targets already. DCC would express this naturally.

This is not necessarily true. It is certainly possible to write a policy that applies to all resources. Any restriction on metadata for example.

> I think you should consider having a policy canary feature that makes a webhook configuration with the "ignore" failure type.

This is a good idea generally speaking. I don''t think it completely solves the issue, as a well-functioning policy could still be subject to transient errors such as webhook downtime, or changes to the system after policy installation, such as installing Istio.

> If we implemented NPC in 1.20 (already too late for 1.19), it'd likely be a year after that before it was universal enough (upgrade lag) for you to rely on it.

This is important to keep in mind, but the inverse of this logic is that if we delay adding this feature, its GA would be that much further out. I believe this is would be a generally useful feature. Even if kludgy workarounds are necessary in the short term, knowing there is a path forward is important.

> Can you use the ObjectSelector to exclude the system-critical resources? ...
> Maybe you can add another validating webhook to only allow certain users to set the escaping labels.

The problem here is that a second webhook would need to be added, so a webook would still be called against critical resources.

> Right, well, that policy is broken, you can't actually have a policy like that. It has to either except the problematic types or list the protected types. The alternative is to selectively not enforce the policy, at the system administrator's discretion.

Temporarily setting aside delegation and whether policies should be universally enforced, there is still the problem that any calling of a webhook whatsoever can be dangerous to cluster availability for certain resources that core cluster functionality relies on.

Bringing back the delegation consideration... you are assuming that authors of policies are experts in K8s clusters and know which resources may be problematic to enforce policy on via webhook. In a specialized work environment where policies are set by compliance teams, that may not be the case. Defining a safe set of resources where compliance teams do not need to worry about breaking the cluster allows them to be more responsive to new risks and compliance requirements as they do not need to coordinate across departments.

In those cases where policy authors still want compliance checks on resources where active enforcement would be too dangerous... this is where a reconciliation plan is necessary, usually consisting of regular audits.

*END REPLIES*

One thing I haven't heard an adequate alternative for is making sure the escape hatch of deleting the webhook config object is preserved. There was one suggestion of manually triggering reconciles, but this breaks the declarative model as it makes the user responsible for actuation.

I would also like to signal boost @tallclair's point about statically configured webhooks.

**Comment by enj** [comment]
> Unless we implement "dynamically-updated statically-configured" webhooks, DCC seems infeasible for static webhooks.

I would expect statically configured webhooks to still reload their config like we do for CA bundles.

**Comment by tallclair** [comment]
> I would expect statically configured webhooks to still reload their config like we do for CA bundles.

Relevant discussion: https://github.com/kubernetes/enhancements/pull/1712#discussion_r417485497

**Comment by deads2k** [comment]
> Hm, that wouldn't need to be exactly like an initializer in that there's no need to hide the resource from the rest of the system prior to it being installed, since the system already tolerates CRDs that aren't being run due to an error. It could be more like a gate, like the pod readiness gate or whatever.

Yes, similar.  A spec field could indicate that additional .status.conditions are required before serving  the CRD.  This would allow for reaction for admission webhooks or any other awesome thing needed.

**Comment by lavalamp** [comment]
I had a chat with @maxsmythe and @tallclair about this and I had another idea.

The theory is that a webhook author really does want their policy enforced. But for some operations, it's more important that the cluster not burst into flames. And the webhook author might not know which operations those are for the cluster.

So, the idea is, instead of making every webhook separately exclude some operations, what if we made a global critical-operation constraint that listed specific types and operations, and listed the maximum timeout?

So, now, when calling a webhook, we match the {type, operation} with both the webhook configurations and the critical-operation constraint. If it matches the latter, when we call the webhook we use the Ignore failure policy and the listed max timeout. Otherwise, we use the webhook's desired values. If this causes us to ignore a webhook, we can e.g. write an audit log about it.

This separation would permit people who know what's performance sensitive in the cluster to write down a sensible critical-operation constraint, and free webhook authors from having to know this (which is good, because it could be different in different clusters).

Of course, webhook authors will have to deal with getting "Ignore" when they asked for "fail" sometimes. I think this is acceptable, because they should already have a post-facto reconciliation mechanism (gatekeeper does). If a webhook can't deal with this, then the cluster that wants to run the webhook shouldn't use the critical-operation constraint feature, and that's fine--some people probably do want their cluster to burst into flames rather than admit a policy-violating object even for a millisecond.

**Comment by lavalamp** [comment]
I think, fundamentally, this exposes a very direct conflict between availability and security. Right now, we accidentally require a great deal of coupling between webhook config author and cluster administrator, which are fairly different roles. A second problem is that we can only choose from two modes, "everything is great" and "fail this request (and the entire chain of things that depend on this request succeeding)". So, I don't know if the exact thing I said in the prior comment is the right answer, but I think a good solution should have these properties:

* Separation of responsibility: "what does the webhook want to intercept" should have a different author than "for what request failures am I willing to break my cluster".
* Gradual failure: There should be at least one and ideally several failure levels before the cluster becomes completely unusable, we shouldn't force people to make a binary choice here.

(Note that some people probably do want their cluster to hard-stop rather than evade a policy and we shouldn't prevent them from configuring the cluster that way; we just want the option for it to not be like that.)

We have a complication in that when we reject a request, there's currently no way to know whether that's part of a chain of requests (e.g. is re-entrant from a webhook or one step of a sequence from a controller). There is no easy fix for this either, as request chains can be arbitrarily nested and dislocated (e.g., for object X, controller A starts controller B starts pod C starts container D makes object Y which starts controller A2 ...).

**Comment by lavalamp** [comment]
Here's an observation: when a "Fail" webhook is breaking the cluster overall, there must be some sort of cycle that is preventing recovery, and at least one of the N requests it is failing are part of that cycle.

So a very stupid way of fixing this is to make the webhook author provide a way of listing the components that implement the webhook, e.g. by a tuple of (namespace, API Group/Kind, name-prefix and/or label selector). Then, if the webhook is failing a lot (e.g. at least one failure and no successes in the past 30s), go into ignore mode *just for objects matching the list* (and also, there should be a metric or something for admins to alert on when this happens, and audit logs, etc).

Authors can test their list by installing the webhook config *first* and then adding config for its deployments/pods/etc.

Policy/security folks will want an "unspoofable" sense of identity so you can't rename your workload to evade a webhook. This solution would rely on locking people who would do such a thing out of the relevant namespaces via e.g. RBAC.

I guess this sounds very much like the exclude list asked for in the OP :) I would say, what I'm thinking of differs from a generic exclude list in these ways:
* Framing: "exclude things, if you want to" vs "list your components"
* Provides an additional behavior, it's not just {exclude, include} x {ignore, fail} behaviors, now there'd be a {include and fail, unless the webhook seems broken, then ignore} behavior.

But maybe that's not an important difference. Maybe the most expedient thing to do is to add an exclusion rule list and document a strong recommendation to list your components, and test your list in an empty cluster.

A flaw in this system is that the author might list too many exclusions (e.g., keeping something from an earlier version), or have an exclusion that covers too many things, and I'm not sure how to help them detect that. Maybe we could keep a metric on exclusions, and the author can verify that it remains zero when they install just the webhook config in a cluster. (But this breaks the cluster, so it's an invasive test.)

**Comment by maxsmythe** [comment]
Another issue with the idea of trying to detect dependency cycles is that it's turtles all the way down, as dependencies may have dependencies, and those ancillary dependencies may vary based off cluster version.

For instance, I'm guessing many webhooks depend either directly or indirectly on kube-controller-manager, which depends on leader election, which means they have a transitive dependency on leader-election resources.

Another issue is that in a scenario where the user values availability over immediate enforcement of all policies, it's not necessarily that we are worried about preventing the webhook from breaking itself, we're concerned about the webhook breaking normal cluster operation.

**Comment by lavalamp** [comment]
Yeah that's a good point, in a cluster that's e.g. self-hosting controller manager, probably nearly all webhooks would want to exclude that, but how could a webhook author know a cluster is going to be set up like that?

I think that argues for the need for a global exclude list of some sort.

Alternatively, what if we added exclude lists to webhook configuration, but then *pooled* those, in memory, into a single global exclude list that is used for all webhooks? This doesn't add any new resource types to the system, and you can make a webhook configuration object that doesn't hook any resources just to add something to the global exclude list, if you want.

I'm not sure if every entry in the exclude list needs to be excluded for every webhook, so maybe items could be listed as exported (exclude for every webhook) or not (exclude only for the current webhook).

**Comment by maxsmythe** [comment]
The ability to have webhook-specific excludes definitely seems useful to me. It's more flexible, so we are at less risk of issues if our assumptions on how people use webhooks don't align with reality.

It would also allow for webhooks that are strictly run off-cluster to have broader enforcement capabilities.

One security risk of allowing multiple webhook resources to interact is that if users rely on resource-name-based RBAC, a malicious user could take advantage of the pooling behavior to disable webhooks they technically don't have access to.

**Comment by yiqigao217** [comment]
+1 We ([HNC](https://github.com/kubernetes-sigs/multi-tenancy/tree/master/incubator/hnc)) have the similar issue.

We have a fail-close webhook configuraiton on all objects except those in namespaces labeled as [excluded](https://github.com/kubernetes-sigs/multi-tenancy/blob/master/incubator/hnc/docs/user-guide/concepts.md#hncx-k8sioexcluded-namespace-label-on-namespaces). If `kube-system` namespace is not labeled, when the HNC pod is in a bad state (not `Running`), the VWH would block everything in `kube-system`, thus breaking the entire cluster.

It would be nice if we can exclude specific namespaces in VWHConfiguration directly without using labelSelector.

**Comment by liggitt** [comment]
as of 1.21, namespaces have a default `kubernetes.io/metadata.name` label on them matching their name.

if you want to exclude specifically named namespaces in addition to namespaces with your excluded-namespace label, in 1.21+ you can do this:

```yaml
  namespaceSelector:
    matchExpressions:
    - key: hnc.x-k8s.io/excluded-namespace
      operator: DoesNotExist
    - key: kubernetes.io/metadata.name
      operator: NotIn
      values:
      - kube-system
      - kube-public
      - hnc-system
      - kube-node-lease
```

**Comment by yiqigao217** [comment]
Wow this is really cool! Yes, default labels on all namespaces could also make it work for us! Thank you for the info @liggitt !

**Comment by maxsmythe** [comment]
Making namespace names available as a label helps diligent users address known problems, but we're still left with the core issue cited in this comment:

https://github.com/kubernetes/kubernetes/issues/92157#issuecomment-655096749

**Comment by maxsmythe** [comment]
To be clear, @liggit's answer addresses @yiqigao217's concern, mainly I wanted to keep focus on the core issue.

**Comment by dims** [comment]
`eks-distro` is carrying a patch for this:
- https://github.com/aws/eks-distro/blob/main/projects/kubernetes/kubernetes/1-24/patches/0002-EKS-PATCH-Bypassed-admission-controller-webhook-for-.patch

Also see additional context - https://github.com/kubernetes/kubernetes/issues/113088

**Comment by liggitt** [comment]
breadcrumbs to other places admission / control-plane health cycles got discussed:
* https://github.com/kubernetes/kubernetes/issues/54522
* https://github.com/kubernetes/kubernetes/pull/65477
* https://github.com/kubernetes/kubernetes/issues/56761
* https://github.com/kubernetes/kubernetes/pull/59073
* https://discuss.kubernetes.io/t/to-to-manage-broken-webhooks-during-cluster-upgrade/19273
* [2022-03-09 api-machinery meeting](https://docs.google.com/document/d/1x9RNaaysyO0gXHIr1y50QFbiL1x8OWnk2v3XnrdkT5Y/edit#bookmark=id.rsko6dbvhb7v)

**Comment by tallclair** [comment]
/assign

I'd like to help drive this forward for v1.27. I'll get started on a KEP.

/milestone v1.27

**Comment by sowmyav27** [comment]
@tallclair Hi, I am part of Bug Triage Shadow team for k8s 1.27 release. I wanted to confirm this is on track for 1.27 ?

**Comment by tallclair** [comment]
Yes, still on track. @ivelichkovich is driving the implementation.

**Comment by tallclair** [comment]
To clarify - this is being addressed by the Match Conditions feature: https://github.com/kubernetes/enhancements/issues/3716

I think we can close this, and just track the enhancement instead.
