### ISSUE TITLE
Scheduler should care toleration seconds

### ISSUE THREAD

**Issue by zhouya0** [kubernetes/kubernetes#92170]
**What would you like to be added**:
Scheduler `TaintToleration` plugin should ignore those tolerations with `tolerations seconds`.

**Why is this needed**:
`toleration seconds` should be used  in case like: 
- "Pod can continue to run on this node for a period of time before eviction since the node has a new taint now".

But not the case like:
- "Pod can be scheduled to this node which has a taint even the pod will be evicted after a period of time".

I don' know if I made myself clear, if not, here's an example:
if we have a deployment whose pod spec has:
```
tolerations:
  - effect: NoExecute
    key: foo 
   operator: Exists
    tolerationSeconds: 30
```
And now we have a node like:
```
taints:
- effect: NoExecute
   key: foo
```

And now the scheduler will continue to schedule the pod to the node because this node will evict this pod 30s later.
And you can see following events:
```
NAME                                READY   STATUS              RESTARTS   AGE
nginx-deployment-578c4b864c-q8r27   0/1     ContainerCreating   0          7s
nginx-deployment-578c4b864c-rtfjd   0/1     ContainerCreating   0          7s
nginx-deployment-578c4b864c-q8r27   1/1     Running             0          8s
nginx-deployment-578c4b864c-rtfjd   1/1     Running             0          10s
nginx-deployment-578c4b864c-q8r27   1/1     Terminating         0          30s
nginx-deployment-578c4b864c-rtfjd   1/1     Terminating         0          30s
nginx-deployment-578c4b864c-gplms   0/1     Pending             0          0s
nginx-deployment-578c4b864c-gplms   0/1     Pending             0          0s
nginx-deployment-578c4b864c-ntjft   0/1     Pending             0          0s
nginx-deployment-578c4b864c-ntjft   0/1     Pending             0          0s
nginx-deployment-578c4b864c-gplms   0/1     ContainerCreating   0          0s
nginx-deployment-578c4b864c-gplms   0/1     ContainerCreating   0          1s
nginx-deployment-578c4b864c-rtfjd   0/1     Terminating         0          31s
nginx-deployment-578c4b864c-q8r27   0/1     Terminating         0          31s
nginx-deployment-578c4b864c-q8r27   0/1     Terminating         0          32s
nginx-deployment-578c4b864c-q8r27   0/1     Terminating         0          32s
nginx-deployment-578c4b864c-rtfjd   0/1     Terminating         0          32s
nginx-deployment-578c4b864c-rtfjd   0/1     Terminating         0          32s
nginx-deployment-578c4b864c-ntjft   0/1     Pending             0          2s
nginx-deployment-578c4b864c-ntjft   0/1     ContainerCreating   0          2s
nginx-deployment-578c4b864c-ntjft   0/1     ContainerCreating   0          3s
nginx-deployment-578c4b864c-gplms   1/1     Running             0          3s
nginx-deployment-578c4b864c-ntjft   1/1     Running             0          7s
nginx-deployment-578c4b864c-gplms   1/1     Terminating         0          30s
nginx-deployment-578c4b864c-tc48l   0/1     Pending             0          0s
nginx-deployment-578c4b864c-tc48l   0/1     Pending             0          0s
```
/sig scheduling
/assign

**Comment by skilxn-go** [comment]
![image](https://user-images.githubusercontent.com/8231208/84852867-7ac91880-b090-11ea-9094-128100624229.png)
I think the behavior, in this case, is defined clearly.

**Comment by alculquicondor** [comment]
/kind bug

https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/#concepts

```
if there is at least one un-ignored taint with effect NoExecute then the pod will be evicted from the node (if it is already running on the node), and will not be scheduled onto the node (if it is not yet running on the node).```

**Comment by alculquicondor** [comment]
/sig node

@damemi you are the owner of the feature. Any comments?

**Comment by damemi** [comment]
@alculquicondor sorry, meant to comment on this the other day but got distracted.

I'm not sure this is a bug, because ignoring tolerations with tolerationSeconds set seems to go against the purpose of tolerations. In the docs you quoted,

> if there is at least one un-ignored taint with effect NoExecute then the pod will be evicted from the node (if it is already running on the node), and will not be scheduled onto the node (if it is not yet running on the node).

But if we have a tolerationSeconds set, the taint is not un-ignored just because there is a timer on when it is no longer tolerated. I think the current behavior is still in-line with the docs.

Preventing scheduling in this case might make sense for relatively small tolerationSeconds that cause these eviction loops, but what about larger cases, like `3600`? Maybe the user wants to attempt to schedule a diagnostic pod on a tainted node. 

imo, when a taint is tolerated that toleration should be respected (even if it's only being tolerated for a limited amount of time). If there are cases where taints are being applied to nodes with `NoExecute` that no pod should ever be scheduled to, perhaps they should also be applied with a matching `NoSchedule` taint.

I think this change would be an added restriction to `tolerationSeconds` functionality, making it apply only to currently scheduled pods, a behavior which isn't clearly implied in the docs that I could find. I'm not against it, but if we look at it from that perspective is that how it should be used?

**Comment by alculquicondor** [comment]
I actually misunderstood the issue at the beginning. I agree that this is a gray area that is not properly defined.

Perhaps the toleration with `tolerationSeconds` should influence scoring, in a similar fashion to `PreferNoSchedule`. But that would be a new feature.

**Comment by damemi** [comment]
Currently, if a pod has a `tolerationSeconds` and is scheduled to a node with a matching taint, then that taint is removed from the node before the pod's `tolerationSeconds` is up, will the pod still be evicted? If not, this could also be a use case to continue supporting scheduling with tolerationSeconds because it's not guaranteed the pod will be evicted due to a taint that was present at scheduling.

**Comment by Huang-Wei** [comment]
IMO "NoExecute" more describes the **runtime** behavior, and it shouldn't behave like a "super-set" of "NoSchedule" no matter tolerationSeconds is set or not.

> // Evict any already-running pods that do not tolerate the taint.
> // Currently enforced by NodeController.
> TaintEffectNoExecute TaintEffect = "NoExecute"

In @zhouya0's case:

- If the node is added system-level taints (i.e., the node becomes unhealthy), Kubernetes (node lifecycle manager) is responsible of applying "NoExecute" taint, **as well as** "NoSchedule" taints. So the workloads, in most cases, won't be scheduled.
- If the node is tainted by system admin, I think a best practice is to apply **both "NoExecute" and "NoSchedule" taints**; otherwise, the workload may be scheduled and then evicted back and forth.

So I agree with @damemi, this is not a bug.

**Comment by pacoxu** [comment]
> I actually misunderstood the issue at the beginning. I agree that this is a gray area that is not properly defined.
> 
> Perhaps the toleration with `tolerationSeconds` should influence scoring, in a similar fashion to `PreferNoSchedule`. But that would be a new feature.

It should influence scoring, no matter tolerationSeconds is small or big. This behavior is not wrong, but not proper to fall into a loop(schedule - evict) util it is scheduled to a better node. 

1. As TaintBasedEvictions feature is enabled by default, this will influence most pods of a cluster.
2. According to https://github.com/kubernetes/kubernetes/issues/84298, too big tolerationSeconds is not best practice.

**Comment by damemi** [comment]
I think adding a score based on the tolerationSeconds is reasonable. Maybe an inverse of the tolerationSeconds set? eg, higher tolerationSeconds gives a higher score than lower tolerationSeconds. 

This would make sense because, like you said, a low tolerationSeconds is more likely to cause an eviction loop while a high tolerationSeconds is less likely to have any effect.

**Comment by zhouya0** [comment]
Agree, @damemi . I'll try to make another PR.

**Comment by ahg-g** [comment]
It is indeed not well defined in the docs, but if I were to implement this now, I would probably implement it such that ```tolerationSeconds``` is for running pods only, and that a pod shouldn't be scheduled on the node otherwise. 

However, I don't know if we can change the current behavior since it is a v1 api, and so we need to update the docs to clarify the scheduler's current behavior and recommend Wei's suggestion with regards to combining both "NoExecute" and "NoSchedule".

**Comment by zhouya0** [comment]
@ahg-g I totally agree with @Huang-Wei too. Adding a `NoSchedule` taint will solve the problem. Perhaps what we need to change is the improvement of the use documents of the `taint`.
Move `TolerationSeconds` to score plugin can also solve the problem but also changes the current behavior. So just now I'll close my PR and waiting for more evidence.
But open this issue to be discussed :)

**Comment by alculquicondor** [comment]
/remove-kind bug
/kind feature

Changing scoring is not so bad as long as it only affects workloads which use a specific API (such as this one).

But @Huang-Wei's suggestion (using a `NoSchedule` toleration as well) sounds like a good way for users to explicitly say if they are ok with their workloads being scheduled in a node where they will be eventually evicted.

In that case, we just update the docs.

**Comment by alculquicondor** [comment]
@zhouya0 could you send a PR to website to clarify this case?

**Comment by zhouya0** [comment]
> @zhouya0 could you send a PR to website to clarify this case?

Sure, I'll try to do that.

**Comment by alculquicondor** [comment]
/unassign @zhouya0

/help

See kubernetes/website#24041 for previous discussions
