### ISSUE TITLE
PD in-tree plugin: migrate to stable zone/region labels

### ISSUE THREAD

**Issue by verult** [kubernetes/kubernetes#92237]
**What would you like to be added**: The PD volume plugin is currently using beta zone/region labels. Stable labels have been introduced

**Why is this needed**: k8s is migrating to stable labels. I'm not sure what the timeline is - following up on that.

/sig storage
/sig gcp
/cc @lookuptable @misterikkit @msau42 @saad-ali

**Comment by msau42** [comment]
We intentionally didn't migrate to the stable labels and instead were going to use CSI migration to convert the beta labels to the csi labels because supporting GA labels would add extra complexity to csi migration. background: https://github.com/kubernetes/kubernetes/pull/81431

However CSI migration timeline is likely to slip. We need to work with sig cloud provider to iron out the timelines. cc @andrewsykim @cheftako

**Comment by msau42** [comment]
Currently volume provisioners will still provision new PVs with beta labels in the NodeAffinity. At the time of implementation, we didn't want to change to v1 because not all nodes had v1 labels and it would add complexity to the csi migration translation layer to parse a nodeaffinity that had a (v1 or v1beta) rule.

But now that we can expect all nodes to have v1 topology on them, I think the translation logic should be simpler now, and we could revisit this decision. I think it particular, the current behavior where migrated pvs get provisioned with intree spec but csi topology label could potentially cause rollback issues.

cc @mattcary

**Comment by msau42** [comment]
Sorry I realize there's still a problem with old PVs created only with beta labels. Without csi migration, they will fail to schedule if nodes are created without beta labels.

**Comment by msau42** [comment]
One idea suggested by @thockin is to allow mutation of PV.NodeAffinity if the only change is to convert the beta label to GA label.

General mutation can lead to irrecoverable races in the scheduler: https://github.com/kubernetes/kubernetes/issues/69528

**Comment by Jiawei0227** [comment]
Some digging process:

> We intentionally didn't migrate to the stable labels and instead were going to use CSI migration to convert the beta labels to the csi labels because supporting GA labels would add extra complexity to csi migration. background: #81431

To be specific, this comment: https://github.com/kubernetes/kubernetes/pull/81431#discussion_r341216734

So IIUC we decide not to import any GA topology labels for in-tree volumes. Instead doing it in the csi migration translation process. And ideally after the CSI migration GA, all in-tree volume will start to use GA version node affinity. So the beta label is not a concern anymore.

**Comment by msau42** [comment]
Yes, however, we may want to reconsider that decision, mainly due to user confusion. Users may see their PVs getting created with deprecated beta labels, try to modify the labels themselves, and the csi migration library doesn't properly translate it.
