### ISSUE TITLE
coreos/azure: login commands

### ISSUE THREAD

**Issue by errordeveloper** [kubernetes/kubernetes#9242]
@srakesh28 has suggested (https://github.com/GoogleCloudPlatform/kubernetes/pull/9060#issuecomment-108642690) that it may be necessary to add the following commands:

```
azure account import 
azure account set <"name of your subscription">
```

**Comment by srakesh28** [comment]
azure login did not work for me, I provided my azure subscription user id and password and below is error I get 
info: Executing command login
warn: Please note that currently you can login only via Microsoft organizational account or service principal. For instructions on how to set them up, please read http://aka.ms/Dhf67j.
Password: ***********

Authenticating... error: Server returned error in RSTR - ErrorCode: NONE : FaultMessage: NONE info: Error information has been recorded to /home/xxxxxx/.azure/azure.err error: login command failed
so I tried out 
azure account import --> to download publish file go to https://manage.windowsazure.com/publishsettings (Login from browser and it will download it)

azure account set <"name of your subscription"> --> Name can be found in publishsetting files or from Portal
This worked to proceed to next steps.

**Comment by errordeveloper** [comment]
CC @squillace

**Comment by squillace** [comment]
@srakesh28 @errordeveloper `azure login` only works from a work or school id, which really means an AAD object (identity). If you have a Microsoft account, you can only "connect" with the `azure account import` command that takes a .publishsettings file that you have to download. (it's a cert file)

This is actually a feature of Azure, although I think we don't communicate well here. Turns out that everyone has a default Azure Active Directory domain that they get for free. 

At a larger level, Azure has two management APIs: 
1. Service management, which can be used with either work ids or Microsoft account ids, and 
2. Resource management, which is the new stuff and can be used only with work or school ids, and that works only with the `azure login` functionality. 

If you want to try it, and you have an Azure account that is personal (uses a Microsoft id to sign in), you can create a work id to use for yourself by following the [instructions here](https://azure.microsoft.com/en-us/documentation/articles/resource-group-create-work-id-from-personal/).

Alternatively, you can create a brand new Free Trial account directly with a work or school (organizational) account here, but for all new users, it's important to remember that there are very low default quotas to "free" accounts: only 4 cores, so the first thing you have to do is request more cores. That you should do by contacting support. The precise calls and requests you have to make are [here](https://azure.microsoft.com/en-us/documentation/articles/resource-group-deploy-debug/#authentication-subscription-role-and-quota-issues).

**Comment by srakesh28** [comment]
Got it great explanation.. this was not very clear at first, This helps. Thanks

**Comment by squillace** [comment]
@srakesh28 My pleasure. I believe that the kubernetes driver and other work for Azure was done with the V1 model, so using a publishettings OR AAD identity should work fine, but it will not use the resource management api to create the resources. I'll look into it.

**Comment by srakesh28** [comment]
Thank you resource management would be great

**Comment by errordeveloper** [comment]
@squillace thank you very much for this excellent explanation of what's going on, as it was a bit unclear and I actually assumed that CLI only works with organisational accounts... Anyhow, the issue here is really about what to do with [`azure-login.js`](https://github.com/errordeveloper/weave-demos/blob/da78a16a5ddc3b1b1ca8f48e5b570517f120138e/coreos-azure/azure-login.js) helper?

**Comment by errordeveloper** [comment]
The purpose of this helper scrip was to not have to ask user to install the package in system path and just use what's already in `node_modules`. Anyhow, sounds like writing an interactive login script that asks what kindda account the user has doesn't make too much sense to me, perhaps there should be just two scripts... although, I would debate whether CLI should wrap this somehow all under `login` subcommad, which is a natural thing to pick for user like myself who only reads usage summary and refrains from reading long docs indefinitely.

**Comment by Snesha** [comment]
@errordeveloper Since Azure doesn't have a scriptable login yet, I suggest sticking with the manual two step login. I'll update this issue once we've got a resolution.

**Comment by errordeveloper** [comment]
@Snesha have you had a chance to take a look at this?

**Comment by mwithrow** [comment]
Hello,
 New to kubernetes and node.js and trying to install in my Azure sub.  I am stuck at the azure-login.js.  It keeps erroring out no matter what parameter I pass?

**Comment by errordeveloper** [comment]
The code no longer lives here.
