### ISSUE TITLE
auth: request signing

### ISSUE THREAD

**Issue by enj** [kubernetes/kubernetes#92535]
Just writing down some thoughts from the [June 24th, 2020 sig-auth meeting](https://www.youtube.com/watch?v=Phco26zYEYs).

The kube API server supports generic authentication mechanisms via the aggregator front proxy (this proxy performs the actual authentication and then uses mTLS+headers to assert the desired identity to the API server).  As expected, this mechanism can be used to support Kerberos, request signing, SAML, etc.  The kubelet does not support this functionality today, but it would be easy to add this support to it since it uses the same code as the kube API server.

On the server side, we have a pretty reasonable story.  The only "small" enchantment I can think of here is that it would interesting if the `TokenReview` API supported passing in the request info attributes (i.e. same info as `authorizer.Attributes`) along with the token and audiences (any token based caching would need to take into account if these request attributes were used to authenticate a request).  This change would make it possible to have token based request signing (i.e. a client could create a bearer token by signing the request info, a timestamp, etc and a token review webhook would map that signature back to a `user.Info` along with validating that the request info matches).  There were some conversations back a little while ago about having a combined `TokenReview` and `SubjectAccessReview` API for use by the kubelet to do remote authn/z.  If such an API was implemented by a webhook in a single remote call, the endpoint could perform validation of the token while taking into account the SAR info.  This would effectively allow for request signing.

On the client side, we do not have a good story.  The `exec` credential plugin mechanism is not designed for this purpose.  In particular, client-go expects to cache the credential until it expires or the process exits (the API is designed around this).  The request information is not passed to the `exec` plugin.  Calling an external process per request also seems like a bad idea.  In general, it is impossible (today) to use the `exec` plugin mechanism in an attempt to support request signing.

It may be possible to use a client side proxy to support request signing (and other methods such as https://github.com/kubernetes/enhancements/pull/1749) with client-go.  The UX around such a proxy is likely to be problematic (the most obvious being lifetime management of the proxy and configuring the proxy to use the correct CA to validate the connection with the server).  Some kind of request offloading / proxy approach on the client side seems like the best long term approach as it handles all future needs instead of being limited to token/cert based auth.

/kind feature

@kubernetes/sig-auth-feature-requests @micahhausler

**Comment by enj** [comment]
cc @cjcullen

**Comment by cristiklein** [comment]
Thanks for the detailed write-up @enj 

I understand there are two concerns regarding the client-side request proxy:

1. **How to transmit configuration from kubeconfig to the proxy?** I think this can easily be addressed in the client-go to proxy API by making sure that relevant kubeconfig entries are transmitted. This can either be done with each request or as part of getting a connection UUID. I favor the former, since that makes the proxy "more" stateless and the amount of redundant data transmitted seems negligible for a local connection.

2. **How to manage the life-cycle of the proxy?** The `exec` plugin solves this problem by spawning an executable itself. The Kubernetes community seems to agree that this poses an unacceptable security risk to the user via "rogue" kubeconfigs and that no new plugins should take that approach. Therefore, life-cycle management needs to be external to client-go/kubectl. Besides being more secure, having the life-cycle of the proxy separated from kubectl gives the proxy more freedom in implementing request pooling, credentials caching, etc.

In the Linux world, `systemd` proposes a fairly accepted [socket activation mechanism](https://www.freedesktop.org/software/systemd/man/systemd.socket.html). In brief, the proxy would install an executable and a systemd unit. Systemd will listen on the UNIX socket and spawn the proxy whenever the first connection is made. Subsequent connections are handled directly by the proxy, which can also implement a custom shutdown policy (e.g., no connections left, timeout after n minutes, etc.). Using this mechanism would add a dependency on the proxy, but not on kubectl/client-go.

I heard that other platforms (Windows, Mac) have similar mechanisms, but I am unfamiliar with them. Nevertheless, in the absence of any fancy OS activation mechanism, the user always has the option of spawning the proxy themselves, albeit the UX is sub-optimal.

My 2 cents.

**Comment by micahhausler** [comment]
The other option not yet discussed would be to integrate message signing directly into the client. Currently AWS uses a form of request signing ([SigV4](https://docs.aws.amazon.com/general/latest/gr/signature-version-4.html)), but I don't think integrating a provider specific authentication mechanism is the right approach. 

There is an early [IETF draft](https://datatracker.ietf.org/doc/draft-ietf-httpbis-message-signatures/?include_text=1) in the works that doesn't have a definite timeline and there is still [much discussion](https://github.com/httpwg/http-extensions/issues?page=1&q=is%3Aissue+is%3Aopen+label%3Asignatures) about the spec. Would a finalized open spec for request signing be something we could eventually consider integrating into our client code? This would sidestep many of the concerns about a proxy, would be much lighter-weight in terms of performance, and wouldn't be tied to a specific provider's implementation.

**Comment by enj** [comment]
@cristiklein 

> I think this can easily be addressed in the client-go to proxy API by making sure that relevant kubeconfig entries are transmitted.

Sure, but it is unclear to me where sig-auth folks land on creating such an API.  My current estimate is that there seems to be a desire to use the existing API surface without any further additions.

> The Kubernetes community seems to agree that this poses an unacceptable security risk to the user via "rogue" kubeconfigs and that no new plugins should take that approach.

I would disagree with this statement strongly.  A minority of users have pointed out that there is some concern that running kubeconfigs from an untrusted source could cause harm.  But `exec` plugins remain the most robust and secure mechanism we have today.  They make a slight security trade-off to have excellent UX.  I imagine the bulk of users obtain kubeconfigs from a trusted source, so this remains a minor concern.  My primary concern with doing something like https://github.com/kubernetes/enhancements/pull/1749 via an exec mechanism is that env var+std in and std out+err do not seem to be an appropriate communication medium for such a protocol.

> Therefore, life-cycle management needs to be external to client-go/kubectl

To me this quickly approaches a DIY approach, at which point one could argue that the existing per cluster `proxy-url` support is sufficient.

> In the Linux world, systemd proposes a fairly accepted socket activation mechanism. In brief, the proxy would install an executable and a systemd unit.

How would one download a kubeconfig from a managed Kuberentes offering that would be configured to use this proxy?  We need a uniform UX across Windows, MacOS and Linux.

---

@micahhausler 

> Would a finalized open spec for request signing be something we could consider integrating into our client code?

While I would say an open spec is a requirement for direct inclusion in our code, I do not think it is a guarantee.  For example, if we directly include some standard request signing format in the client, I would expect us to include the server side portion directly in the API server as well.  Just as we support OIDC on the client, we have matching support on the server.  `exec` on the client side has matching support on the server via x509 and token webhook.  If both the client and server side could be implemented generically, and if identity could be generically carried through this mechanism, I could see this being an option.

The discussion around a client side proxy has some basis in the notion that it is currently not that great of a mechanism on the client, whereas we have strong support on the server side via the aggregator front proxy.  But I do not think we could realistically consider client side proxies without matching server side support.

**Comment by mikedanese** [comment]
IMO, giving users the ability to deploy consistent authentication systems and protocols across their infra is generally a good thing. The evidence this is awaiting is only "if we added support for this in kubectl exec auth, would someone actually use it?" If the answer is yes, feel free to bump the priority and send out a KEP.

**Comment by liggitt** [comment]
Following discussion in the December 9th and January 6th sig-auth meetings, rather than adding APIs around request signing, using a local authenticated proxy (kubectl -> local proxy -> apiserver) is preferred. This proxy could be configured globally via proxy envvars or per-cluster with the `proxy-url` field in a kubeconfig file. This would allow the proxy to sign requests, as well as do other desired transformations.

If there are gaps that would block doing this in a reasonable way (for example, supporting talking to a proxy over a unix domain socket), requests/proposals to address those specific gaps would be welcome.

/close
