### ISSUE TITLE
The pvc controller automatically add protection finalizer when there is only completed pod

### ISSUE THREAD

**Issue by FogDong** [kubernetes/kubernetes#92598]
**What happened**:
The pvc controller automatically add protection finalizer when there is only completed pod.
```
[root@k8s-master-1 /]$ kubectl  get pod | grep rpc
algorithm-4zqx4-rpc1-bv7rs-pod-4g54g                          0/1     Completed   0          64m
algorithm-4zqx4-rpc2-72c5z-pod-6zf7h                          0/1     Completed   0          64m
```
```
fog-nfs-pvc                                  Terminating   pvc-6f644f7b-b14e-11ea-b163-52540065f05e  
```
I looked at the  [souce code](https://github.com/kubernetes/kubernetes/blob/7942dca975b7be9386540df3c17e309c3cb2de60/pkg/controller/volume/pvcprotection/pvc_protection_controller.go#L277) and realized that the controller did not judge the pod status, is there any reason to still protect the pvc even if the relative pod is completed? 
I'd like to create my first PR to fix that.😊

**What you expected to happen**:
The pvc controller should add finalizer when there is only completed pod.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a pod with pvc, and let the pod complete
2. Delete the pvc.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.14.8
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): CentOS Linux
- Kernel (e.g. `uname -a`): x86_64 GNU/Linux
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by msau42** [comment]
A completed pod still has the volume mounted on the node and is not safe to delete. Only non-existence of the Pod object indicates that the volume has unmounted.

**Comment by jimmyjones2** [comment]
@msau42 Is this still correct? RWO volumes must be unmounted from the host once the pod is in Completed state, otherwise scheduling a new pod using the same volume on a different node would fail with a multi-attach error?

I've verified this behaviour with the EBS driver - as soon as the pod goes to Completed state the volume is unmounted from the host and can be used by a new pod on a different node.

My understanding is that PVC protection was to prevent data loss - but if all pods are Completed, how could deleting the PVC cause data loss?

My use case would be similar to the comment on https://github.com/kubernetes/kubernetes/pull/55824#issuecomment-501087893 - keeping Completed pods for logs, but not wanting to keep the PVC any more. This would be useful with Tekton PipelineRuns - delete the temporary build PVC once complete, but keep the logs.
