### ISSUE TITLE
E2E test: support longer test names

### ISSUE THREAD

**Issue by AndiLi99** [kubernetes/kubernetes#92622]
**What would you like to be added**:
Currently test names are formed by concatenating the ginkgo context's together. The testname is used to create a directory. This creates a limit on the length of the the testname, as most operating systems can only support a filename of up to 255 bytes. This concatenating is done by the logging library (I think)

A way to break up the long test names by ginkgo context.
**Why is this needed**:
This test (https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/92555/pull-kubernetes-e2e-gce-storage-snapshot/1277695556403073024/) failed on PR #92555 

Current workarounds are simple by shortening the test names. However this is not desirable if we wish to support more nesting of ginkgo contexts in order to reduce boilerplate testing code by sharing common setup. This is also not desirable because it limits the ability to communicate the intent of the .

**Comment by BenTheElder** [comment]
why are we using the testname to create a directory?
even if we do need to create a directory per test we should probably use something more unique. 
sometimes multiple storage test entries wind up with the same test name

**Comment by pohly** [comment]
I assume this is about the artifacts, for example `_sig-storage_CSI_Volumes_Driver_csi-hostpath_Testpattern_Dynamic_PV_block_volmode_allowExpansion_volume-expand_Verify_if_offline_PVC_expansion_works/` in https://gcsweb.k8s.io/gcs/kubernetes-jenkins/pr-logs/pull/91939/pull-kubernetes-e2e-kind/1277884307708317696/artifacts/?

The test name is guaranteed to be unique per test run. It was chosen because then developers can find the artifacts for a certain test. The alternative might be to split at component texts, see https://pkg.go.dev/github.com/onsi/ginkgo?tab=doc#GinkgoTestDescription

**Comment by pohly** [comment]
In this example, the directory might then become `sig-storage/CSI_Volumes/Driver_csi-hostpath_Testpattern_Dynamic_PV_block/volmode/allowExpansion/volume-expand/Verify_if_offline_PVC_expansion_works` (I'm guessing a bit what the component texts are - I'm not sure).

**Comment by pohly** [comment]
Oh, there's an old todo about doing exactly that. It wasn't possible at the time because gubernator couldn't handle deeply nested directories: https://github.com/kubernetes/kubernetes/blob/c5941e283fd7e37e953832d6743e7ea3b556ab7a/test/e2e/storage/testsuites/base.go#L585-L588

**Comment by AndiLi99** [comment]
Thank you all!
