### ISSUE TITLE
CSR API: cluster signing duration is not flexible and has unsafe defaulting

### ISSUE THREAD

**Issue by enj** [kubernetes/kubernetes#92678]
Kube controller manager supports a built-in set of controllers called `csrsigning`.  These implement the default `kubernetes.io/*` CSR signers and are commonly used (i.e. via `kubeadm`).  Currently all certificates signed from these controllers have a static lifetime configured via the `--cluster-signing-duration` flag:

https://github.com/kubernetes/kubernetes/blob/908847c01e9640ffce2ffda5acf88d92c48a5148/cmd/kube-controller-manager/app/options/csrsigningcontroller.go#L48

When unset, this flag defaults to one year:

https://github.com/kubernetes/kubernetes/blob/908847c01e9640ffce2ffda5acf88d92c48a5148/pkg/controller/certificates/signer/config/v1alpha1/defaults.go#L44

In the [Certificates KEP](https://github.com/kubernetes/enhancements/blob/master/keps/sig-auth/20190607-certificates-api.md), we state:

> Expiration/cert lifetime - minimum of CSR signer or request. Sanity of the time is the concern of the signer.

This is misleading because there is no `or request` functionality - it is simply the duration of the signer.  This also hints that the built-in signers could be configured individually, but we do not expose any per signer config, just a single `--cluster-signing-duration`.  However, per signer config would not be meaningful.  For example, `kubernetes.io/kube-apiserver-client` certs issued for `CN=foo` and `CN=bar` may not have identical duration requirements.

The type of certificate (client vs. serving) may also impact what duration is considered safe.  Long lived serving certs may be okay (they imply trust but not rights) but the same is not true for client certs (an identity against the Kube API that may have RBAC).

Certificates from the CSR API are unrevocable once issued  (this is extremely problematic for the `kubernetes.io/kube-apiserver-client` signer as these are valid as identities against the Kube API server).  The entire underlying certificate authority must be revoked if a single certificate needs revocation.  This is generally impractical and disruptive.  Issuing short lived certificates for all clients can help mitigate the problem, but not all clients are equal in regards to their capabilities to handle certificate rotation (and short durations are vulnerable to outages if the signing infrastructure is down).  Nor are all clients equivalent in how long they should be trusted (ex: a client whose private key is stored in a HSM can be issued a longer certificate).

The built-in CSR signing controllers should be safe to use.  Currently, if one wants to issue short lived certificates based on the client making the request, one must write a custom CSR signer.  This is an unreasonable burden for when one wants the exact semantics of the built-in signers with a custom certificate lifetime.

There are three actors:

1. The client requesting the CSR
1. The approver
1. The signer

We want to be able to use the built-in signers, so only the client and approver can "change."

Option 1: from the client's perspective, it could specify some form of `maxTTL` in the CSR `.spec` (and it would be immutable after creation like the rest of `.spec`).  This is a bit strange because the client is not supposed to be in control of the lifetime of the certificate in standard CSR flows (hence why the CSR format has no such field).  In terms of Kube's CSR API, this may be okay because a dynamic admission webhook could easily enforce that `.spec.maxTTL` is appropriate for the current client (along with the rest of the CSR `.spec` based on any arbitrary policy).  This would require one to write said dynamic webhook (or use something like OPA Gatekeeper) or otherwise intercept the client's request and mutate it before CSR creation.

Option 2: from the approver's perspective, they validate the CSR and if everything is valid, they approve it by setting `.status.conditions[Approved] = true`.  In many cases (i.e. for the `kubernetes.io/kube-apiserver-client` signer) the approver must either be a human actor or requires custom code.  Thus this seems like the most logical place to add an extra field such as `.status.maxTTL` which can only be set via the `certificatesigningrequests/approval` sub resource.  This changes approval from "dear signer, I approve this CSR, give the client a signed cert for some undefined period of time" to "dear signer, I approve this CSR, give the client a signed cert that is valid for at most this length of time."  In a sense, this removes the need for the signer to have any need for a certificate lifetime duration other than some concept of a default when the approver does not state an opinion.  A theoretical `v2` CSR API could require that `maxTTL` be set to prevent the need for any default.  Perhaps the KEP could be updated to:

> Expiration/cert lifetime - minimum of CSR signer _or request (really!)_. Sanity of the time is the concern of the _approver_.

In both API changes suggested above, enforcement of `maxTTL` could be handled by the API server when a certificate is set via the `certificatesigningrequests/status` sub resource.  Thus a new API server would prevent an old controller manager from signing a certificate for longer than the specified `maxTTL`.

@kubernetes/sig-auth-feature-requests 
/kind feature
/sig auth

cc @micahhausler

**Comment by neolit123** [comment]
i think supporting configurable expiration per request makes sense.

> These implement the default kubernetes.io/* CSR signers and are commonly used (i.e. via kubeadm).

today that is solely `kubernetes.io/kube-apiserver-client-kubelet` during TLS bootstrap. we also have a small user base for `kubernetes.io/kubelet-serving` (which seem related to gathering kubelet metrics mostly), but serving cert rotation is disabled by default as it requires extra work today.

slightly tangential and this will not contribute much to the CSR API topic, but i can give you the perspective of what types of users / feature requests i've seen WRT to the certificates that kubeadm manages - i.e. without using the KCM signers.

A) "what you have works for me".

this group is fine with the hardcoded default of 1 year for all kubeadm certificates.
kubeadm signs certificates on kubeadm cluster creation and rotates them on each immutable node upgrade, so as long as users upgrade at least once an year, they are good (and as long as the k8s release cycle is < 1 year)

B) "we want short lived certificates"

this group is usually corporate users that have customers request from them to rotate more often to address the potential issue of compromised long-lived certificates. with k8s not supporting revocation (via e.g. CRL or OSCP) my question for them is "what is a more secure default than one year?", if a certificate leaks and it was signed for one week, does that mean that they have to shutdown their cluster for one week or rotate the whole chain because they don't want the downtime. for api-server clients, i guess they can also block that user on RBAC level, unless the user is `admin` or `cluster-admin`.

C) "i want to sign my certificates and CA to last 100+ years"

this group usually runs their clusters isolated from the internet, e.g. on a programmable dishwasher or something like that and don't care about certificates at all. it's hard to make an argument with them, but we just say that we don't have a plan to make the expiration configurable due to the rest of the k8s use cases and because it's a bad practice.

---

for B and C we give them the option for kubeadm to generate CSRs (which is being reworked today), let the CA determine the expiration and then kubeadm can use a collection of certificates present in a folder instead of creating new ones or rotating them.

**Comment by enj** [comment]
> > These implement the default `kubernetes.io/*` CSR signers and are commonly used (i.e. via kubeadm).
> 
> today that is solely `kubernetes.io/kube-apiserver-client-kubelet` during TLS bootstrap. 

Sorry I should have been a bit more specific.  I meant that when `kubeadm` is used to spin up a cluster, it is generally common to use the built-in KCM signers with `kubeadm` managed PKI (i.e. those controllers are running).  What that means is that it is then possible to use the Kube CSR API to mint certs for `kubernetes.io/kube-apiserver-client` and similar, and that the lack of revocation combined with a one year default cert lifetime makes these dangerous to use in practice.  If instead the duration was exposed in some way via the REST API, it becomes much easier to enforce a dynamic policy around them (which could be as simple as "I do not recognize this actor so I will only give it a cert valid for one day so that it has to keep requesting new certs often and revocation is less of an issue").

> for api-server clients, i guess they can also block that user on RBAC level

If user `service1` loses access to one cert, you do not want to drop all RBAC for `service1` and force it to become `service2` though.  Also, groups are commonly used to manage permissions.  Dropping RBAC from the groups would be very painful for all actors.

**Comment by neolit123** [comment]
> I meant that when kubeadm is used to spin up a cluster, it is generally common to use the built-in KCM signers with kubeadm managed PKI (i.e. those controllers are running). What that means is that it is then possible to use the Kube CSR API to mint certs for kubernetes.io/kube-apiserver-client and similar

that is true.

kubeadm itself currently just creates these certificates without the KCM (which has _some_ potential for drift):
https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/phases/certs/certlist.go#L249-L278
we used to have alpha support for signing arbitrary certificates using the KCM, but we dropped that when the `signerName` change was introduced.

> If user service1 loses access to one cert, you do not want to drop all RBAC for service1 and force it to become service2 though. Also, groups are commonly used to manage permissions. Dropping RBAC from the groups would be very painful for all actors.

it can definitely be problematic.

**Comment by munnerz** [comment]
In cert-manager we have a `duration` field on our own CertificateRequest resource. Due to the fact that our equivalent of signers _may_ ignore this, we treat it as more of an advisory/request from the user rather than a hard-and-fast rule. Other parts of the project (i.e. automated renewal) exclusively use the NotBefore, NotAfter and our own `renewBefore` field (the amount of time before NotAfter that we begin attempting a renewal).

When we come to adopt the CSR API, we will be bringing across a similar concept either through a field or annotation (depending on the results of this discussion).

Therefore, I'd say it'd be preferable for us to allow some form of user configurable duration request (i.e. via `spec`), which is effectively option (1).

I think option (2), to specify a *maximum* TTL may be desirable too, although I think they could be two separate things. One being the user requested duration, and another being the actual maximum.

That said, the ultimate decision/policy comes down to the *signer* - when integration with certain external CAs, it can be difficult/impossible to accurately predict the true `maxTTL` - for that reason, I think separating this into 3 distinct concepts seems the most accurate way to represent this:

1. The *user requested* TTL, which is advisory and signers can choose to ignore it.
2. The *approver advised* maximum TTL, which it is strongly advised that a signer honours, although again not required (often these things are out of our control)
3. The *signer mandated* maximum TTL, which MAY take account of the user requested TTL and SHOULD take account of the approver advised maximum.

I certainly don't think we should provide any guarantees around what a client should expect the duration to be based on either a `spec` or `status` field on the CSR however, and doc comments should reflect that to avoid anyone expecting so.

Naturally, we already have (3). I do see an immediate value in adding (1) (it avoids cert-manager creating its own nomen-culture for this as well). Whilst (2) *sounds* very desirable as a means for an 'internal' process to influence signer decisions, it is not something we're currently looking at right now, as this sort of thing is typically configured in the signer (although it _would_ be interesting to be able to specify maximums on a per-CSR basis).

**Comment by munnerz** [comment]
Should we also update the KEP/documentation to state that users should not presume anything about the properties of the x509 certificate when a CSR is signed based on the `signerName`?

In cert-manager we certainly do not - we determine whether the current specification of our `Certificate` resource is 'up to date' for the most recent *CertificateRequest* solely by comparing the contents of that x509 CSR against the Certificate resource's specification. In the past we have tried to compare the signed x509 certificate against the Certificate resource's spec, which has led to all manner of issues (typically resulting in endless loops requesting new certificates).

**Comment by enj** [comment]
> I certainly don't think we should provide any guarantees around what a client should expect the duration

I think at a bare minimum that the API server could enforce through validation that the issued certificate has a lifetime no greater than the requested duration.

**Comment by liggitt** [comment]
> I think at a bare minimum that the API server could enforce through validation that the issued certificate has a lifetime no greater than the requested duration.

That wouldn't be backwards compatible.

A way to request a TTL in spec and a way to set a recommended TTL in status when approving both seem useful to me

**Comment by jpetazzo** [comment]
Is there actually a way to specify a "requested duration"? As far as I know, a CSR doesn't have a field for that. (I couldn't find it in [the overview of the spec](https://en.wikipedia.org/wiki/Certificate_signing_request#Structure) but perhaps it's using some non-standard extension field?) I also couldn't find a duration or TTL in the CertificateSigningRequest spec (on the k8s side). The Kubernetes docs mention in a few places "...when an expiration is different than the signer-determined expiration that is specified in the CSR", so I wonder if I'm missing something, or if I'm misunderstanding the docs, or something else?

**Comment by mikedanese** [comment]
> I also couldn't find a duration or TTL in the CertificateSigningRequest spec (on the k8s side).

Yes, this is the feature request. Desired TTL would likely be specified in field in CertificateSigningRequestSpec, not in the pkcs#10 CR body.

> The Kubernetes docs mention in a few places "...when an expiration is different than the signer-determined expiration that is specified in the CSR", so I wonder if I'm missing something, or if I'm misunderstanding the docs, or something else?

You can specify a TTL in an annotation today, and maybe some signer would respect it. None if the signers in core k/k do though yet.

**Comment by jpetazzo** [comment]
Thank you for your feedback!

I think the phrasing in the doc should be updated to clarify that while it's theoretically possible to set a TTL in the signing request, there is no standard (agreed-upon) way to do it; so it would probably be in an annotation, and while it's theoretically possible for a signer to use that TTL, there is currently no known implementation that does. I think this would save a lot of time to future readers desperately trying to figure out "how do I set the damn expiration time, dang it" ;-)

If what I said above is technically correct, would you like me to try and suggest a new wording?

**Comment by liggitt** [comment]
> I think the phrasing in the doc should be updated to clarify that while it's theoretically possible to set a TTL in the signing request, there is no standard (agreed-upon) way to do it; so it would probably be in an annotation, and while it's theoretically possible for a signer to use that TTL, there is currently no known implementation that does.

That's accurate
 
> If what I said above is technically correct, would you like me to try and suggest a new wording?

Yeah, a doc update to make the current state clearer would be welcome
