### ISSUE TITLE
Decide what to do with LegacyHostIP

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#9267]
Forked from #8087.

We intended to get rid of LegacyHostIP when we created the NodeAddresses field, but I don't think we have an adequate replacement yet, as we found when we tried to switch ResourceLocation to use an internal IP in #9155.

What we need to know is at least:
1. At which address/name the master/bastion can reach the node, for /proxy, /portforward, /redirect, kubectl exec, kubectl logs, etc.
2. Which address/name is in the node's cert. Ideally this is the same as the above.
3. At which address/name external load balancers can reach the node. 

InternalIP and ExternalIP don't tell us either of these. Only Openstack and AWS even set InternalIP. Openstack and AWS also set ExternalIP, as does GCE. 

LegacyHostIP is set in a variety of ways in different cloudprovider implementations. AWS sets LegacyHostIP to the InternalIP. In the case of Mesos, Ovirt, Vagrant, and Rackspace, they only set LegacyHostIP.

In the case of no cloudprovider, the --hostname-override flag in Kubelet sets LegacyHostIP.

In most of these cases, we don't know whether the LegacyHostIP is internal or external.

We could just rename LegacyHostIP to IPForMaster, ProxyIP, BastionIP, or something similar. InternalIP and ExternalIP would be optionally populated by the cloudprovider. Which address should be used by the external load balancer could be cloudprovider-specific, as it is now.

NodeHostName is defined, but neither set nor used, AFAICT.

I think this change can be made in a backward-compatible manner, so it doesn't absolutely have to be done for 1.0.

cc @krousey @cjcullen @dchen1107 @roberthbailey @ncdc

**Comment by karlkfi** [comment]
LegacyHostIP is the one most used with existing cloud providers. So it definitely needs to remain supported, at least until all the included cloud providers have been updated.

Ultimately, I would like to see the following concepts codified:
- `NodeHost` - IP (or hostname) & Port that the Node web server listens on (intra-node communication)
- `ClusterNodeHost` - IP (or hostname) & Port that the Node advertises to the cluster (inter-node/intra-cluster communication)
- `GlobalNodeHost` - IP (or hostname) & Port that the Node advertises to the world (extra-cluster/internet communication)

I would prefer not to differentiate between Hostname and IP, at least externally, because I want to retain flexibility to allow different cloud providers to use different networking topologies, including IP routes, DNS, and/or a proxy. 

I'm amenable with calling it "-Address" instead of "-Host", but I usually think of "-Address" as including the scheme component of the URI, whereas "-IP" excludes the port.

**Comment by wingedkiwi** [comment]
I cannot set up _SSL tunnels_ from master to the nodes for `kubectl exec` and `kubectl logs` calls. The `kube-apiserver` is looking for the `NodeExternalIP` and fails as I don't use a cloud provider and thus only have a `NodeLegacyHostIP`.

Additionally there is no way to provide external ip and internal ip information when a kubelet registers itself without a cloud provider. Can't we add flags to provide that additional information for registering the node?

**Comment by bgrant0607** [comment]
At this point, I think we've decided to officially deprecate LegacyHostIP. Any Kubelet configurations that don't specify whether its reported IP addresses are internal and/or external should be considered misconfigured.

The apiserver needs to support Kubelet releases at least 2 minor releases older.

I'm not sure whether we can assume that apiserver is the only client that cares about LegacyHostIP, though.

Heapster, for instance, uses it:
https://github.com/kubernetes/heapster/blob/master/metrics/sources/summary/summary.go#L421

It's possible that other monitoring clients may, as well.

@liggitt @justinsb @caesarxuchao @roberthbailey

**Comment by roberthbailey** [comment]
@thockin -- this may be a good test for your new deprecation proposal. ;)

**Comment by thockin** [comment]
Devin will get us a place to store deprecation notices.  I continue to
believe that we should roll a v2 API with minimal changes, *just to prove
we can*.

**Comment by liggitt** [comment]
unused and removed as of 1.7
/close
