### ISSUE TITLE
Missing logging agents causing Job ci-kubernetes-e2e-gci-gce-sd-logging to fail

### ISSUE THREAD

**Issue by brianpursley** [kubernetes/kubernetes#92731]
Job ci-kubernetes-e2e-gci-gce-sd-logging always fails with this error:
```
node <nodename> doesn't have logging agents, want 1
```

### Triage Dashhboard Link:
https://storage.googleapis.com/k8s-gubernator/triage/index.html#9faccb3eb85a99912a98

### Error text:
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/instrumentation/logging/stackdriver/soak.go:44
Jun 17 00:16:21.307: Logging agents deployed incorrectly
Unexpected error:
    <*errors.errorString | 0xc002964f50>: {
        s: "node bootstrap-e2e-minion-group-0fsc doesn't have logging agents, want 1",
    }
    node bootstrap-e2e-minion-group-0fsc doesn't have logging agents, want 1
occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/instrumentation/logging/stackdriver/utils.go:441
```
### Recent failures:
[7/1/2020, 11:36:39 AM ci-kubernetes-e2e-gci-gce-sd-logging](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-sd-logging/1278351753644871680)
[7/1/2020, 11:05:40 AM ci-kubernetes-e2e-gci-gce-sd-logging](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-sd-logging/1278343953086681088)
[7/1/2020, 10:34:13 AM ci-kubernetes-e2e-gci-gce-sd-logging](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-sd-logging/1278335899309969416)
[7/1/2020, 10:02:40 AM ci-kubernetes-e2e-gci-gce-sd-logging](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-sd-logging/1278328098126827522)
[7/1/2020, 9:31:50 AM ci-kubernetes-e2e-gci-gce-sd-logging](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-sd-logging/1278320296067076098)

/sig instrumentation

**Comment by brianpursley** [comment]
Not sure if this is sig instrumentation or not, but I thought I would start there. Feel free to reassign.

**Comment by erain** [comment]
All the recent runs of the tests have been failing: https://prow.k8s.io/job-history/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-sd-logging

Root cause was: [withLogProviderForScope](https://github.com/kubernetes/kubernetes/blob/6b388f06845009b8bd9963a8bd0796189b679486/test/e2e/instrumentation/logging/stackdriver/utils.go#L432-L444) expected that there should be one [fluentd-gcp](https://github.com/kubernetes/kubernetes/blob/6b388f06845009b8bd9963a8bd0796189b679486/test/e2e/instrumentation/logging/stackdriver/utils.go#L214) pod on each e2e node; however it found none. 

Next step should be to find out why the logging agent is missing (by running the e2e test manually and checking the node?).

**Comment by monotek** [comment]
Seems the fluentd-gcp daemonsets were renamed to fluentd-gke.
At least this is what i see in my GKE v1.16.13-gke.400 clusters.

**Comment by erain** [comment]
Discussed with @serathius and it looks like we do not depend on or need those tests. 

Is there anyone depend / need those tests and want to be the new owner for them? If not, I propose that we should delete them since they are unmaintained.

**Comment by erain** [comment]
It seems that nobody needs this.  

We had a discussion during the SIG Instrumentation triage meeting today and we agreed to delete this test to reduce the flakiness. I am going to send a PR for that.
