### ISSUE TITLE
pod stuck on preempting

### ISSUE THREAD

**Issue by lechen26** [kubernetes/kubernetes#92906]
Hi

i'm using GKE 1.16.8-gke.15 cluster (regional) with few nodepools.

i've noticed that one of my pod entered "preempting" mode and remains like that for more then 2 hours.
when describing the pod i saw the following:
```
Start Time:     Wed, 08 Jul 2020 10:49:49 +0300
...
Status:         Failed
Reason:         Preempting
Message:        Preempted in order to admit critical pod
```

that's fine it was preempted but i expect it to evicted and removed so new pod will reschedule.
when looking on the kubelet logs i see the following message :
`0708 10:49:49.949088    1091 preemption.go:114] preemption: pod domain-d9c95557-hs6k6_default(de9427fc-0db2-4bf4-b9f6-344be5233a7b) evicted successfully"   
` 

so it looks like kubelet does assume this pod was preemted and eivcted successfully.
eventually after 2.5 hours i just deleted it.

it looks like there is some kind of bug here no? that the pod stuck on preempting state for that long.
i should mention that this pod scheduled on preemtible nodes, and i've noticed the exact time this pod started (10:49) was basically the time this node was scaled up and started to start all system containers.
maybe its related?

any thoughts?

thanks!
Chen

**Comment by tedyu** [comment]
Here is the code preceding the 'evicted successfully' log:
```
		err := c.killPodFunc(pod, status, nil)
		if err != nil {
```
Can you check the kubelet log to see if there was some clue from killPodFunc ?

thanks

**Comment by lechen26** [comment]
i dont see anything on the log related to killPod.
this issue keeps happening at least few times a week, not sure why.

**Comment by tedyu** [comment]
Can you attach kubelet log (covering 10:49) ?

thanks

**Comment by jessicaochen** [comment]
In case it helps, I looked into a very similar case recently on GKE. Pod A was preempted for a critical pod. A new pod A' was scheduled correctly and promptly but the old pod A was never cleaned up and sat in preempting state.

Turns out, when there is a kubelet preemption it acts similar to a kubelet eviction. The code intentionally leaves the old pod A behind for debugging purposes. Normally, kube controller manager cleans up terminated pods. However, the count of terminated pods needs to meet a certain threshold before it starts cleaning up (presumably to allow room for potential debugging). This threshold was 1000 in the case I looked at. It should be perfectly safe to delete the old pods if you want to.
