### ISSUE TITLE
Add ability to run E2Es with non-root uids

### ISSUE THREAD

**Issue by pmorie** [kubernetes/kubernetes#9299]
There should be a way to easily run any e2e test as a non-root uid -- there's at least one issue that I believe would cause a breakage that it will be critical going forward to surface (#2630)

**Comment by pmorie** [comment]
@quinton-hoole @zmerlynn @smarterclayton @bgrant0607

**Comment by smarterclayton** [comment]
Why was this closed?

**Comment by fejta** [comment]
Thanks for reopening!

Multiple quarters elapsed without anyone making progress. I closed this class of bug because I want to bring attention to any that are still interesting to fix.

@ixdy this looks related to your plans to create a canonical way to run tests. I agree e2e tests should run as a regular user.
