### ISSUE TITLE
Does the pause container need to be resource restricted? Such as the memory

### ISSUE THREAD

**Issue by zhaocheng173** [kubernetes/kubernetes#93055]
Best practices from Docker-CIS tell me that all containers need to be memory restricted, while for the infra container shipped with pod in K8S, how does pause container limit memory？

**Comment by BenTheElder** [comment]
The sources are in build/pause

Pause is a simple while true sleep() loop + some signal handlers. It doesn't allocate, so resource limiting it is pretty unnecessary.

**Comment by nsoubelet** [comment]
Hi @BenTheElder, I do not think that limiting pause container is actually unnecessary.
For example, when using gVisor sandboxing this becomes a real problem since sandbox "reads" reported resources from pause container and informs them within the sandbox, so resource management in container is impossible in this case. See https://github.com/google/gvisor/issues/190#issuecomment-765657423.

Maybe it could be optional to limit pause container resources? What do you think?

**Comment by berginv** [comment]
Hi My pause container is using 33GiB of memory. Is this expected? Is there a way to limit resources?
