### ISSUE TITLE
RFI: Improved scheduling in support of blue-green deployments which don't consume 2x capacity

### ISSUE THREAD

**Issue by huggsboson** [kubernetes/kubernetes#93082]
**Problem**: 
At Box we have a number of large deployments (relative to our cluster capacity) with long drain times which we would like to quickly rollback in the face of issues.  The current rolling update deployments can take 12+ hours due to drain time, number of pods, and max unavailability.  If something were to go wrong it would potentially take 12+ hours to roll back.

One thing to note in this case is that while the old pods need to hang around until the deployment is complete, their CPU utilization is inversely-correlated with the new pod's CPU utilization.  i.e. as we're sending traffic to the new pods there is a lowering of traffic/utilization in the old pods.

**What would you like to be added**:
We would like to implement a form of blue-green (supports rapid rollbacks, allows old version to drain long requests), but one blocker we are constantly running into is the fact that a naive implementation of blue-green temporarily requires 2x the capacity which is an impossibility in our bare metal clusters and expensive in public cloud.

We have discussed a "hack" internally where the blue and the green pods each request their resource limit divided by 2.  And then scheduler guarantees that the blue and green pods get scheduled together either via pod affinities or a custom scheduler, but we're nervous about diverging too much from the community on this issue.  And worried about the scalability of pod affinities/anti-affinities.

It feels like supporting low overhead blue-green deployments would be something that we'd be interested in _enabling_ in a non-hacky way in the core.  I'm not proposing putting blue green deployments into the core as some other folks have, but rather allowing the concept of a pod whose cpu utilization is inversely correlated with another pod so they can be scheduled together without consuming additional capacity.

I'm also curious how other folks are solving these problems.  Are there existing community solutions to this?

**Some details**:
1. The deployments have 1000+ pods and a max unavailability of 10%.
2. The drains are up to an hour
3. New version should come up and be ready to take traffic in less than 10 minutes.
4. New version should take traffic in 1%, 10%, 100% steps.
5. Rollbacks should take less than 5 minutes.
6. The pods are a significant fraction of our cluster capacity 35% and fair exceed our reserved space to spin up a full duplicate.

**Trying to front run some other suggestions people might steer us towards**:
1. Standard rolling update doesn't work because it would take 10 hours just to roll out the new version.  And up to 10 hours in the case of a roll back.
2. Running a pod with a container with both current version and previous version and using standard rolling update solves the roll back problem, but still takes a long time to roll out.
3. We could mutate the code in place within the container and achieve a number of our goals, but there are a ton of other issues with that and it becomes even more non-standard.
4. We could use affinity rules to try and achieve this with the aforementioned hack around requests and limits.  But we're worried about scheduler performance with 1000+ pods running.

**Comment by huggsboson** [comment]
@Huang-Wei I noticed you folks landed the extensible scheduler docs recently.  I'm curious if you have any thoughts on if those extension points would be helpful for achieving my goals above, or if I'd be better served with something else.

**Comment by Huang-Wei** [comment]
> I'm also curious how other folks are solving these problems.  Are there existing community solutions to this?

I believe @resouer and cloud native sig-app-delivery did some research on blue-green deployment. If so, @resouer may be able to shed some light here.

Regarding your req of "_allowing the concept of a pod whose cpu utilization is inversely correlated with another pod so they can be scheduled together without consuming additional capacity_", I'm not quite sure I understand it right: is it possible to implement an out-of-tree Scheduler **Score** plugin to favor the node(s) where correlated pods were previously scheduled? so that you don't need to apply extra affinity rules.

**Comment by huggsboson** [comment]
Hi @Huang-Wei thanks for responding!

Yeah I think the basic question is, we know 2 pods pod-a and pod-b each require require X cores.  But we know that as pod-b's cpu utilization increases, pod-a's cpu utilization decreases (e.g. in a blue-green scenario).  So we'd like to leverage that understanding to overcommit nodes.  This is especially important with fixed sized cluster (i.e. baremetal), and large deployments that consume a significant portion of that fixed capacity to help improve rollout times.

As of today we can end up with full day rollouts for some of our larger services, and if something goes wrong it can take a long time to rollback.

The main hurdle seems like a scheduling problem / overcommitting problem, which is why I've tapped you, but let me know if I'm thinking about this wrong or barking up the wrong tree.  Would love to hear any thoughts from @resouer  as well.

**Comment by Huang-Wei** [comment]
> So we'd like to leverage that understanding to overcommit nodes.

As of today, both scheduler and kubelet honor the KSM (Kubernetes Resource Model) to take into account a Pod's resources **requests**, so you have to tweak the current implementation so as to overcommit, in these 2 components, which I don't believe is a trivial task.

> The main hurdle seems like a scheduling problem / overcommitting problem

I read it as a compound problem. But given that your rollout takes one day, it's more an overcommitting problem. Without enough reource releasing of old version of deployment, the scheduling would be pending - which I guess is common for a high-utilized cluster.

---

My 2 cents is that upon upgrading, pipeline a task to "shrink resource reqs to 1/2 of original value" for both old and new version of the workload, esp. when the proposal of "**In-Place** Horizontal Pod Autoscaling" is available (otherwise updating the req would restart the Pods). With this, this should be able to mitigate the overcommitting problem. If the rollout succeeds (fails), "double up the resource reqs to its original value" for the new (old) deployment.

Based on this, if the scheduling result is not ideal, as I mentioned earlier, you can probably implement an out-of-tree Scheduler Score plugin to favor some node(s) where old version of pods (old and new replicas) were scheduled. So this customized Score plugin can optimize the potential scheduling problem.

**Comment by huggsboson** [comment]
I wasn't aware of the fact that in-place mutation of pod resource requests was becoming an option.  That should definitely help.

Is this the proposal you are talking about?
https://github.com/kubernetes/enhancements/pull/686

**Comment by huggsboson** [comment]
I didn't realize resource requests were becoming mutable, that will help us successfully implement what we need re:blue-green whenever that is released.  Closing for now.

**Comment by Huang-Wei** [comment]
> Is this the proposal you are talking about?
> [kubernetes/enhancements#686](https://github.com/kubernetes/enhancements/pull/686)

Yes.
