### ISSUE TITLE
Volume fails to attach when the k-c-m leader changes

### ISSUE THREAD

**Issue by bryanhanner** [kubernetes/kubernetes#93090]
**What happened**:
A volume never successfully attaches to a node. Note for the timeline that we run k-c-m with high availability. Also note that Palantir’s clusters may see the issue more often than others because we replace both the nodes using the volumes and the nodes running kube-controller-manager automatically on a regular basis.

Timeline:
1. node A launches (ip-10-0-55-221.AZ.compute.internal)
2. the old k-c-m leader L attaches volume 1 (pvc-3e3be98e-2c3c-4c72-bfa7-a6d0dcf7a192) to node A
```
attacherDetacher.AttachVolume started for volume "pvc-3e3be98e-2c3c-4c72-bfa7-a6d0dcf7a192" (UniqueName: "kubernetes.io/aws-ebs/aws://AZ/vol-029ba1842f58a34c1") from node "ip-10-0-55-221.AZ.compute.internal"
```
3. Note that L never logs that the attach was successful
4. the new k-c-m leader M tries to attach volume 1 to node A (same message as above)
5. until another node replaces A, M fails to attach volume 1
```
Operation for "{volumeName:kubernetes.io/aws-ebs/aws://AZ/vol-029ba1842f58a34c1 podName: nodeName:}" failed. No retries permitted until 2020-07-14 01:14:24.015067975 +0000 UTC m=+68508.845386339 (durationBeforeRetry 500ms). Error: "AttachVolume.Attach failed for volume \"pvc-3e3be98e-2c3c-4c72-bfa7-a6d0dcf7a192\" (UniqueName: \"kubernetes.io/aws-ebs/aws://AZ/vol-029ba1842f58a34c1\") from node \"ip-10-0-55-221.AZ.compute.internal\" : volume is still being detached from the node"
```

The issue here is that L succeeded in attaching volume 1 to node A in AWS (confirmed via the console), but was stopped before A’s node object in k8s was updated (specifically https://github.com/kubernetes/kubernetes/blob/release-1.17/pkg/controller/volume/attachdetach/reconciler/reconciler.go#L220). This causes M to try to attach the volume again, which continuously causes an error because the volume is already attached to node A. The error “volume is still being detached from the node” was added in https://github.com/kubernetes/kubernetes/pull/83567 and violates the assumption made in https://github.com/kubernetes/kubernetes/blob/release-1.17/pkg/volume/awsebs/attacher.go#L82-L83 that if the volume is already attached we will succeed.

**What you expected to happen**:
I would expect k-c-m to succeed in attaching a volume when the volume is already attached correctly. 

**How to reproduce it (as minimally and precisely as possible)**:
1. Have the kube-controller-manager pod sleep after attaching the volume but before updating the k8s node.
2. Create pod that requires a volume be attached to a node
3. Kill the k-c-m pod

**Anything else we need to know?**:
I was considering adding a conditional checking the volume status in the attach/detach controller to do the right thing depending on whether the volume is detaching/attaching or is already attached, but looking forward to hearing other people’s ideas.

**Environment**:
- Kubernetes version (use kubectl version): 1.17.8
- Cloud provider or hardware configuration: AWS
- OS (e.g: cat /etc/os-release): Ubuntu 18.04.4 LTS (Bionic Beaver) - debian
- Kernel (e.g. uname -a): Linux xxx 4.15.0-1077-aws #81-Ubuntu SMP Wed Jun 24 16:48:15 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: 
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by ashrayjain** [comment]
Potentially similar to https://github.com/kubernetes/kubernetes/issues/92145

**Comment by msau42** [comment]
@kubernetes/sig-storage-bugs

**Comment by jsafrane** [comment]
cc @gnufied @bertinatto @leakingtapan @wongma7 - AWS plugin should be idempotent and resume where the old A/D controller finished...

**Comment by bryanhanner** [comment]
Hi @jsafrane, the issue isn't idempotency as much as synchronization between k8s and AWS. Specifically, k-c-m can be killed in between a volume attachment and marking the volume attached on the k8s node. This puts the new A/D controller in an error loop because this change you made to fix another bug now blocks the attach from succeeding (even when it's already successfully attached): https://github.com/kubernetes/kubernetes/pull/83567. The hope here is to find a fix for this that still addresses the bug you addressed.

**Comment by gnufied** [comment]
I do not think that diagnosis is correct. If Leader A - tries to attach Volume X to node N1 and fails to record attachment and then Leader B - tries to attach volume X to node N2, but then since volume is previously attached to N1(even though not recorded), it will throw `DanglingAttachError` - https://github.com/kubernetes/kubernetes/blob/db28b0239a1d09e46507e0b320f0b4ffa1cbc8b6/pkg/volume/util/operationexecutor/operation_generator.go#L341 which would cause volume to marked as attached to node N1 in "uncertain state". 

This in turn would trigger detach from node N1 and then attach attempt would be made to node N2 as expected.

**Comment by gnufied** [comment]
Having said that - I do think that - https://github.com/kubernetes/kubernetes/pull/83567 might be problematic. @jsafrane this means that `AttachDisk` is no longer idempotent

**Comment by bryanhanner** [comment]
@gnufied N1=N2, so we don't hit the case you describe here.

**Comment by gnufied** [comment]
@bryanhanner yes if N1 is same node, we have a problem.  I opened https://github.com/kubernetes/kubernetes/pull/93567 to fix this bug while keeping behaviour @jsafrane wanted.

**Comment by wongma7** [comment]
Thx all for the quick fix. Just for the record in case we want to change this code again in the future (seems we are chasing AWS EC2 API behavior changes in perpetuum...), want to remark that this issue is possible without any leader changes being involved. 

As described in the fix PR:

> if DescribeInstance tells us that Volume is attached, we enter
waitForAttach loop without calling AttachDisk. But if DescribeVolume
tell us - device is actually detached, then we don't wait for 20
minutes and return error early.

In my case a statefulset was restarted and the pod was rescheduled to the same node. So KCM quickly Detached then Attached the same volume to the same node. The DescribeInstance at the beginning of Attach reported the volume was attached so AttachDisk was skipped (as described here https://github.com/kubernetes/kubernetes/blob/a6405451674428172956116b4c93710ac03ebddd/staging/src/k8s.io/legacy-cloud-providers/aws/aws.go#L1946). Subsequent DescribeVolumes then said the volume was detached so waitForAttach was stuck for 20+ minutes.

**Comment by msau42** [comment]
@wongma7 were you able to verify that the pr fixes this issue?

**Comment by wongma7** [comment]
@msau42 yes but please ignore me, the issue I just described/saw should've already been fixed by the original PR https://github.com/kubernetes/kubernetes/pull/83567/files. So I didn't really say anything novel or useful, just that I can confirm the new PR preserves the fix from 83567. THe reason I ran into the bug from 83567 again and fake news'd that it's related to this issue here is because I'm testing the patch with a 1.16 cluster which never had 83567 in the first place -_-.
