### ISSUE TITLE
Allow kubectl (and client-go and other client libs) to not follow redirects

### ISSUE THREAD

**Issue by cjcullen** [kubernetes/kubernetes#93129]
**What would you like to be added**: A field in kubeconfig, and a flag to kubectl to prevent the underlying client from following any redirects.

**Why is this needed**: kubectl generally doesn't need to follow redirects. In most cases, following redirects is potentially dangerous.

[CVE-2020-8559](https://github.com/kubernetes/kubernetes/issues/92914) would not have been an issue if kubectl didn't follow redirects. If there were an option to disallow following redirects, we would have had an immediate mitigation.

**Comment by liggitt** [comment]
(also client-go, I assume, and rest.Config)

**Comment by tallclair** [comment]
Related: https://github.com/kubernetes/enhancements/pull/1899.

**Comment by knight42** [comment]
how about adding a field to [rest.Config](https://pkg.go.dev/k8s.io/client-go@v0.18.6/rest?tab=doc#Config), say `FollowRedirect` which default to be false, so that we can configure the `http.Client` in [rest.RESTClientFor](https://pkg.go.dev/k8s.io/client-go@v0.18.6/rest?tab=doc#RESTClientFor) and [rest.UnversionedRESTClientFor](https://pkg.go.dev/k8s.io/client-go@v0.18.6/rest?tab=doc#UnversionedRESTClientFor) according to its value?

**Comment by knight42** [comment]
I have filed #93144 to fix this issue, PTAL!

**Comment by ecda909** [comment]
@knight42 Just tracking this issue and wondering if the failed checks on the PR are being addressed?
