### ISSUE TITLE
kubectl CRD delete hangs

### ISSUE THREAD

**Issue by agniveshadhikari** [kubernetes/kubernetes#93392]
**What happened**:
I ran  
`kubectl delete CustomResourceDefinition challenges.acme.cert-manager.io`  
Outputs  
`customresourcedefinition.apiextensions.k8s.io "challenges.acme.cert-manager.io" deleted`  
and then stuck forever.

Exiting using Ctrl+C, and querying again shows that the CRD was not deleted.  

**What you expected to happen**:
Delete the CRD and return to prompt.  

**How to reproduce it (as minimally and precisely as possible)**:
Not easily reproducible. I installed the CRDs for cert-manager and deleted them, both steps done using kubectl. It didn't delete this CRD (rest of the CRDs were deleted successfully), and I can't even manually get rid of it.  

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):  
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.4", GitCommit:"8a6cdee2dab2329284444e9448bdf8ab165e1c5c", GitTreeState:"clean", BuildDate:"2020-06-24T18:14:29Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:  
Azure Kubernetes Service
- OS (e.g: `cat /etc/os-release`):  
Windows 10
- Kernel (e.g. `uname -a`):  
MINGW64_NT-10.0-18363 xxxxxxxx-laptop 3.0.7-338.x86_64 2019-04-30 21:52 UTC x86_64 Msys

**Comment by liggitt** [comment]
removal of a CRD blocks on deletion of the individual CR instances

removal of the individual instances can block on finalizers

if you get the CRD in yaml form, what conditions are listed in the status?

**Comment by liggitt** [comment]
this one actually did need information :)

**Comment by agniveshadhikari** [comment]
As much as I would have liked to dig deeper into this, I had to reset the cluster to prioritize some deliverables that I had. However, I'll need to do a lot more of what I was doing when I got this error in the near future. Will revert if I am able to repro this.

**Comment by jpbochi** [comment]
@agniveshadhikari I ran into the same problem. As it turns out, there was an instance of `challenges.acme.cert-manager.io` that was still `pending`. I tried a simple delete on that resource, but this command also got stuck.

Then, I tried this trick:

1. *Either* run this:
`kubectl proxy &`
*or* run this is a separate shell session / terminal tab:
`kubectl proxy`

2. Get a json with the resource you want to delete, for example:
`kubectl get challenges.acme.cert-manager.io quickstart-example-tls-1016717128-3781756796-4176224615 -o json > bad.json`

3. Make a PUT call removing any finalizer
`cat bad.json | jq '. | setpath(["metadata","finalizers"]; [])' | curl -kD- -H "Content-Type: application/json" -X PUT --data-binary @- "127.0.0.1:8001$(cat bad.json | jq -r '.metadata.selfLink')"`

**Comment by liggitt** [comment]
Make a PUT call removing any finalizer

I think these steps can be simplified to:
```
kubectl patch challenges.acme.cert-manager.io/quickstart-example-tls-1016717128-3781756796-4176224615 \
  --type=merge \
  --patch '{"metadata":{"finalizers":[]}}'
```
