### ISSUE TITLE
k8s v1.18.3 kubectl top node ,cpu sometimes negative 

### ISSUE THREAD

**Issue by liupeng0518** [kubernetes/kubernetes#93462]
**What happened**:
k8s v1.18.3 kubectl top node ,cpu sometimes negative 
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
k8s v1.18.3
- Cloud provider or hardware configuration:
baremetal
- OS (e.g: `cat /etc/os-release`):
centos7.7
- Kernel (e.g. `uname -a`):

- Install tools:
prometheus,not metrics-server
- Network plugin and version (if this is a network-related bug):
calico
- Others:

**Comment by Cweiping** [comment]
@liupeng0518 Is there more detailed information to reproduce the problem?

**Comment by pawelan** [comment]
I had identical symptoms. In our deployment (hosted on vSphere 6.5) we are using dedicated edge node (2vCPU 4GB RAM) and when in /etc/kubernetes/kubelet-config.yml the configuration was:
```
cpuManagerPolicy: static
reservedSystemCPUs: "0-1"
```
It was giving exact results (truncated for clarity):
```
# kubectl top node
NAME        CPU(cores)   CPU%                                    MEMORY(bytes)   MEMORY%
edgeb2      53m             -9223372036854775808%    1035Mi                  31%
```
This was causing pod allocations to this node fail due to insufficient CPU:
`Warning  FailedScheduling  <unknown>  default-scheduler  0/7 nodes are available: 2 Insufficient cpu, 5 node(s) didn't match node selector.`

Fixing the line:
`reservedSystemCPUs: "0"`
and restarting kubelet resulted in normal readings.

Environment details:
```
CentOS Linux release 7.8.2003 (Core))
Linux 4.18.0-147.5.1.el8_1.x86_64
# kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:12:48Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:04:18Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```
