### ISSUE TITLE
Can we introduce the capabilities of adding custom tags similar to [NodeConformance] , [Conformance] ? 

### ISSUE THREAD

**Issue by amitkrperf** [kubernetes/kubernetes#93553]
We are using sonobuoy to run conformance test and using the "Conformance" image for running the conformance tests. In order to run selective tests, currently there are two ways ( based on my current understanding) : 
1. Use the available test tags like, [NodeConformance] , [Conformance] etc. 
2. Use expressions which would be search using regex. 

We are building a pipeline which needs to run conformance tests on the cluster and we also want to build the capability in which we could run a fraction of the current conformance test based on requirements, eg, service related tests, pods related test. We intend to use our own customized tag instead of using regex expressions: 
1. Service related tests - [MYSVC] 
2. Pods related tests - [MYPODS] 

A wrong selected regex can cause a a large difference in the number of tests being selected ( "Pod" starts 80 tests while "Pods" start 27 tests ) . We would rather prefer to tag specific tests which we want to run. 

Later, we would want to extend this capability to all the other e2e tests, as well. 

**Environment:**

- Sonobuoy version: v0.18.3
- Kubernetes version: (use `kubectl version`): 1.15 
- Kubernetes installer & version: 1.15 
- Cloud provider or hardware configuration: Environment running in an AWS cluster
- OS (e.g. from `/etc/os-release`): Debian GNU/Linux 9
- Sonobuoy tarball (which contains * below) - N/A

**Comment by BenTheElder** [comment]
@spiffxp @johnbelamaric 
/sig testing

**Comment by spiffxp** [comment]
/area conformance

I'm not entirely clear on what's being proposed here?  If it's about adding improving tag hygiene or test naming hygiene for easier regexing, I would be interested in seeing a more concrete proposal.  Otherwise, I'm not really interested in adding a bunch of extra tags upstream.

I would also be interested in what improvements could be made to ginkgo to allow us to use something other than regexes for focus/skip.  I proposed some ideas in https://docs.google.com/document/d/1CECgoGzEVfrp75ef3uF1k3Tw4YfyWXoODVOyb5hEWSw/edit but the community's consensus was to stick with what we have now.
