### ISSUE TITLE
server version and client version in Kubernetes (kubectl version)

### ISSUE THREAD

**Issue by vigneshsolution** [kubernetes/kubernetes#93635]
Hi all,

I'm new to kubernetes world. Recently I have installed k8's 1.18 in my cluster. 
But when i am checking for the kubectl version i could see two different parameters "server version" & "client version". 
Can anyone explain me what is this exactly.
Will this version mismatch cause issue in cluster ?

updating necessary outputs below

root@testserver:~# uname -v
#33~18.04.1-Ubuntu SMP Fri Jun 26 15:01:15 UTC 2020

root@testserver:~# kubectl version --short
Client Version: v1.18.2
Server Version: v1.17.2

root@testserver:~# dpkg -l |grep -i kube
ii  kubeadm                                    1.18.2-00                                        amd64        Kubernetes Cluster Bootstrapping Tool
ii  kubectl                                    1.18.2-00                                        amd64        Kubernetes Command Line Tool
ii  kubelet                                    1.18.2-00                                        amd64        Kubernetes Node Agent
ii  kubernetes-cni                             0.7.5-00                                         amd64        Kubernetes CNI

root@testserver:~# dpkg -l |grep -i docker
ii  docker-ce                                  5:19.03.9~3-0~ubuntu-bionic                      amd64        Docker: the open-source application container engine
ii  docker-ce-cli                              5:19.03.9~3-0~ubuntu-bionic                      amd64        Docker CLI: the open-source application container engine
ii  docker-cimprov                             1.0.0.37                                         amd64        Microsoft CIM management interface for containers

**Comment by rikatz** [comment]
Hello,

It means that the api-server you're connecting to is v1.17.2.

Since you're using kubeadm, check the manifest from kube-apiserver in "/etc/kubernetes/manifests/kube-apiserver.yaml" the field "image":

```
$ cat /etc/kubernetes/manifests/kube-apiserver.yaml |grep image:
    image: k8s.gcr.io/kube-apiserver:v1.17.0
```

There's no problem using a major version of kubectl with one version difference from your cluster (like client v1.18 and server v1.17), it's not recommended that you have a big difference between them (like 3 versions).

If the situation was the opposite (server version > client version) I would recommend to update your client :)

I'm closing this issue, but feel free to reopen if you think it doesn't answer your question. Also I would recommend that you use other support channels (stackoverflow, discuss.kubernetes.io) for further support questions :)

Thank you!
