### ISSUE TITLE
Kubectl skew tests are failing

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#93694]
**Which jobs are failing**:

* ci-kubernetes-e2e-gce-new-master-gci-kubectl-skew
* ci-kubernetes-e2e-gce-stable1-beta-gci-kubectl-skew

https://storage.googleapis.com/k8s-gubernator/triage/index.html?text=Kubectl&job=skew

**Which test(s) are failing**:

Steadily failing tests making signal from the skew jobs unusable:
* `[sig-cli] Kubectl client Kubectl rolling-update should support rolling-update to same image [Conformance]`
* `[sig-cli] Kubectl client Kubectl run rc should create an rc from an image [Conformance]`
* `[sig-cli] Kubectl alpha client Kubectl run CronJob should create a CronJob`
* `[sig-cli] Kubectl client Kubectl run deployment should create a deployment from an image [Conformance]`
* `[sig-cli] Kubectl client Kubectl run job should create a job from an image when restart is OnFailure [Conformance]`
* `[sig-cli] Kubectl client Kubectl run default should create an rc or deployment from an image [Conformance]`
* `[sig-cli] Kubectl client Simple pod should support inline execution and attach`
* `[sig-cli] Kubectl client Update Demo should do a rolling update of a replication controller [Conformance]`
* `[sig-cli] Kubectl client Simple pod should return command exit codes`

Flaking tests:
* `[sig-cli] Kubectl client Guestbook application should create and stop a working application [Conformance]`
* `[sig-cli] Kubectl client Kubectl replace should update a single-container pod's image [Conformance]`
* `[sig-cli] Kubectl client Kubectl patch should add annotations for pods in rc [Conformance]`
* `[sig-cli] Kubectl client Simple pod should support port-forward`
* `[sig-cli] Kubectl client Kubectl client-side validation should create/apply a CR with unknown fields for CRD with no validation schema`
* `[sig-cli] Kubectl client Kubectl client-side validation should create/apply a valid CR for CRD with validation schema`

**Testgrid link**:

**Reason for failure**:

**Anything else we need to know**:

The skew jobs are what tell us if we've broken compatibility with prior kubectl releases. I'm surprised they aren't considered release blocking, but they should be a high priority for sig-cli to fix regardless.

/sig cli
/priority critical-urgent
/cc @soltysh @seans3

**Comment by liggitt** [comment]
cc @hasheddan 

I think you looked at some of these and it looked like kubectl tests were making use of deprecated functionality. Detecting/omitting tests of deprecated functionality in the release the function is removed seems reasonable.

**Comment by liggitt** [comment]
/milestone v1.19

adding to the milestone for sig-cli to resolve the root cause ... these jobs are the primary way we know we're meeting our kubectl compatibility commitments

**Comment by neolit123** [comment]
this test:
> [sig-cli] Kubectl client Update Demo should do a rolling update of a replication controller [Conformance] 

was removed with the "rolling-update" command removal in 1.18:
https://github.com/kubernetes/kubernetes/pull/88057/commits/932500c0151a4f0926cf07e63068248540b22f90#diff-fde2ce0a73639d19347a5ea6fe001ba6L325

a failing job such as `ci-kubernetes-e2e-gce-new-master-gci-kubectl-skew`:
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-new-master-gci-kubectl-skew/1290907818873851904

is defined here:
https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-cli/sig-cli-config.yaml#L217

> stable1 e2e tests run against a stable1 gce cluster using a master kubectl binary

so this test should not be running unless something is wrong with:
```
      - --extract=ci/latest
      - --extract=ci/k8s-stable1 
```

and indeed it is:
```
$ curl -L https://dl.k8s.io/ci/latest.txt
v1.20.0-alpha.0.509+f7e3bcdec2e090
$ curl -L https://dl.k8s.io/ci/k8s-stable1.txt
v1.17.9-rc.0.13+fdec14cd4c84b7
```

so the test-suite in 1.17.9... still has the test that then calls the kubectl binary from master that no longer knows about the "rolling-update" command.

maybe the intent is to use `release/stable-1`:
```
$ curl -L https://dl.k8s.io/release/stable-1.txt
v1.18.6
```

**Comment by neolit123** [comment]
this file also has a variety of different labels that have to be double checked if returning the expected versions WRT the SIG CLI/kubectl tests..:
https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-cli/sig-cli-config.yaml

```bash

# this label is generally confusing. i was asking related questions a couple of years ago.
$ curl -L https://dl.k8s.io/ci/k8s-beta.txt
v1.18.6-rc.0.15+e38139724f8f00

# these two seem fine (expect consumers might ask "what is fast?")
$ curl -L https://dl.k8s.io/ci/latest-fast.txt
v1.20.0-alpha.0.509+f7e3bcdec2e090
$ curl -L https://dl.k8s.io/ci/latest.txt
v1.20.0-alpha.0.509+f7e3bcdec2e090

# these two seem one MINOR behind! BUG?
$ curl -L https://dl.k8s.io/ci/k8s-stable1.txt
v1.17.9-rc.0.13+fdec14cd4c84b7
$ curl -L https://dl.k8s.io/ci/k8s-stable2.txt
v1.16.13-rc.0.5+24212641c73bc0
```

/sig release

**Comment by hasheddan** [comment]
@neolit123 hmm I think we may want `ci/1.18-latest` here. I am not sure why the `stable-*` versions appear to be a cycle behind though. Taking a look.

/cc @kubernetes/release-managers

**Comment by neolit123** [comment]
there is no `ci/1.18-latest`:

```
$ curl -L https://dl.k8s.io/ci/1.18-latest.txt
<?xml version='1.0' encoding='UTF-8'?><Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Details>No such object: kubernetes-release-dev/ci/1.18-latest.txt</Details></Error>master $
```

but i do know there is a:
```
curl -L https://dl.k8s.io/ci/latest-1.18.txt
v1.18.7-rc.0.34+c6cb4f0949d4b9
```

in fact this gives a more recent/valid version and we use it in the kinder e2e tests.
a problem with that is that someone (or automation) has to update https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-cli/sig-cli-config.yaml each release.

**Comment by hasheddan** [comment]
I think the version builds are not honoring `extra-publish-file`: https://github.com/kubernetes/test-infra/blob/b7c645aa693d4ec7e7797d999d977538e356ff23/config/jobs/kubernetes/sig-release/release-branch-jobs/1.18.yaml#L217

**Comment by neolit123** [comment]
i think the version markers / labels are worthy of a KEP where we can define what is redundant and what we need.

**Comment by tpepper** [comment]
Also https://github.com/kubernetes/sig-release/issues/759

**Comment by hasheddan** [comment]
Following up here. The periodic builds are now publishing the correct version markers, when they actually push a new build. However, they only push a new build when it doesn't already exist (and it frequently does already exist). You can see a visualization of this by looking at test duration here: https://testgrid.k8s.io/sig-release-1.19-blocking#build-1.19&graph-metrics=test-duration-minutes

@justaugustus do these builds already exist due to the bazel build jobs and should these also be pushing new version markers (I would think yes, but they currently are not)?

**Comment by liggitt** [comment]
do we have feedback from sig-cli whether the advertised kubectl compatibility is tested for 1.19? is this release blocking?

**Comment by justaugustus** [comment]
Pinged @kubernetes/sig-cli-bugs [here](https://kubernetes.slack.com/archives/C2GL57FJ4/p1598292604022700) and [here](https://kubernetes.slack.com/archives/CN0K3TE2C/p1598305710065000?thread_ts=1598302665.062800&cid=CN0K3TE2C).

**Comment by brianpursley** [comment]
I can't answer whether this is release blocking, but I have some recent experience in the area of skew tests (https://github.com/kubernetes/kubernetes/issues/92734), so I'll add a couple pieces of information that might help:

First, I fixed some of the skew tests on the SIG-CLI dashboard last month by adding `[Deprecated]` to the test name, merging that into the Release-1.17 branch (https://github.com/kubernetes/kubernetes/pull/92972), and then updating the skew tests to skip `[Deprecated]` (https://github.com/kubernetes/test-infra/pull/18213). Maybe there are more like these that need to be marked as deprecated. I was just going off of the SIG-CLI testgrid dashboard [here](https://testgrid.k8s.io/sig-cli-master).

Second, it looks like at least one of the failing tests linked to above is this one: [[sig-cli] Kubectl client Simple pod should return command exit codes](https://testgrid.k8s.io/sig-cli-master#skew-cluster-stable1-kubectl-latest-gce)

This test has a slightly different problem than the ones using deprecated functionality, because the problem stems from an apparent change in behavior between 1.18 and 1.19.  Before 1.19, the test expected no error, but in 1.19 it was changed to expect a timeout. Admittedly, it seems unusual to test for that, but I have not looked into the history behind why that change was made.

About a week ago, I opened a PR (https://github.com/kubernetes/kubernetes/pull/94062) against the release-1.18 branch to fix the skew test failure by checking whether the test is running against a 1.18 cluster or a 1.19 cluster and using the appropriate expect code based on that.  I guess I didn't push hard enough on this, but I didn't realize it might hold up a release if it is not passing.

If someone can take a look at that PR, it might fix as least part of this issue.

**Comment by justaugustus** [comment]
/assign
(to help with looking at the version markers)

/milestone v1.20

**Comment by hasheddan** [comment]
ping @justaugustus, want to chat about this?

**Comment by hasheddan** [comment]
Tagging @saschagrunert on this also because he is doing work on push-build :+1:

**Comment by justaugustus** [comment]
/assign @hasheddan 

I'll work with you to clean this up in v1.21 (in relation to https://github.com/kubernetes/sig-release/issues/850).
/milestone v1.21

**Comment by pacoxu** [comment]
/cc
If need any help.

**Comment by palnabarun** [comment]
@hasheddan @justaugustus -- is this being worked on actively? Or, is it good to be retargeted for v1.22?

**Comment by liggitt** [comment]
it looks like the only consistent failure is `Kubectl client Kubectl cluster-info should check if Kubernetes master services is included in cluster-info [Conformance]`, which was changed by https://github.com/kubernetes/kubernetes/pull/95202/files but broke pre-1.20 tests running with a 1.20+ kubectl

**Comment by liggitt** [comment]
If that is the only failure, this doesn't seem release-blocking to me

/milestone v1.22
