### ISSUE TITLE
[Flaky Test] [sig-storage] CSI mock volume CSI attach test using mock driver should not require VolumeAttach for drivers without attachment 

### ISSUE THREAD

**Issue by hasheddan** [kubernetes/kubernetes#93749]
**Which jobs are flaking**:

`gce-ubuntu-master-containerd (ci-kubernetes-e2e-ubuntu-gce-containerd)`

**Which test(s) are flaking**:

`[sig-storage] CSI mock volume CSI attach test using mock driver should not require VolumeAttach for drivers without attachment `

**Testgrid link**:

https://testgrid.k8s.io/sig-release-master-blocking#gce-ubuntu-master-containerd

**Reason for failure**:

This appears to be an issue with the test cleaning up a namespace too early.

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/csi_mock_volume.go:267
Aug  5 12:10:36.725: deploying csi mock driver: create StatefulSet: statefulsets.apps "csi-mockplugin" is forbidden: unable to create new content in namespace csi-mock-volumes-7035 because it is being terminated
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/drivers/csi.go:410
```

**Anything else we need to know**:

/cc @kubernetes/ci-signal @kubernetes/sig-storage-test-failures 
/sig storage
/milestone v1.19
/priority important-soon

**Comment by msau42** [comment]
I wonder if the generated namespace suffix is not unique enough.

cc @Jiawei0227 to take a look

**Comment by Jiawei0227** [comment]
We do check if the namespace already exists here:
https://github.com/kubernetes/kubernetes/blob/a6405451674428172956116b4c93710ac03ebddd/test/e2e/framework/util.go#L346

**Comment by msau42** [comment]
For CSI tests, we generate a 2nd namespace for the driver. Does that use the same method? cc @gnufied

**Comment by Jiawei0227** [comment]
Another look at the raw-log. It seems like we do deleted the namespace in another test...
This namespace was in the testcase namespace in that test. And it is also the csi-driver namespace for this test. And after the first test terminated, that namespace get deleted. That's why the second test failed.

**Comment by Jiawei0227** [comment]
Okay, I found the issue.
This happens because of the cleanup mechanism in CSI mock volume.
https://github.com/kubernetes/kubernetes/blob/a6405451674428172956116b4c93710ac03ebddd/test/e2e/storage/drivers/csi.go#L216
So Let's say we have two testcases A and B.
1. Testcase A is in namespace `random-X` and it creates a namespace for its CSIDriver called `random-Y`
2. Testcase B is in namespace `random-W` and it creates a namespace for its CSIDriver called `random-X`. 
3. In theory, testcase B cannot create `random-X` for its CSIDriver because that namespace has already been used. However, there is a potential race here.
4. Let's say Testcase A executes first, and after it is finished, it's namespaces are getting cleanup by `deleteNamespaceFunc ` in its CSIDriver. So now the namespace `random-X` and `random-Y` was deleted.
5. Now the Testcase B comes and it creates namespace `random-X` for its CSIDriver and it succeed, because the namespace was already deleted and Testcase B is creating a new one.
6. After step 5, the `AfterEach` cleanup function was called for testcase A: https://github.com/kubernetes/kubernetes/blob/07cf64925e042c6b62a6a6cefd59d49c42b6ae24/test/e2e/framework/framework.go#L360
During this function, it deletes the namespace again just to ensure the namespace `random-X` and `random-Y` were truly deleted. And then it detects that the `random-X` still exists, the test framework think this is a leftover from testcaseA, however it is a newly created namespace from testcaseB. So the aftereach() call will delete the namespace.
7. The namespace `random-X` was deleted, and boom! Testcase B failed in the middle of execution.

This can happen only when testcaseA and B are pretty close to their execution time and also the namespace they generated are the same. 

Some potential fix thoughts:
1. Not to delete the first namespace in cleanupFunc(), because the Aftereach func will help to delete that namespace anyway.
2. generate longer random string, right now it's 4 digits. If we longer it to 6 or 8, the failure rate will decrease.
3. Use different base name for the two namespace generated for csi mock driver. Right now they are both `csi-mock-volumes-xxx`, we may need to change the CSI driver namespace to `csi-mock-volumes-driver-ns-xxx`. This way we are also reducing the chance of collision.

**Comment by gnufied** [comment]
We have to delete the first namespace (which includes test pods), otherwise if you delete them after deleting the driver pods - we will have pods stuck forever in terminating state. 

We could try naming driver namespace differently but it sounds like then this could still happen.  Have we considered first 6 chars of SHA1 or something similar for namespaces? (I know shas can collide too)

**Comment by msau42** [comment]
Maybe try both 2) and 3) to reduce the changes of collision
