### ISSUE TITLE
Discussion of Priority and Fairness End-to-End Tests for Beta

### ISSUE THREAD

**Issue by rngy** [kubernetes/kubernetes#93757]
## Basic CRUD

Should we create tests around the creation, modification and deletion of the `flowcontrol.apiserver.k8s.io` objects ? For example, adding an invalid FlowSchema with a misconfigured PriorityLevelConfiguration and verifying that the Status appropriately reflects its invalidity. I’m assuming the controller tests will suffice and we don’t need explicit e2e tests for this.

What about CRUD tests wherein we’re validating the debug endpoints are showing the right values ?

## Request Categorization Test

The first class of tests are the basic ones to verify that the requests are being categorized into the right FlowSchema and Priority level. We’ll set up a new PriorityLevelConfiguration and FlowSchema objects and observe that requests are correctly being classified onto them. Verification that requests are correctly being classified will be tricky. For now, we can scrape the metrics endpoint for ‘`apiserver_flowcontrol_dispatched_requests_total`’ metric to verify that the expected number of requests for a test FlowSchema is correct. 

Another option is to utilize the ‘dump\_requests’ debug endpoint to verify the correct request classification. If during the course of writing the tests we need additional information, we can extend the debug endpoint.

Scraping the metrics endpoints to validate the proper request categorization could lead to a fickle e2e test. So querying the ‘debug’ endpoint seems like the right way to go. This test will also serve as a proxy for an end-to-end test that ensures that requests matching a new FlowSchema are successful. 

#### Open Questions

*   Does this have the propensity to be a flaky test(s) ?

## Request Drown Out

This class of tests will focus on validating the behavior this feature promises, viz., requests of low priority won’t be drowned out by requests of higher priority and a single bad actor won’t detrimentally affect the requests from others. The following tests will ensure that high velocity flows don’t affect the low velocity flows.

### Priority

For this test, we’ll have two entities submitting requests at the same time. These requests will map to two different FlowSchemas at different priority levels. The higher priority flow will have a lot of requests going through it, far above its concurrency share. At the same time the low priority flow will be submitting requests as well at a rate that well within the concurrency limits of that Flow. The test will ensure that the low velocity (low priority) flow succeeds. 

### Fairness

This test will be the same as the above one except that the two flows will map to the same FlowSchema but are separated via their Flow Distinguisher. One of them will be a high velocity flow which the other is a low velocity one. The test will ensure that the low velocity requests still get through and succeed.

#### Open Questions

*   Does this have the propensity to be a flaky tests ?
*   If the test fails, will the runner of this test be able to grok where the problem could lie and debug ? Is this an actionable failure ?

**Comment by rngy** [comment]
cc/ @lavalamp @MikeSpreitzer @yue9944882 @deads2k

**Comment by lavalamp** [comment]
* We don't need to test that invalid items are rejected, unit tests are better for that.
* We should try to exercise the basic features (exempt, queue...)
* We should not rely on the debug endpoint, since we want this to be a conformance test eventually
* Metrics scraping is also a little questionable.
* I think we should exercise fair queueing (make two new PLs at different shares, saturate both, verify the responses follow the share ratio).
* I think we should exercise the shuffle sharding (make a new PL, saturate it with one/few elephants and many mice, verify the mice get service.

(those latter two seem to match your last two.)

This would be a pretty high level test that tests things end users will care about, but I think it should still be quite hard to pass without actually running our code.

**Comment by caesarxuchao** [comment]
cc @yliaog

**Comment by yue9944882** [comment]
> - We should not rely on the debug endpoint, since we want this to be a conformance test eventually
> - Metrics scraping is also a little questionable.

to verify the requests can be correctly classified, how about we make use of the [response headers](https://github.com/kubernetes/kubernetes/blob/92e51c19017a9e417df291e469ffebb13b6b51e2/staging/src/k8s.io/apiserver/pkg/server/filters/priority-and-fairness.go#L39-L40)? we can do a test like: make two PLs, and two clients w/ different identities then make the clients are hitting different FS/PL.

**Comment by yliaog** [comment]
what about using a test aggregated apiserver to serve different PLs, and with different the response latency

**Comment by MikeSpreitzer** [comment]
> For example, adding an invalid FlowSchema with a misconfigured PriorityLevelConfiguration and verifying that the Status appropriately reflects its invalidity.
No strong opinion on this one.

> We don't need to test that invalid items are rejected, unit tests are better for that.
I am not sure if that was a response to the ideas in the "Basic CRUD" section --- there the idea is not about testing validation but rather testing the status setting about referential integrity.

> What about CRUD tests wherein we’re validating the debug endpoints are showing the right values ?
The debug endpoints are about what is happening at the moment of the GET.  Controlling that tightly enough to be worth a test would be tricky.  The only plausible approach in an E2E test would be to register an authorization webhook that synchronizes with the test function.

> Request Categorization Test
I like the basic idea.
For the reasons above, I would not recommend looking at the debug endpoints.
I do not understand what is wrong with scraping the metrics.  Are they not part of conformance?
This feature _does_ add response headers.  Are those part of conformance?

> Request Drown Out
I like the basic idea.
First, remember that this feature does not control velocity; it controls the product of velocity and execution duration.
To get a high signal-to-noise ratio, we would want deterministic and large execution durations.  Looking in `apiserver/pkg/server/config.go`, you can see that authorization is included in execution.  So we could add a controlled large amount of duration in there.
I am a little surprised at the question of "If the test fails, will the runner of this test be able to grok where the problem could lie and debug"; why would that be more of a question here than for any other E2E test?  Presumably the test failure message will say something about the expected and observed behavior.

> We should try to exercise the basic features (exempt, queue...)
I think the drown-out scenario involves testing queuing.  I think exempt was not covered above, and would be a worthwhile addition.

> I think we should exercise fair queueing (make two new PLs at different shares, saturate both, verify the responses follow the share ratio).
This mixes up two things.  Fair queuing is something that happens within one priority level.

> I think we should exercise the shuffle sharding (make a new PL, saturate it with one/few elephants and many mice, verify the mice get service.
This sounds like it may be expensive for an E2E test.  I think we can make a much more efficient unit test of QueueSet that exercises shuffle sharding.  Because the QueueSet implementation can be given a FakeEventClock, we can run the test much faster than real time.

> what about using a test aggregated apiserver to serve different PLs, and with different the response latency
To get a high signal-to-noise ratio we want controlled, high latencies.  Making an aggregated apiserver do that is possible.  Perhaps the simplest approach would be to put a fixed sleep in the registry strategies for whatever custom resources the aggregated apiserver is serving.  But this seems like a lot more work than necessary.  I think an authorization webhook is a simpler approach.

**Comment by yliaog** [comment]
could you elaborate a bit more about the authorization webhook approach? it is only called in the authorization path, if i understand it correctly.

**Comment by MikeSpreitzer** [comment]
Authorization, and admission control, happen after the priority and fairness filter.

**Comment by ahg-g** [comment]
>  The higher priority flow will have a lot of requests going through it, far above its concurrency share. 

@MikeSpreitzer is this really possible? I am likely missing something, but my understanding from the [KEP](https://github.com/kubernetes/enhancements/blob/master/keps/sig-api-machinery/20190228-priority-and-fairness.md) is that each level is limited to the concurrency shares assigned to it.

**Comment by MikeSpreitzer** [comment]
@ahg-g : the text
> The higher priority flow will have a lot of requests going through it, far above its concurrency share
should be revised to more clearly express the intent.  It is that the driving client has many more requests outstanding at once than the corresponding priority level will allow to be served concurrently.

**Comment by adtac** [comment]
FYI: I'm working on the second test.
