### ISSUE TITLE
test/integration/scheduler_perf: make sure each testCase and workload has a unique name

### ISSUE THREAD

**Issue by adtac** [kubernetes/kubernetes#93795]
Note: this issue should be viewed in the context of #93252.

**What would you like to be added**: When parsing the performance-config.yaml file, make sure each testCase and workload has a unique name. This can also be implemented by changing the yaml file's structure into maps instead of arrays (as suggested by @alculquicondor), but this will result in a loss of test/workload order (i.e. a `5000Nodes` workload may run before a `500Nodes` workload).

**Why is this needed**: The name of each testCase and workload is used in the report generated by the framework and should therefore be unique in order to identify each metric.

/sig scheduling
/sig testing
/assign

**Comment by rajpratyush** [comment]
@adtac Hi this is my first time contributing to kubernetes. can you provide me some guidance on how to to get started?

**Comment by adtac** [comment]
@rajpratyush I recommend starting with the [contributor's guide](https://www.kubernetes.dev/docs/guide/) and reading from there.

**Comment by almas33** [comment]
Hi @adtac are you suggesting that name of workloads should be different for each test case  .
eg:-
`workloads:
  - name: 500Nodes_SchedulingSecrets`

**Comment by adtac** [comment]
@almas33 kinda, but I'm more interested in making sure that each test has a unique `testcase/workload` name identifier so that I can run it with `go test -run=name`

**Comment by Kappie37** [comment]
@almas33 Are you working on this?

**Comment by almas33** [comment]
@Kappie37 you can go ahead if you want

**Comment by pravarag** [comment]
@almas33 @adtac I would like to work on this issue if someone has not started already

**Comment by nicomitchell** [comment]
@almas33 @pravarag @Kappie37 if no one is currently working on this, I'd like to take a crack at it.

**Comment by Kappie37** [comment]
@nicomitchell Of course! Could you explain what you did so noobs like me could learn?

**Comment by nicomitchell** [comment]
> @nicomitchell Of course! Could you explain what you did so noobs like me could learn?

Sure! For the record I am a noob to this project as well, but my process for trying to solve issues on open source projects generally goes like this:

- Read the issue and figure out what files are going to be relevant. In this case I know the relevant file is going to be in test/integration/scheduler_perf because of the issue title and I know a performance-config.yaml file is going to be important as it's mentioned in the issue.
- Look at those files and figure out what they do. In this case I'm really only interested in the bits where the performance-config.yaml is parsed and validated. I Ctrl-F'ed scheduler_perf_test.go to see if it was reading that performance-config.yaml file and figured out that it was being checked in the validateTestCases function.
- Add the changes the issue is asking about. In this case, the issue wants to check that the names of test cases and workloads from the yaml file are unique. So I used a map to track which names had already come up and returned an error if they weren't unique. 

Hopefully this is helpful. I don't know if my PR will be accepted or not but I find it's usually best to just try and implement the changes needed with the limited information you have and let the reviewers tell you if you're on track or not.
