### ISSUE TITLE
Integrating kubernetes with Openstack

### ISSUE THREAD

**Issue by adyanthaya17** [kubernetes/kubernetes#9386]
Hi,

I'm trying to integrate kubernetes with my openstack without murano and was wondering if a code was required to configure in openstack. 

I have worked with chef previously and in that the knife.rb file was used to fetch the data from the openstack. Is it possible to do something similar in kubernetes too? The point of working on it is that I want to be able to look at the applications in the openstack GUI with docker.

Thank you.

**Comment by hurf** [comment]
I guess the Magnum project can help deploy k8s in an openstack environment.

**Comment by uruddarraju** [comment]
And also the latest code from Murano (a Miratis project has something like this)

**Comment by adyanthaya17** [comment]
The thing is I want to avoid working with the heat template for kubernetes and want to have an actual separate node that can integrate with openstack.

**Comment by uruddarraju** [comment]
@adyanthaya17 makes perfect sense, after all, I am not a big fan of Heat for many reasons.

But, if I understand it correctly, you want to create a kubernetes cluster on openstack. Is that right ? If it is, please look at the rackspace cloud providr for kube-up and the openstack.go cloud provider that we use to instantiate kubelet. A lot of these are actually broken and I have it in my queue to fix them. Let me know what you think. 

It by large depends on how you do your networking, and varies if you use a private cloud (like ebay) vs public cloud (rackspace)

**Comment by donghwicha** [comment]
this one can be solution for you https://github.com/GoogleCloudPlatform/kubernetes/pull/11798

I didn't tested it yet

**Comment by erictune** [comment]
fyi #11798 merged.

**Comment by erictune** [comment]
@adyanthaya17 I don't understand when you say "I want to ... have an actual separate node that can integrate with openstack. And launch an instance from the kubernetes.".  Are you talking about a Kubernetes node (which would correspond to one openstack VM instance) or something else?

**Comment by goltermann** [comment]
We’re going through old support issues and asking everyone to direct your questions to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes). 

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases. 

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.
