### ISSUE TITLE
[Flaky unit test] Test_Run_OneVolumeAttachAndDetachMultipleNodesWithReadWriteMany flakes with "Wrong total GetAttachCallCount" error

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#93902]
**Which test(s) are flaking**:

Test_Run_OneVolumeAttachAndDetachMultipleNodesWithReadWriteMany

**Reason for failure**:

```
--- FAIL: Test_Run_OneVolumeAttachAndDetachMultipleNodesWithReadWriteMany (0.63s)
    reconciler_test.go:811: Warning: Wrong NewAttacherCallCount. Expected: <2> Actual: <0>. Will retry.
    reconciler_test.go:811: Warning: Wrong NewAttacherCallCount. Expected: <2> Actual: <1>. Will retry.
    reconciler_test.go:909: Warning: Wrong total GetAttachCallCount(). Expected: <2> Actual: <3>. Will retry.
    reconciler_test.go:909: Warning: Wrong total GetAttachCallCount(). Expected: <2> Actual: <3>. Will retry.
    reconciler_test.go:909: Warning: Wrong total GetAttachCallCount(). Expected: <2> Actual: <3>. Will retry.
    reconciler_test.go:909: Warning: Wrong total GetAttachCallCount(). Expected: <2> Actual: <3>. Will retry.
    reconciler_test.go:909: Warning: Wrong total GetAttachCallCount(). Expected: <2> Actual: <3>. Will retry.
    reconciler_test.go:909: Warning: Wrong total GetAttachCallCount(). Expected: <2> Actual: <3>. Will retry.
    reconciler_test.go:919: Total AttachCallCount does not match expected value. Expected: <2>
FAIL
```

This is flaking rarely enough that it is not caught by our CI jobs, which currently tolerate up to 2 unit test failures per run (!).

With that toleration removed in https://github.com/kubernetes/kubernetes/pull/93605, this flake has been seen (https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/93605/pull-kubernetes-bazel-test/1293257915502694408).

Reproducible with the following steps:

1. Build a test binary for the affected package:

```
go test -race -c ./pkg/controller/volume/attachdetach/reconciler
```

2. Stress the affected test using the [stress](https://godoc.org/golang.org/x/tools/cmd/stress) tool:

```
stress ./reconciler.test -test.run Test_Run_OneVolumeAttachAndDetachMultipleNodesWithReadWriteMany
```

5. Once failures are seen, look at the logs to see the details about the error:

```sh
ls -lat $TMPDIR/go-stress*
cat $TMPDIR/go-stress...<filename>
```

/sig storage
cc @kubernetes/sig-storage-test-failures

**Comment by verult** [comment]
I was lucky enough to get 1 failure in ~5k runs, and then no failures for the next ~45k runs.

```
I0811 19:17:48.733522  335022 reconciler.go:275] attacherDetacher.AttachVolume started for volume "volume-name" (UniqueName: "fake-plugin/volume-name") from node "node-name1" 
I0811 19:17:48.733542  335022 operation_generator.go:361] AttachVolume.Attach succeeded for volume "volume-name" (UniqueName: "fake-plugin/volume-name") from node "node-name1" 
I0811 19:17:48.734076  335022 reconciler.go:275] attacherDetacher.AttachVolume started for volume "volume-name" (UniqueName: "fake-plugin/volume-name") from node "multi-attach-node" 
I0811 19:17:48.734189  335022 operation_generator.go:361] AttachVolume.Attach succeeded for volume "volume-name" (UniqueName: "fake-plugin/volume-name") from node "multi-attach-node" 
I0811 19:17:48.734570  335022 reconciler.go:275] attacherDetacher.AttachVolume started for volume "volume-name" (UniqueName: "fake-plugin/volume-name") from node "multi-attach-node" 
I0811 19:17:48.734805  335022 operation_generator.go:361] AttachVolume.Attach succeeded for volume "volume-name" (UniqueName: "fake-plugin/volume-name") from node "multi-attach-node" 
--- FAIL: Test_Run_OneVolumeAttachAndDetachMultipleNodesWithReadWriteMany (0.61s)
    reconciler_test.go:811: Warning: Wrong NewAttacherCallCount. Expected: <2> Actual: <0>. Will retry.
    reconciler_test.go:909: Warning: Wrong total GetAttachCallCount(). Expected: <2> Actual: <3>. Will retry.
    reconciler_test.go:909: Warning: Wrong total GetAttachCallCount(). Expected: <2> Actual: <3>. Will retry.
    reconciler_test.go:909: Warning: Wrong total GetAttachCallCount(). Expected: <2> Actual: <3>. Will retry.
    reconciler_test.go:909: Warning: Wrong total GetAttachCallCount(). Expected: <2> Actual: <3>. Will retry.
    reconciler_test.go:909: Warning: Wrong total GetAttachCallCount(). Expected: <2> Actual: <3>. Will retry.
    reconciler_test.go:909: Warning: Wrong total GetAttachCallCount(). Expected: <2> Actual: <3>. Will retry.
    reconciler_test.go:919: Total AttachCallCount does not match expected value. Expected: <2>
FAIL


ERROR: exit status 1
```

In summary, attach to the 2nd node happened twice.

Some notes:
* reconciler loop delay in the unit test is 0ms.
* ReadOnlyMany implies multi-attach is allowed, so the operation key in NestedPendingOperations includes node name.

My theory is this: focusing on attaches to `multi-attach-node` only, suppose the first attach is `a1` and second attach is `a2`. Because the attach to `node-name1` is on a different node from `a1` and `a2`, it runs in parallel and can be ignored here because it shouldn't cause any timing effect on `a1` and `a2`.
1. `a1` begins executing in a separate goroutine from the reconciler. An operation with the key `{"volume-name", "multi-attach-node"}` is pending.
1. Reconciler loop continues. When handling attaches, it sees the volume is still missing in ASW, because `a1` is in flight.
1. `a1` finishes, and in the same goroutine, the volume is added to ASW, and removes the operation `{"volume-name", "multi-attach-node"}` from pending list.
1. Reconciler then sees there's no operation  `{"volume-name", "multi-attach-node"}` in the pending state, so it proceeds to run `a2`.

I can see this being very rare - the operation pending check is right after the ASW check, so the chance for a parallel operation to squeeze in just the right instructions to cause the race is low.

This scenario is not unique to a multi-attach, so other tests in the suite should've flaked too.

I can verify this theory by controlling the timing of execution like so:
* inject a delay between ASW and operation pending checks in reconciler (call this `reconcilerCheckDelay`)
* inject a delay in the mock attach func (call this `attachDelay`)
* Set `reconcilerDelay > attachDelay`, and `attachDelay` should be high enough to allow the reconciler get past the ASW check before the attach goroutine marks ASW.
* Reconciler loop delay will be kept at 0.

**Comment by verult** [comment]
Verified with `reconcilerDelay = 100ms` and `attachDelay = 50ms`. Fails everytime

**Comment by verult** [comment]
The issue can be simplified to this: there are two types of threads, and boolean registers A and B initialized to false (A being whether the volume is marked as attached in ASW and B being whether the operation is pending).
```
main thread:
  while true:
    a = read(A)
    b = read(B)
    if not a and not b:
      set(B, true)
      spawnOperationThread()
```

```
operation thread:
  set(A, true)
  set(B, false)
```

This can be fixed by instead calling `read(B)` before `read(A)` in the main thread. `B == false` implies either there were no operations before it, or the previous operation has already set A. Because the main thread spawns the operation thread, there should be no operation thread running that could set A. Collectively, A is guaranteed to be up-to-date when it's read.

This translates to checking operation pending before checking ASW.

**Comment by verult** [comment]
Some other alternatives are (1) locking across ASW and NestedPendingOperations, which is bad; and (2) add an attach pending state in ASW, which, with enough machinery, might be able to replace NestedPendingOperation and keep all states written and read by multiple threads inside a single data structure, maybe? But this is a lot more involved.

**Comment by liggitt** [comment]
/priority important-soon

Note that this is blocking #93605 and full reopen of 1.20, so resolving the test flake in the next few days would be helpful.

**Comment by verult** [comment]
ACK I'm prioritizing this

**Comment by liggitt** [comment]
fyi, we're targeting getting https://github.com/kubernetes/kubernetes/pull/93605 merged by the end of this week, which I expect will start surfacing this flake more consistently

**Comment by verult** [comment]
ACK aiming to get a PR out today as soon as possible

**Comment by verult** [comment]
Still WIP - seeing some new unit test failures as a result of the fix

**Comment by verult** [comment]
Also note that the fix here is an optimization in most cases - attach and detach operations are expected to be idempotent

**Comment by msau42** [comment]
> Also note that the fix here is an optimization in most cases - attach and detach operations are expected to be idempotent

Does that mean the test case is flawed and we should relax the test?

**Comment by verult** [comment]
I think in general it'd be good to avoid issuing unnecessary calls wherever possible, given that we can't always verify a driver call is idempotent

**Comment by jingxu97** [comment]
Generally, I think idempotent is a requirement. Controller cannot guarantee to avoiding calling concurrently, e.g., when controller restarts, it loses the information about in-flight operations. So I think it makes sense to relax tests a little bit.

**Comment by mauriciopoppe** [comment]
Thank you for the detailed analysis @verult! Pasting the comment on https://github.com/kubernetes/kubernetes/issues/93902#issuecomment-672635201:

```
main thread:
  while true:
    a = read(A)
    b = read(B)
    if not a and not b:
      set(B, true)
      spawnOperationThread()
```

```
operation thread:
  set(A, true)
  set(B, false)
```

The order of operations that trigger an attach twice is:

```
main)   a = read(A), a = false
main)   b = read(B), b = false
main)   if not a and not b:
main)   set(B, true)
main)   a = read(A), a = false
thread) set(A, true), 1st attach
thread) set(B, false)  
main)   b = read(B), b = false
main)   if not a and not b:
thread) set(A, true), 2nd attach!
```
