### ISSUE TITLE
Adding tests for Hyper-V isolated Windows containers running on Windows Server 2004 hosts

### ISSUE THREAD

**Issue by marosset** [kubernetes/kubernetes#94017]
# Problem

Running e2e tests using Hyper-V islated Windows containers running on Windows Server 2004 hosts is currently not possible because:
- Containerd does not fully support multi-arch container image pulls with Hyper-V isolation.
The current behavior is that the first image matching OS/ARCH = windows/amd64 is always selected.
- Test images used in Kubernetes e2e tests for Windows are currently multi-arch images with Windows Server 2019 as the image. These images get published to https://hub.docker.com/u/e2eteam

Which results in the test images failing to start

# Possible Solutions

## Mutating admission webhook
Create a mutating admission webhook that would update pod specs scheduled to Windows nodes to use the single-arch images. This webhook would need to be installed on clusters where we want to run e2e tests on 2004 with Hyper-V isolation

https://github.com/jsturtevant/hyperv-mutating-webhook is a prototype for this webhook.

## Create a new image repository for 2004 single arch images
Create another repo (e2eteam2004?) and only publish single-arch test images to that image repository.
E2e test passes for 2004 with Hyper-V isolation would be passed a repo list pointing to this repository

/area test
/sig windows

**Comment by marosset** [comment]
@claudiubelu @adelina-t @jsturtevant what do you all think?
Using a mutating admission webhook seems like it would be more work upfront but a lot less maintenance long-term.

Also if anyone has any other ideas please share.

**Comment by claudiubelu** [comment]
Since it will use the first matched Windows image, then one solution would be to put the 2004 image first in the manifest list. That way it is going to be the first matched image. But this just solves the symptom, not the issue.

But since it is Hyper-V Isolation, why doesn't containerd support containers with multiple OS versions? Docker does, I've used Hyper-V isolation to build images for multiple OS versions after all. Additionally, and this is just a thought, could containerd be made to pull an image from a manifest list that matches the host the most, including OS, arch, and OS version?

**Comment by marosset** [comment]
We would like to be able to run these tests on both Windows Server 2019 and Windows Server ver. 2004.
If we re-ordered the images in the manifest to put the 2004 images first we'd run into the same issue for Windows Server 2019 :(

The Windows container team is working to add support for multiple OS versions to containerd and are working with the containerd community to find an agreeable implementation. Unfortunately this is still a few weeks or months away so we are looking at other ways to validate hyper-v isolated containers on Windows Server ver. 2004.
@immuzz too in case he has anything to add here.

**Comment by adelina-t** [comment]
Ok, so my 2 cents here:

- Mutating webhook would clearly be cleaner solution here IMO. It's a bit more code to maintain, but it's not that complicated.

- New image repo would be a simpler solution, however, when we lose control over the image repository ( i.e when we finally have image builder & Windows images published to gcr ) then this solution will be tough to maintain given that we depend on infra for any change we want in repos.

**Comment by marosset** [comment]
Thanks @adelina-t - If we were to implement the mutating webhook solution, where would be good place to host the code and the container image? Probably sig-windows-tools for the code and the e2eteam repo for the container image?

**Comment by adelina-t** [comment]
For the container image, yes, e2eteam repo. For the code, I would put it in windows-testing repo, as the primary use-case for the webhook is the e2e job. However, I can see how a client / user might make use of the webhook as well, so sig-windows-tools would fit as well.

**Comment by jsturtevant** [comment]
The option for a new image repository will not be effective due to the explosion of versions (each WS OS) and would not be compatible with the work being done to have the [windows images in the promotion pipeline](https://github.com/kubernetes/kubernetes/pull/77269#issuecomment-675002434) as @adelina-t  pointed out.  

In the short term, I think having the mutating web hook for the hyperv tests is a possibility and could be an example for other scenarios, such as the selection of the proper runtime classes.  

I agree with @claudiubelu that containerd handling multiple OS versions it the best solution.  There are conversations in the community to do that in the best way possible.

**Comment by marosset** [comment]
/close

we have tests at 
- https://testgrid.k8s.io/sig-windows-containerd#aks-engine-azure-windows-2004-master-containerd-hyperv
- https://testgrid.k8s.io/sig-windows-containerd#aks-engine-azure-windows-master-2004-containerd-hyperv-serial-slow
