### ISSUE TITLE
jobs: allow user to specify back-off delay

### ISSUE THREAD

**Issue by SeagleLiu** [kubernetes/kubernetes#94012]
Currently, the mechanism is "Failed Pods associated with the Job are recreated by the Job controller with an exponential back-off delay (10s, 20s, 40s ...) capped at six minutes". 

**What would you like to be added**:
I am wondering if we could specify a different set of back-off delays, i.e., we can include a vector of delay times in the job specification.

**Why is this needed**:
Our job work loads have a lot of external connection, which can be interrupted sometimes. The current retry mechanism is a bit too short to wait out the interruptions.

**Comment by neolit123** [comment]
/retitle jobs: allow user to specify back-off delay
/sig apps

please specify your k8s version.

**Comment by SeagleLiu** [comment]
K8S version: 1.15.12-gke.2

**Comment by here-abarany** [comment]
This is still an issue, and still very much a useful feature to have.

We have the opposite problem of the original poster where the maximum exponential backoff delay is too long. We have jobs that end up going through some retry backoff cycles because the namespace resource quotas (mainly CPU in our case) have been hit, and it extends the amount of time before k8s retries to schedule them when capacity is available. We do throttle the number of jobs we schedule to a certain extent to avoid overloading the system, but we want to have some amount of over-committal of scheduled jobs to avoid starving the queue and under-utilizing our quota.

/reopen
/remove-lifecycle rotten
