### ISSUE TITLE
CreateContainer timeout does not increment Attempt count in ContainerMetadata

### ISSUE THREAD

**Issue by willdeuschle** [kubernetes/kubernetes#94085]
**What happened**:
Call to [CreateContainer](https://github.com/kubernetes/kubernetes/blob/v1.17.8/pkg/kubelet/kuberuntime/kuberuntime_container.go#L128) times out. There is an error message of the form `CreateContainer in sandbox "<redacted>" from runtime service failed: rpc error: code = DeadlineExceeded desc = context deadline exceeded`.

The container manager implementing the CRI correctly received a `CreateContainer` request with [ContainerMetadata](https://github.com/kubernetes/kubernetes/blob/v1.17.8/staging/src/k8s.io/cri-api/pkg/apis/runtime/v1alpha2/api.pb.go#L876) having an attempt of 0: `"CreateContainer within sandbox "<redacted>" for container &ContainerMetadata{Name:<redacted>,Attempt:0,}"`. Note the [comment](https://github.com/kubernetes/kubernetes/blob/v1.17.8/staging/src/k8s.io/cri-api/pkg/apis/runtime/v1alpha2/api.pb.go#L875) on the `Attempt` field of `ContainerMetadata`: `// Attempt number of creating the sandbox. Default: 0.`.

On the next run of `SyncPod`, the kubelet attempts to create the same container again. However, it does not increment the `Attempt` number on `CreateContainer` timeouts, only on container restarts. Now, the `CreateContainer` call fails immediately (no longer with a timeout), with the error: `CreateContainer in sandbox "<redacted>" from runtime service failed: rpc error: code = Unknown desc = failed to reserve container name "<redacted>": name "<redacted>" is reserved for "<redacted>"`.

The problem is that after the timeout, the `Attempt` number was never incremented, but the CRI implementing container manager has already reserved the container name, and so all subsequent requests to create the same container will fail.

**What you expected to happen**:
I expect the kubelet to increment the `Attempt` number on the next `CreateContainer` retry (according to the `ContainerMetadata` semantics) so that the CRI implementing container manager does not reject the request.

**How to reproduce it (as minimally and precisely as possible)**:
Put a sleep in your CRI implementing container manager for `CreateContainer` requests. This will cause the kubelet's `CreateContainer` request to timeout, and the subsequent `CreateContainer` requests will have the same `Attempt` number.

**Anything else we need to know?**:
The container manager in our case is containerd. We're working to resolve it's latency, but want to also fix this problem because it causes certain pods to get stuck indefinitely.

Related to: https://github.com/kubernetes/kubernetes/issues/30463

**Environment**:
- Kubernetes version (use `kubectl version`): 1.17.8
- Cloud provider or hardware configuration: AWS
- OS (e.g: `cat /etc/os-release`): 18.04.5 LTS (Bionic Beaver)
- Kernel (e.g. `uname -a`): Linux 4.15.0-1079-aws
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by mkumatag** [comment]
I also have seen this issue with containerd runtime, anyone working on this issue?

**Comment by qiutongs** [comment]
Sorry for not having a chance to work on this. I plan to work on this in the coming week.

**Comment by qiutongs** [comment]
@mkumatag @willdeuschle, 
Sorry for late reply. I dived into the kubelet code. I see the attempt count depends on the restart count of the current status of container ([code reference](https://github.com/kubernetes/kubernetes/blob/v1.17.8/pkg/kubelet/kuberuntime/kuberuntime_container.go#L113-L116)). I am not sure if it correct to increment attempt in timeout case. See my analysis below.

At the time of second CreateContainer request is making, what is the state of **first request** inside the container manager(Containerd)? I think there are three possibilities: (1) succeeded or (2) failed or (3) in the middle of creation. 

And in your cases, I would guess it is (3). If it were (1), the attempt should be already incremented in the second request. If it were (2), the container name shouldn't be reserved. So if it is (3), then it is a race condition and the behavior of kubelet seems correct to not increment?  

I may be wrong and please let me know what you thinks. In the meantime, I am trying to reproduce it locally.

**Comment by qiutongs** [comment]
I was able to test the timeout behavior with **docker runtime**. And all behaviors seem expected. I will similar for containerd.

To simulate the timeout, my setup is:
- set the runtime-request-timeout to 1s
- put a "sleep(2s)" at the **top** of [CreateContainer of dockershim](https://github.com/kubernetes/kubernetes/blob/v1.17.8/pkg/kubelet/dockershim/docker_container.go#L88) (the CRI implementation of docker).

After creating a pod, I found:
1. [First Request][Kuberuntime CreateContainer](https://github.com/kubernetes/kubernetes/blob/v1.17.8/pkg/kubelet/kuberuntime/kuberuntime_container.go#L128) with attempt 0. 
2. [First Request]dockershim CreateContainer went to sleep 
3. [First Request]Kuberuntime got error DeadlineExceeded
4. [Second Request]In next SyncPod, Kuberuntime CreateContainer with attempt 0. (This is expected because the container is not created yet and therefore the [containerStatus is nil](https://github.com/kubernetes/kubernetes/blob/v1.17.8/pkg/kubelet/kuberuntime/kuberuntime_container.go#L114)
5. [Second Request]dockershim CreateContainer went to sleep
6. [Second Request]Kuberuntime got error DeadlineExceeded
7. [First Request]dockershim successfully created the container
8. [Second Request]dockershim failed to create the container. (This is expected because the container name is already taken up)
9. [Third Request] In next SyncPod, Kuberuntime CreateContainer with attempt 1. (This is expected because the container is created and therefore the attempt is incremented)
10. [Third Request] dockershim CreateContainer went to sleep
11. [Third Request] Kuberuntime got error DeadlineExceeded
12. [Third Request] dockershim successfully created the container (This is expected because the container's name is appended by the attempt. So it is a new name this time)
...

Eventually when dockershim completes the request within timeout, the pod becomes ready.

**Comment by qiutongs** [comment]
I simulated the behavior with containerd runtime as well. And everything looks expected, as same as docker runtime.

1. [R1] Kuberuntime CreateContainer with attempt 0
2. [R1] Containerd CRI CreateContainer and went to sleep
3. [R1] Kuberuntime got error DeadlineExceeded
4. [R2] In next SyncPod, Kuberuntime CreateContainer with attempt 0
5. [R2] Containerd CRI CreateContainer and went to sleep
6. [R1] Containerd CRI successfully created the container
7. [R2] Kuberuntime got error DeadlineExceeded
8. [R2] Containerd CRI failed to create the container due to "failed to reserve container name"
9. [R3] In next SyncPod, Kuberuntime CreateContainer with attempt 1
10. [R3] Containerd CRI CreateContainer and went to sleep
11. [R3] Kuberuntime got error DeadlineExceeded
12. [R3] Containerd CRI successfully created the container

**Comment by qiutongs** [comment]
My current summary: the Attempt is set properly and it is a not a bug. The Attempt is determined by the current restart count of the container. The error "failed to reserve container name" is expected to happen when Attempt number is the same. Once container manager(docker or containerd) can complete the CreateContainer request within runtime-request-timeout, the pod will be created successfully in kubelet.

Not sure how the "certain pods to get stuck indefinitely" can happen. Please provide more detail. Feel free to re-open this issue.

**Comment by qiutongs** [comment]
Feel free to reopen the issue.

/close
