### ISSUE TITLE
patch-based (server-side-apply) and post-based Namespace creation requests to different endpoints populate different namespace attribute in AdmissionReview

### ISSUE THREAD

**Issue by maxsmythe** [kubernetes/kubernetes#94168]
**What happened**:

It appears that validating admission requests for server-side apply are populating the `namespace` for requests to create Namespace objects.

Non server-side apply requests don't do this, and a missing namespace field is the only way to distinguish cluster-scoped resources from namespace-scoped resources. This appears to be a breaking behavioral change.

See https://github.com/open-policy-agent/gatekeeper/issues/792#issuecomment-678437342

**What you expected to happen**:

Requests to create namespaces would have a consistent signature between server-side apply and non-server-side apply contexts.

**How to reproduce it (as minimally and precisely as possible)**:

`kubectl apply -f ns.yml -v 8 --server-side`

See https://github.com/open-policy-agent/gatekeeper/issues/792

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): `1.18.2`
- Cloud provider or hardware configuration: kind
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by liggitt** [comment]
Requests made to namespaced URLs (URLs which contain a `.../namespaces/{namespace}` segment) populate the `namespace` attribute in AdmissionReview requests. The documentation of the AdmissionReview `namespace` field is as follows:

From https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#request:
```
    # Namespace of the resource being modified, if the resource is namespaced (or is a Namespace object)
    "namespace": "my-namespace",
```

Update/Patch/Delete requests to specific namespaces have consistently populate this attribute for modifications to Namespace objects. Server-side apply is a type of patch request, so even when it is creating an object, that attribute will be populated.

The difference is caused by a difference in the URL used by POST and apply-based creates.

Creation via POST requests are made against the `/api/v1/namespaces` endpoint, so no `namespace` attribute was populated.

Namespace computed from request path:

https://github.com/kubernetes/kubernetes/blob/a767ee53653e4ff355d8160548c48b4d22a0cbcf/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/create.go#L61-L75

Namespace admission attributes for POST-based creates:

https://github.com/kubernetes/kubernetes/blob/a767ee53653e4ff355d8160548c48b4d22a0cbcf/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/create.go#L143

Creation via server-side apply is done via a PATCH request to `/api/v1/namespaces/{name}`, so the `namespace` attribute is populated.

Namespace computed from request path:

https://github.com/kubernetes/kubernetes/blob/a767ee53653e4ff355d8160548c48b4d22a0cbcf/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/patch.go#L92

Namespace admission for apply-based creates:

https://github.com/kubernetes/kubernetes/blob/a767ee53653e4ff355d8160548c48b4d22a0cbcf/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/patch.go#L150-L161

This is currently working as intended. If we want to make the behavior consistent between the two, I'd consider populating the namespace attribute for POST-based creation of Namespace objects.

**Comment by apelisse** [comment]
Thanks for the thorough analysis Jordan, the problem OP is trying to solve is that they want to know if the object is namespaced or not, and used the presence of the field to detect that. According to your analysis, that seems wrong.

The typical way to know if an object is namespaced is to use the discovery information, would that be the right way to solve that?

**Comment by liggitt** [comment]
> The typical way to know if an object is namespaced is to use the discovery information, would that be the right way to solve that?

They could use discovery, or can continue to use the presence of the `namespace` attribute, special-casing `resource.group=="" && resource.resource=="namespaces"` requests (namespaces are the only cluster-scoped resource which can have the `namespace` attribute populated in AdmissionReview requests).

**Comment by liggitt** [comment]
the documentation should be clearer, and I'd consider updating the POST-based create behavior to include this information to be consistent

**Comment by apelisse** [comment]
@nodo, do you want to update the doc and/or the post-based create behavior?

**Comment by nodo** [comment]
Sure! I am happy to take care of both.

**Comment by nodo** [comment]
@liggitt where do you think it makes sense to add the namespace to the post-based behavior? 

We could add it to [RequestInfo](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/endpoints/request/requestinfo.go#L180), but that might interfere with authorization, right? Would it be better to add the namespace directly to the [createHandler](https://github.com/kubernetes/kubernetes/blob/a767ee53653e4ff355d8160548c48b4d22a0cbcf/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/create.go#L47) ?

**Comment by nodo** [comment]
Makes sense, I will give it a go, thank you! 👍

**Comment by liggitt** [comment]
that will also require sweeping admission plugins that check the namespace attribute. examples:

https://github.com/kubernetes/kubernetes/blob/88512be213159f87ed2dad07f75c02d355eadac5/plugin/pkg/admission/resourcequota/admission.go#L140-L143

https://github.com/kubernetes/kubernetes/blob/88512be213159f87ed2dad07f75c02d355eadac5/staging/src/k8s.io/apiserver/pkg/admission/plugin/namespace/lifecycle/admission.go#L83-L86

**Comment by nodo** [comment]
@liggitt I think that we don't need to change https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#request anymore now.

Do you know if there are other places where I should look?

**Comment by liggitt** [comment]
yeah, I think we're good now. thanks for helping identify and clean this up
