### ISSUE TITLE
Feature Request: Separate Ingress from IngressRule

### ISSUE THREAD

**Issue by rittneje** [kubernetes/kubernetes#94321]
**What would you like to be added**:

Currently the Ingress v1beta1 resource is responsible for holding both the TLS secret to use for each hostname, as well as the HTTP path routing rules to use at the application layer.

With the change, Ingress and IngressRule would be two separate top-level resources.
* An Ingress is responsible for saying which TLS secret to use for a given hostname. Additionally, if you are using mutual TLS or application layer protocol negotiation, that information would be tied to the Ingress.
* An IngressRule would be responsible for HTTP path-based routing.

These definitions line up very well with the existing meaning of these resources. The real difference is that an IngressRule is now a first-class resource that is associated to an Ingress, rather than simply being a child attribute.

**Why is this needed**:

Due to path routing, there can be any arbitrary number of ingresses for the same exact hostname. However, you cannot have separate TLS server certs for these routes, because that information is not known during the handshake. What this means today is the every single ingress needs to include the same secret reference for no real reason. Worse, there is no enforcement that all of the ingresses actually agree on this secret. This is really confusing.

**Comment by liggitt** [comment]
Ingress just reached v1 in 1.19, so it is unlikely significant rework of this API will be done.

**Comment by liggitt** [comment]
cc @robscott

**Comment by robscott** [comment]
Hey @rittneje, I agree with your idea that it would be helpful to have an API that separated routing from TLS and other config. We're actually working on just that with [Service APIs](https://github.com/kubernetes-sigs/service-apis). We want to keep the Ingress API as simple and straightforward as it is, but with Service APIs we're trying to develop an API that allows for more advanced configuration and authorization. We're nearing an alpha API release and would love any feedback you have. You can find us in the #sig-network-service-apis channel in Slack and/or join one of our meetings: https://kubernetes-sigs.github.io/service-apis/community/.

**Comment by rittneje** [comment]
@robscott I went through this document: https://docs.google.com/document/d/1BxYbDovMwnEqe8lj8JwHo8YxHAt3oC7ezhlFsG_tyag/preview#

My understanding is that Gateway lines up with my description of Ingress, and HTTPRoute lines up with my description of IngressRule. Thus it seems very much like the model we are looking for. However, I don't think the Gateway spec ought to include the list of routes. For our workflow, the individual path routes live with their corresponding service specs, and we wouldn't want to have to maintain a master list like this. It would be preferable if instead the HTTPRoute referred to its Gateway, just as the Gateway has a reference to its GatewayClass.

Also, for our use case, the various HTTPRoutes could be in any one of a dynamic set of namespaces, so it would be unfeasible to have to list out all the namespaces that ought to have access to the Gateway. It would be preferable if there were a way to say that a Gateway can be used by all other namespaces.

**Comment by robscott** [comment]
@rittneje the API has evolved since that doc was written and may line up better with your expectations now. As an example, Gateways now use a [RouteSelector](https://kubernetes-sigs.github.io/service-apis/spec/#networking.x-k8s.io/v1alpha1.RouteBindingSelector) that can select Routes matching labels. Similarly, we've also moved from a list of namespaces to using label selection for namespaces. 

Although we'd explored the idea of Routes specifying Gateways it didn't fit well with our security model. We don't want to let any app developer be able to attach their Routes to any Gateway. We've been interested in potential bidirectional selection for Routes where the Gateway would have to select a Route and a Route could include a list of Gateways that were allowed to use it. I'm planning to take another look into exactly how that might work, but that kind of approach might also work for your use case. 

If you have any suggestions for how to improve Service APIs, please file an issue on that repo. We still haven't pushed an alpha release so we have a lot more flexibility with what we can change there.

**Comment by liggitt** [comment]
Thanks for the pointers, Rob. Closing this issue in favor of the service API design/repo
