### ISSUE TITLE
rounding issues with resources

### ISSUE THREAD

**Issue by kfox1111** [kubernetes/kubernetes#94445]
**What happened**:
User loaded in a deployment with a container with resources.requests.memory=1.2Gi

The usage showed up as:
1288490188800m
which is pretty hard to read. The user used 1.2Gi to make it easy to read.

**What you expected to happen**:
Gi should translate to Mi and round to the nearest Mi

**Environment**:
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.9", GitCommit:"a17149e1a189050796ced469dbd78d380f2ed5ef", GitTreeState:"clean", BuildDate:"2020-04-16T11:36:15Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

**Comment by liggitt** [comment]
> Gi should translate to Mi and round to the nearest Mi

Rounding user-specified values is not what I would expect. That seems like data loss.

**Comment by kfox1111** [comment]
Yeah. but I'd think the user having specified 1.2Gi (a value that is not super specific) would be quite confused when it spits out his usage against quota was 1288490188800m (I sure was). If they are specifying it as inprecicely as 1.2Gi, then it being something like 1229Mi is much more readable/understandable then 1288490188800m. If they want that much precision, they could have asked for it explicitly by just asking for 1288490188800m. Ie, round it to 4 decimals or something. Not to the absolute byte. No one these days cares about individual bytes.

**Comment by lavalamp** [comment]
As Jordan points out, many base 10 fractions (.2) expand infinitely in base 2 systems (Gi).

No one cares about the individual bytes until the scheduler is mysteriously telling you something doesn't fit. (This is literally the reason why we don't use regular floating point numbers.)

If we're mangling the user input into this form, that's one issue, but if we're just reporting the actual, literal usage, that seems correct. It can sometimes be important to figure out exactly what the system interpreted the request as.

Making the request for just 1.2G (no 'i') likely avoids this problem. You don't have to make the request in Gibibytes if you don't want to.

I can imagine some math tweaks [*] to change the behavior, but a) this code is already super complex and over-designed and b) it's used in so many places that preserving backwards compatibility is going to be really hard.

So, I am also frustrated that this is a bad user experience, but I'm not sure what to do about it. Open to suggestions.

[*] e.g. imagine what comes after the decimal for the 'i' units were interpreted as being out of 1024 instead of out of 1000. E.g., making the request for 1 and 200/1024 or ~1.195 in decimal. Downside: you'd no longer be able to ask for anything higher than 999/1024, or .976 in decimal. We could hack around that by e.g. permitting "A" as a digit, so it'd range from 0.0 to 0.A23. Even without that hack, this is at least as unexpected as the current behavior.

**Comment by kfox1111** [comment]
Yeah. its a hard problem no matter how you slice it.

I still think the principal of least surprise would have 1.2 become something like 1229Mi though. I don't think a user would ever be confused by it rounding up a smidge to give them a nice round number. Even if it has to go all the way out to a single byte. Them specifying 1.2Gi and it showing up as 1288490188800m is quite confusing. Even as a computer scientist, I have a difficult time parsing that... How can you have a fraction of a byte on a modern computer? 'm' is really strange in this context. (looks like maybe 1000m=1 byte?) but does show up all over the place such as quota when in use making it very difficult to check usage vs quota. It may make sense for a cpu, but not something like a byte.

**Comment by duxinxiao** [comment]
I'm facing this issue to. Don't really get the meaning of unit "m"

**Comment by lavalamp** [comment]
Yes, "m" is milli-, the SI prefix meaning 1/1000. (And of course, it's easily confused with capital "M" which is mega-, or 1,000,000-- that makes it extra confusing.)

I think the only thing that can be done here is resource-specific rounding (millibytes make no sense for modern computer systems but millicores do) in targeted places, but even that is very difficult to do while preserving user input and not breaking existing behavior.

**Comment by invsblduck** [comment]
Yeah, @rptaylor this is well said. I just found this issue after commenting on an older/closed/dead issue of the same topic: https://github.com/kubernetes/kubernetes/issues/74986

It's too bad `G` and `Gi` are already differentiated by K8s (in the spirit of "correctness") and that floating point memory quantities are already allowed, because it means no one can remove these features for fear of backwards-incompatibility. IMO, the implementation should have either copied JVM behavior, which simply doesn't allow floating point values for `-Xmx` and friends&#8212;and `g`/`gb` units mean the same thing&#8212;or it should align floats to sensible 8-bit boundaries (e.g., when the user specifies `1.3Gi`). This is purely for configuration robustness and the principle of least surprise. A user who provides a value like `1.3G` isn't close to the metal and probably doesn't care about the exact number of bytes anyway, and I'd be willing to bet that the majority of those users are completely unaware they are even using a multiple of 1,000 instead of 1,024 in the case of `1.3G`.

C library calls like `malloc(3)` and such work with bytes, kernel virtual memory works with pages that are multiples of bytes, and even memory addressing works by alignment on specific byte boundaries in order to be easier and faster for the CPU to retrieve memory contents (at the tradeoff of wasting memory with padding).

Returning a value like `30786724659200m` is likely just an accidental/uninformed thing to do within the context of modern computing history, Linux, and mainstream CPU architectures.

**Comment by lavalamp** [comment]
@invsblduck the problem is the same type is used for representing CPU quantity, which CAN be fractional (millicores), and we put all resources together in a map and they can't have different types. And then also we forgot to add validation / rounding code specifically for RAM (it's not obvious that 1.2Gi was something that implies a fractional byte). Also JVM wasn't even a test load when this code was written. apiserver and kubelet are completely different parts of the system.

Please note that the resource requests in the spec clause are just that -- requests. They are not expected to be the actual final values because actual memory is allocated in some page size that apiserver certainly doesn't know. Actual values should be reported in .status but I think we did not put them there due to size. There is nothing conceptually wrong with requesting a weird value since who knows what the page size will be -- most values are "weird".

The reason this persists: at this point it's hard to fix without breaking existing users / workflows, which may have settings like this. We can't round or fix values in spec because e.g. there could be controllers that see that as a difference from what they want and go into a loop trying to "fix" it.

There are many possible behaviors that would make more sense, the problem is getting one of those without breaking anyone else.
