### ISSUE TITLE
Pod stuck at "CreateContainerError" because of container name conflict

### ISSUE THREAD

**Issue by jmf0526** [kubernetes/kubernetes#94557]
**What happened**:
One pod stuck at CreateContainerError and can't get recovered automatically. Kubelet log shows that the requested name (let's say Container_2) is already in use.

> E0608 20:22:04.227708    3818 remote_runtime.go:200] CreateContainer in sandbox "7ae6b14089ca17bb2a995b564effb2fb9d993832fb7bfee63a59ad4b243eec58" from runtime service failed: rpc error: code = Unknown desc = Error response from daemon: Conflict. The container name "/k8s_harbor-redis_harbor-master3-bg4tz_kube-system_1b086090-d37b-40f4-99b3-57046033770e_2" is already in use by container "94ffec110c0342db864efad67c8ca47661266677b921a98131e4b0b09434cc05". You have to remove (or rename) that container to be able to reuse that name

`docker ps` shows the Container_2 Running, and it's created before Container_1

> Container_1       10mins ago       Exited 
> Container_2       1 day ago    Up
> 

**What you expected to happen**:
This should never happen.

**How to reproduce it (as minimally and precisely as possible)**:
I wish i knew.

**Anything else we need to know?**:
I know this can be caused by time shifting,  [83050](https://github.com/kubernetes/kubernetes/issues/83050)
but I didn't find any time shifting sign in system log and chrony log, and there is no rebooting between the create timestamp of Container_1 and Container_2, so this should be caused by something else. This happens intermittently in our env,  like 3 times in half a year, and I didn't find any ime shifting sign each time.

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.6", GitCommit:"7015f71e75f670eb9e7ebd4b5749639d42e20079", GitTreeState:"clean", BuildDate:"2019-11-13T11:20:18Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.6", GitCommit:"7015f71e75f670eb9e7ebd4b5749639d42e20079", GitTreeState:"clean", BuildDate:"2020-08-28T11:18:26Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
CentOS Linux release 7.5.1804 (Core)
- Kernel (e.g. `uname -a`):
Linux node-1 3.10.0-957.21.3.el7.x86_64 #1 SMP Wed Jul 17 06:57:50 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: 
kubeadm
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by nandeeshb09** [comment]
Any update on this issue, we are also facing the same issue.
EKS version : 1.14.9
Docker version: 19.03.6-ce
AWS CNI: 1.6.2

Intermittently we are also facing this , what might the issue, could please guide us here?

12e4e6edba39)" with CreatePodSandboxError: "CreatePodSandbox for pod \"a66cd63f-f0fe-11ea-9872-12e4e6edba39)\" failed: rpc error: code = Unknown desc = failed to create a sandbox for pod \"aiqx-server-dep-8f75457f6-b9lmv\": operation timeout: context deadline exceeded"

Sep 07 11:40:40  kubelet[2899]: W0907 11:40:40.679634 2899 prober.go:104] No ref for container "docker://7b9c86b529530f15d941f8e68973a202c8f348ab5db864a8371e8c82ddbf9dc4" (r(47608916-e845-11ea-bd96-0e424a2685e3)

Sep 07 11:40:43 kubelet[2899]: W0907 11:40:43.394480 2899 helpers.go:286] Unable to create pod sandbox due to conflict. Attempting to remove sandbox "a73bd9a03d56bc7855e4e89e163e13c5e7173397f10edcc200fb686e1b6885c8"

Sep 07 11:40:43 kubelet[2899]: E0907 11:40:43.394821 2899 helpers.go:291] Failed to remove the conflicting container "a73bd9a03d56bc7855e4e89e163e13c5e7173397f10edcc200fb686e1b6885c8": Error: No such container: a73bd9a03d56bc7855e4e89e163e13c5e7173397f10edcc200fb686e1b6885c8
