### ISSUE TITLE
StatefulSet status is not correct in a certain situation.

### ISSUE THREAD

**Issue by cvvz** [kubernetes/kubernetes#94577]
**What happened**:
I tried to rolling upgrade and scale out a StatefulSet at the same time. The new revision Pod is created at once, but for some reason, the deletion request of the old revision Pod  is refused by ValidatingWebhook for a long time. Before the deletion request admited by ValidatingWebhook, the status of StatefulSet keeps no change.

**What you expected to happen**:
The status of StatefulSet changes in time.

**How to reproduce it (as minimally and precisely as possible)**:
1. Set `spec.PodManagementPolicyType` to "Parallel", and `spec.updateStrategy.type` to "RollingUpdate".
2. Create a ValidatingWebhook refusing Pod deletion request.
3. Upgrage and scale out a StatefulSet at the same time.

**Environment**:
- Kubernetes version (use `kubectl version`):
```shell
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:48:36Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by kow3ns** [comment]
This is likely do to the implementation of the validating web hook that reacts to the StatefulSet. It isn't in the StatefulSet controller, and I could not reproduce it using a simple validating webhook (i.e. one that simply always validated the Pod). If the problem is in the API machinery (i.e. the API server) you should file a bug with sig api-machinery pertaining to validating web hook performance.
