### ISSUE TITLE
Rewrite bash code of addon updater in go

### ISSUE THREAD

**Issue by marekbiskup** [kubernetes/kubernetes#9470]
Bash has poor maintainability and error handling. Go will be more robust.

**Comment by marekbiskup** [comment]
cc @zmerlynn @davidopp @fgrzadkowski @satnam6502

**Comment by marekbiskup** [comment]
Related to #9849 - the current python inline code breakes CoreOS installations because they don't have python. The priority of this issue may increase (I don't see any other easy way to parse yamls in bash)

**Comment by marekbiskup** [comment]
I suggest to have it v1.0-post. A small go binary to query yamls will suffice for #9849. The binary itself may be also useful for other tests, so it won't be just a waste of time.

**Comment by zmerlynn** [comment]
I think a generic way to query yaml would be quite helpful, if you can
generate something. Or at least something that precompiles all our API
types and can handle those. I've been tempted to write that for a while and
just never had time.

**Comment by marekbiskup** [comment]
I reported #9937 for the command-line tool to query yaml.

**Comment by lavalamp** [comment]
You should use kubectl's template output to generate the format you want, rather than attempting to parse yaml/json from bash. (haven't looked at code at all; maybe you're not doing that?)

**Comment by marekbiskup** [comment]
I think kubectl can only show objects from the api server, not from files. Am I wrong?

**Comment by quinton-hoole** [comment]
This has more to do with updates than cluster.  Removing unnecessary team/cluster label.

**Comment by quinton-hoole** [comment]
Doesn't look like v1.0 to me, but I shall defer to @davidopp

**Comment by quinton-hoole** [comment]
My apologies for interfering - re-adding team/cluster.  Seems @thockin is indeed very involved in the conversation.

**Comment by davidopp** [comment]
This is a sub-issue of #9849, which we've been debating for ages. I'm trying to get closure on it. It's looking like we won't have to do this one (#9470) for 1.0 but I don't want to close it until we're sure.

**Comment by marekbiskup** [comment]
@davidopp 

Is it still needed to rewrite the addon updater in Go?

**Comment by davidopp** [comment]
The CoreOS folks got their stuff working:
https://github.com/kubernetes/kubernetes/blob/master/docs/getting-started-guides/coreos.md

So presumably this issue was addressed somehow -- I admit I did not read the guide yet, so I'm not sure. 

@roberthbailey and @mikedanese are starting to think about a longer-range plan for simplifying deployment, and I think we should let them decide what to do about this issue (and #9849 and the various issues transitively mentioned).

**Comment by roberthbailey** [comment]
@marekbiskup - the plan is to replace the current scheme for addons with a Deployment API object, at which point we will be able to ditch the shell scripts. 

@davidopp - the CoreOS guide details [how to deploy the DNS addon](https://coreos.com/kubernetes/docs/latest/deploy-addons.html), but doesn't provide instructions (anywhere I could find with a quick search) about how to update any cluster addons when you update your cluster software, so I'm not sure this issue has been fully addressed on CoreOS clusters.

**Comment by marekbiskup** [comment]
@roberthbailey I'm not sure how to proceed now. Could you clarify which one is the case:

1. With deployments, the addon updater will not be needed (or will be a very simple script) and there is no need to rewrite it in Go.

2. The addon updater will still be needed, but it will be completely changed (or we're not sure what it will look like). There is no point in porting it to go now.

3. Deployments will only simplify the update process, but the logic of the add-on updater will be the same (read API resources from disk and update it on the API server). I can rewrite it to go now, and then it will only be a small change to use deployments.

**Comment by roberthbailey** [comment]
@mikedanese and/or @nikhiljindal can provide more specifics on deployments, but from what I understand the answer is the first one:

Deployments will provide a declarative way to represent a cluster add-on (e.g., my cluster should have a replication controller for dns and a dns service). kubectl apply will provide a way to update a deployment, so that you can give a new definition of your deployment and the system will update the current state to match the new definition.

**Comment by marekbiskup** [comment]
Ok. Thanks for clarification. 

I'm closing this issue. It can be reopened (or we can create another one) if needed.
