### ISSUE TITLE
volume unstage not invoked until pvc is deleted, controller delete invoked before unstage

### ISSUE THREAD

**Issue by travisghansen** [kubernetes/kubernetes#94745]
**What happened**:

I create PVC, and POD to use the PVC. All csi actions get invoked in proper order.

I delete POD...node unpublish is invoked, unstage is not.
I delete PVC...controller delete is invoked, unstage is invoked.

**What you expected to happen**:

Unstage to happen when no pods on the node no longer need the pvc.
Ensure controller delete only happens when pvc is not published or staged on any node.

**How to reproduce it (as minimally and precisely as possible)**:

- Create a PVC to a csi provisioner with stage/unstage.
- Create a POD which uses the PVC
- Delete the POD
- observe unstage is not invoked
- Delete PVC
- Observe delete is invoke, and then unstage

**Anything else we need to know?**:

Seems to work fine on 1.17.x

**Environment**:
- Kubernetes version (use `kubectl version`): 1.18.6. and 1.18.8
- Cloud provider or hardware configuration: 'bare metal'
- OS (e.g: `cat /etc/os-release`): CentOS7 nodes installed with rke
- Kernel (e.g. `uname -a`): elrepo 5.8
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by travisghansen** [comment]
https://github.com/kubernetes/kubernetes/issues/94108

**Comment by saikat-royc** [comment]
The race between node unstage (NodeUnpublishVolume) and delete volume (DeleteVolume) is being fixed as part of https://github.com/kubernetes/kubernetes/pull/94737

For "volume unstage not invoked until pvc is deleted", this is expected behavior. Thoughts @msau42 @jingxu97

**Comment by msau42** [comment]
> For "volume unstage not invoked until pvc is deleted", this is expected behavior.

When all pods using that volume have successfully unpublished, then unstage should be called. You shouldn't need to delete PVC to get trigger unstage.

@kubernetes/sig-storage-bugs

**Comment by travisghansen** [comment]
@saikat-royc and to be extra clear, in my case unstage/delete is **not** a race condition...delete is simply getting invoked before unstage. Subtle difference but different nonetheless.

**Comment by saikat-royc** [comment]
I havent been able to repro a case where the volume delete is not invoked. Can you share the kube-controller-manager and the csi external provisioner sidecar logs for investigation

**Comment by travisghansen** [comment]
Delete is invoke, it's simply invoked *before* unstage. Which is slightly different from the other issue where unstage was getting invoked first but delete is/was not waiting for it to finish.

I'm using rke-v1.1.7 with my own csi driver/project: https://github.com/democratic-csi/democratic-csi

For my testing I've been running the `nfs-client` sub-driver which is a csi implementation of the old non-csi variant. Installing/configuring it is quite easy if necessary.

**Comment by saikat-royc** [comment]
Ah sorry I misread.

So, from code
Kubelet before proceeding with pod delete, checks if pod can be [deleted](https://github.com/kubernetes/kubernetes/blob/19064f47389429f8360e1d6684bef3d770db9368/pkg/kubelet/kubelet_pods.go#L950) syncPod->canBeDeleted->PodResourcesAreReclaimed->podVolumesExist. This only checks for volume mounted in the pod directory [This check is correct because for a scenario where we have multiple pods using the same volume, we do not expect the pod deletion to be blocked until the volume unstaged from the node]

[pvc protection controller](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/volume/pvcprotection/pvc_protection_controller.go#L171) checks if no POD is referencing the PVC and if so, removes the finalizer on a pvc which is marked for delete (which has a deletion timestamp).

So theoritically, delete volume can be called before unstage is invoked or unstage is in progress, because there is nothing stopping it from calling. An easy way to repro the issue is to keep force failing the unstage call in the driver, the global mount point will still exist, while a delete call will be invoked.

My patch https://github.com/kubernetes/kubernetes/pull/94737 fixes this issue where a "delete volume call should never be invoked before a node unstage". 
The fix: use node.status.VolumesInUse as a barrier in PVC controller before proceeding to remove finalizer on a PVC (marked for deletion).

So looks like the fix should address the issue you are facing. Let me know what you think

**Comment by travisghansen** [comment]
Unless I'm missing something it only addresses part of the issue:

1. unstage should be invoked as soon as no pods on the node are using the pv
2. delete should never be invoked while nodes still have the volume staged or published

Your fix seems to address 2 but not 1 correct?

**Comment by saikat-royc** [comment]
Yes for 2. For 1, we need to investigate kubelet code if there is any bug in unstage logic.

**Comment by jingxu97** [comment]
@travisghansen, do you still have kubelet log around this happened? There should be some log mentioning 
operationExecutor.UnmountDevice started ==> unpublish 
operationExecutor.UnmountDevice started ==> unstage

**Comment by travisghansen** [comment]
I'm just shutting down for the day but I can reproduce this behavior 100%. I'll gather logs in a few hours and send them.

I am however certain kubelet was not restarted during the timeframe.

**Comment by travisghansen** [comment]
OK, think I've found part of the issue. Still not sure why there's a difference in behavior between 1.17 and 1.18 but here's the error 1.18 is giving..

```
E0915 02:54:33.535434   18446 nestedpendingoperations.go:301] Operation for "{volumeName:kubernetes.io/csi/org.democratic-csi.nfs-client^pvc-b768fbb2-5f1f-4093-8de7-b7b9c97906a4 podName: nodeName:}" failed. No retries permitted until 2020-09-15 02:56:35.535298242 +0000 UTC m=+959.311434749 (durationBeforeRetry 2m2s). Error: "GetDeviceMountRefs check failed for volume \"pvc-b768fbb2-5f1f-4093-8de7-b7b9c97906a4\" (UniqueName: \"kubernetes.io/csi/org.democratic-csi.nfs-client^pvc-b768fbb2-5f1f-4093-8de7-b7b9c97906a4\") on node \"node01\" : The device mount path \"/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-b768fbb2-5f1f-4093-8de7-b7b9c97906a4/globalmount\" is still mounted by other references [/vault /host-iscsi/vault /host-iscsi/var/lib/kubelet/pods/687fe90c-e5b7-4b81-ba98-24a206088cfa/volume-subpaths/home-assistant/home-assistant/0 /host-iscsi/var/lib/kubelet/pods/8da38591-5416-4ef1-b17b-689ec05087bd/volume-subpaths/bitwarden/bitwarden/0
...whole bunch of other mounts
/var/lib/docker/overlay2/6dc2ebb666ff46de7f65c1aba55e3b0cec6efe0dd06b2ee2aa53a42f9eda5ca2/merged/host-iscsi/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-b2d3ced9-f556-45c1-ae75-235bb6a1f0c3/globalmount
]
```

Did the detection for this become more strict in 1.18?

Essentially I have a scenario where my nodes have the 'root' of the nfs export mounted on all the nodes (outside k8s). This is what you see as `/vault`. Is kubelet somehow detecting the same host/share (not the same dir/subdir however) and thinking it's not unmount...and this is somehow blocking the unstage from happening when appropriate?

I'll do some more digging/testing with the other subdrivers and see if it's specific to how I implemented/deployed the `nfs-client` configuration.

**Comment by travisghansen** [comment]
OK, I'm near certain this has something to do with the error message above as I've tried the other sub-drivers and they don't exhibit the behavior. They also don't have overlapping mounts of effectively the same export.

I'm guessing something changed which made the above checks more strict which is resulting in the behavior seen..we should probably discuss details further and I'll see if it's possible to do different deployment options which mitigate the issue in the mean time and gather more info along the way.

**Comment by jingxu97** [comment]
I checked the code around this part, there is no recent changes, from what I can see. The reason it failed is because when triggering UnmouontDevice, it first checks whether the globalmount path (/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-b768fbb2-5f1f-4093-8de7-b7b9c97906a4/globalmount) is still referenced by other mounts. If yes, it will abort the operation. In you case, there are a number of other mount points reference it. (/vault /host-iscsi/vault /host-iscsi/var/lib/kubelet/pods/687fe90c-e5b7-4b81-ba98-24a206088cfa/volume-subpaths/home-assistant/home-assistant/0 /host-iscsi/var/lib/kubelet/pods/8da38591-5416-4ef1-b17b-689ec05087bd/volume-subpaths/bitwarden/bitwarden/0
...whole bunch of other mounts ...)

Do you have multiple pods using the same volume? It looks like you have at least two pods 687fe90c-e5b7-4b81-ba98-24a206088cfa/  8da38591-5416-4ef1-b17b-689ec05087bd use the global mounts. From kubelet log you can verify what are those two pods.

**Comment by travisghansen** [comment]
After lengthy discussion on slack it was determined this is related host path mounts:

Quoting @msau42 

```
I've seen an issue where a hostpath mount on something like "/" by a privileged container causes it to keep a mount reference on any mount underneath it. I'm not sure if that is the issue we're seeing here
...
the problem isn't in kubelet. I think it's either in the container runtime or kernel
...
i'm not aware of one. we ran into this internally but we resolved it by getting rid of that hostpath mount
```

In short in my case kubelet run as a container (using `rke`) and that container is mounted with various paths from the host, 1 of which is a/the same nfs server that's being used by the provisioner (although the provisioner is using/mounting deeper subdirs).

It's probably best to determine where the true bug is and address it at whatever level is necessary.
