### ISSUE TITLE
API request content, including pod template env data, are included in API responses

### ISSUE THREAD

**Issue by nikutelusuiphone** [kubernetes/kubernetes#94787]
**What happened**:
Kubernetes api server is returning sensitive data (passwords/secrets) when create/update api fails (Bad request or any other failures) for any pod/deployment and few more resources ?

**What you expected to happen**:
Api server should scrub any sensitive data before returning the response to the client.

**How to reproduce it (as minimally and precisely as possible)**:
While creating a pod/deployment .. add passwords/secrets in the container 'env' and make the template invalid and it returns the passwords/secrets in the api response back.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): Any version
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by liggitt** [comment]
> add passwords/secrets in the container 'env' and make the template invalid

Is the request to not include any of the input data in the server response? A successful create request echoes the input object as the response object. An actor that has access to the request/response already has the content being included in the object.

**Comment by nikutelusuiphone** [comment]
@liggitt 
We have a logging framework that logs all of the api errors and we are observing a lot of sensitive information in the api logs including database passwords, tokens, secrets. I understand user is entering the data and is already aware of what is being returned but it is not the case with our logging framework where different people have access to it.

We are trying to see if the api-server itself can redact the sensitive information. It is enough to say 'pod.template.container.specificField' is invalid instead of echoing the entire template with sensitive data.

**Comment by liggitt** [comment]
Providing details about the invalid values is desired in non-sensitive scenarios, especially when the invalid nature occurs because of a mismatch between how the client thinks it is sending the data and the server thinks it is receiving it.

No fields in a pod / container / pod template spec are considered sensitive. See the following references for the recommended methods for injecting sensitive values into container environment variables, parameters, or files:

* https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-environment-variables
* https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-files-from-a-pod

In contrast, when validating Secret API objects, only the key of the data map that is problematic is included in the error:

https://github.com/kubernetes/kubernetes/blob/release-1.19/pkg/apis/core/validation/validation.go#L5147-L5155

**Comment by nikutelusuiphone** [comment]
Below is a sample log entry (redacted).  This clearly is a bad way to include secrets in the template and some of our new team members are still doing this perhaps to test out a scenario quickly(not a valid reason still) or not knowing about Secret API objects. Our log is retained for a while and this makes it even more difficult to constantly scrub all of the old values. 

Is it possible to extend the same functionality of Secret API objects (only returning key of the env map) to 'Env' as well ??

-------
Containers: []core.Container{{Name: \"CONTAINER_NAME\", Image: \"CONTAINER_IMAGE\", Ports: []core.ContainerPort{{ContainerPort: 5031, Protocol: \"TCP\"}}, Env: []core.EnvVar{{Name: \"DB_USER\", Value: \"**SECRET_VALUE**\"}, {Name: \"**DB_PASSWORD**\", Value: \"VALUE\"}, {Name: \"**DB_ROOT_PASSWORD**\", Value: \"VALUE\"}, {Name: \"DB_ROOT_USER\", Value: \"VALUE\"}, {Name: \"DB_URL\", Value: \"**CONNECTION_URL**\"}}

**Comment by liggitt** [comment]
Omitting non-confidential field values from API errors responses because confidential information _might_ be placed into them inappropriately and the error _might_ be logged doesn't seem very principled. Data specified in pod specs can be logged in other locations as well, and masking it in once place gives a false sense of security that those values are protected when they are not.

**Comment by nikutelusuiphone** [comment]
Thanks @liggitt
