### ISSUE TITLE
Inject Node Info to Pod

### ISSUE THREAD

**Issue by xujihui1985** [kubernetes/kubernetes#94790]
**What would you like to be added**:
Inject label on Node to Pod
**Why is this needed**:
we may have different standards node in one cluster, so when we deploy pod on these node, the qps/tps they can handle are different, I want to expose node info to the pod, so that when I start pod, I know that pod are on the machine with low capacity, then I can adjust the weight of the service that this pod publish.

**Comment by yashvardhan-kukreja** [comment]
would like to pick this up :)

**Comment by yashvardhan-kukreja** [comment]
```
► kubectl describe pod loki-0
Name:           loki-0
Namespace:      loki-playground
Priority:       0
Node:           ip-10-2-181-219.us-west-2.compute.internal
Start Time:     Tue, 15 Sep 2020 09:57:05 +0530
Labels:         app=loki
                name=loki
                release=loki
                statefulset.kubernetes.io/pod-name=loki-0
```

@xujihui1985 if you look at the above example of one of my pods, you can see that the output of `kubectl describe pod loki-0` gives you the name of the node on which that pod is deployed.

**So, do you want the labels of that node to be displayed as well?**

**Comment by xujihui1985** [comment]
@yashvardhan-kukreja thanks for reply, yes I would like to have node labels on the pod so that I would inject the label as environment variable into container, application then could read the env and adjust weight of service

**Comment by yashvardhan-kukreja** [comment]
Got it @xujihui1985  !
I'll hop onto implementing this :)
So, just so that we are on the same page, (at the risk of repeating myself here 🙈 ,) so, considering the pod `loki-0` is deployed on a node with the labels `type=t2.micro`, `region=us-east-1` and `ebs-optimized=true` ,
then, here's how the output of `kubectl describe pod loki-0` would look like, after I implement this feature...

```
► kubectl describe pod loki-0
Name:           loki-0
Namespace:      loki-playground
Priority:       0
Node:           ip-10-2-181-219.us-west-2.compute.internal
Node-Labels:    type=t2.micro
                region=us-east-1
                ebs-optimized=true
Start Time:     Tue, 15 Sep 2020 09:57:05 +0530
Labels:         app=loki
                name=loki
                release=loki
                statefulset.kubernetes.io/pod-name=loki-0
```

**Comment by xujihui1985** [comment]
@yashvardhan-kukreja  yes, that would be nice, and there may be some prefix to filter the label that would attach to pod while we may not want to expose all of the node labels to pod

**Comment by yashvardhan-kukreja** [comment]
@xujihui1985 
1).it would be great if u can please show with an example, exactly what do u mean when u said, "some prefix to filter the label that would attach to pod while we may not want to expose all of the node labels to pod". (i suppose i get it but I am not finding this prefix filter of most use, so I might be not understanding your idea completely, thats why an example would be great)

2). Also, what do u exactly mean "exposing node labels to pods". Do you want the containers sitting inside the pod to know about the labels of the node they are residing in? Or, do u want the node labels to be just displayed under `kubectl pod describe` and nothing else? Or somethijt else?
Please provide clarity on that as well. An example would be great here too :)

**Comment by xujihui1985** [comment]
@yashvardhan-kukreja 
1. for example only lables like io.kubenetes.node/ebs-optimized=true can be expose to node
2. yes as long as we have these labels on pod we can use downwardsapi to inject these label to env of the container, so that application in the container can aware of these information

**Comment by yashvardhan-kukreja** [comment]
alright @xujihui1985. Thanks for the heads up. I'll hop onto implementing this.

**Comment by yashvardhan-kukreja** [comment]
sig/api-machinery

**Comment by yashvardhan-kukreja** [comment]
So, let me give a heads up regarding the solution...

_(@xujihui1985 you might want to look at this because it clearly shows how would this functionality be used. So, you can confirm if you like it or not)._

So, the problem here is to propagate Node Labels as a part of downwards api.
Now, if we look at the documentation of it, we can clearly see that the data which can be propagated from pod to containers using downwards API **has to be available as a part of Pod Spec.**

So, the solution was clear. It was to add support for new fields under Pod Spec.
These are the fields which I propose to add under the `type PodSpec`:
- `ExposedNodeLabelsSelectors []string` - This will be input-ed as a part of `--exposed-node-labels-selectors` So, this is a list of selectors and filters on the basis of which, kubernetes will determine the exact subset of labels (of the node on which pod is being scheduled) belonging to the node, which should be exposed as a part of downwards api. Reason for adding a filter and not just putting all node labels directly to the pod is because at times, the user/developer might not want to expose all of the node-labels to the pod, hence, they can provide these selectors on the basis of which they can expose only specific labels. 
For example, a node has the following labels, `app=frontend`, `hardware=low`, `server=node`. Now, say, the developer only wants to expose the `app` and `server` label to the pod (and hence, the underlying containers via downwards api), then, the developer can enter the following command to do so:
```sh
kubectl run sample-pod --image <image name> --exposed-node-labels-selectors=app --exposed-node-labels-selectors=server
```

- `ExposedNodeLabels map[string]string` - These will be the node labels which will be exposed to the pod. By this I mean, in the above example, the dev was trying to fetch out `app` and `server` labels from the node to the pod right! So, ExposedNodeLabels would be a hashmaps of those node labels with their values. So, this is the place from where the developer can pass his node's labels from the pod to the container by doing the following:

```yaml
      env:
        - name: MY_APP
          valueFrom:
            fieldRef:
              fieldPath: spec.exposedNodeLabels.app
        - name: MY_SERVER
          valueFrom:
            fieldRef:
              fieldPath: spec.exposedNodeLabels.server
```

**Comment by yashvardhan-kukreja** [comment]
Now, clearly, this is a much big of a task.
Because here, we are legit updating the schema of Pod Spec.
Meaning, I suspect that we'd have to deal with the following things:
- Updating the api-machinery's code so as to make sure that it even considers the `ExposedNodeLabelsSelectors` also while orchestrating the Pod Creation's mechanism.
- Updating the `kubelet`'s (or maybe `scheduling`'s too although I don't think so) code to involve the logic of figuring out the `ExposedNodeLabels` with respect to the selectors and store those node-labels under the Pod Spec when the Pod is created finally.

So, I wanted to tag the folks of /sig api-machinery and /sig kubelet to have a look at this and give any suggestions, if need be.

Meanwhile, I am attaching my PR which is work under progress as of now for this issue.

**Comment by yashvardhan-kukreja** [comment]
So, let me give a heads up regarding the solution...

_(@xujihui1985 you might want to look at this because it clearly shows how would this functionality be used. So, you can confirm if you like it or not)._

So, the problem here is to propagate Node Labels as a part of downwards api.
Now, if we look at the documentation of it, we can clearly see that the data which can be propagated from pod to containers using downwards API **has to be available as a part of Pod Spec.**

So, the solution was clear. It was to add support for new fields under Pod Spec.
These are the fields which I propose to add under the `type PodSpec`:
- `ExposedNodeLabelsSelectors []string` - This will be input-ed as a part of `--exposed-node-labels-selectors` So, this is a list of selectors and filters on the basis of which, kubernetes will determine the exact subset of labels (of the node on which pod is being scheduled) belonging to the node, which should be exposed as a part of downwards api. Reason for adding a filter and not just putting all node labels directly to the pod is because at times, the user/developer might not want to expose all of the node-labels to the pod, hence, they can provide these selectors on the basis of which they can expose only specific labels. 
For example, a node has the following labels, `app=frontend`, `hardware=low`, `server=node`. Now, say, the developer only wants to expose the `app` and `server` label to the pod (and hence, the underlying containers via downwards api), then, the developer can enter the following command to do so:
```sh
kubectl run sample-pod --image <image name> --exposed-node-labels-selectors=app --exposed-node-labels-selectors=server
```

- `ExposedNodeLabels map[string]string` - These will be the node labels which will be exposed to the pod. By this I mean, in the above example, the dev was trying to fetch out `app` and `server` labels from the node to the pod right! So, ExposedNodeLabels would be a hashmaps of those node labels with their values. So, this is the place from where the developer can pass his node's labels from the pod to the container by doing the following:

```yaml
      env:
        - name: MY_APP
          valueFrom:
            fieldRef:
              fieldPath: spec.exposedNodeLabels.app
        - name: MY_SERVER
          valueFrom:
            fieldRef:
              fieldPath: spec.exposedNodeLabels.server
```

**Comment by yashvardhan-kukreja** [comment]
Now, clearly, this is a much big of a task.
Because here, we are legit updating the schema of Pod Spec.
Meaning, I suspect that we'd have to deal with the following things:
- Updating the api-machinery's code so as to make sure that it even considers the `ExposedNodeLabelsSelectors` also while orchestrating the Pod Creation's mechanism.
- Updating the `kubelet`'s (or maybe `scheduling`'s too although I don't think so) code to involve the logic of figuring out the `ExposedNodeLabels` with respect to the selectors and store those node-labels under the Pod Spec when the Pod is created finally.

So, I wanted to tag the folks of /sig api-machinery and /sig kubelet to have a look at this and give any suggestions, if need be.

Meanwhile, I am attaching my PR which is work under progress as of now for this issue.
