### ISSUE TITLE
Replicasset is not consider image tag for existing matched labeled pods.  

### ISSUE THREAD

**Issue by mukulk2020** [kubernetes/kubernetes#94849]
I have create a pod (image nginx , label app=nginx). It created successfully and showing total 1 pod in cluster .
apiVersion: v1
kind: Pod
metadata:
  name: nginx01
  labels:
    app: nginx	
spec:
  containers:
  - name: nginx
    image: nginx

Ran : > kubectl get pods -o wide
NAME      READY   STATUS    RESTARTS   AGE   IP            NODE                 NOMINATED NODE   READINESS GATES
nginx01   1/1     Running   0          41s   10.244.0.27   kind-control-plane   <none>           <none>

Then I create a replicaset that create 2 nginx:1.15 pod with label app=nginx. After this total 2 pod is showing in the cluster one is that using nginx:latest and other is nginx:1.15. ideally replicaset should display 2 pods that have nginx:1.15 image with label app=nginx. And total 3 pods should be shown but that not happened. This is wrong ..
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs01
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      # Run the nginx image
      - name: nginx
        image: nginx:1.15
![image](https://user-images.githubusercontent.com/61539926/93425897-9387db00-f8d8-11ea-9ea5-963227486eb7.png)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**rs treated nginx01 pod is the part of rs ...that is not correct bz image/tag is different .**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by neolit123** [comment]
hi, what is the output for this:

> Kubernetes version (use kubectl version):

/sig apps
/priority needs-more-evidence

**Comment by yashvardhan-kukreja** [comment]
@neolit123 please correct me if I am wrong here. 
I read in the kubernetes documentation that replicaset (basically) identifies replicas/pods on the basis of the labels only.
And I belive due to this, @mukulk2020  is facing this concern.

Although the pod corresponding to nginx:1.15 and pod corresponding to nginx:latest are different but still they are marked with the same labels which is `app: nginx` and replicaset only looks for pods with that label (app: nginx) irrespective of what container is actually running inside the pod. Hence, when @mukulk2020 started the replicaset, then the replicaset saw that already a pod with the label `app: nginx` is running (without caring about what exact container is running inside it) and hence, to maintain a total of 2 such replicas/pods in the cluster, it just created 1 more pod/replica (according to the template defined in its manifest).

I have mentioned about the same in a slightly similar issue [ #94851 ]
