### ISSUE TITLE
Fix stderr usage in `kubectl debug`

### ISSUE THREAD

**Issue by verb** [kubernetes/kubernetes#94856]
Feedback in https://github.com/kubernetes/kubernetes/pull/90094#discussion_r443655372 identified that `kubectl` commands should only print errors to stderr. The command currently prints an information "Defaulting debug container name" message to stderr.

These messages should instead print to Stdout as long as `--quiet` is not set.

/sig cli
/kind cleanup

**Comment by dinever** [comment]
Hi @verb, I can work on this if it's okay

**Comment by verb** [comment]
@dinever sounds great, thanks!

/assign @dinever

**Comment by dinever** [comment]
Hi @verb, it looks like the issue has been fixed in #92310 (https://github.com/kubernetes/kubernetes/commit/7e63cc8b9d592abbb8a659205555e67b57080837#diff-70d7d07e532a36e6345494a79fa2fb13L429-R533)

https://github.com/kubernetes/kubernetes/blob/660e1e4969ffd8d5e4b24939e646081233e130a6/staging/src/k8s.io/kubectl/pkg/cmd/debug/debug.go#L534-L536

I don't see any other inappropriate `stderr` usage in the package. Should this be closed?

**Comment by verb** [comment]
@dinever oh no! You're right: I misremembered that we left that unsolved.

Thanks for tracking it down. Sorry it was a waste. 😞
