### ISSUE TITLE
Remove version skew and annotation support for seccomp (v1.23)

### ISSUE THREAD

**Issue by saschagrunert** [kubernetes/kubernetes#95171]
This is a placeholder issue to remove support for the version skew handling as well as the deprecated seccomp annotations.

The [KEP](https://github.com/kubernetes/enhancements/blob/master/keps/sig-node/20190717-seccomp-ga.md) states:

> Since we support up to 2 minor releases of version skew between the master and node, annotations must continue to be supported and backfilled for at least 2 versions passed the initial implementation. However, we can decide to extend support farther to reduce breakage. If this feature is implemented in v1.19, I propose v1.23 as a target for removal of the old behavior.
…
> To raise awareness of annotation usage (in case of old automation), a warning mechanism will be used to highlight that support will be dropped in v1.23. The mechanisms being considerated are audit annotations, annotations on the object, events, or a warning as described in KEP #1693.

Beside that, the kubelet `--seccomp-profile-root` has to be removed in v1.23, too:

> The existing kubelet (alpha) flag --seccomp-profile-root allows for seccomp root path configuration. This flag will be deprecated as of v1.19, and will be removed on v1.23. The seccomp root path will then be derived from the kubelet root path, which is defined by --root-dir. The current default value is <root-dir>/seccomp. This KEP will make the default behavior the only behavior.

/milestone v1.23
/sig node

cc @tallclair @pjbgf

**Comment by saschagrunert** [comment]
/priority important-longterm

_TODO: Add the milestone once it exists_

**Comment by saschagrunert** [comment]
Waiting for the 1.23 cycle
/remove-lifecycle stale

**Comment by saschagrunert** [comment]
/remove-lifecycle stale

I can work on this in v1.23

**Comment by alain-baxter** [comment]
@saschagrunert once this version skew for seccomp has been remove, and annotation based seccomp configuration is no longer functional, will the annotations be allowed to exist on a pod?

**Comment by saschagrunert** [comment]
> @saschagrunert once this version skew for seccomp has been remove, and annotation based seccomp configuration is no longer functional, will the annotations be allowed to exist on a pod?

Yes, to not break existing deployments on upgrade.

**Comment by alain-baxter** [comment]
> > @saschagrunert once this version skew for seccomp has been remove, and annotation based seccomp configuration is no longer functional, will the annotations be allowed to exist on a pod?
> 
> Yes, to not break existing deployments on upgrade.

Thanks for the reply

Allowing the annotations does create confusing pod configuration for any processes and/or end users that are checking resource state for security compliance. 

If the workload made it through the skew period without being remediated for deprecation then seccomp will no longer be configured properly after upgrade. This could cause harder to detect issues with workloads than if the pods failed to deploy due to invalid annotations. The workload might even function normally since the default seccomp profile is likely to be more relaxed than before, however it's security posture could have been lessened causing possible compliance infractions.

I know it's always hard to tell which way to go when deprecating functionality though so thanks for letting me know how it'll work for this and I'll try to compensate for this within the policy.
