### ISSUE TITLE
Missing cadvisor machine metrics (v1.19)

### ISSUE THREAD

**Issue by erikwilson** [kubernetes/kubernetes#95204]
**What happened**:
prometheus cadvisor machine metrics from kubelet are missing
```
# kubectl get --raw "/api/v1/nodes/NODE_NAME/proxy/metrics/cadvisor" | grep -i machine_cpu_cores
```

**What you expected to happen**:
```
# kubectl get --raw "/api/v1/nodes/NODE_NAME/proxy/metrics/cadvisor" | grep -i machine_cpu_cores
# HELP machine_cpu_cores Number of CPU cores on the machine.
# TYPE machine_cpu_cores gauge
machine_cpu_cores 4
```

**How to reproduce it (as minimally and precisely as possible)**:
install k8s 1.19, compare behavior to k8s <1.19

**Anything else we need to know?**:
Looks like missing call to `NewPrometheusMachineCollector` in `pkg/kubelet/server/server.go`, machine metrics collection was split out in cadvisor 0.37

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2+k3s1", GitCommit:"d38505b124c92bffd45f6e0654adb9371cae9610", GitTreeState:"clean", BuildDate:"2020-09-29T20:53:06Z", GoVersion:"go1.15.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2+k3s1", GitCommit:"d38505b124c92bffd45f6e0654adb9371cae9610", GitTreeState:"clean", BuildDate:"2020-09-29T20:53:06Z", GoVersion:"go1.15.1", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by erikwilson** [comment]
/sig node
(hope that's the correct sig :)

**Comment by bboreham** [comment]
Suggest `kube_node_status_capacity{resource="cpu"}` from [kube-state-metrics](https://github.com/kubernetes/kube-state-metrics/blob/master/docs/node-metrics.md) as an alternative (declared as "stable").

**Comment by lingsamuel** [comment]
Related PR https://github.com/google/cadvisor/pull/2444

**Comment by dongwangdw** [comment]
Multiple queries is invalide now. Is there any workaroud for this? Please help. Thanks.

**Comment by bboreham** [comment]
@dongwangdw if you run `kube-state-metrics` see https://github.com/kubernetes/kubernetes/issues/95204#issuecomment-719445180 for an alternative metric.

**Comment by rashmichandrashekar** [comment]
+1 on the issue. This issue has caused the node metric collection for AKS monitoring to be broken which also impacts alerting.

**Comment by zbindenren** [comment]
Exposed metrics are a kind of API and should not be removed without warning.

**Comment by VonRehberg** [comment]
any news, when this will be fixed?

**Comment by ehashman** [comment]
> Exposed metrics are a kind of an API and should not be removed without warning.

It is not possible to have a metric available without exposing it. To provide stability information on metrics, similar to APIs, you might want to read up on the [Kubernetes metric stability framework](https://github.com/kubernetes/enhancements/blob/master/keps/sig-instrumentation/20190404-kubernetes-control-plane-metrics-stability.md). There currently are no metrics in Kubernetes itself that are considered stable, but SIG Instrumentation hopes to be selecting some for the 1.21 release.

This particular issue seems like an unintended bug as opposed to an intentional deprecation.

Suspect this issue got lost in SIG Node's backlog. I'll put it on the agenda for the next SIG Instrumentation meeting.


/sig instrumentation

**Comment by ehashman** [comment]
Backports in https://github.com/kubernetes/kubernetes/pull/97691 and https://github.com/kubernetes/kubernetes/pull/97692
