### ISSUE TITLE
DualStack: Ip family of status.podIP can be wrong depending on CNI-plugin

### ISSUE THREAD

**Issue by uablrek** [kubernetes/kubernetes#95251]
### Ip family of status.podIP can be wrong depending on CNI-plugin

**What happened**:

The `status.podIP` is taken from `status.podIPs[0]` without regard for the main family of the cluster. No warning or error is given if `status.podIP` gets the wrong family.

**What you expected to happen**:

That `status.podIP` is taken from the "main" ip family, or at the very least the POD is not started and an error is given if it's not.

**How to reproduce it (as minimally and precisely as possible)**:

Use the `bridge` CNI-plugin and `host-local` ipam. Use a single node cluster to avoid that `host-local` assign the same address to PODs in different nodes. This _may_ be CRI-plugin dependent, I use `cri-o/1.18.3`.

```
$ cat /etc/cni/net.d/10-bridge.conf 
{
  "cniVersion": "0.4.0",
  "name": "cni-x",
  "type": "bridge",
  "bridge": "cbr0",
  "isDefaultGateway": true,
  "hairpinMode": true,
  "ipam": {
    "type": "host-local",
    "ranges": [
      [ { "subnet": "1100::100/120" } ],
      [ { "subnet": "11.0.1.0/24" } ]
    ]
  }
}
$ ls /opt/cni/bin/
bridge*      host-local*    loopback*
```

The PODs are assigned dual addresses which has been supported since v1.9. Note the order; IPv6 first.

In a dual-stack _or a single-stack_ cluster with main family IPv4 `status.podIP` will get an IPv6 address even if the main family is IPv4;

```
$ kubectl get pod alpine-daemonset-4t6w5 -o json | jq .status.podIP
"1100::102"
```

**Anything else we need to know?**:

First, note that this is **not** a dual-stack problem. `status.podIP` may get the wrong family in a single-stack cluster if the PODs has dual addresses. The bug may however have been introduced with the dual-stack support, before `status.podIPs` K8s may have selected the correct family, I have not checked that.

This is reported and discussed in https://github.com/kubernetes/kubernetes/issues/94505. There it is considered as a CNI-plugin problem, the CNI-plugin must present addresses in the order K8s wants them. Problem is that CNI-plugins doesn't know this.

The addresses takes the path;
```
CNI-plugin -> CRI-plugin -> kubelet -> API-server
```
The problem can be addressed in either of these places.

The current situation is that the full responsibility lies on the `CNI-plugin`, it must send the addresses in the "correct order". This is not the best place. The CNI-plugins are not a K8s-only thing and to require that a "prefered-family" or something similar must be supported by CNI-plugins to be "Kubernetes compliant" should be avoided.

The CRI-plugin *is* a K8s-only thing and a "prefered-family" can be introduced so the CRI-plugin can sort the address array before sending it to `kubelet`. This is however undesirable since it adds a configuration complexity, it put a responsibility on the user or installation tool to configure the "prefered-family" to all CNI-plugins now and in the future.

The best is to handle this in K8s itself where the "main" family is known.
```
    // IP addresses allocated to the pod. This list
    // is inclusive, i.e. it includes the default IP address stored in the
    // "PodIP" field, and this default IP address must be recorded in the
    // 0th entry (PodIPs[0]) of the slice. The list is empty if no IPs have
    // been allocated yet.
    PodIPs []PodIP `json:"podIPs,omitempty" protobuf:"bytes,6,opt,name=podIPs"`
```

Is this really necessary? All communication works even if `podIPs[0]` is not of the main family. EndpointSlices seem to get this right regardless of order. Endpoint on the other hand seem to take the (old) podIP. So perhaps;
```
The "PodIP" field is set to the first address in podIPs that matches the main ip-family.
```
is sufficient?

If `podIP` *really must* be `podIPs[0]`, then K8s should sort the array so `podIPs[0]` belongs to the main family.

The problem exist on all supported K8s versions and on "master".

#### Current situation for dual-stack supporting CNI-plugins

If installed in the default way the situation is;

* Calico *always* send IPv4 first
* Cilum *always* send IPv6 first

I don't think you can control the order, but I have not asked.

**Environment**:
- Kubernetes versions: v1.17.12, v1.18.9, v1.19.2, v1.20.0-alpha.1, master v1.20.0-alpha.1.257+112dbd55860e60
- Cloud provider or hardware configuration: None
- OS (e.g: `cat /etc/os-release`): xcluster
- Kernel: linux-5.8.1
- Install tools: None
- Network plugin and version: bridge, host-local v0.8.7
- Others: CRI-plugin: cri-o 1.18.3

**Comment by uablrek** [comment]
For the record;
all communication via services works perfectly fine even if the order in `podIPs` is "faulty" with `podIPs[0]` _not_ belonging to the main family in k8s > v1.18.8.

**Comment by aojea** [comment]
> For the record;
> all communication via services works perfectly fine even if the order in `podIPs` is "faulty" with `podIPs[0]` _not_ belonging to the main family in k8s > v1.18.8.

because the endpoint checks that the ips matches the service ip family,
https://github.com/kubernetes/kubernetes/blob/112dbd55860e600af525cedc255f2664e3f286aa/pkg/controller/endpoint/endpoints_controller.go#L217-L235

**Comment by liggitt** [comment]
I think this is a duplicate of https://github.com/kubernetes/kubernetes/issues/94505

CNI plugins must report multiple IPs in the order expected by the cluster. The podIPs[0] == podIP requirement is for backwards compatibility with clients that do not read podIPs. Server-side reordering causes problems with clients that continually write/reconcile until the server list exactly matches their local list.

**Comment by uablrek** [comment]
> First, note that this is not a dual-stack problem.

The problem exist in single-stack K8s clusters when PODs has dual addresses (supported since K8s v1.9, i.e way before K8s dual-stack which came in v1.16)

And this issue is not a duplicate of #94505. That issue is about a problem when the CNI-plugin uses the "correct" order. This issue is about the fact that K8s puts undocumented requirements on the CNI-plugins. There is no requirement on order in the [CNI spec](https://github.com/containernetworking/cni/blob/master/SPEC.md). And since this requirement is undocumented it is not supported for instance by cilium and calico.

The `podIP` itself should be the requirement is for backwards compatibility with clients that do not read podIPs. Since they doesn't read podIPs the value of `podIPs[0]` should not matter to them, or?

I think this should be handled in K8s, but _if_ the responsibility is pushed downhill to the CNI-plugins then two things _must_ be done in K8s;

1. The extra requirement on "Kubernetes compliant" CNI-plugins (outside the CNI spec) _must be formally documented_ and communicated to the CNI-plugin providers.
2. If a "faulty" CNI-plugin accidently put's an IP-address of the "wrong" family in the first item then K8s must report an error and not start the POD.

Please note again that this is not a K8s dual-stack problem. In a single-stack IPv6 K8s cluster the CNI-plugins must provide an IPv6 address first in the list.

**Comment by liggitt** [comment]
> The `podIP` itself should be the requirement is for backwards compatibility with clients that do not read podIPs. Since they doesn't read podIPs the value of `podIPs[0]` should not matter to them, or?

The reason podIP must match podIPs[0] is related to **updates** to an existing object by an old client. See https://github.com/kubernetes/kubernetes/pull/88505 for a related problem when this was not done.

* An old client updated an existing object, setting only the podIP field (which is the only one it was aware of).
* The API server needed to detect that and populate the podIPs field correctly for new clients to read.
* The detection is based on the mismatch between podIP and podIPs[0], and the server responds by populating `podIPs=[podIP]`. That means that new clients (aware of both fields) must set podIP and podIPs[0] to match.

**Comment by danwinship** [comment]
> The `status.podIP` is taken from `status.podIPs[0]` without regard for the main family of the cluster.

So this is weird, but... dual-stack clusters do not actually have a "main family", because decisions about IP families are made by multiple components, and kubernetes clusters do not have a single source of configuration truth that applies to all components. So it is explicitly allowed to have kube-apiserver default to IPv4-primary IPv6-secondary for services, and have your network plugin default to IPv6-primary IPv4-secondary for pod IPs, and to have some nodes have a single IPv4 address and some have a single IPv6 address and some have dual-stack addresses. It's not super clear why you'd _want_ to do that, but we decided we had to allow it, simply because there's no easy way to prevent it.

Of course in scenarios where the entire cluster is being installed/deployed by a single tool, one would expect that tool to configure all of the components in a consistent way.

> This is reported and discussed in #94505. There it is considered as a CNI-plugin problem, the CNI-plugin must present addresses in the order K8s wants them. Problem is that CNI-plugins doesn't know this.

There is no "order K8s wants them". _Kubernetes_ doesn't want the addresses in any order. _You_ want them in a particular order. Therefore _you_ must configure the CNI plugin to return them in that order. Eg, in the example above, you should reverse the two `ranges` in the `ipam` config.

> If installed in the default way the situation is;
> 
>   * Calico _always_ send IPv4 first
>   * Cilum _always_ send IPv6 first
> 
> I don't think you can control the order, but I have not asked.

Kubernetes's interpretation of this is that if Cilium sends the IPv6 address first, then it is telling Kubernetes that Kubernetes ought to prefer the IPv6 one.

It appears that the CNI spec doesn't actually say that though... It doesn't seem to say anything about the ordering of multiple IPs... So maybe that should be clarified. If the CNI authors feel that the ordering of returned addresses is _not_ meaningful then perhaps kubelet's behavior could be changed.

**Comment by danwinship** [comment]
> Kubernetes's interpretation of this is that if Cilium sends the IPv6 address first, then it is telling Kubernetes that Kubernetes ought to prefer the IPv6 one.
> 
> It appears that the CNI spec doesn't actually say that though... It doesn't seem to say anything about the ordering of multiple IPs... So maybe that should be clarified. If the CNI authors feel that the ordering of returned addresses is _not_ meaningful then perhaps kubelet's behavior could be changed.

@bboreham @dcbw @squeed Thoughts on this?

**Comment by squeed** [comment]
CNI doesn't make any statement about ordering of IPs. It **definitely** doesn't have any notion of a "primary IP".

It seems that containerd itself does have some [glue code to prefer v4](https://github.com/containerd/containerd/blob/88f089354009d3df6d5556d59ce4ce2ac0717106/pkg/cri/server/sandbox_run.go#L466)

**Comment by danwinship** [comment]
> CNI doesn't make any statement about ordering of IPs.

I mean that's literally what I just said :stuck_out_tongue:. The question is more if that is intentional and/or changeable.

It seems strange that the decision about whether to allocate IPv4 and/or IPv6 IPs is left up to the network plugin, with no input from the runtime, but the decision about what to _do_ with IPv4 and/or IPv6 IPs is then left up to the runtime, with no input from the network plugin.

**Comment by uablrek** [comment]
> So this is weird, but... dual-stack clusters do not actually have a "main family"

That is very good an as it should be but...

> In a dual-stack or a single-stack cluster with main family IPv4 status.podIP will get an IPv6 address even if the main family is IPv4;

The quote is from the initial commant. Please note that this is a **single-stack** cluster! And that has a main family even though the PODs have dual addresses.

**Comment by squeed** [comment]
Right; don't comment on issues just before going to bed. Ooops.

I don't think we want to introduce the notion of IP ordering / or preference in to CNI for a few reasons --
* It's a bit of a breaking change, depending on how you read the spec
* It would be awkward to push the "preferred family" from k8s al the way down through to CNI
* It doesn't match how Linux works - interfaces don't have primary IPs (legacy `ifconfig` aside).

So fixing this in the apisever is probably the right place?

BTW, what, exactly, defines a cluster's address family? ClusterCIDR, but that's optional (as is PodCIDR). ServiceCIDR, certainly. Is there an explicit config flag?

**Comment by aojea** [comment]
> So fixing this in the apisever is probably the right place?

kubelet set the status.PodIPs

>  Please note that this is a single-stack cluster! And that has a main family even though the PODs have dual addresses.

In a single-stack cluster you don't have a main family, you only have ONE family

If we don't have PodIPs and only PodIP in a single-stack cluster this will be clearly a configuration problem in the CNI,no?

I personally,  think that this is a configuration problem and that we created it because we pluralised PodIP without a feature gate

**Comment by uablrek** [comment]
> In a single-stack cluster you don't have a main family, you only have ONE family

Yes, and this is how it looks in an **IPv4 single-stack** cluster if the CNI-plugin has been configured for dual addresses on PODs but returns the assigned addresses in the "wrong" order (ipv6 first);
```
$ kubectl version --short
Client Version: v1.19.2
Server Version: v1.19.2
$ kubectl get pod kahttp-b99jz -o wide
NAME           READY   STATUS    RESTARTS   AGE     IP          NODE     NOMINATED NODE   READINESS GATES
kahttp-b99jz   1/1     Running   0          3m50s   1100::502   vm-005   <none>           <none>
```

**Comment by bboreham** [comment]
Why is requesting an IPv6 address for pods in an IPv4 cluster not a configuration error? 

To me it seems a bit like running an ARM image on an AMD64 machine; Kubernetes will go through some motions but will not make it work or tell you what you did wrong.

**Comment by uablrek** [comment]
> Why is requesting an IPv6 address for pods in an IPv4 cluster not a configuration error?

Dual addresses in PODs has been supported from K8s v1.9, i.e. long before K8s dual-stack so that is not a configuration error. In the CNI specification there is nothing about required order for addresses or "prefered family" so it is not a configuration error for the CNI-plugin either.

For K8s functions the order in `podIPs` does not matter. But design of upgrade requires that `podIP == podIPs[0]` see https://github.com/kubernetes/kubernetes/issues/95251#issuecomment-703132440.

Problem is that K8s (kubelet) sets "podIP = podIPs[0]" without checking the family. Here some error should be in place, like "CNI-plugin not compatible with K8s" and the POD should not be started, or better, sort the addresses or remove the `podIP == podIPs[0]` requirement.

This is a K8s problem. CNI-plugins should **not** have to care about order of reported addresses at least not without a CNI specification update.

**Comment by bboreham** [comment]
> > Why is requesting an IPv6 address for pods in an IPv4 cluster not a configuration error?

> Dual addresses in PODs has been supported from K8s v1.9, i.e. long before K8s dual-stack so that is not a configuration error.

This doesn't appear to answer my question.  What is the meaning of an IPv6 pod address in an IPv4 cluster?

**Comment by danwinship** [comment]
> BTW, what, exactly, defines a cluster's address family? ClusterCIDR, but that's optional (as is PodCIDR). ServiceCIDR, certainly. Is there an explicit config flag?

A cluster does not have an address family. Usually it _seems_ like it does but that's just because the administrator has configured all of the individual components in a consistent way. But most components' configuration only affects what _that component_ does (though in some cases that will have knock-on effects).

- kube-controller-manager sets `node.podCIDR(s)` based on its `--cluster-cidr` (assuming `--allocate-node-cidrs` is set)
- The network plugin (indirectly) sets `pod.status.podIP(s)` (which may be affected by kcm's choice of `podCIDR(s)`) based on its own configuration
- Either kubelet or an external cloud provider sets `node.status.addresses`:
  - based on `--node-ip`, if passed, in the non-cloud-provider case
  - based on cloud-provider-specific configuration (or hardcoded defaults) in the cloud case
- kubelet sets `pod.status.hostIP` from `node.status.addresses`
- kube-apiserver sets `service.spec.ClusterIP(s)` based on its `--service-cluster-ip-range`
  - kube-controller-manager creates endpoints, mostly based on the IP families chosen by kube-apiserver, except in the case of headless selectorless services, where it lets the user set endpoints of whatever family it wants, because it doesn't usually know whether the cluster is single or dual stack.
- kube-proxy determines whether rules are actually _created_ for IPv4 and/or IPv6 services, based on the `--bind-address` passed in if the dual stack feature gate is disabled, and unconditionally dual stack if the feature gate is enabled
- the cloud provider determines whether `type: LoadBalancer` services get IPv4 and/or IPv6 IPs, based on cloud-provider-specific config or hardcoded defaults

This... is kind of a mess, but there's no real way to fix it centrally given the way that kubernetes works. But we could add a config option to kubelet to unambiguously specify whether it should act like it's in a SSIPv4/SSIPv6/DSIPv4Primary/DSIPv6Primary cluster, and then make `podIPs` assignment make use of that.

**Comment by squeed** [comment]
> This... is kind of a mess.

Oof. Well. Maybe it makes sense for kubelet to stop setting PodIP, and leave that decision to the apiserver? It could make that decision based on ServiceCIDR, and order the families accordingly?

**Comment by danwinship** [comment]
No, the dual stack KEP even explicitly calls out the fact that that it doesn't work that way:

> It is possible to have a "partially-dual-stack" cluster, with dual-stack pod networking but only a single service CIDR. This means that pods in the cluster will be able to send and receive traffic on both IP families, but services which use the clusterIP or ClusterIPs field will only be able to use the IP family of this flag.

There is no single source of truth for kubernetes cluster config, and thus there is no single truth about whether the cluster is IPv4, IPv6, dual-stack-IPv4-primary, or dual-stack-IPv6-primary. If we want kubelet to impose some policy on PodIPs, then we need to tell it what policy to impose, because it has no entirely-reliable way of determining what policies any other component is imposing.

**Comment by uablrek** [comment]
> If we want kubelet to impose some policy on PodIPs, then we need to tell it what policy to impose, because it has no entirely-reliable way of determining what policies any other component is imposing.

That is still much better than to require this function from the CNI-plugin which is not even K8s and follows a specification.

**Comment by uablrek** [comment]
Please note that the networking e.g services, external access, works fine whatever order `podIPs` are in and whatever value `podIP` has. I have not found any communication problem in K8s >= v1.19 caused by this.

The value of `podIP` seem more "cosmetic". But it looks wrong to see ipv6 addresses of PODs in an ipv4-only cluster (https://github.com/kubernetes/kubernetes/issues/95251#issuecomment-714366699).

The problem seem to be an unfortunate upgrade design that imposed the constraint https://github.com/kubernetes/kubernetes/issues/95251#issuecomment-703132440. If that can some way be relaxed this becomes a no-problem as I see it.

**Comment by khenidak** [comment]
What is the material impact of this behavior?

**Comment by uablrek** [comment]
> What is the material impact of this behavior?

@khenidak https://github.com/kubernetes/kubernetes/issues/95251#issuecomment-714921607

**Comment by khenidak** [comment]
we can not relax `PodIP == PodIPs[0]` because that will break existing clients.

a side note. Using dualstack configured CNI on a none dual stack cluster was pre dualstack hack, if it must remain in use then CNI should only report one IP not two.

**Comment by bboreham** [comment]
@khenidak what's your reasoning to change CNI rather than kubelet?

**Comment by uablrek** [comment]
We can't just put undocumented requirements on the CNI-plugins, they are not part of K8s, they have a formal specification and they have other users beside K8s.

At least K8s must formally document the extra requirements on CNI-plugins that K8s has for the CNI-plugin to be K8s compliant.

**Comment by khenidak** [comment]
As highlighted on the discussion there is no single truth of what clusterIP family is. Also kubelet will have to depend on `node.Spec.PodCIDRs` which is not always used by CNIs. You can have a perfectly functional cluster that does not use PodCIDRs at all (I believe Cilium for example does not use it).

Also I am not saying change CNI. A well configured CNI (single family for single stack cluster) will not have this problem.

**Comment by bboreham** [comment]
> CNI should only report one IP
> I am not saying change CNI

Is the latter statement a retraction of the former?  If not, how can they be reconciled?

**Comment by danwinship** [comment]
He's saying that an administrator deploying a CNI plugin in a single-stack kubernetes cluster ought to configure that CNI plugin to return a single IP address, of the family being used by the kubernetes cluster.

A CNI plugin that does not allow you configure what address families it uses may not be compatible with all kubernetes clusters. Eg, a CNI plugin that only supports IPv4 cannot be used as the network plugin in a single-stack IPv6 kubernetes cluster.

**Comment by danwinship** [comment]
So, to sum up:

- Kubelet will always use the first IP returned by the CNI plugin as `pod.Spec.PodIP`, regardless of any other cluster configuration.
- Some CNI plugins, when configured to do dual stack, do not give you a way to configure which IP comes first, meaning kubelet may pick a `pod.Spec.PodIP` that is not the IP family the admin considers the cluster's primary IP family
- In dual-stack clusters, this does not appear to cause any actual problems, other than that the "default" pod IPs shown in "`kubectl get`" may not be the ones the administrator wants
- Nothing in the _current_ kubelet configuration is _supposed to_ indicate whether kubelet should prefer IPv4 or IPv6 pod IPs. It would be possible to add a new config option indicating this, or we could just declare that `--node-ip` should also affect the sorting of pod IPs, because really why _wouldn't_ you want that?
- In single-stack clusters, it has been suggested that the right answer is "don't do that then"; ie, the administrator should configure the CNI plugin to only return a single IP, and if they can't do that, then that's the CNI plugin's problem, not Kubernetes's

**Comment by danwinship** [comment]
oh, and:
- if the CNI plugin returns multiple IPs which are not a dual-stack pair (eg, if it returns 2 IPv4 IPs, or 1 IPv4 IP and 2 IPv6 IPs), then kubelet will fail to update the pod at all, because it assumes it can just copy the IPs returned from CNI into `podIPs`, but the apiserver will only accept `podIPs` if it is either a single IP or a dual-stack pair.

**Comment by uablrek** [comment]
> or we could just declare that --node-ip should also affect the sorting of pod IPs, because really why wouldn't you want that?

That would be excellent! Then it would not be necessary to stop supporting dual-stack pods in a single stack K8s. And Cilium users wanting to upgrade their ipv4-only cluster to dual stack would not suddenly see ipv6 addresses on a `kubectl get pods -o wide`.

**Comment by Jean-Daniel** [comment]
> * In dual-stack clusters, this does not appear to cause any actual problems, other than that the "default" pod IPs shown in "`kubectl get`" may not be the ones the administrator wants

Just for the record, this is an actual problem when trying to deploy rook-ceph. Rook makes strong assumption about PodIP family being the same as `clusterIP` family and just fails to create Ceph cluster when they do not match.

`ceph-mon` are configured to listen only on `PodIP` but the `ceph-mon` advertised addresses are the corresponding service `ClusterIP`.

This result in `ceph-mon` listening only on IPv6 address but being advertised using an IPv4 address.
