### ISSUE TITLE
Need a way to set default container

### ISSUE THREAD

**Issue by zeromsi** [kubernetes/kubernetes#95293]
Need an attribute that holds the name of default container or a flag that states which container is default.

**Comment by dougsland** [comment]
Looks like dup request: https://github.com/kubernetes/kubernetes/issues/61333

**Comment by soltysh** [comment]
Spoke with Doug, but for clarity the approach is to do something similar to https://github.com/kubernetes/kubernetes/pull/87809
but instead of `kubectl.kubernetes.io/default-logs-container` annotation we should introduce more generic like `kubectl.kubernetes.io/default-container` that can be used across the board.

**Comment by pacoxu** [comment]
/cc 
@dougsland @soltysh 

`kubectl.kubernetes.io/default-container` is annotation for kubectl
If we use go client or other cli, which is the default?  kubectl annotation is not that generic.

**Comment by dougsland** [comment]
> /cc
> @dougsland @soltysh
> 
> `kubectl.kubernetes.io/default-container` is annotation for kubectl
> If we use go client or other cli, which is the default? kubectl annotation is not that generic.

My understanding from speaking with @soltysh is use the annotation.

**Comment by dougsland** [comment]
We should close this one and mark as dup of https://github.com/kubernetes/kubernetes/issues/96986 as @pacoxu  already started working on it.

**Comment by dougsland** [comment]
/close
dup of https://github.com/kubernetes/kubernetes/issues/96986
