### ISSUE TITLE
dnf/yum/rpm installation of Kubernetes packages from official repos fails on RHEL 8 systems with FIPS enabled

### ISSUE THREAD

**Issue by vip8439** [kubernetes/kubernetes#95455]
**What happened**: yum/dnf/rpm installation of kubernetes packages from the official repo fail on RHEL 8 machines with FIPS enabled.

yum/dnf installations fail with:
```
package: <kubernetes_package> does not verify: no digest
```

```
rpm --checksig <kubernetes_rpm> 
```
fails with:
<kubernetes_package>: DIGESTS signatures NOT OK

**What you expected to happen**:
yum/dnf/rpm installation complete successfully.

**How to reproduce it (as minimally and precisely as possible)**:
```
fips-mode-setup --enable
systemctl reboot
dnf install <kubernetes package>
```

**Anything else we need to know?**:
Please see attached screenshot which points out a missing Payload SHA256 digest. Red Hat recommends building the RPMs with rpm 4.14 so the entire package payload is signed.  Please see [rpm error "does not verify: no digest"](https://access.redhat.com/solutions/4460971) and [8.0 Release Notes - Section 5.1.4 Software Management: RPM now validates the entire package contents before starting an installation](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/8.0_release_notes/index#software-management)

I assume this would also affect CentOS 8; however, I do not have an instance to test.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.18.4
- Cloud provider or hardware configuration: 
- OS (e.g: `cat /etc/os-release`): RHEL 8.2 (Ootpa)
- Kernel (e.g. `uname -a`): 4.18.0-193.14.3.el8_2.x86_64
- Install tools: kubeadm
- Network plugin and version (if this is a network-related bug): kubernetes-cni 0.8.7-0
- Others:
![Screen Shot 2020-10-09 at 4 08 02 PM](https://user-images.githubusercontent.com/8249963/95638171-f5a7ac00-0a50-11eb-873b-1e0721c1e8de.png)

**Comment by saschagrunert** [comment]
Referenced this issue in an open Slack discussion since I see not much what we can do from a SIG Release perspective: https://kubernetes.slack.com/archives/CJH2GBF7Y/p1612887586202400

**Comment by saschagrunert** [comment]
@vip8439 does this still fail with the latest packages, too?

**Comment by BenTheElder** [comment]
If not: the RPM build system is here, how these are built is controlled there:
https://github.com/kubernetes/release/tree/master/packages/rpm

At SIG releases' discretion my team is happy to run and publish new builds.

**Comment by neolit123** [comment]
/reopen
/remove-lifecycle rotten

This appears to still be a problem
https://github.com/kubernetes/website/issues/27868

**Comment by neolit123** [comment]
> Red Hat recommends building the RPMs with rpm 4.14 so the entire package payload is signed.

Would an rpm build version change be sufficient?
/help
See https://github.com/kubernetes/kubernetes/issues/95455#issuecomment-777902782

**Comment by dougsland** [comment]
> > Red Hat recommends building the RPMs with rpm 4.14 so the entire package payload is signed.
> 
> Would an rpm build version change be sufficient?
> /help
> See [#95455 (comment)](https://github.com/kubernetes/kubernetes/issues/95455#issuecomment-777902782)

@BenTheElder someone in your (release) team could double check the info regarding the above statment (rpm 4.14)?

**Comment by BenTheElder** [comment]
My team only _runs_ the builds and publishes them to the registry, the sources for the build are in https://github.com/kubernetes/release/tree/master/packages

Ideally these should be community run and community published, but for now the community still relies on the GCP package host, so we have to publish the builds, and currently the k/k release build doesn't build RPMs/DEBs either so we also run the scripts in order to have something to publish. But we don't work on the build system and don't consume these ourselves.

See comment above: https://github.com/kubernetes/kubernetes/issues/95455#issuecomment-777902782

go.k8s.io/oncall <-- google-build-admin, I am going OOO for real now :-)

**Comment by dougsland** [comment]
> My team only _runs_ the builds and publishes them to the registry, the sources for the build are in
> https://github.com/kubernetes/release/tree/master/packages
> 
> Ideally these should be community run and community published, but for now the community still relies
> on the GCP package host, so we have to publish the builds, and currently the k/k release build doesn't
> build RPMs/DEBs either so we also run the scripts in order to have something to publish. But we don't
> work on the deb/rpm build system and don't consume these ourselves.

Agreed, would be the best if the community that uses the RPM packaging schema for k/k help in this effort.  /help

> go.k8s.io/oncall <-- google-build-admin, I am going OOO for real now :-)

Enjoy :)

**Comment by neolit123** [comment]
If you are on slack you can try asking in the #kubernetes-users channel to
see if someone is willing to help.

**Comment by killergoalie** [comment]
@BenTheElder Hey I'm coming to this kind of late.  Running into the same issue with the package.  I'm willing to offer help with updating the build pipeline to fix the FIPS issue if possible.  Just need someone to point me in the right directions.

**Comment by BenTheElder** [comment]
> 
@BenTheElder Hey I'm coming to this kind of late. Running into the same issue with the package. I'm willing to offer help with updating the build pipeline to fix the FIPS issue if possible. Just need someone to point me in the right directions.


Sorry, I don't closely monitor closed issues ... too many pings.

I haven't been on the team pushing these since August last year, but SIG Release is the group on the community side to talk to. The #release-packages-poc channel in https://slack.k8s.io is where the future of Kubernetes RPM/debian packaging is going on.
