### ISSUE TITLE
kubectl auth can-i <verb> "nonexistent resource" responds with 'yes' even after warning that it doesn't exist

### ISSUE THREAD

**Issue by troy0820** [kubernetes/kubernetes#95480]
**What happened**:
During the query `kubectl auth can-i get dafdafdf` the warning shows:
```
Warning: the server doesn't have a resource type 'dafdafdf'
```
but then it still responds with `yes`
using the -v=10 flag with this command also shows the response body as it being allowed _(which should be false because it doesn't exist)_
```
I1011 10:57:38.284408   66612 request.go:1097] Response Body: {"kind":"SelfSubjectAccessReview","apiVersion":"authorization.k8s.io/v1","metadata":{"creationTimestamp":null,"managedFields":[{"manager":"kubectl","operation":"Update","apiVersion":"authorization.k8s.io/v1","time":"2020-10-11T14:57:38Z","fieldsType":"FieldsV1","fieldsV1":{"f:spec":{"f:resourceAttributes":{".":{},"f:namespace":{},"f:resource":{},"f:verb":{}}}}}]},"spec":{"resourceAttributes":{"namespace":"default","verb":"get","resource":"dafdafdf"}},"status":{"allowed":true}}
yes
```

**What you expected to happen**:
I expected that after the warning it would respond as no because the resource doesn't exist.

**How to reproduce it (as minimally and precisely as possible)**:
Perform the following command with/without -v=10 flag `kubectl auth can-i get dafdafdf` 

**Anything else we need to know?**:
N/A

**Environment**:
- Kubernetes version (use `kubectl version`): Client version: 1.19.2 Server version: 1.19.0
- Cloud provider or hardware configuration: N/A
- OS (e.g: `cat /etc/os-release`): macos x 
- Kernel (e.g. `uname -a`): Darwin
- Install tools: kubectl, _(kind cluster)_
- Network plugin and version (if this is a network-related bug): N/A
- Others:

**Comment by liggitt** [comment]
This is similar to https://github.com/kubernetes/kubernetes/issues/95471#issuecomment-706701187 and is working as intended. 

The authorization layer is decoupled from the serving layer, so that authorization checks can be made speculatively before resources are served. 

The warning is present in case someone typoed the resource name to make it visible that the resource is unknown, but the check can still be made against an unknown resource type and an answer returned.
