### ISSUE TITLE
Reserved range within service CIDR wherein automatically assigned IPs will not be chosen

### ISSUE THREAD

**Issue by pnovotnak** [kubernetes/kubernetes#95570]
**What would you like to be added**:

It would be nice to be able to specify a range, within the service CIDR, where the cluster will not automatically allocate service ClusterIPs but will still allow services to be created with the ClusterIP manually specified.

**Why is this needed**:

This would be useful, for instance, in situations where you need to add more DNS resolvers. Coredns cannot use hostnames for upstreams, so an IP is required. But there is no safe way to allocate a fixed IP, and creates the need to do things like this (verbatim from the the [istio "replicated control plane" docs](https://istio.io/latest/docs/setup/install/multicluster/gateways/#setup-dns)):

```shell
$ kubectl apply -f - <<EOF
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
data:
  Corefile: |
    .:53 {
        errors
        health
        kubernetes cluster.local in-addr.arpa ip6.arpa {
           pods insecure
           upstream
           fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        proxy . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
    }
    global:53 {
        errors
        cache 30
        proxy . $(kubectl get svc -n istio-system istiocoredns -o jsonpath={.spec.clusterIP})
    }
EOF
```

This is fine for toy examples, but if you have a fleet of clusters where you need to run this shell command in your CI... That's less fine and much more annoying. If, as a cluster operator, I could specify `--service-cluster-ip-range=192.168.0.0/19` **and**, say `--service-cluster-ip-range-reserved=192.168.0.0/27`, I could easily remove this shell code and get this configuration back into kustomize.

**Comment by pacoxu** [comment]
https://github.com/kubernetes/kubernetes/issues/24363 is about reserving a cluster ip for dns.

System reserved only the first ip in cluster-ip-range for apiserver.

**Comment by danwinship** [comment]
cc @aojea 

So I was thinking that this could allow us to easily solve the [ipv6 service subnet size problem](https://github.com/kubernetes/enhancements/pull/1881). We could just say that when you have a /64 service CIDR, it also automatically carves out an exception as well so that the system-allocated part only covers 16 bits of the /64. (It would have to be flipped from the example above: we'd want to say that the system gets `fd02::/112` or `fd02::1:0/112` or something, and the user gets the rest of `fd02::/64`.)

But I guess that's not quite right because we don't currently let you manually claim a service IP that's in use at all, even if it was also manually claimed. So the service allocator still needs to keep track of the whole range. Blah.

**Comment by aojea** [comment]
Technically is doable, I think that is just modifying the allocationg strategy on the bitmap allocator to "reserve" one area, so `AllocateNext()` never allocates anything in the reserverd area.

https://github.com/kubernetes/kubernetes/blob/b2e1165/pkg/registry/core/service/allocator/bitmap.go#L64-L65

but since the allocators are not exposed, I can't find an easy way to specify the reserved area (a new flag)?
It also will need validation to avoid people shooting itselfs in their feet.

 'm sure that this will require a KEP

**Comment by aojea** [comment]
This can be fixed with this approach https://github.com/kubernetes/enhancements/pull/1881

**Comment by thockin** [comment]
I might also be OK with some additional parameter to indicate how many IPs to block off, assuming at the bottom of the range.
