### ISSUE TITLE
Error executing command in container: exec unavailable - unable to locate nsenter

### ISSUE THREAD

**Issue by resouer** [kubernetes/kubernetes#9573]
ENV:

I installed k8s by Docker on a single node EC2

COMMAND:
```
 ./kubectl get pods
POD                    IP          CONTAINER(S)         IMAGE(S)                      HOST                  LABELS                STATUS    CREATED   MESSAGE
k8s-master-127.0.0.1                                                                  127.0.0.1/127.0.0.1   <none>                Running   8 days    
                                   scheduler            resouer/hyperkube:v0.17.0                                               Running   7 days    
                                   apiserver            resouer/hyperkube:v0.17.0                                               Running   7 days    
                                   controller-manager   resouer/hyperkube:v0.17.0                                               Running   7 days    
nginx-dk784            10.1.41.2                                                      127.0.0.1/127.0.0.1   run-container=nginx   Running   7 days    
                                   nginx                nginx                                                                     Running   7 days  
```
And I got this ERROR:

```
 ./kubectl exec -i -t -p nginx-dk784 -c nginx /bin/bash
Error: Error executing remote command: Error executing command in container: exec unavailable - unable to locate nsenter
```

I have nsenter in the PATH of that VM, but I don't think that matters.

Can anyone help me with this?

**Comment by ncdc** [comment]
@resouer where do you have nsenter installed? It needs to be in the PATH that the Kubelet is using.

Also, the latest Kubernetes defaults to using Docker's exec API for `kubectl exec`, so you shouldn't see this issue if you're able to update.

**Comment by resouer** [comment]
As I said, kubelet is started by Docker as below, it seems I need to add `nsenter` into the hyperkube image?

```
[ec2-user@ip-172-31-6-127 ~]$ docker ps | grep kubelet
0e8220dbfeac        hyperkube:v0.17.0            "/hyperkube kubelet    8 days ago          Up 8 days                               jolly_ardinghelli

**Comment by CaesarC** [comment]
i have this problem too.
```
[root@gitlab ~]# docker ps -a|grep kube
07fd38b0c654        gcr.io/google_containers/hyperkube:v0.18.2   "/hyperkube proxy --   5 days ago          Up 5 days                               drunk_thompson      
dbb5ec993844        gcr.io/google_containers/hyperkube:v0.18.2   "/hyperkube kubelet    5 days ago          Up 5 days                               agitated_curie 
```

**Comment by goltermann** [comment]
We’re going through old support issues and asking everyone to direct your questions to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes). 

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases. 

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.
