### ISSUE TITLE
Kubelet PLEG relist takes too long result in node notready

### ISSUE THREAD

**Issue by Lion-Wei** [kubernetes/kubernetes#95750]
**What happened**:

In a cluster with lots pods, the relist step takes too much time, result in node not ready.

Most time spend in updateCache step, which will inspect the pod and get the PodStatus to update the cache serially.

**What you expected to happen**:

PLEG relist should not result in node not ready, even many pods changed during the same relist period.

**How to reproduce it (as minimally and precisely as possible)**:

Batch create and delete pods in a short time. 

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by mmerkes** [comment]
PLEG issues are definitely a challenge. However, I have some concerns about updating the pod cache in max parallel. [One goal of the PLEG design was to reduce the overhead of getting the pod status](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node/pod-lifecycle-event-generator.md), as there used to be one go routine per pod. If we update the pod cache in max parallel, we'd be regressing back to the same state. If the relist is taking a long time due to the container runtime running hot, which I'm guessing is a common case (?), this would only exacerbate the problem.

I'd be curious about the state of your container runtime while this is happening and how many pods you're talking about. If it can be reasonably parallelized, might be better to limit the parallelism.

**Comment by Lion-Wei** [comment]
> I'd be curious about the state of your container runtime while this is happening and how many pods you're talking about

Hi, I'm talking about bare metal case, and there are more than 300 container in one node, the runtime state is just fine, but node stuck in notready.

>  If it can be reasonably parallelized, might be better to limit the parallelism.

I think parallelize this step is necessary, and we need  limit the parallelism.

**Comment by zimmski** [comment]
I am glad that i found this issue because the descriptions and comments perfectly describe what we have experienced in the last hours while trying to upgrade a cluster of us from 1.18.x to 1.19.x (and then shortly to 1.20.x to check if it is a problem with 1.19 alone). We are now back to 1.18.x because our nodes have massive available resources put we hit timeouts with PLEG leading to not-ready nodes. We have 100-200 pods per node. We are hitting PLEG timeouts even with a load average of < 5. So for us this is a major regression since this was never a problem with 1.18.x and we cannot upgrade anymore until this gets fixed.

Is there anything we could try In the meantime? We are otherwise stuck with 1.18.x. Reducing pods per node is not really a solution for us because that would mean we are just splitting hosts into multiple VMs to utilize the resources we have.

@mmerkes it seems that https://github.com/kubernetes/kubernetes/pull/96448 is not the solution for you?

**Comment by zimmski** [comment]
> So for us this is a major regression since this was never a problem with 1.18.x and we cannot upgrade anymore until this gets fixed.

Did take another look and can confirm again that this problems appears for us with 1.19.x but not with 1.18.x. I do not have a minimum of pods yet but i can see that the switching of a node to "not ready" also happens with 60-70pods and <5load. In comparision i currently have a node without any problems 254 pods and ~14load that has absolutely no problem.

**Comment by JornShen** [comment]
@zimmski  Do you try this MR https://github.com/kubernetes/kubernetes/pull/96448 in your cluster ?

**Comment by JornShen** [comment]
@zimmski can you also see every relist time in your node kubelet log ?

**Comment by zimmski** [comment]
@JornShen can you give me some guidance on how to try out a MR on a production cluster? Do i have to build and pack everything by hand? Can you pinpoint me to the documentation?

> can you also see every relist time in your node kubelet log ?

Can you explain what you mean and how i can very what you need to know?

**Comment by JornShen** [comment]
@zimmski this is one metrice record every relist time.

https://github.com/kubernetes/kubernetes/blob/9af6f70f8f05479c96efcb23c77447e15fb69eed/pkg/kubelet/pleg/generic.go#L199

Name is `pleg_relist_interval_seconds`. You can call kubelet's port 10250 api to get metrics infos. URI is https://127.0.0.1:10255/metrics. Or you can call its unsecurity port 10255 (using http). Call this URI in the node which has much pod in your cluster. you can also find it in your Prometheus if have.

if you want to try my MR(https://github.com/kubernetes/kubernetes/pull/96448), you can patch it and rebuild kubelet.  and replace it in your cluster.  And you should set the env variable `PLEG_PARALLEL_UPDATE_CACHE_NUM` to raise the relist parallel nuns. And see whether can solve your problems.

**Comment by ikeeip** [comment]
AFAIK there are two issues related with PLEG:
- when `broken pipe` was occurs while `relist`.
- when total response time from container manager greater then `relistTreshhold`.

Is it reasonable add some stream endpoint into `conteinerd` CRI plugin and design new PLEG implementation to fix second problem?

**Comment by JornShen** [comment]
@ikeeip  sorry for delaying long time. And @chenyw1990 you can continue to deal with it based on https://github.com/kubernetes/kubernetes/pull/96448 as I have no much time for it.
