### ISSUE TITLE
Add method to record.EventRecorder to define the event name

### ISSUE THREAD

**Issue by slinkydeveloper** [kubernetes/kubernetes#95903]
Today the `record.EventRecorder` generates a name for each event generated through it. The problem with the generated name is that it uses the target name + the timestamp, hence there are some situations where there could be 2 events generated with the same name (for more details on our use case, look at https://github.com/knative/eventing/pull/4393).

I propose to add some options to customize the generated event, like a new method (or `Event` itself) that accepts a vararg at the end to modify the event:

```
Event(object runtime.Object, eventtype, reason, message string, options ...func(*v1.Event))
``` 

And a sample usage:

```
recorder.Event(target, v1.EventTypeNormal, "HelloWorld", "hello world", recorder.EventName("blabla"))
```

I can take it if you're interested in this feature.

Dup of https://github.com/kubernetes/client-go/issues/887

**Comment by slinkydeveloper** [comment]
Not sure it's the right sig

/sig api-machinery

**Comment by deads2k** [comment]
So a few preliminary comments about the situation. The code currently does 

```
Name:        fmt.Sprintf("%v.%x", ref.Name, t.UnixNano()),
```

This means that enough events were created in a short enough time frame that multiple events managed to be created for the same object in the same nanosecond (or close enough that the system returned the same nano).  Now our default broadcaster limits events about a single object to one every 600 seconds.  That means you're producing events approximately 600 **billion** times faster than the client wants to send them.  Given fairly average kube-apiserver response time, you're producing them about 1 **million** times faster than our server can generally store them (in parallel).  And that's just for a single referenced object.

It's not that I want to prevent you from creating several in a quick burst or even prevent apps with high throughput needs from trying to create and smooth out their events.  But if I were you, I would double check the behavior at scale and try to see if I really need or want all these events. We created the correlator to prevent much slower producers from overrunning a kube-apiserver and its associated storage and you may be pressing against those limits pretty quickly.

Because the use-case seems narrow and potentially abusive to the server, I'm not inclined to change the event-ing API itself.  I am ok with adding a six-digit rand to the end of the name we generate today to make collisions even less likely.  But if you find yourself conflicting because event production is pressing at that high a scale, I don't think events are well suited to your use-case.

**Comment by slinkydeveloper** [comment]
In our use case we're not using k8s events in production, just in our test-infra. Every time we receive a request in our test-images, we log it to k8s events. What I think happened here is that we received 2 requests more or less at the same time, causing the name to be the same.

**Comment by deads2k** [comment]
Spoke on slack. This is being used to back an event load during testing that is intended to be unlimited throughput, without event correlation.  These objectives work against the goal of the event broadcaster, so I recommend not using it for this.  I would also caution against using events as a datastore in general.  They are intended as best-effort, human speed messages in a namespace.  We expect a steady state of about 1 event every five minutes per objectref and events are subject to being dropped or deleted at any time.

/close
