### ISSUE TITLE
Api upgrading automatically when moving from k8s 1.14 to 1.16

### ISSUE THREAD

**Issue by chowmean** [kubernetes/kubernetes#95974]
While upgrading we had a yaml with deployment `apps/v1` api. When we checked in 1.14 the deployment api is converted to `extensions/v1beta1`. Now when we run the same yaml in 1.16 the api used in `apps/v1`. 
Is there any conversion that kubernetes does for backward compatibility in 1.14 for `apps/v1` but since `apps/v1` is available from 1.10 why it does so? 

Kubernetes: Amazon EKS 1.14 -> Amazon EKS 1.16

**Comment by liggitt** [comment]
> When we checked in 1.14 the deployment api is converted to extensions/v1beta1. Now when we run the same yaml in 1.16 the api used in apps/v1.

If you checked using something like `kubectl get deployment $name -o yaml`, that is an ambiguous request, since it does not indicate which API group or version of deployments you want to fetch. 

When faced with an ambiguous request, kubectl resolves to the first API group/version listed in discovery which includes the specified resource. 

Prior to 1.16, extensions/v1beta1 was the first API group listed in discovery containing a deployments resource. It was listed first for compatibility reasons. 

In 1.16, when extensions/v1beta1 deployments were no longer served, apps/v1 became the first API group/version listed in discovery which contained a deployments resource. That is why `kubectl get deployment $name` fetched a different version starting in 1.16. 

Note that the API server would happily return an apps/v1 version of your deployment prior to 1.16 if explicitly requested with `kubectl get deployments.v1.apps $name`
