### ISSUE TITLE
IPv6 Conntrack UDP NodePort kind tests failing 

### ISSUE THREAD

**Issue by cmluciano** [kubernetes/kubernetes#96024]
**Which jobs are failing**:
sig-network-kind-ipvs,dual,master
sig-network-kind-ipvs,IPv6,master

**Which test(s) are failing**:

- [ ] KubeProxy should set TCP CLOSE_WAIT timeout
- [ ] Conntrack should be able to preserve UDP traffic when server pod cycles for a NodePort Service
- [x] KubeProxy should resorve connection reset issue (tracking in  #93281)

**Since when has it been failing**:
Oct 28 

**Testgrid link**:
- [sig-network-kind,ipvs,IPv6,master](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-kind-network-ipvs-ipv6/1321817895239421952)
- [sig-network-kind-ipvs,dual,master
](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-kind-network-ipvs-dual/1321794994394107904)

**Reason for failure**:
- Both appear to be failing on missing conntrack entries

ex. 
```test/e2e/network/kube_proxy.go:54
Oct 29 15:09:08.240: no conntrack entry for port 11302 on node fc00:f853:ccd:e793::2
vendor/github.com/onsi/ginkgo/internal/leafnodes/runner.go:113```

**Anything else we need to know**:

**Comment by cmluciano** [comment]
I'm spinning up a kind cluster with ipv6+ipvs to see if I can replicate this test locally

**Comment by aojea** [comment]
heh, the job was not running it, it started to run when we changed the tag

**Comment by aojea** [comment]
this one has an issue already open, and I have a PR for fixing it
`KubeProxy should resorve connection reset issue #74839`
https://github.com/kubernetes/kubernetes/issues/93281

**Comment by cmluciano** [comment]
@aojea reached out to me on Slack and we identified `Conntrack should be able to preserve UDP traffic when server pod cycles for a NodePort Service` as the high priority. I have tested this locally and it fails on both IPTables and IPVS kind clusters locally. I'm digging through the cluster logs now.

**Comment by aojea** [comment]
> @aojea reached out to me on Slack and we identified `Conntrack should be able to preserve UDP traffic when server pod cycles for a NodePort Service` as the high priority. I have tested this locally and it fails on both IPTables and IPVS kind clusters locally. I'm digging through the cluster logs now.

I' ve added logging to conntrack with level v4 recently https://github.com/kubernetes/kubernetes/pull/95694 just for these problems, try to bump your kube-proxy logging to v4

**Comment by aojea** [comment]
@cmluciano seems that there are less  test failures on the IPv6 jobs, let's keep watching them :eyes: 

However, the dual-stack jobs are legit failures, basically because on dualstack clusters, the node has 2 internal IPs, and those tests use the internal IP for asserting some operations, and the problem is that they are picking the internalIP of the wrong IP family, hence the test fails

https://github.com/kubernetes/kubernetes/blob/b2e1165/test/e2e/network/conntrack.go#L106

The solution should be to add the InernalIp correspoding to the cluster primary IP familty, you can obtain it with 
```
if framework.TestContext.ClusterIsIPv6()
```

but it seems that we have to modify the `ips := e2enode.CollectAddresses(nodes, v1.NodeInternalIP)` function or add a new one that returns the nodes and the corresponding ips

https://github.com/kubernetes/kubernetes/blob/b2e1165da8decee2f36a11e98d3dbccbebf82c55/test/e2e/network/kube_proxy.go#L63-L81

**Comment by cmluciano** [comment]
Hey @aojea Thanks for all the help, will look into the areas of the code and try to bump the logging.
