### ISSUE TITLE
Memory efficient list operation

### ISSUE THREAD

**Issue by hormes** [kubernetes/kubernetes#96082]
Right now, if a list request is sent to apiserver, we return to the client at once by constructing a complete list object like this:

apiserver performs a list, perform filtering request, return a list of the objects, serialized into a huge response and send to the client. If a large number of list requests come at the same time, the instantaneous memory overhead of apiserver is very large, and may even cause oom in an environment with limited memory. (Typically, when we use kubernetes to manage a large number of kubernetes clusters)

```
List() -> []Pod
```

In the current design, we expect the client to request apiserver through pagination to reduce pressure, but pagination list will increase the pressure of etcd, which will affect the performance of the entire cluster. Because of this, all informer list requests are served by apiserver cacher. When the controller restarts, a large number of list requests will cause the problems mentioned above.

We should provide a streaming list interface, similar to watch, apiserver can control the efficiency of data transmission according to its own load,  to avoid memory peaks caused by instantaneous serialization of large object .

```
List() -> chan *Pod
```

**Comment by lavalamp** [comment]
Why do you say that paginated lists add to the memory pressure of etcd?

Solutions to this problem:

* There's a way to invoke WATCH which first streams everything gotten from a list, which sounds like what you're asking for (although it's probably not memory efficient in apiserver) (also it's not very controllable so I don't recommend it).
* APF will offer a way to limit the number of concurrent LISTS (this is the real solution, since serving these just fundamentally uses some memory)
* Bookmarks are solving the problem where an apiserver restart causes controllers to reconnect, triggering the problem.

We may do work to ease this problem, but it's not going to look like streaming lists. Think things more like making controllers cache where they left off.

**Comment by hormes** [comment]
> limit the number of concurrent LISTS

It just slowed down the efficiency of the entire system recovery from failure, and did not really solve the problem.

> There's a way to invoke WATCH which first streams everything gotten from a list

Yeah, WATCH with rv=0. But the current reflector does not work like this, the entire controller and operators ecosystem depend on the LIST operation.

**Comment by lavalamp** [comment]
> Yeah, WATCH with rv=0. But the current reflector does not work like this, the entire controller and operators ecosystem depend on the LIST operation.

It's also not memory efficient for apiserver. Paginated lists are, and the reflector/informer use those by default now, I believe. 

>> limit the number of concurrent LISTS

> It just slowed down the efficiency of the entire system recovery from failure, and did not really solve the problem.

What exact intervention did you perform? And what exact test did you run?

**Comment by hormes** [comment]
Paginated lists are not performed for resourceVersion=0. When a controller like kube-controller-manager restarts, there will be a lot of list operations with resourceVersion=0.

Later, we will do a data comparison, and then re-create an issue to track.

**Comment by lavalamp** [comment]
>  When a controller like kube-controller-manager restarts, there will be a lot of list operations with resourceVersion=0.

What version are you on? That should not be the case.
