### ISSUE TITLE
Misleading "Pending" status is returned when pod fails with "Error: ErrImagePull"

### ISSUE THREAD

**Issue by adombeck** [kubernetes/kubernetes#96186]
Quoting #66828, which describes the issue well, but was closed after inactivity:

If pod fails in pulling a docker image, we have inconsistency in pod status.

    $ kubectl get pods
    NAME READY STATUS RESTARTS AGE
    my_pod_1 0/1 ErrImagePull 0 59m
    my_pod_2 0/1 ImagePullBackOff 0 39m

    $ kubectl get pod my_pod_1 -o jsonpath={.status.phase}
    Pending

    $ kubectl get pod my_pod_2 -o jsonpath={.status.phase}
    Pending

**Comment by troy0820** [comment]
From the docs, it shows that:

 ```
 Pending: The pod has been accepted by the Kubernetes system, 
but one or more of the container images has not been created.
 This includes time before being scheduled as well as time spent
 downloading images over the network, which could take a while.
``` 

So failure would indicate that the pod was created and then exited with a non zero state.  The pending provides a status that allows you to see that the pod isn't scheduled for some other reason.
/sig scheduling

**Comment by yashvardhan-kukreja** [comment]
I would like to pick this up

**Comment by yashvardhan-kukreja** [comment]
@troy0820 should I start working on this?

**Comment by troy0820** [comment]
@yashvardhan-kukreja I don't think there is anything to do with this issue.  The pod status is working by design and isn't intended to show failure because of failing to pull images.  The fail status will show when the container terminates and shouldn't be shown during a failure to pull images.  @adombeck Please read the above comments.
