### ISSUE TITLE
Enhanace CSIdriver object to explain supported PVC access mode for CSI plugin

### ISSUE THREAD

**Issue by Jainbrt** [kubernetes/kubernetes#96344]
**What would you like to be added**:

I would like to enhance csidriver object to explain what different volume access modes for Persistent Volume Claims a csi driver supports 

**Why is this needed**:
There are times when mutiple CSI storage drivers are installed on one k8s cluster and it becomes difficult for administrator/developer to understand which csi driver he/she should use for application requirement of volume access mode.

**Comment by Jainbrt** [comment]
@dpkshetty here is the issue I created as per our discussion, please add more if required.

**Comment by dpkshetty** [comment]
@Jainbrt thanks for opening this issue. Just to add more clarity, today if multiple CSI drivers are available, for someone to figure which ones support RWX Vs RWO modes, one has to list the drivers then go to https://kubernetes-csi.github.io/docs/drivers.html to figure which access modes a particular CSI driver support, it would be good to have the oc or kubectl cmdline provide a way to determine which access modes (RWX Vs RWO) a CSI driver supports so that there is no need for manual checking of the access mode per driver, hence this issue
