### ISSUE TITLE
When a pod has been completed, the taint-manager should no longer evict the pod

### ISSUE THREAD

**Issue by WxySupn** [kubernetes/kubernetes#96363]
**What would you like to be added**:

When a pod has been completed, the taint-manager should no longer evict the pod。

**Why is this needed**:

If a job has a completed pod, but the pod is evicted by taint-manager due to node damage, the job will have to execute this pod again.

**Comment by Dingshujie** [comment]
mark

**Comment by michaelgugino** [comment]
This seems more like a bug in the job controller rather than the taint manager.  There is nothing special about how the pod gets deleted in this case, someone using kubectl could delete the pod in the same way (or the pod might be deleted via eviction/draining the node) in which case, if the OP is accurate, the job would want to reschedule this pod.

IMO, the job controller should keep track of all pods which previously completed successfully, not rely on whether or not a pod is marked for deletion.

**Comment by lingsamuel** [comment]
agree @michaelgugino , job controller should track the complete status.
But the question is: the pod is deleted, user can no longer access its logs. We could check pod's phase in taint manager, and only deletes the Running pods.

**Comment by WxySupn** [comment]
agree @lingsamuel , the completed pods do not occupy node resources and do not need to be evicted.

**Comment by pacoxu** [comment]
Most Likely, eviction is based on `disk usage`. You can run `docker ps -a -s` to check.

**Comment by RainbowMango** [comment]
@WxySupn 
Would you like to make a PR for this?

**Comment by WxySupn** [comment]
Yeah, basically completed. I will commit the PR later.
