### ISSUE TITLE
Add conformance tests for RuntimeClass v1 API

### ISSUE THREAD

**Issue by SergeyKanzhelev** [kubernetes/kubernetes#96524]
Per the @liggitt comment in this PR https://github.com/kubernetes/kubernetes/pull/95718#issuecomment-725735634 conformance tests will regress because of a newly added Runtime Class GA v1 API is not covered with tests. Full comment:

Full comment:

> Does this have e2e coverage of all verbs on all endpoints of v1 RuntimeClasses (like [ea8f4cb](https://github.com/kubernetes/kubernetes/commit/ea8f4cb536718e2695a5c15362695767928fbc4c))? If not, this will appear as a regression in conformance coverage of GA endpoints. The expectation is that GA APIs have 100% e2e coverage via tests suitable to promote to conformance tests

/assign

More links:

- [apisnoop-conformance-gate](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/apisnoop-conformance-gate/1326930505215512576#1:build-log.txt%3A442)
- https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/conformance-tests.md#conformance-test-requirements
- https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/conformance-tests.md#promoting-tests-to-conformance

**Comment by SergeyKanzhelev** [comment]
KEP: https://github.com/kubernetes/enhancements/issues/585

**Comment by SergeyKanzhelev** [comment]
New to conformance tests. So the idea is to mark tests (or create new ones) that would call each of these methods https://github.com/kubernetes/kubernetes/blob/5cfce4e5cb4dc6ff429c088ec25973e2ebae2d86/staging/src/k8s.io/client-go/kubernetes/typed/node/v1/runtimeclass.go#L40-L50 at lease once?

So if this test https://github.com/kubernetes/kubernetes/blob/5cfce4e5cb4dc6ff429c088ec25973e2ebae2d86/test/e2e/common/runtimeclass.go#L64-L87 will be marked as conformance, it will cover `Delete` and `Get`. Is there any additional requirements for the conformance tests? Maybe with the number of side effects of that test or a special execution environment?

**Comment by liggitt** [comment]
> So the idea is to mark tests (or create new ones) that would call each of these methods

Yes. You can make a single test that runs objects through CRUD operations. For the deletecollection one, I'd suggest labeling the objects under test and scoping the deletecollection to your test label to avoid breaking the cluster you're running on. See https://github.com/kubernetes/kubernetes/blob/master/test/e2e/auth/certificates.go#L174-L186 as an example

**Comment by SergeyKanzhelev** [comment]
Great, will be working on it! Also just chatted with @hh about it.

**Comment by kikisdeliveryservice** [comment]
@SergeyKanzhelev @liggitt 

Just to get clarify on this - is this considered a blocker for https://github.com/kubernetes/enhancements/issues/585

Confirming bc grad criteria for it says "No release blocking feedback for API and functionality" should these tests be required to consider this stable? https://github.com/kubernetes/enhancements/tree/master/keps/sig-node/585-runtime-class#graduation-criteria

**Comment by hh** [comment]
Here's possibly an easier link to track:

https://apisnoop.cncf.io/1.20.0/stable/node

![image](https://user-images.githubusercontent.com/31331/99003632-3ee4a180-25a3-11eb-8770-ef2bd724a1f2.png)

**Comment by tallclair** [comment]
> > So the idea is to mark tests (or create new ones) that would call each of these methods
> 
> Yes. You can make a single test that runs objects through CRUD operations.

This seems like something that should be tested generically, or at the very least have a table-driven test that covers all (or most) GA APIs.

**Comment by hh** [comment]
https://apisnoop.cncf.io/1.20.0/stable/node

![image](https://user-images.githubusercontent.com/31331/99196603-4ea5f500-27f2-11eb-8b71-a93fb6915f28.png)

Just a quick note to show that currently the new tests are hitting all endpoints.

I'd go ahead and create the Promotion PR in order to get any necessary feedback from #sig-arch

**Comment by spiffxp** [comment]
/reopen

re: https://github.com/kubernetes/kubernetes/issues/96524#issuecomment-727100020

I disagree with the idea that a single test covering CRUD operations means RuntimeClass is now conformance tested.

Generic CRUD on a resource's API is not sufficient to describe the intended behavior of the resource.  That kind of test is at best verifying that api machinery is working.  A vendor would able to pass this test, without implementing any of the behaviors runtimeclass enables.

What does `RuntimeClass` do?  What kinds of behaviors are visible to an end-user? Are any of those tests in Conformance?

**Comment by spiffxp** [comment]
I'm not familiar enough with runtimeclass to know whether these would be a good start: https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-default&include-filter-by-regex=RuntimeClass

**Comment by SergeyKanzhelev** [comment]
Thank you for reopening. I agree with this in principle. But I really would appreciate some guidance here. 

Scheduling tests that takes runtime handler into account are great. However they don't hit any endpoints. I asked [here](https://github.com/kubernetes/enhancements/issues/757#issuecomment-726427165) and I'm not clear whether those needs to be covered as they are not touching an API.

As for actual scheduling, one limitation is posted [here](https://kubernetes.slack.com/archives/C0BP8PW9G/p1605296887121800?thread_ts=1605294378.121100&cid=C0BP8PW9G). Which makes some other tests impossible to include to conformance.

I can ask on sig node meeting next week, but there may not be all the right people there as it's a Thanksgiving short week. Do you have a suggestion?

**Comment by spiffxp** [comment]
I agree that exercising specific CRI implementations is not the place of Conformance testing.

Conformance testing is intended to exercise end-user visible behaviors of a Kubernetes cluster, which basically means whatever you can see and do at the Control Plane API level (ref: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/conformance-tests.md#conformance-test-requirements)

The challenge we face with Conformance testing is that we don't have an easy way to enumerate and measure coverage of behaviors.  We experimented with listing behaviors in .yaml so that humans and machines could populate and approve them independent of test implementation, but ultimately abandoned that effort due to its complexity (ref: https://github.com/kubernetes/enhancements/tree/master/keps/sig-architecture/960-conformance-behaviors)

So we use API coverage as an easily machine-measurable/enforceable proxy.  Noticing the coverage was at 0% should have been a sign that we should look at the existing test coverage of RuntimeClass and decide which tests were eligible for promotion to Conformance, and whether any new tests needed to be written.

In theory a solid test plan for a KEP would include a list of behaviors that need to be tested.  That's not immediately clear to me from the KEP for RuntimeClass (ref: https://github.com/kubernetes/enhancements/tree/master/keps/sig-node/585-runtime-class)

Based on my read of the KEP, some valid tests might be:
- tests that exercise the runtimeclass admission controller
  - creating pods with a non-existent runtimeclass
  - creating pods with an existing runtimeclass
  - creating pods with scheduling rules that would clash with runtimeclass scheduling rules
  - creating pods with scheduling rules that would merge with runtimeclass scheduling rules

Tests that would be disallowed by conformance requirements because they would require pre-installation/configuration of the cluster under test:
- running pods with a runtimeclass (unless there's some way to create a functional "dummy" runtimeclass without touching kubelets)
- running pods with a runtimeclass with a specific handler such as containerd, crio, etc. and expecting them to run

**Comment by SergeyKanzhelev** [comment]
sorry for the delay
/remove-lifecycle stale
