### ISSUE TITLE
[Failing Test] [sig-node] Pods Extended [k8s.io] Pod Container Status should never report success for a pending container (ci-kubernetes-e2e-ubuntu-gce)

### ISSUE THREAD

**Issue by thejoycekung** [kubernetes/kubernetes#96565]
**Which jobs are failing**:
`ci-kubernetes-e2e-ubuntu-gce`

**Which test(s) are failing**:
`[sig-node] Pods Extended [k8s.io] Pod Container Status should never report success for a pending container`

**Since when has it been failing**:
Flaking since https://github.com/kubernetes/kubernetes/compare/9223413a7...12d9183da Nov 11-12
Failing since https://github.com/kubernetes/kubernetes/compare/295010c30...5cfce4e5c Nov 12 1PM PST

**Testgrid link**:
https://testgrid.k8s.io/sig-release-master-informing#gce-ubuntu-master-default

**Reason for failure**:
Timeout
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/node/pods.go:206
Nov 13 09:51:47.661: timed out waiting for watch events for pod-submit-status-2-1
/usr/local/go/src/runtime/asm_amd64.s:1374
```

**Anything else we need to know**:
Example spyglass links:
- https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-ubuntu-gce/1327209965668012032
- https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-ubuntu-gce/1327179517839544320
- https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-ubuntu-gce/1326905591527903232

Can't find a triage link for this test on this job

/sig node
/cc @kubernetes/ci-signal @kubernetes/sig-node-test-failures 
/priority important-soon

**Comment by liggitt** [comment]
/priority critical-urgent

https://storage.googleapis.com/k8s-gubernator/triage/index.html?pr=1&test=Pod%20Container%20Status%20should%20never%20report%20success%20for%20a%20pending%20container

This is failing almost solidly in post-submits.

**Comment by SergeyKanzhelev** [comment]
Some very first notes (not sure how much I can spent today on this) from this failure: https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-ubuntu-gce/1327392638478848000

Test is waiting on deletion event and fails with timeout. Meanwhile pod is in not ready state. 

Error:

```
Nov 13 23:43:18.544: FAIL: timed out waiting for watch events for pod-submit-status-2-3
```

Events:

```
Nov 13 23:44:33.775: INFO: At 2020-11-13 23:38:16 +0000 UTC - event for pod-submit-status-2-3: {default-scheduler } Scheduled: Successfully assigned pods-215/pod-submit-status-2-3 to bootstrap-e2e-minion-group-sp83
Nov 13 23:44:33.776: INFO: At 2020-11-13 23:38:20 +0000 UTC - event for pod-submit-status-2-3: {kubelet bootstrap-e2e-minion-group-sp83} Pulled: Container image "docker.io/library/busybox:1.29" already present on machine
Nov 13 23:44:33.776: INFO: At 2020-11-13 23:38:20 +0000 UTC - event for pod-submit-status-2-3: {kubelet bootstrap-e2e-minion-group-sp83} Created: Created container busybox
Nov 13 23:44:33.776: INFO: At 2020-11-13 23:38:20 +0000 UTC - event for pod-submit-status-2-3: {kubelet bootstrap-e2e-minion-group-sp83} Started: Started container busybox
```

Pod is not ready:

```
Nov 13 23:44:33.822: INFO: POD                    NODE                             PHASE    GRACE  CONDITIONS
Nov 13 23:44:33.822: INFO: pod-submit-status-2-3  bootstrap-e2e-minion-group-sp83  Pending  1s     [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2020-11-13 23:38:17 +0000 UTC  } {Ready False 0001-01-01 00:00:00 +0000 UTC 2020-11-13 23:38:17 +0000 UTC ContainersNotReady containers with unready status: [busybox]} {ContainersReady False 0001-01-01 00:00:00 +0000 UTC 2020-11-13 23:38:17 +0000 UTC ContainersNotReady containers with unready status: [busybox]} {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2020-11-13 23:38:16 +0000 UTC  }]
```

**Comment by SergeyKanzhelev** [comment]
cannot repro locally:

```
 $GOPATH/src/k8s.io/kubernetes/_output/bin/ginkgo $GOPATH/src/k8s.io/kubernetes/_output/bin/e2e.test -- \
  --kubeconfig=$HOME/.kube/config --host="$CONTROL_PLANE_URL" --provider=skeleton \
  --ginkgo.focus="should never report success for a pending container"
```

Looking at [kubelet.log](https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-ubuntu-gce/1327392638478848000/artifacts/bootstrap-e2e-minion-group-sp83/kubelet.log), pod cannot be terminated because of [volumes keep it alive](https://github.com/kubernetes/kubernetes/blob/bdac36b57ed0d6de91e6ed1f2da7adb1c5117202/pkg/kubelet/kubelet_pods.go#L979-L983):

```
I1113 23:41:22.928028   10686 kubelet_pods.go:981] Pod "pod-submit-status-2-3_pods-215(cc3bd091-8df3-49b4-8e70-dce8cccef497)" is terminated, but some volumes have not been cleaned up
```

/sig storage 

in case there were recent changes in this area. 

need to look more later...

**Comment by andrewsykim** [comment]
Seems unrelated but I am fixing another failing test also on `ci-kubernetes-e2e-ubuntu-gce` (https://github.com/kubernetes/kubernetes/issues/96463), cross referencing in case they could end up being related. Working on a fix for that one here https://github.com/kubernetes/kubernetes/pull/96495

**Comment by andrewsykim** [comment]
fwiw I think `ci-kubernetes-e2e-ubuntu-gce` runs dockershim, @SergeyKanzhelev was your local test using docker or containerd?

**Comment by RobertKielty** [comment]
Another [failure](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce/1328247499541975040#1:build-log.txt%3A87350) to report when run from [sig-release-master-blocking#gce-cos-master-default](https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-default&width=5)

`Nov 16 08:31:33.868: timed out waiting for watch events for pod-submit-status-2-11
`

**Comment by andrewsykim** [comment]
To my point earlier around dockershim, I saw this fail on containerd jobs as well so maybe it's not specific to a container runtime

**Comment by SergeyKanzhelev** [comment]
> fwiw I think `ci-kubernetes-e2e-ubuntu-gce` runs dockershim, @SergeyKanzhelev was your local test using docker or containerd?

run with kind and docker

**Comment by RobertKielty** [comment]
This test also failed recently here on 

https://testgrid.k8s.io/sig-release-master-blocking#gce-ubuntu-master-containerd&sort-by-flakiness

See 
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-ubuntu-gce-containerd/1329006532758605824

**Comment by SergeyKanzhelev** [comment]
Same situation in this failure: https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-ubuntu-gce-containerd/1329128337662021632.

Analyzing [kubelet.log](https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-ubuntu-gce-containerd/1329128337662021632/artifacts/bootstrap-e2e-minion-group-bbzz/kubelet.log):

Log message keep repeating the message over and over and this is what keeping pod alive:

```
I1118 18:40:02.012853    9603 kubelet_volumes.go:91] pod "b828ed92-c07f-4e4d-8f57-fc92c95af793" found, but volume paths are still present on disk [/var/lib/kubelet/pods/b828ed92-c07f-4e4d-8f57-fc92c95af793/volumes/kubernetes.io~secret/default-token-psgtt]
I1118 18:40:02.013245    9603 kubelet_pods.go:1966] Orphaned pod "b828ed92-c07f-4e4d-8f57-fc92c95af793" found, but volumes not yet removed.  Reducing cpu to minimum
```

Un-mounting logs shows successful unmount:

```
I1118 18:40:01.669257    9603 reconciler.go:196] operationExecutor.UnmountVolume started for volume "default-token-psgtt" (UniqueName: "kubernetes.io/secret/b828ed92-c07f-4e4d-8f57-fc92c95af793-default-token-psgtt") pod "b828ed92-c07f-4e4d-8f57-fc92c95af793" (UID: "b828ed92-c07f-4e4d-8f57-fc92c95af793")
I1118 18:40:01.669398    9603 subpath_linux.go:226] Cleaning up subpath mounts for /var/lib/kubelet/pods/b828ed92-c07f-4e4d-8f57-fc92c95af793/volume-subpaths/default-token-psgtt
I1118 18:40:01.669459    9603 util.go:254] Tearing down volume default-token-psgtt for pod b828ed92-c07f-4e4d-8f57-fc92c95af793 at /var/lib/kubelet/pods/b828ed92-c07f-4e4d-8f57-fc92c95af793/volumes/kubernetes.io~secret/default-token-psgtt
I1118 18:40:01.669747    9603 empty_dir_linux.go:98] Statfs_t of /var/lib/kubelet/pods/b828ed92-c07f-4e4d-8f57-fc92c95af793/volumes/kubernetes.io~secret/default-token-psgtt: {Type:16914836 Bsize:4096 Blocks:954552 Bfree:954549 Bavail:954549 Files:954552 Ffree:954543 Fsid:{Val:[0 0]} Namelen:255 Frsize:4096 Flags:4128 Spare:[0 0 0 0]}
I1118 18:40:01.669819    9603 mount_linux.go:262] Unmounting /var/lib/kubelet/pods/b828ed92-c07f-4e4d-8f57-fc92c95af793/volumes/kubernetes.io~secret/default-token-psgtt
I1118 18:40:01.680219    9603 operation_generator.go:797] UnmountVolume.TearDown succeeded for volume "kubernetes.io/secret/b828ed92-c07f-4e4d-8f57-fc92c95af793-default-token-psgtt" (OuterVolumeSpecName: "default-token-psgtt") pod "b828ed92-c07f-4e4d-8f57-fc92c95af793" (UID: "b828ed92-c07f-4e4d-8f57-fc92c95af793"). InnerVolumeSpecName "default-token-psgtt". PluginName "kubernetes.io/secret", VolumeGidValue ""
```

I cannot figure out where in the code this directory suppose to be deleted. Will be looking further, please let me know if you have some pointers

**Comment by kolyshkin** [comment]
We have this test case failing a lot with cri-o recently (see e.g. https://github.com/cri-o/cri-o/pull/4383#issuecomment-730510935, https://github.com/cri-o/cri-o/pull/4370#issuecomment-730506929, https://github.com/cri-o/cri-o/pull/4379#issuecomment-730701738)

**Comment by SergeyKanzhelev** [comment]
This PR was merged just before failures started: https://github.com/kubernetes/kubernetes/pull/84206/

@mucahitkurt can you please take a look? This test failure looks to happen in exactly the logic that was changed.

**Comment by SergeyKanzhelev** [comment]
The directory seems to have to be removed here: https://github.com/kubernetes/kubernetes/blob/7d72ddca6e9a4e9cfa481b137bd0546be6a16cad/pkg/volume/util/subpath/subpath_linux.go#L275

Because this log message is in the `kubelet.log`: https://github.com/kubernetes/kubernetes/blob/7d72ddca6e9a4e9cfa481b137bd0546be6a16cad/pkg/volume/util/subpath/subpath_linux.go#L226 and no errors logged after it. So I cannot figure out why the later check for directory existence would say this folder is still around.

**Comment by mucahitkurt** [comment]
> This PR was merged just before failures started: #84206
> 
> @mucahitkurt can you please take a look? This test failure looks to happen in exactly the logic that was changed.

I'll try to check it.

cc @jingxu97 @msau42

**Comment by RobertKielty** [comment]
Although this test has failed for most of the time there are three times where it passed!

It has passed on these runs ... 
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-ubuntu-gce/1329097884053803008
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-ubuntu-gce/1329158760937033728
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-ubuntu-gce/1329189211646988288

**Comment by msau42** [comment]
Looking, it seems like the secret directory is not getting deleted

**Comment by liggitt** [comment]
if there's clear correlation with https://github.com/kubernetes/kubernetes/pull/84206, should we revert it, given how close we are to release?

**Comment by msau42** [comment]
Yes, it looks highly likely: https://github.com/kubernetes/kubernetes/pull/96758

**Comment by msau42** [comment]
Created https://github.com/kubernetes/kubernetes/issues/96759 to track the secret cleanup issue

**Comment by jeremyrickard** [comment]
Thanks for opening the revert PR @msau42!

**Comment by jingxu97** [comment]
this only failed on ubuntu, not cos?

**Comment by msau42** [comment]
Great question! looks like tests are passing on cos: https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-default&include-filter-by-regex=never.*report.*success

So it seems OS specific

**Comment by SergeyKanzhelev** [comment]
@msau42  you've been a few seconds faster than me answering it =)

**Comment by jingxu97** [comment]
Chris and I were debugging it, seems something strange happened with os.RemoveAll() in Ubuntu. Will update more details in issue #96768

**Comment by jingxu97** [comment]
Some updates.

Both COS and Ubuntu have test failures, but Ubuntu has much more frequent failures, especially on Ubuntu with docker. The failure frequency 
gce-ubuntu-master-default  >> gce-ubuntu-master-containerd >> gce-cos-master-default

Actually I don't think os.RemoveAll has issues here, because otherwise, a lot more tests will fail. 
The only failed test now is 
```
Pods Extended [k8s.io] Pod Container Status should never report success for a pending container.
```

This tests for testing a Pod that should never running because it tries to execute a non exist command.

From the volume logs, pod volume dir should be deleted already. But somehow somewhere it was created again (should not be created by volume manager because no such logs..).

**Comment by jingxu97** [comment]
I almost certain this is a race between emptyDir volume teardown and CreateContainer by kubelet.

This particular test is trying to start a pod, and then almost immediately delete it before the pod is started. (Other tests normally will wait for pod to start and then delete it).

The following will happen
1. pod is created: emptyDir volume is setup and ready
2. kubelet checks volumes are ready by checking volume manager actual state.
3. pod is deleted [ kubelet get delete from configCh]  SyncLoop (DELETE, "api") ]: emptyDir volume is in the process of teardown, it will unmount and then delete volume dir, but it has not yet updated actual state of the volume manager.
4.kubelet is syncing pod from another channel [plegCh] SyncLoop (PLEG): kubelet start to create container (at this point, kubelet thinks volume is still mounted and ready)
```
Creating container &Container{Name:busybox...
```
seems like during this container creation (by docker) it will somehow create this volume dir. 
5. Now, volume tear down finishes and update actual state, although volume dir was created back by step 4. But volume manager does not know this.

I think it is very difficult to avoid this race condition since we cannot make mount setup and container creation an atomic operation. In this situation, some volume dir will be left behind. My proposal is during cleanUpOrphandPodDirs, it can future check volume dir is an empty dir, and then it is safe to delete this dir instead of blocking by this.

**Comment by jingxu97** [comment]
So I think the reverted PR #96759 logic is correct, but it discover an issue which was hidden before.

**Comment by SergeyKanzhelev** [comment]
/close

the test is not failing after the reverted PR. Underlying issue is tracked here: #96759
