### ISSUE TITLE
Add configuration ability for the duration threshold of ApiServer trace

### ISSUE THREAD

**Issue by lala123912** [kubernetes/kubernetes#96587]
**What would you like to be added**:
The duration threshold of the trace  is hard-code, so it will bring inconvennience to the maintainability of the applications if they want to get more requests in a large cluster. What about to configure the threshold through an environment variables and hard-code the threshold a default value such as 500 * time.Millisecond?

https://github.com/kubernetes/kubernetes/blob/b96d8c0eaf8263658e56f89c30de5605b67242ae/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/create.go#L53

**Why is this needed**:
In a large cluster,  requests are very frequent，so some important requsts may not be traced duing to the small duration threshold. So it will be flexible if the threshold can be configured.

**Comment by yashvardhan-kukreja** [comment]
I would like to pick this up

**Comment by leilajal** [comment]
cc @logicalhan

**Comment by leilajal** [comment]
cc @lavalamp

**Comment by lavalamp** [comment]
Personally I think the way to go is with an adaptive theshold, so that it always logs about the same number of things.

E.g., we could have the trace mechanism keep a rolling 99.5 %ile threshold, and trace all that are slower than that.

Using an env var has the problem that if you set it wrong, you have to restart apiserver to change it, which may make the thing you're trying to debug go away.

**Comment by yashvardhan-kukreja** [comment]
Guys, I would love to work on this issue. I was just waiting for the traige-accepted label. Hope that's fine.

**Comment by yashvardhan-kukreja** [comment]
So, @lavalamp , do u mean this? That say, 99.5 percentile of logs are supposed to he shown at a rolling rate of, say, 5 seconds. Meaning at every 5 seconds, 99.5 per cent quantity of logs would be traced 

So, say, if in the last 5 mins, there came 1000 lines of logs, then, 995 (99.5% of 1000) lines would be traced.

and then, say, after sometime, in the last 5 mins, there came 2000 lines of logs, then 1990 (99.5% of 2000) lines would be traced.

**Comment by lala123912** [comment]
> Personally I think the way to go is with an adaptive theshold, so that it always logs about the same number of things.
> 
> E.g., we could have the trace mechanism keep a rolling 99.5 %ile threshold, and trace all that are slower than that.
> 
> Using an env var has the problem that if you set it wrong, you have to restart apiserver to change it, which may make the thing you're trying to debug go away.

Yeah, the threshold will have a default value, and this will be useful for debug to recurring problem   in a lager cluster. @lavalamp

**Comment by lavalamp** [comment]
> So, @lavalamp , do u mean this? That say, 99.5 percentile of logs are supposed to be shown at a rolling rate of, say, 5 seconds. Meaning at every 5 seconds, 99.5 per cent quantity of logs would be traced

The opposite, only the slowest .5% of requests should get traced.

One way to do this is just track the last N times, sort them, and take the value 99.5% of the way to the top as the threshold. That's expensive.

Another way is to count the last N requests and how many of them get logged. If that's too little (< 99.5%), reduce the threshold, otherwise increase the threshold. We can use a PID controller or something like it to compute the updates to the threshold.
