### ISSUE TITLE
Pod with hostNetwork:true reporting podIP from overlay network

### ISSUE THREAD

**Issue by ark-g** [kubernetes/kubernetes#96670]
**What happened**:
Observing a strange issue in k8s: the pod running in host network namespace getting pod IP address from _vxlan.calico_ interface instead of main _bond0_ host interface.
The _vxlan.calico_ interface from host:
```
# ip ad sh vxlan.calico
96: vxlan.calico: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1976 qdisc noqueue state UNKNOWN group default
    inet 10.244.26.64/32 brd 10.244.26.64 scope global vxlan.calico
       valid_lft forever preferred_lft forever

```
The main host network interface _bond0_ from host:
```
# ip ad sh bond0
8: bond0: <BROADCAST,MULTICAST,MASTER,UP,LOWER_UP> mtu 2026 qdisc noqueue state UP group default qlen 1000
    inet 7.7.240.4/24 brd 7.7.240.255 scope global bond0
       valid_lft forever preferred_lft forever
```
The pod status:
```
# kubectl get pod ptpd-XXXXX -oyaml
...
  hostNetwork: true
status:
...
  hostIP: 7.7.240.4
  phase: Running
  podIP: 10.244.26.64
  podIPs:
  - ip: 10.244.26.64
```
**What you expected to happen**:
We are expecting that pods declared as **hostNetwork:true** will get the main host IP (usually this happens), but sometimes pod getting _vxlan.calico_ address, as podIP,  instead of real host IP. Normal case for such a pod is when all 3 fields (hostIP, podIP and podIPs) are containing an address of _bond0_ interface.

**How to reproduce it (as minimally and precisely as possible)**:
The issue reproduced rarely, so we have no exact sequence to reproduce it.

**Environment**:
- Kubernetes version: 
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"archive", BuildDate:"2020-10-01T11:30:06Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"archive", BuildDate:"2020-10-01T11:28:11Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration:
None
- OS:
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
- Kernel:
4.15.0-123-generic
- Network plugin and version:
Multus - v3.4.1
Calico CNI -  v3.16.1

**Comment by ark-g** [comment]
The WA of the issue is to specify explicitly node IP in command line of **kubelet** utility (by using _--node-ip_ command line switch), otherwise, looks like, the node IP can be resolved randomly from set of the all node IP addresses.

**Comment by andrewsykim** [comment]
Can you reproduce this consistently?

**Comment by aojea** [comment]
> The WA of the issue is to specify explicitly node IP in command line of **kubelet** utility (by using _--node-ip_ command line switch), otherwise, looks like, the node IP can be resolved randomly from set of the all node IP addresses.

Pods with hostNetwork: true will use as PodIP, the Status.HostIP 

https://github.com/kubernetes/kubernetes/blob/8f6362bf9e11e42c71220a53eb564248bc9f0b3a/pkg/kubelet/kubelet_pods.go#L1537-L1538


hardcoding it with the flag --node-ip makes it work because, if is not set, kubelet tries to guess it, you can check the algorithm in

https://github.com/kubernetes/kubernetes/blob/b2dc35dab2cdd2aa33ba8240bb6e53478e63c435/pkg/kubelet/nodestatus/setters.go#L213-L219

something has to be causing the nondeterministic behaviour: the default route is changing? or the hostname is failing to resolve the IP? :shrug: 

---

@thockin thinking out loud, but if this merges https://github.com/kubernetes/kubernetes/pull/93898, in situation like this, it will make the pods with Hostnetwork: true change their IP randomly ... that can create a lot of flakiness on a cluster, because usually pods with hostNetwork: true are used for system critical tasks ...

**Comment by ark-g** [comment]
@aojea 
The default route was not changed and stays the same during node life, so I can suspect the DNS issue.
It is make sense since the issue not reproduced in stable manner.
As I see from code, if the _--node-ip_ not specified, then the HostIP can be achieved in so many ways and there is no guarantee that all these ways will return the same IP addresses in the same order in case of several addresses are configured on main interface. ( in case of DNS also no guarantee in IP order AFAIK).

P.S.: I am not expert in Go, just raise my concerns.

**Comment by aojea** [comment]
![image](https://user-images.githubusercontent.com/6450081/100337386-9a695300-2fd7-11eb-9c75-095fa4d0a702.png)
:smile:

**Comment by thockin** [comment]
We need to understand WHY it's choosing different IPs.  Is this code sufficiently instrumented that we can catch a log eventually?

**Comment by aojea** [comment]
> We need to understand WHY it's choosing different IPs. Is this code sufficiently instrumented that we can catch a log eventually?

the main problem is that the NodeAddress field is a minefield right now.
@danwinship is your man here @thockin , he address most issues with Node Addresses in his KEP https://github.com/kubernetes/enhancements/pull/1665/

**Comment by danwinship** [comment]
The kubelet node-ip autodetection in the "bare metal" / non-cloud-provider case is not great, and can't really be trusted if you have multiple interfaces. If you aren't using a cloud provider, it's best to always explicitly specify `--node-ip`.

Yes, one of the things that's talked about in https://github.com/kubernetes/enhancements/pull/1665 is making a new/better/saner/more-stable bare-metal-node-ip-autodetection mode

> Pods with hostNetwork: true will use as PodIP, the Status.HostIP

The code you're quoting there is not from git master, it's from #93898. The current kubelet behavior is that it will only set `podIP` on hostnetwork pods _if the runtime did not_. I know CRI-O always leaves the pod IP unset for hostnetwork pods, to allow kubelet to fill in the value that it thinks is correct, but I don't know what other CRIs or dockershim do. So that's another possibility here: it's possible kubelet and your container runtime disagree about what the node IP is.

**Comment by aojea** [comment]
/close
at this point I don't think that we can do more here
Feel free to reopen
Thanks
