### ISSUE TITLE
Secret volume directories sometimes don't get cleaned up

### ISSUE THREAD

**Issue by msau42** [kubernetes/kubernetes#96759]
**What happened**:
Offshoot of https://github.com/kubernetes/kubernetes/issues/96565.  We had to revert 
https://github.com/kubernetes/kubernetes/pull/84206 because it revealed that secret volume directories sometimes don't get cleaned up.

We should also investigate if other atomic writer volumes are impacted, like configmap, downwardAPI, etc.

**What you expected to happen**:
Volume directories should be cleaned up

**How to reproduce it (as minimally and precisely as possible)**:
Patch with https://github.com/kubernetes/kubernetes/pull/84206 and run the failing test in https://github.com/kubernetes/kubernetes/issues/96565

**Comment by msau42** [comment]
@kubernetes/sig-storage-bugs 
/triage accepted

**Comment by msau42** [comment]
Seems to be OS related, as the tests are passing on COS: https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-default&include-filter-by-regex=never.*report.*success

**Comment by jingxu97** [comment]
I almost certain this is a race between emptyDir volume teardown and CreateContainer by kubelet.

This particular test is trying to start a pod, and then almost immediately delete it before the pod is started. (Other tests normally will wait for pod to start and then delete it).

The following will happen

pod is created: emptyDir volume is setup and ready
kubelet checks volumes are ready by checking volume manager actual state.
pod is deleted [ kubelet get delete from configCh] SyncLoop (DELETE, "api") ]: emptyDir volume is in the process of teardown, it will unmount and then delete volume dir, but it has not yet updated actual state of the volume manager.
4.kubelet is syncing pod from another channel [plegCh] SyncLoop (PLEG): kubelet start to create container (at this point, kubelet thinks volume is still mounted and ready)
Creating container &Container{Name:busybox...
seems like during this container creation (by docker) it will somehow create this volume dir.
5. Now, volume tear down finishes and update actual state, although volume dir was created back by step 4. But volume manager does not know this.

I think it is very difficult to avoid this race condition since we cannot make mount setup and container creation an atomic operation. In this situation, some volume dir will be left behind. My proposal is during cleanUpOrphandPodDirs, it can future check volume dir is an empty dir, and then it is safe to delete this dir instead of blocking by this.

**Comment by chrishenzie** [comment]
@jingxu97 Thank you for the detailed explanation. Is this problem exclusive to emptyDir, or would we need special handling for other volume types?

**Comment by jingxu97** [comment]
good question, if my theory is correct, if will affect other types of volumes too, right now we just don't have similar tests on other volumes. 

I think the fix I am proposing is applying for all types of volumes.

**Comment by gnufied** [comment]
I think this might be upto container runtime which is creating a hostpath if it does not exist. For example:

```
╰─/home> docker run -it --rm -v /home/foo:/bar k8s.gcr.io/busybox /bin/sh
╰─/home> ls
foo  hekumar  linuxbrew  shared
```

**Comment by jingxu97** [comment]
@gnufied thanks for confirming this behavior. Any comments about the proposed solution?

**Comment by gnufied** [comment]
Where exactly in `cleanupOrphanedPodDirs` you are thinking of adding that check? The problem is - I think for this pod the code stops processing the pod in following condition:

```
		if allPods.Has(string(uid)) {
			continue
		}
```

**Comment by gnufied** [comment]
Also cc @kubernetes/sig-node-bugs for CRI interaction.

**Comment by msau42** [comment]
This race sounds very familiar with: https://github.com/kubernetes/kubernetes/issues/69831

**Comment by msau42** [comment]
To really solve the race, we may need to add a new state to the container state. We'll need to work with sig-node to make sure it's safe.

**Comment by hasheddan** [comment]
@msau42 @jingxu97 any updates here?

**Comment by hasheddan** [comment]
Is this a duplicate of https://github.com/kubernetes/kubernetes/issues/88766?

/cc @smarterclayton

**Comment by jingxu97** [comment]
seem related to https://github.com/kubernetes/kubernetes/pull/97659

**Comment by jingxu97** [comment]
Due to the race discovered https://github.com/kubernetes/kubernetes/issues/96759#issuecomment-731523669, after pod is deleted, it is possible that some local dir (unmounted) with data still exist.
