### ISSUE TITLE
Incorrect suggestion for missing field

### ISSUE THREAD

**Issue by ronaldpetty** [kubernetes/kubernetes#96762]
**What happened**:

Using the following yaml (which is incorrect), yields an incorrect suggestion to fix.

```
apiVersion: v1 
kind: PersistentVolumeClaim
metadata:
  name: mypvc-1
spec:
  accessModes:
  - ReadWriteOnce
  resources:
```

```
$ kubectl apply -f mypvc.yaml 
The PersistentVolumeClaim "mypvc-1" is invalid: spec.resources[storage]: Required value
```

**What you expected to happen**:

I would have expected it to say:

```
The PersistentVolumeClaim "mypvc-1" is invalid: spec.resources[requests]: Required value
```

**Environment**:

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:17:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:09:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
```

I am unclear what is required or optional per the actual pvcspec, but applying will fail unless you have resources.request.storage.  Or maybe that is some shorthand saying storage is required if using resources and skipping middle keys, I think that is also less useful.

**Comment by troy0820** [comment]
@ronaldpetty The error you are seeing is coming from the validation of the yaml you asked `kubectl apply -f` to do. 
Within this validation, the PersistentVolumeClaimSpecValidation is seeing if the resourceName (in this case storage) is set and if it isn't it will append the errors before being returned. 
You can see the code block [here](https://github.com/kubernetes-csi/driver-registrar/blob/master/vendor/k8s.io/kubernetes/pkg/apis/core/validation/validation.go#L1809-L1811).  The required field, in this case, in request is quantity and it takes a value of quantity (number).

So saying that requests (which is not a resourceName type) should be the value that is returned from the error would invalidate the logic behind the validation.  
To see the keys/values necessary for yaml definitions for resources, `kubectl explain persistentvolumeclaim` is a great tool
to see what is necessary to create a k8s object.

**Comment by ronaldpetty** [comment]
Thanks Troy for the detailed response.  I reviewed the code and still need
to think about it.

resources.requests.storage is correct

requests is a subkey of resources, storage is not, it is a sub-sub-key.

That said, it seems like a step is missing, why is verifying storage before
requests?  For ex. line 1809 is using requests, yet it wasn't specified in
the yaml, meaning it defaulted.  If that is the case, I don't see that in
the spec (defaulting aka required).

Ron

**Comment by troy0820** [comment]
@ronaldpetty Line 1089 is checking the existence of the value for the requests key. If the value doesn't exist, then it adds the error.  So in your yaml definition:
```
apiVersion: v1 
kind: PersistentVolumeClaim
metadata:
  name: mypvc-1
spec:
  accessModes:
  - ReadWriteOnce
  resources:
```
since it doesn't see the key `requests` , the subkey (storage), and value, it adds the error of the resourceName "storage" in this case because that is the resource it will create on the claim. 

Also in this [link](https://kubernetes.io/docs/concepts/storage/persistent-volumes#resources), you will see that claims have the same resource model and the request is for storage.  The key after requests would be storage (hence the subkey you were talking about)

**Comment by ronaldpetty** [comment]
Troy,

I agree on the last point, which is what I was believing.  That said, for
this yaml, I would still argue its not what 'it's' spec wants, which to me
is confusing.  Suppose can close as I think this is just a difference in
viewpoints (straight yaml of PVC versus semantic relationship to other
resources).

Ron

**Comment by troy0820** [comment]
@ronaldpetty With the resource model, I can understand how the error with `spec.resources[storage]` should look expect to look like `spec.resources.requests[storage]`. The resourceName type itself lends itself to use this functionality across the platform using the same resource model with error messages.  Since the model is the same, I would like to think that the implication of requests/limits would help. If this inconsistency needs to be addressed, raising an issue with the validation of resources will probably be a better idea to bring consistency to the platform.

**Comment by ronaldpetty** [comment]
Thanks @troy0820 I will noodle more on it!  Non-issue I suppose, have a good weekend.
