### ISSUE TITLE
Need specification on InstanceID in cloud provider interface

### ISSUE THREAD

**Issue by Sh4d1** [kubernetes/kubernetes#96871]
**What happened**:
According to 
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/cloud-provider/cloud.go#L177

`InstanceID` should return the providerID

But here: https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/cloud-provider/cloud.go#L114

It uses the name + the `InstanceID`. So does that mean that provider ID is `providerName://instanceID` ? Or only the value returned by `InstanceID`. It's not clear.

And here 
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/cloud-provider/controllers/node/node_controller.go#L648
It's used as the providerID directly

**What you expected to happen**:
Something clear 😄 

/cc @andrewsykim

**Comment by pacoxu** [comment]
IMO, we should follow the definition in core v1 type and the cloud provider 

https://github.com/kubernetes/kubernetes/blob/release-1.19/staging/src/k8s.io/api/core/v1/types.go#L4542
```
	// ID of the node assigned by the cloud provider in the format: <ProviderName>://<ProviderSpecificNodeID>
	// +optional
	ProviderID string `json:"providerID,omitempty" protobuf:"bytes,3,opt,name=providerID"`
```

In cloud like AWS , the instance id is like 'i-0af01c0123456789a' as https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/identify_ec2_instances.html. 

So in https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/cloud-provider/cloud.go#L177 GetInstanceProviderID is for cloud nodes.
```
// GetInstanceProviderID builds a ProviderID for a node in a cloud.
func GetInstanceProviderID(ctx context.Context, cloud Interface, nodeName types.NodeName) (string, error) {
	instances, ok := cloud.Instances()
....
	instanceID, err := instances.InstanceID(ctx, nodeName)
 ...
	return cloud.ProviderName() + "://" + instanceID, nil
}
```

Conversely, openstack write instanceIDFromProviderID
https://github.com/kubernetes/kubernetes/blob/f7e3bcdec2e090b7361a61e21c20b3dbbb41b7f0/staging/src/k8s.io/legacy-cloud-providers/openstack/openstack_instances.go#L234

Commonly
- instanceID is the instanceID for specified nodename
- ProviderID is ProviderName://instanceID


Examples from testcases: 
https://github.com/kubernetes/kubernetes/blob/9c1e124b157cfe5a3943ae68bf74860bf0ec85c1/staging/src/k8s.io/legacy-cloud-providers/openstack/openstack_test.go#L641-L659

As you mentioned,  https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/cloud-provider/controllers/node/node_controller.go#L648
1.  It tries to get node provider id at first. 
2. If node provider-id is none, it tries the instance id(L648)

And in most cloud providers, InstanceExistsByProviderID supports both provider id and instance id. That's why it's confused in node_controller.go and node_lifecycle_controller.go.

**Comment by andrewsykim** [comment]
Unfortunately `InstanceID()` is something we've had to carry over from when the cloud provider was only called from the kubelet. So far we have not been prescriptive to the exact format of providerID, though many cloud providers follow the format `<provider-id>:<zone>/<instance-id>`. This is useful in case cloud providers want to ignore instances not in the same cloud or they want to store other metadata (like zone/region) in there. 

We actually introduced a new "instances" interface recently:

https://github.com/kubernetes/kubernetes/blob/80f2101da12e8ba27a81d15955d84c78534147cf/staging/src/k8s.io/cloud-provider/cloud.go#L196-L212

And this new interface has a `InstanceMetadata()` hook that expects the whole providerID string, so we defer to the provider implementations to generate the entire providerID rather than trying to construct it from calling other methods like `ProviderName()` and `InstanceID()`. Hopefully this removes future confusions around instanceID and providerID.
