### ISSUE TITLE
Deprecation of k/k/cluster/log-dump subdirectory

### ISSUE THREAD

**Issue by tosi3k** [kubernetes/kubernetes#96915]
##  Context
As pointed out in https://github.com/kubernetes/kubernetes/pull/96613, SIG Scalability has proceeded with moving the log dumping mechanism used in the CI tests that leverage `kubekins-e2e` image from `kubernetes/kubernetes` repository to `kubernetes/test-infra` one where it lives in [this](https://github.com/kubernetes/test-infra/tree/master/logexporter) subdirectory. `log-dump.sh` and `logexporter-daemonset.yaml` files are put inside every newly built and released `kubekins-e2e` image.

## Rationale
We had plenty regressions related to log dumping in the past. Debugging and fixing them was painful as this often consisted of building custom package of k8s binaries and installing them on a cluster that seems like a pretty redundant (and painful) step in diagnosing the issue. Next, it was really difficult and time-consuming to merge a fix during code freezes. Lastly, as the `kubernetes/kubernetes` repo has release branches, a potential fix would require backporting which further contributes to the overall toil of expanding the log dumping and debugging it.

In addition, dumping is a utility strictly related to testing, not running a cluster on production whatsoever, so it makes much more sense that it lives in the `test-infra` repository.

## Migrating recommendations and current state of affairs
As we don't have the capacity to check if every job that leverages `log-dump.sh` script would be portable to use its version from `test-infra`, [kubetest](https://github.com/kubernetes/test-infra/tree/master/kubetest) still uses the `log-dump.sh` script from `k/k` repo by default. In order to leverage the new mechanism in your CI jobs see the readme file inside [k/k/cluster/log-dump](https://github.com/kubernetes/kubernetes/blob/master/cluster/log-dump) directory. In the (undefined) future, we would like to move to the new version of log dumping by default, though.

On a sidenote - consider adding `--use-logexporter` flag to `kubetest` arguments of your CI job. This is a way of dumping logs from nodes which is much more scalable and preferable over sequential SSH-ing - it's faster and more reliable as it creates a daemonset in which every pod drains the nodes' logs and uploads them to the test job's GCS directory.

In 1.21 we plan to completely remove `master-log-dump.sh` file which was previously used in the Kubemark CI tests (relevant PR: https://github.com/kubernetes/kubernetes/pull/96611).

/sig scalability

**Comment by pjh** [comment]
hi @tosi3k, we have https://github.com/kubernetes/test-infra/pull/22292/ created to start using log dumping from test-infra rather than from k/k/cluster/log-dump. I [searched test-infra](https://github.com/kubernetes/test-infra/search?q=USE_TEST_INFRA_LOG_DUMPING) and it looks like the USE_TEST_INFRA_LOG_DUMPING setting is only used in two places so far, which is less than I expected. Is this right? Does something need to be done to raise awareness about this?

**Comment by YangLu1031** [comment]
And I checked the [upstream logs](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-windows-gce-serial/1396857096531611648) after the kubernetes/test-infra#22292 got merged. I saw this message:
```
----------------------------------------------------------------------------------------------------
k/k version of the log-dump.sh script is deprecated!
Please migrate your test job to use test-infra's repo version of log-dump.sh!
Migration steps can be found in the readme file.
----------------------------------------------------------------------------------------------------
```
Seems it's still calling k/k/cluster/log-dump.sh instead of test-infra. 
@tosi3k, do you have any good example of setup the upstream test jobs to use log-dump.sh of test-infra? Thanks!

**Comment by pjh** [comment]
@tosi3k the guidance in https://github.com/kubernetes/kubernetes/blob/master/cluster/log-dump/README.md was not sufficient for our test jobs (https://github.com/kubernetes/test-infra/pull/22292) - we had to submit https://github.com/kubernetes-sigs/windows-testing/pull/271 as well.

Could you please update the guidance to reflect that, since https://github.com/kubernetes/kubernetes/pull/102337 has not been accepted?
