### ISSUE TITLE
 Add priority flag to kube-proxy on Windows hosts

### ISSUE THREAD

**Issue by ravisantoshgudimetla** [kubernetes/kubernetes#96935]
**What would you like to be added**:

 Add priority flag to kube-proxy so that end-user can specify priority

**Why is this needed**:

On Windows hosts, there is a chance that the kube-proxy process won't get enough CPU cycles because of the default priority set for the Windows process.

xref: kubernetes/kubernetes#95735 (comment)

Additional context:

xref: kubernetes/kubernetes#95735

cc @marosset @jsturtevant @JocelynBerrendonner @aravindhp

Let me know if you guys are fine with it. I can create a PR for the same.

**Comment by JocelynBerrendonner** [comment]
@sbangari, FYI

**Comment by thockin** [comment]
Why is this in kube-proxy and not whatever starts kube-proxy?  I'd prefer NOT to add flags if we can avoid it...

**Comment by jayunit100** [comment]
The important thing is that we bump the priority, bc kube-proxy running at low-priority on windows causes alot of problems.... wether done by a flag or not is probably less of a big deal, right @ravisantoshgudimetla

**Comment by marosset** [comment]
@thockin There are a few different ways to start processes with non-normal priority but all have some drawbacks (mostly due to how priority can only be set on running processes in Windows)
- `start { /abovenormal | /high | /realtime }` creates the process in a new shell Windows and makes it hard to capture / redirect stdout/stderr
- Using powershell to start the process and then set the priority has similar issues but not all environments/nodes may have powershell installed
- PsExec by Sysintermnals requires introducing a new tool and accepting a EULA
- Setting scheduled tasks to find specific processes and raise their priority is finicky

I think that adding an extra flag would be the solution that is the most re-usable across all of the different solutions already out there for setting up the nodes.

@jayunit100 / @ravisantoshgudimetla I'm asking some folks in the Windows container platform team if they think using AboveNormal or High would be the best priority  class to recoommend.

**Comment by jayunit100** [comment]
@marosset impl detail, can we do this via the kube-proxy config map api ? 

kube-proxy flags, specifically, are not used at all anymore ... theyre in a zombie state and we're working to remove them 

See https://github.com/kubernetes/enhancements/pull/2158 if interested in the specifics, but some history -- it looks like the **flags** in kube-proxy are largely "appendages of the past"

**Comment by marosset** [comment]
> @marosset impl detail, can we do this via the kube-proxy config map api ?

Setting this via the config map API would be fine - I think the important detail is to have the kube-proxy process set its own process priority. I don't have a preference on how kube-proxy is instructed to do so.

**Comment by ravisantoshgudimetla** [comment]
@marosset - Thank you for elaborating on why the kube-proxy process has to set it owns priority. I just want to add one more point related to having external entity set the priority, as community we need to give specification on how to set priority of the kube-proxy and kubelet if we're relying on external entities to do so.

> @jayunit100 / @ravisantoshgudimetla I'm asking some folks in the Windows container platform team if they think using AboveNormal or High would be the best priority class to recommend.

I believe you're referring to recommending in the docs. 

> spoke with @ravisantoshgudimetla and i think hes ok with this as well.

> Setting this via the config map API would be fine - I think the important detail is to have the kube-proxy process set its own process priority. I don't have a preference on how kube-proxy is instructed to do so.

+1

**Comment by desponda** [comment]
Hi 👋 Bug Triage here, code freeze is tomorrow! This issue hasn't been updated in a while and has been marked for 1.21 milestone, is there a plan to continue working on this @immuzz

**Comment by aravindhp** [comment]
/reopen

This is still required.
