### ISSUE TITLE
Skip hostNetwork tests for conformance - fallout from [CVE-2020–15257] in containerd

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#96988]
Given that the recommendation from [1][2][3] is to tell folks NOT to switch on hostNetwork for pods. Do we want to drop this from conformance? 

This will allow folks to create a PSP or use OPA or something to disallow hostNetwork by default. And a cluster thus secured will pass conformance.

[1] https://github.com/containerd/containerd/security/advisories/GHSA-36xw-fx78-c5r4
[2] https://research.nccgroup.com/2020/11/30/technical-advisory-containerd-containerd-shim-api-exposed-to-host-network-containers-cve-2020-15257/
[3] https://medium.com/nttlabs/dont-use-host-network-namespace-f548aeeef575

/area conformance
/sig architecture
/sig network

**Comment by dims** [comment]
cc @johnbelamaric @hh @caseydavenport @dcbw @thockin

**Comment by dims** [comment]
I believe the following tests touch/use hostNetwork

```
[k8s.io] KubeletManagedEtcHosts should test kubelet managed /etc/hosts file [LinuxOnly] [NodeConformance] [Conformance]
[sig-network] Networking Granular Checks: Pods should function for node-pod communication: http [LinuxOnly] [NodeConformance] [Conformance]
[sig-network] Networking Granular Checks: Pods should function for node-pod communication: udp [LinuxOnly] [NodeConformance] [Conformance]
```

**Comment by cmluciano** [comment]
xref: kubernetes/kubernetes#96482 another test that would be affected by any decision here.

The advisory mentions a fix in 1.3.9 / 1.4.3. Does k8s currently release with notes on what runtimes are supported?

**Comment by aojea** [comment]
I don' t think that we should remove hostNetwork from conformance because a vulnerability in one container runtime, another thing if is that it was an arhcitectural problem, but it seems that it was fixed and only affect people that runs the containers with hostnetwork as root.
It' s also widely used in the e2e tests as helper, so if not used directly it will be used indirectly in more conformance tests, that will make it more awkard

**Comment by BenTheElder** [comment]
We still need hostNetwork for pods that *should* be privileged, (e.g. kube-proxy daemonset), i don't think zero hostNetwork pods is happening in basically all clusters, even if it's reasonable to avoid for general usage.

> Does k8s currently release with notes on what runtimes are supported?

No. intentionally. SIG node makes no support guarantees for runtimes.

**Comment by asrivas-vmw** [comment]
We also have this particular test that uses host port:
`[sig-apps] StatefulSet [k8s.io] Basic StatefulSet functionality [StatefulSetBasic] Should recreate evicted statefulset [Conformance] 
`
which we should consider as part of this discussion.

**Comment by caseydavenport** [comment]
Yeah, I can't seem to convince myself that this would be OK. Host networked pods are a pretty important part of just about every kubernetes cluster today. Examples being kube-proxy, as well as other networking agents which typically run as host networked pods (network policy enforcement, routing, etc).

In **theory** yeah, we could say hostNetwork is not required for conformance, since all of those things _can_ be installed independently of k8s without the need to run as pods, but in my opinion the result would just be that most clusters don't conform.

**Comment by bowei** [comment]
My $0.02: I don't think it's a good idea to remove any piece of the API from conformance unless it is deprecated.

**Comment by thockin** [comment]
I think I agree that this is the wrong answer.

**Comment by pacoxu** [comment]
Here's our practise, 
- psp allows hostNetwork pod in sysadm namespaces like kube-system
- psp denies hostNetwork pod in other namespaces
This may be a choice in the conformance.

As @aojea said,
>  we don' t test hostnetwork in conformance but we use hostnetwork to test conformance 
We indeed should use some hostNetwork pods for management of network or monitoring.
