### ISSUE TITLE
Migrate kubernetes e2e tests away from use of docker.io images

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/kubernetes#97027]
Part of umbrella to migrate kubernetes e2e test images/registries to community-owned infrastructure: https://github.com/kubernetes/k8s.io/issues/1458

The following docker.io images are used by 1.20 e2e tests
```
docker.io/gluster/glusterdynamic-provisioner:v1.0
docker.io/library/busybox:1.29
docker.io/library/httpd:2.4.38-alpine
docker.io/library/httpd:2.4.39-alpine
docker.io/library/nginx:1.14-alpine
docker.io/library/nginx:1.15-alpine
docker.io/library/perl:5.26
docker.io/library/redis:5.0.5-alpine
```

We should migrate them to community owned infrastructure (ref: https://github.com/kubernetes/sig-release/issues/1369 for deciding how to implement a mirror registry)

We should consider doing this for release branches as well, which may use different images/tags.  So these wouldn't necessarily be cherry-picks

Two possible approaches:
- change the registry in source (I would prefer eliminating the extra "docker library" registry, and consolidate to a single e2e test image registry)
- start running tests with a config that swaps out docker.io for some other registry

/sig testing
/sig release
/area release-eng
/wg k8s-infra
/milestone v1.21

**Comment by justaugustus** [comment]
/triage accepted
/help
cc: @kubernetes/release-engineering @wilsonehusin 

Give a shout if any of you are interested in working on this!

**Comment by wilsonehusin** [comment]
I'm in!

/assign

**Comment by dims** [comment]
cc @vladimirvivien

**Comment by claudiubelu** [comment]
I've had 2 PRs opened for this, before it was decited that the test jobs would use the registry mirror configuration. Has there been any consensus on the approach? If so, I can un-abandon these PRs if necessary:

https://github.com/kubernetes/kubernetes/pull/95732
https://github.com/kubernetes/kubernetes/pull/95567

**Comment by wilsonehusin** [comment]
ooh thanks for sharing @claudiubelu. I don't think there has been any consensus, though I personally think your work on kubernetes/kubernetes#95567 is relevant, especially that you've covered everything except gluster and redis.

**Comment by claudiubelu** [comment]
> 
> 
> ooh thanks for sharing @claudiubelu. I don't think there has been any consensus, though I personally think your work on #95567 is relevant, especially that you've covered everything except gluster and redis.

We already have the redis image here [1], we'll just have to trigger a job for it afterwards. Indeed, I was missing the gluster image, I only considered the ``docker.io/library images``. :) I've amended the PR to also include the gluster image, however there's only a ``linux/amd64`` image for it.

**Comment by wilsonehusin** [comment]
so I've been thinking about this for a bit and I'm a bit concerned with the visibility of this setup to test authors -- I'm not sure if this is straightforward / intuitive enough for them to follow.

alternatively, are there other lighter (in terms of maintenance) solutions that we can pursue?

**Comment by claudiubelu** [comment]
> 
> 
> so I've been thinking about this for a bit and I'm a bit concerned with the visibility of this setup to test authors -- I'm not sure if this is straightforward / intuitive enough for them to follow.
> 
> alternatively, are there other lighter (in terms of maintenance) solutions that we can pursue?

Hm, what do you mean by the visibility of this setup of test authors?

If I'm not mistaken, the current goal is to not rely so heavily on dockerhub for testing anymore. For this purpose we are mirroring these images into our own registries, and then we are going to update ``kubernetes/test/utils/image/manifest.go`` to use our own registry instead of the dockerhub one. Test authors shouldn't be impacted by this, IMO. From their point of view, it's the same image, from a different source.

And in terms of maintenance... hm, techically, if someone would want to use an newer image, say ``httpd:1.16-alpine`` instead of ``httpd:1.15-alpine``, that image would have to be mirrored first. For that, they would have to update the image under ``kubernetes/test/images/httpd``, more specifically the ``BASEIMAGE`` and ``VERSION`` files, and get the PR merged. After that, we are going to have a postsubmit job that would "build" / mirror the image, and then a PR will have to be made to promote the mirrored image. It wouldn't require any specific person from the infra team to do all this, the Owner of the image could approve all this, so that should be pretty simple.

**Comment by wilsonehusin** [comment]
> If I'm not mistaken, the current goal is to not rely so heavily on dockerhub for testing anymore. For this purpose we are mirroring these images into our own registries, and then we are going to update `kubernetes/test/utils/image/manifest.go` to use our own registry instead of the dockerhub one.

yes, I think we're on the same page on this

> Test authors shouldn't be impacted by this, IMO. From their point of view, it's the same image, from a different source.
> ...
> For that, they would have to update the image under `kubernetes/test/images/httpd`, more specifically the `BASEIMAGE` and `VERSION` files, and get the PR merged. After that, we are going to have a postsubmit job that would "build" / mirror the image, and then a PR will have to be made to promote the mirrored image.

yeah what I'm wondering is: are there ways we make it even less significant work on the first step of modifying `BASEIMAGE` and `VERSION` files? if that step could disappear altogether, especially in scenario of adding new images, that would be great.

**Comment by claudiubelu** [comment]
> 
> 
> > If I'm not mistaken, the current goal is to not rely so heavily on dockerhub for testing anymore. For this purpose we are mirroring these images into our own registries, and then we are going to update `kubernetes/test/utils/image/manifest.go` to use our own registry instead of the dockerhub one.
> 
> yes, I think we're on the same page on this
> 
> > Test authors shouldn't be impacted by this, IMO. From their point of view, it's the same image, from a different source.
> > ...
> > For that, they would have to update the image under `kubernetes/test/images/httpd`, more specifically the `BASEIMAGE` and `VERSION` files, and get the PR merged. After that, we are going to have a postsubmit job that would "build" / mirror the image, and then a PR will have to be made to promote the mirrored image.
> 
> yeah what I'm wondering is: are there ways we make it even less significant work on the first step of modifying `BASEIMAGE` and `VERSION` files? if that step could disappear altogether, especially in scenario of adding new images, that would be great.

I don't really see how. Other images are doing something similar too. For example, the pause image also has its BASEIMAGEs and VERSION in its Makefile.

Not all images are built exactly the same, or have the same base image, or are built for the same arch types. Some of them are from scratch, others are from an alpine image, others are from a different alpine image, others are from a debian image... and then we also have windows base images. So, having those BASEIMAGE files addresses this issue. Plus, it also allows us to control what platforms we build for and what we test for. For example, the s390x support wasn't there from the start, it was added afterwards. Another example, we want to add the ``windows/amd64/2004`` and ``windows/amd64/20H2`` base images to the test images that support Windows since are going to need to support these, and we probably want to remove the ``windows/amd64/1903`` and ``windows/amd64/1909`` base images at some point. Anyways, modifying the BASEIMAGE files is not very common, but when it is, there's a good reason behind it, so it can't really be optional.

Plus, adding / modifying the BASEIMAGE and VERSION files is not significant work. For example, mirroring the 7 images in this PR [1] probably took me ~10 minutes or so.

From what I can tell, you want some fast way to just say: "mirror me this image entirely onto our registry". I don't know if we have something like that, and if we do, it'll probably also mirror images with arch types we don't need, and most likely won't have images for platforms we actually need (for example, the ``httpd`` and ``nginx`` images on dockerhub does not have any Windows images, but we need them). The test images building process for the test images was not designed for mirroring images, but it can easily do it and we can use it to do so. In addition to that, we can even extend those manifest lists with Windows support [2].

[1] https://github.com/kubernetes/kubernetes/pull/95567
[2] https://github.com/kubernetes/kubernetes/pull/77269

**Comment by wilsonehusin** [comment]
> Not all images are built exactly the same, or have the same base image, or are built for the same arch types.

oh right, apologies for the confusion. I was referring to having a Dockerfile as a whole, but your explanation is very helpful for me to gain more context about image usage in our infrastructure -- thank you for elaborating 😃 

> Plus, adding / modifying the BASEIMAGE and VERSION files is not significant work. For example, mirroring the 7 images in this PR [1] probably took me ~10 minutes or so.

I agree the _what_ isn't significant, but the _where_ worries me a bit. I guess in some ways I kind of wish that there is way for this work to simply exist in [k/k8s.io](https://github.com/kubernetes/k8s.io) without touching k/k proper, though now I'm not too sure if that would be overall less complex than this approach.

> From what I can tell, you want some fast way to just say: "mirror me this image entirely onto our registry".

yeah, I was trying to find more solutions towards this direction 😃 though I haven't found anything significant which aligns with this topic.

**Comment by claudiubelu** [comment]
In order to complete this, we are going to need these 2 trivial PRs:

- Retrigger image builder jobs for some images: https://github.com/kubernetes/kubernetes/pull/98831
- Small fix for Windows httpd images: https://github.com/kubernetes/kubernetes/pull/98887

**Comment by wilsonehusin** [comment]
seems like much of the work has been done by Claudiu or I do not have access to finish -- I'll unassign myself to keep this aligned with the state of things

/unassign

**Comment by spiffxp** [comment]
/assign @claudiubelu 
who has done a lot of the work for this
