### ISSUE TITLE
add resource label on inflight metric

### ISSUE THREAD

**Issue by yuanhuaiwang** [kubernetes/kubernetes#97061]
**What would you like to be added**:
add label on metric apiserver_current_inflight_requests , for example:resource,verb
>https://github.com/kubernetes/kubernetes/blob/a744bddbf497ab718a40bee1c730e7e848e471ed/staging/src/k8s.io/apiserver/pkg/server/filters/maxinflight.go#L106
>
**Why is this needed**:
if the apiserver_current_inflight_requests is high and cause system abnormal， the cluster administrator wants to known which resource or verb requests is the reason

**Comment by yuanhuaiwang** [comment]
cc @wojtek-t @smarterclayton @lavalamp @gmarek

**Comment by yuanhuaiwang** [comment]
@liggitt  what do you think this suggestion

**Comment by liggitt** [comment]
cc @logicalhan 

wouldn't the existing metrics let you see which resource/verb has the highest volume? adding dimensions to this doesn't seem that useful

**Comment by wojtek-t** [comment]
> I would think that you should be able to infer it most of the time. The existing inflight metrics group into two buckets, readOnly and mutating. So if you have elevated numbers, I would think you could just look at the corresponding apiserver_request_totals{verb=~"GET|LIST|SOMEOTHERREADONLYVERB"} and figure out where it is coming from.

+1

**Comment by yuanhuaiwang** [comment]
> > cc @logicalhan
> > wouldn't the existing metrics let you see which resource/verb has the highest volume? adding dimensions to this doesn't seem that useful
> 
> I would think that you should be able to infer it most of the time. The existing inflight metrics group into two buckets, readOnly and mutating. So if you have elevated numbers, I would think you could just look at the corresponding apiserver_request_totals{verb=~"GET|LIST|SOMEOTHERREADONLYVERB"} and figure out where it is coming from.

but if some mutating requests are dropped, i want to know which resource caused it, may be there are many resource requests more

**Comment by logicalhan** [comment]
> but if some mutating requests are dropped, i want to know which resource caused it, may be there are many resource requests more

Why not look at the request logs? These are high cardinality fields that you are proposing on adding to the inflight metrics and while it is probably fine for most clusters under a certain size, it will adversely affect the largest clusters (i.e. the ones with lots of resources, objects, traffic). 

Some additional context: we've had a number of instances in the past where we've had to go and [delete/modify metrics due to cardinality concerns](https://github.com/kubernetes/kubernetes/issues/53485), so adding additional (known) high-cardinality fields to existing metrics is something we are careful about. 

Also, if you want granularity on dropped requests then it would make more sense to add these dimensions to [apiserver_dropped_requests_total](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/endpoints/metrics/metrics.go#L120). I still don't think we should do that either though, due to the cardinality issues on the fields you are proposing on adding.

**Comment by yuanhuaiwang** [comment]
ok, i knew it, thanks a lot
