### ISSUE TITLE
Add a suspend/stop flag to job api

### ISSUE THREAD

**Issue by ahg-g** [kubernetes/kubernetes#97170]
**What would you like to be added**:
A `suspended`/`stopped` flag to the job api.

**Why is this needed**:
To control when the Pods of a Job get created by controller-manager. When set to true, all pods of the Job should be deleted. If set to true at Job creation, controller-manager doesn’t create any pods. 

We view this as a primitive that higher-level orchestrators can use to support job queuing, all-or-nothing scheduling and whole job preemption. The idea is that jobs managed by a higher level orchestrator should be created in a “suspended/stopped” state, the orchestrator unsuspends the job when it determines that all the conditions are met for the job to run. 

How the unsuspend conditions are checked is left to the job orchestrator to implement (e.g., job at the head of the queue, resources are available and quota is met etc.) and so it is outside of core Kubernetes support. However, once the job is unsuspended, managing the pods of a job is done by Kubernetes, and so the semantics and behavior of the unsuspended job is k8s native and would be identical between orchestrators.

~~Note that deployment has a [`paused`](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.19/#deploymentspec-v1-apps) flag, so there is precedent to this ask~~ the `paused` flag in deployment has different semantics to what we are proposing here.

/sig apps

**Comment by alculquicondor** [comment]
cc @soltysh

**Comment by ahg-g** [comment]
@kubernetes/sig-apps-proposals

**Comment by adtac** [comment]
Questions worth discussing:

1. Who can unsuspend jobs that were created in a suspended state? If the orchestrator should be the one to unsuspend jobs, should users be prevented from changing this bit? i.e. only allow controllers to toggle the field. Not sure how feasible this is. If this feature is only intended to be used with a controller (debatable if this is true, maybe there are use cases for users manually suspending jobs), allowing users to modify this is basically allowing them to shoot themselves in the foot. 

2. What does it mean to go from suspended -> unsuspended -> suspended? As @ahg-g says, if this semantically equivalent to parallelism = zero -> non-zero -> zero, then the orchestrator should delete all **uncompleted** pods when going from non-zero to zero parallelism. When the job is unsuspended again, the completed pods aren't re-created, so this might cause issues with all-or-nothing scheduling. For example, if 5 parallel pods are created and 3 of them terminate successfully, and then the job is suspended and unsuspended, only 2 parallel pods will be created. Maybe this isn't a big deal because the 3 completed pods would've been in the terminated state anyway.

**Comment by ahg-g** [comment]
This is done. Alpha 1.21.
