### ISSUE TITLE
Validate that each "Getting Started Guide" passes e2e for v1

### ISSUE THREAD

**Issue by RichieEscarez** [kubernetes/kubernetes#9717]
To ensure we dont publish anything for v1 that does not work, each Getting Started Guide should pass e2e. Otherwise we only mention that those IaaS (which dont pass e2e) are in progress (under development/revision/being updated). 

For those that do not pass e2e and do not get published (for v1 - stable), we can point to that "in-development" Getting Started Guide under the HEAD doc set (unstable). Once a Getting Started Guide passes e2e, we can promote it and publish it under v1 doc set (so show official v1 support).

https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/README.md

**Comment by quinton-hoole** [comment]
I don't think that it's useful to run the e2e tests manually over each Getting Started Guide, because the results will get stale quite quickly (due to changes to the system as well as changes to the getting started guides).  Better to have them be part of our continuous integration tests, so that as soon as they break, we can either fix them or declare them to be "in development " in our docs.

**Comment by brendandburns** [comment]
While I agree in principle w/ @quinton-hoole I think that we need to do this for now until we actually have coverage when we go live.

**Comment by quinton-hoole** [comment]
I'm happy as long as "we" is not me :-)

**Comment by quinton-hoole** [comment]
I unassigned myself, as I'm unlikely to have time for this in the next few weeks.

**Comment by justinsb** [comment]
Commenting so that I will remember to (1) open source the dashboard I wrote that makes it easy to watch results from Jenkins and (2) add the GCE output that you're now publishing (thanks!).  I just have to find the time, and I've been working on getting the AWS e2e tests actually passing :-)

FYI though, I would be surprised if anyone had better results than AWS, and AWS is still not at 100%.  I think I have PRs for most of the remainder, and have a few almost-ready-to-go in my queue.

Do we mean the conformance test, or the full e2e test?  The e2e test is also not entirely consistent across clouds: some tests are run on only a few clouds, sometimes for good reasons (special GCE/GKE features), sometimes purely because something isn't implemented (e.g. resize isn't tested on AWS, though I have it working on my branch).

**Comment by erictune** [comment]
We mean conformance test.  Will send out more details soon.

**Comment by erictune** [comment]
I am not going to personally validate all the getting-started-guides.  Conformance test is available for self-validation, and some people are using it.  Closing.
