### ISSUE TITLE
When stress testing a 4-node k8s cluster, the cluster cannot be fully loaded

### ISSUE THREAD

**Issue by lyr5333** [kubernetes/kubernetes#97277]
**What happened**:
   During the stress test for a 4-node cluster, I used several different test cases for pressure testing. The maximum CPU load of the whole cluster is only 30%. There is no performance bottleneck in the test client. Does k8s need to expand some native components or modify configuration files to improve CPU utilization
**What you expected to happen**:
I hope the utilization rate of k8scpu can reach above 90%
**How to reproduce it (as minimally and precisely as possible)**:
I deployed the v1.17.4 version of k8s network plug-in, and selected calico deployment test instance, which is the book example provided by isto official. I set it to automatically expand and shrink, with at least 4 instances and up to 400 instances. The test end is gradually pressurized, and the CPU utilization rate can only reach 30%
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
V1.17.4
- Cloud provider or hardware configuration:
![image](https://user-images.githubusercontent.com/56923025/102035917-9a04f080-3dfc-11eb-9d15-51b3bdc6274b.png)

I don't turn on the 3 and 4 now. It was turned on during the test. The configuration of 3 and 4 is as follows

![image](https://user-images.githubusercontent.com/56923025/102036026-d1739d00-3dfc-11eb-9edf-5192baa5d907.png)

- OS (e.g: `cat /etc/os-release`):
Ubuntu 20.04

- Network plugin and version (if this is a network-related bug):
Calico

**Comment by lyr5333** [comment]
![image](https://user-images.githubusercontent.com/56923025/102036171-1f88a080-3dfd-11eb-94a5-780fef9fb3b8.png)

**Comment by lyr5333** [comment]
There is something wrong with the picture display

k8s-mster1 configured as 24 core 64g
node1 configured as 32 core 64g
node2 configured as 56 core 512g
node4 configured as 56 core 512g

**Comment by BenTheElder** [comment]
What test are you running? I don't recognize anything SIG testing owns here.
This sounds more like an issue with your cluster provider or the (not owned by us) istio tests.
/remove-sig testing

**Comment by ehashman** [comment]
/kind support
/remove-kind bug

This doesn't seem that unusual to me. CPU utilization/idle % does not scale the same way memory does. Often utilization at just 35% of a system indicates high throughput. Workloads need available CPU in order to be responsive to incoming requests, or else you risk increased CPU-bound latency. (You can read about how this can't be modelled on a linear curve in this blog: https://blogs.oracle.com/solaris/cpu-utilization-of-multi-threaded-architectures-explained-v2 Per the example in this post, note that 50% of available throughput is reached at just 21% total CPU utilization, and 80% at 50%.)

Hence,

>  I hope the utilization rate of k8scpu can reach above 90%

This is not a realistic expectation.
