### ISSUE TITLE
s390x support for agnhost and nonewprivs

### ISSUE THREAD

**Issue by rajaskakodkar** [kubernetes/kubernetes#97318]
s390x support for nonewprivs image was added in #94876 and the commit from #94875 was cherry picked in #95032 to fix agnhost broken on s390x. However, the post merge job `post-kubernetes-push-e2e-test-images` failed for both(https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-kubernetes-push-e2e-test-images/1309411632278933504 https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-kubernetes-push-e2e-test-images/1324809920880578560) as image builder was broken. 

Now that image builder has been fixed in #96462, these jobs need to be restarted to push s390x tags of agnhost and nonewprivs in staging bucket.

cc @dims

**Comment by dims** [comment]
@chaodaig as you are on call this week, can you please run the CI job mentioned by hand?

**Comment by chaodaiG** [comment]
@dims , when I try to run the job with `bazel run //prow/cmd/mkpj -- --job=post-kubernetes-push-e2e-test-images --config-path=$(PWD)/config/prow/config.yaml --job-config-path=$(PWD)/config/jobs`, it failed with `FATA[0000] Job post-kubernetes-push-e2e-test-images not found.`.

So I went over and looked at the history and found that this job was deleted by https://github.com/kubernetes/test-infra/pull/19924 on 11/11. 

I don't think prow allows running a job that doesn't exist in its configmap, and searching the prow history with `gsutil ls gs://kubernetes-jenkins/logs | grep post-kubernetes-push-e2e-` got:

```
gs://kubernetes-jenkins/logs/post-kubernetes-push-e2e-agnhost-test-images/
gs://kubernetes-jenkins/logs/post-kubernetes-push-e2e-pets-redis-installer-test-images/
gs://kubernetes-jenkins/logs/post-kubernetes-push-e2e-pets-zookeeper-installer-test-images/
gs://kubernetes-jenkins/logs/post-kubernetes-push-e2e-resource-consumer-test-images/
gs://kubernetes-jenkins/logs/post-kubernetes-push-e2e-sample-apiserver-test-images/
gs://kubernetes-jenkins/logs/post-kubernetes-push-e2e-test-images/
gs://kubernetes-jenkins/logs/post-kubernetes-push-e2e-volume-gluster-test-images/
gs://kubernetes-jenkins/logs/post-kubernetes-push-e2e-volume-iscsi-test-images/
gs://kubernetes-jenkins/logs/post-kubernetes-push-e2e-volume-nfs-test-images/
```

This is the list of jobs that have ever ran since prow keeps all history in GCS, which indicates that not all of the new jobs added in https://github.com/kubernetes/test-infra/pull/19924 has ran yet, can you take a look at https://github.com/kubernetes/test-infra/blob/master/config/jobs/image-pushing/k8s-staging-e2e-test-images.yaml and let us know which job is that you want?

**Comment by dims** [comment]
@chaodaiG thanks for looking. let's ask @claudiubelu what jobs need to be triggered.

**Comment by claudiubelu** [comment]
Hello,

The post-kubernetes-push-e2e-test-images has been split into individual jobs for individual images and are now triggered by changes made in that image's folder. The jobs haven't been run yet since the split. You can trigger a job by sending a PR (e.g.: bumping the VERSION) and getting it merged.

**Comment by chewong** [comment]
/reopen
Still failing according https://testgrid.k8s.io/sig-testing-images#post-kubernetes-push-e2e-agnhost-test-images. #97938 should fix it.

**Comment by rajaskakodkar** [comment]
/close
@chewong I am closing this issue as the agnhost job passed https://testgrid.k8s.io/sig-testing-images#post-kubernetes-push-e2e-agnhost-test-images and the multiarch image is now available, it works fine for s390x as conformance job passed with the same https://testgrid.k8s.io/conformance-s390x#Periodic%20s390x%20conformance%20test%20on%20local%20cluster
