### ISSUE TITLE
ConnectionUpgrades in kube-aggregator API does not use the given roundtripper

### ISSUE THREAD

**Issue by Sh4d1** [kubernetes/kubernetes#97763]
**What happened**:
When using the egress selector, connection upgrade on the kube-aggregator API do not use the egress endpoint and thus timeouts

**What you expected to happen**:
The connection to be upgraded successfully
**How to reproduce it (as minimally and precisely as possible)**:
Upgrading a connection to a kube-aggregator API (in this case with kubevirt console output).
**Anything else we need to know?**:

It seems that https://github.com/kubernetes/kubernetes/blob/39483aa0957be65b04686173d2970b508b3974ca/staging/src/k8s.io/kube-aggregator/pkg/apiserver/handler_proxy.go#L208 does not reuse the given roudtripper when wrapping the roudtripper.

I think it's should be fixed by using the `Wrap` method on the rest config, maybe here https://github.com/kubernetes/kubernetes/blob/39483aa0957be65b04686173d2970b508b3974ca/staging/src/k8s.io/kube-aggregator/pkg/apiserver/handler_proxy.go#L276 (it works)? Or directly in the function (not familiar with the spdy roud tripper though)

**Environment**:
- Kubernetes version (use `kubectl version`): 1.20.1
- Cloud provider or hardware configuration: Scaleway
- OS (e.g: `cat /etc/os-release`): Ubuntu 20.04

/cc @caesarxuchao 
/cc @Jefftree

**Comment by liggitt** [comment]
cc @jkh52

**Comment by caesarxuchao** [comment]
/assign @jkh52 @caesarxuchao 
cc @Jefftree 

/triage accepted

**Comment by caesarxuchao** [comment]
I think we need to refactor the SpdyRoundTripper, 
* replace its [*net.Dialer](https://github.com/kubernetes/kubernetes/blob/bbde53e30054ff93037ebc57edc8d0176f777297/staging/src/k8s.io/apimachinery/pkg/util/httpstream/spdy/roundtripper.go#L62) with a netutil.Dialer, which allows a custom Dial() function, so that we can pass in the egressDialer.
* refactor the [dialWithoutProxy](https://github.com/kubernetes/kubernetes/blob/bbde53e30054ff93037ebc57edc8d0176f777297/staging/src/k8s.io/apimachinery/pkg/util/httpstream/spdy/roundtripper.go#L232) method to use the netutil.Dialer, similar to [proxy.dialURL](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/util/proxy/dial.go#L38), especially noting how it handle https.

**Comment by caesarxuchao** [comment]
I'm not familiar with this use case, @Sh4d1  can you explain more on the network in this use case?

It looks like that the kube-apiserver (or more precisely, the aggragator) is talking SPDY with the custom apiserver.

For my own record:
Note that this use case is different from `kubectl exec`.

In `kubectl exec` case, the kubectl client uses the SPDY transport to initiate a SPDY upgrade with the kube-apiserver, the kube-apiserver handles the upgrade, creates a connection to the backend (the kubelet), and relay data to & from the backend connection. 

Hence, in `kubectl exec` case, egressDialier is only used to create a connection to the kubelet, it's not used by the SPDY transport used by the kubectl.

But in this case, the  aggregator initiates the SPDY upgrade with the customer apiserver. The connection from the aggregator to the custom apiserver needs to go through egressDialer, that's why we need to refactor the SPDY transport to support a custom dial.

**Comment by Sh4d1** [comment]
@caesarxuchao I'm not familiar with it too 😄 
But I think it's when the connection are upgraded (which uses spdy) (with websockets for instance) to a kube-aggregator api. Discovered this when trying https://github.com/kubevirt/kubevirt and trying to see the serial console log via kubectl (which indeed uses a websocket to the kube-aggregator api).

Regarding the network it's pretty basic, master and worker network separated and the kas-network-proxy is used. Do you need more info?

**Comment by liggitt** [comment]
this sounds like the same root issue as https://github.com/kubernetes/kubernetes/issues/71808#issuecomment-445001720

**Comment by liggitt** [comment]
@caesarxuchao is this resolved by https://github.com/kubernetes/kubernetes/pull/104985 ?

**Comment by caesarxuchao** [comment]
Yes. Thanks for the reminder.

/close
