### ISSUE TITLE
pod cannot be deleted without cniVersion in flanne.conf

### ISSUE THREAD

**Issue by wzshiming** [kubernetes/kubernetes#97956]
**What happened**:

``` bash
# cat /etc/cni/net.d/10-flannel.conf
{
    "name": "cbr0",
    "type": "flannel",
    "delegate": {
        "isDefaultGateway": true
    }
}
```

Log when deleting pod:
![image](https://user-images.githubusercontent.com/6565744/104299890-b762d280-5500-11eb-8845-e89088df0ba1.png)

**What you expected to happen**:

error when starting kubelet
or
it can delete pod

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.20.1
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): 7
- Kernel (e.g. `uname -a`):  Linux zsm-test-2 3.10.0-1160.11.1.el7.x86_64 #1 SMP Fri Dec 18 16:34:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by aojea** [comment]
@wzshiming I think that the `cniVersion` field is mandatory in the CNI spec   https://github.com/containernetworking/cni/blob/spec-v0.4.0/SPEC.md

But let me double check with one of the CNI maintainers, @squeed is the CNI configuration in the description valid?

or should it include the cniVersion field?

```
# cat /etc/cni/net.d/10-flannel.conf
{
    "name": "cbr0",
     "cniVersion": "0.3.1",
    "type": "flannel",
    "delegate": {
        "isDefaultGateway": true
    }
}
```

**Comment by squeed** [comment]
`cniVersion` was, in the beginning, optional. If missing, it assumes `0.1.0`.

**Comment by wzshiming** [comment]
> `cniVersion` was, in the beginning, optional. If missing, it assumes .`0.1.0`
@squeed 
Yes, because it is assumed to be '0.1.0', there is no problem in creating pod, but there is a problem in deleting pod.

**Comment by aojea** [comment]
Great, thanks for educating me. So the situation is:

-  the fix is only for dockershim, that has announced it deprecation in previous release https://kubernetes.io/blog/2020/12/02/dockershim-faq/ , do we want to fix something that is being deprecated?

- in case we want to fix dockershim, does kubernetes supports or should support CNI 0.1.0?
The web says it follows 0.4.0 https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/network-plugins/

I think that the fix has to be in the cni configuration https://github.com/kubernetes/kubernetes/issues/97956#issuecomment-759068447 , but is my personal opinion :smile:

**Comment by wzshiming** [comment]
@aojea 
I've tested that containerd doesn't have this problem,
If dockershim is going to be deleted in the next version, I don't think this fix should be needed.
Thanks for your remind.

**Comment by aojea** [comment]
> If dockershim is going to be deleted in the next version, I don't think this fix should be needed.
> Thanks for your remind.

my pleasure, :+1: 
Thanks
/close
