### ISSUE TITLE
Scheduler: support per priority class preemption victim metrics

### ISSUE THREAD

**Issue by xujyan** [kubernetes/kubernetes#97983]
**What would you like to be added**:
Support per priority class preemption metrics that track how many pods are preempted in each priority class over time. 

**Why is this needed**:
This is interesting because priority is a main factor for preemption and in a multi-tenant environment where quotas are oversubscribed and there are multiple priority classes, the rate of preemption per priority class can provide some insight into whether the level of oversubscription is too disruptive to lower priority pods etc. The cluster admin then is able to use this insight to determine how quotas are structured.

**Comment by adtac** [comment]
I assume you mean the priority class of the preempted pod and not the preemptor?

Having both might be issue because of metric cardinality issues; with N priority classes, there could be N^2 combinations of preemptor/preempted pods, so it might not be feasible even for small N values.

Quick note: while we have `preemption_attempts_total`, that is incremented even when preemption isn't successful, so we might need two metric labels.

**Comment by ahg-g** [comment]
@adtac, I think it is N! (factorial), not N^2. Regardless, I think we can have two separate metrics, and so the cardinality is N for each: one metric tracking number of preempted pods that belong to a specific class, the other is number of pod that a specific class preempted.

**Comment by adtac** [comment]
(while I agree that it's inconsequential whether it's N^2 or N!, can you elaborate why it's factorial? my thinking was: if there are N priority classes and we sort them by priority, then each class can only preempt a class lower than itself. the i-th ranked priority class could preempt (i-1) classes, so the summation will N^2.)

**Comment by ahg-g** [comment]
ah, right, it is an arithmetic sequence from 1 - N, which is in the order of N^2.

**Comment by xujyan** [comment]
yeah the issue I raised is mainly about the `victim` but agreed that `preemptor` as a separate metrics is interesting too, although in my use case I think the victim metric is more useful because we typically care about that for the priority class that we oversubscribe and it may be preempted by any priority classes above it. From the preemptor's POV I guess I am less interested how much preemption happened with the preemptor being `system-cluster-critical` or `high-priority`.

**Comment by xujyan** [comment]
Circling back on the naming of the metric and whether to reuse the metric `preemption_victims` (continuing with the discussion in [here](https://kubernetes.slack.com/archives/C09TP78DV/p1610474506378100):

https://github.com/kubernetes/kubernetes/blob/074a5177209c3605daf11cfe6f477fddce0d55c0/pkg/scheduler/metrics/metrics.go#L67

I think it's problematic to reuse these metrics and just add priority labels (and use `HistogramVec` instead of `Histogram`) because where the existing queries would expect a single histogram, the new query would return a vector of histogram with distinct priority labels.

This is true for the `_count` metric as well (instead of a one count now there's a vector of counts)

These could be backwards incompatible.

So if we use new names, any recommendations on the naming? Insert `_per_priority_` into the name or name it such that it's open to more labels?

cc @Huang-Wei

**Comment by ahg-g** [comment]
I am not certain that changing the metric to HistogramVector (basically add labels) is a breaking change. @logicalhan can you advice if it is safe to change to HistogramVector and start adding labels (are framework like prometheus and stackdriver able to handle this automatically)?

I think we should have one metric long term, so I would avoid adding "per_priority" to the name. So, if we can't make the change to the same metric, we should select a generic new name and deprecate the existing one.

**Comment by yuanchen8911** [comment]
We need to be careful. Using the existing metrics names can break many existing systems that use them for monitoring and alerting. What would be a better strategy?

**Comment by ahg-g** [comment]
As I mentioned in the comment above, we two options:

1) if changing the histogram to vector type is a backward compatible change, then we can do that @logicalhan is the expert and can advise if this is safe.

2) if option 1 is not backward compatible, then we need to add a new metric with a new name and deprecate the existing one.

**Comment by Huang-Wei** [comment]
> So if we use new names, any recommendations on the naming? Insert `_per_priority_` into the name or name it such that it's open to more labels?

I agree with @ahg-g on using a more generic name. For example, "preemption_victims_total" - there is a metric naming guide we can refer to.

> Using the existing metrics names can break many existing systems that use them for monitoring and alerting. What would be a better strategy?

I don't have a strong option on this (changing metric type while keeping the metric name). @logicalhan can help confirm if it's a good pattern, but again, the prerequisite is whether it's allowed to change the metric type from Histogram to HistogramVector.
BTW: the metric is marked as Alpha level.

**Comment by logicalhan** [comment]
> Insert `_per_priority_` into the name or name it such that it's open to more labels?

Maybe it's just me, but definitely labels. But adding labels is a breaking change.

> BTW: the metric is marked as Alpha level.

So currently, **every** metric is alpha, because that was the defaulted stability level when the framework was introduced. 

 So given the fact that **_it is_** a breaking change, it's probably better to ask:

- Do people rely on this metric operationally?
- Is this something people are alerting off of?
- Is the metric data primarily an input into a health-related visualization? if so, is the data needed in realtime?

If none of these are true, then it's probably okay to make the breaking change. If some of these are true, you may want to deprecate this metric (and slate it for future removal N releases away) and create new metrics with all the new labels. If you don't even want to deprecate the metric because it is extremely critical (it sounds like that isn't true?) then it may be worth actually just promoting that one to `STABLE` status so that no one accidentally breaks it.

**Comment by ahg-g** [comment]
Thanks Han, since this is a breaking change, I think we can simply assume that someone somewhere used the metric in production even though it is still alpha.

So lets add a new metric with the label and deprecate the old one after a couple of releases to allow for migration.

@logicalhan do we have documented guidelines on metrics names?

**Comment by logicalhan** [comment]
> @logicalhan do we have documented guidelines on metrics names?

Yes, but I actually just found some mistakes in there. https://github.com/kubernetes/community/pull/5464

Generally, we try to adhere to [prometheus standards](https://prometheus.io/docs/practices/naming/).

**Comment by ahg-g** [comment]
Thanks @logicalhan, then I guess we can go with `preemption_victims_total` as Wei suggested and seems to be the best practice for unit-less metrics.

However, we need to make sure we protect the scheduler against clusters with many priorities which will result in high cardinality metrics. I proposed a solution in https://github.com/kubernetes/kubernetes/issues/97208#issuecomment-776414121
