### ISSUE TITLE
[RFE] nodeSelector on persistentVolume(Claim)

### ISSUE THREAD

**Issue by thoraxe** [kubernetes/kubernetes#9802]
It would be interesting to implement some kind of security via nodeSelector for persistent volumes. Essentially the volume would have specific selectors defined and a pod requesting a volume (claimed within the project) should only be scheduleable on a node with matching selectors for both the volume **and** the pod's defined selectors.

This helps to enable external volume security in that I can, ahead of time, expose certain storage to certain nodes with some determinism.

**Comment by markturansky** [comment]
I just realized how easy this would make local storage.  HostPath is a PV (for test and development only).

If a volume has a NodeSelector and that is used when scheduling, pods can land on nodes with HostPath PVs.

Pretty sure folks will hate that idea.

**Comment by ant31** [comment]
Hi,
> I just realized how easy this would make local storage. HostPath is a PV (for test and development only).

I'm looking for such feature, I think HostPath can be used in a cluster if a claim get bound to a node. 

i.e : 
- 'I have multiple PVs with HostPath on my node'
- 'I claim a PV with 20Gi',  the claim is marked to run on a nodeA
- 'I schedule a pod with that claim',  The scheduler should spin the pod on nodeA. 

This something I'm very looking for.
Usecase exemple: 
"As a User I want a MysqlDB with 20Gi persistent local storage ,  I don't care where it run on my cluster, but once it have been scheduled to a node it should always get scheduled on that node"

For now nothing in Kubernetes allow to fullfil this usecase. But having a HostPath  bound to a node would help a lot.
 I think hostpath should be allowed/ready for production, because network storage is sometimes not wanted but persistent-storage is.
 

Another topic: 
I think claims should be part of the scheduler process and asked by RC:
"As a user I want to scale my Database slave with 20Gi persistent local storage with 2cpu, 8Gi ram"
For now Claims have to be identified by name inside the RC so we can't scale to get individual(RWO) persistent per pod, I suggest that we specified only claim requirements inside rc definitions.

**Comment by gweis** [comment]
Is this something you could already do with two steps? E.g. create the pod with the volume first, and after you know on which node it is running, you can label the node and add a nodeSelector to the pod?

**Comment by thoraxe** [comment]
That assumes that the pod landed on a node where the desired storage was available, which means that the end user would require knowledge of the node labels in order to schedule their pod appropriately.

**Comment by markturansky** [comment]
@thoraxe is correct.  The pod becomes a pet that requires a specific node.  Why not then just use HostPath on the pod itself?  The indirection provided by PV/C is no longer useful when the pod is a pet.

**Comment by markturansky** [comment]
@thoraxe this PR contains the PVSelector you originally requested in this issue.  https://github.com/kubernetes/kubernetes/pull/17056

**Comment by thoraxe** [comment]
Cool!

**Comment by phagunbaya** [comment]
Is this feature going to fall into release soon ? Or should be treated as some future enhancement ?

**Comment by CallMeFoxie** [comment]
Still interested in using nodeSelectors for PV(C). Not useful just for databases but also for anything that has local data cached/pre-downloaded. Upon re-creating the pod via some higher controller (RC/RS from Deployment) we cannot easily specify specific node it should run on and would possibly lose its local data validity.

Or, for that matter, allow in nodeAffinity use of fieldRefs. Would work equally.

**Comment by kargakis** [comment]
@kubernetes/sig-storage-misc @kubernetes/sig-scheduling-misc there is another similar issue but can't find it atm

**Comment by davidopp** [comment]
Yes there are various related issues like #41598

**Comment by msau42** [comment]
We have a proposal out for the local storage scenario here kubernetes/community#306.  Once that is implemented, we can also consider how it can be expanded to support more general topology constraints (instead of just one node per volume for the local storage case).

**Comment by msau42** [comment]
We have local PVs available in alpha as of 1.7.  You specify node affinity on the PV that the scheduler will use to properly schedule the pod to the node where the local volume resides.

/assign

**Comment by andypeker** [comment]
There is already feature that could judge pod where to schedule ------ label ! Now, you design another feature do the same thing, absolutely same thing .... Is it necessary ?
