### ISSUE TITLE
How to discard the permissions defined in /etc/kubernetes/admin.conf

### ISSUE THREAD

**Issue by liyongxin** [kubernetes/kubernetes#98092]
I deployed the k8s cluster using kubeadm and gave the file /etc/kubernetes/admin.conf to others as the kubeconfig file. 
Due to security issues, now i want to discard the permissions of the file,
but I found out that the certificate of the file is bound to the system:masters group which is not controlled by RBAC permissions,
so I want to ask, how can I revoke the permissions in admin.conf?

**Comment by neolit123** [comment]
> Due to security issues, now i want to discard the permissions of the file,

you cannot because the cert is signed for the `system:masters` group. it cannot be gated by authz.
as the name implies the admin.conf should not be shared with anyone - it's like giving your `root` password.

you have two options:
- rotate the cluster CA:
https://kubernetes.io/docs/tasks/tls/manual-rotation-of-ca-certificates/
- replace the cluster

you should have used the command `kubeadm {alpha} kubeconfig user` to generate a kubeconfig file for additional users.

/remove-sig auth
/sig cluster-lifecycle
/area kubeadm
/close
