### ISSUE TITLE
error reading container (probably exited) json message: EOF

### ISSUE THREAD

**Issue by harche** [kubernetes/kubernetes#98142]
**What happened**:
Seeing this in the logs,
```
Jan 11 21:04:53.482614 ip-10-0-166-126 hyperkube[1733]: E0111 21:04:53.479356    1733 kuberuntime_sandbox.go:70] CreatePodSandbox for pod "pod-submit-status-0-0_e2e-pods-3370(c76833c3-6e57-4135-8968-2ed47a665cf8)" failed: rpc error: code = Unknown desc = error reading container (probably exited) json message: EOF                                                                                                                  
```

**What you expected to happen**:
Pods startup should not encounter EOF while reading any json (or any other file). 

**How to reproduce it (as minimally and precisely as possible)**:
Observed while running this OpenShift test case,
https://github.com/openshift/origin/blob/e49fe16bd3eb5a177d04e59739bc91864d608d1c/vendor/k8s.io/kubernetes/test/e2e/node/pods.go#L311

**Anything else we need to know?**:
It seems that we hit the race where the Pod attempts to start, and then Kubelet tears it down. There is a corresponding openshift bugzilla to track this issue, https://bugzilla.redhat.com/show_bug.cgi?id=1915085

**Environment**:
- Kubernetes version (use `kubectl version`):
1.20

- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by rphillips** [comment]
Related to https://github.com/kubernetes/kubernetes/issues/98142

**Comment by ehashman** [comment]
/triage accepted
/priority important-soon

not sure if this merits critical-urgent

**Comment by ehashman** [comment]
I think we're hitting the race condition as follows:

- Pod gets created
- Pod starts creating a sandbox
- Pod gets deleted, sandbox creation hasn't completed yet
- CreatePodSandbox fails

From what I can see, this is due to a flaw in `SyncPod`'s logic:

https://github.com/kubernetes/kubernetes/blob/d70ee902fddc682863a3cc4f0d8eac0223ebf70b/pkg/kubelet/kuberuntime/kuberuntime_manager.go#L666-L675

At any step in this sync loop, the pod could be deleted, but this code proceeds with the assumption that the underlying state as initially checked hasn't changed. So by the time we get to creating the sandbox, it might not even be necessary, and it can fail if the pod is deleted partway through:

https://github.com/kubernetes/kubernetes/blob/d70ee902fddc682863a3cc4f0d8eac0223ebf70b/pkg/kubelet/kuberuntime/kuberuntime_manager.go#L743-L755

 @rphillips suggested that we could pass in `PodManager` to lock critical state, but if we lock the pod for the duration of this sync loop, would there be performance implications? It's quite long.

**Comment by dims** [comment]
@harche @ehashman Looks like this message originates from cri-o:
https://github.com/cri-o/cri-o/blob/master/internal/oci/runtime_oci.go#L214-L216

Have we seen this (or similar) in containerd? (what did that error message look like?)

**Comment by dims** [comment]
Also, i don't see the `CreatePodSandbox for pod` in the community CI logs:
https://storage.googleapis.com/k8s-gubernator/triage/index.html?pr=1&text=CreatePodSandbox%20for%20pod

**Comment by haircommander** [comment]
@dims for some background on what I believe is happening when this message comes up:
the `EOF` error comes from runc being killed. What it seems is happening is:
cri-o attempts to create the container, and is waiting on runc to finish.
kubelet gets the delete call, but sees the pod hasn't finished creating. Because it can't ask to RemovePodSandbox (it doesn't have an ID yet), it tears down the cgroup.
in tearing down the cgroup, systemd seems to SIGKILL runc. 

That output we're seeing is cri-o reporting that the runc process took too long, and is specific to cri-o. I wouldn't know what it would look like for containerd. Do y'all use systemd cgroup driver by default? that may also be part of it.

Ultimately, I believe this error really comes from the coordination between the kubelet sync loops:
When one goroutine is in the middle of creating a pod, another tears down the pod, and that is reported as an error. 
From my perspective, either the routines should be synchronized, or the error should be swallowed by kubelet.

**Comment by dims** [comment]
cc @mikebrow

**Comment by ehashman** [comment]
/assign
so I can keep track of this
