### ISSUE TITLE
[Flaky Test] [sig-windows] Services should be able to create a functioning NodePort service for Windows

### ISSUE THREAD

**Issue by PriyankaH21** [kubernetes/kubernetes#98499]
**Which jobs are flaking**:  

- `ci-kubernetes-e2e-aks-engine-azure-master-windows-containerd` 
- `ci-kubernetes-e2e-windows-gce-serial`
- `ci-kubernetes-e2e-windows-gce-1909`

**Which test(s) are flaking**:  `Services should be able to create a functioning NodePort service for Windows`

**Testgrid link**:   https://testgrid.k8s.io/sig-release-master-informing#aks-engine-azure-windows-master-containerd&include-filter-by-regex=Services%20should%20be%20able%20to%20create%20a%20functioning%20NodePort%20service%20for%20Windows

**Reason for failure**:

```
• Failure [28.049 seconds]
[sig-windows] Services
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/windows/framework.go:27
  should be able to create a functioning NodePort service for Windows [It]
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/windows/service.go:42
skipped 4955 lines unfold_more
   DNS Servers . . . . . . . . . . . : 10.0.0.10
                                       1.1.1.1
   NetBIOS over Tcpip. . . . . . . . : Disabled
   Connection-specific DNS Suffix Search List :
                                       default.svc.cluster.local
STEP: Verifying that curl queries FAIL for wrong URLs
Jan 27 09:21:58.699: INFO: ExecWithOptions {Command:[curl.exe -k https://kubernetezzzzzzzz:443] Namespace:dns-4663 PodName:e2e-dns-utils ContainerName:agnhost-container Stdin:<nil> CaptureStdout:true CaptureStderr:true PreserveWhitespace:false Quiet:false}
Jan 27 09:21:58.699: INFO: >>> kubeConfig: /root/tmp321700220/kubeconfig/kubeconfig.southcentralus.json
STEP: Verifying that injected dns records for 'kubernetes' resolve to the valid ip address
Jan 27 09:22:00.724: INFO: ExecWithOptions {Command:[curl.exe -k https://kubernetes:443] Namespace:dns-4663 PodName:e2e-dns-utils ContainerName:agnhost-container Stdin:<nil> CaptureStdout:true CaptureStderr:true PreserveWhitespace:false Quiet:false}
Jan 27 09:22:00.724: INFO: >>> kubeConfig: /root/tmp321700220/kubeconfig/kubeconfig.southcentralus.json
skipped 1756 lines unfold_more
[Fail] [sig-windows] Services [It] should be able to create a functioning NodePort service for Windows
```

**Anything else we need to know**:

**Triage link:** https://storage.googleapis.com/k8s-gubernator/triage/index.html?test=Services%20should%20be%20able%20to%20create%20a%20functioning%20NodePort%20service%20for%20Windows

**Spyglass links:** 
- https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-windows-gce-1909/1353101375789076480
- https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-aks-engine-azure-master-windows-containerd/1354343926944763904

> 
NOTES:  tests have been failing on and off since a build on _1/12/2021_

/sig windows 
/priority important-soon

**Comment by jsturtevant** [comment]
Hadn't seen this in a week or twoo but it popped up yesterday:

https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-aks-engine-azure-master-windows-containerd/1370276426229485568
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-aks-engine-azure-master-windows-containerd/1370048629514964992

**Comment by jsturtevant** [comment]
error:

```
/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/windows/service.go:42
Mar 11 17:03:32.886: Failed after 11.467s.
Unexpected error:
    <exec.CodeExitError>: {
        Err: {
            s: "command terminated with exit code 28",
        },
        Code: 28,
    }
    command terminated with exit code 28
occurred
/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/windows/hybrid_network.go:97
```

**Comment by jsturtevant** [comment]
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-aks-engine-azure-master-windows-containerd/1384425538617085952

**Comment by jsturtevant** [comment]
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-windows-gce-20h2-1-21/1384276803606024192

```
Apr 19 23:30:43.073: Failed after 4.386s.
Unexpected error:
    <exec.CodeExitError>: {
        Err: {
            s: "command terminated with exit code 55",
        },
        Code: 55,
    }
```

**Comment by ravisantoshgudimetla** [comment]
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-windows-gce-2019/1391704790509031424

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/windows/service.go:42
May 10 11:24:19.866: Failed after 10.817s.
Unexpected error:
    <exec.CodeExitError>: {
        Err: {
            s: "command terminated with exit code 28",
        },
        Code: 28,
    }
    command terminated with exit code 28
```

**Comment by jsturtevant** [comment]
xref: https://github.com/kubernetes/kubernetes/issues/101907

**Comment by claudiubelu** [comment]
I've tried to replicate it as well, but to no avail, so I only had to dig through the logs of the current failures.

curl exit code 28 means timeout, so that means that Kubeproxy might not have set up the NodePort properly (stopping the Kubeproxy service on the Windows nodes will also cause this test to fail).

Looking at: [0]

This test failed with the exit code 28. The nodeport pod started at 17:46:15.810. Looking at the kubeproxy logs [1], we can see that no policies could be applied too much before that time, there are no associated endpoints for that service. When the endpoints appeared, the following error then occured:

```
I0620 17:46:15.219267    2876 proxier.go:1207] "Hns LoadBalancer resource created for cluster ip resources" clusterIP="10.0.102.224" hnsID="d3ac33eb-a1f8-40ff-8a22-4381e580eb00"
E0620 17:46:15.265974    2876 proxier.go:1227] "Policy creation failed" err="hcnCreateLoadBalancer failed in Win32: The specified port already exists. (0x803b0013) {\"Success\":false,\"Error\":\"The specified port already exists. \",\"ErrorCode\":2151350291}"
```

Which might be this error [2], since the service has a node port. Didn't see ``nodePort 31079`` being logged for any other service in the kubeproxy logs. After that failure, kubeproxy did not retry to apply the policies for that service. The service was expected to be reachable at: 17:46:22.044.

Looking at [3], the situation is a bit different. The policies for the node port service are not applied at all. The nodeport pod starts at 17:34:00.814, and in the kube-proxy logs, we can see:

```
I0614 17:33:58.843311    3764 service_health.go:183] Not saving endpoints for unknown healthcheck "services-2588/nodeport-test"
I0614 17:33:58.843311    3764 service_health.go:183] Not saving endpoints for unknown healthcheck "services-5439/nodeport-test"
```

Basically, the test fails because the NodePort is not properly configured / set up on the Windows node.

On the testing side, we're are currently asserting the connectivity with ``gomega.Consistently``. I'd suggesting adding a ``gomega.Eventually`` before the ``gomega.Consistently``, so we can first wait and make sure the networking connectivity works first, then assert the consistent behaviour. This might reduce the flakes due to transient errors when setting the policies (first case, if kube-proxy would attempt to set the proper policies afterwards).

[0] https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-aks-engine-azure-master-windows-containerd/1406660931156447232
[1] https://paste.ubuntu.com/p/BrDf44BswY/
[2] https://github.com/kubernetes/kubernetes/blob/6010cbe593f88fbddae78e43e40842e95ba3f2a1/pkg/proxy/winkernel/proxier.go#L1227
[3] https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-aks-engine-azure-master-windows-containerd/1404479980338941952

**Comment by mkorbi** [comment]
looks resolved for now

**Comment by jsturtevant** [comment]
We are still seeing this occasionally. I believe it is either an OS bug or a race condition with kube-proxy and container start up.

https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-aks-engine-azure-master-windows-containerd/1417370848683102208
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-aks-engine-azure-master-windows-containerd-1-22/1419954732759257088

**Comment by ravisantoshgudimetla** [comment]
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-aks-engine-azure-master-windows-containerd/1437494476271521792

Another failure ^

**Comment by jyotimahapatra** [comment]
@sbangari , 👋 I'm the bug triage shadow. Since we're in code freeze, i wanted to check if this issue is still in works or resolved. Please do let us know.

**Comment by jsturtevant** [comment]
There were two issues here, the issue with the test timing should be fixed by https://github.com/kubernetes/kubernetes/pull/103371 and the other is node port overlaps which should be fixed https://github.com/Azure/aks-engine/pull/4767

Once the aks-engine fix is in I will monitor for this error.

**Comment by jsturtevant** [comment]
We saw this in 1.23 since #4767 merged:

https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-aks-engine-azure-master-windows-containerd-1-23/1467985491969183744


```
 "Service updated ports" service="services-7054/nodeport-test" portCount=1
I1206 22:55:55.781946    2864 service.go:419] "Adding new service port" portName="services-7054/nodeport-test" servicePort="10.0.89.142:80/TCP"
I1206 22:55:55.781946    2864 proxier.go:1026] "Syncing Policies"
I1206 22:55:55.781946    2864 proxier.go:1192] "Associated endpoints for service" endpointsInfo=[] serviceName="services-7054/nodeport-test"
E1206 22:55:55.781946    2864 proxier.go:1200] "Endpoint information not available for service, not applying any policy" serviceName="services-7054/nodeport-test"
I1206 22:55:55.781946    2864 bounded_frequency_runner.go:296] sync-runner: ran, next possible in 1s, periodic in 30s
I1206 22:56:00.912636    2864 endpointslicecache.go:358] "Setting endpoints for service port name" portName="services-7054/nodeport-test" endpoints=[10.240.0.75:80]
I1206 22:56:00.912691    2864 proxier.go:327] "Endpoints are modified. Service is stale" servicePortName="services-7054/nodeport-test"
I1206 22:56:00.912691    2864 proxier.go:766] "Service cleanup" serviceInfo="10.0.89.142:80/TCP"
I1206 22:56:00.912691    2864 proxier.go:1026] "Syncing Policies"
I1206 22:56:00.912691    2864 proxier.go:1192] "Associated endpoints for service" endpointsInfo=[] serviceName="services-7054/nodeport-test"
E1206 22:56:00.912691    2864 proxier.go:1200] "Endpoint information not available for service, not applying any policy" serviceName="services-7054/nodeport-test"
I1206 22:56:00.912691    2864 bounded_frequency_runner.go:296] sync-runner: ran, next possible in 1s, periodic in 30s
I1206 22:56:01.962297    2864 endpointslicecache.go:358] "Setting endpoints for service port name" portName="services-7054/nodeport-test" endpoints=[10.240.0.75:80]
I1206 22:56:01.962297    2864 endpointslicecache.go:358] "Setting endpoints for service port name" portName="services-7054/nodeport-test" endpoints=[10.240.0.75:80]
I1206 22:56:01.962297    2864 proxier.go:327] "Endpoints are modified. Service is stale" servicePortName="services-7054/nodeport-test"
I1206 22:56:01.962297    2864 proxier.go:766] "Service cleanup" serviceInfo="10.0.89.142:80/TCP"
I1206 22:56:01.962894    2864 proxier.go:421] "Endpoint cleanup" endpointsInfo="10.240.0.75:80"
I1206 22:56:01.962894    2864 proxier.go:327] "Endpoints are modified. Service is stale" servicePortName="services-7054/nodeport-test"
I1206 22:56:01.962894    2864 proxier.go:766] "Service cleanup" serviceInfo="10.0.89.142:80/TCP"
I1206 22:56:01.962894    2864 proxier.go:421] "Endpoint cleanup" endpointsInfo="10.240.0.75:80"
I1206 22:56:01.962894    2864 proxier.go:1026] "Syncing Policies"
I1206 22:56:01.966156    2864 proxier.go:1176] "Hns endpoint resource" endpointsInfo="10.240.0.75:0"
I1206 22:56:01.966156    2864 proxier.go:1189] "Endpoint resource found" endpointsInfo="10.240.0.75:80"
I1206 22:56:01.966156    2864 proxier.go:1192] "Associated endpoints for service" endpointsInfo=[{ip:10.240.0.75 port:0 isLocal:true macAddress:00-15-5D-F0-F3-54 hnsID:04b8480a-3163-4567-9bc8-7c79d5f3f12e refCount:<nil> providerAddress: hns:{} ready:false serving:false terminating:false}] serviceName="services-7054/nodeport-test"
I1206 22:56:01.977107    2864 hnsV2.go:284] "Hns loadbalancer policy resource" loadBalancer=&{Id:26d5be8f-0e9b-4d4e-b9c9-7a8a82558600 HostComputeEndpoints:[04b8480a-3163-4567-9bc8-7c79d5f3f12e] SourceVIP: FrontendVIPs:[10.0.89.142] PortMappings:[{Protocol:6 InternalPort:80 ExternalPort:80 DistributionType:0 Flags:0}] SchemaVersion:{Major:2 Minor:0} Flags:0}
I1206 22:56:01.977107    2864 proxier.go:1231] "Hns LoadBalancer resource created for cluster ip resources" clusterIP="10.0.89.142" hnsID="26d5be8f-0e9b-4d4e-b9c9-7a8a82558600"
I1206 22:56:01.985897    2864 hnsV2.go:284] "Hns loadbalancer policy resource" loadBalancer=&{Id:a5ecc968-45bc-4d17-b8df-46a18d9d9b7f HostComputeEndpoints:[04b8480a-3163-4567-9bc8-7c79d5f3f12e] SourceVIP: FrontendVIPs:[] PortMappings:[{Protocol:6 InternalPort:80 ExternalPort:31735 DistributionType:0 Flags:2}] SchemaVersion:{Major:2 Minor:0} Flags:0}
I1206 22:56:01.985897    2864 proxier.go:1256] "Hns LoadBalancer resource created for nodePort resources" clusterIP="10.0.89.142" hnsID="a5ecc968-45bc-4d17-b8df-46a18d9d9b7f"
I1206 22:56:01.985897    2864 proxier.go:1307] "Policy successfully applied for service" serviceInfo="10.0.89.142:80/TCP"
I1206 22:56:01.985897    2864 service_health.go:258] "Not saving endpoints for unknown healthcheck" service="services-7054/nodeport-test"
I1206 22:56:01.985897    2864 bounded_frequency_runner.go:296] sync-runner: ran, next possible in 1s, periodic in 30s
I1206 22:56:05.023061    2864 utils.go:180] "Skipping service due to cluster IP" service="statefulset-6617/test" clusterIP="None"
I1206 22:56:30.345263    2864 endpointslicecache.go:358] "Setting endpoints for service port name" portName="services-7054/nodeport-test" endpoints=[10.240.0.75:80]
I1206 22:56:30.345263    2864 endpointslicecache.go:358] "Setting endpoints for service port name" portName="services-7054/nodeport-test" endpoints=[10.240.0.75:80]
I1206 22:56:30.345263    2864 proxier.go:327] "Endpoints are modified. Service is stale" servicePortName="services-7054/nodeport-test"
I1206 22:56:30.345263    2864 proxier.go:766] "Service cleanup" serviceInfo="10.0.89.142:80/TCP"
I1206 22:56:30.365455    2864 proxier.go:421] "Endpoint cleanup" endpointsInfo="10.240.0.75:80"
I1206 22:56:30.365455    2864 proxier.go:327] "Endpoints are modified. Service is stale" servicePortName="services-7054/nodeport-test"
I1206 22:56:30.365455    2864 proxier.go:766] "Service cleanup" serviceInfo="10.0.89.142:80/TCP"
I1206 22:56:30.365455    2864 proxier.go:421] "Endpoint cleanup" endpointsInfo="10.240.0.75:80"
I1206 22:56:30.365455    2864 proxier.go:1026] "Syncing Policies"
I1206 22:56:30.365455    2864 proxier.go:1192] "Associated endpoints for service" endpointsInfo=[] serviceName="services-7054/nodeport-test"
E1206 22:56:30.365455    2864 proxier.go:1200] "Endpoint information not available for service, not applying any policy" serviceName="services-7054/nodeport-test"
I1206 22:56:30.365455    2864 bounded_frequency_runner.go:296] sync-runner: ran, next possible in 1s, periodic in 30s
I1206 22:56:30.540170    2864 endpointslicecache.go:358] "Setting endpoints for service port name" portName="services-7054/nodeport-test" endpoints=[10.240.0.75:80]
I1206 22:56:30.540170    2864 proxier.go:327] "Endpoints are modified. Service is stale" servicePortName="services-7054/nodeport-test"
I1206 22:56:30.540170    2864 proxier.go:766] "Service cleanup" serviceInfo="10.0.89.142:80/TCP"
I1206 22:56:30.540170    2864 proxier.go:421] "Endpoint cleanup" endpointsInfo="10.240.0.75:80"
I1206 22:56:30.540170    2864 proxier.go:1026] "Syncing Policies"
I1206 22:56:30.540170    2864 proxier.go:1192] "Associated endpoints for service" endpointsInfo=[] serviceName="services-7054/nodeport-test"
E1206 22:56:30.540170    2864 proxier.go:1200] "Endpoint information not available for service, not applying any policy" serviceName="services-7054/nodeport-test"
I1206 22:56:30.540170    2864 bounded_frequency_runner.go:296] sync-runner: ran, next possible in 1s, periodic in 30s
I1206 22:56:30.639314    2864 service.go:304] "Service updated ports" service="services-7054/nodeport-test" portCount=0
I1206 22:56:31.540866    2864 proxier.go:374] "Updating existing service port" servicePortName="services-7054/nodeport-test" clusterIP="10.0.89.142" port=80 protocol=TCP
I1206 22:56:31.540866    2864 proxier.go:766] "Service cleanup" serviceInfo="10.0.89.142:80/TCP"
I1206 22:56:31.541973    2864 service.go:444] "Removing service port" portName="services-7054/nodeport-test"
I1206 22:56:31.541973    2864 proxier.go:1026] "Syncing Policies"
```

**Comment by marosset** [comment]
We believe this issue is fixed (at least for aks-engine and CAPZ) by changing some port ranges on the node before running tests.
https://github.com/Azure/aks-engine/pull/4767

**Comment by marosset** [comment]
https://github.com/kubernetes-sigs/image-builder/pull/750
Is the change for CAPZ

**Comment by jsturtevant** [comment]
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-capz-master-containerd-windows/1529043803770458112

**Comment by jsturtevant** [comment]
/reopen 
flake here: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-capz-master-containerd-windows/1623362894328500224

**Comment by marosset** [comment]
/help
This is something that could probably be fixed in Calico but is not a beginner friendly issue

**Comment by ionutbalutoiu** [comment]
I've seen this reproduced in the `sig-windows-networking` testing jobs at:
* https://prow.k8s.io/view/gs/k8s-ovn/logs/k8s-e2e-ltsc2019-containerd-flannel-sdnoverlay-stable/1652870464898338816
* https://prow.k8s.io/view/gs/k8s-ovn/logs/aks-e2e-ltsc2019-azurecni-1.25/1651073859601829888

Besides this, I've also noticed the `sig-windows-master-release` testing jobs have the same flakiness:
* https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-capz-master-windows/1647901555103371264
* https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-capz-master-windows/1648945478588436480

The error seems similar to all the failures:
```
Err: command terminated with exit code 28
[FAILED] Timed out after 10.315s.
Unexpected error:
    <exec.CodeExitError>: 
    command terminated with exit code 28
    {
        Err: <*errors.errorString | 0xc00614dd40>{
            s: "command terminated with exit code 28",
        },
        Code: 28,
    }
```

I spawned an AKS 1.26 cluster and repeatedly ran this test isolated with `--until-it-fails=true` ginkgo flag.

The same issue eventually reproduced.

However, I also used `--delete-namespace-on-failure=false` gingko flag. Every time the issue reproduced, I would manually run the same check on the failure namespace, and it would succeed.

From my observation, sometimes the Windows `NodePort` takes longer to be available, and we are using a timeout of 10 secs to wait for the initial connectivity.

This is the code to assert network connectivity in the test:
https://github.com/kubernetes/kubernetes/blob/d952437921049891bcf69a6aa242d99069db92fb/test/e2e/windows/hybrid_network.go#L104-L122

In the PR https://github.com/kubernetes/kubernetes/pull/103371, a `gomega.Eventually` was added with the purpose to wait for networking connectivity first. But, it uses a timeout of 10 secs.

Sometimes, I noticed that the `NodePort` becomes available within 13 to 15 secs (but it always became available without any issue in my testing).

If it makes sense, I proposed the following PR https://github.com/kubernetes/kubernetes/pull/117721 to increase the timeout that checks the initial connectivity.

I choose 30 secs initial connectivity check timeout, since I noticed that the `[sig-network]` tests use the following timeout / retries logic:
https://github.com/kubernetes/kubernetes/blob/d952437921049891bcf69a6aa242d99069db92fb/test/e2e/framework/network/utils.go#L77
https://github.com/kubernetes/kubernetes/blob/d952437921049891bcf69a6aa242d99069db92fb/test/e2e/framework/network/utils.go#L778-L779

and in the jobs that execute these tests, I see the following log:
```
INFO: Setting MaxTries for pod polling to 34 for networking test based on endpoint count 2
```

Thus, having a timeout of 30 secs seems aligned with the max retries used by the `[sig-network]` tests.
Besides this, I didn't reproduce the E2E failure using the increased timeout.

**Comment by jsturtevant** [comment]
@claudiubelu found some more information on this running across nodes and will post some finding soon.

**Comment by pacoxu** [comment]
https://testgrid.k8s.io/sig-release-master-informing#capz-windows-master&include-filter-by-regex=Services%20should%20be%20able%20to%20create%20a%20functioning%20NodePort%20service%20for%20Windows is quite green. 

https://storage.googleapis.com/k8s-triage/index.html?test=Services%20should%20be%20able%20to%20create%20a%20functioning%20NodePort%20service%20for%20Windows
only two flake on `ci-kubernetes-e2e-capz-master-windows-hyperv` with many others: so I think this is not an issue now
- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-capz-master-windows-hyperv/1758068258184892416
- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-capz-master-windows-hyperv/1755531325747499008

/close
