### ISSUE TITLE
Avoid Python in shell-scripts (e.g., kube-addons.sh) to be compatible with CoreOS.

### ISSUE THREAD

**Issue by erimatnor** [kubernetes/kubernetes#9849]
Kubernetes v0.19.0 breaks kube-addons.sh on CoreOS because it includes some Python code. I am running a setup where Fleet installs Kubernetes on CoreOS from the official tar-ball, basically extracting and installing Kubernetes similar to how Salt does it. This works fine in Kubernetes v0.18.2, but kube-addons.sh now fails on CoreOS because of the use of Python. It would be good if system services avoid Python and other heavy interpreted languages that require big installs that might not be available on all platforms.

**Comment by mikedanese** [comment]
@yifan-gu @kelseyhightower do coreos setups include kube-addons?

**Comment by bakins** [comment]
@mikedanese when using `kube-up.sh`, we still use Debian (or Ubuntu) for the master node which handles the add-ons.

**Comment by zmerlynn** [comment]
We really want to rewrite `kube-addons.sh` in Go, but it's not going to land until after 1.0. cc @marekbiskup .

**Comment by yifan-gu** [comment]
> We really want to rewrite kube-addons.sh in Go, but it's not going to land until after 1.0. cc @marekbiskup .

Good to know. But CoreOS production image does not have go binaries either...

**Comment by zmerlynn** [comment]
You don't need Go binaries. If we rewrite it in Go, we'll compile it and
ship it as an executable like everything else.

**Comment by yifan-gu** [comment]
@zmerlynn Awesome! :+1:

**Comment by marekbiskup** [comment]
@erimatnor, we will get rid of this python by #9470, but surely after 1.0 (this will be one of my first tasks after 1.0).

Is this issue a blocker for 1.0? If so we'll have to workaround it quickly. 
Python is used in bash to extract fields from yamls. Maybe by writing a small binary that does the same job.

Could you also tell me how I can reproduce the problem? (So far I used GCE installations only.)

**Comment by davidopp** [comment]
@thockin @lavalamp

**Comment by davidopp** [comment]
Here are the relevant places where we currently use Python (i.e. stuff that might be used on CoreOS):

* https://github.com/GoogleCloudPlatform/kubernetes/blob/41545d0a66e79e5747302f81400b5909514b6276/cluster/gce/util.sh [in get-password]
* https://github.com/GoogleCloudPlatform/kubernetes/blob/5520386b180d3ddc4fa7b7dfe6f52642cc0c25f3/build/json-extractor.py [this is a Python script; I'm not sure how this is used]
* https://github.com/GoogleCloudPlatform/kubernetes/blob/82aa8f998445ec49bf9756f77d2ffadf317965c6/cluster/aws/coreos/util.sh [in detect-minion-image]
* https://github.com/GoogleCloudPlatform/kubernetes/blob/5520386b180d3ddc4fa7b7dfe6f52642cc0c25f3/cluster/saltbase/salt/_states/container_bridge.py [IIUC this is a pretty core part of running containers; how does it work without Python?]
* https://github.com/GoogleCloudPlatform/kubernetes/blob/5aa0219adad149353c0b3fbd5c18c0e5fbd5c7ad/cluster/gce/configure-vm.sh [this is used for some simple text processing--we should be able to replace it with shell or awk?]
* https://github.com/GoogleCloudPlatform/kubernetes/blob/5596e6f789c92ff8589ce84e30cd5c82d7214966/cluster/saltbase/salt/kube-addons/kube-addons.sh [same as above]
* https://github.com/GoogleCloudPlatform/kubernetes/blob/8a9e0e00bfeb938d7e701268dfd70b8f5641e5e8/cluster/saltbase/salt/kube-addons/kube-addon-update.sh [same as above]

**Comment by dchen1107** [comment]
cc/ @kelseyhightower @philips @brendandburns It is pretty bad at the last minutes we break coreos on different cloud providers. I believe it still works on GCE since I leave the master node using Debian by default. Supporting CoreOS on different cloud providers is required for 1.0 release or not?

**Comment by davidopp** [comment]
Yeah, it would be good if someone could explain the scope of this issue, because I'm very confused. As you can see, we already have python code that surely is running even on CoreOS setups. I don't understand what's special about the kube-addons scripts, or (like @dchen1107 asked) which cloud providers (and/or bare metal) this issue affects. Would be good to get more details ASAP.

**Comment by thockin** [comment]
Just to be clear, if we don't figure this out Kubernetes v1.0 might be broken on CoreOS.  We really REALLY don't want to do that, but we clearly do not have enough coverage to call CoreOS a first-tier supported distro right now.  Help us, CoreOS folks.

**Comment by dchen1107** [comment]
@davidopp Thanks for find all places in the code using python. 

Actually only last two listed by https://github.com/GoogleCloudPlatform/kubernetes/issues/9849#issuecomment-112940384: kube-addons.sh and kube-addon-update.sh has the issues since both are required to run on coreos node. The fix should be simple similar to what I did for running minion-node with coreos. 

I am busy for now. But if it is required for 1.0 and CoreOS folks cannot get to it, I could take care of it sometimes tomorrow.

**Comment by davidopp** [comment]
Thanks for the details. But I don't understand what is special about the kube-addons* scripts. They run on the master, right? Likewise doesn't cluster/gce/configure-vm.sh (which uses python) also run on the master? It is called from here
https://github.com/GoogleCloudPlatform/kubernetes/blob/4d251212065ffa6b797f3991fb572e4d3522294a/cluster/gce/coreos/helper.sh

**Comment by dchen1107** [comment]
@davidopp that is why I am asking earlier coreos on which cloudprovider? Obviously it is not on gce, because like what i said above, I didn't spend time on converting master node earlier because my goal is demo coreos + rkt, and rkt is ready for running complicated container like master components back then. 

With GCE cloud provider including GKE, configure-vm.sh are running on every debian node, but no need for coreos node since I provided a cloud_init.yaml to take care the same functionalities. 

On some other cloud providers, like aws, master node is using coreos dist, which tries to run kube-addons.sh. We just need to convert those into some cloud_init services ...

**Comment by bakins** [comment]
For CoreOS in ./cluster, none of the python ever runs on a CoreOS system. It either runs on the client calling `kube-up` or on the master, which is still Ubuntu/Debian when using the cluster scripts.  All of the CoreOS setup is done via cloud-config using shell scripts and systemd units.

I'll go back through the GCE and AWS cluster scripts ASAP.

**Comment by erimatnor** [comment]
FYI, I am not running the "official" cloud-init that comes with Kubernetes. The reason is that those do not support security and tokens, addons, etc, which means less security and modifying official pod specs that includes things like tokens. To solve this, I hacked together some fleet unit files that installs Kubernetes on CoreOS by copying the relevant components from the tar ball, including the kube-addons.sh script that ensures that addon services work (with token support). This works fine with Kubernetes v0.18.2, but broke with v0.19.0.

It would be nice if Kubernetes supported CoreOS fully down-the-line, and not only as a showcase without the extra security, etc. That's why it would be good to keep components clean from things that do not work well on CoreOS, if possible.

**Comment by thockin** [comment]
Erik,

Agree 1000% - we need to get CoreOS to be a fully-supported platform on
some set of cloud provider modules.

**Comment by erimatnor** [comment]
Btw, the reason I didn't use kube-up.sh for CoreOS is that it is a mixed environment with the master still running Salt, etc. (correct me if I am wrong). I prefer a pure CoreOS environment with the master also running CoreOS and management via Fleet for configuration (the "CoreOS way"). This keeps things simple and unified. Using Fleet has also the benefit of making Kubernetes easier to upgrade without rebooting the machines and making changes to the cloud-init. I wouldn't mind sharing my Fleet unit files if that helps, but the installation is a bit of a hack at this point. However, if a Fleet deployment would become an officially supported way of running Kubernetes I am sure things could be cleaned up without too much work.

**Comment by bakins** [comment]
We (CoreOS) are working on "official" Kubernetes on CoreOS documentation, scripts, configs, and recommendations. This will cover initial install, upgrades, etc.  The current scripts in ./cluster were the fast path to get the e2e tests running on CoreOS.  The add-ons do work on CoreOS, just not using the current tooling in this repo. An official recommended way of deploying the add-ons will be included in our work. 

@philips @kelseyhightower any comments?

@erimatnor I'd like to see your Fleet unit files.  I'm interested in what the community is doing with the toolset.

**Comment by kelseyhightower** [comment]
@bakins I think the first step here is to highlight what is broken on CoreOS as of 0.19.0 so we can possibly workaround it before 1.0.

**Comment by kelseyhightower** [comment]
@thockin @dchen1107 @davidopp Say we are able to find the areas where the kube-addons.sh script does not work on CoreOS, what is deadline to get a fix in place to remain a fully support OS?

**Comment by kelseyhightower** [comment]
@thockin @dchen1107 @davidopp It would also help if we clarify what being a supported OS means. Does that mean kubeup.sh and kube-addons.sh scripts must work for each supported OS? I would also imagine a requirement for all the e2e tests to pass as well. Thanks.

**Comment by erimatnor** [comment]
@bakins and those interested.

Put my scripts, cloud-init and Fleet files here: 

https://github.com/iobeam/coreos-kubernetes

**Comment by dchen1107** [comment]
@kelseyhightower, @erictune is working a suite of conforming tests for cloud providers based on our current e2e-test suites, but not limited to it, so we and kubernetes community can maintain so many different cloud providers. We should have that as soon as possible, but I don't think that is in 1.0 scope. 

CoreOS distro makes the problem even more interesting, since each provider can have different OS distros available. Today GCE and GKE by default are using Debian, and AWS has CoreOS support, but not default either. But fully supporting CoreOS definitely in our roadmap, if we could shoot for 1.0 roadmap, that is great, but I don't think it is required for 1.0 though. 

For this particular issue, since it is pretty safe to other cloud providers and OS distros, I can accept the workaround by end of this week. 

cc/ @brendandburns

**Comment by thockin** [comment]
Until we have conformance "supported" really means one of two things:  a)
That people use and develop on it every day b) that some specific
kubernetes binary release works with some specific set of
tools/instructions to reliably bring up a cluster

**Comment by davidopp** [comment]
Do we consider this a 1.0 blocker? By "this" I mean
https://github.com/GoogleCloudPlatform/kubernetes/issues/9849#issuecomment-113161032
("We (CoreOS) are working on "official" Kubernetes on CoreOS documentation, scripts, configs, and recommendations. This will cover initial install, upgrades, etc. The current scripts in ./cluster were the fast path to get the e2e tests running on CoreOS. The add-ons do work on CoreOS, just not using the current tooling in this repo. An official recommended way of deploying the add-ons will be included in our work.")

Do we have an ETA for that work?

The reason I ask is that we have been letting this issue (and related issue #9470) wallow in 1.0-candidate for several days. It does sound like we can move #9470 to 1.0-post though, since @erimatnor implied they will make everything work.

**Comment by bakins** [comment]
@davidopp I wouldn't I'd let any docs work we are doing hold up those PR's.

**Comment by davidopp** [comment]
Sorry to be pedantic, but I still don't understand the status of this issue.

@marekbiskup 's PR (listed above) looks too risky to me for us to push in at this point. But it's also not clear to me (1) whether we're actually broken on CoreOS or we just broke clusters created by @erimatnor 's custom scripts, and (2) if we're broken on CoreOS, do we need to fix it and if so what is the plan for doing so?

@bakins @kelseyhightower could one of you please clarify?

**Comment by davidopp** [comment]
(And by broken, I mean for addon pods only, of course.)

**Comment by yifan-gu** [comment]
@davidopp From my understading, 
(1) Having python scripts in addon.sh (as the last two cases you mentioned [here](https://github.com/GoogleCloudPlatform/kubernetes/issues/9849#issuecomment-112940384)) will break the master node if it is using CoreOS. We are not breaking the current CoreOS cluster on gce/aws as the master node is still ubuntu (I am glad to dive into it and make the cluster fully CoreOS).

(2) As @jlowdermilk pointed out (https://github.com/GoogleCloudPlatform/kubernetes/pull/10223#issuecomment-114620736) Rewriting `kube-addon.sh` sounds better and easier to me.

**Comment by yifan-gu** [comment]
Edit: CoreOS on gce has python installed, so won't break anyway. And @bakins is working on this.

**Comment by jedsmith** [comment]
@yifan-gu Not quite accurate. In the list of Python candidates that was dumped above, I see at least one shebang that expects Python in-path, because it shebangs via `env`. My comment to you about Google vendoring Python on GCE is related to their internal stuff, and any Python code needs to reach that interpreter directly or rewrite a shebang. Google does this; their daemons are shebanged `/usr/bin/env python` but they are working around it by invoking the interpreter at `/usr/share/oem/python/bin/python2.7` directly.

Anything that does `#!/usr/bin/env python` will absolutely break on CoreOS out-of-the-box because of the nature of `/usr`, Python's usual home at `/usr/bin/python`, Python not in path under OEM, etc...

**Comment by thockin** [comment]
I'm with David - I don't know the status of this - is it a real issue right now for the currently supported platforms?

**Comment by davidopp** [comment]
@yifan-gu @bakins @kelseyhightower 

Could one of you verify that CoreOS on GCE and AWS currently works, including the addons? If so, we can move this issue to post-1.0. We're getting *really* down to the wire for 1.0, so if we need to do something to make this work, it would be really good to know now.

**Comment by bakins** [comment]
@davidopp Currently, `./cluster/kube-up.sh` can create worker nodes on CoreOS for AWS and GCE if certain env vars are set. The master is still Debian and add-ons are set up there. Kubelet, kube-proxy, and the pods for the add-ons run just fine on the CoreOS nodes.

**Comment by davidopp** [comment]
@bakins Thanks. So IIUC the only thing that's critical for 1.0 is to document the env vars you need to set for CoreOS before running kube-up.sh? I didn't see any env vars mentioned in the first few docs at
https://github.com/GoogleCloudPlatform/kubernetes/blob/8813c955182e3c9daae68a8257365e02cd871c65/docs/getting-started-guides/coreos.md

**Comment by thockin** [comment]
I'm moving this to the post 1.0 category.  Scream if I am misinterpreting.

**Comment by davidopp** [comment]
Wasn't @dchen1107 saying there was something to do, and she would do it?

**Comment by davidopp** [comment]
It looks like the stuff alluded to earlier in the thread is released now?
https://coreos.com/blog/official-kubernetes-on-coreos/

We should link to this from
https://github.com/kubernetes/kubernetes/blob/master/docs/getting-started-guides/coreos.md
I would think.

**Comment by yifan-gu** [comment]
cc @robszumski

**Comment by robszumski** [comment]
@davidopp discussing this in https://github.com/kubernetes/kubernetes/issues/14205

**Comment by davidopp** [comment]
@dchen1107 @bakins Can we close this issue?

**Comment by yifan-gu** [comment]
@davidopp Not yet, I am working on this.

**Comment by justinsb** [comment]
Suggest we close this now:

1) kube-addons runs in a container
2) kube-up is in maintenance mode
3) GCI is very similar to CoreOS, and is now under e2e testing, so we know it is possible.

**Comment by mikedanese** [comment]
Agree.
