### ISSUE TITLE
NodeAffinity issue for preemptible nodes

### ISSUE THREAD

**Issue by jayaram250** [kubernetes/kubernetes#98534]
This is the current configuration that is running in a GCP GKE-cluster,
kubernetes version: 1.18.12-gke.1205
Release channel: Regular channel
Master zone	: Asia-south1-c
node-version : 1.18.12-gke.1205
Pre-emptible nodes: Enabled

We are facing the below error for preemptible nodes whenever the node is restarted and this error is specific to all the pods running in that node. But we are not using any node affinity configuration in our deployment.
status:
  **message: **Pod Predicate NodeAffinity failed**
  phase: Failed
  reason: NodeAffinity**
  Can someone help with the root cause?

**Comment by ehashman** [comment]
/sig node

Take a look at #92067 and https://github.com/kubernetes/kubernetes/pull/94087.

This was fixed in 1.21.

There are cherry-picks pending for 1.19 and 1.20 for the next patch release.

This has not been fixed in 1.18 because the backport doesn't merge cleanly and I don't have the time to get it working: https://github.com/kubernetes/kubernetes/pull/97997

/close

**Comment by maxpain** [comment]
The same problem on `1.22.3-gke.700`

**Comment by gillesdouaire** [comment]
We also have experienced the same problem on `v1.22.12-gke.1200`

**Comment by sharkymcdongles** [comment]
This still happens in GKE 1.24.x
