### ISSUE TITLE
Separate mount metrics and `volume_fsgroup_recursive_apply` metric to indicate how volume permission intent was full filled

### ISSUE THREAD

**Issue by gnufied** [kubernetes/kubernetes#98667]
Currently there are three or 4 ways a pod's `fsGroup` intent can be full filled:

1. It can be recursively chown/chmoded (super expensive)
2. We can check permissions of root folder and if necessary go to full recursive mode.
3. We could apply `fsGroup` as a mount option.

I am thinking we should clean this up and emit a single metric that captures this. We have two related metric for this stuff:

1.  `storage_operation_duration_seconds` which will have `volume_mount` as operation_name. This metric is a histogram which includes total time taken for mount operation.
2. We have another metric that measures how long it takes to apply permissions recursively. 

I am thinking we should rename the second metric and have it capture how the `fsGroup` intent was full filled, so as we can have more accurate information about how the permissions were applied.

cc @kubernetes/sig-storage-api-reviews 

/sig storage

**Comment by verult** [comment]
Discussed offline. Today FSGroup latency and errors are already measured by existing storage operation metrics under the `volume_apply_access_control` operation name. The benefit of adding a label in metrics to identify the path would probably be marginal since

1. the latency between Always and OnRootMismatch is the same if OnRootMismatch takes action
2. We can't measure the CSI fsgroup latency or error

It would help us identify which codepath has bugs but the logic isn't complicated enough to need that. For a particular problematic operation, we could always figure out the path based on the podspec and driver.
