### ISSUE TITLE
"BeforeSuite" test is frequently flaking

### ISSUE THREAD

**Issue by ehashman** [kubernetes/kubernetes#98707]
**Which jobs are flaking**:

Looks like many according to triage link, but certainly pull-kubernetes-e2e-gce-ubuntu-containerd (e.g. in #97968)

**Which test(s) are flaking**:

BeforeSuite

**Testgrid link**:

There's going to be a lot of testgrid links/jobs, see triage link instead: https://storage.googleapis.com/k8s-gubernator/triage/index.html?pr=1&text=BeforeSuite%20on%20Node%201%20failed

**Reason for failure**:

All BeforeSuite setups fail, so no tests run, but it still takes 35m to finish the build :(

**Anything else we need to know**:

- links to go.k8s.io/triage appreciated: above
- links to specific failures in spyglass appreciated: https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/97968/pull-kubernetes-e2e-gce-ubuntu-containerd/1356569585897181184/

**Comment by ehashman** [comment]
/sig testing

I'm not sure what's causing the failure but I haven't looked very hard

**Comment by pacoxu** [comment]
I find the error is 

> `W0202 11:47:48.766] WARNING: Download from https://storage.googleapis.com/k8s-bazel-cache/https://github.com/bazelbuild/rules_docker/releases/download/v0.14.4/rules_docker-v0.14.4.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found`


I think we should run

```
bash hack/update-workspace-mirror.sh  "https://github.com/bazelbuild/rules_docker/releases/download/v0.14.4/rules_docker-v0.14.4.tar.gz"
```
but I don’t have the access permission to run this.

**Comment by BenTheElder** [comment]
That's not the error, that's just a warning that this dependency wasn't found in our mirror, so it will download from the original source and the mirror is not available to mitigate flakes / downtime in the original host.
https://github.com/kubernetes/kubernetes/blob/cea1d4e20b4a7886d8ff65f34c6d4f95efcb4742/build/workspace_mirror.bzl

basically we tell bazel `urls = mirror("https://original.url/foo")` all over the place and then that maps `orignal.url/foo` to `https://our-mirror/original.url/foo` (something like that, see source above), `urls` is a list of urls to try. so the warning is relatively fine.

More generally:
When `BeforeSuite` fails that means:
- we completed the build succesfully (and therefore are not using bazel further)
- we started a test cluster
- we started the e2e tests
- the e2e test do not think the cluster reached a state sufficient for testing

In this case it doesn't seem to think the sysetm pods are healthy, and the actual error is:
 >Feb  2 12:13:57.216: Error waiting for all pods to be running and ready: 5 / 22 pods in namespace "kube-system" are NOT in RUNNING and READY state in 10m0s
 
 for this run https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/97968/pull-kubernetes-e2e-gce-ubuntu-containerd/1356569585897181184/

**Comment by BenTheElder** [comment]
also adding: this happens due to actual bugs in tested code sometimes, but if we're seeing it frequently across PRs, probably something else is afoot with pods readying in this test configuration ...

from that particular run in the test log we can see:

---
I0202 12:13:58.982] Feb  2 12:13:57.216: FAIL: Error waiting for all pods to be running and ready: 5 / 22 pods in namespace "kube-system" are NOT in RUNNING and READY state in 10m0s
I0202 12:13:58.982] POD                                    NODE                                   PHASE   GRACE CONDITIONS
I0202 12:13:58.983] coredns-6954c77b9b-kx2pd               e2e-e55c074026-a7d53-minion-group-hdh0 Pending       [{Type:Initialized Status:True LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2021-02-02 12:02:47 +0000 UTC Reason: Message:} {Type:Ready Status:False LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2021-02-02 12:02:47 +0000 UTC Reason:ContainersNotReady Message:containers with unready status: [coredns]} {Type:ContainersReady Status:False LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2021-02-02 12:02:47 +0000 UTC Reason:ContainersNotReady Message:containers with unready status: [coredns]} {Type:PodScheduled Status:True LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2021-02-02 12:02:47 +0000 UTC Reason: Message:}]
I0202 12:13:58.984] kube-dns-autoscaler-76478fcf46-mmtb8   e2e-e55c074026-a7d53-minion-group-74mw Pending       [{Type:Initialized Status:True LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2021-02-02 12:02:48 +0000 UTC Reason: Message:} {Type:Ready Status:False LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2021-02-02 12:02:48 +0000 UTC Reason:ContainersNotReady Message:containers with unready status: [autoscaler]} {Type:ContainersReady Status:False LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2021-02-02 12:02:48 +0000 UTC Reason:ContainersNotReady Message:containers with unready status: [autoscaler]} {Type:PodScheduled Status:True LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2021-02-02 12:02:48 +0000 UTC Reason: Message:}]
I0202 12:13:58.984] l7-default-backend-6dd8477499-ksq95    e2e-e55c074026-a7d53-minion-group-74mw Pending       [{Type:Initialized Status:True LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2021-02-02 12:02:49 +0000 UTC Reason: Message:} {Type:Ready Status:False LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2021-02-02 12:02:49 +0000 UTC Reason:ContainersNotReady Message:containers with unready status: [default-http-backend]} {Type:ContainersReady Status:False LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2021-02-02 12:02:49 +0000 UTC Reason:ContainersNotReady Message:containers with unready status: [default-http-backend]} {Type:PodScheduled Status:True LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2021-02-02 12:02:49 +0000 UTC Reason: Message:}]
I0202 12:13:58.985] metrics-server-v0.3.6-64f5546c87-slgb5 e2e-e55c074026-a7d53-minion-group-74mw Pending       [{Type:Initialized Status:True LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2021-02-02 12:02:44 +0000 UTC Reason: Message:} {Type:Ready Status:False LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2021-02-02 12:02:44 +0000 UTC Reason:ContainersNotReady Message:containers with unready status: [metrics-server metrics-server-nanny]} {Type:ContainersReady Status:False LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2021-02-02 12:02:44 +0000 UTC Reason:ContainersNotReady Message:containers with unready status: [metrics-server metrics-server-nanny]} {Type:PodScheduled Status:True LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2021-02-02 12:02:44 +0000 UTC Reason: Message:}]

---

**Comment by BenTheElder** [comment]
> All BeforeSuite setups fail, so no tests run, but it still takes 35m to finish the build :(

We spent:
- build (build sources): 4.3053109074 minutes
- stage (upload the build for pulling to the cloudy nodes): 3.119139199766666 minutes (slower than you might hope?? but not surprising, the builds are pretty large)
- extract (prepping build output for local usage or downloading it): 14.577866452 seconds
- TearDown Previous (ensure no previous leaked resources in GCP test project): 33.683839613 seconds
- Up (create cluster): 7.43342095865 minutes
- Check APIReachability (sanity probe apiserver): 0.26511064 seconds
- list nodes (~ kubectl get no > $ARTIFACTS/nodes.yaml): 0.347861642 seconds
- test setup: ~0s
- IsUp (another is sanity check): 0.356629559 seconds
- kubectl version (check client versus server version): 0.275756947 seconds
- test (actually running e2e.test): 10.58076447438333 minutes (mostly waiting for the cluster to be ready to test, then collecting some info about it)
- DumpClusterLogs (dump lots of debug stuff from the nodes to $ARTIFACTS): 2.003723411866667 minutes
- TearDown (delete the cluster resources): 5.608520463766666 minutes

https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/97968/pull-kubernetes-e2e-gce-ubuntu-containerd/1356569585897181184/artifacts/junit_runner.xml

This is unfortunately about as fast as it gets with cloudy cluster testing.

The core issue here seems to be that the clusters are not actually healthy and it takes a while to build the sources, prep the cluster and then realize that it's never going to become healthy, then dump debug info and cleanup.
/remove-sig testing
I don't think this is a SIG testing bug, we don't own containerd / kubelet / these pods.

A few pods failing to become healthy is usually SIG Node (kubelet/CRI) or Network (blame DNS / kube-proxy / ... 🙃 ) but skimming the logs I can't tell which yet.

FYI @dims for the gce-ubuntu-containerd e2e

**Comment by ehashman** [comment]
thanks so much for looking at this @BenTheElder @dims!

**Comment by BenTheElder** [comment]
Breadcrumb for anyone else reading along regarding the mirror: https://github.com/kubernetes/enhancements/issues/2420, bazel is not in use any longer. I am cleaning up remnants of the mirror system, and this job is now failing without using bazel.

**Comment by dims** [comment]
looks like this has stopped failing https://storage.googleapis.com/k8s-gubernator/triage/index.html?pr=1&text=BeforeSuite%20on%20Node.*failed

**Comment by dims** [comment]
/close

please reopen if needed
