### ISSUE TITLE
Deprecation plan for Flex Volumes?

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#98815]
FAQ says `Out-of-tree FlexVolume driver [deprecated]` https://github.com/kubernetes/community/blob/master/sig-storage/volume-plugin-faq.md#in-tree-vs-out-of-tree-volume-plugins

Also this was hinted at in https://github.com/kubernetes/kubernetes/issues/78737 as well.

How and when do we roll this out?

**Comment by dims** [comment]
cc @msau42 @xing-yang

**Comment by BenTheElder** [comment]
still seems important?
@kubernetes/sig-storage-misc 
/remove-lifecycle rotten

**Comment by dims** [comment]
cc @xing-yang @msau42 @saad-ali

**Comment by xing-yang** [comment]
I've already sent out deprecation email to sig-storage mailing. This will also be added to 1.23 release notes.

**Comment by pacoxu** [comment]
According to
https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.23.md#deprecation-of-flexvolume
and 
https://github.com/kubernetes/community/blob/master/sig-storage/volume-plugin-faq.md#working-with-out-of-tree-volume-plugin-options, 
- flex volume has been deprecated since v1.23;
- The Kubernetes Storage-SIG plans to continue to support and maintain the Flex Volume API. So you can continue to use it without the worry of deprecation. 

So flex volume will not be removed in future release.

**Comment by jsafrane** [comment]
Yes, we do not plan to remove flex volumes. But we plan to fix only very important bugs there and we will not add new features (like snapshots, volume health, ...)

Is there a better word for it than "deprecated"?

**Comment by dims** [comment]
"frozen" perhaps? :)

**Comment by xing-yang** [comment]
Submitted a PR to clarify the CSI adapter project for Flexvolume is archived: https://github.com/kubernetes/community/pull/6890
