### ISSUE TITLE
Outofcpu error and reset nodeName for failed pods

### ISSUE THREAD

**Issue by yuanchen8911** [kubernetes/kubernetes#98928]
**What would you like to be added**:

`Outofcpu` error and pod scheduling failure has been observed in our systems. If I'm understanding it correctly, it happens after a pod is assigned/scheduled to a node and kubelet rejects the pod due to insufficient CPU capacity, i.e., `pod’s cpu-request+ used cpu > node’s cpu capacity`.  An example is that a pod specifies the node name in `spec.nodeName` and hence skips the scheduler’s resource capacity check. However, it's not our case. 

1. How could it happen? Does it mean there's some discrepancy about the available resources between the scheduler and kubelet? 

2. As the failed pod is already assigned to a node, it will be stuck in `Outofcpu` state unless the node name is removed from  `pod.spec.nodeName`. 

Can kubelet reset `nodeName` (i.e., clear the node name from the field) after rejecting a pod due to `OutOfcpu` or `Outofmemory` error?   

A question is `nodeName` can be set by kube-scheduler or users.  It makes sense to clear the field for the former. If the node name is specified by a user, kubelet cannot simply remove the node name, and instead, it should update the status and move the failed pod back to the scheduling queue. 

**Why is this needed**:

According to many users, it's a transient error, and deleting and rescheduling failed pods usually resolves the issue. 
If kubelet can reset `nodeName` of a failed pod,  the pod can be rescheduled.

**Comment by ahg-g** [comment]
> How could it happen? Does it mean there might be a skew or race condition between the scheduler and kubelet?

Yes, this is possible in the case where there are static pods being created. I am not sure how this is configured in your cluster, but kube-proxy is created as a static pod by default that it consumes 100m CPU; on node startup, kubelet takes sometime to actually create the kube-proxy pod on the api-server, and so the scheduler isn't aware of the allocated 100m and so causing the issue. If you deploy kube-proxy as a static pod and this happens in your cluster on new nodes and the amount you are trying to allocate is within 100m of the node's available cpu, then you are likely hitting this issue and the fix is to switch to deploying kube-proxy using a daemonset

Ideally this shouldn't happen, but the most relevant component that could clean this up is probably the garbage collector.

**Comment by yuanchen8911** [comment]
Thanks, this is helpful. As far as I know, we don't have static pods running in our cluster.  What garbage collector do you refer to?

**Comment by ahg-g** [comment]
> As far as I know, we don't have static pods running in our cluster

Did you verify that kube-proxy is deployed as a daemonset?

> What garbage collector do you refer to?

I am referring to k8s GC: https://kubernetes.io/docs/concepts/workloads/controllers/garbage-collection/ 

Note that it doesn't do that right now, I am just suggesting that it might be the most relevant controller to do so.

**Comment by adisky** [comment]
@yuanchen8911  Can you share more information Kubelet and scheduler logs? and the output of `kubectl describe node`.
Also are you running in the issue while node startup or it is always the case?
/triage needs-information

**Comment by pacoxu** [comment]
I think this is a similar issue with #72593.  It also asks the question how do the kubelet refuse a pod if the pod is scheduled on a node and found it is not fully satisfied.
- When a pod with unsafe sysctl is scheduled to a kubelet that doesn't allow unsafe sysctl, it will be failed for `SysctlForbiden`.
