### ISSUE TITLE
Flaky: InitContainer [NodeConformance] should not start app containers if init containers fail on a RestartAlways pod

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes/kubernetes#98970]
#### Which jobs are flaking:

pull-kubernetes-e2e-kind

#### Which test(s) are flaking:

 InitContainer [NodeConformance] should not start app containers if init containers fail on a RestartAlways pod

#### Testgrid link:

https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-e2e-kind&include-filter-by-regex=InitContainer

#### Reason for failure:

```
test/e2e/framework/framework.go:640
Feb 10 16:13:20.976: Unexpected error:
    <*errors.errorString | 0xc0001821e0>: {
        s: "timed out waiting for the condition",
    }
```

/sig node

**Comment by ehashman** [comment]
Still flaking: https://storage.googleapis.com/k8s-gubernator/triage/index.html?test=should%20not%20start%20app%20containers%20if%20init%20containers%20fail%20on%20a%20RestartAlways%20pod

**Comment by swatisehgal** [comment]
Did some investigation on this and ran InitContainer NodeConformance tests a few times but could not replicate this issue and the tests passed without any problem. The dashboard [here](https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-e2e-kind&include-filter-by-regex=InitContainer) shows no failures which made it appear that there could be underlying infrastructure setup issues in jobs like ci-kubernetes-kind-network-parallel-ipv6 and ci-kubernetes-kind-conformance-parallel that have dependency on this test leading to the problem. However, @ehashman pointed out another job [here](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-kinder-kubelet-1-20-on-latest/1402479881962393600#1:build-log.txt%3A3398) failing for the same reason (timeout waiting for pod to start). Will need to dig further to narrow down the root cause of the problem.
