### ISSUE TITLE
Make windows tests resilient to multiple cloud/installer scenarios w taints, selectors, rc's 

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/kubernetes#99128]
#### What would you like to be added:

- potentially use runtimeClass as the common mechanism for all e2es
- add tolerations for windows nodes to all windows e2es
- add node selectors for all windows nodes to all windows e2es 

#### Why is this needed:

Right now, tests have variable results on EKS/AKS/TKG... different clouds, because some clouds may taint, some may label, and some may require runtime classes 

cc @ravisantoshgudimetla

**Comment by jayunit100** [comment]
@ravisantoshgudimetla  any suggestion on how i should deal with  #98077 for this one ?

**Comment by marosset** [comment]
For our Azure tests we add a NoSchedule taint on the master nodes. I think GKE tests do the same.

Here is the script we run during cluster creation: https://github.com/kubernetes-sigs/windows-testing/blob/master/extensions/master_extension/v1/win-e2e-master-extension.sh

This is needed because some (or most?) of the non-windows specific tests do not add node selectors and we need to make sure those containers do not land on linux nodes.

**Comment by marosset** [comment]
It looks like runtime classes are not compatible with dockershim FYI @jayunit100 @ravisantoshgudimetla 
https://kubernetes.io/docs/concepts/containers/runtime-class/#dockershim

We still maintain test jobs that test dockershim clusters to ensure patch versions for v1.18-v1.20 don't container regressions.

**Comment by marosset** [comment]
I was getting errors like
`Error: windows-2019 failed to create kubernetes rest client for update of resource: resource [node.k8s.io/v1/RuntimeClass] isn't valid for cluster, check the APIVersion and Kind fields are valid.`
