### ISSUE TITLE
metadata.labels limits are not working as expected

### ISSUE THREAD

**Issue by duronrulez** [kubernetes/kubernetes#99156]
#### What happened:
When provisioning a new node with 65 (or more) character metadata.labels value the result was successful provision, but hostname was not changed after booting.

#### What you expected to happen:
Same as when youre trying to provision a node with 64 characters (exactly), failed provision due to:
```
"causes": [
                {
                    "reason": "FieldValueInvalid",
                    "message": "Invalid value: \"i-xxxxxxxxxxxxxxxxx-xxx-xxxxxxx-xxxx-xxxxxxxxxx-1-17-xxxx-xxxxxx\": must be no more than 63 characters",
                    "field": "metadata.labels"
                }
            ]
```
#### How to reproduce it (as minimally and precisely as possible):
Provision a node with a label of 65+ characters.
#### Environment:
- Kubernetes version 1.17
- Cloud provider or hardware configuration: cloud

**Comment by neolit123** [comment]
the 63 limit is by design:
https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#dns-label-names

i don't see how 65 can pass, but 64 can fail:
https://github.com/kubernetes/kubernetes/blob/release-1.17/staging/src/k8s.io/apimachinery/pkg/util/validation/validation.go#L64

you should use 63 as the maximum length.

/close

**Comment by duronrulez** [comment]
I understand that 63 is the limit, but we've managed to provision nodes with larger names (but the node just ignores the label then).
This is what is the problem actually, because it does not error out on 65 characters (just silently ignores the whole label) or more (it errors on 64 chars)

**Comment by pacoxu** [comment]
If your node name is longer, you may use kubelet option `--hostname-override` to override the hostname in cluster.

**Comment by neolit123** [comment]
@duronrulez 
i'm not sure i understand the issue here.

> I understand that 63 is the limit, but we've managed to provision nodes with larger names (the label just gets ignore though).

- are you creating a node with a name longer than 63 characters or a node with a metadata.label key longer than 64 characters?
- how are applying node labels?
- how are you creating your nodes?

> This is what is the problem actually, because it does not error out on 65 characters or more - just silently ignores the whole label. It errors correctly on 64 chars

i don't see how it would error on 64 characters exactly looking at the code.

/reopen
/sig node cluster-lifecycle api-machinery

**Comment by duronrulez** [comment]
Digging a bit deeper seems that it could be AWS EKS related issue.

Basically what we do is
```
/etc/eks/bootstrap.sh --apiserver-endpoint 'https://xxx.eu-west-1.eks.amazonaws.com' --b64-cluster-ca 'xxx' --kubelet-extra-args '--node-labels=nodetype=1234-123456 --cluster-dns=xxx' 'eks-cluster-1234-123456789a'
```

Which results in the full label being:
i-123456789abcdefgh-eks-cluster-1234-123456789a-1-17-1234-123456 - 64 chars, this logs error in the audit api in cloudwatch and fails joining the node in the cluster

i-123456789abcdefgh-eks-cluster-1234-123456789a-1-17-1234-1234567 - 65 chars, this logs success in the audit api in cloudwatch and joins the node in the cluster, but with a default hostname

**Comment by neolit123** [comment]
@duronrulez given you are using the EKS product, please coordinate with their support and if they think this is an upstream issue let them explain with more details in this ticket what they think the bug is. then re-open it.

thanks
/close
