### ISSUE TITLE
Proposal: test kubernetes pre-releases against minikube

### ISSUE THREAD

**Issue by medyagh** [kubernetes/kubernetes#99322]
in minikube we have made several performance measuring tools both for measuring the latency and also resource usage, that gets tested with minikube, I would like to test every alpha release of kuberentes with minikube, preferably on the kubernete side. (prow)

previous years minikube could have not be tested in prow because it was only VM drivers, we have support for docker/podman since 2019, I would love to start testing kuberentes with minikube to avoid performance surprises like this :

 
related issues:
https://github.com/kubernetes/minikube/issues/10545
https://github.com/kubernetes/kubeadm/issues/2395#issuecomment-782784169

```

the Minikube maintainers (cc @medyagh) [found](https://github.com/kubernetes/kubeadm/issues/2395) that this change introduced a performance regression.
when client credentials are fed to a primary kubelet in a cluster (`--kubeconfig`), but there are no other nodes or an API server running yet (because this primary kubelet will boot it from a static pod), this blocks for extra ~40 seconds.

i can see the informer wait as something desired but i think the logic here can be improved.
cc @derekwaynecarr @deads2k @liggitt 

we also backported this change in the support skew and since we don't have direct performance tests, nobody saw it until now.
```
_Originally posted by @neolit123 in https://github.com/kubernetes/kubernetes/issues/94087#issuecomment-782786341_

**Comment by neolit123** [comment]
@BenTheElder proposed that we start timing the kind deployments which are already in the e2e here and use kubeadm. these jobs run in high-priority and can catch perf. problems with them.

both kind and minikube are using kubeadm, so could also have the timing tests in the kubeadm e2e, but the kubeadm e2e are currently running in low-priority.

/sig testing cluster-lifecycle
/kind feature
/area test

**Comment by medyagh** [comment]
could we add minikube two kubedm e2e too ?

**Comment by neolit123** [comment]
the kubeadm e2e test setup is based on something that resembles kind (uses it as a library).

i can see you already have prow jobs for the minikube repository:
https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/minikube/minikube.yaml

you could add more periodic and pre/post-submit jobs there.

**Comment by medyagh** [comment]
excellent ! thank you for link, @azhao155 on minikube side is interesting in helping with this. I will add it our v1.19.0 milestone

**Comment by BenTheElder** [comment]
>  I would like to test every alpha release of kuberentes with minikube, preferably on the kubernete side. (prow)

Anyone can add jobs to CI, however there are documented requirements for signal the release team monitors:
https://github.com/kubernetes/sig-release/blob/master/release-blocking-jobs.md

There is no guarantee that the CI signal team agrees to monitor any given signal, however the minimum requirements are listed there.

Note also that there's no "test on every alpha release" CI functionality. There is "test on merge" and "test periodically" (cron).
Releases are soft-blocked on certain jobs passing reliably within that branch, as inspected by the release team. Though primarily the 1.X release.

> [...] adding minikube tests would add testing for crio,docker [..]

Kubernetes does **not** try to test against the matrix of all integrations nor do we wish to, this is the burdern of the implementers of these integrations. We need to test against one concrete CRI implementation and are winding down dockershim based CI to a minimum (we have some still) as we plan to remove dockershim. This is incidentally why kind does not support these ...

> proposed that we start timing the kind deployments which are already in the e2e here and use kubeadm. these jobs run in high-priority and we can catch perf. problems with them.

yes, this is something we did not monitor in CI previously because prow did not provide guaranteed QOS anywhere. it does now for high prio jobs (xref the whole CI policy revamp effort), so we can finally add this.

**Comment by BenTheElder** [comment]
Today we typically performance test on GCE clusters, with Kubernetes SIG Scalability primarily owning this space.

We have performance test presubmits even, but "cluster startup time" is not something the project has chosen to block on so far. If we do choose to block on this, we could easily do so it in our existing test jobs, we're already recording the timing typically.

It's not clear that the project is willing to block on this sort of thing. (Though I personally would welcome it!)
