### ISSUE TITLE
Migrate Windows test images from k8sprow.azurecr.io/kubernetes-e2e-test-images to gcr promoted registry

### ISSUE THREAD

**Issue by jsturtevant** [kubernetes/kubernetes#99363]
#### What happened:
We started to move Windows Tests images to the new promoter registry in #98964 but ran into a few issues.  This is an aggregate issue to track converting the Window Images back to the 

- https://github.com/kubernetes/kubernetes/issues/99325
- https://github.com/kubernetes/test-infra/issues/20884

#### What you expected to happen:
Windows tests to be able to use the test images in promoter registry.

#### Anything else we need to know?:

We added a `image-repo-list-pr` (https://github.com/kubernetes-sigs/windows-testing/pull/249) list so we can run the e2e tests as presubmit when we attempt to cut over again.

#### Environment:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

/sig windows
/assign @chewong

**Comment by jsturtevant** [comment]
To mitigate this in the mean time we cut the windows tests images back to the k8sprow.azurecr.io/kubernetes-e2e-test-images container registry and the tests are in much better shape now.

**Comment by chewong** [comment]
Steps we took to mitigate the issues temporarily:
- [x] we stoped using the default test image registry `k8s.gcr.io/e2e-test-images` because it contains erroneous httpd & nginx test images. Instead, we switched to `k8sprow.azurecr.io/kubernetes-e2e-test-images` by adding `promoterE2eRegistry: k8sprow.azurecr.io/kubernetes-e2e-test-images` (PR: https://github.com/kubernetes-sigs/windows-testing/pull/249) because it contains the following test images that work:
  - `k8sprow.azurecr.io/kubernetes-e2e-test-images/httpd:2.4.38-alpine`
  - `k8sprow.azurecr.io/kubernetes-e2e-test-images/httpd:2.4.39-alpine`
  - `k8sprow.azurecr.io/kubernetes-e2e-test-images/nginx:1.14-alpine`
  - `k8sprow.azurecr.io/kubernetes-e2e-test-images/nginx:1.15-alpine`

Steps to permanently mitigate the issues:
- [ ] fix #99325 and https://github.com/kubernetes/test-infra/pull/20884
- [ ] create a presubmit job that can be auto-triggered to verify any changes in https://github.com/kubernetes/kubernetes/blob/master/test/utils/image/manifest.go so we can avoid similar situation in the future
- [ ] remove `promoterE2eRegistry: k8sprow.azurecr.io/kubernetes-e2e-test-images` in https://github.com/kubernetes-sigs/windows-testing/blob/master/images/image-repo-list-master and https://github.com/kubernetes-sigs/windows-testing/blob/master/images/image-repo-list-2004 so the jobs can start using  the default test image registry `k8s.gcr.io/e2e-test-images` instead of `k8sprow.azurecr.io/kubernetes-e2e-test-images` again

**Comment by jsturtevant** [comment]
https://github.com/kubernetes/kubernetes/pull/99395 addresses the nginx image failing

**Comment by chewong** [comment]
> #99395 addresses the nginx image failing

facing the same issue as https://github.com/kubernetes/test-infra/issues/20884 when we tried to push nginx images to the staging registry

**Comment by jsturtevant** [comment]
We are now using the gcr promoted registry in our test.

There are a few more PRs open with some additional fixes:

- #99670
- #99866
- #99860

**Comment by jsturtevant** [comment]
with the agnhost (https://github.com/kubernetes/kubernetes/pull/100410) merged we now have passing tests for all the windows tests using the gcr promoted registry

/close
