### ISSUE TITLE
self-signed kubelet server certificate is never renewed

### ISSUE THREAD

**Issue by champtar** [kubernetes/kubernetes#99418]
#### What happened:
Looking at how to easily renew kubelet server certificate (serverTLSBootstrap + custom approver/script to regenerate a new cert myself/...), I had a look at the code and I can only find `kubelet.crt` (https://github.com/kubernetes/kubernetes/search?q=kubelet.crt&type=code) here 
https://github.com/kubernetes/kubernetes/blob/e7cc2117a02bc5c74a8235a2725834b1841c459e/cmd/kubelet/app/server.go#L985-L990
This checks if the cert/key are readable but not if the cert is still valid.

#### What you expected to happen:
selfsigned cert is rotated before expiration

#### Anything else we need to know?:
I have only looked at the code and not manually reproduced it, but I can't find anything in k8s/kubeadm rotating this cert

#### Environment:
- Kubernetes version: master
- Install tools: kubeadm / kubespray

**Comment by neolit123** [comment]
kubeadm doesn't use the kubelet serving certificate for anything, thus it's not enabling its automatic rotation via --rotate-server-certificates RotateKubeletServerCertificate or manual rotation.

also see the note there that the rotation requires an external controller to sign CSRs:
https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet-tls-bootstrapping/#certificate-rotation

related thread:
https://github.com/kubernetes/kubeadm/issues/1223
https://github.com/kubernetes/kubeadm/issues/1602

> I have only looked at the code and not manually reproduced it, but I can't find anything in k8s/kubeadm rotating this cert

kubeadm will not enable this feature anytime soon, due to the "minimal viable principle" - i.e. the majority of kubeadm users don't need this.

you can ask kube-spray to see what is their stance doing it on higher level.

/remove-sig node
/sig cluster-lifecycle
/close
