### ISSUE TITLE
psp.allowedHostPaths could not reject symlink

### ISSUE THREAD

**Issue by nicktming** [kubernetes/kubernetes#99499]
#### What would you like to be added:
Add a admithandler in kubelet to reject symlink vol. if pods want to use a hostpath, there is no need to use symlink, becase pods could use its symlink target path.

#### Why is this needed:
psp.allowedHostPaths using prefix could not reject symlink, which would make all system path such as /dev, /root exposed to pods using symlink.

**Comment by liggitt** [comment]
Rejecting symlinks cannot be done in a backwards compatible way without adding something like a "noSymlinks" field to the pod spec hostPath volume definition.

That could be opened as a sig-storage proposal, but my sense is that fine-grained control to allow *some* breakage of the container/host boundary while still preventing the pod author from doing anything unsafe is not generally a goal.

PSP specifically is deprecated in 1.21, and is likely to be replaced by something that enforces much more coarse-grained policies, like https://kubernetes.io/docs/concepts/security/pod-security-standards/, where the dividing line is between "allow hostPath volumes" and "do not allow hostPath volumes", rather than "allow specific hostPath volumes to specific paths".

If you want to pursue this feature, I would suggest raising it in sig-storage as a "noSymlinks" option in hostPath volume definitions to see if there is interest/support there.

/close
