### ISSUE TITLE
[Flaky Test] [sig-node] Pods Extended Pod Container Status should never report success for a pending container

### ISSUE THREAD

**Issue by jkaniuk** [kubernetes/kubernetes#99599]
#### Which jobs are failing:
ci-kubernetes-e2e-gce-scale-correctness
#### Which test(s) are failing:
[sig-node] Pods Extended Pod Container Status should never report success for a pending container
#### Since when has it been failing:
2021-02-19
#### Testgrid link:
https://k8s-testgrid.appspot.com/sig-scalability-gce#gce-master-scale-correctness&show-stale-tests=&width=90
![image](https://user-images.githubusercontent.com/5487158/109526678-21d0d180-7ab3-11eb-8aa9-5813daccc09f.png)

#### Reason for failure:
`/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/node/pods.go:206
Feb 19 12:22:34.933: 1 errors:
pod pod-submit-status-0-11 on node gce-scale-cluster-minion-group-2-cczj container unexpected exit code 128: start=1970-01-01 00:00:00 +0000 UTC end=2021-02-19 12:21:43 +0000 UTC reason=StartError message=failed to create containerd task: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/var/lib/kubelet/pods/f1598006-96dc-4682-af6a-55e15d016926/volumes/kubernetes.io~projected/kube-api-access-fwq42\\\" to rootfs \\\"/run/containerd/io.containerd.runtime.v2.task/k8s.io/5474dfbe9c140c64de6588b40231cf05fc12cfbb0225591d70efde342ce18efe/rootfs\\\" at \\\"/var/run/secrets/kubernetes.io/serviceaccount\\\" caused \\\"stat /var/lib/kubelet/pods/f1598006-96dc-4682-af6a-55e15d016926/volumes/kubernetes.io~projected/kube-api-access-fwq42: no such file or directory\\\"\"": unknown
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/onsi/ginkgo/internal/leafnodes/runner.go:113
`
#### Anything else we need to know:
/sig scalability
/sig node
It failed 6/10 times in recent runs
/priority critical-urgent

/cc @SergeyKanzhelev 
/cc @jingxu97

**Comment by jkaniuk** [comment]
I do not see any recent changes in test setup, apart from test renames.

**Comment by jkaniuk** [comment]
Test is already ignoring:
`var reBug88766 = regexp.MustCompile('rootfs_linux.*kubernetes\.io~secret.*no such file or directory')`
https://github.com/kubernetes/kubernetes/blob/8df355b/test/e2e/node/pods.go#L209

Looks very similar, so probably regex should be extended.

Original issues and PRs:
https://github.com/kubernetes/kubernetes/issues/88766
https://github.com/kubernetes/kubernetes/pull/88872

/assign @smarterclayton
@rphillips
@ehashman
@tosi3k

**Comment by jkaniuk** [comment]
@kubernetes/sig-node-test-failures, could you triage?

**Comment by ehashman** [comment]
We meet tomorrow, I'll make sure this is on our board/agenda.

**Comment by liggitt** [comment]
Injected service account tokens changed from secret-based to projected-token based by default in https://github.com/kubernetes/kubernetes/pull/95667, which merged 2/18

That coincides with this flake starting: https://storage.googleapis.com/k8s-gubernator/triage/index.html?date=2021-02-27&text=volumes%2Fkubernetes.io~projected

as @jkaniuk points out, the test already tolerated secret volume setup errors, I guess because those error messages are expected to occur spuriously in rapidly restarting containers? If it was acceptable for secret volume errors to be encountered in this test before, I agree the regex should be expanded to accomodate projected volume tokens.

opened https://github.com/kubernetes/kubernetes/pull/99898 to do this. Separately, is sig storage or sig node looking at https://github.com/kubernetes/kubernetes/issues/88766?
