### ISSUE TITLE
web-based simulator for scheduler behaviour

### ISSUE THREAD

**Issue by adtac** [kubernetes/kubernetes#99605]
An in-tree web-based simulator that hooks into the scheduler code to simulate aspects of the scheduler's behaviour. The interface should allow the user to create/delete nodes, pods, volumes, etc. and simulate behaviour such as spreading, affinity, preemption, etc. faithfully. The standalone tool can simulate a cluster and its operations similar to how the integration tests and scheduler_perf benchmarks work. This would serve as a great, interactive learning tool to understand the scheduler's behaviour without having to spin up a real cluster. A decent analogy: this is the play.golang.org of the k8s scheduler.

I'm proposing this project as a [GSoC 2021](https://github.com/cncf/mentoring/blob/master/summerofcode/2021.md) project under the CNCF org, so please hold off on working on this until we get more information. Specific details are a bit vague currently, but if a student is chosen to work on this, they're expected to submit a detailed proposal.

/sig scheduling
cc @alculquicondor

**Comment by Harshrai3112** [comment]
Hi, I would  really like to work on this project. So can you assign me any task so that i can work on that now.

**Comment by joyliu-q** [comment]
Hello! This project seems fascinating, and a great sandbox for hands-on learning, which I'm a huge fan of. Sent you a message on slack with some more information: I would love to contribute and get involved!

**Comment by Hangzhi** [comment]
Hello! I would also like to contribute to this scheduler. Is this idea similar to the [Hawk](https://www.usenix.org/conference/atc15/technical-session/presentation/delgado)? Is there any further information to better understand the project or basic tasks I can work on?

**Comment by adtac** [comment]
Also I hope everyone's familiar with the [GSoC timeline](https://developers.google.com/open-source/gsoc/timeline). And be sure to go through the [student guide](https://google.github.io/gsocguides/student/), it's a truly useful resource.

**Comment by adtac** [comment]
I've labeled a handful of issues in SIG scheduling with "good first issue".

Btw try experimenting with the `test/integration/scheduler_perf` performance testing framework because I think there will be some overlap between what that framework does and what this proposal will be doing. We won't be doing anything performance related in this proposal, but the way that testing framework creates a scheduler, creates virtual nodes, schedules pods, etc. might be relevant.

**Comment by wy2249** [comment]
Hi, @adtac 

This project idea is amazing! When I worked as a SRE intern last summer and tried to experiment and study k8s, I was hoping there is a web simulator to save my time and money! Cluster is expensive... Anyway I am super excited for this one!

Before I dig more into this project, may I have some clarification questions?

Firstly, are we gonna use the scheduler of k8s as pkg for this simulator? Or is it supposed to create a simplified version to simulate the real complicated scheduler? I am wondering this because you only mentioned resources like cluster, node, pod and volume, but from what I knew, k8s also has other resources and also custom defined resources. So I am not sure if you are looking for a simplified simulator, or we can simply use the default one for k8s.

Also, do you have any preference or detailed plan how users interact with this simulator? Are we supposed to create a front-end playground page, or we can have other forms like a CLI?

Thanks in advance and appreciate a lot for bringing this fun idea!!

**Comment by adtac** [comment]
>Firstly, are we gonna use the scheduler of k8s as pkg for this simulator? Or is it supposed to create a simplified version to simulate the real complicated scheduler? I am wondering this because you only mentioned resources like cluster, node, pod and volume, but from what I knew, k8s also has other resources and also custom defined resources. So I am not sure if you are looking for a simplified simulator, or we can simply use the default one for k8s.

Good questions! I think we should start with a simple version that doesn't involve CRDs. We also don't want to duplicate the scheduler's logic anywhere, so we should use the default k8s one. You can spin a mock API server and a mock scheduler like we do in integration tests to achieve this.

So I think we'll want to simulate the real and complicated scheduler, but we will be restricting what resources can be accessed and modified through the UI (i.e. you won't be able to add a CRD to begin with). Exactly what resources you want to support in the UI will depend on your project proposal. GSoC is usually structured in phases/milestones, so we can even defer supporting non-essential resources like volumes to a later stage in the timeline.

>Also, do you have any preference or detailed plan how users interact with this simulator? Are we supposed to create a front-end playground page, or we can have other forms like a CLI?

I was originally thinking of an interactive web UI, but now that you mention it, an interactive CLI works too. However, note that the primary users of this tool will be relatively new users of k8s, so I think a web UI might be more accessible. FWIW you can write a relatively simple CLI as an initial milestone and then create a web UI later as a future milestone; it's all up to the student :)

**Comment by alculquicondor** [comment]
> Firstly, are we gonna use the scheduler of k8s as pkg for this simulator? Or is it supposed to create a simplified version to simulate the real complicated scheduler? I am wondering this because you only mentioned resources like cluster, node, pod and volume, but from what I knew, k8s also has other resources and also custom defined resources

Note that CRDs don't have any effect on the default scheduler.

**Comment by ingvagabund** [comment]
> An in-tree web-based simulator that hooks into the scheduler code to simulate aspects of the scheduler's behaviour. The interface should allow the user to create/delete nodes, pods, volumes, etc. and simulate behaviour such as spreading, affinity, preemption, etc. faithfully. The standalone tool can simulate a cluster and its operations

This was intention behind building https://github.com/kubernetes-sigs/cluster-capacity. Right now it provides a number of pods what would get scheduled given the current state of a cluster before resources get depleted. With some help, the project can be extended to achieve what's suggested.

**Comment by Ananya-1106** [comment]
Hello everyone!
I am new to this but very curious to learn more about this, explore and help. Please guide me with what i should start?

**Comment by prakhar101** [comment]
Hey !!!
I am quite interested in this project and want to do it with my full efforts by making  the utilization of my Kubernetes CKA & CKAD knowledge...So, @adtac sir , can you please provide your  guidance that how I  should proceed....
Thanks  in advance...

**Comment by adtac** [comment]
@Ananya-1106 @prakhar101 please see the previous comments in this thread :)

@ingvagabund thanks for that, that's an interesting project. From briefly reading the README, I agree there's some overlapping objectives.

**Comment by adtac** [comment]
@Harshrai3112 @joyliu-q @Hangzhi @wy2249 @Ananya-1106 @tigllon (I hope I didn't miss anyone)

Hello! As you might know, the GSoC project proposal phase has begun. It goes on till the 13th of April, so you have approximately two weeks to submit a proposal. Refer to the [GSoC timeline page](https://developers.google.com/open-source/gsoc/timeline) for full details.

Kubernetes is a part of the CNCF org for GSoC this year [(link to org page)](https://summerofcode.withgoogle.com/dashboard/organization/6354864663166976/statistics/). Look for CNCF in the org list when submitting your proposal.

I'm not aware of any templates at the moment, but I've contacted the CNCF org admin to confirm this. Until then, you can use the following section pointers to roughly guide your proposal.

1. An introduction: your name, your email address, GitHub handle, where you're studying (there are [restrictions](https://developers.google.com/open-source/gsoc/faq#what_are_the_eligibility_requirements_for_participation) on who can participate in GSoC), whether you have other commitments during GSoC, and anything else you think will be relevant.
2. An abstract of your proposal. This shouldn't be more than 3-4 paragraphs in general. I recommend keeping this light on technical details and focusing on the end result from the user's perspective.
3. A detailed, technical description of your strategy. This is probably the most important section that will tell us how deeply you've thought about your proposal.
4. A weekly/bi-weekly timeline for the 10 weeks. Feel free to allocate 2-3 weeks to ramp up with the scheduler code. Try to be explicit with the deliverables in each milestone. This is all approximate though, so don't sweat too much about accurately estimating how much each subtask will take. From past GSoC experience, I recommend having a buffer week towards the end just in case; it'll come handy.
5. Your past OSS contributions that you're proud of, both within Kubernetes and outside.

Good luck!

**Comment by BenS-Move** [comment]
@adtac Hello, I am a first-year graduate student from East China Normal University in China. I am very interested in this project, and I'm familiar with the implementation process for this project，because I have been involved in the implementation of a similar website [play.golang.org](https://play.golang.org/). The online learning  website where I am involved in  is [kfcoding.com](http://kfcoding.com/), and it can provide students, teachers, technicians with online programming environment, simply and fast! So I think your project is very suitable for me, and I am also very happy to participate in your project. In addition, I have a certain understanding of cloud native, k8s, docker and so on!
Do you have any small tasks or needs? I'd like to complete the research in advance. I look forward to hearing from you.

**Comment by sanposhiho** [comment]
Hi team :D
Here is the detailed proposal.

I'd love to hear any advice or point out where I'm wrong.

---

## What user can

This section describes the features covered by this description. These features are the starting point of the simulator and expected to be expanded in the near future. (So I'm not going to talk about affinity etc. here.)

- Users can create/delete pods and nodes.
- Users don’t have to know how to use `kubectl`. They create/delete resources with only simple operation of web UI.

## Technical description

Front-end and back-end communicate via WebSocket. This is to notify the backend to the frontend of resource state changes.
The front-end makes HTTP requests to the back-end for resource changes. The backend returns status NoContent(204) if the request was processed successfully. The resource status change caused by the request is notified to the frontend via websocket (as described above).

### create Nodes
![simulator (1)](https://user-images.githubusercontent.com/44139130/119180199-f0144900-baaa-11eb-9cde-d64a18db7236.png)

The backend of the simulator request to kube-apiserver to create node and kube-apiserver stores the information about the node in etcd.
To distinguish between users, give a label to each node to indicate which user created the node. 

### create Pods

![simulator (4)](https://user-images.githubusercontent.com/44139130/119182308-b42eb300-baad-11eb-9c91-1cf16fceef68.png)


The backend request to kube-apiserver to create pod and kube-apiserver stores the information about the pod in etcd.
And, scheduler realizes the new pod was created, does scheduling, and requests to kube-apiserver to bind the pod.
Use the user-specific label that we gave to the node so that the new Pod will be created on the node created by the user. (use nodeSelector to achieve this.)

### delete Pods/Nodes

![simulator (3)](https://user-images.githubusercontent.com/44139130/119181819-16d37f00-baad-11eb-9a2a-0fa55b29e788.png)

Very simple.

**Comment by alculquicondor** [comment]
The proposal above sounds like a visualization of the decisions taken by a scheduler (after binding).
This is a great first step!
Have you thought of visualizing more data? In particular, it would be good to visualize which nodes were deemed feasible (passed the filters) and what scores they got, perhaps even per plugin.

**Comment by sanposhiho** [comment]
> Have you thought of visualizing more data? In particular, it would be good to visualize which nodes were deemed feasible (passed the filters) and what scores they got, perhaps even per plugin.

I hadn't thought of that. Thanks
I think it's very interesting! I'll think about it as a future expansion. 👍

**Comment by damemi** [comment]
I was under the impression that the scheduling simulator would focus more on the scheduling behaviors, like @alculquicondor mentioned. From the description:

> The interface should allow the user to create/delete nodes, pods, volumes, etc. and simulate behaviour such as spreading, affinity, preemption, etc. faithfully

This implies to me that being able to create/delete pods and nodes is a part of the simulator (ie, test data population), but not what's "being simulated" whereas the behavior of spreading, affinity, preemption, etc is more along what Aldo mentioned where we can actually visualize the filtering and scoring phases.

**Comment by sanposhiho** [comment]
Hi @damemi, thank you for the comment.

The features described above are needed to, as @alculquicondor says, show how the scheduler made the decision(after binding).

> This implies to me that being able to create/delete pods and nodes is a part of the simulator (ie, test data population), but not what's "being simulated" whereas the behavior of spreading, affinity, preemption, etc is more along what Aldo mentioned where we can actually visualize the filtering and scoring phases.

Yeah, It's true that we need to be able to see in the scheduler what decisions are made by each plugin in each phase.
So I'm going to implement it after supporting basic operations such as creating pods as described above. Thanks!

I'm sure I'll submit a detailed proposal for this implementation somewhere, but now I'm thinking of having the scheduler notify the backend through a channel when each plugin is done running.
Implementing a wrapper around the plugin that would notify the result to the backend through a channel when the plugin is done running, and use this to wrap the default plugins.
When the backend receives the notification, it notifies the frontend via websocket.

**Comment by adtac** [comment]
@sanposhiho and I talked offline. I agree with what everyone said, the primary purpose is to visualise spreading, node affinity, etc. I really like @alculquicondor's scoring suggestion as well, but I think we should leave that to the later stages of the project.

**Comment by sanposhiho** [comment]
Hello, I wrote the features list on Google docs.
This describes which features will be implemented in each period of GSoC.

https://docs.google.com/document/d/1zbCvZL-iKa7Xdi2STlxSp7KPYx3MH1ZZQqvFe9i1WnQ/edit?usp=sharing

**Comment by sanposhiho** [comment]
Hello, I wrote the current progress of this project. I'd be happy to get ideas or feedback :)

https://docs.google.com/document/d/1mbPcGuI1AlJ8bvAY0sl5AUp7WzL4oBMFDYc2OFnwQWU/edit?usp=sharing

**Comment by alculquicondor** [comment]
I added a few comments. Mostly suggesting simplifications.

I think now you can focus on:
- Making the simulator easy to run by anybody.
- Ensuring documentation is in-place to be able to keep the simulator up-to-date with the latest version of k8s.

And... adding it to a repo in github.com/kubernetes-sigs?

**Comment by sanposhiho** [comment]
Hi @alculquicondor, thanks for your comments. 
It helps me a lot :)

I'd like to reply to some of your comments here. 

> Is the intention that we host the simulator somewhere? Or is the intention that there is an easy way for anybody to run a simulator in their own computers?

Currently, this simulator is designed to be hosted somewhere and to work properly even if it is accessed by multiple users. (Of course, we can use it on computers.)
This is because when started developing, we had a further goal that creates the site users can use to learn about scheduler behavior. I would like to hear @adtac's idea about this.

>  adding it to a repo in github.com/kubernetes-sigs?

@adtac is thinking about it now, maybe?
I'm currently developing it on kubernetes/kubernetes repo (on dir `./cmd/scheduler-simulator`)
But, it's easy to create new repository on somewhere and move codes on it. (Because, of course, I haven't touched the code of the scheduler itself)

**Comment by alculquicondor** [comment]
> Currently, this simulator is designed to be hosted somewhere

With the current architecture, it looks like it would be easy to bring the website down. It would be nice if each user's backend would run in its own container. But I wouldn't go that path now, perhaps for a 2nd project. For now, I think it's more important to make the simulator easy to execute for individual users.

@Huang-Wei wdyt about creating a new repo?

**Comment by sanposhiho** [comment]
>  it looks like it would be easy to bring the website down. It would be nice if each user's backend would run in its own container.

Good, it would be simpler if one backend didn't have to deal with multiple users. This one will be a further goal.

> For now, I think it's more important to make the simulator easy to execute for individual users.

Ok, simulator only require nodejs(+ yarn), etcd(installed with /hack/install-etcd.sh) and Golang, and there is Makefile to execute. So it is not difficult for users to execute. 
I'll add some documents to describe how to execute and use simulator in detail.

**Comment by adtac** [comment]
re new repo: yes, I was thinking of the same but I wasn't sure how to proceed with getting a new repository. Pinging @Huang-Wei for help :)

Just to set the expectations right in the context of GSoC, while I like the idea of a separate instance of the binary for each user as a security model, I'd like to mention that it's out of scope for this project. However if Kensei wants to work on it, then there's no problem, of course :) Also, for the sake of completeness, there are other solutions too (e.g. refactor the code to manage multiple users in the same server by potentially starting multiple apiservers, schedulers, etc?).

**Comment by Huang-Wei** [comment]
Sure, I can help setup a repo. Before we head to the repo creation, let's clarify our expectations:

- Is this repo for the all-in-one web simulator ? i.e., the frontend UI (maybe also includes user session mgmt) + backend (running the simulation)
- or, are we going to host two repos - a repo for web simulator SDK (external integrator can benefit from this), and a repo for frontend UI
- and, are we going to host the project somewhere? i.e., as an external accessible service (this needs further work like domain name request, apply for compute resource, security check, a fully automated CI/CD pipeline to roll out new versions, etc.)

**Comment by sanposhiho** [comment]
As @adtac, and @alculquicondor said, for GSoC, it should be the priority to make the simulator easy for users to use their own machine. So, in the rest of GSoC, I'll add some docs, write the blog post and the final report and improve the code to be easy to maintain.
And, about hosting, I know that this will require a lot of further work and resources. If we can reach an agreement to create a website after this GSoC, I would be happy and willing to help a lot, of course :)

**Comment by adtac** [comment]
@Huang-Wei agreed on (3), I don't think that's an immediate goal of the project. For now, we're focusing on building something that you can run locally on your machine.

re (2): I disagree, I think the frontend and the backend should be in the same repo. They're very closely coupled at the moment so I think it makes sense to keep them tightly integrated. We can always refactor things to be more usable in other projects later, but IMO we should prioritise making it as easy as possible to clone the project and run it locally in just a couple of minutes. @sanposhiho is workingon adding a Dockerfile which will make it even easier to run with just a `docker build -t simulator .` command.

As for the repo name, let's say `kubernetes/scheduler-simulator`? Open to suggestions :)

**Comment by alculquicondor** [comment]
+1 on (1) and the repo name. An alternative would be `kubernetes/scheduling-visualizer`

**Comment by Huang-Wei** [comment]
@adtac I always believe the core value of this project is not the UI, it's the fine-grained abstracted simulation SDKs that **all** integrators can benefit from. UI is only one kind of consumer. That's why I'm inclined to separate the logic in the beginning and treat SDKs as the 1st class citizen, instead of UI.

However, I understand that GSoC must have a deliverable MVP upon a due date, so prioritizing that goal and thus create the all-in-one simulator repo is fine with me. We can separate the logic in the future.

Regarding the repo creation, please go ahead to open an issue at https://github.com/kubernetes/org/issues/new/choose, and choose "Repository creation/migration". Note that the org should be kubernetes-sigs rather than kubernetes.

**Comment by adtac** [comment]
>UI is only one kind of consumer.

That's a fair point. Out of curiosity, do you have any external integrations in mind?

Also thanks, I'll open an issue there :+1:

**Comment by adtac** [comment]
I'd also like to talk to somebody about scheduling a potential blog post at the end of GSoC (authored by @sanposhiho). Whom should I talk to?

**Comment by alculquicondor** [comment]
Ask the owners https://github.com/kubernetes/website/blob/main/OWNERS_ALIASES#L2

**Comment by sanposhiho** [comment]
Hello, can someone be my sponsor of membership? 
https://github.com/kubernetes/org/issues/2901

ref: https://github.com/kubernetes/org/issues/2878#issuecomment-900604877

**Comment by sanposhiho** [comment]
Maybe we can close this issue because we already have created the repository. Feel free to open the issue on the repo if you have something to discuss.
https://github.com/kubernetes-sigs/kube-scheduler-simulator

I've successfully passed Google Summer of Code 2021 on Kubernetes!!! 🎉 
It was a great journey for me!! Everyone, thanks for helping me a lot!! Also, I would like to thank my mentor, @adtac , for his help and support :)

https://summerofcode.withgoogle.com/projects/#4712838116933632

**Comment by alculquicondor** [comment]
I'll leave it up to @adtac to close it.

Thank you for your contributions @sanposhiho! We hope to see you around in k8s and sig-scheduling in particular :)

**Comment by adtac** [comment]
Oops, I forgot to post an update on this issue. A big thank you @sanposhiho for all the amazing work in GSoC! I'm so glad you enjoyed working on this and I'm really proud of what you've built here!

I'll close this issue, but if someone wants to continue the discussion on specific parts of the project, please feel free to open an issue in the kube-scheduler-simulator repo.
