### ISSUE TITLE
v1alpha1.VolumeAttachment deprecation

### ISSUE THREAD

**Issue by pohly** [kubernetes/kubernetes#99827]
#### What happened:

storage.k8s.io/v1alpha1/VolumeAttachment has been replaced with v1beta1 already since 1.10 and now with v1. Apparently it was never deprecated, though.

#### What you expected to happen:

- deprecation notice in 1.21
- removal in 1.22

/sig storage

**Comment by ialidzhikov** [comment]
@pohly , @msau42 what would be next steps for this issue?

I see that #99641 adds proper `k8s:prerelease-lifecycle-gen` tags for the types.

I was wondering what we mean exactly by `removal in 1.22`? Is it `stop serving the v1alpha1.storage.k8s.io API` (if it was not already done)?

I think the `v1alpha1` is not served since longtime. Against v1.18.18 cluster:

```
$ k get volumeattachments.v1alpha1.storage.k8s.io
error: the server doesn't have a resource type "volumeattachments"

$ k get volumeattachments.v1beta1.storage.k8s.io
No resources found

$ k get volumeattachments.v1.storage.k8s.io
No resources found
```

Then I think we rather mean `remove the types under ./k8s.io/api/storage/v1alpha1`? Do you mean `remove only the VolumeAttachment types under ./k8s.io/api/storage/v1alpha1 or remove all types under ./k8s.io/api/storage/v1alpha1`?

I can try to help with this issue if you give a short answers to the above questions :)

**Comment by pohly** [comment]
My understanding is that in 1.22, we can and should remove all code for these three types under v1alpha1:
https://github.com/kubernetes/kubernetes/blob/50e319767cc4aad5c6ff56a8d002c406cdcc3e0e/staging/src/k8s.io/api/storage/v1alpha1/types.go#L25-L143

**Comment by msau42** [comment]
From https://github.com/kubernetes/kubernetes/pull/101694#issuecomment-831235149, it looks like a mistake to not have removed the v1alpha version when promoting to beta. Now it is only possible to stop serving. If we want to remove, we need to find a way to re-persist any v1alpha objects to v1beta/v1.

We also have this problem with the recent v1beta.StorageCapacity objects too

**Comment by msau42** [comment]
A [controller that updates status on all objects](https://github.com/kubernetes/kubernetes/pull/101694#issuecomment-847844020) would be able to address this.

**Comment by msau42** [comment]
@kubernetes/sig-storage-bugs

**Comment by jingxu97** [comment]
what is the status of this?

**Comment by pohly** [comment]
/reopen

Someone needs to implement https://github.com/kubernetes/kubernetes/issues/99827#issuecomment-848094780

**Comment by ialidzhikov** [comment]
/reopen
/remove-lifecycle rotten

@liggitt @msau42 can add a lifecycle frozen label?

**Comment by ialidzhikov** [comment]
@pohly @msau42 please reopen this issue as it is not fixed (closed by the bot due to inactivity).
