### ISSUE TITLE
kubectl defaults to its pod's namespace

### ISSUE THREAD

**Issue by rittneje** [kubernetes/kubernetes#99884]
#### What happened:

We are using CloudBees Kubernetes agents for our build job. In this job, we launch a container with `kubectl` in it that is configured to talk to a completely different cluster in EKS. It seems that in this situation, `kubectl` is defaulting to the namespace of the pod it is running on (in CloudBees) for all operations, instead of using `default` like it normally would, causing confusion and failures.

I am unable to find any documentation that describes such behavior. Also, there do not appear to be any relevant environment variables that could explain it.

#### What you expected to happen:

I expected `kubectl` to work the same way it always has, using `default` as the default namespace.

#### Environment:
- Kubernetes version (use `kubectl version`): The version of `kubectl` in question is 1.16.15.
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by neolit123** [comment]
> We are using CloudBees Kubernetes agents for our build job. In this job, we launch a container with kubectl in it that is configured to talk to a completely different cluster in EKS. It seems that in this situation, kubectl is defaulting to the namespace of the pod it is running on (in CloudBees) for all operations, instead of using default like it normally would, causing confusion and failures.

this is not a the default kubectl behavior. this could be a custom build of kubectl or maybe there are plugins affecting this.

> CloudBees Kubernetes
> EKS

you are better of asking the service providers, before opening a ticket here.

> The version of kubectl in question is 1.16.15.

this version is out of support, you must verify this with 1.18+.

/close

**Comment by pacoxu** [comment]
https://github.com/kubernetes/kubernetes/blob/8bf42039e62d001f5d0331753bd99790b70d51eb/staging/src/k8s.io/client-go/tools/clientcmd/client_config.go#L579-L584

It may be related with env `POD_NAMESPACE` in your pod. If you want use default namespace, use `-n default`.

**Comment by rittneje** [comment]
> this is not a the default kubectl behavior. this could be a custom build of kubectl or maybe there are plugins affecting this.

No, this is using kubectl downloaded straight from your site. https://storage.googleapis.com/kubernetes-release/release/v1.16.15/bin/linux/amd64/kubectl

> you are better of asking the service providers, before opening a ticket here.

I disagree. If `kubectl` is allowing itself to be influenced by CloudBees, then it is a bug in `kubectl` (or at the very least undocumented behavior).

> this version is out of support, you must verify this with 1.18+.

I have also verified this with `kubectl` v1.18.15. The same bug exists. This was also using `kubectl` downloaded straight from your site. https://storage.googleapis.com/kubernetes-release/release/v1.18.15/bin/linux/amd64/kubectl

> It may be related with env POD_NAMESPACE in your pod. If you want use default namespace, use -n default.

Thanks for the tip, but I checked the environment variables being used within CloudBees, and `POD_NAMESPACE` is not set.

@neolit123 Please re-open this issue.

**Comment by rittneje** [comment]
After turning on verbose logging and digging through the `kubectl` implementation, I have found the source of the issue. Basically, because the `KUBERNETES_SERVICE_HOST` and `KUBERNETES_SERVICE_PORT` env vars are set, and there is a service account file, `kubectl` wrongly assumes that we are doing "inside-kubernetes-cluster" mode. https://github.com/kubernetes/kubernetes/blob/cea1d4e20b4a7886d8ff65f34c6d4f95efcb4742/staging/src/k8s.io/client-go/tools/clientcmd/client_config.go#L593-L599

So I think there a few aspects to this issue:
1. This behavior is not clearly documented.
2. The fact that this is happening is non-obvious unless you explicitly turn on log level 4 or greater.
3. This behavior is flat out wrong when `kubectl` has been configured to point to a cluster other than the one it is actually running on.

**Comment by neolit123** [comment]
ok, leaving the ticket for SIG CLI (owners of kubectl) to triage.

/reopen

**Comment by BenTheElder** [comment]
[I am not from SIG CLI]

Couple notes:
1. See: https://github.com/kubernetes/kubernetes/issues/57601 for the core behavior discussion, automounted service accounts are pretty much required now, it would be a breaking change to remove this by default
2. This can however be disabled at the pod or service account level `automountServiceAccountToken: false` https://kubernetes.io/docs/reference/access-authn-authz/service-accounts-admin/#bound-service-account-token-volume

IMO this is a documentation issue, for example the following:
https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#config should probably cover this.

Documentation is in https://github.com/kubernetes/website, with their own issue tracker.

A general suggestion: Do not rely on default namespaces if you care about the namespace. You can explicitly specify them even if `default` is the intended namespace. `KUBECONFIG` files can also change the current namespace, and unspecified namespaces will become that one instead of "default".

https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/#working-with-namespaces discusses the namespace preference in client configuration ([setting the namespace preference](https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/#setting-the-namespace-preference))

**Comment by liggitt** [comment]
Kubectl use of injected credentials is equivalent to a kubeconfig file using a context that sets the default namespace to the pod's namespace. This is working as intended. 

You can choose a different namespace by passing `-n $namespace` or specifying the namespace explicitly in the manifests being passed to kubectl.

**Comment by rittneje** [comment]
@liggitt The kubeconfig file is something I have proper control over. Silently relying on special environment variables and service account token files is a bad design. If anything, both the use of `POD_NAMESPACE` and this implicit "inside-kubernetes-cluster" mode ought to be removed, and replaced with a clearly purposed environment variable (e.g., `KUBECTL_NAMESPACE`).

I will be filing a bug over on https://github.com/kubernetes/website for the lack of documentation, but as far as I'm concerned this is a complete misfeature of `kubectl` that will likely confuse other people.

**Comment by BenTheElder** [comment]
Er so, the "inside-kubernetes-cluster" logic in `kubectl` comes from using the standard Kubernetes client ([`client-go`](https://github.com/kubernetes/client-go#client-go)), and _many_ things that operate against the cluster intentionally expect this mode (and in particular operating against their current namespace when not specified).

I would suggest that CloudBees ought to really consider inverting the default of `automountServiceAccountCredential` in their CI pods / agents, so that only CI tasks explicitly intended to operate against the current cluster do so. (see https://github.com/kubernetes/test-infra/pull/10103 for our upstream CI "prow" which Jenkins-X used? to use portions of).

These are pretty atypical pods, more common workloads either don't use a Kubernetes client and are unaffected, or intend to operate against the current cluster and desire this behavior. CI workloads probably shouldn't mount credentials for the current cluster in the common case.

It looks like this is possible using the pod template feature https://docs.cloudbees.com/docs/cloudbees-ci/latest/cloud-admin-guide/agents#kubernetes-agents

+1 to improving the documentation.

**Comment by rittneje** [comment]
> I would suggest that CloudBees ought to really consider inverting the default of `automountServiceAccountCredential` in their CI pods / agents, so that only CI tasks explicitly intended to operate against the current cluster do so

Yes, I'm checking with our admin to see if we can set that flag to false universally in either our service account specs or at least our pod specs.
