### ISSUE TITLE
Support Windows on ARM

### ISSUE THREAD

**Issue by rubin55** [kubernetes/kubernetes#99948]
#### What would you like to be added:

Currently kubernetes (and kubectl) run on a host of platforms. Recently, there has been an uptake in ARM based computing devices, most notably Apple's new M1 and Microsoft's Surface Pro X.

It would be great ik K8S would consider Windows on ARM a primary platform and release their binaries (at least kubectl) for this platform.

#### Why is this needed:

Supporting ARM-based devices accross varying operating systems (Linux, macOS, Windows) opens up the platform for new users and developers who will be using ARM based devices today and tomorrow. Making Kubernetes executables available for Windows on ARM brings Kubernetes a little bit more (next to current Linux and macOS efforts) into the ARM world.

**Comment by neolit123** [comment]
one can already try:
```
KUBE_BUILD_PLATFORMS=windows/arm64 make WHAT=cmd/kubectl
KUBE_BUILD_PLATFORMS=windows/arm64 make WHAT=cmd/kubelet
KUBE_BUILD_PLATFORMS=windows/arm64 make WHAT=cmd/kubeadm
```

which would give them ARM64 binaries for Windows if the go toolchain supports it, but i don't think it does?
https://github.com/golang/go/issues/36439

even if Go works, officially supporting windows/arm64 in K8s is difficult.
someone needs to sponsor the hardware and setup for e2e signal, otherwise the support cannot be claimed and the artifacts will remain untested.

related reads about release artifacts:
https://github.com/kubernetes/sig-release/issues/1337
https://docs.google.com/presentation/d/1bctKOljDHwCB6115pphPO3VQ4PiLHcOqYiBA5IXorTE/edit

**Comment by BenTheElder** [comment]
We do have _client_ binaries without testing etc currently (e.g. M1, actually most of them). But lack of go support is a blocker. It looks like it _may_ land in 1.17 but go 1.17 also has some potentially high effort work for us FYI https://github.com/kubernetes/kubernetes/issues/82531

@hasheddan also has work detailing support tiers.

**Comment by BenTheElder** [comment]
@kubernetes/sig-release

**Comment by justaugustus** [comment]
@kubernetes/release-engineering @kubernetes/sig-architecture @kubernetes/sig-windows-leads -- for input
